### ISSUE TITLE
[EN][Druid][Talent] Primal madness report extended

### ISSUE THREAD

**Issue by Vayns** [Atlantiss/BugTracker#10006]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

First bug was posted here: https://github.com/Atlantiss/BugTracker/issues/6267 But there's more to it so it made more sense to make a new report.

**Description**: Currently there's 3 issues with Primal Madness's interaction with tiger's fury, berserk and shapeshifting. Looking for input on number 3.

**Current behaviour**: When shapeshifting out of cat form during **berserk** you keep the Primal Madness buff, this is fine. The problem is you lose the actual energy cap so the buff is only visual.

**Expected behaviour**: You should keep the 120 energy bar as cat even after shapeshifting.
https://youtu.be/WcS9gFfmKF8?t=1m7s

**Steps to reproduce the problem**:

1. Go cat form and pop berserk
2. See you have 120 energy and the primal madness buff
3. Shapeshift and go cat again and see you have the buff but lost the 120 energy cap

-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

**Current behaviour**: When shapeshifting out of cat form during **Tiger's Fury** you keep the Primal Madness buff and only lose Tiger's Fury, this isn't correct and you should lose both. (Right now however it's only visual cuz of the bug above.)

**Expected behaviour**: When shapeshifting during Tiger's Fury you should lose both Tiger's Fury and Primall Madness buffs. 
https://youtu.be/WcS9gFfmKF8?t=7m20s

**Steps to reproduce the problem**:

1. Go cat form and pop Tiger's Fury
2. See you have 120 energy and the primal madness buff
3. Shapeshift out of cat
4. See you lost Tiger's Fury but still have the Primal Madness buff. 

-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

---------------------------------------------**Needs input**--------------------------------------------------
**Current behaviour**: When casting berserk in any form that isn't catform you won't get the Primal Madness buff.

**Expected behaviour**: This is the part I'm not 100% sure about, and proof is hard to find since its an unusual situation. The tooltip says the following: "Tiger's Fury and Berserk also increase your current and maximum Energy by 20 during their durations". 

Following this it would be logical you get Primal Madness in cat form no matter in which form you've casted berserk. The main thing I'm unsure about is whether you get Primal Madness as soon as you cast berserk or once you go into cat form. 

**Steps to reproduce the problem**:

1. Cast Berserk in any form that isn't cat
2. Go cat form
3. See you don't have the Primal Madness buff nor the extra energy

**Revision**: 5745

**Comment by xmesaj2** [comment]
fix in r5748
