### ISSUE TITLE
[PL] Wyrzucanie z instancji po kilkus sekundach

### ISSUE THREAD

**Issue by Dorael22** [Atlantiss/BugTracker#10001]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem ; Wyrzuca mnie z insty po kilku sekundach z wiadomością że, Lokalizacja nie jest prawidłowa i co sprawia ze nie moge sie przeteleportować okiem do insty

**Current behaviour**: What happens - Wyrzuca z insty

**Expected behaviour**: What should happen instead - Powinienem inste zrobić normalnie...

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
nawet nie powiedziałes jaka insta, ani co robiles

**Comment by Dorael22** [comment]
Gdyby to było ważne to bym napisał która insta a tak to ze wszystkich, a co mogłem robić przez 5 sek na inście ? :D Po prostu szedłem za drużyna i nagle kick z insty nie mogę nic napisać na party chat jestem w team wizualnie a fizycznie nie.

**Comment by pelekon** [comment]
Kickneli Cię z grupy, a visual bug faktycznie jest i jakoś jeszcze nie jest naprawiony

**Comment by Dorael22** [comment]
To niezłe typy skoro na max. 900 ludzi na serwerze RDF szuka praktycznie 30 min wywalaja typow by dobralo innych. Mind Fuck, Dzięki za odpowiedź   Problem Solved

**Comment by Piklo** [comment]
chodzi o jakiekolwiek informacje, no fajnie ze cie wyrzucilo z insty, ale co mamy z tym zrobic skoro nic nie wiemy bo nic nie powiedziales
