### ISSUE TITLE
[EN][Talent][Hunter] Point of No Escape  doesn't work

### ISSUE THREAD

**Issue by Vilfernan2** [Atlantiss/BugTracker#10009]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
This talent is not increasing 6% our critical strike chance on targets affected by our ice trap.
**Current behaviour**: What happens

**Expected behaviour**: What should happen instead
This talent provides you with a 6% increased critical strike chance on targets affected by your Ice Trap, and may prove to be a DPS increase on AoE heavy fights.
**Steps to reproduce the problem**:

1. Launch ice trap
2. Once it's active you should increase your critical strikes but nothing happens.
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Frostbreaker** [comment]
Any proof, calculations?

**Comment by MangeNerfedOwl** [comment]
I did test it about 7-10 months ago. It does indeed work on targets that CAN be affected by slow debuffs. It works on trash mobs and dummies, doesn't do shit to bosses what is logical. From my calculations it works fine. It's really minor dps boost on trash mobs not worth taking at all.
