### ISSUE TITLE
[EN][Spell][Druid]Primal Madness interaction with Tiger's Fury

### ISSUE THREAD

**Issue by Vayns** [Atlantiss/BugTracker#10016]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Supposed fix of https://github.com/Atlantiss/BugTracker/issues/10006 only fixed it partially, this bug remains
**Description**: The primal madness buff should be lost once you lose tiger's fury, right now you keep it after shapeshifting.

**Current behaviour**: When shapeshifting out of cat form while having Tiger's Fury up you keep the Primal Madness buff and only lose Tiger's Fury.

**Expected behaviour**: When shapeshifting out of cat both Tiger's Fury and Primal Madness should be lost. https://youtu.be/WcS9gFfmKF8?t=7m20s

**Steps to reproduce the problem**:

1. Go cat > cast Tiger's Fury 
2. Go any other form that isn't cat
3. See that Tiger's Fury is lost but Primal Madness remains

**Revision**: 5750

**Comment by xmesaj2** [comment]
So Primal Madness should be lost with Tiger's Fury but not Berserk right? Or should Tiger's Fury also remain in this case?

**Comment by Vayns** [comment]
Correct.

Primal Madness interaction with Berserk in Cat Form is fine now.
cat form > berserk +primal madness > shapeshift > back to cat > still have primal madness = correct

What I reported here is this
cat form > tiger's fury +primal madness > shapeshift > both buffs should be removed

But what happens right now is
cat form > tiger's fury +primal madness > shapeshift > tiger's fury is removed but primal madness stays

**Comment by xmesaj2** [comment]
will be fixed with rev. 5751
