### ISSUE TITLE
[EN][SPELL][CLASS] Leader of the Pack icd

### ISSUE THREAD

**Issue by MangeNerfedOwl** [Atlantiss/BugTracker#10011]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Leader of the Pack of Feral Druids has too low internal cooldown for the healing proc.

**Current behaviour**: ICD is 4 seconds. Usually I see heal proc after 5 seconds from last one but sometimes even after 4 seconds so I belive that's the ICD we have right now.

**Expected behaviour**: ICD should be 6 seconds according to the talent's description.

**Steps to reproduce the problem**:

1. To make it easier than counting over and over again I reccomand to get an addon that tracks ICDs like ExtraCD that I used.
2. Autoattack target dummy (easier to see on bear form imo)
3. See that heal can proc 1 or 2 seconds before ICD is over.

**Revision**: 5745

**Comment by Vayns** [comment]
Confirming this bug, wasn't able to get a 4sec window but had 5sec multiple times which is already incorrect.

**Comment by Jenovas** [comment]
Fixed
