### ISSUE TITLE
[EN][Spell][Druid]Feral tank t13 4p

### ISSUE THREAD

**Issue by Vayns** [Atlantiss/BugTracker#10013]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Feral t13 4piece is healing 400% of what it should do.

**Current behaviour**: Mass Regeneration (the party/raid buff from t13 4p) is healing for the same amount as Frenzied Regeneration. 

**Expected behaviour**: It should heal only 25% of the Frenzied Regeneration heal. This was 50% originally but got nerfed to 25% in a hotfix. https://worldofwarcraft.com/en-gb/news/3368932
"The Mass Regeneration effect from the druid tier 13 bonus now heals 25% of the healing received by the druid from Frenzied Regeneration, down from 50%. The tooltip will be updated in a later patch."

**Steps to reproduce the problem**:

1. Be a sexy bear for 15 sec. and use frenzied regen to save the raid
2. See that you single handedly actually saved the raid by healing too much
3. Profit

**Revision**: 5745

**Comment by pelekon** [comment]
fixed in 5749
