### ISSUE TITLE
[EN][Spell][Mage] Water Elemental - Freeze 

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1001]
http://cata.openwow.com/spell=31687
http://cata.openwow.com/spell=33395

Water elemental's spell called "Freeze" sometimes misses target while we have hit cap on mage, here is screenshot: http://wstaw.org/m/2014/12/26/WoWScrnShot_122614_210904.jpg
As you can see on combat log - Freeze missed 85 lvl target player while i have over 4% hit cap which should be enough to hit targets in PvP.

And another screenshot: http://wstaw.org/m/2014/12/26/WoWScrnShot_122614_221805.jpg

**Comment by MasterK15** [comment]
Yeah it'ts really anoying in PvP when you need your Proc or Freeze your oponents.

**Comment by Arcadia713** [comment]
In newest rev we have: 
"The Retribution version of Guardian of the Ancient Kings should now benefit from owner's hit and expertise"
Would be possible to add benefits from Mage's hit ratings to his Water Elemental? Or is more complicated?

**Comment by Wolffenstein** [comment]
Fixed in rev 4234.
