### ISSUE TITLE
([EN][Talent][Death Knight] Improved Death Strike)

### ISSUE THREAD

**Issue by alontxf** [Atlantiss/BugTracker#10010]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The talent has three modifications on the spell Death Strike, a damage increase, increased critical srtike chance and a buff on the heal done by it, this last enhancement is the one that isn't working.

**Current behaviour**: Death Strike (at maximum health without receiving any damage) heals for exactly 7% of the maximum health (as shown on the image).

**Expected behaviour**: The heal should be buffed, and instead of healing for 7% health it should be healing for about 10.15% of maximum health.

**Steps to reproduce the problem**:

1. Put 3 points on Improved Death Strike talent
2. Be at maximum health
3. Use Death Strike
4. Check the healing versus your health

**Revision**: rev. 5745
![wowscrnshot_042918_001041](https://user-images.githubusercontent.com/38825753/39403417-0ef969c0-4b52-11e8-8091-84b5c0682a34.jpg)

**Comment by Piklo** [comment]
https://us.battle.net/forums/en/wow/topic/3182449410#post-2

> It does not increase the minimum of 7% of your maximum health.
> It increases the healing you get when you go above the minimum.
