### ISSUE TITLE
[EN][Quest][Darkmoon Faire Island] Putting the carnies back together again

### ISSUE THREAD

**Issue by PrinceArty** [Atlantiss/BugTracker#10026]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest in the Darkmoon Island "Putting The Carnies Back Together Again" It's bugged, and it's not working like it should, it's very abusable and gamebreaking with many options.

**Current behaviour**: The quest item, (Darkmoon Bandage). You use it as an bandage and it heals you to full HEALTH. It can be used on enemy players, yourself, whatever has health in the Dungeons, whatever that has an"Health Bar" and MOST IMPORTANT (IN RAIDS) you can use this to heal anything which is bugged, you're not supposed to be able to use it outside the Darkmoon Island Event. Atm you can use it outside the Darkmoon Island and where ever you want.

**Expected behaviour**: It should only be usable INSIDE the Darkmoon Island and only on this quest npc, nowhere else. Fix it asap cause its gamebreaking.

**Steps to reproduce the problem**:

1. Take the quest from the Npc inside the Darkmoon Island.
2. Target a friendly player or enemy player, or boss npc, and whatever has health.
3. Click on the item and It gives you full health back nomatter what.

**Revision**: 5756

**Comment by Quroo** [comment]
Quest: http://www.wowhead.com/quest=29512/putting-the-carnies-back-together-again
Quest item: http://www.wowhead.com/item=71978/darkmoon-bandage

**Comment by TranceAccount** [comment]
http://www.wowhead.com/npc=54518/injured-carnie

**Comment by xmesaj2** [comment]
5757
