### ISSUE TITLE
[EN][Spell][Paladin] Hand of Sacrifice and Divine Shield

### ISSUE THREAD

**Issue by Katonetwo** [Atlantiss/BugTracker#10024]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hand of Sacrifice damage pierces Divine Shield.

**Current behaviour**: When you use Hand of Sacrifice and Divine Shield, you still take damage when the target of your Hand of Sacrifice takes damage.

**Expected behaviour**: Divine Shield should block all damage.

**Steps to reproduce the problem**:

1.  Cast Hand of Sacrifice on someone who is about to take damage.
2.  Cast Divine Shield.
3.  Watch as you still take damage through Divine Shield.

**Revision**: 5750

**Comment by blinkmaster** [comment]
Wasnt this fixed to work that way a year ago or smth?

**Comment by Katonetwo** [comment]
if this is intended, might aswell let mages continue cauterizing during ice block

**Comment by xmesaj2** [comment]
5770, did not find any references it should not (just that it should since at least wotlk and no changes regarding it later) and the last change was damage cap, some time ago
