### ISSUE TITLE
[EN][Spell][Druid] Resto T13 4 set bonus regrowth bug

### ISSUE THREAD

**Issue by Blurview** [Atlantiss/BugTracker#10022]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When using the 4 set pieces for T13 restoration Regrowth sometimes doubles the duration of Rejuvenation, making it possible to last for hours and days, instead of timeslipping itself.

**Current behaviour**: Rejuvenation's duration is sometimes doubled by Regrowth using the T13 4 set bonus.

**Expected behaviour**: Regrowth should only be able to timeslip(which it doesn't) and not double Rejuvenation's duration.

**Steps to reproduce the problem**:

1. Equip 4 T13 restoration set pieces
2. Cast Rejuvenation
3. Spam Regrowth

**Revision**: 5750

**Comment by phanttom** [comment]
true fix that little tiny thing and Gift of the earthmother that is still same in 4 set which means 16000 intellect Loss  ;)

**Comment by Katonetwo** [comment]
pretty much confirmed

5 minutes
![wowscrnshot_050418_121355](https://user-images.githubusercontent.com/32794643/39623877-5fe0afe4-4f97-11e8-8613-f8ae6ff0a9ca.jpg)
8 minutes
![wowscrnshot_050418_121450](https://user-images.githubusercontent.com/32794643/39623918-885050e2-4f97-11e8-88b1-2b1c2b9f3cc3.jpg)
*fast forward*
16 days
![wowscrnshot_050418_122235](https://user-images.githubusercontent.com/32794643/39623941-9f1d5892-4f97-11e8-9e07-fb1bd471805d.jpg)

and after that it starts overflowing and resetting the timer

**Comment by xmesaj2** [comment]
rev. 5751
