### ISSUE TITLE
[EN][Event]Darkmoon Faire

### ISSUE THREAD

**Issue by Llagas** [Atlantiss/BugTracker#10029]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Some quests are missing from the faire. 

**Current behaviour**: 
A few dailies from the games are missing: 
http://www.wowhead.com/quest=29463/its-hammer-time
http://www.wowhead.com/quest=29436/the-humanoid-cannonball
http://www.wowhead.com/quest=29438/he-shoots-he-scores
We can do the games but we cannot complete the dailies for thoses 3 games, therefore we cannot get the "step Right Up" achievement http://www.wowhead.com/achievement=6020/step-right-up

Also a monthly quest is missing: http://www.wowhead.com/quest=29433/test-your-strength that should be given by the NPC Kerri Hicks http://www.wowhead.com/npc=14832/kerri-hicks

And the achievement "Blastenheimer Bullseye" cannot be achieved even if you hit the middle of the target. http://www.wowhead.com/achievement=6021/blastenheimer-bullseye

**Expected behaviour**: Everyone should be able to get and complete all theses quests and achievements. 

**Steps to reproduce the problem**: 
1. Go to the Darkmoon Faire 
2. See that the quests are missing 
3. Try the cannon game and land in the middle of the target. 

**Revision**: rev. 5757

**Comment by Llagas** [comment]
By the way i just wanted to thank you for scripting the darkmoon faire that well, it is very enjoyable and there are only thoses few issues that remain.

**Comment by xmesaj2** [comment]
rev. 5764
