### ISSUE TITLE
[EN][Item] Elementium-coated Geode

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10030]
**Description**: Elementium-coated Geode (item ID 78891)("Geode" in the following) does not drop the correct gems. 

**Current behaviour**: Geode drops epic gems of every colour (red, orange, yellow, green, blue, purple) 
https://imgur.com/8hMgY3q <-- 400 gems opened on PTR -- thanks to Ido for commenting these. 

**Expected behaviour**: Geode should only drop red, orange, and purple epic gems. 
See the item's tooltip. https://imgur.com/IEeBAyZ

**Steps to reproduce the problem**:

1. Go on PTR (optional but helpful) 
2. Give yourself a *lot* of Geodes. Open them.  
3. See you will not only receive red, orange, or purple epic gems. 

**Revision**: 5768

**Comment by idohealz** [comment]
Just for additional proof of current behavior, 400 of the gems on PTR gave me this spread of gems
https://imgur.com/a/yDkxf4P

**Comment by TranceAccount** [comment]
www.wowhead.com/item=78891/elementium-coated-geode
