### ISSUE TITLE
[EN][Item] gurthalak-voice-of-the-deeps summon creature doesn't work properly

### ISSUE THREAD

**Issue by jerry313git** [Atlantiss/BugTracker#10031]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
        gurthalak-voice-of-the-deeps(item ID:77191) summon creature doesn't work properly
        item link:http://www.wowhead.com/item=77191/gurthalak-voice-of-the-deeps
        the item can correctly summon Tentacle of the Old Ones,but  Tentacles dont do any damage.
**Current behaviour**: What happens
       the item can correctly summon Tentacle of the Old Ones,but  Tentacles dont do any damage.
**Expected behaviour**: What should happen instead
       summoned Tentacles can do damage.
**Steps to reproduce the problem**:

1. equip the item
2. hit any mobs
3. view the Tentacles behavier and check damage record

**Revision**:5768

**Comment by MangeNerfedOwl** [comment]
Please, when you fix it don't forget about slow from channeled spells and avoidence for aoe.

**Comment by Elannreportujerzeczy** [comment]
and the tentacles should be a bit bigger xD

**Comment by Elannreportujerzeczy** [comment]
Gurthalack doesn't proc on arenas

**Comment by Elannreportujerzeczy** [comment]
bump, Gurthalak still doesn't work on arenas and vs bosses its attacks are immune

**Comment by Piklo** [comment]
Gurthalak should be working on arenas in [rev5782](https://atlantiss.eu/changelog#rev5782) (not mentioned in changelog)

**Comment by pelekon** [comment]
Fixed in 5783

**Comment by Piklo** [comment]
more changes to Gurthalak [rev5786](https://atlantiss.eu/changelog#rev5786)
