### ISSUE TITLE
[EN][Raid][Dragon Soul] Madness of Deathwing loot and achivement bug

### ISSUE THREAD

**Issue by Olrios** [Atlantiss/BugTracker#10034]
**Description**:
Problem with loot, gem and achivement

**Current behaviour**:
Boss doesn't give achivement and gem item.

ALSO sometimes there is no loot at all from boss, item where loot should be doesn't spawn. Only Thrall and portals appears. Boss is dead, but raid id shows Madness is available. All players have combat bug and there's no way to start encounter again, you cannot talk to Thrall, so this is not a reset bug.

**Expected behaviour**:
Fix loot, gem and achiv

**Steps to reproduce the problem**:

1. kill madness of deathwing
2. enjoy no loot, gem, achi and free combat bug

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by pelekon** [comment]
Fixed in rev  5774
