### ISSUE TITLE
[EN][Raid][Dragon Soul] Madness of Deathwing 2nd phase hitbox problem

### ISSUE THREAD

**Issue by Olrios** [Atlantiss/BugTracker#10033]
**Description**: 
**Current behaviour**:
Skills like Thunder Clap, Blood Boil, Dragon's Breath, Water Elemental's Freeze etc doesn't works on Deathwing's head during 2nd phase of Madness of Deathwing.

**Expected behaviour**: 
Fix hitboxes for 2nd phase and skills should work normally.

**Steps to reproduce the problem**:

1. enter 2nd phase madness deathwing
2. use any aoe skill listed above

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by pelekon** [comment]
Fixed in rev 5774
