### ISSUE TITLE
[EN][Raid][Dragon Soul] Madness of Deathwing boss reset bug +TEMP FIX

### ISSUE THREAD

**Issue by Olrios** [Atlantiss/BugTracker#10032]
**Description**:
**Current behaviour**:
During 2nd phase Deathwing is targeting a random player. Whenever you taunt a boss during 2nd phase, all fight will reset. Boss will disappear, leaving all players with combat bug. Only Thrall appears to start everything from the beginning. Whenever you start encounter from beginning all boss' timers will be broken. Even boss can cast Cataclysm instantly. Temp fix - players have to leave and reset instance and tank cannot taunt boss head during 2nd phase.

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. enter 2nd phase madness deathwing with few players
2. taunt boss
3. start over

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by pelekon** [comment]
Fixed in rev 5774
