### ISSUE TITLE
[EN][Classic][Item] Thunderfury, Blessed Blade of the Windseeker

### ISSUE THREAD

**Issue by henkka90** [Atlantiss/BugTracker#10040]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When attacking with the Thunderfury, it should have a chance to proc, however the proc isen't working.

**Current behaviour**: Attacking with the Thunderfury doesn't proc the weapon at all.

**Expected behaviour**: Attacking with Thunderfury, it should have a chance to proc on hit.

Addional information:

- https://db.rising-gods.de/?spell=27648#triggered-by
- https://db.rising-gods.de/?spell=21992
- http://www.wowhead.com/spell=21992/thunderfury#changelog

**Steps to reproduce the problem**:

1. Equip Thunderfury, Blessed Blade of the Windfury
2. Attack mobs with it
3. See that the proc doesn't work

**Revision**: 5771

**Comment by Piklo** [comment]
duplicate #8171

**Comment by henkka90** [comment]
It doesn't have the right template, nor the exact title for items,that one should be closed and the one with the proper template should remain open.

**Comment by henkka90** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
