### ISSUE TITLE
[EN][Talent][Spell][Rogue][Bandit's Guile][Redirect]

### ISSUE THREAD

**Issue by vule456** [Atlantiss/BugTracker#10043]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Bandit's Guile's Insight progress does not properly transfer to the target you use redirect on while in combat spec only the combo points.

**Current behaviour**: You press redirect and the current insight does not transfer it stays on the previous target while the combo points transfer properly, the insight will run out or if you get 4 sucessive hits with sinister strike and revealing strike the insight will refresh and start from green again.

**Expected behaviour**: The Insight (Green, Yellow or Red) progress from the current target should switch to the target you use redirect on only if you are transfering combo points as well. Note redirect should not transfer Insight progress without combo points on your current target.

**Steps to reproduce the problem**:

1. Enagge 2 mobs
2. Build combo points on 1 of them and get to yellow insight at least
3. Use redirect on the second one
4. Combo points transfered but Insight will stay on previosu target and run out.

**Revision**: 5771

**Comment by wtRCH** [comment]
I might sound stupid but this is completaly wrong. From what I understood Redirect should only transfer combo points from redirected target to current redirect target. Insight should stay on the previous target and not be transfered as Redirect is ability which transfers combo points only. If you find it wrong, please provide proofs @vule456 

Closing.
