### ISSUE TITLE
[EN][Item] Heart of Unliving

### ISSUE THREAD

**Issue by Quroo** [Atlantiss/BugTracker#10045]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
[Heart of Unliving 1.xlsx](https://github.com/Atlantiss/BugTracker/files/1998973/Heart.of.Unliving.1.xlsx) (Tested for priest and paladin for now)

**Description**: Heart of Unliving procs are incorrect. Some spells should proc, some should not do it.

**Current behaviour**: Attached some sheets for easier check and not to spam the bugtracker with reports for each spell.

**Expected behaviour**: It is not specified direct healing spells in the trinket description but it does proc only from direct spells. (Proofs in sheet)

**Steps to reproduce the problem**:

1. Get Heart of Unliving.
2. Start casting spells.
3. Check which spell procs and which does not.

**Revision**: 5775

**Comment by mluc90** [comment]
I does not proc on any HoT-Apply from a Restodruid on Atlantiss right now. As you can see in this [](https://www.youtube.com/watch?v=GXUAjJ3b2Ko&t=24) the stacks at 0:26 jump from 6 to 10 with one Wild Growth apply. You can also find this behaviour described in wowhead comments [](http://de.wowhead.com/item=77199/herz-der-leblosen#english-comments), comment 3 - 0. This is a major drawback for HoT-Healing with this Trinket right now...

**Comment by MangeNerfedOwl** [comment]
While hot applyiing bug is major problem the trinket is supposed to get stacks from every single direct heal. Healing rain grants stacks from every tick but Swiftmend ticks do not. I don't know about Holy Ward Sanctuary.

**Comment by Piklo** [comment]
small corrections in [rev5814](https://atlantiss.eu/changelog#rev5814)

**Comment by Piklo** [comment]
more changes in [rev5817](https://atlantiss.eu/changelog#rev5817), some of them are not mentioned in changelog
