### ISSUE TITLE
[EN][NPC] Southsea Strongarm

### ISSUE THREAD

**Issue by Hartwall** [Atlantiss/BugTracker#10059]
**Description**: Describe the problem

In Lost Rigger Cove after killing pirates the other mobs around are not spawning fast. Makes farming steamwheedle cartel reputation ass to wait for respawns.
Mob IDs; 7858, 40593, 7855, 40635, 40632, 40632

**Current behaviour**: What happens

Killing southsea pirates, musketeers, strongarms or other pirates in the cove doesnt make the surrounding pirates to respawn in bulk.

**Expected behaviour**: What should happen instead

The mobs in lost rigger cove should be respawning after the others are killed; 

source:
https://youtu.be/EmScvZqjB7I?t=26
http://www.wowhead.com/npc=40593/southsea-taskmaster#comments:id=1186777:reply=254918
http://www.wowhead.com/faction=369/gadgetzan#comments:id=1530656

**Steps to reproduce the problem**:

1. Kill pirates in Lost Rigger Cove in tanaris
2. See if mobs respawn
3. cry

**Revision**: ACore rev. 5784 hash. 92c6ffc69dda 2018-05-18 09:31:26 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
this is called dynamic respawn system, so its more like core thing than one npc related
