### ISSUE TITLE
[PL][Dragon Soul][Madness of Deathwing]Madness of Deathwing 2 phase bug

### ISSUE THREAD

**Issue by strusiek9** [Atlantiss/BugTracker#10053]
**Description**: 

Podczas rozpoczęcia fazy 2 Madness posiada 27% hp gdzie powinien zaczynać z 20% hp tak jak przedstawia to Dungeon Journal, wowhead i wiele innych źródeł. Jest to problematyczne, gdyż faza 2 trwa o połowę za długo co prowadzi do wielu wipe.

**Current behaviour**: 

Podczas rozpoczęcia fazy 2 Madness zaczyna z 27% HP

**Expected behaviour**:

Podczas rozpoczęcia fazy 2 Madness powinien zaczynać z 20% HP

http://www.wowhead.com/npc=56173/deathwing#encounter
Stage Two: The Last Stand
At 20% remaining health, Deathwing falls forward onto the platform.

**Steps to reproduce the problem**:

1. Rozpocząć walkę z Madness of Deathwing w trybie 10 man normal ;
2. Dotrwać do rozpoczęcia fazy 2 ;
3. Zobaczyć ilość HP Bosa .

**Revision**: 5779

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/10044

**Comment by pelekon** [comment]
Fixed in rev 5858.
