### ISSUE TITLE
[//]: # ([EN][CHARACTER INTERFACE]

### ISSUE THREAD

**Issue by Vilfernan2** [Atlantiss/BugTracker#10050]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
hi, On my account I have 4 characters, between them is Xzolotl. I have a problem with the interface that don't allow me to use my secundary professions. I can see only Alchemy 525/525 and can't see Herbalism. Besides, I can't see Fishing (may be 450 can't remember) wich I used with a macro that I found on the internet and can't use archeology (1/525) both of them are "invisible" on the professions interface. If I look my others characters on the account ther isn't such a problem.

**Current behaviour**: What happens
As you can see on the picture there are not visible professions in the interface.
![12](https://user-images.githubusercontent.com/38261449/40059697-c5b1d3a0-5822-11e8-953a-b4ebe60396e1.png)

**Expected behaviour**: What should happen instead
I should see my interface like the picture.
![13](https://user-images.githubusercontent.com/38261449/40059745-e8934f34-5822-11e8-9c63-14c4abe690e2.png)

Thanks for the help.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Katonetwo** [comment]
have you tried using /reload

**Comment by pelekon** [comment]
BT is not proper place for such things

**Comment by Vilfernan2** [comment]
Good answer to that...may be you can suggest something....but thanks anyway

**Comment by Piklo** [comment]
delete cache or rename WTF and disable addons
