### ISSUE TITLE
[EN][Priest][Item] Will of Unbinding

### ISSUE THREAD

**Issue by Chanji2018** [Atlantiss/BugTracker#10056]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Will of the Unbinding doesnt stack while applying Priest DoTs.

**Current behaviour**: Will of the Unbinding doesnt stack while applying Priest DoTs, such as Vampiric Touch, Devouring Plague, Shadow Word: Pain and Mind Flay. It only stacks up by using direct damage spells such as Mind Blast, Mind Spike, Shadow Word: Death (for Shadow). 

**Expected behaviour**: Normally, each time a DoT and Mind Flay is casted on the target, it should apply 1 stack of the trinket. And only on cast, not on every tick of the DoT.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Psychobird7** [comment]
This is not a priest-specific issue, you did not include any evidence of expected behaviour, and did not follow the template.  

/voteforclose.

**Comment by firemagegodx** [comment]
https://www.youtube.com/watch?v=xAAGUWve3N0&feature=youtu.be
Here's how it stacks on ATS. Greek internet is shitty so I recorded for him instead. 
The revision is 5784.

Battle.net:
"FYI to any shadow priests that are eyeballing this:

It does NOT stack per DoT tick. So if you cast Shadow Word: Pain, Mind Flay, Devouring Plague, or Vampiric Touch, you will only gain 1 stack.

It will however stack per HIT if you Mind Sear. Which is to say, if you Mind Sear 3 targets, you will get 3 stacks per tick of Mind Sear.

I hope this gets fixed, as the ramp-up time for Shadow is further impeded by having to either cut Mind Flay ticks a lot to stack it, or sit and Mind Sear."

**Comment by Psychobird7** [comment]
Already made a proper report. 
https://github.com/Atlantiss/BugTracker/issues/10058 
You can close this.
