### ISSUE TITLE
[PL][Other] Equipment Manager

### ISSUE THREAD

**Issue by KrolServera** [Atlantiss/BugTracker#1005]
Equipment Manager często się buguje, wyskakuje "you can't do it right now" poza combatem ect.

**Comment by jurek1** [comment]
nie buguje , tylko jest zbugowany ,  jak tworze nowy set  , po relogu juz go nie ma ( brak zapisu ).
dziala dobrze jedynie ten set ,ktory byl stworzony przed wprowadzeniem patcha 4.3.4

**Comment by Varchord** [comment]
No nie działa ten EQ menadżer biedny. setów nie zapisuje.

**Comment by Arcadia713** [comment]
Polecam Outfitter do czasu naprawy.

**Comment by ShockRW** [comment]
BUMP

**Comment by XrayAlert05** [comment]
EM jest zwyczajnie bugnięty, Jak zapiszę itemy w jednej ikonce na Arms to jest okej, ale po zrobieniu drugiej ikonki na Prot i zapisaniu itemów do tankowania, po kliknięciu w tę ikonę resetuje się i wyskakują mi itemki w Arms..
