### ISSUE TITLE
[EN][Item][Gurthalak, Voice of the Deeps]

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#10066]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Gurthalak tentacle procs have too mutch hp currently around 90k.
Also the tentacle when spawned should attack the closest target and can spawn nearby 10 yards of the sword holder. 
**Current behaviour**: What happens
Tentacle has around 90k hp pool.
Tentacle attacking main target only of the sword owner.
**Expected behaviour**: What should happen instead
Tentacle should have 15-20k hp
Should random spawn and attack closest target.
**Steps to reproduce the problem**:

1. Proc tentacle check hp
2. Proc tentacle check spawns points of it in yards
3. Proc tentacle check that it hits always mostly main target.

Sources proofs:
https://www.youtube.com/watch?v=6zyrTlaDs-E&t=348s
Retail Famouse warrior Klindaz.
Check 2:00 min tentacle proc hitting pet instead of main target priest.
Check 2:25 min tentacle proccing pretty nice yards away and attacking shadow priest.
Check 4:40 min tentacle hitting paladin instead of main target.
Check 13:58 min tentacle killing first other 2 tentacles near him then nuking main target also notice that the tentacles are getting one shotted by getting hit by 17k dmg meaning that the tentacles have less pool than 17k.
Link where the guy tells about tentacle hitting on 40 yards range max and that it has 15k Hp.
https://gaming.stackexchange.com/questions/77717/in-pvp-how-should-i-respond-to-the-tentacle-proc-from-gurthalak.
You can aswell overall check whole video for more infos about tentacle.
https://www.youtube.com/watch?v=sQ-y4NaLn7I    1:04 min check hp pool of tentacle.
Revision:5784
**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
should be fixed in [rev5793](https://atlantiss.eu/changelog#rev5793), forget to close
