### ISSUE TITLE
[EN][Item] Trinkets: follow-up to 9822 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10065]
**Description**: This is a followup to #9822.  

**Current behaviour**: Rev 5788 (https://atlantiss.eu/changelog#rev5788) will make every trinket have a 30s CD upon equipping it. 
This is incorrect. 

**Expected behaviour**: **Only trinkets with procs should trigger a CD.**  
Stacking trinkets like the Spine of Deathwing trinkets or Vessel of Acceleration should not go on CD. 

https://www.youtube.com/watch?v=sy0NP3rlZho 
The above features Landsoul executing a prepull manoeuvre as Fury. 
In doing so, he equips Moonwell Chalice, casts Death Wish, and subsequently re-equips Vessel of Acceleration, as can be seen on his trinket bar. (it is located just below the Horn of Winter icon+timer) 
Soon after the pull happens, he crits and gains a stack of Accelerated (procced by Vessel of Acceleration). 

https://www.youtube.com/watch?v=v7evz194SEo 
The above features a random Fury warrior executing a similar prepull. 
It is not *entirely* clear which trinkets he uses/equips, however it can clearly be seen that Creche of the Final Dragon procs ~10s into the fight, which would not be possible had he swapped Creche while prepulling. 
This means he *must* have swapped Eye of Unmaking in doing the prepull, and therefore that EoU did not trigger a CD when he equipped it.  

List of level 85 trinkets that should be exempt from the CD rule (***incomplete***)
Eye of Unmaking (**confirmed**: see video), License to Slay, Wrath of Unchaining, Fluid Death, Heart of Unliving, Darkmoon Card: Tsunami, Will of Unbinding, Vessel of Acceleration (**confirmed**: see video), Apparatus of Khaz'goroth (Titanic Power generation only), Necromantic Focus, Jar of Ancient Remedies.  

**Steps to reproduce the problem**:
Not live yet. 

**Revision**: 5784 (bug will only appear with 5788)

**Comment by Psychobird7** [comment]
As mentioned, the list of trinkets that should be exempt from the CD-on-equip rule is incomplete, and I would welcome additions ***with evidence of expected behaviour.***

**Comment by Mizune-kun** [comment]
https://www.mmo-champion.com/threads/1120365-Warlock-Tips-and-Tricks-and-Specific-Encounter-Guides-4-3

Sounds like Cunning of the Cruel shouldn't go on 30s ICD as well, considering what's written in "Gear Swapping" section.

**Comment by Psychobird7** [comment]
Cunning definitely does have an ICD, although it is possible that only trinkets with ICDs longer than 30s actually trigger a 30s CD when equipped, and that trinkets with ICDs shorter go on their actual ICD.  

Which could certainly make sense, and the way it is worded in the guide makes it sound like a possibility.  
("for similar reasons")

**Comment by pelekon** [comment]
Fixed in rev 5790, if some trinkets shouldnt be affected by equip ICD just create new report.

**Comment by Psychobird7** [comment]
Will do, ty <3
