### ISSUE TITLE
[EN][Warlock] Summon Doomguard 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10069]
**Description**: Doomguards (DG) have a few major issues, specifically with the SP it inherits from the warlock who summons it. 
DG is meant to inherit a percentage of the warlock's Spell power (SP), as well as benefit from Demonology's mastery. 

**Current behaviour**: 
Doomguards seem to inherit the wrong amount of SP from the warlock, which causes them to deal far too much damage. Based on testing done on the PTR, DG inherits 100% of the warlock's SP. 
They do however appear to use the correct multipliers from Mastery and everything else. 

This can be observed by analysing any log recorded on the server, and comparing DG's damage with a top ranked log. This report will use a high ranked Destruction log for further calculations. 
http://www.worldoflogs.com/reports/rt-3hkfcpsna3fc89e1/sum/damageDone/?s=3875&e=4107 

**Expected behaviour**: 
**Based on analysis from Simcraft and comparison with logs, DG should inherit 53.11% of the Warlock's SP.** 
-- **Aloise's research shows DG to inherit 50% of the owner's SP.** 
It is also worth noting that DG should not benefit from **any** damage multipliers other than Demonology's mastery. 

Simcraft shows Doom bolt's (ID 85692) damage being calculated as follows: 
DOOM BOLT 
direct_power_mod: 1.360000  -- Doomguard's SP 
base_dd_min: 1200.42 
base_dd_max: 1340.15 

To calculate Warlock SP contribution to DG Doombolt damage, several profiles using T13H BiS gear (while removing *all* procs/stacking) were ran over 100k iterations. 
The profiles were then overridden to add a flat 10000 SP to the warlock, and the results used to determine DG's inherited SP. 
Below are the results from those simulations. 

**RAID BUFFS ENABLED**: 10% SP, 8% magic, 5% orc racial 
The 10% SP buff was enabled to facilitate comparison with the Demo profile. This means +10000 SP becomes +11000, **and will be accounted for**. 

**Affliction** 
Doom bolt damage: 
+10k SP: 21309; normal SP: 12298 --> diff=9011 

Remove CoE/racial multiplier: 
9011/1.08=8344 
9011/1.08/1.05=7946

+10k SP --> 7946 Doombolt increase 

**Destruction**
Doom bolt damage: 
+10k SP: 21309; normal SP: 12298 --> diff=9011 

Remove CoE multiplier: 
9011/1.08=8344 
9011/1.08/1.05=7946 

+10k SP --> 7946 Doombolt increase 

**Demo** -- 1979 Mastery (1.43788 multiplier)  -- also calculated with with +1000 Mastery 
Doom bolt damage: 
+10k SP: 36624; normal SP: 20943 --> diff=15681 

W/O Mastery multiplier: 
+10k SP: 25471; normal SP: 14565 --> diff=10906 

Remove CoE/racial multiplier: 
10906/1.08= 10098 
10906/1.08/1.05= 9617 

10k SP --> 9617 Doombolt increase  -- damage appears to be 21% higher than affli/destro; ***this could not be confirmed via logs, so until a source can be found on what is causing it, it should be disregarded.*** 

11000 SP increased Doom Bolt's damage by 7946. This means DG inherited the following SP. 
7946/1.36=5843 
5843/11000=0.531182 

**Therefore, DG inherited 53.11% of the Warlock's SP.** 

This can be confirmed using the above-mentioned logs. and using DG damage to calculate the SP the warlocks snapshotted from. The numbers will be very close to correct. 

For completeness, I will include this analysis here. It will only use Destruction logs as Demo's mastery multiplier is impossible to determine based on a log. 

The following log will be used. 
http://www.worldoflogs.com/reports/rt-3hkfcpsna3fc89e1/sum/damageDone/?s=3875&e=4107 
http://www.worldoflogs.com/reports/rt-3hkfcpsna3fc89e1/details/12/?s=3875&e=4107 
http://www.worldoflogs.com/reports/rt-3hkfcpsna3fc89e1/details/78/?s=3875&e=4107 

This warlock's DG shows 14715.4 as the average Doombolt damage. 

Using the coefficients calculated earlier, and removing the buffs/debuffs as shown earlier, it can be determined that this warlock snapshotted a 16987 SP DG. A realistic number, considering they only had Volcanic power up at the time. 

**Steps to reproduce the problem**:

1. Use DG on any boss fight on Atlantiss 
2. Note its damage 
3. Compare your DG's damage to a simulation, or log. 

**Revision**: 5784

**Comment by Psychobird7** [comment]
I am by no means a warlock expert so if anyone can explain the unexplained 21% DG damage increase on Simcraft, I'd welcome some information. 

Apart from that, please do let me know if my math is flawed so that I can fix it asap.

**Comment by Aloise3** [comment]
You beat me to it. I’ll go and look through it again to figure out what is causing the unexplained damage Demo.

A look at the code would be enough to determine the inheritance:

virtual double composite_spell_power( const school_type school ) const
  {
    double sp = pet_t::composite_spell_power( school );
    sp += owner -> composite_spell_power( school ) * ( level / 80.0 ) * 0.5 * owner -> composite_spell_power_multiplier();
    return sp;
  }

Taken from the sc_pet file.

**Comment by Aloise3** [comment]
Furthermore, could it be possible the unexplained increase can be explained by Demonic Pact? As far as I know the Doomguard should also provide it's own Demonic Pact allowing it to double dip from it.

**Comment by Psychobird7** [comment]
The 1.36 coefficient that I used was taken from sc_warlock.cpp.  
It lists the following; https://pastebin.com/Bn7PVpEW 
"//Rough numbers based on report in EJ thread 2011/07/04
      direct_power_mod  = 1.36;
      base_dd_min *= 1.25;
      base_dd_max *= 1.25; "

These numbers differ slightly from the ones you listed. Looks like someone was a little lazy while testing.   

As for the Demonic pact double dipping, from what I was able to research, DG should only cast its own Demonic pact is there isn't already one active from another pet.  
This can be confirmed by looking through logs, not all DGs will have a Demonic pact on them. 
http://www.worldoflogs.com/reports/rt-84bxecnswnuwsstf/sum/damageDone/?s=2877&e=3094 -- Soulja's DG does cast a Demonic Pact, but Soulja did not have his own pet's Demonic pact on himself (he had an Ele shaman's Totemic wrath the entire time). 
http://www.worldoflogs.com/reports/rt-2dzuo5ogsofd8tos/sum/damageDone/?s=6898&e=7058 -- Shendoah's does, Lazzoo's doesn't.  

I *have* considered the possibility, since 1.1*1.1=1.21. This difference would almost match the numbers observed on Simcraft, but is not reflected in retail logs. 
The most likely behaviour would be that DG casts its own Demonic pact, and does benefit from it. 
The thing is, if a warlock had Totemic Wrath, and not their own Demonic Pact, the DG casting its own Pact would only increase the overall damage by 10%. 
For a 21% difference to appear, it would require a 3rd Demonic pact to be present, which is not possible.

**Comment by kadi2** [comment]
Not really, every warlock pet had to cast its own buff on themselves. There are buffs in the game that cannot be cast on other pets. You cannot also see some auras being applied when you summon a fresh pet in combat log (worldoflogs) which Demonic Pact and Embrace of the Shale Spider for example. So yeah Double Dipping was a thing every single time.

**Comment by klm670** [comment]
Also, the spell cast from the Doomguard, has a 20% dmg increase on targets below 20% health.
Currently can't find the old spell being cast by it, only the new version of legion, that doesn't have the execute.

**Comment by Psychobird7** [comment]
Kadi: What exactly are you trying to say? 
I can see the uptimes, but you can also clearly see the Felhunter is only getting one of the buffs. Which means if the warlock also had one, it would only have been 2 buffs, not 3. 
Which would only amount to a 10% increase, not 21%. 
You also looked at the wrong pet, DG only ever had its own Demonic Pact. 

Klm: No. The execute mechanic was added in 5.0. 
http://www.wowhead.com/spell=85692/doom-bolt#changelog 
Hover over 4.2.0, then hover over 5.0.1.

**Comment by klm670** [comment]
I remember it actually having an execute on retail too. Will have to look up some footage with MSBT or parrot.

**Comment by Aloise3** [comment]
To Klm.
First of all Legion doom Bolt got an Execute.
Second: According to WoWHead tooltips the Execute was added in MoP.

**Comment by lostmyusername** [comment]
that execute was put in with 5.0.1.

im just curious: weve got 2 big demo-lock logs from ultrax 25H.
http://www.worldoflogs.com/reports/rt-84bxecnswnuwsstf/details/41/?s=2877&e=3094
http://worldoflogs.com/reports/rt-2dzuo5ogsofd8tos/details/1/?s=6898&e=7058

first one was the log, you posted up there (best demo-dps ultrax 25H). Doomguard hits for 30k noncrit, when he pulled it with ONLY synapse-springs as spell-/intellect-proc, if i see that correctly. It has 27 Doom Bolts=81 secs cast-time.

second one is the second best log from a demo-lock at ultrax 25H. his doomguard hits for about 24.7k noncrit, when he snapshotted it with potion, lightweave, power torrent and 4p t13.  IT HAS 34 Doom Bolts, which would be a cast-time of 102 seconds.

i assume, both warlocks have almost the same gear = same spellpower raidbuffed (both didnt use their doomguard prefight with some trinket-procs). doublecheck the procs pls, if you can.

dates of the logs are 3rd July 2011 and 25th July 2012

i am seriously confused.

**Comment by Psychobird7** [comment]
These logs are both of 2012, as Ultraxion was not released in july 2011.  

The reason for Shendoah's DG casting more Bolts than Soulja's is Insignia's proc. DG seems to inherit some of the warlock's haste ***rating.*** 
How much, I do not know, but it is a thing. So that would explain the larger number of casts.

**Comment by Aloise3** [comment]
Doomguard does not scale with haste rating.

**Comment by Aloise3** [comment]
@lostmyusername, the wowhead comment is from 4.2, where there was a bug that allowed doomguard to benefit 3 times as much from Mastery. It got fixed in 4.3 patch notes.

**Comment by Jenovas** [comment]
Rev 5801 - Fixed
