### ISSUE TITLE
[EN][Quest][Event]Darkmoon Faire

### ISSUE THREAD

**Issue by Llagas** [Atlantiss/BugTracker#10078]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Some quest are suppose to be repeatable monthly but if you complete them once, you can't see them anymore the next month. 

**Current behaviour**: I completed the quests last month and they don't appear anymore this month. 
The quests are: http://www.wowhead.com/quest=29433/test-your-strength 

And the profession quests: 
- alchemy http://www.wowhead.com/quest=29506/a-fizzy-fusion
- blacksmithing http://www.wowhead.com/quest=29508/baby-needs-two-pair-of-shoes
- enchanting http://www.wowhead.com/quest=29510/putting-trash-to-good-use
- engineering http://www.wowhead.com/quest=29511/talkin-tonks
- herbalism http://www.wowhead.com/quest=29514/herbs-for-healing
- inscription http://www.wowhead.com/quest=29515/writing-the-future
- jewelcrafting http://www.wowhead.com/quest=29516/keeping-the-faire-sparkling
- leatherworking http://www.wowhead.com/quest=29517/eyes-on-the-prizes
- mining http://www.wowhead.com/quest=29518/rearm-reuse-recycle
- skinning http://www.wowhead.com/quest=29519/tan-my-hide
- tailoring http://www.wowhead.com/quest=29520/banners-banners-everywhere
- archaeology http://www.wowhead.com/quest=29507/fun-for-the-little-ones
- cooking http://www.wowhead.com/quest=29509/putting-the-crunch-in-the-frog
- first aid http://www.wowhead.com/quest=29512/putting-the-carnies-back-together-again
- fishing http://www.wowhead.com/quest=29513/spoilin-for-salty-sea-dogs

Also, i couldn't take the quest this month from http://www.wowhead.com/item=71636/monstrous-egg 

**Expected behaviour**: All those quests are suppose to be monthly repeatable. 

**Steps to reproduce the problem**:

1. Complete theses quests. 
2. Come back the next month when darkmoon faire is up. 
3. See that none of those are available to you. 

**Revision**: 5792

**Comment by Pieczyyea** [comment]
Looks like no fix for this month Darkmoon :-(

**Comment by TranceAccount** [comment]
Entry array: 29433, 29506, 29507, 29508, 29509, 29510, 29511, 29512, 29513, 29514, 29515, 29516, 29517, 29518, 29519, 29520

**Comment by Hartwall** [comment]
To add to this, the daily quests dont appear every day. I only got 2 quests today when it should be all 5 daily quests every day.

**Comment by Piklo** [comment]
should be fixed in rev. 5919
