### ISSUE TITLE
[EN][Items] Heart of Unliving doesn't proc on HOTs (Resto Druid)

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#10079]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

http://www.wowhead.com/item=77199/heart-of-unliving

**Description**: Describe the problem
This trinket should work exactly like Darkmoon Card: Tsunami, that means for resto druids the first application of a hot should have a chance to proc the stack. However, on atlantiss, it doesn't, it only works with direct casts.
**Current behaviour**: What happens
It doesn't proc whatsoever, I can spam rejuvenation for days and it won't give me a single stack.
**Expected behaviour**: What should happen instead
It should have a chance to give me a stack on the first application of the hot, basically when I cast the spell, same thing as DC: Tsunami.
https://www.youtube.com/watch?v=Z4xXAvl_UJk Inspo video, you can see on the bottom left of this video the stacks go up very quickly and don't ever go down, which wouldn't currently be possible at all. You can also see when the stacks go up by which spells he uses.
**Steps to reproduce the problem**:

1. Look at the script from DC: Tsunami
2. Use that script and just buff it to the 880 spirit value on 10 stacks
3. Just make it work on the first application of a hot otherwise this trinket is currently absolute trash for resto druids

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 
rev. 5797

**Comment by 123432211** [comment]
Heart of Unliving shouldnt proc from hots :)

**Comment by Aldergar** [comment]
No, it should proc on the 1st application of the hot, that means when i press rejuvenation, it gives me 1 stack. Not every tick. Just the 1st tick, tsunami works the same way, you can test it ingame by yourself if you dont believe me.

**Comment by Psychobird7** [comment]
WoU should works in the exact same way, and *yes*, they are both meant to proc on DoT/HoT applications.  

People say so on every known forum/board, and it is easily confirmed by watching a few videos.

**Comment by Heroclassx** [comment]
https://youtu.be/cY4pgtfU4WM?t=1232

Tsunami should proc from hot ticks (renew in posted video), so each tick refreshes renew while hou should proc on application (use) of the hot itself but dosent get refreshed on ticks.

That and the lower uptime was the reason DC:Tsunami > HoU for any healer in pvp afaik

**Comment by Psychobird7** [comment]
I fail to see the connection between the point you're trying to make, and the video you linked?

**Comment by Aldergar** [comment]
In either way guys, it doesnt work. HOU doesnt proc from the first application and that is the bug I just reported.

**Comment by Piklo** [comment]
should proc on hot apply in [rev5814](https://atlantiss.eu/changelog#rev5814)
