### ISSUE TITLE
[EN][Core] AoE Diminishing returns 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10073]
**Description**: Diminishing returns (DR) for Holy Radiance and Healing Rain currently do not function correctly. 

**Current behaviour**: 
AoE healing currently hits pets/guardians/summons, and DRs from them. 
The following logs of an Ultraxion 25N kill show current DR on Atlantiss.  
http://www.worldoflogs.com/reports/rt-5efs7rs1ug4bt3vk/xe/?s=1476&e=1754&x=spellID%3D82327 
For Holy Radiance (HR) hits, you will see that, as soon as the Storm Scarabs despawn, the healing increases **significantly**. 
http://www.worldoflogs.com/reports/rt-5efs7rs1ug4bt3vk/xe/?s=1476&e=1754&x=spellID%3D73921 
Same thing for Healing Rain (HRain). 

**Expected behaviour**: 
AoE healing should hit pets/guardians/summons, but should not DR from them. 
DR should work as follows: 
For 1-6 players | Heal per player = (Base heal * 6) / 6
For 6+ players | Heal per player = (Base heal * 6) / players affected
**The DR should completely ignore pets/guardians/summons.** 
Here's an example: https://imgur.com/8UvF2Wk 

The following logs of retail kills will show proper DR behaviour. 
http://www.worldoflogs.com/reports/rt-ix11bblcoy2tuyri/xe/?s=5904&e=6262&x=spellID%3D82327 
This log shows DR for HR on an Ultraxion 10H kill. 
http://www.worldoflogs.com/reports/rt-2kytm3wo4lsnvnkq/xe/?s=13444&e=13736&x=spellID%3D82327 
This one will show DR for HR on Ultraxion 25H. 

**Steps to reproduce the problem**:

1. Be a healer with AoE healing 
2. Cast AoE healing on 6+ targets, in a group that has pets/guardians etc 
3. Cry. 
 
**Revision**: 5790

**Comment by Piklo** [comment]
should be fixed in [rev5793](https://atlantiss.eu/changelog#rev5793)
