### ISSUE TITLE
[EN][Cataclysm][NPC]Ozumat

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#10076]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Ozumat's loot is bugged in Throne of the Tides normal (not sure about HC)

**Current behaviour**: Ozumat drops only 1 item 

**Expected behaviour**: He should drop atleast 3 items

**Steps to reproduce the problem**:

1. Get in Throne of the Tides normal
2. Kill Ozumat
3. Check the loot

**Revision**:  5792

**Comment by Piklo** [comment]
any proofs of that?

**Comment by trolloh** [comment]
Proofs of the bug or of the loot?

**Comment by Piklo** [comment]
proof that this is a bug

**Comment by trolloh** [comment]
Wrong call for bug
