### ISSUE TITLE
[EN][Quest][Winterspring] They Grow Up So Fast

### ISSUE THREAD

**Issue by martemushi** [Atlantiss/BugTracker#10070]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Unable to turn quest in. http://www.wowhead.com/quest=29034/they-grow-up-so-fast

**Current behaviour**: After collecting everything you need for the quest you can't turn it in. When speaking to the quest giver the 'continue'-button is grey and can't be clicked.

**Expected behaviour**: You should be able to turn in the quest

**Steps to reproduce the problem**:

1. Get quest from questgiver
2. Collect everything
3. Try to turn it in

**Revision**: 5784

**Comment by TranceAccount** [comment]
Try retaking the q. It shouldn't delete your questitems.

**Comment by martemushi** [comment]
Worked like a charm! It's been in my quest log for ages, thats probably why it bugged out :p Thanks!
