### ISSUE TITLE
[EN][Dragon Soul] Trash loot

### ISSUE THREAD

**Issue by klm670** [Atlantiss/BugTracker#10072]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Dragon Soul trash should drop loot. Gold, and items. Currently it doesn't drop any loot, even though it should. As seen in [http://www.wowhead.com/item=77938/dragonfire-orb](url) for example.
[http://www.wowhead.com/npc=57158/earthen-destroyer](url)
 [http://www.wowhead.com/npc=57821/lieutenant-shara#comments](url) Currently also despawns before there is any chance to loot. There is no loot to loot however.

**Current behaviour**: The mobs don't drop gold, and they barely ever drop anything. 

**Expected behaviour**: The mobs should drop gold, and have an increased chance to drop items. 

**Steps to reproduce the problem**:

1.  Kill DS trash
2. ???
3. No profit, because no loot

**Revision**: 5790 #

**Comment by TranceAccount** [comment]
@Piklo <3
