### ISSUE TITLE
[EN][Talent][Warrior] Blood Frenzy

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#10082]
**Description**:
Blood Frenzy ( the +20 rage part)  procs +/- every 60 sec, so it seems it has a ICD how ever theres no mention of it everywhere i looked on the web, 

**Current behaviour**:
gives +20 rage every 60 sec

**Expected behaviour**:
every melle (white) atack should have 10% chance to give ectra 20 rage

http://www.tauri-veins.tk/arms-warrior-wow-pve-dps-spec-builds-talents-glyphs
> Blood Frenzy: each time a target is affected by one of your bleeds (Rend and Deep Wounds), it takes 4% increased physical damage and 30% increased bleed damage (from all players in your raid). Note that this effect does not stack with several other equivalent debuffs provided by other classes. **This talent also provides you with a 10% chance to generate 20 rage each time you perform a white attack.**

http://cata-shoot.tauri.hu/?spell=29859
> Cooldown | n/a

http://cata-shoot.tauri.hu/?spell=92576
> Cooldown | n/a

**Steps to reproduce the problem**:
1. 

**Revision**: rev. 5798

**Comment by stanq87** [comment]
for now: 
1 normal rotation procs +/- every 60 sec
2 executoner spam has been seen to proc as often as every 3 sec 
   with cancel aura macro of execiutoner (haste buff)  procs every +/-45 sec 
3  mortal strike+heroic strike with rend present spam, procs every +/-45sec

**Comment by Piklo** [comment]
retail, 4 min 11 sec
![image](https://user-images.githubusercontent.com/16057987/41682225-6c7e1010-74d7-11e8-8a7e-617f9ae5f097.png)
ats, 4 min 28 sec
![image](https://user-images.githubusercontent.com/16057987/41682253-87969f20-74d7-11e8-88f8-b7f1b63622ff.png)

there is no icd
