### ISSUE TITLE
Doomguard damage

### ISSUE THREAD

**Issue by Felflamez** [Atlantiss/BugTracker#10089]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
 http://wowwiki.wikia.com/wiki/Summon_Doomguard  does low damage after "fix"
**Current behaviour**: What happens
before fix it doing legit(blizzlike damage)
**Expected behaviour**: What should happen instead
after it does very low damage even in full buffed mode wlock , it should doing normal damage like before fix 
**Steps to reproduce the problem**:

1. use Doomguard on dummy/boss and see what happen
2. look on damage done
3. compare with any youtube videos from wlock PoV that made during retail Cataclysm(for example https://youtu.be/XVb8-r5k6lU ) 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
rev. 5809

**Comment by Aloise3** [comment]
Doomguard did not scale properly with mastery before 4.3 (It gained 3x the amount it should, which lead to those numbers)

Please get some proof before commenting nonsense

**Comment by xolon** [comment]
REEP LOX
