### ISSUE TITLE
[EN][Glyph][Spell][Priest] Glyph of Shadow Word: Death

### ISSUE THREAD

**Issue by Axelitoo** [Atlantiss/BugTracker#10085]
**Description**: Glyph of Shadow Word: Death is a glyph that allows you to use SW:D twice when the target you use it on is at or below 25% health. It then goes on its natural CD for 10s. The current issue is that it doesn't work properly when there's more than one person with the glyph, in your raid group.

**Current behaviour**: Whenever you utilize the glyph aka use SW:D twice, it goes on CD for everyone in the group, meaning that once you SW:D twice, the rest of the people can only use it once, until **your** CD is off.

**Expected behaviour**: It should be individual. The glyph should work for everyone and should give an individual CD.

**Steps to reproduce the problem**:

1. Death twice with two or more shadow priests in the party.
2. Watch how the other priest cries about it.
3. You two start a contest of who can SW:D the fastest and make use of the glyph.

**Revision**: 5808

**Comment by fluessig** [comment]
nice find, i was troubled with this one a lot and simply gave up trying to find out

**Comment by pelekon** [comment]
fixed in rev 5828
