### ISSUE TITLE
[EN] [Class] [Dk] [Spell] Dark Simulacrum

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#10080]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Dark Simulacrum should copy any spell which costs mana and copy this cast as instant cast.

**Current behaviour**: sometimes you actually have to cast for some reason.

**Expected behaviour**: Should be instant, its really frustraiting losing the proc because you randomly have to cast a spell, also not useable while running (which It should be since it is an instant cast)

**Steps to reproduce the problem**:

1. Let a class cast somethign at you
2. Use Dark Simulacrum before the cast is finished
3. Try to use the copied spell, sometimes you actually have to cast the spell instead of being instant also check that you cant use the spell while moving.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Jenovas** [comment]
Fixed
Seems like not being able to cast while moving was a retail bug
