### ISSUE TITLE
[EN][Spell][Warrior] Slam

### ISSUE THREAD

**Issue by Axelitoo** [Atlantiss/BugTracker#10083]
**Description**: Slam is an ability that on Arms does 196% of your melee damage + 1039 damage. This extra number is affected by talents and enrage, and is the Slam base damage. It is unaffected by AP. The issue right now is that Slam does far too much damage.

**Current behaviour**: To calculate the **hypothetical** Slam damage, I simply took my average melee damage, and did the following:

(8800*1.96)+1039=18287

Due to the following tests I made I will divide this number by 1.46 to take into account the lost damage because of the armor on the dummy. Comparing melee strikes made 1.46 more accurate than /3*2, and therefore I will use this. Whether this is accurate or not the damage was only fluctuating by 400 ish between the two ways of calculating in armor, so it would still not explain the massive gap.

18287/1.46=12525

The average damage for me on the dummy would be **12525**.

In reality, my average Slam damage on the dummy (only hits) was **14516**

![image](https://user-images.githubusercontent.com/35030805/41252858-b5816de0-6dbe-11e8-8a71-c5faa4b1fbde.png)

The current Slam for me is doing about 16% more than intended.

This test was made using the same buffs, but also counting away things like Colossus Smash, Expose Armor and Blood Frenzy. No "temporary" buffs were applied. Only Blessing of Might, Mark of the Wild and a food buff. Also note that the damage increases from talents have been taken into consideration.

**Expected behaviour**: The damage should follow the "formula" given in the description, aka 196% of your melee damage and also the Slam base damage. 

**Steps to reproduce the problem**:

1. Be arms warrior
2. Slam
3. Notice how absurdly high it hits for

**Revision**: 5798

**Comment by Katonetwo** [comment]
worthy of note that this is without slaughter stacked, and that damage is even more abnormal if you test with lower level weapons


essentially
something somewhere went terribly wrong

**Comment by stanq87** [comment]
so  assuming armor values on those dummys are correct,  
expected 10500-12600 i get  12800-16000 on normal strikes and 24k-29k -->   30k - 37k  crits

**Comment by Katonetwo** [comment]
armor values *are* correct
it's not like slam pierces armor either, because it gets the same bonus from CS as anything else
it's supposed to hit about as hard as mortal strike
instead, it hits as hard as templar's verdict (somehow)

**Comment by Psychobird7** [comment]
Boss/dummy armour values are *definitely* correct, we had those double-checked a while ago. 

"Fixed in rev. 4400 by @ Jenovas (checked current state on server and is correct).
Rev. 4400: 2015-04-14
reducing all level 88 bosses armor to 11977"

**Comment by brajevicm** [comment]
Tests were done with decent gear without any buffs/procs and with 403 Gurthalak. Keep in mind same thing applies with no gear equipped and 3.3 QA 2h weapon. Defensive stance and no talents were used.

AP: 14667
Weapon Speed: 3.6
Base Weapon Damage: 2704 - 4057

Slam Damage:
(((AP/14)*UnnormalizedWeaponSpeed)+BaseWeaponDamage)+431
Lower end: ((((14667/14)*3.6)+2704)+431) * 1.45 = 10014
Higher end: ((((14667/14)*3.6)+4057)+431) * 1.45 = 11976

With Armor:
Lower end: 10014 - (10014 * 0.315) = 6860
Higher end: 11976 - (11976 * 0.315) = 8204

Testing on PTR after 100 Slams:
Lowest 7870, which is 114.7% of 6860
Highest 9344, which is 113.9% of 8204

**Comment by Piklo** [comment]
should be fixed in [rev5812](https://atlantiss.eu/changelog#rev5812)
