### ISSUE TITLE
[EN][Paladin][Spell] Zeal of the Crusader (4T13) 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10099]
-- New report since the old issue was incorrect. 

**Description**: Zeal of the Crusader (ZotC), Retribution's 4T13 currently does not work correctly. 
***ZotC should act as an 18% increase to all damage dealt, in the same way Avenging Wrath does.***

**Current behaviour**: ZotC does not grant the proper 18% increase to abilities.  

**Expected behaviour**: ***ZotC should act as an 18% increase to all damage dealt, in the same way Avenging Wrath does***, and the same way it is modelled on Simcraft.  
https://pastebin.com/sbsmpbLK 
if ( p -> set_bonus.tier13_4pc_melee() && p -> buffs_zealotry -> check() )
{player_multiplier *= 1.18;}

- See the following:
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/sum/damageDone/?s=5141&e=5343#Dns
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/details/13/?s=5141&e=5343
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=spellID%3D105819+OR+spellID%3D85256+OR+spellID%3D86700+OR+spellID%3D75176

Take the highest TV seen in the log, 124258.

Now for the sake of comparison, I will run a 500k iteration simulation of a Heroic Dragon Soul BiS Ret paladin.
We know exactly how Simcraft models ZotC, and therefore know exactly how it calculates TV's damage, which will be useful in determining the correct calculation method based on this log.
"if ( p -> set_bonus.tier13_4pc_melee() && p -> buffs_zealotry -> check() )
{player_multiplier *= 1.18;}"
The maximum TV damage as calculated by Simcraft (same gear, same procs, same everything) is 126728.

If we were to fully recalculate TV's damage to see the maximum possible damage with ZotC being additive, the result would be 120728. This is much lower than the number seen on the log.

---> ***Zeal of the Crusader had to have been multiplicative on retail***.

- http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=sourceName%3D%22Dns%22

[20:39:26.699] Dns crits Ultraxion 32483

This auto-attack proves that ZotC had to have been coded as an AW-like damage increase.

If ZotC did not increase melee swing damage, the highest possible melee swing on a full Heroic Dragon Soul BiS ret paladin would be 29994.1, using the same buffs as the Paladin on the aforementioned log had.
The paladin on the log crits for 32483.

- The same thing happens with Censure ticks.
[20:39:24.000] Dns Censure Ultraxion 9859
This tick occured just before the Paladin activated AW+Zeal.

[20:39:26.042] Dns Censure Ultraxion 15938
This tick occured right after. The difference between those two ticks (keep in mind, he has the same buffs for both) is far too high to be caused by RNG.

**Steps to reproduce the problem**:

1. Go on PTR (not necessary, but helpful), add the item with ID 57692. 
2. Make two sets of gear, one with 4T13 equipped, one without, and note your AP in both setups. 
3. Do a test run for each set of gear, and note the damage of your abilities. See they will not get the proper 18% increase. 

**Revision**: 5809

**Comment by MangeNerfedOwl** [comment]
Should it then also affect tentacle from Gurthalak then same as AW does?

**Comment by Psychobird7** [comment]
Wowhead comments point that way. 
ex.: http://www.wowhead.com/item=77191/gurthalak-voice-of-the-deeps#comments:id=1700501 

As does this MMOC thread. 
https://www.mmo-champion.com/threads/1040084-Gurthalak-questions?p=14582206&viewfull=1#post14582206 

The source log also shows increased Mind Flay damage around CD periods.

**Comment by Jenovas** [comment]
Fixed in rev 5818
