### ISSUE TITLE
[EN][Raid][Dragon Soul] General class issues

### ISSUE THREAD

**Issue by mcfreddas** [Atlantiss/BugTracker#10095]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: On encounters like Ultraxion http://www.wowhead.com/npc=55294/ultraxion, Spine of Deathwing http://www.wowhead.com/npc=53879/deathwing and Madness of Deathwing http://www.wowhead.com/npc=56173/deathwing you can't use most of the spells that requires that you are behind target and that makes some specs like subtility for rogues complitly unviable wich is a shame i think. Altho Ultraxion is not suppose to be attackable from behind spells like http://www.wowhead.com/spell=51690/killing-spree still turn you away and you miss importent normal attacks as far as i can tell and can also teleport you off the boat for example on http://www.wowhead.com/npc=56427/warmaster-blackhorn encounter. I have heared other classes also having problems with some spells like http://www.wowhead.com/spell=100/charge etc.

**Current behaviour**: Unable to use spells like http://www.wowhead.com/spell=53/backstab and dagerous to use spells like http://www.wowhead.com/spell=51690/killing-spree because it can flip out and possition you in a realy bad way in some cases. 

**Expected behaviour**: You should be able to use these spells for the most part if i remeber correcly https://www.youtube.com/watch?v=41GhaWPLx6o in this video at 6:15 a top player back in live is using subtility spec for exampel on spine.

**Steps to reproduce the problem**: Try the spells on the encounters above i guess

1. 
2. 
3. 

**Revision**: rev. 5809

**Comment by Axelitoo** [comment]
Fairly sure the Killing Spree making you fall down on the boat is if the add starts casting Blade Rush towards the group. This makes him turn around, and if you're on the edge like you should, then you drop off. Same shit if the tank is a monkey and moves stupidly. Also could happen if your Killing Spree fixates on the drake.

**Comment by brajevicm** [comment]
Last time I checked you can use Backstab on every unit on Spine. KS is also usable on everything.

**Comment by Piklo** [comment]
#10090, better report about madness, if there is bug with spine, please open new report (preferably with list of npcs)
