### ISSUE TITLE
[EN][Talent][Warrior] Sudden Death

### ISSUE THREAD

**Issue by vk1354** [Atlantiss/BugTracker#10096]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  The talent sudden death (tier 5) for arms warrior has it's second rank producing lower values than the tooltip says and retail logs for the equivalent patch recorded.

**Current behaviour**: The second rank of the talent sudden death (tier 5) for arms warrior has 50% (aprox) lower chance of triggering (equal to rank one of the talent but not the appropriate 6% chance of proccing of the second rank of that talent) a reset on the ability Colosus Smash.
**Expected behaviour**: What should happen instead The buff Sudden Death should be procced off 6% of all attacks (not bleeds) made by the warrior. You can calculate the accuracy on retail logs by getting a random sample (a longer duration fight has provided with more accurate results in the decimal points), adding up the critical attacks made, the non critical attacks made and lastly the glances made, then dividing that result with the amount of Sudden Death procs gained throught the course of that fight as seen here: http://www.worldoflogs.com/reports/rt-0rtq0x83driajmjn/sum/damageDone/?s=3395&e=3762 . Or here: http://www.worldoflogs.com/reports/rt-zhynwqtxb78hm9ij/sum/damageDone/?s=97&e=461 .
**Steps to reproduce the problem**:
1. Apply the same logic on a prerecorded fight (either boss fight or a session at the training dummies while doing your normal rotation)
2. Watch as you get half the expected values of the second rank of the talent (tier 5) Sudden Death
3. Here are some arms warrior logs from atlantis: http://www.worldoflogs.com/reports/yse94rfjx56nma07/sum/damageDone/?s=3108&e=3395 http://www.worldoflogs.com/reports/jn7k417ma55mwkbk/sum/damageDone/?s=2493&e=2792

**Revision**: 5809

**Comment by MangeNerfedOwl** [comment]
Maybe it has something to do with Opportunity Strikes (mastery of arms spec). When I tested amount of rage gained and resets of collosus smash mine and another warrior that had weapon with same speed but prot gear (full reforge and gems into mastery) there was pretty much no difference at all between us in both rage gained and Sudden Doom procs. Preach in his guide spoke about more procs for Collosus Smash with more mastery coming at your gear https://www.youtube.com/watch?annotation_id=annotation_159831&feature=iv&src_vid=OYM_rhC-ldA&v=rGQweiWrEhw 9:30

**Comment by Piklo** [comment]
should be fixed in [rev5812](https://atlantiss.eu/changelog#rev5812)
