### ISSUE TITLE
[EN][Item][Spell] Heart of Unliving / Darkmoon Card: Tsunami | Atonement Priest.

### ISSUE THREAD

**Issue by Fabiana-B** [Atlantiss/BugTracker#10093]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Spells like **Holy Fire** (14914) and **Smite** (585) doesn't grant an **Heart of Unliving (N)(77199) stack**, on a Discipline Priest with the **Atonement** talent, but it grants on **Darkmoon Card: Tsunami** (62050)

**Current behaviour**: Equipping 
![dmc- tsunami](https://user-images.githubusercontent.com/22076895/41397662-ed59ad8e-6f82-11e8-9ef6-17fa82e10891.png), and using Smite or Holy Fire, sometimes grants a **Giant Wave** stack, and the tooltip on the item is correct: 

"Your healing spells **have a chance** to increase Spirit... bla,bla,bla...". Since Atonement is a healing spell, you will get stacks of **Giant Wave**.

But that will not happens with the Heart of Unliving: 
![hou](https://user-images.githubusercontent.com/22076895/41397826-6a19818c-6f83-11e8-9411-b22fb3e12291.png)
Tooltip on the item is correct:

"Your healing spells **grant** 88 spirit...". This means, you will get a **Expansive Mind** stack (107962) every time you cast a healing spell.

There's a potato video I made when I was writing this bug: https://youtu.be/PUg1_FbNg3g

**Expected behaviour**: Heart of Unliving will proc with the Atonement talent, same as the DMC:T does.

**Steps to reproduce the problem**:

1. Equip DMC: Tsunami, and hit something with Smite/Holy Fire, having the Atonement Talent.
2. Unequip DMC: Tsunami, and equip Heart of Unliving, and hit something with Smite/Holy Fire, having the Atonement Talent.
3. You will see, Atonement is not a "healing spell" on Heart of Unliving, but it's a healing spell on the Darkmoon Card: Tsunami.

**Revision**: 5809

**Comment by Lonerin** [comment]
Despite not working correctly, Heart of Unliving trinket is NOT supposed to proc on atonement healing. 
Every healing class has some spells that do not grant HoU proc, it's intended by blizzard

**Comment by Piklo** [comment]
Atonement shouldnt proc HoU
