### ISSUE TITLE
forever drunk

### ISSUE THREAD

**Issue by aplamhden** [Atlantiss/BugTracker#10091]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
after i use a trinket that makes me drunk, the visual effect remains
**Current behaviour**: What happens
the visual dizzy effect remains
**Expected behaviour**: What should happen instead
normal visuals
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Aloise3** [comment]
This is my favorite post.

**Comment by calladin** [comment]
kys (in game not irl 🗡 )  and it should be all good ;)

**Comment by Axelitoo** [comment]
You're forever drunk?
Perhaps you should contact Anonymous Alcoholics or any other helping hand.

**Comment by Katonetwo** [comment]
only the dead may know peace from this curse

**Comment by Piklo** [comment]
please dont open empty reports
