### ISSUE TITLE
[EN][NPC][Drop] Balnazzar

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#10102]
Description: The NPC (http://www.wowhead.com/npc=10813) doesn't drop Plans: Truefaith Vestments (http://www.wowhead.com/item=14512)

Current behaviour: The recipe does not drop at all

Expected behaviour: It should have about 9% drop chance according to wowhead

Revision: 5809

**Comment by Piklo** [comment]
should be fixed in [rev5810](https://atlantiss.eu/changelog#rev5810), not mentioned in changelog
