### ISSUE TITLE
[EN][Item] Heart of Unliving for Discipline Priest

### ISSUE THREAD

**Issue by Lonerin** [Atlantiss/BugTracker#10105]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Heart of Unliving is supposed to proc only from certain abilities, and for some, only the initial tick/bounce. Many websites such as wowhead has lists for every spell that proc HoU for each class.

**Current behaviour**: HoU doesn't give any stack when you cast prayer of mending, PW:Shield or Renew

**Expected behaviour**: All 3 spells mentioned above should grant a proc from HoU:
*Prayer of Mending: 1 proc on the initial cast
*PW:S: 1 proc (with the glyph) when you cast it
*Renew: 1 proc on the first tick (I'm not sure if its for Holy spec only, but sources I've read indicates disc spec too)

**Steps to reproduce the problem**:

1. Equip Heart of Unliving trinket
2. Cast Prayer of mending, PW:Shield, Renew
3. Check your expansive mind stack

http://www.wowhead.com/item=77976/heart-of-unliving#comments

**Revision**: 5813

**Comment by Piklo** [comment]
fixed proc from renew and PW:S in [rev5814](https://atlantiss.eu/changelog#rev5814)

**Comment by Piklo** [comment]
more changes in [rev5817](https://atlantiss.eu/changelog#rev5817), some of them are not mentioned in changelog
