### ISSUE TITLE
[EN] Highland Guppy Schools in Twilight Highlands

### ISSUE THREAD

**Issue by Laagg** [Atlantiss/BugTracker#10100]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Highland Guppy Schools are spawning along the Verrall River and in the Verrall Delta in locations where they cannot be fished from. The pools do not have a respawn/reset timer, making them permanently unusable and reducing the amount of pools that can be fished from every time one respawns in such a location. Eventually, there will be no more Highland Guppy Schools that will be usable.

**Current behaviour**: What happens
Highland Guppy Schools spawn where they are not usable ("Water is too shallow").

**Expected behaviour**: What should happen instead
Highland Guppy Schools should either not spawn where they are not usable, or they should have a reset/respawn timer, avoiding an eventual lack of usable pools.

**Steps to reproduce the problem**:

1. Fly up the Verral River in Twilight Highlands and fish out of every Highland Guppy pool you find.
2. After noticing that many are unusable, repeat step one.
3. Realize that there are fewer and fewer usable pools.

**Revision**: ACore rev. 5809 hash.08746d0626ff

**Comment by Laagg** [comment]
I get that it's not something very urgent, but these fish are one of the ingredients for feasts and I highly doubt this would take a long time to fix...

**Comment by TranceAccount** [comment]
Should be fixed  when rev 5824 is applied.
