### ISSUE TITLE
[EN][Warlock] Summon Infernal 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#10114]
**Description**: https://github.com/Atlantiss/BugTracker/issues/10069 
Exact same issue as in the Doomguard report. 

**Current behaviour**: Infernal is inheriting too much of the warlock's SP. 

**Expected behaviour**: Infernal should inherit the same amount as Doomguard. 

**Steps to reproduce the problem**:

1. Summon an infernal 
2. Have it DPS a dummy/boss 
3. Notice it will do way more damage than it should 

**Revision**: 5815

**Comment by Piklo** [comment]
Infernal is not inheriting too much of the warlock's SP, but have some other issues with inheriting SP.

since [rev5826](https://atlantiss.eu/changelog#rev5826), infernal should do less dps
