### ISSUE TITLE
Surge of Light 2

### ISSUE THREAD

**Issue by lagertha1995** [Atlantiss/BugTracker#10112]
Dear my expert Axelito, read well when someone writes something. It has nothing to do with the difference in spec, it does not affect the effect of talent. Talent says "You have 6% chance with Flash Heal, Heal, Binding Heal and Greater Heal to get a free Flash Heal" but he work only with Greater Heal and Binding Heal on Disci spec.

Summary of first issue for Surge of Light :
Description = Surge of Light proc.
The "Surge of Light" only proc with Greater Heal and Binding Heal. Hit doesn't proc work with Flash Heal and Heal.

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Axelitoo** [comment]
A bug tracker report somehow in my honor... well well. 
Again, you completely ignored the template.
Second of all, where's the evidence? I showed you a very clear video of it proccing from Heal, so unless you show us that it doesn't proc for Discipline, it's naturally gonna be counted as a fairly shitty report, no?

So - let me try to interpret what you just said. You assume that this talent does NOT proc from Flash Heal and Heal, right?
This is just false. Anyone who plays Priest will know this is absolute bullshit, I even showed you a video which showed what you claimed impossible.

**Comment by lagertha1995** [comment]
Ok now he work, but with 6% 1/25 flash heal It seems a little too low. I ask if possible to check the percentage of proc.

**Comment by Katonetwo** [comment]
if you think that flash heal doesn't proc surge, you should probably go ahead and double check 
and please, for the love of god, use the template
>.<

**Comment by Axelitoo** [comment]
I'll give you some advice. Close down the report, do a comprehensive test of perhaps let's say, 100 Flash Heals and 100 Heals, and then tell us how many procs you got. And then structure the report following the template given.
