### ISSUE TITLE
[EN][Item] Wrap of Unity and Shroud of Cooperation

### ISSUE THREAD

**Issue by maddy169** [Atlantiss/BugTracker#10119]
Description: Guild members can't buy these objects.

Current behaviour: Honored members of the guild can't buy these objects from any guild vendor.

Here you can see:
https://ibb.co/bvE8XJ
https://ibb.co/f0q46d

Expected behaviour: Every honored, revered and exalted guild member should be able to buy them from any guild vendor.

Wrap of Unity: http://www.wowhead.com/item=63207/wrap-of-unity
          Reward from: http://www.wowhead.com/achievement=4945
Shroud of Cooperation: http://www.wowhead.com/item=63353/shroud-of-cooperation
          Reward from: http://www.wowhead.com/achievement=4989

Steps to reproduce the problem:

1. Become at least honored with a guild that has the necessary achievements.
2. Go to a guild vendor.

Revision: 5815

**Comment by TranceAccount** [comment]
Probably related to the specific guild vendor.

**Comment by TranceAccount** [comment]
Does your guild have the achievement for this item? Guild Cataclysm Dungeon Hero

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5827
