### ISSUE TITLE
[EN][Achievement][Argent Tournament] Champion of the Horde

### ISSUE THREAD

**Issue by maddy169** [Atlantiss/BugTracker#10118]
Description: After becoming Exalted Champion of your Capital, you can't keep going to become Champion of the others cities.

Current behaviour: After getting the achievement "Exalted Champion of (city)" and being exalted with other cities, the others NPC are not offering the quests to begin your way to become a champion of their capital. 

Expected behaviour: The NPC's Zul'tore (Sen'jin), Runok (Thunderbluff), Mokra (Orgrimmar) and Deathstaker Visceri (The Undercity) should offer the quests to continue and become champion of every city after you become champion of your own city and being exalted with the others.

Here's a guide of how the full tournament should work: www.wowhead.com/championing-the-argent-tournament#achievements

Links of the Achievements:
Champion of the Undercity: http://www.wowhead.com/achievement=2787
Champion of Orgrimmar: http://www.wowhead.com/achievement=2783
Champion of Silvermoon City: http://www.wowhead.com/achievement=2785
Champion of Sen'jin: http://www.wowhead.com/achievement=2784 
Champion of Thunderbluff: http://www.wowhead.com/achievement=2786

Champion of the Horde: http://www.wowhead.com/achievement=2788
Exalted Champion of the Horde: http://www.wowhead.com/achievement=2771
Exalted Argent Champion of the Horde: http://www.wowhead.com/achievement=2816

Links of the Quests that should be available:
Sen'jin: http://www.wowhead.com/quest=13727/the-valiants-challenge
Silvermoon City: http://www.wowhead.com/quest=13731/the-valiants-challenge
Thunderbluff: http://www.wowhead.com/quest=13728/the-valiants-challenge
Orgrimmar: http://www.wowhead.com/quest=13726/the-valiants-challenge
Undercity: http://www.wowhead.com/quest=13729/the-valiants-challenge

Must tell, that all of this is necessary to become Exalted Argent Champion of the Horde, which unlocks Dame Evniki Kapsalis <Crusader's Quartermaster> (http://www.wowhead.com/npc=34885/dame-evniki-kapsalis) as it is necessary for getting 5 tittles in game.

Steps to reproduce the problem:

1. Become champion of your city.
2. Try to continue to make yourself a champion for the other capitals.

Revision: 5815.

**Comment by maddy169** [comment]
Here are proofs of what i'm saying:

https://ibb.co/cXjHsJ
https://ibb.co/gEycsJ
https://ibb.co/iFFOXJ
https://ibb.co/nqqOXJ
https://ibb.co/gNzYXJ

There you can see I already have the title "of Silvermoon" and I am exalted with every city. 

Thanks in advance.

**Comment by Piklo** [comment]
everything works fine, but you have to open a ticket, so GM will add marker to your char that will allow you to take next quests
![image](https://user-images.githubusercontent.com/16057987/42133868-4d084f86-7d31-11e8-978d-a51b9b32d94c.png)
