### ISSUE TITLE
[EN][QUEST][DK] Finishing An End to All Things & The Light of Dawn doesn't grant talent points.

### ISSUE THREAD

**Issue by SuperCaelum** [Atlantiss/BugTracker#10110]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: As a male Worgen quests An End to All Things and The Light of Dawn do not grant talent points (2 points and 3 points respectively). This greatly puts you behind other DK's as of lvl 59 others will have 30 points in their main talent tree.

**Current behaviour**: Quest An End to All Things rewards you with: 2 gold 30 silver, 16300 experience and Greathelm of the Scourge Champion. 
The Light of Dawn rewards you with: either Greataxe of the Ebon Blade or Greatsword of the Ebon Blade, Death Gate, 16350 experience 3 gold and 55 silver  

**Expected behaviour**: On top of those rewards you should also receive 2 talent points for An End to All Things and 3 talent points 

**Steps to reproduce the problem**: I didn't do anything extraordinary so 

1. Be a Worgen Male. (Don't know if it has anything to do with it)
2. Be lvl 57/58 (I was at exact lvl game expected me to be, but I don't remember which it was)
3. After starting An End to All Things use the horn in worgen form (I've heard that some months ago [?] that item couldn't be used in worgen form and perhaps it's correlated.)
4. Do the quest 
5. After killing 150 crusaders and 10 ballistas accidentally press 2 which lowers the frost wyrm to the ground and lowers it's speed.
6. Say **** it, dismount and go back to Lich King using your Running Wild ability.
7. Start The Light of Dawn quest.
8. Go to Darion Mograine, notice he's at Light's Hope Chapel and he want's to start the battle from there and relog.
9. Begin the battle for real this time.
10. Wait like 4 minutes before battle starts because quest is bugged as ****.
11. Wait until everybody stops talking **** behind Lich King's back and choose your reward.
12. Notice you didn't receive talent point for quest again, wait 2 days to make a post here.

**Revision**: 26.06.2018 - 4.3.4.

**Comment by Katonetwo** [comment]
30 talent points at 59 is impossible
you didn't mention how many you got yourself, which, at 59, should be 26

**Comment by SuperCaelum** [comment]
If it's impossible then quests shouldn't show talent points as rewards...
