### ISSUE TITLE
[EN][Object][End Time] Hourglass of Time

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#10113]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hourglass of Time doesnt reset the Cooldown of Raise Dead (DK Spell)

**Current behaviour**:  When you use Hourglass of Time at Muruzond in End Time all of your CDs gets reseted as DK except Raise Dead

**Expected behaviour**:  Raise Dead should be reseted too 

**Steps to reproduce the problem**:

1. Get to End Time as DK
2. Kill first two bosses, then get to Murozond
3. Use Raise Dead
4. Use Hourglass of Time, watch the cooldown wont get reseted

**5815**: Current server version

**Comment by poleloa** [comment]
I was doing murozond many times. And i believe you #trolloh -you're right.
I'm too dk in game. Raise Dead could not reset . I didn't know why. Thanks (hope delevopers fix it as fast they can)
Greetings

**Comment by mati865** [comment]
@TranceAccount it can be hard to find, pets haven't used to die on every damaging ability back then.

**Comment by trolloh** [comment]
@TranceAccount https://youtu.be/_TJXMif_RsA?t=51s look on his spellbar, third row, 5th spell

**Comment by TranceAccount** [comment]
@trolloh I don't see them press the Hourglass of Time, and after they kill Murozond they swap to another frame

**Comment by trolloh** [comment]
@TranceAccount they did, look at holes disappearing and screen becomes silver for few seconds too

**Comment by Piklo** [comment]
@mati865 the report which abilities are killing pets but shouldn't

**Comment by TranceAccount** [comment]
@trolloh isn't that just the death scene of murozond? And I don't see it reset the 5th button in 3rd row

**Comment by TranceAccount** [comment]
Nevermind I see it now, sorry.

**Comment by trolloh** [comment]
Its been fixed, maybe devs forgot to inform
