### ISSUE TITLE
[EN][Item][Profession] Nitro Boosts

### ISSUE THREAD

**Issue by Nooblydone** [Atlantiss/BugTracker#10124]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Nitro Boosts backfire is not correct. 

**Current behaviour**: Nitro Boosts can fail, however the way they fail is wrong. As of Cataclysm, they shouldn't throw the players up in the air when they backfire. This is what happens currently

**Expected behaviour**: When Nitro Boosts fail, they should deal 80% of the player's health over 8 seconds, and not throwing them up.

https://wow.gamepedia.com/Nitro_Boosts

As it is written on patch notes, in Cataclysm it shouldn't blow up players in the air but deal 80% (and not 120%) of the player's health over 8 seconds.

**Steps to reproduce the problem**:

1. Use Nitro Boosts (in or outside a raid) and notice they can fail throwing you up in the air.

**Revision**: 5823

**Comment by Piklo** [comment]
should be fixed in [rev5831](https://atlantiss.eu/changelog#rev5831)
