### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] Crisis at the Sunwell

### ISSUE THREAD

**Issue by Elkas** [Atlantiss/BugTracker#10127]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Quest can't be completed.

**Current behaviour**: What happens
Exarch Larethor is the name of NPC to turn in the quest is not there. I found out that he is inside Magister Terrace , but still can't turn in the quest.

**Expected behaviour**: What should happen instead
Exarch Larethor should be in his original position besides Shattrath Sun Offensive quartermaster not inside Magister Terrace. Player talk to him there to turn in the quest.

**Steps to reproduce the problem**:

1. Talk with Adyen the Lightwarden in Shattrath City to take the quest  http://www.wowhead.com/npc=18537/adyen-the-lightwarden
2. Take Quest http://www.wowhead.com/quest=11481/crisis-at-the-sunwell
3. Take portal to Isle of Quel'Danas then talk to Exarch Larethor http://www.wowhead.com/npc=24813/exarch-larethor

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
Rev.5823

**Comment by TranceAccount** [comment]
Confirmed, but it requires a dungeon event at the end. #572

**Comment by Navedonar** [comment]
Patch 4.3.0 (2011-11-29): Now shows up inside the Magisters' Terrace.

**Comment by TranceAccount** [comment]
Should be fixed in rev 5832.
