### ISSUE TITLE
[EN][Dragon Soul][Madness of Deathwing]Blistering Tentacle bug

### ISSUE THREAD

**Issue by lu3a** [Atlantiss/BugTracker#10126]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Blistering Tentacle during Madness of Deathwing 10 Normal are not appearing correctly.

**Current behaviour**: Blistering Tentacle are spawning 2 times, at 70% and 40% of the limb %.

**Expected behaviour**: Blistering Tentacle during Madness of Deathwing 10 normal encounter should spawn 3 times for each limb, at 75%, 50%, 25%. 

Proof: Read the dungeon journal: "At 75%, 50% and 25% remaining health the Limb Tentacle sprouts several Blistering Tentacle that are immune to Area of Effect abilities".

**Steps to reproduce the problem**:

1. Enter Dragon Soul, face Madness of Deathwing and see that Blistering are spawning 2 times at 70% and 40%.

**Revision**: 5823

**Comment by idohealz** [comment]
There are numerous videos online showing that only two sets spawn, even though the dungeon journal states otherwise. If you want your report to be taken seriously, I would suggest finding a video to prove it.

**Comment by Axelitoo** [comment]
According to Icy-veins (https://www.icy-veins.com/wow/madness-of-deathwing-strategy-guide-normal-heroic), 40% and 70% are correct. Close.

**Comment by Aival94** [comment]
Yes. This report is not really bug. Is just sth blizzard forgot to change on journal again.
