### ISSUE TITLE
[PL][Spell][Mage]Ignite dmg is halved

### ISSUE THREAD

**Issue by wojen616** [Atlantiss/BugTracker#10125]
**Description:** Ignite to dot nakładany przy krycie z fire spella
![image](https://user-images.githubusercontent.com/10191782/42233207-26d6c344-7ef1-11e8-93b4-5a8963af4d5f.png)
Spell id: 12846

**Current behaviour:**  Po ostatnich zmianach dmg ignite 3/3 wynosi około 20% wartości, zamiast tooltipowego 40%. 
![image](https://user-images.githubusercontent.com/10191782/42233427-d7d1fe7a-7ef1-11e8-9012-db67612c9880.png)

**Expected behaviour**: Ignite 3/3 powinien nakładać dot o wartości 40% krytyka z fire spella

**Steps to reproduce the problem**:
1. wycastuj fireballa który jest krytem
2. porównaj dmg ignita z wartością kryta fireballa

rev. 5823

**Comment by Axelitoo** [comment]
Can confirm, Google Translate. Did some quick maths on it and my crit did like 13%*2 instead of intended 20%*1.03*1.mastery.
I might have missed a few multipliers, but the damage is waaaaaaaaay off.

**Comment by SatsumaDK** [comment]
why u report this?
finally fire mages are working fine

**Comment by Aloise3** [comment]
Ahh, nothing like stealth nerfs

**Comment by Axelitoo** [comment]
Confirmed by Jenova to be a stealth nerf from **20% * 1.mastery in %** to **15% * 1.mastery**.
Can close, but expect one to be open in the nearest future with solutions.

**Comment by stanq87** [comment]
the  5% there makes mages loose  25% dmg on ignites  , and then makes decent combustions harder, good time to respec into frost
