### ISSUE TITLE
[EN][Raid][Spell] Nether Vortex on Ultraxion

### ISSUE THREAD

**Issue by Fabiana-B** [Atlantiss/BugTracker#10136]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Arcane Mages' talent: Nether Vortex is affecting Ultraxion.

**Current behaviour**: When an Arcane Mage uses **Arcane Blast and procs Nether Vortex** on Ultraxion, the boss is getting the **Slow** debuff.
![screenshot_11](https://user-images.githubusercontent.com/22076895/42417011-831eaa9c-824b-11e8-814c-8068be1c8a5f.png)

- Increasing by 30% the casting time of the Hour of Twilight up to **6.5 sec**. (check image, the DBM timer says 0.8 secs left to explode, but on castbar there's like 1.5 secs more to explode)
![untitled](https://user-images.githubusercontent.com/22076895/42417017-93191522-824b-11e8-8d87-f4622b952e14.png)

- And slowing the cast of Unstable Monstrousity.

**Expected behaviour**: Ultraxion **WILL NOT** get a Slow debuff (from the Slow ability or the Nether Vortex proc).

**Steps to reproduce the problem**:

1. Use an Arcane mage with the Nether Vortex talent (1/2 or 2/2)
2. Start the battle against Ultraxion.
3. Use Arcane Blast on Ultraxion. Ultraxion will get the Slow Debuff.

**Revision**:  rev. 5828.

Lot of thanks to Raenor and Martillito to help me testing this.

**Comment by Psychobird7** [comment]
This probably affects other DS bosses as well.       

And to clarify, bosses *should* get the debuff (it's essential to Arcane's DPS), but should not be affected by the casting time slow or the movement slow.

**Comment by pelekon** [comment]
hidden fixed in some revs ago
