### ISSUE TITLE
[EN][Death Knight][Spell] Howling Blast

### ISSUE THREAD

**Issue by Axelitoo** [Atlantiss/BugTracker#10131]
**Description**: Howling Blast currently does not do enough damage.

**Current behaviour**: Howling Blast currently for me does *10 699* damage (the damage is not fluctuating because the min-max damage is the same), on a Heroic Trainer's Dummy. This is quite far below what it should do.

**Expected behaviour**: Howling Blast follows the following formula:

[((minimum damage + maximum damage)/2) + (attack power×0.44)]

This ability should for me do the following:
[((1322+1322)/2) + (13000×0.44)]  = 7042 damage.

This must also take into considering my mastery, which boosts my Frost damage done by 62%.
7042×1.62 = **11 408.04 damage**

This means that Howling Blast on average does **710 damage** less than it should for me, and **355 damage** less to surrounding enemies.

I do also wish to add that we found multiple formulas all slightly different, but this one was provided by simcraft and we therefore based it from that result.

**Steps to reproduce the problem**:

1. Use Howling Blast
2. Realise it does shit damage
3. Wondering why you aren't Unholy at this point

**Revision**: 5828

**Comment by Psychobird7** [comment]
-- Formula as taken from Simcraft: 

"Blast the target with a frigid wind, dealing ${(($m2+$M2)/2)+($AP*0.44)} Frost damage to that foe" 

"base_dd_min:1322.14
base_dd_max:1322.14"

-- Spell ID for Howling Blast is 49184.

**Comment by Piklo** [comment]
should be fixed in [rev5831](https://atlantiss.eu/changelog#rev5831)
