### ISSUE TITLE
[EN][Spell][Death Knight] Death Coil

### ISSUE THREAD

**Issue by Axelitoo** [Atlantiss/BugTracker#10138]
**Description**: Death Coil is a ranged damaging ability for Death Knights. It currently does too little damage.

**Current behaviour**: Death Coil for a DK with 12 237 Attack Power and 73% mastery does 8374 damage on Atlantiss.

**Expected behaviour**: Death Coil should follow the formula;
[((($m1+0.23×ap)×1.15)×1.15)×1.mastery in %.]

This in translation becomes the following, for me;
(((985+0.23×12237)×1.15)×1.15)×1.73 = **8693**

8374/8693 = **96.3%**

Also wish to add that this test didn't require a big sample pool (actually only 1 DC) since the damage doesn't fluctuate as long as no modifying to AP occurs. $m1 is always 985.

**Steps to reproduce the problem**:

1. Death Coil
2. Does the outrageous 96% of intended damage. 
3. Wonder why you haven't rerolled retribution or arms

**Revision**: 5828

**Comment by Piklo** [comment]
should be fixed in [rev5837](https://atlantiss.eu/changelog#rev5837)
