### ISSUE TITLE
[EN][Item][Trinket]Insignia of the Corrupted Mind and Seal of the Seven Signs

### ISSUE THREAD

**Issue by popcorns12** [Atlantiss/BugTracker#10132]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The interaction between Insignia of the Corrupted Mind(I will refer to it as ICM from now on) and Seal of the Seven Signs(I will refer to it as SSS from now on) is very inconsitent.

**Current behaviour**: What happens
If you have ICM(397 ilvl) and SSS(397 ilvl) equiped at the same time, if one of them procs and it's ICD is triggered, the other one's ICD will be triggered as well even though it didn't proc. Furthermore if you have ICM(410 ilvl) and SSS(410 ilvl) equiped at the same time that issue isn't present, istead what happens is both trinkets can proc regardless of the state of the other trinket. I should also note that if you have one of the trinkets equiped as 410 ilvl and the other as 397 ilvl they behave the same way as if they were both 410 (the order doesn't matter both ICM and SSS can be 410/397 ilvl).

**Expected behaviour**: What should happen instead
I am uncertain as to whether or not both trinkets should be able to proc at the same time if they have the same ilvl since I couldn't find enough information on the web. One thing is for sure though and it's that this is an internal inconsistency and it should be looked into. I will note that even though the proc buffs from both trinkets have the same name and haste values(if they have the same ilvl) they have different IDs thefore it is logical that both trinkets should be able to proc together regardless of ilvl.

**Steps to reproduce the problem**:

1. Go in PTR and log an affliction warlock(best class/spec to test this in my opinion)
2. Add both trinkets with both item levels
3. Equip the trinkets and DPS a dummy with Drain Life(this ability can proc both trinkets)
4. Test different combinations of the ilvl of the trinkets and see for yourself.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
Rev 5808

**Comment by pelekon** [comment]
Thats how it should work as both trinkets use same spell
