### ISSUE TITLE
[EN][Spell][Priest] Glyph of Shadow Word: Death

### ISSUE THREAD

**Issue by Laagg** [Atlantiss/BugTracker#10130]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Glyph of Shadow Word: Death does not instantly reset the cooldown of Shadow Word: Death.

**Current behaviour**: What happens
Shadow Word: Death's cooldown is not instantly reset when used on an enemy at or below 25% health when using Glyph of Shadow Word: Death. Instead, it seems to behave as if it were on its own global cooldown (i.e. approximately 1 second delay between the first SW:D and being able to cast the second SW:D; in between the two, the UI displays "Spell is not ready yet" ).

**Expected behaviour**: What should happen instead
Glyph of Shadow Word: Death should instantly reset the cooldown of SW:D, making it so you can cast two of them back-to-back on an enemy at or below 25% health, with no delay in-between (as per the tooltip: "instantly reset").

**Steps to reproduce the problem**:

1. Be a priest, have Glyph of Shadow Word: Death
2. Use Shadow Word: Death on an enemy below 25% health, at an amount of health with which two back-to-back SW:D should kill him instantly.
3. Notice that the enemy does not die instantly due to the cooldown of SW:D not being "instantly reset", as per the tooltip of Glyph of Shadow Word: Death ("The spell is not ready yet" is displayed).

**Revision**: rev. 5828 hash. 4e0bda045840

**Comment by Piklo** [comment]
https://youtu.be/rd9rr9UNNTY?t=4m39s
i dont know if this is what you mean by "instantly"

**Comment by Axelitoo** [comment]
Just tested. It works like it should. You have to wait for GCD; hence "Spell is not ready yet."
