### ISSUE TITLE
holy wrath not stunning bloods

### ISSUE THREAD

**Issue by kek11** [Atlantiss/BugTracker#10142]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
holy wrath not stunning bloods on spine whne glyphed not sure about amlaganation
**Current behaviour**: What happens
nothing happens
**Expected behaviour**: What should happen instead
bloods need get stunned for 3 seconds
**Steps to reproduce the problem**:

1. press holy wrath
2. ????
3. nothing

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Psychobird7** [comment]
Amalgamation should not get stunned by anything.     
Only the bloods should, and they should also be slowed by Dazing Shield and similar effects.

**Comment by TranceAccount** [comment]
Proof?

**Comment by Psychobird7** [comment]
https://www.youtube.com/watch?v=UnWz0GMn8Fg        

At 3:41, watch the bottom center of the paladin's screen. The Holy Wrath debuff will appear right above Censure.  

https://www.youtube.com/watch?v=ScOQML2HuEQ 

At 3:41, watch the bottom left-ish. You will see a Shockwave debuff appear on the Blood the warrior is targeting. 
At 8:00, a Dazed debuff will appear on the Blood, in the same location. 

Both videos are dated from 4.3.x.

**Comment by TranceAccount** [comment]
Thank you

**Comment by Piklo** [comment]
should be fixed in [rev5837](https://atlantiss.eu/changelog#rev5837)
