### ISSUE TITLE
[EN][Dungeon][Well of Eternity] Not rewarding Justice Points

### ISSUE THREAD

**Issue by branel** [Atlantiss/BugTracker#10149]
[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
If you queue for the Well of Eternity dungeon as a Horde player killing any of the 3 bosses does not reward Justice Points.
**Current behaviour**: What happens
You're rewarded as a Alliance player but not Horde.
**Expected behaviour**: What should happen instead
Both factions should be rewarded.
**Steps to reproduce the problem**:

1. Queue for Well of Eternity using the Dungeon Finder on a Horde toon.
2. Kill any of the 3 bosses.
3. Notice how you get no Justice Points.
4. Repeat steps 1-2 but this time on a Alliance toon.
5. Notice how you get Justice Points this time from any of the 3 bosses.
????
Profit

**Revision**:  5836

**Comment by Lukabxjx** [comment]
I am doing Woe on my hunter for last few days(farming agi ring) and i am never getting any JP from any boss.Btw i am alliance.

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5854.
