### ISSUE TITLE
[EN][Cataclysm][Dungeon][Well of Eternity][Hour of Twilight][End Time] Reputation

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#10153]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hot/WoE/ET dont give us reputations

**Current behaviour**: The 378 ilvl dungeons mentioned above dont give us reputations meanwhile we have a cata faction's tabard on 
**Expected behaviour**: Mobs should give you rep if you wear tabard

**Steps to reproduce the problem**: Those 3 dungeons should give reputations (http://www.wowhead.com/guide=4134/guide-to-championing-cataclysm-reputations scroll down till the table)

1. Get for example Tabard of the Earthen Ring
2. Get to one of those 3 dungeons, kill few mobs
3. Watch you are not getting any rep

**5836**

**Comment by TranceAccount** [comment]
Is there any information on how much reputation these mobs should give?

**Comment by TranceAccount** [comment]
Some videos show 20 rep gained, others 16/17 rep
- https://www.youtube.com/watch?v=zCSvHJWrG4M (16/17 rep)
- https://www.youtube.com/watch?v=NUCPjpvGCI4&t=202s (20 rep, but he removes tabard after first few kills...)

**Comment by trolloh** [comment]
@TranceAccount looks like mobs before Jaina give 20 rep https://youtu.be/kgxnP0dbOqY?t=32s 
I couldnt find any video about WoE/HoT, even though found a WoWHead comment: "Normal rep is 15-16 per Shadowbat. 2 Shadowbats" - Shadowbats are mobs before you fight Varo'then/Mannoroth

**Comment by trolloh** [comment]
Also looks like bosses dont give reps, as you can see in Jaina/Murozond videos. Will edit the post

**Comment by TranceAccount** [comment]
The thing is, the players in the videos need to have a tabard equiped with a faction that they are not exalted with yet. This makes getting the values quite hard...

**Comment by TranceAccount** [comment]
WTB values :(
This is so annoying

**Comment by TranceAccount** [comment]
Jaina gives 250 reputation (275 with bonus): https://youtu.be/hyygwnWfHLc?t=1m56s

**Comment by trolloh** [comment]
Basically its 15 in general like in normal dungeons, I think that would do the thing, need to only know the rest bosses.
Good job on searching

**Comment by TranceAccount** [comment]
Partially fixed for ET because I didn't add values to the mobs at Emerald Shrine and to Murozond. It felt wrong and didn't have proof.

**Comment by TranceAccount** [comment]
Well of Eternity should now have reputation in rev. 5854.

**Comment by TranceAccount** [comment]
Fixed in rev. 5855.
