### ISSUE TITLE
[EN][SPELL][MAGE] Mirror image & glyph of mirror image

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#10156]
**Description**: clones use arcane blast when they supose to use firebal with glyph present

**Current behaviour**: they cast arcane blast as if i play arcane

**Expected behaviour**: glyphed in miirori mage my clones should use fireballs if im fire and arcaneblast if im arcane, 

**Steps to reproduce the problem**:
1. be mage
2.  have glyph
3.  summon clones
4. use eyes or skada or recount to chek what clones cast

**Revision**: Current server version

**Comment by pelekon** [comment]
fixed
