### ISSUE TITLE
Guild Page and Herald Issue

### ISSUE THREAD

**Issue by Maraad** [Atlantiss/BugTracker#10169]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: There seems to be an issue with the Guild Page and Herald when summoned. It doesn't allow you to buy/sell anything to the companion pet.

**Current behaviour**: When you summon the pet you are not able to sell/ buy anything off of it.

**Expected behaviour**: You should be able to buy guild rewards and vendor things to the pet.

**Steps to reproduce the problem**:

1. Gain required reputations to gain access to said companion pets
2. Buy said companion pets.
3.  Summon it and it is useless only making it a normal pet with a cooldown.

**Revision**: Patch 4.3.4

**Comment by TranceAccount** [comment]
Duplicate #9183, #7548, #10141.
Missing wowhead link, proof.
Title is wrong
