### ISSUE TITLE
[EN][Spell] Khorium Champion

### ISSUE THREAD

**Issue by ripara** [Atlantiss/BugTracker#10164]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The weapon has a chance on hit proc but it seems that it is bugged since the weapon doesn't proc at all .

**Current behaviour**: Nothing is happening (no procs) . 

**Expected behaviour**: The weapon is suppose to have on hit proc : self heal for 360 hp + 120 str for 30 seconds .

**Steps to reproduce the problem**: 

1. Attack a target (better hit a dummy) .
2. Wait .
3. No proc at all .

**Revision**: 5848

**Comment by TranceAccount** [comment]
Chance on hit is broken in general. #8171

**Comment by TranceAccount** [comment]
https://www.wowhead.com/item=23541/khorium-champion
