### ISSUE TITLE
[EN][Talent][Shaman] Focused Insight

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#10174]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: "Focused Insight" 3/3 does not reduce the mana cost of your next heal by 75%.
http://wowwiki.wikia.com/wiki/Focused_Insight
https://imgur.com/Vmk1mNt
https://imgur.com/IUCUWtK

**Current behaviour**: It looks like "Focused Insight" 3/3 reduces the mana cost of your next heal by the amount of mana you used to cast the shock spell. (NOT confirmed)

**Expected behaviour**: "Focused Insight" 3/3 should reduce the mana cost of your next heal by 75%.

**Steps to reproduce the problem**:

1. Look at the mana cost of any heal.
2. Cast a shock spell to proc "Focused Insight".
3. Look at the mana cost of the same heal as you did in step 1

**Revision**: ACore rev. 5853 hash. e567c8d41823 2018-08-09 13:15:28 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Psychobird7** [comment]
https://imgur.com/wbHJUnG      
Tooltip is pretty clear about it.

**Comment by Aival94** [comment]
Yep. This is not a bug but how it is supposed to work. It decrease by 75% of the amount of the mana of the shock spell that got used.
