### ISSUE TITLE
[EN][NPC] Alizabal 

### ISSUE THREAD

**Issue by Hartwall** [Atlantiss/BugTracker#10171]
http://www.wowhead.com/spell=105067/seething-hate

Description: Alizabals seething hate debuff gets replicated by a player with Dragonwrath taregcosa's rest

What happens is alizabal makes the player the source of the damage instead of alizabal itself. Only the aoe should be placed on the player, not the source of the damage itself.

**Expected behaviour**: Alizabal should still be the source of the damage, not the player itself.

**Steps to reproduce the problem**:

1. Alizabal applies seething hate debuff on a player
2. player becomes the source of the damage of seething hate damage instead of alizabal
3. watch as you deal damage to friendly players around you

ACore rev. 5853 hash. e567c8d41823 2018-08-09 13:15:28 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by pelekon** [comment]
fixed in rev 5891
