### ISSUE TITLE
[EN][Cataclysm][Dungeon][Well of Eternity][Quest] Documenting the Timeways

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#10179]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: One of the recently added WoE quests is bugged

**Current behaviour**: when you kill a Legion Demon, it doesnt count

**Expected behaviour**: It should count as Legion Demon archived 1/1

**Steps to reproduce the problem**:

1.  Get into WoE
2.  Accept the quest Documenting the Timeways
3.  Kill the Demon Lords, see it doesnt count
It worked in the first days

**5854**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
Can you tell me if you were close to him or not?

**Comment by TranceAccount** [comment]
You only get credit for the first legion demon, and you need to be in range when he is killed.

**Comment by TranceAccount** [comment]
And for the other objectives?

**Comment by trolloh** [comment]
They work, just the Legion Demon not

**Comment by TranceAccount** [comment]
In the picture I can see that all your party members got the credit (visual), except you. I can't really reproduce this by myself, nor test it on PTR, so when I push a fix for this, you will have to give feedback.

**Comment by trolloh** [comment]
Okay sure
Im gonna delete my cache folder aswell

**Comment by TranceAccount** [comment]
Potential fix in 5856. Please test when the server gets updated.

**Comment by trolloh** [comment]
it works now, thanks for your help

**Comment by TranceAccount** [comment]
Cool, thanks for testing. :)
