### ISSUE TITLE
[EN] [General] [GCD] GCD when swapping weapons IC/OOC

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#10183]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: While in Combat it triggers a global Cooldown when swapping weapons, out of combat this dosent happen.

**Current behaviour**: While in Combat it triggers a global Cooldown when swapping weapons, out of combat this dosent happen.

**Expected behaviour**: Weapon swapping should never trigger a GCD no matter if in combat or not afaik.

**Steps to reproduce the problem**:

1. Duel/attack a dummy
2. Swap your weapon while being in combat
3. GCD getting triggered.

Video to show problem: https://www.youtube.com/watch?v=NapCNTQCdgo&feature=youtu.be

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://eu.battle.net/forums/en/wow/topic/2313912791#post-2
30 Jun 2011
I'm not sure I understand you, but swapping weapons in combat has caused a global cooldown for a long time.

**Comment by Heroclassx** [comment]
Damn, my bad then, topic can be closed
