### ISSUE TITLE
[EN][Spell][Warrior] Spell Reflecting hunter traps

### ISSUE THREAD

**Issue by lancer1st** [Atlantiss/BugTracker#10187]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
Hunters freezing traps are supposed to freeze the hunter if a warrior using spell reflect runs over them.
**Current behaviour**:
If warrior using spell reflect runs over a freezing trap the trap dissapears not freezing warrior but not freezing hunter either
**Expected behaviour**:
When warrior using spell reflect runs over it, it should freeze the hunter
**Steps to reproduce the problem**:

1. Be a warrior
2. Use spell reflect
3. Run over a hunters freezing trap

**Revision**:5857

**Comment by Piklo** [comment]
video from retail?

**Comment by Razfury** [comment]
https://www.youtube.com/watch?v=ojTZ2smQmhQthe vid is from WoD (Beta) but this has been in since wotlk.
