### ISSUE TITLE
[EN] Stonetalon mountains quest Ashes to ashes 

### ISSUE THREAD

**Issue by Whujubi** [Atlantiss/BugTracker#10182]
Stonetalon mountains quest Ashes to ashes

Bugs you can use flamethrower but it doesnt set tent on fire or count as tent burned

**Comment by TranceAccount** [comment]
Please use the search option before reporting anything. #10111
Also use the template.

**Comment by groumulous** [comment]
Problem still exists. Flamethrower throws flame, tents do not burn, no credit given for burning tent.
