### ISSUE TITLE
Feral Spirit

### ISSUE THREAD

**Issue by Noquestionsasked** [Atlantiss/BugTracker#10197]
**Description**: I can't use Feral Spirits on Madness of Deathwing

**Current behaviour**: Pressing the keybind for Feral Spirits on Madness of Deathwing doesn't summon the wolves neither does clicking the spell

**Expected behaviour**: Using the keybind should cast the spell
**Steps to reproduce the problem**:

1. Be Enhancement at Madness of Deathwing
2. Try to use Feral Spirits
3. See you can't summon the wolves and cry / reroll to Ret paladin

**Revision**: rev 5857

**Comment by Axelitoo** [comment]
Alright so:
1. This has nothing to do with the spell not being cast
2. Follow the template
3. There's already a much better report regarding this bug
