### ISSUE TITLE
[EN][Item] Gurthalak, Voice of the Deeps, excessive proc rates

### ISSUE THREAD

**Issue by Flinvoltx** [Atlantiss/BugTracker#10195]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Gurthalak, Voice of the Deeps has excessive proc rates.

**Current behaviour**: 
![kek](https://user-images.githubusercontent.com/30041703/44846678-b693b380-ac59-11e8-86d0-fe34eede5f15.png)

**Expected behaviour**: What should happen instead

![123](https://user-images.githubusercontent.com/30041703/44847161-33735d00-ac5b-11e8-90b3-bb5c32059bfc.png)

http://www.worldoflogs.com/reports/rt-f3177158hp2b3u9j/sum/damageDone/?s=4012&e=4157#Paladion
http://www.worldoflogs.com/reports/4gp9bnnwu4570d9w/sum/damageDone/?s=477&e=748#Bellora
http://www.worldoflogs.com/reports/2nh3fjr8lcdlirei/sum/damageDone/?s=1758&e=2037#Verees%C3%A0
http://www.worldoflogs.com/reports/tduvjn595t60swv7/sum/damageDone/?s=796&e=1004#Imer

**Steps to reproduce the problem**:

1. Try dummy
2. Observe DS raid logs

**Revision**: Test realm 5859, but same happens on live

Note: Whole problem could be realted to faulty trigger check. By that i mean it can have 2% proc chance but tentacle proc could happen not only from melee swing as it should be.
Gamebreaking for PvP.

As per wowhead comments: 
The following details reflect the Normal version (403 ilevel):
    Your special weapons swings have a 2% chance to spawn a stationary tentacle on the ground.
https://www.wowhead.com/item=78478/gurthalak-voice-of-the-deeps#comments:id=1584215

As per YouTube movie:
https://www.youtube.com/watch?v=XPyMdpkzLfc

**Comment by Axelitoo** [comment]
10 milion feels a tad low considering how RNG it is. Had entire Ultraxion with one tentacle on Retribution at 13 milion or so damage. More testing is probably required.

**Comment by Axelitoo** [comment]
10 milion feels a tad low considering how RNG it is. Had entire Ultraxion with one tentacle on Retribution at 13 milion or so damage. More testing is probably required.

**Comment by Psychobird7** [comment]
Interesting. 

As Axel said, the single 6min parse you linked as evidence is statistically, completely irrelevant.   
Might want to bring more convincing testing, including raid buffs etc.  

The proc rate was confirmed to me by both Pelekon and Piklo to be 2%; Piklo also tested the triggering abilities on a ret paladin, and they were correct.           
It is possible that Warriors/DKs are getting incorrect proc rates, but for Paladins they are definitely correct. 

Further: 
"279 strikes (not counting sweeping strikes and mastery swings)" 
Arms mastery procs *should* proc Gurthalak. 

"As per wowhead comments: [...]" 
This comment is incorrect, as "special weapon swings" (whatever that is meant to mean) are not how the weapon works -- it is meant to proc from any melee attack or attack considered as melee, which includes melee swings, every melee ability in the game (minus Bloodthirst) . 
It is also dated from 4.2, which means that person's testing was done on PTR/beta.

**Comment by Aloise3** [comment]
You’re aware that the WoL percentage you displayed are percentage of the whole raids dps, right? I don’t see why you would otherwise post those pictures.

**Comment by Flinvoltx** [comment]
Official logs ranges from 0.9% to 5% depending on fight type, while i haven't saw anything lower like 3% on Atlantiss. It is very often seen 2-3 tentacles damaging at once from one person, while 2% means 100-150 strikes in average to proc this sum of tentacles. The chance of 3 tentacles at once from less than 5 strikes to solo target should be rare occasion.
Need more raid data to clarify chances, I can't provide this amount of data alone.

Counting mastery strikes for warrior makes chances even less.
Provided screen with reports on percantage shows, that gurthalak does about 8-10% dmg on Yorsahj fights (probably with trash), but no way it is 16%.

**Comment by freddie12** [comment]
You have a simple mistake with your math here on that WoL data. 
 For the first one: the paladin named Paladion had done 8.5 million damage in total and his/her tentacles had done 0.83 million. If you do the simple math 0.83 / 8.5 , you will get around 0.097. In other words, Tentacles had done almost 10% of its total damage and you will see your argument is invalid. Just do the mat properly.

**Comment by Flinvoltx** [comment]
freddie12 It was 8-10% and not 16%, yes. And also i made chance proc calculation dependent on number of hits. Wasn't telling that tentacle part of their damage=proc chance.
