### ISSUE TITLE
([EN][NPC] Voidwalker Minion

### ISSUE THREAD

**Issue by Nasudaa** [Atlantiss/BugTracker#10215]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The Voidwalker Minions in Skull Rock (Durotar) should normaler EITHER despawn after you kill the Burning Blade Apprentice OR being able to be damaged by shadow spells.

**Current behaviour**: Voidwalkers dont despawn and are immune to shadowspells, can only be damaged by a immolate as warlock

**Expected behaviour**: They can either despawn or beeing damaged

**Steps to reproduce the problem**:

1.  Fight them with shadowspells
2. Kill Apprentice
3. 

**Revision**: rev: 2060, content patch: 203

**Comment by wtRCH** [comment]
If it's Netherwing Bug then: voidwalkers minions shouldn't despawn after their owner dies (it's blizzlike) and you can't damage them by shadow spells (it's blizzlike too)
