### ISSUE TITLE
[EN][Item] Ti'tahk, The Steps of Time

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#10211]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The haste granting to allies should be 386.

**Current behaviour**: The weapon gives 1928 haste to allies instead of 386.

**Expected behaviour**: The weapon should give 386 haste to allies not 1928.

**Steps to reproduce the problem**:

1. Get someone in party
2. Attack a dummy
3. 

**Revision**: 5864

**Comment by TranceAccount** [comment]
Wowhead link...

**Comment by Piklo** [comment]
works fine for both normal and heroic
![image](https://user-images.githubusercontent.com/16057987/48285403-ca7e4180-e462-11e8-8dcd-90e733b1c2df.png)
![image](https://user-images.githubusercontent.com/16057987/48285457-f00b4b00-e462-11e8-8506-9bed48e235be.png)
