### ISSUE TITLE
[EN][Character Info] Still Red after Repair or Replacement of Broken Amor

### ISSUE THREAD

**Issue by Steverus1** [Atlantiss/BugTracker#10212]
**Description**: If I repair or replace armor or weapon that has zero durability, the red frame at the item slot doesn't disapear. The infographic on the right side also still shows the armorpiece/weapon in red.

**Current behaviour**: after reparation or replacement of broken armor/weapons, the red frame on the item slots remains and the infrographic still shows red.

**Expected behaviour**: red frame should instantly disappear on the itemslot. infographic on the right side also should instantly vanish or refresh.

**Steps to reproduce the problem**:

1. Die until your armor or weapon goes to zero durability points. (maybe you need multiple broken armor pieces for the problem-reproduction)
2. go to a vendor and repair the item manually (not used "repair all" function) or replace the item
3. check if the red frame disappears and the info-graphic gets refreshed.

**Revision**: 2037

**Comment by Piklo** [comment]
cannot reproduce, probably client or addons
