### ISSUE TITLE
[EN][Paladin][Talent] Denounce

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1022]
Denounce is a Holy Paladin talent, which reduces the mana cost of Exorcism by 75%, along with Holy Shock critical strikes making Exorcism an instant cast. The issue is that occasionally, when you teleport from one zone to another, for example teleporting in a dungeon through RDF, the talent bugs out in such a way that it doesn't reduce the mana cost of Exorcism at all. Even though you have the talent, the mana cost isn't reduced. So far, the only way to fix it is by relogging.

**Comment by Wolffenstein** [comment]
Fixed in rev 4276.
