### ISSUE TITLE
[EN][Quest][Item][Rogue] Cluster Clutch

### ISSUE THREAD

**Issue by azncoolz** [Atlantiss/BugTracker#10229]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Drop rate of Elementium Gem Cluster (https://www.wowhead.com/item=77952/elementium-gem-cluster) is buged on 10m and 25m.

**Current behaviour**: All the bosses don't have a 100% drop rate (bosses with loot chests have a 0% drop rate Ultraxion+Spine+Madness).
Also, bosses on 25m drop just 1 Elementium Gem Cluster too often.

**Expected behaviour**: 
On 10m every boss must have a 100% chance to drop 1 Elementium Gem Cluster, including Ultraxion+Spine+Madness. You should always get 8 Elementium Gem Clusters per full run on 10m.

On 25m every boss must have a 89% chance to drop 2 Elementium Gem Clusters, a 10% chance to drop just 1 Elementium Gem Cluster and a 1% chance to drop 3 Elementium Gem Clusters.

https://ptr.wowhead.com/guide=441/a-legendary-undertaking-helping-your-rogue-pick-up-a-pair-of-fangs#acquisition-rates
https://www.wowhead.com/quest=30107/cluster-clutch#comments
https://www.wowhead.com/item=77952/elementium-gem-cluster#comments
https://www.mmo-champion.com/threads/1049311-quot-You-Receive-loot-3x-Elementium-Gem-Cluster-quot-Say-what
https://www.mmo-champion.com/threads/1024351-Fangs-of-the-Father-F-A-Q

**Steps to reproduce the problem**:

1. Be a rogue with Cluster Clutch quest, go to Dragonsoul raid 10m and 25m.
2. Kill bosses.
3. Notice that not every boss drops Elementium Gem Cluster and chests from ultra+spine+madness never drop, and bosses on 25m drop just 1 Elementium Gem Cluster too often.

**Revision**: 5880

**Comment by Piklo** [comment]
should be fixed in rev. 5908
