### ISSUE TITLE
[EN][Quest][Item][Rogue]Rogue Legendary-Cluster Clutch

### ISSUE THREAD

**Issue by Phasmophobia** [Atlantiss/BugTracker#10226]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Every boss is supposed to drop 1 cluster in 10man and give 3-9 Shadowy Gem
**Current behaviour**: Everyboss isn't dropping a cluster and when the cluster is opened it doesn't give any Shadowy Gem

**Expected behaviour**: Every boss to should atleast 1 cluster and give 3-9 Shadowy Gem when opened

**Steps to reproduce the problem**:

1.kill a boss in DS while on quest 
2. get Elementium Gem Cluster
3. Open Cluster to get nothing.

**Revision**: 5869 hash. 6588d2164350 2018-09-28 14:00:41 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by pelekon** [comment]
Fixed in 5876
