### ISSUE TITLE
Ds hc spine tendon bug

### ISSUE THREAD

**Issue by Wasalaiv** [Atlantiss/BugTracker#10227]
**Description**: The tendon is not supposed to be interrupted with any interrupt ability when the cast is nearly done, should be either considered as immune or evade.

**Current behaviour**: The tendon fails it's cast near the end when a player uses an interrupt spell, so the tendon stays up until it dies, that should not happen.

**Expected behaviour**: The tendon should go down when the cast ends.

**Steps to reproduce the problem**:

1.Kill amalgamation with 9 stacks
2. Plate opens, raid is focusing on the tendon.
3. Tendon is interrupted near the end of the cast.

**Comment by pelekon** [comment]
Fixed in 5876

**Comment by Wasalaiv** [comment]
Thank you good sir
