### ISSUE TITLE
[En][Quest][Small Comforts][[Twilight Highlands][Alliance[

### ISSUE THREAD

**Issue by faustisama** [Atlantiss/BugTracker#10235]
Mission objects do not appear

-Meara's Dried Roses
-Parlan's Ivory Hammer
-Aprika's Doll

[https://www.wowhead.com/quest=27805/small-comforts](url)

**Comment by TranceAccount** [comment]
Have you waited for the respawn times?
Have you looked good enough, because I have done this quest before without any issues?
Have you perhaps relogged which might have changed your phase?
Why do you not follow the template?
