### ISSUE TITLE
[EN][Raid][Dragon Soul][Hagara][HC] Frost Phase

### ISSUE THREAD

**Issue by Arokher** [Atlantiss/BugTracker#10242]
**Description:** Ice structures moving and boss becoming immune to any damage permanently

**Current behaviour:** When frost phase starts and the raid has any pets active ( Hunter pets, warlock pets, dk pets etc ) the ice structures are following pets around the area and also making Hagaras Frozen Tempest ability  bug so it becomes permanent even after killing the structures meaning u cant kill the boss

**Expected behaviour:** Ice Structures not moving out from their places even that raid has any kind of pets active and boss not becoming perma immune to damage after destroying all 4 ice structures

**Steps to reproduce the problem:** 

1. have hunter pets , dk pets ( even bloodworms ), warlock pets etc active from the start
2. get into Frost Phase
3. get to the edge to destroy structures while pets are hitting either the Ice Structures or Hagara herself
4. after u have destroyed all 4 ice structures , try hit the boss and u notice that its immune to all damage

**Revision:** Acore rev. 5905 hash. a2db3c01e6f5 2018-10-24 17:39:06 +0200 (4.3.4 branch)

**Comment by Piklo** [comment]
Potentialy fixed in rev. 5914. Please comment this post or open new one if not fixed

**Comment by Arokher** [comment]
Hagara Frost phase Ice structures still following pets even after the rev 5914 fix

**Comment by Arokher** [comment]
Providing Video material from both Bugs either today / tomorrow once ive done the editing

**Comment by Arokher** [comment]
From Piklos request heres some video mats to help out with these 2 bugs. 
Rev. 5918
Rogue PoV Hagara 10hc ( Cosmic Powa Guild run 2.12.2018 )
https://www.youtube.com/watch?v=mgpmXypVnkg

Ice structures following pets bug from 0:00 - 2:40 
( keep an eye on the Red Wind Serpent )

Hagara becoming perma immune to all  damage from 4:55 - 7:10 
( this bug has happened also on the very first Frost Phases when there is over 6 minutes left on berserk timer )
