### ISSUE TITLE
[EN][Item][Trinket]Moonwell Chalice rev. 5911

### ISSUE THREAD

**Issue by Coldsteel12** [Atlantiss/BugTracker#10245]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** since last update (today at noon) doesnt work
**Current behaviour:** just doesnt give the buff "Blessing of the Moonwell"
**Expected behaviour:** It should give that buff
**Proof:** 
![wowscrnshot_111418_170850](https://user-images.githubusercontent.com/39312136/48491990-df2f5080-e839-11e8-8903-768ae6c21377.jpg)

**Steps to reproduce the problem:**

1. Buy and equip this trink
2. use and realise
3. fix

**Revision:** Current server revision (You can see current server revision by typing ".server info" in the in-game chat.)

**Comment by Piklo** [comment]
should be fixed in rev. 5912
