### ISSUE TITLE
[EN][Quest][Winterspring] Borrowing From the Winterfall

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/BugTracker#10243]
Related issues:
#9714
#9787
#8646

**Comment by TranceAccount** [comment]
I have a potential fix which I am currently testing.

**Comment by TranceAccount** [comment]
For some reason it only increments the quest status, but doesn't show that it is incremented..

**Comment by TranceAccount** [comment]
Fixed in rev 5915.
