### ISSUE TITLE
([EN][Mount] Traveler's Tundra Mammoth' vendors (Gnimo and Hagmul)

### ISSUE THREAD

**Issue by Coldsteel12** [Atlantiss/BugTracker#10246]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Gnimo and Hagmul of Argus (mobs o this mount) keep staying only for 3-4 sec, then they just disappear

**Current behaviour:** 
**Expected behaviour:** they should sit on their places till i dismount or eject them
**Proof:**
![wowscrnshot_111418_190400](https://user-images.githubusercontent.com/39312136/48495085-4bad4e00-e840-11e8-8859-84d7029c4a67.jpg)

**Steps to reproduce the problem:**

1. Mount UP
2. wait for 3-4 secs
3. Profit

**Revision:** Current server revision (You can see current server revision by typing ".server info" in the in-game chat.) 5911

**Comment by Piklo** [comment]
should be fixed in rev. 5912
