### ISSUE TITLE
[EN][Profession][Mining Trainer] Mining trainers in Og and Tb not working

### ISSUE THREAD

**Issue by knoedel001** [Atlantiss/BugTracker#10254]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Mining training window not available at some trainers.

**Current behaviour:** At least the mining trainers in Orgrimmar and Thunderbluff don't have a training window to skill mining. Instead, a dialog with the Option "Train me" opens, nothing happens when clicking on it. 

**Expected behaviour:** The window should pop up when you click on the trainer or after clicking the "Train me" dialog option. A trainer working as expected can be found at Razor Hill.

**Proof:**

**Steps to reproduce the problem:**

1. Learn Mining
2. Skill to 75
3. Try to train at a trainer.

**Revision:** ACore rev. 5916, Hash a978022b6c88

**Comment by Bildo** [comment]
fixed
