### ISSUE TITLE
[EN][Raid][Dragon Soul][Yor'sahj the Unsleeping] Deep Corruption

### ISSUE THREAD

**Issue by Noquestionsasked** [Atlantiss/BugTracker#10258]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Yor'sahj the Unsleeping's Deep Corruption ability is proccing off of heals its not supposed to (Death Strike, Word of Glory, Beacon of Light....)

**Current behaviour:** Using the spells listed above causes the target of the heal to get a stack of Deep Corruption
**Expected behaviour:** The spells listed above are part of a list of spells that do no cause stacks of Deep Corruption

**Proof:**
https://www.icy-veins.com/wow/yor-sahj-the-unsleeping-strategy-guide-normal-heroic

".... It is interesting to note that certain heals do not trigger this effect. We cannot provide a comprehensive list, but we will list those that we are aware of:

Lay on Hands, Word of Glory and any healing transfered through Beacon of Light;
Prayer of Mending;
Death Strike and the absorb from Mastery: Blood Shield;
on-proc effects (Maw of the Dragonlord, trinkets procs, etc).
......"

https://www.wowhead.com/spell=105171/deep-corruption#comments:id=1610080

https://www.youtube.com/watch?v=X9bm-sYbByE

" at 0:25 Blood Shield is refreshed, meaning a Death Strike has been used, yet no new stacks appeared. "

https://www.youtube.com/watch?v=Tvsx0msiefg

2:32 The paladin receives a beacon heal, no new stacks received.
2:35 The paladin receives a word of glory, no new stacks received.

**Steps to reproduce the problem:**

1. Start the heroic Yor'sahj the Unsleeping fight as a Death Knight or a Paladin
2. Wait for the boss to apply Deep Corruption and Use Death Strike, Word of Glory or beacon of Light
3. Gain stacks of Deep Corruption

**Revision:** 5918 hash. 282c041b7460

**Comment by Piklo** [comment]
duplicate #10230
