### ISSUE TITLE
[EN][NPC] Stephanos <Hippogryph Master>

### ISSUE THREAD

**Issue by AMGarkin** [Atlantiss/BugTracker#10253]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Hippohryph Master Stephanos in The Exodar doesn't work.

**Current behaviour:** You can click "I desire to travel by hippogryph." but nothing happen.

**Expected behaviour:** It should open the flight map and you should be able to flight from there to Azure Watch or whatever destination you have opened.

**Proof:** What kind of proof should I have? Just try it, its easy to test.

**Steps to reproduce the problem:**

1. Interact with Stephanos
2. Click the only option in there: "I desire to travel by hippogryph."
3. And that's it.

**Revision:** ACore rev. 5916 hash. a978022b6c88 2018-11-17 14:46:08 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Bildo** [comment]
fixed
