### ISSUE TITLE
Serious bug with how spells are considered cast

### ISSUE THREAD

**Issue by parlaking** [Atlantiss/BugTracker#10262]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Describe the problem

There are side effects of the delay it takes for a spell to be considered cast. I don't know if it's the spellbatching or not, because I don't recall this happening a few weeks ago and I was told there have been no recent changes to spell batching. But I could have just not noticed it a few weeks ago.

**Current behaviour:** What happens

Certain spell procs that rely on casts being considered 'cast' aren't behaving properly.
The easiest example of this is with a druid with the balance tree talent Nature's Grace. I will outline the steps to reproduce the problem below.

**Expected behaviour:** What should happen instead

The casts should be properly accounted for.

**Proof:**

**Steps to reproduce the problem:**

1. Make a druid, get the talent Nature's Grace
2. Spam starfire onto target dummy as fast as you can
3. After you crit, keep spamming it. You'll notice that your next cast does not consume nature's grace.
4. Do the same thing except wait ~300-500ms (the weird spell delay) after each starfire cast ends before casting the next starfire. You will notice that your next starfire will be properly consumed.

So there's a disconnect between the spell cast delay system and what it considers to be a cast if it's cast before or after the delay system. Especially considering that half of the Nature's Grace proc works immediately (the -0.5 second cast time part), while the other half (the internal 'look for completion of cast' part) is improperly interacting with the cast delay system.

**Revision:** Current server revision (You can see current server revision by typing ".server info" in the in-game chat.)

**Comment by Piklo** [comment]
are you sure you wanted to post it on cata bugtracker? :P

**Comment by Aloise3** [comment]
@Piklo you automatically became a NW dev also

But seriously, read where you are posting
