### ISSUE TITLE
[EN][Quest][Netherstorm] Becoming a Spellfire Tailor

### ISSUE THREAD

**Issue by nallac** [Atlantiss/BugTracker#10261]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Describe the problem
After accepting the quest [Becoming a Spellfire Tailor](https://www.wowhead.com/quest=10832/becoming-a-spellfire-tailor), travelling to Netherstorm and using the [Nether-wraith Beacon](https://www.wowhead.com/item=31742/nether-wraith-beacon) brings about the bug: two [Furious Nether-wraiths](https://www.wowhead.com/npc=22408/furious-nether-wraith) spawn before the channeling is complete and, on occasion, a third [Furious Nether-wraiths](https://www.wowhead.com/npc=22408/furious-nether-wraith) will spawn (after the "arcane explosion" effect) if you allow the channeling to complete.

**Current behaviour:** What happens
Two [Furious Nether-wraiths](https://www.wowhead.com/npc=22408/furious-nether-wraith) spawn before the channeling of the [Nether-wraith Beacon](https://www.wowhead.com/item=31742/nether-wraith-beacon) is complete. Sometimes, a third [Furious Nether-wraith](https://www.wowhead.com/npc=22408/furious-nether-wraith) will spawn if you allow the channeling to complete.

**Expected behaviour:** What should happen instead
Two [Furious Nether-wraiths](https://www.wowhead.com/npc=22408/furious-nether-wraith) should spawn after the channeling is complete.

**Proof:**
[Here is a video demonstration of the bug.](https://youtu.be/H_NVkSxN3yw)

**Steps to reproduce the problem:**
1. Acquire a character with 350 Tailoring who is level 60 or higher.
2. Accept the quest [Becoming a Spellfire Tailor](https://www.wowhead.com/quest=10832/becoming-a-spellfire-tailor) from [Gidge Spellweaver](https://www.wowhead.com/npc=22213/gidge-spellweaver) in Shattrath City.
3. Travel to Netherstorm and use the [Nether-wraith Beacon](https://www.wowhead.com/item=31742/nether-wraith-beacon). Allow the channeling to complete despite being attacked the by the prematurely spawned [Furious Nether-wraiths](https://www.wowhead.com/npc=22408/furious-nether-wraith).

**Revision:** Current server revision (You can see current server revision by typing ".server info" in the in-game chat.)
2407

**Comment by Piklo** [comment]
its dragonwrath (cataclysm) bugtracker, not Netherwing (tbc)

**Comment by nallac** [comment]
Thank you very much for pointing this out, Piklo! I'm terribly sorry as I didn't notice where I was posting. I'll correct this immediately.
