### ISSUE TITLE
Shamans Mana Spring-Totem

### ISSUE THREAD

**Issue by Siebtenn** [Atlantiss/BugTracker#10276]
So, the problem is, the bonus after we place the totem down is = 0, we got the Icon which suggest that we got the BUFF on us, yet not only it doesn't give us the bonus see Image one and two by clicking on link.
https://imgur.com/a/zgYzbHj  without Mana Spring
https://imgur.com/a/OpMEvUS  with Mana Spring
https://imgur.com/a/V2S9lJA  you can see i got IMPROVED MANA SPRING TOTEMS still the same mana regen also check how much it should give me 11 to 12
https://imgur.com/a/XWjjCDM  current mana = 5
https://imgur.com/a/X1yCVTF  after regen = 16 which gave me a total of 11 mana regen which means i got 4 mana included on my regen after i casted a spell ... pathetic
now let's see after i eat a Greater Sage Food.
https://imgur.com/a/b3whIEo Without Greater Sage food
https://imgur.com/a/it0Qk0A  with Greater Sage Food which clearly states that gives me 6 mana regen
https://imgur.com/a/Uisw8b9  you can see that my well fed buff Gives me in my Regen those 6 bonus mana regen.

**Comment by Piklo** [comment]
wrong expansion
