### ISSUE TITLE
Demon armor  

### ISSUE THREAD

**Issue by Vorborg91** [Atlantiss/BugTracker#10278]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Describe the problem
When i put on my demon armor rank 3, it automatically becomes demon armor rank 2 on. I tried deleting the WDB folder as your GM said, but it didn't work.

**Current behaviour:** What happens
Stated above. Rank 3 becomes rank 2 when applied.

**Expected behaviour:** What should happen instead
It should be the rank i take on.
**Proof:**
![WoWScrnShot_031119_054207](https://user-images.githubusercontent.com/48426819/54101003-a5beba00-43c1-11e9-8c0f-9367ec2445be.jpg)
![WoWScrnShot_031119_054210](https://user-images.githubusercontent.com/48426819/54101008-a8211400-43c1-11e9-9099-3d7aa6eac02e.jpg)

**Steps to reproduce the problem:**

1.  Make the ranks fit with the rank i have.
2. 
3. 

**Revision:** Current server revision (You can see current server revision by typing ".server info" in the in-game chat.) 
Thank you

**Comment by Piklo** [comment]
wrong bugtracker, its cata one
