### ISSUE TITLE
([EN][NPC][Hellfire Peninsula] Marauding Crust Burster

### ISSUE THREAD

**Issue by phantom1004** [Atlantiss/BugTracker#10277]
**Description:** If engaging the NPC in stealth, it doesn't tunnel through the surface however continues to attack

**Current behaviour:** Stays underground being impossible to target and killing the player

**Expected behaviour:** When engaged during stealth either by being noticed in stealth, or opening attack in stealth, it should pop through the ground

**Proof:** Difficult for me to prove, just engage one in stealth and see for yourself

**Steps to reproduce the problem:**

1. Find rumbling ground
2. get into aggro range in stealth
3. either be detected or attack when it bursts thru

**Revision:** 2825

**Comment by Piklo** [comment]
its cata realm bugtracker
