### ISSUE TITLE
[EN][NPC] Essence of Anger

### ISSUE THREAD

**Issue by Refuge001** [Atlantiss/BugTracker#10291]
[/]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

[/]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in the nearest future - others. It is important to determine at the beginning of a title in which language the report will be written by using the symbols [EN] or [PL].)
[/]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[/]: # (Write your title according to the format:)
[/]: # ([EN][Quest][Zone] A Vision of the Past)
[/]: # ([EN][NPC] Thoralius the Wise)
[/]: # ([EN][Spell][Class] Frostfire Bolt)
[/]: # ([PL][Talent][Class] Brain Freeze)
[/]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[/]: # ([EN][NPC][Drop] Thoralius the Wise)
[/]: # ([EN][Web] Armory doesnt work)

**Description:** Describe the problem
Essence of Anger is currently casting Spite on tanks - which is causing them to go immune and drop threat temporarily. Included are two pictures of recount taken of our warrior and paladin tank both having spite cast on them on different attempts. (It happened every attempt).
- Spite: 3 random targets get a debuff which grants 2 sec immunity, then deals 7444-7556 nature damage followed by another 2 sec immunity.

**Current behaviour:** Tank becomes immune causing him to lose threat, causing Boss to attack next highest threat, which causes the Seethe debuff on the entire raid.

**Expected behaviour:** What should happen instead
He should not cast Spite on tanks.
**Proof:**
![Spite1](https://user-images.githubusercontent.com/48739878/80783192-88592c00-8b3e-11ea-8c73-732bc5670c97.PNG)
![Spite 2](https://user-images.githubusercontent.com/48739878/80783200-8d1de000-8b3e-11ea-94a4-92863e730b50.PNG)

**Steps to reproduce the problem:**

1. Attack Essence of Anger
2. Wait until he casts Spite on a tank
3. Profit

**Revision:** Current server revision: 3338 
(You can see current server revision by typing ".server info" in the in-game chat.)

**Comment by pelekon** [comment]
@Refuge001 wrong bugtracker, its old BT of cata realm.
