### ISSUE TITLE
[EN][Rogue][Spell] Combat Readiness

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1029]
<s>1.There should be an internal cooldown for stacking Combat Insight buff. I couldn't find anywhere useful information about duration of this ICD, it's kinda short, not longer than 1 second</s> // Not 100% sure if there was an ICD.

2.Combat Insight expiration should remove Combat Readiness buff from the rogue but it doesn't on main.
https://www.youtube.com/watch?v=6jgxC3YDLjM // Movie from early Cata.
http://cata.openwow.com/spell=74001 // Combat Readiness
http://cata.openwow.com/spell=74002 // Combat Insight

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
