### ISSUE TITLE
[EN][Paladin][Spell] Holy Shock

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1031]
When you use Holy Shock with your back facing the enemy target, which you have selected, the cooldown starts, although you have not actually damaged the target, since he has to be in front of you. If you try to cast Holy Shock on an enemy unit with your back facing them, you should receive an error message that the target must be front of you, without the 6 seconds cooldown starting.

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
