### ISSUE TITLE
[PL][Death Knight] Blood of The North

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1045]
http://cata.openwow.com/spell=54637

Buguje się po śmierci i daje blood runy bez możliwości zamiany. Pomaga respec
Nie jestem jeszcze pewien w jaki sposób się buguje, ale podejrzewam, że działa to tak, że jeśli umrzemy gdy jakaś death runa jest na CD to ta runka po wskrzeszeniu będzie blood.

**Comment by Wolffenstein** [comment]
Kilkanaście różnych prób i nie udało mi się zreprodukować buga. Jeżeli dalej będzie się bugowało i będziesz miał jakiś pewny sposób na zbugowanie tego to proszę o nowe zgłoszenie.

**Comment by Varchord** [comment]
Ok postaram się :P screena ze zbugowanymi runami dorzucę.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1475
