### ISSUE TITLE
 [EN]Wands

### ISSUE THREAD

**Issue by drnick88101** [Atlantiss/BugTracker#1046]
reposting ticket #472 
Hi there, I recently created a priest and the ability "Shoot" with a wand appears to be bugged. After using it, it abruptly stops after 1 or 2 shots at an enemy mob. It happens frequently, especially when the mob is in melee range and damaging me; it almost disdains the entire use of having a wand in the first place as leveling a priest without one is doable, but still harder. 

The ticket was closed because it was a 4.0.6 issue that was supposed to be fixed in 4.3.4. I am still having the exact same issue on 4.3.4 though

**Comment by Vyrtuz** [comment]
http://www.wowhead.com/spell=5019/shoot

**Comment by Wolffenstein** [comment]
Fixed in rev 4355.
