### ISSUE TITLE
[EN][Quest][Borean Tundra] The Sub-Chieftains

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1052]
The quest is completeable, but the issue is that the four chieftains are always spawned. They should spawn only after you turn the valves, which are located near their current spawn points.

**Comment by meowmewo** [comment]
The South Point Station Valve is now not working,The other 3 are.The quest is now uncompletable because u can kill 3 ot the 4 guys.

**Comment by meowmewo** [comment]
Thats the one for the Grinder

**Comment by Satyr87** [comment]
. . . thanks Spydoc , now the quest is broken
cant summon the grinder , cant complete the quest

**Comment by Spydoc** [comment]
What are you thanking me for? I just reported that the quest is completeable but not blizzlike. You should thank the developers for breaking the quest beyond completeable.

**Comment by Satyr87** [comment]
relax mon , this situation is hilarious

**Comment by S3khM3t** [comment]
Still broken

**Comment by Oxyntes** [comment]
still not working for me either
when I was approaching the place with my alt, I saw an ally just kill the grinder, so somehow, he got spawned... when I returned later, nothing happened for me, no valve to spawn the grinder.

**Comment by Satyr87** [comment]
ill tell you what happened : each of those robots have 2 valves to spawn them , one is for allies , second is for hordes , the thing is grinder has only ally valve , it can be completed only on ally side
OR
camp at grinders ally valve and gank some ally who spawns grinder , then kill him
