### ISSUE TITLE
[EN][Quest][Borean Tundra] The Doctor and the Lich-Lord

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1055]
Both of the NPCs are spawned at the wrong location. Doctor Razorgrin should be on the second floor of the building and Lich-Lord Chillwinter should be at the top of the building. Currently both of them are on the first floor.

**Comment by Spydoc** [comment]
http://www.wowhead.com/npc=25678/doctor-razorgrin
http://www.wowhead.com/npc=25682/lich-lord-chillwinter

**Comment by Technowizard15** [comment]
I encountered Chillwinter on top of the wreckage, but Doctor Razorgrin was still inside. Since the report is closed and the problem still exist I'm forced to open a new one.
