### ISSUE TITLE
[PL][Instance] Zul'Aman

### ISSUE THREAD

**Issue by kukukz** [Atlantiss/BugTracker#1061]
brak questa 
The Hex Lord's Fetish - http://www.wowhead.com/quest=29186

**Comment by Jaffar1989** [comment]
napisałem ostanio te 3 quest których nie ma z npc  szukałem chyba z godzine miejsca nps XD
promises,promisses...

**Comment by arekczup** [comment]
część węikszego problemu 

https://github.com/Atlantiss/BugTracker/issues/1651
