### ISSUE TITLE
[PL][Raid-Cata] Sinestra

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1085]
http://www.wowhead.com/npc=45213/sinestra

[Twilight Whelps](http://www.wowhead.com/npc=47265/twilight-whelp)

Po wipe whelpy się nie despawnują i właczają do walki przy najbliższym przyzwaniu whelpów

Przykład:

Pierwsza próba wychodzi 5 whelpów, nikt ich nie zabija, jest wipe
Druga próba wychodzi 10 whelpów, sytuacja jak wyżej
Trzecia próba wychodzi 15 whelpów...

I tak dalej. 
Jeśli się jej nie zabije za pierwsyzm podejściem to nie zabije jej się wcale

**Comment by qubuslabadz** [comment]
Fixed.
