### ISSUE TITLE
[EN][Quest][Northrend][Borean Tundra] Emergency Protocol: Section 8.2, Paragraph D

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#1086]
ID http://www.wowhead.com/quest=11796/emergency-protocol-section-8-2-paragraph-d

Eastern: 63,36
Southern: 61,39
Northwestern: 61,30

Using http://www.wowhead.com/item=35224 at the location (within 15yd range obviously) of http://www.wowhead.com/npc=25845 returns a warning "Can only be used near plane wreckage" and does not complete quest objective. 

Other objectives work:
http://www.wowhead.com/npc=25846
http://www.wowhead.com/npc=25847

Northern plane wreckage needs a fix.

**Comment by silverches** [comment]
Seems like it doesn't work anymore

**Comment by xmesaj2** [comment]
@silverches 
It works, I've done it later, just try other plane wreckages than quest helpers instruct.

**Comment by Aequitass** [comment]
Doesn't seem to work that way anymore, tried all wreckages and couldn't get the southern one to count.

**Comment by Griskhet** [comment]
Doesn't work, tried all three wreckage and not even one works

**Comment by aendry** [comment]
still broken

**Comment by Piklo** [comment]
aww, please don't bump closed one if there is opened one too :D #8693

**Comment by aendry** [comment]
@Piklo I wrote here cuz the other posts have no one assigned to.... Here at least is @Bildo.

**Comment by aendry** [comment]
this quest cuts other quest zone chain [Scouting the Sinkholes](http://www.wowhead.com/quest=11713/scouting-the-sinkholes#comments)
