### ISSUE TITLE
[EN][Core] Ability Queue doesn't work

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1087]
It seems to me that the ability (spell) queue system doesn't work at the moment. This means that especially when dealing with a high ping, you can't chain your casts smoothly together.

The spell queue system was introduced with 4.0 I think, with the new "Custom Lag Tolerance" interface option in [4.0.3](http://www.wowwiki.com/Patch_4.0.3) and [another improvement](http://wow.joystiq.com/2010/10/06/ability-queue-system-issues/) which Ghostcrawler described as: *We are working on an improvement where the most recent command will override the previous one. If for example you are spamming Hamstring, and then succeed in snaring someone, you can switch to Mortal Strike which will clear out the Hamstring queue instead of wasting more GCDs on Hamstring.*

So the ability queue system should be in full effect with the current patch: if you hit an ability with maybe 0,5 - 1 sec or less left on the GCD, it should queue that ability. 
However it seems to me that this doesn't work at the moment. Even if you set the Custom Lag Tolerance slider to max, the next ability isn't queued. You have to start them manually as soon as the previous cast is finished.

![Example](http://i.imgur.com/p3SU2m4.jpg)

To further try to confirm this, I spammed the hunter ability Wing Clip for 5 minutes on a dummy and checked the combat log afterwards. 

* 12/29 23:56:28.260  SPELL_CAST_SUCCESS  
* 12/29 23:56:29.845  SPELL_CAST_SUCCESS (+1.585 sec)  
* 12/29 23:56:31.367  SPELL_CAST_SUCCESS (+1.522 sec)  
* 12/29 23:56:33.209  SPELL_CAST_SUCCESS (+1.842 sec)  
* 12/29 23:56:34.993  SPELL_CAST_SUCCESS (+1.784 sec)  
* 12/29 23:56:36.591  SPELL_CAST_SUCCESS (+1.598 sec)  
* ...

In 300 seconds, I was able to cast Wing Clip **184 times**, which means the CD between them was 1,642 seconds. 

However, Wing Clip should only have 1,5 sec GCD (most hunter abilites had 1 sec GCD in cata, but WC and a few others still had 1.5 GCD), which means that in 300 seconds I should have been able to cast it **200 times**.

With a working ability queue, this should have been achievable... however since there is a 142 ms difference per cast, I think this is my latency, and so the ability queue doesn't work.

**Comment by Wolffenstein** [comment]
I'm sorry, but I don't think there is anything we could do about this issue. Lag tolerance is set on the client side but there is no way to send this information to the server (no packet is sent), so I can't even start working on it.

**Comment by Malylolek** [comment]
So how it work on global serwer ? They must do it some how

**Comment by Tj20** [comment]
Even if the "custom lag tolerance" slider does nothing, the spell queue mechanism should work automatically, no?

I don't know if this is any help, but I've read that other Cata servers apparently also had problems with the spell queue, but found a fix somehow? [Spell Queue mechanism has been fixed](https://www.facebook.com/wowfreakz/posts/457237401051851), [2](http://www.dm.freakz.ro/forum/FIXED-Important-Spell-Queue-System-Bug-Pve-PvP-t225601.html).
But I don't know what they did and if it would even work for us.

**Comment by Tj20** [comment]
Today I've registered on the server I mentioned and gave it a try. It seems I was mistaken: Spells over there work exactly like they do here, meaning that you can't queue spells. You can only start a new spell after the previous one has been completely finished.

Maybe this is just how it is. Maybe they got the spell queue working, but they had to change something in the client, which I didn't try (I used our 4.3.4 client instead of downloading theirs).

So... I don't know. I guess there has to be some way because it worked on retail servers, but it may be that no pserver has figured out how to do it, and maybe never will... who knows.

I would *assume* that it works maybe like this: everytime the user presses a button, the server gets this info and tells the client "yep, you can do this" or "no, you can't do this". And since the introduction of the spell queue in 4.0, the server can also answer: "you can't do this *right now*, but I put your request in the spell queue. I will do it in 0.8 seconds after I'm done with your current job".  
But that's just my assumptions, it may be really hard to do and maybe no pserver has achieved to implement this so far.

**Comment by Varchord** [comment]
It's like "Rise Ally" spell, no private server could script it :<

**Comment by Jenovas** [comment]
Varchord - I did the fix, but we decided not to add it to the server cause we were planing to go to 4.3.4 not long. :P

**Comment by Varchord** [comment]
But i've wanted to be a little ghul after dead :<
Still. Ability Queue would be cool

**Comment by mitim1** [comment]
BUMP!

**Comment by Tj20** [comment]
> and gave it a try. It seems I was mistaken: Spells over there work exactly like they do here, meaning that you can't queue spells. You can only start a new spell after the previous one has been completely finished.

By chance I stumbled over [this post](https://www.freakz.ro/forum/Multiple-Spell-Queue-t355216.html) and probably found an explanation why it didn't work for me: Over there you had to enable/disable this with the server command .spellqueue on/off. According to that post it seemed to have worked, but with minor issues (spamming the keys gave you a "fake GCD" or something). Unfortunately they don't have a Cata realm any more, so I can't take a look at it.

**Comment by Tj20** [comment]
By the way, WM seems to have a working spell queue on their Cata and MoP realms. I don't want to play there, but I've had a quick peek and I think chain casting abilities works pretty smoothly, nearly like on retail servers.

I've had a look at the /eventtrace window, and here is how I imagine the spell queue system works:

- The custom lag tolarance slider is client-side only. If you set it to 0 ms it won't allow you to cast a second spell until the GCD is totally over. If you set it to 400 ms, it will allow you to cast a little bit before the client thinks the GCD is over.
- When the client sends its request, the server won't answer until the server agrees that the GCD is over. It essentially lags a little bit. After that, it will say: "ok, here is your spell!"
- Our server on the other hand will respond immediately. And it will say: "Sorry bro, it has only been 0.8 sec since your last cast, you can't do that yet!"

![pic](http://i.imgur.com/hiDmKWn.jpg)

I imagine the communication a bit like this:

![pic](http://i.imgur.com/JEIiwVa.jpg)

There later was an improvement where you could change your queued spell into something else. That doesn't seem to work on the server mentioned before, but I think even the old spell queue system is neat: it makes chain casting abilities feel much smoother, you don't have to mash your buttons any more.

Now I don't know the communication between server and client in detail, and implementing this might be very complicated. I just wanted to present everything I know about this issue (which might not be too much... :ghost: )

**Comment by Jenovas** [comment]
I already got the basic Ability Queue System working, by basic I mean if you are casting a spell already and click a different spell it will be casted the moment you finished casting the first spell, letting you do nice combos, are nice smooth casting without seeing latency effect your casts.

But this is still a very alpha version, so it wont be released yet (maybe it'll be added on the PTR this week).

**Comment by Varchord** [comment]
Add this on ptr! ASAP

**Comment by Tj20** [comment]
Ooooh... you're the man! :yellow_heart:

**Comment by Varchord** [comment]
Nie no Jenova. Na razie to działa że tak powiem chujowo. Całkowicie ignoruje custom lag latency ustawione (rozumiem, że nie zaimplementowane). Następnego spella czasem zatriggeruje, czasem nie. Częściej nie działa niż działa. Dużo roboty z tym jeszcze :<<

**Comment by Bildo** [comment]
Tylko, ze jeszcze nikt tego nie wrzucał

**Comment by Varchord** [comment]
To mnie aneq w chuja zrobił

**Comment by Tj20** [comment]
I didn't understand everything, but it on the PTR already? 

To me it looks like it's not implemented yet.

**Comment by Varchord** [comment]
Guildmate told me it was implemented and I was "testing" it during yesterday FL tests. Turns out it's not implemented ;p

**Comment by Tj20** [comment]
Ah, ok.

**Comment by Jenovas** [comment]
I didnt add anything. When I do I'll let you know.

**Comment by ahtebe** [comment]
Are you there yet ^^' ? Been a month since news on this subject.

**Comment by Jenovas** [comment]
I've been doing other stuff, decided to leave this for now cause there are more important stuff.

**Comment by Pvt-8Ball** [comment]
I came here to report this bug, but clearly a fix is already in the works, neat.

I will stress this is one of the more irritating bugs on the server, hope you can get it fixed.

**Comment by debtheone** [comment]
BUMP rly annoying

**Comment by debtheone** [comment]
BUMP

**Comment by aneq** [comment]
@Aviannaqt 
Fixed, the issue can be closed
