### ISSUE TITLE
[EN][Spells][Warlock] Health Funnel, Unending breath

### ISSUE THREAD

**Issue by pahanzt** [Atlantiss/BugTracker#1088]
1. Health funnel (http://www.wowhead.com/spell=755), Unending breath (http://www.wowhead.com/spell=5697)
2. a). Health funnel doesn't make your character to sacrifice health for healing your demon. It says "Miss", when you do that (http://imageshack.com/a/img661/7589/kq3bvD.jpg).
b). Unending breath. The problem is the same as in my other report with entering combat (https://github.com/Atlantiss/BugTracker/issues/773)
3. Bugs were noticed 30.12.2014
4. Value: 4/10.

**Comment by Wolffenstein** [comment]
One issue = one bug. Health Funnel damage fixed in rev 4223.
