### ISSUE TITLE
[PL][NPC] Garr

### ISSUE THREAD

**Issue by wojen616** [Atlantiss/BugTracker#1092]
Garr (http://www.wowhead.com/npc=50056) nie powinien dropić już http://www.wowhead.com/item=67235 zamiast tego winien lecieć http://www.wowhead.com/item=69842
Ten NPC stoi w miejscu a powinien się tam poruszać.
Brak przy nim 8 http://www.wowhead.com/npc=50055
![iqmxinhbnxudbstyfhmjciqkcdjvqosckbcrukojvkxgibjrmceurchzacveemlzfrszqceuscoskjbaurinjxliucqspjeizybqijbkyjbpoopqavknexphgjfnlmfi](https://cloud.githubusercontent.com/assets/10191782/5578960/55d34ba6-9032-11e4-96b0-d9e60b1c6803.jpg)

**Comment by Piklo** [comment]
posted fix for loot at forum:
http://community.atlantiss.eu/index.php?/topic/12042-garr-loot-tables/
