### ISSUE TITLE
[PL][Quest] Seeking Soil

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#1093]
Gdy odbieram Questa od Seeding Protector ( http://www.wowhead.com/npc=48032/seedling-protector ) to pojawia się Sapling Protector ( http://www.wowhead.com/npc=48042/sapling-protector )  co uniemożliwia zdobycie Rich Soil. Na dodatek w linku poniżej obrazek nie pokazuje by te kopce się "dymiły" : / tak czy owak - Sapling Protector nie powinien się pojawiać zwłaszcza, że wykonałem zadania, które trzeba mu oddać. Gdy usunę zadanie to  Seeding Protector znowu pojawia się jako companion, a poprzednik znika. Zauważyłem, że nawet nie biorąc questa znikają wszystkie kopce w pobliżu, ale mi nic nie przychodzi :( 

Link: http://www.wowhead.com/quest=28220/seeking-soil

**Comment by Satyr87** [comment]
rzecz w tym ze seedling rosnie za szybko w saplinga , powinno dzialac tak ze dopiero po zrobieniu questow od niego zamieni sie w saplinga zeby dac nowe questy ale po podniesieniu seeking soil puchnie automatycznie i jest saplingiem

i przy okazji to jak sie nie ma seeking soil w questlogu i jest maly to faktycznie zre ta glebe , ale coz z tego

**Comment by Danelar** [comment]
No właśnie :[

**Comment by HUMBOL** [comment]
bump!
http://screenshot.sh/ofoZdbkB5zmS3

**Comment by lourrific** [comment]
As of November 27, 2015 this quest is still bugged. Next month in December this quest has gone one full year without a fix. Welcome to Atlantiss.

**Comment by BAndysc** [comment]
Should be fixed in 5635
