### ISSUE TITLE
[PL][Item]"Blood Red Key"/[Quest]"[DEPRECATED]A Strange Red Key"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1098]
Nie mogę wziąć questa z tego itemu ( http://www.wowhead.com/item=13140/blood-red-key#starts ) klikam i nic :|
Nie wiem czy to w tym dodatku czy w innym tego questa , ale jeśli w tym to błędem jest obecność przedmiotu w grze.

**Comment by Bildo** [comment]
fixed in 4192 by Navedonar

**Comment by Danelar** [comment]
aha :)
