### ISSUE TITLE
[EN][Instance - TBC] Shadow Labyrinth

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#110]
Complete list of 4.3 updates for the instance to be implemented:

-------------------------------------------------------------------

Spy Grik'tha and Field Commander Mahfuun were moved from their previous location outside the instance, now they are inside.

http://www.wowhead.com/npc=54891 - Spy Grik'tha
http://www.wowhead.com/npc=54890 - Field Commander Mahfuun

Their old IDs are npc=19496 and npc=19542, respectively. These should no longer spawn where they were previously located.

-------------------------------------------------------------------

Also, two types of flavor NPCs were added at the entrance.

http://www.wowhead.com/npc=54893 - Lower City Operative
http://www.wowhead.com/npc=54895 - Lower City Healer

-------------------------------------------------------------------

The revamped questline and associated notes:

breadcrumb: http://www.wowhead.com/quest=29642 - Trouble at Auchindoun
(notes: replaced pre-4.3 quest http://www.wowhead.com/quest=10177; should give 1250 XP pre-squish)

Mahfuun's quest strand:

1. http://www.wowhead.com/quest=29643 - The Codex of Blood
2. http://www.wowhead.com/quest=29644 - Into the Heart of the Labyrinth

Grik'tha's quest strand:

1. http://www.wowhead.com/quest=29640 - Find Spy To'gun
2. http://www.wowhead.com/quest=29641 - The Soul Devices

(general note: these quests should award 25300 XP pre-WoD squish)

-------------------------------------------------------------------

Other:

http://www.wowhead.com/npc=18667 - Blackheart the Inciter randomly spouts some gossip text in "Engrish". It isn't present on retail version.

**Comment by romigrabarz** [comment]
Confirmed. Can't finish the quest on NPC http://www.wowhead.com/npc=54890/field-commander-mahfuun

**Comment by abcbok** [comment]
Still bugged. Quests can't be returned.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
