### ISSUE TITLE
[EN][Quest][Alliance][Stonetalon Mountains] "Downfall"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1101]
http://www.wowhead.com/quest=25848

Killing the first general is supposed to start a gauntlet fight where 3 others generals come, final one drops a chest with the item. That doesn't work, after killing the first general, nothing happens.

The whole area of south of Stonetalon seems a bit bugged: there should be some alliance- and some horde-friendly mobs fighting each other, but they are all hostile to alliance and don't fight each other, they just stand there.

**Comment by Bildo** [comment]
This quests works :) 
http://i.imgur.com/0A3vCEv.jpg
