### ISSUE TITLE
[EN][Quest][Teldrassil]Teldrassil: The Burden of the Kaldorei (ID 7383)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1105]
Quest should be available to every Alliance race.Now it is not at least for Worgen char.
Rest of the chain should be available to every Alliance race as well.

Wowhead Link:1. [Teldrassil: The Burden of the Kaldorei](http://www.wowhead.com/quest=7383)
Gamepedia Link: [Quest:Teldrassil: The Burden of the Kaldorei](http://wow.gamepedia.com/Quest:Teldrassil:_The_Burden_of_the_Kaldorei)
Openwow link:[Teldrassil: The Burden of the Kaldorei](http://cata.openwow.com/quest=7383)

Wowhead link for the rest of the chain: 
2. [Teldrassil: The Coming Dawn](http://www.wowhead.com/quest=933)
3. [The Vengeance of Elune](http://www.wowhead.com/quest=14005)
4. [The Waters of Teldrassil](http://www.wowhead.com/quest=935)
5. [Home of the Kaldorei](http://www.wowhead.com/quest=14039)

**Comment by Bildo** [comment]
fixed in rev 4240
