### ISSUE TITLE
[EN][Instance - Classic][NPC] Earthgrab Totem in Razorfen Kraul 

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1109]
[Razorfen Totemics](http://www.wowhead.com/npc=4440/razorfen-totemic) occasionally spawn an earthgrab totem which is supposed to root enemies.

The totem

a) doesn't root us as it should and
b) behaves like a mob: it runs around and attacks players. Pretty hilarious for a totem.

![earthgrab totem punch: activate!](http://i.imgur.com/9HvAE5Z.png)

**Comment by Bildo** [comment]
fixed in rev 4240
