### ISSUE TITLE
[PL][Object][Fishing][Hyjal] Pool of Fire

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#1111]
http://www.wowhead.com/object=207734#comments
W jednym miejscu jest tak położone że nie możemy zarzucić wędki.
http://i.imgur.com/cDeMQ4n.jpg
http://i.imgur.com/UM91xUP.jpg

**Comment by Magohoy** [comment]
[EN] Also, you should be able to fish here at fishing level 1, with 100% catch chance, which is not the case here.

**Comment by Lidless** [comment]
UP

**Comment by tomatosz** [comment]
[EN] Bump, the pool (at 52.09, 77.74) is still unfishable: "You can't do that here"

**Comment by tomatosz** [comment]
Fixed in rev. 5824
