### ISSUE TITLE
[EN][Arenas] MMR and Team Names are wrongly displayed on the Scoreboard

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1112]
For some reason Our Team MMR values are swapped with Enemy Team MMR at the end of the arena on the scoreboard.

EDIT: The same goes to Team Names

![](http://oi61.tinypic.com/24kz7e9.jpg)

Add-ons go crazy
![](https://camo.githubusercontent.com/01492be4a9bafc9cc41f0c8c7a05360de2fa2ca8/687474703a2f2f7777772e696d672e706c2f70674a672e6a7067)

**Comment by BeVeR86** [comment]
I have problems with this bug, one of my addons really doesn't like the switched team names and just goes haywire.
It is annoying. It seems the players are just displayed in the wrong team.

**Comment by kadi2** [comment]
It worked fine before wolf's fixes to mmr.

**Comment by BeVeR86** [comment]
I am also looking into this issue since I believe in helping this community and this bug just annoys me :p 
My experience with Lua is very limited though so it is taking me a while to debug this.

**Comment by Jenovas** [comment]
Fixed in rev 5255
