### ISSUE TITLE
[PL][QUEST][Mount Hyjal] Prepping The Soil

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1115]
http://www.wowwiki.com/Quest:Prepping_the_Soil

http://www.wowhead.com/quest=25502#comm Nie można odpalić obelisku wygląda na ciągle aktywny. żadnego innego z 5 podanych w qescie nie znalazłem kierując się mapka z wowiki.
http://wrzucaj.net/image/bQL

oraz moby wyłażą z pod ziemi.
http://wrzucaj.net/image/bQR

**Comment by exyide** [comment]
Obelisk resetuje się przy restarcie serwera. W ciągu kilku minut od restartu udało mi się go uruchomić(zaliczyło objective), pojawiały się moby, które ubiłem, ale nie zaliczyło mi obrony obelisku ;(

**Comment by ThordAelo** [comment]
Zadanie jest do zrobienia, chociaż trochę musiałem popróbować: Gdy obelisk zostaje aktywowany, otrzymuje się bufa i pojawiają się mobki. Trzeba utrzymać przynajmniej jednego przy życiu do końca działania bufa, aby zaliczyło zadanie całkowicie. Nie jest to może blizzlike, ale tymczasowo rozwiąże problem.

**Comment by Murmaider** [comment]
Aktualnie psikus jest taki, że obelisku nie da się aktywować w ogóle. Prosimy o pomoc.

**Comment by imeasytokill** [comment]
Potwierdzam wersję ThordAelo. Dziś zrobiłem ten quest.

**Comment by Wolffenstein** [comment]
Fixed in rev 4253.
