### ISSUE TITLE
[EN][Other] Equipment manager

### ISSUE THREAD

**Issue by serianx** [Atlantiss/BugTracker#1116]
Equipment manager http://www.wowwiki.com/Equipment_Manager
does not save when you create a new set, it is gone after you relog making impossible quick changing armor sets when you have two specs

**Comment by int24rain** [comment]
Doesn't work for me too after the pre-patch.Could be good if it fixes asap.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1005 duplicate
