### ISSUE TITLE
[EN][Quest][Undercity] Cooking & Fishing Daily Quests

### ISSUE THREAD

**Issue by imeasytokill** [Atlantiss/BugTracker#1117]
Eunice Burch <Cooking Trainer> http://www.wowhead.com/npc=4552 should give daily quest from list http://www.wowhead.com/npc=4552#starts

Armand Cromwell <Fishing Trainer> http://www.wowhead.com/npc=4573 should give daily quest, from list http://www.wowhead.com/npc=4573#starts

Quests was added in patch 4.1.0

Same in Thunder Bluff: https://github.com/Atlantiss/BugTracker/issues/937

**Comment by Danelar** [comment]
True!!!!

**Comment by Wolffenstein** [comment]
Thunder Bluff's cooking dailies fixed in rev 4384.

**Comment by Kiperr** [comment]
Fixed  in rev 4928.
