### ISSUE TITLE
[EN][Tol Barad][PvP][Vehicles] Can't get into Tol Barad vehicle (buff doesn't show)

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1120]
http://www.wowhead.com/npc=45344/abandoned-siege-engine

Since i couldn't get into vehicle in TB last time, you said it's because i didn't kill anyone and didn't get some kind of buff - so here are the screenshots:
I killed druid (got killing blow if it matters because 1v1): http://wstaw.org/m/2014/12/31/WoWScrnShot_123014_162346.jpg
A few seconds later i was trying to use siege but i couldn't ("You can't do that yet" message): http://wstaw.org/m/2014/12/31/WoWScrnShot_123014_162354.jpg

Reference to https://github.com/Atlantiss/BugTracker/issues/996 (PL version)

**Comment by Wolffenstein** [comment]
Fixed in rev 4304.
