### ISSUE TITLE
[PL][Core][Rogue] Regeneracja energii

### ISSUE THREAD

**Issue by lastkiss** [Atlantiss/BugTracker#1125]
Statystyka Haste nie wpływa w żadnym stopniu na regenerację energii u rogue, a powinna:
http://www.wowwiki.com/Haste
In World of Warcraft: Cataclysm, haste will also increase the rate at which you gain energy, runes, and focus. Retribution paladins and Enhancement shaman will have a talent that allows them to take advantage of this benefit.

w talentach subtlety mimo posiadania haste, regen energii cały czas na poziomie 10, więc podstawowym http://i.imgur.com/NdWjlV3.jpg

w talentach combat haste również nie zwiększa regenu tak jak powinno, natomiast współczynnik regenu w talentach combat wynosi 12.5 http://i.imgur.com/OUS7Qn2.jpg , co wynika z pasywnej zdolności Vitality w combacie http://i.imgur.com/YOmLwWo.jpg - więc zostaje do rozwiązania problem wpływu haste na regenerację energii

**Comment by Azotox** [comment]
Wizual  swoja droga, gdy przykladowo odpalimy adrenaline rush wspolczynnik zostaje podwojony, natomiast slice and dice i ogolny haste zgromadzony na naszej postaci nie zwieksza regenu. 
uwazam ze tool tip dziala poprawnie i pokazuje dobre wartosci, lecz w tej chwili haste ogolny jest martwa stata. Pozdrawiam.

**Comment by Jenovas** [comment]
Haste wpływa na regen. Wiele buffów na "haste" nie powinno wpływać na regen i tak jest u Nas zrobiony podział. Ostatnio robiłem testy i haste zwiększa regen jest tylko bug graficzny w karcie postaci. Zamykam.
