### ISSUE TITLE
[EN][ITEM] Alliance Quartermasters

### ISSUE THREAD

**Issue by shogo238** [Atlantiss/BugTracker#1132]
Alliance QMs are selling the race/reputation specific bags below the required reputation of revered. 

Tested on Dwarven, Gnomish, and Human quartermasters. 

http://www.wowhead.com/item=67531#sold-by
http://www.wowhead.com/item=67528
http://www.wowhead.com/item=67530

**Comment by Bildo** [comment]
duplicate
