### ISSUE TITLE
[EN][Quest][Zangarmarsh]Uncatalogued Species

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#1133]
I was questing in zangarmarsh, finally farmed 10 undiscovered plants or w.e was the name, returned the Q and from the satchel i received i got a Q item, "Uncatalogues Species" i clicked on it, accepted it and i received another Q item, the same one, that way i had 2 ^^ when i turned the Q only 1 of them dissapeared and so i could keep accepting and returning the Q until i became revered with cenarion expedition :P. Sadly after that it stopped working, showing me "You dont meet the requirements for that quest"

http://www.wowhead.com/quest=9875

**Comment by Bildo** [comment]
duplicate
