### ISSUE TITLE
[EN][Instance-Classic] Uldaman: Run begins at Back Entrance

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1142]
The dungeon finder places the group at the back entrance of the dungeon instead of the front entrance. 
Normally your run should start at the front entrance, where the questgivers are located. 

![Map](http://i.imgur.com/FCpIUOp.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4226.

**Comment by Bildo** [comment]
Damn Wolf i already fix this !
