### ISSUE TITLE
[PL][Item][Low Priority] Heart of Ignacious

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#1146]
Trinket Heart of Ignacious (http://www.wowhead.com/item=59514/heart-of-ignacious) przy odpaleniu w makrze (zmieniałem kolejności i formułki, efekt ten sam) z berserkingiem daje tylko 321 haste rating zamiast 1605 (przy 5 stackach ofc). Odpalony oddzielnie i w dowolnej kolejności działa normalnie i daje tyle ile powinien. Nie wiem jak z innymi racialami działa w makrze.

Miałem wrażenie, że odpalając go w jednocześnie z tym racialem wartość przez 0,5s była taka jak powinna być po czym wróciła do tej zaniżonej ale nie jestem pewien, takie luźne przemyślenie.

**Comment by Raamzey** [comment]
Dodam, iz testujac ten trinket nawet nie majac stackow mozna dostac 1605 haste, czasem 321, czasem odpalajac oddzielnie (nie makrem) daje tylko 321 haste przy 5ciu stackach SP. Niestety dosc czesto daje tylko 321 haste, co sprawia, ze ten trinket jest na ta chwile bezuzyteczny.

Serdecznie prosze o jego naprawienie :(

**Comment by Kiperr** [comment]
Fixed in rev 4351
