### ISSUE TITLE
[EN][Dungeon-WotLK][Quest] Don't Forget the Eggs!

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1147]
http://www.wowhead.com/quest=13182/dont-forget-the-eggs

Eggs aren't usable. Quest cannot be completed

**Comment by PVPViddys** [comment]
Just came to post this one, I second this bug.

**Comment by Tj20** [comment]
The issue seems to be fixed, I could interact with the eggs properly now (after deleting my cache folder... I guess I had still the old eggs in there).
