### ISSUE TITLE
[EN][Dungeon-Cata] Lost City of the Tol'vir

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1154]
http://www.wowhead.com/zone=5396/lost-city-of-the-tolvir~

# Other
UPDATE 09.01.2015 rev 4215

* You can get to Siamat right after killing first boss

# [General Husam](http://www.wowhead.com/npc=44577#encounter)
* [Bad Intentions](http://www.wowhead.com/spell=83113) He is not hurling players into a wall. He is just throwing them in the air. In addition they should be stunned as long as they are in the air

# [High Prophet Barim](http://www.wowhead.com/npc=43612)
* [Plague of Ages](http://www.wowhead.com/spell=82622) sometimes players get 'evade' on this
* [Blaze of Heavens](http://www.wowhead.com/spell=95248) never saw her losing hp all by itself
* [Soul Fragment](http://www.wowhead.com/npc=64608) sometimes are not moving at all. They are still visible after phase 2 ends.
* [Repentance](http://www.wowhead.com/spell=81947) After casting this and finishing Phase 2 he will just stand in place. He should be able to move when phase 2 ends. Sometimes he isn't moving after wipe

# [Lockmaw](http://www.wowhead.com/npc=43614)
* [Dust Flail](http://www.wowhead.com/spell=81644) Should appear behind boss instead of in front of him. It persist after he finishes it and moves but it shouldn't. In addition it's hitting all players in proximity of the boss instead of only those behind him, near his tail.
* [Scent of Blood](http://www.wowhead.com/spell=81690) I've seen all players being infected by it at once

# [Augh](http://www.wowhead.com/npc=49045#encounter)
* [Whirlwind](http://www.wowhead.com/spell=1680) he stops moving after being taunted.

# [Siamat](http://www.wowhead.com/npc=44819#encounter)
* He should cast his bubble a couple of seconds after pull not immediately
* [Depletion](http://www.wowhead.com/spell=84550) adds not using this
* There is problem with platform. You get LOS problems because platform is still treated as if columns stil existed (I think it's global problem, but still)

**Comment by Varchord** [comment]
UPDATE 09.01.2015 rev 4215

**Comment by qubuslabadz** [comment]
Fixed in rev. 4300. Jeśli pojawią się kolejne bugi proszę założyć nowe issue.

**Comment by Varchord** [comment]
To teraz reszta! ^^ Proponuje zacząć od grim batol smoczków XD
