### ISSUE TITLE
[EN][Quest] The Amphitheater of Anguish

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1157]
http://www.wowhead.com/quest=12932

Quest [The Champion's Call!](http://www.wowhead.com/quest=12974) shouldn't be mandatory to pick up [The Amphitheater of Anguish: Yggdras!](http://www.wowhead.com/quest=12932) and the following

**Comment by Bildo** [comment]
fixed in rev 4240

**Comment by Varchord** [comment]
Co ty tak to zamykasz i otwierasz? Zdecyduj się ^^
