### ISSUE TITLE
[EN][Quest][Kezan]Off to the Bank

### ISSUE THREAD

**Issue by cosminus85** [Atlantiss/BugTracker#1158]
The quest should be in raport of your sex, i mean, if u are boy goblin, u get quest from Candy Cane: http://www.wowhead.com/quest=26712
and if u are girl goblin u get quest from Chip Endale:
http://www.wowhead.com/quest=26711
and in game i get quest as boy from Chip Endale; strange he say he love me O_o, and i am boy.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
