### ISSUE TITLE
[EN][Raid-Cataclysm][NPC] Omnotron Defense System

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1159]
http://www.wowhead.com/npc=42178#encounter

UPDATE 20.01.2014 rev 4265

* [Converted Power](http://www.wowhead.com/spell=79735) spellstealing this by mage increases his cast time instead of decreasing it. Mage from my guild told me that his fireball cast time was 970 hours
 * http://i.imgur.com/mvCokPm.jpg
* When bosses are at low hp or dying there is a chance that their HP will reset back to 100%. Encounter continues as if nothing have happened. Berserk timer or any other for that matter don't reset

**Comment by qubuslabadz** [comment]
Na czystej postaci z tego co widzę działa poprawnie.

**Comment by Varchord** [comment]
No powiedzieli mi, że tak się działo. Weź może kogoś na magu ze sobą zamiast takiego GM-owego maga.

**Comment by Varchord** [comment]
http://i.imgur.com/mvCokPm.jpg

Ha! Nie działa xD W dodatku nie stackuje się ten buffek na magu. Tylko jeden może mieć stack

**Comment by Pazurek** [comment]
I jeszcze ostatnio dość często spotykany bug na bossie to taki że przy 1% bossa nagle jakimś cudem przywracało mu się hp do 100%. Zdażyło się tak mojej gildii dwa razy.

**Comment by Varchord** [comment]
O cholera przypomniałeś mi. Miałem zgłaszać to ;x

**Comment by Varchord** [comment]
UPDATE 20.01.2014 rev 4265

* Boss hp reset

**Comment by mitim1** [comment]
Dodam ze czasem wywala crasha (wowa nie servera) gdy "jednocześnie" jest Flamethrower i Grip. 
A i dalej występuję bug ze spellstealem buffa z arcanotrona.

**Comment by Alandiel** [comment]
wow error pewnie jest gdy ktoś używa disengage lub innego tego typu skilla podczas gripa.

**Comment by Varchord** [comment]
Consolidated
https://github.com/Atlantiss/BugTracker/issues/3143
