### ISSUE TITLE
[PL][Quest]"Guarding Secrets isn't <not avaible>"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1160]
Mogę odebrać ten quest od Blue-Feathered Necklace ( http://www.wowhead.com/item=12558 ), ale zgodnie z poniższym linkiem quest już nie istnieje - nawet końcowego NPC już tam nie ma Trull Failbane ( http://www.wowhead.com/npc=10306 ) 

Link: http://www.wowhead.com/quest=4882/guarding-secrets

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Danelar** [comment]
czyli item wyrzucić?

**Comment by Navedonar** [comment]
tak

**Comment by Danelar** [comment]
Dobrze :)

**Comment by Bildo** [comment]
fixed in 4192 by Navedonar

**Comment by Danelar** [comment]
Dziękuje ;)
