### ISSUE TITLE
[EN][Quest][The Lost Isles]Trading Up 

### ISSUE THREAD

**Issue by cosminus85** [Atlantiss/BugTracker#1164]
There is a bug on raptors, when they are catch by traps, they release eggs on my char foots and not on they foots, the raptors. 
http://www.wowhead.com/quest=24741/trading-up

**Comment by Tj20** [comment]
True. It's not a big problem, but I've noticed the same. The eggs spawn at *your* position instead of the *raptor's* position.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
