### ISSUE TITLE
[EN] Lost Isles - Ghost falling through world 4.3.4

### ISSUE THREAD

**Issue by Hacker--x** [Atlantiss/BugTracker#1167]
See = https://github.com/Atlantiss/BugTracker/issues/551
Was a bug in the 4.0.6 server with if you die with a goblin in the caves on the lost isles, you will fall through the map and cannot be resurrected without a gm. Tested and still on new server, extremely game breaking, caused a friend to restart his goblin character.

**Comment by Giq** [comment]
Fixed
