### ISSUE TITLE
[quest][The Steamvault] Containment is Key

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#1168]
http://www.wowhead.com/quest=29614

Mekgineer Steamrigger (http://www.wowhead.com/npc=17796) doesn't drop Irradiated Gear (http://www.wowhead.com/item=72574) or the chance is too low (should be 100% if we have the quest).
Tested once on normal and once on heroic.

**Comment by Bildo** [comment]
fixed in 4192 by Navedonar
