### ISSUE TITLE
[EN][Quest][The Slave Pens] Lost in Action

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#1169]
http://www.wowhead.com/quest=29563

Can't complete the quest because game doesn't give us credit for discovering Naturalist Bite (http://www.wowhead.com/npc=17893). I think we should get credit after opening the cage but i couldn't find any confirmation.

**Comment by Aruzam** [comment]
Still doesn't work, doesn't give credit for discovering Naturalist Bite and can't complete the quest.

**Comment by Enay** [comment]
Confirming this, still not working.

**Comment by Thefakemccoy** [comment]
Problem is you cant open the cage.

**Comment by Dean1989** [comment]
confirmed

**Comment by Atlantissbug** [comment]
Still isn't working

**Comment by Samineh** [comment]
:+1:

**Comment by coba999** [comment]
Natur
![wowscrnshot_111115_232019](https://cloud.githubusercontent.com/assets/15231821/11112984/2e898a86-8921-11e5-8d61-b649eb9e3a87.jpg)
alist Bite (http://www.wowhead.com/npc=17893/naturalist-bite) don't trigger. Quest does not work.
