### ISSUE TITLE
[quest][The Slave Pens] The Heart of the Matter

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#1170]
http://www.wowhead.com/quest=29565

We can't get the quest items:
- The Invader's Claw (http://www.wowhead.com/item=72118) should drop from the second boss (http://www.wowhead.com/npc=17991)
- The Slave Master's Eye (http://www.wowhead.com/item=72119) should drop drom the last (http://www.wowhead.com/npc=17942)

**Comment by Bildo** [comment]
fixed in 4192 by Navedonar
