### ISSUE TITLE
[PL] [Spell] [Druid]  Rip

### ISSUE THREAD

**Issue by Beatit** [Atlantiss/BugTracker#1172]
Zbyt duży dmg z ripa http://www.wowhead.com/spell=1079/rip#changelog
https://wow.freakz.ro/spells.php?spell=1079 (version 4.3.4)

Descripción: Rip Cat Form
30 Energy Melee range
Instant cast

Finishing move that causes Bleed damage over time. Damage increases per combo point and by your attack power:
1 point: (56 + 4 * 1 + 0.0207 * AP) * 8 damage over 16 seconds.
2 points: (56 + 4 * 2 + 0.0414 * AP) * 8 damage over 16 seconds.
3 points: (56 + 4 * 3 + 0.0621 * AP) * 8 damage over 16 seconds.
4 points: (56 + 4 * 4 + 0.0828 * AP) * 8 damage over 16 seconds.
5 points: (56 + 4 * 5 + 0.1035 * AP) * 8 damage over 16 seconds.

Testowane na 74 lvlu, 2180 AP, 0 mastery, braku mangle na targecie, 5 combo pointsach czyli czysty RIp bez "dopalaczy".

5 points: (56 + 4 * 5 + 0.1035 * 2180) * 8 = 2413,04 damage (jeśli jakiś tick nie critnie)

A ile bije u nas? 6.4k (8 ticków po 802 bez crita) czyli za ponad połowe hp takiego druida (także przy braku mastery (74lvl), manglu na targecie i innych "dopalaczach").

**Comment by Varchord** [comment]
Sprawdź na max levelu. Taka sama sytuacja jak flametounge weapon.
Zresztą link do freakz? Kiepskie źródło informacji(nieoficjalne), a poza tym  kryptoreklama :O Ja bym banował ^^

**Comment by Beatit** [comment]
na 85 też sprawdzałem, ale sam osobiście nie mam postaci 85 lvl a Ci co sprawdzali nie chciało im się screenów robić lub niewłaściwie sprawdzali. Daj passy Spite to sprawdze, sam mówiłeś, że na 85 za mocno bije :)

**Comment by Bildo** [comment]
Co to za roznica czy freakz czy nie. Id to samo

**Comment by Varchord** [comment]
Ja nic takiego nie mówiłem. Wiesz bildo forum battle.ne, wowhead, mmo champions to co innego niz baza innego serwera prywatnego

**Comment by Beatit** [comment]
na wowhedzie jest ta sama formuła...

**Comment by Varchord** [comment]
Nie dam Ci passów. Nic nie ukrywam. Odkąd 4.3.4 weszło to jedyne co na druidzie sprawdziłem to Natural Reaction

**Comment by kadi2** [comment]
z 5.7k tick z ripa spadl do 4.2 ale dopiero po oduczeniu sie talentow...

**Comment by Varchord** [comment]
Ta. Z tym tylko, ze feral nie ma talentów na zwiększenie dmg z rip

**Comment by kadi2** [comment]
Przy oduczaniu sie talentow oduczasz sie tez masterki, po oduczeniu sie talentow i rozdaniu ich na nowo  bug zniknal.

**Comment by Jenovas** [comment]
Jest bug na całym serwerze że gracze mają podwójnie mastery, jest to bug który pojawił się z wejściem 4.3.4. Są przypadki gdzie rogala w sub mają mastery z suba i combata na raz. Najprawdopodobniej zostanie odpalony reset talentów dla całego serwera. Co do DMG samego Ripa i Rake jest on zawyżony o około 1k dla Ripa i 900 dla Rake przy 21 mastery (im więcej mastery tym większy błąd, bo mastery % zwiększa DMG).

**Comment by kadi2** [comment]
Jezeli chodzi o ostatni reset talentow, to moj rogue nie mial oduczonego drugiego speca do konca, odjeliscie mu tylko 41 punkty z drzewka. - Mastery zostalo.

**Comment by Beatit** [comment]
u mnie było to samo, 2 spec był bez talentów, ale wybrane było już drzewko Holy, więc tylko w ten spec mogłem talenty rozdawać

**Comment by Jenovas** [comment]
Głowne drzewko zostało zresetowane całe drugie nie do końca do tego zresetowane zostały aury. Z tego co robiliśmy wczoraj testy z Djwintrade Rip już się nie buguje i ma ok DMG. Zamykam.
