### ISSUE TITLE
[PL][Dungeon][Azjol-Nerub][Server Crash]

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#1175]
Podczas bicia ostatniego bossa w instancji, którym jest Anub'Rekhan bardzo możliwe, że następuje crash. Gdy Anub podczas walki znajduje się pod ziemią zaczyna summonować addy, których co następne zejście pod ziemię przybywa w bardzo dużych ilościach. Podczas drugiego zejścia addów jest ponad 100, których nie można zobaczyć ani bić. Dodatkowo addy atakują nas ale nie mogą nas trafić (miss i dodge). Za pierwszą próbą gdy addów było około 100 nastąpił spadek fps do 1 i wow wyłączył się (brak odpowiedzi), natomiast inni gracze umierali w skutek otrzymanych obrażeń. Za drugim podejściem przy takim samym ciągu zdarzeń najzwyczajniej wystąpił crash.
Anub'arak - http://www.wowhead.com/npc=29120/anubarak#abilities

**Comment by Varchord** [comment]
Lol wut? Biłem go dziś i nic takiego nie miałem. Screeny mogłeś zrobić

**Comment by Arcadia713** [comment]
Potwierdzam, że jakieś małe niewidzialne addy się pojawiają, bo dostajemy bardzo dużo "hitów" po ~50-100dmg co skutkuje instantową śmiercią postaci na ~70-71lvl (około 50 hitów na sekundę). Nie mam screenów póki co, jak będę expił alta i trafię na Anub'a to porobię.

**Comment by Varchord** [comment]
A ja wiem co to jest w takim razie!
to jest to
http://www.wowhead.com/spell=53520

**Comment by Hextall** [comment]
Tym razem zrobiłem to sam na postaci z 85 i poszło bez żadnych problemów. Wiec możliwe, że gdy w party jest 5 osób może się bugować http://www.wowhead.com/spell=53520.

**Comment by Bildo** [comment]
nadal wystepuje bug ?

**Comment by Varchord** [comment]
To pewnie jak z nefarianem. Bug okresowy :P
