### ISSUE TITLE
[EN][Quest][Borean Tundra] Words of Power

### ISSUE THREAD

**Issue by Cedril** [Atlantiss/BugTracker#1176]
Quest: http://www.wowhead.com/quest=11942

I have 2 issues in this quest.

1. One of the [NPCs](http://www.wowhead.com/npc=25392) does not always drop quest item (although he should). It only occured with this one in my case.

2. It is connected with overall pathing, but [one of them](http://www.wowhead.com/npc=26073) spawns in textures (under the spawn point) and he is targatable, but not pullable. I have not checked if this situation happens with other NPCs.

**Comment by Bildo** [comment]
fixed in rev 4240

**Comment by Hordraric** [comment]
i tried to do this quest and mob is still under the textures, dont know it it reverted back the bug

**Comment by drakthar** [comment]
High Priest Talet-Kha seems to still spawn under the textures:
![wowscrnshot_022415_164505](https://cloud.githubusercontent.com/assets/4015470/6351522/e921c4bc-bc44-11e4-95f8-cb996495b288.jpg)

**Comment by Thefakemccoy** [comment]
Still spawns under floor.

![wowscrnshot_050915_132725](https://cloud.githubusercontent.com/assets/12252441/7551223/3199eae6-f64f-11e4-9952-bd2c015712e9.jpg)

**Comment by Dean1989** [comment]
confirmed
