### ISSUE TITLE
[EN][Talent][Warlock] Backdraft

### ISSUE THREAD

**Issue by Cedril** [Atlantiss/BugTracker#1177]
This bug revolves around two talents:
[Backdraft](http://cata.openwow.com/spell=54277)
[Backlash](http://cata.openwow.com/spell=34936)

When someone casts instant Incinerate or Shadow Bolt from Backlash, while having Backdraft  active as well, one stack from Backdraft is taken.

I have seen couple movies from Warlock Destruction on 4.3.4, and on neither of them were the stacks consumed. One of them is:
https://www.youtube.com/watch?v=b3bThA9zt88
Clearly seen throught most of the video.

**Comment by Propolys** [comment]
This seems to have been a bug that existed on Retail too. Just noticed this today. Didn't expect it to be known already.

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
