### ISSUE TITLE
[PL] [Spell] [Priest] Devouring Plague

### ISSUE THREAD

**Issue by Malylolek** [Atlantiss/BugTracker#1178]
http://www.wowhead.com/spell=2944

Przy 4365 SP i 28,25%hasta
W tooltipie skilla pisze że zada 12120 dmg
W rzeczywistości zadaje 11930 dmg  w 10 tickach każdy po 1193 dmg

Ino nie wiem czy to visual tylko czy coś ale zgłaszam.

**Comment by kadi2** [comment]
Nawet na retailu, wiele tooltipow nie podawalo rzeczywistej wartosci umiejetnosci.

**Comment by Aviannaqt** [comment]
Możliwe ze visual. SW:P też bije o 100 mniej niż w tooltipie, i reszta spelli podobnie.

**Comment by Malylolek** [comment]
SW:P nie ma dmg w tooltipie ;c tak samo jak Mind blast
