### ISSUE TITLE
[EN] [Talent] [Hunter] Lock and Load

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#1180]
Lock and load should give 2 free explsive shots. First is free but second costs focus
http://www.wowhead.com/spell=168980/lock-and-load

**Comment by Howlingwolf** [comment]
I checked it today. It works properly.

**Comment by xolon** [comment]
Iv reseted my talents still same problem, but all the other hunters dont have it

**Comment by xolon** [comment]
It works properly on Training dummy but in group, rdf it doesn't. Don't know whats causing it

**Comment by xolon** [comment]
When l&l pops if you fire both explosive shots in same time ( second instantly after first one ) you lose focus, but if you wait like 1-2 seconds between then you don't.

**Comment by Howlingwolf** [comment]
Xolon, I strongly not recommend firing both shots one after another. Smart stacking is still not working for explosive shot, they overwrite each other.  Put a dump skill between explos. You can avoid losses of the focus, and won't overwrite one shot with the second one.

**Comment by Morderczyk** [comment]
Howling if you use Arcane Shot between "free"  Explosive Shot second explo cost focus.

**Comment by Howlingwolf** [comment]
Kay, i checked it again.  You were right guys. This happens only if "freebies" are shot quicker than ~1.1s one after another. So even if we use coba/steady which have a shorter time cast than 1s this problem may occur.

**Comment by arekczup** [comment]
j test lock and load is working already and stack is 7 hits  3 us explosive shot.

**Comment by Oldworldgame** [comment]
U mnie występuje identyczny problem z explosive shot. Podczas lock&load drugi kosztuje focus podczas rotacji exp-arc-exp, natomiast podczas rotacji exp-cobra-exp czasem kosztuje a czasem nie. Chcialbym jeszcze dodac ze podczas encounter Chimareon gdy boss stanie bardziej z tylu kolo klatki pety nie moga w ogole bic poniewaz nie potrafia zejsc do wody za bosem.

**Comment by arekczup** [comment]
sprawdzałem na moim hunterze wszystko. Nie działa mi tylko stakowanie mam postać trolla pewnie dla tego część problemu mojej postaci nie dotyka.

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
