### ISSUE TITLE
[EN][Battleground][Error...ish] Error #132 while playing Strand of the Ancients

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1182]
Today i got error on BG Strand of the Anciets (just randomly, when i was fightning - nothing special like vehicle/start or end bg) and when i was trying to log in i got same error over, and over again (i was clearing cache after every crash). I noticed about half of our party had these errors (since they disconnected aswell).
Screen: http://wstaw.org/m/2015/01/01/Untitled.png

If you need specific report of error check this thread: http://atlantiss.eu/community/viewtopic.php?f=10&t=476&p=2205#p2205 (i put this there because it'd be too spammy here since we can't put messages on [spoiler])

**Comment by aje** [comment]
can you give the full error message again please (the forum link is dead)
