### ISSUE TITLE
[PL]Achievement 1000 Fish

### ISSUE THREAD

**Issue by Lauthai** [Atlantiss/BugTracker#1185]
Achievement nie nalicza ryb, wartość zostaje zatrzymana od czasu update'u.

**Comment by eryczek1615** [comment]
http://www.wowhead.com/achievement=1561

**Comment by xALSQ** [comment]
Lauthai did you manage to get any of the previous achievements? I couldn't even start the 25 Fish one. (Is this a duplicate then?, #896)

**Comment by Lauthai** [comment]
Only because i had 617/1000 when there was still wotlk on this server. It stopped.

**Comment by qubuslabadz** [comment]
Fixed in rev. 4266
