### ISSUE TITLE
[EN][Spell][Druid] Leather Armor Specialization (Mana pool)

### ISSUE THREAD

**Issue by PlayFullTV** [Atlantiss/BugTracker#1189]
Character: Playfull
Level: 85

My mana pool is lower in Resto spec than in Feral spec. Wearing the same healing gear. I'm wearing all leather. Looks like armor specialization passives are bugged? The same bugged happened on my last server when they updated to this patch. Similar mana pool problems are present with some of my guildies.

**Comment by aneq** [comment]
Looked up your armory.
In feral, you're specced into 3/3 furor which also happens to increase your maximum mana by 5% per rank (15% on 3/3)
In your resto spec however, you don't have this talent. Is this where your maximum mana has gone? :)
