### ISSUE TITLE
[PL][Instance - WotLK] Utgarde Keep

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#119]
http://www.wowhead.com/npc=24111 - znajduje się w niepoprawnym (starym) miejscu poza instancją (notka: na nowej lokalizacji powinien być widoczny tylko dla alliance)
http://www.wowhead.com/quest=11252 - deprecated
http://www.wowhead.com/quest=13205 - deprecated; zastąpiony przez http://www.wowhead.com/quest=29764
http://www.wowhead.com/quest=29803 - dodać do listy oferowanych questów npc=24111
http://www.wowhead.com/quest=29763 - dodać do listy oferowanych questów npc=24111

http://www.wowhead.com/npc=24137 - odpowiednik hordy dla npc=24111
http://www.wowhead.com/quest=30112 - odpowiednik hordy dla quest=29803
reszta dla niej powinna być w porządku, ID pozostałych questów dla tego NPC się nie zmieniło

**Comment by sharlatan** [comment]
still dont have http://www.wowhead.com/npc=24137, and quest http://www.wowhead.com/quest=30112/a-score-to-settle gives this http://www.wowhead.com/npc=23780/high-executor-anselm npc, but when start cata, all quests give only http://www.wowhead.com/npc=24137
