### ISSUE TITLE
(PL) The Spirits of Golakka Hot Springs (Q)

### ISSUE THREAD

**Issue by Toxicplayer** [Atlantiss/BugTracker#1190]
NPC ma dla nas questa ktorego nie można wziąć, pokazuje że mamy niby complete ale nic się nie da zrobić

**Comment by Varchord** [comment]
Tytuł, wowhead linki

**Comment by Toxicplayer** [comment]
http://www.wowhead.com/quest=24706/the-spirits-of-golakka-hot-springs

**Comment by Bildo** [comment]
duplikat
