### ISSUE TITLE
[EN] [NPC] Angela Leifeld, Shaina Fuller

### ISSUE THREAD

**Issue by Dearkus** [Atlantiss/BugTracker#1192]
Both NPCs stand in the same spot in Stormwind City. Angela Leifeld doesn't train, but Shaina Fuller does. As of patch 4.3 Shaina Fuller was replaced by Angela Leifeld.
WoWHead:
Angela Leifeld: http://www.wowhead.com/npc=56796
Shaina Fuller: http://www.wowhead.com/npc=2327

**Comment by Tj20** [comment]
Now there's only Angela Leifeld on that spot (who doesn't train), the first aid trainer Shaina Fuller (who does train) is gone.

**Comment by Bildo** [comment]
ohh my fault ;p when i delete Shaina Fuller i forgot about Angela Leifeld i will fix it soon

**Comment by Bildo** [comment]
fixed in 4248
