### ISSUE TITLE
[EN][Quest][Dun Morogh ] It's Raid Night Every Night

### ISSUE THREAD

**Issue by silverches** [Atlantiss/BugTracker#1193]
Normally frostmane riders should spawn but they aren't spawning on 4.3.4.

http://www.wowhead.com/quest=25932/its-raid-night-every-night
https://www.youtube.com/watch?v=UpeOj3thiDQ

**Comment by Wolffenstein** [comment]
Works fine for me.

**Comment by Wolffenstein** [comment]
Fixed in rev 4191.

**Comment by xandis1** [comment]
Bug seems to have reappeared...
