### ISSUE TITLE
[EN][Hunter][Pet][Spell] Wolverine Bite

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#12]
http://cata.openwow.com/spell=53508
Spell is supposed to have a condition that makes it usable only when pet has made a critical attack, also it's damage is way too small, it seems like it doesnt stack with hunter stats.

**Comment by meowmewo** [comment]
Confirmed. It does no get affected by any of the hunters nor pets stats.It gits for like 700 :D .

**Comment by meowmewo** [comment]
:( Bump Bump

**Comment by meowmewo** [comment]
Bump again. Cmon now..u fixed every pet formula that gave extra dps to the pet...now its time to fix the things that make us loose dps.

**Comment by ShockRW** [comment]
Make a new entry about this, so they may notice it.

**Comment by mzn928** [comment]
shameless bump. its still bugged

**Comment by TranceAccount** [comment]
Openwow is sleeping at the moment:
http://wowwiki.wikia.com/wiki/Wolverine_Bite

**Comment by ShockRW** [comment]
BUMP

**Comment by TranceAccount** [comment]
Instead of bumping, why not update what is wrong, since I think there is only something wrong with the damage it deals.

**Comment by TranceAccount** [comment]
Can ANYONE describe exactly what the problem is with Wolverine Bite, since this report is not clear and very old.
