### ISSUE TITLE
[EN] [Profession] [Archeology] Not enough fragments / missing loot info

### ISSUE THREAD

**Issue by WarCrow** [Atlantiss/BugTracker#1200]
In patch 4.3 is undocumented change about number of fragments we get from digging, it should be 5-9 now but on the server it is 3-5 (on max lvl)

Links:
http://www.wowdigsite.com/2011/12/patch-4-3-for-archaeologists/
http://wow.gamepedia.com/Patch_4.3.0_%28undocumented_changes%29

Furthermore im not getting any info (on chat) about how much fragments i get

**Comment by Wolffenstein** [comment]
Fixed in rev 4193.
