### ISSUE TITLE
[EN][Quest][Ashenvale]All's Well(ID 13924)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1202]
Quest is missing.It should be available after quest [In the Hands of the Perverse](http://www.wowhead.com/quest=13922).

Wowhead link: [All's Well](http://www.wowhead.com/quest=13924)
Openwow link: [All's Well](http://cata.openwow.com/quest=13924)
Gamepedia link: [Quest:All's Well](http://wow.gamepedia.com/Quest:All%27s_Well)

Youtube link: https://www.youtube.com/watch?v=Vd3tx9mGoTE#t=156

**Comment by Bildo** [comment]
fixed
