### ISSUE TITLE
[EN][Quest][Dun Morogh] Extinguish the Fires Quest 

### ISSUE THREAD

**Issue by silverches** [Atlantiss/BugTracker#1203]
http://www.wowhead.com/quest=26078
https://www.youtube.com/watch?v=n_5uMEqnuV8

The flames aren't showing. The quest itself works.

**Comment by hbalazs1** [comment]
It's working, but " The flames aren't showing".

**Comment by silverches** [comment]
Yes and you need to be in a precise spot or it won't work.
Op 17 feb. 2015 13:17 schreef "hbalazs1" <notifications@github.com>:

**Comment by Wolffenstein** [comment]
Fixed in rev 4331.
