### ISSUE TITLE
[PL][Paladin][Talent] Acts of Sacrifice

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1206]
http://www.wowwiki.com/Acts_of_Sacrifice
Cleanse ( http://www.wowhead.com/spell=4987/cleanse ) nie usuwa efektów spowalniających, bynajmniej przy wydaniu na talent 1 punktu. Co ciekawe, nie działa on na arenach i battlegroundach natomiast w duelach już tak. Proszę o skorygowanie, bądź podzielenie się swoimi opiniami na ten temat.

**Comment by Varchord** [comment]
Sprawdź czy respec pomaga. Może być jak z primal fury

**Comment by Varchord** [comment]
Hmm. A na kogo rzucasz cleansa na tych bg i arenach? Bo to ma działać tylko na tobie

**Comment by Wolffenstein** [comment]
Działa dobrze.
