### ISSUE TITLE
[PL][Mob][Mount Hyjal]  Twilight Proveditor

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1207]
http://pl.tinypic.com/r/10yqfs8/8  
http://www.wowhead.com/npc=39436/twilight-proveditor  - MOB

Spora ilość mobów zbugowanych w sobie.

Było ich mniej więcej (na oko) 50:
http://pl.tinypic.com/r/11t9cfk/8
http://pl.tinypic.com/r/208w6cp/8
http://pl.tinypic.com/r/208w6cp/8

To mnie tak na hita

**Comment by Bildo** [comment]
duplikat https://github.com/Atlantiss/BugTracker/issues/1110
