### ISSUE TITLE
[PL] [Core] [Nick]  polskie znaki w friend

### ISSUE THREAD

**Issue by jurek1** [Atlantiss/BugTracker#1209]
Mam nick "Krowka" , jak ktos chce mnie dodac do znajomych to automatycznie dodaje nick przez "ó"  z czym wiaze sie wyswietlanie mnie z brakiem aktywnosci .

**Comment by Danelar** [comment]
Ale że ludzie się mylą?

**Comment by Wolffenstein** [comment]
Niech patrzą co wpisują...

**Comment by Bildo** [comment]
ale serio jak wpiszesz Krowka to do znajomych dodaje sie Krówka ;p

**Comment by Wolffenstein** [comment]
Cache?

**Comment by Bildo** [comment]
po wyczyszczeniu nadal dodaje Krówka, dodam, ze z postaicia Krowka ani Krówka nigdy nie rozmawialem i nie bylem w gildii ;p

**Comment by jurek1** [comment]
no jakby ktos sie pomylil czy cos to bym nie pisal.. xD
od poczatku jak expie na tym nicku tak jest

**Comment by Varchord** [comment]
Tłuste bugi. Ja bym banował :P

**Comment by Bildo** [comment]
Nie powiem o co mnie prosiles przed chwila ;)

**Comment by Arcadia713** [comment]
High priority or riot! :D

PS: Potwierdzam ;p

**Comment by Varchord** [comment]
Ale że mi to dałeś Bidlo!

Syf troche tu robimy xd

**Comment by jurek1** [comment]
nie jestem pewien , ale chyba tez maila nikt do mnie nie moze wyslac , bo ja i kolega o 20 zamowilismy glyphy u kolesia , jemu doszlo o 22 a ja do tej pory nie mam : D ( a wysylal z 5 min po tym jak wyslal koledze ) 
zaczekam do jutra , jak nadal nie bedzie maila to napisze

**Comment by Beatit** [comment]
dać vp na zmiane nicki i fixed ;)

**Comment by jurek1** [comment]
wczoraj wyslalem tez z drugiej postaci ( na tym samym koncie ) maila do krowki , tez kolega wyslal od siebie  i do tej pory nie doszlo ... ( tak samo ten mail z glyphami od typa )  

jest mozliwosc zmiana nicku na inny? ( chyba ze to naprawicie : D )

**Comment by Danelar** [comment]
Czyli, że wysyłają do do Krowka, a idzie do Krówka? :D

**Comment by jurek1** [comment]
tak , tak samo z nickiem pisza Krowka a dodaje Krówka :palm_tree:

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by jurek1** [comment]
serio? ..  moze bys napisal reason tego zamkniecia , linka z wowheada ci nie dam jezeli chodzi o nick o.O
tak samo nazwe tematu jak mam zmienic , na [quest]? ..
zreszta kazdy wiedzial o co mi chodzi i potwierdza ze jest to bug

**Comment by Varchord** [comment]
Dał ci powód

**Comment by jurek1** [comment]
dal mi jedynie link , https://github.com/Atlantiss/BugTracker/wiki/How-To%3F  , jezyk jest dodany, problem tak samo ( jak nie zrozumiale to mozna przecież edytowac a nie zamykac.. ) , link do wowheada to raczej nie podam...   tagi ticketu no raczej to jest [core] [ nick ] , w faq nie ma tego podane , ale to co mam dac  [npc] [spell] ?.. no bez przesady

**Comment by kadi2** [comment]
"On the Bugtracker all titles of reports must be written in English" - zapobiega to duplikatom zgloszen

**Comment by jurek1** [comment]
no to moderator chyba ma opcje edytuj , a nie odrazu zamkykac . 
mam nadzieje ze teraz jest dobrze.. ;x

**Comment by Danelar** [comment]
No właśnie :/
