### ISSUE TITLE
[EN][Raid] BOT 10H and 10N Valiona Devouring Flames.

### ISSUE THREAD

**Issue by int24rain** [Atlantiss/BugTracker#1210]
This week while we was trying Valiona HC (to see if t he invisible flames are fixed) faced a new Valiona invicible ability!The Whirlwind Flames.
Instead to "spit" the flames in 1 way, after 1 second she is turning in another way killing 70% of the raid.This occurs only 1st time, second time is OK, then switch to Theralion and switch back to Valiona again 1st Flames are bugged.

**Comment by int24rain** [comment]
Update:
She is targeting someone obviously cause for like 5th time she is facing a different way, left,right and etc.Its unpredictable and not sure if its killable.

**Comment by jakubo98** [comment]
Boss http://www.wowhead.com/npc=45992
Ability http://www.wowhead.com/spell=86840

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838

already exist

**Comment by int24rain** [comment]
@Varchord I still doesnt understand polish :))) We are raiding this from 2 months and this is the first time Valiona is doing this stuff.Thats why I cr8 the issue.

**Comment by Malylolek** [comment]
Varchord post it for developer cause they can have list like : dev 1 fix issues 1212 and dev 2 fix 838 then dev 1 and 2 upload fix in same time to core and core get crash cause 1 and 2 script not match with 2 and 1. :P Sorry for bad English any way i try answer somehow.

**Comment by Varchord** [comment]
You just can look at the boss name in my report and see that i've reported Devouring Flames ability
