### ISSUE TITLE
[PL][Item]"Stave of Fur and Claw"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1216]
Gdy zamieniam się w Furbolga, to wsiadając na Mounta ( naziemnego i latającego ) stoję na nim chociaż klikając 'X' mogę zauważyć, że wprogramowaną czynność siedzenia. 

Link: http://www.wowhead.com/item=66888/stave-of-fur-and-claw

**Comment by Navedonar** [comment]
https://www.youtube.com/watch?v=cyCBRy2sPP0
