### ISSUE TITLE
[EN][Quest][Lost Isles] The Biggest Egg Ever

### ISSUE THREAD

**Issue by Hacker--x** [Atlantiss/BugTracker#1219]
http://www.wowhead.com/quest=24744/the-biggest-egg-ever
You basically need to kill a giant chicken, loot it and get the egg to continue the Goblin starting quests (a compulsory quest) and the looting of the egg is buggy, you can get it after 10 minutes of spamming loot, but it is difficult and wastes time especially for those leveling another goblin

**Comment by cosminush** [comment]
confirmed!

**Comment by Bildo** [comment]
Of course you can u just need to wait a couple of minutes or relog etc

**Comment by Hacker--x** [comment]
Yes exactly wastes time, but if you guys know about it then I'm sure you have it under control:)

**Comment by Tj20** [comment]
I've had trouble with the eggs as well. Killing the chicken+relog+waiting 5 minutes afterwards didn't help.

Killing the chicken and just wait (don't log out) did the trick for me. 55 seconds after killing the chicken all the eggs in the area became lootable for me.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
