### ISSUE TITLE
[PL][Item] Mysterious Egg

### ISSUE THREAD

**Issue by kazuuhiro** [Atlantiss/BugTracker#1222]
Nie działa Mysterious Egg http://www.wowhead.com/item=39878 kupione od NPC Geen <Oracles Quartermaster> http://www.wowhead.com/npc=31910 w Sholazar Basin.

**Comment by Kiperr** [comment]
Spróbuj trzymać jajo w backpacku.

**Comment by air7** [comment]
Jajo działa jeśli trzyma się jest w backpacku, Kupiłem wczoraj i pisało 3 dni do otwarcia jaja, dzisiaj już pisze że 2 dni.

**Comment by Blackaddder** [comment]
Nie działa! po relogu zawsze pokazuje 0 sec, po ruszeniu 3 days. Mija z 4 dzien a jajko jakie bylo takie jest.

**Comment by LaveniaGithub** [comment]
I've never had problems with this item.

**Comment by Anhaeyn** [comment]
Działa. Trzymaj w głównej torbie i będzie działać.

**Comment by pelekon** [comment]
fixed in rev 5901
