### ISSUE TITLE
[PL][NPC] Aneera Thuron

### ISSUE THREAD

**Issue by kazuuhiro** [Atlantiss/BugTracker#1223]
Brak NPC Aneera Thuron <Mistress of Hawkstriders> http://www.wowhead.com/npc=33548 w Icecrown (przez co o 2 mniej questów do wzięcia dla blood elfów.

**Comment by bgb** [comment]
Kiedy w końcu fix? :/ Brak tego npc bardzo spowalnia zbieranie Valiant seali :(
