### ISSUE TITLE
[PL][Quest][Tanaris] Easy Money

### ISSUE THREAD

**Issue by kazuuhiro** [Atlantiss/BugTracker#1226]
Biorę questa http://www.wowhead.com/quest=28557 ( Warchief's Command: Uldum! ) w Orgriammarze, oddaje go w Tanaris u Adarrah i na tym koniec, nie dostaję kolejnego questa http://www.wowhead.com/quest=27003 ( Easy Money )

**Comment by MasterK15** [comment]
Quest działa, na mapie nie pokazuje nam znaku zapytania (gdzie go oddać) i nie przenosi nas do miejsca w którym możemy go oddać ( zostajemy tam gdzie wsiadało się na karawane i musimy polecieć oddać Q, ktorego nie ma na mapie)

Quest działa i dostejemy Qesty dalej.

Robiłem wczoraj

**Comment by kazuuhiro** [comment]
nikt nie daje mi zadania o nazwie easy money jak pisałem wyżej. 
a jaką frakcją grasz? może to ma znaczenie

**Comment by Pazurek** [comment]
Przy karawanie w Tanaris powinieneś dostać tego q.

**Comment by kazuuhiro** [comment]
właśnie oddałem quest Warchief's Command: Uldum i jak widzicie Adarrah, która powinna dać questa tylko mnie pozdrawia.. ![wowscrnshot_010315_153417](https://cloud.githubusercontent.com/assets/10380285/5602665/216a515a-935e-11e4-947e-b01f85f5559e.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4198.
