### ISSUE TITLE
[EN][Dungeon][ShatteredHalls][Game Crashes]

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#1227]
So.. i was doing shattered halls with some random peep and a bit after the first boss when we tried to clear 1 group of mobs our games crashed and we all had to restart our PC so we can do sth .. When we tried again after we regrouped it happened again, and again and we gave up. Pls fix it asap ;x

P.S the same thing happened to me in Borean tundra while i was questing near Kaskala

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/870

Already Exist
