### ISSUE TITLE
[EN] [Spell] [Warlock]Apprentice Riding at Level 20

### ISSUE THREAD

**Issue by tremore** [Atlantiss/BugTracker#1228]
http://www.wowhead.com/spell=33388/apprentice-riding

Warlocks are automatically granted Apprentice Riding upon reaching level 20, but it isn't.

**Comment by Varchord** [comment]
And they should. Along with paladins and druids (fly form at 58)

**Comment by PVPViddys** [comment]
This shouldn't be closed I don't think. I just hit 20 on my warlock and got felsteed but didn't get apprentice riding.
