### ISSUE TITLE
[PL][Skill][Mage] Ice Block 

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1229]
Witam dzisiaj udało mi się użyć Ice Blocka na Arenie gdy miałem Cyclona Druida.
http://www.wowhead.com/spell=33786/cyclone   Cyclone
http://www.wowhead.com/spell=45438   Ice Block 

Dostałęm CD na blocku, cyclona mi nie zdjeło. 

Nie powinno mi dać CD na spellu ( nie moge go uzyc podczas Cyclona)

**Comment by KrolServera** [comment]
Jakbyś ss zrobił, a tak to kto ci uwieży?

**Comment by Arcadia713** [comment]
Who will tower you?

Przydałby się screen, próbowałem powtórzyć to wyskakuje komunikat, że nie można ;)

**Comment by Varchord** [comment]
Może użył w momencie kiedy dostał cycek? ^^

**Comment by Jenovas** [comment]
Pewnie identycznie w momencie cyclone dal iceblock i przez diffa odpalilo. Na globie są tez takie bugi. Najsłynniejszy to chyba bladestorm który wyciąga z CC jeżeli trafimy nim do max 0.5 SEC po dostaniu CC.

**Comment by MasterK15** [comment]
Możliwe, ale jestem pewien że ice block był chwilke po cycku + przed koncem Cycka był crash serwera ( nie wiem moze jakies powiazanie)

**Comment by Arcadia713** [comment]
To pewnie zlagowało czy coś, skoro jeszcze crash do tego - watpie, że Ice Block ściągnał Cyclone :P
