### ISSUE TITLE
[PL][PvP]Nazwy Team'ow i MMR

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1231]
Nazwy teamów i MMR są pokazane na odwrót (naszemu teamowi pokazuje MMR i nazwe teamu przeciwników, i na odwrót)

http://pl.tinypic.com/r/24kz7e9/8

Nasz team to Slow Fall
http://atlantiss.eu/armory/arena/10120#view-page

Team Arcadii
http://atlantiss.eu/armory/arena/11084#view-page

Team Slow Fall wygrał arene, lecz w tabeli nasz team był pokazany jako team przeciwników ( tylko visual- staty/win i rating przypisany poprawnie)

**Comment by kadi2** [comment]
![](http://www.img.pl/medium/YfJg.jpg)
Addony troche sie psuja przez to.

**Comment by Bildo** [comment]
duplikat
