### ISSUE TITLE
[PL][Item] Potion of Illusion

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#1234]
http://www.wowhead.com/item=58489
Potion nie działa . Po kliknieciu pisze "Not avaliable to you"

**Comment by reapertg** [comment]
This is still an issue. It might be a minor issue, but this is a very fun item used by many, and is a healthy source of income for upcoming alchemists. 2 year old issue now :(

**Comment by pelekon** [comment]
fixed in rev 5903
