### ISSUE TITLE
[EN][NPC][High Priority] Vendors Trainers etc

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1235]
Vendor npcs, trainers, auction house npcs, inkeepers, bank npcs are not working. You click on them and nothing happens. 

Bug appeard after crashfixes

**Comment by Beatit** [comment]
wszyscy vendorzy nie działają, trenerzy działają z tego co zauważyłem np. od alchemii ale każdy vendor już nie, nawet Ci z mamuta :)

**Comment by Varchord** [comment]
Trenerzy klas nie działają

**Comment by Bastion** [comment]
Innkeeper przy mojej afkerni działa, heheh :D

**Comment by Varchord** [comment]
No to jedyny NPC, który zauważyłem że działa

**Comment by Arcadia713** [comment]
Działa też Jeeves :D Ale Scrapbot już nie ;p

**Comment by Bastion** [comment]
Dobra działają po restarcie już, weź to zamknij ;d
