### ISSUE TITLE
[EN][Quest][Dragonblight] The Cleansing Of Jintha'kalar

### ISSUE THREAD

**Issue by Cedril** [Atlantiss/BugTracker#1237]
Quest:
http://www.wowhead.com/quest=12545/the-cleansing-of-jinthakalar

There are no mobs to kill to accomplish this quest.

Creatures that should appear there:
http://www.wowhead.com/npc=26946
http://www.wowhead.com/npc=26948
http://www.wowhead.com/npc=26965
http://www.wowhead.com/npc=26942
http://www.wowhead.com/npc=26943

**Comment by Bildo** [comment]
They are here.
