### ISSUE TITLE
[EN][Quest] [Stonetalon Mountains] Ashes to Ashes

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1241]
http://www.wowhead.com/quest=26010/ashes-to-ashes

* Quest item can be spammed off gcd
* You can burn the same tent multiple times
* Tents that appear as burned can still be burned ^^

**Comment by NONLIFE** [comment]
change [Quest-Classic] to [Quest][Stonetalon Mountains] it will be more accurate for others

**Comment by BAndysc** [comment]
Fixed in rev. 4464

**Comment by MercuricUma** [comment]
I don't remember if for my first lv 85 worked but for me at the moment it doesn't seem working. Tried to burn many tents using the quest item first in cat form and then "human" form , but I'm still 0/8 :(
