### ISSUE TITLE
[EN][Quest][Desolace]Calming the Kodo

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1242]
http://www.wowhead.com/quest=14309/calming-the-kodo

* After feeding the kodo trigger "enraged kodo kc bunny" is visible and stays for a while

**Comment by NONLIFE** [comment]
change [Quest-Classic] to [Quest][Desolace] it will be more accurate for others

**Comment by Bildo** [comment]
fixed
