### ISSUE TITLE
[EN] [Class] Restoration Druids

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#1247]
Restoration Druids are way off there not healing very well at all i am all epic gear and may heals are only doing 3,000 heals per tick with me Rejuvenation and 10,000 heals with my Healing Touch i have never healed so low on my Charactor 4.0.6 i was doing just fine but now this is a big problem and needs to be checked.

**Comment by Varchord** [comment]
So check it. Go through every spell, every talent and make reports if you find something.
This issue will be closed anyway because it's too.. unspecified(?)

**Comment by Spydoc** [comment]
I don't know if this is relavant, but here are two screenshots of the healing meters on boss encounters. My Holy Paladin had roughly 340 ilevel, with the Restoration Druid having full epic gear.
http://imgur.com/bJyVO61,j6AtZUg
http://i.imgur.com/j6AtZUg.jpg

**Comment by Varchord** [comment]
Irrevelant for this boss. 
You heal only to around 10% of players health and paladin has absorbs (this make a huge difference)

Like i said. Check every spell and talent

**Comment by InformatorPE** [comment]
Rejuvenation working
![image](https://cloud.githubusercontent.com/assets/8093039/5606190/eecacc50-9422-11e4-871e-c41f6ac0eade.png)

**Comment by InformatorPE** [comment]
Healing Touch works
![image](https://cloud.githubusercontent.com/assets/8093039/5606233/b08f1a6a-9425-11e4-9854-8f8865d93915.png)

**Comment by InformatorPE** [comment]
Nourish works
![image](https://cloud.githubusercontent.com/assets/8093039/5606378/c17076a6-942c-11e4-896b-da352f339f05.png)
