### ISSUE TITLE
[PL][Quest][Isle Of Quel'Danas] The Air Strikes Must Continue

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1250]
http://www.wowhead.com/quest=11533/the-air-strikes-must-continue
https://www.youtube.com/watch?v=Y1SU5tanGWs
Nie można wykonać. Zalicza kilka sztuk z każdego rodzaju mobów:
http://www.wowhead.com/npc=25031
http://www.wowhead.com/npc=25033
http://www.wowhead.com/npc=25030
następnie moby są odznaczone jako cele i zabijanie ich nie aktualizuje statusu questa

**Comment by snoopyrock85-85** [comment]
Aktualizacja tematu :
Quest działa, nie aktualizuje tylko postępu zadania w quest logu, co mnie zmyliło. Temat do zamknięcia

**Comment by Danelar** [comment]
Aha...
