### ISSUE TITLE
[EN][Raid-Cataclysm][NPC] Valiona

### ISSUE THREAD

**Issue by Blasiren** [Atlantiss/BugTracker#1251]
During the encounter  Valiona should use her ability called Devouring Flames (http://www.wowhead.com/spell=86840) which works but with a rather painful bug. Valiona doesn't turn in the direction she's breathing fire, due to that half of the raid group gets wiped because they can't avoid it (Valiona turns in the direction she's breathing fire right before dealing damage). I'm hoping for a fast fix due to the fact that smaller guilds can't kill the boss and progress further.

Podczas walki Valiona powinna używać umiejętności która nazywa się Devouring Flames (http://www.wowhead.com/spell=86840) co działa ale z dość bolesnym bugiem. Valiona przed zionięciem ogniem nie odwraca się w strone w która nim zieje co skutkuje szybkim wipem gdyż nie da się tego uniknąć (Valiona odwraca się zaraz przed zadaniem obrażeń). Licze na szybkiego fixa ponieważ mniejsze gildie nie mogą zabić tego bossa i progressować dalej.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838
Dubel
