### ISSUE TITLE
[EN] [QUEST] [NPC] Return to Angrathar

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#1253]
After returning this quest a cinematic should be available (currently it isn't). Also, Alexstrasza <The Life-Binder> should be in front of the Wrathgate after the cinematic and show it again if you ask her.

Quest:
(Alliance) http://www.wowhead.com/quest=12499/return-to-angrathar
(Horde) http://www.wowhead.com/quest=12500/return-to-angrathar

NPC:
http://www.wowhead.com/npc=55394#sounds

Cinematic:
https://www.youtube.com/watch?v=iLANMJF-s5A

**Comment by Bildo** [comment]
fixed in rev 4245
