### ISSUE TITLE
[EN][Quest][Stonetalon Mountains]Rumble in the Lumber... Mill(ID 25669)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1258]
NPC [Warlord Roktrog](http://www.wowhead.com/npc=41063) is missing/not spawing when take the quest so you cannot complete quest.

Wohead link: [Rumble in the Lumber... Mill](http://www.wowhead.com/quest=25669)
Openwow link: [Rumble in the Lumber... Mill](http://cata.openwow.com/quest=25669)

How it should work: https://www.youtube.com/watch?v=xiIuspLa3cA#t=147

**Comment by Bildo** [comment]
4250 fixed

**Comment by Deadlyblonde** [comment]
Mob już się pojawia ale klatka od NPC jest wciąż otwarta i nie można zaliczyć zadania.
