### ISSUE TITLE
[EN][Quest][Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by seanyuan1994** [Atlantiss/BugTracker#1259]
The Totem tends to fade away before anythings happen's and the minion's don't seem to spawn after the first kill.
(Quest)Alliance
 http://www.wowhead.com/quest=13580/soothing-the-elements
https://www.youtube.com/watch?v=RZa6hZapjMw

**Comment by Aival94** [comment]
Please check first if already reported. 

#762

You can close it or someone will mostly close it for you.
