### ISSUE TITLE
[EN][Quest][Stonetalon Mountains]Arcane Legacy(ID 25766)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1260]
Using the item [Highborne Prison](http://www.wowhead.com/item=55972)(which use  spell [Highborne Prison](http://www.wowhead.com/spell=77306) which trigger [Highborne Prison](http://www.wowhead.com/spell=77307)) only kill everything which is around it(including other NPCs or even the player is near it).

Wowhead link: [Arcane Legacy](http://www.wowhead.com/quest=25766)
Openwow link: [Arcane Legacy](http://cata.openwow.com/quest=25766)

How it should work: https://www.youtube.com/watch?v=yAcfpQfj-58

**Comment by Bildo** [comment]
4250 fixed
