### ISSUE TITLE
[PL][Class][Druid] Lifebloom

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1261]
http://www.wowhead.com/spell=33763
https://www.forgottenlands.eu/showthread.php/8193-Formule-Spell-Restoration

Lifebloom za malo leczy z hoty, ale to nie znacznie oraz bardzo znacznie z direct healinga

![image](https://cloud.githubusercontent.com/assets/8093039/5606507/a446e80c-9432-11e4-866e-86c0aefbc431.png)

**Comment by kadi2** [comment]
Lifebloom HoT doubledippuje sie z buffem 15% Healing done z Tree of Life...

**Comment by Jenovas** [comment]
Fixed in rev 4706
