### ISSUE TITLE
[PL][Raids - Classic]

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#1263]
W każdym z raidów classic nie ma ani mobow, ani bossów, ani NPC. Instancje są puste.

http://www.wowhead.com/zone=2717/molten-core
http://www.wowhead.com/zone=2677
http://www.wowhead.com/zone=3429/ruins-of-ahnqiraj
http://www.wowhead.com/zone=3428/temple-of-ahnqiraj

**Comment by Arcadia713** [comment]
Dziwne, bo przedwczoraj robiłem Molten Core i BWL, i wszystko działało ładnie. Może zmień "trudność" raidu na 10 Normal czy coś.

**Comment by InformatorPE** [comment]
Na MC zdarza sie ze nie ma Ragnarosa i Majordomo Executusa

**Comment by Aviannaqt** [comment]
Rzeczywiscie, moby sa tylko gdy zmienie na 10 man. 
Mimo tego nie wiem czy powinno tak byc xD
Dzięki Arcadia :)

**Comment by Bildo** [comment]
powinno tak byc, heroic ogolnie powinien byc niedostepny
