### ISSUE TITLE
[EN][Quest][Storm Peaks] Cold Hearted

### ISSUE THREAD

**Issue by Cedril** [Atlantiss/BugTracker#1269]
In this quest:
http://www.wowhead.com/quest=12856
there are not enough [Brunnhildar Prisoners](http://www.wowhead.com/npc=29639) to save. Currently we are able to pick up 4 Prisoners, and we have to wait for their respawn.

**Comment by Bildo** [comment]
fixed in rev 4245

**Comment by lolsund** [comment]
still bugged

**Comment by Bildo** [comment]
this quest should be rewritten :<
