### ISSUE TITLE
[PL][Class][Druid] Starsurge

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1270]
http://www.wowhead.com/spell=78674
https://www.forgottenlands.eu/showthread.php/8324-Formule-Spell-Balance

Starsurge bez zadnego eclipsa (lunar/solar) bije srednio o okolo 550 dmg za malo, natomiast z eclipsem (solar +53%/lunar + 53%) bije o okolo 800-1000 dmg za malo.

![image](https://cloud.githubusercontent.com/assets/8093039/5606975/874c6654-9447-11e4-941d-dbbf77433550.png)
![image](https://cloud.githubusercontent.com/assets/8093039/5606984/97c916b2-9447-11e4-898c-89207079084c.png)

**Comment by Wolffenstein** [comment]
Nie jestem przekonany co do tych formuł i już tłumaczę dlaczego - bazowy dmg tego spella nie wynosi 1212, jest on przedziałem 1017,73 do 1405,43  (dane z dbc). Coeff jest prawidłowy, więc bazowy dmg spella na pewno jest prawidłowy (nie wiem jak z eclipsem). Dlatego nie ufałbym tym formułom, tym bardziej, że dr damage również przyznaje mi rację.

**Comment by InformatorPE** [comment]
![image](https://cloud.githubusercontent.com/assets/8093039/5607137/c771872c-944d-11e4-968a-64a2fef37550.png)

**Comment by Wolffenstein** [comment]
Co by znaczyło, że nie spell jest zbugowany, a któryś z talentów.

**Comment by Varchord** [comment]
Wszystkie talenty zwiększające spell damage działają. Sprawdzałem dziś rano. W tym master shapeshifter

**Comment by Varchord** [comment]
Sprawdzałem na tickach dot bo ich dmg zawsze jest taki sam

**Comment by Wolffenstein** [comment]
No to nie wiem, mi dmg się zgadza...

**Comment by InformatorPE** [comment]
Podany dmg ze spella w bialej tabelce jest damage usredninym, co oznacza ze uderzenia z tego spella mialy wartosci nizsze oraz wyzsze wzgledem wartosci usrednionej (wartosci normalnego uderzenia [crity w czasie testu byly pomijane]). Jak juz zostalo ustalone zolta tabelka ma blednego coefa, natomiast tabelka pomaranczowa i oliwkowa zawiera damage ze spella Starsurge z przedziału sp coeffa "1017,73 do 1405,43 (dane z dbc)" co oznacza ze dmg powinien sie miescic w przedziale 13969-14203 dmg spella bez eclipsa, gdzie usredniona wartosc spella bije 13370, mozna zaobserwowac iz dana wartosc nie miesci sie w przedziale dmg, rowzniez dmg z przedzialu 20954-21731 damage spella Starsurge z eclipsem ktory zwieksza dmg ze spelli natute i arcane o 53% (Starsurge jest spellem nature i arcane), dmg usredniony z eclipsem wynosi 20368 dla eclipsa lunar oraz 20568 dla eclipsa sonar, gdzie rowzniez obie wartosci nie mieszcza sie w wyliczonym przedziale.
Z powyzszych obserwacji mozna wnioskowac że jednak cos nie dziala, wiec prosilbym nie pisac ze cos dziala jak cos nie dziala, w tym przypadku dmg ze spella Starsurge jest zanizony.

**Comment by InformatorPE** [comment]
update
przesymulowalem dmdge w programie SimultionCraft z talentami/itemami/statami itd z atlantissa i wedlug symulacji starsurge powinien bic:
http://zapodaj.net/c9ac0c4c17072.jpg.html

**Comment by InformatorPE** [comment]
Po globalnym restarcie talentow damage starsurge jest taki sam jak w bialej tabelce/ czyli taki jak byl zglaszany, nie bije tyle ile powinien bic.
