### ISSUE TITLE
[EN][Quest][Stonetalon Mountains]Save the Children!(ID 25899)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1272]
NPC [Thal'darah's Hippogryph](http://www.wowhead.com/npc=41529) when on mount somehow is trying to fly even when on the ground and when you try to use [Drop Off Young Druid](http://www.wowhead.com/spell=77629)(which should kill credit for [Helpless Young Druid](http://www.wowhead.com/npc=41528)) when you are near Thal'darah  Hippogryph Station it say that you should be near there.

Wowhead link: [Save the Children!](http://www.wowhead.com/quest=25889)
Openwow link: [Save the Children!](http://cata.openwow.com/quest=25889)

![wowscrnshot_010415_171943](https://cloud.githubusercontent.com/assets/10282971/5607254/2699350c-945c-11e4-82f4-e99130cddcb7.jpg)

How it should work: https://www.youtube.com/watch?v=7dnEk5k_K_I

**Comment by ammeba** [comment]
Up. Can not drop off druids at the destination point.
