### ISSUE TITLE
[PL][Instance-TBC][Magisters' Terrace] Heroic Mode

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#1273]
Link do insty: http://www.wowhead.com/zone=4131/magisters-terrace
Link do starego q: http://www.wowhead.com/quest=11492
Link do nowego q: http://www.wowhead.com/quest=29685

Obecnie jest tak, że Heroic Mode MT nie jest u nas dostępne bez ukończenia chaina.
Natomiast wymogi związane z posiadaniem kluczy i/lub wykonaniem chainów do inst TBC zostały zniesione(np. Arcatraz).

Chain został usunięty, a w zasadzie przeniesiony do insty. Na górze załączam linki do ostatniego questa starego i nowego chaina. 

W nowym widnieje napis: Added in patch 4.3.0.

Natomiast w starym można znaleźć ten oto komentarz:

As of Patch 4.2.0(28/06/11), players will no longer need to do this pre-quest to be able to get into the Heroic version of Magisters' Terrace.

plus notka z wowheada:

This quest was marked obsolete by Blizzard and cannot be obtained or completed.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/572

**Comment by Glare** [comment]
Jako, że komentarz nie daje bumpa a nie mam pewności czy ktoś to tam przeczyta:

Bump, search option fooled me -.-

Is there an option to open the instance without scripting the whole new quest chain inside dungeon? I assume that doing both would require much more time and I think it would be better than waiting for someone to actually script those quests.
