### ISSUE TITLE
[PL] [Talent] [Death Knight] Chillblains

### ISSUE THREAD

**Issue by Mietla122** [Atlantiss/BugTracker#1277]
odnowienie Frost Fever powinno nakladac chillblains na 10 sec, a tego nie robi. Odnowic slow mozna dopiero jak zejdzie poprzedni

**Comment by Varchord** [comment]
wowhead links

**Comment by Mietla122** [comment]
http://www.wowhead.com/spell=50041/chilblains

**Comment by mrkariox** [comment]
Kazde odnowienie Frost Fever powinno nakladac slowa na 10 sec, a tego nie robi. Odnowic slow mozna dopiero jak zejdzie poprzedni.

**Comment by Varchord** [comment]
To nie jest bug z howling blast tylko z chillblains

**Comment by Bildo** [comment]
zdeedytuj 1 post

**Comment by Varchord** [comment]
Możesz do tytułu dodać, że to talent jest

**Comment by Varchord** [comment]
Bug jak ten, moze w czymś to pomoże
https://github.com/Atlantiss/BugTracker/issues/181

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
