### ISSUE TITLE
[EN] [Guild] Throne of the Four Winds Guild Run

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#1279]
The Guild Achievement  for Throne of the Four Winds did not work for our guild and we killed both bosses today please fix our members want the mount badly. ( The Nemesis Order )

**Comment by Blasiren** [comment]
You also can't earn bastion of twilight guild run

**Comment by Bud1980** [comment]
not working still

**Comment by Bud1980** [comment]
This need's to be reopened
