### ISSUE TITLE
[EN] [QUEST] Gluttonous Lurkers

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#1280]
You don't get the rats in your inventory when picking them.

WoWhead:
QUEST: http://www.wowhead.com/quest=12527
ITEM: http://www.wowhead.com/item=38380
NPC: http://www.wowhead.com/npc=28202

Video:
https://www.youtube.com/watch?v=4W8unhFVO4g

**Comment by Daknyas** [comment]
Excuse me Bildo, this is still bugged.

**Comment by Bildo** [comment]
check after update and write if it's work or not because
