### ISSUE TITLE
[PL][Guild]Guild Finder

### ISSUE THREAD

**Issue by Hosampsich** [Atlantiss/BugTracker#1281]
----

Guild Finder dziła, lecz każdy off serwera, nawet ten najkrószy,
powoduje kasacje ogłoszenia gildii i trzeba je na nowo uzupełniać.

----
http://us.battle.net/wow/en/blog/2657799

----

**Comment by Dralo** [comment]
przestaje dzialac po kazdym dc

**Comment by krecik88** [comment]
Mogę prosić o więcej info? Czy kasuje się tylko na liście dostepnych aplikacji, czy kasuja sie teksty od ogloszen? próbuję odtworzyć ewentualne błędy lokalnie, ale póki co wszystko poprawie działa.

**Comment by Hosampsich** [comment]
Kasują się listy ogłoszeń gildyjnych, po każdym dc lista ogłoszeń gildyjnych jest pusta i trzeba na nowo ją uzupełniać żeby była widoczna.
-----
Co do złożonych aplikacji przez graczy chcących dołączyć do gildii to nie mam pewności - nie sprawdzałem dokładnie...

**Comment by krecik88** [comment]
Fixed in 4232
