### ISSUE TITLE
[EN] [Dungeon-Classic] Sunken Temple

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1285]
(Not sure if I should do one big or several small bug reports... I'll try Varchord's bug report format:)

The Sunken Temple: http://www.wowhead.com/zone=1477

## [Dreamscythe](http://www.wowhead.com/npc=5721#comments) & [Weaver](http://www.wowwiki.com/Weaver)
* Should fly around the central chamber when Jammal'an the Prophet is defeated. At the moment Dreamscythe ~~is missing~~ (edit:) sits on a balcony where we didn't see him the whole run and Weaver sits on the floor at the start of the dungeon (not only after Jammal'an is dead). [pic](http://i.imgur.com/DYweJgB.jpg)
* (edit:) Now we even had 2 Dreamscythes and 2 Weavers: The first pair we didn't kill because the server crashed and we already had Weaver killed once. After defeating Jammal'an, another pair of Dreamscythe&Weaver spawned. [pic](http://i.imgur.com/wHYMAp7.jpg)
* pet & mob pathing is a bit problematic around the center circle: the circle is slightly raised and pets/mobs don't like to cross that.

## [Hazzas](http://www.wowhead.com/npc=5722) & [Morphaz](http://www.wowhead.com/npc=5719)
* Should patrol the room they're in, not be stationary. Weaver, Hazzas and Morphaz also all seemed to drop plenty of loot... if I remember correctly, only one of them drops loot (but according to their wowhead table, they can all drop blue items... strange).

## [Shade of Eranikus](http://www.wowhead.com/npc=5709)
* Should not be attackable unless you've killed Jammal'an first [source](http://www.wowwiki.com/Shade_of_Eranikus)
* Should call the other dragonkin for help when you attack him (which is why the goup should have cleared the central area first), but right now he doesn't call them

## [Jammal'an the Prophet](http://www.wowhead.com/npc=5710)
* Repeats his sound emote until you kill him [pic](http://i.imgur.com/UOa08YJ.jpg)
* spawns an Earthgrab Totem which behaves like a normal mob [pic](http://i.imgur.com/JNwxwEx.jpg), same problem like in Razorfen Kraul, issue [#1109](https://github.com/Atlantiss/BugTracker/issues/1109) 
* the trash mobs in front of him sometimes spawn an [Atal'ai Deathwalker's Spirit](http://www.wowhead.com/npc=8317#comments). These behave like normal mobs at the moment, but they should be slow, immune to everything and despawn after some seconds, so that your group has to kite them.

## [Avatar of Hakkar](http://www.wowhead.com/npc=8443)
* If I recall correctly, the doors close when you start the event and there are more enemies spawning until you can attack Hakkar
* Hakkar spams emotes. Also last run he spawned twice and dropped loot twice. [pic](http://i.imgur.com/1IHDK6H.jpg)

**Comment by Varchord** [comment]
Atal'ai Deathwalker's Spirit shouldn't even be targetable

**Comment by Bildo** [comment]
yes they should

**Comment by Varchord** [comment]
If nothing had changed in this dungeon between cata and wod they shouldn't
I've done this on retail, desperately tried to taunt them off and couldn't even target them

**Comment by Bildo** [comment]
https://www.youtube.com/watch?v=IiMioW7ibIc 13:56

**Comment by Varchord** [comment]
Then something must've changed
You know you can copy to specific time? ^^

**Comment by Bildo** [comment]
yea i know

**Comment by Bildo** [comment]
fixed in rev 4231
