### ISSUE TITLE
Race changed randomly in-game.

### ISSUE THREAD

**Issue by Bearbigelow** [Atlantiss/BugTracker#1288]
My level 8 blood elf paladin turned into a gnome in a green santa suit. This happened just a little bit after fininshing the swift discipline quest. I hope this helps :)

**Comment by Varchord** [comment]
There are machines during Feast of Winter Veil that can turn you into a gnome for an hour if you walk past them

**Comment by Bearbigelow** [comment]
Kk sorry about the false report.
