### ISSUE TITLE
[EN][QUEST] Let's Do Lunch: Orgrimmar 

### ISSUE THREAD

**Issue by pampidoo** [Atlantiss/BugTracker#1289]
This achievement don't works fine. One of the 5 daily quests don't works correctly, it's "Stealing From Our Own". The quest doesn't call for the achievement. Screenshot below proves it:
http://i.imgur.com/OyvK6h0.jpg

**Comment by Varchord** [comment]
title

**Comment by pampidoo** [comment]
http://www.wowhead.com/quest=26233

**Comment by pampidoo** [comment]
http://www.wowhead.com/achievement=5475

**Comment by Qwers** [comment]
confirm

**Comment by Bildo** [comment]
duplicate
