### ISSUE TITLE
[EN][NPC] The Cape of Stranglethorn - Airwyn Bantamflax 

### ISSUE THREAD

**Issue by Hacker--x** [Atlantiss/BugTracker#1290]
The NPC Airwyn Bantamflax is hostile for horde in the Cape of Stranglethorn (Booty Bay - in the region of 43, 73 [second floor]) and its level is unknown to the character and retaliating will cause the bruisers to attack you. Makes your experience in Booty bay quite unpleasant

**Comment by Bildo** [comment]
wowhead links

**Comment by Hacker--x** [comment]
No idea its a npc let me go look

**Comment by Hacker--x** [comment]
http://www.wowhead.com/npc=44112/airwyn-bantamflax

**Comment by Bildo** [comment]
fixed in rev 4240
