### ISSUE TITLE
[EN][Social] add to friends, send mail, special characters

### ISSUE THREAD

**Issue by kronus7** [Atlantiss/BugTracker#1293]
When I'm trying to send a mail to my alt named Khâleesi I get an error 'target is unfriendly'. I'm a troll druid and my alt is a blood elf priest.

Update: my friend tried adding me to friends and all he got was red text saying 'Player is not the same faction'. Thus I believe due to use of special characters in character name, the game thinks it belongs to the other faction.

Note: I'm not writing the â myself, I choose my alt from the list, and also my friends tried to add me when targeting me and clicking Add to friends and also by copying my name from chat/whisper to the friend name box

**Comment by sujezz** [comment]
That's fine, most of ppl can't write such letters and thus won't be able to mail or whisper to such character. Now feel our pain :)

Probably an intentional change so I suggest you to make regular name (a-z) for your character.

**Comment by kronus7** [comment]
my intention was to avoid spending tons of my time to come up with a name I like, so since it was taken, I used a different 'a' character :) whispers and mails are fine if you shift-click on my name in chat, it works on global so I believe it IS a bug on Atlantiss.

**Comment by Bildo** [comment]
change title

**Comment by Emtec** [comment]
duplicate: https://github.com/Atlantiss/BugTracker/issues/1530
