### ISSUE TITLE
[PL][Class][Druid] Moonfire

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1297]
https://www.forgottenlands.eu/showthread.php/8324-Formule-Spell-Balance
http://www.wowhead.com/spell=8921

Brakuje ok 200 mg spellowi Moonfire z Doty jak i z Direct Damage bez eclipsa jak i z eclipsem (+53% dmg arcane[lunar])

![image](https://cloud.githubusercontent.com/assets/8093039/5613049/951783c6-94de-11e4-9fbb-ce6218c271df.png)

**Comment by InformatorPE** [comment]
update
niektorym excell przeszkadzal to przesymulowalem damage w programie SimultionCraft z talentami/itemami/statami itd z atlantissa i wedlug symulacji moonfire powinien bic:
http://zapodaj.net/0efa21eab9731.jpg.html

**Comment by Morderczyk** [comment]
a zmieniles dmg z broni bo simcraft sie bugowal i naliczal bronie z nie tego patcha czyt. podwzyszony dps broni = podwyzszony dps z moonfire

**Comment by InformatorPE** [comment]
main_hand=incineratus,heroic=1,ilevel=372,quality=epic,stats=165int_248sta_110mastery_110haste_2207sp,reforge=mastery_spi,enchant=power_torrent,weapon=dagger_1.80speed_328min_611max,suffix=0

**Comment by Varchord** [comment]
Umm. Morderczyk, ale co ma dps broni do moonfire? Toż to spell. Jedyny stat, który modyfikuje jego dmg na tick to spellpower. nie zadaje w końcu % weapon damage ^^

**Comment by InformatorPE** [comment]
Po globalnym restarcie talentow damage moonfire jest taki sam jak w bialej tabelce/ czyli taki jak byl zglaszany, nie bije tyle ile powinien bic.

**Comment by Morderczyk** [comment]
Varchord prawda, nie jestem przyzwyczajony do casterow i zapomnialem ze dmg broni wam nie zwieksza dmg spelli moj blad

**Comment by Varchord** [comment]
Tak tak, pewnie salg z savkiem i zakiem biegają z mackami 2h  i staffami żeby wzmocnić spelle od weapon dmg :P Już ja znam te techniki bugowania ^^

**Comment by Jenovas** [comment]
Tutaj koledze chodziło o to co Kejmil kiedyś zgłaszał - Simcraft w którejś wersji (tej od Shadoowa) bierze już staty z Mopa, a na Mopie bronie te same dawały dużo więcej inta/spellpower i należy sprawdzać czy dobrze wrzuciło ich staty i czy staty z simcrafta (tam na dole jest tabelka z int/spellpower) zgadza się z tym co mamy w grze.

**Comment by InformatorPE** [comment]
# Gear Summary
# gear_strength=20
# gear_agility=20
# gear_stamina=5739
# gear_intellect=4793
# gear_spirit=1624
# gear_spell_power=2207
# gear_hit_rating=143
# gear_crit_rating=563
# gear_haste_rating=2013
# gear_mastery_rating=1162
# gear_armor=10857
# meta_gem=burning_shadowspirit
# tier11_2pc_caster=1
# tier11_4pc_caster=1
# main_hand=incineratus,heroic=1,weapon=dagger_1.80speed_328min_611max,enchant=power_torrent

zgadza sie z tym co mam w gearze i co bylo w symulacji

**Comment by InformatorPE** [comment]
wersja simcrafta Patch 4.3.3 Release 2
https://code.google.com/p/simulationcraft/downloads/detail?name=simc-433-2-win32.zip&can=1&q=
