### ISSUE TITLE
[PL][H.Pet][Talent][Wild Hunt] A reason for pets' big damage.

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#1298]
Zgłoszenie było, jeden z devów próbował naprawiać, ale okazuje się że problem dalej wystepuje. Jest to oczywiście jedna z przyczyn(oprócz stackoawnia buffów) sporego dmgu petów w PvE.
Odsyłam do zamkniętego złoszenia. https://github.com/Atlantiss/BugTracker/issues/684

**Comment by Wolffenstein** [comment]
Fixed in rev 4209.
