### ISSUE TITLE
(PL) Skałki w Nagrand ( Rich Adamantite Deposit )

### ISSUE THREAD

**Issue by Toxicplayer** [Atlantiss/BugTracker#1299]
Pojedyńcze skałki są pobugowane, nie da sie ich wykopać http://www.wowhead.com/object=181569/rich-adamantite-deposit

**Comment by Bildo** [comment]
zmien tytul

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
