### ISSUE TITLE
[PL][Talent][Spell][Rogue] Mutilate

### ISSUE THREAD

**Issue by bijtankga** [Atlantiss/BugTracker#130]
Talent/Spell: Mutilate
Klasa: Rogue
Drzewko: Assasination
Linki:
http://www.wowhead.com/spell=1329
http://cata.openwow.com/spell=1329
1. Miss/dodge (przypuszczalnie parry) jest przeliczane dla "calego" skila na raz, tzw zawsze sie trafia obiema lub zadna reka. Z tego co mi wiadomo powinno byc przeliczane osobno dla kazdej reki (moge sie mylic, a nie moge znalexc informacji w necie)
2. Dla assa bez talentow z testow wszlo ze wspolczynnik AP wynosi 0,261 gdzie DrDmg wskazuje wartosc 0,243 (wartosci dmgu z addonu i z gry znaczie sie roznia).
3. Zdarza sie ze wyprowadzany jest atak tylko z jednej reki (brak wpisu w combat logu o drugiej; najczesciej brakuje chyba mh)

**Comment by Wolffenstein** [comment]
1. W dbc jest ustawione, że ten główny spell triggeruje atak z MH i OH, więc jeżeli zmissuje to naturalnie oba ataki zmissują. Raczej zamierzone.

2. DrDmg na 4.3.4 ma często jakieś dziwne wartości. Ja bym mu nie ufał.

**Comment by nerv234** [comment]
Na poprzednich patchach też mi się wydawało np. że miał dziwne wartości, jednak po bardzo dogłębnej analizie okazało się że były dobre wartości na dr damage, sprawdzę i przeanalizuję.

**Comment by nerv234** [comment]
Co do coefa to drdamage wrzuca inny w zależności od tego jakie bronie mamy i czy obie założone i od speeda. Na razie ciężko u mnie z czasem, na weekendzie zrobie dokładniejsze testy.

**Comment by nerv234** [comment]
Ok coefa przy wyliczeniach się nie powinno brać pod uwagę jeśli chodzi o ten spell(zakłądając że dobrze coef wpływa na dmg broni). Bo wzór na dmg spella wynosi dmg broni * 2.33+561(wg. tooltipa z gry).

Próbuje wyprowadzić wzór na mutilate...
1.3 oportunity
1.2 Assasins resolve
233% dmg broni to podstawowe 179*1,3. (tutaj A..R.. zostało zaaplikowane bezpośrednio już do broni.
Dodatkowe 360dmg * 1.3 *1,2=561.

Więc wzór na mutilate main hand powinien wyglądać mniej więcej tak: 
(w.dmg*1.2)*2.33+561 w zakładce postaci pokazuje jeszcze przed pomnożeniem o 20%:)

Wzór na OH powinien wynosić 
(w.dmg*1.2)*2.33+561 tak samo bo w zakładce już pomniejszone jest o połowe dmg oh.

Moje testy na kukiełce w orgri z czaszką(ta po prawo z 3 bossowych):
założyłem 2x Dirge (1-3dmg)
Dmg broni:
MH: 945-947(*1.2)
OH: 472-474(*1.2)

DMG non crit zadane:
2241-2243 MH
1308-1308 OH

Wg. wzoru powinno być(bez armoru):
MH: 3203-3208,8
OH: 1880,7-1886.3

Z pomniejszeniem o armor(33% bo wolf mówił że kukły mają 33% armora te z levelem bosa)
MH: 2146-2150
OH: 1260-1264
Tu zachodzi nieścisłość pewna i z moich cyferek wychodzi 30-31% redukcji z armoru na kukiełce.


Natomiast jeszcze raz chciałbym przypomnieć że coef jest wykorzystywany do liczenia dmg z broni tylko, dlatego przy różnych broniach jest inny w drdamage i nie powinno się brać go pod uwagę.
