### ISSUE TITLE
[PL][Rogue] Haste i regen energii.

### ISSUE THREAD

**Issue by sujezz** [Atlantiss/BugTracker#1302]
Obecnie haste nie wpływa na przyrost energii. Vitality(talent w combat) zwiększa z 10/s do 12.5/s i na tym koniec. Nawet najeżdżając myszką na haste wyświetla nam się "Increases attack speed and energy regeneration". Dodatkowo w internecie można znaleźć na wielu stronach takie coś:
"As a rogue, most of your abilities need Energy to be used. Your Energy bar has a capacity of 100 Energy and refills at a rate of 10 Energy per second. Your energy regeneration is increased by:

    your melee haste (Haste Rating + haste-enhancing buffs);"

**Comment by Varchord** [comment]
W character sheet masz napisane cały czas 10/s czy rzeczywiście regeneruje caly czas 10/s?
Character sheet ejst zbugowane i zawsze bd pokazywać 10

**Comment by sujezz** [comment]
w character shhet po zmianie speca na combat zmienia się z 10/s do 12.5/s, haste nie wpływa na regen energii albo tego nie wyświetla.

**Comment by lastkiss** [comment]
faktycznie nie wpływa u nas haste na regen energii u rogue

**Comment by sujezz** [comment]
To sporo zaniża dps, haste jest a raczej powinien być drugim najważniejszym statem dla combat rogala. Pierwszy raz dzisiaj grałem od dawna i na rhc zauważyłem, że strasznie wolno mi energia rośnie. Gdzie na globalu na 4.3.4 ledwo wyrabiałem se spamowaniem SS i RS żeby nie dobić 100 energii, mogłem nawet biegać z włączonym Blade Flurry i nie wpływało to na dps na single target. Za to tutaj często czekałem na energię po kilka sekund.

**Comment by Morderczyk** [comment]
Jest tak tylko z rogalem czy z focusem hunta tak samo?

**Comment by Wolffenstein** [comment]
Fixed in rev 4214.

**Comment by Varchord** [comment]
Fix tyczy się też druida?

**Comment by Jenovas** [comment]
Haste wpływał normalnie na regen energii, były robione testy, dawałem sobie 200% haste i można było spamować czym się chciało dowoli, został poprawiony bug wizualny i w karcie postaci powinno już rosnąć też.

**Comment by Varchord** [comment]
Myślałem, że się znów coś zpsuło czy cuś

**Comment by Varchord** [comment]
Jak uważasz, ze nadal nie działą to stwórz nowy report. Devi z zasady nie zaglądają do zamkniętych tematów ani ich na powrót nie otwierają
