### ISSUE TITLE
 [PL] [Talent] [Rogue] Bandit's Guile

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#1303]
Pomimo 3 pkt w w/w talencie Buff nie odświeża się z każdym SInisterem czy Revealingiem, a powinien--> http://cata.openwow.com/spell=84654

**Comment by kadi2** [comment]
Rzeczywiscie tooltip talentu nie jest zbyt zrozumialy, musisz uderzyc z RS/SS 4 razy, na tym samym targecie aby otrzymac buffa Focused Insight. Prawdopodobnie dziala poprawnie.

**Comment by Wolffenstein** [comment]
Nie wiem czy nie chodzi o to, że powinno odświeżać czas trwania buffa.

**Comment by Reversion** [comment]
Mój błąd, źle zinterpretowałem tooltip jak kolega wyżej napisał. Działa prawidłow odświeża stak na co 4tym ss/rs. 
"This has been figured out over at Elitistjerks. it takes 4 uses of either Sinister Strike or Revealing Strike (Any combination of the two) to make it go up one level." 
"I wouldn't say people are confused about how the tooltip reads at all but rather that blizz worded it very poorly to the point it is misleading. The first time I read it I thought it meant I would get the buff after the first SS/RS use, which is in fact wrong. Imo it should read something more like:

"For every combination of 4 Sinister Strike/Revealing Strike you have a 100% chance to grant you an evolving insight into an opponent's defenses, increasing damage to that target by 10% up to 30% max. Opponents can adapt over time, negating this benefit for a time, and Striking a different opponent will begin the cycle anew.". 

Na chwile obecną działa bez zarzutu.

**Comment by Wolffenstein** [comment]
:)
