### ISSUE TITLE
[EN] [Glyph] [Druid] Glyph of Regrowth

### ISSUE THREAD

**Issue by Dujooo** [Atlantiss/BugTracker#1305]
Your Regrowth heal-over-time will automatically refresh its duration on targets at or below 50% health. I tried to do this with my friend in many varieties, and in no situation did the heal-over-time refresh. Maybe i misunderstood it, but i don't believe that's the case :)

**Comment by Wolffenstein** [comment]
When should it refresh? When it ticks?

**Comment by Varchord** [comment]
http://cata.openwow.com/spell=54743

**Comment by Wolffenstein** [comment]
I'm pretty sure it refreshes when it ticks. Otherwise it would have no sense.

**Comment by Wolffenstein** [comment]
Or it refreshes when the duration ends. It's the other option.

**Comment by Wolffenstein** [comment]
Fixed in rev 4210.

**Comment by Dujooo** [comment]
Once again, I don't really see how this is fixed, i can see 2 options, when the target already has less than 50% hp when the heal-over-time effect ends, it should refresh itself, or when target has over 50%, but reaches 50% or less while the heal-over-time is active, either way it should refresh itself when it finishes, otherwise I dont see any changes in the ticking or anything, it is just the same....
