### ISSUE TITLE
[PL][Talent][Warrior] Titan's Grip

### ISSUE THREAD

**Issue by Szarky** [Atlantiss/BugTracker#1306]
Titan's Grip obniza damage z offhandu o 50% - w talencie ani na wowheadzie nie ma wzmianki o obniżaniu damage z off
http://www.wowhead.com/spell=46917

**Comment by tnarf** [comment]
http://www.wowwiki.com/Dual_wield
W 3. akapicie mozesz przeczytac ze off-hand w przypadku dual wielda ma obnizony dmg o polowe.
Wiec jest chyba ok.

**Comment by Szarky** [comment]
W summaries dotyczace dual wielda jest nawet +25% dmg do offhand
http://kawinski.net/szarky/share/2015-01-05_23-56-12.png
ponadto w porownaniu do WotLK'a nie ma właśnie wzmianki o obniżaniu DMG
http://kawinski.net/szarky/share/2015-01-05_23-58-52.png
więc powinno być albo 125% dmg offhandu (w co wątpię), 100% lub obniżony tylko o 25% do 75% 
a nie do 50%

**Comment by tnarf** [comment]
Bo to nie talent obniza tylko sama mechanika dual wielda.
Z tego co mi wiadomo powinen byc tak jak zawsze obnizony do 0,5 a potem przemnozone o te 0,25 tzw
1 * 0,5 * 1,25 = 0,625

slaby dowod: w komentarzach na wowhedzie do dual wield speca wersji wotlkowej jest napisane ze multiplicative
http://www.wowhead.com/spell=23588#comments:id=1017452
