### ISSUE TITLE
[PL][Spell][Warrior] Whrilwind

### ISSUE THREAD

**Issue by Szarky** [Atlantiss/BugTracker#1307]
http://www.wowhead.com/spell=1680/whirlwind
Na wowheadzie jest opisane "po nowemu" ale spell zadaje damage tylko z jednej broni, a powinien z obu
screenshot tooltipu: http://kawinski.net/szarky/share/2015-01-05_18-48-11.png

**Comment by Wolffenstein** [comment]
Fixed in rev 4211.
