### ISSUE TITLE
[PL][Raid-Cata] Throne of the Four Winds

### ISSUE THREAD

**Issue by Hosampsich** [Atlantiss/BugTracker#1308]
Pierwszy przeciwnik The Conclave of Wind ( 3 dżiny ), w momencie gdy ma już zaliczyć zgon, zaczyna się mały lag a po 3 sekundach mamy DC servera, były wykonane 2 podejscia do bosa każde z tym samym rezultatem. Dziło się tak pomiędzy godzina 16:30 a 18:00.

**Comment by Dralo** [comment]
ubicie powoduje dc servera

**Comment by InformatorPE** [comment]
na hc nie powoduje dc

**Comment by Dziara** [comment]
Parę godzin temu biliśmy na normalu i żadnego dc/crasha nie było.

**Comment by Varchord** [comment]
PIERWSZY RAZ WIDZE ARCANE MAGA
Muszę się przyjrzec temu zagrożonemu gatunkowi :P

**Comment by Hosampsich** [comment]
17:28 - crash servera ( The Conclave of Wind ) bite w innej kolejność ..... i dalej crash

**Comment by mrkariox** [comment]
Przypadek to nie jest to ze crashuje, przypadek to to ze NIE crashuje. Przewaznie jest crash i to wymaga poprawy.

**Comment by Jenovas** [comment]
Wiemy o crashu i jesteśmy w trakcie naprawy.

**Comment by qubuslabadz** [comment]
Crashe już nie występuja.
