### ISSUE TITLE
[PL][Spell][Mage] Pyroblast! (DoT)

### ISSUE THREAD

**Issue by adryjan** [Atlantiss/BugTracker#1309]
Castując ''Pyroblast!'' czyli instant z Hot Streak zastępujemy DoTy wszystkich magów z wycastowanego ręcznie Pyroblasta. Dodatkowo gdy na targecie mamy DoT z instant Pyroblasta (może być ich kilka w jednym momencie zależy od ilości magów) to castując ręcznie Pyroblasta ściągamy wszyskie instant Pyroblast DoT.

Pyroblast: http://www.wowhead.com/spell=11366/pyroblast
Pyroblast!: http://www.wowhead.com/spell=48108#see-also-other

Sprawdzone przed chwilą na Dummy, 3 magów fire.

Generalnie działa jak powinno tylko powinno dotyczyć twoich castów żeby zapobiec dwóm dotom z Pyro, nie powinno mieć jednak żadnego wpływu na doty innych magów tylko to należy poprawić.

**Comment by Wolffenstein** [comment]
Fixed in rev 4235.
