### ISSUE TITLE
[PL][Instance - Classic] Wailing Caverns

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#131]
The maze section has been removed to make the overall dungeon more accessible and quicker to complete. Nearby creatures and bosses have been adjusted to compensate.

http://www.wowhead.com/npc=3670 - przesunięty
http://www.wowhead.com/npc=3674 - przesunięty

dochodzi do tego całkowite przesunięcie bądź wywalenie naprawdę sporej ilości spawnów ze względu na ukrócenie dungeonu, wrzucam zbiorcze linki.

http://www.wowhead.com/zone=718#npcs
http://www.wowhead.com/zone=718#objects

**Comment by Hacker--x** [comment]
Just tried, pythas is inaccessable

**Comment by xtul** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 4202.
