### ISSUE TITLE
[PL][Warrior][Fury] Dual Wield Specialization

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1310]
http://cata.openwow.com/spell=23588

Nie zwiększa obrażeń z offhandu

**Comment by Varchord** [comment]
Nic dziwnego, że furas taka fujara teraz jest jak każdy atak z użyciem offhandu zadaje mniej o te 25% obrażeń

**Comment by tnarf** [comment]
cel: kukla z czacha
talenty: "puste" fury
stance: defensive
bufy/debufy: brak
ap: 7165
wepon: Double Axe (19-36; 2,5 speed)
1 x weapon avg auto atack dmg: 1298 (1209-1223)
2 x weapon avg auto atack dmg: 902 (540-1223)
2x weapon min auto atack dmg - dual wield specialization (/1,25): 432
j/w - redukcja off handa: 864
j/w + precision (x 1,4): 1209,6
"Uzyskany" tymi obliczeniami dolny dmg off-handa zgadza sie z dolnym dmg mh wiec.

Tak wiec wg mnie "Dual Wield Specialization" dziala dobrze.
Natomiast "Precision" niekoniecznie; nie wiem czy oh powinen mu podlegac.

**Comment by NONLIFE** [comment]
@Varchord Masz jakieś cyferki czy coś ze nie zwiększa dmg?

**Comment by Varchord** [comment]
Testowałem, już cyferek nie mam, ale prosiłem w innym poście żeby po mnie posprawdzać bo mi się to nie zgadza.
Poprzednie zamknąłem bo wychodziło na to, że dummy mają redukcje dmg fizycznego. To zostawiłem bo jeszcze nie mam pewności czy to działa czy jest zepsute, myśle jak definitywnie sprawdzić

**Comment by NONLIFE** [comment]
umiesciłem teraz problem z talentem Enrage co daje 13% dmg wiecej mozesz sprawdzic ?

**Comment by Varchord** [comment]
Teraz to mam raid :P  W niedziele moze. A Enrage bazowo daje 10%, modyfikowane przez mastery ^^

**Comment by NONLIFE** [comment]
@Varchord zgadzam się za mały dmg ;d
