### ISSUE TITLE
[PL][Warrior][Fury] Bloodthirst

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1311]
http://www.wowhead.com/spell=23881#changelog

Bloodthirst zadaje za małe obrażenia. Prawdopodobnie wina skalowania z AP.
Powinien on bić za 80% naszego attack power

**Comment by Varchord** [comment]
Sprawdzane na defensive stance bez talentów

**Comment by tnarf** [comment]
cel: kukla z czacha
talenty: "puste" fury
stance: berserker
bufy/debufy: brak
ap: 7165
wepon: Double Axe (19-36; 2,5 speed)
redukcja armoru (wyzaczona w innym watku autora problemu):0,3315733897
avg BT dmg: 4261 (4261-4261)
BT dmg wg AP: 5732
BT dmg wg AP - redukcja armoru: 3831,4213305174
BT dmg wg AP - redukcja armoru + stance: 4214,5634635692
roznica: 46,4365364308
Przyjmujac ze roznica miesci sie jeszcze w bledzie wyznaczenia armoru wg mnie dziala dobrze.
Jesli przyjac ze nie miesci sie to bije kapke za duzo, a nie za malo.

**Comment by Varchord** [comment]
Kukły nie mają armoru. Wolff gdzieś mi to wcześniej pisał

Przy 9027 AP, w def stance, na czystym fury bije u mnie po 5110, powinno 7221. nawet jeśli założymy, że armor jest na kukłach to wychodzi ~5560 dmg czyli bije o 450 za mało

**Comment by Varchord** [comment]
Gupi armor. Ja byłem przekonany, że kukły nie mają żadnej redukcji tego typu :X W dodatkuliczyłem z 0,77 zamaist 0,67 teraz xd
