### ISSUE TITLE
[PL][Quest][Mount Hyjal] Vigilance on Wings

### ISSUE THREAD

**Issue by Qwers** [Atlantiss/BugTracker#1313]
http://www.wowhead.com/quest=29177
http://www.wowhead.com/npc=40578
http://www.wowhead.com/achievement=5860

NPC Farden Talonshrike nie daje daily q Vigilance on Wings co uniemożliwia zrobienie achievementu The 'Unbeatable?' Pterodactyl: BEATEN.

**Comment by Asavel** [comment]
Zadne nowe questy nie byly dodawane a ten zostal dodany w 4.1 pewnie wraz z wejsciem oficjala i contentu 4.1 bedzie

**Comment by monibu** [comment]
Rzekomo problem był naprawiony w rev 4130, to może byście odblokowali ten quest?

**Comment by Romarez** [comment]
Nadal brak daily q, co powoduje ze nie mozna zrobic achieva The 'Unbeatable?' Pterodactyl: BEATEN

**Comment by Aival94** [comment]
Bump.Still daily quest is missing.

**Comment by HUMBOL** [comment]
BUMP!

**Comment by vermik** [comment]
BUMP!, Still don't give quest.
