### ISSUE TITLE
[PL][Warrior] Heroic Strike

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1314]
http://www.wowhead.com/spell=78#changelog

Za mało bije. Powinien 60% naszego AP

**Comment by Varchord** [comment]
Sprawdzane na defensive stance bez talentów

**Comment by tnarf** [comment]
cel: kukla z czacha
talenty: prot (brak bonusow do hs'a)
stance: defensive
bufy/debufy: brak
ap: 8719
wepon: zin'rokh
avg mele hit: 3165 (2850-3443)
avg mele hit wg okna postaci: 4735 (4261-5209)
wyznaczona redukcja armoru celu: 0,3315733897
avg HS dmg: 3485 (3485-3485)
HS dmg wg AP: 5231,4
HS dmg wg AP - redukcja armoru: 3496,806969377
roznica: -11,806969377
Na moje miesci sie w bledzie wyznaczenia redukcji armoru

**Comment by Varchord** [comment]
Kukły nie mają armoru. Wolff gdzieś mi to wcześniej pisał

**Comment by Varchord** [comment]
Licze tylko i zamykam. Ah ten wolff mnie w błąd wprowadził xD
