### ISSUE TITLE
[PL][Warrior] Cleave

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1315]
http://cata.openwow.com/spell=845

Bije za mało. Powinien 45% naszego AP na target.

PS.
Niech ktoś to cholera po mnie posprawdza bo ja nie wiem czy ten warek taki pobugowany na minus czy ja coś źle rozumuje/licze

**Comment by Varchord** [comment]
Sprawdzane na defensive stance bez talentów

**Comment by tnarf** [comment]
cel: kukla z czacha
talenty: prot +6% z thunderstruck
stance: defensive
bufy/debufy: brak
ap: 8719
wepon: zin'rokh
avg mele hit: 3165 (2850-3443)
avg mele hit wg okna postaci: 4735 (4261-5209)
wyznaczona redukcja armoru celu: 0,3315733897
avg cleave dmg: 2769 (2769-2769)
cleave dmg wg AP: 3923,55
cleave dmg wg AP+talent: 4158,963
cleave dmg wg AP+talent - redukcja armoru: 2779,9615406547
roznica: -10,9615406547
Na moje miesci sie w bledzie wyznaczenia redukcji armoru

**Comment by Varchord** [comment]
Kukły nie mają armoru. Wolff gdzieś mi to wcześniej pisał

**Comment by tnarf** [comment]
moze armoru nei maja ale maja redukcje dzialajaca identycznie jak redukcja armora
i maily to zawsze

**Comment by Varchord** [comment]
Czyste fury, def stance

9027 AP
dmg wdlg ap 4062
dmg wdlg ap z amorem 3127
dmg rzeczywiście zadawany 2705

**Comment by Varchord** [comment]
Cholera czekaj, źle armora liczyłem. Wychodziłoby dobrze
