### ISSUE TITLE
[PL][Shaman] Healing Rain

### ISSUE THREAD

**Issue by astale** [Atlantiss/BugTracker#1316]
Przy użyciu skilla Healing Rain http://cata.openwow.com/spell=73920 w resto, dostaje się spam "Target not in light of sight" jeżeli jakiś target jest poza nim (ale leczyć leczy)... O ile też nie miałem jakiegoś pecha to z takiego Healing Raina na 3 targetach na pełnych 50castach nie złapało ani razu buffa  Ancestral Healing ( http://cata.openwow.com/spell=16235 ) ani Earthlivinga ( http://cata.openwow.com/spell=51945 )

**Comment by kadi2** [comment]
Jak sie zalogowalem na swojego szamana, to moj Earthliving nie dodawal bonusa do leczenia, oraz rowniez nie procnal ani razu. Po nalozeniu nowego Earthlivinga wszystko wrocilo do normy.

**Comment by Wolffenstein** [comment]
Prawdopodobnie fixed w revie 4213. Jak nie zadziała to proszę o nowe zgłoszenie.

**Comment by astale** [comment]
Działa już w porządku :)
