### ISSUE TITLE
[PL][Object]Meeting Stone

### ISSUE THREAD

**Issue by andrzeju56** [Atlantiss/BugTracker#1319]
Meeting Stone summonuje najbliższą postać stojącą tuż obok zamiast po prostu target . Znajomi też nie  mogli się summać wzajemnie . Po wyłączeniu wszystkich addonow problem dalej występował.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/837

Niemalże dubel. Proponuje devom te issue jakoś połączyć iz mienić na samą mechanike summa

**Comment by cosminush** [comment]
This stone, afect all, summon char what clicked not target of summoner. It's all summ stone same problem.
