### ISSUE TITLE
[PL][Talent][Druid] Lunar Shower

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#132]
http://cata.openwow.com/spell=81192
UPDATE 07.04.2015 rev 4392
* Lunar Shower doesn't generate energy when specced only 1/3. (2/3 and 3/3 working as intended)

UPDATE 12.12.2014 rev 4155

* Osiągając 100 lunar lub solar energii za pomocą Lunar Shower nie aktywuje się Eclipse, dopiero następny spell generujący energię to zrobi. Jeśli to będzie Moonfire/Sunfire to ustawi nas w eclipse na 92 energii, jeśli będzie to starfire/wrath/starsurge ustawi nas na 100 energii w eclipse.

Miałem także sytuacje, kiedy moonfire wyszedłem z lunar eclipse z 4 energi w stronę solar, a eclipse był aktywny dla następnego spella. Nie byłem w stanie tego odtworzyć

**Comment by Milton3450** [comment]
U checked if it generates 8 energy with 1/3 in Lunar Shower?

**Comment by Varchord** [comment]
Mate. I will be home Tuesday afternoon

**Comment by Varchord** [comment]
UPDATE 07.04.2015 rev 4392
* Lunar Shower doesn't generate energy when specced only 1/3.

**Comment by Jenovas** [comment]
Fixed in rev 4860
