### ISSUE TITLE
[EN][Spell][Shaman] Flametongue Totem

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1320]
Spell Power Bonus from the totem doesn't work. Tested 6% Spell Power bonus in resto spec and 10% bonus in Elemental spec. No it's not visual bug. Reproduced this with Healing Stream Totem.

http://cata.openwow.com/spell=8227 // Flametongue Totem

EDIT: Dziwne rzeczy sie dzieja ze spell powerem, podczas przywolywania pojedynczego Flametongue totemu oraz przywolywaniu i odwolywaniu wszystkich naraz w zakladce postaci tak czy inaczej Healing Stream Totem leczy zawsze za tyle samo niewazne co jest w zakladce postaci. Arcane Brilliance maga rowniez nie wplywa na leczenie tego totemu.

**Comment by serianx** [comment]
I can confirm this

**Comment by gurin** [comment]
Still bugged after 1 year,

**Comment by kadi2** [comment]
Fixed in rev https://atlantiss.eu/changelog#rev4930
