### ISSUE TITLE
[EN][Quest] Warchief's Command: Outland!

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1323]
http://www.wowhead.com/quest=28705

Quest is missing

**Comment by Daknyas** [comment]
According to WoWhead, note that if you already did http://www.wowhead.com/quest=9407 you can't pick it too, because both are leading to the same quest chain.

**Comment by Varchord** [comment]
I didn't. In orgri warchief command wasn't available to me (at level 60).

**Comment by xolon** [comment]
That quest showed up in my lvl 61 tauren warrior warchief's borad
http://i.imgur.com/BcPVIU4.jpg

**Comment by Varchord** [comment]
Dunno Maybe wrong level requirment?
