### ISSUE TITLE
[PL][Warrior][Talent] War Academy

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1326]
http://cata.openwow.com/spell=84572

Nie działa. sprawdzane na 3 pkt z użyciem Victory Rush (nie ma on przedziału dmg)

**Comment by Wolffenstein** [comment]
To miałeś pecha, bo nie działa tylko na Victory Rush :D

**Comment by Varchord** [comment]
W konia mnie robisz :P

**Comment by Wolffenstein** [comment]
Niet

**Comment by Wolffenstein** [comment]
Fixed in rev 4212.
