### ISSUE TITLE
[PL][Quest][Mount Hyjal] The Last Living Lorekeeper

### ISSUE THREAD

**Issue by sandgt** [Atlantiss/BugTracker#1331]
http://www.wowhead.com/quest=25830/the-last-living-lorekeeper

NPC z którym powinniśmy porozmawiać znika gdy się do niego zbliżymy, z pewnej odległości jest widoczny.

**Comment by jurek1** [comment]
owszem potwierdzam, gdy sie zblizamy do niego wlacza sie inna "faza" z czym wiaze sie brak mozliwosci oddania questa .
ten q psuje caly chain w hyjal

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/912
Dubel
