### ISSUE TITLE
[ENG] [NPC] Astrid Langstrump

### ISSUE THREAD

**Issue by Golonqa** [Atlantiss/BugTracker#1334]
Well, the NPC is where it should be but... she doesn't want to sell anything: http://s22.postimg.org/bfkke91jl/Wo_WScrn_Shot_010615_165141.jpg

Gib me my horses gypsy girl! ;<

**Comment by Bildo** [comment]
wowhead links

**Comment by Golonqa** [comment]
Here you go :] https://github.com/Atlantiss/BugTracker/issues/88

**Comment by Bildo** [comment]
fixed in rev 4240
