### ISSUE TITLE
[PL][Quest][Blade's Edge Mountains] Intercepting the Mana Cells

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1337]
http://www.wowhead.com/quest=11513
Po użyciu Bash'ir Phasing Device ( http://www.wowhead.com/item=34248 ) przenosi gracza w inną fazę natomiast nie da się wyjąć z kontenerów Smuggled Mana Cell 
( http://www.wowhead.com/item=34246#objective-of )

**Comment by Bildo** [comment]
fixed
