### ISSUE TITLE
 [PL][Quest][Icecrown] Reforging The Sword 

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1339]
http://www.wowhead.com/quest=24559
Na instancji Pit of Saron ( http://www.wowhead.com/zone=4813/pit-of-saron ) są widoczne te złoża 
( http://www.wowhead.com/item=49718/infused-saronite-bar ), nie da się jednak wejść z nimi w interakcje aby je podnieść.

**Comment by iprotocol** [comment]
Since every other version of this bug report has been closed(including mine) without a description, is there an update for this quest at all?

**Comment by Bildo** [comment]
this is open :)

**Comment by iprotocol** [comment]
thank you :) just curious

**Comment by HUMBOL** [comment]
Bump!

**Comment by avalancze23** [comment]
Well will this quest be repeared soon?

**Comment by aranguard** [comment]
This quest is working now and Tempering The Blade quest also works (2. Part of Chain) but 3. Part of chain The Halls of Reflection not working.Sword in the Halls of reflection and you can attack it but cant loot Subdued Quel'dalar.

**Comment by zano354** [comment]
For me, it still bugged (cannot be loot, even its glowing)

**Comment by raduriel** [comment]
Still the infused saronite in unobtainble hope they fix this it rly dosent take that much of a time

**Comment by zano354** [comment]
Bump!
