### ISSUE TITLE
[PL][Glyph] [Glyph of Exorcism]

### ISSUE THREAD

**Issue by Grigorian7** [Atlantiss/BugTracker#1341]
Now causes Exorcism to do 20% additional damage over 6 sec
Raz działa raz nie.
![wowscrnshot_010615_174510](https://cloud.githubusercontent.com/assets/10414753/5632047/caa70d2a-95cb-11e4-9441-c09faf2fe93d.jpg)

**Comment by Wolffenstein** [comment]
Zgaduję, że nie działa jak exorcism zmissuje. Ktoś może sprawdzić?

**Comment by Wolffenstein** [comment]
Przydałoby się więcej info. Jakaś zależność kiedy działa a kiedy nie?

**Comment by Wolffenstein** [comment]
Fixed in rev 4276.

**Comment by bgb** [comment]
Wciąż jest problem z tym glyhphem. Często się buguje i po jakimś czasie przestaje działać, trzeba się relogować:/

**Comment by Khangu** [comment]
Potwierdzam. Glyph ma tendencję do zacinania się. Na celu pokazuje się animacja, ale nie dostaje dota.
