### ISSUE TITLE
[PL][Quest][Desolace] Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1342]
http://www.wowhead.com/quest=6134/ghost-o-plasm-round-up
https://www.youtube.com/watch?v=ykoBCikTYiM
Po użyciu pudła ( http://www.wowhead.com/item=15848 ) w wyznaczonym miejscu ustawiany jest "magnes" i na tym koniec. Nie pojawiają się duchy ( http://www.wowhead.com/npc=11560 ), nie można więc zdobyć celu questa czyli ( http://www.wowhead.com/item=15849 ).

**Comment by Danelar** [comment]
po prostu nie pojawiają się te duchy, ani nawet wokół tego "magnesu" nie ma zielonego światła :|

**Comment by Veruca1320** [comment]
Potwierdzam

**Comment by Deonorth** [comment]
nadal nie działa

**Comment by Bildo** [comment]
fixed
