### ISSUE TITLE
[EN][Quest][The lost Isles] Old Friends

### ISSUE THREAD

**Issue by kazy14** [Atlantiss/BugTracker#1343]
http://www.wowhead.com/quest=25023 When you accept the quest the plane fly's few yards then dissappears droping me too , i abandone the quest and re-accepted it over and over again and tryed to accept it from different positions but same thing happend , i also tryed walking on foot but there is no  possible way out , however i found the solution by creating a macro with /reload and the moment i accepted the quest and the plane appeared i started pressing repeatedly the macro for about 15 times and it worked i was out of the cave and the plane was carrying me back to the camp , i should mention that i'm using the Mini Game Client

**Comment by Tj20** [comment]
I'm also using the mini game client and didn't have problems 2 days ago. The plane took my out of the Volcano just fine.
Maybe it is already fixed?

**Comment by Bildo** [comment]
It won't be smooth because script doesn't have support, only npcs that doesn't have waypoints in script use smooth path.

**Comment by Tj20** [comment]
Ah, ok. Well, anyways... the quest worked pretty much fine for me.

**Comment by Othentik** [comment]
Hi everyone, 

I completed that quest without issue but i'm still having permanent buff (Chipie's Flying Machine) and reload/relog don't remove it. Anybody else who's confront to this problem ?

Cheers.

**Comment by lamaATS** [comment]
Fixed in rev. 5241
