### ISSUE TITLE
[EN][Quest] Rolling with my homies

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1344]
This quest does not show the correct locations on its quest tracker and also does not cast a light around the required npc's.
http://www.wowhead.com/quest=14071

**Comment by Bildo** [comment]
wowhead links

**Comment by Tj20** [comment]
That's true, the lights around the NPCs are missing and the map locations are either wrong or too late and point at the NPC you've just picked up. (how it should look like: [video](https://www.youtube.com/watch?v=QyALeDsnkvc#t=41), [pic](http://i.imgur.com/om5BW30.jpg)).
I've traveled several minutes around Kezan in vein trying to find the 3 NPCs until I decided to look them up in a video.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
