### ISSUE TITLE
[En][Quest]Swift Discipline

### ISSUE THREAD

**Issue by Adunai** [Atlantiss/BugTracker#1346]
The apprentices are supposed to say the appropriate lines.

Apprentice Ralen says: What? Oh, not this again!

Apprentice Meledor says: You can't do this to me! We had a deal!

Link (http://wow.gamepedia.com/Quest:Swift_Discipline).

Screenshot#1 (http://i.imgur.com/TuUK88G.jpg).
Screenshot#2 (http://i.imgur.com/zj8Rzg8.jpg).

**Comment by Bildo** [comment]
wowhead links
