### ISSUE TITLE
[PL][Event]Aoenaxx

### ISSUE THREAD

**Issue by Admarx** [Atlantiss/BugTracker#1347]
Expię alta. Nagle NPCSCAN mi wykrzykuje, że Aoenaxx znalazł. Logam maina, dotarłem do Aoenaxx wskakuję licząc na smoka. Co się okazuje? Nie da się bić ani Aoenaxx, ani tych jej smoków.

Proszę o naprawienie eventu z Aoenaxx i jeśli łaska smoka za odnalezienie powyższego jegomościa ._.

//Admarx

http://i61.tinypic.com/16094sm.jpg

**Comment by Drutmaster** [comment]
Smoka nie dostaniesz, bo nie jesteś pierwszym, który takowego buga ma. Nawet w takim stanie DA się zabić Aeonaxxa (rangedzi mają łatwiej, bo jest jedna skała, skąd można smoka klepać. Owszem wydłuża to jego zdobycie, ale nie uniemożliwia). Jedyne co tutaj można zrobić, to naprawić błąd z losem podczas eventu. Ale mounta to musisz znowu sobie upolować.

**Comment by Wojmistrz** [comment]
@Drutmaster a co to za głupie gadanie "Nawet w takim stanie DA się zabić Aeonaxxa (rangedzi mają łatwiej, bo jest jedna skała, skąd można smoka klepać. Owszem wydłuża to jego zdobycie, ale nie uniemożliwia)." właśnie jest bug który jest po prostu do naprawy i nie ma gadania że RANGED może a MEELE nie może, to tak jakby napisać "Chcecie zdobyc mounta to sobie zrobcie rangeda i bijcie ze skałki O TAM bo smok Ci gunwo zrobi (bugowanie) no niestety meele klasy muszą się pożegnać ze zdobyciem tego."

**Comment by Drutmaster** [comment]
Ekhem... Kolega tutaj miał nadzieję, że mounta dostanie, ponieważ przez buga nie mógł go klepać (co zresztą podobno da się ominąć, wystarczy się inaczej na nim ustawić, nie wiem, nie próbowałem). Wyprowadziłem go z błędu i powiedziałem, że jak jest uparty, to DA radę go ubić. Czytaj całość. "Jedyne co tutaj można zrobić, to naprawić błąd z losem podczas eventu." Nie powiedziałem, że nie ma buga. Ale rozumiem, że według Ciebie, ma on czekać x czasu, aż zostanie naprawiony i patrzeć jak jakimś cudem ludzie mają tego mounta? (co drugi aeonaxx jest bugged i tak nawiasem mówiąc, smoki nie biją jak się na nim siedzi, co również jest bugiem...). Więc jak możesz, daruj sobie wyskakiwanie na innych i to jeszcze z motywem, że bugują. I następnym razem napisz coś pożytecznego, a nie tylko ciśnięcie -.-

**Comment by Giq** [comment]
Cza się na nim odwrócić i leciec "tylem w strone lotu". Low priority

**Comment by Giq** [comment]
#840
