### ISSUE TITLE
[EN][Quest][Ashenvale] Search the Bole

### ISSUE THREAD

**Issue by Hordraric** [Atlantiss/BugTracker#1349]
ive killed over 20 crazed ancients (http://www.wowhead.com/npc=3834) which should drop wooden key  (http://www.wowhead.com/item=5475) so i could open the chest and still no loot from these mobs

quest: http://www.wowhead.com/quest=1026#comments

**Comment by Aival94** [comment]
before 5-7 days if i remember correctly :D

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
