### ISSUE TITLE
[EN] [Core idk] Frame drop Nagrand

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#1350]
So i have constant 60 fps in every area except Nagrand, when i enter Nagrand zone it drops to 20-30 few of my mates have same issue

**Comment by Wojmistrz** [comment]
im guessing it is caused because core (called core clusters? or smth) isn't optimized for every areas and aspects of game (it can be seen in dungeons and raids as well) and ofc it depends on your PC :P especially processor and graph card.

**Comment by Jenovas** [comment]
Xolon please tell us is it everywhere in Nagrand or maybe zones? There might be scripts that arent optimized and cause FPS drop or even lags. The best thing would be fly around Nagrand and make screenshots of the map where FPS falls. Thx.

**Comment by Bildo** [comment]
For me everything works fine
