### ISSUE TITLE
[EN][QUEST][the lost isles] Warchiefs Revenge

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1356]
The cyclone stutters and jolts in flight and does not carry you back to the wild overlook.
http://www.wowhead.com/quest=14243

**Comment by Bildo** [comment]
wowhead links

**Comment by Tj20** [comment]
True. After the cyclone drops you you have to swim and run quite a distance.

![pic](http://i.imgur.com/O8tLUay.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
