### ISSUE TITLE
[EN][Quest][Winterspring] "Get Them While They're Young"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1357]
http://www.wowhead.com/quest=29032

The Cubs you're supposed to collect cannot be collected, only killed.

This was already mentioned in closed issue [#1047](https://github.com/Atlantiss/BugTracker/issues/1047) because it should have been fixed in rev. 4179, however it doesn't seem to work yet.

**Comment by Bildo** [comment]
Ohhh i forgot fix that :D

**Comment by Bildo** [comment]
fixed in 4248

**Comment by Aival94** [comment]
This one is stil bugged the same way.
