### ISSUE TITLE
[EN][Quest][Badlands] The Day Deathwing Came

### ISSUE THREAD

**Issue by Rakeen70210** [Atlantiss/BugTracker#1358]
Neither of the quests in badlands are working at all. Both are heavily scripted quests but are extremely fun quests. 

Here are the two quests that are bugged: http://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened

http://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story

**Comment by Varchord** [comment]
There is a story. Story of great heroes and villains but you can't tell one from another. 
A story that this quests has been scripted by a great hero. But along with the mighty script came crashes and code inefficiency and so council of sages decided to banish the code into lands of forgotten.
Hero then said "Fuck it, I quit!"

**Comment by Varchord** [comment]
Either that or i was thinking of another quests ^^

**Comment by nerv234** [comment]
Administration knows about badlands bugs very well.

**Comment by Varchord** [comment]
But he didn't knew that ^^

PS. That guy above me is the one from my story :P

**Comment by lourrific** [comment]
As of May 18, 2015 this quest is still broken.
I'm not getting credit for killing the rock elementals.
OK I get it that scripted quests are very difficult to fix so nobody cares to fix them anymore but can you at least make them instant win for the sake of game play and quest completion?

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6774
