### ISSUE TITLE
[PL][Quest][Storm Peaks] Drakkensryd

### ISSUE THREAD

**Issue by greenrhasta** [Atlantiss/BugTracker#1362]
Nie mogę użyć poprawnie harpunu, zaraz po użyciu wskakuje na protodrake-a i laduje sporo metrów pod nim, wraz z nim się przemieszczam, widok przechodzi do 1st osoby i na tym sie konczy nie moge targetować ani atakować wyznaczonych targetów z questu. 

http://www.wowhead.com/quest=12886
https://www.youtube.com/watch?v=0M2y0bJRBn4

Powodzenia i Milego Dnia

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1513

**Comment by Startbar** [comment]
I have no idea what the polish are saying but this quest needs looking at from the ground up. It is completely broken

**Comment by Fikoblin** [comment]
Quest w ogóle nie działa. Po zaakceptowaniu zamiast przenieść nas na smoka, kasuje przebranie i wszyscy stają się wrodzy. Pewnie ma to coś w związku z aurami, kilka questów wcześniej też usuwało buffa, ale wystarczyło wlecieć i wylecieć z wioski, by znowu się pojawiła.

**Comment by armano2** [comment]
dupliacte: #3784
