### ISSUE TITLE
[EN][NPC] Timothy Jones

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1363]
http://www.wowhead.com/npc=28701/timothy-jones#comments

His training option is labeled as "GOSSIP_OPTION_TRAINER"

**Comment by Bildo** [comment]
and he should have ?

**Comment by Varchord** [comment]
Train me? I dont know. But im sure it shouldn't be "GOSSIP_OPTION_TRAINER"

**Comment by Bildo** [comment]
fixed in rev 4240
