### ISSUE TITLE
[PL] Seek Out Neltharaku

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1365]
nie ma npc żeby skończyć quest
http://www.wowhead.com/quest=10811/seek-out-neltharaku

**Comment by Wolffenstein** [comment]
Jest npc, tyle że powinien latać po waypointach, a stoi w jednym miejscu.

**Comment by arekczup** [comment]
to gdzie on jest ? szukałem lecz nie znalazłem.
