### ISSUE TITLE
[EN][Quest][The Hinterlands]Ongo'longo's Revenge

### ISSUE THREAD

**Issue by silverches** [Atlantiss/BugTracker#1368]
https://www.youtube.com/watch?v=0UnybOR6CvY
http://www.wowhead.com/quest=26515

Ongo'longo is in the wrong place and you can't kill him

http://prntscr.com/5plh6a

**Comment by Dexobox** [comment]
This quest did not work for me, NPC Ongo'longo gets enraged but still maintains aggro instead of running away, and count towards quest objetcive never happens.

**Comment by Nightend1** [comment]
+1 still  broken

**Comment by TheCopacabanaMan** [comment]
+1 still broken

**Comment by tomatosz** [comment]
Ongo'Longo enrages and walks away, but quest doesn't complete. Could this be opened again or should I open a new one?

**Comment by KasiaSmolarska** [comment]
+1 still broken
