### ISSUE TITLE
[EN] [Dungeon-Classic] Lower / Upper Blackrock Spire (LBRS/UBRS)

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1369]
http://www.wowhead.com/zone=1583/blackrock-spire

**Problem 1:** The Dungeon Finder doesn't place you at the dungeon entrance, but at the instance portal to Blackwing Lair. (The same problem as in Uldaman [#1142](https://github.com/Atlantiss/BugTracker/issues/1142) and Blackrock Depths [#946](https://github.com/Atlantiss/BugTracker/issues/946) where the Dungeon Finder also spawns you at the wrong entrance)

![wrong entrance](http://i.imgur.com/8rXA5Gd.jpg)

**Problem 2:** Shortly after entering the dungeon, the group encounters two [Blackhand Assassins](http://www.wowhead.com/npc=10318/blackhand-assassin) in stealth, who can't be targeted and interacted with in any way even after they de-stealth and attack you (I only got their name when looking at the combat log). These mobs will just kill your group, since you can't do anything to them. (Only my pet seems to be able to attack them)

![2 stealthy 4 you](http://i.imgur.com/QeSzyvM.jpg)

It seems that because of these mobs, the dungeon cannot be completed at the moment.

**Comment by Wolffenstein** [comment]
Fixed in rev 4226.
