### ISSUE TITLE
[PL] Block

### ISSUE THREAD

**Issue by KrolServera** [Atlantiss/BugTracker#1370]
Prot war jak i paladyn nie blokuje

**Comment by Varchord** [comment]
Eeee. Blokuje

**Comment by KrolServera** [comment]
Nie blokuje

**Comment by NONLIFE** [comment]
Nie blokuje bo nie zlicza zadnego blocka

**Comment by KrolServera** [comment]
Skren że nie blokuje - https://imagizer.imageshack.us/v2/720x576q90/673/5cNKlX.jpg

**Comment by Varchord** [comment]
No patrz faktycznie. To ja nie wiem co to za liczby w nawiasie
http://i.imgur.com/HXU19cW.jpg

I na Tym twoim recouncie w "blocked" wierszu to faktycznie te cyferki to samoe 0

**Comment by Varchord** [comment]
Zamknij ten issue bo to jakiś śmiech jest

**Comment by KrolServera** [comment]
Sam się zamknij, jest problem to go zgłaszam

**Comment by Varchord** [comment]
Gdzie ty problem widzisz? Ty blokujesz, ja blokuje -.-

**Comment by KrolServera** [comment]
Oto chodzi że nie blokuje, jakbym blokował to chimerion normal/hc z jednym stackiem na strzałą by mnie nie zabijał

**Comment by Varchord** [comment]
Jak byk u ciebie jest napsiane 
Blocked : 7218

Jak byk u mnie widać 
<252 blocked>
<152 blocked>
<120 bloecked>
<123 blocked>

**Comment by fafal** [comment]
1. Naucz sie tankiem odpalac czy cokolwiek, nie wiem nie stac plecami?
2. Odpalaj robota?
3. Naucz helerow topować tanka?
4. NAUCZ SIĘ PISAĆ NORMALNE ZGŁOSZENIA?
no offence ;s

**Comment by iskk** [comment]
Od siebie dodam, że blokujesz nie całego hita a tylko część DMG. Zresztą na chimka hc masz za słaby gear lol
