### ISSUE TITLE
[PL][QUEST][Hillsbrad Foothills][Basic Botany]

### ISSUE THREAD

**Issue by asteroida** [Atlantiss/BugTracker#1378]
Nie przenosi do miejsca gdzie mona  zacząć quest, a powinno zrobić to automatycznie po  zaakceptowaniu.

http://www.wowhead.com/quest=28733/basic-botany
https://www.youtube.com/watch?v=ocMikuQ0JNg

**Comment by Bildo** [comment]
duplikat uzyj najpierw opcji search
