### ISSUE TITLE
[PL][QUEST][Darkshore][Remembrance of Auberdine]

### ISSUE THREAD

**Issue by asteroida** [Atlantiss/BugTracker#1380]
nie ma NPC od questu

http://www.wowhead.com/npc=32959

**Comment by Wolffenstein** [comment]
Zrobiłeś questa http://www.wowhead.com/quest=13518?

**Comment by asteroida** [comment]
mam zrobione wszystkie q  z wioski, npc pijawił  się z jednym q 
http://www.wowhead.com/quest=13563 a kolejnego nie dostałam

**Comment by asteroida** [comment]
po kilku dodatkowych questach w Darkshore a mianowicie 30 dostalam ten q
