### ISSUE TITLE
[EN][Quest] [Reforging The Sword] Horde

### ISSUE THREAD

**Issue by florrine** [Atlantiss/BugTracker#1381]
http://www.wowwiki.com/Quest:Reforging_The_Sword_%28Horde%29

The infused saronite piles aren't lootable in either normal or heroic although the are giving their loot glow.
 https://c1.staticflickr.com/3/2769/4179267839_6280f0528b_z.jpg?zz=1

**Comment by Bildo** [comment]
duplicate
