### ISSUE TITLE
[EN][Spell][Shaman] Earth Shield and Heal Modifiers

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1382]
I haven't heard about this mechanic before, but i noticed Earth Shield is snapshotting upon casting with heal modifiers such as Wound Poison, Spark of Life and then scales dynaimcally too, to the point where these buffs and debuffs doubledipp their effects.

I am not sure if it's a bug. Just wanted to share this unusual find.

http://cata.openwow.com/spell=974 // Earth Shield
http://cata.openwow.com/spell=84848 // Spark of Life
http://cata.openwow.com/spell=13218 // Wound Poison
http://cata.openwow.com/spell=47180 // Nurturing Instinct
http://cata.openwow.com/spell=16213 // Purification // Impossible to test
http://cata.openwow.com/item=45775 // Glyph of Earth Shield // Can't be tested right now

**Comment by Varchord** [comment]
HoTs, DoT's scale dynamically with debuffs/buffs on targets

**Comment by kadi2** [comment]
It is possible it will benefit twice with Earth shield glyph and benefits twice from purification. It's hard to say anything about coeffs right now with all these bugs but:

Patch 4.1.0 (26-Apr-2011): Earth Shield healing done by Restoration shaman has been reduced by 20%.

However right now it heals about twice than it should.

**Comment by Wolffenstein** [comment]
Fixed in rev 4277.
