### ISSUE TITLE
[EN][Paladin][Spell] Holy Shock

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1386]
This is a continuation of the already closed report: https://github.com/Atlantiss/BugTracker/issues/1031

Well, you managed to make the spell even more broken than before the "fix". Let me explain in more detail how both components of the spell are supposed to work. When you use Holy Shock on an enemy target, you're supposed to be able to damage your target only if you're facing towards him. If you're not facing him, then you should receive an error message that the target needs to be in front of you and the 6 seconds cooldown shouldn't start. You've fixed the position requirement for the damage component of the spell, but this same rule now applies for the healing component as well. Right now, your friendly target has to be in front of you in order to heal him with Holy Shock. If you're not facing towards him, you receive the error message that he needs to be in front of you. Needless to say, every healing spell in the game has no facing requirement and this includes the healing component of Holy Shock.

Holy Shock: http://cata.openwow.com/spell=20473

**Comment by Wolffenstein** [comment]
Sorry, fixed in rev 4218.
