### ISSUE TITLE
[PL][Spell][Rogue] Combat Readiness

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1389]
Ciag dalszy https://github.com/Atlantiss/BugTracker/issues/1029

Wiedzialem, ze nie obejzysz filmiku i zostanie to naprawione w ten sposob :D Combat Insight powinien schodzic tylko i wylacznie on remove Combat Insight buff lub 20 sekund po uzyciu umiejetenosci.

W tej chwili Combat Readiness moze zniknac 10 sekund po odpaleniu Combat Readiness nawet jezeli nie nastackujemy ani jednego buffka Combat Insight. W takim przypadku Combat Readiness buff powinien trwac pelne 20 sekund mimo tego, ze nie zostalismy zaatakowani z melee ataku.

https://www.youtube.com/watch?v=9kIlcpD1ZQs // Mimo tego, ze jest to MoP to na tym i poprzedni filmiku mozna bylo zaobserwowac ta sama mechanike spella.
http://cata.openwow.com/spell=74001 // Combat Readiness
http://cata.openwow.com/spell=74002 // Combat Insight

**Comment by Wolffenstein** [comment]
Eh, to po co ja się tak męczyłem. Czemu wszędzie jest napisane, że jak nie oberwiesz po 10 sekundach to ci zniknie?

**Comment by kadi2** [comment]
Bo tak jest napisane w tooltipie. ;p A szkoda, bo fajnie nawet wyszlo.

**Comment by Wolffenstein** [comment]
Fixed in rev 4220.
