### ISSUE TITLE
[PL][Talent][Rogue] Overkill

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#1391]
Regeneracja energii u rogala ( jej wyswietlanie w stat. oraz jej odczuwanie) dzialają poprawnie. Niestety, ostatnia poprawka na wyswietlanie i odczuwanie reg. energii spowodowała że talent Overkill http://www.wowwiki.com/Overkill przestał działać. Nie wyświetla dodatkowej reg. energii w statystykach ani nie przyspiesza samej eneregii. Pwazny bug dla assa.

**Comment by nerv234** [comment]
Potwierdzone info, testy wykonane na moim rogalu (spamienie shivem) bez innego regenu energii.
Bez overkilla w 20sekund 9 shivów i zostało 20 energii.
Z overkillem 20sekund 9shivów i 19energii zostało(błąd ludzki przy sprawdzaniu).

Sprawdzałęm na 20 sekundach bo tyle trwa overkill i jak by działało bym wycastował przynajmniej jednego więcej shiva.

**Comment by Wolffenstein** [comment]
Fixed in rev 4220.

**Comment by nerv234** [comment]
Dzięki, sprawdzę jak wejdzie rev na serwer.
