### ISSUE TITLE
[PL][Object] Portal to Orgrimmar in Blasted Lands

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1392]
Tak jak w temacie przy Dark Portal nie ma możliwości przeniesienia sie do Stolicy Hordy :|

**Comment by nerv234** [comment]
Jest portal po 2 stronie portalu:), btw. gdzie linki i opis, dowody że powinien być?

**Comment by Bildo** [comment]
heheszki

**Comment by NONLIFE** [comment]
Tak jak nerv234 napisal portale do Ogrimmar jak i Stormwind sa po przejsciu przez Dark Portal w Hellfire Penisula na prawo albo lewo.

Co do portalu w Blasted Lands do ogrimmar chyba jest ale nie na tym contencie 
http://youtu.be/6ieGGbtu9wo?t=16s

close plz

**Comment by Danelar** [comment]
No sam skorzystałem, ale byłoby mi wygodniej :/
@nerw234 - :P
