### ISSUE TITLE
[PL][Quest][Un'Goro Crater] They Grow Up So Fast

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#1395]
http://www.wowhead.com/quest=13906/they-grow-up-so-fast
Nasz mały nicpoń ( http://www.wowhead.com/npc=34320/venomhide-hatchling#starts ) za pierwszym razem daje questów aż za dużo ( każdy quest 2 razy), a następnego dnia nie dostajemy już żadnego, w kolejnych dniach również.

**Comment by Satyr87** [comment]
w moim przypadku wcale nic nie dal od nowosci

**Comment by Bildo** [comment]
fixed in rev 4240
