### ISSUE TITLE
[EN][Core] Flight path not automatically revealed

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1396]
The flight path to Hunter's Hill in Southern Barrens isn't automatically being revealed, once you reach the appropriate level. If anyone else has found the same issue with other flight paths, please share.

**Comment by Spydoc** [comment]
Update: The flight path to Desolation Hold in Southern Barrens also doesn't get automatically revealed.

**Comment by Bildo** [comment]
Weird becouse Desolation Hold should reveal after 35 level

**Comment by Bildo** [comment]
fixed in rev 4240
