### ISSUE TITLE
[EN][Spell][Shaman] Healing Stream Totem

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1399]
For some odd reason Healing Stream Totem heals for less upon entering arena.
Normally it heals me for: 1486
When i enter arena it heals me for: 1337

In addition Healing Stream Totem stopped to benefit from Mastery.

http://cata.openwow.com/spell=5394 // Healing Stream Totem

**Comment by Jenovas** [comment]
In every PvP zone (BG, Arena) there is something called "Heal Dampening".
Blizzard didnt know how to balance healers in PvP and PvE, so they decided to reduce healing in PvP zones. This aint a bug.
Closing.
