### ISSUE TITLE
[EN][QUEST][the lost isles]The Biggest Egg Ever

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1401]
After killing Mechachicken, his egg is unlootable.

http://www.wowhead.com/quest=24744
https://www.youtube.com/watch?v=AMLyqW-L3WE

**Comment by Wolffenstein** [comment]
You have to wait about 10 minutes and it will be lootable.

**Comment by JeZuZz** [comment]
After a quick relog you can loot it as well.

**Comment by narosky** [comment]
Issue is still here and up to date, it's fine after relog.
