### ISSUE TITLE
[EN][Worgen] Abberation passive

### ISSUE THREAD

**Issue by stewazy** [Atlantiss/BugTracker#1404]
This passive gives resist to shadow and nature dmg, i'm lvl 58 atm and it gives 1 resistance ? I think it is broken

**Comment by Bildo** [comment]
wowhead link and find proofs that it's working bad

**Comment by stewazy** [comment]
They changed stuff in wowhead in wod but here is the link anyway http://www.wowhead.com/spell=68976/aberration and a screenshot from my spellbook
![image](https://cloud.githubusercontent.com/assets/8582180/5705041/a247f4c0-9a76-11e4-80f0-832ff0ba84ea.png)

**Comment by Kejmil** [comment]
it's only visual, racial gives proper values to resistances
