### ISSUE TITLE
[EN][NPC][The Lost Isles]Oomlot shaman

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1406]
The npc does not attack until you attack them first, they chase you while casting their spell.
![wowscrnshot_010815_215048](https://cloud.githubusercontent.com/assets/10423624/5671572/e757bdd2-9780-11e4-9146-200377ce8579.jpg)
 
http://www.wowhead.com/npc=38574

**Comment by Bildo** [comment]
i can't reproduced it
