### ISSUE TITLE
[EN] [Dungeon-TBC] Slave Pens

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1407]
http://www.wowhead.com/zone=3717/the-slave-pens

Two minor issues I've noticed in the Slave Pens:

**1.** In the big room there are many ice blocks which are [normally](http://i.imgur.com/lyvXZ2a.jpg) not there. I guess they belong to the midsummer festival boss [Ahune](http://www.wowhead.com/npc=25740/ahune). No big deal, but they were a problem for our group because they created a line of sight issue with a mob, so we couldn't attack him, and being a caster, he kept us in combat the whole instance (see [#1018](https://github.com/Atlantiss/BugTracker/issues/1018)).

![ice ice baby](http://i.imgur.com/JRFGeWa.jpg)

**2.** [Coilfang Slavehandlers](http://www.wowhead.com/npc=17959) call nearby [Wastewalker Slaves](http://www.wowhead.com/npc=17963) and [Wastewalker Workers](http://www.wowhead.com/npc=17964) for help when aggroed, however the slaves did ignore the call for help.

Normally they are neutral, get hostile when a Slavehandler calls them and become neutral again and run away when the Slavehandler dies.

**Comment by Bildo** [comment]
fixed in 4248
