### ISSUE TITLE
[EN][NPC] Forsaken Prisoner

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1409]
What is not working:
=============

They are standing in a "torture bed".

---------------
How should work:
=============

They should be dead, laying in their torture beds.

----------------------
More info:
=============

They are usually visited by the players who are doing the quest "[Torture the Torturer](http://www.wowhead.com/quest=12252)".

[Screenshot](http://i.imgur.com/C5H3TZe.jpg)
[Video#1](http://youtu.be/2Tf-jF-lyS8?t=36s)
[Video#2](http://classic.xfire.com/video/487b49/)
[Forsaken Prisoner#1](http://www.wowhead.com/npc=27400)
[Forsaken Prisoner#2](http://www.wowhead.com/npc=27219)

**Comment by Bildo** [comment]
fixed in rev 4240
