### ISSUE TITLE
[EN][Spell][Mage] Cone of Cold Multiple procs for Finger of Frost

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#141]
Cone of Cold should make separately checks for each target it hits with Finger of Frost and it's very possible it should work this way with Brain Freeze procs.(I just don't have prove for Brain Freeze and probably won't be able to find it)

Watch first 11 seconds for double FoF proc
https://www.youtube.com/watch?v=N7JWFBNijDE

Works well with impact proc on PTR and 4.0.6

**Comment by blinkmaster** [comment]
bump. major bug for procc management

**Comment by blinkmaster** [comment]
.

**Comment by blinkmaster** [comment]
plz :( fix this :(
