### ISSUE TITLE
[PL][Class][Death Knight][Pet] Ghoul energy regeneration

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#1410]
U nas ghoul nadal posiada regen energi w postaci 20 co 2 sec a powinien regac 1 co 0.1 sec jak rogal czy druid w kotku.
https://www.youtube.com/watch?v=y0tfUCk7FbI przy 1:44 widac frame ghoula po lewej gdzei jest poprawny regen
Haste także powinnien zwiększać regen energii u ghoula tak jak u rogala/druida.
https://www.youtube.com/watch?v=MmcO4G6I0jA  od 7:38 widać na środku ghoula pod wpływem dark transformation który spamuje sweeping clawem który ma efekt graficzy warkowego cleawa.

**Comment by Jenovas** [comment]
Fixed in rev 4357
