### ISSUE TITLE
[EN][Quest][Dragonblight] The Denouncement

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1411]
What is not working:
=============

At the moment, there are 2 Commander Jordans in the same room. But in different positions.
One is in the right position, the other is near the center.

---------------
How should work:
=============

There should only be one inside the room.

----------------------
More info:
=============

**Important Note:** The room is kinda different from the one on the Video. I found the room with just 2 NPCs (2 Cmd. Jordans), on the video there were some guards.

[Screenshot](http://i.imgur.com/n4iVRgu.jpg)
[Video](http://youtu.be/NJgCqOjJ9cg?t=1m5s)
[Commander Jordan - WoWHead](http://www.wowhead.com/npc=27237)
[Commander Jordan - WoWPedia](http://wow.gamepedia.com/Commander_Jordan)
[The Denouncement - WoWHead](http://www.wowhead.com/quest=12273)

**Comment by Bildo** [comment]
fixed in 4248
