### ISSUE TITLE
[EN][Item] The Diary of High General Abbendis

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1413]
What is not working:
=============

It's basically a blank book.

---------------
How should work:
=============

This book should have a nice story about Abbendis' adventures.

----------------------
More info:
=============

This book is needed for the quest "[The Truth Will Out](http://www.wowhead.com/quest=12283)".

[Screenshot](http://i.imgur.com/D0Iewy3.jpg)
[The Diary of High General Abbendis - WoWHead](http://www.wowhead.com/item=37540)
[The Diary of High General Abbendis - WoWPedia](http://wow.gamepedia.com/The_Diary_of_High_General_Abbendis)

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
