### ISSUE TITLE
[eng] misleading/abusable gm script!!!

### ISSUE THREAD

**Issue by ankankank55** [Atlantiss/BugTracker#1415]
alredy known

**Comment by ankankank55** [comment]
first is a gm second is me

**Comment by ankankank55** [comment]
perfected sript Xd /script if(not scm) then scm=SendChatMessage; end; function SendChatMessage(m,t,l,c) if(strfind(m,"\124H")==nil) then scm("\124cffff7eff\124TInterface\\ChatFrame\\UI-ChatIcon-Blizz.blp:13:20:0:0\124t"..m.."\124r",t,l,c);else scm(m,t,l,c);end;end

**Comment by ankankank55** [comment]
if i didnt give golds back now i d have 200k:C

**Comment by ankankank55** [comment]
<3 bastek <3 -ty for talent reset backup keep up the good work guys

**Comment by Tj20** [comment]
I would advise to delete that script here and the link to where you found it. It may take a while to get fixed, and you don't want other people to use it in the meantime. Maybe PM it to a dev.

**Comment by ankankank55** [comment]
thanks  <3

2015-01-09 1:46 GMT+01:00 Tj20 <notifications@github.com>:

**Comment by lanrutcon** [comment]
GMs have the Blizz logo before their names. That script adds an image after your name.
Still, this might be effective against newbies.

**Comment by ankankank55** [comment]
:D it can be modyfied  buty thanks for help:D
