### ISSUE TITLE
[EN][Spell][Shaman/Warlock] Earth Shield and Soul Link

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1416]
Earth Shield: http://cata.openwow.com/spell=974
Soul Link: http://cata.openwow.com/spell=25228

When warlock has active Soul Link and shaman put Earth Shield on him - ES doesn't heal Warlock while he is hit by melee attack, he has still 9 stacks and there is no heal effect. 
Only reduced pushback thing works.

Without active Soul Link - Earth Shield heals properly.

**Comment by Jenovas** [comment]
Fixed in rev 4404
