### ISSUE TITLE
[EN][Quest][Southern Barrens]The Butcher of Tuarajo

### ISSUE THREAD

**Issue by kazy14** [Atlantiss/BugTracker#1420]
http://www.wowhead.com/quest=24637/the-butcher-of-taurajo    The Npc you are supposed to talk with to start the event is at the right place but the problem is when you click the Gossip "I am ready Karthog.  FOR THE HORDE ! " nothing happens

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/627
