### ISSUE TITLE
[EN][Quest][Southern Barrens] Siegebreaker

### ISSUE THREAD

**Issue by kazy14** [Atlantiss/BugTracker#1421]
http://www.wowhead.com/quest=24569 You are supposed to destroy those "siege machinery outside the gates of Mulgore" but this quest auto completes

**Comment by eryczek1615** [comment]
bump

**Comment by RastaTinu** [comment]
Quest dalej jest jako "auto complete" chociaż samemu można zniszczyć te maszyny, więc można go pewnie zrobić blizzlike

**Comment by Jenovas** [comment]
Fix in 5538
