### ISSUE TITLE
[EN][Spell][Shaman] Elemental Mastery

### ISSUE THREAD

**Issue by serianx** [Atlantiss/BugTracker#1424]
http://cata.openwow.com/spell=64701
Elemental mastery is not properly showing the remaining time of the cooldown most of the time. sometimes it works, but most of the time it tells you spell is not ready yet, but the icon doesn't display cd

**Comment by int24rain** [comment]
Well it was working before but now isnt working.It doesnt show the time left and even without using it you cannot use it cause it says "Spell is not ready yet".

**Comment by Crusaderz** [comment]
Workaround: 
make macro /castsequence reset=5 Elemental Mastery

**Comment by Jenovas** [comment]
Fixed in rev 4714
