### ISSUE TITLE
[EN][NPC][Ironforge] Hulfdan Blackbeard <Rogue Trainer>

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#1429]
NPC: http://www.wowhead.com/npc=5165/hulfdan-blackbeard

EN: Can't interact with NPC nor take quest from him (as a rogue).
PL: Brak możliwości interakcji oraz przyjęcia zadania (jako łotrzyk).

**Comment by Bildo** [comment]
rev. 4353 by Quban
