### ISSUE TITLE
[EN][Quest][Wetlands] Onwards to Menethil

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#1432]
Quest: http://www.wowhead.com/quest=25777/onwards-to-menethil

EN: Can't take ram mount which would transport us to destination (Menethil Harbour).
Currently we need to walk by our own means, quest works.

PL: Brak możliwości użycia barana, który doprowadziłby nas do miasta Menethil.
Aktualnie jesteśmy zmuszeni iść na własną rękę, zadanie działa prawidłowo.

**Comment by Bildo** [comment]
w kazdym swoim ogloszeniu popraw tytul i dodaj [EN] (tak wbrew pozorom jest to wazne)

**Comment by Navedonar** [comment]
działa już prawidłowo
