### ISSUE TITLE
[EN][Creature][Duskwood] Black Widow and Black Widow Hatchlings

### ISSUE THREAD

**Issue by roderik18** [Atlantiss/BugTracker#1434]
The Black Widow and Black Widow Hatchling mobs in Duskwood (needed to kill in the [The Jitters-Bugs] quest) disappear after a few hits and then reappear, this is no huge problem because it is pretty easy to kill them and it is possible to loot the corpses, but it is quite annoying that you have to target them again and i think they are not supposed to do that.

mobs: http://www.wowhead.com/npc=930/black-widow-hatchling
           http://www.wowhead.com/npc=45582/black-widow
quest: http://www.wowhead.com/quest=26721

Fix this whenever you have time.

Importance of fix: Low

**Comment by Quban** [comment]
They use http://www.wowhead.com/spell=87080/vanish and http://www.wowhead.com/spell=82715/flee-into-the-shadows so they work properly.
