### ISSUE TITLE
[EN][[Warlock][Pets] Crit Frequency? + Melle swing

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#1436]
I think about spell crit frequency on warlocks pet.
These values arent too low?

Simcraft show me selfbuffed value on shadow bite 28%
On Raid i had values between 11-14% crit
Selfbuffed testing on 88+ dummy i had something between 6-10% with Hand of Guldan Aura and improved shadow bolt (testing with around 200 hits of SB 2 times)
Same with imp i had high crit chance on simcraft(24%) on dummy, my firebolt crit frequency is... not amazing ;s some guyz on EJ (http://forums.elitistjerks.com/topic/109273-simulationcraft-for-warlocks-cataclysm-edition/page-15 testing dat mechanic too and i never see on my imp 16%+ chance for crit after encounter/dummy...
For Autoattack everything i think works good.

Maybe someone knows much more about dat? Because I have an impression a something works not correctly.

+++
Imp,Doomguard,Succub still use autoattack on melee range...

Ps. Guyz plox do something with https://github.com/Atlantiss/BugTracker/issues/76 ;o

**Comment by Bildo** [comment]
pet melee and spell crit will now scale with owners crit fixed by Jenova
