### ISSUE TITLE
[PL] [Achievement] The Incredible Hulk

### ISSUE THREAD

**Issue by Lauthai** [Atlantiss/BugTracker#1444]
Miecz Svali nie uderza w ziemie i nie zabija Hulka przez co nie mozna zrobic achievementa
http://www.wowhead.com/achievement=2043/the-incredible-hulk

**Comment by eryczek1615** [comment]
Achie da się zrobić jest sposób lecz to nie zmienia faktu, ze achi bugged

**Comment by Lauthai** [comment]
Napisz mi jaki masz nick, przydałaby mi sie twoja rada, poniewaz jest to ostatni achi jakiego potrzebuje do Glory of the Hero
:)

**Comment by xolon** [comment]
bump

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1755
