### ISSUE TITLE
[EN][NPC] Theramore Sentry

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1445]
The NPCs are hostile but you can't interact with them in any way. They should be attackable, just like any other mob.

Theramore Sentry: http://www.wowhead.com/npc=5184

**Comment by Daknyas** [comment]
Aren't they hostile only towards horde?

**Comment by Spydoc** [comment]
They are, but they also aren't moving and are unattackable. Even if you move your mouse cursor over them, it doesn't turn to a sword, it just stays as a hand.

**Comment by Bildo** [comment]
fixed
