### ISSUE TITLE
[PL][Warrior][Fury][Talent] Enrage

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#1447]
Po aktywowaniu 

Berserker Rage - http://www.wowhead.com/spell=18499/berserker-rage#changelog

powinnismy dostać ?

Enrage - http://www.wowhead.com/spell=13046/enrage#modified-by

Czy to ma tak byc?

**Comment by kadi2** [comment]
Tak ma byc.

**Comment by NONLIFE** [comment]
albo po odpaleniu 

Death Wish - http://cata.openwow.com/spell=12292 ( sry z wowhead nie znalazlem )

**Comment by Jenovas** [comment]
Nie rozumiem zgłoszenia. Zamykam.
Jak coś jest zbugowane proszę jeszcze raz napisać tym razem po ludzku i nie pytać tylko sprawdzić samemu jak ma być.
