### ISSUE TITLE
[PL][Questy] JC - broken figurine

### ISSUE THREAD

**Issue by ecllipse** [Atlantiss/BugTracker#1449]
Po mimo posiadania matsów nie da się oddać poniższych questów do JC:
Broken Boar Figurine http://www.wowhead.com/quest=28778#comments
Broken Earthen Figurine http://www.wowhead.com/quest=28776
Broken Owl Figurine http://www.wowhead.com/quest=28777

**Comment by Bildo** [comment]
duplikat
