### ISSUE TITLE
[PL][Warrior][Fury] Death Wish - zaniżony dmg

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#1451]
w Berserker Stance-ie bez żadnego shout-a
moj dmg wynosi: 5113 - 6156

po wlaczeniu Death Wish 

dmg wynosi: 6377 - 7678

jest to za niski dmg o

116,51 - 140,12

moj Death Wish wynosi 27%

**Comment by Varchord** [comment]
Sprawdzaj takie rzeczy na bloodthirst. Ma on stały dmg jeśli twoje ap si nie zmienia. Dmg, któy posiada range jest mało wiarygodny

**Comment by NONLIFE** [comment]
Z tym może byc problem własnie XD

**Comment by Varchord** [comment]
Jaki problem? Ściągasz trinkety. Kupujesz białą broń do vendora. Sprawdzasz ile BT bije bez DW, sprawdzasz ile bije z DW i mnozysz

**Comment by NONLIFE** [comment]
po szybkich testach z biala bronia wydaje mi sie ze jest ok. Zamykam i dzieki :)
