### ISSUE TITLE
[EN][NPC] some hostile (red) mobs behave like neutrals (yellow)

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1452]
[Thunderlord Dire Wolves](http://www.wowhead.com/npc=20748/thunderlord-dire-wolf) are marked as hostile (red), yet behave like a neutral mob: they won't aggro / attack you unless you attack them.

edit: I found more after a quick round in Blade's Edge Mountains, but I guess it may also be the case in other zones:

[Bloodmaul Skirmisher](http://www.wowhead.com/npc=19948)

[Bloodmaul Geomancer](http://www.wowhead.com/npc=19952)

[Bladespire Shaman](http://www.wowhead.com/npc=19998)

[Bladespire Brute](http://www.wowhead.com/npc=19995)

[Elder Black Bear](http://cata.openwow.com/npc=1186), Loch Modan

![don't want to attack](http://i.imgur.com/gqERX1H.jpg)

**Comment by Bildo** [comment]
Thunderlord Dire Wolves are neutral ;p

**Comment by Tj20** [comment]
Yes, their behaviour is neutral, but their name plates / names are red, which indicate hostile behaviour. So either their behaviour or their nameplates/names seem to be wrong.

![red name plates, neutral behaviour](http://i.imgur.com/Dg5cu6g.jpg)

**Comment by Bildo** [comment]
ohh wowhead says that they should be neutral

**Comment by Bildo** [comment]
fixed
