### ISSUE TITLE
[PL][Raid-Cataclysm] Conclave of Wind HC

### ISSUE THREAD

**Issue by iskk** [Atlantiss/BugTracker#1453]
1. Po zmianie platformy z Rohash'a na Nezira i powrocie po ultimate na Rohash'a występuje wow error (kilka prób za każdym razem wow exe u kilku różnych osób). Cache czyszczone.
2. Rohash bije z melee w melee dpsów z aggro a nie powinien.

http://www.wowhead.com/npc=45870/anshal
http://www.wowhead.com/npc=45871/nezir
http://www.wowhead.com/npc=45872/rohash

Prawdopodobny winowajca: http://www.wowhead.com/spell=86193/wind-blast http://www.wowhead.com/spell=87770/wind-burst

Errory z wczoraj: https://drive.google.com/file/d/0B6KCElpTqq7wMGs3U2VIR3NBdFk/view?usp=sharing

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/869

Dubel

**Comment by iskk** [comment]
Gdzie Ty tu widzisz dubel oO

**Comment by Bildo** [comment]
no wlasnie xd ?

**Comment by Varchord** [comment]
No 2 raporty o conclavie to wcale nie jest dubel. Lepiej nowy robic niż w istniejącym dopisac

**Comment by Wojmistrz** [comment]
@Varchord Ty w ogóle powinieneś przestać pier..... na tym BT na prawdę...... i jak to Jenova czy też Wolf napisał że lepiej pisać NOWY issue niż komentować jakieś stare bądź otwarte wcześniej. Ogarnij się.

**Comment by Bildo** [comment]
Varchord jak juz chcesz aby byl 1 raport na 1 inste to kopiuj inne zgloszenia do swojego tak aby wszystko bylo w 1 miejscu a nie walalo sie po komentarzach

**Comment by Varchord** [comment]
Toz w moich zgloszeniach wszystko co jest w komentarzach jest w głównym poście. Gdybyś ten temat zamknął a w oryginalnym poście znajdowałby się link do wydruku errora to znalazłoby się to zaraz u mnie

**Comment by Dziara** [comment]
Crash przypuszczalnie jest związany z umiejętnością Wind Blast Rohasha http://www.wowhead.com/spell=85480/wind-blast . W naszym raidzie crashe zdarzały się, gdy ktoś, zaraz po przyleceniu z platformy Nezira, wpadał w w/w spell.

**Comment by mrkariox** [comment]
^ dokladnie to powoduje bug.

**Comment by iskk** [comment]
Update zgłoszenia

**Comment by Kejmil** [comment]
to ogolnie bug globalny ze "zmiana pozycji" + knockbackiem, death grip + thunder storm = error, szarzujacy warrior tez by pewnie sprezentowal wszystkim niespodzianke gdyby cos go odepchnelo w jej trakcie

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3636
