### ISSUE TITLE
[PL][glyph][paladin] glyph of divinity

### ISSUE THREAD

**Issue by Holywhisper** [Atlantiss/BugTracker#1456]
http://cata.openwow.com/spell=54939

jak w linku, po uzyciu powinno zwrocic paladynowi 10% maksymalnej many, aktualnie nie zwraca jej w ogole, przynajmniej dostepne metody wzrokowego pomiaru przyrostu many nie pozwalaja zauwazyc jakiejkolwiek korzysci majacej wynikac z tego glyphu.

recount potwierdza, brak jakiegokolwiek regenu many z loha

**Comment by Wolffenstein** [comment]
Fixed in rev 4227.
