### ISSUE TITLE
[EN][Quest][Deepholm] Petrified Delicacies

### ISSUE THREAD

**Issue by Xaedric** [Atlantiss/BugTracker#1457]
In this quest, Shalehide Basilisks (http://www.wowhead.com/npc=43181) are missing, also there is no bat gameobject to loot Petrified Stone Bat from them. (http://www.wowhead.com/spell=80952).

Wowhead link: http://www.wowhead.com/quest=26507
Video from Retail: https://www.youtube.com/watch?v=TUUhD5VlJ1E

**Comment by MorbidMike** [comment]
This quest can be completed by killing Shalehide Basilisks http://www.wowhead.com/npc=43181/shalehide-basilisk which are a bit more to the north, close to Terrath the Steady.

**Comment by Bildo** [comment]
THey are a lot of Petrified Stone Bat and also you can find Shalehide Basilisks

**Comment by Simgiov** [comment]
Can't find any petrified stone bats, and the basilisks spawn in a very small group to the north of where the quest should be done. This needs a fix.
