### ISSUE TITLE
[EN][Spell][Mage] Dragon's Breath breaking on Flame orb and Living Bomb explosion

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#146]
Dragon's Breath breakes on Flame orb ticks and Living Bomb explosion but it shouldn't. It should still attack and do damage to targets affected by Dragon's Breath as it does. When it comes to Flame Orb Explosion I just have no idea how it should work.

http://cata.openwow.com/spell=31661 // Dragon's Breath
http://cata.openwow.com/spell=44457 // Living Bomb
http://cata.openwow.com/spell=82731 // Flame Orb

**Comment by Wolffenstein** [comment]
Fixed in rev 4237.
