### ISSUE TITLE
[PL][Other]  Slayer of Stupid, Incompetent and Disappointing Minions

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1460]
http://www.wowhead.com/title=188#comments

Tytuł powinien się zrobić nieodstępny bo zejściu debuffa [Master Adventurer Award](http://www.wowhead.com/spell=89798#comments). Aktualnie tytuł mamy na stałe

**Comment by qubuslabadz** [comment]
Fixed in rev. 4236
