### ISSUE TITLE
[PL][PROFESSIONS][INSCRIPTION]Brak możliwości nauczenia nowych glyphów

### ISSUE THREAD

**Issue by Fuckedmywayuptothetop** [Atlantiss/BugTracker#1461]
Jak wiadomo na nowym patchu pojawiły się również nowe glyphy. Niestety, przy próbie użycia http://www.wowwiki.com/Northrend_Inscription_Research w przypadku, gdy posiadało się wszystkie recepty na poprzednim patchu, nadal pojawia się komunikat "Nothing left to discover".

**Comment by iskk** [comment]
Ja się nauczyłem niedawno glypha na lightning bolta w biegu i na zmianę shadow formy. Jakiego glypha Ci brakuje?

**Comment by Drutmaster** [comment]
Nowe glyphy z cata odkrywasz przy pomocy Minor Inscritpion Research, a nie Northrend.

**Comment by Fuckedmywayuptothetop** [comment]
W takim razie wszelkie źródła kłamią, bo daleko nie szukając http://wow.gamepedia.com/Glyph_of_Unleashed_Lightning , "discovered through  [Northrend Inscription Research]."

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
