### ISSUE TITLE
[PL][Talent][Warlock] Everlasting Affliction

### ISSUE THREAD

**Issue by Zak1** [Atlantiss/BugTracker#1462]
http://cata.openwow.com/spell=47203
Generalnie dzięki Everlasting Affliction nasze Drain Soul powinno zawsze odnawiać nasze Corruption, niezależnie ile target ma hp. Obecnie działa tak, że DS nie odnawia Corruption, gdy target ma więcej niż 25% hp oraz odnawia Corruption (poniżej 25%) tylko kiedy zaczynamy castować DS, a powinien co każdy tick, tak samo jak w przypadku talentu Pandemic i Unstable Affliction.

Dla potwierdzenia: http://youtu.be/hmDcc6G4o_Q?t=4m58s

**Comment by Wolffenstein** [comment]
A Drain Life i Haunt poprawnie odświeżają Corruption?

**Comment by Wolffenstein** [comment]
Fixed in rev 4227.
