### ISSUE TITLE
[EN][Quest][Western Plaguelands] I'm Not Supposed To tell you this.

### ISSUE THREAD

**Issue by Hacker--x** [Atlantiss/BugTracker#1464]
http://www.wowwiki.com/Quest:I%27m_Not_Supposed_to_Tell_You_This
Not spawning the ghost wolf in the area specified to drop the hunting sword and thus cannot complete this chain quest

**Comment by Varchord** [comment]
I've done this quest week, two weeks ago

**Comment by Hacker--x** [comment]
Hmmm ok will look closing for now then

**Comment by cosminush** [comment]
that npc http://www.wowhead.com/npc=45450/the-lone-hunter have spawn time too long or it is under map, donno, npc isnt here.
