### ISSUE TITLE
[PL][Vashj'ir][Rare Mob] Poseidus

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#1465]
Witam!

Odkąd na naszym serwie można w miarę swobodnie zwiedzać Vashj'ir, rozpocząłem poszukiwania Poseidusa (http://www.wowhead.com/npc=50005). U nas najprawdopodobniej nie jest on wgrany. Jest to rzadki konik morski, który ma 100% szansy dropa mounta po ubiciu (http://www.wowhead.com/item=67151). Według komentarzy powinien się odradzać w przedziale od 72-120 godzin i w wyniku restartów serwera. Sam mount jest BoE (to znaczy, że można nim handlować) i może być użyty w jakimkolwiek wodnym środowisku (nie tylko w Vashj'ir). Prosiłbym o dodanie tego moba.
Z góry dziękuję!

Rev. 4224

**Comment by Bildo** [comment]
fixed in rev. 4274
