### ISSUE TITLE
[EN][NPC] Reagan Mancuso

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1466]
What is not working:
=============

She's selling the same gems twice or more.

---------------
How should work:
=============

She should only sell "one of a kind".

----------------------
More info:
=============

Before Cataclysm, there were gems of Spell Power, Attack Power, Armor Penetration, etc...
Now, instead of getting removed, they got converted (e.g.: SP to Intelect), so, that's why you see copy of gems...

Anyway, there are for sure more NPCs like this, it worths to take a look in all of them.
[This might be helpful.](http://wow.gamepedia.com/Gem_vendors)

[Screenshot](http://i.imgur.com/3JZEyX3.jpg)
[Reagan Mancuso - WoWHead](http://www.wowhead.com/npc=22225)
[Reagan Mancuso - WoWPedia](http://wow.gamepedia.com/Reagan_Mancuso)

**Comment by Navedonar** [comment]
fixed
