### ISSUE TITLE
[PL][Talent][Hunter] Improved Serpent Sting

### ISSUE THREAD

**Issue by adryjan** [Atlantiss/BugTracker#1467]
Serpent Sting: http://cata.openwow.com/spell=82834
Serpent Spread: http://cata.openwow.com/spell=87934
Multi Shot: http://cata.openwow.com/spell=2643

Bug polega na tym że improved serpent sting czyli instant 30% dmg z doty wchodzi więcej razy niż powinien. 
JAK POWINNO DZIAŁAĆ: Przykładowo przy użyciu multi shot'a raz, na 3 targety przy talentach do których podałem linki wyżej powinien wejść 3 razy, bo multi rozrzuca na te targety 3 serpent stingi (skrócone ofc).
JAK DZIAŁA U NAS: Multi shot trafił 10 razy, 10 razy zaaplikował Serpent Sting, natomiast Improved Serpent Sting zadał dmg 23 razy. 
SS: http://pl.tinypic.com/view.php?pic=16ht477&s=8#.VLEwrdKG8kA

Wynikiem jest kosmicznie przesadzony AoE dmg hunterów Survi. Niestety nie mam pojęcia w jaki sposób generują się te dodatkowe proce talentu ale średnio wchodzi ponad 2 razy więcej proców niż być powinno.

**Comment by Howlingwolf** [comment]
Faktycznie. :/  Duplikacja nie występuje podczas strzelania z multi w jeden target. 2+ juz tak.

**Comment by adryjan** [comment]
Nam podczas testów udało się zaaplikować 2 razy z jednego targetu multi shota ale to jest dosyć losowe przy jednym targecie.

**Comment by Howlingwolf** [comment]
Z jakiegoś dziwnego powodu im więcej celów tym więcej razy odpala się talent. Sądzę, że przy 500 celach mozna było by zyskać grubo ponad 5 tysięcy instantowych nałożeń. Przy małych liczbach bug jest znośny, ale im dalej w las... 
Testowaliście już to w pvp? Może być kluczowe zwłaszcza podczas walk w TB. Wyobraźcie sobie, że hunter trafia 50 graczy, i każdy dostaje dmg czterokrotnie.

**Comment by Asavel** [comment]
nie trafi 50 graczy bo limit na tb jest 40 ;D

**Comment by kadi2** [comment]
40 hunterow z odpalonymi snake trapami ;s

**Comment by nerv234** [comment]
Jesteście pewni że liczycie aplikacje improved ss zamiast ticków?

**Comment by Wolffenstein** [comment]
Fixed in rev 4306.
