### ISSUE TITLE
[EN][QUEST][BURNING STEPPES] A Perfect Costume

### ISSUE THREAD

**Issue by Razor254** [Atlantiss/BugTracker#1468]
http://www.wowhead.com/quest=28204
It's about the quest [A Perfect Costume] from the town Chiselgrip in Burning Steppes given by Thelaron Direneedle. I tried all the possible combinations, even searched on the internet for the gnome combination for the disguise  but it didn't work. After i take the mats from his table and i want to talk to him to give in I cannot. Nothing appears there for completing my disguise. Please help me I even made a ticket for this because it unlocks other quests and if I do not complete it I cannot level anymore ! Waiting for reply.

**Comment by Wolffenstein** [comment]
Fixed in rev 4227.
