### ISSUE TITLE
[EN][NPC] Dragonblight Mage Hunter

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1469]
What is not working:
=============

This NPC is not using any ability, just simply attacking.

---------------
How should work:
=============

It should be using abilities...

----------------------
More info:
=============

This NPC plays a role in the quest "[Avenge this Atrocity!](http://www.wowhead.com/quest=12006)"

[Screenshot](http://i.imgur.com/IqsvrTH.jpg)
[Video](http://youtu.be/c4_XZMCJaos)
[Dragonblight Mage Hunter - WoWHead](http://www.wowhead.com/npc=32572)

**Comment by Bildo** [comment]
fixed in rev 4240
