### ISSUE TITLE
[EN][NPC] Focus Wizard

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1470]
What is not working:
=============

This NPC is not using any ability, just simply attacking.

---------------
How should work:
=============

It should be using abilities...

----------------------
More info:
=============

This NPC plays a role in the quest "[Avenge this Atrocity!](http://www.wowhead.com/quest=12006)"

[Screenshot](http://i.imgur.com/rNSw2Lw.jpg)
[Focus Wizard - WoWHead](http://www.wowhead.com/npc=26816)

**Comment by Bildo** [comment]
fixed in rev 4240
