### ISSUE TITLE
[EN][NPC] Elder Nurgen

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#1471]
What is not working:
=============

Currently, you can see this NPC, even when Lunar Festivial is off.

---------------
How should work:
=============

Elder Nurgen should only be available (visible) when Lunar Festival event is on.

----------------------
More info:
=============

[Screenshot](http://i.imgur.com/bQC86GC.jpg)
[Elder Nurgen - WoWHead](http://www.wowhead.com/npc=30533)

**Comment by Bildo** [comment]
fixed in 4248
