### ISSUE TITLE
[PL]nie da się zrobic acigmentu skyshattered [outland] 

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1474]
po prostu pierwszego q nieda sie wykonać czyli pierwszego wyścigu
http://www.wowhead.com/achievement=1638
http://www.wowwiki.com/Quest:Dragonmaw_Race:_Captain_Skyshatter
to ten quest
http://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold

**Comment by Bildo** [comment]
zasady bugtrackera

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
