### ISSUE TITLE
[PL][Death Knight] Blood of The North 

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1475]
http://cata.openwow.com/spell=54637

Buguje się po śmierci i daje blood runy bez możliwości zamiany. Pomaga respec

Jak zreprodukowałem?
1. Lecimy do BWD, atakujemy trash
2. Zużywamy wszytkie nasze runki
3. Umieramy z runkami na CD
4. Ressamy się w BWD
5. Runki są blood

Co ciekawe jeśli umrzemy z blood runkami (bez cd) staną się one na powrót death
Wyjście z BWD też przywraca runki do postaci death

http://i.imgur.com/ZI3wAXw.jpg

**Comment by Varchord** [comment]
Wygląda na to, że buguje się to po śmierci w instancjach. Podczas duela zabiłem się poprzez falling damage z runkami na cd ale nie zmieniły się one na blood

**Comment by Kejmil** [comment]
bug nadal wystepuje

**Comment by Varchord** [comment]
Merged with https://github.com/Atlantiss/BugTracker/issues/444#issuecomment-69742942
