### ISSUE TITLE
[PL][Druid][Talent] Master Shapeshifter

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1476]
http://cata.openwow.com/spell=48411

Po ostatnim fixu możliwe jest stackowanie tej aury w wersji "caster form" czyli zwiększania healing done

Zmieniając ciągle formy np pomiędzy bear/cat i caster formą stackujemy aurę i robimy coraz większy healing.
W feral talentach i gearze doszedłem z lifebloom o wartości 141 na tick do 8500 na tick. Słyszałem o graczach na bg z 41k na tick

Nie posiadam talentu Nurturing Instinct i jestem 100% pewien, że to master shapeshifter. Proszę o szybki fix zanim się znów płacz zacznie

**Comment by Varchord** [comment]
Ale na tyle wolny żebym sobie BoT HC wysolował xD

Stackuje się najpewniej addytywnie, nie multiplikatywnie
Zostaje po śmierci

**Comment by Varchord** [comment]
O nie! Wolff już przyszedł, a ja dopiero halfusa hc zabiłem :/
Relog usuwa stacki

**Comment by Wolffenstein** [comment]
Fixed in rev 4230.
