### ISSUE TITLE
[EN][Quest][Starting Zones] auto-accept of follow-up quests in starting areas seems strange

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1477]
In starting areas I've found that follow-up quests are automatically accepted. (This behaviour I find strange in itself, because surely you'd want to read a quest text so you know what you have to do before you accept it...? But I'm not sure if this is blizzlike.)

However, the game still presents the quest text of the follow-up quest to you, and you still can click "accept". This buttons doesn't seem to do anything though, because the game has already accepted the quest for you.

Now this is where different starting areas treat this "double quest accept" differently:

1. Draenei Zone:
An error sound is played and you get the error message: "You are already on that quest".
(This is what made me curious, because I got a lot of sad "Duh-Duuuuuuuhhhh!" error sounds in the Draenei starting area and I was wondering why.)

Examples:
- [You survived](http://www.wowhead.com/quest=9279/you-survived) -> [Replenishing the Healing Crystals](http://www.wowhead.com/quest=9280)/ [Replenishing the Healing Crystals](http://www.wowhead.com/quest=9369)
- [Botanist Taerix](http://www.wowhead.com/quest=9371) -> [Volatile Mutations](http://www.wowhead.com/quest=10302) -> [What Must Be Done](http://www.wowhead.com/quest=9293)
- [The Missing Scout](http://www.wowhead.com/quest=9309) -> [The Blood Elves](http://www.wowhead.com/quest=10303)
![Draenei](http://i.imgur.com/mt7EnOn.jpg)

2. Undead Starting Area:
Although technically the same is happening, you get no error sound and in chat you get the message "Quest accepted". You can click the accept button again however if you like, it doesn't make any difference.

Example:
- [Fresh out of the Grave](http://www.wowhead.com/quest=24959) -> [The Shadow Grave](http://www.wowhead.com/quest=28608)

![Undead](http://i.imgur.com/KItGfUp.jpg)

**Comment by Wojmistrz** [comment]
in all starting zones for races and not only on atlantiss server quests are automaticly taken when You speak to quest giver (about 5-7 quests are like that if i am correct). Though i don't know about retail how it was there with that.
NOTE: who read quest text :D

**Comment by Aldurion** [comment]
According to wowhead comments, the quest Botanist Taerix  (http://www.wowhead.com/quest=9371/botanist-taerix#comments) must be available only after you turn in the quest Urgent Delivery! (http://www.wowhead.com/quest=9409/urgent-delivery). You can take the quest Botanist Taerix regardless of prerequisite. Also the X button on the upper right is grayed out so yeah, you are forced to accept the quest if you talk to the NPC.

**Comment by Aldurion** [comment]
The X button on the upper right of the chat window with NPC  is grayed out so you are forced to accept the quest if you talk to the NPC.

**Comment by BAndysc** [comment]
Fixed in 5097 :)
