### ISSUE TITLE
[PL] [Core] [Druid] [Critical] Feral heals

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#1479]
W secie PvP i z talentami Feral healuje się po 60k (bez cryta) z HT i po 2-4k tick z lifeblooma.

Z błędem nie jest powiązany żaden spell, a kalkulacja Healing Power.

Prawdopodobnie efekty zwiększające bazowe staty, spell power lub inne bufy będą pogłębiały buga.

W tej chwili nie jestem w stanie określić co dokładnie powoduje takie działanie, jednak wraz z czasem heale powiększają się sukcesywnie w nieskończoność.

Screen:
![wowscrnshot_011015_210227](https://cloud.githubusercontent.com/assets/6035437/5693027/0d05bc8c-990c-11e4-88fd-d54b27fc63f5.jpg)

Błąd jest zatem krytyczny i bardzo proszę o zbadanie tego zajścia zaczym ktoś mi urwie głowę.

PS prawdopodobnie ma to związek z krótkotrwałymi bufami (głównie na agility).

PS2 po relogu wszystko wraca do normy.

**Comment by Asavel** [comment]
Dubel #1476

**Comment by Varchord** [comment]
Ehh. Żaden spell nie ma skopanej kalkulacji HP
https://github.com/Atlantiss/BugTracker/issues/1476

**Comment by Kuszki** [comment]
Wybaczcie, jednak wyszukiwarka nie znalazła podobnych do mojego zgłoszeń, a z uwagi na wagę błędu postanowiłem dodać własne.
