### ISSUE TITLE
[PL][Death Knight] Raise Dead and Talent Reset

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1481]
Jeśli jesteśmy unholy dk z przywołanym ghoulem to po resecie talentów i zmianie np na frost czy blood zostaje nam pet z unholy.
To znaczy ma nieskończony czas trwania oraz dodatkowe umiejętności

http://cata.openwow.com/spell=46584

Dodatkowo możemy przywołać regularnego ghula i mieć oba na raz

**Comment by Jenovas** [comment]
Fixed in rev 4358
