### ISSUE TITLE
[PL][NPC][Drak'Tharon Keep] Risen Drakkari Bat Rider

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#1482]
Witam!
Występuje problem w Drak'Tharon Keep, mianowicie mob o nazwie Risen Drakkari Bat Rider nie jest to ztargetowania. Problem występuje na wersji heroic.

http://www.wowhead.com/npc=26638

SS:
http://s1304.photobucket.com/user/dementor_111/media/WoWScrnShot_011015_115922_zpsbfde72a2.jpg.html

**Comment by Bildo** [comment]
fixed in rev 4240
