### ISSUE TITLE
PL[Guild][item] Kotła z flaszkami nie mogę wsadzić do gb.

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1487]
http://www.wowhead.com/item=62288/cauldron-of-battle
Nie wiem czy to bug ale było by to  bardzo mało użyteczne, alchemicy (albo ich alty) musieli być na każdym raidzie bo nie da się wsadzić kotła do gb albo coś mi się bugneło z gb :P 
http://wrzucaj.net/image/4BG

**Comment by Varchord** [comment]
Kotly sa boa.
Do zamkniecia

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by arekczup** [comment]
Moim zdaniem to jest bez sensu, powinny należ do całej gildii, ponieważ po co coś  robić dla gildii jeśli  nie mogę się podzielić z innymi członkami gdy mnie nie ma w grze.Tylko ja mogę to odpalić online To już nie nasz problem lecz   Blizzarda.

**Comment by nerv234** [comment]
Zalety bycia alchemem, pretensje do blizzarda możesz złożyć.
