### ISSUE TITLE
[EN][NPC] Chosen Zealot

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1493]
The respawn time of these NPCs are very high, they should should respawn roughly 90 seconds after being killed. At the moment they seem to respawn 7 minutes after being killed and fully looted. There are also 7 mobs in the area, which have a respawn time different from the rest. Here are two screenshots of the questionable mobs:
http://i.imgur.com/BK4jJYd.jpg
http://i.imgur.com/BoHYoy6.jpg

Chosen Zealot: http://www.wowhead.com/npc=32175

**Comment by Bildo** [comment]
fixed in rev 4240
