### ISSUE TITLE
[PL][Battleground][Buffs] Power-ups and Stealth

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1496]
Stealth: http://cata.openwow.com/spell=1784
Invisibility: http://cata.openwow.com/spell=66
Prowl: http://cata.openwow.com/spell=5215

Kiedy próbujemy wziąć jeden z poniższych buffów na bg/~~arenie~~ będąc niewidzialnym (Stealth, Invisibility, Prowl) nie dostajemy go, jednak "buff" znika z ~~areny~~/bg tak jakby został wzięty. Powinno się go normalnie dać zebrać bez wyrzucania z efektu niewidzialności.

Buffy:
~~Shadow Sight (Arena): http://www.wowhead.com/spell=34709/shadow-sight~~
Berserking (BG): http://www.wowhead.com/spell=23505/berserking
Restoration (BG): http://www.wowhead.com/spell=132958
Speed (BG): http://www.wowhead.com/spell=23451

**Comment by blinkmaster** [comment]
shadowsight dziala inaczej niz buffy z bg. zeby zabrac shadowsight trzeba wyjsc ze stealth/invi i dopiero wtedy mozna go zabrac i znow dac stealth/invi, dziala to tak od poczatku s2. kiedys bylo jeszcze tak, ze ten shadowsight zadawal odrobine damage ale to o ile pamietam cofneli na wotlku. reszta jest faktycznie bugged.

**Comment by Arcadia713** [comment]
Dzięki za info, poprawiłem.

**Comment by sshad00w** [comment]
Tak samo jest z camouflage u huntera.
http://www.wowhead.com/spell=51753/camouflage

**Comment by Jenovas** [comment]
Fixed
