### ISSUE TITLE
[EN][Druid][Spell] Unlimited Ravages

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1498]
Using a macro you're able to have an unlimited amount of Ravages, while out of stealth. The way it works is you first Feral Charge (Cat) once, to gain the Stampede buff, and from that point on you have access to Ravage the whole time. To write it in other words, after you've gained the Stampede buff, it visually gets consumed by the first Ravage, but you continue having the benefits of Stampede no matter how many times you've used Ravage. The benefits of Stampede are being able to use Ravage while out of stealth and having no positional requirement, but the skill still costs 60 energy. Here's the macro:
#showtooltip
/cast [nostealth] Ravage!
/cast [nostealth] Shred
/cast [stealth] Ravage

Stampede: http://cata.openwow.com/spell=78893
Ravage: http://cata.openwow.com/spell=6785

**Comment by Wolffenstein** [comment]
Fixed in rev 4320.
