### ISSUE TITLE
[EN][HUNTER][Talent] Master Marksman

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#15]
http://cata.openwow.com/spell=82925
http://cata.openwow.com/spell=34485
http://cata.openwow.com/spell=34486
http://cata.openwow.com/spell=34487
After reaching 5 stacks of Master Marksman every single shot despite the auto shot removes Instant Aimed S. buff.

**Comment by Wulgarny** [comment]
aaaaand BUMP again. I dont want o rush You, but its pretty important talent for hunters :)

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
