### ISSUE TITLE
[PL][Other] Transmog

### ISSUE THREAD

**Issue by Zlo-** [Atlantiss/BugTracker#150]
Istnieje błąd dzięki któremu możemy transmogować każdą broń i każdy armor jak nam się tylko podoba, np. bronie 1h na 2h :) http://i.imgur.com/Gyg3MFu.jpg
Filmik: http://youtu.be/yTScyjJDjLI
Jak powtórzyć błąd:
1. Zapisujemy przedmiot który chcemy zmienić w equipment menagerze i przypisujemy go do klawisza.
2. Zamieniamy przedmiot na taki, który można transmogować na to co chcemy.
3. Transmogujemy podmieniony przedmiot na ten który chcemy.
4. Jednocześnie wciskamy 'apply' oraz zbindowaną zmianę eq.
5. Profit

**Comment by Jeakerek** [comment]
Witam, W moim przyadku działa tylko i wyłącznie Sword - axe (2h na 2h i 1h na 1h) Natomiast xsmog 1h na 2h, one-hand na main hand... nie. Robie coś źle? :)
