### ISSUE TITLE
[PL][Druid][Talent] Balance of Power

### ISSUE THREAD

**Issue by Wyrafinowane** [Atlantiss/BugTracker#1500]
Bonus dodający hit rating ze spirit nie działa. Mając zbroję +193hit rating mam +7.47% na trafienie. Ze zbroją bez hit rating za to z +202 spirit szansa na trafienie spada do +5.83%. Bez żadnej zbroi szansa jest taka sama jak ze zbroją +202 spirit.
http://cata.openwow.com/spell=33596 Rank 1 
http://cata.openwow.com/spell=33592 Rank 2

**Comment by Bildo** [comment]
linki do wowheada

**Comment by Wyrafinowane** [comment]
http://www.wowwiki.com/Balance_of_Power daję do wowwiki bo na wowhead talent jest następnego dodatku i działa inaczej. Zmiana z 4.0.6 dla talentu nie działa.

**Comment by Bildo** [comment]
juz dalem linka za ciebie...

**Comment by Wolffenstein** [comment]
A sprawdziłeś, czy to nie jest tylko bug wizualny w statystykach?

**Comment by Varchord** [comment]
Kazać człowiekowi tak na druida wchodzić

Talent działa idealnie.
Mam
1407 spiritu
336 czystego hita z itków
Łączny spell hit rating 1743 = 17.01 %

Do zamknięcia
