### ISSUE TITLE
[PL][Profession][Engineering] Nie można wykonać q na Gnome Engineering

### ISSUE THREAD

**Issue by kleofasa** [Atlantiss/BugTracker#1501]
Wziełam questa na Gnome Engineering tj, Quest:Gnome Engineering z Undercity. Quest wysłał mnie do Booty Bay z "Manual of Engineering Disciplines" do Oglethorpe Obnoticus, trenera inżynierii, gdzie kończy się owy quest. Problem w tym że NPC nie dał mi kontynuacji questa, przez co nie jest możliwe zrobienie rozszerzenia inżynierii na gnomią.

http://www.wowhead.com/quest=3635/gnome-engineering
http://www.wowwiki.com/Oglethorpe_Obnoticus

**Comment by Varchord** [comment]
Linki wowhead
Nie krzycz

**Comment by kleofasa** [comment]
Nie krzyczę -___-

**Comment by NONLIFE** [comment]
Twoj temat sugeruje ze krzyczysz 

to jest stary q ktory jeszcze jest w grze 
http://www.wowhead.com/quest=3635/gnome-engineering

a to jest nowy 
http://www.wowhead.com/quest=29477
ktorego nie ma

**Comment by kleofasa** [comment]
jest w grze ale nie działa :)

**Comment by Bildo** [comment]
zeedytuj pierwszy post albo zamknij ten i zrob nowy
