### ISSUE TITLE
[EN][Qest] They grow up so fast [Un'Goro]

### ISSUE THREAD

**Issue by nenormalen** [Atlantiss/BugTracker#1505]
Hello there!
I've finished the quest line [They Grow Up So Fast] in Un'Goro and collected 20 teeth from the 	"Venomhide Hatchling" and also bought 20 Runecloth and 20 Rugged Leather and it shows me in the quest log that quest is finished/completed. But when I got to the npc (Mor'vek) it shows me silver questionmark and when I interact with him the "continue" button is grey/innactive. I would be very thankful if there is solution.
Thank you in advance!

**Comment by Bildo** [comment]
wowhead links

**Comment by nenormalen** [comment]
Here is the quest  http://www.wowhead.com/quest=13906/they-grow-up-so-fast  and here is the npc from which i should collect teeth http://www.wowhead.com/item=46362  i completed the dayly quests and after completing them had to return the quest to http://www.wowhead.com/npc=11701 and get the mount http://www.wowhead.com/item=46102 but the continue button on the quest to complete it is grey and not allowing me to complete it and get the mount.

**Comment by Drutmaster** [comment]
Just retake quest, it should help

**Comment by Angelo-DM-** [comment]
This quest require you 80g... maybe you don't have money! ;)

**Comment by nenormalen** [comment]
I have over 2k gold :) ok I will retake it.

**Comment by Bildo** [comment]
so it's working or nah ?

**Comment by nenormalen** [comment]
Yes... it is working! I've retook it now and it is working without problem! Thanks for the advice!

**Comment by Drutmaster** [comment]
No problem mate :)
