### ISSUE TITLE
[EN][Spell] enemy's spells colors

### ISSUE THREAD

**Issue by lastkiss** [Atlantiss/BugTracker#1507]
Enemy's Flare http://cata.openwow.com/spell=1543 and Smoke Bomb http://cata.openwow.com/spell=76577 should be "red coloured" on 4.3.4 patch but they are not

http://patrz.pl/filmy/hunter7373 // http://patrz.pl/filmy/rogue128131

It should be like: https://www.youtube.com/watch?v=RpmG0AD2-VU 0:30 // 1:18

**Comment by kadi2** [comment]
It works pretty fine with Ring of Frost. Was recently fixed by someone.

**Comment by kadi2** [comment]
It should be applied to Wild Mushrooms too.

**Comment by Astrobazooka** [comment]
Enemey's wild mushroom and fungal growth should be "red coloured" too.
Openwow links:
http://cata.openwow.com/spell=78777
http://cata.openwow.com/spell=78788

**Comment by crosik** [comment]
BUMP for this

**Comment by Navedonar** [comment]
.

**Comment by lamaATS** [comment]
Fixed in rev. 5232
