### ISSUE TITLE
[PL][Quest]"Gelkis Alliance"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1509]
Ten quest nie powinien zostać usunięty? Nie ma NPC końcowego - Uthek the Wise                                  ( http://www.wowhead.com/npc=5397/uthek-the-wise ).

Link: http://www.wowhead.com/quest=1368/gelkis-alliance

**Comment by Bildo** [comment]
fixed in rev 4245

**Comment by Danelar** [comment]
Oczywiście :)
