### ISSUE TITLE
[PL][Server Atlantiss]"Brak możliwości wejścia na witrynę"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1510]
Gdy wchodzę na stronę to wyskakuje komunikat: "Ta strona internetowa zawiera pętlę przekierowań"

**Comment by Asavel** [comment]
A czytałes Info na stronie było napisane że beda jakies tam prace i zamknieta bedzie

**Comment by Malylolek** [comment]
Był news o tym że będzie nieczynna, i problem jest tylko na .pl

.eu działa dobrze

**Comment by Danelar** [comment]
ale inni mogli gdy an chacie pisałem :|
