### ISSUE TITLE
[PL][NPC][Drak'Tharon Keep] Drakkari Guardian

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#1511]
Witam!
Ciąg dalszy błędów na Drak'Tharon Keep. Mob o nazwie Drakkari Guardian nie może być targetowany (ale także nie atakuje, tylko stoi, jakby był teksturą). Problem występuje na normalu i heroicu.

http://www.wowhead.com/npc=26620

SS:
http://s1304.photobucket.com/user/dementor_111/media/WoWScrnShot_011115_184515_zpsd7508388.jpg.html

**Comment by Bildo** [comment]
fixed in rev 4245
