### ISSUE TITLE
[PL][Talent][Mage] Fire Power / Flame Orb

### ISSUE THREAD

**Issue by Shainear** [Atlantiss/BugTracker#1512]
http://cata.openwow.com/spell=54734
http://cata.openwow.com/spell=82731
Zdaje się, że update do Flame Orba już wszedł (miał wejść z revem 4242, a na serwerze jest 4244).
Flame orb zadaje już jakiś dmg z eksplozji z talentu Fire Power, ale:
1) jest bardzo mały, na procach przy 10 k SP uderzył za 1200. Bez proców przy 7400 SP uderzyła za 1150 - pewnie eksplozja nie ma poprawnego coeffu.  Wg simcrafta eksplozja Flame Orba postaci posiadającej około 7800 SP powinna bić minimalnie po 4073.
2) missuje mimo posiadania hit capa
3) nie crituje (a powinna) 
http://oi61.tinypic.com/2133tzb.jpg

**Comment by Shainear** [comment]
Do tego kwestia kosmetyczna: wybuchowi Orba powinien towarzyszyć efekt graficzny eksplozji, podobny temu, który ma Living Bomb. https://www.youtube.com/watch?v=qArci35dHjU około 20 sekundy widać animację wybuchu dwoch Flame Orbów. Tymczasem na Atlantissie Orb po prostu znika i nie towarzyszy temu żaden dodatkowy efekt. 
Z tego co zauważyłem eksplozja jest też identyfikowana np przez recount jako atak peta 'Flaming Orb' podczas gdy sam Orb nie jest petem, a zwykłym spellem. Być może z tego biorą się wyżej wspomniane problemy, bo sama eksplozja powinna mieć taką samą szansę na crit i taki sam coeff jak sam Flame Orb, podczas gdy zachowuje się jak zupełnie inny spell.

**Comment by Shainear** [comment]
I jeszcze jedna rzecz, dotyczy Flame Orba, ale jest to osobna kwestia i jeśli mam ją zgłosić w osobnym temacie to proszę o informację. 
Flame Orb powinien atakować najbliższy target, ale zasięg w którym sprawdza czy jest jakiś jest bardzo mały. Właściwie trzeba go używać bezpośrednio przy jakimś targecie żeby zaczął coś bić, a na bossach takich jak Sinestra (i spodziewam się, że magmaw), gdzie nie można podejść bardzo blisko flame orb jest w ogóle bezużyteczny, bo gdzie by go nie użyć to po prostu stoi i nic nie robi, podczas gdy na filmikach z tego bossa widać, jak Orb normalnie podlatuje do Sinestry i zaczyna ją bić.

**Comment by Jenovas** [comment]
Fire Power fixed in rev  4293
