### ISSUE TITLE
[EN][QUEST][ITEM] Riding Training Pamphlet

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1514]
When you hit lvl 20, you should receive a mail with one of them inside:
http://www.wowhead.com/search?q=riding+training
but in the real you receive only the mail and not the item that begins one of thoose quests:
http://www.wowhead.com/quests?filter=na=learn+to+ride;cr=8;crs=4;crv=40304

**Comment by Aival94** [comment]
Removed on cata.
