### ISSUE TITLE
[EN][Web] Registration captcha not working

### ISSUE THREAD

**Issue by AlexBenic** [Atlantiss/BugTracker#1516]
I am pretty sure that registration captcha always returns false. I tried at least 10 times to register, used 2 different browsers, accessed the web site from different locations ( VPN ), tried all variations of captcha ( all caps, no caps ).

**Comment by Varchord** [comment]
http://atlantiss.eu/community/viewtopic.php?f=10&t=579

**Comment by Bildo** [comment]
Registration should nwo work
