### ISSUE TITLE
[ENG][Profession][Cooking] Undermine Clam Chowder can't be bought

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#1518]
"Chef" Overheat (http://www.wowhead.com/npc=48060/chef-overheat) doesn't sell the recipe for Undermine Clam Chowder. Mrs. Gant (http://www.wowhead.com/npc=54232#sells) has no selling dialog at all much less the mentioned recipe.

**Comment by Bildo** [comment]
fixed in 4248
