### ISSUE TITLE
[PL][Raid-Cata] Ascendant Council (Normal 10)

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#1519]
Wczoraj (11.01.14) jak zbilismy  Feludiusa i Ignaciousa do mniej wiecej 25 % ( jeden z nich mial ciut wiecej), wbilismy do 2 fazy z  Arionem i  Terrastrą, padlismy, i po wbiciu do insty boss sie nie zresetowal, tylko Felek i Ignacy stali na balkonach i mieli po ok 25 % hp ( tyle ile im zbilismy)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838


poza tym, jeśli mieliście affli locka to to jest normalne
