### ISSUE TITLE
[PL][SPELL/MECHANIC][MAGE] poly, a cone of cold (improved ) ; frost nova

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#1522]
danie "jednoczesnie" novy ( lub Cone of Cold) pod koniec castu sheepa powinno dawac nam debuffy i nie wyciagac targetu dmgem z sheepa,
https://www.youtube.com/watch?v=bK8Qw4ZXFJA 0.42 min:sec
https://www.youtube.com/watch?v=u7W75EXoev4 11:28 min :sec
w pvp robi to ogromna roznice bo pozwala na darmowe shattery na czystych castach.

**Comment by Arcadia713** [comment]
Problem był już kiedyś omawiany z Dev'ami i na privie nie ma takiej możliwości niestety. Na globie spelle mają większe opóźnienie i jedynym sposobem, żeby tak u nas było to zwiększenie "diffu" serwera :P

**Comment by blinkmaster** [comment]
hm nie zgadzam sie, widzialem servery gdzie takie opóznienie dziala ale o ile sie nie myle to jest ustawiane do danego spella ;) tak samo jak niektore servery czas "lotu" blinda nawet dodaja. niby to delay ale jest to bardziej blizzlike niz tego brak ;)

**Comment by kadi2** [comment]
Oczywiscie, ze jest mozliwosc zrekonstruowania czegos takiego. Bylo zglaszane kilka razy wieki temu. Administracja poprostu ma swoje powody dla ktorych nie chce tego wprowadzic.

**Comment by Arcadia713** [comment]
To musiałem źle zinterpretować wypowiedzi, chociaż jestem w 90% pewny, że któryś z Devów pisał o braku możliwości (na starym BT) :P
No nic może kiedyś się doczekamy :)

**Comment by blinkmaster** [comment]
nie no, jeżeli się nie da to się nie da, zgłaszam bo bug ;)

**Comment by kadi2** [comment]
Shadow Word: Death juz pewnie ma po czesci wgrany taki delay.

**Comment by Bildo** [comment]
Administracja od zawsze mówiła, że lagów z globa nie przenosimy. Jeśli coś się zmieniło w tej kwestii to niech któryś dev otworzy to.

**Comment by Jenovas** [comment]
Wszystko jest możliwe, ale nie będziemy pisać całych systemów pod to żeby do spella dodać 0.05 sec opóźnienia. To nie jest blizzlike, bo sam blizzard mówił że to są bugi spowodowane przez diff. Spell NIE MA tak działać, ale działał tak z powodu diffu. Tak samo Bladestorm na globie działał jak trinket przez opóźnienia, i tak był to bug, ale tak działało. Nie przenosimy bugów i opóźnień z globa.
