### ISSUE TITLE
[EN][QUEST] Respect for the Fallen

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#1523]
The item http://www.wowhead.com/item=45042 cannt be loted from npc.
http://www.wowhead.com/quest=13626/respect-for-the-fallen

**Comment by Aival94** [comment]
In order to loot this one you should stop be on phase(it is this way bugged).

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/670
