### ISSUE TITLE
[EN][Mage][Spell] Flame/Frostfire Orb breaks Blind, Sap etc.

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1524]
Frostfire Orb - http://cata.openwow.com/spell=84714
Flame Orb - http://cata.openwow.com/spell=82731
Blind - http://cata.openwow.com/spell=2094
Sap - http://cata.openwow.com/spell=6770

I should put that on previous issue (https://github.com/Atlantiss/BugTracker/issues/28) but my bad i didn't, so i made new one.
Flame/Frostfire Orb breaks targets from Blind and Sap aswell but it should ignore them (like with Polymorph right now - it works very well, thx). 
Screenshot with Blind: http://wstaw.org/m/2015/01/12/WoWScrnShot_011215_135814.jpg

Actually i don't know right now which spell should ignore too - Polymorph (works), Dragon's Breath (works), Blind (doesn't work), Sap (doesn't work) for sure. If someone know more of them please write.

EDIT:
I see on rev. 4238 there was fix "Frostfire Orb will no longer attack targets with Polymorph and similar auras", why it changed in rev. 4242 to "Flame and Frostfire Orbs will ignore only targets with polymorph"? I guess it was for Ring of Frost but this is only exception.

**Comment by kadi2** [comment]
So, it should never ignore Dragon's Breathed targets https://github.com/Atlantiss/BugTracker/issues/146
I already posted alot proof for this on the old bug tracker.

**Comment by Wolffenstein** [comment]
"The Orb will break any crowd control spells that are not [Polymorph]."

http://wow.gamepedia.com/Flame_Orb

**Comment by Arcadia713** [comment]
But is bug :( 
We want retail bug aswell? :D

**Comment by Wolffenstein** [comment]
Gamepedia is not Blizzard's official page, therefore it may be a bug for them, but it could be working as Blizzard intended, we don't know it. The fact is that it worked like that on 4.3.4 and we should stick to it.

**Comment by Wolffenstein** [comment]
http://youtu.be/u7W75EXoev4 ~11:50
Dragon's Breath targets SHOULD be skipped. So the spell is working fine, only Polymorph and Dragon's Breath targets are skipped, while targets with other crowd control effects are attacked. Closing the issue.

If you find proof that it should be working differently, please open a new ticket.

**Comment by kadi2** [comment]
![](http://bug.omfg.gg/attachments/download/563/Schermafbeelding%202014-01-10%20om%2014.06.14.png)

http://youtu.be/rPXue4sObxg?t=18m31s // Shamman getting hitted by Flame Orb in Dragon's Breath.

**Comment by kadi2** [comment]
By skipping, i just meant it's not attacking Dragon's Breathed targets. We can't even say if it's breaking from Flame Orb damage since it's not even attacking it. with recent changes on the main.

**Comment by Arcadia713** [comment]
So on Wolf's video Orb is attacking Dragon's Breathed target but on Kadi's video Orb changed target as soon as shaman got Breathed. WTF then? :D
