### ISSUE TITLE
[EN] [Guild]Guild Finder

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#1527]
( The Nemesis Order ) The guild finder is not working i have setup a guild recruitment for my guild and started a new char to test it out and its not working i have screenshots for it.

![buddy](https://cloud.githubusercontent.com/assets/4362814/5704762/f07abb10-9a39-11e4-9c00-8d8d53c874d9.jpg)
![wowscrnshot_011215_085719](https://cloud.githubusercontent.com/assets/4362814/5704691/6e96ab86-9a39-11e4-8f0b-efaf398ec8d4.jpg)
![wowscrnshot_011215_085723](https://cloud.githubusercontent.com/assets/4362814/5704692/6e9783bc-9a39-11e4-8a7f-b143ae399f70.jpg)

**Comment by Bud1980** [comment]
i have even ask other players levels 50+ to see if its on there and still nothing

**Comment by krecik88** [comment]
Oh boy.. i will look in to that

**Comment by Bud1980** [comment]
let me know when you get it fix i will test it

**Comment by krecik88** [comment]
Fixed in 4246
