### ISSUE TITLE
  [EN][Dungeon-Classic] Lower/Upper Blackrock Spire (LBRS/UBRS)

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1528]
http://www.wowhead.com/zone=1583/blackrock-spire , a follow-up of closed ticket [#1285](https://github.com/Atlantiss/BugTracker/issues/1285):

Well, the issue with the Dungeon Finder spawning you at the wrong dungeon entrance has been fixed... Sort of. Now you just spawn in the void and fall to your death.

![I believe I can fly...](http://i.imgur.com/2A4niWO.jpg)

edit: also tested UBRS... happens in both dungeons.

Couldn't release spirit afterwards, but /script RepopMe() helped.

**Comment by Bildo** [comment]
fixed in 4248
