### ISSUE TITLE
[EN] Character names with umlaut.

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#1530]
Impossible to mail to chracters with umlaut (ex. ä,Ŕ,ď, etc.). Every mail is lost, also we can't add them to friend list or ignore.

**Comment by BeVeR86** [comment]
The mail is actually not lost but the special character is replaced by the character without the sign for instance:
Mailing something to Hárry will send the item to Harry, or mailing something to Érïk will send it to Erik.

I really hope this gets fixed soon. Just a small suggestion, if this isn't easy to fix it might be a good idea not to allow the use of special characters in character names. (not a fix but will save you from people complaining)

**Comment by Emtec** [comment]
Fixed In [ 4336 ] (http://atlantiss.eu/changelog)
