### ISSUE TITLE
[EN][Spell][Mage] Flame Orb an Dragon's Breath

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1531]
By "skipping" in https://github.com/Atlantiss/BugTracker/issues/1524, i just meant it's not attacking Dragon's Breathed targets on the main. We can't even say if it's breaking from Flame Orb damage since it's not even attacking it. with recent changes on the main.

You just posted a proof in last issue so i guess you understand the mechanic.
http://youtu.be/u7W75EXoev4 ~11:50
![](http://bug.omfg.gg/attachments/download/563/Schermafbeelding%202014-01-10%20om%2014.06.14.png)
http://youtu.be/rPXue4sObxg?t=18m31s // Shamman getting hitted by Flame Orb in Dragon's Breath.

http://cata.openwow.com/spell=82731 // Flame Orb
http://cata.openwow.com/spell=31661 // Dragon's Breath

**Comment by Wolffenstein** [comment]
Sorry, will fix it soon.

**Comment by Wolffenstein** [comment]
Fixed in rev 4247.
