### ISSUE TITLE
[EN] [Guild]Guild Finder

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#1532]
there is a new issue for the guild finder now here is the pick the guild levels are messed up and the names are not showing right either and the for the comments are not showing right either. guild member do not work and there acheivement points are also not working right. i am using a new char. to test this if you need ingame confirmation my name on there is Daxter i will be staying on this char. for awile to keep testing it.

![wowscrnshot_011215_102751](https://cloud.githubusercontent.com/assets/4362814/5706359/bf964c7e-9a45-11e4-94b7-9d386f889788.jpg)
![wowscrnshot_011215_102405](https://cloud.githubusercontent.com/assets/4362814/5706308/4737f9c6-9a45-11e4-9269-f781fed7e3b6.jpg)

**Comment by krecik88** [comment]
Wait for the 4246, it should be fixed also.
