### ISSUE TITLE
[EN][Achievements] Bounce

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#1533]
The trampoline in mt hyjal doesn't throw you in the air
www.wowhead.com/achievement=5483

**Comment by Romarez** [comment]
It still doesnt work

**Comment by Aival94** [comment]
It now work.I did it today.

![wowscrnshot_123115_021911](https://cloud.githubusercontent.com/assets/10282971/12059502/1d9beff6-af65-11e5-87f3-8e5d7285a0b4.jpg)
