### ISSUE TITLE
[PL][Profession][Engineering] Nie można wykonać q na Gnome Engineering

### ISSUE THREAD

**Issue by kleofasa** [Atlantiss/BugTracker#1534]
Pierwszy raz wziełam Q od Tinkerwiz z Ratchet, wykonałam go i nie otrzymałam kontynuacji.
Tego samego questa na Gnome Engineering tj, Quest:Gnome Engineering dostałam również z Undercity. Quest wysłał mnie do Booty Bay z "Manual of Engineering Disciplines" do Oglethorpe Obnoticus, trenera inżynierii, gdzie kończy się owy quest. Problem w tym że NPC nie dał mi kontynuacji questa, przez co nie jest możliwe zrobienie rozszerzenia inżynierii na gnomią.

http://www.wowhead.com/quest=3635/gnome-engineering
http://www.wowwiki.com/Quest:Gnome_Engineering_(Undercity)
http://www.wowwiki.com/Oglethorpe_Obnoticus

**Comment by Bildo** [comment]
fixed in 4248

**Comment by Bildo** [comment]
fixed in rev. 4274
