### ISSUE TITLE
[PL][Quest][Silverpine Forest]Iterating Upon Success

### ISSUE THREAD

**Issue by TheRealCiapaty** [Atlantiss/BugTracker#1536]
Questa nie da się ukończyć, nietoperz buguje się i lata jakby miał atak epilepsji, skacze w powietrzu, skręca w miejscu, drgawki ma jakieś. xD
Spell 'Go Home' nie działa. http://www.wowhead.com/spell=83594
A po kliknięciu Leave Vehicle wyskakuje komunikat 'I can't do that yet'
Dopiero po ok. 2-3 minutach akrobacji spadamy z nietoperza.
A no i visual, nietoperz generalnie nie leci tylko podskakuje w powietrzu do momentu zbugowania się :)

Quest: http://www.wowhead.com/quest=26998/iterating-upon-success

@Edit
Za drugim razem nietoperz nie zbugował się w pewnym miejscu lecz wciąż podskakiwał w powietrzu zamiast normalnie lecieć :)

**Comment by Bildo** [comment]
duplikat
