### ISSUE TITLE
[PL][Spell][Mage] Ice Block

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1537]
http://www.wowhead.com/spell=45438/ice-block

Ice Block mozna uzyc podczas Cyclona druida, dostajemy CD debuff a Ice Block sam sie odpala po Cyclonie.
Ice Block nie powinien zdejmowac Cyclona(czego nie robi) Ale ten nie powinnismy miec mozliwosci odpalenia go w Cyclonie

http://pl.tinypic.com/r/2qbhgy1/8

Mam torche wiecej screenow, ten pokazuje najwiecej

**Comment by Wolffenstein** [comment]
Fixed in rev 4332.
