### ISSUE TITLE
[EN][Spell] Camouflage

### ISSUE THREAD

**Issue by lastkiss** [Atlantiss/BugTracker#1538]
On 4.3.4 patch it should be possible to hit a hunter with active http://cata.openwow.com/spell=51753 by anyone of rogue's spells except http://cata.openwow.com/spell=6770 - when rogue wants to sap there should be red info "Your vision of the target is obscured"

https://www.youtube.com/watch?v=RILbZtQOTYs // 0:23

I do not know how it looks like with other classes.

**Comment by kadi2** [comment]
"untargetable by ranged attacks." says everything. It's just Cammouflage bug,

**Comment by ShockRW** [comment]
I'd love to see fully blizzlike camouflage but I doubt I will, it's indeed quite complex spell.

**Comment by lastkiss** [comment]
If untargetable by ranged attack then also redirect and deadly throw

**Comment by lastkiss** [comment]
Premeditation is not an attack so imo it should be possible to use on camo

**Comment by Kuszki** [comment]
Same problem with druid's Pounce

**Comment by Jenovas** [comment]
Fixed in rev 4285
