### ISSUE TITLE
[EN][Spell][Priest] Talent improved mind blast

### ISSUE THREAD

**Issue by stewazy** [Atlantiss/BugTracker#1539]
The shadow talent improved mind blast is not working as intended it doesn't reduce the cooldown of mind blast

**Comment by lanrutcon** [comment]
It's working fine for me.
Could you post a screenshot?

**Comment by Wolffenstein** [comment]
Working fine.

**Comment by stewazy** [comment]
ok here's the screenshot http://s8.postimg.org/w166r8i39/Wo_WScrn_Shot_011315_025319.jpg
http://s12.postimg.org/vurdt3q65/Wo_WScrn_Shot_011315_025434.jpg
http://s3.postimg.org/78loqeb9f/Wo_WScrn_Shot_011315_025509.jpg

**Comment by lanrutcon** [comment]
New to WoW?
On you first screenshot (ss), you have 3points on Improved Mind Blast.
2nd SS, you mouse-over, and on the tooltip there 8-1.5 = 6.5s of CD.
Now, on the 3rd (ss), you get new talents (spec), in which you don't have Improved Mind Blast. So you get the original 8s CD.

There's no bug here.

**Comment by stewazy** [comment]
Even if i dont have the talent i have 1.5 sec cd

**Comment by Quban** [comment]
1.5 sec cast time, 8 sec CD
