### ISSUE TITLE
[PL][Quest][Kosmetyka] Drottinn Hrothgar

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1545]
http://www.wowhead.com/quest=14101/drottinn-hrothgar
http://www.wowhead.com/npc=34980/drottinn-hrothgar#comments

NPC Drottinn Hrothgar nie posiada broni (http://zapodaj.net/c3b23b1161ed4.jpg.html) powinien ja posiadac (http://www.wowhead.com/quest=14101/drottinn-hrothgar#screenshots:id=140282), nie posiada rowniez czerwonego dymu wokol siebie.

**Comment by Navedonar** [comment]
Poprawka na broń czeka na wgranie 
czerwony dym jest pojawia się jak używa http://www.wowhead.com/spell=67038/smash 
Do blizzlike brakuje tylko zeskoku jak się go summnie , tekstu jak spadnie i  przez chwile nie powinno się go dać zaatakować
https://www.youtube.com/watch?v=Jq0R1NSIqDk
https://www.youtube.com/watch?v=H0M-KYLoQwM

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
