### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] The Fel and the Furious

### ISSUE THREAD

**Issue by kazy14** [Atlantiss/BugTracker#1546]
http://www.wowhead.com/quest=10612/the-fel-and-the-furious

There is no Fel Reaver Control Console and the quest cannot pe completed

**Comment by Deadlyblonde** [comment]
Bump. Q dalej nie działa.

**Comment by Beatit** [comment]
bump! :(

**Comment by Illusionist87** [comment]
Still not working :(

**Comment by simonnorbert23** [comment]
still not working :(

**Comment by Bildo** [comment]
fixed
