### ISSUE TITLE
[PL][NPC][Kosmetyka] Tingiyok

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1548]
http://www.wowhead.com/npc=33868/tingiyok

NPC Tingiyok nie posiada w rekach kufli (http://zapodaj.net/9cc1e3a9c579b.jpg.html), a powinien posiadac(http://www.wowhead.com/npc=33868/tingiyok#screenshots:id=126549).

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
