### ISSUE TITLE
[PL][NPC][Kosmetyka] Binkie Brightgear

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1549]
http://www.wowhead.com/npc=33586/binkie-brightgear

NPC Binkie Brightgear jest facetem (http://zapodaj.net/a9fb65d78be99.jpg.html) a powinien byc kobieta (http://www.wowhead.com/npc=33586/binkie-brightgear#screenshots:id=294779).

**Comment by Asavel** [comment]
Może zmienił płeć?

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
Fixed by Navedonar:
