### ISSUE TITLE
[PL][NPC][Kosmetyka] Crystal Brightspark

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1550]
http://www.wowhead.com/npc=33588/crystal-brightspark

NPC Crystal Brightspark powinien trzymac w rekach flaszki (http://www.wowhead.com/npc=33588/crystal-brightspark#screenshots:id=294792), a nie posiada (http://zapodaj.net/d11b5b28846c6.jpg.html).

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
