### ISSUE TITLE
[PL][NPC][Kosmetyka] Oluros

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1551]
http://www.wowhead.com/npc=33590/oluros

NPC Oluros nie posiada w prawej rece off-handa (http://zapodaj.net/17cf71338dcca.jpg.html), a powinien posiadac (http://www.wowhead.com/npc=33590/oluros#screenshots:id=294795).

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
