### ISSUE TITLE
[PL][NPC][Kosmetyka] Crok Scourgebane 

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1552]
http://www.wowhead.com/npc=33762/crok-scourgebane

NPC Crok Scourgebane posiada zly model broni (http://zapodaj.net/62573bdb50912.jpg.html), powinien posiadac inny (http://www.wowhead.com/npc=33762/crok-scourgebane#screenshots:id=126447).

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
