### ISSUE TITLE
[PL][Other] Zeppelin Master

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#1553]
Ci NPC powinni nam mówić gdzie obecnie znajduje się zeppeling. 
Aktualnie zawsze jest to kwestia, że zeppelin wyruszył z miasta lub nie chcą z nami gadać wcale

http://www.wowhead.com/npc=9564/frezza#comments
http://www.wowhead.com/npc=3149/nezraz
http://www.wowhead.com/npc=12137/squibby-overspeck
http://www.wowhead.com/npc=12136/snurk-bucksquick

**Comment by Bildo** [comment]
fixed by Wolfenstein
