### ISSUE TITLE
[EN][NPC][Dungeon: Lower Blackrock Spire] Shadow Hunter Vosh'gajin

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1554]
[Vosh'gajin's](http://www.wowhead.com/npc=9236/shadow-hunter-voshgajin#abilities) ability *Hex* seems to be too strong right now. It should have 8 sec duration and 20 yd range (so that healers and range DPS could easily outrange this ability).

Right now, Hex has ~20 sec duration and cannot be outranged.

![you mad, bro?](http://i.imgur.com/uqeLpZI.jpg)

I just tried to 2-man this dungeon after the rest of the group left (why does nobody want to do UBRS/LBRS?). We came up to this boss, who kept us both perma-CCed and killed us until we called it a day.

**Comment by lanrutcon** [comment]
From the screenshot, you can clearly see that's a "fake" Hex.
1st - the "Hex" that you got is a buff (right-click may remove it).
2nd - unlike shaman's hex, this one is a "magic" spell (not a curse)
And 3rd, next time provide the combatlog, there you can clearly see what the boss casted.

So, in the end, he's basically using the wrong spell.

**Comment by Tj20** [comment]
Huh, you're right... what a shame I didn't think of just right-clicking that.

**Comment by Tj20** [comment]
Today I did the fight again with a proper group ([combatlog](http://pastebin.com/GMMrMnXJ)), and it seems that Vosh'gajin's hex is indeed marked as a buff, which could not be dispelled by the healer, but could be right-clicked by me (not totally sure, but it looked that way for me).

The hex by the [Smolderthorn Shadow Priests](http://www.wowhead.com/npc=9240/smolderthorn-shadow-priest#abilities) on the other hand did properly work like a debuff which could be dispelled by the healer and also is marked in the combatlog as a debuff.

> 2/6 15:42:54.283  SPELL_AURA_APPLIED,0xF130241400712DBF,"Shadow Hunter Vosh'gajin",0x10a48,0x80,0x0000000000046D77,"Sharai",0x511,0x0,16708,"Hex",0x8,BUFF

> 2/6 15:43:14.917  SPELL_AURA_APPLIED,0xF130241800712DB8,"Smolderthorn Shadow Priest",0xa48,0x0,0x0000000000046D77,"Sharai",0x511,0x0,11641,"Hex",0x8,DEBUFF

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2084
