### ISSUE TITLE
[PL][NPC][Kosmetyka] Dame Evniki Kapsalis 

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1557]
http://www.wowhead.com/npc=34885/dame-evniki-kapsalis

NPC Dame Evniki Kapsalis nie posiada (http://zapodaj.net/16a2c6edbdd63.jpg.html) staffa, a powinien posiadac (http://www.wowhead.com/npc=34885/dame-evniki-kapsalis#screenshots:id=136033).

Powinien tez posiadac mozliwosc kupowania Herloomow (http://www.wowhead.com/npc=34885/dame-evniki-kapsalis#sells) za Champion's Seale.

**Comment by Navedonar** [comment]
She offers various items and heirlooms to players who have earned the title of <Crusader>.
Spełniasz to wymaganie?

**Comment by Beatit** [comment]
są herloomy z tego co pamietam, Info nie masz Crusadera...

**Comment by InformatorPE** [comment]
Ale staffa nie posiada

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
