### ISSUE TITLE
[EN][Dungeon][Scarlet Monastery][Quest] Compendium of the Fallen

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#1559]
Quest: http://www.wowhead.com/quest=26993/compendium-of-the-fallen
Quest Item: http://www.wowhead.com/item=5535/compendium-of-the-fallen

Quest item is glittering but we're unable to pick it up. Also, according to addon we're using, provided information from Private Status, when quest was working, only one person per party could pick up book.

Edit: 
[EN] Small update: On Horde side this quest seems to work without problems, except book respawn takes 4-6 minutes each.

[PL] Drobne uaktualnienie: Po stronie Hordy quest działa bez zarzuceń, jedynie książka respawnuje się co 4-6 minut.

------------------
http://webm.host/9418a/ 
Edit: Only one person can grab the book per instance, apparently.

**Comment by Jackalantern** [comment]
Still having this problem as of this date on my Draenei.

**Comment by Razvanobivan** [comment]
i cant click that book....

**Comment by Dean1989** [comment]
same issue

**Comment by Dexobox** [comment]
+1 The book is still un-clickable

**Comment by coba999** [comment]
didn't work
