### ISSUE TITLE
[EN][QUEST][Southern Barrens] Working the Bugs Out

### ISSUE THREAD

**Issue by Nosere** [Atlantiss/BugTracker#1560]
http://www.wowhead.com/quest=25082/working-the-bugs-out

Using http://www.wowhead.com/item=50128/bucket-of-burning-pitch at the correct location does not work.

How its supposed to work:
http://youtu.be/nWsY3mniuXE?t=16s

**Comment by darklord88** [comment]
Working!Just not before aly kamp do on opposite side xD

**Comment by GamingAnonymous** [comment]
Still bugged

**Comment by Thunderlmao** [comment]
As of 15/04/2017 it only works on the Horde side, meaning if you're in the Alliance you must go over to the Desolation Horde which is at the other side of the Battle Scar and do the quest on the mounds there.

**Comment by naakarg** [comment]
Still bugged, hell I'd take a full time programming course and apply to help, please fix these little quests.

**Comment by roirraWedorehT** [comment]
Still bugged but at least still works on the Horde side

**Comment by Bildo** [comment]
fixed
