### ISSUE TITLE
[ENG][NPC][instance]Nefarian

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#1562]
When the 2nd phase starts within the encounter, no lava appears to let us swim up towards the platform. or at least it doesn't spawn in time. The adds already start their cast on the spell and we can't interrupt them so we die before the lava even appears. Please fix it. Thanks

**Comment by NONLIFE** [comment]
https://github.com/Atlantiss/BugTracker/issues/844
