### ISSUE TITLE
[EN] [QUEST] [DUNGEON] Taragaman the Hungerer (ID: 26858)

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1564]
The quest http://www.wowhead.com/quest=26858/taragaman-the-hungerer have a bug:
You need to kill mobs (and this part works fine) and you need to loot the Taragaman the Hungerer's Heart that it should be dropped everytime (100%) and it should be dropped for each character that have the quest...
In the real this not happens! I've killed 3 time the boss http://cata.openwow.com/npc=11520, but no one time he dropped the quest item http://cata.openwow.com/item=14540.

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
