### ISSUE TITLE
[EN][Quest][Gilneas] Worgen Quest problem - Endgame

### ISSUE THREAD

**Issue by zero092** [Atlantiss/BugTracker#1567]
Endgame-http://www.wowhead.com/quest=26706/endgame
After taking it,the quest seems to be stuck,Tobias doesnt do anything and the only thing i can do is complete it without doing anything by talking to the NPC who gave me the quest.

**Comment by Varchord** [comment]
1 issue 1 bug (quest)

**Comment by zero092** [comment]
Sorry,first time using this.I'll edit out this post and make 2 more.

**Comment by Danelar** [comment]
[PL] Po prostu quest jest wykonany w momencie jego wzięcia :|

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3558
