### ISSUE TITLE
[EN][Quest][Gilneas] Worgen Quest problem - Push Them Out

### ISSUE THREAD

**Issue by zero092** [Atlantiss/BugTracker#1568]
Push Them Out-http://www.wowhead.com/quest=24676/push-them-out
After talking with the royal alchemist game enters a loading screen and i spawn in the city with the quest completed.

**Comment by Tj20** [comment]
I just did "Push them Out", the quest worked fine.

I think you meant the follow-up quest "The Battle for Gilneas City". That one is indeed set on auto complete (but I think it would be extremely hard to script).

**Comment by Bildo** [comment]
Yea it's REALLY hard to script this quest. As i mentioned somewhere on the forum this quest worked but causes some problems to many players so we decided to set to autocomplete.
