### ISSUE TITLE
[PL][Pet][Warlock] Ebon Imp

### ISSUE THREAD

**Issue by Zak1** [Atlantiss/BugTracker#157]
"Imps summoned by  [Bane of Doom] now benefit from the warlock's stats."
http://wowpedia.org/Patch_4.1.0

Porównałem dmg z maina i ptra. Na obu biją identycznie, co wyklucza działanie tego fixa. Zresztą guardiany tego typu chyba nie są u nas zbyt dobrze oskryptowane?

**Comment by Jenovas** [comment]
Chciałbym jakieś informacje po ile biją, z czym mają się skalować?

**Comment by Jenovas** [comment]
From what I see in the code Ebon Imp DMG scales with warlock Spellpower, it might be that we had them already scaling with 4.0.6 or someone fixed it and didnt close the issue. They also scale with warlock hit rating.

**Comment by Varchord** [comment]
Zrobiłeś to przy okazji wszytkich petów/guardianów chyba :P

**Comment by Jenovas** [comment]
Starałem się, jeżeli coś ominąłem proszę to zgłosić.
