### ISSUE TITLE
[PL][Spell][Hunter] Aggresive

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#1571]
Tryb aggresive u peta powoduje, że ten kręci się w kółko i nie atakuje nikogo.

**Comment by szpagaciarz** [comment]
tryb ten od patcha 4.2 zostal usuniety
Pets
The Aggressive pet stance has been removed and replaced with the Assist stance. This stance will cause the player's pet to attack the player's target. The pet will not change targets unless the master attacks a new target for a few seconds.
The Defensive pet stance will now only cause the player's pet to attack enemies which attack the pet or the master.

ponadto pet znika jak wsiada sie na mounta a nie powinien. jesli trzeba to załoze o tym osobny temat
