### ISSUE TITLE
[EN][Quest][Winterspring] Hunting Practice

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#1572]
http://www.wowhead.com/quest=29038/hunting-practice
The problem with the quest is that the snow-covered burrows are nowhere to be found. Searched the whole area with no success which leads me to believe they are not implemented.

**Comment by Bildo** [comment]
should be working, comment if its not

**Comment by Swepy** [comment]
i coudnt find any either, maybe its just that they dont have that glowing or they wasnt added, its hard to tell because my map doesnt shows where they are suppose to be.
