### ISSUE TITLE
[EN] [Quest] [Items] [Ghostlands] Rotting Heart and Spinal Dust

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1573]
Thoose items:

Spinal dust http://cata.openwow.com/item=22642
Rotting heart http://cata.openwow.com/item=22641

are dropped only if you have the quests:

Spinal dust http://cata.openwow.com/quest=9218
Rotting Heart http://cata.openwow.com/quest=9216

and in the real, thoose items are not "quest items" but a normal drop.
For this reason, the quests:

More Spinal Dust http://cata.openwow.com/quest=9219
More Rotting Heart http://cata.openwow.com/quest=9217

can't be completed!

This problem should be fixed in rev 4179, but now is back!

https://github.com/Atlantiss/BugTracker/issues/1042
https://github.com/Atlantiss/BugTracker/issues/1044

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
