### ISSUE TITLE
[PL][Hunter][Pet] Qirot

### ISSUE THREAD

**Issue by Shadi0** [Atlantiss/BugTracker#1574]
http://www.wowhead.com/npc=5350/qirot

Problem w tym, że..
Pet będąc Waspem, można aktualnie tamować go jako Beast, a po złapaniu jest Chimerą, oczywiście ze spellami tej family. Dodać trzeba, że Chimera jest petem egzotycznym, czyli powinno móc się używać tylko i wyłącznie w drzewku BM mając ostatni talent. Tego peta niestety idzie używać normalnie jako exotic w MM drzewku oraz Survi. Bug wykorzystywany.

**Comment by wojen616** [comment]
To, że można go tamować jako beast, to nie bug, na globie też w każdym specu można go złapać. 

Co do spelli, to się nie wypowiem, bo nie widziałem, nie mam, zarobiony jestem. ;)

**Comment by Shadi0** [comment]
Szukałem innych nawet tych po instach raidach ahn'qiraj ale nie można było tamować, bo nie były beastami, ten Qirot akurat jest nim a rzucił się w oczy bo przez 3tyg jeden hunter nim bugował... a to nie mogło przejść uwadze kiedy w tym samym czasie widzisz buffka z talentów MM :d 
W sumie jak ktoś znajdzie jeszcze jakieś pety tego typu to dobrze by było dodać ;)

**Comment by wojen616** [comment]
No ja akurat po tym zgłoszeniu poleciałem altem do feralas złapać qirota, a że go nie było, to złapałem pierwszego z brzegu waspa i też ma złe spelle :)
