### ISSUE TITLE
[EN] [QUEST] [Silverpine Forest] Belmont's Report

### ISSUE THREAD

**Issue by Jackalantern** [Atlantiss/BugTracker#1575]
After I accept this quest from Deathstalker Commander Belmont it asks me to give his report to Lady Sylvanas Windrunner just a few meters away from him at the Forsaken High Command. However there is no yellow question mark above her head, and she is unclickable for any dialogue or progression. The yellow question mark does, however, appear on the minimap.

I completed this quest just a couple weeks ago on another character and it seemed to work fine, but not this time. I am for the moment stuck as I cannot progress with any quests in the zone and the main undead quest line. Character is named "Bartholomeu".

**Comment by Technowizard15** [comment]
Same for me. Deleted cache and restarted quest, didn't help.

**Comment by KubqoA** [comment]
Same with me
Character name Zlýujo Undead Mage 13

**Comment by Technowizard15** [comment]
Today I suddenly could finish the quest.

**Comment by Frosteru** [comment]
yep can't finish the quest, no question mark appears above the banshee quens head.

Character: Bertjan level 13 undead warlock

**Comment by stormbreakerZ** [comment]
Also have this problem, it isn't fixed yet.
character: Laidorr, undead hunter

**Comment by Tremorius** [comment]
I am having the same problem. 
character: Tremorius, undead warlock

**Comment by Tremorius** [comment]
oh, it suddenly works :), could turn in the quest just now.

**Comment by Technowizard15** [comment]
My suspicion is that the server has to be restarted for the quest to work.

**Comment by Sveron1** [comment]
I have that same problem Character: Sveron, Blood elf hunter
