### ISSUE TITLE
[PL][Profession][Engineering] Nie można wykonać q na Gnome  i Goblin Engineering

### ISSUE THREAD

**Issue by kleofasa** [Atlantiss/BugTracker#1579]
Pierwszy raz wziełam Q od Tinkerwiz z Ratchet, wykonałam go i nie otrzymałam kontynuacji.
Tego samego questa na Gnome Engineering tj, Quest:Gnome Engineering dostałam również z Undercity. Quest wysłał mnie do Booty Bay z "Manual of Engineering Disciplines" do Oglethorpe Obnoticus, trenera inżynierii, gdzie kończy się owy quest. Problem w tym że NPC nie dał mi kontynuacji questa, przez co nie jest możliwe zrobienie rozszerzenia inżynierii na gnomią.

http://www.wowhead.com/quest=3635/gnome-engineering
http://www.wowwiki.com/Quest:Gnome_Engineering_(Undercity)
http://www.wowwiki.com/Oglethorpe_Obnoticus

Próbowałam również zrobić quest na goblin engi ale sytuacja wygląda identycznie jak z gnome engi.
http://www.wowhead.com/quest=3526/goblin-engineering

Podobno problem był naprawiony w rev 4248 ale niestety dalej nie działa więc otwieram post ponownie.

**Comment by NONLIFE** [comment]
"This quest was marked obsolete by Blizzard and cannot be obtained or completed." -.-

**Comment by Bildo** [comment]
stary quest chyba usunalem ale nie jestem pewien rowniez nei sprawdzalem czy ten nowy dziala, jakby ktos napisal bylboy super

**Comment by NONLIFE** [comment]
nowego nie ma

**Comment by Bildo** [comment]
http://www.wowhead.com/npc=11017/roxxik napewno ten npc nic nie daje ? jestem pewien, ze dodawalem ten quest

**Comment by NONLIFE** [comment]
stoje przed nim i nic nie ma ;[

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1534

**Comment by NONLIFE** [comment]
w #1534 podaje do q ktorego nie da sie ukonczyc

**Comment by NONLIFE** [comment]
teraz tylko trzeba dodac 2 questy do roxxik-a ;d

**Comment by kleofasa** [comment]
roxxik nic nie daje :(
