### ISSUE TITLE
[PL][Quest][Silverpine Forest]Orcs are in Order

### ISSUE THREAD

**Issue by TheRealCiapaty** [Atlantiss/BugTracker#1581]
Questa nie da się ukończyć co uniemożliwia kontynuowanie chaina.
Nie można oddać questa Sylvanas.
http://www.wowhead.com/quest=27096/
![wowscrnshot_011415_194150](https://cloud.githubusercontent.com/assets/9433606/5744977/9d59631c-9c25-11e4-960b-1daa8217121f.jpg)

**Comment by krecik88** [comment]
http://www.wowhead.com/npc=44365/lady-sylvanas-windrunner

Nie do tej sylvanas.

**Comment by TheRealCiapaty** [comment]
Właściwie to do dobrej sylvanas pobiegłem, przed sekundą się zalogowałem i w magiczny sposób questa mogłem oddać. Dziwne no ale cóż. xD
