### ISSUE TITLE
[PL][Spell] Priest Mastery

### ISSUE THREAD

**Issue by Meteora11** [Atlantiss/BugTracker#1583]
Priest w talentach holy posiada Mastery Echo of Light (http://www.wowhead.com/spell=77485/mastery-echo-of-light) natomiast w talentach discipline Mastery Shield Discipline (http://www.wowhead.com/spell=77484/mastery-shield-discipline). Jeżeli zrobimy respec z Holy na Discipline bardzo często dalej leczymy graczy healem z mastery w holy, posiadjąc jednocześnie mastery z Discipline (czyli to prawidłowe). Wygląda to tak jakby heal Echo of Light w losowych sytuacjach zostawał dalej mimo zmiany speca.
PS.
Za wszelkie błędy przepraszam, pierwszy raz zgłaszam coś na bt, jeżeli dubel to proszę o usunięcie.

**Comment by Glare** [comment]
Czyżby winnym był pseudo reset talentów? Zresetowane zostały jedynie punkty, same drzewka talentów pozostały te same więc i mastery nie zostało zresetowane.

**Comment by Jenovas** [comment]
Reset talentów i aur naprawił większość bugów z mastery, np rogali i ferali, tlyko że tam był bug że zawsze miało się podwójnie mastery i np w feralu miało się podwójnie mastery dla ferala, a tutaj kolega mówi że przy respecu raz się ma podwójnie a raz nie, tak więc to prawdopodobnie wina respeca i tego że czasami nie usuwa wszystkich aur (no niewiem zobaczymy).

**Comment by Aviannaqt** [comment]
Dopowiem, ze czasem mastery sie dziwnie kumuluje przy np, przy engulfing magic potrafi stackowac sie do 100k+, a na DW (ICC) na 6 stackach potrafi leczyc za miliony/sek.

**Comment by Jenovas** [comment]
Bug ten już był że się kumuluje za szybko. Najpewniej podczas przejścia na 4.3.4 ktoś wywalił, popatrzę na to.

**Comment by Meteora11** [comment]
Dowód, że bug występuje: https://www.youtube.com/watch?v=cI8oSGtcWRM&feature=youtu.be

**Comment by Jenovas** [comment]
Czy bug wciąż występuje?

**Comment by Aviannaqt** [comment]
Teraz już działa poprawnie i nie stackuje się do kosmicznym ilości.

**Comment by Kejmil** [comment]
powiedzial holy priest :D

**Comment by Jenovas** [comment]
Fixed in rev 4570 - fix a bug that allowed any class to have two different masteries active
Bug dotyczył KAŻDEJ klasy i już nie powinien występować.
