### ISSUE TITLE
[EN] [Dungeon-TBC] Auchenai Crypts: Summoned Ghosts

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1584]
Auchenai Crypts: http://www.wowhead.com/zone=3790

**Observed behaviour:**
[Auchenai Monks](http://www.wowhead.com/npc=18497/auchenai-monk#abilities), [Auchenai Soulpriests](http://www.wowhead.com/npc=18493/auchenai-soulpriest#abilities) and [Auchenai Vindicators](http://www.wowhead.com/npc=18495/auchenai-vindicator#abilities) each spawn multiple ghosts. Also, the summoned ghosts start attacking immediately.

example: 1 Soulpriest summons 4 ghosts
![1 Soulpriest, 4 summoned mobs](http://i.imgur.com/xwOSAVz.jpg)
[combatlog snippets](http://pastebin.com/FhQTi5Mc)

**Expected behaviour:**
Each mob should only spawn one ghost. Each ghost has a spawn animation (~ 2-3 seconds, I think), during which the ghost can already be damaged, but does not attack himself yet, giving tanks time to pick the ghosts up.
[video](http://youtu.be/2vUzLaUcy3g?t=3m55s)
![pic](http://i.imgur.com/SgQxE1D.jpg)

**Comment by cosminush** [comment]
Firsts NPCs from entrance and first chamber are spawned continue after they die, it's imposible to continue without combat continue. I dont know for rest of instance but i cant continue dungeon.

**Comment by Bildo** [comment]
fixed
