### ISSUE TITLE
[EN][Guild][Achievement] Ragefire Chasm

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1586]
After killing "Taragaman the Hungerer" The achievement is not granted when in a guild party of 3 or more in Ragefire Chasm. 

http://www.wowwiki.com/Ragefire_Chasm_%28achievement%29

**Comment by NONLIFE** [comment]
by "guild party" u mean "Guild Members" ?

**Comment by Helbringer** [comment]
Yes

**Comment by Helbringer** [comment]
I ran the instance twice with 3 guild members including myself and we did not gain the achievement.

**Comment by Angelo-DM-** [comment]
This is a Duplicate post... this problem has already reported here:
https://github.com/Atlantiss/BugTracker/issues/1564

**Comment by Angelo-DM-** [comment]
https://github.com/Atlantiss/BugTracker/issues/1564

**Comment by Helbringer** [comment]
All of us recieved the heart however we did not receive the guild acheivment for killing the boss.

**Comment by Helbringer** [comment]
However to support your report of the heart drop rate, 1 of our group did not aquire it till he re entered the instance, at no point did he loot the item, somehow he was still able to complete the quest.

**Comment by xolon** [comment]
none of guild dungeon/raid achis work
our guild just started guild raiding (10/10 ppl are from guild) we did 5/6 bwd 3/4 bot but we didnt get credit for any of the bosses we killed, my 4 guild mates tryed to get all tbc dung achis for guild, but were only able to get personal ones
