### ISSUE TITLE
[EN][Quest][Winterspring] Cub's first toy

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#1587]
http://www.wowhead.com/quest=29040/cubs-first-toy
The mobs that should drop the quest items don't drop them at all, even after killing all of them in the area. Either they don't have the quest items on the possible drop list or it's much lower chance than it should be.

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by cuba1984** [comment]
Unfortunately still unworkable quest because of lack of loot in the form of feathers
http://www.wowhead.com/item=68662/wildkin-feather#dropped-by
