### ISSUE TITLE
[PL][Talent][Hunter] Lock and Load

### ISSUE THREAD

**Issue by Wulgarny** [Atlantiss/BugTracker#1591]
Talent: http://www.wowhead.com/spell=168980/lock-and-load
Pierwszy darmowy explosive shot działa poprawnie, lecz drugi nie jest możliwy do wycastowania gdy hunter nie ma odpowiedniej ilości focusu. Gdy hunter osiągnie (w moim przypadku) 44 focusu explosive shot jest możliwy do wycastowania bez kosztu.

**Comment by Shadi0** [comment]
Spróbuj używać skilla zgodnie z jego gcd, tzn nie spamuj na siłe skilla klikająć kilkakrotnie jak najszybciej to na pewno nie będzie się bugował ;)

**Comment by Wulgarny** [comment]
Używam zgodnie z GCD >.>

**Comment by Shadi0** [comment]
Testowałem to już kiedyś, sprawdziłem jeszcze teraz dla upewnienia.
Jeśli wyskoczy L&L buff i klikasz powoli pojedynczo skille to możesz normalnie używać.
Jak dosłownie spamujesz button to skill się buguje.
Więc wina leży po Twojej stronie, testowane z 3 hunterami survi i nikt nie miał takiego problemu ;P

**Comment by Wulgarny** [comment]
Kill me please. 
case closed.
