### ISSUE TITLE
[EN] [QUEST] [Tirisfal Glades] The Truth of the Grave

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1593]
This quest should be horde side, instead it has "undead restriction".

http://www.wowhead.com/quest=24961

This quest unlock five more quests (in order):

http://www.wowhead.com/quest=28672

http://www.wowhead.com/quest=26802

http://www.wowhead.com/quest=24973

http://www.wowhead.com/quest=24970

and

http://www.wowhead.com/quest=24971

As Blood Elf, i can't take this quest.

**Comment by Bildo** [comment]
fixed in rev. 4274
