### ISSUE TITLE
[EN] [Quest] [Mount Hyjal] Prepping the Soil

### ISSUE THREAD

**Issue by jasiol2** [Atlantiss/BugTracker#1600]
Quest: http://www.wowhead.com/quest=25502/prepping-the-soil
Can't Activate the Flameward, simply unable to use it 
Screenshot: http://i.imgur.com/pJiPx53.jpg
It's essential to complete this quest in order to pick next quests. People are stuck with 80/115 in Mount Hyjal this way. 
Looking forward to your help!

**Comment by Wolffenstein** [comment]
Fixed in rev 4253.

**Comment by Wajju** [comment]
Bug is reoccurring as of Nov 4. The same flame ward has not been activatable for the past hour.
