### ISSUE TITLE
[EN][NPC][Teldrassil] Nightsaber

### ISSUE THREAD

**Issue by Duros** [Atlantiss/BugTracker#1602]
**Issue:**

The Nightsabers you need to kill for [Nightsaber Fangs](http://www.wowhead.com/item=3409/nightsaber-fang) for the quest: [Zenn's Bidding](http://www.wowhead.com/quest=488/zenns-bidding) don't seem to spawn correctly. They suddenly appear when you walk over them.

**Bugged NPCs:**
* [**Nightsaber**](http://www.wowhead.com/npc=2042/nightsaber)
* [**Elder Nightsaber**](http://www.wowhead.com/npc=2033/elder-nightsaber)
* [**Nightsaber Stalker**](http://www.wowhead.com/npc=2043/nightsaber-stalker)

**Not Bugged:**
* [**Feral Nightsaber**](http://www.wowhead.com/npc=2034/feral-nightsaber)

**Comment by Duros** [comment]
Feral Nightsabers do appear correctly.

**Comment by Duros** [comment]
Why does this issue get closed? Yesterday they were still bugged.

**Comment by Bildo** [comment]
no wowhead links ?

**Comment by Duros** [comment]
I am sorry, updated.

**Comment by Navedonar** [comment]
working properly
http://www.wowhead.com/spell=24450/prowl
