### ISSUE TITLE
[EN][Quest][Howling Fjord] The Cleansing

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#1604]
http://www.wowhead.com/quest=11317/the-cleansing

using frostblade shrine http://www.wowhead.com/object=186649/frostblade-shrine doesnt do anything , it should spawn your inner turmoil http://www.wowhead.com/npc=27959/your-inner-turmoil which is a visual copy of the player and to be killed

cant complete this quest and it ruins the chain

**Comment by Dexobox** [comment]
Youtube Link: [The Cleansing] (https://www.youtube.com/watch?v=sP7EHXZG108)

**Comment by Bildo** [comment]
fixed
