### ISSUE TITLE
[EN] [QUEST] [Silverpine Forest] Transdimensional Warfare: Chapter III

### ISSUE THREAD

**Issue by Jackalantern** [Atlantiss/BugTracker#1605]
The shield does not properly overload, and the quest does not complete, no matter if Archmage Ataeric gets overloaded and dies. I tried it twice, tried relogging, and I tried exiting the dimension, relogging, and re-entering the dimension to overload and kill him again and nothing seemed to work.

So once again I am stuck in the Undead quest chain. It would seem this whole area regarding Silverpine Forest and Ruins of Gilneas needs some serious overhaul as far as ironing out bugs. This is my third "showstopper" when it comes to questing with my undead, which is a shame, and it's one of the better ones in cataclysm xpac as far as starting zone quest chains.

**Comment by Cassedy** [comment]
I can confirm this bug but had no probs in the main questline before this
