### ISSUE TITLE
[EN][Dungeon][Vortex Pinnacle] Asaad

### ISSUE THREAD

**Issue by jasiol2** [Atlantiss/BugTracker#1609]
Asaad in The Vortex Pinnacle http://www.wowhead.com/npc=43875/asaad
His http://www.wowhead.com/spell=86911/unstable-grounding-field spell does not create a full triangle, it's missing one wall and does not prevent damage of http://www.wowhead.com/spell=86930/supremacy-of-the-storm
Instead the safe zone is where Asaad stands, if you stick to him for the duration of Supermacy of the Storm you avoid the huge damage

**Comment by NONLIFE** [comment]
https://github.com/Atlantiss/BugTracker/issues/769
