### ISSUE TITLE
[EN][Achievement] Oh Novos

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#1610]
http://www.wowhead.com/achievement=2057/oh-novos
Last 2 attempts i did, i was killing each npc before they could reach half of the stairs, none did pass or reach bottom. After killing the boss i didn't earn achievement

**Comment by Meteora11** [comment]
I earn achievement today so it's working.

**Comment by xolon** [comment]
It doesn't work sometimes idk what is causing that
