### ISSUE TITLE
[EN][NPC][Gnomeregan] B.E Barechus <S.A.F.E.>

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#1611]
NPC link: http://www.wowhead.com/npc=44560/b-e-barechus

Lack of NPC makes impossible to finish quest "The G-Team" (http://www.wowhead.com/quest=26939/the-g-team) and continue chain by taking "The G-Team" (http://www.wowhead.com/quest=26941/the-g-team).

This is for Alliance side.

**Comment by Veruca1320** [comment]
still missing

**Comment by Dexobox** [comment]
+1 I can confirm still missing

**Comment by reapertg** [comment]
Still MIA, where oh where is poor BA?

**Comment by Nightend1** [comment]
+1

**Comment by arndry** [comment]
The NPC is not placed yet... 

and also: In the retail version the monster you have to kill is way bigger than the others. 

https://www.youtube.com/watch?v=wnIPSGNmF-k

**Comment by Bildo** [comment]
fixed

**Comment by Snake90** [comment]
The quest is still, always and definitely bugged ... No NPC :/

**Comment by TranceAccount** [comment]
You have to move back to the entrance at this moment to hand in the quest.

**Comment by Snake90** [comment]
Ok thanks :)
