### ISSUE TITLE
[PL][Talent][Priest]Harnessed Shadows

### ISSUE THREAD

**Issue by Unn90** [Atlantiss/BugTracker#1613]
http://wow.gamepedia.com/Harnessed_Shadows
http://cata.openwow.com/spell=78228#see-also-ability
http://www.wowwiki.com/Harnessed_Shadows

NIe działa 2 częśc talentu: "and you have a 50/100% chance to gain a Shadow Orb when critically hit by any attack.". Cryty z jakichkolwiek spelli typu Devourling Plague, Vampirit Touch czy inne nie nabijaja shadow orbów a powinny.

**Comment by Glare** [comment]
Zdajesz sobie sprawe z tego, że chodzi o crity, które twoja postać OTRZYMUJE od moba/gracza?

**Comment by Unn90** [comment]
zdaje sobie i widze, że nigdzie nie ma tam słowa "you" a nawet WoW-Space tłumaczy to, że kiedy ty uderzysz a nie kiedy ty zostaniesz uderzony krytycznym atakiem otrzymujesz shadow orba.
http://wow-space.info/menu/kalkulator#priest|0|433

**Comment by Wolffenstein** [comment]
Obawiam się, że autorzy WoW-Space raczej nie mogą być stawiani jako przykład osób doskonale władających angielskim.

Na potwierdzenie, dane z dbc:

Proc flag 0x000222A8, chance = 50, charges - 0
=================================================
  03 Taken damage from melee strike hit
  05 Taken damage by Spell that use melee weapon
  07 Taken damage from ranged attack
  09 Taken damage by Spell that use ranged weapon
  13 Taken negative spell hit
  17 Taken magic spell damage
