### ISSUE TITLE
[PL][Talent][Priest]Shadowy Apparitions

### ISSUE THREAD

**Issue by Unn90** [Atlantiss/BugTracker#1614]
http://wow.gamepedia.com/Shadowy_Apparitions
http://www.wowhead.com/npc=46954/shadowy-apparition#comments

Cienie, które z nas "wychodzą" nie crytuja a powinny. 

simulationcraft z 4.0.6 ale w żadnym patchu do 4.3.4 nie ma zmian w telencie.
http://simulationcraft-swtor.googlecode.com/git-history/6986f6c3522ab859808874fa407dee369fed630d/html/406-7/Raid_T11_372.html#Priest_Shadow_T11_372

shadowy_apparition  12207(hit) 25682{cryt) 33306(max crit) 28.6%(% na cryta)

addon dr.damage pod 4.3 również pokazuje, że cienie mogą crytować.

**Comment by Jenovas** [comment]
Fixed in rev 4285
