### ISSUE TITLE
[EN] [NPC] [Drop] Stone Guardian

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#1615]
NPC: Stone Guardian ( http://www.wowhead.com/npc=6560/stone-guardian )
Item: Guardian Stone ( http://www.wowhead.com/item=12809/guardian-stone )

Context: I have cleared the zone about 8 times and although it's supposed to have a 20% drop chance, I haven't got a single Guardian Stone.

Several comments from patch 4.0.6 confirm the higher than average drop rate:
 
"I was just doing Marshal's refuge quest in Un'goro and 5 Guardian Stones dropped for me. I probably only killed 15 Guardians, so it shouldn't be too hard to farm now."

**Comment by Bildo** [comment]
fixed in rev. 4274
