### ISSUE TITLE
[PL][Quest][Winterspring] A Cub's Cravings

### ISSUE THREAD

**Issue by cuba1984** [Atlantiss/BugTracker#1616]
http://www.wowhead.com/quest=29035/a-cubs-cravings
Zadanie polega na zabiciu bialych niedzwiedzi i zebraniu 6 sztuk miesa
http://www.wowhead.com/item=12622/shardtooth-meat
i nakarmieniu nim peta.
Niestety nie zalicza karmienie miesiem.

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by cuba1984** [comment]
Odnawiam zgloszenie. Po wprowadzeniu poprawek (rev.4274) quest nadal niewykonalny gdyz z miskow nie dropi q itemu w postaci mieska. 
To samo dotyczy innego questa w #1587
