### ISSUE TITLE
[EN][Dungeon-Cataclysm] Throne of the tides

### ISSUE THREAD

**Issue by stewazy** [Atlantiss/BugTracker#1617]
This instance is not working as it should, the first time you get this on normal rdf u can complete it after that when ever you get this instance the instance is empty all the time because you can only do 3 bosses, the second boss doesn't spawn .

**Comment by adryjan** [comment]
Bro are u sure? Coz u have to use a device in his room to summon 2nd boss.

**Comment by stewazy** [comment]
Ok my mistake but even when you finish the instance, and requeue the and get the same instance (throne of the tides), it doesnt get reseted, the server has to crash in order for it to be reset.

**Comment by Varchord** [comment]
It's not instance problem. besides https://github.com/Atlantiss/BugTracker/issues/1156
