### ISSUE TITLE
[EN][Pet][Wailing Caverns] Pet paths glitch

### ISSUE THREAD

**Issue by Duros** [Atlantiss/BugTracker#1620]
My pet does take some weird paths inside the dungeon, for example in the center at the turtle boss. If you move past the rocks the the next boss, my pet took a route al the way up again. Here was no jumping involved. And then he get stuck at some weird place. Dismiss pet does not work at that point.

**Comment by Howlingwolf** [comment]
It happens everywhere. Pets have problem pass through shallow water, bumpy terrain. They stuck in high places with sharp edges, don't wanna jump down if they are ordered to attack target or follow their master. At least they are not moving through the walls (most of them), and winged pets can properly fly.
