### ISSUE TITLE
[EN][Deepholm] Alliance Gunship

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#1621]
While questing on the Alliance Gunship every few minutes the character gets teleported outside the Deepholm map to the north edge and falls down (if not mounted when teleported). Making completing quests on the ship really annoying.

This was NOT fixed in rev 4176.

**Comment by Aydien** [comment]
hope, fix will be soon for now its rly frustrating

**Comment by Rageless** [comment]
Still bugged , also i cannot  see the quest npc on the ship ( stormcaller mylra) people told me to wait there but when i wait a while i get teleported outside deepholm

**Comment by muddykinz** [comment]
Writing here to get notified of when this is fixed

**Comment by meowmewo** [comment]
While waiting for my Ressurection sickness to go off due to not being able to reach my corpse...Still bugged.

**Comment by Kubion** [comment]
Still bugged

**Comment by Wolffenstein** [comment]
Fixed in rev 4319.
