### ISSUE TITLE
[PL][Quest][Westfall] A Vision of the Past

### ISSUE THREAD

**Issue by Misiac** [Atlantiss/BugTracker#1622]
Quest jest niemożliwy do ukończenia ponieważ nie odpala się animacja walki.
W dodatku po użyciu q itemka na początku instancji przelatujemy przez ściany a powinniśmy teleportować się do jaskini z statkiem. 
Video:  https://www.youtube.com/watch?v=gYVayNuhrzg
Quest : http://www.wowhead.com/quest=26320/a-vision-of-the-past

**Comment by deathscare666** [comment]
i have the same problem

**Comment by Athelon** [comment]
https://github.com/Athelon/Mari/issues/1

**Comment by Theraden** [comment]
Phase sequence is broken...cannot continue in Westfall questline.

**Comment by armano2** [comment]
again same issue xd

**Comment by davidrivasdos** [comment]
the quest is still broken...

**Comment by Roraa** [comment]
Still broken

**Comment by Ambiorixa** [comment]
Still broken

**Comment by lourrific** [comment]
1 year later and it's still broken.

**Comment by Athelon** [comment]
Still broken...

**Comment by karhima** [comment]
Still broken

**Comment by RobHibicus** [comment]
Still bugged. We're not asking for it to be scripted, but to at least be able to turn it in to progress in the zone.

**Comment by Robisant** [comment]
1 year passed since the issue was posted,still no fix?

**Comment by arndry** [comment]
still broken. I wa thinking that the bugged mission was Rise of The Brotherhood (It is broken by the way) but this is the main problem from this line of missions

**Comment by kvokul** [comment]
lata mijają i quest wciąż nie działa.

Dodam, żę bez niego nie da się zrobić Westfall Quests, więc kolejny achivment jest wyjęty.

Kolejna kropelka do basenu elementów, które mają gracze z Sunwella grający na tym serwerze, a tacy co przeszli z innych serwerów, lub grali tylko tutaj już nie.

**Comment by BoudikaPL** [comment]
Ten Quest dało się wykonać jeszcze na początku tego roku. Nawet bez wchodzenia do instancji. Obecnie na minimapie jest żółty znak zapytania a Questu oddać się nie da (nie ma animacji przy wieży).

**Comment by Quellz** [comment]
Bumping. Been wanting to do this quest for precisely 8 days now. Needs to be fixed, as it is essencial to the achievement for Westfall and the primary storyline in that area.

**Comment by Bikinitrusa** [comment]
Me bumping. 
I know Westfall is a bit deserted-ish, but not like this u guys... u are devs of this server, a lot of quests in Westfall are either unobtainable or unable to turn in, do something about it!

**Comment by Aedomus** [comment]
I confirm...this part of the quest "part 5" (http://www.wowhead.com/quest=26320/a-vision-of-the-past) when in the vision inside the Deadmines, nothing happens and was forced to leave "vehicle".

**Comment by victordavid23** [comment]
26/9/16 THIS QUEST STILL BROKEN.

**Comment by seanwow1337** [comment]
Please repair this quest its 1,2years in this bugtracker and still no repaired.

**Comment by Snapy853585** [comment]
This quest is still not achievable. The item works fine but the conversation doesn't start.

**Comment by ZFake** [comment]
Still broken.

**Comment by Fabrikantje** [comment]
...Still broken. Can this quest at least be completable? Instant turn-in or smth.

**Comment by krecik88** [comment]
fixed in 5244

**Comment by m1szczu** [comment]
today i tried to finish this quest but the problem still occurs

**Comment by LaveniaGithub** [comment]
Server still needs update before it is fixed.
