### ISSUE TITLE
[PL][Kosmetyka][Howling Fjord]  Forsaken Crossbowaman +2

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#1626]
http://www.wowhead.com/npc=23883/forsaken-crossbowman
 - mają kij zamiast kuszy

http://www.wowhead.com/npc=23865/vengeance-bringer
 - zły model broni
 - większośc się randomwo a powinny być ustawione w szykach

http://www.wowhead.com/npc=23778/dark-ranger-lyana
 - zły model broni
 - stoi w złym miejscu

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
