### ISSUE TITLE
[EN][Quest][Durotar] Meats to Orgrimmar

### ISSUE THREAD

**Issue by KubqoA** [Atlantiss/BugTracker#1631]
wowhead link: http://www.wowhead.com/quest=6365/meats-to-orgrimmar
openwow link: http://cata.openwow.com/quest=6365

Problem is that the quest giver won't give it to you. Exactly the quest giver is not marked as quest giver with some exclamation mark he is only like a normal npc. Please help me. This is start of quest line.

Thank you.

Character Prístroj LvL 8 Druid

**Comment by Bildo** [comment]
rev. 4353 by Quban
