### ISSUE TITLE
[PL][Quest][Badlands] Lifting the Veil

### ISSUE THREAD

**Issue by Misiac** [Atlantiss/BugTracker#1632]
Po wzięciu questa z tego co wiem powinien pojawiać się smok.
Żadnego video nie znalazłem dlatego też nie wiem dokładnie jak działa ten quest.
Quest: http://www.wowhead.com/quest=27770/lifting-the-veil

**Comment by nerv234** [comment]
Po wzięciu quest Rhea powinna mówić coś, po czasie quest powinien się zaliczyć i pojawić się powinien smok, administracja wie o tym:).

**Comment by Thefakemccoy** [comment]
I cant really understand anything here but as of May, 6 2015 it is still bugged. It does not trigger the dragon.

**Comment by lourrific** [comment]
This quest is the second part of a six part quest chain and as a result from it being bugged the following quests are unavailable.

1. Third Sample: Implanted Eggs http://www.wowhead.com/quest=27771/third-sample-implanted-eggs
2. Rhea Revealed http://www.wowhead.com/quest=27769/rhea-revealed
3. The Venerable Doctor Blam http://www.wowhead.com/quest=27772/the-venerable-doctor-blam
4. Troggish Troubles http://www.wowhead.com/quest=27789/troggish-troubles

**Comment by nerv234** [comment]
And y u know those quest you listed you think they're working? y're wrong, they aren't working.

**Comment by lourrific** [comment]
If for whatever reason I can not do a quest then it is broken. 1 quest breaks 4 other quests. they are all broken.

**Comment by nerv234** [comment]
Btw. Badlands is little complicated so please stop reporting anything from badlands/stop spamming it won't do anything about it.

I'm content fixer and i already script all Badlands and it is waiting for apply. But it is entire zone and it can wait some time for one dev to find time.... Please understand it is frustrating to me seeing badlands spaming on bt.

**Comment by Thefakemccoy** [comment]
You say its fixed waiting for it to be applied. I understand that but this is the first time i have heard of it. I dont think most people know you have finished it. They are only reporting what is broke atm. Is that not what people should do?

Are we to assume everything is waiting to be applied in a fix? Meaning everything is done.

I am being serious you seem to be getting mad but i see nothing on the channel log about this is done waiting for to be applied.

**Comment by lourrific** [comment]
With the exception of  [EN] [Quest] [Badlands] Lifting the Veil I have found a total of 5 bugged quests in badlands that I have done a search for and nothing has come up as reported or being worked on ect. 

So I assume I'm reporting the bugged quests correctly? 

If nothing comes up on the search about it then it's a legitimate bug that needs to be reported. How am I to know what has been fixed so far and waiting to be applied?

btw it's actually more than 5 bugged quests because a few of them are part of a quest chain and that one bugged quest ruins the others.

**Comment by nerv234** [comment]
So instead of trusting me you started spamming another badlands bugs:)  You will get what you deserve, Badlands will be applied when i'll be promoted to developer, so you will wait few month longer.

**Comment by ylluminate** [comment]
5 of us here having this issue as well.  Looking forward to the patch!

**Comment by coba999** [comment]
Didn't working.
http://www.wowhead.com/quest=27770/lifting-the-veil - quest
http://www.wowhead.com/npc=46654/rhea - quest giver
https://www.youtube.com/watch?v=Egz2AsdgOpo - video how it's works

**Comment by eryczek1615** [comment]
bump

**Comment by zelekxmalinowy** [comment]
Nadal nie działa

**Comment by nerv234** [comment]
Już nie jestem jakkolwiek związany z serwerem, zostawiłem kod + sqle a przynajmniej przekazałem komuś z ekipy, także jak nie podobał się codestyle albo optymalizacja to długo by nie zeszło do ogarnięcia tego, na pewno nie dłużej niż mi zeszło na testy ograniczeń kąta z lewej i prawej do targetingu w jednej z minigier:) Btw. przekazując kod miałem nadzieję że trafi na serwer, i mimo że nie jestem już związany z serwerem jakkolwiek to kod już przekazałem także fajnie by było widzieć że się przydał.

**Comment by Angelo-DM-** [comment]
As Horde, i've done only 9 quests in the Badlands...
The quest [Lifting the Veil (ID:27770)](http://www.wowhead.com/quest=27770/lifting-the-veil) blocks all the other quests!
Only when you complete the [Reha (ID: 46654)](http://www.wowhead.com/npc=46654) chain quests you are able to take all the others...

Reha chain:
1. First Sample: Wild Eggs -> OK
2. Second Sample: Whelps -> OK
__3. Lifting the Veil -> BUGGED!
4. Third Sample: Implanted Eggs
5. Rhea Revealed -> it spawn [Rheastrasza (ID:46655)](http://www.wowhead.com/npc=46655/rheastrasza)
6. The Venerable Doctor Blam
7. Troggish Troubles__

**Comment by tkupcewicz** [comment]
[Lifting the Veil](http://www.wowhead.com/quest=27771/third-sample-implanted-eggs) leads to another quest which rewards players with one and only unique [chestpiece](http://www.wowhead.com/item=63161/vest-of-restraint) in World of Warcraft, so it would be nice to get it done.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6774

**Comment by attan0** [comment]
bump

**Comment by Patriag** [comment]
Still not working, bump

**Comment by karolnpc** [comment]
Bump

**Comment by Llagas** [comment]
Please fix this quest, it would be really nice for the Loremaster achievement :)

**Comment by Bildo** [comment]
duplicate

**Comment by ExperBug** [comment]
bump

**Comment by aholler2** [comment]
Bump. Lifting the veil still not working.

**Comment by XreaperDK** [comment]
Bildo, your reason for closing as a duplicate is one that describes the zone for questing as a whole and actually references this specific post as a bug, This is still a major bug and has not been fixed and not a duplicate, as any other duplicate post has been redirected here as the origin!

**Comment by coba999** [comment]
@XreaperDK just quit this server, as i done, nobody will fix this and many other bugs. Something wrong with developers.
