### ISSUE TITLE
[PL][Death Knight][Spell] Pillar of Frost

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1633]
Pillar of Frost: http://cata.openwow.com/spell=90259
Glyph of Pillar of Frost: http://cata.openwow.com/item=43553
Glyph of Pillar of Frost (spell): http://cata.openwow.com/spell=58635

Spell Pillar of Frost BEZ GLYPHA daje immune na wszelkie efekty crowd control, a nie powinien, glyph powoduje jedynie, że postać nie może się poruszać (co jest w porządku). 
Dodatkowo daje immune na disarm'a co nie jest efektem powodującym utratę kontroli nad postacią (tak jest w opisie glypha).

**Comment by Varchord** [comment]
Znaczy mówisz, że czysty PoF działa jakby był z glyphem ale z możliwością poruszania się?

**Comment by Arcadia713** [comment]
Dokładnie.

**Comment by Wolffenstein** [comment]
Fixed in rev 4255. PoF POWINIEN dawac immune na Disarm pomimo, że nie jest tak napisane w tooltipie.

**Comment by Arcadia713** [comment]
http://us.battle.net/wow/en/forum/topic/7710221275
Potwierdzenie, że nie powinien dawać immune na disarma:
"Hi guys and gals. Just had an idea I'd like to throw out there. (...) Remove the knockback immunity from pillar of frost and replace it with a disarm immunity mechanic. (...)"

http://www.arenajunkies.com/topic/172636-glyph-of-pillar-of-frost-is-all-wrong/
Tu o glyphie ale i o spellu - nigdzie nie ma powiedziane, że daje immune na disarm.
