### ISSUE TITLE
[PL][Warrior][Spell] Thunder Clap

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1634]
http://www.wowhead.com/spell=6343/thunder-clap

Problem podobny do https://github.com/Atlantiss/BugTracker/issues/180

Jeśli Thunder Clap trafi i zada damage to część odpowiedzialna za zmniejszenie attack speed nadal może zmissować. Nie powinno tka być

**Comment by Wolffenstein** [comment]
Przecież to jest jeden spell, hit result jest liczony dla całości, nie dla poszczególnych efektów. To zupełnie co innego od Frost Fever, bo tam był triggerowany spell. 

Video or it didn't happen.

**Comment by Varchord** [comment]
No i rób mu teraz wideo. Uczyć sie miałeś! :<

**Comment by Jenovas** [comment]
Zamykam. Jak będzie filmik na którym widać że jest jak mówisz to proszę stworzyć nowe zgłoszenie.
