### ISSUE TITLE
[EN][Cosmetic] Captain Harker

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#1635]
http://www.wowhead.com/npc=24037/captain-harker
 - lack a weapon
 - nothing yells

+

http://www.wowhead.com/npc=23983/north-fleet-ma
 - lack a weapon

http://www.wowhead.com/npc=23982/forsaken-deckhand
 - missed npc

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
