### ISSUE TITLE
[EN][Quest][Dragonblight] Into the Fold

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#1638]
http://www.wowhead.com/quest=11978/into-the-fold

the conditions to pick this quest up should be doing http://www.wowhead.com/quest=11977/a-tauren-among-taunka OR http://www.wowhead.com/quest=11979/the-taunka-and-the-tauren but it wants you to do BOTH of them
(sucks because the prequest for that first one is bugged)

**Comment by lanrutcon** [comment]
*Across Transborea* is working, at least I did it 3 days ago...
But, yeah, you should get *Into the Fold* after complete one of them...

**Comment by Quban** [comment]
```UPDATE quest_template SET ExclusiveGroup = 11977, NextQuestId = 11978 where id in (11977, 11979);```

**Comment by Bildo** [comment]
rev. 4353 by Quban
