### ISSUE TITLE
[PL][Death Knight][Spell] Pillar of Frost - disarm immune

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1643]
Pillar of Frost: http://cata.openwow.com/spell=90259
Disarm: http://cata.openwow.com/spell=676
Dismantle: http://cata.openwow.com/spell=51722
Psychic Horror: http://cata.openwow.com/spell=65545

U nas Pillar of Frost daje immune na efekt disarmu, czego nie powinien robić - wiem, że Wolf pisał innaczej jednak mam kilka dowodów, że tak nie powinno być.

https://www.youtube.com/watch?v=X_J91ZshXOo&feature=player_detailpage#t=247
4:07+ DK używa Pillara (bez glypha, bo może chodzić :P) warrior daje mu disarm (nawet podkreślone, że go trinketuje od razu, czyli działa).

http://us.battle.net/wow/en/forum/topic/7710221275
Potwierdzenie, że nie powinien dawać immune na disarma:
"Hi guys and gals. Just had an idea I'd like to throw out there. (...) Remove the knockback immunity from pillar of frost and replace it with a disarm immunity mechanic. (...)"

"Can't do that to pillar of frost. If an opponent is being good and watching buffs etc, he should save his disarm for then. He should wait for us to pop strength trink and pillar then use his disarm, negating our burst."

http://www.arenajunkies.com/topic/172636-glyph-of-pillar-of-frost-is-all-wrong/
Tu o glyphie ale i o spellu - nigdzie nie ma powiedziane, że daje immune na disarm.

PS: Założyłem nowy temat, bo stary https://github.com/Atlantiss/BugTracker/issues/1633 został zamknięty.

**Comment by Wolffenstein** [comment]
Bez glypha może i tak, ale z glyphem według blizzarda disarm powinien być.

**Comment by Arcadia713** [comment]
"How about if the glyph makes you silence and disarm immune, something different and needed if you ask me." 

Nie wiem czy dobrze zrozumiałem ale w temacie http://www.arenajunkies.com/topic/172636-glyph-of-pillar-of-frost-is-all-wrong/ koleś ma przemyślenia "co by było gdyby glyph dawał immune na silence i disarm" - według tego tematu daje on immune tylko na formy cc takie jak feary, stuny, horrory, incapacity. Sam nie wiem już, raczej by nie pisali jakby dawał immune na disarma :p

**Comment by kadi2** [comment]
Nie wiem czy ma to jakies wieksze znaczenie, jakie immune ma DK z glyphem. Takie wypowiedzi znalezione gdziekolwiek nie maja sensu. Zaloze sie, ze nikt nie testowal az tak doglebnie tego glypha bo byl kompletnie bezuzyteczny. Prawdopodobnie autorzy tych wypowiedzi rowniez tego nie robili.

**Comment by Wolffenstein** [comment]
Ponadto wypowiedzi są z początku listopada 2010, a patch 4.0.1 (z glyphem) wszedł 12 października, więc też nie wydaje mi się, żeby tak dokładnie zdążyli to przetestować.

**Comment by Arcadia713** [comment]
Hmmm no w sumie racja, zobaczymy jak po poprawce będzie, czy bez glypha będzie immune na disarm - jeśli nie to wywalić, spalić ten temat :) Pzdr
