### ISSUE TITLE
[PL][Talent][Warrior] Blood Frenzy/Trauma

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#1646]
Mortal Strike powinien odświeżać debuff Trauma (brak linku) z talentu Blood Frenzy
http://wow.gamepedia.com/Blood_Frenzy
Obecnie trzeba odswiezac go rendem, zeby nie schodzil.

https://www.youtube.com/watch?v=99U7N1On8D4 - Widac odswiezanie Traumy przez Mortal Strike.

**Comment by Morderczyk** [comment]
On w ogole nie powinein schodzic gdy na targecie jest Rend lub inna dota Warka, u nas to zle dziala i po jakims czasie schodzi

**Comment by Jenovas** [comment]
Inna dotka? Warek ma renda i deep wounds tak?

**Comment by Aviannaqt** [comment]
Tak.

**Comment by Jenovas** [comment]
Fixed in rev  4262
