### ISSUE TITLE
[EN][Quest][Winterspring] 'Borrowing' From the Winterfall

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#1647]
http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall

In this quest we have to steal some meat from furbolg camps and feed it to our pet.

There are none smoked meat racks (http://www.wowhead.com/object=208189), so we can't get quest items (http://www.wowhead.com/item=68645).

Also, my guess is that we don't get credit for giving meat to our cub (since we don't in #1616)

**Comment by american123** [comment]
Plz fix:)

**Comment by docc46** [comment]
bump

**Comment by Aival94** [comment]
Just posting a video of how it should work.

https://youtu.be/mDHUWX7Qses?t=256

**Comment by biaicc98** [comment]
Still bugged as of 30/08/2015

**Comment by supreemetac** [comment]
Could you at least disable the bugged quest because its annoying as hell to get to winterspring and get the bugged quest.

**Comment by localhost127001** [comment]
bump for disabling quest until get fix

**Comment by alexsanderr5205** [comment]
Still bugget 09/21/2016

**Comment by Navedonar** [comment]
smoked meat objects fix http://community.atlantiss.eu/index.php?/topic/11656-objectsmoked-meat/#entry55277

**Comment by Berlin1993** [comment]
23.09.2016 BUGGED

**Comment by Navedonar** [comment]
objects added

**Comment by mastercho** [comment]
I just try it today and it's still bugged, can't loot the meat from object 
![wowscrnshot_101916_025642](https://cloud.githubusercontent.com/assets/10222100/19504212/4c7e49a4-95b0-11e6-8109-5a6401d181ff.jpg)

**Comment by Bulvers** [comment]
bump

**Comment by roirraWedorehT** [comment]
As of 6/10/2018, can get the smoked meat but feeding 6 of the smoked meat to the cubs doesn't do anything - quest isn't counted as complete.

**Comment by calecale13** [comment]
The meet can be picked up but feeding it does nothing
