### ISSUE TITLE
[PL] [Pet] [Warlock] Missing PetActionBar

### ISSUE THREAD

**Issue by ammeba** [Atlantiss/BugTracker#1648]
Dzień dobry :> Mój problem jest taki, że w ogóle nie pojawia mi się Pet Action Bar. Po otwarciu spellboka zakładka demona również nie występuję, więc wg gry pet jest, ale go nie ma :D
Działało przez krótką chwilę po uzyskaniu Voida, ale po queście z mountem niestety znowu padło.
Próbowałam z/bez addonów, czyściłam cache i takie tam. Nadal nie działa. Da się z tym grać, no ale jednak jest to dla mnie irytujące.

**Comment by qubuslabadz** [comment]
Jaki masz level? Od 10 levela dopiero się uczy od trenera controli peta.

**Comment by Asavel** [comment]
A nie uzywasz jakiś addonów zmieniających UI ALbo nie robisz /reload ?

**Comment by ammeba** [comment]
14 lvl. 
Używam addonów, co nie zmienia faktu że bez jakichkolwiek addonów, na standardowym Blizzard UI i domyślnymi ustawieniami też się nie pokazuje :c
Asavel - raz czy dwa mi się zdarzyło /reload użyć.

**Comment by Arcadia713** [comment]
Byłaś u trenera nauczyć się "control demon"?

**Comment by ammeba** [comment]
Arcadia - byłam...
... ale żeby było śmiesznie ponownie włączyłam grę i zaczęło działać. Ciekawe na jak długo i czemuż nie działało wcześniej :o

**Comment by Asavel** [comment]
To przez  /reload ;)
