### ISSUE TITLE
[EN][Spell][Druid] Wild Mushrooms

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#1649]
Mushrooms also missing the sound effect when spawned and are missing animation when detonated.

Proof: http://youtu.be/RK81Qn9d940?t=20s

Openwow links:
http://cata.openwow.com/spell=78777
http://cata.openwow.com/spell=88751

**Comment by Jenovas** [comment]
They have an animation and sound effect - https://www.youtube.com/watch?v=y_0iT4tUboI&feature=youtu.be

**Comment by kadi2** [comment]
Indeed, but there's no this specific sound when you cast a mushroom.
