### ISSUE TITLE
[EN][Core] Knockback effects, rooted targets and bladestorm.

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1652]
Rooted targets and warriors with Bladestorm buff should be immune to knock-back effects. Haven't checked if the Bladestorm has been fixed, but it was bugged for so long time.

http://cata.openwow.com/spell=46924 // Bladestorm
http://cata.openwow.com/spell=50516 // Typhoon
http://cata.openwow.com/spell=51490 // Thunderstorm
http://cata.openwow.com/spell=1463 // Mana Shield with Arcane Mage talents.

To note: Characters should be still knock-able in other Crowd Control effects. It should be just exception for root effects.

**Comment by Wolffenstein** [comment]
Fixed in rev 4258.
