### ISSUE TITLE
[EN][Quests][Un'Goro Crater]Quests missing(quest order)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1657]
There are many quests in Un'Goro Crater which are missing.This probably happen because of the quest order so i will give every quest on Un'Goro Crater as obtainable or missing and giving their quest order.

[Finding the Source](http://www.wowhead.com/quest=24742) - obtainable (unlock when reach level 49)
[Speak With Spraggle](http://www.wowhead.com/quest=24794) - obtainable (unlock when complete [Finding the Source](http://www.wowhead.com/quest=24742))
[Lost!](http://www.wowhead.com/quest=24734) - obtainable (unlock when complete [Speak With Spraggle](http://www.wowhead.com/quest=24794))
[A Little Help From My Friends](http://www.wowhead.com/quest=24735) - obtainable (unlock when comeplete [Lost!](http://www.wowhead.com/quest=24734))

[Adventures in Archaeology](http://www.wowhead.com/quest=24698) - missing (unlock when complete [Mossy Pile](http://www.wowhead.com/quest=24693)) (breadcumb with [Roll the Bones](http://www.wowhead.com/quest=24730))
[Roll the Bones](http://www.wowhead.com/quest=24730) - missing (unlock when complete [Adventures in Archaeology](http://www.wowhead.com/quest=24698)) (breadcumb with [Adventures in Archaeology](http://www.wowhead.com/quest=24698))
[The Fossil-Finder 3000](http://www.wowhead.com/quest=24708) - missing (unlock when complete [Roll the Bones](http://www.wowhead.com/quest=24730))
[A Tale of Two Shovels](http://www.wowhead.com/quest=24709) - missing (unlock when complete [The Fossil-Finder 3000](http://www.wowhead.com/quest=24708))
[The Western Pylon](http://www.wowhead.com/quest=24723) - missing (unlock when complete [A Tale of Two Shovels](http://www.wowhead.com/quest=24709))

[An Abandoned Research Camp](http://www.wowhead.com/quest=24866) - obtainable (unlock when reach level 49)

[An Important Lesson](http://www.wowhead.com/quest=24703) - obtainable (unlock when reach level 51)

[Hero's Call: Un'Goro Crater!](http://www.wowhead.com/quest=28525) - obtainable (unlock when reach level 50) (breadcumb with [Tropical Paradise Beckons](http://www.wowhead.com/quest=24911))
[Tropical Paradise Beckons](http://www.wowhead.com/quest=24911) - obtainable (unlock when reach level 49) (breadcumb with [Hero's Call: Un'Goro Crater!](http://www.wowhead.com/quest=28525))
[Volcanic Activity](http://www.wowhead.com/quest=24740) - missing (unlock when complete [Hero's Call: Un'Goro Crater!](http://www.wowhead.com/quest=28525) or [Tropical Paradise Beckons](http://www.wowhead.com/quest=24911))
[Blazerunner](http://www.wowhead.com/quest=24690) - missing (unlock when complete [Volcanic Activity](http://www.wowhead.com/quest=24740))

[Finding Stormclaw](http://www.wowhead.com/quest=24854) - obtainable (unlock when level 49)
[Claws of White](http://www.wowhead.com/quest=24719) - obtainable (unlock when level 49(breadcumb with quest [Finding Stormclaw](http://www.wowhead.com/quest=24854))
[Carried on the Waves](http://www.wowhead.com/quest=24686) - obtainable (unlock when complete [Claws of White](http://www.wowhead.com/quest=24719))
[Flowing to the North](http://www.wowhead.com/quest=24689) - obtainable (unlock when complete [Carried on the Waves](http://www.wowhead.com/quest=24686))
[Bouquets of Death](http://www.wowhead.com/quest=24687) - obtainable (unlock when complete [Flowing to the North](http://www.wowhead.com/quest=24689))
[Zen'Aliri](http://www.wowhead.com/quest=24688) - don not know ((unlock when complete [Flowing to the North](http://www.wowhead.com/quest=24689))(breadcumb with [Finding Stormclaw](http://www.wowhead.com/quest=24854))
[Aberrant Flora](http://www.wowhead.com/quest=24855) - obtainable (unlock when complete [Flowing to the North](http://www.wowhead.com/quest=24689) and have completed [Zen'Aliri](http://www.wowhead.com/quest=24688)if not completed first [Finding Stormclaw](http://www.wowhead.com/quest=24854))
[The Eastern Pylon](http://www.wowhead.com/quest=24721) - obtainable (unlock when complete [Aberrant Flora](http://www.wowhead.com/quest=24855))

[Chasing A-Me 01](http://www.wowhead.com/quest=24714) - missing (unlock when complete [Volcanic Activity](http://www.wowhead.com/quest=24740), [Blazerunner](http://www.wowhead.com/quest=24690), [Peculiar Delicacies](http://www.wowhead.com/quest=24691), [Mossy Pile](http://www.wowhead.com/quest=24693) and 
[Marshal's Refuse](http://www.wowhead.com/quest=24701))
[Repairing A-Me 01](http://www.wowhead.com/quest=24715) - missing (unlock when complete [Chasing A-Me 01](http://www.wowhead.com/quest=24714))
[Serving A-Me 01](http://www.wowhead.com/quest=24926) - missing (unlock when complete [Repairing A-Me 01](http://www.wowhead.com/quest=24715))

[Crystal Charge](http://www.wowhead.com/quest=24725) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Crystal Force](http://www.wowhead.com/quest=24726) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Crystal Restore](http://www.wowhead.com/quest=24724) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Crystal Spire](http://www.wowhead.com/quest=24727) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Crystal Ward](http://www.wowhead.com/quest=24728) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Crystal Yield](http://www.wowhead.com/quest=24729) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))

[Damsels Were Made to be Saved](http://www.wowhead.com/quest=24705) - obtainable (unlock when reach level 51)

[The Shaper's Terrace](http://www.wowhead.com/quest=24694) - missing (unlock when complete [The Eastern Pylon](http://www.wowhead.com/quest=24721), [The Northern Pylon](http://www.wowhead.com/quest=24722), [The Western Pylon](http://www.wowhead.com/quest=24723) and [Crystals of Power](http://www.wowhead.com/quest=24720))
[Ever Watching From Above](http://www.wowhead.com/quest=24695) - missing (unlock when complete [The Shaper's Terrace](http://www.wowhead.com/quest=24694))

[Crystals of Power](http://www.wowhead.com/quest=24720) - obtainable (unlock when reach level 49)

[Super Sticky](http://www.wowhead.com/quest=24737) - missing (unlock when complete [Mossy Pile](http://www.wowhead.com/quest=24693))
[Gormashh the Glutinous](http://www.wowhead.com/quest=24699) - missing (unlock when complete [Super Sticky](http://www.wowhead.com/quest=24737))

[Hard to Harvest](http://www.wowhead.com/quest=24700) - missing (unlock when reach level 49)

[Here Lies Dadanga](http://www.wowhead.com/quest=24702) - missing (unlock when rach level 49)

[How to Make Meat Fresh Again](http://www.wowhead.com/quest=24697) - obtainable (unlock when reach level 50)

[Is This Stuff Still Good?](http://www.wowhead.com/quest=24865) - obtainable (unlock when reach level 49)

[Marshal's Refuse](http://www.wowhead.com/quest=24701) - missing (unlock when complete [Volcanic Activity](http://www.wowhead.com/quest=24740), [Blazerunner](http://www.wowhead.com/quest=24690), [Peculiar Delicacies](http://www.wowhead.com/quest=24691), and [Mossy Pile](http://www.wowhead.com/quest=24693))

[Peculiar Delicacies](http://www.wowhead.com/quest=24691) - missing (unlock when complete [Blazerunner](http://www.wowhead.com/quest=24690))
[Mossy Pile](http://www.wowhead.com/quest=24693) - missing (unlock when complete [Peculiar Delicacies](http://www.wowhead.com/quest=24691))

[Shizzle's Flyer](http://www.wowhead.com/quest=24736) - obtainable (unlock when reach level 49)

[The Apes of Un'Goro](http://www.wowhead.com/quest=24717) - missing (unlock when complete [Gormashh the Glutinous](http://www.wowhead.com/quest=24699))

[The Fare of Lar'korwi](http://www.wowhead.com/quest=24731) - obtainable (unlock when reach level 49)
[The Scent of Lar'korwi](http://www.wowhead.com/quest=24732) - obtainable (unlock when complete [The Fare of Lar'korwi](http://www.wowhead.com/quest=24731))
[The Bait for Lar'korwi](http://www.wowhead.com/quest=24733) - obtainable (unlock when complete [The Scent of Lar'korwi](http://www.wowhead.com/quest=24732))

[The Ballad of Maximillian](http://www.wowhead.com/quest=24707) - missing (unlock when complete [The Spirits of Golakka Hot Springs](http://www.wowhead.com/quest=24706))

[The Evil Dragons of Un'Goro Crater](http://www.wowhead.com/quest=24704) - obtainable (unlock when reach level 51)

[The Fledgling Colossus](http://www.wowhead.com/quest=24692) - missing (unlock when complete [Blazerunner](http://www.wowhead.com/quest=24690))

[The Mighty U'cha](http://www.wowhead.com/quest=24718) - missing (unlock when you have or complete [The Apes of Un'Goro](http://www.wowhead.com/quest=24717))

[The Northern Pylon](http://www.wowhead.com/quest=24722) - missing (unlock when complete [The Apes of Un'Goro](http://www.wowhead.com/quest=24717))

[The Spirits of Golakka Hot Springs](http://www.wowhead.com/quest=24706) - obtainable (unlock when complete [Damsels Were Made to be Saved](http://www.wowhead.com/quest=24705)) #398

Wowhead link: [Un'Goro Crater quests](http://www.wowhead.com/quests=1.490?filter=si=1)
Wowpedia link: [Un'Goro Crater quests](http://wow.gamepedia.com/Un'Goro_Crater_quests)

NOTE:some of them will not be missing but just not be available because of pre-quests not completed or missing. Sorry for the big post.

**Comment by Bildo** [comment]
most of the things should dissapear

**Comment by Aival94** [comment]
Sorry but i cannot know which one is the real problem as after some quests there is only one obtainable(bugged) quest and not other.

**Comment by cosminush** [comment]
On 13 July 2015 still bugged "Finding the Source" [http://www.wowhead.com/quest=974/finding-the-source].

**Comment by Aival94** [comment]
This one Quest @cosminush is horde but the main post is for alliance and closed.So better make an other report about this one if not already exist.
