### ISSUE TITLE
[EN] [Spell] [Paladin] Seal of Insight

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1658]
Seal of Insight ([openwow1](http://cata.openwow.com/spell=20165), [openwow2](http://cata.openwow.com/spell=20167), [wowhead](http://www.wowhead.com/spell=20165)) does seem to heal more than the tooltip indicates, at least at my low level 41.

According to the combatlog it heals for **187** per proc.

The tooltip says it should heal for **84** per proc.

Openwow says it should heal 15% AP + 15% SP per proc. In my case with 423 AP and 138 SP (I guess this includes the 60%Str->SP conversion by the "touched by the light" talent), that would be **84**.

Am I missing something? I also have the +6% healing talent "divinity", but that doesn't explain the whole difference. Maybe the tooltip would be right at level 85, but at low levels the formula is a bit different?

![pic](http://i.imgur.com/mgzjsiD.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4257.
