### ISSUE TITLE
[EN][Quest-priest] Aiding the injured

### ISSUE THREAD

**Issue by box95** [Atlantiss/BugTracker#1666]
I can't find the quest on WoWHead
http://wow.gamepedia.com/Quest:Aiding_the_Injured
After learning "Flash Heal" you should use it on the Injured Draenei but they can't be healed

**Comment by Bildo** [comment]
can't be healed because ?

**Comment by box95** [comment]
Because when you cast the healing spell it heals yourself even if you targeted him

**Comment by Rushor** [comment]
this quest was replayed with http://de.wowhead.com/quest=26970/das-richtige-wort

**Comment by slikfang** [comment]
Any fix on this quest coming soon? Also any suggestions on what to do in the meantime? Having the same issue of healing self...
