### ISSUE TITLE
[EN][NPC][Howling Fjord] Iron Rune Constructs and You: Rocket Jumping

### ISSUE THREAD

**Issue by Norfik** [Atlantiss/BugTracker#1668]
Don't give credit. After using the working bench we are thrown into a large distance and theres no action button with spell "Rocket Jump" to use.

Vehicle entry: http://www.wowhead.com/npc=24806/iron-rune-construct
Spell: http://www.wowhead.com/spell=44498/rocket-jump

The way it works on Blizz: https://www.youtube.com/watch?v=6M-XhkVLHBc
The way it works on Atlantiss: http://youtu.be/yfTnk6hvuGk

**Comment by bgb** [comment]
Confirmed. Cant complete this quest.

**Comment by krauza666** [comment]
1. Wrong quest route
2. It's possible to complete quest, but we need kill all Proto-Drakes on ember clutch area.

**Comment by Bildo** [comment]
fixed
