### ISSUE TITLE
[PL][Shaman][spell/guardian] Elementale nie skaluja sie z crit chance shamana

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1669]
Fire elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

Earth elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

U shamana z crit chance na poziomie 25% na 60 hitow guardiany maja 3 crity. Cos tu jest nie tak. To powinno po czesci zalatwic zanizony dps ELE shama. Testowane wielokrotnie, wiec to nie jest wina przypadku.

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
