### ISSUE TITLE
[EN] [Quest] [Thousand Needles / Feralas] The Grimtotem are Coming (Thousand Needles Questline)

### ISSUE THREAD

**Issue by ariean** [Atlantiss/BugTracker#1672]
I completed Hero's Call: Thousand Needles! (http://www.wowhead.com/quest=28503/heros-call-thousand-needles)

But can not receive the quest The Grimtotem are Coming (http://www.wowhead.com/quest=25486/the-grimtotem-are-coming) from Caryssia Moonhunter (http://www.wowhead.com/npc=39946/caryssia-moonhunter).

This effectively blocks the entire Thousand Needles quest chain.

The Grimtotem are Coming should be available after any of the three pre-quests, but as far as I know, in server, it can only be done after To New Thalanaar (http://www.wowhead.com/quest=25481/to-new-thalanaar). Characters who have done the Hero's Call, can neither do To New Thalanaar, nor The Grimtotem are Coming. For us, there are no ways to do the Thousand Needles quest chain.

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by ariean** [comment]
Thank you so much. I'm really really impressed. God, I LOVE this server. Thank you once again!
