### ISSUE TITLE
[PL][Spell][Deathknight] Death and Decoy

### ISSUE THREAD

**Issue by Pilarka** [Atlantiss/BugTracker#1673]
Gdy uzyjemy Death and Decoy i przejdziemy za sciane DnD nie zadaje dmgu i wyskakuje komuikat "target is not in lane isght".

**Comment by Wojmistrz** [comment]
wowhead link

**Comment by Jaffar1989** [comment]
http://www.wowhead.com/spell=39658/death-and-decay
masz pan :P

**Comment by aneq** [comment]
podales link do spella bossa a nie do class ability dk ....

**Comment by arekczup** [comment]
http://www.wowhead.com/spell=143375/death-and-decay
moja wina

**Comment by Jenovas** [comment]
Fixed in rev 4264
