### ISSUE TITLE
[EN] [QUEST] [Tirisfal Glades] Caretaker Caice

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1674]
Link: [Caretaker Caice (ID: 28652)](http://www.wowhead.com/quest=28652)

This quest is missing from the Questgiver [Undertaker Mordo (ID: 1568)](http://www.wowhead.com/npc=1568),
and the quest [The Wakening (ID: 24960)](http://www.wowhead.com/quest=24960), that should be obtainable after completing this one,
instead is direclty available to the questgiver [Caretaker Caice (ID: 2307)](http://www.wowhead.com/npc=2307).

**Comment by Bildo** [comment]
fixed
