### ISSUE TITLE
[EN][Quest] Burning Blade Ear

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#1676]
Burning Blade ears, collected from burning blade npcs in Desolace ( http://www.wowhead.com/item=49203/burning-blade-ear#starts ) should start a quest for both alliance and horde characters, however as an alliance character you get the message "that quest is not available to your race".

**Comment by Aival94** [comment]
Mobs should drop the item depend of your race.
If you are an Alliance race it should drop: [Burning Blade Ear(ID 49203)](http://www.wowhead.com/item=49203)
if you are a Horde race it should drop: [Burning Blade Ear(ID 49010)](http://www.wowhead.com/item=49010)

Now for Alliance it drop the Horde version of the item which should not.

Drop rate for Alliance version(ID 49203):
5%    [Burning Blade Shadowmage](http://www.wowhead.com/npc=4667/burning-blade-shadowmage)
1.5% [Burning Blade Felsworn](http://www.wowhead.com/npc=4666/burning-blade-felsworn) 
1.5% [Burning Blade Augur](http://www.wowhead.com/npc=4663/burning-blade-augur)
1.3% [Burning Blade Reaver](http://www.wowhead.com/npc=4664/burning-blade-reaver)
1%    [Burning Blade Adept](http://www.wowhead.com/npc=4665/burning-blade-adept)

Drop rate for Horde version(ID 49010):
6% [Burning Blade Shadowmage](http://www.wowhead.com/npc=4667/burning-blade-shadowmage)
2% [Burning Blade Felsworn](http://www.wowhead.com/npc=4666/burning-blade-felsworn) 
2% [Burning Blade Augur](http://www.wowhead.com/npc=4663/burning-blade-augur)
1.7% [Burning Blade Reaver](http://www.wowhead.com/npc=4664/burning-blade-reaver)
1.2%    [Burning Blade Adept](http://www.wowhead.com/npc=4665/burning-blade-adept)

**Comment by Jackalantern** [comment]
I was leveling in Desolace today on my Draenei and got this message as well, so it is still an outstanding issue.

**Comment by lourrific** [comment]
I'm having same problem as noted above. Today is November 24, 2015 and this quest bug will soon be 1 year old. keep on keeping on atlantissss, bring on TBC yeah!

**Comment by Avalain** [comment]
Gamebreaking bug for me that caused that my depression improved and I'm considering suicide. My only hope was finish this quest on my Alliance toon, but alas... I couldn't.

**Comment by Aival94** [comment]
Bump. This quest still have same problem.

**Comment by Malanie** [comment]
congrats to 2nd anniversary of this bug report! 
*bump bump*

**Comment by 1Andas** [comment]
I can confirm this too, I've leveled a few characters through Desolace, that problem persists.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14194-1676-burning-blade-ear/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
