### ISSUE TITLE
[PL][SPELL]Death Pact

### ISSUE THREAD

**Issue by lx771** [Atlantiss/BugTracker#1677]
Death Pact powinien mieć możliwość poświęcenia nie tylko Ghula, ale także gargulca jak i ghuli z Army of the Dead. Wszystko pięknie, działa, ale tylko, kiedy nie ma przyzwanego permanentnego ghula od unh dk. W takim przypadku zarówno macra typu /tar Ebon gargoyle czy /cast [target=Ebon gargoyle] ignoruja gargulca i zawsze poświęcają ghula. Nawet przy ręcznym stargetowaniu gargulca poświęcany jest ghul.

**Comment by Varchord** [comment]
wowhead links

**Comment by arekczup** [comment]
http://www.wowhead.com/spell=48743/death-pact
to taki problem wkleić ? -_-

**Comment by Jenovas** [comment]
Fixed in rev  4263
