### ISSUE TITLE
Big Chicken egg not lootable unless relog

### ISSUE THREAD

**Issue by Kabuki77** [Atlantiss/BugTracker#1679]
Hi, my name is Kabuki and I would like to submit a minor bug that isn't really bothering me but it would be nice if you fixed it. At The Lost Isles when you're doing the quest The Biggest Egg Ever when you kill the big chicken you can't loot the egg unless you relog. It's not a big problem, I just want to help you fix all the bugs.

Thank you for reading this

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
