### ISSUE TITLE
[EN][Spell][Mage] Counterspell/Evocation

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#168]
When we use Counterspell (http://cata.openwow.com/spell=2139) on other mage who is casting Evocation (http://cata.openwow.com/spell=12051) it should block every Arcane spell for 7 seconds. 

But it doesn't block his Counterspell so when we block his Evo he can use Counterspell (if you are talented with Improved Counterspell 2/2 (http://cata.openwow.com/spell=12598) he gets silence but not arcane school locked on his Counterspell) after countered.

**Comment by Wolffenstein** [comment]
Is it still bugged? I can't reproduce it, it works properly on my local server. Maybe some talent is bugging it?

**Comment by Giq** [comment]
It works fine on my local server too.
