### ISSUE TITLE
[PL][Shaman][spell] Elementals should have shamans crit chance

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1680]
Elementale nie skaluja sie z crit chance shamana.

"(...) His melee attacks are magical (fire damage), but crit for 200% damage,"

Fire elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

Earth elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

U shamana z crit chance na poziomie 25% na 60 hitow guardian ma 3 crity. Cos tu jest nie tak. To powinno po czesci zalatwic zanizony dps ele shama.

**Comment by mrkariox** [comment]
Rev 4285:
"Shaman Fire elemental should now scale with owner hit rating and crit rating"

Elementale nadal nie crituja, jest gorzej niz bylo, na 60 hitow 0 critow.

**Comment by Jenovas** [comment]
Nie powinny mieć crita właściciela, sprawdziłem w poradnikach, na forach blizzarda, simcraft i wszędzie jest że nie dziedziczy crita od Shamana i nie powinien.
