### ISSUE TITLE
[PL][QUEST] Nobody to Blame but Myself

### ISSUE THREAD

**Issue by Lauthai** [Atlantiss/BugTracker#1682]
Quest nazywa sie Nobody to Blame but Myself, zaraz po wystartowaniu karawany zrzuca nas z niej a wóz znika. Link do wowhead: http://www.wowhead.com/quest=27489/nobody-to-blame-but-myself

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1376
