### ISSUE TITLE
[PL][Drop] The Conclave of Wind

### ISSUE THREAD

**Issue by Oldworldgame** [Atlantiss/BugTracker#1683]
Item z bossa (Sky Strider Belt, http://www.wowhead.com/item=63490/sky-strider-belt ) nie posiada zadnych randomowych enchantow. Loot byl rozdzielany przez master loot (nie wiem czy to cos ma wspolnego).

**Comment by Rainofblood** [comment]
Wczoraj, wtorek 20.01.15, Conclave 25n, ten sam pasek bez statów, reszta itemów miała staty, loot rozdany przez "group loot".

**Comment by Gustawas** [comment]
Witam.
http://wow.gamepedia.com/Sky_Strider_Belt 
Tu są poprawne wartości jakie powinien mieć item na dodatku cata.
Mam nadzieje, że zostanie to jak najszybciej naprawione, iż ten item jest bis'owy, dla nie których klas, z dostępnych boss'ów

**Comment by Aival94** [comment]
I do not speak polish but i think that the bug the talk is about the random stats of this gear.This gear has no stats every time and it still drops from Conclaive of wind and is annoying.

![wowscrnshot_121815_233243](https://cloud.githubusercontent.com/assets/10282971/11920345/1f8ae8e6-a775-11e5-9c4a-b7c686211f5e.jpg)

**Comment by Piklo** [comment]
Still bugged?

**Comment by Piklo** [comment]
should be fixed in [rev. 5613](https://atlantiss.eu/changelog#rev5613)
