### ISSUE TITLE
[PL][Druid]Shapeshifting, cancel aura effect.

### ISSUE THREAD

**Issue by Vegakyudan** [Atlantiss/BugTracker#1689]
Przy zmianie formy mam efekt(na 2 druidzie tego nie zaobserwowałem, więc wychodzi na to, że to sie tyczy tylko mojej postaci) podobny do działania macra /cancel aura, czyli po zmianie formy odrazu wracam do formy worgena jesli jeszcze raz szybko kliknę bind'a. Normalnie wcześniej działał global cooldown i nic takiego nie miało miejsca. Przez ten "bug" wszystkie macra działające na zasadzie "zmiana formy -> użycie spella" przestały dzialać.

**Comment by Jenovas** [comment]
Podaj treść makr.

**Comment by Vegakyudan** [comment]
#show Skull Bash
/stopcasting
/cast Cat Form(Shapeshift)
/cast [target=focus] Skull Bash(Cat Form)

pewnie myślisz, że to wina macra. Przedwczoraj wszystko jeszcze działało normalnie. Widzę różnicę w szybkości zmiany formy z worgen>forma>worgen. Mam jeszcze jednego druida i tam nic takiego sie nie dzieje, wchodzi global cd i jest przerwa miedzy zmianami, u mnie tej przerwy brak.

**Comment by Kuszki** [comment]
hmmm, tak czy inaczej to ja polecam troche zmienic to macro

#showtooltip [stance:1] Skull Bash(Bear Form); Skull Bash(Cat Form)
/cast [stance:1] Skull Bash(Bear Form); [stance:3] Skull Bash(Cat Form); !Cat Form

W ten sposob na jednym guziku masz wybicie casta w misku/kocie + automatyczna zmiane formy na kota + bash w innej formia niz misiek czy kot

**Comment by Vegakyudan** [comment]
"PS nawet gdy recznie "klikniesz" w cat form podczas GCD gdy przed chwila uzyles cat form to wychodzisz z formy. nie mam pojecia czy tak powinno byc" 

czyli też tak masz? Zmieniasz sie w kota i gdy jeszcze leci GCD klikasz znowu kota i wychodzisz z formy? Bo ja np. na innym druidzie tak zrobić nie mogę, po zmianie jest GCD i jesli nie usunę buffa/aury od kota to nie wyjdę w trakcie GCD z formy. Tak to działało na moim pierwszym druidzie wcześniej, ale już nie działa. 
Dzięki za ten "!" to rozwiązuję problem makr, ale tak czy siak jest to dla mnie nie wygodne bo często spamuję formami i przez brak tej "pauzy" miedzy zmianami form czesto wylaczam to co dopiero wlaczylem, to sie głownie tyczy tree formy, ktora "spamuje" w gorących momentach, od wczoraj spaliłem już w ten sposób wiele drzew na BG, odpalajac drzewo i odrazu je anulując :P

**Comment by Kuszki** [comment]
ten "!" nie zawsze pomaga - jak juz minie GCD i mozesz uzyc formy, to "!" "zrobi: ze wyjdziesz z niej i wejdziesz w nia (to jest fajne, bo takie macro "/cast !cat form" usuwa snary). najbezpieczniej zrobic to "na dwa razy" czyli "/cast {stance:<forma>]; !forma" - wtedy nawet jak sa lagi to w sumie male prawdopodobienstwo jest ze to nie bedzie dzialac

**Comment by kadi2** [comment]
Jak dla mnie to blizzlike, zobaczcie na to. Wydaje mi sie, ze jedynie Moonkin forma zostala napisana przez blizzard w miare znosnie.
https://www.youtube.com/watch?v=l4SEO95Vmec&feature=youtu.be&t=4m55s

**Comment by Vegakyudan** [comment]
tylko, że na moim drugim druidzie tego nie ma ;D i nikt kogo pytałem też tak nie ma. Jeśli to blizzlike to proszę :P ja już nie chcę być blizzlike, chcę tak jak reszta graczy żyć w nieświadomości i zmieniać formy z "pauzą".

**Comment by Vegakyudan** [comment]
Hello!

 

Important message, visit http://bijverdienste.com/besides.php?90

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hey friend!

 

Check it out http://optionsbinairesbroker.com/delight.php?6un

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hey!

 

Important message, please visit <http://babajiskitchen.com.au/likely.php?zg>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hey!

 

Important message, please visit <http://bienhieucaocap.com/legs.php?3m0e>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hey!

 

Important message, please visit <http://takecookie.com/become.php?d>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://hostalsolbahia.com/pale.php?ybb7j>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://www.sdfholistic.com/anybody.php?p23>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://mobile-pharma.com/circumstances.php?u9ioa>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://meandsuccess.com/ashamed.php?xxet>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://farmaciadepanes.com/hold.php?f1gs>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://izmirpergole.com/thousand.php?bw6>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hello!

 

New message, please read <http://saolucasnatal.com.br/twenty.php?banl3>

 

kyudan@wp.pl

**Comment by Vegakyudan** [comment]
Hey,
I just wanted to share with you my feelings about an  unexpected surprise my  friends made  forme)) It wsa so  cool, just  take a  look <http://benefit.atcook.com/e7or/04>


Wishes, kyudan
