### ISSUE TITLE
[PL] [Spell] [Warrior] Berserker Rage

### ISSUE THREAD

**Issue by Kochany** [Atlantiss/BugTracker#1690]
Berserker Rage nie zdejmuje Repentance'a http://www.wowhead.com/spell=20066/repentance, ani Gouga http://www.wowhead.com/spell=1776/gouge, ale da sie nim wyjść z takich spelli jak Fear czy Sap. Sam effect Enrage'a też wydaje się być w porządku. Prosiłbym o w miarę szybki fix, gdyż jest to bug przez graczy atlantissa wykorzystywany specjalnie i z premedytacją, nie mówiąc już o graniu jakichkolwiek aren.

http://www.wowhead.com/spell=18499/berserker-rage

**Comment by Varchord** [comment]
Ciężko wykorzystywać to z premedytacja. I tak gracz rzuci CC i tak, nie robią tego w stylu "patrz warrior!  bugujemy!"
Ale bug to bug

**Comment by Wolffenstein** [comment]
Fixed in rev 4263.
