### ISSUE TITLE
Nie działa quest w strefie startowej Rycerzy Śmierci

### ISSUE THREAD

**Issue by Kushimaru** [Atlantiss/BugTracker#1692]
Nie działa quest w strefie startowej Rycerzy Śmierci który polega na dostarczaniu czaszek kotłowi.
Problem polega na tym iż po kliknięciu continue nic się nie dzieje.

**Comment by monibu** [comment]
poczytaj sobie reguły zgłaszania bugów: https://github.com/Atlantiss/BugTracker

**Comment by Kushimaru** [comment]
ale ten q sie nie przyjmuje tylko tylko sie oddaje
Nie ma go w spisie questów

**Comment by Kushimaru** [comment]
Nazwa krainy to Plaguelands:The Scarlet Enclave
