### ISSUE TITLE
[EN] [Dungeon Quest] Reforging The Sword

### ISSUE THREAD

**Issue by Bemalthan** [Atlantiss/BugTracker#1693]
Problem: Infused Saronite Bars are not possible to loot. They do not appear as quest objects that can be clicked on/looted.
Note: Other quest items are possible to get at the moment.

![wowscrnshot_011915_212339](https://cloud.githubusercontent.com/assets/10603375/5807228/66bf8e30-a021-11e4-8168-bd364dc2adda.jpg)

As you can see on the screenshot they are visible and even glitter like usual quest items, but are not clickable when I hover mouse pointer over them.
There are many of them spawned throughout the dungeon and they all share same problem!

**Comment by Bildo** [comment]
duplicate

**Comment by iprotocol** [comment]
Since every other version of this bug report has been closed(including mine) without a description, is there an update for this quest at all?
