### ISSUE TITLE
[PL][Class][Druid] Glyph of Ferocious Bite

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1698]
Obecnego opisu tego skilla nie mogłem się doszukać na żadnych patchu cataclismu.
Obecnie wygląda tak:   http://imgur.com/A6gH3nI

A powinien wyglądać tak: http://www.wowwiki.com/Ferocious_Bite

Ponadto nie zostało zwiększony jego dmg o 15%,   nie zgadza się koszt energi dodatkowo spalanej by zwiększyć dmg.  DMG na 5 combo pointach gdy posiadam 25 energi i mi spala 25 energi jest jak ten który ma też na 5 combo pointach a spala energi 50 - brak zwiekszenie dmg o 100% przy podwójnym spaleniu energi.

Będę w kontakcie i pozdrawiam,
Bloodmist

**Comment by NONLIFE** [comment]
Odznacz "Beginner Tooltips" w Interface -> Help

**Comment by Jenovas** [comment]
Problem zapewne jest Glyph of Ferocious Bite. Z dodatkiem 4.0.6 powodował że nie zjada dodatkowej energii i nie zwiększał DMG a obecnie powinien tylko hilać, zapewne coś zostało w kodzie i dlatego nie zwiększa mu DMG.

**Comment by Varchord** [comment]
Wywal ten glyph i wtedy sprawdź czy zżera energie. Masz jakieś potwierdzenie, że nie zwiększył się dmg o 15%? Masz do czego przyrównać?

**Comment by Bloodmisty** [comment]
Sprawdziłem to dziś jeszcze raz i faktycznie problemem tutaj jest glyph.  Jak nie ma glyphu to zżera dodatkowa energie i jest zwiększony dmg o 100%

**Comment by Varchord** [comment]
Zmień nazwę i opis

**Comment by Jenovas** [comment]
A czy glyph leczy?

**Comment by Bloodmisty** [comment]
trestowalem i nie, tlyko leader of the pack w overhilu na kukle

**Comment by Varchord** [comment]
Skasuj sobie część hp np spadając i sprawdzaj czy cyferki heala lecą. Skada/recount czasami pomijają overheal niektórych skilli/efektów etc

**Comment by Bloodmisty** [comment]
no tak zrobiłem, i  czekałem specjalnie by mnie uleczył Leader of the pack, bo to ma cd i od razu FB i zero hila.  No  z glyphem nie leczy FB.

**Comment by Jenovas** [comment]
Fixed in rev  4283
