### ISSUE TITLE
[PL][Class][Druid] Ravage

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1699]
Opis Skila jest nieaktualny jak i jego obrażenia.
Obecnie: http://imgur.com/HOI6jkw

Prawidłowy opis skilla: http://www.wowwiki.com/Ravage_(druid_ability)

Zarówno po przeliczeniu  dmg w statystykach meele razy wymagany  przelicznik i dodaniu do tego bonusu zawartego w opisie skilla - dmg wynosi identycznie jak pokazuje mi dr damage na obecny opis.Jednakże opis powinien być inni jak i dmg.
Dmg SKilla nie jest na obecny patch. 

Wnioski:
DMG skilla i jego opis jest błędny.

Będę w kontakcie i pozdrawiam,
Bloodmist

**Comment by Jenovas** [comment]
Nic nie zrozumiałem. DMG nie jest poprawny tzn za mały? Za duży? Zły przelicznik jest? Brałeś pod uwagę że cel ma armor?

**Comment by Varchord** [comment]
Opis skilla bierze się z klienta. Sam miałem często inne opisy niż powinno być.

Podejrzewam, że problem jest taki sam jak przy innych zgłoszeniach kolegi. Nie bierze pod uwagę redukcji dmg z armora.
Jak piszesz, że dmg jest błędny to pokaż cyferki

**Comment by Bloodmisty** [comment]
Posiadam Clienta 4.3.4 na nowo sciaganego a nie aktualizowanego.
Jak to nikt nic nie rozumie?  Ferocious bite boje bile samo jak  zuzywa 25 energi i tyle samo jak zużywa 50 enregi,   nie dodaje 100% bonusu, bo jest pokazane w linku. Jeśli trzeba to nagram filmik z komentarzem. Armor nie biore pod uwagę, gdyż nie o to chodzi głównie - bo bijąc ten sam cel nie ma zwiększenie dmg o 100%
Pozdrawiam

**Comment by Bloodmisty** [comment]
I przepraszam ale zamkniecie tematu? ;0   udowodnie ze Ravage bije dmg za mały.
Nie rozumiem skąd ten pośpiech....

**Comment by Varchord** [comment]
Testuj na jakieś broni z mniejszym przedziałem dmg (u vendorów można kupić białe z 1-3 bodajże). Przy skillach z % weapon dmg to się to wszystko za bardzo rozłazi jak masz duży przedział.

I nie patrz ile pokazuje DrDamage :P

**Comment by Bloodmisty** [comment]
Po ponownym przeliczeniu  przyznaje Wam racje.
Uzwzglednieniu iż kukła redukuje 33% obrażeń ilości obrażeń się zgadzają ;)
Przepraszam i Dziękuję
