### ISSUE TITLE
[PL][Dungeon - Cata] The Deadmines

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#170]
Patch 4.1.0: Ragezone cast by Defias Blood Wizards now only increases damage dealt, no longer increasing damage taken. (w porządku, działa jak należy)

- Admiral Ripsnarl: http://www.wowhead.com/npc=47626

Podczas wejścia na pokład poruszał się i schodził poza "arenę" pokładu statku. Gdy zbiłem go do 66% odpaliła się mgła (nie doszukałem się ID które jest za to odpowiedzialne), jednak Admiral zniknął, Vapory się nie pojawiały. (testowane na normie) 

- Poison Clouds:

W każdym miejscu gdzie strzelają armaty znajdują się triggery które aktywują Poison Clouds, zadające 7-10k dmg na normal i 18-21k na heroic. Nie powinny one w ogóle się tam znajdować (nie wiem jakie mają ID).

- Misc:

Brak visuali przy wejściach i wyjściach (wyglądają jak portale do instancji wotlk/cata - fioletowe)

- Screenshoty: http://imgur.com/a/LtFRi

**Comment by qubuslabadz** [comment]
Fixed in rev 4252.
