### ISSUE TITLE
[PL][Class][Druid] Rake initial DMG

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1700]
Błędny dmg z Rake przy użyciu skilla.

Jest tak: http://imgur.com/bJeruDH
Powinno być tak: http://www.wowwiki.com/Rake

Przy minimalnym periodick dmg z bleeda wynoszącym wynoszącym 3766, minimalny dmg z użycia skila powinien być taki sam jak wielkość perodicka, czyli 3766 a jest 2507. Dane porównane na obrażeniach nie będące krytykami. Sam dmg pojedynczego thicku bleeda jest prawidłowy i wynosi 14,7% AP.

Będę w kontakcie i pozdrawiam,
Bloodmist

**Comment by Wojmistrz** [comment]
panie @Bloodmisty popraw periodick na periodic :D

**Comment by Varchord** [comment]
Rake zadaje taki sam dmg jak kazdy jego tick
Problemem jest to, że initial dmg jest obniżany przez armor chociaż nie powinien

**Comment by Bloodmisty** [comment]
nie jestem humanista ale ścisłowcem analitykiem ;P
Varchord widzisz ale nie zmienia to faktu ze innitiated dmg bije za mało ;P

**Comment by Varchord** [comment]
Nie. Bije dobrze, tylko przy kalkulacji niepotrzebnie bierze pod uwagę armor. Gdybyś zaatakował kogoś z 0 armoru initial byłby identyczny z tickiem. zmień tytuł/treść głownego posta

**Comment by Rainofblood** [comment]
Możliwe, że initial damage jest liczony jako physical, a nie bleed, co powoduje branie armoru.

**Comment by Bloodmisty** [comment]
Bardzo Dziękuję za zmianę tematu Jenovas;)
Rainofblood ale wiesz jak Ci pisze tyle samo to ja to rozumiem jednoznacznie ;)

**Comment by Kuszki** [comment]
Z obserwacji sądze, że initial jest bleedem ponieważ Mangle zwiększa jego wartość. Co nie zmienia faktu, że faktycznie nie ignoruje on armora.

**Comment by Varchord** [comment]
Initial nie jest bleedem, ale zadawać ma takie same obrażenia jak część bleed tego skilla i ma być traktowany jako bleed przy każdych kalkulacjach dmg.
W patchnotes wszystko jest

**Comment by Kuszki** [comment]
Blizzard logic - "zróbmy nie bleeda, który będzie bleedem anie niech to nie będzie bleed, tylko niech będzie bleedem"

Tak czy inaczej chyba już jasna sprawa jest. W sumie to ciekawe skąd oni te pomysły biorą...

**Comment by Bloodmisty** [comment]
poprostu ma uderzyc tyle co pojedynczy dmg z bleeda i tyle ;p

**Comment by Varchord** [comment]
Ale to trzeba wiedzieć dlaczego tyle nie bije :P Jak devi nie musza sami głowkowac to szybciej fixy wchodzą

**Comment by Bloodmisty** [comment]
no wchodza szybciej, ale jak sie nie zna kodu, lub cieżko znaleźć wiele wiesz przelcznikow i coefficientow to ciezko tak ;p

**Comment by Wolffenstein** [comment]
Czyli Rake ma ignorować armor?

**Comment by Wolffenstein** [comment]
Rake będzie ignorował armor od reva 4268.

**Comment by Bloodmisty** [comment]
i gitara ;D

**Comment by Varchord** [comment]
"Nie będzie fixów bo sesja"
A nie mówiłem :P

**Comment by nerv234** [comment]
Czy to nie jest tak że sesja się zaczyna w lutym? Przynajmniej u mnie.

**Comment by Varchord** [comment]
Jeśli przez sesja rozumiesz egzaminy i egzaminy poprawkowe to tak, w lutym
Ja myślę o kolokwiach itp (można ominąc niektóre egzaminy)

**Comment by nerv234** [comment]
Racja, ale np. u mnie kolokwia miałem już w połowie semestru niektóre i teraz są "kolokwia nr 2".

Wolf myślę że jest na tyle odpowiedzialny że stawia zaliczenie semestru ponad skrypty:)
