### ISSUE TITLE
[PL][Class][Druid] Shred

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1701]
Zły dmg, opis skilla i wpływ na jego zwiększenie dmg.

Obecny opis: http://imgur.com/h7yMzsT
dmg: 1539 -1761
pomijając haste robię średnia arytmetyczna to dmg = 1650

Liczenie obecnego dmg:  1650 * 425% + 238 = 7250,5   (dmg nie bedacy krytykiem z shreda bez efektu bleed)

ale dmg wychodzi taki: http://imgur.com/SjFVorz
wiadomo, że przy zero armoru ale różnica jest ogromna.

Obecny opis skilla jest prawidłowy jesli postać posiada do 80 lvl,  jesli ma wyższy lvl to przelicznik powinien być taki: http://www.wowwiki.com/Shred

liczac dmg = 1650 otrzymujemy:

1650 * 540% + 302 = 9212 dmg

Kolejna sprawą jest talent Rend and Tear: 
Zakładająca samo Mangle na cel osiągam dmg  7600 - 8478 (większy dmg niż bez mangle)
Bez Mangle: 5763 - 6374
- mangle zwiększa dmg z shreda a nie powinien

Z samym Rake na targecie:  dmg z SHreda wynosi 6950 - 7191
Natomiast z Rake i Manglem : dmg z Shreda wynosi 8956 - 9983 
- mangle zwieksza dmg z shreda
- razem  magle i rake zwieksza dmg z shreda jeszcze bardziej

Przedstawione wartości nie są obrażeniami krytycznymi by wyeliminować zbyt dużą losowość.

Wnioski:
- Shred ma zły bazowy dmg, według złego przelicznika (powinien mieć więcej co przedstawiono wyżej)
- rake zwiększa dmg z shreda  (prawidłowo)
- rake i mangle dodatkowo zwieksza dmg z shreda (nieprawidłowo - Mangle wpływa na dmg z shreda)

Będę w kontakcie i pozdrawiam,
Bloodmist

**Comment by Jenovas** [comment]
Mangle powinno zwiększać DMG Shreda i Maula w opisie spella masz że wszystkie efekty które zwiększają DMG Bleedów zwiekszają również DMG tym spellom.

Tak więc proszę dokładniej czytać.

**Comment by InformatorPE** [comment]
jaki addon pokazuje Ci te informaje w czerwonej ramce http://zapodaj.net/d662ab5c753dd.jpg.html

**Comment by Varchord** [comment]
Damage jest dobry. Każdy dummy posiada około 33% redukcji dmg. 
Przy twoich obliczeniach ile powinno być dmg 
1650 * 540% + 302 = 9212 dmg
9212 * 0,67 = 6172,04
Średni dmg na twoim screenie to 6134
Tak jak Jenova napisał. Istnieje talent, który powoduje, że debuffy zwiększające bleed dmg zwiększają dmg dla shred

Uważam, że problem do zamknięcia
Ten addon to DrDamage

**Comment by Bloodmisty** [comment]
Dobrze Dziś pokaże przeliczenie bez targetu na ilości dmg wskazywanego przed dr damage,

**Comment by Varchord** [comment]
DrDamage zawyża wartości. Nie wolno się nim sugerować

**Comment by Jenovas** [comment]
Obliczenia:
Min DMG - 1539
Max DMG - 1761
Min Shred DMG z wzoru - 1539 * 540% + 302 = 8612
Max Shred DMG z wzoru - 1761 * 540% + 302 = 9811

Min Shred DMG z wzoru - armor - 8612 * 0.67 = 5770
Max  Shred DMG z wzoru - armor - 9811 * 0.67 = 6573

Min DMG z Twojego SSa - 5766
Max DMG z Twojego SSa - 6508

Myślę że nie trzeba tu nic więcej liczyć. Prosta matematyka i nie ma co kombinować.

**Comment by Bloodmisty** [comment]
czyli kukla ma az 33 % redukcji dmg z tego wynika ;)
