### ISSUE TITLE
[PL][Event][Vendor] Valadar Starsong

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#1703]
Witam!
Otóż z tego co widzę, na serwerze zaczął się już Lunar Festival (a przynajmniej ozdoby są i vendorzy w Moonglade też). Niestety Valadar Starsong (http://www.wowhead.com/npc=15864/valadar-starsong) nie ma na sprzedaż dwóch petów dodanych w patchu 4.3.0, a mianowicie Festival Lantern (http://www.wowhead.com/item=74611/festival-lantern) oraz Lunar Lantern (http://www.wowhead.com/item=74610/lunar-lantern), obydwa kosztują 50 coinsów. Tutaj pojawia się pytanie/prośba, czy pety te zostaną dodane podczas tegorocznego eventu, czy niestety z racji dodawania contentu wedle kolejności jego wychodzenia przyjdzie poczekać jeszcze rok (minimum)? 
Z góry dziękuję za odpowiedź!

Rev. 4265

**Comment by Yebyemnetho** [comment]
Nie da sie również ukonczyć Achivmentu http://www.wowhead.com/achievement=6006/elders-of-cataclysm. nie zalicza komendy /bow ani nie da sie z nimi porozmawia.
Nie działa również http://www.wowhead.com/quest=8868/elunes-blessing nawet po wystrzeleniu 40 rakiet nie pokazuje sie npc. https://www.youtube.com/watch?v=gao02nmpj6g.

**Comment by Yebyemnetho** [comment]
W Dungeonie nie ma NPC Elder Starsong http://www.wowhead.com/npc=15593/elder-starsong#comments przez co nie da sie ukonczyc achiv'a http://www.wowhead.com/achievement=910/elders-of-the-dungeons

**Comment by Yebyemnetho** [comment]
http://scr.hu/4u87/5gl0a
Nie ma także kolejnego Eldera w Gundrak obok  Drakkari Colossus http://www.wowhead.com/npc=30537/elder-ohanzee#comments

**Comment by Drutmaster** [comment]
Ten jest akurat, ale występuje tylko w wersji hc Gundraka.

**Comment by Yebyemnetho** [comment]
a powinien również na normalu ;)

**Comment by Bildo** [comment]
fixed in rev. 4274
