### ISSUE TITLE
[EN] [Hearthstone] [Rogue]

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#1704]
Casting Hearthstone (and possibly other item-related spells) does not break Stealth as it's supposed to.

Stealth: http://www.wowhead.com/spell=1784/stealth
Hearthstone: http://www.wowhead.com/item=6948/hearthstone

**Comment by kadi2** [comment]
related to https://github.com/Atlantiss/BugTracker/issues/475
