### ISSUE TITLE
[EN] [Achievement] Loremaster Sub-Achievements

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#1706]
Every Loremaster-related achievement shouldn't count towards its own completion the daily quests.
(got no useful wowhead link).

Wowiki: "Repeatable or daily quests in general can be assumed not to count towards any Loremaster though there are a few exceptions. If they do at all, it is likely that only the first completion (which is sometimes technically a separate quest and not repeatable or daily, as in the case of Not a Bug) will count. They will on occasion count towards The Seeker." ( http://www.wowwiki.com/The_Loremaster > Tips and Tricks)

**Comment by Wolffenstein** [comment]
Can you give some examples of daily quests counting towards Loremaster achievements?

**Comment by Propolys** [comment]
Therazane's daily quests that count towards http://www.wowhead.com/achievement=4871/deep-into-deepholm

**Comment by Propolys** [comment]
Did some research and apparently the quest I completed before getting the Loremaster achievement WAS supposed to count.
http://www.wowhead.com/quest=27050/fungal-fury

Notice that in the Quickfacts "Loremaster: Deepholm" is mentioned.
