### ISSUE TITLE
[EN] [Talent] [Druid] Feral Swiftness + Bear Stampeding Roar

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#1707]
With talent Feral Swiftness Stampeding Roar should remove movement impairing effects but Bear 
version of Stampeding Roar doesn't.
http://cata.openwow.com/spell=77761

**Comment by Varchord** [comment]
It does.
wowhead links

**Comment by Jenovas** [comment]
It does. Closing

**Comment by Iambugged** [comment]
Bear version doesn't.
http://cata.openwow.com/spell=77761

**Comment by Iambugged** [comment]
It clearly is bugged I even tested it in a duel and it didn't remove chains of ice or frost nova.

**Comment by Jenovas** [comment]
So next time please add that Bear Version doesnt do it.

**Comment by Iambugged** [comment]
Sorry about that I actually thought first it was both.

**Comment by Jenovas** [comment]
Fixed in rev 4285
