### ISSUE TITLE
[EN][Quest] Drive-by Piracy

### ISSUE THREAD

**Issue by peraz** [Atlantiss/BugTracker#1710]
http://www.wowhead.com/quest=26649/drive-by-piracy

This quest is bugged. Once you talk to the NPC to start swimming with a boat, the boat appears and leaves very fast and you aren't fast enough to jump in. Tried various ways to jump into the boat, I think it's even impossible to stand on it, it's like a hologram, not even solid.

This bug won't let the players get The Cape of Stranglethorn Quests achievement and will deny you from the rest of the awesome Bloodsail Buccaneers questline.

Please fix it.

**Comment by Bildo** [comment]
duplicate
