### ISSUE TITLE
[EN][Guild] Guild achievements for dungeons/raid

### ISSUE THREAD

**Issue by Bildo** [Atlantiss/BugTracker#1716]
You can't earn any of the dungeon/raid guild achievement.
http://www.wowhead.com/achievements=3.15079.15082
http://www.wowhead.com/achievements=3.15079.15084
http://www.wowhead.com/achievements=3.15079.15085
http://www.wowhead.com/achievements=3.15079.15086
http://www.wowhead.com/achievements=3.15079.15083
http://www.wowhead.com/achievements=3.15079.15087

**Comment by mitim1** [comment]
!Bump

**Comment by Nukeey** [comment]
Will this be fixed anytime soon? I would really like to finally get the mount for cata raids.

**Comment by abominalizer** [comment]
Bump

**Comment by Aival94** [comment]
It seems that server(or whatever is called) does not recognize the boss you kill each time when in guild group as you can see in news section of any guild when you kill a boss "<x Guild> defeated Unknown".

Please try to fix it if possible :)
