### ISSUE TITLE
[EN][Quest][Deepholm] Twilight Research / Maziel's Research

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#1719]
http://www.wowhead.com/quest=27100/twilight-research
the situation is:
this quest starts from an item http://www.wowhead.com/item=60816/maziels-research dropped by some trogg , but when you right click it it doesnt offer you to accept any quest , doesnt autoaccept it together with putting it into your questlog , only opens that quest window http://oi62.tinypic.com/2j41sw3.jpg , now while having "maziel's research" in your inventory youre able to collect quest items http://www.wowhead.com/item=60814/twilight-research-notes from mobs
the problem is:
"Continue" button is dead , even when you collect 4 research notes you can click it 100 times and nothing happens , it doesnt allow you to accept that quest and bring it to Seer Kormo the quest completer http://www.wowhead.com/npc=43397/seer-kormo

**Comment by Wolffenstein** [comment]
Fixed in rev 4268.
