### ISSUE TITLE
[PL][Quest][Darkshore]Soothing the Elements

### ISSUE THREAD

**Issue by deplecak** [Atlantiss/BugTracker#1720]
Po postawieniu totemu na szczycie tylko 1 lub 2 moby sie spawnują i potem nic się nie dzieje co za tym idzie nie można ukończyć tego questa i iść dalej z fabułą

in english: after puting totem (quest item) in place, instead of waves of fire elements attacking this totem only 1 or 2 elements are spawning after that nothing happens so i cant complete this quest.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1521
