### ISSUE TITLE
[PL][Quest][Profession] Figurine - Dream Owl

### ISSUE THREAD

**Issue by Adamelinium** [Atlantiss/BugTracker#1721]
A więc znalazłem niedawno Figurine - Dream Owl i mam wszystkie potrzebne matsy, ale nawet nie mogę zacząć questa. Dodam tylko, że JC mam na poziome 525.

http://www.wowhead.com/quest=28777/broken-owl-figurine

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1355

**Comment by Wolffenstein** [comment]
Fixed in rev 4268.

**Comment by Exorcista** [comment]
issue still persists, today i couldnt complete any of the figurines quest
