### ISSUE TITLE
[PL] head no look for character

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1722]
problem polega na tym ze normalnie widzę hełmy inych postaci ale mojej postaci  nie widzę 
 http://www.wowhead.com/item=58123/willow-mask
tak powinienem widzieć swoją głowe 
a widze 
![image](https://cloud.githubusercontent.com/assets/8699987/5838772/eb081842-a189-11e4-8f47-8f3f56e7ba7b.png)

**Comment by Aviannaqt** [comment]
Zaznacz Show Head w interface --> display.
