### ISSUE TITLE
[PL] [Spell] [Priest] Prayer of Healing

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#1723]
http://www.wowhead.com/spell=596/prayer-of-healing

"This spell doesnt seem to be affected by Line of Sight.
However your target must be in Line of sight, other party members who are out of sight but still in range will also get healed."

Niestety, obecnie spell sprawdza cele leżące na linii w promieniu priesta.

Jeśli celem PoH jest gracz(1), który ma w zasięgu działania spella innego gracza(2) oraz są "na linii" ale jest on "niewidoczny" dla kapłana to gracz(2) nie otrzyma leczenia.

spełniono następujące warunki podczas testowania:
-zachowano zasięg
-"party" składało się z trzech graczy.

**Comment by Vyrtuz** [comment]
Dodatkowo "promieniowanie" z PoH (to z zasięgiem 30 yardów) powinno leczyć wszystkich w party niezależnie czy są ukryci za ścianami itp czy nie. Na poparcie wklejam kilka (czyt. aż 2) linków:

http://wow.gamepedia.com/Prayer_of_Healing
"Line of sight is only checked on the target, not on other players receiving the healing (...)"

http://www.mmo-champion.com/threads/707201-Prayer-of-healing?p=7598196
"Prayer of Healing is a great tool because it ignores line of sight, which is a massive problem on sindragosa (...)"

**Comment by Wolffenstein** [comment]
Fixed in rev 4332.
