### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by andydaninja** [Atlantiss/BugTracker#1726]
This quest is bugged.
Start of the quest: http://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit
End of the quest: http://www.wowhead.com/npc=21772/chief-apothecary-hildagard

**Comment by Bildo** [comment]
what exactly is bugged... ?

**Comment by andydaninja** [comment]
Were he takes control of your bodie and transform you into him to kill Karsius the Ancient Watcher.

**Comment by Satyr87** [comment]
... the thing is when you pick this quest up you get some 5min debuff called "teron gorefiend" but nothing happens except that you cant use abilities , it says "cant attack while pacified" , that guy Karsius to beat his ass is spawned tho but despawns when that debuff expires

**Comment by ThandorAts** [comment]
Now this quest is totally bugged because http://www.wowhead.com/npc=21877/karsius-the-ancient-watcher doesn't spawn after taking the quest. Moreover as Satyr87 said we only get the debuff (which causes us unable to act) without changing into Teron Gorefiend.

**Comment by ahtebe** [comment]
Still bugged just like in ThandorAts's post.

**Comment by PlayFullTV** [comment]
Also I'd like to point out that I WAS able to complete this quest on horde side, just waited for the silence debuff to expire then killed Karsius BUT the huge issue here is that the quest doesn't give the proper rewards for completing it. You're supposed to be granted a choice between six helms. http://www.wowhead.com/quest=10639/teron-gorefiend-i-am

They're highly sought after so being able to complete a bugged quest and not getting the rewards can be quite frustrating

**Comment by MarkBovee** [comment]
I tried the questline yesterday and like ThandorAts said the NPC that u have to kill doesn't spawn and U don't change into Teron Gorefiend. The player only get's a debuff.

**Comment by Dranerys** [comment]
This quest is still bugged. Whenever you accept the quest you turn into Teron Gorefriend but Karsius doesn't always spawn. This causes that Teron doesn't die meaning you can't retake the quest and you have to wait for some sort of reset. Whenever he does spawn he will kill you when he's around 30%, meaning you can't complete the quest.
