### ISSUE TITLE
[EN][Quest][NPC] Ghislania

### ISSUE THREAD

**Issue by petersaints** [Atlantiss/BugTracker#1732]
This quest does not work. The NPC starts to cast abilities to attack you but it can't be targeted by you. You can't kill it as it is intended by the quest.
Wowhead: http://www.wowhead.com/quest=25257/ghislania
OpenWOW: http://cata.openwow.com/quest=25257

The quest is given end ended by speaking to this other NPC nearby:
Wowhead: http://www.wowhead.com/npc=39590/spiketooth
OpenWOW: http://cata.openwow.com/npc=39590

This is the NPC that you are supposed to kill after asking for a duel:
Wowhead: http://www.wowhead.com/npc=39351/ghislania
OpenWOW: http://cata.openwow.com/npc=39351

I also marked it as not working on Private Status. It was marked as Blizzlike, so is this a regression from 4.0.6?

**Comment by petersaints** [comment]
This bug is related to #1733 and #1734. They all have the same starting and ending NPC and require you to duel an NPC placed nearby.

**Comment by Satyr87** [comment]
simpler version : you cant attack and beat her because shes green-named (friendly) all the time

**Comment by MirrorWraith** [comment]
why this was closed?? this quest still bugged

**Comment by aje** [comment]
I just did this quest. It works as intended.

**Comment by Dean1989** [comment]
the quest got bugged again, same problem as the op described

**Comment by silberberg44** [comment]
As Dean1989 said, the problem still persists: even after accepting the quest, it is impossible to attack Ghislania because of her "Friendly" status + she keeps casting Static Burst on herself repeatedly.
![wowscrnshot_082816_002913](https://cloud.githubusercontent.com/assets/21288699/18032494/d0ff982e-6d0e-11e6-9ad9-b1257065c773.jpg)
