### ISSUE TITLE
[PL][Class][Druid] Savage Defence

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1737]
Na screenie są informacje o postaci przy stałym bonusach:
http://imgur.com/Kny37UR

ilość AP: 11187
Mastery: 
2172 rating (+12.12 Mastery)
1 mastery = 4% 
Bazowe:  8 mastery *4% =  32%
BOnusowe: 12.12 *4% = 48.48%

SUmarycznie 80%

Savage Defence Absord Physical DMG:  11187 *80% = 8949.6

Wchodzi 7065 a powinno 8949.6

Biorąc pod uwagę, iż to się włącza praktycznie non stop jest to bardzo dyżym osłabieniem dla feral tanka.

Zastanawia mnie tutaj czy to tylko na tanku tak działa czy tez nie wpływa na bleedy, ale w przyszłości to sprawdzę.

Będę w kontakcie,
Bloodmist

**Comment by Varchord** [comment]
Nie wiesz jak działa savage defense.
Działa ono w ten sposób, że z 35% AP druida jest liczony shield, które następnie jest modyfikowany przez mastery
Czyli liczymy to tak:
AP * 0.35 * (1+mastery)

I wszystko się zgadza
Moje AP 12341
Mastery bazowe + bonus: 77,16%
Mój shield : 7652
12341*0.35*(1+0.7716)=7652,16046

Do zamknięcia moim zdaniem

**Comment by Jenovas** [comment]
Jak Varchord napisał źle liczysz działanie Savage Defense. Zamykam.
