### ISSUE TITLE
[EN] [Dungeon-Classic] [Scholomance] missing Meeting Stone

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1738]
The Meeting Stone in front of the Scholomance is missing:

![mia](http://i.imgur.com/X4Bclib.jpg)

![should be here](http://i.imgur.com/zbmCCTe.jpg)

**Comment by Quban** [comment]
DELETE FROM `gameobject_template` WHERE `entry` IN (178832);
INSERT INTO `gameobject_template` (`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`faction`,`flags`,`size`,`questItem1`,`questItem2`,`questItem3`,`questItem4`,`questItem5`,`questItem6`,`data0`,`data1`,`data2`,`data3`,`data4`,`data5`,`data6`,`data7`,`data8`,`data9`,`data10`,`data11`,`data12`,`data13`,`data14`,`data15`,`data16`,`data17`,`data18`,`data19`,`data20`,`data21`,`data22`,`data23`,`data24`,`data25`,`data26`,`data27`,`data28`,`data29`,`data30`,`data31`,`unkInt32`,`AIName`,`ScriptName`,`VerifiedBuild`) VALUES
(179585,23,5495,'Meeting Stone','','','',35,0,1,0,0,0,0,0,0,15,255,1583,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',15595);

DELETE FROM `gameobject` WHERE `entry` IN (178832) and `map` = 0;
INSERT INTO `gameobject` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnMask`,`phaseMask`,`PhaseId`,`PhaseGroup`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecs`,`animprogress`,`state`,`VerifiedBuild`) VALUES
(GetGameobjectGuid(),179584,0,0,0,1,1,0,0,-7590.7,-1139.77,260.68,3.51685,0,0,0.998135,-0.0610486,120,255,1,0);

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
