### ISSUE TITLE
[EN] [Dungeon] Inner Blackrock: missing Meeting Stones

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1739]
The inner Blackrock dungeons (BRD, MC, UBRS/LBRS, Blackrock Caverns) are missing two Meeting Stones.

![pic](http://i.imgur.com/9k4K43F.jpg)

[This](https://lifebeginsguild.wordpress.com/2009/06/19/231/) picture from 2009 (=WotLK) shows one. [This](http://wowscrn.blogspot.de/2011/04/dungeon-entrance-classic.html) pic from 04.08.2011 confirms that it was still there in Cata.
![pic](https://lifebeginsguild.files.wordpress.com/2009/06/wowscrnshot_061709_220239.jpg?w=495)

[This](https://betablast.wordpress.com/2010/08/14/the-entrance-to-the-blackrock-caverns/) post from 8/2010 (beta pre Cata) mentions the other Summoning Stone which obviously has been there before. [This](http://wowscrn.blogspot.de/2011/04/dungeon-entrance-classic.html) pic from 2011 (Cata) confirms the location.

![pic](https://betablast.files.wordpress.com/2010/08/wowscrnshot_081410_184511.jpg?w=630&h=393)

**Comment by Quban** [comment]
-- entry 179584 - meeting stone blackrock depths
-- entry 179585 - meeting stone blackrock spire

DELETE FROM `gameobject_template` WHERE `entry` IN (179584, 179585);
INSERT INTO `gameobject_template` (`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`faction`,`flags`,`size`,`questItem1`,`questItem2`,`questItem3`,`questItem4`,`questItem5`,`questItem6`,`data0`,`data1`,`data2`,`data3`,`data4`,`data5`,`data6`,`data7`,`data8`,`data9`,`data10`,`data11`,`data12`,`data13`,`data14`,`data15`,`data16`,`data17`,`data18`,`data19`,`data20`,`data21`,`data22`,`data23`,`data24`,`data25`,`data26`,`data27`,`data28`,`data29`,`data30`,`data31`,`unkInt32`,`AIName`,`ScriptName`,`VerifiedBuild`) VALUES
(179584,23,5495,'Meeting Stone','','','',35,0,1,0,0,0,0,0,0,15,255,1584,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',15595),
(179585,23,5495,'Meeting Stone','','','',35,0,1,0,0,0,0,0,0,15,255,1583,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',15595);

DELETE FROM `gameobject` WHERE `entry` IN (179584, 179585) and `map` = 0;
INSERT INTO `gameobject` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnMask`,`phaseMask`,`PhaseId`,`PhaseGroup`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecs`,`animprogress`,`state`,`VerifiedBuild`) VALUES
(GetGameobjectGuid(),179585,0,0,0,1,1,0,0,-7625.35,-1226.51,231.775,3.51057,0,0,0.998135,-0.0610486,120,255,1,0),
(GetGameobjectGuid(),179584,0,0,0,1,1,0,0,-7590.7,-1139.77,260.68,3.51685,0,0,0.998135,-0.0610486,120,255,1,0);

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar
