### ISSUE TITLE
[PL][Quest]"The Lost Pages"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1740]
Qyest wprawdzie usunięty już macie, ale znalazłem Shredder Operating Manual - Page 8 ( http://www.wowhead.com/item=16652/shredder-operating-manual-page-8 ) i Shredder Operating Manual - Page 10 ( http://www.wowhead.com/item=16654/shredder-operating-manual-page-10 ), a powinny zostać usunięte razem z Questem.

Link: http://www.wowhead.com/quest=6504/the-lost-pages

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by Danelar** [comment]
Dzięki :)
