### ISSUE TITLE
[EN][Spell][Paladin/Warlock] Healthstone and Hand of Protection

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1742]
Use Healthstone spell: http://cata.openwow.com/spell=6262
Healthstone (item): http://cata.openwow.com/item=5512
Hand of Protection: http://cata.openwow.com/spell=1022

I can't use Healthstone to heal myself, when paladin puts on me Hand of Protection. It should block only physical attacks not spells/items like Healthstone.

**Comment by Wolffenstein** [comment]
http://eu.battle.net/wow/en/forum/topic/1549441393

**Comment by Wolffenstein** [comment]
Blizzard fucked up, it's impossible to use Healthstone during HoP due to spell mechanics. I'm not going to change them. It may have been unintended, but that's how it worked on retail.
