### ISSUE TITLE
[PL][spell][hunter][pet] special spell 

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1743]
![wowscrnshot_012215_155304](https://cloud.githubusercontent.com/assets/8699987/5857892/4f10d994-a24f-11e4-972d-b59a2b7f19ed.jpg)
Corrosive Spit nawet jak trafi w 18 sekundzie buff znika zamiast sie stakować
http://www.wowhead.com/spell=160074/speed-of-the-swarm

**Comment by arekczup** [comment]
niewiem czy nie ma więcej XD

**Comment by arekczup** [comment]
nether ray 
brakuje jemu tego  Ancient Hysteria
http://www.wowhead.com/spell=90355/ancient-hysteria#used-by-pet
nie wiem jak z core houndem

**Comment by arekczup** [comment]
ravager nie ma spella Ravage
http://www.wowhead.com/npc=19189/quillfang-skitterer#abilities

**Comment by arekczup** [comment]
http://www.wowhead.com/spell=86570/shale-flurry#changelog
http://www.wowhead.com/npc=47071/deep-spider#abilities
egzotyczny pająk nie ma shale flurry

**Comment by arekczup** [comment]
http://www.wowhead.com/npc=16879/starving-helboar
http://www.wowhead.com/npc=16863/deranged-helboar#abilities
http://www.wowhead.com/npc=16880/hulking-helboar
powiny być bestiami i sie teamować hunterem :[

**Comment by Navedonar** [comment]
Poprawka na niżej wymienione czeka na wgranie
http://www.wowhead.com/npc=16879/starving-helboar
http://www.wowhead.com/npc=16863/deranged-helboar#abilities
http://www.wowhead.com/npc=16880/hulking-helboar

**Comment by arekczup** [comment]
dzienkuje

**Comment by arekczup** [comment]
egzotyczny pet  silithid nie ma tendor rip
http://www.wowhead.com/spell=160065/tendon-rip

**Comment by arekczup** [comment]
boar nie da sie złapać prubowałem nawet najniże lvl 
nie da sie go złapać a powino 
![wowscrnshot_012715_092620](https://cloud.githubusercontent.com/assets/8699987/5915496/a5f749fe-a606-11e4-9661-a993547d3d78.jpg)

**Comment by arekczup** [comment]
beetle  nie da się złapać  i powiniem mieć spella 
http://www.wowhead.com/spell=90339/harden-carapace#used-by-pet

**Comment by arekczup** [comment]
to już chyba wszystko co znalazłem

**Comment by Navedonar** [comment]
http://www.wowhead.com/npc=42859/wild-mature-swine#comments według komentarzy nie dało się go złapać w cata

**Comment by arekczup** [comment]
sry chory jestem wiec mogłem się z czymś pomylić. 
Dziękuje też ze w ogóle ktoś zobaczył na te zgłoszenie.

**Comment by Bildo** [comment]
fixed in rev 4291 by Navedonar

**Comment by arekczup** [comment]
nadal efekt wogule ise nie stakuje 
http://wow.gamepedia.com/Corrosive_Spit

**Comment by Navedonar** [comment]
Poprawiłem tylko to :
http://www.wowhead.com/npc=16879/starving-helboar
http://www.wowhead.com/npc=16863/deranged-helboar#abilities
http://www.wowhead.com/npc=16880/hulking-helboar
nie wiem czemu zamknięte
zrób najlepiej nowe zgłoszenie

**Comment by arekczup** [comment]
ok
