### ISSUE TITLE
[EN][Quest][Desolace] Wetter than wet

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#1747]
http://www.wowhead.com/quest=14264/wetter-than-wet
The quest previous to this one provides the player with http://www.wowhead.com/item=49064/slitherblade-charm that when used transforms the player to a naga and makes him able to use the abilies given by this quest. Problem is, every time you use an ability in naga form, it breaks the transformation and you can't kill the quest mobs while transformed because of it. Tried killing them without and it doesn't count on the quest log. Atm, it is impossible to complete the quest and as such it also breaks the chain for Desolace. 
I do mention that I'm a druid, if it has anything to do with the transformation bug.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2575
