### ISSUE TITLE
[PL][Quest][Deepholm]"All Our Friends Are Dead"

### ISSUE THREAD

**Issue by relek** [Atlantiss/BugTracker#1749]
Quest trzeba wykonac na statku ktory lata w Deepholm, po przebywaniu na nim z 1-2 minuty pokazuje sie szybki loading screen, a nastepnie sie spada w dol bez mozliwosci dotarcia potem w postaci ducha.

**Comment by eryczek1615** [comment]
http://www.wowhead.com/quest=26248/all-our-friends-are-dead

**Comment by jurek1** [comment]
jak robilem w 2014 ( po wprowadzeniu 4.3.4 ) , wypychalo mnie ze statku ( jak racial goblina :p ) wysoko na polnoc , az za mape deepholm
