### ISSUE TITLE
[PL][NPC] Training Dummy

### ISSUE THREAD

**Issue by Malylolek** [Atlantiss/BugTracker#175]
Kukły muszą zostać zaatakowane jakimś instantem [skillem lub atakiem który od razu zada dmg] przy nakładaniu DoT nic się nie dzieje, DoT'a wyparowuje i wychodzi z combatu.

**Comment by Wojmistrz** [comment]
Kukły NIE POWINNY trzymac w combacie jeśli się przestaje je bić a ktoś inny biję też tą samą kukłę co biliśmy przed chwilą (np. 3 osoby biją kukłę, jedna osoba rezygnuje i 2 nadal biją i utrzymują combat na tej osobie co odpuściła) TAK NIE POWINNO BYĆ!! wkurzające jest to....

**Comment by TranceAccount** [comment]
Is this issue still relevant?
