### ISSUE TITLE
[EN][Quest][Darkshore] The Ancients' Ire

### ISSUE THREAD

**Issue by zero092** [Atlantiss/BugTracker#1753]
http://www.wowhead.com/quest=13514/the-ancients-ire
The ancient protectors which you are supposed to ride are stuck in place and can't be moved.

**Comment by Aival94** [comment]
They see to try to swim somehow but you can make them move when you reach(by moving one step at a time(better moving backside because it go a little faster) to the ground.After reaching ground everything is blizzlike

**Comment by zero092** [comment]
Yeah i manged to do that,but it took me like 5 mins.

**Comment by Aival94** [comment]
#646 this can be updated to 4.3.4 or closed as it is the same one.
