### ISSUE TITLE
[EN][Quest][Mount Hyjal] The Last Living Lorekeeper

### ISSUE THREAD

**Issue by drlinux92** [Atlantiss/BugTracker#1754]
http://www.wowhead.com/quest=25830/the-last-living-lorekeeper
This quest is not doable. Whenever I try to move towards to Nordu (the NPC where I could turn the quest in) it disappears. So right before I could reach the NPC it always disappears. From far away (~50-60+ yards away) I can see him however. I think it's related to phases. Lets say Nordu is in phase1 and I'm in phase2. From phase2 I can see Nordu standing in phase1(from afar), but as soon as I approach Nordu's "border" I enter in phase1, but my character is still in phase2 and maybe this is the cause I can't interact with the NPC, because we are in two different dimensions.
Additional notes: I was lucky, that in the same time, there was a player nearby to Nordu. Guess what, When I went far away from Nordu, I could see Nordu but couldn't see the Player itself. When I went closer, Nordu disappeared but the Player appeared. Its clearly something with the phases. (this isn't on the pictures, this happened right after I made the screenshots)

![wowscrnshot_012315_145117](https://cloud.githubusercontent.com/assets/10670595/5875605/713e9806-a30f-11e4-86c6-ac5927f9819a.jpg)
![wowscrnshot_012315_145107](https://cloud.githubusercontent.com/assets/10670595/5875608/7712f8bc-a30f-11e4-86a6-842d007df1f4.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/912
