### ISSUE TITLE
[PL][Achievement][Northrend]On The Rocks/Glory of the Hero

### ISSUE THREAD

**Issue by Volstagg** [Atlantiss/BugTracker#1755]
A więc wbiłem achievement http://www.wowhead.com/achievement=1919/on-the-rocks lecz na liście do achievementu http://www.wowhead.com/achievement=2136/glory-of-the-hero go nie mam wbitego.

http://i60.tinypic.com/xemtra.jpg - O the rocks
http://i57.tinypic.com/1fi6wg.jpg - Glory of the Hero

**Comment by Sathus** [comment]
I have the same problem with http://www.wowhead.com/achievement=2043/the-incredible-hulk

I get it, but it doesnt count it towards glory of the hero. And i am almost done with it.

**Comment by xolon** [comment]
thats not the only prob, for glory of the hero - achievement "The incredible hulk"  #1444 doesn't work

**Comment by qubuslabadz** [comment]
Fix in rev. 4289.
