### ISSUE TITLE
[EN] [QUEST] [TELDRASSIL] Druid of the Claw

### ISSUE THREAD

**Issue by Jackalantern** [Atlantiss/BugTracker#1758]
There is no way to reach Rageclaw to be able to complete this quest. The door to reach him will not open like normal. At least I believe you are supposed to open that "locked" door to get to him. I haven't done this quest in cataclysm yet. Either way I haven't been able to find Rageclaw anywhere, except by way of /target Rage, and it will work so I am assuming he is behind that door.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/643

**Comment by Jackalantern** [comment]
My apologies. The search function doesn't appear to work. I searched Druid of the Claw and it came up as an entirely empty search.
