### ISSUE TITLE
[PL][NPC] Bizby

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#1759]
http://www.wowhead.com/npc=35757/bizby
http://www.wowhead.com/quest=14253/fletch-me-some-plumage
http://www.wowhead.com/quest=14252/good-gold-for-bad-tail
http://www.wowhead.com/quest=14251/new-beginnings

NPC Bizby nie daje 3 questow: Fletch Me Some Plumage!, Good Gold For Bad Tail, New Beginnings

**Comment by Wolffenstein** [comment]
Musisz zrobić quest http://www.wowhead.com/quest=14247/stubborn-lands
