### ISSUE TITLE
[EN] [Quest] [The Underbog] "Stalk the Stalker"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1760]
http://www.wowhead.com/quest=9719/stalk-the-stalker

Maybe a crashlike issue - at least the server crashed at the same moment when I did that:

I already completed the quest once. Just now I could turn in the quest a second time and I received a second item [Essence Infused Mushroom](http://www.wowhead.com/item=28109/essence-infused-mushroom). (I think normally you're supposed to do this only once)

Since the trinket was not marked as unique, I tried to equip both. Then the server crashed.

![too many shrooms - am I Teemo?](http://i.imgur.com/sg5kNKJ.jpg)

**Comment by Bildo** [comment]
fixed in rev. 4274
