### ISSUE TITLE
Warchief's command: Azshara!

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1762]
Link: www.wowhead.com/quest=28496
Level: 10
Requires level 9
Side: Horde

This quest is missing from Warchief's Command Board.

Orgrimmar:

1) http://www.wowhead.com/object=206109/warchiefs-command-board
2) http://www.wowhead.com/object=206116/warchiefs-command-board

Thunder Bluff:

1) http://www.wowhead.com/object=207323/warchiefs-command-board

**Comment by Angelo-DM-** [comment]
is this quest fixed or what?

**Comment by Bildo** [comment]
bugtracker rules

**Comment by Angelo-DM-** [comment]
I have changed the title.

**Comment by Angelo-DM-** [comment]
I've noticed that with my tauren, this quest is avaiable... i'm level 9 and i can take this quest from TB board... Instead I can't take this quest with my Blood Elf.

**Comment by Angelo-DM-** [comment]
i need to create again this report or you can re-open it?

**Comment by Bildo** [comment]
new
