### ISSUE TITLE
[EN] [NPC] [Sethekk Halls] Time-Lost Controller

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1764]
http://www.wowhead.com/zone=3791/sethekk-halls

[Time-Lost Controllers](http://www.wowhead.com/npc=18327/time-lost-controller) are supposed to summon a [Charming Totem](http://www.wowhead.com/npc=20343/charming-totem#abilities) which charms one group member for up to 30 seconds.

![Charming Totem](http://i.imgur.com/WTHk605m.jpg)

They spawn said totem, but the totem charms no group member... it looks more like it charms itself ([combat log snippet](http://pastebin.com/h7BjVYtX)).

![charming](http://i.imgur.com/jKpwlil.jpg)

**Comment by Bildo** [comment]
fixed in rev. 4274
