### ISSUE TITLE
[EN][Battlegrounds][Core] Rewards from Call to Arms

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1766]
http://us.battle.net/wow/en/forum/topic/3595670888

"In patch 4.3 we’re changing the daily battleground (BG) to reward 100 conquest for a win (up from 25). In addition, every non-rated BG that you win will also give you 50 conquest. There is no limit to how many BGs you can run this way, up to the normal conquest cap."

Actually on server looks like that: 25 conquest points for first win of the day, next wins only gives some honor.

**Comment by Wolffenstein** [comment]
Fixed in rev 4273.
