### ISSUE TITLE
[PL][Achievement][Cooking] Dinner Impossible

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#1775]
Witam!

Problem polega na tym, że postawienie Great Feast (http://www.wowhead.com/item=34753/great-feast) na którymkolwiek z bg, potrzebnych do achievementa Dinner Impossible (http://www.wowhead.com/achievement=1785/dinner-impossible) nie zalicza go. Zarówno na Arathi Basin, na które trafiłem (bg było już w trakcie, więc pomyślałem, że może dlatego nie zalicza), jak i na Strand of the Ancients (na którym byłem od początku) nie zaliczyło postawienia Feasta. Z góry dziękuję za pomoc!
Rev. 4268

**Comment by qubuslabadz** [comment]
Fixed in rev. 4289.
