### ISSUE TITLE
[PL][instance][cataclysm][CRASHLIKE] Throne of the four winds - Al'akir

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1778]
Kiedy Al'akir (http://www.wowhead.com/npc=46753/alakir) uzyje **Wind Burst** (http://www.wowhead.com/spell=87770/wind-burst) w momencie gdy **gracz znajduje sie poza platforma** (wyskoczy z niej) to **crashuje klient wowa**, gdyz serwer nie wie gdzie takiego gracza odrzucic.

Sprawdzane w wersji **HC** bossa, w wersji **NORMAL** bug chyba nie wystepuje, ale nie jestem pewien.

**Comment by mrkariox** [comment]
Dlaczego zamkniete? ;O

**Comment by Bildo** [comment]
duplikat

**Comment by mrkariox** [comment]
Prosze podac link, ja nie znalazlem tego problemu odnosnie al akira nigdzie.
