### ISSUE TITLE
[EN][Spell][Warlock] Nether Protection (finally :>)

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1779]
Shadow Ward: http://cata.openwow.com/spell=6229
Nether Ward: http://cata.openwow.com/spell=91711
Nether Protection: http://cata.openwow.com/spell=30301

Nether Protection should work like this:
"When you absorb damage through Shadow Ward, Nether Ward or other effects, you gain Nether Protection, reducing all damage by that spell school by 30% for 12 sec."

On server - he activates after every spell hits Warlock even WITHOUT Shadow/Nether Ward on him. It means Warlock even doesn't have to have Shadow/Nether Ward active and he takes 30% less from every spell which hits him. 
It's been too long with us, but i hope finally someone can repair this :)

**Comment by Jenovas** [comment]
Fixed in rev 4285
