### ISSUE TITLE
[EN][Quest][Uldum] Fire From the Sky

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#1781]
http://www.wowhead.com/quest=28736/fire-from-the-sky

those demolishers http://www.wowhead.com/npc=48644/confiscated-artillery dont work , there were 5 of these machines on that hill but Harrison Jones had the only one which worked and he just phased away together with it

also those soldiers to shoot them with it are visible in wrong places , not where they really stand , i guess its because there are spawned NPCs to shoot plus walking textures to give a player any idea where to shoot , made that way because its too far away to see NPCs from that demolisher location , walking textures arent synchronized with NPCs

**Comment by armano2** [comment]
new, updated issue: #4192
