### ISSUE TITLE
[PL][Quest][The Storm Peaks] The Drakkensryd

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#1782]
Witam!
Quest The Drakkensryd nie działa na naszym serwerze jak powinno (choć jest wykonalny). A więc:
1) Używając harpuna (quest item) na smoka, pikujemy w dół przez chwilę, a potem jesteśmy za nisko, żeby móc rzucić w kogo innego (musimy wychodzić guzikiem, co kończy się śmiercią z wysokości).
2) Nie można ztargetować (przynajmniej ja nie mogłem) moba stojąc na smoku, więc żeby go zabić trzeba używać AoE.
3) Column Ornament, który powinien nam pozwalać bezpiecznie zejść ze smoków (używając na nim harpuna), pozwala na to, niestety nie utrzymujemy się na nim długo (1s).

Wowhead: http://www.wowhead.com/quest=12886/the-drakkensryd
Jak q powinien działać: https://www.youtube.com/watch?v=N-oAjPT4n_g

SS z naszego serwera: http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_012415_194952_zpscaf843ff.jpg

**Comment by Bildo** [comment]
duplikat

**Comment by Pieczyyea** [comment]
Duplikat? Dobrze wiedzieć, bo w wyszukiwarce na bugtrackerze nie znalazłem
