### ISSUE TITLE
[PL][Achievement][Argent Tournament] Exalted Champion of the Horde

### ISSUE THREAD

**Issue by szaruwa** [Atlantiss/BugTracker#1785]
Witam!
Po zrobieniu jednego tytułu w Argent Tournament ( http://www.wowhead.com/achievement=2765 ) nie są dostępne questy ( http://www.wowhead.com/quests=7.-241?filter=na=valiant%27s+charge;si=-2 ) u przedstawicieli innych frakcji, które powinny pojawić po ukończeniu chaina dla pierwszej z nich. Z tego powodu nie jest możliwe uzyskanie innych tytułów, a finalnie achiva http://www.wowhead.com/achievement=2771

**Comment by Nausica07** [comment]
It is same for Alliance. It's not possible to get titles from the other factions - http://www.wowhead.com/achievement=2770/exalted-champion-of-the-alliance

**Comment by katrinsa** [comment]
Niedawno zaczęłam robić q i mam ten sam problem. Myślałam że wszystko jest ok, bo niektórzy już mają je zrobione i dostali tytuły. Jednak nie działają. Ze zrobieniem archiwa http://www.wowhead.com/achievement=2770/exalted-champion-of-the-alliance chyba będziemy musieli poczekać!!!

**Comment by Althin** [comment]
Potwierdzam, działa tytuł tylko jednej frakcji. Proszę o szybki fix do tego :)

**Comment by Tessa99999** [comment]
Confirmed. This still does not work. As stated, after completing The Valiant's Charge quest (http://www.wowhead.com/quest=13697/the-valiants-charge) a new set is not available making this achievement impossible to do.

**Comment by Illusionist87** [comment]
Bumping, since this is still not fixed

**Comment by szaruwa** [comment]
bump

**Comment by Elunara** [comment]
Still nothing. It would be awesome if something could be done about it.

**Comment by Althin** [comment]
Stilll bugged.

**Comment by Lidless** [comment]
Up!!

**Comment by Dranerys** [comment]
I can confirm that after being a champion for your own faction, no quests for the other factions unlock. This makes it impossible to get the achievement 'Exalted Champion of the Horde'.

**Comment by TranceAccount** [comment]
#4899

**Comment by Piklo** [comment]
should be fixed in [rev5794](https://atlantiss.eu/changelog#rev5794)
