### ISSUE TITLE
[EN][Core] WoW Error in Kaskala

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1791]
Every 1-10 minutes I'm receiving a WoW Error, while killing Kvaldir Raiders in Kaskala, Borean Tundra. I still don't know what exactly is causing this issue, the error can appear right after I kill a mob or a bunch of mobs, or while I'm just flying around the zone. So far this is the only area in the game, which causes me to receive this error. The only thing that comes to my mind, which can actually be considered as a problem, are the ships in the water and along the coast.

Screenshot of the error: http://i.imgur.com/lG6WAqr.png

**Comment by Haz3L** [comment]
I had the same problem so it's not only for one person.

**Comment by bgb** [comment]
And my wow just hangs when Im killing Kvaldir Raiders (not always). This issue is very similar to this: https://github.com/Atlantiss/BugTracker/issues/736#issuecomment-91495044
And sadly I must say its happening only on Atlantiss server for me...

**Comment by Tj20** [comment]
I've tested this a bit: source of the crashes seems to be a buggy mob type like in the Shattered Halls (#870).

### Affected mobs: 
- [Kaskala Defender](http://www.wowhead.com/npc=25764/kaskala-defender)

### What happens:
When a group of 3 or more Kaskala Defenders killed the last enemy they were fighting and leave combat the game grashes. 

The player doesn't have to do anything. If there is a group of 3+ Kaskala Defenders nearby (=within drawing distance of the client) who killed the last Kvaldir they were fighting and reset their aggro, the WoW clients of nearby players crash.

Here are some screenshots right before the crash:

![pic 1](http://i.imgur.com/ipRuskl.jpg)
![pic 2](http://i.imgur.com/L48ydTs.jpg)
![pic 3](http://i.imgur.com/ffG25xc.jpg)

### Why does it happen?
I think like in the Shattered Halls there is either something broken with how the mobs are linked together and how they get into/drop combat. Or it has something to do with their animations (note that their *Throw* ability does not have a proper model: it's just a small blue+white cube.)

![throwing cubes](http://i.imgur.com/AoUhtlV.jpg)

### Workaround:
None. Quest somewhere else or be prepared to restart your client from time to time. :D

**Comment by Tj20** [comment]
I tested this bug again and it still happens.

[This](http://i.imgur.com/QOKrKFl.jpg) was the last screen the game shows after the Defenders kill the last enemy and then the game stops responding.

**Comment by Illusionist87** [comment]
Any news about a fix for this? It makes doing quests in this area a real pain, with crashes every minute or so...

**Comment by cosminush** [comment]
I have occurred same bug, but it don't give me reboot, just freeze my game and crash game.

**Comment by CSLooney** [comment]
bugs like this should be a high priority. they are game-breaking. I am encountering this bug as well. The first time i had to completely restart my comp, and run a scan on my comp to fix a disk error.
