### ISSUE TITLE
[EN] [QUEST] [Mulgore] Mazzranache

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1792]
Link: http://www.wowhead.com/quest=26188/mazzranache

When you turn in the quest, you can only choose [Belt of the Prairie Wolf (ID: 57209)](http://www.wowhead.com/item=57209/belt-of-the-prairie-wolf) as reward, instead you could choose between [Cougar Pelt Wristwraps (ID: 66616)](http://www.wowhead.com/item=66616/cougar-pelt-wristwraps) and [Swoopskin Gloves (ID: 57234)](http://www.wowhead.com/item=57234/swoopskin-gloves).

![wowscrnshot_012515_122733](https://cloud.githubusercontent.com/assets/10468828/5891383/aa04a610-a492-11e4-89c3-332f8011f7b7.jpg)

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
