### ISSUE TITLE
[EN][Achievement] Let's Do Lunch: Orgrimmar

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1793]
At the moment it's impossible to earn this achievement, because you don't receive credit towards it when you complete the quest [Stealing From Our Own](http://www.wowhead.com/quest=26234). There are two versions of this quest, one for Trolls and one for the other Horde races, so I assume something is messed up with that.

Achievement: [Let's Do Lunch: Orgrimmar](http://www.wowhead.com/achievement=5475)

**Comment by Tessa99999** [comment]
I can confirm this to still be true as of May 8th 2015. I did each version of Stealing From Our own today separately and turned them in and received no credit. This has happened several times.

**Comment by BAndysc** [comment]
Fixed in rev [4849]. You have to redo Stealing From Our own again
