### ISSUE TITLE
[PL][NPC] Therazane

### ISSUE THREAD

**Issue by NeedWeed** [Atlantiss/BugTracker#1794]
http://www.wowhead.com/npc=42465/therazane

Kiedy Boss zostaje pullniety przez gracza ktory jest unfrendly dla frakcji http://www.wowhead.com/faction=1171/therazane nie traci targetu po przejsciu nawet calego deepholmu, jedynie gdy dostaniemy inv na inste / bg boss traci na nas agro i pozostaje w miejscu w ktorym go zostawilismy.

**Comment by Drutmaster** [comment]
Toż tego nie powinno się w ogóle pullać. Co wy macie za pomysły? xD

**Comment by NeedWeed** [comment]
Ja latalem po deepholmie tylko i nagle patrze, goni mnie Therazane :D. nvm
Nic nie zmienia faktu ze jest to bug :)

**Comment by Thefakemccoy** [comment]
NOt sure if the post is the same topic as i want, But i do know a bug once you are friendly with Therazane it should auto un check at war with the. It does not and this can cause issues with doing quest for them.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3902 duplicate
