### ISSUE TITLE
[PL][Instancja][Quest]Compendium of the Fallen

### ISSUE THREAD

**Issue by Hosampsich** [Atlantiss/BugTracker#1796]
lokalizacja: Trisfal Glades
Instancja: Scarlet Monstastery Graveyard

Miejsce gdzie znajduje się książka jest widoczne i oznaczone jako przedmiot do wzięcia, 
lecz nie można wziąć z niego przedmiotu wymaganaego do ukończenia zadania.

http://www.wowhead.com/quest=1049/compendium-of-the-fallen
http://wow.zamimg.com/uploads/screenshots/resized/10404.jpg

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1559
