### ISSUE TITLE
[EN] [QUEST] [The Battle For The Ebon Hold] Patchwerk Respawn Timer

### ISSUE THREAD

**Issue by MorbidMike** [Atlantiss/BugTracker#1797]
The respawn timer of Patchwerk in the final quest of the Death Knight chain is way too high. At the moment it has not respawned for 30 minuted, and another guy came checking who said he had been waiting for it for 20 minutes as well. I have no idea how long it is supposed to be but it was never this long on retail.

**Comment by Wolffenstein** [comment]
Fixed in rev 4320.
