### ISSUE TITLE
[EN][Spell][Rogue] Vanish

### ISSUE THREAD

**Issue by lastkiss** [Atlantiss/BugTracker#1799]
Vanish http://cata.openwow.com/spell=1856 can be instantly  broken by mage's Orb's http://cata.openwow.com/spell=84721 and http://cata.openwow.com/spell=82731

Vanish effect should prevent a rogue from being kicked out of stealth by any dmg for 3 sec

"Allows the rogue to vanish from sight, entering an improved stealth mode for 3 sec. For the first 3 sec after vanishing, damage and harmful effects received will not break stealth."

**Comment by Jenovas** [comment]
http://www.skill-capped.com/forums/showthread.php?9551-Fire-orb-breaking-vanish
