### ISSUE TITLE
[PL][Spell][Death Knight] Frost Fever

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#180]
http://cata.openwow.com/spell=59921
http://cata.openwow.com/spell=59879

Frost Fever jest w stanie zmissować (nie nalożyć się) nawet jeśli spell nakładający ten debuff trafi

Podejrzewam, że to samo może się dziać dla Blood Plague

Na main realmie to samo dzieje się dla outbreak

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
