### ISSUE TITLE
[EN][Raid][Loot] Request: Can you please check Onyxias (Lvl 80) loot table.

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#1800]
After 20 Kills I still haven't seen Gleaming Quel'Serrar drop 
http://www.wowhead.com/item=49303/gleaming-quelserrar 

This might just be bad luck, but I have talked with other players that farmed for the sword and it never dropped for them either.

It's supposed to have a 5.7% drop rate.

As I said, this might just be really bad luck, but could you please check her loot table? Thanks

**Comment by Nukeey** [comment]
I am up to 32 Kills now. I have seen every other weapon drop multiple times. But not this sword.

**Comment by LordMoriarty** [comment]
It dropped for us on July 26. 
There was however no head nor bag.
http://www.wowhead.com/item=49643/head-of-onyxia#comments (Alliance: http://www.wowhead.com/item=49644/head-of-onyxia#comments )
http://www.wowhead.com/item=49295/enlarged-onyxia-hide-backpack

The bag of gems DID DROP.
There's no head on Nefarian in BWL too.

**Comment by Nukeey** [comment]
Got it a few weeks ago.
Closing issue.
