### ISSUE TITLE
[EN][other] Drinks and food cost buying from vendor

### ISSUE THREAD

**Issue by dillanX** [Atlantiss/BugTracker#1801]
Hello,

there is currently a bug with the costs of food and drinks from the vendor.
Example:

Stormwind.
Innkeeper Allison
when I buy shiny Red Apple the cost is 21 copper
but when I buy it, it costs me 1 silver 
same with drinks.

meaning that because it is a stack of 5 it is per item the cost  21 x 5 stack = 1 silver 5 copper

Thank you for your time

**Comment by Wolffenstein** [comment]
Confirmed.
