### ISSUE TITLE
[EN] [Talent] [Druid] Rejuvenation

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#1802]
So this is what my mate said:
druid healer rejuvenation is bugged because when u put talent Gift of the earthmother when u use rejuvenation it heals for me 3k than after 2 sec it heals 4k ....the talent Gift of the earthmother should give it instant 15% rejouvenation thats not working at all and druid healer without it is nothing !!

**Comment by Wolffenstein** [comment]
And my mate said that it's working ok.

No links, no calculations, no proof. We're not accepting these kind of reports.
