### ISSUE TITLE
[ENG][Talent][Lock&Load]

### ISSUE THREAD

**Issue by Oldworldgame** [Atlantiss/BugTracker#1803]
After fixx talent lock&load dont take focus in second use but still is unuseable in rotation:
explosive shot - arcane shot - explosive shot 
when u dont have 50focus and should be free to use.
http://www.wowhead.com/spell=168980/lock-and-load

**Comment by xolon** [comment]
its doesn't remove focus when you do it, but for some reason you need 45 focus to do it

**Comment by Oldworldgame** [comment]
the second use of explosive shot in rotation above should be for free but its not in half way couse needs to have 50focus but dont take this focus. should be useable even with 0 focus.

**Comment by arekczup** [comment]
używałem dla mnie to było randomowo czasami mi się castował a czasami mi wogule sie nie czstowało
trzebało mieć te 45 punktów focusu .
ENG
j us for then is random spell cast .

**Comment by arekczup** [comment]
is the problem for cast explosiv shot  
cost is the explosiv shot should be 50. no 44 -_-
http://www.wowhead.com/spell=53301/explosive-shot#changelog

**Comment by sshad00w** [comment]
Sometimes when we received proc. bonus from Lock and Load (http://www.wowhead.com/spell=168980/lock-and-load), the second Explosive Shot (http://www.wowhead.com/spell=53301/explosive-shot#changelog) need focus to use them.
In my experience when we use a Feign Death (http://www.wowhead.com/spell=5384/feign-death) this bugs is sometimes exist.

**Comment by lukipol** [comment]
no this bug exist very often and should be qualificated as major bug, becouse it is ~3k dps waste when you using explosive shot - arcane shot - explosive shot rotation, also very annoying bug.

**Comment by stewazy** [comment]
It required you to have atleast 50 focus to use explosive shot when lock and load procs ... so it won't use up the focus but it requires you to have  50 so you can fire off a free explosive shot :(

**Comment by mitim1** [comment]
!bump

**Comment by Jenovas** [comment]
Fixed in rev 4442
