### ISSUE TITLE
[EN] [Achievement] [Northrend] Glory of the hero

### ISSUE THREAD

**Issue by vladovlado** [Atlantiss/BugTracker#1804]
I have the incredible hulk achievement ( http://www.wowhead.com/achievement=2043/the-incredible-hulk ) but it does not count toward glory of the hero ( http://www.wowhead.com/achievement=2136/glory-of-the-hero )
Here are the screenshots - <a href="http://tinypic.com?ref=2ryqd6q" target="_blank"><img src="http://i57.tinypic.com/2ryqd6q.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://tinypic.com?ref=mignzt" target="_blank"><img src="http://i61.tinypic.com/mignzt.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://tinypic.com?ref=29cl2zq" target="_blank"><img src="http://i61.tinypic.com/29cl2zq.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Bildo** [comment]
duplicate
