### ISSUE TITLE
[EN][NPC] Jin'do the Godbreaker

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#1814]
The ability of this boss in the spirit realm called Shadow Spike seems to be a way bigger radius than 4 yards. Even if you stay 10 yards away from the bomb, it still manages to deal damage. Unfortunatelly I can't find the ability Shadow Spike in Wowhead. The second issue is unconfirmed, but it's worth mentioning. There seem to be way too many Twisted Spirits spawning in the spirit realm, way more than the retail videos I've watched.

Twisted Spirit: http://www.wowhead.com/npc=52624
NPC: http://www.wowhead.com/npc=52148

**Comment by qubuslabadz** [comment]
Fix in rev. 4282.
