### ISSUE TITLE
[PL][Quest][Instance] Questy w Zul'Gurub oraz Stranglethorn

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#1817]
Witam!
Na wstępie chciałbym napisać, że Zul'Gurub prezentuje się wspaniale: żadnych bugów nie zauważyłem, poza tym zgłoszonym dot. last bossa. Brakuje w sumie tylko jednej rzeczy, a mianowicie questów do insty i okolic dodanych wraz z 4.1. 

Te Questy to:
- http://www.wowhead.com/quest=29251/booty-bays-interests (zaczyna chaina), 
- http://www.wowhead.com/quest=29252/booty-bays-interests (drugi z chaina),
- http://www.wowhead.com/quest=29253/a-shiny-reward (ostatni z chaina).
- http://www.wowhead.com/quest=29208/an-old-friend (po ubiciu drugiego bossa powinien się pojawić mały raptorek, który daje tego questa osobom, które ukończyły chaina w stranglethorn, nagrodą za niego jest pet w postaci tego właśnie raptorka).

Oprócz tego został dodany chain w Stranglethorn, który rozpoczyna się w Orgri:
- http://www.wowhead.com/quest=29157/the-zandalari-menace (bierze się go z tablicy w stolicach),
- http://www.wowhead.com/quest=29219/bwembas-spirit (2 quest z chaina, brak u nas npc do q, mianowicie http://www.wowhead.com/npc=53081/bwemba),

- http://www.wowhead.com/quest=29220/to-bambala (ten quest odsyła nas już do Stranglethorn, gdzie rozpoczyna się kolejny chain),
- http://www.wowhead.com/quest=29221/serpents-and-poison (kolejny quest z chaina),
- http://www.wowhead.com/quest=29222/spirits-are-with-us (3 quest z chaina)

- http://www.wowhead.com/quest=29223/nesingwary-will-know (odesłanie do kolejnego obozu z questami),
- http://www.wowhead.com/quest=29226/track-the-tracker
- http://www.wowhead.com/quest=29227/the-hunters-revenge

- http://www.wowhead.com/quest=29228/follow-that-cat (wowhead pokazuje, że quest nie jest dostępny w grze, nie mniej w komentarzach ludzie potwierdzają jego istnienie, więc to po prostu jakiś błąd na stronie, czasami trzeba go sobie wziąć od kupki gruzu ),
- http://www.wowhead.com/quest=29230/mauti
- http://www.wowhead.com/quest=29231/hows-the-hunter-holding-up
- http://www.wowhead.com/quest=29232/bury-me-with-me-boots
- http://www.wowhead.com/quest=29268/some-good-will-come (quest z nagrodą w postaci peta)

- http://www.wowhead.com/quest=29233/warn-gromgol (chain w bazie hordy w Grom'gol)
- http://www.wowhead.com/quest=29235/defend-gromgol
- http://www.wowhead.com/quest=29236/to-hardwrench-hideaway
- http://www.wowhead.com/quest=29237/voodoo-zombies
- http://www.wowhead.com/quest=29238/bad-supplies
- http://www.wowhead.com/quest=29250/making-contact (quest odsyłający do Booty Bay)

Wiem, że jest tego dużo (nie chciałem niczego pominąć) Linki są do questów hordziackich, ale ally mają analogiczne questy (te same nazwy). Zrozumiem również, jeżeli ten temat dostanie low priority. Devowie mają teraz ważniejsze rzeczy do skryptowania, nie mniej z góry dziękuję za pomoc!
Rev. 4280

P.S jeżeli trzeba dodać jakieś informacje, to oczywiście w razie potrzeby dodam.

**Comment by Navedonar** [comment]
http://wow.gamepedia.com/Rise_of_the_Zandalari_quest_chain  tak powinien wyglądać chain questów
