### ISSUE TITLE
[PL][Class][Druid] Primal Fury

### ISSUE THREAD

**Issue by Bloodmisty** [Atlantiss/BugTracker#1818]
Dziś testowane:  przy uderzeniu krytykiem z mangla, shreda, ravage, rake  (w kukłe heroiczna) nabija czasami 1 combo point a zawsze powinno nabijać dwa!. Zaobserwowałem to głownie w momentach gdy taget ma 0/5 combo pointów. Po kolejnym teście nawet jak miałem 2/5 combo pointow i uderzyłem krytyka z Mangle to miałem 3/5 więc w trakcie tez jest coś nie tak.
Primal Fury: http://www.wowwiki.com/Primal_Fury

Bloodmist

**Comment by Kuszki** [comment]
Zmien build/zresetuj talenty, przejdz na ferala znow, wyloguj sie, zaloguj sie i wtedy testuj. To bylo juz naprawiane, ale do dzialania potrzebowalo resetu talentow. Zawsze dzialalo po resecie, ale po relogu sie znow zacinalo. Teraz chyba juz dziala zawsze dobrze, ale warunkiem konieczynm byl przynajmniej jeden reset talentow od czasu naprawy.

**Comment by Isuel** [comment]
idk what he's saying in here, but i think he means he gets only 1 combo point from critting (sometimes, around 50% chance). I've also noticed it happen, the chance seems to be 50% (from only 1 point).
confirmed.

**Comment by Kuszki** [comment]
@Isuel. Its the same problem as #860.

**Comment by Isuel** [comment]
yep, but the bug is still happening :P

**Comment by Bloodmisty** [comment]
Przepraszam dla czego ani w tym ani w temacie odnoszącym nie ma żadnej odpowiedzi GM?
Jak widać zostało to przetestowane przez parę osób i dalej nie wiemy kiedy  i czy w ogóle  będzie Primal Fury naprawione, 
Pozdrawiam,
Bloodmist

**Comment by Bloodmisty** [comment]
Czy mozna prosic o jakiekolwiek zainteresowanie od strony GM  tym tematem ?

**Comment by Wolffenstein** [comment]
GMi nie zajmują się naprawianiem rzeczy, więc ciężko, żeby się zainteresowali.

Powinno być fixed w revie 4326. Wymagany reset talentów.
