### ISSUE TITLE
 [PL][Talent][Spell][Rogue] Main Gauche

### ISSUE THREAD

**Issue by Natureone** [Atlantiss/BugTracker#1822]
Każdy punkt mastery powinien zwiększać szanse uderzenienia z Main Gauche o 2%
http://www.wowhead.com/spell=76806/mastery-main-gauche

Na chwilę obecną mastery daje 1% na Main Gauche.

**Comment by tnarf** [comment]
Z tego co widze dla 15.55 mastery daje mi 31%
31/2 = 15,5
wiec kazdy punkt daje 2%.

Mozesz odnosic wrazenei ze dodaje 1 poniewaz mastery w tooltipie (ogolnie mozliwe ze tez) naliczane jest co najmniejsza wyswietlana cyfre, czyli co 1%, co nam daje w tym przypadku 0,5 mastery
