### ISSUE TITLE
[PL][NPC]Gurubashi Shadow Hunter

### ISSUE THREAD

**Issue by NeedWeed** [Atlantiss/BugTracker#1824]
http://www.wowhead.com/npc=52327/gurubashi-shadow-hunter#abilities

http://www.wowhead.com/spell=96767 - Skill ten bije od 1pkt obrazen do 5. Nie jestem pewien, ale z normalnymi atakami moze byc podobnie.

Rev.4280

**Comment by qubuslabadz** [comment]
Fixed in rev. 4297.
