### ISSUE TITLE
[PL][NPC] Renataki

### ISSUE THREAD

**Issue by NeedWeed** [Atlantiss/BugTracker#1825]
http://www.wowhead.com/npc=52269/renataki#abilities

http://www.wowhead.com/spell=96640/ambush - Nie dziala, nie redukuje HP, nie jestem pewien ale stuna chyba tez nie ma.

Rev.4280

**Comment by qubuslabadz** [comment]
Przetestowałem i bije ładnie tym skillem. http://oi58.tinypic.com/flh7kg.jpg
