### ISSUE TITLE
[PL][Class][Death Knight] Ghoul action bars

### ISSUE THREAD

**Issue by Malyrycerz** [Atlantiss/BugTracker#1828]
Witam, ja oraz kilku innych graczy, mamy problem ze skilami naszych petów, a chodzi o to, ze po próbie wymiany jakiegokolwiek skilu na pasku peta po wejściu i zejściu na mounta, relogu, wejściu na inste, bg itp. miejsca ze zmienonymi skilami zostają puste. Mimo ponownego ustawienia skili na pasku po wykonaniu wyżej wymienionych czynności skile ponownie znikaja. Napisałem w tej sprawie ticketa i mimo wielu prób naszych GM-ów problem nie został rozwiązany, dlatego też polecono mi napisanie tego posta. Problemy te maja wszystkie klasy posiadające pety ale nie zawsze, nie wiem od czego to zależy w przypadku huntera pomaga kolejne złapanie peta, neistety dk, warlock nie maja takiej możliwości. Prosimy o szybkie zbadanie problemu. Pozdrawiam

**Comment by Varchord** [comment]
Gdzies tu juz jest taki temat

**Comment by Kuszki** [comment]
Spotkałem się już z podobnym problemem kiedyś i dotyczył on tylko "akcji" peta (attack, follow, stay, pasive, assist.. itd) - po przesunięciu/usunięciu/wstawieniu/zmianie tych akcji na pasku peta znikały one i nigdy więcej się nie pojawiały - zawsze znikały po odwołaniu i przywołaniu peta (nawet automatycznym - mount + dismount).

Pomagało tylko złapanie nowego peta.

Innymi słowy - ingerencja dotycząca zmiany pozycji "akcji peta" (nie skili) powodowała, że bezpowrotnie znikały one z pet-bara.

**Comment by Kushimaru** [comment]
ja rowniez mam taki problem z petem

**Comment by jagoan1** [comment]
i dont understand polish but it seems this is the same problem that i have. attack/follow/etc command doesnt showed up after dismount or change area or summon. any solution for this? coz DK cant tame another pet to fix it.

**Comment by Malyrycerz** [comment]
jagoan1, yes thats the same. Unfortunetly we stil waiting that someone fix it.

**Comment by Wolffenstein** [comment]
Fixed in rev 4318.
