### ISSUE TITLE
[EN][Spell][Druid] Wild Mushrooms sound effect.

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#1832]
Mushrooms are missing sound effect when spawned.

This time watch it more closely so we can have blizzlike feeling while playing here.
Proof:
https://www.youtube.com/watch?v=RK81Qn9d940&feature=youtu.be&t=20s
https://www.youtube.com/watch?v=13oOon5AWXo
Openwow links:
http://cata.openwow.com/spell=78777
http://cata.openwow.com/spell=88751

**Comment by Jenovas** [comment]
fixed in rev  4286
