### ISSUE TITLE
[EN][Item][Druid] Flask of Battle (Cauldron) for feral

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#1835]
Flask of Battle (http://www.wowhead.com/item=65455/flask-of-battle) from Cauldron on Battle (http://www.wowhead.com/item=62288/cauldron-of-battle) should give ferals Stamina flask buff in Bear form and Agility flask buff in any other form, but when used in humanoid form (not shapeshifted) it gives you intellect instead of agility.

**Comment by Rainofblood** [comment]
No matter which talents you have on, bear will give you stamina, cat agi, humanoid int.

**Comment by Iambugged** [comment]
That's what it does but the item description says: "Use in bear form to gain stamina and in ANY other form to gain agility"

**Comment by pelekon** [comment]
fixed in rev 5903
