### ISSUE TITLE
" The Usual Suspects " quest bugged

### ISSUE THREAD

**Issue by amd87** [Atlantiss/BugTracker#1838]
this quest is no more working , workers not interogated by clicking on them , this quest is so important to reach twilight highlands , the quest is part of a quest chain , please fix that as soon as possible , thank you

**Comment by amd87** [comment]
sorry , it was my bad , loosing anduil wont make you able to interogate worker , thank you

**Comment by Exorcista** [comment]
Reopen this, Anduil doesnt reach the harbor because of a LOS problem he just stands there and doesnt go down the stairs
