### ISSUE TITLE
[PL] [Spell] [Hunter] Flare

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#1840]
[Flare](http://www.wowhead.com/spell=1543/flare)

Gdy zostanie wystrzelona w wybrane miejsce i podczas lotu przemieścimy się tak, że nie bedziemy w linii z tym miejscem gdy flara ląduje, to zwrócony zostanie komunikat "Target not in line of sight", a flara nie pojawi się w wybranym miejscu.

Przykład: "wyłaniam się zza filaru" -> rzucam flarę -> "flara leci" -> wchodzę za filar -> "flara ląduje" -> komunikat o błędzie + flara nie pojawia się na ziemi -> CD flary zmarnowane.

Wygląda na to, że "lądowanie flary" powoduje użycie jakiegoś spela który wymaga "kontaktu wzrokowego" z celem.

**Comment by Navedonar** [comment]
http://us.battle.net/wow/en/forum/topic/1827254383#2

**Comment by Jenovas** [comment]
Flare does not work at all if the hunter goes out of line of sight from where it landed.
