### ISSUE TITLE
[EN] [Dungeon - WotLK] Utgarde Keep

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1841]
Some minor points I've noticed after doing [Utgarde Keep](http://www.wowhead.com/zone=206/utgarde-keep):

- [Dragonflayer Strategists](http://www.wowhead.com/npc=23956/dragonflayer-strategist) don't use their ability [Ticking Bomb](http://www.wowhead.com/spell=54962) at all. They do cast their ability [Hurl Dagger](http://www.wowhead.com/spell=42772), but without success. To me it looks like they have no target (nil) ([combat log](http://pastebin.com/wyRKSsH7)).

- On the terrace if you cross an invisible trigger, a [Proto-Drake Rider](http://www.wowhead.com/npc=24849/proto-drake-rider#abilities) and his [Enslaved Proto-Drake](http://www.wowhead.com/npc=24083/enslaved-proto-drake) should land ([pic](http://i.imgur.com/Gc49NGl.jpg)). Right now, they stay where they are, and the rider is more like a stander.

- The endboss [Ingvar the Plunderer](http://www.wowhead.com/npc=23954/ingvar-the-plunderer#abilities) had a weird invisible unit *"Ingvar Throw Dummy"* standing next to himself. [pic](http://i.imgur.com/nC4uXxl.jpg). I also was not able to loot his head for the quest [Into Utgarde!](http://www.wowhead.com/quest=11252/into-utgarde)  ([pic](http://i.imgur.com/bmHTobE.jpg)) (see also [#119](https://github.com/Atlantiss/BugTracker/issues/119)). It had the bug where if I click the corpse, the loot window opens and closes itself again some miliseconds later.

**Comment by Quban** [comment]
For the http://www.wowhead.com/npc=23956/dragonflayer-strategist bug

DELETE FROM `smart_scripts` where `entryorguid`=23956 and `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(23956,0,0,1,1,0,100,7,0,0,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Out of Combat - Disable Combat Movement (No Repeat) (Dungeon)'),
(23956,0,1,0,61,0,100,0,0,0,0,0,20,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Out of Combat - Stop Attacking (No Repeat) (Dungeon)'),
(23956,0,2,3,4,0,100,3,0,0,0,0,11,42772,0,0,0,0,0,2,0,0,0,0,0,0,0,'Dragonflayer Strategist - On Aggro - Cast \'Hurl Dagger\' (No Repeat) (Normal Dungeon)'),
(23956,0,3,0,61,0,100,0,0,0,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - On Aggro - Increment Phase By 1 (No Repeat) (Normal Dungeon)'),
(23956,0,4,5,9,0,100,2,5,30,2300,5000,11,42772,0,0,0,0,0,2,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-30 Range - Cast \'Hurl Dagger\' (Normal Dungeon)'),
(23956,0,5,0,61,0,100,0,0,0,0,0,40,2,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-30 Range - Set Sheath Ranged (Normal Dungeon)'),
(23956,0,6,7,4,0,100,5,0,0,0,0,11,59685,0,0,0,0,0,2,0,0,0,0,0,0,0,'Dragonflayer Strategist - On Aggro - Cast \'Hurl Dagger\' (No Repeat) (Heroic Dungeon)'),
(23956,0,7,0,61,0,100,0,0,0,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - On Aggro - Increment Phase By 1 (No Repeat) (Heroic Dungeon)'),
(23956,0,8,9,9,0,100,4,5,30,2300,5000,11,59685,0,0,0,0,0,2,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-30 Range - Cast \'Hurl Dagger\' (Heroic Dungeon)'),
(23956,0,9,0,61,0,100,0,0,0,0,0,40,2,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-30 Range - Set Sheath Ranged (Heroic Dungeon)'),
(23956,0,10,11,9,0,100,7,25,80,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 25-80 Range - Enable Combat Movement (No Repeat) (Dungeon)'),
(23956,0,11,0,61,0,100,0,0,0,0,0,20,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 25-80 Range - Start Attacking (No Repeat) (Dungeon)'),
(23956,0,12,13,9,0,100,7,0,5,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 0-5 Range - Enable Combat Movement (No Repeat) (Dungeon)'),
(23956,0,13,14,61,0,100,0,0,0,0,0,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 0-5 Range - Set Sheath Melee (No Repeat) (Dungeon)'),
(23956,0,14,0,61,0,100,0,0,0,0,0,20,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 0-5 Range - Start Attacking (No Repeat) (Dungeon)'),
(23956,0,15,16,9,0,100,7,5,15,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-15 Range - Disable Combat Movement (No Repeat) (Dungeon)'),
(23956,0,16,0,61,0,100,0,0,0,0,0,20,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - Within 5-15 Range - Stop Attacking (No Repeat) (Dungeon)'),
(23956,0,17,0,0,0,100,2,4500,5000,11000,16000,11,54962,1,0,0,0,0,5,0,0,0,0,0,0,0,'Dragonflayer Strategist - In Combat - Cast \'Ticking Bomb\' (No Repeat) (Dungeon)'),
(23956,0,18,0,0,0,100,4,4500,5000,11000,16000,11,60227,1,0,0,0,0,5,0,0,0,0,0,0,0,'Dragonflayer Strategist - In Combat - Cast \'Ticking Time Bomb\' (No Repeat) (Dungeon)'),
(23956,0,19,0,0,0,100,6,7500,9000,13000,15000,11,42972,1,0,0,0,0,5,0,0,0,0,0,0,0,'Dragonflayer Strategist - In Combat - Cast \'Blind\' (No Repeat) (Dungeon)'),
(23956,0,20,0,7,0,100,7,0,0,0,0,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Dragonflayer Strategist - On Evade - Set Sheath Melee (No Repeat) (Dungeon)');

**Comment by Bildo** [comment]
rev. 4353 by Quban
