### ISSUE TITLE
[PL] [Spell] [Racial] Elusiveness

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#1847]
Umiejętność rasowa Nocnych Elfów: Elusiveness nie dodaje bonusu do szybkości ruchu w stealth.
http://www.wowwiki.com/Elusiveness_%28night_elf_racial%29

Testowane klasą "Rouge":
-Wartość szybkości ruchu w panelu "Character Info" nie ulegają zmianie po wejściu w Stealth (bez talentów w "Nightstalker"). To pierwsze podejrzenie, jednak sprawdzałem również w praktyce: pokonałem tę samą trasę w identycznym czasie będąc w stealth i nie. Rzeczywiście nie działa. Jakby brakowało wartości.

**Comment by Jenovas** [comment]
Fixed in rev 4374
