### ISSUE TITLE
[EN][NPC] Kore <Warrior Trainer>

### ISSUE THREAD

**Issue by gashole** [Atlantiss/BugTracker#1849]
Kore <Warrior Trainer> (ID: 16503) in Azuremyst Isle should only train class abilities up to level 6. Parry, Rend, & Thunder Clap have the wrong level requirements and should not be trainable here.

![kore-warrior-trainer](https://cloud.githubusercontent.com/assets/7091308/5935187/d0a2cce2-a68c-11e4-95af-38c76217fcd1.png)

**Comment by Quban** [comment]
-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
DELETE FROM `npc_trainer` WHERE `entry` = 16503 AND `spell` NOT IN (100, 772, 34428);

**Comment by Bildo** [comment]
@Quban jak dodajesz jakies sqlki do rob tak
''-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
DELETE FROM npc_trainer WHERE entry = 16503 AND spell NOT IN (100, 772, 34428);''

**Comment by Bildo** [comment]
@Quban jak dodajesz jakies sqlki do rob tak
>-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
DELETE FROM npc_trainer WHERE entry = 16503 AND spell NOT IN (100, 772, 34428);>

**Comment by Bildo** [comment]
@Quban jak dodajesz jakies sqlki do rob tak

~~-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
DELETE FROM npc_trainer WHERE entry = 16503 AND spell NOT IN (100, 772, 34428);>~~

**Comment by Bildo** [comment]
`-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
DELETE FROM npc_trainer WHERE entry = 16503 AND spell NOT IN (100, 772, 34428);`

**Comment by Bildo** [comment]
@Quban jak wrzucasz sqlki to rob uzywaj `
-- spell: 100 (Charge), 772 (Rend), 34428 (Victory Rush)
`DELETE FROM npc_trainer WHERE entry = 16503 AND spell NOT IN (100, 772, 34428);`

**Comment by Bildo** [comment]
fixed in rev 4294 by Quban
