### ISSUE TITLE
[EN][NPC] Surveyor Candress

### ISSUE THREAD

**Issue by gashole** [Atlantiss/BugTracker#1850]
Surveyor Candress (ID: 16522) in Azuremyst Isle                                     

* Stands around when idle when she should be channeling the bloodstone.
* Doesn't move when attacked and only melee attacks if you are in melee range. 

Retail video:
http://youtu.be/Jc4BiOBMAsw

**Comment by Wolffenstein** [comment]
Fixed in rev 4330.
