### ISSUE TITLE
[EN] [Quest] [Gameobject] [Blackfathom Deeps] "Knowledge in the Deeps"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1851]
The Quest [Knowledge in the Deeps](http://www.wowhead.com/quest=971/knowledge-in-the-deeps) requires you to loot the quest item from the [Pitted Iron Chest](http://www.wowhead.com/object=13949/pitted-iron-chest). This works, but the chest should respawn after a couple of seconds, so everybody in the group can loot it, not after several minutes like it is now.

**Comment by Navedonar** [comment]
https://www.youtube.com/watch?v=QCBqOwQjbRY 9:03

**Comment by Quban** [comment]
update `gameobject` set `spawntimesecs` = 5 where `id` = 13949 and `map` = 48;

**Comment by Wolffenstein** [comment]
4292
