### ISSUE TITLE
[EN][Quest][Azuremyst Isle] Tree's Company

### ISSUE THREAD

**Issue by postblock** [Atlantiss/BugTracker#1852]
Same problem as posted here:
https://github.com/TrinityCore/TrinityCore/issues/13736

>Tree's Company
http://www.wowhead.com/quest=9531

>Tree Disguise Kit:
http://www.wowhead.com/item=23792

>Bug description:
When walking up to the cove where the flag is, the scripted actions start before the disguise is used, then when the disguise is used it initiates the scripted actions a second time, overlapping the first.

>How it should be:
Go to the designated cove and look for a naga flag. Use the disguise kit when you see the flag and wait. Eventually the traitor will show up. Let the meeting finish to get credit for completion.

**Comment by Rushor** [comment]
DELETE FROM creature WHERE guid=85587;

**Comment by Bildo** [comment]
We have diffrent guids than you have.

**Comment by Rushor** [comment]
soo you don't use trinitycore as base? okay well simply run this instead:

DELETE FROM creature WHERE  `id`=17318;

**Comment by Bildo** [comment]
No, we don't

**Comment by cosminush** [comment]
The NPC [http://www.wowhead.com/npc=17243] isn't deleted after he speak with the goblin, and there are a lot of spawns of him.
PS: http://imgur.com/YiE2Xvh

**Comment by Bildo** [comment]
fixed
