### ISSUE TITLE
[Warlock][Spell][Ritual of Summoning]

### ISSUE THREAD

**Issue by Haffyd** [Atlantiss/BugTracker#1857]
Od przejścia na patch 4.3.4 nie działa w/w spell. Jest to bardzo irytujące, gdyż traci się masę czasu przy zbieraniu na raidy osoby.

**Comment by Spymage** [comment]
Ten spell nie działa na serwie od kiedy pamietam czyli jakoś od 07.2013

**Comment by Haffyd** [comment]
Przed zmianą patcha działał.

**Comment by Varchord** [comment]
Taki temat już istnieje. Poza tym nie działa mechanika tego typu summa
Linki wowgead

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/837
