### ISSUE TITLE
[Meeting Stone]

### ISSUE THREAD

**Issue by Haffyd** [Atlantiss/BugTracker#1858]
Wszystkie meeting srony nie działają prawidłowo. W momencie kiedy ktoś próbuje sumnąć kogokolwiek przyzywana jest osoba, która kliknie w portal. Jest to niesłychane utrudnienie przy wypadach na dungi i raidy. Jak narazie jedyny summon, który działa poprawnie to perk gildijny.

**Comment by Wolffenstein** [comment]
Było zgłaszane.
