### ISSUE TITLE
[PL][Shaman][spell/guardian] Fire Elemental doesnt use spells

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1859]
http://www.wowhead.com/spell=2894/fire-elemental-totem
Elemental nie uzywa skilli:

**Fire Nova** (Zadaje AOE dmg zblizony do melee ataku, jest to **BARDZO** wazny spell, mocno podnosi dps shama w walkach aoe) http://www.wowhead.com/spell=12470/fire-nova
**Fire Blast** (Zadaje fire dmg, dosyc spory) 
http://www.wowhead.com/spell=57984/fire-blast#used-by-npc

Wiekszosc dmg elementala (ok 70%) powinno pochodzic z melee, wyjatkiem sa AOE sytuacje, gdzie wiekszosc dmg powinien stanowic spell Fire Nova, ktorego nasz elemental nie uzywa.

**Comment by mitim1** [comment]
bump!
