### ISSUE TITLE
[PL][Quest][Game object][The Nexus] Have they no shame?

### ISSUE THREAD

**Issue by Alandiel** [Atlantiss/BugTracker#1860]
http://www.wowhead.com/object=192788/berinands-research respi się zdecydowanie zbyt długo.
http://youtu.be/pySQvQey1f8?t=40s widać, że od razu po podniesieniu książka się zrespiła.

**Comment by Quban** [comment]
update `gameobject` set `spawntimesecs` = 1 where `id` = 192788 and `map` = 576;

**Comment by Bildo** [comment]
fixed in rev 4294 by Quban
