### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] The Only Way Down is in a Body Bag

### ISSUE THREAD

**Issue by zero092** [Atlantiss/BugTracker#1861]
http://www.wowhead.com/quest=25614/the-only-way-down-is-in-a-body-bag
Creeps are bearly spawning and when they do,they're usually outside of shooting range and if by some miracle they do come into your range,its next to impossible to shoot them down,cannonballs literally go through them. 
![wowscrnshot_012815_165319](https://cloud.githubusercontent.com/assets/10528535/5940992/83d64650-a70e-11e4-984c-930c9fcaeb1c.jpg)

**Comment by Bildo** [comment]
duplicate
