### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Save the Children!

### ISSUE THREAD

**Issue by zero092** [Atlantiss/BugTracker#1862]
http://www.wowhead.com/quest=25889/save-the-children
Cant drop off druids.The game is telling me im not in the right place,while i actually am.
![wowscrnshot_012815_185722](https://cloud.githubusercontent.com/assets/10528535/5943467/88c694ba-a71f-11e4-9253-8aa68e39d29d.jpg)

**Comment by Bildo** [comment]
duplicate
