### ISSUE TITLE
[EN][QUEST][NORTHREND] "Blightbeasts be dammed!"

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#1866]
![wowscrnshot_012815_213429](https://cloud.githubusercontent.com/assets/10423624/5947544/d7a19b78-a735-11e4-8a98-c5455429db6b.jpg)
The Kor Kron War Rider does not fly when you press space and stays fixed to teh ground similar to a non flying mount. 
http://www.wowhead.com/quest=12072/blightbeasts-be-damned

**Comment by Bildo** [comment]
duplicate
