### ISSUE TITLE
[EN] [Gameobject] [Blackrock Depths] Chest of the Seven

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1869]
The [Chest of the Seven](http://www.wowhead.com/object=169243/chest-of-the-seven) which spawns after you successfully fought [The Seven](http://www.wowhead.com/npc=9039/doomrel) contains no loot.

(Other than that, the dungeon works fine now. The great wheel/door mechanism operates smoothly, the drunk dwarf in the Grim Guzzler opens the door for you by smashing a keg, new meeting stones outside... great!)

**Comment by Wolffenstein** [comment]
Fixed in rev 4292.
