### ISSUE TITLE
[en][Item][Drop] 378 ilvl items from HoT dropping from random mobs

### ISSUE THREAD

**Issue by serianx** [Atlantiss/BugTracker#1870]
It seems that Hour of Twillight items ilvl 378 like
http://www.wowhead.com/item=72799/dead-end-boots
http://www.wowhead.com/item=72805/gloves-of-the-hollow
are dropping from random mobs .
people are getting better than heoric gear farming random mobs in northrend
this is the npc that dropped the gloves
http://www.wowhead.com/npc=28465/hebdrakkar-striker

**Comment by Wolffenstein** [comment]
Don't worry, they will be removed.

**Comment by Wolffenstein** [comment]
Fixed. All items will be removed tonight.
