### ISSUE TITLE
[EN] [By Hook or by Crook] [Northern Barrens]

### ISSUE THREAD

**Issue by Krexos** [Atlantiss/BugTracker#1872]
Hey, the quest isn't working fine the razormane prisoner will not talk at any option!

**Comment by Bildo** [comment]
duplicate

**Comment by Drutmaster** [comment]
and he is talking, but only first time. At the beginning you have 4 options, first 2 are aggresive (beat him or sth) and second 2 are nice (feed or sth). If you choose agressive options, quest will be not completable, cause only nice options will make him talk (but they dissappear after first talk). So you need to take q once again and choose nice option.

**Comment by HK8919** [comment]
There are 4 options or so.
Depending on the option you take you get a buff.
You're mean -> You get mean buff and you can only pick mean opciones
You're nice -> You get nice buff and you complete the quest

If you were mean just right click your buff and pick a nice option.

Boom, your quest was completed.
