### ISSUE TITLE
[EN][Web] Item/Talent links

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#1873]
I've seen that the talent calculator bug has been reported. But the missing/broken images/links for talents generalizes for items too. The armory has broken links towards items in the character page.

**Comment by PatriotasLT** [comment]
They know it, now focusing on fixing game bugs. Read in forum http://atlantiss.eu/community/viewtopic.php?f=9&t=408&p=3495&hilit=armory#p3495
