### ISSUE TITLE
[PL]Talent nie dodaje dmg | Paladyn

### ISSUE THREAD

**Issue by Dawid5221** [Atlantiss/BugTracker#1874]
[PL][Talent][Class] <Wiem fail w tytule> :c

W drzwku protection środkowy talent na samej górze powinnien zwiększyć nasz dmg od umiejętności Seal of Righteousness i jakieś tam innej

Ilość zwiększonego dmg nie widać ani na obrazu z umiejetnością<Po jej aktywacji> jak i podczas bicia mobków itd...

Proszę o szybką interwencję!

**Comment by Jenovas** [comment]
Proszę napisać poprawnie zgłoszenie. Zamykam.

**Comment by Dawid5221** [comment]
Nie znam angielskiego by przeczytać zasady ;p

**Comment by Nc94** [comment]
Żałosne zgloszenie.
Chodziło pewnie o talent Seals of the Pure w drzewku prot -http://www.wowwiki.com/Seals_of_the_Pure
Talent działa na Seal of the Righteousness jak i Seal of Truth nie działa jedynie dla Seal of Justice.
Recount:
Talent 0/2:
http://i.imgur.com/V1MHTX5.png
Talent 1/2:
http://i.imgur.com/c0lDHja.png
Talent 2/2:
http://i.imgur.com/OSCREBw.png
