### ISSUE TITLE
[EN] [Social] [Friend list] Player names containing special characters

### ISSUE THREAD

**Issue by molesterman69** [Atlantiss/BugTracker#1875]
When trying to add a player with such a name to the friend list, the special character (or diacritical mark) is being ignored which means the person with the exact name but without the special characters is added instead. Sometimes that person happens to be from the other fraction which results in an error message. For example, adding a player named Jôhn would instead add the player John.

I am aware that this issue has been reported in the past, however, the report is closed and the bug is still around.

Kindest regards.

**Comment by BeVeR86** [comment]
Yep I am having this issue aswel.

Here is a little example of what happens:
Mailing something to Hárry will send the item to Harry, or mailing something to Érïk will send it to Erik.

I really hope this gets fixed soon. Just a small suggestion, if this isn't easy to fix it might be a good idea not to allow the use of special characters in character names. (not a fix but will save you from people complaining)

**Comment by Emtec** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/1530
