### ISSUE TITLE
[EN] [NPC] Plague Walker

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#1876]
The Plague Walkers in Ahn'kahet: The Old Kingdom seem to randomly cast the Aura of Lost Hope on every party member. He's supposed to do that only when engaged.

Aura of Lost Hope: http://www.wowhead.com/spell=56709/aura-of-lost-hope#used-by-npc
NPC: http://www.wowhead.com/npc=30283/plague-walker

**Comment by Bildo** [comment]
fixed in rev 4294
