### ISSUE TITLE
[PL][Spell][Rogue] Smoke Bomb

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1878]
http://www.wowhead.com/spell=76577/smoke-bomb

http://wstaw.org/m/2015/01/29/WoWScrnShot_012915_162901.jpg
Smoke bomb powinna chronić przed obrażeniami innych jeśli w niej przeciwnik nie stoi - jednak u nas na arenie dmg przechodził. Ja stałem w bombie, przeciwny hunter poza nią. 
Testując w duelu niby działa ok ale na arenie się buguje.

**Comment by Jenovas** [comment]
To mogło się stać po moich ostatnich poprawkach, bo zmieniałem w sposób w jaki działa camo u hunta i niestety efekty tych spelli są te same więc jedno wpływa na drugie, ale bardzo dziwne że na arenie nie działa a w duelu działa. Sprawdzę czy to nie moja poprawka.

**Comment by Iambugged** [comment]
Doesn't look like English to me..

**Comment by Arcadia713** [comment]
Sorry, my bad - title changed.

**Comment by Urith** [comment]
Wg opisu spella zabrania on jedynie targetowania z zewnątrz do wewnątrz albo z wewnątrz na zewnątrz. Nie ma mowy o żadnej ochronie przed obrażeniami. Jeżeli jesteś pod wpływem AoE powinno mimo wszystko działać. Jeżeli chodzi o to dlaczego strzelał hunter, nie mam pojęcia. Może działa pod macro [@mouseover] strzelanie bez targetowania nawet jeżeli jesteś w chmurce.

**Comment by lastkiss** [comment]
hunters mark nie ma wplywu na mozliwosc bicia w smoke bomb, testowalem

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/1884 Tutaj niby też jest jakiś świeży bug z frakcjami na arenkach, kto wie ;s

**Comment by Genomnomnomnom** [comment]
- Jeśli dwa enemy Rogue klada Smoke Bomb w odddzielnych miejscach, mogą się targetować i Shadowstepować do siebie. Pewnie dotyczy to też pozostałych graczy, więc Bomby zamiast tworzyć za każdym razem osobny LoS tworzą wspólnie "sieć połączonych chmur" (błagam niech ktoś to wytłumaczy za mnie)
- Smoke Bomb powinien negować działanie Spirit Link Totem Szamana
- Jeśli położę Smoke Bomb na enemy targecie, odbiegnę z dala od jej zasięgu, to przeciwnik wciąż jest w stanie targetować mnie na zewnątrz Bomby

**Comment by kadi2** [comment]
@Genomnomnomnom 
"Jeśli dwa enemy Rogue klada Smoke Bomb w odddzielnych miejscach, mogą się targetować i Shadowstepować do siebie. Pewnie dotyczy to też pozostałych graczy, więc Bomby zamiast tworzyć za każdym razem osobny LoS tworzą wspólnie "sieć połączonych chmur" (błagam niech ktoś to wytłumaczy za mnie)"
100% Blizzlike "bug"
"Smoke Bomb powinien negować działanie Spirit Link Totem Szamana"
https://github.com/Atlantiss/BugTracker/issues/464

**Comment by Genomnomnomnom** [comment]
- Smoke Bomb powinien negować efekt SLT Shamana (jeśli to trudne do naprawienia, to ustawiłbym po prostu, że SLT nie działa na targety z debuffem SB)

- jeśli położy się Smoke Bomb i wybiegnie poza niego, Rogue ciągnie efekt za sobą i wciąż można wykrywać Stealth/Prowl celów w zasięgu 

- można działać na zewnątrz Smoke Bomb właściwie dowolnym spellem (jeśli jest się w środku unfriendly SB, można targetować na zewnątrz)

**Comment by Jenovas** [comment]
niektóre spelle przechodzą przez Smoke Bomb jakby w ogóle go nie było (np. Judgement i Hand of Reckoning)

Smoke Bomb powinien negować efekt SLT Shamana (jeśli to trudne do naprawienia, to ustawiłbym po prostu, że SLT nie działa na targety z debuffem SB)

jeśli położy się Smoke Bomb i wybiegnie poza niego, Rogue ciągnie efekt za sobą i wciąż można wykrywać Stealth/Prowl celów w zasięgu

można działać na zewnątrz Smoke Bomb właściwie dowolnym spellem (jeśli jest się w środku unfriendly SB, można targetować na zewnątrz)

Wszystko powinno działać po następnym upie
