### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Graverobbers

### ISSUE THREAD

**Issue by Fikoblin** [Atlantiss/BugTracker#1879]
http://www.wowhead.com/quest=24997

Minor bug, when we kill Rot Hide Graverobber, it's marked as Rot Hide Mongrels and vice versa. So it is funny bug when you have 8/5 kills in questlog

---

Quest has a visual bug in which it doesn't appear to credit you the kills towards Rot Hide Graverobbers. You can still turn in the quest however so it doesn't inhibit further questing.

---

_merged_

**Comment by wtRCH** [comment]
Working ok.
