### ISSUE TITLE
[EN][Dungeon] Zul'farak

### ISSUE THREAD

**Issue by cybermatrix1** [Atlantiss/BugTracker#1880]
Just finishted Zul'Farak. We couldn't complete scripted event when u open up the cages.

**Comment by xolon** [comment]
wowhead link + describe what happend, maybe npcs got killed and thats the reason, try doing zul'farak again and tell us

**Comment by cybermatrix1** [comment]
No, this boss http://www.wowhead.com/npc=7274/sandfury-executioner must drop the key to unlock prisoniers. But it loots nothing.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2106
