### ISSUE TITLE
[PL][Spell] corrosive spit

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#1882]
http://wow.gamepedia.com/Corrosive_Spit
spell  się nie skatuje tylko ciągle przerywa nowym castem który automatycznie eliminuje efekt spella
nie dałem linka z wowhead bo napisało ze już nie ma tego spella na ich stronce
http://cata.openwow.com/spell=95466

**Comment by Varchord** [comment]
Cata.openwow.com
Ty masz dysleksję?

**Comment by arekczup** [comment]
nie po prostu jestem chory i robie błędy
