### ISSUE TITLE
[PL][Talent][Paladyn] Seals of the Pure

### ISSUE THREAD

**Issue by Dawid5221** [Atlantiss/BugTracker#1883]
W drzwku protection środkowy talent na samej górze powinnien zwiększyć nasz dmg od umiejętności Seal of Righteousness i jakieś tam innej

Ilość zwiększonego dmg nie widać ani na obrazu z umiejetnością jak i podczas bicia mobków itd...

Proszę o szybką interwencję!
*********************************************

Jeśli dalej zgłoszenie jest złe to niech ktoś inny się męczy z pisaniem tego.

https://github.com/Atlantiss/BugTracker/issues/1874

**Comment by Jenovas** [comment]
Kolega w poprzednim zgłoszeniu zrobił SSy na których widać że zwiększa DMG z Seal of Righteousness. Zamykam.

**Comment by Jenovas** [comment]
Talent 0/2:
http://i.imgur.com/V1MHTX5.png
Talent 1/2:
http://i.imgur.com/c0lDHja.png
Talent 2/2:
http://i.imgur.com/OSCREBw.png
