### ISSUE TITLE
[PL][Arena][Core][High priority] Friendly opponents

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#1884]
http://wstaw.org/m/2015/01/29/WoWScrnShot_012915_190643.jpg
http://wstaw.org/m/2015/01/29/WoWScrnShot_012915_190703.jpg
http://i.imgur.com/wHoL6ua.jpg

Przeciwnicy na arenie byli ... friendly. Nie mogliśmy ich bić, ani oni nas.
Dodatkowo na friend liscie pokazywalo nas, ze jestesmy w strefie "unknown".
Aha i dodam, że poprzednią arenę grając na tych samych przeciwników było ok, więc to nie kwestia frakcji ale losowo.

**Comment by Asavel** [comment]
Potwierdzam ;D

**Comment by mrkariox** [comment]
Ale czym to jest spowodowane? Za kazdym razem to wystepuje? Gdzie szukac bledu? Jakies konkrety ;D

**Comment by Arcadia713** [comment]
Właśnie nie wiadomo czym. Całkowicie losowo - czasem ten sam team był friendly, innym razem nie. Jedynie wchodząc na arenę i mając partnera na liście friend widać, że jest w lokacji "Unknown" wtedy już wiadomo, że przeciwnicy będą friendly.

**Comment by Varchord** [comment]
Żaden Bug. To ma pomóc w z integracji ludzi na serwerze

**Comment by Asavel** [comment]
Wystepuje prawdopodobnie bo zagraniu 2 areny na ten sam team z tej samej frakcji
