### ISSUE TITLE
[EN][NPC] Lesser Scorching Totem

### ISSUE THREAD

**Issue by gashole** [Atlantiss/BugTracker#1886]
Lesser Scorching Totem (ID: 18795) in Bloodmyst Isle should only spawn when a Bristlelimb Shaman (ID: 17320) attacks. They currently spawn and move around like normal NPCs.

[![Atlantiss - Lesser Scorching Totem](http://img.youtube.com/vi/sF9QwzSAEHQ/0.jpg)](http://www.youtube.com/watch?v=sF9QwzSAEHQ)

**Comment by Bildo** [comment]
fixed in rev 4294
