### ISSUE TITLE
[EN][NPC] Nazzivus Felsworn

### ISSUE THREAD

**Issue by gashole** [Atlantiss/BugTracker#1888]
Nazzivus Felsworn (ID: 17339) in Bloodmyst Isle continues its non-combat movement behavior when in combat, stopping only to cast a spell.

[![Atlantiss - Nazzivus Felsworn](http://img.youtube.com/vi/33s6yYUs4e8/0.jpg)](http://www.youtube.com/watch?v=33s6yYUs4e8)

**Comment by Bildo** [comment]
fixed in rev 4294
