### ISSUE TITLE
[EN][Quests][Nagrand]HELP!(ID 9923)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1891]
NPC [Corki](http://www.wowhead.com/npc=18369) for this quest should be in a cage in [Burning Blade Ruins](http://wow.gamepedia.com/Burning_Blade_Ruins) but is not(it is on an other cage which is supposed to be after doing two rescues of the same one and because it is on an other cage the quest text and item location is wrong because it need an other key)

Wowhead link: [HELP!](http://www.wowhead.com/quest=9923/help)

![wowscrnshot_012915_223518](https://cloud.githubusercontent.com/assets/10282971/5969182/2734cbc6-a829-11e4-81e7-f70ea20e3f2a.jpg)

After this quest Corki should be at [Northwind Cleft](http://wow.gamepedia.com/Northwind_Cleft) for quest [Corki's Gone Missing Again!](http://www.wowhead.com/quest=9924/corkis-gone-missing-again) and after this quest corki should be at [Warmaul Hill](http://wow.gamepedia.com/Warmaul_Hill) for quest [Corki's Ransom](http://www.wowhead.com/quest=9954/corkis-ransom) and [Cho'war the Pillager](http://www.wowhead.com/quest=9955/chowar-the-pillager)

each time he should be at different cages depend of the keys it need for each quest:
[HELP!](http://www.wowhead.com/quest=9923/help) need [Boulderfist Key](http://www.wowhead.com/item=25490/boulderfist-key) 
[Corki's Gone Missing Again!](http://www.wowhead.com/quest=9924/corkis-gone-missing-again) need [Northwind Cleft Key](http://www.wowhead.com/item=25509/northwind-cleft-key)
[Cho'war the Pillager](http://www.wowhead.com/quest=9955/chowar-the-pillager) need [Cho'war's Key](http://www.wowhead.com/item=25648/chowars-key)

EDIT:You can complete it by freeing the one which you normally should do.

Update 16/03/15 : i am sorry.I did not read this one.Might be related: #493

**Comment by Quban** [comment]
fix soon

**Comment by Dean1989** [comment]
still bugged
