### ISSUE TITLE
[EN][Dungeon] Gnomeregan Instance rare entrance portal.

### ISSUE THREAD

**Issue by PatriotasLT** [Atlantiss/BugTracker#1894]
When you going from instance rare entrance portal geting stuck under textures and daying.
http://wow.gamepedia.com/File:WorldMap-Gnomeregan3.jpg

**Comment by Wolffenstein** [comment]
I didn't understand a single thing.

**Comment by Canderous** [comment]
I think what he meant to say is if you enter the dungeon through the second portal (not the one the DF puts you in, rather the one shown on the map linked), you fall through the ground and die. I did not test it though.

**Comment by PatriotasLT** [comment]
Canderous yes! exactly, what I wanted to say.

**Comment by TranceAccount** [comment]
Haven't had this problem. Only when leaving the dungeon through the Workshop Portal. #8053
