### ISSUE TITLE
[Quest][Ashenvale] Rain of Destruction

### ISSUE THREAD

**Issue by Zentharim** [Atlantiss/BugTracker#1896]
After being transformed in an imp the mine (and Splintertree Post) won't phase, thus not generating hittable npc near the village. Moreover the Accursed Ore needs you to be in Splintertree Tower to be used, but the game won't recognise the position. 
http://wow.gamepedia.com/Quest:Rain_of_Destruction

**Comment by Danelar** [comment]
[PL] Na dodatek znikają wszyscy NPC, a górnicy z kopalni ( którzy  też znikają  :| ) nie okazują strachu ani też kopalnia się nie wali jak w poniższym filmiku:

Link: https://www.youtube.com/watch?v=0RgvDuMn9bc

**Comment by Asrael87** [comment]
I have a problem with disguse, i can't turn to normal from Imp Form to Normal hunter. Can you help me?
