### ISSUE TITLE
[PL][Quest][Hellfire Peninsula]Forge Camp: Mageddon

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#1897]
http://www.wowhead.com/quest=10390/forge-camp-mageddon

Z http://www.wowhead.com/npc=20798/razorsaw nie wypada quest item http://www.wowhead.com/item=29586/head-of-forgefiend-razorsaw. Zabijałem go już kilka razy i nic.

**Comment by Drutmaster** [comment]
Wypada. Nie mniej jej drop jest bardzo niski, a powinien być 100%

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
Fixed by Navedonar:
