### ISSUE TITLE
[EN][Quest][Twilight Highlands] The Crucible of Carnage: The Deadly Dragonmaw

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#1898]
http://www.wowhead.com/quest=27864/the-crucible-of-carnage-the-deadly-dragonmaw
Only problem with this quest is that it visually glitches whoever is caught by the boss while the boss dies. I'm posting 2 pictures of 2 different toons it happened to. The glitch is quite persistent since dying, relogging, having server restart or anything of the sort doesn't remove it. A friend of mine had it before and the only way it got removed was with the help of a GM through an in game ticket.
http://imgur.com/ZacePhm,KWs2sjJ#0
http://imgur.com/ZacePhm,KWs2sjJ#1
That's the position the characters are stuck in (made an in game ticket about them few min ago).

**Comment by Arisiel** [comment]
I have the same problem, please help

**Comment by Navedonar** [comment]
.
