### ISSUE TITLE
[EN][HUNTER][Spell] Camouflage

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#19]
http://www.wowhead.com/spell=51753/camouflage
1.Rapid Fire, Trinekts-on-use, using Hunter Mark on any target, starting cast  Aimed S, Steady S, Cobra S, switiching aspects. All of those actions remove CAMO from Hunter, which doesn't work as intented.
https://www.youtube.com/watch?v=uxYgZMaR9zU In this movie at 4;50 Hunter is popping up rapid fire, trinket on-use and starting to cast Aimed Shot. Camouflage is not removed from him untill he finishes casting.
2. Rogues are unable to sap, cheap shot or just "open" on hunter that is already in Camouflage.
I am not sure what spells rogues should be able to use on camo'ed hunter. I was told by some rogue to report it.

**Comment by Wolffenstein** [comment]
Only spells with maximum range of 5yd or less (like Cheap Shot) should break Camouflage. Sap and Blind have more than 5yd.

**Comment by Wolffenstein** [comment]
Fixed in rev 4321.
