### ISSUE TITLE
[En] [Items] Not working weapon passives

### ISSUE THREAD

**Issue by Urith** [Atlantiss/BugTracker#1900]
Hello there. 

My weapon passive doesn't work. 

[Stinging Viper]
Chance on hit: poison target for 7 nature dmg each 3 sec for 15sec.

[Darkwater Talwar]
Chance on hit: sends shadowy bolt on enemy causing 26 shadow damage.

[Searing Blade]
Chance on hit: Hurls a fiery ball that causes 74 fire damage and additional 9 damage over 6 seconds.

Never ever proxxed, any of those. 
Checked it on Skada, no damage proxx, no animation proxx, no effect on enemy. Nothing. 
Those were effects that I really wanted to test, to use, made me give up stronger weapon for something that did not work at all.

Hope to hear from you soon and that fix will be in no time!

(because I probably won't be able to use it anymore anyway until fix...)

Yours faithfully,
Urith

**Comment by Varchord** [comment]
Links
Besides. You will outlevel these weapons before fix

**Comment by Wolffenstein** [comment]
One ticket = one issue. Each of these items need to be scripted separatly, it's not a core problem.
