### ISSUE TITLE
[EN][NPC]bird with hammer

### ISSUE THREAD

**Issue by cybermatrix1** [Atlantiss/BugTracker#1904]
There is swampstrider who has a hammer in her right wing. - Swamp of sorrows

**Comment by Varchord** [comment]
links/screens

**Comment by cybermatrix1** [comment]
closing means?

**Comment by Bildo** [comment]
that is soemthing worng with issue

**Comment by cybermatrix1** [comment]
what's wrong?

**Comment by Tj20** [comment]
Like Varchord already said: there's no wowhead/openwow link (see [How to use](https://github.com/Atlantiss/BugTracker)), and a screenshot might also not bad here.

http://www.wowhead.com/npc=45825/swampstrider

![picture](http://i.imgur.com/TxEScjm.jpg)

All Swampstriders have said hammer. Unfortunately it disappears if you tame it as a hunter pet. 
:( 
:D

**Comment by Bildo** [comment]
Fixed by Navedonar:
