### ISSUE TITLE
[PL][NPC]"Wuu <Pig Handler>"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#1909]
Czy on nie powinien być Handlarzem? - Nie można wejść w ŻADNĄ interakcje :/ 

Link: http://www.wowhead.com/npc=40498/wuu#sounds

**Comment by Wolffenstein** [comment]
A jest na wowheadzie, że ma coś sprzedawać? Zamykam.

**Comment by Danelar** [comment]
Nie mogę znaleźć, ale coś jest nie tak - na pewno :/
