### ISSUE TITLE
[PL][Quest][In with a bang

### ISSUE THREAD

**Issue by cybermatrix1** [Atlantiss/BugTracker#1910]
Quest in Swamp of sorrows. It lauches you with the cannon, but a mob does too much dmg.

**Comment by Urith** [comment]
Witam serdecznie. 

Mam pytanie, czy Ty zdurniałeś totalnie? Napisałeś [PL] na początku swojego problemu co znaczy, że cała sprawa ma być rozważana po polsku. A Ty dajesz opis po angielsku. Świetne xD

Poza tym cały opis "Strzela Cię działo, a mob za dużo bije". Brzmi to jak piąte przez dziesiąte.

Jeżeli masz tak opisywać problemy, to proszę, lepiej ich nie opisuj, tylko poproś kolegę, albo coś...

Pozdrawiam,
Urith.
