### ISSUE TITLE
[EN][Dungeon][RHC] ID isn't resetting

### ISSUE THREAD

**Issue by Tottres** [Atlantiss/BugTracker#1911]
There is something wrong with resetting daily ID for random cataclysm heroic. Don't know why, but this issue is 'active' only on my second account. 
Yesterday i was doing rhcs with my two characters on aforesaid second account and both didn't receive reset (both with ID on Vortex Pinnacle and Lost City, one with Grim Batol). But on my first account everything is allright and there is no overdued IDs.
I've also talked with some other people and they also have the same issue.

**Comment by int24rain** [comment]
UPDATE:

After being in Dungeon using Dungeon Finder tool and server crashes (without killing any bosses) some of the players or all party gets locked to this dungeon and cannot requeque again.

**Comment by serianx** [comment]
same issue here

**Comment by Wolffenstein** [comment]
Fixed in rev 4365.

**Comment by Spymage** [comment]
According to my knowledge, bug has not been eliminated.
