### ISSUE TITLE
[PL][Vehicle][Tol Barad] Abandoned Siege Engine

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1913]
http://www.wowhead.com/npc=45344/abandoned-siege-engine#comments

Ranga po zdobyciu honorowego zabójstwa nie zostaje przyznana. Przed Pre-patchem działało tylko dla Kogoś kto zabił (Healer nie miał możliwośći zdobycia Rangi- jeśli się nie mylę).

Bez rangi nie możemy kontrolować w/w pojazdów co utrudnia rozgrywkę na Tol Barad Battle.

**Comment by Varchord** [comment]
Arcadia to zgłaszał juz

**Comment by MasterK15** [comment]
Warto przyponieć. bug "chyba" łatwy do naprawienia, a wiele by pomógł

**Comment by Arcadia713** [comment]
Zgłaszał miesiąc temu - https://github.com/Atlantiss/BugTracker/issues/1120 Dubel

**Comment by Wolffenstein** [comment]
Fixed in rev 4304.

**Comment by bgb** [comment]
Wciąż coś nie tak jest z tymi pojazdami. Bardzo często mimo posiadania buffa wciąż nie można nimi kierować. Można tylko wsiąść do środka i pokręcić się pojazdem w miejscu:/ Właściwie mam tak na każdym tol barad... I nie tylko ja, bo zaobserwowałem, że podobny problem mają inni gracze. Żeby było ciekawiej to jeśli ktoś inny ma ten problem i wysiądzie - wtedy inny gracz będzie już mógł jechać pojazdem bez problemu.
