### ISSUE TITLE
[PL][Raid][Classic]Ruins of Ahn'Qiraj

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1914]
Ruins of Ahn'Qiraj  http://www.wowhead.com/zone=3429/ruins-of-ahnqiraj Od tego ID są puste, nie wiem czy tylko dla mnie, ale tydzień temu (na poprzednim ID) Trash i bossy jeszcze były.

http://www.wrzuc.to/c2e268b789cf6d74

Liczba w miejscu gdzie powinna być ilość graczy w raidzie (flaga przy minimapie) wynosi 0 - nie wiem o co chodzi, ID czyste

**Comment by Bildo** [comment]
wchodzisz pewnie na hc a nie na norm

**Comment by MasterK15** [comment]
Testowane na norm i HC ...

**Comment by MasterK15** [comment]
PS: na Screenie wyraźnie widać że Normal.

**Comment by MasterK15** [comment]
http://pl.tinypic.com/r/2i778m8/8
