### ISSUE TITLE
[PL][Raid][Classic][Again]Ruins of Ahn'Qiraj

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#1915]
Ruins of Ahn'Qiraj http://www.wowhead.com/zone=3429/ruins-of-ahnqiraj Od tego ID są puste, nie wiem czy tylko dla mnie, ale tydzień temu (na poprzednim ID) Trash i bossy jeszcze były.

http://pl.tinypic.com/r/2i778m8/8   NOWY LINK DO SS, wyraźnie widać że NORMAL 

Testowałem na HC i Normalu

Liczba w miejscu gdzie powinna być ilość graczy w raidzie (flaga przy minimapie) wynosi 0 - nie wiem o co chodzi, ID czyste

**Comment by Bildo** [comment]
http://imgur.com/Da9aMqW my to chyba gramy na innym serwerze :D  jestem stu proconetowo pewny, ze jestes na heroic
