### ISSUE TITLE
[PL][Core][Dungeon] - The Shattered Halls

### ISSUE THREAD

**Issue by romigrabarz** [Atlantiss/BugTracker#1917]
Rev. 4291
Podczas robienia instancji występuje crash aplikacji z błędem critical error:
Objecy AnimKitSegmentInst(.?AUAnimKitSegmentInst@@)
Request 9732 bytes of memory

Usunięcie cache nie pomaga, Ramu mi nie brakuje na pewno.
Crash występuje zawsze w tym samym miejscu w instancji (tryb Heroic), Jest to miejsce zaraz za pierwszym bossem, gdy dalej zbijamy trashe stojące w grupach po 4.

**Comment by Bildo** [comment]
duplikat
