### ISSUE TITLE
[PL][Quest][Ghostlands] Oooh, Shinies!

### ISSUE THREAD

**Issue by romigrabarz** [Atlantiss/BugTracker#1918]
Rev. 4291

brak NPC http://www.wowhead.com/npc=23559/budd do oddania questa.

**Comment by Bildo** [comment]
a do czego ten npc jest ? z tego co widze nie powinien zadnych questow miec

**Comment by Wolffenstein** [comment]
http://www.wowhead.com/quest=11130/oooh-shinies - the quest should be removed.

**Comment by romigrabarz** [comment]
To usuńcie też ten quest do wzięcia od NPC http://www.wowhead.com/npc=19227/griftah, od którego można wziąć ten quest w Shatt.

**Comment by Bildo** [comment]
fixed in rev 4294
