### ISSUE TITLE
[Quest][Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by Ash1993** [Atlantiss/BugTracker#1921]
http://www.wowhead.com/quest=13580/soothing-the-elements

You can´t complete the quest because the boss doesn't appear. At a certain moment, the elementals stop appearing.

**Comment by Bildo** [comment]
duplicate

**Comment by Ash1993** [comment]
Ah sorry, I look for it in the bugtracker but i didn't find it. That's my fault
