### ISSUE TITLE
[EN][Battlegrounds] Changing talents

### ISSUE THREAD

**Issue by jasiol2** [Atlantiss/BugTracker#1922]
Players should be allowed to change their spec in the preparation time on any Battleground, currently they are not. Same goes for arenas, haven't checked it though. 
http://www.wowwiki.com/Dual_Talent_Specialization

**Comment by Arcadia713** [comment]
Confirmed. Same with glyphs - you should be allowed to change spec and glyphs in preparation to battle on BG/Arena.

**Comment by coocoo89** [comment]
Stll can't change spec during preparation on battlegrounds. REopen pl0x

**Comment by BeVeR86** [comment]
This issue was closed but still persists... can it please be reopened? it would be very nice for this feature to work!

**Comment by lamaATS** [comment]
Fixed in rev. 5235
