### ISSUE TITLE
[Eng][Quest][Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by Andarien** [Atlantiss/BugTracker#1924]
Quest is not working properly. The player should place a totem at special place and then defend it from waves of fire elementals. But when the totem is placed, only one elemental appears. I kill him and wait. After some time the totem is gone. I can place it again, but with same result. The Ritual is not finished.

http://www.wowhead.com/quest=13580/soothing-the-elements
Here is the full description. Without completing this quest, the player can't finish big quest chain.

**Comment by Aival94** [comment]
Already reported: #1521

**Comment by Andarien** [comment]
Strange, I used search and didn't find. Then sorry, my mistake.
