### ISSUE TITLE
[EN][Dungeon] Loot of Final boss in Culling of Stratholme (Normal and Heroic Mode)

### ISSUE THREAD

**Issue by grayfox764** [Atlantiss/BugTracker#1925]
Im not totally sure if this has been reported in bugtracker (looked for it and didn't find any topic), in this dungeon after you kill Mal'Ganis (http://www.wowhead.com/npc=26533/malganis) a cinematic with him talking to arthas happens, and then you sholud be able to loot the Dark Runed Chest (http://www.wowhead.com/object=193597/dark-runed-chest), which contain the loot of the mentioned boss, but after you kill him, chest is there, but you can't interact with it, so in the end, there's no loot working for that final boss. just pointing it out because i would really love to have items from that boss, so, will just wait for an answer here, thanks for the amazing job and progress.

**Comment by xolon** [comment]
confirmed

**Comment by Aival94** [comment]
We try to do this but Arthas start run all the way without stoping to kill npcs and becasue we need to kill them to continue arthas died or just vanish making it impossible for event to continue and kill last boss.(normal one)

How it should work: https://www.youtube.com/watch?v=qjdPPElxNCI#t=1253

**Comment by Tj20** [comment]
related: #2551
(This is the earlier topic, but both problems are also mentioned over there, so I wanted to link it)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2551 duplicate (in pl tho)
