### ISSUE TITLE
[EN] [QUEST] [K3] Know no fear

### ISSUE THREAD

**Issue by Startbar** [Atlantiss/BugTracker#1928]
The snowblind devotee should spawn in the cave with the Garm watchers. They are spawning outside and appear to be phasing as their health resets when attacked.

http://www.wowhead.com/quest=12822/know-no-fear

**Comment by Enay** [comment]
Already reported it, but I guess you couldn't have known, because it wasn't in the title.

Anyway, yeah, there's an issue here, and that whole cave has messed up phasing.

https://github.com/Atlantiss/BugTracker/issues/555
