### ISSUE TITLE
[EN] [Deepholm] Alliance Gunship

### ISSUE THREAD

**Issue by antilooppi** [Atlantiss/BugTracker#1930]
Alliance Gunship in Deepholm is lagging. I was killing Twilight Saboteurs and suddenly I drop to top of the deepholm and you cant go there with wisp. This happened 3 times in a row.  
![wtf](https://cloud.githubusercontent.com/assets/10763543/5987519/779212fe-a937-11e4-8fed-ae9aef089c93.JPG)

**Comment by Bildo** [comment]
duplicate
