### ISSUE TITLE
[EN]Dungeon] Locked dungeons for 2 days or more.

### ISSUE THREAD

**Issue by int24rain** [Atlantiss/BugTracker#1931]
Hello there.

For some reason from few days when I do a Random Heroic Dungeon it has locked for 2 days not for 1.From 3 days I can do only 2,3 dungeons per day cause the rest are locked.For example I did Stonecore yesterday morning 30.01.2014 and its locked till 01.02.2014.The Deadmines I did in 29.01.2014 and server crashed and from 29 I cannot play it 2 days are passed and its always written on the calendar that it will unlock on the next day but it doesnt.

http://i.imgur.com/y68wD4T.jpg
http://i.imgur.com/WkU592Q.jpg

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1911

**Comment by serianx** [comment]
this is not fixed yet, same issue here
