### ISSUE TITLE
[PL][Wotlk - instance][Gundrak] Trash and bosses fall under textures

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1933]
http://www.wowhead.com/zone=4416/gundrak

Wszystkie trashe i bossy w Gundrak spadaja pod tekstury, przez co nie mozna zrobic insty.

Sprawdzane w wersji **HC**

**Comment by mrkariox** [comment]
Już nie spadaja ze zamkniete zgloszenie?

**Comment by Bildo** [comment]
mi w ogole nie spadaly i wszystkim innym osobom co robily tez nie
