### ISSUE TITLE
[En][Item

### ISSUE THREAD

**Issue by Urith** [Atlantiss/BugTracker#1937]
![wowscrnshot_013115_123707](https://cloud.githubusercontent.com/assets/10770941/5987908/091fe2e2-a946-11e4-975c-1e182b20c46a.jpg)

Passive of item above doesn't proxx at all and doesn't work.

**Comment by Urith** [comment]
I it fixxed already that it' closed? :-D

**Comment by Bildo** [comment]
read bugtracer rules
