### ISSUE TITLE
[En][Item] Searing Blade

### ISSUE THREAD

**Issue by Urith** [Atlantiss/BugTracker#1938]
![wowscrnshot_013115_124013](https://cloud.githubusercontent.com/assets/10770941/5987917/7b768378-a946-11e4-93f4-1a09c0ba3d78.jpg)

Passive of item with screenshot above doesn't work.

**Comment by Arcadia713** [comment]
wowhead.com link to item or will be closed again i assume.

**Comment by Bildo** [comment]
bugtracker rules
