### ISSUE TITLE
[EN][NPC][Mount Hyjal] Provisioner Whitecloud

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#1940]
http://www.wowhead.com/npc=50314/provisioner-whitecloud
My problem with this NPC is that I can only see the first page of what he sells, there's no arrow to switch to second, no way to see all the items. He should have 14 items as the wowhead link says but I can only see 10 of them, the ones on the first page.
Had a friend check it, I checked it on several of my other toons, we can see everything. Only one bugged is my druid, there's no option to flip the page and the items are not in the same order either (the Arcanum should be on 2nd page, I can see it on 1st).
I don't need anything of the items that are missing just figured it should be reported.

**Comment by Bildo** [comment]
You can see only items that you can wear or are bind on equipped
