### ISSUE TITLE
[EN] [Dungeon] Black Rock Dephs

### ISSUE THREAD

**Issue by cybermatrix1** [Atlantiss/BugTracker#1944]
We encountered lots of mobs fighting each other. Tank rushed im, and we wiped. The healer left. Here is screenshot of what remained: http://i.cubeupload.com/U3ApqH.jpg . The npc's then start talking with themselfs.

**Comment by Tj20** [comment]
That isn't BRD, but Upper Blackrock Spire, see [#1585](https://github.com/Atlantiss/BugTracker/issues/1585).
