### ISSUE TITLE
[PL][Quest][Icecrown] Generosity Abounds

### ISSUE THREAD

**Issue by szaruwa** [Atlantiss/BugTracker#1945]
http://www.wowhead.com/quest=13146/generosity-abounds
Po przywiązaniu bomby do Lithe Stalkera i doprowadzeniu jej do Lumbering Atrocity'ego nie następuje żadna reakcja, a powinien wypowiedzieć jedną z kilku kwestii, po czym złapać bombę i wybuchnąć odpychając na około 20 yardów (bez zadawania dmg).

Dodam, że naprawienie tego q umożliwiłoby odblokowanie chaina, który zapewniłby zrobienie achievementa [Icecrown: The Final Goal] http://www.wowhead.com/achievement=40/icecrown-the-final-goal

**Comment by Haffyd** [comment]
Potwierdzam :)

**Comment by Veruca1320** [comment]
Potwierdzam! Wciąż nie działa

**Comment by gacek1989** [comment]
Bump !!!

**Comment by LaveGit** [comment]
Bump :3

**Comment by Drutmaster** [comment]
Annnnd bump!

**Comment by Bildo** [comment]
fixed in rev 4662

**Comment by Pocketerino** [comment]
Currently not working.
