### ISSUE TITLE
[EN][Instance-TBC] Graveyard Location of the Tempest Keep Instances

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#1948]
Players dying in one of the Tempest Keep instances ([Mechanar](http://www.wowhead.com/zone=3849/the-mechanar), [Botanica](http://www.wowhead.com/zone=3847/the-botanica), [Arcatraz](http://www.wowhead.com/zone=3848/the-arcatraz), [TK: The Eye](http://www.wowhead.com/zone=3845/the-eye)) revive at the wrong graveyard (near the Stormspire).

![pic](http://i.imgur.com/anROmAo.jpg)

It's correct that they don't respawn as ghosts, but alive... only the location is incorrect.

**Comment by eryczek1615** [comment]
bump

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12281-1948instance-tbc-graveyard-location-of-the-tempest-keep-instances/
