### ISSUE TITLE
[EN][Quest][Borean Tundra] Not Without a Fight

### ISSUE THREAD

**Issue by BlessedByTheSin** [Atlantiss/BugTracker#1956]
http://www.wowhead.com/quest=11949/not-without-a-fight

Theres a group of Kvaldir Raiders, they'r fighting Kaskala Defenders.
After you kill mob/mobs you got2 reboot system. totally freezing Computer.

P.S
Only mobs at Coordinates: 67/48 are buged!

**Comment by razguz** [comment]
I got the same problem.

**Comment by Aruzam** [comment]
Can confirm as well. Was doing the quest with a friend and the moment we both killed the last mob to complete the quest both our PCs froze and we had to reboot completely.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1791
