### ISSUE TITLE
[EN][Quest][Northern Barrens] Into the Raptor's Den

### ISSUE THREAD

**Issue by petersaints** [Atlantiss/BugTracker#1957]
This quest is not completable. There are only two nests. There is no third nest as required by the quest.
Wowhead: http://www.wowhead.com/quest=905/into-the-raptors-den

**Comment by xolon** [comment]
The third nest is above on the hill

**Comment by petersaints** [comment]
I have already found that one.

**Comment by petersaints** [comment]
Why have you closed the issue Wolfenstein? What I meant with my previous comment was that I had found the nest above on the hill, yet there is still one missing that is nowhere to be found. And I checked YouTube videos to see where "glowing" nests where, but after the first two there are no others around that can be activated.

**Comment by Greatleader** [comment]
This is still bugged

**Comment by Ocelot92** [comment]
Quest is bugged. Placing the feathers doesn't trigger always the objective.
