### ISSUE TITLE
[EN][Low Priority][NPC Drops] Azshara

### ISSUE THREAD

**Issue by idontknow12** [Atlantiss/BugTracker#1958]
Revision 4297

Naga in Azshara are level 17-20, yet are capable of dropping level 38-43 loot.

Related to https://github.com/Atlantiss/BugTracker/issues/547

**Comment by idontknow12** [comment]
These are the links from wowhead. They drop the listed high level food but also high level equipment which is not listed on those drop tables. The tables only list a level 44 axe from the myrmidon.

http://www.wowhead.com/npc=36989/spitelash-invader
http://www.wowhead.com/npc=6196/spitelash-myrmidon
http://www.wowhead.com/npc=35833/spitelash-priestess
http://www.wowhead.com/npc=35832/spitelash-seacaller
http://www.wowhead.com/npc=6194/spitelash-serpent-guard
http://www.wowhead.com/npc=6195/spitelash-siren
http://www.wowhead.com/npc=35831/spitelash-stormfury
http://www.wowhead.com/npc=6190/spitelash-warrior

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1616

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11048-1958-loot-tables/
