### ISSUE TITLE
[PL][BugTracker] Czy Was popierdoliło? :-)

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#1959]
Witam serdecznie. 

Mam pytanie, czy Was popierdoliło? 

Nie działa wewnątrz gry i muszę jak ten idiota wchodzić tutaj aby zgłaszać bugi, co jest wielkim utrudnieniem. Nawet po załączeniu screenshota, o którego prosił ktoś, tematy zamknięte, ponieważ nie ma linku do WoWheada i mam od nowa otwierać, ponieważ nie potrafiliście w jednym temacie napisać "proszę link do WoW Head'u", tylko wszystkie po kolei zamykacie, jak ostatnie chamy i z łaską podchodzicie do tego? 

Ja mam zgłosić tutaj buga, czy od razu najlepiej wysłać Wam skrypt, który możecie wrzucić sobie do gry na gotowca? Hm? 

Napiszę więc tak - wszystkie itemy z pasywami na low level nie działają i sprawdźcie wszystkie, ponieważ cholera jasna nie jest to przyjemne, jak się znajduje masę itemów i nie działają ich dotki czy inne zabawne pasywki. 

Tym samym takie traktowanie osób, które zgłaszają błędy dla Was, a Wy wymagacie od nich nie wiadomo czego - jest czystym skurwysyństwem, ponieważ ja tutaj nie jestem od lokalizowania przedmiotów w internecie, a najlepiej błędu w skrypcie, tylko żeby pomóc Wam zlokalizować błąd, a nie rozwiązać go w połowie za Was, tego typu traktowanie - gdy nie mogę dokończyć nawet otwartego ticketa - jest debilne, ponieważ czytałem tematy tutaj kilka razy dziennie i po prostu wszystko bym ulepszył, ale cóż - lepiej pozamykać, najlepiej bez wyjaśnienia żadnego, ponieważ tak i chuj? 

Pozdrawiam.

**Comment by Asavel** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md polecam przeczytać a pózniej miec pretensje.

**Comment by Bildo** [comment]
Szkoda nam czasu aby się użerać, ze wszystkimi osobami którym trudno jest poświecić minutę na przeczytanie zasad bugtrackera. Waszym zadaniem jest zgłaszanie bugów a naszym naprawianie.

**Comment by Dx51** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md jak rozumiem, nie umiesz czytać.

**Comment by Urith** [comment]
No comment.

**Comment by Giq** [comment]
Spoko, nara.
