### ISSUE TITLE
[EN][dungeon-cata] ID-locks

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#1960]
I just noticed today when i logged i had an ID for hoo and ZG (i did hoo yesterday and ZG 2 days ago). i don't really know why they are there since it's the first time i log today so it must be the ID is there already for few days, reminding it should be only until the day after. Please fix this asap cause now i can't do several dungeons just because i have an ID for something i didn't even do. So please fix it so the ID's just stay until the morning after 5am.

**Comment by arekczup** [comment]
me to

**Comment by Aruzam** [comment]
I have the same problem but with Shadowfang Keep. Lock doesn't want to reset, did it yesterday around noon, it didn't reset today at 5am server time when all locks do usually.

**Comment by Malylolek** [comment]
ID on raid's dont reset too. My priest cry and cant do BWD

**Comment by Aruzam** [comment]
I have the same issue for raids as well on 3 of my characters, either BoT or BWD didn't reset the locks properly and I have them locked until next week on Wednesday. More people from my guild are experiencing the same issue.

**Comment by serianx** [comment]
same problem here, not just ZG, i get randomly locked into some heroics too, the locks last for 2-3 days. this bug plus the one that locks you in every dungeon using random heroic finder makes gearing up so hard.

**Comment by Tj20** [comment]
Might be related to #1911 (I'm not sure if both are describing the same problem or something slightly else)
