### ISSUE TITLE
[EN][NPC][Icecrown] Narasi Snowdawn

### ISSUE THREAD

**Issue by Nausica07** [Atlantiss/BugTracker#1962]
After getting achievement "A Silver Confidant", it should unlock new daily quests from Narasi Snowdawn.

A leg up: http://www.wowhead.com/quest=14074/a-leg-up
Rescue at Sea: http://www.wowhead.com/quest=14152/rescue-at-sea
Stop The Aggressors: http://www.wowhead.com/quest=14080/stop-the-aggressors
The Light's Mercy: http://www.wowhead.com/quest=14077/the-lights-mercy
You've Really Done It This Time, Kul: http://www.wowhead.com/quest=14096/youve-really-done-it-this-time-kul

**Comment by Illusionist87** [comment]
Bumping, since this is still not fixed.

**Comment by sottolichio** [comment]
Bumping, since this is still not fixed.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2239
