### ISSUE TITLE
[EN][NPC][Icecrown] Savinia Loresong

### ISSUE THREAD

**Issue by Nausica07** [Atlantiss/BugTracker#1963]
After getting achievement "A Silver Confidant", it should unlock new daily quests from Savinia Loresong.

Breakfast Of Champions: http://www.wowhead.com/quest=14076/breakfast-of-champions
Gormok Wants His Snobolds: http://www.wowhead.com/quest=14090/gormok-wants-his-snobolds
What Do You Feed a Yeti, Anyway? : http://www.wowhead.com/quest=14112/what-do-you-feed-a-yeti-anyway

**Comment by Illusionist87** [comment]
Bumping, since this is still not fixed.

**Comment by sottolichio** [comment]
Bumping, since this is still not fixed.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2239
