### ISSUE TITLE
[EN] [Quest] [Swamp of Sorrows] Jammal'an the Prophet

### ISSUE THREAD

**Issue by sanwyrth** [Atlantiss/BugTracker#1965]
Location: EK, Swamp of Sorrows.
NPC (quest giver) Lord Itharius
Quest name: Jammal'an the Prophet.
Issue: Jammal'an the Prophet does not drop the quest item required to complete the quest, (Head of Jammal'an), upon death.
Attempts tried: 3x
Faction: Horde

**Comment by Bildo** [comment]
Fixed by Navedonar:
