### ISSUE TITLE
[EN][Quest][The Shattered Halls] How to Save a Life

### ISSUE THREAD

**Issue by FrostCZE** [Atlantiss/BugTracker#1968]
I can not use http://www.wowhead.com/item=23735/grand-warlocks-amulet nearby brazier to get http://www.wowhead.com/item=23726/fel-ember
Quest: http://www.wowhead.com/quest=29649/how-to-save-a-life

**Comment by Illusionist87** [comment]
Still doesn't work...

**Comment by kzlatkov** [comment]
Confirm that the Q is still not working.

**Comment by Arnokie** [comment]
Quest **works** in _Normal_ Shattered Halls but does **not work** in _Heroic_ mode.

**Comment by DuGalle** [comment]
Does not work on Heroic mode still

**Comment by Navedonar** [comment]
![wowscrnshot_111816_201602](https://cloud.githubusercontent.com/assets/1525533/20443125/dc5c0e7a-adcb-11e6-963d-9fc29ca47139.jpg)

Quest works in heroic mode. Close please
