### ISSUE TITLE
[ENG][Quest[Badlands] The Bad Dogs

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#1971]
http://www.wowhead.com/quest=27890/the-bad-dogs

The NPC Amakkar (http://www.wowhead.com/npc=47011/amakkar) is not sitting where he should be. But since the question mark is visible on the mini map he might be below ground.

**Comment by Quban** [comment]
``DELETE from `creature_addon` WHERE guid in (SELECT guid FROM `creature` where id = 47011);``
``DELETE FROM `creature` WHERE id = 47011; ``

```INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `PhaseId`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `corpsedelay`, `specialData`) VALUES (GetCreatureGUID(), 47011, 0, 1, 1, 0, 0, 1, -6730.15, -2484.37, 274.411, 1.68115, 300, 0, 0, 1592, 1640, 0, 2, 0, 0, 0, 0);```

``SELECT @VAR := (SELECT guid FROM `creature` where id = 47011);``
```INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES (@VAR, 0, 0, 1, 0, 0, 0);```

**Comment by Bildo** [comment]
rev. 4353 by Quban
