### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Fuselight, Ho!

### ISSUE THREAD

**Issue by Rakeen70210** [Atlantiss/BugTracker#1974]
Everything about this http://www.wowhead.com/quest=27762/fuselight-ho#see-also quest works EXCEPT for the fact that the rocket moves insanely slow. It takes way too long to get from the plaguelands to badlands and is extremely frustrating. This is how fast and how the rocket is supposed to work: https://www.youtube.com/watch?v=YFjwUyzJ0u0

**Comment by cinas** [comment]
flying about half an hour, enough time to fap three times and eat a sandwich and you are not in the place at that time

**Comment by Corson** [comment]
Now travelling is super fast BUT the path is bugged (we fly through mountains)
