### ISSUE TITLE
[PL] [Spell] [Hunter] Mend Pet

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#1977]
http://cata.openwow.com/spell=136

Brak sprawdzania czy pet znajduje się w zasięgu spela i w linii z hunterem.

Pet nie dostaje efektu gdy nie jest w linni lub jest zbyt daleko. Mimo niespełnienia warunków spell jest jednak wycastowany i marnuje GCD.

**Comment by Jenovas** [comment]
English Version:
http://www.wowhead.com/spell=136/mend-pet

Casting Mend pet while pet is out of line of sight causes the spell to be casted and cause global cooldown but the effect doesn't go on the pet.

**Comment by Jenovas** [comment]
Fixed in rev 4473
