### ISSUE TITLE
[ENG][Quest][Badlands] Half-Ton Holdouts

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#1980]
http://www.wowhead.com/quest=27880/half-ton-holdouts

Contrary to the quest description "Dustbelcher Shaman" (http://www.wowhead.com/npc=2718/dustbelcher-shaman) are not counted towards the quest completion.

"Slay 12 Dustbelcher Combatants. You may kill Dustbelcher Maulers or Dustbelcher Shaman."

**Comment by Quban** [comment]
`UPDATE creature_template SET KillCredit1=2717 WHERE entry=2718;`

**Comment by Bildo** [comment]
rev. 4353 by Quban
