### ISSUE TITLE
[EN] [Instance] [Uldaman] - infinite mob summoning

### ISSUE THREAD

**Issue by Jinsen102** [Atlantiss/BugTracker#1981]
In the Uldaman instance, Hall of Crafters chamber, there is an Altar of The Keepers, stone used to summon a Stone Keeper elemental http://www.wowhead.com/npc=4857/stone-keeper and start the fight event.
It is possible to use the stone multiple times and summon that many Stone Keepers, making it infinite exp source. It doesn't stop even after defeating them or defeating last boss, it's totally infinite.

As I suppose (I couldn't find any source) it should be allowed to start the event only once.

![wowscrnshot_020115_213641](https://cloud.githubusercontent.com/assets/2950330/5993816/b6c2de74-aa5c-11e4-9c47-19792db48c2e.jpg)

**Comment by Wojmistrz** [comment]
well infinity summon mobs can be sometimes a cause of server crash i guess.
