### ISSUE TITLE
Potential cause of server crash

### ISSUE THREAD

**Issue by lolwtfqt** [Atlantiss/BugTracker#1995]
I have experienced quite a number of times where the server crashes when I try to filter the auction house listings via the string entry search in the left upper corner of the auction window. Just leaving this here so you have a hint and investigate if it is really a reason for server crashes.

**Comment by Spydoc** [comment]
For me it never sorts the items in the Auction House whenever I click on a column name from a long time, although it has never actually caused the server to crash.
