### ISSUE TITLE
[EN][RAID][TBC] Serpentshrine cavern

### ISSUE THREAD

**Issue by stewazy** [Atlantiss/BugTracker#1996]
Lady Vashj in ssc is not working properly when she is in second phase in the bubble, elementals come and i can't loot tainted core from them because they don't drop it, the green elemental desn't spawn :(.

**Comment by Varchord** [comment]
Links

**Comment by spell406** [comment]
Boss - Lady Vashj - http://www.wowhead.com/npc=21212/lady-vashj
Add - http://www.wowhead.com/npc=22009/tainted-elemental
Item required to deactivate shield - http://www.wowhead.com/item=31088/tainted-core
Bug - Tainted Core drops, but it is required only to deactivate one generator to remove vashj's shield.
Also Vashj drops 3 items and 5 tokens, shouldn't it be reversed (5 items 3 tokens)?
