### ISSUE TITLE
zbugowany pasek spelli peta

### ISSUE THREAD

**Issue by Kushimaru** [Atlantiss/BugTracker#2001]
kiedy z paska spelli peta (hunter) wyciagnie jakakowiek zdolnosc, to z miejsca w ktorym ten spell byl znikaja spelle kiedy sie przywoluje tego peta badz wchodzi do gry albo whodzi sie do lokacji ktora sie laduje (np do instancji lub zmienia sie kontynent)

**Comment by Kuszki** [comment]
nawiązuje do #1828

**Comment by Bildo** [comment]
zasady bt
