### ISSUE TITLE
[PL][Event][Love is in the Air] Heart-Shaped Box

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#2004]
Witam!

Event już dodany, instancja eventowa też jest, ale brak nagrody za nią, mimo spełnienia warunku (pierwsza instancja dnia). W ogóle nie wyskakuje informacja o zakończeniu instancji po ubiciu bossów, a co za tym idzie, gra uważa, że nie jest ona "ukończona" (pewnie wyjście z niej w takim stanie dałoby dezertera, gdyby nie był on wyłączony). Z góry dziękuję za pomoc!
Rev. 4301

Link do nagrody - http://www.wowhead.com/item=54537/heart-shaped-box
Link do eventu - http://www.wowhead.com/event=335/love-is-in-the-air
P.S loot z samych bossów jest już poprawny (tj. przedmioty są na lvl 85)

**Comment by Misiac** [comment]
Sprawdź na innej postaci.
Z tego co wiem jeśli zrobiłeś rhc to nie możesz dostać nagrody z eventu i na odwrót.

**Comment by jurek1** [comment]
ja wczoraj nie robilem rhc , a z eventu i tak nie dostalem boxa.. ; p

**Comment by Haffyd** [comment]
Robiłem za pomocą event findera i również nie otrzymałem boxa.
