### ISSUE TITLE
[EN][Quest][Mount Hyjal] Into the Maw!(ID 25623)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#2005]
Quest is not given by NPC [Ian Duran](http://www.wowhead.com/npc=39433/ian-duran)

Wowhead link: [Into the Maw!](http://www.wowhead.com/quest=25623/into-the-maw)

Prequisites are the same as the one exist in the server already.

**Comment by Wolffenstein** [comment]
I'm pretty sure you missed some pre-quest. I've seen alliance players doing quests in the quest ender's area, so they must have done this quest.

**Comment by Aival94** [comment]
there is one more quest the same as this one from an other NPC which exist here.It is this one:
[Into the Maw!](http://www.wowhead.com/quest=25618/into-the-maw) from NPC [Spirit of Goldrinn](http://www.wowhead.com/npc=39627)

In commnets on wowhead some say that these two are breadcumbs but some say that can be obtained both of them if you take the in specific order(first commnet of the quest).The reason why the one in the main post should exist is because NPC [Spirit of Goldrinn](http://www.wowhead.com/npc=39627) after some time despawn(or after one crash for example)and players cannot take quest as not have again item to summon it.

**Comment by Wolffenstein** [comment]
Oh ok, I understand now.

**Comment by tomatosz** [comment]
Fixed in rev. 5759
