### ISSUE TITLE
[EN][Quest][Hellfire Ramparts]Weaken the Ramparts

### ISSUE THREAD

**Issue by grzott** [Atlantiss/BugTracker#2006]
According to : http://www.wowhead.com/quest=9575/weaken-the-ramparts
this quest cannot be obtained. Its have his equivalent in dungeon from this npc: http://www.wowhead.com/npc=54603/advance-scout-chadwick

**Comment by Danelar** [comment]
True - Has been divided into 3 Quests.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
