### ISSUE TITLE
[PL][Event][Love is in the Air] Swift Lovebird

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#2009]
Witam!

Otóż od 4.3 vendorzy eventowi (http://www.wowhead.com/npc=37674/lovely-merchant) powinni mieć na składzie mounta-strusia  (http://www.wowhead.com/item=72146/swift-lovebird) za 270 Love Token (http://www.wowhead.com/item=49927/love-token). U nas tego mounta u vendorów nie ma. I tutaj pojawia się pytanie/prośba. Czy mount zostanie dodany jeszcze podczas tego eventu, czy idąc zasadą contentu (teraz powinniśmy mieć content 4.1), będzie trzeba poczekać, aż serwer wejdzie z contentem na 4.3? Pytanie o tyle ważne, że jeśli okaże się, że takie rzeczy będą wprowadzane dopiero od 4.3, to będę miał świadomość, żeby nie zgłaszać wszelkich brakujących rzeczy z eventów, które zostały dodane powyżej 4.1, aż do momentu wejścia serwa na odpowiedni content. Z góry dziękuję za odpowiedź!

Rev. 4301

**Comment by drlinux92** [comment]
<a href="http://wow.gamepedia.com/Swift_Lovebird">  Patch 4.3.0 (2011-11-29): Added. </a>
As far as I know the server is not yet on the content 4.3 so it shouldn't implemented yet.

If the server is not on 4.3 content then <a href="http://atlantiss.eu/changelog#rev4302">Rev. 4302</a> you shouldn't implement item!
