### ISSUE TITLE
[EN][Quests in Outland]

### ISSUE THREAD

**Issue by cybermatrix1** [Atlantiss/BugTracker#2010]
I noticed in Outland quests the quest item drop are very rare. For ex if I need 12 wolf tails i have to kil 30 wolfs. I don't think this is normal.

**Comment by lanrutcon** [comment]
WoWHead Comment #1: http://www.wowhead.com/quest=10016/timber-worg-tails#comments:id=68647
WoWHead Comment #2: http://www.wowhead.com/item=25807/timber-worg-tail#comments:id=247234

Timber Worg Tail drop rate: http://www.wowhead.com/item=25807/timber-worg-tail#dropped-by
