### ISSUE TITLE
[PL][Event][Love is in the Air] Lovely Charm Collector's Kit

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#2013]
Witam!

Problem pojawia się pewnie tylko tym osobom co w zeszłym roku brali udział w evencie i się tego przedmiotu (www.wowhead.com/item=49661/lovely-charm-collectors-kit w zakładce "provided for" jest podane, które q dają ten item) pozbyli. Powinna być możliwość odzyskania tego przedmiotu, poprzez wzięcie któregoś z questów na prezent dla wodza stolicy (obojętnie której). U nas te questy nie są daily, a powinny być, co uniemożliwia odzyskanie Kita i farmienie bransoletek. Prosiłbym o naprawienie tego w wolnej chwili. Z góry dziękuję za pomoc!

Rev. 4301

**Comment by Pieczyyea** [comment]
Co nie zmienia faktu, że rzecz jest do naprawienia.

**Comment by Drutmaster** [comment]
Dlatego nie zamykam tematu

**Comment by Wolffenstein** [comment]
Fixed in rev 4304.
