### ISSUE TITLE
[EN][Quest][Badlands]Lifting the Veil

### ISSUE THREAD

**Issue by Shesgar** [Atlantiss/BugTracker#2015]
The quest "Lifting the Veil" (http://www.wowhead.com/quest=27770/lifting-the-veil) should trigger a cutscene to complete the quest. It doesn't, therefore, mission can't be completed.

**Comment by bgb** [comment]
Confirmed. Also here is video what is supposed to happen in this quest: 
https://www.youtube.com/watch?v=6JH_lf4Cs2Q#t=0m31s

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1632

**Comment by ffighter29** [comment]
Confirmed

**Comment by Kleanex** [comment]
Hello, the alliance quest does not, the bug was repaired side horde #6774, would it possible to adapt the script for the other side?
Thank you
