### ISSUE TITLE
[EN][Quest][Badlands] The Sentinel's game

### ISSUE THREAD

**Issue by Shesgar** [Atlantiss/BugTracker#2017]
The quest "The Sentinel's game" (http://www.wowhead.com/quest=27886/the-sentinels-game) is bugged. There is no beam coming out of the statue as it should.

**Comment by lourrific** [comment]
As of May 18, 2015 this quest is still broken.

This quest is the second part of a five part quest chain and as a direct result of it being bugged the following quests are also broken.

1. Ancient Protectors http://www.wowhead.com/quest=27793/ancient-protectors
2. The Titans' Trove http://www.wowhead.com/quest=27912/the-titans-trove
3. Return to Blam http://www.wowhead.com/quest=27794/return-to-blam

**Comment by zelekxmalinowy** [comment]
Still bugged.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6774
