### ISSUE TITLE
[PL/EN][Event][Love is in the Air][High priority] Love Rocket

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#2018]
Witam!
Przedmiot Love Rocket (http://www.wowhead.com/item=34258/love-rocket) powinien być sprzedawany w ilości 5 sztuk naraz za 5 Love Tokens. Jednak u nas jest jedna sztuka za 5 Love Tokens, co jest bardzo drogie.

Dowód:
http://www.wowhead.com/npc=37674/lovely-merchant

SS:
http://s1304.photobucket.com/user/dementor_111/media/WoWScrnShot_020315_191620_zps5aa0b11c.jpg.html

Hello!
Item Love Rocket (http://www.wowhead.com/item=34258/love-rocket) should be sold in the amount of 5 pieces at the time for 5 Love Tokens.

Wowhead:
http://www.wowhead.com/npc=37674/lovely-merchant

**Comment by Spydoc** [comment]
This issue persists with Handful of Rose Petals and Silver Shafted Arrow.

http://www.wowhead.com/item=22200/silver-shafted-arrow
http://www.wowhead.com/item=22218/handful-of-rose-petals#sold-by

**Comment by Haz3L** [comment]
It should be [High priority]

**Comment by Danelar** [comment]
[PL]Mam nadzieję, że będzie, bo drogie to ,a czasu na achievy mało...

**Comment by Pieczyyea** [comment]
Walentynki trwają do 16 lutego, więc fakt, niech kt0oś zauważy.

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
Fixed by Navedonar:
