### ISSUE TITLE
[EN][Mage][Spell] Combustion & Ignite

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#2020]
Combustion and Ignite should be calculated differently in 4.3.4 with some damage modifiers and probably scale dynamically with them.

Posting some formulas taken from EJ forums that didn't really change:
IgniteTickDamage = 0.2*AnyCriticalStrike
Combustion Tick damage = PyroDotPower/3+ LbDotPower/3+ IgniteTickDamage/2

To note1: There was another issue with ignite that didn't get absorbed damage from critical strikes into account and i am not sure if it has been fixed on the main by now.
To note2: Shouldn't double-dip modifiers in any way. Especially in calculation to ignite that lowered combustion damage too and existed on retail, but has been shortly hotfixed by blizzard.
To note3: You should be careful with Mage's mastery since it's possible you'll make it to double-dip with mastery. 
"Combustion damage from Ignite is no longer penalized by Resilience more than once, nor can it gain double benefit from Flashburn (mastery)." // patch notes
"EDIT: I just tested pyro, and again it double dips on mastery but has a low coefficient:" // EJ quote from early cata
"Combustion double dips mastery on LB/pyro, but not ignite." // EJ quote from early cata

What this change really brings?
You shouldn't be able to deal full damage to Shadow Priests through Dispersion, Rogues through Cheat Death, Ferals through Survival Instincts etc. if you casted combustion or scored critical strike that proc ignite before they get their dmg mod buffs on.

http://www.wowhead.com/spell=11129 // combustion
http://www.wowhead.com/spell=12654 // ignite
http://www.wowhead.com/spell=76595 // Mastery: Flashburn

http://us.battle.net/wow/en/forum/topic/2957535757#10 // Blue Post about ignite bug
http://forums.elitistjerks.com/topic/109238-cataclysm-mage-simulators-and-formulators/page-23#entry2057675 // Someone's calculations about Combustion

**Comment by mitim1** [comment]
!bump

**Comment by Jenovas** [comment]
ok so what does this mean? You wrote how it should work but didnt write how it works. Does it double dip from something? Does it take to much DMG from ignite? Does it take to much DMG from living bomb? Does mastery bug it?

**Comment by mitim1** [comment]
"EDIT: I just tested pyro, and again it double dips on mastery but has a low coefficient:" // EJ quote from early cata
"Combustion double dips mastery on LB/pyro, but not ignite." // EJ quote from early cata

**Comment by kadi2** [comment]
Just wanted to bring as much random "useful" information to someone that is going to play around with this bug. All the formulas seemed to work correctly with static damage modifiers like resilience and mastery with combustion.

"Combustion double dips mastery on LB/pyro, but not ignite." // EJ quote from early cata
Someone was telling on ours form that fire mages are doing too much damage with Ignite. It's possible that ignite itself shouldn't take bonus from some damage modifiers like it does on the server. (Mastery, Fire Power, Fire Specialization)

**Comment by Jenovas** [comment]
Closing the issue. The next time you start an issue please write what works, what doesnt work, if it's about the DMG show some numbers.
PL - Zamykam zgłoszenie. W zgłoszeniu ma być opisane co działa, co nie działa, jeżeli dotyczy to DMG jakieś liczby, dowody.
