### ISSUE TITLE
[EN][NPC] Detective Snap Snagglebolt

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#2021]
The NPC doesn't offer any quests. This should have a high priority, since it's related with Love is in the Air achievements.

http://www.wowhead.com/npc=37172/detective-snap-snagglebolt#starts

**Comment by Bildo** [comment]
Ehh you need to do a prequest starting in Undercity.

**Comment by Spydoc** [comment]
Hm, that actually was the case, although it wasn't specified in Wowhead.
