### ISSUE TITLE
[EN][Dungeon-TBC] Shadow Labyrinth 

### ISSUE THREAD

**Issue by Dyju** [Atlantiss/BugTracker#2022]
Most of the mobs in normal or HC Shadow Labyrinth should have items like Fel Armaments and Mark of Sargeras in their loot tables, but they don't drop any, so It's hard to farm Aldor reputation. For example - http://www.wowhead.com/npc=18794/cabal-ritualist#drops
http://www.wowhead.com/item=29740/fel-armament
http://www.wowhead.com/item=30809/mark-of-sargeras#dropped-by

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1837
