### ISSUE TITLE
[EN][Item] Heart-Shaped Box

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#2023]
It seems that defeating the trio in Shadowfang Keep by queuing for Crown Chemical Co. through the RDF system doesn't reward you with Heart-Shaped Box.

http://www.wowhead.com/item=54537/heart-shaped-box

**Comment by xolon** [comment]
If you finish your first random heroic dungeon and get reward, you wont get box from event dungeon. Thats bugged

**Comment by Spydoc** [comment]
Actually, before that I hadn't done a single dungeon for the day and also absolutely nobody from my group, with which we did the trio, got the Heart-Shape Box.

**Comment by xolon** [comment]
did you kill all 3 or just 1 or 2?

**Comment by Wolffenstein** [comment]
Fixed in rev 4304.
