### ISSUE TITLE
[EN] [FIX] [Quest] [Sholazar Basin] Dreadsaber Mastery: Ready to Pounce 

### ISSUE THREAD

**Issue by BAndysc** [Atlantiss/BugTracker#2025]
Almost certainly quest item Shango's Pelt (38523) should have drop chance 100% and lower rate on wowhead is caused by killing the mob without quest.

    DELETE FROM `creature_loot_template` WHERE entry = 28297 and item = 38523;
    INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (28297, 38523, -100, 1, 0, 1, 1);

[Quest on wowhead](http://www.wowhead.com/quest=12558/dreadsaber-mastery-ready-to-pounce)

**Comment by Bildo** [comment]
why gameobject_loot_template

**Comment by BAndysc** [comment]
Of course I used wrong example :D Undoubtedly it should be `creature_loot_template`

**Comment by Navedonar** [comment]
fixed
