### ISSUE TITLE
[EN][Quest][Darkshore] The Eye of All Storms 

### ISSUE THREAD

**Issue by alina999** [Atlantiss/BugTracker#2028]
http://www.wowhead.com/quest=13588/the-eye-of-all-storms

The Npcs http://www.wowhead.com/npc=34282/twilight-rider and the Portal are not in the correct position's and can not be targeted very well or at all, especially the Portal. Please fix this. Thanks.

**Comment by Aival94** [comment]
The [Twilight Portal](http://www.wowhead.com/npc=34316/twilight-portal) and the [Twilight Rider](http://www.wowhead.com/npc=34282/twilight-rider) seems that when first spawn(after restart or crash of server) they are just nice but after someone kill them once, their model seems to go down but their loaction flag look likes it is still on air as you cannot attack them while in the ground but they aggro some times while you fly high enough and come to you.

**Comment by Aival94** [comment]
Minor Issues: 1. NPC [Thessera](http://www.wowhead.com/npc=34243/thessera) is not moving in circles while go up to the tornado.
2. Spell [Land Thessera](http://www.wowhead.com/spell=65579/land-thessera) when reach the highest location for the quest is not working or when mob aggro on you.

**Comment by Lebiedz** [comment]
This quest is still difficult to finish - as Aival94 mentioned there are still Twilight Riders dropping to the ground. What's more, those Riders which are still in the air don't aggro and if I hit them, they heal automatically, making it impossible to kill them. Some of them are evading every attack too.

Also, I gained control over Thessera movement by attacking (right click or "T") one of Riders, which I don't think should be possible.

**Comment by lcorr031** [comment]
Quest is still broken! Dragon Riders are not placed in the correct places (THERE ARE A WHOLE BUNCH OF DRAGON RIDERS ON THE GROUND THAT CAN'T BE ATTACKED), Thessera's flight path is broken, and all Dragon Riders and the Twilight Portal at the top regenerates health which prevents you from killing them.

**Comment by lourrific** [comment]
November 22, 2015 this quest is still broken. Erratic flight pattern can't target anything. the dragon only flies in small circle inside tornado for about 30 secs then lands.

**Comment by njou7** [comment]
November 22, 2015... Is still broken!

**Comment by njou7** [comment]
November 30. 2015. is still broken. Same problems

**Comment by Griskhet** [comment]
Still broken, same issues.

**Comment by Gameexpert** [comment]
This is still broken for my friend and I. When the dragons spawn they just fall to the ground instead of flying in the sky and become unattackable.

**Comment by Spatsa** [comment]
This quest is still broken as of 03/13/16. It is, however, completable.

As said, when approaching the area all of the Twilight Riders will fall from the sky to the ground and are "out of range". When mounting on Thessera the player will follow a flight path upwards for a few minutes. At the end of this flight path, some of the dragons on the ground may or may not aggro the player and attack. There may also be one or two dragons in the sky already.

To complete this quest I had to ride the dragon all the way up, hope the Twilight Riders would aggro, kill them, and repeat the process. Some of the dragons, as well as the twilight portal, will start to immediately heal when you attack them, making killing them almost impossible without a friend who's also on this quest.

**Comment by jesseh101** [comment]
The annoying part of this is that the spell to get the dragon to go back down doesn't work, so in order to do this as any class without slow fall if you do not get drakes to aggro is to fall, die, and run back and hope that they aggro the next time... if they do not, you must rinse and repeat until the quest is finished. Such a shame for a cool quest like this involving Malfurion.

**Comment by karhima** [comment]
This quest is a total mess, nothing's working as intended. Just make it instantly completed maybe?

**Comment by AtlantissPlayer** [comment]
Over a year later and this quest is STILL not working as it should. Devs if you aren't going to bother fixing this up, please just make it auto complete when you accept the quest.

**Comment by Jevsevije** [comment]
You can kill the rider , but there is no Portal to destroy! And dragon can fly, just going in circles and can't land

**Comment by bernatgy** [comment]
I could kill everything, but the dragons didn't register in the roster....

**Comment by attan0** [comment]
Managed to kill the riders with little to no problem, the issue is the portal, that isnt present. Tried flying all around the whereabouts of the quest to check if it was misplaced but wasnt able to find it.

**Comment by martoak** [comment]
The portal is near the ground but when ever you try to attack it either on the dragon or as your own character the system says it's out of range.
![thessera](https://cloud.githubusercontent.com/assets/16217266/18698911/fb3ecd9c-7f8a-11e6-9586-74acf79ca444.png)

**Comment by henrythenth** [comment]
The Twilight Portal unit/object can be targeted just behind Thessera, but can't be seen (no model & nameplate) nor attacked (says out of range when casting character/Thessera's abilities, same as last post)
![wowscrnshot_100816_164203](https://cloud.githubusercontent.com/assets/12162909/19211748/94fe3fa0-8d76-11e6-9426-810f9c5d2f1e.jpg)

**Comment by tattycakes** [comment]
Still having this issue as of 26/02/2016.

I can kill the riders but I can't attack the portal. It's on the ground but keeps saying out of range.

**Comment by roirraWedorehT** [comment]
Still have the issue as of 4/5/2017.  As noted by @henrythenth you can "/tar twilight portal" and target it, but I can't actually see it even when close to the ground, and it always says out of range.

**Comment by leonrm** [comment]
4/20/17 still broken, can't attack the portal

**Comment by Piklo** [comment]
@leonrm open new issue

**Comment by Aival94** [comment]
not really..just comment here https://github.com/Atlantiss/BugTracker/issues/8442
