### ISSUE TITLE
[EN][Talent][Mage] Improved cone of cold doesn't root

### ISSUE THREAD

**Issue by idontknow12** [Atlantiss/BugTracker#2030]
Using a glyphed (+25% dmg) improved (root) cone of cold.
The target never gets rooted.

Revision 4302

**Comment by Wolffenstein** [comment]
Fixed in rev 4304.

**Comment by idontknow12** [comment]
Just tested in revision 4305 and it's not rooting.
If that helps, I have these talents affecting cone of cold:
- 3/3 permafrost
- 2/2 Improved cone of cold
- 1/3 Fingers of Frost
- 3/3 Piercing ice
Plus the glyph.

**Comment by Arcadia713** [comment]
If you mean rooting low level characters (mobs etc) - yeah this is bugged for a long time, but on 85 (especially in PvP) it works totaly fine.

**Comment by idontknow12** [comment]
Oh i see, but that's what i meant - low level mobs. Shouldn't we push for this to get fixed?
