### ISSUE TITLE
[EN][talent][priest] circle of Healing

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#2032]
Noting that i wachted several video's on youtube of people playing holy priest on retail, circle of healing isn't scaling on your intellect/spell power. Also your mastery isn't procing when you use circle of healing. Please fix this asap cause it's making holy less strong as they should be in this patch/expansion

**Comment by TheRealCiapaty** [comment]
I am playing holy priest and circle of healing procs mastery correctly...
