### ISSUE TITLE
[PL][Character] Set

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#2033]
Set zapisany znika po relogu/ wejściu do innego zainstancjonowanego Zone'a

http://www.wowwiki.com/Equipment_Manager   mialem problem zeby znalesc inny jakis link. 

Dosc to problematyczne, zeby szukac itemow w bagu caly czas

**Comment by Kuszki** [comment]
true

**Comment by krecik88** [comment]
Wiemy o problemie, do czasu naprawy zalecam korzystanie z addonów, są rózne do zarządzania setami.

**Comment by Arcadia713** [comment]
Polecam Outfitter.
