### ISSUE TITLE
[EN]Quest][Northern Barrens] A Burning Threat

### ISSUE THREAD

**Issue by Cassedy** [Atlantiss/BugTracker#2034]
Since the NPC Brogor was added recently there is a (small) problem with the quest "A Burning Threat" (Horde)

http://www.wowhead.com/quest=29090/a-burning-threat

First of all: the quest is still doable but it takes longer since only half of the mobs are flagged for the quest.

While the "Burning Blade Bruisers" count as kills for completing the quest, the "Burning Blade Acolytes" dont count as kills & when mouseovered don't show the yellow quest remark.

http://www.wowhead.com/npc=3380/burning-blade-acolyte

**Comment by Bildo** [comment]
fixed
