### ISSUE TITLE
[EN][NPC][QUEST RELATED] Prince Nadun in Uldum

### ISSUE THREAD

**Issue by szejd** [Atlantiss/BugTracker#2035]
He should give following Qs: 
-http://www.wowhead.com/quest=27629/the-viziers-vote
-http://www.wowhead.com/quest=27630/the-high-priests-vote
-http://www.wowhead.com/quest=27631/the-high-commanders-vote
And he doesn't. I have finished the whole Jones story line but cannot get loremaster achi from uldum because of the missing Qs. I asked many people, all had the same problem.

**Comment by Wolffenstein** [comment]
I completed all of them 2 days ago...

**Comment by szejd** [comment]
Nope, like i said i did ALL quests before it and Harisson Jones plot, need 30q more to finish uldum and those q coming after that 3 i linked.

**Comment by Wolffenstein** [comment]
It's impossible, I did those quests, and my guildmates did those quests (and got Uldum achievement). Nobody had an issue with getting those since Uldum was scripted (1.5yrs ago).
