### ISSUE TITLE
Stuck at "Connected" screen

### ISSUE THREAD

**Issue by Creeo** [Atlantiss/BugTracker#2036]
So yesterday everything was working fine, I was playing with my friends and had a good time. But now I can't log in. When I try, I fill in the password, it does all the stuff like "Handshaking" and such, but then I reach the Connected screen, and if I press the cancel button, the game freezes and I can't close it, and if I wait for a while the game freezes again and I am unable to close the application nor continue. 

This problem also occurred for my friends and we're not playing on the same network. Help/fix is appreciated. Thanks.   

EDIT: The way we fixed it and were able to log in was to:
1. Start the game. DO NOT LOG IN
2. Wait 1-3 minutes.
3. Quit the game with the "Quit" button at the bottom right corner.
4. Restart the game.
5. Log in.

**Comment by Bildo** [comment]
It was a temporary problem and its fixed now.
