### ISSUE TITLE
[EN][Quest][Icecrown]the battle for crusaders pinnacle

### ISSUE THREAD

**Issue by silverches** [Atlantiss/BugTracker#2038]
http://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle
http://www.wowhead.com/npc=30987/hideous-plaguebringer

The Hideous Plaguebringer are only lvl 1 with just a bit more than 100HP. They should be lvl 80 with 13,835 HP.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
