### ISSUE TITLE
[EN][Mind Spike][Priest] 

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#2041]
Any interrupt on shadow school does lock shadowfrost school[mind spike]
http://www.wowhead.com/spell=73510/mind-spike#used-by-npc
http://www.wowwiki.com/Mind_Spike  [1]
"Cataclysm-Logo-Small Patch 4.2.0 (28-Jun-2011): When interrupted while casting a single-school spell such as Mind Flay or Frostbolt, players will now be able to cast dual-school spells such as Mind Spike (Frost and Shadow schools) or Frostfire Bolt (Frost and Fire schools). However, being interrupted while casting a dual-school spell will still interrupt all respective schools as intended"  -->[1]
I'd like to bump https://github.com/Atlantiss/BugTracker/issues/6!!!

**Comment by Arcadia713** [comment]
Contributed with: https://github.com/Atlantiss/BugTracker/issues/84

**Comment by Wolffenstein** [comment]
Fixed in rev 4355.
