### ISSUE TITLE
[EN][talent][Priest] Twisted faith

### ISSUE THREAD

**Issue by stewazy** [Atlantiss/BugTracker#2042]
This talent should give 100% of spirit into hit rating but i have the same hit rating with and without the talent.

**Comment by kadi2** [comment]
I don't believe nobody noticed this before, make sure you are looking at spell hit rating instead melee hit rating.

**Comment by Dziara** [comment]
It works properly.

**Comment by Jenovas** [comment]
Works ok. Closing.
