### ISSUE TITLE
[EN] [NPC] Warlord Thresh'jin

### ISSUE THREAD

**Issue by darklord88** [Atlantiss/BugTracker#2045]
Npc dont spawn yet for http://www.wowhead.com/quest=27481/out-of-the-ziggurat quest

**Comment by MorbidMike** [comment]
The quest NPC required to kill does not spawn for this quest. He is not targettable through /tar Warlord.

**Comment by Bildo** [comment]
He is but idk why he has 240 minutes respawn :hankey:

**Comment by Alandiel** [comment]
He was rare mob for some time on 4.0.6 maybe that's why his respawn is 4h.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
