### ISSUE TITLE
[EN][NPC][Duskwood] Ravaged Dire Wolf

### ISSUE THREAD

**Issue by PVPViddys** [Atlantiss/BugTracker#2047]
The mob aggros and targets nearby players.

Ravaged Dire Wolf (http://www.wowhead.com/npc=45517/ravaged-dire-wolf) should be dead and non-interactable. However it is actually alive and just has this aura (http://www.wowhead.com/spell=29266/permanent-feign-death).

**Comment by PVPViddys** [comment]
It appears it should already been fixed but I can assure you the issue remains.
https://github.com/Atlantiss/BugTracker/issues/724


XYZ of one example: -10603.83, -790.7663, 59.50988

**Comment by Bildo** [comment]
None of them has this aura also the only bug is that they aggro to player.

**Comment by PVPViddys** [comment]
So very easy fix then?

**Comment by PVPViddys** [comment]
Agree, mob should not aggro.
