### ISSUE TITLE
[PL] [dungeon finder] zandalari

### ISSUE THREAD

**Issue by szpagaciarz** [Atlantiss/BugTracker#2051]
Powinna być jeszcze 1 opcja do wyboru 
Type: random Rise of the Zandalari
http://www.wowhead.com/guide=4.1
 tu 1 fotka to pokazuje

**Comment by Bildo** [comment]
jestesmy na patchu 434 wiece nie ma tej opci i zamaist tej jest hours of twilight

**Comment by szpagaciarz** [comment]
Ale jest content z patcha 4.1. Chyba, że nie ma tej opcji w plikach gry to ok.
