### ISSUE TITLE
[PL][Core]You have entered too many instances recently

### ISSUE THREAD

**Issue by TheRealCiapaty** [Atlantiss/BugTracker#2056]
Często wchodzenie na zwykłe dungeony(nie za pomocą Dungeon Findera) blokuje naszą postać na godzinę. Wiele razy miałem taką sytuację, że po zresetowaniu instancji wyskakiwał mi komunikat "You have entered too many instances recently" kiedy próbowałem wejść na instancje(co dziwniejsze, na niektóre wchodziłem normalnie a na inne nie mogłem wejść i pojawiał się ten komunikat). O ile dobrze pamiętam to na patchu 4.3.4 powinno blokować dopiero po zrobieniu/zresetowaniu dungeona 5 razy w ciągu jednej godziny, tutaj wygląda to tak, że czasami blokuje, czasami nie, dzieje się to kompletnie randomowo i często jest bez sensu...

**Comment by Varchord** [comment]
To nie ma blokować po zrobieniu/ zresetowaniu tylko po wejściu 5 krotnym. Wejdziesz i wyjdziesz 5 raz w ciagu 5 min do instancji to będziesz zablokowany.
Tak powinno byc

**Comment by TheRealCiapaty** [comment]
Nawet jeśli, ja czy znajomy z gildii na pewno minimum 5 razy nie weszliśmy. Wczoraj próbowaliśmy zrobić Stratholme w Caverns of Time, na początku zapomniałem zmienić z normala na HC, więc znajomy wyszedł z instancji, po zmianie już nie mógł wejść. Później ja wchodziłem i wychodziłem wiele wiele razy i nie byłem blokowany. Następnie stwierdziliśmy, że będziemy sobie robić Stonecore normala, on mógł wejść a ja nie. Wszystko działo się w ciągu tej samej godziny...

**Comment by NONLIFE** [comment]
Masz 5 rekordow. Kazdy rekord ma swoj czas wejscia do instancji. Rekord zwalnia sie po 60 minutach od czasu wejscia do instancji.

close plz

**Comment by TheRealCiapaty** [comment]
Nie no, na globalu działało to trochę inaczej, ale skoro uważacie, że nie mam racji to zamykajcie. Nie zmienia to faktu, że wiele osób na tym serverze często skarży się na ten problem
