### ISSUE TITLE
[PL][Spell][Rogue] Smoke Bomb

### ISSUE THREAD

**Issue by Tyroth** [Atlantiss/BugTracker#2058]
Nie ma możliwości wyciągnięcia friendly targetu z friendly smoke bomby spellem priesta "Leap of Faith". Widać to na obrazku zamieszczonym poniżej. http://i.imgur.com/yd7EeML.jpg

**Comment by Arcadia713** [comment]
Linki: 
http://www.wowhead.com/spell=76577/smoke-bomb
http://www.wowhead.com/spell=73325/leap-of-faith

**Comment by lastkiss** [comment]
+ można oberwać z zewnątrz np. deep freez będąc w Smoke Bomb jak na tym obrazku http://i.imgur.com/h5KWH2Y.jpg 

bomba działa jakby odwrotnie, przeszkadza friendly targetom a propsuje enemy ;d

**Comment by Arcadia713** [comment]
Aha no i https://github.com/Atlantiss/BugTracker/issues/1878 jak już bugi o Smoke Bomb :P

**Comment by Genomnomnomnom** [comment]
- Jeśli dwa enemy Rogue klada Smoke Bomb w odddzielnych miejscach, mogą się targetować i Shadowstepować do siebie. Pewnie dotyczy to też pozostałych graczy, więc Bomby zamiast tworzyć za każdym razem osobny LoS tworzą wspólnie "sieć połączonych chmur" (błagam niech ktoś to wytłumaczy za mnie)
- Smoke Bomb powinien negować działanie Spirit Link Totem Szamana
- Jeśli położę Smoke Bomb na enemy targecie, odbiegnę z dala od jej zasięgu, to przeciwnik wciąż jest w stanie targetować mnie na zewnątrz Bomby

**Comment by Genomnomnomnom** [comment]
- SMOKE BOMB NIE DZIAŁA, PRZECIWNIK MOŻE MNIE TARGETOWAĆ Z ZEWNĄTRZ

**Comment by armano2** [comment]
duplikat: #1878
