### ISSUE TITLE
[EN][Spell][Mage] Mirror Image

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#2059]
Since openwow doesn't work since a week for now, I will link that spell from another server
<a href="http://cata-shoot.tauri.hu/?spell=55342">Mirror Image</a>

Basically the main problem with this spell, is when I use it, my mirror images won't attack my target. However they will start attacking when I make them moving from their start postion ( I have to walk away in any direction like 5yards to make them work). This is very frustrating especially in encounters, when I have to break my rotation to make them do something useful.

This is how it should work: "Creates copies of the caster nearby, which cast spells and ATTACK the mage's enemies". They should automatically start attacking my primary target!

Screenshot(I'm in combat with the dummy, yet my pets won't attack): 
<img src="http://i.imgur.com/YEbeuDB.jpg" />

Mirror Image does not replicate transmogrified equipment's look that a Mage is wearing, instead it replicates the items' default look.
http://www.wowhead.com/spell=55342/mirror-image

**Comment by Arcadia713** [comment]
Related to: https://github.com/Atlantiss/BugTracker/issues/633 (in Polish)

**Comment by drlinux92** [comment]
Well yes I found that ticket, to be honest, and put the whole text into the translator, buuuut I couldn't find any sentence containing this type of bug which I described here, but maybe it's the translator then :P

**Comment by Arcadia713** [comment]
No, i mean in polish issue there's nothing about not attacking (but should be :P) - i just posted link, because is problem with same spell so it could related somewhat with this problem ;)

**Comment by drlinux92** [comment]
Oh, alright :)

**Comment by sunshineinabox** [comment]
I found the following fix that was related to a similar trinitycore issue. [Here](https://github.com/Ofinka/TrinityCore/commit/ee9c9e6051e4bcbd02d7710473068d8ddab89cc5) it is not sure if it would help.

**Comment by armano2** [comment]
link: #633

**Comment by Pocketerino** [comment]
Bumperino.

**Comment by pelekon** [comment]
Fixed in 5840
