### ISSUE TITLE
[EN][Spell] Inner Focus

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#2062]
In most cases inner focus is displayed as ready while being on cd.Its so irritating being interrupted due to this bug.
http://www.wowwiki.com/Inner_Focus  wowwiki link due to the fact that dm cata does not work and inner focus does not exist anymore on wowhead

https://github.com/Atlantiss/BugTracker/issues/6  >> BUMP

**Comment by TheRealCiapaty** [comment]
Confirmed

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by Wolffenstein** [comment]
Can't reproduce, any ideas?

**Comment by razgal** [comment]
@Wolffenstein  here is how you can reproduce it ;)
https://github.com/Atlantiss/BugTracker/issues/4808

**Comment by debtheone** [comment]
bump

**Comment by Jenovas** [comment]
Fixed in rev 4714
