### ISSUE TITLE
[PL][Priest]Surge of Light i Chakra

### ISSUE THREAD

**Issue by TheRealCiapaty** [Atlantiss/BugTracker#2063]
Po użyciu Chakry, a następnie Flash Heala kiedy mamy proca Surge of Light, Chakra nie ulega zmianie i dostajemy na nią cooldown. Bez Surge of Light użycie flash heala normalnie zmienia chakrę.
http://www.wowhead.com/spell=2061/flash-heal
http://www.wowhead.com/spell=114255/surge-of-light
http://www.wowhead.com/spell=126172/chakra

**Comment by Wolffenstein** [comment]
Fixed in rev 4355.
