### ISSUE TITLE
[PL][Priest] Borrowed Time

### ISSUE THREAD

**Issue by Meteora11** [Atlantiss/BugTracker#2064]
Buff Borrowed Time (http://www.wowhead.com/spell=52798/borrowed-time) nakładany przez użycie Power Word: Shield jest konsumowany przez spelle channelowane typu Penance, Hymn of Hope itd.
Buff ten powinnien zwiększąć szybkość casta spelli channelowany i castowanych, jednak w wypadku channelowanych nie powinien być konsumowany.
Dowody jako takie obecnie ciężko znaleść, oto najlepsze jakie wygrzebałam.
1. http://forums.elitistjerks.com/topic/105060-healing-priest-faq-v401-surviving-until-december-7th/?p=1763253
wypowiedź z Elite Jerks.
2. Filmik z globala:
https://www.youtube.com/watch?v=HCr9_RDZq8w&feature=player_detailpage#t=1203
proszę obserwować: Zarzuca Power Word: Shield, dostaje buffa Borrowed Time, channeluje Penance (z przyspieszonym castem od Borrowed Time) i dalej ma buffa od Borrowed Time aż do następnego casta.

**Comment by Vyrtuz** [comment]
Potwierdzam, ten bug jest od dłuższego czasu i był zgłaszany na 4.0.6
Ja znalazłem jeszcze takie coś:

http://www.tauri-veins.tk/discipline-priest-wow-pve-healing-rotation-cooldowns-abilities

"After each cast of Power Word: Shield you gain the Borrowed Time buff. This reduces the cast time of your next spell by 14%, provided that you cast a spell within 6 seconds (before the buff expires). Casting a spell consumes the buff. Note that spells with an instant cast time, as well as channeled spells, do not benefit from nor consume the buff."

"Penance does not consume the Borrowed Time buff, even though its cast time does benefit from the buff. An important note should be made here. For maximum efficiency, you should try to cast a Penance after your Power Word: Shield and before the heal which will consume Borrowed Time."

**Comment by debtheone** [comment]
Meteora11 opened this issue on 5 Feb 2015  
almost a year 

BUMP

**Comment by debtheone** [comment]
BUMP

**Comment by debtheone** [comment]
bump

**Comment by stanq87** [comment]
ciagle zbugowane

**Comment by debtheone** [comment]
bump

**Comment by Tetriandoch** [comment]
Bump, Disci received some nice fixes, but this one is still bugged

**Comment by lamaATS** [comment]
Fixed in rev. 5224
