### ISSUE TITLE
[EN] Auction House : Items that return via mailbox after expiring on an auction have C.O.D.

### ISSUE THREAD

**Issue by lolwtfqt** [Atlantiss/BugTracker#2065]
Title says it all. Happened twice yesterday.
![wowscrnshot_020515_180343](https://cloud.githubusercontent.com/assets/10812986/6072601/d3ebd1aa-ada3-11e4-8654-0fdbc3c29832.jpg)

**Comment by Magohoy** [comment]
Can confirm, I have a full mailbox of C.O.D' items from canceled auctions.
