### ISSUE TITLE
[PL][Quest][Wotlk][Battered Hilt]The battered Hilt

### ISSUE THREAD

**Issue by derbeal** [Atlantiss/BugTracker#2068]
Gdy przyjmie sie misje pojawia sie drugi itemek. Po odrzuceniu questa ma sie gotowe 2 battered hilty w skorcie klonuja sie. 
FILM: 
https://www.youtube.com/watch?v=VHcZdqHmPhs&feature=youtu.be

**Comment by Bildo** [comment]
zasady bt
