### ISSUE TITLE
Mobs Grim Batol

### ISSUE THREAD

**Issue by M1kox** [Atlantiss/BugTracker#2069]
Moby w Grim batol dostały niemożliwego boosta, ukończenie instancji jest niemalże niemożliwe.

**Comment by Asavel** [comment]
jakie moby i linki daj bo ci bildo zamknie ;D

**Comment by Varchord** [comment]
I nazwę zmien

**Comment by Meteora11** [comment]
Zapewne chodzi o ten mobki: http://www.wowhead.com/npc=39405/crimsonborne-seer#abilities i ich umiejętność Corrupted Flame.
