### ISSUE TITLE
[PL][Priest] [Talent]Atonement

### ISSUE THREAD

**Issue by Meteora11** [Atlantiss/BugTracker#2070]
Atonement (http://www.wowhead.com/spell=81749/atonement#comments).
Crity z leczenia z Atonement powinny procowac Divine Aegis (http://www.wowhead.com/spell=47515/divine-aegis)- czyli crity ze Smite oraz Holy Fire.
Dowód:
http://wow.gamepedia.com/Atonement
"Crits from Atonement healing will proc [Divine Aegis]."
Filmik:
https://www.youtube.com/watch?v=iXuH3kuLgiI&feature=player_detailpage#t=146

**Comment by Dziara** [comment]
Potwierdzam!

**Comment by Meteora11** [comment]
nie chce być upierdliwa ale czemu w każdej klasie coś fixujecie poza prejem? 2 zgłoszenia leżą i zero reakcji.

**Comment by Wolffenstein** [comment]
https://github.com/Atlantiss/BugTracker/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22Class+-+Priest%22+is%3Aclosed - prej kompletnie olany

**Comment by Wolffenstein** [comment]
Fixed in rev 4331.

**Comment by Nouitra** [comment]
Moge potwierdzic ze problem nie zostal jeszcze rozwiazany. Crity z Smite/Holy Fire nadal nie procuja Divine Aegis. W rev 4331 wprowadzono critical heala z atonementa i co za tym idzie proc Divine Shielda.
Natomiast w rev 4567 odjeto mozliwosc critowania z atonementa i system nie uznaje crita ze smita jako critical heala w nastepstwie nie procuje Divine Aegisa.
Szybka naprawa byla by mile widziana ze wzgledu na duzy inbalance zwiazany z tym bugiem.

This problem have not been solved yet. Crits from Smite and Holy Fire does not proc Divine Aegis. In rev 4331 patch was introduced that was supposed to fix the problem with atonement and divine shield : "Atonement heals can now crit and proc Divine Aegis". Then bug was discovered that healing from atonement was crting twice so:
In rev 4567 fix was introduced that took away ability to crit with atonement. Systems thanks to that AWESOME change now does not trigger Aegis cause the heal from atenement ( even when smite and holy fire crit ) is not considered a crit. 
Just to clarify things ( some1 already wrote how the atonement and divine aegis should work but no1 listened ):
When we crit with Smite, lets say 10k we should get heal of the same amount but that heal should be considered a crit( unless we got archangel buff which gives us 3/6/9/12/15% more healing ) and should proc Divine Aegis. With Archangel buff and basic mastery=30%, it should go like this:
Smite crit =10k so Heal = 10k+15% from Archangel buff = 11,5k + a bubble = 3450 x 30% =4485 Divine Aegis. 
http://us.battle.net/wow/en/forum/topic/8728753750
Look for Fibromyalgia post. Read the part about cata.

**Comment by Beatit** [comment]
bump :)
