### ISSUE TITLE
[EN][City][Drop] Mailbox (AH GOLD)

### ISSUE THREAD

**Issue by Sehje** [Atlantiss/BugTracker#2071]
What to do about AH sells, does not receive gold

![wowscrnshot_020615_090403](https://cloud.githubusercontent.com/assets/10879101/6076241/f701d1de-ade0-11e4-996e-dd20b18ee3b3.jpg)
![wowscrnshot_020615_090410](https://cloud.githubusercontent.com/assets/10879101/6076242/f7069b1a-ade0-11e4-87a3-353ac9734f88.jpg)

**Comment by Axahus** [comment]
o_O
Just learn english - "Amount not yet sent" "Estimated delivery time 12:00".

**Comment by Sehje** [comment]
and if you look at the clock it is 09.00AM

**Comment by Sehje** [comment]
it said the same for more then 15hours

**Comment by Iambugged** [comment]
Maybe your mailbox is full?

**Comment by Sehje** [comment]
It's wierd, now i force deleted Them all from inbox, after 10min i got new mail with the gold? 

I only had 2 pages of mails.. 

Don't know if it is solved now, but I believe I got it all

**Comment by Exorcista** [comment]
You can delete this type of message, they just say you just sold X item, the gold comes in another mail that its autosaved in the server DB, delething theese wont make you not recieve you gold Dx
