### ISSUE TITLE
[EN][Gameobject][Stormwind] Mailbox Locations

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2076]
Stormwind is missing 2 mailboxes that I remember:

![Mailbox 1](http://i.imgur.com/63f5PUU.jpg)
See Cata screenshot from Feb, 8th 2012 [here](http://i.imgur.com/JAZf48Z.jpg). (Also now that I see it, the cart wasn't there either. Maybe it belongs to a special event? Both screenshots are from the love is in the air event)

![Mailbox 2](http://i.imgur.com/dOhA3Fs.jpg)
See screenshot from Jan, 13th 2011 [here](http://i.imgur.com/54VdxmE.jpg). The mailbox on the other side near the AH is correct, but near the bank there was one, too.

Not a big deal, but when you crafted and sold hundreds of glyphs and other stuff per day back in that time, you kinda got to know your mailboxes... :D

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
