### ISSUE TITLE
[PL][Other][Borean Tundra]Brak Tundra Penguin

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#2078]
Brak jest crittera http://www.wowhead.com/npc=28440/tundra-penguin co uniemożliwia ukończenie achievementu http://www.wowhead.com/achievement=2557/to-all-the-squirrels-who-shared-my-life.

**Comment by Bildo** [comment]
na serwerze znajduje sie 34 tych pingwinow szukaj dalej

**Comment by Haz3L** [comment]
To w takim razie są pod teksturami jak reszta pingwinów.

**Comment by Drutmaster** [comment]
Są są. Normalnie stoją na lodowcu, na południe od głównej bazy ally w borean
