### ISSUE TITLE
[PL][Quest][Classic][Scarlet Cathedral]Compendium of the Fallen

### ISSUE THREAD

**Issue by radarowiec** [Atlantiss/BugTracker#2079]
Książka, którą powinniśmy wziąć z półki http://www.wowhead.com/object=19283/compendium-of-the-fallen po wzięciu Q od NPC Dominic jest nietargetowalna. Świeci, ale nie można jej wziąć.
![zrzut ekranu 2015-02-06 o 15 51 08](https://cloud.githubusercontent.com/assets/10885193/6083047/41e779a2-ae26-11e4-8ac3-4fc5b055a489.png)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1559
