### ISSUE TITLE
[EN][Rogue][Spell] Cloak of Shadows

### ISSUE THREAD

**Issue by lastkiss** [Atlantiss/BugTracker#2080]
Cloak of Shadows http://www.wowhead.com/spell=31224/cloak-of-shadows is bugged again.
Should prevent a rogue from receiving magical debuffs, magical dmg etc but sometimes it does not.
This annoying bug had occured on 4.0.6 patch but it seems that it returned.

http://i.imgur.com/3KfIWnO.jpg (fearie fire while in cloak of shadows and couldnt vanish..)
http://i.imgur.com/OCimAEA.jpg (frosfite bolt while in CoS)

bump --> https://github.com/Atlantiss/BugTracker/issues/2058

**Comment by Wolffenstein** [comment]
Any ideas when this happens? How to reproduce?

**Comment by lastkiss** [comment]
I dont know. it just happens sometimes and its hard to say when it will occur for sure. one time it works fine and another time it works like shit

**Comment by zano354** [comment]
perhaps, its still working like the wotlk cloak of shadow, where you have 90% chance to immune any spells incoming (not 100% chance of immunity).

**Comment by kadi2** [comment]
I couldn't find any info about fearie fire (feral), but are you sure it isn't supposed to go through CoS unlike normal Fearie Fire?

About frostfire Bolt, do you remember if that was glyphed frostfire bolt? That would be helpful info for sure.

**Comment by lastkiss** [comment]
bump

it seems it doesnt work again and always f*cks up in the worst moment --> today bg's screenshots

http://i.imgur.com/LVX0oEo.jpg and 7 minutes later http://i.imgur.com/o8r4EBB.jpg

pls do something with this it is a massive critical bug

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
