### ISSUE TITLE
Tabard of Illidari - Quest -  Battle of the Crimson Watch

### ISSUE THREAD

**Issue by dwergjee03** [Atlantiss/BugTracker#2081]
Today i did this quest . 
After you complete the quest and you receive the ring and the box with the tabard inside i ecountered a  bug. After you open the box it will appear a message that says that the box is empty.
This leads you to not receiving the tabard of illidari and of course you cant repeat the quest.

**Comment by Drutmaster** [comment]
You can go to dalaran center and talk with tabard vendor, she has a quote in case if you lost your tabard. You should be albe to choose, which one you want to receive in return

**Comment by Supremacja** [comment]
Val'zareq the Conqueror  doesn't drop The Journal of Val'zareq. I'am after the Path of Conquest chain and still nothing. I'am thinking that item is not added to Val'zareq drop.
