### ISSUE TITLE
[ENG][Quest[Silithus] The Twilight Mystery

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2082]
http://www.wowhead.com/quest=8284/the-twilight-mystery

Some "Twilight Tablet Fragment" (http://www.wowhead.com/item=20378/twilight-tablet-fragment) are not usable, for example at cord. (33,14).

**Comment by Haffyd** [comment]
Now i can't get this starter q. Geologist Larksbane don't have any avaiable quest :(

**Comment by Technowizard15** [comment]
Have you already done "Vyral the Vile" and "Dearest Natalia"? Both should by the requirement for this quest. Did this quest with 3 chars in the last 2-3 weeks.

**Comment by Haffyd** [comment]
Yes i have done this "Vyral the Vile". Still don't see a new q from Geologist Larksbane

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
