### ISSUE TITLE
[EN][Dungeon-Classic] Lower Blackrock Spire

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2084]
He are some things I've noticed about Lower [Blackrock Spire](http://www.wowhead.com/zone=1583/blackrock-spire). Apart from Vosh'gajin's Hex and some mobs dropping no loot they are barely noticable, and I thought: "Should I even write that down? Hm... might as well."

### [Shadow Hunter Vosh'gajin](http://www.wowhead.com/npc=9236/shadow-hunter-voshgajin#abilities)

Vosh'gajin's ability Hex seems to be too strong right now. It should have 8 sec duration and 20 yd range (so that healers and range DPS could easily outrange this ability).

Right now, Hex has ~20 sec duration and cannot be outranged.

### [War Master Voone](http://www.wowhead.com/npc=9237/war-master-voone#encounter)
- Voone uses only his abilites [Throw Axe](http://www.wowhead.com/spell=16075) and [Snap Kick](http://www.wowhead.com/spell=46182). He didn't use [Thrash](http://www.wowhead.com/spell=158175), [Cleave](http://www.wowhead.com/spell=20666), [Mortal Strike](http://www.wowhead.com/spell=12294), [Uppercut](http://www.wowhead.com/spell=18072) and [Pummel](http://www.wowhead.com/spell=6552) in our fight ([combatlog](http://pastebin.com/WtBKfZWk)), but the fight was over fast anyways
- (I'm unsure if he dropped any loot)

### [Mother Smolderweb](http://www.wowhead.com/npc=10596/mother-smolderweb)
The fight was fine, but she didn't drop loot

### [Urok Doomhowl](http://www.wowhead.com/npc=10584/urok-doomhowl)
- Urok was attackable right from the start ([pic](http://i.imgur.com/TeM6UNF.jpg)), we did not have to combine a [Pike](http://www.wowhead.com/item=12533#comments:id=1603881) and [Omokk's Head](http://www.wowhead.com/item=12534#comments) to spawn multiple waves of Ogres until Urok finally appears. I didn't miss it though, and the fight itself was fine.
- He did not drop any loot

### [Quartermaster Zigris](http://www.wowhead.com/npc=9736/quartermaster-zigris#encounter)
- Did not use [Hooked Net](http://www.wowhead.com/spell=15609) and [Drink Healing Potion](http://www.wowhead.com/spell=62822) ([combatlog](http://pastebin.com/5CdLrhX9))

### [Halycon](http://www.wowhead.com/npc=10220/halycon#encounter) & [Gizrul the Slavener](http://www.wowhead.com/npc=10268/gizrul-the-slavener#encounter)
- Halycon does not cast [Thrash](http://www.wowhead.com/spell=158175) and [Rend](http://www.wowhead.com/spell=772). Does cast *Mighty Blow* and *Crowd Pummel* instead ([combatlog](http://pastebin.com/jZwC4i6a))
- Gizrul does not cast [Frenzy](http://www.wowhead.com/spell=156861) and [Fatal Bite](http://www.wowhead.com/spell=20539)

**Comment by Bildo** [comment]
i merged ur topic (as a parf of my and Armano bt cleanup :P )
