### ISSUE TITLE
[EN] [Rogue] Energy regeneration on attack debuff.

### ISSUE THREAD

**Issue by MikeViper** [Atlantiss/BugTracker#2085]
Energy regeneration is bugged on Atlantis from what I've observed. Attack speed debuffs like Frost armor or earth shock decrease the amount of energy gained, which technically it should not be the case. Those debuffs do not modify haste to affect Energy regeneration, they only reduce attack speed and hence it should not reduce energy regeneration rate.

As an example, Slice and Dice increases attack speed by 40% but it does not mean the energy gained is also increased by 40%. It only increases the attack speed itself which has no relevance with energy regen.

Further addition is that Focus or Energy can go below negative in amount, as in losing them instead of gaining which should not happen by any circumstances. At worst Energy or Focus stays frozen and doesn't regenerate, it should never go negative.
There is this mob in eastern plaguelands (http://www.wowhead.com/npc=9451/scarlet-archmage) which has an 100% slowing attack frost armor, getting affected by it will cause energy to degrade, instead of gained. Can be easily tested by GM.

As of conclusion:
- Attack speed debuffs should not affect energy regeneration, unless it is haste related modifier like Bloodlust is, bloodlust gives raw 30% haste which increases energy regen. On Atlantis those debuffs do that and it should not be the case, just like melee attack speed buffs don't increase the energy gained (slice and dice or Lightning reflexes 9% talent) neither attack speed debuffs should decrease it.

Thanks for your time, here's hoping for a fast fix. Can be gamebreaking for rogues in pvp and certain pve encounters.

**Comment by adryjan** [comment]
Ye im leveling rouge now, but didint played him since tbc, i was concern about this energy regen few times when my atack speed was slowed. I couldnt use my sinister strike as often as should be.

**Comment by Iambugged** [comment]
Can confirm it happens to Feral druids too.

**Comment by Jenovas** [comment]
Fixed in rev  4363
