### ISSUE TITLE
[EN](wotlk dungeon) culling of stratholme hc loot

### ISSUE THREAD

**Issue by Swepy** [Atlantiss/BugTracker#2089]
http://www.wowhead.com/object=190663/dark-runed-chest#screenshots:id=306253

Hi
after killing Mal'Ganis (he is the last boss) in culling of stratholme hc mode solo as a lvl 85 blood dk i coudnt loot/click on him or on the dark duned chest, so i cant get any loot from the last boss. I don't know if it happens every time, but it happened twice in two try. (sorry for bad english)

**Comment by Bildo** [comment]
duplicate
