### ISSUE TITLE
[EN][Druid][Spell] Faerie Fire

### ISSUE THREAD

**Issue by Tyroth** [Atlantiss/BugTracker#2090]
Faerie Fire has now 3 stacks and to get them off, you need 2 dispels, while this should only be 1. Let's say there are 3 stacks of FF and frost nova on a target. When priest's dispel hits 1 stack of FF and nova, then the target has no debuffs at all, because when at least 1 stack of FF gets dispelled, the rest goes off too. Priest's dispel has to hit 2 different magic debuffs (if there are 2), so there should be no possibility to hit 2 stacks of faerie fire without dispeling nova. It's hard to find some info about it right now, but i found some discussion on bnet. http://us.battle.net/wow/en/forum/topic/2016084183

**Comment by kadi2** [comment]
Confirmed
https://www.youtube.com/watch?v=SXsAB-2aRo4

**Comment by Tyroth** [comment]
Bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by Genomnomnomnom** [comment]
BUMP

**Comment by Isuel** [comment]
confirmed. quite important, i'd say xd

**Comment by Genomnomnomnom** [comment]
BUMP BUMP BUMP BUMP BUMP

It wouldn't be a overstatement if I said that it's a GAMEBREAKING bug. Whole arena I'm in roots and fears due to dispel protection, as Rogue I cannot restealth/Vanish without praying to RNG Gods.

**Comment by Genomnomnomnom** [comment]
BUMP

**Comment by Thefakemccoy** [comment]
Also want to add that if 1 druid has the talent to put more than one stack on, and another druid does not then the weaker one overwrites the stronger one.

a single stack FF should not overwrite a 2 stack FF

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
