### ISSUE TITLE
[EN][Faction]Mag'Har

### ISSUE THREAD

**Issue by grzott** [Atlantiss/BugTracker#2092]
I cannot interact with :  Mag'har http://www.wowhead.com/faction=941/the-maghar
i tried to do pre q in Helfire penisula but i cant end quest with npc : http://www.wowhead.com/quest=9406/the-maghar

**Comment by meta1** [comment]
i did whole chain for this reputation and when i capped friendly or honored i could talk with their vendor, for me works all fine, did a week ago

**Comment by grzott** [comment]
My bad, everything working fine.
