### ISSUE TITLE
[EN][Druid][Spell] Feral Charge - Cat

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2093]
When Feral Charging (cat version) a player that it hugging his back against a wall my druid will leap behind him through to the other side of the wall and make me fall through the ground.
http://www.wowwiki.com/Feral_Charge_-_Cat

**Comment by Jenovas** [comment]
Fixed in rev 4475

**Comment by ahtebe** [comment]
It doesn't even leap behind anymore whether the mob is against a wall or not. Tested on training dummy with no wall behind and on Cutpurse (http://www.wowhead.com/npc=94/cutpurse) in Elwynn Forest.
