### ISSUE TITLE
[PL][Profession][Engineering] Spinal Healing Injector

### ISSUE THREAD

**Issue by strzala** [Atlantiss/BugTracker#2094]
http://www.wowhead.com/spell=82200/spinal-healing-injector

Opis z tooltipa: "Permamently attaches a specialized injector kit to your gloves, allowing you to inject a Mythical Healin Potion directly to your bloodstream for increased effect. Only a skilled engineer can activate the modified gloves"

Enchant działa - leczy poprawnie i załącza cd na normalną potkę, jednak nie załącza się CD na same glovesy.Tzn - po upływie minuty 2,3,5 dalej otrzymujemy informacje"You cannot drink yet"(cytat z głowy). Natomiast po relogu można znowu użyć.

W skrócie - potrzeba dodać cd do owego enchantu.

**Comment by Bildo** [comment]
duplikat
