### ISSUE TITLE
[PL][Priest][Spell]Divine Hymn

### ISSUE THREAD

**Issue by Meteora11** [Atlantiss/BugTracker#2096]
Divine Hymn(http://www.wowhead.com/spell=64843/divine-hymn) tylko podczas combatu jest przerywany mimo, że nie otrzymuje żadnego dmg/nie ruszam się/ nic mi nie przerywa casta.
Dzieje się tak tylko i wyłącznie w combacie, poza jest ok
Tracimy na tym około ~2 ticki hymnu więc jest to dość bolesne.
W razie wątpliwości mogę przedstawić filmik.

**Comment by TheRealCiapaty** [comment]
Jesteś pewien/pewna, że to żaden mob/boss nie przerywał divine hymnu?

**Comment by Meteora11** [comment]
tak, jestem pewna co więcej tak jest ZA KAŻDYM RAZEM. W sumie potem wrzuce filmik.

**Comment by Meteora11** [comment]
https://www.youtube.com/watch?v=lgcUMARkeO8&feature=youtu.be
specjalnie spaliłam hymn na fazie bez aoe/direct dmg we mnie. Filmików mogę wrzucić więcej ale raczej nie ma sensu bo na każdym będzie to samo. Tutaj akurat mam Bloodlust ale to nie ma znaczenia, z nim czy bez przerywa.

**Comment by TheRealCiapaty** [comment]
Szczerze mówiąc miałem taką sytuację wczoraj podczas walki z Al'Akirem ale to on wtedy przerywał. Jednakże, dzisiaj sprawdzałem kilka razy i faktycznie jest z nim coś nie tak, często przerywał mi się tak sam po prostu...

**Comment by Aviannaqt** [comment]
Przerywa ci, poniewaz haste dziala na hymn, ale cast nadal trwa 8 sec. Podczas BL hymn ticka co +- 1,5 sec a przerywa dlatego, ze maksymalna liczba tickow to 20. Bylo to naprawiane i od tego czasu wg. mnie dziala bardzo dobrze.

**Comment by Meteora11** [comment]
czytaj ze zrozumieniem: z bl'em czy bez jest to samo.

**Comment by Aviannaqt** [comment]
To dziwne XD
Tysiace razy używałem hymna i nigdy nic nie zauwazyłem.. ;D

**Comment by Meteora11** [comment]
Potem postaram się wrzucić wycinek z WoL z dowodami.

**Comment by meta1** [comment]
rowniez mialem z takim bugiem do czynienia jak Meteora

**Comment by Jenovas** [comment]
To że przerywa to jest poprawne działanie. Jeżeli spell wyleczy 20 razy ma się automatycznie przerwać, bo 20 to jego limit. Jeżeli przerywa się a nie ma 20 hili to wtedy jest bug.

**Comment by kadi2** [comment]
Moze jest to minor, ale czy nie powinno to poprostu skracac czasu channelowania spella?

**Comment by Jenovas** [comment]
A skąd spell ma wiedzieć ile masz celów w zasięgu i ile osób wejdzie bądź wyjdzie z zasięgu? Mając 3 cele będzie leczył całe 8 sekund, a mając 5 będzie leczył 4 sekundy. Haste nie powinien mu skracać czas powinien dodawać ticki.

**Comment by Meteora11** [comment]
Faktycznie ticków jest 20, mój błąd sugerowałam się działaniem Hymnu z WoTKL.
