### ISSUE TITLE
[PL][Shaman][spell] Earthquake dmg

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#2098]
Spell Earthquake bije za malo. Z opisu spella wynika ze tick powinien bic po 1210, a bije po 840. Wymaga delikatnego boosta do dmg.

http://www.wowhead.com/spell=61882/earthquake

**Comment by Kejmil** [comment]
Earthquake to physical dmg, redukowany przez armor. Przyjmujac 30% armora 1210*0,7=847, dmg jest prawidlowy

**Comment by mrkariox** [comment]
"Valyndyral on 2010/09/30 (Patch 3.3.5)
It's physical, but it doesn't get mitigated by armor, nor is it subject to dodging, blocks or parries. In general, it is all the benefits of physical damage with none of the drawbacks."

Komentarze z wowheada. To jest spell ktory tylko zadaje fizyczny dmg. SPELL nie atak, wiec armor omija.
