### ISSUE TITLE
[EN][Hunter][Transmog] Range Weapon

### ISSUE THREAD

**Issue by grayfox764** [Atlantiss/BugTracker#210]
you can't transmog a gun into a bow, and as far as i know, transmog works so you can transmog any range weapon into another one, bow to crossbow, gun to bow, bow to gun, etc.

**Comment by Tj20** [comment]
I can confirm this now that transmog is live. You can transmog guns into xbows and xbows into guns, but bows you can only transmog into other bows.

xbow -> xbow
xbow -> gun
~~xbow -> bow~~

gun -> gun
gun -> xbow
~~gun -> bow~~

bow -> bow
~~bow -> xbow~~
~~bow -> gun~~

Normally you should be able to transmog every range weapon type in every range weapon type, see [blue post](http://us.battle.net/wow/en/forum/topic/3196342583).

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
