### ISSUE TITLE
[EN]Visual bug

### ISSUE THREAD

**Issue by Archeist** [Atlantiss/BugTracker#2101]
Hello! I want to report an visual bug. I went to the BH 25 people and after i've done it my calendar shows me cooldown for BH 10. I hope u can fix this.

**Comment by xolon** [comment]
All cataclysm raid mods share same lock
If you do BH on 25 it saves you on both 25 and 10 etc.

**Comment by Archeist** [comment]
Okey sorry to bother You than.
