### ISSUE TITLE
[EN][Quest] Quest Texts

### ISSUE THREAD

**Issue by nt32** [Atlantiss/BugTracker#2102]
I am a lvl 16 dwarf questing in Loch Modan currently. So far every quest i have completed including ones in Dun Morogh has some text issues. I dont know if its server or my client, if its server:
Quests with objects after completing that objects show the return text as completed instead of object.
And as a completed quest should show return text instead they show quest object as text.
Example: Gathering Idols (Loch Modan)

Text that shown as completed after gathering idols: "Return to Magmar Fellhew at Ironband's Ecavation. (Complete)", "Carved Stone Idol: 8/8 (Complete)"(note that only this one should be completed)

Text that should tell what to do after completing quest: "Bring 8 Carved Stone Idols to Magmar Fellhew at Ironbard's Excavation." Which is actually the quest text instead of this "Return to Magmar Fellhew at Ironband's Ecavation." should be shown as text

This is by no means an urgent issue or a major one I just find it annoying and wanted to report if it has an easy fix I would really appreciate it when you have time. Thank you

**Comment by Bildo** [comment]
bt rules
