### ISSUE TITLE
[EN][NPC][Deepholm] Stone Trogg Fungalmancer

### ISSUE THREAD

**Issue by Canderous** [Atlantiss/BugTracker#2104]
Stone Trogg Fungalmancers are supposed to drop nothing (see wowhead comment), but sometimes they drop Heartblossoms and Cinderblooms, making it possible to farm these for the herbs. 
http://www.wowhead.com/npc=47184/stone-trogg-fungalmancer
http://www.wowhead.com/item=52983/cinderbloom
http://www.wowhead.com/item=52986/heartblossom

Also, as a sidenote, they do not cast their ability "Fungal Decay" and have no staff in their hands (minor visual issue).
http://www.wowhead.com/spell=32065/fungal-decay

**Comment by Bildo** [comment]
Fixed by Navedonar:
