### ISSUE TITLE
[EN][Quest][Zone] Deepholm, Alliance Gunship

### ISSUE THREAD

**Issue by crashcoreks** [Atlantiss/BugTracker#2105]
The Alliance Gunship on deepholm is more or less bugged.
Whenever I try and quest on it, I fall into some random place in the "Abyssal Maw" and I can't release my spirit. This is really annoying as I need to finish the quests here to unlock Therazene daily quests (And so do many others)

**Comment by MasterK15** [comment]
Yep i think its problem when Shit travel full road and teleport back to his first possition

**Comment by KrolServera** [comment]
I think it was already reported.

**Comment by Aival94** [comment]
Maybe is sth about its height when it fly as we teleported higher than we normal do(maybe it try to send us out of deepholm but instead it send us somewhere between deepholm and the surface of maelstorm
