### ISSUE TITLE
[EN][Instance-Classic] Zul'Farrak

### ISSUE THREAD

**Issue by Canderous** [Atlantiss/BugTracker#2106]
# Loot
*  Every boss should always drop exactly 1 item from its loot table. Right now each item has a separate drop chance, so every boss can drop any number of loot from 0 to all of them.
    *  [Antu'sul](http://www.wowhead.com/npc=8127/antusul)
    *  [Witch Doctor Zum'rah](http://www.wowhead.com/npc=7271/witch-doctor-zumrah)
    *  [Shadowpriest Sezz'ziz](http://www.wowhead.com/npc=7275/shadowpriest-sezzziz)
    *  [Chief Ukorz Sandscalp](http://www.wowhead.com/npc=7267/chief-ukorz-sandscalp)
    *  [Gahz'rilla](http://www.wowhead.com/npc=7273/gahzrilla)

# Stair Event
* <del>The [Sandfury Executioner](http://www.wowhead.com/npc=7274/sandfury-executioner) does not have a 100% chance to drop [Executioner's Key](http://www.wowhead.com/item=8444/executioners-key), so the stair event can not be started sometimes. This is related to the next issue.

*  Since the stair event can't be started all the time (or maybe for some other reason), currently there is a [Shadowpriest Sezz'ziz](http://www.wowhead.com/npc=7275/shadowpriest-sezzziz) and a [Nekrum Gutchewer](http://www.wowhead.com/npc=7796/nekrum-gutchewer) spawned initially, without the need to do the event. They should be removed once everything else is working perfectly.

*  <del>During the stair event, dead mobs can be chosen as the "next wave", and if they are chosen, their corpses will start moving up the stairs. Only living mobs should be chosen.

*  <del>The door leading to [Chief Ukorz Sandscalp's](http://www.wowhead.com/npc=7267/chief-ukorz-sandscalp) room is open by default, once everything is fixed, it should be closed by default, and should be opened only by talking to [Weegli Blastfuse](http://www.wowhead.com/npc=7607/weegli-blastfuse). The talk option is here right now and the goblin moves normally when interacted with (with placeholder texts though), so it is possible the script already works, but the door is already open, so nothing happens.

# [Chief Ukorz Sandscalp](http://www.wowhead.com/npc=7267/chief-ukorz-sandscalp) & [Ruuzlu](http://www.wowhead.com/npc=7797/ruuzlu)
*  Their pathfinding is bugged, once aggroed, they can not move off their initial positions, making for an easy kill with ranged. I remember it working some time ago (during 4.0.6), so maybe some recent changes broke the pathfinding. An easy fix would be to place them off the stairs and on the sand.
![ukorz](https://cloud.githubusercontent.com/assets/9568075/6096256/e684bba2-af87-11e4-9e2a-dcf57b7b5c7a.jpg)

**Comment by Maczuga** [comment]
bump, the key drop is a pretty issue while leveling.

**Comment by sunshineinabox** [comment]
The key drop isn't needed anymore, but you don't need to do the stairs event the bosses are already spawned at the bottom.

**Comment by TheCopacabanaMan** [comment]
The stair event starts regularly, just "reset all instances" before entering dungeon.
Just Gahz'rilla dont spawn...
