### ISSUE TITLE
[PL][Guild] Guild Bank Crash

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#2108]
Gdy otwieramy guild bank gra crashuje. Gdy uda nam się go otworzyć crash występuje po zmianie strony w GB/ podczas przeglądania/ po zamknięciu Guild banku

Co tu dodać ? plik textowy z Error folderu ?

**Comment by Asavel** [comment]
linknij all itemy co sa ;D

**Comment by MasterK15** [comment]
Tu nie chodzi o jeden guild bank tylko wgl guild bank wszystkich/wiekszosci gildii, mi si to zdarzylo na 4 postaciach z 4 gidiami 
wiec to nie kwestja jednej gildii tylko wiekszej liczby, ps nie tylko mi bo innym ludzia z gildi tez wywala errora

**Comment by Bildo** [comment]
mi nie wywala a mam 8 tabow w gildii, moze jakis item crashuje ktory jest w bagu dlatego powiedzial aby linknac itemy

**Comment by adryjan** [comment]
Często się zdarza, u mnie to występuje raz na 10 razy gdy otwieram bank, innym natomiast 9 na 10. Coś z addonami sie moze gryzie nie wiem.

**Comment by MasterK15** [comment]
Co do addonow to nawet z wylaczonymi mam ten problem

**Comment by raaq** [comment]
u mnie jest 1/2. Za pierwszym otworzeniem error, po włączeniu wowa i włączeniu GB error nie wyskakuje albo wyskakuje z opóźnieniem od 20s do mniej wiecej 3 min.

**Comment by Aival94** [comment]
I do not know it this is related or just luck but when i have any buff in my char and try to open guild bank i crash all the times.

Note:I have some errors files but do not know how to upload them here.

**Comment by Avalain** [comment]
Ostatnimi czasy również i mnie wyskakuje error#132 po otwarciu lub zamknięciu okna banku.
Usunąłem całe foldery: Interface, Catche, WTF oraz pobrałem Game Client z Atlantiss (mini).
Nic w swoim systemie nie zmieniałem, a crashe pojawiły się od dosyć niedawna.

**Comment by aje** [comment]
can you give the full error message please
