### ISSUE TITLE
[EN][Professions] Leatherworking

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#211]
Leather working isnt working properly there is no + for separating the groups in leather working and when you hit the + for all nothing happens

![wowscrnshot_110614_120110](https://cloud.githubusercontent.com/assets/4362814/4940945/50a28eb2-65df-11e4-8e38-b2bff51c7dcf.jpg)

**Comment by user1011** [comment]
I tested this in game and it works fine for me, only when I close a tab far down it makes me go up all the way.
