### ISSUE TITLE
[EN][Spell][Paladin] Avenger shield inflicts silence

### ISSUE THREAD

**Issue by idontknow12** [Atlantiss/BugTracker#2110]
On my level 26 tauren paladin, avenger shield is inflicting silence on targets (mobs). Haven't tested on players.

Revision 4308

edit- no talents affecting the spell that i know of.

**Comment by Tj20** [comment]
You mean the spell is doing exactly what it's supposed to do?

Shocking... :D

**Comment by idontknow12** [comment]
Oh wow, the in-game tooltip doesn't mention that. But i see that wowhead does.. /shrug
![avenger shield](https://cloud.githubusercontent.com/assets/10792691/6097539/bebf19fc-afa8-11e4-85af-3e047e050681.jpg)

**Comment by Tj20** [comment]
Maybe you have Beginner Tooltips enabled? They don't show you everything a spell does, but only some basic information.

You can turn them off under Interface > Help > Beginner Tooltips

**Comment by idontknow12** [comment]
Oh this is embarrassing.. yeah that was it. I've been looking for that option for a while also..

This can be closed! Thanks.
