### ISSUE TITLE
Buff does not go away

### ISSUE THREAD

**Issue by juwzero** [Atlantiss/BugTracker#2114]
One day I accepted one quest and it gave me 2 "buffs" called "combat training" and "farmers militia". I deleted the quest a week or more ago and the buffs wont go away. I also checked my bag for any quest items and there arent any. Naturally I also tried clicking on them but no luck.

I asked on the forum and one player had the exact problem and had to write a ticket.

It isn't a big problem but it's getting kind of annoying.

Keep up the good work Atlantiss!

here's the print screen of the buffs:
http://i.imgur.com/GvBl3OV.png

**Comment by juwzero** [comment]
One day I accepted one quest and it gave me 2 "buffs" called "combat training" and "farmers militia". I deleted the quest a week or more ago and the buffs wont go away.  I also checked my bag for any quest items and there arent any. Naturally I also tried clicking on them but no luck.

here's the print screen of the buffs:
http://i.imgur.com/GvBl3OV.png

**Comment by Bildo** [comment]
bt rules
