### ISSUE TITLE
[PL][Raid] ID onyxia etc

### ISSUE THREAD

**Issue by jurek1** [Atlantiss/BugTracker#2122]
zrobilem onyxie i os ( mam id ale pisze ze boss jest available ) , moge znowu isc na te raidy , wystarczy ze raid leader ma czyste id 
mozliwe ze owy blad jest takze na innych raidach , nawet cata.. 

ps  to zjawisko ma raczej kazdy

**Comment by Alandiel** [comment]
Nie występuje w przypadku raidów cata.

**Comment by mitim1** [comment]
Występuje tylko na Onyxi i osie.

**Comment by jurek1** [comment]
robilem tez toca hc i tez pisze ze bossy available

**Comment by arekczup** [comment]
ja użyłem heal bota ze ui loadowałem to mogłem z 2 razy pujść na za i zg
