### ISSUE TITLE
[EN] Set doesn't save

### ISSUE THREAD

**Issue by Archeist** [Atlantiss/BugTracker#2125]
Hello. I have a problem with my item set i mean i make them and after a relog they dissapear. It's not only my issue i asked people on world and they have the same problem.

**Comment by Haffyd** [comment]
Equip menager don't work ;p

**Comment by Archeist** [comment]
Is there any hope that it will be fixed

**Comment by Tj20** [comment]
Eventually, I guess. You can however use addons like "Outfitter" or "ItemRack" which were there before Blizz decided to do their own equip manager with patch 3.1 and they also have more options.
