### ISSUE TITLE
[EN] [Dungeon-Cata] Throne of the Tides

### ISSUE THREAD

**Issue by PatriotasLT** [Atlantiss/BugTracker#2126]
When you try go to Mindbender Ghur'sha you get crashes wich show error 132. Hapened 5 times for all grupe members. Mostrly when you start kiling trash mobs in corridor
![throne of the tides](https://cloud.githubusercontent.com/assets/10769064/6102405/9fa24490-b03e-11e4-9446-e6922bd6882f.jpg)

**Comment by BAndysc** [comment]
Confirm. Big problem since this is cata content.

**Comment by Alandiel** [comment]
Maybe someone in your pt used disengage/blink or something like that when trash was pulling you.

**Comment by Varchord** [comment]
Already exist
https://github.com/Atlantiss/BugTracker/issues/1156
