### ISSUE TITLE
[PL] BWD Omnotron System Defense

### ISSUE THREAD

**Issue by alurrr** [Atlantiss/BugTracker#2127]
Wczoraj podczas bicia omntrona zbilismy bossa do 324k hp i sie nam ich hp zresetowalo. Nie wiem czy to jakis bug czy nie przejmowac sie tym

**Comment by Qwers** [comment]
To samo mieliśmy w sobotę. Bijemy bossa, zbijamy do ok. 10%-20% (dokładnie nie pamiętam, ale niewiele już zostało do zbicia), a tu nagle mają full HP. Dodam, że robiliśmy na 10n i nikt na 100% nie wyszedł poza salę. Oczywiście encounter się nie zresetował, zresetowało się tylko HP i trzeba było zbijać jeszcze raz.

**Comment by Qwers** [comment]
asdad

**Comment by mitim1** [comment]
dubel #1159
