### ISSUE TITLE
[EN][Quest][CoT][Old Hillsbrad] Escape from Durnholde

### ISSUE THREAD

**Issue by cookienator152** [Atlantiss/BugTracker#2129]
http://www.wowhead.com/quest=29599/escape-from-durnholde

The option to tell Thrall to start walking is gone. I did this the day before, and in the middle of the quest server crashed, after which nothing - resetting instances, doing both norm/heroic, abandoning and taking the quest again - helps with the issue, thus renders the quest not completable (and it is needed to get into Black Morass for alchemy spec quest).

**Comment by Tj20** [comment]
Btw, since patch 4.3 the Black Morass should be unlocked by default without prequests. Currently it isn't though, see issue: #579

**Comment by meta1** [comment]
after dc u need to start again event with planting bombs in baracks and then u will be able to talk with thrall and start journey, dont need to reset instance just plant bombs again for me works did  few days ago

**Comment by Tj20** [comment]
Ooh... did you not try that? That's true, you have to start all over again, incuding planting the mobs. I did it like 2 weeks ago and it worked indeed then.

**Comment by cookienator152** [comment]
Ok, planting the explosives on the barrels again allowed that dialogue option - thanks for the tips :).

**Comment by armano2** [comment]
duplicate: #1768
