### ISSUE TITLE
[PL][Spell/talent][Mage] Fingers of Frost - Deep Freeze

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#2130]
Deep freeze uzyty na fingers of frost przy 2 jego stackach zabiera nam 2, przy 1 stacku FoF dziala poprawnie, oczywiscie powinno zabierac 1 stack
http://wow.gamepedia.com/Fingers_of_Frost

**Comment by Arcadia713** [comment]
Potwierdzam, deep freeze uzyty na graczach zabiera dwa ladunki FoF zamiast jednego. Na maszynach/bossach jest ok.
http://www.wowhead.com/spell=44572/deep-freeze
http://www.wowhead.com/spell=112965/fingers-of-frost

**Comment by blinkmaster** [comment]
bump :<

**Comment by Wolffenstein** [comment]
Fixed in rev 4330.
