### ISSUE TITLE
[EN][Quest][Ungoro Crater] The Spirits of Golakka Hot Springs

### ISSUE THREAD

**Issue by darklord88** [Atlantiss/BugTracker#2131]
I finished this quest http://www.wowhead.com/quest=24704/the-evil-dragons-of-ungoro-crater without the npc what the quest given on the start, i lost him.I cant do the next quest because the npc who helping missing now.
http://www.wowhead.com/quest=24706/the-spirits-of-golakka-hot-springs There is nothing option recall him again.

**Comment by Bildo** [comment]
duplicate
