### ISSUE TITLE
[EN][Druid][Spell] Skull Bash

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#2139]
skull bash should not work in roots, its a "charge spell"
now it consumes the cd without the charge but it can be abused as an interrupt which you shouldn't be able to do in roots.
http://wow.gamepedia.com/Skull_Bash

http://www.mmo-champion.com/threads/929123-Skull-Bush-vs-Alysrazor-adds?p=12062797

"Slightly Off-topic here, but anyone know anything about Skull Bash not being usable whilst rooted? Is that intended?

I know it's a "charge" thing, but when in melee range it's quite annoying not being able to interrupt. >.>"
"Doesn't SOUND like it should be intended - but...Blizzard works in mysterious and usually strange ways."

http://eu.battle.net/wow/en/forum/topic/1549436214
"Make Skull Bash usable while rooted (not so it breaks roots, so we can interrupt people next to us in roots who cast).
19/01/2011"

**Comment by kadi2** [comment]
Skull Bash in roots should be usable only when you stay in melee range to the target.

**Comment by blinkmaster** [comment]
read the comments its not. if u have proof give it.

**Comment by kadi2** [comment]
A:"You can't use skull bash at all when you're rooted, even if your target is right next to you."
B:"I have definitely interrupted players while rooted."

The problem on the server is that you shouldn't be able to use skull bash while rooted OUTSIDE melee range.

**Comment by Iambugged** [comment]
Another thing I found out about it is that it sometimes doesn't charge to your target even if it interrupts (not rooted).
Can't be 100% sure but I think it has something to do with target running out of range the moment you use skull bash.

**Comment by Jenovas** [comment]
Fixed in rev 4831
