### ISSUE TITLE
[PL][Spells][Core][High Priority] Absorb

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#2144]
Absorby w rev. 4314 nadal nie działają poprawnie.

Backstab crit bez odpałek w "czystego" maga (bez absorbów): 10710 dmg (http://wstaw.org/m/2015/02/10/non_absorb.jpg)
Backstab crit bez odpałek w Ice Barrier: 22746 dmg - 5953 weszło, 16793 zaabsorbowane (http://wstaw.org/m/2015/02/10/absorb.jpg)

Ice Barrier absorbuje wg. tooltipa 18129 dmg - http://wstaw.org/m/2015/02/10/ib.jpg

Wniosek: Absorby zwiększają obrażenia jednocześnie je absorbując, jednak wychodzi na to samo co było przed poprawką - gdyby backstab critnął jak normalnie crituje za ~11k w maga z Ice Barrier, to powinno zabsorbować tą ilość i jeszcze około 7k barriery zostać. 
To wszystko dotyczy każdego spella dającego immune jakiejś wartości.

http://www.wowhead.com/spell=11426/ice-barrier
http://www.wowhead.com/spell=35064/mana-shield
http://www.wowhead.com/spell=17/power-word-shield

**Comment by Wolffenstein** [comment]
4315
