### ISSUE TITLE
[PL][Spell][Paladin] Hand of Sacrifice

### ISSUE THREAD

**Issue by Unn90** [Atlantiss/BugTracker#2146]
http://www.wowhead.com/spell=6940/hand-of-sacrifice#comments
http://www.wowwiki.com/Hand_of_Sacrifice
http://wow.gamepedia.com/Hand_of_Sacrifice

Gdy użyje skilla na friendly target dmg jest transferowny na mnie, ale niestety nie wyjmuje mnie z żadnego Crowd Control kiedy otrzymuje owy dmg.
Dla przykładu Arena 2v2: rzucam na mejta HoS, gramy na maga, mag daje mi poly i bije mojego mejta z aktywnym HoSem dmg jest transferowany z niego na mnie, poly mi nie schodzi nie jest zbijane a powinno. To samo testowałem z blindem i sapem mimo otrzywywanego dmg z HoS stoje w cc.
Skill powinien łamać/wyjmować z wszystkiego rodzaju cc u nas niestety nie działa to.

**Comment by Varchord** [comment]
http://eu.battle.net/wow/en/forum/topic/2624879182

**Comment by Jenovas** [comment]
Fixed in rev 4408
