### ISSUE TITLE
[EN][Quest][Eversong Woods] Unstable Mana Crystals

### ISSUE THREAD

**Issue by Kubion** [Atlantiss/BugTracker#2149]
http://www.wowhead.com/quest=8463/unstable-mana-crystals

1. I couldn't take the quest item without autoloot because loot window disappeared too fast. We must have a while to take it.
2. I'm not sure that Wretched Urchin should drop quest item. http://www.wowhead.com/npc=15644/wretched-urchin I checked it and they don't have this item on drop list.

**Comment by Atyors** [comment]
With or without autoloot it seems that the crates are empty.

**Comment by Bildo** [comment]
fixed
