### ISSUE TITLE
[EN][Instance][Black Morass] Time Rift Spawn Timers

### ISSUE THREAD

**Issue by Sonicberry** [Atlantiss/BugTracker#2155]
http://www.wowhead.com/zone=2366/the-black-morass
The time rift spawn timers are incorrect for Black Morass in both Normal and Heroic Difficulty. There should be a waiting period only after clearing waves 6 and 12, but instead there is a waiting period after every wave from wave 7 onward.

**Comment by Axahus** [comment]
Confirm. After 7th rift we must wait 1:30-1:45 for next rift.
