### ISSUE TITLE
A blight upon the land

### ISSUE THREAD

**Issue by CrepX** [Atlantiss/BugTracker#2156]
Hello , recently I've stumbled upon the forsaken quest called ,, A blight upon the lang ,, In which you have to kill Warden Stillwater . The problem is he's an npc , so I can't attack him , and now I have 2 idiots following me and triggering mobs ... So if you could fix it , I would be very  greatful .

**Comment by arekczup** [comment]
link wowhead openwow ?

**Comment by Wolffenstein** [comment]
Already reported.

**Comment by CrepX** [comment]
Oh ok good to know , thanks anyways .
