### ISSUE TITLE
[EN][Mage][Spell] Living bomb, Cauterize

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#2157]
Living bomb -> Has no restrictions on number of targets 
Patch 4.0.1 (12-Oct-2010): This spell can be cast on a maximum of 3 (!!!) targets at a time.

Cauterize -> When we get sufficient damage to death, and in addition they are much larger that we are healed more than 40%, depending on how many we got damage. Simple example - meteor on Valiona HC hit us and cauterize heal us to 100% hp.

**Comment by Varchord** [comment]
wowhead links

**Comment by Asavel** [comment]
http://www.wowhead.com/spell=44457/living-bomb#changelog

**Comment by NONLIFE** [comment]
What about http://www.wowhead.com/spell=86622/engulfing-magic#changelog ?

**Comment by Varchord** [comment]
1 Bug, 1 issue

**Comment by Caturix** [comment]
I can confirm both bugs, tested them out myself.

**Comment by Jenovas** [comment]
Living Bomb fixed in rev 4356
