### ISSUE TITLE
[PL][NPC][CORE] Faldren Tillsdale, Jamus'Vaz (Wymiana VP na CP)

### ISSUE THREAD

**Issue by Unn90** [Atlantiss/BugTracker#2158]
http://www.wowhead.com/npc=46556/jamusvaz#comments:id=1433384
"Conquest points can be purchased in stacks of 250 from Faldren Tillsdale (Alliance) or Jamus'Vaz (Horde) in exchange for 250 Valor Points. (...)"

http://wow.gamepedia.com/Patch_4.1.0
"General: Conquest is now purchasable from the Valor vendor at 250 Conquest per 250 Valor."

http://www.wowhead.com/npc=44245/faldren-tillsdale 
http://www.wowhead.com/npc=46556/jamusvaz

Oba NPC nie sprzedają/wymieniają 250 Conquest pointsów za 250 Valor Pointów. Wraz z patchem 4.1 weszła taka możliwość z tego co wiem to wymiana JP <=> Honor działa lecz niestety CP za VP nie.

**Comment by docc46** [comment]
bump, pretty essential thing

**Comment by Unn90** [comment]
bump ;/
