### ISSUE TITLE
[PL][Paladin][Spell]Crusader Strike

### ISSUE THREAD

**Issue by fixpalbugsomg** [Atlantiss/BugTracker#2159]
http://www.wowhead.com/spell=35395/crusader-strike

jak dziala? nie zawsze nabija holy powera nie robiac nic
jak powinno dzialac? oczywiste, nabijac 1-3 holy power (zalezy czy zealotry wlaczone) oraz robic dmg

**Comment by Varchord** [comment]
tytuł

**Comment by Jenovas** [comment]
A może miss miałeś na crusader strike? Powinien wbijać nawet na missach holy power?

**Comment by Varchord** [comment]
Nie powinien wbijać Holy Power przy miss. Żaden spell generujący Holy Power nie powinien go na miss wbijac

**Comment by fixpalbugsomg** [comment]
coz, posiadam hit capa wiec o missie nie ma mowy..
jeszcze podobny bug znalazlem co do divine purpose.

**Comment by kadi2** [comment]
Na poprzednim bug trackerze wklejalem troche info o tym, ze nie powinien generowac HP przy dodge/parry/immune/miss

**Comment by redoXe** [comment]
CS działa dobrze, nie wiem o co Ci chodzi w tym temacie
