### ISSUE TITLE
[PL][Paladin][Talent] Divine Purpose

### ISSUE THREAD

**Issue by fixpalbugsomg** [Atlantiss/BugTracker#2160]
http://www.wowhead.com/spell=86172/divine-purpose
jak dziala? czasami zamiast nie zabierac holy powera zbiera 1
jak powinno dzialac? oczywiste, nie zbierac holy powera

**Comment by Varchord** [comment]
tytuł

**Comment by Jenovas** [comment]
Na czym to testowałeś?

**Comment by fixpalbugsomg** [comment]
właściwie na wszystkim... szczególnie jest to odczuwalne przy biciu bossów, gdy widząc że procuje mi się divine purpose zamiast nie zbierać holy powera to zabiera 1 co utrudnia dosyć komfortowe dpsowanie.

**Comment by Psychobird7** [comment]
Can someone translate this? I don't think DP is bugged, at all.
