### ISSUE TITLE
[PL] Raid ID 

### ISSUE THREAD

**Issue by Liska23** [Atlantiss/BugTracker#2161]
Wczoraj robiłem Bastion of Twilinght i nie zresetowało sie ID tak samo sie dzieje z niektórymi instancjami robi sie je a następnego dnia na jedne CD sie resetuje na inne nie

**Comment by Drutmaster** [comment]
W skrócie, bug z id ciągle jest :/

**Comment by Nc94** [comment]
To samo dzieje się z ID na rhc. Żeby zrobić HoO na rogalu muszę czekac po 2-3 czasami aż mi ID zresetuje.

**Comment by arekczup** [comment]
ja zrestartowałem sobie ui przed daugeon cata z heal bota jak zrobiłem z 3 bossy i wróciłem na wcześniejsze ui to znowu mogłem robić tą inste :]
