### ISSUE TITLE
[PL][NPC] Lost City of the Tol'vir

### ISSUE THREAD

**Issue by Morrdok** [Atlantiss/BugTracker#2164]
Witam, aby móc bić Siamat, nalezy zabic General Husam oraz High Prophet Barim, Lockamaw jest bosse-em opcjonalnym, znaczy to zeby moc podejsc do Siamat nie trzeba go zabijac.
Na Atlantisie, natomiast nalezy zbic waszystkie bossy, by moc podejsci do Siamat.

"...Lockmaw is the third - and optional - boss in the Lost City of the Tol'vir..."
http://www.wowhead.com/npc=43614/lockmaw

**Comment by arekczup** [comment]
Nie ja z grupą ubiłem tylko pierwszego bosa i pokazywał mi się wir po nim.
wtedy zabijałem siamat bez zbędnych bosów z nie zniszczonym budynkiem.

**Comment by arekczup** [comment]
ja ubijałem bosa 1 i pokazywał mi się wir do siamanta bez zniszczonego budynku nie wiem czy teraz tak jest ale zabijałem go bez zabicia 3 bossów.
