### ISSUE TITLE
[PL][EN][Item - Scrolls] Scroll of Stamina/Strength not stacking

### ISSUE THREAD

**Issue by redoXe** [Atlantiss/BugTracker#2168]
[PL] Scroll of Stamina liczy się jako Guardian Elixir, natomiast Scroll of Strength liczy się jako Battle Elixir, więc oba te scrolle powinny być możliwe do jednoczesnego użytku na postaci - zamiast tego scrolle te nawzajem się zbijają/ściągają (można mieć na sobie tylko jeden scroll, strength lub stamina, a powinno można mieć oba)

[EN] Scroll of Stamina counts as Guardian Elixir, while Scroll of Strength counts as Battle Elixir, therefore both of these scrolls should be able to use simultaneously on your toon - instead both of the scrolls are discarding each other (you can have only one of them on your toon, while you should be able to be buffed by both stamina and strength)

Scroll of Stamina - http://www.wowhead.com/item=1180/scroll-of-stamina 
["This effect counts as a Guardian Elixir."]

Scroll of Strength - http://www.wowhead.com/item=954/scroll-of-strength 
["This effect counts as a Battle Elixir."]

Battle Elixir - http://www.wowwiki.com/Battle_Elixir
Guardian Elixir - http://www.wowwiki.com/Guardian_Elixir

UZASADNIENIE/SUBSTANTIATION: Players can only have one Guardian Elixir and one Battle Elixir active on them at one time, or one Flask, which counts as both Elixir slots.

**Comment by jurek1** [comment]
a czasem te scrolle nie stackuja sie z buffem na stame/str?

**Comment by redoXe** [comment]
Buffy i scrolle są niezależne i nie mają żadnego wpływu na zgłoszony tutaj bug. Jedynym scrollem, który nie stackuje się z buffem (konkretnie ze staminą od preja) jest Scroll of Fortitude, który działa dobrze, gdyż się zbija ze staminą od preja. Ale jak już wspomniałem to nie wnosi nic do tematu. Wszystko jest opisane w pierwszym poście.

**Comment by jurek1** [comment]
moze nie wnosze do tematu nic ale chce zapytac , daje sobie scroll na str potem daje buffa dk horna i scroll znika ; d  tak powinno byc ?

**Comment by redoXe** [comment]
Raczej nie.. Ogólnie coś ze scrollami jest schrzanione i trzeba by się temu bliżej przyjrzeć, dlatego zrobiłem ten topic..

**Comment by qolo** [comment]
Tak samo działają eliksiry, na przykład gdy próbuje nałożyć Elixir of Intellect (battle) na Troll's Blood'a (guardian), to mam tylko Intellect.

**Comment by lamaATS** [comment]
Fixed in rev. 5224
