### ISSUE TITLE
[EN][CORE]Pet bar and pets' commands.

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#2173]
After pets move to command fix, I noticed new bug. The core doesnt save the pets' commands we have just dragged to the pet bar. After every game load, or pet dismiss, all pets' commands that were put in the bar dissapear, so you have to set them over and over again. For example: I want to replace 'follow' command with newly fixed 'move to' command – everything works ok but after game load or pet dimiss and calling it again the 'move to' command will disappear leaving the slot in pet bar empty.

**Comment by xolon** [comment]
duplicate
btw. this was happening before move to command got fixed

**Comment by ShockRW** [comment]
Is this duplicate? I cannot find it somehow. If you talkign bout this: https://github.com/Atlantiss/BugTracker/issues?q=is%3Aissue+is%3Aopen+pet+bar, I doubt that you can call it duplicate since there is almost no info. So if this was happening before the fix, it means that move to command fix is usless because we cant use it anyway, at least ppl that created character before 4.3.
