### ISSUE TITLE
[ENG] Always in combat bug

### ISSUE THREAD

**Issue by okevino25** [Atlantiss/BugTracker#2179]
it seems that whenever i finish a fight, i cant equip items or eat/drink nor logout, in my character portrait thought, it does not appear in red designating that i am in combat but when i want to do any of those actions metioned before, the game refuses, telling me that i am in combat..... my charecter is a night elf (might help out) i do not know if anyother races/zones react this way

**Comment by okevino25** [comment]
why has this been closed?

**Comment by Rushor** [comment]
dublicate
