### ISSUE TITLE
[PL][Death Knight][Unholy][Pet] Ghoul/Character HP

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#2187]
Podczas zmiany presence z Unholy na Blood i odwrotnie nasz ghoul traci hp.
z Glyph of Raise Dead
- z Unholy na Blood do 38%
-  z Blood na Unholy do 40%

bez Glyph of Raise Dead
- z Unholy na Blood do 53%
-  z Blood na Unholy do 55%

Sprawa jest taka sama gdy pet dostaje buff Blessing of Kings. 
Inne buffy wymagają jeszcze sprawdzenia.

*Wychodzi na to, że glyph działa prawidłowo i sprawa leży gdzieś głębiej.
*Pety, które nie są pod naszą kontrolą (czyli przyzywane we frost i blood specu) nie tracą hp.

Blood Presence - http://cata.openwow.com/spell=48263
Unholy Presence - http://cata.openwow.com/spell=48265
Glyph of Raise Dead - http://cata.openwow.com/item=43549
Master of Ghouls - http://cata.openwow.com/spell=52143
Blessing of Kings - http://cata.openwow.com/spell=20217

Dodatkowo zmieniając bronie (w tym przypadku Vicious Gladiator), które mają takie same statystyki, hp postaci spada ze 100% do 94%. Dzieje się to tylko w przedziale 94 - 100% hp. W każdym innym przypadku hp postaci zostaje prawidłowo stałe.

**Comment by Haffyd** [comment]
Jakakolwiek zmiana naszego Hp (zmiana itemku, presence, buff itp.) sprawia, że pet instantowo traci ~60% hp

**Comment by Jenovas** [comment]
Fixed
