### ISSUE TITLE
[EN] [Quest] [Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by biceryen** [Atlantiss/BugTracker#2189]
Didn't see this reported anywhere. Also not 100% sure about how descriptive I have to be.

But in Soothing the Elements in Darkshore, you get to a point where you have to use the item [Energized Soothing Totem] and then defend supposedly three waves of enemies. However, after using it, you only get one wave of one enemy and then no more spawn. Making the quest impossible to continue.

And if possible, I wouldn't mind having my quest advanced due to this problem. So I can continue with this quest line. Not sure how to contact a GM, or if that service is allowed.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1521
