### ISSUE TITLE
[ENG][Quest][Howling Fjord] The Jig is Up

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2193]
http://www.wowhead.com/quest=11471/the-jig-is-up
https://www.youtube.com/watch?v=ys1pV96qatA

The combat is not scripted. You have to fight "Mad" Jonah Sterling (http://www.wowhead.com/quest=11471/the-jig-is-up) till he is almost dead, he will flee by jumping through the feeding hole. Hozzer will attack and swallow him and by this he acquires "Jonah Sterling's Spyglass" (http://www.wowhead.com/item=34128/jonah-sterlings-spyglass) needed for the quest. It shouldn't be in his possession before this.

Also Hozzer did fall asleep in the middle of combat.

**Comment by Technowizard15** [comment]
Update: "Jonah Sterling's Spyglass" (http://www.wowhead.com/item=34128/jonah-sterlings-spyglass) should be a guaranteed/100% drop if you have the quest according to:
http://eu.battle.net/wow/en/item/34128

**Comment by Navedonar** [comment]
drop fixed

**Comment by Tj20** [comment]
dublicate: #1761

Btw, I just did this and can confirm that Hozzer drops the Spyglass fine now.

**Comment by Technowizard15** [comment]
That happens if people don't use the right names for their reports.
