### ISSUE TITLE
[ENG][Quest][Howling Fjord] The Lost Shield of the Aesirites

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2194]
http://www.wowhead.com/quest=11519/the-lost-shield-of-the-aesirites

1.: The ladder to the ship (http://wow.zamimg.com/uploads/screenshots/resized/238417.jpg) is missing.

2.: The NPCs on board constantly appear and disappear depending on the angel of the ship.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1877
