### ISSUE TITLE
[ENG][Item] Black Conrad's Treasure

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2195]
Opening Black Conrad's Treasure (http://www.wowhead.com/item=34119/black-conrads-treasure#contains) the reward from the quest "Dead Man's Debt" (http://www.wowhead.com/quest=11467/dead-mans-debt) I got an error about an empty slot and no loot. Because of the great list of possible loot this is statistically almost impossible and points to a bug in the loot table. By the way, I had 13 empty slots in my inventory at that moment.

**Comment by Navedonar** [comment]
fixed soon
