### ISSUE TITLE
[PL][Herbalism] Frozen Herb

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#2197]
http://www.wowhead.com/object=190173/frozen-herb   Czasem po zebraniu rośliny nic nie dostajemy. Jeżeli info z wowheada jest aktualne to powinno dropić od 2-8 roślin a u nas dropi od 0-8

**Comment by MasterK15** [comment]
DUMP

**Comment by Thefakemccoy** [comment]
Can target herbs and attempt to collect. You get the skill point from collecting them but no herbs in general.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14310-219731189021-frozen-herb/

**Comment by pelekon** [comment]
Fixed
