### ISSUE TITLE
[PL][Fishing] brak reakcji po kliknięciu w bobber

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2200]
Pomimo posiadania fishingu na maksymalnym poziomie (z dodatkowymi łatkami) bardzo często kliknięcie w podskakujący bobber nie reaguje. Wygląda to tak jakby się miało za niski poziom wędkarstwa na łowienie w danym miejscu. Pomimo łowienia w Stormwind zdażało mi się tracić nawet co 3 rzut.

**Comment by kostas4949** [comment]
Google translate helped me understand what this report said. This is exactly the issue i was coming here to post. Sometimes you click the bobber and the line that connects the bobber with your fishing pole disappears, but you don't actually fish it up, and after a few seconds the fish gets away with the corresponding message. It responds as if you didn't even try to get the fish out of the water.

**Comment by mitim1** [comment]
Łowiłem wczoraj w th oraz w uldum, i problem u mnie nie występował nawet raz.
Fishing na 525 + 100 z wędki.

**Comment by Giq** [comment]
https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
