### ISSUE TITLE
[ENG][QUEST] Stones Of Binding 

### ISSUE THREAD

**Issue by Cassedy** [Atlantiss/BugTracker#2201]
The Stones of Binding are not spawned in the places they should be so the quest can not be completed.

Quest:
http://www.wowhead.com/quest=28459/stones-of-binding

Questitem:
http://www.wowhead.com/item=64308/elemental-binding-stone

Don't know if its the same for Alliance Warlocks. Anyway here is a link to their quest.
http://www.wowhead.com/quest=28399/stones-of-binding

**Comment by hexerion** [comment]
True, no quest items. No horns for the lock, except those from Garr from MC.

**Comment by aendry** [comment]
still

**Comment by tomatosz** [comment]
Fixed in rev. 5759
