### ISSUE TITLE
[PL][NPC] Spore Strider

### ISSUE THREAD

**Issue by Alandiel** [Atlantiss/BugTracker#2204]
Addy http://www.wowhead.com/npc=22299/spore-strider przywoływane przez http://www.wowhead.com/npc=17882/the-black-stalker w Underbog heroic dają 250 repy(tyle co bossy). Nie powinny dawać repy.

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
Fixed by Navedonar:
