### ISSUE TITLE
[PL][Quest] Maul 'Em With Kindness

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#2207]
Nie mogę użyć Bilgewater Cartel Promotional Delicacy Morsels ( http://www.wowhead.com/item=52044/bilgewater-cartel-promotional-delicacy-morsels )  to napisali "You can't to that yet". To chyba dlatego, że nie mogę zaatakować Ogrów z Dunemaul ( czasem się zdarzy jakiś co o można zaatakować ):
Dunemaul Brute ( http://www.wowhead.com/npc=5474/dunemaul-brute ) 
Dunemaul Enforcer ( http://www.wowhead.com/npc=5472/dunemaul-enforcer ) 
Dunemaul Warlock ( http://www.wowhead.com/npc=5475/dunemaul-warlock )

Link: http://www.wowhead.com/quest=24963/maul-em-with-kindness

P.S. Wydaje mi się, że to ogry są bardziej bugiem... :/

**Comment by Maczuga** [comment]
Bump, można zrobić questa jedynie na mobkach najbliżej jaskini.
