### ISSUE TITLE
[PL][Quest][Icecrown] The Art of Being a water Terror

### ISSUE THREAD

**Issue by Haffyd** [Atlantiss/BugTracker#2208]
Link : http://www.wowhead.com/quest=13091/the-art-of-being-a-water-terror

Zadanie polega na zamienieniu się w żywiołaka wody i zemscie. Zamiana działa ale nie posiadamy many/energi co za tym idzie, nie możemy w żaden sposób używac skilli.

Dodam, że q jest częścią chaina na odblokowanie arenki w IC.

**Comment by Bildo** [comment]
duplikat
