### ISSUE TITLE
[PL] [Deepholm] Aliance flight ship. this troll ?

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2212]
na tym statku czasami z 3 razy tak miałem ze mnie tepneło za deepholm
![wowscrnshot_021515_092359](https://cloud.githubusercontent.com/assets/8699987/6202622/2092c2e4-b4f6-11e4-9a5a-887162e5e5bd.jpg)

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4319
