### ISSUE TITLE
[EN][Quest][Westfall] A vision of the Past

### ISSUE THREAD

**Issue by ivan6285** [Atlantiss/BugTracker#2213]
The stage of the quest where  the player is supposed to witness a vision of what happened between the party of NPCs and VanCleef is bugged. 

The party just stand there and does nothing, the script does not advance further, and the player is stuck in place until he dies after several minutes.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1622

**Comment by Athelon** [comment]
https://github.com/Athelon/Mari/issues/1
