### ISSUE TITLE
[PL] [Spell] [Death Knight] Unholy Frenzy

### ISSUE THREAD

**Issue by Kochany** [Atlantiss/BugTracker#2215]
Po nałożeniu na np. gościa w trapie Uh frenzy dmg owszem otrzymuje, hp % obniża się, ale nie zostaje uwolniony z cc. Podobny przypadek jest z HoSem od paladyna jak i intervene od warriora.

http://www.wowhead.com/spell=31626/unholy-frenzy
http://www.wowhead.com/spell=6940/hand-of-sacrifice
http://www.wowhead.com/spell=3411/intervene

**Comment by Jenovas** [comment]
Fixed
