### ISSUE TITLE
[PL] [Shaman] [Talent] Ancestral Swiftness

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2218]
talent w ogóle nie działa poprawnie nie dodaje 15 % speeda jak 
shaman jest w ghost wolf. 
http://wow.gamepedia.com/Ancestral_Swiftness_(shaman_talent)
http://cata.openwow.com/spell=16262

**Comment by Bastion** [comment]
talent zmniejsza cast ghost wolfa i normalny speed, a nie w ghost wolfie..

**Comment by arekczup** [comment]
zmienia prędkość twojej postaci ghost wolfa ( duchowego wilka )

**Comment by Aviannaqt** [comment]
Bastion dobrze mówi. To zwiększa poruszanie się twojej postaci o 7/15% a nie wilka.

**Comment by Wolffenstein** [comment]
Działa dobrze...

**Comment by Haffyd** [comment]
[Rank 1] Reduces the cast time of your Ghost Wolf spell by 1 sec and increases movement speed by 7%. This does not stack with other movement speed increasing effects.

Czytaj uważnie! Nie stakuje się z innymi bufami zwiększającymi Twoją prędkość ;)
