### ISSUE TITLE
[EN][Spell][Druid] Moonkin form shapeshift macro

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#222]
/cast !Moonkin Form should remove root and slow effects, but it doesn't do it.

http://cata.openwow.com/spell=24858 // Moonkin Form

**Comment by serianx** [comment]
shapeshifting no longer removes roots since cataclysm

**Comment by kadi2** [comment]
@serianx There is exception for Moonkin Form, and Resto druids with learnt talent.

**Comment by Jenovas** [comment]
Fixed in rev 4705
