### ISSUE TITLE
[EN][Spell][Paladin] Hand of Protection

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#2221]
Hand of Protection: http://cata.openwow.com/spell=1022

I can't use spells when i am under effect of Hand of Protection. I tried Blink and it says "can't do that while silenced".
Screenshot: http://wstaw.org/m/2015/02/15/WoWScrnShot_021515_174539.jpg

Every other spell is "gray" and it's not possible to use them while Paladin puts on us HoP. 

It should only block physical attack.

PS: Related to https://github.com/Atlantiss/BugTracker/issues/1742

**Comment by Wolffenstein** [comment]
It has been like that since 4.3.4 or it bugged after a certain revision?

**Comment by Arcadia713** [comment]
After one of last revision (i mean in case of not possibility of using Blink - https://github.com/Atlantiss/BugTracker/issues/1742 was since 4.3.4).

**Comment by Jenovas** [comment]
Does it block all spells? Frostbolt? Or only some spells?

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
