### ISSUE TITLE
[PL][Spell][Death Knight] Death Grip

### ISSUE THREAD

**Issue by Kozuro** [Atlantiss/BugTracker#2231]
Death Grip powinien tauntować wszystko co jest podatne na taunt, czyli bossy i moby, które mają immune na przyciągnięcie także. Nie jestem pewny czy można opis traktować dosłownie, ponieważ nie znalazłem nic konkretnego na wowhead, a z opisu można wywnioskować, że aggro powinno być skierowane na nas, tylko przez 3 sek po użyciu death gripa.

http://www.wowhead.com/spell=49576/death-grip#changelog

**Comment by Kozuro** [comment]
Miło by było, gdyby w końcu ktoś to naprawił.

**Comment by Jenovas** [comment]
Jak bedzie czas to naprawimy.

**Comment by Kozuro** [comment]
Nadal nie macie czasu naprawić ważnego skilla u dk?

**Comment by Kejmil** [comment]
death grip to normalny taunt, a "bug" ktory sprawil ze jest traktowany jak taunt jakiegos peta datuje sie na progressy lich kinga na atlantissie

**Comment by Jenovas** [comment]
Nadal nie było czasu naprawić. Próbowałem ale nie jest to takie proste. Proszę czekać. Jest 1000 bugów a nie jeden.

**Comment by Jenovas** [comment]
Fixed in rev 4374
