### ISSUE TITLE
[EN][Molten Core] Thunderfury & Sulfuras

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#2232]
The Molten Core raid http://www.wowhead.com/zone=2717/molten-core holds two legendary weapons:

Thunderfury, Blessed Blade of the Windseeker http://www.wowhead.com/item=19019/thunderfury-blessed-blade-of-the-windseeker
Sulfuras, Hand of Ragnaros http://www.wowhead.com/item=17182/sulfuras-hand-of-ragnaros

Both of these require certain maths to be gathered. I've already assembled all required maths for Thunderfury, which include the legendary Enchanted Elementium Bar http://www.wowhead.com/item=17771/enchanted-elementium-bar , save for the two bindings that drop from Garr http://www.wowhead.com/npc=12057/garr and Baron Geddon http://www.wowhead.com/npc=12056/baron-geddon Those bindings are:

http://www.wowhead.com/item=18563/bindings-of-the-windseeker
http://www.wowhead.com/item=18564/bindings-of-the-windseeker

As far as I remember, they should both have a drop chance of about 4%, using the RNG drop system. Also, in order to forge Sulfuras, Hand of Ragnaros, you need to combine a forged mace using Blacksmithing and Eye of Sulfuras http://www.wowhead.com/item=17204/eye-of-sulfuras which should have a drop chance of 1%.

For the 4 months that I've been on this server, I have seen people with other legendaries, like Warglaive of Azzinoth http://www.wowhead.com/item=32838/warglaive-of-azzinoth but I have never ever seen nor heard anyone seeing either the Bindings or the Eye of Sulfuras drop. This makes me question whether if those items are even scripted. And even if they are, are the legendary quests associated with them scripted too?

**Comment by Arcadia713** [comment]
Yes they are scripted. I know at least 3 people with Windseeker and Sulfuras (myself i have Left Bindings and Enchanted Elementiums, just need one more Binding and quest item from Ragnaros).

**Comment by captjvmoore** [comment]
I already asked in-game. The GM advised me to report this here and see what the results are.

**Comment by Varchord** [comment]
I know at least one person with sulfuras
