### ISSUE TITLE
[EN][npc] Restless Infantry and Restless Soldier

### ISSUE THREAD

**Issue by box95** [Atlantiss/BugTracker#2235]
http://www.wowhead.com/npc=46823/restless-infantry
http://www.wowhead.com/npc=46825/restless-soldier
These two npc dont usually have full hp but 50% or less and when you  kill them they aren't tracked on quest log
http://i.imgur.com/ZnIZuVO.jpg
http://i.imgur.com/z5OFynz.jpg

**Comment by box95** [comment]
ofc the quest says to kill the restless infantry so I suppose this happens to on the horde side

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/736
