### ISSUE TITLE
[PL][Item] Drakehide Leg Armor

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#2238]
http://wow.gamepedia.com/Pattern:_Drakehide_Leg_Armor
Żaden NPC z LW nie posiada tego patternu i tankowie muszą dalej nosić enchant 145 stama 55 agi kiedy agility od wejscia 4.3.4 nie daje żadnych profitów warkowi/dk/palowi.

**Comment by Varchord** [comment]
Ktos juz to zgłaszał pamiętam. I chyba naprawiane bylo

**Comment by Qwers** [comment]
Nie było naprawione. Łatka została dodana w 4.2.0, a u nas dalej jej nie ma.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1628
Wiedziałem, że było! Ale zamknięte, chyba przez zły format zgłoszenia ^^

**Comment by Wolffenstein** [comment]
Fixed in rev 4330.
