### ISSUE TITLE
[EN][Achievement] A Silver Confidant

### ISSUE THREAD

**Issue by ThandorAts** [Atlantiss/BugTracker#2239]
Earning achievement http://www.wowhead.com/achievement=3676/a-silver-confidant don't grant reward: Unlocks Silver Covenant dailies at the Argent Tournament. In effect NPCs http://www.wowwiki.com/Savinia_Loresong and http://www.wowwiki.com/Narasi_Snowdawn don't offer their daily quests.

**Comment by Cudownie** [comment]
same with the Horde side.
http://www.wowhead.com/achievement=3677/the-sunreavers

**Comment by Illusionist87** [comment]
Bumping, since this is still not fixed.

**Comment by jacula666** [comment]
bump

**Comment by Bildo** [comment]
fixed

**Comment by jacula666** [comment]
Well, not really... Still don't have them unlocked

**Comment by Bildo** [comment]
wait for an update
