### ISSUE TITLE
[PL][Quest][Hillsbrad Foothills]A Blight Upon the Land

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#2240]
http://www.wowhead.com/quest=28237/a-blight-upon-the-land

NPC nie jest wrogi w stosunku do nas, więc nie zdobędziemy jego głowy potrzebnej do ukończenia questa.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/397
