### ISSUE TITLE
[EN][Quest][Icecrown] The Valliant's Challenge

### ISSUE THREAD

**Issue by ThandorAts** [Atlantiss/BugTracker#2241]
Completing quest http://www.wowwiki.com/Quest:The_Valiant%27s_Challenge_%28Alliance%29 doesn't unlock the "Valiant of ..." chain quests e.g. http://www.wowwiki.com/Quest:Valiant_Of_Ironforge for other capital cities.

**Comment by zano354** [comment]
Even the other faction are already exalted, the other champion faction still doesnt give the quest (the valiant challenge).

**Comment by TheCroak** [comment]
Months later... still can't complete it because no unlocked quests.

**Comment by virushm** [comment]
dont work

**Comment by Piklo** [comment]
should be fixed in [rev5794](https://atlantiss.eu/changelog#rev5794)
