### ISSUE TITLE
[PL][Event] Lunar Festival

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#2242]
http://www.wowhead.com/achievement=6006/elders-of-cataclysm - jak narazie niewykonalne

http://www.wowhead.com/npc=55210/elder-sekhemi - stoi, nie mozna nawet zagadać
http://www.wowhead.com/npc=55211/elder-menkhaf - stoi, nie mozna nawet zagadać
http://www.wowhead.com/npc=55227/elder-evershade - stoi, nie mozna nawet zagadać
http://www.wowhead.com/npc=55224/elder-windsong - stoi, nie mozna nawet zagadać

**Comment by Pieczyyea** [comment]
Problem pewnie dotyczy elderów z Twilight Highlands, Deepholm i Vash'ir (choć lokacje są wyłączone, elderzy powinni działać)
