### ISSUE TITLE
[PL][Event] Lunar Festival

### ISSUE THREAD

**Issue by asteroida** [Atlantiss/BugTracker#2243]
osoby które robiły event w zeszłym roku, w tym nie mogą zbierać tokenów a dokładniej chodzi o http://www.wowhead.com/item=21100/coin-of-ancestry

**Comment by Velius94** [comment]
Dodatkowo, żadnego z dodanych w Cata Elderów nie można znaleźć.

http://www.wowhead.com/achievement=6006/elders-of-cataclysm - Achievement

Lista NPC:

http://www.wowhead.com/npc=55227 - Elder Evershade, Mount Hyjal
http://www.wowhead.com/npc=55224 - Elder Windsong, Mount Hyjal
http://www.wowhead.com/npc=55228 - Elder Moonlance, Vashj'ir
http://www.wowhead.com/npc=55217 - Elder Stonebrand, Deepholm
http://www.wowhead.com/npc=55216 - Elder Deepforge, Deepholm
http://www.wowhead.com/npc=55210 - Elder Sekhemi, Uldum
http://www.wowhead.com/npc=55211 - Elder Menkhaf, Uldum
http://www.wowhead.com/npc=55218 - Elder Darkfeather, Twilight Highlands
http://www.wowhead.com/npc=55219 - Elder Firebeard, Twilight Highlands

**Comment by Bildo** [comment]
http://www.wowhead.com/npc=55227 - widac
http://www.wowhead.com/npc=55224 - widac 
http://www.wowhead.com/npc=55228 - widac
http://www.wowhead.com/npc=55217 - nie widac (bedzie po update)
http://www.wowhead.com/npc=55216 - widac
http://www.wowhead.com/npc=55210 - widac
http://www.wowhead.com/npc=55211 - widac
http://www.wowhead.com/npc=55218 - nie widac (bedzie po update)
http://www.wowhead.com/npc=55219 - nie widac (bedzie po update)

**Comment by Fikoblin** [comment]
Żaden z NPCów nie ma możliwości oddania questu. Są to po prostu kukły 1lvl 51hp, które nie mają żadnej możliwości rozmowy i za razem zrobienia osiągnięcia.

**Comment by Navedonar** [comment]
.
