### ISSUE TITLE
[EN] Inns without Rest Areas

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2244]
The following alliance and neutral inns don't have a [rest](http://wow.gamepedia.com/Rest) area associated with them.

![zzz - resting](http://i.imgur.com/ua50nH8.jpg)

I'm not sure if every last of them is supposed to have one (for example I can't remember if the Wyrmrest Temple innkeeper had one and the wowhead comments are inconclusive: some say 'yes', some say 'no'), but I'm sure that the vast majority of the Inns mentioned here should have rest areas (For example the inns in Elwynn Forest, Darkshore and Howling Fjord).

#### Howling Fjord
- [Innkeeper Hazel Lagras](http://www.wowhead.com/npc=23731/innkeeper-hazel-lagras), Valgarde

#### Dragonblight
- [Demestrasz](http://www.wowhead.com/npc=27950/demestrasz), Wyrmrest Temple

#### Icecrown
- [Caris Sunlance](http://www.wowhead.com/npc=33970/caris-sunlance), Silver Covenant Pavillion

## TBC
(nothing)

#### Elwynn Forest
- [Innkeeper Farley](http://www.wowhead.com/npc=295/innkeeper-farley), Lion's Pride Inn

#### Badlands
- [Sally Gearwell](http://www.wowhead.com/npc=48054/sally-gearwell), Fuselight

#### Wetlands
- [Innkeeper Helbrek](http://www.wowhead.com/npc=1464/innkeeper-helbrek), Deepwater Tavern
- [Innkeeper Daughny](http://www.wowhead.com/npc=44006/innkeeper-daughny), Sundown Marsh
- [Innkeeper Larisal](http://www.wowhead.com/npc=43993/innkeeper-larisal), Greenwarden's Grove

#### Tanaris
- [Carmen Ibanozzle](http://www.wowhead.com/npc=38714/carmen-ibanozzle), Bootlegger Outpost

#### Uldum
- [Kazemde](http://www.wowhead.com/npc=48886/kazemde), Ramkahen
- [Yasmin](http://www.wowhead.com/npc=49406/yasmin), Oasis of Vir'sar

#### Thousand Needles
- [Daisy](http://www.wowhead.com/npc=40832/daisy), Speedbarge Bar

#### Stonetalon Mountains
- [Innkeeper Bernice](http://www.wowhead.com/npc=44177/innkeeper-bernice), Farwatcher's Glen
- [Valos Shadowrest](http://www.wowhead.com/npc=41491/valos-shadowrest), Thal'darah Overlook
- [Alithia Fallowmere](http://www.wowhead.com/npc=40898/alithia-fallowmere), Fallowmere Inn
- [Lyanath](http://www.wowhead.com/npc=41286/lyanath), Northwatch Expedition Base Camp

#### Felwood
- [Innkeeper Wylaria](http://www.wowhead.com/npc=48215/innkeeper-wylaria), Whisperwhind Grove
- [Denmother Ulrica](www.wowhead.com/npc=47931/denmother-ulrica), Talonbranch Glade (she's also missing the 'Innkeeper' subtitle)

#### Darkshore
- [Innkeeper Kyteran](http://www.wowhead.com/npc=43420/innkeeper-kyteran), Lor'danel

#### Mount Hyjal
- [Sebelia](http://www.wowhead.com/npc=40843/sebelia), Nordrassil Inn
- [Isara Riverstride](http://www.wowhead.com/npc=43487/isara-riverstride), Shrine of Aviana
- [Salirn Moonbear](http://www.wowhead.com/npc=53779/salirn-moonbear), Grove of Aessina

**Comment by Artix333** [comment]
when it will be fixed?

**Comment by Wolffenstein** [comment]
Fixed in rev 4599.
