### ISSUE TITLE
[ENG][Quest][Zul'Drak] Cocooned!

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2245]
http://www.wowhead.com/quest=12606/cocooned

Would be nice to see some freed Footmen (http://www.wowhead.com/npc=28415/captive-footman).

**Comment by Quban** [comment]
`SET @cocoon = 28413;`
`SET @footman = 28415;`
`SET @sumFoot = 51599;`
`SET @sumCaptive = 51597;`
``UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@cocoon;``
``DELETE FROM smart_scripts where entryorguid in (@cocoon, @cocoon*100, @cocoon*100+1,@cocoon*100+2);``
```INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES```
```(@cocoon,0,0,1,11,0,100,1,0,0,0,0,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - On Respawn - Disable Combat Movement (No Repeat)'),```
```(@cocoon,0,1,2,61,0,100,0,0,0,0,0,18,2097152,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - On Respawn - Set Flag Disarmed (No Repeat)'),```
```(@cocoon,0,2,0,61,0,100,0,0,0,0,0,42,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - On Respawn - Set Invincibility HP'),```
```(@cocoon,0,3,0,4, 0,100,0,0,0,0,0,64,1,0,0,0,0,0,7,0,0,0,0,0,0,0,'Nerubian Cocoon - On Death - Store Target List (No Repeat)'),```
```(@cocoon,0,4,0,2,0,100,1,0,2,0,0,87,@cocoon*100,@cocoon*100+1,@cocoon*100,@cocoon*100+2,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - On Death - Run Random Script (No Repeat)'),```
```(@cocoon*100,9,0,0,0,0,100,0,0,0,0,0,11,@sumFoot,2,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - Script 1 - Cast Summon Captive Footman'),```
```(@cocoon*100,9,1,0,0,0,100,0,0,0,0,0,33,@footman,0,0,0,0,0,12,1,0,0,0,0,0,0,'Nerubian Cocoon - Script 1 - Give Kill Cedit'),```
```(@cocoon*100,9,2,0,0,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - Script 1 - Despawn'),```
```(@cocoon*100+1,9,0,0,0,0,100,0,0,0,0,0,11,@sumCaptive,2,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - Script 2 - Cast Summon Summon Scourged Captive'),```
```(@cocoon*100+1,9,1,0,0,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - Script 2 - Despawn'),```
```(@cocoon*100+2,9,0,0,0,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Nerubian Cocoon - Script 3 - Despawn');```

**Comment by Bildo** [comment]
rev. 4353 by Quban
