### ISSUE TITLE
[AuctionHouse] Opcja Usable nie działą dla recept

### ISSUE THREAD

**Issue by siof** [Atlantiss/BugTracker#2248]
Zaznaczanie opcji Usable nie działa dla recept. Zaznaczenie jej powinno spowodować usunięcie z wyników wszystkich recept które już umiemy.

fix (nie sprawdzałem go na skyfire): 
Dodanie do CanUse(item proto) czegoś takiego:
https://bitbucket.org/siof/hellground-wowemu/src/d383a3ac615777f030ed5692b79c0c00ea8a6d51/src/game/Player.cpp?at=trunk#cl-10532 

Modyfikacja w auctionmgr::BuildListAuctionItems na używanie item proto zamiast item
https://bitbucket.org/siof/hellground-wowemu/commits/b9ccf7ec493bb723ec635ab468860545f362402b

**Comment by Wolffenstein** [comment]
Wrzucone w trochę innej formie, dzięki ;)

Rev 4330.
