### ISSUE TITLE
[EN][Event][Burning Steppes] Elder Rumblerock

### ISSUE THREAD

**Issue by Hordraric** [Atlantiss/BugTracker#2250]
Elder rumblerock is bugged for some people due to a phasing quest. even tried to finish the chain but no sucess. retail also had the problem and they said to finish the chain but since it didnt worked i think the best solution would be to respawn him near the other elder in the burning steppes or respawn him in the phased area

http://www.wowhead.com/npc=15557/elder-rumblerock

**Comment by Xaedric** [comment]
I can confirm, I did all quests in burning steppes back when server was 4.0.6a and the elder is not there now making it impossible to complete 'Elders of Eastern Kingdoms' Achievement.

**Comment by Xaedric** [comment]
Still an issue as of Feb 4th 2016. Rev. 4866. If you quest on the area, make sure to talk to the elder first before you're getting phased.

**Comment by Brotato** [comment]
So is there anyway to get this elder? Or i just won't get this achievement?

**Comment by Bildo** [comment]
fixed rev  4880
