### ISSUE TITLE
[EN][Quest][Redridge Mountains] To Win a War You Gotta Become War

### ISSUE THREAD

**Issue by B2Kcodrutz** [Atlantiss/BugTracker#2251]
In the blackorc tower . I place the seaforium , the spell works , but the quest doesn't complete

**Comment by Bildo** [comment]
wowhead links laos its duplicate

**Comment by B2Kcodrutz** [comment]
what wowhead links? what you mean?

**Comment by Bildo** [comment]
http://www.wowhead.com/quest=26651/to-win-a-war-you-gotta-become-war

**Comment by B2Kcodrutz** [comment]
btw, the seaforium ,,fuzz,, is outside the tower near a big rock... i think thats the problem
