### ISSUE TITLE
 [Twisted Faith] talent recently bugged

### ISSUE THREAD

**Issue by buburubuu** [Atlantiss/BugTracker#2252]
This is a talent on the shadow priest tree where its suppose to give u 100% from your spirit as hit on 2/2 points on it the problem is it doesnt give any.

http://www.wowwiki.com/Twisted_Faith

"Increases your Shadow spell damage by 2%, and grants you spell hit rating equal to 100% of any Spirit gained from items or effects."

**Comment by Wolffenstein** [comment]
Are you sure that it isn't just a visual bug?

**Comment by buburubuu** [comment]
I tested it on heroic dumy with and without the talent, so it seems to be jsut a visual bug. But please fix it because its kind of impossible to see when  u are capped. Thank u in advance.

**Comment by Arcadia713** [comment]
It works...
Items without spirit (only base amount): http://wstaw.org/m/2015/02/17/WoWScrnShot_021715_141310.jpg
Items with spirit (+309 additional Spirit from items): http://wstaw.org/m/2015/02/17/WoWScrnShot_021715_141250.jpg http://wstaw.org/m/2015/02/17/WoWScrnShot_021715_141524.jpg

**Comment by Wolffenstein** [comment]
Closing the issue, it's working.
