### ISSUE TITLE
[PL][Quest][Arathi Highlands]Sigil of Storm

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#2255]
http://www.wowhead.com/quest=639/sigil-of-strom

Item potrzebny do ukończenia questu nie wypada.

**Comment by Wolffenstein** [comment]
"This quest was marked obsolete by Blizzard and cannot be obtained or completed."
Tego questa raczej w ogóle nie powinno już być.

**Comment by Bildo** [comment]
chodzilo mu o ten quest http://www.wowhead.com/quest=26030/sigil-of-strom :dancer: a item ma 5% dropu

**Comment by Haz3L** [comment]
Chyba nie ma 5% dropu skoro po zabiciu 100 mobów nie wypadł.

**Comment by Asavel** [comment]
na globie byl ten sam problem przeczytaj komentarze ;)

**Comment by Bildo** [comment]
masz pecha

**Comment by Haz3L** [comment]
I może powiesz mi, że druga postać po zabiciu kolejnych 100 mobów też ma pecha? ;]
