### ISSUE TITLE
[PL][Quest]"Gnomish Engineering"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2258]
Ten Quest nie powinien mi się pokazywać, gdyż posiadam Tailoring i Enchanting.

Link: http://www.wowhead.com/quest=29477/gnomish-engineering

**Comment by Quban** [comment]
Fixes also https://github.com/Atlantiss/BugTracker/issues/2259

`SET @engiSkillID = 202;`
`SET @QuestGoblin = 29475;`
`SET @QuestGnome = 29477;`
`UPDATE quest_template SET RequiredSkillId = @engiSkillID, ExclusiveGroup = @QuestGoblin, RequiredSkillPoints = 1 where Id in (@QuestGoblin, @QuestGnome);`

**Comment by Navedonar** [comment]
200 Engineering is required to make this quest available.

**Comment by Quban** [comment]
Updated

**Comment by Danelar** [comment]
Ja w ogóle nie zamierzam na tej postaci mieć Engineering - powinno mi się pokazywać wtedy jak go się nauczę, bądź wyskilluje - tak jak jest z Daily na Fishing i Cooking. :|

**Comment by Quban** [comment]
fix soon
