### ISSUE TITLE
[PL][Quest]"Goblin Engineering"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2259]
Ten Quest nie powinien mi się pokazywać, gdyż posiadam Tailoring i Enchanting.

Link: http://www.wowhead.com/quest=29475/goblin-engineering

**Comment by Navedonar** [comment]
http://www.wowhead.com/quest=29475/goblin-engineering#comments
200 Engineering is required to make this quest available.

**Comment by Danelar** [comment]
I not have Engineering - and I'm not going!

**Comment by Danelar** [comment]
Powinno mi się pojawiać tak Daily z Fishingu i Cookingu tz. wtedy gdy się nauczę profesji - bądź jak w tym przypadku - wyskilluję odpowiednio.

**Comment by Quban** [comment]
fix soon
