### ISSUE TITLE
[PL][core] DK weapon enchants on BoA weapons shoudnt work on another classes

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#2262]
Enchanty dk na broni BoA (np. takiej z archeologi) po przeslaniu na inna postac nie powinny działać, a działaja. Wysylać bronie z enchantem, i uzywac ich powinno sie dac, ale enchant ten nie powinien sie odpalać.

**Comment by Kejmil** [comment]
potwierdzam - patrzac po dzisiejszym av troche gamebreaking

**Comment by grzesiurwk** [comment]
http://imgur.com/poMLbbY

**Comment by Wolffenstein** [comment]
Fixed in rev 4352.
