### ISSUE TITLE
[PLl][Achievement][Guild] Working as a Team

### ISSUE THREAD

**Issue by Marzec737** [Atlantiss/BugTracker#2264]
http://www.wowhead.com/achievement=4860/working-as-a-team

na Atlantiss działa to w ten sposób, że liczy osoby które NAJPIERW wbiły honored w guild repu, a dopiero później wbiły maxx skill w profesji. Powinno liczyć wszystkich którzy maja 525+ w profesji i mają Honored w guild, niezależnie od tego, co wbili pierwsze.

**Comment by sunshineinabox** [comment]
I have experienced this. Without the achievement you can't get certain heirlooms and maxing professions takes a long time.

**Comment by Radeghost** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 4819.

**Comment by Radeghost** [comment]
same goes for Thunderfury guild achi :s
