### ISSUE TITLE
[ENG][NPC][Sholazar Basin] Dreadsaber Mastery: Ready to Pounce

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2268]
http://www.wowhead.com/quest=12558/dreadsaber-mastery-ready-to-pounce

Same as issue #2230. "Shango's Pelt" (http://www.wowhead.com/item=38523/shangos-pelt) should have a drop chance of 100%, the lower chance in wowhead is a result of people killing Shango without the quest.

**Comment by Quban** [comment]
```UPDATE creature_loot_template SET ChanceOrQuestChance = -100 WHERE entry = 28297 and item = 38523;```

**Comment by Navedonar** [comment]
fixed http://atlantiss.eu/changelog#rev4353
