### ISSUE TITLE
[PL][Priest] Dispel Magic

### ISSUE THREAD

**Issue by Malylolek** [Atlantiss/BugTracker#2269]
Będąc w specu shadow nie moge użyć Dispel magic na nikim poza sobą 

Dispel Magic : http://www.wowhead.com/spell=15090/dispel-magic#changelog

**Comment by Arcadia713** [comment]
Bo 4.3 he-he-he.

**Comment by Malylolek** [comment]
Idzi sobie tez lamisz nie robisz 1,5kk z combusta

2015-02-17 23:06 GMT+01:00 Arcadia713 <notifications@github.com>:
