### ISSUE TITLE
[PL][NPC] Ramkahen

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#227]
http://www.wowhead.com/npc=46402
- Poruszają się randomowo

http://www.wowhead.com/npc=46333
- poruszają się randomowo

**Comment by ashrasmun** [comment]
https://community.atlantiss.eu/index.php?/topic/14465-227-ramkahen-citizenslaborers-movement/

**Comment by Jenovas** [comment]
Fix in rev 5539
