### ISSUE TITLE
[EN][CORE][SETS] HighPrio

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#2270]
Sometimes after relog or random action resi set bonus does stack

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
BUMP ?

**Comment by BialyADI** [comment]
Some one is here?

**Comment by Wolffenstein** [comment]
"Sometimes" doesn't exactly help in reproducing the bug.

**Comment by TranceAccount** [comment]
Afaik this got fixed very long ago xd
