### ISSUE TITLE
[EN][CORE][Fear][HighPrio]

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#2271]
fear is so broken it throw down people from edge for ex. behind box in dalaran or bridge in bem and vice versa i feared target that was  down and he went on top of the bridge LOL

**Comment by blinkmaster** [comment]
works the same with polymorph, probably every lose control effect can do that

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
change fear to mechanics like it was in 406 cause its gamebreaking rly /bump

**Comment by Jenovas** [comment]
Rev 4406 - fixed
