### ISSUE TITLE
[PL][ROGUE] Shadowstep

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#2283]
Gdy użyjemy <a href="http://cata.openwow.com/spell=36554">shadowstep</a> na osobie która jest w powietrzu zostaniemy przeteleportowani na ziemię pod graczem. To samo dzieje się w wodzie, po shadowstepie teleportuje nas na samo dno.

**Comment by xmesaj2** [comment]
Dodam, że w Hyjal często wpadałem nim pod tekstury podczas expienia.

**Comment by Vyrtuz** [comment]
dodatkowo po użyciu Shadowstep na cel, który jest "pod dachem" przemieszcza gracza na dach. Przykład: bunkry Stormpike w Atletic Vallery.

**Comment by armano2** [comment]
liked: #1868
