### ISSUE TITLE
To Honor One's Elders

### ISSUE THREAD

**Issue by Xtrodinary001** [Atlantiss/BugTracker#2284]
Elder Firebeard and Elder Darfeather in Twilight Higlands not interactable.

Elder Stonebrand Phased in Questing Zone of Temple of Earth making it unobtainable for people who have finished quests in Deepholm.

**Comment by Beatit** [comment]
true

**Comment by ThandorAts** [comment]
Confirmed http://www.wowhead.com/quest=29737/firebeard-the-elder, http://www.wowhead.com/quest=29736/darkfeather-the-elder and http://www.wowhead.com/quest=29735/stonebrand-the-elder bugged through the phasing.

**Comment by therealpadthai** [comment]
Confirmed on all three.

**Comment by Hordraric** [comment]
also have the same poblem with twilight highlands one

**Comment by Wolffenstein** [comment]
Fixed in rev 4341.

**Comment by Xaedric** [comment]
What about Elder Rumblerock at Burning Steppes? #2250
