### ISSUE TITLE
[PL][Profession][Alchemy][Quest] Elixir, Potion & Transmutation Master

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#2286]
Quest giver Honor Hold: http://www.wowhead.com/npc=18802/alchemist-gribble
Quest giver Thrallmar: http://www.wowhead.com/npc=16588/apothecary-antonivich
Quest giver Stormwind: http://www.wowhead.com/npc=5499/lilyssia-nightbreeze
Quest giver Orgrimmar: http://www.wowhead.com/npc=3347/yelmak

Na obecnym patchu NPC w Outland nie powinni już dawać nam questów na wymienione w temacie specjalizacje. Powinni je za to dawać NPC w Stormwind/Orgrimmar wraz z nowymi wymaganiami(475 skill req + matsy* z Cata) dotyczącymi ukończenia tych questów.

*Tutaj pojawia się problem, ponieważ nie mogę znaleźć tych questów z czasów Cata. Wszystkie są już z wymaganiami pod MoP'a. Jeśli ktoś dysponuje linkami to proszę o wpis(chyba, że nie będą potrzebne?).

Edit: Lista wymaganych przedmiotów potrzebnych do ukończenia każdego z questów: http://www.wowwiki.com/Alchemy#Changing_Specializations_after_Patch_4.3

**Comment by Canderous** [comment]
I'm not entirely sure as I don't know polish, but if you are looking for the alchemy specialization quests introduced in 4.3 (as Google Translate leads me to believe), I found them here:
http://www.wowwiki.com/Alchemy#Changing_Specializations_after_Patch_4.3

It confirms that the old BC ones were removed, and new ones were added with Cata materials.

**Comment by Glare** [comment]
Yes, this is exactly what I was looking for. Thank you very much.

**Comment by Morrdok** [comment]
Obecnie na sewerze quest-y do specjalizacji ( jest ich 3) można wziąć od Apothecary Antonivich 
w Hellfire Peninsula.
Na patchu 4.3 questy do specjalizacji (jest ich również 3 ), powinny byc do wzięcia od Yelmak 
w Orgrimmar.
http://www.wowwiki.com/Alchemy#Changing_Specializations_after_Patch_4.3 
sekcja Changing Specializations after Patch 4.3

**Comment by krecik88** [comment]
Fixed in 4393.
