### ISSUE TITLE
[EN][Achievement] Rock Lover doesn't reward with companion

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#2289]
http://www.wowhead.com/achievement=5449/rock-lover

Is supposed to reward you with Pebble  http://www.wowhead.com/item=60869/pebble
Did autocomplete to 10/10 after doing it once (still on 4.0.6) Didn't give the pet.

Did quest 10 times now and still haven't gotten it.

**Comment by smmuntz** [comment]
Just backing up the fact that this achievement doesn't award the companion, I completed it but never received the companion Pebble.

**Comment by Oxyntes** [comment]
yes, Pebble still not available.

**Comment by Samineh** [comment]
ok so I am 9/10 right now, Should I do the quest for the 10th time or wait till fix ?

**Comment by grigman** [comment]
confirmed , achivement still dosent give companion, will we recieve the companion after fix?

**Comment by DuGalle** [comment]
No Pet is given and this report is Months ago old what gives ?

**Comment by xmesaj2** [comment]
http://community.atlantiss.eu/index.php?/topic/10742-2289achievement-rock-lover-reward/ fix
