### ISSUE TITLE
[EN] [Quest] [Twilight Highlands] Darkfeather the Elder and Firebeard the Elder

### ISSUE THREAD

**Issue by Lathron** [Atlantiss/BugTracker#2290]
Hello, 

There seems to be an issue with these 2 quests, all the other ones in cataclysm zones can be completed. The npcs for these quests (http://www.wowhead.com/npc=55218 & http://www.wowhead.com/npc=55219) are spawned, they can be seen but I cannot interact with them and complete the quests (which are http://www.wowhead.com/quest=29736/darkfeather-the-elder & http://www.wowhead.com/quest=29737/firebeard-the-elder) because of the Twilight Shift I assume.

**Comment by Glare** [comment]
https://github.com/Atlantiss/BugTracker/issues/2284
This "all the other ones in cataclysm zones can be completed" is wrong. You can't complete Elder Stonebrand if you finished quest chain in Deepholm.

**Comment by therealpadthai** [comment]
Please see this bugreport: https://github.com/Atlantiss/BugTracker/issues/2284

**Comment by Wolffenstein** [comment]
Fixed in rev 4341.
