### ISSUE TITLE
[En] [Druid] [Feral] Feral charge bear

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#2291]
it shares DR with roots and other controlled roots, which shouldn't, since feral charge isn't a controlled root. It's been like that since vanilla...

**Comment by Varchord** [comment]
wowhead links

**Comment by Isuel** [comment]
http://cata.openwow.com/spell=16979

**Comment by Jenovas** [comment]
Should be fixed in rev 4356
