### ISSUE TITLE
[EN][Guild] Guild Vault Voucher (8th Slot)

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#2293]
www.wowhead.com/item=62287
Our guild vault has 7 tabs, i bought voucher for 8th one, and when i used it, it just went puft 20k gold given for nothing rip

**Comment by therealpadthai** [comment]
Did you buy it in Dalaran? When I bought the 7th tab in Stormwind, the 8th tab did not show up on the vendor screen, however when I went to Dalaran the vendor correctly showed the 8th tab for 20k. I bought it, used it, and have 8 slots in the bank.

**Comment by xolon** [comment]
i bought it in Orgrimmar
