### ISSUE TITLE
[PL][Event] Elder Darkfeather, Firebeard, Stonebrand

### ISSUE THREAD

**Issue by Fikoblin** [Atlantiss/BugTracker#2294]
Tylko ci trzej elderzy zostali niedziałający z całego eventu. 

Elder Stonebrand - http://www.wowhead.com/quest=29735/stonebrand-the-elder
Działa dobrze, ale tylko dla osób które nie skończyły questów w Deepholm. Dla reszty za sprawą fazowania Temple of Earth znika po wejściu do budynku. Pewnie łatwe do naprawienia.

Elder Darkfeather - http://www.wowhead.com/quest=29736/darkfeather-the-elder
Elder Firebeard - http://www.wowhead.com/quest=29737/firebeard-the-elder
Stoją na swoich miejscach, mają żółte pytajniki nad głową, czyli pewnie działają. Niestety za sprawą aury nie można z nimi porozmawiać. Może by wyłączyć aurę w pobliżu nich, albo jeśli się nie da przenieść ich gdzieś indziej?

Każdy z pozostałych elderów jest dostępny i zalicza się do osiągnięcia (nawet ten z Vashj'ir).

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4341

**Comment by HUMBOL** [comment]
rev. 4342, ciągle nie da się zrobić tych questów. Tym razem jednak nie z powodu Twighlight Shift, ale z powodu braku npc's,
