### ISSUE TITLE
[PL][Event] elders cat

### ISSUE THREAD

**Issue by jurek1** [Atlantiss/BugTracker#2296]
po restarcie serwera , nadal nie dzialaja te 3 eldery  
http://www.wowhead.com/quest=29737/firebeard-the-elder      Twilight Highlands ( nie ma go ) 
http://www.wowhead.com/quest=29736/darkfeather-the-elder     Twilight Highlands  ( nie ma go )
http://www.wowhead.com/quest=29735/stonebrand-the-elder      Deepholm  ( znika gdy sie podejdzie - faza )

**Comment by therealpadthai** [comment]
I can confirm that even after revision 4341, the elders in Twilight Highlands are not there. Stonebrand the Elder is still not phasing properly for players who have completed all Deepholm quests.

**Comment by ThandorAts** [comment]
Confirm they're still bugged as written above.

**Comment by Wolffenstein** [comment]
4344
