### ISSUE TITLE
[ENG][INSTANCE][Deeprun Tram Exit Ironforge] Fatal Error Upon Exit

### ISSUE THREAD

**Issue by Stratty94** [Atlantiss/BugTracker#2298]
Upon exiting the Deeprun Tram on the Ironforge side, I have received a fatal error that has caused the application to crash. Every time I try to log back in with the character concerned, the error repeats itself. I now seem to have a redundant character that i cannot use. 

Screenshot attached as evidence: 
![wow error](https://cloud.githubusercontent.com/assets/11082273/6277911/762e623e-b88a-11e4-8afb-e558a28a251a.jpg)

**Comment by Tj20** [comment]
I've used the Deeprun Tram in both directions (IF->SV and back) and it works fine for me.

According to [this](http://atlantiss.eu/community/viewtopic.php?f=10&t=1785) forum post error 134 usually occurs when some files are corrupted. As a fix it suggests to download the game again.

**Comment by aje** [comment]
wow error 134 are related to corruptions of your client
try to redownload the client http://atlantiss.eu/pages/1
