### ISSUE TITLE
[PL] Macro Mind Flay + /petattack

### ISSUE THREAD

**Issue by iskk** [Atlantiss/BugTracker#2301]
Od niespełna tygodnia zauważyłem, że co jakiś czas mój mind flay przerywa się po rozpoczęciu chanellowania. Dziś odkryłem, że spowodowane jest to macrem:

#showtooltip
/cast Mind Flay
/petattack

Macro działało ok do czasu update 4dni temu (pamiętam bo od valiony macro wysiadło a po halfusie był update:D - data wg armory). Nie wiem, czy macro jest poprawne. Nie wiem czy to ważne (defacto mogę wrzucić w macro inny skill). Ale zgłaszam jako minor:D

**Comment by Kesee** [comment]
A masz hitcapa ? Równie dobrze mogą missy przerywać channel.
Btw nie ma linków:D

**Comment by Dziara** [comment]
Problemem jest po prostu atak peta. Nawet bez macra, jeżeli klikniesz go "ręcznie" na pasku peta to przerywa Mind Flaya.

**Comment by iskk** [comment]
Nie dałem linka bo problem jest z /petattack a nie wiem jak znaleźć do tego linka.

Przed chwilą przetestowałem:
Cobra Shot huntera jest castem i /petattack nie przerywa casta.
Health Funnel locka jest channelem i /petattack przerywa channel. Więc /petattack przerywa każdy channel

**Comment by Arcadia713** [comment]
Tak samo u maga, /petattack przerywa działanie Invisibility, przerywa Evocation (channeling), Blizzard (channeling).

**Comment by Wolffenstein** [comment]
Fixed in rev 4344.
