### ISSUE TITLE
[EN][DUNGEON][BLACKROCK CAVERNS]

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#2303]
When aggroing the core hounds before the Boss Beauty, the core hounds all aggro together along with the boss, this seems unavoidable. Thus making every group skip this boss. I found this problem in Heroic Mode. Im unsure if the problem persists in normal.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/353
Issue aready exist
wowhead links
Besides it's not a problem. It's working as intended, read some tactics and boss mechanics
