### ISSUE TITLE
[PL][Object]"Wyrmtail"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2305]
Gdy najeżdżam na ten obiekt myszką NIE MAJĄC QUESTA to pojawia się trybik i możliwość zebrania tej rośliny, ale loot jest pusty ( okienko z czaszka nie ma nic ). Dzieje się tak z wieloma innymi obiektami, lecz póki co ten pamiętam. 

Link: http://www.wowhead.com/object=186463/wyrmtail

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Danelar** [comment]
Dzięki :] Takich obiektów jest spoooro!
Bee pisał jak znajdę podobne :)
