### ISSUE TITLE
[EN][NPC][Twilight Highlands][Horde]

### ISSUE THREAD

**Issue by zasiek** [Atlantiss/BugTracker#2309]
After completing quest Twilight Skies(http://www.wowhead.com/quest=26388/twilight-skies) we can't interact with questgivers Admiral Stonefist(http://www.wowhead.com/npc=42978/admiral-stonefist) and Warlord Krogg(http://www.wowhead.com/npc=43193/warlord-krogg)

**Comment by Bildo** [comment]
th is closed
