### ISSUE TITLE
[PL][Quest][Object][Item] Bloodpetal Sprouts

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#2311]
Zgodnie z linkiem Quest został usunięty.

Link: http://www.wowhead.com/quest=4144/bloodpetal-sprouts

Poniższy Obiekt powinien zostać usunięty.

Link: http://www.wowhead.com/object=164958/bloodpetal-sprout 

Więc Item również.

Link: http://www.wowhead.com/object=164958/bloodpetal-sprout

**Comment by Navedonar** [comment]
obiekt nie powinien być usunięty
http://www.wowhead.com/quest=24702/here-lies-dadanga

**Comment by Danelar** [comment]
Nie mam możliwości odbioru questa - trzeba to naprawić, zgłoszenie aktualne!!!

**Comment by wtRCH** [comment]
fix pending
