### ISSUE TITLE
[EN][Battleground] Alterac Valley Frostwolf Warmaster buff

### ISSUE THREAD

**Issue by Gleecerine** [Atlantiss/BugTracker#2312]
Hello,

I've noticed some players receiving the East / West Frostwolf Warmaster buff when they were in the Horde main base. It gives them +40% Damage and +30% Health for each buff which can make the defense of the base (and the 2 towers) really easy for 1 player with it . It's supposed to only buff other Warmasters and Drek'Thar.

Thanks in advance,

Edit : buff :  http://www.wowhead.com/spell=45826/east-frostwolf-warmaster (is the same for every warmaster
PNJ : http://www.wowhead.com/npc=14777/west-frostwolf-warmaster#comments

**Comment by Varchord** [comment]
wowhead links

**Comment by Thefakemccoy** [comment]
I have proof. This need to be addressed. I have removed any names so no one can be called out. 
![wowscrnshot_121915_162710](https://cloud.githubusercontent.com/assets/12252441/11968075/78fc3396-a8d6-11e5-997a-de8ea8ce5d19.jpg)
![wowscrnshot_121915_162531](https://cloud.githubusercontent.com/assets/12252441/11968076/7beca522-a8d6-11e5-9095-0a689a3f5614.jpg)
