### ISSUE TITLE
[EN][NPC][The Bastion of Twilight] Cho'gall

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#2313]
Not sure how the wowhead link would help but here: http://www.wowhead.com/npc=43324/chogall
Problems with the boss are:
1. Did it today, wiped around 50% HP on boss, a rogue vanished and mass resurrected. The boss didn't respawn, had to make a ticket and a GM respawned him for us. This happened again on the 2nd wipe, this time everyone just resurrected normally just in case that was bugging it out, still no respawn. Had to ask for GM help once again to get a 3rd try.
2. After the first wipe and it being respawned by the GM, while the boss was in Flame Orders ( http://www.wowhead.com/spell=81171/flames-orders ) doing Flaming Destruction ( http://www.wowhead.com/spell=81194/flaming-destruction ), we got the room spammed with 30+ pools of Blaze ( http://www.wowhead.com/spell=158241/blaze ) which made the fight quite a bit more difficult. We killed Cho'gall several times before and he should only put a few Blaze pools, not anywhere near as many as we got. During our first encounter before the wipes it worked properly.

**Comment by xolon** [comment]
same happend to us last night, we wiped once and it didn't respawn

**Comment by HUMBOL** [comment]
Same today.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838
Issue for this raid already exist
