### ISSUE TITLE
[EN][Quest][Uldum] Schnottz So Fast

### ISSUE THREAD

**Issue by BAndysc** [Atlantiss/BugTracker#2314]
[Wowhead npc link](http://www.wowhead.com/npc=48668/schnottz-elite-trooper)
[Wowhead quest](http://www.wowhead.com/quest=28402/schnottz-so-fast)

There is no cutscene after killing last mob - https://www.youtube.com/watch?v=0fPapgUFdHU&t=4m50s

Also [the issue](https://github.com/Atlantiss/BugTracker/issues/2132) has been closed, but I am not sure if it should have been. At least for the quest, npcs in the Chamber should have ~77k hp. So do [wiki](http://www.wowwiki.com/Schnottz_Elite_Trooper) and [wowhead comments](http://www.wowhead.com/npc=48668/schnottz-elite-trooper#comments) say. Please note those comments are from patch 4.0.3, and second one from 4.2, so certainly 230k hp is too much.

**Comment by Canderous** [comment]
https://www.youtube.com/watch?v=de_RyyqZyZw

You can see on the video at 0:47 that the mobs have 232k max hp, but they should start off injured from fighting the ghosts, so the ~77k hp is correct.

**Comment by BAndysc** [comment]
Ok, so the bug is: they should fight :>

**Comment by Canderous** [comment]
They should constantly have a starting hp of 77k, the fighting is just cosmetic, but yes, that's also bugged then, though it's the minor part.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2645

**Comment by BAndysc** [comment]
@Bildo, my issue was first ;P

**Comment by Bildo** [comment]
doesn't matter :P
