### ISSUE TITLE
[PL][PvP] Rated Battleground - bugs

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#2315]
http://www.wowwiki.com/Rated_battlegrounds

Graliśmy dzisiaj Rated BG 10v10 - Twin Peaks.
Co zaobserwowaliśmy:
- ogromną ilość errorów WoW'a w losowych momentach (http://wstaw.org/m/2015/02/20/1_1.png)
- pewny error podczas otwierania tabeli wyników (http://wstaw.org/m/2015/02/20/1_1.png)
- error na koniec bitwy, tj. przy oddaniu ostatniej flagi cały raid dostał errora (http://wstaw.org/w/3dAG/linki/)
- nie zalicza guild challenge (było 8 osób z 1 gildii)

Reszta okej, można jeść żarcie maga, można używać bandaży.
Podejrzewamy też, że jazda na mouncie powoduje crasha (bez mounta nie dostałem chyba żadnego).

**Comment by Alauree** [comment]
Za każdym razem gdy podnosiłem flagę z bazy przeciwnika dostawałem errora. Ale o dziwo inna osoba przede mną zdołała tą flagę podnieść bez crasha.
Dostawaliśmy również errory chwilę po zalogowaniu - bez wyraźnej przyczyny - prawdopodobnie po ruszeniu się z miejsca. .

**Comment by Wolffenstein** [comment]
Sprawdźcie errory w revie 4345.

**Comment by Gunus** [comment]
Ogólnie podejrzewam, że prawdopodobnie każda zmiana na tabeli powodowała errora losowej osobie albo tej osobie co awansowała w tabeli wyżej. 
Na początku przez dołączanie do bitwy. 
A w trakcie kiedy leciały fragi. I osoby wymieniały się pozycjami.
Zauważyłem jeszcze jedną rzecz. Gdy nie miałem żadnej styczności z flagą nie miałem problemu. Lecz gdy zabrałem flage nagłe error.

**Comment by Wolffenstein** [comment]
Ta, to wina pakietu od wyników BG, dla rated powinien mieć inną strukturę. Na razie zobaczymy czy po update dalej będą errory, potem trzeba będzie tą strukturę uzupełnić.

**Comment by Alauree** [comment]
Witam, fix nic nie naprawił. Dodatkowo warto wspomnieć, że jeden team ma o wiele więcej errorów, tym razem horda nie była w stanie kompletnie grać. U nas tylko 1 osoba miała non stop errory, a tak to bardziej sporadycznie sie zdarzało. Po skonczeniu bg oczywiscie wszyscy dotaliśmy error i nie zaliczyło nam w ogóle wygranej. Tablica wyników również wciąż powoduje errory.

**Comment by Gunus** [comment]
Witam! Poprawki nic nie dały ;) Problem nadal ten sam, error za errorem. Jak kolega opisał wyżej.
W naszym przypadku (Hordy) cały czas... Dodam też, że errory te powodują bardzo mocne ,,przymulenie komputera" do takiego stopnia, że system każe wyłączyć system przyciskiem zasilania. Miałem tak ja i ktoś jeszcze. Całe Rated miałem zawieszony komputer przez właśnie ten error. 
Nadal wina tablicy. Zauważyłem jeszcze, że do momentu kiedy jej nie otwarłem było jeszcze w miarę okej.

**Comment by Wolffenstein** [comment]
Ja wam dam "High Priority"...

**Comment by debtheone** [comment]
a co w tym nie jest high prio ?

**Comment by Wolffenstein** [comment]
High Priority jest zarezerwowane dla rzeczy, które absolutnie muszą być naprawione jak najszybciej, ponieważ
a) Ludzie coś mogą bugować
b) Crashuje serwer albo mocno utrudnia grę.

Rated BG to po prostu nie działający feature, jak wiele na privach.

**Comment by ShockRW** [comment]
Zori gdzie jestes.

**Comment by ShockRW** [comment]
Czy brak rated bg nie utrudnia mocno gry zainteresowanym niemniej niż questy w Dun Morogoh ?

**Comment by debtheone** [comment]
bump take a look on it please

**Comment by Wolffenstein** [comment]
Na jakie mapy was wrzuciło na te rated? Eots?

**Comment by Gunus** [comment]
Ostatnie rated TP, graliśmy dwa razy i dwa razy to samo, możliwe, że problem siedzi w tym jednym. 
A było grane jakieś chyba ok. półtora miesiąca temu.

**Comment by Wolffenstein** [comment]
:) Spróbujcie rozegrać coś dzisiaj

**Comment by Gunus** [comment]
Na ptr można?  Bo nie wiem czy znajdziemy przeciwników na dziś. A i pytanie czy tworząc postacie mamy full Lvl?  Tak możemy odpalić kilkanaście wowkow i jedziemy z koksem.

**Comment by Wolffenstein** [comment]
Nie wiem czy PTR jest online, a jeśli jest to na pewno wyłączone jest instant 85 level. Zobaczę co da się zrobić.

**Comment by Gunus** [comment]
Postaram się umówić z zaprzyjaźnioną gildią z ally, chociaż oni mniej pvp teraz...  Chyba, że ewentualnie jakieś postacie na okres przetestowania lecz to już nie od nas zależy, czekamy na odpowiedź ;)

**Comment by Wolffenstein** [comment]
PTR jest aktualizowany, niedługo powinien być online z instant 85.

**Comment by Gunus** [comment]
Okej bierzemy się do roboty ;)

**Comment by Wolffenstein** [comment]
PTR online.

**Comment by debtheone** [comment]
My (where the dodges begins) mozemy chetnie potestowac tylko trzeba przeciwnikow, ktos chetny?

**Comment by debtheone** [comment]
Zagralismy gilneas i wsg.
BUGI:
Visual combatu(nie ma go na portrecie) pokazuje ze mozemy uzywac  stuff jak mount picie(nie jest na szaro) ale combat jest. 
2) Debuff na wsg i pewnie  tez TP stackuje sie zbyt wolno 
http://www.mmo-champion.com/threads/1030050-Rated-Battlegrounds-Flag-Carrier-Debuff
http://www.wowhead.com/spell=46392/focused-assault#changelog

**Comment by Kejmil** [comment]
ress na cmentarzu powinien byc co 45sec na rated, nie co 30

**Comment by Kejmil** [comment]
Pula map do rated:
Warsong Gulch
Arathi Basin
Eye of the Storm
Strand of the Ancients
Battle for Gilneas
Twin Peaks

nie wyskoczylo nam sota i eots w trakcie testow
przy czym eye to powinna byc zupelnie inna mapa - odkad znowu wprowadzono ja do puli rated dla 10 osob punkty przejmuje sie tak samo jak na ab, a wokol flagi sa "skalki" uniemozliwiajace w znacznym stopniu zrzucanie ludzi (https://www.youtube.com/watch?v=FYY5tjdFOGI)

**Comment by Kejmil** [comment]
po uzyskaniu capa conquest pointow rated battlegroundy powinny zamiast nich dawac honor
http://us.battle.net/wow/en/forum/topic/1648733522?page=1#1

**Comment by Kejmil** [comment]
ponadto, tak jak i na zwyklych bg jest problem z widocznoscia flagi (albo jest to problem tylko z flaga alliantow, albo z flaga druzyny przeciwnej, poprawie tutaj jak bede wiedziec na pewno)

**Comment by Wolffenstein** [comment]
Nie mam pomysłu na tę aliancką flagę, coś się zmieniło 4.0.6->4.3.4 ale jeszcze nie wiem co.

**Comment by Tj20** [comment]
If I understand this right via google translate, the position of the flags in the battlefield is not shown correctly?

As far as I understand, the client gets their positions and textures via

[GetNumBattlefieldFlagPositions()](http://wowprogramming.com/docs/api/GetNumBattlefieldFlagPositions) and
[GetBattlefieldFlagPosition(index)](http://wowprogramming.com/docs/api/GetBattlefieldFlagPosition)

It returns the X,Y coordinates and "flagToken - Unique portion of the path to a texure for the flag". So if only the alliance flag is missing, maybe the path to the texture is just wrong?

(I've had a look at [Blizzard_BattlefieldMinimap.lua](http://wowprogramming.com/utils/xmlbrowser/test/AddOns/Blizzard_BattlefieldMinimap/Blizzard_BattlefieldMinimap.lua) which I think belongs to WoD, but I guess the funtions were more or less the same in Cata.)

![picture:Blizzard_BattlefieldMinimap.lua](http://i.imgur.com/aUcbxjN.jpg)

**Comment by Wolffenstein** [comment]
Nope, it was a packet issue. It will be fixed in rev 4424.

**Comment by debtheone** [comment]
jak idą prace?

**Comment by Jenovas** [comment]
A działają poprawnie areny? Jak tak to można sie brać za przepisywanie BG i Rated BG.

**Comment by debtheone** [comment]
ciężko powiedzieć, 3v3 nie żyje, a dwujek na wysokim racie też coś nie ma

**Comment by debtheone** [comment]
3v3 hvsh dziala git, dzeina

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by deadlycalm** [comment]
bump

**Comment by debtheone** [comment]
wiadomo co z fixem?
