### ISSUE TITLE
[EN] [Quest] [Uldum] Forunte and Glory

### ISSUE THREAD

**Issue by Exorcista** [Atlantiss/BugTracker#2316]
The following quest Forunte and Glory: http://www.wowhead.com/quest=27748 doesnt works as intented and cant be completed somethimes.

<b>::How it Works</b>: all event goes well, but when you kill the Obsidian Collossus, you dont get credit at all for the quest, hence impossible to compelte.

<b>::How should it work</b>: Credit should be given and quest completed.

<b>Video for reference</b>: https://www.youtube.com/watch?v=6EAqe86Ncow

**Comment by Wolffenstein** [comment]
Fixed in rev 4345.
