### ISSUE TITLE
[EN]  [Coastal Delicacies!] [Hillsbrad Foothills] 

### ISSUE THREAD

**Issue by KEEPSANE** [Atlantiss/BugTracker#2319]
In the quest  [Coastal Delicacies!] the spider does not eat the murlocs you kill. Quest chain in this area can not be completed.

**Comment by Wolffenstein** [comment]
Are you close enough to murloc corpses? The spider needs to be in 2yd range.

**Comment by Wolffenstein** [comment]
Fixed in rev 4346.

**Comment by afuchi** [comment]
Its still broken actually, at least for me
