### ISSUE TITLE
[EN] [Quest] [Deepholm] Block The Gates

### ISSUE THREAD

**Issue by Exorcista** [Atlantiss/BugTracker#2320]
Quest http://www.wowhead.com/quest=26861/block-the-gates, doesnt work at all

<b> How it works </b>: when using the item <b>Stormstone - 60501</b> on any of the gates it doesnt give any credit at all.

<b>How should it work</b>: Credit should be given.

<b>Additonal comment</b>: Is blocking a major questline to unlock Therazane reputation in the zone.

**Comment by Satyr87** [comment]
i confirm http://www.wowhead.com/item=60501/stormstone can be used anywhere but doesnt disrupt the gate
im surprised because this quest worked like 2-3 weeks ago and now got broken , like a punch in the face from surprise while questing

**Comment by Wolffenstein** [comment]
Fixed in rev 4346.

**Comment by Aph1d** [comment]
Bump. Not working.
