### ISSUE TITLE
[EN]  [spell] Cheap Shot & Pounce (critical)

### ISSUE THREAD

**Issue by Chulain** [Atlantiss/BugTracker#2321]
Currently Cheap Shot and Pounce share Diminishing Returns (DR) with all the other stuns.

These 2 stuns are supposed to have their own DR rule.

source: http://www.wowwiki.com/Diminishing_returns?oldid=2568823 ( 04:55, July 28, 2012 )

Opener Stun - Cheap Shot, Pounce 

Controlled Stun - Bash, Concussion Blow, Deep Freeze, Demon Charge, Gnaw, Holy Wrath, Inferno Effect (Doomguard summon), Hammer of Justice, Intercept (Felguard), Intercept (Warrior), Intimidation, Kidney Shot, Maim, Ravage, Shadowfury, Shockwave, Sonic Blast, War Stomp, Throwdown

**Comment by Ivanfool** [comment]
This is incorrect, the only stun that has a separate DR is Charge stun. It has been like this since the release of Cataclysm. Also, that thread clearly shows both Cheap Shot and Kidney Shot as Controlled Stuns.

**Comment by Chulain** [comment]
you're right, i found several videos that prove me wrong, i'm just trying to find the patch now
