### ISSUE TITLE
Falling through the ground

### ISSUE THREAD

**Issue by Creeo** [Atlantiss/BugTracker#2325]
When you play as the race goblin and die at the quest "Kaja'Cola Gives You IDEAS! (TM)" by the volcano at The Lost Isles you fall and release  your sperit, you fall through the ground. After spamming the Return To Graveyard button ~5-10 times I get teleported to the air and I am given a parachute. I see that it's a temporary fix for problems like these but It would improve the gameplay if this was fixed.

Thank you for your epic server hosting and for fixing this issue :)

**Comment by Varchord** [comment]
title, wowhead links
