### ISSUE TITLE
[EN][Tol Barad Peninsula][The Restless Front]

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#2327]
When using charge in the restless front, a unknown error will crash wow and freeze the screen, i have tried charging 4 times in this specifc area and each time i have crashed, however i tested charging in other areas and they seemed to work fine.
![wowscrnshot_022115_140719](https://cloud.githubusercontent.com/assets/10423624/6314350/84a62a64-b9d3-11e4-9e3a-2a5f9db10b39.jpg)

**Comment by Bildo** [comment]
duplicate
