### ISSUE TITLE
[PL][Quest]Smoot's Samophlange

### ISSUE THREAD

**Issue by Maksi85** [Atlantiss/BugTracker#2328]
Levelując postać i przechodząc przez krainy wprowadzone w Cata (Mount Hyjal, Deepholm i Uldum) chwaliłem serwer za skrypty i działanie praktycznie WSZYSTKICH questów. Na 84 poziomie zdecydowałem pójść do Twilight Highlands... problem w tym, że co 2 quest nie działa.
Pomijam kilka questów, które da się ominąć/dzialały na dzień następny.
A zresztą... lepiej zobaczcie sami.
http://i.imgur.com/az8R8iB.jpg
Tak, quest wymaga ode mnie bycia w BATTLE STANCE.
Problemem jest to, że jestem Warlockiem, a JEDYNIE Warrior posiada tą umiejętność.
Rozumiem gdyby to był starszy content, ale jest to misja z dodatku na którym serwer się opiera, więc nie wyobrażam sobie dlaczego Northrend działa lepiej od misji na 84 poziom.

**Comment by Navedonar** [comment]
Twilight Highlands jest zamknięte
