### ISSUE TITLE
[PL][Event][Lunar Festival] Elder Rumblerock

### ISSUE THREAD

**Issue by hardrockcafe97** [Atlantiss/BugTracker#2331]
Brak NPC:
Elder Rumblerock - http://www.wowhead.com/npc=15557/elder-rumblerock#screenshots:id=211301

Wiele osób zaliczyło go. Problem leży prawdopodobnie w fazach (w jaskini w tej górze- Firegut Furnace pojawiają się i znikają Orki gdy po niej chodzę). Zdobyty Achievement za krainę. Przy pomocy addonu szukałem jakichkolwiek questów- nie znalazłem.

Screen:
http://screenshooter.net/101985963/olvxdkx

**Comment by Hordraric** [comment]
I did a ticket b4 with he same information. Youre phased just askgm to unphase

**Comment by armano2** [comment]
#2250
