### ISSUE TITLE
[PL][Quest]"The Western Pylon"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2333]
Nad Western Crystal Pylon ( http://www.wowhead.com/object=164956/western-crystal-pylon ) wciąż unosi się niebieski pytajnik ,mimo że quest został usunięty. 

Link: http://www.wowhead.com/quest=4288/the-western-pylon

**Comment by Navedonar** [comment]
http://www.wowhead.com/quest=24723/the-western-pylon nie został usunięty

**Comment by Danelar** [comment]
No to jednak mamy bug, ale inny - ale mamy!
