### ISSUE TITLE
[PL][Quest]"The Eastern Pylon"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2334]
Nad Eastern Crystal Pylon ( http://www.wowhead.com/object=164957/eastern-crystal-pylon ) wciąż unosi się niebieski pytajnik , mimo że quest został usunięty.

Link: http://www.wowhead.com/quest=4287/the-eastern-pylon

**Comment by Navedonar** [comment]
http://www.wowhead.com/quest=24721/the-eastern-pylon nie zostal usunięty

**Comment by Danelar** [comment]
Ale go nie ma - bug jest!
