### ISSUE TITLE
[PL][Quest]"The Northern Pylon"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2335]
Nad Northern Crystal Pylon ( http://www.wowhead.com/object=164955/northern-crystal-pylon ) wciąż unosi się niebieski pytajnik, mimo że quest został usunięty.

Link: http://www.wowhead.com/quest=4285/the-northern-pylon

**Comment by Navedonar** [comment]
http://www.wowhead.com/quest=24722/the-northern-pylon nie został usunięty

**Comment by Danelar** [comment]
Ale nie można go otrzymać - więc bug wciąż jest.
