### ISSUE TITLE
[PL] Error

### ISSUE THREAD

**Issue by zbix6652** [Atlantiss/BugTracker#2337]
Exe:      D:\AT cata\WoW.exe
Time:     Feb 22, 2015 12:32:01.726 AM
User:     Komp
Computer: KOMP-KOMPUTER
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal condition!

http://zapodaj.net/4e988108b440b.jpg.html

Nie wiedzialem gdzeie sie to zglasza

**Comment by aje** [comment]
wow error 134 are related to corruptions of your client
try to redownload the client http://atlantiss.eu/pages/1
