### ISSUE TITLE
[EN][Western Plaguelands] Hearthglen Mustangs are not disappearing after use

### ISSUE THREAD

**Issue by idontknow12** [Atlantiss/BugTracker#2340]
This is possibly causing server overload...
http://www.wowhead.com/spell=83771/hearthglen-mustang
The mustangs are used in
http://www.wowhead.com/quest=27000/learning-the-ropes
and
http://www.wowhead.com/quest=27001/this-means-war-wild-arachnid-roundup

![wowscrnshot_022115_190116](https://cloud.githubusercontent.com/assets/10792691/6317188/564121ea-ba25-11e4-921a-7e14d4b3e19c.jpg)

**Comment by Bildo** [comment]
fixed
