### ISSUE TITLE
Quest: Unexpected results

### ISSUE THREAD

**Issue by fakeyoulolxx** [Atlantiss/BugTracker#2343]
bag, nope mobs

**Comment by fakeyoulolxx** [comment]
bag, nope mobs

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1813

**Comment by fakeyoulolxx** [comment]
ssory. russian here


Воскресенье, 22 февраля 2015, 2:11 -08:00 от Navedonar <notifications@github.com>:
>#1813
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Denis abramov
fakeyoulolxx@mail.ru
