### ISSUE TITLE
[EN] The master planner

### ISSUE THREAD

**Issue by stenli8** [Atlantiss/BugTracker#2344]
Whats bugged? the master planner doesnt drop the blueprints
not really too important :P

**Comment by Varchord** [comment]
Title, links

**Comment by stenli8** [comment]
http://www.wowhead.com/quest=10001 thats the quest
http://www.wowhead.com/npc=18567/moarg-master-planner thats the npc

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
