### ISSUE TITLE
[PL][Item] Satchel of Exotic Mysteries

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#2345]
Paczka z Call to Arms : Tank/Heal/Dps na 95% nie posiada lootu. Wszyscy którzy ja otwierają mają tylko napis : "This slot is empty". Sam otworzyłem już 3 i każda bez lootu.
http://www.wowhead.com/item=69903/satchel-of-exotic-mysteries
Edit : Jednak 100% ponieważ z każdej powinien dropic gold +-50-100 a nie dropi.

**Comment by Wolffenstein** [comment]
Zgadza się, póki co chciałem zobaczyć jak Call to Arms się sprawuje, więc nie dodawałem jeszcze lootu.

**Comment by Aviannaqt** [comment]
Wydaje mi sie ze CTA : Dps troche źle działa. Prawdopodobnie działa tak jak reszta - do 1 osoby a powinno do 3

**Comment by Wolffenstein** [comment]
Nope, ma inny przelicznik. Ale jeżeli występuje zbyt często to mogę go zmienić.

**Comment by Aviannaqt** [comment]
Niby występuje tak samo jak reszta, ale rzadko łapie przy zapisie ale to chyba nie od tego zależy ;)

**Comment by Drutmaster** [comment]
Był też motyw, że zapisałem się na df-a, pokazało mi, że paczkę dostanę, ale niestety po zabiciu lasta valory dostałem, a paczki w bagu nie było (miejsce w bagach miałem)

**Comment by Wolffenstein** [comment]
Jeżeli jakiś gracz został dodany ręcznie do PT w trakcie robienia DFa to paczki się nie dostanie.

**Comment by Aviannaqt** [comment]
Pytanie tylko czy wyfarmione teraz paczki po dodaniu lootu będą go miały, czy nie, bo jeśli nie to nie opłaca mi sie ich farmic xd

**Comment by Wolffenstein** [comment]
Po dodaniu lootu będą go miały.

**Comment by Drutmaster** [comment]
Nie był dodany nikt do df-a, był to heroic z rdf-a z tym, że po jego zakończeniu nie dostałem paczki (mimo, że w momencie "wyskoczenia" okienka df-a była ona w nagrodach - za bycie tankiem)

**Comment by Wolffenstein** [comment]
To będę musiał to zbadać, widocznie jest jakiś przypadek, gdy się nie dostaje pomimo bycia wybranym na CtA.

**Comment by Aviannaqt** [comment]
Mozna wiedziec loot bedzie wgrany ?

**Comment by nerv234** [comment]
Bump:) można by było już dodać loot.

**Comment by Wolffenstein** [comment]
Fixed in rev 4367.
