### ISSUE TITLE
[PL][Raid] Eye of Eternity - Malygos

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#2347]
http://www.wowhead.com/zone=4500/the-eye-of-eternity
http://www.wowhead.com/npc=28859/malygos
Raid jest obecnie trudny do zrobienia w mniejszej grupie, ponieważ smoki w 3 fazie (Red drakes, nie ma linku) nie posiadają energii oraz spawnują się za nisko i trzeba kilkanaście sekund leciec w góre aby doleciec do bossa. 
Raid można ukończyć tylko poprzez zlecenie z mounta w 3 fazie i ręczne dobicie - tutaj kolejny bug, gdy zlecimy jakies 30yd poniżej bossa nie zalicza już nam achievementów za zabicie, lub zburstowanie bossa w 1 fazie, ale do tego trzeba miec juz więcej osób. 
Add : Bossa w 3 fazie nie ma wogóle.

**Comment by Asavel** [comment]
Lepiej bys napisał że boss działa jak kukła i można go w rootsach,stunach trzymac ;p

**Comment by Aviannaqt** [comment]
Nawet nie wiedzialem o.0 Tyle, że on i tak nic nie robi xd

**Comment by Holywhisper** [comment]
probowalismy zrobic tego bossa dzisiaj, w 3 fazie mozna bylo latac na smokach, ale boss zniknal. Po resecie niemozliwe bylo jego ponowne odpalenie i nie byl widoczny w inscie

**Comment by nerv234** [comment]
Na dzisiejszy dzień smok jest widoczny, natomiast w 3 fazie mounty(smoki) nie mają energii którą powinny mieć.

**Comment by Aviannaqt** [comment]
!Bump
Na 3 fazie nie ma bossa i zpawnuje nas w jakims smiesznym miejscu pod platworma ;x

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/960

**Comment by fruvel** [comment]
boss w 3 fazie siedzi w teksturach i nie da sie go dobic ..
