### ISSUE TITLE
[EN][Quest][Ironforge] Seize the Ambassador

### ISSUE THREAD

**Issue by FrostCZE** [Atlantiss/BugTracker#2348]
Quest cant be complete, because Ambassador Slaghammer is missing.
quest: http://www.wowhead.com/quest=26118/seize-the-ambassador
npc: http://www.wowhead.com/npc=42146/ambassador-slaghammer

**Comment by Navedonar** [comment]
![wowscrnshot_030215_100106](https://cloud.githubusercontent.com/assets/1525533/6437797/2a7de3d2-c0c3-11e4-92ee-eb4c0dd70c03.jpg)
