### ISSUE TITLE
[EN][NPC][The Bastion of Twilight] Ascendant Council

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#2349]
http://www.wowhead.com/npc=43735/elementium-monstrosity
Everything was fine with the encounter up until the 3rd phase when all the elementals combine and form the Elementium Monstrosity. Killed him as usual but instead of getting his corpse to loot at the end it completely bugged out. Once he "died", he dissapeared, we were all stunned in a bubble (same as when the transition between phase 2 and 3 happens) and then he reappeared with 0 HP frozen in place. We couldn't attack him or do anything to him. I mention that we killed him as he was doing the Gravity Crush ability ( http://www.wowhead.com/spell=84948/gravity-crush ).
I even got a screenshot: http://imgur.com/Kfyi2nQ
Managed to get a GM to help us out with it but even once he reset him and killed him himself it ended up the same and we had to give up on the loot. The door to Cho'gall opened as usual and we were able to continue at least.

**Comment by Holywhisper** [comment]
same problem here, monstrosity stays with 0 hp without loot, doors opened

**Comment by qubuslabadz** [comment]
Fixed in rev. 4348
