### ISSUE TITLE
[PL][Item] Znikające staty z itemów

### ISSUE THREAD

**Issue by Natureone** [Atlantiss/BugTracker#2352]
Posiadam sworda http://www.thottbot.com/item=68127 w moim przypadku jest to  ...of the Undertow który powiniem dawać 219 staminy 146 intelektu 97 haste 97 spirit i 1954 spell power i niewiadomo dlaczego ostatnio zniknął mu spirit.

**Comment by Alandiel** [comment]
Każdy miecz z Al'Akira nie daje jednego ze statów. Do tego reforge na itemach z Al'Akira czy Conclave nic nie zmienia.
