### ISSUE TITLE
Smity Hammerhead: No Supplies

### ISSUE THREAD

**Issue by kidwest** [Atlantiss/BugTracker#2354]
The vendor Smity Hammerhead has no supplies and doesn't even open up any shop. He is located in the Cape of Stranglethorn.

**Comment by Technowizard15** [comment]
You should change the headline of your report to:

[Eng][NPC][The Cape of Stranglethorn] Smity Hammerhead: No Supplies

and a link like http://www.wowhead.com/npc=44195/smity-hammerhead should always be added, else the report will most likely be closed.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
