### ISSUE TITLE
[PL][Item]"Twilight Trappings Set"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2355]
Czy on powinien być jeszcze w grze? Questa na rozmowę z kryształami nie ma, a kamienie zmieniły kolor i nazwę na "Wind Stone" (  http://www.wowhead.com/object=180461/wind-stone ) 

Link: http://www.wowhead.com/itemset=492/twilight-trappings

**Comment by Navedonar** [comment]
powinien być

**Comment by Danelar** [comment]
No ale questa nie ma :<

**Comment by Navedonar** [comment]
the wind stones no longer function. The cowl, robe, and mantle are now for decoration only

**Comment by Danelar** [comment]
OK :)
