### ISSUE TITLE
[PL][Warrior][spell][talent] Thunderstruck talent doesnt increase shockwave dmg

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#2359]
Talent Thunderstruck nie zwieksza dmg shockweave a powinien go zwiekszac nawet o 30%. Spora strata dmg zwlaszcza na aoe.

**Thunderstruck:**
http://www.wowhead.com/spell=80980
87095 (1 rank) 87096 (2 rank) id znalozione za pomoca addona TellMeWhen

**Shockwave:**
http://www.wowhead.com/spell=46968/shockwave

**Comment by Wojmistrz** [comment]
kolejne do zgłoszenia jest to że SHOCKWAVE NIGDY NIE KRYTUJE a z tego co wiem powinien!!!!!!! jak każdy inny skill.....

zawsze ma 0% kryta.......

**Comment by Wolffenstein** [comment]
Fixed in rev 4352.
