### ISSUE TITLE
[PL][Object]"Wildkin Feather"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2360]
Nie posiadam questa, a i tak mogę je zbierać. Ponadto są potrzebne tylko w zadaniu dla Kapłana, a ja jestem Magiem. 

Link do Questa: http://www.wowhead.com/quest=3661/favored-of-elune

Link do Projektu:  http://www.wowhead.com/object=153239/wildkin-feather

**Comment by Navedonar** [comment]
http://www.wowhead.com/quest=27362/favored-of-elune

**Comment by Danelar** [comment]
Ja tam gram hordą i nie patrzyłem na to - xD - w każdym razie bugiem jest fakt, że mogę to zebrać - a nie quest :>

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Danelar** [comment]
Dziękuję :)

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
