### ISSUE TITLE
Dunemaul Compound mobs not attackable

### ISSUE THREAD

**Issue by Zollo11** [Atlantiss/BugTracker#2365]
Problem is that you can't attack most of mobs in Dunemaul Compound.
http://tinypic.com/r/4j500w/8

How it should work:
You should be able to attack every mob in that area. 
Watch this video https://www.youtube.com/watch?v=8hNZKO7IYHg

**Comment by PVPViddys** [comment]
Same issue, Invalid target

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2207
