### ISSUE TITLE
[PL][Quest][Deepholm] Take Him to the Earthcaller

### ISSUE THREAD

**Issue by romigrabarz** [Atlantiss/BugTracker#2367]
Rev. 4346

Quest - http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller
Nie da się wykonać zadania. NPC nie reaguje na przyprowadzonego companiona.

**Comment by freddie12** [comment]
ya, i agree that as well. it is not working.

**Comment by Kesee** [comment]
Działa u mnie (robiłem wczoraj kolo 23)

**Comment by TheRealCiapaty** [comment]
Możliwe, że quest działa ale cholernie ciężko jest odpowiednio ustawić tego companiona aby zaliczyło... Jak levelowałem postać jakieś 5 miesięcy temu to pamiętam, że musiałem się sporo nabiegać żeby mi w końcu zaliczyło questa. :)

**Comment by romigrabarz** [comment]
Mi też już zaliczyło quest. Prawdopodobnie restart serwera naprawił sytuacje.
