### ISSUE TITLE
[PL][Item]"Loregrain's Grimoire"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2368]
Powyższy przedmiot nie wypada z Loregrain's Grimoire   (      http://www.wowhead.com/npc=9024/pyromancer-loregrain ).

Link: http://www.wowhead.com/item=64305/loregrains-grimoire

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Danelar** [comment]
Danke :)

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
