### ISSUE TITLE
[PL][NPC]"Ribbly Screwspigot"

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#2369]
Nie da się go zaatakować, ponieważ ma status Friendly, a gdy z nim rozmawiam to mówi tradycyjne "Greetings <Name>" i nic. 

Link: http://www.wowhead.com/npc=9543/ribbly-screwspigot

**Comment by Navedonar** [comment]
https://www.youtube.com/watch?v=pcIAd9cN9sY
