### ISSUE TITLE
[pl][achievement] Abuse the Ooze

### ISSUE THREAD

**Issue by Holywhisper** [Atlantiss/BugTracker#2370]
http://www.wowhead.com/achievement=2155/abuse-the-ooze 
Nie zaliczylo po zbiciu odpowiednich addow i nastepnie bossa

**Comment by Drutmaster** [comment]
jesteś pewien, że zabiłeś odpowiednie addy?

**Comment by Bildo** [comment]
juz sprawdzam czy dziala

**Comment by Holywhisper** [comment]
sprawdzalem, robilem juz kiedys, tak zbijalismy te gluty, przedtem zrobilismy serie dungeonow i porobilismy wiekszosc achi do glory, wiec raczej przy tym nagle nie doszlo do pomylki, jesli trzeba przejdziemy sie jeszcze raz jutro by to sprawdzic

**Comment by jurek1** [comment]
w styczniu robilem to dzialalo
