### ISSUE TITLE
[PL][Quest][Blade's Edge Mountains] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by Elhalli** [Atlantiss/BugTracker#2381]
Link do WoWheada: http://www.wowhead.com/quest=10565/the-stones-of-vekhnir
Mając Q item tj. http://www.wowhead.com/item=30567/charged-vekhnir-crystal i Complete w Quest logu nie można oddać questa do NPC.

**Comment by Technowizard15** [comment]
Sorry if I reiterate some points but Google Translator let me down.
When taking the quest no quest markers appear on the map. To complete the quest you have to quit it when you have the "Charged Vekh'nir Crystal" and accept it a second time, only then will you be able to submit it.

**Comment by meowmewo** [comment]
STILL cant finish the quest after getting the item.

**Comment by Norfik** [comment]
Can't drop the quest item. Killed whole village several time for several days with no luck. Deleting cache and retaking quest didn't helped at all.

**Comment by Norfik** [comment]
```sql
-- fix Blizzard addon to show where can be find mobs for quest
DELETE FROM `quest_poi` WHERE `questId`=10565;
INSERT INTO `quest_poi` (`questId`, `id`, `objIndex`, `mapid`, `WorldMapAreaId`, `FloorId`, `unk3`, `unk4`, `VerifiedBuild`) VALUES
(10565, 1, 10, 530, 475, 0, 0, 5, 0),
(10565, 2, -1, 530, 475, 0, 0, 5, 0),
(10565, 3, 5, 530, 475, 0, 0, 5, 0);

DELETE FROM `quest_poi_points` WHERE `questId`=10565;
INSERT INTO `quest_poi_points` (`questId`, `id`, `idx`, `x`, `y`, `VerifiedBuild`) VALUES
(10565, 1, 7, 1617, 4649, 0),
(10565, 1, 8, 1628, 4629, 0),
(10565, 1, 9, 1648, 4593, 0),
(10565, 1, 6, 1648, 4687, 0),
(10565, 1, 5, 1683, 4700, 0),
(10565, 1, 0, 1697, 4574, 0),
(10565, 1, 1, 1746, 4594, 0),
(10565, 1, 2, 1762, 4619, 0),
(10565, 1, 3, 1780, 4653, 0),
(10565, 1, 4, 1780, 4678, 0),
(10565, 2, 0, 2162, 4770, 0),
(10565, 3, 0, 1709, 4625, 0);

-- fix drop of Vekh'nir Crystal
UPDATE `creature_template` SET `questItem1` = 30561,`questItem2` = 30655 WHERE `entry` IN (19983,19984,20161);

UPDATE `quest_template` SET `RequiredSourceItemId1` = 30561 WHERE `Id` = 10565;
```

It will fix drop of the "Vekh'nir Crystal" to create  "Charged Vekh'nir Crystal" and cords on map for quest but you still need to do like Technowizard15 wrote: "To complete the quest you have to quit it when you have the "Charged Vekh'nir Crystal" and accept it a second time, only then will you be able to submit it.".
It will fix drop of the "Vekh'nir Crystal" to create  "Charged Vekh'nir Crystal" and quest markers on map for quest but you still need to do like Technowizard15 wrote: "To complete the quest you have to quit it when you have the "Charged Vekh'nir Crystal" and accept it a second time, only then will you be able to submit it.".

**Comment by Technowizard15** [comment]
Why change the drop? The quest is working, did it three times. You have to charge the "Vekh'nir Crystal" by using it in the glowing circle like in this vid:

https://www.youtube.com/watch?v=3-jpZtt9yY8

**Comment by Norfik** [comment]
I know how this quest works. Currently mobs don't drop the item used to make the quest item. Just trust me.

**Comment by aranguard** [comment]
Bump. Tried it today and still not drop.Killed all mobs in village but no item.Last 3 quests left for area achieve and couldnt get outland loremaster achieve couse of that1.

**Comment by Norfik** [comment]
Bump. At least fix the quest item drop plz so horde players could achiev outland loremaster achievment.

**Comment by aranguard** [comment]
I really wondering people says this quest was working before but now not working so it must be easy to fix it.Becouse its about something you changed about last 6 monthes like fishing area bug and like flame leviathan fight in ulduar and Kel'thuzad in naxxramas etc..... Developers should protect working content first or its not gonna be development.

**Comment by Norfik** [comment]
It is easy to fix. Core and DB fixes for this quest are posted above. Fixing loot problem comes to CTRL+C and CTRL+V it's about 30 sec of work and core restart.

**Comment by aranguard** [comment]
I have very small knowledge about scripting but i m sure if any developer spare a bit time to fix that issue it shouldnt be so hard.In many places writes Outland loremaster achieveble but its not.This quest block further chains at this area.Leoroxx not giving any quest couse of that1.

**Comment by Bildo** [comment]
fixed
