### ISSUE TITLE
[Druid] Primal Madness

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#2382]
when you have the primal madness talent, and you activate both tiger's fury and berserk, while berserk is still active, if tiger's fury goes off, you lose the 20 max energy (even if berserk is still active)
http://cata.openwow.com/spell=80317

**Comment by mati865** [comment]
@lamaATS help.

**Comment by lamaATS** [comment]
Probably I need to buy some dev kit to fix some bugs 💃 
I will try to look at this but I don't know when it will be.

**Comment by lamaATS** [comment]
Fixed in rev. 5261
