### ISSUE TITLE
[ENG][NPC][Borean Tundra] Doctor Razorgrin and Lich-Lord Chillwinter

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2383]
http://www.wowhead.com/npc=25678/doctor-razorgrin
http://www.wowhead.com/npc=25682/lich-lord-chillwinter

There are two instances of Chillwinter and Doctor Razorgrin, one inside and one on top. The one inside should be deleted from the database. The Doctor Razorgrin on top the wreckage sometimes glitches trough the wall and can therefore not be seen.

Bildo, if you are thinking about closing this report because it is essentially a copy of #1055 you should reopen that report beforehand because the problem still exists else the next guy is forced to open the second copy.

**Comment by Quban** [comment]
fix soon
