### ISSUE TITLE
[ENG][Quest][Borean Tundra] The Horn of Elemental Fury

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2384]
http://www.wowhead.com/quest=11695/the-horn-of-elemental-fury

The drop chances for the key needed to get both parts of the horn are interesting. "Burblegobble's Key" (http://www.wowhead.com/item=34961/burblegobbles-key) has a 73% drop chance, "Gurgleboggle's Key" (http://www.wowhead.com/item=34962/gurgleboggles-key) a 85% drop chance. This raises the suspicion that in reality it should be 100% but people killed the chieftains without the quest giving us a wrong chance for both keys.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Technowizard15** [comment]
Good to hear.

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
