### ISSUE TITLE
[PL][Raid-Cata] Throne of the Four Winds, Al'akir

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#2386]
http://www.wowhead.com/npc=46753/alakir

Boss na 10 normal na 1 fazie(100-80%) używa http://www.wowhead.com/spell=87873/static-shock, który powinien być używany tylko na heroicu.

Na 2 fazie spawnują się 2 http://www.wowhead.com/npc=47175/stormling naraz(oczywiście powinien wychodzić 1 co 20 sekund).

**Comment by Dziara** [comment]
Poprawka, Static Shock jest używany przez całą walkę aktualnie(na normalu). Powinien być TYLKO na 1 fazie na heroicu.

**Comment by mitim1** [comment]
Al`akir niema zaktualizowanego lootu.(4.1.0)
http://www.wowhead.com/item=69833/permafrost-cape
http://www.wowhead.com/item=69827/mistral-pendant
http://www.wowhead.com/item=69828/permafrost-choker
http://www.wowhead.com/item=69829/cloudburst-necklace
http://www.wowhead.com/item=69830/planetary-amulet
http://www.wowhead.com/item=69834/cloudburst-cloak
http://www.wowhead.com/item=69831/mistral-drape
http://www.wowhead.com/item=69835/planetary-drape
oraz prawdopodobnie 
http://www.wowhead.com/item=66998/essence-of-the-forlorn + tokeny t11

**Comment by mitim1** [comment]
Dodam ze bez tego lootu robienie al`akira jest trochę bez sensu.

**Comment by erulogoss** [comment]
dodatkowo walka z Al'Akirem powoduje błąd 132 i wywala cały raid

**Comment by mitim1** [comment]
!BUMP Dajcie chociaż ten loot bo niema sensu wgl al`akira robić.

**Comment by mitim1** [comment]
1.Lightning Rod nie ma max range, przez co zadaje dmg na platformach The Conclave of Wind oraz na platformie startowej. 
2.Po wyskoczeniu z platformy podczas trwanie encountera powrót na nią zajmuje za dużo czasu.
Filmik potwierdzający 1 i 2.
https://www.youtube.com/watch?v=hGeY1Hxv-u8 
1.   0,56-1,00
2.   1,12-1,20

**Comment by mitim1** [comment]
Podczas bicia al`akira nastąpiło dc, po powrocie na server zastaliśmy to xD :
[img]http://i62.tinypic.com/344owvr.jpg[/img]
[img]http://i58.tinypic.com/2wlyrrt.jpg[/img]

**Comment by Quban** [comment]
Prędkość powrotu na platformę wydaje się być prawidłowa https://youtu.be/BQA3rauaV70?t=7m6s, na tamtym filmie wyskoczył 2x hunter i powrócił od razu przez użycie Disengage

**Comment by mitim1** [comment]
Prosil bym o napisanie co dokładnie zostało naprawione

**Comment by Quban** [comment]
Powrot powinien trwac okolo 15s i  nigdy mi sie nie zdazylo wracac dluzej. W jakiej sytuacji sie wraca az minute?
