### ISSUE TITLE
[PL][QUEST][Ebon Hold] Grand Theft Palomino

### ISSUE THREAD

**Issue by Alinous0** [Atlantiss/BugTracker#2388]
Ten quest nie powinien być zaliczony po zabiciu konia tylko powinna być możliwość wsiadania na niego i należy na nim dojechać do NPC dającego q czyli http://www.wowhead.com/npc=28653 i użyć skilla nr 1 konia.

**Comment by sunshineinabox** [comment]
Hello I ran into an issue with this quest where when I get on the horse Gallop is not usable. It moves very slowly and anytime you agro something it goes out of control and you can't control the horse anymore. I made a ticket and a GM completed the quest for me, but I've talked with other DKs and they have been able to do it in the past. As recently as 2 days ago.

**Comment by sunshineinabox** [comment]
Why was this issue closed the issue in my comment is still preset.
