### ISSUE TITLE
[PL] Raid ID

### ISSUE THREAD

**Issue by Liska23** [Atlantiss/BugTracker#2390]
Nie zresetował sie u mnie CD na Bastion of twilight nie mozna tego jakos naprawic wkoncu zeby to sie poprawnie robilo

**Comment by Pazurek** [comment]
Raczej u nikogo się nie zresetowało, na wszystkich postaciach, którymi robiłam Bota nabiło się ponownie ID na tydzień. BWD się zresetowało, ale BOT już nie.

**Comment by Arcadia713** [comment]
Potwierdzam na BoT zostaje + na niektóre raidy ze starszego contentu.

**Comment by Dziara** [comment]
Nawet na 5-man heroic pozostawały

**Comment by Kozuro** [comment]
Idźcie robić q, a nie zaśmiecacie bug tracker.
