### ISSUE TITLE
[EN][Spell][Rogue] Cloak of Shadows

### ISSUE THREAD

**Issue by Fyriel** [Atlantiss/BugTracker#2391]
Cloak of Shadows does not make you completely immune to some spells such as Death Coil. This might affect other spells such as Traps, Frost Novas, Seduction as well - happens in many other private servers; needs more testing for sure.

OpenWow Link: http://cata.openwow.com/spell=31224
Tooltip: Instantly removes all existing harmful spell effects, provides a brief moment of immunity against magical damage and harmful effects, and then causes you to resist ALL spells for 5 sec. Does not remove effects that prevent you from using Cloak of Shadows.
Proof: http://i.imgur.com/nhJuHd1.jpg

**Comment by kadi2** [comment]
Already exists https://github.com/Atlantiss/BugTracker/issues/2080

**Comment by MasterK15** [comment]
Problem byl juz na 406
