### ISSUE TITLE
[EN][Quest][Plaguelands: The Scarlet Hold] Massacre at Light's Point

### ISSUE THREAD

**Issue by eltoino7** [Atlantiss/BugTracker#2393]
Once taking the mine cart to sneak into the Scarlets' ship, all the mobs become friendly and thus untargetable. The only way to kill them is by the canon's AOE, during which they stand passively, but once the quest's 100 are killed, it can't be turned in. The NPCs by the quest-givers are all now hostile and will kill. The Scarlet mobs even defended me as I tried to turn in the quest. I have tried this on a DK Dreani twice, now a Worgen, deleting the cache, with no progress. 
http://www.wowhead.com/quest=12701/massacre-at-lights-point

![wowscrnshot_022515_154114](https://cloud.githubusercontent.com/assets/11200552/6380815/61522420-bd0a-11e4-86ae-9392ea04d230.jpg)
![wowscrnshot_022515_154327](https://cloud.githubusercontent.com/assets/11200552/6380814/614f24dc-bd0a-11e4-8700-858e53ae1c57.jpg)

**Comment by ligitm** [comment]
1 possible fix instead of mobs friendly have the cart cast invisibility and clear invis on exit but the workaround till fixed is dont use the cart go behind the tower and run up the beach to the ship

**Comment by Muramas** [comment]
This is a game breaking bug, please set to high priority.

**Comment by Aurelia1993** [comment]
I fixed it by relogging. Of course, I couldn't use the mine cart. But at least it fixed the friendly problem.

**Comment by ylluminarious** [comment]
My only way around this was to not use the minecart and run down to the ship manually. But that was a cumbersome and dangerous step for this. It would be nice to do this quest properly.

**Comment by BAndysc** [comment]
Fixed in rev 4850
