### ISSUE TITLE
[ENG][Quest][Blade's Edge Mountains] Felling an Ancient Tree

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2396]
http://www.wowhead.com/quest=10489/felling-an-ancient-tree

Again the problem with people killing a mob without the quest. The drop rate given for "Stronglimb Deeproot's Trunk" (http://www.wowhead.com/item=30177/stronglimb-deeproots-trunk) is 94%, but it should be 100%.

Update: Looked it up at http://eu.battle.net/wow/en/item/30177 , the listed drop chance is "Guaranteed".

**Comment by Navedonar** [comment]
fixed soon

**Comment by Navedonar** [comment]
fixed http://atlantiss.eu/changelog#rev4353
