### ISSUE TITLE
[EN][Dungeon][Core] Deserter Debuff

### ISSUE THREAD

**Issue by ASX89** [Atlantiss/BugTracker#2397]
Everyone in the party gets debuff for leaving party, including the last two person 2/5 to leave.
This is not the way it should work.

**Comment by Wolffenstein** [comment]
Can I get a screenshot of this happening?

**Comment by Golonqa** [comment]
I was the last one leaving the dungeon :hankey: 
http://s21.postimg.org/3wnyrc2qv/image.jpg

**Comment by Wolffenstein** [comment]
It's not a bug and it's not a Deserter debuff either. Read more about it here http://eu.battle.net/wow/en/forum/topic/900710580 and here http://www.wowhead.com/spell=71328/dungeon-cooldown

**Comment by ASX89** [comment]
it was not that what i meant, i mean when 3 players leave, the 2 players left in party group get Deserter Debuff.
