### ISSUE TITLE
[EN] Battle of the Crimson Watch > Offering of the Sha'tar

### ISSUE THREAD

**Issue by Caturix** [Atlantiss/BugTracker#2398]
I've completed quest Battle of the Crimson Watch, and received item http://cata.openwow.com/item=31408 + ring that I've chosen. As you probably know, Offering should contain Tabard of Illidari, but once I tried to open it, it said that it's empty.

I've already seen few players with tabard, i.e Morderczyk from Amicorum etc, so i'm guessing that it should work?

Ingame nickname: Caturix, Troll Mage

Best regards,
Caturix

**Comment by DuGalle** [comment]
Same thing happen to me few days ago and now the tabard vendor dont wanna give me my ilidary tabard either something witch must be available in cata.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14771-2398-offering-of-the-shatar-loot_template/

**Comment by Jenovas** [comment]
Fix in 5539
