### ISSUE TITLE
[ENG][Quest][Netherstorm] Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2400]
http://www.wowhead.com/quest=10299/shutting-down-manaforge-bnaar

The drop chance for "B'naar Access Crystal" is again wrong. Wowhead lists it at 84% in itself suspicious, but if you go to http://eu.battle.net/wow/en/item/29366 the drop chance is listed as "Guaranteed". I'm sorry but I trust Blizzard more when it comes to game facts about WoW.

When the manaforge got shut down the quest isn't listed as completed in the quest log and no question mark is set on the map marking the quest giver.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Navedonar** [comment]
fixed http://atlantiss.eu/changelog#rev4353
