### ISSUE TITLE
[ENG][Quest][Terokkar Forest] Vestments of the Wolf Spirit

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2401]
http://www.wowhead.com/quest=10018/vestments-of-the-wolf-spirit

The drop chance in wowhead for "Timber Worg Pelt" (http://www.wowhead.com/item=25812/timber-worg-pelt) is listed at 13 and 25%. I don't know how high the chance is set (doing this quest was a pain in the ass till I finally quit it after killing a heap of worgen) but if you set them according to wowhead they a definitely wrong.

openwow list them at 37/38% http://wotlk.openwow.com/item=25812
Blizzard list them as "high" whatever this means http://eu.battle.net/wow/en/item/25812

**Comment by Navedonar** [comment]
fixed soon
