### ISSUE TITLE
[EN][Spell][Warrior] Charge - Arenas

### ISSUE THREAD

**Issue by Zabiasty** [Atlantiss/BugTracker#2402]
Warrior's charge doesnt work at Ruins of Lordaeron trough the 'green' water.
Warrior's charge doesnt work at Blade Edges Arena on stone pillars.

http://cata.openwow.com/spell=100
http://www.wowhead.com/spell=100

![lordaeron-innen](https://cloud.githubusercontent.com/assets/5214950/6387546/d6de15be-bd8c-11e4-8648-0706afe8914f.jpg)
![bladeedge](https://cloud.githubusercontent.com/assets/5214950/6387574/6dd4e4ac-bd8d-11e4-8f72-ff87eedd8048.jpg)

http://www.wowhead.com/zone=3702/blades-edge-arena
http://www.wowhead.com/zone=3968

**Comment by Isuel** [comment]
confirmed. And it's not only charge, it's also intercept and bear charge.

**Comment by bgb** [comment]
Is charging mid-air even working here? Im leveling my warrior and noticed something just isnt right here... For example: im jumping/falling from cliff and want to charge mob and then It says no path available... Or: im swimming under water and cant charge other swimming mobs unless im touching ground underwater and my target mob is touching ground too... It shouldnt be like this... 
Appparently its some problem with path finding/creating. I suppose charging when shamman thunderstorm you from cliff will also doesnt work here... (and on blizz it works).

**Comment by Zabiasty** [comment]
You're right. It unfortunetly doesnt work. This is really Important, so then should fix it as soon as posibble.

**Comment by Ponyrider2** [comment]
Dont forget about intervene aswell.

**Comment by bgb** [comment]
Well thats sad... I think that current mechanism of charge/intercept/intervene etc. is just overdone... Just keep it simple: Move warrior in straight line to his target when its not out of LoS and its in his charge range (without any checking of height positions of both players).

**Comment by Jenovas** [comment]
Rev 4406 - charging from air should work now

**Comment by Kochany** [comment]
Bump it still doesn't work. For example on dalaran arena when you want to charge upward even if you shouldn't can, the target get the charge debuff and you're sitting where you are.

**Comment by Jenovas** [comment]
I didnt understand a word, please use Polish. Charging from air does work, warriors tested it already and gave me good feedback.

**Comment by lanrutcon** [comment]
Charge (and maybe all similar spells) is **not preventing** fall damage.
When you charge from a high altitude, you should not suffer fall damage.

**Comment by Jenovas** [comment]
Charge doesnt prevent but it does RESET the fall damage, so you get damage from only the fall after using charge (20-30yards).

**Comment by Kochany** [comment]
ehh nie chodzi tylko i wyłącznie o chargowanie z góry/ z powietrza czy jak to tam nazwiecie. Tak jak napisałem w przykładzie : Na dalaran arenie kiedy jestes poza platformą " na dole " i użyjesz skilla na np. warlocka, który stoi na górze i castuje w ciebie spelle, to on dostaje tylko stuna od chargy, ale ty pozostajesz tam gdzie jestes. Na innych arenach jest wiele innych sytuacji, podobnych do tych. Nie wiem z czym to jest zwiazane, ale wiem napewno, że tak być nie powinno. Pomysl, ze mozna uzywac tego buga np. jako stuna na odleglosc. A Fall damage, to akurat najmniejszy problem tego buga.

**Comment by Ponyrider2** [comment]
Wygląda to mniej więcej tak, że w miejscach gdzie kiedyś miałeś msg w postaci "path not available" teraz używając charge cd zostaje nabity target dostaje debuff (stun) a my stoimy w miejscu.

**Comment by bgb** [comment]
Potwierdzam, słowa Ponyrider2.

**Comment by bgb** [comment]
Błagam zróbcie coś z tym bo jest to strasznie wkurzające grając pvp jako warrior tutaj:/ Warrek to klasa która bardzo opiera się na swojej mobilności i właśnie szarży.

**Comment by Jenovas** [comment]
Proszę sprawdzić po revie 4473. Zazwyczaj jak Charge nie działa to wystarczy podskoczyć postacią i spamować charge, nie wiem czemu tak jest ale jakoś lepiej mu idzie liczenie ścieżki jak gracz jest minimetr nad ziemią.
