### ISSUE TITLE
[EN][Spell][Warrior] Heroic Leap - Arena

### ISSUE THREAD

**Issue by Zabiasty** [Atlantiss/BugTracker#2403]
Warrior's Heroic Leap doesnt work at Blade Edges Arena on stone pillars.
http://www.wowhead.com/spell=6544/heroic-leap
http://cata.openwow.com/spell=6544

![bladeedge](https://cloud.githubusercontent.com/assets/5214950/6387565/4d24c8da-bd8d-11e4-9887-0b41ccfbff02.jpg)
http://www.wowhead.com/zone=3702/blades-edge-arena

**Comment by Zollo11** [comment]
It actually doesn't work on other places as well. Like you can't charge and leap in same time and you should. Also when you are falling you should be able to leap on ground to avoid falling damage but it doesnt work here.

**Comment by Jenovas** [comment]
Rev 4406 - charging or using heroic leap from air should work now

**Comment by Kochany** [comment]
Bump

**Comment by Jenovas** [comment]
Please check after rev 4473. If you jump and use Heroic Leap you should be able to both jump around the green water and the lines in BE Arena. It's a hack fix but I dont have any more ideas how to fix this.
