### ISSUE TITLE
[EN][Core] shaman totems hitting through LoS

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#2409]
just as the title say's, the shaman totems are hitting through LoS. I know for sure it's bugged for magma totem (just happened in dalaran arena), didn't test with earthbind yet.

**Comment by mitim1** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by xmesaj2** [comment]
http://cata.openwow.com/spell=2484
http://cata.openwow.com/spell=8190

I can confirm it's abused on alterac valley often. Shaman can just put both totems in towers and you,re unable to sneak in as rogue, even if you're on lower floor, totems will affect you through the roof.

**Comment by Isuel** [comment]
well, there's a particular resto shammy full vici with his partner (full vici as well), who's abusing that bug just because they can't win a 100k hp mage. he did it after he couldn't reach me with the eye in ruins of lordaeron, because he was slowed and i was in LoS.

**Comment by Jenovas** [comment]
So all totems should no work when not in LoS?

**Comment by kadi2** [comment]
@Jenovas Spirit Link Totem shouldn't restore health when outside LoS, same should go for earthbind, magma and searing totem.

Saying the totems shouldn't work when not in LoS isn't correct at all. Still the totems should grant the buffs for party/raid members.

**Comment by Jenovas** [comment]
Kadi thx for the info

**Comment by Kejmil** [comment]
also grounding totem shouldn't protect ppl in los with it, buff from totem should disappear from you when you are in los with grounding

**Comment by kadi2** [comment]
@Kejmil It does here: https://youtu.be/4qsERLrW3_o?t=8m5s

**Comment by Jenovas** [comment]
Should be fixed in rev 4559
