### ISSUE TITLE
[EN] [QUEST] [Jewelcrafting]  Elemental Goo

### ISSUE THREAD

**Issue by Exorcista** [Atlantiss/BugTracker#2410]
The following quest Elemental Goo - http://www.wowhead.com/quest=25162, has incorrect drop rate as for 4.3.4 patch, as mentioned in a comment in wowhead itself regarding the drop, it says  <b>"Later in the Cataclysm expansion, the rock elementals mentioned above have a 100% drop rate. 10 kills, 10 Elemental Goo. (Patch 4.3.3)"</b> (you can read the entire comment here http://www.wowhead.com/quest=25162/elemental-goo#comments:id=1172335)

I literally wiped entire deepholm and didnt got a single drop from any elemental. This makes JC dailys (even WOTLK ones, i was trying yesterday and they have same lower drop), a pain to complete if not everyone avandoning them when they are not the "crafting X gem" ones.

I hope you guys can find a easy fix for this, thanks for the good work, cheers.

**Comment by Canderous** [comment]
While there is indeed a lower drop rate than it should be, you can go to Hyjal (right at the start) as the comments advise and you can complete it in quite a short time :)

**Comment by Exorcista** [comment]
No, i went there they dont drop, but after scouting all cata zones i found that in Twilight Highlands, the Water Elementals @ Verall Delta drop them 100% drop rate

**Comment by Canderous** [comment]
Hm, the [Scalding Rock Elementals](www.wowhead.com/npc=40229/scalding-rock-elemental) have about a 50% drop rate for me, done the quest 3 times there already.

**Comment by Frainzil** [comment]
I always went to hyjal to complete the quest for like 10 times now. Maybe the drop rate isn't correct, but they still drop it frequently :D.

**Comment by Navedonar** [comment]
fixed soon
