### ISSUE TITLE
[PL][Core] Zbugowany Stable Master

### ISSUE THREAD

**Issue by Parwers** [Atlantiss/BugTracker#2412]
Witam chciałem zamienić sobie pety i zdarzył   mi się   nietypowy dylemat, otóż kiedy chce   "dodać" jakiegoś peta  do Call Pet np. raptora  za pająka, to  pająk    znika. Poleciałem później do  Dalaranu myślałem że  może tam dobrze działa Stable Master  i tak samo   jest. Udało mi  się przywrócić  kilka petów, ale jeszcze 4 mi brak  i  nie moge  już ich przywrócić. Mam nadzieje że naprawicie  i przywrócicie pozostałe  moje pety.
1) http://zapodaj.net/d584295d5cb64.jpg.html
P.S   Jak coś to mogę  jeszcze nagrać   filmik. Problem  pojawił się  wtedy kiedy zrobiłem sobie nowy spec  Survival.
2) http://zapodaj.net/f9217ebe4ba0c.jpg.html

**Comment by krecik88** [comment]
fixed in 4979

**Comment by Lunni** [comment]
Niestety, ale w moim przypadku bug powrócił tylko dotyczy przechowania. Pierwszego peta mogłam oddać bez problemu (tego standardowego) za to oswojonego już nie ponieważ znika po wybraniu opcji dialogowej. Sprawdzałam Stable Masterów w Stormwind City i w Goldshire, ale u wszystkich dzieje się tak samo.
