### ISSUE TITLE
[EN]  [Profession]Taloring Problem

### ISSUE THREAD

**Issue by solidsnakes** [Atlantiss/BugTracker#2414]
For some reason when i make Vicious Fireweave Item ... it makes me Emberfire Item ... if i make 
Vicious Fireweave Pants it makes me  Emberfire Pants ... this problem started when i hit 515-520 Taloring .... it keeps making me the lower item and takes the items that i need for the High level Item ...

**Comment by Wolffenstein** [comment]
Because it's still 4.1 content, and those items are higher ilvl than what you should be able to make at this stage.
