### ISSUE TITLE
Druid Clearcasting

### ISSUE THREAD

**Issue by Kimbris** [Atlantiss/BugTracker#2415]
http://cata.openwow.com/spell=16870
Pomimo posiadania buffu castowane skille pobierają mane i buff schodzi dopiero po minięciu czasu trwania a nie po skillu

**Comment by Jenovas** [comment]
Sprawdzone. Działa poprawnie.
Proszę napisać na jaki spell  nie działa.

**Comment by Kimbris** [comment]
Na mojej postaci nie działa na żaden skill leczący np Nourish

**Comment by Jenovas** [comment]
Na nourish nie powinien działać. Powinien działać tylko na regrowth i healing touch.

**Comment by Kimbris** [comment]
Spróbuje wyczyścić cashe i powylaczac addony bo u mnie na regrowth i healing touch też nie działa:o
