### ISSUE TITLE
[EN][Quest][Westfall]Secrets of the Tower

### ISSUE THREAD

**Issue by RufusPL** [Atlantiss/BugTracker#2420]
I can't complete this quest cause Agent Kearnen who should shoot the guys around the tower just isn't shooting. Everytime i'm attacking this guys i'm just dying cause she isn't shooting. When i tried to just go through them there is nothing in the tower (i tried to use a potion at the bottom of tower and on top multiple times). I think it's caused by unbound cyclones who mooved the agent to the wrong location and she just can't shoot from there. I saw the cyclones mooving mercenaries all over the location.
![wowscrnshot_022715_111835](https://cloud.githubusercontent.com/assets/11227680/6410962/00471396-be74-11e4-959f-a1f702cd6b6a.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2338
