### ISSUE TITLE
[EN][Item][Quest][Legendary] Essence of the Firelord % drop

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#2421]
Essence of the Firelord: http://www.wowhead.com/item=19017/essence-of-the-firelord
Ragnaros (MC): http://www.wowhead.com/npc=11502/ragnaros
Thunderaan the Windseeker quest: http://www.wowhead.com/quest=7786/thunderaan-the-windseeker

Item Essence of the Firelord should have 100% drop from Ragnaros in Molten Core while we have quest "Thunderaan the Windseeker" in our changelog (quest for Legendary weapon). 
Right now looks like it has "original" % drop like without having quest.
I killed Ragnaros so many times with quest active and it didn't drop yet.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Navedonar** [comment]
fixed http://atlantiss.eu/changelog#rev4353
