### ISSUE TITLE
[ENG][Core][Dungeon finder]Not finding other players

### ISSUE THREAD

**Issue by cookienator152** [Atlantiss/BugTracker#2423]
The dungeon finder in its current form does not find other people to form a group with. I thought for a second it might be a visual bug, but I've tested it with people from party joining queue separately, and getting no result (not showing them in roles screen might be that visual bug I suspected). In short, unless you have a 5 people in group and queue together, you won't get into rhc/rdf. It sometimes displays Call to Arms bonus available, so at least that works.

**Comment by Zollo11** [comment]
Confirmed

**Comment by dzonik** [comment]
for me worked today... we had other bug when we kick tank . we could not few minutes to  que again giving us some error but after 5 minswe could que

**Comment by Quban** [comment]
About a cooldown in LFG queue found in:
http://wow.gamepedia.com/Dungeon_Finder#Using_the_Dungeon_Finder

"Leaving a group
When you leave a group you got via the Dungeon Finder you will be on Dungeon Finder cooldown, preventing you from joining another random group for the next 30 Minutes (from the time you were matched with a dungeon). There are the following exceptions:

You got kicked from the group
The End Boss (or whoever gives the reward for joining a LFD-group) of the instance has been killed"

Only in those 2 cases we should get cooldown for rejoining LFG. Now we've got CD after we teleport to the instance, so we cant join LFG if some1 left pt.

**Comment by Athinira** [comment]
Yup had same issues. When i made group and joined was fine. But if i look solo for players im never getting pop up.

**Comment by dzonik** [comment]
Did it again late last night and all worked good

**Comment by Bildo** [comment]
Wolfenstein wrote:
Apparently MYSQL issue was affecting Dungeon FInder, as it seems to be working now...

**Comment by sabi102** [comment]
Still not working

**Comment by Athinira** [comment]
everything works fine for me.
