### ISSUE TITLE
[PL][Mount Hyjal][Error]

### ISSUE THREAD

**Issue by zbix6652** [Atlantiss/BugTracker#2424]
==============================================================================
World of WarCraft: Retail Build (build 15595)

Exe:      D:\AT cata\WoW.exe
Time:     Feb 27, 2015  7:22:41.380 PM
User:     Komp
Computer: KOMP-KOMPUTER
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal condition!

Program:	D:\AT cata\WoW.exe
ProcessID:	4256

Failed to read file from local.

**Comment by Wolffenstein** [comment]
Nic nam to nie mówi.
