### ISSUE TITLE
[PL][Quest][Shadowmoon Valley] The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Deonorth** [Atlantiss/BugTracker#2426]
Nie można porozmawiać z Sar'thisem, który powinien sumnąć takiego elementala z którego dropi potrzebny do questa Flawless Arcane essence
http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron

**Comment by Veruca1320** [comment]
potwierdzam !

**Comment by Deonorth** [comment]
nadal nie działa :)

**Comment by XrayAlert05** [comment]
bump

**Comment by XrayAlert05** [comment]
bump
Czy ktoś to w kocu naprawi ?? Nie mona zdobyć mounta.

**Comment by Wolffenstein** [comment]
Ten quest nie jest wymagany do mounta...

**Comment by dinosaldo** [comment]
Nadal nie działa .

**Comment by Aival94** [comment]
Quest is still not working as when you speak with [Sar'this](http://www.wowhead.com/npc=23093/sarthis) does not have any option to start the event which will summon the elementals.

**Comment by suchyt** [comment]
bump
;(

**Comment by RastaTinu** [comment]
Dalej nie działa

**Comment by tomatosz** [comment]
Bump, can't even interact with Sar'this

**Comment by maddy169** [comment]
I can interact with Sar'this and there's the option to begin, but when you click it, nothing happens u.u

**Comment by TranceAccount** [comment]
Closing this report since #10157 uses the newly implemented template and is in English.
