### ISSUE TITLE
[EN][Professions][Mining Nods][Northern Stranglethorn]Nods are spawning on trees

### ISSUE THREAD

**Issue by Alinous0** [Atlantiss/BugTracker#2427]
Well half nods are spawning like this 
![wowscrnshot_022815_120650](https://cloud.githubusercontent.com/assets/5849521/6425986/b4ee3cb0-bf42-11e4-8684-fbdf8f02b303.jpg) Should i give you as much coords as i can?

**Comment by xmesaj2** [comment]
It's more of general issue, I spotted the same in Winterspring.
