### ISSUE TITLE
[EN][Item]Formula: Enchant Weapon - Crusader

### ISSUE THREAD

**Issue by marrog91** [Atlantiss/BugTracker#2428]
This formula didn't drop once after slaying A LOT of these mobs (http://www.wowhead.com/npc=9451/scarlet-archmage). I suppose that this may be the server patch issue, because:

"For future reference, this item was removed from the game with the Shattering (4.0.3a), when the mobs that dropped it were converted from humans to undead. In 4.1.0, this oversight was resolved."
From:http://www.wowhead.com/item=16252/formula-enchant-weapon-crusader#comments

Of course I asked couple of times but don't get answer. I guess that no one know about it, so I can't confirm the bug.

**Comment by Arcadia713** [comment]
You know it has 1.2% drop chance? It's super low. I was farming that even on 4.0.6a and they didn't drop (i slain about 1000 of those). But people have this recipe for sure (since i got this enchant on my heirloom sword) so it drops somehow...

**Comment by marrog91** [comment]
Yes, I know. I've played on many servers and farmed plenty of extremely rare pets (recipes too) with 0.2% drop rate's (sometimes more, sometimes even less .0's percents) with multiple successes of course and this over 1% chance to drop don't really look like it should. I know what it mean cuz i'm farming items with low drop rate's for years. Unfortunately I can't look in the database to convince myself, but I guess the droprate is much lower than 1% like you said after killing 1k of those mobs, recipe would drop more than 1 time and I thought that noone have it, hence my suspicion and this issue on BT.

Or perhaps I'm really, really unlucky this time...

**Comment by Wolffenstein** [comment]
The drop rate is 0.2% :P

**Comment by marrog91** [comment]
Well, as I thought. I wanted to farm this recipe (for me 1% to drop is high) but after days of not dropping I stop killing mobs believing that something is wrong... and looked on the Wowhead  - our server was on "starting" patches too.
Anyway, the percent of drop the awesome for alts Crusader formula is significantly lowered and this is bug to be fixed. :)

**Comment by Bildo** [comment]
rev. 4353 by Navedonar

**Comment by bgb** [comment]
Is this fixed?

**Comment by Navedonar** [comment]
yes 1,2 % drop rate
