### ISSUE TITLE
[PL][Warlock][Item][PvP][Core][High Priority][game breaking]  Healthstone

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#2429]
http://www.wowhead.com/item=5512/healthstone

Nie da się użyć Healthstone'a podczas disarmu rogala. 
Nie testowałem na disarmie warriora, ale pewnie to samo

http://www.wowwiki.com/Dismantle disarm

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
