### ISSUE TITLE
[EN][Item] Dragon's Call

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#243]
Sword is supposed to proc a drake summon for a short period of time. It doesn't.
http://www.wowhead.com/item=10847
http://www.wowhead.com/spell=13049
http://www.wowhead.com/npc=8776

**Comment by illidan810** [comment]
I can confirm that the sword is still useless.

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14121-item-dragons-call/

Thanks for the report.

**Comment by phixor** [comment]
It's still bugged><

**Comment by TranceAccount** [comment]
Fix failed.

**Comment by TranceAccount** [comment]
I have a fix ready, which removes the mana cost of this spell.
Apparently you needed many if you wanted to proc the spell, which is not logical, since warriors can use the weapon too. Requires some more testing tho.

**Comment by TranceAccount** [comment]
#8171
