### ISSUE TITLE
[PL][Reputation] Zandalar Tribe

### ISSUE THREAD

**Issue by Alandiel** [Atlantiss/BugTracker#2430]
http://wow.gamepedia.com/Zandalar_Tribe_(faction)#Patch_changes
Patch 4.0.3a (2010-11-23): It is no longer possible to gain reputation with this faction.
Obecnie da radę zdobyć tę reputację zabijając http://www.wowhead.com/npc=11383/high-priestess-haiwatna, http://www.wowhead.com/npc=11346/hakkari-oracle i http://www.wowhead.com/npc=11355/gurubashi-warrior przed Zul'Gurub.
Bardzo możliwe, że http://www.wowhead.com/npc=11346/hakkari-oracle i http://www.wowhead.com/npc=11355/gurubashi-warrior nie powinno być już w grze tylko nie mogłem nigdzie znaleźć info kiedy zostały usunięte.

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
