### ISSUE TITLE
[EN][raid-cata]Al'Akir

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#2431]
We just did tot4w and when we wanted to go al'akir, everytime we start the fight, on the first phase when the boss does the spell 'Wind Burst' it is crashing the whole raid at the end if his cast. Idk if others are having the same problem but atleast we had it 3 times in a row, i don't think that is normal :s

**Comment by Dziara** [comment]
It may be connected with #1453 and Kejmil's comment.

**Comment by Frainzil** [comment]
Maybe yes, but i don't understand a word of that language/comment so this is the english version :D

**Comment by iskk** [comment]
"this is global bug. change position + knockback, death grip + thunder storm = error. i guess warrior's charge would crash too if something pushed him back during run"
