### ISSUE TITLE
[PL][NPC][Icecrown] Matthias Lehner

### ISSUE THREAD

**Issue by Alandiel** [Atlantiss/BugTracker#2433]
Brak NPC http://www.wowhead.com/npc=32408/matthias-lehner zaczynającego quest http://www.wowhead.com/quest=13394/do-your-worst, blokuje to spory chain w Icecrown.

**Comment by Avalain** [comment]
Potwierdzam, po wykonaniu zadania http://www.wowhead.com/quest=13393/field-repairs powinien pokazać się nam http://www.wowhead.com/npc=32408/matthias-lehner oferujący zadanie http://www.wowhead.com/quest=13394/do-your-worst

**Comment by Bildo** [comment]
fixed
