### ISSUE TITLE
[EN] [QUEST] [Hellfire Peninsula] Birds of a Feather

### ISSUE THREAD

**Issue by Tikalis** [Atlantiss/BugTracker#2434]
According to http://www.wowhead.com/quest=9397/birds-of-a-feather this quest should be completable by capturing a Female Kaliri Hatchling http://www.wowhead.com/npc=17034/female-kaliri-hatchling

However when near or directly targetting Female Kaliri Hatchling, error message will pop up while trying to use the item ("You can't do that yet"). I tried to lowering it's health but same message pops up everytime.

Clicking the nests located in Den of Haal'esh should also randomly spawn either male or female kaliri hatchling, but they do not work either.

Not completable in current stage.

**Comment by Quban** [comment]
fix soon

**Comment by bgb** [comment]
Still bugged...
