### ISSUE TITLE
[EN][Quest][Dragonblight] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2437]
This quest had a workaround but is not completable anymore.
http://www.wowhead.com/quest=12237
There is a previous post for the quest from the bug tracker.
Link to quest info and wowhead links: 
[ https://github.com/Atlantiss/BugTracker/issues/523 ] (https://github.com/Atlantiss/BugTracker/issues/523)

**Comment by Technowizard15** [comment]
A tip: You don't have to copy&past the github link, just write down it's number like #523 and it will link the corresponding bug report, it even opens a little convenient window with possible candidates and their headlines.

**Comment by Thefakemccoy** [comment]
Just finished the quest not sure what is broke. Up untill the last update it worked just fine. Summon gryphon collect 10 lost town folks. 

Now when you dismount from the gryphon they wont disappear.

http://www.wowhead.com/npc=27258/wintergarde-gryphon
![wowscrnshot_061915_082601](https://cloud.githubusercontent.com/assets/12252441/8253345/d33bfe66-165c-11e5-949b-86d3a9d497a7.jpg)

**Comment by nenormalen** [comment]
Quest is working like a charm!

**Comment by Sylvictus** [comment]
I am attempting to do this quest now and it refuses to work. All it says while I am on the grphon is "You can not use that ability yet", when I am next to a villager trying to use the ability to rescue them.

**Comment by roxkyp** [comment]
I get the same error as Sylvictus does!

**Comment by miriada** [comment]
Still doesnt work, an i stuck in Dragonblight at 84/115 questes :(.

**Comment by Thefakemccoy** [comment]
Back in June of 2015 I managed to complete the quest now i cant get you cant do that yet.

**Comment by Bildo** [comment]
fixed

**Comment by TheCopacabanaMan** [comment]
Gospodin... why i can summon the gryphon, but cant mount?

**Comment by Lycanar** [comment]
It's not fixed..
