### ISSUE TITLE
[PL][Quest][Tanaris]Find OOX-17/TN!

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#2438]
http://www.wowhead.com/quest=351/find-oox-17-tn

NPC nie ma w miejscu gdzie powinien być, co uniemożliwia ukończenie questa.

**Comment by Bildo** [comment]
jest, zapewne ktos go wczesniej zrobil i nie zdazyl sie zrespic

**Comment by Haz3L** [comment]
W połowie drogi zaczyna skakać w powietrzu aż w końcu znika.

**Comment by Porobiony** [comment]
Pół godziny siedzenia i kurczak się nie zrespił. Quest nadal niewykonalny
