### ISSUE TITLE
[EN][NPC][Icecrown] - Carrion Hunter

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#2442]
The undead-like looking birds in Icecrown called Carrion Hunter,
link - http://www.wowhead.com/npc=31263/carrion-hunter#comments, 
are suposed to be tameable as of 4.0.6. Atm they are marked as Undead and ofc not tameable.
You can actually see its tameable in the Quck facts.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Navedonar** [comment]
fixed http://atlantiss.eu/changelog#rev4353
