### ISSUE TITLE
[EN][NPC][Eastern Plaguelands] - The Lone Hunter - Wrong model

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#2443]
NPC (wolf) The Lone Hunter has a wrong model. It has to have a sword stuck in its head.
Link - http://www.wowhead.com/npc=45450/the-lone-hunter
Atm its just a normal ghostly wolf.

**Comment by Navedonar** [comment]
http://www.wowhead.com/spell=84910/josephs-hunting-blade

**Comment by meowmewo** [comment]
I mean that the wolf on its own should have the sword in his head. Yes he drops it but its not in his head.Hes not looking like the one in the link i showed you :)

**Comment by Quban** [comment]
fix soon

**Comment by cosminush** [comment]
there isn't any NPC, with wrong model or not. Quest can't be completed.
