### ISSUE TITLE
[EN][Quest][Westfall]A Vision of the Past

### ISSUE THREAD

**Issue by 17chungsamuel** [Atlantiss/BugTracker#2444]
There is an error in this quest. I tried doing the vision but had an error. So when I abandoned the quest to get it again, the quest giver has a blue question mark to finish the quest but the complete quest button wont work. Therefore, i cant get or complete the quest.
(note: in the picture I don't have the quest)
![wowscrnshot_030115_094248](https://cloud.githubusercontent.com/assets/11258992/6432014/666d492c-bff7-11e4-979a-c69cc4eec382.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1622

**Comment by Tegis** [comment]
completed the quest.  after going into the deadmines, clicked item from inventory.  once in the quest said to report back to sentinel hill.  I left vehicle and hearthed back to sentinel hill where a grey question allowed me to complete the quest.

**Comment by sigmundfreud2016** [comment]
I've relogged after using the quest item. Here are the results lol. 
![wowscrnshot_080715_125203](https://cloud.githubusercontent.com/assets/12395407/9134430/5911d272-3d04-11e5-9320-c46499457ed7.jpg)
![wowscrnshot_080715_125419](https://cloud.githubusercontent.com/assets/12395407/9134433/59181484-3d04-11e5-94b3-e7de7b03e426.jpg)
Then I used my hearthstone and became a ghost of Stormwind.
![wowscrnshot_080715_125453](https://cloud.githubusercontent.com/assets/12395407/9134432/5914d95e-3d04-11e5-9b22-9d0bf4451c38.jpg)
![wowscrnshot_080715_125503](https://cloud.githubusercontent.com/assets/12395407/9134431/5914b42e-3d04-11e5-955d-65a0a7b5e2d6.jpg)
Everything went back to normal few minutes later. Pretty funny anyway.
