### ISSUE TITLE
[PL][Druid][Item]BONUS 4T RESTO

### ISSUE THREAD

**Issue by Hennessee** [Atlantiss/BugTracker#2445]
Bonus odpala się w sposób w jaki powinien się odpalać na patchu 4.0.x, tzn z 3 stacków Lifeblooma, natomiast teraz on powinien działać w momencie gdy mamy buffa Harmony(odpalanego miedzy innymi z Regrowtha).

**Comment by Jenovas** [comment]
Fixed in rev 4374
