### ISSUE TITLE
[EN] [Quest] [Mount Hyjal] Black heart of flame

### ISSUE THREAD

**Issue by xandis1** [Atlantiss/BugTracker#2446]
In the quest http://www.wowhead.com/quest=25428/black-heart-of-flame the quest item http://www.wowhead.com/item=53464/charred-branch cannot be used at the "inferno zone". Wow complains about "you are in the wrong zone".

Issue #577 no longer appears to be relevant.

**Comment by xandis1** [comment]
nevermind, issue #577 still applies.

**Comment by artamedan** [comment]
The item to summon is still bugged but the quest is completable because the NPC respawns by himself. Not in the centre of Inferno but near coords 13.1 / 36.6
