### ISSUE TITLE
[PL][Instance-Cata] Zul'Gurub ID

### ISSUE THREAD

**Issue by Alandiel** [Atlantiss/BugTracker#2448]
ID na Zul'Gurub resetuje się co środę, tak jak raidy. Powinno po 1 dniu jak każdy inny dungeon.

**Comment by Hennessee** [comment]
System ID na ten moment to jest jakas kpina. Jednym nie resetuje wogole ID, drugim resetuje ID w trakcie tygodnia nawet z raidów.

**Comment by Alandiel** [comment]
Spośród heroiców cata spotkałem się z tym bugiem tylko w przypadku Zul'Gurub i w sumie dzieje się tak za każdym razem gdy zrobię tę instę.

**Comment by Malylolek** [comment]
Alandiel bo raidy sa od 2 tygodni resetowene manualnie co środe koło godziny 19 dlatege.

**Comment by Alandiel** [comment]
Ja napisałem o dungeonach, a nie o raidach to jednak jest co innego.
