### ISSUE TITLE
[PL][INSTANCE][NPC] Naxxramas Kel'Thuzad

### ISSUE THREAD

**Issue by Holywhisper** [Atlantiss/BugTracker#2450]
http://www.wowhead.com/npc=15990/kelthuzad
Problem polega na tym, ze po zbiciu addow i dosc bardzo dlugim czekaniu boss nie zaatakowal. Uniemozliwia to zdobycie achieva i tytulu. Stan na 01.03.15

**Comment by jurek1** [comment]
potwierdzam tez mialem taki problem z tydzien temu ( wersja 25 )

**Comment by Tessa99999** [comment]
Also Confirmed. Had his problem on 3/12/15

**Comment by sshad00w** [comment]
Confirmed 15/03/2015

**Comment by spell406** [comment]
Ponadto wersje 10 i 25 Naxxramas powinny miec oddzielne ID na 10 i 25 man a tak nie jest.

**Comment by Jenovas** [comment]
http://us.battle.net/wow/en/forum/topic/4427707351
Powinny mieć WSPÓLNE ID.

**Comment by Hextall** [comment]
7/11/2015 - (wersja 25) Nic się nie dzieje po zabiciu addów i odczekaniu sporej ilości czasu. Tydzień przed tą próbą odpalił się. Nie mam pojęcia od czego to zależy.

**Comment by Bastion** [comment]
myślę że to zależy od lagów! 
https://www.youtube.com/watch?v=fdKoPvKSfLQ

**Comment by HUMBOL** [comment]
Nie wiem dlaczego to jest zamknięte, skoro addy dalej włażą pod tekstury, a po zabiciu wszystkich, które jakimś cudem da się zobaczyć i tak boss się nie odpala.

**Comment by Aviannaqt** [comment]
Pewnie dlatego, ze przez jakis czas działało, i na nowo sie zwaliło.

**Comment by secu312** [comment]
Ruszylo sie cos w sprawie Kela?

**Comment by Piklo** [comment]
@secu312 z aktualną ilością devów, nie sądzę żeby ktokolwiek robił cokolwiek "cięższego" związanego z starym contentem + ostatnio ruszyły prace nad contentem 4.3, a to raczej ma wyższy priorytet

**Comment by secu312** [comment]
@Piklo ja wszystko rozumiem, ale jednak moje serce krwawi gdy przez jednego bossa 200 achiev pts zalega do zrobienia :D to tak boli :>

**Comment by amonkira88** [comment]
Własnie próbowałam zabić Kela. Nie wiem jak Kel ale addy włażą pod podłogę, zwłaszcza Soul Weaver nie chcą wyjść. Ponad 10 minut skaczę by jakoś je zabić. Podbijam prośbę o naprawę.

**Comment by Aviannaqt** [comment]
@@@xd

**Comment by Elannreportujerzeczy** [comment]
Would be nice if you fixed it after 3 years.

**Comment by roesiran** [comment]
Please fix him or make him just killable, he's blocking, if i remember correctly 11 achievements. Thanks in advance.

**Comment by TranceAccount** [comment]
@pelekon did this get fixed?
