### ISSUE TITLE
[EN] [Quest] [Storm Peaks] Discipline

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2453]
The quest involves using a [ Disciplining Rod ] (http://www.wowhead.com/item=42837/disciplining-rod) on [ Exhausted Vrykul ] (http://www.wowhead.com/npc=30146/exhausted-vrykul) which is obtained when you begin the quest.

Using the rod on the npc accomplishes nothing, making the objective incomplete and quest not-doable.

Wowhead:
[ http://www.wowhead.com/quest=12906/discipline ] (http://www.wowhead.com/quest=12906/discipline)

Actual quest Video:
[ https://www.youtube.com/watch?v=dUBTN-0j_co ] (https://www.youtube.com/watch?v=dUBTN-0j_co)

**Current Buggy Workaround:**
_Find a sitting Vrykul > Hit it whith the Rod >> Get aggro and take damage >> Hit it Second time with the rod >> Gets the objective count!_  
Works on any sitting Vrykul multiple times after the first hit. Just watch your HP  and you should be :+1:

**Comment by Quban** [comment]
Done this q now, its bugged but in other way, you can get all kill credits on just 1 mob.

**Comment by Dexobox** [comment]
Post a photo / location coordinates of this mob as workaround here @Quban

**Comment by Quban** [comment]
Well, any Exhausted Vrykul actually gave me kill credit, do you play on horde or alliance side?

**Comment by Dexobox** [comment]
Alliance Worgen Mage

**Comment by Quban** [comment]
http://imgur.com/WZ1Kj4Z,7dlH3Kz,ca54iOO,EvfbynU,LA9cgTl,VcCgyia,x9ZAXKg
As you can see i did it again today and it works. Dont know maybe you were in a raid grp or sth. Or you didnt get this ice lady form

**Comment by Dexobox** [comment]
I can confirm i was with the **"Brunnhildar Disguise"(Ice Lady)** buff and model, also not in any groups. But i shall try it once more and post coordinates of this Exhausted Vrykul if it works for anyone else facing trouble doing this. I really appreciate your effort on posting the image @Quban . Thank you for your help.

**Comment by Dexobox** [comment]
**Alright i finally figured out a workaround!** The [ Exhausted Vrykul ] (http://www.wowhead.com/npc=30146/exhausted-vrykul) that is resting(sitting down) when i hit it with [ Disciplining Rod ] (http://www.wowhead.com/item=42837/disciplining-rod) he aggros and hes starts attacking back but u do not get the objective completion on the 1st hit. (I used to kill the [ Exhausted Vrykul ] (http://www.wowhead.com/npc=30146/exhausted-vrykul) after i got his aggro).

Instead hitting the npc a second time using the [ Disciplining Rod ] (http://www.wowhead.com/item=42837/disciplining-rod) got the quest to work.

Aggro'ed Vrykul
![wowscrnshot_030315_210044](https://cloud.githubusercontent.com/assets/5689143/6478160/363f17a4-c1ea-11e4-9b34-f62758aea7a6.jpg)

Sitting Vrykul
![wowscrnshot_030315_210655](https://cloud.githubusercontent.com/assets/5689143/6478163/3f7945a6-c1ea-11e4-88d1-89189914cf2f.jpg)

**Comment by Bildo** [comment]
rev. 4353 by Quban
