### ISSUE TITLE
[EN] [Quest] [The Storm peaks] Baby Stealers

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2454]
The quest involves rescuing Eagle's Eggs from Harpies.

The [ Eagle Egg ] (http://www.wowhead.com/object=191773/eagle-egg) item which drops [ Stormcrest Eagle Egg ] (http://www.wowhead.com/item=41341/stormcrest-eagle-egg) are missing from the zone near the Harpies in Storm Peaks. There are some eggs in other regions but are not loot-able or click-able.

Wowhead:
[http://www.wowhead.com/quest=12867/baby-stealers ] (http://www.wowhead.com/quest=12867/baby-stealers)

Youtube Video:
[ https://www.youtube.com/watch?v=2E4I9j-KpUk ] (https://www.youtube.com/watch?v=2E4I9j-KpUk)

**Comment by Quban** [comment]
They are not missing, they are just not clickable ;P

**Comment by Dexobox** [comment]
Umm Yes They are missing from the location i can give you location screen shots where they are missing. I suggest you look at the video. Anyway the quest is bugged and incomplete.

**Comment by Bildo** [comment]
rev. 4353 by Quban
