### ISSUE TITLE
[EN][Quest][Ashenvale] Rain of Destruction

### ISSUE THREAD

**Issue by Fellron** [Atlantiss/BugTracker#2455]
In order to complete the quest, you're required to kill 30 Attacking Elves and 5 Raging Ancients infront of the camp, but as you accept the quest and it turns you into the imp which you have to mark the targets with, every NPC disappears and there are no targets to attack or pretty much anything and you can't remove the "buff" to become your character again, even if you abandon the quest or relog.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1896
