### ISSUE TITLE
[EN] [Talent] [Druid] Pulverize

### ISSUE THREAD

**Issue by voklee** [Atlantiss/BugTracker#2456]
Using Lancerate to build op stacks on the target goes well. But when i use Pulverize (bear talent) its does not give the damage it should. The extra 1688 dmg for each stack of Lancerate is not given.

Description of spell: https://cata-twinhead.twinstar.cz/?spell=80313  (cataclysm version)

**Comment by Varchord** [comment]
First part is true. Additional damage per laceration stack is too low.
As for crit buff, it's false. I get crit buff every time, it's working

And how the hell low pulverize damage makes it hard to hold aggro? Feral druid is the most faceroll tank in terms of threat output

**Comment by voklee** [comment]
You are true. I can see the buff appear now. I have updated the post. 
Not getting the 1688 dmg for each stack remains as the bug.

**Comment by Jenovas** [comment]
I did some changes to pulverize like a month ago because it dealt only 1 dmg. I'll check the Formula again.

**Comment by Varchord** [comment]
If i remember correctly it was 0.6*wpn_dmg+1688*stack

**Comment by Jenovas** [comment]
DMG should be higher in rev 4356
