### ISSUE TITLE
[PL][Raid-tbc]The Eye-Kael'thas Sunstrider

### ISSUE THREAD

**Issue by Braned** [Atlantiss/BugTracker#2457]
Kael'thas Sunstrider (http://www.wowhead.com/npc=19622/kaelthas-sunstrider) ma zbugowany phase5.
Po sprowadzeniu Kae'la do 50%hp przechodzi on do phase5 gdzie powinien uciec do "swojego pokoju"  (tempest bridge) i tam powinno się sprowadzić go do samego końca hp. Bug polega na tym, że Kael nie ucieka do tempest bridge a zostaje w miejscu gdzie był tankowany pod koniec phase4, dodatkowo po przejściu do phase5 nie da się go zaatakować większością ataków (nie działają ataki melee, jeśli chodzi o ataki ranged instanty działają a ataki castowane w większości nie) ostatnią częścią bugu jest to, że Kael może losowo sam zresetować walkę.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1718
