### ISSUE TITLE
[EN][Core] shred, backstab, ambush, stealth ravage

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#2458]
they're parryable and dodgeable and they shouldn't be.

**Comment by Varchord** [comment]
Proof, wowhead links

**Comment by Jenovas** [comment]
"Standing behind a melee target negates that enemies chance to parry and block your attacks. In PVP, it negates their chance to dodge as well, but NPC creatures can dodge attacks from behind."

**Comment by Varchord** [comment]
So as far as i know it's working as intended. But OP didn't specify if he meant pve/pvp or whatever

**Comment by Isuel** [comment]
yeah, sorry, i meant for pvp (though nothing is parry-able from the back anyway). i guess it happens if the target turns around too fast, i don't know. could be a global issue if that's the case.

**Comment by kadi2** [comment]
Are you sure that you can dodge/parry ambush/Ravage? I thought it's already fixed for all the openers (haven't got a single dodge/parry for cheap shot on the atlantiss)

**Comment by Isuel** [comment]
i don't know about ambush, i'm just guessing about it since it has the same mechanic as shred and backstab (i know it did in wotlk).

**Comment by Isuel** [comment]
bump, it's retarded to have to move the whole game in order to get a shred, and then to have it dodged in pvp.

**Comment by Jenovas** [comment]
Fixed in rev 4542
