### ISSUE TITLE
[EN]Heroic Training Dummy's and Training Dummy's

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#2459]
Deathknights have been pulling these Training dummy's all over the place the need to be immune to Deathgrip please fix this problem as soon as you can im tired of trying to have to find a Training dummy becuase of trolls moving them around and the next time i will get Screen shots on them doing this aswell i already seen one doing it but he left before i could get a screen shot.

**Comment by Bildo** [comment]
rev. 4353 by Quban
