### ISSUE TITLE
[EN][Quest][Stormwind docks][Twilight Shores]

### ISSUE THREAD

**Issue by terranu1** [Atlantiss/BugTracker#2461]
Fargo Flintlocke shows the yellow mark to get his quest for flying to Twilight Highlands but it's not working, I click on the NPC and it wont open quest window.

**Comment by PVPViddys** [comment]
I see this issue is closed but I'm experiencing the same problem.

**Comment by Allowas** [comment]
It is closed because 4.3.4 is not released yet.

**Comment by mati865** [comment]
Still an issue.

**Comment by foxclubniner** [comment]
Still an issue
