### ISSUE TITLE
[ENG] Orgrimar [QUEST] Unfamiliar Waters

### ISSUE THREAD

**Issue by flohpicco** [Atlantiss/BugTracker#2465]
When players find Herezegor and talk to him, a small group of Twilight Nightblades will attack before he can draw his map. It seems players must defeat these mobs on their own, without any assistance, excepting group members, this origanialy happend when u talk to Herezegor but when i talk to Herezegor he says greetings and i click on good bye
pls fix the prequests to twilighthighlands

**Comment by Quban** [comment]
http://www.wowhead.com/npc=42638/herezegor-flametusk
http://www.wowhead.com/npc=42707/twilight-nightblade
http://www.wowhead.com/quest=26311/unfamiliar-waters
Remember, next time find links too or it will be closed.

**Comment by flohpicco** [comment]
haha thanks but im not stupid.
its because twilighthighlands is closed, thats why it dont work!!!!
