### ISSUE TITLE
[PL][Spell][Priest]Circle of Healing

### ISSUE THREAD

**Issue by Lightfury** [Atlantiss/BugTracker#2468]
CoH base CD: 8 sec.

Po uruchomieniu Chakra:Sanctuary, cooldown Circle of Healing powinien być zredukowany do 6 sekund, jednakże nadal pozostaje ten bazowy - 8 sekundowy.

Ciężko znaleźć coś aktualnego, jedynie co nieco w komentarzach z patchu 5.0.5.
http://www.wowhead.com/spell=81206/chakra-sanctuary#comments
- " Chakra: Sanctuary transforms Holy Words to  Holy Word: Sanctuary, reduce  Circle of Healing's CD by 2 sec"

**Comment by Jenovas** [comment]
Bazowy CD CoH to 10 sekund a z Sanctuary ma 8 sekund. Zamykam.
