### ISSUE TITLE
[ENG][Quest][The Storm Peaks] Ample Inspiration

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2469]
http://www.wowhead.com/quest=12828/ample-inspiration

"Mammoth Carcass" (http://www.wowhead.com/object=192693/mammoth-carcass) should give you 3-4 "Hearty Mammoth Meat" (http://www.wowhead.com/item=40728/hearty-mammoth-meat) not 1.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
