### ISSUE TITLE
[ENG][Item] Hyldnir Spoils

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2470]
Opening the "Hyldnir Spoils" (http://www.wowhead.com/item=44751/hyldnir-spoils#contains) I get the message "The slot is empty." and no loot. The loot table seems to be empty.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4353
