### ISSUE TITLE
[ENG][Quest][The Storm Peaks] Into the Pit

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2474]
http://www.wowhead.com/quest=12997/into-the-pit

The "Hyldsmeet Warbears" (http://www.wowhead.com/npc=30174/hyldsmeet-warbear) don't move nor attack.

**Comment by Dexobox** [comment]
Actually this Quest is completable ! I am pretty sure you did not use the provided quest item [Reins of the Warbear Matriarch] (http://www.wowhead.com/item=42499/reins-of-the-warbear-matriarch) provided at the start of the quest.

Here a re a few screen-shots for me completing the quest as i write this:

![wowscrnshot_030415_003937](https://cloud.githubusercontent.com/assets/5689143/6479704/f87e5d4a-c206-11e4-9d4c-e0ddca65b6b8.jpg)

**Comment by Technowizard15** [comment]
I never claimed that the quest isn't doable, heh one even might do it while fallen asleep with his face on the keyboard, because you know ... THEY DON'T ATTACK ... like I already said. And how you came to the conclusion that I didn't use the warbear to do the quest when I filled a second bug report #2473 where a bemoaned the fact that it moves too slow I don't get. Ah and to your notice I also did use the warbear to do the quest "The Warm-Up" #2472, which has the same problems.

The problem with Bite I might explain ... it shouldn't have the ability, like I think you mentioned if I correctly got the message of your 2. paragraph. Since the youtube link isn't correct: https://www.youtube.com/watch?v=bLyEsHZ-fSs

**Comment by Dexobox** [comment]
Well the description above was very lazy and appalling for a bug report. Good I promoted you to write more :smile:  Report Descriptions must be accurate so the Bug Fixer is assisted easily.

**Comment by Technowizard15** [comment]
Cool, you help me to write more in me bug report and I will help you write readable sentences, deal?

And as a token of good will I will start with your last sentence:
"He does not need to search for what exactly to search for." -> The dev should not have to look up the infos he needs to fix the bug.

**Comment by Dexobox** [comment]
Its all about improvement u see . Good I will take you up on that deal. English isn't my first language,

**Comment by Technowizard15** [comment]
Neither is it mine, so I can feel your pain. Actually it's my second foreign language, my first one is Latin, can you believe it? Didn't know which devil rode me on the day I chose it.

**Comment by Dexobox** [comment]
Well i am sure you will be better at it than i am Latin would def. be a nightmare i assume. grammar esp.

**Comment by Quban** [comment]
fix soon

**Comment by VioletFlare** [comment]
The issue still exists, [I have tested it today](https://4.sendvid.com/ecry6hdb.mp4), summing it up:
· The bears aren't attacking (only the first one attacked back)
· They aren't using their skills
· They aren't fighting each other
· The Hyldnir are not sitting on the bears
[YT retail video](https://www.youtube.com/watch?v=CJ28xVAeh6M), [Wowhead](http://www.wowhead.com/quest=12997/into-the-pit)
