### ISSUE TITLE
Gundrak

### ISSUE THREAD

**Issue by mouredkingdoom** [Atlantiss/BugTracker#2475]
While trying to do achievement "share the love" on last boss all party members suddenly receive wow error, we tried it for five times always with the same result, we even used GM advice to do fix1 but that changed nothing, best regards - Nefalem

**Comment by mitim1** [comment]
1.https://github.com/Atlantiss/BugTracker/blob/master/README.md
2.I did this achievement on rev 4350 and we didn't get any wow error.

**Comment by mouredkingdoom** [comment]
1. It's my first bug that i was supposed to submit - GM told me to, sorry if i did something wrong.
2. We can not, while doing 4/5 party members get wow error, so it's not my computer that failed, (4/5 always one person didn't and it was random) got 3 persons impaled and that's it. I'm not sure what "rev 4350" mean, if you could explain it to me it would be awesome.
3. Thanks for quick response.
