### ISSUE TITLE
[PL][Quest][Deepholm][One With the Ground]

### ISSUE THREAD

**Issue by hirumka** [Atlantiss/BugTracker#2477]
http://www.wowhead.com/quest=27934/one-with-the-ground  brak możliwości oddania q .http://www.iv.pl/images/42937312060342133302.jpg po dotarciu do miejsca pokazuje się q lecz nie można nic z nim zrobić . Ten quest jest bardzo ważny blokuje dosyć sporo q lecz ważniejsze jest to ze blokuje zdobycie reputacji do The Earthen Ring oraz Therazane!!

**Comment by jurek1** [comment]
doszedles tam na pieszo ? jak tak to sie nie dziwie , powinines pogadac z tym co ci questa daje  i w  tedy bedzie event jak dojdziesz tam automatycznie ( niby pod ziemia ;p )
