### ISSUE TITLE
[PL][Quest][Mount Hyjal]The Bears Up There

### ISSUE THREAD

**Issue by wareczka** [Atlantiss/BugTracker#2484]
http://www.wowhead.com/quest=25462/the-bears-up-there
Nie działa w ogóle. Quest możemy wziąć i oddać. A szkoda, bo jest dość ciekawy, a do tego można zdobyć achiev http://www.wowhead.com/achievement=5483/bounce na trampolinie.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/578
