### ISSUE TITLE
[PL][NPC]Twilight Juggernaut

### ISSUE THREAD

**Issue by wareczka** [Atlantiss/BugTracker#2485]
http://www.wowhead.com/npc=41031/twilight-juggernaut
Moby mają całkowitą redukcję obrażeń przez zbroje, które noszą i przez ten czas, kiedy mają buffa (zdejmuje się go za pomocą questa) http://www.wowhead.com/spell=77224/armor-plating i http://www.wowhead.com/spell=77085/painful-stasis nie powinny być w ogóle możliwe do zabicia (a da się autoatakiem) oraz nie powinny w ogóle powodować combatu, dopóki właśnie powyższe buffy nie zostaną usunięte podczas tego questa http://www.wowhead.com/quest=25761/disassembly

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1490
