### ISSUE TITLE
[PL][Spell][Priest] Guardian Spirit

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#2486]
Spell Guardian Spirit (http://www.wowhead.com/spell=47788/guardian-spirit) dziwnie się zachowuje przy otrzymaniu dużych obrażen przez gracza na którym został aktywowany. Nie jest przyznawana wartość 50% maksymalnego zdrowia gdy gracz otrzyma śmiertelny cios od dużych obrażeń- dla przykładu: Spell "The Skullcracker" (http://www.wowhead.com/spell=75543/the-skullcracker#used-by-npc) używany przez Rom'ogg Bonecrusher'a jak i Spell "Blackout" (http://www.wowhead.com/spell=86788/blackout#used-by-npc) używany przez Vailone nie zabijają gracza lecz zostawiają gracza z 1 pkt. HP i nie dodają 50% jego maksymalnego HP. Umiarkowane obrażenia, które by zabiły gracza poświęcają buff Guardian Spirit i odnawiają 50% jego HP (czyli działa jak należy) czego brakuje w powyższych przykłdach.

Opis Guardian Spirit z tolltipa:
"Calls upon a guardian spirit to watch over the friendly target. The spirit increases the healing received by the targed by 60%, and also preventing the target from dying by sacrificing itself. This sacrifice terminates the effect but heals the target of 50% of maximum health. Lasts 10 sec."

**Comment by Jenovas** [comment]
Maybe the bug is that first the target gets healed and after that he gets the damage? It would be good if someone could check this in his combatlog

**Comment by Aviannaqt** [comment]
Nie Jenova, to juz jest po update sprzed +- 2 miechow tylko nie chcialo mi sie tego zgłaszać.
Po oberwaniu w wyżej wym. spellach zawsze zostaje 1 hp a nie 50% co lepsze, gdy tank padnie od Flaming Destruction na chogallu mając guardiana na sobie pada instantowo - sprawdzane z 3 razy.
Tak samo sindragossa - po dostaniu z kulki zostaje 1 hp.

**Comment by Vyrtuz** [comment]
jakieś nowe fakty w tej sprawie?

**Comment by armano2** [comment]
doubled: #3048
