### ISSUE TITLE
[EN][Quest][Eversong Woods] Unstable Mana Crystals 

### ISSUE THREAD

**Issue by Smiley13** [Atlantiss/BugTracker#2487]
http://www.wowhead.com/quest=8463/unstable-mana-crystals

This quest seems not to work.. Indeed, you are supposed to find the unstable mana crystals in those small crates  
![](http://wow.zamimg.com/uploads/screenshots/normal/15797.jpg) 
But, as you open them, it is impossible to collect those mana crystals since the loot window keeps opening and closing, so fast that you can't click on the object to take it..

**Comment by Bildo** [comment]
duplicate
