### ISSUE TITLE
[EN][Hunter] Feign Death

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2490]
Feign Death doesn't remove combat when casted and the effect gets cancelled when taking any damage (which is pretty much instantly in pvp)
http://www.wowhead.com/spell=5384/feign-death

**Comment by ShockRW** [comment]
Agree with FD and combat issue.

**Comment by Hanatsu** [comment]
I was write a bugreport on this too. Feign Death does not work at all.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/16
