### ISSUE TITLE
[EN] [Hunter] Camouflage

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2491]
Sending your pet to attack target breaks camouflage instantly on the hunter and the pet (while the pet is still running to the target and hasn't had the chance to attack yet), when it should break after pet or the hunter has dealt damage.
http://www.wowhead.com/spell=51753/camouflage

**Comment by Jenovas** [comment]
-Sending your pet to attack breaks camo immediately, even before your pet engages.
Closing issue.
