### ISSUE TITLE
Character stuck in Imp form

### ISSUE THREAD

**Issue by Bl00dSugar** [Atlantiss/BugTracker#2492]
Was doing a quest in Ashenvale "rain of destruction" but it was glitched so I abandoned it and now I'm stuck in Imp form with no NPC's around

**Comment by Dexobox** [comment]
Here is some additional info the Bug fixer might need.

1. Wowhead link: [Rain of Destruction] (http://www.wowhead.com/quest=13798/rain-of-destruction#comments)

2. The spell that must be executed on completion or abandon quest: [Cancel Imp Disguise](http://www.wowhead.com/spell=64118/cancel-imp-disguise)

3. Character name on which this has occurred (probably).

Also this falls into the category of quest bug so i wiould post the tile as **[EN] [Quest] [Ashenvale] Rain of Destruction (my character stuck in Imp form!)**

**Comment by Bl00dSugar** [comment]
I tried right clicking the imp disguise, didn't work. Tried logging didn't work.

What did work was, I walked out of the quest zone and the Imp disguise disappeared. Thanks! Resolved
