### ISSUE TITLE
[EN] [The Darkscale Warlord] [Darkshore]

### ISSUE THREAD

**Issue by Tokojiro** [Atlantiss/BugTracker#2496]
He is nowhere to be found

**Comment by Dexobox** [comment]
I think the correct way to post the title would be **[EN] [NPC] Warlord Wrathspine**, what do you say?
Don't need to mention the zone in the title but a wowhead link helps. This being asper instructions given in the [README](https://github.com/Atlantiss/BugTracker/blob/master/README.md) file on how to post bugs.

Also someone has already marked the quest as bug referenced here [#1099](https://github.com/Atlantiss/BugTracker/issues/1099)

I am unsure but i assume [Warlord Wrathspine] (http://www.wowhead.com/npc=34423/warlord-wrathspine) is the npc you say is missing and the name of the quest is [The Darkscale Warlord](http://www.wowhead.com/quest=13899/the-darkscale-warlord)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1099
