### ISSUE TITLE
[PL][Quest][Hillsbrad Foothills] A Blight Upon The Land

### ISSUE THREAD

**Issue by Enimens** [Atlantiss/BugTracker#2497]
http://www.wowhead.com/quest=28237/a-blight-upon-the-land
Niestety jak weźmiemy questa event się nie zaczyna co powoduje  że nie da się ukończyć questa a on blokuje reszte chaina.
https://www.youtube.com/watch?v=o5bgUcOQEJw Filmik z questa.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/397
