### ISSUE TITLE
[PL][Quest][EDIT!] Exodus - nie pojawił się NPC do oddania questa

### ISSUE THREAD

**Issue by Phestek** [Atlantiss/BugTracker#2501]
Co tu dużo mówić, wszystko jest na screenie. Nie ma NPC do oddania questa Exodus. 
http://www.wowhead.com/quest=24438/exodus
![no niezle](https://cloud.githubusercontent.com/assets/10514578/6507210/b0e4287a-c350-11e4-8307-fb2595ffa90f.png)

**Comment by TranceAccount** [comment]
The NPC is there.
Perhaps you should've waited for the respawn of him.

**Comment by Phestek** [comment]
Thanks for response... After 1.5 year, lol.
