### ISSUE TITLE
[PL][Quest][Deepholm] The Stone Throne

### ISSUE THREAD

**Issue by joozeck** [Atlantiss/BugTracker#2503]
Nie jest możliwe porozmawianie i oddanie questa u Therazane w Therazane's Throne. NPC "spada" z nieba po zbliżeniu się do miejsca, gdzie powinien stać. Brak możliwości ukończenia tego questa blokuje możliwość robienia daily questów dla Therazane.

https://www.youtube.com/watch?v=EAuk2WgZ3Uc
http://www.wowhead.com/quest=26709/the-stone-throne

**Comment by jurek1** [comment]
zobacz czy nie masz zaznaczone "at war" w reputacji

**Comment by joozeck** [comment]
Nie mam zaznaczone, sprawdzałem już, próbowałem ponownie go wziąć i oddać,
relog itp. i ciągle dupa.

2015-03-05 19:35 GMT+01:00 jurek1 <notifications@github.com>:

**Comment by joozeck** [comment]
Po długim pokombinowaniu stwierdzam że quest da się oddać, ale wyłącznie wtedy, gdy w Temple of Earth użyjemy portal do Therazane Throne i podejdziemy do Therazane. Oddanie powinno być możliwe również w przypadku, gdy polecimy mountem do tego NPC.
