### ISSUE TITLE
[En][Core][Battlegrounds][Vehicles][Important] Flying bug

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#2505]
I've entered game. I was in no-fly zone - Tol Barad, mounted on flying mount to get riding speed boost. Next thing, queued for Random Battleground and it was Isle of Conquest, in which I drive Glaive thrower, got near rocks at west horde gate, then battleground ended due to player amount being too low. Then I got back into Tol Barad and when I get in rocks near Baradin hold quartermaster then tried going towards portals, I was flying above the ground at the same height the said rock was.

Entering portal to Stormwind didn't fix the bug , stepping on the nearest barrel or object above ground level caused me to fly again. While in the air, you can use flying mount in locations where it's available and mount to get back on the ground, but you can also fly higher, dismount airborne and walk in the air.

While bug happens, you can't jump using Spacebar.
Alt+F4 and relogging removed the bug.

**Comment by xmesaj2** [comment]
Ok just got this for the second time just now, seems to confirm that exiting ended battleground while driving vehicle causes this bug. Also Strand of the Ancients ended the same, so not just Isle of Conquest is bugged.

**Comment by Wolffenstein** [comment]
Fixed in rev 4359.
