### ISSUE TITLE
[EN] [Spell] [Priest] Improved Devouring Plague

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#2508]
#2292 
Jenova, it is not true what you are saying. I don't want to dig through source code of simcraft(hate reading someone's code), but running simulation itself gives the answer(it is based on code right? :P)
Simcraft: http://i.imgur.com/VIQVb2N.png
World of Logs: 
http://www.worldoflogs.com/reports/rt-4nl2ko0oowurss1w/spell/63675/?s=7096&e=7551
http://www.worldoflogs.com/reports/9p67y2x297l7mc29/spell/63675/?s=8296&e=8774

BTW 1.5 crit multiplier would be nonsense. Shadow Power in Shadow tree specialization clearly states: "Increase the critical damage of your Shadow spells by 100%" and IDP is shadow spell indeed.

**Comment by Dziara** [comment]
And please don't make us(spriests) wait another 2 weeks to change one double number in code.

**Comment by Malylolek** [comment]
http://www.worldoflogs.com/reports/t790cwzzh72t5v9i/spell/2944/?s=5268&e=5453
http://www.worldoflogs.com/reports/t790cwzzh72t5v9i/spell/2944/?s=6328&e=6594

Same here from patch 4.3.4

**Comment by Dziara** [comment]
@Malylolek Sorry but you linked periodic damage from Devouring Plague ^^ Here is the IDP table linked with that priest:
http://www.worldoflogs.com/reports/t790cwzzh72t5v9i/spell/63675/?s=5268&e=5453
http://www.worldoflogs.com/reports/t790cwzzh72t5v9i/spell/63675/?s=6328&e=6594

**Comment by Jenovas** [comment]
I'll be looking into it again.
I thought it should be 1.5 because I found these two topics:
http://eu.battle.net/wow/en/forum/topic/927079493
http://us.battle.net/wow/en/forum/topic/1921987550

**Comment by Varchord** [comment]
Base crit dmg is always 1+(0.5). That's 0.5 more dmg per tick/whatever
Now specialization says "Increase the critical damage of your Shadow spells by 100%"
That means crit dmg should be 1+(0.5*2)
So crit dmg should be 2
It's working like this for EVERY talent, spell in this game
If i remember correctly DK have passive stating that they deal double crit damage with their spells unlike other magic users (or something like that)

**Comment by Jenovas** [comment]
Varchord - there was a bug on retail that made imprv devouring plague crit for 150% when you are shadow. I showed you the issues players wrote to blizzard. Also when we check Shadow Power in the DBC it is made in such a way that it doesnt effect Imprv Devouring Plague. Blizzard must have added a hotfix that fixed this issue.

**Comment by Varchord** [comment]
But these topics are from year 2010 and 22.01.2011
Patch 434 came live 30.11.2011

**Comment by Jenovas** [comment]
That's why I'm saying that I'll be looking into it, because the topics were made not on 4.3.4, but saying it always was and always should have been x2 is wrong. I also used simcraft for 4.3.4 and it showed that Imprv Devouring Plague should crit for 1.5 and that's why I thought the bug didnt get fixed from earlier patches of Cata. I'm at work now so I wont be searching for data regarding this spell, once I get home today I'll check the link you guys gave.

Have a nice day and calm down.

**Comment by Malylolek** [comment]
From 05.08.2012 [ 4.3.4 patch] 
http://www.worldoflogs.com/reports/4p1u54ykme6em8gt/spell/63675/?s=3782&e=3900
http://www.worldoflogs.com/reports/4p1u54ykme6em8gt/spell/63675/?s=3019&e=3272

**Comment by Jenovas** [comment]
Should be fixed in rev 4366
