### ISSUE TITLE
[EN] [NPC] Archmage Mordent Evenshade <The Highborne>

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2509]
[Archmage Mordent Evenshade <The Highborne>](http://www.wowhead.com/npc=36479/archmage-mordent-evenshade#comments) is missing from the lower level of the Temple of the Moon.

This also causes quest [A Cautious Return](http://www.wowhead.com/quest=14409/a-cautious-return) to become uncompleted.
Wowwiki : [A Cautious Return](http://www.wowwiki.com/Quest:A_Cautious_Return)

**Comment by Navedonar** [comment]
Fixed soon

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
