### ISSUE TITLE
[EN] [Quest] [Darnassus] A Cautious Return

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2510]
Wow-wiki: [A Cautious Return](http://www.wowwiki.com/Quest:A_Cautious_Return)

As per Wowwiki website blizzard **removed** this quest from Patch **4.0.3a** onwards. This quest is still active on Atlantiss and not completable as the NPC [Archmage Mordent Evenshade <The Highborne>](http://www.wowhead.com/npc=36479/archmage-mordent-evenshade) is missing.

The npc bug can be referenced here #2509

**Comment by Navedonar** [comment]
Fixed soon

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
