### ISSUE TITLE
[EN][Dungeon][Utgarde Keep] Meeting Stone missing

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2514]
The Meeting Stone in front of [Utgarde Keep](http://www.wowhead.com/zone=206/utgarde-keep) (Howling Fjord [58.7,46.7](http://www.wowhead.com/maps?data=495:587467)) is missing:

![pic](http://i.imgur.com/gOFr1Rj.jpg)

see [video](http://youtu.be/RFLS8LK0bsA?t=3m14s)
![pic](http://i.imgur.com/xkwQ4Tc.jpg)

**Comment by Navedonar** [comment]
fixed soon

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
