### ISSUE TITLE
[EN][Quest][Darkshore]The Absent-Minded Prospector

### ISSUE THREAD

**Issue by Maxor2571** [Atlantiss/BugTracker#2516]
NPC stop everytime in the same place near base camp, you can see this on movie 3:33[We need to kill murloc at the bottom of cliff to "reset" NPC. After we completed escort, We can not return quest to Jr. Archaeologist Fred, Question mark doesn't show up 3:45.
https://www.youtube.com/watch?v=KF-_Pt9XlnY
Quest ID 13911

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/648

**Comment by Snake90** [comment]
Still bugged ! The quest was completed but i can't return quest to the NPC and even after a crash/restart, the situation remains the same.
