### ISSUE TITLE
[EN][QUEST][Stonetalon Mountains] Free Our Sisters

### ISSUE THREAD

**Issue by k-kang** [Atlantiss/BugTracker#2518]
http://www.wowhead.com/quest=25662/free-our-sisters

This quest requires you to unlock a few cages and set free the NPCs. Yet the cages are already opened and cannot be clicked. The cages will not respawn. Previously noted in the link below, but has been closed without this issue being resolved.

https://github.com/Atlantiss/BugTracker/issues/2435

**Comment by Aival94** [comment]
I think this is a general issue about cages in stonatalon mountains because they do not close(npc spawn i think) as supposed after some time(probably need restart or extremely too much time to close)

**Comment by Tarvo27** [comment]
Plz fix.

**Comment by lourrific** [comment]
February 26, 2016 and this quest is stilled bugged. Cages are open can not get credit for completion when I click cage.

**Comment by monar92** [comment]
March 27, 2016, we can open it only after dc or restart of server.
Keys: http://www.wowhead.com/item=55200
Npc to kill: http://www.wowhead.com/npc=41062
Npc to save: http://www.wowhead.com/npc=41070

**Comment by morgs71** [comment]
Not working still 4/24/2016

**Comment by Snake90** [comment]
Confirmed : still bugged :/

**Comment by Neokea** [comment]
Confirmed, cages are still opened

**Comment by Snake90** [comment]
Confirmed : still bugged :/ So If you can't fix it : just auto-complete the quest because then all the other quests are blocked!

**Comment by henrythenth** [comment]
Still can't interact with cages.

**Comment by m3inbl0ck** [comment]
Issue still persists. However, I believe it just takes a very long time to close the cages, as I was able to open 4/5 so far.

**Comment by m3inbl0ck** [comment]
Update - cages now closed after server restart 11/3/16

**Comment by Malanie** [comment]
*bump bump*
still open cages

**Comment by 1Andas** [comment]
Confirmed. Cages still don't "respawn" so to speak.

**Comment by rdoherty0** [comment]
Still bugged

**Comment by Khangu** [comment]
I tried do this about 20 minutes after today's res and gues what? Cages were already opened. Well if there are so many quests that can be completed and work fine OLNY ONCE after restart maybe server sould be restarted more often, mmm?

**Comment by Thunderlmao** [comment]
All cages are open. No way to free them. You can't even enter the cages.

**Comment by TheAcidtrip** [comment]
Its July 1st and it's still bugged

**Comment by levinnivel** [comment]
Still bugged

**Comment by Snake90** [comment]
Still bugged. All cages are open :/ The cages are supposed to close after the sisters are released but they remain open ...

**Comment by naakarg** [comment]
Why no one cares about these quests, they are part of the leveling experience, I'm no expert on private server maintenance but is it rly that hard to fix quest scripts that been reported for years now.

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18251-gameobject-horde-cage/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
