### ISSUE TITLE
[ENG][Item] Adventurer's Journal

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2523]
http://www.wowhead.com/item=62237/adventurers-journal#comments

"Adventurer's Journal" crafted by inscription have no effect when used. List of buffs given by the journal:
Terrain Expert: +15% increased movement speed
Learning by Example: +10% quest experience gained
Living Forever: 30% chance to heal yourself for 4-6% of your maximum health, when dealing damage to an enemy
Kneecapper: +15% damage done against Giants
The Great Hunt: +15% damage done against Beasts
Deadly Drive: +15% damage done against Humanoids
Dragonsbane: +15% damage done against Dragonkin
28 Chapters Later: +15% damage done against Undead
Fire and Water: +15% damage done against Elementals
Mechanical Aptitude: +15% damage done against Mechanicals

**Comment by krecik88** [comment]
fixed in 4354
