### ISSUE TITLE
[EN][Quest][Uldum] Neferset Prison

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#2524]
http://www.wowhead.com/quest=27707/neferset-prison
Problem with the quest is that even though the NPC for the quest is where he should be, talking with him doesn't start anything and you can't free him. Makes the quest not able to complete and also breaks the whole chain of quests following it in the Ramkahen story.

**Comment by ASX89** [comment]
ive completed that quest without a problem, u talk to the npc and mobs will spawn so u too kill, done that 1 day ago.

**Comment by Aruzam** [comment]
I know how it works and I've completed it multiple times in the past. What I'm saying is that talking to the NPC did nothing, no mobs spawned. 
I'm saying "did" because it apparently fixed itself after the server restart/crash.

**Comment by Miki91sz** [comment]
Please check this q. When I talk whith NPC nothing happened.

**Comment by krecik88** [comment]
fixed in 5268
