### ISSUE TITLE
[EN][Crashlike][High priority]Pickpocket

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#2525]
It is very possiable that pickpocket in ShadowFang Keep on Heroic is what is causing a crash becuase just as i pickpocketed a mob is there the server crashed then when the server came back up my group was gone and i was Tped out of the dungeon so you might want to check into this.

**Comment by krecik88** [comment]
Can you tell me on which mob it happen? or in which area of instance.

**Comment by Bud1980** [comment]
one of the female mobs just after the 2nd boss as soon as you go up the steps

**Comment by Wolffenstein** [comment]
Coincidence
