### ISSUE TITLE
[PL][Quest][Grizzly Hills] Out of Body Experience

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#2526]
Po zakończeniu questu: Ruuna's Request (http://www.wowhead.com/quest=12328/ruunas-request) nie otrzymujemy następującego zadania: Out of Body Experience (http://www.wowhead.com/quest=12327/out-of-body-experience).
NPC odpowiada jedynie "Greetings <character name>"
Uniemożliwia to wykonanie kontynuacji kolejnych zadań.

Sprawdzane po stronie Przymierza.

**Comment by Pieczyyea** [comment]
Po stronie Hordy faktycznie teleportuje na miejsce, jednak na miejscu NPC gada w kółko to samo, a powinna być dłuższa ścieżka dialogowa.

**Comment by krecik88** [comment]
fixed in 4354
