### ISSUE TITLE
[PL][Quest][Grizzly Hills] Secrets of the Flamebinders

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#2528]
Brak możliwości wykonania zadania: http://www.wowhead.com/quest=12222/secrets-of-the-flamebinders
NPC nie oferuje questu.

**Comment by Kiperr** [comment]
Zrobiłeś wcześniej quest http://www.wowhead.com/quest=12292/local-support ?

**Comment by Avalain** [comment]
Zrobiłem, ściągnąłem nawet addon Quest Completist aby sprawdzić czy nie wykonałem jakiegoś zadania w tej lokacji. Do osiągnięcia achievmentu brakują mi 2 questy.

**Comment by armano2** [comment]
doubled: #3626
