### ISSUE TITLE
[EN][Quest][Icecrown] Vile Like Fire!

### ISSUE THREAD

**Issue by Allowas** [Atlantiss/BugTracker#2529]
http://www.wowhead.com/quest=13071/vile-like-fire

Quest can be completed but animations for flying or for fire balls arent there at all.

![wowscrnshot_030715_152231](https://cloud.githubusercontent.com/assets/10573692/6541650/16828ee0-c4de-11e4-9e2a-4fb98bad7180.jpg)

**Comment by krecik88** [comment]
fixed in 4354
