### ISSUE TITLE
[PL][Object]"I didn't see the water"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#2531]
Co tu dużo pisać :| ...
![wowscrnshot_030715_180540](https://cloud.githubusercontent.com/assets/8941339/6542318/2ddff3ea-c4f5-11e4-9493-de5a382b6c87.jpg)
![wowscrnshot_030715_180510](https://cloud.githubusercontent.com/assets/8941339/6542319/2de52798-c4f5-11e4-9f3b-dab860fb2cd2.jpg)
![wowscrnshot_030115_114939](https://cloud.githubusercontent.com/assets/8941339/6542320/2deec848-c4f5-11e4-98d6-2e99149bed11.jpg)
![wowscrnshot_030115_114918](https://cloud.githubusercontent.com/assets/8941339/6542321/2e056d46-c4f5-11e4-9fe7-87bf18977a46.jpg)
![wowscrnshot_030115_114904](https://cloud.githubusercontent.com/assets/8941339/6542322/2e28c14c-c4f5-11e4-99f1-110c74660ac5.jpg)
 
Tu powinna być woda! - Co to jest???

**Comment by Danelar** [comment]
Te dwa ostatnie screeny to to samo miejsce - tylko, że jestem wyżej - zobaczcie na ziemię pode mną. Te "niebieskie mrówki"...

**Comment by Bildo** [comment]
serio... zmien ustawienia grafiki

**Comment by Danelar** [comment]
To jest problemem?

**Comment by Danelar** [comment]
Na jakie zmienić?
