### ISSUE TITLE
[PL][RAID] The Eye of Eternity

### ISSUE THREAD

**Issue by Fabsik** [Atlantiss/BugTracker#2533]
Podczas bicia Malygos na 3 fazie smoki nie maja energii. Malygos tez się nie pojawia w miejscu gdzie powinien być. Można tez używac na nim spela "Fear".

http://www.wowhead.com/zone=4500/the-eye-of-eternity

Screeny:

http://zapodaj.net/6053c3b68cd9e.jpg.html

http://zapodaj.net/408be7d463b90.jpg.html

**Comment by Aviannaqt** [comment]
Dubel #2347
