### ISSUE TITLE
Southern Barrens

### ISSUE THREAD

**Issue by Bogdan3214** [Atlantiss/BugTracker#2534]
While leveling i noticed some bugs : 
- The NPC's around Fort Triumph cannot be attacked but between Fort Triumph and Desolation Hold there is a dwarf which is attacking everyone but cannot be even targeted.
- 3 bugged quests: "The Butcher of Taurajo", "Smarts-is-Smarts" and "Sabotage!"

**Comment by Bildo** [comment]
bt rules
