### ISSUE TITLE
[EN[Gilneas][Objects][Minor]Gathering nods should be deleted

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#2535]
In the starting zone of worgen(Gilneas) there are some gathering nods which should be removed in this phase at least.I tried to gather all of their coordinates(titan panel addon)

2 Peacebloom - 67.23, 74.47
1 Peacebloom - 67.00, 75.84
1 Peacebloom - 66.18, 75.22
1 Peacebloom - 64.66, 80. 02
1 Copper Ore - 63.87, 59.28
1 Copper Ore - 63.07, 80.24
1 Peacebloom - 59.86, 76.36
1 Silverleaf - 59.40, 74.60
1 Peacebloom - 60.73, 78.29
1 Silverleaf - 61.10, 74.40
1 Silverleaf - 61.39, 73.20
1 Silverleaf - 64.00, 68,76
1 Silverleaf - 63.37, 69.72
1 Copper Ore - 65.35, 68.76
2 Copper Ore and 1 Silverleaf - 53.76, 76.61
1 Copper Ore - 49.81, 71.52
1 Copper Ore - 49.80, 84.35
1 Copper Ore - 47.45, 84.48
1 Peacebloom - 38.40, 81.39

I think that is all.
Youtube Video: https://www.youtube.com/watch?v=kpdLsNQJnvc&t=574

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3558
