### ISSUE TITLE
[ENG][NPC][Borean Tundra] Dead Caravan Guard + Dead Caravan Worker

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2538]
"Dead Caravan Guard" (http://www.wowhead.com/npc=25342/dead-caravan-guard) + Dead Caravan Worker (http://www.wowhead.com/npc=25343/dead-caravan-worker) have a dialogue option "Retrieve Warsong outfit" for both Horde and Alliance players.
This option should only be available for (Alliance) players with the active quest "Plan B" (http://www.wowhead.com/quest=11658/plan-b).

**Comment by IamtheLexx** [comment]
There are several copies of the orc PNJ near the banner, which is a problem. Also, I didn't meet this particular problem when I did the quest yesterday with a reroll (and a some help), but today I returned to do the quest again with another character, and whenever I came close to the banner my framerate dropped to 1. I tried lowering my settings to the minimum but my framerate is still at 1, making it impossible to do the quest at all.

**Comment by TranceAccount** [comment]
@IamtheLexx Are you talking about Warsong Caravan Guards or about the Dead Caravan Guards?

**Comment by TranceAccount** [comment]
#8585

**Comment by TranceAccount** [comment]
## Posted a fix on the forums for the gossip_menu of the Dead Caravan Guards.
