### ISSUE TITLE
[ENG][Quest][Borean Tundra] Secrets of the Ancients

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2540]
http://www.wowhead.com/quest=11910/secrets-of-the-ancients

Again the drop chances of the quest items is screwed up by people killing the corresponding NPCs (http://www.wowhead.com/npc=25707/magic-bound-ancient | http://www.wowhead.com/npc=25709/glacial-ancient) without the quest.

"Magic-Bound Splinter" (http://www.wowhead.com/item=35484/magic-bound-splinter) should have a "Guaranteed" (100%) drop chance according to http://eu.battle.net/wow/en/item/35484
Same goes for "Glacial Splinter" (http://www.wowhead.com/item=35483/glacial-splinter) according to http://eu.battle.net/wow/en/item/35483

**Comment by Navedonar** [comment]
fixed soon
