### ISSUE TITLE
[ENG][Quest][Borean Tundra] Hatching a Plan

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2541]
http://www.wowhead.com/quest=11936/hatching-a-plan

"Frozen Axe" should have a "Guaranteed" (100%) drop chance (http://eu.battle.net/wow/en/item/35586) from "Coldarra Wyrmkin" (http://www.wowhead.com/npc=25728/coldarra-wyrmkin).

**Comment by Navedonar** [comment]
fixed soon
