### ISSUE TITLE
[EN] [Quest] [Deepholm] At the Stonemother's Call

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#2542]
This quest chain stops abruptly after completing  [Resonating Blow](http://www.wowhead.com/quest=26659/resonating-blow) as the quest is not offered by npc [Terrath the Steady](http://www.wowhead.com/npc=42466/terrath-the-steady)

Wowhead:[At the Stonemother's Call](http://www.wowhead.com/quest=26750/at-the-stonemothers-call)
Video: [At the Stonemother's Call](https://www.youtube.com/watch?v=VlQPmN1UW_M)

**Comment by Aival94** [comment]
Try do [Shaken and Stirred](http://www.wowhead.com/quest=26584) as i think is prequisite as well.

**Comment by Dexobox** [comment]
Yeah i cannot do the quest mentioned by you becus the npc is bugged  #2543

**Comment by PVPViddys** [comment]
Confirm she just needs to placed differently, she falls when you enter the room and then will not interact. I tried spamming IWT as well.

**Comment by Avalain** [comment]
I menaged to make her active by making myself "At War" with their faction, attack, cast invisibility to drop aggro. When it was all over I could give/take quests from her.
