### ISSUE TITLE
[EN][Achievement][Eye of The Storm] Storm Capper and Bound for Glory

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#2544]
Storm Capper: http://cata.openwow.com/achievement=212
Bound for Glory: http://cata.openwow.com/achievement=216

3 flag flag captures without death and neither Storm Capper and Bound for Glory achievements are done.

Proof:

![Battleground stats](https://cloud.githubusercontent.com/assets/550384/6545534/501e5004-c58c-11e4-82e6-b34bdf2d7689.jpg)

![Achievements panel](https://cloud.githubusercontent.com/assets/550384/6545535/501ea91e-c58c-11e4-97e1-96396d923054.jpg)

**Comment by Deadlyblonde** [comment]
BUMP. Still don't works.

**Comment by Aviannaqt** [comment]
bump

**Comment by LaveniaGithub** [comment]
Fixed in rev. http://atlantiss.eu/changelog#rev4847
