### ISSUE TITLE
[ENG][Quest][Dragonblight] Rifle the Bodies

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2553]
http://www.wowhead.com/quest=11999/rifle-the-bodies

The whole thing is puzzling. I have done the quest with two chars, but if I try to do it now with my third I get all the crap when looting the "Mage Hunter Personal Effects" (http://www.wowhead.com/item=35792/mage-hunter-personal-effects#contains) but not the needed quest item. The only thing is that sometime the message appears."That slot is empty." Did somebody change the loot table or is something affecting it?

**Comment by Technowizard15** [comment]
OK, after a pause and deleting the cache I retried the quest just now and found the quest item after the fourth try. If nobody experiences the same problems I will close the report in a few days.

**Comment by Technowizard15** [comment]
OK, since nobody has had the same problem it seems that it was on my side, So I'm closing the report.

**Comment by Simgiov** [comment]
Nope, it's not your problem, it has 0% loot chance and should be 100%

**Comment by Hallieth** [comment]
I actually have this problem right now. I have looted all the corpses twice (after their respawn) and still zero drop of the quest item...:(:(

**Comment by TranceAccount** [comment]
http://www.wowhead.com/item=35792/mage-hunter-personal-effects#comments

> By Whittall (2,724 – 9·28) on 2009/01/29 (Patch 3.0.8)		
I got about 50 of the bags before i actaully got the plans. I guess it depends on luck :).

> By they (865 – 5·14) on 2013/07/20 (Patch 5.3.0)		
It took me 92 corpses before I finally got the plans.

Oh my lord. Skip this damned quest.
