### ISSUE TITLE
[EN] [ASHENVALE] Some wrong quest requirements I found

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#2554]
As the title says.
1)
In order to get http://www.wowhead.com/quest=13870/as-good-as-it-gets you should complete these ones first:
http://www.wowhead.com/quest=13865/wet-work
http://www.wowhead.com/quest=13815/making-stumps

Currently the quest is available even if the previous ones are not completed.
2)
Same happens for http://www.wowhead.com/quest=13873/sheelahs-last-wish which can be obtained even without completing http://www.wowhead.com/quest=13871/security (it should not be this way).

**Comment by Daknyas** [comment]
Edit: I found another messed chain.
You can pick http://www.wowhead.com/quest=13841/all-apologies without completing the quest chain that Draaka/Durak gives you, which is (in order):
1.Playing With Felfire http://www.wowhead.com/quest=13730/playing-with-felfire
2.Tell No One! http://www.wowhead.com/quest=13751/tell-no-one
3.Dirty Deeds http://www.wowhead.com/quest=13797/dirty-deeds
4.Rain of Destruction http://www.wowhead.com/quest=13798/rain-of-destruction

**Comment by Quban** [comment]
fix soon
