### ISSUE TITLE
[ENG][Quest][Dragonblight] The Focus on the Beach

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2555]
http://www.wowhead.com/quest=12066/the-focus-on-the-beach

Drop chance for "Ley Line Focus Control Ring" (http://www.wowhead.com/item=36751/ley-line-focus-control-ring) should be 100% (Guaranteed) according to http://us.battle.net/wow/en/item/36751

**Comment by Navedonar** [comment]
fixed soon
