### ISSUE TITLE
[EN][Quest][Northern Stranglethorn Vale] Mind Control

### ISSUE THREAD

**Issue by Canderous** [Atlantiss/BugTracker#2558]
[Braddok's Big Brain] (http://www.wowhead.com/item=58225/braddoks-big-brain#objective-of), the objective for the quest [Mind Control] (http://www.wowhead.com/quest=26774/mind-control) should have a 100% chance to drop from [Braddok] (http://www.wowhead.com/npc=42858/braddok).

**Comment by Navedonar** [comment]
fixed soon
