### ISSUE TITLE
[PL][Professions][Dalaran][Cooking][Fishing]

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#2559]
Kiedy wykonamy jakikolwiek daily nadany przez Katherine Lee (http://www.wowhead.com/npc=28705/katherine-lee), nie mamy możliwości wykonania daily dawane przez Marcia Chase (http://www.wowhead.com/npc=28742/marcia-chase).

Niebieski znak daily questu znika z nad jej głowy po wzięciu cooking daily w Dalaran.

To oczywiście tyczy się strony Przymierza.

**Comment by Misiac** [comment]
Czy przypadkiem tak nie powinno być ? :D

**Comment by Avalain** [comment]
O ile pamiętam z retail to nie, ale jeśli ktoś w 100% może potwierdzić to byłoby zacnie.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1777
