### ISSUE TITLE
[EN] [Quests] [Zangarmarsh] [Objects] More Spore Sacs

### ISSUE THREAD

**Issue by 0135** [Atlantiss/BugTracker#2565]
<a href="http://www.wowhead.com/object=182069/mature-spore-sac">Mature Spore Sacs</a> are unlootable without taking the quest and since <a href="http://www.wowhead.com/quest=9742/more-spore-sacs">More Spore Sacs</a> is a repeatable quest, which you cannot "take", only turn in, making it impossible to complete.

**Comment by Quban** [comment]
fix soon
