### ISSUE TITLE
Czarny ekran po zalogowaniu

### ISSUE THREAD

**Issue by GerY6661666** [Atlantiss/BugTracker#2567]
W trakcie 20 sekundowego wylogowywania zaatakowała mnie przeciwna frakcja, udało mi się przeżyć do końca odliczania ale po wylogowania z postaci mam ekran nieprzerwane ładowanie. Nie wiem co mam robić, proszę o szybką pomoc.

**Comment by jurek1** [comment]
unstuck w panelu na stronie attlantiss
