### ISSUE TITLE
[ENG][Quest][Zul'Drak] I Sense a Disturbance

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2569]
http://www.wowhead.com/quest=12665/i-sense-a-disturbance

https://www.youtube.com/watch?v=y90V-nYQz8Y

One should to be affected with what seems to be an invisibility effect when riding the snow leopard. This must prevent those hostile NPCs all around the temple from attacking you, else the leopard stops moving while you get beaten up.

Also adding the chains to Har'koa would be nice.

**Comment by Quban** [comment]
fix soon

**Comment by Quban** [comment]
fix soon

**Comment by gacek1989** [comment]
Quest doesnt work, please fix it because you cant get achiv for quests in zul'drak

**Comment by Bildo** [comment]
fixed

**Comment by rdoherty0** [comment]
The Snow Leopard never showed up, but I completed the quest by just flying over there, dismounting near the corpse, and walking around, per the suggestions in the wowhead comments.  So it is still bugged, but finish-able.
