### ISSUE TITLE
[EN][Quest][Dustwallow Marsh] Catch a Dragon by the Tail

### ISSUE THREAD

**Issue by agusgk13** [Atlantiss/BugTracker#2570]
So, in this quest you have to gather wyrmtail (http://www.wowhead.com/item=33175/wyrmtail), but the plants which should give it don't work. You can't even select them as they are not selectable objects. Here's a screenshot in which you can see the plant
![wowscrnshot_031015_000533](https://cloud.githubusercontent.com/assets/10890556/6568661/39c64d82-c6ba-11e4-9153-063a294df84c.jpg)
.

**Comment by bgb** [comment]
Confirming this... Have same issue.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Jackalantern** [comment]
This is still a problem as of today.

**Comment by Lovless** [comment]
Today is 13.05 and problem is same as in the first comment.

**Comment by happyreaper111** [comment]
i am facing this problem right now.....

**Comment by GonzaRP14** [comment]
October 1st and I have the same problem..

**Comment by tondiaq44** [comment]
Still nothing...

**Comment by Goraix** [comment]
bump

**Comment by vragni** [comment]
still buged

**Comment by Blackaddder** [comment]
Please fix!!! Still bugged.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7800-2570catch-a-dragon-by-the-tail/?p=31471

**Comment by Syrnikus** [comment]
Still Bugged !! Fix pls

**Comment by BAndysc** [comment]
@Navedonar, thanks
rev [4849]
