### ISSUE TITLE
[ENG][Quest][The Storm Peaks] Mildred the Cruel

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2573]
http://www.wowhead.com/quest=12905/mildred-the-cruel

After accepting the quest one gets the disguise "Lok'lira's Bargain" (http://www.wowhead.com/spell=72914/lokliras-bargain or http://www.wowhead.com/spell=55012/lokliras-bargain I don't know) but it misses the visual effect. One's char only changes appearance if he leaves the area and returns.

**Comment by Quban** [comment]
fix soon

**Comment by bgb** [comment]
Still bugged. When we take quest our character changes visually but its still hostile to npcs so we cant talk and finish quest.

**Comment by Technowizard15** [comment]
I think you should open a new report, I would be astonished if this report would be reopened.
