### ISSUE TITLE
[ENG][Quest][The Storm Peaks] A Change of Scenery

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2574]
http://www.wowhead.com/quest=12921/a-change-of-scenery

https://www.youtube.com/watch?v=9pSc4GAtvos

By accepting the quest you shouldn't loose "Lok'lira's Bargain" (http://www.wowhead.com/spell=72914/lokliras-bargain or http://www.wowhead.com/spell=55012/lokliras-bargain I don't know). You regain it when you enter Brunnhildar Village,  but one should should be able to safely go to it through the Forlorn Mine.
Also submitting the quest shouldn't make the disguise disappear again.

**Comment by Quban** [comment]
fix soon
