### ISSUE TITLE
[EN] [Item] [Quest] [Northern Stranglethorn] Emerine's Telling-Sphere

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#2577]
The item Emerine's Telling-Sphere (http://www.wowhead.com/item=60273/emerines-telling-sphere), given in the quests Water Elementals (http://www.wowhead.com/quest=26729) and You Can Take the Murloc Out of the Ocean... (http://www.wowhead.com/quest=26730), doesn't work.

Emerine's Telling-Sphere : Use: Ask Emerine Junis to teleport to your location within Northern Stranglethorn. (2 Min Cooldown)

When using the item, it does an animation, but the NPC Emerine Junis (http://www.wowhead.com/npc=43885/emerine-junis) is not summoned.

**Comment by Quban** [comment]
fix soon
