### ISSUE TITLE
[EN][Item] Tank heirlooms for JP

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2579]
http://www.wowwiki.com/Bloodsoaked_Skullforge_Reaver
http://www.wowwiki.com/Burnished_Pauldrons_of_Might
http://www.wowwiki.com/Burnished_Breastplate_of_Might

^ Missing from the justice heirloom vendor.

**Comment by zano354** [comment]
http://www.wowwiki.com/Burnished_Breastplate_of_Might

still missing / not added in any heirloom vendor.

**Comment by Sinestra01** [comment]
Still missing tank Chest  from any vendor
http://www.wowwiki.com/Burnished_Breastplate_of_Might
