### ISSUE TITLE
[Hunter][ Dun Morogh]

### ISSUE THREAD

**Issue by Marcin24** [Atlantiss/BugTracker#2583]
Po walce z mobem w szybkim tępie odzyskuję energię. Właściwie to nawet nie muszę jeść czy brać potionów. Podobnie ma mój pet.

**Comment by Marcin24** [comment]
After fight witw npc I get back my health very quickly. Even, I musn't eat or take potion.

**Comment by Wolffenstein** [comment]
Na początkowych levelach tak jest. Polecam pograć na globie.
