### ISSUE TITLE
[ENG][Quest][Sholazar Basin] Power of the Great Ones

### ISSUE THREAD

**Issue by wwlink** [Atlantiss/BugTracker#2584]
http://www.wowwiki.com/Quest:Power_of_the_Great_Ones

Cannot polish the crystal at the exposed lifeblood crystal, also the Frenzyheartmobs cant get attacked regularly so you have to AoE them in order to kill them

**Comment by Pieczyyea** [comment]
If you use AoE, you can get At War with Frenzyheart. It's very interesting,  because "At War" mark and unmark random.

**Comment by wwlink** [comment]
I did not know that, thanks Pieczyyea

**Comment by Arondorwar** [comment]
You can complete it. You need to stand by the crystal, few meters east of the cultist corpse.

**Comment by Pieczyyea** [comment]
Yes it's working now

**Comment by Hexenbane89** [comment]
This quest not working again u can finish part with crystal

**Comment by 1Andas** [comment]
It's doable, did it today. 
Recharge the crystal at the location Arondowar pointed out, aoe the Frenzyhearts.

**Comment by Lidless** [comment]
I just recharged my crystal in the position two steps from the corpse to the direction of the crystal. Ty for posting.

**Comment by jackal86** [comment]
Confirmed it works, you have to be standing in a very specific spot close to the Cultist's corpse. (eastbound)

**Comment by Noviush** [comment]
Confirmed, two steps east from the body.
