### ISSUE TITLE
[EN][Quest][Howling Fjord] The Clutches of Evil

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2585]
[Captain Adams](http://www.wowhead.com/npc=23749) in the Howling Fjord does not have the quest [The Clutches of Evil](http://www.wowhead.com/quest=11157/the-clutches-of-evil), which is the start of a very long quest chain and also is the prerequisite to other quests in Westguard Keep.

Westguard had only 3 quests for me: [Of Traitors and Treason](http://www.wowhead.com/quest=12297/of-traitors-and-treason), [One Size Does Not Fit All](http://www.wowhead.com/quest=11190/one-size-does-not-fit-all), [Shoveltusk Soup Again?](http://www.wowhead.com/quest=11155/shoveltusk-soup-again), but normally there should be many more. I've did those 3 quests to see if they are a secret prereq. for the Clutches... nope.

Captain Adams offers me a quest item for Skorn which normally is not available until much [later](http://www.wowhead.com/quest=11248/operation-skornful-wrath) in the quest chain... maybe he got confused about my quest progress? Using the quest item in Skorn does nothing by the way, the quest giver spawns but has no quests for me.

![pic](http://i.imgur.com/mODKfsw.jpg)

**Comment by Tj20** [comment]
The following quest areas are unavailable because they are follow-ups or otherwise linked to the missing "The Clutches of Evil" quest:

- Gjalerbron
- Skorn
- Whisper Gulch
- Ember Clutch
- Halgrind

![pic](http://i.imgur.com/zFP9a9t.jpg)

**Comment by Tj20** [comment]
I've read in the [TC bug tracker](https://github.com/TrinityCore/TrinityCore/issues/14101) that you first have to complete the quest [News From the East](http://www.wowhead.com/quest=11501/news-from-the-east) (but without proof).

I believe however that this is wrong. [This video](https://youtu.be/JE80Vhj2zeI?t=2m4s) shows that Captain Adams offers "The Clutches of Evil" already, although the player has "News from the East" not yet turned in.

![pic](http://i.imgur.com/iya8dTR.jpg)

I think "News from the East" is just another breadcrumb quest like [To Westguard Keep!](http://www.wowhead.com/quest=11291/to-westguard-keep) but not a prerequisite. As far as I remember it, "The Clutches of Evil" has no pre quests and you can start questing in Westguard Keep immediately, without having done the quests at the Explorer's League Outpost first.

**Comment by Tj20** [comment]
I've decided to check this quest on retail with a level 90 boosted char who never did a single quest in Northrend.

![pic](http://i.imgur.com/kACVV7O.jpg)

As you can see "The Clutches of Evil" has no prerequisites, it can be the very first quest you do in Northrend (and that's how I remember it from the past, too).

**Comment by aendry** [comment]
still broken

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15106-quest-the-clutches-of-evil/

**Comment by Jenovas** [comment]
Fix in 5537
