### ISSUE TITLE
[EN][Quest][Azshara] Fade to Black

### ISSUE THREAD

**Issue by jtKr** [Atlantiss/BugTracker#2587]
http://www.wowhead.com/quest=24467/fade-to-black
I was unable to complete the quest due to Malicion simply hovering in the air above the altar. All he did was follow Katrana with his gaze, but he never picked me up.

**Comment by peacebringer** [comment]
I can confirm this bug, I tried several times today and Malicion is just flying over me.

**Comment by armano2** [comment]
duplicate: #3583
