### ISSUE TITLE
[PL][Quest] The Sub-Chieftains

### ISSUE THREAD

**Issue by Galexia** [Atlantiss/BugTracker#2590]
http://www.wowhead.com/quest=11907/the-sub-chieftains
Niema pokrętła przy pierwszym punkcie. 
http://www.wowhead.com/npc=25833/the-grinder
Niema jak odpalić. Reszta działa poprawnie

**Comment by Navedonar** [comment]
popraw tytuł

**Comment by bgb** [comment]
Confirmed. South Point station bugged.

**Comment by Satyr87** [comment]
rzecz w tym ze do kazdego z tych robotow sa 2 osobne pokretla dla hordziakow i aliantow , u grindera nie ma pokretla dla hordziakow
CO ZA RASIZM !!!

**Comment by HUMBOL** [comment]
BUMP!
http://screenshot.sh/ofisZRrKetOPb

**Comment by Navedonar** [comment]
https://github.com/TrinityCore/TrinityCore/issues/785

**Comment by vragni** [comment]
Dalej nie dziala u hordy

**Comment by Avalain** [comment]
Broken like hopes and dreams of African children.

**Comment by mean931** [comment]
still broken hordeside

**Comment by stanq87** [comment]
bump

**Comment by Bildo** [comment]
fixed
