### ISSUE TITLE
[EN][SPELL][Racial Night Elf] Shadowmeld

### ISSUE THREAD

**Issue by sshad00w** [Atlantiss/BugTracker#2591]
http://www.wowhead.com/spell=58984/shadowmeld

Durning the encounter is in progress and we use Shadowmeld , then instantly reset a combat, and the next one we can use all potions. - really nice bug.

**Comment by Wojmistrz** [comment]
same u can do with invisibility on Mage :) reset potion cd :p

**Comment by sshad00w** [comment]
May u raport separate issue on bugtracker? Thanks:)

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/475
