### ISSUE TITLE
[EN][Item]S4 pvp gear for Mage not shown at PvP honor vendors.

### ISSUE THREAD

**Issue by Zhilextheone** [Atlantiss/BugTracker#2592]
As the title says, all the honor vendors that sell the s4(brutal gladiator's) gear for Alliance show ONLY the off-parts of the set while the main parts (head/shoulders/chest/legs/hands) are not shown/visible for mage class.

Other parts of the sets are visible to other classes but only mages cannot see them. 

S4 gear is one of the coolest looking PvP sets and by fixiing his would really help in terms of transmogrification feature that will be implemented on Atlantiss.

Thanks for reading.

**Comment by planche** [comment]
Rogues also can't obtain that set from vendors.

**Comment by mimaxpl123** [comment]
same with dk

**Comment by Zhilextheone** [comment]
bump

**Comment by Nymonz** [comment]
same with priest :)
