### ISSUE TITLE
Bugged Stoentalon horde quests

### ISSUE THREAD

**Issue by cropower5** [Atlantiss/BugTracker#2593]
http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two The quest can't be handed in.
http://www.wowhead.com/quest=26115/to-be-horde The cutscene in wich Overlord Kromgar gets killed by Garrosh doesn't play and thus the quest can't be completed
http://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress the deffense of krom'gar doesn't start
http://www.wowhead.com/quest=26074/beginning-of-the-end You can't board the ballon with the bomb

**Comment by Navedonar** [comment]
duplicate
