### ISSUE TITLE
[PL][Raid-Cata] Bastion of Twilight / Ascendant Council Heroic

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#2594]
http://www.wowhead.com/zone=5334/the-bastion-of-twilight
http://www.wowhead.com/npc=43735/elementium-monstrosity
http://www.wowhead.com/npc=49821/bound-zephyr

Drugi tydzień z rzędu podczas pierwszego pulla Ascendant Council Heroic w trakcie koncowki 1szej fazy pojawil sie znikąd trasz Bound Zephyr.

http://zapodaj.net/f73148d065cb7.jpg.html

**Comment by InformatorPE** [comment]
Zdarzyła sie też taka próba w której przez całą 2 faze nie było "wirków", a ten "ziemny" tez dziwnie działał (nie wciągał mnie tylko mogłem przechodzić przez niego (specjalnie w 30 sek wchodzilem kilka razy zeby bylo wiadomo o co chodzi))

https://www.youtube.com/watch?v=x00NrRSwXL8

**Comment by iskk** [comment]
U nas traszu nie było.
Wirki przy drugiej parze (Arion+Terrastra) zniknęły nam raz chyba przy wszystkich próbach.
"Studnia" nie wciąga jak masz debuffa od niej więc chyba jest ok.

**Comment by Pazurek** [comment]
Ten Zephyr czasami jest normalnie. A czasami go nie ma i pojawia sie po kilku minutach od zbicia tego trashu. Jest to zaraz 1 mobek na prawo gdy wejdzie sie do sali.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/838 duplicate
