### ISSUE TITLE
[EN][Professions] Engineering tinkering doesn't stack with normal enchants

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#2595]
I spoke with a max level engineer who said that engineering enchants don't stack with normal enchants. For example the on-use tinker on gloves doesn't stack with a normal glove enchant. They should stack. Proof taken from wow wiki:

"Patch 4.0.1 (12-Oct-2010): The belt and cloak tinkers no longer have stats, but all tinkers can now be used alongside general enchants simultaneously..."

"Patch 4.1.0 (26-Apr-2011): Tinker enchantments now stack with regular enchantments."

http://www.wowwiki.com/Tinker_%28engineering%29

Now, I haven't been able to test if this issue is true, since I don't have a max level engineer. I only spoke with a max level engineer who said that the enchants don't stack.

**Comment by Kejmil** [comment]
i just tried it and everything was working fine, i was able to put enchant first, then tinker and vice versa, i suggest you to test yourself before writing on BT
