### ISSUE TITLE
[EN] Wands

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#2596]
I understand there was an issue about this, but it was closed.
I will quote the relevant part from the previous issue: "...the ability "Shoot" with a wand appears to be bugged. After using it, it abruptly stops after 1 or 2 shots at an enemy mob." tho now it's more 2 or 3 shots.
It's still not fixed.

**Comment by kadi2** [comment]
http://atlantiss.eu/changelog#rev4355
You can see there it's still waiting to update.
