### ISSUE TITLE
[EN][Talent][Mage] Ring of Frost and Deep Freeze don't share DR with each other

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#26]
Ring of Frost (http://cata.openwow.com/spell=82676) and Deep Freeze (http://cata.openwow.com/spell=44572) should share DR (Diminishing Returns) with each other since patch 4.2:

"Deep Freeze and Ring of Frost will cause diminishing returns on each other, in addition to the spells they normally share diminishing returns with."
(http://www.wowwiki.com/Patch_4.2.0)

But they don't on PTR :) 

Attention! Deep Freeze should still share DR with other stuns only and Ring of Frost with other incapacites (like Sap, Repentance, Polymorph). There's just exception when "stun" (DF) share DR with "incapacite" (RoF)..

**Comment by blinkmaster** [comment]
.

**Comment by debtheone** [comment]
rly fix it

**Comment by Jenovas** [comment]
You fix it...
Your comments wont get it fixed faster, it might even make it get fixed later than planned

**Comment by debtheone** [comment]
im used to it so np :D

**Comment by Isuel** [comment]
bump. Please, it's important, especially with frost mage being probably one of the most played specs in pvp.

**Comment by debtheone** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
