### ISSUE TITLE
[EN][Raid-Cata] Blackwing Descent / Magmaw Heroic (Warlock BoH)

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#2602]
When we cast Bane of Havoc before exposed head appears, bane of havoc dont do dmg to Magmaw when we dps Magmaw  Exposed Head.

"It’s also a good idea to put Havoc on Magmaw just before he’s chained. It means the body will still take damage as you’re dpsing the exposed head. Then put Havoc on the head just before it disappears again."
Source:
http://forums.elitistjerks.com/topic/117067-warlock-mechanics-in-cataclysm/
http://spellbound.nu/?p=966
https://www.youtube.com/watch?v=DGMXqvGGSkk

**Comment by Jenovas** [comment]
Should be already fixed

**Comment by fafal** [comment]
Still doesnt work
