### ISSUE TITLE
[EN][Shaman][pet/guardian] Elementals doesnt have avoidance (or its not working).

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#2605]
Elementals like all pets and guardians shoud have avoidance, but now they die every time boss uses one of his aoe dmg spells. It's pretty annoying.

Ex. :
-Sinestra's breath (http://www.wowhead.com/spell=90125/flame-breath)
-Maloriak's Engulfing Darkness (http://www.wowhead.com/spell=92754/engulfing-darkness)
-Maloriaks's Scorching Blast (http://www.wowhead.com/spell=77679/scorching-blast)

Fire elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

Earth elemental totem:
http://www.wowhead.com/spell=2894/fire-elemental-totem

**Comment by Jenovas** [comment]
Fixed in rev 4360
