### ISSUE TITLE
[EN][Quest][Howling Fjord] "Gambling Dept"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2607]
[Taruk](http://www.wowhead.com/npc=24541/taruk) does not offer the quest [Gambling Dept](http://www.wowhead.com/quest=11464/gambling-debt) to me as Alliance which is the start of a small quest chain.

This seems to be an Alliance-only problem because I just saw a Horde player fighting against the quest mob (and the mob glitched through the roof of the tent).

![pic](http://i.imgur.com/1EWRyZ2.jpg)

Wowhead comments mention that you have to do the quest [Forgotten Treasure](http://www.wowhead.com/?quest=11434) first to unlock this, but I did that. 

May be related to closed issue #878 about that quest, not sure.

priv-status has this quest marked as Horde only, but Wowhead has it marked as both and I remember doing the quest chain as Alliance on retail.

**Comment by MercuricUma** [comment]
I auto attacked him in human form and he died, without surrender :(  (feral tank druid)
