### ISSUE TITLE
[EN][Spell][Mage] Arcane Brilliance

### ISSUE THREAD

**Issue by ksgm92** [Atlantiss/BugTracker#2608]
http://cata.openwow.com/spell=1459
It sometimes doesn't increase the spell power, the increase mana does work fine, but the %SP doesn't seems to work properly...

I tested it with a Lesser Wizard Oil (http://cata.openwow.com/item=20746) and when I put this on my weapon it kinda forces Arcane Brilliance to increase its % but is kinda buggy, sorry if i'm not being too specific its my first report and i'm new to the server

**Comment by kadi2** [comment]
Relted to https://github.com/Atlantiss/BugTracker/issues/1320

**Comment by ASX89** [comment]
It seems the problem has got to do with the armors (Mage Armor and Molten Armor etc) if u cast armor, then Arcane Brilliance and then remove the armor it fixes the spell power.

**Comment by ksgm92** [comment]
well, i have tested it with other stuff, for example, if you buff with arcane brilliance and then swap an item from your gear out and in, it will apply the %sp increase, so i guess the problem is with some type of refresh mechanic maybe it isn't updating properly after the buff...

**Comment by ASX89** [comment]
well... ive been testing and it seems its just visual bug on Caracter Info (C).
