### ISSUE TITLE
[PL] [Quest] [The Lost Isles] Warchief's Revenge

### ISSUE THREAD

**Issue by narosky** [Atlantiss/BugTracker#2610]
Wszystko z questem jest najbardziej OK, poza tym, że owy "wir" powinen przenieść nas na jego koniec do Wild Overlook, a wraca z nami na statek, przez co musimy płynąć wpław, a następnie spacerować, żeby oddać questa, co zajmuje dodatkowo ~10min.

**Comment by Bildo** [comment]
zasady bt przeczytaj je rowniez jest to duplikat
