### ISSUE TITLE
[PL][Item] Arcanum of the Dragonmaw & Arcanum of the Wildhammer

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#2612]
http://wow.gamepedia.com/Arcanum_of_the_Dragonmaw 
http://atlantiss.eu/armory/item/62368
http://atlantiss.eu/armory/item/68763

http://wow.gamepedia.com/Arcanum_of_the_Wildhammer 
http://atlantiss.eu/armory/item/62422
http://atlantiss.eu/armory/item/68767

Od czasu zniesienia Twilight Shift w Twilight Highlands Alliance dostało możliwość kupienia enchantu na head dla melee dps, gdyż ich Quartermaster - http://www.wowhead.com/npc=49386 posiada zarówno enchant wymagający reputacje jak i ten nie wymagający, kiedy Quartermaster Hordy - http://www.wowhead.com/npc=49387 posiada tylko ten wymagający reputacji revered.

Fajnie by było dodać możliwość kupna hordzie gdyż melee musi biegać z enchantem pvp lub zabrać obu Quartermasterów gdyż TH nie działa.

**Comment by Malylolek** [comment]
W obecnej sytuacji dużo aliantow juz lata z tą łatką wiec samo usuniecie jej z ich Quartermastera było by niesprawiedliwe dla hordy.

**Comment by nerv234** [comment]
Bump horda też chce.

**Comment by Malylolek** [comment]
BUMP !

**Comment by nveri** [comment]
BUMP.

**Comment by Nc94** [comment]
@up
Już można repe wbić...

**Comment by nveri** [comment]
przeciez nie mozliwosc chodzi. do powinno byc do uzytku bez repy.
