### ISSUE TITLE
[PL][Quest] There Is No Hope

### ISSUE THREAD

**Issue by mockingjay21** [Atlantiss/BugTracker#2613]
Witam,
Chciałbym zglosic problem z questem "There is no hope", który jest ostatnim questem z chaina, którego wykonujemy w nagrand.
Mianowicie po wykonaniu questa, nie dostajemy "rewards"(nagrody), gdzie wg. wowhead, owy Quest został dodany w patchu 3.3.0 i po rozmowie z npc powinniśmy miec do wyboru 4 nagrody w postaci 4 itemów. W naszym przypadku wyglada to tak, że zagadujemy do npcta i mamy tylko opcje "complete quest". 

Link do questa: http://www.wowhead.com/quest=10172/there-is-no-hope
ss z questa: 
![wowscrnshot_031315_134149](https://cloud.githubusercontent.com/assets/11462665/6642281/d354eb66-c9a3-11e4-8948-d322f78b5aa2.jpg)

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3880
