### ISSUE TITLE
[EN][Quest][Western Plaguelands] I'm Not Supposed To tell you this

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#2614]
http://www.wowhead.com/quest=27392/im-not-supposed-to-tell-you-this
While the quest is completable, the ghost wolf wanders around instead of staying on its spawn spot.
Its model also doesn't have a sword stuck in the head like it should.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2443
