### ISSUE TITLE
[En][Mage][Talent/spell] Impact / living bomb

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#2615]
After the fix when you use impact to spread living bomb the main target loses living bomb when it shouldn't. it was fixed by blizzard in patch 4.2 
Fire
When Impact spreads Living Bomb, it will only be spread to two additional targets. The net effect is that if the mage's most recent Living Bomb target is the same as their Impact target, that target will no longer lose the Living Bomb effect. If Living Bomb is active on multiple targets when the Impact effect is cast, Living Bomb will remain active on the most recent Living Bomb target, and will be added to two other nearby targets.

**Comment by Wuxia88** [comment]
Bug occure when there are more than 3 targets. When we have 3 target and use living bomb on main target then spread by impact - all 3 targets got living bomb. When we have more than 3 targets, after using LB on main target it dissapears on main target and spreads to other 2 targets, so we have LB only on 2 targets without possibility to spread it further.
Very annoying bug when fighting high multi-target encounters.

**Comment by Jenovas** [comment]
Are you sure that 2 targets? I did tests and I see 3 targets with living bomb

**Comment by Wuxia88** [comment]
Yes I'm sure. Yesterday confirmed it on halfus hc encounter. In addition CombustionHelper addon which tracks LB goes completly mad after impact with more than 3 targets, and shows empty tracking bars without any data. Also on trash groups before Cho'gal impact spreads LB on 2 targets but loses LB on main target.

**Comment by adryjan** [comment]
I ve just did a test, it's confirmed, if u have more than 3 targets then LB from your main target is lost. Tested on 3 dummy and works fine, tested on 4 mobs in Deepholm and I ve lost LB from main target.

**Comment by Caturix** [comment]
Confirmed bug, very annoying.

**Comment by Jenovas** [comment]
Fixed in rev 4831
