### ISSUE TITLE
[EN][Mage][Spell] Mirror Image

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#2617]
using mirror image causes friendly targets to lose target from you, it should only affect enemy players/monsters.
http://wow.gamepedia.com/Mirror_Image
http://www.warcraftmovies.com/movieview.php?id=212147
about 5.55 sec. 
additionally, Mirror Image when should start attacking exactly the same moment they are summoned and if there is no enemy in their cast range ( 30yd or smth) but mage is in combat they should chase after targets and start casting at them

**Comment by blinkmaster** [comment]
bump, added some info

**Comment by sunshineinabox** [comment]
The mirror images are pretty useless right now usually when you summon them they don't end up attacking. If you move around 2/3 or 1/3 attacks, but on very few occasion do all three actually start attacking.

**Comment by armano2** [comment]
simmilar: #2059
