### ISSUE TITLE
[ES][Quest][Westfall] Rise of the Brotherhood

### ISSUE THREAD

**Issue by Eledrik** [Atlantiss/BugTracker#2618]
A la hora de hablar con el Rey Varian para recibir la recompensa de esta misión en Ventormenta, dentro del cuadro de diálogo no aparece la opción para entregar la misión. Adjunto captura del juego:

http://i.imgur.com/h2uG1zH.jpg

**Comment by Bildo** [comment]
Unfortunately we are not supporting Spanish so next time pls use english also this is a duplicate.https://github.com/Atlantiss/BugTracker/issues/2322
