### ISSUE TITLE
[EN][RAID-VANILLA]Temple of Ahn'Qiraj & Ruins of Ahn'Qiraj

### ISSUE THREAD

**Issue by Ulrich1able** [Atlantiss/BugTracker#2619]
When you enter these instances, no mobs or bosses spawn whatsoever. The whole instance is a ghost town, the little flag above the minimap also says 0.
The other vanilla raids (Blackwing Lair & Molten Core) work and mobs spawn in those, but not in these Ahn'Qiraj raids.

http://www.wowhead.com/zone=3429/ruins-of-ahnqiraj
http://www.wowhead.com/zone=3428/temple-of-ahnqiraj

**Comment by Bildo** [comment]
change difficulty to normal
