### ISSUE TITLE
[EN][Quest][Zone] Catch a Dragon by the Tail Quest

### ISSUE THREAD

**Issue by KinnoAtlantiss** [Atlantiss/BugTracker#2621]
Quest explanation can be found here: http://www.wowhead.com/quest=27413/catch-a-dragon-by-the-tail

How it looks like at the moment: Wyrmtail stalks do exist on the ground but they are not lootable.

How it should look like can be seen here: https://www.youtube.com/watch?v=4LkNKN5A2Xo

**Comment by Navedonar** [comment]
Duplicate
