### ISSUE TITLE
[EN]Falling below the ground from fear

### ISSUE THREAD

**Issue by Chori97** [Atlantiss/BugTracker#2625]
Hello,
I was doing this quest http://www.wowhead.com/quest=27382/rough-roads and this npc http://www.wowhead.com/npc=8600/plaguebat used his ability http://www.wowhead.com/spell=6605/terrifying-screech and when i was fleeing in fear i suddenly fell below the ground. I couldn't reset but after waiting 6 mins it spawned me on the graveyard.
I have heard that this happens sometimes, please consider fixing this and the pathfinding at all. 
![wowscrnshot_031415_130359](https://cloud.githubusercontent.com/assets/11473302/6651481/a52c7200-ca4c-11e4-83d4-332fa358cdde.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1970
