### ISSUE TITLE
[EN][Quest][Cape of Stranglethorn] Ol' Blasty

### ISSUE THREAD

**Issue by Illedran** [Atlantiss/BugTracker#2627]
I can get on the cannon and shoot at the dummy(http://www.wowhead.com/npc=43560/smilin-timmy-sticks): the dummy takes damage but I do not credit for the quest.

Quest link: http://www.wowhead.com/quest=26647/ol-blasty

Screenshot: http://i.imgur.com/ncRvZ9X.jpg

**Comment by Illedran** [comment]
After killing the dummy with normal attacks, I can now hit it with the cannon and I get credit.

**Comment by dstn3422** [comment]
reported on match 14th - still bugged, good job

**Comment by lourrific** [comment]
Smilin' Timmy Sticks is underwater now, not in a boat as he supposed to be. You are able to fire at him with the cannon but it does no damage and you get no credit for quest. can not complete quest.

**Comment by Bildo** [comment]
fixed
