### ISSUE TITLE
[EN][Core] Spells "disappear"

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#263]
Whenever you lose vision of the target, every spell that is in the mid-air will lose its destination and will have no effect which is incorrect.
http://youtu.be/sQj3_jnjCdg?t=56s // Stealth and Vanish
http://youtu.be/Wmzlh6ZIg4M?t=16m1s // Stealth
Im sure it's not stealth, vanish or prowl related since when i have vision of the target everything works preety fine.
The fact there is no added custom delay to all the skills (except for Shadow Word: Death) has nothing to do with this bug report at all as you can see at second movie with stealth.

BTW: When it comes to making mid-air spells "disappear" there are only 2 known effects that can do it (haven't tested them): Mage's Invisibility and Shadowmeld.

**Comment by kadi2** [comment]
Just wanted to add the information about Shadowmeld being the only exception to this rule before it has been totally fixed LONG TIME AGO during 4.0.6 on the server.

**Comment by Wolffenstein** [comment]
Nope, it's unrelated to 4348.

**Comment by lamaATS** [comment]
Fixed in rev. 5498
