### ISSUE TITLE
[EN][Quest][Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by CredZeg** [Atlantiss/BugTracker#2630]
In the quest after placing the totem it should start spawning waves after waves of                                       "Fire Elemental Remnat" and after waves the boss. But instead it spawns 1, sometimes 2 of "Fire Elemental Remnat".

![wowscrnshot_031415_143837](https://cloud.githubusercontent.com/assets/11473791/6651688/e42fa232-ca57-11e4-9c6e-28dd4da61c1b.jpg)

 So it makes quest incompletable and you cannot continue questline.
More information about the following quest: http://www.wowhead.com/quest=13580/soothing-the-elements and http://wow.gamepedia.com/Quest:Soothing_the_Elements .

P.S. I was playing as worgen race and rogue class.

Thank you for your atention.

CredZeg

**Comment by Tj20** [comment]
I like your report, but it already exists on bug tracker: #1521
