### ISSUE TITLE
[EN][Quest][Uldum] Fire From the Sky

### ISSUE THREAD

**Issue by Allowas** [Atlantiss/BugTracker#2632]
http://www.wowhead.com/quest=28497/fire-from-the-sky

After I click on only valuable demolisher , screen goes black after that all demolisher with NPCs around them are gone. Even NPCs which are supposed to be killed are now untargeble.

Before
![wowscrnshot_031415_140858](https://cloud.githubusercontent.com/assets/10573692/6651755/c200d8ce-ca53-11e4-8674-b9b15ead9bc7.jpg)

After
![wowscrnshot_031415_140921](https://cloud.githubusercontent.com/assets/10573692/6651756/c73d13ca-ca53-11e4-9e9b-16ad18935f63.jpg)

**Comment by Bildo** [comment]
duplicate
