### ISSUE TITLE
[PL] Naxxramas/10/men/LastBoss/Kel/

### ISSUE THREAD

**Issue by Dariwa99** [Atlantiss/BugTracker#2634]
Cześć, chciałem zgłosić ze  ostatni boss na naxxarusie 10 osobowym buguje się, w fazie gdzie trzeba go bic nie da sie go z targetowac mimo ze boss trzyma na kims agro i walka powinna trwać normalnie jednak nikt nie możne go z targetowac. Robimy kilka razy reparty, restart. Dodam ze to nie jest przyczyna że zbijamy za szybko (swoje odczekaliśmy) mobki, addy bo i addy tez sa zbudowane i nawet nie podchodzą do środka zwyczajnie stoją w sobie i w tych korytarzach i często wchodzą w tekstury. Zgłaszam bo wiadomo niebawem  będzie trasmo i ludzie będą śmigać na pre cata rajdy po itemki. Jeśli będziecie mieli chwile to będę wdzięczny za naprawę.

**Comment by Bildo** [comment]
duplikat
