### ISSUE TITLE
[EN][NPC] Bloodscalp Berserk

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2640]
What is not working?
=============

Bloodscalp Berserk is spamming "Enrage".

---------------
How should it work?
=============

He should only use it once.

---------------
More info:
=============

[Screenshot](http://i.imgur.com/GWx59vj.jpg)
[Bloodscalp Berserk](http://www.wowhead.com/npc=597/bloodscalp-berserker)
[Bloodscalp Berserk's Enrage](http://www.wowhead.com/spell=8599/enrage)

**Comment by Quban** [comment]
fix soon
