### ISSUE TITLE
[EN][NPC] Dead Trooper

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2641]
What is not working?
=============

Some Dead Troopers are standing up. They don't seem to be dead at all...

---------------
How should it work?
=============

All Dead Troopers should be in the "dead position".

----------------------
More info:
=============

There guys are part of ["Fashionism" quest](http://www.wowhead.com/quest=27941/fashionism), even though that some aren't in the correct position, all of them are working fine.

[Screenshot](http://i.imgur.com/FgEmzcF.jpg)
[Dead Trooper #1 - WoWHead](http://www.wowhead.com/npc=47219/dead-trooper)
[Dead Trooper #2 - WoWHead](http://www.wowhead.com/npc=47207/dead-trooper)
[Dead Trooper #3 - WoWHead](http://www.wowhead.com/npc=47216/dead-trooper)
[Dead Trooper #4 - WoWHead](http://www.wowhead.com/npc=47213/dead-trooper)

**Comment by Quban** [comment]
fix soon
