### ISSUE TITLE
[EN][NPC] Neltharaku

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2644]
What is not working?
=============

Neltharaku seems to be standing on a invisible flying platform and he has no "patrol path".

---------------
How should it work?
=============

He should be in "flying mode" and should be flying around that area. 

---------------
More info:
=============

Important NPC because he plays a huge role on the Netherwing chain-quest.

[Screenshot](http://i.imgur.com/KZUeHKB.jpg)
[Neltharaku](http://www.wowhead.com/npc=21657/neltharaku)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1365
