### ISSUE TITLE
[EN][Quest][Northern Stranglethorn] Speaking with Gan'zulah

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2647]
What is not working?
=============

You can get (and complete) this quest.

---------------
How should it work?
=============

This quest should not exist in the last patch (4.3.4) of Cataclysm expansion.

---------------
More info:
=============

This quest got removed in patch 4.0.3a.

[Screenshot](http://i.imgur.com/byYawGD.jpg)
[Speaking with Gan'zulah - WoWHead](http://www.wowhead.com/quest=586/speaking-with-ganzulah)
[Speaking with Gan'zulah - WoWPedia](http://wow.gamepedia.com/Quest:Speaking_with_Gan%27zulah)

**Comment by Quban** [comment]
fix soon
