### ISSUE TITLE
[EN][Quest][The Cape of Stranglethorn] An OOX of Your Own

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2648]
What is not working?
=============

You are able to pick and complete the quest without saving all chickens.

---------------
How should it work?
=============

After saving all 3 chickens, [Oglethorpe Obnoticus](http://www.wowhead.com/npc=7406/oglethorpe-obnoticus) should give you the quest that gives you a robot chicken to play with.

---------------
More info:
=============

One of the most iconic quests of WoW must get some love.

[Screenshot](http://i.imgur.com/pIXAfxo.jpg)
[An OOX of Your Own - WoWHead](http://www.wowhead.com/quest=3721/an-oox-of-your-own)
[An OOX of Your Own - WoWPedia](http://wow.gamepedia.com/Quest:An_OOX_of_Your_Own)
[Rescue OOX-17/TN! - WoWHead](http://www.wowhead.com/quest=648/rescue-oox-17-tn)
[Rescue OOX-09/HL! - WoWHead](http://www.wowhead.com/quest=836/rescue-oox-09-hl)
[Rescue OOX-22/FE! - WoWHead](http://www.wowhead.com/quest=25476/rescue-oox-22-fe)

**Comment by Quban** [comment]
fix soon
