### ISSUE TITLE
[EN][Spell][Warrior] Inner Rage

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#2649]
What is not working?
=============

Inner Rage cannot be learned at level 56.
Trainers say that you must be level 83.

---------------
How should it work?
=============

It should be "learnable" at level 56.

---------------
More info:
=============

This was a change made in patch 4.1 (from 83 to 56).
It got removed in patch 5.0.4, so it's impossible to find it on WoWHead now.

[Screenshot #1](http://i.imgur.com/v7zdt3M.jpg)
[Screenshot #2](http://i.imgur.com/WCJYvFC.jpg)
[Inner Rage - WoWHead](http://www.wowhead.com/spell=1134) 
[Inner Rage - WoWPedia](http://wow.gamepedia.com/Inner_Rage)
[Inner Rage - OpenWoW](http://cata.openwow.com/spell=1134)

**Comment by Kejmil** [comment]
http://wow.gamepedia.com/Inner_Rage

**Comment by Quban** [comment]
fix soon

**Comment by lanrutcon** [comment]
The problem still persists, at least on my warrior (level 63).
Checked the same trainers (Orgrimmar) and they still say that I need to be level 83 to get it.

**Comment by sigmundfreud2016** [comment]
it is still bugged.

**Comment by Quban** [comment]
should work after server update
