### ISSUE TITLE
[PL][Crash-like][The Shattered Halls] Shattered Hand Zealot

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#2650]
Witam!
Atakowanie mobów o nazwie Shattered Hand Zealot (http://www.wowhead.com/npc=17462/shattered-hand-zealot) może powodować crashe serwera, a przynamniej crashe gry. Może to powodować dodatkowo użycie sżarży na te moby. Na razie spowodowało to crashe dwa razy.

**Comment by Exclibrion** [comment]
potwierdzam

**Comment by Aival94** [comment]
I think it has been reported: #870
