### ISSUE TITLE
[PL][Class][Paladin][Talent] Light of Dawn

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#2651]
Link talentu: http://cata.openwow.com/spell=85222
Link tematu: http://us.battle.net/wow/en/forum/topic/2369682241
Link logów: http://worldoflogs.com/reports/2t7hjvn7n1iygmu1/details/0/?s=1573&e=1770

Spell nie korzysta z crita. Jedyny dowód na to, że powinien to temat na forum battle.net z okresu Cata. Lepsze byłyby logi, więc jeśli ktoś takimi dysponuje prosiłbym o ich wstawienie. Jednak na chłopski rozum nie widzę powodu, żeby nie critował.

Edit: Dodane logi.

**Comment by iskk** [comment]
http://worldoflogs.com/reports/2t7hjvn7n1iygmu1/details/0/?s=1573&e=1770
Czegoś takiego szukasz?
Skada z wczorajszego BWD też nie pokazuje critów.

**Comment by Glare** [comment]
Dokładnie tak. Widać jak na dłoni, że Light of Dawn korzystał z crita. Dzięki wielkie.

**Comment by Kejmil** [comment]
jest to kolejny skill ktory z jakiegos powodu nie crituje a powinien (przed naprawa mial to shockwave prot warka), moze istnieje jakis bug globalny ktory to powoduje?
https://github.com/Atlantiss/BugTracker/issues/2359

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
