### ISSUE TITLE
[PL][Paladin][Talent] Infusion of Light

### ISSUE THREAD

**Issue by Wojowniczka** [Atlantiss/BugTracker#2652]
chodzi o ten talent http://www.wowhead.com/spell=53576/infusion-of-light  zauważyłem że jak zrobi się kombinację Holy Shock kryt =proc Infusion of Light >> cast Holy Radiance >> kolejny Holy Shock kryt załączy się proc Infusion of light to zostaje skonsumowany przez Holy Radiance z poprzedniego proca co jest bugiem.

Holy Shock kryt(proc talentu) + Holy Radiance + Holy Shock kryt(proc talentu który za sekundę zostaje zjedzony przez trwający Holy Radiance z poprzedniego proca) tak się zrekonstruuję tego buga.

http://www.wowhead.com/spell=25914/holy-shock < Holy Shock
http://www.wowhead.com/spell=82327/holy-radiance < Holy Radiance
http://www.wowhead.com/spell=53576/infusion-of-light < Infusion of Light

**Comment by Glare** [comment]
A już myślałem, że to tylko moja wyobraźnia. Nie mogłem dojść do tego co mi zjadało buffa z Infusion of Light. Wygląda na to, że to HoT z Holy Radiance.

**Comment by Wojowniczka** [comment]
wszedłem dziś na paladyna(po miechu nie grania nim czy coś) i poszedłem sobie na RHC pohealać no i mnie wkurzało to że mi zjadało proca..... :P a wykryć było bardzo łatwo ^^ także czekam na fixa :)

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
