### ISSUE TITLE
[EN] [Spell] [Priest] Shadowy Apparition

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#2653]
In few words: they are vulnerable to all AoE spells from mobs/bosses, and that is bugged.
In topic(http://atlantiss.eu/community/viewtopic.php?f=85&t=1330) on forum, Lanrutcon pointed that their immunities should be the same as shaman's totems(and he posted video with the example of AoE influence at Shadowy Apparitions).
And some comparison from global/our server:
g:http://www.worldoflogs.com/reports/rt-2z93bleivct1yu8w/details/53/?s=17782&e=18356
a:http://www.worldoflogs.com/reports/rt-2kn43xo386fmoinn/details/19/?s=2437&e=3002&x=sourceName%3D%22Shadowy+Apparition%22
As you can see there's a difference in "damage taken" table.

**Comment by Jenovas** [comment]
Fixed in rev 4360
