### ISSUE TITLE
[ENG][NPC][Hellfire Peninsula] Kalaen not selling Jeweler's Setting

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2654]
Kalaen (http://www.wowhead.com/npc=18751/kalaen) should sell "Jeweler's Setting" (http://www.wowhead.com/item=52188/jewelers-setting#sold-by:0+3+1).

**Comment by Technowizard15** [comment]
Update: Add Parnis (http://www.wowhead.com/npc=16613/parnis) and Gelanthis (http://www.wowhead.com/npc=16624/gelanthis#sells:0-2) to the list.

By the way Gelanthis has the wrong model and inventory, he for example should be male not female .... OK he really needs a total overhaul, he is totally screwed up.

**Comment by Technowizard15** [comment]
Sara Lanner (http://www.wowhead.com/npc=52588/sara-lanner) is missing completely in Undercity.

**Comment by Quban** [comment]
fix soon

**Comment by Quban** [comment]
fix soon
