### ISSUE TITLE
[PL][Quest] Coldridge Valley

### ISSUE THREAD

**Issue by maslak** [Atlantiss/BugTracker#2655]
WAŻNE!

Chain u krasnoludów nie działa poprawnie. Po wbiciu 3 poziomu dalszych zadań nie ma.

Po zrobieni krasnala działają te zadania w takiej kolejności

1.Hold the Line!
http://www.wowhead.com/quest=24469/hold-the-line
2.Give 'em What-For
http://www.wowhead.com/quest=24470/give-em-what-for
2. Aid for the Wounded
http://www.wowhead.com/quest=24471/aid-for-the-wounded
3. Lockdown in Anvilmar
http://www.wowhead.com/quest=24473/lockdown-in-anvilmar
4. All the Other Stuff
http://www.wowhead.com/quest=24475/all-the-other-stuff
4. First Things First: We're Gonna Need Some Beer
http://www.wowhead.com/quest=24474/first-things-first-were-gonna-need-some-beer
4. Dwarven Artifacts
http://www.wowhead.com/quest=24477/dwarven-artifacts
5. Wbicie 3 lvl i zadanie Arcane Rune
http://www.wowhead.com/quest=24496/arcane-rune
6. Filling Up the Spellbook
http://www.wowhead.com/quest=24526/filling-up-the-spellbook

I na tym się zadania kończą. Nie ma kolejnego. Dałem całą liste od początku bo nigdy nie grałem krasnalem i nei wiem jaki powinien być kolejny quest. Na pewno nie jest to dobra reklama gdzie podstawowy chain nie działa.

Pozdro.

**Comment by Kejmil** [comment]
bo trzeba miec priorytety :D

**Comment by maslak** [comment]
Temat odswieżam.

Od npc Grundel Harkin brakuje zadania Make Hay While the Sun Shines
http://www.wowhead.com/quest=24486/make-hay-while-the-sun-shines
Gdzie itemy z mobów lecą nawet bez wzięcia zadania, którego tutaj nie ma lol

Następnie brakuję zadania :Whitebeard Needs Ye
http://www.wowhead.com/quest=24487/whitebeard-needs-ye
A reszta to już na wowhead jest :)
Startowe zadania u brzydkich gnomów działają a krasnale nie, przykre.

**Comment by Wolffenstein** [comment]
Fixed in rev 4367.
