### ISSUE TITLE
[PL][Class][Shaman][Spell] Healing Stream Totem

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#2658]
Link do spella: http://www.wowhead.com/spell=5394
Link do mastery: http://www.wowhead.com/spell=77226
Link do gamepedii: http://wow.gamepedia.com/Healing_Stream_Totem

Nie korzysta z Mastery. Dowody na to, że powinien: komentarze pod samym totemem z czasów Cata, opis spelli na które działa Mastery oraz opis z gamepedii.

**Comment by kadi2** [comment]
Was benefiting from mastery at the very of beginning of "pre-patch"

**Comment by mrkariox** [comment]
21.05.2015 still not working

**Comment by Kejmil** [comment]
@Aviannaqt fixed in rev 4889
