### ISSUE TITLE
Undercity and Silvermoon bosses are gone 

### ISSUE THREAD

**Issue by spartanski** [Atlantiss/BugTracker#2661]
For over 2 days they seen to do not respawn i have been checking constantly they are not there  :)

**Comment by Aival94** [comment]
If they have the same respawn time as world bosses thye should respawn after 2-4 days after they killed which mean 2 more days to check them the maximun.

World bosses respawn time: http://www.wowwiki.com/World_boss

**Comment by Ulrich1able** [comment]
We just killed all the horde leaders 2 days ago, so according to what aival said, they should spawn soon :)

**Comment by lanrutcon** [comment]
Most leaders should have [2hours respawn time](http://wow.gamepedia.com/For_The_Horde!#Victory.21), according to WoWPedia.
But some have really small respawn timer like [Garrosh](http://wow.gamepedia.com/For_The_Alliance!#Just_GO.21) and [Lor'themar](http://wow.gamepedia.com/For_The_Alliance!#Killed_in_Quel.27Thalas) (5-10mins).
This prevents players to be stuck on some quests.

**Comment by PVPViddys** [comment]
@Aival94 They are not "World Bosses" they are faction leaders. 2 hr respawn would be correct.

**Comment by Navedonar** [comment]
bt rules
