### ISSUE TITLE
[PL][Item] Gilnean White

### ISSUE THREAD

**Issue by imeasytokill** [Atlantiss/BugTracker#2662]
Item ten sprzedawany powinnien być przez vendorów (i tylko w Twilight Highlands)

http://www.wowhead.com/item=58276/gilnean-white#sold-by

NPC'ów nie ma bo nie jest oskryptowane Twilight Highlands.

Czy jest możliwość dodania tych npc lub dodanie Gilnean White u jakiegoś innego vendora.

Uniemożliwia to wykonanie achievementu Cataclysmically Delicious
http://www.wowhead.com/achievement=5753/cataclysmically-delicious

**Comment by monibu** [comment]
małą rzecz, ale parę osób by ucieszyło

**Comment by Veruca1320** [comment]
podpisuję się pod prośbą! To jedyne czego mi brak do zaliczenia achievementu!
