### ISSUE TITLE
[EN][NAME][DK] your name has been flagged for rename

### ISSUE THREAD

**Issue by Acolito** [Atlantiss/BugTracker#2663]
https://imagizer.imageshack.us/v2/939x587q90/673/YQtcxZ.jpg

your name has been flagged for rename.

Now what?
Why?

**Comment by xmesaj2** [comment]
Curse filters. "Suka" in Polish means (sorry to say) "whore" and server probably found it in your name string. It was discussed on forums http://atlantiss.eu/community/viewtopic.php?f=76&t=688&p=3709&hilit=rename#p3709 and I don't think it should really go in BugTracker

**Comment by Wojowniczka** [comment]
delete this "issue" coz it isn't one :P

**Comment by Jenovas** [comment]
Please write a message to our support. Thx
