### ISSUE TITLE
[EN][Quest][Dun Morogh] Whitebeard Needs Ye

### ISSUE THREAD

**Issue by Justscott** [Atlantiss/BugTracker#2667]
Upon completing the prerequisite quest All the Other Stuff (http://www.wowhead.com/quest=24475/all-the-other-stuff) the next quest Whitebeard Needs Ye (http://www.wowhead.com/quest=24487/whitebeard-needs-ye) is not available.

None of the other quests later in the quest chain are available either, essentially preventing further questing and leveling in this zone.

**Comment by maslak** [comment]
https://github.com/Atlantiss/BugTracker/issues/2655
