### ISSUE TITLE
[ENG][NPC][Shattrath City] The Scryers missing 26 NPCs

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2670]
Aelthin http://www.wowhead.com/npc=33630/aelthin
Botanist Alaenra http://www.wowhead.com/npc=33639/botanist-alaenra
Auctioneer Kalaren http://www.wowhead.com/npc=50139/auctioneer-kalaren
Auctioneer Lyrsara http://www.wowhead.com/npc=50140/auctioneer-lyrsara
Alchemy (book shelve that functions as a trainer) http://www.wowhead.com/npc=33608/alchemy
Blacksmithing http://www.wowhead.com/npc=33609/blacksmithing
Blood Knight Argaron http://www.wowhead.com/npc=50012/blood-knight-argaron
Cooking http://www.wowhead.com/npc=33619/cooking
Enchanting http://www.wowhead.com/npc=33610/enchanting
Engineering http://www.wowhead.com/npc=33611/engineering
First Aid http://www.wowhead.com/npc=33621/first-aid
Fishing http://www.wowhead.com/npc=33623/fishing
Herbalism http://www.wowhead.com/npc=33616/herbalism
Inscription http://www.wowhead.com/npc=33615/inscription
Jewelcrafting http://www.wowhead.com/npc=33614/jewelcrafting
Derithela http://www.wowhead.com/npc=50007/derithela
Leatherworking  http://www.wowhead.com/npc=33612/leatherworking
Tailoring http://www.wowhead.com/npc=33613/tailoring
Skinning http://www.wowhead.com/npc=33618/skinning
Mining http://www.wowhead.com/npc=33617/mining
Summoner Durael http://www.wowhead.com/npc=50017/summoner-durael
Tarlhir http://www.wowhead.com/npc=50018/tarlhir
Matron Ismara http://www.wowhead.com/npc=50013/matron-ismara
Pathstalker Arpalir http://www.wowhead.com/npc=50016/pathstalker-arpalir
Loremaster Skosiris http://www.wowhead.com/npc=33642/loremaster-skosiris
Magister Falris http://www.wowhead.com/npc=19485/magister-falris

**Comment by Quban** [comment]
fix soon

**Comment by ShockRW** [comment]
There is also missing auctioneer in The Aldor bank – Auctioneer Braku
http://www.wowhead.com/npc=50145/auctioneer-braku

**Comment by Technowizard15** [comment]
I bet there will be more missing. Had a  corresponding list for the Aldor planned but lacked the motivation to make one till now cause this one took  me almost one hour to write down.
