### ISSUE TITLE
[EN] [Quest] Feathers for Grazle

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#2673]
This quest should be repeatable
http://www.wowhead.com/quest=28396/feathers-for-grazle

**Comment by Quban** [comment]
fix soon

**Comment by danlapps** [comment]
try
```SQL
UPDATE  `quest_template` SET `flags`=8448 WHERE `id`=28396;
```

**Comment by Quban** [comment]
you forgot to set SpecialFlags=1 :D

**Comment by danlapps** [comment]
nah you just misread :P

**Comment by Quban** [comment]
actually this one http://www.wowhead.com/quest=28395/feathers-for-nafien is broken
http://www.wowhead.com/quest=28396/feathers-for-grazle is not even there

**Comment by danlapps** [comment]
lol

**Comment by xolon** [comment]
Grazle is in emerald sanctuary south felwood
http://i.imgur.com/RuKy9BW.jpg

**Comment by Quban** [comment]
I know where grazle is, just saying that i cant get this q on my horde druid, did 4q chain and nothing

**Comment by xolon** [comment]
I didn't do any of those 2 quest today before the restart, but after it couldn't get any of those 2.
i'll try it tomorrow if they aren't there i'm gonna make new report

**Comment by Quban** [comment]
yes, something went wrong im looking into it
