### ISSUE TITLE
[EN] [Achievement] Arathi Basin battleground

### ISSUE THREAD

**Issue by Swepy** [Atlantiss/BugTracker#2674]
Hi!

In the Arathi Basin battleground the achievement called "we had it all along *cough*" is not working or
at least not how its suppose to in Cataclysm. In Wotlk to get the achi you must win Arathi Basin with only 10 points difference, but it was changed in Cataclysm to 50.

http://www.wowhead.com/achievement=162/we-had-it-all-along-cough#criteria-of

So the problem is, in the last AB we won with 40 points difference, but still nobody got the achievement which is strange, because i remember once when the hordes won with 10 points difference it gave them the achi. So i think it wasnt changed to 50 or the achievement is bugged
only for the alliance :D

<a href="http://tinypic.com?ref=2rqc668" target="_blank"><img src="http://i59.tinypic.com/2rqc668.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Swepy** [comment]
Now its 100% that it wasnt changed from wotlk. We just won an AB with 10 points difference and every1 got the achi.

**Comment by Wolffenstein** [comment]
Fixed in rev 4375.
