### ISSUE TITLE
[EN][Spell][Pet][Warlock] Firebolt

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#268]
Firebolt crits for 150% normal damage instead 200%
http://www.worldoflogs.com/reports/rt-4xsuev06pq24wxeo/xe/?s=6572&e=7004&x=spell+%3D+%22Firebolt%22 // WoL proof

This abbility is scaling with warlock's melee ratings - not sure if this is a bug, but this is kinda strange for me. Deals 20% more damage than normal tooltip and Drdamage's tooltip

http://cata.openwow.com/spell=3110#see-also-ability // Firebolt

**Comment by fafal** [comment]
Still crit value is to low.
Additional to imp: in melee range he use melee attack instead of firebolt - dat happens only when imp is without mana, not because "yes" ;c

**Comment by Bildo** [comment]
fixed in rev 4240
