### ISSUE TITLE
[EN][Core]Equipment Manager.

### ISSUE THREAD

**Issue by Clarkiez96** [Atlantiss/BugTracker#2682]
When you make an armour set in the equipment manger feature in the Character tab after relogging that Equipment Set is gone.

http://www.wowwiki.com/Equipment_Manager

**Comment by Tj20** [comment]
duplicate: #1005

I would advise to use an addon for that like *Outfitter* for the time being.

**Comment by Clarkiez96** [comment]
Oh ye, don't search for Polish tickets due to not being able to read it. Thanks for the add on ^.^
