### ISSUE TITLE
[PL][RAID][WotLK] Ulduar Demolisher

### ISSUE THREAD

**Issue by EndTime** [Atlantiss/BugTracker#2686]
Po prawidłowym odpaleniu Ulduaru, kiedy rozmawiamy z Brann'em Bronzebeard'em, że jesteśmy gotowi i ten wzywa nas, do zajęcia miejsc w pojazdach, Demolisher nie jest możliwy do ztargetowania. Nie ma możliwości wejścia do niego. Motor i Siege działają poprawnie, ale bez Demolishera, zabicie Levka jest niemożliwe. 

http://scr.hu/5gsj/6o37a  Screen z Demolisher'em
http://scr.hu/5gsj/aa88a   Screen ze stargetowanych Siege'em

**Comment by ShockRW** [comment]
Leviathan również jest zbugowany, tak jak cała faza po wyczyszczeniu trashy i dojechania pod brame.

**Comment by Aviannaqt** [comment]
Fixed in rev. 4671

**Comment by Erthar** [comment]
Dlaczego piszecie, że fixed skoro nie jest fixed ? Otwórzcie to od nowa.
