### ISSUE TITLE
[EN][Spell][Hunter] Kill Shot

### ISSUE THREAD

**Issue by sshad00w** [Atlantiss/BugTracker#2688]
Kill Shot:
100% weapon dmg + 45% RAP + 543) * 150%

http://www.wowhead.com/spell=53351/kill-shot#changelog
4.3.0 (Tue Nov 29 2011) Build 14732

TEST-IN-GAME RESULT:
[Shadoow]: Recount - Shadoow's Hostile Attacks: Kill Shot
[Shadoow]: 1. Hit 8 (67%) (Min: 10380 Avg: 10713 Max: 11090)
[Shadoow]: 2. Crit 4 (33%) (Min: 21358 Avg: 22173 Max: 22983)

TARGET:
Raiders Training Dummy lvl 84 (I choose this target becouse i cant test on something whose have less then 20% HP)

------

Shadoow Hunter Survival (without buffs, trinkets, etc...):
1688-2533 - Weapon DMG [Av. 2110,5]
4869-5714 - Ranged Damage [Av. 5291,5]
14851 - 100% RAP
6682,95 - 45%

(2110,5 + 6682,95 + 543) * 150 % = 14004,675
[9336,45] * 150% = 14004,675

Diff:
14004,675 - 10713 = 3291,675

**Comment by Kejmil** [comment]
armor...

**Comment by Varchord** [comment]
Redukcja dmg na kukłach to ~33%
14004,675*0.67=9383,13225

**Comment by sshad00w** [comment]
aa sorka przepraszam mój błąd. W innych spellach uwzględniłem bo już dostałem "zjebke" że nie uwzględniam armora. "Raiders Training Dummy lvl 84" ile ma? Bo na "???" nie jestem w stanie sprawdzić kill shot-a. Jeżeli byłoby 33% to mniej więcej się zgadza.
