### ISSUE TITLE
[EN][Spell][Pets of Hunter] Abilities of pets - [nerf dmg comming]

### ISSUE THREAD

**Issue by sshad00w** [Atlantiss/BugTracker#2689]
OK at now confirmed:
https://www.youtube.com/watch?v=9sED1CXYcy8
its my video from 4.0.6 - coefs of pets IS DONT CHANGED. Look dmg done by pets on orange scrolls text durning combat on Training Dummy. its about 1100-1400 on blizzard server, on Atlantiss.eu is more then 2k - about (Min: 2522 Avg: 2613 Max: 2792), and crits - Crit 8 (30%) (Min: 5044 Avg: 5280 Max: 5486).
In my video we can see dmg from normal hits about 1.1k - 1.4k and crits more then 2.4-2.8k

I tested all pets with THATS SAME ITEMS ON BLIZZ SERVER. (354 ilvl), and thats same eq.
Pls nerfs all pets, at this moment hunters of pets hit about 30-40% more dmg.. In my opinion is very important.

Pet:
Melee Base Dmg: 73-110 - tested 12/27
Bite/Claw/Smack: 19.52% Pet AP + 164 - tested 12/27
Thunderstomp: 7% Pet AP + 170
Wolverine Bite: 10% Pet AP + 1 - tested 12/27
42.5% of hunter AP
100% of hunter hit as both hit and expertise (so if you are hit capped, your pet is hit and exp capped)
100% of hunter haste
100% of hunter crit

Tested on Heroic Traning Dummy (???) with pet without buffs some like BOM, BOK, etc...

Shadoow Survival Hunter:
RAP 100% - 14851
RAP 42.5% - 6311,675
AP 100% - 615
AP 42.5% - 261,375

CRIT Pet:
AP 100% - 6807
AP 19.52% - 1328,7264

[center]-----------[/center]

Bite/Claw/Smack:
19.52% Pet AP + 164

1328,7264 + 164 = 1492,7264

IN-GAME:
[Shadoow]: Recount - CRIT <Shadoow>'s Hostile Attacks: Bite
[Shadoow]: 1. Hit 19 (70%) (Min: 2522 Avg: 2613 Max: 2792)
[Shadoow]: 2. Crit 8 (30%) (Min: 5044 Avg: 5280 Max: 5486)

Diff:
2613 - 1492,7264 = [b]1120,2736[/b]

[center]-----------[/center]

Thunderstomp: 7% Pet AP + 170

TANK pet:
AP 100% - 6807
AP 7% - 476,49

476,49 + 170 =[b] 646,49[/b]

N-GAME:
[Shadoow]: Recount - TANK <Shadoow>'s Hostile Attacks: Thunderstomp
[Shadoow]: 1. Hit 8 (80%) (Min: 213 Avg: 214 Max: 216)
[Shadoow]: 2. Crit 1 (10%) (Min: 324 Avg: 324 Max: 324)
[Shadoow]: 3. Miss 1 (10%) ( Avg: 0)

Diff:
214 - 646,49 = [b]-432,49[/b]

PS: My opinion spells like a Bite/Claw/Smack at this moment is really OP, Thunderstomp is less dmg. Remember additionally pets on Atlantiss.eu may received buffs from others ppls.

**Comment by Jenovas** [comment]
I already told you Bite/Claw/Smack DMG is not and never was 20% Pet AP + 164

**Comment by sshad00w** [comment]
Yeahh, i remember your post from forum. But i check aboves coeffs from my first post in this issue, and all looking thats same on Atlantiss and Blizzard Server.
If u wish i can tested again if you share there Atlantiss.eu coefs.

**Comment by Jenovas** [comment]
Should be fixed in rev 4361. Please test it and tell me if DMG is ok.

**Comment by sshad00w** [comment]
Thanks Jenova:) I hope so it works really nice:) I give there result after a compilation.
