### ISSUE TITLE
Therazane reputation

### ISSUE THREAD

**Issue by Chrones** [Atlantiss/BugTracker#2690]
I was doing quests at Deebholm and suddently my Therazane reputation dropped from honored to friendly - Now i cannot return my quests even that they are completed and i suppose to be able to even talk to Earthmother. This happened 18.3.2015 around 10:50 - 11:20 AM server time

Anyone else got same issues - I haven't got contact from GM's about it yet

**Comment by jurek1** [comment]
turn off  "at war" option in reputation

**Comment by Chrones** [comment]
That helped alot - Forgot that there was even that option - Thank you alot.
