### ISSUE TITLE
[EN][Item] Reins of the Golden King

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2691]
http://www.wowhead.com/item=62298/reins-of-the-golden-king

When mailing this Bind on Account mount from Alliance to your Horde alt, it stays the same and cannot be learned by horde character.

Wowhead comment: "Previous to 4.1, if you mail this to a Horde alt, they get it as a lion but can't use it. In Patch 4.1, mailing this to a Horde alt converts it to a  Reins of the Kor'kron Annihilator and they can use it, regardless of guild rep."

**Comment by DataMemoryStick** [comment]
BUMP'ing this.

Just tried it and got sad mount, didn't change.

Anything on this?

**Comment by tomatosz** [comment]
Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14502-mailing-guild-mount-cross-faction/
