### ISSUE TITLE
[EN][Core][Battlegrounds] Player names appear as "Unknown"

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#2692]
Sometimes when I enter a battleground some players' names show as "Unknown". Also that happens when I summon my pet sometimes. When it happens in a BG the scoreboard doesn't show anything.

http://postimg.org/image/l7be1bn67/

**Comment by Swepy** [comment]
i think it has to do something with tol barad, because usualy i see this bug only there.
