### ISSUE TITLE
[PL][Death Knight] pet z unholy

### ISSUE THREAD

**Issue by Mietla122** [Atlantiss/BugTracker#2694]
bug nadal wystepuje, nadal można miec w blood/frost peta z unholy 
http://imgur.com/HTJQziu

**Comment by sshad00w** [comment]
Sorka za spam, ale cieszy widok uczciwych graczy którzy zgłaszają bugi na korzyść danej klasy.
Oby tak dalej.

**Comment by Jenovas** [comment]
Normalnie miałeś peta w UH, zmieniłeś spec i nie znikł?

**Comment by Mietla122** [comment]
nie poprostu byl crash spowodowany przez gracza a następnie po zalogowaniu mialem peta z drugiego speca

**Comment by Quban** [comment]
nie crash serwera a error gry na omnotronie, spowodowany gripem nefariana

**Comment by Mietla122** [comment]
poprawka: teraz wystarczy zwykly relog i mozna miec peta

**Comment by Jenovas** [comment]
Jak? Proszę opisać jak to zrobić.
Przykład:
1. Wchodze w unholy
2. Wchodze w frost
3. Logut
4. Mam peta

**Comment by sunshineinabox** [comment]
This issue is still present a DK was reporting it in world chat.
