### ISSUE TITLE
[ENG][NPC][Shattrath City] List of buggy Aldor 

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2695]
Missing:
Bratu http://www.wowhead.com/npc=50025/bratu
Irva http://www.wowhead.com/npc=50020/irva
Ordo http://www.wowhead.com/npc=50023/ordo
Salha http://www.wowhead.com/npc=50024/salha
Auctioneer Braku http://www.wowhead.com/npc=50145/auctioneer-braku
Auctioneer Itoran http://www.wowhead.com/npc=50143/auctioneer-itoran
Darahu http://www.wowhead.com/npc=50019/darahu
Raluhi http://www.wowhead.com/npc=50021/raluhi

Wrong models:
Anchorite Nindumen http://www.wowhead.com/npc=19378/anchorite-nindumen#sounds
Neophyte Nemarn http://www.wowhead.com/npc=19377/neophyte-nemarn
2 Aldor Neophyte http://www.wowhead.com/npc=19153/aldor-neophyte looking like Bloodelves at (31,33) and (31,34).

**Comment by Quban** [comment]
fix soon

**Comment by ShockRW** [comment]
We cannot use the auctioneers that you added in the last fix.
