### ISSUE TITLE
[EN][QUEST][BLADES EDGE] Stasis Chambers of Bash'ir

### ISSUE THREAD

**Issue by Cebarus** [Atlantiss/BugTracker#2696]
http://www.wowhead.com/quest=10974/stasis-chambers-of-bashir

You are supposed to use the quest item to open the bubble, and out comes a boss that you must kill.

You can open the bubble, but no boss spawns and quest is not completable.

I need this for my Xmog set and did a 38 quest chain to get here, please fix :P

**Comment by Cebarus** [comment]
So is this fixed and will be implemented on 25th? I don't understand

Thanks

**Comment by Navedonar** [comment]
no

**Comment by ShockRW** [comment]
BUMP!

**Comment by Beatit** [comment]
bump

**Comment by aranguard** [comment]
Bump.This quest and The Stones of Vekh'nir quest (also its in bugtracker) in blade edge mountain to obstruck all Loremaster achieve for outland.Only Blade edge mountanin left at 84/86.

**Comment by Illusionist87** [comment]
Bumping, still not working.

**Comment by Rinniel** [comment]
Bump. Still bugged. Please fix this, it's very annoying to find this not working after doing a quest chain and farming an instance for rep+keys. I really wanted that set for transmog.

**Comment by eryczek1615** [comment]
BUMP!

**Comment by Bildo** [comment]
fixed
