### ISSUE TITLE
[EN][Quest]Slowing the Inevitable

### ISSUE THREAD

**Issue by MonkeyBoygoku** [Atlantiss/BugTracker#2697]
http://www.wowhead.com/quest=24920/slowing-the-inevitable
You're suppose to get a skill upon mounting the bat, the kill never shows up, there for you cant finish the quest like. I am stuck where I am at cause of this.

**Comment by Varchord** [comment]
It's quest cata, not classic. I suggest writing a ticket

**Comment by Varchord** [comment]
And this quest was working for me. Completed Gilneas chain today

**Comment by MonkeyBoygoku** [comment]
Ya, Im sorry It worked, its just wouldnt work for me cause of the addon I
was using. Im sorry again.

**Comment by Varchord** [comment]
Close It then :P
