### ISSUE TITLE
[EN][TALENT][HUNTER] Entrapment

### ISSUE THREAD

**Issue by sshad00w** [Atlantiss/BugTracker#2699]
http://www.wowhead.com/spell=19387/entrapment

Hello, i would like thanks for Keyone01 (Kejmil??) for information me via PM on forum about bugs.

On first : 
- If we throw Ice trap on ground and someone activated that, and we click for other player whose stay far far away (100, 200,300 y) he received instantly 'preventing them from moving for 4 sec.' - its really nice shit.
-  Snake Trap thats same but situation in this fact is a better for all hunters. When someone activated Snake Trap the 'preventing them from moving for 4 sec.' received player who activated trap, and if we target a player whose stay far away from Snake Trap (100,200,300y...) he received 'preventing them from moving for 4 sec.' too - nice situation for preventing both players to the ground for 4 sec.
- If we use a Snake Trap, and us target is a Friendly Target we may received someone error with a "Invalid Target" but we have a bonus from preventing in this place.

INFORMATION for Keyone01 : 
'No, damage does not break the effect. It's not a magic effect, nor are the affected targets considered frozen. Nothing dispels it other than abilities that remove movement impairing effects (invulnerability like Paladin bubble removes it). Consider it as a trap with AoE improved Hamstring. _edit_ NVM,click on Apply Aura: Entrapment and it's a Magic class debuff.'

**Comment by Kejmil** [comment]
still bugged, huntards still (un)happy

**Comment by Wolffenstein** [comment]
Napisz to po polsku bo nie rozumiem ani słowa...

**Comment by Kejmil** [comment]
Efekt entrapment w przypadku ice trapa nie zalacza sie w miejscu w ktorym on lezy, ale wokol targetu huntera, nawet jesli jest on kilometr od trapa (dostajesz unmove posrodku wsg od goscia ktory polozyl trapa na respie bo akurat mial na tobie target, do tego respektuje (?) toto los w stosunku do huntera). Jesli hunter nie ma celu to wcale go nie ma, jak ma friendly to jakis error wyskakuje).
Snake trap triggeruje i w miejscu w ktorym lezy (ok) i na targecie huntera (nie ok).

Reszta to komentarz do tego co napisalem shadowowi na pw - entrapment jako magic effect przechodzil przez AMS dk a nie powinien, nie wiem jak jest teraz.

**Comment by erathor123** [comment]
Still bugged.
If you throw a root trap besides you and somebody walks in and you have a target far away, this target gets rooted as well which shouldnt be.
Also if your target gets the root trap it automatically triggers a DR and the root duration is only 2 secs.
Please fix that as it is a major incident for hunters.

**Comment by Piklo** [comment]
should be fixed in [rev5758](https://atlantiss.eu/changelog#rev5758)
