### ISSUE TITLE
[NPC][Dungeon Cata][Throne of the Tides]Erunak Stonespeaker

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#2701]
That NPC http://www.wowhead.com/npc=40825/erunak-stonespeaker is used by that octopus boss, but when that npc http://www.wowhead.com/npc=40788/mindbender-ghursha leave him, Erunak still have aggro and combat on tank after Mindbender leave him. It happened every time to get that aggro+combat on me (as tank) after i defeat boss, http://www.wowhead.com/npc=40788/mindbender-ghursha.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1156

**Comment by Quban** [comment]
Fixed in rev. 4455
