### ISSUE TITLE
[PL][Achievement] I hate that song

### ISSUE THREAD

**Issue by sherinkal** [Atlantiss/BugTracker#2704]
Mam problem ze zrobieniem achievu [I hate that song] ( http://www.wowhead.com/achievement=5293/i-hate-that-song#submit-your-data ) na Halls of Origination. Wszystko zostało wykonane poprawnie jak w opisie, addon również potwierdził prawidłowe wykonanie achievementu, aczkolwiek nie zalicza mi go. Wykonałam 3 próby zrobienia tego achievu i to tylko w tym tygodniu.
Przy ostatniej próbie, dzisiejszej (19.03.2015 r.) ja i inny dps nie ruszaliśmy się spod przekładni, aby mieć pewność, że achi będzie wykonany prawidłowo.

Dodaję screen zaliczonego achievementy wg addonu oraz brak otrzymania go. Sytuacja powtarza się już 3 raz, nikomu z moich znajomych którzy nie mają jeszcze wykonanego tego achi- nie udało się go zaliczyć.

Załączony screen: 
http://imageshack.com/a/img661/8455/R2ThzO.jpg

Pozdrawiam.

**Comment by Pietras11** [comment]
Potwierdzam to co zostało powyżej napisane. Jest to frustrujące, ponieważ w danej chwili przez ten bug nie da się ukończyć 'Glory of the Cataclysm Hero'.

**Comment by meowmewo** [comment]
I dont understand polish but i think i understand what happened. We too had to make it 3 times untill we got the achivement. First two times we did it fast enough, Achivement addon said we did..we killed the boss but we didnt get any achivement. On the 3rd time we tried it, we did,
