### ISSUE TITLE
[PL][Raid cata BWD] Chimaeron

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2705]
Chimaeron praktycznie nie stwarza się po waipie w tym samym miejscu za każdym razem jak  dedniemy i zostawimy go w jakieś inej pozycji zostanie tam nawet na wejściu do bosa.

Jak w ogóle postawisz peta przy chimaeron to praktycznie pet znika pod tekstury to jest upierdliwe kiedy jest bitwa postawisz peta żeby go atakował a nagle paczysz a pet zniknął ci z pola widzenia
musiałem z kilka razy ćwiczyć stawianie peta na tym bosie.

**Comment by Varchord** [comment]
Składniowo to jest okropnie napisane -.-
Nie jest to problem bossa tylko wody. Każdy pet na serwerze boi się wchodzić i podchodzić do wody

**Comment by Kejmil** [comment]
pewnie z kotem biegales :D

**Comment by Wojowniczka** [comment]
Kejmil xD ale tego kota można przeprogramować przynajmniej bo żywe to tak nie bardzo ^^ i fakt to dla huntów jest uciążliwe jak pet patrzy praktycznie 60-80% walki na bossa i nic nie robi tylko mruczy w przypadku kota :D

**Comment by Varchord** [comment]
Bossa da się tankować tak, żeby go pety mogły bić. I wcale to nie jest trudne.

Proponuje wywalić tą część o petach ze zgłoszenia, stworzyć osobny issue dla niego i nie oczekiwać szybkiego fixa.

Więc zostaje kwestia robota który się nie rusza. To już jest chyba problem NPC konkretnego, a nie całego encountera.
Ogólnie to według mnie zgłoszenie jest do zamknięcia i rozbicia na 2 osobne :P

**Comment by Wojowniczka** [comment]
to ma być blizzlike server więc odpada to co napisałeś "Bossa da się tankować tak, żeby go pety mogły bić. I wcale to nie jest trudne." mimo iż faktycznie nie jest to trudne :P a co do robota to minor issue ale było by "ciekawiej" gdyby jednak blaszak się ruszał :)

**Comment by Alandiel** [comment]
Można też ustawić peta w miejscu, z którego będzie mógł normalnie bić komendą Move To.

**Comment by arekczup** [comment]
dobra wywale to

**Comment by Varchord** [comment]
Ja nie mówię, że to może tak zostać tylko żeby to rozbić na 2 zgłoszenia

**Comment by arekczup** [comment]
ok

**Comment by arekczup** [comment]
![image](https://cloud.githubusercontent.com/assets/8699987/7572052/eee3c70c-f81b-11e4-8b13-c621dd7d39ca.png)
chimeron zniknoł na hero i normalu plusem jest to ze textury sie naprawiły bo pet mi nie znika tam gdzie był chimeron i początkowa platforma bo juz mi nie znikają kumple jak ich widze na platformie.
