### ISSUE TITLE
[EN][Quest][Mount Hyjal] Black Heart of Flame

### ISSUE THREAD

**Issue by psykotic619** [Atlantiss/BugTracker#2707]
when you click on the quest item it says that your in the wrong zone even though im in the right zone.

![wowscrnshot_031915_221045](https://cloud.githubusercontent.com/assets/11563188/6742146/470c3a24-ce85-11e4-9e85-e9c5cbd20510.jpg)
![wowscrnshot_031915_221120](https://cloud.githubusercontent.com/assets/11563188/6742156/59c13cbe-ce85-11e4-9dc6-04f693a5a3ec.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/577
