### ISSUE TITLE
[ENG] A Curse We Cannot Lift

### ISSUE THREAD

**Issue by Wrathion** [Atlantiss/BugTracker#2708]
The quest is in the revamped area of Duskwood. 

I tried doing this quest multiple times to no avail. The Worgen target cannot be tranquilized as per the quest's requirement. 

Even after dropping him below 20% HP, he's still not reacting to the quest item usage.

Tried retaking it or using on dead body, still no completion. GM couldn't find a way either.

http://www.wowhead.com/quest=26720/a-curse-we-cannot-lift
http://www.wowhead.com/item=60206/harriss-ampule

**Comment by Swepy** [comment]
try when he have only like 1% hp left, i did this a few weeks ago and it worked for me

**Comment by Kejmil** [comment]
He has to be 10%- hp, then it works.
Nevertheless, it is still bug - he should be able to transquilized with more hp or info about it should be little later

**Comment by Quban** [comment]
Actually he has to be below 20%, you should see that "Worgen hesitates and stares" than use item, npc script is actually working, item is broken, but you can get kill credit for this i you use it properly.
I'll fix item soon, (it should have more than 1 use)
