### ISSUE TITLE
[PL] [Priest] Shadow Apperation

### ISSUE THREAD

**Issue by Malylolek** [Atlantiss/BugTracker#2709]
http://www.wowhead.com/spell=78203/shadowy-apparitions 
http://www.wowhead.com/spell=15473/shadowform 
http://wow.gamepedia.com/Shadow_Power ID: 87327

Nie dostają bonusu 15% ze specjalizacji i shadow formy ewentualnie gdzieś coeffy są zjebane

**Comment by Dziara** [comment]
Niestety bzdury.
Obliczenia przy SP=4766: (516.19+4766*0.515)*1.15*1.15*1.3*1.06*1.02(kolejno: spec, shadowform, t11 4pt,taleny twin disciplines i twisted faith) = 5522
DMG zadany w grze = 5509

**Comment by Kejmil** [comment]
jakby ktos jeszcze chcial zglosic ze apparitiony powinny critowac za 200%, to niestety jest tylko 150% i tak tez u nas dziala

https://www.youtube.com/watch?v=3CMjXeqaFx8&t=134 do 2:40

simcraft nie jest nieomylny :/

**Comment by Jenovas** [comment]
Czyli powinno critać za 150% i dobrze u Nas to działa?

**Comment by Dziara** [comment]
Aktualnie na Atlantissie apparitiony mają dobry crit modifier (x1.5). 
Ale IDP za to wciąż leży zgłoszone ;_;
