### ISSUE TITLE
[PL][Hunter] Pet no like water 

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2710]
jak mam  peta kota  lub wilka to jak chce atakować npc na wodzie to Musze mieć pająka bo praktycznie nie umią pływać. Na  otwartym morzu to na dno idzie i sobie siedzi .

**Comment by Asavel** [comment]
To normalne że koty nie lubią wody z psami tak samo mój pies też jej nie lubi.

**Comment by Tj20** [comment]
Not sure if I understand this correctly via Google translate, but the issue might be related to #1059 (mobs, pets etc. don't like to enter/exit water).
