### ISSUE TITLE
[EN][Elwynn Forest][Quest] Pie for Billy

### ISSUE THREAD

**Issue by MadeeV** [Atlantiss/BugTracker#2711]
Hi, at this quest you need to get 4 Tender Boar Meat whose you can drop from Rockhide Boar, as you can see here -> http://www.wowhead.com/quest=86/pie-for-billy but i killed few these Boars, but did not get anything..:( And BTW, again this quest has got bad string, it shows string that could shows when quest is completed, but it shows when it is not completed.. I already make a thread about this, because as I am doing quest, it looks, like every quest in Elwynn Forest has got these bugged strings..
![wowscrnshot_032015_162606](https://cloud.githubusercontent.com/assets/11557553/6754591/d66b58f6-cf1d-11e4-8502-bba75d2d6aa4.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2702

**Comment by MadeeV** [comment]
No.. I was speaking about no drops from boars.. I only said some sentences about that completed string bug again..

**Comment by user1011** [comment]
Works fine..
