### ISSUE TITLE
Quest-The Lost Isles-Warchief's Revenge

### ISSUE THREAD

**Issue by JairukoTV** [Atlantiss/BugTracker#2712]
Hi! :D

So I was questing on The Lost Isles while I figured that there was a quest that didn't work :( 
The quest http://www.wowhead.com/quest=14243/warchiefs-revenge are supposed to send you back to the Wild Overlook, after you've killed the 50 alliance pirates. But that didn't happen, sadly, I got flown back to Thrall instead, and I had to swim all over over to my destination.

**Comment by Allowas** [comment]
add wowhead links

**Comment by Navedonar** [comment]
duplicate
