### ISSUE TITLE
Cobra Shot regeneracja Focus'a Bugged

### ISSUE THREAD

**Issue by lukipol** [Atlantiss/BugTracker#2713]
Otóż sprawa wygląda tak że kiedy używamy cobra shota focus generuje nam dopiero wtedy kiedy udeży w cel, powinno być tak że dostajemy focus odrazu kiedy wyleci strzala. Licze na szybka naprawe Pozdrawiam.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
