### ISSUE TITLE
[PL][NPC] bile-o-tron-800

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2714]
robot  nie przemieszcza się w czasie bitwy tylko stoi.
  https://www.youtube.com/watch?v=4rR84Tk-Kqo
http://www.wowhead.com/npc=44418/bile-o-tron-800#abilities

**Comment by Bildo** [comment]
celowo to wylaczone jest

**Comment by Wojowniczka** [comment]
Bildo a co było nie tak gdy "był" włączony albo jeśli/gdy ktoś go testował?

**Comment by Varchord** [comment]
Zapewne wpadłby pod tekstury, zaczał latać czy coś

**Comment by Jenovas** [comment]
NPC został wyłączony, bo są problemy z MMapami w niektórych miejscach i zapadał się pod ziemię. Wipe w tym momencie oznaczał że następnego podejścia już nie będzie.

**Comment by Wojowniczka** [comment]
ok @Jenovas dziękuję za wyjaśnienie :)
