### ISSUE TITLE
[EN][Profession] Enchant Weapon - Hurricane

### ISSUE THREAD

**Issue by Dracona** [Atlantiss/BugTracker#2715]
Testing of Enchant Weapon- Hurricane procs indicates that this buff does not interact well with DoT or HoT spells; it simply increases their duration to get extra ticks, as opposed to reducing the duration whilst keeping the same number of ticks, until getting to the haste point where the duration would stay the same and increase the number of ticks by one.

This caused longer-duration DoT spells during my testing, and acts differently to haste gained through equipped items.

**Comment by Jenovas** [comment]
This isnt a bug related to Enchant, it's a bug related to haste and DoT/HoT mechanic that you already wrote about. Closing.
