### ISSUE TITLE
[EN][Spell- Generic] Haste not working properly for DoTs.

### ISSUE THREAD

**Issue by Dracona** [Atlantiss/BugTracker#2716]
In Cataclysm, DoTs are supposed to interact with haste in that the duration is reduced for the same number of ticks, until a haste point is reached where an extra tick is generated during the original DoT duration (source: http://forums.elitistjerks.com/topic/123258-shadow-priest-pve-guide-43-updated/). The DPS should scale smoothly with haste, and have minimal impact from extra tick breakpoints.

As tested on druid and shadow priest DoT spells, the duration of the DoT spell on the tooltip is updated when haste is gained, but regardless of the haste value, the duration of the debuff on the target is always the original length, meaning that extra haste is worthless to DoT-heavy classes other than at the breakpoints for extra ticks. The DPS does NOT scale smoothly with haste at all, and only counts for the extra tick breakpoints.

**Comment by kadi2** [comment]
Where exactly is the bug regardless visual bug with tooltip?

**Comment by Dracona** [comment]
I cast a Devouring plague that should last for 23.75s, due to haste. The applied debuff lasts for 25s. I then cast a devouring plague that should last 24.64s, due to changing haste, and the applied debuff still lasts for 25s (unless hurricane proc is active, which lengthens the duration and doesn't change the DPS, just lets you get in extra ticks due to lengthening the DoT length, but that's a different bug that just complicates testing slightly). The duration should be reduced by haste for the same number of ticks, before the breakpoint for an extra tick is reached, but the duration is not reduced.

**Comment by iskk** [comment]
You should read more about dots in cataclysm.
Read this: https://cynwise.wordpress.com/2010/10/29/how-warlock-dots-work-in-cataclysm/ 
YEAH i know its for warlock but hey dot is dot.

Dot duration is constant unless you refresh dot before tick - then time from refresh to tick is added to new dot time. So whats bugged here?

**Comment by Dracona** [comment]
Going by http://forums.elitistjerks.com/topic/123258-shadow-priest-pve-guide-43-updated/, it states that DoTs have their duration reduced:
"Haste has become a far more interesting and advanced stat than it had once been prior to 4.0. It was redesigned to benefit damage- and healing-over-time spells by allowing them to tick faster and thus reducing the overall duration of those spells. This is important because with enough haste your DoTs will tick with enough frequency to allow for additional ticks to occur.

A very interesting thing happens when you reach one of these extra tick points: the duration of your damage- or healing-over-time spells increases from its hastened duration back to its natural duration. This is important to note because while the ticks are still ticking at roughly the same frequency as they were prior to hitting one of these points, and thus doing roughly the same DPS, they are now doing it for a slightly longer time. That extra time allows for you to insert other damage-dealing abilites such as Mind Flay (which aside from being our nuke is also behaves as a DoT benefiting from haste). "

Clearly states that haste plateaus for DoTs are only of importance for getting extra free GCDs, and that the DPS of the spell itself is smooth wrt haste, disagreeing entirley with your link. Unfortunately, the link from EJ as to why 4.3.4 haste plateaus don't exist has vanished into the aether.

**Comment by iskk** [comment]
You do realise it isnt wotlk? Here we have haste for more tick with constant dot time?

Correct me if im wrong but im trying to get your point.

You thing haste in cata works like that:
more haste = more ticks + shorter duration?

**Comment by Dracona** [comment]
Iskk, that's what the Elitistjerks 4.3.4 SPriest thread clearly states, with comments like:

"Reaching haste breakpoint reset its duration to bigger value - so you need recast it less.
Its not very big dps increase.
Last time I checked it was something like ~100-150 in BiS gear. "

or my quotes earlier. Is Elitistjerks wrong? Was EJ wrong for the entirety of Cata?

**Comment by iskk** [comment]
SO basicaly you say that short dots = less recast?

DOTS are working FINE - like on your last quote.

EXAMPLE (i used https://docs.google.com/spreadsheet/ccc?key=0AsDL8HE-bGDVdEU1S1NqMW5IbWU1dURKcmdibFFTeVE#gid=16):
Vampiric Touch: 15sec duration, 3sec tick, 5ticks - no haste.
30%haste = 15sec duration, 2,14 sec tick, 7ticks - last tick when dot s about to expire.
So you cast first VT-15sec. You recast VT when old one has 1,5sec to end. New one has 15+1,5=16,5sec duration (new dot time + time to last tick). "Reaching haste breakpoint reset its duration to bigger value - so you need recast it less."

**Comment by Tj20** [comment]
I think Dracona is right in how DoTs should work.
[http://wow.gamepedia.com/Damage_over_Time](http://wow.gamepedia.com/Damage_over_Time)

> Between patches 4.0.1 and 6.0.1, the DoT's duration would be the sum of the number of DoT ticks that leaves the final duration closest to the original duration as possible, meaning the duration would fluctuate around the original duration by up to half the tick interval as haste values changed.

Which IMHO means for example: a 12 sec DoT (3 sec tick intervals) may be between 10.5 and 13.5 seconds long.  
Getting some haste reduces the time of the DoT slightly. When you have enough haste to reach 10.5 seconds, you gain another tick and the DoT will run for 13.5 seconds overall.  
More haste will reduce the time again until at 10.5 you get a second tick again.

That being said, I don't know if this works on Atlantiss or not, but I think Dracona will have checked that via combat log or something.

**Comment by Dracona** [comment]
So EJ is flat out wrong when it says that the DoT duration should decrease with haste, until you reach the breakpoint, at which point the duration resets back to 15s, and that the only benefit of getting to these breakpoints is the extra GCD, as opposed to a boost in the damage from extra ticks? Because as it works at the moment, that's not how it works, and the duration is always constant, regardless of haste.

**Comment by iskk** [comment]
Your point is to calculate dot timer to last dot tick. My point is that this is no different than what we have now. if you have 29%haste your VT will have  last tick on 12sec or something like that. So you can say that DOT is 12sec when on your target dot has 15sec dura long (after 12sec you wont see any dmg) but it doesn't make any difference to what we have now. Dot ticks working fine - check it.

**Comment by Dracona** [comment]
Hmm, okay, Iskk, and the haste breakpoints are negligible, serving only to increase the number of free GCDs? So the bug is only a minor one where the debuff length is longer than it should be, and refreshing between the second last tick and the end of the debuff, as shown on the target, have the same effect? Sorry for the false positive, then.

**Comment by Tj20** [comment]
I would be interested in a combat log. Maybe one with haste above and one below a certain break point where you would get another tick. I think this would clear up how DoTs work exactly here, but I don't have a DoT class.

(/combatlog in game, upload logs/WoWCombatLog.txt on [pastebin](http://pastebin.com/) for example)

**Comment by ksgm92** [comment]
I have tested it with a druid and a warlock it seems to be working as intended

**Comment by sunshineinabox** [comment]
Druids don't benefit much from haste, but it takes an INSANE amount of haste to get extra ticks.

**Comment by sunshineinabox** [comment]
So I have tested this on my warlock and haste seems to work exactly as described [here](https://cynwise.wordpress.com/2010/10/29/how-warlock-dots-work-in-cataclysm/).

This first screenshot is of testing it without gear I got 12 ticks of corruption over two casts.
![wowscrnshot_071815_091316](https://cloud.githubusercontent.com/assets/11906669/8762433/7a15b0e2-2d2d-11e5-95d5-fdf9cb4ef6b0.jpg)

In this second screenshot I got 15 ticks of corruption over 2 casts. With gear. Gear added 13% haste.
![wowscrnshot_071815_091331](https://cloud.githubusercontent.com/assets/11906669/8762434/7e4f7ee0-2d2d-11e5-84cf-952c75edbf04.jpg)

Now thats a very rough test. I didn't test any specific haste values, but haste does increase the number of ticks and also the duration stays the same. That is exactly how they are described in the blogpost that was linked here before. If someone wants to test specific haste values you can go ahead, but the behavior seems to be working fine.
