### ISSUE TITLE
RDF disconnect issue

### ISSUE THREAD

**Issue by thegunners14** [Atlantiss/BugTracker#2719]
I seem to be having an issue with RDF. Every time i enter a dungeon i get disconnected every 20-30 seconds. I will have to exit client and reopen and repeat this through the whole dungeon. It makes doing rdf practically impossible and quite a game ruining bug. I had the same issue while in the open world in the airfields in dun morogh. I am not sure what causes this to happen as everyone I ask have never had this issue. I really don't know what to do at this point.

**Comment by Aival94** [comment]
try redownloading your client.

**Comment by thegunners14** [comment]
I am running the mini-client now and I have the same issue however at a much lower frequency of disconnects. 

Date: Sat, 21 Mar 2015 15:01:31 -0700
