### ISSUE TITLE
[EN] [Dire Maul] [NPC] Hydrospawn bug

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#272]
In Dire Maul, upon engaging Hydrospawn he immediately floats upwards and stops upon reaching the next level platform that is above him, he remains being in combat with the rest of the group and comes down to attack the group only when the group heads out for a rise of stairs that lead to that upper-level platform that he is stuck on. Otherwise, when he comes down, fight carries out normally.

http://www.wowhead.com/npc=13280

**Comment by Tj20** [comment]
I've also noticed that the mob pathing is a bit iffy in Dire Maul East (Warpwood Quarter).

1. The boss Hydrospawn jumps through the ceiling when you engange him, as mentioned before

![Hydrospawn](http://i.imgur.com/y7nYFXY.jpg)

2. The trash mobs in the garden run away when you engange them first, then come back on a specific path on the border between stone path and grass, maybe also pulling other mobs in the process.

![the garden](http://i.imgur.com/n4YM0Dr.jpg)

**Comment by Bildo** [comment]
fixed in rev 4240

**Comment by Dean1989** [comment]
these things still happens
