### ISSUE TITLE
[EN][Talent][Warrior] Sweeping strikes

### ISSUE THREAD

**Issue by bgb** [Atlantiss/BugTracker#2720]
Its not proccing from Bladestorm attacks at all. And this is actually very important "trick" for pvping warriors mentioned in many pvp tips videos... Also, I found video showing bladestorm+sweeping strikes in action: https://www.youtube.com/watch?v=71nkds0PAZY

**Comment by kadi2** [comment]
This movie shows Opportunity Strikes, Bladestorm, Deep Wounds and Swiping Strikes damage. Unfortunately this movie shows that you shouldn't be able to attack with melee attacks during Bladestorm as it is on the server.

**Comment by bgb** [comment]
What do You mean "you shouldn't be able to attack with melee attacks during Bladestorm" ? If You mean white hits then, yes You should, and if sweeping strikes procs - it also should work from bladestorm. Another video, better showing this (even combat log included): https://www.youtube.com/watch?v=JuYJFug0F24

**Comment by Quban** [comment]
this is from WoD

**Comment by bgb** [comment]
He did hit, look at 27-28 sec, also mechanic of bladestorm didnt change in WoD. But You can do some research if You dont believe it. Anyway this is not the topic to discuss bladestorm+autoattack. Concentrate on sweeping strikes+bladestorm please.

**Comment by bgb** [comment]
This is also important to make it blizzlike and not overpowered (like on other private servers where it procs from every target of bladestorm): http://eu.battle.net/wow/en/forum/topic/1302975419

**Comment by Kejmil** [comment]
i just tested it and everything is working fine so...

**Comment by bgb** [comment]
Hmm, so I just rechecked this in game and, yes - it seem to work but ONLY if I have turned on autoattack on my current target (im not talking about actual autoattack swings, they doesnt matter - its just important to have autoattack on). With autoattack SS triggers from bladestorm as it should but without - it doesnt trigger at all... Well this is odd and im not sure how it is supposed to be... Well, at least I know how to use it now to make it proc...
