### ISSUE TITLE
[EN][NPC] Woodpaw Reavers

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#2721]
The Woodpaw Reavers in Feralas (http://www.wowhead.com/npc=5255/woodpaw-reaver) don't attack the player at all, even if provoked. The Woodpaw mystics in the area are however fully scripted and attack on sight.

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1641
