### ISSUE TITLE
[PL] Arcane Mage Mastery

### ISSUE THREAD

**Issue by kvokul** [Atlantiss/BugTracker#2722]
Mam problem z mastery u mojego arcane maga. O ile opis w innych postaciach i speckach się zmienia gdy zmieniam ilość mastery, o tyle w arcane zawsze jest napisane, ze mam 12% bonus dmg.

Może być to błąd wyswietlania tylko, ale nie zauważyłem żadnej różnicy w uderzeniu mojej postaci, nieważne czy miała 500 czy 1500 mastery rating. Recount oczywiście nie jest do końca wiarygodny, ale mam wrażenie, że nawet kukły wcześniej biłem mocnej. Mam też wrazenie (ale mogę się mylić), że przed patchem w charakterystykach postaci widniała tez większa ilość "bonus dmg" przy mastery. 

Nie wiem, czy problem dotyczy tylko mojej postaci, ale MG w grze po zgłoszeniu ticketem, powiedział, że mam to wrzucić z opisem na bugtackera na wszelki wypadek.

--------  Edycja ------

Podobno innym Arcane Mage działa to poprawnie, pozostawiam to jednak na bugtrackerze, ze  względu na to, że GM po obejrzeniu mojej postaci polecił mi tak zrobić.

**Comment by Kejmil** [comment]
skoro jest to odosobniony przypadek, to jest to problem z twoja postacia a nie z ogolna mechanika, niech jakis gm cie obejrzy i sprawdzi czy nie masz przypadkiem mastery usunietego czy cos
