### ISSUE TITLE
[EN][Death Knight] Death and Decay

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#2724]
Death and Decay causes pushback to those casting spells who are standing in the aoe. It should not cause spell pushbacks.

**Comment by Wolffenstein** [comment]
Any proof?

**Comment by Milton3450** [comment]
I haven't been able to find proof though searching on google for either option (pushback or not). To me  it makes sense that it shouldn't cause pushbacks because aoe on the ground in general (in raid encounters too) have never caused pushbacks either.

**Comment by Milton3450** [comment]
I have found this

http://www.wowwiki.com/Interrupt

'Whenever a damaging spell or ability hits the caster, the cast time will be set back by a given amount, slowing the casting. In general any melee attack (be it a normal or a special attack) or direct damage spell will cause interruption. Damage over Time spells and most Channelled spells will not cause interruption. The only channeled spell which does is Arcane Missiles.'

So from I can read it is melee attacks and direct spells which cause the pushback.

**Comment by Milton3450** [comment]
It might be good with some more input for this.

**Comment by Milton3450** [comment]
I found this about immolation traps.

http://eu.battle.net/wow/en/forum/topic/1549669727

"Immolation Trap/Explosive Trap: Both equally bad ability's. Doesnt really deal any damage (maybe 1k overall), isnt interrupting someting, isnt causing pushback, is useless. Why not make this ability increase casting/attack speed instead of deal damage."

So at least immolation/explosive traps don't cause pushbacks.

**Comment by Milton3450** [comment]
I found this on a thread on another forum (am I allowed to link to other servers' forums?):

"In case Molten hasn't fixed AoEs causing pushback, pick Intensity over Destructive Reach."

**Comment by Milton3450** [comment]
I just tested consecration with a pala and it doesn't cause pushbacks.

**Comment by Kejmil** [comment]
every tick of death and decay besides first should be considered like a dot, so this ticks  shoudn't cause pushbacks, canceling base captures in bgs, etc.

**Comment by Jenovas** [comment]
Fixed in rev  4413
