### ISSUE TITLE
[EN][Rogue]Restless Blades

### ISSUE THREAD

**Issue by dashnyamn** [Atlantiss/BugTracker#2726]
If you cast Slice and Dice it is not reducing coldown of killing spree,adreline rush,redirect i think it should reduce the CD of these since tooltip reads like this.
![wowscrnshot_032215_015237](https://cloud.githubusercontent.com/assets/11595923/6768849/636224f6-d036-11e4-8e1b-3f7f82231dee.jpg)

**Comment by kadi2** [comment]
It shouldn't and the tooltop states it in the word "damaging"

**Comment by dashnyamn** [comment]
hmm i didn't notice word damaging :p how do you remove posts?
