### ISSUE TITLE
[EN][Hunter][Major bug] - Wild Hunt pet talent 

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#2729]
Link - http://cata.openwow.com/spell=62762

So basically the Telent works really bad. After 20 min of testing i noticed the problem:

When ur pet has 50 or over 50 focus the talent works in 2 ways.

1.If AFTER the use of the basic ability (bite,claw,smack) the pets focus will end up under 50, the ability will cost 100% more focus but do normal damage. 
2.If AFTER the use of the basic ability (claw,bite,smack) the pets focus will be 50 or above, the ability will cost 100% more focus and do 120% more damage.

Tip.To test this just send ur pet to attack on Heroic dummy, sit and:
on 50 focus click Claw  (i get normal damage + 100% more focus cost)
on 75 focus click Claw  (i get normal damage + 100% more focus cost) 
on 90 focus click Claw  (i get normal damage + 100% more focus cost)
on 100 and 100+ focus(BM) Click Claw (i get 120% more damage + 100% more focus cost)

For me since im BM and geared my normal Claw is 4k ~.My pet will do 8+k claw only when it has 100+ focus since as i explain it will end with 50 or 50+ focus in the end. 

In my honest opinion such bug is of major priority especially now before the incomming so called "hunter pet dmg fix" that will destroy pet dmg probebly.

**Comment by Jenovas** [comment]
hunter pet dmg fix will reduce pet base DMG by probably half and will reduce scaling by probably a half also, I'll take a look into this talent.

**Comment by Jenovas** [comment]
Should be fixed in rev 4366

**Comment by meowmewo** [comment]
Will be the first one to test it. Thank u. I will tell here how it went

**Comment by meowmewo** [comment]
Working perfect.
