### ISSUE TITLE
[EN][Quest][Deepholm] Entrenched

### ISSUE THREAD

**Issue by 1cemangithub** [Atlantiss/BugTracker#2730]
The quest is to talk with "Kor the Immovable" (coordinate 34:34).
There is the yellow question sign above him but when we click him, the dialogue quest window doesn't appear.
So the quest cant be finished.

Thank you for your attention and sorry for the bad english.

BR.

**Comment by Alandiel** [comment]
Probably you're at war with Therazane.

**Comment by Quban** [comment]
Or just go closer to the npc, land and you should be able to hand in q

**Comment by Kejmil** [comment]
and you should include proper link in your issue, as stated in https://github.com/Atlantiss/BugTracker
http://www.wowhead.com/quest=26436/entrenched

**Comment by 1cemangithub** [comment]
Im sorry for the absence of link in my post. 

Alandiel was right, that im at war whith therazane eventhough my therazane reputation at neutral rank.
So i had to turn off the "At War" status at reputation tab first and then i can interract with the NPC.

Thank you all for the help.
