### ISSUE TITLE
[PL] [Glyph] [Mage] Mage armor

### ISSUE THREAD

**Issue by kvokul** [Atlantiss/BugTracker#2731]
Nie ważne, czy Mage Armor jest zgyphowane czy nie, pod postacią podawana jest wartość 3% przy wartości zwracanej many, pomimo tego, że wartość ta się zmienia w opisie skillu. Nie udało mi się zaobserwować różnicy w regeneracji many z założonym glyphem.

Wartość mana regenu podawana w okienku postaci nie zmienia się po uruchomieniu Mage Armor, ale nie wiem czy tak powinno być i czy to jest błąd i nie ma to znaczenia.

**Comment by Kejmil** [comment]
To tylko tooltip, pewnie blizzowi nie chcialo sie ustawiac wyswietlania liczb po przecinku.
Przed chwila sprawdzilem w combat logu i glyph na mage armor zwieksza regen many, proponuje dokladniej robic testy nastepnym razem.
