### ISSUE TITLE
[EN][Quest][Westfall] "The Westfall Brigade"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2733]
http://www.wowhead.com/quest=26287/the-westfall-brigade

The attacking level 12 gnolls have a low respawn rate and a gnoll gets slaughtered in 2 seconds by a couple of level 24 alliance guards, making the completion of the quest on Sentinel Hill really difficult.

**Comment by Kejmil** [comment]
on retail, guards do almost nothing to this mobs
until it is fixed - you can find some of this mobs on southwest of the sentinel hill

**Comment by Tj20** [comment]
Thanks for the reply. Btw, wouldn't this be more a "Classic" than a "Cata" quest?

**Comment by Kejmil** [comment]
"added in 4.0.3" so it was revamped on cataclysm

**Comment by Tj20** [comment]
Oooh... I see.

**Comment by Bildo** [comment]
fixed
