### ISSUE TITLE
[PL][Quest][Shadowmoon Valley] The Deadliest Trap Ever Laid

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#2734]
Witam!
Chciałbym zgłosić niedziałający quest The Deadliest Trap Ever Laid (www.wowhead.com/quest=11097/the-deadliest-trap-ever-laid). NIe działają dwie rzeczy:
1. Nie pojawiają się przeciwnicy do pokonania, przez co nie można wykonać zadania.
2. NPC o nazwie Commander Hobb (http://www.wowhead.com/npc=23434/commander-hobb) jest, a w zasadzie go nie ma. Chodzi tutaj o to, że jest, bo można wziąść od niego questa, ale go nie widać (brak grafiki NPC-a).

SS: http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_032215_223233_zpsxpxdolzh.jpg

**Comment by dinosaldo** [comment]
Nadal quest nie działa

**Comment by Aival94** [comment]
How is should work: [The Deadliest Trap Ever Laid](https://www.youtube.com/watch?v=M_ygYydXyuk)

**Comment by Bildo** [comment]
fixed
