### ISSUE TITLE
[EN][Instance][Stockade] No random dungeon bonus for Hogger

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#2736]
After beating last boss, Hogger in Stockades we receive achievement but no bonus for dungeon finder random group run.

http://www.wowhead.com/npc=46254

**Comment by xolon** [comment]
i can confirm this

**Comment by Canderous** [comment]
Yes, and also, when you leave, the dungeon is not counted as completed and you get the Deserter debuff.

**Comment by Wolffenstein** [comment]
Fixed in rev 4367.
