### ISSUE TITLE
[ENG][PROFESSIONS][MINING][NODES]Outland- Rich Adamantite Deposits not working.

### ISSUE THREAD

**Issue by Ulrich1able** [Atlantiss/BugTracker#2739]
I'm trying to level up my mining and engineering, so while out mining ore veins, i noticed all of the rich adamantite ones weren't working. When you hover over them instead of giving a little pickaxe to mine it, it just shows a gear instead, and its impossible to mine it.
http://www.wowhead.com/object=181569/rich-adamantite-deposit

**Comment by xmesaj2** [comment]
Some work, but not all of them. Try mining in The Slave Pens instance, I could mine them there and some random nodes in world too.

**Comment by Wolffenstein** [comment]
Fixed in rev 4367.
