### ISSUE TITLE
[PL][Quest][The Storm Peaks] The Last of Her Kind

### ISSUE THREAD

**Issue by Elhalli** [Atlantiss/BugTracker#2740]
http://www.wowhead.com/quest=12983/the-last-of-her-kind#comments
Zgodnie z komentarzem na Wowheadzie:
"Enter the cave at 55,63.

Take the far left path and fight mobs along the cave wall.

Eventually you will stumble across a large white bear laying on the ground which you are able to ride.

Simply hop on the bear, it is a vehicle and it will automatically ride back to the quest giver."
Automatycznie nie zawozi nas do Quest givera, jednakże można miśkiem biegać jak zwykłym mountem, a po dotarciu do givera nie zalicza nam questa

EDIT:
Po ~2-3 razach zadziałał

**Comment by Scrimish** [comment]
Zepsute jest fazowanie, po wylocie z wisoki traci sie buffa dajacego przebranie. Przez co sam mis w jakini jest wrogi w stosunku co do nas (nie da sie go dosiasc). Fazowanie dzialalo dobrzez w poprzednich questach. Dodam ze jest to quest z chaina do reputacji u Hodirow (co obecnie jest zablokowane)

**Comment by Scrimish** [comment]
bump

**Comment by armano2** [comment]
new issue: #4309
