### ISSUE TITLE
[EN][NPC][Icecrown Citadel][The Lich King]

### ISSUE THREAD

**Issue by Nausica07** [Atlantiss/BugTracker#2741]
The final boss in Icecrown Citadel (10) - The Lich King http://www.wowhead.com/npc=36597/the-lich-king#abilities has multiple bugs:
- We couldn't always port to The Lich King, when we managed it, sometimes players fell through the platform
- During remorseless winter sometimes players were one-shot to death (http://www.wowhead.com/spell=72259/remorseless-winter ) 
- The outer platform didn't come back after he used Quake on our first attempt. (http://www.wowhead.com/spell=72262/quake)
- The cutscene at the end of the fight has missing animations
- At the end of the fight NPC ressed only one person

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1361
