### ISSUE TITLE
[EN][Quest][In Defense of Westfall][Westfall]

### ISSUE THREAD

**Issue by MadeeV** [Atlantiss/BugTracker#2745]
http://www.wowhead.com/quest=26286
Quest is bugged, dont work.. It should work like this: https://www.youtube.com/watch?v=Bc_LxoqNMOc

**Comment by Kejmil** [comment]
same problem as in https://github.com/Atlantiss/BugTracker/issues/2733

**Comment by Quban** [comment]
Fixed by Bildo in rev. 4446 when fix to https://github.com/Atlantiss/BugTracker/issues/2733 was applied

**Comment by Bildo** [comment]
huh ?

**Comment by Quban** [comment]
Yes :)
