### ISSUE TITLE
[EN][Quest][Duskwood] Morbent's Bane

### ISSUE THREAD

**Issue by burkarn** [Atlantiss/BugTracker#2749]
There are many Flesh Eaters and Plague spreaders spawned down in Dawning Wood Catacombs (Duskwood 16,39). They're supposed to lie on the benches, but on Atlantiss they are alive.
After you kill Morbent Fel he's supposed to kill the mobs that are guarding the path to the exit. He doesn't do that.

Atlantiss: http://i.imgur.com/B1pt0Tm.jpg
Retail: https://www.youtube.com/watch?feature=player_detailpage&v=Dd96KY9SEHE#t=66
http://www.wowhead.com/quest=26754/morbents-bane

**Comment by Quban** [comment]
fix soon
