### ISSUE TITLE
[PL][Quest][Uldum] Three if By Air: Quest item crashes client.

### ISSUE THREAD

**Issue by jakubo98** [Atlantiss/BugTracker#275]
http://www.wowhead.com/quest=28622
Quest item http://www.wowhead.com/item=64668 powoduje crash po paru sekundach. Nie ma castowania, postać ma animacje tworzenia czegoś ale nic nie robi (jak przy lagu lub crashu serwa), nie zalicza questa.
4 crash logi:
http://pastebin.com/iWCKmzbL
http://pastebin.com/HBN9s8My
http://pastebin.com/D81nHH3R
http://pastebin.com/83vjvG7N
PS: Dotyczy to main serwera. Nie znalazłem bugtrackera od 4.0.6

**Comment by bgb** [comment]
Mam to samo. Używam quest itema, postać zaczyna castować ale nic się nie dzieje. Item tylko ma tą żółtą obwódke jakby był używany... No i gdy naciskam esc wyskakuje wow error.

**Comment by sunshineinabox** [comment]
This is the same crash I was part of the similar issues that I was having when I leveled as well. The issue I opened was #3053

**Comment by WickedInsaneMan** [comment]
Happened to me too. The crash happens after you use the item and press 'ESC', but if you interrupt the casting with something else, like mounting the crash does not happen anymore. The quest can be completed by right clicking the flare locations and not using the item.

**Comment by aje** [comment]
confirmed

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6819-wow-error-by-pressing-escape-after-using-item/

**Comment by krecik88** [comment]
Fixed in 5377
