### ISSUE TITLE
[ENG][MOB] Azure Scalebane" "Azure Spellweaver

### ISSUE THREAD

**Issue by Ulrich1able** [Atlantiss/BugTracker#2751]
These dragonkin mobs at 'The Azure Front' inside Crystalsong Forest in Northrend are currently untargetable.

http://www.wowhead.com/npc=31402/azure-scalebane
http://www.wowhead.com/npc=31403/azure-spellweaver

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1639

**Comment by Ulrich1able** [comment]
Thanks
