### ISSUE TITLE
[PL] [Quest] [Cata] [Origrimar] Weapons of Mass Dysfunction

### ISSUE THREAD

**Issue by HUMBOL** [Atlantiss/BugTracker#2752]
http://www.wowhead.com/quest=26294/weapons-of-mass-dysfunction

Po przeprowadzeniu inspekcji na wadliwym sprzęcie nie zalicza pierwszej części questa (Faulty Demolisher Discovered), natomiast drugą część można zaliczyć (Chief Engineer Disciplined)

Screen: http://screenshooter.net/101984253/hxdvftd

**Comment by mitim1** [comment]
Quest działa w 100%. 
Do zamknięcia.
