### ISSUE TITLE
[PL][Quest] Coldridge Valley #2

### ISSUE THREAD

**Issue by maslak** [Atlantiss/BugTracker#2753]
Temat związany z tym https://github.com/Atlantiss/BugTracker/issues/2655

Niestety ale oba zadania dalej nie działają poprawnie.
 Make Hay While the Sun Shines
http://www.wowhead.com/quest=24486/make-hay-while-the-sun-shines
Whitebeard Needs Ye
http://www.wowhead.com/quest=24487/whitebeard-needs-ye

Zadanie  Make Hay While the Sun Shines można oderbać od npc ale zamiast zdobycia 5 itemów Priceless Rockjaw Artifact musimy zdobyć ich 5+1 jak na ss.
http://s22.postimg.org/4xkzopr4x/zadanie_1.jpg 
Po dropie 5 itemów kolejnego nie można zdobyć, zadanie nie do zrobienia.

Zadanie Whitebeard Needs Ye. Gdzie normalnie powinno się oddać raport do jednego npc do drugiego, tutaj na realmie wygląda to tak, że mamy ubić npc o naziwe Overseer Narvir - This NPC can be found in The Storm Peaks.
http://s9.postimg.org/w87jk7cfz/zadanie_2.jpg

Czekam na poważne potraktowanie sprawy. Pozdro.

**Comment by sabi102** [comment]
U mnie Overseer Narvir pojawil sie do zabicia w kazdym quescie z questloga - nawet w http://www.wowhead.com/quest=28884/victory-in-tol-barad. Ss niestety nie dodam gdyz serwer off.

**Comment by Wolffenstein** [comment]
To wina dzisiejszych problemów z bazą.

**Comment by sabi102** [comment]
A czy zostanie to naprawione? Bo mimo usuniecia questow i zabrania ich na nowo wciaz trzeba zabic tego npc zeby wykonac questa..

**Comment by Bildo** [comment]
wyczysc cache
