### ISSUE TITLE
[PL] [Quest] [Cata] [Origrimar] The Zandalari Menace

### ISSUE THREAD

**Issue by HUMBOL** [Atlantiss/BugTracker#2754]
http://www.wowhead.com/quest=29157/the-zandalari-menace

Brak Npc do pogadania:http://www.wowhead.com/npc=53081/bwemba#ends

Screen: http://screenshooter.net/101984253/qxyjbpc

**Comment by Unn90** [comment]
Jest juz 4.1? że ten q ma działać?

**Comment by HUMBOL** [comment]
http://atlantiss.eu/changelog#rev4368

**Comment by Giq** [comment]
Napisaliśmy, że chain otworzymy 25tego. Npc stoi narazie w innej fazie
