### ISSUE TITLE
[PL][Quest][Cata][Origrimar]Unfamiliar Waters

### ISSUE THREAD

**Issue by mitim1** [Atlantiss/BugTracker#2755]
http://www.wowhead.com/quest=26311/unfamiliar-waters
http://www.wowhead.com/npc=42638/herezegor-flametusk
http://www.wowhead.com/npc=42707/twilight-nightblade
http://www.wowhead.com/item=58141/twilight-highlands-coastal-chart
Nie można porozmawiać z "Herezegor-flametusk" przez co "Twilight-nightblade" nie pojawiają się i nie ma możliwości zdobycia "Twilight Highlands Coastal Chart".

**Comment by Wolffenstein** [comment]
TH jeszcze nie jest gotowe.
