### ISSUE TITLE
Quest: Archivum Data Disk

### ISSUE THREAD

**Issue by Vallst** [Atlantiss/BugTracker#2759]
Archivum Data Disk is the quest chain in Ulduar to obtain the Celestial Planetarium Key,which opens the chamber of Algalon the Observer,a boss in Ulduar. The very first part of the quest chain is uncompletable,after a player loots the quest starting item and accepts the first quest,it cannot be completed,even tho the minimap shows a yellow ? at the spot where the quest item must be brought to.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
