### ISSUE TITLE
[PL][Quest][Mount Hyjal] Spis

### ISSUE THREAD

**Issue by Asavel** [Atlantiss/BugTracker#276]
***As Hyjal Burns*** - http://www.wowhead.com/quest=25316
Zdjęcie - http://zapodaj.net/c431cf06bd43b.jpg.html
Nie można zejść ze smoka ani się ruszyć pomaga relog zrzucając nas na ziemie.

***The Bears Up There*** - http://www.wowhead.com/quest=25462
Jest Complete po odebraniu.

***The Last Living Lorekeeper*** - http://www.wowhead.com/quest=25830
Przy próbie oddania Questa npc(http://www.wowhead.com/npc=41381) znika 
SS'y:-http://zapodaj.net/44505e150be18.jpg.html  http://zapodaj.net/b886b352dd6a2.jpg.html

***Ten post będzie edytowany o kolejne Questy***

**Comment by BAndysc** [comment]
Trochę szkoda, że pierwszy quest z Cataclysmu As Hyjal Burns przestał działać :s

**Comment by nerv234** [comment]
działał mi kilka dni temu.

**Comment by Bildo** [comment]
działa all

**Comment by Asavel** [comment]
:O trampolina dziala?

**Comment by Bildo** [comment]
trampolina akurat nie dziala :D ale jest zgloszone inne
