### ISSUE TITLE
[EN][Quest][Darkshore] Soothing the elements 

### ISSUE THREAD

**Issue by samigafsi0** [Atlantiss/BugTracker#2764]
in the quest you are supposed to place a totem and defend it against elementals until the ritual is done.
the bug here is that when you place the totem only one elemental appear and they stop . you can spend the whole day there waiting and no other elemental will spawn and the quest will not get confirmed .

http://www.wowhead.com/quest=13580/soothing-the-elements

**Comment by Tj20** [comment]
duplicate: #1521
