### ISSUE TITLE
[En] [Quest] [Gilneas] You Can't Take' Em Alone

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#2765]
This quest works and everything is scripted as it should, however if you throw the barrel when you are a bit far away the barrel won't explode. A cd is shown on the Abomination but it remains alive.
Wowhead:
 http://www.wowhead.com/quest=14348/you-cant-take-em-alone

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3558
