### ISSUE TITLE
[EN][Proffesions][Core mechanic] Exp from mining

### ISSUE THREAD

**Issue by e-s** [Atlantiss/BugTracker#277]
'New to Patch 4.0.1, mining, herbalism, and archeology grant XP. Skinning does not grant XP.'

http://www.wowwiki.com/Formulas:Gather_XP

As for Atlantiss, mining does not give xp, need to be fixed. Herbalism and archeology do give exp.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/615

**Comment by mikonek07** [comment]
Herbalism also doesnt provide experience at higher lvl [ only classic herbs do, gattering herbs from OL, Northrend, Cata's locations dont give experience ]
