### ISSUE TITLE
[EN][NPC][Zul'Drak] Thrym

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2770]
http://www.wowhead.com/npc=28243/thrym (World NPC)
http://www.wowhead.com/npc=29895/thrym (phased quest NPC)

This little guy is not patrolling the path in Zu'Drak and sneaking up on poor players to crush them. (Talking about the world mob here, not the phased quest mob mentioned in #518 who also seems to be missing)

![pic](http://i.imgur.com/WfQn9rL.jpg)

**Comment by eryczek1615** [comment]
bump

**Comment by Rushor** [comment]
>This little guy

xDDD
