### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Soft Landing

### ISSUE THREAD

**Issue by hiralovesgiita** [Atlantiss/BugTracker#2771]
http://www.wowhead.com/quest=27460/soft-landing

Quest should work on any crusade mobs,
But it only works on "Scarlet Warder".

Also i believe their hp is twice the normal.

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7445-2771quest-soft-landing/
