### ISSUE TITLE
[EN][Quest][Argent Call: The Trial of the Crypt] Eastern Plaguelands

### ISSUE THREAD

**Issue by hiralovesgiita** [Atlantiss/BugTracker#2772]
http://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt

You should be able to cast the scroll and he will spawn, so you can fight him. Instead, you cast it, you cannot fight it, only your companions from the quest http://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt can attack him (but only one of them)
You can cast the scroll again to spawn another one which will then fight another of your companion.

You can cast the scroll how many times you want, but you wont be able to hit the quest mob, you will have to patienty wait for your companion to kill him. (Takes really long).

**Comment by Swepy** [comment]
I remember doing this quest two times, for the first time i had the same bug what you just said so i let my companions kill it and i completed the quest. The second time i was doing it with an other character and it worked just fine. Maybe if you relog or abandon and take the quest again can fix it.

**Comment by hiralovesgiita** [comment]
Well then it's still needed a fix :)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/499
