### ISSUE TITLE
[EN][Quest][Postponing the Inevitable] Eastern Plaguelands

### ISSUE THREAD

**Issue by hiralovesgiita** [Atlantiss/BugTracker#2774]
https://www.youtube.com/watch?v=ti2ZB44-LzA
http://www.wowhead.com/quest=27420/postponing-the-inevitable

You should gather Control Runes from Dark Cultists and Shadowmages.
Then you should use the Overcharged Mote to destroy 3 Plague Disseminators.

Instead you can use the Overcharged Mote on the campfire. (not tested other places) and there is no Plague Disseminators. So you basically use it on air and the quest is completing.

Youtube video shows how it should work.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/498
