### ISSUE TITLE
[PL][NPC][STORMWIND] Bwemba 

### ISSUE THREAD

**Issue by Unn90** [Atlantiss/BugTracker#2776]
Brak NPC.
http://www.wowhead.com/npc=52654/bwemba

Sprawdzałem 5 postaciami do tego 30 innych osób sprawdzało i go nie widzi. 
Panie Bildo także NIE MA GO po stronie ALLY na łódce, na której powinien być natomiast po stronie HORDY NPC jest.

**Comment by Lulz1** [comment]
Potwierdzam, brak npc - nie można zacząć chaina. Niech admin łaskawie raczy się przejść i sprawdzić zanim walnie pustym komentem...

**Comment by Wolffenstein** [comment]
Lulz bo ci żyłka pęknie :D
