### ISSUE TITLE
[EN] [Night elf racial trait] Elusiveness

### ISSUE THREAD

**Issue by diokap** [Atlantiss/BugTracker#2778]
http://cata.openwow.com/spell=21009

"Increased speed while stealthed" racial trait doesn't work. I don't know about "reduced chance to be detected while using shadowmeld" though.
I know there is a polish version of this bug report, but i made a new one so english speakers can track this easily.

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev4374 and next time if u see that there is a polish report just add comment in english.

**Comment by diokap** [comment]
Ok thank you.
