### ISSUE TITLE
[PL][Core][Transmog] mace weapon

### ISSUE THREAD

**Issue by jurek1** [Atlantiss/BugTracker#2779]
nie moge dac na transmoga tej macki http://cata.openwow.com/item=14531#
gdy klikam apply , nic sie nie dzieje i nie ma zadnej informacji

**Comment by blinkmaster** [comment]
to nie bug. transmogowac mozna tylko itemy ze statystykami, to jest item bez statystyk a tylko efektem.

**Comment by jurek1** [comment]
no ale jakies info powinno chyba byc xd

**Comment by Tj20** [comment]
Should be possible, others have transmogged that mace, [source](http://www.mmo-champion.com/threads/987609-Rate-the-transmogrification-set-above-you!/page201).

![pic](http://i.imgur.com/ROtwRav.jpg)

If it doesn't work, try to relog and make sure that you have enough gold. On retail there once was a [known issue](http://eu.battle.net/wow/en/forum/topic/6892930617) that transmogrification costs were appearing incorrectly in the Transmog UI.

**Comment by jurek1** [comment]
i have 20 k gold , so i have enough gold

**Comment by bgb** [comment]
You can use items without stats to transmog according to this:

http://www.engadget.com/2013/02/08/how-to-get-started-with-transmogrification-and-be-the-most-styli/

" You cannot transmogrify items without stats of any kind, though you can use their appearance to transmogrify other items."

**Comment by jurek1** [comment]
kolega hunter chcial na transmoga http://www.wowhead.com/item=48697/frenzystrike-longbow  i ma taki sam problem jak ja ( 0 info itp )

**Comment by Nc94** [comment]
Same issue with: http://cata.openwow.com/item=31331

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
