### ISSUE TITLE
[PL][Guild] Przejęcie GM

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#278]
Od patcha 4.3 gdy GM jest nie aktywny przez miesiąc lub więcej jeden z graczy może przejąć stanowisko GM. Aktualnie to u nas nie działa(brak jakiejkolwiek wiadomości w New & Events)

Guilds with inactive guild leaders can now usurp the leader under specific conditions.
The way inactive guild leader replacement works is pretty straightforward. If a guild leader’s character is inactive for 30 days, a notification will appear in the Guild News & Events feed which can only be seen by guild members who are eligible to become the new guild leader. To determine eligibility, the game will look for the highest ranked character in the guild that’s logged on in the past week, and any guild member from that rank will be able to request guild leadership simply by clicking on the notification.

http://pl.wow.wikia.com/wiki/Patch_4.3.0_(undocumented_changes)

**Comment by Malylolek** [comment]
Rev.4300 
Nie działa

**Comment by gorciott** [comment]
Kiedy będzie wiadomo coś o tej opcji?

**Comment by krecik88** [comment]
already fixed
