### ISSUE TITLE
[PL][Quest][Badlands] Lifting the Veil

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2781]
Praktycznie cały quest chain od Rhea nie działa. Działa jedynie pierwszy quest, utknęłam na drugim - "Lifting the Veil"
link do chaina: http://www.wowhead.com/quest=27765/first-sample-wild-eggs
link do drugiego questa: http://www.wowhead.com/quest=27770/lifting-the-veil
po otrzymaniu questa "Lifting the Veil" nic się nie dzieje.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1632
