### ISSUE TITLE
[PL][Quest][Icecrown] Generosity Abounds

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2782]
Przeciąganie bomby do Abominata nic nie daje, nie ma reakcji. Mobek powinien wybuchnąć a nam powinno zaliczyć questa.
link do questa: http://www.wowhead.com/quest=13146/generosity-abounds

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1945
