### ISSUE TITLE
[PL][Quest][Desolace] Three Princes

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2783]
Quest można bez problemu zaliczyć, jednak nie ma npc, któremu powinno się quest oddać.
link do questa: http://www.wowhead.com/quest=14328/three-princes
link do npca: http://www.wowhead.com/npc=36185/khan-shodo

**Comment by Bildo** [comment]
jest

**Comment by Veruca1320** [comment]
gdzie jest ? obeszłam całą jaskinie, zrobiłam questa 2 razy i nic :/
