### ISSUE TITLE
[EN][Quest][The Storm Peaks] Back to the Pit

### ISSUE THREAD

**Issue by 0135** [Atlantiss/BugTracker#2784]
<a href="http://www.wowhead.com/npc=30174/hyldsmeet-warbear">Hyldsmeet Warbear</a> are not attacking and missing their riders.
<a href="http://www.wowhead.com/npc=29918/warbear-matriarch">Warbear Matriarch</a> that you summon has a wrong abillity "Bite" instead of auto attack and is stuck in "walk" mode.
How it should work : http://classic.xfire.com/video/34ad37/

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2473
