### ISSUE TITLE
[PL][Core] Transmog

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#2788]
Nie da się w żaden sposób transmogować <a href='http://www.wowhead.com/item=18816/perditions-blade#dropped-by'>Perdition's Blade</a>. Możliwe, że ma to związek z nadpisywaniem enchantów przez tę broń.

**Comment by bgb** [comment]
Problem raczej polega na błędnym założeniu devów, że item nie może być użyty do transmogowania jeśli nie ma statystyk...

**Comment by sabi102** [comment]
Ja rowniez mam problem z transmogiem - 
http://www.wowhead.com/item=17590/warlords-dreadweave-mantle
http://www.wowhead.com/item=23256/champions-dreadweave-spaulders
ani jednego ani drugiego itemu nie moge tranmogowac, gdy probuje wlozyc item w okienko wyskakuje mi wiadomosc "This item's appearance cannot be used"
Dodam ze gram warlockiem wiec nie jest problemem to ze chce na inna postac warlockowy set zalozyc .

**Comment by bgb** [comment]
sabi102 - tak akurat powinno być. Poczytaj komentarze na wowhead.

**Comment by bgb** [comment]
Czemu Closed? Transmogowanie broni bez statów, tylko z szansą na hit wciąż nie działa.

**Comment by Jenovas** [comment]
Jest wiele innych zgloszeń w których jest to samo, nie ma sensu trzymać wiele zgłoszeń w których jest ten sam błąd.
