### ISSUE TITLE
[En] [Quest] [Gilneas] Introductions Are in Order

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#2790]
The quest can be completed, however the final event (that happens right after that the quest is completed) is not scripted.
Wowhead:
http://www.wowhead.com/quest=24472/introductions-are-in-order
Video from retail:
https://youtu.be/8e8eWNSwNVw?t=41m6s

**Comment by Aival94** [comment]
I think you mean the vent after this quest.

https://youtu.be/2M8Yh4Uuaac?t=2189

**Comment by Daknyas** [comment]
Yes, it's the same quest. I didn't notice that that part was not in the video I posted. Thanks!

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3558

**Comment by gonzoyola** [comment]
Hoping this is the right place to address this. As of 1:00 am CST on 11/8/2015 Koroth's banner cannot be picked up. I tried from several locations, and other players had the same problem.
