### ISSUE TITLE
[PL][Quest][Westfall] A Vision of the Past

### ISSUE THREAD

**Issue by Eluno** [Atlantiss/BugTracker#2793]
Po skonczeniu poprzedniego questu chainowego miałem nad tym NPCem normalny żółty wykrzyknik. Przeczytałem opis questu ale odrzuciłem go, a wykrzyknik zmienił się w niebieski pytajnik i teraz nie mogę ani wziać questu ani go oddać, mimo, że mam taki opis jakbym go wykonał. http://oi61.tinypic.com/29dx0fp.jpg
Quest ten jest częścią głównego chaina w Westfall.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1622
