### ISSUE TITLE
[EN][Dungeon heroic]The Culling of Stratholme

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#2795]
That dungeon dont work. Link: http://www.wowhead.com/zone=4100/the-culling-of-stratholme
Arthas when beggin event to cull all city, he start to attack http://www.wowhead.com/npc=27737/risen-zombie and get aggro from Malganis come so speak with Arthas and after that he stop and dont continue his path on map.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2551
