### ISSUE TITLE
[PL] Instant Statue Pedestal

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#2796]
Krótko i zwięźle powinno działać tak:
https://www.youtube.com/watch?v=enAoYb01a-s&ab_channel=olegunnar1984

a u nas działa tak:

http://postimg.org/image/yy6jdjydt/

Platforma się pojawia i nic.

**Comment by Haz3L** [comment]
Kiedy w końcu zacznie działać? Nie po to wydałem vote pointy...

**Comment by Haz3L** [comment]
Naprawcie to w końcu, albo oddajcie mi vote pointy...

**Comment by aje** [comment]
Just tested on the PTR and now it works.
Post a comment here if this is not the case on the main realm.
