### ISSUE TITLE
[EN] [Warrior] [Spell] - Deadly Calm & Recklessness

### ISSUE THREAD

**Issue by obsyd** [Atlantiss/BugTracker#2798]
http://wow.gamepedia.com/Deadly_Calm
http://www.wowwiki.com/Deadly_Calm

http://wow.gamepedia.com/Recklessness
http://www.wowwiki.com/Recklessness

Sometimes weird things happen with those skills, namely after wipe on a boss it is very often the case that warrior's CD on those skills gets buged - both of them magically get 5 min CD (which is funny since Deadly Calm is 2 min cd). I dont know what exactly causes the bug but it is extremly annoying when you have to wait 5 min every wipe for your CDs even if at the moment of wipe you had for example 1 min left. I actually stoped asking people to wait for them because it takes too much time ;p (i see this bug almost everytime i appear on the graveyard in ghost form after wipe)

Here is SS showing what i am talking about ;p :

http://i61.tinypic.com/2crsndf.jpg

**Comment by Wojowniczka** [comment]
I am TOTALLY agreed with @obsyd and i get that bug few times as well during raids and i don't know what causes this issue :/ tryed few ways to reproduce that but with no succes.

**Comment by Wojowniczka** [comment]
chyba wiem co to powoduje - dziś 06.04.2015 rev.4385 byłem na Sethekk Halls i użyłem tylko Recklessness (Deadly Calm nie użyłem i był możliwy do użycia) na Anzu po czym po prostu opuściłem dunga i prawdopodobnie gdy przechodzimy przez portal do dunga / raidu buguje się cd na Deadly Calm i jak tylko wyszedłem z dunga i się załadował ekran to patrze a na Deadly Calm i Recklessness mam po 4 minuty cd :o tak jak napisałem w nawiasie wyżej NIE użyłem Deadly Calma w ogóle więc nie powinno być żadnego CD na nim.

**Comment by Wojowniczka** [comment]
potwierdzam iż bug wysępuje gdy użyjemy Recklessness a zostawimy sobie Deadly Calm po czym wyjdziemy / wejdziemy do dunga przez portal i robi się 4 min cd na Deadly Calmie mimo że nie był używany a i tak CD jest "zapożyczony" z Recklessnessa

**Comment by Jenovas** [comment]
Fixed in rev  4413
