### ISSUE TITLE
[PL][Hunter][Warrior][Core]

### ISSUE THREAD

**Issue by lx771** [Atlantiss/BugTracker#2799]
Huntery bez przeszkód strzelaja sobie na bg przez przeszkody typu drzewewa, skały, pagórki. Postaram się to złapac na screenie i wrzucić.

O tym już epwnie cała administracja wie, ale przypomnę: szarża i heroic leap nie działają w 100% jak powinny. Nie da się szarżować czy leapować w powietrzu, z wody czy do wody, rowniez w wodzie czasami działa.

**Comment by Varchord** [comment]
BT rules
