### ISSUE TITLE
[EN][Talent][Mage] Frostfire orb breaks Polymorph

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#28]
Frostfire Orb (http://cata.openwow.com/spell=84714) breaks Polymorph (http://cata.openwow.com/spell=118). 
It should ignore targets with Polymorph and hit other targets or just do nothing, when theres no enemy target available.

FFO works fine with Ring of Frost (it hits "RoFed" target but don't break it which is blizzlike).

**Comment by Wolffenstein** [comment]
Fixed in rev 4238.
