### ISSUE TITLE
[EN] [Instance-Cata] Throne of the Tides - ID Bug

### ISSUE THREAD

**Issue by Hanatsu** [Atlantiss/BugTracker#2800]
The instance starts with all mobs dead with new group, after reset. When you leave you either get deserter debuff or CD with 10min+

This occurs during normal difficulty often!

**Comment by Varchord** [comment]
Actually bug is slightly different. 
Problem is that completing this dungeon in normal mode gives you 4h ID for it. You can still queue for it in rdf but instance will be empty for you and your party members

**Comment by KlawiszQ** [comment]
>Problem is that completing this dungeon in normal mode gives you 4h ID for it.

This lock as well as the locks for 5 man HCs are pretty much fun killers, it could be useful to have them turned off
![Image of lock](http://i.imgur.com/ldA9MNF.jpg)

**Comment by Varchord** [comment]
rdf finder for hc dungeons gained ID bypassing mechanic in 4.2 i think
It is described in my general dungeon finder issue. Wolff've tried to implement it but there were many problems with it

**Comment by Tj20** [comment]
Varchord is right, I've experienced this as well. Completing this in normal mode gave me a 2h ID where I could still queue, but the instance was empty (save for the one boss no group wants to do).

![pic](http://i.imgur.com/ovxnkV1.jpg)

**Comment by sunshineinabox** [comment]
This issue is still happening and it is, because of the instance lock. This can be an issue when using rdf b/c sometimes it puts half the group in a fresh ID while the rest are left in an empty instance.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3312
