### ISSUE TITLE
[EN] [RAID-Cata] Throne of the Four Winds - Al'Akir

### ISSUE THREAD

**Issue by Hanatsu** [Atlantiss/BugTracker#2801]
I don't know if this topic have been brought up.

Every time we raid Al'Akir (only tested 10man), we get fatal error and client crashes (error134 IIRC). We have defeated the boss before, but the crashes occur 9/10 times.

I'll screenshot the error message next time we raid him if required.

**Comment by mitim1** [comment]
#2386

**Comment by Bud1980** [comment]
they need to fix the Guild Achievement for killing the all bosses as a guild aswell
