### ISSUE TITLE
[PL][NPC]Vendor Arena Season 4 Set

### ISSUE THREAD

**Issue by FakeMarcin** [Atlantiss/BugTracker#2803]
Na naszym serwerze nie ma Npc którzy umożliwiają kupienie setu s4 z TBC[http://www.wowhead.com/itemset=-2/brutal-gladiators-battlegear]

Vendors
http://www.wowhead.com/npc=23396 and http://www.wowhead.com/npc=40209 in Netherstorm [A H]
http://www.wowhead.com/npc=20278 and http://www.wowhead.com/npc=40216 in Tanaris [A H]
http://www.wowhead.com/npc=30885/blazik-fireclaw and http://www.wowhead.com/npc=40212 in Dalaran [A H]
http://www.wowhead.com/npc=12795 in Orgrimmar [H]
http://www.wowhead.com/npc=12785 in Stormwind [A]

**Comment by Varchord** [comment]
wowhead liinks
BT rules

**Comment by FakeMarcin** [comment]
bump

**Comment by Bildo** [comment]
npc sa tylko nie sprzedaje wszystkich rzeczy, tak trudno napisac dobre zgloszenie ?

**Comment by Bildo** [comment]
Replic nie bedzie na serwerze, na retailu byly one dostepne za sezon z tbc czy tam ktoregos wczesnego dodatku, u nas moga byc za cos innego ale jeszcze nie wiem za co
