### ISSUE TITLE
[PL] [zbugowana faza]

### ISSUE THREAD

**Issue by pankutator** [Atlantiss/BugTracker#2804]
Mam problem ponieważ buguje mi się faza w stormwind przy npc od transmoga, reforge itd. jak tylko faza zmienia sie z the canals na stormwind znikają mi npc i nie moge nic tam zrobić. Ten problem występuje tylko na postaci Pankutator a na innych się nie buguje

**Comment by Murmaider** [comment]
Wiele osob ma ten problem, relog pomaga.

**Comment by arekczup** [comment]
po pierwsze angielski nagłówek zrób i daj linka z wowheda

**Comment by pankutator** [comment]
mi relog nie pomaga ;(
