### ISSUE TITLE
[PL][Raids][Ulduar]

### ISSUE THREAD

**Issue by FakeMarcin** [Atlantiss/BugTracker#2805]
-[Flame Leviathan] kompletnie nie przepisany boss,po pullu wchodzi w tekstury i co jakiś czas pojawia się by wybrać target i wycastować spell,brak maszyn po zaaktywowaniu normal/hard mode,
-[Xt Deconstructor] widoczne serce w teksturach przez całą walkę
-[Freya] brak możliwosci zbicia rootow  z gracza, co za tym idzie brak możliwości przemieszczania się
-Nie działający [Quest:Archivum Data Disc] a co za tym idzie uniemożliwia to otwarcie pomieszczenia Celestial Planetarium gdzie znajduje się boss [Algalon the Observer]

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1756
wowhead liinks
BT rules
