### ISSUE TITLE
[PL][Achievement][PvP] Gurubashi Arena Grand Master

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2809]
Obecnie nie możliwe jest zaliczenie achievementu ze względu na brak trinketu w skrzyni (a potrzeba 12 sztuk).
link do achievementu: http://www.wowhead.com/achievement=396/gurubashi-arena-grand-master
link do trinketa: http://www.wowhead.com/item=18706/arena-master#comments

**Comment by xmesaj2** [comment]
Nie wiem czy coś zmieniali, ale mam kilka sztuk trinketu Arena Master. Może ktoś po prostu wyciągnął go ze skrzynki przed Tobą.

**Comment by Veruca1320** [comment]
próbuje zrobić ten achievement od kilku miesięcy, jak nie dłużej, za każdym razem gdy była skrzynia - bez trinketu.

**Comment by xmesaj2** [comment]
no nie wiem, ja max 2 tygodnie temu pomagałem zdobyć ten trinket jakiemuś low lvlowi jak kopałem skałki w stv i dostał przy mnie achieva za zdobycie jednej sztuki.

**Comment by Veruca1320** [comment]
za jedna sztuke tez bez problemu zdobyłam, ale juz kolejnych 11 sztuk nie ma. W skrzynkach sa same "śmieci".

**Comment by coocoo89** [comment]
Prawdopodobnie oddałaś q u goblina co uniemożliwia zabieranie nastepnych trinketów.
To działa i jest blizzlike 4 dni temu sam zdobyłem trinketa ze skrzyni.
Więc można ten watek usunąć.

**Comment by Veruca1320** [comment]
bardzo możliwe, że oddałam quest goblinowi, ale skąd miałam wiedzieć, że nie należy oddawać? Co w takim wypadku powinnam zrobić?

**Comment by coocoo89** [comment]
Napisz maila do supportu o wymazanie q na postaci, może ci sie uda.

**Comment by Veruca1320** [comment]
po interwencji GM'a (wymazaniu questa) CHWILOWO działało - w skrzyni pojawił się trinket (obecnie mam 2). Quest z trinketa miałam dostępny - nie akceptowałam go, nie oddawałam goblinowi! Przy kolejnej skrzynce problem znów się pojawił - same śmieci, brak trinketa, a po próbie wzięcia questa z trinketa - "you are already on that quest". Wychodzi na to, że po każdym zabranym ze skrzyni trinkecie trzeba wymazywać quest... :/

**Comment by Veruca1320** [comment]
<Po 3 wymazywaniach questa> Podjęcie próby zaakceptowania questa z trinketa nie wyszło mi na dobre - w skrzyni nie było trinketa, a gdy usunełam quest z quest loga 2 z 3 trinetów ZNIKNEŁY! Ale dzięki temu mogłam ze skrzyni wziąć trinket, więc teraz mam 2...

**Comment by xmesaj2** [comment]
chodź na browar i spokój, ładna pogoda :D

**Comment by Kaabum** [comment]
Obecnie mam dokładnie ten sam problem. GM już raz mi resetował q, niestety nie pomogło. Ktoś, coś pomoże?
Nick: Retnuh

**Comment by rustndust** [comment]
U mnie to samo. W ub. r robiłęm to kilkoma twinkami i udawało się ukończyć, aczkolwiek zdarzały się skrzynki bez trinketu. Teraz mam 1 trinket w bagu twinka i bodaj 6 czy 7 w bagu u alta ubijającego guardów. On podnosi bez problemu (nawet po uprzednim otwarciu skrzynki przez twinka), zaś twinkowi pojawia się tylko junk, Napisałem ticket i dostałem odpowiedź, żeby to wrzucić na bugtracker. Wrzuciłem, ale brak odzewu. Co jeszcze mogę zrobić?
