### ISSUE TITLE
[EN][Quest][Grizzly Hills] "Filling the Cages"

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2810]
http://www.wowhead.com/quest=11984/filling-the-cages

The quest is completable, but easier than intended: Just click the quest item and you're done.

Normally you would have to talk to the NPC Budd who becomes your pet. He would sap an enemy troll for you via pet bar button and then you would have to use the quest item on the enemy troll.

**Comment by Wolffenstein** [comment]
Fully scripted in rev 4384.

**Comment by Maczuga** [comment]
Sadly this doesn't work at all now. I've already tried pressing button, putting him in different stances, moving him to NPC, but nothing happends, he's just making aggro sounds.

**Comment by lanrutcon** [comment]
It's currently bugged, like Maczuga said, even if you press the ability to sap the trolls, the NPC doesn't do anything.
And without it, the quest-item is impossible to use.
