### ISSUE TITLE
[ENG][NPC][Shattrath City] Auctioneers useless

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2811]
Auctioneer Braku http://www.wowhead.com/npc=50145/auctioneer-braku
Auctioneer Itoran http://www.wowhead.com/npc=50143/auctioneer-itoran
Auctioneer Kalaren http://www.wowhead.com/npc=50139/auctioneer-kalaren
Auctioneer Lyrsara http://www.wowhead.com/npc=50140/auctioneer-lyrsara

Those are useless, they are only standing around and are not working.

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1610

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7978-60692811-auctioneers-shattrath-city/
