### ISSUE TITLE
[EN][Spell][Hunter] Misdirection

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2812]
http://www.wowhead.com/spell=34477/misdirection

**Observed behavior:** 

[Tallhorn Stags](http://www.wowhead.com/npc=26363/tallhorn-stag) apparently are immune to Misdirection: if I misdirect my pet and begin shooting the stag, the stag immediately targets and attacks me instead of my pet. (pet set on passive so it won't interfere with its attacks) ([combat log](http://pastebin.com/Yf8LV4w8))

![pic](http://i.imgur.com/YaY7Z7a.jpg)

**Expected behavior:**

if I misdirect my pet and begin shooting, the enemy should target my pet and attack it, like this [Imperial Eagle](http://www.wowhead.com/npc=26369/imperial-eagle).

![pic](http://i.imgur.com/gTZ1mmj.jpg)

I've never encountered misdirect-immune mobs on retail. I don't know if there are others, or if this is just a problem of Tallhorn Stags. At first I thought this might be a problem of my pet being out of LOS or a problem with neutral (yellow) enemies, but apparently it's not.

**Comment by Exorcista** [comment]
I was about to make a report of this, i think it has something to be with the glyph, mob just ignores the "redirected" target.

**Comment by Tj20** [comment]
In the case of the Tallhorn Stags it's not the glyph... they go straight to me, no matter if I use [Glyph of Misdirection](http://www.wowhead.com/spell=56829/glyph-of-misdirection) or not. 

That being said, I don't know if there's also a problem with the glyph, I just learned Misdirection and the glyph 2 hours ago and noticed that it doesn't quite seem to work in every case.

**Comment by Tj20** [comment]
Just to be clear: do you think the glyph is bugged? What mobs exactly do you have problems with?

**Comment by Exorcista** [comment]
@Tj20 sorry for being late lol, mainly beasts didnt happened on any regular mob as i recall, i mentioned glyph because somethimes i just spam it and maybe it makes the aggro reset too fast and the comand doesnt have time to respond idk haha, but i think its close to it, and also when it bugs the beast shows wild ammount of aggro in the blizzard ui like 4 figures numbers or 5 somethimes

**Comment by Bloodbane007** [comment]
i been having this weird problem with the misdirection ability, that if i use misdirection 1 time it works but if i use misdirection before the 3 segs pass then the cooldown for the ability locks and i cant use it again unless i log out or enter an instance, wen i try to use it the game tells me that the abilty isnt ready . btw the problem happens with and whitout the gylp.

**Comment by Jenovas** [comment]
This is most probably an NPC bug not spell bug. Please create a new report that the NPC immunities it shouldnt have.
