### ISSUE TITLE
[En][Herbalism] Azshara's Veil

### ISSUE THREAD

**Issue by shadryana** [Atlantiss/BugTracker#2814]
Azshara`s Veil should be a common herb found in the waters of cataclysm zones, like in the link below 

http://www.wowhead.com/item=52985/azsharas-veil

, but as far as i can tell it can only be found in tol barad, which makes the herb kind of rare and very expensive on auction house.
now...i know this is not much of an issue, but it would be nice having this profession balanced :D

**Comment by Morrdok** [comment]
Confirm, 3 of them i found in lake at Mount of Hyjal. When checked Shimmering Expanse, Abyssal Depths, Kelp'thar Forest, they were not there. In Uldum don't saw pools for fishing

**Comment by armano2** [comment]
duplicate: #3335
