### ISSUE TITLE
[EN][Proffesion] Dun Garok dig site is bugged

### ISSUE THREAD

**Issue by Tokojiro** [Atlantiss/BugTracker#2818]
When I dig in Dun Garok and reach the green indicator, it shows me to go in a direction adn digg there, and when I digg 1meter further, it tells me to go back and so on....
![wowscrnshot_032815_122016](https://cloud.githubusercontent.com/assets/11329640/6880653/cae482f4-d545-11e4-989b-b264b1ceb0a0.jpg)

**Comment by monibu** [comment]
Dig on the upper floor.

Close the topic, digsite works fine
