### ISSUE TITLE
Shattered Hall Dungeon Crashes the game/computer

### ISSUE THREAD

**Issue by Creeo** [Atlantiss/BugTracker#2821]
Everytime me and my friends are playing the "Shattered Hall" dungeon
http://www.wowhead.com/zone=3714/the-shattered-halls and get to a specific point in the dungeon (right after the first boss http://www.wowhead.com/npc=16807/grand-warlock-nethekurse  and when you walk up those stairs to see loads of orcs standing in an attack formation http://www.wowhead.com/zone=3714/the-shattered-halls#screenshots:id=130106 and when you walk up to them and then two orcs comes out from no-ware to attack you and then) it crashes the game so badly that 3/4 of my friends computers crashes, including mine. So it would be greatly appreciated if this was fixed as soon as possible :)

Love your work, stay awesome.
-Creeo

**Comment by Wojowniczka** [comment]
ur PC crashes? so it shut down? or ur and ur friends WoW client crashes?

**Comment by Bildo** [comment]
dupilcate

**Comment by Creeo** [comment]
@wojowniczka the computers freeze and we are unable to do anything, and we got a black screen so I would conider it a crash yes
