### ISSUE TITLE
[PL][NPC] Bwemda

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2822]
Po wzięciu questa: http://www.wowhead.com/quest=29219 zostaje na mnie rzucony jakiś spell. Wizualnie widać cast, jednak podczas podróżowania po STV nie podąża za mną NPC http://www.wowhead.com/npc=52234/bwemba co blokuje mi dalszą możliwość wykonywania chaina.

Z tego co wiem, to inne osoby były w stanie zrobić tego questa, więc może być to problem indywidualny bądź rasowy. Postać Satha (Goblin shaman).

PS.: Problem znika po śmierci, jednak nie jest to rozwiązanie blizzlike.
PS2.: Problem znika tylko na jakiś czas, po krótkiej podróży mountem postać znowu się zgubiła, trzeba było ponownie paść.

**Comment by Giq** [comment]
Fixed in rev 4379
