### ISSUE TITLE
[PL] [Item] brak S4 DK u vendora

### ISSUE THREAD

**Issue by mimaxpl123** [Atlantiss/BugTracker#2824]
Nie można kupić setu http://www.wowhead.com/itemset=-416/brutal-gladiators-dreadplate u vendorów którzy powinni go sprzedawać
http://www.wowhead.com/npc=12785/sergeant-major-clate
http://www.wowhead.com/npc=30885/blazik-fireclaw
http://www.wowhead.com/npc=20278/vixton-pinchwhistle

**Comment by FakeMarcin** [comment]
Setu pod DK nie ma,Dk nie istnial na TBC,malo tego juz topiki o tym sa takze...

**Comment by mimaxpl123** [comment]
Set DK został dodany wraz z DK, chyba że czytam informacje o nieistniejącym secie z opiniami od nieistniejących ludzi. Komentarze na temat setu są najwcześniej od patcha 4.2.2 więc jestem pewien że nie wyssałem możliwości istnienia tego z palca, poza tym akcesoria od setu są dostępne.

**Comment by Karagrath** [comment]
Nie ma ogólnie itemów z s4... więc tu nie chodzi tylko o DK...

**Comment by FakeMarcin** [comment]
pisalem request,jak inni o set s4 dla innych klas ,wciaz jak nie ma tak nie ma
