### ISSUE TITLE
[PL][Quest][Storm Peaks] The Reckoning

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#2825]
Po otrzymaniu questa i dotarciu na miejsce (Temple of Wisdom) nic się nie dzieje, nie pojawiają się NPC.
link do questa: http://www.wowhead.com/quest=13047/the-reckoning
tak powinno być: https://www.youtube.com/watch?v=TO0YeqW1eRw

**Comment by Bildo** [comment]
jak doszedles do questa skoro nie dziala Krolmir, Hammer of Storms ?

**Comment by Veruca1320** [comment]
zależy od kiedy nie działa :) ja już od dawna mam dostępny quest "The Reckoning" i od dawna nie działa. Teraz poprostu go zgłosiłam.

**Comment by Bildo** [comment]
ohh przepraszam, doszłaś :) naprawie go na dniach

**Comment by Bildo** [comment]
fixed
