### ISSUE TITLE
[ENG][Item]Vicious Gladiator's Felweave Handguards

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#2827]
On the item it says Equip: Reduces the cooldown on your Demonic Circle: Teleport spell by 5 sec. but then it didn't. It's season 9 but this one say season 11 for example: http://www.wowhead.com/item=73487/cataclysmic-gladiators-felweave-handguards#dropped-by

**Comment by Milton3450** [comment]
Works for me? Normal CD is 30 sec. I have 21 sec CD with handguards and glyph (4 sec + 5 sec reduce).

**Comment by ShockRW** [comment]
Works for me as well.

**Comment by Jenovas** [comment]
Please remove cache, put item off/on it should work.
