### ISSUE TITLE
[PL][Item]Instant Statue Pedestal

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#2828]
http://www.wowhead.com/item=54212/instant-statue-pedestal

Ta zabawka z vote shopu nie działa.

**Comment by Daknyas** [comment]
Duplicate 
https://github.com/Atlantiss/BugTracker/issues/2796

**Comment by Haz3L** [comment]
Super, że zamknięte, ale może by zostało w końcu naprawione skoro item jest w sklepie, a ja wydałem na niego punkty i nie tylko ja :>
