### ISSUE TITLE
[EN][Quest] To the Digsite

### ISSUE THREAD

**Issue by Fabsik** [Atlantiss/BugTracker#2830]
The new quest chain in Stranglethorn has a bug. The quest called "To The Digsite" does not have an ending npc to turn the quest into at the digsite. The question mark is there in the mini map, but there are only digsite zombies in the digsite, no ending npc.

http://www.wowhead.com/quest=29133/to-the-digsite

**Comment by Veruca1320** [comment]
confirm!

**Comment by Veruca1320** [comment]
You turn the quest to Bwemba, so just keep an eye to her. Be sure she fallows you. If you used fly master - go back for Bwemba.

**Comment by Fabsik** [comment]
Bwemba like flies with me also did not include the quest

**Comment by Veruca1320** [comment]
i just finished "To the Digsite" so it's not bugged

**Comment by Fabsik** [comment]
my bad quest working
