### ISSUE TITLE
[PL][NPC] Baron Revilgaz

### ISSUE THREAD

**Issue by Fabsik** [Atlantiss/BugTracker#2832]
Brak NPC-a http://www.wowhead.com/npc=2496/baron-revilgaz co daje questa http://www.wowhead.com/quest=29252/booty-bays-interests  przez co nie można skończyć chaina http://www.wowhead.com/quest=29100/bwembas-spirit

**Comment by Veruca1320** [comment]
potwierdzam!

**Comment by Bildo** [comment]
a ja nie potwierdzam, nie potrzebujesz http://www.wowhead.com/quest=29252/booty-bays-interests tego questa aby skonczyc http://www.wowhead.com/quest=29100/bwembas-spirit dodatkowo gdy skonczysz bwembas spirit wrocisz do normalnej fazy gdzie http://www.wowhead.com/npc=2496/baron-revilgaz bedzie stał
