### ISSUE TITLE
[EN][Talent][Hunter][Lock&Load]

### ISSUE THREAD

**Issue by mitim1** [Atlantiss/BugTracker#2835]
Though we have a new patch 4.3.4 we stayed with old(pre 4.3.4) internal cooldown of lock and load proc.

--------------------------------------------------------
It should be 10sec.icd ,proofs how it should be:

1)article from elite jerks:

http://forums.elitistjerks.com/topic/109771-cataclysm-survival-hunter/page-27

"It appears the reduced ICD of LnL made it to live. (looks like 10-12 seconds as opposed to the old 22 sec icd)"

2)Hunter pov

https://www.youtube.com/watch?v=UNn_jat-kyA

we can notice that lnl trig in :
4:18->4:31->4:41 so there are first 13 then 10 sec space between lnl trigers.

3)Wowiki article about lnl

http://www.wowwiki.com/Lock_and_Load

Here lnl is considered as a passive but its clearly says that "it cannot occur more often than once every 10 sec" , when on 4.0.1 "patch this effect has a 22 sec cooldown"

-------------------------------------
Unfortunalty I can't make a movie how it looks atm on atlantiss,
but its really easy to test:

1)we should open ingame stopwatch
2)use black arrow on dummy when lnl procs start stopwatch
3')when our lnl just trigered after 10sec our ice trap should trig another lnl proc (ice trap have 100% chance to do that)
   it wont work beouse of wrong icd
3")when we use our ice trap around 20 sec it have 1sec arm time it will trig lnl.

It is very major issue for hunters survi

**Comment by Wulgarny** [comment]
Sup! 
 I've tested LnL proc today... aaaaand it's damn right; ICD is like old 4.0.1 patch - 22sec. 
After all this hunter nerfs and this insane major issue with our most important talent Survival Hunters are unable to play. My life has changed; even SPriests can overtake SHunters in dps atm. I had thoughts of suicide when warriors were upon me on recount. I feel like my hunter is incomplete, it's like prot warrior w/o a shield, like Blood DK w/o runes, like Nutella w/o chocolate. 
All the hunters around ATS unite! Be strong in these difficult times - we'll return in a blaze of glory! 
Dear ATS Staff, hear cry of hundreds hunters! Help us! 
Signed sincerely, the saddest hunter ever :c

**Comment by Pietras11** [comment]
Hello guys, I've tested this today on dummies for about hour, using addons like TellMeWhen, SexyCooldowns and simple my phone timer and I totally agree with author of this topic. It's still on 22sec internal cd.
 Another sad hunter ask for fix. 
Cheers !

**Comment by Giq** [comment]
Fixed in rev 4379
