### ISSUE TITLE
[PL][Enchanting] Abyssal Shatter

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#2836]
http://www.wowhead.com/spell=69412/abyssal-shatter#taught-by-npc

UPDATE
Poprawka, mają recke, ale dostępna od 445, powinna być dośtępna od 390

**Comment by Wolffenstein** [comment]
Requires only 390 enchanting currently on live servers. EDIT: Turned yellow at 400, green at something beetween 405-408 (don't remember), gray at 410.
Last edited by rutsis on 2012/09/23 (Patch 5.0.5)

Wygląda na to, że dopiero w MoPie Blizz zmniejszył wymaganie do skilla.

**Comment by Varchord** [comment]
Ok
