### ISSUE TITLE
[ENG][Quest]Drive-By-Piracy

### ISSUE THREAD

**Issue by eyeore** [Atlantiss/BugTracker#2837]
Hello :D
So as said there's an iddue with this quest : 
when you speak to the NPC "Bloodsail Oarsman" , he let you jump into a boat with a cannon "Ol'blasty"
to shoot down [75xVenture Co. Oil Worker] . The problem is that when you jump on the boat you're under water you can aim but your aiming won't do a thing and you can't slain any Venture Co. Oil Worker .

**Comment by Daknyas** [comment]
https://github.com/Atlantiss/BugTracker/issues/360
