### ISSUE TITLE
[PL] [NPC] Aeonaxx 

### ISSUE THREAD

**Issue by sylas88agreas** [Atlantiss/BugTracker#2839]
Hunter siedzac na Aeonaxxie nie moze do niego strzelac, moze bic jedynie melee.

http://i.imgur.com/J3lvghS.jpg?1

a powinno wygladac tak 

https://www.youtube.com/watch?v=0vsja8vwj_Q

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/840
