### ISSUE TITLE
The Pride of Kezan

### ISSUE THREAD

**Issue by Silvijn** [Atlantiss/BugTracker#2841]
In the openingstory of the goblins, you get a quest at around aproximately level 11, It's called The Pride of Kezan. 
You have to fly into the air with a flying machine and snipe goblin stealth choppers, but I can't seem to manage to get up into the air.
Please help me, it's quite an issue and i cant really skip it.
Thanks for your help

Silvijn

**Comment by Navedonar** [comment]
bt rules
