### ISSUE TITLE
[EN][Battleground] Spirit healer not ressing

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#2842]
There's a bug where the spirit healer doesn't res u. And it has nothing to do if you own the graveyard because it happens in WSG too. You are stuck at "1 second remaining" and you don't get ressed.

http://i.imgur.com/KpgoieM.jpg

**Comment by Bildo** [comment]
that's because you pressed esc

**Comment by Milton3450** [comment]
It doesn't help to press "cancel" and right click on the spirit resser again. It will get stuck at 1 second again.

**Comment by Maczuga** [comment]
You do not have a ressurection buff. Leave the ress area and press Return to Graveyard and it'll be back.

**Comment by Milton3450** [comment]
Ok, I might try that.

**Comment by xmesaj2** [comment]
Also sometimes if you fall under map textures, you will die and keep falling without being placed in graveyard, /script RepopMe() helps but there might be players that don't know it and leave battleground instead.

**Comment by PVPViddys** [comment]
This happens to me all the time. If you cancel your res and then interact with the spirit healer, the bug will occur. Interacting with healer only gives you the resurrection buff for about a second, so in order to res, I need to time it right so I have the buff exactly when the spirit healer rezzes.

**Comment by karama300** [comment]
Important thing for fix!

**Comment by fruvel** [comment]
the spirit healer don't ress when you talk to him always when time to resurrection down, other players are ressurected but me not. You must go to the corpse ... ;/

**Comment by xmesaj2** [comment]
@fruvel jump out of his range then use "teleport to graveyard" it should work after that

**Comment by Jenovas** [comment]
Fixed in rev 5247
