### ISSUE TITLE
[EN][Northern Stranglethorn][Quest]Bwemba's Spirit(ID 29100)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#2849]
Quest should be completed when you complete quest [Making Contact](http://www.wowhead.com/quest=29152/making-contact)(#2786) but it does not right now.

Wowhead link:[Bwemba's Spirit](http://www.wowhead.com/quest=29100)

How it should work: https://youtu.be/cadPgORZh5A?t=991

**Comment by Giq** [comment]
Fixed in rev 4379
