### ISSUE TITLE
[EN][PVP] Honor is not granted properly

### ISSUE THREAD

**Issue by KlawiszQ** [Atlantiss/BugTracker#2850]
Every single kill should grant 9 honor points evenly split among people involved in combat (healers and damage dealers). Currently it gives only 1 honor point even when you kill enemy alone.

**Comment by Jenovas** [comment]
Links? Anything?

**Comment by KlawiszQ** [comment]
I found it hard to prove but i'll have to help myself with some screenshot and a post sadly written while MOP was live, but the honor point system has not changed since 4.0 patch 

http://eu.battle.net/wow/en/forum/topic/7257056493

Basiclly you should be awarded a 9-10 honor points for a kill when enemy was at the same level, evenly split among everybody taking part in the fight, in addidion outside BG every consecutive on this same opponent should award less honor

It may be non-professional but we can look at old cataclysm montages for e.g.

https://www.youtube.com/watch?v=6WlF-hmpwCI

https://www.youtube.com/watch?v=snS5lZmjq1k [Low quality but still able to see how much honor he recives]

You can see how often the mage recives honor points and what amount, pretty much here on Atlantiss you never recive more than 1 HP, even when you kill enemies alone outside BG. We can even see on scoreboard that people end BG with 500+ HP 

I played through whole cata on retail and just felt like gaining honor here is not right, tol barad gives enormous amount while pvp kills gives nothing, Tol Barad rewards should get a closer look as well.

**Comment by MasterK15** [comment]
Thats true ,each flag cap or 330 pkt on base holding bg should be 40 honor for everyone (in party that cap or gain points) each 100pkt lostby oposing fraction on av and ioc should be 100hp for everyone.

**Comment by michal1441** [comment]
I did a research on the subject and here is what I found. Info on amounts of honor gained was hard to prove so I took a closer look at the videos from patch 4.3 where we can observe the amounts of honor gained. 

Randon Battleground awards: 130 honor and 50 conquest points per win (270 honor and 100 conquest points on the first win of the day), 45 honor per loss

Honorable kill - 10 honor (split evenly between the players who are close to the target)
Source: https://www.youtube.com/watch?v=bGMbz-Op_HU
	http://eu.battle.net/wow/en/forum/topic/7257056493

These awards go to all the participants:

Warsong gulch:
- capturing the opponent's flag awards 18 honor
- win awards 45 honor
Source: http://www.wowwiki.com/Warsong_Gulch
	https://www.youtube.com/watch?v=Z7avhqEZPHE

Arathi Basin
- Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
- win awards 18 honor 
Source: http://www.wowwiki.com/Arathi_Basin
	https://www.youtube.com/watch?v=yoi_m9bM9zU
	
Eye of the storm
- Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
- win awards 27 honor
Souce: http://www.wowwiki.com/Eye_of_the_Storm
	https://www.youtube.com/watch?v=pj1I2d9gvVs

Twin peaks
- capturing the opponent's flag awards 18 honor
- win awards 45 honor
Source: https://www.youtube.com/watch?v=0GUKi4ZmTS4

Alterac Valley
- tower destruction awards 27 honor
- captain kill awards 27 honor
- general kill awards 36 honor
- alive captain at the end awards 18 honor
- undestroyed tower at the end awards 18 honor
Source: http://www.wowjuju.com/honor-and-battleground-explained-20071220 (1 kill was swapped with 9 honor during cata, videos are the proof)
	https://www.youtube.com/watch?v=NE1n8-gEgIw

Battle for Glineas:
- Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
- win awards 18 honor
Source: https://www.youtube.com/watch?v=hX1xybZlQzU

Strand of the Ancients:
- destroying a gate awards 9 honor
- successfuly ending a round before the time ends (if attacking)/succesfully defending the Relic for the whole round awards 9 honor
- win awards 27 honor
Source: https://www.youtube.com/watch?v=S77logRcPpo

Isle of Conquest
- destroying a gate awards 18 honor
- win awards 36 honor
- controlling Rafinery and/or Quarry provides "a constant flow of honor" (2 honor per tick as seen in a video)
Source: https://www.youtube.com/watch?v=7qQQcTAOur0
	http://www.wowhead.com/zone=4710/isle-of-conquest#comments
	https://www.youtube.com/watch?v=-Kku9GoIswA

If anyone has a better source or any corrections feel free to update this!

**Comment by MasterK15** [comment]
DUMP
