### ISSUE TITLE
[PL] [Deepholm] Therazane

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#2860]
![image](https://cloud.githubusercontent.com/assets/8699987/6896642/d3c2a9b0-d6ed-11e4-917f-43eefc0e82d0.png)
nie ma npc królowej deepholmu 
http://www.wowhead.com/faction=1171/therazane

**Comment by Ranor** [comment]
Npc jest już na miejscu.

**Comment by arekczup** [comment]
ok

**Comment by Tj20** [comment]
Does this mean the "Therazane falling through the floor" issue was fixed? Because there are still some open bug reports about this: #2905, #2542, #2503, #1794(?)
