### ISSUE TITLE
[PL][QUEST][AZSHARA]Smoot's Samophlange

### ISSUE THREAD

**Issue by Gustawas** [Atlantiss/BugTracker#2862]
http://imgur.com/sX3mNx4
Gdy klika się na tego Smoot'a to wyskakuje kominikat: "Must be in Battle Stance".
Jak wiadomo tylko warke posiada Stance'y, więc q jest nie do zrobienia dla innych klas.

Pisze tego posta bo podobno naprawiliście pre chain hordy do th. Jak widać nie wszystko.

http://wow.gamepedia.com/Quest:Smoot%27s_Samophlange - stronka do questa
https://www.youtube.com/watch?v=kdU1iK5Re4o - filmik do questa

**Comment by Wolffenstein** [comment]
Prechain do TH nie jest skończony.
