### ISSUE TITLE
[ENG][Professions][Fishing][Achievement] The Lurker Below

### ISSUE THREAD

**Issue by badpollo** [Atlantiss/BugTracker#2863]
The Strange Pool in Serpentshrine Cavern is submerged too far down and is unable to be fished from. I have heard of people finding minimal success in out of the way locations, but personally have not had success. Please fix this (or if anyone has manageable solutions, that works too).

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1795
