### ISSUE TITLE
[PL] [Quest] [Durator] Call Of Duty

### ISSUE THREAD

**Issue by Galexia** [Atlantiss/BugTracker#2865]
Witam. Mam takowy problem.
Zrobiłem to http://www.wowhead.com/quest=28816/to-the-depths.
z tego co pamiętam, ale ciągu dalszego nie ma czyli tego http://www.wowhead.com/quest=25924/call-of-duty
Może ja coś zle zrobiłem nie mam pojęcia. Dlatego prosił bym o sprawdzenie i danie odpowiedzi.
W miare jak najszybciej gdyż aktualnie stoję w miejscu z questami i nie mam przez to portalu do tejże lokacji. (Vashj`ir)
Z góry dziękuję i pozdrawiam.

**Comment by nerv234** [comment]
Ta kraina jest zamknięta, nieoskryptowana, i nie jest planowana do ukończenia w najbliższej przyszłości, dlatego musisz wybrać Hyjal.

**Comment by Galexia** [comment]
Aha to dzięki ;) za info
