### ISSUE TITLE
[EN][Druid] Skull Bash (both cat and bear)

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#2867]
basically, when your SB is dodged, parried, blocked or you miss it, the charge doesn't happen.
when u miss or get dodged/blocked/parried on skull bash, the charge should still happen, "teleporting" you to your target anyway. Of course, the charge shouldn't happen if you would be immobilized.

**Comment by Jenovas** [comment]
I think that effects such as Skull Bash (interrupt) should never miss.
Can you check if it's a miss or is it a  parry / dodge / block?

**Comment by Isuel** [comment]
well, the interrupt itself shouldn't miss, and that's working. Only the debuff from improved skull bash should miss, and the charge should happen anyway unless u're immobilized

**Comment by razgal** [comment]
Any type of interrupt shouldn't be EVER missed/blocked/parried

Proof:
http://eu.battle.net/wow/en/game/patch-notes/4-1-0
"All non-damaging interrupts off the global cooldown will now always hit the target. This includes Pummel, Kick, Mind Freeze, Rebuke, Skull Bash, Counterspell, Wind Shear, Solar Beam, Silencing Shot, and related player pet abilities."

**Comment by Isuel** [comment]
I don't remember where I read (it was when cata launched or about then) that the mana cost debuff from improved skull bash can miss.

**Comment by Isuel** [comment]
either way, i just want to be able to still charge even if they parry, dodge or block or if i miss. best example would be against a hunter who just used deterrence.

**Comment by razgal** [comment]
yes if the target its in immune/detterence the kick effect shouldn't work through it,  but the pathing of SKull Bash yes.

**Comment by Dean1989** [comment]
i want to add that if you use skull bash when snared the skill goes in cd, i think it shouldn't since you can't use it when immobilized

**Comment by Jenovas** [comment]
"i want to add that if you use skull bash when snared the skill goes in cd, i think it shouldn't since you can't use it when immobilized" - you can use it if your target is less than I think 7 yards away from you. The charge doesnt happen BUT you still stop the cast if someone was casting something.

**Comment by Fearyourself** [comment]
Are there some ETA on this? Skull bash can still be dodged...

**Comment by Jenovas** [comment]
Fixed in rev 4549
