### ISSUE TITLE
[EN] [QUEST] [DESOLACE] "Early Adoption"

### ISSUE THREAD

**Issue by Jackalantern** [Atlantiss/BugTracker#2872]
This quest involves you laying down an egg at a nest at the quest location provided, fighting off a couple waves of mobs to ensure the eggs health. After you defeat these waves a "Defiant Swoop" is supposed to appear and take the egg, thus giving you credit for quest criteria, which is protecting 3 eggs.

At the moment of writing I am able to lay down the egg just fine, and the mobs and waves behave as they should and can be defeated. But no swoop ever appears to carry off the egg and no criteria can be currently met.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1492
