### ISSUE TITLE
[EN][Druid] Clearcasting vs. Ravage

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#2873]
When you have Clearcasting proc (from omen of clarity) it shouldn't consume your Ravage if you used Feral Charge.

Proof:
http://www.mmo-champion.com/threads/801783-%E2%80%A2Ravage
"It means that if you use Feral Charge with 2/2 Stampede your next Ravage will not consume the clearcast effect. Since the Ravage is free to begin with due to the talent it just doesn't consume the clearcast (which would make it free either way). Just a minor bug fix on their part. It should still benefit from Tiger's Fury as it normally would."

**Comment by Isuel** [comment]
confirmed

**Comment by Jenovas** [comment]
Fixed in rev 4549

**Comment by razgal** [comment]
a question is this live right now?

**Comment by Kejmil** [comment]
http://atlantiss.eu/changelog

**Comment by razgal** [comment]
because ia not working on live atm.

**Comment by Jenovas** [comment]
http://atlantiss.eu/changelog - rev. 4549 Waiting for update - so no it is not live
