### ISSUE TITLE
Transmog wont work for me

### ISSUE THREAD

**Issue by Sthibodeaux** [Atlantiss/BugTracker#2876]
I'm a level 54 hunter with an assortment of green,blue, and epic items, all mail and whenever I interact with the transmog guy, it opens the character gear window, but there are no arrows next to any of my gear and I can't select anything. I definitely can afford it, and I also have multiple items of the same material in my bag. thanks!

**Comment by Varchord** [comment]
There should be green arrows? I thought it's just drag and drop
