### ISSUE TITLE
[EN][Quest][Darkshore] The Ritual Bond

### ISSUE THREAD

**Issue by azuresky2** [Atlantiss/BugTracker#2877]
The insence does not appear in front of Keeper Karithus (the quest giver) while it should. Therefore, quest cannot be completed.

http://www.wowhead.com/quest=13569/the-ritual-bond

**Comment by Wolffenstein** [comment]
So... what's this? http://scr.hu/3jjl/6zn9q

**Comment by azuresky2** [comment]
yeah I just played again and it has appeared now. I dont know why

**Comment by Wolffenstein** [comment]
I'm gonna assume you had a client bug.
