### ISSUE TITLE
[PL][Spell] Cultivation

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2878]
http://www.wowhead.com/spell=20552/cultivation#comments

Taureni powinni zbierać kwiatki znacznie szybciej niż pozostałe rasy. Czas zbierania powinien wynosić 0.5sek zamiast 2.

![wowscrnshot_040115_124139](https://cloud.githubusercontent.com/assets/544349/6939394/92b2d55a-d86c-11e4-9417-80d8510c7fcd.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1497
