### ISSUE TITLE
[EN][Quest] The Art of persuasion

### ISSUE THREAD

**Issue by sargoth** [Atlantiss/BugTracker#288]
When I use the quest item on the npc my client crashes.http://www.wowhead.com/quest=11648

**Comment by Hordraric** [comment]
this crash also happens in 4.3.4 had it today too

**Comment by Athinira** [comment]
Had the same issue today. I crashed 2 times while using "Neural Needler".

**Comment by Bildo** [comment]
try without pressing 'esc'

**Comment by Rushor** [comment]
removing the triggered flag from the spellatributes probably helps here

**Comment by Athinira** [comment]
gonna try later today and edit this post.

**Comment by armano2** [comment]
#2281

**Comment by kzlatkov** [comment]
Had the quest in my Quest log not working for 2-3 weeks, then suddenly i've decided to go back there and try it out once again. I have written a ticket to the GM's and don't know if this was the reason, but the quest did work! FROM the first time. I've just stood 2-3 yards away from the sitting prisoner, and i have noticed that there is another one next to him, showing his name in green (friendly). So went between them both (prisoners - friendly and unfriendly) DID NOT TARGET EITHER OF THEM. Pressed the Quest item and it worked. The unfriendly prisoner then starts a monologue everytime you press the Q item. After 5-6 repeats the Q is complete! Good Luck.
