### ISSUE TITLE
[PL]Hit rating Special Attacks

### ISSUE THREAD

**Issue by hunter153** [Atlantiss/BugTracker#2880]
Hit rating dla ataków specjalnych wynosi 8%. Mam rogue'a i pomimo tego, że mam 15,03% hita melee to missuję z Mutilate, Backstab i Evenom. 
Screen:
http://oi61.tinypic.com/2e3bel3.jpg

**Comment by Lenox07** [comment]
A z jakiej walki masz tego recounta? Bo bijąc kukłe z 14.98% hit nie miałem missow na wyżej wymienione skille.

**Comment by Kejmil** [comment]
pewnie chimeron...

**Comment by hunter153** [comment]
Z chimaerona.

**Comment by Varchord** [comment]
Chimaeron rzuca czasem debuff zmniejszający hit chance.
IMO do zamknięcia
