### ISSUE TITLE
[PL][Quest][Stonetalon Mountains] We're Here To Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by Saranai** [Atlantiss/BugTracker#2881]
http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two

Nie da się oddać questa, co uniemożliwia wykonanie całego głównego quest line'a dla Stonetalon Moutains.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/906
