### ISSUE TITLE
[PL] [SPELL] [PALADIN] Hand of Sacrifice

### ISSUE THREAD

**Issue by Sillmarien** [Atlantiss/BugTracker#2883]
Obrażenia przekazywane na naszą postać za pośrednictwem ww. spella nie przerywają efektów crowd control takich jak blind/repentance itd, które powinny być przerywane po otrzymaniu obrażeń.

Hand of Sacrifice id http://www.wowhead.com/spell=6940/hand-of-sacrifice#comments

"This can also be used to free yourself from CC in PvP. Works best on sap/repentance/sheep as those break instantly when you take damage. Timing it is not easy, but it's extremely useful." komentarz z wowhead'a

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2146
