### ISSUE TITLE
[EN] [Warrior] [Spell] Shield Slam

### ISSUE THREAD

**Issue by PVPViddys** [Atlantiss/BugTracker#2888]
Shield Slam does not take player's crit rating into account and is unable to crit when unbuffed and with no talents affecting crit.

Tested on dummy with 100+ Shield Slams, and with 4.5% melee crit chance, it did not crit.

With the Cruelty talent, Shield Slam will crit 10% of the time, but it still doesn't take player's crit rating into account.

**Comment by Kejmil** [comment]
perhaps bugged in the same way that https://github.com/Atlantiss/BugTracker/issues/2359 was?

**Comment by Varchord** [comment]
That's nothing not true. Ss is critting without talent using just your crit rating. I'm speaking from experience.


Besides 4.5% crit chance is too low to assume its not working after only 100 hits

**Comment by Jenovas** [comment]
Crit Suppression vs boss level enemies is 4.8%, so with 4.5% you have -0.3%, no wonder you dont crit. 
Closing.
