### ISSUE TITLE
Guild abilities disappear

### ISSUE THREAD

**Issue by Sthibodeaux** [Atlantiss/BugTracker#2889]
After placing Mass ressurection, Have Group Will Travel, or any other guild abilities (level 25 guild) they are removed upon my next login. A minor issue, just thought I'd bring it up.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/219

**Comment by nerv234** [comment]
Pro tip: make a macros with this abbilities, macros won't dissapear.
