### ISSUE TITLE
[EN][Area][NPC] Murlocs missing in Elwynn Forest

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#289]
There's this little island in Elwynn Forest with a lot of murloc huts.

![wowscrnshot_111714_103403](https://cloud.githubusercontent.com/assets/9798968/5067825/3af60484-6e47-11e4-9159-d68499ff9968.jpg)

It should have murloc lurkers (http://www.wowhead.com/npc=732) and murloc foragers (http://www.wowhead.com/npc=46) on it, but they are all missing from this island.

**Comment by Quban** [comment]
fix soon
