### ISSUE TITLE
[EN][Guild] Reputation

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#2890]
So if you leave your current guild you will lose all rep, but when you re-join the same one you start again from 0 (neutral). 

How it should work: If you re-join guild you should get back reputation which you had before leaving
http://eu.battle.net/wow/en/forum/topic/981628729

This happen to me ( and no i didn't join any guild in the meantime i was w/o guild )

**Comment by Varchord** [comment]
I was wondering if it's working. But i didn't want to lose my rep ;P

**Comment by xolon** [comment]
qq i want my rep bak

**Comment by krecik88** [comment]
Note that upon joining a different guild, your Guild reputation is knocked down a level - if you had reached Exalted with your previous Guild, you will drop to Revered with your new Guild."
this was implemented im MOP

actualy i'm trying to reproduce bug, but on my offline realm it always works, even if char is kicked by GM or is removed by itself. so it may tak some time to figure it out

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/7033
