### ISSUE TITLE
[EN][QUEST][Blasted Lands] You Are Rakh'likh, Demon

### ISSUE THREAD

**Issue by Exorcista** [Atlantiss/BugTracker#2898]
Quest link: http://www.wowhead.com/quest=26171/you-are-rakhlikh-demon

Not much wrong with the quest just this:

![wowscrnshot_040215_134811](https://cloud.githubusercontent.com/assets/6818405/6970498/ad9570b6-d93f-11e4-8cea-f946d4d08683.jpg)

Loramus the Defiled spawned like 9 times in the top (were you get teleported) wich attack as soon as you teleport and kill you, i had to jump down and heal myself till i got out of combat. I couldnt complete the quest because of this.

<b> Video of how should it work: https://www.youtube.com/watch?v=tCs6R3TCm50</b>

Also the rune of return doesnt work unless a gm decides to help you or a gmate of higher lvl :S

**Comment by Wolffenstein** [comment]
Well, the quest is supposed to be the last from the chain, but the quests in the zone aren't linked together, so it isn't blocking anything at the moment.

**Comment by Varchord** [comment]
Did you got lazy? :P

**Comment by Exorcista** [comment]
Feedback here, yea its supossed to be the last i know anyways i managed to get a gmate to help, we cleared them all and of course i got my quest jeje

**Comment by nerv234** [comment]
Bad zone name in issue name.

**Comment by lourrific** [comment]
http://www.wowhead.com/quest=26171/you-are-rakhlikh-demon

"Destroy Razelikh's body, then use the Stone Knife of Sealing to imprison his soul." 

Impossible to kill there are multiple spawns of him attacking at once he's a level 57 elite.

**Comment by Bildo** [comment]
fixed
