### ISSUE TITLE
[PL][Transmogrification] Sulfuron Hammer (epic version)

### ISSUE THREAD

**Issue by Sulfur937** [Atlantiss/BugTracker#29]
Nie da się transmogować (a powinno się dać) - wersja epicka http://www.wowhead.com/item=17193 .
Ta wersja powinna dać się normalnie transmogować - zostaje to zablokowane dopiero w patchu 5.2 (Transmogrification Changes - wtedy liczy się jako część legendarnej).

**Comment by Navedonar** [comment]
.

**Comment by TranceAccount** [comment]
On what kind of item are you transmogging the two-handed axe?

**Comment by TranceAccount** [comment]
Nevermind, I don't know how transmog is handled by core.

**Comment by Piklo** [comment]
@TranceAccount I think you have to delete / add one of FlagsExtra
https://trinitycore.atlassian.net/wiki/display/tc/item_template#item_template-FlagsExtra
2097152	0x0200000	CANNOT_BE_TRANSMOG
4194304	0x0400000	CANNOT_TRANSMOG
8388608	0x0800000	CAN_TRANSMOG

**Comment by TranceAccount** [comment]
I thought that too but 
- CANNOT_BE_TRANSMOG isn't applied to the item
- CANNOT_TRANSMOG and CAN_TRANSMOG allow the item to be transmogged over or not and not be the displayed item in game

**Comment by TranceAccount** [comment]
Cannot reproduce on PTR.
