### ISSUE TITLE
[EN][Dungeon-WotLK] The Oculus

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2900]
http://www.wowhead.com/zone=4228/the-oculus
Besides some small issues the Oculus works surprisingly well. It surely is the most hated instance of all WoW, and so I was not sure if it would even work, but it is surprisingly well scripted.

Quest: see #124

### The Dragon Mounts
These things work pretty well. You have to mount up manually and after dismounting they stick around, which means that the instance will have quite a few of your old mounts standing around after some time ([pic](http://i.imgur.com/NuXEMLa.jpg)), but they do their job. They can not move on the ground, but flying and their special abilites seem to work well. Sometimes I had trouble to leave the ground, but pressing the "jump" key only seemed to do the job.

### [Drakos the Interrogator](http://www.wowhead.com/npc=27654/drakos-the-interrogator#encounter)
- There are Unstable Spheres visible during the encounter, but their explosions seem to do 0 damage

![pic](http://i.imgur.com/A8qtTHY.jpg)

### [Varos Cloudstrider](http://www.wowhead.com/npc=27447/varos-cloudstrider#encounter)
- [Energize Cores](http://www.wowhead.com/spell=50785): Varos should fill a portion of his platform with small lightnings. The group should run out of this, because several seconds later, big lightnings would damage the group, see [video](https://youtu.be/p7bpkTx17WA?t=11m14s). This is broken at least visually: here the little lightnings hit the group members instead of the swirly things on the edge of his platform. Sometimes you get damaged by it, sometimes you don't... there's no way of knowing where the damage will happen. ([combat log](http://pastebin.com/kSagiaPd))

![pic](http://i.imgur.com/7HlJxS2.jpg)
- The [Azure Ring Captain](http://www.wowhead.com/npc=28236) should cast [this beam](http://www.wowhead.com/spell=51021) which essentially creates a moving blue fire patch on the ground which follows somebody and damages him if he stands in it. Instead he casts [this beam](http://www.wowhead.com/spell=49549/ice-beam) which seems to be invisible and slows you, so you can't really avoid it.

### [Mage-Lord Urom](http://www.wowhead.com/npc=27655/mage-lord-urom#encounter)
- doesn't cast [Time Bomb](http://www.wowhead.com/spell=51121)
- his [Empowered Arcane Explosion](http://www.wowhead.com/spell=51110) works fine, there's only a visual bug with his z-position: he should fly in the middle of the ring, but instead he falls to the ground of the dungeon

![pic](http://i.imgur.com/Y6fG1m8.jpg)

### [Ley-Guardian Eregos](http://www.wowhead.com/npc=27656/ley-guardian-eregos#encounter)
Nothing really to report here. I just wanted to express that I was surprised that this fight works here at all, and it seem to work also pretty well. My green dragon could use his life-leeching DoT and heal other players with the green beam... I'm impressed.

![pic](http://i.imgur.com/rYCd0Na.jpg)

**Comment by Aviannaqt** [comment]
Fixed in rev. 4666
