### ISSUE TITLE
[PL][Quest][Instancja] Zul'Gurub - An Old Friend

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#2901]
Witam!

Otóż pomimo zrobienia wszystkich questów w STV oraz chaina do Zandalari, w samym Zul'Gurub po ubiciu drugiego bossa, nie pojawia się mały raptorek (http://www.wowhead.com/npc=52877/lashtail-hatchling), oferujący questa (http://www.wowhead.com/quest=29208/an-old-friend), za którego nagrodą jest tenże sam raptorek. Zrobiłem wszystkie questy w STV (chaina z raptorem również, jeszcze przed wprowadzeniem chaina z Zandalari), jednak po ubiciu drugiego bossa na ZG, malec się nie pojawia.
Prosiłbym o przyjrzeniu się temu w wolnej chwili.
Z góry dziękuję za pomoc!
Rev. 4382

**Comment by Lebiedz** [comment]
BUMP. Nadal nie działa.

**Comment by Egosit** [comment]
Dalej nie działa. Proszę o naprawienie.

**Comment by CheriLady** [comment]
Dalej nie działa. Proszę o naprawienie.

**Comment by 1Andas** [comment]
Bump Still not working.

**Comment by Llagas** [comment]
This is confirmed buged, please fix it :) it would be really nice to have this companion !

**Comment by Bildo** [comment]
fixed
