### ISSUE TITLE
[EN][NPC/Quest] Wayward Child (Therazane)

### ISSUE THREAD

**Issue by gala320** [Atlantiss/BugTracker#2905]
http://oi57.tinypic.com/23vxbbo.jpg
Therazane fell under textures. She is supposed to be where the question mark on minimap is.
Proof for where she should be: http://www.wowhead.com/npc=42465/therazane
It's impossible to finish the quest.

**Comment by Varchord** [comment]
It Has nothing to do with this quest. She sometimes do that :P

**Comment by gala320** [comment]
Well, I can't finish the quest because I have to talk to her for a reward, that's why I marked it this way.

**Comment by Thefakemccoy** [comment]
Its bugged i can see her but when i click on her i get nothing to turn the quest in.

**Comment by armano2** [comment]
doubled: #3902
