### ISSUE TITLE
[ENG][NPC's]Afther you exit the camp

### ISSUE THREAD

**Issue by TheLichWarrior** [Atlantiss/BugTracker#2907]
Hello Atlantiss WoW server is best today i am playing warrior Tauren afther i start the first quest there are some little errors with the Defenders of the starting zone thay carry weapon Spear but shoot with them sometimes check the NPCs and if you can correct the quliboar's respawn times and there positions to correct little thank you.

**Comment by Varchord** [comment]
wowhead links
1 problem, 1 issue
