### ISSUE TITLE
Ashenvale quest broken

### ISSUE THREAD

**Issue by Gaurab-Chatterjee** [Atlantiss/BugTracker#2908]
Quest: Defend the tree
Quest giver: Halannia (inside building /62,51/ Ashenvale forest)
Previous quest:Recover the Fallen
Problem: After accepting the quest, player should be able to talk to the NPC
to become Shade of Shadumbra, a black panther to kill 50 enemies. This isn't the case.

**Comment by Tj20** [comment]
Thank you for considering to report bugs, but the topic already exists: #671 
Also please have a look at the [readme](https://github.com/Atlantiss/BugTracker/blob/master/README.md) (title format, wowhead link)
