### ISSUE TITLE
[PL][ROGUE] Killing Spree

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#2911]
Podczas bicia Magmawa gdy użyjemy <a href='http://www.wowwiki.com/Killing_Spree'>Killing Spree</a> (linkuje wowheada cata openwow nie działa) zostajemy teleportowani za niego i wpadamy w lawę. Jak powinno to wyglądać <a href='https://www.youtube.com/watch?v=g8saiH5nF2s'>link</a>  
2;28 killing spree uzyto na glowie magmawa 
0:15 
1:20
znalazłem jeszcze kilka komentarzy 
"Using Killing spree during non-exposed phases drops you next to the spike, so it is safe to use."
http://forums.elitistjerks.com/topic/110247-cataclysm-40x-raid-mechanics/

**Comment by Varchord** [comment]
Jak nie działa? http://cata.openwow.com/spell=51690
Swoją drogą to zlinkowałeś wowwiki, nie wowheada.

Śmieszny bug, znany bug. Dziwię się, że dopiero teraz ktoś zreportował

**Comment by Jenovas** [comment]
Fixed in rev 4509
