### ISSUE TITLE
[EN][ITEM]Reputations

### ISSUE THREAD

**Issue by antymage** [Atlantiss/BugTracker#2912]
http://www.wowhead.com/item=62366/arcanum-of-the-earthen-ring
http://www.wowhead.com/item=62367/arcanum-of-hyjal
http://www.wowhead.com/item=62369/arcanum-of-the-ramkahen

Items from those reputations are "bind on account".The problem is that you can send them to other chars but you can't use them cuz of your reputation level.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/682
