### ISSUE TITLE
[PL][ROGUE] Venomous Wounds

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#2915]
Dmg jest zbyt niski
zgodnie z formułą z http://forums.elitistjerks.com/topic/104491-cataclysm-mechanics-testing/
675+.176*AP i informacją "It crits at your usual spell crit rate, and benefits from Potent Poisons and the spell damage buff (Master Poisoner or equivalent) but not Vile Poisons"
damage powinien wynosić: (675+0,176 * 10572) * 1,56 * 1,08=4272 (pomnożone przez 56% mastery i 8% z talentu Master Poisoner
testowałem przy 10572 ap 56% mastery
 <img src="http://i.imgur.com/689Xbfb.jpg?1">

**Comment by nerv234** [comment]
Nie wiem co skąd wychodzi itd... ale w spellworku info o coefie nie da się znaleźć.

Nawiązując do danych z EJ.(i twoich cyfer) coef na 10% pochodzi z levela 80 zamiast 85 czyli 0.135 zamiast 0.176. I gdyby działał Master Poisoner to dmg powinien wynosić(z błędnym coefem) 3541.82.... Natomiast bez master poisonera ze złym coefem 3279.46....

Reasumując najprawdopodobniej Master Poisoner nie działa na ten spell jak i coef nie skaluje się chyba z levelem i jest sztywno ustawiony na 0.135 zamiast 0.176.

**Comment by Jenovas** [comment]
Fixed in rev 4416
