### ISSUE TITLE
[ENG][Quest][Grizzly Hills] We Have the Power

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2918]
http://www.wowhead.com/quest=12197/we-have-the-power

Hi, back with some wrong drop chances ;D

Wowhead lists the drop chances for the quest items at 43% and 47%, Blizzard themselves list them on battle.net at "Guaranteed" (aka 100%):
http://eu.battle.net/wow/en/item/36857
http://eu.battle.net/wow/en/item/36858

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1589
