### ISSUE TITLE
[ENG][Quest][Grizzly Hills] See You on the Other Side

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2922]
http://www.wowhead.com/quest=12121/see-you-on-the-other-side

Not working. When standing on front of the Drakil'jin Gong and trying to strike it with the "Charged Drakil'jin Mallet" (http://www.wowhead.com/item=36834/charged-drakiljin-mallet) I get the following error message:"Requires Drakil'jin Gongs".

**Comment by Bildo** [comment]
everything works
