### ISSUE TITLE
[ENG][Quest][Grizzly Hills] The Magical Kingdom of Dalaran

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2923]
http://www.wowhead.com/quest=12791/the-magical-kingdom-of-dalaran

The quest givers should have a dialogue which teleports you to Dalaran as long as you have the quest active:

http://www.wowhead.com/npc=26471/image-of-archmage-aethas-sunreaver
http://www.wowhead.com/npc=29155/magistrix-kaelana
http://www.wowhead.com/npc=29159/magister-varenthas
http://www.wowhead.com/npc=29160/magistrix-phaelista
http://www.wowhead.com/npc=29162/magister-tyrganal
http://www.wowhead.com/npc=23729/baron-ulrik-von-stromhearth
http://www.wowhead.com/npc=26673/image-of-archmage-modera
http://www.wowhead.com/npc=27158/vas-the-unstable
http://www.wowhead.com/npc=29158/magister-dathomere
http://www.wowhead.com/npc=29161/magistrix-haelenai

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/831
