### ISSUE TITLE
[pl][Spell]Envenom

### ISSUE THREAD

**Issue by nerv234** [Atlantiss/BugTracker#2924]
32645 Envenom
http://www.wowhead.com/spell=32645/envenom
Formuła na dmg przy 5cp(przy tylu testowałem tylko)+5 dp(deadly poison)
(0.45*ap+240*5)*1.2(Coup de Grace)*1.36(Vile Poisons)*1.08(Master Poisoner)*mastery
Moje ap przy testach: 8259
Moje mastery przy testach 1.62
Dmg ze wzoru: (0.45 * 8259+240*5)*1.2*1.36*1.08*1.62=14038.45
Dmg na tescie: 9672

Dziwne cyferki wychodzą, ale jakby Master Poisoner nie działał + Vile Poisons, albo wgl. zepsute liczenie dmg. Pod żadną kombinacją tych współczynników nie jestem w stanie dojść do wyniku z testu czyli 9672, nawet +-50. Ktoś mógłby pomóc w liczeniu cyferek?

Edit: Komentarz z wowheada gdzie ktoś wypisuje co wpływa na envenom:
http://www.wowhead.com/spell=32645/envenom#comments:id=1642248

**Comment by Jenovas** [comment]
Ogólnie wydaje mi się że u Nas DMG może być zaniżony bo, wszelkie mastery i talenty wpływają na bazowy DMG spella a dopiero potem jest +DMG z dp +DMG z cp.

**Comment by nerv234** [comment]
little change to Envenom DMG w revie 4394, co tam było zmienione?

**Comment by Jenovas** [comment]
AP coef był zależny od stacków Deadly Poison a powinien od CP.

**Comment by Jenovas** [comment]
Fixed in rev 4416
