### ISSUE TITLE
[EN] [Talent-Priest] [Masochism]

### ISSUE THREAD

**Issue by Jackalantern** [Atlantiss/BugTracker#2925]
The Shadow Word: Death portion of this talent says that if the spell ends up damaging you, aka it is not a killing blow, then you are supposed to return 5/10% of your mana. Currently this is slightly bugged. I've noticed that if my Shadow Word: Death brings the target down to close to death (around 1% health, perhaps just slightly more), but doesn't actually kill them, then I will receive no mana back.

There is some sort of an issue with it being so close to the mobs last bit of health. But obviously this shouldn't happen. If the mob doesn't die from it, then I should receive my mana back regardless of how close to death the target is.

**Comment by Varchord** [comment]
http://cata.openwow.com/spell=88995
http://cata.openwow.com/spell=32379
links mate

**Comment by Jenovas** [comment]
From what I see the talent works this way - If caster gets damaged from SW : D you will get mana back, BUT SW : D deal backlash damage after 1 sec, so if your target dies in this 1 second the backlash DMG wont happen so no mana gets returned, and this seems to be a Blizzard feature.
