### ISSUE TITLE
[PL][NPC] Solid Ice

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2926]
Ten npc nie powininen nas atakować ani się obracać: http://www.wowhead.com/npc=49233/solid-ice

**Comment by Rithelight** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1638

**Comment by coba999** [comment]
Problem: Solid Ice have 2703 HP, instead of ~93 HP.
http://www.wowhead.com/npc=49233/solid-ice
![wowscrnshot_111115_151153](https://cloud.githubusercontent.com/assets/15231821/11112919/95713cc2-8920-11e5-9abb-3c09547d2d8a.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6640-issue-with-npc-icy-tomb/
