### ISSUE TITLE
[EN] [Quest] [Stonetalon Mountains] Free Our sisters

### ISSUE THREAD

**Issue by Gaurab-Chatterjee** [Atlantiss/BugTracker#2929]
Captured Huntresses cannot be "freed" as they are already free. Only one behind the mill works.

**Comment by Aival94** [comment]
#2518

**Comment by Snake90** [comment]
The quest is still bugged : all cages are already open.

**Comment by Thunderlmao** [comment]
Quest still bugged. All cages are open.
