### ISSUE TITLE
[PL] [instance][ZA] Akil'zon

### ISSUE THREAD

**Issue by ravax** [Atlantiss/BugTracker#2932]
http://www.wowhead.com/npc=23574/akilzon#drops
Boss bije za dużo, po 50k+ w tanka.
Tutaj filmik z globa 2:51 zaczynają walkę.
https://www.youtube.com/watch?v=b3yeYGEgTgQ
Jak widać tutaj w tanka bije po 20k~.
Jak potrzebujecie ss/filmiku od nas z tego bossa to mogę zrobić i dostarczyć.

**Comment by Canderous** [comment]
I'd also like to note that the last time I did Zul'Aman, all of the bosses hit for 50k+ (not just Akil'zon), where they should be hitting for around as much as the Zul'Gurub bosses currently do, which is around 20-25k depending on gear / block / talents etc.

**Comment by Hanatsu** [comment]
I can comfirm this as well, it's impossible to ZA right now. They hit WAY too hard.

**Comment by Jenovas** [comment]
Not impossible, because I did the whole instance as a tank, and also as a healer, but I gotta say it's hard if your tank or heal has low gear.

**Comment by Hanatsu** [comment]
We have tried it twice now with full groups with 356-359 gear all of us. The healer which is the best we got in the guild cant' seriously outheal the damage on Nalorakk. He hits tank for like 100k damage. Can someone look into if it really works correctly...? WE have done it several times before without any issues.

**Comment by meowmewo** [comment]
Yep, today we had to use 2 heals to down Nalorakk,his bear form 2 shoted the tank at times. As the guy said..the dung is posible to be done BUT with a premade of uber geared ppl .Def. does NOT work currectly.

**Comment by Canderous** [comment]
There is something definitely off with the Axe Throwers, yes, but the rest of the trash seemed fine to me.
