### ISSUE TITLE
[EN][Quest][Azjol-Nerub] Death to the Traitor King

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#2936]
new: http://www.wowhead.com/quest=29807/death-to-the-traitor-king
old: http://www.wowhead.com/quest=13167/death-to-the-traitor-king

This is a follow up to closed issue #1149

The quest item still does not drop from the endboss of Azjol-Nerub. Maybe it was for the old quest(13167)? Looking at my quest log, I have the new quest(29807) and the boss didn't drop the item.

![pic](http://i.imgur.com/emsCVYR.jpg)

**Comment by Dean1989** [comment]
confirmed, seem an easy fix if you can do it asap ty

**Comment by Quban** [comment]
Fix soon
