### ISSUE TITLE
[EN][Event][Professions][Fishing] Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by petden** [Atlantiss/BugTracker#2939]
Can't fish Speckled Tastyfish during the Stranglethorn Fishing Extravaganza event in Stranglethorn from Schools of Tastyfish on my low level level 35 toon with 177+80 fishing.
Server revision: ACORE3 (Revision: 4385)
Tested during the event on 2015/04/05 (YYYY/MM/DD) in The Cape of Stranglethorn. At around 13:59 server time the Schools of Tastyfish appeared. At 14:00 the event quest-giver NPC (Riggle Bassbait) yelled in the zone that the event has started.
I was fishing in the Schools of Tastyfish, found 2 close to each other, I fished in those 2. The Bobber was in the school. I had a 177 fishing skill, fished with a Strong Fishing Pole (+5 fishing skill) and had Bright Baubles (+75 fishing skill) on most of the time (when it wore off I tried it without the Bright Baubles too a few times, didn't work either).
When I clicked the Fishing Bobber (after the splashing sound) either no fish or other kinds of fishes were caught. I guess when I caught nothing that should have been the Speckled Tastyfish. With auto loot on it looted nothing, but I tried shift-clicking too (which turns auto loot off) and I got an empty loot window. Finished like 6 schools (fished in the schools until they disappeared) during the event, caught 0 Speckled Tastyfishes.
The server crashed a few minutes after the even started, but came back a few minutes later and the schools were still there and the NPC yelled about the even starting again. Tried fishing before and after the crash too, didn't work either time.
I think it worked for other players because at 14:31 Riggle Bassbait announced that "Timeric" won the tournament. Here's his Armory page (he's a level 85 Blood Elf):
http://atlantiss.eu/armory/character/295509/activity#view-page
The Activity page shows he got the Arcanite Fishing Pole and the Master Angler of Azeroth achievement.
I think this has something to do with my level or fishing skill. My character is a level 35 Night Elf Feral Druid with a ~170 base fishing skill. It should work because there shouldn't be a skill requirement according to this:
http://web.archive.org/web/20120608224650/http://www.wowwiki.com/Stranglethorn_Fishing_Extravaganza
This is the Wowwiki page from the June of 2012 (when 4.3.4 was on the Blizzard servers). It says:
"At one time a skill of 130 was required to catch anything other than trash from the Schools of Tastyfish, but in patch 3.3 this changed. At the present, any successful catch, i.e. anything other than No Fish Were Hooked, from a pool will result in catching what that pool contains. This means that anyone with a fishing skill of 1 can, theoretically, win the Extravaganza."
I have more than 130 skill anyways. It should work.
I think I had a similar bug before: I did the fishing daily in Stormwind 3 times so far. The first 2 times the reward bag contained nothing; it showed some kind of error message on the top of the screen (where it says "Invalid Target" and other error messages), don't know what it said exactly and I looted nothing from the bag. Yesterday the third time I did the daily it worked, I looted some gray items from the bag. I was higher level then. I think it's kinda similar (I didn't report it, because I don't have enough data about it).
Anyways here are some screenshot about the Stranglethorn event:
http://i.imgur.com/y3oZtiN.png
http://i.imgur.com/WXPi2If.png
http://i.imgur.com/4rnetY6.png

**Comment by 1Andas** [comment]
I tried fishing today for the event, I haven't caught a SINGLE Speckled Tastyfish, and I have 525 fishing +100 lure, and Jeweled Fishing Pole. I was fishing in Tastyfish Schools. What's going on here?

**Comment by xmesaj2** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11084-2939fishingloot-speckled-tastyfish/
