### ISSUE TITLE
[PL][QUEST] Postponing the Inevitable

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2940]
http://www.wowhead.com/quest=11905/postponing-the-inevitable

Dotyczy questa z instancji The Nexus, nie z krainy EP.

Na platformie z bossem nie można użyć: http://www.wowhead.com/item=35479/interdimensional-refabricator

**Comment by Varchord** [comment]
Można, q działa. Trzeba to zrobić odpowiednim miejscu
