### ISSUE TITLE
[EN][Quest] At the stonemother's call

### ISSUE THREAD

**Issue by Dracorath** [Atlantiss/BugTracker#2941]
I can't interact with the NPC,whatsoever. She's at the throne and i can't open the quest log to give in the quest.
Please fix this

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2542

**Comment by Dracorath** [comment]
Avalain commented 18 days ago
I menaged to make her active by making myself "At War" with their faction, attack, cast invisibility to drop aggro. When it was all over I could give/take quests from her.
^^^^
I tried this,when i'm at war with her faction i can't attack her,with nothing so far.
I can attack all of the giants,they reset and i try to talk to her but still nothing. I did almost every quest in deepholm 98/110 already done.

**Comment by Dracorath** [comment]
And i did both Resonating Blow and Shaken and Stirred quests.
Still,nothing.
Although there was a point where i clicked on the npc once,and i got in. Clicked turn in the quest and it was the same as One with the ground, i was clicking "Continue" But nothing happened.
I tried taking her other quest,clicked accept and still i didnt receive it.
I have no idea how to move the stonemother

**Comment by Dracorath** [comment]
Fixed,talked to a GM
