### ISSUE TITLE
[EN][Quest] One with the ground

### ISSUE THREAD

**Issue by Dracorath** [Atlantiss/BugTracker#2942]
Okay i'm really fed up with this quest,i can't turn in.
I tried EVERYTHING and nothing works,other ppl can do it but i cant.. please do something!

**Comment by Varchord** [comment]
First. This is your second issue without wowhead/openwow links
This quest is returned via in game interface/auto pop up. Disable your addons and then try again

**Comment by Dracorath** [comment]
Still can't turn it in..

**Comment by Varchord** [comment]
I don't know how to help you. Write a ticket or something

**Comment by Dracorath** [comment]
Fixed it,talked to a gm
