### ISSUE TITLE
[PL] [Quest] [Zul'Drak] I Sense a Disturbance

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#2943]
http://www.wowhead.com/quest=12665/i-sense-a-disturbance
https://www.youtube.com/watch?v=y90V-nYQz8Y
Wg privstat quest jest "completable" (należy wcześniej zabić moby na trasie, gdyż zagrowanie jakiegoś uniemożliwia dalszą jazdę), lecz niestety po dotarciu na miejsce nie zalicza go. Niemożność wykonania tego q przerywa (w połowie) bardzo fajny chain :/

**Comment by Bildo** [comment]
fixed
