### ISSUE TITLE
[EN][Item] Ember Shadowspirit Diamon

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#2944]
You get benefit of this gem without having a required yellow gems
https://cata-twinhead.twinstar.cz/?item=52296
I don't know if this stands for other gems

**Comment by Frainzil** [comment]
All meta gems are bugged, i just tested it, it doesn't matter which one you have, you get all the bonusses even if you don't have the requirements.

**Comment by Piklo** [comment]
bump bump

**Comment by pelekon** [comment]
fixed in rev 5907
