### ISSUE TITLE
[PL][NPC] Banshee Soulclaimer

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2946]
http://www.wowhead.com/npc=29646/banshee-soulclaimer

Podczas walki NPC castują wysoko ponad ziemią, uniemożliwiając ich zabicie meele klasom.
![wowscrnshot_040515_233554](https://cloud.githubusercontent.com/assets/544349/6998771/84e9414c-dbec-11e4-9426-f5306d9f4ec9.jpg)

**Comment by Rithelight** [comment]
WoWHead comment: "As a Retridin, I've had some difficulties facing these floating banshees corrently. Try stepping back until your melee attacks hit them"

**Comment by Maczuga** [comment]
I tried everything, like taunting, charging them, moving around.. The Z coord (height) is just making meele attack causing 'too far away' errors.

**Comment by Wolffenstein** [comment]
Fixed in rev 4391.
