### ISSUE TITLE
[PL][Spell][Hunter] Cobra Shot

### ISSUE THREAD

**Issue by FakeMarcin** [Atlantiss/BugTracker#2947]
Po użyciu Cobra Shota powinniśmy dostawać instantowo 9 focus po wystrzeleniu, natomiast na naszym serwerze focus zostaje zwrócony w momencie dolecenia pocisku do bossa.
http://www.wowhead.com/spell=77767/cobra-shot#changelog

**Comment by FakeMarcin** [comment]
any comments?

**Comment by Wojowniczka** [comment]
Cobra Shot nie jest talentem tylko spell......

**Comment by lukipol** [comment]
Wojowniczka kazdy glupi nawet i tak bedzie wiedzial o co chodzi co nie zmienia faktu ze tego buga hunterzy z tego serwa ktorzy ponoc grali na retailu nie zauwazyli.

**Comment by Wojowniczka** [comment]
@lukipol jak się nie mylę już kiedyś był fix wprowadzany na to jeszcze za czasu 4.0.6a widocznie się coś zchrzaniło. ja nic nie piszę że źle bo zgłosił właśnie bardzo dobrze (ja niestety jeszcze hunta nie mam więc o tym nie wiedziałem) a teraz fix it. @lukipol oraz @FakeMarcin jak wam działa Lock'n'Load talent? bo skarżą się na to że się "zacina" albo jeszcze inne takie wiecie coś o tym? jeśli tak to przydałby się issue :)

**Comment by jackares1** [comment]
Lock sie zacina i co najgorsze pobiera facusa i nie wystrzeli darmowy jak nie masz focusa.

**Comment by lukipol** [comment]
lock drugi shot wymaga focusu ale go nie pobiera

**Comment by Sentus** [comment]
Ten bug związany z Cobra Shotem i Steady Shotem jest już od początków Serwera zanim włączyli Hyjal, Deepholm, itd. Powinien dawać focus po skończonym sukcesywnym castowaniu a nie uderzeniu bo tak na ten moment dodaje focusu. Bug jest krytyczny i ma duży wpływ na DPS hunta.
Nie będę już dodawał filmików zdjęć wykresów a nawet nie będę zapraszał na video-konferencje aby tlumaczyć że tak MA BYĆ bo to już nie pierwszy raz temat jest wałkowany.

**Comment by Jenovas** [comment]
https://github.com/Atlantiss/BugTracker/issues/7517
