### ISSUE TITLE
[PL][Talent][Hunter] Feign Death

### ISSUE THREAD

**Issue by FakeMarcin** [Atlantiss/BugTracker#2948]
Talent Feign Death nie zdejmuje combata co staje się uporczywe.
http://www.wowwiki.com/Feign_Death

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2490
https://github.com/Atlantiss/BugTracker/issues/16

Ah ten nowy od kolorków, nawet nie sprawdza czy to nie duble :P

**Comment by FakeMarcin** [comment]
Sprawdzam tylko robie nowe bo nikt z devow nie patrzy na stare topiki a bynajmniej nic nie
i robi.
Nie wiem co masz na mysli ''od kolorkow''

**Comment by Varchord** [comment]
Nie robi się nowego bo to są duble i powinny byc zamykane. Od kolorków mam na myśli Navedonara, który oznacza zgłoszenia ^^

**Comment by Kejmil** [comment]
dubel takze ten...
