### ISSUE TITLE
Flying Quest NPC's

### ISSUE THREAD

**Issue by kitingmad** [Atlantiss/BugTracker#2949]
There too many flying npc's in this server that fly up way too high up in the sky, and for ranged classes it is not a problem, but for melee classes like rogues and warriors, it's extremely frustrating. You either have to resort to using bows or guns that take up to 2 minutes worth of spamming the "shoot" button. This really should get fixed because there lot's of melee classes/specs that don't have the ranged capabilites as other melee specs such as rets (exorcism), dk's (death coil), and/or ferals (wrath/moonfire). some examples of this are the condors in redridge, and my personal ones : the banshees in zul'drak. And no, these npc's will not move closer to the ground REGARDLESS of your positioning. also, they will not attack you in melee range if you interrupt them, they will just stay up in the sky ... forever and ever.... here's a screenshot 
![wowscrnshot_040515_191059](https://cloud.githubusercontent.com/assets/11811180/6999247/ea3fc180-dbc7-11e4-9e5a-e0198e05c35a.jpg)

**Comment by Maczuga** [comment]
https://github.com/Atlantiss/BugTracker/issues/2946
