### ISSUE TITLE
[EN][NPC] Sentinel Hill Guard

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#295]
Sentinel Hill Guard - http://www.wowhead.com/npc=42407

Sentinel Hill Guards in Westfall (Sentinel Hill) are doing too much damage to the attacking Riverpaw Gnolls.

They are killing them too fast, making it very hard to complete this quest http://www.wowhead.com/quest=26287

Yes, you can complete the quest, but it's a hassle, and not blizzlike, but not because of the quest itself, but because of these guard NPCs.

Here, I've also filtered all the Riverpaw Gnoll mobs that are in Westfall, in case you need to get to them quickly  - http://www.wowhead.com/npcs?filter=na=Riverpaw;cr=6;crs=40;crv=0

In addition to them doing too much damage, I also think that there are too many Sentinel Hill Guards spawned at this location, and there's even a huge squad down at the wall, that I didn't see in any of the videos where people are killing the gnolls for the quest. I leave you to look into it, but damage they do is the biggest issue, because they're pretty much instantly killing the gnolls, making it almost impossible to get the count for the quest. They should be doing almost minimal damage to the Gnolls, so that players can join in the fight, and pick up the kills for the quest count.

You're forced to move quite far away to find gnolls that are not fighting the guards in order to get count for the quest.

**Comment by devilirium** [comment]
Indeed. They should damage the gnolls from 0 to 2 and they take almost no damage from them. Basically the guards are there to simulate a long going battle.

You can check the [youtube video](http://youtu.be/c89R0OooHUY?t=34s) to see how it should be.
