### ISSUE TITLE
[PL][NPC] Crystalweb Spitter

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2950]
http://www.wowhead.com/npc=29412/crystalweb-spitter

Spawnów jest zdecydowanie za mało. Po wyczyszczeniu całej jaskini dalej brakowało mi 2 z 12 mobków do zabicia. W jaskini nie było nikogo poza mną, w całej strefie byłem sam, nie było żadnych zwłok. Drugi run wykazał to samo.

**Comment by Wolffenstein** [comment]
Fixed in rev 4391.
