### ISSUE TITLE
[PL][Quest][Deepholm] Violent Gale

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2962]
http://www.wowhead.com/quest=26426/violent-gale

Po ukończeniu celów misji powinno pokazać się okno z możliwością ukończenia questa.
https://www.youtube.com/watch?v=yrHsePGv9h0 (0:29)

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/5441
