### ISSUE TITLE
[PL][NPC] Jaspertip Crystal-gorger

### ISSUE THREAD

**Issue by Maczuga** [Atlantiss/BugTracker#2964]
http://www.wowhead.com/npc=43171/jaspertip-crystal-gorger

Biją o wiele za mocno jak na mobki z 5,4k hp. W miśka na lvl 84 biją ponad 4,5k normalnymi hitami. Zważywszy na ich grupowe położenie, jak i otoczenie mobków z ilością HP większą o 10x.

https://www.youtube.com/watch?v=g2kAYcXVBJM

Co prawda MoP, ale mobki http://www.wowhead.com/npc=42521/jaspertip-swarmer które są tylko 2x mocniejsze od tych zbugowanych biją na filmiku po ok. 300.

http://www.wowhead.com/quest=26438/intervention

Z tej grupy NPC, wymienione w liście celów misji wszystkie biją tak samo.

**Comment by Bildo** [comment]
fixed
