### ISSUE TITLE
[EN][raid-cata] Al'Akir lootbug

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#2967]
We just killed Al'Akir on 10m normal mode. A leg-item dropped together with the head token for warrior,hunter and shammy. Now since myself and 1 other person survived the encounter, all the rest had to use that /script RepopMe() to get their body back and so they were able to release. Now that being said, when everyone came back into the raid, i gave legs to random person (gave it to shammy for OS) now when i wanted to grant the token to one of our warrior who was there dps'ing, it told me i couldn't grant it to him cause he wasn't in the raid; according to the game. Now i showed the GM; dxx and he told me i was right, he saw he was in the raid (showed recount) What may have happened is with the update of those new items last week, they are kinda bugged that whenever you die or when you are to far away from the boss when the boss dies, they can't get the item. they aren't eligable. i could only grant it the guy who was alive with me, though we had no problem at all with giving the other  item. Please fix this ID bug issue and script the new items as the others are in the al'akir loot table.

**Comment by Bildo** [comment]
Everyone need to be on the same platform as is Nezir. It's a known bug

**Comment by arekczup** [comment]
We killed him on monday the same difficulty , and only paladin and hunter live. We wait for open the lot for everyone else come back to us, they need to use the same comand. And we don't have problem with giving loot to people but token isn't drop. Probably he have some % to drop but i didn't know how it works on 4.1 patch.

**Comment by xolon** [comment]
Blido, al'akir not conclave of the wind

**Comment by Bildo** [comment]
Ohh gosh my mistake xd

**Comment by xolon** [comment]
Well this is what happed, me and raid leader were only ppl alive at the end. loot was some agi legs and token.
We gave legs to 1 shaman, but for token he wasnt eligible to get it and also the other guy who won the roll.
so the conclusion is that tokens drops work differently than normal items

**Comment by xolon** [comment]
Also another bug is that token is in the same loot table as normal items
How it works now: boss drops only 2 items (etc. 2 normal items, 1 normal item and token, 2 tokens)
How it should work: boss should always drop 2 normal items and 1 token, like Cho'gall and Nefarian

**Comment by Jenovas** [comment]
http://eu.battle.net/wow/en/forum/topic/2384578829 - Blizzard wrote "Al'akir drops 2-3 pieces of loot and that a T11 token is not a guaranteed drop"

Also a retail player wrote - "From the two/three items he usually drops on 10 man, it's pretty much random what you get. It can be one or two tier tokens (shoulder/head), or just some other non-tier epics.

I've had few kills, even on my alts when he would just drops 2x non-tier legs. Then next time, he dropped two tier head pieces."

**Comment by Frainzil** [comment]
but as you said, he should also drop 3 items from time to time right? Is it just bad luck or are we never getting 3 items? :p That the token is 1 item of the 2 drops i can understand, but are you sure he is able to drop a 3rd item to?

**Comment by Frainzil** [comment]
or is this only possible from the moment the loot got updated to 4.1?
