### ISSUE TITLE
[EN][Quest][Redridge Mountains] Canyon Romp

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#297]
The quest is not bugged, what's bugged is actually the way you receive it.

After finishing the previous quest in the chain called "Tuning the Gnomecorder" (http://www.wowhead.com/quest=26512), you should get a Canyon Romp (http://www.wowhead.com/quest=26514) quest dialogue open up automatically right there on the spot for you to accept, but that doesn't happen.

You simply get the quest at Magistrate Solomon (http://www.wowhead.com/npc=344), and you need to go back to him to pick up the quest.

As you can see here - https://www.youtube.com/watch?v=Xguz-ebbdDE

Pause at 0:01, and as you can see, it's automatic when you finish the previous quest, and you can only accept the quest, "x" is greyed out, and there is no "decline" button at all.

In addition, after you finish Canyon Romp, completing the quest, and getting the next quest in chain is automatic again, and so on I think, until this chain quest is over, but instead, you have to run back to the NPC for each of these quests.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/5065

**Comment by user1011** [comment]
Bump.

**Comment by user1011** [comment]
On the quest Canyon Romp the gnolls don't show, in their tooltip, that you have to kill them for the quest item Redridge Gnoll Collars.
http://www.wowhead.com/item=58897/redridge-gnoll-collar

![image](https://cloud.githubusercontent.com/assets/13118481/16524614/10c5ccfa-3fa9-11e6-97ee-0bf308f4d102.png)
![image](https://cloud.githubusercontent.com/assets/13118481/16524629/16c4b0c6-3fa9-11e6-9d16-01aa95ae9064.png)
![image](https://cloud.githubusercontent.com/assets/13118481/16524638/1c385828-3fa9-11e6-83fe-37c7de8b7c8d.png)
![image](https://cloud.githubusercontent.com/assets/13118481/16524640/2361dbec-3fa9-11e6-9053-8a6f5e5078e4.png)

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14478-zone-redridge-mountains/

**Comment by Jenovas** [comment]
Fix in rev 5539
