### ISSUE TITLE
[EN][NPC][Deepholm] Terborus

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#2970]
Terobrus (rare mob) is missing.
http://www.wowhead.com/npc=50060/terborus

**Comment by Drutmaster** [comment]
It's not. It's a very, very rare mob. He is showing from time to time.

**Comment by ShockRW** [comment]
Are you sure that you've seen him in 4.3.4 atlantiss ? He spawns near the stone worms cave?. Respond plz.

**Comment by Drutmaster** [comment]
He spawns outside the cave. Near normal Gyroworms. If you have NPC_Scan it should shout out that you found him
