### ISSUE TITLE
[EN] [Glyph] Glyph of Swiftmend 

### ISSUE THREAD

**Issue by tincho388** [Atlantiss/BugTracker#2971]
Doesn't seems to work cause it still consumes a rejuvenation or regrowth.Thanks http://www.wowwiki.com/Glyph_of_Swiftmend

**Comment by arekczup** [comment]
On my druid working good.

**Comment by Varchord** [comment]
Same here, working as charm

**Comment by Jenovas** [comment]
Works ok. Please change talents, remove glyph add it again.
Closing.
