### ISSUE TITLE
[EN][NPC] Una Kobuna

### ISSUE THREAD

**Issue by tincho388** [Atlantiss/BugTracker#2974]
This NPC that sells a "must have" items for Inscription it's bug. 
http://www.wowhead.com/npc=50248/una-kobuna

**Comment by Bildo** [comment]
https://www.youtube.com/watch?v=guomoIbZiT8

**Comment by Axahus** [comment]
Scribes are forced to skill 520-525 on one 24h-cd recipe... Please fix it asap.

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12988-2974-una-kobuna-vendor/
