### ISSUE TITLE
[EN][Quest][Sol Basin] Rough Ride

### ISSUE THREAD

**Issue by Procto** [Atlantiss/BugTracker#2976]
while riding the croc  when he go in river it freezes and get your attack by a Gorilla i try to dismount and i feel with a 6min rez .

**Comment by Navedonar** [comment]
bt rules

**Comment by Procto** [comment]
it is with in the rules [EN][Quest][Sol Basin] Rough Ride   i put  and wrote a comment  what wrong with it ?

**Comment by Navedonar** [comment]
wowhead links

**Comment by maslak** [comment]
Sol basin lol
[Quest]Sholazar Basin
http://www.wowhead.com/quest=12536/a-rough-ride
