### ISSUE TITLE
[PL][NPC]Miwana

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#2977]
http://www.wowhead.com/npc=44785/miwana#sells
http://www.wowhead.com/item=58257/highland-spring-water
http://www.wowhead.com/item=58259/highland-sheep-cheese
http://www.wowhead.com/item=58261/buttery-wheat-roll
http://www.wowhead.com/item=28399/filtered-draenic-water
http://www.wowhead.com/item=58274/fresh-water
http://www.wowhead.com/item=1179/ice-cold-milk
http://www.wowhead.com/item=1205/melon-juice
http://www.wowhead.com/item=1645/moonberry-juice
http://www.wowhead.com/item=33444/pungent-seal-whey
http://www.wowhead.com/item=8766/morning-glory-dew
http://www.wowhead.com/item=58260/pine-nut-bread
http://www.wowhead.com/item=159/refreshing-spring-water
http://www.wowhead.com/item=58256/sparkling-oasis-water
http://www.wowhead.com/item=35950/sweet-potato-bread
http://www.wowhead.com/item=1708/sweet-nectar

NPC Miwana sprzedaje Highland Spring Water, Highland Sheep Cheese, Buttery Wheat Roll, Filtered Draenic Water, Fresh Water, Ice Cold Milk, Melon Juice i inne wymienione w linkach po 1, a powinna w stackach po 5.

**Comment by Asavel** [comment]
a bildo za takie bzdury dał sated :( a ty sobie zgłaszasz.

**Comment by InformatorPE** [comment]
Serwer powinien dążyć do doskonałośći.

**Comment by Asavel** [comment]
Dokładnie!
