### ISSUE TITLE
[PL] [NPC] Officer Redblade

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#2982]
http://www.wowhead.com/npc=15765/officer-redblade
http://www.wowwiki.com/Officer_Redblade

Patches and hotfixes
Patch 1.9.0 (03-Jan-2006): Added
Patch 3.2.0 (04-Aug-2009): Removed

NPC Officer Redblade jest (http://zapodaj.net/b386ae3ebd01c.jpg.html), a nie powinno go tu być.

**Comment by Artist1995** [comment]
http://atlantiss.eu/community/viewtopic.php?f=133&t=1657
