### ISSUE TITLE
[PL][QUEST][Silithus] Thunderaan the Windseeker

### ISSUE THREAD

**Issue by Nitunita** [Atlantiss/BugTracker#2983]
http://www.wowhead.com/quest=7786/thunderaan-the-windseeker
Nie można kontynuować questa po zdobyciu wszystkich potrzebnych itemów.

**Comment by smmuntz** [comment]
Ragnaros doesn't seem to have a 100% chance to drop the Essence of the Fire Lord while you are on the quest. I have killed Ragnaros several times while on the quest, and it hasn't dropped once.

http://www.wowhead.com/item=19017/essence-of-the-firelord

**Comment by Nitunita** [comment]
Odświeżam

**Comment by Xtrodinary69** [comment]
Any news on this fix?
