### ISSUE TITLE
[EN][Racial][Worgen] Flayer

### ISSUE THREAD

**Issue by Polarchris** [Atlantiss/BugTracker#2986]
The racial passive Flayer, http://www.wowhead.com/spell=68978/flayer ,should allow worgen players to skin faster than other races skinners. Cast time of worgen skinner should be 0.5 seconds but it's 1.5 seconds like all other races.

**Comment by zeoos** [comment]
So will this be fixed? Why you closed it because this racial is still not working.

**Comment by Bildo** [comment]
wait for an update >.<

**Comment by zeoos** [comment]
Cool, i'd like to confirm that is fixed, 0.5 seconds skinning.
