### ISSUE TITLE
[EN][Spell][Death Knight] Blood tap (Frost DK)

### ISSUE THREAD

**Issue by jagoan1** [Atlantiss/BugTracker#2990]
(http://cata.openwow.com/spell=45529) after using blood tap with frost DK, the death rune used become a blood rune. where frost dk permanently change blood rune to death rune. and it still a blood rune till i respec back to frost spec. ty

**Comment by Varchord** [comment]
Propably related to 
https://github.com/Atlantiss/BugTracker/issues/444

**Comment by Wojowniczka** [comment]
@jagoan1 after wipe and entering raid or dung will bug ur death rune so You will have 1 blood and 1 death and u need to do relog or respec......
annoying bug

**Comment by Kejmil** [comment]
@Aviannaqt 
blood tap is no longer doing things reported in this issue so it can be closed

**Comment by Aviannaqt** [comment]
dobrze prosze pana
