### ISSUE TITLE
[PL][Un'Goro Crater][Quest] Shizzle's Flyer

### ISSUE THREAD

**Issue by Saranai** [Atlantiss/BugTracker#2991]
http://www.wowhead.com/quest=24736/shizzles-flyer

Drop Webbed Pterrordax Scale jest za mały, Zamiast wypadać po 1-6 sztuk, wypada 5-6 lub nic.

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11344-item-webbed-pterrordax-scale-drop-chance/
