### ISSUE TITLE
[EN][NPC] Big Zokk Torquewrench

### ISSUE THREAD

**Issue by Sadzka** [Atlantiss/BugTracker#2996]
Can't interraction with him.
http://www.wowhead.com/npc=54649/big-zokk-torquewrench

**Comment by Bildo** [comment]
he doesnt sell anything for now

**Comment by Bemalthan** [comment]
Are you planning to fix this at some point?

**Comment by mgshaper** [comment]
unfortunatelly, it's still not working :/ - this NPC (Big Zokk) hasn't any items in his "offers"

**Comment by Piklo** [comment]
"This NPC will sell the replica Grand Marshal and High Warlord weapons to any who have the original Feat's of Strength (Grand Marshal or High Warlord) or the new rated battleground ranks of Grand Marshal or High Warlord."
http://www.wowhead.com/npc=54649/big-zokk-torquewrench#comments:id=1587191

**Comment by 1Andas** [comment]
@Piklo Does this work here though? Can it be confirmed?

**Comment by Piklo** [comment]
I don't know, im not pvp player so I don't have that achiev :D
