### ISSUE TITLE
[EN][Item] Darkmoon Card: Hurricane

### ISSUE THREAD

**Issue by Hanatsu** [Atlantiss/BugTracker#2997]
This trinket does not proc.

http://i1204.photobucket.com/albums/bb404/Hanatsu2/WoWScrnShot_041015_053905_zps5odtk4ub.jpg

Auto-shot on a dummy for a few min. 0 dmg from trinket. 

http://www.wowhead.com/item=62051/darkmoon-card-hurricane

**Comment by Varchord** [comment]
To me it looks like it procced but didn't deal damage. Idk how to full screen view image on your hosting and it's very unclear..
Try moving closer to your target. When 4.3.4 went live people were talking that volcano card has 15 yd range or something( it's not true afaik). Maybe it's something similar
Check then and post all abilities from skada (click on your name).

**Comment by Hanatsu** [comment]
It would seem that you are correct. The trinket does not proc unless you are very close to target. This is bullshit, I shouldn't have to stand in almost melee range for the trinket to proc. This needs a fix.

http://i1204.photobucket.com/albums/bb404/Hanatsu2/recount_zpsycu7xrcb.png

**Comment by Hanatsu** [comment]
...and even if I stand as close as possible, the proc rate is awful. Is it supposed to be this low?

http://i1204.photobucket.com/albums/bb404/Hanatsu2/WoWScrnShot_041015_145121_zps8m2spt7f.jpg

**Comment by Varchord** [comment]
"The PPM is reportedly 1 PPM, giving this about a 4.3% chance per hit of a proc(assuming 2.6 weapons..."
Wowhead comment.
I suggest leaving your character for an hour or so autoattacking and check proc rate after that.
As for range of the proc
http://www.wowhead.com/spell=89087/lightning-strike
Range	20 yards (Short)

You have to check that too :P

**Comment by Hanatsu** [comment]
That link is conflicting however, some of the spells also called "Lightning strike" says unlimited range. I will do as you suggest though to check proc rate properly ;)

**Comment by Varchord** [comment]
The lighting strike i've linked is procced by this
http://www.wowhead.com/spell=89086/hurricane

**Comment by Supremacja** [comment]
The Card still working very poorly. Its worse than ilvl333 trinkets or even lower ones. Procing about 10 - 20 times on 500 hits (I tested 50 times) Heres screen:
![wowscrnshot_080415_110416](https://cloud.githubusercontent.com/assets/13468777/9057250/f4422418-3a98-11e5-94ae-f02d19eab989.jpg)

I think its really a fatal issue, casue many players buing it without knowledge, and the prices are from freaking cosmos...

**Comment by CrypticWizard** [comment]
Why was this closed?

- There was no determination whether or not the proc rate is actually Blizzlike on Atlantiss.
- The fact that according to previous messages it will only proc when in very close proximity to the target is also not Blizzlike. See the very trinket itself. Melee or Ranged attacks. If people need to be in melee range for it to work, then it is obviously completely useless to Hunters. Which is not Blizzlike. During retail Cataclysm it was every bit a solid trinket for Hunters as it was for Enhance / Rogues.
