### ISSUE TITLE
[PL][ACHIEVEMENT] 2500 Daily Quests Complete

### ISSUE THREAD

**Issue by coocoo89** [Atlantiss/BugTracker#2998]
Nie pobiera danych ze statystyk, aktualnie pokazuje mi 5/2500, ten na 1000 mam oczywiście zaliczony.
W statystykach mam 1800+ complete.

http://www.wowhead.com/achievement=5751/2500-daily-quests-complete

**Comment by Veruca1320** [comment]
Zgadza się! Według statystyk mam ukończonych 3543 daily questów, a obecnie achievement pokazuje 272/2500.

**Comment by armano2** [comment]
All bugs with this type are merged into one issue: #4451
