### ISSUE TITLE
[PL][ACHIEVEMENT] Justly Rewarded

### ISSUE THREAD

**Issue by coocoo89** [Atlantiss/BugTracker#2999]
Nie pobiera danych ze statystyk, 1000+ /30 000 w achie a w statystykach 67 000+ (prawie 6 000 q wykonanych).

http://www.wowhead.com/achievement=5752/justly-rewarded

**Comment by Veruca1320** [comment]
Zgadza się! Według statystyk mam 104 000+ golda z questów, a obecnie w achievemencie 6000+.

**Comment by armano2** [comment]
All bugs with this type are merged into one issue: #4451
