### ISSUE TITLE
[PL][QUEST] Proving grounds

### ISSUE THREAD

**Issue by coocoo89** [Atlantiss/BugTracker#3000]
http://www.wowwiki.com/Quest:Proving_Grounds_%28Horde%29
Q failed przy starcie. Powinno to wygladac tak: idziesz na av, prawie na samym koncu w Wildpaw cavern jest objekt http://www.wowwiki.com/Frostwolf_Banner który odnosisz do NPCa który dał ci to zadanie.

**Comment by monibu** [comment]
linki do wowhead:
quest dla ally: http://www.wowhead.com/quest=7162/proving-grounds
quest dla hordy: http://www.wowhead.com/quest=7161/proving-grounds

**Comment by Erny102** [comment]
Już miałem robić nowe zgłoszenie apropos tego Q, ale postanowiłem jeszcze raz przeszukać tracker - no i jest. Quest nadal nie działa. 'Failed' natychmiast po wzięciu. Jest on niezbędny do zdobycia http://www.wowhead.com/item=17691/stormpike-insignia-rank-1#objective-of

**Comment by eryczek1615** [comment]
wciąż jest failed

**Comment by Bildo** [comment]
fixed

**Comment by Erny102** [comment]
Z tego co widzę to nadal jest failed po wzięciu. Nie byłem na AV więc nie mogę potwierdzić co dalej, ale quest failed to raczej nic dobrego...

**Comment by Kiperr** [comment]
Gdyż serwer nie został jeszcze zaktualizowany, wystarczyło zajrzeć w changelog na stronie.

**Comment by Erny102** [comment]
Ups przepraszam bardzo.
