### ISSUE TITLE
[PL][SPELL][DK] HUNGERING COLD

### ISSUE THREAD

**Issue by coocoo89** [Atlantiss/BugTracker#3001]
http://cata.openwow.com/spell=49203 jest przerywane przez http://cata.openwow.com/spell=43265#see-also-ability 
Działało na 4.0.6a

**Comment by Varchord** [comment]
Enemies are considered Frozen, but any damage other than diseases will break the ice.

Znajdź dówód, że D&D nie powinno wyrzucać z hungering cold

**Comment by coocoo89** [comment]
Szukałem i znalazłem tylko informacje na privach dlatego moja teorie opieram na tym, że prawdopodobnie już to kiedyś było naprawiane.

**Comment by Varchord** [comment]
Informacja z privów to żaden dowód. Fakt, że "działało" na 4.0.6 może oznaczać, że było wtedy zbugowane

**Comment by Jenovas** [comment]
"Btw why you are using DnD before Hungering Cold if you know you'll break the effect as soon as it deals damage? It seems a bit stupid, isn't it? :)" - comment from wowhead.
Closing.

**Comment by coocoo89** [comment]
link pl0x

**Comment by Jenovas** [comment]
Google - Death and Decay wowhead
