### ISSUE TITLE
[PL][Quest][Un' Goro Crater] Ever Watching From Above

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#3002]
Po pociągnięciu za dźwignie przemienia nas w danego stwora, ale nie przenosi w konkretny teren na mapie w związku z czym nie można wykonać zadań koniecznych do zaliczenia questa.
link do questa: http://www.wowhead.com/quest=24695/ever-watching-from-above
tak powinno być: https://www.youtube.com/watch?v=bvCx0DxfPfc

**Comment by BAndysc** [comment]
Fixed
