### ISSUE TITLE
[EN][Warlock] Demonic Empowerment

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#3006]
Felguard is my pet as demonology. If I use Demonic Empowerment before the pet goes into a ring of frost he will get frozen. He should be immune to cc for 15 sec. If he first gets frozen and I use Demonic Empowerment he will get un CC'ed correctly. Not sure if he is immune 15 sec afterwards. Haven't tested. But with ring of frost it is bugged.

Felguard: "Instantly removes all stun, snare, fear, banish, or horror and movement impairing effects from your Felguard and makes your Felguard immune to them for 15 sec."

http://www.wowwiki.com/Demonic_Empowerment

**Comment by Milton3450** [comment]
I tested with Turn Evil. My pet DOES NOT get immune! It removes the fear BUT he does not get immune. So I guess this count for all cc. Can this pls be marked as critical? This is a gamebreaking bug for demo locks.

**Comment by Wolffenstein** [comment]
http://us.battle.net/wow/en/forum/topic/1921984400 - Demonic Empowerment shouldn't prevent from getting Turn Evil or other similar effects.

**Comment by Milton3450** [comment]
Maybe it was changed to include all cc later, maybe in MOP? Maybe you are right. I will check the tooltip on my lock.

**Comment by Wolffenstein** [comment]
The only issue with Demonic Empowerment is that it doesn't protect against freeze mechanics.

**Comment by Milton3450** [comment]
It doesn't make sense to me because the tooltip says "fear" and "horror" effects. What effect would you think Turn Evil is?

**Comment by Wolffenstein** [comment]
Mechanic = 23 (MECHANIC_TURN)

**Comment by Milton3450** [comment]
So it is a "turn" effect? Never heard of such a thing. It might be legit nevertheless :). So I will leave this report open because of the Ring of Frost issue?

**Comment by Wolffenstein** [comment]
After some research, I think you might be right about Turn Evil.

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
