### ISSUE TITLE
[EN][Hunter][Talent][Spell] Focus Fire and Pathing

### ISSUE THREAD

**Issue by smmuntz** [Atlantiss/BugTracker#3007]
http://www.wowhead.com/spell=82692/focus-fire

When using the Focus Fire Ability at full stacks while also being fully talented into Pathing seems to only give the haste of Focus Fire. Pathing, while providing haste initially seems to go away during the duration of Focus Fire, but it does return once Focus Fire fades.

For math on my end using the stats that I have with/without the Pathing talent:
__________________________
**With Pathing, Without Focus Fire:**
500 haste rating (+7.02% haste) according to the tooltip

**With Pathing, With Focus Fire at 5 stacks:**
500 haste rating (19.49%) according to the tooltip

**that means:**
19.49% - 7.02% = 12.47% multiplicative increase
_________________________________________
**Without Pathing, Without Focus Fire:**
500 haste rating (+3.90% haste) according to the tooltip

**Without Pathing, With Focus Fire at 5 stacks:**
500 haste rating (19.49%) according to the tooltip

**that means:**
19.49% - 3.90% = 15.59% multiplicative increase
_______________________________________
I calculated it out, and my haste with focus fire should actually be 23.07% (haste is calculated multiplicatively, so it is 1.039x1.03x1.15 = 1.2307)

**Comment by Tj20** [comment]
I think you're right. I also gave it a try and [here](http://i.imgur.com/OXo0FRN.jpg) is a pic without Pathing and [here](http://i.imgur.com/TBcjlTD.jpg) with 3/3 pathing under the focus fire effect. 

As one can see, everything stays exactly the same: 25.68% ranged haste, 1.59 sec Cobra cast time, the swing timer, too (I'm not sure why my character sheet says 2.31 speed while my swing timer addon says 1.96 speed (base speed of my bow is 2.90), but in any case, both values stay the same).

**Comment by ShockRW** [comment]
Seems like focus fire also doesn't provide 20 focus when used (if we are talking aboout 5 stacks) it always give 4 focus to the hunter and 20 to the pet. Can someone confirm this ?

**Comment by meowmewo** [comment]
BUUUUUMP please i beg u have mercy

**Comment by Caturix** [comment]
Buuuump

**Comment by meowmewo** [comment]
buuump

**Comment by LaveGit** [comment]
Bump :(

**Comment by troublemakerr** [comment]
BUUUUUUUUUUUUMP BOI!

**Comment by troublemakerr** [comment]
BUMP

**Comment by troublemakerr** [comment]
BUMP

**Comment by meowmewo** [comment]
Mature.

**Comment by Bildo** [comment]
Maybe because it's 1 second fix?

**Comment by Wolffenstein** [comment]
This is the last time I allow these kind of bumping actions and posting bugs on the forum. The next time someone does it, there will be punishment involved.

Fixed in rev 4701.
