### ISSUE TITLE
[PL] Pety

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#3008]
Jak jest: 
Obecnie pety otrzymują buffy takie jak marka druida, bom paladyna itd..

Jak powinno być:
Pety nie powinny otrzymywać buffów od graczy zwiększających statystyki
pet warlocka  <a href='http://www.worldoflogs.com/reports/73zxd3o7n353msjc/sum/damageDone/?s=2626&e=2812'>link</a>
pet huntera <a href='http://www.worldoflogs.com/reports/73zxd3o7n353msjc/details/17/?s=2626&e=2812'>link</a>
pet Dk <a href='http://www.worldoflogs.com/reports/73zxd3o7n353msjc/details/151/?s=2626&e=2812'>link</a>

Znalazłem jeszcze komentarz z EJ  <a href='http://forums.elitistjerks.com/topic/104583-unholy-dps-cataclysm-semi-charmed-life/'>link</a>

"Ghouls work like most permanent pets, receiving a portion of your stats and benefitting from any buffs on you  although they, themselves, cannot be individually buffed so as to prevent double dipping."  

Korzystałem z logów gildii paragon z czasów patcha 4.3.4

**Comment by Jenovas** [comment]
Should be fixed in  rev. 4397
