### ISSUE TITLE
[PL][Death Knight] Dmg petów

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#3009]
Jak jest: 
<a href='http://cata.openwow.com/spell=91778'>Sweeping Claws</a> uderza zbyt często i zbyt mocno.
Logi z Atlantissa <a href='http://worldoflogs.com/reports/rt-lqugbokbr28s3mg2/details/85/?s=6499&e=6707'>link</a> porównująć do <a href='http://www.worldoflogs.com/reports/73zxd3o7n353msjc/details/151/?s=2626&e=2812'>link</a>

Średni hit na globalu 11405.8
Średni hit u nas 11428.2	
podkleślam że logi z globala są z contentu 4.3.4 pet dk który zrobił w tej walce 45k dpsu uderza mniej niż pet dk z atlantissa z gearem z 2 kontentów niżej.
W dodatku rozkład % obrażeń nie jest poprawny ( sweeping claws uderza zbyt często)
global:
Melee 74.7 %
Sweeping Claws 18.1 %
Claw 7.2 %	

atlantiss: 
Sweeping Claws 47.8 %
Meele 35.1 %
Claw 16.9 %	
Niestety nie znalazłem żadnej formuły co do damage'a. Możliwe, że damage wróci do normy po naprawieniu buga z nakładaniem buffów na pety #3008 wtedy trzeba będzie tylko poprawić częstość uderzeń Sweeping Claws. Ciężko mi przetestować czym jest to spowodowane bo nie mam żadego dk.

**Comment by fafal** [comment]
Logi z t13 vs BoT norm
ok

**Comment by Jenovas** [comment]
Od rev. 4397 buffy nie powinny wchodzić na pety / guardiany.

**Comment by mitim1** [comment]
Nadal można dać scrola na peta.

**Comment by nevcio** [comment]
W dodatku bloodlust ktory powinien wchodzic na pety teraz na nie nie dziala. Domyslam sie ze buff w 3 fazie sinestry essence of the red tez nie bedzie dzialal co znacznie obnizy dps grupy ( a powinien wchodzic) ale tego jeszcze nie mialem okazji sprawdzic

**Comment by qubuslabadz** [comment]
Pet powinien mieć buffa hero/bl, ale czy powinien on dawać effect? Nie sądzę. Bo wtedy pet by miał 2x haste z BL'a. Na Sinestrze buff prawdopodobnie będzie na pecie, ale nie będzie dawał mu podwójnego effectu.

**Comment by mitim1** [comment]
Tak powinien dawać effect.
https://www.youtube.com/watch?v=LA04Wmv-QHw

**Comment by qubuslabadz** [comment]
To że pet i hunter maja buffa, nie znaczy, że pet ma 2x haste. Jeden od huntera, drugi od swojego buffa.

**Comment by mitim1** [comment]
http://www.worldoflogs.com/reports/73zxd3o7n353msjc/details/17/?s=2626&e=2812
Aha czyli ze jeśli pet ma boma i hunter ma boma to pet nie dostaje statystyk? To co oni cały czas fixowali, visuala? -.-

**Comment by qubuslabadz** [comment]
Jeśli chcesz coś udowodnić, najlepiej pokaż, że w statystykach pet podczas BL'a na globie miał podwójny haste (od siebie oraz od huntera) , bo na razie to tylko spekulacje.

**Comment by qubuslabadz** [comment]
"The pet gains the effects of AH, but will not gain the 'double' effect from the hunter.

To illistrate:

pet speed with AH on hunter+pet: 130%
pet speed with AH on pet ONLY: 130%
pet speed with AH on hunter ONLY: 100%
pet speed with no AH: 100%"

http://www.mmo-champion.com/threads/909405-Terrible-DPS-ideas-that-might-just-work/page2

**Comment by signeral** [comment]
"pet speed with AH on hunter ONLY: 100%
pet speed with no AH: 100%"
to znaczy ze haste hunta nie ma znaczenia ?!

**Comment by mitim1** [comment]
Znaczy to też ze pet powinien dostawać bl/hero ale nie skalować się z dodatkowych hastem swojego właściciela.

**Comment by qubuslabadz** [comment]
To jest blizzarda mechanika. My mamy uproszczoną, czyli nie dajemy w ogóle petom BL'a, ale za to hunter zawsze daje petowi haste z BL'a, niezależnie, czy on ma, czy nie.

**Comment by Jenovas** [comment]
Tzn że dodatkowy haste z BLa nie idzie na peta, czyli końcowy wynik jest +30% haste dla peta, u nas końcowy efekt również jest +30% haste dla peta, tylko zrobione w inne sposób. Bug jest bugiem wizualnym, zostanie poprawiony za rok jak nie będzie co robić albo jak komuś bardzo będzie się nudzić.

**Comment by mitim1** [comment]
Tylko ze ta mechanika jest zła ponieważ KAŻDY buff który daje haste hunterowi da haste petowi, a są spele które daje haste tylko hunterowi np. Focus Fire.

**Comment by Jenovas** [comment]
Większość spelli dających haste pewnie tak jest zrobiona.

**Comment by mitim1** [comment]
A czy buff sinestry także będzie działać jak bl ?

**Comment by Jenovas** [comment]
Buff Sinestry będzie tak działać że i pet i hunt mają buffa a tylko Hunt dostaje bonus z aury, a pet skaluje się z właścicielem. Czyli nie będzie jak do tej pory 200% haste dla peta tylko 100%.

**Comment by mitim1** [comment]
A co z sytuacja gdy odpalamy bl, po pewnym czasie nasz pet umiera, przyzywamy nowego i mając dalej sated chcemy zęby ktos odpalił bl aby nasz pet dostał dodatkowych haste?

**Comment by mitim1** [comment]
Podsumowując u nas pety działają jak guardiany a guardiany jak pety.

**Comment by mitim1** [comment]
Na pety locka ta mechanika nie działa. Pety locka mimo tego ze lock dostał bl nie zmieniają swoich statystyk.

**Comment by fafal** [comment]
Warlock:
Pet benefit from:
Your character's haste, crit, and hit RATING
External haste buffs applied to it after it is summoned (DI, power infusion - not that he should ever get them :P)
He does not benefit from:
5% haste aura
Heroism/BL/Time Warp 
Takze +1
Aczkolwiek neie jestem pewien czy pety locka i DG w ogole sie skaluja z haste wlasciciela (ale tylko z gearu) ^^

**Comment by fafal** [comment]
Aczkolwiek np Doomguarda mimo, że nie ma nic z haste buffów to powinien działać na nim buff z sinestry o ile został summniety przed nim ^^

**Comment by mitim1** [comment]
http://www.mmo-champion.com/threads/926727-Haste-and-DoomGuard?p=12005453&viewfull=1 
Potwierdzenie ^

**Comment by Jenovas** [comment]
A co z sytuacja gdy odpalamy bl, po pewnym czasie nasz pet umiera, przyzywamy nowego i mając dalej sated chcemy zęby ktos odpalił bl aby nasz pet dostał dodatkowych haste? - nie będzie działał

Ktoś wyliczył że majać same pety z Ancient Histeria i summajać za każdym razem nowego kiedy poprzedniemu skonczy się buff zyskujesz aż od 500-1000 DPSa. Tak więc za dużo zabawy dla tak minor buga.

**Comment by MasterK15** [comment]
wczoraj moj pet (felguard) mial na sobie hero

**Comment by mitim1** [comment]
Brak 1 k dpsu może spowodować wipe + obecny stan avo u petow = dość często będzie występować ta strata 1 k ale rozumiem.

**Comment by mitim1** [comment]
Podsumowując

Buffy
-Nadal można dać KAŻDEMU petowi/guardianowi buffy targetowane np.Bom/Bok, wystarczy że osoba która daje buffa jest sama w pt i stargetuje peta 
Bl/Hero
Hunter
-Działa w miarę ok 
Dk
-Działa na peta, nie wiem jak z gargoyle,armia oraz blood parasite, prosił bym kogoś od dodatkowe testy.
Shaman
-Na elemental działa prawidłowo.(blizzlike)
-Na feral spirit działa prawidłowo,(blizzlike)
Lock
-Obecnie ŻADEN pet/guardian locka nie dostaje żadnych benefitow z bl/hero.
Druid
-Trenty dostaje benefit z bl, nie znalazłem na ten temat żadnej informacji po za ta ze trenty NIE maja haste.
Paladyn
Guardian of Ancient Kings - prosił bym kogoś o testy bo nie posiadam pala, nie znalazłem żadnych informacji czy powinien dostawać jakie benefity z bl/hero.
 
Jeśli ktos sobie życzy mogę zrobić oddzielne zgloszenię
Pominąłem tu takie rzeczy jak to że Great Fire Elemental nie castuje 2 spelli czy to ze doomguard czasem potrafi stać i nic nie robić.

**Comment by Jenovas** [comment]
4412 już żadne buffy nie powinny wchodzić na pety nawet jak targetujemy peta i nie jesteśmy w party

**Comment by mitim1** [comment]
A bl na petach locka w planie jest ?:)

**Comment by mitim1** [comment]
!BUMP
