### ISSUE TITLE
[EN][Recipe] : Living Action Potion

### ISSUE THREAD

**Issue by yemaja** [Atlantiss/BugTracker#3010]
item:
http://www.wowhead.com/item=20013/recipe-living-action-potion

sould be sold by:
http://www.wowhead.com/npc=11188/evie-whirlbrew

**Comment by ryukrem** [comment]
item: http://www.wowhead.com/item=20008/living-action-potion
should be sold by:http://www.wowhead.com/npc=11188/evie-whirlbrew

**Comment by aslearr** [comment]
Please fix this recipe problame :) 
  One of the many best  recip the game can offer! :)
