### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] Burnside must fall

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#3012]
After accepting this quest i went where Magistrate Burnside is and i can't attack him, the event doesn't even start, he remains in his invulnerable bubble and you can't do nothing.
http://www.wowhead.com/quest=28235/burnside-must-fall

**Comment by Wolffenstein** [comment]
Did you walk under him?

**Comment by Griskhet** [comment]
Yes, no response, no reaction and i can't attack him

**Comment by Griskhet** [comment]
![wowscrnshot_041115_170148](https://cloud.githubusercontent.com/assets/11901135/7101858/8f93b31e-e06c-11e4-902f-d6df4edbc827.jpg)

**Comment by coocoo89** [comment]
it used to work once after server crash

**Comment by TheSteventh** [comment]
It still doesnt work.

**Comment by Brego55** [comment]
I tried to do this now, but doesn't work

**Comment by BAndysc** [comment]
Should now reset
