### ISSUE TITLE
Death pact vs. pet in cc

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3013]
Right now if your pet is in CC(clone,ring,stun,etc) and you use Death pact you still get healed.

How it should be:
You shouldn't be able to use Death Pact at all while your pet is CCed,  when you try to use Death Pact a message like "You can't use that right now" should pop up

**Comment by Varchord** [comment]
title
links

**Comment by razgal** [comment]
why did you even closed it?

**Comment by Navedonar** [comment]
bt rules
