### ISSUE TITLE
[EN]Ring of frost vs. cc

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3014]
If mage it's in any kind of CC ( Cyclone , Polymorph , hex,stun,silence) when he casts Ring of Frost , enemy targets should NOT be frozen if they are in the area of the ring.

Proofs:
1.
http://us.battle.net/wow/en/forum/topic/4927282934
"technically, Ring of Frost is a channeled spell. If you're in some form of CC (cyclone, poly, blind, etc. etc.) the cc interrupts the channel and enemies can run through it without a problem."

2.
http://www.warcraftmovies.com/movieview.php?id=210911

**Comment by Varchord** [comment]
title
links (to skills)

**Comment by razgal** [comment]
closed it by mistake.

**Comment by blinkmaster** [comment]
it was considered a bug on retail servers. i hope that if u fix this you will also fix the delay allowing mages to for example scorch fb the nova for guaranted shatter? or wait.. you said that you wont allow retail bugs like that spell delay to exist on this server

**Comment by razgal** [comment]
this wasn't a bug on retail it's working even now on live WoD

**Comment by Jenovas** [comment]
Fixed in rev 4425
