### ISSUE TITLE
Hunter's Pet

### ISSUE THREAD

**Issue by pokolito** [Atlantiss/BugTracker#3017]
As a hunter, my pet should be attacking always with me. My pet does not want to attack while swimming underwater. If the target gets almost IN the pet... then it might attack the target. Sometimes even does not want to get in the water and goes around the pool I want to get in.
Other thing is that I feel like my pet is slow and not sticking with me like it should be. It's like 10 yards behind.

**Comment by arekczup** [comment]
https://github.com/Atlantiss/BugTracker/issues/1059
