### ISSUE TITLE
[EN][Quest][Hillsbrad FootHills] A blight upon the land

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#3018]
When you reach the place where Warden Stillwater is, getting near him should trigger an event, but nothing happens and he isn't even hostile, so you can't kill him and take his head.
http://www.wowhead.com/quest=28237/a-blight-upon-the-land
![wowscrnshot_041115_231811](https://cloud.githubusercontent.com/assets/11901135/7103303/0d1126e4-e0a1-11e4-9821-77583a93d5db.jpg)

**Comment by Tj20** [comment]
#397

**Comment by HopMage** [comment]
Still bugged - please fix.

**Comment by Hica** [comment]
Still bugged
