### ISSUE TITLE
[EN]Stratholm Gate does not reopen on wipe

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3019]
Hello,
Today my group wiped on baron and could not initiate the fight again, because the gate was closed. We were forced to leave RDF. The gate should reopen once you wipe so that you can get access again. I believe the gat closes after initiating Ramstein the Gorger fight.

Thank You

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1540
