### ISSUE TITLE
[EN][Quest][Stonetalon mountains] Final delivery

### ISSUE THREAD

**Issue by BAndysc** [Atlantiss/BugTracker#3021]
Quest [Final Delivery](http://www.wowhead.com/quest=26077/final-delivery) isn't scripted.

Fix: http://atlantiss.eu/community/viewtopic.php?f=133&t=1687

**Comment by Bildo** [comment]
fixed

**Comment by Beatit** [comment]
nie działa, balon cały czas się buguje ;/

**Comment by Bastion** [comment]
chwile działało :D

**Comment by Bildo** [comment]
dziala sprawdzalem przed sekunda >.<

**Comment by Beatit** [comment]
Bildo tak działa, że pierwszy przelot próbowałem zrobić 2 miesiące i jakoś po 2 miechach zatrybiło, a ten próbuje od tygodnia i balon zbugowany cały czas w wodzie jest zamiast przy platformie...

**Comment by Bildo** [comment]
no nie gadaj wczoraj przyszedlem i fakt balon byl na dole ale wystarczy wejsc do wody i wtedy mozna go kliknac

**Comment by Beatit** [comment]
no właśnie w 99% nie można, bo wyskakuje ze Ballon jest za daleko od Ciebie czy coś takiego
