### ISSUE TITLE
[EN][Quest][Instance][Stratholme] The Great Fras Siabi

### ISSUE THREAD

**Issue by Cassedy** [Atlantiss/BugTracker#3022]
The quest " The Great Fras Siabi" doesnt work.

http://www.wowhead.com/quest=5214/the-great-fras-siabi

The crate near the mailbox isnt lootable, so the questmob doesnt spawn and the q is uncompletable.

http://www.wowhead.com/npc=11058/fras-siabi

**Comment by Quellz** [comment]
Quick update, the NPC did spawn for me, but there were no items inside the mailbox for me.

**Comment by RastaTinu** [comment]
Quest still doesn't work

**Comment by sigmundfreud2016** [comment]
Still

**Comment by TranceAccount** [comment]
Bump

**Comment by tomatosz** [comment]
bump

**Comment by aendry** [comment]
still bugged

**Comment by Bildo** [comment]
fixed
