### ISSUE TITLE
[EN][Quest][Icecrown] New Recruit

### ISSUE THREAD

**Issue by iprotocol** [Atlantiss/BugTracker#3023]
http://www.wowhead.com/quest=13143/new-recruit

The mob becomes a temporary pet (as expected) but then one of two things occur of which neither is the proper outcome:
it doesn't become friendly and continues to attack the player preventing the quest from continuing,

or

it becomes friendly but still attacks the player and follows them around the entire zone.

**Comment by jasiu666** [comment]
Also you should only need to escort that mob to the rock formation where the lone abomination is (not all the way back to the questgiver).

I managed to finally complete that quest after long time. You need to drag the Lithe Stalker to the rock formation then jump down and wait untill the debuff wears off. Then you'll need to transform into geist (Eye of Dominion), slap the Lithe Stalker with your third ability so he falls down and drag him to the quest giver.

cheers

**Comment by Illusionist87** [comment]
bump. The quest is broken. The thing that follows you can't follow you across the rocks to the quest giver. So the quest can't be completed.

I tried the tactic explained above but was unable to finish the quest that way.

**Comment by Bildo** [comment]
fixed
