### ISSUE TITLE
[EN][Quest][Orgrimmar] Stealing From Our Own

### ISSUE THREAD

**Issue by sashatje** [Atlantiss/BugTracker#3024]
Upon finishing Stealing From Our Own (http://www.wowhead.com/quest=26233/stealing-from-our-own) quest in Orgrimmar, the quest does not get market as done for the achievement Lest Do Lunch: Orgrimmar (http://www.wowhead.com/achievement=5475/lets-do-lunch-orgrimmar). So, basically, you can't get the achievement.

**Comment by Cassedy** [comment]
I can confirm that bug.

**Comment by Maczuga** [comment]
Perhaps beacause of the criteria: http://www.wowhead.com/spell=99249/stealing-credit
This one requires spell cast instead of quest complete.

**Comment by xolon** [comment]
For the achievement criteria is to complete 5 different daily quests including this one.

#1289
#1793

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/1793
