### ISSUE TITLE
[EN][Talent][Hunter] Serpent Spread

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#3025]
Serpent Spread: http://cata.openwow.com/spell=87935
Improved Serpent Sting: http://cata.openwow.com/spell=82834
Toxicology: http://cata.openwow.com/spell=82833
Serpent Sting: http://cata.openwow.com/spell=1978

When looking at my combat log I've noticed that the DoT of my spell Serpent Sting and the one caused by my Multi-Shot/Serpent Spread do the same base damage (1159) but different crit damage:

The normal SrS crits do 200% damage, but the MS/Serpent Spread crits do 300% damage.

![pic](http://i.imgur.com/y56oTHl.jpg)

I'm trying to think of an explanation, but as far as I know, Serpent Sting should do 150% base crit damage and 200% with 2 points in Toxicology. Am I forgetting something here?

(Btw, I've specced 2 points in Serpent Spread right now. Normally you'd only have 1 point in your cookie-cutter SV raid spec.)

**Comment by Jenovas** [comment]
There was a bug were all hunter survi spells crited for 300% due to toxicology (Black Arrow, Explo, Serpent), it seems I missed the Serpent Sting from Serpent Spread.

**Comment by xolon** [comment]
rip surv hunters 2015

**Comment by Jenovas** [comment]
Fixed in rev. 4397
