### ISSUE TITLE
[EN] [Spell] [Hunter] - Scatter Shot

### ISSUE THREAD

**Issue by vuze28** [Atlantiss/BugTracker#3027]
The 50% weapon damage from Scatter Shot sometimes breaks the disorient duration.

http://cata.openwow.com/spell=23601

**Comment by ShockRW** [comment]
The problems lies in not working Macro which most of the hunters use.
/#shotooltip Scatter Shot
/stopcasting
/cast Scatter Shot
When Iam using SS from spellbook (not macro'ed) it always seems to work, altough the macroed one fails very often which results in interrupted SS by autoshot, or MM mastery.

Do you use macro for SS like the one above ?

**Comment by Jenovas** [comment]
Closing.
