### ISSUE TITLE
[PL][Hunter] [spell] Black arrow

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#3028]
http://www.wowhead.com/spell=3674/black-arrow#changelog
black arrow powinien zadawać w 10 x 2850 = 28500 + crit 
narazie na atlantisie miałem z 23050 damage z  jednej strzały czyli 2088 x 10 + crit 
![image](https://cloud.githubusercontent.com/assets/8699987/7124853/9b1a6770-e22c-11e4-8962-8af03e418c4c.png)

**Comment by arekczup** [comment]
na razie bez bufów mam 1917 x 10 + crit

**Comment by arekczup** [comment]
narazie mi muj aspect of the hawk nie zwienksza mi spell pawera o 35 % tylko o 32-31%
muj spell pawer 11046 po uzyciu 14557 powino być 14912.1 
http://wow.gamepedia.com/Aspect_of_the_Hawk
11046 + 3866.1 [35 x 110.46] = 14912.1 z bufamy nam dochodzi do 500 spell pawera mniej

**Comment by Jenovas** [comment]
A skąd masz wartość 28500? Jakieś liczby cokolwiek? Czekam do jutra jak nie to zamykam.
