### ISSUE TITLE
[EN][Quest][Tanaris]Clamlette Surprise

### ISSUE THREAD

**Issue by sashatje** [Atlantiss/BugTracker#3029]
http://www.wowhead.com/quest=6610/clamlette-surprise

The questgiver does not give the quest.

**Comment by xolon** [comment]
You need to have cooking skill of 250-300 idr, but i did it week ago

**Comment by sashatje** [comment]
Oh you're right. 

How do I delete a ticket?

**Comment by xolon** [comment]
When you want to comment here next to the green "Comment" button there should be a red "Close issue" or smting like that
