### ISSUE TITLE
[EN][Al'akir HC]AOE dmg reduction doesn't work on pets

### ISSUE THREAD

**Issue by iskk** [Atlantiss/BugTracker#3030]
http://www.wowhead.com/npc=46753/alakir
http://www.wowhead.com/spell=91020/ice-storm

Pet in icepath gets full dmg (90% aoe dmg reduction doesn't work).
http://www.wowhead.com/npc=416/imp
http://www.wowhead.com/npc=11859/doomguard

I can confirm this on destro warlock + hunter's pets but i guess all pets/guardians receive full dmg instead of reduced.

**Comment by xolon** [comment]
also pets take full damage from black stuff on the puddles on maloriak heroic in black phase

**Comment by nevcio** [comment]
this probably applies to all aoe spells that cause damage through a debuff rather than damage directly

**Comment by Glare** [comment]
It was an issue aroud 8 months ago and it got fixed back then. I guess it came back with some of the recent revisions and if not, if it came with 4.3.4, may the God have mercy for all the warlocks, hunters and DKs for not reporting this earlier. This is a huge problem especially on Maloriak.

**Comment by Varchord** [comment]
> This is a huge problem especially on Maloriak.

Lol. Maloriak is nothing. 
AC HC mate
