### ISSUE TITLE
[EN][QUEST][Stormwind]Twilight Shores

### ISSUE THREAD

**Issue by azaze110** [Atlantiss/BugTracker#3034]
Yellow question mark appears on Fargo's head- and u cant talk with him. This bug unales to open a quest line in Twilight Highlands. Its pretty ridicoulos that its not repaired yet- and you close issues.

**Comment by Navedonar** [comment]
links

**Comment by azaze110** [comment]
Why you closed issue? What links you want? Just tell me and i will get it. The biggest issue is whole Twilight Shore- almost no quests that are not bugged(i found one- that i cannot check-arena quest, rest is bugged). There is whole place on map for the top level with no quests and pretty useless. At least answer if you are going to do it with something or maybe you have more important bugs to repair?

**Comment by Navedonar** [comment]
TH is closed.

**Comment by azaze110** [comment]
And is it oging to be open?

**Comment by azaze110** [comment]
Anytime, at least.
