### ISSUE TITLE
[PL][Quest][Maelstrom][Deepholm, Realm of Earth]

### ISSUE THREAD

**Issue by Grabc** [Atlantiss/BugTracker#3036]
Rozpocząłem quest, wszystko przebiegało bez problemu do momentu DC. Po zalogowaniu spadłem z quest mounta ginąc w teksturach. Zrespiłem się w Westfall, wracam do Stormwind i już nie ma możliwości powrotu ani do Maelstrom ani Deepholm. Quest anulowałem z nadzieją, że portal pojawi się znów, ale niestety go nie ma. Jest to mój pierwszy ticket, więc proszę o wyrozumiałość. Nie wiem jakie są możliwości rozwiązania problemu - jeżeli da się 'cofnąć' jeden quest i exp za niego, abym mógł sprobować ponownie ze Stormwind to byłoby miło. Ewentualnie teleportowanie mnie do Maelstromu.

**Comment by coocoo89** [comment]
Napisz ticketa w grze, a to jest do usunięcia.
