### ISSUE TITLE
[PL][PvP] Honor from BG and Kills

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#3037]
http://www.wowhead.com/currency=392/honor-points - honor pkt 
Na atlantissie dostajemy za mało pkt za odniesienie flagi/ killing blow 

https://www.youtube.com/watch?v=hb-HAvpcNsk - killing blow od 1 do 6honoru + o wiele większy zasięg łapania Honorowego zabicia.  w 4:00- 4:05 widać jak otrzymał 18 honoru za flag capa u nas jest to po 2/3 honoru, w 5:10 widać że po bg uzbierał 109 honoru 

https://www.youtube.com/watch?v=rkq3OKKywBA  6 /9 honoru za zabicie na tol Barad 

https://www.youtube.com/watch?v=sXq87MVs9PQ  4:39 18 honoru za cap flagi przez team

**Comment by michal1441** [comment]
There was a similar report where I summarised how much honor should be given, I will just copy it here:

"I did a research on the subject and here is what I found. Info on amounts of honor gained was hard to prove so I took a closer look at the videos from patch 4.3 where we can observe the amounts of honor gained.

Randon Battleground awards: 130 honor and 50 conquest points per win (270 honor and 100 conquest points on the first win of the day), 45 honor per loss

Honorable kill - 10 honor (split evenly between the players who are close to the target)

Source: https://www.youtube.com/watch?v=bGMbz-Op_HU http://eu.battle.net/wow/en/forum/topic/7257056493
These awards go to all the participants:

Warsong gulch:

capturing the opponent's flag awards 18 honor
win awards 45 honor
Source: http://www.wowwiki.com/Warsong_Gulch https://www.youtube.com/watch?v=Z7avhqEZPHE
Arathi Basin

Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
win awards 18 honor
Source: http://www.wowwiki.com/Arathi_Basin https://www.youtube.com/watch?v=yoi_m9bM9zU
Eye of the storm

Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
win awards 27 honor
Souce: http://www.wowwiki.com/Eye_of_the_Storm https://www.youtube.com/watch?v=pj1I2d9gvVs
Twin peaks

capturing the opponent's flag awards 18 honor
win awards 45 honor
Source: https://www.youtube.com/watch?v=0GUKi4ZmTS4
Alterac Valley

tower destruction awards 27 honor
captain kill awards 27 honor
general kill awards 36 honor
alive captain at the end awards 18 honor
undestroyed tower at the end awards 18 honor
Source: http://www.wowjuju.com/honor-and-battleground-explained-20071220 (1 kill was swapped with 9 honor during cata, videos are the proof) https://www.youtube.com/watch?v=NE1n8-gEgIw
Battle for Glineas:

Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
win awards 18 honor Source: https://www.youtube.com/watch?v=hX1xybZlQzU
Strand of the Ancients:

destroying a gate awards 9 honor
successfuly ending a round before the time ends (if attacking)/succesfully defending the Relic for the whole round awards 9 honor
win awards 27 honor
Source: https://www.youtube.com/watch?v=S77logRcPpo
Isle of Conquest

destroying a gate awards 18 honor
win awards 36 honor
controlling Rafinery and/or Quarry provides "a constant flow of honor" (2 honor per tick as seen in a video)
Source: https://www.youtube.com/watch?v=7qQQcTAOur0 http://www.wowhead.com/zone=4710/isle-of-conquest#comments https://www.youtube.com/watch?v=-Kku9GoIswA
If anyone has a better source or any corrections feel free to update this!"

Link to the report: https://github.com/Atlantiss/BugTracker/issues/2850

**Comment by Jenovas** [comment]
To fix this we need a list like this:
1. Killing a player gives 5 honor should give 10
2. WSG cap flag give 2 honor should give 16
3. AB points give 1 honor should give 2

etc. etc.

**Comment by MasterK15** [comment]
OK ill give it to you today

**Comment by MasterK15** [comment]
"I did a research on the subject and here is what I found. Info on amounts of honor gained was hard to prove so I took a closer look at the videos from patch 4.3 where we can observe the amounts of honor gained.

Randon Battleground awards: 130 honor and 50 conquest points per win (270 honor and 100 conquest points on the first win of the day), 45 honor per loss

Honorable kill - 10 honor (split evenly between the players who are close to the target)
Atlantiss - 1/2 honor for kill (1v1) 

Source: https://www.youtube.com/watch?v=bGMbz-Op_HU http://eu.battle.net/wow/en/forum/topic/7257056493
These awards go to all the participants:

Warsong gulch:

capturing the opponent's flag awards 18 honor
win awards 45 honor
Source: http://www.wowwiki.com/Warsong_Gulch https://www.youtube.com/watch?v=Z7avhqEZPHE

Arathi Basin
Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
win awards 18 honor
Source: http://www.wowwiki.com/Arathi_Basin https://www.youtube.com/watch?v=yoi_m9bM9zU

Eye of the storm
Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
win awards 27 honor
Souce: http://www.wowwiki.com/Eye_of_the_Storm https://www.youtube.com/watch?v=pj1I2d9gvVs
Twin peaks

capturing the opponent's flag awards 18 honor
win awards 45 honor
Source: https://www.youtube.com/watch?v=0GUKi4ZmTS4

Alterac Valley
tower destruction awards 27 honor
captain kill awards 27 honor
general kill awards 36 honor
alive captain at the end awards 18 honor
undestroyed tower at the end awards 18 honor
Source: http://www.wowjuju.com/honor-and-battleground-explained-20071220 (1 kill was swapped with 9 honor during cata, videos are the proof) https://www.youtube.com/watch?v=NE1n8-gEgIw

Battle for Glineas:
Collecting multiples of 260 (200 on holiday weekends) resources awards 9 honor
Atlantiss - 1 honor 
win awards 18 honor Source: https://www.youtube.com/watch?v=hX1xybZlQzU

Strand of the Ancients:
destroying a gate awards 9 honor
successfuly ending a round before the time ends (if attacking)/succesfully defending the Relic for the whole round awards 9 honor
win awards 27 honor
Source: https://www.youtube.com/watch?v=S77logRcPpo

Isle of Conquest
destroying a gate awards 18 honor
win awards 36 honor
controlling Rafinery and/or Quarry provides "a constant flow of honor" (2 honor per tick as seen in a video)
Source: https://www.youtube.com/watch?v=7qQQcTAOur0 http://www.wowhead.com/zone=4710/isle-of-conquest#comments https://www.youtube.com/watch?v=-Kku9GoIswA
If anyone has a better source or any corrections feel free to update this!"

Link do oryginału: #2850

I'll update this post every time i play different BG

**Comment by MasterK15** [comment]
Ok i need to be true, i don't play BG's a lot, and its hard to test all BG;s but on our server you get 1-3 honor points for Caps/point collection. i'll update this list but i think you can change all values for capping flags and point collection go 18 and 9

**Comment by Dean1989** [comment]
i can't find a table or formula on google for honor points, i think the devs need to get this infos into another core or everywhere they look for find formulas.
i'm a lvl 67 rogue and today i've killed a lvl 67 war in world pvp and i got 1.04 honor points, this is incorrect for sure.

**Comment by MasterK15** [comment]
DUMP

**Comment by MasterK15** [comment]
DUMP

**Comment by michal1441** [comment]
Why are you dumping this thread? It's not yet finished
