### ISSUE TITLE
[PL][NPC][STORMWIND] Larisse Pembraux

### ISSUE THREAD

**Issue by ysiu15** [Atlantiss/BugTracker#3038]
Nie ma mozliwości zakupu hierloomów dla tanka. 
http://www.wowwiki.com/Burnished_Pauldrons_of_Might
http://www.wowwiki.com/Burnished_Breastplate_of_Might
http://www.wowwiki.com/Bloodsoaked_Skullforge_Reaver

dodam także że nie można kupić spodni dla tanka u vendora gildii.

**Comment by Giq** [comment]
Hierloomy dla tanka doszły w MoPie
