### ISSUE TITLE
Heal reduction 

### ISSUE THREAD

**Issue by yomasek** [Atlantiss/BugTracker#3039]

**Comment by Bildo** [comment]
proofs ?

**Comment by Kejmil** [comment]
Heal reduction (25%) is like any other "raid" debuff - you don't see +8% magic dmg taken from dk, bala and lock working at the same time - they can be all present on target but only one of them is giving dmg boost.
Once upon a time i made list with all this debuffs and buffs on 4.0.6 bt, but i guess all of this got scrapped with it.
http://www.wowhead.com/spell=54680/monstrous-bite#changelog added in 4.1 so it wasn't on this list, dunno if more new spells with various effects got added with next patches before 4.3.4

**Comment by yomasek** [comment]
I know there can be several buffs on target but it stacks as I said.  If u want proof u can test It on your own.  I have currently no time to do it but as soon as I can I will try to update sth.  But as I said I tested it on hunter and he had 50% healing reduction in summary(real not just buffs)

**Comment by Kejmil** [comment]
http://imgur.com/eATr51z,kgbdKgB
i can confirm that this 2 buffs stacks up to 50% heal reduction, while they shoudn't
