### ISSUE TITLE
[EN][Rogue][Druid] Energy Regeneration from Buff's

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#3042]
Bloodlust: http://www.wowhead.com/spell=2825/bloodlust
Time Wrap: http://www.wowhead.com/spell=80353/time-warp
Heroism: http://www.wowhead.com/spell=32182/heroism

How it should work:
As we can read in links below (in 1st 5th paragraph) BL/TW/Hero should increase energy regeneration.

http://www.engadget.com/2011/02/02/encrypted-text-the-challenges-of-haste-and-energy-regeneration
http://fluiddruid.net/forum/viewtopic.php?f=3&t=449

How it works:
Bloodlust/Time Wrap/Heroism don't increase energry regeneration.

Observed on rogue combat buffed with Time Wrap.
Tested on rogue without talents on dummy
2x 50s spam sinister strike, 1st with BL buffed on <20 energy, 2nd without buff
in these two fights obtained the same amount of SS (14; with buff should be 17).

**Comment by Varchord** [comment]
What about stuff like berserking racial? Have you checked it?

**Comment by tnarf** [comment]
it seems that (lov energy per use, long cd) Berserking increases regeneration but
For 1lvl troll with Berserking regeneration is 11,81 (in "character info")
(diminishing return for energy regeneration? O_o)

**Comment by PlayFullTV** [comment]
Why isn't there anything here about attack speed reduction debuffs completely negating energy regeneration? It's literally the biggest issue for druids/rogues at the moment...

**Comment by Jenovas** [comment]
Negating meaning you dont regen energy but instead loss it by doing nothing?

**Comment by PlayFullTV** [comment]
Pretty much. Even on some bosses in dungeons etc. you are stuck @ 0 energy instantly. (2nd boss in Vortex Pinnacle, 2nd boss in Grim Batol for example. ALSO another major thing are the attack reducing debuffs frost mages put on you (and any other classes with similar debuffs of course) Your energy regen is pretty much halved.

**Comment by Jenovas** [comment]
ALSO another major thing are the attack speed reducing debuffs frost mages put on you (and any other classes with similar debuffs of course) Your energy regen is pretty much halved. - this is not true, please do tests.

Haste effects / attack speed effects are divided into like 10 different categories (by Blizzard) one category should effect the second shouldnt and so on. 

Please make a list of PvP skills that reduce regen and shouldnt and we'll have a look on them.

**Comment by Jenovas** [comment]
Fixed in rev 4413

If any other spells should or should not effect regen and they do on our server please create a new issue and tell us what it is.
