### ISSUE TITLE
[EN] [NPC] [Raid] [Cata] Twilight Ascendant Council

### ISSUE THREAD

**Issue by Atraac** [Atlantiss/BugTracker#3043]
1. Waterbombs should be thrown to random places around the room, not focused on players as it works now:
https://www.youtube.com/watch?v=jLZJRHClFvU
https://www.youtube.com/watch?v=IGlTm6abmHo

2. Gravity Core and Static Overload should both have the first tick 2 seconds AFTER being applied, right now they tick instantly therefore this tact is impossible to do:
https://youtu.be/RDsRT1UdOZ4?t=7m11s

3. Lava Seeds are still in the same places instead of pseudo random but it is already known.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838
Pomijam fakt, że to już drugi dubel.

2. Wcale nie tickują instantowo. Idzie uciec od osoby co to dostaje jeśli się ogarnie wystarczająco szybko.

**Comment by Atraac** [comment]
Sprawdzałem wczoraj na 25h, tickują wcześniej niż po 2 sekundach, po których powinny.

**Comment by Malylolek** [comment]
Filmik wrzucimy to będzie widać po ile dokładnie wchodzi !

**Comment by InformatorPE** [comment]
No Cecid licz sekundy https://www.youtube.com/watch?v=7KyQkKpSRo0&feature=youtu.be
