### ISSUE TITLE
[PL][Druid][Item] Ruthless Gladiator's Wildhide - bonus set

### ISSUE THREAD

**Issue by Bloodstomp** [Atlantiss/BugTracker#3045]
Trzeci bonus z setu http://cata.openwow.com/item=65552 nie działa.

**Comment by Kozuro** [comment]
Dokładnie.

**Comment by ziiomex** [comment]
no i chuj

**Comment by anket21** [comment]
potwierdzam

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/4034 duplicate
