### ISSUE TITLE
[NPC] Warcaller Gorlach incorrect walking animation

### ISSUE THREAD

**Issue by RocketeerRaccoon** [Atlantiss/BugTracker#3046]
This is only a minor bug but it's really funny but isn't how it's suppose to be, the npc known as Warcaller Gorlach who can be found walking around Orgrimmar has his walking animation bugged and as a result he looks like he's falling while walking around.

![wowscrnshot_032615_011855](https://cloud.githubusercontent.com/assets/1485170/7209796/ecfb23bc-e543-11e4-8eb0-ce81717e4188.jpg)
![wowscrnshot_032615_011858](https://cloud.githubusercontent.com/assets/1485170/7209797/ecfe51c2-e543-11e4-9b0e-202e4f0b3e39.jpg)
![wowscrnshot_032615_011902](https://cloud.githubusercontent.com/assets/1485170/7209798/ed01f444-e543-11e4-8598-828f5b84fb69.jpg)

**Comment by Bildo** [comment]
http://www.wowhead.com/npc=10880/warcaller-gorlach#comments
Just found him late at night walking past the bank and he was walking really funny. Sort of like he was floating forwards and having a seizure-like dance contest. It was the most odd way I've seen a npc move so far. Might have to do with the new Zandalari patch.

**Comment by Chevchelioz** [comment]
Please dont fix this i love it
