### ISSUE TITLE
[EN][talent][priest] Guardian Spirit

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#3048]
First of all i'll note the full explanation the game gives us about the spell;

Calls upon a guardian spirit to watch over the friendly target, increasing healing received by 60% and preventing the target from dying by sacrificing itself. This sacrifice terminates the effect and heals the target for 50% of maximum health. Lasts 10 sec.  Castable while stunned.

What i wanna talk about is the fact that there are 3 important things it needs to do;
1) increase healing received by 60% -> this works fine. 
2) Prevent someone getting oneshotted from a spell -> works fine.
3) When that person do get a killing blow, the guardian needs to sacrafice and give the player 50% of his HP. Now this isn't working at all. When we use it on certain occasions during encounters, the person gets to 1 hp after the guardian his 2 ability got activated. Now i don't think that is right is it? For example if you are doing chimaeron hc, there is a feud phase, and you put your GS on the OT, since he get's quiet some amount of dmg, he will get prevented from getting oneshotted, but it doesn't heal him to 50%. Now i don't really know if its really a heal what the spell does, so for example during the 2nd phase of chimaeron i can understand you don't get to 50% though i think it isn't really a heal but just from the moment the person with GS gets a killing blow, he needs to drop/rise to 50% HP. 

I tested some things; when i'm up in the air, i remove my mount and take the full fall damage but i put GS on myself. What i note was:
-128k fall dmg
+1 heal from Spirit of Redemption, no healz from GS or whatso-ever.
Though i transformed into my 'Spirit of Redemption'. Which is another bug. GS needs to have priority over my Spirit of Redemption and make sure i'm still alive and not in spirit form, since i think Spirit of Redemption gets activated on a killing blow, as is GS. This isn't correctly scripted. 

Testing this on a different character who doesn't have 'Spirit of Redemption' shows us that he just dies, even with GS. Though it shouldn't matter what dmg you take, you still get a killing blow, which should NOT happen when you have GS up on that certain target.

**Comment by mitim1** [comment]
dubel #2486

**Comment by Frainzil** [comment]
well i don't understand Polish... so I couldn't know..

**Comment by Jenovas** [comment]
"Guardian Spirit won't prevent death from fall damage" - can be found on wowpedia, wowwiki, wowhead. So jumping of a mount and saying it doesnt work is a bad way to test it.

**Comment by Frainzil** [comment]
Didn't know that, but still all the rest is true. We usually do not use a holy priest in our raids, but we wanted to try something different yesterday so we went v&t hc. Now when 1 of the person gets the blackout, you give him GS, dispel him, he always ends up with 1 hp. He was full HP before the dispel, 1 hp after the dispel. I think the other issue said something similar? the one in polish?

**Comment by Vyrtuz** [comment]
Bump? :D

**Comment by Jenovas** [comment]
Should be fixed in rev 5012
