### ISSUE TITLE
[EN][Quest][Redridge Mountains] Weapons of War

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#305]
After you complete the objective for "Weapons of War" (http://www.wowhead.com/quest=26571), a window should pop up to complete the quest, and after you do, you automatically get a new window to accept the next quest in the series, and that's "His Heart Must Be In It" (http://www.wowhead.com/quest=26573).

On our server, we have to go back to the NPC to turn in, and take the new quest, but that shouldn't be the case.

You can see how it works here - https://www.youtube.com/watch?v=sElFhhg7Hx8

Pause at 3:32, and you'll see that he gets "His Heart Must Be In It" automatically, after he completes "Weapons of War".

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14633-quest-weapons-of-war
