### ISSUE TITLE
[EN][Boss] Devourer of Souls

### ISSUE THREAD

**Issue by Cudownie** [Atlantiss/BugTracker#3050]
http://www.wowhead.com/npc=36502/devourer-of-souls

Phantom Blast - http://www.wowhead.com/spell=68982/phantom-blast cannot be interrupted. Boss is immune.
http://www.wowhead.com/achievement=4523/three-faced achivement cannot be complete

**Comment by Bildo** [comment]
This instance is currently rewriting

**Comment by eryczek1615** [comment]
This achievement is feasible to do, but very hard.
I did same  what the guy in the video https://www.youtube.com/watch?v=LXQ3Qu8mY90
If I made mistake in spelling this I sorry

**Comment by Quban** [comment]
Fixed in rev. 4432
