### ISSUE TITLE
[PL][NPC][The Bastion of Twilight] Cho'gall - worshipping

### ISSUE THREAD

**Issue by nevcio** [Atlantiss/BugTracker#3051]
http://www.wowhead.com/spell=91303/conversion
http://www.wowhead.com/spell=1776/gouge
gracze channelujacy conversion nie moga byc przerwani przez gouge rogue'a

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838
dubel

**Comment by Bildo** [comment]
jaki dubel ?

**Comment by Varchord** [comment]
Chcesz to mogę rozpisać każde swoje zgłoszenie. 1 skill bossa, jedno zgłoszenie

**Comment by Malylolek** [comment]
Dajesz Spite, będzie widać że coś się tu dzieje :P

**Comment by Bildo** [comment]
Mowilm ci juz kiedys, ze jak chcesz aby zgloszenie bylo dublem to zupdatuj swoj pierwszy post, komentarze jak sama nazwa wskazuje sluzy do komentowania bugow, a nie do ich zglaszania, takze dopoki nie zupdatujesz 1 post o ten bug tak ten bug nie bedzie duplikatem.

**Comment by Varchord** [comment]
Wiesz bildo. Niektórzy sa na tyle inteligentni żeby szukac czy nie istnieje juz temat o nosie i pisac w komentarzach.
Przykład Dungeon Finder issue. Znajdź mi buga którego nie ma w main poście, a ktos w komentarzach zgłosił.

Jeszcze bym rozumiał takie pierdolenie jakbym swoich postów nie updatowal. Ale hej. To w końcu salg będzie musial po 20 zgłoszeniach szukać czy nie bylo jakiegoś update/zmiany/dodanego buga. Nie ja

**Comment by Varchord** [comment]
A duplikatem jest caly report bossa. Równie dobrze mógłbyś sie przyjebac jak ktos zglosi, ze w skillu x nie działa y, a ktos drugie zgłoszenie otworzy ze w skillu x nie działa z zamiast dopisać do poprzedniego

**Comment by Varchord** [comment]
O, przykład. 2 identyczne zgłoszenia, bo tak lepiej zgłaszać. Ktoś trzeciego buga znajdzie to kolejne zgłosznie powstanie

https://github.com/Atlantiss/BugTracker/issues/906
https://github.com/Atlantiss/BugTracker/issues/2881
