### ISSUE TITLE
[PL][Twilight Highlands][Fishing] Deepsea Sagefish School

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#3055]
Link Deepsea Sagefish School: http://www.wowhead.com/object=208311/deepsea-sagefish-school
Link Algaefin Rockfish: http://www.wowhead.com/item=53071/algaefin-rockfish
Link hotfix: http://us.battle.net/wow/en/blog/4023884

Od patcha 4.3 Algaefin Rockfish School w Twilight Highlands zostały zastąpione Deepsea Sagefish School. U nas niestety nadal są te pierwsze. Natomiast Algaefin Rockfish powinny być dostępne do złowienia na otwartych wodach bez szkółek.

Dowód w postaci hotfixów w linku na górze: "Algaefin Rockfish no longer swim in schools, and schools of Deepsea Sagefish have taken their place along many coastlines."

**Comment by Navedonar** [comment]
.

**Comment by gally9** [comment]
Yes, it gives us problems to farm sagefish to make these important recipes for raids:

http://www.wowhead.com/spell=88016/delicious-sagefish-tail

http://www.wowhead.com/spell=88039/severed-sagefish-head

**Comment by tomatosz** [comment]
bump

**Comment by tomatosz** [comment]
Posted fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14753-gameobject-deepsea-sagefish-school/

**Comment by Jenovas** [comment]
Fix in 5539
