### ISSUE TITLE
[PL][Hillsbrad Foothills][Quest] Basic Botany

### ISSUE THREAD

**Issue by cuba1984** [Atlantiss/BugTracker#3056]
Po wzięciu tego questa od Brazie the Botanist:
http://www.wowhead.com/quest=28733/basic-botany
wyskakuje od razu komunikat "Failed". 
Jest to chain z 5 questami, i w nagrode mozna zdobyc fajnego peta:
http://www.wowhead.com/item=66067/brazies-sunflower-seeds
Na filmiku przedstawiono jak to powinno wygladac:
https://www.youtube.com/watch?v=fg-CFAHzM5o

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/974
