### ISSUE TITLE
Soul Link + Earth Shield = nie działa

### ISSUE THREAD

**Issue by ppiinniioo** [Atlantiss/BugTracker#3059]
Witam, Gm sprawdzal to już ze mną i kolega :) Kiedy Lock ma Soul Linka, to Shield na nim nie dziala, nie schodzą mu staki i nie leczy. Jednak kiedy Lock wyłączy Soul Linka, to Shield zaczyna dziala i stacki schodzą :)    Pozdrawiam i liczę na pomoc z tym :)
[PL][Skill][Shaman][Warlock]

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/1416 doubled
