### ISSUE TITLE
[EN][NPC][Sholazar Basin] Thalgran Blightbringer - No Deathbolt

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3061]
The NPC Thalgran Blightbringer (http://www.wowhead.com/npc=28443/thalgran-blightbringer#abilities), does not cast Deathbolt. It should cast Deathbolt (http://www.wowhead.com/spell=51854/deathbolt).

This ability is important to the completion of the quest Returned Sevenfold (http://www.wowhead.com/quest=12611/returned-sevenfold).

**Comment by Scorpio185** [comment]
now, he casts Deathbolt too often... Ward is still on cooldown when he kills you with another Deathbolt :)
