### ISSUE TITLE
[EN][Quest] In Defense Of Krom'gar Fortress

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#3062]
In the quest **In Defense Of Krom'gar Fortress** (http://www.wowhead.com/quest=26058), all the **Goblin Heavy Guns** (http://www.wowhead.com/npc=41895) are missing, and they are needed in order for flying enemies to even appear, I'm guessing it's a phasing thing when you mount the gun, but anyway, they are missing, so you can't complete the quest.

The video of the quest being done: https://www.youtube.com/watch?v=sKM2TP3Hveg

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/907

**Comment by Enay** [comment]
Same as the other one D:
