### ISSUE TITLE
[EN][Quest] We're here to do one thing, maybe two...

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#3064]
In the quest **We're here to do one thing, maybe two...** (http://www.wowhead.com/quest=25945), you can't interact with **Krom'gar Wagon** (http://www.wowhead.com/npc=41744), so the quest can't be completed. 

You should be able to "mount it" and then it should take you to **The Fold** in **Stonetalon Mountains**, which also completes this quest upon arrival.

Strangely enough, in some videos on youtube, some people don't even use the wagon, but just go there on their mounts, and complete the quest directly, which I found strange, since the objective is to take the wagon to **The Fold**, so I'm not sure what to make of that.

Either way, you can't ride the wagon here, and you can't complete the quest by going to **The Fold** on your own, so it can't be completed in any way.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/906
https://github.com/Atlantiss/BugTracker/issues/2881

TBH I find it strange that there are 2 marked issues.

**Comment by Enay** [comment]
Strange, when I searched, nothing came up.
