### ISSUE TITLE
[PL][Quest][The Storm Peaks] Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by RelmAtlantiss** [Atlantiss/BugTracker#3065]
Quest da się wykonać (Objective Complete), ale nie da się go oddać. Thorim, który powinien zostać w Thunderfall znika, a to u niego oddaje się quest.

![thorim](https://cloud.githubusercontent.com/assets/11969548/7240503/ae84f69c-e7b1-11e4-9453-2ecc44322e0b.jpg)
http://www.wowhead.com/quest=13010/krolmir-hammer-of-storms
Current revision: 4401

**Comment by Bildo** [comment]
fixed
