### ISSUE TITLE
[EN][NPC] Therazane the Stonemother

### ISSUE THREAD

**Issue by MosOpinca** [Atlantiss/BugTracker#3072]
Even thou for some time this NPC problem was solved - Therazane , The Stonemother- as of this morning it's inactive for me . Can't interact with it in any way , Tried the "at war" strategy ... no luck ..can't attack here . So ... there is no way to get the quest chain to advance . ( name of character Tankzilla)

LE :After i've made the above entry( about 6:30 am server time) I've made an ingame ticket and left for work. The ticket was still open when i came home and tried the game (~1:30  PM server time) with no sign that a GM had done anything about it ( maybe he did and i didn't figured out) but, upon trying again to deliver the quest it worked . The NPC Therazane worked as it should be and I was able to interact with it. So it seems that this problems either comes and goes without any ideea on how to replicate it , or it is known to GMs and they might have an ideea on what is going on.

**Comment by Aival94** [comment]
might be better to post it in the already open one and close this one: #2542

**Comment by MosOpinca** [comment]
Not really ...I think that the porblem resides either in the NPC or the quest line somehow 
At about 3:30 pm after reciving the quest Wayward Child http://www.wowhead.com/quest=28824/wayward-child
I proceded in turning it in at the NPC located in Therazane's Throne ( found a copy of the NPC at 62,25  that gave me a couple of other quests that I could finish and turn it at that second doubled NPC - coudnt turn in Wayward Child thou) .
One of the quests was The stone throne http://www.wowhead.com/quest=26709/the-stone-throne which upon completion should be turned in at the NPC located at Therazane's Throne . Couldn't turn it in even tho the NPC is there.
