### ISSUE TITLE
Human lvl 3 Prist  "Healing the Wounded" (Cataclysm) DOES NOT WORK. EARLY GAME. 

### ISSUE THREAD

**Issue by Mooteddy** [Atlantiss/BugTracker#3073]
The quest Healing the Wounded is giving right at the beginning after you kill the wolfs and some of orcish spies. It's a class quest. The thing you need to do is to heal wounded Stormwind soldiers. 

The problem is this: Whenever you heal - or "try" to heal - a wounded soldier, the character heals himself. I also try to disable "auto-cast"  and I realized that you cant even highlight the NPC. It's like the NPC isn't even there in the first place. 

However, the quest doesn't work.. and it's one of the first quests in the game. Is there a way around it?

**Comment by Navedonar** [comment]
bt rules
