### ISSUE TITLE
[PL][Spell][Hunter] Lock and Load

### ISSUE THREAD

**Issue by armaw** [Atlantiss/BugTracker#3074]
http://www.wowhead.com/spell=168980/lock-and-load http://www.wowhead.com/spell=53301/explosive-shot
Lock and Load powoduje, że możemy użyć "Explosive shot" bez żadnego kosztu focus'a.
Na serwerze występuje bug że drugiego darmowego explosive shot'a nie można użyc jeśli nie ma sie focusa na explosive shot (40 focus), użycie drugiego darmowego explosive shot'a jest darmowe ale ta przerwa przez brak focus'a na kolejny strzal explosive shot'em powoduje luki w rotacji.

**Comment by mitim1** [comment]
DUBEL

**Comment by mitim1** [comment]
#1803
