### ISSUE TITLE
[EN][Spell][Jewelcrafting] Prospecting

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#3075]
Upon using the prospect spell on 20 ores, since the newest update, it uses 10 ore instead of 5(actually uses 5 and removes another 5 of them instantly) and gives only the amount of gems you can get out of 5 ore. (only tested it on elementium ore) Spitting them up in groups of 5 ore do works and you will get your gems, i'm only talking than when it's a pack of 20 ores, it bugs out when you prospect them.

**Comment by krecik88** [comment]
fixed in 4409

**Comment by krecik88** [comment]
fixed
