### ISSUE TITLE
[EN][Spell][Archaeology] Survey

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#3076]
The survey spell itself works, you get a telescope showing you were to go and you will find the spot with the ''loot'', but upon opening it, you get nothing and the loot item disappears and you get no fragments. (this also only happened after the update of 22/04)

**Comment by mitim1** [comment]
rev 4412. Working again

**Comment by krecik88** [comment]
It is fixed temporary, need to work still on it.

**Comment by krecik88** [comment]
fixed
