### ISSUE TITLE
[EN][Item] Stormwake The Tempest's Reach / Al'akir sword disappearing stats

### ISSUE THREAD

**Issue by Stupify** [Atlantiss/BugTracker#3078]
Yesterday (21.4.15)  I recived Stormwake the Tempest's Reach from Al'akir at the Throne of the Four Winds (normal mode). 
http://tinyurl.com/mxnbv8f

With the following stat combination:

...of the Stormblast
+146 Agility, +219 Stamina, +97 Hit, +97 Critical Strike

After several hours I noticed that my sword has only one stat and it's Hit. Crit rating disappeared mysteriously. It's probably because of relogging but still it shouldn't be possible for the stats to disappear.

http://tinyurl.com/stormwake

Now the 'fun' part begins:
Whenever I want to reforge the sword, Crit rating is listed but not reforgable - I mean when I picked he stat from the list to reforge into another but nothing happens when I click the reforge button.

http://tinyurl.com/stormwake1

The sword only gives me the stats that are currently listed, so the Crit rating is absent:

http://tinyurl.com/stormwake2

As you can see both Fang of Twilight and Stormwake have the same amount of Crit rating so it should remain unchanged in my stats.

**Comment by Frainzil** [comment]
i have the same problem, but a healers version, i do not receive the spirit. Now i talked about a gm about this and it has something to do with the loot of al'akir and the random stat table. He told me he couldn't do anything to fix this and that i just had to find a different sword, i guess you will have to do the same.

**Comment by Caturix** [comment]
Bump, this shitty bug is still not fixed. Either remove the weapon out of loot table or fix it! :-1:

**Comment by meowmewo** [comment]
Bumb

**Comment by LaveGit** [comment]
Bump :3

**Comment by fafal** [comment]
buuump, cause caturix says to come here ;c

**Comment by xolon** [comment]
Better fix belts and ring w/o any stats which drop in here

**Comment by Bastion** [comment]
no axe here

**Comment by Caturix** [comment]
really, low priority? Something simple as this :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by Wolffenstein** [comment]
This is the last time I allow these kind of bumping actions and posting bugs on the forum. The next time someone does it, there will be punishment involved.

Fixed in rev 4701. Bear in mind, that it will NOT fix already bugged weapons in your inventory. Their stats are gone forever.
