### ISSUE TITLE
[EN] Tol Barad queue

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#3079]
Queuing for TB doesn't work. If you get there on foot during the battle, you get kicked to your faction's camp.

**Comment by Jenovas** [comment]
Tolbarad throws out players if one faction has more players than the other. Say there is 15 ally vs 15 horde, if you queue it wont let you enter, if you go by foot you'll be kicked out. This is Blizzlike. Closing.

**Comment by Helbringer** [comment]
This is no longer working as it should and i finally have overwhelming proof...
![wowscrnshot_062315_021207](https://cloud.githubusercontent.com/assets/10423624/8296908/66fac15c-194e-11e5-91a6-cd303bf864d1.jpg)
As allience have far many more players, tol barad is completely unbalanced and not fun for horde, most horde do not join anymore as a knock on affect.
