### ISSUE TITLE
[EN][Dire Maul] Prince Tortheldrin

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#3080]
http://www.wowhead.com/npc=11486/prince-tortheldrin

is spawned twice.

**Comment by ahtebe** [comment]
And also does 3x the damage he should do. He currently hits 500 to 600 on a normal melee hit on 32,43% armor reduction (bear tank with heirlooms) whereas he should hit for 130 - 290 on a tank as shown in this video: https://www.youtube.com/watch?v=zQcjryeNHs4
