### ISSUE TITLE
[ENG][Quest Item's]Missing

### ISSUE THREAD

**Issue by TheLichWarrior** [Atlantiss/BugTracker#3081]
]Zone:Ruins of Gilneas
Location:The Black Wald
Quest:Preparations
Hello so far server is good only problem i found was with the quest above on patch 4.0.6 quests items   Moonleafs were there but now on 4.3.4 they are missing pls fix it.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
