### ISSUE TITLE
[ENG][Quest]Effect

### ISSUE THREAD

**Issue by TheLichWarrior** [Atlantiss/BugTracker#3082]
Zone:Ruins of Gilneas
Location:Tempest Reach
Quest:Betrayal at Tempest Reach
Quest is working good only problem is when i atack lord Walden some blurry effect apears on all screen and it doesnt disapear afther thet visibilty is so low fix it ty.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
