### ISSUE TITLE
[EN][Profession][Ironforge] Can't fish in Ironforge

### ISSUE THREAD

**Issue by CyricPoL2** [Atlantiss/BugTracker#3086]
Currently fishing in Ironforge doesn't work. When you try to fish in The Forlorn Cavern (only spot in Ironforge that should be fishable) it just gives an error "You can't use that here."

That makes http://cata.openwow.com/achievement=1837 unobtainable

**Comment by qolo** [comment]
Fishing in Undercity isn't working as well.

**Comment by sunshineinabox** [comment]
Also in Dalaran

**Comment by Bildo** [comment]
fixed by Wolfenstein
