### ISSUE TITLE
[EN][RDF/Quests][Major Bug] Item is still being rolled for errors

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#3087]
Okay, so I've run into this problem in several dungeons that I went to through the dungeon finder, and I'm pretty sure it's going to keep happening in all the future dungeons that I do, as long as I go into them through dungeon finder.

For all the following quests, you keep getting "*Item is still being rolled for*" message, and you can't pick up the item because of it.

# Razorfen Kraul

In the quest **Going, Going, Guano!** (http://www.wowhead.com/quest=26901), you can't pick up **Kraul Guano** (http://www.wowhead.com/item=5801).

In the quest **Agamaggan's Charge** (http://www.wowhead.com/quest=26905), you can't pick up **Razorflank's Heart** (http://www.wowhead.com/item=5793).

# Uldaman

In the quest **We Require More Minerals** (http://www.wowhead.com/quest=27682), you can't pick up **Obsidian Power Core** (http://www.wowhead.com/item=62053) and **Titan Power Core** (http://www.wowhead.com/item=62055) .

Anyway, I'm pretty sure that this is all due to rdf, rather than quests being bugged, but I wrote those up there anyway. I need to test if the quests will still be bugged if I go in manually and solo, rather than using RDF.

Going to update this soon, after I test it.

Update:
Okay, so I hopped on to my warrior (85) and went to uldaman, and I have completed that **We Require More Minerals** quest when I was leveling, it seems. So, this bug is something that came along in one of the recent updates that you guys did. Still not sure about soloing it now, but I'll try it when I get this new character to level 60 and get a flying mount.

**Comment by Dean1989** [comment]
same problem with the wailing caverns and shadowfang keep (just the 2 dg i did with the rdf)

**Comment by Dean1989** [comment]
can we have this bug set in high priority pls?

**Comment by Dean1989** [comment]
with the latest maintenance the loot is back to normal

**Comment by krecik88** [comment]
It is fixed temporary, need to work still on it.

**Comment by krecik88** [comment]
fixed
