### ISSUE TITLE
[EN][Quest] The Platinum Discs

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#3088]
In the quest **The Platinum Discs** (http://www.wowhead.com/quest=2278), **Lore Keeper Norgannon** (http://www.wowhead.com/npc=7172) is completely missing, making it impossible to finish the quest, as the objective is to learn the lore from him by going through a lengthy dialogue with him.

Also, after you complete this quest, you should get **The Platinum Discs** (http://www.wowhead.com/quest=2280) (different quest), but here, they are both given to you at the same time. This 2nd quest can be completed, though, but it should only be available after the 1st one is finished.

Youtube video of the quest being done: https://youtu.be/j9AyMOu1tzg?t=21m20s

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1144

**Comment by Enay** [comment]
Sigh, I never get any results in search, I don't get it. -.-
