### ISSUE TITLE
[EN] Tol Barad queue

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#3089]
Responding to
https://github.com/Atlantiss/BugTracker/issues/3079

There is currently no way of queuing or entering the battle.
You can't queue even via the PvP interface (i tried a few minutes before the battle and when it didnt work - after it started). Even if the bg is full (and it was totally empty), the server should put you into a queue in case someone leaves and you can take his place. After the GUID update clicking "Join battle" does nothing, entering TB by foot results in an empty window showing up, with buttons "cancel" and "accept", which do nothing, and then, after a few seconds, a kick WITH NO QUEUEING. I was playing the Alliance side. The Horde was unable to get in too, and the battle ended with our win (defending), because the battleground was empty.

**Comment by Kejmil** [comment]
raid only for one side of the conflict isn't really blizzlike

**Comment by Cassedy** [comment]
Can confirm the bug. Same on Hordeside as described above.

**Comment by mitim1** [comment]
After rev 4412. working again :)

**Comment by krecik88** [comment]
It is fixed temporary, need to work still on it.

**Comment by aneq** [comment]
gamebreaking bug abused mainly by alliance
queuing by using the npc near tol barad portal entirely bypasses the queue and the player limit (so alliance usually outnumbers horde)

**Comment by Kejmil** [comment]
55 vs 29 woohooo, such balance

**Comment by molesterman69** [comment]
would be nice if the queue could get fixed, you can't win if the enemy outnumbers you 1:2...

**Comment by molesterman69** [comment]
would be nice if the queue could get fixed, you can't win if the enemy outnumbers you 1:2...

**Comment by Kejmil** [comment]
there is still issue with queuing, due to it alliance mostly outnumber horde 2 to 1

**Comment by Jenovas** [comment]
Is the queue bugged or is there still a npc that allows to bypass the player limit?
If it's a NPC please give me it's name.

**Comment by Kejmil** [comment]
there is no npcs for now, but problem still persist
It is also a little more complicated, because from what i remember up to 25 ppl (?) there was no balancing sides, after that horde=ally (at least at one of the patches of cata)
but when i was sniffing tol barad other day with giqu on mop/wod i remember that there was lower than 10 ppl in each factions and balancing was active from the start

**Comment by meowmewo** [comment]
Lost probebly the last 10-15 TB battles on horde side due to Alliance clearly being 2/3x more then horde. At this point im starting to think that this problem is just not taken care of on purpose.

**Comment by Jenovas** [comment]
meowmewo - think what you want.
Kejmil - with Mop I think the queue system changed to start balancing when there is more than 5A-5H.

**Comment by Kejmil** [comment]
i think that making it in MoP way will be most beneficial to our server with current population

**Comment by davesmix** [comment]
I have stopped donating to this server because of this issue. It is a serious issue and hurts Horde extremely. Until it gets fixed they won't see a dime of my $$

**Comment by Thefakemccoy** [comment]
So today i was notified bt the normal message Tol Barad in 15 mins. So I go ahead a queue up instead of a BG. My friend comes on to do some BGs i tell him im in queue for TB. So he queues up. He get a invite to TB and i did not when i was queued up 10mins prior to him coming online.

**Comment by Fapguy** [comment]
Please fix TB fast.
