### ISSUE TITLE
[PL] [Proffesion] [Archeology] Archeology fragments

### ISSUE THREAD

**Issue by HUMBOL** [Atlantiss/BugTracker#3095]
Dzisiaj latając za archeologią, dokładnie w miejscach gdzie są artefakty night elfów (Stonetalon Mountains - Stonetalon Peak oraz Darkshore - Nazj'vel) po wykopaniu artefaktu i zebraniu go nie dostałem żadnych fragmentów. Nie mam jak zrobić screena, w każdym razie koleżanka też robiła i miała ten sam problem, dodawało jej skilla i expa, ale nie zbierała żadnych fragmentów.

**Comment by Dargorad** [comment]
W Redridge Mountains i Burning Steps zbierałem "Fossil", lecz fragmenty w ogóle nie wypadały. Okienko Lootowania było puste.

**Comment by HUMBOL** [comment]
http://screenshooter.net/101984253/bdehgap

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3076

**Comment by mitim1** [comment]
rev 4412. działa

**Comment by krecik88** [comment]
It is fixed temporary, need to work still on it.

**Comment by krecik88** [comment]
fixed
