### ISSUE TITLE
eye of eternity

### ISSUE THREAD

**Issue by murdurer** [Atlantiss/BugTracker#3096]
first time i went in , used the key , got to phase 2 and when phase 3 should start we didint get dragons , nothing happened except him flying arround the platform untargetable. got saved
secound time i tryed we actually got dragons but the boss was ,,,noowere he dissapeared. got saved.
....fix pls?=)

**Comment by mitim1** [comment]
https://github.com/Atlantiss/BugTracker

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2347
