### ISSUE TITLE
[EN][ITEM] Shard of Woe

### ISSUE THREAD

**Issue by Vergos** [Atlantiss/BugTracker#3098]
http://www.wowhead.com/item=60233/shard-of-woe#comments
http://wow.gamepedia.com/Shard_of_Woe

Shard of Woe was initally reducing all spellcasts costs by 405 mana, being later nerfed to base reduction of 205 mana on all BUT Holy and Nature spells.

http://us.battle.net/wow/en/blog/2259389

February 15
...
Items
Shard of Woe (Heroic trinket) now reduces the base mana cost of spells by 205, with the exception of Holy and Nature spells -- the base mana cost of Holy and Nature spells remains reduced by 405 with this trinket.

On Atlantiss, Nature spells costs are being reduced only by 205 mana. (I guess the same applies to Holy spells, but I am unable to test this)

**Comment by Jenovas** [comment]
On patch 4.3 the trinket got nerfed to 205 for ALL spells.
Closing.
