### ISSUE TITLE
[PL][Profession] Jewelcrafting

### ISSUE THREAD

**Issue by spell406** [Atlantiss/BugTracker#310]
Crafting podanych poniżej itemów powinien mieć szansę ( około 10%) na stworzenie niebieskiej wersji itemu.

http://www.wowhead.com/item=52308 -> http://www.wowhead.com/item=52316
http://www.wowhead.com/item=52309 -> http://www.wowhead.com/item=52314
http://www.wowhead.com/item=52306 -> http://www.wowhead.com/item=52310
http://www.wowhead.com/item=52307 -> http://www.wowhead.com/item=52312

**Comment by sigmundfreud2016** [comment]
Confirm, still bugged. Made about 150 http://www.wowhead.com/item=52306/jasper-ring, not even a single one was blue.

**Comment by pelekon** [comment]
fixed in rev  5859
