### ISSUE TITLE
[EN] [Item] [Guild] Guild Charter Signatures

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/BugTracker#3102]
I have purchased a Guild Charter,
http://www.wowwiki.com/Guild_Charter
& require 4 signatures to complete and 
start a PvP Guild. I have one signature
so far, yet have made 4 other attempts
with helpful people to sign the charter, but
NOOP, it won't open/activate/show in the
signee's game window. They all say that
"Block Guild Invites" is not selected, and
the last attempt was made by a kind person
who actually /gquit, so it is a definite BUG.

Plz help or auto the Guild Charter to a Guild.

Appreciatively,
SwimzwithSharkz

* other than this and a few other minor glitches, 
rly enjoying Atlantiss, TY

**Comment by Liebeqt** [comment]
This issue was created 23 days ago, but I was able to create a guild without problems sometime after it was made.

**Comment by Jenovas** [comment]
Because 23 days ago we added the new guid system to the server, after that there were to many bugs with the new guid system so we reverted the changes and a few days ago when we fixed most of the problems and we added them again.

**Comment by Liebeqt** [comment]
Thanks for a clarification, hope it's solved soon.

**Comment by krecik88** [comment]
fixed in 4431
