### ISSUE TITLE
[EN][Spell][Paladin] Holy Light

### ISSUE THREAD

**Issue by Hordewolf** [Atlantiss/BugTracker#3103]
Currnetly in Mulgore, Bloodhoof Village where I leveled up to 07. Spell book told me the "Holy Light" ability was available "See your Trainer" Went to the Paladin Trainer though the NPC says I can only get at level 14.

Spell Book: http://i.imgur.com/K5PURwp.jpg
Paladin Trainer: http://i.imgur.com/UZMG2H9.jpg

**Comment by mati865** [comment]
http://cata.openwow.com/spell=635
