### ISSUE TITLE
[EN][Quest][The cape of stranglethorn] Through the Troll Hole

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3107]
http://www.wowhead.com/quest=26811/through-the-troll-hole 
auto pop-up quest part of the chain quest 
http://www.wowhead.com/quest=26819/akiris-by-the-bundle

after you turn in http://www.wowhead.com/quest=26810/eliminate-the-outcast the quest don't pop-up and you can't continue the chain, the portal is here but i don't know if the rest of the chain is scripted.

video: 
https://www.youtube.com/watch?v=Nz1Xx9DQ3W4
https://www.youtube.com/watch?v=83RWurfNLHQ

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/354
