### ISSUE TITLE
[PL][Pilgrim's Bounty][Orgrimmar][Object] The Pilgrim Chair

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#311]
Na niektóre z krzeseł na Durotarze nie można wejść. Znajdują się trochę dalej przez jeżdżących na nich graczy - trzeba to usunąć :/ - może to przez to? Nie jestem w stanie pokazać gdzie one są ale są to:
The Cranberrry Chair            - http://www.wowhead.com/npc=34823/the-cranberry-chair 
The Turkey Chair                  - http://www.wowhead.com/npc=34812/the-turkey-chair
The Stuffing Chair                 - http://www.wowhead.com/npc=34819/the-stuffing-chair
The Pie Chair                        - http://www.wowhead.com/npc=34819/the-stuffing-chair
The Sweet Potato Chair        - http://www.wowhead.com/npc=34824/the-sweet-potato-chair 
Utrudnia to zrobienia Achievement'u ;(... Zwłaszcza, że Cranberrry jest tylko jedno... :<

**Comment by TranceAccount** [comment]
#425
