### ISSUE TITLE
[EN][shaman]Fire elemental cannot be controlled in any way

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#3110]
The fire elemental does not obey /petattack or /petfollow commands like other guardians (gargoyle etc)
this is really frustrating because the elemental has 120 second duration and on fights with a lot of target switching (like omnotron) it is useless (and this is a large chunk of elemental dps)

**Comment by Nc94** [comment]
And it shouldn't Fire Elemental should prioritize target with Flame Shock DOT like Searing Totem and that mechanic was buggy even on retail.
http://www.mmo-champion.com/threads/932756-Fire-elemental-totem-question

P.S. Ebon Gargoyle is Construct not Guardian
P.S.1 You're playing ELE Shaman on retail and that command doesn't work there either... Fire elemental attacks target that shaman is attacking and switch itself 1-2 sec after shaman start attacking other target (just testet on dummys) so it's not bug..

**Comment by aneq** [comment]
i didnt know that i put /petattack in my lightning bolt command just in case.
regardless, neither thing works and there is no control over the fire elemental whatsoever.

**Comment by Nc94** [comment]
Actually same issue is with Earth Elemental Totem, Army of the Dead and Risen Ghoul (frost/blood spec), the only Guardian pet that follows player targetting on ATS is Guardian of the Ancient Kings in Ret Spec.

P.S. Infernal/Doomguard are also Gurdians and probably have same issue but someone with warlock need to test it.

**Comment by Glare** [comment]
Also Doomguard and probably Infernal. They don't change target untill it dies or they vanish. They should follow the target with Bane of Doom. Though I'd love to see them work like Retri Guardian.

**Comment by Milton3450** [comment]
Also, sometimes, Ebon Imps summoned with Bane of Doom seem to lose their target and start following the warlock instead.
