### ISSUE TITLE
[EN][Core][API] "UNIT_HEAL_PREDICTION", UnitGetIncomingHeals()

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#3114]
Problem: Incoming Heals are not displayed on our server, the event "UNIT_HEAL_PREDICTION" doesn't fire which was introduced in Cataclysm patch 4.0.

**Background:**
- In Vanilla, TBC and WotLK incoming heals were not managed by the game itself. Instead there were addons like [LibHealComm](http://www.wowace.com/addons/libhealcomm-4-0/) which took a look at your equipment, talents, auras etc. and tried to guess how much your next heal would heal. It would then broadcast this estimation to other LibHealComm users in the raid so they know who you wanted to heal and for how much.

- Cataclysm: With Patch 4.0 Blizzard introduced the API event **"UNIT_HEAL_PREDICTION"** and **UnitGetIncomingHeals()**. Now the old LibHealComm addon by the community became obsolete because the game itself would broadcast incoming heals from now on.

Unfortunately there is not much documentation on this on Blizzard's part, the community figured this out on their own. (Sometimes you see the event called UNIT_HEALTH_PREDICTION, but I think that's an error and it's actually UNIT_HEAL_PREDICTION.) You can see that LibHealComm was abandoned at the start of Cata because of the new API, and [here's](http://us.battle.net/wow/en/forum/topic/1568011609) a forum entry from the start of Cata which talks about the reported predictions being slightly too low, with a code example.

**Our Situation:**
Using [this](http://pastebin.com/gJe9RVc7) lua snippet, it seems that the UNIT_HEAL_PREDICTION event doesn't fire. (I made sure that Interface>Raid Profiles>Display Incoming Heals is ticked, although I'm not even sure that this is necessary... the event should always fire, I think)

Looking at the /eventtrace window, there's also no heal prediction event to be found:

![pic](http://i.imgur.com/bi5EFHF.jpg)

**Comment by Wolffenstein** [comment]
Is the heal prediction always 100% accurate or it's sometimes noticably different from the actual heal value?

**Comment by Tj20** [comment]
The heals predictions were slightly different, you didn't know the exact value the heal would do at the end of his cast time (could be a crit, for example). In my personal experience I'd usually heal a bit more (or much more in case of a crit) than the prediction bar predicted.

However, I usually found them a pretty good indicator for checking if I should bother casting a heal on somebody or not. It looked like this:

![pic](http://www.wowace.com/media/images/10/705/playerbar.jpg)

**Comment by Wolffenstein** [comment]
Ok, I got it fixed locally. Will upload in the nearest future.

**Comment by Tj20** [comment]
Great, thank you!

\o/

**Comment by Wolffenstein** [comment]
Fixed in rev 4418.
