### ISSUE TITLE
[EN][PROFESSION][HERBALISM] ZUL'DRAK

### ISSUE THREAD

**Issue by Ulrich1able** [Atlantiss/BugTracker#3118]
The Frozen Herb's in Zul'Drak aren't working, you cannot pick and collect them, When you hover over them you just get a gear logo instead of the logo for normal herbalism plants.

This herb works perfectly find in the other zones it spawns in, but as i could see it doesn't work in Zul'Drak.

WOWHEAD 
http://www.wowhead.com/object=190173/frozen-herb#herbalism

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2197

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14310-219731189021-frozen-herb/

**Comment by pelekon** [comment]
Fixed
