### ISSUE TITLE
Hogger is not attacking back

### ISSUE THREAD

**Issue by Hansrutger** [Atlantiss/BugTracker#3122]
Simple, Hogger that is in Elwynn Forrest is not attacking back once you start an encounter with him. On the picture link below you can see that the combat log only shows that I am attacking Hogger but he's not attacking back. On the picture you can also see Hogger facing his back toward me as if he wanted to die.

http://puu.sh/hujdT/c10ef140da.jpg

**Comment by Hansrutger** [comment]
Sorry forgot to add "[EN] [NPC] Hogger" to the title, not sure how to change it. :/

**Comment by arekczup** [comment]
you can change subject ............
on the right you have a create new issue and edit click edit and change

**Comment by Hansrutger** [comment]
Thank you, did not see that!

**Comment by Bildo** [comment]
bt rules
