### ISSUE TITLE
[EN][Spell][Paladin] Summon Exarch's Elekk

### ISSUE THREAD

**Issue by henrythenth** [Atlantiss/BugTracker#3124]
It's almost the same as with what was posted in https://github.com/Atlantiss/BugTracker/issues/1228, so I won't post the db link here (just use the link on the mentioned thread as reference).

I was able to learn the mount spell, but the apprentice riding skill that was supposed to be free for my paladin still wasn't enabled. Here's a screenshot showing the problem (box labeled 1 - riding skill should've been automatically learned upon reaching level 20; box labeled 2 - mount spell):
![mount bug](https://cloud.githubusercontent.com/assets/12162909/7384344/787f7032-ee63-11e4-9e91-e695a120a14b.jpg)

I know the other thread was already closed, for reasons I don't know (maybe it was fixed then, but just came back, who knows), but there was no clear indication of its status aside from it being closed, so I decided to just create another one. My point here is that this is really inconvenient and problematic, considering those who are just new and do not have sufficient gold to train the riding skill yet, and made paladins/warlocks/druids/worgen to save even just a little early on.

**Comment by Varchord** [comment]
Yea weird that the previous one got closed without any explanation

Have you tried relogging? There is a bug when you learn the highest level flying that you need to relog to actually gain it. Maybe this is the case.

**Comment by henrythenth** [comment]
Yeah. Several times, and /reload too, but up to no avail. o_o

**Comment by henrythenth** [comment]
hmm. the auto-learn for the apprentice riding skill in worgen characters seems to be fine, but this one still persists, even after my paladin got a few levels since then. :/
