### ISSUE TITLE
[EN][NPC][Hellfire Peninsula] Stone Guard Stok'ton

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#3126]
This bug could be one of two possibilities, so I'll write them both, and you can check to see what's actually bugged. I really think it's the second one, though.
# First possibility

It could be that in **Thrallmar**, **Stone Guard Stok'ton** placed in the biggest hut has a wrong ID. One that is placed is this **Stone Guard Stok'ton** (http://www.wowhead.com/npc=54606), but it should be this **Stone Guard Stok'ton** (http://www.wowhead.com/npc=17493).

This makes it so that you can get **Demons in the citadel** (http://www.wowhead.com/quest=29530) and **War on the ramparts** (http://www.wowhead.com/quest=29527) quests two times (once in Thrallmar, and again in the Hellfire Ramparts dungeon), and complete them. Oddly enough, you can't get **Hitting them where it hurts** (http://www.wowhead.com/quest=29593) twice for some reason, which makes me think that maybe the second possibility is how it is actually bugged.
# Second possibility

**Stone Guard Stok'ton** (http://www.wowhead.com/npc=17493) somehow got **Demons in the citadel** and **War on the ramparts** assigned to him. I think this is more likely the case, because if the  **Stone guard stok'ton** (http://www.wowhead.com/npc=54606) is actually placed instead, he should be seethrough (Plus, should give **Hitting them where it hurts**, as well), just like he is in the dungeon where he actually should be, and this one in Thrallmar on our server is solid, so I think that it's actually **Stone Guard Stok'ton** (http://www.wowhead.com/npc=17493), but these two quests somehow got assigned to him.

Anyway, I'm sure you can check this out easily.

**Comment by hawcik** [comment]
Still bugged. Can't give back quests :

War on the Ramparts [http://www.wowhead.com/quest=29528/war-on-the-ramparts](url)
Demons in the Citadel [http://www.wowhead.com/quest=29528/war-on-the-ramparts](url)

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12521-697769763126questhellfire-peninsula-weaken-the-ramparts/
