### ISSUE TITLE
[EN][Instance][Blackrock Caverns/The Vortex Pinnacle] Drop rates seem high

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3131]
The drop rates of some items that drop from trash seem to be way too high for the following items 

- Blackrock Caverns:
 - [Acanthia's Lost Pendant](http://www.wowhead.com/item=55791/acanthias-lost-pendant)
 - [Toxidunk Dagger](http://www.wowhead.com/item=55790/toxidunk-dagger)
 - [Berto's Staff](http://www.wowhead.com/item=55789/bertos-staff)

- The Vortex Pinnacle
 - [Darksky Treads](http://www.wowhead.com/item=55855/darksky-treads)
 - [Rainsong](http://www.wowhead.com/item=55854/rainsong)

The drop rates seem too high in most of the cata content, but these are the ones that I can recall standing out.

**Comment by Tj20** [comment]
True. I've had BC runs where 4 Daggers and 3 Staffs dropped... the drop rates seem really high.

**Comment by Foreverloved** [comment]
I can agree. I play the AH and can confirm that items like these are flooded in the AH. The value of them is so low since everyone and their mom seems to have one :P I always see items like these drop in normals (and even heroics) too

**Comment by Tj20** [comment]
I've just read the changelog, rev 4437:

    fix Atlantiss/BugTracker3131
    fix spell Healing Well, it won't heal players anymore

Thanks for fixing stuff, but why was Healing Well changed so it won't heal players anymore? It did so on retail, which was a nice way to conserve mana as a healer.

[Young Storm Dragon](http://www.wowhead.com/npc=45919/young-storm-dragon#comments)
> As implied by people above, this healing well can be used by the party, and will last quite a while, or until the drake is dead.

[plusheal](http://www.plusheal.com/home/m/1833799/viewthread/858622-vortex-pinnacle):
> During the Storm Drake trash pulls, everyone can stand in the Healing Well on the ground after the tank pulls the Drake out. Massive heals for the group and the healer can just mind the tank until the add dies. Sadly, the healing well disappears after a bit, so you can't use it while fighting additional mobs.

**Comment by Quban** [comment]
Ok ill look into it :)

**Comment by sunshineinabox** [comment]
I haven't been in the vortex pinnacle, but the bug does not seem resolved for BRC. Got three of the staff drops in one rdf.

**Comment by Quban** [comment]
I,ve been in BRC 3 times and not even 1 staff, you had to be lucky it seems, those items got now about 10x less chance to drop.

**Comment by Quban** [comment]
@Tj20 Fix for healing well soon

**Comment by sunshineinabox** [comment]
Hmm I'll collect data on any BRC runs I go through and let you know if I see anything weird.
