### ISSUE TITLE
[EN][Aura] Blessing of Auchindoun

### ISSUE THREAD

**Issue by RelmAtlantiss** [Atlantiss/BugTracker#3133]
Flying in Crystalsong Forest causes you to get buff Blessing of Auchindoun, which increases your damage done and experience gained by 5%. However, the buff remains active even after leaving Crystalsong Forest and it cannot be removed by command "/cancelaura Blessing of Auchindoun" (by right clicking the icon too). Relog / Alt+F4 doesn't help.

http://www.wowhead.com/item=28558/spirit-shard
http://www.wowhead.com/spell=33377/blessing-of-auchindoun
Current revision: 4412

**Comment by xolon** [comment]
It is so absurd how many people abuse this buff, should be fixed asap

**Comment by meowmewo** [comment]
BUUUMP
