### ISSUE TITLE
[EN][Quests][Dun Morogh] It's Raid Night Every Night

### ISSUE THREAD

**Issue by krashan34** [Atlantiss/BugTracker#3134]
http://www.wowhead.com/quest=25932/its-raid-night-every-night
The Event does not start when the quest is accepted. It would appear that it has been scripted before,
http://atlantiss.eu/news/view/49 Search on the webpage with Crt + F and type in the quest name...

**Comment by coba999** [comment]
didnt work

**Comment by rasmodeus** [comment]
Just attempted.  Will not start, even after multiple quest drop and pick ups.

**Comment by karhima** [comment]
Still broken, event does not start after multiple relogs, quest drops and pick ups.

**Comment by Khangu** [comment]
Quest was working fine about month or two ago.

**Comment by Larousene** [comment]
Bump! Still not working

**Comment by emrecgty** [comment]
I can swear it was working before but now it isn't working

**Comment by Aival94** [comment]
Bump.
How quest should work: https://www.youtube.com/watch?v=0s-et4dtvaM&feature=youtu.be

**Comment by Alajszopa** [comment]
Welcome! 
Quest is still doesnt working ... Pls fix it

**Comment by Sorvirus** [comment]
Quest isn't working still, could somebody please help?

**Comment by Snake90** [comment]
The quest only works after a reboot or a crash but it means that that as soon as a person has done this quest, it remains bugged until the next restart or crash :/ 

Problem : The NPC who come to fight the Frostmane raiders are supposed to leave after the quest is validated or there they stay, so when the next person comes to take the quest nothing happens :/

**Comment by valeriu28** [comment]
bump
Quest is still broken, tried logging out and etc. :)

**Comment by Snake90** [comment]
Still bugged because the NPC stay ...

**Comment by Khangu** [comment]
Waiting for res/down is still the only way to complete it.

**Comment by Alzand** [comment]
The quest is not working actually, tried 10 minutes ago

**Comment by Snake90** [comment]
Still bugged but now it's bugged after a restart/down too because the Frostmane Raiders run away and and dissapear, they can't be purchased or killed so ... the quest is definitely bugged. Pffffff

**Comment by podatekvat** [comment]
4 months and it's still not scripted

**Comment by ylluminarious** [comment]
Bump
I bet someone could work around this bug by killing the mountaineer NPCs. According to @Snake90, those mountaineers prevent the Frostmane Raiders from coming. Unfortunately, I have no high-level Horde characters to test this theory out...

**Comment by ylluminarious** [comment]
Wow, I can't believe I just got so lucky... just as I finished writing that last comment, the server went down and the mountaineer NPCs were gone when I logged back in. So I was finally able to complete the quest!

So, I can confirm: a server restart will allow the quest to be completed and those mountaineer NPCs are indeed what prevents the quest from being completed. Although, strangely enough, the NPCs are gone now that I've completed the quest... I am not sure what causes them to stay which breaks the quest for other people later.

**Comment by drc1119** [comment]
This quest is still bugged. The Amberstill Mountaineer NPCs are still here and I cannot get the quest to start.

**Comment by grizzlydaddy** [comment]
Sadly still not working.

**Comment by Azotherian** [comment]
Can confirm that the quest is not working again. I start the quest, and no NPCs or enemies spawn to fight

**Comment by Avalain** [comment]
I killed NPC with my Horde character, quest did indeed started but trolls started running to ram pens, ignoring guards and despawned in the middle of it. Quest remained unfinished.

**Comment by NonIdentifie** [comment]
Still doesn't work, enemies not spawn.

**Comment by grindbox** [comment]
still not working as intented

**Comment by Bildo** [comment]
fixed
