### ISSUE TITLE
[EN] [Warrior] [Spell] - Slam

### ISSUE THREAD

**Issue by obsyd** [Atlantiss/BugTracker#3136]
http://www.wowhead.com/spell=1464/slam#changelog
http://wow.gamepedia.com/Slam

http://www.filedropper.com/slam - Simulation (without talents, items, buffs, dubuffs etc I have only used http://www.wowhead.com/item=30902/cataclysms-edge)

Test on the ATS server.
[IMG]http://i58.tinypic.com/1zvwwic.jpg[/IMG]

Simulation shows average 812 hit, and average 1377 cryt.

On ATS it's ~1446 average hit and 3k cryt (got only one because i have 1,9% cryt without items).

4.2.0 (Tue Jun 28 2011) Build 14107 - Slams the opponent, causing 145% weapon dmg plus 430. (source - wowhead)

Again - i have used http://www.wowhead.com/item=30902/cataclysms-edge for testing.

Weapon DMG - 386-580

580 * 140 / 100 + 430 = 1,271
386 * 140 / 100 + 430 = 989,7

Heroic Dummy Armor Reduction 31,5%

1,271 * 68,5 / 100 = 870
989,7 * 68,5 / 100 = 677,9

I do not know where exactly the bug is but i think it should be reported - dmg is a little bit too high :)
EDIT: i have forgotten to mention (and to include this into my calculations) that i was in berserker stance while doing this tests - but this probably doesnt change much, slam is still buged (maybe wrong formula for caclucating dmg or wrong coeffs, idk )

**Comment by strnoobspk** [comment]
It's not...your tests applied arn't correctly tested.

**Comment by Kejmil** [comment]
prove it?

**Comment by obsyd** [comment]
On our server tooltip shows 196% + 992. Wowhead says : 4.2.0 (Tue Jun 28 2011) Build 14107 - Slams the opponent, causing 145% weapon dmg plus 430. - So the bug is probably here.

**Comment by Var3** [comment]
Our tooltip shows 196% + 992 only in arms with Improved Slam. Without it (i tested on prot spec) it shows 167% + 791.

**Comment by HaydenGT** [comment]
tool tip scales with all talents which increase dmg of slam - war academy(15%) and improved slam(20%)

**Comment by strnoobspk** [comment]
^^^this...it's working perfectly
