### ISSUE TITLE
[EN/PL] [QUEST] [EMBERSTONE MINE] [LIBERATION DAY]

### ISSUE THREAD

**Issue by CholewaKnight** [Atlantiss/BugTracker#3139]
After receiving key and using it on "ball and chain" priosoners aren't free. Normal cast while opening and than nothing happend. Checked on different balls, keys are lost during the process. This interrupts chain quest which is leading to q "push them out".

Po zdobyciu klucza i użycia go na "kuli z łańcuchem" więźniowie nie są uwalniani. Normlany cast przy otweraniu a nastepnie nic się nie dzieje. Sprawdzałem na kilku różnych kulach, klucze traci się przy otwierani. Uniemożliwia to zrobienie serii dalszych zadań dla worgenów.

**Comment by Maxad2234** [comment]
Nie wszystkie kule zaliczają się do tego questa. Otwieraj tylko te, przy których są gilneani - powinno zadziałać.
