### ISSUE TITLE
[EN][QUEST]Soothing the elements (please read before commenting)

### ISSUE THREAD

**Issue by Maxad2234** [Atlantiss/BugTracker#3141]
i know this quest have been reported already more than 10 times, but in my case, this bug is a little different.
you see, yes, sometimes elementals just don't spawn, but i've already killed fire elemental rager... 3 TIMES, and quest still isn't completed.
i don't know what's wrong. i've killed all waves of these fire elementals and still i can't complete it.
thanks.

**Comment by Varchord** [comment]
Then add a comment https://github.com/Atlantiss/BugTracker/issues/1521
