### ISSUE TITLE
[PL][NPC][EASTERN PLAGUELANDS] Duskwing

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#3145]
http://www.wowhead.com/npc=11897/duskwing 
Ten potwór powinien być do oswojenia, a się nie da, wyskakuje napis "invalid target", a na http://www.wow-petopia.com/look/batskinwhite01.html jest oznaczony jako jeden z oswajalnych.

**Comment by Varchord** [comment]
Patch 2.0.3
> As he's a white bat the size of a wyvern, he should be easy to spot. Unfortunately, hunters can't tame him.
Patch 5.0.5
> Was recently made tamable along with many other previously untameable beasts shortly after Mists of Pandaria was released.

Nie powinien być do złapania. Do zamknięcia
