### ISSUE TITLE
[PL][Spell][Mage] Ring of Frost

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#3146]
Ring of Frost nie powinien zamrażać jeśli Mage jest pod wpływem CC, które uniemożliwia 'channeling'.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3014
uczcie sie szukać

**Comment by Genomnomnomnom** [comment]
Szukałem w klasie Mage i wyszukiwarce na górze. Mam przeglądać cały bugtracker zanim coś wrzucę?

**Comment by Varchord** [comment]
Ring of Frost w wyszukiwarce, drugi od góry(wcześniej był pierwszy) temat. Strasznie dużo mi to zajęło, aż 20s. Nie dyskutuj bo nie masz racji tylko zamknij temat

**Comment by Genomnomnomnom** [comment]
No to mi nic nie wyświetla po wpisaniu Ring of Frost w wyszukiwarkę. Nie wiem gdzie to się zamyka, pomóż.
