### ISSUE TITLE
[EN/PL][NPC][Ghostlands] Vampiric Mistbat

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#3150]
EN: Vampiric Mistbats should be hostile, at the moment they're neutral.
http://www.wowhead.com/npc=16354/vampiric-mistbat

PL: Vampiric Mistbats powinny być wrogo nastawione, aktualni neutralne.
http://www.wowhead.com/npc=16354/vampiric-mistbat

**Comment by Bildo** [comment]
fixed
