### ISSUE TITLE
[EN][Mage][Talent] Pyromaniac

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#3151]
# [Pyromaniac](http://cata.openwow.com/spell=34295)
* "Increases spell haste by 10% if 3 or more targets are taking Fire damage over time from your spells."

2 living bombs + one other DoT on 2 targets will trigger pyromaniac. It should be at least one dot per target on 3 targets

**Comment by blinkmaster** [comment]
tested it, it works a little bit different.
when you have 2 living bombs pyromaniac will not proc
BUT
when you have 2 living bombs + ignite on the target it will proc, same goes with pyro dot

**Comment by Varchord** [comment]
So it's 2 living bombs + one other DoT

**Comment by blinkmaster** [comment]
bump its a huge buff bug

**Comment by Jenovas** [comment]
Fixed in rev 4714

**Comment by PierwszyKrytykRP** [comment]
Can someone test it when it goes live? I forgot password to my mage(again)

**Comment by Illusie** [comment]
still bugged
@Jenovas @blinkmaster @Wolffenstein
