### ISSUE TITLE
Black Morass (Instance)

### ISSUE THREAD

**Issue by Duchel** [Atlantiss/BugTracker#3152]
Portal event is bugged First 7 portals are poping out one after the other and works fine, but for every next portal you have to wait around 5 min witch is quite insane if you want drop some transmog gear or just do the instance to level up your character

**Comment by Varchord** [comment]
god damn
https://github.com/Atlantiss/BugTracker/issues/2155
https://github.com/Atlantiss/BugTracker/blob/master/README.md
https://github.com/Atlantiss/BugTracker/blob/master/README.md
