### ISSUE TITLE
[EN][Quests][Darkshore] A Troubling Prescription

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3153]
A Troubling Prescription (http://www.wowhead.com/quest=13831/a-troubling-prescription) is not available. It should be an optional quest accepted by clicking the disgusting workbench (http://www.wowhead.com/object=194714/disgusting-workbench).

**Comment by Bildo** [comment]
This quest is avaiable after http://www.wowhead.com/quest=13554/a-cure-in-the-dark

**Comment by ahtebe** [comment]
It shouldn't be available after A cure in the dark, it should be available according to this quest chain: http://wow.gamepedia.com/Quest:A_Cure_In_The_Dark#Quest_progression
