### ISSUE TITLE
[EN] [Profession] Fishing 

### ISSUE THREAD

**Issue by Arsic333** [Atlantiss/BugTracker#3155]
I can't fish in any cata zone beside Tol Barad. When I try to fish in Uldum it is saying that my fish got away but I pressed bobber in time. Fishing skill - 245

**Comment by Bildo** [comment]
Your skill is too low you need ~400

**Comment by Arsic333** [comment]
Thanks!

**Comment by Thefakemccoy** [comment]
actually that is wring
As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and all casts will catch something and award a chance for a skill-up. However, if your skill level is too low for a zone, you will catch mostly vendor trash items.
