### ISSUE TITLE
[EN][Instance-TBC]The Black Morass Mobs

### ISSUE THREAD

**Issue by Foreverloved** [Atlantiss/BugTracker#3157]
1) http://www.wowhead.com/npc=18982/sable-jaguar -- These mobs are unskinnable. They should be able to be skinned and at the moment aren't.
2) http://www.wowhead.com/npc=17952/darkwater-crocolisk -- These mobs cannot be found in the instance at all. I remember pulling half of the instance at one point and only saw jaguars and spiders.

**Comment by Bildo** [comment]
fixed
