### ISSUE TITLE
[EN][Area][NPC] Ridge Stalker Patriarchs in Dragon's Mouth alliance camp killing NPCs

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#316]
Ridge Stalker Patriarchs (http://www.wowhead.com/npc=2734) in Badlands are roaming inside the alliance camp at Dragon's Mouth

![wowscrnshot_111914_105100](https://cloud.githubusercontent.com/assets/9798968/5103656/6f2df650-6fda-11e4-8404-a6f93801c074.jpg)

Other than being spawned inside the camp, where they shouldn't be, they are also attacking and killing some of the alliance NPCs in this camp.

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/3305

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6569-npc-ridge-stalker-patriarchs-in-dragons-mouth-alliance-camp-killing-npcs/
