### ISSUE TITLE
[EN][Druid] Skullbash/Feral Charge vs. Clearcasting

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3160]
Skull Bash and Feral charge(bear form / cat form) should not consume Clearcasting proc from Omen of Clarity since it isn't a damage,healing spell and offensive feral ability.

Proof:
http://us.battle.net/wow/en/forum/topic/2112512991

https://www.youtube.com/watch?v=MBVndy3dSFo
at 0:35 you can see he has clearcasting up, and he uses skull-bash, clearcasting is still up.

**Comment by Isuel** [comment]
confirmed

**Comment by Jenovas** [comment]
Fixed in rev 4549
