### ISSUE TITLE
[EN][NPC][Ashenvale] Sentinel Avana

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3162]
Sentinel Avana (http://www.wowhead.com/npc=33445/sentinel-avana) should provide a ride in one of her nightsabers to Astranar according to these requirements: http://wow.gamepedia.com/Sentinel_Avana#Notes . In this server, the NPC does not offer the ride, even after meeting the requirements.

**Comment by BAndysc** [comment]
Fixed
