### ISSUE TITLE
[ENG][Quest]Drive-By-Piracy

### ISSUE THREAD

**Issue by lolsund** [Atlantiss/BugTracker#3164]
Hello.
So as said there's an iddue with this quest : 
when you speak to the NPC "Bloodsail Oarsman" , he let you jump into a boat with a cannon "Ol'blasty"
to shoot down [75xVenture Co. Oil Worker] . The problem is that when you jump on the boat you're under water you can aim but your aiming won't do a thing and you can't slain any Venture Co. Oil Worker

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/360
