### ISSUE TITLE
[Pl][Quest][Desolace] Jugkar's Undoing

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#3165]
Quest zaczyna się od itemu "Infernal Power Core", który powinien mieć 55% szans na drop z mobka "Lesser Infernal", jednak obecnie mobek nie posiada żadnego lootu.
link do questa: http://www.wowhead.com/quest=14344/jugkars-undoing
link do quest itemu: http://www.wowhead.com/item=49200/infernal-power-core#starts
link do mobka: http://www.wowhead.com/npc=4676/lesser-infernal

**Comment by Bildo** [comment]
fixed
