### ISSUE TITLE
[PL][Dungeon][Heroic][Halls of Stone] Tribunal of the Ages

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#3169]
Brak lootu z Tribunal of the Ages w wersji heroic. Pomimo ustawionego heroic mode ze skrzynki zawsze dropią itemy z normal mode.

http://www.wowhead.com/npc=28234/tribunal-of-the-ages#drops:mode=heroic

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
https://github.com/Atlantiss/BugTracker/issues/2882
