### ISSUE TITLE
[PL][Class][Druid]Shred

### ISSUE THREAD

**Issue by Mordorianin** [Atlantiss/BugTracker#3171]
Podczas przypięcia po manglu na Magmawie nie można shredować. To samo tyczy się skilli, które do użycia wymagają znajdowania się za targetem, np. backstab.

http://www.wowhead.com/spell=5221/shred

**Comment by Asavel** [comment]
To nie jest bug spella

**Comment by Varchord** [comment]
> To nie jest bug spella 
+1

I jestem pewien, że jest już raport na ten temat.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/3143
