### ISSUE TITLE
Mining ore and herbalism problems on trees in air cant geather them without flying mount

### ISSUE THREAD

**Issue by dusan123** [Atlantiss/BugTracker#3172]
hello this is my first post and sorry for bad english im new on server playing here for a week now and i notice there is very low ores  example in The Cape of Stranglethorn herbs very very low mining ores  i found 10 of them for whol map i try in morning  i try at night in any case sombody is farming but resoult is the same can you fix it please and put more ores and herbs where they need to be? please answer!

**Comment by cuamanuel** [comment]
I second this, I've encountered something like this in Deepholm:
![image](https://cloud.githubusercontent.com/assets/4362689/7516100/520b38d0-f4ff-11e4-829f-9a30e258f1d1.png)
