### ISSUE TITLE
[EN][Quest] Take him to the earthcaller

### ISSUE THREAD

**Issue by Polarchris** [Atlantiss/BugTracker#3178]
This quest used to work but now doesn't; Meaning, i bring Flint Oremantle near Earthcaller Yevaa but nothing happens,can't complete the quest; I saw some other guy from the other faction trying to complete without succes. This quest is a chain quest so we can't continue if it isn't fixed.

http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller

**Comment by sohussain** [comment]
+1

**Comment by sohussain** [comment]
seams its fixed now, you may close this issue.

**Comment by Kozilak** [comment]
The quest is broken again, dunno why, but more then one person, me included, confirmed that they cannot complete it. I've taken it and retaken it at least 20 times. Did it mounted,  unmounted, while RP walking- absolutamente nada.
