### ISSUE TITLE
[EN/PL][Warlock] Summon Felsteed

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#3179]
EN: Learning to summon Felsteed is free and doesn't grand you Apprentice Riding (http://www.wowhead.com/spell=33388/apprentice-riding).
Checked in Silvermoon City.

How it should be: Summon Felsteed (http://wow.gamepedia.com/Summon_Felsteed) should cost some silver coins (probably 90 silver, not sure in which reputation range if any), and should grand free Apprentice Riding upon buying skill (Summon Felsteed).

PL: Nauczenie się umiejętności przywołania Felsteed jest darmowe i nie daje podstawowej umiejętności jeździeckiej (http://www.wowhead.com/spell=33388/apprentice-riding).
Sprawdzone w Silvermoon City.

Jak powinno być: Przywołanie Felsteed (http://wow.gamepedia.com/Summon_Felsteed) powinno kosztować trochę srebra (najprawdopodobniej 90 srebrników, nie jestem jednak pewien w jakim zakresie reputacji, o ile ma ona wpływ na cenę), dodatkowo powinniśmy otrzymać darmową umiejętność podstawowego jeździectwa przy zakupie umiejętności (Przywołanie Felsteed).

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
