### ISSUE TITLE
[Quest][Blade's Edge Mountains][Ogri'la] Banish the Demons

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#3180]
Wowhead link: http://www.wowhead.com/quest=11026

After getting honored with Ogri'la this quest should be available for players. Nothing happens when we get honored. After getting revered the quest giver (Kronk http://www.wowhead.com/npc=23253) gets a yellow exclamation mark above his head, but the quest is still unavailable.

**Comment by Beatit** [comment]
bump!
Kronk haven't any quest... but he show "i have quest to you" (yellow exclamation mark over his head)  on revered reputation.

**Comment by Aival94** [comment]
Still quest is not being given at all.
Furthermore should unlock a Daily Quest [Banish More Demons](http://www.wowhead.com/quest=11051/banish-more-demons).

**Comment by Aival94** [comment]
Why this report got closed?(have not seen it fixed or i missed it?)

**Comment by Bildo** [comment]
i'm fixing and closing issues at the same time, will be posted in changelog later

**Comment by Aival94** [comment]
ok. Sorry to ask you but did not saw in changelog and was wondering :)

**Comment by Bildo** [comment]
np
