### ISSUE TITLE
[PL][DK][Runeforging] Rune of Cinderglacier

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#3182]
Rune of Cinderglacier - http://cata.openwow.com/spell=53341/rune-of-cinderglacier

Obecnie buff, który daje nam Rune of Cinderglacier zostaje zużyty przy każdym frost/shadow damage (np. przy ticku Frost Fever, Blood Plague i ticku z Rune of Razorice).
Oczywiście powinien działać tylko ze skillami typu direct damage takimi jak Frost Strike, Death Coil itd.

**Comment by Jenovas** [comment]
Fixed in 4461
