### ISSUE TITLE
[EN][NPC][Blade's Edge Mountains] Rexxar

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#3183]
NPC Rexxar is missing.He is suposed to be in Thunderlord Stronghold, i think even giving 7-8 quests .He is not there at all.

link - http://www.wowhead.com/npc=21984/rexxar

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Wolffenstein** [comment]
If I remember correctly, you have to do some quests for him to show up.

**Comment by aje** [comment]
NPC present. He first appear when you have this quest http://www.wowhead.com/quest=10718/the-spirits-have-voices
