### ISSUE TITLE
[EN][Druid][Rogue] Energy Regeneration from Debuffs

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3184]
This https://github.com/Atlantiss/BugTracker/issues/3042 , and this https://github.com/Atlantiss/BugTracker/issues/2085 , and https://github.com/Atlantiss/BugTracker/issues/1048 , aren't fully fixed yet.

Some attack speed debuffs from mobs, like http://www.wowhead.com/spell=11443/cripple , still slow energy regeneration, which should not happen under any circumstance.

**Comment by coocoo89** [comment]
it works as it should.

**Comment by ahtebe** [comment]
No... it shouldn't slow energy regen.

**Comment by coocoo89** [comment]
i had a discussion about this with Armano it's blizzlike.

**Comment by Jenovas** [comment]
It should modify regen. It is the same effect type as Unholy Frenzy or Unholy Presence which both increases regen, so I dont see why it shouldnt reduce regen also.
Closing.

**Comment by ahtebe** [comment]
Ok, I did a bit of research myself and your both right: http://us.battle.net/wow/en/forum/topic/2416193981 . (seriously this was the only reliable cataclysm dated source I was able to find... one would think something like this would be well documented in wikis and such)

**Comment by ahtebe** [comment]
Ok, I did a bit of research myself and your both right: http://us.battle.net/wow/en/forum/topic/2416193981 . (seriously this was the only reliable cataclysm dated source I was able to find... one would think something like this would be well documented in wikis and such)
