### ISSUE TITLE
[Zone] Crash at Crowley Orchard/Grandma Wahl

### ISSUE THREAD

**Issue by Shockaboom** [Atlantiss/BugTracker#3185]
Issue: Fatal Error 132 every time upon reclogging in Crowley Orchard/Grandma Wahl area, might be a phase problem, might just be a zone problem (1 character is unphased, 1 character is phased for the Crowley Horse Gathering quest), instant CTD. Cannot complete Worgen Starting Zone.

Attempts: Tried on 2 separate machines, including a computer where a worgen made it out of the starting area and is in Azeroth. This worked 1 week ago, does not work today for new toons.

Tried on 2 separate characters as well.

Cleared cache, cleared entire World of Warcraft folder, did a fresh install properly with miniclient, still will not allow past Orchard/Grandma area- results in CTD.

Seems to happen once approaching Lorna Crowley for the horse quest.

Attempted every fix, including checking memory errors on my end from this post: http://atlantiss.eu/community/viewtopic.php?f=10&t=1785

No memory errors were reported.

**Comment by Tj20** [comment]
related:
- [EN] [NPC] [Quest] Lorna Crowley crash #2493
- [EN][Quest][Gilneas] Quest:Grandma's Cat #2678

**Comment by Shockaboom** [comment]
Update: Confirmed Temporary Fix:

- Use 5 Vote Points and use the Atlantiss.eu Website Unstuck Command.
- Player will be teleported to Gilneas City (Start Area on Character Creation).
- If you saved your Inn at Dusthaven (you should have upon arrival earlier) then use your Hearthstone to be ported here.
- Try some other quests like the gathering/slaying quest on the beach area in the mean time.
- Now go back and try the horse gathering quest/grandma's items quest, all will work and you will be able to proceed 100%.

Confirmed, tested, works, May 7, 2015, 3 AM.
