### ISSUE TITLE
[EN][Druid] Ferocious Bite

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3190]
Ferocious Bite does less damage than it should.

Proof:
http://www.wowhead.com/news=189203/patch-4-2-ptr-build-14107-achievements-spell-changes-items-and-more

Formula:
MIN DMG: 230+576*5*1+0.545 * AP * 1 
MAX DMG: 498+576*5*1+0.545 * AP * 1

my stats:
http://tinypic.com/r/e9dzxs/8 - ap 585 

damage i do:
min damage: 3339
max damage: 3603

how it should be:
min damage: 230+576 * 5 * 1+0.545 * 585 * 1  = 3429
max damage: 498+576 * 5 * 1+0.545 * 585 * 1 = 3697

on target without armor/resilience/talents/glyphs and me without gear/talents/glyphs etc.
every ferocious bite is under 30 Energy at 5 combo points

**Comment by Isuel** [comment]
could you also please test it for max energy? i think that at max (60) energy, bite is doing more than double the dmg from min energy, so maybe the energy formula is getting calculated wrong

**Comment by razgal** [comment]
for 50 energy

how it should be in our current state:
mindamage: 3339*2 = 6678
maxdamage: 3603*2 =  7206

how it should be with blizzard formula:
mindamage: 3429*2 = 6858
maxdamage: 3697*2 = 7394

how much I do:
mindamage: 6878
maxdamage: 7332
http://tinypic.com/r/2e3tiyd/8

yea the mindamage at 50 energy seems slightly more, even tho it's closer to blizzard formula

however, the damage is broken even at 50 energy becouse it should do 6678 - 7206 in our current state, and with the good one should be 6858 - 7394

**Comment by Isuel** [comment]
and could you please test it with 60 (it's 60, not 50) energy AND full gear? maybe the difference in damage will be bigger enough to consider it not a "Low priority"

**Comment by razgal** [comment]
50 or 60 it's exactly the same thing.
damage is doubled at 50 or more energy.

**Comment by PlayFullTV** [comment]
feral's largest hitting spell.. low priority.. pfff ok

**Comment by sunshineinabox** [comment]
Ferocious bite is a 3rd option finisher. Now if savage or rip had an issue feral would be unplayable.

**Comment by PlayFullTV** [comment]
Ferocious bite is used as your main source of burst during your berserk (after you apply your rip) soooo yeah, basically feral burst is fucked due to this dmg scaling

**Comment by Isuel** [comment]
it's not a big issue, feral's dps is fine as it is, there are way bigger problems with mechanics... which i reported.
