### ISSUE TITLE
[EN][mage] ring of frost vs cc. x2 ticket

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3191]
it was marked as resolved here,few days ago https://github.com/Atlantiss/BugTracker/issues/3014

i cloned the mage and i entered in ring and I still got Freezed.

**Comment by Tj20** [comment]
It was fixed in rev 4425 - according to the [changelog](http://atlantiss.eu/changelog) the fix is not live yet, still "waiting for update".

**Comment by Varchord** [comment]
It is live on ptr

**Comment by Jenovas** [comment]
Waiting for update.
