### ISSUE TITLE
[EN][Class][Mage] Arcane Missiles doesn't remove Arcane Blast debuff

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#3192]
How it should work. When casting Arcane Blast u get a debuff. This debuff will get removed if u cast any arcane spell except Arcane Blast and Arcane Explosion. If u cast Arcane Missiles this debuff should get removed. Bug: The debuff isn't removed when casting Arcane Missiles.

**Comment by Varchord** [comment]
Yes it is. We have arcane mage. If it was bugged he would be oom after 40s in to a fight

**Comment by Milton3450** [comment]
http://cata.openwow.com/spell=30451

dunno if it's just on lower levels it doesn't work... Haven't tested it again after a relog. Levelled to level 40 without relogging (RAF).

**Comment by Milton3450** [comment]
I tested it again today. Maybe I am mistaken, and it works like intended. I am unsure what the intented mechanic is. It removes AB debuff when the spell hits or when it is cast?

**Comment by Milton3450** [comment]
Because right now the cast bar is almost finished when I cannel arcane missiles before the debuff disappears.
