### ISSUE TITLE
[EN][Racial]Shadowmeld

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3193]
If you use shadowmeld at cca. 0.3 within other spell hits you, the spell should be evaded
right now shadowmeld negates only traveling-time spells,like: frostbolt,deathcoil,firebolt, etc.

example: rogue blinds you and you use in same time Shadowmeld, the Shadowmeld should evade that spell.
or a mage with polymorph
or a druid with clone
or a hunter with scatter/monkey/etc 

proof:
https://www.youtube.com/watch?v=sQj3_jnjCdg
https://www.youtube.com/watch?v=9di0x0WuuuY

**Comment by MasterK15** [comment]
few days ago someone meld my Deep Freeze so iI think its work fine

**Comment by ShockRW** [comment]
Keep in mind that there is no custom delay for spells.

**Comment by Isuel** [comment]
also, when the casted spell (frostbolt, for example) travels towards you, if you use shadowmeld, but then exit it before it hits you, you'll get the full damage.

**Comment by Isuel** [comment]
also, your shadowmeld should make the target cancel his cast and lose his target, and it's not doing that. Really important, looking forward to it being fixed

**Comment by armano2** [comment]
cmon, can you guys use search?
#3193
