### ISSUE TITLE
[EN][QUEST][DARKSHORE]Soothing the elements

### ISSUE THREAD

**Issue by bemoi** [Atlantiss/BugTracker#3195]
Same issue as in #1521 , not fixed, below is my comment on the bug in the issue post but it was closed anyway

Hi,
this issue is not fixed yet, people who were commenting were talking about not being able to defeat the elementals or not being able to locate the place to place the totem, while our issue is different, that no elementals appear when totem is placed in the right place.

Appreciate your help :) :)

**Comment by Wolffenstein** [comment]
The fix is not yet uploaded. Check the revision.
