### ISSUE TITLE
[PL][Transmog] Frostguard

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#3196]
Nie można przyjąć wyglądu broni: "Frostguard" (http://wow.wyesoft.com/item/?id=12797). Oryginalnie przedmiot można transmogować i inne enchanty nie wykluczają jego "wizualnego lodowego efektu".
"When transmogrified it does not lose its original enchant but instead keeps it. No other enchants will overtake it." (http://www.wowhead.com/item=12797/frostguard#comments).

Niezależnie czy nałożony jest runeforge czy też nie, po zaznaczeniu broni "Frostguard" do transmoga i kliknięciu czerwonego przycisku "apply" słychać "iskrę" nie jest pobierana opłata i nie nakłada się nowy wygląd, przycisk się nie wyciemnia. Może ma to związek z próbą nałożenia transmoga tej broni na miecz, który ma runeforga?

**Comment by ShockRW** [comment]
raczej item który nie ma statów

**Comment by nerv234** [comment]
Item ma chance on hit, powinien sie dać transpomogwać ale nie daje bo tak to u nas działa.

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
