### ISSUE TITLE
[PL][Warrior] Strikes of Opportunity

### ISSUE THREAD

**Issue by HaydenGT** [Atlantiss/BugTracker#3197]
Masterka dla armsa nie działa poprawnie. Meele strike, który procuje masterke nie daje nam rage.

**Comment by Jenovas** [comment]
http://www.mmo-champion.com/threads/774074-Strikes-of-Opportunity
http://eu.battle.net/wow/en/forum/topic/1679648868

Skąd masz wiadomość że powinna? Tutaj jest napisane że nie powinna.
Czekam do jutra wieczorem na źródło z którego wynika że powinno.

**Comment by HaydenGT** [comment]
Nie mówię o procku masterki, tylko zwykłym białym melee hicie, który tą masterkę procuje.

**Comment by Jenovas** [comment]
Działa poprawnie. Zrobiłem test mając 100% szansy na odpalanie masterki i rage był normalnie generowany przez ataki.
