### ISSUE TITLE
[PL][Feral Spirit][Shaman] 

### ISSUE THREAD

**Issue by czarny88** [Atlantiss/BugTracker#3198]
Witam.
Rozmawiałem z kilkoma graczami na temat  problemu wilków szamana.  Generalnie chodzi o abilitki petów których nie ma w "spell booku" Wszyscy odpowiadaj to samo ze wilki się nie skalują z szamanem maja za mało hp, być może ich atak nie jest proporcjonalny do levelu wilczków  i nie można nimi sterować stunami czy tez szybkim bieganiem. Trzeba klikac. Pisze tez w imieniu tych graczy bo w sumie grając pvp jest to kluczowa umiejętność, która pomaga wyjść z spowolnień czy tzw. efektu rootsow. Nie chce być nieznośnym ale fajnie by było żeby to trochę działało. Poniżej dokańczam linki .
<a href="http://pl.tinypic.com?ref=287g268" target="_blank"><img src="http://i60.tinypic.com/287g268.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://pl.tinypic.com?ref=huewy1" target="_blank"><img src="http://i61.tinypic.com/huewy1.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Pozdrawiam 
Łukasz

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by nerv234** [comment]
To jest bug tracker, tutaj masz opisać dokładnie co jest zbugowane, linki do skilli:) wypunktuj bug za bugiem. Całe zgłoszenie wygląda chaotycznie  w stylu "słyszałem że coś nie działa a coś działa, macie zdjęcia i naprawcie".

**Comment by mitim1** [comment]
Mam shamana (w hordzie) i żaden z tym problemow mnie nie dotknął.
