### ISSUE TITLE
[EN][Mage] molten armor vs. ignite

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3199]
when Molten armor crits the enemy it applies ignite , which is wrong

proof:
http://www.wowwiki.com/Molten_Armor
"Patch 3.2.0 (04-Aug-2009): Critical strikes from the effect on this armor will no longer trigger Ignite. "

**Comment by Jenovas** [comment]
Fixed in rev 4428

**Comment by fruvel** [comment]
anyone have fix on molten armor  ? 
This is very old bug on patch 3.3.5a - Combustion consumed when molten armor cirts and combustion stacks when molten armor don't cirts
