### ISSUE TITLE
[EN][Mage] flame orb vs. haste

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3201]
Flame orb shouldn't scale with haste. 

it has 15 second duration, should do 1 hit/second, this means 15 hits.

proof:
https://www.youtube.com/watch?v=x2hedrKM2ck
at 1:29 , casted the orb in the boss, in 15 seconds it did 15 hits.

http://forums.elitistjerks.com/topic/128507-433-fire-mage-compendium/
"Flame Orb|||||Flame Orb is not considered a DOT. It does not gain any additional ticks from Haste"

**Comment by Jenovas** [comment]
Doesnt scale with haste
