### ISSUE TITLE
[EN][Mage] living bomb explosion vs. ignite

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3203]
Living Bombs explosion applies Ignite if it crits, which is wrong.

proof:
http://www.mmo-champion.com/threads/1036699-Flame-Orb-Ignite?p=14516327&viewfull=1#post14516327
"Flame Orb's explosion can not cause ignite, nor can living bomb's explosion cause it. I recently (and just now again) tested this, even SimulationCraft had this wrong until recently."

http://www.mmo-champion.com/threads/1038982-Ignite-munching-4-3?p=14575348&viewfull=1#post14575348
"Chiaroscuro, I spent some time on some target dummies the other day putting up LB x 3 and using Flame orb on CD for 5 minutes. Not once did ignite show up in my damage logs. This includes many living bomb explosions, it is a little harder to tell if I got a flame orb explosion, but I would say we can probably assume it behaves the same."

**Comment by razgal** [comment]
same should be for Flame orb Explosion

**Comment by Kejmil** [comment]
the explosion of living bomb should be considered as periodic dmg, that's it

**Comment by Jenovas** [comment]
Fixed in rev 4428
