### ISSUE TITLE
[EN][Quest][Terokkar Forrest] A Personal Favor

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Atlantiss/BugTracker#3204]
So I came to collect the 5 stolen goods. I killed every one out here and only got 4. Seems a little low on the drop rate was wondering if this could be looked at.

http://www.wowhead.com/quest=10112/a-personal-favor

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12044-3204-lathrais-stolen-goods-drop-chance/
