### ISSUE TITLE
[PL] [Quest] [Zul'Drak] [I Sense a Disturbance]

### ISSUE THREAD

**Issue by Maniuszka** [Atlantiss/BugTracker#3206]
Po akceptacji questu i porozmawianiu z npc powinno wlaczyc sie automatyczne biegniecie na panterze, lecz jest tak, ze trzeba samemu biec a combat przerywa akcje, dlatego quest jest niewykonalny.

Powinno to wygladac tak:
https://www.youtube.com/watch?v=sDYVoDT5MDo

**Comment by Bildo** [comment]
czekaj na update, oraz przeczytaj zasay bt
