### ISSUE TITLE
[PL][Item] Loot-A-Rang

### ISSUE THREAD

**Issue by Razzim** [Atlantiss/BugTracker#321]
http://www.wowhead.com/spell=84342

Użyć się da, jest fioletowy efekt na celu użycia, jest mały freez... i tyle. Brak lootu.

**Comment by stewazy** [comment]
this item is not working, i made it and checked ....

**Comment by Bildo** [comment]
yea that's why its on bugtracker lol

**Comment by sigmundfreud2016** [comment]
![wowscrnshot_120715_123404](https://cloud.githubusercontent.com/assets/12395407/11625940/ffaa17b8-9cde-11e5-98a2-1cfdc0cdb3c0.jpg)
The animation is correct, but nothing is collected. I just wasted 1000g on it.

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
