### ISSUE TITLE
[Hunter][Talent] Ferocious Inspiration

### ISSUE THREAD

**Issue by yomasek** [Atlantiss/BugTracker#3210]
http://www.wowwiki.com/Ferocious_Inspiration
Ferocious Inspiration - Beast mastery talent does not work in a party. When I invite my partner to a party, buff disappears

**Comment by Tj20** [comment]
Can't confirm, the 3% damage buff seems fine to me in a group. Are you sure that you had your pet out, that both your pet and your partner were in range and that your partner is not a retri pala or arcance mage who provides a 3% damage buff himself?

![pic](http://i.imgur.com/r4CbBp9.jpg)

**Comment by yomasek** [comment]
oh, actually it was a retri pala, but i havent noticed any buff 3% from retri pala.

**Comment by aneq** [comment]
but if you checked your character tab you would see the 103% damage
Just the paladin 3% does not have its icon (well it kinda has but it never appeared even on retail) and probably the paladin buff took precedence.

**Comment by yomasek** [comment]
so if it is as you say, then u can close this issue

**Comment by Tj20** [comment]
As the author of this issue you can also close it yourself. :D
