### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by happyreaper111** [Atlantiss/BugTracker#3211]
guns not appearing

**Comment by Bildo** [comment]
but rules

**Comment by happyreaper111** [comment]
i am new to wow....wanted to know how too fix a bug in general
 


     On Saturday, May 9, 2015 7:28 PM, Bildo <notifications@github.com> wrote:
   

 but rules—
