### ISSUE TITLE
[en][mage][spell] Flame orb / Frostfire Orb

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3212]
When the getting stealthed out of it works perfectly fine, the orb itself pop out of stealth rogues with cloak of shadows and its really game breaking for them.
how it should work: when the stealthed class is in normal stealth the orb should get them out, but when they have cloak of shadows they are immune to spells so they can't be get out of it.
how it works: gets out of stealth everything not checking if target is immune to spells etc.
http://wow.gamepedia.com/Flame_Orb?cookieSetup=true

**Comment by lastkiss** [comment]
It also instantly removes vanish like a flare, dunno if it should

**Comment by blinkmaster** [comment]
this is actually working as intended, proofs were given by me and Wolfenstein in some entries ago ;) but this thing with cloak of shadows is bug

**Comment by blinkmaster** [comment]
can be closed, tested it and it seems thats cloak of shadows is bugged - sometimes it simply grants 0 immunity to spells. And becouse Cloak of Shadows is already submited there is no point for double ;)
