### ISSUE TITLE
[en][core mechanics] Skills/spells and Line of sight

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3214]
When some1 is close to the "pillars" ( for example in arenas) and you cast spells on them, they often dont get the desired spell, the spell goes on cooldown. Happens with both casts and melee, can be gamebreaking becouse melee hits can be "avoided" that way too.
how to replicate:
cast spells/use abilities/ autoattack character which is constatly LoSing you character close to pillar

**Comment by Isuel** [comment]
also happens when hitting stealthed targets, sometimes. (stealthed targets who appear for a second, time when u use the ability, then disappear)
