### ISSUE TITLE
[en][spell][shaman] spirit link totem

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3215]
Spirit link totem sometimes doesn't redistribute health properly, it should redistribute the health values but often it redistribute percents and sometimes it pretty much "tops" everyone to full health
http://www.wowhead.com/spell=98008/spirit-link-totem
how to replicate : 
get lvl 85 class for example warrior tank
get shaman with lvl apropriate for SLT ( smth about 60 if i remember corectly)
get warrior to like 5% hp with shaman full hp,
make shaman cast spirit link totem

**Comment by Tj20** [comment]
Hm, as far as I understand it, redistributing health percentages is what it's supposed to do, no?

I just did a test on the PTR with the instant 85s:

Warrior (109k HP) dropped to 17% HP, Shaman (39k HP) is at 100%.

after Spirit Link: both are at 60% HP.

before:
![pic](http://i.imgur.com/Oz6tHZj.jpg)
after:
![pic](http://i.imgur.com/fu1fZw5.jpg)

I think around 60% is pretty much exactly what should happen, isn't it? 17%+100%=117% / 2 = 58,5%. Close enough, I think.

Or do you mean something else? Someone reported a bug with SLT and Smoke Bomb (#464), but I'm not sure about this one.

**Comment by blinkmaster** [comment]
no, slt shouldnt redistribute PERCENTS but it should redistribute HEALTH - thats why it looks like that.
even in tooltip it is clearly written ;) so you just proved it is bugged, thx becouse i dont have shaman and couldnt do that :(

**Comment by Tj20** [comment]
The tooltip says
> Every 1 sec, the health of all affected players is redistributed, such that each player ends up with the same percentage of their maximum health.

I think it's pretty clear that this means percent.

Look at the wowhead comments of the link your posted above also:

>Basically, this is what it does: Take percentages (of HP) of all the group members. As an example I'll use these numbers (%): 45, 65, 12, 19, 67

> These numbers are added together which makes: 208. This is divided by the amount of group members, which is 5. This gives 41.6% - therefore everyone in the group gets 41.6% - it sort of makes everything level.

--
> So as to not cause confusion I would like to point out that this is EXACTLY how it works [...]. If person A is at 100% HP Person B is at 50% HP Person C is at 10% It will put those PERCENTS together, then divide them by three. This is 160%, leaving them all at 53.3% health. This means that regardless of how much health one has, it won't influence how much someone is healed for. A shaman using this totem that has 100K hp near a lvl 1 with 100 HP max will not make the lvl 1 be healed for more than their maximum HP. It is percentage based

**Comment by Tj20** [comment]
I mean, I get the difference.

For example:

person A) has 1.000.000 HP, is at 100% HP
person B) has 10 HP, is at 50% HP

using formala 1, Spirit Link Totem puts them at (100+50)/2 = **75% HP**. That is how it works on our server.

formula 2, proposed by somebody else in the comments says, it's 1.000.005 / 1.000.010 HP which puts them at **99,999%...** HP.

I don't play a shaman normally, but looking at the comments formula 1 is at 36 upvotes and formula 2 is at -6 downvotes, so I think we're using the correct formula here.

**Comment by Kejmil** [comment]
If solid proofs has to be shown here to fix this stupidity then i will provide them
SOON

**Comment by kadi2** [comment]
First of all, make sure it doesn't scale with healing modifiers.

**Comment by Tj20** [comment]
I don't have a high-level shaman on live (only on PTR because of the instant 85s atm) but if you need somebody to test some things drop me a line as a forum PM or my hunter Aliena if I'm in game.

Judging from the wowhead comments at first glance SLT seems to work as it is supposed to to me, but my knowledge about shamans is limited although I did have a level 90 resto on retail at some point.

**Comment by Jenovas** [comment]
"Every 1 sec, the health of all affected players is redistributed, such that all players are at the same percentage of maximum health." - the description of the spell

https://www.youtube.com/watch?v=G9lReLePe_E - in the video we see both the shaman and hunter have the same % of health.

Closing.

**Comment by Tj20** [comment]
Regarding healing modifiers: I haven't it tested on our server, but it should ignore all positive and negative healing modifiers.

> The damage dealt by the totem is nature damage. It could be resisted on the PTR (#333) but not on live anymore (R41#55, R41#91). In fact, the damage and healing dealt is unaffected by any damage and healing modifiers, including mortal strike effects. This can be abused on Halfus (healing a tank with 98% reduced healing back to full), Chimaeron (getting a tank up again in the last phase), and Cho'Gall (healing dps with 100 stacks corruption) (R41#92-97). ([source](http://www.guildportal.com/ContentControls/Support/InfoSectionViewer.aspx?GuildID=419563&TabID=3567230&GuildInfoSectionID=305895))

-
>SLT ignores all Mortal Strike and Healing debuffs (for the moment)
>SLT’s healing is not affected by personal +healing talents or effects (a Divine Guardian’ed player under SLT’s will not received 30% more healing from SLT).
>PW:S will absorb the damage from SLT (Example), conceivably PW:B will as well despite the lack of combat log evidence
>SLT’s balance of healing and damage occurs within the same second, theoretically balancing out to 0 with each tick
>SLT can overheal! I would assume that it’s caused by a heal landing in between the point where a player is selected for a heal, which no doubt precedes the heal itself, and the point when SLT’s heal actually lands ([source](http://lifeingroup5.com/?p=2315))

**Comment by Kejmil** [comment]
Test made today on retail:

Indifferent aka shaman with high max hp but low current % health
Cyckozord aka paladin with low max hp but max % current health

Suddenly, properly working spirit link totem aproaches:

http://imgur.com/KLESAt1,PC3kBJD (2 screens, before and after using slt)

It's super effective! (not like on atlantiss)

**Comment by blinkmaster** [comment]
just as i said, it should redistribute HEALTH first, trying to make HEALTH PERCENTS THE SAME but if it cant it just redistributes health

**Comment by Tj20** [comment]
Oh, good job! The majority of wowhead comment voters apparently was wrong then.

The question is: how exactly does it work?

Test results before:
Shaman: 4596/314k  (**1,5%**)
Paladin: 25.5k/25.5k (**100%**)

after:
Shaman: 46.6k/314k (**14,8%**)
Paladin: 3753/25.5k (**14,7%**)

2 methods from wowhead:

Method 1: (100%+1.5%)/2 = **50,75%** (clearly it's not that)
Method 2: (4596+25.5k)/(314k+25.5k) = 30096/339500 = **8,86%**

8,86% is still not the 14,8% we actually got, but it's much closer. Hmm...

**Comment by Kejmil** [comment]
we weren't in combat so it was just health regen, mostly from shaman

**Comment by Jenovas** [comment]
Should be fixed in rev 4559
