### ISSUE TITLE
[EN] [Quest] [The Zandalar Representative Chain Quest] [4.1.0 IMPORTANT],.

### ISSUE THREAD

**Issue by otto943** [Atlantiss/BugTracker#3217]
The chain is formed by:(speaking of Alliance Side)    

The Zandalar Representative
 Bwemba's Spirit
            To Fort Livingston works
            Serpents and Poison works
            Spirits Are With Us works
            Nesingwary Will Know works
            Track the Tracker works
            The Hunter's Revenge Bugged, quest can't be turned in. I think it should be automatically... http://www.wowhead.com/quest=29115/the-hunters-revenge   i'm stucked here...
            Follow That Cat Unknown
            Mauti Unknown
            How's the Hunter Holding Up? Unknown
            Bury Me With Me Boots... Unknown
            Some Good Will Come Unknown
            Warn the Rebel Camp Unknown
            Defend the Rebel Camp Unknown
            To the Digsite Unknown
            Voodoo Zombies Unknown
            Bad Supplies Unknown
            Making Contact Unknown

**Comment by Bildo** [comment]
this report is exactly relate to what ?

**Comment by krauza666** [comment]
http://www.wowhead.com/quest=29115/the-hunters-revenge 
You turned it in Bwemba npc.

**Comment by grindbox** [comment]
well, i dont know how to end Hunters revenge. the Cat just grabs the dwarf and flies away...
