### ISSUE TITLE
[PL][Achievement][Pit of Saron] Don't look up

### ISSUE THREAD

**Issue by Veruca1320** [Atlantiss/BugTracker#3219]
Po wejściu do tunelu brak jest "lodowego deszczu", plam, są tylko mobki, ale mimo pozbycia się ich achievementu brak. Na końcu tunelu jest ściana ognia (a chyba nie powinna).
link do achievementu: http://www.wowhead.com/achievement=4525/dont-look-up
tak powinno być: https://www.youtube.com/watch?v=yQ3agrSMtwg

**Comment by nerv234** [comment]
"Sauron"  is character from Lord of the Rings

**Comment by Veruca1320** [comment]
Haha! Thanks

**Comment by Brego55** [comment]
Still doesn't work. I was there few times and I don't see any rain of ice.

**Comment by Bildo** [comment]
fixed
