### ISSUE TITLE
[EN][NPC][Hellfire Peninsula]  Doom Lord Kazzak

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3220]
The NPC  Doom Lord Kazzak  (http://www.wowhead.com/npc=18728/doom-lord-kazzak), isn't present at Throne of Kil'jaeden.

I've never seen the NPC there, however the NPC apparently spawns like so: http://eu.battle.net/wow/en/forum/topic/3483959151#3 . Those are fairly high percentages, and I don't think many players kill it so it's odd that the NPC is never there.

Reporting just in case it is a bug.

**Comment by Axahus** [comment]
I killed it 2 times in last week so I'm sure that it isn't bugged. You just need more luck :P
