### ISSUE TITLE
[EN] [Quest] [Duskwood] The Yorgen Worgen 

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3221]
http://www.wowhead.com/quest=26717/the-yorgen-worgen
Apprentice Fess does not offer me this quest, I have done 25 quests in area so far but this quest does not open up for me.

**Comment by ahtebe** [comment]
First complete http://wow.gamepedia.com/Quest:Mistmantle%27s_Revenge , then complete http://wow.gamepedia.com/Quest:Part_of_the_Pack , then you should be able to get The Yorgen Worgen
