### ISSUE TITLE
[EN][Frenzy][Hunter] Frenzy

### ISSUE THREAD

**Issue by antonhagelberg** [Atlantiss/BugTracker#3226]
The talent doesn't work at all.

**Comment by Tj20** [comment]
What do you mean? It does work.

You pet has the buff which at 5 stacks indicates a 30% attack speed increase and the char sheet of the pet also shows the attack speed increase.

![pic](http://i.imgur.com/88zNIDe.jpg)

**Comment by Bildo** [comment]
1. it works
2. read bt rules
