### ISSUE TITLE
[PL][Death Knight] Regeneracja energi peta

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#3227]
<b>Jak jest teraz</b>
Pet regeneruje energię zbyt szybko. Obecnie spamując <a href='http://cata.openwow.com/spell=91776'>Claw</a> nie ma szans żebym wyładował energię do zera. Dlatego u nas <a href='http://cata.openwow.com/spell=91778'>Sweeping Claws</a> zadaje procentowo dużo więcej obrażeń niż meele dmg. Dla porównania
retail: <a href='http://www.worldoflogs.com/reports/j6rpxnaj0n3ubbze/details/52/?s=376&e=515'>Sweeping Claws</a>  meele 71.5% Sweeping Claws 20% Claw 8.5%
Atlantiss: <a href='http://worldoflogs.com/reports/oerzsmzh7q05u6g0/details/275/?s=8699&e=9079'>Sweeping Claws</a>  meele 41.7% Sweeping Claws 39% Claw 18.9%

<b>Jak powinno być</b>
<a href='https://www.youtube.com/watch?v=QeyZk893-yw'>Link</a> dowolny film z patcha 4.3. Widać jak energia przybywa w płynnie tak jak u rogue lub druida. W każdym dowolnym filmie na yt jest tak samo.

Potwierdza to też wpis z patchloga
<a href='http://www.wowwiki.com/Energy'>Energy</a> "Regeneration went from 20 energy per tick to 1 energy per decisecond."

**Comment by Jenovas** [comment]
On our server haste increases the ghouls energy regen. Maybe thats the problem?

**Comment by planche** [comment]
"Haste is decent, although it's no longer as remotely amazing as it was towards the end of Wrath. Do remember, it does now affect rune regeneration rates by the same amount at which it affects attack speed (meaning NewRuneRegenTime = (BaseRuneRegenTime) / (1 +(Haste%/100)), as well as our ghoul's energy generation rate (by that same formula)." 
 <a href='http://forums.elitistjerks.com/topic/109345-unholy-dps-cataclysm-406-the-missing-frame/'>EJ</a>
Według EJ haste powinien wpływać na regen energii ghoula. Może bazowa wartość regenu jest zbyt wysoka?

**Comment by planche** [comment]
fix please, dk zabija ludzi petem:(

**Comment by Jenovas** [comment]
Rev [4558]

**Comment by Kejmil** [comment]
teraz regen energii ghoula wydaje sie byc ok, a to ze nie mozna wyladowac energii ghoula - cos blokuje uzywanie clawa jesli ghoul ma ponizej 70 energii, nawet jesli manualnie kazemy mu to zrobic za pomoca /cast claw (przy manualnym uzywaniu taka blokada na bank nie powinna miec miejsca)

**Comment by Genomnomnomnom** [comment]
Confirmed - haste doesn't affect Ghoul's energy regeneration.

**Comment by nevcio** [comment]
bo nie powinien ale dmg ghul ma za niski

**Comment by Kejmil** [comment]
wolalbym ufac elite jerks niz randomowemu gosciowi z mmo-championa
niech ktos znajdzie pova unholy z sinestry to sie zaraz wyjasni

**Comment by nevcio** [comment]
https://www.youtube.com/watch?v=RyJLiYnc6UM
trudno znalezc nie bylo ;d

**Comment by Kejmil** [comment]
znaczy ghoul nie powinien miec regenu z haste (przynajmniej jesli chodzi o buffy), wiec:
a) ghoul ma za niski bazowy regen, na atlantissie dluzej trwa zgromadzenie energii niz na retailu
b) ghoul powinien benefitowac tylko z haste z gearu dk jesli chodzi o energy regen i to by wyjasnialo ta mala roznice

**Comment by nevcio** [comment]
teraz naladowanie energii peta od 0 do 100 trwa z 11-12 sekund zamiast 10 max

**Comment by Jenovas** [comment]
Fixed in rev 4840
