### ISSUE TITLE
[EN] [Quest] [Duskwood] The Halls of the Dead

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3232]
http://www.wowhead.com/quest=26753/the-halls-of-the-dead

I'm level 27 warrior and I can't make it across the first big room in the crypt without getting raped by a lot of ghouls that spawn from the ground as you walk over the graves in that area. They can not be targeted so I can not kill them. The spawn rate is very high. halfway across the room  I have 6 of them on me and they hit for 25 and crit for 40 dmg each not to mention the mobs in the same room that have to be dealt with also. I end up dead before I make it to the otherside. Please make the ghouls targetable so they can be killed.

**Comment by Walhallen** [comment]
They are many on other servers as well, but they can be targeted there.
