### ISSUE TITLE
[PL][Quest][The Storm Peaks] The Reckoning

### ISSUE THREAD

**Issue by RelmAtlantiss** [Atlantiss/BugTracker#3238]
http://www.wowhead.com/quest=13047/the-reckoning
Po kliknięciu opcji dialogowej, nic się nie dzieje.

![the reckoning](https://cloud.githubusercontent.com/assets/11969548/7586792/cbb83cc8-f8b0-11e4-82cb-797ba07ab8c2.png)

**Comment by Bildo** [comment]
hmm moze zla wersje wrzucilem albo dziala tylko po dc :<

**Comment by Veruca1320** [comment]
potwierdzam!

**Comment by Bildo** [comment]
potwierdzasz, ze co ? ze dziala tylko po dc czy to, ze nie dziala w ogole ?

**Comment by Veruca1320** [comment]
potwierdzam, że wciąż nie działa - kliknięcie w opcję dialogową nic nie daje.

**Comment by Bildo** [comment]
fixed
