### ISSUE TITLE
[EN][Core] "Being in Combat" is not working properly and causes bugs to game mechanics and Addons (Recount, Skada, Combustion helper)

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#3239]
The named AddOns are not working properly since the latest patch. The per combat doesn't work properly in recount and Skada. Combustion helper doesn't show up at all.
Same goes for the UI "in combat" indicators, like the swords over your level and the red sheen around your portrait.
I assume all these bugs have the same cause. Namely the "In combat" flag not being passed on to UI/AddOns properly.

Or something along those lines. I don't actually know the source code of Atlantiss so this is just an assumption.

**Comment by Nukeey** [comment]
This bug also affects Rage decay for warriors/feral tanks. And probably DKs as well by all logic.
This makes me assume that it is more than only the UI part of being in combat that is not working properly.

**Comment by Kejmil** [comment]
also mana regen is affected by this - in combat ui shows that you have regen like without it and then you mana get backwards to be in proper state

**Comment by krecik88** [comment]
We will look in to that today afternoon.

**Comment by Kejmil** [comment]
i can confirm that DK rp is falling off in combat, and talent which should give rp in combat doesn't work (or is overwhelmed by this falloff)

**Comment by krecik88** [comment]
4427 fixed
