### ISSUE TITLE
[en][mage][spell] Ring of Frost and Ice block

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3242]
Ring of frosts takes mage ice block as cc - it doesnt work when you are in block.
probably i will find more for this genius fix so you dont have to close it yet.
http://www.wowhead.com/spell=113724/ring-of-frost
http://www.wowhead.com/spell=45438/ice-block

**Comment by Jenovas** [comment]
Fixed in rev 4554
