### ISSUE TITLE
[EN][Core][Warlock] Affliction talent Jinx removes rogues' stealth and mages' invisibility

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#3244]
If you have invisibility and you are within the aura of Jinx ( http://www.wowwiki.com/Jinx ) then invisibility is removed. Happens also with rogue stealth. They should only break on damage.

**Comment by Propolys** [comment]
It's a warlock affliction thing though

**Comment by Milton3450** [comment]
not sure what your point is?

**Comment by Kejmil** [comment]
His point is that it is not invisibility bugged, but jinx which also screw rogues in stealth.
Change the title and description of issue to match real problem or make new one after closing this one.

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
