### ISSUE TITLE
[EN][Quest] Rise Of The Brotherhood

### ISSUE THREAD

**Issue by MaryShelley** [Atlantiss/BugTracker#3246]
Rise Of The Brotherhood ( http://www.wowhead.com/quest=26322/rise-of-the-brotherhood ), given in Westfall (Sentinel Hill) which says to talk to the king in Stormwind, is broken...when you go to the king the "continue" option is greyed out and nothing seems to fix it (logging, restarting, updating, etc)
I saw that this was an issue last November but it got fixed...it is broken again now

**Comment by armano2** [comment]
#3974
