### ISSUE TITLE
[PL][Quest][Redridge Mountains]Yowler Must Die!

### ISSUE THREAD

**Issue by Saranai** [Atlantiss/BugTracker#3253]
http://www.wowhead.com/quest=26545/yowler-must-die

Nie da się wykonać questa, mob znajduje sie pod ziemią.
Can't finish this quest, mob is underground(fell through the world).

**Comment by Thefakemccoy** [comment]
Cant really read what you wrote, But it worked last week when i did it.

**Comment by Yukitara** [comment]
I also have an issue with this quest similar to OP, Yowler is unreachable, and I cannot continue this quest line. Any feedback is appreciated.

**Comment by Thefakemccoy** [comment]
I think what it is he went through the world and fell in the cave system.

**Comment by Thefakemccoy** [comment]
![wowscrnshot_051415_025501](https://cloud.githubusercontent.com/assets/12252441/7627359/a529f1de-f9e4-11e4-9a15-9bbe8ae9e340.jpg)

I have him targeted he is either under ground or hiding in that tree.

**Comment by Aival94** [comment]
mob [Yowler](http://www.wowhead.com/npc=518/yowler) try to move through the bones in front of the fire and he get stuck and start move underground.I manage to do it after a crash of server which he spanw normally and get him before moving to the bones and underground.

**Comment by Bildo** [comment]
fixed
