### ISSUE TITLE
[EN] [Quest] [The Cape of Stranglethorn] Drive By Piracy

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3255]
http://www.wowhead.com/quest=26649/drive-by-piracy

"Speak with the Bloodsail Oarsman outside the Crimson Veil, then use the cannon to kill 75 Venture Co. Oil Workers." 

When I speak to the Bloodsail oarsman the small boat casts off with me under water. I can't target the venture company oil workers because I can't see them if I'm under the boat in the water. can not complete quest.

This quest is critical to The Bloodsail Buccaneers progression it is prerequisite to a quest chain that is needed to gain rep and complete the "Piracy" quests.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/360
