### ISSUE TITLE
[EN][Object][Quest][Stormwind City] Call board

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3258]
You can pick up troll incursion quest multiple times and keep turning it in.
![wowscrnshot_051415_034200](https://cloud.githubusercontent.com/assets/12252441/7627957/32898d72-f9eb-11e4-9e3d-c67876deebd3.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2831

**Comment by krauza666** [comment]
This is really major bug which allows you to get unlimited gold.

**Comment by Bildo** [comment]
fixed
