### ISSUE TITLE
[PL][ROGUE] Venomous Wounds

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#3259]
Po ostatnim updacie obrażenia są trochę zbyt wysokie. Skopiuję informacje z mojego poprzedniego zgłoszenia #2915
zgodnie z formułą z http://forums.elitistjerks.com/topic/104491-cataclysm-mechanics-testing/
675+.176*AP i informacją "It crits at your usual spell crit rate, and benefits from Potent Poisons and the spell damage buff (Master Poisoner or equivalent) but not Vile Poisons"
damage powinien wynosić: (675+0,176 * 11127) * 1,71 * 1,08=4863 (pomnożone przez 56% mastery i 8% z talentu Master Poisoner
testowałem przy 11127 ap 71% mastery
<b>Co jest źle?</b>
 Wygląda na to , że u nas <a href='http://cata.openwow.com/spell=16515'>Vile Poisons</a> wpływa na dmg <a href='http://cata.openwow.com/spell=79134'>Venomous Wounds</a>
(675+0,176 * 11127) * 1,71 * 1,08*1.36=6614 co mniej więcej pokrywa się z tym co jest teraz(screen niżej)
 <img src="http://i.imgur.com/bmBVn1r.jpg">

**Comment by Jenovas** [comment]
Z tego co pokazuje DBC to Vile Poison powinno wływać na DMG.
Również patrząc np DMG rogala w T12 z 14k AP i niego Venomous Wounds bije średnio za 8k - 8.5k.

Tak więc policzmy:
(675+0,176 * 14000) * 1,71 * 1,08 * 1.36 = 7884

W T12 pewnie ma więcej Mastery od Ciebie więc DMG tam wzrośnie do 8k i ponad trochę.
Tak więc nie widze tutaj buga.

**Comment by planche** [comment]
W weekend po raidzie sprawdzę wyniki z logami wtedy będę w stanie to lepiej porównać.

**Comment by Jenovas** [comment]
planche - co zrobiłes że w pierwszych testach miałeś 6800 tick a teraz masz od 11-20k? Trochę dziki ten rozrzut. Zupełnie jakbyś miał nie wiem dwa trinkety pod mastery odpalane albo buffa +200% na DMG.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/3400

**Comment by planche** [comment]
Pierwszy screen jest z kukły bez żadnych buffów + nie używałem vendetty a 2 jest z warunków raidowych. Mam 2 trinkety ze stałym agility bez żadnych odpałek. Jedyny odpalany bonus do statystyk to potion na agility

**Comment by Jenovas** [comment]
Fixed in rev 4488
