### ISSUE TITLE
[EN][Guild]Guild creation - cannot obtain charter signatures

### ISSUE THREAD

**Issue by Liebeqt** [Atlantiss/BugTracker#3260]
Players are unable to sign a guild charter. They don't get a window asking them to sign or decline, nothing happens at all.

Signing a guild charter is possible for the first player that signs it, but all the following players can't.

Tested on alliance character: created a charter, got 1 signature, tried to get 3 other players to sign, none were able to.

Deleted the charter, created another one. Again managed to get 1 signature, then tried to get more by 2 other players, but again with no success.

**Comment by Hansrutger** [comment]
This must be fixed really fast... Please :/

**Comment by tuxwizzle** [comment]
You can make a guild if the 5 people get the prompt to sign before any of them accept. Made a guild yesterday doing that. Still needs to be fixed

**Comment by Jenovas** [comment]
https://github.com/Atlantiss/BugTracker/issues/3102
