### ISSUE TITLE
0 Armor Bug

### ISSUE THREAD

**Issue by danih92** [Atlantiss/BugTracker#3261]
My protection warrior "Krod" somehow has 0 armor. 

It doesn't matter what I do. Any kind of relogg doesn't work. Re-equipping doesn't work. Even when I get buffed by for example protection aura it says "Armor 0 (-X)(+X)".

**Comment by Jenovas** [comment]
Did you try removing cache?

**Comment by danih92** [comment]
Yes I did. Didn't fix it though.

However now it's fixed.
