### ISSUE TITLE
[EN] [NPC] [Western Plaguelands] Zen'Kiki

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3269]
http://www.wowhead.com/npc=44863/zenkiki

"Bring Zen'Kiki to the Malicia Outpost in Western Plaguelands, then break 4 Captive Plaguebears out of their cages and allow Zen'Kiki to heal them. "

Zen'Kiki does not heal the bears when I free them.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/2763
