### ISSUE TITLE
[EN][Quest][Icecrown]Argent Aid

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#3273]
http://www.wowhead.com/quest=13363/argent-aid

[Highlord Tirion Fordring](http://www.wowhead.com/npc=31044/highlord-tirion-fordring) is missing. Quest can not be turned in. It's blocking major Icecrown questline

**Comment by imeasytokill** [comment]
I did this q, u have to do diffrent q in Icecrown, and then Highlord Tirion Fordring will show. i think its bugged by can be achive. i dont remember which q it was.

**Comment by Varchord** [comment]
I should be able to see him as soon as i pick up the quest. Not after doing other quests

**Comment by Bildo** [comment]
chain order is messed up, this has nothing to do with quest, as @imeasytokill said you have to do certain quest to unlock Crusader's Pinnacle phase
