### ISSUE TITLE
[ENG][NPC][Instance] Magmaw 10 Heroic

### ISSUE THREAD

**Issue by Arganthos** [Atlantiss/BugTracker#3274]
Good morning!

Yesterday, our guild noticed a pretty serious bug wth the 10m H version of the Magmaw encounter; the boss seems to transition to the final burn phase (with Nefarian casting his AoE Shadowflame Barrages) even if the boss reaches 30% HP during an Impale phase; the boss have never, and it's not suppose to do that (the phase should only start AFTER the Impaled phase has ended).

The bug has been replicated twice.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3143

**Comment by Jenovas** [comment]
Should be fixed in rev 4430
