### ISSUE TITLE
[EN][Quest][Westfall]Secrets of the Tower

### ISSUE THREAD

**Issue by Zwizzor** [Atlantiss/BugTracker#3275]
Potion of Shrouding applies the buff correctly, but the visual effects are not here.
It should look like this : http://wow.zamimg.com/uploads/screenshots/resized/373344.jpg but just looks normal.
Edit: the NPCs are not here either, but this is already reported here : https://github.com/Atlantiss/BugTracker/issues/2420

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2338
