### ISSUE TITLE
[PL][Quest][Winterspring]Hunting Practice

### ISSUE THREAD

**Issue by gregoryfaded** [Atlantiss/BugTracker#3277]
Witam http://www.wowhead.com/quest=29038/hunting-practice quest ten nie działa, gdy podbiegam z kotem do kupki śniegu on nic nie robi a powinien zbierać jakieś króliki lub co innego. Jest to daily potrzebny do zrobienia q http://www.wowhead.com/quest=29034/they-grow-up-so-fast w którym to trzeba  daily questy w tym ten przez 20 dni robić także bardzo przydałoby się żeby działał. GM Myivo widział na własne oczy i napisał mi żebym zgłosil to tutaj.
Pozdrawiam Faded.

**Comment by gregoryfaded** [comment]
Już działa jak coś, sprawdziłem przed chwilą.

**Comment by Bildo** [comment]
nic nie bylo robione z tym questem, ten q dzialal :D

**Comment by gregoryfaded** [comment]
Robiłem go wcześniej i nie dało się.....

**Comment by gregoryfaded** [comment]
Ale juz nie ważne
