### ISSUE TITLE
[PL][Talent][Paladin] Sanctity of Battle

### ISSUE THREAD

**Issue by kukukz** [Atlantiss/BugTracker#3278]
Efekty podobne do http://www.wowhead.com/spell=88286/downwind-of-altairus [Downwind of Altairus]
zwiekszaja cd na Crusader Strike i Divine Storm. Znaczy wizualnie nie zwiekszaja. Mija cd a nie da sie uzyc spella bo niby jest na cd. W tym przypadku cd trwa 2 razy dluzej. Jakiejs tragedii nie ma ale czasami potrafi to byc irytujace bo podwaja normalnego cd tych spelli.

**Comment by Wojowniczka** [comment]
@kukukz  popatrz na inne zgłoszenia odnośnie talentów innych użytkowników i popraw to zgłoszenie.

**Comment by Malvoli0** [comment]
(I used google translate to see what you guys were saying)

I am not sure the problem is caused by Sanctity of Battle, will test further, but Crusader Strike / Divine Storm definitely have a problem with their cooldown.

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
