### ISSUE TITLE
[EN] [Quest] [Wailing Caverns] Deviate Hides

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3279]
http://www.wowhead.com/quest=26872/deviate-hides

As many npc's that are in there it should be no problem to loot 10.

This is the second time i have done this instance.
The first time i barely managed to get by with 10 
hides
The second time i only manged to come up with 9.

The drop rate is way to low or its not in the loot table for some.

Lootable Mobs
http://www.wowhead.com/item=6443/deviate-hide

**Comment by Bildo** [comment]
fixed
