### ISSUE TITLE
[EN][Guild]Guild creation - cannot obtain charter signatures

### ISSUE THREAD

**Issue by dodouser** [Atlantiss/BugTracker#3281]
For example players are unable to sign a guild charter. They don't get a window asking them to sign or decline the ideea is that nothing happens at all.

If signing a guild charter is possible for the first player that signs for the other players they can't.

Tested on alliance character: created a charter, got 1 signature, tried to get 3 other players to sign, none were able to.

Deleted the charter, created another one. Again managed to get 1 signature, then tried to get more by 2 other players, but again with no success.

**Comment by Jenovas** [comment]
https://github.com/Atlantiss/BugTracker/issues/3102
