### ISSUE TITLE
[EN][Creature] Dragonmaw Peon

### ISSUE THREAD

**Issue by darklord88** [Atlantiss/BugTracker#3285]
When i do http://www.wowhead.com/quest=11020/a-slow-death quest in Shadowmoon Valley (Netherwing Ledge) using quest item on dragonmaw peon my client freeze and getting error after 10 minute.I think some scripts bad about these npcs.

**Comment by Varchord** [comment]
post wowerror

**Comment by XrayAlert05** [comment]
Have similar problem. Each time I do quests in netherwing ledge (daily) my client is frozen and can't do anything.

**Comment by Philippe777** [comment]
Same problem. For some reason the Dragonmaw Peons there are flagged as Horde? Maybe that's the reason, because they should probably be friendly, since we're disguised as a dragonmaw...

According to this vid (https://www.youtube.com/watch?v=vYLAZshMncY) they should be friendly.

**Comment by Varchord** [comment]
dont write in closed topics. Devs don't read them
