### ISSUE TITLE
[EN] [NPC] [Western Plague Lands] Hearthglen Mustang

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3290]
So you mount the horses to scare the spider for one quest. And another to lure them to be killed by guards. 

But when you dismount the horse they stay and dont disappear leaving tons of horses around.

![wowscrnshot_051715_161526](https://cloud.githubusercontent.com/assets/12252441/7671922/2bcb8df6-fcb0-11e4-9ac3-d28084670a30.jpg)

**Comment by Bildo** [comment]
wowhead links !

**Comment by Thefakemccoy** [comment]
Horse
http://www.wowhead.com/spell=83771/hearthglen-mustang

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2340
