### ISSUE TITLE
[EN][Talent][Rogue] Deadly Momentum

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3293]
http://wow.gamepedia.com/Deadly_Momentum
After killing an opponent that yields experience or honor, you have a 50/100% chance to increase the critical strike chance of your next attack within 15 sec by 40%, and to refresh your Slice and Dice and Recuperate abilities to their original duration.

i don't know if this is bugged, but you are supposed to last hit the mob to get the buff? because when you are in party and you don't last hit the mob you don't get the buff.

**Comment by Thefakemccoy** [comment]
you have to get the last hit for it to proc. You have to have the killing blow
