### ISSUE TITLE
[EN] [Quest] [Badlands] Lifting the Veil

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3294]
http://www.wowhead.com/quest=27770/lifting-the-veil

"Witness the final piece of Rhea's studies"

no cut scene is generated quest is bugged. can not complete quest.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/1632

#1632 

This post will be closed. FYI

**Comment by Bildo** [comment]
yep i'm fast

**Comment by Thefakemccoy** [comment]
cheater
