### ISSUE TITLE
[EN][Item][Deepholm] Ricket's Tickers

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3295]
Ricket's Tickers (http://www.wowhead.com/item=65514/rickets-tickers) does not send players flying when it explodes, as can be read in the wowhead comments and this video: https://youtu.be/2rtgPTBdNIs?t=43s .

**Comment by Thefakemccoy** [comment]
If you want it for that reason to get to higher places you can fly in those caves.

**Comment by ahtebe** [comment]
I know that, but the item does not do all it is supposed to do. So it is a bug. Very low priority, but still a bug.

**Comment by Thefakemccoy** [comment]
Well in that cause the cave it self is bugged you shouldn't be able to fly in it.

**Comment by ahtebe** [comment]
Yeah, you shouldn't be able to fly there: https://youtu.be/CE0IJYg6GUw?t=14s , after getting past the goblin quest giver it automatically dismounts. (Oddly enough on Atlantiss druid flight form doesn't work inside the cave).

**Comment by Thefakemccoy** [comment]
Ill take flying over fixing the bomb any day.
