### ISSUE TITLE
[EN][Quests][Western Plaguelands]Combat Training

### ISSUE THREAD

**Issue by Juau** [Atlantiss/BugTracker#3297]
Right now, [Combat Training](http://www.wowhead.com/quest=27174/combat-training#comments) isn't working properly. You are supposed to receive an army of farmers to fight [Gory](http://www.wowhead.com/npc=45212/gory) after you talked with the NPC. As the quest tittle says, this is a training and you're not in a untill death match. However, in Atlantiss, you do not get that peasent army and you don't need to talk to [Gory](http://www.wowhead.com/npc=45212/gory) as it is hostile to everyone. In retail servers, Gory "gives up" at 10% hp as in our server the quest only completes when you kill poor Gory.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/332
