### ISSUE TITLE
[EN][Class][Paladin] Censure(dot)/ Seal of truth/ Seals of command

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#3298]
I've been doing some tests for quiet a while now. The only thing i keep noticing is that i pull less dmg than i should be doing according to simcraft. (settings were no raid buffs but your own, probably that is with food and flask buf). Simcraft says i should be pulling 20020 dps.

After doing few rounds of rotation (8minutes each) i have an anverage dps of 17,5k, sometimes 18k max. Now you can discuss several options which cause this, or i'm doing something wrong in my rotation, something might be wrong with elite dummy's?, OR the dmg a retri paladin can pull is just to low. 

EVERY spell compared to simcraft deals LOWER amount of dmg, except for seals of command (this is bugged, it deals 2 ticks every melee attack, instead of 1) which is causing this is unknown to me. 

http://prntscr.com/766wsq

This is one of the results simcraft gave me for my dps. as you can see there are +- same amount of ticks for seal of truth and seals of command, on my recount i have twice as many ticks for seals of command.

Here is the full list of my dmg of 1 of the rotations i did:
http://i.imgur.com/iBS0f7B.jpg
http://imgur.com/u8EARjV.jpg

Now first i wanna talk about the spells i put in the title. To start with Censure(dot). According to simcraft it should be dealing an average hit tick of 4,9k. With crits up to 10k. (crit% on simcraft was 5.2% of ticks critted). Here is what i got: 

http://i.imgur.com/iBS0f7B.jpg

224 ticks, 1 crit. Now i know its only 1 try, but on that amount of ticks such a difference noticable. On top of that is that my avg tick of the spell deals ONLY 3,3k dmg. (50% lower than on simcraft). 

The 2nd spell, seal of truth, has the exact same problem; 

http://i.imgur.com/GgCEPXR.jpg

433 ticks, 0 crits. according to simcraft, they had also a comparable 5.1% crit. An avg tick on my recount did 1.5k dmg, Simcraft has an average tick of 2k (again a 25% less dmg from this spell).

As noted before, seals of command has double ticks, but also for this spell, crit isn't working at all;
http://i.imgur.com/taEnbyI.jpg

864 ticks, 6 crits. Though its doing double ticks, also this spell is dealing 25% less dmg compared to simcraft.

Yes this may be caused by the dummy, maybe not. The only thing i know is that compared to simcraft i'm doing a pretty decent rotation since i'm casting more crusader strikes per melee attacks than they are doing, which means i should be doing more dps ( since i'm generating more holy power). Though all spells do less dmg than on simcraft, atleast with 5-10%) What's causing this = no idea.

**Comment by Jenovas** [comment]
We do not use simcraft for spells. Calculate the DMG and create one report for every one of them if the DMG is wrong.
