### ISSUE TITLE
[EN][Quest][Badlands] The Day that Deathwing Came: What Really Happened

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3299]
http://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened
 
"Choose an admirer to save"
"Beat Deathwing in a knife fight"

Can not complete this quest there is no admirer or deathwing to be found at designated location.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/1358
