### ISSUE TITLE
[EN][Quest] Ambushed! (Phase bug)

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#330]
Before I explain what's the problem, I have to say that this issue actually starts before you even take "Ambushed!". You take the quest "The Abandoned Crypt" (http://www.wowhead.com/quest=27170) and you're sent into some crypt to retrieve weapons. This crypt normally shouldn't have any mobs around, or inside of it, but they are actually spawned there at all times, and they shouldn't be.

How it should work is that when you go into the crypt, and turn in "The Abandoned Crypt" quest at Broken Weapons Crate (http://www.wowhead.com/object=205258), and then take "Ambushed!" (http://www.wowhead.com/quest=27171) quest, you would then be in the phased version of this area where the mobs are spawned, and you need to get back out, and along the way, as you're killing them, pick up the items that you need for a quest.

If you read the wowhead comments here http://www.wowhead.com/quest=27171 , you can also understand how it should work, as one of the wowhead members explained it pretty well.

**Comment by BAndysc** [comment]
Fixed in 4774
