### ISSUE TITLE
[EN][Quest][Badlands] The Day that Deathwing Came: The Real Story

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3300]
http://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story

"Grow large enough to reach the clouds"
"Find Deathwing"

I do not "grow large" there is no hot bar interface. Can not complete quest.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1358
