### ISSUE TITLE
[PL][SPELL][SHAMAN] Fire/Earth Elemental Totem

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#3301]
Totemów z elementalami nie powinno dać się używać na arenach, na Atlantissie można je przyzwać np. przez Call of the Elements.

Link do spella: http://cata.openwow.com/spell=2894
Dowód (pierwsze zdanie): http://us.battle.net/wow/en/forum/topic/1965569489

**Comment by Bildo** [comment]
duplikat https://github.com/Atlantiss/BugTracker/issues/3568
