### ISSUE TITLE
[EN][NPC][Badlands] Victoria Dolen

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3305]
http://www.wowhead.com/npc=46930/victoria-dolen

This NPC keeps getting killed by 2 Ridge Stalker Patriarchs http://www.wowhead.com/npc=2734/ridge-stalker-patriarch that keep wandering into the camp. can not interact with her if she is dead.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6569-npc-ridge-stalker-patriarchs-in-dragons-mouth-alliance-camp-killing-npcs/
