### ISSUE TITLE
[PL] [bot] Valiona and therliona

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#3307]
twilight blast zadało mi od 34k do 35 k mamy z 5.0.1 dmg tego http://www.wowhead.com/spell=86369/twilight-blast#changelog na hc 25 ten błąd nie występuje.
![image](https://cloud.githubusercontent.com/assets/8699987/7697880/0a964c9a-fe0c-11e4-847f-73c0ec2a0f74.png)

twilight flames ogień nie leci do nas tylko pojawia się jak z nikąd na nas nie możemy tego nawet uniknąć.
https://www.youtube.com/watch?v=jCcAm_fFDrY  1:50  - 1:60  
Na fazie kiedy valiona rzuca paskami ogień therliona nie rzuca twilight flames na tym etapie a powina.
valiona paski ognia nie rzuca randomowo tylko ciongle lewa środek a póżniej prawa albo prawa, środek i lewa.
twilight meteor zadaje z 14k-15k powinien z 11k-12k
http://www.wowhead.com/spell=86013/twilight-meteorite#changelog
biłem sie na hero zapomniałem jak jest na normalu....

**Comment by Atraac** [comment]
Zmień realmlist z Moltenowego na Atlantiss i sprawdź jeszcze raz.

**Comment by InformatorPE** [comment]
Twilight Blast u nas na 25 HC biło średnio 24k, może Ty jednak nie na tym serwerze odbywałeś raid
http://www.worldoflogs.com/reports/m5obpdojw3btlfa3/spell/92905/?source=139&s=1813&e=2223&target=27

**Comment by arekczup** [comment]
skąd podejrzenia że grałem na moltenie?

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/838
Zacznijcie może czytać 
https://github.com/Atlantiss/BugTracker/blob/master/README.md

W ogóle nie wiem o czym on opowiada. Mówi o ogniu valiony a daje filmik do [Dazzling Destruction](http://www.wowhead.com/spell=86408/dazzling-destruction)

Na 10 hc działa. Ubiłem w obecnym ID

Każdy damage jest dobry, idź lepiej poczytaj newsy z kilku miesięcy wstecz zamiast linkować changelog 4.3.

IMO to do zamknięcia jest
1. Dubel
2. Zle napisane 
3. O co tu chodzi
4. Takie wyssane z palca to jest,
