### ISSUE TITLE
[EN][NPC] Withdrawn Soul

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#331]
Withdrawn Soul (http://www.wowhead.com/npc=45166) are always hostile, but they should actually be friendly (green).

They only CAN turn hostile when you use a quest item on them, and even then, it's not 100%, they just have a chance to turn hostile when you use the quest item on them, while you're on "Those That Couldn't Let Go" (http://www.wowhead.com/quest=27168) quest.

**Comment by TranceAccount** [comment]
Cannot reproduce on PTR.
