### ISSUE TITLE
[EN][Spell][Paladin] Hand of Freedom

### ISSUE THREAD

**Issue by zixsen** [Atlantiss/BugTracker#3313]
Encountered this bug in arenas today, when I tried to cast hand of freedom (http://www.wowhead.com/spell=1044/hand-of-freedom) on my mage friend while he was silenced by garrote (http://www.wowhead.com/spell=703/garrote) it wouldn't go off, and I would get the error message, "Can't do that while silenced."

To clarify my friend (the mage) was the one who was silenced, not me (the paladin).

**Comment by Aydien** [comment]
bump. still bugged

**Comment by zixsen** [comment]
Bump still bug'd cant freedom people while they are silenced.

**Comment by Wingnanx** [comment]
Damn I missed the 1 year anniversery of this bug.

This issue still persists, if your teammate is silenced you can not give them hand of freedom, only when the paladin himself is silenced this should persist.

**Comment by zixsen** [comment]
and I missed the 2 year anniversery 🥇

**Comment by Bugtrack123** [comment]
Realy annoying "gamebreaking" bugg which still persists

**Comment by pelekon** [comment]
There will be no 3 anniversary, muahahah 😈
