### ISSUE TITLE
[EN] [Client] Crash

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3314]
So my client crashed when i was doing quest:
http://www.wowhead.com/quest=11949/not-without-a-fight

I restarted the game 
and it put me on a flight patch to who knows.
![wowscrnshot_052015_174237](https://cloud.githubusercontent.com/assets/12252441/7737285/eebf126a-ff17-11e4-9fab-793162682d52.jpg)

![wowscrnshot_052015_174414](https://cloud.githubusercontent.com/assets/12252441/7737288/f396754e-ff17-11e4-84b9-e055c414d4d2.jpg)

**Comment by Thefakemccoy** [comment]
Finally it dropped me in the middle of the ocean here.
![wowscrnshot_052015_174608](https://cloud.githubusercontent.com/assets/12252441/7737312/2f5720ba-ff18-11e4-9245-a6fe58c45af8.jpg)

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/3316

Both diff but both simialar in ways

**Comment by xolon** [comment]
there is something wrong with your client if you crash that much as i can see in your reports. i have never had a client crash ( does not include server crash) when i was leveling my alt from lvl 1 to 85

**Comment by Thefakemccoy** [comment]
Doing that quest on both toons is the only time my game has ever crashed. I have done it on 2 toons now same result.

**Comment by Tj20** [comment]
see: [EN][Core] WoW Error in Kaskala #1791

It's the Kaskala Defenders in that area, I think. When a group of 3 or more Kaskala Defenders kills the last enemy they were fighting and leaves combat the game grashes. 

You don't even have to do anything... the game just crashes when the Defenders do their thing and you are nearby.
