### ISSUE TITLE
[EN][Quest][Searing Gorge] Lunk's Adventure: Rendan's Weakness

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3315]
http://www.wowhead.com/quest=28034/lunks-adventure-rendans-weakness

"Speak with three Iron Summit Guards and ask them to join your dance"

When I accept the quest lunk follows me but when I speak to the guards there is no chat interface. I can not ask them to join me.

This quest is the third part of a five part quest chain and as a direct result of this quest being bugged I can not complete the following 2 quests.
1. The Mountain-Lord's Support http://www.wowhead.com/quest=28035/the-mountain-lords-support
2. Operation: Stir the Cauldron http://www.wowhead.com/quest=28052/operation-stir-the-cauldron.

**Comment by Aival94** [comment]
Furthermore the npc [Lunk](http://www.wowhead.com/npc=47430/lunk) seems to be having an aura which make everyone around him to start dancing.

**Comment by Nepajimsi** [comment]
This quest was bugged on retail wow to, so i think i would be good if dev make it auto complete

**Comment by tomatosz** [comment]
*bump* This also makes it impossible to turn in Dark Iron Residue for Thorium Brotherhood rep, as this comes further on in the chain.

**Comment by visi212** [comment]
And what ? Do you repair this quests ?

**Comment by Aequitass** [comment]
Bump

**Comment by w273** [comment]
just completed it, the problem seems to be with the guards, after you get them to dance for you they don't return to their original status (there's a similar issue with one of the borean tundra quests where that mage is always or rather stays captured, both were bugged on retail iirc)

try to do it after a restart, that's your only way of completing it i guess

**Comment by karhima** [comment]
Still bugged and cannot be completed.

**Comment by arndry** [comment]
this quest is just doable after a server reset. still bugged

**Comment by tomatosz** [comment]
Tried after server reset, still not working

**Comment by rasmodeus** [comment]
This quest is still bugged.  Because of this, cannot get the quests that follow this to turn in dark iron residue with the Thorium Brotherhood.  Can this please be autocompleable?  Waiting for a random server reset seems quite tedious.

**Comment by coba999** [comment]
can't interract with Iron Summit Guard!

**Comment by jackal86** [comment]
Bump! still bugged, everyone is dancing around me but no way to complete it.

**Comment by xStiven** [comment]
Bump. Yep, another broken chain there. Guards is not intractable,

**Comment by Dranerys** [comment]
Bump!! Still bugged

**Comment by XreaperDK** [comment]
Bump. It's been over 2 years!

**Comment by xmesaj2** [comment]
after rev. 5514 guards should respawn properly

**Comment by valadilajne** [comment]
I've the same problem. I can't interact with any one guardian :( I try abandon this quest, I try logout with this quest before abandon, I try logout after abandon quest and nothing!
Please help me with this quest.
