### ISSUE TITLE
[EN][Dungeons][RDF]

### ISSUE THREAD

**Issue by madKinno** [Atlantiss/BugTracker#3319]
At the moment, even when everyone in the party choose to kick a player from RDF, we get the message that kick failed. This is an issue that exists for some time now. Same bug occurs in all lvl RDF's.

How to reproduce: Initiate voting to kick someone from the dungeon and ask everyone to confirm and observe what happens. More info on how it should work here http://www.wowwiki.com/Dungeon_Finder

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3256
