### ISSUE TITLE
[EN][Quest][Western Plaguelands] Combat Training

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#332]
**In Combat Training** (http://www.wowhead.com/quest=27174) quest, four farmers should accompany you on this quest to challenge **Gory** (http://www.wowhead.com/npc=45212) to a duel, and defeat him.

First bug is that farmers never appear for you, so you're on your own, one versus one against **Gory** with 8,000+ HP, and that can be problematic for some classes.

Second bug is that **Gory** should be a friendly npc, and you need to talk to him, go through a dialogue, asking him for a duel, and then he turns hostile, and you fight. On our server, he is always hostile.

Quest can be completed by simply killing him, but it's not blizzlike.

Here's the video of this quest - https://www.youtube.com/watch?v=UjkrNKNpo3I

**Comment by stewazy** [comment]
This quest also leaves a buff on you for the whole time i don't know why but i have combat training and Farmers' Militia buff on me everywhere i go. Whats up with that, how can i get it off me ?

**Comment by Tarvo27** [comment]
How to get these permanent buffs off??? It's so annoying?

**Comment by ylluminarious** [comment]
Same problem here; I'm stuck with this "Combat Training" buff everywhere I go.

**Comment by Tiennshan** [comment]
Its labelled ich changelog as fixed but the buffs still stay after logout.

**Comment by armano2** [comment]
duplicate: #482

**Comment by Enay** [comment]
Actually, that report is a duplicate, not this one. I posted mine on November 20th, and that one was posted on November 27th.

**Comment by armano2** [comment]
Sorry for closing your issue, but they are linked still and person who is going to fix it will have both messages.
