### ISSUE TITLE
[EN] [Quest]  [Darkshore]  The Ancients' Ire

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3320]
hi the npc Vengeful Protector is bugged when i mount in Vengeful Protector  he cant move i can kill 30 monsters but  i cant burn building and quest cant be finish it  here screenshots and videos !!
http://www.wowhead.com/quest=13514/the-ancients-ire
http://prntscr.com/77p0yo
https://www.youtube.com/watch?v=Wn4hLS7013w
http://www.wowhead.com/npc=43742/vengeful-protector

**Comment by Aival94** [comment]
already reported #646
Try to search before reporting sth :)
