### ISSUE TITLE
[EN][NPC]Therazane the Stonemother 

### ISSUE THREAD

**Issue by Leastways** [Atlantiss/BugTracker#3321]
NPC inactive, i cant interact with him, tried change flag on war in reputation panel...not help. NPC need for achievement - http://www.wowhead.com/achievement=4871/deep-into-deepholm and gain reputation.

**Comment by Aival94** [comment]
It can be good to wait for the updates to be implemented(now they are in state "Waitiing for update") and then report sth if not yet fixed(try search if there is already in bugtracker already either open or close as well)

rev. 4435 Author: Quban :: 2015-05-20 21:09 - Waiting for update
Firelands:

fix some spells
fix majordomo melee damage
Forge of Souls:

fix Atlantiss/BugTracker#3309
Quest:

fix Atlantiss/BugTracker#3296
fix Atlantiss/BugTracker#2542
fix Atlantiss/BugTracker#2503
Misc:

fix Atlantiss/BugTracker#3295
fix Atlantiss/BugTracker#3288

#2542
