### ISSUE TITLE
[PL][Other]Transmogrification

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#3322]
Nie mogę zrobić transmogu dwuręcznego miecza. Poniżej filmik jak to wygląda.

https://youtu.be/-ArDFCEKJ00

**Comment by Malylolek** [comment]
Jeśli mnei pamiec nie myli itemy do transmo musza miec statystyki, twój miecz ich nie ma dlatego sie nei udaje.

**Comment by Haz3L** [comment]
Nie powinno tak być.

**Comment by Nc94** [comment]
U nas na serwie jest własnie bug przez który nie można transmogować itemów bez żadnych statów z samym procem - było już zgłaszane pare razy.
