### ISSUE TITLE
Burn in Effigy

### ISSUE THREAD

**Issue by Atyors** [Atlantiss/BugTracker#3323]
Does not work. We cannot use the torch near the ships. When I try to burn "Bor's Hammer" it writes that I should be near the ship. Even if I'm inside and I tried all arround.

**Comment by Thefakemccoy** [comment]
title is wrong and wow head link

http://www.wowhead.com/quest=11656/burn-in-effigy

**Comment by Anhaeyn** [comment]
This quest works. You need to stand in front of ship, near bow. Then use quest item. I did this quest some time ago, and worked this way.

**Comment by Thefakemccoy** [comment]
@Anhaeyn how long is some time ago i seen a quest break in a matter of a week.

**Comment by Anhaeyn** [comment]
Last week I think. Atyors has to stand under these dragons (or horses?) to be able to burn these ships. http://wow.zamimg.com/uploads/screenshots/resized/105216.jpg

**Comment by Thefakemccoy** [comment]
Ehh it might work idk i was just basically linking the info cause when bildo comes around he will kick it back.

**Comment by Anhaeyn** [comment]
If this quest really broke, then okay. I just tried to help ;)

**Comment by Thefakemccoy** [comment]
IDK if it is or not maybe you can get with them in game and see i dont have a horde toon

**Comment by Anhaeyn** [comment]
Sure, I can help him in game if he wants.

**Comment by Bildo** [comment]
This quest works, there are additional ships and some of them doesn't count for quest (which is not a bug of course). Next time read but rules also.

**Comment by nobileus** [comment]
It works, just need to stand under those dragons and snakes in front of the ships.
