### ISSUE TITLE
[EN][Item] Coarse Stone Statue

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3326]
Coarse Stone Statue (http://www.wowhead.com/item=25880/coarse-stone-statue) doesn't work, it does not heal. It should do this: "+15hp/tick for 12 ticks (1 tick/sec) This is still correct as of 4.1" like this "Drops a small Uldaman looking rock mob that uses a channeling spell, which looks like mana drain, but instead heals you over time." (source: http://www.wowhead.com/item=25880/coarse-stone-statue#comments)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/347
