### ISSUE TITLE
Zul'Drak bug with Storm King's Vengeance

### ISSUE THREAD

**Issue by nolemelon** [Atlantiss/BugTracker#3331]
I was doing the quest in Zul'Drak and everything was working fine until my spells stop responding so i tried doing a /reload, but when i came back all my spells had disappeared so i abandoned the quest to try to restart it, but the zone didn't reset. After that i tried re-logging still nothing changed so i figured that i needed to leave the zone for it to reset so i hearthed. When i arrived in Dalaran i noticed no mobs, objects, or portals  had loaded so i was still stuck in the quest state. Then i tried re-logging still no luck. Please help as of now i can't play the game

**Comment by Wojowniczka** [comment]
god damn ppls learn to give links....... for example to this quest (no1 cares that u writted name of quest in issue topic)

**Comment by Thefakemccoy** [comment]
here is the link:
http://www.wowhead.com/quest=12919/the-storm-kings-vengeance

also can you rethink the first 2 words in your statement 
Thanks :)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/518

**Comment by nolemelon** [comment]
No, you're missing the point, I don't care if I can or can't finish the quest. I abandoned the quest but the fame still zoned me as if I was on the quest. Literally meaning no npc anywhere will spawn.

**Comment by nolemelon** [comment]
Game*
