### ISSUE TITLE
[PL][BG] Strand of the Ancients Bomb

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#3332]
Po użyciu bomby powinna ona się pojawiać przed bramą, tak aby drużyna przeciwna miała możliwość ją rozbroić. Obecnie jeżeli użyje się bomby będąc blisko bramy pojawia się ona w teksturach i nie ma mozliwości jej rozbrojenia, a osoba która użyła bomby nie musi jej bronić tylko idzie po następną.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2664
