### ISSUE TITLE
[PL][Spell][DK] Ghoul

### ISSUE THREAD

**Issue by SadistPL** [Atlantiss/BugTracker#3333]
Po zmianie specjalizacji UH >> BL Ghoul zostaje jako pet na stałe. Nie wiem jednak czy zawsze, czy przy specjalnych warunkach - zwrócę na to teraz uwagę przy zmianie, ale może z samej informacji będzie można coś rozpracować.

**Comment by Jenovas** [comment]
Ale jak to robisz? Masz Ghoula przy sobie peta w UH, zmieniasz spec i ghoul nie znika? Czy zmieniasz spec i znow wzywasz Ghoula i on znow jest petem?
