### ISSUE TITLE
[EN] [NPC] Rex Ashil

### ISSUE THREAD

**Issue by death2you2** [Atlantiss/BugTracker#3334]
Hello, i just tried to tame this rare mob called 'Rex Ashil' he should be tameable but he isn't??
He isn't a *beast* it says but he should be tameable....??
![wowscrnshot_052315_135645](https://cloud.githubusercontent.com/assets/12572548/7784113/5618e10e-015a-11e5-8ef4-35ed5fbab549.jpg)

**Comment by Thefakemccoy** [comment]
maybe he is a exotic pet and you need to be BM

**Comment by death2you2** [comment]
But even if he was exotic he should still be saying 'beast' under his name, for example this one is exotic and still has 'beast' and im pretty sure that the wasp isnt exotic 
![wowscrnshot_052315_144611](https://cloud.githubusercontent.com/assets/12572548/7784120/827fe4e0-015a-11e5-91ed-d913488fb43c.jpg)

**Comment by Anhaeyn** [comment]
It's a Wasp, not Beast. Wasps are tameable too. Beasts are for example wolves, tigers, stags etc. 
http://www.wowhead.com/npc=14475/rex-ashil

**Comment by death2you2** [comment]
Ohhh i see, so it is tameable but exotic?

**Comment by Anhaeyn** [comment]
Petopia doesn't marks wasps as exotic, so I think you should be able to tame him. If you can, try to learn second spec - beastmastery and try with this spec to tame him.

**Comment by armano2** [comment]
#3823
