### ISSUE TITLE
[EN][Issue in magic/keyboard buttons response]

### ISSUE THREAD

**Issue by nenormalen** [Atlantiss/BugTracker#3337]
Hello Atlantiss!
I have some issues after I installed bartender4 and masque addons. Actually i am not sure if they are the cause of the problem i am experiencing. The problem is this - when i click on any of my abilities i am experiencing some latency. I mean that I have to press 2-3 times my spell so it can activate and everything turns into mashing keyboard buttons so 2-3 spells activate properly. I've disabled masque addon but still experiencing the same issue. Can you pls give me some advice?
Best regards!

**Comment by Anhaeyn** [comment]
Maybe it's your keyboard's fault?

**Comment by nenormalen** [comment]
I think not... Everywhere when i am typing it is perfect with no delay, but when i start using my abilities in wow i have to tap them 2-3 times so they can activate.

**Comment by Bildo** [comment]
can't reproduce it
