### ISSUE TITLE
[EN][Item - Potion] Potion of Concentration + Alchemist Stone

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#3344]
Potion of Concentration, Link - http://www.wowhead.com/item=57194/potion-of-concentration#comments

It doesnt get affected by Alchemists Stone(AKA + 40%). In my case Vibrant Alchemist Stone.
This potion should be affected by it, but it doesnt. Ive tested it 10 times and i got numbers between 18 and 22k (1.8 to 2k~ticks) (Tooltip shows up to 22k, and it does not take the Alchemist stone into account) These numbers are in the range of the normal potion tooltip without a 40% buff wich means the 40% does not aply to this exact potion. Comments from the link can confirm. 

Edit: Also every time the character dies the 40% buff provided by the stone is removed upon character death, and u have to re equip it all the time in order to get the buff back. This is wrong...the buff should never be removed.

**Comment by Quban** [comment]
fixed in rev. 4482
