### ISSUE TITLE
[EN][Druid] Skull Bash interrupts while frozen

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#3345]
Exactly what is decribed in the link below. The report got closed and bug was supposedly fixed. Still bugged. As a mage I freeze the druid and I stand 5 yards away. He can interrupt me even while frozen. He still remains frozen tho. Yes, I am not in melee range.

https://github.com/Atlantiss/BugTracker/issues/2139

**Comment by Jenovas** [comment]
The distance is 8 yards, if your farther than 8 yards he shouldnt interrupt you.

**Comment by Milton3450** [comment]
Ok, that makes no sense to me but you seem to be certain :) sorry and I will close the report.

**Comment by Jenovas** [comment]
You can do the test, I did it when the fix that you showed was made. If it bugged again let me know.
But the distance is 8 yards not 5.

**Comment by kadi2** [comment]
spell range + target's hitbox = range of skull bash in roots
(5 yards - range of skull bash in roots) + (3 yards - hitbox of any player) = 8 yards
