### ISSUE TITLE
[EN][NPC][Est. Plaugelands] Gidwin Goldbraid is over powered

### ISSUE THREAD

**Issue by Anthrex** [Atlantiss/BugTracker#3346]
The dwarf paladin that follows you around in Eastern Plaugelands, Gidwin Goldbraid, deals 3000 damage every tick when he casts Consecration.

**Comment by Bildo** [comment]
wowhead links

**Comment by Anthrex** [comment]
sorry, first time doing this, http://www.wowhead.com/npc=45730/gidwin-goldbraids
