### ISSUE TITLE
[EN] [NPC] [West. Plaugelands] broken loot tables

### ISSUE THREAD

**Issue by Anthrex** [Atlantiss/BugTracker#3347]
Rare mobs in Western Plaugelands are level 36, but they will drop level 58 gear, many other mobs north of Andorhal also have broken loot tables, possibly because they were unchanged from pre Cataclysm to post Cataclysm

**Comment by Bildo** [comment]
wowhead link to these npcs

**Comment by Anthrex** [comment]
sorry, first time doing this, give me a few minutes to go find them again, I didn't know about the bug tracker and this happened last night

**Comment by Anthrex** [comment]
http://www.wowhead.com/npc=1837/scarlet-judge was one of them, however on wowhead one of the drops has a level requirement of 55, so I guess this is normal? it just seemed off getting such a high level item at such a low level.

**Comment by Bildo** [comment]
fixed
