### ISSUE TITLE
[EN][Quest][Redridge Mountains]Yowler Must Die

### ISSUE THREAD

**Issue by rawhunger** [Atlantiss/BugTracker#3349]
I know this issue has already been submitted, but I thought I would do one in English.

Yowler is still not where he is supposed to be and I've been standing here for a hour waiting to spawn or re-spawn or whatever.  I can't get any more quests here in Redridge now, at least not that I know of.

Here's a screenshot...
![wowscrnshot_052415_140519](https://cloud.githubusercontent.com/assets/9438170/7789218/bece5fac-021e-11e5-908c-493bd041c851.jpg)

It's been like that for an hour now.  Is there anything that can be done about this?

**Comment by Dean1989** [comment]
#3253
he's inside the terrain, atm you can kill him after a server crash before he move near the bones and got bugged.

**Comment by rawhunger** [comment]
So... I have to wait for a server crash to complete this quest?  Can't a GM just spawn him?

**Comment by Dean1989** [comment]
this is how it can be doable or you have to wait until it get fixed. or simple just move on to another zone

**Comment by rawhunger** [comment]
I have a feeling things (at least in the vanilla lands) don't get fixed too quickly. That's a shame for the new players.

**Comment by Thefakemccoy** [comment]
actually they do get fixed. Depends on who has the zone

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3253
