### ISSUE TITLE
[EN] [NPC] [Blasted Lands] You Are Rakh'likh, Demon

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3350]
http://www.wowhead.com/quest=26171/you-are-rakhlikh-demon

"destroy Razelikh's body, then use the Stone Knife of Sealing to imprison his soul."

Impossible to kill there are multiple spawns of him attacking at once he's a level 57 elite.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2898
