### ISSUE TITLE
[EN][NPCS][SOUTHERN BARRENS] Frazzlecraz Miner

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3352]
http://www.wowhead.com/npc=39280/frazzlecraz-miner
there are few of these npcs outside the mine and are friendly, so you can't attack them. the mine
instead is completely empy.

from this video you can see a bit how the zone should be: https://www.youtube.com/watch?v=TvrJ86Cbtow

**Comment by Bildo** [comment]
you are horde or alliance ?

**Comment by Dean1989** [comment]
ally
