### ISSUE TITLE
[EN][NPC] Stone Bat 

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#3357]
http://www.wowhead.com/npc=42523/stone-bat#drops

They should have 5,368  hp, Currently they have 53.7k hp

**Comment by Alandiel** [comment]
Are you sure about that?
http://www.wowhead.com/npc=44289/abyssion
http://www.wowhead.com/npc=42543/crystal-gorged-basilisk
http://www.wowhead.com/npc=43513/verlok-pillartumbler
http://www.wowhead.com/npc=43171/jaspertip-crystal-gorger
Look at their hp.

**Comment by Varchord** [comment]
Ok, i stand corrected. hey should have 5,368 hp. 
http://wowwiki.wikia.com/Stone_Bat
Last change since August 20, 2011 was about adding ID to them.

Still, they have 10x more hp then they should

**Comment by vove9000** [comment]
Hmm, on wowhead and wowdb it says they have 710 hp, but 5,368 seems about right as they attack in packs. Low hp was also the reason they removed loot and skinning possibility on those mobs.

**Comment by Varchord** [comment]
wowhead and wowdb were updated for WoD. All things in WoD have lower hp then they used to

> As of 31 Jan 15, these do not drop anything nor are they skin able. If you're trying to farm savage leather, go northwest to the pale roost and hit up the dragons and basilisks, decent drop rates.

I guess disabling skinning on them happened on WoD too

**Comment by Dean1989** [comment]
there are a some comments from 4.0.3, 4.0.6, 4.1 that say these mobs can't be looted and skinned.

**Comment by Varchord** [comment]
I guess you are right
