### ISSUE TITLE
Worgen quest crashes wow (Chance the cat)

### ISSUE THREAD

**Issue by marknguyen22** [Atlantiss/BugTracker#3360]
After i took this quest, I ran to the cat location then wow crashed, its keep crashing every time i get in the game. I have cleared cache but it didn't work. 

Im playing on Macbook pro mid 2010 (Lion)
My character names : Drakeinz

**Comment by RawrWolf** [comment]
Hey Darkeinz
i've been haveing the same crashing issue in that area.
You will have to unstuck your character useing 5 vote points then cast your heartstone!
=) goodluck and sorry it happened to you too! :(

**Comment by marknguyen22** [comment]
Thank you for your advice, so can i continue to finish that quest after ?

**Comment by RawrWolf** [comment]
i finished the quest just fine -- just try to avoid that spot as much as possible.
i crashed around the horse quest area. xD sucks men.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3329
