### ISSUE TITLE
Dmg mage 

### ISSUE THREAD

**Issue by Mikox1** [Atlantiss/BugTracker#3363]
[EN][Frostbolt][Mage] ~25k crit dmg
[EN][Ice Lance][Mage] ~22k crit dmg (5k + 16k absorbed)
Bloodtirsty mage on 3599 resilence, 364 iLvL shaman enhancement.
http://www.tinypic.pl/uyhph7xrcdel

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
