### ISSUE TITLE
[PL][Priest][Spell] PoM and LoF

### ISSUE THREAD

**Issue by Windwalk** [Atlantiss/BugTracker#3365]
Hej,

Podczas BG nie mozna rzucic innym graczom PoM i LoF, prosze naprawic :F 
Chcialam jeszcze dodac, ze MC tez jest zbugowane, przeciwnik moze po czesci sterowac podczas MC -.-

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker
