### ISSUE TITLE
[EN][Dungeons] Cataclysm Heroics

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3368]
Ok, so this isn't really a bug report, but more like a question that I think will get the best answers here.

Are the 85 heroics tuned for 4.3.4 or are they from 4.1 content? In other words, are they nerfed or prenerfed?

For example, Ozruk (http://www.wowhead.com/npc=42188/ozruk#abilities) does a shatter which should kill anyone (according to a comment it does upwards of 150k damage), however on Atlantiss it does barely half that much (tested as tank, no cooldowns... did not die when I should've).
His ability Paralyze (http://www.wowhead.com/spell=92426/paralyze) should stun and deal 50k + damage when it expires (http://www.wowhead.com/npc=42188/ozruk#comments:id=1222243), however it only roots and I let it expire and noticed that my health bar was pretty much the same (no shields or anything).

I don't know if the fight how it is on Atlantiss is accurate as of 4.3.4... and the same goes to all other heroic fights. So i don't know if I should report these bugs (like the Ozruk example given) or not.

**Comment by Jenovas** [comment]
Spells are nerfed, they have to be nerfed because we are running on 4.3.4 and all spell data is generated automatically from the WoW DBC files, so DMG will be lower.

As for Paralyze that is a bug that it doesnt deal DMG.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1155
