### ISSUE TITLE
[EN][NPC] Ripsnarl

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3369]
Npc is not in right location 
http://prntscr.com/79c6l1
http://prntscr.com/79c6sd

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by vove9000** [comment]
<a href="http://www.wowhead.com/npc=47626">Admiral Ripsnarl</a>

It was reported in #2061 as well and closed by @Bildo
