### ISSUE TITLE
[EN][Quest][Deepholm] Underground Economy

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3372]
After the update the bunnies for the quest
http://www.wowhead.com/quest=27048/underground-economy

have been all over the place

![wowscrnshot_052615_024319](https://cloud.githubusercontent.com/assets/12252441/7806632/571155ac-0351-11e5-9fe7-43a7703e94a0.jpg)

**Comment by Bildo** [comment]
fixed

**Comment by Samineh** [comment]
Still bugged :( :-1:
