### ISSUE TITLE
[EN][QUEST][Mulgore] Thunderhorn Totem

### ISSUE THREAD

**Issue by helldeskmonkey** [Atlantiss/BugTracker#3374]
Prairie Stalkers don't appear to drop Stalker Claws. I've killed about 30 so far and not a single one has dropped. Incidentally, this blocks the main Mulgore quest chain. 

http://www.wowhead.com/quest=24441/thunderhorn-totem

**Comment by Bildo** [comment]
wowhead links

**Comment by helldeskmonkey** [comment]
http://www.wowhead.com/search?q=+Thunderhorn+Totem

**Comment by helldeskmonkey** [comment]
http://www.wowhead.com/quest=24441/thunderhorn-totem

**Comment by anijatsu** [comment]
I've got the same issue.

**Comment by richarddewit** [comment]
+1

**Comment by hachuking** [comment]
yes sadly this is not fixed yet having the same issue right now.

**Comment by BAndysc** [comment]
Fixed in rev. 4464
