### ISSUE TITLE
[EN][QUEST][Mulgore] The Restless Earth

### ISSUE THREAD

**Issue by helldeskmonkey** [Atlantiss/BugTracker#3375]
Restless Spirits didn't spawn in the digsite - in fact, nothing was alive there. I waited around for respawn, nothing. Quest can't advance.

**Comment by Bildo** [comment]
wowhead links

**Comment by helldeskmonkey** [comment]
http://www.wowhead.com/quest=14491/the-restless-earth

**Comment by Helbringer** [comment]
I can confirm this and i also note that, they do spawn, but they just spawn in textures inside the hill next to the digsite.
![wowscrnshot_072315_011253](https://cloud.githubusercontent.com/assets/10423624/8840424/d202ff9a-30d8-11e5-8397-d42291598def.jpg)
