### ISSUE TITLE
[EN] [NPC] Evolved Twilight Zealot

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3376]
He puts a debuff on you called Grievous Whirl. It should go away when you are healed to full yet it does not.

Ability
http://www.wowhead.com/spell=76524/grievous-whirl
NPC:
http://www.wowhead.com/npc=39987/evolved-twilight-zealot
Zone:
http://www.wowhead.com/zone=4926/blackrock-caverns

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/1458

**Comment by Thefakemccoy** [comment]
Ok so i looked it up and it wont labeled right not my fault.
