### ISSUE TITLE
[PL][CLASS][ROGUE] Smoke Bomb

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#3377]
Po ostatnich fixach można targetować z zewnątrz Smoke Bomb. Spell stał się bezużyteczny.

**Comment by Varchord** [comment]
A ja się zastanawiałem czemu mnie napierdalają nada! Myślałem, że źle używam xd

**Comment by Jenovas** [comment]
POprawione już proszę czytać changelog
