### ISSUE TITLE
[EN][Quest][Dragonblight] Planning for the Future

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/BugTracker#3378]
Hi Atlantiss,

The WotLK Quest Planning for the Future
http://www.wowhead.com/quest=11960/planning-for-the-future 
is now bugged to me. I can click the puppies,
http://www.wowhead.com/quest=26178/planning-for-the-future
but am not receiving credit nor are they appearing
in my bag. I have been doing this daily for 2 weeks
and all was fine, till the last 2 dayz.
TY SwimzwSharkz

**Comment by Bildo** [comment]
wowhead links

**Comment by armano2** [comment]
#3550
