### ISSUE TITLE
[EN] [Quest] [Deepholm] Battlefront Triage

### ISSUE THREAD

**Issue by Reddie90** [Atlantiss/BugTracker#3379]
Quest:
http://www.wowhead.com/quest=26591/battlefront-triage

When trying to apply the Deepvein's Patch Kit to Injured Earthen it tells the player "You can't do that right now" Not sure is it because the Injured Earthen's have 100% health or other reason. Cannot be completed

**Comment by Reddie90** [comment]
Also Troggs in the area are neutral but they should be hostile. Not sure if relevant or not

**Comment by Thefakemccoy** [comment]
This is what retail looks like

![wowscrnshot_052615_131950](https://cloud.githubusercontent.com/assets/12252441/7818476/f22150da-03a9-11e5-8830-26758889434b.jpg)

**Comment by Reddie90** [comment]
Found a solution, the Injured Earthen's cannot be patched up if you are not in combat. Get some troggs to follow you near to the Injured Earthen and fight it for awhile, then apply the Deepvein's Patch Kit to the Injured Earthen. Still, it is not working as it should

**Comment by phtdwfaa** [comment]
Comment to eddie:
SOLUTION is not bound to being in combat, you just need to have missing HP. So either get chopped by some trogg or take fall dmg or sthing.
