### ISSUE TITLE
[PL][NPC] Honor to Justice Point converstion

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#338]
http://www.wowhead.com/npc=52033#comments

As of 4.1 you can purchase 250 Justice Points for 375 Honor Points from Edlan Halsing (Alliance) and Rogoc (Horde). You can purchase 250 Honor Points for 375 Justice Points from Talric Forthright (Alliance) and Togar (Horde).

U nas nie ma możliwości wymiany honoru na JP ani na odwrót

**Comment by Varchord** [comment]
BUMP

**Comment by Magohoy** [comment]
This is implemented now, but does not work.
The Merchant says "You dont have the required items" when you try to buy Honor for Justice.
