### ISSUE TITLE
[EN] [Item] Withered Basidium

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3381]
http://www.wowhead.com/item=24483/withered-basidium

This item has a 3% drop rate and I farmed withered giant for over 1 hour and nothing dropped.

This item starts 2 part quest chain. http://www.wowhead.com/quest=9827/withered-basidium

**Comment by Aival94** [comment]
Maybe there is a issue with the drop rate but for me it droped after kiling many.

**Comment by lourrific** [comment]
With 3% drop rate after killing 100 withered giants 3 withered basidium should have dropped. I killed over 100 and none have dropped.
