### ISSUE TITLE
[EN][CORE] Fishing

### ISSUE THREAD

**Issue by Docholiday-Atlantiss** [Atlantiss/BugTracker#3386]
So i know there have been other issues posted about fishing. 

My issue is some times when i fish even in SW. the fish hits the bobber and i click it nothing happens.
Other times i click it and i catch nothing and get a skill point

If the fish gets away the bobber bugs in the water so when i go to cast again the first bobber is still there and thats the one that gets hit but i cant click it.

Also fishing is completely broke you should never miss. So no fish should ever get away unless you never click the bobber.

As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and all casts will catch something and award a chance for a skill-up. However, if your skill level is too low for a zone, you will catch mostly vendor trash items.

http://us.battle.net/wow/en/game/patch-notes/3-1-0

Currently i am looking for the Weather-Beaten Journal for fish finding.
http://www.wowhead.com/item=34109

I have gather a couple crates just to open them and they be empty.
This does not happen every time but random crates will be empty which should not be.

Current crates opened to be empty:
http://www.wowhead.com/item=21228/mithril-bound-trunk
http://www.wowhead.com/item=27481/heavy-supply-crate
http://www.wowhead.com/item=27513/curious-crate
http://www.wowhead.com/item=21150/iron-bound-trunk

**Comment by Thefakemccoy** [comment]
I want to add the the catch to skill gain is off.
                 
1-75:		1	 7
76-145:		2	 140
146-190:		3	 135
191-225:		4	 140
226-265:		5	 200
266-300:		6	 210
301-340:		8.5	 240
341-400:		9.5	 570
401-450:		12.5	 625
450-495:		13	 585

This table was gotten from 
http://wowwiki.wikia.com/Fishing?action=edit&section=8

it was never updated after cata.

**Comment by Veruca1320** [comment]
i have the same problem - nothing happens when i click on the bobber when it jumps. It's not all the time but very often and it shouldn't be since i have max fishing skill.

**Comment by Thefakemccoy** [comment]
Before i open the crate
![wowscrnshot_052715_085544](https://cloud.githubusercontent.com/assets/12252441/7836486/8de2876a-044e-11e5-8f1b-d0b7e25f6740.jpg)

**Comment by Thefakemccoy** [comment]
After opening the crate.
![wowscrnshot_052715_085546](https://cloud.githubusercontent.com/assets/12252441/7836499/a3906eb0-044e-11e5-8ba8-a14bd96634d4.jpg)

**Comment by LaveGit** [comment]
Often the crates are empty, but not always. The number of times the crates are empty seems way too high though (I don't know if they always should contain something or not, don't beat me on that :P). Weather-Beaten Journal is obtainable from the crates here on Atlantiss as well (the times they contain loot that is), so it's still obtainable.

**Comment by Thefakemccoy** [comment]
BUt the crates should never be empty they always have something in them even if its junk they have been like that on retail always.

**Comment by Thefakemccoy** [comment]
Also fishing is completely broke you should never miss

As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and all casts will catch something and award a chance for a skill-up. However, if your skill level is too low for a zone, you will catch mostly vendor trash items.

**Comment by sunshineinabox** [comment]
Sometimes the fishing daily also shows up as "This slot is empty"

**Comment by Thefakemccoy** [comment]
@sunshineinabox I havent really tested those out much if you have issues you might want to add the wow head link for the ones you have issues with.

**Comment by sunshineinabox** [comment]
I've gotten empty rewards from each of the Stormwind, Dalaran and Shat daily quests.

The items that are rewarded are the following:

[Bag of Fishing Treasures](http://www.wowhead.com/item=34863/bag-of-fishing-treasures)

[Bag of Fishing Treasures](Baghttp://www.wowhead.com/item=46007/bag-of-fishing-treasures)

[Bag of Shiny Things](http://www.wowhead.com/item=67414/bag-of-shiny-things)

**Comment by Thefakemccoy** [comment]
So i ran roughly a 10 min test on fishing.

![wowscrnshot_052815_103345](https://cloud.githubusercontent.com/assets/12252441/7862881/cb4e340e-0526-11e5-8d67-d791171288fe.jpg)

In the first image i did a screen shot of my fishing skill the time of start. I started with a 382 fishing skill with a +25 pole and a +150 lure. making my fishing skill=557. With 0 fish caught.

In the Frozen Sea in North Rend it requires a 575 fishing skill to make it a 100% catch rate. I had a 93% catch rate

![wowscrnshot_052815_104413](https://cloud.githubusercontent.com/assets/12252441/7862927/240a620c-0527-11e5-9485-b3a28c4b7d9e.jpg)

Roughly 10 min later i stopped the clock.
As you can notice in the picture my skill had gone up to 389+175=564 which means a  96% catch rate. 

For 10 minutes i did not catch a thing I am still at 0 caugh. I caught nothing from fishing not even the  trash items.

**Comment by Thefakemccoy** [comment]
Test 2 3mins

So after the NR test i went to hyjal and did a test at 389 fishing with the +25 pole= 414 fishing. Hyjay requires a 100% chance fishing at 575. I had only 51% chance to catch anything.

![wowscrnshot_052815_105725](https://cloud.githubusercontent.com/assets/12252441/7863219/25f9ead6-0529-11e5-81e9-a4f1a7923aea.jpg)


In the close of my 3 min attempt.

I ended with 390fishing+25pole=415 52% chance

I caught 7 total items. 1 being a failed attempt which was a weed.

All open water not in a pool. 

![wowscrnshot_052815_110026](https://cloud.githubusercontent.com/assets/12252441/7863283/6c477aa8-0529-11e5-8522-cb1dbfcf10ec.jpg)

**Comment by Lidless** [comment]
UP

**Comment by Docholiday-Atlantiss** [comment]
I will be closing this one as I am working on a core issue tracker and a seperarte container iuuse tracker. 
Core is #8055
