### ISSUE TITLE
[EN] [Quest] [Zangarmarsh] The Sporelings' Plight

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3387]
http://www.wowhead.com/quest=9739/the-sporelings-plight

"Fahssn at the Spawning Glen wants you to collect 10 Mature Spore Sacs"

Can not interact with spore sac. Item can not be collected.

http://www.wowhead.com/quest=9739/the-sporelings-plight#screenshots:id=62909

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2870
