### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Escaped From Gilneas

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#339]
What is not working:
=============

The NPC that should give you the quest is not appearing when fighting some mobs **(more info below)**

---------------
How should work:
=============

While fighting some mobs, a worgen (NPC) should appear near you, and give you the quest (no need to accept).

--------------------
More info:
=============

[Private Status](http://www.private-status.com/39,11,85,53908/atlantisspl,quest:escaped-from-gilneas)

The mobs are:
[Cursed Darkhound](http://www.wowhead.com/npc=1548)
[Decrepit Darkhound](http://www.wowhead.com/npc=1547)

Quest:
[Escaped From Gilneas - WoWHead](http://www.wowhead.com/quest=24992/escaped-from-gilneas)
[Escaped From Gilneas - WoWPedia](http://wowpedia.org/Quest:Escaped_From_Gilneas)

Check out WoWHead comments because they got useful information.
Some players say that only the "Cursed Darkhound" trigger the NPC, others already said that they got the quest from the Decrepit one.

Another note is (by checking WH's comments): you don't need to kill the mob to trigger the NPC, some players say that the mob needs to attack you.

WoWPedia's notes:
[Darkhound Pounding](http://wowpedia.org/Quest:Darkhound_Pounding#Notes)
[Escaped From Gilneas](http://wowpedia.org/Quest:Escaped_From_Gilneas#Notes)

**This was tested on 4.0.6a realm**

**EDIT#1:** WoWPedia says this quest has a previous one (requires), [Darkhound Pounding](http://wowpedia.org/Quest:Darkhound_Pounding), WHead comments said that can get this quest while doing the other one. Testing now!
**EDIT#2:** No luck. Even after you completed [Darkhound Pounding](http://wowpedia.org/Quest:Darkhound_Pounding), the NPC still doesn't appear.

**Comment by Angelo-DM-** [comment]
Confirm! no one worgen is spawned while fighting cursed darkhounds! (ID: 1548)
While you kill one of them, you should see a worgen, and the quest should automatically added in your quest log!
If you decide to abandon this quest, a new quest: "Have You Seen Anything Weird Out There?" http://www.wowhead.com/quest=25039 become available from "Ratslin Maime" http://www.wowhead.com/npc=6785, and You can't take anymore the first quest (escaped from gilneas).

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/4020
