### ISSUE TITLE
[EN] [Quest] [Mount Hyjal] [82] Magma Monarch

### ISSUE THREAD

**Issue by darkiepie** [Atlantiss/BugTracker#3391]
So, the quest, given by commander Shadowsong, entitled "[82] Magma Monarch", u are suposed to kill the magma monarch with the help of tortolla, you summon tortolla with drums which they give youj to use at the location of the magma monarch, when u use it your character just does the animation non stop, even thou the turtle is already spawnned, when u lead the monarch to the turtle, the turtle doesn't attack at all, and in under 1 minute your game crashes.

Tried it 3 times, basicly if u use the item your game crashes, tortolla doesn't attack, your character gets in summoning action the hole time.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Dean1989** [comment]
confirmed
