### ISSUE TITLE
[EN][NPC] Boulderslide Mobs

### ISSUE THREAD

**Issue by Johndoe53** [Atlantiss/BugTracker#3393]
The NPC's in Boulderslide Cavern (in Stonetalon Mountains) dont attack.They just follow you but dont hit you. Just wanted to point this out while it does not stop you from actuallly completing the quest.

**Comment by Dean1989** [comment]
adjust the title of your report or it will be ignored.
https://github.com/Atlantiss/BugTracker/blob/master/README.md
