### ISSUE TITLE
[EN] [CORE] Random 5-man Heroic Lockout

### ISSUE THREAD

**Issue by Valaya** [Atlantiss/BugTracker#3394]
Currently, if you've done every heroic using LFG tool (random), and if you're locked to all of them, you can't queue up again.
The way it works on retail; you can do same HC unlimited times per day if you use LFG tool, but if you've done it already (regardless if it's LFG or specific), you can't do it by queueing for specific or walking to dungeon.

http://www.mmo-champion.com/threads/1208640-How-do-Heroic-lockouts-work
http://wow.gamepedia.com/Heroic_mode 

http://www.wowhead.com/forums&topic=244488/heroic-dungeon-lockout

"Heroic dungeon can only be completed once a day if you queue for the particular one.
You can still get it in random dungeon however (after)."

More links, including the blue post: http://www.engadget.com/2009/12/07/dungeon-finder-tool-mini-faq/
http://blue.mmo-champion.com/topic/1545-07-12-dungeon-finder-tool-mini-faq/

**Comment by Aival94** [comment]
This was implemented during 4.3 patch.

"Players who use Dungeon Finder for a random Heroic dungeon will no longer be locked to that instance. Previously, players who entered an instance via the Random Dungeon option were then prohibited from queuing for that dungeon or entering the instance manually via the portal. Players should now always be able to complete a specific Heroic dungeon once per day regardless of any random dungeons completed."

Maybe they will try to implement it when they make the 4.3 content as for now they are still working in 4.2 content.

http://wowwiki.wikia.com/Patch_4.3.0

**Comment by Thefakemccoy** [comment]
Ill do one better the actual Blizz patch notes.

http://us.battle.net/wow/en/game/patch-notes/4-3-0#dungeons

**Comment by Dean1989** [comment]
adjust the title of your report pls
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Valaya** [comment]
> Ill do one better the actual Blizz patch notes.
The notes state: "...players who entered an instance via the Random Dungeon option were then prohibited from queuing for that dungeon or entering the instance MANUALLY via the portal."

The bluetracker post I've linked talks about the changes to random dungeon finder in 3.3 changes ("..For example, if you log into the game right after 3.3 is released") and the date of the post is 12/07/2009, several months before the 3.3.0 patch, which was released 09/12/2009 (http://us.battle.net/wow/en/game/patch-notes/3-3-0)

This game mechanic was from Wrath of the Lich King; also, adding another source: 
http://wow.gamepedia.com/Instance_limitations---> 
"Random heroics are exempt from instance locks: if you receive a dungeon that you are saved to as a random, you can enter it as though you weren't saved. However, random heroics do create instance locks. What this means is that in one day, you can clear a heroic dungeon first as a specific (or by traveling to it without the Dungeon Finder) and then as a random, but not vice-versa."

**Comment by Thefakemccoy** [comment]
It might have been some what added in 3.3 but it still said you was most likely to NOT get one you have already run. I think they fixed in in 4.3 can you can queue RHC and get the same one back to back.

Also like was stated the client is in 4.3 But the game is in 4.2ish. I say that cause the IF and Darnasus cooking and fishing dailies are not aval which was added 4.3

**Comment by Thefakemccoy** [comment]
I think basically how it worked in 3.3 You could run all the heroics by walking into them. And getting a lock out and Queueing RHC ad getting a seperate lock out meaning you could only do them each twice a day.

In 4.3 the RHC lock out was removed all together.

**Comment by Aival94** [comment]
During 4.1 players can only do once per day each cata heroic dungeon(they probably have removed for cata heroics what you said Valaya).After 4.3 they remake it so you can queue do same heroic as many times as you want(i think there is a limitation of 15 heroics per day) but only if you enter via rdf(not specific) so you can enter it many times but not if you enter it via specific que or manual going there.

**Comment by Thefakemccoy** [comment]
Your 3.3 interview

The Heroic lockouts still exist, however the difference is that the random heroic option will ignore any potential lockouts a player might have. This means that even if you run every single WotLK heroic dungeon in a day, you can still choose the random heroic option to continue running WotLK heroics that day. As mentioned above though, the heroic dungeons you have run the most that day will be the least likely to be randomly selected for your continued play by the dungeon finder system.

**Comment by Valaya** [comment]
There's no limit in how many times per day you can do a HC, if you get it via Random Dungeon 5 times, you can do it 5 times, the current problem is that system locks you up from queuein if you've done all heroics via Random Dungeon tool, that's the main reason of the report, because you're stuck doing nothing if you're a new player trying to gear up from RHC drops, which I think is kinda important to fix.

> As mentioned above though, the heroic dungeons you have run the most that day will be the least likely to be randomly selected for your continued play by the dungeon finder system.

Yes, least likely, but not impossible.

**Comment by Aival94** [comment]
"There's no limit in how many times per day you can do a HC, if you get it via Random Dungeon 5 times, you can do it 5 times"

" Each dungeon is on an independent timer, however, so a character could run as many as 15 heroic mode instances per day"

source: http://wow.gamepedia.com/Heroic 

If it was implemented later sorry but cannot find it in patches.

Gearing up via heroics was difficult even in blizzard during cata.

**Comment by Thefakemccoy** [comment]
one prob with gamepedia is seeing when it was last updated
http://wow.gamepedia.com/Heroic
This page was last modified on 6 July 2014, at 06:27.

**Comment by Valaya** [comment]
> "There's no limit in how many times per day you can do a HC, if you get it via Random Dungeon 5 times, you can do it 5 times"
> 
> " Each dungeon is on an independent timer, however, so a character could run as many as 15 heroic mode instances per day"

What I meant, there's no arbitrary limit set by the code/developer.

> Gearing up via heroics was difficult even in blizzard during cata.

That was mostly because of the dungeon's own difficulty, has nothing to do with any of this.

> If it was implemented later sorry but cannot find it in patches.

I presume you're thinking about the 15 per day limit ?

> one prob with gamepedia is seeing when it was last updated
> http://wow.gamepedia.com/Heroic
> This page was last modified on 6 July 2014, at 06:27.

http://s859.photobucket.com/user/Nyeriah/media/Capture_zpsbltpuydk.jpg.html
http://web.archive.org/web/20101029010507/http://www.wowpedia.org/Instance_limitations

Anyways, I think there's more that 'nuff proof that this was active during Wrath (post 3.3 patch).

**Comment by Thefakemccoy** [comment]
i dont understand why it would happen in 3.3 and again in 4.3

**Comment by Varchord** [comment]
You guys know that your whole disussion is double issue ?
https://github.com/Atlantiss/BugTracker/issues/696

>Players who use Dungeon Finder for a random Heroic dungeon will no longer be locked to that instance. Previously, players who entered an instance via the Random Dungeon option were then prohibited from queuing for that dungeon or entering the instance manually via the portal. Players should now always be able to complete a specific Heroic dungeon once per day regardless of any random dungeons completed.


If i remember correctly Wolff once attempted to fix this. That's when ID problems have started occuring. AFAIK he hasn't touched it since

**Comment by Thefakemccoy** [comment]
You should direct that more to Valya i cant close some one else's bug tracker.

**Comment by Thefakemccoy** [comment]
the problem that lies with multiple tickets is if you search for what you want and dont find a result most people open another. You have one labeled Dungeon Finder. If he didnt search dungeon finder he would never know

**Comment by Aival94** [comment]
i know about the other one but i think that this one is more specific of how ids should work and the other is more about bugged things in the already rdf mechanics implemented in the server so i think it can be a separate report.

**Comment by Varchord** [comment]
This is dungeon finder issue. It is reported for 6 months. 
What are you doing and thinking is againt the rules

>Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.

If that was the case we would have doubling reports every 2 months because people would think that "they are old" and problem needs to be reminded to the devs

**Comment by Valaya** [comment]
closing it then
