### ISSUE TITLE
[EN] [Web] Talent Calculator

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3395]
So i try to use the the talent calculator on the website the only issue i have is if i scroll over a talent i dont get a tool-tip to tell me what that talent is.

I have set my pop-up blocker to allow the domain so that is not the issue.

I am aware i cant just google one and get it. I just dont know if it bugged on their website.

**Comment by Varchord** [comment]
There are so many talent calc reports :X I think they should be unified

**Comment by Aival94** [comment]
i think that some of the bugs reported are already fixed.
This is all the bug reports i find searching "talent calculator":

#2679
#1873
#1736
#855
