### ISSUE TITLE
[EN][ROGUE][TALENT] Venomous Wounds

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3396]
#3259 here there is a more detailed topic but is in pl so i can't understand it.
http://cata.openwow.com/spell=79134
the problem is the amount of nature dmg it does is very low, now i don't remember exactly the tooltip 
at lvl 66 because i dinged meanwhile i was writing the report, but was around 630 dmg per tick and it did only 247 dmg per tick. i think in the long run vs a boss is a big dps loss.
here a screenshot of the dmg when i was questing on variuos mobs:
![vw](https://cloud.githubusercontent.com/assets/8077498/7858476/a5938eaa-0538-11e5-96db-f0bce2ac34ab.jpg)

**Comment by Jenovas** [comment]
The DMG is ok. You say that the DMG is to low, the issue you linked shows that it's to high...
Closing.

**Comment by Dean1989** [comment]
well as i said i can't understand polish, i will edit my post removing the linked issue.
