### ISSUE TITLE
[EN][Quest][Northern Barrens] Into The Raptor's Den

### ISSUE THREAD

**Issue by anijatsu** [Atlantiss/BugTracker#3398]
It's possible to place the feathers received from the raptors in only a single den. Others consume the feather, but it doesn't count for the quest for some reason.

http://www.wowhead.com/quest=905/into-the-raptors-den

**Comment by Angelo-DM-** [comment]
The quest works 100% Blizzlike to me. 3 nests, 3 feathers, a lot of raptors to kill :laughing:
