### ISSUE TITLE
[EN][Druid] Owlkin Frenzy gets removed upon shapeshifting

### ISSUE THREAD

**Issue by Liebeqt** [Atlantiss/BugTracker#3401]
Issue: A druid balance talent "Owlkin Frenzy" gets removed when the druid shits out of Moonkin Form.

Proper functioning: Owlkin Frenzy can proc only when in Moonkin Form, but remains active when shapeshifting to any other form.

Wowpedia link, since the spell no longer exists on Wowhead (and retail): http://wow.gamepedia.com/Owlkin_Frenzy

PROOF: https://youtu.be/dJPzlxhR1T4?t=1m50s
At 1:55 he leaves Moonkin Form, yet the Owlkin Frenzy buff (black moonkin on orange background) stays on.

**Comment by Isuel** [comment]
confirmed. )
took you a while to report it

**Comment by Liebeqt** [comment]
You said you will ).

**Comment by Jenovas** [comment]
Fixed in rev 4631
