### ISSUE TITLE
[EN] [Quest] [The Storm Peaks] The Warm-Up

### ISSUE THREAD

**Issue by Yukitara** [Atlantiss/BugTracker#3406]
When I try to do this quest, The Warm-Up:
http://www.wowhead.com/quest=12996/the-warm-up#comments

The yeti you have to kill, Kirgaraak (http://www.wowhead.com/npc=29352/kirgaraak) doesn't seem to be hostile or even neutral while on the bear or not, thus being unable to kill it.

I've tried to use "/removeaura Lok'lira's Bargain" (http://www.wowhead.com/spell=72914/lokliras-bargain#comments) to remove my disguise, hoping that would make him killable, but it didn't work.

Any help would be very appreciated.

**Comment by Dean1989** [comment]
adjust the title of your report pls.
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Yukitara** [comment]
Should be correct now :)

**Comment by SwimzwithSharkz** [comment]
Plz Help my Toon Gankerz to complete thiz quest also.
I cannot target nor kill Kirgaraak.

TY

**Comment by SwimzwithSharkz** [comment]
Good Newz, I can kill him.
Bad Newz, doesn't count.

![sigh](https://cloud.githubusercontent.com/assets/12092984/8193037/3ffbfdfe-1440-11e5-8ec5-f6b7edf49a96.png)

**Comment by Bildo** [comment]
Good Newz, I can fix it.
Good Newz, Should be fixed very soon.

**Comment by SwimzwithSharkz** [comment]
[bildo ty](https://cloud.githubusercontent.com/assets/12092984/8193225/9b43c83a-1441-11e5-82cd-37260eb2eb73.jpg)

**Comment by SwimzwithSharkz** [comment]
;D
![bildo ty](https://cloud.githubusercontent.com/assets/12092984/8193258/c84d2a92-1441-11e5-8d9e-b7cc8dbd0c14.jpg)

**Comment by Bildo** [comment]
http://i868.photobucket.com/albums/ab242/cortnyann1/400x400px-LL-e95604cb_Happy-oh-stop-it-you-l_zpsb767b493.png

**Comment by gainey666** [comment]
after some one dose this quest it breaks apparently mob still @ 1450 of 37k hp and   just chill en has been all day one of the only time i am hopping for crash / restart

**Comment by Bildo** [comment]
Today this should be fixed

**Comment by Bildo** [comment]
fixed

**Comment by AnubisMRM** [comment]
The last two day I kept checking to see if Kirgaraak respawned, but he's not there. I'm not sure if he is phased out or dead. I saw him twice, bu only for a fraction of a second before he disapeared again. Maybe you need to be in a precise location in order to see him. After 15 minutes I gave up.
But I would really like to complete this quest so I can finish the chain which unlocks the Sons of Hodir.

**Comment by AnubisMRM** [comment]
I managed to complete the quest a few days later. Kirgaraak was where he was supposed to be. There was probably a server crash and I was lucky that nobody killed him.
