### ISSUE TITLE
[EN][Quest][Borean Tundra] The Lost Spirits

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3408]
http://www.wowhead.com/quest=11607/the-lost-spirits
using the quest item on the spirits don't give the credit

video: https://www.youtube.com/watch?v=XllO4O3f0i8

**Comment by Hansrutger** [comment]
Confirmed to not work. :/

**Comment by Aruzam** [comment]
Confirmed today as well, just tried it. All the NPCs are green (usually were yellow as I recall) and using the item on them doesn't do anything.

**Comment by BAndysc** [comment]
Fixed in rev. 4465
