### ISSUE TITLE
[EN][NPC][Gilneas City] Bloodfang Stalker

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#3410]
1. [Bloodfang Stalkers](http://www.wowhead.com/npc=35229/bloodfang-stalker) spam CHAT_MSG_MONSTER_EMOTE messages "error", [pic](http://i.imgur.com/d2POJW1.jpg).

2. Quest [Slowing the Inevitable](http://www.wowhead.com/quest=24920/slowing-the-inevitable): You can blow yourself up with your own bombs when you accidentally put the targeting circle on a tree or other object near the path you're flying. I've never seen this with bombing missions in WoW, so I'm pretty sure that the bombs are supposed to hit only enemies, but not also yourself. ([targeting circle](http://i.imgur.com/h8otGNr.jpg), [death 1](http://i.imgur.com/S3u7H9f.jpg), [death 2](http://i.imgur.com/d4FNvM5.jpg))

3. Quest [Knee-Deep](http://www.wowhead.com/quest=24678/knee-deep): The Rats in the tunnel should attack [video](https://www.youtube.com/watch?v=OldY7IkaWdk), however despite being red (aggressive) they don't attack you on their own ([pic](http://i.imgur.com/n89GVKY.jpg)), which means that you don't really need to use the quest item on them, you can just walk through them.

4. Quest "Liberation Day": see #3459, many chains are too far away from the prisoners.

5. Quest [The Battle for Gilneas City](http://www.wowhead.com/quest=24904/the-battle-for-gilneas-city) ([video](https://www.youtube.com/watch?v=LGgiU0-8Wfg)) is set to auto complete (not surprising, it looks extremely hard to script).

6. Quest [Endgame](http://www.wowhead.com/quest=26706/endgame) ([video](https://www.youtube.com/watch?v=d3E_Tv8mBXA)) is set to auto complete (also not too surprising), #1567

7. Quest [Introductions are in Order](http://www.wowhead.com/quest=24472/introductions-are-in-order): The event after the quest is not scripted, see #2790

8. There are some copper veins in Gilneas City which should be deleted, see #2535

**Comment by Bildo** [comment]
Hi, can you make one big report with Gilneas bug ? I think would be easier for us.

**Comment by Tj20** [comment]
Yes, if I should have more small bugs like this one and the Gilneas City zone border I shall make one big report for them.

At the moment however it's just these two, and the thing with the WoW crashes and that got pretty long already and I think warrants its own report.
If I find more small things, I'll collect them in one post.

**Comment by Tj20** [comment]
As requested I've made one big report about the Gilneas bugs, but I can't change the title. 

Well, I think I'll just close this and make a new bug report then.
