### ISSUE TITLE
[EN][CORE][Transfer]

### ISSUE THREAD

**Issue by Magohoy** [Atlantiss/BugTracker#3411]
After transfering my horde goblin mage to an alliance human mage, I still have the Pack Hobgoblin racial from goblins in my spellbook, it is also usable.

Edit: The same character allso has the spell "Blessing of Auchindoun" up 100%, and I cannot manually remove it

**Comment by relek** [comment]
Write a ticket in-game

**Comment by Magohoy** [comment]
Done, got told to write up a bugtracker post instead.

**Comment by Thefakemccoy** [comment]
It might help if you link the racial's aswell

**Comment by Thefakemccoy** [comment]
Might want to link the racials as well
