### ISSUE TITLE
[EN] [Dungeon] One or more dungeons was not valid

### ISSUE THREAD

**Issue by CommanderKrazy** [Atlantiss/BugTracker#3412]
Anytime i click find group in dungeon finder it says in chat "one or more dungeons was not valid." Any info would be appreciated.

**Comment by Thefakemccoy** [comment]
What char level? What item lvl

**Comment by CommanderKrazy** [comment]
my character level is 19 and my item level is 8/8

**Comment by Thefakemccoy** [comment]
did you check under specific dungeon see if any was locked?

**Comment by Thefakemccoy** [comment]
Also since you are 19 and idk if this is aval on atlantiss. At one point blizz allowed you to turn off xp for twinks. Idk if thats something you done that could conflict it.

**Comment by CommanderKrazy** [comment]
None are locked I have 4 dungeons deadmines (15-21), Ragefire Chasm (15-21), Wailing Caverns (15-25) and shadowfang keep (16-26) and my xp is not locked.

**Comment by CommanderKrazy** [comment]
I did the ragefire dungeon and then got off for about 30 minutes then came back on to this issue.

**Comment by Thefakemccoy** [comment]
idk then did you try restarting your client?

**Comment by CommanderKrazy** [comment]
i'll try

**Comment by CommanderKrazy** [comment]
Nope still wont let me join a dungeon

**Comment by Thefakemccoy** [comment]
IDK what to tell you then. Wait for a dev to reply here or open a ticket to talk to a GM

**Comment by CommanderKrazy** [comment]
K, thx

**Comment by Thefakemccoy** [comment]
It might help take a screen shot of ur RDF open with you clicking where they can see the chat window as well. The take another screen shot of the Specific tab showing you are not locked to anything

**Comment by CommanderKrazy** [comment]
OK

**Comment by Aival94** [comment]
have you done a dungeon before the issue start?If yes ask someone to invite you to group and then leave group and try again to queue.

**Comment by CommanderKrazy** [comment]
ya it worked thx
