### ISSUE TITLE
[EN][Quest][Sholazar Basin] Still At It

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3413]
http://www.wowhead.com/quest=12644/still-at-it
i did all the steps correctly but at some point the npc http://www.wowhead.com/npc=28566/tipsy-mcmanus stop talking and you can't get the quest item from the barrel and complete the quest.

**Comment by Thefakemccoy** [comment]
I had the same issue i abandoned it picked it back up did it all over. But i waited a sec after he stopped talking before i opnened the barrel.

**Comment by Dean1989** [comment]
i didin't understand if you was able to complete the quest or not

**Comment by Thefakemccoy** [comment]
Yes i was able to

**Comment by Dean1989** [comment]
tried 7 times but nothing, the quest need a tune-up

**Comment by Aival94** [comment]
The problem in this quest is that there are already spawned some empty [Thunderbrew's Jungle Punch](http://www.wowhead.com/object=190643/thunderbrews-jungle-punch) which are empty.After you complete the steps the quest if you click on the right one(which is probably spawned) it will have the item you need to complete quest.

**Comment by Blackaddder** [comment]
The ONLY problem is that the barrel doesn't despawn after picking loot. Also the fruits should be thrown from the buckets to machine, not from player to buckets.

**Comment by DuGalle** [comment]
barrel is empty non working confirm

**Comment by Cellhawk** [comment]
So, only thing we need is to someone put a "timed despawn" on [Thunderbrew's Jungle Punch](http://www.wowhead.com/object=190643/thunderbrews-jungle-punch) and it can be done easily.

**Comment by buzzstpoint** [comment]
Doesn't work for me...

**Comment by Silverdevilboy** [comment]
Quest works, but there are empty barrels stacked up. Keep clicking the barrels (you only need to make the punch once) and eventually you find the one with the item. Took half a dozen barrels for me.

**Comment by Samineh** [comment]
Spam clicking didn't work for me, will wait for a restart to see if it works then.

**Comment by Samineh** [comment]
So checked it after the restart and it works for the first person for sure the barrel just won't disappear. If you want to do the quest badly you can wait for a crash or restart.

**Comment by Piklo** [comment]
#9413 is written with issue_template, so i will close this post
