### ISSUE TITLE
[PL] [NPC] [drop] Noxoius whelp

### ISSUE THREAD

**Issue by Seavitia** [Atlantiss/BugTracker#3415]
Z tego moba powinna być szansa na wydropienie dwóch companionow. 
Emerald Whelpling - szansa 0,91% (Info z wowhead)
Sprite Darter Egg  - szansa 0,01% (info z wowhead)

Głównie chodzi mi o szansę na wydropienie emerald whelpling - od jakiegoś czasu probuje go wydropic. Wiem, że szzansa jest ekstremalnie mała i, że oczywiście może to być kwestia zwykłego pecha z mojej strony - jednak ubiłam już 4218 (licznik z addona mob info) smoczkow i nic. Dla porownania wpadło mi już 275 zielonych itemkow i 19 niebieskich - z ktorych większość ma szansę na dropa w wysokości 0,01%. Dla przykładu Kaleidoscope Chain - 0,01% (wowhead) wpadł już 4 razy.

Stąd prośba o sprawdzenie prawidłowości szansy na dropa companionow i w miare mozliwosci poinformowanie czy rzeczywiscie było coś nie tak, czy też mam totanlnego pecha.

**Comment by Quban** [comment]
Use links next time pls:
<a href="http://www.wowhead.com/item=8498/emerald-whelpling">Emerald Whelpling</a>
<a href="http://www.wowhead.com/item=11474/sprite-darter-egg">Sprite Darter Egg</a>

**Comment by Drutmaster** [comment]
Masz totalnego pecha, peta wydropiłem wielokrotnie, czasem po jednym runie, czasie po kilkugodzinnych runach. Kwestia farta lub jego braku, niestety. Sprite też dropi, chociaż mi się to zdarzyło chyba tylko raz (jeśli idzie o drop z tego moba oczywiście)

**Comment by Quban** [comment]
Emerald Whelping ma trochę zaniżony drop, fix soon :)
