### ISSUE TITLE
[en][spell][mage] Ring of Frost and Line of sight

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3416]
Ring of frost is not working behind the LoS of mage. before the fixes for controling the mage to prevent RoF it was working now its not.
crucial bug.

**Comment by MasterK15** [comment]
Yeah Ring of frost is crapy right now, its good only for pilling your healer. You need to fix it fast :+1:

**Comment by Jenovas** [comment]
Fixed in rev 4553
