### ISSUE TITLE
Blackwing Descent (BWD) Maloriak HC 10m

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#3417]
The boss is not suppose to spawn so many black AoEs on the ground  [Dark Sludge]. It spawns almost the whole room, there should not be that many.

**Comment by Wojowniczka** [comment]
proofs (idk videos and sites with explanation etc.) + links (to which You refer) + AOE black plams is made not by boss but by Dark Sludge

**Comment by meowmewo** [comment]
http://www.icy-veins.com/wow/maloriak-strategy-guide-normal-heroic

Scroll down. He spawns 5. On heroic and normal its the same number but heroic has more HP + more damage. If its the same number on Atlantiss. then its correct.

**Comment by jangsna** [comment]
No, this fight should not have that many balck aoe. And I know it's not
from the boss I and I'm talking about the dark sludge. Why wouldn't you
guys understand if it is not scripting properly?
On May 30, 2015 1:04 PM, "meowmewo" <notifications@github.com> wrote:
>
> http://www.icy-veins.com/wow/maloriak-strategy-guide-normal-heroic
>
> Scroll down. He spawns 5. On heroic and normal its the same number but
heroic has more HP + more damage. If its the same number on Atlantiss. then
its correct.

**Comment by Bildo** [comment]
https://www.youtube.com/watch?v=zbBahhCGkIs - Atlantiss
https://www.youtube.com/watch?v=G2atEUGr9FA - Retail
I can't see difference between atlantiss and retail.

**Comment by mitim1** [comment]
Same problem with Cho`gall HC (idk about norm) Blaze, but only with the first Blazes after encounter start.
Problem didn't exist before rev .4454


http://www.wowhead.com/spell=158241/blaze

**Comment by Frainzil** [comment]
watching both video's i also don't really see any difference in the amount of puddles spawning. It's just rng, and if people are stacked together, ofc many black puddles will spawn on the same spots. that black phase is all about position and is easily done if people move fast and if people do not stack on eachother.
