### ISSUE TITLE
[EN] [Quest] [Nagrand] HELP!

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3419]
http://www.wowhead.com/quest=9923/help

"Find the Boulderfist Key and Free Corki. Speak with Arechron in Telaar should you succeed. "

I am friendly with Kurenai but Corky does not offer me this quest.

**Comment by Aival94** [comment]
For now try to go to this  [Corki](http://www.wowhead.com/npc=18445/corki) as the bug might be that the one Corki you went is the wrong id one [Corki](http://www.wowhead.com/npc=18369/corki)

**Comment by Dean1989** [comment]
#1891
