### ISSUE TITLE
[en][battleground][rated battleground] Same faction rated BG

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3421]
after the play today we discovered some things: ( when playing horde vs horde)
- horde players labeled as alliance couldnt use pvp trinkets
- horde players labelled as alliance when capped flag the flag visually didn't count ( but it did afterall)
- after the win horde players labelled as alliance were granted:
*alliance rated bg win achievment
* strange achievments completly unrelated with this - for example brewmaster
* some achivments they already completed years ago - for example arathi basin master
also we couldn't use alot of spells ( like leap of faith etc).
after all, rated bg same faction works but its a long way from normal play.

**Comment by Kejmil** [comment]
"horde players labelled as alliance when capped flag the flag visually didn't count ( but it did afterall)"

after alt+f4 i saw everything as normal (horde side)

**Comment by Jenovas** [comment]
Thank you for the tests and for the report.
Will try to fix this soon.

**Comment by debtheone** [comment]
horde players labeled as horde couldnt use such spells as  leap of faith prayer of mending kinda sure same thing with 'alliance' players

**Comment by debtheone** [comment]
any progress?

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
Tested on ptr it works fine. Jenova is it already implemented on main?

**Comment by Jenovas** [comment]
Rated BG does work, but same faction BG doesnt work properly
