### ISSUE TITLE
[en][talent][rogue] Cheat Death

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3423]
http://wowwiki.wikia.com/Cheat_Death_%28rogue_talent%29
talent works but not exactly as it should.
if the rogue have more than 10% hp and some1 would deal a fatal blow to them it triggers -working as intended
but 
if the rogue is on lower hp ( for example 4%) and some1 is doing fatal dmg to them the cheat death is not increasing their hp value to 10%

**Comment by Jenovas** [comment]
It shouldnt increase your helath.
If the Rogue is below 10% health, the killing blow is still completely absorbed; if the Rogue is over 10% health, enough damage will be absorbed to reduce the Rogue’s health down to 10%.
