### ISSUE TITLE
[EN][Spell][Shaman] Stormstrike with Glyph of Stormstrike

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#3424]
I want to report an bug on that skill http://cata.openwow.com/spell=32175, stormstrike, but not sure if it's an visual bug or skill bug. The glyph is http://cata.openwow.com/item=41539.
The skill with Glyph of Stormstrike should have 35% chance of critic but still have 25%, and there i dont know if glyph dont work or it work and debuff just show 25%.
http://i.imgur.com/ohqObvs.jpg

**Comment by aneq** [comment]
@Aviannaqt 
do zamknięcia
