### ISSUE TITLE
[EN][NPC][Teldrassil] Denalan

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3426]
http://www.wowhead.com/npc=2080/denalan

he should be appeared on 2 different place, but sometimes i saw 2 copy of him which was colliding on the lake, and i never see him on the hovel

thanks

**Comment by aje** [comment]
the 2 are present

**Comment by MirrorWraith** [comment]
It WAS Colliding

**Comment by aje** [comment]
so is there a bug or not ?

**Comment by MirrorWraith** [comment]
i think so, there were many of them but in 2 places, they're colliding
for example there's 4 denalan in 1 place, it looked like 1 though
thanks

**Comment by aje** [comment]
this morning, there was no problem and only one NPC at each location

**Comment by MirrorWraith** [comment]
if that so, there's no problem anymore
that's last time i played in teldrassil
ok, sorry for your inconvenient

**Comment by TranceAccount** [comment]
1 is missing @ 2nd spot
