### ISSUE TITLE
[EN][Quest][Darkshore]Eye of All Storms

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3429]
http://www.wowhead.com/quest=13588

it should be looked like this 
https://www.youtube.com/watch?v=R8xveRFTwU8

the twilight dragons we had to kill was bugged, all of them were not flying, they're landing instead so i couldn't attack them, i got only one kill because sometimes there're 1 dragon which was flying, 
i couldn't find the portal too..

thanks, i hope this will be fixed soon

**Comment by Aival94** [comment]
Reported: #2028

**Comment by Quban** [comment]
Pls check first for existing bug reports before you post

**Comment by MirrorWraith** [comment]
ok, sorry about that
