### ISSUE TITLE
Drakehide Leg Reinforcements

### ISSUE THREAD

**Issue by danih92** [Atlantiss/BugTracker#3433]
It is supposed to be trained by a LW trainer but they don't train it, none of them do.

My character which is mainly tank needs this bug to be fixed.

**Comment by LaveGit** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Thefakemccoy** [comment]
http://www.wowhead.com/item=71720/drakehide-leg-armor#taught-by-item

is a pattern you buy from a vendor

**Comment by Thefakemccoy** [comment]
![wowscrnshot_053115_121106](https://cloud.githubusercontent.com/assets/12252441/7902657/2373c112-078e-11e5-86db-639684a62bbe.jpg)

**Comment by Aival94** [comment]
the problem here that they added them in patch 4.2 so you might need to wait.

**Comment by Thefakemccoy** [comment]
if he is looking for the lvl 85 leg enchants for tanking they are in game now.

**Comment by Invaerne** [comment]
I think he's writing about the leatherworkers only reinforcement, not the leg armor for everyone
http://wow.gamepedia.com/Drakehide_Leg_Reinforcements. It's true, you can buy Drakehide Leg ARMOR recipe, but there is no Drakehide Leg REINFORCEMENT skill on our server.

**Comment by Thefakemccoy** [comment]
Oh i see been along time since i messed with a LW.

he can just make the one any one can use same stats. Its not like that pattern cant be gotten. So its not hurting him as a tank. 

Yes the LW one might be cheaper and easier to make but if he is a LW it wont take him long to make it.
