### ISSUE TITLE
[EN][Core][Mage] Water Elemental Pathing when auto attacking in arena

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#3434]
In arenas when I send my water elemental to attack he will sometimes go to the other end of the map and go back again sometimes and sometimes he just gets stuck there. Happens when I use /petattack and have waterbolt on auto.

**Comment by blinkmaster** [comment]
its due to move maps which are... well.. just plain bad for pets. on some arenas pet is like a shadow, you have it but it does nothing ;d

**Comment by MasterK15** [comment]
Its problem with Mage Roots, your pet trying to do not breake roots so he try "move away" while casting Water Bolt. Its bug ofc. 
Here is problem with Ruins of Lor... arena pets cant enter green water. and warrior cant charge into this watter or charge away from water
