### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] Picking Up Some Power Converters

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3436]
http://www.wowhead.com/quest=10584/picking-up-some-power-converters

"Use the Protovoltaic Magneto Collector to collect 5 Electromentals."

Toshley does not offer me this quest. So far I have completed 4 out of 14 quests at Toshley station. This should be one of the first quests offered when you arrive at Toshley station. This quest is part 1 of a 4 part quest chain. I can not do any other quests at Toshley station until I complete this quest.

**Comment by lourrific** [comment]
Disregard above. I found the correct quest progression to obtain this quest.
[66] The Trappings of a Vindicator
[67] Gorr'Dim, Your Time Has Come...
[67G3] Planting the Banner
[67] Where Did Those Darn Gnomes Go?
[67] Follow the Breadcrumbs
then
[67] Picking Up Some Power Converters

**Comment by aendry** [comment]
this is fixed, I did this ques 5 minutes ago
