### ISSUE TITLE
Westfall -"Secrets of the Tower"  quest doesn't work

### ISSUE THREAD

**Issue by Beponator** [Atlantiss/BugTracker#3437]
http://www.wowhead.com/quest=26290/secrets-of-the-tower

shrouding potion is working but when i get to the top nothing happend.

**Comment by BAndysc** [comment]
Update title of issue according to [those rules](https://github.com/Atlantiss/BugTracker)

**Comment by Thefakemccoy** [comment]
there are now 3 post about this quest

**Comment by Thefakemccoy** [comment]
I dont see how it got broke in 2 days cause i just did it 2 days ago

**Comment by Aival94** [comment]
Reported: #2338
