### ISSUE TITLE
[PL][Quest][Ashenvale] Playing With Felfire

### ISSUE THREAD

**Issue by neshugo** [Atlantiss/BugTracker#3438]
http://www.wowhead.com/quest=13730/playing-with-felfire
Ognie nie znikają po użyciu na nich quest itema oraz nie ma animacji.

**Comment by BAndysc** [comment]
Na flimiku z retaila nie widzę żadnej animacji: https://www.youtube.com/watch?t=147&v=j7jProoGLUQ

**Comment by neshugo** [comment]
Może źle to nazwałem, chodzi o taki zielony promień, którego tutaj brak albo u mnie tego nie widać. W sumie to jest kosmetyka, a quest da się wykonać.

**Comment by anijatsu** [comment]
+1
