### ISSUE TITLE
[PL][Spell][Mage] Invisibility

### ISSUE THREAD

**Issue by hubert01** [Atlantiss/BugTracker#3440]
http://www.wowhead.com/spell=66/invisibility powinien dać się włączyć przed rozpoczęciem areny i działać razem ze startem areny, teraz jest tak, że jeśli wejdziemy w invisibility przed startem areny to automatycznie wyrzuca nas jak arena wystartuje.

**Comment by Wojowniczka** [comment]
a wiesz że gdy wejdziesz na arene to wszystkie BUFFY zostają "zdispelowane" (zdjęte)??

**Comment by blinkmaster** [comment]
nie wszystkie. tylko te ktorych czas trwania jest krotszy niz 20 sek.

**Comment by MasterK15** [comment]
Z tego co wiem Invi nie jest zdejmowane i działa poprawnie, musisz odpalic je 3-4 sec przed startem aby dostać długi buff od invi a nie ten 2-3 sec czas oczekiwania na wejście w invi, chyba ze cos sie zmienilo od ostatniego tygodnia, nie gram magiem aren od czasu zepsucia RoF z losem

**Comment by hubert01** [comment]
Ja też nie grałem już z 3 tygodnie aren, ale jeśli grałem to właśnie nie dało się wyjść w invi na arene przy starcie, chyba, że teraz na dniach wprowadzili poprawke.

**Comment by blinkmaster** [comment]
working fine, can be closed
@Aviannaqt

**Comment by aneq** [comment]
@Aviannaqt open it again
Invisibilty currently allows mages to exit combat during pve encounters, which should never happen

**Comment by blinkmaster** [comment]
https://github.com/Atlantiss/BugTracker/issues/2623
co mie tu spam robisz Anku! to inny bug, ten tu jest fixed ( bo nigdy nie byl zbugowany)
