### ISSUE TITLE
[EN][NPC][Sholazar Basin] Frenzyheart Ravager/Hunter

### ISSUE THREAD

**Issue by Tokojiro** [Atlantiss/BugTracker#3442]
This is a big anoying bug: before I have entered any dungeon I could kill them, but after entering a dungeon via the Dungeon Finder they ALL became untargetable by single target spells/abilitties, only by AoE spells.Here's the proof:
![wowscrnshot_060115_182534](https://cloud.githubusercontent.com/assets/11329640/7916337/dce45186-088b-11e5-951e-484e45faf092.jpg)
![wowscrnshot_060115_181432](https://cloud.githubusercontent.com/assets/11329640/7916145/a415d556-088a-11e5-8326-d8dd9991d303.jpg)
![wowscrnshot_060115_181439](https://cloud.githubusercontent.com/assets/11329640/7916148/ab0de57e-088a-11e5-8d69-e3d5a088dfdd.jpg)
![wowscrnshot_060115_182032](https://cloud.githubusercontent.com/assets/11329640/7916221/35ddfad6-088b-11e5-8245-b34ff07ec5de.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/978
