### ISSUE TITLE
[EN][Quest][Westfall] Secrets of the Tower

### ISSUE THREAD

**Issue by Beponator** [Atlantiss/BugTracker#3443]
http://www.wowhead.com/quest=26290/secrets-of-the-tower

Shrouding potion  works properly but when i get to the top nothing happens.

**Comment by Aival94** [comment]
Reported: #2338

**Comment by Tegis** [comment]
I was able to complete.  had to break aggro from all mobs and use the potion from the inventory at the top of the tower.
