### ISSUE TITLE
[EN][Quest][Northrend - Dragonblight] Fresh Remounts

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#3444]
I report this quest [http://www.wowhead.com/quest=12214/fresh-remounts] as being bugged. It is incompletable, u should kill knights [http://www.wowhead.com/npc=27206/onslaught-knight] and to drop an itemquest [http://www.wowhead.com/item=37202/onslaught-riding-crop] and with that player should ride horses [http://www.wowhead.com/npc=27213/onslaught-warhorse], but horses cant be ride, because are enemy if u kill knight, with or without itemquest.

**Comment by aje** [comment]
this quest works:
kill http://www.wowhead.com/npc=27206/onslaught-knight
take the http://www.wowhead.com/item=37202/onslaught-riding-crop
use it on http://www.wowhead.com/npc=27213/onslaught-warhorse
go back to the giver of the quest and use the deliver spell

**Comment by rwystop** [comment]
no it isnt work, you surelly can controll the horse, but the horse has 1% speed, and if someone attack you, the horse is still teleported to the attacker -,-
YOU CALL QUEST LIKE THIS WORKING ?!!?!?!
