### ISSUE TITLE
[EN][Quest][Northrend - Sholazar Basin] Still At It

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#3445]
I wanna report this quest [http://www.wowhead.com/quest=12644/still-at-it] as being bugged.
In his sequence of droping the fruits, it end with no complete the quest. Sequence can start repetatly from that npc [http://www.wowhead.com/npc=28566/tipsy-mcmanus] but even if u do correct sequence or click any another fruit, it end same with no complete quest.

**Comment by Dean1989** [comment]
#3413
