### ISSUE TITLE
[EN][Quest][Eversong Woods] Unstable Mana Crystals

### ISSUE THREAD

**Issue by shrek15001** [Atlantiss/BugTracker#3447]
New to this server but if i do remember correctly i should be able to click on the crate but how ever its not

http://www.wowhead.com/quest=8463/unstable-mana-crystals

**Comment by Bildo** [comment]
You sure ? i just checked and i can loot cretes without any problem

**Comment by Tegis** [comment]
same issue, mana crates are unclickable.

**Comment by Anhaeyn** [comment]
Yeah, I couldn't click them too, but this quest is doable. You have to kill Wretched Urchins and Arcane Patrollers, there's a small chance that they drop these crystals. I was doing this quest about 2 days ago.

**Comment by MirrorWraith** [comment]
i tried this quest for the second time (yesterday) and it's bugged (unable to click the target) however, the first time I played, this quest was bugged but still be able to click the target...

**Comment by Wolffenstein** [comment]
Fixed in rev 4555.
