### ISSUE TITLE
[EN][Quest][Ashenvale]A Trip to the Moonwell

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3449]
http://www.wowhead.com/quest=13919/a-trip-to-the-moonwell

a minor problem, the quest just didn't have any explanation on the player's tracked quest
thanks

**Comment by Wolffenstein** [comment]
Can you upload a screenshot of what is supposed to be the problem?

**Comment by xolon** [comment]
i think he meant the quest text  below minimap is missing, it shows just  quest name

**Comment by MirrorWraith** [comment]
yeah tx for explaining him xolon, he's right Wolffenstein, sorry i cant take the screenshot, i haven't played it for days

**Comment by Quban** [comment]
Pewnie chodzi o to http://scr.hu/75h5/rz787

**Comment by BAndysc** [comment]
I have just checked it and everything seems fine
