### ISSUE TITLE
[PL][Quest][Icecrown]Ornolf The Scarred

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#3450]
http://www.wowhead.com/quest=14104/ornolf-the-scarred

Potwór nie pojawia się po użyciu quest itemu.

**Comment by Bildo** [comment]
działa

**Comment by Haz3L** [comment]
Nie kurwa, nie działa.

**Comment by Bildo** [comment]
TA TA TA DAAAAAAAM
![wowscrnshot_060315_130811](https://cloud.githubusercontent.com/assets/3138020/7958667/ab3cb328-09f1-11e5-993c-26f1239966b7.jpg)
