### ISSUE TITLE
[PL][Quest][Icecrown]Deathspeaker Kharos

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#3451]
http://www.wowhead.com/quest=14105/deathspeaker-kharos

Nie ma potwora potrzebnego do wykonania questu.

**Comment by Bildo** [comment]
działa

**Comment by Haz3L** [comment]
Nie działa.

**Comment by Bildo** [comment]
![wowscrnshot_060315_130811](https://cloud.githubusercontent.com/assets/3138020/7958684/d96d7976-09f1-11e5-809d-ea9b1480c726.jpg)
