### ISSUE TITLE
[PL][Quest][Icecrown]Drottinn Hrothgar

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#3452]
http://www.wowhead.com/quest=14101/drottinn-hrothgar

Potwór nie pojawia się po użyciu quest itemu.

**Comment by Bildo** [comment]
działa

**Comment by Haz3L** [comment]
Nie, nie działa.

**Comment by Bildo** [comment]
zrobilem przed chwila wiec dziala
