### ISSUE TITLE
[EN] [DUGEON] Warpwood Quarter

### ISSUE THREAD

**Issue by darkiepie** [Atlantiss/BugTracker#3455]
Did an RDF and we came across Warpwood quarter dugeon, the damage on the mobs are too high, tanks dont reach 3k hp, normal non elite mobs do 250+ normal damage and alot of crits hitting for almost 800 damage, now maybe doing 1 would be fine but in that dugeon its groups of 3 to 8, elites are even worse if seemed, not fully tested since tank would die in 2 shots my normal mobs.

Summary:
-Tank hp pool 3000 hp , Groups of normal mobs 8 - do 250 dmg to 800 crits per mob
-either we somehow entered in Hardcore, or the dmg is bugged on the mobs.

**Comment by Quban** [comment]
Any special mobs? Some links would be great, thx

**Comment by darkiepie** [comment]
uhh was so long ago and i cannot recreate the effect due to be high lvl now

from what i remembered we entered a 2nd time but now our tank had plate, maybe it was just the bad gear aspect.
the dugeon is from 40-50, so i presume tanks just came with the mail gear without much armor gets them bad stats for it.

i'll try to ask around if anyone experiences it, but i don't think so.
sorry to waste your time ;)
