### ISSUE TITLE
[PL][Raid] Serpentshrine Caverns, Battle of Mount Hyjal, Karazhan. Niewlasciwy loot lub jego brak

### ISSUE THREAD

**Issue by dondiego85** [Atlantiss/BugTracker#3456]
Na bossach 'tokenowych' raidow TBC strasznie buguje sie loot, albo dropia same tokeny, albo nie ma tokenow, a nawet nie dropnia zadne itemy. Sytuacje te zdarzyly sie na Kaz'rogalu w Battle of Mount Hyjal, Curator w Karazhanie oraz Lady Vashj na SSC.
Na dowod zostawiam screenshota z Curatora http://i.imgur.com/LlGrCMD.jpg
Niestety nie mam dowodow na reszte bossow, myslac ze to jednorazowe po prostu nie zrobilem.

**Comment by SOYER** [comment]
potwierdzam, ale to nie tylko na tych bossach co wyżej wymienione, ale na kazdych TBC i nie ma zaleznosci.
po jednym resecie ID np. z Princa w karazhan dropnie sam gold, po nastepnym resecie wszystkie ity naraz

**Comment by Piklo** [comment]
posted fixes at forum:
http://community.atlantiss.eu/index.php?/topic/11981-3456-serpentshrine-cavern-boss-loot-tables/
http://community.atlantiss.eu/index.php?/topic/11980-3456-karazhan-boss-loot-tables/
http://community.atlantiss.eu/index.php?/topic/11979-3456-the-battle-for-mount-hyjal-boss-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
