### ISSUE TITLE
[EN] [Mage] Living Bomb

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#3457]
the last tick gets me (the mage's target) into combat, really annoying if u're trying to restealth or eat.
I don't know if it gets the mage in combat if he isn't already. the mage's target shouldn't get for sure in combat once living bomb ends.

**Comment by kadi2** [comment]
Everything works blizzlike.

**Comment by Isuel** [comment]
then why was it reported AND fixed on a wotlk server?

**Comment by blinkmaster** [comment]
http://eu.battle.net/wow/en/forum/topic/2868759154
http://us.battle.net/wow/en/forum/topic/2913173185
its like on retail, working as intended.
