### ISSUE TITLE
[EN] [Quest] [The Storm Peaks] The Warm-Up

### ISSUE THREAD

**Issue by Ergiere** [Atlantiss/BugTracker#3458]
After defeating Kirgaraak (http://www.wowhead.com/npc=29352/kirgaraak) quest is not counted as completed.

http://www.wowhead.com/quest=12996/the-warm-up - The Warm-Up
http://www.wowhead.com/npc=29352/kirgaraak - Kirgaraak (main obj.)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/3406
