### ISSUE TITLE
[EN] [Quest] [Gilneas]Liberation Day

### ISSUE THREAD

**Issue by godric20** [Atlantiss/BugTracker#3459]
The quest is very bugged. The npcs that need to be freed arent in place where they should be which makes freeing them impossible. Just 2-3 NPCs work in entire cave.

Problematic NPC name: Enslaved Gilnean (http://www.wowhead.com/object=201775)
Problem description: The chains that they are supposed to stuck with are empty. Only a couple have the NPCs near them. Rest are empty or NPCs too far away to trigger the objective.

**Comment by Dean1989** [comment]
https://github.com/Atlantiss/BugTracker

**Comment by helldeskmonkey** [comment]
This is also a blocking quest - without completing this quest you are unable to proceed in the questline. This blocks Worgen from getting out into the main world.

(Whether or not this is a good thing is an exercise left to the devs)

**Comment by Tj20** [comment]
I can confirm this: Only very few Enslaved Gilneans have to chains attached to them.

However clicking the chains also works if there is a little bit of distance between the chains and the Gilneans.

This for example still gives you the quest credit, but it won't work if they are even farther away from their chains:

![still works](http://i.imgur.com/56KRj9Y.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3558
