### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Recruitment

### ISSUE THREAD

**Issue by davidcadena** [Atlantiss/BugTracker#3460]
http://www.wowhead.com/quest=26800/recruitment

After throwing one body ontop of Darnell he cannot pick up any more, and instead of the gear icon appearing on the bodies, it appears on Darnell. Clicking him does nothing though, and logging out does not fix this bug.

**Comment by martoak** [comment]
It still isn't working, anyone have a work around.

**Comment by then0rTh** [comment]
The quest works (just finished it), Darnell picks bodies without issue.

But there are few unpickable bodies (just outside Deathknell and on that little square). They make the impression that the quest is completly bugged. Would be nice to have them removed or fixed, but i guess its not that important.

**Comment by BAndysc** [comment]
Will be fixed in 5149
