### ISSUE TITLE
[EN][RAID] Karazhan

### ISSUE THREAD

**Issue by Johndoe53** [Atlantiss/BugTracker#3462]
I noticed the first boss (Attumen the Huntsman) is bugged. I was trying to farm the mount and it seems impossible. He goes down to 20% and then calls his horse.. he becomes untargetable/unkillable but he still grunts as if he was hitting you.

**Comment by smmuntz** [comment]
While this does happen sometimes, it doesn't happen all the time. Try switching who you are attacking down to 20%. Attacking the horse down also makes him mount the horse.
