### ISSUE TITLE
[EN][RAID] Serpentshrine Cavern

### ISSUE THREAD

**Issue by Ulissexo** [Atlantiss/BugTracker#3465]
Hello Team,

The other day I was doing serpentshrine cavern with my guild and we noticed that we're not able to use "fishing" inside serpentshrine cavern, because of this, we cannot summon "The Lurker Below" and we require this boss for some transmog items. Please help us on this.

Thanks in Advance

**Comment by Althin** [comment]
Same problem is in Dalaran, where we cannot use fishing.

**Comment by Probullet25** [comment]
Yea, same problem in Dalaran canals or Mount Hijal, near Fireland raid. Soo you can't fishing alots of thinks.

**Comment by Ulissexo** [comment]
Any update on this issue?

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1795
