### ISSUE TITLE
[PL][Profession][Inscription] Northrend Inscription Research doesn't give skill up

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3469]
Wykonanie http://wowwiki.wikia.com/Northrend_Inscription_Research powinno za każdym razem dawać szanse na 1 pkt skilla (100% "na pomarańczowo" itd.). U nas niestety daje tylko za pierwszym razem. Jest to dość irytujące, gdyż trzeba dobijać skilla na "zielonych" reckach do poziomu, na którym można się nauczyć nowych recek.

**Comment by Anhaeyn** [comment]
Ale każdy z tych "research" można zrobić tylko raz dziennie.
