### ISSUE TITLE
[EN][Item] Rough Stone Statue

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#347]
# What is not working:

The item is not working correctly. Instead of healing, behaves like a pet, dealing damage + tanking.

---
# How should work:

Basically, after you use the item (Rough Stone Statue), a tiny statue should appear (currently working) and heals you (not working). And after a few seconds, it should die (currently working).

After checking some [comments](http://www.wowhead.com/item=25882#comments:id=319800), it is possible to stop healing and start dealing damage, by going out of combat. I doubt that is just going out of combat (like Vanish) or it's just Feign Death (stop pet's cast).
Anyway, I added a link below that shows a player using the statue as a tank.

---
# More info:

This is made by Jewelcrafters. There are 5 versions. I just tested this one, so my guess is that the others are broken too.

Video#1 (from TBC): http://www.youtube.com/watch?v=u74buwdlEyY
Video#2 (from WotLK): http://crash.xfire.com/video/e21e9/
[Rough Stone Statue - WoWHead](http://www.wowhead.com/item=25498)
[Rough Stone Statue (Craft-Spell) - WoWHead](http://www.wowhead.com/spell=32259)
[Stone Healing - WoWHead](http://www.wowhead.com/spell=32253)
[Guardian Pet - WoWPedia](http://wowpedia.org/Guardian_pet)

Video#2 notes:
There is a pet bar, which does not appear on video#1.

Stone Healing is the buff applied to you when you are being healed by a statue. Can be seen on the video#1.

**This was tested on 4.0.6a realm**

**Comment by Angelo-DM-** [comment]
I confirm this bug! all the stones summons a PET!
![wowscrnshot_011015_160658](https://cloud.githubusercontent.com/assets/10468828/5692013/364506b2-98e3-11e4-98ce-607fe3e742ad.jpg)

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14397-npc-rough-stone-statue/

**Comment by TranceAccount** [comment]
Not sure whether the Stone Statue should rotate towards to summoner while he is casting Stone Healing.
