### ISSUE TITLE
[PL][Quest][Thousand Needles] Circle the Wagons... er, Boats

### ISSUE THREAD

**Issue by Misiac** [Atlantiss/BugTracker#3470]
Po abbadonowaniu questa nie można go już wziąć od żadnego NPC.
http://www.wowhead.com/quest=25542/circle-the-wagons-er-boats
Powinien być dostępny u NPC - http://www.wowhead.com/npc=40475/jinky-twizzlefixxit

**Comment by Bildo** [comment]
duplikat https://github.com/Atlantiss/BugTracker/issues/3266
