### ISSUE TITLE
Stable Master "internal pet error"

### ISSUE THREAD

**Issue by XrayAlert05** [Atlantiss/BugTracker#3471]
Kiedy próbuję wyciągnąć rare peta ze stable mastera, wyskakuje mi "internal pet error", ten komunikat występuje za każdym razem kiedy próbuję wyciągnąć któregoś z rare. Naprawcie ten bug!

**Comment by wojen616** [comment]
Głupie pytanie, ale czy jesteś w BMie gdy próbujesz je wyciągnąć?

**Comment by XrayAlert05** [comment]
A no fakt zresetowaliście talenty.. Nic dziwnego, że nie mogłem wyjąć rare ze stable. -,-'
