### ISSUE TITLE
[EN][QUEST] Bring 'Em Back Alive

### ISSUE THREAD

**Issue by Ulissexo** [Atlantiss/BugTracker#3473]
Hello Team,

This quest was working few weeks back, the kodos after you mount them don't move at all and you can't deliver them.

Thanks in advance

**Comment by Quban** [comment]
http://www.wowhead.com/quest=11690/bring-em-back-alive

**Comment by Ulissexo** [comment]
I retook the quest and i was able to complete, I didn't read the "10 minutes" for the antidote, but neither the item or the quest have a timer or any quest failed... So after taking the quest again, I did as soon as possible and able to complete.

Thanks for the support

**Comment by MercuricUma** [comment]
well it may have worked for you but at the moment is still bugged. The kodo doesn't move at all
