### ISSUE TITLE
[EN][Quest][Zul'drak] That's What Friends Are For...

### ISSUE THREAD

**Issue by goliatpiotr** [Atlantiss/BugTracker#3474]
http://www.wowhead.com/quest=12903/thats-what-friends-are-for

Quest doesnt seem to work. It worked before on all my previous characters. Didnt work now and i even tried again after restart, abandoned and retaken the quest couple of times, still the same whether you are very close to these npcs or just pass by them on a flying mount.

**Comment by Aruzam** [comment]
Can confirm, having the same problem. Done it without issues on several other characters lvling but now it doesn't work anymore. No matter what you do the quest doesn't record finding them.

**Comment by goliatpiotr** [comment]
To speed things up id like to say that without this quest you cannot start argent crusade chain in zul'drak, which means nearly half quests there are unavailable 'cause of this bugged quest.

**Comment by Helbringer** [comment]
I can reconfirm this, sorry for creating double bug report. #3616

**Comment by lourrific** [comment]
I can confirm also that this quest is bugged. I can not interact with NPC's.

**Comment by Atlantissbug** [comment]
I can also confirm

**Comment by schwim0341** [comment]
Please fix this quest, it makes the zone pretty useless due to it's importance in continuing the chain.

**Comment by DuGalle** [comment]
It has been so long

**Comment by jissabraham** [comment]
still not working ;-<

**Comment by Bildo** [comment]
fixed
