### ISSUE TITLE
[PL][Death Knight][Spell] Dark Simulacrum

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#3476]
Dark Simulacrum - http://www.wowhead.com/spell=77606
Cyclone - http://www.wowhead.com/spell=33786
Ring of Frost - http://www.wowhead.com/spell=113724

Dark Simulacrum kopiuje Cyclone tylko wtedy, gdy druid rzuci ten spell na inną osobę niż Death Knight. Gdy druid rzuca Cyclone na Death Knighta i w efekcie Death Knight otrzymuje Cyclone pozostaje tylko cooldown na Dark Simulacrum i nic więcej.

Ring of Frost natomiast u nas jest nie do skopiowania. Oczywiście powinien dać się kopiować.

**Comment by MangeNerfedOwl** [comment]
Cyclone nie powinien być możliwy do skopiowania, gdyż przy dark simulacrum działa to podobnie jak z healem czy procami - nie można nic dostać w cyclone. Na przykład: jeśli jako balance druid dostałem cyclone i w czasie tego cc mój dot tick spowodował pojawienie się proc na instant cast Starsurga - nie dostanę go. Gra pokaże mi że zdobywam "aurę" z prociem, ale w rzeczywistości go nie dostaję. Z simulacrum jest tutaj podobnie - najpierw dostajesz cyclone na siebie, a potem gra próbuje dać Ci tego spella, gdy latasz w cyclone, przez co nie możesz go dostać.

**Comment by lamaATS** [comment]
Fixed in rev. 5510
