### ISSUE TITLE
Human starting area.

### ISSUE THREAD

**Issue by vonsnabeldrake** [Atlantiss/BugTracker#3477]
Wolf's attack in pair if they are close enough to each other.
Assassin's are in stealth until you get close to them.

Lots of monster re spawn to slow, i could be mistaken but should be neutral but are hostile.

**Comment by Thefakemccoy** [comment]
Most mobs are neutral till you get down to where you have to put out fires. at the old vinyard.

**Comment by vonsnabeldrake** [comment]
Yes i know that, but they also have an extreme agro range and will gang you in pair.
