### ISSUE TITLE
[PL][quest][uldum] Chance of breaking chain.

### ISSUE THREAD

**Issue by nerv234** [Atlantiss/BugTracker#349]
Posiadając questa Shaping Up(28210) lata za nami Salhet(48022), gdy oddamy quest, tracimy aure kontrolującą tego npc, co za tym idzie jak za szybko zabiją nam go hieny to potem nie będziemy mieli możliwości wziąć kolejnego questa Salhet's Secret(28276).

Sposób naprawy? Wg. mnie zmiana wpisu w bazie danych żeby aura z Salhetem zostawała aż do momentu akceptacji questa Salhet's Secret(28276), wtedy rzadziej będzie się urywał chain różnym osobom i mniej ticketów będzie.

Pozdrawiam.

**Comment by Bastek** [comment]
Dodatkowo ten NPC ma 280 HP
