### ISSUE TITLE
[EN][Quest][Stormwind/Fishing] Diggin' For Worms

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3491]
The worms in this quest are invisible. You cannot see them. There are screenshots on Wowhead that show them as sparkling stars, but currently they are invisible. http://www.wowhead.com/quest=26420/diggin-for-worms#screenshots

**Comment by Anhaeyn** [comment]
They are invisible, but easy to find. Just move your cursor around the shore, and if there is any worm, then your cursor will change to gear icon.

**Comment by Juau** [comment]
Can confirm they are visible. Did this daily two days ago.

**Comment by stanchuck** [comment]
I've seen the worms being visible when I was around Olivia's Pond the other day, but when I got the daily, I couldn't find them. I caught the quest fish in the canals with no worm anyways, so the quest's completable, but not Blizzlike.
