### ISSUE TITLE
[Class][Hunter]Arcane Shot

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3493]
it shows wrong tooltip, i mean the tooltip said it dealed 0 arcane damage, but it dealed that damage
thanks

note=and so did steady shot

**Comment by Varchord** [comment]
Ok mate. You reaaaaly need to read this
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by MirrorWraith** [comment]
im sorry please close this thread, my bad
