### ISSUE TITLE
[EN][Quest][Borean Tundra] The Emissary

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#3496]
http://www.wowhead.com/quest=11626/the-emissary

Currently the quest won't count the kill, no matter if you kill it with the spear or even without it just by skills and attacks. Tried it 3 times, nothing worked. Broken and it also stops the chain and you progressing further with Kaluak.

**Comment by lourrific** [comment]
I'm currently having the same problem with this quest. i killed him twice and no quest complete.

**Comment by Thefakemccoy** [comment]
How it should be working.
Target him (Be in range) Throw Trident.
He then agroos on you with only 8% hp.
The you kill and get credit.
https://www.youtube.com/watch?v=jCvlh2k3T44&feature=youtu.be

**Comment by user1011** [comment]
At the moment the quest item doesn't work when I use it on Leviroth.

**Comment by LordKnightCecilo** [comment]
Right now to complete the quest you need to damage the boss down to 50% then use the spear. Using the spear first seems to give credit to the spear since you havent done at least 50% damage.

I managed to complete it with this method. At least it is a work around until possibly fixed.

**Comment by mcfreddas** [comment]
@LordKnightCecilo pretty hard to do that for some classes tho

**Comment by LordKnightCecilo** [comment]
Oh. I agree. I am just letting people know how it can be done. Obviously not all classes can self heal like my DK could. But you can always ask help from guildies or world or general. Until the problem is solved.

**Comment by coba999** [comment]
Quest doesn't work, pls fix it

"Find Leviroth in the waters below the iceberg floating among the northern edge of Riplash Ruins. Use the Trident of Naz'jan to slay him and return to Karuk to the north of Riplash Strand."
http://www.wowhead.com/item=35850/trident-of-nazjan - this must kill the http://www.wowhead.com/npc=26452/leviroth from 1 shot

**Comment by vragni** [comment]
Still Buged

**Comment by Aival94** [comment]
Bump.

**Comment by Larousene** [comment]
Still bugged, so... Bump

**Comment by Bildo** [comment]
fixed

**Comment by TheCopacabanaMan** [comment]
No fixed. As per 24 august, i tried all above methods, workarounds, and so on
Not get credit
