### ISSUE TITLE
[EN] [Quest] [Winterspring] Borrowing From the Winterfall

### ISSUE THREAD

**Issue by liftedleaf** [Atlantiss/BugTracker#3497]
http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall

This quest has the player collect meat from 3 furblog camps in Winterspring. Currently the meat does not spawn and so the quest cannot be completed. 

It's one of five  daily quests that are picked randomly for the player to earn their Reins of the Winterspring Frostsaber. The questline is only supposed to take 20 days (20 daily quests) but this bug will further the length if the player is unable to complete a randomly chosen daily.

**Comment by Aival94** [comment]
#3497 
#1647
