### ISSUE TITLE
[PL][Spell][Warrior] Charge

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3499]
1. Mniej więcej połowa szarży http://www.wowhead.com/spell=100/charge wykonanych w ruchu (głównie podczas skoku) tylko stunuje przeciwnika bez przemieszczenia warriora, mimo, że jest LoS i oczywiście dostępny path. Podobnie jest gdy warrior spada z wysokości, nawet niewielkiej (np. cmentarz na wsg).
2. Po użyciu szarży zaraz po zmianie targetu, jest ona wykonywana na pierwszym targecie, w trakcie szarży cały czas jest stargetowany drugi target. Na początku myślałem, że to przez spell Intervene użyty przez drugi target na pierwszym, gdyż nie znam mechaniki tego spella, lecz w każdym z przypadków żaden z targetów był warriorem albo hunterem z tenacity petem.

**Comment by Jenovas** [comment]
Proszę sprawdzić po revie 4473

**Comment by sunshineinabox** [comment]
Charge places you just outside the hit box sometimes it faces you in the correct direction but you need to take a few steps forward to be in melee range. Its happening with bosses with big hit boxes. I first noticed it in Slabhide.

**Comment by Axahus** [comment]
Generalnie jest duża poprawa na płaskim terenie oraz niewielkich nierownościach, warrior nie zostaje już w miejscu, a przynajmniej nie zdarzyło mi się to ani raz na kilku bg po wgraniu fixa. 

Zauważyłem natomiast problem przy podskoku/zeskakiwaniu + szarży z obiektów.
![11](https://cloud.githubusercontent.com/assets/10374091/8324311/8e586bf8-1a4f-11e5-812f-154a81f58416.jpg)
1. Podskok + szarża -> war wykonuje minimalny ruch, ale blokuje go krawędź obiektu. Mob na dole się agruje.
2. Skok w przód + szarża -> gdy war jest w powietrzu mniej więcej na poziomie krawędzi lub nawet trochę niżej, wraca na nią. Mob na dole się agruje.

![22](https://cloud.githubusercontent.com/assets/10374091/8324324/ad9d5046-1a4f-11e5-9b21-b066aa9f8874.jpg)
Tutaj podobna sytuacja, z tym, że szarża jest częściowo wykonana, ale kończy się na murku w zaznaczonym miejscu (mniej więcej w połowie tego odcinka z lewej). Mob na dole również się agruje.

**Comment by sunshineinabox** [comment]
Warrior's charge charge puts you out of melee range for lots of mobs its not just bosses like I thought. I have noticed it more now that I have played a little more.

**Comment by BialyADI** [comment]
Jest szansa że zostanie to naprawione ;x? Charge często zatrzymuje się na teksturze, daleko od celu od naszego targetu, tak jak widać to na obrazkach z stycznia.

**Comment by lamaATS** [comment]
Dalej występują problemy podane powyżej lub jak aktuanie wygląda sytuacja **Charge**?

**Comment by BialyADI** [comment]
Jest całkiem dobrze, czasem są sytuacje że Charge/Intercept nie chce się użyć np. na Blades Efge Arena. 

![](https://cloud.githubusercontent.com/assets/5214950/6387574/6dd4e4ac-bd8d-11e4-8f72-ff87eedd8048.jpg)

Link to starego zgłoszenia: https://github.com/Atlantiss/BugTracker/issues/2402.

**Comment by lamaATS** [comment]
Jesteś w stanie podac takie punkty? Bo osobiście nie udało mi się takich znaleść.

**Comment by BialyADI** [comment]
to występuje gdy masz Glyph na Charge i ma 30y zasięgu i gdy staniesz daleko przy tych drewnianych słupach a przeciwnik na kamiennym pilarze za lina, to klient nibmy pokazuje na ze możesz wcisnąć Charge a się nie da.
Podobnie jest z Bg Warson Gough nie można dać Charge/Intercepta na Resp wroga a powinno się dać co widać na różnych filmikach PvP.

wyjaśniłem to tu w jednym z postów: https://github.com/Atlantiss/BugTracker/issues/6505.

"No i jest problem z takim czymś jak na filmiku, o ile jest to możliwe do naprawy na Atlantissie:

Charge pod górkę na resp przeciwnika na WG, na Atlantissie zobaczymy "No path available".
https://youtu.be/Qce6m6HstRA?t=3m50s <-- 3:50 min.

Intervene pod GÓRĘ, u nas niemożliwe:
https://youtu.be/scDrEXNSR-Y?t=21m49s <-- 21:49 min."

**Comment by BialyADI** [comment]
Można chyba tan wątek zamknąć bo z Charge i golnie z Charge/InterceptIntervene jest ok nie zatrzymuje się w połowie i daje Stuna po dotarciu do celu.
Jedynie co pod wzniesienia Charge/InterceptIntervene co opisałem tu https://github.com/Atlantiss/BugTracker/issues/8489.

**Comment by BialyADI** [comment]
Dam tu ostatnie 3 problemy które dotyczą Movementu Warkowego, a tak to jest już ładnie :P.
https://github.com/Atlantiss/BugTracker/issues/8491
https://github.com/Atlantiss/BugTracker/issues/8490
https://github.com/Atlantiss/BugTracker/issues/8489

**Comment by lamaATS** [comment]
Zamykam jeśli według kogoś powinno pozostać otwarte nich napiszę i najlepiej powód dlaczego (czyli co jeszcze działa nie tak) lub poprostu otworzy nowe issue.
