### ISSUE TITLE
[EN][Core] Double dipping with percentage damage modification effects

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#3500]
Certain spells double dip with percentage damage modification buffs, nearly all of those spells are spells that have their values based on other spells (spells that work similarily to ignite are all suspect)
The easiest way to reproduce it, is to gain the Tidal surge buff  http://www.wowhead.com/spell=76133/tidal-surge from throne of the tides and then hit something. However it works with any effect that is not present on the caster as well (such as boss buffs/debuffs)
Such effects include the debuffs on Halfus Wyrmbreaker (http://www.wowhead.com/spell=87683/dragons-vengeance), Al'akir (http://www.wowhead.com/spell=87904/feedback), Elementium Monstrosity (http://www.wowhead.com/spell=84918/cryogenic-aura) and Magmaw (http://www.wowhead.com/spell=79011/point-of-vulnerability)
Spells affected by this bug include : 
Conflagrate (http://cata.openwow.com/spell=17962) - This warlock spell is also increased by Destruction Mastery : Fiery Apocalypse
Searing Flames (http://cata.openwow.com/spell=77657) - This shaman talent is also increased by Enhancement Mastery : Enhanced Elements
Improved Serpent Sting (http://cata.openwow.com/spell=82834) - This hunter talent is also increased by Survival Mastery : Essence of the Viper
Echo of Light (holy priest mastery - http://cata.openwow.com/spell=77489)
An important thing to note is all of the above spells deal damage based on another spell's damage (Immolate, Searing Bolt, Serpent Sting) and this also might be related to this bug. Also any similar effect (such as warrior deep wounds and mage ignite) might be affected by this bug as well.
There also might be other spells affected by this bug of course, but right now I only remember about those 3.

**Comment by kadi2** [comment]
I didn't test it so deeply, but at first look it seemed to me Conflagrate's portion of damage from immolate is also reduced by resilience. I'd say combustion and ignite works pretty well with all the damage modifiers, otherwise it would be noticeable with such effects you mentioned above.

**Comment by aneq** [comment]
yes, its not just damage amplification, its damage modification. It makes sense those spells double dip from resilience as well
The fix should either make those spells not affected by such modifications or base of immolate/serpent sting/searing bolt before they're affected by such modifications

**Comment by kadi2** [comment]
At the moment it's like:
[(Immolate_basic_damage + Immolate_coeffs) * DMGMod + Conflagrate_Basic_damage + Conflagrate_coeffs] * DMGMod

Probably should be:
(Immolate_basic damage + Immolate_coeffs + Conflagrate_Basic damage + Conflagrate_coeffs) * DMGMod

Ignite is totally ignoring DMG Modifiers on the server, but Ignite shouldn't do so since middle of cataclysm... No idea about Deep Wounds and similar effects.
https://github.com/Atlantiss/BugTracker/issues/3130

**Comment by aneq** [comment]
I'm pretty sure searing flames double dips with mastery as well 
I've run some test in simcraft and searing flames seems to deal at least x2 the damage it should (and that is before any external modifiers like throne of the tides last boss aura)

**Comment by meowmewo** [comment]
Can confirm Conflagrate and Improved serpent sting. 
If u have 1/2 Serpent Spread everything is fine.
If u have 2/2 serpent spread - double dip from Improve serpent sting on every multi shot.

**Comment by aneq** [comment]
UPDATED to include echo of light

**Comment by meowmewo** [comment]
And still.

**Comment by Kejmil** [comment]
still bugged, used by DA to kill 25hc Nefarian, plz ban ( ͡° ͜ʖ ͡°)

**Comment by aneq** [comment]
stop being so TOXIC and ANTI-FUN

**Comment by Wolffenstein** [comment]
Fixed in rev 4647. If there are any other spells with similar problems, please open a new issue.
