### ISSUE TITLE
[PL][QUEST][Winterspring]  The Root of All Evil

### ISSUE THREAD

**Issue by Seavitia** [Atlantiss/BugTracker#3501]
Id Questa 8481
Quest brany u Timbermaw Hold po zdobyciu statusu exalted.

Po ubiciu Moba nie dropi Torba z której powinien wypaść Q item. Ewentualnie zaniżony drop.

Xandivious http://www.wowhead.com/npc=15623/xandivious
Xandivious Demob Bag http://www.wowhead.com/object=180671/xandivious-demon-bag#contains
Xandivious essence http://www.wowhead.com/item=21145/essence-of-xandivious

**Comment by Quban** [comment]
Torba nie dropi z moba tylko pojawia się skrzynka koło moba, w której powinien znajdować się item. Testowałem 5x i działa, spell działa, skrypt też działa. Proszę sprawdzić jeszcze raz, czy nie pojawia się skrzynka, może w texturach się pojawiła i nie było jej widać
