### ISSUE TITLE
[PL][Quest][Winterspring] "Borrowing" From the Winterfall

### ISSUE THREAD

**Issue by Seavitia** [Atlantiss/BugTracker#3502]
Jeden z daily questow branych od kociaka, żeby zdobyć wąsy na mounta (http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall)

W osadach furbolgów powinny być do zebrania q itemy - brakuje ich całkowicie
http://www.wowhead.com/object=208189/smoked-meat

**Comment by Aival94** [comment]
#3497 
#1647
