### ISSUE TITLE
[PL][Core] Can't queue BG when there is DF cooldown / Dungeon deserter

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3506]
Jak w tytule - nie można zapisać się na BG gdy mamy DF cooldown lub dungeon desertera. Wyświetla się komunikat "You cannot queue for a Battleground or Arena while using the Dungeon System".

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/696
