### ISSUE TITLE
[EN][Quest] Green Eggs and Whelps

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#3509]
http://www.wowhead.com/quest=11279/green-eggs-and-whelps

spraying the plague on eggs doesnt do anything , it should spawn http://www.wowhead.com/npc=24160/plagued-proto-whelp when you do it , then youre supposed to kill the whelps which drop quest items http://www.wowhead.com/item=33420/plagued-proto-whelp-specimen
something like that

**Comment by Helbringer** [comment]
I can confirm this is not working.

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4469

**Comment by MercuricUma** [comment]
for me it's working. I damaged the egg and used the quest item on it, the dragon came out and looted the quest item
