### ISSUE TITLE
Surrender or Else! [The Lost Isles] quest.

### ISSUE THREAD

**Issue by ankhet** [Atlantiss/BugTracker#3512]
The following NPC is not spawning - [Leader of the Naga] -screenshot of the NPC - http://wow.zamimg.com/uploads/screenshots/resized/316005.jpg
      wowhead link to this quest 
http://www.wowhead.com/quest=24868/surrender-or-else

**Comment by Tj20** [comment]
I did this quest 2 days ago and it worked fine for me. There were even two of these guys at the same time since I started the quest about at the same time as another player.

**Comment by Artix333** [comment]
Mine are spawning in the ground and I can't atack it...

**Comment by domel1998** [comment]
Hi, I cant end this  quest becouse this MOB is not here! i cant see him anywhere waiting all time and nothing. PLS HELP!
