### ISSUE TITLE
[PvP] [PL]Big Issue 

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#3513]
Musi być jakiś problem z łapaniem na areny 2v2 / 3v3 i BG na atlantissie, zawsze gdy się zapisuje to prawie nigdy nie łapie na te kategorie, wydaje mi się że coś jest źle zrobione z systemem kolejkowania. Przecież to nie możliwe żeby nikt nie grał PvP

**Comment by blinkmaster** [comment]
coz, juz dawno temu dawalem sugestie zeby zrobic dynamiczne, rozszerzajace sie widelki ( taki system  powstal poczatkowo na dawnym AT, pozniej przeszedl na wiele prywatnych serverow w tym sunwell/tod etc). inna opcja by bylo zeby chociaz po 2,5 - 3 min byla instant arena, bo to jest straszniee denerwujace jak trzeba tyle czekac :(
