### ISSUE TITLE
[EN][Quest][Terrokar Forest] Digging Through Bones

### ISSUE THREAD

**Issue by Beponator** [Atlantiss/BugTracker#3514]
http://www.wowhead.com/quest=10922/digging-through-bones it is bugged, please fix it because i can't get http://www.wowhead.com/achievement=1272/terror-of-terokkar missing one quest .

**Comment by imeasytokill** [comment]
Hi, I did this quest like this:
I go on a spot before take q, kill mob which stand there and then go take q. Works for me. Did i 20 day ago.

**Comment by Beponator** [comment]
Thank you very much imeasytokill.

**Comment by imeasytokill** [comment]
I think that this is a issue, mob from q exists before event in q starts.

**Comment by armano2** [comment]
#479
