### ISSUE TITLE
[EN] [Quest] [Shattrath City] What Book? I Don't See Any Book.

### ISSUE THREAD

**Issue by Beponator** [Atlantiss/BugTracker#3515]
http://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book
i can't  beat Down "Dirty" Larry and get information.please fix it

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/687

**Comment by Noviush** [comment]
Almost two years... Could you set this quest to autocomplete if there is no possibility to fix it?

**Comment by Piklo** [comment]
Dont bump closed posts
