### ISSUE TITLE
Destro useless in pvp

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#3517]
Nether Protection talent in the Destruction tree is not working at all.

What it's supposed to do: When you absorb damage through Shadow Ward, Nether Ward or >other effects<, you gain Nether Protection, reducing all damage by that spell school by 30% for 12 sec.

What it does now: Nothing.

Usually other servers have this fixed with Shadow Ward & Nether Ward, but not through other effects.
I'd be so happy if you could fix ASAP since it's a gamechanging talent. Without it destro is dead meat against all casters. Thanks for reading.

http://wowwiki.wikia.com/Nether_Protection

Edit: This effect does not work with rogue poisons.

Edit 2: Did some more testing and I found out it works fine while within Fel Armor. It's not working through Demon Armor. Thanks for understanding.

**Comment by MasterK15** [comment]
Learn to post bugs here, Learn to reading. and start use Armors for your lock thats all.

**Comment by Fearyourself** [comment]
I am using armors... It doesn't work with rogues poisons.

**Comment by MasterK15** [comment]
you edit your report  after my post so stop lie

**Comment by Fearyourself** [comment]
Wtf.. Are you stupid? Just fix the damn bug will you.

**Comment by Fearyourself** [comment]
Like seriously
