### ISSUE TITLE
[EN] [Item] [Borean Tundra] The Ultrasonic Screwdriver

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3519]
http://www.wowhead.com/item=34984/the-ultrasonic-screwdriver

This item is supposed to drop from NPC Sentry-bot 57-K with 3% droprate. I have farmed this NPC for over an hour with100 plus kills and it hasn't dropped once. With 3% droprate at 100 kills this item should of dropped at least 3 times.

This item starts quest The Ultrasonic Screwdriver http://www.wowhead.com/quest=11729/the-ultrasonic-screwdriver

**Comment by BAndysc** [comment]
The drop chance should be ~75%.

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4469

**Comment by BAndysc** [comment]
Thank you, forgot to close :)

**Comment by Emielos** [comment]
Today i have killed many robots, but this item does not seem to drop. Even tho i read it was fixed?

**Comment by Thorghar** [comment]
If someone say that Ultrasonic Screwdriver can be looted from sentry bot (wowhead say is 3% chance to drop) or any bot in the area than its S..T !!! It can't be looted, it's broken....
http://atlantiss.eu/changelog#rev4469 and this is shit...

**Comment by aendry** [comment]
i can't get the item :/
