### ISSUE TITLE
[EN][Pet][Hunter] Wolvarine Bite

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#3520]
Close.

**Comment by Jenovas** [comment]
We only made pets scale with AP, Expertise, Hit, Haste, HP, Armor, Resistance, Resi, fixed all Basic attack spells (Bite, Smack) but yeah we only nerfed them with passion...

**Comment by meowmewo** [comment]
I didnt say nerf. I said fixing bugs that gave extra dps. Its time to fix stuff that are not doing enough dps now.

**Comment by Jenovas** [comment]
meowmewo - yeah that's why before my fixes they did 100 DPS at max after my fixes they started doing 10k DPS which was a little to much so they get nerfed. EoT cause I see you have no idea what your talking about.

**Comment by meowmewo** [comment]
Im not considering ur pirmal fixes on server release. Im talking about pet dmg + getting buffs to present time.

**Comment by meowmewo** [comment]
Anyway. Just close it then if u want.

**Comment by armano2** [comment]
diplicate: #12
