### ISSUE TITLE
[EN][UNKNWON][VENOMSPITE] Extreame lags inside tower

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3522]
![wowscrnshot_061215_123231](https://cloud.githubusercontent.com/assets/10423624/8129292/b73612cc-10ff-11e5-8841-a7ee9ef7a561.jpg)
![wowscrnshot_061215_123500](https://cloud.githubusercontent.com/assets/10423624/8129293/b873ec86-10ff-11e5-971c-37965d3de6d2.jpg)
When entering this building you will instantly find that it will lag your client ALOT, however when not moving inside this building it will run smoothly. Just seems that movement makes the lag. I have tried running in other buildings in venomspite and they seem fine.

**Comment by Quban** [comment]
Hmm. I can't reproduce this issue, i've asked my friend so he tried too and nothing is happening. Maybe you've handed in some quest or started some event?

**Comment by Helbringer** [comment]
I will try to reproduce this again on anouther client and character

**Comment by Helbringer** [comment]
I got this lag while i was questing, so its possible that it may have been linked to a quest.

**Comment by xmesaj2** [comment]
My brother has some lag in instances and various places as well.

**Comment by Helbringer** [comment]
I never managed to reproduce this. I have no idea how this lag occurred in the tower.
