### ISSUE TITLE
[EN][Achievement] Guild - Working as a Team not working

### ISSUE THREAD

**Issue by Pickles23** [Atlantiss/BugTracker#3523]
The guild achievement Working as a Team to max all professions in your guild is not working properly. It requires you to reach honored before you max your profession. Instead it should give credit once you reach honored with the guild even if your profession is already maxed.

edit; I've checked with people in my guild to verify that they are Honored and we're still not getting credit.

**Comment by Pickles23** [comment]
![image](https://cloud.githubusercontent.com/assets/12860938/8131260/b16ea334-10de-11e5-8e51-ba8af442b2fb.png)

**Comment by Aival94** [comment]
check first if they have honored with the guild.

**Comment by Pickles23** [comment]
I have checked. The problem is you have to get honored BEFORE you max professions. It should not work like this. If you have max profession and get honored AFTER you will not get credit, but you should.

**Comment by sunshineinabox** [comment]
Yup experienced the same thing. There is a polish entry already.

**Comment by Aviannaqt** [comment]
#2264
