### ISSUE TITLE
[EN][Quest-Priest]Aiding the injured

### ISSUE THREAD

**Issue by Celulariq** [Atlantiss/BugTracker#3525]
http://wow.gamepedia.com/Quest:Aiding_the_Injured
After learning "Flash Heal" you should use it on the Injured Draenei but they can't be healed.
When you cast Flash Heal on the injured Draenei they are no healed, my character it heals itself.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1666
