### ISSUE TITLE
[EN] [Dugeon] [The Vortex Pinnacle - Cata Dugeon] Boss Ecounter

### ISSUE THREAD

**Issue by darkiepie** [Atlantiss/BugTracker#3526]
Asaad, Caliph of Zephyrs 
http://wowwiki.wikia.com/Asaad

During the fight Asaad casts:

- Unstable Grounding Field 
http://www.wowhead.com/spell=86911

this field is currently not workin, players withing the field, will take and do damage wich leads to,
the Field currently doesnt complete itself prob dat problem comes from that, it should be a piramid resemble and with asad on top of it, asaad does not more to on top of it and the field does not complete itself to resemble a piramid, it only draws two ground lines as seen in.

http://i.imgur.com/gtgMrGh.jpg

-Supremacy of the Storm, http://www.wowhead.com/spell=86715

when this happens all players should be withing the Unstable Grounding Field, to avoid the massive damage, therefore leading to a wipe, but as it was mentioned above, the Field is not working and Supremacy of the Storm hits all players, making the last boss fight impossible (Comments say its possible to avoid the skill if we stand real close and underneath the boss).

Done in normal more
Unknown in Hardcore.

Here's how the fight should be :

https://www.youtube.com/watch?v=Ycl4ihhDpuM

All in all all comes down to knowning the secrets of the server i had no ideia how it worked and the rest of the party so we were confused and i decided to report it.
Sorry for the bad english.

other general problems also seen in #769
Thank you to Varchord.

**Comment by xolon** [comment]
You can still do it by standing really close to boss, no matter where unstable grounding field is

**Comment by jakeoff** [comment]
Can confirm the fight is not impossible. It's actually easier without Supremacy of the Storm not working, just stack under the boss the whole fight.

**Comment by darkiepie** [comment]
hmm thx for the tip, good to know.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/769
