### ISSUE TITLE
[EN][Object] The Orb of Command

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#3528]
http://www.wowhead.com/object=179879/orb-of-command#comments

The orb of command is missing. It is used to teleport players directly to BWL
As of patch 4.3 you don't have to be in raid group to be teleported

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7893-4666questblackrock-mountain-blackhands-command/?p=32330
