### ISSUE TITLE
[PL][Event] Darkmoon Faire don't stay one week

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3529]
http://wowwiki.wikia.com/Darkmoon_Faire_%28old%29 powinno stać tydzień od 00:01 w niedziele. U nas już w piątek ich nie ma (możliwe, że nawet wcześniej, ale zajrzałem dopiero w piątek).

**Comment by Bildo** [comment]
Wiesz, ze DMF odpala sie w zlym terminie ? Odpala sie 2 tygodnie +/- w porownaniu do kalendarza

**Comment by Axahus** [comment]
Nie wiedziałem. Czerwcowy odpalił się poprawnie - w pierwszą niedzielę miesiąca.
