### ISSUE TITLE
[PL][Instance-Cataclysm] Blackrock Caverns

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#353]
# Other
UPDATE 09.01.2015 rev 4215
* <del>Portal przenoszący nas do 3 bossa jest od razu aktywny</del>
* <del> Jeśli jeden gracz wskoczy do portalu obok wejścia od razu za drugim ten drugi gracz utknie i musi wykonać relog</del>

# [Rom'ogg Bonecrusher](http://www.wowhead.com/npc=39665)
UPDATE 09.01.2015 rev 4215

* <del> Boss czasem przy zagrowaniu nie atakuje tanka tylko kontynuuje swój patrol używając umiejętności z encountera. Należy go wtedy przetauntować
* [Call for Help](http://www.wowhead.com/spell=82137/call-for-help) nie działa

# Trash

**Conflagration**
* <del>Powinny ożywiać Quicksilver</del>
 * http://www.wowhead.com/npc=40004#comments
 * http://www.wowhead.com/npc=39994#comments

**Comment by Varchord** [comment]
Zmień to na 4.3.4

**Comment by Varchord** [comment]
UPDATE 09.01.2015 rev 4215

**Comment by Varchord** [comment]
UPDATE
* Call for Help

**Comment by Quban** [comment]
Fix na kilka rzeczy, do sprawdzenia :)

**Comment by Varchord** [comment]
Jakich rzeczy? Slepy. Jestem albo w changelogu nic nie ma ^^

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4455 zapomnialem wtedy tu napisac jak wrzucalem

**Comment by sunshineinabox** [comment]
I used translator to check this and it seems the issue with him getting stuck on his patrol path is mentioned. I would like to add that there is a way to get around this get a dps to pull wait for him to finish call for help and then the tank can taunt and he will exit his path and actually come to the tank.

**Comment by Aival94** [comment]
Mobs [Quicksilver](http://www.wowhead.com/npc=40004/quicksilver) are always active and not frozen as supposed to be and then become active again when [http://www.wowhead.com/npc=40004/quicksilver](http://www.wowhead.com/npc=39994/conflagration) move near them.

Minor issues: 1. [Karsh Steelbender <Twilight Armorer>](http://www.wowhead.com/npc=39698/karsh-steelbender) not move around in circles like he should do(https://youtu.be/CyAjhaIe5v0?t=136)
2. One [Conflagration](http://www.wowhead.com/npc=39994/conflagration) should move on the inner circle and the other on the outer circle.Now both move on the outer circle which make the inner quicksilvers just useless/decoration.
3. Not sure if this is a bug or not but [Conflagration](http://www.wowhead.com/npc=39994/conflagration) respawn after some time.

**Comment by Quban** [comment]
Fixed Quicksilver and Conflagration

**Comment by Varchord** [comment]
quban are you bored?

**Comment by Quban** [comment]
no

**Comment by Varchord** [comment]
too bad
