### ISSUE TITLE
[EN][QUEST][DARKSHORE]The Eye of All Storms

### ISSUE THREAD

**Issue by Theraden** [Atlantiss/BugTracker#3530]
Quest cannot be completed. The green dragon's pathing is broken, the twilight dragons are bugged and don't fly in the air, they're stuck on the ground below and can't be attacked. Also, the Twilight Portal you are supposed to kill is unattackable and invisible (you have to type /tar twilight portal to target it, and it can't be hurt).

http://www.wowhead.com/quest=13588/the-eye-of-all-storms

The portal is supposed to be floating above in the vortex so you can attack it, and the twilight dragons are supposed to be circling flying in the air in the vortex as well so you can attack them.

This quest is required to progress in Darkshore...so once you reach this quest, you have to leave Darkshore because it can't be completed.

**Comment by LaveGit** [comment]
It's completable, but very bugged indeed.

You can un-stuck the drakes which are one the ground by slowly flying straight upwards from where a drake is on the ground.

Takes a lot of time to complete it and it is very annoying yea :P

**Comment by Theraden** [comment]
And how do you kill the portal?

**Comment by Aival94** [comment]
Reported: #2028
