### ISSUE TITLE
Dungeon Finder Bugged

### ISSUE THREAD

**Issue by Skillzkillz** [Atlantiss/BugTracker#3531]
The dungeon finder is completely bugged.

I proved it with a few friends, and for instance if I join the dungeon finder for instance and it says for instance 1/1 tank ; 1/1 healer and  2/3 Damage then I invite a friend (DPS) then we queue again and it says the same again then I invite another friend also a DPS then we queue again,then it says we need a tank,then I invite another friend a tank then it says we need a healer, we have tested it a few times with different classes,different specs and on different times... it's always the same,and now and then when your lucky it instantly pops.

I don't know how your guy's dungeon finder is scripted,but it is one of the very few bugs and we are all very great full for that.

**Comment by Aival94** [comment]
Please search before reported and generallt follow rules how to make a topic.

#2028
[README.md](https://github.com/Atlantiss/BugTracker)

**Comment by darkiepie** [comment]
ill copy pasta this for you mate since i find this super important.
