### ISSUE TITLE
[EN] [Game Function ]  RDF function Bugged!

### ISSUE THREAD

**Issue by darkiepie** [Atlantiss/BugTracker#3532]
"The dungeon finder is completely bugged.

I proved it with a few friends, and for instance if I join the dungeon finder for instance and it says for instance 1/1 tank ; 1/1 healer and 2/3 Damage then I invite a friend (DPS) then we queue again and it says the same again then I invite another friend also a DPS then we queue again,then it says we need a tank,then I invite another friend a tank then it says we need a healer, we have tested it a few times with different classes,different specs and on different times... it's always the same,and now and then when your lucky it instantly pops.

I don't know how your guy's dungeon finder is scripted,but it is one of the very few bugs and we are all very great full for that."

Original and tests by Skillzkillz
#3531

**Comment by Dean1989** [comment]
it's only a visual bug

**Comment by Aival94** [comment]
Reported: #696

If you want to give more information make a comment in the already reported one.Do not make a new one.

**Comment by darkiepie** [comment]
good point, but u reported a different thread dats why i did this one for the lad
