### ISSUE TITLE
[EN][Quest][Un'Goro Crater]The Spirits of Golakka Hot Springs

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#3534]
In the Un'Goro Crater quest "The spirits of Golakka hot springs" (http://www.wowhead.com/quest=24706/the-spirits-of-golakka-hot-springs), the NPC giving the quest, "Maximillian of Northshire" should have a dialogue with the Steaming Furies (http://www.wowhead.com/npc=38254/steaming-fury) in the region. No matter how one tries to provoke the furies however, the quest cannot be completed since Maximillian does not speak to the furies or stops following the player.

**Comment by BAndysc** [comment]
Please search for similar issue before posting a new one.

https://github.com/Atlantiss/BugTracker/issues/398
