### ISSUE TITLE
[EN][Quest][Loot][Westfall] It's Alive! #26257

### ISSUE THREAD

**Issue by ElBondi34** [Atlantiss/BugTracker#3537]
The Quest are not acheivable because we can't loot the quest on NPC : Harvest Watcher . Can you  work the loot of this quest .

Quest Link: http://www.wowhead.com/quest=26257/its-alive
NPC of Loot : http://www.wowhead.com/npc=114/harvest-watcher

**Comment by Dean1989** [comment]
did this quest 4 days ago without problem

**Comment by Beatlejuicey** [comment]
It worked for me as well, with no issues

**Comment by ElBondi34** [comment]
Ok i close , just me i have no chance with the loot . Think you for answer .
