### ISSUE TITLE
[EN][Quest][Script][Westfall] A Vision Of the Past #26320

### ISSUE THREAD

**Issue by ElBondi34** [Atlantiss/BugTracker#3538]
The Quest is bugged because when i use obejct i go with spirit to the battle of the past and when i arrived to the battle , 0 Event are activated , the quest is bugged and can't complete it . Need a Rework of the Script .
link : http://www.wowhead.com/quest=26320/a-vision-of-the-past
Object : http://www.wowhead.com/item=58147/incense-burner

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1622
