### ISSUE TITLE
[EN][Quest][The Cape of Stranglethorn] Through the troll hole

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#354]
After completing "Eliminate the outcast" (http://www.wowhead.com/quest=26810), you should get an on-the-spot turn in, through the interface, and you DO, but after you turn it in there you don't get the follow up quest "Through the troll hole" (http://www.wowhead.com/quest=26811) automatically.

Also, back at the NPC, there's no "!" mark, and some people could actually miss this quest, and thus not complete this chain of quests. In order to continue, on our server, you need to talk to the NPC that gave you "Eliminate the outcast", and then click on the dialogue option, which then teleports you for the "Through the troll troll hole" quest, and you also get the quest.

https://www.youtube.com/watch?v=KhJUXWp38d0
https://www.youtube.com/watch?v=bm4E6rOR7v0

Watch the first video, you will see that in the end, before the video is finished, he automatically gets "Through the troll hole" to accept, and after that, and in the second video, you see how the rest of this quest goes, and that he continues right there on the spot.

**Comment by xmesaj2** [comment]
rev 5607, fixed
