### ISSUE TITLE
[EN][Quest][Azshara] Azsharite Experiment Number Two

### ISSUE THREAD

**Issue by Thamaska** [Atlantiss/BugTracker#3543]
http://www.wowhead.com/quest=14388/azsharite-experiment-number-two
"Speak with Assistant Greely to be shrunken down to rat-size. Mount a Rocketway Rat and use it to terrify Gormungan the giant."
When you terrify Gormungan you grow back to original size and you able to fly like a GM :laughing:

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/888
