### ISSUE TITLE
[EN][Quest][The Storm Peaks]Warm up

### ISSUE THREAD

**Issue by Garndzilla** [Atlantiss/BugTracker#3544]
It's impossible to finish this quest http://www.wowhead.com/quest=12996/the-warm-up#videos
I beat Kirgaraak many times, he must to be "green" with us when is near to his death. I tried to beat him very slowly but it's no use. Please fix it.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/3406
