### ISSUE TITLE
[en][core] Dynamic MMr team picking up system

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3548]
This system doesn't work here. It should increase ( after some time ) your picking range so you can play with lower ( or higher ) teamed opponents but still closest to ur rating.
Its pretty hard to find some info regarding that matter due to WoD and MoP having totally different style of arena q but hope this will help.
http://www.mmo-champion.com/threads/720492-Guide-Match-Making-Rating-(MMR)/page3
"Problem is the lack of teams. Blizzard prefer you fighting higher or lower teams in stead of not fighting any teams at all. It's both for good and bad obviously.
If you wait in queue for a long time the matchmaking system will increase the rating range of possible ooponents.
If there were more teams queueing at around your rating you'd be fighting proper teams."
so after all i can change this from suggestion in arena part of forum into bugtracker ^^ finally!

**Comment by Jenovas** [comment]
Ok so how often should this happen and by how much?
Let's say every 1 minute +- 100 rating?

**Comment by blinkmaster** [comment]
well i dont have the proper info so i dont want to throw random numbers but i think 100 rating every minute is realy ok, considering you have about 2300 - 2400 mmr in top ranks it will still take few mins to que you up with low rated teams.
1 thing i have to add : 
current system works like that : if in 5 mins no one from your team ques up you will be qued up with first team which que after your 5 mins
how it should work with the new system : should take you in with teams ALREADY in que, due to your rating pick up increase. 
hope i made it clear and its possible to do, would be lovely

**Comment by Jenovas** [comment]
I already did the system, every 1 minute rating goes up and down by 150.
Already did tests and teams that have a high difference in rating get connected after 4-5 minutes.
But I also think I found a serious bug with the arena system and a bug that makes teams wait longer than they should. I need to test this and fix it and maybe this week there will be an update with this.

**Comment by blinkmaster** [comment]
well this are great news, hope its gonna go live soon *_*

**Comment by Jenovas** [comment]
So I did the dynamic MMR and I fixed the bug we had.
The bug we had / have is - if the first team in queue has say 2500 rating the teams that are allowed to play with this team are from 2250 to 2750 rate, if no team is found the searching for teams ends.

So say we have team1 with 2500 rate, team2 with 1000 rate, team3 with 1000 rate.
Just because team1 has 2500 rate team2 and team3 will not be able to fight, and have to wait for team1 to first have it's battle. So the worst scenario is all teams have to wait 5 minutes to have a battle even though there are many teams at their MMR.

These fixes change alot so I'll be trying to first test this at home by myself running 10 wow clients and once I'm happy with it the server will be updated.

**Comment by blinkmaster** [comment]
this explains why we had to wait 5 mins for the second team in q in our mmr range :)

**Comment by blinkmaster** [comment]
oh and btw - if its gonna work properly i think you could update this in NEWS page on forum :) afterall - not all servers have this working, especially working correctly and it may always encourage more people to try out some pvp in arenas.

**Comment by Jenovas** [comment]
Should be live with next update - rev. 4478 please check if everything works ok

**Comment by blinkmaster** [comment]
cool thing, did u make it show that mmr increases? i remember from other servers it showed in yellow text smth like : you mmr picking range is now x to y
would be very nice to see this also, small and cosmetic but still nice ;)

**Comment by Jenovas** [comment]
No I didnt add anything like that, we will think about that in the future.
For debugging I had the players yell in chat "Min MMR 1500" "Max MMR 1700" "Normal MMR 1600", I can add that it might be funny :P

**Comment by blinkmaster** [comment]
would be nice, its always easier to type in /world that ppl from 1300-1900 range can que up and not to do hard math skillz and calculate it by ourself ^^
