### ISSUE TITLE
[en][core] MMR team and personal ratings

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3549]
MMR, Team and personal ratings should try to equalize each other. In other words:
I have high mmr - i receive alot of team rating and personal rating to equal it with mmr at some point
this pretty much work BUT
Team have high rating, i have high mmr, my partner have high mmr and we joined the team so we have low personal - personal should increase at maximum to equalize with mmr and team rating. here it doesn't work and i find it pretty strange that after more than 100 arenas with v. decent win/lose ration i am still 300 points behind team rating. This is clearly game breaking - if i want to equal with team rating i have to play like 400 arenas to equalize and what if another person joins team? well even with 100% win ratio it would take him about 800 arenas to catch up. Clearly broken.
due to fact MoP and WoD mechanisms are clearly different its hard to find some explanation of how it should be but still i managed to find smth:
http://us.battle.net/wow/en/forum/topic/4063168186

**Comment by kadi2** [comment]
MMR system and any arena tournament will bring some PvP players and competition. Please.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/205

**Comment by Jenovas** [comment]
rev. 4610 
PvP:
fixes to Arena Queue System - needs testing, also please check if Rated BG works after this fix and send me a report
changes to gained rate from arena's - MMR, Personal and Team Rating will grow faster until they are even

Please check it after this rev.
