### ISSUE TITLE
[EN][Quest][Dragonblight] Planning for the Future

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3550]
http://www.wowhead.com/quest=11960/planning-for-the-future

"Collect 12 Snowfall Glade Pups. Deliver them to Trapper Mau'i at Moa'ki Harbor."

When I click on the Pups I get no credit for picking them up. can not collect Pups.

**Comment by SwimzwithSharkz** [comment]
I also have thiz same issue and a bug post regarding this.
TY

**Comment by Anhaeyn** [comment]
I have this problem too.

**Comment by Oxyntes** [comment]
same here
