### ISSUE TITLE
Enhancement Shaman talent "Earthen Power" does not work correctly

### ISSUE THREAD

**Issue by Victabob** [Atlantiss/BugTracker#3552]
The Earthen Power talent does not function correctly. It doesn't remove all snares/roots. Examples: Frost Nova, Entrapement, Improved Hamstring. Also was buggy with improved hamstring, it would instead remove the slow effect of hamstring instead of the root.

**Comment by Bildo** [comment]
Read but rules or i will close it

**Comment by Jenovas** [comment]
Earthen Power DOESNT REMOVE ROOTS AND SHOULDNT.
Earthen Power remove snares.
Snare = reduced movement speed.
Root = stops the target from moving.
