### ISSUE TITLE
[EN][Quest][Uldum] Neferset Prison

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#3555]
http://www.wowhead.com/quest=27707/neferset-prison

Quest is working mostly as intended for one person. Problem is if you try to complete the quest with someone else in party. It only counts for the person who talks with the NPC and picks the dialog line. 
Other people in party have to wait for the NPC to respawn and talk with him again to complete their quest (which takes quite a few min)

**Comment by Bildo** [comment]
duplicate

**Comment by Nausica07** [comment]
IT IS NOT A DUPLICATE.

Please Bildo, read what player wrote before you jump into conclusions. Previous report was about something else, now same quest is bugged in different way.

**Comment by Bildo** [comment]
Yes it is duplicat, tehre is a thread about this quest here https://github.com/Atlantiss/BugTracker/issues/2524 and if you want add something write a comment. We don't want to have 10 reports about 1 quest, i think it's obvious.
