### ISSUE TITLE
[EN][Spell] Fire elemental totem

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#3568]
http://cata.openwow.com/spell=2894
The elemental cannot be controlled in any way, does not respond to /petattack command nor does it attack targets with a flame shock like searing totem does
Also it can by summoned in an arena using the call of the elements ability

Health and mana : According to simulationcraft source code the mana and health values on atlantiss are currently too high. Fire elemental is supposed to have 4643 + 7.5 x owner's stamina health and 8508 + 4.5 x owner's intellect mana. It should also have around 10.66 mp5 regen.
Fire Elemental scaling is off, currently elemental gets around 0.54 total spell power which is too low.
According to simulationcraft fire elemental should get 0.85 owner's int and  0.53419 of any pure spell power (currently only found on any +spellpower buffs or weapons) as spell power. Fire elemental spell damage is too low at the moment. Fire Elemental melee is also bit too low

Reference material : simulationcraft fire elemental source code : http://pastebin.com/1nRuEAJp

**Comment by mitim1** [comment]
#1859
#3110

**Comment by aneq** [comment]
Why did you close it? If anything, this issue combines the other two.
If anything, close the other two ones

**Comment by aneq** [comment]
UPDATED

**Comment by LaveGit** [comment]
Bump :3

**Comment by Jenovas** [comment]
Fire Elemental DMG fixed in rev  4703
