### ISSUE TITLE
[EN][Quest][Duskwood][Aliance]The Yorgen Worgen

### ISSUE THREAD

**Issue by Beatlejuicey** [Atlantiss/BugTracker#3570]
The dirt pile cannot be clicked and i cant complete the quest
http://www.wowhead.com/quest=26717/the-yorgen-worgen

**Comment by Quban** [comment]
Just click on the dirt pile and move a bit so trigger can spot you.

**Comment by Beatlejuicey** [comment]
Well 2 of us kept trying the other day and couldent get it to work..we had some weird stun animation on the first click then nothing, this quest is near the start of a chain that atm is stopping access to around 4-5 other quests been completed.

**Comment by Dean1989** [comment]
just move behind/around the house and you will get the credit, did it 2 times

**Comment by Beatlejuicey** [comment]
Perhaps you mistake my reason for posting this bugged quest.

e.g if I order a burger from mcdonolds they dont tell me to do a dance in order to recieve it.


I am taking the time to log bugged quests because I want to help the server to become as Blizz like as possible.

Telling me to run around a bit isent going to help the next 1000 players to get it done, and it isent going to do the servers reputation any good either.

I realy like this server and I think it has a lot of potential..but "quick fixes" such as this are not going to do much good in the long term..Apologies for the sarcasm but I hope you take this on board, thanks for your time.

Sent from Yahoo Mail on Android

**Comment by Dean1989** [comment]
the quest will get a tuneup for sure but i don't like your sarcasm because you are pretty much complaining about the quest is broken and you can't access the chain quests, instead it is doable without any effort. the first time i did it i didn't waste even a minute because is enough move your char 1cm over the pile and i discovered it just by walking to the pile, so don't be so dramatic since there isn't any major bug.

**Comment by Beatlejuicey** [comment]
I can see im wasting my time here, I will not bother in the future

Sent from Yahoo Mail on Android

**Comment by Quban** [comment]
i improved it, dont worry, fix just hasnt been applied to the main realm

**Comment by Beatlejuicey** [comment]
Great to here, keep up the hard work, thanks.

Sent from Yahoo Mail on Android

**Comment by Quban** [comment]
Ok, and thx to you too for reporting bugs :)
