### ISSUE TITLE
[EN][Quest][Ghostlands][Night Elf Plans]

### ISSUE THREAD

**Issue by Hica** [Atlantiss/BugTracker#3571]
Night Elf Plans: An'owyn cant be picked up. http://www.wowhead.com/object=181139/night-elf-plans-anowyn

**Comment by Dean1989** [comment]
add wowhead link

**Comment by LaveGit** [comment]
I completed this quest yesterday without problems.

**Comment by Hica** [comment]
yea quest is working it just has long spown time
