### ISSUE TITLE
[EN] [Character] My character is frozen / stuck in an animation.

### ISSUE THREAD

**Issue by pPinhoPT** [Atlantiss/BugTracker#3575]
So...I don't know what the hell happened but I can surely show you what is going on. As you can see in the images attached, my character is ALWAYS in that same animation. It is completely stuck / frozen. I tried dying, relogging, shapeshifting and nothing works. Before this bug happened all I did was the Twillight Highlands Arena. I hope I can get help asap since this is really annoying.  Thank you :)
EDIT: Now that I think about it I think this bug might be originated from the second boss of Twillight Highlands Arena "Sully Kneecapper". He did this spell on me where he grabbed me and never let me go until a dude killed him. Oh well...once again, hope you know how to fix it. Thank you for your atention :)
![wowscrnshot_061715_165218](https://cloud.githubusercontent.com/assets/12939637/8213498/b9dbefae-1511-11e5-9891-dfabba7e85c3.jpg)
![wowscrnshot_061715_165224](https://cloud.githubusercontent.com/assets/12939637/8213500/b9e05c56-1511-11e5-933d-24b85a6df5f0.jpg)
![wowscrnshot_061715_165227](https://cloud.githubusercontent.com/assets/12939637/8213499/b9df9172-1511-11e5-9726-b86e31e13848.jpg)
![wowscrnshot_061715_165230](https://cloud.githubusercontent.com/assets/12939637/8213501/b9e2d71a-1511-11e5-960f-083b3303c35f.jpg)

**Comment by blinkmaster** [comment]
i would love to have that bug XD !

**Comment by imeasytokill** [comment]
clear cache dont help ?

**Comment by pPinhoPT** [comment]
I was logged off for about 1 hour and half and now it seems to be fixed. Thank you all <3<3 But I still don't know how this happened nor how it got fixed :p

**Comment by pPinhoPT** [comment]
I used hearthstone back to Orgrimmar and the bug reappeared...I really don't know what to do.

**Comment by pPinhoPT** [comment]
Deleted WTF and Cache folders. Didn't work either.

**Comment by mrkariox** [comment]
Arena in TH makes that bug. Only gm in game can help, i had same problem. Write a ticket and wait.

**Comment by pPinhoPT** [comment]
Ok, thanks mrkariox. I really can't stand this bug. Hope a GM can see this asap tho :/

**Comment by pPinhoPT** [comment]
A GM talked to me ingame and fixed it instantly <3<3 Love you all and I hope you have a great day :) Atlantiss is the best!! <3<3
