### ISSUE TITLE
[EN][Druid] Thorns does wrong damage in feral forms

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3577]
The Druid spell Thorns (http://cata.openwow.com/spell=467) does not do the damage it should while in either bear or cat form.
What happens: Thorns gets cast in caster form -> Thorn's damage is appropriate while in caster (around 300 damage) -> shift to cat/bear form -> Thorn's damage is still around 300.
What should happen: Thorns gets cast in caster form -> Thorn's damage is appropriate while in caster (around 300 damage) -> shift to cat/bear form -> Thorn's damage is around 2,3k (the exact damage can be seen in the tooltip while in a feral form).

While the tooltip for the spell shows the correct damage while the player is in either cat or bear form, the buff does not update upon shifting.

Proof: http://us.battle.net/wow/en/forum/topic/3530333852#16 and that most other Cataclysm private servers (including Warmane post merge with Arena Tournament which had this working correctly) have this working like I described.

**Comment by Dean1989** [comment]
nice report, i didn't know about this. i did a little search and i found others topics about it:
http://us.battle.net/wow/en/forum/topic/2966896670#7
"thorns cast from cat form as a feral are extremely valuable vs duel wielding melee, ie- rogue/feral/frost dk/enhancement(not that you see them in arena now anyway). Usually reflects 3k ish damage per hit for the duration of the buff. Some may argue teh gcd isnt worth spending, but, hey.... 15+ melee hits during its duration * 3000 = 45k (approximate, dont troll me please :P) free damagez."

plus here there is a formula for cata 4.0.3
http://us.battle.net/wow/en/forum/topic/1083358664#4
"The coefficient in 4.0.3a (which is nerfed by 66%) is: 

[ 16.8% of Spell Power + 178.58 ] or [ 16.8% of AP + 178.58 ] depending on the highest."

**Comment by Isuel** [comment]
confirmed, always wanted to report it but i forgot. xd

**Comment by Jenovas** [comment]
Fixed in rev 4510
