### ISSUE TITLE
Tauren Racial Passive [Cultivation]

### ISSUE THREAD

**Issue by Torimas** [Atlantiss/BugTracker#3578]
The Cultivation Tauren Racial Passive does not work properly.
It does give the +15 maximum herbalism skill, but it does not increase the Tauren's speed when gathering herbs.
On Blizzard servers, Tauren gathered herbs in 0,5 seconds. Here they do in 2 seconds, which is just as fast as every other races herbalists.
Now my suggestion in order to have an even more blizzlike experience, the Tauren Racial Passive [Cultivation] needs to work as intended.

**Comment by Wolffenstein** [comment]
https://github.com/Atlantiss/BugTracker/issues/1497
