### ISSUE TITLE
[EN] [General Caster NPC A.I.] [This bug should have high priority because it's affecting all caster mobs]

### ISSUE THREAD

**Issue by peacebringer** [Atlantiss/BugTracker#3582]
Hello Atlantiss. This is my first bug report :).
I want to report that all caster mobs have some issues considering their artificial intelligence.

When you attack some caster (range) mob and when you hide behind some object (behind a wall for example) in order to be out of his line of sight (out of LOS), that caster mob should run towards you (now that mob just stands still in one place) and when that caster mobs finds a spot from which he can attack you with his spells or some other range attack, he should do that. Proof, watch from 1:43 (its from vanilla wow, but the mechanic is the same in all expansions) - https://www.youtube.com/watch?v=pO7geZF8SQ8 

Maybe this one situation is bugged too, I didn't test it, but I will report it also because it's almost the same case as I already described above. For example if you cast silence on some caster mob (so not just interrupting the spell but silencing them for some period of time and preventing them to cast spells from that spell school) that caster mob should run to you to engage you in melee combat (now that caster mob just stands still in one place) Proof, watch from 1:16 - https://www.youtube.com/watch?v=pO7geZF8SQ8 

Using immunites when a caster mob is casting a spell on you should also make ranged mobs to come close to you and engage you in melee combat. Proof, watch from 0:56 - https://www.youtube.com/watch?v=h2uWcQtssh8

Mob spreading is not working on Atlantiss also, when you have many mobs attacking you, they should not overlap eachother, but rather find a free spot around you. This video will explain you better what I am talking about. Proof, watch from 2:18 - https://www.youtube.com/watch?v=h2uWcQtssh8

I am not ambassador of any private server, I just could not find better videos representing and explaining these buggs. These buggs are pretty serious (except maybe for mob spreading) because they are affecting all caster mobs in the world.

Keep up the great work Atlantiss :)

**Comment by Dean1989** [comment]
#1018

**Comment by Tj20** [comment]
As Dean pointed out it has already been reported. I agree, it is an issue - probably the most visible one this server has, apart from pathing issues and the in-combat bug (which is also often caused by unmoving casters).

The problem is, as Wolfenstein explained: There is a fix available, but someone would have to sort through the whole mob database (probably thousands and thousands of mobs) by hand and change a flag on the affected creatures, which would be not complicated, but a lot of work.
