### ISSUE TITLE
[EN][Quest][Azshara] Fade to Black

### ISSUE THREAD

**Issue by peacebringer** [Atlantiss/BugTracker#3583]
Hello. This quest is bugged at the moment, I tried several times with taking and abandong the quest but dragon Malicion is just flying above and he doesn't attack me when I kill Lord Katrana. Here is the video how this quest should be scripted - https://www.youtube.com/watch?v=K4IR_hmp_yE
http://www.wowhead.com/quest=24467/fade-to-black

**Comment by Angelo-DM-** [comment]
Confirm! Bugged Quest! You can kill [Twilight Lord Katrana](http://www.wowhead.com/npc=36638) but after that, [Malicion](http://www.wowhead.com/npc=36649) should attack you and [Azuregos](http://www.wowhead.com/npc=36676) should come in your help and kill the dragon for you.

Instead nothing happens! I've noticed too that there are two Azuregos near the Northern Roketway terminus: one is flying and one is half out the ground and half behind the ground.

![wowscrnshot_060916_024014](https://cloud.githubusercontent.com/assets/10468828/15915750/3470d0d8-2dec-11e6-8014-a4b4b19c93fc.jpg)

**Comment by Sorvirus** [comment]
Bump, is there anybody who can solve this?

**Comment by Dranerys** [comment]
Bump! Confirming that Malicion is still untargetable after killing Twilight Lord Katrana.

**Comment by Bildo** [comment]
fixed
