### ISSUE TITLE
[EN] [NPC] [Shattrath] Anduin Wrynn <PTR Glyph Vendor>

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3585]
Anduin Wrynn is in Shatt on the main server. 
He shouldnt be here.

Loc: 58,46
![wowscrnshot_061715_231937](https://cloud.githubusercontent.com/assets/12252441/8223568/93863a72-1547-11e5-907b-c4888ddc426b.jpg)

**Comment by Bildo** [comment]
should dissapear after crash

**Comment by Thefakemccoy** [comment]
He is actually still here

**Comment by Bildo** [comment]
AFTER CRASH

**Comment by Thefakemccoy** [comment]
well the server crashed a few mins ago so i assumed that one

**Comment by Bildo** [comment]
umm nope, server uptime 1h 30min
