### ISSUE TITLE
[PL][QEST][Deepholm][Battlefront Triage] 

### ISSUE THREAD

**Issue by Dariwa99** [Atlantiss/BugTracker#3586]
Qest o podanej nazwie nie działa, polega na zabandażowaniu npc klęczących. Być może qest item sie zepsuł lub hp npc powinno być do połow, a po bandażowaniu ich nic się nie dzieje.  Dodam, że qest jest pilny bo bez niego nie idzie dostać kolejnych i nie pozwala na dokończenie lore w deepholm.

**Comment by Myivo** [comment]
Quest już jest zgłoszony. ^^ https://github.com/Atlantiss/BugTracker/issues/3379

Napisz ticket w grze.

**Comment by Dariwa99** [comment]
Ticket napisany czekam może ktoś się odezwie...
