### ISSUE TITLE
[EN][NPC] Tyrande Whisperwind

### ISSUE THREAD

**Issue by Tarvo27** [Atlantiss/BugTracker#3587]
She's missing in the Temple of the Moon, next to Malfurion, can't complete quest called 
[Home of the Kaldorei] http://www.wowhead.com/quest=14039/home-of-the-kaldorei

Please fix.

**Comment by Drutmaster** [comment]
Maybe horde killed her? Wait a while, she should respawn soon

**Comment by Tarvo27** [comment]
Nope, checken just now, 7 hours have passed, no Tyrande here.

**Comment by Myivo** [comment]
Tyrande is in the Temple of the Moon.

**Comment by Tarvo27** [comment]
Either I am blind as fuck or she's invisible, I can't see her on the balcony next to Malfuirion.

**Comment by Myivo** [comment]
Write ticket in-game.

**Comment by Tarvo27** [comment]
Tyrande has spawned.
