### ISSUE TITLE
[Quest][Redridge Mountains] Saving Foreman Oslow (26520

### ISSUE THREAD

**Issue by ElBondi34** [Atlantiss/BugTracker#3588]
Hello , this quest is bugged because the boulder is not spawned . I think Need to spawn this boulder work this quest pls .
Link : http://www.wowhead.com/quest=26520/saving-foreman-oslow
Item : http://www.wowhead.com/item=58895/ettin-control-orb
Spell : http://www.wowhead.com/spell=80704/control-ettin
JPG : http://wow.zamimg.com/uploads/screenshots/normal/176044.jpg

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2589
