### ISSUE TITLE
[EN][Core Mechanic] Resurrection after release

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3589]
You cannot res someone after they have released. As far as I know this is recent behavior and wasn't happening a month or two ago. Not sure what you would need links for. Its pretty easy to replicate just die and then release and have someone try to res you.

**Comment by zeoos** [comment]
Yes, you should be able to ressurect a player that has released.
Quote from Wowpedia:

Players can be resurrected whether or not they release. If the dead player has not released, the resurrecting player can select the body and cast the spell.

Source: http://wow.gamepedia.com/Resurrect

**Comment by aneq** [comment]
While being ressed after releasing works, it works only if the rezzer targets the corpse. If the target is selected via raid frames it won't work

**Comment by zeoos** [comment]
Ok, i'll test this next time i'm going to be in a dungeon.
