### ISSUE TITLE
[EN][NPC][Hellfire Peninsula]Fulgorge(ID 18678)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#3590]
NPC not come out of the ground.I could not find any other NPC which might be this one as other are comimg out.

![wowscrnshot_061815_222246](https://cloud.githubusercontent.com/assets/10282971/8240036/95474754-1608-11e5-8877-093719734d81.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1196

**Comment by Aival94** [comment]
For me all of the Tunneler were coming out so i thought that this rare must be not attacking,
