### ISSUE TITLE
[EN] [Quest] [Dragon Blight] Not in Our Mine

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3596]
WoWhead Quest Link:
http://www.wowhead.com/quest=12269/not-in-our-mine

I made a pass through the mine there are only 5 miners in the mine. You need to collect 10 miner's cards.

Item:
http://www.wowhead.com/item=37411/wintergarde-miners-card

NPC:
http://www.wowhead.com/npc=27401/risen-wintergarde-miner

in the pic you can see there is more than 5 in the mine.

**Comment by JessicaCartsey** [comment]
It does not stop you from completing the quests however. Still, waiting can be a bit of a pain sometimes.

**Comment by Thefakemccoy** [comment]
No its completeable but its missing alot of mobs in the mine.
