### ISSUE TITLE
[EN][NPC] Warchief Rend Blackhand

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#3599]
This NPC is almost missing from the Upper Black-rock spire except seen riding his mount in dead form.

This also renders the quest The False Warchief #3598 incomplete.

wowhead link: [Warchief Rend Blackhand](http://www.wowhead.com/npc=10429/warchief-rend-blackhand)

**Comment by Tj20** [comment]
I've already mentioned it in #1585, but it's true: Gyth doesn't use his [Summon Rend Blackhand](http://www.wowhead.com/spell=16328/summon-rend-blackhand#comments) spell even if you make sure to kill him very very slowly so he has plenty of time to use it.
