### ISSUE TITLE
[EN][Quest] Drive-By Piracy

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#360]
Drive-by Piracy (http://www.wowhead.com/quest=26649) can be completed, but it's not blizzlike, at all.

2 skills are missing from the canon boat, and 4th skill, one that returns you to the shore, doesn't work.

You just use 3rd skill to shoot, however, there's a lot of issues.

- There's no canon animation or sounds
- There's no visible canon ball flying, when you fire.
- There's no shooting indicator, you're pretty much aiming with this small green aoe indicator.
- Previous boats that were spawned keep spinning on their own in circles, and at times are dropping into the water, even your own boat, when it stops for you to shoot, first sinks, and then raises up, and then you can shoot normally.
- Mobs that you're supposed to shoot at are dropping through the structures and into the water (I'm guessing this is a collision issue, so you can't do much about it, but still)

Here's how the quest works - https://www.youtube.com/watch?v=kXd51y4rmjk

**Comment by simonnorbert23** [comment]
Hello. I just want to confirm Satyr87's description of the broken quest. Because of this bug it is impossible to gain the Cape of Stranglethorn quests achievment.

**Comment by cosminush** [comment]
The quest is working in some way, but the char get stuck under the boat and can't shoot targets from petrol gathers, and breath is decreasing, and after some time die.

**Comment by ahtebe** [comment]
Just like cosminush said, you get stuck under the boat and since your underwater, the canon aoe circle doesn't target the workers above water. 

This a pretty important quest since not completing it prevents earning the Cape of Stranglethorn quests achievment.

**Comment by lourrific** [comment]
They are high up on the oil rigs and I can not be reached manually. Come back in another 20 levels when you have a flying mount and then try to kill them. Not sure if it can be done with flying mount because I don't have one yet. This will probably ruin Loremaster progression achievement.

**Comment by ahtebe** [comment]
It is completable, even before having flying mounts. Just need a ranged attack to hit one of the workers and they will all come. However, it will be pretty tough beating a pack of them at once at the recommended level for the zone.

**Comment by rawhunger** [comment]
I've tried the ranged weapons that I have (gun, bow, crossbow) and none can reach the mobs.  So how is this quest "completable" exactly?

**Comment by ahtebe** [comment]
AoE stuff like Rain of Fire (warlock) will reach them. For melee classes try taunt, throw weapon... (not sure if they have 40yd range).

**Comment by rawhunger** [comment]
I am a melee class, and I can tell you that Heroic Throw doesn't reach.
So, I'm stuck I guess.

**Comment by worgenman** [comment]
yes please make it autocomplete at least

**Comment by nenormalen** [comment]
Ok, today I've done this quest... So I will tell you how i managed to. First of all you have to be lvl 60 or higher with learned flying license and flying mount. Then go to the platforms and aggro the mobs, then they will fall into the water and you will be able to kill them (it will take you maybe 5-7 platforms to kill the 75 mobs). Another time consuming thing is that every time when you kill them you have to swim to the shore, mount and go to another platform. I've managed to do the quest for maybe 15-20 min at all (I believe). While I was doing it for myself I helped another player to finish the quest too (he was low lvl). That's how you do it. Hope I helped a bit.

**Comment by Spatsa** [comment]
Just tried this quest today. It still drags you under the boat and cannot be completed that way, but I also found out if you issue the command to return to shore, it will force you under the map when you've returned. 
![wowscrnshot_102015_181609](https://cloud.githubusercontent.com/assets/15221619/10622949/be6ae2b0-7758-11e5-98f1-9f26717b8292.jpg)

**Comment by Satyr87** [comment]
why you people didnt read what i wrote ?

**Comment by Ambiorixa** [comment]
https://github.com/Atlantiss/BugTracker/issues/3973

**Comment by Bildo** [comment]
fixed

**Comment by Shisai** [comment]
unfortunately still not fixed :/

**Comment by Xenerus** [comment]
Can't even talk to the Bloodsail Oarsman now.

**Comment by siwy92** [comment]
stil not work ..

**Comment by Mihu44** [comment]
same

**Comment by BAndysc** [comment]
I have updated the script to use smooth waypoints, but I forgot to upload the script itself :dancer: 

So it didn't worked properly now, because the waypoints were new, but script was old. Uploaded the new script in rev [5043]. Sorry

**Comment by siwy92** [comment]
where is this fix ?? stil dont work..

**Comment by BAndysc** [comment]
5043 rev is not yet live

**Comment by siwy92** [comment]
Forgive for the spam but I am awaiting as many as 3 days from expem to this q... and whether it is known when rec is live ?

**Comment by BAndysc** [comment]
When there are few upcoming revisions, but currently only my 5043 rev is waiting in the queue.

**Comment by visi212** [comment]
Rev 5043 is up and quest still doesn't work.

**Comment by BAndysc** [comment]
I swear, it must be an unlucky quest :D Now the bug was: Bloodsail Oarsman entered the boeat instead of player, right? Because at the moment I am not sure if I have the same script as on live server. rev 5048

**Comment by visi212** [comment]
Yep he enters boat instead me and departs :) it's really funny but still buged

**Comment by BAndysc** [comment]
Should be fixed in rev 5048, I do not know how it was possible that the current bug has happend

**Comment by visi212** [comment]
hehehehe still buged ;P

**Comment by BAndysc** [comment]
Finally 😂

**Comment by visi212** [comment]
Achievement done :P

**Comment by Cellhawk** [comment]
Very well done.

**Comment by forgethebald** [comment]
Bugged as 4 of august , you can talk to the oarsman but when you start the boatride you get stuck on the beach only being able to shoot your cannon there
