### ISSUE TITLE
[EN][Instance][TBC] The Underbog doesn't grant Sporeggar reputation

### ISSUE THREAD

**Issue by Juau** [Atlantiss/BugTracker#3603]
As per [this](http://www.wowhead.com/zone=3716/the-underbog) wowhead article, the mobs inside The Underbog should grant reputation with Sporeggar until Exalted but at the moment it doesn't work accordingly in Atlantiss.

**Comment by Thefakemccoy** [comment]
Killing mobs and bosses grant Cenarion Expedition reputation, capped to Honored in normal mode. This is also a good source for Sporeggar reputation: it gives reputation through Exalted in normal mode and an NPC is at the entrance for repeatable  Sanguine Hibiscus turnins.

What it says 

How you should read it 

Killing mobs and bosses grant Cenarion Expedition reputation, capped to Honored in normal mode. This is also a good source for Sporeggar reputation: it gives reputation through Exalted in normal mode by completing  the repeatable quest.  Sanguine Hibiscus turnins

**Comment by Thefakemccoy** [comment]
Plus i have never seen killing these mobs in any expansion give rep to sporeggar

**Comment by Aival94** [comment]
It seems that mobs also give reputation as well as bosses in normal mode,

http://us.battle.net/wow/en/forum/topic/3881884865

**Comment by Thefakemccoy** [comment]
Ok i stand corrected on that one guess i never really payed attention to that rep.

So on normal Rep is as follow
Cenarion Expedition 7
Sporeggar 21

Heroic 
Cenarion Expedition 15
Sporeggar 45

**Comment by Juau** [comment]
This (along with Sanguine Hibiscus turn ins) is the fastest way to grind Sporeggar reputation so a fix would be quite nice.

Can anyone explain me how hard it is/can be to fix it?

**Comment by Thefakemccoy** [comment]
It could be a 4.3 issue. The game is running on a 4.3.4 client but they are only up to 4.1 ingame. SO it could be that. Some 4.3 things are in some arent.
