### ISSUE TITLE
Stood in the Fire (achivement) bug

### ISSUE THREAD

**Issue by Deekin789** [Atlantiss/BugTracker#3605]
Saw Deathwing blowing fire in Tanaris and i stood in the fire, in retail the fire deals damage and if you die you got the achievement [Stood in the Fire]  (also obtainable by dieing in Dragon soul but lvl 5's can get the achievement this way)

**Comment by MasterK15** [comment]
You need to be killed when Deathwing, Flame don't deal any dmg, You must be in location when Deathwing come

**Comment by aneq** [comment]
any broken english aside it is indeed bugged. walking into fire left by deathwing should give you the achievement (and kill you ofc :D )

**Comment by Clarkiez96** [comment]
Can confirm the fire does inflict damage, like any fire and dying to this should give achievement

**Comment by zeoos** [comment]
Can confirm that it works, just got it on char **Silentstep**

**Comment by Bildo** [comment]
correct title

**Comment by Illusionist87** [comment]
This is not fixed. I stood in fire left by Dethwing today (28.06.2015.) and it didn't do any damage, or give the achievement.

**Comment by zeoos** [comment]
Maybe Deathwing passed you allready. Just yesterday, one guildie got it. So it works.

**Comment by Illusionist87** [comment]
You can get the achievement only if Deathwing kills you directly. Standing in fire left behind him doesn't do anything.
