### ISSUE TITLE
 [PL][Shaman][Spell] Healing Stream Totem + Totemic Wrath

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#3606]
Link do spella: http://cata.openwow.com/spell=5394
Link do talentu: http://cata.openwow.com/spell=77746

Talent Totemic Wrath zwiększa spell power o 10%, mimo tego Healing Stream Totem leczy po tyle samo co bez niego

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/1320
