### ISSUE TITLE
[EN][Bugged Mobs][Southern Barrens] The Overgrowth

### ISSUE THREAD

**Issue by ffjjdd** [Atlantiss/BugTracker#3607]
Link to the mob on Wowhead - http://www.wowhead.com/npc=37092

The mobs called "Outgrowth" can't be killed while they are in the river (at least the deeper parts where they swim), because they constantly reset when you attack them.

When they are outside the river it is fine.

ACORE3 - Rev. 4466

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6568-npc-the-overgrowth/
