### ISSUE TITLE
[PL][Quest][Swamp of Sorrows] Marking the Fallen

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#361]
Gdy używam flago na martwych żołnierzy orków ( http://www.wowhead.com/quest=27856 )  to flaga się nad ciałami pokazuje się, ale nie zalicza mi postępu zadania.

Link: http://www.wowhead.com/quest=27856

**Comment by ahtebe** [comment]
Still have this issue.

**Comment by Thefakemccoy** [comment]
My 3rd toon on this quest i did it after a server crash. At first every one i did worked but as i was doing this i was going around kill the mobs for the other quests. I ended up coming back to the 2nd body i had dropped the flag on and it didnt count. I think what is happening is once the flag is dropped on the body they body wont despwan making it perma flagged as triggered eventually leavinh non doable.

**Comment by martinelrey1979** [comment]
dobry dla mnie, nawet nie zakończyć moją misję na więcej niż paznokci bantera tysiąc razy będę zresetować komputer po prostu nie zakończyć moją misję miejmy nadzieję rozwiązać go lub przynajmniej mieć pomysł, jakiego ogólnym błędem wszystkich, że jeśli zakończyć, a innym nie

**Comment by martinelrey1979** [comment]
good to me even not complete my mission for more than you nail the bantera thousand times I will reset my pc just not complete my mission hopefully resolve it or at least have an idea of what the general error of all, that if they complete some and not others

**Comment by Hacker--x** [comment]
Still not completable

**Comment by Bildo** [comment]
fixed
