### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by dsuder32** [Atlantiss/BugTracker#3611]
Hello,

I downloaded the WoW game from the Atlantiss website and when I try to exp in lands like Hellfire Peninsula, Zul'Drak, Icecrown or try to teleport to Exodar, my game crashes. I have attached an image with the crash window. Now my 2 characters are stuck on those maps and I can't even log on to them. Please help.
![crash](https://cloud.githubusercontent.com/assets/12986801/8271372/12e7adfe-1814-11e5-9307-daec1d895ad9.png)

**Comment by Tj20** [comment]
[Here](http://community.atlantiss.eu/index.php?/topic/3865-how-to-fix-error-132-and-error-134/) is a forum thread with possible solutions for the errors 132 and 134.

Error 134 means that the files mentioned in the error window are probably corrupt (expansion2.MPQ in your screen). Try downloading that file again or if you're using the streaming (mini) client it might be sufficient to delete/move that file to another folder to make the game downloading the file again.
