### ISSUE TITLE
[EN][Quests][Shadowmoon Valley]The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Juau** [Atlantiss/BugTracker#3612]
[This](http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron#comments) quest is a part of que Netherwing faction questline.

How it should work: You speak with [Sar'this](http://www.wowhead.com/npc=23093/sarthis) and kill the four elementals it spawns. The last one drops [Flawless Arcane Essence](http://www.wowhead.com/item=32822/flawless-arcane-essence)

How it is: You speak with the NPC but it doesn't spawn anything.

**Comment by zeoos** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/2426

**Comment by XrayAlert05** [comment]
bump. 
U can't speak to that npc no interaction.

**Comment by Hallieth** [comment]
yup. still not working.
