### ISSUE TITLE
[PL][Event] Midsummer

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#3613]
http://www.wowhead.com/npc=25740/ahune
http://www.wowhead.com/item=54536/satchel-of-chilled-goods

<s>nadal nie ma worka </s>

<s>Loot z bossa potrzebuje update do 353ivl
http://cata.openwow.com/item=69771
http://cata.openwow.com/item=69769
http://cata.openwow.com/item=69770
http://cata.openwow.com/item=69768
http://cata.openwow.com/item=69767
http://cata.openwow.com/item=69766

Brak ognisk z Cata
http://www.wowhead.com/achievement=6012
http://www.wowhead.com/achievement=6014
http://www.wowhead.com/object=208093
http://www.wowhead.com/object=208094
http://www.wowhead.com/quest=29030/honor-the-flame
http://www.wowhead.com/object=208184
http://www.wowhead.com/object=208188
http://www.wowhead.com/object=208089
http://www.wowhead.com/object=208090</s>

**Comment by Thefakemccoy** [comment]
Since you have a ticket open i wanted to also add the Event Boss Ahune is dropping lvl 80 gear.
http://www.wowhead.com/npc=25740/ahune

**Comment by xolon** [comment]
Every item from world events should be 200-216 ilvl before firelands is released

**Comment by Bildo** [comment]
Umm nope

**Comment by sunshineinabox** [comment]
The chilled goods still aren't working. You don't receive them after you kill him.

**Comment by Bildo** [comment]
Yea i realized that satchel doesn't drop after ending df. I thought that satchel doesnt have loot so i fixed loot from satchel. Fixed to Midsummer Festival will appear on tuesday or wednesday

**Comment by armengar** [comment]
So everything thats not alright with the Midsummer fest like the broken fires in Stranglethorn and the Ahune related stuff will be working fine in the next  2 days?

**Comment by RelmAtlantiss** [comment]
Southern Barrens and Northern Stranglethorn bonfires are missing for both factions.

**Comment by Bildo** [comment]
@armengar everything that is reported here, i'm not playing on atlantiss as much as i would so i don't know bugs.

**Comment by armengar** [comment]
@Bildo Alright then, I checked the links shared in the original post and I think a few of the Npcs and Fireplaces in Azeroth are missing aswell

Both the Horde and Alliance Npc and Fire in Northern Stranglethorn

**Comment by lelokrul** [comment]
Still doesn't drop daily satchel

**Comment by Haz3L** [comment]
Wciąż nie ma ogniska ani npc w Southern Barrens.

**Comment by jsembatman** [comment]
Brak:
http://www.wowhead.com/object=207982/alliance-bonfire
http://www.wowhead.com/object=207983/horde-bonfire
http://www.wowhead.com/object=207986/horde-bonfire
http://www.wowhead.com/object=207985/alliance-bonfire

**Comment by darklord88** [comment]
Some people got problem with burning steppes.I did quests there and when i want go to fires those disappears in burning steppes(visual bug)

**Comment by Aival94** [comment]
These achievements are not updated to 4.1.
[Flame Warden of Eastern Kingdoms[(http://www.wowhead.com/achievement=1022/flame-warden-of-eastern-kingdoms)

Missing:
[Honor the Flame](http://www.wowhead.com/quest=28929/honor-the-flame)
[Honor the Flame](http://www.wowhead.com/quest=28925/honor-the-flame)

**Comment by Aival94** [comment]
These achievements are not updated to 4.1.
[Flame Warden of Eastern Kingdoms[(http://www.wowhead.com/achievement=1022/flame-warden-of-eastern-kingdoms)
Missing:
[Honor the Flame](http://www.wowhead.com/quest=28929/honor-the-flame)
[Honor the Flame](http://www.wowhead.com/quest=28925/honor-the-flame)

[Flame Warden of Kalimdor](http://www.wowhead.com/achievement=1023/flame-warden-of-kalimdor)
Missing:
[Honor the Flame](http://www.wowhead.com/quest=28932/honor-the-flame)
[Honor the Flame](http://www.wowhead.com/quest=28928/honor-the-flame)

**Comment by sunshineinabox** [comment]
The satchels still aren't working. I do not get it after killing him.

**Comment by Bildo** [comment]
I just said wait, everything's gonna be fixed just be patient (and no it's not happen on the last day )

**Comment by sunshineinabox** [comment]
Ah just wanted to report it not being fixed after the hotfix of course no rush or anything. I understand you guys are busy.

**Comment by Bildo** [comment]
Ok i add these npcs:
51582,
51574,
51588,
51606,
25941,
51602,
51585
and objects:
207989
207990,
207992,
207991
anything else ?

**Comment by Bastion** [comment]
worek popraw bo sie z kwiatkami nie wyrobie ;;

**Comment by armengar** [comment]
@Bildo the Horde fire object in Grom gol camp , Northern stranglethorn

**Comment by darklord88** [comment]
Burning steppes fires still disapper who have finished quests there.

**Comment by Aival94** [comment]
I should probably be more specific about the outdated achievement.In 4.1 patch they change some locations of the already zones quests and furthermore add these 2 quests i wrote to the achievements i said.Here these achievements not have them at all as need to go there and do the quests(honor them or extinguise them)

Proof:
![wowscrnshot_062415_153804](https://cloud.githubusercontent.com/assets/10282971/8330138/04be582e-1a88-11e5-8727-556be5d98cec.jpg)
![wowscrnshot_062415_153812](https://cloud.githubusercontent.com/assets/10282971/8330139/04befbda-1a88-11e5-96a8-8d40000e9d70.jpg)
![wowscrnshot_062415_154030](https://cloud.githubusercontent.com/assets/10282971/8330140/04c20cc6-1a88-11e5-92f1-6b69c763de60.jpg)
![wowscrnshot_062415_154041](https://cloud.githubusercontent.com/assets/10282971/8330141/04c52bb8-1a88-11e5-88c6-13d3d25cb273.jpg)

**Comment by Illusionist87** [comment]
Jut wanted to add that http://www.wowhead.com/achievement=272/torch-juggler is bugged too.

**Comment by Bildo** [comment]
idk if i added everything, let me know ok ? satchel still not working (it's harder to fix than i thought xd)

**Comment by KieraHorde** [comment]
Hello,

Would like to know when NPCs in Southern Barrens and Northern Stranglethorn will be added?

Cheers!

**Comment by Bildo** [comment]
check after update >.<

**Comment by armengar** [comment]
on my way

**Comment by armengar** [comment]
Npcs and Fire objects in Northern Stranglethorn are still missing

**Comment by Bildo** [comment]
Daaamn CHECK AFTER UPDATE

**Comment by armengar** [comment]
ay guys we pissed him off finally lol 

when is the update going live?

**Comment by Bildo** [comment]
after dc changes should be on realm

**Comment by armengar** [comment]
cheers,will report after a crash

**Comment by Aival94** [comment]
Achievement [Torch Juggler](http://www.wowhead.com/achievement=272/torch-juggler) is working just fine.I think the only bug is that while doing it does not count your torches but when you reach 40 you get the ach normaly.(sorry bildo for so much work we give you.I think all appreciate your hard work :D )

**Comment by Haz3L** [comment]
Extinguishing Kalimdor - Southern Barrens still doesn't work on Horde side.

**Comment by armengar** [comment]
horde bonfire in Southern Barrens is still broken, the bonfire is there and it has a ! mark but doesnt do anything when clicked on

**Comment by Bildo** [comment]
ok give me a few minutes

**Comment by Bildo** [comment]
The rest is working ?

**Comment by armengar** [comment]
Northern Stranglethorn for both sides seems to work, the Alliance NPC in southern barrens does work i believe only the bonfires on both sides are acting weird

**Comment by Bildo** [comment]
ok and what about satchel ?

**Comment by armengar** [comment]
satchels are now obtainable after killing ahune

**Comment by LaveGit** [comment]
The bonfire for Horde to extinguish the flame in Southern Barrens still doesn't work. The bonfire is now there, as well as the quest marker, but the quest is not available to take. You can't click the bonfire.

**Comment by Bildo** [comment]
Yes i know i just can't figure it out why it's not working.

**Comment by KieraHorde** [comment]
Is there any way to overcome the issues with Fire in Southern Barrens? Maybe an extra NPC? Or there is a solution already?

**Comment by Bildo** [comment]
Ohh i forgot to say, I manage to fix it, wait for an update.

**Comment by LaveGit** [comment]
Great to hear ! :))

**Comment by Aival94** [comment]
Bildo sorry to ask but will the outdated achievements will be updated in this year event or no?(i ask because i wait for them to  be updated(if possible) to finish them)

**Comment by armengar** [comment]
why cant u finish them now?
 the outland achievement is completely doable

**Comment by Bildo** [comment]
Isn't achievement 'The Flame Keeper' achievable (besides Southern Barrens bonfires ofc) ?

**Comment by KieraHorde** [comment]
The rest works fine, as long as I could do everything. This Alliance Fire
in Southern Barrens doesn't let to get the full event achievement

**Comment by Nukeey** [comment]
@Bildo no, you need the southern barrens for the achievement.

**Comment by Bildo** [comment]
Read carefully

**Comment by Nukeey** [comment]
Ah, everything else works now.

**Comment by Dean1989** [comment]
i don't see the satchel on my char http://i.imgur.com/YU4sbyy.jpg

**Comment by Bildo** [comment]
southern barrens works now ?

**Comment by ThordAelo** [comment]
Still doesn't work :(

**Comment by Bildo** [comment]
WEIRD AF

**Comment by Bildo** [comment]
Ok i know what's happend :D Fix it's not live yet xd

**Comment by armengar** [comment]
so we're waiting for a crash?

**Comment by Bildo** [comment]
i don't know crash or update

**Comment by KieraHorde** [comment]
Hello!

I've seen a player who got the full achievement yesterday. He said that he
wrote a ticket to GM and later got teleported where he reached an NPC with
a quest that finished the last - Southern Barrens.

Maybe there is a way to put an extra NPC next to that Alliance Fire in
Southern Barrens so that Horde could get the achievement?

Kiera

**Comment by Bildo** [comment]
What ? Ok i need to talk with someone... Bonfire will work after crash geeeeeez ppl

**Comment by sunshineinabox** [comment]
There is an issue with the event script itself. Either the spawn rate or the number of adds spawned is pretty messed up. You can check the video I posted above. You have 3-4 adds up at a time. The level and hp seems to be corrected for adds and ahune now tho.
