### ISSUE TITLE
[Quest] Last Rites

### ISSUE THREAD

**Issue by Duqino** [Atlantiss/BugTracker#3614]
Killed the npc but i cant claim my price.

Thassarian doenst go back to the place where he should be going to so i can claim my price.
http://gyazo.com/1cfade9d45ed517c6ead6c7a78bbca8f
He just stands around and i cant talk with him.

Tharrasain doenst help with killing the npc.

Also this doenst look goo either

http://gyazo.com/b4b6c8887ddcd30a98bcd1c22922b96f

Looks like the quest doesnt reset.

**Comment by Duqino** [comment]
Update:

Found out you can claim your price at the start where the quest begins.

**Comment by Tj20** [comment]
#720
