### ISSUE TITLE
[EN][Raid] Throne of the Four Winds, Conclave of Wind (Heroic). Nezir spams Ultimate.

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#3615]
## **What is happening:**

When both Anshal and Rohash are dead, Nezir keeps on using his ultimate ability endlessy with only a few second delay inbetween.

## **What is supposed to happen instead:**

Nezir only does his ultimate when he reaches 90 energy naturally.

http://www.wowhead.com/npc=45871/nezir#encounter

**Comment by xolon** [comment]
Never happen'd to us

**Comment by Frainzil** [comment]
We usually kill nezir during the 3rd ultimate he does so i'm not really sure if we would have had the same bug. I think gm's can check this pretty easily if it's really bugged or not.
