### ISSUE TITLE
[EN] [CORE] Alchemy

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3618]
So i did the old alchemy master quest from TBC ones. Once i hit high enough lvl and skill in alchy i was given the cata quests. I am already a alchemy transmute master and the trainer is offering me the quest in SW.

First pic shows my transmute spec:
![wowscrnshot_062215_104150](https://cloud.githubusercontent.com/assets/12252441/8284528/4e9816ec-18cb-11e5-9c56-badef7306c1a.jpg)

2nd pic shows the trainer offering the quests.
![wowscrnshot_062215_104156](https://cloud.githubusercontent.com/assets/12252441/8284552/62fddab8-18cb-11e5-9c8c-fa764ee4969e.jpg)

**Comment by Thefakemccoy** [comment]
I did the quest from 
http://www.wowhead.com/npc=18802/alchemist-gribble
just earlier this week,

Now 
I am being offered 
http://www.wowhead.com/quest=29482/transmutation-master

**Comment by ahtebe** [comment]
Those Outland quests are supposed to be removed in 4.3.0, at the time when the new quests with cataclysm mats were introduced in the faction cities. 4.3.4 server with 4.1 content, so that's probably why both sets of quests exist at the same time.

**Comment by Bildo** [comment]
fixed
