### ISSUE TITLE
[EN][QUEST][The Storm Peaks] Destroy The Forges

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3619]
When using the item "Bouldercrag's Bomb" on one of the forges, it does nothing and doesnt grant you have destroyed the forge. This does not work for any of the 3 forges and makes the quest incompletable and breaks the chain.
![wowscrnshot_062215_191634](https://cloud.githubusercontent.com/assets/10423624/8296737/4269c4f2-194c-11e5-897e-fc772ff1751d.jpg)
This seems to have broken recently as i have completed this quest before, maybe due to the guid update?
This is how it should work https://www.youtube.com/watch?v=4de8wTnUpSI
wowhead http://www.wowhead.com/quest=12988/destroy-the-forges

**Comment by lourrific** [comment]
confirmed as of July 12, 2015 this quest is still bugged.
