### ISSUE TITLE
[EN] Tol barad queing system (again

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3620]
This is no longer working as it should and i finally have overwhelming proof...
![wowscrnshot_062315_021207](https://cloud.githubusercontent.com/assets/10423624/8296908/66fac15c-194e-11e5-91a6-cd303bf864d1.jpg)
As allience have far many more players, tol barad is completely unbalanced and not fun for horde, most horde do not join anymore as a knock on affect.
In this screenshot i can see about 9 allience, in one base alone, u can see there is only 4 horde including myself, if theres 9 in one base then there could well be at least 16.
16 vs 4, doesnt sound like good math for a 1 - 1 ratio style battle ground.

(Edit), since this i have also noticed that there seems to be no system what so ever that is actually working, as the queue just lets every single player in instantly. I never have to wait to get in, even on popular hours anymore. I noticed one time that the horde had around 55 players, i was in the secound raid group.

**Comment by zeoos** [comment]
Nice, Horde not playing PVP.
On retail, when I played it, I got about 1:1 Ratio

**Mechanics**
Maximum 80 players per faction able to enter the zone during combat. Unlike Wintergrasp, Tol Barad will not have Tenacity buffs. Instead, the queue system will attempt to match each side at a 1 to 1 ratio.

    "If there are only 50 Alliance players, the system will find only 50 Horde players -- 
    even if there are 200 Horde players queued."

There are minimum cap also.

    "With the minimum cap is 25, if 25 Horde que and 150 alliance que, the battle will be 25 vs 25.
     And if 25 Horde que, and 10 alliance que, it will then 25 v 10."

[Source](http://www.mmo-champion.com/threads/820256-Tol-Barad-Strategy-Guide)

**Comment by meowmewo** [comment]
Confirmed. Still alliance are 2/3x more then horde in every TB battle. Ive lost my last 15 TBs i qued due to that. I couldnt even do my BH for 2 weeks now cuz of this bs.

**Comment by Fearyourself** [comment]
Is it possible to reduce the minimum cap or get rid of it?
