### ISSUE TITLE
[EN] [Social] [Social Tab] Friend list isn't working.

### ISSUE THREAD

**Issue by Azuzzu** [Atlantiss/BugTracker#3621]
Yeah as you can read, if I open my Social Tab where Friends, Who, Chat etc is in it doesn't load at all and only displays the empty Friend's List. Only way around to access the Who or Chat tab is by changing from Friends to Ignore list, then the tab works but still without friends on that list.

Dubhlainn.

**Comment by Bildo** [comment]
Clear your cache, disable addons or idk, it's not server bug.
![wowscrnshot_062315_174240](https://cloud.githubusercontent.com/assets/3138020/8310323/64a8037a-19cf-11e5-98b4-66d52a08f282.jpg)

**Comment by Mapartipin** [comment]
Same problem! Delete from wow folder - font folder
