### ISSUE TITLE
[EN][Raid] Throne of the Four Winds, Conclave of Wind (Heroic). Anshal also heals himself with zephyr (everytime)

### ISSUE THREAD

**Issue by Isuel** [Atlantiss/BugTracker#3622]
http://www.wowhead.com/spell=84651/zephyr#used-by-npc

Anshal doesn't heal only his adds, as stated in the tooltip, but also heals himself. I don't know if that also happens in normal.

**Comment by Asavel** [comment]
Agahahahahh

**Comment by Isuel** [comment]
the tooltip from dungeon journal says that it only heals the adds. if the report is wrong, feel free to close it.

**Comment by Jenovas** [comment]
He should heal himself.
Closing issue.
