### ISSUE TITLE
[EN][Quest][Hellfire Ramparts]Hitting Them Where It Hurts

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3625]
The objects are spawned now with the quest item sparkle, but only like half of the crates are actually lootable. Some of the have the sparkle, but are unlootable. 

http://www.wowhead.com/quest=29594/hitting-them-where-it-hurts

http://www.wowhead.com/object=209348/hellfire-supplies#comments

**Comment by Bildo** [comment]
That's because some of them are only for the ally quest verion and some of the are for horde
