### ISSUE TITLE
The Razza bug (normal chimera look)

### ISSUE THREAD

**Issue by XrayAlert05** [Atlantiss/BugTracker#3628]
A rare located in Feralas, a tameable hunter pet, its bugged. When I came back to orgri it changed his look to normal lv 70 looking chimera. Please fix that.

he is supposed to look like this: http://www.wowhead.com/npc=11497/the-razza#screenshots:id=207729

**Comment by Bildo** [comment]
change title or i will close this

**Comment by XrayAlert05** [comment]
Why change and how I am suppose to name it?
