### ISSUE TITLE
[PL][Spell] Replenishment

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#3630]
[PL] <b>Jak jest</b>
[EN] <b>How works</b>
[PL] <a href='http://cata.openwow.com/spell=57669'>Replenishment</a> zwraca zbyt dużo many. 
[EN] <a href='http://cata.openwow.com/spell=57669'>Replenishment</a> returns too much mana. 
[PL] Mając 26547 many dostaję 66 many co sekundę. 
[EN] Having 26547 mana I get 66 mana every second.
 <img src="http://i.imgur.com/DaT75V9.jpg">
[PL] <b>Jak działa</b>
[EN] <b>How should work</b>
[PL] Replenishment powinien zwracać 0.1% many co sekundę. Czyli w moim przypadku 0,001 * 26547=26.6
[EN] Replenishment should return 0.1% mana every second. In my case it should be 0,001 * 26547=26.6

**Comment by Varchord** [comment]
Sprawdz lepiej czas. Bo te 66 many nie musi być w ciągu sekundy, tylko updatowane co 2-3s

**Comment by planche** [comment]
Na screenie widać 15 ticków czyli 1 tick na sekundę trwania buffa

**Comment by Varchord** [comment]
ściągnąłeś trinkety, bronie itp? Odpałki z inta zwiększają twoją mane

**Comment by planche** [comment]
Nie miałem żadnych buffów. Jeśli masz postać z maną sam możesz sprawdzić..

**Comment by Quban** [comment]
zwraca za duzo bo tez testowalem

**Comment by Frainzil** [comment]
Can someone roughly translate this to english? ^^

**Comment by Bildo** [comment]
Translated into English.

**Comment by Quban** [comment]
It restores 0.25% every sec now instead of 0.1%, fix soon ;d

**Comment by planche** [comment]
Thanks

**Comment by Quban** [comment]
fixed in rev. 4482
