### ISSUE TITLE
[EN][Quest][Darkshore]Leave No Tracks

### ISSUE THREAD

**Issue by oguzhanyuruk** [Atlantiss/BugTracker#3633]
The quest does not work properly, when you go to the place where quest scenerio will happen NPCs start to talk but after their conversation is done nothing happens.

**Comment by Aival94** [comment]
last time i did it worked.Maybe need to be near them(in the middle of them).

**Comment by lcorr031** [comment]
THIS QUEST IS STILL BROKEN! You go to the location where they are speaking and the quest does not complete!
