### ISSUE TITLE
[PL][Death Knight] Blood of The North

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#3637]
http://cata.openwow.com/spell=54637
Buguje się po śmierci i daje blood runy bez możliwości zamiany. Pomaga respec

Jak zreprodukowałem?
1. Lecimy do BWD, atakujemy trash
2. Zużywamy wszytkie nasze runki
3. Umieramy z runkami na CD
4. Ressamy się w BWD
5. Runki są blood

Co ciekawe jeśli umrzemy z blood runkami (bez cd) staną się one na powrót death
Wyjście z BWD też przywraca runki do postaci death

http://i.imgur.com/ZI3wAXw.jpg

Reasumując. 
Wychodzi na to, że zmiana mapy podczas gdy death runki są na CD powoduje ich przemianę na blood i vice versa

**Comment by Aydien** [comment]
Już prawie pół roku to wisi, a frost dalej jest niegrywalny na BG, ostatnio nawet zmiana speca nie pomaga pozostaje jedynie relog, jest to chyba najbardziej irytujacy bug.

**Comment by PierwszyKrytykRP** [comment]
Wisi o wieleeeeeee dłużej niż "prawie pół roku" https://github.com/Atlantiss/BugTracker/issues/444

**Comment by lamaATS** [comment]
Fixed in rev. 4930 (missing close)
Part of commit message:
`Blood of the North will no longer bug out after player death`
