### ISSUE TITLE
[EN][Spell][Paladin]Holy Radiance

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#3639]
http://www.wowhead.com/spell=82327/holy-radiance#changelog
The spell itself works fine, the only thing which i'm concerned about is the 5th hot tick of the spell. I have done some research on how much haste rating you need to get a 5th hot tick of the spell; (1hit/crit of the spell followed by 5 hot ticks/crits). According to a lot of players on retail this number was around 3350-3370 haste rating which is (1% haste = 128haste rating) => +- 26% haste. Now when i do some math;

basic haste% of the character = 3,31%
haste% i get from gear= 10,34%
judgement of the pure = 9% (this is actually bugged and gives 10,23%)
a shaman totem (haste buff) = 5% (also this is bugged and gives around 5,6%)

Now if i add this all together i have around +- 27.65 in retail stats, on our server it is = 29.48% haste. Now this is not enough for me to get a 5th tick of holy radiance. I tried to get as much haste as possible adding around another 150 haste rating through gems + a haste flask adding another 225 haste rating, still no 5th tick appears (total here was 4150 haste rating or 32% haste). ONLY when i use divine favor (20% extra casting haste, which makes the total on around 50%???) i get a  5th tick of holy radiance. Can someone explain me why i'm not getting a 5th tick?

**Comment by Bildo** [comment]
wowhead link

**Comment by Quban** [comment]
> Now if i add this all together i have around +- 27.65 in retail stats, on our server it is = 29.48% haste

You don't add haste bonuses, you multiply them. So if your haste is 29.48% which is 1.2948, than you have 1.2948/(1.09*1.05*1.03) = 1.2948/1.178835 = 1,09837 which gives you 9.837% haste from your gear => 9.837*128 = 1259,136 this is probably your haste rating from gear

**Comment by Quban** [comment]
You dont add haste, you multiply you bonuses and your math is wrong here.

**Comment by Quban** [comment]
To get another tick your heal have to tick every 3/4 sec which is 1 / 0.75 = ~1.33(3) so you need about 33.34% haste to get it, another breakpoint is 3/5 sec tick => 1 / 0.6 = ~1.66(6) so 66.67% haste.
Now you know the mechanics, haste works great on atlantiss.
Closing this coz there is no bug here :)
