### ISSUE TITLE
[EN][Quest][Silverpine Forest] Iterating Upon Success

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#364]
What is not working (Minor bug):
=============

The flight path is not fluid/smooth, sometimes the bat turns back for a second.

---------------
How should work:
=============

It should work like this:
[Video#1](http://youtu.be/esYSi6i4t30?t=35s)
[Video#2](http://youtu.be/cYXBCQi3-Zs?t=28s)
[Video#3](http://www.youtube.com/watch?v=Es6w5MtdxHU)

----------------------
More info:
=============

Apart from that, works great.

**This was tested on 4.0.6a realm**

**Comment by krecik88** [comment]
Fixed in 4267.
