### ISSUE TITLE
[EN][Spell][Shaman] Elemental Mastery

### ISSUE THREAD

**Issue by Chriztiaan** [Atlantiss/BugTracker#3641]
Elemental Mastery's cooldown remains to be an issue, it still shows that it is castable even when it is not. Making dps as an elemental shaman just a tad annoying. If you could please look into the issue once more it would be appreciated a lot seeing as it is an important dps cooldown.
Enjoy

**Comment by sunshineinabox** [comment]
There is a similar issue with Socrch for mages, but there is a way to make it act properly by switching spec and then switching back.

**Comment by aneq** [comment]
As someone who plays elemental a lot heres my 2 cents.
This is annoying, true but it's caused by excessive button mashing. If you press it once it won't bug out.

**Comment by Jenovas** [comment]
Duplicate
