### ISSUE TITLE
[EN] [NPC] Gorsik the Tumultuous

### ISSUE THREAD

**Issue by orhasson** [Atlantiss/BugTracker#3642]
The NPC isn't responding at all, I tried everything.
Not giving nor taking any quests.
I took the quests from him a day ago, but now I can't finish them.
Please fix it pronto, thanks.
![wowscrnshot_062515_220531](https://cloud.githubusercontent.com/assets/7671028/8363370/19657db6-1b87-11e5-8e57-254761fe2f4a.jpg)

**Comment by monibu** [comment]
un-check "At-war" with therazane
