### ISSUE TITLE
[EN][Spell][Paladin] Guardian of Ancient Kings

### ISSUE THREAD

**Issue by Hobbit696** [Atlantiss/BugTracker#3643]
A visual that needs correcting. When in Protection spec, Guardian follows the caster instead of standing in place and casting the beam. Spec glow is correct.

Spell: http://cata.openwow.com/spell=86150
How should it work (2:25): https://www.youtube.com/watch?v=KdjK4fuD0ow

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
