### ISSUE TITLE
[PL][Achievement]

### ISSUE THREAD

**Issue by hayter2** [Atlantiss/BugTracker#3644]
Flame Keeper of Eastern Kingdoms, lokacja Badlands dalej nie dysponuje questami do Midsummer. Extinguishing Kalimdor Southern Barrnets po stronie ally tez nie działa. jest quest ale nie mozna odebrać i oddać.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3613
