### ISSUE TITLE
[EN][Quest][Mount Hyjal] Portal not showing up

### ISSUE THREAD

**Issue by death2you2** [Atlantiss/BugTracker#3646]
Hello, so apparantly i finished the Hero's call: Mount Hyjal! quest line but i did not receive the portal from stormwind to mount hyjal.. i sent a few tickets and a GM put the quest in my log again but nothing happens when i talk to the npc who's supposed to tp me to moonglade. So afterwards with my second ticket i was sent to moonglade and still nothing happened after i hopped on the drake. Any way it can be fixed? it's quite a pain to fly to Mount hyjal every single time i want to go there..

**Comment by Aival94** [comment]
The Portal from Mount Hyjal to Stormwind/Orgrimmar and from Stormwing/Orgrimmar should be spawned when you complete quest [As Hyjal Burns](http://www.wowhead.com/quest=25316/as-hyjal-burns).
Now the portals from Mount Hyjal are already spawned and from Stormwind at least do not spawn after you complete it.For some i heard it does not spawn from Stormwind after doing 20-30 or never spawn even if the complete all the zone.

Proof 1: "Turning in this quest creates the portal in Orgrimmar (and presumably in Stormwind) that teleports you to Mount Hyjal. If you leave Mount Hyjal without turning it in, you will have to return by other means." - [Wowhead Comment](http://www.wowhead.com/quest=25316/as-hyjal-burns#comments:id=1219772:reply=568526)
Proof 2: "The quest you are referring to is called "As Hyjal Burns". The portal will open up in Orgrimmar/Stormwind afterward so you can return to the zone." - [Blizzard Support Forum Agent comment/asnwer](http://us.battle.net/wow/en/forum/topic/1406720817#15)

**Comment by zotmer** [comment]
Problem still persists. I just turned As Hyjal Burns, yet there is no portal in OG.

**Comment by BAndysc** [comment]
Since rev 5099 portal to Hyjal will appear once you finishe quest As Hyjal Burns
