### ISSUE TITLE
[EN] [Spell] [Hunter- Pet] Raptor Special - Tear Armor 

### ISSUE THREAD

**Issue by badpollo** [Atlantiss/BugTracker#3647]
The special ability from the Raptor http://cata.openwow.com/spell=50498 is not stacking properly. The first stack applies the debuff (4% armor reduction) for 30 seconds, and is on a 6-second cooldown. Upon applying the second stack, the duration is reduced to 7 seconds. When it attempts to apply the third stack, the target is Immune. The next strike (to apply the first stack again) then continues to say the target is Immune for a few more seconds. 

I'm not sure if this is suffering from diminishing returns, or if this is an improper stacking mechanic.

**Comment by Quban** [comment]
pls link spells
