### ISSUE TITLE
[PL][TALENT][SHAMAN] Talent Feedback is not working with Chain Lighting

### ISSUE THREAD

**Issue by Beliteo** [Atlantiss/BugTracker#3648]
talent http://cata.openwow.com/spell=86185 - Feedback nie działą w połączeniu z http://cata.openwow.com/spell=421- Chain lightning

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by LaveGit** [comment]
Have you actually tested this yourself? Just did a test at dummies, and it properly reset cooldown by 3 sec for every Chain Lightning. I don't recall that it haven't worked at some point recently.

**Comment by Beliteo** [comment]
I saw it on instance, when i was spamming CHL. It didn't reduced the cd of my feedback talent. Maybe becaouse of http://cata.openwow.com/item=41518

**Comment by LaveGit** [comment]
I use that glyph myself, so that shouldn't be the problem. What instance were you in?

**Comment by aneq** [comment]
I also never had the issue with this talent
