### ISSUE TITLE
[ENG][Quest][The Storm Peaks] Mildred the Cruel

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3651]
When accepting the quest, you are visually transformed, however when going to Mildred the Cruel, she is still aggressive. This means you cant talk to her and complete the quest.
![wowscrnshot_062415_235302](https://cloud.githubusercontent.com/assets/10423624/8384636/4a511b70-1c3a-11e5-86e9-5951b36761ba.jpg)

**Comment by Bildo** [comment]
Just relog

**Comment by Helbringer** [comment]
Not many people are going to know to do that.
