### ISSUE TITLE
[EN][Pet][Hunter][Beast Mastery] Tamed boss pets are immune to CC effects

### ISSUE THREAD

**Issue by huujo** [Atlantiss/BugTracker#3652]
When a Beast Mastery Hunter tames a boss (beast), the pet also holds onto the bosses immunity to all crowd control effects.

These pets cannot be:
Polymorphed
Feared
Frozen
Stunned
Slowed
etc.

Some tameable bosses, that i have tamed and confirmed to be immune:
The Beast   http://www.wowhead.com/npc=10430/the-beast
Chromaggus  http://www.wowhead.com/npc=14020/chromaggus
Buru The Gorger http://www.wowhead.com/npc=15370/buru-the-gorger

Some more tameable bosses:
Magmadar    http://www.wowhead.com/npc=11982/magmadar
Princess Yauj   http://www.wowhead.com/npc=15543/princess-yauj
Vem     http://www.wowhead.com/npc=15544/vem
Lord Kri    http://www.wowhead.com/npc=15511/lord-kri

(Not sure if that's all of them...)

In PvP it's pretty impossible to run away from these pets. The only way to stop them, is to kill them.

**Comment by Piklo** [comment]
no proofs
