### ISSUE TITLE
[EN][GRIM BATOL]  Dragons are not working

### ISSUE THREAD

**Issue by Terrificlol** [Atlantiss/BugTracker#3655]
The Grim Batol mechanic with the dragons is not working (it says "You are in the Wrong Zone" when you click on them), what makes this instance really long

**Comment by Aival94** [comment]
Reported: #764

**Comment by Varchord** [comment]
You dont say?

https://github.com/Atlantiss/BugTracker/issues/764

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by sunshineinabox** [comment]
No need for you to comment and be a bully the guy above you already pointed out that it was reported.

**Comment by Varchord** [comment]
I disagree. Too many people don't read the rules and make multiple posts about the same things, do not attach links, make wrong titles, write posts that should be reported as in game ticket.

They need to learn, maybe a little bit of tough love will help
