### ISSUE TITLE
[EN][Mage] Ring of Frost vs. deep freeze dr

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3658]
Ring of Frost should share DR with deep freeze

proof:
http://us.battle.net/wow/en/forum/topic/6490599996
 "Pretty sure they shared DR during 4.3."
"They shared DR before because ring was instant cast."
"No it doesnt. Ring shared dr with deep last season" (season 11)

http://wowwiki.wikia.com/Ring_of_Frost
" Patch 4.2.0 (28-Jun-2011): Deep Freeze and Ring of Frost will cause diminishing returns on each other, in addition to the spells they normally share diminishing returns with."

**Comment by blinkmaster** [comment]
https://github.com/Atlantiss/BugTracker/issues/26
its posted since november.
