### ISSUE TITLE
[en][spell][druid] Dash and Stampeding roar

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3659]
It shouldn't be possible to have both buffs on character.
if u want to use dash when already with stamp roar you should wait for buff to expire or /cancelaura it
here you can do this without that
http://eu.battle.net/wow/en/forum/topic/2569217041

http://wow.gamepedia.com/Dash_(druid_ability)
http://wow.gamepedia.com/Stampeding_Roar_(Cat_Form)

"The problem is that you can't use both effects at the same time. That means that if one is active then you will get the message "you can't use that yet" if you try to activate the other."

**Comment by Thefakemccoy** [comment]
IDK when it was changed but on retail you can use both but you wont get the effect from SR if you have dash active.

I looked throught the patch notes up until 6.2 and didnt really see the change.

**Comment by Isuel** [comment]
the movement speed effects don't stack anyway, so i see no reason to use both at the same time. Don't think it's such a big issue :P

**Comment by Fearyourself** [comment]
It is a big issue if you're a feral and want to get out of roots.

**Comment by phifedawg** [comment]
you should just use /cancelaura command implemented into your root breakers anyways..
