### ISSUE TITLE
[EN][NPC] Qirot (rare wasp) treated as Chimaera family.

### ISSUE THREAD

**Issue by Philippe777** [Atlantiss/BugTracker#3660]
Qirot (http://www.wowhead.com/npc=5350/qirot#comments) my new pet, is being treated as a Chimaera, even though it's a wasp. It even has the Cunning pet talent tree and the exotic ability of the Chimaera family. Please fix this asap. :)

My hunter was in Survival spec at the time, but I do have a Chimaera tamed in my BM offspec.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1574
