### ISSUE TITLE
[EN] [Talent] Tree of Life & Sap

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#3661]
Tree of Life is supposed to make you immune to sap for the duration of the shapeshift.

ToL link
http://cata.openwow.com/spell=33891
Sap link
http://cata.openwow.com/spell=6770

**Comment by Jenovas** [comment]
Where does it say that it gives immune to sap?

**Comment by kadi2** [comment]
I don't think Tree of Life counts as elemental since cataclysm.
