### ISSUE TITLE
[EN][Achievement][minor] To All the Squirrels Who Cared for Me

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#3665]
http://www.wowhead.com/achievement=5548/to-all-the-squirrels-who-cared-for-me

6 out of 13 critters are missing:
1) Oasis Moth from Uldum http://www.wowhead.com/npc=50496
2) Mac Frog from Uldum http://www.wowhead.com/npc=50491
3) Highlands Turkey from Twilight Highlands http://www.wowhead.com/npc=48706
4) Grotto Vole from Hyjal http://www.wowhead.com/npc=50419
5) Baradin Fox Kit from Tol Barad http://www.wowhead.com/npc=48630
6) Sea Cucumber from Vashj'ir http://www.wowhead.com/npc=48802

Not an important bug, but still would be nice if it was fixed.

**Comment by HUMBOL** [comment]
Bump!

**Comment by Bildo** [comment]
fixed
