### ISSUE TITLE
[EN][Achievement] Stood in Fire

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#3666]
http://www.wowhead.com/achievement=5518/stood-in-the-fire

You only get this achievement if Deathwing himself kills you when shooting fire. 
Fire that remains behind him doesn't do damage and standing in it won't kill you. I was just flying behind him through 3 maps trying to get in front of him, but he was too fast.

**Comment by Bildo** [comment]
duplicate
