### ISSUE TITLE
[EN][Achievement] King of Dire Maul

### ISSUE THREAD

**Issue by RelmAtlantiss** [Atlantiss/BugTracker#3668]
You can't pass the doors in the Gordok Commons (they should be unlocked), therefore you can't kill King Gordok, which is needed to the achivement.
![diremaul](https://cloud.githubusercontent.com/assets/11969548/8396417/683d42ce-1da4-11e5-9bc1-8223fd30a123.png)

**Comment by Quban** [comment]
i ll open it for now but i dont remember that doors being open at retail, think it should be opened with some key from boss

**Comment by RelmAtlantiss** [comment]
The key shouldn't be longer needed due to Cataclysm changes.

**Comment by Quban** [comment]
ok than i'll leave it opened ;d
