### ISSUE TITLE
[EN][Instance-Cata] Zul'Gurub, Jin'do the Godbreaker

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#3669]
http://www.wowhead.com/npc=52148

It should be possible to fight with this boss after defeating any 2 other bosses (Cache of Madness does not count as boss).

**Comment by Aival94** [comment]
This was change during 4.3 so they might want to first reach content of 4.3 to change it.

http://wow.gamepedia.com/Zul%27Gurub_(instance)
