### ISSUE TITLE
[EN][Quest][Silverpine Forest] The Waters Run Red...

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#367]
What is not working:
=============

You can't do anything, totally broken.

---------------
How should work:
=============

You should be able to use the cannons, and right after you enter on one, waves of worgens would on the island in front of you, and start crossing the river.
With your cannon, your mission is to kill 50 worgens. 

----------------------
More info:
=============

At the moment is auto-completed.

[Video](http://www.youtube.com/watch?v=lO1VkhpRuIQ)
[The Waters Run Red... - WoWHead](http://www.wowhead.com/quest=27232)
[The Waters Run Red... - WoWPedia](http://wowpedia.org/Quest:The_Waters_Run_Red...)

**This was tested on 4.0.6a realm**

**Comment by Angelo-DM-** [comment]
Confirm! 
1) [Hillsbrad Worgens](http://www.wowhead.com/npc=45270) are not spawned caused you can't use the cannon.
2) The [Horde Cannon](http://www.wowhead.com/npc=45263) is totally bugged: You can't use it. It is not interactive.
3) The quest is on Autocomplete...

**Comment by Cassedy** [comment]
Confirm
as Angelo-DM described

**Comment by Spydoc** [comment]
Currently the quest is set on auto-complete, so this indicates that the quest is still not working.

**Comment by Enay** [comment]
Confirming, completely bugged.

**Comment by eryczek1615** [comment]
bump

**Comment by JohannDoe** [comment]
comfirmed

**Comment by BAndysc** [comment]
Fixed in rev 5102
