### ISSUE TITLE
North Point Tower in Dustwallow Marsh Npc's are dead.

### ISSUE THREAD

**Issue by ZoZo2012** [Atlantiss/BugTracker#3670]
Well i was leveling and i had some quest at http://wowwiki.wikia.com/North_Point_Tower in Dustwallow Marsh and the NPC's are dead and stand up like they are alive. http://i.imgur.com/Yr83am2.jpg / http://i.imgur.com/vAB66hg.jpg.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
