### ISSUE TITLE
[EN][Quest][Nagrand] Not on my watch

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#3674]
http://www.wowhead.com/quest=9918/not-on-my-watch

Issue is pretty simple, Lump is just not there. Waited over 20min and he still didn't appear (in case he might've gotten killed which I doubt it's possible anyway)

**Comment by zeoos** [comment]
I'll second that. I think I've seen him for like 1 second then he phased out.
He's supposed to be asleep, then, after you get him down a little, he'll not be attackable and you will talk with him and complete the quest.

**Comment by Quarvol** [comment]
I have been sitting here around 30 minutes and no lump.

**Comment by micha666** [comment]
Just wanted to add that problem still exists. He spawns and dissapear.

**Comment by Heart1783** [comment]
Is there a way to complete this quest or do you just have to farm orgers to get to friendly to skip the quest ?

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/7104

**Comment by BAndysc** [comment]
Fixed in rev 5093
