### ISSUE TITLE
[EN][DUNGEON][Dire Mail] Gordok Courtyard Door

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3676]
The Gordok Courtyard Door is unopenable after killing the first boss, in turn pretty much shutting down the entire dungeon as it locks u out from progressing any further.
![wowscrnshot_062915_123320](https://cloud.githubusercontent.com/assets/10423624/8407154/ccba8f1a-1e5b-11e5-8491-41d8c5d482d4.jpg)

**Comment by Bildo** [comment]
duplicate
