### ISSUE TITLE
[PL] [DK] Blood of the North

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#3677]
http://cata.openwow.com/spell=54637

"Permanently transforms your Blood Runes into Death Runes. Death Runes count as a Blood, Frost, or Unholy Rune."

Po przejściu przez portal, po użyciu Hs'a, czasem po śmierci buguja death runy zmieniając się w blood runy we drzewku Frost.

Pomaga respec ( nie zawsze ) lub relog.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3637

A szukać umiesz?
