### ISSUE TITLE
[EN][Item]The Last Relic of Argus

### ISSUE THREAD

**Issue by TheRealCiapaty** [Atlantiss/BugTracker#3679]
Przedmiot nie działa, po użyciu powinien teleportować gracza w losowe miejsce(niżej koordy tych miejsc). Cooldown 12h jest, lecz postać stoi tam gdzie stała.

- (28.7, 57.6): Silithus [Hive'Zora]
- (18.7, 24.8): Duskwood [Dawning Wood Catacombs]
- (69.6, 87.8): Wetlands [on the Shattered Dam]
- (32.3, 22.7): Desolace [Slitherblade Shore]
- (33.2, 56.2): Ungoro [Galakka Hot Springs]
- (51.9, 34.2): Badlands [Crypt]
- (42.3, 15.0): Western Plaguelands [Mardenholde Keep]
- (64.5, 20.0): Tanaris [Steamwheedle Port]
- (89.9, 36.3): Badlands [Fuselight by the Sea]
- (97.5, 47.1): Hellfire Peninsula [on a floating rock]
- (78.0, 91.6): Northern Barrens [Fray Island]
- (69.7, 47.9): Tanaris [Lost Rigger Cove]
- (53.4, 31.2): Felwod [Irontree Woods]
- (45.7, 47.0): Moonglade [Nighthaven]
- (50.9, 36.4): Western Plaguelands [Scholomance]
- (45.1, 68.4): Northern Stranglethorn [The Sundering, in a tree]
- (23.9, 56.4): Badlands [Scar of the Worldbreaker]
- (48.9, 43.8): Arathi Highlands [Dabyrie's Farmstead]
- (33.6, 51.3): Blasted Lands [The Tainted Forest]
- (35.4, 63.7): The Cape of Stranglethorn [Janeiro's Point]
- (52.3, 54.9): The Northern Barrens [Wailing Caverns/Cavern of Mists]
- (39.4, 67.0): Searing Gorge [Iron Summit]
- (23.0, 65.8): Wetlands [Black Channel Marsh]
- (64.7, 55.1): Blasted Lands [on a Mountain Peak]
- (62.5, 28.0): Diremaul [Broken Commons]

Koordynaty z wowhead.

Item link: http://www.wowhead.com/spell=90984/the-last-relic-of-argus

**Comment by 1Andas** [comment]
Bump. Still bugged.

**Comment by jissabraham** [comment]
confirmed its not working still

**Comment by TranceAccount** [comment]
Confirmed.

**Comment by pelekon** [comment]
Fixed in  rev  5143.
