### ISSUE TITLE
[PL][QUEST][HORDE][ Weapons of Mass Dysfunction.]

### ISSUE THREAD

**Issue by Dariwa99** [Atlantiss/BugTracker#3680]
Witam quest nie działa na zasadzie podejścia do  trzeciej maszyny która powinna się rozwalić a npc reaguje i pojawia się interakcja którą podaje na filmiku. W naszej sytuacji przy 3 maszynie nie ma npc tzw. chefa.

Link do poprawnie działającego questa https://www.youtube.com/watch?v=SHivOt_x78g

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by XxaklxX** [comment]
I don't speak Polish, but in order not to create another topic , I think it 's happening the same with me!
