### ISSUE TITLE
[EN][Quest] The Magical Kingdom of Dalaran

### ISSUE THREAD

**Issue by Nosere** [Atlantiss/BugTracker#3681]
http://www.wowhead.com/quest=12794/the-magical-kingdom-of-dalaran
Speaking to her again provide you a teleport to dalaran

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/831

**Comment by Nosere** [comment]
How am I supposed to know polish

**Comment by Bildo** [comment]
you don't have to know polish, title is in english
