### ISSUE TITLE
[EN][NPC] Captain Dirgehammer <Conquest Quartermaster>

### ISSUE THREAD

**Issue by PVPViddys** [Atlantiss/BugTracker#3683]
Currently Captain Dirgehammer is showing as PvP Items <The Atlantiss PTR Crew>

Also deleted cache and problem still persists.

![wowscrnshot_062915_151957](https://cloud.githubusercontent.com/assets/10858563/8416240/6373fe3a-1e72-11e5-92ed-0b7923b2b80d.jpg)

**Comment by Kejmil** [comment]
i checked both ptr and main realm and didn't encounter the problem
i guess it is your client, propably modified dbc files or something else

**Comment by Bildo** [comment]
clear your cache
