### ISSUE TITLE
[EN][Quest][Felwood] Touch the Untouchable

### ISSUE THREAD

**Issue by aje** [Atlantiss/BugTracker#3687]
http://www.wowhead.com/quest=28044/touch-the-untouchable

The [mob](http://www.wowhead.com/npc=47398/vorlus) is not present.

You can see the video for how the quest works
https://www.youtube.com/watch?v=rZRjTNVewZ8

**Comment by user1011** [comment]
It worked for me, about a month or 2 ago.

**Comment by aje** [comment]
Reading your message, I tried again and the mob was here.
