### ISSUE TITLE
[EN] [Event] [Midsummer] Satchel of Chilled Goods

### ISSUE THREAD

**Issue by LaveGit** [Atlantiss/BugTracker#3688]
If you complete an RHC dungeon before queuing for the event boss, you won't be able to get a Satchel of Chilled Goods that day.

**Comment by Probullet25** [comment]
I think is 1/day, like a daily quest.

**Comment by LaveGit** [comment]
I know that. But doing an RHC before doing the event boss makes you get 0/day.
