### ISSUE TITLE
Mastery talents get messed up when switching from Arms to Protection Warriors

### ISSUE THREAD

**Issue by Victabob** [Atlantiss/BugTracker#3694]
I noticed recently that as a prot warrior i was pulling 12k dps. That seemed unlikely, but my recount addon is saying that my 2nd top dps is Strikes of Oppurtunity, which is an Arms mastery talent. This happens when i change specializations from Arms to Protection. So the arms mastery talent is being brought forward to protection when i change specs.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
apparently recent reset only resetted current talent tree, not both of them
