### ISSUE TITLE
[PL][Glyph][Shaman] Glyph of Shocking

### ISSUE THREAD

**Issue by Mikox1** [Atlantiss/BugTracker#3696]
http://wowwiki.wikia.com/Glyph_of_Shocking
http://wow-mania.com/armory/?spell=55540

Glyph włożony do slota mimo tego cd shocków zamiast 5 sec, wynosi 6 sec.
http://zapodaj.net/9490c1bdae71e.jpg.html
http://zapodaj.net/4f9e45815ffb1.jpg.html

Wnoszę prośbę o naprawienie. Pozdrawiam!

**Comment by Wolffenstein** [comment]
"Use: Reduces the global cooldown triggered by your shock spells to 1 sec."

"Global" to słowo klucz w tym przypadku. Działa poprawnie.
