### ISSUE TITLE
[EN][Other][Azuremyst Isle] Double/2 hero's call boards in exodar

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3705]
there were 2 hero's call boards 
![wowscrnshot_070115_214933](https://cloud.githubusercontent.com/assets/12637348/8457403/5c0be00c-203b-11e5-987d-3b135f647f00.jpg)

see image.. thanks

**Comment by MirrorWraith** [comment]
the left one has 1 quest for bloodmyst and the other has 1 quest for westfall

**Comment by TranceAccount** [comment]
Confirmed

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18254-gameobject-heros-call-board/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
