### ISSUE TITLE
[EN][Quest][Azuremyst Isle][Minor] Azuremyst Isle Quests Order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#3706]
This zone is working just fine but some quests order is not right so i write all the quests i found that had wrong quest order.

<del>[Botanist Taerix](http://www.wowhead.com/quest=9371/botanist-taerix) should be available after completing quest [Urgent Delivery!](http://www.wowhead.com/quest=9409/urgent-delivery)

<del>[Vindicator Aldar](http://www.wowhead.com/quest=10304/vindicator-aldar) should be available after completing quest [Healing the Lake](http://www.wowhead.com/quest=9294/healing-the-lake)

[Botanical Legwork](http://www.wowhead.com/quest=9799/botanical-legwork) should be available after completing quest [Volatile Mutations](http://www.wowhead.com/quest=10302/volatile-mutations)

[Rescue the Survivors!](http://www.wowhead.com/quest=9283/rescue-the-survivors) should be available after completing quest [Urgent Delivery!](http://www.wowhead.com/quest=9409/urgent-delivery) . More bugs about this quest #1853 and #3704

[Spare Parts](http://www.wowhead.com/quest=9305/spare-parts) should be available after completing quest [Urgent Delivery!](http://www.wowhead.com/quest=9409/urgent-delivery)

[Travel to Azure Watch](http://www.wowhead.com/quest=9313/travel-to-azure-watch) should be available after completing quest [The Emitter](http://www.wowhead.com/quest=9312/the-emitter)

[The Missing Scout](http://www.wowhead.com/quest=9309/the-missing-scout) should be available after completing quest [Inoculation](http://www.wowhead.com/quest=9303/inoculation)

[The Emitter](http://www.wowhead.com/quest=9312/the-emitter) should be available after completing quests [Spare Parts](http://www.wowhead.com/quest=9305/spare-parts) and [Blood Elf Spy](http://www.wowhead.com/quest=9311/blood-elf-spy)

[An Alternative Alternative](http://www.wowhead.com/quest=9473/an-alternative-alternative) should be available after completing quest [Medicinal Purpose](http://www.wowhead.com/quest=9463/medicinal-purpose)

[The Prophecy of Velen](http://www.wowhead.com/quest=9505/the-prophecy-of-velen) should be available after completing quest [An Alternative Alternative](http://www.wowhead.com/quest=9473/an-alternative-alternative)

[Stillpine Hold](http://www.wowhead.com/quest=9559/stillpine-hold) should be available after completing quest [The Prophecy of Akida](http://www.wowhead.com/quest=9544/the-prophecy-of-akida)

[Reclaiming the Ruins](http://www.wowhead.com/quest=9513/reclaiming-the-ruins) should be available after completing quests [A Small Start](http://www.wowhead.com/quest=9506/a-small-start) and [Cookie's Jumbo Gumbo](http://www.wowhead.com/quest=9512/cookies-jumbo-gumbo)

[Warlord Sriss'tiz](http://www.wowhead.com/quest=9515/warlord-srisstiz) should be available after completing quest [Rune Covered Tablet](http://www.wowhead.com/quest=9514/rune-covered-tablet)

[Precious and Fragile Things Need Special Handling](http://www.wowhead.com/quest=9523/precious-and-fragile-things-need-special-handling) should be available after completing quests [A Small Start](http://www.wowhead.com/quest=9506/a-small-start) and [Cookie's Jumbo Gumbo](http://www.wowhead.com/quest=9512/cookies-jumbo-gumbo)

[The Kurken is Lurkin'](http://www.wowhead.com/quest=9570/the-kurken-is-lurkin) should be available after completing quests [Blood Crystals](http://www.wowhead.com/quest=9566/blood-crystals) and [Chieftain Oomooroo](http://www.wowhead.com/quest=9573/chieftain-oomooroo)

[Chieftain Oomooroo](http://www.wowhead.com/quest=9573/chieftain-oomooroo) should be available after completing quests [Beasts of the Apocalypse!](http://www.wowhead.com/quest=9560/beasts-of-the-apocalypse) and [Murlocs... Why Here? Why Now?](http://www.wowhead.com/quest=9562/murlocs-why-here-why-now)

[Warn Your People](http://www.wowhead.com/quest=9622/warn-your-people) should be available after completing quests [Blood Crystals](http://www.wowhead.com/quest=9566/blood-crystals), [Chieftain Oomooroo](http://www.wowhead.com/quest=9573/chieftain-oomooroo) and [The Kurken is Lurkin'](http://www.wowhead.com/quest=9570/the-kurken-is-lurkin)

[Search Stillpine Hold](http://www.wowhead.com/quest=9565/search-stillpine-hold) should be available after completing quests [Beasts of the Apocalypse!](http://www.wowhead.com/quest=9560/beasts-of-the-apocalypse) and [Murlocs... Why Here? Why Now?](http://www.wowhead.com/quest=9562/murlocs-why-here-why-now)

[Rune Covered Tablet](http://www.wowhead.com/quest=9514/rune-covered-tablet) should be available when you have in log or complete quest [A Small Start](http://www.wowhead.com/quest=9506/a-small-start)

[Beasts of the Apocalypse!](http://www.wowhead.com/quest=9560/beasts-of-the-apocalypse) should be available after completing quest [The Prophecy of Akida](http://www.wowhead.com/quest=9544/the-prophecy-of-akida)

[Murlocs... Why Here? Why Now?](http://www.wowhead.com/quest=9562/murlocs-why-here-why-now) should be available after completing quest [The Prophecy of Akida](http://www.wowhead.com/quest=9544/the-prophecy-of-akida)

[Gurf's Dignity](http://www.wowhead.com/quest=9564/gurfs-dignity) should be available when have in log quest or complete quest [Murlocs... Why Here? Why Now?](http://www.wowhead.com/quest=9562/murlocs-why-here-why-now)

[Blood Elf Plans](http://www.wowhead.com/quest=9798/blood-elf-plans) should be available when complete quest [The Missing Scout](http://www.wowhead.com/quest=9309/the-missing-scout)

[Urgent Delivery!](http://www.wowhead.com/quest=9409/urgent-delivery) should be available after completing quest [Replenishing the Healing Crystals](http://www.wowhead.com/quest=9280/replenishing-the-healing-crystals)/[Replenishing the Healing Crystals](http://www.wowhead.com/quest=9369/replenishing-the-healing-crystals). Now is missing.

**Comment by Aival94** [comment]
Sorry but can i ask if you fix all quests here or just the 2 that you put the line.I am asking because you have put the line in these 2 and close the issue so i do not know if all were fixed or just the 2 only.Sorry for bothering.

**Comment by Quban** [comment]
all of them, you can check them after next compilation and restart

**Comment by Aival94** [comment]
ok.ty.will probably check them after next compilation.
