### ISSUE TITLE
[PL][Item] D.I.S.C.O.

### ISSUE THREAD

**Issue by Asavel** [Atlantiss/BugTracker#3707]
Nie dziala tak jak powinnien powinnien dawac kazdemu kto wejdzie w zasieg aure przez ktora tanczy

Link do aury - http://www.wowhead.com/spell=50493/listening-to-music
Link do itemu - http://www.wowhead.com/item=38301/d-i-s-c-o

**Comment by Varchord** [comment]
Nie naprawiajcie tego bo będzie ludzi denerwował :P

**Comment by Asavel** [comment]
:D
