### ISSUE TITLE
Quest "Teron Gorefiend, I am..." Bugged

### ISSUE THREAD

**Issue by Destained** [Atlantiss/BugTracker#3712]
Quest "Teron Gorefiend, I am..." is bugged, when we accept it we can't transform into Teron Gorefiend to defeat "Karsius the Ancient Watcher" also we are silenced with the Teron Gorefiend Spell which was to transform into Teron... Please fix to complete it !

**Comment by Bildo** [comment]
read bt rules

**Comment by Destained** [comment]
Thanks, i made a new ticket !
