### ISSUE TITLE
[EN][Item][Alchemy] Flask of the North

### ISSUE THREAD

**Issue by Peekaboo** [Atlantiss/BugTracker#3713]
Flask of the North increases intellect, agility, or strength for the alchemist. This item can function in one of two ways: 1. Increase the highest stat of the user or 2. Allow the user to cycle through each stat. In its current state I am only able to switch between intellect and strength as a feral druid. I am dps feral druid so agility is my highest stat but I am not able to select it. http://cata.openwow.com/item=47499

**Comment by Varchord** [comment]
To gain agility use it in cat form.

Flasks from the cauldron work the same way

**Comment by Thefakemccoy** [comment]
As of 4.0.1 this Flask now gives Intellect, Strength or Agility based on your class and spec. Ex) As a feral druid, you cannot get anything but the Agility buff. If you dual spec into restoration or balance, you get the Intellect buff only. (No more multiple clicks for hybrids, it seems.)

**Comment by Varchord** [comment]
I just gave him a workaround until it's fixed

**Comment by Thefakemccoy** [comment]
I saw the post for it so I was just adding the info cause on my shaman i have the same issue. And forgot to look it up when i noticed it. So i figured i would add this info.

The cauldrons should work the same way.

The only big diff is as feral you always get agi unless you are a bear and want stam you must be in bear form.

**Comment by Varchord** [comment]
Well, no. On druid it works this way. No matter your talent tree is

Caster/boomkin/travel form - intellect
cat form - agility
bear form - stamina

It's stupid, but its the way it is

**Comment by Thefakemccoy** [comment]
well that means it is broke it suppose to agi in feral spec at all times unless you are in bear form then you get stam.

**Comment by Thefakemccoy** [comment]
How it should work:

As feral if you take the flask it should always proc as agi normal form form or kitty form.
With the exception of being in bear form then it would proc stam.

**Comment by Peekaboo** [comment]
I used in cat form and still was unable to get the agility buff.

**Comment by Avalain** [comment]
Just tested it on druid.

No matter in which form I currently am, Flask of the North gives only strength or intellect buff.
I couldn't gain agility buff.

It's small disadvantage for feral druids, shamans, hunters and rogues in WotLK.
