### ISSUE TITLE
Battlefront Triage:quest bug

### ISSUE THREAD

**Issue by Gurthalak** [Atlantiss/BugTracker#3716]
I cant apply Deepvein's Patch Kit
 on the injured nothing happens they should be low on health and all that , you cant complete the quest here is the quest .
https://www.youtube.com/watch?v=APfg6Pwjz9o =video
http://www.wowhead.com/quest=26591/battlefront-triage =wowhead
this is in deephome

**Comment by Bildo** [comment]
duplicate
