### ISSUE TITLE
[EN] Low fps

### ISSUE THREAD

**Issue by Blobble** [Atlantiss/BugTracker#3717]
I usually play at ultra and reach my fps to 95. But when I play on Atlantiss I play between 1 - 35 fps. I can't even play. Why is this happening!?

**Comment by Varchord** [comment]
Bugtracker is not foroum or ticket system

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Blobble** [comment]
But what I do!? ;_;

**Comment by rihards1** [comment]
turn settings on high or medium xD

**Comment by rihards1** [comment]
make sure that multisampling is on 1x, if its on 2x,4x or 8x it will kill your fps!

**Comment by Anhaeyn** [comment]
If you play as Worgen in their starting area, then just make another character, not worgen. I had the same issue long time ago, when playing worgen. After one of the cinematics I started to have 0-2 fps and couldn't play. If you're not playing as worgen and you have this problem, lower your settings.

**Comment by Blobble** [comment]
Worgen is fine after some time. But I also tried human and goblin, doesn't matter what race you pick: you're always fine, but for when you go into combat because then, for no apparent reason the fps goes downhill. EH!?

**Comment by rihards1** [comment]
whats you pc specs?

**Comment by Blobble** [comment]
It was the server that lagged not my PC....

**Comment by rihards1** [comment]
atlantiss lagging your game, thats weird

**Comment by Varchord** [comment]
I'm surprised as hell it isn't closed yet

**Comment by Jenovas** [comment]
Change settings, turn off addons, check each addon, clear cache, clear WTF.
