### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by Destained** [Atlantiss/BugTracker#3719]
Quest "Teron Gorefiend, I am..." http://www.wowhead.com/quest=10639/teron-gorefiend-i-am is bugged, when we accept it we can't transform into Teron Gorefiend to defeat "Karsius the Ancient Watcher" also we are silenced with the Teron Gorefiend Spell which was to transform into Teron... Please fix to complete it ! This is how it should be working - https://www.youtube.com/watch?v=EFJ02uLodbc

**Comment by Bildo** [comment]
you didn't read carefully :) i won't close this but add wowhead links

**Comment by Destained** [comment]
Can i add a video showing how the quest is Blizzlike ? BTW Sorry ! It's just my first time doing a ticket.

**Comment by Bildo** [comment]
Of course you can :) More information better for us.

**Comment by PlayFullTV** [comment]
Also, Bildo the main issue of the quest is that it does not grant the proper rewards it should even if someone does manage to complete it like I did.

http://www.wowhead.com/quest=10639/teron-gorefiend-i-am

I've done my research and this quest is even buggy on retail up to this date so perhaps an easier work around of some sort can be made if it's too much of a nightmare to code properly. Just a suggestion.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1726#issuecomment-100935592
