### ISSUE TITLE
[EN][NPC] High Chief Stillpine

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3727]
The NPC High Chief Stillpine (http://www.wowhead.com/npc=17440/high-chief-stillpine), has the wrong NPC text when you talk to it when not completing/accepting quests.
The text mentions the Shadow Council and Shattrath and how "our" spies where discovered and tells the player to slip into a labyrinth (Outland 60+ content).
This isn't something a lvl 13 NPC on the Draenei starting area without any connection to Outlands would say.
A "Greetings <player name>" would be better than this text.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12277-3727npc-high-chief-stillpine/
