### ISSUE TITLE
[PL][QUEST][Ruins of Ahn'Qiraj] Ring of the Gathering Storm

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#3729]
Link do q: http://www.wowhead.com/quest=8698/ring-of-the-gathering-storm
Nie można oddac questa mając Exalted u Cenarion Circle.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12501-3729questruins-of-ahnqiraj-ring-of-the-gathering-storm/
