### ISSUE TITLE
[EN][Quest] Stinky's Escape

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#373]
Stinky's Escape (http://www.wowhead.com/quest=1222) quest is auto-complete when you take it.

The escort itself is perfect, I've escorted the NPC even though the quest was marked as complete, just to see if it's working as it should.

Currently, if you take the quest, even though it auto-completes, if you leave the NPC on his own, and he dies to a mob, your quest will fail, and it will go back from "Complete" to "Failed".

Anyway, just make so it doesn't auto-complete, and the quest is perfect.

**Comment by Bildo** [comment]
rev. 4353 by Quban
