### ISSUE TITLE
EN Quest, Seek and Destroy, Silverpine Forest

### ISSUE THREAD

**Issue by jonamau5** [Atlantiss/BugTracker#3731]
http://www.wowhead.com/quest=27193/seek-and-destroy#comments i went inside the barn the npc attacked me i didn't kill because i didn't have the quest, once i got the quest i was unable to target him he's stuck midair and can't be aggrod etc.

**Comment by Raknar** [comment]
Checked 10x times respawning, dying and running with him. Can't reproduce your problem.

**Comment by armano2** [comment]
https://github.com/Atlantiss/BugTracker/issues/3994

**Comment by Athinira** [comment]
had same issue as jonamau5
http://imgur.com/1ccFJOe
