### ISSUE TITLE
[PL][Pet] Pet w wodzie

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#3732]
Niekóre pety nie atakują gdy są w wodzie, np:  Shattered Hand Warhound, Loch Buzzard. Nie wiem czy to bug, ale być może tak.

http://www.wowhead.com/npc=17280/shattered-hand-warhound
http://www.wowhead.com/npc=44184/loch-buzzard

**Comment by Asavel** [comment]
koty nie lubia wody

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
I to jest dubel

https://github.com/Atlantiss/BugTracker/issues/1059
