### ISSUE TITLE
goblin hunter pet talent dash

### ISSUE THREAD

**Issue by eikilegion** [Atlantiss/BugTracker#3736]
hi.. im a goblin hunter. new in server atlantiss. tame pet then put talent on dash. then its not working.
no matter how many times i change pet. so i though its not working. then...
when the lvl reach 50 i dg with another hunter that dash work!
so i try to put some bug issue... if any can help me..

my char is goblin hunter nick Eisei 
![wowscrnshot_070515_000536](https://cloud.githubusercontent.com/assets/13178816/8508798/b210e8ce-22a9-11e5-87f8-b211040b91cb.jpg)

that talent icon cant be clik

**Comment by eikilegion** [comment]
and second bug.. aspect of cheetah doesnt stack with mount.. if mount used aspet doesnt work... automaticaly turn of.. even when mounted then clik aspect of chetah the mov speed not speed up... thanks for check and help..

**Comment by Glare** [comment]
This talent should be now in pet abilities as ragular spell.

As for the aspect. I'm pretty sure it's Blizzlike.

**Comment by Jenovas** [comment]
Did you use the spell? Put in on pet spell bar and click it?

**Comment by eikilegion** [comment]
ahhh.. thanks for the teaching.. sorry im new many things not the same as classic.. thanks many thanks
