### ISSUE TITLE
[EN[NPC] Kradu Grimblade

### ISSUE THREAD

**Issue by pofka321** [Atlantiss/BugTracker#3740]
This NPC in Shattarath city is supposed to be a blacksmithing  trainer, but he does not train you or bring any dialog, besides greetings:

![wowscrnshot_070515_141631](https://cloud.githubusercontent.com/assets/13185455/8511474/b6fe1c72-2320-11e5-8450-e951f1bcd48e.jpg)

Source: http://www.wowhead.com/npc=20124/kradu-grimblade#teaches-recipe

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6565-npc-kradu-grimblade/
