### ISSUE TITLE
[EN][Quest][Bloodmyst Isle] The Cryo-Core

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3742]
http://www.wowhead.com/quest=9703/the-cryo-core
completeable but major bugged
there's no spawning crate/target object, so the only path to complete it was via looting sunhawks
thanks

**Comment by coba999** [comment]
still bugged

**Comment by TranceAccount** [comment]
There are no object to be looted.

**Comment by Bildo** [comment]
fixed
