### ISSUE TITLE
[EN][Quest][Bloodmyst Isle]Matis the Cruel

### ISSUE THREAD

**Issue by MirrorWraith** [Atlantiss/BugTracker#3743]
http://www.wowhead.com/quest=9711/matis-the-cruel
after i killed him, he turned into green NPC (friendly)
and the quest didn't finish
thanks
![wowscrnshot_070515_200506](https://cloud.githubusercontent.com/assets/12637348/8511993/e55e82e4-2359-11e5-9a55-ea7080e0772e.jpg)

**Comment by krza91** [comment]
It works. you just need to lead it to the blood watch camp.

**Comment by Juau** [comment]
Did the quest couple days ago. It works as intended.
