### ISSUE TITLE
Quest: Chains of the Anub'ar, Dragonblight

### ISSUE THREAD

**Issue by Swordsister** [Atlantiss/BugTracker#3744]
Scour the Icemist Village and collect three  key fragments from Anub'ar Magi: Arok'ra, Tivax, Sinok.
Spawns: two Tivax the Breakers in far buildings of village and Sinok.  No Spawn on Arok'ra.

**Comment by Astear** [comment]
Actually not bugged. The Arok'ra spawns below the Sinok the Shadowrager (the first one). It's right in the entrance. Here
![wowscrnshot_012616_015128](https://cloud.githubusercontent.com/assets/14007359/12569518/e0e4371a-c3cf-11e5-8146-0b0a25f1b180.jpg)
