### ISSUE TITLE
[EN][Talent][Warrior] Battle trance

### ISSUE THREAD

**Issue by kvarzlami** [Atlantiss/BugTracker#3746]
Fury warrior talent "battle trance" doesnt work, it never triggers.

**Comment by MasterK15** [comment]
hello, you need to post Link if you want report somethinks
do it next time. ATM ill post this link:
http://wowwiki.wikia.com/Battle_Trance_(old_warrior_talent)

no problem

**Comment by kvarzlami** [comment]
Im sorry, thanks.

**Comment by Mordorianin** [comment]
of course it does.

**Comment by Varchord** [comment]
It works. Test something thoroughly before reporting

http://i.imgur.com/uU7tLNY.jpg

**Comment by Varchord** [comment]
Well, that was fast
