### ISSUE TITLE
[EN][Quests] Hero's Call Board

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3747]
The Hero's Call Board should offer certain quests depending on player level and which capital city it is in: http://wow.gamepedia.com/index.php?title=Hero%27s_Call_Board&oldid=2844317#Quest_zones . 

Hero's Call: Arathi Highlands! (http://wow.gamepedia.com/Quest:Hero%27s_Call:_Arathi_Highlands!) should be available as soon as the player is level 24 at the Ironforge board but as a level 25, this quest does not show up.

Adventurers Wanted Dungeon quests aren't available at any level (http://wow.gamepedia.com/index.php?title=Hero%27s_Call_Board&oldid=2844317#Dungeons).

**Comment by TranceAccount** [comment]
Works on PTR.
