### ISSUE TITLE
[PL] [NPC] Creepthess

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#3749]
http://www.wowhead.com/npc=14279/creepthess

Posiada 782 HP, powinien posiadać 1186 HP.

**Comment by Varchord** [comment]
http://wowwiki.wikia.com/Creepthess?oldid=2421050

Powinien mieć 664 HP.

http://wowwiki.wikia.com/Creepthess?oldid=2421050

Jest to wpis z listopada 2010 roku
