### ISSUE TITLE
[PL] [NPC] Ro'Bark

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#3750]
http://www.wowhead.com/npc=14278/robark

Posiada 842 HP, a powinien 1206 HP.

**Comment by Varchord** [comment]
Źle. Powinien mieć 896 hp

http://wowwiki.wikia.com/Ro%27Bark

Ostatnia zmiana jest z października 2012 roku i dotyczy edycji ID, nazwy itp. reszta.

wowhead w sprawach HP dla wszystkich mobów jest nieaktualny dla cata. W przypadku lootu jest nieaktualny dla mobów nieinstancjowanych

**Comment by InformatorPE** [comment]
Jak dobrze, że czuwasz Spite.

**Comment by Varchord** [comment]
wsadz sobie taki sarkazm gleboko w dupe, a potem zajrzyj czy na pewno tam jest

**Comment by InformatorPE** [comment]
Tak
