### ISSUE TITLE
[PL] [NPC] Araga

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#3751]
http://www.wowhead.com/npc=14222/araga

NPC Araga posiada zły drop, dropi itemy uncommon na 30-31 lvl, a powinien 18-22 lvl.

**Comment by Varchord** [comment]
Posiada dobry drop.

http://cata.openwow.com/npc=14222#drop:150-14+1

Itemy z zakresu 30-32. Wowhead jest aktualny dla WoD, nie dla Cata
