### ISSUE TITLE
[EN] [Quest] [Icecrown] Shadow Vault Decree

### ISSUE THREAD

**Issue by LaveGit** [Atlantiss/BugTracker#3754]
When using the provided quest item (http://www.wowhead.com/item=41776/shadow-vault-decree) in front of Thane Ufrang the Mighty, it gives you an error message as seen in the picture below.

![thane ufang](https://cloud.githubusercontent.com/assets/12621497/8534990/1d174048-2442-11e5-884d-08ebc73e4ce3.png)

Link to quest; http://www.wowhead.com/quest=12943/shadow-vault-decree

**Comment by LaveGit** [comment]
Seems it's owrking, you just have to stand at an odd range to the NPC.

**Comment by MercuricUma** [comment]
Wouldn't be bad having a screenshot to know where exactly people have to stand. I keep clicking the item but nothing happens...
