### ISSUE TITLE
[EN][Quest][Catch a Dragon by the Tail]

### ISSUE THREAD

**Issue by jonamau5** [Atlantiss/BugTracker#3755]
The object is spawned but can't pick it up. 
http://www.wowhead.com/quest=27413/catch-a-dragon-by-the-tail#comments

**Comment by Raknar** [comment]
Fixed after compile.

**Comment by Goraix** [comment]
bump

**Comment by jonamau5** [comment]
not sure whether you're asking me to confirm or not, haven't played in
about 2 months, don't have time sadly :(
