### ISSUE TITLE
The Pale Roost

### ISSUE THREAD

**Issue by karrixd** [Atlantiss/BugTracker#3756]
THIS IS BY FAR THE BEST FARMING ZONE FOR LEATHERWORKING, AS MINERS GET ALMOST A STACK PER NOD SOMETIMES I THINK IT'S ONLY FAIR YOU FIX THIS, THE DRAGONS SHOULD BE DROPING FROM THE SKY WITH VERY LOW HP, EVEN THE LOOT IS POOR ON BLIZZ IT WAS AT LEAST 2x ( FOR BLOATED STOMACHS, AND THEIR CONTENT TO ),  http://wowwiki.wikia.com/Stone_Drake IT SAIS IN THE ARTICLE IF YOU DONT BELIVE ME .

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md


I think readme should be updated and forbid ABUSING CAPSLOCK AND SHIFT LIKE THAT
