### ISSUE TITLE
LOGIN ERROR

### ISSUE THREAD

**Issue by marcinpl33** [Atlantiss/BugTracker#3757]
when I tryed to log in it sead there was an error loging in please try again later and ive had this for two days now:/ can someone plz help???

**Comment by Bildo** [comment]
switch to Dragonwrath realm

**Comment by marcinpl33** [comment]
how
?

**Comment by Bildo** [comment]
sorry i understand your question wrong, can you login on webstie ?

**Comment by marcinpl33** [comment]
yea

**Comment by Bildo** [comment]
so change your realmlist E:\World of Warcraft Cataclysm\Data\enGB\realmlist.wtf to set realmlist play.atlantiss.pl

**Comment by marcinpl33** [comment]
its set to that

**Comment by Bildo** [comment]
E:\World of Warcraft Cataclysm\WTF\Config.wtf here too ?

**Comment by marcinpl33** [comment]
yea

**Comment by marcinpl33** [comment]
wait pl?

**Comment by Bildo** [comment]
ta

**Comment by marcinpl33** [comment]
lol nawet nie wiedziałem czekaj zara to zrobie i sprawdze XD

**Comment by marcinpl33** [comment]
nope nie działa

**Comment by Bildo** [comment]
sciagnij moze mini clienta i zobacz czy sie mozesz zalogowac

**Comment by marcinpl33** [comment]
no właśnie drugi raz zainstalowałem i nie działa no :/

**Comment by marcinpl33** [comment]
a wczesniej działało

**Comment by Bildo** [comment]
tobie wyskakuje, ze nie poprawne dane czy ci wow error wywala ?

**Comment by marcinpl33** [comment]
w wow error

**Comment by marcinpl33** [comment]
nie fatal error tylko w grze error

**Comment by Bildo** [comment]
podaj nick postaci

**Comment by marcinpl33** [comment]
w wow czy wogóle konta?

**Comment by marcinpl33** [comment]
jak konta to marcinpl33

**Comment by Bildo** [comment]
no nie ma innej opcji wpisujesz zle haslo albo login, serwer jest online

**Comment by marcinpl33** [comment]
dobrze wpisuje

**Comment by Bildo** [comment]
zmieniales serwer od tego czasu ?

**Comment by marcinpl33** [comment]
nie

**Comment by Bildo** [comment]
wyslij ssa z wowa

**Comment by marcinpl33** [comment]
e którym to guzikiem??

**Comment by marcinpl33** [comment]
bo zapomniałem

**Comment by Bildo** [comment]
Print Screen

**Comment by marcinpl33** [comment]
windows 8

**Comment by marcinpl33** [comment]
a juz nic

**Comment by marcinpl33** [comment]
zara pokaze

**Comment by marcinpl33** [comment]
![wowscrnshot_070815_200523](https://cloud.githubusercontent.com/assets/13223926/8553536/c7d211a2-24ec-11e5-8a8f-d6b638127dd6.jpg)

**Comment by marcinpl33** [comment]
no I nwm co robić

**Comment by marcinpl33** [comment]
zara bede

**Comment by Bildo** [comment]
OMG nie wpisujesz emaila tylko sam login

**Comment by Bildo** [comment]
czuje sie wlasnie strolowany

**Comment by marcinpl33** [comment]
pszepraszam niewiedziałem normalnie to mi email działał srry

**Comment by marcinpl33** [comment]
naprawde moj błąd

**Comment by Kejmil** [comment]
niby pomocny Bildo a spamu narobil jeden z drugim...
:D

**Comment by Asavel** [comment]
ahahah :D
