### ISSUE TITLE
[EN][QUEST][HORDE] Weapons of Mass Dysfunction

### ISSUE THREAD

**Issue by XxaklxX** [Atlantiss/BugTracker#3759]
There is a polish topic about it, but google translate wasn't very helpfull,
The third Hellscream Demolisher that should crumble doesn't break, neither the globin is there to be kicked. It is not working for other players too.
While I was trying to do the quest, some player did the second demolisher to crumble, but it didn't work for me.
http://www.wowhead.com/quest=26294/weapons-of-mass-dysfunction
https://www.youtube.com/watch?v=lRCH59npB70
![wowscrnshot_070715_142857](https://cloud.githubusercontent.com/assets/13158834/8554386/b0d98316-24b7-11e5-84cc-6fc727791d52.jpg)
![wowscrnshot_070715_142904](https://cloud.githubusercontent.com/assets/13158834/8554396/b826804c-24b7-11e5-9306-43e3c8db7ac2.jpg)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3758

**Comment by gesik2** [comment]
Quest still doesn't working, there is no npc near third Demolisher (https://youtu.be/lRCH59npB70). And all the npc talk only after checking Demo, and as You can see on the YT, npc should talk also before.

**Comment by Navedonar** [comment]
.
