### ISSUE TITLE
[EN][Quest][Horde] Spy Infestation

### ISSUE THREAD

**Issue by aranguard** [Atlantiss/BugTracker#3760]
This is a horde side Quest from Stonetalon Mountains.Its the fourth step of a six quests chain.
1.All's Quiet on the Southern Front
2.Beginning of the End
3.The Turd Problem
4.Spy Infestation
5.Final Delivery
6.To Battlescar!
Link : http://www.wowhead.com/quest=26076/spy-infestation

Number 3 and 5 marked as fixed in changelog. rev. 4492 But this quest not works.Gas bomb seems like work well but there are no alliance spy on area.

Youtube link: https://www.youtube.com/watch?v=YV2GNPqltkI

**Comment by duttyy** [comment]
You can use the gas bomb and you can 'hear' the spy's when you walk by, but the bomb doesn't unlock them wich u cant 'see' and kill them.
