### ISSUE TITLE
[EN[Quest][Horde] Barrier to Entry

### ISSUE THREAD

**Issue by aranguard** [Atlantiss/BugTracker#3761]
It's 3. step of 6 quests chain.

1.Warchief's Command: Stonetalon Mountains!
2.We're Here to Do One Thing, Maybe Two...
3.Barrier to Entry
4.The Missing Blastgineer
5.Alliance Attack Plans
6.Krom'gar Fortress
Link : http://www.wowhead.com/quest=25999/barrier-to-entry

Number 2 marked as fixed in changelog and it works now.rev 4493

About that quest Krom'gar Elf Killers on area (land mines), it seems good and also click marker shown when you cursor on.But they are not clickable.Youtube link below.

https://www.youtube.com/watch?v=5IVNb__-gOs

**Comment by xxMAKMAKxx** [comment]
Just wanna add that this is quite important quest becasue without him we can't move forward in Stoleton quests... sadly

**Comment by vegichan** [comment]
Number 2 is still bugged. Tried it yesterday, if the caravan gets attacked by one of the elves, it gets stuck.

**Comment by xxMAKMAKxx** [comment]
But after death when u ress u can complete the quest...

**Comment by duttyy** [comment]
you can do nr2 by FIRST killing the mobs in the way and then take the caravan.. sadly nr3 is not working

**Comment by HelAmarth** [comment]
Number 6 does't work too...the "heavy guns" you have to use to shoot enemies in the quest does not appear.

**Comment by dstn3422** [comment]
those bugs were reported months ago! they just don't care about them honestly...

**Comment by Angelo-DM-** [comment]
Quest "We're Here to Do One Thing, Maybe Two..." is bugged as vegichan says...  but is doable. Just clear the road before taking the quest... 2 mobs near "The fold" in stonelaton mountains and 2 mobs on the road on the left of silverwind refuge. (you should remove the PVP flag on the caravan)

Quest "Barrier to Entry" is totally bugged!

4.The Missing Blastgineer
5.Alliance Attack Plans
6.Krom'gar Fortress

Thoose quests can't be taked!

**Comment by Bastion** [comment]
![bez nazwy-3](https://cloud.githubusercontent.com/assets/1584564/11016350/1f7c5adc-857f-11e5-935f-ff8d5072e996.jpg)

**Comment by vragni** [comment]
Still buged

**Comment by thissideup-atlantiss** [comment]
Still bugged.

**Comment by SlendyMan0** [comment]
Aaaaand... Still bugged. Will be year soon.

**Comment by BAndysc** [comment]
Yeah still bugged :/
