### ISSUE TITLE
[EN][QUEST] Entry Into Karazhan

### ISSUE THREAD

**Issue by Beponator** [Atlantiss/BugTracker#3763]
The box where http://www.wowhead.com/item=24514/first-key-fragment is there but a problem is that
i can't  loot it.please fix it http://www.wowhead.com/quest=9831/entry-into-karazhan

**Comment by xolon** [comment]
There is sometimes a bug with lootable objects "is already being looted" if that is happening just wait 10-15 min and you should prolly be able to open it

**Comment by Quban** [comment]
box spawns npc, you have to kill it and loot key from corpse, i've changed spawn spot so its blizzlike now

**Comment by Quban** [comment]
fix soon
