### ISSUE TITLE
[EN] [Quest] [Dun Morogh] It's Raid Night Every Night

### ISSUE THREAD

**Issue by Tiennshan** [Atlantiss/BugTracker#3766]
Quest It's Raid Night Every Night won't start after taking it from questgiver.

http://www.wowhead.com/quest=25932/its-raid-night-every-night

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3134

https://github.com/Atlantiss/BugTracker/blob/master/README.md
