### ISSUE TITLE
[EN][Dungeon] Dire Maul Capital Gardens (West)

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3770]
The dungeon Dire Maul Capital Gardens (West) (http://www.wowhead.com/zone=2557/dire-maul  West wing) accessed by the random dungeon finder has every mob inside doing too much damage.

Every mob is doing about 450 damage per melee hit on an appropriate level tank, which is about 1/5 - 1/6th of the health of the average tank at that level.
The mobs should do less damage.

Take for example Eldreth Apparition  (http://www.wowhead.com/npc=11471/eldreth-apparition)  (https://wow.freakz.ro/npc_finder.php?npc=11471  (linking this because it shows the damage it should do)) it should do 465 - 615 unmitigated damage. The average tank will have more than 45% melee damage reduction, so it would hit the tank for 256 - 338 . The damage should probably even lower than this.

Also this video of the times of cataclysm where the mobs are doing about 150 - 160 damage per melee hit as they should: https://www.youtube.com/watch?v=qTSG3mcc9qs

Apparently some boss's melee hits are more or less correct in Atlantiss. Definitely not the trash tho.

**Comment by wrehas** [comment]
https://wow.freakz.ro doesn't seem like a reliable source (although it may be just that Dire Maul got changed), for example: https://wow.freakz.ro/npc_finder.php?npc=13285 says HP=19020 while http://www.wowhead.com/npc=13285/death-lash says HP=9534 so it's hard to say how reliable it is.

**Comment by Bildo** [comment]
wowhead isn't reliable source either because of wod

**Comment by wrehas** [comment]
True, I'm just pointing out that I don't think that source is reliable.

**Comment by ahtebe** [comment]
Well even if you don't find the source reliable, the fact is that higher level dungeons don't have anywhere near the damage of Dire Maul West.
Here is a video of the times of cataclysm where the mobs are doing about 150 damage per melee hit: 
https://www.youtube.com/watch?v=qTSG3mcc9qs

**Comment by wrehas** [comment]
Well, I'm going to find a talent calc and see how much dmg reduction he should have, that should give a somewhat more accurate number.

**Comment by wrehas** [comment]
Well my guesstimate would be 350-500 (140-200 from video, with an estimate of 40% reduction from armor (same level tanks should have about the same armor, right?))

**Comment by ahtebe** [comment]
About 45% armor reduction for plate. Bears should have about the same too.

**Comment by wrehas** [comment]
Well, from my guestimate it seems that freakz has non-cata info as well. BTW is it worth it to make changes with guestimates or no, cause i can turn that into an sql query quite easily.

**Comment by sunshineinabox** [comment]
According to http://cata.openwow.com/npc=11471 the Elderth Apparition does 439-597(pre-mitigation) damage.
