### ISSUE TITLE
AL'AKIR-Ice Storm

### ISSUE THREAD

**Issue by Skeetis** [Atlantiss/BugTracker#3771]
Umiejętność zabija pety w pare sekund, na przykładzie dk zabija mi ghoula+gargulca w 2-3 sekundy co troche utrudnia go na wersji hc. Brak działanai redukcji 90% dmg od spelli aoe.

**Comment by Bildo** [comment]
duplikat, niestosowanie sie do zasad https://github.com/Atlantiss/BugTracker/issues/3636
