### ISSUE TITLE
DK starting zone - Horses

### ISSUE THREAD

**Issue by Xianji** [Atlantiss/BugTracker#3772]
The horses have the following problem(I was playing a gnome):

* They can only walk, and if you toggle run they will stop after .5 seconds.
* If they aggro something they will fight it until only of them dies.
* If you dismount they will run back to their original spot.

All in all this means that you have to slowly waddle your way past any and all monsters that might be in your way. If you engage ANY monster during your journey you will have to do it all over again.

It does however work if you manage to turn it in.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
