### ISSUE TITLE
The seer's relic - Quest bugged

### ISSUE THREAD

**Issue by Xianji** [Atlantiss/BugTracker#3774]
In Hellfire Peninsula, the quest works but cannot be turned in:

http://puu.sh/iTkv3/4c07ef7d0f.jpg

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by rasmodeus** [comment]
I just tested this quest, and it works perfectly! I was able to turn it in.  Only issue is the quest marks as "completed" too early, you just have to stay through the entire scene that plays out.  If you actually leave the scene too early, you will eventually get a quest failed message too.

**Comment by schwim0341** [comment]
Then it does not "work perfectly".  The system tells you the quest has been completed before it actually has been completed.  For it to "work perfectly", it would need to wait until it was actually completed to state such a thing.

Quest is still bugged in this regard.

**Comment by TheCopacabanaMan** [comment]
The quest not  "work perfectly" at all. I stayed the entire scene, got the message "Quest completed", waited another minute just in case.
When i turn in, i cannot, because the button "Complete" is still gray, and quest is failed

What chorto "work perfectly" you mean?
