### ISSUE TITLE
[En] [Instances] Heroic Locks Triggered Through RDF

### ISSUE THREAD

**Issue by Victabob** [Atlantiss/BugTracker#3777]
As a heavy Cata retail player, I remember specifically that heroic dungeon locks do not trigger when you que through Random Dungeon Finder. Example here: http://www.wowhead.com/forums&topic=202865/heroics-still-have-a-lockout
Therefore, I believe that the current lock triggers that happen via Random Dungeon Heroic are not blizzlike and should be removed and excempt from dungeon locks done via Random Dungeon.

**Comment by Varchord** [comment]
already exist

https://github.com/Atlantiss/BugTracker/issues/696
