### ISSUE TITLE
[EN][Quest][Storm Peaks] Valkyrion Must Burn

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3785]
http://www.wowhead.com/quest=12953/valkyrion-must-burn

"Use the Valkyrion Harpoon Guns to burn 6 Dry Haystacks."

There are no Dry Haystacks. http://www.wowhead.com/npc=30096/dry-haystack can not complete quest.

**Comment by Illusionist87** [comment]
bumping.
Dry Haystacks are still missing.

**Comment by Aequitass** [comment]
Bump

**Comment by Bildo** [comment]
fixed

**Comment by Danbar1976** [comment]
no fixed i can't use harppons

**Comment by Malylolek** [comment]
This should help :100: 

- Update creature_template SET npcflag=npcflag|16777216 WHERE entry = 30066;

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11290-questnpc-next-vehicles/

**Comment by Danbar1976** [comment]
i  checked it today still not working

**Comment by Malylolek** [comment]
No one upload my fix. Need to wait

**Comment by Malylolek** [comment]
Should work after rev. [5164](http://atlantiss.eu/changelog#rev5164)
