### ISSUE TITLE
[EN][PL]Instance

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#3786]
I found 2 bugs on Dire Maul and Razorfen Downs (Znalazłem 2 bugi na Dire Maul i  Razorfen Downs)

Dire Maul - http://www.wowhead.com/zone=2557/dire-maul
 - First: npc hit for 200-350 hp (npc biją po 200-350hp)
 - Second: Hydrospawn https://github.com/Atlantiss/BugTracker/issues/272

Razorfen Downs - http://www.wowhead.com/zone=722/razorfen-downs
 - First: on one place has spawn 2 npc (na jednym miejscu sa 2 npc)
 - Second: bad graveyard we are teleported to Southen Bareens, and we should teleported to Thausand Needles (zły cmentarz. Jestesmy teleportowani do SB a powinnismy to 1k Needles)

That same it is in RFK (first bug) - to samo w RFK(pierwszy bug)

Sorry for my English:)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md


I loled at 

> That same

**Comment by eryczek1615** [comment]
Sorry i used translate in this sentences
So i must close this issue and do it 2 other?

**Comment by Varchord** [comment]
1 bug/instancja, 1 report
Byleby dubli nie robić
