### ISSUE TITLE
[EN][Quest] Missing dailies from Ironforge and Darnassus

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#379]
The trainers in IF <del>and Darna</del> are missing the daily quests added in 4.1 patch. (Probably quests from <del>Thunder Bluff and</del> Undercity are also missing)

<del> Alegorn in Darnassus (http://www.wowhead.com/npc=4210) should give us the following quest:
<del>- The Secret to Perfect Kimchi http://www.wowhead.com/quest=29313
<del>- Remembering the Ancestors http://www.wowhead.com/quest=29314
<del>- Back to Basics http://www.wowhead.com/quest=29316
<del>- Ribs for the Sentinels http://www.wowhead.com/quest=29318
<del>- Spice Bread Aplenty http://www.wowhead.com/quest=29357

Daryl Riknussun (http://www.wowhead.com/npc=5159) in IF should give:
- A Fowl Shortage http://www.wowhead.com/quest=29352
- A Round for the Guards http://www.wowhead.com/quest=29351
- Can't Get Enough Spice Bread http://www.wowhead.com/quest=29355
- I Need to Cask a Favor http://www.wowhead.com/quest=29356
- Keepin' the Haggis Flowin' http://www.wowhead.com/quest=29353

Grimnur Stonebrand (http://www.wowhead.com/npc=5161) in IF should give:
- Cold Water Fishing http://www.wowhead.com/quest=29342
- Fish fer Squirky http://www.wowhead.com/quest=29344
- Live Bait http://www.wowhead.com/quest=29347
- One fer the Ages http://www.wowhead.com/quest=29343
- The Gnomish Bait-o-Matic http://www.wowhead.com/quest=29350

<del>Astaia (http://www.wowhead.com/npc=4156) in Darnassus should give:
<del>- A Slippery Snack http://www.wowhead.com/quest=29325
<del>- An Old Favorite http://www.wowhead.com/quest=29359
<del>- Happy as a Clam Digger http://www.wowhead.com/quest=29321
<del>- Stocking Up http://www.wowhead.com/quest=29323
<del>- The Sister's Pendant http://www.wowhead.com/quest=29324

These quest are linked with those from SW, meaning that out of quests offered each day in every city you can only choose one cooking and one fishing quest.

**Comment by Propolys** [comment]
The NPCs have been added (supposing they missed before) but they still don't give the respective cooking/fishing dailies.

**Comment by monibu** [comment]
Updated, quest in Darnassus and Thunder Bluff are available now
