### ISSUE TITLE
[PL][Spell][Death Knight] Raise Dead

### ISSUE THREAD

**Issue by Mietla122** [Atlantiss/BugTracker#3791]
Bug polega na tym, że dmg przyzwanego risen ghoula(w frost i blood) nie skaluje się z attack power gracza.dodatkowo zauważyłem też, że armia jak i risen ghoul nie używa clawa. http://i.imgur.com/YtutdaO.jpg

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
ghoul we frost i blood powinien byc po prostu kopia ghoula z unholy ze skillami na autocascie i brakiem kontroli gracza
podobnie zreszta army od the dead powinna uzywac clawa, o tauntowaniu wszystkiego co nie jest bossem nie wspomne

**Comment by Hextall** [comment]
Raise Dead - http://cata.openwow.com/spell=46584
Bump! Priorytet tego powinien być wysoki. Ciężko znaleźć informacje na temat tego jak dokładnie powinno to działać. Na pewno wiadomo, że u nas attack power peta nie skaluje się ze statystykami gracza (u nas ghul z autoattacku bije po około 160). Z filmików wynika też, że powinien autocastować Clawa. https://youtu.be/FlySOYaKvDs?t=1m58s 
Na chwile obecną Raise Dead w specu Frost/Blood  (jeśli chodzi o DMG) jest bezużyteczne.

**Comment by Kejmil** [comment]
leapa tez
https://youtu.be/C4HzNcttNdc?t=115

**Comment by Aival94** [comment]
The [Raise Dead](http://www.wowhead.com/spell=46584/raise-dead) Ghoul stop attacking after the first mob it target die.It should change target and start attacking after the the mob died.

**Comment by Kejmil** [comment]
tozto juz 8 miesiecy od zgloszenia i 2-3 lata odkad ten bug jest, jak ten czas leci ( ͡° ͜ʖ ͡°)

**Comment by Jenovas** [comment]
Taunt, Claw, Leap added in rev 5080.
The Ghoul will also start scaling with owner's AP in rev 5081.
Closing report.
