### ISSUE TITLE
[EN][Quest][The Storm Peaks] The Brothers Bronzebeard

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3792]
http://www.wowhead.com/quest=12973/the-brothers-bronzebeard

"Accompany Brann Bronzebeard and his flying machine to Frosthold."

Can not get on the flying machine. I get green mount arrow interface but when I click it I don't get on plane. Can not complete quest.

**Comment by Bildo** [comment]
fixed
