### ISSUE TITLE
[EN][Instance] Normal Throne of the Tides - Neptulon's Cache

### ISSUE THREAD

**Issue by Aurelia1993** [Atlantiss/BugTracker#3793]
The chest should always loot out 2 blue items and currently, it's hit or miss. One time it's 2 items, another time it's only 1. Easily confirmed by watching videos from retail Cataclysm.

**Comment by Helbringer** [comment]
You need a wowhead link

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1156 duplicate
