### ISSUE TITLE
Korm Blackscar missing frequently

### ISSUE THREAD

**Issue by kathydunnigan** [Atlantiss/BugTracker#3797]
Twice I've gone to turn in a quest to Korm Blackscar and he's missing. I had to wait til today to turn in a quest from yesterday. Today, I got another quest behind turning one in, and when going to turn in this one, he wasn't there. My GM told me to report it to BT. This is my first time, so hopefully I'm doing it right. Have a good one!

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
