### ISSUE TITLE
[EN][PL][Instance] Dire Maul

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#3798]
I found 2 bugs on Dire Maul (Znalazłem 2 bugi na Dire Maul)

Dire Maul - http://www.wowhead.com/zone=2557/dire-maul
 - First: npc hit for 200-350 hp (npc biją po 200-350hp)
 - Second: Hydrospawn #272

Edit.
Quban all npc hits for 300-350 hp(on 85 lvl without items and he hits me for 500-800hp), boss too.
Wszystkie npc bija po 300-350 hp (na 85 lvl bez itemów biły mnie za  500-800hp), bossy też.

NPC on the north (Gordok Commons)should hit for 100-230, boss from 210-350
NPC na północy(Gordok Commons) powinny bić za 100-230, bossy od  210-350

NPC on east(Warpwood Quarter) should hit for 70-100, boss from 100-200 and normal npc from 30-50 hp
NPC na wschodzie(Warpwood Quarter)powinny bić za 70-100, bossy od 100-200, a zwykłe npc od 30-50

NPC on west(Capital Gardens) should hit for 100-200, boss from 300-400
NPC na zachodzie (Capital Gardens) powinny bić za 100-200, bossy od 300-400

I found more bugs znalazłem więcej bugów

At that moment we can't finish Capital Garden and Gordok Commons
Capital Garden - when we destroy all of 5 crystal the prison don't opens himself.
Gordok Commons - We can't open thhe door after General Fengus
https://github.com/Atlantiss/BugTracker/issues/3698 i found him once but other time he walkin in textures
Na ten moment nie możemy ukończyć Capital Garden i Gordok Commons
Capital Garden - gdy zniszczymy wszystkie z 5 kryształów więzienie nie otwiera się
Gordok Commons -  nie moze otworzyc drzwi po Generale Fengusie

Related Issues - Powiązane zgłoszenia
https://github.com/Atlantiss/BugTracker/issues/3668
https://github.com/Atlantiss/BugTracker/issues/3698
https://github.com/Atlantiss/BugTracker/issues/3770
https://github.com/Atlantiss/BugTracker/issues/3795

**Comment by Quban** [comment]
Can you write here more specific data on the first issue, which npcs do too much dmg and what should it be instead? 
Jakies bardziesz szczegolowe dane do 1 zgloszenia? i jak mozna jakies id npckow ktorzy bija za wiele i ew po ile powinny bic?

**Comment by eryczek1615** [comment]
Quban wszystkie npc tam maja tak bug wiec chyba się nie opłaca linków wklejać. Postarałem się znaleźć ile powinni zadawać obrażeń na danej cześci

**Comment by Quban** [comment]
ok dzieki :)

**Comment by Quban** [comment]
ok jeszcze poprawie niedlugo problem krysztalow i wtedy zamkne tamten temat z krysztalami

**Comment by Lizes** [comment]
Problem z kryształami dalej występuję dziś o godzine 3-4 nad ranem próbowałem zrobić po achi i chociaż jest animacja iż kryształ został zdezaktywowany to po kliknięciu 5 dajlej nie można przejść do bossa
