### ISSUE TITLE
[EN][Quest][Silverpine Forest] Transdimensional Warfare: Chapter III

### ISSUE THREAD

**Issue by poilmok** [Atlantiss/BugTracker#3803]
Hello

I have a problem with this quest : http://www.wowhead.com/quest=27518/transdimensional-warfare-chapter-iii

When I kill the Archmage Ataeric , the quest is not valid.

No matter how many times I try

Thanks for helping

**Comment by Quellz** [comment]
You're not supposed to kill the boss. He will spawn fairly easy enemies around him. After killing some, he will disappear along with the barrier.
