### ISSUE TITLE
Melee Hit box Range

### ISSUE THREAD

**Issue by kevlarz** [Atlantiss/BugTracker#3804]
Hello, 

There is a bug with the hit boxes of mobs for melee. 

Any mob that is meant to have a bigger hit box than normal isnt taken into account for on the server.

It treats all mobs as small mobs and you have to be stood right on top of them to do melee auto attacks. Please fix this SOON !!!! 

Thank you.

**Comment by Axahus** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
God damn! That's my job man!


And what OP wrote isn't true. Atramedes for example. Big ass hitbox.
Show us examples of wrong hitboxes to prove your point

**Comment by Kejmil** [comment]
report specific mobs, because mechanic is working properly
