### ISSUE TITLE
[EN] [Instance] Wailing caverns not completable / deadmines mobs

### ISSUE THREAD

**Issue by Snow22** [Atlantiss/BugTracker#3806]
The event to escort the npc to trigger the last boss in wailing caverns does not work. The npc is there with the right dialog option but clicking it causes nothing to happen. Making the instance impossible to finish and forcing all in said dungeon group to leave and receive deserter status.
At least all if not 99% of deadmines mobs do not drop any coin. Mostly only cloth is dropped and nothing else.

First error report so apologies if It isn't presented properly

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
