### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] Can you smell what the loktar is cooking

### ISSUE THREAD

**Issue by Haures** [Atlantiss/BugTracker#3807]
http://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking

Kingslayer Orkus should appear in the water near southshore , but or the Npc is missing or the phasing isnt working in that area

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
lol. really mate?

**Comment by Haures** [comment]
Sorry its the first time sending a ticket here and dont understand so good this , better delete it...

**Comment by Varchord** [comment]
Just look at my reports for example

**Comment by Varchord** [comment]
Now it's ok

**Comment by Quellz** [comment]
Still borked, and it's part of the main questline, needs a fix.

**Comment by corvusaraneae** [comment]
Seconding this problem. Still borked.

**Comment by Dearkus** [comment]
Still not there.

**Comment by BAndysc** [comment]
Finally fixed (whole chain) ^.^
