### ISSUE TITLE
[PL][Spell][Warrior] Intervene

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#3811]
Nie powinno się dać użyć Sap na celu z Intervene, jeżeli Warrior, który daje Intervene jest w zasięgu Sapa. U nas działa to tylko wtedy, kiedy Warrrior nie ma combat.

http://cata.openwow.com/spell=3411 - Intervene
http://cata.openwow.com/spell=73154 - Sap

**Comment by debtheone** [comment]
bump

**Comment by Jenovas** [comment]
Ok po kolei.
Jest Warrior i powiedzmy Priest, Warrior daje intervene na priesta i w tym momencie priest powinien być "immune" na sapy dopóki intervene nie zejdzie?

**Comment by debtheone** [comment]
roguna daje sapa buff z intervene znika warror nie dostaje sapa bo jest w cb

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
