### ISSUE TITLE
[EN] [Quest] [Stormwind] Twilight Shores

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3812]
http://www.wowhead.com/quest=28832/twilight-shores

"Speak with Lieutenant Fawkes at Highbank in Twilight Highlands."
"Right then, just hop in the seaplane behind me and I'll fly yeh to the Highlands."

Fargo Flintlocke does not offer me this quest. He has a yellow exclamation mark over his head  for this quest but when I click on him no interface opens to offer me this quest. I have completed all prerequisites that lead up to this quest. When working I should be able to click the plane and ride it to twilight highlands.

**Comment by Thefakemccoy** [comment]
That is where every one has stopped. That quest is turned off because TH is not open to quest in yet. The only quest that are working in TH is the CoC (arena)
