### ISSUE TITLE
[EN] [Quest] [Hillsbrad Foothills] Can You Smell What the Lok'tar is Cooking?

### ISSUE THREAD

**Issue by poilmok** [Atlantiss/BugTracker#3816]
Hello, 

I have a problem with this quest : http://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking

Kingslayer Orkus is not here so I don't finish the quest

Thanks for helping

**Comment by Quban** [comment]
dup. of https://github.com/Atlantiss/BugTracker/issues/3807
