### ISSUE TITLE
[EN][NPC] Silithid Harvester

### ISSUE THREAD

**Issue by Philippe777** [Atlantiss/BugTracker#3818]
Now that the Cataclysm has arrived, this bug should be tameable and be part of the "Beetle" pet family. But instead, you get a message that he is an "invalid target" when you try to tame him. :( (I wanted him too...)

http://www.wowhead.com/npc=3253/silithid-harvester#comments (Top comment mentions him being tameable as early as 4.0.3 / 4.0.6)

**Comment by marrog91** [comment]
Just tamed this mob so I can say it's tameable now. However after taming it and relogging it changes its model to old pre-Cata blue silithid instead keeping green beetle skin. Clearing cache doesn't work.
