### ISSUE TITLE
[EN][BG&Arenas] TB

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/BugTracker#3819]
Hi Atlantiss,

I joined Tol Barad last nite, http://www.wowhead.com/zone=5095/tol-barad,
& upon leaving the central tower start zone, I was a BG Goddess.
I was still the same height in the air as start zone, never came down.
![tb goddess 01](https://cloud.githubusercontent.com/assets/12092984/8674279/e98b4ffc-2a0a-11e5-89af-6dc03048e447.jpg)
TY
SwimzSharkz
- I did log out to try to repair it, which it did, then luckily came back to game FTW.

**Comment by Helbringer** [comment]
This is not to do with Tol barad at all im sure. Ive had this bug about 5 times when running off a tall surface and then i stay at the same height. Ive had it in Tb, Tbp, grim batol, zul gurub etc etc
