### ISSUE TITLE
[EN][NPC] Olm The Wise

### ISSUE THREAD

**Issue by Philippe777** [Atlantiss/BugTracker#3820]
Cataclysm new skin. Still using old world models. Should be neutral, is hostile. http://www.wowhead.com/npc=14343/olm-the-wise

**Comment by AnakyWacky** [comment]
Confirmed. Should look like this:
http://www.wowhead.com/npc=14343/olm-the-wise#screenshots:id=220899

**Comment by Luna-maria** [comment]
display id: 37568

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12235-3820npc-olm-the-wise/
