### ISSUE TITLE
[EN][Quest][Durotar] Ghislania

### ISSUE THREAD

**Issue by comnet256** [Atlantiss/BugTracker#3832]
http://www.wowhead.com/quest=25257/ghislania

Upon talking to the npc "Ghislania" it should change faction to be attack-able,currently it is not the case.

Other two quests, "Griswold Hanniston" and "Gaur Icehorn" are identical except their starting faction is set differently and those two npcs are attack-able upon talking to them.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/1732
