### ISSUE TITLE
Can't resurrect.

### ISSUE THREAD

**Issue by wedoweed** [Atlantiss/BugTracker#3833]
So I died during a dungeon; and when i went to my corpse to resurrect myself, a notification appeared saying that I "must enter the instance to recover your corpse". There is no way to resurrect the normal way and there is no healer NPC to resurrect me. Please help me! *sorry for my english; it's not my native language*

**Comment by Aival94** [comment]
You probably went ot wrong instance or could not recover because you were not in a party.Except if it told you that "Your corpse is not in the instance" which happen sometimes when you dc and for this one you need spirit healer for sure as no corpse still exist.

**Comment by Probullet25** [comment]
Use /script RepopMe ();

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
write a ticket, use script which you can see above

**Comment by wedoweed** [comment]
I solved the problem another way. I went out of the dungeon trying to find a graveyard, and I got pretty far of the dungeon cave. So I fount a sort of animals graveyard but there was no NPC healer. So I pushed the button "return to graveyard" and this time it took me to the NPC healer and I could resurrect. Thank you all for your prompt help. ^^
