### ISSUE TITLE
Quest Giver Bugged!

### ISSUE THREAD

**Issue by masterskull1996** [Atlantiss/BugTracker#3834]
So, I was doing the "Hero's Call: Twilight Highlands" quest chain and I came across this npc who refuses to give me the quest.

https://www.youtube.com/watch?v=wDCtdMeJIQ4

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
also, it is done on purpose i think, TH is not available for now
