### ISSUE TITLE
No NPC's

### ISSUE THREAD

**Issue by Terrar2** [Atlantiss/BugTracker#3835]
I used Hearthstone today and teleport to Orgrimmar and since this teleportation i can't see any NPC not only in Orgirmmar but in every location
![wowscrnshot_071615_115813](https://cloud.githubusercontent.com/assets/7278448/8720274/049a7f4a-2bb2-11e5-98b5-48515232028a.jpg)
![wowscrnshot_071615_115823](https://cloud.githubusercontent.com/assets/7278448/8720275/04a11896-2bb2-11e5-9189-1e9c1e77a299.jpg)

**Comment by Rushor** [comment]
phasing bug

**Comment by arekczup** [comment]
your internet go down .......... in this moment.

**Comment by Terrar2** [comment]
How can i fix this phasing bug?

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by BAndysc** [comment]
@Terrar2, write a ticket
