### ISSUE TITLE
[EN][NPC] Bemarrin - Silvermoon city blacksmithing trainer

### ISSUE THREAD

**Issue by sargoth** [Atlantiss/BugTracker#3837]
The Blacksmith trainer in Silvermoon is not showing all plans which you can learn only the ones for higher levels of the profession. http://www.wowhead.com/npc=16669/bemarrin
![wowscrnshot_071615_154236](https://cloud.githubusercontent.com/assets/9791061/8722841/56865e0e-2bd1-11e5-9efa-56c01d0867ed.jpg)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3129 duplicate
