### ISSUE TITLE
[PL] Spell/Class Druid - Forms

### ISSUE THREAD

**Issue by Sobolek** [Atlantiss/BugTracker#3839]
Witam, jak wiadomo druid który zostanie "przytwierdzony" do ziemi np. czarami takimi jak Frost Nova Maga, rootsami Druida bądź też shamana z telentem 2/2 POWINIEN mieć możliwość wyjścia z tego efektu poprzez prostą operację jaką jest wyjście z formy przykładowo: kota do formy klasowej.
Na Atlantissie będąc w takim efekcie można wchodzić i wychodzić z dowolnej formy do innej wciąż pozostając pod działaniem czaru.

Kolejną sprawą jest możliwość rzucenia przez Shamana na formę druida HEX'a, druid w formie POWINIEN być immune na taki efekt. W żabę co prawda się nie zmienia ale skilli podczas działania HEX'a używać nie może.

**Comment by Asavel** [comment]
:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D zmien spec

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

Poza tym tylko resto i balas może z rootsów wychodzić. Do zamknięcia. Nie dość, że nie poprawne zgłoszenie to jeszcze 2 bugi w jednym zgłoszeniu

**Comment by Kejmil** [comment]
oddalam to zgloszenie

**Comment by Sobolek** [comment]
Niepoprawne pisze się razem. Lepiej dostosować się do potrzeb servera niż odwrotnie, good job.

**Comment by Varchord** [comment]
Dzieki za info
