### ISSUE TITLE
[EN][Quest] Rocket Rescue

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#384]
Rocket Rescue (http://www.wowhead.com/quest=25050) auto-completes when you take it.

Here's how the quest should work - https://www.youtube.com/watch?v=SFGGsLbyeHA

**Comment by BAndysc** [comment]
Fixes in rev 4990

**Comment by kostas4949** [comment]
Not sure for others, but I can't seem to do it. I have no spells on the bar that appears while in the balloon. Have tried disabling all addons, relogging, dying,retaking quest. Nothing seems to work.

**Comment by BAndysc** [comment]
God damn, I had this problem from time to time, but I thought it is only my local server problem, will look into it.

**Comment by lourrific** [comment]
May 23, 2016 and I'm stuck on this stupid balloon. The spells on the bar are my own and they don't work for quest. There are no rocket or bomb abilities on the action bar. I need a GM to get me off this thing.

**Comment by kostas4949** [comment]
You definitely don't need a GM for it. You can simply relog

**Comment by Karathe** [comment]
As of 02.06 quest still remains bugged. Instead of balloon abilities I see only my own.

**Comment by BAndysc** [comment]
Good news: I think now I finally found the cause. Bad news: I won't be able to fix it before Monday, because it is larger thing than I thought

**Comment by BAndysc** [comment]
It should work since rev [5042]. Let me know if it still bugs

**Comment by hawcik** [comment]
Still bugged. Didn't count Southsea Blockader if you are too far away from them. Working just on one boat when killing them.

**Comment by MercuricUma** [comment]
Works perfectly fine now and when you click on return to gadgetzan you're thrown into the water
