### ISSUE TITLE
[EN][Instance][Wailing Caverns] Muyoh bugged

### ISSUE THREAD

**Issue by Timoca** [Atlantiss/BugTracker#3840]
http://www.wowhead.com/npc=3678/muyoh

When you've killed all bosses you run to Muyoh and speak with him so a escort mission to the final boss starts.  The issue is that when you try to press the white sentence to get him walking, nothing happens.  Done the dungeon 4 times today, hasn't worked once.

**Comment by Wolffenstein** [comment]
Fixed in rev 4523.

**Comment by Quban** [comment]
instance works
