### ISSUE TITLE
[EN][Mining] Placement of veins

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#3841]
So, i just started a toon with mining here and first thing i noticed is that there are some veins that are kinda unreachable unless you have flying mount and a lot of time. For example veins instead of spawning on the ground spawn on the tree above them or all the copper veins in elwynn forest Jasperlode Mine insted of spawning inside they spawn on top of it :/

**Comment by blekx** [comment]
yes, im new here, comming from mormerly most crowded world server and im enjoying everything here.
except flying ORE VEINS (not placed inside the mine, but on the top survace above it)
and COMBAT BUGS, once i realized that some citter was activated by my aoe, didnt die, and didnt leave me go, day after i was trying to find another citter, but rather killed myself...
