### ISSUE TITLE
[PL][Web]Register Captcha Image error

### ISSUE THREAD

**Issue by Qukcyf** [Atlantiss/BugTracker#3847]
Chciałem zarejestrować nowe konto i zacząć grać na waszym serwerze lecz nie da się przepisać kodu z obrazka (bo nie wyświetla się on) sprawdzone na przeglądarkach Opera, Chrome, Firefox i Micresoft Edge. Screen dodany z Opery. A to raczej nie sprzyja nowym graczom.
![111](https://cloud.githubusercontent.com/assets/13392844/8761384/b5d2fc3a-2d4f-11e5-83e1-5d20d279c4d3.png)

**Comment by armano2** [comment]
solved
