### ISSUE TITLE
[EN][Quest] Secrets of the Tower

### ISSUE THREAD

**Issue by 0609zeus90** [Atlantiss/BugTracker#3852]
Don't work quest Secrets of the town. Alliance, Westfall
http://www.wowhead.com/quest=26290/secrets-of-the-tower

**Comment by cubson** [comment]
For me it works. You need to wait some time. Title of your post should look like this [EN][Quest]Secrets of the Tower

**Comment by 0609zeus90** [comment]
I waited about 40 minutes, but nothing happened

**Comment by Timoca** [comment]
I'm waiting for 10 minutes as well now, he hasn't showed up yet.  Did work a few days ago on my main, but not on this char.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2338
