### ISSUE TITLE
[EN][NPC] Bayne

### ISSUE THREAD

**Issue by Caera** [Atlantiss/BugTracker#3854]
I have checked multiple times on this rare spawn to try and tame it with my hunter. The mob is Bayne, a lvl 8 spawn in Tirisfal Glades. Each time it has been classed as "demon" and I have been unable to tame it, getting a "target invalid" message. I submitted a ticket ingame and a GM informed me that it should be tameable by hunters.
www.wowhead.com/npc=10356

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8163-3854npcbayne/
