### ISSUE TITLE
 Mastery visual tooltip bugged.

### ISSUE THREAD

**Issue by hypermodez** [Atlantiss/BugTracker#3856]
Hello.
So today I was messing a bit with the reforging dude, I was reforging between crit and mastery to check what was more beneficial, out of nowhere my mastery tooltip got stuck at 17% the mastery rating would change but when I'd put the cursor over it to read the bonus, it would stay on 17% no matter if it increased or decreased, even taking all my gear off wouldn't make it change, which obviously made no sense.
I tried relogging multiple times.
I reset my spec.
I reset my UI to default.
I talked to a GM to make all my auras dissapear (didn't know what else to do)
And the tooltip was still stuck, so I decided to check if it was only a visual bug or my mastery was actually bugged, I used simple spells without buffs against a dummy (to make it easier to tell the difference) and I found out it wasnt legitemately bugged, it is just visual.
Regardless, it is pretty annoying because it won't let me see the mastery bonus difference between reforges, gems and whatsoever. Please fix this! (:

**Comment by wrehas** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
