### ISSUE TITLE
[EN][PL] Whispering Forest

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#3857]
In rev. 4498 this event has been scripted. I went there yesterday and he don't working i can't see dragons. I stand in the center of the circle and event don't start.
http://www.wowhead.com/npc=51963/fey-drunk-darter

W rev. 4498 ten event był oskryptowany. Poszedłem  tam wczoraj i nie działał nie widziałem smoczków.
Stałem w centrum koła i event się nie rozpoczął

**Comment by Bildo** [comment]
on jest co pare godzin...
