### ISSUE TITLE
[EN] Orgrimmar Visuals

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/BugTracker#3862]
Hi Atlantiss,

Early this morning server time, I was in Orgrimmar &
noticed "brown bars" quite often shooting across my
screen. They were most anywhere I went. I have
attached the two best examplez of thiz. 

![orgrimmar 01](https://cloud.githubusercontent.com/assets/12092984/8766132/aea05e12-2df9-11e5-95ba-918a6f7567b4.jpg)
![orgrimmar bug 02](https://cloud.githubusercontent.com/assets/12092984/8766133/b0e4f00c-2df9-11e5-8e7e-1a39417bf2f1.jpg)
TY

**Comment by Bastion** [comment]
it's problem with your graphic card
