### ISSUE TITLE
BC Quest Bugged Blades Edge Mountains

### ISSUE THREAD

**Issue by Warthog12** [Atlantiss/BugTracker#3865]
The quest Showdown, in the Blades Edge Mountains in Outland, is not completing properly.  I have summoned and killed the guy Goc 3 times and it still has not counted in the quest log.

**Comment by Philippe777** [comment]
I've done this quest a few days ago, and although it doesn't mark the quest as completed, you can still turn it in.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by TheCopacabanaMan** [comment]
Up. I killed Goc, but can't turn in the quest. For me, quest is impossible to complete

**Comment by Thorghar** [comment]
Still not working.
I've killed Goc and nothing happens...
Even try to fly back to questgiver but this doesn't help either...
