### ISSUE TITLE
[PL][Quest][Shadowmoon Valley] Teron Gorefiend, I am... - there is no reward for complete

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3868]
Jak w tytule - nie ma nagród za ukończenie questa www.wowhead.com/quest=10639/teron-gorefiend-i-am
Powinno być 6 itemów (1 do wyboru):
http://www.wowhead.com/item=31104/evokers-helmet-of-second-sight
http://www.wowhead.com/item=31109/stealthers-helmet-of-second-sight
http://www.wowhead.com/item=31106/stalkers-helmet-of-second-sight
http://www.wowhead.com/item=31110/druidic-helmet-of-second-sight
http://www.wowhead.com/item=31107/shamanistic-helmet-of-second-sight
http://www.wowhead.com/item=31105/overlords-helmet-of-second-sight

**Comment by Philippe777** [comment]
Not to mention, if you destroy the Spectrecles, the draenei paladin npc back at the Wildhammer Stronghold (http://www.wowhead.com/npc=21774/zorus-the-judicator) should be able to craft you new ones. He doesn't do that. =/ And I'm guessing the Horde one does not either.

Also, you should be in a semi-phased version of the zone, where a spectral version of Teron Gorefiend (wowhead lists the abilities under the Ancient Shadowmoon Spirit) becomes your pet and fights Karsius The Ancient Watcher.

You obviously lose the pet upon killing Karsius and can go back to your respective quest npc.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1726

**Comment by pariskaravidas** [comment]
Still not fixed
