### ISSUE TITLE
[PL][Quest] Circle the Wagons... er, Boats

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#3869]
Kolejny quest po Pirate Accuracy Increasing, też nie wykonalny, bo nie da się pożyczyć łodzi od NPC.

http://www.wowhead.com/quest=25561/circle-the-wagons-er-boats
http://www.wowhead.com/quest=25542/circle-the-wagons-er-boats
http://www.wowhead.com/quest=25543/circle-the-wagons-er-boats
http://www.wowhead.com/quest=25562/circle-the-wagons-er-boats

**Comment by Wolffenstein** [comment]
Fixed in rev 4523.

**Comment by armano2** [comment]
#3266
