### ISSUE TITLE
[PL][Item] Runescroll of Fortitude II

### ISSUE THREAD

**Issue by Axahus** [Atlantiss/BugTracker#3871]
Buffek z http://www.wowhead.com/item=62251/runescroll-of-fortitude-ii nie powinnien sie skalować do levelu (co ma to miejsce w przypadku buffka od priesta), ale powinni móc go otrzymać wyłącznie gracze z 70 lub wyższym levelem. Średnio raz na ok. 10 bg (lvl 10-19) jakiś twink z alliance buguje to i ma ok. 6k hp...
Krąży mnóstwo plotek (zapewne wymyślonych na poczekaniu), że jest to legalne, ale po sprawdzeniu w Google stwierdzam, że nie jest legalne.
http://www.twinkinfo.com/forums/f28/runescroll-fortitude-ii-25122/ - fragment jakiegoś twinkowego forum
"only lvl 70 and above "
http://www.truewow.org/forum/viewtopic.php?f=3&t=2620&start=660 - forum innego servera (oczywiście nic tu nie reklamuję), temat jest poruszony w 6 postach od góry (co prawda mowa tam o WotLKowej wersji scrolla, ale zasada jest ta sama)
"if you are not level 70 you get no buff"

EDIT: Prawie zapomniałem http://www.wowhead.com/item=62251/runescroll-of-fortitude-ii#comments:id=1424105

**Comment by Wolffenstein** [comment]
Fixed in rev 4803.
