### ISSUE TITLE
[EN][Talent][Druid] Restoration - Swift Rejuvenation

### ISSUE THREAD

**Issue by Dujooo** [Atlantiss/BugTracker#3872]
I think that this talent doesn't function the way it should, I've tested it and the numbers don't match up. There is always a small delay after casting Rejuvenation when you have this talent. In 20 seconds time I cast 19 Rejuvenations with the talent, and 14 without. If my math is correct, without the talent, the global cooldown of Rejuvenation (and all the other spells) is 20/14 = 1.43 sec, while with the talent it should be 1.43 - 0.5 = 0.93 sec. However, this doesn't agree with 20/19 = 1.05 sec. Maybe I misunderstood the concept of global cooldown, but anyway, I thought I should report it.
http://wowwiki.wikia.com/Swift_Rejuvenation

**Comment by kadi2** [comment]
It's supposed to reduce GCD by 0.5s and then calculate haste, but haste can't reduce GCD below 1 second.

**Comment by ahtebe** [comment]
And because of natural connection delays and the spell queue system that doesn't work you won't get the expected number of spells cast.

**Comment by Varchord** [comment]
What these 2 guys have said already.

**Comment by Jenovas** [comment]
Admittedly, once talented, haste will not reduce the gcd of rejuvenation any further.
