### ISSUE TITLE
Arcanum of the Dragonmaw

### ISSUE THREAD

**Issue by Bolilol** [Atlantiss/BugTracker#3875]
This head slot enchant is free of reputuion on Allys and cost only 150g but on Horde its req reputation what means, Horde players cant use it! (quests dont work). Can you give horde players same rights as Allys?

**Comment by Axahus** [comment]
1. https://github.com/Atlantiss/BugTracker/blob/master/README.md

2. https://github.com/Atlantiss/BugTracker/issues/2612 - already reported

**Comment by Varchord** [comment]
STOP THE RACISM AMONG DEVELOPERS!
