### ISSUE TITLE
Maraudon

### ISSUE THREAD

**Issue by Dailybs** [Atlantiss/BugTracker#3877]
Noxosios boss can't be killed because when I go there with my hunter, first thing is my pet can't go to him(I even go to the boss and my pet on follow still can't attack him), so I end up with only me shooting at him, then he spawns mobs and after 3rd spawn I think he dissapeared.Smt is wrong with him pls check him out, thanks.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Dailybs** [comment]
This discourages me to post here.I wana talk about what I saw like I did above post not fit your box.Nex time I would think twice if I will post here.

**Comment by Varchord** [comment]
You can edit your post and title easily
