### ISSUE TITLE
[EN][Quest][NAGRAND] There is no hope quest reward bugged

### ISSUE THREAD

**Issue by skalja** [Atlantiss/BugTracker#3880]
The quest http://www.wowhead.com/quest=10172/there-is-no-hope after finishing the quest there is no reward for it I rly wanted those horns in the end the gm told me to report it on the bugtracker and that he will be able to complete it for me after its fixed. Please check out the quest and hope soon it will be fixed with your answer under. Regards

**Comment by arekczup** [comment]
https://github.com/Atlantiss/BugTracker-PTR

**Comment by skalja** [comment]
Still nothing new about the quest getting soon fixed :(

**Comment by Bildo** [comment]
fixed
