### ISSUE TITLE
[EN][Professions][Fishing] Fishing in Dalaran

### ISSUE THREAD

**Issue by maciekf3** [Atlantiss/BugTracker#3881]
It is impossible to fish anywhere in Dalaran or The Underbelly.
I get message "You can't use that here" every time I try to fish somewhere there.

![wowscrnshot_072115_224441](https://cloud.githubusercontent.com/assets/13379840/8812159/ce8b512a-2ffa-11e5-9958-af0291166f5a.jpg)
![wowscrnshot_072115_224454](https://cloud.githubusercontent.com/assets/13379840/8812187/f78ff918-2ffa-11e5-9426-66469524f48c.jpg)
![wowscrnshot_072115_224526](https://cloud.githubusercontent.com/assets/13379840/8812206/0bb1f608-2ffb-11e5-9d73-31e9813fa7a4.jpg)
![wowscrnshot_072115_224620](https://cloud.githubusercontent.com/assets/13379840/8812227/21089412-2ffb-11e5-8355-03334bff11a9.jpg)

**Comment by xolon** [comment]
#2808
