### ISSUE TITLE
[EN][NPC] KTC Train-a-Tron Deluxe

### ISSUE THREAD

**Issue by Philippe777** [Atlantiss/BugTracker#3882]
While he will teach you profs, this npc does not sell you any item used for said profs. =( So he's still more or less useless. Here's everything he should sell. I did not see an option to buy from him, just to get professions.

http://www.wowhead.com/npc=45286/ktc-train-a-tron-deluxe#sells

**Comment by lordsesho** [comment]
this npc still not selling stuff yet...i have skinning but i cant do it withtout a skinning knife, so as you said is almost useless, unless you dont need any thing like herbalism.

**Comment by TranceAccount** [comment]
Confirmed.

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:
https://community.atlantiss.eu/index.php?/topic/15537-npc-ktc-train-a-tron-deluxe/
[//]: # ([EN][Web] Armory doesnt work)

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
