### ISSUE TITLE
[EN][Object][Drop] Eadric's Cache

### ISSUE THREAD

**Issue by sdadasdas** [Atlantiss/BugTracker#3883]
After multiple runs through Trial of the Champion in normal mode I haven't seen Gauntlets of the Stouthearted Crusader (http://www.wowhead.com/item=47197/gauntlets-of-the-stouthearted-crusader) drop. It might be I'm just so unlucky but the item has ~15% drop chance and other items from the cache drop as they supposed to do. Could you please check its loot table?

**Comment by Quban** [comment]
just bad luck m8 from what i see
