### ISSUE TITLE
[en][alliance][bug fraction] mysterious egg=>cracked egg

### ISSUE THREAD

**Issue by pastor09** [Atlantiss/BugTracker#3887]
Hi
 i wolud like to report that when duration of mysterious egg (reward from oracle fraction) pass, it doesn`t change in to craced egg so it is imposible to get any reward.

**Comment by Anhaeyn** [comment]
You have to keep this egg in your main bag, or it will not work.

**Comment by Philippe777** [comment]
Correct. The egg works.
