### ISSUE TITLE
[EN][Spell][Mage][Cosmetic] Mirror Image

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#389]
Mirror Image does not replicate transmogrified equipment's look that a Mage is wearing, instead it replicates the items' default look.
http://www.wowhead.com/spell=55342/mirror-image

**Comment by armano2** [comment]
link: #633

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2059
