### ISSUE TITLE
[PL][ENG][Mob][Cosmetic] Frostmane Troll Whelp

### ISSUE THREAD

**Issue by Corson** [Atlantiss/BugTracker#3890]
PL:
Zła ikona po najechaniu na moba kursorem - pojawia sie ikona do interakcji, z mobem da sie nawet pogadać (i zabić więc quest z nim działa okej). Powinna być zwykła ikona miecza.

ENG:
Wrong icon appears when mouse hover over mob - instead of sword icon, the npc-like cloud appears. The mob is attackable so the quest involves him works fine.

**Comment by Bildo** [comment]
link do moba...
