### ISSUE TITLE
Client crashes in dungeons

### ISSUE THREAD

**Issue by srtjko** [Atlantiss/BugTracker#3892]
I don't know how to reproduce the problem but sometimes the client will crash if you are in a dungeon. It happened to me in RDF maybe 2 times but today I was doing a dungeon in Hellfire Citadel, The Shattered Halls and I got 3 random client crashes, it has a huge impact on my PC, it barely recovers. I've noticed every time it crashed some stealthed mobs were close to me about to attack me. Maybe that triggers the crash. I am using your .exe. Can't upload a log cause its .txt

**Comment by Bildo** [comment]
duplicate
