### ISSUE TITLE
[PL][Quest][The Cape of Stranglethorn] Bwemba's Spirit

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#3898]
http://www.wowhead.com/quest=29219/bwembas-spirit
Po oddaniu tego q wszyscy w Boty Bay są unknown, dopiero po jakimś tam czasie przechodzi
Przed oddaniem nie ma nikogo w Boty Bay

**Comment by Asavel** [comment]
Fazowanie...........
