### ISSUE TITLE
[ENG][quest] Trial of the Naaru: Mercy

### ISSUE THREAD

**Issue by Betraye21** [Atlantiss/BugTracker#3899]
It is required to obtain a title "Champion of the Naaru", but quest item(Unused axe of the executioner) doesn't drop from the boss (Kargath Bladefist) in Shattered Halls.

**Comment by LordMoriarty** [comment]
http://www.wowhead.com/achievement=432/champion-of-the-naaru
"As of patch 3.02 you will no longer be able to recieve the title "Champion of the Naaru", You can finish the quest to get it, yet you will no longer get the title."

The only way to get the title would be using a lvl 70 character with the original quests but that's not possible on atlantiss.

http://www.wowhead.com/quest=10884/trial-of-the-naaru-mercy
The quest IS completable on 4.3.4 ("April 18 2012: This quest is now working again and can be completed", patch released on april 17 2012).

Did you complete the dungeon in under 55 minutes?

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2760
