### ISSUE TITLE
[Eng] Profession tab got bugged.

### ISSUE THREAD

**Issue by demlk** [Atlantiss/BugTracker#3901]
Heallo, After i learned cooking my profession tab got bugged,i disabled addons,reinstalled wow - nothing helped. I asked gm and he said that it happened not only for me.

**Comment by krecik88** [comment]
Please post some screenshots what happen.

**Comment by demlk** [comment]
http://imgur.com/ZXLQk4n
As you see only alchemy is aviable to select, but i have Archeology ind herbalism

**Comment by krecik88** [comment]
You have learned two specialization for Alchemy, that's why it is bugged (it happens for people that have finished TBC quest for specialization before 434 patch). You have to unlearn specialization for alchemy. The other one you have learned will appear as active.

**Comment by demlk** [comment]
I created this account like 2 weeks ago. how could  i do tbc quest?

**Comment by demlk** [comment]
Ok,thx it's fixed now :)

**Comment by ahtebe** [comment]
Well just so you know, you could've had 2 specializations. At the same time. And that is a game breaking bug too.

**Comment by krecik88** [comment]
Already fixed. If someone has this bug, contact with gm to remove alchemy specialization and then take it again.
