### ISSUE TITLE
[PL][Quest][Deepholm] All Our Friends Are Dead

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#3909]
Link quest: http://www.wowhead.com/quest=26248
Link q item(totem): http://www.wowhead.com/item=58167

Totem prawdopodobnie pojawia się na ziemi daleko pod statkiem(widać ikone na mapie), co za tym idzie NPC nie wstaja by z nami "porozmawiać" i nie da się oczywiście ukończyć questa.

**Comment by Glare** [comment]
Nadałbym temu high priority ze względu na to, że blokuje chaina do 60~ questów w Deepholm.

**Comment by cosminush** [comment]
This quest dont work anymore, it did some time ago but now dont work.

**Comment by shrek15001** [comment]
Faction: Both
Race: All
Class: All
Quest ID: 26248
Provided item: Spirit Totem > 58167
Quest Name: All Our Friends Are Dead
Quest Description: Use the Spirit Totem on the corpses of 6 Slain Crew Members.
 Slain Crew Member information (6)
Something's wrong here, <name>.
The ship's crew has been slain. Yet there is no bloodshed or damage to the ship's structure.
This was not the Horde's doing.
We will find the answers we seek by speaking to the spirits of the dead. They have not yet left this world.
Take this totem and place it near the corpses of the fallen. You will have a few seconds to listen to their last few thoughts.
Beware, however! There is no telling how the spirits of the dead will react to our prodding.
Quest Reward: [Incorporeal Sandals (61501)] [Skyrend Bracers (61497)] [Totem-Caller Hood (61499)]
Cleared Cache: Yes
Relogged: Yes

Issue: Quest is bugged now, wasn't bugged about a month ago

**Comment by ahtebe** [comment]
Quest doesn't work. When using the Spirit Totem (http://www.wowhead.com/item=58167/spirit-totem) on a Slain Crew Member (http://www.wowhead.com/npc=42681/slain-crew-member), nothing happens.

Since this quest is needed to begin the Therazane quest chain, the Therazane reputation faction is not accessible to players.

**Comment by sunshineinabox** [comment]
It was working recently, but got broken. Lots of things seem to have gotten broken recently. I also experienced the same thing press the totem button and nothing happens.

**Comment by Glare** [comment]
Totem just spawns on the ground under ship. You can see totem's icon on the minimap. Probably some vmap(?) issue.

**Comment by sunshineinabox** [comment]
Might be similar to the nefarrian adds spawning under platform. IIRC someone said there was an issue that would be fixed after a server a restart or something.

**Comment by Bildo** [comment]
please check now and close if it works

**Comment by Glare** [comment]
Not always working but it's completable.

**Comment by ahtebe** [comment]
Just because it's completable doesn't mean it isn't bugged and shouldn't be reported. If it is working as intended then close.

**Comment by sunshineinabox** [comment]
There are still some issues 

The totems spawn on the floor below that little platform:
![wowscrnshot_072615_083749](https://cloud.githubusercontent.com/assets/11906669/8894684/c424f1c8-3374-11e5-849c-0ae3382f34a6.jpg)

Mobs can be agroed that are in the middle of the ship again seems like a vmaps issue: 
![wowscrnshot_072615_083837](https://cloud.githubusercontent.com/assets/11906669/8894692/34f5b478-3375-11e5-9cfb-8ed78c72b58f.jpg)

**Comment by Glare** [comment]
I'd say you should open new issue and report the whole battleship chain instead of just sticking to this single quest. I mean, this one depends on how vmaps(?) are working but look at the other part of the chain. There are like 3 or 4 autocomplete quests(not sure about vmaps influence on those, I've never done them on retail). The whole quest chain probably requires a lot of time to make it work blizzlike and that's why it works so poorly.
