### ISSUE TITLE
[EN][Quest][Silverpine Forest] On Her Majesty's Secret Service

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#391]
# What is not working:

The quest is not available, even if you completed the required quests.

---
# How should work:

The quest-giver should give you the quest.

---
# More info:

[On Her Majesty's Secret Service - WoWHead](http://www.wowhead.com/quest=27594)
[On Her Majesty's Secret Service - WoWPedia](http://wowpedia.org/Quest:On_Her_Majesty%27s_Secret_Service)
[Lord Godfrey](http://www.wowhead.com/npc=45878)

**This was tested on 4.0.6a realm**

**Comment by janbrand** [comment]
I had the same problem. Very frustrating to have the quest line break with only two quests to go.

**Comment by Angelo-DM-** [comment]
Confirm! [Lord Godfrey](http://www.wowhead.com/npc=45878) do not give you this quest.

Completing this quest, it should unlock [Cities in Dust](http://www.wowhead.com/quest=27601) from [Lady Sylvanas Windrunner](http://www.wowhead.com/npc=45617) that is the last quest in silverspine forest!!

**Comment by Avantie** [comment]
indeed this bug still exists

**Comment by Satyr87** [comment]
oh bloody hell !
i confirm that being unable to do 2 final quests in silverpine makes you angry like f***

**Comment by Enay** [comment]
Confirming this

Upon completing **Sowing Discord** (http://www.wowhead.com/quest=27580), you don't get a follow up quest **On Her Majesty's Secret Service** (http://www.wowhead.com/quest=27594)

**Comment by corvusaraneae** [comment]
Also confirming. The NPCs just kept following me around and just kinda stopped giving me quests at some point.

**Comment by eryczek1615** [comment]
BUMP!!

**Comment by Angelo-DM-** [comment]
1 year and 2 months and we are not able to do these 2 lasts quests? BUMP! BUMP! BUMP!

**Comment by Angelo-DM-** [comment]
Quest:
http://www.wowhead.com/quest=27594/on-her-majestys-secret-service

NPC (i don't know witch one):
http://www.wowhead.com/npc=45997/commander-lorna-crowley (Health: 6564 hostile)
http://www.wowhead.com/npc=46027/commander-lorna-crowley (Health: 6564 hostile)
http://www.wowhead.com/npc=46001/commander-lorna-crowley (Health: 5808 friendly)

If you go on Silverspine forest, at 50,88, you'll find Commander lorna crowley (lvl 20) with 774k hp!

Lord Godfrey still not give you the quest...

**Comment by Angelo-DM-** [comment]
In order:
[Lord Godfrey](http://www.wowhead.com/npc=45878) should give you [On Her Majesty's Secret Service](http://www.wowhead.com/quest=27594/on-her-majestys-secret-service)
that unlock [Cities in Dust](http://www.wowhead.com/quest=27601) from [Lady Sylvanas Windrunner](http://www.wowhead.com/npc=45617),
that unlock [Empire of Dirt](http://www.wowhead.com/quest=27746/empire-of-dirt) always from her that is the first quest on Hillsbrad Foothills!

**Comment by EyalAndOmer** [comment]
on her majesty secret service still not fixed :(

**Comment by sharkyand10** [comment]
Same problem here :( i dont think they will ever fix this ...

**Comment by Khangu** [comment]
Any chance to ever see this quest added?

**Comment by Lindria** [comment]
Will you ever fix this?

**Comment by Fuzzypunk** [comment]
still doesn't work - Quest:On Her Majesty's Secret Service 
	
Lord Godfrey doesn't give this quest ;(

**Comment by xStiven** [comment]
Bump, This bug is still not fixed. Very bad - whole area is mostly works fine, but those end quests, is still not working. Please fix it ;/

**Comment by worloq** [comment]
On Her Majesty's Secret Service-- still Lord Godfrey doesn't give this quest pls fix it

**Comment by Samineh** [comment]
Bump xD

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14388-3918681-on-her-majestys-secret-service/

**Comment by ammeba** [comment]
Fix it please!

**Comment by Piklo** [comment]
@ammeba open a new post if it still not working
