### ISSUE TITLE
[EN] PTR server

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#3911]
I don't know if this is a bug or if it should even be reported here, but on the PTR server valor and conquest points are limited to their normal cap. Completing the quest to earn more does nothing.
This means valor point items can't be bought.

I heard the .gangnamstyle was supposed to give gear or something, but it doesn't do anything it just appears on the chat bubble.

I wanted to test out some classes spells with different gear levels (346 to 359 to 372), but I found this to be impossible.

**Comment by Bambosz** [comment]
You should use PTR bugtracker for reports about test realm.
Also it's already reported - https://github.com/Atlantiss/BugTracker-PTR/issues/5
