### ISSUE TITLE
[EN][RDF] Random Dungeon Finder

### ISSUE THREAD

**Issue by skillet75** [Atlantiss/BugTracker#3912]
RDF has stopped working for a bunch of people all of which were under 85 (atleast those that i spoke with, that had the same problem).People seem to queue but only see themselves appear in the waiting queue.This started happening at about 1-2 hours before I made this post/issue.Cheers.

**Comment by ahtebe** [comment]
Same is happening at level 85 with heroic dungeons. There are people on world chat looking for tank and healer to queue, when for some other people those two roles are already queued and what is missing is dps.

**Comment by kunfuu** [comment]
Yep, this is true!

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/696

**Comment by Kejmil** [comment]
suddenly, issue is collapsing...

**Comment by skillet75** [comment]
Why did you close the issue when it's still not resolved ?!

**Comment by Bildo** [comment]
because it's duplicate
