### ISSUE TITLE
[EN][RAID][BWD]Nefarion Is Still Bugged (After supposed fix)

### ISSUE THREAD

**Issue by davesmix** [Atlantiss/BugTracker#3915]
So we took a raid group (after clearing all bosses but Nef the previous day) to solely kill Nef. When we first got there, Onyxia was half underground. Once we started the encounter even more issues came up.
During the entire encounter, if you used a movement ability (i.e. Blink, Feral Charge, Etc.) you would fall through the floor into the lava. Pets from players also would fall through the floor from the start of the encounter. The adds in phase 1 adds were also spawning underground and could not be managed. Phase 2 seemed to work correctly, but in phase 3 the adds would spawn underground along will the flame spawning underground so you can't see the flames or the mobs (eventually wiping raid). We have fought Nef before since the fix with no issues. It seems like something has happened today that has bugged the encounter somehow. We did try this encounter many times with same results.

**Comment by Wolffenstein** [comment]
Recent vmap update fucked it up. It should be working after server restart.

**Comment by davesmix** [comment]
Ok ty for info
