### ISSUE TITLE
[EN][Quest][Desolace] Calming the Kodo

### ISSUE THREAD

**Issue by xxMAKMAKxx** [Atlantiss/BugTracker#3917]
http://www.wowhead.com/quest=14309/calming-the-kodo

the kodo just wont calm after placing the bowl... (put bowl under enraged kodo, the elite one.. nothing happens)

**Comment by Avalain** [comment]
Placed bowl not far from Enraged Kodo, he just slowly approached it and returned to his own spot. Still not counted as a calm.
Placed a bowl under Enraged Kodo while having aggro from him, he approached to bowl position, animation started. Still not counted as a calm, Kodo stays in place, can move him by placing next bowl.
Killing them after also don't count for quest.
