### ISSUE TITLE
[PL][Paladyn] Vindication

### ISSUE THREAD

**Issue by kacper123** [Atlantiss/BugTracker#3918]
Ktoś wykazując się nadgroliwością zmienił jakiś czas temu działanie talentu . Używając hammera uzyskujemy zgodnie z opisem osłabienie dmg od głównego celu jednak w rzeczywistości był to błąd zawarty w opsie talentu ponieważ hammer zmiejszał dmg otrzymywany od wszyskich mobkow . 

Załanczając dowody 
http://www.wowhead.com/spell=26016/vindication#changelog
Even though it says [...]Hammer of the Righteous reduce physical damage done by their primary targets by 10% for 30 sec.[...] Vindication will hit effect all targets that gets hit by Hammer of the Righteous AoE holy damage, not just the one who got primarily targeted as the spell description says.

http://eu.battle.net/wow/en/forum/topic/1035414131
bump. I think it's been around for ages but it should be fixed. Prot Paladins have to do literally nothing extra to maintain their tanking debuffs which is boring

dodatkowo na filmiku widać wyrażnie 
https://www.youtube.com/watch?v=uD4uibId-7g  
1:15-1:19 że po zmianie targetu mobki posiadają debuffa 

i hop na koniec 
http://eu.battle.net/wow/en/forum/topic/1701751571
ostatni post 
o i tu 
http://us.battle.net/wow/en/forum/topic/2016084019

**Comment by kacper123** [comment]
podbijam to dość istotny problem

**Comment by Nc94** [comment]
BUMP

**Comment by kacper123** [comment]
BUMP

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
