### ISSUE TITLE
[EN][WoWError] Random Dungeon Finder Bug - Do not work

### ISSUE THREAD

**Issue by kingstyles** [Atlantiss/BugTracker#3920]
It is seem that since yesterday 25/07/2015 the RDF has not worked, as we queue there is only us in the queue at all time and it doesn't connect to a party or raid. In addition, other people on the server at the time also have this problem. We have to go into a group and then queue for specific dungeon for it to work.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/696
