### ISSUE TITLE
[EN][Quest][Loch Modan] The Winds of Loch Modan

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3924]
quest dont work 
see in wowhead http://www.wowhead.com/quest=27116/the-winds-of-loch-modan
see video https://www.youtube.com/watch?v=81OvOklhkRI

**Comment by Quban** [comment]
taking a flight is not working?

**Comment by iliarakov** [comment]
yes and quest cant finished

**Comment by CrazyFredy** [comment]
Picking the flight up works just fine, but you are dropped out of the vehicle halfway through the flight. Can still be completed.

**Comment by Bildo** [comment]
fixed
