### ISSUE TITLE
[EN][Quest] Anvilmar the Hero

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#3925]
Can't speak to NPC, can't complete the quest.

http://www.wowhead.com/quest=26327/anvilmar-the-hero

**Comment by Dexobox** [comment]
+1 Confirm bug still exists

**Comment by Dexobox** [comment]
This and the continued quest chain is not completeable, I was able to turn in this quest somehow. but the next quest [The Twilight's Hammer Revealed](http://www.wowhead.com/quest=26127/the-twilights-hammer-revealed) cannot be turned in.

**Comment by Aival94** [comment]
For some reason after a crash/restart of server i got quest and finish it just fine and the next quest mentioned by dexobox was available after completing it.

**Comment by Larcan** [comment]
+1 bug still exists

**Comment by ylluminate** [comment]
What needs to be done to resolve this?

**Comment by kuba22277** [comment]
We still can't complete the broken quest chain because of this bug. Please resolve it.

**Comment by Nightend1** [comment]
+1 Please fix this bug

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5109
