### ISSUE TITLE
Scooty is missing

### ISSUE THREAD

**Issue by Gerdat16** [Atlantiss/BugTracker#3930]
Scooty, the guy who mans the Gnomeragan teleporter on the horde side, is missing from his spot in Grom'Gol Base camp. So is his portal to Gnomeregan.

**Comment by Pallitax** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the NPC provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md
