### ISSUE TITLE
Goldshire Griffon Master

### ISSUE THREAD

**Issue by mikeytrousers** [Atlantiss/BugTracker#3931]
Sits atop the rooftop of the building next to the two griffons where he usually resides making him unable to be interacted with.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the NPC provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
I'm so proud of you mate
