### ISSUE TITLE
[EN][Quest][Durotar] That's the End of That Raptor

### ISSUE THREAD

**Issue by saduss** [Atlantiss/BugTracker#3932]
This raptor named "Screamslash" is not spawning at its location and I can't complete the quest.

http://www.wowhead.com/quest=25195/thats-the-end-of-that-raptor

**Comment by Quellz** [comment]
He spawned perfectly for me. Might be just that you didn't wait long enough. Respawn timer perhaps?

**Comment by MirrorWraith** [comment]
today, this quest works well and there's 2 Screamlash
