### ISSUE TITLE
[EN] [Quest] [Gilneas] The Battle for Gilneas City

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#3934]
http://www.wowhead.com/quest=24904/the-battle-for-gilneas-city

The event is missing. You just have to talk to Krennan. The quest is pretty much auto-complete in this regard. 
I found a youtube video for the event:
https://www.youtube.com/watch?v=g9zPTOd5yCY

**Comment by Aival94** [comment]
#3558
