### ISSUE TITLE
[EN][NPC][Darkshore] Corrupted Blackwood

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#3935]
http://www.wowhead.com/npc=33044/corrupted-blackwoo

His aggro range is broken. If he gets aggro on you, he will follow you until the end of the earth and attack you. Also, when doing this quest, http://www.wowhead.com/quest=13545/cleansing-the-afflicted, the furbolg will still follow you until the end of the earth and attack you, even after you become friendly with him.

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/1746

**Comment by Bildo** [comment]
fixed
