### ISSUE TITLE
[EN] [Quest] [Darkshore] The Eye of All Storms

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#3937]
http://www.wowhead.com/quest=13588/the-eye-of-all-storms

The twilight riders can be killed and the twilight portal can be destroyed only until our green dragon, Thessera reaches the portal. There is an invisible "ceiling" and upon reaching it, the twilight riders can no longer be killed and the portal can no longer be destroyed because they reset their health points.
The quest can still  be completed by killing the riders and destroying the portal before reaching the invisible "ceiling" and dismounting Thessera several times and flying up again.

**Comment by Aival94** [comment]
#2028
