### ISSUE TITLE
[EN][NPC][Mount Hyjal] Vision of Ysera

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#3939]
http://www.wowhead.com/npc=46987/vision-of-ysera
http://www.wowhead.com/npc=46987/vision-of-ysera#screenshots:id=199371

This NPC should be located around the area of shrine of goldrinn, coords 28,29 across from npc Ian Duran in Mount Hyjal but she is not there. She should offer quest Aviana's Legacy but is no where to be found. As a result of not being able to obtain the quest Aviana's Legacy from her the following 3 quests can not be done because they are part of a quest chain.
1. An Offering for Aviana
2. A Plea From Beyond
3. A Prayer and a Wing

**Comment by Aival94** [comment]
Quests can be done and you can impements yours here if you want: #2108

**Comment by lourrific** [comment]
I like how people say "quest can be done" but do not offer a solution and instead decide to "implements" problem on another page on this forum where it might be addressed but hasn't offered a solution since February. 

If anything that page should be implemented to my page because I describe the problem in better detail.

Do you mind elaborating on how this quest can be done? 

I am aware that quest Wings Over Mount Hyjal http://www.wowhead.com/quest=25985/wings-over-mount-hyjal is an alternate starter quest that leads to the other 3 quests mentioned above but I tried NPC Choluna she does not offer it. The other option is of course NPC vision of ysera but we all know she is not available. so please explain how you were able to do the follow up 3 quests? only other possibility is if starter quest was assigned to other npc not listed in wowhead.

**Comment by Aival94** [comment]
You probably have checking wrong location for the quest npc as npc is on first camp where you teleport at the beginning of starting mount hyjal quests.This is the only way to continue these quests and i have done them without any problem.If any changes had been done after i have done them then only solution is make a ticket. And i ask you if you can to implements yours to the other one as you made a mistake because the Vision appear for some time after doing a quest but after some time disappear like it should do and after it only Ysera herself can give this quest which do not.

**Comment by lourrific** [comment]
Do you have any idea what quest progression is? or do you just randomly grab quests in an area and use youtube as reference?

Ysera should be there because I have done all the quests that lead me up to her vision.
 
If she is not there after I do certain quests then she is broken. Do you know what quest I need to do so she can phase in? I do, I have done it. This is why I know she is broken.

You obviously do not know quest progression if you can not provide name of NPC or know what quests are needed before and after the initial quest you are trying to do. 

What quest should come before Aviana's Legacy? what quest comes after? or does youtube show you that too? 

Maybe what's shown in youtube is from another patch but it could probably work on this server because of patch integration? do you know name of NPC in youtube video? 

This is Aviana quest progression:

(optional linking quests ofWings over Mount Hyjal or Aviana's Legacy)
Two chains:
* An Offering for Aviana, A Plea from Beyond, and A Prayer and a Wing
* The Wormwing problem, Scrambling for Eggs, and then A Bird in Hand

Next comes Fact-Finding Mission which enables these required quests:

    1. Setheria's Brood
    2. A Gap in Their Armor and Disassembly
    3. The Codex of Shadows [from here ] leads to Egg Hunt

Finish the above for:

4. Sethria's Demise 
5. Return to the Shrine 
6. An Ancient Reborn [Vision of Ysera] 

Vision of Ysera should appear now but if not something is broken.

Optional bonus:

1. The Hatchery Must Burn
2. Flight in the Firelands
3. Wave One
4. Wave Two
5. Egg Wave

This also gives:

6. Beware of the 'Unbeatable?' Pterodacyl 

and choice of :

7. Gold Mini Jouster or 8. Blue Mini Jouster

and finally

9. Return to Aviana

**Comment by Aival94** [comment]
i just say from my experience when i did the quest  she appear just fine and disappear after some time(maybe was before some fixes which bugged her).If you have a problem only way is to make a ticket.

**Comment by Aival94** [comment]
[Vision of Ysera](http://www.wowhead.com/npc=46987/vision-of-ysera) should be spawned when complete each quest.
[Return from the Firelands](http://www.wowhead.com/quest=25611/return-from-the-firelands)
[An Ancient Reborn](http://www.wowhead.com/quest=25807/an-ancient-reborn)
[An Ancient Awakens](http://www.wowhead.com/quest=25520/an-ancient-awakens)

**Comment by VioletFlare** [comment]
She disappears after a very short time, so beware if someone has the habit of reading quests.

**Comment by tomatosz** [comment]
The vision of Ysera only spawns for a short while. However the 'regular' Ysera at Nordrassil will also give the quest Aviana's Legacy as of rev. 5759.
(Also, Wings Over Mount Hyjal is an alternative breadcrumb quest instead of Aviana's Legacy).
