### ISSUE TITLE
[EN] [Quest][Silverpine Forest] It's only poisonous if you ingest it 

### ISSUE THREAD

**Issue by Obaibi** [Atlantiss/BugTracker#3943]
Hello, 

First of all, wowhead's link: http://www.wowhead.com/quest=27088/its-only-poisonous-if-you-ingest-it
Then a video to show how the quest should work: https://youtu.be/Pvd9oP9kUfc

And now I'll sum up some bugs I noticed about this quest.

Bug report#1: The chicken is working and makes the forest ettin greatly weaken but when you kill him, quest isn't confirmed. To confirm this one, we have to kill him without using the chicken. 
Bug report #2: When you pull the forest Ettin before using the chicken, the famous op chicken doesn't work so the targeted forest Ettin doesn't become weak anymore.
Bug report #3: When you pull the forest Ettin and escape to him after dealing some damages, his life doesn't reset. 
Bug report#4: On the server, there are 2 forrest Ettins. On official server, there is only one :) 

Thank for reading and good luck.

Bye

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
Mate, I'm proud of you. I really am, but you forgot about something

https://github.com/Atlantiss/BugTracker/issues/366

**Comment by Pallitax** [comment]
I wouldn't want to put you out of work, Varchord.

**Comment by Obaibi** [comment]
Sorry. This was my first report. Didn't see the rules for reporting. I edited.
