### ISSUE TITLE
[EN][Quest][Silverpine Forest] Lost in the Darkness

### ISSUE THREAD

**Issue by Obaibi** [Atlantiss/BugTracker#3944]
Hello,

Wowhead's link: http://www.wowhead.com/quest=27093/lost-in-the-darkness
Video's link to show you how should work the quest: https://www.youtube.com/watch?v=w3SB52NdcQc

Ok there are two minor bugs really minor

Report#1: When you hit the cocoon with your weapons, some peons you have already give them their  freedom  will help you to destroy the cocoon. That's not a big problem even if they shouldn't attack cocoons, they should attack monsters.  But, if there is a peon inside the cocoon and one your peon already free attacks the cocoon, the new peon wil be not count for the quest. That's really a minor bug but it can be boring for mage, warlocks or priest ... 
Report#2: Minor visual bug, peon should be spread and not pack in only one peon ^^
Report#3: I'm not sure, but cocoon should have one point of life . It can depends on the game version

Thank and good luck 

Bye 

PS: That's really minor bug but I read on the website, you want to know every bug even they aren't important  so I did it ^^.

**Comment by Obaibi** [comment]
Edit2: #report3 can resolve #report1. And dot don't work on cocoon but I don't know if it's normal. If anybody do, comment :)

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3657

**Comment by Kedrak** [comment]
Confirmed this quest can be done...

As a Warlock, i just put my pet on passive mode and destroy the cocoons with shadow bolts...

Every ork that pop up, counted to quest completion.
