### ISSUE TITLE
[PL][Quest] Missing in Action

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#3945]
Quest polega na otwieraniu klatek. Nie wiem czy to bug, ale gdy ktoś pootwiera klatki to nie zamykaja się one i druga osoba już nie może tego questa zrobić. Chociaż czasami zdaża się, że są zamknięte, ale wydaje mi się, że to z powodu disconnectu.

http://www.wowhead.com/quest=26284/missing-in-action

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/4098
