### ISSUE TITLE
[EN][Spell][Death Knight] Death Grip

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3946]
Death Grip seems to apply twice (the debuff that is applied) you can see it both in the combat log and as a debuff. 

![wowscrnshot_072515_173922](https://cloud.githubusercontent.com/assets/11906669/8892413/8022134e-330a-11e5-83d2-dba265ee2158.jpg)

![wowscrnshot_072515_173743](https://cloud.githubusercontent.com/assets/11906669/8892411/7bb5a8ca-330a-11e5-99fb-483ee170595a.jpg)

http://www.wowhead.com/spell=49576/death-grip

**Comment by Pallitax** [comment]
• No wowhead link for the spell provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by sunshineinabox** [comment]
Ah shit my bad completely forgot about that its a little late. Added it.

**Comment by Jenovas** [comment]
It is applied once, one of the effects is the pull effect the second one is a taunt effect. The only bug that may be here is that one of them should be client hidden.

**Comment by sunshineinabox** [comment]
Ah ok, I'll take a look at some videos try to see if it is hidden on the client side.

**Comment by Avalain** [comment]
Death Grip: http://www.wowhead.com/spell=49576/death-grip

It should put Death Knight performing it at top of threat table, similar to any other taunt.
At the moment only forces enemy to attack DK for 3s.

Discussion: http://www.wowhead.com/forums&topic=82628/am-i-that-stupid-death-grip-taunts
