### ISSUE TITLE
[EN][Quest][Northern Stranglethorn.] Favored Skull

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3947]
quest dont work see
see in wowhead http://www.wowhead.com/quest=26745/favored-skull
see video https://www.youtube.com/watch?v=9aCnHSeVKDI

**Comment by krauza666** [comment]
Just add NPC Osborn Obnoticus, http://www.wowhead.com/npc=43884/osborn-obnoticus

**Comment by krauza666** [comment]
This quest is WORKING. First you must finish Spared from Madness quest: http://www.wowhead.com/quest=26736/spared-from-madness
Where you rescue Osborn Obnoticus. And then this NPC is in Rebel Camp :)

**Comment by iliarakov** [comment]
Thanks man :)
