### ISSUE TITLE
[Instance] Throne of the Tides

### ISSUE THREAD

**Issue by Kelmore31** [Atlantiss/BugTracker#3948]
As far as l know normal RDF shouldn't give IDs yet... l got one earlier :) After we requeued for RDF and got Throne again the adds were all dead and bosses weren't there, same as any raid ID would work.

![throne](https://cloud.githubusercontent.com/assets/13494578/8893590/f14be01a-339e-11e5-89a9-8dbf9fa8b3bf.png)

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md
