### ISSUE TITLE
[EN][Quest] How to make meat fresh again

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#395]
In "How to make meat fresh again" (http://www.wowhead.com/quest=24697), you should be able to use meat on nearby dinosaurs in order to lure them into a trap, and get a count for the quest. However, you can't use the meat on majority of dinosaurs nearby, in fact, there's only one dinosaur that you can use it on, making the quest very annoying to complete. Majority of dinosaurs around are "Invalid Target" when you try to use the meat on them.

Here's how the quest should work - https://www.youtube.com/watch?v=YkfJmxmGEKY

**Update**:

IF you use the meat on this one dinosaur that you can use it on, Ravasaur (http://www.wowhead.com/npc=6505), and you get close to the trap, you instantly die.

Also, Ravasaur shouldn't be spawned here, nor is he related to the quest.

So...quest can't be completed at all, sadly.

**Comment by Bhaluck** [comment]
Hello,

Today (19/04/2015), I managed to do it by ignoring the meat, kiting the Ravasaur to the pit, then killing it normally. I believe there is only one Ravasaur that spawns closely enough for you to do that.

It's not how it is supposed to be, but at least you can complete it.

**Comment by Bildo** [comment]
fixed
