### ISSUE TITLE
[pvp][druid][restoration] tree of life

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#3952]
Can't shapeshift into tree of life while polymorphed/hex'd

wowhead link
http://www.wowhead.com/spell=33891/incarnation-tree-of-life

openwow link
http://cata.openwow.com/spell=65139

The exact spell is neither of the links, but I couldn't find it on any of the databases provided... However the difference from the tooltips isn't very big, so I hope this will be enough :)

**Comment by Jenovas** [comment]
Where does it say that you should be able to break Poly and Hex using ToL?

**Comment by sunshineinabox** [comment]
http://us.battle.net/wow/en/forum/topic/2057515783

**Comment by Jenovas** [comment]
1.When shaman hex you....tree of life no longer break hex = major resto druid nerf 
-you cant break hex with tree form if you are alredy hexed (tryed out today)

It states that you CANT break out of hex.

**Comment by Fearyourself** [comment]
http://us.battle.net/wow/en/forum/topic/2057515783 both comments say that you can break poly/hex by shapeshifting into Tol just like you can shapeshift into cat/bear...

Also if you read the tooltip it says it protects you from these polymorph effects. i know for a fact that you couldn't shapeshift while polymorphed back in wrath of the lich king though.

**Comment by ezzira** [comment]
This is not a bug, shapeshifting prevents you from getting polymorphed/hexed. so if you shape shift into tree of life, you can't get hexed or poly'ed, but it doesn't break an already casted hex/poly.

**Comment by Jenovas** [comment]
ezzira - Tree Of Life Form as a shapeshift with a long CD not only grants immune to hex/poly but also should BREAK them if they are already on you

**Comment by kadi2** [comment]
https://www.youtube.com/watch?v=4pJnytyGuvQ&feature=youtu.be&t=2m30s // This is from early cata, but the post about hex was posted like half year later. 

The stealth nerf about Hex and Tree of Life you are talking about indeed existed. But it was a buff to hex, that made people unable to use any spells while under the effect of hex.

the only bugged thing in Hex is that you can change form (without breaking it) you can move, you can go to cat form and use dash, you can even drop totems.

In late cata it was impossible to cast anything when under Hex effect.


"the only bugged thing in Hex is that you can change form (without breaking it) you can move, you can go to cat form and use dash, you can even drop totems." // Quote from early cata

**Comment by armano2** [comment]
It's not a bug, on retail on 4.3.4 it was preventing you from change form,
