### ISSUE TITLE
[EN][Quest][Western Plaguelands] Zen'Kiki and the Cultists

### ISSUE THREAD

**Issue by 0609zeus90** [Atlantiss/BugTracker#3954]
http://www.youtube.com/watch?v=NwBBGJ6KAaE

**Comment by worgenman** [comment]
yes its bugged, bears are of the cage and u cant do anything about them

please fix it

**Comment by Dexobox** [comment]
Wowhead Link [Zen'Kiki and the Cultists](http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists)
npc : [Zen'Kiki](http://www.wowhead.com/npc=44863/zenkiki)
Zen'kiks algorithm is messed up: 

Currently:
if(any npc is in range)
 {
       Zenkik attacks them;
}

What it should be:

if( player has aggro)
{
      Zenkiki attack target: npc with highest aggro/threat on player;
}
if ([Captive Plaguebear](http://www.wowhead.com/npc=44902/captive-plaguebear) in range && free from cage)
{
     Heal it  once ; 
    count towards quest objective ;
    de-spawn bear /make bear dissapear
    ~ respawn bear inside cage in like 60sec timer;
}
something along those lines

**Comment by davidrivasdos** [comment]
still bugged and worst

**Comment by SloaneMarie** [comment]
This quest does not allow for the bears to be healed or even attacked. Any word on when this quest will be fixed or should I drop it?

**Comment by DuGalle** [comment]
Quest still broken nothing happen to bears once you approach em with the npc

**Comment by Snake90** [comment]
The quest is still bugged.

2 problems :

1) When someone makes the quest after a restart / crash, the bears stay outside the cages as they should return for the next player.

2) Even if we do the quest after a restart / crash, it doesn't work : the cage opens, the bear comes out, Zen'Kiki is there but nothing happens, it doesn't cont for the quest.

**Comment by Snake90** [comment]
Still bugged
