### ISSUE TITLE
[EN][Gameobject] Mailbox Locations

### ISSUE THREAD

**Issue by Tj20** [Atlantiss/BugTracker#3955]
I compared all alliance capital cities and Orgrimmar mailbox locations to retail and they seemed mostly fine. I noticed only 2 exceptions:

Stormwind [61,50] - 1 missing
![Atl](http://i.imgur.com/7QmFpve.jpg)
[retail](http://i.imgur.com/ZHgIwNa.jpg)

Ironforge [71,49] - 2 at one location
![Atl](http://i.imgur.com/o4NFpJS.jpg)
[retail](http://i.imgur.com/Dr6S5M4.jpg)

**Comment by wtRCH** [comment]
fix pending.
