### ISSUE TITLE
[EN][Quest] Hero's Call quests

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#396]
So, this has happened to me first in STV, and it happened again now in un'goro, so it needs to be looked at.

I've already mentioned this a bit in my report here https://github.com/Atlantiss/BugTracker/issues/346

It seems like on our server, Hero's Call quests somehow became requirements for unlocking various quests. In Un'goro now, I did 21 quest, and I got stuck, so I went to pick up hero's call quest for un'goro in exodar, and when I came back to un'goro and turned it in, it unlocked a new quest, and I was able to continue playing in this zone.

The thing is that, as far as I know, hero's call quests are only breadcrumb quests, and they are only there to lead you to a new zone. 

So anyway, hero's call quests should be looked at, and fixed if they're required to unlock some quests, because it shouldn't be like that.

**Comment by Satyr87** [comment]
ive tried doing un'goro today on horde side and pretty much stuck there in something like half of quest chain , the only quest that lead me there was from the warchief board (nothing from tanaris or anywhere else was sending me there) , ive done few quests in marshal's camp and for those guys at the passage between tanaris and un'goro , and for this druid http://www.wowhead.com/npc=38263 , and saved Ringo http://www.wowhead.com/npc=9999 , collected foodstuffs and research equipment and thats pretty much over - no more quests , nothing sends me further for example to mossy pile where should be like 10 quests to do (ive managed to pick 1 but it didnt trigger anything else) , ive tried visiting questgivers being guided by wowhead map but only that retarded knight Maximillian gave anything

**Comment by Quban** [comment]
fix soon

**Comment by Aival94** [comment]
@Velius94 Hero' call quests should never disappear depend of your level. They disappear if you do one quest which is breadcumb to this one.

**Comment by Wolffenstein** [comment]
The low level ones SHOULD disappear after reaching a certain level, you can login on Blizzard's PTR and as a 90 level character you will only see breadcrumbs to Twilight Highlands, Uldum, etc.. Low level ones disappear because they are never required to start questing in any zone (the high level ones are).

**Comment by Aival94** [comment]
By this post there should not disappear generally but only from hero's call board(do not know if they have changed it during mop or later so sorry if they have) 

http://us.battle.net/wow/en/forum/topic/8729062899
