### ISSUE TITLE
[PL][Arena] Arena System

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#3960]
##### 5.Po zakonczeniu sezonu wystepuja resety MMR, co nie jest blizzlike i jest destruktywne dla kolejnych sezonow

-Na kazdym serwerze prywatnym jakim sie spotkalem, gracze wykorzystuja startowy 1500 MMR po zakonczonym sezonie aby "snajpowac" inne wysoko rankingowe druzyny ubranymi juz w poprzednim sezonie altami. Mozna latwo wydedukowac po co sie to robi i jakie sa proporcje w zdobywanym MMR po obu stronach.
-Gladiatorzy z poprzednich sezonow, ktorych MMR wynosil 2500, zaczynaja nowy sezon na farmieniu nieubranych/ niedoswiadczonych graczy na arenach.
-Sezonowy reset MMR zatrzymuje naturalna inflacje MMR wsrod aktywnych graczy na serwerze.

Nie jestem zwolennikiem zasady blizzlike na prywatnym serwerze, ale uwazam ze powinna byc przepasc w MMR pomiedzy ubranymi graczami oraz tymi nieubranymi. Dzieki temu nowi nieubrani gracze przegrywajac areny nie traca kosmicznej liczby MMR walczac na gladow z poprzedniego sezonu, Rowniez nie powinna powstawac zbyt duza przepasc pomieszy "topką". a cala reszta serwera, dlatego MMR kazdego gracza powinien byc zrownywany do poziomu 1500-2000 jezeli jest poza tym progiem.
##### 6.MMR jest rozdawany tak jak mialo to miejsce na retailu do s9 i wyglada tak na serwerze:

Nasz wygrany team w ktorym mamy do dyspozycji 24 MMR na wygrany team
GraczA: 500 MMR
GraczB: 2500 MMR

Wedlug starego s9 systemu gracze otrzymuja na serwerze po 12 MMR na glowe a powinni otrzymywac go zgodnie z wkladem "doswiadczenia MMR" ktory wlozyli w mecz. Niestety dokladna formula nie jest nigdzie podana i nie jestem w stanie jej odtworzyc do konca, jednak system ELO to system sprawdzony i napewno tutaj tez by sie sprawdzil.

Troche przykladow, gdyby udalo sie zaadaptowac system ELO

Czlonkowie Wygranej Druzyny:
1. 500 MMR
2. 2500 MMR

Personal_MMR_Gained_For_Player1 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player1 - MMR_Player2 / 400 ) ) )
Personal_MMR_Gained_For_Player1 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 500- 2500 ) / 400 ) ) = 23.9997600024

Personal_MMR_Gained_For_Player2 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player2 - MMR_Player1 / 400 ) ) )
Personal_MMR_Gained_For_Player2 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 2500- 500 ) / 400 ) ) = 0.0002399976

Podam troche innych przyladow:

Czlonkowie Wygranej Druzyny:
1. 1500MMR
2. 2000 MMR

Personal_MMR_Gained_For_Player1 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player1 - MMR_Player2 / 400 ) ) )
Personal_MMR_Gained_For_Player1 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 1500- 2000 ) / 400 ) ) = 22.7222348352

Personal_MMR_Gained_For_Player2 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player2 - MMR_Player1 / 400 ) ) )
Personal_MMR_Gained_For_Player2 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 2000- 1500 ) / 400 ) ) = 1.27776516485

Czlonkowie Wygranej Druzyny:
1. 1500 MMR
2. 1750 MMR

Personal_MMR_Gained_For_Player1 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player1 - MMR_Player2 / 400 ) ) )
Personal_MMR_Gained_For_Player1 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 1500 - 1750 ) / 400 ) ) = 19.3996241412

Personal_MMR_Gained_For_Player2 = Team_MMR_Gained \* ( 1 / ( 1 + 10 ^ ( ( MMR_Player2 - MMR_Player1 / 400 ) ) )
Personal_MMR_Gained_For_Player2 = 24 \* ( 1 / ( 1 + 10 ^ ( ( 1750 - 1500 ) / 400 ) ) = 4.60037585881

Mozesz kontrolowac MMR zmieniajac wspolczynnik z 400 na jakis inny. Jest to wspolczynnik wykorzystywany z podstawowego wzoru ELO w szachach.

Jako, że jest to prywatny serwer z małą ilością graczy to przydałaby się jakaś inflacja w zdobywanym MMR w stosunku do tego, ktory jest tracony. Aby nie przesadzic z inflacja nalezy obserwowac skutki poczynajac od 10-20%

Jezeli chodzi o kalkulowanie Team Ratingu, ta formula rowniez jest nieznana. Oczywiste jest tylko, ze personal rating oraz team rating powinny z czasem zrownywac sie ze sobą....

http://www.arenajunkies.com/topic/202541-mmr-when-abused-when-its-not/ // Abusowanie mmr-u w s9.
http://eu.battle.net/wow/en/forum/topic/1820952130

**Comment by Jenovas** [comment]
ArenaStartRating = 0
ArenaStartPersonalRating = 0
ArenaStartMatchmakerRating = 0
Czy wartości podane wyżej są poprawne?

Oraz dam przykład:
MMR Teamu = 3000
Team Rating = 2000
Czy za wygraną walkę MMR powinien tam podskoczyć o 10 a Team Rating o 96 żeby jak najszybciej wyrównać?

Oraz drugi przykład
Team Rating = 3000
MMR Gracza1 = 3000
MMR Gracza2 = 1000
Czy za wygraną Team Rating i MMR Gracza1 powinien podskoczyć o 10 a MMR Gracza2 i Personal Gracza2 o 96?

**Comment by Jenovas** [comment]
To tak system został trochę zmieniony. Niestety obsługa aren to jest wielka ilość kodu więc może pojawić się bug i może pojawić się możliwość że zrobimy reset aren pewnie, ale myślę że lepiej to ogarnąć teraz zanim zacznie się nowy sezon.

Ogólnie zmiany które wprowadziłem:
1. Jeżeli TeamMMR jest większy od TeamRating o więcej niż 96 to TeamRating będzie wzrastał o 96.
2. Jeżeli TeamRating jest większy od Personal Gracza o więcej niż 96 to dany gracz dostanie 96 Personala.
3. Jeżeli TeamRating jest większy od MMR Gracza o więcej niż 96 to dany gracz dostanie 96 MMR.

**Comment by Jenovas** [comment]
Dodatkowa zmiana do queue aren - jeżeli dany team czeka dłużej niż 5 minut to powinno go złapać z pierwszym lepszym teamem z w granicach o 0 do 5000 ratingu.

**Comment by kadi2** [comment]
@Jenovaa Wyglada na to, ze wiesz jak to powinno smigac. 

Takie info jakbys mial zamiar cos robic ze startowym MMR:
Pamietam, ze jak Wolf ustawial startowy MMR 1500 to postacie wylevelowane pozniej mialy MMR 1000.

**Comment by Jenovas** [comment]
Poprawki jeszcze nie zostały wgrane na serwer, chciałbym wpierw napisać o tym gdzieś żeby nie było potem zdziwienia jak byśmy musieli reset ratingu zrobić, ale mam nadzieje że będzie działać poprawnie.

**Comment by HaydenGT** [comment]
+1

**Comment by Jenovas** [comment]
Tylko kadi2 Ty tam wyżej napisałeś że MMR powinno być rozdawane po 24 na drużynę i rozdzielone tak że gracz z mniejszym MMR powinien dostać więcej, ale 24 wydaje mi się mało i tak ciężko mi się wydaje żeby było żeby MMR się wyrównał z team ratingiem etc. Muszę poczytać jeszcze trochę gdzieś o tym.

**Comment by nevcio** [comment]
Czyli np team z 2300 mmr i 2200 rating dostanie 96 ratingu za wygrana przeciw teamowi z np 1000 mmr? to nie brzmi zbyt blizzlike :p

**Comment by Jenovas** [comment]
1. When you start a new team, you'll be at 0 rating but at a much higher MMR, meaning that you'll gain 96 rating every win until you start getting close to your MMR.

2. I have seen a teams infront SW while dueling played games 90 = 57/32 rating 1924.
Me and my buddy had 340 played games 185/155 and we barely reached 1600 .
We disband it and with the new1 = 27 played 23/4 wins we were 1750 already.

Tak więc wydaje się bardzo Blizzlike. Dopóki Team Rating nie dogoni MMR to dostaje się kosmiczne wartości Team Ratingu żeby jak najszybciej się wyrównało. Jak w przykładzie wyżej 23 wygrane i 1750 tzn że dostawali blisko 80 za każdy win, ponieważ ich MMR jest wysoki a team rating niski, bo założyli nowy team.

Prosiłbym na przyszłość jeżeli ktoś coś wie to proszę napisać jeżeli ktoś nie wie albo zgaduje to niech lepiej się nie odzywa, bo robi niepotrzebne zamieszanie i przez niego będą potem błędy. Dziękuje.

**Comment by kadi2** [comment]
Jasne, to co napisalem bylo napisane zbyt ogolnikowo. 24 to byla przykladowa liczba, ktora wzialem, bo nie chcialo mi sie podawac kalkulacji biorac pod uwage MMR przeciwnego teamu. Wszystko ladnie bedzie sie wyrownywalo ze soba tylko i wylacznie jezeli naprawimy ponizszego buga.

6.MMR jest rozdawany tak jak mialo to miejsce na retailu do s9 i wyglada tak na serwerze:

Postaram sie napisac cos wiecej jak wroce do domu.

**Comment by Jenovas** [comment]
To moje fixy biorą to pod uwagę. Gracz z małym MMR będzie dostawał 96 aż do wyrównania, gracz z dużą ilością MMR będzie dostawał według wzoru który obecnie używamy.

**Comment by latarnia93** [comment]
Nareszcie jakieś pozytywne zmiany.
"Prosiłbym na przyszłość jeżeli ktoś coś wie to proszę napisać jeżeli ktoś nie wie albo zgaduje to niech lepiej się nie odzywa"
Brawo za podejście, złota zasada która powinna być stosowana w każdym temacie dotyczącym pvp))

Może zamiast ryzykować koniecznością resetowania teamów/mmru pod koniec sezonu, zebrać grupę osób która zna się na rzeczy i to ztestuje? Chętnie pomożemy.

**Comment by nevcio** [comment]
Jakby to było blizzlike to praktycznie nie istniałyby przyrostu ratingu +40, +70 itp, bo na początku byłby nonstop +96 a po wyrównaniu ratingu z mmr nagły spadek do około +15, a uwaga - jest mnóstwo filmików na których po wygranej arenie na ludzi o podobnym mmr gracze dostają np +40. Chcę powiedzieć, że dodawanie +96 rata aż dopóki różnica mmr i ratingu jest mniejsza niż 100 jest znacznym uproszczeniem, ale jak ja śmiem w ogóle zabrać głos, przecież nic nie wiem

**Comment by Jenovas** [comment]
Nevcio wyżej pokazałem dwie wypowiedzi graczy z globala i policzyłem że wychodzi 80rate za win.

**Comment by kadi2** [comment]
Przepraszam was, ze stworzylem troche uproszczony report. Sprawa z +96 oczywiscie nie jest taka oczywista [GitHub Logo](http://i.imgur.com/0xRSbAh.png)

Prawdopodobnie wystepowala jakas formula malejaca w "booscie +96" Nie widze przeciwskazan, ku temu by uproscic te formule, ktorej nigdy nie poznamy. Wazne jest to, aby gracze mogli co chwile zmieniac druzyny bez utraty swojego progressu z poprzednich druzyn.

Te przyrosty +40 MMR, o ktorych mowisz mogly wynikac rowniez z systemu stabilizacji MMR graczy tuz przy wylevelowaniu postci. Otoz, gdy zaczynasz areny jako swieza 85, twoje zmiany MMR mnoza sie kilkukrotnie. Mialo to za zadanie szybsze umieszczenie cie w twoim przedziale MMR o wiele szybciej. Nie wydaje mi sie jednak, ze ktokolwiek chcialby, zeby cos takiego bylo tutaj wprowadzone.

@Jenovas Obawiam sie, ze te fixy nie biora pod uwage tego, ze czlonek druzyny wygranej z mniejszym MMR powinien otrzymywac wiecej MMR, niz ten z wyzszym MMR. Przez co nie bedzie mozliwe zrownanie Personal ratingu osoby z niskim MMR do Team Ratingu. Druga sprawa to taka, ze ludzie zaczna wkoncu dostrzegac fakt, ze MMR jest dzielony na pol i beda grali ze swoimi altami o niskim MMR, aby zboostowac MMR gracza o wyzszym MMR. Bedzie dochodzilo do przypadkow, ktore sa opisane w artykule Dakkrotha z AJ, ktory link podalem w pierwszym poscie.

**Comment by debtheone** [comment]
Hej jak idą prace?

**Comment by Jenovas** [comment]
Wspólnie z Wolfem postaram się coś niedługo wrzucić, a tak to walczymy z diffem na serwerze i może się chwile niektóre poprawki przeciągnąć (za co przepraszam, ale co z tego że będzie działać jak mamy po 300-500 diffa jak wbija 1300 online).

**Comment by kadi2** [comment]
2. Jeżeli TeamRating jest większy od Personal Gracza o więcej niż 96 to dany gracz dostanie 96 Personala.

Wzrost personal rating powinien byc zalezny tylko od MMR gracza. Nie mozna dopuscic do sytuacji, gdzie gracze beda miec wyzszy personal rating niz swoj MMR po zagraniu kilku aren w Teamie majacym wysoki Team Rating.

Wyobraz sobie, ze ktos z podstawowym MMR 1500 dolacza do druzyny z 2200 ratingiem i po kilkunastu wygranych arenach ma MMR 1600 oraz 2200 Personal rating. Jestem na sto procent pewien, ze wzieliscie to pod uwage, ale zawsze warto napisac dla pewnosci.

**Comment by Jenovas** [comment]
Kadi2 nie.
2. Jeżeli TeamRating jest większy od Personal Gracza o więcej niż 96 to dany gracz dostanie 96 Personala.
3. Jeżeli TeamRating jest większy od MMR Gracza o więcej niż 96 to dany gracz dostanie 96 MMR.
Nie bedzie ze personal bedzie wiekszy od MMR bo wspolnie rosna o tyle samo. Nie mozna tych punktów osobno rozpatrywać.

"Wyobraz sobie, ze ktos z podstawowym MMR 1500 dolacza do druzyny z 2200 ratingiem i po kilkunastu wygranych arenach ma MMR 1600 oraz 2200 Personal rating. Jestem na sto procent pewien, ze wzieliscie to pod uwage, ale zawsze warto napisac dla pewnosci." - nie bo będzie za każdy win dostawał 96 MMR i 96 Personal tak więc w krótkim czasie wbije 2200 MMR i 2200 Personal.

Niestety u nas wzór z globala słabo się sprawdza, bo mamy mało teamów, przez co teamy 2k rate spotykają się często z 1k rate (jak nie 90% walk). Tak więc wbijanie wyższego rate to męczarnia. Niewiem co możemy z tym zrobić. 

Po moich fixach niby szybciej będzie się równać MMR, Personal i Team Rating dla nowych członków teamu czy jak założycie nowy team, ale to wciąż nie zmienia faktu że jak się wyrówna wszystko to za win potem będzie dalej +5 a za lose -50.

**Comment by Scrimish** [comment]
czy ktos jeszcze pracuje nad powyszszym problemem? Bo majac 1600 rating, traci sie przykladowo -20 ratingu za przegrana walke a zyskuje 4 za win. Bardzo watpie ze co drugi team ktory spotykam na arenie z pelnym pvp ekwipunkiem ma mniej niz 1000mmr (a startowy to 1500). Bo taka redysproporcja ratingu za walke jest conajmniej depresyjna. Powyzsza sytuacja bylaby zrozumiala gdybym ja mial 2k+ ratingu, ale 1600? Gralem na wilu prywatnych serwerach (czasem z mniejsza populacja niz tutaj), ale takich rzeczy nie widzialem.

**Comment by kadi2** [comment]
@Scrimish  startowy MMR raczej napewno nie wynosi 1500, a fakt ze spotykasz full ubranych ludzi w vicious sety to jest glowniee nastepstwo ostatniego resetu MMR przy zakonczeniu sezonu.

**Comment by Brightflame** [comment]
"3.Problem łączenia drużyn w queue - powód jest bliżej nieznany." 

Problem wciąż istnieje. Aktualnie jestem zapisany od 15min na arene 2v2. Widzę jak inne teamy o różnych mmrach sobie grają, a mnie z nikim nie łączy. Problem jest częsty i występuje zarówno na 2v2 i 3v3.

**Comment by debtheone** [comment]
maybe Average wait time: Unavailable has something to do with it

**Comment by Jenovas** [comment]
Bardzo dziwne że nie chce łączyć teamów. Przez ostatnie kilka dni rozbierałem na drobny mak cały system łączenia BG i Aren. Zrobiłem testy gdzie wirtualnie zapisuje się 1500 teamów z różnym ratingiem i niestety wszystkie 1500 teamów po 5 minutach się połączyło tak więc nie wiem co może być przyczyną że na serwerze wciąż źle łapie. Najpewniej będę musiał dodać jakieś logi które będą nam mówić co się dzieje.

Tak więc na czym stoimy:
1. Poprawki do zdobywania ratingu i MMR najpewniej wgram w ten weekend jak będzie czas i nie pojadę do rodziców. Zobaczymy jak się zachowa, jak się coś zepsuje to się na szybko wycofa a ja znów nad tym usiądę.

2. Niestety wciąż nie wiem dlaczego nie łączy niektóre teamy, ALE zostaną wgrane drobne zmiany które możliwe że poprawią trochę sytuację. Również chce naprawić kolejkowanie na Rated BG.

3. W niedługim okresie postaram się dodać możliwość zapisanie na RDFa i na RBG na raz. Już działa zapisywanie na obie kolejki, ALE muszę dorobić automatyczne wywalanie z wszystkich kolejek po przyjęciu inva na RBG albo RDF a z tym niestety mam kilka problemów.

Był pomysł żeby dać możliwość zapisywania się graczom PvP na RBG i Arene na raz - co o tym myślicie? Póki co nie wiem czy to możliwe, ale chciałbym wiedzieć wcześniej czy zostanie to pozytywnie przyjęte, bo jak negatywnie to nie ma sensu żebym to pisał.

**Comment by Jenovas** [comment]
rev. 4610 
PvP:
fixes to Arena Queue System - needs testing, also please check if Rated BG works after this fix and send me a report
changes to gained rate from arena's - MMR, Personal and Team Rating will grow faster until they are even

**Comment by debtheone** [comment]
jak tam idą prace ?

**Comment by Jenovas** [comment]
Nowy Arena System skończony, zostały tylko testy.
Zapisywanie na RBG + RDF na raz skończone, zostały tylko testy.

**Comment by debtheone** [comment]
co nowego w tym systemie ?

**Comment by Jenovas** [comment]
Zmieniłem to że 3v3 i 5v5 powinno działać a do tej pory nie działało.
Zmieniłem że 2v2 powinno już dobrze działać i teamy nie powinny czekać 15 minut i zero walk a inne teamy grają. Do tego dynamiczny MMR - co minute rośnie zasięg teamów który może połączyć. Do tego optymalizacja.

Co do personala i MMRa - zmiana zostanie przywrócona moja ostatnia czyli +96 rata do momentu wyrównania ratingów. A co dalej nie wiem, pewnie trzeba będzie własne wzory wymyślać bo wzory blizzarda są dla tysięcy teamów dobre a nie dla kilkunastu.

**Comment by Scrimish** [comment]
Jenovas a powiedz, pytam z ciekawosci, jest to mozliwe aby zaimplementowac system jaki byl za czasow tbc? Mam na mysli pozbawienia calego systemu mmr. Za czasow tbc teamy byly laczone tylko i wylacznie poprzez team rating. Blizzard to zmienil aby wyeliminowac zjawisko boostowania. Na prywatnym serwerze jak Atlantiss nie jest to problemem w zadnym stopniu. Poza tym system sprawdzal sie rewelacyjnie na serwerach prywatnych + umozliwial graczom z wyzszym ratem zakladanie nowych grup bez utrudnien jak mmr. Poza tym pkt jakie otrzymujesz za wygrany mecz i przegrany wciaz dzialaja strasznie niepoprawnie. Podam Ci przyklad (global) majac mmr 1700 doszedlem do teamu z ratem 2,2k (partner mial 2,2k mmr). I dokladnie po 21 walkach (17-4) mialem na postaci ktora ledwo doszla do teamu (startowy rat 1k teamu) mialem 2,2k achieve. Tutaj nieosigalne w zadnym stopniu. I mysle ze dluga droga nas czeka aby doprowadzic to do stanu grywalnosci. 
 Jesli jest mozliwa implementacja systemu z tbc moze by ja rozwazyc.
P.S. Co z Solo q 3v3?

**Comment by debtheone** [comment]
ktoś może sprawdzić czy perso działa po fixie ?

**Comment by Kejmil** [comment]
juz uzyte do zabusowania i kupienia elite gearu i broni 372
http://atlantiss.eu/armory/character/106587/activity#view-page
