### ISSUE TITLE
[EN][Item] Inscription Scrolls

### ISSUE THREAD

**Issue by tdotzlod** [Atlantiss/BugTracker#3962]
There is similar issue open (https://github.com/Atlantiss/BugTracker/issues/2168) and assume core of problem is the same.

Inscription scrolls is getting replaced by player's buff with similar stats.

Warrior's battle shout, dk's horn of winter and shaman's strength of earth totems replace scrolls of agility/strength. And stamina buffs such as commanding shout replace scroll of stamina (not the scroll of fortitude) while they shouldn't.

Proofs http://www.wowhead.com/spell=21562/power-word-fortitude#comments
http://www.wowhead.com/spell=6673/battle-shout#comments:id=1362371

**Comment by jissabraham** [comment]
plz fix this issue

**Comment by zotmer** [comment]
This huge problem still persists! Should be high priority fix as it is pretty game-breaking bug.

**Comment by karhima** [comment]
bump

**Comment by lamaATS** [comment]
`Inscription scrolls is getting replaced by player's buff with similar stats.`
It's not a bug.

If I'm wrong give me any Video proof where someone has for examples both stamina from scroll and from priest.

**Comment by karhima** [comment]
Kinda funny how you delete comments and simply close this issue, acting as if all players who have made the effort to report it here, are simply wrong. This makes me stop contributing here. kthxbai

**Comment by lamaATS** [comment]
I don't know what are you talking about sorry, sometimes when are I see comments with only `DUMP` I removing but only in this case.
Maybe someone how posted the commend removed it? If You have message what was there please post it here If you can.
