### ISSUE TITLE
[EN][Raid] Icecrown Citadel

### ISSUE THREAD

**Issue by LordMoriarty** [Atlantiss/BugTracker#3965]
The Chill of the Throne debuff(-20% dodge) was active on our characters. It was removed in 4.0.1 ( source: http://www.wowhead.com/spell=69127/chill-of-the-throne#comments )

I(raid leader) couldn't talk to Garrosh and we did not have the Hellscream's Warsong ( http://www.wowhead.com/spell=73822/hellscreams-warsong#comments ).

The alliance version is http://www.wowhead.com/spell=73828/strength-of-wrynn (I DO NOT know if this version works)

**Comment by Thefakemccoy** [comment]
Adding more notes:

Dream Walker drops no loot
http://www.wowhead.com/npc=36789/valithria-dreamwalker

When you die on LK at the end Tirion should mass rez any one killed by the LK ability at the end mass rez does not work

And of course the ship battle is not scripted
http://www.wowhead.com/object=201873/gunship-armory

**Comment by mastercho** [comment]
after 1 year is still same...

**Comment by lamaze** [comment]
it's not the same, we noticed that festergut is bugged to he resets at pull :D

**Comment by Samineh** [comment]
Sorry I will post the issues that are not mentioned here (this will be edited alot xD): #9260

**Comment by Smiite** [comment]
Still waiting for gunship battle

**Comment by Smiite** [comment]
Bump

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by pelekon** [comment]
bump

**Comment by Aviannaqt** [comment]
siemano

**Comment by Aviannaqt** [comment]
@Elannreportujerzeczy @Smiite https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Elannreportujerzeczy** [comment]
@Aviannaqt https://www.youtube.com/watch?v=L_jWHffIx5E

**Comment by Aviannaqt** [comment]
@Aviannx

**Comment by Piklo** [comment]
should be fixed in [rev. 5613](https://atlantiss.eu/changelog#rev5613)
