### ISSUE TITLE
[EN][Quest][Scarlet Monastery] Compendium of the Fallen

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3967]
quest dont work 
see in wowhead http://www.wowhead.com/object=19283/compendium-of-the-fallen

**Comment by EnderBlazer** [comment]
It works, I did it approximately two weeks ago. What most likely hapenned was that one of your party members used the book first to complete his quest, making the book disappear for the rest of the party. What you need to do is either wait for it to respawn (I don't know if it does) or try again and get to the book first

**Comment by iliarakov** [comment]
ok thanks :)

**Comment by Avalain** [comment]
Worth checking out, done SM recently and I was first near the book. 
Couldn't interact with it and neither other party members. 
Book was glittering, quest was in quest log.

**Comment by Quellz** [comment]
Only one person can grab the book per instance, apparently.

**Comment by Alessi4** [comment]
i had the same problem and i made a little video http://webm.host/9418a/ 
i hope it helps

**Comment by iliarakov** [comment]
yes and i cant to get book

**Comment by armano2** [comment]
duplicate: #1559
