### ISSUE TITLE
[EN][Professions] Leatherworking

### ISSUE THREAD

**Issue by Talona** [Atlantiss/BugTracker#3969]
You get http://www.wowhead.com/item=56527/bloodied-dragonscale-shoulders instead of http://www.wowhead.com/item=75116/vicious-dragonscale-shoulders .

This bug also happens for other Vicious Dragonscale Items ( http://www.wowhead.com/items=4.3?filter=na=Vicious+Dragonscale ).

![wowscrnshot_072715_132546](https://cloud.githubusercontent.com/assets/13520460/8905383/26910cc4-3466-11e5-9361-5ddbb3c8c68b.jpg)

![wowscrnshot_072715_132615](https://cloud.githubusercontent.com/assets/13520460/8905385/2d6a6518-3466-11e5-9f6c-8a55ae6afc69.jpg)

**Comment by Wolffenstein** [comment]
Intended.
