### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] A Blight Upon the Land

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#397]
What is not working:
=============

The event doesn't trigger. So, it's impossible to complete the quest because after the event the NPC turns hostile and you need to kill to complete the quest.

---------------
How should work:
=============

An event should start when you bring [Lydon](http://www.wowhead.com/npc=47900/master-apothecary-lydon) near [Warden Stillwater](http://www.wowhead.com/npc=48080).
I'll post some videos below, usually a picture worth a 1000 words.

----------------------
More info:
=============

I guess this is somekind of phase, because NPCs' position are slightly different when you pick the firsts quests.

This quest is very important because it brokes the whole chain, without it, the players are losing +10 quests (Hillsbrad Foohills achiev quest included).

[Video#1](http://youtu.be/vpfdPCM04rw?t=18m39s)
[Video#2](http://www.youtube.com/watch?v=o5bgUcOQEJw)
[Video#3](http://www.youtube.com/watch?v=vmEmaq5q_9k)
[A Blight Upon the Land - WoWHead](http://www.wowhead.com/quest=28237)
[A Blight Upon the Land - WoWPedia](http://wowpedia.org/Quest:A_Blight_Upon_the_Land)

**This was tested on 4.0.6a realm**

**Comment by Duffy15** [comment]
This quest still don't work, so i'm hoping it gonna work soon.

**Comment by bohntron** [comment]
I attempted this quest yesterday, to no avail.  Same error mentioned in the original post, where Warden Stillwater is supposed to speak with Lydon once you draw near, but nothing happened.  I attempted to abandon/restart the quest, logout/login, even trying to accept the quest far away from the sludge fields (as the npcs follow all the way to the southpoint gate), yet nothing worked. (Note: Warden Stillwater doesn't change his position like shown in the videos linked above.  He is still standing back near the doorway with the line of guards in front of him no matter what I try.)

**Comment by SMFloris** [comment]
Today on 9.01.2015 does not work. This is a very important quest for the undead quest chain, I noticed the same things as bohntron.

**Comment by banexdurex** [comment]
Still doesn't work, I've been trying for couple of days but still nothing happens when Lydon gets near Stillwater

**Comment by Spydoc** [comment]
Confirmed, Warden Stillwater never turns hostile, although both quest givers are close to him.

**Comment by Kubion** [comment]
Still bugged.

**Comment by Vinii** [comment]
BUMP 25.03.2015 Still bugged.

**Comment by Griskhet** [comment]
Still bugged

**Comment by bgb** [comment]
Confirmed, still bugged:(

**Comment by HopMage** [comment]
Still bugged - please fix

**Comment by Jokoga** [comment]
still bugged

**Comment by Anhaeyn** [comment]
Still bugged.

**Comment by Bildo** [comment]
fix is coming :D

**Comment by Bildo** [comment]
fixed

**Comment by Articuno** [comment]
Not fixed, still bugged.

**Comment by Bildo** [comment]
because ?

**Comment by PVPieter** [comment]
Because it looks like nothing has changed. When you arrive nothing happens, a cutscene should start so that you can attack Warden Stillwater.

**Comment by petrock420** [comment]
maybe put a temporary fix in like put an aggroable warden stillwater some where close to the building behind the non-aggroable warden stillwater

**Comment by Quellz** [comment]
Bugged. Cutscene does not trigger and you cannot fight the boss.

**Comment by Enslaved** [comment]
Nope,didn't work at me at all.

**Comment by HUnta1337** [comment]
still bugged now gotta create another character or go to another server:/

**Comment by Quellz** [comment]
@HUnta1337 - "a quest doesn't work so I'm leaving the server"

Is that what you're trying to say? Nonetheless, enjoy and do whatever you have to do. Just seems really stupid to me.

**Comment by IndrifValk** [comment]
The quest is not glitched, you have to pull the mobs right ONTO him- It worked for me. I brought them right on him and they slowly walked in front of him, had a convo then the fight started.
