### ISSUE TITLE
[PL][Quest]The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Grimri** [Atlantiss/BugTracker#3971]
Chciałbym zgłosić nie działający quest The Soul Cannon of Reth'hedron. Nie można zdobyć w nim Flawless Arcane Essence http://www.wowhead.com/item=32822/flawless-arcane-essence ponieważ po rozmowie z NPC Sar'this http://www.wowhead.com/npc=23093/sarthis nie ma możliwości przyzwac Flawless Arcane Elemental niezbędnego do zrobienia questu

**Comment by Wolffenstein** [comment]
#2426
