### ISSUE TITLE
[EN][Quest][Feralas] Wild Leather Shoulder

### ISSUE THREAD

**Issue by mariohenriquebr** [Atlantiss/BugTracker#3972]
Hello,
I'm reporting the Leatherworking quest from Feralas, Wild Leather Shoulders. I took the quest with Jangdor Swiftstrider at Stonemaul Hold. When i got the materials to the quest, I went to Camp Mojache, Feralas, where I should turn in the quest, but the NPC wasn't there, and when I went to Stonemaul Hold, where I got the quest, I can't complete the quest the same way.

Thank you, Furioso

http://www.wowhead.com/quest=2855/wild-leather-shoulders

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by mariohenriquebr** [comment]
Oh, sorry!

**Comment by pelekon** [comment]
This quest and other quests from Wild Leather series schould be disable on our server. Blizzard deleted those quests in patch 4.0.3a.
