### ISSUE TITLE
[EN][Quests][Bloodmyst Isle] Bloodmyst Isle Quest order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#3976]
[Alien Predators](http://www.wowhead.com/quest=9634/alien-predators) should be available when Completing quest [Hero's Call: Bloodmyst Isle!](http://www.wowhead.com/quest=28559/heros-call-bloodmyst-isle) or [Elekks Are Serious Business](http://www.wowhead.com/quest=9625/elekks-are-serious-business)

[What Argus Means to Me](http://www.wowhead.com/quest=9693/what-argus-means-to-me) should be available after completing quest [Report to Exarch Admetius](http://www.wowhead.com/quest=9668/report-to-exarch-admetius)

[Nolkai's Words](http://www.wowhead.com/quest=9561/nolkais-words) should be available after completing quest [Deciphering the Book](http://www.wowhead.com/quest=9557/deciphering-the-book)

[Intercepting the Message](http://www.wowhead.com/quest=9779/intercepting-the-message) should be available after completing quest [Blood Watch](http://www.wowhead.com/quest=9694/blood-watch)

[Culling the Flutterers](http://www.wowhead.com/quest=9647/culling-the-flutterers) should be available after completing quests [The Bear Necessities](http://www.wowhead.com/quest=9580/the-bear-necessities) and [Constrictor Vines](http://www.wowhead.com/quest=9643/constrictor-vines)

[The Cryo-Core](http://www.wowhead.com/quest=9703/the-cryo-core) should be available after completing quest [I Shoot Magic Into the Darkness](http://www.wowhead.com/quest=9700/i-shoot-magic-into-the-darkness). Other bugs: https://github.com/Atlantiss/BugTracker/issues/3742

[Matis the Cruel](http://www.wowhead.com/quest=9711/matis-the-cruel) should be available after completing quest [Galaen's Journal - The Fate of Vindicator Saruan](http://www.wowhead.com/quest=9706/galaens-journal-the-fate-of-vindicator-saruan)

[Don't Drink the Water](http://www.wowhead.com/quest=9748/dont-drink-the-water) should be available after completing quest [The Cryo-Core](http://www.wowhead.com/quest=9703/the-cryo-core)

[Urgent Delivery](http://www.wowhead.com/quest=9671/urgent-delivery) should be available only if you have completed quest [A Small Start](http://www.wowhead.com/quest=9506/a-small-start)

[Ysera's Tears](http://www.wowhead.com/quest=9649/yseras-tears) should be available after completing quest [Mac'Aree Mushroom Menagerie](http://www.wowhead.com/quest=9648/macaree-mushroom-menagerie)

[Artifacts of the Blacksilt](http://www.wowhead.com/quest=9549/artifacts-of-the-blacksilt) should be available after completing quest [Explorers' League, Is That Something for Gnomes?](http://www.wowhead.com/quest=10063/explorers-league-is-that-something-for-gnomes)

 [Galaen's Journal - The Fate of Vindicator Saruan](http://www.wowhead.com/quest=9706/galaens-journal-the-fate-of-vindicator-saruan) should be available after completing quest [Intercepting the Message](http://www.wowhead.com/quest=9779/intercepting-the-message)

[Into the Dream](http://www.wowhead.com/quest=9688/into-the-dream) should be available after completing quest [Restoring Sanctity](http://www.wowhead.com/quest=9687/restoring-sanctity)

[Razormaw](http://www.wowhead.com/quest=9689/razormaw) should be available after completing quest [Into the Dream](http://www.wowhead.com/quest=9688/into-the-dream). Other Bugs: https://github.com/Atlantiss/BugTracker/issues/3384

[Saving Princess Stillpine](http://www.wowhead.com/quest=9667/saving-princess-stillpine) should be available only if you have completed [Stillpine Hold](http://www.wowhead.com/quest=9559/stillpine-hold)

**Comment by Champions2012** [comment]
![wowscrnshot_080315_000624](https://cloud.githubusercontent.com/assets/13512234/9150783/2596a67e-3deb-11e5-802b-bc75201ccfb5.jpg) Could u make a report about this thing. I don't think this is how it should give you quests.

**Comment by Champions2012** [comment]
Also this one 
![wowscrnshot_080515_024810](https://cloud.githubusercontent.com/assets/13512234/9150804/d25146c6-3deb-11e5-9fba-4b164e35c4a9.jpg)
