### ISSUE TITLE
Priest Shadow Paralysis

### ISSUE THREAD

**Issue by fmalust** [Atlantiss/BugTracker#3979]
This talent doesn't work, like at all. I searched and couldn't find anything about it on the bug tracker. But yeah, I don't know if it'll work in pvp but it wont work in pve at all that I had to respec to skip it entirely.

**Comment by Pallitax** [comment]
Duplicate of [#3790](https://github.com/Atlantiss/BugTracker/issues/3790) and

• Title doesn't follow the guidelines
• No wowhead link for the talent provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
^
