### ISSUE TITLE
[EN][Quest][Un'Goro Crater] The Spirits of Golakka Hot Springs

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#398]
http://www.wowhead.com/quest=24706

So in quests prior to this one, I had Maximillian following me, though he was kinda buggy, but I did manage to complete previous quests. While doing quests before this one, Maximillian was actually stopping and saying prayers for THIS quest, but that was when I didn't have this quest yet.

After I've finished the other quests, and I got this one, the NPC was gone (NPC, as in version of Maximillian that's following you on his horse for the quests that you get from him).

I tried abandoning the quest and taking it again, I tried talking to NPC, but there's nothing to be done. I just can't get him to spawn for me again, BUT he was actually saying prayers for this quest, before I even had this quest.

So, I just think this needs some fine tuning, make the NPC that's following you a bit more stable, because he's quite buggy (Goes into walking movement mode sometimes, stops and won't move, and the main reason for this report, he disappeared for me)
(http://www.wowhead.com/npc=38255 - this is the NPC that should be following you around and helping)

I don't know if he just got bugged for me, and won't spawn again, or it's the case for everyone, but it's definitely a possibility, since it happened to me.

https://www.youtube.com/watch?v=XbQ5ytULdbw - There's the video

Just want to add that he was only repeating the first line of the prayer when I had him following me (Though, you should note that he probably shouldn't be saying prayers if you're not on this quest, obviously)

So he was just repeating "Squire! Please stand next to me as I request the blessing of this light-blessed spirit.", so anyway, when you get to fixing this, be sure to make his "Speaking" script go all the way, it's nice to see these things working ^^

**Comment by Aival94** [comment]
this bug still occur on 4.3.4 and furthermore you cannot take this quest because after pressing is send you to epilogue like it is autocomplete but choosing complete quest not give quest or complete quest at all.

![wowscrnshot_011315_213347](https://cloud.githubusercontent.com/assets/10282971/5727461/023830ca-9b6c-11e4-9497-703305009b22.jpg)

![wowscrnshot_011315_213353](https://cloud.githubusercontent.com/assets/10282971/5727469/0966836a-9b6c-11e4-9b11-093e49931e60.jpg)

**Comment by darklord88** [comment]
Same priblem i abandoned the npc when he fighted with me vs dragons and i cant do this quest now coz i miss the npc :/

**Comment by worgenman** [comment]
yes please fix it, it cant be completed, i accept it but he dont follow or talk to spirits

**Comment by Dexobox** [comment]
+1 confirm this is stll bugged

**Comment by Aival94** [comment]
For me for old chars it cannot be completed but i have done it before 2 weeks as a new char i had created.

**Comment by Satyr87** [comment]
doesnt work , you cant summon him to follow you anymore and you need that "horse" version of him to complete this quest , you could summon him while doing quests before this one , just now its gone

**Comment by siwy92** [comment]
stil not work

**Comment by karhima** [comment]
Yes, still not working.

**Comment by Klickeazy** [comment]
It isnt working for me as well but I have an idea. It is to get the NPC to travel with you once and it is possible to complete the previous two quests without travelling with him. If possible, finish the previous two quests without him and then try going with him to finish this quest. If someone could test this and put up their observations, might help understand the problem better.

**Comment by hawcik** [comment]
Still not working.

**Comment by RastaTinu** [comment]
Quest still doesn't work

**Comment by Snake90** [comment]
Still bugged :/ What a surprise !

**Comment by Cebarus** [comment]
Still bugged after 2 years! I literally quit Warmane when I couldn't do this quest to get my Transmog shield, don't make me regret it =/

**Comment by Snake90** [comment]
Ok, so what is the "proper quest order" ?

**Comment by Aival94** [comment]
As far as i found the order should be:
1. [An Important Lesson](http://www.wowhead.com/quest=24703/an-important-lesson)
2. [Damsels Were Made to be Saved](http://www.wowhead.com/quest=24705/damsels-were-made-to-be-saved)
3. [The Spirits of Golakka Hot Springs](http://www.wowhead.com/quest=24706/the-spirits-of-golakka-hot-springs)

I have not done it for some time but i think that was the order and their prerequisites.

**Comment by Snake90** [comment]
Ok, so the quest is really bugged because I've done the quests in that order and i can do the two first but not the third. The NPC doesn't move, doesn"t do anything and i can't talk to him to begin eventually this mini-event.

**Comment by Cebarus** [comment]
this is so upsetting! i really need this shield for my x-mog set, it's been 2 years christ! bump it up boys

**Comment by Cebarus** [comment]
3 years*

**Comment by Bildo** [comment]
Quest has been added to my sprint
