### ISSUE TITLE
[EN][Quest][The cape of Stranglethorn] Our Mortal Enemies

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3981]
quest dont work
see in wowhead http://www.wowhead.com/quest=26648/our-mortal-enemies
see video https://www.youtube.com/watch?v=xgsmgJVDuyU

**Comment by Champions2012** [comment]
This quest is working. Use your Dead-Eye's Flare Gun and u will summon a dwarf that will reveal all ninjas. I did it yesterday.

**Comment by iliarakov** [comment]
yes i use but i dont find them
