### ISSUE TITLE
Rogue talent tree (Combat)  [Bandit's Guile]

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#3982]
It says that 100% proc when using Sinister Strike or Revealing Strike but its not a 100% proc whenever i use it.

**Comment by zano354** [comment]
yeah, its only proc when we hit 4 times either sinister strike / revealing strike. It should be proc on the first time it damage with sinister / revealing strike

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
"This has been figured out over at Elitistjerks. it takes 4 uses of either Sinister Strike or Revealing Strike (Any combination of the two) to make it go up one level."
also, rules
