### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Traveling Companions

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#3984]
when i speak with Npc  is noting happend
see in wowhead http://www.wowhead.com/quest=27381/traveling-companions
see video https://www.youtube.com/watch?v=EkZd8z_Yfvg#t=26

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Quellz** [comment]
Not an admin, but this might be you just doing it the wrong way. You have to pick up the quest from him, and upon completion of the quest, he will join you.

**Comment by iliarakov** [comment]
ok thanks :)
