### ISSUE TITLE
[EN][Player][Slowness]

### ISSUE THREAD

**Issue by demon034** [Atlantiss/BugTracker#3985]
I am so sloooooow. My ms is 0. Everything is slowed down to me. Flying, abillities, other people... Chatting works as it should. I talked to a GM about it and he suggested to me that I make a video and report it on bugtracker. Here is a video to a video that I made about this problem: https://www.youtube.com/watch?v=dnO9cpc6jfY&feature=youtu.be

**Comment by kadi2** [comment]
You took the wrong pill Neo ![LOL](https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Red_and_blue_pill.jpg/220px-Red_and_blue_pill.jpg)

**Comment by armano2** [comment]
Issue is not related to serwer code. It's can sometimes happend when load in system is to high (on server).
