### ISSUE TITLE
[EN][Quest][Badlands] Lifting the Veil

### ISSUE THREAD

**Issue by dondrakis** [Atlantiss/BugTracker#3986]
She stands and do nothing, dragon does not appear.

http://www.wowhead.com/quest=27770/lifting-the-veil
It should work like that https://www.youtube.com/watch?v=Egz2AsdgOpo

**Comment by Varchord** [comment]
you know what? fuck it, i bet this one is reported already too
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by zeoos** [comment]
#1632

**Comment by Alessi4** [comment]
i had the same problem i have made a short video http://webm.host/83b40/ i hope it helps

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/1632
