### ISSUE TITLE
[EN][Quest][Badlands] The Sentinel's Game

### ISSUE THREAD

**Issue by dondrakis** [Atlantiss/BugTracker#3987]
Statues does not appear, q broken.

It should work like that https://www.youtube.com/watch?v=QlAP4l0DLSU

**Comment by Varchord** [comment]
you know what? fuck it, i bet this one is reported already too
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by zeoos** [comment]
#2017

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2017
