### ISSUE TITLE
[EN][Quest][Badlands] The Warden`s Game

### ISSUE THREAD

**Issue by dondrakis** [Atlantiss/BugTracker#3988]
Statues does not appear, q broken.

It should work like that https://www.youtube.com/watch?v=s4lvnQoIaoU

**Comment by Varchord** [comment]
you know what? fuck it, i bet this one is reported already too
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by zeoos** [comment]
#2016
