### ISSUE TITLE
[EN][Quest][Badlands] Baelog, the Glass Cannon

### ISSUE THREAD

**Issue by dondrakis** [Atlantiss/BugTracker#3989]
Dwarf does not appear as your companion, q broken.

**Comment by Varchord** [comment]
you know what? fuck it, i bet this one is reported already too
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by zeoos** [comment]
#3303

**Comment by armano2** [comment]
duplicate: #3303
