### ISSUE TITLE
[EN] [Quest] [Silverpine Forest] Seek and Destroy

### ISSUE THREAD

**Issue by poilmok** [Atlantiss/BugTracker#3994]
Hello,

I have a problem with the quest [ Seek and Destroy] : http://www.wowhead.com/quest=27193/seek-and-destroy

I can't recover Smithers' Logbook.

This dear Smithers doesn't go down, it remains high and i can't attack him whatever I do.  I have every time "You're not facing the right direction" but I tried to attack him from all sides. And it's imposssible to join him without flying. 

Thanks for helping.

Have a good day :)

**Comment by MostDakka** [comment]
Can confirm. Npc is stuck in a wall making quest uncompletable.
