### ISSUE TITLE
[EN][Quest][worgen] a really bad lag when u r about completing quests here

### ISSUE THREAD

**Issue by worgenman** [Atlantiss/BugTracker#3997]
hey guys

thank u so much for ur great server

well it seems when u r about completing quests in worgen zone suddenly it will lag for u for some seconds and its really bad. i even asked others too while playing and they had it too, can u please check and fix it?

thank u so much

**Comment by Champions2012** [comment]
This also happend to me when i was leveling in goldshire

**Comment by worgenman** [comment]
yea its strange, i still have it even in darkshire now, maybe its related to worgens and wod high quality models mod cause i have no problem with playing as a dwarf.
