### ISSUE TITLE
[EN][Talent][Death Knight] Blood of the North

### ISSUE THREAD

**Issue by raduriel** [Atlantiss/BugTracker#3998]
Blood of the North  could cause Death Runes to incorrectly revert back into Blood Runes when you enter to a donjon (personal experience),raids,bgs,arenas(guild and friends's experiences)
Hope you hotfix it 
                                                                                                           My regards 
                                                                                                                               Raduriel

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/3998
read rules

**Comment by Aydien** [comment]
Still bugged
