### ISSUE TITLE
[PL][Core][Pet] brak Assist stance

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#40]
http://www.wowwiki.com/Patch_4.2.0    http://wowpedia.org/Assist
The Aggressive pet stance has been removed and replaced with the Assist stance. This stance will cause the player's pet to attack the player's target. The pet will not change targets unless the master attacks a new target for a few seconds.

U nas na ptr jeszcze jest jeszcze stary u peta (przynajmniej u ghula) Aggressive stance
ss z ptr: http://imgur.com/8U0pllk

**Comment by Wolffenstein** [comment]
Fixed in rev 4318.
