### ISSUE TITLE
[EN][Quest] The Shaper's Terrace

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#400]
http://www.wowhead.com/quest=24694

Okay, so there's number of issues here, and I'll try to be clear, but this may get messy.

So, first of all, there's no dialogue with **Un'goro Examinant**, there's just an empty window when you interact with it, and that's it. That's as all there is to the bug of this quest, but there are other issues.

Namely, I shouldn't have this quest anyway, because I didn't complete **The Northern Pylon** (http://www.wowhead.com/quest=24722), nor the **The Western Pylon** (http://www.wowhead.com/quest=24723), but I DID complete **The Eastern Pylon** (http://www.wowhead.com/quest=24721).

All three of these quests require you to complete some of the normal quests in the area in order to unlock them at the designated NPCs. 

Strangely though, I didn't get **The Northern Pylon**, even though I actually DID complete all the requirements for it, I'll quote them from the wowhead comments, because they're not displayed on the side:

This quest is obtained on turning in **The Apes of Un'Goro.**

**The Apes of Un'Goro** needs the following to be turned in

**Gormashh the Glutinous**
which needs **Super Sticky**
**Hard to Harvest**
**Marshal's Refuse**

I did finish all of those, but it didn't unlock  **The Northern Pylon** for me at **Gremix** (http://www.wowhead.com/npc=38275)

For **The Western Pylon**, you can see the requirements for it on the side as a quest chain, here http://www.wowhead.com/quest=24723

I did complete all of the requirements for **The Western Pylon**, as well, but it also didn't unlock the quest for me at **Spark Nilminer** (http://www.wowhead.com/npc=9272)

**The Eastern Pylon** works.

So what needs to be done? Here:

- Make sure that **The Northern Pylon** and **The Western Pylon** quests are unlocked once you complete their requirements for unlocking, and make sure that they can be completed then.

- Make sure you can't get **The Shaper's Terrace**, UNTIL you've completed **The Western Pylon**, **The Eastern Pylon**, and **The Northern Pylon**.

- Fix the interaction with **Un'goro Examinant**, so that you can teleport to the shaper's terrace and complete the quest.

**Comment by BAndysc** [comment]
Fixed

**Comment by szentigrad3** [comment]
i just tried to click i'm ready to go to The Shaper's Terrence and nothing happens
