### ISSUE TITLE
[EN] [Proffesion] Skinning Upgrade dosen't work

### ISSUE THREAD

**Issue by Freestylezhobo** [Atlantiss/BugTracker#4000]
when i upgrade from 1st Skinning to Journeyman skinning, i can buy it but when i kill a target and then tries to skin it, it stops it is just standing there and doing the animation, 
Please fix it, i love skinning i need for my leatherworking.

-Freestylezhobo

**Comment by Quellz** [comment]
Follow the guidelines.
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Freestylezhobo** [comment]
sorry fixed it now,

**Comment by Quellz** [comment]
I think your problem might be that you NEED to relog everytime you get an upgrade. Be it riding upgrades or profession upgrades.

**Comment by Freestylezhobo** [comment]
ah thank you for the help i try

**Comment by Freestylezhobo** [comment]
THANK YOU SO MUCH
