### ISSUE TITLE
[PL][Item] Formula: Enchant Weapon - Executioner

### ISSUE THREAD

**Issue by kiepski** [Atlantiss/BugTracker#4006]
Brakuje tego enchantu: http://www.wowhead.com/item=78348/formula-enchant-weapon-executioner
do kupienia u tego Vendora:http://www.wowhead.com/npc=19536/dealer-jadyan

w tym linku z wowhead enchant daje tylko 60 critical strike w dodaku z wod
na cataclysm powinien dawac 120 critical strike.  
http://www.wowdb.com/items/78348-formula-enchant-weapon-executioner

**Comment by Illusionist87** [comment]
bumping. formula is still missing from the vendor

**Comment by sigmundfreud2016** [comment]
Still missing
![wowscrnshot_102515_111334](https://cloud.githubusercontent.com/assets/12395407/10715116/efcc33fe-7b09-11e5-860a-b48123301085.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7007-4006-item-formula-enchant-weapon-executione/
