### ISSUE TITLE
[EN][Connection] Stuck in connected stage

### ISSUE THREAD

**Issue by XxaklxX** [Atlantiss/BugTracker#4008]
Yesterday I played normally. Today I tried to log in but gets stuck with this connected message. My internet connection is ok. What could it be?

![wowscrnshot_072915_151651](https://cloud.githubusercontent.com/assets/13158834/8967726/bf00672e-3606-11e5-80fe-b685f4cff3a4.jpg)

**Comment by Kejmil** [comment]
http://community.atlantiss.eu/ last message in shoutbox atm
