### ISSUE TITLE
[EN][Quest][Westfall] Captain Sanders' Hidden Treasure

### ISSUE THREAD

**Issue by tdotzlod** [Atlantiss/BugTracker#4010]
Horde players can't start mentioned quest from Captain Sanders' Treasure Map (http://www.wowhead.com/item=1357/captain-sanders-treasure-map)
At this moment it say "that quest is not available to your race" when one try to pick it up.
Despite quest marked as "alliance" it's actually available to and completable by both factions.

http://www.wowhead.com/quest=26353/captain-sanders-hidden-treasure#comments:id=1207102:reply=245879

**Comment by Thefakemccoy** [comment]
can confirm just tested on retail on my orc i was able to pick the quest item up and start the quest.
