### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] Stormpike Rendezvous (generally, Kingslayer Orkus's quests

### ISSUE THREAD

**Issue by Quellz** [Atlantiss/BugTracker#4011]
![wowscrnshot_072915_214144](https://cloud.githubusercontent.com/assets/13531939/8969356/bee89ec6-363a-11e5-9ba7-71285d6859da.jpg)

Righty. I spoke with Yggr and he placed a temporary NPC in the area, as seen in the screenshot above. This allowed me to complete two of Orkus's quests, but on Stormpike Rendezvous, the dialogue doesn't trigger, not allowing you to complete the quest.

**Comment by BAndysc** [comment]
Finally fixed ^.^
