### ISSUE TITLE
[EN][Dungeon][Scarlet Monastery Graveyard] Mobs aren't spawning.

### ISSUE THREAD

**Issue by Quellz** [Atlantiss/BugTracker#4012]
As I walked in, everything was fine up until my group headed outside after killing Interrogator Vishas. No mobs spawned in the courtyard, nor in the crypt, only the bosses and mini-bosses. Rather irregular.

![wowscrnshot_072915_215608](https://cloud.githubusercontent.com/assets/13531939/8969761/61fcbfb4-363d-11e5-9f90-2b3bced7df5b.jpg)
![wowscrnshot_072915_215625](https://cloud.githubusercontent.com/assets/13531939/8969770/6bf164fc-363d-11e5-8196-e5852e95609b.jpg)
![wowscrnshot_072915_215810](https://cloud.githubusercontent.com/assets/13531939/8969775/7338c34a-363d-11e5-9e25-76b261006918.jpg)

**Comment by EnderBlazer** [comment]
when using recount you may wanna switch to dps instead of damage done
about the dungeon, not sure what hapenned, never hapenned to me before

**Comment by Quellz** [comment]
lol I'll take that recount advice into consideration.
I'm gonna try to re-run it and see if the same happens. I don't know if it was only that time.

**Comment by Quellz** [comment]
Ran through this again, mobs spawned properly. Turns out it was a one-time thing.
![wowscrnshot_073015_153746](https://cloud.githubusercontent.com/assets/13531939/8985837/1401bc1c-36d1-11e5-8e0b-d6c4637baa8a.jpg)
