### ISSUE TITLE
[EN][NPC] Grom-Grom

### ISSUE THREAD

**Issue by Champions2012** [Atlantiss/BugTracker#4014]
Well, this npc should be dead but he is not. He is alive and when u get close to him you get in combat and you can't get out of it. He doesn't attack you nor you can attack him.

http://wow.gamepedia.com/Grom-Grom

![wowscrnshot_072915_153048](https://cloud.githubusercontent.com/assets/13512234/8971753/b220c240-3653-11e5-83b6-eee9f4e5dc84.jpg)
![wowscrnshot_073015_003012](https://cloud.githubusercontent.com/assets/13512234/8971752/b21c9fda-3653-11e5-92e1-9e15f5876b1e.jpg)

And here's how it should look like:
https://www.youtube.com/watch?v=qQvyt4cTaYw

You can see the body in the upper left at 00:03.

**Comment by Champions2012** [comment]
Well, this npc should be dead but he is not. He is alive and when u get close to him you get in combat and you can't get out of it. He doesn't attack you nor you can attack him.

http://wow.gamepedia.com/Grom-Grom

![wowscrnshot_072915_153048](https://cloud.githubusercontent.com/assets/13512234/8971753/b220c240-3653-11e5-83b6-eee9f4e5dc84.jpg)
![wowscrnshot_073015_003012](https://cloud.githubusercontent.com/assets/13512234/8971752/b21c9fda-3653-11e5-92e1-9e15f5876b1e.jpg)

And here's how it should look like:

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6862-4014-npc-grom-grom/
