### ISSUE TITLE
[EN][Spell][Outland] Blessing of Auchindoun

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#4019]
This buff remain permanent after an player got it, it remain in all maps, all time.
Link: http://www.wowhead.com/spell=33377/blessing-of-auchindoun
This is quest have location of all towers.
Link: http://www.wowhead.com/quest=11505/spirits-of-auchindoun
This buff should work only in Terokkar Forest.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/3133

**Comment by phifedawg** [comment]
Is there any way to get rid of the buff? Right clicking it won't help
