### ISSUE TITLE
Craw MacGraw head enchant

### ISSUE THREAD

**Issue by Tilter** [Atlantiss/BugTracker#4021]
Hello there, I recently got a new helm and I wanted to get an enchant for it and since I need strength ench I went to Craw MacGraw in Twilight Highlands to buy it and I knew there used to be one for gold ONLY and no Rep required since you can't get rep there yet. So I sent a ticket and got a response that there IS. So we talked a bit and came to a conclusion that I can't see it while GM's can and I've been told to upload my screen shot here so it can be reviewed.

http://i.imgur.com/SalKVJr.jpg - This is the link to the screen shot.

Thanks in advance.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

Besides. Alliance being the only faction with access to this enchant is bullshit and it should be corrected

**Comment by Wolffenstein** [comment]
It was available for far too long.
