### ISSUE TITLE
[EN] [Quest] [Uldum] Do the World a Favor

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#4022]
http://www.wowhead.com/quest=27187/do-the-world-a-favor

"Kill 12 Mangy Hyenas. "

After I kill the 12 hyenas I see the question mark for auto-complete but when I click it I get error "this objective is not in the database" so I can not hand it in and I do not get credit.

**Comment by Wolffenstein** [comment]
Have you tried turning off all your addons and clearing cache?

**Comment by eryczek1615** [comment]
When you have Carbonite you can't complete this quest

**Comment by lourrific** [comment]
Apparently there is an issue with Carbonite and some auto complete quests because I was previously able to complete many of these type of quests in other areas using the Carbonite interface. To remedy this I just disable carbonite and complete the quest then turn it back on.
