### ISSUE TITLE
[EN] [Quest] [Stonetalon Mountains] Barrier to Entry

### ISSUE THREAD

**Issue by ebm0991** [Atlantiss/BugTracker#4023]
http://www.wowhead.com/quest=25999/barrier-to-entry

https://www.youtube.com/watch?v=ziAfRn0ANQU&feature=youtu.be

You can´t select the mines with the item "Land Mine Wrench", also if you try it to click it without the item nothing happens

**Comment by Bildo** [comment]
duplicate
