### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] Studies in Lethality

### ISSUE THREAD

**Issue by bogdanplete** [Atlantiss/BugTracker#4024]
![wowscrnshot_073015_231652](https://cloud.githubusercontent.com/assets/13574290/8993980/2881e1cc-3711-11e5-8c61-b6ec1651cc2d.jpg)
The Blight Slimes are not spawned and i need to collect something from them!

**Comment by Quellz** [comment]
They do spawn. Just have a irregular respawn time.

**Comment by eryczek1615** [comment]
NPC - http://www.wowhead.com/npc=48136/blight-slime
Quest - http://www.wowhead.com/quest=28324/studies-in-lethality
