### ISSUE TITLE
[EN][Quest][Azuremyst Isle] Botanist Taerix

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#4026]
(http://www.wowhead.com/quest=9371/botanist-taerix#comments
According to wowhead comments, the quest Botanist Taerix must be available only after you turn in the quest Urgent Delivery! (http://www.wowhead.com/quest=9409/urgent-delivery). You can take the quest Botanist Taerix regardless of prerequisite.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/3706
