### ISSUE TITLE
[EN][Quest][Azuremyst Isle] Vindicator Aldar

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#4027]
http://www.wowhead.com/quest=10304/vindicator-aldar
According to wowhead comments, this quest should only be available only after completing http://www.wowhead.com/quest=9294/healing-the-lake.
Currently the quest Vindicator Aldar can be taken without completing the prerequisite.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/3706
