### ISSUE TITLE
[EN][ITEM] Stormwake, The Tempest Reach Of The Wildfire

### ISSUE THREAD

**Issue by idguakeren** [Atlantiss/BugTracker#4029]
So i won this item from a raid, it is a spellpower sword dropped from Al'akir that has random stats. it has a secondary stat enhancement of +97 hit and +97 Crit chance. After the last server reset i logged on and saw that it lost the +97 Crit chance enhancement. so i wrote a ticket to the GM. and they said to delete my cache folder and if the problem persist write it in the bugtracker. so here i am now. i do not have the image of the item before the stat loss because i wasnt expecting for this to happen but  here is an image of the item now, and for a level 359 epic it is very unusual to not have 2 secondary stat enhancement. 
![bug](https://cloud.githubusercontent.com/assets/13581125/8999559/4a2ad748-3766-11e5-91db-43e7fa1265de.jpg)
For comparison this is also an item that i got from Al'akir in the same raid, but has all the secondary stat with no loss after reset
![bug 2](https://cloud.githubusercontent.com/assets/13581125/8999652/b142a6ee-3767-11e5-97fa-d8c605cdcdb5.jpg)
I hope you will fix this soon, Best regards~

**Comment by turnkeyfriend** [comment]
http://www.wowhead.com/item=68127

**Comment by Aviannaqt** [comment]
#3078
