### ISSUE TITLE
[EN][Quest] I'm Not Supposed to tell you This

### ISSUE THREAD

**Issue by Gerdat16** [Atlantiss/BugTracker#4030]
http://www.wowhead.com/quest=27392/im-not-supposed-to-tell-you-this

Mob doesn't spawn in correct location. 

http://www.wowhead.com/npc=45450/the-lone-hunter

**Comment by turnkeyfriend** [comment]
Mob does in fact spawn. Just not quite in the correct location. It's at the bottom of the hill and kind of nearby. Takes a little looking for it.

**Comment by iliarakov** [comment]
mob is not missing he in more left in location

**Comment by Gerdat16** [comment]
Got it. Editing now.
