### ISSUE TITLE
Cannot use forum

### ISSUE THREAD

**Issue by ylluminate** [Atlantiss/BugTracker#4031]
I and a few others on our network are not able to use the forum.  Our account is active and works fine otherwise, but the forum provides the following message:
![Screenshot](http://cl.ly/image/3X3T2c233o2M/skitched-20150731-135919.jpg)

**Comment by Varchord** [comment]
You were propably banned. But i think BT is not a place for this kind of issues

**Comment by ylluminate** [comment]
Hmm, odd. All of our family's accounts are acting the same way... Sounds like an IP blocking issue, but no one has replied to support emails.

**Comment by ylluminate** [comment]
@armano2 @Varchord here is a capture of the odd throbber at the top as well:
![throbber](http://cl.ly/image/2v0q1V1P122Z/Image%202015-07-31%20at%204.21.45%20PM.png)
