### ISSUE TITLE
[PL] Rated Battleground

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#4032]
Nie działa, nie łączy, przypadek sprawdzony Horda vs Ally.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/2315
https://github.com/Atlantiss/BugTracker/issues/3421

**Comment by deadlycalm** [comment]
bump

**Comment by deadlycalm** [comment]
bump, season comes to an end and highest rating is 645
