### ISSUE TITLE
[EN][Npc]Twilight Highlands Rare Boss spawn

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#4036]
i have been searching for him in twilight Highlands and he is not here his name is ( Julak-Doom <The Eye of Zor> ) i have the proof that he is suppose to be in the Current cata patch we are in he is the link and video for him

http://www.wowhead.com/npc=50089/julak-doom

https://www.youtube.com/watch?v=x7jSArkZV5Q

**Comment by meowmewo** [comment]
Twilight Highlands is still closed. It will open soon ( 1 month probebly)

**Comment by Bud1980** [comment]
that maybe but with the ability to see all mobs there not shouldnt he be that aswell even for testing purpose?

**Comment by Wolffenstein** [comment]
nope.
