### ISSUE TITLE
[EN][Quest][Deepholm] Wrath of the Fungalmancer

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#4038]
The quest Wrath of the Fungalmancer doesn't work correctly (http://www.wowhead.com/quest=26583/wrath-of-the-fungalmancer).

The NPC Earthmender Norsala cannot be found (http://www.wowhead.com/npc=43503/earthmender-norsala), as it has a much longer spawn time than it should.

Edited to take into account what maciekf3 wrote.

**Comment by maciekf3** [comment]
It does work but she has very long spawn time

**Comment by ahtebe** [comment]
Still not blizzlike, still a bug.

**Comment by Bildo** [comment]
fixed

**Comment by Simgiov** [comment]
Not fixed.

**Comment by hawcik** [comment]
Still bugged
