### ISSUE TITLE
i look like meat

### ISSUE THREAD

**Issue by novalyfe** [Atlantiss/BugTracker#4039]
well, during an instance that i dont know the name of, i died and turned into a bunch of meat and bones...

http://gyazo.com/7684cdbe74ef4c198ebb2f601b10028f

http://gyazo.com/4a473426596f61aaf12b8889236516bf

![wowscrnshot_080115_181523](https://cloud.githubusercontent.com/assets/13603027/9022849/2fb848de-3886-11e5-84c9-0ee5d71248a1.jpg)
![wowscrnshot_080115_181518](https://cloud.githubusercontent.com/assets/13603027/9022850/2fba8522-3886-11e5-831d-3a098755206d.jpg)

I would love to get this fixed as it was fun at start but it's just annoying now :D
![Uploading 7684cdbe74ef4c198ebb2f601b10028f.jpg…]()

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the instance that caused this bug provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by novalyfe** [comment]
THats because i have no idea what the name of the instance is. ill try and look it up...

**Comment by Bildo** [comment]
write a ticket
