### ISSUE TITLE
[EN][NPC][Shimmering Expanse] Provisioner Arok 

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#4040]
He is Earthen Ring Quarter Master. I can not go to this NPC or he can not be reached. 

Apparently I have done enough questing in Deepholm and with other factions to accumulate honorable status with the Earthen Ring. I would like to get the Stone-Wrapped Greaves http://www.wowhead.com/item=62355/stone-wrapped-greaves for tanking but I can't find a way to get to him to purchase them.

**Comment by Drutmaster** [comment]
He is standing next to Therazane Quartermaster. You don't need to look after him in Vashj'ir.
