### ISSUE TITLE
[PL][ENG][ITEM] Silverbound treasure chest

### ISSUE THREAD

**Issue by Corson** [Atlantiss/BugTracker#4042]
http://www.wowhead.com/object=207472/silverbound-treasure-chest

PL: skrzynka nie otwiera się (a przynajmniej nie ta, znaleziona w Stromgarde Keep)
ENG: the chest cannot be open (at least that, found in Stromgarde Keep)

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3753
