### ISSUE TITLE
[EN][Crash][Outlands] Fatal Crashes in Outland

### ISSUE THREAD

**Issue by RazeSmile** [Atlantiss/BugTracker#4049]
Since yesterday I've been having problems in Outland, the first set of crashes was when entering the Dark Portal; the game would crash and this message would appear:

![crash](https://cloud.githubusercontent.com/assets/13557598/9026013/ca47adac-391e-11e5-83f2-5040263bb35d.png)

I re-downloaded the Atlantiss 4.3.4 torrent from the website and this fixed the problem. Then, earlier today, I got another set of crashes when entering Blade's Edge Mountains with this message: 
 
![crash 2](https://cloud.githubusercontent.com/assets/13557598/9026018/3c028c82-391f-11e5-9229-1534ef353933.png)

I tried using both clients, the old client I downloaded a week ago and the one I downloaded yesterday, interestingly; the old client didn't crash upon entering the Dark Portal anymore, but it kept crashing in Blade's Edge Mountains, just like the new client. 

Any help would be appreciated, for now, i'll have to download the torrent AGAIN. Hopefully I won't have any more problems. Thank you in advance :)

**Comment by StoneyMahoney420** [comment]
The first error suggests the art.mpq file was damaged. The second error suggests the expansion1.mpq file is damaged. Hopefully that'll help you narrow down your re-downloading to the specific broken files.

**Comment by Bildo** [comment]
are you using our exe file ?

**Comment by RazeSmile** [comment]
The exe file from your "How to connect" page? I thought that was included in the torrent download, perhaps I misread the instructions.

I'll use that from now on, downloaded a fresh torrent for the third time. If I run into any more problems, I'll be sure to report them :)

**Comment by aje** [comment]
you didn't reported new errors so I assume the issue is now corrected

and was probably because of corrupt files in your client
