### ISSUE TITLE
[EN][Quest][Durotar] An Ancient Enemy

### ISSUE THREAD

**Issue by Dustur** [Atlantiss/BugTracker#405]
Last troll starting quest doesn't work. You can actually kill The Sea Witch but there is no way to achieve "Speak with vol'jin" part of the quest.

http://www.wowhead.com/quest=24814/an-ancient-enemy

**Comment by stormyboy** [comment]
now you can't even kill the sea witch. Vol'jin yells what he has to yell and that's it. From there it won't work

**Comment by TranceAccount** [comment]
I've done this recently and it worked fine to me.
Open another issue if you happen to find another bug on this.
