### ISSUE TITLE
[EN][NPC][Shadowfang Keep] Packleader Ivar Bloodfang

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#4050]
http://www.wowhead.com/npc=47006/packleader-ivar-bloodfang

I've encountered a problem after killing Lord Walden. Packleader Ivar Bloodfang should come up and unlock the gate and let you go further, to the room where you'll kill Lord Godfrey. This does not happen currently, and the gate stays closed, Bloodfang doesn't show up at all thus impending progress further. 
The gate can be bypassed by talking to the NPC at the start of the dungeon and teleporting to the laboratory, which bring you on the upper floor past the gate but it doesn't solve the problem. Reason being, once you reach the door leading to the room Lord Godfrey is in, Packleader Ivar Bloodfang is again supposed to unlock it which he fails to do. Presumably it's related to him not coming to unlock the gate in the first place.

**Comment by Otisjay** [comment]
I can conform this is a issue, Just ran Shadowfang keep on Aug. 8th, & the bug was there.
