### ISSUE TITLE
[EN][Quest][Nagrand] HELP! (Corki rescue quest chain)

### ISSUE THREAD

**Issue by StoneyMahoney420** [Atlantiss/BugTracker#4052]
This is the first quest in the Corki rescue chain, but it starts from the "wrong" Corki - it should start from the Burning Blade Ruins Corki, instead you have to go to the Warmaul Hill Corki to start the quest. The rest of the quest works fine - the correct NPCs drop the key and opening the cage Corki is in is Burning Blade Ruins completes the quest requirements as they should.

**Comment by Xaedric** [comment]
#493
