### ISSUE TITLE
[EN][Warlock][Spell] Affliction Talent doesn't works

### ISSUE THREAD

**Issue by Fugaza** [Atlantiss/BugTracker#4054]
I was testing the afflic spec in my warlock, but i see 2 problems...

1) Bad luck doesn't put the debuff in the adds near of my target.
![nueva imagen](https://cloud.githubusercontent.com/assets/13612764/9027104/c92bc59c-3915-11e5-9ac1-5118cf1d70d1.JPG)

2) Shadow embrace doesn't work, you hit a shadowbolt and put 1 charge of the debuff, but hit one shadowbolt more or one haunt, and the debuff disappears and don't acumulate.

3) Seed of corruption doesnt do the dot damage, you hit the spell and finish, doenst work...

**Comment by ahtebe** [comment]
Are you sure? At least 1 month ago all of that worked as it should.

**Comment by fafal** [comment]
2) Shadow embrace doesn't work, you hit a shadowbolt and put 1 charge of the debuff, but hit one shadowbolt more or one haunt, and the debuff disappears and don't acumulate.

Talent Works, check once again
