### ISSUE TITLE
[EN][TALENT][SHAMAN] TALENT LAVA SURGE

### ISSUE THREAD

**Issue by camadonna** [Atlantiss/BugTracker#4055]
http://cata.openwow.com/spell=77755
Lava Suge is not working properly. sometimes it pops up when u re casting lava and doesnt reset cd.
As i played in offy quite a lot i know that if lava surge procs u have surely a cd reset no matter of what u do so maybe they forced it to be always after casting lava and not during it.
https://github.com/Atlantiss/BugTracker/issues/1424 is still not working and it s a pain in the ass

**Comment by Crusaderz** [comment]
Can we fix it already? Very important talent for pvp and pve.

**Comment by fafal** [comment]
http://community.atlantiss.eu/index.php?/topic/6516-current-state-of-elemental-shaman/?p=23361

**Comment by aneq** [comment]
@Aviannaqt 
do zamknięcia
