### ISSUE TITLE
[EN][Spell][Warrior] Colossus Smash

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#4056]
http://cata.openwow.com/spell=86346
REDUCING 100% INSTEAD OF 50% IN PVP

**Comment by latarnia93** [comment]
True. Fix pls
Reducing 100% in PvP*

**Comment by Jenovas** [comment]
Are you sure it reduces 100% in PvP?

In the core I see this, so it should work
// In PvP reduce armor by 50%
if (target == TYPEID_PLAYER)
    amount = 50;

Please make sure that for 100% it bypasses all armor.

**Comment by armano2** [comment]
`CAPS LOCK OFF` pls

**Comment by debtheone** [comment]
yes im sure

**Comment by Asavel** [comment]
http://wow.gamepedia.com/Colossus_Smash

 Patch 4.1.0 (2011-04-26): Now ignores 50% of a hostile player's armor (PvP), but continues to ignore 100% of a non-player character's armor (PvE).

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
