### ISSUE TITLE
[EN][Talent][Priest] Shadow Orbs

### ISSUE THREAD

**Issue by ezzira** [Atlantiss/BugTracker#4061]
Hi guys, i just discovered a small bug with shadow orbs. so i have discipline as first talent specialisation and shadow as second. the bug is that when I'm in discipline spec i still have a chance to generate shadow orbs with shadow word: pain. This shouldn't be the case, you should only get shadow orbs if you are in shadow spec.

**Comment by Jenovas** [comment]
Fixed in rev 4570 - fix a bug that allowed any class to have two different masteries active
It is probably this bug. Closing.
