### ISSUE TITLE
Camouflage brakes on Rogue Distract Spell

### ISSUE THREAD

**Issue by 4free100** [Atlantiss/BugTracker#4063]
Never seen this bug but apparently here on Atlantiss Camouflage will brake by Rogue's Distract spell. Have played on manye Cata P-Servers like Arena Tournament and also Retail Cata and it was never like that. Please fix this, it's annoying.

brgds 4free100

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the spell provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by 4free100** [comment]
Haha well thats not the problem. You could 've done that aswell. 
Here is the link the Distract.
http://cata.openwow.com/spell=1725
Is just says on the last line. 
''Does not brake stealth.''
All said.

**Comment by Pallitax** [comment]
Your title still doesn't follow the guidelines.
