### ISSUE TITLE
[EN][Trinket][General] Trinket vs. macro

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4064]
I want to use my (pvp)Damage Trinket in a macro with Berserk and Tiger's Fury.But the macro requires to be pressed twice, which is wrong.

Berserk -> requires a gcd in order to be used(works fine)
Tiger's Fury -> can be used during global cooldown(works fine)
Dmg trinket -> can be used during global cooldown(works fine)

The problem is when you put Dmg Trinket in a macro with other spell, like Berserk, or/and with Tiger's Fury. Your trinket is not popped,and requires another hit of the button.
They should both be used in the same time at one button, becouse trinket is instant usable just like Tiger's fury(can be used during GCD)

**Comment by mitim1** [comment]
http://forum.warmane.com/showthread.php?248683-4-3-4-Feral-druid-PvP-Guide

Burst macro
/cast Tiger's Fury
/cast Berserk
/use 13

That macro doesnt work because you cant cast tiger's fury and berserk at the same time.

**Comment by Jenovas** [comment]
Tigers Fury can be used with Berserk so this macro should work.

**Comment by mitim1** [comment]
"#showtooltip Berserk
/cast Tiger's Fury
/cast Berserk
/use 13" 100% working
