### ISSUE TITLE
[EN][NPC][Uldum] Akma'hat drops no gear

### ISSUE THREAD

**Issue by agardosh** [Atlantiss/BugTracker#4066]
Only drops gold

**Comment by Bildo** [comment]
wowhead link

**Comment by aje** [comment]
http://www.wowhead.com/npc=50063/akmahat

**Comment by Aival94** [comment]
It is probably a percent issue as i have killed many times this world boss and always drop one epic item.(I think world bosses drop 2 epic items and 1 jc recipe.)

**Comment by LordKnightCecilo** [comment]
Same here. Killed today. Should always drop a ilvl 359 item. Only dropped two green JCing recipes.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12043-4066-akmahat-loot-tables/
