### ISSUE TITLE
[EN][Hunter][Pets] Hunters' pet kills - unlootable

### ISSUE THREAD

**Issue by Lyet** [Atlantiss/BugTracker#4067]
If hunters' pet kills a mob all by itself, player can't loot/skin the corpse.

**Comment by quantil** [comment]
its normal,

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by mitim1** [comment]
This is not a bug
