### ISSUE TITLE
Deephelm Daily Quests

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#4068]
Quest ( The Restless Brood ) is unable to complete.
Quest ( Underground Economy ) unable to complete becuase you are unable to get the quest items

All Daily  quest do not give Reputation

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead links for the quests provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Bud1980** [comment]
how long you been playing WoW?
