### ISSUE TITLE
[EN][Quest] False Idols (Minor)

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#407]
In the quest **False Idols** (http://www.wowhead.com/quest=25705), you can keep attacking just one **Azsh'ir Idol** (http://www.wowhead.com/object=203289) to get all the 8 counts for the quest, when you should actually be destroying 8 different **Azsh'ir Idols**.

Problem is that **Azsh'ir Idol** is not removed when you destroy it, so you can keep using just one to finish the quest.

**Comment by Bildo** [comment]
rev. 4353 by Quban

**Comment by bgb** [comment]
I just tried to do this quest and seems its bugged but in a different way now... When I attack idol it dissapear but I dont get quest credit for it... Destroyed many of the idols but its still 0/8 in quest log, therefore quest is uncompletable now...

**Comment by Austerity** [comment]
Can't get credit for activating idols. This is a quest chain it breaks the chain.

**Comment by Austerity** [comment]
As bgb says, this quest is now impossible to complete.
