### ISSUE TITLE
[EN][Rogue][Spell] Distract

### ISSUE THREAD

**Issue by 4free100** [Atlantiss/BugTracker#4070]
Never seen this bug but apparently here on Atlantiss, Camouflage will brake by Rogue's Distract spell. Have played on manye Cata P-Servers like Arena Tournament and also Retail Cata and it was never like that. Please fix this, it's annoying.

http://cata.openwow.com/spell=1725

brgds 4free100

**Comment by Genomnomnomnom** [comment]
Confirmed. Also taking Mages out of Invisibility.

**Comment by 4free100** [comment]
Haven't played a Mage on this server yet but it would makes sense that it'll brake aswell.
Since this Genomnomnomnom guy is playing a Rogue here, he should know. 
People say he is the highest xp'd Rogue here, which makes him even more trustful.

brgds 4free100

**Comment by Jenovas** [comment]
Rev [4558]

**Comment by 4free100** [comment]
rev. 4558 Author: Wolffenstein :: 2015-08-12 21:06

Death Knight:

    Reduced ghoul's energy regeneration rate (thanks Jenova for valuable info)

Rogue:

    Distract will no longer work on targets invisible to the caster
    Smoke Bomb will not be reapplied on the caster if he's outside the range of it
    Smoke Bomb should now correctly work on melee spells (e.g. Judgement, Hand of Reckoning)
    Targets inside an unfriendly Smoke Bomb should no longer be able to cast spells on targets outside of the Smoke Bomb

Shaman:

    Spirit Link Totem can no longer target players inside of an unfriendly Smoke Bomb. The Totem itself should be immune to Smoke Bomb's effect.

It still takes me out of stealth.

**Comment by GtGraphics6** [comment]
Tried it out aswell, distract not fixed
