### ISSUE TITLE
[EN][TALENT][SHAMAN] TALENT earth grasp

### ISSUE THREAD

**Issue by camadonna** [Atlantiss/BugTracker#4072]
http://cata.openwow.com/spell=51485
http://cata.openwow.com/spell=2484
Talent Earth Grasp doesn t work properly: if a mob is inside AOE it will 100% rooted, if he s outside AOE and cames inside it it s only slowed, not rooted (should be rooted as he cames inside AOE and THEN slowed until he s inside it. To be checked for players in PVP

**Comment by zano354** [comment]
its only roots at cast, not every time it release/pulsing its debuff (which is 1 sec per pulse).
IDK if the earthbind totem earth grasp has its own aoe, but i think it has the same aoe like earthbind totem with or without talent totemic reach (2nd tier at enhancement talent).

**Comment by Jenovas** [comment]
The root should happen only on totem cast.

**Comment by camadonna** [comment]
no the root should appear when mobs or players came in the aoe zone




----Messaggio originale----

Da: notifications@github.com

Data: 04/08/2015 23.42

A: "Atlantiss/BugTracker"<BugTracker@noreply.github.com>

Cc: "camadonna"<varrani@libero.it>

Ogg: Re: [BugTracker] [EN][TALENT][SHAMAN] TALENT earth grasp (#4072)




The root should happen only on totem cast.

**Comment by camadonna** [comment]
no it roots at first pulse and slows after the first pulse has rooted until u get out of aoe. totemic reach only makes bigger aoe. I believe it has the same aoe of other totemsi saw u closed this and #4074. i m not going to lose my time again with that. instead of closing  them try to fix or link me a page where u state they re working properly. it s too easy to close issues like that so i say it again i will not post more bugsregards




----Messaggio originale----

Da: notifications@github.com

Data: 04/08/2015 21.11

A: "Atlantiss/BugTracker"<BugTracker@noreply.github.com>

Cc: "camadonna"<varrani@libero.it>

Ogg: Re: [BugTracker] [EN][TALENT][SHAMAN] TALENT earth grasp (#4072)




its only roots at cast, not every time it release/pulsing its debuff (which is 1 sec per pulse).

IDK if the earthbind totem earth grasp has its own aoe, but i think it has the same aoe like earthbind totem with or without talent totemic reach (2nd tier at enhancement talent).
