### ISSUE TITLE
[EN][SPELL][SHAMAN] Fire Nova

### ISSUE THREAD

**Issue by camadonna** [Atlantiss/BugTracker#4074]
http://cata.openwow.com/item=45778
It doesnt work. when activated it asks for a target. It shouldn't. It should AOE damage all around it when activated

**Comment by jsembatman** [comment]
This spell work fine.
Fire Nova: http://cata.openwow.com/spell=1535
You must have Flame Shock (http://cata.openwow.com/spell=8050) on target to use this spell
