### ISSUE TITLE
[EN][Talents][Rogue] Bandit's Guile

### ISSUE THREAD

**Issue by zano354** [Atlantiss/BugTracker#4076]
Bandit's guile buff (which is shallow insight, moderate insight) cannot advance/ continue to stronger buff (shallow to moderate, moderate to deep) if you using redirect into other target, and it makes the buff reset. Which its shouldn't works like that, since combat rogue have to use redirect to change the target without losing/resetting the buffs.

**Comment by Jenovas** [comment]
Duplicate - https://github.com/Atlantiss/BugTracker/issues/2147
