### ISSUE TITLE
[EN][Quest][Duskwood] The Yorgen Worgen Quest is Unavailable

### ISSUE THREAD

**Issue by coretbh** [Atlantiss/BugTracker#4077]
http://www.wowhead.com/quest=26717/the-yorgen-worgen

This quest is unavailable. I couldn't take it from Apprentice Fess. I was level 23. This makes other quests inaccessible as well like "Delivery to Master Harris" ( http://www.wowhead.com/quest=26719/delivery-to-master-harris ) and subsequently "A Curse We Cannot Lift" ( http://www.wowhead.com/quest=26720/a-curse-we-cannot-lift )

The quest should be available at level 22.

**Comment by coretbh** [comment]
Was able to get it now at level 24 after finishing "Part of the Pack"

**Comment by Flathe** [comment]
Impossible to get this quest level 24, i've done 1 quest of Apprentice Fess, and now i can't find the quest 'Part of the Pack'

Thanks

**Comment by Quban** [comment]
> Was able to get it now at level 24 after finishing "Part of the Pack"

>This quest takes place in Duskwood. Follow up on Quest: Part of the Pack.
http://worldofguidecraft.com/2011/02/15/quest-the-yorgen-worgen/

So this works as intended
