### ISSUE TITLE
[EN][Quest][Terokkar Forest] Digging Through Bones

### ISSUE THREAD

**Issue by Quellz** [Atlantiss/BugTracker#4080]
As seen in the screenshot below, after the digger arrives at the site, he runs the dialogue just fine, but after saying the line "I think there's something below the sands..", he freezes and doesn't do anything.

![wowscrnshot_080515_030120](https://cloud.githubusercontent.com/assets/13531939/9076758/64c839f4-3b1e-11e5-9486-ff1be494408a.jpg)

**Comment by armano2** [comment]
dplicate: #479
