### ISSUE TITLE
[EN][Instance-TBC][The Black Morass Heroic] Aeonus Loot 

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#4089]
After my 32th try I'm now certain that loot tables are not set correctly as I have only looted one epic item from Aeonus while - statistically looking I should have looted all of them.
The item I looted:
http://www.wowhead.com/item=29356/quantum-blade
Loot:
http://www.wowhead.com/npc=17881/aeonus#drops:mode=heroic

**Comment by Quban** [comment]
http://scr.hu/75h5/1m46u seems fine for me

**Comment by milzo** [comment]
They are gems, they drop every single time but epic gear doesn't.

http://www.wowhead.com/item=30531/breeches-of-the-occultist
http://www.wowhead.com/item=29247/girdle-of-the-deathdealer
http://www.wowhead.com/item=29253/girdle-of-valorous-deeds

**Comment by milzo** [comment]
Forty tries and still nothing, not a single epic gear.
