### ISSUE TITLE
[PL][Eastern Kingdom][Blasted Lands][Quest] The Altar of Storm

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#409]
Gdy używam Ciała Loramusa na Ołtarzu Burz to nic się nie dzieje z wyjątkiem pojawienia się Ciała na "Stole" - i nic... ;/

**Comment by Bildo** [comment]
fixed

**Comment by Cone182** [comment]
I cant turn in the quest

**Comment by jissabraham** [comment]
its not working
