### ISSUE TITLE
[EN][Quest][Dun Morogh] Missing in action

### ISSUE THREAD

**Issue by popcorns12** [Atlantiss/BugTracker#4098]
The quest is called Missing in action. I want's me to rescue 6 captured demolitionists that are located in cages. But most of them I can't rescue, I can talk to them but they only say greetings (my name) and I can't break the cage. Some cages are empty and when I break them nothing happens. I would be glad if you can fix this quest.

http://www.wowhead.com/quest=26284/missing-in-action

**Comment by ylluminarious** [comment]
+1

**Comment by Samineh** [comment]
:+1:

**Comment by apsiq** [comment]
If cage is empty it means someone rescued guy from it and u shouldnt destroy cage cuz you are bugging it, which means when gnom spawn cage will be still open...Cuz of stupid guy like you who bugged empty cages.

**Comment by Odynia493** [comment]
thats a bit harsh wouldn't you say..they are not stupid for trying to complete the quest and you have no right to call them stupid for it...this quest is still bugged. it all that is required to bug it out it to talk to the gnomes when the cage is already open then something needs to be done about it.

**Comment by apsiq** [comment]
Not sure if you are that stupid or just acting, you have to rescue gnom from cage if gnom is not there why would u even try to open cage?

**Comment by ffighter29** [comment]
Confirmed. Cages are always opened and NPC's are inside.

**Comment by Soldat20** [comment]
Is there anyway around it or does the gnome quest stop there?

**Comment by Samineh** [comment]
You can wait for a restart.

**Comment by ZGold92** [comment]
Any update on this quest?

**Comment by rasmodeus** [comment]
Bump. Quest still in uncompleteable.

**Comment by reapertg** [comment]
As stated above, the cages are empty with no way to actually complete this quest :(

**Comment by reapertg** [comment]
This also completely breaks the Gnome starting area with no way to circumnavigate. Only option is to grind xp mob farming until you get to the level where quests start in Kharanos

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
http://community.atlantiss.eu/index.php?/topic/13270-gameobject-makeshift-cages/

**Comment by Avalain** [comment]
As per 28th November - cages still don't respawn and you can't complete quest.

**Comment by Piklo** [comment]
[fix ](http://atlantiss.eu/changelog#rev5540)is not on server yet

**Comment by TranceAccount** [comment]
This fix got reverted due to a completely different fix not working in the update.
