### ISSUE TITLE
Druid of the claw quest

### ISSUE THREAD

**Issue by Fallenlegacy** [Atlantiss/BugTracker#4101]
So i am on the druid of the claw quest where in the mines you meet a NPC that tells you have to kill his body to complete the quest and he also gives you a voodoo charm. So i have that and i go the burrow door but the door won't open and i need the door to open so that i can finish the quest. 

(Sorry for any grammar mistakes)

**Comment by Aival94** [comment]
Reported(about one thousand times till now :P): https://github.com/Atlantiss/BugTracker/issues/643

**Comment by Pallitax** [comment]
Apart from being a duplicate...

• Title doesn't follow the guidelines
• No wowhead link for the quest provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by armano2** [comment]
duplicate: #4101
