### ISSUE TITLE
[PL][Quest][Storm Peaks] The Drakkensryd

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#4115]
http://www.wowhead.com/quest=12886/the-drakkensryd

Quest niewykonalny. Po użyciu harpuna na mobie, teleportuje nas na smoka i nic się nie dzieje, nic nie możemy zrobić. Nie można przez ten quest ukończyć chaina żeby dostać się do quartermastera Sons of Hodir.

**Comment by armano2** [comment]
duplicate: #3784
