### ISSUE TITLE
[ENG] Stonecore

### ISSUE THREAD

**Issue by treflowa** [Atlantiss/BugTracker#4118]
Last boss in Stonecore is bugged. She flew away from us. 
She is unkillable.

**Comment by Juau** [comment]
I can confirm Hight Priestess Azil is unkillable at the moment; as soon as it is engaged, the NPC flies away.

**Comment by MasterK15** [comment]
LINKS ...

**Comment by cuba1984** [comment]
She is killable. Just go to a place the third boss.

**Comment by Wulgarny** [comment]
Shes killable. She lands down on Ozuruk place (3rd boss), then on fly phase just wait there for adds.

**Comment by Aival94** [comment]
[High Priestess Azil](http://www.wowhead.com/npc=42333/high-priestess-azil) but it might be good idea to put it to the general stonecore report which already exist i think,

https://github.com/Atlantiss/BugTracker/issues/1155

Confirmed both the bug and the way to kill her.

**Comment by Bildo** [comment]
fixed by @Quban

**Comment by Aldergar** [comment]
I dunno why you said it's fixed...because it's not.)

**Comment by Quban** [comment]
coz server havent been compiled and restarted yet
