### ISSUE TITLE
[EN][NPC][Halls of Origination] Temple Guardian Anhuur

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#4123]
http://www.wowhead.com/npc=39425/temple-guardian-anhuur

After killing the boss a bridge should form to allow passage on the other side of the room. The bridge does appear but no one can pass it, we're blocked by an invisible wall right at the start of the bridge and we're unable to continue and finish the dungeon.

**Comment by Aival94** [comment]
It might be good to put it here: https://github.com/Atlantiss/BugTracker/issues/1153
