### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Windshear Mine Cleanup

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#4124]
http://www.wowhead.com/quest=25646/windshear-mine-cleanup
This quest should be available only after completing the prerequisites, http://www.wowhead.com/quest=25640/bombs-away-windshear-mine and http://www.wowhead.com/quest=25616/hellscreams-legacy .
How it is bugged: This quest is available without completing the prerequisites.

**Comment by Quban** [comment]
actually only http://www.wowhead.com/quest=25642/dont-look-them-in-the-eyes is preq for this

**Comment by Aival94** [comment]
I use an addon and check wowhead comments or wowpedia and only prequisite for this quest is completing [Bombs Away: Windshear Mine!](http://www.wowhead.com/quest=25640/bombs-away-windshear-mine)

**Comment by Quban** [comment]
Y, i've looked at wrong comment ;p

**Comment by Aldurion** [comment]
Well, the quest is still available without completing prerequisite.
