### ISSUE TITLE
[EN][Quest][The Cape Of Stranglethorn] Drive-By Piracy

### ISSUE THREAD

**Issue by Flathe** [Atlantiss/BugTracker#4126]
Bug on this quest : 
http://www.wowhead.com/quest=26649/drive-by-piracy

When using boat with canon to kill 75 Venture Co. Oil Worker, teleporting under the boat, unable to attack.
Obliged to kill them manually (quit the boat)

Thx

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/360
