### ISSUE TITLE
[EN][Auction House] No gold/gold loss

### ISSUE THREAD

**Issue by Chrupek7** [Atlantiss/BugTracker#4127]
I did not get the money from auction house. Even before it happened. Now it 3 stacks of embersilk cloth. Fortunately this does not happen with every auction.
![wowscrnshot_080615_140130](https://cloud.githubusercontent.com/assets/13677930/9111197/b61849e4-3c44-11e5-81a4-926eb6056503.jpg)
![wowscrnshot_080615_140439](https://cloud.githubusercontent.com/assets/13677930/9111198/b61b56ca-3c44-11e5-92ad-e5b606f2f8e5.jpg)
![wowscrnshot_080615_140824](https://cloud.githubusercontent.com/assets/13677930/9111199/b61fcebc-3c44-11e5-9d1c-0833362a32b6.jpg)

**Comment by Probullet25** [comment]
I think you need wait around 30 mins / 1 hour to get your money. AH send gold after you sell your mats/items in maxim 1 hour if you not bind.

**Comment by Chrupek7** [comment]
1 hour later :
![wowscrnshot_080615_152955](https://cloud.githubusercontent.com/assets/13677930/9112654/29c75f32-3c50-11e5-810c-aaefb42bc245.jpg)
![wowscrnshot_080615_152957](https://cloud.githubusercontent.com/assets/13677930/9112655/29cb89cc-3c50-11e5-8bab-22ae34959dfd.jpg)
![Uploading WoWScrnShot_080615_152959.jpg…]()

**Comment by Chrupek7** [comment]
1 hour later:
![wowscrnshot_080615_152955](https://cloud.githubusercontent.com/assets/13677930/9112674/51c174b4-3c50-11e5-9ef3-f7096b53a12d.jpg)
![wowscrnshot_080615_152957](https://cloud.githubusercontent.com/assets/13677930/9112675/51e398c8-3c50-11e5-8aff-0eeafe4d6f27.jpg)
![wowscrnshot_080615_152959](https://cloud.githubusercontent.com/assets/13677930/9112676/5206fc96-3c50-11e5-8c36-5591272015ee.jpg)

**Comment by Chrupek7** [comment]
Next One 
![wowscrnshot_080615_203251](https://cloud.githubusercontent.com/assets/13677930/9120049/72d17a44-3c7a-11e5-8929-92b1109bbe85.jpg)

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Thefakemccoy** [comment]
item/gold was lost basically same thing i reported a while back 
https://github.com/Atlantiss/BugTracker/issues/3339

**Comment by armano2** [comment]
duplicate: #3339
