### ISSUE TITLE
Swimming/flying bug as a Druid

### ISSUE THREAD

**Issue by Panekek** [Atlantiss/BugTracker#4129]
![wowscrnshot_080615_124723](https://cloud.githubusercontent.com/assets/13681780/9118289/48ef5f84-3c39-11e5-948a-a17db7515bc8.jpg)

![wowscrnshot_080515_170041](https://cloud.githubusercontent.com/assets/13681780/9118108/3616bc14-3c38-11e5-9c7b-d8d9dd5f5655.jpg)
 I found this by accident.  
Jumping while you're swimming and using flight form as you're falling closer to the water will make your character fly in any form (travel, owlkin, tree, etc.). It seems to treat you as if you were still swimming (the speed is the default swimming speed)

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Helbringer** [comment]
Im pretty sure this bug has already been reported with a video too
