### ISSUE TITLE
[EN][Reputation] Bloodsail Buccaneers

### ISSUE THREAD

**Issue by LordMoriarty** [Atlantiss/BugTracker#4130]
Booty Bay Bruisers stop giving reputation for Bloodsail Buccaneers after reaching honored. They should give reputation until exalted.
http://www.wowhead.com/faction=87/bloodsail-buccaneers#comments

**Comment by xolon** [comment]
Well you should not be able to go past honored with Bloodsail Buccaneers, ( Even the achievement "Insane in the membrane" requires Honored with them ) It was changed somewhere in pandaria that you can go past honored

**Comment by LordMoriarty** [comment]
Check the comments, it's cataclysm.(Also, you could get to exalted back in wotlk but that involved one specific NPC)

"[Hotfix confirmed, The Booty Bay bruisers now give reputation all the way up to exalted!]
[Hotfix? - unconfirmed CONFIRMED] June 2nd, 2011"
"By xabbu76 (154 – 2) on 2011/04/29 (Patch 4.1.0)		
I can confirm that since 4.1 Booty Bay Bruisers give reputation past Revered.
I just killed a Bruiser and was awarded +25 Bloodsail Rep (-125 Booty Bay, -63 other Goblin Factions)."
"By Iapeto (10,690 – 1·11·77) on 2011/05/13 (Patch 4.1.0)		
Also confirm that they (Booty Bay Bruisers) give reputation into Exalted, currently 30/1000."

They gave too much reputation though. More than 150 with guild perks.

**Comment by TranceAccount** [comment]
http://wow.gamepedia.com/Bloodsail_Buccaneers Patch Notes:
> Cataclysm Patch 4.0.3a (2010-11-23): Booty Bay Bruisers will now provide reputation up through Exalted.

**Comment by xShojirox** [comment]
By the way, this was fixed back in January of 2017, https://atlantiss.eu/changelog/21#rev5295

**Comment by TranceAccount** [comment]
Partly fixed by Bildo, and I will add my fix soon.

**Comment by TranceAccount** [comment]
Fixed in rev. 5849.
