### ISSUE TITLE
[EN][Warlock][Spell] Conflagrate + Serpent Sting(hunt obv)

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#4131]
http://www.wowhead.com/spell=17962/conflagrate

Spell Conflagrate with buffs +dmg like on Valiona / Nefarian encounters doin too much damage. Really toooo much. (For example Nefarian doin 3mln, its 2mln too much when stacked...). Im not sure that conflgrate after count immolate damage, stack second time sp/mastery itc.
Please check it.

BTW: Similar bugged spell is Serpent Sting. Is Also doin too much damage with those buffs. (500k trololoo)

**Comment by mitim1** [comment]
Bug zgłoszony + jest to problem z podwójnym dmg spelli w monecie kiedy jest jakie modyfikator dmg taken

#3500

**Comment by fafal** [comment]
To w takim razie jestem slepy i prosze o skasowanie tematu

**Comment by Kejmil** [comment]
oddalam to zgloszenie
