### ISSUE TITLE
[EN][Quest][Client Crash] Sealing the way.

### ISSUE THREAD

**Issue by Wishingstars** [Atlantiss/BugTracker#4135]
Using the item "Rockslide Reagent" on any of the Geomancers causes the client to crash. 

ERROR #132 (0x85100084) Fatal exception!

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the quest and the quest item provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Therenir** [comment]
You can complete this quest without crash, just target npc Earthen Geomance and then use Quest item.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6819-wow-error-by-pressing-escape-after-using-item/

**Comment by Aival94** [comment]
Seems the crash happen as well when you press esc after using item.

One more Minor bug is that the credits are visible.

**Comment by krecik88** [comment]
Fixed in 5377
