### ISSUE TITLE
[EN][Quest][Raid][WotLK] Head of Onyxia

### ISSUE THREAD

**Issue by LordMoriarty** [Atlantiss/BugTracker#4138]
The Head of Onyxia does not drop from Onyxia in Onxyia's Lair. It is a 100% drop. http://www.wowhead.com/item=49643/head-of-onyxia
http://www.wowhead.com/quest=24429/a-most-puzzling-circumstance

There is no buff or yell like there is for Nefarian.
It should unlock the quest to make the old Ony cloak
Her head should be on a spike in Orgrimmar, near Nefarian's head. 

This bag should also always drop from Onyxia: http://www.wowhead.com/item=49295/enlarged-onyxia-hide-backpack#comments

**Comment by wtRCH** [comment]
fix pending, quest working fine.
