### ISSUE TITLE
[EN] [npc] [Stonecore] last boss

### ISSUE THREAD

**Issue by blekx** [Atlantiss/BugTracker#4139]
In [**Stonecore**](http://www.wowhead.com/zone=5088/the-stonecore), Cata 5-men dungeon, [**Last Boss** High Priestess Azil](http://www.wowhead.com/npc=42333/high-priestess-azil#abilities) does these two things wrong:
**1)** She moves herself to **wrong coordinates** - instead of down to the front of the altar, she linearly moves too far back.
**2)** Her SPELL dark purple circle [Gravity Well](http://www.wowhead.com/spell=79340/summon-gravity-well) on the ground does not affect the enemy adds. And does not seem to hurt [them(?Devout Follower](http://www.wowhead.com/npc=42428)).
__
1) This wrong way-point takes place in Both HC / NORMAL modes.
I noticed it got bugged since about yesterday ( =Th, 6th August).
-confirmed
2) With purple circles issue i'm not 100% sure.
-needs confirmation
__
(I didn't find any manual how to make such reports, please let me know.)

**Comment by blekx** [comment]
(ok i have found something more how to report bugs, but i am still confused with labels and tags)
#4118 
#1155

**Comment by Aival94** [comment]
If i remember correctly Gravity well is affecting adds but they do not get hit by it but not sure if it should hit them as it say only enemies are being hit by it and both friendly and Hostile are affected by it.

**Comment by LaveGit** [comment]
![high priestess](https://cloud.githubusercontent.com/assets/12621497/9137504/5c99059a-3d1e-11e5-9e04-f96c59bf6863.png)

Experienced this just now.

**Comment by Bildo** [comment]
fixed by @Quban

**Comment by Quban** [comment]
> 2) Her SPELL dark purple circle Gravity Well on the ground does not affect the enemy adds. And does not seem to hurt them(?Devout Follower).

still not fixed btw :palm_tree:

**Comment by Aldergar** [comment]
Still not fixed,and it's pretty annoying.
