### ISSUE TITLE
What  ?

### ISSUE THREAD

**Issue by Nenoboka95** [Atlantiss/BugTracker#4141]
![screenshot_1](https://cloud.githubusercontent.com/assets/13695450/9137568/7b5b0c3a-3cd3-11e5-9fab-aaac5a5b87e9.png)

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Nenoboka95** [comment]
I do not know . Please explain

**Comment by razgal** [comment]
reinstal the game and try a different 4.3.4 client than the normal you used
you messed up something with the files in your wow folder and corrupted the launcher.

**Comment by Pallitax** [comment]
A proper title is descriptive and contains tags so that it's easier to categorize it. The title "What?" is anything but that.

A good title for this report would be something like **[EN][Other] WoW crashes on launch**

**Comment by Jenovas** [comment]
Please ask for help on the forum. This is not a server bug.
