### ISSUE TITLE
[EN][Quests][Dragonblight] Wanted quests

### ISSUE THREAD

**Issue by Lluksonak** [Atlantiss/BugTracker#4143]
Still getting used to this bugtracker e.e sorry.

The three Wanted mobs from the wanted poster in Agmar's Hammer are non-elite as of 4.3, but it isn't so on this server. http://www.wowhead.com/quest=12090/wanted-gigantaur#comments

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12526-4143questwanted-gigantaur/
