### ISSUE TITLE
[EN][Instance-WotlK] Culling of Stratholme - Mal'ganis Loot-chest bugged.

### ISSUE THREAD

**Issue by Morteraz** [Atlantiss/BugTracker#4145]
After completing the Culling of Stratholme, and after you manage to guide the kinda-buggy Arthas finally to the Mal'Ganis-Endfight, you simply can NOT open the Dark Runed Chest. Because the Chest is not there, just the textures. 

Thereby you can not get several items.

The Dungeon is listed as "Completable without major issues".

BUt that's a gamebreaker and easy to resolve.

I am a Donator because i believe in the skills of the Atlantiss-Staff, so please, take 30 seconds, spawn that Crate with the Loot-List and give us the possibility to obtain the special loot and complete that wonderful lore-dungeon! :)

**Comment by xolon** [comment]
This issue is already reported.
Also this ain't pay2win server, so you won't get extra help and being higher than others just cause you are donator

**Comment by blekx** [comment]
LAST BOSS UNAVAILABLE
Today **Arthas** got mad, and crazily **charged trough the second half of last street** (full of undead) leading to the [last boss Mal'Ganis](http://www.wowhead.com/npc=26533/malganis). **After he didn't manage to die** or wipe our very strong party (in our second attempt in one instance, attempt started again in front of city), **he went probably somewhere to Mal'Ganis, directly trough the wall** (shortcut last maybe 100yd trough the corner). In that wall +- **he disappeared** for ever. When we came fast to red, but unpullable Mal'Ganis, he wasn't anywhere anymore. We could only wait for about 10 minutes until Mal'Ganis also disappeared.

**Comment by xolon** [comment]
you need to stay really close to arthas
when he is moving, he can clip thru walls/ground and you will have to reset

**Comment by saane2** [comment]
Yea tried several times and Best reaults was defeat the mal'ganis but cache is not popping :(

**Comment by Bildo** [comment]
fixed

**Comment by saane2** [comment]
Seems like not fixed first try no chest
