### ISSUE TITLE
[PL][Quest][Orgrimmar] Weapons of Darkness

### ISSUE THREAD

**Issue by gesik2** [Atlantiss/BugTracker#4149]
http://www.wowhead.com/quest=28473/weapons-of-darkness  Quest item nie dropi z żadnego dwarfa w instancji Blackrock Depths. Item powinien mieć 100% drop rate (dowód: http://us.battle.net/wow/en/item/64313#tab=dropCreatures)

**Comment by Bildo** [comment]
fixed By Pelekon
