### ISSUE TITLE
[En][Death Knight] Mind Freeze

### ISSUE THREAD

**Issue by aranguard** [Atlantiss/BugTracker#4152]
Link 
http://www.wowhead.com/spell=47528/mind-freez

Interrapt part working well but "preventing any spell in that school from being cast for 4 sec." this part not works.For example if i interrapt a cast from Frost School player shouldnt be able to cast any spell from frost school 4 sec.Sure same for other magic schools.

**Comment by Jenovas** [comment]
Just did tests on a Frost Mage and it works. Closing.

**Comment by Kejmil** [comment]
the problem persist in pve situation, when all mobs are constantly ignoring the fact that they should be school locked after interrupt
but even so, it's global issue affecting all interrupts so this issue will remain closed
