### ISSUE TITLE
[EN][Talent][Druid] Heart of the Wild

### ISSUE THREAD

**Issue by Lluksonak** [Atlantiss/BugTracker#4155]
It doesn't seem to increase attack power for cat form.

No talent points:
![wowscrnshot_080815_104156](https://cloud.githubusercontent.com/assets/13673127/9151045/4ebcb128-3dba-11e5-91d5-c218c23a1e08.jpg)

After 3/3 talent points:
![wowscrnshot_080815_104215](https://cloud.githubusercontent.com/assets/13673127/9151047/5e399472-3dba-11e5-8ab4-91910998585b.jpg)

**Comment by Jenovas** [comment]
It works, just checked it. Relog or change form and it works.
