### ISSUE TITLE
[EN][Druid]Savage Roar 

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4158]
If you kill a player with combo points left on him, you should be able to use Savage Roar after he died, just like on pve targets

proof:

https://www.youtube.com/watch?v=NfLv8DUqOms
and
Savage Roar
"As of 4.0, you don't immediately lose combo points on a dead target (they disappear after about 20 seconds, or when you generate new ones on another target) and you can use Savage Roar (same with the rogue's Slice and Dice) without the target selected (alive or not) so you can kill an enemy however you like, and then spend remaining combo points on a SR before attacking the next enemy. Note however, that some boss adds or otherwise summoned creatures despawn instantly on death, meaning any combo points on them are lost."

**Comment by Jenovas** [comment]
If you kill a player with combo points left on him, you should be able to use Savage Roar after he died, just like on pve targets - and you can until he clicks release spirit, you cannot after he releases spirit or gets looted and is forced to release spirit.

Proof - 
1. I know in bgs after the person releases you lose the cp's
2. I think it's when they release or if somebody else loots the body. 
3. Evidently CP's have no timer other than selecting another target or in the case of BG's the dead guy releases his corps to res at a GY.
4. From what I've seen you only lose CPs temporarily when the person releases
5. You definitely do lose access while the player released.

All of the above are from the blizzard forum. I just tested and in PvP you can use the combo points if the person doesnt click release spirit. After he clicks your combo points are lost. Works as it should. Closing.
