### ISSUE TITLE
[PL][Item] The Last Relic of Argus

### ISSUE THREAD

**Issue by pelekon** [Atlantiss/BugTracker#4161]
Aktualnie po użyciu itemu The Last Relic of Argus (http://www.wowhead.com/item=64457/the-last-relic-of-argus#comments) nie dzieje się nic, odbywa się cast (http://www.wowhead.com/spell=82674/teleport-with-error), ale nie przenosi nas nigdzie.
Item powinien nas przenieść w losowe miejsce z tej listy:
    Wetlands: Shattered Dam
    Desolace: Slitherblade Shore
    Ungoro: Galakka Hot Springs
    Badlands: Crypt
    Silithus: Hive'Zora
    Western Plaguelands: Mardenholde Keep
    Tanaris: Steamwheedle Port
    Badlands: Fuselight by the Sea
    Hellfire Peninsula: Rock near Dark Portal
    Blasted Lands: The Tainted Forest
    Duskwood: Dawning Wood Catacombs
    The Cape of Stranglethorn: Janeiro's Point
    The Northern Barrens: Wailing Caverns
    Searing Gorge: Iron Summit
    Wetlands: Black Channel Marsh
    Moonglade: Nighthaven
    Western Plaguelands: Scholomance
    Northern Stranglethorn: The Sundering
    Blasted Lands: West Mountain
    Diremaul: Broken Commons
    Northern Barrens: Fray Island
    Tanaris: Lost Rigger Cove
    Felwod: Irontree Woods
    Badlands: Scar of the Worldbreaker
    Arathi Highlands: Dabyrie's Farmstead

**Comment by pelekon** [comment]
Fix zrobiony i oczekuje na akceptacje.

**Comment by armano2** [comment]
duplikat: #3679
