### ISSUE TITLE
[PL][Mobs] Ethereum Jailor

### ISSUE THREAD

**Issue by pelekon** [Atlantiss/BugTracker#4162]
Aktualnie moby Ethereum Jailor (http://www.wowhead.com/npc=23008/ethereum-jailor) nie spawnią się, utrudnia to mocno zdobywanie Ethereum Prison Key (jedynym możliwym sposobem jest wydropienie ich z insty Mana Tombs w wersji heroicznej).

**Comment by Bildo** [comment]
fixed By Pelekon
