### ISSUE TITLE
[EN][Spell][Rogue] Killing Spree

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#4164]
While using this spell player is teleported in front of the target and not behind as it was intended.

**Comment by Jenovas** [comment]
You are teleported behind if the core knows for 100% that you can go behind and you wont fall of anything or fall into textures (in a wall etc). If the core thinks that landing behind the target can bug you it makes you land in front. And its not only killing spree but also feral charge and other leaps. So this isnt a bug of the spell only of mmaps if you see that you can go behind but it puts you in front.

**Comment by milzo** [comment]
I've never been teleported behind, always in front.
