### ISSUE TITLE
[EN][Item] Vengeful Gladiator's Felweave Cowl

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#4165]
Vengeful Gladiator's Felweave Cowl have the visual of Hood of the Malefic (T6).

Vengeful link: http://www.wowhead.com/item=33683/vengeful-gladiators-felweave-cowl
Malefic link: http://www.wowhead.com/item=31051/hood-of-the-malefic

The wings are Malefic too, which is orange instead of purple.
Also when you activate wings by jumping or casting howl of terror makes them dissapear almost instantly. They're supposed to do its thing like when you do the /roar command.

**Comment by Fearyourself** [comment]
.

**Comment by Piklo** [comment]
#812
