### ISSUE TITLE
[EN][Dungeon-Cata][Deadmines][Vanessa-Vancleef]

### ISSUE THREAD

**Issue by blekx** [Atlantiss/BugTracker#4166]
During the [last boss](http://www.wowhead.com/npc=49541/vanessa-vancleef) encounter we got **stuck** when we appeared bound hanging on a rope **INSIDE** (not as high as supposed) **the furnace** with molten orange metal.

I think my visual impression looked like i am falling into it about every 1 second again. But if i am not mistaken, moving the camera showed we are all just inside it. Btw. i didnt notice any effect like after you drink alcohol or when you are in some nightmare.) No idea if a nearby [add](http://www.wowhead.com/npc=49229) here from [previous buggy boss](http://www.wowhead.com/npc=43778/foe-reaper-5000) influenced it in any way. (Watched myself stuck there for at least 20 sec, but probably 1min+ befoere we dissmissed.)

**Comment by maciekf3** [comment]
Did you use steam valve near the furnace ? 
Doing so makes you get out of there

**Comment by Aviannaqt** [comment]
Should be work fine.
