### ISSUE TITLE
[EN][Quest][Zangarmarsh] Fhwoor Smash!

### ISSUE THREAD

**Issue by aqa000** [Atlantiss/BugTracker#4168]
Located in Sporeggar, we should escort the quest giver to Marshlight steam pump and back, but at the start of the quest the NPC doesn't start moving, nothing happens.
Wowhead link: http://www.wowhead.com/quest=9729/fhwoor-smash
How it should work: https://www.youtube.com/watch?v=zsRUNKxvb9o

**Comment by Illusionist87** [comment]
Bumping... Still not working.

**Comment by tomatosz** [comment]
Bumpity bump

**Comment by Nanosystem01** [comment]
It's a shame this does not work, the weapon you receive is quite an upgrade for me at the moment. I would most likely use it until I got to Northrend.

**Comment by Bildo** [comment]
fixed
