### ISSUE TITLE
[PL][Quest][Stonetalon Mountains] Reinforcements...

### ISSUE THREAD

**Issue by Cougie** [Atlantiss/BugTracker#4169]
Użycie poganiacza na koboldach nic nie daje. Bugged quest.

**Comment by Angelo-DM-** [comment]
Confirm! Bugged Quest! [ID: 26066](http://www.wowhead.com/quest=26066)
When you use the [Subjugator devo's whip](http://www.wowhead.com/item=56794) on any [Boulderslide Kobold](http://www.wowhead.com/search?q=Boulderslide) in the cave, no one of them become a [Subdued Kobold](http://www.wowhead.com/npc=42024).

**Comment by Syrnikus** [comment]
Nie działa DALEj !!

**Comment by GamerSlew** [comment]
Quest does not work.
