### ISSUE TITLE
[PL][Dungeon Finder] Cant get Valor Points

### ISSUE THREAD

**Issue by Domri** [Atlantiss/BugTracker#4170]
Zdobyłem 85 poziom i mogę robić heroiki. Tyle że po zrobieniu heroica nie dostaję Valor Points tylko normalne Justice Points jakbym robił normala tylko że robię heroica. Na górze Dungeon Findera nie pojawia się żaden licznik punktów choć w nagrodach jest napisane że mogę zdobyć 140 Valor Points. 
Bez Valor Points nie ma sensu grać dalej

**Comment by blinkmaster** [comment]
valory za rhc dostajesz od nastepnego lockout resetu od wbicia 85 lvl czyt nast dnia.

**Comment by Domri** [comment]
Ale minął już tydzień a dalej nie mogę zdobyć Valorów

**Comment by Anhaeyn** [comment]
W środy resetuje się prawie wszystko, w tym tygodniowy limit na valor points. Spróbuj wtedy.
