### ISSUE TITLE
[EN][General]Hearthstone problems

### ISSUE THREAD

**Issue by zetsuno** [Atlantiss/BugTracker#4173]
I really don't know, but it might be a character-specific bug, however, I can't set 'home' for the hearthstone at new places. Also when I tried to delete it, to see if I could get a non-bugged one back from a Innkeeper, I don't get anything. So, pretty much I can't get a hearthstone and I can't set the 'home' location. Help would be appreciated. Made a GM Ticket last night but Pallitax redirected me here. 

Thanks for your help,
Best regards.

**Comment by Wolffenstein** [comment]
Have you tried other Innkeepers?

**Comment by zetsuno** [comment]
Tried 3 alredy

**Comment by zetsuno** [comment]
For some reason, after I use unstuck, and asked the inkeeper for a hs again, he gave it to me, tried relogging multiple times before and didnt fix it... oh well, atleast it's fixed.
