### ISSUE TITLE
Into the Raptor's Den Quest - Bugged

### ISSUE THREAD

**Issue by Alexhandr** [Atlantiss/BugTracker#4177]
When I go to put the feathers into the raptor's nests, there is no action icon (gear). The nests glow, but nothing can be done, so I cannot place the feathers.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the quest provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by armano2** [comment]
duplicate: #3398 also bad title no links, no videos...
