### ISSUE TITLE
[EN][Quest][The Hinterlands] Hunt the Keeper

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#418]
What is not working:
=============

At the moment, the quest is auto-complete, you get the quest-item when you pick the quest.

---------------
How should work:
=============

You should not get the item. The NPC is available to slaughter, and the quest-item is dropping.

----------------------
More info:
=============

I did the quest "normally", by killing the required mob, but I found another issue. The mob has no script. When approaching it, it seems to be "trapped" and it can't move, if you go close enough, it starts to attack. Fall back and it stops the attack.

[Screenshot#1](http://i.imgur.com/WwYdwuk.jpg)
[Screenshot#2](http://i.imgur.com/FSWsjPR.jpg)
[Morta'gya the Keeper - WoWHead](http://www.wowhead.com/npc=42877)
[Morta'gya the Keeper - WoWPedia](http://wowpedia.org/Morta%27gya_the_Keeper)
[Hunt the Keeper - WoWHead](http://www.wowhead.com/quest=26369)
[Hunt the Keeper - WoWPedia](http://wowpedia.org/Quest:Hunt_the_Keeper)

**Important Note:** There are 2 versions (Horde+Alliance), dunno if Alliance quest is on auto-complete too.

**This was tested on 4.0.6a & 4.3.4 realm**

**Comment by Enay** [comment]
First time I took the quest, I got the item and it was auto-completed. I abandoned it, threw away the item and took the quest again, but this time, I didn't get the item and I had to do the quest.
