### ISSUE TITLE
[EN][Quest][Northern Barrens] Into The Raptor's Den

### ISSUE THREAD

**Issue by Alexhandr** [Atlantiss/BugTracker#4180]
When I go to put the feathers into the raptor's nests, there is no action icon (gear). The nests glow, but nothing can be done, so I cannot place the feathers.
http://www.wowhead.com/quest=905/into-the-raptors-den

**Comment by pelekon** [comment]
Quest is working correctly You have to use feather in your backpack while being next to glowing nests. Just did it while ago.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3398
