### ISSUE TITLE
[EN][Quest][Northern Barrens] Raging River Ride

### ISSUE THREAD

**Issue by Alexhandr** [Atlantiss/BugTracker#4181]
![wowriverboatbug](https://cloud.githubusercontent.com/assets/13699247/9173734/011d2ace-3f4a-11e5-8068-35affb059d6c.jpg)

Upon the riverboat stopping at it's destination, I began to fall through the world (with a parachute) and continued to fall for about two to three minutes until finally reaching the "bottom," and dying.

http://www.wowhead.com/quest=26769/raging-river-ride

**Comment by Quban** [comment]
is this boat swimming through textures?

**Comment by Alexhandr** [comment]
No, sir
Sent on a Sprint Samsung Galaxy S® III

<div>-------- Original message --------</div><div>From: Quban <notifications@github.com> </div><div>Date:08/11/2015  6:50 AM  (GMT-05:00) </div><div>To: Atlantiss/BugTracker <BugTracker@noreply.github.com> </div><div>Cc: Alexhandr <alexhandrdenthanor@yahoo.com> </div><div>Subject: Re: [BugTracker] [EN][Quest][Northern Barrens] Raging River Ride
  (#4181) </div><div>
</div>is this boat swimming through textures?

**Comment by JohannDoe** [comment]
That's still buggy. Happened to me just now...

**Comment by xmesaj2** [comment]
rev. 5417 fixed
