### ISSUE TITLE
[EN][Quest][Mulgore] The Restless Earth

### ISSUE THREAD

**Issue by Alexhandr** [Atlantiss/BugTracker#4182]
Upon arriving at the Bael'dun Digsite, there are dwarven corpses, but no Earth spirits at all. Therefore it is impossible to complete the quest.
http://www.wowhead.com/quest=14491/the-restless-earth

**Comment by pelekon** [comment]
http://community.atlantiss.eu/index.php?/topic/5480-issue-4182/

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3375
