### ISSUE TITLE
[EN][Item] Starfire Espresso

### ISSUE THREAD

**Issue by user1011** [Atlantiss/BugTracker#4183]
When you drink a starfire espresso (http://www.wowhead.com/item=62675/starfire-espresso), you become completely smashed.
![wowscrnshot_081015_161116](https://cloud.githubusercontent.com/assets/13118481/9179570/cfa39768-3f9d-11e5-9988-a959bcd88347.jpg)
according to the comments on wowhead, it shouldn't really sober you up either.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1032
