### ISSUE TITLE
[PL][Quest][Horde] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by pelekon** [Atlantiss/BugTracker#4189]
Aktualnie przy oddawaniu questa nie dostajemy żadnej nagrody, a powinniśmy móc wybrać sobie jeden z 6 hełmów. http://www.wowhead.com/quest=10639/teron-gorefiend-i-am#comments

**Comment by Axahus** [comment]
Duplikat https://github.com/Atlantiss/BugTracker/issues/3868

**Comment by pelekon** [comment]
Ok nie zauważyłem, fix jest już napisany i wstawiony na forum, powinien być zaakceptowany.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1726
