### ISSUE TITLE
[PL][Quest][Mount Hyjal] Death to the Broodmother

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#4194]
[Death to the Broodmother] (http://www.wowhead.com/quest=25553)
 - podczas brania q brak obrazka
 - quest nie powinien być zaliczony od razu po wzięciu 

Sprawdzałem jak działa i event dobrze działa tylko, że npc do zabicia się nie pojawia(pojawia się gdy znikną te przyjazne i znika po 3 sec)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/611
