### ISSUE TITLE
[PL][NPC][Burning Steppes] Eitrigg

### ISSUE THREAD

**Issue by Kaabum** [Atlantiss/BugTracker#4195]
Kłopot pojawia się już któryś raz w tej krainie z blokowaniem questów.

http://www.wowhead.com/npc=48569/eitrigg

Wykonałem od niego 3 questy:
-http://www.wowhead.com/quest=28445/a-heap-of-delicious-worg
-http://www.wowhead.com/quest=28443/blackened-ashes
-http://www.wowhead.com/quest=28444/latent-demons-of-the-land

Kolejne 5 jest nie do wzięcia:
-http://www.wowhead.com/quest=28451/a-delivery-for-neeralak
-http://www.wowhead.com/quest=28450/a-delivery-for-thorgizog
-http://www.wowhead.com/quest=28452/a-delivery-for-xilun
-http://www.wowhead.com/quest=28455/glory-amidst-chaos
-http://www.wowhead.com/quest=28456/the-spoils-of-war

EDIT

Brakuje tego npc http://www.wowhead.com/npc=48565/ariok

Byc moze przez to reszta q nie chce ruszyc, poniewaz kilka q trzeba zrobic u niego, by moc u Eitrigg'a.

**Comment by pelekon** [comment]
Według wowwiki musisz wykonać najpierw tego questa( http://wowwiki.wikia.com/wiki/Quest:Placing_the_Pawns )żeby móc wykonywać te pozostałe.

**Comment by Quban** [comment]
wg DB tez ;p

**Comment by Kaabum** [comment]
Z tym, że ja staram się wbić aczi za lore, a q tam robiłem koło 2012, więc nie pamiętam, które robiłem, których nie robiłem. Ostatnio pomagał mi kilkukrotnie GM, żeby pchnąć te q dalej i co jakiś czas się blokowały.

**Comment by pelekon** [comment]
Polecam addon everyquest, pokazuje on które q z danej krainy już zrobiłeś, z pomocą wowheada i wow wiki znajdziesz szybko które q musisz jeszcze zrobić.

**Comment by Kaabum** [comment]
Już jest git. Brakowało tego drugiego npc, Ariok'a.
