### ISSUE TITLE
"Rested" xp bonus grows larger and larger

### ISSUE THREAD

**Issue by Gromko1111** [Atlantiss/BugTracker#4198]
So it looks like I'm receiving double xp (or no double xp, I don't really know how much should I actually get for that giraffe) 
![a](https://cloud.githubusercontent.com/assets/13754995/9210549/405ec4d4-407d-11e5-9f2e-89329f74e20c.jpg)

![b](https://cloud.githubusercontent.com/assets/13754995/9210512/04333292-407d-11e5-8ff3-3a08dbf130c9.jpg)

Disclaimer: There is no subliminal message in my character holding his head up the giraffe's ass...

**Comment by Wolffenstein** [comment]
Bonus exp, it's intended.
