### ISSUE TITLE
[PvP][PL]Honor 

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#4206]
Caly czas leci za mało honoru, za cap flagi powinno być 14 honoru dla każdego na BG a nie po 2/3.
Za kill powinno być 12 rozdzielone dla wszystkich w pobliżu. Za pkt na Bg z punktami powinno byc 14 honoru dla wszystkich a nie 0/1

**Comment by Bildo** [comment]
Nie widzisz, ze update nie bylo ;o ?

**Comment by MasterK15** [comment]
Serio ? dalej mam sie wkurwiać na worldzie/plu jak to bardzo migliscie zjebac ?

**Comment by Bildo** [comment]
he ? człowieku daj se spokój lepiej z wowem skoro wkurwiasz sie bez powodu...

**Comment by MasterK15** [comment]
moze masz racje
