### ISSUE TITLE
[quest][pl] Thunderaan the Windseeker

### ISSUE THREAD

**Issue by kacper123** [Atlantiss/BugTracker#4207]
http://www.wowhead.com/quest=7786/thunderaan-the-windseeker
Po uzbieraniu wszsykich matsów nie ma możliwości oddania q jest nieaktywny  tak jakbyś nie miał uzbieranych wszskich elemntów dalsza cześć q działą poprawienie 

+Essence of the Firelord
http://www.wowhead.com/item=19017/essence-of-the-firelord
nie posaida 100% szansy na dropa padło za 4 razem a powinno posaidać

**Comment by armano2** [comment]
duplicate: #2983
