### ISSUE TITLE
[EN][NPC] Silvermoon City Guardian

### ISSUE THREAD

**Issue by Adunai** [Atlantiss/BugTracker#421]
Problem: SMC Guardian doesn't respond to Horde paladins' emotes (/kiss, /rude, /shy and /eye).

How should it work: you create a Horde (BE/Tauren) paladin, go to the SMC Guardian, use an emote (/kiss, /rude, /shy or /eye). He should respond.

Nota bene (pay attention): don't confuse SMC Guardians with Sunstrider Guardians. The latter should not respond to emotes.

Links & proofs: WoWPedia (http://wowpedia.org/Silvermoon_City_Guardian).
WoWHead (http://www.wowhead.com/npc=16222).
Screenshot (http://s20.postimg.org/dq0amskwt/Wo_WScrn_Shot_112414_045113.jpg).

You can make a character on retail and check it thoroughly themselves.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/427
