### ISSUE TITLE
[EN][Priest] atonement

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4210]
I got healead 45k crit from atonement by a priest. 
http://tinypic.com/r/1zyh955/8

First bug:
The atonement should heal for exactly same amount as you damage.If you crit, the heal should be that damage.
proof: tooltip

Second bug:
45k heal it's way too much for atonement,you can't crit with a normal healing spell that much, but with smite or Holy fire?there must be some modifiers that increase the healing by more than it should.

**Comment by Jenovas** [comment]
Well its like this - smite crits for 20k, atonement gets bonuses from heal increasing talents AND can crit (which is a bug I think). So the heal should have been around 20k+ without the heal being able to crit. I think the only bug is that the heal can crit.

**Comment by planche** [comment]
You have a point Jenova. Paragon's logs back from 4.3 (healing by spell tab)
http://www.worldoflogs.com/reports/73zxd3o7n353msjc/details/20/?s=2626&e=2812

**Comment by Dziara** [comment]
When you will try to fix that, remember about older issue #2070 .
So it should work like that: Smite/Holy fire crit -> Atonement(without chance to be crit) + Divine Aegis.

**Comment by Quban** [comment]
divine aegis doesnt work?

**Comment by Dziara** [comment]
It works incorrectly. Right now it procs only from crits from Atonement (but crits from Atonement should never exist according to that issue). When we crit with Smite/Holy fire and DON'T get crit from Atonement, Divine Aegis doesn't proc and that is bug.

**Comment by Jenovas** [comment]
atonement - shouldnt be able to crit BUT if it was proced from a smite that critted it should give Divine Aegis

**Comment by Kejmil** [comment]
smite hits for 10k, heal someone for 10k <-works ok, maybe range of the atonement is too high
smite crits for 20k, atonement don't crit and heal someone for 20k <- atlantiss
smite crits for 20k, atonement heal also crit and heal someone for 40k <- atlantiss
smite crits for 20k, heal someone for 20k while being unable to crit+(30%+mastery of this heal in divine aegis) <- retail

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev4567
