### ISSUE TITLE
[en][spell][death knight] Death Grip in PvP minimal range

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#4211]
since late 3.3.5 and all cata Death Grip should have minimal range of 8yds in PvP, change was made due to fact DKs used DG as another interrupt when being on top of the target.
http://wowwiki.wikia.com/wiki/Death_Grip
 Patch 3.3.3 (2010-03-23): Minimum range has been changed to 8 yards in PvP.
 Patch 4.0.6 (8-Feb-2011): The tooltip has been updated to reflect the minimum distance of 8 yards in PvP.

**Comment by nevcio** [comment]
These changes never went live
https://www.youtube.com/watch?v=0SXB4zPiOe8
1:19 grips priest in melee range
http://us.battle.net/wow/en/forum/topic/2973247700?page=1
people complaining about no minimum range on official wow forums during cataclysm

**Comment by aranguard** [comment]
Death grip has only 2 problems for now.

For pvp : When grip player its coming to death knight but %50 stops half way or turning back to first place instant.

For pve : For some bosses its only animation and useless.

For all other aspects its working well.

**Comment by blinkmaster** [comment]
not rly convinced.

http://www.arenajunkies.com/topic/130398-death-grip-nerf-discuss/

http://www.mmo-champion.com/threads/704977-quot-Unintended-quot-DG-change-is-live
"Here is my trying to DG a paladin in front of, but right outside my melee range, notice the "target is to close"

"What the hell? I though that change was not supposed to go live, yet on PvP targets me and my friend DK seems to have a minimum ~8yard range on deathgrip, or is it some kind of bug.."

"i don't see a nerf. Atm you need >5y or so to interrupt a cast or so, nothing changes

but i like this one
Unstable Affliction - Only one Unstable Affliction or Immolate per Warlock can be active on any one target. "

"I somehow think the range is more now then before, since I never faced the "Target is to close" issue before the patch"

http://www.warcraftmovies.com/movieview.php?id=130169 2.20

https://www.youtube.com/watch?v=ufVSmB_hH0s 4.27

http://www.warcraftmovies.com/movieview.php?id=145367 11.07
Check 11:11 in that wcm movie also, he stands right in front of Snutz, presses death grip and it says "Target too close".

**Comment by nevcio** [comment]
https://www.youtube.com/watch?v=4fQPSkQR5CE
9:52
