### ISSUE TITLE
[PL][NPC][Blackrock Mountain] Lotos Riftwaker

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#4212]
[Lotos Riftwaker] (http://www.wowhead.com/npc=14387)
Brak tego NPC powinien nam dawać q   [Attunement to the Core] (http://www.wowhead.com/quest=7848) i po ukończeniu tego q dostajemy u niego możliwość teleportu do Molten Core(bez skakania przez okno :) )

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6636-missing-npc-lothos-riftwaker/
