### ISSUE TITLE
[EN][Spell][Class] Master Shapeshifter gets removed after entering travel/swim/fly/tree form

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#4214]
After entering travel/swim/fly/tree form Master Shapeshifter gets removed which reduces our healing by 4%. Entering cat or bear form and leaving fixes this.

**Comment by LaveGit** [comment]
Won't be deleted if you reform it accordingly; https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Kejmil** [comment]
because i have good heart i give you time to midnight (pl time) to fix it
and pls, limit your childlish behaviour - if anything, you are ensuring that no dev will look onto this problem

**Comment by phanttom** [comment]
btw there is difference between a problem and disaster ;) 1500 intellect = 7 heroic items

**Comment by Kejmil** [comment]
it is propably related to rev. 4490 (http://atlantiss.eu/changelog/3#rev4490), change title to reflect it

**Comment by Kejmil** [comment]
twoja poprawka :D

**Comment by Jenovas** [comment]
Please tell me how much intelect and spellpower do you have and for how much do you heal from reju, instant reju, lifebloom tick with 1 stack, lifebloom tick with 3 stacks, lifebloom bloom with 1 stack, lifebloom bloom with 3 stacks. Thx.

**Comment by Jenovas** [comment]
I did some tests and the healing only bugs when leaving travel form and entering bear form / Cat Form and exiting it fixes the bug. So it aint that bad as you stated above.

**Comment by phanttom** [comment]
u still dont get it if i transform to tree il get bugg and even that 30 sec tree form that im counting on to heal better it wont heal as i was expected so the solution is when i transform to tree  i should cancel it by bear?it will fix it but than again bye bye tree form wasnt useful as suppose to be healing.... so i went tree i have now bugg on tree form :Z therefore the 30 seconds tree form is healing low with bugg and i dont want to cancel it by bear i want it to be fixed ........thats nt just me 4 healers in nefarious guild have same problem tree form buggs it, aquatic and travel and swift flight and flight form. So point is my tranquility in tree form is low thx to the bugg + all other spells that im using on tree form

**Comment by phanttom** [comment]
clicking tree form = -1500 intellect as i explained on the first praragraph= 30 sec tree form with -1500 intellect

**Comment by Jenovas** [comment]
Yes yes - 5000. Disater.

**Comment by Tottres** [comment]
-1500, -5000 or even maybe -100000 it doesnt matter cause the point is, that Tree of Life is the only one class druid buff and without working it properly, druid is useless on 'huge amount of damage' phases.
Even if leaving cat/bear form repairs this bug, it is only for a while, cause every shapeshifting into tree form is activating this bug again.

**Comment by Kejmil** [comment]
If it is SO important to you, why you are unable to make proper issue on bt? It was DEV who tested what exactly is causing problem here, not you, you are just misleading him talking about some lost intellect (wtf?).
Dev should spend his time on fixing things, not checking if issue is actually correct.
I wouldn't be suprised if this issue will now rot here on BT, actually i hope that it will - maybe then some people wil be able to actually read and follow rules.

**Comment by Tottres** [comment]
for your information - I made private gist for devs week ago (in request of an admin) after few hours of testing this bug, where everything is clearly explained, so please stop being scathing.

**Comment by phanttom** [comment]
Kejmil u crack me up haha (loss 1500 intellect the problem)  want me show anytime or u gonna hide behind ur screen talking trash that nothing wrong or nvm il never enter bugtracker i already lost much of my gold time convincing wall that blind ppl can see it

**Comment by Jenovas** [comment]
You do need lose 1500 intellect you lose the buff call Master Shapeshifter that increases healing by 4%.

**Comment by phanttom** [comment]
300 intellect flask gives u more 55 HP for instant( first tick) rejuvenation so 300X 5=? 1500 intellect u get 275..........with bug u loss 279 insta rejv ......... means u lost 1500 intellect and to be more specific u lost 1518.75 intellect still talking about only instant rejv if u want me to talk on each spell detail and over time will take me 10 pages Loss healing !!! well if u say  4% for me its 1518.75 intellect if u call that nt working

**Comment by phanttom** [comment]
and if thats true implies the more gear u have the more worse u loose intellect. 362 item lvl and loss 1518.75 intellect if i have more than :Z who knows how much loss lol

**Comment by phanttom** [comment]
yea ur right i lose that master shapeshifter thx for info :) i just tried it ur correct :D btw the higher gear u have the worse u become ,in other words : from 362 item lvl and above  its like losing at least 1500 intellect and the more itemlvl in healing the number increase above 1500..... if u see that is k according to kejmil than i have no words to say anything :D

**Comment by Jenovas** [comment]
Should be fixed in rev 4669.
Also Tree Of Life Form will increase healing by 15%, was around 33%.
