### ISSUE TITLE
[PL][Spell][Warlock] Burning Felhunter

### ISSUE THREAD

**Issue by Maksi85** [Atlantiss/BugTracker#4215]
![wowscrnshot_081315_190603](https://cloud.githubusercontent.com/assets/11136167/9257277/f9109840-41f4-11e5-9f81-dd7b3afb1f28.jpg)
Nie mam pojęcia czy ma to być jako spell, czy npc. GM kazał mi tu napisać, więc piszę. Chodzi o to, że jakieś 3-4 miesiące temu po jednym z BG mój Felhunter zaczął płonąć (w taki sposób jak staniesz postacią na ognisko). Zabiera mu to 900hp co sekundę, a jako że gram w Affliction potrzebuję owego peta. Wcześniej się tym nie przejmowałem, bo przestałem grać, lecz teraz, gdy wróciłem praktycznie uniemożliwia mi to grę we wcześniej wymienionej specjalizacji.

**Comment by Bildo** [comment]
niech gm da na niego unaure i po problemie

**Comment by Maksi85** [comment]
GM kazał mi to napisać tutaj. Nie mam ochoty czekać kolejnych 3h na odbiór ticketa.

**Comment by Kejmil** [comment]
tutaj czekasz rok, tam pare dni :D
