### ISSUE TITLE
[PL][Quest][Isle of Quel'Danas] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by Lihtan** [Atlantiss/BugTracker#4216]
http://www.wowhead.com/quest=24553/the-purification-of-queldelar
Ten quest nie działa. Nie można wejść do Sunwell Plateau i uzyskać końcowego itemu - http://www.wowhead.com/item=49871/restored-queldelar .
Tylko tyle i aż tyle.... Są szanse na naprawienie go?

**Comment by eryczek1615** [comment]
Wpierw trzeba Sunwella naprawić

**Comment by Lihtan** [comment]
A nie można po prostu dać itemku graczom i tyle? Po tickecie?

**Comment by Lihtan** [comment]
Co oznacza ten znaczek "closed"? Quest jest naprawiony??

**Comment by Bildo** [comment]
nic nie oznacza w tym wypadku ten issue nadal jest otwarty tamten to po prostu duplikat

**Comment by Nc94** [comment]
co do ludzi mówiących że trzeba SWP naprawić to ten quest NIE WYMAGA działającego SWP bo do wykonania go jest całkiem osobny event nie odbywający się w samej raid instancji tylko w osobno fazowanej jej wersji https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by Bildo** [comment]
No nie do końca, bo quest dzieje sie w instancji (ta sama mapa) tylko faza jest inna.

**Comment by Nc94** [comment]
aaa chyba że tak

**Comment by Syruzak** [comment]
as Bildo stated, you should talk to a Warden of the Sunwell who teleports you to a different instance to finish this quest, therefore this quest doesn't need the Sunwell Plateau raid
(sorry for speaking english in a polish chat but the english version got closed and linked here)

**Comment by Bildo** [comment]
In my post I said that the instance need to be opened

**Comment by Kubelecer** [comment]
As of today the NPC that is supposed to teleport you to the sunwell is still not visible. I also recieved 3 copies of the quest that were available before I did the prequest that was about talking to the body in the dead scar.

**Comment by ounagi21** [comment]
bump

**Comment by Bildo** [comment]
fixed

**Comment by jissabraham** [comment]
now it teleport u as of rev. 5314, but once inside the event is not starting and the sward is not been able to be restored. so quest is still undoable

**Comment by wowcircle** [comment]
Halduron Brightwing doesn't give me this quest after i complete "Thalorien Dawnseeker" quest. Any idea?

**Comment by secu312** [comment]
The Purification of Quel'Delar still bugged

**Comment by Skjemme** [comment]
Still bugged

**Comment by Skjemme** [comment]
Dalej musimy być w grupie raidowej żeby poprzez rozmowe ze strażnikiem przeniesiono nas do sali eventowej ale w sali ewentowej nawet z grupą raidową nic się nie dzieje po uzyciu quest itema. tzn. bohater castuje, wyrzuca miecz do sunwella i to wszystko, tracimy quest item, i nie dostajemy nastepnego potrzebnego do dokonczenia zadania. undoable.

**Comment by Piklo** [comment]
Następnym razem otwierajcie nowe posty bo na 90% jestem pewien że zamkniętych mogą nie czytać :p

**Comment by Malylolek** [comment]
Otwartych też ! ! !
