### ISSUE TITLE
[EN][Silverpine Forest][NPC] Master Forteski and Veteran Forsaken Trooper

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#4217]
While this is a bug with the NPC respawn, I'll have to say that it affects a previous quest chain that ends with **Cornered and Crushed!** (http://www.wowhead.com/quest=27194).

See, when people do the next quest, **Nowhere to Run** (http://www.wowhead.com/quest=27195), they escort **Master Forteski** (http://www.wowhead.com/npc=45228) and **Veteran Forsaken Trooper**(**s**) (http://www.wowhead.com/npc=45225) to the end of the **Deep Elem Mine**, there's a trap, bombs/dynamites explode and they all die.

However, when they die, they should spawn back at the beginning of the mine right away. As you can see on the video here: https://www.youtube.com/watch?v=qzOTkVxYnpI

On Atlantiss, this doesn't happen, so if some player does **Nowhere to Run**, just as you arrive to turn in your **Cornered and Crushed!**, you're stuck waiting for a while for the respawn of **Master Forteski** in order to turn in your quest and start your own **Nowhere to Run**.

**Comment by Quban** [comment]
fixed in rev http://atlantiss.eu/changelog#rev5086
