### ISSUE TITLE
[EN][Ruins Of Gilneas][NPC] Forsaken Vanguard (Minor)

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#4218]
**Forsaken Vanguard** (http://www.wowhead.com/npc=45280) @ **45.8**, **21.8** should be dead, as you can see in this video: https://youtu.be/7Rj-3TCx6m0?t=46s

On Atlantiss, they are alive, as you can see on this screenshot:

![wowscrnshot_081315_234834](https://cloud.githubusercontent.com/assets/9798968/9262587/64e3fe56-4216-11e5-9bcc-35b42fbf53e1.jpg)

**Note**: There are more **Forsaken Vanguard** in Ruins Of Gilneas that have the same ID and they are alive, so be sure that only those on the coordinates I gave (you can see the pin on the wowhead map, on the link) are dead.

**Edit**:
These here as well. Here's the video: https://www.youtube.com/watch?v=Ac1BXtYswO0
But they should obviously be dead, since they're in fire :P

![wowscrnshot_081415_072017](https://cloud.githubusercontent.com/assets/9798968/9267768/4deebfda-4255-11e5-9ea4-602cb922449e.jpg)

**Comment by armano2** [comment]
duplicate: #2642
