### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by Alexhandr** [Atlantiss/BugTracker#4219]
Upon arriving at Grol'drom farm, you dismount the kodo, which for some reason bugs into the picture I linked below. Then when you are supposed to continue to the Crossroads, you are unable to mount the kodo. A gear icon appears, but not a mount vehicle icon. If you walk to Crossroads and talk to Thork, he will ask if you are the one using the gun, but he will not complete the quest for you.
https://gyazo.com/0e99f5d4f6c3f5176d568cf346cf3427
http://www.wowhead.com/quest=13975/crossroads-caravan-delivery

**Comment by Ishana** [comment]
I had that bug occur to me as well

**Comment by duttyy** [comment]
confirmed

**Comment by Xenerus** [comment]
As far as I know, you should be able to talk with Rocco Whipshank (http://www.wowhead.com/npc=34578/rocco-whipshank), who should have a dialouge option. After you speak to him, NPC (http://www.wowhead.com/npc=34577/head-caravan-kodo) will spawn. You should be able to mount it and it will take you to the Crossroads. You encounter enemies (http://www.wowhead.com/npc=34594/burning-blade-raider) along the way.

If you guys have more important matters, repair quests such as this, temporary at least, with a totem kill/click credit.

**Comment by Alexhandr** [comment]
I have no idea what a totem kill/click credit is, I would have to look it up.
Also, I did attempt to do as listed above.All it does is bring up the quest log box where he gives you the gun. That's it.

**Comment by Xenerus** [comment]
My message was intended for the developers who are fixing it. :)

**Comment by Alexhandr** [comment]
Ohhhh, haha. Got it. Sorry :)


Sent on a Sprint Samsung Galaxy S® III

<div>-------- Original message --------</div><div>From: Xenerus <notifications@github.com> </div><div>Date:08/15/2015  6:25 AM  (GMT-05:00) </div><div>To: Atlantiss/BugTracker <BugTracker@noreply.github.com> </div><div>Cc: Alexhandr <alexhandrdenthanor@yahoo.com> </div><div>Subject: Re: [BugTracker] [EN][Quest][Northern Barrens] Crossroads Caravan
  Delivery (#4219) </div><div>
</div>My message was intended for the developers who are fixing it. :)
