### ISSUE TITLE
[EN][NPC] Blood Elf Warlock

### ISSUE THREAD

**Issue by Adunai** [Atlantiss/BugTracker#422]
Problem: animation of these NPCs is wrong.

What should be: these NPCs should suck fel energy from crystals via green beams.

Admiration: I really appreciate your work, Atlantiss. Other servers have no animation for them at all, you tried, at least. But you can do better! I believe in you!

Links & proofs: WoWHead (http://www.wowhead.com/npc=18763).
Screenshot from Atlantiss (http://s20.postimg.org/e5bkft6u5/Wo_WScrn_Shot_112414_045256.jpg).
Screenshot from Agamaggan (RETAIL REALM) (http://s20.postimg.org/fmu681syl/Wo_WScrn_Shot_081914_133530.jpg).

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6650-missing-green-laser-animation/
