### ISSUE TITLE
[PL] Level cap nie działa.

### ISSUE THREAD

**Issue by azawko** [Atlantiss/BugTracker#4223]
Po odblokowaniu na stronie Level cap- cataclysm u postaci nie pojawił się pasek xp bar. Doświadczenie nie wzrasta

**Comment by Bambosz** [comment]
Spróbuj jeszcze włączyć expa u http://www.wowhead.com/npc=35364/slahtz albo http://www.wowhead.com/npc=35365/behsten

**Comment by azawko** [comment]
Dzięki to działa.Byłam tam już wcześniej ale nie zauważyłam tego gościa.
