### ISSUE TITLE
[EN][I'M NOT SUPPOSED TO TELL YOU THIS][Quest]

### ISSUE THREAD

**Issue by Valhallen** [Atlantiss/BugTracker#4224]
NPC #45450 "The Lone Hunter" seems missing from the Darrowshire Hunting Zone.

**Comment by Philippe777** [comment]
It worked for me. =/ The Lone Hunter is a brown wolf (like, hinterlands ones) with a sword through its skull.

**Comment by turnkeyfriend** [comment]
Same as https://github.com/Atlantiss/BugTracker/issues/4030

Currently spawns at 38,80.

**Comment by Anhaeyn** [comment]
He spawns, but is in a bit different place.

**Comment by armano2** [comment]
duplicate: #4030
