### ISSUE TITLE
[EN][Talent][Mage] Cauterize

### ISSUE THREAD

**Issue by OnlyGodKnows** [Atlantiss/BugTracker#4230]
Cauterize talent sometimes causes Mage hit with Chimareon (BWD) massacre to die. Mage isn't healed to 40%, but stays at 1% and gets Caudterize's DOT, which kill him immediately.
As i was surprised by how easly i got killed i was told that it's a known bug, but i haven't seen it reported.

**Comment by tdotzlod** [comment]
Playing a mage but haven't spotted such problem.
Cauterize doesnt bring mage to 40% is true. Instead mage healed to 100%
If you die at chimaeron as fire mage from cauterize then you got consecutive hits of caustic slime and massacre but it's possible to avoid it with timely used iceblock.
