### ISSUE TITLE
[PL][Achievement][Let's Do Lunch: Orgrimmar]

### ISSUE THREAD

**Issue by relek** [Atlantiss/BugTracker#4235]
Achievement - http://www.wowhead.com/achievement=5475/lets-do-lunch-orgrimmar. Nie może zostać ukończony ponieważ quest http://www.wowhead.com/quest=26234/stealing-from-our-own#see-also nie zalicza się do achievement.

**Comment by LaveGit** [comment]
Confirmed.

**Comment by armano2** [comment]
duplicate: #1793
