### ISSUE TITLE
[PL][Death Knight][Pet] Ghoul stat scaling

### ISSUE THREAD

**Issue by nevcio** [Atlantiss/BugTracker#4236]
Z dyskusji o simcraft
https://code.google.com/p/simulationcraft/issues/detail?id=767
https://spreadsheets.google.com/spreadsheet/ccc?key=0AjwRbvWnfOyXdFRvTnc5U3hubkJjQWJobEtyTEN1b0E&hl=en_US&pli=1#gid=0
Ghoul powinien miec 476 base strength i 622-933 base dmg
1. Ghoul powinien otrzymywac 1.01 strength dk lub 1.4354 strength dk jesli posiada http://cata.openwow.com/item=43549#teaches-recipe
czyli z glyphem strength ghula = 476 + 1.4354*strength dk
2. Strength zamienia sie w attack power; ap ghula= (2*strength ghula)-20     
3.Minimalny damage ghula = 0.12*ap ghula + 622
   Maksymalny damage ghula = 0.12*ap ghula + 933

Nie pisza tam za duzo o staminie, ale wykonujac obliczenia na tych danych mozna dojsc do wniosku ze ghul powinien miec 389 base stamina  i scalowac sie z 0.903 staminy dk jezeli dk ma wczesniej wymieniony glyph. Brak tylko informacji o base health ghula. Ale patrzac na filmik
https://www.youtube.com/watch?v=8ETTQL0K-Rw
Dk ma 126k hp, ja na atlantissie dk rowniez mam 126k hp i 5779 staminy.
Zatem moj pet powinien miec 0,903*5779+389= 5607 staminy = 56070 health ze staminy.
Ghul dk z filmiku ma 81237 hp, czyli base health powinien wynosic okolo 25000 health.

**Comment by nevcio** [comment]
bump

**Comment by Lenox07** [comment]
Jako że zrobiłem "duplikat" to napisze tutaj.
Z linkami jest właśnie problem bo ciężko coś znaleźć odnośnie bazowych statów. 
http://forums.elitistjerks.com/topic/124191-unholy-dps-my-friend-of-misery-430/
===Pet (Timmy Stats)===
While our Ghoul is described as inheriting 100%/140%(glyphed) strength from the player, data collection has shown a distinct variation. In observation, an unglyphed Ghoul appears to have closer to ~101% strength and a glyphed Ghoul has closer to ~143%. Linear regressions performed with samples of player data place the Ghoul's base AP at ~931.
Z tematu EJ widać iż przelicznik str może wynosić 1.4 albo te 1.43 oraz bazowy str 476 bo 476x2-20=932.
Jedynie nie mogłem nic znaleźć odnośnie bazowego dmg (622-933) oraz przelicznika ap->dmg

logi 4.3.4 Ultraxion
http://www.worldoflogs.com/reports/j6rpxnaj0n3ubbze/sum/damageDone/?s=2184&e=2381
Ghul robił 10043 dps a dk 32504 dps.
logi 4.0.6 valiona
http://www.worldoflogs.com/reports/jokfm4griz0mykk9/sum/damageDone/?s=3215&e=3598
Ghul robił 5053 dps a dk 15855 dps.
Czyli gear/patch nie wpływa zbytnio na stosunek dps ghul/dk.
U nas bijąc kukłe z bufami (bok bom horn i jedzeniem):
ghul robił 3601 dps a dk 15953 dps.

**Comment by nevcio** [comment]
bump

**Comment by nevcio** [comment]
https://www.youtube.com/watch?v=Tf1LiwVwfTE
widzimy ze dk ma okolo 8500 strength
W minucie 16:20 dk juz nie ma buffa od jedzenia wiec zalozmy ze ma okolo 8400 strength 
Zatem ghoul powinien bic:
od (1.4354*8400+476)*2*0.12+622 = 3630 do (1.4354*8400+476)*2*0.12+933=3941
(powinien bic 3630-3941)
Kukla ma okolo 12k armor czyli okolo 31% redukcji wiec ghul powinien bic kukle od
3630*0.69=2505 do  3941*0.69=2719
Na filmiku w momencie 16:20 widac ze ghul bije okolo 2700-2900 czyli mniej wiecej zgadza sie z obliczeniami w granicach bledu

**Comment by Lenox07** [comment]
U nas mając 7408 siły ghul bije aż 1789-1817.
1100 siły daje około 189 dmg przed redukcją armoru.
![wowscrnshot_082615_201615](https://cloud.githubusercontent.com/assets/9517740/9502066/534dac78-4c2f-11e5-8f2d-77503cbb8f8c.jpg)

**Comment by nevcio** [comment]
bump

**Comment by nevcio** [comment]
.

**Comment by Aviannaqt** [comment]
Powinno działac dobrze od reva 4667.
