### ISSUE TITLE
[EN][NPC][Orgrimmar] First Sergeant Hola'mahi

### ISSUE THREAD

**Issue by Birdseye123** [Atlantiss/BugTracker#4238]
The NPC [First Sergeant Hola'mahi](ID=12795) doesn't sell the item Insignia of the Horde.
This URL shows that it is supposed to be sold by this vendor. http://cata.openwow.com/npc=12795#sells:100+1
![](http://wow.zamimg.com/uploads/screenshots/resized/429368.jpg)

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
