### ISSUE TITLE
[EN][Quest][Badlands]

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4239]
not if you wrote the message as you wish just try somehow to communicate in my own language what happens, for me it is very important that all these tasks and those that follow in this area are listed as soon as possible for my achievement thanks.

the list of erroneous missions are:
The Sentinel's Game
http://www.wowhead.com/quest=27886/the-sentinels-game#comments
The Warden's Game
http://www.wowhead.com/quest=27885/the-wardens-game
Lifting the Veil
http://www.wowhead.com/quest=27770/lifting-the-veil
Eric, the Utility Dwarf
http://www.wowhead.com/quest=27828/eric-the-utility-dwarf
Baelog, the Glass Cannon
http://www.wowhead.com/quest=27834/baelog-the-glass-cannon
Olaf, the Big Fella'
http://www.wowhead.com/quest=27835/olaf-the-big-fella
The Day that Deathwing Came
http://www.wowhead.com/quest=27713/the-day-that-deathwing-came
The Day that Deathwing Came: The Real Story
http://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story
The Day that Deathwing Came: What Really Happened
http://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened

**Comment by PierwszyKrytykRP** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by martinelrey1979** [comment]
I do not understand what you're saying

2015-08-14 23:15 GMT-05:00 Pierwszy Krytyk RP <notifications@github.com>:

**Comment by martinelrey1979** [comment]
I do not understand what you're saying

**Comment by Pallitax** [comment]
All of these quests have been reported two or three times already. At least use the search engine before flooding the bug tracker with useless reports that don't follow the guidelines.
