### ISSUE TITLE
[EN][NPC] Elrodan & Aurosalia

### ISSUE THREAD

**Issue by Adunai** [Atlantiss/BugTracker#424]
Problem: Elrodan does nothing. Aurosalia is always a sheep and does nothing.

What should be: Elrodan has to polymorph Aurosalia into various creatures. Aurosalia has to say phrases every time he does so.

Aurosalia says: Will you stop--
Aurosalia says: Stop!

Just before she's transformed ,she'll either say 'Stop', or give the /no or /angry.

Links & proofs: Elrodan on WoWHead (http://www.wowhead.com/npc=18743).
Aurosalia on WoWHead (http://www.wowhead.com/npc=18744).
Screenshot from Atlantiss (http://s20.postimg.org/wz1yqjufx/Wo_WScrn_Shot_112414_050049.jpg).
Screenshot from Kazzak EU (http://s20.postimg.org/fzt0baj8d/Wo_WScrn_Shot_112414_134750.jpg).

Their position was changed in WoD, apparently.

**Comment by Bildo** [comment]
fixed in rev 4294

**Comment by Adunai** [comment]
You have broken it. First, Elrodan should transform Aurosalia, not himself. Second, when Aurosalia says the words, her name does not appear in the chat.
Screenshot (http://i.imgur.com/kKryIwB.jpg).
