### ISSUE TITLE
Ogrim's hammer npc's are missing

### ISSUE THREAD

**Issue by grigman** [Atlantiss/BugTracker#4243]
In Icecown there is this zeppelin flying around 1 in horde side 1 aliance i think both of them miss most important npc since on both of them  i only found 1 npc.
sorry for my bad english i hope its gets fixed :dancers:

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the NPC

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
