### ISSUE TITLE
[PL][NPC] Nefarian strikes back again

### ISSUE THREAD

**Issue by Skeetis** [Atlantiss/BugTracker#4244]
Po ostatnich revach zaczeły dziać się dziwne rzeczy na nefku:

1.Niektóre addy respią się pod platformą.

2.Skacząc na platforme można przelecieć przez nią i wpaść do lawy.

3.Portale(hc) spawnią się pod platformą przez co gracze wpadają do lawy.

4.Podczas dominiona gdy gracz miał full hp padł od heart strik'a który uderzył go za 10k.

5.Mieliśmy przypadek że jedna osoba dostała dmg z electrocuta gdy boss miał 82% ( może być spowodowane tym, że miała dominiona podczas poprzedniego elctrocuta).

6 Niektórzy gracze giną instantowo gdy dostaną dominiona.

7.Ognie na 3 fazie pokazują się pod platformą ( odnawia energie addom) utrudnia to poruszanie się  i przy większej ilości płomieni ciężko jest tego unikać

**Comment by Aviannaqt** [comment]
http://www.worldoflogs.com/reports/rt-o3dgyl7au6hbarcs/sum/damageDone/?s=710&e=1096
http://www.worldoflogs.com/reports/rt-o3dgyl7au6hbarcs/sum/damageDone/?s=5944&e=6225

**Comment by PierwszyKrytykRP** [comment]
https://github.com/Atlantiss/BugTracker/issues/3143

**Comment by Emtec** [comment]
Wprowadziliśmy nowe vmaps lepiej dostosowane do 4.3.4 (wczęśniej tak nie było). Teraz rzeczy które customowo były poprawiane ze względu na źle działające vmaps muszą zostać poprawione. 

Za niedługo dojdzie lepiej poprawione mmaps także, więc problem powinien zniknąć.

**Comment by Bastek** [comment]
W jakim dniu i o której godzinie robiliście Nefariana?

**Comment by PierwszyKrytykRP** [comment]
Czwartek. w przedziale 21-23 czy cuś takiego

**Comment by Skeetis** [comment]
Jeśli chodziło o naszego nefka to od 16 do 18 próbowaliśmy w piątek.

**Comment by Bastek** [comment]
W Sobotę o 16:00 została wgrana stara vmapa dedykowana specjalnie dla Nefariana. Proszę o ponownie sprawdzenie i ewentualną korektę zgłoszenia.

**Comment by Bastion** [comment]
nie działa nadal

**Comment by Tottres** [comment]
addy nadal respią się pod platformą, portale zabijają instantowo bo również pojawiają się pod platformą a jak pojawią się dobrze to i tak jest szansa, że wpadnie się do lawy

sprawdzane dzisiaj tj. 17.08.15

**Comment by Bastek** [comment]
Chyba znaleźliśmy przyczynę powstałych błędów. Proszę o ponowne sprawdzenie.

**Comment by Bastek** [comment]
I jak?

**Comment by Tottres** [comment]
DA sprawdzi w najbliższy poniedziałek

**Comment by Tottres** [comment]
zabiliśmy za pierwszym podejściem, więc za dużo nie potestowaliśmy, ale żadnego buga z wyżej wypisanych przez to podejście nie było - chyba działa :dancer:

**Comment by Bastek** [comment]
Dziękuję za sprawdzenie. W przypadku wystąpienia bugów proszę o ich wypisanie w tym temacie - zrobimy reopen.

**Comment by Bastion** [comment]
combat resy jeszcze ^^
