### ISSUE TITLE
Kindness

### ISSUE THREAD

**Issue by Rettro** [Atlantiss/BugTracker#4246]
Quest used to work, doesn't work now. Mobs dropping quest items just don't drop it. I'm sure that quest is bugged because I did it many times on previous server.

**Comment by pelekon** [comment]
Please add all important information, I mean links to wowhead( link to mobs, qitem).

**Comment by Rettro** [comment]
http://www.wowhead.com/quest=10804/kindness - quest
http://www.wowhead.com/npc=21477/rocknail-flayer , http://www.wowhead.com/npc=21478/rocknail-ripper - mobs
http://www.wowhead.com/item=31373/rocknail-flayer-giblets - quest item, http://www.wowhead.com/item=31372/rocknail-flayer-carcass - second quest item

**Comment by pelekon** [comment]
Q works correctly, I did it 2 min ago.

**Comment by Rettro** [comment]
For me it doesnt drop q items...

**Comment by Rettro** [comment]
i killed like 40 mobs in a row, no one q item, when its like 90% of drop ?
