### ISSUE TITLE
[EN][Talent][DK] Rime

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#4248]
http://cata.openwow.com/spell=49188 r1
http://cata.openwow.com/spell=56822 r2
http://cata.openwow.com/spell=59057 r3

Free Howling Blast or Icy Touch from Rime shoudn't generate any runic power without http://cata.openwow.com/spell=49149 or http://cata.openwow.com/spell=50115, with first of this talents should generate 5rp, with second one 10rp.

You can see it on multiple videos from retail, f.e. https://www.youtube.com/watch?v=FlySOYaKvDs

**Comment by Jenovas** [comment]
Fixed in rev 4631
