### ISSUE TITLE
[EN][Talent][Warrior] Blood Frenzy

### ISSUE THREAD

**Issue by maciekf3** [Atlantiss/BugTracker#4251]
Arms Warrior's <A HREF="http://cata.openwow.com/spell=29859"> Blood Frenzy </A> effect (4% damage) is removed from the target after few crits (First crit applies the effect , the next applies duration to the effect , then duration is shorten and then disappears)  even if the target is still bleeding with <A HREF="http://cata.openwow.com/spell=772"> Rend </A> or <A HREF="http://cata.openwow.com/spell=12867"> Deep Wounds </A>.

**Comment by Jenovas** [comment]
Duplicate
