### ISSUE TITLE
[EN][Item] Warbear Leather

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/BugTracker#4252]
Is it possible to increase the drop rate a bit on warbear leather,
http://www.wowhead.com/item=15419/warbear-leather
from the Shardtooth Maulers in Winterspring,
http://www.wowhead.com/npc=7443/shardtooth-mauler
since some mobs with a higher drop rate are not on the realm?
http://www.wowhead.com/npc=7446/rabid-shardtooth &
http://www.wowhead.com/npc=42336/tainted-black-bear
TY

**Comment by Helbringer** [comment]
This is not how you submit a bug report. You need to say
.What the problem is
.How it should be
.Show your evidence of how it should be
The bug trakcer is not for suggestions, if you have foudn somthing that is wrong, then you say what it is and give proof and evidence that it is wrong.
Thankyou.

**Comment by Quban** [comment]
i've added missing creatures

**Comment by SwimzwithSharkz** [comment]
![ty](https://cloud.githubusercontent.com/assets/12092984/9322399/699134dc-4540-11e5-8fa7-2155441a2514.jpg)
