### ISSUE TITLE
Achievement: Full Caravan

### ISSUE THREAD

**Issue by Demonhunting** [Atlantiss/BugTracker#4255]
The NPC Beezil Linkspanner( http://www.wowhead.com/npc=46022/beezil-linkspanner )
Is supposed to give an option to join the caravan after you finish all the other caravan quests and recruit everyone in the caravan. Instead, he gives the quote "Greetings" and doesn't give option to finish the achievement Full Caravan( http://www.wowhead.com/achievement=5442 ).
![wowscrnshot_081515_183641](https://cloud.githubusercontent.com/assets/13814068/9291133/e88f49aa-437d-11e5-8304-9f95cf437732.jpg)
![wowscrnshot_081515_183725](https://cloud.githubusercontent.com/assets/13814068/9291136/f32a21be-437d-11e5-851a-95f0fe57bcef.jpg)

**Comment by LaveGit** [comment]
Duplicate; https://github.com/Atlantiss/BugTracker/issues/2216
