### ISSUE TITLE
[Quest][Silverpine Forest][It's Only Poisonous if You Ingest It] (Part 2 of 2)

### ISSUE THREAD

**Issue by mara1987** [Atlantiss/BugTracker#4259]
In this quest you need to slain a Forest Ettin (Elite mob) with the help of a quest item provided by the quest giver. The quest works as intended, but when you kill the Ettin in the right way there is no quest completition.

Just need to make the system recognise you completed it.

Thank you.

**Comment by tondiaq44** [comment]
i managed to complete the quest by simply not using the chicken and bursted down the Etin and i received the kill credit.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/366
