### ISSUE TITLE
[PL][Quest][Southern Barrens] Desolation Hold Inspection

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4262]
Gdy rozmawiam z Warlordem Bloodhiltem w Vendetta Point ( http://www.wowhead.com/npc=37679 ) powinniśmy mieć opcje pojechania dalej, bez tego nie można ukończyć zadania
http://www.wowhead.com/quest=24577/desolation-hold-inspection
![wowscrnshot_081615_153647](https://cloud.githubusercontent.com/assets/13817775/9293470/a59b91c6-442c-11e5-9e23-5dbe62ec4384.jpg)

**Comment by Syrnikus** [comment]
Dalej nie działa!!!!

**Comment by therealmikz** [comment]
+1

**Comment by veisse** [comment]
Nadal nie działa, ponadto rozmawiając z docelowym NPC u którego później powinno się ten quest oddać, mamy coś takiego: 
![wowscrnshot_061516_223917](https://cloud.githubusercontent.com/assets/19961033/16096728/969fbf0e-334a-11e6-93c0-f4f63c110ee5.jpg)
Po kliknięciu "continue" nic się nie dzieje. Nie da się zaliczyć warunku "Gar'dul Notified"

**Comment by coba999** [comment]
Same problem

**Comment by Bildo** [comment]
fixed
