### ISSUE TITLE
[EN][Spell][Web] Two Forms not received on RACE CHANGE human -> worgen

### ISSUE THREAD

**Issue by ylluminate** [Atlantiss/BugTracker#4265]
Two Forms is missing when one performs race change from human to worgen.

**Comment by davidrivasdos** [comment]
the same

**Comment by Helbringer** [comment]
Pretty sure this is a known issue, submit a game master ticket in game.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the racial provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
