### ISSUE TITLE
[EN][Talent][Shaman] Maelstrom Weapon

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#4269]
http://cata.openwow.com/spell=51528 r1
http://cata.openwow.com/spell=51529 r2
http://cata.openwow.com/spell=51530 r3

From 4.3 patch maelstrom weapon should proc from fully absorbed atacks, as stated here http://wow.gamepedia.com/Patch_4.3.0

**Comment by Kejmil** [comment]
still bugged, enh unplayable ( ͡° ͜ʖ ͡°)

**Comment by Kejmil** [comment]
pretty funny to see enh with no mana against anything that has absorbs :D
bump

**Comment by BialyADI** [comment]
Maelstrom Weapon can Proc from every attack from Windfury Weapon Proc and no one say about that ;p.
It is bug too.

**Comment by Jenovas** [comment]
Stormstrike* hits will not proc stacks of Maelstrom Weapon. Lava Lash and Windfury attacks will proc it though.

**Comment by Jenovas** [comment]
Fixed in rev 4720
