### ISSUE TITLE
[PL][Quest][Hellfire Ramparts] Hitting Them Where It Hurts

### ISSUE THREAD

**Issue by gretowy** [Atlantiss/BugTracker#4271]
http://www.wowhead.com/quest=29593/hitting-them-where-it-hurts

Wszystkie skrzynie iskrzą się, jednak w całej instancji można podnieść jedynie kilka. Nawet kursor nie zmienia się na tych zbugowanych na trybik. Brak lootu dotyczy przynajmniej 4 osób w pt ( zapisujemy się na dungi w 4 osoby).

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/1205
