### ISSUE TITLE
[PL][Quest][Swamplight Manor]Marsh Frog Legs

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4272]
Nigdzie w okolicy nie ma takiego przeciwnika, nieda się ukończyć 
http://www.wowhead.com/quest=1218/marsh-frog-legs
![wowscrnshot_081715_130104](https://cloud.githubusercontent.com/assets/13817775/9303682/56c93d28-44e0-11e5-9be9-e7a72dd23f6c.jpg)

**Comment by Quban** [comment]
mylisz sie 
http://scr.hu/75h5/a9mae moby
