### ISSUE TITLE
[PL][Spell][Shaman] Unleash Elements

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#4273]
Unleash Elements : http://cata.openwow.com/spell=73680

1.Przykładowo mając Flametongue Weapon na 2 broniach po użyciu Unleash Elements powinno zadać 1 dmg z Unleash Flame(http://cata.openwow.com/spell=73683), aktualnie zadaje 2. Dotyczy wszystkich spelli szamana nakładanych na broń.

2.Od patcha 4.2 spell ten należy do szkoły Nature, więc mając zablokowana tą szkołę nie powinno dać się go użyć.

3.Mając na broniach WF i FT to po użyciu Unleash Elements (Testowane w odległości około 20y):
- Unleash Wind(http://cata.openwow.com/spell=73681) uruchamia z 2 broni Flametongue Attack 
- jeżeli Unleash Wind uruchomi Windfury  to te dodatkowe ataki również uruchamiają Flametongue Attack

Flametongue Attack powinien być zadawany w momencie uderzenia bronią, na której jest założone Flametongue Weapon.

**Comment by Bastion** [comment]
działa tak jak ma działać, ile grasz enhem?

**Comment by Kejmil** [comment]
podobnie jak slynny totem ma dzialac bastion?
a do autora - znajdz jakies dowody ze ma byc tak jak mowisz

**Comment by Bastion** [comment]
a co ma totem do globalnego bugu z double dippingiem?

**Comment by jsembatman** [comment]
Dowody:
1. Opis spella, gdy jest się w enhu + komentarze na wowhead

2. http://www.wowhead.com/patchnotes=4.2.0

3. Z racji punktu 2 + komentarze na wowhead 

4. Flametongue Weapon zakłada się na broń i w momencie uderzenia  bronią (na której jest założony) cel powinien otrzymywać obrażenia fire z  Flametongue Attack.
- Unleash Wind nie jest atakiem bronią na której jest założone Flametongue Weapon
- Ataki z Windfury też nie są atakami z broni na której nałożone jest Flametongue Weapon.

No chyba, że Flametongue Weapon działa inaczej niż napisałem?

**Comment by aneq** [comment]
Ten bug działa też w drugą stronę - ataki z offhanda procują windfury które jest na mainhandzie

**Comment by Jenovas** [comment]
Fixed in rev 4721
