### ISSUE TITLE
[EN][PvP]Rated battlegrounds

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#4275]
So yesterday we assembled 2 teams - 1 horde 1 ally and when we queued nothing happened. We waited queued for like 5 minutes but no que popped :/

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/2315
https://github.com/Atlantiss/BugTracker/issues/3421

**Comment by deadlycalm** [comment]
bump

**Comment by deadlycalm** [comment]
bump, season comes to an end and highest rating is 645
