### ISSUE TITLE
assistance mission

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4276]
the mission marking the fallen malfunctions annex the website and a video to check: https://www.youtube.com/watch?v=Qb-SvxWu7Hg video, website: http://www.wowhead.com / quest = 27845 / marking-the-fallen

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/361

**Comment by Pallitax** [comment]
Aside from being a duplicate...

• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by krecik88** [comment]
duplicate
