### ISSUE TITLE
My game will not open !

### ISSUE THREAD

**Issue by lekgrubi** [Atlantiss/BugTracker#4287]
I really need help here please.
So firstly i downloaded the game from the how to connect to the server from the torrent i waited like 4-5 hours for the game to be downloaded destination was on Local Disk D:/Games folder called, then i downloaded the EXE File, the realmlist was set alredy i coped the wow_434.exe to main folder.
And then when i launch wow_434.exe i see the gameon Task Manager to !. So when i wait like 5-6 minutes and error shows up wich says, This application has encountered a critical error:
ERROR #134 (0x85100086) Fatal condition!
PRogram: D:\Games\World of Warcraft 4.3.4.15595
Atlantiss.eu\wow_434.exe
ProcessID:5476
Failed to Opend requred archive Data/wow-update-base-15211.MPQ with error : 5
Streaming Status: Data Rdy
Wow.mfil download error: Failed to create file 'WoW.mfil' manifest is valid

Press OK to termniate the Application.

**Comment by WickedInsaneMan** [comment]
Right click on the World of Warcraft folder, click Properties, uncheck read-only and click Ok. Make sure the game is not open in task manager first, if it is kill the process. Had the same problem earlier, hope it helps.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by Kejmil** [comment]
rules
