### ISSUE TITLE
[PL][MAGE]  Ring of frost

### ISSUE THREAD

**Issue by Kurwawszystkozajete** [Atlantiss/BugTracker#4289]
Ring of frost działa jak chce. Czasami ktoś się w niego złapie ale w większości przypadków gracze biegają sobie po nim i nic się nie dzieje. Jedno z najmocniejszych cc maga...

**Comment by Kejmil** [comment]
zapewne ma to zwiazek z tym ze ring najpierw musi sie "naladowac"
poza tym https://github.com/Atlantiss/BugTracker
