### ISSUE TITLE
[EN][NPC][ITEM] Level 60 pvp gear vendors

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#4291]
This NPC should sell the level 60 Blue and epic armor sets for honor.
Also the same goes for the allience vendor in stormwind, "Sergent major Clate" should sell the allience version of the lv60 epic and rare pvp gear for honor.
It wasnt until Warlords of Dreanor that this gear was sold at Area 52 for gold. Making wowhead unreliable. In additon to this, make sure that the item sets are added to the game and not the Replica versions.
![wowscrnshot_081815_153303](https://cloud.githubusercontent.com/assets/10423624/9333714/05d1a8f4-45c3-11e5-90cc-0b877ad3607e.jpg)

Proof 
http://wowwiki.wikia.com/wiki/Warlord's_Battlegear
https://www.youtube.com/watch?v=43rYDkS9V1o

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-4291-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
