### ISSUE TITLE
[PL][TALENT][SHAMAN] Improved Lava Lash

### ISSUE THREAD

**Issue by gretowy** [Atlantiss/BugTracker#4293]
Flame shock:
http://cata.openwow.com/spell=8050

Lava lash:
http://cata.openwow.com/spell=60103

Improved Lava Lash
Rank1: http://cata.openwow.com/spell=77700
Rank2: http://cata.openwow.com/spell=77701

Był już temat o rozrzucaniu ale zauważyłem inny problem. Jeżeli próbuję użyć Lava Lash na mobie, który otrzymał Flame Shock właśnie z takiego rozrzucenia, Flame Shock nie rozchodzi się na inne moby. Działa to tylko na moby, na które sam nakładam Flame Shock.

**Comment by Kejmil** [comment]
zapewne "rozrzucony" flame shock ma inne id lub w jakis inny sposob odroznia sie od zwyklego, kiedys bylo tak z serpent stingiem nakladanym u survi huntera przez multishot - nie mozna go bylo przedluzac cobra shotem

**Comment by PierwszyKrytykRP** [comment]
Kejmil jesteś mega. Swoje zgłoszeni a od razu otagujesz, a w innych przypadkach przychodzisz, skomentujesz i wyjebka xD

**Comment by gretowy** [comment]
Btw (sorry za spam) czy jest możliwość otrzymania praw do własnoręcznego tagowania swoich wpisów? Niestety piszę tu ponieważ nie widzę możliwości wysłania czegoś w rodzaju "pw" do osób, które taką możliwość posiadają.

**Comment by Jenovas** [comment]
Fixed in rev 4721
