### ISSUE TITLE
[EN][Spell][ROGUE] Combat Readiness

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#4294]
Combat Readiness state should elapse after 10 sec without weapon strike.

http://cata.openwow.com/spell=74001

**Comment by kadi2** [comment]
Musialo sie popsuc, bo dzialalo pol roku temu.
https://github.com/Atlantiss/BugTracker/issues/1389

**Comment by kadi2** [comment]
No idea how you reproduced the bug, but it works fine on my character.

**Comment by Kejmil** [comment]
for pony
