### ISSUE TITLE
[EN][Dungeon-Cata] Deadmines Vanessa VanCleef (Gauntlet)

### ISSUE THREAD

**Issue by Reddie90** [Atlantiss/BugTracker#4301]
Parties are unable to finish Gauntlet (therefore entire Deadmines dungeon) for Glubtok doesn't spawn at all in to the location. Only his fires appear there and killing them does no good. 

http://wowwiki.wikia.com/wiki/Vanessa_VanCleef_(tactics)

**Comment by maciekf3** [comment]
<A HREF="http://www.wowhead.com/npc=49670/glubtok"> Glubtok </a> appears but then instead of engaging , he just disappears
