### ISSUE TITLE
[En][Quest][Scarlet Monastery] Compendium of the Fallen quest

### ISSUE THREAD

**Issue by worgenman** [Atlantiss/BugTracker#4305]
hi

well u can take the quest, but u can't obtain the book, the book is there and shining but u cant click on it to obtain it, please fix it thank you.

wowhead link:

http://www.wowhead.com/quest=1049/compendium-of-the-fallen

**Comment by Avalain** [comment]
Same issue: https://github.com/Atlantiss/BugTracker/issues/1559
