### ISSUE TITLE
[EN][Quest][Duskwood] Delivery to Master Harris quest

### ISSUE THREAD

**Issue by Nikolay-Asenov** [Atlantiss/BugTracker#4307]
You can take the quest but you can't return it. You cannot speak with Oliver Harris at Raven Hill.

http://www.wowhead.com/quest=26719/delivery-to-master-harris

**Comment by maciekf3** [comment]
Why ? I did it few days ago

**Comment by Nikolay-Asenov** [comment]
I don't know but there was another guy with me and he couldn't complete it too.
