### ISSUE TITLE
[EN][Web] Logging in

### ISSUE THREAD

**Issue by amirhilal** [Atlantiss/BugTracker#4310]
Logging in to the website works but then I get logged out when I try to visit another page on the website

Session/Cookie problems? I tried this on multiple browsers and PCs.

To be specific...
Edge & Chrome , Windows 10
Chrome , Windows 7

**Comment by zeoos** [comment]
More details? Error screenshot and more informations about the url you try to acces.

**Comment by Pallitax** [comment]
This problem should be fixed now.
