### ISSUE TITLE
[PL][Death Knight][Pet] Ghoul base stats and scaling

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#4315]
https://github.com/Atlantiss/BugTracker/issues/4236
Zakładając że informacje z simcrafta są wiarygodne to ghul bije za mało oraz ma za dużo bazowego hp.
"Ghoul powinien mieć 476 base strength i 622-933 base dmg" 
Na postaci bez itemów i buffów w zakładce peta ghul na dmg 322-365 oraz 1812 ap.

"1. Ghoul powinien otrzymywac 1.01 strength dk lub 1.4354 strength dk jesli posiada ghyph
czyli z glyphem strength ghula = 476 + 1.4354strength dk.
2. Strength zamienia sie w attack power; ap ghula= (2strength ghula)-20
3.Minimalny damage ghula = 0.12ap ghula + 622
Maksymalny damage ghula = 0.12ap ghula + 933"
DK ma 6693 str
6693x1,4354=9607 str
9607+476=10083 str
10083x2-20=20146 ap
min dmg = 20146x0.12+622=3039
max dmg = 20146x0.12+933=3350
U nas w zakładce pokazuje 16252 ap oraz 2384-2417dmg
Bazowe hp powinno wynosić około 25k a u nas ma prawie 37k.

http://www.worldoflogs.com/reports/j6rpxnaj0n3ubbze/sum/damageDone/?s=2184&e=2381
Nie wiem dokładnie jak bardzo gear i bufy/debufy wpływają na rozkład dmg skilli ale patrząc na logi z globa ghul robił 10043 dps a dk 32504 dps gdzie u nas (bijąc kukłe z bufami bok bom horn i jedzeniem) ghul robił 3601 dps a dk 15953 dps. Dodatkowo obaj dk byli orkami czyli pet bił o 5% więcej.

**Comment by Jenovas** [comment]
1. Pokazałeś Loga z Ultraxiona... Bossa z contentu 4.3.4 ostatnie insty Cata. 
2. Czy mógłbyś podać jakieś linki? Simcraft już wielokrotnie okazał się nieprawidłowy więc opieranie się tylko i wyłącznie na nim nie wystarcza.
3. Duplikat.

**Comment by Lenox07** [comment]
Podałem logi z 4.3.4 bo u nas jest taki patch i raczej rozkład dmg ghul/dk nie powinien się zbytnio zmieniać. A że jest akurat Ultraxion to z powodu iż jest on DS'owym Pachwerkiem/kukłą.
http://www.worldoflogs.com/reports/jokfm4griz0mykk9/sum/damageDone/?s=3215&e=3598
Tutaj są starsze logi z Valiony i Theraliona na patchu 4.0.6 i widać że dk(Mancheese) zrobił 15855 dps a ghul 5053 dps. Czyli porównując z logami z Ultraxa widać że stosunek dps sie nie zmienił zbytnio dk 32504 do 15855 i ghul 10043 do 5053.

Z linkami jest właśnie problem bo ciężko coś znaleźć odnośnie bazowych statów.
http://forums.elitistjerks.com/topic/124191-unholy-dps-my-friend-of-misery-430/
===Pet (Timmy Stats)===
While our Ghoul is described as inheriting 100%/140%(glyphed) strength from the player, data collection has shown a distinct variation. In observation, an unglyphed Ghoul appears to have closer to ~101% strength and a glyphed Ghoul has closer to ~143%. Linear regressions performed with samples of player data place the Ghoul's base AP at ~931.
Z tematu EJ widać iż przelicznik str może wynosić 1.4 albo te 1.43 oraz bazowy str 476 bo 476x2-20=932.
Jedynie nie mogłem nic znaleźć odnośnie bazowego dmg (622-933) oraz przelicznika ap->dmg

**Comment by Lenox07** [comment]
Dodatkowo patrząc na dmg melee ghula z logów(valiona) średni hit wynosił 4153 gdzie u nas(na kukle) 
3148 (mając na sobie bok bom horn i jedzenie).

**Comment by aneq** [comment]
@Jenovas
Sorry za lekki necropost, ale gdzie konkretnie simcraft okazał się nieprawidłowy? Jeśli simcraft źle simował to była to wina programu a nie danych które ma albo bugów blizzarda (przez cały wotlk simcraft zawyżał dps DK frost w dual wieldzie, przestał zawyżać jak weszło 4.2. i blizzard naprawił buga, który sprawiał, że Killing Machine nie odpalał się z hitów z offhanda)
Ciężko mi wierzyć, że jakiekolwiek dostępne teraz źródło (szczególnie poradniki) są bardziej wiarygodne niż simulationcraft
