### ISSUE TITLE
[EN][NPC][Azhara] Assistant Greely

### ISSUE THREAD

**Issue by Brego55** [Atlantiss/BugTracker#4318]
I have a problem in Azshara. When I'm entering Southern Rocketway Terminus, NPCs, stuff around the tower and players are disappearing. I can't interact and do quests there. I deleted cache folder, but it doesn't help. What's wrong with this area? How to slove this problem? 
This is my video which shows the problem : https://www.youtube.com/watch?v=H7T9A7JIFug

**Comment by Wolffenstein** [comment]
Do you have Twilight Skies in your quest log?

**Comment by Brego55** [comment]
I done it one hour ago.
