### ISSUE TITLE
[PL][NPC] Rogoc <Honor Trade Goods>

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#4319]
Rogoc: http://www.wowhead.com/npc=52033/rogoc
Rogoc sprzedaje towary za honor, lecz ich cena jest za wysoka. Od patcha 4.1 towary powinny kosztować o 50% mniej. (http://www.wowhead.com/patchnotes=4.1.0)
Aktualnie cenu u tego vendora to:
- Hypnotic Dust 200 HP (Honor Points), powinno kosztować 100 HP
- Satchel of Freshly-Picked Herbs 3000 HP, powinno kosztować 1500 HP
- Elementium Ore 2000 HP, powinno kosztować 1000 HP
- Greater Celestial Essence 800 HP, powinno kosztować 400 HP
- Savage Leather 700 HP, powinno kosztować 375 HP
- Embersilk Cloth 2400 HP, powinno kosztować 1250 HP
- Heavenly Shard 1200 HP, powinno kosztować 600 HP

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12980-4319-rogoc-honor-trade-goods-cost/
