### ISSUE TITLE
[PL][Core Mechanic][Northern Barrens]Moby nie ruszają się

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#4320]
W Northern Barrens wszystkie moby stoją nieruchomo w miejscu. Powinny chodzić.

Tak jest u nas: https://youtu.be/6fAqd65JVx4

Tak powinno być: https://www.youtube.com/watch?v=eh0gX-S4FSE

**Comment by Bildo** [comment]
jest to zamierzsone dzialanie poki co
