### ISSUE TITLE
[PL][Quest][Tanaris] Maul 'em with kindness

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4322]
Nie można zaatakować ogrów(one nas tak)
![wowscrnshot_082115_123257](https://cloud.githubusercontent.com/assets/13817775/9424304/05132168-48e8-11e5-9133-2dd54713cdd8.jpg)
http://www.wowhead.com/quest=24963/maul-em-with-kindness
https://www.youtube.com/watch?v=Ikd-Y0EZPmg

**Comment by armano2** [comment]
duplicate:#2207
