### ISSUE TITLE
[EN][NPC] Dareth <Druid Trainer> 

### ISSUE THREAD

**Issue by Topinas** [Atlantiss/BugTracker#4326]
Hello!

So added in patch 4.1.0 there should be worgen druid trainer right outside the gates of Ironforge.

But he is missing.

**Comment by LordKnightCecilo** [comment]
Original Poster forgot the link - http://www.wowhead.com/npc=52335/dareth

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8202-4326npc-dareth-druid-trainer/?p=34599
