### ISSUE TITLE
[EN][Quest] Avruu's Orb

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#433]
**Avruu's Orb** (http://www.wowhead.com/quest=9418) can't be completed because when interacting with **Haal'eshi Altar** (http://www.wowhead.com/object=181606), it doesn't spawn **Aeranas** (http://www.wowhead.com/npc=17085), so you can't continue on with the quest.

How it should work is that when you interact with **Haal'eshi Altar** (JUST interacting, not clicking the dialogue option), **Aeranas** should spawn next to it, and when you click the dialogue option on **Haal'eshi Altar**, script for **Aeranas** should start. He should talk for a bit, and then turn hostile, and then you need to fight him, but once his HP reaches 30%, the fight should stop, then he talks some more, and after that you can turn in the quest.

Here's the quest in action - https://www.youtube.com/watch?v=pGJ_bxkkc8c

**Comment by Satyr87** [comment]
NO ! its not working , tried it like an hour ago , the altar has a dialogue window with 1 dialogue option , you can click it 100 times and nothing happens
thats the situation currently with this quest

**Comment by silverches** [comment]
I can also confirm that it is not working.

**Comment by grzott** [comment]
Confirm, this quest still not working

**Comment by Avalain** [comment]
Again, comfirm - quest still not working properly 12.02.2015

**Comment by ThiefOfNavare** [comment]
Quest not working 16.03.15. Dialog box opens but no spawn!

**Comment by Maczuga** [comment]
Not working.

**Comment by meowmewo** [comment]
STILL not working as of 06.05.2015

**Comment by Dean1989** [comment]
confirmed, not working

**Comment by Crusaderz** [comment]
Still not working

**Comment by nenormalen** [comment]
22.09.2015 Still bugged

**Comment by Satyr87** [comment]
oh crap maybe we missed something , what faction you people are ? this quest worked for me when i was playing ally , stopped when i tried to do it on horde side

**Comment by nenormalen** [comment]
Well, I am alliance mate. Never tried it as a Horde, despite the fact I have 1 - 85lvl horde character. Actually in Hellfire this one quest is the only one which is bugged, all other quests worked properly so I have the achievement for Hellfire questing.

**Comment by Bildo** [comment]
fixed
