### ISSUE TITLE
[ENG][NPC] Mobs all over the game are not walking around

### ISSUE THREAD

**Issue by Todoran** [Atlantiss/BugTracker#4330]
Mobs are suposed to move around but they are stayng in 1 place and dont move they just sit there.... 

![wowscrnshot_082315_142450](https://cloud.githubusercontent.com/assets/8948853/9428014/0c53032e-49a3-11e5-8e1f-99ca51ef76c5.jpg)

**Comment by Anhaeyn** [comment]
This was turned off for some time, because they uploaded new v-maps. They'll enable mobs walking soon.

**Comment by Todoran** [comment]
ok thank you good to hear it.... :dancer:

**Comment by krecik88** [comment]
Actually this is more related with server diff.
Closing issue, when we got fixed problems with diff we are going to enable random movement again.
