### ISSUE TITLE
[EN][Raid] Throne of the Four Winds, Conclave of Wind (Heroic)

### ISSUE THREAD

**Issue by abominalizer** [Atlantiss/BugTracker#4333]
Rohash (http://www.wowhead.com/npc=45872/rohash) should not melee hit anyone.

On heroic you need melee to stand on his platform since melee will get raped on Anshal, making this fight way harder since Rohash is melee swinging his primary aggro target ( if he is in melee range).

**Comment by Exertt** [comment]
This is serious bug that heavily increases the difficulty of the encounter and making it possible only for small amount of raid compositions, making melees absolutely useless. This needs to have a higher priority.

**Comment by Aviannaqt** [comment]
Fixed in rev. 4673
