### ISSUE TITLE
[EN] [Horde] [Stonetalon Mountains] [Quest] In Defence Of Krom'gar Fortress

### ISSUE THREAD

**Issue by HelAmarth** [Atlantiss/BugTracker#4334]
In Krom'gar Fortress the npc Chief Blastgineer Bombgutz asks to use one of the heavy guns to kill 15 Gnomish Flying Machines and 25 Gnome Wing Commanders. These guns should be on the left on a grey balcony but there are none. Even if I reloaded the game and also logout and login again it still doesn't work.

Quest page from wowhead: http://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress

Quest page from cata.openwow: http://cata.openwow.com/quest=26058

Video of completed quest from YouTube: https://www.youtube.com/watch?v=JE8xTVZa90Y

**Comment by Bildo** [comment]
duplicate
