### ISSUE TITLE
[EN][Quest - WotLK][Howling Fjord] Sorlof's Bounty

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#4337]
Slay Sorlof using the Big Gun and recover Sorlof's Booty. Return Sorlof's Booty to Captain Ellis aboard the Sister Mercy.

    Inv box 01 [Sorlof's Booty] 

--------------------------------------------------------------------------------------------------------------------------------
The whole ship has phasing issues while traveling which makes it extremely difficult to complete the previous quests.  This particular quest is not completable because you cannot use the cannon aboard the ship.  I tried killing Sorlof without the cannon but he did not drop the quest item.

**Comment by morgs71** [comment]
The bounty spawned on the ground this time for me but the cannon is still not usable

**Comment by Tj20** [comment]
#537
(preq: #1877)
