### ISSUE TITLE
[EN][Gnaw][Death Knight]

### ISSUE THREAD

**Issue by Kubelecer** [Atlantiss/BugTracker#4338]
The gnaw spell will become "locked" if used when the ghoul doesn't have enough energy, which makes it impossible to cast Gnaw for an undefined amount of time even when the ghoul has enough energy and has no CD. Tried with autocast, macro and manual click on the pet bar. Error "Ability is not ready yet" is shown

http://cata.openwow.com/spell=47481

**Comment by Jenovas** [comment]
Should be fixed with next update.
