### ISSUE TITLE
[EN][Spell][class] Wild Growth bugs with haste

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#4339]
I have 13.12% haste and my wild growth ticks 8 times
13.12% haste with full nature grace = 30.09% haste - my wild growth ticks 9 times
13.12% haste + nature grace + beserking(troll)= 56.10% haste  - my wild growth ticks 8 times

This only happens with Wild Growth, for some reason with higher amounts of haste we dont get more ticks.

**Comment by Jenovas** [comment]
Did a test on the main realm.
Druid resto with 13.37% of haste from gear.
13.37% + Nature Grace = 30.37%
Wild Growth ISNT bugged because it ticked 9 times.
Closing the issue.

**Comment by xolon** [comment]
Read the whole post again, he said that his 13.12%+nature grace do give 9 ticks, but if he uses berserking ( troll racial) on top of that it will give 8 ticks instead 10-11

**Comment by Jenovas** [comment]
I will reopen the issue and change it cause ONLY wild growth is bugged by haste and no other druid HoT.

**Comment by Jenovas** [comment]
Fixed in rev 4580

**Comment by phanttom** [comment]
so sir rather than fixing wild growth according to haste now it ticks once even if u have 1M haste

**Comment by phanttom** [comment]
so it ticks the last tick as fist one and as u know wild growth keep ticking and decrease and at last tick will be too low heal and now it ticks only one time at start same as  (the last tick low healing ) 270hp mine

**Comment by Kejmil** [comment]
poor you, mean dev keeps destroying your class rather than fixing it
oh wait

**Comment by phanttom** [comment]
nah they fixed it finally :D i know they are trying hard i was giving them details what was happening nothing more  anw master shapeshifter need to be fixed for now and druid will be perfect
