### ISSUE TITLE
[PL][Quest][Hillsbrad Foothills] Can You Smell What the Lok'tar is Cooking?

### ISSUE THREAD

**Issue by QuHard** [Atlantiss/BugTracker#4340]
Witam,
Mam problem z questem:
http://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking

Jestem w miejscu, gdy powinien być owy npc Kingslayer Orkus, lecz go nie ma przez co nie mogę oddać questa i wziąć następnego.

Dziękuje za pomoc.

**Comment by armano2** [comment]
duplicate: #3807
