### ISSUE TITLE
[PL][Location][Borean Tundra] Error 132

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4341]
W Borean tundra występuje problem który sprawia że gra sie crashuje, jest to blad gry bo inne postaci dzialaja. Gra crashuje się 3 sekundy po zalogowaniu. Proszę też o teleportacje postaci do innego miejsca żeby móc grać
![wow](https://cloud.githubusercontent.com/assets/13817775/9441531/fb3151d4-4a76-11e5-9494-ecbf54583fd9.png)

**Comment by magromo** [comment]
Po unstacku poleciałem tam jeszcze raz i odkryłem, że problem pojawia się podczas logowania bądź  powrotu z dungeona, czyli za każdym razem gdy wczytuje się obszar, nie licząc momentu lotu zeppelinem

**Comment by Azeratus** [comment]
Mam dokładnie ten sam problem w tym samym miejscu, też proszę o teleportacje postaci. Nick: Renihis

**Comment by Kibito22** [comment]
Również proszę o teleport z tego samego powodu. Nick: Scypius

**Comment by Tj20** [comment]
#3905
