### ISSUE TITLE
[PL][Quest][The Slave Pens] Lost in action

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4342]
Po zagadnięciu powinno zostać zaliczone jego odnalezienie a nie jest
http://www.wowhead.com/quest=9738/lost-in-action
![wowscrnshot_082315_015323](https://cloud.githubusercontent.com/assets/13817775/9441606/66543120-4a77-11e5-9e7e-5b1cd01ed8c6.jpg)

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/1169
