### ISSUE TITLE
[PL][Spell][Shaman] Flametongue Weapon

### ISSUE THREAD

**Issue by jsembatman** [Atlantiss/BugTracker#4348]
Flametongue Weapon: http://cata.openwow.com/spell=8024

Flametongue Weapon założone na broni off-hand bardzo często zadaje obrażenia fire przy uderzeniu bronią z main hand, na której nie jest nałożony. Dodatkowo jeżeli na main hand mamy nałożone Windfury Weapon to do ataków z Windfury również dokładane są obrażenia fire z Flametongue Weapon.

**Comment by Jenovas** [comment]
Fixed in rev 4721
