### ISSUE TITLE
[EN][NPC]Talrich Fortright/Togar

### ISSUE THREAD

**Issue by Pwnzone** [Atlantiss/BugTracker#435]
As of 4.1 you can purchase 250 Justice Points for 375 Honor Points from Edlan Halsing (Alliance) and Rogoc (Horde). You can purchase 250 Honor Points for 375 Justice Points from Talric Forthright (Alliance) and Togar (Horde). Vice versa, too.
http://us.battle.net/wow/en/blog/2657803

It is not happening...at least for horde side.

**Comment by Navedonar** [comment]
.
