### ISSUE TITLE
[EN][Quest][NPC][Durotar] Griswold Hanniston

### ISSUE THREAD

**Issue by Varidelil** [Atlantiss/BugTracker#4352]
http://www.wowhead.com/quest=25258/griswold-hanniston
http://www.wowhead.com/npc=39353/griswold-hanniston

Griswold Hanniston is not where he's supposed to be and I can't locate him anywhere around the area. This quest is impossible to complete as of right now.

**Comment by aje** [comment]
this npc is present

**Comment by pipesbez** [comment]
The npc is present but still "Friendly" and doesnt complete the quest .

**Comment by Daknyas** [comment]
Confirmed. The NPC is present but you can't attack it cause it's friendly.

**Comment by aje** [comment]
he is friendly but he can becomes enemy if you have the quest: right click on him, talk to him and he becomes enemy
