### ISSUE TITLE
[EN][Achievment][Azshara] Glutton for fiery/shadow punishment

### ISSUE THREAD

**Issue by agardosh** [Atlantiss/BugTracker#4353]
Those three achievement, the two in the title and the third one, Icy punishment, are all related to the quests given out by Archmage Xylem's, but only Icy punishment is obtainable. I also noticed that the stacks given out in the trials required for the achievements are given as a Debuff in the non-obtainable achievements, and as a Buff in the obtainable one.

**Comment by armano2** [comment]
duplicate: #1441, #1440
