### ISSUE TITLE
[EN][NPC][Utgarde Keep] Dark Ranger Marrah

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4357]
This NPC is missing.
According to gamepedia.com:

Dark Ranger Marrah is a dark ranger fighting against the Vrykul in Northrend, located in the Utgarde Keep in Howling Fjord.
She appears only for Horde groups, and runs up to the group inside the instance after the players enter and start moving towards the mobs for the first pull.

http://www.wowhead.com/npc=24137/dark-ranger-marrah

She should give 3 quests:
http://www.wowhead.com/quest=30112/a-score-to-settle (added in patch 4.3.0)
http://www.wowhead.com/quest=13206/disarmament
http://www.wowhead.com/quest=11262/ingvar-must-die

**Comment by Quban** [comment]
fixed in rev http://atlantiss.eu/changelog#rev4678
