### ISSUE TITLE
[EN][Spell][Druid] Wild Growth is completely broken. [revision 4581]

### ISSUE THREAD

**Issue by tomelajt** [Atlantiss/BugTracker#4360]
The other day when I played my level 50 druid, Wild Growth was working fine, but when I logged on today, this morning, it didn't work at all. It just ticks once and for like 50 healing @ level 60.

P.S; this is my first bugtracker report, so if I missed anything, let me know.

**Comment by aneq** [comment]
well the tagging is slightly off.
change it to [EN][SPELL][DRUID] and it will be fine
also a openwow link to the spell would be nice, tho since its a fresh report i doubt it will be neccessary

**Comment by Jenovas** [comment]
I will have a look at it today.
How much haste do you have? 0?

**Comment by tomelajt** [comment]
Currently I have 3% haste.
And thanks aneq for the response.

**Comment by phanttom** [comment]
ye its broken even at 85 reaching 112% haste u get 6 ticks of wild growth i think at 85 above 35% haste wild growth will start to bug and decrease in its ticks

**Comment by phanttom** [comment]
actually was wrong now it ticks one time bugg like hell and not an ordinary one tick its the lowest one 270 hp pro i cant even save a rat in dungon :D

**Comment by Jenovas** [comment]
Fixed in rev 4582

Totally my fault I did something like this 
GetTickNumber() - 1 * 0.06 
instead of this 
(GetTickNumber() - 1) * 0.06
and it broke the spell.
