### ISSUE TITLE
[EN] [Quest] [Stonetalon Mountains] In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by Umanaar** [Atlantiss/BugTracker#4361]
Hey, i just tried this quest a few days ago but it's not working. You need to accept it at the NPC Chief Blastgineer Bombgutz but you simply can't perform the task (Destroy 15 Gnomish Flying Machines or Bombers and 25 Gnome Wing Commanders) because there is no gun to shoot with near the NPC. 
Here is an image and a video about the quest below. 
![217867](https://cloud.githubusercontent.com/assets/13934330/9499459/3f532a06-4c28-11e5-97ea-12323e5d3319.jpg)

http://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress#videos:id=49723

**Comment by vragni** [comment]
still buged
