### ISSUE TITLE
[EN][Quest][Dustwallow Marsh] A Shambling Threat

### ISSUE THREAD

**Issue by Umanaar** [Atlantiss/BugTracker#4362]
Hey, there is a quest in D.Marsh which can be picked up at the NPC Krog in Brackenwall Village. Here is the exact task: Slay 7 Withervine Creepers or Withervine Ragers in the marsh north of Brackenwall Village. The problem is that the quest accepts/counts only the killing of Withervine Creepers and the Ragers's don't. 
Here is a video about the quest:  http://www.wowhead.com/quest=26682/a-shambling-threat#videos:id=67939

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7443-4362quest-a-shambling-threat/
