### ISSUE TITLE
[EN][Talent][Druid]Nature's Grace

### ISSUE THREAD

**Issue by Fakeaccent** [Atlantiss/BugTracker#4363]
Nature's Grace provides no haste bonus for Rejuvenation. As shown in the combat log, the talent fails to activate after casting Rejuvenation, though works just fine after casting Regrowth, Moonfire or Insect Swarm.(tested)
I removed the Regrowth and Nature's Grace buffs after casting Regrowth so the comparison between Rejuvenation and Regrowth can be seen.

![wowscrnshot_082615_101507](https://cloud.githubusercontent.com/assets/13984638/9500654/7b310810-4bdb-11e5-8bf9-88f7a6f176a7.jpg)

**Comment by phanttom** [comment]
u need 1779 haste + nature grace to see 6 tick of rejuvenation so depends on ur haste rating sometimes it stays 5 ticks but ur instant rejuvenation ( first tick) increased than previous that u had... its working fine

**Comment by Fakeaccent** [comment]
I'm not referring to rejuvenation ticks here, but to overall haste bonus, other abilities should be affected as well by the buff and they're not. For instance casting Nourish usually takes me 2.42 seconds with 3.15% haste. After casting Regrowth my haste is increased by 15% and it only takes 2.11 seconds to cast Nourish. After casting Rejuvenation nothing happens. So it IS an issue.

**Comment by Kejmil** [comment]
you mean that it should proc from rejuvenation? i don't see this spell included in tooltip:
"You gain 15% spell haste after you cast <b>Moonfire, Regrowth, or Insect Swarm</b>, lasting 15 sec."

**Comment by Fakeaccent** [comment]
You are right, I must have been seeing things.
