### ISSUE TITLE
treasure chests

### ISSUE THREAD

**Issue by Starterror** [Atlantiss/BugTracker#4366]
its been already too long with this bug.i know it already for more than 2 weaks.you can't open any chests what so ever...pls fix it

**Comment by Helbringer** [comment]
This is not how you submit a bug report.

**Comment by Kejmil** [comment]
^ reason of closing

**Comment by Starterror** [comment]
i've seen this before...you guys almost want the one that reports a bug to have PHD in something like reporting bugs.for the developers in atlantis team GUYS GO IN GAME AS REGULAR PLAYERS AND TRY OPEN A CHEST!THEN YOU WILL SEE YOU CAN'T...WHY?!CUZ IS A FREAKING BUG!!!and for the rest...really no comment YOU GUYS SUCK!

**Comment by Bildo** [comment]
kthxbye then
