### ISSUE TITLE
[EN][DEATH KNIGHT][Revision 4582] Mastery is not working properly.

### ISSUE THREAD

**Issue by tomelajt** [Atlantiss/BugTracker#4367]
I've noticed that on my Blood death knight I don't get the shield from the mastery whenever I heal myself with Death Strike. It worked when I respecced, but after I logged in again it stopped working.

http://cata.openwow.com/spell=77535

I've contacted a GM aswell and he told me to do a bugtracker.

Edit: I changed my second specc to blood now. The mastery seems to be working again when I changed to my other spec. Also tried to relog and it still worked.

**Comment by Kejmil** [comment]
remember that you have to be in blood presense to receive mastery shield

**Comment by aneq** [comment]
This is one weird bug. @tomelajt certainly isn't talking out of his ass on this one. I had this bug on my priest - mind blast wasn't consuming any shadow orbs. When I saw this ticket i hopped on my priest to see if those issues might be connected. After that the orbs were not proccing at all. After changing specs everything worked fine. I wasn't able to reproduce the "relog broke it again" part. After I relogged everything was fine. It happened to me once but does not happen any more. Do you have a dual spec on your character?

**Comment by tomelajt** [comment]
Yeah aneq, I do. Now that you mention dual spec, I think it broke when I purchased it.
Also forgot to mention that the GM that helped also reseted my auras, told me to log out and delete the cache folder, but it didn't work. It only seems to work when I respecc.

**Comment by Jenovas** [comment]
Did you try cleaning both of your specs?

**Comment by tomelajt** [comment]
Yes Jenovas, I cleaned both of my speccs and the mastery is currently working on both of the talent trees (I have the exact same talents on both of them).
I don't know what I did but it works properly for now. It usually stops working when I've been offline for a while, so I'll have to get back and see tomorrow if it's still working.

**Comment by Jenovas** [comment]
Sure thing. Thx for the tests.

**Comment by tomelajt** [comment]
It's still working as it should be working. I have no idea what happened before, but it's seem to have fixed itself now.
