### ISSUE TITLE
What the hell?

### ISSUE THREAD

**Issue by MandrarK** [Atlantiss/BugTracker#4370]
I was on a dungeon on Thrallmar, when te server just disconnected me and my party mate. After this, I've logged again and, my character was a Ghost, in Orgrimmar. And I can't ress, because I can't find my body. Can someone unstuck me, please? A pic of what just happened:
![wowscrnshot_082715_013154](https://cloud.githubusercontent.com/assets/12882321/9512647/7d8bfd74-4c5b-11e5-821c-b3786767b542.jpg)

**Comment by LaveGit** [comment]
Just use a spirit healer and wait 10 minutes.

**Comment by Anhaeyn** [comment]
Or use /script RepopMe () in chat. Should work.
