### ISSUE TITLE
[PL][Quest][Dragonblight] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by effects79** [Atlantiss/BugTracker#4372]
Quest mounta przyzwać się da.
Jednak przy probie wzięcia pasażera pisze "You can't do that yet",
nawet gdy wszystkie moby w okolicy zostaną wyczyszczone.

**Comment by maciekf3** [comment]
Spróbuj na innym NPC , podleć bliżej

**Comment by effects79** [comment]
Wszystkiego probowalem. Zawsze to samo: "You can't do that yet".

**Comment by armano2** [comment]
duplicate: #2437
