### ISSUE TITLE
[PL][Quest][Borean Tundra] Bring 'Em Back Alive

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#4374]
Po użyciu nic się nie dzieje i kodo lezy
http://www.wowhead.com/quest=11690/bring-em-back-alive
![wowscrnshot_082515_193829](https://cloud.githubusercontent.com/assets/13817775/9522608/edff0ebe-4cd5-11e5-9331-addb3766fd75.jpg)

**Comment by armano2** [comment]
dupliate: #1994
