### ISSUE TITLE
Lack of Vines

### ISSUE THREAD

**Issue by Majertn** [Atlantiss/BugTracker#4379]
Ther is a Huge Lack Of Vines in Many Areas ! For an Example : I found Only 1 Iron Deposit In Feralas! And In Durotar Ther is a lack in Cooper Deposits Too !

**Comment by Helbringer** [comment]
This is not how you submit a bug report. This is also a well known and reported issue.
https://github.com/Atlantiss/BugTracker

**Comment by armano2** [comment]
already reported: https://github.com/Atlantiss/BugTracker/issues?q=is%3Aopen+is%3Aissue+label%3AProfessions+label%3AGameobject
