### ISSUE TITLE
[PL][Class][Death Knight] crit chance gargulca

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#438]
http://www.wowwiki.com/Patch_4.3.0
"Death Knight pets now properly inherit their master’s crit and spell penetration stats."
Ghoul został naprawiony ale Gargulec nadal nie dostaje naszego crita a powinnien.

ss z ptr: http://imgur.com/48II3fI

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
