### ISSUE TITLE
[EN][Talent][Paladin] Judgements of the Wise

### ISSUE THREAD

**Issue by WickedInsaneMan** [Atlantiss/BugTracker#4381]
Judgements of the Wise (http://cata.openwow.com/spell=31878) should proc on cast rather than on hit as seen here: http://wow.gamepedia.com/Judgements_of_the_Wise and here http://forums.elitistjerks.com/topic/125329-prot-43-send-me-on-my-way/ (the note under "Stat Overview")
Judgements of the Bold (http://cata.openwow.com/spell=89901) works as intended by proc'ing on hit.

(Forgot to mention what this means)
In case Judgement misses you do not get the buff and you get no mana regen. This is important mostly for undergeared Prot Paladins that cannot get the 8% hit cap and end up starving for mana.

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
