### ISSUE TITLE
[EN][Raid][Firelands] Shannox

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#4385]
Rageface
When he uses Face Rage http://www.wowhead.com/spell=99947/face-rage#used-by-npc
he doesn't stop it when he takes a 30k hit. He is supposed to stop it when this happens.

Riplimb
Ignores the Crstal Traps http://www.wowhead.com/npc=53713/crystal-prison-trap#abilities
Even if he is not affected by the Immolation Trap http://www.wowhead.com/spell=99838/immolation-trap#used-by-npc

**Comment by aneq** [comment]
And here I hoped it will be a "shannox is immune to taunt" bug submission ;D
When Riplimb gets trapped he is immune to traps for the following 25 seconds, so thats probably why he wasnt trapped while on top of crystal trap.
As for rageface, when we tested it on wednesday, face rage was broken properly

**Comment by Nukeey** [comment]
Well when you know he is immune to tant, then why do you need a bug report for it?
And for Rageface, I hit him 3 times with abilities over 30k and he kept doing his attack.

**Comment by aneq** [comment]
I don't know, on 25m we just had 2 mages stay on rageface the whole time and face rage was broken nearly instantly. Worked for us.

**Comment by Nukeey** [comment]
Was 10m for us, maybe there is a difference in the script for some reason.

**Comment by aneq** [comment]
25m requires 45k dmg I think, we were doing 10m on monday and it worked fine as well.. I don't know maybe it got broken recently

**Comment by LaveGit** [comment]
We did 10man two days ago, and Face Rage was broken properly as well.

**Comment by Frainzil** [comment]
Riplimb + rageface both work properly, except their dmg output is way to low (on our try). + The boss Mechanics also work fine, except his melee-dmg output. Traps work really well; tank on riplimb is allowed to reset his stacks after riplimb got into a crystal trap.
