### ISSUE TITLE
Crash on startup!

### ISSUE THREAD

**Issue by crazywow** [Atlantiss/BugTracker#4386]
==============================================================================
World of WarCraft: Retail Build (build 15595)

Exe:      E:\wow\World of Warcraft 4.3.4.15595 - Atlantiss.eu\wow_434.exe
Time:     Aug 28, 2015  5:26:00.359 PM
User:     windows
Computer: WINDOWS7
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal condition!

Program:	E:\wow\World of Warcraft 4.3.4.15595 - Atlantiss.eu\wow_434.exe
ProcessID:	3764

Failed to open required archive Data/wow-update-base-15211.MPQ with error : 5 

Streaming Status: Data Rdy

Wow.mfil download error: Failed to create file 'WoW.mfil'
Manifest is valid.

**Comment by Pallitax** [comment]
Select your WoW folder and untick the "Read only" option.

Also:

• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
