### ISSUE TITLE
[EN][PvP] Too many conquest points after low level Call to Arms battleground.

### ISSUE THREAD

**Issue by Dearkus** [Atlantiss/BugTracker#4392]
After winning a Call to Arms battleground at level 27, I got 100 conquest points. You are supposed to get one.

**Comment by Dearkus** [comment]
![capture](https://cloud.githubusercontent.com/assets/10296506/9560854/269c379c-4e34-11e5-960c-3ecc3889f982.PNG)
A screenshot showing what I am supposed to get, and what I got.

**Comment by Axahus** [comment]
Mi wyświetlało 1 i pół zera, więc możliwe, że tam jest jakiś "niewidzialny margines", który ucina resztę liczby.
