### ISSUE TITLE
Taste for blood

### ISSUE THREAD

**Issue by egostar** [Atlantiss/BugTracker#4393]
taste for blood should ADD 60% critchance and not raise it to 60% critchance. 
![wowscrnshot_082915_114918](https://cloud.githubusercontent.com/assets/14028172/9561408/7ba13584-4e44-11e5-9f0b-5d9f020e8d1f.jpg)

so critrate of overpower should be over 70% and i have the feeling that attackpower is not added to overpower or just a small part of it

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead links for the ability provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by Kejmil** [comment]
also 70 samples is too low to prove anything. 1k or 10k and you have a point
also change title, add links or i will close this

**Comment by Jenovas** [comment]
Works properly. I set my crit chance to be 41% and out of 250 overpowers all were crits.
Closing.
