### ISSUE TITLE
[EN][Item] Discerning Eye of the Beast

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#4395]
On equip effect doesnt work .
http://www.wowhead.com/item=122362/discerning-eye-of-the-beast&bonus=0

**Comment by EnderBlazer** [comment]
Yes it does, just checked. Screenshot:
https://www.dropbox.com/s/4gwvhutqmj273am/a.png?dl=0

**Comment by aje** [comment]
I assume it works with the proof of EnderBlazer
