### ISSUE TITLE
[EN][Gamebreak]

### ISSUE THREAD

**Issue by FeedTheBeat** [Atlantiss/BugTracker#4396]
I discovered a gamebreaking Glitch which im not gonna explain here, because of typical reasons.
Basically what it does is, it gives you a buff from an npc which makes you kind of immune to damage.
I would prefer to write via private messages with a gm or so to talk about it.

**Comment by xolon** [comment]
Is it the one from Sholazar Basin, it doesn't work you will still take damage while you have it

**Comment by FeedTheBeat** [comment]
no it's from Halls of reflection

**Comment by Wolffenstein** [comment]
Send me more info with forum message.
