### ISSUE TITLE
[PL][Class][Death Knight] hit and exp cap of pets

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#440]
http://www.wowhead.com/spell=42650/army-of-the-dead
Ghule z armii nie dostają poprawnie naszego hita czyli nie mają ani hit capa ani exp capa.
http://imgur.com/7y38G04

Ghul-pet także niepełnie dostaje expertise z naszego hita : http://imgur.com/hZOCnjw
Powołując na różne tematy z elitistjerks:

http://forums.elitistjerks.com/topic/71616-unholy-dps-335-king-of-anything/
Ghoul hit rating rounds down. So if you have 7.99% hit rating, the ghoul will have 7% hit rating.
Ghouls gain expertise based on your hit rating. So if you had 131 hit (4%), the pet gains 13 expertise. 263 hit (8%), the pet gains 26 expertise. The Draenei hit aura does not give expertise to the pet.

http://forums.elitistjerks.com/topic/109345-unholy-dps-cataclysm-406-the-missing-frame/
Ghouls receive 100% of your strength, stamina, haste rating, and hit rating. Glyph of Raise Dead causes your ghoul to receive 140% of your strength and stamina.
Ghouls gain expertise based on your hit rating. If you are half-way to the hit cap, then your pet will be half-way to the expertise cap. The Draenei hit aura does not give expertise to the pet.

**Comment by Jenovas** [comment]
Powinno juz dzialac od jakiegos czasu.
Zamykam
