### ISSUE TITLE
Assassination Rogue mastery isn't scaling

### ISSUE THREAD

**Issue by pyza1234** [Atlantiss/BugTracker#4400]
I just noticed that Assassination Rogue mastery http://www.wowhead.com/spell=76803/mastery-potent-poisons isn't scaling with Mastery Rating. I had 65% damage increase yesterday and tommorrow it's stuck at 28%.

![wowscrnshot_083015_105645](https://cloud.githubusercontent.com/assets/14038817/9566439/debd7b2a-4f05-11e5-804d-730914e28008.jpg)

**Comment by meowmewo** [comment]
Its a visual bug.

**Comment by meowmewo** [comment]
Changing talents usually fixes it. And check the mastery icon in ur Spellbook, not in ur char screen. You should be able to see your real mastery there.

**Comment by pyza1234** [comment]
I noticed my damage output drop significantly so I doubt that it's a visual bug.

**Comment by meowmewo** [comment]
If the mastery icon in ur spellbook shows 20% as well.. then its really bugged. But i have the same problem and its just visual bug for me..ive been having it since then did something to talents and resseted everyones talents.

**Comment by pyza1234** [comment]
Had 28% in the spellbook, changed the talents as you said and it's good now. Thank you very much for quick reply.
