### ISSUE TITLE
[PL][Paladin][Spell] Light of Dawn

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#4402]
http://cata.openwow.com/spell=85222
Light of Dawn nie crituje.
![wowscrnshot_083015_160329](https://cloud.githubusercontent.com/assets/9517740/9567577/e1ce8b4e-4f30-11e5-884b-50853d8be75d.jpg)

**Comment by Glare** [comment]
https://github.com/Atlantiss/BugTracker/issues/2651

Znane od dawna.
