### ISSUE TITLE
[ENG][Zone][NPC's]

### ISSUE THREAD

**Issue by Pomosnik** [Atlantiss/BugTracker#4407]
In zone Azshara near the northern rocketstation thet is in north-east azshara there are some dragons thet need proper placement in correct location some of them fly with halfbody on the ground thay need to be little higher then the ground and the blue big dragon thet should be near the tower he is stucking his wing in the tower make him fly far away from the tower.Server is good but pls check every npc in the world for proper positions and fix them good luck.

**Comment by Arturiccc** [comment]
Hey, you could give atleast NPC name which are bugged.
Thanks.
