### ISSUE TITLE
FoS, PoS, HoR questline

### ISSUE THREAD

**Issue by theodoros1996** [Atlantiss/BugTracker#4408]
Jaina inside of FoS does not provide this quest:

http://www.wowhead.com/quest=24499/echoes-of-tortured-souls

thus we cant get access to the PoS or HoR.

**Comment by maciekf3** [comment]
You have to take chain-starting quest in Dalaran first

**Comment by theodoros1996** [comment]
No you do Not have too.

**Comment by maciekf3** [comment]
I took the quest and completed all 3 instances

**Comment by Alastia** [comment]
+1 maciefkf3, the chain starts in dalaran http://cata.openwow.com/quest=24510
