### ISSUE TITLE
catechism stuff do not work for me

### ISSUE THREAD

**Issue by zefera** [Atlantiss/BugTracker#4410]
when I downloaded the client I download a mini client because the torrent doesn't work for me and then when I was done downloading it everything work properly I played about for three months my friend wanted me to play it on another after I try connecting to another server and it didn't work if it started to act this way after that I couldn't choose any of the new races or I couldn't go to any of the places but I do have access to the Wrath of the Lich King content

**Comment by Bastion** [comment]
http://atlantiss.eu/account/expansion
