### ISSUE TITLE
[EN][Spell][Paladin] Word of Glory

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/BugTracker#4411]
http://cata.openwow.com/spell=85673

I tested this on a level 12 holy paladin. All other spells that I currently have deal the correct damage/healing as it's written in their tooltips, except Word of Glory. 

Word of Glory states that it heals 61 per charge of Holy Power consumed. In my experience, it healed for 140-150 per charge, which seems overpowered because at 3 stacks it heals for 450 health while I have 290 health total, and as I said before it doesn't match the tooltip. 

Even with the Walk in the Light passive accounted for (http://cata.openwow.com/spell=85102) it still heals for too much, and I feel that the tooltip should reflect this passive anyway, because it does for other spells like Holy Light. There might be something else I'm missing but there's really not anything to miss since this is a fairly low leveled character so it has only a couple of passives in total.

So, either the tooltip is wrong and it should really heal that much, or the actual amount healed is bugged and way too high.

A sceenshot showing the tooltip and the healed amount as I clicked on the spell while having only 1 Holy Power:

![2015-09-01 14_11_57-world of warcraft](https://cloud.githubusercontent.com/assets/9539181/9603828/bc054f40-50b3-11e5-876a-ee906efeecd9.png)

**Comment by PierwszyKrytykRP** [comment]
Tests at levels lower than 85 are irrelevant

**Comment by Sinyr** [comment]
I know that the balance doesn't matter all that much on lower levels, but it still might indicate that there's something wrong with the way the heal is calculated or the tooltip, right?

**Comment by Frainzil** [comment]
on lvl 85 the amount Word of Glory heals a decent amount. With 8200SP i heal; 1 holy power = a 6700 heal, 2holy power = a 13404 heal and at 3 holy power = a 20000 heal. (without any intellect procs) According to  me there seems nothing wrong with that ^^ It's just that early on in the game spells do hit for quiet a lot, the same is for some other classes where you do insane dmg with some spells.

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.
