### ISSUE TITLE
SERIOUSLY?!

### ISSUE THREAD

**Issue by switchnate** [Atlantiss/BugTracker#4417]
so i heard you guys actually worked, i downloaded the whole 28gb deal to make sure i had no problems, also deleted all my previous wow files. i changed my settings, cache, everything i wasted my time reading on. the "ONLY" solution would be to download 28gb AGAIN, see the lil loop there? i had to create an account to create another forum account to create an account here yet again just to desperately tell you guys to fix your shit. after 2-3 minutes i get a #134 error crash report and the issue is with the updater as it fails HARD

**Comment by Bastion** [comment]
awesome!

**Comment by Helbringer** [comment]
It all works, sounds like you downloaded a virus or somthing. The full cata client is only 11gb, i dont know where you got 28gb from. Its very easy.. download the game here http://atlantiss.eu/pages/1 .
Please read the very "simple" instructions too.

**Comment by switchnate** [comment]
18.6gb, my bad for mistaking it with another one thats been doing the trick so far ;) thats where i downloaded it in the first place, unless youre saying thats where the "virus" comes from

**Comment by switchnate** [comment]
plus nice job on closing a thread after saying it all works but having dozens of people complaining about the same effing mistake and telling them to delete or renaming folders for nothing, some of them dating months back. thats exactly how stuff gets fixed, blame it on the guy who can just print screen everything

**Comment by Jenovas** [comment]
The thread was closed cause this is not how a thread should look like. Please read how it should look and create a new thread or even better go to our forum and search for threads that say what you should do when you get errors.
