### ISSUE TITLE
ToT4W Loot bug

### ISSUE THREAD

**Issue by davesmix** [Atlantiss/BugTracker#4419]
So usually when we do tot4w after al akir we have everyone who died use /script RepopMe() and wait for them to get back before looting. This strategy has always worked for us, but today when we did raid I did same strat waiting for people to get back before looting. Unfortunately when I looted only about 5 people were eligible. I couldn't give loot to the proper person and I had a GM come and see if he could fix. We couldn't get it figured out and he suggested that I submit problem to bugtracker.

**Comment by Aival94** [comment]
#3953 
Only temporal fix for future raids is to tell everyone to hug the crystal but nobody click on it as i think get bugged again

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
