### ISSUE TITLE
all character is ok but when I login to shaman fatal error!! error 132

### ISSUE THREAD

**Issue by razer88** [Atlantiss/BugTracker#4421]

**Comment by cacaocow123** [comment]
i ahve the same problem

**Comment by comnet256** [comment]
Issue possibly related to a nearby improperly handled object (plains of nasam crashed some characters). 
Attempt going to http://atlantiss.eu/shop/vote ,obtaining 5 vote points and then using unstuck for your characters race at http://atlantiss.eu/shop/3 .

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
