### ISSUE TITLE
[EN][Quest][The Slave Pens.] Lost in Action

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4425]
one of npc in this quets dont work when i want to speak is dont happend noting  and i cant finish quest
see my screenshot  http://prntscr.com/8c95ga
see in wowhead http://www.wowhead.com/quest=29563/lost-in-action

**Comment by zeoos** [comment]
https://github.com/Atlantiss/BugTracker/issues/1169

**Comment by iliarakov** [comment]
sorry but i search but dont find this
