### ISSUE TITLE
Poseidus

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#4426]
Is the mount still (rare mob) there in Vash'jir or deleted?

**Comment by Anhaeyn** [comment]
He spawns, at least spawned. (long time ago I was player on this mount which drops from Poseidus) But it's very rare, I think.

**Comment by Helbringer** [comment]
This is a great place to ask questions.

**Comment by Drutmaster** [comment]
Well  #1465 ,,, He was added. He lived about 30 min and then has been deleted. Everyone who had this mount, lost it. Reason was obvious - he was bugged and could be killed only via bugging, so dev decided to delete him. He is still waiting for a proper scripts :)

**Comment by Scrimish** [comment]
how can i get to vashir'r?

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
