### ISSUE TITLE
Scholomance Boss Loot 

### ISSUE THREAD

**Issue by Fernando90232** [Atlantiss/BugTracker#4429]
I've been farming Scholomance for about 2 days now and have witnessed that the bosses drop nothing at all 95% except for greys and trash most of the time. One in specific which I'd like fixed is the Boss 'Lorekeeper Polkelt' which drops the transmog pieces I'm farming for. Maybe with an RDF groups it may work for some reason but soloing Scholomance bugs the loot.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the monsters with a missing loot table provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
