### ISSUE TITLE
[EN][Cosmetic] Stormwind gossip texts (very minor)

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#443]
Many of the NPCs have their flavor texts filled with typos, grammar errors or simply they are not supposed to exist (non-blizzlike ones). They might be some leftovers from unknown sources. Most of them need fixing or deleting.

This is Stormwind portion of these.

-----------------------

Brother Kristoff: His current quote has a typo, also he should randomly say something from the quote list on Wowhead page. (http://www.wowhead.com/npc=1444) [CORRECTION]

-----------------------

Thomas Miller: One of his quotes is blizzlike, but with a typo. He should randomly say things that are listed on his quote list on Wowhead. (http://www.wowhead.com/npc=3518) [CORRECTION]

-----------------------

Topper McNabb / Morris Lawey: They currently don't say anything but they should speak things as listed on the Wowpedia page: (http://wowpedia.org/Topper_McNabb; http://wowpedia.org/Morris_Lawry) [CORRECTION]

-----------------------

Rebecca Laughlin: She just randomly spouts her non-blizzlike quote "Where is it?" (http://www.wowhead.com/npc=5193) [DELETE]

-----------------------

Aldwin Laughlin: Same as above, his quote is a response "I found it!" (http://www.wowhead.com/npc=4974) [DELETE]

-----------------------

Thurman Schneider: Again, a non-blizzlike quote "I want some sweets" without punctuation (http://www.wowhead.com/npc=1429) [DELETE]

-----------------------

Eldraeith: "TelAthir, you are so beauty!" Typos, grammar errors. No, thanks. Doesn't show up in Wowhead quote list, either. (http://www.wowhead.com/npc=5503) [DELETE]

-----------------------

Dockhand: "I am so busy! When I can relax? Where is my money for yestrday?" Can't trace it but it definitely isn't something that was in the retail quote list, never seen it there. (http://www.wowhead.com/npc=29019) [DELETE]

-----------------------

Wright Williams: "Sir, I think we were close with the Lethargy Root in that last poison recipe." No confirmation about its existence. (http://www.wowhead.com/npc=28355) [DELETE]

-----------------------

Miles Sidney: responds to Wright Williams "Remember, kid: You're always more wrong than you think you are. Double It!" No confirmation about its existence. (http://www.wowhead.com/npc=28347) [DELETE]

-----------------------

Wilhelm Strang: "I have new armor. Armor is very cheap!" No confirmation about its existence (http://www.wowhead.com/npc=1341) [DELETE]

-----------------------

Donna and William: They currently do not say anything, nor they are found anywhere in the city.
(http://www.wowhead.com/npc=2532; http://www.wowhead.com/npc=2533)
(http://wowpedia.org/Donna; http://wowpedia.org/William)

------------------------

Ol' Emma: She is currently standing in one place and does not say anything. Should wander around. (http://www.wowhead.com/npc=3520; http://wowpedia.org/Ol%27_Emma)

**Comment by Bildo** [comment]
fixed in rev 4294
