### ISSUE TITLE
[EN][Quest] We're here to do one thing, maybe two...

### ISSUE THREAD

**Issue by dstn3422** [Atlantiss/BugTracker#4430]
So this quest is still bugged, the first report was opened in december of 2014 i guess? and yet every reprot was closed with "duplicate". no issues opened and the quest is still bugged.

**Comment by Aival94** [comment]
As far as i know Duplicate means than someone else has already reported it.Only reported is here: https://github.com/Atlantiss/BugTracker/issues/3761
