### ISSUE TITLE
[EN][NPC][Pet][Hunter] The Razza

### ISSUE THREAD

**Issue by AnakyWacky** [Atlantiss/BugTracker#4434]
The Rare mob The Razza is showing up his normal skin but after you tame it as a Hunter and once you Dismiss and Recall pet or Hearthstone, it reverts back to the old Chimaera skin.

It is supposed to look like this:
http://www.wowhead.com/npc=11497/the-razza#screenshots:id=212591

and it is currently looking like this, which is the old skin:
http://www.wowhead.com/npc=7448/chillwind-chimaera#screenshots:id=77008

**Comment by Gandalf-the-Dank** [comment]
Here is some supporting data.  
Locating "The Razza" 
Taming. (new model)
Dismissing  (new model)
Recalling pet.  (OLD MODEL)
NPD ID: 11497

![wowscrnshot_090415_191348](https://cloud.githubusercontent.com/assets/14133310/9696684/9bedc046-533a-11e5-8386-cfbaa2864d07.jpg)
![wowscrnshot_090415_191409](https://cloud.githubusercontent.com/assets/14133310/9696687/aaf111ba-533a-11e5-8df9-58cbd98f9187.jpg)

![wowscrnshot_090415_191435](https://cloud.githubusercontent.com/assets/14133310/9696689/c383ceb6-533a-11e5-970a-f854596e3347.jpg)
![wowscrnshot_090415_191442](https://cloud.githubusercontent.com/assets/14133310/9696691/c9489ba6-533a-11e5-8a24-2209c7fdd0b9.jpg)

**Comment by XrayAlert05** [comment]
Pet bugged not visible when calling it.
