### ISSUE TITLE
PvP

### ISSUE THREAD

**Issue by thomasrkk** [Atlantiss/BugTracker#4437]
I have tryed many times to get killed by an horde at an alliance low level quest zone, im sick and tried off it that's the reason i stop donate for this server.
Many other i know as well have stop too, becurse this is fucking annoying

i have been in the same area for 45min+ and we can't quest or shit.....
![wowscrnshot_090615_013110](https://cloud.githubusercontent.com/assets/14143447/9701718/2d29ec6c-5438-11e5-8ca9-6be61d70cbf6.jpg)

**Comment by Achiver** [comment]
And why do you report it here on bugtracker ?

**Comment by thomasrkk** [comment]
becure your email isn't to find any where

2015-09-06 10:30 GMT+02:00 Jenovas <notifications@github.com>:
