### ISSUE TITLE
[PL][Death Knight] Blood of The North

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#444]
http://cata.openwow.com/spell=54637

OLD:
* ~~Po użyciu jakiegokolwiek teleporta nasze death runy na powrót stają się blood i należy wykonać respec~~

NEW:
Buguje się po śmierci i daje blood runy bez możliwości zamiany. Pomaga respec

Jak zreprodukowałem?
1. Lecimy do BWD, atakujemy trash
2. Zużywamy wszytkie nasze runki
3. Umieramy z runkami na CD
4. Ressamy się w BWD
5. Runki są blood

Co ciekawe jeśli umrzemy z blood runkami (bez cd) staną się one na powrót death
Wyjście z BWD też przywraca runki do postaci death

http://i.imgur.com/ZI3wAXw.jpg

**Comment by Kejmil** [comment]
problemem wydaje sie nie byc nawet uzycie teleporta ale wczytanie innej mapy w momencie kiedy nasze death runy sa na cd (smierc na dungu czy raidzie + release spirit, wejscie na bg czy arene itd.)
i tak, bug dalej wystepuje

**Comment by Varchord** [comment]
Znaczy sie w momencie kiedy otwierałem ten raport to problem byl bardziej ekstremalny. Nie ważne czy runki były na cd czy nie, zawsze zmieniało je w blood. Mam dodać to co napisałem w nowszym issue tutaj i zamknąć tamten?

**Comment by Kejmil** [comment]
tak, niech wszystko bedzie w jednym miejscu

**Comment by Varchord** [comment]
UPDATE

**Comment by xtul** [comment]
bump

**Comment by Aydien** [comment]
Wciąż zbugowane

**Comment by PierwszyKrytykRP** [comment]
Kejmil, ja to zamknalem poniewaz nikt nie zwracaw uwagi na stare reporty. Otwieralem to na nowo zeby odswiezyc temat https://github.com/Atlantiss/BugTracker/issues/3637

**Comment by Jenovas** [comment]
"Kejmil, ja to zamknalem poniewaz nikt nie zwracaw uwagi na stare reporty. Otwieralem to na nowo zeby odswiezyc temat #3637" - skąd bierzecie takie informacje? Patrzymy, czytamy, nie zawsze jest pomysł jak coś naprawić nie zawsze się udaje.

**Comment by PierwszyKrytykRP** [comment]
Ostatnio zamykane są stare raporty na rzecz nowych z komentarzem, ze sa to duble. Dla mnie to wystarczajcy dowod na to, ze starsze zgloszenia staja sie nic nie warte
