### ISSUE TITLE
[PL][Class][Mage]Mag fire a skalowanie resi (dmg) + haste a crit [Hot Steak]

### ISSUE THREAD

**Issue by M1kox** [Atlantiss/BugTracker#4446]
Dmg fire maga w pvp zle skaluje się z resi co skutkuje zbyt wysokim poziomem obrażeń, nie pierwszy raz już to zauważyłem więc postanowiłem założyć temat ponieważ jest to już bardzo irytujące.
Ogólnie wygląda to tak że: mag fire  363 ilvl dosłownie KOSI postacie mające 3600 resilence (nie zależnie od klasy), dobre wykożystanie cc, pare instant spelli pyro pyro i tyle. Troszkę to przegiete! :p 
Zauważyłem również że talent [Hot Streak] nie skaluje się z critem, a z hastem (przetestowałem to własnoręcznie i muszę powiedzieć że "Instant Pyro" wchodzi co 1 spella przy wysokim poziomie haste, crit tak jakby w ogóle na to nie wpływa. Proponuje to naprawić bo najwyraźniej to źle działa, prosił bym również o ponowne przeskalowanie dmg maga fire z resi! Pozdrawiam!

**Comment by Jenovas** [comment]
Błędne zgłoszenie. Zamykam.

**Comment by Asavel** [comment]
Resi i resisty nie wplywaja na dmg z combu a istant pyro jest dlatego ze przy 23% cryta majac glyph i nalozony critical mass masz cryt cap na targety w novie/ringu wiec wystarczy fireball/pyro+fire blast i procuje
