### ISSUE TITLE
[PL][Guild][Alliance]Guild Glory of the Cataclysm Raider dla Legionu

### ISSUE THREAD

**Issue by M1kox** [Atlantiss/BugTracker#4447]
Witam, otwieram kolejny temat w którym wnoszę prośbę o przyznanie nam gildyjnego Achivementa Guild Glory of the Cataclysm Raider dla gildii Legion, pisałem już z wieloma gamemasterami w tej sprawie i każdy przenosi mnie tutaj! Pozdrawiam

**Comment by Bastion** [comment]
w takim razie ja chce moje axe z nefariana hc

**Comment by Asavel** [comment]
Axy dla bastiona!

**Comment by Bildo** [comment]
ya ya ya i am lorde ya ya ya, zamyrak przeczytaj zasady bt poza tym to duplikat
