### ISSUE TITLE
[PL][WoW Error] crash w black edge mountains

### ISSUE THREAD

**Issue by maruchem** [Atlantiss/BugTracker#4450]
![crash 134](https://cloud.githubusercontent.com/assets/14177764/9732384/c4ff79b6-5623-11e5-919b-b44dd8400732.png)
witam lecac na fm do bem, dostaje crasha, to samo bylo na hellfire, addony wylaczone cache usuniete mimo to problem ciagle sie powtarza. o ile na hellfire byl "czas" zeby uzyc hs'a tak na bem crashuje od razu gdy tylko konczy sie pasek ladowania postaci.

**Comment by aje** [comment]
wow error 134 are related to corruptions of your client
try to redownload the client http://atlantiss.eu/pages/1
