### ISSUE TITLE
[en][arena] starting arena buffs

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4454]
Now when arena starts and there is a priest/rogue team(for example), you click priest and you can't see any buffs/auras on him(Honor Among Thieves from rogue,for example).

Seeing auras/buffs at the start are important for the team to know what type of tactics to adapt, or what target they want to kill.

**Comment by blinkmaster** [comment]
and i thought war mage who we played against were actually sneaky! but indeed, its impossible to see the buffs, dunno why O.o

**Comment by razgal** [comment]
yea or if you want to spellsteal in opener as mage, you don't know how many buffs the opponent has.

**Comment by GtGraphics6** [comment]
Happens all the time  with any class now, sometimes i cant even see my teammate's buffs. Really annoying , especially as a mage or priest.

**Comment by blinkmaster** [comment]
srsly fix this already.

**Comment by Jenovas** [comment]
This is only bugged in arenas?

**Comment by blinkmaster** [comment]
Gonna check later on bg but pretty sure its arena oriented

**Comment by blinkmaster** [comment]
Checkd its only arena related bug

**Comment by debtheone** [comment]
gamebreaking

**Comment by GtGraphics6** [comment]
Fix it already,  it`s unplayable

**Comment by razgal** [comment]
[code]"This is only bugged in arenas?"[/code]
I think it's a general one, because I see people in sw on mounts or with shields on them and can't see anything on buffs.

**Comment by Jenovas** [comment]
Is this all buffs? Or only a few of the buffs arent visible? Or one specific one?

**Comment by razgal** [comment]
all

**Comment by debtheone** [comment]
most annoying bug iv ever seen please fix it

**Comment by debtheone** [comment]
bump

**Comment by Fearyourself** [comment]
This bug also happens in 5-man heroics, in the world and in battlegrounds.

**Comment by l337g0g0** [comment]
Yea this needs to be fix ASAP guys, sorry to rush you but this is important stuff here... :P

**Comment by debtheone** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 4677.
