### ISSUE TITLE
NPC : The Amazing Zanzo + Others

### ISSUE THREAD

**Issue by Pomyinauzz** [Atlantiss/BugTracker#4455]
• NPC : The Amazing Zanzo (ID:32712)
• Location : Dalaran
• Issue : NPC does not appear to be scripted? From what I can understand, there are 20 different NPC's which roam the city of Dalaran (10 Alliance faction, 10 Horde faction) - but only 1 from each faction will be active at a time. The variety of these NPC's are a unique class, (mage, warrior, druid, etc...) and each offers something to your chosen class. I am uncertain as to when they are supposed to swap shifts, but I can say for certain that after many returns and long hours of waiting, this issue needs to be visited.

For more information : http://www.wowhead.com/npc=32712/the-amazing-zanzo#comments

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
