### ISSUE TITLE
[Quest-Classic][NPC] Twin Temptresses

### ISSUE THREAD

**Issue by Jasintar** [Atlantiss/BugTracker#4456]
Quest NPC Salia is located in textures and cannot be attaked.

**Comment by Aival94** [comment]
Probabky after a restart if server it gonna get fixed.It happened to me yesterday after using my shaman [Thunderstorm](http://www.wowhead.com/spell=51490/thunderstorm) which push her in the wall.I tried to aggro her somehow but could not find a way to unstuck her.I suppose all push abilities can cause the same bug if use on these npcs or on this location.

**Comment by aje** [comment]
I just saw the npc which is no longer blocked.
