### ISSUE TITLE
Warlock plonacy Felguard 

### ISSUE THREAD

**Issue by Zibolock** [Atlantiss/BugTracker#4457]
Temat poruszany, pet płonie i traci hp.

A problem ten pojawil mi sie po OS 25 
Prosze o usuniecie buga.

**Comment by aneq** [comment]
Demony Warlocków są przyzywane i są częścią płonącego legionu, więc nie dziwiłbym się, że płoną.
Jeśli masz wątpliwości skontaktuj się z szefem płonącego legionu, Kiljadynem

**Comment by Kejmil** [comment]
ewentualnie ze straza pozarna

**Comment by Bastion** [comment]
spróbuj iść do Icecrown, tam jest zimno

**Comment by Bildo** [comment]
napisz ticket...
