### ISSUE TITLE
[EN] [Draenei] [Racial]  Gift of the Naaru

### ISSUE THREAD

**Issue by grayfox764** [Atlantiss/BugTracker#446]
As can be readed in the skill description.

"Gift of the Naaru: Heals the target for 20% of the caster's total health over 15 sec."

But after trying it, is only healing me 4 points of health each tick. tried many times, same result.

**Comment by Wojmistrz** [comment]
ffs would it be fixed any soon? coz this is annoying when u want to SURVIVE and what? heal for 4 hp -.-

**Comment by Wolffenstein** [comment]
Fixed in rev 4243.
