### ISSUE TITLE
[PL] Postac zablokowana

### ISSUE THREAD

**Issue by Goraen** [Atlantiss/BugTracker#4460]
Moj alt Gorenah 55 lvl DK jest zablokowany. Jak robilem q: The Eye Of Acherus wow-client sie zawiesil, po resecie nie moge kontynuowac tego zadania. Jestem dalej w cytadeli i nie ma NPC. Relog nie pomaga.

**Comment by Bastion** [comment]
zrób nowego DK, tylko tym razem nie popełnij tego samego błędu!

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the quest provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
