### ISSUE TITLE
[PL] Rogue - goblin questline

### ISSUE THREAD

**Issue by Goraen** [Atlantiss/BugTracker#4461]
Moj alt Gorenoir 6lvl sie zablokowal. Wow-client wyrzucil mnie z gry i po ponowny zalogowaniu przenioslo mnie do The  Last Isles. Mam aure: Near Death! i nie moge sie ruszyc ani uzywac zadnych skillow. NPC wokolo mnie nie reaguja (nie ma opcji dialogwej). Relog nie dziala.

**Comment by Bastion** [comment]
smutno troche :(

**Comment by Asavel** [comment]
a unstuck probowales?
