### ISSUE TITLE
Transmog issue

### ISSUE THREAD

**Issue by pooneytang** [Atlantiss/BugTracker#4462]
I'm unable to transmog my bow to look like a gun which I should be able to do. http://us.battle.net/wow/en/forum/topic/3196342583 is an offical blizzard transmog rules list that says that weapons must be the same weapon type with an exception of guns, crossbows, or bows.

**Comment by ezzira** [comment]
you sure your weapons also have stats? thats also a transmog rule, so if some low level weapons don't have stats (just a passive), these can't be transmogrified.

**Comment by Shisai** [comment]
actually the transmog rule doesn't say anything about needing stats, it says any item, green blue or purple can be transmogged to

**Comment by ezzira** [comment]
"..the quality (color) of an item does not matter at all, the basic rule is that it has to have attributes to be a valid source, and it also has to be Bind on Pickup, Bind on Equip or Bind to Account to be a valid target.."
source: http://wow.gamepedia.com/Transmogrification

**Comment by EnderBlazer** [comment]
Something I've noticed in transmog is that once I transmog any of my 2h weapons (using a retri pala), I can't transmog it to another weapon (after I revert my sword to original I can't transmog it to it's previous mog or any other, the apply button works but has no effect).

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by ezzira** [comment]
@EnderBlazer yeah thats pretty normal, when you revert it, its going back to the original look. than you have to re-apply the transmog to get it back.
