### ISSUE TITLE
Blood DK "bugs"

### ISSUE THREAD

**Issue by RobiD2** [Atlantiss/BugTracker#4463]
Just started playing a few days ago Blood DK( my first char. on server - Nooberta )

- Blood Tap activate blood & UH/F rune = 2 death rune every 30 sec.

- 27% of their Strength bonuses as parry rating dont work at lvl 85 (cant create 2nd DK to test on low lvl )

- Bloodworms (Blood Parasite 2/2) randomly pull mobs far away from DK / underground and pull mobs from other floor   

- Dancing rune weapon dont mimic DK attacks

- Mastery : Blood Shield randomly stops working (this is IMHO game-breaking bug but i did not managed to replicate)

- Army of the Dead taunt mehanic dont work

 English is not my native language. So if you feel you have need to mock my English "skills" Mr. Nazi Grammar plz avoid this topic.Best regards.

**Comment by Jenovas** [comment]
1 bug = 1 issue.
Please also read how to use the bugtracker.
Closing.
