### ISSUE TITLE
[EN][Class][Warrior] Blood Frenzy Debuff on the Target

### ISSUE THREAD

**Issue by freddie12** [Atlantiss/BugTracker#447]
Arms Warrior's "Blood Frenzy" debuff on the target does not remain while Deep Wounds and Rend are active on the enemy. I do know it does not stack while both Deep Wounds and Rend active but its duration has something wrong when both effects are active simultaneously on the target. When i apply Rend (without applying DW), it triggers Blood Frenzy and it remains during Rend effect on the target as usual. It is same for applying only Deep Wounds as well. However, when both are active simultaneously, Blood Frenzy debuff remains 4 seconds and disappears before any of the triggering bleed effects vanish from the target. This issue does not occur frequently so that it is hardly noticeable. 

Blood Frenzy: http://wowpedia.org/Blood_Frenzy

**Comment by Morderczyk** [comment]
I confirm this

**Comment by BialyADI** [comment]
It will be reapair?

**Comment by BialyADI** [comment]
This have more than year ;x.

**Comment by freddie12** [comment]
No1 likes warriors.

**Comment by freddie12** [comment]
bump
