### ISSUE TITLE
[PL] Algalon

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#4470]
problem dotyczy dodatkowego bossa raidu kontentu Wotlk Ulduaru dokładniej rzecz biorąc przy otwarciu bramy boss pojawia sie w ilosci 4 po czym nie nabija sie na niego id dokładniej chodzi mi o to ze pojawia sie spowrotem mozna go robić raz dziennie na przykład jak nie wiecej przez całe id.

**Comment by Bastion** [comment]
4x Algalon, KTO DA WIĘCEJ !!

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the boss provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
