### ISSUE TITLE
[EN][Cape of Stranglethorn] Broken Quest

### ISSUE THREAD

**Issue by nenormalen** [Atlantiss/BugTracker#4471]
Hello there Atlantiss!
Well, I was doing the quest: http://www.wowhead.com/quest=26649/drive-by-piracy . The quest is bugged for me. I can talk to the Bloodsail Oarsman npc so we can get on the boat. But when I have to be on the boat I am actually under it. So in that way I can't shoot with the gun and kill Venture Co. Oil Workers npc. I have no other quest options to do there (I've done a lot of quests in that zone so far). Can you help please? Thanks in advance!

**Comment by Bildo** [comment]
duplicate
