### ISSUE TITLE
Fishing in Dalaran bugged

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#4472]
I cant fish in Dalaran anymore for some reasons

**Comment by klm670** [comment]
Fishing is bugged everywhere. It's impossible to fish for volatile fire, what would be the main source of it. After clicking the float when it splashes it doesn't open loot, and takes the 3 seconds to say "your fish got away"

**Comment by jangsna** [comment]
Nah man I understand that but at least u can still fish but u cannot fish
in dalaran fountain nor doing the disarmed question one cuz it just don't
let u

**Comment by xolon** [comment]
its like reported 100 times already

**Comment by xolon** [comment]
#2808
