### ISSUE TITLE
[EN][Spell][Death Knight] Howling blast

### ISSUE THREAD

**Issue by nevcio** [Atlantiss/BugTracker#4474]
http://cata.openwow.com/spell=49184
Howling blast does too much aoe dmg.
It should do 50% of main target damage but it does for example
1850 to main target and 1050 aoe dmg when im naked
or 8000 damage to main target and 7000 aoe dmg when im in vicious gear

**Comment by nevcio** [comment]
Nevermind, seems to be the same double dipping issue as #3500

**Comment by ezzira** [comment]
that would explain why i only see frost dl's :D

**Comment by Achiver** [comment]
Yeah , Howling Blast is too OP for now.

**Comment by Jenovas** [comment]
Fixed in rev 4631
