### ISSUE TITLE
[EN][Talent][Druid] Typhoon

### ISSUE THREAD

**Issue by ezzira** [Atlantiss/BugTracker#4476]
Hi guys, so i discovered some strange bugs with typhoon. typhoon should actually knock people away after a short delay and daze them for 6 seconds, which it does if you are standing still. The thing is when you move and turn your character typhoon seems to bug sometimes, here are some bugs i faced:
-Typhoon icon going on cooldown and spell animation is appearing but nothing happens and you can recast Typhoon
-Typhoon animation is going in the right direction, but knocks mobs in an other direction.
-Typhoon animation appears but mobs are not knocked away or get dazed.
-Typhoon animation is not appearing and mobs doesn't get knocked away but still get dazzed
-Typhoon animation is not appearing but is working as intended
I guess most of the problems can be solved by re-writing the typhoon script. after facing the bugs i listed i think, there is something wrong with the spell delay typhoon has, because if you turn you character to fast the animation will go in the right direction but the spell effect isn't following the animation. To avoid this, at the moment,when turning your character, you have to stand still for like 0.5 sec, to cast typhoon and guarantee that the spell will work like it should. For PvE its not that big of a deal, but for moonkin pvp its pretty annoying if enemys doesn't get knocked away.

**Comment by Crusaderz** [comment]
Fun fact. On retail typhoon had same bugs.
http://eu.battle.net/wow/en/forum/topic/2505103760

**Comment by Wolffenstein** [comment]
That's because Typhoon consists of 2 spells, the first one triggers the second one (with dmg, knockback and slow). If you change your facing before the second spell is casted, the cone of attack will be in the direction you're currently facing, not the one when you actually used Typhoon.

**Comment by ezzira** [comment]
Yeah thanks for closing a topic that is still not solved. "If you change your facing before the second spell is casted, the cone of attack will be in the direction you're currently facing, not the one when you actually used Typhoon." if this would just happen i would be happy, but its completely the opposite of what happens. 
in like 50% of my casted typhoons the effect of the spell is going in the direction where i casted typhoon and not he one that I'm currently facing. thats why i said "..the animation will go in the right direction but the spell effect isn't following the animation." 
in 25% of the cases it's actually working and the spell effect will follow the animation and will go in the direction I'm currently facing.
the other 25% the spell effect is just doing random weird stuff, like knocking enemys in the opposite direction they should get knocked, or knocking them behind me, or just dazing them and don't even knock them away (even if they are like 5-10 yard away from me).

**Comment by MangeNerfedOwl** [comment]
Ezzira is right. P.S. that delay is quite broken too what was said and shown already in another topic https://github.com/Atlantiss/BugTracker/issues/5295. It's worse than spell lock before it has been fixed recently.
