### ISSUE TITLE
Mysterious camel figurine

### ISSUE THREAD

**Issue by stefannis** [Atlantiss/BugTracker#4478]
There are spawns that pop out everytime there is a server crash or restart couple of those are (45.45/15.17 , 34.40/21.27 ,33.34/62.82 , 22,11/64.09 , 40.87/49.72 ,71.95/43.89 ) there is at least one more I forgot they do not drop the mount(ever) and I do not know if they interfere with the proper one spawning but I guess it is worth mentioning it here

**Comment by Achiver** [comment]
Well , every camel's spawn have a chance to be the one that teleports you to the Feralas.

**Comment by stefannis** [comment]
nope there is one that is proper that npcscan finds these are bugged and spawn all the time and never proc the proper one allways gives the mount

**Comment by Bildo** [comment]
There is 5% to spawn proper camel instead of 'normal' camel. Everything works as it should.

**Comment by stefannis** [comment]
it does not the camels allways spawn in the same place please read what I wrote it does not work as it should its just not bugged as hell
