### ISSUE TITLE
[PL][Core] Account Bound Items

### ISSUE THREAD

**Issue by Rhyvos** [Atlantiss/BugTracker#448]
Itemy które są "Account Bound" np. [Ring of the Boy Emperor](http://cata.openwow.com/item=64904) po nałozeniu enchanta [Enchant Ring - Intellect](http://cata.openwow.com/spell=74217) nie mogą zostać wysłane na inne postacie na koncie.

**Comment by Wolffenstein** [comment]
Fixed in rev 4196.
