### ISSUE TITLE
[EN][QUEST][Ironforge] Keepin' the Haggis Flowin'

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4481]
Sognar Cliffbeard <Meat Vendor>  ( http://www.wowhead.com/npc=5124 ) doesn't sell Bag o' Sheep Innards ( http://www.wowhead.com/item=69984 ) which is needed for quest.

Quest ID - http://www.wowhead.com/quest=29353

**Comment by Deadlyblonde** [comment]
Bump!

**Comment by zano354** [comment]
Bump! as 20/09/2015 still 08:19 server time, still not fixed. :P

**Comment by Thefakemccoy** [comment]
![wowscrnshot_102915_020826](https://cloud.githubusercontent.com/assets/12252441/10811412/26e7884a-7de2-11e5-9ec7-cf40112fc732.jpg)

**Comment by monibu** [comment]
To my knowledge this will fix it:

DELETE FROM `npc_vendor` WHERE `item`= 69984;
INSERT INTO `npc_vendor` VALUES (5124, 11, 69984, 0, 0, 0);

**Comment by KieraHorde** [comment]
This quest still doesn't work. The NPC doesn't sell the quest item. Can you fix it, please?

**Comment by Deonorth** [comment]
bump

**Comment by monibu** [comment]
Seriously guys, would it hurt you to fix this quest and give ally one more achievement to complete?

**Comment by schwim0341** [comment]
Another IF daily that can't be completed.  Not looking forward to traveling to the other continent to see how many of those dailies can't be finished as well.

**Comment by morgs71** [comment]
Still not working

**Comment by buzzstpoint** [comment]
Just tried this daily, Abandoned and tried several times. 
Same thing. 
Sognar Cliffbeard does not sell the "Bag O' Sheep Innards"

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8055-4481questironforge-keepin-the-haggis-flowin/
