### ISSUE TITLE
[EN][Ironforge][Quest] Fish fer Squirky

### ISSUE THREAD

**Issue by Nikolay-Asenov** [Atlantiss/BugTracker#4482]
You can take the fishing daily quest but you still cant fish in the pool where the quests wants to.

http://www.wowhead.com/quest=29344/fish-fer-squirky

**Comment by TranceAccount** [comment]
You can fish from the pool, but I haven't seen them drop yet.

**Comment by Docholiday-Atlantiss** [comment]
@TranceAccount Trance I know you closed it due to it said you cant fish in the area when you can but the Blind Minnows are not dropping been trying for 5 mins have not caught one.

**Comment by TranceAccount** [comment]
Yeah they're quite rare
