### ISSUE TITLE
[En][Quest][goblin starting zone] goblin starting zone

### ISSUE THREAD

**Issue by worgenman** [Atlantiss/BugTracker#4484]
hello

well after today's restart for fixing daily quests, goblin starting zone became absoloutly unplayable, u cant do quest without loging out evertyime, everytime u complete the quest u need to relog for taking new quests, if u dont u cant take quests, please fix it

thank u so much for ur great server

**Comment by Fangorn919** [comment]
It doesnt happen only in Goblin starting are, it is a problem which has come to the DK starting area aswel as to the Night elf starting area

5 stars for the server, and it would be realy great if u could solve this :D

**Comment by ArtiiQ** [comment]
It's happening on the human starting zone too, just introduced the server to my friend and he can't even enjoy it properly, he can't get the quest for the Orc Spies, says the same thing, that he doesn't have the requirements. Even when he reconnects it doesn't work.

**Comment by Akinata** [comment]
Who can help, after today's restart for fixing daily quests, i went doing quests in DeepHolm, me was TP to Thrall, and second quest bags,  i don`t restart, and  i can`t port to DH, in SW on circle i haven`t port. Please Fix.  Тhanks in advance

**Comment by Ruski91** [comment]
Napiszę po polsku bo nie chce mi się kaleczyć angielskiego, sorry.
Po ostatnim update'cie są problemy z aktualizacją wymagań do rozpoczynania następnych questów. Np w Grizzly Hills po oddaniu questa i po wybraniu accept natępnego questa z chain'u, pojawia się komunikat, "you don't meet the requirements for this quest" i wykrzyknik znika z npc. Po relogu nad npc jest juz wykrzyknik i można wziąć quest. Z tego co ludzie piszą na World to są takie questy przy których relog nie pomaga. Proszę o szybką interwencje, bo to pewnie drobny błąd a strasznie uprzykrza exp ;_;

**Comment by worgenman** [comment]
Bad email please unsubscrite me 


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Ruski91 <notifications@github.com> 
Date : 13/09/2015  21:52  (GMT+01:00) 
À : Atlantiss/BugTracker <BugTracker@noreply.github.com> 
Cc : worgenman <worgen@gmail.com> 
Objet : Re: [BugTracker] [En][Quest][goblin starting zone] goblin starting
  zone (#4484) 

Napiszę po polsku bo nie chce mi się kaleczyć angielskiego, sorry.

Po ostatnim update'cie są problemy z aktualizacją wymagań do rozpoczynania następnych questów. Np w Grizzly Hills po oddaniu questa i po wybraniu accept natępnego questa z chain'u, pojawia się komunikat, "you don't meet the requirements for this quest" i wykrzyknik znika z npc. Po relogu nad npc jest juz wykrzyknik i można wziąć quest. Z tego co ludzie piszą na World to są takie questy przy których relog nie pomaga. Proszę o szybką interwencje, bo to pewnie drobny błąd a strasznie uprzykrza exp ;_;

**Comment by worgenman** [comment]
its fixed thanks
