### ISSUE TITLE
[EN][Quest][Felwood] Seeking soil

### ISSUE THREAD

**Issue by supreemetac** [Atlantiss/BugTracker#4485]
The quest is bugged for a long time , the creature that spawns does not dig the soil so you cant finish the quest

**Comment by armano2** [comment]
duplicate: #1093

**Comment by supreemetac** [comment]
Yes , but that statement is in polish. I don't understand polish so i opened one in English.

**Comment by Sulmurz** [comment]
Completable. I abandoned the quest and after 30 minutes all of a sudden Seedling Protector appeared next to me. Then I was able to collect soils with his help.
