### ISSUE TITLE
[EN][NPC][Uldum] Mangy Hyena

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4491]
http://www.wowhead.com/npc=45202/mangy-hyena#drops

This npc is dropping blues and greens at a rate far higher than is reported. Killed five of them and got four blues. Easy place for enchanters to farm materials, could also disrupt the economy. As you can see in the drops, it should be about .5 to .05% Drop rate on stuff for this npc, It is more like 50-60%.

**Comment by meowmewo** [comment]
Killed 30 of them just now, not a single item. not a blue, no green. nothing. 
Id suggest u to not waste time and go play the lottery.

**Comment by meowmewo** [comment]
Update: 
Mangy Hyena killed - 50
Greens - 3
Blues  - 1

**Comment by LordKnightCecilo** [comment]
I guess I really just got lucky then. Wish I had that kind of luck with things like glyph books. 

Did the same as Meow to confirm it wasn't dropping at the rate it was or appeared to be.

Killed - 30,
Greys - 22
Whites - 10 (Toughened Flesh)
Green - None
Blue - None

**Comment by aje** [comment]
Just saw loot table for this monster and no high rate for green/blue item.
