### ISSUE TITLE
Formula: Enchant Gloves - Advanced Herbalism

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#4493]
![image](https://cloud.githubusercontent.com/assets/12395407/9858988/317df52c-5b24-11e5-950c-de0656488274.png)
According to wowhead, this item is not obtainable in Cata http://www.wowhead.com/item=11205/formula-enchant-gloves-advanced-herbalism as the only mobs who dropped it were removed from the game.

**Comment by xolon** [comment]
http://www.wowhead.com/item=11205/formula-enchant-gloves-advanced-herbalism#comments

Check the third top comment

**Comment by sigmundfreud2016** [comment]
And why should I believe him? Maybe he is wrong. Both listed mobs do not exist in the game, and no other mobs are listed. This means nobody should drop it.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by Pallitax** [comment]
According to [OpenWoW](http://cata.openwow.com/npc=14448#drop), the NPC [Molt Torn](http://www.wowhead.com/npc=14448/molt-thorn), which is still in the game, has a 0.8% chance to drop this recipe.

**Comment by Wolffenstein** [comment]
This item shouldn't be in the game anymore.

**Comment by sigmundfreud2016** [comment]
@Pallitax I don't see it on the list
![image](https://cloud.githubusercontent.com/assets/12395407/10079631/69b7d51a-62eb-11e5-8510-9fe90dbdfcad.png)

**Comment by xolon** [comment]
never trust wowhead
http://cata.openwow.com/npc=14448

**Comment by Navedonar** [comment]
http://wow.gamepedia.com/Formula:_Enchant_Gloves_-_Advanced_Herbalism

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8172-4493itemformula-enchant-gloves-advanced-herbalism/
