### ISSUE TITLE
[EN][Spell][Priest] Spirit of Redemption

### ISSUE THREAD

**Issue by Faaith** [Atlantiss/BugTracker#4497]
http://www.wowhead.com/spell=20711/spirit-of-redemption

"Upon death, the Priest becomes the Spirit of Redemption for 15 sec.  The Spirit of Redemption cannot move, attack, be attacked, or be targeted by any spells or effects.  While in this form the Priest can cast any healing spell free of cost.  When the effect ends, the Priest dies."

How it works now:
- Player can move/jump while in Spirit form
- Healing spells cost mana, so if player dies while oom, SoR is completely usless
- Player while in SoR can heal themselves and be healed which is often misleading and other healers think that priest is still alive and heal him, wasting mana in process.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2838
