### ISSUE TITLE
[EN][Ironforge][Quest] Live Bait 

### ISSUE THREAD

**Issue by Nikolay-Asenov** [Atlantiss/BugTracker#4498]
The quest works fine but you can't return it to Cook Ghilm. I tried with relog and redoing the quest but the problem still appears. 

Cook Grihlm - http://www.wowhead.com/npc=1355/cook-ghilm
Quest - http://www.wowhead.com/quest=29347/live-bait

**Comment by Achiver** [comment]
You didnt explain the problem: You cant get the quest reward from Cook Grihlm.

**Comment by Illusionist87** [comment]
There is no question mark (?) on the Cook Ghilma, so it is imposible to complete the quest.

**Comment by Deadlyblonde** [comment]
Bump!

**Comment by zano354** [comment]
Bump, still not yet fixed.

**Comment by monibu** [comment]
To my knowledge this will fix it:

DELETE FROM  `creature_questender` WHERE quest = 29347;
INSERT INTO `creature_questender` VALUES (1355, 29347);

**Comment by schwim0341** [comment]
Still waiting on a fix for this so we can get the IF fishing dailies achiev.

**Comment by Quban** [comment]
> To my knowledge this will fix it:

it wont :D
