### ISSUE TITLE
[ENG][Passive][Death Knight][Blood] STR to Parry convert

### ISSUE THREAD

**Issue by br34th5** [Atlantiss/BugTracker#4499]
25% of their Strength bonuses as parry rating dont work 

1. Blood DK should have a bonus parry rating from their current Strength, but it gives 0 parry rating from Strength at the moment.
2. Originally, the only stat which increased the chance to parry was defense (0.04% per point). However, with the addition of death knights, 25% of their strength is added as parry rating (it is important to note that a death knight's high parry rating is one of their mitigation mechanics).[ taken from http://wow.gamepedia.com/Parry ]

Proof: http://imgur.com/a/Pj8LV
First image: Without Horn of winter (horn of winter taken as an example) 
Second image: With Horn of winter parry rating is the same

**Comment by Wolffenstein** [comment]
Are you sure it's not a visual bug?

**Comment by br34th5** [comment]
Hey Wolffenstein! It could be a visual bug, but don't know how to test it properly

**Comment by PierwszyKrytykRP** [comment]
It's visual. I could provide screenshots showing that horn and other str buffs increase mine parry %

**Comment by RobiD2** [comment]
http://imgur.com/Dzy7nhH   parry % screenshot

http://imgur.com/AOeY46x  only STR gear 

http://imgur.com/QvIWGkR NO gear SS

race > Goblin     like u see even macro dont see parry higher then 5% from 27% str>parry bonus(4.3.4)

**Comment by lanrutcon** [comment]
I'd say it's a class issue. Tested on my Blood Death Knight (lvl70) and removing STR gear (without Parry Rating) decreased my Parry chance. Also tested Horn of Winter, and it was converting to Parry as well.

**Comment by RobiD2** [comment]
No official response so anyone who thinks lvl up blood DK do not pick GOBLIN.
