### ISSUE TITLE
Retrieving realmlist.....

### ISSUE THREAD

**Issue by fenix2009** [Atlantiss/BugTracker#4506]
Hey, when i turn on my wow i get this error
http://i.imgur.com/pFLzIbh.jpg
Someone can help...
I already reinstall the wow
When i reinstall the network start work after 5 minuts i shutdown my wow to install addon and start again this error someone know how solve that?

**Comment by Bastion** [comment]
go to forum ffs

**Comment by xolon** [comment]
Bastion maddddddd rip

**Comment by Bildo** [comment]
read bt rules
