### ISSUE TITLE
[EN] [Class] [Paladin] T11 4 parts set bonus

### ISSUE THREAD

**Issue by grayfox764** [Atlantiss/BugTracker#451]
tried today on the PTR after buying all the tier parts, bonus says:

"Grants 540 Spirit for 6 sec after you cast Holy Shock."

tried healing spells on me and on another player and bonus didn't worked.

link to the tier bonus: http://www.wowhead.com/spell=90313/item-paladin-t11-holy-4p-bonus

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
