### ISSUE TITLE
[EN][QUEST][Northrend] Disappearing quest items

### ISSUE THREAD

**Issue by Talrandel** [Atlantiss/BugTracker#4510]
Any quest item that drops from mobs and starts a quest disappears right after i start a quest from that item. So i can't complete that quests and any other in quest line. 
For example, 
http://www.wowhead.com/quest=11941/puzzling
http://www.wowhead.com/quest=12055/a-strange-device
http://www.wowhead.com/quest=11730/master-and-servant
http://www.wowhead.com/quest=12168/the-favor-of-zangus

**Comment by Wolffenstein** [comment]
Fixed in rev 4597.
