### ISSUE TITLE
Chest loot

### ISSUE THREAD

**Issue by modkis15** [Atlantiss/BugTracker#4511]
![wowscrnshot_091715_150049](https://cloud.githubusercontent.com/assets/14330178/9932536/5d4d85e8-5d4d-11e5-9e7c-7302efacfe5c.jpg)
i get This is in this area:
![worldmap-teldrassil](https://cloud.githubusercontent.com/assets/14330178/9932560/961491b4-5d4d-11e5-852f-a3921fc7bbb7.jpg)

**Comment by Bastion** [comment]
bis shoulders

**Comment by Bildo** [comment]
read bt rules
