### ISSUE TITLE
[EN][QUEST] Zen'kiki and the cultist

### ISSUE THREAD

**Issue by davidrivasdos** [Atlantiss/BugTracker#4513]
the quest in western plaguelands dont work at all. the bears appear out of the cages, and zen'kiki nps dont heal the bears.

**Comment by karhima** [comment]
Confirmed, it should work like this: http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

**Comment by baks93** [comment]
dalej nie działa prosimy o naprawienie q :)

**Comment by Snake90** [comment]
Still bugged
