### ISSUE TITLE
[EN][QUEST][Plaguelands: The Scarlet Enclave] Brothers in Death

### ISSUE THREAD

**Issue by helldeskmonkey** [Atlantiss/BugTracker#4514]
Thassarian is not offering this quest. I've relogged and it's still missing. Doesn't matter if he's in combat or all the mobs in the building are dead. I also went to where Koltira was, and could not begin or end the quest there. The questline is necessary for new DKs because it provides at least one talent point. I'm not 100% certain (as I haven't attempted it yet) but I believe one cannot complete the DK starting area without completing this questline as well.

http://www.wowhead.com/quest=12725/brothers-in-death

**Comment by helldeskmonkey** [comment]
Ignore - I'd close it if I could, but apparently instead of Brothers in Death being offered alongside the quest it's normally offered with it's instead chained sequentially.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1932
