### ISSUE TITLE
[EN] Gnome starting zone, Quest: Decontamination, no Yellow "?" from NPC

### ISSUE THREAD

**Issue by zidemizar** [Atlantiss/BugTracker#4517]
I know it was closed a few minutes ago, but I am still having issues with the quest. Once I accept the quest, the NPC that I have to talk to does not have the Yellow ? on top of its head, however there is a yellow ? on my minimap but it does not show the quest as complete on the quest log and I cannot interact with the NPC.

**Comment by zidemizar** [comment]
Here is a screenshot of the issue.
![wowscrnshot_091715_141143](https://cloud.githubusercontent.com/assets/14335441/9943311/3d6c17d2-5d46-11e5-918a-ffb612d7cb42.jpg)

**Comment by Wolffenstein** [comment]
The server has not been updated yet.
