### ISSUE TITLE
[EN][Talent][Class] Penance

### ISSUE THREAD

**Issue by Chulain** [Atlantiss/BugTracker#4524]
not worth my reports

**Comment by Frainzil** [comment]
i never get this bug though, been testing it for few minutes now. Always had my 3ticks of penance.

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=ty8tR0HSJ-Y

**Comment by RandomPickNewb** [comment]
Tested it myself out of 40-50 penances 4 didnt do the last tick.Tested while both directly facing the target and while needing to reposition.In both cases there was a missing last tick.

**Comment by Illusie** [comment]
Maybe haste problem? On molten when i played there like 1.5 y ago it was ticking 2 times sometimes too.
