### ISSUE TITLE
[PL] Itemy bez statystyk nie mogą być użyte do zmiany wyglądu (TRANSMOGA)

### ISSUE THREAD

**Issue by bobicz** [Atlantiss/BugTracker#4525]
Itemy typu :
http://www.wowhead.com/item=12592/blackblade-of-shahram

Nie posiadające statystyk a efekty powinno dać się użyć do transmoga

http://www.wowhead.com/news=195310/4-3-preview-the-dragon-soul-raid-and-transmogrification-rules

**Comment by Bildo** [comment]
duplikat
