### ISSUE TITLE
game doesn't launch, error message

### ISSUE THREAD

**Issue by TygerScorpion85** [Atlantiss/BugTracker#4527]
this is the error message I get

==============================================================================
World of WarCraft: Retail Build (build 15595)

Exe:      E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
Time:     Sep 18, 2015  8:55:37.323 PM
User:     TS85
Computer: HP-ENVY
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal condition!

Program:	E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
ProcessID:	7484

Failed to open required archive Data/wow-update-base-15211.MPQ with error : 5 

Streaming Status: Data Rdy

Wow.mfil download error: Failed to create file 'WoW.mfil'
Manifest is valid.

Debug Details:

[29] err=2 text=SFileOpenArchive - STORM_ERROR_ACCESS_DENIED - Data/wow-update-base-15211.MPQ
[28] err=0 text=FileStack_Streaming::StreamingOpen - Unable to open the storage file
[27] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[26] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[25] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[24] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[23] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[22] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[21] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[20] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[19] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[18] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, createMode:0x4, flags:0x80, lastError:5
[17] err=4 text=Win32 Open - Data\wow-update-base-15211.MPQ, accessMode:0xc0000000, shareMode:0x3, crea

WoWBuild: 15595
Version: 4.3.4
Type:  WoW
Platform: X86

Patch data download failed.
Failed to create file 'WoW.mfil'
Manifest is valid.

Settings: 
SET locale "enGB"

----------------------------------------
               GxInfo
----------------------------------------
No GX Device Created
Desktop Display List:
Device Name: \\.\DISPLAY1
Device String: NVIDIA GeForce GTX 745
State Flags: 0x00000005
Device ID: PCI\VEN_10DE&DEV_1382&SUBSYS_6893103C&REV_A2

Installed DX9 Version:
File Version: 6.3.9600.17415
------------------------------------------------------------------------------

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

Showing 6/6 threads...

--- Thread ID: 6932 [Current Thread] ---
004047B9 0018FB08 0001:000037B9 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00404BBA 0018FB20 0001:00003BBA E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
007A3070 0018FC44 0001:003A2070 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
007A32B5 0018FC54 0001:003A22B5 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
0040672F 0018FDA4 0001:0000572F E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
004080E9 0018FEDC 0001:000070E9 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
004083F6 0018FEEC 0001:000073F6 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00408458 0018FF80 0001:00007458 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
75F57C04 0018FF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 0018FFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 0018FFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

--- Thread ID: 1624 ---
75F57C04 033DFF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 033DFFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 033DFFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

--- Thread ID: 6532 ---
76C92C02 037DFEF0 0001:00001C02 C:\windows\SYSTEM32\KERNELBASE.dll
007DF69B 037DFF28 0001:003DE69B E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
007E393A 037DFF3C 0001:003E293A E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12A8E 037DFF74 0001:00611A8E E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12B36 037DFF80 0001:00611B36 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
75F57C04 037DFF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 037DFFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 037DFFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

--- Thread ID: 8340 ---
76C92C02 03C1FEF0 0001:00001C02 C:\windows\SYSTEM32\KERNELBASE.dll
007DF17F 03C1FF28 0001:003DE17F E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
007E393A 03C1FF3C 0001:003E293A E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12A8E 03C1FF74 0001:00611A8E E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12B36 03C1FF80 0001:00611B36 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
75F57C04 03C1FF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 03C1FFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 03C1FFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

--- Thread ID: 7720 ---
76C92C02 03D5FEF4 0001:00001C02 C:\windows\SYSTEM32\KERNELBASE.dll
007DF569 03D5FF28 0001:003DE569 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
007E393A 03D5FF3C 0001:003E293A E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12A8E 03D5FF74 0001:00611A8E E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
00A12B36 03D5FF80 0001:00611B36 E:\Downloads\World of Warcraft 4.3.4\wow_434.exe
75F57C04 03D5FF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 03D5FFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 03D5FFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

--- Thread ID: 8408 ---
75F57C04 0309FF94 0001:00007C04 C:\windows\SYSTEM32\KERNEL32.DLL
76EFAD1F 0309FFDC 0001:00059D1F C:\windows\SYSTEM32\ntdll.dll
76EFACEA 0309FFEC 0001:00059CEA C:\windows\SYSTEM32\ntdll.dll

----------------------------------------
    Stack Trace (Using DBGHELP.DLL)
----------------------------------------

Showing 6/6 threads...

--- Thread ID: 6932 [Current Thread] ---
004047B9 wow_434.exe  <unknown symbol>+0 (0018FB40,00000000,0391EC20,0018FD94)
00404BBA wow_434.exe  <unknown symbol>+0 (0018FB40,0018FD94,0018FD02,00000080)
007A3070 wow_434.exe  GetBattlenetAllocator+1317248 (00404B60,0018FD02,0018FDA4,0040672F)
007A32B5 wow_434.exe  GetBattlenetAllocator+1317829 (00404B60,0018FD94,000000FC,000000FB)
0040672F wow_434.exe  <unknown symbol>+0 (FFFFFFFE,00000000,00000001,61746144)
004080E9 wow_434.exe  <unknown symbol>+0 (00000001,00000001,0018FF80,00408458)
004083F6 wow_434.exe  <unknown symbol>+0 (0040E4D5,00400000,00000000,0127307B)
00408458 wow_434.exe  <unknown symbol>+0 (FFFDC000,75F57BE0,08EF04D1,0018FFDC)
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (FFFDC000,0811393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (00401190,FFFDC000,00000000,78746341)

--- Thread ID: 1624 ---
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (012E7B90,0B34393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (76EB4A00,012E7B90,00000000,00905A4D)

--- Thread ID: 6532 ---
76C92C02 KERNELBASE.dll WaitForSingleObject+18 (000023D4,FFFFFFFF,02B92948,00A12AB4)
007DF69B wow_434.exe  GetBattlenetAllocator+1564587 (02B92FD0,00A12AB4,02B92948,037DFF74)
007E393A wow_434.exe  GetBattlenetAllocator+1581642 (02B928C0,997FC225,00A12AB4,02B92948)
00A12A8E wow_434.exe  GetBattlenetAllocator+3871646 (00A12AB4,037DFF94,75F57C04,02B92948)
00A12B36 wow_434.exe  GetBattlenetAllocator+3871814 (02B92948,75F57BE0,0B8A04D1,037DFFDC)
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (02B92948,0B74393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (00A12AB4,02B92948,00000000,20FB7EA3)

--- Thread ID: 8340 ---
76C92C02 KERNELBASE.dll WaitForSingleObject+18 (000021F4,FFFFFFFF,00A12AB4,038F5E70)
007DF17F wow_434.exe  GetBattlenetAllocator+1563279 (00000000,00A12AB4,0391E0B0,03C1FF74)
007E393A wow_434.exe  GetBattlenetAllocator+1581642 (038F5E70,99C3C225,00A12AB4,0391E0B0)
00A12A8E wow_434.exe  GetBattlenetAllocator+3871646 (00A12AB4,03C1FF94,75F57C04,0391E0B0)
00A12B36 wow_434.exe  GetBattlenetAllocator+3871814 (0391E0B0,75F57BE0,0B3604D1,03C1FFDC)
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (0391E0B0,0BC8393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (00A12AB4,0391E0B0,00000000,00000000)

--- Thread ID: 7720 ---
76C92C02 KERNELBASE.dll WaitForSingleObject+18 (00000014,FFFFFFFF,00A12AB4,038F6228)
007DF569 wow_434.exe  GetBattlenetAllocator+1564281 (0295D6A0,00A12AB4,0391E3A0,03D5FF74)
007E393A wow_434.exe  GetBattlenetAllocator+1581642 (038F6228,99D7C225,00A12AB4,0391E3A0)
00A12A8E wow_434.exe  GetBattlenetAllocator+3871646 (00A12AB4,03D5FF94,75F57C04,0391E3A0)
00A12B36 wow_434.exe  GetBattlenetAllocator+3871814 (0391E3A0,75F57BE0,0B2204D1,03D5FFDC)
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (0391E3A0,0BDC393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (00A12AB4,0391E3A0,00000000,00000000)

--- Thread ID: 8408 ---
75F57C04 KERNEL32.DLL BaseThreadInitThunk+36 (012740D0,0B00393E,00000000,00000000)
76EFAD1F ntdll.dll    RtlInitializeExceptionChain+143 (FFFFFFFF,76EE0233,00000000,00000000)
76EFACEA ntdll.dll    RtlInitializeExceptionChain+90 (76EB4A00,012740D0,00000000,26557B44)

----------------------------------------
    Loaded Modules
----------------------------------------

DBG-MODULE<00400000 00CDC000 "wow_434.exe" "Wow.pdb" 0 {9a9fe68a-1174-4bdf-b51a0cab2be97eae} 1 1334105658>
DBG-MODULE<55010000 00141000 "dbghelp.dll" "dbghelp.pdb" 0 {24f6937d-6631-40a2-aff3210434afba90} 1 1265054906>
DBG-MODULE<55160000 00277000 "AcLayers.DLL" "AcLayers.pdb" 0 {0f36e7fa-b6fa-477e-afae307d5c621325} 2 1414545824>
DBG-MODULE<56590000 00016000 "MPR.dll" "mpr.pdb" 0 {f1b94b40-5359-4c0c-8b9c06dbf214e748} 2 1414544792>
DBG-MODULE<57260000 00036000 "DINPUT8.dll" "dinput8.pdb" 0 {343d6c05-4ba8-432f-96de0cc284eb483d} 1 1414547753>
DBG-MODULE<57380000 0000F000 "sfc_os.DLL" "sfc_os.pdb" 0 {1b097a0f-1f5a-46b3-99033103dd72c943} 2 1414548027>
DBG-MODULE<5BDC0000 00017000 "MSACM32.dll" "msacm32.pdb" 0 {66e10c13-1126-4bb0-ac86fb7a8b8cce1c} 2 1414544721>
DBG-MODULE<5C2F0000 00065000 "WINSPOOL.DRV" "winspool.pdb" 0 {12592a98-fe3b-4632-a0b404cc5cb6fb44} 2 1414543514>
DBG-MODULE<5CA90000 0000A000 "HID.DLL" "hid.pdb" 0 {353d832e-8ace-4c06-8f07725ab19c5c14} 2 1414544739>
DBG-MODULE<5FC60000 00007000 "DCIMAN32.dll" "dciman32.pdb" 0 {77a3cef8-21be-492d-ae8749d7f82fb959} 2 1414547999>
DBG-MODULE<5FC70000 000EC000 "DDRAW.dll" "ddraw.pdb" 0 {486e3d24-3830-4fa5-864cb95b7e2667aa} 2 1414543963>
DBG-MODULE<5FD60000 00025000 "GLU32.dll" "glu32.pdb" 0 {25f7e4da-db92-497d-bf7a82dc411e4e5a} 1 1414547991>
DBG-MODULE<60550000 000DE000 "OPENGL32.dll" "opengl32.pdb" 0 {9cc9e188-abaf-4d4a-b12c631ae28671dc} 1 1414547870>
DBG-MODULE<61BF0000 0000E000 "SortServer2003Compat.dll" "SortServer2003Compat.pdb" 0 {99e83df8-c417-473b-b3b1ec6233c2b289} 1 1414548012>
DBG-MODULE<61C00000 00003000 "sfc.dll" "sfc.pdb" 0 {6c9dfdc9-1e03-4ca9-87fc8604e6675b3d} 1 1377144808>
DBG-MODULE<63630000 000A0000 "apphelp.dll" "apphelp.pdb" 0 {037f6371-5335-468e-ad54764ed142b861} 2 1414548011>
DBG-MODULE<637A0000 00023000 "WINMMBASE.dll" "winmmbase.pdb" 0 {773a9d5b-7983-4d06-b3a0a02385aaad2d} 2 1414544266>
DBG-MODULE<637D0000 00023000 "WINMM.dll" "winmm.pdb" 0 {ff0d2553-53ac-46d4-8c593c91f26717ee} 2 1414544138>
DBG-MODULE<67050000 001D3000 "d3d9.dll" "d3d9.pdb" 0 {f8f65709-5c16-4527-aefbe588d054f0d5} 2 1414547905>
DBG-MODULE<72980000 00021000 "DEVOBJ.dll" "devobj.pdb" 0 {7dda1bfd-61c9-43b9-8898ee3d9035be53} 2 1414544601>
DBG-MODULE<73610000 0001A000 "dwmapi.dll" "dwmapi.pdb" 0 {60670c1e-c9c4-4d20-b99c8e6e83d24e4c} 2 1414544302>
DBG-MODULE<73910000 00206000 "Comctl32.dll" "comctl32.pdb" 0 {8380e347-10d5-4275-b26e608f0740d7f6} 2 1429929259>
DBG-MODULE<73B20000 00046000 "fwpuclnt.dll" "fwpuclnt.pdb" 0 {b8905975-16d1-4ba4-84127e5cf71b0ac2} 2 1414544189>
DBG-MODULE<73B70000 00008000 "rasadhlp.dll" "rasadhlp.pdb" 0 {e180815f-7f9a-4a85-b8c43ea47d6c8884} 2 1414544732>
DBG-MODULE<73B80000 0007E000 "DNSAPI.dll" "dnsapi.pdb" 0 {165b3d53-ca62-4097-a06a54cfb25a85ec} 2 1414544783>
DBG-MODULE<73C10000 00008000 "WINNSI.DLL" "winnsi.pdb" 0 {2ca93168-0866-4965-9e0daefc75a2b362} 2 1414544777>
DBG-MODULE<73C20000 00020000 "IPHLPAPI.DLL" "iphlpapi.pdb" 0 {02d9ac30-0342-4c6c-ab4b8392cf9d2605} 2 1414544769>
DBG-MODULE<73C40000 0009F000 "winhttp.dll" "winhttp.pdb" 0 {52a299a6-7000-4e76-94661c6112c50096} 2 1414544175>
DBG-MODULE<73CE0000 0000A000 "ondemandconnroutehelper.dll" "OnDemandConnRouteHelper.pdb" 0 {238c1d69-7ba6-48ef-9a028569a16652f0} 1 1414544702>
DBG-MODULE<73CF0000 0004B000 "mswsock.dll" "mswsock.pdb" 0 {6b0d6839-4688-4027-becb35001726e8d9} 2 1414544775>
DBG-MODULE<73D40000 0000A000 "Secur32.dll" "secur32.pdb" 0 {3038c46e-97d0-4810-8740eccdb1bd73a0} 2 1414544779>
DBG-MODULE<73E10000 0008B000 "SHCORE.dll" "shcore.pdb" 0 {ab29e1ed-4d52-4fed-828e421ae8673dd7} 2 1421981223>
DBG-MODULE<73EA0000 0014A000 "urlmon.dll" "urlmon.pdb" 0 {7aadaf93-5a4e-48be-96ae56804e927fde} 2 1440259009>
DBG-MODULE<741A0000 00009000 "kernel.appcore.dll" "Kernel.Appcore.pdb" 0 {9fdd5e16-9552-48d0-aaf693bd83d5a785} 1 1414544666>
DBG-MODULE<741B0000 0000F000 "profapi.dll" "profapi.pdb" 0 {4e4981a8-efed-432a-824e07f832a0f989} 2 1414544771>
DBG-MODULE<741C0000 0001B000 "USERENV.dll" "userenv.pdb" 0 {83d19410-3824-48e6-b3d28d2dacc1f6d1} 2 1414544457>
DBG-MODULE<741E0000 00232000 "iertutil.dll" "iertutil.pdb" 0 {bbb6e928-12d9-4838-9af789139357253e} 2 1440262242>
DBG-MODULE<74420000 001E4000 "WININET.dll" "wininet.pdb" 0 {2fad33d7-7512-40a1-97348d3e9f30403c} 2 1440259199>
DBG-MODULE<74620000 00008000 "VERSION.dll" "version.pdb" 0 {4dadb143-e234-4821-a4c080ef73a4952e} 2 1414547985>
DBG-MODULE<74630000 00054000 "bcryptPrimitives.dll" "bcryptprimitives.pdb" 0 {46cb28d4-6f7e-4fd4-85df196c07cc27ee} 2 1414544757>
DBG-MODULE<74690000 0000A000 "CRYPTBASE.dll" "cryptbase.pdb" 0 {965b22dd-4cae-4f69-8ef8939960be657c} 2 1414548075>
DBG-MODULE<746A0000 0001E000 "SspiCli.dll" "wsspicli.pdb" 0 {849b8e8d-6777-4a85-9ed4435f55818911} 1 1414544764>
DBG-MODULE<746C0000 00129000 "ole32.dll" "ole32.pdb" 0 {98238254-7562-4bdf-820d4cb09bd0ce00} 2 1434398971>
DBG-MODULE<749F0000 000C3000 "msvcrt.dll" "msvcrt.pdb" 0 {d4416a97-d40c-497a-aa487f2b1835a142} 2 1414548270>
DBG-MODULE<74B60000 0007C000 "ADVAPI32.dll" "advapi32.pdb" 0 {917bb487-3d01-4392-b99999aa0371b1b2} 2 1414547868>
DBG-MODULE<74BF0000 00095000 "OLEAUT32.dll" "oleaut32.pdb" 0 {ab2d635e-e225-41d0-94beb9153dea4519} 2 1418964595>
DBG-MODULE<74C90000 012AD000 "SHELL32.dll" "shell32.pdb" 0 {055c068b-78b1-40c4-83ad9e3e20e1fefb} 2 1431011363>
DBG-MODULE<75F40000 00140000 "KERNEL32.DLL" "wkernel32.pdb" 0 {dfb9f6a1-661c-482c-87b4d0d454332cb8} 1 1414547902>
DBG-MODULE<76080000 000BA000 "RPCRT4.dll" "wrpcrt4.pdb" 0 {34f9f7d0-96a4-45da-a6a69fa4de53993e} 2 1435423350>
DBG-MODULE<76180000 0010F000 "GDI32.dll" "wgdi32.pdb" 0 {c0cf278d-42eb-401e-ad5ef1d6fd2cd425} 2 1435932043>
DBG-MODULE<76290000 00045000 "SHLWAPI.dll" "shlwapi.pdb" 0 {68ec2a42-4e52-42c2-a309e194e68b56cb} 2 1414543388>
DBG-MODULE<762E0000 00041000 "sechost.dll" "sechost.pdb" 0 {f28ed1eb-82e7-44d3-b999e441a6b3ef43} 2 1426821659>
DBG-MODULE<76330000 00027000 "IMM32.DLL" "wimm32.pdb" 0 {57d0acfa-2275-4450-bb9660da8818f362} 2 1414547988>
DBG-MODULE<76360000 0003C000 "CFGMGR32.dll" "cfgmgr32.pdb" 0 {126aaf7d-0541-4d42-b11ac7240a355bee} 2 1414544762>
DBG-MODULE<76420000 00112000 "MSCTF.dll" "msctf.pdb" 0 {7e838438-6823-4f45-b491c219cc6a0003} 2 1426294385>
DBG-MODULE<766D0000 0017D000 "combase.dll" "combase.pdb" 0 {b9684e7a-2a1e-43dc-b0f9a0a9717cb1ab} 2 1414544772>
DBG-MODULE<76850000 00007000 "NSI.dll" "nsi.pdb" 0 {e855cbea-595c-4ff2-b952ff7f82447083} 2 1414548211>
DBG-MODULE<768C0000 001B1000 "SETUPAPI.dll" "setupapi.pdb" 0 {2789ff1b-9e7a-4e56-b7963a59a1fed96c} 2 1414543418>
DBG-MODULE<76B30000 00153000 "USER32.dll" "wuser32.pdb" 0 {fbaae417-246b-4e84-ae5bcec86a73fc64} 2 1414544672>
DBG-MODULE<76C90000 000D7000 "KERNELBASE.dll" "wkernelbase.pdb" 0 {dbe05aac-a1e6-4947-b24fc7feb4e26453} 2 1414548190>
DBG-MODULE<76D70000 00050000 "WS2_32.dll" "ws2_32.pdb" 0 {b4acd51c-f1b9-497a-89b2c0de225bd36d} 2 1414544769>
DBG-MODULE<76EA0000 0016E000 "ntdll.dll" "wntdll.pdb" 0 {c89f4928-0bb3-4e01-8aa487ba22ada47a} 2 1436978641>

----------------------------------------
    Memory Dump
----------------------------------------

Stack: 1024 bytes starting at (ESP = 0018E678)

* = addr                            **                                *       
0018E670: B5 0D 4C 00  78 E6 18 00  00 00 00 00  01 00 04 00  ..L.x...........
0018E680: 03 00 01 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E690: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6A0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6B0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6C0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6D0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6E0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E6F0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E700: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E710: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E720: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E730: 00 00 00 00  50 E9 18 00  B5 0D 4C 00  00 00 00 00  ....P.....L.....
0018E740: 00 00 00 00  78 E6 18 00  00 00 00 00  00 00 00 00  ....x...........
0018E750: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E760: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E770: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E780: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E790: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7A0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7B0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7C0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7D0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7E0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E7F0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E800: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E810: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E820: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E830: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E840: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E850: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E860: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E870: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E880: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E890: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8A0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8B0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8C0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8D0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8E0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E8F0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E900: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E910: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E920: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E930: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018E940: 00 00 00 00  00 00 00 00  00 00 00 00  43 F2 D0 01  ............C...
0018E950: 7C E9 18 00  3B 57 4B 00  01 00 6E 00  80 4B 4B 00  |...;WK...n..KK.
0018E960: EC 23 00 00  05 00 00 00  80 E6 18 00  00 00 00 00  .#..............
0018E970: 00 00 00 00  40 FB 18 00  86 00 00 00  AC F1 18 00  ....@...........
0018E980: 7F 5D 4B 00  86 00 10 85  B8 F0 B9 00  00 00 00 00  .]K.............
0018E990: AC E9 18 00  00 00 00 00  01 00 00 00  02 00 00 00  ................
0018E9A0: 11 11 11 11  A0 89 93 03  05 00 00 00  46 61 69 6C  ............Fail
0018E9B0: 65 64 20 74  6F 20 6F 70  65 6E 20 72  65 71 75 69  ed to open requi
0018E9C0: 72 65 64 20  61 72 63 68  69 76 65 20  44 61 74 61  red archive Data
0018E9D0: 2F 77 6F 77  2D 75 70 64  61 74 65 2D  62 61 73 65  /wow-update-base
0018E9E0: 2D 31 35 32  31 31 2E 4D  50 51 20 77  69 74 68 20  -15211.MPQ with 
0018E9F0: 65 72 72 6F  72 20 3A 20  35 20 0A 0A  53 74 72 65  error : 5 ..Stre
0018EA00: 61 6D 69 6E  67 20 53 74  61 74 75 73  3A 20 44 61  aming Status: Da
0018EA10: 74 61 20 52  64 79 0A 0A  57 6F 77 2E  6D 66 69 6C  ta Rdy..Wow.mfil
0018EA20: 20 64 6F 77  6E 6C 6F 61  64 20 65 72  72 6F 72 3A   download error:
0018EA30: 20 46 61 69  6C 65 64 20  74 6F 20 63  72 65 61 74   Failed to creat
0018EA40: 65 20 66 69  6C 65 20 27  57 6F 57 2E  6D 66 69 6C  e file 'WoW.mfil
0018EA50: 27 0D 0A 4D  61 6E 69 66  65 73 74 20  69 73 20 76  '..Manifest is v
0018EA60: 61 6C 69 64  2E 0D 0A 0A  0A 44 65 62  75 67 20 44  alid.....Debug D
0018EA70: 65 74 61 69  6C 73 3A 0A  0A 5B 32 39  5D 20 65 72  etails:..[29] er

------------------------------------------------------------------------------
Percent memory used:    25
Total physical memory:  17130881024
Free physical memory:   12721909760
Page file:              19681017856
Total virtual memory:   4294836224
Free virtual memory:    4159995904
------------------------------------------------------------------------------

List of running WoW processes:

Process: E:\Downloads\World of Warcraft 4.3.4\wow_434.exe; pid: 7484

**Comment by Bildo** [comment]
bt rules
