### ISSUE TITLE
[EN][Quest][Stratholme] Weapons for War

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#4530]
Wowhead Link:  [Weapons for War](http://www.wowhead.com/quest=27230/weapons-for-war) 

This quest is bugged as NPC [Black Guard Swordsmith](http://www.wowhead.com/npc=11121/black-guard-swordsmith) is missing from instance #4529

**Comment by Achiver** [comment]
Did you use the plan laying on the ground ?

**Comment by Dexobox** [comment]
Yes i did now :+1:
