### ISSUE TITLE
[EN][Emperer Vek'lor][Ahn'Qiraj 40]

### ISSUE THREAD

**Issue by spedred** [Atlantiss/BugTracker#4531]
Emperor Vek'lor and his twin Vek'nilash were killed by my group and only dropped one piece of loot and again did not drop the quest item that is a 100% chance to drop from them if you have the quest. Same thing with C'thun directly afterwards. The loot tables on wowhead show that each boss is suppose to drop a guaranteed two pieces of loot per kill. This includes both emperor's.

**Comment by Helbringer** [comment]
Nice for even killing them, people kept telling me they were bugged!

**Comment by jasiek21** [comment]
Minął rok, a quest dalej nie działa....można prosić o naprawę?

**Comment by spedred** [comment]
Sorry only english

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11635-4531-twin-emperors-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.

**Comment by spedred** [comment]
Awesome nice work and thanks
