### ISSUE TITLE
Pirate's Day

### ISSUE THREAD

**Issue by Jovana1** [Atlantiss/BugTracker#4532]
Hello there, I want to report that the event Pirate's Day don't work. I can understand that battlegrounds and raids are important, and that lot of people always ask for them if there is some bug. But, that doesn't means that other people don't care about something different that raids and bgs. World events are once per year, so lot of people(I can tell lot of people since lot of them ask in world about the event) want to take a brake from bgs and raids and enjoy the world events. That's the main purpose of them. Also, world events can help us get Violet proto drake, which is awesome. For taking Violet proto drake you dont need to finish pirate's day acheivement, but since this is only 1 day in a year it will be nice that this event works. Also, for this event you just  need to insert npcs, and we're supposed to talk with Dread Captain DeMeza so we can join his crow and that's it. Achievement earned. Because of that, I know that it's not hard to script npcs for this one. For other world events, like Brewfest or Hallow's End is a bit harder. So I want You to ask to take this npcs in game and give us a chance to fully enoy this game. If it's too late now to get this, You can always insert them tomorrow and let people know that You just changed the day for the event. I believe that You will have a lot of happy players after this.

**Comment by Wolffenstein** [comment]
It's fully scripted, it starts in about 6 hours...
