### ISSUE TITLE
Grand Theft Palomino not working!

### ISSUE THREAD

**Issue by H2OMelon** [Atlantiss/BugTracker#4533]
When stealing the horse, it is extremely slow (walk speed). If one then gets aggro from the mobs around it, the horse gets fast again, but it always turns around to the enemies, no matter which direction one goes, thus it's impossible to steal a horse.

**Comment by RandomPickNewb** [comment]
It is possible to steal a horse and its very easy.Just clear the a path and done no problem.And also you should read the rules https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by H2OMelon** [comment]
It doesn't work like it should. As stated, the horse is extremely slow (walking tempo) and takes aggro, where after taking aggro, it isn't possible to go any further with this horse.

**Comment by Corson** [comment]
Bump, same problem
