### ISSUE TITLE
[EN][Item] Qiraji Lord's Insignia

### ISSUE THREAD

**Issue by Achiver** [Atlantiss/BugTracker#4535]
<a href="http://www.wowhead.com/item=21229/qiraji-lords-insignia"> Qiraji Lord's Insignia </a> is not dropped by any boss in Temple of Ahn'Qiraj.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6997-4535-item-qiraji-lords-insignia/
