### ISSUE TITLE
[EN][Brewfest][Dungeon]Coren Direbrew

### ISSUE THREAD

**Issue by Alastia** [Atlantiss/BugTracker#4539]
the keg-shaped treasure chest rate is bugged, the rate of brewfest tokens is 91% and none in party got them, they got the satchel empty and i got direbrew's remote.

**Comment by xolon** [comment]
Don't want to create a new report, but delivering kegs for that minigame doesn't reward tokens (for horde, idk for alliance)

**Comment by Stephenjawn33** [comment]
Yeah, the keg-shaped treasure chest doesn't drop tokens, I don't know if the drop chance for the other items is the same, but tokens should drop from every keg.

**Comment by Aival94** [comment]
It is true.Some times [Keg-Shaped Treasure Chest](http://www.wowhead.com/item=54535/keg-shaped-treasure-chest) is empty but normally it should always drop at least one item(at least 10-15 [Brewfest Prize Token](http://www.wowhead.com/item=37829/brewfest-prize-token)).There is small posibility to get 2 items in the chest but still this is not important as we at least need to always have 1 item or the tokens.

**Comment by Wolffenstein** [comment]
Fixed in rev 4606.
