### ISSUE TITLE
[EN][SPELL][ROGUE]Tricks of the Trade

### ISSUE THREAD

**Issue by Quamarek** [Atlantiss/BugTracker#4545]
Tricks of the Trade cause proc of rogue's t12 bonus (even if you don't have any part of t12) ( http://cata.openwow.com/spell=99175 ) but it gives only 25 of stat (not 25%) also it started to break stealth (like few days ago, when it also started to trigger t12 bonus)

**Comment by zeoos** [comment]
Since then, it was fixed. I did not encounter this issue last few days.
