### ISSUE TITLE
[EN][Shaman][Spell][Unleash Elements][Earthliving Weapon]

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#4549]
Hello,
I just made few RHC today to cap my valor points.
I just noticed thanks to Recount addon that Unleash Elements+Earthliving Weapon [Restoration Shaman]
When you use it, It does heal for 4.5-5k [atleast that the amount of heal it does with my Resto].

But that not the reason I post this issue.
The reason is that It never crits! (Tested around 50th times UE)

And I wondered to myself because I played on different servers which the UE actually does a heal-crit!
So I think that spell should heal-crit aswell on Atlantiss.

Check it out please.

Edit:
here is screeenshot I have made from dungeon i made.
11 times i used Unleash Elements
0 crits
http://i.imgur.com/CvLfmmf.jpg

If you want tomorrow i'll make 50 times unleash elements and will post the results here.

**Comment by Kejmil** [comment]
better 1k, 50 is very little

**Comment by Illusie** [comment]
@Kejmil lolol,,, do 1k tests by yourself.

here another 26 times UE / 0 crit done. as far as i know it suppost to crit.

http://i.imgur.com/tuuxu5o.jpg

**Comment by Illusie** [comment]
@Wolffenstein bump / answer lol?

**Comment by Illusie** [comment]
what going on with that issue @Wolffenstein @armano2 ?

**Comment by Illusie** [comment]
bump

**Comment by Jenovas** [comment]
Fixed in rev 4721
