### ISSUE TITLE
[EN][Equipment Management]

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#4550]
Hello,
Sorry for that title, don't know how to classify that issue.

I'm playing Demonology Warlock for PvE
and as Demonology our important and way to DPS harder and higher is gear switching before entering to combat.
That what Demonology warlock calls "Mastery gear" <- https://www.youtube.com/watch?v=-iLDDNBRPe8

Since the Equipment Managment does not work on Atlantiss. We [Demo locks] lose alot of DPS.

I use an addon called "Outfitter" but I can't macro it and use it on my keyboard.
like /equipset 'Name of Set'

So please fix that issue, It's bother me as Demonology warlock, but I believe that other people will be happy to see that function works. It's pretty basic stuff that server must have.

**Comment by xolon** [comment]
well they fixed it today, works fine for me

**Comment by Illusie** [comment]
you right it seems like it fixed.
thanks just not noticed that :D
