### ISSUE TITLE
[EN][DRUID][CORE] Shapeshifting

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4551]
1) The power shifting ( http://us.battle.net/wow/en/forum/topic/7978989508 ) does not remove slow and roots.
How it should work: https://youtu.be/NbyKK4-nIMk?t=30 and it worked this way since TBC expansion.

2) When spam powershifting macro player ends in caster form with error "ability is not ready yet". 

/cast [stance:1] !Bear Form; [stance:2] !Aquatic Form; [stance:4] !Travel Form; [stance:3] !Cat Form; [stance:5] !Moonkin Form 

This is true for all form except moonkin form. For some reason moonkin form is not affected by this bug.

How it should work: Player shouldn't end in caster form when spam macro.

The importance of this issues is high. Powershifting is bread and butter for any pvp druid.

**Comment by blinkmaster** [comment]
Actually the most important bug with this is the fact that shapeshifting out of form does not dispel anything

**Comment by Crusaderz** [comment]
It does. Atleast it works for me when i change forms manually. Are you feral? Feral shapeshifting does not remove roots since 4.0.6.

**Comment by Jenovas** [comment]
The power shifting ( http://us.battle.net/wow/en/forum/topic/7978989508 ) does not remove slow and roots. - only in resto spec and only for moonkin. Since Cata Feral cant shapeshift out of roots

**Comment by Crusaderz** [comment]
That's what i said. Roots and slows should be removed by powershifting for balance and resto and for feral it should remove snares. It does nothing right now.

**Comment by Illusie** [comment]
should be fixed. top priority imo

**Comment by Milton3450** [comment]
Yes, and "out of form" bug is a must to fix.

**Comment by Jenovas** [comment]
Both issues Fixed in rev 4705
