### ISSUE TITLE
[EN][QUEST][Duskwood][A Curse We Cannot Lift] Quest id: 26720

### ISSUE THREAD

**Issue by seanwow1337** [Atlantiss/BugTracker#4554]
Npc hes bugged in wall. 
wowhead: http://www.wowhead.com/quest=26720/a-curse-we-cannot-lift

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the quest and NPC provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by oprinandrei** [comment]
Try it now. I had the same problem so i made an ingame ticket. A gm fixed the wall problem for me. I had to kill it, but then when the npc respawned it worked perfectly

**Comment by Dexobox** [comment]
Also another quest behaviour which is part of the bug is the quest item [Harris's Ampule] (http://www.wowhead.com/item=60206/harriss-ampule) can be used on the dead worgen. This should not be possible, I am unsure of if the item dissapears from bag in 1 charge use, but i would like to confirm that behavior.

**Comment by Thefakemccoy** [comment]
Just tried to do the quest used the potion under 25% didnt get credit. And the potion bottle is consumed once used have to abandond and repick it up

**Comment by Dexobox** [comment]
__Workaround:__
I was able to complete this quest by bringing him to 2% health . I had to remove all my gear and also hit him with just fists. But yes first time I had to kill him and wait for a respawn.

**Comment by schwim0341** [comment]
After the third time of having him not jump down in a row, I climbed up there with him using the barrels and successfully completed the quest by using the item after beating him down on the platform.

**Comment by Ambiorixa** [comment]
Confirmed. Use the barrels to jump up the ledge where he is. When he hasitate use the potion. Peace of cake.

**Comment by karhima** [comment]
Cannot confirm that. Jumping up on the ledge to him and using the potion after he hesitated with almost no HP left also doesn't give credit. Gave up on it after 4 tries. Wouldn't be so annoying if the potion stayed in your bags, but you have to abandon and come back for every try. Not worth it IMHO.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5057
