### ISSUE TITLE
[EN][QUEST][Stranglethorn Vale][Favored Skull] Quest id: 26745

### ISSUE THREAD

**Issue by seanwow1337** [Atlantiss/BugTracker#4555]
if i get quest and i complete i not found npc here: http://i.imgur.com/cfXOrxE.jpg?1
wowhead: http://www.wowhead.com/quest=26745/favored-skull

**Comment by Pallitax** [comment]
Aside from being a duplicate of #3947...

• Title doesn't follow the guidelines
• No wowhead link for the quest and NPC provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F
