### ISSUE TITLE
[EN][ITEM] Heirlooms item level

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4556]
Herlooms item level is always 1 and they does not scale. Cata dungeons requires to have minimum average item level values before player can sign up for a dungeon using the LFD tool. So players wearing herloom helm, cloak and legs basically have empty slots, since they does not contribute to player average ilevel.
How it should work: http://wow.gamepedia.com/Heirloom#Stat_values

**Comment by Thefakemccoy** [comment]
It works right for cata they never scaled up in iLvL until Mop or WoD heirloom tab cant remember which one but not in cata they was always iLvL1

**Comment by Crusaderz** [comment]
You are right: http://us.battle.net/wow/en/forum/topic/5149181758.
