### ISSUE TITLE
[Quest][Northrend][Grizzly Hills] The Horse Hollerer

### ISSUE THREAD

**Issue by Jovana1** [Atlantiss/BugTracker#4559]
Quest The Horse Hollerer is in Grizzly Hills and it's bugged. You should use quest item Flashbang Granade on Highland Mustang so it will count for Your quest, but when You do that, nothing happened. Tryed it twice and nothing.

http://www.wowhead.com/quest=12415/the-horse-hollerer

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the quest provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by armano2** [comment]
dupliacte: #3562
