### ISSUE TITLE
Missing NPC in Argent Tournament

### ISSUE THREAD

**Issue by Jovana1** [Atlantiss/BugTracker#4563]
This will be like 7th day that one NPC in Argent Tournament is missing. I'm trying to get achievement "Champion of the Horde" and I started with Silvermoon city since I'm a blood elf. Before You can earn the right to represent Your city You need to finish "The Valiant's Charge" so You need to collect 25 Valiant's Seals. You can get them from 3 different NPCs from Silvermoon city, but one of them is missing. I checked rest towns, for Orgrimmar, Undercity, Thunder Bluff, all 3 NPC's are there. Properly, You can get 5 Valiant's Seals daily, and You need 5 days for each fraction. But with missing NPC You can get only 3 Valiant's Seals daily. As I sad before, for other cities all other NPCs are there. So It will be nice if You can fix this. 
Thanks in advance :)

**Comment by Arturiccc** [comment]
Which Silvermoon NPC is missing can you tell that?

**Comment by Jovana1** [comment]
I'm not sure what's the name of the NPC since it's missing. And at the moment I'm not in AT so I can check. If You want I can check that out, and let You know about it when I finish something, and then I can visit AT.

**Comment by Jovana1** [comment]
http://wowwiki.wikia.com/wiki/Argent_Tournament You can take a look here, about quest chains. Also check "Quest part" At number 6 you will see that You can get 5 Valiant's seals daily, and with Silvermoon I can only get 3, since NPC is missing.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines
• No wowhead link for the NPC provided

https://github.com/Atlantiss/BugTracker/wiki/How-To%3F

**Comment by aranguard** [comment]
Actually its still doable but real problem here you cant continue to other factions after you became champion your own faction.So impossible to get champion of the horde.

**Comment by xolon** [comment]
Well, when i was doing it there was the same bug, tho Gms were giving me the quests for other races dunno if they will now?

**Comment by aje** [comment]
(still bugged)
fix http://community.atlantiss.eu/index.php?/topic/6632-missing-npc-in-argent-tournament/

**Comment by NatsumeLily** [comment]
This is indeed still bugged. Npc is still missing and you only get 3 marks a day when it should be 5..Makes it longer for blood elves who just started at the Tournament..

Bump bump..Fix it already..Been like this for more then 2 months...

**Comment by aje** [comment]
be patient. for now, the priority is to optimize the server because of the number of new players.
And then there is also molten core that just opened and which is a priority.

This is minor compared to those other things.

**Comment by NatsumeLily** [comment]
This npc is still missing...

**Comment by aje** [comment]
yep we know why the NPC is still not present. he was added but he is "invisible". It will be fixed soon
