### ISSUE TITLE
[PL][PROFESSION] inability to unlearn profession

### ISSUE THREAD

**Issue by Magdalenach** [Atlantiss/BugTracker#4566]
the window did not work profession red sign 'unlearn profession' I tried many times and still nothing. I uninstalled the game, I wrote the command / reload and shut down the game 'alt and f4'. Please help. For several days I try every day. 
![wowscrnshot_092315_173827](https://cloud.githubusercontent.com/assets/14807188/10049926/0bbfa50e-621a-11e5-88d5-8a16d81b472e.jpg)

**Comment by zeoos** [comment]
Have you tried just learning a second primary profession?

**Comment by Magdalenach** [comment]
yes
