### ISSUE TITLE
[EN][TALENT][WARLOCK] Mana Feed

### ISSUE THREAD

**Issue by adryjan** [Atlantiss/BugTracker#457]
Talent http://wowpedia.org/Mana_Feed is not working propertly with Felguard & Felhunter pets.  
Patch 4.1.0 (2011-04-26): Now restores more mana (four times as much) when the warlock is using a Felguard or Felhunter.

On PTR it's still 4% with all pet's instead of 16% with FG and FH.

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
