### ISSUE TITLE
[NPC][Booty Bay] Mrs. Gant

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#4571]
Still bugged.
![wowscrnshot_092415_183417](https://cloud.githubusercontent.com/assets/12395407/10079548/011ebabe-62eb-11e5-86d8-1b31ea31597a.jpg)

**Comment by Xenerus** [comment]
[Wowhead link](http://www.wowhead.com/npc=54232/mrs-gant)
