### ISSUE TITLE
[EN][NPC][Vendor] Sergent Major Clat not selling Field Marshal for some classes

### ISSUE THREAD

**Issue by jonathanargentiero** [Atlantiss/BugTracker#4572]
Sergent Major Clate in Stormwind Champion's Hall is not selling Priest and Paladin Field Marshal's sets (didn't checked for every classes).

I tested with a level 60 (experience blocked) Gnome Priest and Dwarf Paladin.

http://www.wowhead.com/itemset=389/field-marshals-raiment

**Comment by aje** [comment]
same as https://github.com/Atlantiss/BugTracker/issues/4291 so I close

by the way I posted a fix for this and it will eventualy be accepted in the future
