### ISSUE TITLE
Cross-Faction Auction House

### ISSUE THREAD

**Issue by cxcv195** [Atlantiss/BugTracker#4573]
2 different items which were listed for sale at the Booty Bay Auction House by my Alliance Character were not visible to my Horde Character.

**Comment by Aival94** [comment]
you cannot see or buy your own item in auction house(i mean same account) with an other alt i think.

**Comment by Achiver** [comment]
It is visable for your alt but you can't buy it.

**Comment by armano2** [comment]
There is 3 auction houses:
1. Cross Faction
2. Horde only
3. Alliance only

tax for listing is different.
