### ISSUE TITLE
[EN] Quest, Un-goro, Carried on the waves

### ISSUE THREAD

**Issue by zidemizar** [Atlantiss/BugTracker#4575]
Cannot gather the petals with the net.

**Comment by Aival94** [comment]
I did it yesterday and it worked just fine.You just need to go near one of them and use item.

**Comment by zidemizar** [comment]
How close to the spores are we talking, because I am right on top of them and spin multiple times but I cannot catch any.

**Comment by Aival94** [comment]
try move while using the net as maybe the net has this kind of bug which you need to move near the spore while using the item.

**Comment by zidemizar** [comment]
Okay, got it working, I was doing the ones underwater and didnt realize there were some on the ground, the ground ones worked.
