### ISSUE TITLE
[EN][Quest][Icecrown] The Fate Of The Fallen

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4578]
Discarded Soul Crystal which are needed for the quest are not spawned in the quest area.  There are small blue circles of light on the ground where those are supposed to be but no crystals.
Quest is not completable at the moment.

Quest ID - http://www.wowhead.com/quest=14107
Discarded Soul Crystal (item) - http://www.wowhead.com/item=47035
Discarded Soul Crystal (object) - http://www.wowhead.com/object=195344

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12508-45787836questicecrown-the-fate-of-the-fallen/
