### ISSUE TITLE
[EN][Npc][Thunderbluff] Jewelcrafting Trainer

### ISSUE THREAD

**Issue by Krooks187** [Atlantiss/BugTracker#4584]
Nahari Cloudchaser, the jewelcrafting trainer is missing from her shop on the lower bluff.
http://www.wowhead.com/npc=52657/nahari-cloudchaser

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6654-npc-add-missing-npcs-in-thunder-bluff/
