### ISSUE TITLE
Corki's Ransom[QUEST]

### ISSUE THREAD

**Issue by albylord** [Atlantiss/BugTracker#4591]
http://www.wowhead.com/quest=9954/corkis-ransom
This quest cannot be completed, since the npc (http://www.wowhead.com/npc=18445/corki) you should talk to, simply says: "greetings".

**Comment by Articuno** [comment]
I can confirm that.

**Comment by albylord** [comment]
Update: casually I found another "corki" in the south-west of nagrand and I could complete the quest. However this should be fixed, since that is not the right one.
