### ISSUE TITLE
[EN][Mage] Pyroblast procs Pyroblast

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4594]
## What's wrong:
Pyroblast procs Pyroblast.

## How it should be:
Instant Pyroblast should not proc Hot Streak or Improved Hot Streak because it is listed as another spell ( "Pyroblast!" ) . 

The problem it is at Hot Streak and also at Improved Hot Streak.
The instant Pyroblast it's not a normal Pyroblast, it's name it's actualy "Pyroblast!".

## proof:
http://eu.battle.net/wow/en/forum/topic/1839965053
http://forums.elitistjerks.com/index.php?showtopic=109377
http://www.youtube.com/watch?v=rfsQOCSsX1k

**Comment by blinkmaster** [comment]
never happend to me. cant confirm

**Comment by blinkmaster** [comment]
after 500 pyroblast! crits it never happend to me to proc another pyroblast!.
wrong report or individual bug.

**Comment by razgal** [comment]
It doesn't happen anymore, I don;'t know if it was a visual bug.

I'll close and re-open if tihs will ever happen again.
