### ISSUE TITLE
[EN][Mage] Flamestrike

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4597]
## What's wrong:
Each Flamestrike makes his separate damage when they are stacked,which it's incorrect.

## How it should be:
* 1. When you spam Flamestrike in a single place ,there should be just 1 dot ACTIVE which will tick continuously even if there are other Flamestrike overlapping only it's duration it's reset back to 8 sec.
* 2. As long as Flamestrike 's are not overlapping each other and you are casting them on different spots they should have their individual damage.

## Proof:
http://us.battle.net/wow/en/forum/topic/2211762512
 *!* Attention. This effect doesn't have DR,even if you have 100 mobs in your flamestrike's the damage of dot should be the same.

**Comment by Badrng** [comment]
Flamestrike's dot ticks 4 times over 8 seconds. If what you claim was true then by stacking two flamestrikes on top of each other under a single target I would be getting 8 ticks in total. Instead, I only get 5, which seems fine since the 5th tick belongs to that latter flamestrike which lasts longer due to gcd. Seems fine unless I got something wrong.

**Comment by blinkmaster** [comment]
just as above - it works fine. visually there are alot of FSs but only the last one damages.

**Comment by Rushor** [comment]
```c++
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 36f70b8..e4e8045 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -1936,7 +1936,8 @@ void Spell::EffectPersistentAA(SpellEffIndex effIndex)
         if (!caster->IsInWorld())
             return;
 
-        caster->RemoveDynObject(m_spellInfo->Id);
+        if (caster->GetTypeId() == TYPEID_PLAYER)
+            caster->RemoveDynObject(m_spellInfo->Id);
 
         DynamicObject* dynObj = new DynamicObject(false);
         if (!dynObj->CreateDynamicObject(sObjectMgr->GenerateLowGuid(HIGHGUID_DYNAMICOBJECT), caster, m_spellInfo->Id, *destTarget, radius, DYNAMIC_OBJECT_AREA_SPELL))
```
