### ISSUE TITLE
[EN][Mage] Spell resistance vs. polymorph

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4600]
## What's wrong:
spell resistance doesn't work against Polymorph,tested 100 polymorphs against another mage with 142 arcane resist,and no poly was resisted

## proof that it should:
http://www.wowwiki.com/Talk:Polymorph
"Polymorph CAN be resisted (unpleasnt personal experience!) but this isnt too much of a problem; just cast it again. The spell is arcane so presumably arcane resistance helps? Damoloces"

**Comment by blinkmaster** [comment]
actually its not polymorph bug but spell resistance - on our server it only decrease the dmg of spells but not making them be able to be resisted. thus some classes dont even bother to gem spell pene, gaining slight advantage in dps in pvp ;)
