### ISSUE TITLE
[EN][Mage] Blink range

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4603]
## What's wrong:
Blink seems to have a bigger range than it should.
Normal blink (without glpyh) should have 20yards range.On our server it has more than 20yards,maybe around~23yards range.With glyph it has even more than 25yards, maybe ~28 yards.

## How I tested it:

(without glyph of blink)
I put my Feral in same position with mage.
Feral Charge has a 25yards range.Blink has 20yards range(without glyph).
Mage Blinks and it moves ~2 yards in front, I can't reach with my Feral to feral charge.

(with glpyh of blink)
I put my Feral in same position with mage.
Feral Charge has 25yards range. Blink has 25yards range(with glyph).
Mage Blinks and it stays where it is. I can't reach it with my Feral to Feral Charge, even though both have same range.
Here I have to move with my feral ~3yards in front,to actually be able to leap.

**Comment by planche** [comment]
I can confirm that I can't reach mage with shadowstep after blink.

**Comment by Wolffenstein** [comment]
Fixed in rev 4623.

**Comment by razgal** [comment]
#high-five wolfenstein
