### ISSUE TITLE
[EN][Quest][Northern Barrens] Into the Raptor's Den

### ISSUE THREAD

**Issue by ObiVanKenobi** [Atlantiss/BugTracker#4608]
You need to visit 3 nests Red Yellow and Blue. Red and Blue nest works fine but you cant do for Yellow nest never count as done.

**Comment by kimo8532** [comment]
Visual bug

**Comment by ObiVanKenobi** [comment]
what visual bug quest is undoable?

**Comment by kimo8532** [comment]
You can complete it make sure you went at all 3 nests then just hand it in
Trust me i done it already enough times

**Comment by ObiVanKenobi** [comment]
thanks

**Comment by Angelo-DM-** [comment]
This quest works 100% blizzlike.

**Comment by Angelo-DM-** [comment]
#3398
