### ISSUE TITLE
Book of Glyph mastery - chance to drop

### ISSUE THREAD

**Issue by mikonek07** [Atlantiss/BugTracker#4609]
I ve been trying to find some http://www.wowhead.com/item=45912/book-of-glyph-mastery#dropped-by 
by killing http://www.wowhead.com/npc=32255/converted-hero .
After few hrs of killing i got 0 books.  It's not the best proof, better in my opinion is comparison to another item http://www.wowhead.com/item=43297/damaged-necklace.
According to Wowhead Damaged necklace has 2.5x lower drop chance than Book of Glyph mastery.
After this hrs of killing i got about 10 damaged neckaces. 
In the event of farming books of glyph mastery, there is also another inconvenience - there are no treasue chests in Northrend and Cataclism zones with makes books even harder to get.
I ask for fixing drop rate of books to ~ 1% from every monster in Northrend or, what may be much better, adding chance  to drop books from cataclism monsters and zones [ Blizzard fixed problem with books in next expansion - it proofs that they had done mistake in Cata about this books ].

**Comment by user1011** [comment]
#4502

**Comment by aje** [comment]
I posted a fix for this issue, just wait some time before it is on the server.

I close since it is a duplicate
