### ISSUE TITLE
You have entered to many instances recently

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#4610]
if you enter any instance without even killing any boss inside it it counts towards the blockade, thats a bug and it locks you out like when you do it like me and enter all instances in hellfire to try to find magetheridons lair and then it locks you out

**Comment by xolon** [comment]
if you enter an instance x5 times or enter 5 different instances inbetween 1 hour, you will get cannot enter 6th until 1 hour passes after you entered 1st one
