### ISSUE TITLE
[EN][Instance - TBC] Heroic mode for Magisters' Terrace inaccessible

### ISSUE THREAD

**Issue by Zenokin** [Atlantiss/BugTracker#4611]
I wanted to run Magisters' Terrace Heroic for transmog gear but always get the message "You must be at least level 65 to enter Heroic Difficulty". 

Screenshot: http://imgur.com/ScvvpS0

**Comment by Drutmaster** [comment]
Well, on Atlantiss you need to do old quests chain to obtain access for MT hc mode. Chain starts in Shattrah City from Aldors or Scryers - depends on your faction choice

**Comment by Zenokin** [comment]
Oh thanks, I'll try looking for it. Could you tell me the name of the quest, by any chance? 
Wish it told me something about that, instead of giving that error message.

**Comment by Faaith** [comment]
http://google.com
http://wowwiki.wikia.com/wiki/Portal:Main
http://wowhead.com

That's all you need to check before posting false reports. Took me 2 minutes to find the quest and all info I needed.

**Comment by Zenokin** [comment]
I did search for it before posting here, but I couldn't find anything. Eventually, I found a thread on the WoW forums where I found more information. The quest seems to be "Duty Calls" or "Crisis at the Sunwell" depending on your faction. I didn't get a chance to look for it yet.
Also, I certainly did not post false reports, I even provided a screenshot with the error. It would also be nice if you could actually provide the details, instead of acting like an asshole.
