### ISSUE TITLE
[EN][Dungeon-TBC] Sunwell Plateau

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4613]
http://www.wowhead.com/zone=4075/sunwell-plateau

This Raid is completely closed, I checked and did not see a bug report on this, nor a rule about it, so I figured I should mention it.  When you go to enter it in a raid group it just gives you the "This instance is closed" Message. 

The raid is required for two achievements (Outlands Raider and Sunwell Plateau), as well as for several pieces of transmog gear.

**Comment by LaveGit** [comment]
It's because of the bosses in there.
Some are unkillable, and I think that last boss crashes the server, so they decided to close it for now.

**Comment by LordKnightCecilo** [comment]
Alright, I just didn't see anything on it. Better safe than sorry and all.
