### ISSUE TITLE
[EN][Quest][Darnassus] The Sister's Pendant

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4618]
http://www.wowhead.com/quest=29324/the-sisters-pendant

Minor quality of life problem, both the progress and completion text is missing for the quest.

What the texts should be --

Progress Text - Have you had any luck finding Aquinne's missing pendant? I must've caught fifty of those monsters and I have nothing to show for it! 

Completion Text - <Astaia takes the pendant from you.>

Underneath all the slime and tarnish, I think this is it! Aquinne will be so happy to have this back... after a thorough cleaning, of course. I can't thank you enough, <name>.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7496-4618questthe-sisters-pendant/
