### ISSUE TITLE
The Oculus - Mage Lord Uthom

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#4620]
http://www.wowhead.com/npc=27655/mage-lord-urom
after u defeat his summonings 2 times at the third time he doesnt spawn any and because of that he doesnt show up in the middle of the ring wich causes you to not be able to complete the dungeon

**Comment by Achiver** [comment]
Maybe you used charge or any stun on one of his images ? If you do so , he disappears and you cant kill him and then the last boss.
