### ISSUE TITLE
[EN][Warlock][Item] Warlock t11 2p bonus

### ISSUE THREAD

**Issue by klm670** [Atlantiss/BugTracker#4623]
The warlock t11 2 piece bonus doesn't correctly reduce the cast time of Hand of Gul'dan by 10%. The cast time is exactly the same with and without set bonus. The cast time is 1.4s including my haste. And the cast time should be reduced by 0.14 seconds, however with set bonus it remains 1.4s cast time, effectively making the 2 piece bonus no bonus at all.

**Comment by Glare** [comment]
I'm pretty sure it doesn't work at all, not only for HoG.

**Comment by fafal** [comment]
Are sure about that? For me looks fine but maybe its too late and im blinded.

**Comment by anxanas** [comment]
It works fine, just close this topic, so there can be more focus on real bugs
