### ISSUE TITLE
[EN][druid][resto] master shapeshifter

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#4627]
transforming to travel form, aquatic form, (TREE form),swift flight form ,flight form = remove master shapershifter !! and to fix that we need to change to bear than to normal form BUT when I use tree I already lost master shapeshifter ...so 31 second tree form healing low ! since no master shapeshifter ......I hope u guys fix that imba bugg because its very important !!! so my heal increase a lot....for everyone else that don't know master shapeshifter  , if u lose it and u have itemlvl  350 means u lose around 1600 intellect ** logically speaking and the higher itemlvl the worse loss u lose ... hope taking this into consideration .. thx u.

**Comment by Jenovas** [comment]
Duplicate - https://github.com/Atlantiss/BugTracker/issues/4214
