### ISSUE TITLE
[EN][Talent][Paladin] Sanctity of Battle

### ISSUE THREAD

**Issue by Charybdo** [Atlantiss/BugTracker#4629]
This talent : http://www.wowhead.com/spell=25956/sanctity-of-battle Calclate EVERY speed of our character, movement speed, casting speed, atack speed and count speed buff for lower cd Crusader strike and divine storm and count speed DEBUFF for increase cd Crusader strike and Divine storm. Properly working is only lower our cd from only atack speed [ not count movement speed ], there shouldn't be any increasing for our skills, only decreases cd.

I think i don't need any aproove, it is write in description of talent and at wowhead site : http://imgur.com/B1RqBKA  

There isn't wrote that "haste affect our cooldown of your skills..." but LOWER.

I hope you fix it fast, it's very important skill for retri paladin :)

**Comment by Aival94** [comment]
Write your title as supposed to: https://github.com/Atlantiss/BugTracker

sth like [EN][Sanctity of Battle][Paladin]Description Title should be ok as sometimes reports get closed because of no proper title.

**Comment by Jenovas** [comment]
Should be fixed in rev [4623]
