### ISSUE TITLE
[EN][Quest][Dalaran] Disarmed!

### ISSUE THREAD

**Issue by Apehiron** [Atlantiss/BugTracker#4630]
Hi, the daily quest of fishing "Disarmed" whe you have to fish an arm from the Dalaran Prision Waters doesnt work, can you check it out plz? Thx very much!! 

[wowscrnshot_100515_163347](https://cloud.githubusercontent.com/assets/14956088/10291361/c6d12a5c-6b7f-11e5-8f66-bff35eb52f95.jpg)

**Comment by Anhaeyn** [comment]
Fishing in Dalaran is bugged at all, you can't fish there, so you can't do some dailies and get many achievments soo title isn't possible to gain too.

**Comment by Bildo** [comment]
fixed by Wolfenstein
