### ISSUE TITLE
[EN][Quest][Darnassus] An Old Favorite

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4632]
http://www.wowhead.com/quest=29359/an-old-favorite

This quest is missing the progress and completion text, again small quality of life things.

It should be 

Progress - Did you get those herring? 

Completion - Thanks! I wonder what I should do with this batch...

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7495-4632questan-old-favorite/
