### ISSUE TITLE
[EN][Quest][Darnassus] Stocking Up

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4635]
http://www.wowhead.com/quest=29323/stocking-up

Another minor quality of life problem, this quest is missing its Progress and Completion text

It should be --

Progress - If all of our fishermen pitch in, it won't take long to rebuild our supplies. 

Completion - These are beautiful! Thank you, <name>. I'll set them out to dry.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7494-4635queststocking-up/
