### ISSUE TITLE
[PL][Quest][Dun Morogh] To the Surface

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#4636]
Rozmawianie z NPC nie przenosi postaci na powierzchnię.

http://www.wowhead.com/quest=27674/to-the-surface

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7440-4636quest-to-the-surface/?p=27295

**Comment by BAndysc** [comment]
@cano112, thanks
rev [4849]
