### ISSUE TITLE
[EN[Spell][Shaman] Unleash Elements 

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4638]
Unleash elements proc windfury from RANGE and every windfury hit also proc flametongue from other weapon. This is shouldn't be possible, only melee strikes should proc WF.

Shamans running around for months, doing damage they not supposed to do.

**Comment by blinkmaster** [comment]
https://github.com/Atlantiss/BugTracker/issues/4273

**Comment by blinkmaster** [comment]
btw can some1 post the correct formula for searing totem dmg of enh shamans? still i dont see its here on bugtracker and i assure u totem hitting 5-6k in pvp is not normal on this season.

**Comment by Kejmil** [comment]
totem is double dipping of enh mastery

**Comment by Bastion** [comment]
bugujo?

**Comment by Scrimish** [comment]
if they going to do that i hope they will fix at the same time mealstorm which is not proccing if dmg is absorbed (which it should, fighting with anybody with absorbtion shields is like pain in the arse)

**Comment by deadlycalm** [comment]
why you removed high priority? fix enh shaman globaling in pvp

**Comment by BialyADI** [comment]
Bump :P

**Comment by Jenovas** [comment]
Fixed in rev 4721
