### ISSUE TITLE
[EN] Tol Barad minimum players cap

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4639]
According to this source: http://www.mmo-champion.com/threads/820256-Tol-Barad-Strategy-Guide
the minimum tol barad cap before 1:1 ratio kicks in is 25 players. I often can't join to TB while /who z-"Tol Barad" shows less than 25 in the zone. So it's clearly not working as intended

16 players
![tb](https://cloud.githubusercontent.com/assets/3641625/10333045/f3c51e7c-6ce9-11e5-90f4-e9ee70d0f2e7.PNG)

**Comment by Jenovas** [comment]
We already talked about this many times. Many pages show different info. Some pages say that from the start the ratio is 1:1, some that after 10, some after 20, some after 25.

Closing.

**Comment by Crusaderz** [comment]
Well, actually, info about 25 players cap came from official blizzard community manager, Zarhym.
His post was saved by mmo-champion blue-tracker service:
http://blue.mmo-champion.com/topic/19293-tol-barad---wintergrasp/#post17

**Comment by Jenovas** [comment]
Do you see the date of that post? It was when Patch 4.0.1 was live, the very start of Cata.
We did tests with MoP and there the minimum tol barad cap was I think 5 or even 1.

**Comment by Crusaderz** [comment]
There is plenty post on blizzard forum dated 2011 (active cata), where players complain about being outnumered on a heavy one-sided servers, like 1:2. Hows it's possible without minimum cap implemented?

Anyway, atlantiss faction ratio is very balanced, every side can participate in TB, but if alliance choice not to do so, why should horde suffer? Alliance should encourage their players to join TB if they want victory.
![online](https://cloud.githubusercontent.com/assets/3641625/10340585/7c0637ec-6d19-11e5-824e-d1d1f8d5cca7.PNG)

Here, i did this screenshot while i awaited TB invite (happens so many times), unable to join, because it was full and because TB queue is not real queue (first come first served) but random invite throwing fest. 

P.S.
I thought min cap is implemented on atlantiss but does not working well, because when horde had 16 players, alliance had 10
![tb_alliance](https://cloud.githubusercontent.com/assets/3641625/10341142/31a12bbe-6d1c-11e5-8035-3d550f6186a8.PNG)

and later changed to 18:11
