### ISSUE TITLE
[EN][Spell][Shaman] Spirit Link Totem interraction with Smoke Bomb

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#464]
There was a bug on retail that made Smoke Bomb most likely always negate Spirit Link Totem HEAL till MoP. To fix it you probably need to make SLT(maybe it should be even applied to all the totems) immune to Smoke Bomb debuff effect. Actually SLT is working like on MoP.

http://youtu.be/d1Sp_JN-swA?t=3m46s // SLT Smoke Bomb
http://youtu.be/Wmzlh6ZIg4M?t=4m42s // Another SLT Smoke Bomb
http://youtu.be/GAbRoY1Mm6Y?t=1m24s // Another SLT Smoke Bomb
http://youtu.be/GAbRoY1Mm6Y?t=3m59s // Another SLT Smoke Bomb
http://youtu.be/GAbRoY1Mm6Y?t=16m46s // This is the best SLT movie that shows SLT totem should be immune to Smoke Bomb Effect but it isn't on PTR. I just think this is the main issue why it was bugged on retail.

http://us.battle.net/wow/en/forum/topic/5826412849 // Cyclone & SLT interreaction, it's diffrent mechanic but it's kinda strange too. Maybe it will help in interpretation how SLT is supposed to work.

http://cata.openwow.com/spell=98008 // Spirit Link Totem
http://cata.openwow.com/spell=76577 // Smoke Bomb

**Comment by kadi2** [comment]
The answer and explanation can't be short, all the private servers are fixing this just by making Spirit Link Totem totally useless whenever it has Smoke Bomb debuff.
First of all, I am not sure if i am interpreting this mechanic correctly, so I advice you to watch atleast posted movies. In my opinion Spirit Link Totem or the trigger that heal people (if there is any) should be immune to Smoke Bomb debuff to make it work blizzlike way.

Whatever there are 2 possible scenarios that doesn't match blizzlike mechanic and i added MY explanations to them:
(IB) - Inside Smoke Bomb
(OB) - outside Smoke Bomb
1.SLT(IB), Player1(IB), Player2(IB) // Shouldn't work since SLT is immune to Smoke Bomb debuff and can't connect with targets that have Smoke Bomb debuff
2.SLT(IB), Player1(OB), Player2(OB) // Should work since SLT is immune to Smoke Bomb debuff and can connect with players(OB) only.

**Comment by nerv234** [comment]
Shouldn't iot works like totem works on u when totem and you have or not have debuff from smoke bomb? Simpliest and most propabliest explaination imo.

**Comment by kadi2** [comment]
@nerv234 It actually works this way on the Atlantiss, the only diffrence is that SLT was immune to Smoke Bomb debuff on retail.

**Comment by nerv234** [comment]
So i don't know how it should works.

**Comment by kadi2** [comment]
Podobno naprawione.
