### ISSUE TITLE
Shaman Maelstorm proc display bug

### ISSUE THREAD

**Issue by Jarovid91** [Atlantiss/BugTracker#4640]
I ply with enhancement shaman and i have problem with talent called "Maelstorm Weapon". For each proc that we get from that talent we should get animation above our char head (animation that looks like lighting) problem is i get that animation only when i get whole 5 stacks and not before. Can you pls fix this problem? We dont cast spells only when they got on full 5 stacks and knowing that you have 3 or 4 maelstorm proc can sometimes be a lifesaver (casting heals in 1 sec or hex and so on...)

I added some pictures where you can clearly see what im talking about (you can see maelstorm proc in the right corner of this picture) and no lighting animation above my character. Only when i get whole 5 stacks animation shows up showing that i can instant cast my skills.

![wowscrnshot_100715_161047](https://cloud.githubusercontent.com/assets/15015962/10339970/3df87af6-6d0e-11e5-99d3-5bb7e1637fdd.jpg)
![wowscrnshot_100715_161050](https://cloud.githubusercontent.com/assets/15015962/10339969/3df6cb98-6d0e-11e5-88a0-7ec7a9d7a5ef.jpg)
![wowscrnshot_100715_161051](https://cloud.githubusercontent.com/assets/15015962/10339971/3df9f944-6d0e-11e5-939f-00b06f2d1086.jpg)
![wowscrnshot_100715_161053](https://cloud.githubusercontent.com/assets/15015962/10339972/3e00ce18-6d0e-11e5-8617-9c81f90cffb3.jpg)

**Comment by xolon** [comment]
i think that was adden in mop, i mean visual for every stack you get

**Comment by Jarovid91** [comment]
you can see in picture 4 that i have maelstorm proc display above my head

**Comment by xolon** [comment]
You get the animation for 5 stacks, but not for others,i wanted to say that animations for 1,2,3,4 stacks were added in mop

**Comment by Bastion** [comment]
no mop, wod

**Comment by Jarovid91** [comment]
are u guys 100% sure? and if u are can you tell me what addon should i download so i can track maelstorm better (also i would like to know how can i disable default one cuz its only showing 5 stack proc witch is retarded...

**Comment by xolon** [comment]
Weak auras, whisper me in the game (Sniprep) and i'll tell you how to set it up for mael stacks
