### ISSUE TITLE
[PL][Spell] Rune of the Fallen Crusader

### ISSUE THREAD

**Issue by Smiite** [Atlantiss/BugTracker#4643]
Runa prawdopodobnie nie nalicza pasywki od dk unh 25% do str .
http://imgur.com/k7IQRIC    z hornem
http://imgur.com/DQaMSbs
Z hornem mam 7019 str czyli runa powinna mi dać 1052 a daje tylko 810.

http://imgur.com/w88c0Dt    bez horna
http://imgur.com/45lELw5
Z 6035 str runa powinna dać 945 str a dodaje 727

**Comment by Jenovas** [comment]
Runa jak i pasyw dają % wartości STR, z tego co mi wiadomo buffy od statystyk nie powinny się mnożyć tylko dodawać.

Przykład:
Postać ma bazowo 1000STR.
Wybierasz UH spec i dostajesz 25% STR. Twój STR wynosi teraz 1250.
Runa daje Ci kolejne 10%, ALE nie 10% z 1250 tylko 10% z 1000STR, czyli w sumie masz jakby jeden buff +35% do STR i masz 1350 STR.

Jeżeli macie jakieś tematy / filmiki / jakiekolwiek dowody że buffy nie powinny się dodawać proszę zrobić o tym temat. Zamykam.
