### ISSUE TITLE
[EN][Quest][Ironforge] A Fowl Shortage

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#4644]
http://www.wowhead.com/quest=29352/a-fowl-shortage

Like the quests in Darnassus, this quest is just a minor quality thing, it is missing the progression and completion text.

Progress - The chickens, <name>, do ye have them or not? 

Completion - Aye, that's exactly what I needed. Ye have me thanks, <name>, and me apologies fer bein' so brusque earlier. I just cannae stand the thought of not gettin' a meal finished on time.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7492-4644a-fowl-shortage/
