### ISSUE TITLE
[EN][Spell][Death knight][Bloodworm]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#4645]
The bloodworm's heal is about 2-times weaker than his buff ("Blood Gorged") tells. So instead 20% of my max.health I get only 10%, instead 50% only 25%, etc

**Comment by Jenovas** [comment]
May burst, healing nearby allies for X% of ITS maximum health.
It doesnt heal you for 20% it heals for 20% of the bloodworms health.
