### ISSUE TITLE
[pl][core] Instant Spells and LoS

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#4647]
zdarza się, że kiedy osoba A castuje spell instant np deep freeze - nazwijmy go X, a osoba B wbiega w tym momencie za Line of sight, spell X "znika" - cooldown wchodzi, efektu brak. 
dzieje się tak tylko z instantowymi spellami

**Comment by debtheone** [comment]
LAVA LASH W CORNER :D

**Comment by debtheone** [comment]
bump

**Comment by Jenovas** [comment]
Fixed in rev 4714
