### ISSUE TITLE
[EN][Talent] Nature's Grace

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#4654]
Nature's Grace is supposed to give you 15% spell haste. The issue is that your Moonfire and Insect Swarm DoTs aren't hastened, instead their duration is actually increased by roughly 1 second.

http://cata.openwow.com/spell=61346

**Comment by Jenovas** [comment]
That is what happens when you gain haste but not enough for a new tick.
Please do a proper test. Example
" 10%haste + 15% NG = 25% - 25% should be 10 ticks of moonfire, I have only 9. When I normally get to 25% I have 10 ticks."

Closing.
