### ISSUE TITLE
[EN][Guild] Guild ranks bugging out after server restart/crash

### ISSUE THREAD

**Issue by linesar** [Atlantiss/BugTracker#4656]
it happened to the guild <LAW> twice yesterday, the ranks got set to default and got bugged 2 times after 2 server crashes/restarts, dunno how to explain it more since that is in detail what happened and i cant give much more info about it.
It is basically the same problem as https://github.com/Atlantiss/BugTracker/issues/2210

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/2210
