### ISSUE TITLE
[EN][Spell] Have Group Will Travel

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#4658]
the guild perk doesnt work at all
http://wow.gamepedia.com/Have_Group,_Will_Travel
it was removed in Mists of Pandaria so it should be able to function on 4.3.4.
Cant provide spell IP

**Comment by Aival94** [comment]
The spell is working but not blizzlike.The bug it has is that you cannot summon someone who is on other continent(for example from eastern kingdoms to kalimbor(probably you can summon someone from tbc starting zones to outland)) but if you are on same continent it work just fine.

**Comment by xolon** [comment]
Also you have to target someone (also needs to be on your continent) and summon wont work on ppl who are using flight paths

**Comment by Samineh** [comment]
:+1:

**Comment by krecik88** [comment]
fixed 5378
