### ISSUE TITLE
[EN][Spell][Mage] Mirror Image - class mage

### ISSUE THREAD

**Issue by kasztek124** [Atlantiss/BugTracker#4659]
Witam, bug dotyczy skilla "mirror image", mianowicie chodzi o to że po odpaleniu owego skilla pojawiają się 3 nasze odbicia lecz nie atakują do czasu gdy coś w nie uderzy. Jest też czasami tak że "oberwie" tylko jeden i tylko on atakuje.

**Comment by klm670** [comment]
The tag says English but it's clearly polish...
But they don't attack targets indeed.

**Comment by blinkmaster** [comment]
https://github.com/Atlantiss/BugTracker/issues/2617
https://github.com/Atlantiss/BugTracker/issues/2059
