### ISSUE TITLE
[PL] [Glyph] [Druid] Glyph of Bloodletting

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#466]
- http://wowpedia.org/Glyph_of_Bloodletting
- http://cata.openwow.com/item=40901

Glyph działa o dwa dodatkowe ticki za dużo.

Jak powinien działać:
- po użyciu odpowiedniego ataku dodaje +2s do czasu trwania debufa Rip, maksymalnie 6 sekund (3 razy)

Jak działa:
- po użyciu ataków dodaje poprawnie +2s do czasu trwania Rip, jednak można uzyskać ten efekt 5 razy (+10 sekund)

W czasie unikatowego cyklu powinniśmy uzyskać 11 ticków, a uzyskujemy 13.

![wowscrnshot_112514_195920](https://cloud.githubusercontent.com/assets/6035437/5189379/a899aea4-74dd-11e4-9b22-125c256f45b8.jpg)

**Comment by Jenovas** [comment]
Fixed in rev 4360
