### ISSUE TITLE
[Talent][Unholy Death Knight] Runic Corruption

### ISSUE THREAD

**Issue by aranguard** [Atlantiss/BugTracker#4660]
I realized 2 problems.

1.Its normaly should have same chance to proc Runic Empowerment which is %45 chance but it procs a bit rare.Sometimes using 8-10 death coil without proc.

2.And here is main problems it procs by vision only.I see the buff procs but when i use scourge strike after it procs still gain 10 runic power.It should be %100 more with 2 points talent means 20.Same for Festering strike.Using after proc but still gets 20 runic power not 40.

its very bad for uh dk dps.

**Comment by Kejmil** [comment]
1. bad rng, try with 10k samples

2. https://www.youtube.com/watch?v=DUvADbpqGlQ

**Comment by Jenovas** [comment]
Runic Corruption increases Rune Generation not Runic Power Generation. So number 2 isnt a bug.
Also the proc chance is around 50%, sometimes you will have bad luck and no proc for 8-10 deathcoils and after that you'll have runic corruption on for 30 seconds.
