### ISSUE TITLE
[EN[Guild] News

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#4665]
News don't display boss encounters defeated
http://i.imgur.com/wsOxyTH.jpg

**Comment by mitim1** [comment]
"Nefarious defeated Unknown"

**Comment by Malylolek** [comment]
#864

**Comment by xolon** [comment]
Sorry, unknown just shows for normal diff bosses or dungeon ones, yday guild defeated few on hc and on pic you don't even see unknown bug
