### ISSUE TITLE
[PL][Quest][Blackrock Mountain] Blackhand's Command

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#4666]
http://www.wowhead.com/npc=9046/scarshield-quartermaster
Brak tego NPC przez co nie można zdobyć http://www.wowhead.com/item=18987/blackhands-command i rozpocząć q na szybszy tp do BWL

Na WoD dopiero usunięty

http://www.wowhead.com/object=179879 - pierwszy komentarz a także brak tego orba
https://www.youtube.com/watch?v=NJZswzneYyg - jak wygląda

http://www.wowhead.com/npc=9044/scarshield-sentry
http://www.wowhead.com/npc=9043/scarshield-grunt 
Brak tych npc

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7893-4666questblackrock-mountain-blackhands-command/
