### ISSUE TITLE
Dragon Breath

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#4667]
http://www.wowhead.com/spell=31661/dragons-breath
when a mages uses this on a player he cant move afterwards, hes forced to jump first then hes able to move around

**Comment by scidrov** [comment]
tested in a duel didint see it happen but im 100% sure it happend on bg where the only thing i could do was to turn around and not be able to move

**Comment by Helbringer** [comment]
Proberly allience passive.

**Comment by mitim1** [comment]
https://github.com/Atlantiss/BugTracker
WRONG TITLE.
