### ISSUE TITLE
[EN][Achievement][Bastion of Twillight] Double Dragon

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#4670]
The achievement Double Dragon from the Valiona & Theralion encounter in the Bastion of Twillight isn't working. The Twillight Fiends are simply not spawning at all.

http://www.wowhead.com/achievement=4852/double-dragon

![double dragon](https://cloud.githubusercontent.com/assets/12621497/10466720/122cdc90-71f6-11e5-8ea7-66d317943873.png)

How it should work: https://www.youtube.com/watch?v=VxhwKtB6Kro

The Twillight Fiends should spawn inside the Twillight Realm.

That's the only achievement that's not working for the Meta-Achievement: Glory of the Cataclysm Raider. (http://www.wowhead.com/achievement=4853/glory-of-the-cataclysm-raider), and is therefore not obtainable.

**Comment by LaveGit** [comment]
Bump. Any info about this?

**Comment by Aviannaqt** [comment]
Quban pls Double Dragon :<

**Comment by xolon** [comment]
#2020

**Comment by xolon** [comment]
#quban2020

**Comment by LaveniaGithub** [comment]
#2020

**Comment by LaveniaGithub** [comment]
#2020hype

**Comment by Sayris9876** [comment]
High priority since januray.... please fix :((

**Comment by Malylolek** [comment]
Already send to Developers to check my fix, hope it good and go live !

**Comment by Sayris9876** [comment]
Ayyyy finally... lets hope its all good now. Thanks!!

**Comment by LaveniaGithub** [comment]
#CeciditDoubleDragon2016

**Comment by Malylolek** [comment]
Volcano 32k wink wink

**Comment by Malylolek** [comment]
Propably fixed in rev. [5137](http://atlantiss.eu/changelog#rev5137).
