### ISSUE TITLE
[EN][Spell][Druid] Savage Roar

### ISSUE THREAD

**Issue by stefannis** [Atlantiss/BugTracker#4677]
If you cast Savage Roar in Cat Form and switch to Bear Form it will not affect your auto attack damage (in Bear Form)
You can cast Savage Roar in Bear Form and it will affect your auto attack damage in Bear Form

**Comment by razgal** [comment]
what? you can use savage roar in bear form?)) well there's a bug.

and indeed doesn't affect your auto-attack damage in bear-form.

**Comment by stefannis** [comment]
it does not if you use it in cat and then swap but if you use it in bear it does

**Comment by Thefakemccoy** [comment]
Well to clear that up savage roar should only be able to be cast in cat form so if you can cast savage roar in bear form it is broke.

http://cata.openwow.com/spell=52610

**Comment by stefannis** [comment]
yea I said that but thank you for repeating it you the champ

**Comment by Thefakemccoy** [comment]
yes i know im not sure why this report wasnt closed but maybe since i the champ supplied a link it will stay open

**Comment by razgal** [comment]
you supplied what?a link that you can see in tooltips aswell? there are 2 bugs in this report:
1. you can use savage roar while in bear form, which it shouldn't
2. savage roar if it's casted in cat form damage should be transfered in bear form, which is not.

**Comment by Thefakemccoy** [comment]
yes i supplied a link that was never given does not matter what a tootip says the guid lines for reporting requires you to post a link. (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker

**Comment by stefannis** [comment]
A link on the bug dosent exist since there isn't one on blizzard the buff stays but dosent affect the damage on atlantiss if you cast it in bear it is there and it affects the damage if you find a link that says that (that I didn't) feel free to post it here champ

**Comment by Jenovas** [comment]
You should ALWAYS and a link of the BUGGED SPELL not to a topic about the bug.

**Comment by stefannis** [comment]
yea someone checking the spell needs the link to go ahhh right that's the spell they are talking about sure allright

**Comment by Jenovas** [comment]
Fixed in rev 4705
