### ISSUE TITLE
[PL] [Spell] [Hunter] Camouflage

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#468]
http://www.wowhead.com/spell=51753/camouflage
http://cata.openwow.com/spell=51753

Następujące akcje przerywają efekt, a nie powinny:
- Rapid Fire (http://cata.openwow.com/spell=3045)
- Snake Trap (tylko w połączeniu z launcherem) (prawdopodobnie to to ID: http://cata.openwow.com/spell=82948)
- Jedzenie i picie
- Użycie trinketów zwiększających wybrany stat (np: http://cata.openwow.com/item=73648)
- Gdy efekt skończy się powinniśmy pozostać w efekcie "stealth" aż do podjęcia jakiejś akcji (ruch, walka itp.)
- Zmiana aspectów (lista: http://cata.openwow.com/search=aspect+of+the#spells:0-16+1)

Dodatkowo efekt powinien być przerwany przez:
- akcję /petattack natychmiastowo po wydaniu przez gracza takiego polecenia (pet wychodzi z ukrycia dopiero po zadaniu ciosu, a gracz zupełnie nie traci efektu)

Co do Rapid Fire i trinketów, to pozwole sobie o zamieszczenie filmiku z serwera blizza:
https://www.youtube.com/watch?v=d1Sp_JN-swA&feature=player_detailpage#t=324

Reszta opisana jest w komentarzach na wowhead.

**Comment by Wolffenstein** [comment]
"Gdy efekt skończy się powinniśmy pozostać w efekcie "stealth" aż do podjęcia jakiejś akcji (ruch, walka itp.)"
Nieprawda, właśnie sprawdziłem na globalu i stealth znika po upływie minuty. Wątpię, że było to zmieniane między 4.3.4 a WoDem, nic nie wskazuje na to by było inaczej.

**Comment by Wolffenstein** [comment]
Fixed in rev 4321.
