### ISSUE TITLE
[EN][Quest][Southern Barrens] Southern Barrens Quests order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4681]
[Running the Gauntlet](http://www.wowhead.com/quest=24862/running-the-gauntlet) should be available after completing quest [Hero's Call: Southern Barrens!](http://www.wowhead.com/quest=28550/heros-call-southern-barrens)(ID 28550) or [All's Clear](http://www.wowhead.com/quest=25852/alls-clear)

[Report to Aubrey](http://www.wowhead.com/quest=24921/report-to-aubrey) should be available after completing quest [Survey the Destruction](http://www.wowhead.com/quest=25191/survey-the-destruction) or [Hero's Call: Southern Barrens!](http://www.wowhead.com/quest=28551/heros-call-southern-barrens)(ID 28551) Note: quests  [Survey the Destruction](http://www.wowhead.com/quest=25191/survey-the-destruction) and [Hero's Call: Southern Barrens!](http://www.wowhead.com/quest=28551/heros-call-southern-barrens)(ID 28551) should be breadcumb to each other.

[The Taurajo Briefs](http://www.wowhead.com/quest=25059/the-taurajo-briefs) should be available after completing quests [A Line in the Dirt](http://www.wowhead.com/quest=25045/a-line-in-the-dirt) and [Fields of Blood](http://www.wowhead.com/quest=25043/fields-of-blood)

[...And Bury the Rest](http://www.wowhead.com/quest=25183/and-bury-the-rest) should be available after completing quest [Twinbraid Needs to Know](http://www.wowhead.com/quest=25174/twinbraid-needs-to-know) Note: Quest [Twinbraid Needs to Know](http://www.wowhead.com/quest=25174/twinbraid-needs-to-know) is missing because quest chain start with the bugged quest reported here: https://github.com/Atlantiss/BugTracker/issues/1274

[Make 'em Squeal](http://www.wowhead.com/quest=25015/make-em-squeal) and [A Failure to Communicate](http://www.wowhead.com/quest=25022/a-failure-to-communicate) should be available at level 29 and if you complete any of them the quest [Teegan's Troubles](http://www.wowhead.com/quest=25036/teegans-troubles) should no longer be available.

[Teegan's Troubles](http://www.wowhead.com/quest=25036/teegans-troubles) should be available at level 29 without any prerequisites quests.

[A Line in the Dirt](http://www.wowhead.com/quest=25045/a-line-in-the-dirt) should be available at level 30 without any prerequisites

[Fields of Blood](http://www.wowhead.com/quest=25043/fields-of-blood) should be available at level 30 without any prerequisites

[Lion's Pride](http://www.wowhead.com/quest=25041/lions-pride) should be available at level 30 without any prerequisites.

[Claim the Battlescar](http://www.wowhead.com/quest=25081/claim-the-battlescar) should be available at level 32 without any prerequisites.

[No Bull](http://www.wowhead.com/quest=25102/no-bull) should be available at level 32 without any prerequisites.

[Digsite Status](http://www.wowhead.com/quest=25104/digsite-status) should be available at level 32 without any prerequisites.

**Comment by Bildo** [comment]
fixed
