### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] A Blight Upon The Land

### ISSUE THREAD

**Issue by BurningMetal** [Atlantiss/BugTracker#4682]
I'm trying to finish this quest and sadly it wont let me attack the warden I've tried reloading the game,abandoning the quest and picking it up again also tried the placement of the npcs that are following me but nothing. Could I get some help or some insight on this 
![wowscrnshot_101615_104425](https://cloud.githubusercontent.com/assets/15161802/10548981/21d490c6-73f3-11e5-88a1-7db6e88c7d4b.jpg)

**Comment by Wolffenstein** [comment]
Already reported.

**Comment by BurningMetal** [comment]
Thank You
