### ISSUE TITLE
[EN][Quest][Bambala] See The Raptor

### ISSUE THREAD

**Issue by BurningMetal** [Atlantiss/BugTracker#4686]
While attempting to do this quest were I am suppose to see this raptor im not seeing anything and talking to the priestess,she doesn't give me any dialogue . I have abandoned the quest and picked up the quest again but nothing as you see 
![wowscrnshot_101715_070550](https://cloud.githubusercontent.com/assets/15161802/10559127/9767495a-749d-11e5-8872-0b4cee2315cc.jpg)
![wowscrnshot_101715_070559](https://cloud.githubusercontent.com/assets/15161802/10559128/97734804-749d-11e5-9d70-ce3214721418.jpg)
![wowscrnshot_101715_070605](https://cloud.githubusercontent.com/assets/15161802/10559129/978788b4-749d-11e5-9007-f68fa70c3db6.jpg)

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/500
