### ISSUE TITLE
Artruis the Heartless bug

### ISSUE THREAD

**Issue by darkomerc0806** [Atlantiss/BugTracker#4687]
http://www.wowhead.com/npc=28659/artruis-the-heartless hey there i posted this issue already and u did fix the part where oracle and frenzy attack me and the Artrius is killable... but after i kill Frenzy for example i should get friendly with Oracles and Hostile with Frenzy or something like that... but nothing happens

**Comment by xolon** [comment]
you need to complete fenzyheart chain and that chain will automatically change your rep from frenzyheart to oracle, after you do all normal quests in sholazar you can use Artruis to change rep to frenzyheart from oracles, and vice-versa
