### ISSUE TITLE
[EN][NPC][Drop] Tuten'kash

### ISSUE THREAD

**Issue by LibrarianEir** [Atlantiss/BugTracker#4689]
This ticket concerns the first boss of Razorfen Downs: Tuten'kash (http://cata.openwow.com/npc=7355)

Tuten'kash currently only drops [Swine Fists] (http://cata.openwow.com/item=10760) and [Plaguerot Sprig] (http://cata.openwow.com/item=10766). Neither of these items should be on his drop table, instead belonging to Plaguemaw the Rotting (http://cata.openwow.com/npc=7356)

Tuten'kash should instead be dropping [Carapace of Tuten'kash] (http://cata.openwow.com/item=10775), [Silky Spider Cape] (http://cata.openwow.com/item=10776) and [Arachnid Gloves] (http://cata.openwow.com/item=10777).

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6653-npc-drop-tutenkash-and-plaguemaw-the-rotting/

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6649-remove-loot-from-creature/
