### ISSUE TITLE
Dungeon Deserter

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#4691]
if you have http://www.wowhead.com/spell=71041/dungeon-deserter
you cant even que for RBG

**Comment by Aival94** [comment]
rev. 4629 Author: Jenova :: 2015-10-15 22:45 - Waiting for update
Core:

arena queues have been rewritten. Please test all 2v2, 3v3, 5v5 queues and report any found bugs.
players are now able to sign for both RDF and RBG at once.


AND: https://github.com/Atlantiss/BugTracker/issues/2561
