### ISSUE TITLE
[EN][Dungeon][Event] The Headless Horseman

### ISSUE THREAD

**Issue by Alastia** [Atlantiss/BugTracker#4693]
So, the boss event is doable but he's a bit bugged,for example boss level is 80, he should be 85 with 968625 hp and 8908 mana.
Fort the boss fight you just have to kill him and gg, instead he should work like this: phase 1 starts and you fight him from 100-60%, then he heals too 100% and you now fight his head. Phase 2 starts and you fight him 100-30%, then his head once more and he again heals back to 100%. Phase 3 starts and you fight him 100-0% (assuming you do it quick enough and don't let him heal back up) and that is his "total health" -but it varies depending on the outcome of your fight. The result you see here is the minimum amount of damage you have to deal to get him down.
-he doesnt have his sword equipped 
-the pumpkin you use to summon him shall burn and disappear after few sec from his appereance
-the quest "Call the Headless Horseman" (pumpkin quest) doesnt work, you cannot complete it from the "loosely turned soil" near
-he doesnt talk
-missing animation when he spawn from the loosely turned soil
-he does an incorrect flight path(really bigger than expected)
-The talk text to summon him should be only said by the guy who is summoning him

I'm gonna link here a video from retail cata(i assume) of the fight; https://www.youtube.com/watch?v=O9XJ4Vdcma4 

If you need i can upload a video of how it works here in atlantiss.

**Comment by eryczek1615** [comment]
bump
