### ISSUE TITLE
[PL][Event][Achievement] Tricks and Treats of Northrend

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#4694]
http://www.wowhead.com/achievement=5835/tricks-and-treats-of-northrend
nima dyni
http://www.wowhead.com/quest=12946/candy-bucket
http://www.wowhead.com/quest=12947/candy-bucket

**Comment by monibu** [comment]
poszukaj w wioskach ally, rok temu tam były

**Comment by Thefakemccoy** [comment]
grab the 2 horde buckets to get the achv they are flagged backwards.

**Comment by Bastion** [comment]
dobra alianckie zalicza ;d
