### ISSUE TITLE
[EN][Event][Hallow's End][Quests] Candy Buckets - Alliance

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#4695]
server rev as of writing this: 4627
http://www.wowhead.com/search?q=candy+bucket#quests

Missing candy buckets Northrend for Alliance
Grizzly Hills – Westfall Brigade
Grizzly Hills – Amberpine Lodge 

Missing candy buckets Kalimdor for Alliance
Darkshore - Lor'danel
Felwood – Talonbranch Glade 
Felwood – Whisperwind Grove 
Stonetalon Mountains – Farwatchers Glen
Stonetalon Mountains – Windshear Hold 
Southern Barrens – Northwatch Hold
Southern Barrens – Fort Triumph
Southern Barrens – Honor’s Stand
Tanaris - Bootlegger outpost
Un'goro Crater - Marshal's Stand 
Feralas - Dreamer's Rest
Desolace - Karnum's Glade

Missing candy buckets Cataclysm zones for Alliance
Deepholm - Temple of Earth 
Uldum - Ramkahen
Uldum - Oasis of Vir'sar
Mount Hyjal - Grove of Aessina
Mount Hyjal - Nordrassil 
Mount Hyjal - Shrine of Aviana 
Vashjir - most likely a death zone without the quests and/or seahorse, haven't checked but assume they're all missing as well - Darkbreak Cove, Deepmist Grotto, Silver Tide Hollow and Tranquil Wash
Twilight Highlands - Victor's Point
Twilight Highlands - Firebeard's Patrol
Twilight Highlands - Thundermar
Twilight Highlands - Highbank

Missing candy buckets Eastern Kingdoms for Alliance
Badlands - Dragon's Mouth 
Badlans - Fuselight
Blasted Lands - Surwich
Blasted Lands - Nethergarde Keep
The Hinterlands - Stormfeather Outpost
Loch Modan - Farstrider Lodge
Searing Gorge - Iron Summit
Northern Stranglethorn - Fort Livingston 
Swamp of Sorrows - Bogpaddle 
Swamp of Sorrows - Harborage
Western Plaguelands - Chillwind Camp
Wetlands - Greenwarden's Grove
Wetlands - Swiftgear Station

All the candy buckets in Outlands seem to be working for Alliance

for Alliance
Also the candy bucket at Thal'darah Overlook in Stonetalon Mountains does not give credit for the achievement
Neither does the candy bucket in Arathi Highlands at Refuge Point

The candy buckets for Teldrassil - Dolanaar and Feralas - Feathermoon Stronghold also appear twice on my achievement list. They can however be obtained so no big deal here

I have no clue what the state of the candy buckets are for the Horde side as I don't have a Horde toon to check it on

**Comment by Thefakemccoy** [comment]
Nice update but i know you have some listed that are horde only. The achv is labeled for both faction for some reason.

Example:
Swamp Of Sarrows

Alliance is The Harborage
Horde is : The Bogpaddle

Alliance achv
http://cata.openwow.com/achievement=966

**Comment by Thefakemccoy** [comment]
I am currently gathering them myself as i finish i will update my post and Confirm what OP has said.

Eastern Kingdoms: Confirmed
Kalimdor: TBA
Northrend; TBA
OUtlands: TBA
Cata Zones: TBA

**Comment by Thefakemccoy** [comment]
Kalimdor List:

Darkshore - Lor'danel
 http://www.wowhead.com/quest=28951/candy-bucket
Felwood – Talonbranch Glade 
http://www.wowhead.com/quest=28995/candy-bucket
Felwood – Whisperwind Grove 
http://www.wowhead.com/quest=28994/candy-bucket
Stonetalon Mountains – Farwatchers Glen
http://www.wowhead.com/quest=29013/candy-bucket
Stonetalon Mountains – Windshear Hold 
http://www.wowhead.com/quest=29011/candy-bucket
Southern Barrens – Northwatch Hold
http://www.wowhead.com/quest=29007/candy-bucket
Southern Barrens – Fort Triumph
http://www.wowhead.com/quest=29008/candy-bucket
Southern Barrens – Honor’s Stand
http://www.wowhead.com/quest=29006/candy-bucket
Tanaris - Bootlegger outpost
http://www.wowhead.com/quest=29014/candy-bucket
Un'goro Crater - Marshal's Stand 
http://www.wowhead.com/quest=29018/candy-bucket
Stonetalon Mountains - Northwatch Expedition Base
http://www.wowhead.com/quest=29010/candy-bucket
Feralas - Dreamer's Rest
http://www.wowhead.com/quest=28952/candy-bucket
Desolace - Karnum's Glade
http://www.wowhead.com/quest=28993/candy-bucket

**Comment by Thefakemccoy** [comment]
Eastern Kingdoms:

Badlands - Dragon's Mouth 
http://www.wowhead.com/quest=28956/candy-bucket
Badlans - Fuselight
http://www.wowhead.com/quest=28955/candy-bucket
Blasted Lands - Surwich
http://www.wowhead.com/quest=28961/candy-bucket
Blasted Lands - Nethergarde Keep
http://www.wowhead.com/quest=28960/candy-bucket
The Hinterlands - Stormfeather Outpost
http://www.wowhead.com/quest=28970/candy-bucket
Loch Modan - Farstrider Lodge
http://www.wowhead.com/quest=28963/candy-bucket
Searing Gorge - Iron Summit
http://www.wowhead.com/quest=28965/candy-bucket
Northern Stranglethorn - Fort Livingston 
http://www.wowhead.com/quest=28964/candy-bucket
Swamp of Sorrows - Bogpaddle 
http://www.wowhead.com/quest=28967/candy-bucket
Swamp of Sorrows - Harborage
http://www.wowhead.com/quest=28968/candy-bucket
Western Plaguelands - Chillwind Camp
http://www.wowhead.com/quest=28988/candy-bucket
Wetlands - Greenwarden's Grove
http://www.wowhead.com/quest=28991/candy-bucket
Wetlands - Swiftgear Station
http://www.wowhead.com/quest=28990/candy-bucket
