### ISSUE TITLE
[EN][TALENT][WARLOCK] Shadow embrace

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4698]
"Your Shadow Bolt and Haunt spells apply the Shadow Embrace effect, increasing all shadow periodic damage dealt to the target by you by X%, and reduces all periodic healing done to the target by Y%. Lasts for 12 sec. Stacks up to 3 times."

On our server the buff increases direct damage spells too, not just periodic.

**Comment by meowmewo** [comment]
Bump :P

**Comment by anxanas** [comment]
Bump

**Comment by meowmewo** [comment]
It should affect Dots + Drain soul only. 
At the moment it affects Dots + drain soul + Haunt + Shadow bolt.

**Comment by meowmewo** [comment]
Tears for Shadow and Death's Embrace fixes 
https://github.com/Atlantiss/BugTracker/issues/5916

**Comment by BialyADI** [comment]
Bump.

**Comment by BialyADI** [comment]
Jest tu kto ;<?

**Comment by meowmewo** [comment]
Kind of balances things out for Affliction, what we loose from the Doomguard not scaling with spellpower,crit, haste bug, we get from this bug ... sort of... :)

**Comment by Jenovas** [comment]
what we loose from the Doomguard not scaling with spellpower,crit, haste bug, we get from this bug ... sort of...

Actually Doomguard already crits for 70k (that is probably too much).

**Comment by meowmewo** [comment]
Not on affliction :) Probebly bugged mastery scaling for demo :)

**Comment by meowmewo** [comment]
By some fix Devs did, this is now fixed. Tested and confirmed. You can close.

**Comment by BialyADI** [comment]
They dont repair it.

**Comment by Zak1** [comment]
Confirmed, fixed.
