### ISSUE TITLE
[EN][Quest][The Hinterlands] The Battle for Andorhal

### ISSUE THREAD

**Issue by lanrutcon** [Atlantiss/BugTracker#470]
What is not working(Minor bug):
=============

The Flight Master Kellen Kuhn should give you a bat to Andorhal.

---------------
How should work:
=============

Reading the quest, you can clearly see that you need to speak with Kellen Kuhn to give you a trip to Andorhal.

----------------------
More info:
=============

**Note:** There are 3 quests with the same name (+3 for Alliance, so 6 in total). One gives you a [free trip on a winged beast](http://www.wowhead.com/quest=28508), another gives you [a portal to teleport](http://www.wowhead.com/quest=28750) you, and the last one [doesn't give you anything](http://www.wowhead.com/quest=26920).

[Screenshot](http://i.imgur.com/ZNjE2xu.jpg) - I'm on a bat but I had to pay for this one
[The Battle for Andorhal - WoWHead](http://www.wowhead.com/quest=28508)
[The Battle for Andorhal - WoWPedia](http://wowpedia.org/Quest:The_Battle_for_Andorhal_%28Horde%29)

**This was tested on 4.0.6a realm**

**Comment by Kiperr** [comment]
Fixed in rev 4422.
