### ISSUE TITLE
[EN][Event][Achievement]Tricks and Treats of Kalimdor - Southern Barrens, Desolation Hold

### ISSUE THREAD

**Issue by biaicc98** [Atlantiss/BugTracker#4704]
Alright, so the issue here is not that the candy bucket (http://www.wowhead.com/quest=29005/candy-bucket) doesn't work. In fact it does work very well: you deliver the quest, you get the Handful of Treats.

The problem here is that after using it, it did not count for the achievement.

I don't really know how I can prove this, but yeah, I hope it gets fixed. Thanks in advance!

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/4695
