### ISSUE TITLE
[EN][Event][Hallow's End][Quests] Candy Buckets - Alliance

### ISSUE THREAD

**Issue by klm670** [Atlantiss/BugTracker#4710]
These are the Alliance Azeroth buckets for the achievement that are bugged. Rest is available on the Horde Report.
[EN][Event][Hallow's End][Quests] Candy Buckets - Horde #4703
http://i.imgur.com/zs7NKkj.jpg
![ally buckets 2](https://cloud.githubusercontent.com/assets/12796403/10567115/9d8a21d2-75fa-11e5-886f-14354809ecc0.jpg)
![ally buckets](https://cloud.githubusercontent.com/assets/12796403/10567116/9d8b8964-75fa-11e5-85c9-71cf05ea6682.jpg)
http://i.imgur.com/bfRWNOz.jpg

Arathi Highlands, Refuge Point and Darkshore, Lor'danel are available but don't give credit.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/4695

**Comment by SwimzwithSharkz** [comment]
Also, In Northrend, Amberpine Lodge Candy Bucket is there, but no quest "?" on it, so unusable.
