### ISSUE TITLE
[PL][Spell][Rogue]Mastery :potent poisons 

### ISSUE THREAD

**Issue by heekael** [Atlantiss/BugTracker#4712]
Mianowicie niewiem czy to tylko u mnie czy w rasie undead ale nie dziala Mastery niema dodatkowego dmg wcześniej 20k dps od jakiegoś czasu 11k np w rasie troll działa ok. Mam 20.61 Mastery a różnicy niema jak zreforgowalem do minimum mastery przy 20,61% dmg powinien wynosic coś około 72% dodatkowego dmg z Mastery a wynosi 0

**Comment by Jenovas** [comment]
Probowales zresetowac talenty? Zmienic build?

**Comment by heekael** [comment]
Resetowalem talenty zmieniałem reforg ale nic to nie dało ogólnie zaczęło się dziać od tego tygodnia po którymś dc
