### ISSUE TITLE
[EN][Proffesion][Fishing] Rev. 4630 Dalaran fishing fix

### ISSUE THREAD

**Issue by agardosh** [Atlantiss/BugTracker#4714]
still doesn't seem to work, didn't see anyone reporting it anywhere, so just bringing that up

**Comment by Aival94** [comment]
"rev. 4631 Author: Jenova :: 2015-10-19 23:33 - Waiting for update"

When you see in an update in changelog say waitting for update it means that these changes/fixes has not been yet implemented.(never check it while is offline as it will show all changelog with waiting for update status)

**Comment by agardosh** [comment]
Was writing this because all of the updates were "Waiting for update" for a few days now, just realized the online status on the site was bugged..
Sorry!

**Comment by Bildo** [comment]
You can easily check revision in-game by typing .s in
