### ISSUE TITLE
[EN][Quest][Dun Morogh] Ammo for Rumbleshot(ID 5541)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4715]
Quest has been removed at patch 4.0.3

Wowhead Link: [Ammo for Rumbleshot](http://www.wowhead.com/quest=5541/ammo-for-rumbleshot)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6648-remove-old-quest/
