### ISSUE TITLE
[EN][Quest][Fishing Daily] Bag of shinny things

### ISSUE THREAD

**Issue by Docholiday-Atlantiss** [Atlantiss/BugTracker#4717]
2 of the past 3 days i have done the fishing daily 2 in Stormwind and 1 in Ironforge the Bag of shinny things have turned up empty. When i opened it it said it was empty.

http://www.wowhead.com/item=67414/bag-of-shiny-things

**Comment by Thefakemccoy** [comment]
These are the 2 quest i did and got empty bags
Ironforge
http://www.wowhead.com/quest=29342/cold-water-fishing

Stormwind
http://www.wowhead.com/quest=26488/big-gulp

Not sure if the bags are related to the quests but i figured I would link the ones the quests that gave me empty bags.

**Comment by Docholiday-Atlantiss** [comment]
#8056
