### ISSUE TITLE
Warlock's minion's name bug

### ISSUE THREAD

**Issue by ashphoenix92** [Atlantiss/BugTracker#4719]
Every time after a resummon or a summoning new minion, it's name changes anew. As far as known, warlock's demon-minions' name can be changed only via Demon Trainers NPCs for a cost, not by itself because of a re-summon or a summoning.

Source - http://wow.gamepedia.com/Warlock_minion#Patch_changes
(look "Notes" section)

**Comment by Bildo** [comment]
bugtracker rules
