### ISSUE TITLE
[EN][Quest][Dun Morogh] Frost Ram Exchange(ID 7673)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4723]
This Quest has been removed during Cata at least(seems to be forgotten till the end of Woltk and not be removed)

Wowhead Link: [Frost Ram Exchange](http://www.wowhead.com/quest=7673/frost-ram-exchange)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6647-quest-removed/
