### ISSUE TITLE
[EN][Quest][Dun Morogh] Black Ram Exchange(ID 7674)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4724]
This Quest has been removed during Cata at least(seems to be forgotten till the end of Woltk and not be removed)

Wowhead Link: [Black Ram Exchange](http://www.wowhead.com/quest=7674/black-ram-exchange)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6647-quest-removed/
