### ISSUE TITLE
[EN][Quest][Ironforge] A Little Slime Goes a Long Way(ID 4513)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4725]
Quest should be available after completing quest [A Little Slime Goes a Long Way](http://www.wowhead.com/quest=4512/a-little-slime-goes-a-long-way) (ID 4512)

Wowhead Link: [A Little Slime Goes a Long Way](http://www.wowhead.com/quest=4513/a-little-slime-goes-a-long-way)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6646-previous-quest-fix/
