### ISSUE TITLE
[EN][Reputation] Every faction reputation grows simultaneously

### ISSUE THREAD

**Issue by ashphoenix92** [Atlantiss/BugTracker#4727]
Noticed, that every faction reputation grows simultaneously no matter what is written in dialog\chat box. Example "Reputation with Undercity increased by 250"  - in fact all of the faction's rep's get an increase of the same ammount.

**Comment by Wolffenstein** [comment]
?

**Comment by iliarakov** [comment]
no some time giving  350  500
