### ISSUE TITLE
[en][dungeon finder] logout/dc in dungeon

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4728]
if you get dced or logout in rdf and then you log back in: 

SOMETIMES you get teleported out of dungeon and it looks like you were kicked, even tho other party members can still see you in party, and you can't teleport back in dungeon or anything, practicly is like a kick.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/2439
