### ISSUE TITLE
[En][Quest-Classic][Blasted Lands] Futile Pride

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#4730]
After Turning in Warchief's Command: Blasted Lands! (http://www.wowhead.com/quest=28671), there is no follow up quest. The next quest that you get should be Futile pride (http://www.wowhead.com/quest=25674) from Okrilla (http://www.wowhead.com/npc=41124) to start the chain :).

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6645-next-quest-fix/
