### ISSUE TITLE
[EN][Quest][Un'Goro Crater] Super Sticky

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#4733]
There are only 2 NPC's [Tar Lord]  that drop the quest Item out of the 50 - 60 in the area.

Hence making this quest take forever to complete ..waiting for respawn of the same two mobs. takes almost an hour and half

`Wowhead quest Link:` [Super Sticky](http://www.wowhead.com/quest=4504/super-sticky)                                                            

`NPC's that should drop the quest item`:
- [Tar Lord](http://www.wowhead.com/npc=6519/tar-lord)
- [Tar Beast](http://www.wowhead.com/npc=6517/tar-beast)
- [Tar Creeper](http://www.wowhead.com/npc=6527/tar-creeper)
- [Tar Lurker](http://www.wowhead.com/npc=6518/tar-lurker)

`Quest Item :` [SuperSticky Tar](http://www.wowhead.com/item=11834/super-sticky-tar)

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11615-4733item-super-sticky-tar/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
