### ISSUE TITLE
[En][Quest-Event][Hollow's End][Rotten Hallow Daily Quests][Stormwind]

### ISSUE THREAD

**Issue by mean931** [Atlantiss/BugTracker#4735]
There should be 3 npcs giving the daily quests outside Stormwind, near a burning Wickerman, The npcs in question are: 1) Celestine of the Harvest (http://www.wowhead.com/npc=51665/celestine-of-the-harvest); 2)Gretchen Fenlow (http://www.wowhead.com/npc=51934/gretchen-fenlow); 3)Keira (http://www.wowhead.com/npc=52064/keira). Without them the Achievement [Rotten Hallow] is not doable, and the Hallow's End vendors are also missing (http://www.wowhead.com/npc=53728/dorothy) (http://www.wowhead.com/npc=53702/stymie) (http://www.wowhead.com/npc=52497/spanky)

**Comment by Thefakemccoy** [comment]
They are re written the hallows end quest
