### ISSUE TITLE
[EN][Quest][NPC] Rise, Forsaken

### ISSUE THREAD

**Issue by ashphoenix92** [Atlantiss/BugTracker#4737]
Small glitch\bug with NPC Agatha in quest "Rise,Forsaken"

She travels with you half-buried under textures. 
![wowscrnshot_102315_141528](https://cloud.githubusercontent.com/assets/15208895/10691356/075b1bea-7991-11e5-9226-a66e00309fd4.jpg)

Link - http://www.wowhead.com/quest=27097/rise-forsaken

Quest "No escape"(quest chain afrer "Rise, Forsaken") small glitch - after completion Agatha caries character back with a speed of standard walking, which takes pretty descent 10 minutes.

http://www.wowhead.com/quest=27099/no-escape

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4203

**Comment by Angelo-DM-** [comment]
https://github.com/Atlantiss/BugTracker/issues/1678 (#1678)
