### ISSUE TITLE
Protection Warrior "Devastate" Spell Bug!

### ISSUE THREAD

**Issue by vladic24** [Atlantiss/BugTracker#4739]
Protection Warrior Skill "Devastate" doesn't work properly...devastate should deal damage equal to 109% of weapon damage plus "X" damage for each application of Sunder Armor ...it doesn't increase damage for each application of sunder armor the damage is the same ...i have tested it on player targets, dungeon boss and even on creeps that don't have armor but still no damage increase from sunder armor application ...the 109% of weapon damage increases only by a very small amount because of the sunder armor that reduces targets armor but does not increase the damage for each application ...sunder armor works fine that is for sure but the X damage for each application doesn't...It isn't normal to deal 3000 damage with "Devastate" at level 85 EVEN  FOR  A TANK!

**Comment by Thefakemccoy** [comment]
Links and Title

https://github.com/Atlantiss/BugTracker

**Comment by vladic24** [comment]
how can i link the spell if there are 30 types of devastate and none of them is the same as the one i have?...

**Comment by vladic24** [comment]
Ok i found the spell  http://cata.openwow.com/spell=20243
