### ISSUE TITLE
[EN][Gameobject] Invincible's grave

### ISSUE THREAD

**Issue by djsup** [Atlantiss/BugTracker#4740]
I found out that Invincible's grave text is replaced with "Item 1 out of 1".
![bug](https://cloud.githubusercontent.com/assets/15264360/10693714/3073ac96-799a-11e5-9cc2-410e3fce265c.png)

**Comment by Thefakemccoy** [comment]
http://www.wowhead.com/object=192835/invincible

Should say 

INVINCIBLE

Beloved steed of Prince Arthas Menethil

Loyal and great of heart in life, may you find peace in death.

Pure streams and green pastures, devoted friend.

**Comment by djsup** [comment]
Thanks for adding info Thefakemccoy.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6644-wrong-gameobject-text/
