### ISSUE TITLE
[en][druid]stampede vs. dash

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4741]
## What's wrong:
Dash is stacking with Stampeding Roar

## How it should be:
Dash shouldn't stack with Stampeding Roar , if you have one ability active you shouldn't be able to use the other one.

also if you have stampeding roar you shouldn't be able to use Dash

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/3659
