### ISSUE TITLE
[EN][Object] Fishing pools spawning in shallow water

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#4743]
I don't know all spawn points for fishing pools that are in shallow water, but there are at least 7 pools, which spawn in such waters around Twilight Highlands. It can get quite frustrating, because the more you fish from pools, the more pools actually spawn in shallow water and you can't do anything about it.

**Comment by Achiver** [comment]
Also I found:
~10 fishing pools floating in air below the ground west of Nijel's Point in Desolace
1-3 pools floating above the water in Nordrassil , Mount Hyjal

**Comment by therealpadthai** [comment]
+1 on the fishing pools in TH. It's almost impossible right now to actually fish any highland guppy's, as all the pools are in shallow water where you can't start a cast. 

Any chance at fixing? It's been close to a year :(

**Comment by namreeb** [comment]
Confirmed

**Comment by therealpadthai** [comment]
This is still bugged. Any chance at a fix again? I thought it was fixed a while back, guess it still is buggy.

**Comment by tomatosz** [comment]
@namreeb do you have any source for that? I want to see if I can fix it and the easiest solution would be to just delete the 'shallow' pools, but if they are in the correct places then it would be harder to fix.

**Comment by namreeb** [comment]
My only evidence was the fact that they are listed on wowhead as spawning in the shallow rivers of Twilight Highlands, as seen here: http://www.wowhead.com/object=202777/highland-guppy-school

I think that most emulation servers do not consider water which is shallow enough to walk in as being water as it makes pathfinding easier.  I suspect that is the problem.  So when the server considers these positions as potential spawn points for the bobber, it sees water depth as zero, and therefore not suitable.

**Comment by tomatosz** [comment]
Fixed in rev. 5824

Deleted several, there are still others in the 'shallow' water that did work
