### ISSUE TITLE
[PL][NPC][Achidment] Scarlet Comander Mograine

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#4744]
Nie zalicza mi achidmentu Scarlet Monastery przez to że mi nie zalicza zabicia 
npc Scarlet Comander Mograine.
Czasami npc po zabiciu będzie łaził za zabujcą do końca insty kiedy wyjde i wejde to npc sie cofa do poprzedniej pozycji i sie odradza.
http://www.wowhead.com/npc=3976/scarlet-commander-mograine

**Comment by Bastion** [comment]
co sie robi?! XD

**Comment by arekczup** [comment]
dobra musi ten high inguisitor white name go resnąć jak szybko si zabije 2 bosy to ngo nie zabije w tym jest problem
