### ISSUE TITLE
[EN] [Event] [Hallow'sEnd] [Alliance] Candy Buckets and Mask Vendor (4634 update)

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#4745]
Eastern Kingdoms (after update (Complete list of not working))

Badlands Dragons Mouth (there but wont complete)
http://www.wowhead.com/quest=28956/candy-bucket

Loch Modan, Farstrider Lodge(Not there)
http://www.wowhead.com/quest=28963/candy-bucket

Wetlands, Swiftgear Station(not there)
http://www.wowhead.com/quest=28990/candy-bucket

Arathi Highlands, Refuge Point(Is back but cant complete)
http://www.wowhead.com/quest=28954/candy-bucket

**Comment by Thefakemccoy** [comment]
Kalimdor

**Comment by Thefakemccoy** [comment]
Cata Zones (WiP)

**Comment by Thefakemccoy** [comment]
A side note if any one reads this i did not check Outlands cause it was doable.

I am in the process of checking Grizzly Hills (will update)

**Comment by Thefakemccoy** [comment]
Masks Missing from Vendor
http://www.wowhead.com/item=49216/worgen-male-mask
http://www.wowhead.com/item=49215/worgen-female-mask

**Comment by SwimzwithSharkz** [comment]
I second the non interaction with the Blasted Lands Candy Bucket. 
The "?" is there, but I cannot click on it to complete. TY.
Here is a screenshot.
http://i.imgur.com/623hdGw.jpg

**Comment by Luna-maria** [comment]
Northrend candy buckets in Grizzly hills are working fine now

**Comment by Thefakemccoy** [comment]
@Luna-maria; Thanks i was unable to check it. Thanks for confirming they work.

**Comment by Bildo** [comment]
I fixed all buckets and worgen mask in addiction i scripted this :D https://www.youtube.com/watch?v=-G0mCL3NNQE for horde and alliance

**Comment by Luna-maria** [comment]
sweet, which update is it gonna be in? :3

**Comment by Thefakemccoy** [comment]
@Bildo Sweet thanks figured i would try to keep most of it contained to 1 post instead of multiple ones then i just decided to add the mask cause thats all i read in chat.

**Comment by SwimzwithSharkz** [comment]
TY Yall, & which addiction didcha use Bildo? coffee?
lulz & http://i.imgur.com/Gg9uPVW.jpg

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev4636

**Comment by Xaedric** [comment]
@Bildo The ones i list below have some problems. The bucket is actually there but no '?' above them. Possibly broke after update? (REV. 4637)

Kalimdor
Desolace - Karnum's Glade
http://www.wowhead.com/quest=28993/candy-bucket

Felwood – Whisperwind Grove 
http://www.wowhead.com/quest=28994/candy-bucket

Tanaris - Bootlegger Outpost
http://www.wowhead.com/quest=29014/candy-bucket

Un'Goro Crater - Marshal's Stand 
http://www.wowhead.com/quest=29018/candy-bucket

**Comment by Thefakemccoy** [comment]
@Xaedric  Im starting a new list as i go after hearing some are broke again but Bildo has a hotfix not sure if thats why.
