### ISSUE TITLE
[EN] [Event] [Hallow'sEnd] [Alliance] Under City

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#4746]
In under city the alliance can pick up 2 of the horde quests.
Stink Bombs Away
http://www.wowhead.com/quest=29374/stink-bombs-away
and
Clean up the Under City
http://www.wowhead.com/quest=29375/clean-up-in-undercity

We can also access the vendors they are flagged as friendly along with the rest of the horde npcs there for hallows end.

I assume its the same way for the Horde in Stormwind

**Comment by BAndysc** [comment]
Stink Bombs Away scripted

**Comment by Thefakemccoy** [comment]
I guess since it wasnt really scripted it wasnt flagged for a faction.

**Comment by BAndysc** [comment]
Scripted 10 minutes ago ;-)

**Comment by Thefakemccoy** [comment]
Either im lost or my report wasnt clear i guess. Thanks for taking the time to script it though.

My org report was not for it not working but as a Alliance char i could go to under city and pick up the horde quest for it.

Was that because it wasnt scripted? 

Not tyring to be a pain in the butt. Just want to make sure my report was understood.

**Comment by BAndysc** [comment]
Damn, it is too late, I assumed it is bugged quest report and automatically, once I opened the issue I have added the comment. Sorry for my mistake

**Comment by Thefakemccoy** [comment]
I understand guess thats a plus on me for being US its still early here. Bildo scripted a event outside wasnt sure if this was it might want to get with him on that. If not you are one step ahead.

**Comment by Thefakemccoy** [comment]
I just wanted to make sure when it was time to fix you guys knew the quest was missing its faction only flag. 
Sorry not sure how WoW works as far as programming so i made it so you guys knew.

**Comment by Bildo** [comment]
i think i fixed faction for some buckets and quest, i don't really remember because this event is sooo huge xd

**Comment by Thefakemccoy** [comment]
I sent u the bucket thing for the reason stated in the message and i reported this cause it hadnt been fixed yet for the same reason stated in that message.

Also can one of you plz look at my forum bug post i really would like to get back on the forums. :)
Im on TS if you guys know how to fix it.

**Comment by Bildo** [comment]
give me your forum name

**Comment by Thefakemccoy** [comment]
therealmccoy

**Comment by Bildo** [comment]
done

**Comment by Thefakemccoy** [comment]
Thank you are my hero

**Comment by Bildo** [comment]
Not me, Bastek

**Comment by Thefakemccoy** [comment]
I owe him a beer.

**Comment by Thefakemccoy** [comment]
Stink bombs away you fly to fast in undercity for alliance to do anything.

**Comment by Thefakemccoy** [comment]
I recant my last statement may have been a bug if you guys saw it

**Comment by Thefakemccoy** [comment]
I just checked undercity as alliance and the quest are gone.
Closing
