### ISSUE TITLE
[PL][Event][Hallow'sEnd][Candy Buckets][Horde] Bugged objects in Eastern Kingdoms

### ISSUE THREAD

**Issue by Sevyarneya** [Atlantiss/BugTracker#4748]
Lista niedzialających koszyków w Eastern Kingdoms
1. Blasted Lands, Dreadmaul Hold;
2. Badlands, New Kargath;
3. The Cape of Stranglethorn, Hardwrench Hideway;
4. Hillsbard Foothills, Eastpoint Tower;
5. The Hinterlands, Hiri'watha Research Station;
6. Silverpine Forest, Forsaken Rear Guard;
7. Tirisfal Glades, The Bulwark;
8. Western Plaguelands, Andorhal
Koszyków z lokacji Cataclysm nie sprawdzałem jeszcze w całości. Jak będę mieć wynik, to napisze o tym.

**Comment by Faaith** [comment]
Co do Cata koszyki są w Hyjal i TH. W Deepholm nie ma, Vashj'ir nie sprawdzałem, to raczej robota dla druida ;p

**Comment by Sevyarneya** [comment]
jak masz miotle to skaczesz nad wode i latasz gora, wiec vashjir nie tylko dla druida

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev4636
