### ISSUE TITLE
[EN][Spell][Racial] Shadowmeld

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#475]
Shadowmeld is currently bugged in few ways.
<s>1.Shadowmeld shouldn't drop combat during PVE raids, rdfs as it does right now. I am not certain what should be overall correct conditions, but you shouldn't be able to drop combat during boss encounter in raid or rdf. </s> Fixed in http://atlantiss.eu/changelog/1#rev4932
2.Starting any cast should remove shadowmeld buff from the player but it doesn't on PTR. Just imagine how it can be abused so easly in arenas with Revive.
3.You should be able to cast spells that require Stealth or Prowl, but you're not able to do it on PTR. For example Cheap shot, pounce, garrote. Blizzard made this racial kinda useful in pve for rogues and feral druids. Since it shouldn't be possible to shadowmeld into stealth/Prowl in PVE.
http://forums.elitistjerks.com/topic/121101-42-changes-discussion/page-16 // Shadowmeld Ambush
http://youtu.be/sQj3_jnjCdg?t=42s // You can see Premeditation becomes usable on the right side of his screen.

http://cata.openwow.com/spell=58984 // Shadowmeld

**Comment by debtheone** [comment]
Meld is broken sometimes it does not break the cast even when used at 50% cast bar. Its impossible here to meld such things as aoe fears scatters shots aimed shot etc its kinda odd cause ure able to meld coil. Also meld sometimes does not cancel when ure casting something so the enemy cast see the cast bar ,ex. casting ress from meld

**Comment by kadi2** [comment]
1. Fixed in http://atlantiss.eu/changelog/1#rev4932

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
its bugged on almost every pserver come on Zori u can do this :^)

**Comment by debtheone** [comment]
please fix its best racial in this game

**Comment by debtheone** [comment]
Bump

**Comment by lamaATS** [comment]
Fixed in rev. 5486
