### ISSUE TITLE
[EN] [Event] [Hallow'sEnd] [Quest] [Alliance] 

### ISSUE THREAD

**Issue by mean931** [Atlantiss/BugTracker#4752]
The quests [A time to lose](http://www.wowhead.com/quest=29371/a-time-to-lose) not working at all;
The quest [Clean up Stormwind] (http://www.wowhead.com/quest=29144/clean-up-in-stormwind) also not working;
The quest [Stink Bombs Away](http://www.wowhead.com/quest=29054/stink-bombs-away) also not working, the npc does not give you the option to start the voyage with the broom;

**Comment by Thefakemccoy** [comment]
These quest was not finished and will be added in part 2

**Comment by Bildo** [comment]
in part 3 i think :D

**Comment by BAndysc** [comment]
Stink Bombs Away fixed

**Comment by iliarakov** [comment]
y

**Comment by iliarakov** [comment]
we waiting for  A Time to Lose quet

**Comment by BAndysc** [comment]
Clean up in Stormwind fixed in 4641

**Comment by iliarakov** [comment]
nice work

**Comment by klm670** [comment]
A time to lose quest is still bugged.

**Comment by BAndysc** [comment]
Fixed ^.^ (rev 4645)

**Comment by SwimzwithSharkz** [comment]
Knock Knock,
Plz Help, thiz Quest still will not work for me. 
Before it would just zoom around and around UC, with the 
Stink Bombz not targeting anything. Now, the same but
when I choose the Option to Return to SW, I die EVERY
SNGLE TIME, by falling to my death in Elwynn Forest.
TY

**Comment by BAndysc** [comment]
You can bomb anything with stink bombs. What level are you?

**Comment by Thefakemccoy** [comment]
Log out and back in swim
