### ISSUE TITLE
[EN] [Dungeon] Vortex Pinnacle & Blackrock Caverns combat bug

### ISSUE THREAD

**Issue by vanael** [Atlantiss/BugTracker#4759]
![wowscrnshot_102515_091706](https://cloud.githubusercontent.com/assets/5870498/10714675/04526bf0-7afa-11e5-8cc7-61a90ec28397.jpg)

As can be seen this kind of object causes combat bug.
![wowscrnshot_102515_115433](https://cloud.githubusercontent.com/assets/5870498/10715258/f06f58d0-7b0f-11e5-8f5f-0fa24a0beb9f.jpg)
![wowscrnshot_102515_115437](https://cloud.githubusercontent.com/assets/5870498/10715259/f072d104-7b0f-11e5-8ee7-9e2d45f4bd93.jpg)
![wowscrnshot_102515_115440](https://cloud.githubusercontent.com/assets/5870498/10715260/f08aa0c2-7b0f-11e5-96d6-af1e00ae5991.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/4722
