### ISSUE TITLE
[PL][Event][Hallow's End] Chain na Creepy Crate

### ISSUE THREAD

**Issue by Drutmaster** [Atlantiss/BugTracker#4760]
Witam!

Wiele poprawek zostało wprowadzonych w celu naprawienia eventu. Nie wiem jednak czy został zgłoszony brak chaina na wyżej wymienionego companiona (Creepy Crate - http://www.wowhead.com/item=71076/creepy-crate). Powinien mieć on swój początek w Orgrimmarze (w przypadku Hordy - http://www.wowhead.com/quest=29415/missing-heirlooms) lub w Stormwind (w przypadku Alliance - http://www.wowhead.com/quest=29392/missing-heirlooms). Wiem, że Bildo i wiele innych osób stara się przywrócić event na jego właściwe tory i chwała im za to. Liczę, że znajdą chwilę czasu na przyjrzenie się temu. Zrozumiem jednak, jeżeli brak czasu lub chęci uniemożliwią oskryptowanie tego w tym roku. ;)  

Życzę miłego dnia!
Rev. 4637

**Comment by Bildo** [comment]
postaram sie zrobic

**Comment by Drutmaster** [comment]
Ok, dzięki wielkie Bildo

**Comment by Bildo** [comment]
fixed
