### ISSUE TITLE
[EN] [Event] [Hallow'sEnd] [Alliance] Candy Buckets (4637 Update)

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#4764]
@ Bildo if the hotfix is for the buckets feel free to close this. For i am going around on a 2nd toon and doing all them some people are saying they are unable to complete them.

* **I have completed Kalimdor and was only unable the complete the 4 listed the rest worked fine. These pumpkins are there but dont offer a quest.**

* **After looking at the list and comparing the Alli and Horde list these look like it might be a faction issue when they should be neutral or labeled for both**

**Kalimdor:** This does include **Hyjal** and **Uldum**

Felwood - Whisperwind Grove (Possible faction flag issue should be neutral or no faction flag)
http://www.wowhead.com/quest=28994/candy-bucket

Desolace, Karnum's Glade (Possible faction flag issue should be neutral or no faction flag)
http://www.wowhead.com/quest=28993/candy-bucket

Un'Goro Crater, Marshal's Stand (Possible faction flag issue should be neutral or no faction flag)
http://www.wowhead.com/quest=29018/candy-bucket

Tanaris, Bootlegger Outpost (Possible faction flag issue should be neutral or no faction flag)
http://www.wowhead.com/quest=29014/candy-bucket

**Comment by Thefakemccoy** [comment]
Eastern Kingdoms (If any)

**Comment by iliarakov** [comment]
yes you cant return  quest and cant get  this  bucket me need  me  for  this achivement  Tricks and Treats of Kalimdor

**Comment by Thefakemccoy** [comment]
I am working on the new list for Bildo. They where fixed but something went wrong he has a hotfix posted im not sure if that fixes this issue.

**Comment by iliarakov** [comment]
nice

**Comment by iliarakov** [comment]
ok  i find other dont working candy bucket they i , (Tanaris Bootlegger Outpost),(Un Goro Crater Marshal stand) and (desolace karnum's glade)

**Comment by Thefakemccoy** [comment]
Yes it seems to be a faction based issue. Alot of buckets are to be faction flagged so you cant do both horde and alliance. It seems the update marked them for horde only possible. If that is the case they should be flagged for both or neutral however the coding works.

**Comment by Bildo** [comment]
fixed, relog

**Comment by iliarakov** [comment]
nice
