### ISSUE TITLE
[EN][Quest][Feralas] The Darkmist Legacy

### ISSUE THREAD

**Issue by Dexobox** [Atlantiss/BugTracker#4766]
This quest is not working as the lootable Items to be collected is missing, Hence making the quest incomplete.

Quest Link : [The Darkmist Legacy](http://www.wowhead.com/item=53135/glowing-soil)
Item : [Glowing Soil](http://www.wowhead.com/item=53135)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6643-quest-gameobject-unlootable/
