### ISSUE TITLE
[en][priest] divine aegis vs. PoH crit

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4771]
## How it should be:
If you crit with PoH it should give you an 60% shield instead of 30%

## Proof:
appearently Divine aegis has a hidden tooltip, It hides a duplicated aegis and double affected by mastery in case of a critical heal from Prayer of Healing,in the tooltip there is written "Critical heals and all heals from PoH" ; except that when you had a critical PoH, Divine Aegis considered that you had an aegis from PoH + an aegis from the crit, so a double aegis instead of a simple aegis (30%). Basically you had an aegis of about 60% and not an aegis of 30% on Blizz servers. Currently, PoH crit puts a simple aegis,the 30% we have here.

the proof is in french idk if you have any french dev, however easy with google translate

http://eu.battle.net/wow/fr/forum/topic/3295160262
"Le point important, et peut être le seul vraiment intéressant/discriminant de ce guide est la mise en avant d’un « bug » de la prière de soins. En effet, le talent [Divine Aegis] nous dit : « les soins critiques et tous les soins de prière de soins créent un bouclier blablabla ». Ce tooltip peu clair cache une égide doublée et doublement affectée par la maitrise dans le cas d'un critique sur PoH. Ce point est développé ci-après dans la section « Quels sorts utiliser ». "

**Comment by Beatit** [comment]
bump :)

**Comment by Jenovas** [comment]
Shouldbe fixed in rev rev. 5003
