### ISSUE TITLE
[EN] Maloriak Aberrations bugged (HC)

### ISSUE THREAD

**Issue by shandrios** [Atlantiss/BugTracker#4773]
My guild encountered an issue with Maloriak's aberrations during our heroic difficulty attempts. After some time (it seemed to happen when he released the third wave of adds), the aberrations stopped being affected by slows. We tried both our Death Knight's Chillblains talent and Hunter's Freezing trap. They just completely ignored the slows and proceeded to kill our kiter.  Obviously the adds should not be immune to slows, and as this bug makes the encounter alot harder, i hope it can be fixed soon.

**Comment by Kejmil** [comment]
After recent fix to howling blast damage if there are 5+ adds in close proximity using howling blast on them is doing absolutely nothing - no direct dmg, no applied diseases via glyph, no slow coz no disease.
Other slows, unmoves, ccs are working fine

**Comment by Jenovas** [comment]
5+ adds with buff that reduces DMG taken? Without the buff it works ok?

**Comment by Kejmil** [comment]
as long there is no more than 5 buffs on add it still hits and apply slow, maybe dmg reduction is now addictive for howling blast while it should be multiplicative (20+20+20+20+20 dmg reduction while it should be 0.8^5 dmg taken)

**Comment by Jenovas** [comment]
Fixed in rev 4651
