### ISSUE TITLE
[EN][GuildAchieve] Conclave of the Wind

### ISSUE THREAD

**Issue by Sayris987** [Atlantiss/BugTracker#4774]
Earlier today in changelog i saw that guild achievements for dungeons are working so our guild went into Bastion of Twilight and yes we got the guild achievement. Right after that we went for Throne of the Four Winds and we didn't get the guild achievement. When i checked the achieve we got credit for killing Al'akir but not for Conclave of the Wind. That was 30 min before i post this.

**Comment by xolon** [comment]
I think that all of you ( or 8/10) need to be on nezir platform and kill him last

**Comment by Sayris987** [comment]
we all were there 10/10 guldies 10/10 alive

**Comment by Aival94** [comment]
I have encountered this bug as well.Next time we will try have at least one ppl in each platform to see if work like this.

**Comment by Sayris987** [comment]
That might work we will try it aswell

**Comment by Aival94** [comment]
Is not working.we were full Guild group and we had 1 on rohash,1 on anshal and rest killed nezir but no Guild ach.

Please Wolffenstein try fix it like the others.Ty for fixings rest :)

**Comment by Sayris987** [comment]
Thanks for the info man. I guess no Dark Phoenix yet :(

**Comment by Aival94** [comment]
It seems is a bug about encounter with many bosses supposed to be the encounter boss as Omotron Defence System is not working as well.

**Comment by Sayris987** [comment]
ODS Worked fine for us all we need is conclave we already have BoT and BWD.

**Comment by Aviannaqt** [comment]
Fixed.
