### ISSUE TITLE
[en][priest] shadowfiend

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4777]
## What's wrong:
* Shadowfiend is bad scaled with attack speed, on our server shadowfiend does 7 attacks in 15 seconds
* Shadowfiend does less damage than it should, on our server it does 4,3k dmg at 7,1k SP.

## How it should be:
* In 15 seconds it should do at least 10 attacks,11 hits at most if its spawned right into our target and it's not peeled.
* Should do ~5.3k dmg at 7.1K SP
* Should inherit your crit/hit (not sure about this i it works on our srv coudln't test it)

## Proof:
http://wowpedia.org/Shadowfiend
"The Shadowfiend has a base attack speed of 1.5" 
http://web.archive.org/web/20120815094737/http://www.wowpedia.org/Shadowfiend
"The Shadowfiend grants up to 11 hits per use, although this number is usually 10. Its attack speed is 1.5 and it has a 15 second duration. It is rare but possible for it to get one final attack as it expires if it spawned adjacent to your target." 

https://www.youtube.com/watch?feature=player_detailpage&v=8ApvEFOAegs#t=406s
at 6:45 priest with 7,1k SP , his pet does ~5.3k dmg.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/1004

**Comment by Faaith** [comment]
3773 reports later and still not fixed. Same goes for Spirit of Redemption.

**Comment by razgal** [comment]
formula for shadowfiend attack speed:
10 * (1 + Haste*0.01)
