### ISSUE TITLE
[ENG][Hallow's End] Stuck in Combat Bug after Horseman's death

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#4781]
![image](https://cloud.githubusercontent.com/assets/5083789/10758065/3791d12a-7caf-11e5-9af3-e2a07c8e8cda.png)
This is the entry of the npc keeping us in combat after the boss death.

**Comment by Thefakemccoy** [comment]
kill the head.. also 
https://github.com/Atlantiss/BugTracker/issues/4722
