### ISSUE TITLE
[EN][Quest][Argent Tournament] Up To The Challenge

### ISSUE THREAD

**Issue by drmetud** [Atlantiss/BugTracker#4783]
After completing the quest http://www.wowhead.com/quest=13672/up-to-the-challenge when you gather the 15 Aspirant's Seal http://www.wowhead.com/item=45192 by doing the daily quests http://www.wowhead.com/quest=13625/learning-the-reins , http://www.wowhead.com/quest=13671/training-in-the-field ETC ,you still have the same daily quest unlocked rewarding you with once again only the same aspirant's seals,which from this point are literally useless,shouldn't these dailies start rewarding Champion's seals http://www.wowhead.com/currency=241/champions-seal from this point or just be disabled after the quest is complete?

**Comment by Thefakemccoy** [comment]
Links

**Comment by drmetud** [comment]
Links?

**Comment by Thefakemccoy** [comment]
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Quest links 
Item Links
NPC Links

**Comment by LaveGit** [comment]
I'm quite sure that they should still grant Aspirants Seals, even though they're useless from the point.
The only reason to do those quests is;
- To progress in the chain quest
- To gain reputation with Sunreaver (for Horde) / and Silver(something) (for Alliance)

**Comment by drmetud** [comment]
Experience and reputation rewards are ok,but the Aspirants Seals are completely and utterly useless,checked in on wowhead.

**Comment by LaveGit** [comment]
This is not a question of whether or not the rewards are useless or not, but a question of how it is/was on retail.

If you have a proof that shows the quest shoudln't give Aspirants Seals, but something else instead, please do show us.

A lot of dailies doesn't actually give anything useleful, but it doesnt' mean it should be remade.
