### ISSUE TITLE
[EN] [Event] [Hallow'sEnd] [A Time to Lose] [Quest] [Alliance] 

### ISSUE THREAD

**Issue by mean931** [Atlantiss/BugTracker#4787]
The Quest "A Time to Lose" still bugged, as you can see :) 
1)http://i.imgur.com/NqxIxV6.jpg
2)http://i.imgur.com/b3GRU9p.jpg
3)http://i.imgur.com/lOuR0y0.jpg

**Comment by iliarakov** [comment]
yes is still bugged
