### ISSUE TITLE
[EN] [Event] [Hallow'sEnd][Hallowed Wand - Pirate] 

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4788]
pirate wand dont working i  use in player and dont happend noting 
http://www.wowhead.com/item=20397/hallowed-wand-pirate
Ubdate  dont working too 
http://www.wowhead.com/item=20398/hallowed-wand-ninja
http://www.wowhead.com/item=20409/hallowed-wand-ghost
http://www.wowhead.com/item=20399/hallowed-wand-leper-gnome

**Comment by BAndysc** [comment]
Fixed in 4646
