### ISSUE TITLE
[EN][Item] Bag of Fishing Treasures buggy loot (Outlands Fishing Daily Reward)

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#4791]
http://www.wowhead.com/item=35348/bag-of-fishing-treasures
http://www.wowhead.com/item=34863/bag-of-fishing-treasures

both of those should always at least contain something while you open/loot them, and they currently don't. 

Reading comments and retail experience, you should always receive:

1: gold (guaranteed around 7gold)
2: chance on recipe/weather beaten journal
3: fishing related items (hooks, baubles) (guaranteed to get something) 
4: chance on grey quality items/rare items 
5: for the bag with id 35348 the crocolisk pets are also part of the drops, not guaranteed to drop though

**Comment by xolon** [comment]
For my 10 months of farming Captain Rumsey's lager recipe 70-80% of these bags were empty.

**Comment by Thefakemccoy** [comment]
Alot of the bags and crates from fishing are empty some from the SW dail and IF daily can be empty

**Comment by Achiver** [comment]
I think most of containers (things you open) are bugged - ~50% of them are empty

**Comment by LaveGit** [comment]
1. Gold doesn't drop. Correct.
2. I've gotten the Weather Beaten Journal twice.
3. I almost always get hooks or bubbles. But again, not guarenteed here on Atlantiss.
4. I've gotten a lot of grey items.
5. I've gotten all 5 of the crocolisk companions from Crocolisks at the City quest. So that one works as well.

**Comment by Luna-maria** [comment]
I never said nothing dropped, just that it's empty a lot of times :)

**Comment by 1Andas** [comment]
I usually get few sharpened hooks, but I also recently received wather-beaten fishing hat from it, and today I got Toothy, non-combat pet companion.

**Comment by xolon** [comment]
Well i do these quests for quite a while now maybe 1 and a half year and i can tell you that most of em were empty. I have all 4 pets the seem to drop quite often.

**Comment by Docholiday-Atlantiss** [comment]
8056

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11607-80564791-crates-and-bags/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
