### ISSUE TITLE
[en][mage]Blast wave

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4792]
## What's wrong:
Blast wave does more damage than it should
## How it should be:
formula of Blast Wave is:
**851 to 1003+(0.143*SP)**

**Comment by blinkmaster** [comment]
where did u take this formula from? not saying its not as u say but just curious.

**Comment by Wolffenstein** [comment]
I can confirm that the formula is  851,00 to 1003,04 and SP Coeff = 0,14

**Comment by Jenovas** [comment]
When making reports like this add calculations. Show us how it works on our server, test if its caused by Spellpower scaling too much.

**Comment by razgal** [comment]
"I can confirm that the formula is 851,00 to 1003,04 and SP Coeff = 0,14"

It's correct, I forgot to take into account specialization.
