### ISSUE TITLE
[en][mage] pyroblast dmg

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4794]
## What's wrong:
Pyroblast initial damage does more damage than it should.
## Formula:
Hurls an immense fiery boulder that causes (1229 to 1561)+(1.545*SP) Fire damage and an additional X Fire damage over 12 sec.

**Comment by Jenovas** [comment]
When making reports like this add calculations. Show us how it works on our server, test if its caused by Spellpower scaling too much.
