### ISSUE TITLE
Overall lag (WoW434_Mini

### ISSUE THREAD

**Issue by kevininersj** [Atlantiss/BugTracker#4795]
Hello guys.
I've recently downloaded the private server Atlantiss. (WoW434_Mini version, torrent version did not work.
It has very much lag when I start the game and login on my character. I have downloaded alot of other WoW private servers as (Vanilla) Kronos (Wrath of the Lich King) TrueWoW, and could run it directly on ultra without any problems at all when I started the game from the beginning. Although I downloaded them from a torrent.
I think the game still downloads stuff in the background that causes the lag. Anyone who got some thoughts about this?

**Comment by Wolffenstein** [comment]
It's a mini-client. It means that you can download just a few files and start the game, but it will be downloading missing content as you play.
