### ISSUE TITLE
0 armor bug

### ISSUE THREAD

**Issue by piskoty** [Atlantiss/BugTracker#4796]
My feral druid  "Kráva" somehow has 0 armor.

It doesn't matter what I do. Any kind of relogg doesn't work. Re-equipping doesn't work.

**Comment by Jenovas** [comment]
Write a ticket in-game, it is probably an aura bug, have a GM ""unaura all" your Druid, and tell him to first make a list of all auras on you  (tell him that a dev asked for that).
