### ISSUE TITLE
[En][Quest-TBC][Hellfire Peninsula] Heart of Rage

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#4799]
When you enter the last boss's room, the quest have to be completed. But as I tested 2x times (abandoning and retaking), it didn't give me the credit.
Source: http://www.wowhead.com/quest=29536

**Comment by Aldurion** [comment]
It depends on what quest you are refering exactly. The quest Heart of Rage (quest ID 29536), http://www.wowhead.com/quest=29536/heart-of-rage#see-also , that was added in 4.3.4 at the entrance of the dungeon is working from what I remember.
The quest Heart of Rage (quest ID 9608) is not working.

**Comment by Samineh** [comment]
You are right @Aldurion Sorry for necro xD.
