### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by kevininersj** [Atlantiss/BugTracker#4800]
I've recently downloaded the TORRENT version of WoW434 instead of the mini client but I still have so much lag. As I said before in my latest post I can run normal WoW on ultra with triple buffering and have straight 60+ fps. 
I have downloaded 24% of the game in the background but does that have something with my fps to do?
I only get 60 fps when I have everything on low or disabled.

**Comment by xolon** [comment]
Disable Vertical Sync in Graphic options

**Comment by user1011** [comment]
Lowering resolution might help too.
