### ISSUE TITLE
[EN][Stormwind][NPC] King Varian Wyrnn

### ISSUE THREAD

**Issue by WladerDark** [Atlantiss/BugTracker#4803]
i found not king varian in castlle of stormwind in his throne

**Comment by Thefakemccoy** [comment]
cause the horde killed him

**Comment by WladerDark** [comment]
how long respawn ?

**Comment by WladerDark** [comment]
1 wait more at 1 hour

**Comment by Thefakemccoy** [comment]
idk the respawn timer but i know the horde did kill him so the respawn timmer might be high

**Comment by Thefakemccoy** [comment]
prob want to edit the title to something like [EN][Stormwind][NPC] King Varian Wyrnn

**Comment by razgal** [comment]
from my own experience respawn timer is around 48 hours (?)

**Comment by Thefakemccoy** [comment]
he showed up like 13hrs later last night but the timer should not be that long since he revolves around some quests.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6641-city-king-wrong-respawn-time/
