### ISSUE TITLE
[EN][Guild] Guild Vault crash

### ISSUE THREAD

**Issue by kmlck** [Atlantiss/BugTracker#4805]
I opened my guild vault to grab a few items but the game crashes when i was switching between tabs. I tried opening it again to see if it was a random bug but again the game crashed. This is the crash report.
![untitled](https://cloud.githubusercontent.com/assets/15521036/10863422/238e9956-7fde-11e5-9add-c9ef972a4716.jpg)

**Comment by Aviannaqt** [comment]
Duplicate
