### ISSUE TITLE
[en][tailoring]enchants icd

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4807]
tailoring back enchants have the wrong icd.
Swordguard Embroidery
Lightweave Embroidery
Darkglow Embroidery
## how it should be:

on our server icd is 45
it should be 55
## Proof:

http://www.tankspot.com/showthread.php?75684-Swordguard-Embroidery-Proc-rate-and-ICD

**Comment by Kejmil** [comment]
page not found

**Comment by razgal** [comment]
google.com

http://forums.elitistjerks.com/forums/topic/104491-cataclysm-mechanics-testing/

**Comment by Pocketerino** [comment]
Lightweaves cooldown was indeed changed from 45 secs to *65* secs, not 55, somewhere during cataclysm, and it was present during 4.2 too btw. This mistake buffs casters tho, especially fire mages, since the dmcs cd is 45 secs too, so plox dont fixerino.

**Comment by Piklo** [comment]
@Pocketerino icd should be 55 sec :P 
https://us.battle.net/forums/en/wow/topic/3881712288
