### ISSUE TITLE
[en][priest] inner focus cd

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4808]
## What's wrong:
if you spam too fast the button for Inner Focus,afer you cast a spell you can't see anymore the cd of Inner focus

probably same for Nature's swiftness from resto druid and shaman

**Comment by xolon** [comment]
happens with many instant spells that have longer cd

**Comment by debtheone** [comment]
https://github.com/Atlantiss/BugTracker/issues/2062
