### ISSUE TITLE
Problem with Precious Cargo quest (urgent)

### ISSUE THREAD

**Issue by Zombarian** [Atlantiss/BugTracker#4811]
Hi my character name is Zombarian, and i have problem with a quest in the game. I play as a gnome, and i have a quest that involves being carried by a "Gyrochoppa" to a boat. See the problem is that the "Gyrochoppa" left me in the water near the boat and i can't get ON the boat, making the quest impossible for me. When i try talking to the "Gyrochoppa" i just get the message Greetings Zombarian! 

Please help ASAP

**Comment by Bildo** [comment]
abandon and take quest again

**Comment by philozofer** [comment]
I have the same problem, I'ven abandon and retook the quest at least 5 times and it always drop me in the sea instead on the boat!
