### ISSUE TITLE
[EN][Spell][Warlock] Incinerate damage with immolate

### ISSUE THREAD

**Issue by blizzlaic** [Atlantiss/BugTracker#4814]
Incinerate damage doesn't add the correct bonus with immolate on the target.
Ex: 
Spell sais 4950 damage (+ 820 damage if target is affected by immolate). At the moment the +820 damage is not correctly added, and the result is somewhere around 4950 + ~200.
Game breaking bug.

**Comment by Jenovas** [comment]
Please add links to the spells.
Also calculate the DMG if you may to make sure that the DMG is wrong.

**Comment by Glare** [comment]
Warlocks drama...

But seriously, you can't count on the tooltips. If you want the true dmg you should deal find another source.

**Comment by Lenox07** [comment]
http://cata.openwow.com/spell=348
http://cata.openwow.com/spell=29722
Well if i have good coeffs inci dmg on targets with immolate is correrct but the dmg without is wrong and should be lower. 
without immolate:
7036*0.539=3792,404    3792.404*1,372=5203,178
with immolate:
7036*0.629=4425,664    4425,664*1,372=6071,983
(7036*0.09)*1,372=868,805
It may be error with base dmg that i didnt calulated. But only bug i see that inci deals higher dmg without immolate on target. 
![wowscrnshot_110115_171529](https://cloud.githubusercontent.com/assets/9517740/10869894/18561c3c-80bd-11e5-8580-de97793cd7af.jpg)
![wowscrnshot_110115_171553](https://cloud.githubusercontent.com/assets/9517740/10869892/0a636cd8-80bd-11e5-98c8-53f9ccbf7b6d.jpg)

**Comment by Thefakemccoy** [comment]
You cant go by tooltips its only a average. 4950 does not mean 4950 every cast.
All spell and ability tooltips will now display damage averages rather than minimum and maximum damage potential. This feature is on by default but can be changed via the Display settings under User Interface options.

**Comment by meowmewo** [comment]
This was recently fixed. You can close this one.
