### ISSUE TITLE
[PL][QUEST][DK] Problem z opuszczeniem lokacji

### ISSUE THREAD

**Issue by Luim00** [Atlantiss/BugTracker#4822]
Grałem z kolegą i robiliśmy questa "The Light of Dawn" nagle pojawił się problem gdyż nic się nie działo na miejscu gdzie powinno się coś stać. Więc postanowiliśmy wyrzucić zadanie i wrócić się Scourgestone'em na Argerus'a. I tu pojawia się problem nie jesteśmy w stanie opuścić Argerusa w żaden sposób portal, który prowadził na piętro niżej nie działa. Proszę o szybką odpowiedź :) 

Dodam, że próbowałem użyć Unstack'a z Shop panel'u jednak nic to nie pomogło.

**Comment by Anhaeyn** [comment]
Ten quest jak porzuciliście, to wystarczyło go wziąć ponownie i wrócić na miejsce, gdzie miał odbyć się ten quest. Niepotrzebnie wracaliście tam na górę.

**Comment by Luim00** [comment]
Jest jakiś sposób opuszczenia Argerus'a? Może administracja była by wstanie nas wyteleportować do obozu pod nim?

**Comment by Luim00** [comment]
BUMP
