### ISSUE TITLE
[EN][Quest][Isle of Quel'danas]Disrupt the Greengill Coast

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#4823]
http://www.wowhead.com/quest=11541/disrupt-the-greengill-coast seems to be missing from the isle of quel' danas. 
Comments on wowhead say the questgiver is supposed to appear on the island after phase 3 of reclaiming the island.
I'm assuming all of those phases are just not active (since TBC content is way old) and the NPC is already there
She just isn't giving out the quest

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8198-4823questisle-of-queldanasdisrupt-the-greengill-coast/
