### ISSUE TITLE
[EN][Item][Jewelcrafting] No loot from Fire Prism

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#4829]
When using the "Fire Prism" (http://www.wowhead.com/item=52304/fire-prism#contains) I created I got no loot but an error message "That slot is empty". It appears that the loot table is bugged.

**Comment by Luna-maria** [comment]
I got this once or twice too :/

**Comment by Erinti** [comment]
Happened to me today, exactly the same thing.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11914-4829-fire-prism-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.

**Comment by sigmundfreud2016** [comment]
Got same problem today at 16:20, char Grassone.
![wowscrnshot_123116_162225](https://cloud.githubusercontent.com/assets/12395407/21578124/4bba54b4-cf75-11e6-89db-9785bbe3b0a6.jpg)
it's pretty frustrating to spend ~300 g and get nothing but 1 skill point.

**Comment by sigmundfreud2016** [comment]
![wowscrnshot_010817_230533](https://cloud.githubusercontent.com/assets/12395407/21753943/00d77818-d5f7-11e6-91fd-72210c04dc9a.jpg)
and yet again, this time I made screenshot right in time, you can see "This slot is empty" fading.

**Comment by dphat** [comment]
I've been having this same issue. It's the 2nd time today that I got empty prism with the same messages that the above players got 

Character: Dphatdk

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12960-4829-fire-prism-loot-tables/

**Comment by dphat** [comment]
Error Still occuring. Has the fix been uploaded? 
[wowscrnshot_012017_071049](https://cloud.githubusercontent.com/assets/25198546/22134581/8f7afeee-dee1-11e6-8d00-1c32e703f746.jpg)

**Comment by Piklo** [comment]
fix is not accepted yet, Bildo is too busy :P

**Comment by sigmundfreud2016** [comment]
![wowscrnshot_012517_023622](https://cloud.githubusercontent.com/assets/12395407/22274502/28291c16-e2a7-11e6-99ca-9a6f244f0107.jpg)
just now

**Comment by Piklo** [comment]
[rev. 5295](http://atlantiss.eu/changelog#rev5295) is "Waiting for update" so you won't see any changes before it will be on server

**Comment by dphat** [comment]
Piklo, i waited for rev. 5295 to load after today's restart and quite a time passed until the server restart. I created a fire prism and opened it but the same Empty slot appeared. 
I was unable to capture screenshot at the time of 'This slot is empty' message so basically for me at least this issue hasn't been fixed.
Appreciate your expertise on this matter towards a resolution as this pretty much makes being a Jewelcrafter pointless and my guild's JC for raids

**Comment by sigmundfreud2016** [comment]
@dpchat
> this pretty much makes being a Jewelcrafter pointless

You are exaggerating. It is just annoying. All gems but inferno rubies are very cheap anyway, but still getting nothing while spending something is bad.

**Comment by dphat** [comment]
@sigmundfreud2016 How is your comment helping anyone on a bugtracker? Also, you've gotten my name wrong but you can make it up to me by buying all my gems henceforth. 

Important thing is Piklo's looking into this. 

Irrespective of your opinion, spending 18 gems prospected from catacylsm ores for an item on 24hr cooldown to obtain an empty slot(which wasn't designed to be as the contents are random but never empty) is certainly not blizzlike and so my hope is that this will be remedied soon.

**Comment by sigmundfreud2016** [comment]
@dphat I am the one who posted a lot of screenshots here, there is no need for further proofs. You can still buy and cut any blue quality gems you want. That's what JC is about. Prism is just a little gamble which raises you skill at the same time. You may get 3 inferno rubies which is profitable or 3 dream emeralds which cost much less than ~300g you've lost by spending 18 green quality gems on it.
BTW there are other JC bugs which were just as annoying (if not more), when I was raising JC, however they are completely irrelevant for the end-game and therefore may never be fixed:
https://github.com/Atlantiss/BugTracker/issues/3340
https://github.com/Atlantiss/BugTracker/issues/310

**Comment by dphat** [comment]
@sigmundfreud2016 You're diverting from the topic of this thread (Dphatdk ingame if you want counters to your opinions, I wont reply to you here)

@Piklo Regret the sidetrack but appreciate your fix on this nevertheless

**Comment by stanq87** [comment]
still bugy, got an ampty prism yestarday and today,  rev. 5298

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/13080-4829-fire-prism-loot-tables/

**Comment by deadspear** [comment]
Its back to the same Black Diamond. Just did it today only Prismatic Black Diamonds.
