### ISSUE TITLE
[EN][Quest][Western Plaguelands] Latent Disease

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#483]
# What is not working:

Every Diseased Black Bear drops only 1 Plague Tangle. 

---
# How should work:

Diseased Black Bears should drop around 4 Plague Tangle.

---
# More info:

The herb is kinda different from the video & screenshot below.

[Screenshot](http://i.imgur.com/GbgzOwp.jpg)
[Video](http://youtu.be/YdGUJW5-jCw?t=10m2s)
[WoWHead's Screenshot](http://wow.zamimg.com/uploads/screenshots/resized/191885.jpg)
[Latent Disease - WoWHead](http://www.wowhead.com/quest=26934)
[Latent Disease - WoWPedia](http://wowpedia.org/Quest:Latent_Disease)
[Plague Tangle](http://www.wowhead.com/item=60679)
[Diseased Black Bear](http://www.wowhead.com/npc=1815)

**This was tested on 4.0.6a realm**

**Comment by Hacker--x** [comment]
There bears do not even spawn in 4.3.4. Just tested

**Comment by Thefakemccoy** [comment]
There are only 3 or 4 of the diseased bear.
There should be more according to wowhead.
http://www.wowhead.com/npc=1815/diseased-black-bear

**Comment by krecik88** [comment]
fixed in 5287
