### ISSUE TITLE
[en][priest] levitate vs. channeled spells

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4830]
if u levitate and then cast penance, while changing your camera position,your penance cast will stop

**Comment by debtheone** [comment]
works fine for me

**Comment by razgal** [comment]
press right click and change camera position after you started casting penance

**Comment by debtheone** [comment]
thats what i did

**Comment by razgal** [comment]
you do it wrong then

**Comment by debtheone** [comment]
xdxdxd

**Comment by razgal** [comment]
ok after few more tests this doesn't happen all the time and can happen to any spell thats channeled

**Comment by razgal** [comment]
another way to reproduce:
bind "Turn Left" , "Turn Right" in keybindings with "A" "D" , cast penance and then press "A" or "D"
