### ISSUE TITLE
[EN][Zone][Deephom]falling

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4832]
ok  with my friend get quets in hero call for deepholm ..... and we arrived in The Melstrom and get quets from  Thrall  and get mout to go in Deepholm but before teleporting and arrival in deepholm my friend is fall from maunt and he die  and now he cant go in The Melstrom and get mount to go in deepholm he cant get portal from  stormwind because he dont finished first quets and he dont arrived for first time in zone  he try to abandont quets but he cant go in The Melstrom to get quest and get mount and arrival in deepholm is it possible to fix that or teleport him his  character in The Melstrom to get quets from thrall and get mount to arrive in deephom  in his name is Decklenes

**Comment by Luna-maria** [comment]
let your friend make a ticket

**Comment by iliarakov** [comment]
ok thank you
