### ISSUE TITLE
rev 4363

### ISSUE THREAD

**Issue by Andelen** [Atlantiss/BugTracker#4833]
This rev was supposed to fix energy regeneration when suffering an attack speed debuff, but on the server right now energy regen can be lowered to 0 through this kind of debuff. Happens on bosses like Altairus from the Vortex Pinnacle and in many mobs through the game. Basic energy regen is 10. Even getting a 100% haste debuff wouldn't lower your energy regen to 0. This is a game breaking bug for both rogue and feral druid, and should be fixed.

**Comment by Jenovas** [comment]
This rev was supposed to fix PvP debuffs from reducing energy/rune regen and it did.
Closing.
