### ISSUE TITLE
[EN] [Spell] [Warlock] Soul harvest triggers Power torrent & Lightweave tailoring enchant

### ISSUE THREAD

**Issue by vanael** [Atlantiss/BugTracker#4834]
http://www.wowhead.com/spell=74242/power-torrent
http://cata.openwow.com/spell=75172

In power torrent it says that when we deal damage it should trigger, but it triggers while casting soul harvest which does not deal any kind of damage. However I am not so sure about lightweave because it is not clearly said that it triggers damage/healing spell. In fact,when I soul harvest before encounter to gain some shards I waste very important burst cooldown from enchants mentioned above. I believe it should not work in that way.
![wowscrnshot_110315_064236](https://cloud.githubusercontent.com/assets/5870498/10901909/b83cde4a-81f6-11e5-95d2-dc84e9a8ae8f.jpg)
![wowscrnshot_110315_064240](https://cloud.githubusercontent.com/assets/5870498/10901908/b83ca718-81f6-11e5-81b1-cd573f5e88c2.jpg)

**Comment by Kejmil** [comment]
"dealing damage or healing with spells"
"casting a spell"
soul harvest is spell and is also healing you
working as intended

**Comment by vanael** [comment]
Even though it is trange that it triggers without combat and you waste your power torrent and lightweave :/
