### ISSUE TITLE
[PL][Quest/Zone] Deepholm

### ISSUE THREAD

**Issue by tomaszek123** [Atlantiss/BugTracker#4837]
Nie mogę dostać się do deepholm. Zaczynałem chainquest otwierajacy portal do deepholm, lecz gdy już pogadałem z Thrallem w Maelstormie i wsiadłem na wyverne to zsiadłem z niej w trakcie lotu (myślałem, że tak trzeba) i musiałem użyć HS'a do Orgri. Niestety nie mogę ponownie wziąć Questa ani nie mam jak dostać się do Maelstrom/Deepholm

**Comment by Faaith** [comment]
Kup na AH potion of deepholm.
