### ISSUE TITLE
[EN] Blizzard Main bar covering the chat

### ISSUE THREAD

**Issue by kimo8532** [Atlantiss/BugTracker#4838]
This is the problem 
http://puu.sh/l9nuq/acfc0f0601.jpg
This is the fix : (blank)
I redownloaded the game done everything still no work
Help
plz

**Comment by Thefakemccoy** [comment]
right click general unlock it and move it where ever you want.

**Comment by Thefakemccoy** [comment]
you can also press esc go to options under advanced check ui scale and scale your ui down

**Comment by kimo8532** [comment]
This thing never happend before... it just got bigger...
