### ISSUE TITLE
[EN][Quest] The Altar of Storms

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#484]
So, this Polish guy that reported this quest from the horde side closed his report for whatever reason.

So I'm just gonna open a new one, this is from the Alliance side, though.

**The Altar of Storms** (http://www.wowhead.com/quest=26162) is completely bugged. There's no point in even writing up the details. Just look at the quest being done on youtube (https://www.youtube.com/watch?v=Td8wXl0d9wU), then check out for some extra details if you can find them on wowhead, there's a lot to be looked at in the comment section, aaaaand get to fixing. :)

**Comment by Dearkus** [comment]
Still not fixed in 4.3.4

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/409

**Comment by Exorcista** [comment]
this happens to me for not having bugtracker in bookmarks lol, confirming this today.

**Comment by worgenman** [comment]
yea pls fix it its still bugged

**Comment by coba999** [comment]
not working.
![wowscrnshot_111015_215635](https://cloud.githubusercontent.com/assets/15231821/11074019/0d55a40c-87f6-11e5-826b-845904fb8ab8.jpg)
