### ISSUE TITLE
[EN][Quest][Mount Hyjal] Prepping the Soil

### ISSUE THREAD

**Issue by Wajju** [Atlantiss/BugTracker#4840]
Referencing closed issue #1600 

The bug seems to still be occuring, the Flameward has been unusable for the past hour.
Quest: http://www.wowhead.com/quest=25502/prepping-the-soil
Part of the main Hyjal quest line so it's stopping progress through the zone.

**Comment by Thefakemccoy** [comment]
did you try all of them or just the one?

**Comment by Wajju** [comment]
There are not other flamewards in the zone that I can find and I double checked each spot where the quest tracker says they should be. Only the one at 33,64 (outside the cave) seems to spawn and it's currently not working.

**Comment by LaveGit** [comment]
Confirmed. It's bugged atm.

**Comment by Simgiov** [comment]
It worked for me, the one at the cave.
