### ISSUE TITLE
[EN][NPC][Blade's Edge Mountains] Death's Door Fel Cannon

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4842]
The Fel Cannon is missing, making the quest Fire at Will! impossible to complete.

NPC: http://www.wowhead.com/npc=22443
Quest: http://www.wowhead.com/quest=10911

**Comment by Bildo** [comment]
fixed by Dimbaheca

**Comment by jissabraham** [comment]
unable to control Fel Cannon
