### ISSUE TITLE
[EN][Event][Hallow's End][Quests] Taking Precautions

### ISSUE THREAD

**Issue by klm670** [Atlantiss/BugTracker#4844]
The quest Taking Precautions (http://www.wowhead.com/quest=29402/) is bugged, because the Blood Nettle (http://www.wowhead.com/item=71035) is unclickable, and therefor unobtainable. This is in the quest chain for the creepy crate.

**Comment by Bastion** [comment]
delete cache or go collect in orgrimmar

**Comment by Illusionist87** [comment]
Horde one is also bugged and clear cache doesn't work

**Comment by Thefakemccoy** [comment]
Can confirm they are unclickable.
![wowscrnshot_110515_134858](https://cloud.githubusercontent.com/assets/12252441/10978279/ffdfe048-83c3-11e5-8f27-41272edd6cb8.jpg)

**Comment by klm670** [comment]
Neither option works, Bastion.

**Comment by gurin** [comment]
Still don't work

**Comment by Bildo** [comment]
will work after crash

**Comment by BAndysc** [comment]
You see guys, crashes are fixing content :)

**Comment by Thefakemccoy** [comment]
server just came up from a crash and still cant collect them.

**Comment by Bildo** [comment]
quest is working for me (alliance char)
