### ISSUE TITLE
(QUEST) HELP! nagrand

### ISSUE THREAD

**Issue by mcfreddas** [Atlantiss/BugTracker#4846]
The npc is not in his cage and there for u can't open it

**Comment by Bastion** [comment]
awesome

**Comment by Illusionist87** [comment]
Why is this thread closed? The quest isn't fixed and it is not the same bug as other threads for this quest. 

Still not working, if anyone is interested.

**Comment by schwim0341** [comment]
Because Atlantiss is Blizzlike in the way that they treat the end user by ignoring their input.

**Comment by Bildo** [comment]
You didn't even read bugtracker rules also quest is working

**Comment by Illusionist87** [comment]
The NPC cage disappears after use of the quest item. Only server crash bring it back.
In my particular case I had to wait day and a half for cage to respawn again (which in one hand is good, since we didn't crash a lot in that time)
