### ISSUE TITLE
[EN][Quest] Stopping the Spread

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#485]
<s>Some</s> Majority of the **Sunspring Villagers** (http://www.wowhead.com/npc=18240) don't give you the count for **Stopping the Spread** (http://www.wowhead.com/quest=9874) when you use **Torch of Liquid Fire** (http://www.wowhead.com/item=24560) on them.

<s>A lot of them do, though, so the quest can be completed.</s>

Majority of them won't give you the count for the quest, but some of them will, so it takes a while to finish the quest.

**Comment by krecik88** [comment]
fixed in 5244
