### ISSUE TITLE
[EN][mob] Gilneas Combat Bug

### ISSUE THREAD

**Issue by cosminn123** [Atlantiss/BugTracker#4850]
Entry: 35118, Name: Bloodfang Worgen, GUID: 5186466, X: -1719.275269, Y: 1404.761719, Z: 21.668991
Entry: 35118, Name: Bloodfang Worgen, GUID: 5186467, X: -1721.270630, Y: 1409.450806, Z: 21.668991

**Comment by Thefakemccoy** [comment]
#4722
