### ISSUE TITLE
[en][priest] penance third tick

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4852]
## What's wrong:
sometimes Penance third tick doesn't land.
BUT the Grace stack lands.
## Proof:
http://tinypic.com/r/280oytc/9 -> third grace landed but no penance tick.

I don't know how to reproduce, happens randomly, a random pattern I found it might happen after you cast Power Word Shield (and get Borrowed Time buff) ,so might be a haste issue with penance.

**Comment by dantethehunter** [comment]
I Agree. Penance is bugged and 1 in 5 times 3 tick doesnt land indeed. It has nothing to do with haste or power word shield, I lvl up my priest and this bug exists even in very low levels. Its just bugged and its serious. Affecting both pve and pvp situations.

**Comment by Kaldros** [comment]
Bump because this is a high priority issue for disc priests!

**Comment by debtheone** [comment]
did test 4/10 penance were 2 ticks. its realy huge for disc *_*

**Comment by Kaldros** [comment]
Yeah, it's a pretty big issue, idk why this is not marked as high priority...

**Comment by Wolffenstein** [comment]
Should be fixed in rev 4901 (or happen less often). Please test.

**Comment by debtheone** [comment]
<3 Wolf

**Comment by debtheone** [comment]
works fine, thanks

**Comment by Kaldros** [comment]
Did 100 Penances in a row and they all had 3 ticks each. Great fix! Thank you so much!

**Comment by Illusie** [comment]
is it possible that the Penance bugged again? character ilvl 230. but Penance should always do 3 ticks even with Ilvl 0. If I am right.

http://imgur.com/a/OaVXD
http://imgur.com/a/jgvRE
