### ISSUE TITLE
[EN][Class][Paladin] Censure(dot)

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#4853]
http://www.wowhead.com/spell=31803/censure#changelog

The censure spell itself works fine, though there is something wrong with the crit% of this spell. I'll prove this;
This is the recount from a boss we killed yesterday evening (al'akir hc):
http://i.imgur.com/q6FXTD9.jpg
As you may see, the spell had ticks (normal hits for 94.4% of the time) and critted 5.6%. Now if i look at my crit%, i have 7.53% crit ( with raid buffs that makes it be around 13%). Now i wonder why i get crits on this spell during raids, though when i'm solo i get 0 crits on this spell. (Does this mean it only scales on raid crit%?).
Here is an example of when i attack a dummy for few minutes:
http://i.imgur.com/21uHSZe.jpg
As you can see for yourself, 0 crits.

Now the question is, is it supposed to crit? If so, than why does it only crit when i'm in a raid which provide me crit%?

**Comment by Kejmil** [comment]
boss crit suppresion?

**Comment by Frainzil** [comment]
As i said before, the first print screen is from al'akir heroic boss, the 2nd one is from a heroic dummy. Both are elite mobs and should have a similar crit suppresion. Though i see a difference of atleast 5% in crit%. If the problem was regarding an overall crit% that would be to low, than yes it might have been crit suppresion, but here we have 2 totally different crit% though both are elite mobs of lvl 88+
