### ISSUE TITLE
[EN] [Class Druid] Feral Maim

### ISSUE THREAD

**Issue by Slotease** [Atlantiss/BugTracker#4854]
Feral maim is a combo based attack. My cat only gets one second of Maim stun no matter how many points i put into maim.

**Comment by Slotease** [comment]
I cant pvp in feral at all cos that skill is not working

**Comment by Thefakemccoy** [comment]
i get 3 secs with 5 combo points

**Comment by Jenovas** [comment]
How did you test this? From my tests it lasts 1 second for every cp on the target

**Comment by Kejmil** [comment]
from topic on forum i guess that this guy don't know what DR is

**Comment by Slotease** [comment]
How did i test this? By playing the game. I built up points and then use Maim. No matter how many points i have i still only get one second of maim.

Dr? Those are two letters mate. D and R. Wanna be more specific?

**Comment by Slotease** [comment]
For me at least it is fixed now so thanks
