### ISSUE TITLE
[PL][Spell][Warlock] Conflagrate

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#4857]
Link spell: http://cata.openwow.com/spell=17962
Link buff: http://cata.openwow.com/spell=77987

Conflagrate penetruje buff na addach Maloriaka i zadaje 100% obrażeń.

Albo poszedł taki nerf, że aż buff albo coś nie tak z buffem addów ;]

Atlantyda nerf pls

**Comment by Wolffenstein** [comment]
ups

**Comment by Glare** [comment]
Czy jest możliwe, że przebija kazdą redukcje obrażeń? PvP gracze wzywam was!

**Comment by Brotor** [comment]
To chyba nie chodzi o redukcję tylko aury na celu w który bijesz. W halfusa na bufie z 3 smoków największy cryt z confli 36k miałem.

**Comment by Wolffenstein** [comment]
Fixed in rev 4654.
