### ISSUE TITLE
[EN] [Talent] [Druid] Eflorescence

### ISSUE THREAD

**Issue by Ringerils** [Atlantiss/BugTracker#4858]
Eflorescence :Your Swiftmend spell causes healing flora to sprout beneath the target, restoring health equal to 12% of the amount healed by your Swiftmend to the three most injured targets within 8 yards, every 1 sec for 7 sec.

The problem is that the AOE HEAL created by this talent , heal all the targets that are inside the circle, instead of healing the most injured THREE targets.
I think this bug is a big buff for resto druids and should be fixed according to the server blizzlike status.

**Comment by Reversion** [comment]
Please give us some proof that now is malfunctioning. On what basis you say that 's a bug?

**Comment by Jenovas** [comment]
Eflorescence has two bugs. The first one is as stated above that it heals everyone in Eflorescence.
The second one is that the more players are inside the lower the healing, so it isnt a big buff for resto druids, I'd say it a nerf cause a lot of the healing get's wasted and the people that rly need the healing dont get it.

**Comment by Ringerils** [comment]
I totally agree with jenovas.

Well maybe a proof video could help . But this is very easy to test in game . You just have to join a dungeon as resto and u will see that all the targets ( including pets )which are inside the spawned circle are healed  and the healing amount varies ,depending on how many targets are inside. ( more targets = less heal . Less targets = more heal ) .

**Comment by Reversion** [comment]
I agree with you. I am confident that the fix will work as it should. Including all factors, talents and modifiers.

**Comment by Reversion** [comment]
hmm
This Talent works propertly imo.
Cataclysm Patch 4.0.3a (2010-11-23): Now have a diminished effect when healing more than 6 players at once.

http://wow.gamepedia.com/Efflorescence

**Comment by Wolffenstein** [comment]
It doesn't. It was redesigned in 4.1.0:

Cataclysm Patch 4.1.0 (2011-04-26): Has been redesigned. It creates a healing zone at the feet of a [Swiftmend] target, but this healing zone now restores health equal to 4/8/12% of the amount healed by Swiftmend to the three most injured targets within 8 yards, every 1 second for 7 seconds. This periodic effect now also benefits from spell haste, but the individual ticks cannot be critical effects. In addition, [Living Seed] is no longer a prerequisite talent for Efflorescence.

**Comment by Illusie** [comment]
same happen with Healing Rain I guess.

**Comment by Jenovas** [comment]
Fixed in rev  4703
