### ISSUE TITLE
[EN][Shaman][Spell] Thunderstorm

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#4859]
Sometimes players immune to thunderstorm damage and knockback without a reason.
I noticed it mostly with warriors (no, they not using bladestorm at the time).

![image](https://cloud.githubusercontent.com/assets/3641625/11015211/f55f4a26-856e-11e5-8165-063202ea6151.png)

As you can see, Klezmir (warrior) was completly immune for thunderstorm.
Hunter pet was nearbly and was immune too but not for damage.

**Comment by Crusaderz** [comment]
![image](https://cloud.githubusercontent.com/assets/3641625/11019719/0a597194-861f-11e5-9e8e-310713e8f3ff.png)
Has a 45s cooldown, which all melee have gap closer cooldowns (charge, shadowstep, etc) to counter and does not work? Not Cool.

**Comment by Wolffenstein** [comment]
"Sometimes" doesn't really tell us much. Unless you find a way to reproduce this "bug" (if it truely is a bug) then we have nothing to work with.

**Comment by klm670** [comment]
Not a warrior myself, but as I recall, warrior and dks have immunity to knockbacks on cd, like ibf for dks.

**Comment by Crusaderz** [comment]
I played warrior and DK during cata on retail, so i know their possibilities. Frost DKs have pillar of frost, while arms warriors gains immunity to knockback during bladestorm. And diminishing returns for knockbacks (10 sec immunity) introduced only in patch 5.4.

So, about "if it truely is a bug" - yes, it's a bug. Might be something wrong with charge mechanic, since in all cases it happened after warrior charges on me (you can see it on second screenshot).

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/4827

**Comment by aneq** [comment]
it's berserker rage (a warrior spell)
berserker rage and pillar of frost effects are swapped (berserker rage makes you immune to knockbacks, something only pillar of frost should do, and vice versa)

**Comment by Frainzil** [comment]
'' which all melee have gap closer cooldowns'' RIP paladins, let's go judgement, speed me!

**Comment by razgal** [comment]
You probably used Thunderstorm on a warriors bladestorm, or a rogue in Cloak of Shadows.
Or paladin in bubble.

**Comment by Crusaderz** [comment]
aneq: wow is it real?

**Comment by Kejmil** [comment]
on 4.3.4 ptr was working fine ( ͡° ͜ʖ ͡°)

**Comment by Jenovas** [comment]
Fixed in rev 4716
