### ISSUE TITLE
[en][core][arena] points gain for win/loss

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#4862]
How it should be : 
- you have 2600 team rating , 2000 mmr and personal and you are facing 2000 team - after you win arena it should : 
increase your team rating by a small margin ( points gained are calculated from 2600 - 2000 ratio )
your mmr and personal increase by 90+
if you lose arena it should be : 
you lose points by ALOT ( 2600 - 2000 ratio )
you lose personal and mmr in ratio to the team ( 2000 - 2000 ) so 15 rating

how is it working on our server:
you win arena ( stats as stated above ) you get points from mmr rating - thus on 2600 personal you get 15 arena team points 
you get + 15 personal and mmr
if you lose : 
you lose team rating by small margin (11-15 points )
you lose personal and mmr rating by a small margin ( 11-15 points )

plz fix this asap.
and plz enable the fixes which were before coz they worked perfectly fine ;/ now with 90-0 win ratio and 2300 starter mmr i have like.. 1800 team rating.

**Comment by deadlycalm** [comment]
maybe its not my problem but fix it before season ends.. now it's impossible to gain rating

**Comment by blinkmaster** [comment]
Bump
