### ISSUE TITLE
Combat bug Report ( With Screen Shot )

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#4864]
its in the chat window at the bottom left i used .combatlist

![wowscrnshot_110815_040801](https://cloud.githubusercontent.com/assets/4362814/11019781/8b825020-85ce-11e5-8d06-90e1579e773f.jpg)

**Comment by LaveGit** [comment]
There is an official thread to post all the combat bugs; https://github.com/Atlantiss/BugTracker/issues/4722

**Comment by Bud1980** [comment]
ty
