### ISSUE TITLE
[EN][Quest][Horde][Stonetalon Mountains] Beginning of The End

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#4866]
Quest: [Beginning of The End - (ID: 26074)](http://www.wowhead.com/quest=26074/beginning-of-the-end)

Problem: The quest require you to jump into the [Krom'gar Hot Air Balloon](http://www.wowhead.com/npc=42030/kromgar-hot-air-balloon) and escort it to the Sludgewerks. When you try to go inside using the rope (the only thing that is clickable) instead of going in, you release the bomb attached at the balloon (of course without any effect).

**Comment by Angelo-DM-** [comment]
Can you please tell me why you have closed this issue?

**Comment by Bildo** [comment]
because it's duplicate?

**Comment by Angelo-DM-** [comment]
#4869 is the issue for the Achievement... there are 5 bugged quests that blocks 8 more quests.
#4866 is for the specific quest. If you say that #4866 is a duplicate of #4869, then ok.
Sorry if i've not noticed it.

**Comment by Bildo** [comment]
Well in my opinion merged issues looks better (for example https://github.com/Atlantiss/BugTracker/issues/3593 and https://github.com/Atlantiss/BugTracker/issues/3558) because it lets us see how many bugs are in zones so because you listed every quest that does not work i closed other issues,

**Comment by Angelo-DM-** [comment]
i agree with you opinion! Now that you have closed all the others issues i understand what you mean!
Thank you for your explanation!
