### ISSUE TITLE
[EN][NPC] Fargo Flintlocke

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4867]
http://www.wowhead.com/npc=44806/fargo-flintlocke
i cant get quest from him i click but dont happend noting i finished one quets him but he give new and new quets cant get !!  
![wowscrnshot_110815_161513](https://cloud.githubusercontent.com/assets/12482135/11020813/e170b470-8634-11e5-988a-50b465bdfa25.jpg)

**Comment by Thefakemccoy** [comment]
TH is not open yet that is why.

**Comment by iliarakov** [comment]
aha im very stupid :D
