### ISSUE TITLE
[EN][NPC] Ramkahen prisoner

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4870]
wowhead http://www.wowhead.com/npc=46425/ramkahen-prisoner
wowhead http://www.wowhead.com/quest=27707/neferset-prison
 video https://www.youtube.com/watch?v=S5vE-fQDw1k
 screenshot 
![wowscrnshot_110815_222340](https://cloud.githubusercontent.com/assets/12482135/11022441/d9bdf6f6-8667-11e5-99b9-cf3ce9e5c169.jpg)

hello  i get quets Neferset Prison and when i go is need to speak with npc Ramkahen prisoner but i clik in npc but noting happend

**Comment by xolon** [comment]
someone already did the quest, wait few mins and try again

**Comment by iliarakov** [comment]
ok thank you :)

**Comment by Thefakemccoy** [comment]
Its not bugged just did it before typing this. 

PLZ close this report.

**Comment by xolon** [comment]
I think it kinda works like this, mobs are invisible and you can't aggro them, so when you talk to the npc they become visible and attack you. So when you kill them they have to respawn and you can't repeat the quest instantly which shouldn't be the case
