### ISSUE TITLE
[EN][Huntard][Talent] Lock and Load

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#4872]
http://cata.openwow.com/spell=56342
http://cata.openwow.com/spell=56343

http://wow.gamepedia.com/Lock_and_Load

" Patch 3.2.0 (2009-08-04):
Now has a 22 second cooldown. <b>The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used.</b>"

On Atlantiss you can still gain L&L procs from targets immune to snare effect from Ice Trap (modern Frost Trap) resulting in more dmg in pve (using traps on bosses or adds immune to snares), propably also in pvp.

**Comment by xolon** [comment]
its never stated in any change log, but look here #2835 about 10 sec icd on lnl

**Comment by Thefakemccoy** [comment]
Dont think he was talking about the ICD. He was talking about getiing a LnL proc from the trap from people who should be immune  to snare effect.

**Comment by Kejmil** [comment]
still broken, people still die due to not seeing aoe because traps ( ͡° ͜ʖ ͡°)

**Comment by Kejmil** [comment]
after next month i can confirm that it is still a problem

**Comment by Wolffenstein** [comment]
Fixed in rev 4807.
