### ISSUE TITLE
[EN][Quest][ZulDrak]That's What Friends Are For

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#4873]
Burr and Crusader Dargath are not intractable at all and Gerk can be clicked to talk to but nothing happen.

YouTube:
https://www.youtube.com/watch?v=Wn0HOE3dSFo
Wowhead:
http://www.wowhead.com/quest=12903/thats-what-friends-are-for

**Comment by ffighter29** [comment]
Confirmed...quest is not working

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/3474
