### ISSUE TITLE
[EN][NPC]Dark Ranger Marrah

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#4874]
She is supposed to be spawning on the first stairs in the instance Utgarde Keep and give out 2 quests for the instance:

[71D] Ingvar Must Die!
[71D] Disarmament 

Currently she is not spawning so the 2 quests are unobtainable

Wowhead:
http://www.wowhead.com/npc=24137/dark-ranger-marrah

**Comment by Crusaderz** [comment]
Duplicate: #4357

**Comment by aje** [comment]
close since duplicate
