### ISSUE TITLE
[EN] [NPC] Hazzali Cocoon

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#4876]
http://www.wowhead.com/npc=39081/hazzali-cocoon - npc link
Problem: cocon have 2255 HP, instead of ~179 HP.

https://cata-twinhead.twinstar.cz/?npc=39081 - another link Health: 184

![wowscrnshot_110915_190908](https://cloud.githubusercontent.com/assets/15231821/11040522/67b1180a-8715-11e5-887e-4ead96a129b4.jpg)

**Comment by Bildo** [comment]
fixed by Dimbaheca
