### ISSUE TITLE
[EN][QUEST] Gilneas city bug...

### ISSUE THREAD

**Issue by wojsyrek** [Atlantiss/BugTracker#4877]
[The Hunt For Sylvanas] 
Hello i got an problem with this quest bug. When i started this quest whole starting worgen map was empty. There was no npc anywhere. I abadoned this quest and nothing happend. Now i stuck in worgen start location and i cant do anything, just walk... Please help me ;c

**Comment by BAndysc** [comment]
Firstly, send a ticket to GM
