### ISSUE TITLE
[EN] [NPC] Stable Masters

### ISSUE THREAD

**Issue by Tierek** [Atlantiss/BugTracker#4878]
I have noticed at least three stable masters that do not work properly (Dalaran, K3, and Everlook). 

Instead of giving the single option of "*I'd like to stable my pet here," which opens the stable panel, these NPCs say the following: 
"Greetings, hunter. I can assist you in recovering lost companions; 
*I'm looking for a lost companion.
*I'd like to heal and revive my battle pets." 

Neither of these options open the stable window, so they are effectively broken. 
I do not know of any other broken ones beyond those three, but I wouldn't doubt there are more exhibiting the same bug.

**Comment by Thefakemccoy** [comment]
Might want to link the actual NPCs from either openwow or wow head.

**Comment by Tierek** [comment]
There is only one per city, but I'll do that for convenience: 

http://www.wowhead.com/npc=28690/tassia-whisperglen <- Dalaran
http://www.wowhead.com/npc=11119/azzleby <-- Everlook
http://www.wowhead.com/npc=29906/heksi  <- K3 

As I said, I haven't extensively gone all over the world to see who works and who doesn't, but these are three that exhibit the same issue.

**Comment by avalancze23** [comment]
http://www.wowhead.com/npc=10056/alassin<- Darnassus

**Comment by Luna-maria** [comment]
http://www.wowhead.com/npc=10085/jaelysia Lor'Danel

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6883-48785300-stable-master-issues/

**Comment by Luna-maria** [comment]
omg.. why hasn't this been run yet

http://www.wowhead.com/npc=27010/celidh-aletracker also bugged, can't stable my pet
