### ISSUE TITLE
[EN][Quest]Attunement to Dalaran

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#4880]
In the quest "Attunement to Dalaran" (http://www.wowhead.com/quest=12173/attunement-to-dalaran#comments), the player needs to travel to a pit beneath a surge needle in Dragonblight and use a ley line attunement crystal (http://www.wowhead.com/item=37006/ley-line-attunement-crystal). The crystal can be successfully used at the location, but its use does not complete the quest as it should, making the quest uncompletable.

**Comment by Bildo** [comment]
fixed
