### ISSUE TITLE
[EN][Warrior][Core] Avoidance excess is not turned into critical block.

### ISSUE THREAD

**Issue by gumby123** [Atlantiss/BugTracker#4881]
When your avoidance goes above avoidance cap, e.g. when you use Shield Block, all excess avoidance should be transferred into critical block.

This bug makes protection warriors absolutely useless on Atlantiss. Whole protection mastery stops making any sense, whole itemization for protection warriors is turned upside down due to this bug. 

It's a core mechanic bug that has existed since forever. Fix it.
![image](https://cloud.githubusercontent.com/assets/15706917/11065023/3c4ce87c-87c1-11e5-8177-ae146b12f7ac.png)

Although the information is mentioned in the Shield Block tooltip, it's a global core mechanic, not strictly related or caused by this spell. The situation, when you have excess avoidance, happens usually when you're wearing some basic tanking gear and activate Shield Block.

http://cata.openwow.com/spell=2565

**Comment by Jenovas** [comment]
Fixed in rev 4661
