### ISSUE TITLE
[EN][Spell][Warrior] Devastate, no bonus damage per SA application.

### ISSUE THREAD

**Issue by gumby123** [Atlantiss/BugTracker#4882]
Devastate should deal damage equal to 109% of weapon damage plus "X" damage for each application of Sunder Armor.
It doesn't increase damage for each application of sunder armor the damage is the same. 

I have tested it on player targets, dungeon boss and even on creeps that don't have armor but still no damage increase from sunder armor application
The 109% of weapon damage increases only by a very small amount because of the sunder armor that reduces targets armor but does not increase the damage for each application.
Sunder armor works fine that is for sure but the X damage for each application doesn't.

http://cata.openwow.com/spell=20243
http://cata.openwow.com/spell=7386

**Comment by Quban** [comment]
i ve tested it, and there is other bug - devastate hits too much :dancer: 
melee dmg = 1555
1 stack = 4966
2 stack = 5024
3 stack = 5082
when it should hit for about 2633, 3572, 4511
so that means it hits like there would always be 3 stacks

**Comment by Ervzz** [comment]
This needs to be fixed. Quban it's not hitting like its always 3 stacks. Its using an entire formula altogether where stacks are rather insignificant.

Based off the tests I just did for the last 2 hours its doing something like this:

125% weapon damage + Attack power + 55(sunderstacks)

Thats not a typo, its only adding around 50 to 60 for each stack. So currently its hits higher than it should when there's no stacks, or one stack, but beyond that its broken.

The formula should be something like this(?):

109% weapon damage + 854(sunderstacks)

Link from archived cata wowhead:

https://web.archive.org/web/20120415064327/http://www.wowhead.com/spell=20243

Note the spell details.

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
