### ISSUE TITLE
[EN][Talent][Warrior] Hold the Line doesn't improve critical block chance.

### ISSUE THREAD

**Issue by gumby123** [Atlantiss/BugTracker#4883]
This talent does increase your MELEE CRIT chance, but seems to not increase your CRITICAL BLOCK chance as it should.
Talent Hold the Line 1/2 and 2/2 either doesn't improve critical block chance by 5/10% or the information in character panel is wrong.

http://cata.openwow.com/spell=84621
http://cata.openwow.com/spell=84604

**Comment by Quban** [comment]
> the information in character panel is wrong.
