### ISSUE TITLE
[en][shaman][hunter] hex vs. hunter's mark/other

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4885]
## What's wrong:
If a hunter it's Hex 'ed he can still cast Hunter's Mark
and probably Call Pet abilities and disengage aswell.
## similar topics:
https://github.com/Atlantiss/BugTracker/issues/4884

**Comment by aneq** [comment]
@Aviannaqt 
raczej fixed, do zamknięcia
