### ISSUE TITLE
[en][shaman] shamanistic rage vs. trap

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4886]
## What's wrong:
Shamanistic Rage it's usable in Freezing Trap
## Proof you shouldn't:
http://www.wowwiki.com/Shamanistic_Rage
"Wrath-Logo-Small Patch 3.2.2 (2009-09-22): Thunderstorm and Shamanistic Rage can no longer be used while Frozen, Cycloned, Sapped, or Incapacitated."

**Comment by blinkmaster** [comment]
wooo so actually they cant get out of RoF also. pretty huge! :) :+1:

**Comment by deadlycalm** [comment]
shamans are bugging ring of frost freeze and trap since forever so pls fix somethig

**Comment by Wolffenstein** [comment]
Fixed in rev 4684.
