### ISSUE TITLE
[ENG][PL][Quest][Dragonblight] Planning for the Future

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#4889]
http://www.wowhead.com/quest=11960/planning-for-the-future
We can't collect http://www.wowhead.com/npc=26200/snowfall-glade-pup so we lose 500 reputation for Kalu'ak

Nie możemy zebrać(link powyżej) więc tracimy 500 repy dla Kalu'ak

**Comment by Navedonar** [comment]
już działa
