### ISSUE TITLE
Steamweedle Cartel reputation

### ISSUE THREAD

**Issue by gurin** [Atlantiss/BugTracker#4890]
For example http://www.wowhead.com/npc=3383/southsea-cutthroat
    3 reputation with Booty Bay
    3 reputation with Gadgetzan
    5 reputation with Ratchet (stops at Revered)
    3 reputation with Everlook

This mobs should grant 5 rep with Ratchet up to Revered and 3 spillover rep with the other towns all the way through Exalted. But they stop giving any rep after Revered with Ratchet. Same with other factions mobs. Looks like it's reputation implementing bug since all of this mobs bugged in the same way.

http://wowwiki.wikia.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel

**Comment by Bildo** [comment]
bt rules
