### ISSUE TITLE
[EN][Rouge][Talent] Deadly Momentum not working in Dungeons

### ISSUE THREAD

**Issue by l337g0g0** [Atlantiss/BugTracker#4892]
The refresh of slice and dice and recuperate do not refresh when mobs were dying in Gnomeregan Dungeon today... :(

**Comment by Kejmil** [comment]
you need to score killing blow and that is harder with other people in party :P

**Comment by l337g0g0** [comment]
It doesn't state that on the tool tip for the ability.
But you do have to have the killing blow?

**Comment by Kejmil** [comment]
http://cata.openwow.com/spell=79122

**Comment by l337g0g0** [comment]
Yea i'm just being hyper technical...
"After killing an opponent that yields experience or honor,"
If it's killed by me or my group it's still killed.

But i guess if you take it super literal then so be it.

Thank you good sir...
