### ISSUE TITLE
[en][shaman] windfury icd / procchance / etc

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4895]
## How it should be:
* Windfury weapon should have an Internal Cooldown of 3 seconds. it should have this internal cooldown on BOTH WEAPONS, so BOTH WEAPONS CANNOT PROC windfury for 3s.
* Windfury weapon should have a procchance of 20%. It seems to proc rather often now, but maybe this is only caused by the missing icd.
* Windfury should NOT proc in ghost wolf

## What's wrong:
* On our server Windfury weapon procced after 2 seconds from previous one, I guess the icd is set wrong or it's not set at all.
* Windfury procs in ghost wolf

## Proof on our server:
here is the proof that it took 2 sec with the wow timer-> https://www.youtube.com/watch?v=x5nq26oyNqw from 0:20
and I started timmer cca. 0.3 sec after I got windfury proc.

## Proof retail:
http://web.archive.org/web/20120712235459/http://www.wowhead.com/spell=8232#comments
http://www.wowhead.com/forums&topic=124489/windfury-icd
"The three second ICD is a global ICD for WF procs...if WF procs, it can not proc again on you for 3 seconds regardless of weapon."

"After WF procs it cannot proc again on either hand for 3 seconds. No 1H weapon in the entire game can proc WF twice in a row. This means that WF will proc less than the 20% promised on its tooltip."

"Can't proc in Ghost Wolf (yes, im stupid enough to test that)"

## Proof that icd wasn't changed since tbc:

http://us.battle.net/wow/en/forum/topic/1869559907
" Given that Windfury has gone untouched for 4+ years, it's actually a boon to see it changed.

3) Everything I hate about Windfury is still there. The attack bonus is still flat, and most importantly the ICD is still there. If you were really considering changing Windfury, I'm curious as to why you just wouldn't remove the ICD first. "

**Comment by Achiver** [comment]
Enh shaman nerf pls

**Comment by blinkmaster** [comment]
hehehheehhe and enh shamans claiming everything works fine with their dmg for so long time :))

**Comment by anxanas** [comment]
Where is the proof of it being bugged on Atlantiss? The only thing anyone got out of this post was getting to know the ICD of windfury. Dont claim anything is bugged without proper proof. And u feeling that windfury procced 2 secs after one already procced, can be due to latency or you just counting wrong. The likelyhood of it proccing at 3 secs after the first windfury is pretty high, you most likely misjudged the time.

**Comment by anxanas** [comment]
And i tried to test it with my enhancement shaman, by putting windfury on both weapons and melleing a dummy and quickly stopping attack, i never got 2 windfury procs, maybe that means the icd is at 1 sec or 2 sec but it surely has a icd, and if you cant prove that it has a lower icd than 3 secs then there is no need to fix it.

**Comment by Bastion** [comment]
link from tbc

**Comment by anxanas** [comment]
Lol that's right, your first link is from wotlk and your second is from tbc. Though the information about windfury icd being 3 secs applys to patch 4.3.4

**Comment by razgal** [comment]
here is the proof that it took 2 sec with the wow timer-> https://www.youtube.com/watch?v=x5nq26oyNqw from 0:20
and I started timmer cca. 0.3 sec after I got windfury proc.

It can be easily tested by a dev with Haste aura, because the time between auto-attack takes literaly 1 second and the difference between 2 or 3 sec can't be tested by a player with normal gear.


they didn't changed the mechanic of windfury since tbc. 
here is a proof: 
http://us.battle.net/wow/en/forum/topic/1869559907
" Given that Windfury has gone untouched for 4+ years, it's actually a boon to see it changed.

3) Everything I hate about Windfury is still there. The attack bonus is still flat, and most importantly the ICD is still there. If you were really considering changing Windfury, I'm curious as to why you just wouldn't remove the ICD first. "

**Comment by Bastion** [comment]
u have daggers idiot and don't record at 5fps

**Comment by razgal** [comment]
I updated everything in the first post so it will be easier to read by devs.

@Bastion @Anaek
Stop joining discussions if you are not eligible to back-up your arguments or have no idea about mechanics.

It can be easily tested by a dev with Haste aura, the time between auto-attack takes literaly 1 second and the difference between 2 or 3 sec can't be tested fully by a player with normal gear.

**Comment by Bastion** [comment]
this is bullshit

**Comment by anxanas** [comment]
Again your video proves nothing, you are a human being and cant click that timer exactly the same time as windfury procs, not to mention latency. Regardless of your timer for me it looks like there goes 3 secs. And i am probably not the only one who sees this, but according to the youtube video where ur timer says its 2 secs, its actually 3 secs just pause the video at 0:20 and 0:23, there u can clearly see that there goes 3 seconds from the first windfury proc to the next.

**Comment by Jenovas** [comment]
Closing....

**Comment by razgal** [comment]
don't close ticket without reading everything.

windfury should not proc in ghost wolf , still, and I still think the ICD it's 2 seconds but whatever.

**Comment by Jenovas** [comment]
Razgal N/C. Please start checking what you report cause you're wasting my time.

**Comment by anxanas** [comment]
So i assume this wont be "fixed" since there is no real proof? =)))

**Comment by Jenovas** [comment]
This wont be fixed beacuse the cooldown is 3 second. The only bug is that it can proc in wolf form. Please create aissue about windfury procing in wolf form.
