### ISSUE TITLE
[EN][Quest][Argent Tournament] Valiant of Ironforge

### ISSUE THREAD

**Issue by drmetud** [Atlantiss/BugTracker#4899]
The [Valiant of Ironforge] quest,does not seem to unlock after you already have completed the  [Exalted Champion of Stormwind] even if your reputation is exalted with Ironforge.
I have been told ingame by people who managed to complete the [Champion of the Alliance] achievement that you have to ask a Game Master for this quest (and in fact other Valiant of XY quests) to be unlocked. I did open a ticket some days ago but got no response so far,so I have been instructed by the friendly community of Atlantiss to open an issue on the Bug Tracker.

**Comment by drmetud** [comment]
Ths issue has been solved thanks to GM Myivo

**Comment by TheCroak** [comment]
Same problem as Horde, can't open the other set of dailies.

**Comment by Piklo** [comment]
should be fixed in [rev5794](https://atlantiss.eu/changelog#rev5794)
