### ISSUE TITLE
[en][shaman] lava lash vs. flametongue weapon

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4900]
## What's wrong:
Lava lash does more damage than it SHOULD when its influenced by Flametongue Weapon

## Proof:
Tested on target with 0 resil, 0 gear, no talents buffs etrc
the weapon I used and it's damage: http://tinypic.com/r/34t33b9/9
Lava Lash normal damage,without any buffs/talent increase/etc -> http://tinypic.com/r/1zlzxc5/9
**MIN.WEAP DMG**: 91
**MAX.WEAP DMG**: 104

Lava Lash damage with Flametongue Weapon -> http://tinypic.com/r/el75p4/9
**MIN.WEAP DMG**: 133
**MAX.WEAP DMG**: 152
## How it should be:
**MIN.WEAP DMG**: 91 * 1.4 = 127
**MAX.WEAP DMG**: 104 * 1.4 = 145

**Comment by Bastion** [comment]
what's wrong with u

daggers?

**Comment by razgal** [comment]
you have a phobya for daggers?

**Comment by Bastion** [comment]
u have lava burst in enh

**Comment by aneq** [comment]
flametongue increases your magical damage, not spell damage. lava lash is fire damage which is magical damage. I need my chemotherapy after seeing this thread

**Comment by razgal** [comment]
appearently I piss off a lot of braindeads with my reports.

stop defending your class and stop entering in my tickets.

**Comment by aneq** [comment]
I'm not even playing enhancement, your tickets are just bad
Go do some real tests with simcraft and then compare with atlantiss

**Comment by razgal** [comment]
and for Pokemon consumers, similar topic here
https://github.com/Atlantiss/BugTracker/issues/4904

**Comment by Jenovas** [comment]
If you add the 5% DMG bonus you get from Flametongue Weapon the DMG is ok.
Closing.
