### ISSUE TITLE
[EN][PRIEST][TALENT] MASOCHISM

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#4901]
Masochism should work with power word shield up but it does not.
http://cata.openwow.com/spell=88995 mas
http://cata.openwow.com/item=42408 pws
proof: https://www.youtube.com/watch?v=qmV-S0yazFY   6:25 
kinda important issue for sp
update. also doesnt work on target with absorb

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump makes sp unplayable

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
BUMP

**Comment by debtheone** [comment]
Jenovas self-assigned this on 15 Dec 2015

**Comment by Jenovas** [comment]
Jenovas removed their assignment just now

**Comment by debtheone** [comment]
halo nie tak to się miało zakonczyć :D

**Comment by debtheone** [comment]
Bump pretty huge for SP

**Comment by kadi2** [comment]
bump

**Comment by kadi2** [comment]
Bump, you just go oom after 2 minutes of arena.

**Comment by kadi2** [comment]
related to https://github.com/Atlantiss/BugTracker/issues/7529

**Comment by lamaATS** [comment]
Fixed in rev. 5207
