### ISSUE TITLE
[en][shaman] Unleash Elements vs. Windfury weapon.

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4902]
## What's wrong:
If you use Unleash Elements from distance while having Windfury Weapon it procs the three attacks.
## How it should be:
The attacks should be procced only from auto-attacks.
## Proof:
Unleash Elements is a spell, not a weapon swing.

http://us.battle.net/wow/en/forum/topic/2522435353
"Unleash Elements is now in the Nature school"

**Comment by Bastion** [comment]
GO BACK TO MOLTEN

**Comment by deadlycalm** [comment]
yesterday there was bg when 4 enh shamanas was on the top of kills/damage and you prettend everything works fine

**Comment by anxanas** [comment]
Again no proof whatsoever, it is true that windfury procs from unleash element(windfury) on this server, but you provide absolutely no proof, that it was'nt like that on retail. I could'nt find any source that unleash elements should proc windfury, but i found a source that says that it procs weapon enchants, which in my book is pretty much the same. 

http://www.wowhead.com/spell=73680/unleash-elements#comments
"The Unleash Wind portion of this spell can proc Avalanche (and thus I would assume any other on-melee-hit proc enchant), and will proc Flurry if it crits. However, it seems unable to proc Maelstrom Weapon." Cloudburst

And what is wrong with your Enhancement Shaman holocaust? You find bugs that does'nt exist(or atleast can't be proven)

**Comment by razgal** [comment]
not gonna explain myself anymore to you or to "dagger" guy, you 2 are from other planet. 
stop entering my tickets.

**Comment by anxanas** [comment]
I admit that "dagger" guy isnt provided any usefull information to your reports but i am just proving you wrong, so we dont bug something that is works perfectly.

**Comment by Lanrutcon** [comment]
More proofs:
http://us.battle.net/wow/en/forum/topic/6552025848
http://bug.omfg.gg/issues/15252

**Comment by anxanas** [comment]
After doing a bit of "research"  by watching a video of an enhancement shaman doing rhc i gotta admit that it seems like windfury shouldnt proc from unleash elements, not once in the video does it proc windfury when used from range. The video is https://www.youtube.com/watch?v=NM_MJZ8a84M

**Comment by deadlycalm** [comment]
please work on this - whole server complains about enh damage which is totally ridicolous

**Comment by deadlycalm** [comment]
any response?

**Comment by Aviannaqt** [comment]
#4638
