### ISSUE TITLE
[en][shaman] mana tide totem

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4903]
## what's wrong:
The totem uses spirit procs from trinkets and enchant procs, such as Fall of Mortality and Tear of Blood, and Heartsong, leading to bigger regen than it actually should.

**Comment by mitim1** [comment]
Links?

**Comment by razgal** [comment]
check the tooltip, it says on it.

**Comment by Jenovas** [comment]
How are you testing this? Did tests just now. All auras that last 20sec or less and give 1000 or more spirit do not benefit from mana tide totem.

Closing.
