### ISSUE TITLE
[EN][Hunter]Pet leveling

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#4906]
Cataclysm changed pet leveling in patch 4.0.1 and 4.1.0

Currently I believe hunter pet leveling is still on WotLK settings, which levels it up to max 5 levels below the current Hunter's level. Currently whenever you tame (or call) a pet that is much lower level than the hunter, it's 5 levels lower than the hunter. (at level 44 i called back my bear which I haven't used since Dun Morogh, and it leveled up to level 39). For patch 4.0.1 this particular pet and my current level should be at least level 41 

In patch 4.0.1: "Numerous changes. Many pet abilities have been replaced or altered. Hunters now start with pets at level 1. Whenever a hunter is more than 3 levels above a pet, the pet levels to within 3 levels of the hunter."

They updated it again in patch 4.1.0 

In patch 4.1.0: "Pets will now level with hunters in the same way warlock pets currently do. Also, summoned pets now start with 100 focus, up from 0."   (the focus bit is working fine)

So whichever patch we're supposed to be on currently on Atlantiss, be it 4.0.1 or 4.1.0 or possibly soon 4.2.0 (though technically with current spells available to classes we're o 4.3.4) the settings for pet leveling are off. Pets should max. be 3 levels behind on the hunter, but more appropriately level up as the hunter does.

http://wow.gamepedia.com/Pet_%28Hunter%29 (scroll down to patches and hotfixes) 

rev. as of writing this: 4650

(apologies if this has already been posted but I couldn't find anything on it so)

**Comment by Kejmil** [comment]
i think it is problem only with old pets - when i log on my hunter after a year break i had few pet to lvl still, but new one was always caught at 85lvl

**Comment by Wolffenstein** [comment]
I fixed pet levels long ago, try taming a new one and he should be the same level as you are.

**Comment by Luna-maria** [comment]
Makes me wonder how long ago it was because I haven't been playing my hunter for more than 2 months max :p 

anyways, went and tamed a new pet and it did indeed jump to the level my hunter is at, so this post can be closed, sorry :)
