### ISSUE TITLE
[ENG][NPC][Nagrand]Missing NPC - Challe

### ISSUE THREAD

**Issue by Corson** [Atlantiss/BugTracker#4907]
Missing NPC http://www.wowhead.com/npc=23101/challe
And her kids (don't remember the names).
Not the key NPC, just random one.

**Comment by Bildo** [comment]
fixed by Dimbaheca

**Comment by aje** [comment]
(still bugged)
fix http://community.atlantiss.eu/index.php?/topic/6637-4-missing-npc/
