### ISSUE TITLE
[en][shaman] mana tide totem x2

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4909]
> How are you testing this? Did tests just now. All auras that last 20sec or less and give 1000 or more spirit do not benefit from mana tide totem. Closing

without any gear:
1. Cast Mana Tide Totem, check your spirit before and after.
for me : I have 158 base spirit, with Mana Tide Totem 474
2. Enchant your weapon with Heartsong(http://cata.openwow.com/item=52761)
Wait for Heartsong to pop, after it pops check your spirit again, I have 358 spirit with Heartsong.
3. After your Heartsong pops, cast Mana Tide Totem. Your spirit will be:  1074
4. Now cancel fast Heartsong, you'll have 874 spirit, instead of 474.

That's the problem, your Mana Tide Totem should give you 200% increase spirit of your Base spirit, not of your spirit that's present with procs from trinkets and enchants, you understand now??

**Comment by razgal** [comment]
if you say that every aura that gives 1000+ spirit working correctly then problem is with every aura that has <1000 spirit, like Heartsong

**Comment by Jenovas** [comment]
"Mana Tide totem does take Heartsong into account if it is active when you cast the spell.

I can't tell you why, but I can think of a few reasons as to why. The fact that Heartsong is up in excess of 65% of the time is one possible reason."

Mana Tide Totem should work on ALL buffs that give little amounts of spirit + have a high uptime. It should not work on buffs that are short and give ALOT of spirit.

Please start searching before you create more bug reports.

Closing.
