### ISSUE TITLE
[en][DK] death pact vs. pet in cc

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4913]
## What's wrong:
Right now if your pet is in CC(clone,ring,stun,etc) and you use Death pact you still get healed.

## How it should be:
You shouldn't be able to use Death Pact at all while your pet is CCed, when you try to use Death Pact a message like "You can't use that right now" should pop up

**Comment by Jenovas** [comment]
Fixed in rev 4658
