### ISSUE TITLE
[EN] [Spell] [Shaman] Lava Lash not always benefits from mastery

### ISSUE THREAD

**Issue by Jenovas** [Atlantiss/BugTracker#4916]
Shaman Ench Mastery:
77223 Enhanced Elements - with basic 8 points of mastery - Increases all Fire, Frost, and Nature damage done by 20%.  

Weapon DMG from character:
MIN DMG - 35
MAX DMG - 41

Lava Lash - 60103 -  You charge your off-hand weapon with lava, instantly dealing 260% of that weapon's damage to an enemy target.  Damage is increased by 40% if your off-hand weapon is enchanted with Flametongue.

Lava Lash DMG without glyph, without searing flames, without flametongue should be:
MIN DMG - 35 x 2.6 x 1.2 = 109
MAX DMG 41 x 2.6 x 1.2 = 128

DMG ON ATLANTISS:
MIN DMG: 91
MAX DMG: 104

This shows that the base DMG does not get the 20% bonus DMG from mastery, BUT this bug goes away if we have Glyph Of Lava Lash on OR the talent Improved Lava Lash and any stacks on or target.

So for some weird reason this bug only appears for shamans without Glyph of Lava Lash and without stacks of searing flame on their target.

**Comment by lamaATS** [comment]
Fixed in rev. 4910 (missing close)
