### ISSUE TITLE
[en][Mage][general bug possibly] petattack vs. combat

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4920]
## What's wrong:

If you /petattack an enemy player, it puts you in combat.
## How it should be:

If you /petattack an enemy player, you should enter in combat after your pet reaches and succesfully attacks that target.

Currently this is bugged for Mages, I don't know for other classes,but more than sure is same for Udks,Hunters,Enha Shamans,Locks,Boomkins with trents probably,etc

**Comment by razgal** [comment]
this is can be very gamebreaking in pvp, because mages can't get sapped against rogues in bgs/arena  if they know to abuse this.

**Comment by Kejmil** [comment]
hunters confirmed, was killed by game when i was logging out because of this :D

**Comment by lamaATS** [comment]
Fixed in rev. 5533
