### ISSUE TITLE
[EN][Huntard][Pet][Spell] Monstrous Bite and other debuffs for healing reduction

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#4927]
Old BT issue about it: https://github.com/Atlantiss/BugTracker/issues/3039
Author even deleted his github account to hide it after he received ban for mentioned arena :D

http://www.wowhead.com/spell=54680/monstrous-bite#changelog

Because of this "added in 4.1" thing, this debuff was not set to group with other healing reductions in 4.0.6 (when zori fixed all this stuff) and can stack with any other to provide 50% heal reduction, which shoudn't ever happened.

While not really changing much in pve area, this can be a disaster in pvp environment.

**Comment by Jenovas** [comment]
This spell is added to the group but the group doesnt work.
Can you please check if this is a pet problem? Maybe all pet debuffs stack, not only this one.

Can you please check if:
Corrosive Spit (Pet)
Tear Armor (Pet)
Stacks with any other armor reduction debuff.

Can you please check if:
Ravage (Pet)
Acid Spit (Pet)
Stacks with any other increase dmg taken debuff.

**Comment by Kejmil** [comment]
i don't have so much pets for now and time to test it through, but during checking if this healing reduction works i saw something strange - this debuff from pet was DRing with itself and after 3 application target was immune to it, i heard that some other pet debuffs have this DR problem too (but can't give anything more than my word for now), maybe that is cause of the problem?

**Comment by Jenovas** [comment]
Fixed in rev 4714
