### ISSUE TITLE
[EN][NPC] Corki, Corki and Corki

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#493]
This **Corki** (http://www.wowhead.com/npc=18369) is placed where this **Corki** (http://www.wowhead.com/npc=18445) should be, and vice versa.

This Corki (http://www.wowhead.com/npc=20812) is the 3rd Corki, but I think his position is right.

Just check all the IDs, and make sure that every **Corki** is where he should be.

**Comment by Tarvo27** [comment]
During the Quest HELP! you have to go to another Corki to get the quest and even after getting the key, there seems to be no way of completing the quest since you can't open the cages the quest giving Corki is in and the one who should give the quest isn't even in a cage.

**Comment by supreemetac** [comment]
The quest were Corki needs to be freed from the cage in the ogre cave is bugged. Corki is standing at the end of the cave , but there is no cage around him.
