### ISSUE TITLE
[PL] [Dungeon-Cata] Deadmines

### ISSUE THREAD

**Issue by tralala21** [Atlantiss/BugTracker#4931]
Witam,
ostatni boss (faza) w Deadmines Heroic nie dziala.
Mianowicie po zabiciu bossa "Captain" Cookie, Przychodzi kolej na Vanessa VanCleef.
Pojawia sie przerywnik, po czym zostajemy wrzuceni do wielkiego kufla (zbiornika) z lawa, gdzie musimy otkrecic (kliknac) na zawory by sie wydostac i móc walczyc z bossem Vanessa VanCleef.
Jednak u nas na serwerze, zostajemy szybko wrzuceni do kufla i na tym koniec, nie mozna sie poruszac ani nic zrobic.

filmik jak powinno dzialac 0:19 sek

https://www.youtube.com/watch?v=tkNxQ176Bhs

Link do bossa:

http://www.wowhead.com/npc=49541/vanessa-vancleef

Proszę o naprawę, gdyz obecnie jest niemozliw zrobienie calego Deadmines. Dziękuję.

**Comment by Achiver** [comment]
Pojawianie się w środku tego czegoś, po użyciu zaworów wyrzuca was na zewnątrz.  Może miałeś zbyt przybliżona kamerę i nie widziałeś zaworów?
