### ISSUE TITLE
[EN][Hunter] Cunning Pet - Wolverine Bite

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#4932]
link - http://wow.gamepedia.com/Wolverine_Bite

Making a new post cuz it seems this importent bug has bee forgotten. It been 1 year since the last report on this.

This is an special attack ability in cunning pet talent trees. At the moment the ability doesnt scale with anything and just does the damage from the tooltip - 600~ DMG. Also it doesnt proc after crit but rather can go off cd.

**Comment by Wolffenstein** [comment]
And for how long should the skill be available to use?

**Comment by meowmewo** [comment]
The skill has a 10 sec cd. If ur pet Crits..the skill gets available untill used. When used ..the 10 seconds cd applies, in these 10 seconds u cant use it again even if ur pet crits.

**Comment by meowmewo** [comment]
(1 + ((RAP * 0.40) * 0.10)), this is the foruma , so it seems the damage the skill does is right so the major bug is that it doesnt have 10 sec cd and since it has a GCD it takes it over from Bite, Claw etc...and you cant really use it. So just fix the Cooldown and this are fine.

**Comment by meowmewo** [comment]
Here is a video, u can see how the skill works here. https://youtu.be/p9IYdfcThAo?t=879
