### ISSUE TITLE
[EN][Quest][Northrend] Out of Body Experience

### ISSUE THREAD

**Issue by virushm** [Atlantiss/BugTracker#4933]
http://www.wowhead.com/quest=12327/out-of-body-experience
quest not avaible for worgen

**Comment by holdias** [comment]
not available at all

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15190-quest-out-of-body-experience/

**Comment by Jenovas** [comment]
Fix in 5537
