### ISSUE TITLE
[PL][Item] Roadway Plans

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#4938]
http://www.wowhead.com/item=49776/roadway-plans
Powinny mieć 72% sznasy na drop ja zabilem ich ~20 i nie padł
http://www.wowhead.com/npc=37216/honors-stand-officer

**Comment by Navedonar** [comment]
powinno być 100%

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8142-4938item-roadway-plans/

**Comment by therealmikz** [comment]
+1
wciąż nie dropi

**Comment by RastaTinu** [comment]
Dalej nie dropi
