### ISSUE TITLE
[EN][Arathi Highlands][Object] Wanted Board

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#4939]
http://www.wowhead.com/object=2713/wanted-board
This board is missing and not available. It starts 2 quests in Arathi Highlands required for eastern kingdoms quest progression.
1. Wanted! Marez Cowl http://www.wowhead.com/quest=26024/wanted-marez-cowl
2. Wanted! Otto and Falconcrest http://www.wowhead.com/quest=26079/wanted-otto-and-falconcrest

**Comment by Aival94** [comment]
I did both quest before some days but i think they were just given by the npc which complete them instead so the only bug is probably the missing object and not the quests or quest progress.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12550-4939arathi-highlandsobject-wanted-board/?p=60018
