### ISSUE TITLE
[EN][NPC] Gezzarak the Huntress

### ISSUE THREAD

**Issue by Zhabrina** [Atlantiss/BugTracker#4940]
http://www.wowhead.com/npc=23163/gezzarak-the-huntress#comments

Gezzarak the Huntress is supposed to be tamable as of patch 4.0.3.

![wowscrnshot_111515_190421](https://cloud.githubusercontent.com/assets/15862677/11172039/889c1126-8bcc-11e5-8893-cce95e3e85d5.jpg)

Beast Lore states she is not tamable.

![wowscrnshot_111515_190438](https://cloud.githubusercontent.com/assets/15862677/11172042/92a359a4-8bcc-11e5-8f63-342d73086d1d.jpg)

Combat log shows the tame failed because of 'invalid target'.

Rev. 4657

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6652-npc-23163-should-be-tameable/
