### ISSUE TITLE
[en][dk[ blood tap

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4942]
## What's wrong:
Blood tap http://cata.openwow.com/spell=45529 , can convert both blood runes into death runes
## How to reproduce:
You need to have your first blood rune in cd, then when you use blood tap it will convert both blood runes into death runes, instantly.

**Comment by Lenox07** [comment]
Its not a bug.
https://youtu.be/u3mXQtOesMI?t=8m40s
