### ISSUE TITLE
[EN][RAID][CATA] ODS HC

### ISSUE THREAD

**Issue by Dorsinor** [Atlantiss/BugTracker#4944]
I know it already is in the bugtracker, but since it's still bugged I figured that I should mention the problem again. When you kill ODS while a new activation is in progress, the boss resets his HP. Also, yesterday we found out that this happens when Toxitron is using Poison Protocol as well. It happened to my guild on our first ODS HC kill. It might not be a problem for guilds that kill ODS HC weekly, but as a guild that just started to progress through HC raids, killing ODS is a big millstone that we lost due to that bug. Can you work on fixing it please? Thanks.

**Comment by Aviannaqt** [comment]
Fixed in rev. 4664
