### ISSUE TITLE
[en][mage] Pyroblast! crit vs.Crit

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4946]
after analyzing the topic from here https://github.com/Atlantiss/BugTracker/issues/4595 found another thing related to the Hot streak subject but I'll make a new topic since it's not directly related to the issue.
## What's wrong:
after you crit with Pyroblast! proc, and it's followed by another crit(example Fireball crit) you get another pyro proc.
## Proof you shouldn't:
http://www.mmo-champion.com/threads/780272-Hot-Streak-Procs
"Pyroblast! did not trigger if Pyroblast! critted followed by a Fireball crit."

**Comment by razgal** [comment]
also in the same topic says following:
"Pyroblast! did not trigger if Pyroblast! didn't crit followed by a Fireball crit."

on our server it procced Pyroblast. maybe these 2 issues should be first fixed before giving more attention to https://github.com/Atlantiss/BugTracker/issues/4595 hot streak imp hot streak complicated shit

**Comment by anxanas** [comment]
Hotstreak is able to proc even without two crits after eachother, it has a chance(depending on crit chance) to proc hotstreak even after one crittical hit, especially if you have very low crit chance or maybe you are right and it is bugged, only way to check is to test it.

**Comment by blinkmaster** [comment]
doesn't happen at all beside like 1/1000 or smth. so its a normal way of t3 HS working

**Comment by Jenovas** [comment]
So this is not a bug?

**Comment by blinkmaster** [comment]
its not a bug that u can get hot streak proc after fireball crit when u used hot streak proc already. i will illustrate it:
- fireball crit ( HS can proc )
- fireball crit ( HS WILL PROC )
HOTSTREAK PROC
- HOTSTREAK USAGE 
- Fireball CRIT - HS CAN PROC 
- fireball CRIT - HS WILL PROC

**Comment by Jenovas** [comment]
Can I close this?

**Comment by blinkmaster** [comment]
well i am unable to reproduce the bug to work it as stated at the beginning so for me it can be closed BUT i think the author should speak and decide by himself.

**Comment by razgal** [comment]
ook , developer asking randomguythatdefendshisclass if he can close it, just shows the lack of knowledge,motivation and will to fix things around.

http://www.mmo-champion.com/threads/772878-Pyroblast-not-proccing-Hot-Streak
"I played around with this briefly when another mage in my guild pointed out that HS Pyro crits weren't proccing HS if they were the second crit

This is completely ignoring the first HS talent which could possibly have been messing with me each time. :P"

i'll close this myself,I play mage as alt and I'll benefit from this bug,balancing pvp when you're not capable of making a decision for yourself and analyzing everything over others opinions.

**Comment by Jenovas** [comment]
Razgal not the lack of knowledge and motivation, I already checked 10 of your other bugs and all turned out not to be a bug, so I bet that this one also isnt a bug . I dont want to lose time because of you again, so I asked a different player is this a bug. Learn how to test and report bugs and stop attacking other players.
