### ISSUE TITLE
[EN][Item] Cloak of Coordination

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#4947]
Cloak of Coordination seems to be missing from Alliance Guild Vendors.

Wowhead Link: [Cloak Coordination](http://www.wowhead.com/item=65360/cloak-of-coordination)

**Comment by Thefakemccoy** [comment]
Does the guild have the achv for the cloak? 
Do you have the proper rep for the cloak?

**Comment by Aival94** [comment]
both yes:
![wowscrnshot_111615_225106](https://cloud.githubusercontent.com/assets/10282971/11215857/fa4bc2e6-8d50-11e5-918d-ea50799822bd.jpg)
![wowscrnshot_111615_225109](https://cloud.githubusercontent.com/assets/10282971/11215858/fa4f78dc-8d50-11e5-89ae-ff5f19b24444.jpg)
![wowscrnshot_111615_225111](https://cloud.githubusercontent.com/assets/10282971/11215859/fa551134-8d50-11e5-8354-5dccf6e443ab.jpg)
![wowscrnshot_111615_225115](https://cloud.githubusercontent.com/assets/10282971/11215860/fa5526b0-8d50-11e5-891b-32a1a74069c5.jpg)
![wowscrnshot_111715_173426](https://cloud.githubusercontent.com/assets/10282971/11216039/ddf462c8-8d51-11e5-9560-5900ef4f1a7f.jpg)
![wowscrnshot_111715_173444](https://cloud.githubusercontent.com/assets/10282971/11216040/ddfe775e-8d51-11e5-988a-588958dfdcf4.jpg)

**Comment by Navedonar** [comment]
.

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5827
