### ISSUE TITLE
[EN][Core][Warrior] Mastery to Block conversion is rounded down incorrectly.

### ISSUE THREAD

**Issue by gumby123** [Atlantiss/BugTracker#4948]
Mastery should be converted into % Block Chance with decimal precision and NO rounding-down, like this [RETAIL]:
![image](https://cloud.githubusercontent.com/assets/15706917/11196190/608391c4-8cb6-11e5-994f-e655c0db107f.png)

video source: https://www.youtube.com/watch?v=pXEPKURzXdQ#t=597

Currently, Mastery points are multiplied by 1,5% Block Chance and then ALWAYS ROUNDED DOWN, with no decimal places, like this [Atlantiss]:
![image](https://cloud.githubusercontent.com/assets/15706917/11196325/8edfb804-8cb6-11e5-9333-84d33d40f8fc.png)

So, a block chance that should be 55,89% becomes 55% on Atlantiss. This is wrong and needs fixing, like many other protection warrior bugs, the main one being :https://github.com/Atlantiss/BugTracker/issues/4881

**Comment by blinkmaster** [comment]
im kind of curious if this affects all masteries hm hm.
cant check myself atm, can some1 provide some info on that?

**Comment by Kejmil** [comment]
if not all, then most of them

**Comment by Jenovas** [comment]
Fixed in rev 4661
