### ISSUE TITLE
[EN][Spead the good word][Dragonblight]

### ISSUE THREAD

**Issue by Sinos26** [Atlantiss/BugTracker#4950]
quest not scripted at all , the machines won't appear when i take it 
![wowscrnshot_111715_163555](https://cloud.githubusercontent.com/assets/15890669/11214352/747c3a3a-8d49-11e5-8713-e0d2c6765f42.jpg)

**Comment by Quban** [comment]
dup https://github.com/Atlantiss/BugTracker/issues/2223
