### ISSUE TITLE
[en][dk] Gargoyle GCD cap

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4952]
## How it should be:
* Gargoyle cast time should stop at 1.5 sec cast time, it shouldn't go under that even if you have 1000% haste.

Gargoyle should do 16 hits if its casted at 1.5 GCD haste.
## Proof:
http://forums.askmrrobot.com/index.php?topic=3580.0
"You will encounter at least one or possibly two haste breakpoints in this tier. The first breakpoint, valued at ~1600 personal haste, will provide the Gargoyle an attack speed that exceeds its own global cooldown of 1.5 seconds. Effectively, any inherited haste beyond this point can have no effect for him: the Gargoyle is GCD locked."

http://us.battle.net/wow/en/forum/topic/3881708498
"If you have about 1650 haste rating or more Unholy frenzy will not benefit your gargoyle.
It will increase the gargoyles cast speed But will not increase the number of gargoyle strike a gargoyle can cast /gargoyle summon,because of the gargoyle's GCD.A gargoyle can only cast 16 GS / gargoyle summon atm in live.Even with heroism/BL,UHF other haste effects won't let it cast more than 16 GS /summon.It will start casting 17th GC and will stop casting and fly away.
We don't need to know this.Summoning gargoyle with UHF buff is totally fine.
But it is a fact.And knowing something is good.
Another thing is I don't know the exact haste rating cap to make the gargoyle use 16 GS/summon.But with 1550 ish haste rating its using 15 GC.And its benefiting from UHF."

**Comment by razgal** [comment]
also the base cast time of gargoyle is wrong, it should be 2 sec
my dk with no gear and only in Unholy presence,  Gargoyle Strike does 1.7 sec. 

proof:
http://www.mmo-champion.com/threads/697868-Gargoyal-and-Haste
"The base cast time is 2 secs "

**Comment by blinkmaster** [comment]
doesnt unholy pressence give 15% haste? 15% from 2secs is 1.7sec.

**Comment by razgal** [comment]
I guess you're right, but this means with gear 500 haste rating you reach the 1.5 cap .. which the guy in proofs said at  1600 is the cap

**Comment by Kejmil** [comment]
Unholy presense doesn't affect spell haste of DK, gargoyle cast should scale from this
For same reason unholy frenzy shoudn't affect gargoyle's casts.
also https://github.com/Atlantiss/BugTracker/issues/825

**Comment by aneq** [comment]
yep, 1600 haste should be the haste soft cap for unholy

**Comment by Jenovas** [comment]
Gargoyle should benefit from UH Presence. 1600 haste alone gives aroun 15% haste. UH gives 15% haste. To get the cast to around 1.5sec you need around 33% haste.

**Comment by Jenovas** [comment]
Fixed in rev 4715

**Comment by Kejmil** [comment]
if changelog description is accurate then it was fixed in wrong way - gargoyle cast can reach below 1,5sec but due to gcd it's just unable to cast more than one per this time

"If you have about 1650 haste rating or more Unholy frenzy will not benefit your gargoyle.
<b>It will increase the gargoyles cast speed But will not increase the number of gargoyle strike a gargoyle can cast</b>"
from first post

**Comment by Jenovas** [comment]
It's easier to implement it this way than add a Global Cooldown only to 1 pet.
