### ISSUE TITLE
[en][dk] ghoul base hp

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4954]
## What's wrong:
Ghoul inherits ~85% health of master (with Glyph of Raise Dead)
## How it should be:
Ghouls health should inherit around 70% of your health ( with Glyph of Raise Dead)
## On our server:
I have 87699 HP
My ghoul has 74795 (with Glyph of Raise Dead), that's around 85%
## Proof:
https://www.youtube.com/watch?v=vfV1h8nlHQ0
at 10:40 you can see well
dk has 155.200 HP
pet has 107.300 HP ( he has Glyph of Raise Dead), that's around 70% of masters health

now the problem is the base health not the Glyph. the base health should be decreased.

**Comment by klm670** [comment]
At lvl 66 my pet has 10.8k health why I have only 7.7k myself.

**Comment by Jenovas** [comment]
Fixed in rev 4667
