### ISSUE TITLE
[EN][Achievement] Pilgrim's Paunch

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#4956]
http://www.wowhead.com/achievement=3557/pilgrims-paunch

Doesn't work.

**Comment by mean931** [comment]
can confirm, not working for ally as well

**Comment by KieraHorde** [comment]
Will it be fixed?

**Comment by Sayris987** [comment]
Not working for horde too

**Comment by maslak** [comment]
bump

Odswieżam.

Achievement Pilgrim's Paunch nie działa po obu stronach barykady[Ally-Horda]

Ally: http://www.wowhead.com/achievement=3556/pilgrims-paunch  - 3556
Horda: http://www.wowhead.com/achievement=3557/pilgrims-paunch - 3557
Jest możliwe zdobycie The Spirit of Sharing http://www.wowhead.com/spell=61849/the-spirit-of-sharing - 61849 ale nie zalicza nam tego.

Jest to jedyny achievement, którego nie można zdobyć co za tym idzie peta i tytułu. 
Przy okazji ten cały event nie rozpoczyna się w dobrym dniu.

**Comment by vaseno1** [comment]
bump pls fix its been 2nd year or 3rd since this does not work!

**Comment by Dranerys** [comment]
Confirmed that it's the only achievement for the Pilgrim title that doesn't work.
