### ISSUE TITLE
[EN][Achievement] Pilgrim's Peril

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#4957]
http://www.wowhead.com/achievement=3580/pilgrims-peril
http://www.wowhead.com/achievement=3581/pilgrims-peril

Doesn't work.

**Comment by kostas4949** [comment]
You sure? Just completed it on horde. No issues at all.

**Comment by gurin** [comment]
Tried it yesterday in Undercity as human and it does not work. Checked several tables while wearing Attire, Hat and Boots.

**Comment by lena142** [comment]
Same here - only Thunder Bluff works when you are from Alliance.

**Comment by mean931** [comment]
now working for tb, ogri, silvermoon but still not working for uc

**Comment by LordKnightCecilo** [comment]
Worked for Orgrimmar.

**Comment by Illusionist87** [comment]
Heard it was possible to complete but most of the capitals have chairs missing, and those that I found are bugged (can't sit in them). Horde chairs even got transferred to different continent using Orgrimmar zeppelin.
So at the moment it is almost impossible to complete this

Moving chairs problem was reported in a different thread: #4958

**Comment by Damfee** [comment]
Pilgrim's Bounty 2016 is upon us!

The undercity chair still does not work though. Can't get credit for it.

And the orgrimmar chairs have already been moved far far away from their original location by hordies, which shouldn't be possible.

**Comment by ofelia59** [comment]
The achievement doesn not work for the Alliance in Undercity and server keepers do not make any efforts to improve all those bugs. It is frustrating and awfull that such poor server decided to take so many players from Sunwell. I try to find any other server to move and leave that trash called Atlantis empty

**Comment by DuGalle** [comment]
confirmed broken

**Comment by Pphhaaaddd** [comment]
I was able to do this by moving the bugged chairs near the zone change boundary, and then re-mounting them. This was like a week ago though.

**Comment by Bildo** [comment]
In Undercity you have to move with chairs to different area and to be more precisely to area where undercity is marked as horde only in the passage to lordaeron or near evelevators to the undercity. This is a temp solution.

**Comment by Bildo** [comment]
Ok event extended for 3 days, if you want to achieve in Undercity please use chairs in this 'weird' place :P
