### ISSUE TITLE
[EN][Warlock][Spell] Dark Intent

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#4960]
Dark intent gives more than 3% Haste right now, so its scale with somethin.
I Saw the numbers between 3.20% to 3.70%
For Example:
Before DI: http://files.tinypic.pl/i/00726/szwp9hgo1o93.jpg 8.14
After DI: http://files.tinypic.pl/i/00726/viu9nfo5tpfv.jpg 11.38
Other locks have same "problem" :P

Ps look my post in https://github.com/Atlantiss/BugTracker/issues/3389 <3

**Comment by aneq** [comment]
maybe because haste is multiplicative and not additive
