### ISSUE TITLE
[EN][Quest][Swamp of Sorrows]can't take it with them

### ISSUE THREAD

**Issue by l337g0g0** [Atlantiss/BugTracker#4962]
The mobs you have to loot are not in the water floating like their suppose to be...

http://www.wowhead.com/quest=27599/cant-take-it-with-them

**Comment by Thefakemccoy** [comment]
Should put the quest link in or it might be subject to being closed.

**Comment by l337g0g0** [comment]
TY...

**Comment by Quban** [comment]
fixed in rev 5117
