### ISSUE TITLE
[EN][Quest][Thousand Needles] Pirate Accuracy Increasing

### ISSUE THREAD

**Issue by Davirafa** [Atlantiss/BugTracker#4963]
This NPC (http://www.wowhead.com/npc=40475/jinky-twizzlefixxit) dont give the quest (http://www.wowhead.com/quest=25532/pirate-accuracy-increasing), so I can´t earn the boat.
(http://www.wowhead.com/item=55121/river-boat#comments)

**Comment by Bildo** [comment]
It does work, you need to complete first Down in the Deeps | Bar Fight! and | In the Outhouse
