### ISSUE TITLE
[EN][Mining][Mining Nodes on trees]

### ISSUE THREAD

**Issue by dzejsonator** [Atlantiss/BugTracker#4969]
Hello guys, it's not very major bug, but it looks kinda retarded and is really confusing sometimes, especially for miners without flying. A lot of mining nodes appear at the top of trees. I noticed at least two spots in Duskwood, one in Elwynn Forest and two (for now) in Stranglethorn Vale. Hope for you guys to fix this, I would really love to mine ores from ground and save poor trees. Cheers.

**Comment by EnderBlazer** [comment]
True. Not only the mining nodes show up on top of trees, sometimes they're in the water surface.

**Comment by pipesbez** [comment]
I had a similar problem in Durotar , mainly in Drygulch Ravine but in other places with crags as well . The nodes spawn up on the crags and there is no way to get to them . I know some people can fly up there and mine them but those are copper nodes and are mainly for low level characters who cant . I think they should be better on the ground where everyone can reach them . Thank you in advance .
