### ISSUE TITLE
[EN][Hunter][Spell] Explosive Shot reapplying (possibly related to all DoT spells)

### ISSUE THREAD

**Issue by 0cto** [Atlantiss/BugTracker#4970]
In patch 4.0.1 the way that Damage over Time (DoT) abilities worked was fundamentally changed. Here a quote giving information on how the new DoT reapplying works:
http://wow.gamepedia.com/Previews_of_class_changes_in_Cataclysm
"All warlock damage-over-time (DoT) spells will benefit from crit and haste innately. Haste will no longer act to reduce the DoT's duration, but rather to add additional ticks. When reapplying a DoT, you can no longer "clip" the final tick. Instead, this will just add duration to the spell, similar to how Everlasting Affliction currently works."
"Preventing dot clipping is something we want to do in general. It obviously benefits Shadow priests just as much as warlocks."

This reapplying was also applied for Explosive Shot.
What this means for Explosive Shot is that when Lock and Load triggers and you use Explosive Shot wait for the GCD and a small fraction of a second and then cast the second Explosive Shot you should see the following:
1. You cast the first explosive shot, Explosive Shot deals instant damage and leaves a 2 second DoT.
2. After 1 second the first DoT tick does damage
3. You cast the second Explosive Shot, This deals instant damage and refreshes the existing DoT making it 3 seconds long.
4. You see a DoT tick every seconds for the remaining 3 seconds.
This results in a total of 6 Explosive Shot damage Ticks (2 of them instantly when Explosive Shot hits the target and 4 from the periodic damage).

This reapplying mechanic is bugged here for Explosive Shot (whether or not it works for other DoT spells on other classes I don't know yet).
What I observe is that the 2nd Explosive Shot only leaves a 2 second DoT (instead of 3). This results in only 5 total Explosive Shot damage Ticks as shown here http://i.imgur.com/rjCVAfp.jpg

I hope that it's clear what the problem is and I hope that we can soon also test this reapplying mechanic for other damage over time abilities.

**Comment by kadi2** [comment]
Not sure if it's not already applied on the main by lama

**Comment by Jenovas** [comment]
Works properly
