### ISSUE TITLE
[EN] Strange wavy edges and water on client

### ISSUE THREAD

**Issue by ylluminarious** [Atlantiss/BugTracker#4971]
I'm having some strange wavy graphics on my client that have been happening on Windows 8, 8.1 and 10. I've my updated my drivers multiple times to try and fix this issue, but to no avail. I've been thinking that this might have something to do with the Nvidia driver and/or Direct X, but can't resolve it.  The edges are wavy or very distorted/tessellated. Water is especially bad. Here's a short screen recording of the issue in action around the edges and also some clipping demonstrated:
![Image of Edge Rendering Problem](http://f.cl.ly/items/1E0f1e0k2r3m1k2d0W0C/Screen%20Recording%202015-11-19%20at%209.22.36%20PM.gif)

It seems to happen on all water and protruding objects as well as sometimes when there is an object that has a chance to clip through another object.

Any idea of what may be going on or how to resolve this problem?

Also, here's some hardware information that I thought might be relevant: ![driver or hardware info](http://cl.ly/image/0h0c1M183a2c/Image%202015-11-19%20at%209.02.54%20PM.png)

**Comment by wtRCH** [comment]
this is computer related, doesn't happen to me at all
