### ISSUE TITLE
[EN][Quest][Horde][Stonetalon Mountains] We're Here to Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Atlantiss/BugTracker#4972]
When you take the wagon to stonetalon to the fold. If you get in combat the waghon stops till you die have to run back to corpse kill every thing that stopped you and start the wagon ride all over.

http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two

**Comment by vragni** [comment]
still buged

**Comment by Luchass** [comment]
Is there any news?

**Comment by Lidless** [comment]
thissideup-atlantiss commented on Jan 31 2016 "
Quest is completable by starting from The Fold and running back to Silverwind Refuge (preferably on a mount) the same path the Wagon is taking. If you take out the two Sentinal Ambushers in the Crag (one right and one left of the road) and the two Ashenvale Assassins right outside the Skunkworks, the Wagon will ride right through to The Fold.
"
This one is a good solution, so follow it! You have to kill that 2 Sentinal Ambushers and they will not attack you on the way. If you are too slow and the Ambushers are up again then I suggest you to set your HS to Silverwind refuge so you can jump back in no time after clearing the way.
