### ISSUE TITLE
[EN][Quest][Badlands] Lifting the Veil

### ISSUE THREAD

**Issue by hollowIncorporalis** [Atlantiss/BugTracker#4975]
This is what's supposed to happen:
https://www.youtube.com/watch?v=0797Tk5-LTM
For some reason nothing is going on, i need some help here guys, if i don't finish this quest i'll not be able to progress in Badlands.

**Comment by Thefakemccoy** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/1632
