### ISSUE TITLE
Ogrish motivation

### ISSUE THREAD

**Issue by samvel2804** [Atlantiss/BugTracker#4977]
I know dungeons are not to be reported but theres a bug that players can and do abuse. Beffor the first boss in dead mines there are 2 ogres that buff the players attack speed with the skill "Ogres Motivation". That buff never ends! Even outside of the dungeon thay run around with 25% or more higher attack speed. 
skill: http://www.wowhead.com/search?q=ogrish+motivation%5D

**Comment by Bildo** [comment]
read bt rules
