### ISSUE TITLE
[EN][NPC][ The Arcatraz]Eredar Deathbringer

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4979]
http://www.wowhead.com/npc=20880
Thin NPC is missing from the game. He is important because it is the only NPC in the game that drops Formula: Enchant 2H Weapon - Major Agility.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6868-4979-npc-the-arcatrazeredar-deathbringer/
