### ISSUE TITLE
Still Assessing the Threat

### ISSUE THREAD

**Issue by samvel2804** [Atlantiss/BugTracker#4982]
The quest items can't be read. And the end quest text is missing.
quest http://www.wowhead.com/quest=26503/still-assessing-the-threat
Gnoll Battle Plans: http://www.wowhead.com/item=58887/gnoll-battle-plans
Gnoll Orders: http://www.wowhead.com/item=58888/gnoll-orders
Gnoll Strategy Guide: http://www.wowhead.com/item=58889/gnoll-strategy-guide

**Comment by Bildo** [comment]
read bt rules
