### ISSUE TITLE
[en][quest] Wanted: Redridge Gnolls

### ISSUE THREAD

**Issue by samvel2804** [Atlantiss/BugTracker#4986]
This quest dosent have end quest text. Just a blank window with the reword.
http://www.wowhead.com/quest=26504/wanted-redridge-gnolls

**Comment by Thefakemccoy** [comment]
Fix your titles you are wasting time they are getting closed.

**Comment by Quban** [comment]
i ve good day and fixing titles :D

**Comment by Quban** [comment]
http://scr.hu/75h5/juc59 i dont see any bugs here

**Comment by Thefakemccoy** [comment]
I see nothing wrong with this quest.

![wowscrnshot_112815_195614](https://cloud.githubusercontent.com/assets/12252441/11454801/2b40cefc-960a-11e5-83f8-3119d7347a5a.jpg)

**Comment by Thefakemccoy** [comment]
Maybe you have addon conflicting with it
