### ISSUE TITLE
[EN][NPC] Coach Crosscheck Assistant Greely Foreman Dampwick

### ISSUE THREAD

**Issue by deathb** [Atlantiss/BugTracker#4988]
Some of the NPC's like Coach Crosscheck, Assistant Greely and Foreman Dampwick are spawned in wrong locations. Can someone please respawn them in the right location?
![wowscrnshot_112115_144011](https://cloud.githubusercontent.com/assets/15955925/11318520/9866765a-905e-11e5-89a0-7a635489ab04.jpg)
![wowscrnshot_112115_144034](https://cloud.githubusercontent.com/assets/15955925/11318521/986698ce-905e-11e5-8587-6c9188b34c32.jpg)
![wowscrnshot_112115_144121](https://cloud.githubusercontent.com/assets/15955925/11318519/9865eac8-905e-11e5-8484-f08f90e5b0fd.jpg)

**Comment by RandomPickNewb** [comment]
Read https://github.com/Atlantiss/BugTracker and change your title otherwise your bug "report" will be closed even if it's a legit bug.
