### ISSUE TITLE
[EN][PL][Spell][Warlock] Hand of Gul'dan

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#4989]
**[EN]**
Hand of Gul'dan: http://cata.openwow.com/spell=71521

Aura it applies shouldn't affect friendly targets, only hostile.
Movie of a beta in Cataclysm: https://youtu.be/3D4ZxThihQU?t=105
Watch from 1:45

---------------------------
**[PL]**
Hand of Gul'dan: http://cata.openwow.com/spell=71521

Aura, którą powoduje ta umiejętność, nie powinna dotyczyć przyjaznych celów, jedynie wrogie.
Film z beta testów Cataclysm: https://youtu.be/3D4ZxThihQU?t=105
Proszę obejrzeć od 1:45

**Comment by Aviannaqt** [comment]
#3338

**Comment by Avalain** [comment]
@Aviannaqt This is separated issue. You referenced this bug of untalented skill to talented skill. Problems between them are different.

**Comment by aneq** [comment]
@Aviannaqt 
fixed
