### ISSUE TITLE
[EN][Quest][Bloodmyst Isle] Alien Predators

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#4990]
I can not get this quest  Alien Predators: http://www.wowhead.com/quest=9634/alien-predators and I have tried all prerequisites that lead up to it.

I completed Hero's Call: Bloodmyst Isle! : http://www.wowhead.com/quest=28559/heros-call-bloodmyst-isle and I still can not obtain it.

I tried to do the lead up quest http://www.wowhead.com/quest=9625/elekks-are-serious-business
but quest giver did not offer it. Even before I did the hero's call quest he did not offer me this quest.

**Comment by Quban** [comment]
You must complete  http://www.wowhead.com/quest=28559/heros-call-bloodmyst-isle + http://www.wowhead.com/quest=9625/elekks-are-serious-business, to do elekks you have to finish http://www.wowhead.com/quest=9623/coming-of-age first. I ve tested it now and it works
