### ISSUE TITLE
[EN][PL][Spell][Warlock] Demon Armor

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#4991]
**[EN]**
Demon Armor: http://cata.openwow.com/spell=79934

Currently spell doesn't have a duration when applied. It should be a buff with duration of 30 minutes. Similar to Molten Armor. Mage Armor, Frost Armor etc. 

After relogging spell disappear, and need to be reapplied. Again, it should work as MolA, MagA, FA etc. which remain on character till death, dispel or whole duration.

-------------
**[PL]**
Demon Armor: http://cata.openwow.com/spell=79934

Aktualnie umiejętność nie ma czasu trwania. Powinien to być buffek z czasem trwania 30 minut.
Podobnie do Molten Armor, Mage Armor, Frost Armor itd.

Po relogowaniu buffek znika i musi zostać nałożony ponownie. Powinno to działać jak MolA, MagA, FA itd. które pozostają na postaci aż to śmierci, dispela lub całą durację.

**Comment by Fearyourself** [comment]
Demon Armor is not supposed to have a duration in 4.3.4. and the link you've provided is a NPC spell.

**Comment by Avalain** [comment]
Yes, I noticed patch changes after I posted issue, hence I closed it myself.

**Comment by TranceAccount** [comment]
> After relogging spell disappear, and need to be reapplied. Again, it should work as MolA, MagA, FA etc. which remain on character till death, dispel or whole duration.

I can confirm this, but I have no proof that it should stay applied after relogging. Would be nice tho.
