### ISSUE TITLE
[EN][PL][Spell][Warlock] Fel Armor

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#4992]
**[EN]**
Fel Armor: http://cata.openwow.com/spell=79954

Currently spell doesn't have a duration when applied. It should be a buff with duration of 30 minutes. Similar to Molten Armor. Mage Armor, Frost Armor etc. 

After relogging spell disappear, and need to be reapplied. Again, it should work as MolA, MagA, FA etc. which remain on character till death, dispel or whole duration.

Movie showing duration of buff: https://youtu.be/VcInhXEHeMU?t=23

-------------
**[PL]**
Fel Armor: http://cata.openwow.com/spell=79954

Aktualnie umiejętność nie ma czasu trwania. Powinien to być buffek z czasem trwania 30 minut.
Podobnie do Molten Armor, Mage Armor, Frost Armor itd.

Po relogowaniu buffek znika i musi zostać nałożony ponownie. Powinno to działać jak MolA, MagA, FA itd. które pozostają na postaci aż to śmierci, dispela lub całą durację.

Filmik pokazujący czas buffku: https://youtu.be/VcInhXEHeMU?t=23

**Comment by Fearyourself** [comment]
Fel Armor is not supposed to have a duration in 4.3.4. and the link you provided is the spell of an NPC.

**Comment by Avalain** [comment]
Yes, I noticed patch changes after I posted issue, hence I closed it myself.
