### ISSUE TITLE
[PL][Raid-Cata] The Conclave of Wind - Rogue Stealth/Vanish

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#4993]
Bug tyczy sie rogala, czy to przed pullem czy w trakcie walki czesto wchodzac w Stealth cała platforma na której znajduja sie bossy staje sie niewidzialna i i kiedy poruszy sie postac badz skoczy to sie spada. Tak samo podczas walki po uzyciu Vanish'a i ruchu postacia sie spada  i po chwili wraca sie na platforme. Nieco uciazliwy bug.

**Comment by Bastion** [comment]
jak tank pada na kwiatkach i nie da sie go resnac bo spadl pod platforme to znaczy ze jest to wina rogala bo ma dziwne spele?

**Comment by melsage** [comment]
Ja co innego ( zglaszam buga) ty co innego.... Bug to bug

**Comment by tnarf** [comment]
juz zgloszone
https://github.com/Atlantiss/BugTracker/issues/4716

**Comment by Quban** [comment]
Duplikat
