### ISSUE TITLE
[EN][Quest][Gilneas] The Battle for Gilneas City

### ISSUE THREAD

**Issue by starsurge7** [Atlantiss/BugTracker#4994]
http://wowwiki.wikia.com/wiki/Quest:The_Battle_for_Gilneas_City 
After starting this quest you just get teleported into the city and quest is completed. Are you working on making it work? It's really awesome quest, I got very disapointed when it auto completed...

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3558
