### ISSUE TITLE
[EN][Cinematic][Gilneas] Liam Graymane's funeral

### ISSUE THREAD

**Issue by starsurge7** [Atlantiss/BugTracker#4995]
https://www.youtube.com/watch?v=N9uHT-XKbwU

Cinematic that should start after completing "Quest:Patriarch's Blessing"  in Gilneas (http://wowwiki.wikia.com/wiki/Quest:Patriarch%27s_Blessing) does not show up. 

This is not a big problem of course, but since this server is striving to be a blizzlike server I decided to report it.

**Comment by BAndysc** [comment]
Fixed in rev 5103
