### ISSUE TITLE
[EN] [Guild] No Rep gains at 85 for TB quests and Dungeons

### ISSUE THREAD

**Issue by Slotease** [Atlantiss/BugTracker#4996]
My Tenkan is getting no reputation at all anywhere and is stuck at recruit.

**Comment by Anhaeyn** [comment]
You get rep with guild only from quests (TB, dailies) and maybe you don't know, but there's rep cap you can get per week. (resets in wednesdays). You can find it, if you in-game press J.

**Comment by Slotease** [comment]
That was it. 2 years in retail and 8 months here and i still did not know that. Was here to close ticket. thanks
