### ISSUE TITLE
[EN][Quest][Dun Morogh] Missing in action 

### ISSUE THREAD

**Issue by lena142** [Atlantiss/BugTracker#4997]
Still same problem as in #4098 - it wants me to rescue 6 captured demolitionists that are located in cages. I cannot finish it as lvl 4 gnome priest. All cages are open and cannot be used for the quest.

**Comment by ylluminarious** [comment]
+1

**Comment by Bankstercide** [comment]
Still bugged.  Cages are open, Demolitionists are non-interactable.  It's kind of a problem, as it's part of the main story quest chain that takes you out of Dun Morogh.

**Comment by ylluminarious** [comment]
@Bankstercide 
I think that @Bildo closed this to avoid duplicate tickets.
