### ISSUE TITLE
[EN][Zone][Vash'jir][Throne of the Tides][Entrance]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#4998]
How it should work https://www.youtube.com/watch?v=G7gAel8cRTs
How it "works":
![wowscrnshot_112215_140926](https://cloud.githubusercontent.com/assets/12395407/11324008/29d26944-9124-11e5-9f1a-a4efce66b249.jpg)
So, I managed to get to the bottom of this vortex (by queueing and joining WSG one time to reset my breath) and then NOTHING happened. Absolutely N-O-T-H-I-N-G. It should have swallowed me up but instead I just drowned and appeared near the Westfall (why??? o_O) Spirit Healer.
![wowscrnshot_112215_141717](https://cloud.githubusercontent.com/assets/12395407/11324030/e6cfab56-9124-11e5-9517-1d7a341ba275.jpg)

**Comment by Thefakemccoy** [comment]
Thats prob cause Vashijr is not scriptied at all.
