### ISSUE TITLE
Loch Modan Lord Condar

### ISSUE THREAD

**Issue by Khyranee** [Atlantiss/BugTracker#4999]
After taming Lord Condar in Loch Modan and dissmising him, then calling it back it changes his look from an white giant vulture to an black - red small vulture. It totaly changes his model.

**Comment by Luna-maria** [comment]
should probably fix the title
http://www.wowhead.com/npc=14268/lord-condar there's the wowhead link for the npc

**Comment by Khyranee** [comment]
Its not about the title, its about the entire model and colour of the bird :( It seems that its bugged.

**Comment by Kejmil** [comment]
it's about reading bugtracker rules, moron :D

**Comment by Khyranee** [comment]
I don't care about bugtracker, i care about the fact that something in this damn server is broken ;-;
