### ISSUE TITLE
[en][mage][spell] Living Bomb Explosion and interrupt from it

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#5001]
Living bomb explosions interrupt yours spell casts ( the mage who casted living bomb)
was working fine last week
annoying.. :( 
http://www.wowhead.com/spell=44457/living-bomb

**Comment by Kejmil** [comment]
can't reproduce on dummy

**Comment by Wolffenstein** [comment]
There were no changes made to LB recently.
