### ISSUE TITLE
[EN][NPC]Jaelysia

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5004]
http://www.wowhead.com/npc=10085/jaelysia

supposed to be able to stable my pets at her, but the only 2 options she has are: 
I'm looking for a lost companion

and

I'd like to heal and revive my battle pets 
which shouldn't even be a thing until mop? 

edit, same goes for Alassin http://www.wowhead.com/npc=10056/alassin

**Comment by Tierek** [comment]
I've already made this ticket, please add these to the list on the appropriate page:

https://github.com/Atlantiss/BugTracker/issues/4878
