### ISSUE TITLE
Thunderaan the Windseeker

### ISSUE THREAD

**Issue by Xtrodinary69** [Atlantiss/BugTracker#5007]
Essence of the Firelord: http://www.wowhead.com/item=19017/essence-of-the-firelord
Ragnaros (MC): http://www.wowhead.com/npc=11502/ragnaros
Thunderaan the Windseeker quest: http://www.wowhead.com/quest=7786/thunderaan-the-windseeker

Item Essence of the Firelord should have 100% drop from Ragnaros in Molten Core while we have quest "Thunderaan the Windseeker" in our changelog (quest for Legendary weapon). 
Right now looks like it has "original" % drop like without having quest.
I killed Ragnaros so many times with quest active and it didn't drop yet.

Quest was reported on February as bugged. On March it was replyed as fixed, but now it's still not droping. (killed him abaut 7 times with the quest)

**Comment by Achiver** [comment]
You will get many essences before you get both halfs and elementium bars anyway.

**Comment by Xtrodinary69** [comment]
I have both essences and 10 bars already...and I'm farming the essence only.

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/2983
