### ISSUE TITLE
[EN][Achievement] BWD and To4W guild run

### ISSUE THREAD

**Issue by Spydoc** [Atlantiss/BugTracker#5008]
Omnotron Defense System and Conclave of Wind don't count for their respective guild achievements once killed, although we've killed them multiple times with a full 10-man group.

http://www.wowhead.com/achievement=4985/blackwing-descent-guild-run
http://www.wowhead.com/achievement=4987/throne-of-the-four-winds-guild-run

**Comment by Sayris987** [comment]
I already have post about conclave but so far nothing and about ODS we got it without problem maybe it got bugged after that since i saw few more ppl complaining about that fight too

**Comment by Thefakemccoy** [comment]
this should be fixed in Rev:4670

**Comment by Spydoc** [comment]
I don't see how that fix will have an effect on ODS, since we're pretty close to each other in that fight.

**Comment by Thefakemccoy** [comment]
it could just be a radius thing if you are say more than 5 meters form the active boss you might not get credit so 3 of the 10 guild memebers are to far away would cause you to not get guild achv

**Comment by Aviannaqt** [comment]
Should be work fine after update.
