### ISSUE TITLE
See Raptor (Stranglethorn Vale)

### ISSUE THREAD

**Issue by Zabrajin** [Atlantiss/BugTracker#5010]
Speak with Priestess Hu´Rala at Bambala to participate in the Mind Vision ritual.
This quest does not work, i cant speak with priestess.
PS this server is amazing. A lil bit of bugs, but its like playing on official. Keep doing great work. Hope there will be sometime a MoP datadisk there :)

**Comment by Luna-maria** [comment]
suggest fixing your title, instructions here http://atlantiss.eu/pages/10
also add a wowhead link :) 
if not they'll close the post

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/500
