### ISSUE TITLE
Darkshore - Quest: The Eye of All Storms

### ISSUE THREAD

**Issue by Khyranee** [Atlantiss/BugTracker#5014]
1. There is no portal in the top of the whirlwind
2. The dragoness doesnt know how to land when i click the command
3. The purple dragons rather than flying in circles they are just falling down to the ground
4. I cant complete the quest, please help me somehow :(

**Comment by Avalain** [comment]
Quest is bugged, there is no doubt but issues perish after server restart. 

Till someone does quest portal and dragons are there. 
To kill dragons mount up your dragon and right click enemy. After this use special abilities.

**Comment by Khyranee** [comment]
Thank you :) sorry for breaking the rules if i did :x
