### ISSUE TITLE
[EN][PL][Spell][Warlock] Soulburn + Demonic Circle: Teleport

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#5015]
**[EN]**
Soulburn: http://cata.openwow.com/spell=74434
Demonic Circle: Teleport: http://cata.openwow.com/spell=48020

After using Soulburn and Demonic Circle: Teleport, we're correctly receiving buff Soulburn: Demonic Circle (http://cata.openwow.com/spell=79438), problem is that Soulburn buff still remain on our character after teleport, not consumed. Buff (Soulburn) should be consumed after teleportation.

--------
**[PL]**
Soulburn: http://cata.openwow.com/spell=74434
Demonic Circle: Teleport: http://cata.openwow.com/spell=48020

Po użyciu Soulburn i Demonic Circle: Teleport, prawidłowo otrzymujemy buff Soulburn: Demonic Circle (http://cata.openwow.com/spell=79438), problem polega na tym, że Soulburn pozostaje na naszej postaci po teleporcie, nie zużyty. Buff (Soulburn) powinien zostać zużyty zaraz po teleportacji.

**Comment by Jenovas** [comment]
Fixed in rev 4717
