### ISSUE TITLE
[EN][Raid][BWD]Nefarian Stage

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#5016]
Hi.
I wondered if the problem with Nefarian stage is fixed.
The problem in Nefarian stage was with pet(s)

Since I play Demonology warlock on pve, the pet(s) are huge source of dps to me.
And on Nefarian the pet does not attack, actually he stuck somewhere underground.

I believe other classes that using pet have some problem. or maybe not?

well, I did not made a raid run since two months ago.
so I just asking / checking things here.

if it's not the place, lock the issue.

**Comment by gurin** [comment]
Same with warrior and feral charge, rogue shadowstep, combat ressurection, etc.. You fall under textures.
