### ISSUE TITLE
[EN][QUEST][Southern Barrens] A Line in the Dirt

### ISSUE THREAD

**Issue by Asharok** [Atlantiss/BugTracker#5017]
http://www.wowhead.com/quest=24546/a-line-in-the-dirt
Objectives are to capture a point and to defend a point. There are neutral grey flags that have to be clicked on. These should spawn two grunts, and presumably alliance forces attack until the objective is achieved.
Currently, one of the flags disappears completely when clicked, and the other spawns the grunts and then nothing happens.

**Comment by Quban** [comment]
pls give links to quest from wowhead next time

**Comment by Syrnikus** [comment]
Quest dont works

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/583

**Comment by Thunderlmao** [comment]
As of 14/04/2017 the field banner just disappears after clicking it.
