### ISSUE TITLE
[EN][QUEST][Stonetalon Mountains] To Be Horde...

### ISSUE THREAD

**Issue by Asharok** [Atlantiss/BugTracker#5018]
http://www.wowhead.com/quest=26115/to-be-horde
Talking to the NPC for this quest should start an event where the hot air balloon bombs the NPC area below. The warchief should then appear and kill the orc NPC. The quest is then completed by talking to the Tauren NPC. Currently, the quest can be accepted but no option is available to start the event so nothing happens.

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/8231
