### ISSUE TITLE
[EN][Hunter][Talents][Major] - Pathing + Focus Fire

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#5021]
A major bug in Beast Mastery Hunters.

When pet reaches (1 to 5) stacks of frenzy, u can use Focus fire - http://cata-shoot.tauri.hu/?spell=82692
When this is used, the talent Pathing  - http://cata-shoot.tauri.hu/?spell=52786 stops working. When focus fire ends , it starts to work again. So this leads to loosing all the haste from pathing. And since focus fire is almost always on, we loose 3% of the haste rating at all times.

Edit : Its the rank 2 and 3 of Pathing talent that doesnt work with Focus Fire. Rank 1 (1%) works, but rank 2(2%) and 3(3%) dont. So for example if i have 1/3 in pathing and my haste is 5.32%, that makes 6.37%.
6~% + Focus fire at 5 stacks of frenzy(15%) = 21% ~ 

but when i have 3/3 Pathing. my haste is now 8.48%. Using focus fire at 5 stacks of frenzy (15%) and i again get 21%~, rather than 23% ~.

**Comment by Aviannaqt** [comment]
#3007

**Comment by anxanas** [comment]
Nerf hunters please

**Comment by meowmewo** [comment]
buump
