### ISSUE TITLE
[EN][Quest][Storm Peaks] Fate of the Titans

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#5023]
http://www.wowhead.com/quest=12986/fate-of-the-titans

Creteus in the Foot Steppes has requested that you travel to the Temple of Invention, the Temple of Winter, the Temple of Life, and the Temple of Order and utilize the databank to examine each area.

	Temple of Invention Investigated
	Temple of Winter Investigated
	Temple of Life Investigated
	Temple of Order Investigated
Provided item:
	Creteus' Mobile Databank
--------------------------------------------------------------------------------------------------------------------------------
There is either a phasing issue or missing script here the summoned pet will not go through its script to complete quest objectives.  Possible fix from trinitycoredb:

https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/sql/old/4.3.4/TDB5_to_TDB6_updates/world/087_2013_09_16_00_world_sai.sql

**Comment by Noviush** [comment]
There is another problem with this quest/event. After finishing this chain and another http://www.wowhead.com/quest=12973/the-brothers-bronzebeard
Creteus event shold be finished and The Foot Stepped zone should be back to previous state, but it's not.
Zone still stays on event phase, and can't do daily The Frosborn rep quest "Pushed Too Far" http://www.wowhead.com/quest=12869/pushed-too-far
