### ISSUE TITLE
[en][quest] matters of loyalty

### ISSUE THREAD

**Issue by Xtrodinary69** [Atlantiss/BugTracker#5025]
After accepting the quest a cinematic should appear. Nothing happens..
http://www.wowhead.com/quest=28600/matters-of-loyalty

**Comment by magromo** [comment]
As I know, cinematics and other things such as these don't work on privates.

**Comment by Xtrodinary69** [comment]
To make it simple, quest is bugged it can't be completed

**Comment by SloaneMarie** [comment]
I'm having that issue as well. No NPC to talk to.

**Comment by Angelo-DM-** [comment]
Confirm! You can't complete this quest!
How the quest should work: https://www.youtube.com/watch?v=Wl8BnLXwNHI

This quest block (in order):
1) [Cry of the Banshee (ID:28538)](http://www.wowhead.com/quest=28538/cry-of-the-banshee)
   2) [Decimation (ID:28566)](http://www.wowhead.com/quest=28566/decimation)
      3) [Infiltration (ID:28603)](http://www.wowhead.com/quest=28603/infiltration)
         4) [Deception and Trickery (ID:28604)](http://www.wowhead.com/quest=28604/deception-and-trickery)
            5) [Domination (ID:28605)](http://www.wowhead.com/quest=28605/domination)

**Comment by Aviannaqt** [comment]
fixed in 4909
