### ISSUE TITLE
[EN][Quest] The Breath Of Cenarius

### ISSUE THREAD

**Issue by luigimaru** [Atlantiss/BugTracker#5028]
http://www.wowhead.com/quest=28343/the-breath-of-cenarius
2nd Class Quest for Druids. I can collect the "Breath of Cenarius", but cant close any portal since there is none. The interest is the reward, antler's horns. thanks

**Comment by Rinniel** [comment]
Bump, still not working

**Comment by Bildo** [comment]
fixed
