### ISSUE TITLE
[EN][Quest] Livin' the Life

### ISSUE THREAD

**Issue by dan2142** [Atlantiss/BugTracker#5031]
http://www.wowhead.com/quest=26228/livin-the-life
Problem: Our carater insted of beeing in the item (Two-Shoed Lou's Old House) is somewere in the right side or behind her and is just sitting down.
Revision :4657

**Comment by tristanvm** [comment]
Can confirm http://i.imgur.com/eXRWz6X.jpg
The character is not supposed to be visible as they should be in the crate.

**Comment by Piklo** [comment]
#8968 reported with issue_template
