### ISSUE TITLE
[EN]Sentinel Hill

### ISSUE THREAD

**Issue by dan2142** [Atlantiss/BugTracker#5034]
[EN][Sentinel Hill][Westfall]
[Quest]:In Defense of Westfall ( this just one othe quests the problem persists more then just this quest its the global event in that this is scripted)
Link : www.youtube.com/watch?v=Bc_LxoqNMOc
NPC : Stormwind Investigator,Lieutenant Horatio Laine,Scout Galiaan,Captian Danuvin.
Problem: All this NPC are Dazed and they are in the wrong position and posture in there knees with there hands behind insted of the couth Worgen that  should be in the hang.
(Server revison : 4657)

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/5020
