### ISSUE TITLE
[EN][Buff][class] Druid Resto Master shapeshifter bugged after this new fix

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#5036]
Before the fix if u transform aquatic form , swift flight form ,flight form , travel form , tree form = u will loose Master shapeshifter buff and to fix it u need go bear form than back human form . ................................... Now after fix today : If u transform to bear , travel form, cat form, u will loose master shape shifter and to fix it u need transform again to bear or cat or travel form , while tree form is working fine with master shape shifter and aquatic form and all bird forms so guys gd job for fixing tree :)  . Remark for raiders , if u enter raid with master shapershifter bug u need transform cat , bear , or travel form to fix it or all ur healings will be low . Example entering with bug u need click Just once bear or cat or travel form to fix , if u click twice ! bugg returns .........I hope u can fix the new bugg guys soon. My regards professional dudu resto Tidehuntar.

**Comment by Fapguy** [comment]
No one uses master shapeshifter for healing.

**Comment by phanttom** [comment]
there one person uses master shapeshifter fapguy and that is ur (MOM). better stay out of it sir , keep ur comments for ur potatoe friends

**Comment by Jenovas** [comment]
Fixed in rev 4676
