### ISSUE TITLE
[PL][Quest] [Questioning Reethe]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5037]
Ten quest nie działa po rozmowie z npc i zabicu mobkow nic sie nie dzieje 
http://www.wowhead.com/quest=27261/questioning-reethe

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/3488

**Comment by RastaTinu** [comment]
Quest działa pod warunkiem, że od razu zabijemy wszystkie mobki zaraz po tym jak się pojawią.
