### ISSUE TITLE
[EN][Quest][Icecrown] Battle at Valhalas: Fallen Heroes

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5040]
This quest can't be completed.
http://www.wowhead.com/quest=13214/battle-at-valhalas-fallen-heroes
The mobs get spawned correctly, but once killed you don't get credit for completing the quest objective.

![skaermbillede 2015-11-27 kl 15 11 37](https://cloud.githubusercontent.com/assets/12621497/11442972/cde06c86-9519-11e5-8a7a-7cd6bebffcd8.png)

Furthermore the mob giving the quest Geirrvif is always up in the air, but should actually start on the ground and only fly up once the quest have been accepted.
http://www.wowhead.com/npc=31135/geirrvif

She also bugs out after the combat event, and it's not possible to talk to her, so you can't abandon the quest and retake it immidiately (I don't know how and when she resets so it's possible to retake the quest.

This bug prevents the rest of the quests taken from her.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2550
