### ISSUE TITLE
[PL][Npc]Krkk'kx

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5043]
Gdy atakuje tego rare mobka wchodze i wychodze z kombatu i nie da sie go ubic 
http://www.wowhead.com/npc=4132/krkkkx
![wowscrnshot_112715_224950](https://cloud.githubusercontent.com/assets/16046575/11448621/22e8107a-955c-11e5-8b44-7a2d0917853f.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6867-5043-npckrkkkx/
