### ISSUE TITLE
[EN][GuildAchive] Cnonclave of the Wind

### ISSUE THREAD

**Issue by Sayris987** [Atlantiss/BugTracker#5048]
"Make achievements and loot rolls instance-wide (This will fix issues with loot and achievements on Throne of the Four Winds)".... This is from changelog we just did conclave and we still didn't get the achieve. I wonder if we fucked up something or it still not working? (Full guild run 10/10)

**Comment by Quban** [comment]
this fix was reverted, it was causing crashes
