### ISSUE TITLE
[PL][Thousand Needles]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5050]
W tym miejscu z niewyjasnionych przyczyn dostaje Combat Buga 
![wowscrnshot_112815_014923](https://cloud.githubusercontent.com/assets/16046575/11449503/81e5211e-9578-11e5-85d2-32e592adc78f.jpg)

**Comment by Thefakemccoy** [comment]
I manged to make out combat bug did you try .combatstate to see if it would drop your combat?

**.combatstate **

**Comment by Aviannaqt** [comment]
Użyj komendy ^ w tym miejscu i daj screena w #4722
