### ISSUE TITLE
[EN][Spell][Class] Mage Water Elemental does not have Avoidance, dies to every AoE

### ISSUE THREAD

**Issue by Pickles23** [Atlantiss/BugTracker#5051]
http://wow.gamepedia.com/Avoidance_(passive)
http://wowwiki.wikia.com/wiki/Avoidance_(pet)

"Avoidance was a pet talent located in the 3rd tier of all the pet talent trees. It was replaced by the pet talent Culling the Herd in patch 3.3.0, since Avoidance has been given as a passive treat to all player's pets, except Death Knights'."

Frost Mage Water Elemental should have Avoidance like other pet classes or it will die to any raid AoE.

**Comment by Illusie** [comment]
People play frost mage in raid (pve?) that new.

**Comment by aneq** [comment]
they do, and its pretty good spec

**Comment by rahliell** [comment]
Bump. Frost is largly gimped due to elemental being HUGE part of the spec and basicly non existant in any group environment.

**Comment by ocbald** [comment]
Bump. Frost mage is unplayable in PvE conditions only becausr of this bug.

**Comment by Kejmil** [comment]
just remember that in pvp environment there is no aoe avoidance for pets

**Comment by ocbald** [comment]
Bump, frost mage is completely unplayable in raids at this moment

**Comment by Jenovas** [comment]
Fixed in rev 5077
