### ISSUE TITLE
[PL/EN][Instance-WotlK] Culling of Stratholme - Mal'ganis Loot-chest bugged.

### ISSUE THREAD

**Issue by Incia** [Atlantiss/BugTracker#5052]
Skrzynia z lootem z ostatniego bossa wciąż nie działa pomimo Fixa.
https://github.com/Atlantiss/BugTracker/issues/4145

 rev. 4666 Author: Bildo :: 2015-11-22 12:42 - Waiting for update
Culling of Stratholme:
    Fix Mal'ganis chest
Po skończonej instancji i wysłaniu tickietu w grze 3 godziny później GM zasugerował zgłoszenie do poprawy na BT.

 When Malganis (last boss) die arthas should give a loot in chest but chest doesnt work

**Comment by Siudzin** [comment]
Prosze zróbcie tą skrzynie ;) nie mogę się już doczekać tarczy :P pozdrawiam :)

**Comment by Incia** [comment]
Tak samo czekam na nią -  wisienka na torcie do mojego transmoga.

**Comment by headachex** [comment]
I confirmed this as of 19.02.2016. When you kill MalGanis there is no loot (chest isnt lootable).

**Comment by Siudzin** [comment]
a ja jajaj zrooobicccie proszze teeeennn looooot ;p

**Comment by 1Andas** [comment]
Confirmed. Bump.

**Comment by DuGalle** [comment]
confiremd

**Comment by Vyrtuz** [comment]
(http://www.wowhead.com/object=193597/dark-runed-chest#contains)

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14181-9067-8748-5052-malganis-loot-tables/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
