### ISSUE TITLE
[PL][Quest][Orgrimmar] Weapons of Darkness

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#5053]
http://www.wowhead.com/quest=28473/weapons-of-darkness
Quest item nie dropi z żadnego dwarfa w instancji Blackrock Depths, ani z żadnego przeciwnika przed wejsciem do instancji
http://us.battle.net/wow/en/item/64313#tab=dropCreatures

**Comment by Aviannaqt** [comment]
Duplikat #4324
