### ISSUE TITLE
[PL][Spell][Warlock] Ritual of Summoning / Soulwell

### ISSUE THREAD

**Issue by Fabsik** [Atlantiss/BugTracker#5056]
Witam nie działa u locka:
http://www.wowhead.com/spell=698/ritual-of-summoning
http://www.wowhead.com/spell=29893/create-soulwell

A 2 dni temu wszystko jeszcze działało.

Pozdrawiam

**Comment by Kejmil** [comment]
no patrz a dzisiaj dzialalo jak uzywalem

**Comment by Fabsik** [comment]
No patrz a poszlismy na ulduar to 3 lokom nie dzialalo pytalem znajomych i tez mieli ten sam problem. Ogolnie to nawet nie pojawia sie "jajo" zeby kliknac.
 
W dniu 2015-11-28 16:37:55 użytkownik Kejmil <notifications@github.com> napisał:
no patrz a dzisiaj dzialalo jak uzywalem

**Comment by Glare** [comment]
Naprawcie do jutra bo raid mam i mnie nie wezmą.

**Comment by mitim1** [comment]
A loki wiedzo ze trzeba mieć KOGOŚ na targecie żeby zadziało?

**Comment by Avalain** [comment]
Możliwe, że jest to związane bardziej z lokacją w której próbowaliście używać skilli?
Nie zauważyłem aby te umiejętności nie działały.

**Comment by Glare** [comment]
Wszystko działa, może brak targetu.
