### ISSUE TITLE
[EN][Glyph][Warrior][Heroic Throw]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5061]
Applies only 1 "Sunder Armor" instead of stack (3).
![image](https://cloud.githubusercontent.com/assets/12395407/11453757/12db78ae-9618-11e5-9fd2-e6a0be9e17d8.png)

**Comment by Thefakemccoy** [comment]
The glyph it self says applies  a stack of sunder not 3stacks
