### ISSUE TITLE
[EN][IRONFORGE][QUEST] I need to Cask a Favor - daily

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#5062]
http://www.wowhead.com/quest=29356/i-need-to-cask-a-favor 
This is cooking daily quest in Ironforge. I need to get Cask of Drugan's IPA http://www.wowhead.com/object=208872/cask-of-drugans-ipa which seems to not spawning, so I can't finish this quest and get achievments in cooking.

**Comment by morgs71** [comment]
Can confirm this as of today still not spawning cask

**Comment by morgs71** [comment]
these still aren't spawning in world cannot complete this daily

**Comment by buzzstpoint** [comment]
No spawn of Cask as of 1/30/16

**Comment by jissabraham** [comment]
now its cooking daily is not rotating

**Comment by KuperusBP** [comment]
Still not working - even after implementation of fix

**Comment by jissabraham** [comment]
I need to Cask a Favor  not working not getting cask inside inn
