### ISSUE TITLE
[EN][Quest][Orgrimmar] Grimshot's Call 

### ISSUE THREAD

**Issue by SloaneMarie** [Atlantiss/BugTracker#5063]
Hello. I do apologize if this is not the place to post this. I am having trouble turning in these two quests and am wondering if they are bugged somehow. Grimshot's Call just won't allow me to turn in. Hero of the Sin'dorai, the NPC isn't anywhere to be found. I appreciate your time and patience. Thank you.
 
-Sloane Marie

http://www.wowhead.com/quest=27278/grimshots-call

**Comment by Thefakemccoy** [comment]
This would be the correct place to report a bug. However you should read the bug tracker rules.

**Comment by SloaneMarie** [comment]
Ok. Have I done something wrong? I've already looked around for these quests and didn't see anything.

**Comment by Thefakemccoy** [comment]
Your title should look like 
[EN][Quest][Zone] Grimshot's Call

and have a link which you do have now.

**Comment by Thefakemccoy** [comment]
Getting there
more like this
[EN][Quest][Redridge Mountains]Hero's Call to Redridge

you can remove all 
[EN][Quest][Zone] Hero of the Sin'Dorai/Silvermoon City
[EN][NPC] Lor'themar Theron
[EN][Spell][Class] N/A Blood Elf
[PL][Talent][Class] N/A Blood Elf
[EN][Glyph][Class] N/A Blood Elf
[EN][Npc][Drop] Magister Kaendris

Those are just examples of titles

**Comment by Thefakemccoy** [comment]
SO a ticket should look likke this 
Title Being 
[EN][Quest][Redridge Mountains]Hero's Call to Redridge

Then in the body explain whats wrong like 
Im trying to turn in the quest (quest name) but the npc is not there. Or something along those lines

Quest Link 
http://www.wowhead.com/quest=26365/heros-call-redridge-mountains

Npc
http://www.wowhead.com/npc=464/watch-captain-parker

Video
Optional

**Comment by Thefakemccoy** [comment]
Being 2 quest you should make 2 tickets

**Comment by SloaneMarie** [comment]
Like that?

**Comment by Thefakemccoy** [comment]
Yep just make sure instead of ZOne in the title you put the Zone name 
like Elywnn Forest or North Strangelthorn Vale or where ever the quest is

**Comment by SloaneMarie** [comment]
Thanks for your help. Never done this before.

**Comment by Thefakemccoy** [comment]
NP man they will close them of they arent right.
