### ISSUE TITLE
[EN][Quest][Silvermoon City] Hero of the Sin'Dorei

### ISSUE THREAD

**Issue by SloaneMarie** [Atlantiss/BugTracker#5064]
Hello. I do apologize if this is not the place to post this. I am having trouble turning in this quest and am wondering if it's bugged somehow. The NPC isn't anywhere to be found. I appreciate your time and patience. Thank you.
 
-Sloane Marie

http://www.wowhead.com/quest=9328/hero-of-the-sindorei

**Comment by Quban** [comment]
i ve respawned the npc, this issue is fixed just waiting to be applied to server, coz now npc has a week long respawn ;D
