### ISSUE TITLE
[en][mage][spell] Flame Orb / Frostfire Orb Duration time

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#5071]
Duration time of flame / frostfire orb on our server is too long. 
with stopwatch on it counts 18secs and it should be 15 STATIC 

http://wow.gamepedia.com/Flame_Orb

**Comment by Jenovas** [comment]
Flame Orb should last 18 seconds. 
In the blizzard files we see - Duration: ID (85)  18000, 0, 18000
They probably added the 3 seconds cause the orb has to show up, move a little bit before it reacts and it wastes a few seconds.

**Comment by Kejmil** [comment]
then the amount of atacks that flame orb performs is propably bugged
