### ISSUE TITLE
[EN][NPC]Surprisingly I can talk with certain enemies

### ISSUE THREAD

**Issue by luckylyrs** [Atlantiss/BugTracker#5072]
I cant take a Screenshot with my Mouse-Icon, but its the balloon-Icon, when I'm hovering the Mob.
![wowscrnshot_112915_214827](https://cloud.githubusercontent.com/assets/16072861/11460103/79c57370-96e6-11e5-9393-b4d93e90e990.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6866-5072-npc-frostmane-troll-whelp/
