### ISSUE TITLE
[PL][Talent][Rogue]

### ISSUE THREAD

**Issue by heekael** [Atlantiss/BugTracker#5075]
witam wcześniej niedzialalo mastery teraz odczuwam ze niedziala poprawnie  [Venomous Wounds] lub nadal buguje sie mastery strata dps 10k http://imgur.com/Yiewq8g na 360 ilev teraz max 20k  z 363 zmiana 3 itemow hc i zmniejszony dmg gdy szhaman ench z 320 ilev  bez hit capa robi wiecej ponad 20 k na  rhc na kukle staly 16-17k dps teraz na rogalu na burscie max dps to 20k staly 14-15k

**Comment by Lenox07** [comment]
https://github.com/Atlantiss/BugTracker/issues/4191

**Comment by Aviannaqt** [comment]
Zrób respec/reset talentow i sprawdz jeszcze raz, jak ostatnio byłem na BH rogalem to wszystko działało dobrze.

**Comment by heekael** [comment]
tak zrobilem reset talentow staly dps 13k .........
