### ISSUE TITLE
[PL][Spell][Warlock] Bane of Doom

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#5076]
link spell: http://cata.openwow.com/spell=603

Korzysta z haste a nie powinien. Powinien mieć stały 60sekundowy czas trwania i tickować co 15s, nastomiast w tej chwili sięga on 70+ sekund.

Problem musi dotyczyć Bl'a/Hero, ewentualnie Power Infusion i być może buffów od bossów, ponieważ testowałem na kukle i posiada standardowy czas trwania, zatem nie korzysta z haste z gearu.

**Comment by Quban** [comment]
Haste z gwaru nie dostaje na pewno co do pozostałych buffow proszę o jakiś dowód że skraca czas tickow

**Comment by Glare** [comment]
Nie napisałem, że skraca czas ticków tylko, że wydłuża czas trwania co nie powinno się dziać.

Jeśli nie znajdę chętnych do testowania na kukłach to załącze dowód dzisiaj w nocy po raidzie. Do tego czasu proszę nie zamykać.

**Comment by Glare** [comment]
Nvm, myślałem, że na BoD nie działa nowy system odświeżania dot. Wszystko ok.
