### ISSUE TITLE
[EN][QUEST][DUN MOROGH] MISSING IN ACTION

### ISSUE THREAD

**Issue by madethatway** [Atlantiss/BugTracker#5077]
http://cata.openwow.com/quest=26284 

Unable to open cage doors to free captured demolitionists - doors are permanently open and captured demolitinists simply say, "Greetings, <name>".

**Comment by Samineh** [comment]
Bump, Still bugged :+1:

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/4098
