### ISSUE TITLE
[PL][Spell][Class] Rogue

### ISSUE THREAD

**Issue by heekael** [Atlantiss/BugTracker#5080]
po dc niedziala dobrze mastery niewiem czy w rasie unded ale max dps na burscie 15k teraz ze zmiana 3 itemow na hc ... wczesniej 25k jakis miesac temu mialem ten sam problem wtedy mailem max 12k na odpaleniu  gdy shaman ench bez hit capa robi ponad 20++ dps ?? zmienialem talenty respec itp i nic nie dalo

**Comment by Reversion** [comment]
Aby udowodnić bug potrzeba więcej dowodów niż osobiste odczucia. Zrób jakieś wyliczenia, podaj wiecej szczegółów, wklej ssy.

**Comment by heekael** [comment]
zwiekszenie mastery nie przeklada sie na dmg jest taki sam gdy mam 40% i 79%

**Comment by Aviannaqt** [comment]
No jak wczoraj byłem na BH robiłem ponad 30k na odpalkach w 357 więc nie wiem...

**Comment by heekael** [comment]
wiesz ja juz mialem wczesnieja taki problem ze masterka byla bugnieta a rogal troll mial ok we 2 robilismy na kukle on mial ponad 20k a ja 12 a po ostatnich dc znowu cos niedzial jak ostatnio na bh na odpalkach to ja mailem 40k

**Comment by Kejmil** [comment]
to fajnie, zrob respeca i powiedz czy pomoglo

**Comment by heekael** [comment]
zrobilem reforg pod haste  http://imgur.com/a/IL2af i ..... o 1 k wiecej dps pod haste

**Comment by heekael** [comment]
respeca robilem zmienialem talenty i dupa

**Comment by Aviannaqt** [comment]
Wczesniej tzn. kiedy?

**Comment by heekael** [comment]
przed tymi dc co byly ostatnio

**Comment by heekael** [comment]
zmienialem rase na trola wydalem vp i tez dupa ... lub moje acc sie jebie niewiem sam juz

**Comment by heekael** [comment]
wiec sprawdzalem trinket 364 agi hc daje 164 mastery dmg z deadly posion z kolei 321 agi daje wartosc 148 dmg do deadly posion gdy trinket 321 mastery daje aby 36 dmg z deadly posion czyli 1,79 prawie 2% % daje aby 36 dodatkowego dmg z mastery ??

**Comment by Jenovas** [comment]
Radziłbym napisać ticket w grze i poprosić GMa w tickecie o list aura i zeby sprawdzil czy masz mastery, potem unaura all, po czym zrob relog.

**Comment by heekael** [comment]
ok wielkie dzieki za sensowna wkoncu odpowiedz pozdrawiam

**Comment by heekael** [comment]
wartosci mastery jak i ap wkoncu przekladaja sie jak powinny deadly posion dziala poprawnie temat do zamkniecia
