### ISSUE TITLE
[EN][Quest][Silithus] Securing the Supply Lines

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#5081]
http://www.wowhead.com/quest=8280/securing-the-supply-lines
The quest is missing from the game.

**Comment by Quban** [comment]
nope it isnt, all you have to do is to finish one of those:
http://www.wowhead.com/quest=28859/the-dunes-of-silithus
http://www.wowhead.com/quest=28856/the-sands-of-silithus

**Comment by Illusionist87** [comment]
Thx for info. But that is still a bug and I think the thread should not be closed.
Those 2 quests are breadcrumb quests same as Warchief's Command/Hero's Call quests (and I did Hero's Call one) and shouldn't be prerequisites for anything.

**Comment by Quban** [comment]
k ill fix that in next rev

**Comment by Sylvictus** [comment]
I just turned in "Dunes of Silithus" and the followup quest this thread is talking about is not showing up like you said should happen. But either way it's not supposed to be that way anyway as the quest is not a prerequisite.
