### ISSUE TITLE
Disarmed enhancement shamans can use all abilities

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5086]
![wowscrnshot_113015_202733](https://cloud.githubusercontent.com/assets/12395407/11508855/2db101ae-985b-11e5-9345-d7b430c82a5d.jpg)
Including stromstrike and lava lash. So it is absolutely pointless to disarm a shaman. Don't know if it is a bug or intended though.

**Comment by Kejmil** [comment]
warrior disarm doesn't remove offhand
