### ISSUE TITLE
[PL][Quest] [It's Time to Oil Up]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5088]
Gdy klikam na item przy baloniku nic sie nie dzieje a dodatkowo gdy klikne Esc pojawia sie wow error
http://www.wowhead.com/quest=28333/its-time-to-oil-up

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6819-wow-error-by-pressing-escape-after-using-item/

**Comment by krecik88** [comment]
Fixed in 5377
