### ISSUE TITLE
[EN][Warrior][Spell][Charge]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5089]
There are 2 issues with it. First and the most annoying: "NO PATH AVAILABLE".
![wowscrnshot_120215_102929](https://cloud.githubusercontent.com/assets/12395407/11527718/e52cdcc2-98e2-11e5-9de9-700ff32f3437.jpg)
![wowscrnshot_120215_103151](https://cloud.githubusercontent.com/assets/12395407/11527719/e52d3988-98e2-11e5-82c9-dfe45f1488cd.jpg)
![wowscrnshot_120215_103752](https://cloud.githubusercontent.com/assets/12395407/11527720/e5303674-98e2-11e5-9cb9-a3e12e811b90.jpg)
Even one millimeter ascent/descent can't be done with charge, the destination point has to be at the same level  as warrior. At the same time mages can blink on graveyard(!) in WSG and I can't follow them. I highly doubt it is blizzlike.
Second issue is pretty clear:
![wowscrnshot_120115_130715](https://cloud.githubusercontent.com/assets/12395407/11527856/a7eaa730-98e3-11e5-8ed0-f559e8dc5da1.jpg)
![wowscrnshot_120115_192947](https://cloud.githubusercontent.com/assets/12395407/11527857/a7fdf312-98e3-11e5-9779-1cd211e2c163.jpg)

**Comment by xolon** [comment]
the problem is in pathfinding not charge

**Comment by sigmundfreud2016** [comment]
ok, change the title then.

**Comment by Thefakemccoy** [comment]
This issue has been around for a while it not just warriors druids are the same way.

**Comment by sigmundfreud2016** [comment]
![wowscrnshot_120415_151136](https://cloud.githubusercontent.com/assets/12395407/11593304/dbe218e0-9aa3-11e5-908c-9dff8a8303e0.jpg)
![wowscrnshot_120415_162458](https://cloud.githubusercontent.com/assets/12395407/11593305/dbf3ccde-9aa3-11e5-81a9-145c30c61373.jpg)
With so bugged charge this class is currently unplayble. Make it work like a shadowstep or cat charge, just TPing to the target (not necessarily behind, just at the melee range of the target).
