### ISSUE TITLE
[EN][Quest] Razormaw

### ISSUE THREAD

**Issue by Atherill** [Atlantiss/BugTracker#509]
Here is the link to an article about this quest: http://www.wowhead.com/quest=9689
Razormaw can be summoned, however he doesn't land and cannot be attacked ("Invalid target"), he just passes by and flies away, then disappears.

**Comment by Duros** [comment]
Is this issue going to be fixed in next update? Because it's still bugged today.
He first flies away like described above, and after 20 sec or so, he reappears and is killed able.

**Comment by AnepaTuB** [comment]
still bugged Razormaw dont summon when i used bones on fire ;)

**Comment by Slotease** [comment]
Nov 21 2015 still bugged

**Comment by BehindTimesGame** [comment]
This quest is still bugged where Razormaw does not spawn when using the Bundle of Dragon Bones on the Ever-burning Pyre. Abandoned Quest and retried 3 times and still no spawn.

**Comment by Spatsa** [comment]
July 21, 2016, still bugged. No spawn at all.

**Comment by RobekX** [comment]
30 March 2017, still bugged. Not spawn

**Comment by roirraWedorehT** [comment]
Still bugged, won't summon.  Tried 3-4 times so far.

**Comment by Quroo** [comment]
The quest works. You have to wait a bit until Razormaw will land. He spawns in the air and flies to the fire where you have to use the quest item.
