### ISSUE TITLE
[PL][Other]Skill increased

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5091]
Od cata nie powinno juz tego byc 
![wowscrnshot_120215_020519](https://cloud.githubusercontent.com/assets/16046575/11531821/f4d0d8b4-98ff-11e5-80ec-d8b01c6dc57d.jpg)

**Comment by Kejmil** [comment]
to tylko visual

**Comment by vragni** [comment]
ale bug to bug jednak

**Comment by Quban** [comment]
fixed zapomnialem o tym napisac w ostatnim revie :dancer:
