### ISSUE TITLE
[PL][Quest] [Raging River Ride]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5097]
Po doplynieciu na miejsce zapadam sie pod tekstury
http://www.wowhead.com/quest=26769/raging-river-ride
![wowscrnshot_120215_182645](https://cloud.githubusercontent.com/assets/16046575/11538486/8f9ec8ca-9922-11e5-8719-1ca78bd0441d.jpg)

**Comment by magromo** [comment]
Potwierdzam, z tego co pamiętam trzeba się było wylogowaywać

**Comment by RastaTinu** [comment]
Robiąc dzisiaj tego q też wpadłem po textury, po czym musiałem wyjść z gry ALT+F4, a więc problem dalej jest.
