### ISSUE TITLE
[EN]Mobs going back

### ISSUE THREAD

**Issue by ajredinir** [Atlantiss/BugTracker#5100]
When i shoot a mob they come at me and then they go back again and when i hit them while going back it always evades... could you please fix it ?

**Comment by Thefakemccoy** [comment]
Not trying to sound like a smart a** but you know how many mobs are in the game. Linking the mob from wowhead or openwow that causes the issue help a lot. 

But what you are saying you are attacking a mob and he is running to far away from point of origin and resetting. If he is in reset mode running back to org spot he will always evade thats the way the game is.
