### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Fuselight, Ho!

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Atlantiss/BugTracker#5103]
Its fast but it takes you through the terrain and sadly it killed me.

http://www.wowhead.com/quest=27762/fuselight-ho#see-also

**Comment by karhima** [comment]
Confirmed, you end up dead and have a long walk from the graveyard.

**Comment by TranceAccount** [comment]
This works fine for me.
