### ISSUE TITLE
[PL][Item][Transmog] Transmog itemu Dragonheart Piercer na dowolny łuk.

### ISSUE THREAD

**Issue by kukukz** [Atlantiss/BugTracker#5108]
Nie da sie transmogowac Dragonheart Piercer
http://www.wowhead.com/item=63532/dragonheart-piercer
na bow.
Wedlug zasad transmogrifikacji powinno byc to mozliwe. 
Oto dowód :
http://us.battle.net/wow/en/forum/topic/3196342583
"
• Weapons must be the same weapon type (exceptions: Guns, Crossbows, or Bows)

• Guns, Crossbows, and Bows can be used to transmogrify Guns, Crossbows, or Bows.
"

**Comment by Aviannaqt** [comment]
#4581
