### ISSUE TITLE
[PL][Quest] [Reinforcements...]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5109]
Jak uzywam q itema na koboltach nic sie nie dzieje 
http://www.wowhead.com/quest=26066/reinforcements

**Comment by therealmikz** [comment]
+1

Tu jest filmik jak powinno to działać: https://www.youtube.com/watch?v=PUVSUP6I5DA

**Comment by RastaTinu** [comment]
Quest still doesn't work

**Comment by GamerSlew** [comment]
Quest doesn't work.
