### ISSUE TITLE
[PL][Other]Coiled Rope

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5111]
Po uzyciu liny powinienem zejsc na dol a nic sie nie dzieje 
http://www.wowhead.com/object=201707/coiled-rope
![wowscrnshot_120315_223717](https://cloud.githubusercontent.com/assets/16046575/11575780/3322901c-9a13-11e5-9206-de9eabb01d96.jpg)

**Comment by BAndysc** [comment]
Fixed
