### ISSUE TITLE
[PL][Npc]Bristleback Thornweaver

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5112]
Gdy atakuje te mobki sa evade i zostawiaja combat buga
http://www.wowhead.com/npc=3261/bristleback-thornweaver
![wowscrnshot_120315_230908](https://cloud.githubusercontent.com/assets/16046575/11575908/c823576e-9a13-11e5-91fa-8446e5723b98.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6865-5112-npcbristleback-thornweaver/
