### ISSUE TITLE
[EN][NPCs][Rep][Argent Dawn]Stratholme and Scholomance Mobs

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5113]
After 4.0.3 patch Stratholme and Scholomance Mobs do not give rep at all.On the server trashes stop give when you are exalted and all bosses give till 999 of exalted.Only way after cata to get rep are the 2 repeatable quests [Annals of the Silver Hand](http://www.wowhead.com/quest=28755/annals-of-the-silver-hand) and [Aberrations of Bone](http://www.wowhead.com/quest=28756/aberrations-of-bone) after you complete the Eastern Plaguelands quests.

Wowhead: [Argent Dawn](http://www.wowhead.com/faction=529/argent-dawn)
Dungeons: [Stratholme](http://www.wowhead.com/zone=2017/stratholme) and [Scholomance](http://wow.gamepedia.com/Scholomance_(original))

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7803-5113-reputation-stratholme-and-scholomance/
