### ISSUE TITLE
[EN][Item] Burnished Legplates of Might

### ISSUE THREAD

**Issue by immakoo** [Atlantiss/BugTracker#5114]
Burnished Leg plates of Might are free from the guild vendor

**Comment by Achievements** [comment]
According to mmo-champion, during wotlk and cata, Legs were not available anyway. They might have been in the files, but they were not purchasable in game till a later time. Even in 4.3 content. Legs are for some reason given to us, when they weren't in 4.1-4.3 retail, so appreciate that they're even there.

"Whereabouts Unknown: Heirloom Leg pieces (Not purchasable at the moment - 10% Experience boost)" - http://www.mmo-champion.com/threads/819091-The-Complete-Heirlooms-Guide-(WotLK-amp-Cataclysm) - Dec 26, 2010

4.3 was released on Novemeber 29, 2011. Here is another link, to 4.3's Wiki page with all updates 4.3 brought. - http://wowwiki.wikia.com/wiki/Patch_4.3.0
Still no pants.

**Comment by Thefakemccoy** [comment]
http://www.wowhead.com/item=69888/burnished-legplates-of-might

Added patch 4.1.0

**Comment by Achievements** [comment]
Yes, added, like I stated above, but not implemented in game. Check the comments within 4.0-4.3 time range and all say unknown. It was in the files but, it was not in retail. People got the listing from datamining.

**Comment by Achievements** [comment]
If you look at that wiki page, it says it's from the achievement Working as a Team. Gaining 600 skill points in all professions. A MOP achievement.

**Comment by Thefakemccoy** [comment]
They where added in cata purchasable in cata cause in MoP they added it so you could upgrade all the 1-80 gear to 1-85 gear with the previous item and more JP

**Comment by Achievements** [comment]
Ok. Tell me from which vendor they were purchasable in cata? From which achievement were they unlocked in cata? Which rep did you need or tournament to win? In cata.

**Comment by Thefakemccoy** [comment]
OK so after doing more digging you are right i can admit when i am wrong. They where added to the vendor in MoP but was datamined with 4.1.

**Comment by Achievements** [comment]
Fact is, pants were added to the files in 4.1, but like the brown polar bear mount, they were never released on live servers. If you deny that, you deny all comments on wow head from that period, and that wiki page you linked, which says it's from a MOP achievement. Heirloom pants were not implemented for purchase until MOP. The only lvl 85 heirlooms were helm and cloak from guild rep/achievements. They increased the possible lvl range via JP to make the 80 items useful again.

**Comment by Thefakemccoy** [comment]
But they cant just remove them now so they could atleast fix it so its not free.

**Comment by xolon** [comment]
http://community.atlantiss.eu/index.php?/topic/2987-434-leveling/

"
Therefore that blizzard already implemented the MoP herirloom trousers, we decided to give you the opportunity to buy the above-mentioned pants that will be availaible to buy it from the guild merchants for the amount of gold equal to the 1500 pieces of gold and for acquiring the achievement for having all professions at the maximum level of 525 skill points (equivalent to 600 skillpoints from Mists of Pandaria). "
