### ISSUE TITLE
[EN][Quest][Teldrassil] Druid of the Claw, Oden - Locked Door

### ISSUE THREAD

**Issue by TaleOf4Gamers** [Atlantiss/BugTracker#5116]
I have a quest to kill Obens body but I cannot as the door of which is body is behind is locked and it will not open. I have the Voodoo charm and I saw something somewhere about a key but I do not know.
Any help or clarification would be amazingly appreciated!

**Comment by Aival94** [comment]
This bug is already reported and i think it has all the info you provided.Next time better do a search if your bug is reported to see if it is on bugtracker or if there is a temporary fix as a comment.

https://github.com/Atlantiss/BugTracker/issues/643

**Comment by Quban** [comment]
> This bug is already reported and i think it has all the info you provided.Next time better do a search if your bug is reported to see if it is on bugtracker or if there is a temporary fix as a comment.
> 
> #643
