### ISSUE TITLE
[EN][Other] King Crawler

### ISSUE THREAD

**Issue by Romarez** [Atlantiss/BugTracker#5117]
Not found this mobs in feralas
http://www.wowhead.com/npc=51714/king-crawler

In the same place should be other mobs
http://www.wowhead.com/npc=51726/greater-roc
http://www.wowhead.com/npc=51752/oil-slime

**Comment by Atlntssplayer** [comment]
As of 2016 10 05, this is still unresolved. I checked the place in Feralas and there we no NPCs at all and after waiting there nothing spawned.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11838-5117npcking-crawler/

**Comment by TranceAccount** [comment]
@Bildo close
