### ISSUE TITLE
[PL][Npc]Innkeeper Lhakadd

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5118]
Nie da sie u niego ustawic HS
http://www.wowhead.com/npc=44276/innkeeper-lhakadd
![wowscrnshot_120415_004534](https://cloud.githubusercontent.com/assets/16046575/11593092/aa647eb2-9aa2-11e5-9eda-43dccc0eff32.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6864-5118-npcinnkeeper-lhakadd/
