### ISSUE TITLE
[PL][Other] Ravenwind

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5119]
Ten znacznik lewituje w powietrzu 
![wowscrnshot_120415_143417](https://cloud.githubusercontent.com/assets/16046575/11593154/fb6e913a-9aa2-11e5-8548-43283160c162.jpg)

**Comment by Navedonar** [comment]
fix https://community.atlantiss.eu/index.php?/topic/18354-other-ravenwind/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)
