### ISSUE TITLE
[PL][Dungeon - Cata] The Deadmines (Heroic)

### ISSUE THREAD

**Issue by hexerion** [Atlantiss/BugTracker#512]
Rev: 4018
Dotyczy: http://www.wowhead.com/zone=1581/the-deadmines
Po pierwszym wipie przy "Captain" Cookie (http://www.wowhead.com/npc=47739/captain-cookie) nie można wejść do dungeona. Wszyscy dostają powiadomienie w stylu "Can't enter when encounter is in progress", nawet gdy wszyscy są już martwi.

**Comment by qubuslabadz** [comment]
Fixed in rev. 4251
