### ISSUE TITLE
[PL][Quest]Might of the Stonemaul

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5120]
Gdy wchodze na ta arene pojawiaja sie 2 mobki w powietrzu , ogry i nic sie dalej nie dzieje 
http://www.wowhead.com/quest=25329/might-of-the-stonemaul
![wowscrnshot_120415_180157](https://cloud.githubusercontent.com/assets/16046575/11595798/82f1c7f4-9ab1-11e5-9a08-737c73b40f15.jpg)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1459
