### ISSUE TITLE
[PL][Core][Achievement] Honorable Kills

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5122]
http://www.wowhead.com/achievement=1151/loyal-defender
Criteria : 
50 honorable kills in the Hall of the Stormpike.

Obecnie na naszym serwerze zalicza tylko killing blow'y, a nie honorable kille, co bardzo utrudnia zdobycie tego osiągnięcia.

**Comment by Wolffenstein** [comment]
To core bug, jedno zgłoszenie wystarczy.

**Comment by Wolffenstein** [comment]
Fixed in rev 4684.
