### ISSUE TITLE
[PL][Achievement] Stormtrooper

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5123]
http://www.wowhead.com/achievement=213/stormtrooper#comments
Criteria : Kill 5 flag carriers in a single Eye of the Storm battle.

"This only requires HK's on flag carriers, not killing blows." 
"There is no requirement to pick up the flag. Just get HKs on 5 opposing team members who are carrying the flag." - Wowhead

Obecnie na naszym serwerze zalicza tylko killing blow'y, a powinno honorable kille, co jest utrudnieniem w zrobieniu tegoż osiągnięcia.

PS. #2544 , nie da sie zrobic mastera..

**Comment by Wolffenstein** [comment]
#5122
