### ISSUE TITLE
[PL][Achievement] Supreme Defender

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5124]
http://www.wowhead.com/achievement=1252/supreme-defender
Criteria : Kill 100 flag carriers in Warsong Gulch.
 
"You do not have to kill the flag carrier yourself, the flag carrier just has to be a honorable kill you recieve for it to count." - Wowhead.

Obecnie na naszym serwerze, zalicza jedynie killing blowy, a powinno honorable kille, przez co bardzo utrudnia to zdobycie achievementa.

**Comment by Wolffenstein** [comment]
#5122
