### ISSUE TITLE
[PL][Achievement] Not In My House

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5125]
http://www.wowhead.com/achievement=1251/not-in-my-house#comments
Criteria : Kill 2 flag carriers before they leave the Warsong Flag Room

Obecnie na naszym serwerze zalicza tylko killing blow'y a powinno honorable kille, co utrudnia zdobycie osiągnięcia.

**Comment by Wolffenstein** [comment]
#5122
