### ISSUE TITLE
[PL][Achievement] Save the Day

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5126]
http://www.wowhead.com/achievement=207/save-the-day
Criteria : Kill the enemy who is carrying your flag in the opposing team's flag room while the opposing team's flag is at their base, within their control.

Obecnie na naszym serwerze zalicza tylko killing blow'y a powinno honorable kille, co utrudnia zdobycie achievementa.
Dowód : https://www.youtube.com/watch?v=RPYT9QIkREE

**Comment by Wolffenstein** [comment]
#5122
