### ISSUE TITLE
[PL][Achievement] Soaring Spirits 

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5127]
http://www.wowhead.com/achievement=5214/soaring-spirits
Criteria : Kill 100 flag carriers in Twin Peaks.
"you just need to be in close enough range for the flag carrier to qualify as an HK to get credit for this achievement." - Wowhead.

Obecnie na naszym serwerze zalicza tylko killing blowy, a powinno honorable kille, co utrudnia zdobycie osiągnięcia

**Comment by Wolffenstein** [comment]
#5122
