### ISSUE TITLE
[PL][Achievement] I'm in the White Lodge 

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5128]
http://www.wowhead.com/achievement=5219/im-in-the-white-lodge
Criteria : In a single Twin Peaks battle, kill 2 flag carriers before they leave the Wildhammer Stronghold.

Obecnie na naszym serwerze zalicza tylko killing blow'y a powinno honorable kille. (podobnie jak na WSG)

**Comment by Wolffenstein** [comment]
5122
