### ISSUE TITLE
[PL][Achievement] City Defender

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5129]
http://www.wowhead.com/achievement=1006/city-defender#comments
"The only way around this requirement is if you're in a party/raid and one of your members gets the kill, in which case you will get credit even if you did no damage."

Obecnie zalicza tylko NASZE killing blow'y, a powinno zaliczac honorable kille, utrudnia to zaliczenie osiągnięcia.

**Comment by Wolffenstein** [comment]
#5122
