### ISSUE TITLE
[PL][Dungeon - Cata] The Lost City of the Tolvir 

### ISSUE THREAD

**Issue by hexerion** [Atlantiss/BugTracker#513]
Rev: 4018
Dotyczy: http://www.wowhead.com/zone=5396/lost-city-of-the-tolvir (normal)
Przy encounterze z Siamat (http://www.wowhead.com/npc=46753) gdy jedna postać zginie, boss zawiesza się/resetuje i jego hp nie spada. Nie wiem szczerze mówiąc co mogło to spowodować. Prawdopodobnie dotyczy drugiej fazy po zabiciu addów.

**Comment by qubuslabadz** [comment]
Fixed in rev. 4300.
