### ISSUE TITLE
[PL][Arena] Rating

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#5131]
Po odczekaniu około 7 minut w kolejce połączyło nas z teamem, który miał około 1200 MMR (mój team około 1900 MMR). Po wygranej dostałem +96 ratingu, team też +96, natomiast partner dostał normalną wartość.

**Comment by Hextall** [comment]
Kolejna wygrana arena tym razem MMR na prawie takim samym poziomie i znów +96 ratingu. Nie gram dalej :D

**Comment by Jenovas** [comment]
Nie jest to bug. Jest to zalozenie nowego systemu ktory jezeli widzi roznice miedzy mmrem / personalem / team rate wieksza niz 96 probuje jak najszybciej wyrownac je do siebie.

Kilka dni temu siedzialem z chlopakami grajacymi duzo aren i wymyslismy nowe wzory ktore beda ze tak powiem mniej inwazyjne a team rate / personal / mmr i tak bedzie sie wyrownywal tylko w nie tak drastycznych krokach tylko powoli.
