### ISSUE TITLE
[EN][Quest][Ruins of Ahn'Qiraj] Cloak of Unending Life(ID 8692)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5133]
Quest is given by NPC [Keyl Swiftclaw](http://www.wowhead.com/npc=15500/keyl-swiftclaw) normally but cannot be ended at all as npc do not have any kind of ? upon him(gray or yellow).
Furthermore the Quest mark on the maps is on the old location as during cata npc was moved outside the AQ ruins from Cenarion Hold.

Wowhead link: [Cloak of Unending Life](http://www.wowhead.com/quest=8692/cloak-of-unending-life)

Possibility of rest of the quests he give to not be able to end them. 
Wowhead Link: [NPC Starting quests](http://www.wowhead.com/npc=15500/keyl-swiftclaw#starts)

**Comment by Buggingtrack** [comment]
Still bugged the same way as it is today, the NPC [Keyl Swiftclaw](http://www.wowhead.com/npc=15500/keyl-swiftclaw) at the door of Ahn'Qiraji ruins simply doesn't accepts the completion quest despite being the same NPC that gives you the quest, and in the Cenarion Hold the NPC isn't present either

**Comment by Piklo** [comment]
should be fixed in [rev. 5613](https://atlantiss.eu/changelog#rev5613)
