### ISSUE TITLE
[EN][Object][Ruins of Ahn'Qiraj]Scarab Coffer(ID 180691)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5134]
Scarab coffers are totally missing from the server and the keys for opening them are the outdated version as during cata [Scarab Coffer Key(Old Version)](http://www.wowhead.com/item=21761/scarab-coffer-key) was replaced by [Scarab Coffer Key(New Version)](http://www.wowhead.com/item=76401/scarab-coffer-key) which can only be kept when you are in Ruins of Ahn'Qiraj and last only for 16 hours.

Wowhead link: [Scarab Coffer](http://www.wowhead.com/object=180691/scarab-coffer)
Note: These changes were done during 4.3 so sorry if you want to do it later.
Note2: The keys are droping only from bosses of AQ Ruins and not from the AQ Ruins trashes like the prev version.

**Comment by DuGalle** [comment]
still missing coffers keys drops properly now

**Comment by tomatosz** [comment]
bump

**Comment by ashrasmun** [comment]
https://community.atlantiss.eu/index.php?/topic/14404-5134-scarab-coffers/
