### ISSUE TITLE
[EN][Item]Blackrock Medallion(ID 11467)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5135]
Blackrock Medallion has been removed on patch 4.0.1 but it still drop on server.

Wowhead Link: [Blackrock Medallion](http://www.wowhead.com/item=11467/blackrock-medallion)
Wowpedia Link: [Blackrock Medallion](http://wow.gamepedia.com/Blackrock_Medallion)

![wowscrnshot_113015_040221](https://cloud.githubusercontent.com/assets/10282971/11605499/d7c8b80c-9b09-11e5-9ba6-6c0f7d9ae249.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6996-5135-itemblackrock-medallion/
