### ISSUE TITLE
[EN][Dungeon][Outlands]Blood Furnace

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5136]
Some of the mobs in Blood Furnace on normal are lvl 67-70.
When this is the 2nd starter dungeon for TBC.
I  think they are marked for Heroic version.
http://www.wowhead.com/npc=18894/felguard-brute

![wowscrnshot_120415_223507](https://cloud.githubusercontent.com/assets/12252441/11605965/018fc09a-9add-11e5-8f14-34d99de0dd3d.jpg)

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8146-5136npcfelguard-brute/
