### ISSUE TITLE
[EN][Druid][Balance] Master shapeshifter

### ISSUE THREAD

**Issue by Exertt** [Atlantiss/BugTracker#5140]
After the newest update, Master shapeshifter for balance druids still doesn't work.

![ss 2015-12-05 at 02 28 35](https://cloud.githubusercontent.com/assets/16023330/11607991/4fd13b0a-9b5d-11e5-8638-c991716f7269.jpg)

While it works in cat form.

![ss 2015-12-05 at 02 28 52](https://cloud.githubusercontent.com/assets/16023330/11607995/685b28fc-9b5d-11e5-8c2e-d0696b35ddbd.jpg)

And yes it is supposed to show up in the buffs for balance druids too http://i54.tinypic.com/aufgub.jpg

**Comment by Hordraric** [comment]
can confirm the problem. you know if its just visual bug or it doesnt even give the buff?

**Comment by Knerox** [comment]
The buff doesnt appear and there is no dmg increase for moonkin form (was testing this on dot ticks with and without the talent - no difference). The talent is working fine for cat, bear and caster/tree form.

**Comment by Jenovas** [comment]
I will take care of this probably today, thx for the report

**Comment by Jenovas** [comment]
Fixed in rev 4693

**Comment by Hordraric** [comment]
awsome gm, tyvm!!!!
PS: if possible, you should also try to fix to remove the flight form once we get swift flight :3 that would be 10/10 for druids
