### ISSUE TITLE
No forsaken catapults and forsaken mobs under ground

### ISSUE THREAD

**Issue by kry631** [Atlantiss/BugTracker#5142]
Like in the title:
![wowscrnshot_120515_161219](https://cloud.githubusercontent.com/assets/16166875/11608516/11adf7c8-9b6c-11e5-86db-d5ee480b8f47.jpg)
![wowscrnshot_120515_161204](https://cloud.githubusercontent.com/assets/16166875/11608517/11af1ef0-9b6c-11e5-8840-fee0cc47a431.jpg)
![wowscrnshot_120515_161207](https://cloud.githubusercontent.com/assets/16166875/11608518/11b4889a-9b6c-11e5-81a6-0738e1bbca18.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4685.
