### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by hardmen125** [Atlantiss/BugTracker#5143]
to talk to Rocco Whipshank not cooperate with the mission and one responds ah greetings

link Mission: http://www.wowhead.com/quest=13975/crossroads-caravan-delivery

video Mission: https://www.youtube.com/watch?v=x806X_oCs68

**Comment by coba999** [comment]
bump

**Comment by Xenerus** [comment]
https://github.com/Atlantiss/BugTracker/issues/3718
