### ISSUE TITLE
[EN][Quest][Gilneas][Two By Sea]

### ISSUE THREAD

**Issue by madethatway** [Atlantiss/BugTracker#5147]
http://www.wowhead.com/quest=14382/two-by-sea 

There are no catapults - unable to begin quest..

**Comment by Wolffenstein** [comment]
Rev 4685.

**Comment by rdoherty0** [comment]
Confirmed I cannot board the catapults, and therefore cannot complete the quest.

Worse, this means **Worgen are completely broken**, as you are phased on this island and cannot leave until the quest chain is done, and therefore cannot play the character anywhere else.

rev. 5302
