### ISSUE TITLE
[EN][Item]Greater Scarab Coffer Key(ID 76402)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5148]
The item during 4.3 patch was updated and the old version [Greater Scarab Coffer Key](http://www.wowhead.com/item=21762/greater-scarab-coffer-key) was replaced by this new version [Greater Scarab Coffer Key](http://www.wowhead.com/item=76402/greater-scarab-coffer-key) and will disappear if you leave the AQ Temple and last only for 16 hours.

Wowhead Link: [Greater Scarab Coffer Key](http://www.wowhead.com/item=76402/greater-scarab-coffer-key) 

NOTE: These keys are only dropping from AQ Temple and not from AQ Temple Trashes.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6995-5148-itemgreater-scarab-coffer-key/
