### ISSUE TITLE
[EN][Spell][Core][Vengeance]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5149]
In late Cata http://wowwiki.wikia.com/wiki/Vengeance_(tanking_bonus) was turned off in PVP for all tanking specs rendering them useless for anything but FC. Currently on Atlantiss Vengeance doesn't work in PVP only for protection warrior. But it does work for blood DK and druid (he promised to post his screenshot here soon). Protection paladin is not tested yet.
Vengeance should either work or not work for all tanks.
![wowscrnshot_120615_180918](https://cloud.githubusercontent.com/assets/12395407/11614601/84811e7a-9c47-11e5-8dc4-7e84be9ad58b.jpg)
![wowscrnshot_120615_183851](https://cloud.githubusercontent.com/assets/12395407/11614634/b826d598-9c48-11e5-8bf1-b4c9480f71a0.jpg)

**Comment by Thefakemccoy** [comment]
Veng shouldnt proc at all in PvP

**Comment by sigmundfreud2016** [comment]
Depending on the version. Looks like they nerfed only warriors, as always.

**Comment by Thefakemccoy** [comment]
The client it self is  4.3.4 the content is only up to 4.1
.

**Comment by sigmundfreud2016** [comment]
Then Vengeance should work for all tanks, including warriors.

**Comment by Thefakemccoy** [comment]
But the core of the game is 4.3.4 the content is 4.1

**Comment by Aival94** [comment]
The client is on 4.3.4.The content is on .4.1 and the spells and talents on 4.3.4 so this should be fixed.

**Comment by Thefakemccoy** [comment]
So no tanks should get vengeance from another player.
http://us.battle.net/wow/en/game/patch-notes/4-3-2

**Comment by metaldoctor** [comment]
Vengeance bugged and stacking for all tanks from hunter/warlock/mage and other pets attacks.

**Comment by sigmundfreud2016** [comment]
@metaldoctor I think it should work from pets (and Kill Command) as pets technically aren't players. They can be taunted as well, nobody uses it though.

**Comment by metaldoctor** [comment]
Pets technically must calculate like player in pvp, because with pet u can stack a lot of vengeance and then it will be same with out remove vengeance from pvp, like in 4.3.0 patch at retail when u can hit 50k+ for full ress ppl.

**Comment by Kejmil** [comment]
200ap=lot of vengeance, such hits, many (jk none) enrage dispels

**Comment by sigmundfreud2016** [comment]
@metaldoctor rogues do it without vengeance, so what? :D
We don't have to invent anything: if it worked from pets in 2012, it should work here too.
@Kejmil it was more, I made my screenshot a bit too late. In pair with heal against 3 DPS it's indeed possible to get maximum (10% HP), almost doubling the total AP. I never said I don't like, it's fair because rogues ignore armor, always have crazy damage + more avoidance from dodge + more CC + much more mobility + 2 vanisches. But blizzlike is blizzlike. And blizzlike means: no balance in PVP.

**Comment by Jenovas** [comment]
Fixed in rev 4693
