### ISSUE TITLE
[EN][Quest] Rifle the Bodies

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#515]
In the quest **Rifle the Bodies** (http://www.wowhead.com/quest=12000), you can loot one **Dead Mage Hunter** (http://www.wowhead.com/npc=26477) for various amounts of **Mage Hunter Personal Effects** (http://www.wowhead.com/item=35792).

Once I got 8 of them from one of these NPCs, and other time I looted, didn't get anything, and body disappeared.

You should be getting one **Mage Hunter Personal Effect** at a 100% rate, I believe, and then the body would disappear, after you loot it once.

**Comment by lanrutcon** [comment]
I had some problems with this quest.
When I grab it, I went right away to complete it, but for some reason whenever I right-clicked the NPC, they were just vanishing without giving any loot.

Then I went to complete another quests...and after a few of them completed, I decided to try this quest again, it had a totally different result, this time I was getting the loot but the NPCs weren't disappearing, so you could loot them over and over again.
Tested on the same mobs that I did before...

In the end, I had the same result as the OP.

**Comment by Hordraric** [comment]
im also having the problem of the body vanishing without giving loot
