### ISSUE TITLE
[EN][Item]Pattern: Devilsaur Leggings(ID 15772)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5151]
On 4.3 patch both [Pattern: Devilsaur Leggings](http://www.wowhead.com/item=15772/pattern-devilsaur-leggings) and [Pattern: Devilsaur Gauntlets](http://www.wowhead.com/item=15758/pattern-devilsaur-gauntlets) started to be sold from NPC [Nergal <General Goods>](http://www.wowhead.com/npc=12959/nergal) but on server only the [Pattern: Devilsaur Gauntlets](http://www.wowhead.com/item=15758/pattern-devilsaur-gauntlets) is being sold.

Wowhead Link: [Pattern: Devilsaur Leggings](http://www.wowhead.com/item=15772/pattern-devilsaur-leggings)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6994-5151-itempattern-devilsaur-leggings/
