### ISSUE TITLE
[EN][Quest][Twilight Highlands]Burnin' at Both Ends

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5153]
See plenty of barrles not really any one around but cant click barrels.

Quest
http://www.wowhead.com/quest=28597/burnin-at-both-ends
Item
http://www.wowhead.com/item=64585/cannon-powder

3 in one spot shiny and cant click any.
![wowscrnshot_120615_142824](https://cloud.githubusercontent.com/assets/12252441/11615114/abfe0e76-9c25-11e5-9888-54ab532d43b0.jpg)

**Comment by Wolffenstein** [comment]
Remove the quest, clear cache, pick it up again. It will be autocomplete until server restart.

**Comment by Thefakemccoy** [comment]
Thanks didnt have to delete cache though
