### ISSUE TITLE
[EN][Quest][Twilight Highlands]Once More Into The Fire(ID 27648)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5155]
Quest is bugged as when you speak with NPC [Cayden Dunwald](http://www.wowhead.com/npc=46174/cayden-dunwald) to start the event no event of him miving is starting.He seems to have stuck up somehow.

Wowhead Link: [Once More Into The Fire](http://www.wowhead.com/quest=27648/once-more-into-the-fire)
How it should work: https://www.youtube.com/watch?v=8bvyw_XBcAk

Edit: After a crash/restart of server it work perfect.

**Comment by Wolffenstein** [comment]
So you clicked the gossip to start the event and nothing happened?

**Comment by Aival94** [comment]
Yes.I clicked it.He said that is the spirit and he stayed there.I think 2 mobs who were there might cause sth like cb and he stuck as these 2 normally are dead and untargetable but they were targetable and alive.

**Comment by lourrific** [comment]
I can confirm this bug I clicked through all the dialogues to start the escort he says "lets go" but then he disappears and nothing happens.

**Comment by Aldergar** [comment]
I can confirm this too,no dialogue appeared to me,he just stood here for 2 minutes then he disappeared.

**Comment by Wolffenstein** [comment]
Did it work after he reappered?

**Comment by Aldergar** [comment]
need to check when server is back online

**Comment by Wolffenstein** [comment]
Added a few changes in rev 4690, might be better.

**Comment by Aldergar** [comment]
Still not working

**Comment by Aviannaqt** [comment]
rev. 4690  - Waiting for update

**Comment by Foggy0260** [comment]
Still bugged

**Comment by ffighter29** [comment]
Yea it is still bugged

**Comment by Prodiege** [comment]
You need to redo the report then

**Comment by Prodiege** [comment]
Can this be re-opened?

**Comment by Aival94** [comment]
Just make a new report if no other is open i suppose.

**Comment by Prodiege** [comment]
Why not just re-open it?

**Comment by Aival94** [comment]
Because devs usually do not see an already closed issue and the one who make it cannot reopen it if it is closed by a a dev.

**Comment by Prodiege** [comment]
Unless they unsubscribe to it manually every time they close a topic then they still see it
