### ISSUE TITLE
[EN][Rogue][Druid] Energy/Focus regen bug

### ISSUE THREAD

**Issue by TwigsInc** [Atlantiss/BugTracker#5156]
Saw a topic on this before, but it is closed. So I would like to reopen it on behalf of the fact that the bug is still present in game. Getting debuffs on attack speed, sends rogues and druids into negative energy/focus gains, which is not how it is supposed to work. Debuffs on attack speed also send haste into negative value, and no it's not visual.

Attack speed and Haste are not 1 and the same, and energy/focus regen should not be affected. Also I've tested SnD on rogue and the bug does not buff energy regen when I increase my attack speed, so I'm positive it's a bug. Might not be easy to fix, but it makes the 2 classes unplayable at times and breaks the experience of playing the classes in pvp and pve.

Thank you for your time, and keep up the good work you've done on the server.

**Comment by tnarf** [comment]
If im not mistake, that topic has been closed because main mechanics works well.
but some (maby most) skils are bugged and use wrong "old" mechanics.
to repair this devs need info what skils works bad.

**Comment by TwigsInc** [comment]
At 0 energy and no energy regen, no skills work obviously. As for opponents all bosses and mobs that i've encountered that have some sort of attack speed debuff bug my energy regen. My rogue is almost lvl 70 so i've played for a while just to make sure it's not just low lvl stuff and non important enemies.

**Comment by Wolffenstein** [comment]
Fixed in rev 4692.
