### ISSUE TITLE
[PL][Item]Bagi 16 slot w stolicach

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5160]
Te bagi z tego co pisze powinny byc dostepne dopiero od Revered a sa dostepne od poczatkowej repy
![wowscrnshot_120615_215420](https://cloud.githubusercontent.com/assets/16046575/11617129/ea288fd6-9c8a-11e5-9aa6-c07ed6b1d976.jpg)

**Comment by Thefakemccoy** [comment]
All the faction bags are like this for horde and alliance. I think they removed the rep to allow easier access to bags.

**Comment by Aviannaqt** [comment]
#4358
