### ISSUE TITLE
[EN][Quest][Twilight Highlands] Home Again

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#5162]
http://www.wowhead.com/quest=27650/home-again

You should be able to obtain this quest after completing:

Finding Beak http://www.wowhead.com/quest=27646/finding-beak
OR
Once More Into The Fire http://www.wowhead.com/quest=27648/once-more-into-the-fire

from any of the following NPC's:

Cayden Dunwald
Donnelly Dunwald
Eoin Dunwald

I have verified them all and they do not offer this quest. I have completed all prerequisites needed in order to obtain it.

This quest is needed to obtain Doing It Like a Dunwald http://www.wowhead.com/quest=27651/doing-it-like-a-dunwald it is critical in continuing Twilight Highlands quest progression.

**Comment by Wolffenstein** [comment]
Nope. You need to complete all Dwarven quests in Dunwald Ruins to receive this quest. See http://wow.gamepedia.com/Twilight_Highlands_quests for more info.
