### ISSUE TITLE
[EN][NPC][Twilight Highlands]Misty Merriweather

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5169]
Misty Merriweather is the leather trader in TH.
http://www.wowhead.com/npc=50381/misty-merriweather

The problem is he has a 333BoE on him for trade whe he shouldnt.

![wowscrnshot_120715_004900](https://cloud.githubusercontent.com/assets/12252441/11620002/5c83ac64-9c7c-11e5-9c0f-d4db5f457573.jpg)

**Comment by Thefakemccoy** [comment]
![wowscrnshot_120715_042806](https://cloud.githubusercontent.com/assets/12252441/11623450/f973ed0e-9c9a-11e5-9c62-869fcead2129.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4690.
