### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Quenching the Blade

### ISSUE THREAD

**Issue by Norfik** [Atlantiss/BugTracker#517]
In quest: http://www.wowhead.com/quest=10679 
the blade is not lootable -> http://wow.zamimg.com/uploads/screenshots/resized/103258.jpg

**Comment by Bildo** [comment]
rev. 4353 by Navedonar

**Comment by monibu** [comment]
rev. 4354 still not lootable

**Comment by ThordAelo** [comment]
bump

**Comment by Milton3450** [comment]
Still bugged.

**Comment by Milton3450** [comment]
Would really hope this is getting fixed for the dagger for my transmog. Why are GMs not able to auto complete the quest? Tried with a ticket.

**Comment by Bildo** [comment]
fixed
