### ISSUE TITLE
[EN][Item][Demonslayer][Transmog]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5172]
http://www.wowhead.com/item=13044/demonslayer can't transmog another 2H-sword into this item, when I press "apply" nothing happens, no error message, nothing.
![wowscrnshot_120715_114128](https://cloud.githubusercontent.com/assets/12395407/11624970/ab2bce2c-9cd7-11e5-84d7-4eff3be03ca9.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
