### ISSUE TITLE
[EN][Quest][Twilight Highlands] Warm Welcome

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#5178]
http://www.wowhead.com/quest=27485/warm-welcome

"Meet with Lirastrasza at Vermillion Redoubt. "

This quest is not available from NPC Lauriel Trueblade and I have down a total 84 quests in TH so far.

I have completed the "descent into madness" quest chain up to and including the quest "Nightmare" but I can not acquire the followup quest  "Warm Welcome" that starts off "Plight of the reds" quest line.

**Comment by Wolffenstein** [comment]
That's where the chain ends. It's not scripted yet.

**Comment by Raikurs** [comment]
When is this gonna be fixed?
