### ISSUE TITLE
[EN][Spell][Shaman] Unleash Elements

### ISSUE THREAD

**Issue by TheRealParadigm** [Atlantiss/BugTracker#5180]
Unleash Elements buff should fade off upon spell landing, instead of spell casting.

http://www.wowhead.com/spell=73683/unleash-flame

"You can use this AFTER casting Lava Burst and still get the Bonus Damage, but you have to be a fair distance away so it damages the target before Lava Burst lands."

**Comment by BialyADI** [comment]
Unleash Elements shoudnt Proc WindFury Weapon but it does...
And it Proc Maelstrom Weapon stack too.
Unleash Elements is just buged at all, overpowered.

**Comment by Bastion** [comment]
yeah 50k dps XD

**Comment by lamaATS** [comment]
https://web.archive.org/spell=73683/unleash-flame#comments

Here you can read the first commend:
```
You can use this AFTER casting Lava Burst and still get the Bonus Damage, but you have to be a fair distance away so it damages the target before Lava Burst lands.
```

BUT second comment says:
```
This has been changed recently, if I'm correct. The buff now applies at cast, rather than impact, much like the change to Flame Shock and Lava Burst - the buff needs to be active when the cast finishes, not prior to enemy impact.
```

So `the buff needs to be active when the cast finishes, not prior to enemy impact` if this is incorrect find some other proof (best will be video) where it works liek you said.
