### ISSUE TITLE
[EN][Spell][Shaman] Grounding Totem

### ISSUE THREAD

**Issue by TheRealParadigm** [Atlantiss/BugTracker#5181]
Grounding Totem should still work eventho you are not in the LoS of the totem.
Grounding Totem buff is listed as an aura : http://wowwiki.wikia.com/wiki/Aura
Following screens will show the bug (check buff/debuff) : http://imgur.com/a/sR9dS

**Comment by Jenovas** [comment]
Fixed in rev 4720
