### ISSUE TITLE
[EN][Talent][Shaman] Feedback

### ISSUE THREAD

**Issue by TheRealParadigm** [Atlantiss/BugTracker#5182]
Upon dying, any seconds that decreased Elemental Mastery cooldown will be reverted.

First screen, you can see the Elemental Mastery cooldown is about to reset : https://gyazo.com/48d98761abad9894a34e7acb7bcb0f29
Second screen, you can see I died and I released (grey screen) and the Elemental Mastery cooldown has been reseted as if Feedback didn't occur : https://gyazo.com/946016104318a1c175e7f6ab6d15813a

**Comment by aneq** [comment]
This is fixed now, @Aviannaqt close this please
