### ISSUE TITLE
[EN][Spell][Shaman] Fire Elemental Totem

### ISSUE THREAD

**Issue by TheRealParadigm** [Atlantiss/BugTracker#5183]
It's been reported but I want to bring attention to developers since it will be a core spell with the release of Firelands. (2P T12 bonus)

The damage from the elemental appears to be very low : 
Melee : Damage is fine.
Fire Nova : Not enough damage.
Fire Blast : Not enough damage.

At 0:15 timestamp in this video, you can see a small preview of the Fire Elemental damage.
https://www.youtube.com/watch?v=RwFU6JbKc9s
Fire Nova did 9k5 damage and Fire Blast did 4k1.

In this picture, I have dropped the Fire Elemental Totem with intellect procs. (it scales up, more intellect when you put the totem down, more damage)
http://imgur.com/a/k33ba

**Comment by aneq** [comment]
I'm sorry I know you mean well, but this submission is just low quality (and is a duplicate #3568 )
Everyone knows its bugged, you need to put in info about correct values (which I did in my previous submission)
The link in this guide can give someone wrong idea, but can be useful anyway.
At 0:45 we can see a shaman's unbuffed stats (10309 spellpower). At 1:39 we can see Fire elemental was used without any buffs (fire ele snapshots while summoned), so we can safely assume fire elemental inheritted exactly 10309 spellpower from the shaman. 
We can also see the fire elemental damage in floating combat text : elemental melee is 10k, fire blasts are 4.2k and fire nova is 9.5k
On 10309 spellpower, retail fire elemental melees for 10k, uses fire blast for 4.150k dmg and uses fire nova for 9.5k dmg.
Now let's take a look at atlantiss : 
On full procs my shaman has 13251 spellpower, roughly 3k more than the retail shaman 
Melee is 12k, roughly in the same ballpark but still bit too low
Fire blast hits for 3k  and fire nova hits for like 500 dmg
I have more spellpower during the summoning and fire blast hits for less. Atlantiss pls.
You can find simulationcraft formulas in #3568

**Comment by TheRealParadigm** [comment]
I'm a simple player, I'm not wanting to look for formulas because I'm not sure where to find them. I'm reporting the bug, even if it's a replica, because this bug is a major nerf to Elemental Shaman since months apparently, in both PvE and PvP, and will be even more with release of Firelands.

**Comment by fafal** [comment]
Doomguard dont work since new patch, dont think they will fix elemental also, probably not before 4.2 release

**Comment by Jenovas** [comment]
Fixed in rev  4703
