### ISSUE TITLE
[EN][Spell][Shaman] Earthquake

### ISSUE THREAD

**Issue by TheRealParadigm** [Atlantiss/BugTracker#5184]
Earthquake ticks consume Elemental Focus buff, Clearcasting.

Negatør's Earthquake hits Heroic Training Dummy for 796 Physical.
Negatør's Lava Burst hits Heroic Training Dummy for 27758 Fire.(Critical)
Negatør gains Negatør's Clearcasting.
Negatør's Earthquake hits Heroic Training Dummy for 877 Physical.
Negatør's Earthquake hits Heroic Training Dummy for 877 Physical.
Negatør's Clearcasting fades from Negatør.

However the buff Arcane Concentration for Mage works fine, Flamestrike ticks doesn't consume Clearcasting.

**Comment by lamaATS** [comment]
Fixed in rev. 4805 (missing close)
