### ISSUE TITLE
[EN] [Quest][Nagrand]Not On My Watch!

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5185]
So I have never had any issue with this quest before till now.

Whats wrong.:
Lump spawns in asleep like he should but then just despawns as soon as you can target him.

Quest Link:
http://www.wowhead.com/quest=9918/not-on-my-watch

NPC:
http://www.wowhead.com/npc=18351/lump

I even tried to sit on top of him to put him in combat to see if he would stay and he just despawned on me.

**Comment by Thefakemccoy** [comment]
I made a short video as prof of what I see. Its only about 8secs long but you can see him spawn in and out.

https://youtu.be/VXvBrnWEUrs

**Comment by tantyk** [comment]
up

**Comment by Thefakemccoy** [comment]
IDK if this quest was fixed but i just did it on an alt.

**Comment by micha666** [comment]
Still had that bug.

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/3674
