### ISSUE TITLE
[ENG][Other]Statless items can't be transmogrified

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#5192]
Title says it all really. No bug message or anything of the sort shows up, nothing happens when you click the "Apply" button, that's all. I'm pretty sure this is not intended considering that in retail statless items were always able to be transmogrified. 

For the sake of illustration, I should be able to transmog my Soulblades into http://www.wowhead.com/item=1728/teebus-blazing-longsword. This is making me really sad.

**Comment by sigmundfreud2016** [comment]
https://github.com/Atlantiss/BugTracker/issues/5172
