### ISSUE TITLE
[EN][Quest][Twilight Highlands] Doing It Like a Dunwald

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#5194]
http://www.wowhead.com/quest=27651/doing-it-like-a-dunwald

"Speak to Flynn Dunwald and aid the Dunwald brothers in killing Darunga."

this is new post after restart with latest revision implemented :

At least now I can get the quest from NPC but when I got to location flynn dunwald doest not have event trigger dialogue and darunga is there but evades attacks. can not complete quest.

**Comment by Deadlyblonde** [comment]
Bump!

**Comment by Illusionist87** [comment]
still bugged

**Comment by Wolffenstein** [comment]
I'll fix it tomorrow.

**Comment by Wolffenstein** [comment]
Fixed in rev 4704.
