### ISSUE TITLE
[EN][QUEST][TWILIGHT HIGHLANDS}[Enter the dragon Queen}

### ISSUE THREAD

**Issue by rafal363** [Atlantiss/BugTracker#5195]
missing npc "Lirastrasza"

**Comment by Wolffenstein** [comment]
It's not scripted.

**Comment by artamedan** [comment]
For the Horde, the correct name of the quest leading to Lirastrasza is "Warm Welcome". This quest is given by Golluck Rockfist after we turn in the quest "Nightmare" to Earthcaller Torunscar.
[http://www.wowhead.com/npc=48264/golluck-rockfist](url) We should be grabbed and taken by a red dragon to Lirastrasza.
This quest is missing on the NPC and all the chain and mobs are missing in Vermillion Redoubt.

**Comment by XrayAlert05** [comment]
Missing NPC, what were you guys doing all year?

**Comment by worloq** [comment]
still doesn't work

**Comment by rdoherty0** [comment]
NPC still missing
