### ISSUE TITLE
[EN][Spell][Druid] Bear Charge

### ISSUE THREAD

**Issue by fizzle7** [Atlantiss/BugTracker#5197]
Bear Charge gives "No path available" on horizontal surfaces with nothing in between like outside SW dueling area. Apparently people are telling me it happens 15% of the times but to me it's like 90%. Won't even comment on how much it breaks ferals nor anything else. This is for PvP, charge works on dummies.

**Comment by sigmundfreud2016** [comment]
https://github.com/Atlantiss/BugTracker/issues/5089
At least you can respec to cat and enjoy your "shadowstep charge". Warriors don't have choice.

**Comment by fizzle7** [comment]
Well, it's funny you say that cause cat leap doesn't work properly either, it should put you behind your target, but it doesn't.
