### ISSUE TITLE
The Darkmoon Faire should be available

### ISSUE THREAD

**Issue by Zombarian** [Atlantiss/BugTracker#5198]
The Darkmoon Faire is said to start on the first Sunday of every month, so it should be available, but for some reason it doesn't. I have searched all over for the DMF portal and for the lady and found nothing.

Could i please get an answer on how to join it.

Thanks!

**Comment by Thefakemccoy** [comment]
DMF is still pre 4.3 so you have to go find it

**Comment by Zombarian** [comment]
What do you mean go find it?

**Comment by Luna-maria** [comment]
it's either in mulgore, elwynn forest or terokkar forest

to my best knowledge it's in mulgore right now
