### ISSUE TITLE
this mission is bug secrets of the tower

### ISSUE THREAD

**Issue by orki777** [Atlantiss/BugTracker#5199]
The next mission : secrets of the tower you can find in westfall for Agent Kearnen

when you walk into the tower no npc to complete the mission.although you enter with potion putting.
and that mission is needed to do more. Please repair this problem I hope that answer me as soon as possible

**Comment by Thefakemccoy** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/2338

**Comment by Thefakemccoy** [comment]
But you can complete it i have done it on every char i lvled

**Comment by Anhaeyn** [comment]
Recently I did this quest. Enter the tower, tag yourself, use potion to become invisible, go upstairs till the end of stairs and should be triggered conversation, after which your quest should be completed. 

Btw - you need to put link to the quest from wowhead.
