### ISSUE TITLE
[EN][NPC]Highbank Marksman

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5200]
IDK why these guys all of a sudden poped up in Kirthaven but wow.

http://www.wowhead.com/npc=49366/highbank-marksman
![wowscrnshot_120915_015617](https://cloud.githubusercontent.com/assets/12252441/11678705/30c85ca8-9e18-11e5-8379-1d33d9ba1057.jpg)

**Comment by Thefakemccoy** [comment]
Seems like they are walking up here i just passed more headed tot hat spot.

**Comment by Thefakemccoy** [comment]
![wowscrnshot_120915_021610](https://cloud.githubusercontent.com/assets/12252441/11678981/f026e874-9e1a-11e5-91ca-027f36a189a1.jpg)

**Comment by Thefakemccoy** [comment]
![wowscrnshot_120915_022052](https://cloud.githubusercontent.com/assets/12252441/11679061/7dd2b40a-9e1b-11e5-8632-fd59752b9880.jpg)

**Comment by Wolffenstein** [comment]
Annual Highbank Marksman Meeting

**Comment by Wolffenstein** [comment]
Should be fine now.
