### ISSUE TITLE
[PL][Npc]Honor Hold Gryphon Brigadier, South

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5208]
Te mobki sa masowo w jednym miejscu i sie palą
http://www.wowhead.com/npc=21170/honor-hold-gryphon-brigadier-south
![wowscrnshot_120915_171253](https://cloud.githubusercontent.com/assets/16046575/11692459/d6f99934-9e9f-11e5-946a-cf8f21ccffe2.jpg)

**Comment by aje** [comment]
they disapeared so bug resolved :)
