### ISSUE TITLE
[EN][Holy conecentration, Priest]

### ISSUE THREAD

**Issue by zfhdza** [Atlantiss/BugTracker#5210]
Holy concentration of holy priests doesn't work.I tried (in combat) with and without the talent and it took me the same time to get all mana back

**Comment by Aviannaqt** [comment]
![wowscrnshot_121015_164805](https://cloud.githubusercontent.com/assets/6614173/11720099/1606428a-9f5e-11e5-8eec-bec3edf75e80.jpg)
![wowscrnshot_121015_164801](https://cloud.githubusercontent.com/assets/6614173/11720100/160d2816-9f5e-11e5-9eed-8efb5472b452.jpg)

**Comment by zfhdza** [comment]
Yep, I looked that before I posted the issue but as I said It took me the same time to get all the mana back:

0/2 1:52
1/2 1:52
2/2 1:52

Of course in combat.

**Comment by Aviannaqt** [comment]
Hmm.. i will test it later.
