### ISSUE TITLE
[EN][Quest] To New Thalanaar

### ISSUE THREAD

**Issue by rasmodeus** [Atlantiss/BugTracker#5211]
I am unable to take the flight from Dyslix Silvergrub in Mudsprocket.  I get an error stating I am too far away from the taxi. I tried several spots, even right on top of him. The quest's map location is not centered on Dyslix either.

**Comment by Wolffenstein** [comment]
Fixed in rev 4700.

**Comment by reapertg** [comment]
If this was fixed, it has become and issue again. Best to open a new report or can closed ones be re-opened?
Thanks
