### ISSUE TITLE
[PL][Quest]Arelion's Secret

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5215]
Ten npc jest zle oznaczony na mapie 
http://www.wowhead.com/quest=10286/arelions-secret
![wowscrnshot_121015_165056](https://cloud.githubusercontent.com/assets/16046575/11720217/9d3a48fa-9f5e-11e5-8c7f-c0d3b33234f7.jpg)

**Comment by aje** [comment]
this NPC as a path that's why. this is not a bug, this is the same on retail
look here http://www.wowhead.com/npc=20159/magister-aledis

**Comment by hawcik** [comment]
This npc is bugged. He is walking under ground:
![wowscrnshot_091616_144224](https://cloud.githubusercontent.com/assets/22025866/18586213/d4fc6cb0-7c1b-11e6-8858-33598b9a2724.jpg)

U have to wait sometime till he will go up to the ground.
