### ISSUE TITLE
[EN][Other] Crossbow/Guns Transmogrification 

### ISSUE THREAD

**Issue by Shirofune** [Atlantiss/BugTracker#5218]
Hello.

Since the release of the transmogrification function, in retail, you were able to transmogrify Guns/Crossbows/Bows into one of the other category, no matter which one.

On Atlantiss, you can transmogrify a gun into a crossbow and viceversa, but you can't do that bows. (Bows only allow to be xmog into bows themselves)

That's the bug. You should be able to transmog a crossbow and a gun into a bow, and viceversa.

Retail link confirming it: http://us.battle.net/wow/en/forum/topic/3196342583

• Guns, Crossbows, and Bows can be used to transmogrify Guns, Crossbows, or Bows.

The topic dates of September, 2011. MoP launched on September, 2012, so this dates of the actual 4.3.4 in Retail.

I know this is a repeated issue, but the other one was closed for no reason, and this is an actual and confirmed bug.

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
