### ISSUE TITLE
[EN][Spell][Warrior][Deadly Calm][Execute]

### ISSUE THREAD

**Issue by Morderczyk** [Atlantiss/BugTracker#5219]
http://cata.openwow.com/spell=85730
http://cata.openwow.com/spell=5308

When i use execute with deadly calm, execute is not free(20 rage cost)

**Comment by Jenovas** [comment]
http://us.battle.net/wow/en/forum/topic/2089270021

Deadly calm only removes the base cost. It's been like that since it's inception.

**Comment by goalien** [comment]
greeting team. I think the spell execute is not working properly. on the spell says he spends 10 rage, but it consumes up to 50-30 rage.
  Is this a bug?
