### ISSUE TITLE
[EN] [Quest] [Hellfire Peninsula] Invading the Citadel

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5222]
The NPC http://www.wowhead.com/npc=19309/sergeant-altumus
should give the quest http://www.wowhead.com/quest=29543/invading-the-citadel#comments but she does not.

**Comment by Aldurion** [comment]
Note: This quest was added in patch 4.3.0

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12545-5222quest-hellfire-peninsula-invading-the-citadel/
