### ISSUE TITLE
mother sharaz 

### ISSUE THREAD

**Issue by immakoo** [Atlantiss/BugTracker#5223]
shoots u up in the air when soloing making it impossible which is extremely annoying because i want the shoulders from this boss but i cant solo cause u die three times after being shot in the air

**Comment by Lanrutcon** [comment]
Working as intended.
https://youtu.be/CAsGBT0kWzU?t=4m1s

**Comment by immakoo** [comment]
sorry i didnt c it on the youtube videos i watched. how can i avoid it?


________________________________

**Comment by Achievements** [comment]
Tank her in the doorway to her right. you'll only bounce ~10 yards.

**Comment by immakoo** [comment]
ty sorry for bothering


________________________________
