### ISSUE TITLE
[EN][Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#523]
**Workaround for this quest for players**:
*Summon the gryphon, get on him, go near the flight master and use the 2nd ability, "Drop Off Villager"*

Okay, on to the report now.

In the quest **Flight of the Wintergarde Defender** (http://www.wowhead.com/quest=12237) there are several issues.

- You can't fly with gryphon summoned by the quest provided item, **Wintergarde Gryphon Whistle** (http://www.wowhead.com/item=37287), if you do try to press space key to ascend, you'll just get stuck in air, barely able to move.

- Even if the gryphon worked, all the **Helpless Wintergarde Villagers** (http://www.wowhead.com/npc=27336) are missing. They should be running around in fear, just outside of the quest hub in **The Carrion Fields** mainly, but there's none to be found.

- And of course, the bug that I mentioned as a workaround for now. If you just summon the gryphon and go near the quest giver, and use the 2nd ability of the gryphon, **Drop Off Villager**, you will get the quest count, even though you have no villager to drop off.

Here's the video of the quest: https://www.youtube.com/watch?v=3MHyoWDaLJQ

**Comment by Dexobox** [comment]
The Workaround does not work anymore :(
