### ISSUE TITLE
[PL][Guild][Achievement] Realm First

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5231]
[Sinestra](http://www.wowhead.com/achievement=5411/realm-first-sinestra)
[Nefarian](http://www.wowhead.com/achievement=5409/realm-first-nefarian)
[Al'Akir](http://www.wowhead.com/achievement=5410/realm-first-alakir)
[Level 25](http://www.wowhead.com/achievement=5407/realm-first-guild-level-25)
[Working as a Team](http://www.wowhead.com/achievement=5408/realm-first-working-as-a-team)

Każda gildia dostaje te osiągnięcia.
- 3 pierwsze osiągnęła gildia Amicorum
- Level 25  osiągnęła gildia Apocalypse Raiders
- Ostatni nie wiem kto zdobył jako pierwszy

**Comment by Porobiony** [comment]
Ultimate Destiny

**Comment by Kejmil** [comment]
a jesli uwzglednic buga to ostatni tez powinna miec apo :P

**Comment by BAndysc** [comment]
Since 5148 guild will no longer earn Realm First achievements, I will remove incorrect achievements in the nearest days

**Comment by Aival94** [comment]
Is not this one fixed already?

**Comment by Aviannaqt** [comment]
@pelekon do zamkniecia
