### ISSUE TITLE
[PL][Quest][Hillsbrad Foothills] Stormpike Rendezvous

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5233]
http://www.wowhead.com/quest=28348/stormpike-rendezvous
Filmik nie działa za dobrze. Brak postaci oraz tekstów
https://www.youtube.com/watch?v=WQlMiy5DvQA

**Comment by BAndysc** [comment]
Coś musiało się w tym jednym przypadku zbugować z fazami, całość niedawno skryptowałem.

**Comment by worloq** [comment]
filmik nadal niedziela ale quest da się zrobic

**Comment by BAndysc** [comment]
Czy byłeś może na mouncie gdy miała odpalić się scenka?
