### ISSUE TITLE
[PL][Quest][Hillsbrad Foothills] Stagwiches

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5235]
http://www.wowhead.com/quest=28489/stagwiches
http://www.wowhead.com/npc=48184/hill-stag -zostają zabijane przez inne npc przez co długo się wykonuje ten quest.Powinny sięporuszać

**Comment by BAndysc** [comment]
"Not convinced this quest is worth it - it took around 30 minutes to complete. The Stalkers far outweigh the stags and the respawn rate of Stalkers is ridiculous. About half the time I couldn't loot the stags (even ones that hadn't been attacked by Stalkers)."
