### ISSUE TITLE
[PL][Achievement][I Hate That Song]

### ISSUE THREAD

**Issue by rafal363** [Atlantiss/BugTracker#5241]
raid achievement pisze ze achiev zostal zaliczony i mozna zabic bossa,po jego zabiciu nie dostajemy achieva

**Comment by Bildo** [comment]
lol to nie jest zaden dowod

**Comment by Bildo** [comment]
poza tym przeczytaj zasady bug trackera

**Comment by Assiria** [comment]
od 3 resetow probuje zrobic achiva i taka sama sytuacja jak na gorze, 5 stackow debuffa i banka schodzi pod wplywem interrupta, powtarzamy, znowu to samo i achiv powinien wskoczyc po zabiciu bossa, lecz tak sie nie dzieje.
