### ISSUE TITLE
[PL][Quest] [Gammothra the Tormentor]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5244]
Po uzyciu itemka na mobku dalej jest jako elita 
http://www.wowhead.com/quest=11721/gammothra-the-tormentor
![wowscrnshot_121215_154313](https://cloud.githubusercontent.com/assets/16046575/11762580/4f668cf4-a0eb-11e5-88b9-3bdc98ff6573.jpg)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2371
