### ISSUE TITLE
[PL][Quest] Early Adoption 

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5246]
http://www.private-status.com/39,1,405,55317/

Q nie działa po pierwszym mobie wiecej sie nie spawnuje jajko potem znika.

jak to powinno wyglądac: https://www.youtube.com/watch?v=YXCtEdUOEv0

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1492
