### ISSUE TITLE
[PL][Core][Healer] aggro

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#5248]
Healerzy robia zbyt duże aggro, 3 death strike nie wystarczają żeby przebić aggro na przykład holy paladina po judgemencie

**Comment by Kejmil** [comment]
death strike konsumuje runy nawet jak nie trafisz, paladyn moze miec wlaczonego RFa...

**Comment by Piklo** [comment]
kazdy death strike byl trafiony, wszyscy robili respeca i reloga i dalej healerzy robia za duze aggro

**Comment by Aviannaqt** [comment]
Nie wiem czy to przypadek, ale już kilka osób do mnie pisało dlaczego przebija aggro healem, może coś jest na rzeczy :p

**Comment by VinidVeryou** [comment]
Healerzy resetuja aggro przy uzyciu m. in. Judgement, Chain heal. Sprawdzane na Omnotron Defense System Hc , ciagla utrata aggro na tankach, ciagle tauntowanie. Pozdrawiam.

**Comment by Reversion** [comment]
Co do Omno to problem leży w encounyerze ponieważ występuje tylko w wersji hc gdzie threat jest resetowany po każdej zmianie bosa. Na normie nie ma tego problemu bo się nie resetuje. Po za tym wartości threatu są śmieszne. Po 30 sekundach od pula  i 2 retauntach taki miały po 20k threatu. IMO problem leży po stronie encounterow nie klas. Jak był by problem z klasami na każdym bosie były by jazdy.
