### ISSUE TITLE
[ENG][Other]Statless items still can't be transmogrified

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#5252]
-Re-opening because as of rev 4707 it still isn't working-

Title says it all really. No bug message or anything of the sort shows up, nothing happens when you click the "Apply" button, that's all. I'm pretty sure this is not intended considering that in retail statless items were always able to be transmogrified.

For the sake of illustration, I should be able to transmog my Soulblades into http://www.wowhead.com/item=1728/teebus-blazing-longsword. This is making me really sad.

**Comment by Wolffenstein** [comment]
Can you provide a link to the item you're trying to transmog?

**Comment by Bastion** [comment]
http://www.wowhead.com/item=59521/soul-blade
chyba to

**Comment by Wolffenstein** [comment]
Fixed in rev 4709.
