### ISSUE TITLE
[EN][TALENT][MAGE] LIVING BOMB 

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#5254]
It should not explode when dispeled but it does 
http://cata.openwow.com/spell=44461
http://wow.gamepedia.com/Living_Bomb  -----------> "No longer explodes when dispelled".

**Comment by blinkmaster** [comment]
+1 already noticed Jenova about that yesterday

**Comment by Jenovas** [comment]
Fixed in rev 4714
