### ISSUE TITLE
[EN][cinematic][Gilneas]Worgen Transformation

### ISSUE THREAD

**Issue by DanielMan191** [Atlantiss/BugTracker#5256]
The cinematic is broken :(
![wow_434 2015-12-13 21-54-14-17](https://cloud.githubusercontent.com/assets/16239982/11768937/83e2a1da-a1e4-11e5-8b06-05ff20b1a6a4.jpg)

**Comment by DanielMan191** [comment]
why u closed

**Comment by BAndysc** [comment]
You are playing on mini-client and you do not have cinematics downloaded. It is not a server bug.
