### ISSUE TITLE
[PL][Other]The Geyser Fields

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5262]
Na tym terenie kazdy mechaniczny mob jest podatny na dzialanie skillow bleeding
![wowscrnshot_121315_234113](https://cloud.githubusercontent.com/assets/16046575/11770396/3a90df88-a1fd-11e5-9be7-841b389a3fc1.jpg)

**Comment by aje** [comment]
Just tested on retail and they bleed. This is intended
