### ISSUE TITLE
[PL][Warlock] Drain Life

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5267]
Drain Life bije za wiele, sprawdzałem to Addonem DrDamage.
Wiem że to tylko Addon ale zazwyczaj się sprawdza, test robiłem bez talentów.
Drain Life powinienem bić za ~1000 lecz biłem ~1400 wiec różnica jest dośc spora dlatego to zgłaszam.
Prawdopodobnie coeff jest nie poprawny a powinien wynosić 0.387.

**Comment by Jenovas** [comment]
Dowody, liczby, link do spella.
Zamykam.
