### ISSUE TITLE
[EN][Core] Player movement Bug

### ISSUE THREAD

**Issue by Pvt-8Ball** [Atlantiss/BugTracker#5268]
There's a bug regarding the movement of other players where a stutter will systematically happen every second or so, it's a rubber banding effect of sorts. It can be seen here:

https://youtu.be/yv0bWKmzO_0?t=46

Focus on the Shaman and Druid who are running in circles, they will rubber band back and forth, this behavior is seen on pretty much every player. Player movement was definitely not like this during retail Cataclysm.

This issue doesn't seem to be caused by anything client side, I have friends who can confirm the exact same thing happens to them. So it leads me to believe it's a bug in the Server's core.

I noticed this bug is apparent on many servers, however, I've observed that it seems to be fixed within Trinity Core, so maybe a fix can be found from there, I'm no expert though.

Maybe this helps too https://www.worldofcorecraft.com/comment/940#comment-940, although I leave that up to you to decide. I think that's how the fixed the same bug in CoreCraft.

**Comment by Wolffenstein** [comment]
The fix you provided is over 2 years old, and doesn't quite correspond to what we have in core now. The logic is fine, but that's not entirely what we're looking for.


I did, however, manage to spot something that might cause this issue and did a few changes that will be applied in rev 4712. Please provide me with some feedback when it's live on the main server.

**Comment by Thefakemccoy** [comment]
Its worse riding on a 2 person mount.

**Comment by Pvt-8Ball** [comment]
Can confirm the fix worked, thanks so much, I can't believe how quickly you fixed it.

I'm Atlantiss WoW Fanboy now, I've been converted.

**Comment by Pvt-8Ball** [comment]
This might actually want to be re-opened, since the fix was reverted.

**Comment by syrobee** [comment]
This is still an issue.

**Comment by Pvt-8Ball** [comment]
Bump - as of current this is still an issue.

Thanks.
