### ISSUE TITLE
[PL][Npc]Riplash Sorceress

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5271]
Ten Npc powinien byc martwy
![wowscrnshot_121415_022457](https://cloud.githubusercontent.com/assets/16046575/11789251/9d1498e6-a295-11e5-86e5-d9d23be6e408.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6860-5271-npcriplash-sorceress/
