### ISSUE TITLE
[PL][Npc]Solid Ice

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5273]
Atakuje mnie jak by to byl normalny mob
http://www.wowhead.com/npc=84548/solid-ice
![wowscrnshot_121415_163721](https://cloud.githubusercontent.com/assets/16046575/11789391/684d6150-a296-11e5-91a3-1d560dc12c10.jpg)

**Comment by Aviannaqt** [comment]
#2926
