### ISSUE TITLE
[PL][Npc]Umbranse the Spiritspeaker

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5274]
Ten npc jest out of range 
http://www.wowhead.com/npc=8588/umbranse-the-spiritspeaker
![wowscrnshot_121415_175024](https://cloud.githubusercontent.com/assets/16046575/11789455/c754e358-a296-11e5-9e92-887a0cedc8de.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6859-5274-npc-umbranse-the-spiritspeaker/
