### ISSUE TITLE
[EN][Spell][Death Knight[GearBonus] DK's gear bonus doesn't work

### ISSUE THREAD

**Issue by bewiserdude** [Atlantiss/BugTracker#5276]
Bonus from 4 piece of Bloodthirsty Gladiator's set doesn't work. It should regenerate 3 Runic Power every 1 sec for 5 sec whenever you are struck by a movement-impairing effect.
http://www.wowhead.com/item=64735/bloodthirsty-gladiators-dreadplate-chestpiece

**Comment by Kaspi92** [comment]
The 4set bonus for DK's still does not work.

Sniprep and me tested classes /specs on which it does actually proc.
http://pastebin.com/Nthjapjq

here is the spell-ID: http://www.wowhead.com/spell=61258

The 4set should proc by all movement impairing effects (which are slows, stuns, roots). At the moment it only works on a few specific spells (mentioned above in the pastebin).

**Comment by kadi2** [comment]
There are several spells that it shouldn't proc from, like desacration, ice trap. I always was pretty sure that it shouldn't proc from stuns. Can someone confirm this?

**Comment by kadi2** [comment]
I just found out that it didn't proc on cheapshot on this movie so it should just proc from roots and slows. You can notice crippling poison procing the talent in this movie aswell.
https://youtu.be/ETAtbKHyuaA?t=1m

**Comment by lamaATS** [comment]
If you will look on those spells on the list you maybe get that all spells on the list dealing damage and when I checking this probably this is a problem I will check it tomorrow.
About Stun effects like @kadi2 said (about `Cheap Shot` it's not `movement-impairing effect`.

**Comment by lamaATS** [comment]
Fixed in rev. 5228
