### ISSUE TITLE
[PL][Warrior] Dodge/Parry Attack give no Rage

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5279]
Jak jest: Gdy nasz atak na przeciwniku będzie miał Dodge/Parry nie dostaniemy Rage

Jak powinno być: Powiniśmy dostać standardową ilość Rage.

Dowody:
http://www.mmo-champion.com/threads/851623-Rage-Normalisation-Calculation
"Rage is generated the same on a dodge or parry."
i to jeszcze:
http://calltoarms.blog.com/2010/11/26/rage-normalization-what-it-is-and-what-it-isnt/

Ogolnie Rage działa u nas ok tylko szwankuje to przy Dodge/Parry.
Gdy grałem na Offie kiedy było Cata testowalem to też na moim warku, zresztą na WoD nadal tak jest.
Ogolnie jak znormalizowali zdobywanie Rage z Wotlka na Cata, każdy Mele Swing powinien generować Rage zgodnie z 6.5 x base weapon speed i nie ważne czy Dodge, Parry czy Absorb i tak powinien generować Rage.
Akurat to ostanie z Absorbem jest u nas ok.

**Comment by BialyADI** [comment]
Nie zwróciłem na to uwagi do tej pory, ale Missy nie generują ciągle Rage u Warra/Druta.

**Comment by Quban** [comment]
Czyli działa :D

**Comment by BialyADI** [comment]
Tyczy się to warka w Fury.
W dual wield mimo że masz hit capa i tak ma się missy które nie generują Rage co osłabia Fury mimo że i tak jest cienki w PvE.
Missy u DK dają Runy z powrotem u warka miss z AA powinien dać Rage ponieważ tera w Fury jest to losowe i zależy od missa, a nie oto chodziło jak normalizowali to ;x.

**Comment by Quban** [comment]
hmm przygladne sie temu

**Comment by BialyADI** [comment]
ok, dzięki.

**Comment by BialyADI** [comment]
Bump, plz so annoying bug ;x.

**Comment by Quban** [comment]
nie mam teraz jak fixowac bo mam problem z kompem ;(

**Comment by BialyADI** [comment]
N ooki to potem bumptne to narazie jest majółwka ;D.

**Comment by stanq87** [comment]
Bump

**Comment by BialyADI** [comment]
Dobra jak Quban będzie miał kompa to, to naprawi. 
A pobił bym sobie Smoki w Fury a nie tylko Armsy.

**Comment by Jenovas** [comment]
Missy od 5004 powinny dawac rage.
Zamykam.

**Comment by Quban** [comment]
wiedziałem ze jenova poprawi ;P

**Comment by aneq** [comment]
@BialyADI 
gratulacje sunwellowcu, reportujesz rzeczy które nie są bugami, w końcu ktoś się dał nabrać.
Mam nadzieję, że po tej akcji nikt nie będzie już traktował twoich zgłoszeń poważnie.

**Comment by tnarf** [comment]
O ile rozumiem ui tego warka to PASEK na srodku ekranu pokazuje RAGE (ma minimalne opoxnienie wzgledem normalnego ale jest czytelniejszy wiec na niego patrzylem), CYFERKI wyskakujace lekko na lewo lub prawo to wartosci dmg i nie ma znaczenia z ktorej strony wyskoczyly (jak sie tu myle to reszta postu do wywalenia)

Przeanalizowalem fragment tego filmiku od 22 (taka pauza w biciu z powodu ptaszka) do 36s. W fragmencie tym wystepuja 2 missy (30 i 33s).

Warek trafil w nim 12 razy z auto ataku (cyferki bez ikony), 2x zmisowal (Verfehlen)
Wystepuje tu 11 zauwazalnych przyrostow RAGE; kolejno: 23, 12, 23, 23, 12, 23, 12, 11, 24, 23, 15.

I pojawia sie pytanie: co z pozostalymi 3 hitami (przypuszczalne 1 trafiony, 2 miss)?
W 25s wszedl dmg z auto ataku ktory nie ma odpowiadajacego sobie przyrostowi RAGE z powyzszej listy. Jednak jak przyjrzymy sie filmikowi (najlepiej w zwolnionym tempie) zauwazymy ze na ulamek sekundy RAGE osiaga 100 (przyrost z 91) po czym spada do 80, a 100-80=20 a tyle kosztuje uzyty Colosus Smash. Mozna sie spodziewaz ze przyrost wygenerowany tym hitem wyniosl 12+/-1.

Spodziewne 2 pozostale brakujace przyrosty wystepuja akurat wtedy kied maja miejsce MISSy. Co ciekawe po 1. missie nastepuje przyrost zblizony do poprzedzajacego (11 i 12), a po 2. missie tak samo.
W zwiazku z powyzszym dziwnym brakiem oraz wynikajacym z niego zaburzeniem kolejnosci wielkosci generowanego RAGE smiem sadzic ze:
TEN FILMIK JEST DOWODEM NA TO ZE **MISSY NIE DAJA RAGE**

**Comment by Jenovas** [comment]
Proszę nie atakować innych graczy, bo nawet ja po obejrzeniu tego filmiku na szybko stwierdziłem że rzeczywiście missy dawały mu rage. Pomyłki się zdarzają każdemu.

Rev 5004 został wycofany. Missy nie będą dawać rage.
Dziękuje wszystkim za pomoc.

**Comment by stanq87** [comment]
missy misami a co z  dodgami parry i block ?  bo o to sie  rozchodzilo na poczatku   tego zgloszenia

-Rage can be generated with several different methods. The primary cause of rage generation is by being attacked, which varies based on damage taken. Attacks that are blocked, parried, dodged or absorbed (as with Power Word: Shield) also generate rage.
[http://wowwiki.wikia.com/wiki/Rage](http://wowwiki.wikia.com/wiki/Rage)

**Comment by tnarf** [comment]
wowwiki i temat rage to... ale nowsze xrodla takze mowia ze dodge/parry/blockpowinno dawac
nie wiem czy nie masz wawrka czy co ze pytasz ale
na 100% absorby, Dodge i Parry na atlantsie na PvP DAJA RAGE co smiem sadzic ze w PvE sie nie zmienia, wiec jest ok
co do blockow to nie mam jak samemu sprawdzic ale podejrzewam ze jest tak samo

**Comment by Jenovas** [comment]
Tylko evade i miss obecnie nie powinny dawać radę. I proszę nie wklejać już więcej z wowwiki bo temat jest 10lat do tyłu...
