### ISSUE TITLE
[EN][NPC] NPC missing

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5281]
Like on screen. I see Quest mark on map but no NPC.
![wowscrnshot_121515_182813](https://cloud.githubusercontent.com/assets/5780624/11818296/e3cccfd2-a359-11e5-8f8c-49d76ccbfb10.jpg)

**Comment by Luna-maria** [comment]
you're probably gonna have to mention either which quest it is or the name of the npc :p

**Comment by sunshitwowsucks** [comment]
is it dead?
