### ISSUE TITLE
Character bugged

### ISSUE THREAD

**Issue by fealon96** [Atlantiss/BugTracker#5282]
My warlock's graphic look got bugged few days ago when I was doing quest in twilight highlands.
I tried everything to make it right  but with no sucess.

screenshot example:
![wowscrnshot_121515_104200](https://cloud.githubusercontent.com/assets/16310445/11820621/44f1d680-a31a-11e5-96af-df73f7ec0d25.jpg)

**Comment by Anhaeyn** [comment]
Have you tried using emotes like /dance?

**Comment by fealon96** [comment]
Yes, all of them.
Eaven items that make my charr move and etc.

**Comment by BialyADI** [comment]
that is funy some kind ;D

**Comment by debtheone** [comment]
gosciu polamalo cie jak kiedys irene x]]]
gm need to remove all auras from you
