### ISSUE TITLE
[EN][NPC]Blazing Talon Initiate

### ISSUE THREAD

**Issue by kostas4949** [Atlantiss/BugTracker#5284]
Blazing Talon Initiates on Alysrazor fight hit people in the air if they don't have a target on the ground. They shouldn't be hitting people in the air in any case. 
Damage taken while flying in the air the whole time:
![damagetaken](https://cloud.githubusercontent.com/assets/11000444/11837234/3ad53e16-a3e8-11e5-8d9e-ee635003cb15.png)
The journal states it too that they should only attack ground targets.
![bzi](https://cloud.githubusercontent.com/assets/11000444/11837243/4b0921a8-a3e8-11e5-824a-b2232871b9d3.png)

**Comment by Quban** [comment]
thx for the report its serious bug in this fight :dancer:

**Comment by kostas4949** [comment]
Thanks for fixing it this fast :)
