### ISSUE TITLE
[BG][Battle for Gilneas][Graveyard Use]

### ISSUE THREAD

**Issue by Vegakyudan** [Atlantiss/BugTracker#5294]
With patch 4.1 the functionality of graveyards within the Battle for Gilneas was changed.

    Players who die at a control point that they own will now be teleported to the next closest graveyard, instead of the one at which they died.
    If a player's team owns the Mine and Waterworks, and dies at Waterworks, they will be teleported to the Mine.
    If an Alliance player's team only owns Lighthouse, and dies at Lighthouse, they will respawn at their base.
    If a Horde player's team owns Waterworks and Mine, and dies at Lighthouse, they will respawn at Waterworks. 

http://wowwiki.wikia.com/wiki/Battle_for_Gilneas

**Comment by Kejmil** [comment]
Similar thing was done to Twin Peaks: http://eu.battle.net/wow/en/forum/topic/1776588666
Also for some reason there are no power ups on BfG, while they of course should be.

**Comment by Jenovas** [comment]
Fixed in rev 4728 both Battle for Gilneas and Twin Peaks.
