### ISSUE TITLE
[EN][Spell][Druid] Typhoon

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#5295]
Balance druid talent called Typhoon is almost usless in current state. Targets are dazed and Knocked back after roughly 3 seconds. It is extremely annoying and broken beyond limits. Imagine that you are trying to Knock back enemy player off of bridge in Blade's Edge Arena and you simply can't, because your Typhoon do completely nothing.

-Watch this viedo carefully and you will see that Typhoon Knock back players instantly.
https://www.youtube.com/watch?v=X79Vj1wgLb4&feature=youtu.be&t=4m2s
-OpenWoW link: http://cata.openwow.com/spell=50516#see-also-ability

**Comment by PierwszyKrytykRP** [comment]
Typhoon is generally fucked up. Sometimes it just goes on cooldown and doesn't do anything. It collides with GCD (generates additional gcd when pressed during gcd, doesn't do anything and you have to spam it or time it)

**Comment by Astrobazooka** [comment]
To o czym wspomniałeś faktycznie występuje, ale na naszą niekorzyść tak było na retailu.
https://youtu.be/X79Vj1wgLb4?t=1m48s w 1 minucie i 48 sekundzie dobrze to widać. Generalnie w wielu poradnikach pvp ludzie wspominają o tym, że należy przyspamować Typhoon aby zadziałał. Niemniej jednak Typhoon powinien odpychać targety natychmiastowo.

**Comment by MangeNerfedOwl** [comment]
Jeśli chodzi o odepchniecie, które poleciało przeciwnikowi prosto w twarz i nic nie zrobiło - jest sposób na ominięcie tego buga. Generalnie występuje to przy obracaniu naszą postacią. Mimo że właśnie szybko się obróciliśmy o te 90 stopni w naszego przeciwnika, żeby go odepchnąć, a nie odepchnęliśmy powodowane jest przez to, że gra tak jakby źle odczytuje kierunek w jakim nasza postać jest zwrócona. Można temu zapobiec jeśli trzymamy S w chwili rzucania casta. Wtedy z jakiegoś powodu mimo szybkiego obrotu zawsze Typhoon działa w tą stronę, w którą powinien. Nie mniej jednak to opóźnienie jest masakrą. Na chwilę obecną muszę przewidywać, że warlock zacznie zaraz castować feara, ponieważ jeśli walnę pushbackiem w czasie casta to nie odepchnie na czas.

**Comment by Jenovas** [comment]
Should be fixed in rev 5015
