### ISSUE TITLE
[EN][Spell][Druid] Eclipse.

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#5296]
Eclipse powinno się zawsze resetować po wejściu do gry albo zmianie lokacji. Dla przykładu jeśli wejdziesz na arenę, to Eclipse zawsze zaczyna od zera. Kierunek Eclipse można wybrać samemu ( Starfire oraz Starsurge ruszają pasek w prawo, a Wrath w lewo). Opisuję podstawy działania tej mechaniki, ponieważ jest jeden bardzo istotny błąd, o którym za chwilę napiszę.
 Po zresetowaniu Eclipse jeśli pierw użyjesz Moonfire z rozdanymi talentami w Lunar Shower (oczywiście jeśli użyjesz go tylko raz, żeby Lunar Shower nie zadziałał i nie dostarczył nam 8 energy przy pierwszym stacku), a następnie wyczarujesz Wrath, ponieważ chcesz uzyskać pierw Lunar Eclipse, to każdy kolejny spell prócz Wrath zacznie cofać pasek w stronę prawą, czyli Solar Eclipse. Błąd polega na tym, że jeśli wybrałeś już jeden z kierunków, to każdy czar powinien się do tego dostosować, a nie brnąć w zaparte.
 Ktoś może powiedzieć, że przed pullnięciem boss'a i tak pierwszym czarem jaki użyjesz będzie Starsurge, a co za tym idzie będziesz szedł w kierunku prawej strony. Opisany problem bardziej dotyczy PvP, ponieważ osiągnięcie Lunar Eclipse jako pierwszej daje lepsze rezultaty.

 Podsumowanie:
Jeśli używasz talentu Lunar Sower, to opisany problem istnieje chociaż nie powinien. Sprawa jest naprawdę problematyczna jeśli zależy Ci na prawidłowych obrażeniach w PvP, a i w PvE na pewno prawidłowo działające Eclipse się przyda, ponieważ nie zawsze powinno zaczynać się od Solar Eclipse.
 W obu poradnikach jest opisana strategia nazywana Pre-Lunar, która polega właśnie na zaczęciu rotacji od wybrania lewej strony poprzez wyczarowanie Wrath:
http://forums.elitistjerks.com/forums/topic/109404-balance-cataclysm-43-dragon-soul/
http://us.battle.net/wow/en/forum/topic/2721372177

OpenWoW link: http://cata.openwow.com/spell=80745 , http://cata.openwow.com/spell=81192

**Comment by PierwszyKrytykRP** [comment]
Kurwa kuban nie! Zes zjebal teraz masakrycznie, Starsurge w neutralnej pozycji ma dawac Solar a nie lunar energy.... Ty nie rozumiesz problemu....

http://forums.elitistjerks.com/forums/topic/109404-balance-cataclysm-43-dragon-soul/


> From a reset Eclipse position, Starsurge will give Solar energy.  Keep this in mind when planning your first few casts of the fight, to make sure you start cleanly towards whichever Eclipse you want first (which Eclipse this is depends on your plan for the fight).  A solid starting routine is important, because you have your Volcanic Potion, first set of trinket procs, and often Bloodlust, and want to maximize their effect.  Pay particular attention to DoT refreshing.



A i tak od siebie to wrath ZAWSZE ma generowac lunar energy, starfire ZAWSZE generowac solar energy. Starsruge ma generowac solar jesli zaczynamy od zera. Lub ta energie ktora nas szybciej do eclipse zaprowadzi. Sunfire(z lunar shower) generuje lunar energy, z moonfire nie wiem jak powinno byc, ale podejrzewam ze solar ma generowac

**Comment by PierwszyKrytykRP** [comment]
Ok jeszcze sprawdziłem to o czym mówi Astro i nie odtworzyłem twojego problemu. Wygenerowalem lunar energie wrathem a potem zaczalem spamowac moonfire i eclipse szedl w strone lunar. Jesli spamowalem od 0 to szedl w strone solar czyli wszystko dzialalo tak jak powinno.

Ja ci powiem na czym twoj problem polega i nie jest on zwiazany z zadnym bugiem.
Wrath generuje energie nie w momencie kiedy go wypuscisz tylko wtedy, kiedy on doleci. Jesli wycastujesz wrath i zaczniesz spamowac z lunar shower zanim wrath zada dmg to oczywiscie, ze dostaniesz solar energie z lunar shower i w kierunku tego eclipse bedziesz musial sie kierowac

**Comment by kadi2** [comment]
@PierwszyKrytykRP  Chodzi raczej o to, ze Moonfire nie powinien WYBIERAC strony eklipsy przy uzyciu moonfire jednokrotnie. Nie wgrywajcie tego fixa. :D

**Comment by kadi2** [comment]
@PierwszyKrytykRP Moonfire -> Wrath -> Starfire

**Comment by PierwszyKrytykRP** [comment]
A to nie ma nic wspolnego z Lunar shower :P 

Castujesz wratha z 0 energi, zanim zdazy przywalic w kukle castujesz starsurge, strarsurge zawraca w strone solar. Ale jesli wrath doleci, wygeneruje energie i dopiero potem zaczniesz castowac starsurge to wszytko jest ok

Wiec mi sie wydaje ze takie cos sie dzieje poniewaz starsurge sprawdza ile jest energi w trakcie jego castowania, a nie kiedy uderzy w cel.

**Comment by kadi2** [comment]
@PierwszyKrytykRP Pierwszy hit moonfire (bez lunar shower) nie powinien chyba nadawac kierunku eklipsie.

**Comment by PierwszyKrytykRP** [comment]
Mi moonfire bez lunar shower nie nadaje kierunku eclipsa. Ani wizualnie ani faktycznie. Zrobiłem to combo z twojej poprzedniej wiadomosci i lecialem w stronę lunar eclipse tak jak powinienem.

**Comment by kadi2** [comment]
@PierwszyKrytykRP Nie wiem, u mnie buguje sie za kazdym razem.
1.Rozdaj talenty w lunar shower
2. Przy kazdej probie zrob wczesniej reloga, zeby zresetowac kierunek eklipsy.

Moonfire -> Wrath -> Starfire/Starsurge

1.U mnie Moonfire wprawdzie nie nabija zadnej energii, jednak wizualnie strzaleczke przekreca sie na solar
2.Wrath daje prawidlowo lunar energie. Strzalka przekreca sie w strone lunar
3. Starsurge/Starfire Zaczyna nabijac energie solar, strzaleczka skierowana jest w strone lunar.

**Comment by PierwszyKrytykRP** [comment]
Mam lunar shower, robilem relogi za kazdym razem. Mowie, jedyny problem jaki napotkalem to ten ze starsurge ktory opisalem

**Comment by kadi2** [comment]
Wszedlem na drugiego druida, bug rowniez wystepuje.

**Comment by PierwszyKrytykRP** [comment]
Zresetuj talenty, wylacz addony moze?

**Comment by kadi2** [comment]
![](http://postimg.org/image/wp3jjih49/)
1.Castuje moonfire
![](http://postimg.org/image/suzhv7d9l/)
2.Castuje Wrath
![](http://postimg.org/image/adc3wf6af/)
3.Castuje Starfire
![](http://postimg.org/image/aqwftarzh/)
4.Wycastowalem kilka starfire wiecej.
![](http://postimg.org/image/k12j37uib/)

**Comment by Astrobazooka** [comment]
Kadi2 bardzo ładnie opisał to na przedstawionych screenach. Rozchodzi się o to, że Moonfire z rozdanym talentem Lunar Shower przy pierwszym uderzeniu (uderzeniu, które jeszcze nie nabija 8 energy) nakierowuje strzałeczkę w stronę Solar Eclipse. Następnie jeśli wyczarujemy Wrath, to strzałeczka przesunie się w stronę Lunar Eclipse o 13 energii. Jak na razie wszystko działa w porządku, ale jeśli po tym Wrathu zaczniemu spamować Moonfire albo Starsurge, to zacznie nas cofać w stronę Solar ignorując totalnie wcześniej wyczarowany Wrath.

**Comment by PierwszyKrytykRP** [comment]
Mowie, nie napotkalem tego problemu.

**Comment by Astrobazooka** [comment]
Jednakże problem istnieje i należałoby się nim zająć w odpowiednim czasie. Postaram się znaleźć chwilę i pokazać to na filmiku.

**Comment by Quban** [comment]
moonfire nie ruszalem, a starsurge nie powinien pierw isc w lewo?

**Comment by PierwszyKrytykRP** [comment]
Masz tu ladnie z EJ napisane

>From a reset Eclipse position, Starsurge will give Solar energy.


Od zera starsurge ma iść w prawo. Nie dobry kuban! Fe!

**Comment by Quban** [comment]
cofniete

**Comment by Quban** [comment]
ten temat strasznie zawile napisany
ciezko cokolwiek zrozumiec jak sie nie gra druidem bala

**Comment by Quban** [comment]
k chyba wiem ocb i postaram sie fixnac

**Comment by Astrobazooka** [comment]
Miło słyszeć :) Jeśli będę mógł jeszcze jakoś pomóc, to daj znać.
Ps. Zapoznaj się jeszcze raz z tym reportem zanim pójdzie w niepamięć, proszę. 
https://github.com/Atlantiss/BugTracker/issues/5297

**Comment by Jenovas** [comment]
Fixed in rev 4860
