### ISSUE TITLE
[EN][Spell][Druid] Lunar Shower direction.

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#5297]
Po zalogowaniu do gry albo wejściu na arenę, gdy Eclipse się resetuje Moonfire pod wpływem talentu Lunar Shower powinien zacząć generować lunar energy, czyli przesuwać pasek w stronę lewą, a nie prawą. Opisany przeze mnie błąd jest bardzo istotny w PvP, ponieważ Lunar Eclipse zapewnia nam silniejsze obrażenia ze względu na benefit dla Starfall'a.

 Dowody:
http://www.skill-capped.com/forums/showthread.php?16844-LSD2-vs-RLS-Stratagy
https://youtu.be/EOQz1PS0jlo
"Start off by throwing out a cyclone on the warlock ensuring that he is not able to set up dots on your entire team before the rogue opens, you should immediatly cast a starsurge into the pet to get your eclipse bar moving towards solar"
 Skopiowany przeze mnie fragment jest świetnym dowodem na to, że mam rację. Poradnik opisał to tak, że jeśli pierw chcesz mieć Solar Eclipse, to powinieneś unikać spamowania Moonfire z talentem Lunar Shower, ponieważ zacznie Cię on kierować w stronę Lunar Eclipse, dlatego pierw powinno się wyczarować Starsurge jeśli zależy nam na Solar Eclipse.
 
OpenWoW link: http://cata.openwow.com/spell=81192

**Comment by Quban** [comment]
While you are under the effect of Lunar Shower, Moonfire generates <b>8 Solar Energy</b> and Sunfire generates <b>8 Lunar Energy.</b>
Działa dobrze. jedynie starfire źle działa

**Comment by kadi2** [comment]
@Quban https://youtu.be/EOQz1PS0jlo
Nie zrozumiales zbytnio tego co linknales, https://youtu.be/EOQz1PS0jlo 1.35.

**Comment by kadi2** [comment]
https://www.youtube.com/watch?v=lW4n4wzW6Jo // 0:44

**Comment by Astrobazooka** [comment]
Widać, że nie zapoznałeś się z materiałem jaki podesłałem. Kadi2 specjalnie jeszcze raz Ci go udostępnił. Starsurge działa akurat prawidłowo. Zanim zabierzesz głos, to udowodnij mi, że się mylę, a nie cytuj tooltip. Od dawna jest wiadome, iż Blizzard popełnia błędy w tooltipach.

**Comment by Astrobazooka** [comment]
https://github.com/Atlantiss/BugTracker/issues/4034
Warto dodać, że bonus z tego setu również powinien pierw dać energię w stronę Lunar Eclipse.
https://youtu.be/EOQz1PS0jlo?t=1m30s 1m30s

**Comment by Jenovas** [comment]
Fixed in rev 4860
