### ISSUE TITLE
[EN][PL][Rogue] Tricks of the trade cd

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#5299]
Class: Rogue
Spell: Tricks of the trade
Link: http://www.wowhead.com/spell=57934

[EN]
Very often tott's cd doesn't disapear.
Probably becous Rev 4714

[PL]
Bardzo często cdek totta nie znika.
Prawdopodobnie przez Rev 4714

EDIT:
Bug occurs when TotT is activated by hit that triggers poison
Setting Lag Tolerance for 0 little reduce frequency of this bug (but still occurs) (discovered by Jenova)

**Comment by kadi2** [comment]
Shadowform ma podobne problemy czasami od niedawna.

**Comment by Jenovas** [comment]
Czyli wcześniej był bug że nie było widać CD spella, a teraz mamy że spelle zostają na zawsze na CD?

**Comment by kadi2** [comment]
Nie wiem jak dokladnie zreprodukowac bug z shadowform, ale spell jest podswietlony na ciemny kolor. Wyskakuje komunikat ability is not ready yet.

**Comment by Aviannaqt** [comment]
Potwierdzam, na jednym bg musiałem 3 razy resetowac gre, bo co chwila shadowform sie bugował.

**Comment by kadi2** [comment]
@Jenovas Raczej poprostu popsuły się inne skille przy naprawianiu docelowych.

**Comment by tnarf** [comment]
Jesli pytanie Jenowy dotyczy totta to:

wcześniej (przed wspomnianym revem) było tak że cd normalnie działał i mozna bylo uzywac swobodnie skila

teraz jest tak ze co ktores uzycie cd jest non stop uniemozliwiajac uzycie skila
i schodzi dopiero (jesli dobrze zauwazylem) przy smierci, relogu i jakiegos powodu ktorego nie potrafie nazwac bo nagle ikona skila pokazywala ze nie ma juz cd (czas pomiedzy poprzednim uzyciem a ta sytuacja byl mierzony w minutach, a wiec znacznie dluzszy od cd)

dodam jeszcze ze taki problem z tym skilem kiedys wystepowal (chyba na poprzednim patchu)

**Comment by Jenovas** [comment]
I czy wiecie kiedy się to dzieje? Dawny bug był jeżeli spamujemy dany spell, a teraz kiedy to się dzieje, bo zrobiłem sobie macro które mi używa dany spell 20 razy i niestety nie udało mi się odtworzyć buga.

**Comment by Evelinrose** [comment]
It's hard to say,what i noticed yday in raid is that it happened a lot,i play sub which means i go into stealth a lot,maybe it bugs out on vanish.I did notice one thing tho you dont have to relog to get it working,i simply went outside instance and spell was ready to use.

**Comment by tnarf** [comment]
potestowalem chwile (build assa):
1. przy samym skilu "podstawowym" (bez wykonania ataku) nie bylo problemow z CD
2. przy uzycia skilla bez zalozonych trutek nie bylo problemu z CD

3. przy uzyciu skilla z zalozonymi trutkami w czasie trwania buffa Envenom (zwieksza szanse na wejscie trutki) CD sie zacinal
w dodatku (czego wczesniej nie zauwazylem) zaden buff nie wszedl, a w CombatLogu nie pojawilo sie "SPELL_CAST_SUCCESS" lub "SPELL_AURA_APPLIED" za to 2 linijki "SPELL_CAST_FAILED (...) "Not yet recovered"" (tazke kiedy odstep pomiedzy uzyciami przekraczal 60s gdzie cd 30s)
obie linijki byly poprzedzane wpisami o trafieniu MH/OH z wejsciem trutek

dodam jeszcze ze CD skila zaczyna sie "ladowac" dopiero w momencie zejscia bufa "podstawowego" (nie jestem pewien czy tak powinno byc ale to nie jest problemem), wiec samym spamieniem skila raczej nie da sie tego powtorzyc

przy okazji zauwazylem ze czas trwania podstawowego buffa trwa 20s a nie 30s jak mowi tooltip (otworzyc dodatkowy temat?)

**Comment by Jenovas** [comment]
Potrzebuje ID spelli które się teraz bugują albo ID spelli które się dawniej bugowały. Których jest więcej?

**Comment by kadi2** [comment]
Shadowform buguje sie gdy probujesz go uzyc podczas tego dziwnego gcd https://github.com/Atlantiss/BugTracker/issues/866

Shadowform - 15473
Inner Focus - 89485

**Comment by Jenovas** [comment]
Inner Focus - 89485 - też się teraz zacina, czy wcześniej się zacinał?

**Comment by kadi2** [comment]
Wczesniej sie zacinal, zapewne teraz smiga dobrze skoro nikt sie nie skarzy

**Comment by Jenovas** [comment]
Tymczasowy fix na ten problem to ustawienie po stronie client Lag Tolerance na 0.
Znajdziecie tą opcję w Interface/Combat.

**Comment by kadi2** [comment]
Nadal potrafi sie zbugowac, ale o wiele rzadziej.

**Comment by RhythmOfficial** [comment]
@Jenovas

> Please try searching before you create duplicates. #5299
> [EN]
> Very often tott's cd doesn't disapear.
> Probably becous Rev 4714
> PS - it's not Polish, just try searching, it's not that hard.

Hmmmm amazing search, now if you would actually have the brain capacity to understand english.
You would be able to understand what I was saying in my report, but since you don't let me put a couple of whitemarks and all caps in there so you can understand it ;).

GOING TO UR INTERFACE > COMBAT AND REDUCING THE SPELL LATENCY TO 0 DOESN'T WORK THE ISSUE STILL REMAINS THE SAME, THEREFORE THIS BUG "FIX" IS INCORRECT, AND STILL BUGGED NOT FIXED.

so now you can read it and not just mindlessly close it as fixed, then linking me some polish bug post claiming it's not polish when obviously it is. And actually fix the bug.
Thanks ;)

While you're at it, you might check my other bug reports that I did for this "amazing blizzlike" server aswell, since that should help you get back to that r1 spot you guys always have been on!

**Comment by Jenovas** [comment]
Should be fixed. If not create a new topic.
