### ISSUE TITLE
Hunter mastery bugged?

### ISSUE THREAD

**Issue by Sulfuron1997** [Atlantiss/BugTracker#5304]
So when i equip/reforge items with mastery the damage of my pet( i am BM hunt) does not increase, the same thing for MM and survival

**Comment by Jenovas** [comment]
Mastery works properly, please write a ticket in-game, ask the GM that answers your ticket to check your auras for mastery, if not .reset talents, .unaura all, try to relog and Mastery should start working for you.

**Comment by Sulfuron1997** [comment]
those scripts you gave me are not working and i have reset my talents and relogged and its still not working

**Comment by Jenovas** [comment]
They are scripts for the GM. Write a ticket and wait.

**Comment by Sentus** [comment]
Mastery sometimes turns off and sets percentage to the default values.
You must then either switch between builds or log in again.
Interestingly this does not happen only in hunters.
