### ISSUE TITLE
Warlock: Incinerate not benefiting from the increased damage when used on an immolate target

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5309]
As the tittle says incinerate should get around 1k increased damage when immolate is up on the target, this doesnt work, which is a major dps loss for both incinerate demo spec and destro lock and a minor dps loss for shadow bolt demo, please fix this =)))))))

**Comment by anxanas** [comment]
Also if people are testing this for destro they will see that the immolate target takes more damage from incinerate, this is due to to the fire and brimstone talent which increases incinerate damage by 15% to targets with immolate, so if you notice this while trying to test this as destro it doesnt mean that the incinerate increase from immolate isnt bugged.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/4814
