### ISSUE TITLE
Mouse cursor issue.

### ISSUE THREAD

**Issue by moollen** [Atlantiss/BugTracker#5315]
My mouse cursor glove icon, appears to remain stuck in one spot at the lower left area. 
i can still move my mouse about, however it is incredibly difficult to do anything because 
i cannot tell where my mouse is. accepting the terms of service and creating a character were incredibly difficult. ild rather not play like this. Unfortunately your server seems to be the best. anyone know a fix?

**Comment by Corson** [comment]
Are you using launcher from the site?

**Comment by moollen** [comment]
im using the mini from the site.

**Comment by moollen** [comment]
wow_434

**Comment by Pvt-8Ball** [comment]
Sound like a client side issue to me, so it shouldn't have anything to do with the server, try going to options>advanced and toggle Hardware Cursor Off/On and see if either fixes it.

**Comment by kadi2** [comment]
It may also colide with other software you are using. Try to turn it off.

**Comment by moollen** [comment]
disabled hardware cursor did it, thanks a bunch.
