### ISSUE TITLE
Deepholm

### ISSUE THREAD

**Issue by Skrafin** [Atlantiss/BugTracker#5318]
Quicksilver submersion quest was taken from an NPC by my character, but it showed, that I can finish it instantly (yellow question mark appeared) so I did it, but I didn't get the reward, quest is gone, and I have a blocked way for all my other chain quests in deepholm, because this one was the last one I had available. Please help my as I have no way to complete other quests in Deepholm and get the achievement I really want.

Character name "Restorina"

**Comment by Aviannaqt** [comment]
Read BT rules.
