### ISSUE TITLE
[PL][Faction][Achivement] Zandalar Tribe

### ISSUE THREAD

**Issue by Althin** [Atlantiss/BugTracker#5321]
Zandalar Tribe- na 4.1 powraca jako Reputacja w Feats of Strength. Obecnie nie możemy jej wbijać ani na Zul'Aman, ani na Zul'Gurub. 

Link: http://wowwiki.wikia.com/wiki/Zandalar_tribe

Niedlugo dodam kolejne bugi questów, które są powiązane z ową frakcją.

**Comment by Thefakemccoy** [comment]
This faction was removed and rep can no longer be earned as of 4.1

**Comment by Thefakemccoy** [comment]
http://www.wowhead.com/faction=270/zandalar-tribe
Players who reached Exalted before the faction was removed were given  Hero of the Zandalar Tribe.

**Comment by Aviannaqt** [comment]
Tak powinno byc.

**Comment by Althin** [comment]
Otwórzcie temat, ta Reputacja powraca jako feats of strength. Chcecie grać na bugach to grajcie, ale innym dajcie zagrać jak na Blizzlike :(

**Comment by Kejmil** [comment]
Ta reputacja nie wraca jako tako, tylko ci ktorzy wczesniej ja dobili dostaja za to feat of strength.
Skoro ten serwer wystartowal na patchu cata a od cata nie ma tych trolli na ich wyspie to jak chcesz u nich repe wbic? ZA i ZG zostaly przerobione i fabularnie bijac tamtejsze trolle nie pomagasz zandalari tylko psujesz ich plany xD

**Comment by Althin** [comment]
Przykro mi to mówić, ale na globie na ZA i ZG działała i będę walczył o to
by reszta questów na ZG i ta reputacja były do zrobienia.

W dniu 21 grudnia 2015 13:01 użytkownik Kejmil <notifications@github.com>
napisał:

**Comment by Jenovas** [comment]
By Daimoth (1,095 – 1·1·10) on 2011/06/10 (Patch 4.1.0)		
Apparently impossible to rep up with these guys now. Don't bother, move the rep faction to inactive so it doesn't bug you.

Ludzie którzy grali na globie za czasów Cata oraz Wowhead twierdzą inaczej.

Althin proszę poszukać dowodu że powinno się wciąż dać rade wbić repe u nich a wtedy zobaczymy co i jak. Póki co z źródeł które sprawdziłem repa dla nich została niby usunięta (nie da się już jej wbić), tak więc temat zostaje dalej zamknięty.

**Comment by Althin** [comment]
Mam źródło, które grało wtedy na globie i twierdzi mi, że działała ta repa


W dniu 21 grudnia 2015 20:36 użytkownik Jenovas <notifications@github.com>
napisał:

**Comment by Walniety** [comment]
Ja też grałem na golbalu w sumie od classic'a i pamiętam że od pacha 4.2 poza repą z firelandów powracała wraz z przerobieniem zul'amana i zul'guruba jest też repa do zandalari tribe :D

**Comment by Jenovas** [comment]
To nie jest żaden dowód. Wszędzie gdzie się szuka jest napisane że nie ma tej repki, fora blizzarda, wowhead, patch notes, mmo-champs. Tak więc nie będzie tej reputacji i nie da się jej wbić.

**Comment by Kejmil** [comment]
juz mielismy takiego co gral na globie i domagal sie rune systemu z wotlka na cata "bo gralem i wiem" xD

**Comment by Althin** [comment]
"With the Gurubashi trolls destroyed and the Blood God no longer an issue,
most Zandalar trolls have returned back to their home land Zandalar,
leaving Yojamba Isle empty. Exalted reputation with this faction would
become a Feat of Strength. It is not easy to become exalted."

2015-12-22 13:22 GMT+01:00 Kejmil <notifications@github.com>:

**Comment by Althin** [comment]
To jest wpis z wowwiki, gdzie wchodzi to na patchu cata.

**Comment by Bildo** [comment]
Swoim wpisem potwierdziłeś to co napisał Kejmil. Temat zakończony.
