### ISSUE TITLE
[EN][NPC][Northern Stranglethorn] Pogeyan

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#5322]
http://www.wowhead.com/npc=51663/pogeyan
On atlantiss he is level 1 friendly npc. Not tamable.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6982-53235322-npc-pogeyan-and-tsulkalu/

**Comment by Corson** [comment]
bump

**Comment by aje** [comment]
no bump are needed. the fix is here.
be patient, everybody is working on 4.2 right now
