### ISSUE TITLE
Dissension Amongst The Ranks...

### ISSUE THREAD

**Issue by avensharr** [Atlantiss/BugTracker#5324]
I have all the info correct, was at the right location with the buff ''Illidari Disguise''. But not all the kills would count. A ratio of about 10% is working right now. I was in a group of 5.... then i tried alone.... nothing changed. At first i tought it was only one that counted but no. All of them had the same bug

**Comment by Thefakemccoy** [comment]
Title and links

**Comment by RadioActiveSoul** [comment]
It still has the same problem while doing the quest, at the right position and with the tabard equipped, just confirming what avensharr said. 

Dissension Amongst the Ranks...
http://www.wowhead.com/quest=10769/dissension-amongst-the-ranks
