### ISSUE TITLE
[PL][Quest][Daily][Classic][Borrowing' From the Winterfall]

### ISSUE THREAD

**Issue by magion342** [Atlantiss/BugTracker#5327]
http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall
brakuje quest itemow a mianowicie tego 
![gwesehesh](https://cloud.githubusercontent.com/assets/16358596/11917675/08ff7560-a711-11e5-9e06-332089530639.jpg)

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/1647
