### ISSUE TITLE
[PL][ITEM] Arcanum of the Wildhammer

### ISSUE THREAD

**Issue by Deadlyblonde** [Atlantiss/BugTracker#5329]
Enchant Arcanum of the Wildhammer http://www.wowhead.com/item=62422/arcanum-of-the-wildhammer jest zdublowany u wendora Craw Macgraw http://www.wowhead.com/npc=49386/craw-macgraw 
![wowscrnshot_122015_125348](https://cloud.githubusercontent.com/assets/3464907/11917859/acba7bfc-a719-11e5-9bde-22ae5b075f00.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/6987-5329-item-arcanum-of-the-wildhammer/
