### ISSUE TITLE
[EN][Dungeon-WotLK] Utgarde Pinnacle 

### ISSUE THREAD

**Issue by Vidyapoky** [Atlantiss/BugTracker#5331]
![wowscrnshot_122015_165529](https://cloud.githubusercontent.com/assets/1499989/11918661/9da86cde-a73a-11e5-9543-166ded9228f8.jpg)
Svala's sorrowgraves Ritual (http://www.wowhead.com/spell=48276/ritual-of-the-sword) does no damage + she gets stuck in place after doing ritual. Boss is killable but achievement Incredible Hulk isn't completable.

Note: I had 400 hp before ritual and after ritual. (No damage)

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/1865
