### ISSUE TITLE
[EN][Quest][Old Hillsbrad Foothills][Visual]Nice Hat...(ID 12513)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5334]
Quest is working correct but it show that it end to the location the NPC [Don Carlos](http://www.wowhead.com/npc=28126/don-carlos) before the cata(near the water) but the npc is on the right cata location.

![wowscrnshot_121915_193733](https://cloud.githubusercontent.com/assets/10282971/11920388/9287f040-a776-11e5-8b12-5d8b0d9e7912.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7004-5334-questnice-hatid-12513/
