### ISSUE TITLE
[PL][Warrior] Charge/Intercept/Intervene "No path available"

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5335]
Jak jest:
Charge działa bardzo słabo bardzo często jest "No path available" nawet w takiej sytuacji jak ta:
![wowscrnshot_122115_025914](https://cloud.githubusercontent.com/assets/5780624/11921796/0c546ec2-a78f-11e5-9da1-f1d9f703e95b.jpg)

Prawie w ogóle nie da się Charge dać pod górkę np. taką jaka jest na BG Warsong Gulch.
Ogólnie Charge/Intercept/Intervene mają u nas dziwnie spłaszczony tor dotacia.
Jak nasz cel jest poniżej nas a my chcemy go szarżować z góry na dół też prawdopodobnie zobaczymy "No path available"...

Jak powinno być: 
Charge czy intervene powinno normalnie się dać użyć nawet jak nasz cel jest nad nami, a nie ciągle widzieć "No path available".

Dowody:
Dowodów jest mnóstwo wiele filmików na YT chociażby ^^:
Charge pod górę na resp przeciwnika na WG, na Atlantissie zobaczymy "No path available".
https://youtu.be/Qce6m6HstRA?t=3m50s <-- 3:50 min.

Intervene pod GÓRĘ, u nas niemożliwe:
https://youtu.be/scDrEXNSR-Y?t=21m49s <-- 21:49 min.

Jeśli będą potrzebne jeszcze jakieś dowody chętnie poszukam czy w filmikach które lubię oglądać czy na forach.

**Comment by Aviannaqt** [comment]
Someday we'll probably try to fix pathfinding, but that is a huge task and we dont have time now to do it. - Jenova
