### ISSUE TITLE
[EN][Warrior] Talent ''Taste For Blood'' 

### ISSUE THREAD

**Issue by nicefruits** [Atlantiss/BugTracker#5336]
With the spec Arms Warrior, you can choose Taste For Blood. U should then be able to use Overpower  after you have used Rend. But this isn't working at the moment. The icon comes up to the screen but you're not able to use Overpower. Watch the screenshot down below ( the icon is at the corner) .
![wowscrnshot_122115_121303](https://cloud.githubusercontent.com/assets/16383355/11929537/561bdd54-a7dc-11e5-821f-262412a9c4bf.jpg)

**Comment by Kejmil** [comment]
i just tested this on my warrior and everything was working fine there

**Comment by kadi2** [comment]
But you don't even have overpower on your cast bars or im blind.

**Comment by Porobiony** [comment]
I can confirm, there's no Overpower at any of action bars

**Comment by Wolffenstein** [comment]
It's working fine, you don't have Overpower on any of your action bars, you must have confused it with some other icon.

**Comment by nicefruits** [comment]
Oh lol my bad XD
