### ISSUE TITLE
[EN][Item] Crashin' Thrashin' Racer

### ISSUE THREAD

**Issue by agardosh** [Atlantiss/BugTracker#5338]
2 problems I've noticed:
First one being the Achievement related, "Crashin' & Thrashin'". In the server, the count of crashes reset every time you're being crashed into, the achievement text doesn't suggest that, and reading through comments on wowhead seems to support this.
Link: http://www.wowhead.com/achievement=1295/crashin-thrashin#comments
Second is collision issues, for some reason the toys ability, "Racer Rocket Slam", can launch you through walls, even though running around the toy can't go through terrain. This actually bugged me and crashed the client once.

**Comment by LaveGit** [comment]
Both issues reported in following thread already: https://github.com/Atlantiss/BugTracker/issues/5286

**Comment by agardosh** [comment]
Sorry, I ran a search on the bugtracker for this problem and wound up only with stuff from last year.
