### ISSUE TITLE
[PL][Quest] [Across Transborea]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5339]
Po dojsciu do na miejsce npc spada z klifu i nie da sie zaliczyc questa
http://www.wowhead.com/quest=11930/across-transborea
![wowscrnshot_122215_030302](https://cloud.githubusercontent.com/assets/16046575/11946259/139979fa-a859-11e5-85d7-5baa77d920fb.jpg)

**Comment by Aviannaqt** [comment]
#939
