### ISSUE TITLE
[PL] [QUEST] [STONETALON MOUNTAINS] [BARRIER TO ENTRY]

### ISSUE THREAD

**Issue by NewBieMisiek** [Atlantiss/BugTracker#5342]
![wowscrnshot_122215_124219](https://cloud.githubusercontent.com/assets/16384411/11954541/b2eb9344-a8a9-11e5-8691-9b967aa9fc0a.jpg)
![wowscrnshot_122215_124240](https://cloud.githubusercontent.com/assets/16384411/11954542/b6abf460-a8a9-11e5-9163-e38affa3cc65.jpg)

Bug polega na tym że w miejscu gdzie są miny powinniśmy użyć klucza który dostajemy od npc żeby je rozbroić, niestety nie da się w żaden sposób ,npc znajduje się dokładnie w THE FOLD.

**Comment by Bildo** [comment]
zasady bt
