### ISSUE TITLE
[PL][Quest]You're mean one.

### ISSUE THREAD

**Issue by probboy3** [Atlantiss/BugTracker#5346]
Nie da się otworzyć worków stojących przy jaskini, świecą się one typowo dla quest itemów, ale nie da się wejść z nimi w interakcję. Uniemożliwia to wykonanie jednego z achievmentów na event świąteczny.

http://www.wowhead.com/quest=6983/youre-a-mean-one

//edit:
Chodzi o fragment ukazany na tym filmie w okolicach 8:20s 
https://www.youtube.com/watch?v=AnYplPFAiQw

**Comment by Aviannaqt** [comment]
#5292
