### ISSUE TITLE
[EN][Quest][Sethekk Halls]Can't Stay Away(ID 10180)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5347]
Quest text was updated in 4.3 and npc was moved inside Sethek Halls but here text is still saying to find him outside Sethek Halls and it show it end on the pre-cata location.

![wowscrnshot_121515_230716](https://cloud.githubusercontent.com/assets/10282971/11960178/fbe6d3bc-a8d9-11e5-968d-041ee06323c1.jpg)

Wowhead Link: [Can't Stay Away](http://www.wowhead.com/quest=10180/cant-stay-away)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7036-5347-quest-cant-stay-away-10180/
