### ISSUE TITLE
[EN][Quest][Zangarmarsh]Coilfang Armaments(ID 9766)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5348]
Quest has been removed on 4.3 patch([Comments](http://www.wowhead.com/quest=9766/coilfang-armaments#comments:id=1588255)).

Wowhead Link:[Coilfang Armaments](http://www.wowhead.com/quest=9766/coilfang-armaments)

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8153-5348questzangarmarshcoilfang-armaments/

**Comment by sunshitwowsucks** [comment]
Server is 4.2 though

**Comment by Aival94** [comment]
That is the reason i gave which patch get removed so they can keep it like that or fix it as the content is 4.2 but patch is 4.3.4.
