### ISSUE TITLE
[EN][Quest][Minor][Northern Stranglethorn]An OOX of Your Own(ID 3721)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5349]
Quest Text is totally missing including showing what you get as reward.

![wowscrnshot_122215_002959](https://cloud.githubusercontent.com/assets/10282971/11960469/95e299aa-a8db-11e5-9d56-96c6743c8149.jpg)

How it should be: [Youtibe video](https://youtu.be/QZ2X_As3w9w?t=89)
Wowhead Link:[An OOX of Your Own](http://www.wowhead.com/quest=3721/an-oox-of-your-own)

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7448-5349quest-an-oox-of-your-own/
