### ISSUE TITLE
[EN][Quest] Mounting Up

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#535]
In the quest **Mounting Up** (http://www.wowhead.com/quest=12414) you get the quest count by simply using the quest provided item **Stick** (http://www.wowhead.com/item=37708), but how it should work is that when you use the **Stick** on **Highland Mustang** (http://www.wowhead.com/npc=26472), only after you have collected a **Wild Carrot** (http://www.wowhead.com/item=37707) from a **Wild Carrot** (http://www.wowhead.com/object=189983), then you would mount the **Highland Mustang** and be able to ride him back to the quest giver to get the quest count.

Here's the youtube video: https://www.youtube.com/watch?v=X3YdBitZbho

**Comment by Bildo** [comment]
fixed
