### ISSUE TITLE
[EN] [Spell] [Shaman] Hex

### ISSUE THREAD

**Issue by Bustyplz** [Atlantiss/BugTracker#5351]
Hi,
There is a problem with the Hex : 

-You can use Totem (Since 4.2 patchnote, its not possible to use your totem when you are Hex)

![wowscrnshot_122215_181558](https://cloud.githubusercontent.com/assets/16181538/11961368/4ebe4c5c-a8d8-11e5-8918-c05570acbf82.jpg)

You can see on this screen i'm hex and i can use my Spirit Link Totem

**Comment by Jenovas** [comment]
Duplicate - https://github.com/Atlantiss/BugTracker/issues/4884
