### ISSUE TITLE
[EN][Quest][Icecrown] The Last Line of Defense

### ISSUE THREAD

**Issue by thenoobbomb** [Atlantiss/BugTracker#5353]
http://www.wowhead.com/quest=13086/the-last-line-of-defense

This quest. Phasing is messed up. Once you enter the Argent Cannon, all of the enemies you have to kill disappear, making you unable to complete the quest which in return hampers progression of all the questing in Icecrown.

**Comment by Aviannaqt** [comment]
#4431
