### ISSUE TITLE
[EN][Other] PvP Resilience vs Pets/Minions

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5354]
Naw: Resilience don't reduced Dmg from Hunter/Warlock/DK Pets.

Resilience should reduced Dmg from Players and their Pets and Minions.

I just tested it. Thats explain why everyone play BM hunter and do so much Dmg in PvP ;x.

**Comment by Jenovas** [comment]
Just tested. Resilience works on pets.

**Comment by Kejmil** [comment]
based on last encounter in lost city i think it's possible that pet basics atack bypass all % dmg reduction, dunno if it happens also in pvp, but on this boss during phase one you can see that hunter pets meleeing boss for 100- and hitting with basic atack for 3k+
