### ISSUE TITLE
[PL] [Talent] [Warrior] Battle Trance

### ISSUE THREAD

**Issue by Mordorianin** [Atlantiss/BugTracker#5356]
Przy aktywacji talentu Battle Trance, nasz kolejny skill, który kosztuje więcej niż 5 rage będzie darmowy. Działa to poprawnie ze wszystkim oprócz Execute, po którym użyciu, aktywny talent jest zjadany, a rage za użycie skilla zostaje nam odjęty.

Linki:
Battle Trance - http://wowwiki.wikia.com/wiki/Battle_Trance_(old_warrior_talent)
Execute - http://wowwiki.wikia.com/wiki/Execute

**Comment by PierwszyKrytykRP** [comment]
Execute zjada dodatkowy rage (jeśli go masz) żeby zadać więcej obrażeń. 

Battle Trance najwyraźniej wpływa tylko na bazowy koszt skilla. Według mnie działa jak powinno i musisz udowodnić, że dodatkowy koszt execute też powinien być modyfikowany przez ten talent

**Comment by Kejmil** [comment]
http://www.wowhead.com/spell=5308/execute#comments 4.3.4 comment

**Comment by Jenovas** [comment]
It works the same as Deadly Calm. The base cost gets reduced to 0 but you still lose the rage that gives the extra DMG.
