### ISSUE TITLE
[PL][Npc] Crazed Mana-Wyrm

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5357]
Ten npc powinien byc martwy 
http://www.wowhead.com/npc=26761/crazed-mana-wyrm#screenshots
![wowscrnshot_122215_042115](https://cloud.githubusercontent.com/assets/16046575/11968654/ccf29976-a90e-11e5-9f98-52fe3cfd323f.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7056-5357-npccrazed-mana-wyrm/

**Comment by wtRCH** [comment]
Accepted, probably fixed untill now. Closing.
