### ISSUE TITLE
[PL][Npc]Azure Skyrazor

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5358]
Ten npc powinien byc martwy
http://www.wowhead.com/npc=26736/azure-skyrazor
![wowscrnshot_122215_042247](https://cloud.githubusercontent.com/assets/16046575/11968668/fd3dd1a4-a90e-11e5-9cdb-dc3e42543992.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7055-5358-npcazure-skyrazor/
