### ISSUE TITLE
[PL][Npc]Venture Co. Ruffian

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5359]
Ten npc ma niewlasciwa teksture 
http://www.wowhead.com/npc=28124/venture-co-ruffian
![wowscrnshot_122215_152731](https://cloud.githubusercontent.com/assets/16046575/11968696/483d455e-a90f-11e5-818c-4fa77b8386c3.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7054-5359-npcventure-co-ruffian/
