### ISSUE TITLE
[PL][Mage][Other] Resilience and Ignite

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5360]
Jak jest: 
Resilience nie redukuje DoTy Ignite. Tak jak na obrazku:
![wowscrnshot_122315_014139](https://cloud.githubusercontent.com/assets/5780624/11969207/cc3edd16-a916-11e5-930b-795c6513b128.jpg)

Jak powinno być:
Resilience powinien redukować otrzymany Dmg od Ignite jak każdy inny.
Widać na obrazku ze dostałem 2009 hit i 2009 * 0,4=802 z Ignite, 802 tyle powinna zadać Dmg DoTa gdybym nie miał Resi.
Dmg z Ignite powinien być zredukowany przez Resilience 802 * 0,7535=604.

Sprawdziłem też czy jest redukowany przez Defensive Stance Warka i tu jest wszystko ok.
Ogólnie z Resilience są często problemy na priv serwerach.
Postaram się jeszcze po testować jak to jest z Petami czy omijają Resi, te co Jenovas zamknoł zrobiłem trochę na odwal bez screenów albo się mylę i pety nie omijają Resi u nas ^^.

**Comment by kadi2** [comment]
To co mowisz potwierdza, ze ignite dziala poprawnie z resilience. Natomiast double-dippuje sie z defensive stance. Nie mowie, ze tak nie bylo na blizzardowskich serwerach, raczej ciezko bedzie cos wygrzebac na ten temat.

**Comment by BialyADI** [comment]
Nic nie trzeba grzebać, masz nawet w Rev. 4694 "Ignite DMG will now be reduced by auras that reduce DMG Taken" i tak właśnie powinno być, Resi tez powinno redukować Dmg od Ignite.
Grałem swojego czasu na Cata i wiele rzeczy testowałem, lubiłem sprawdzać mechanikę gry i wiem że redukować każdy otrzymany Dmg od graczy. to nie PvE gdzie Ignie robi praktycznie główny Dmg.

**Comment by kadi2** [comment]
Prawdopodobnie mam racje, 4 luty 2012 daje duze prawdopodobienstwo na to, ze filmik zostal nagrany po hotfixie buga z ignite.
https://youtu.be/ny--IOtV12E?t=4m12s
DK majacy na sobie Blood presence, i dwa pozostale talenty zwiekszajace redukcje
3249*0.2=649.8

Nad glowa DK pokazuja sie liczby 3249 z jakiegos skilla, natomiast 2 sekundy pozniej liczba 650. Nie ma tutaj mowy o jakis modyfikatorach z mastery maga, gdyz jest to twink 79.

**Comment by kadi2** [comment]
Prawdopodobnie ignite nie zostalo poprawnie naprawione i mam racje, 4 luty 2012 daje duze prawdopodobienstwo na to, ze filmik zostal nagrany po hotfixie buga z ignite.
https://youtu.be/ny--IOtV12E?t=4m12s
DK majacy na sobie Blood presence, i dwa pozostale talenty zwiekszajace redukcje
3249*0.2=649.8

Nad glowa DK pokazuja sie dwie powyzsze liczby 3249 z jakiegos skilla, natomiast 2 sekundy pozniej liczba 650. Nie ma tutaj mowy o jakis modyfikatorach z mastery maga, gdyz jest to twink 79.

**Comment by BialyADI** [comment]
Ten link do dyskusji jest na temat Combustion i Resi tego nie sprawdzałem i nie wiem, jakiś bug z tym związany widać i na Globa się wkradł. 
Natomiast osoby co tam się wypowiadają tylko potwierdzają moje słowa, zresztą wiem co pisze.

Ktoś napisał:
"This is the only thing that was cast at a player wearing 3667 resilience...
Pyroblast! 20354 (critical)
Combustion 7554 (critical)
Pyroblast! DoT 951 per tick over 10.98 seconds
Ignite DoT 4772 both ticks over 4.00 seconds

COMBUSTION DOT = 1992 DPS ???"

Jak widać Ignite nie ignoruje Resi jak u nas.
Co do Combustion fakt dziwne żeby bił mniej od Ignite, sprawdzę jak to u nas wygląda, lecz to już na inne zgłoszenie.  

Potem wypowiedział się w temacie pracownik Blizzarda też potwierdzając to co napisałem w tickecie Buga:
"There is a separate issue with Ignite that we are looking into. The interaction with resilience is still working as intended."

Czyli interakcja/zależność Resi i Dmg Ignite była czyli pamięć mnie nie myli.
A u nas Resi nie działa całkowicie na Dmg Ignite ;x.
Tak jak pisałem Resi powinno redukować każdy Dmg od innych graczy i petów od DoTy Ignita też, od tego nie było wyjątku.

**Comment by blinkmaster** [comment]
Oczywiście,  że resilence nie działa na ignite. Wynika to z prostego faktu, że ta klasa by wówczas nie istniała. Spell jak ignite oblicza swoją wartość z redukowanego przez resi dmg spella. Redukcja dmg ignite przez def stance tez jest bugiem, dzięki będę wiedział co sprawdzać teraz :) a tak BTW to idąc Twoim tokiem rozumowania, to combust powinien też się double dipowac z masterka czyż nie? W końcu to osobny Spell,  niezależny od czegokolwiek innego! Litości.

**Comment by blinkmaster** [comment]
http://us.battle.net/wow/en/forum/topic/3881924750

**Comment by blinkmaster** [comment]
https://www.freakz.ro/forum/FIXED-Mage-Fire-Mastery-Ignite-Double-dip-on-resilience-t379872.html jeszcze z innego server priv zgłoszenie, tez potwierdza co mówię. Sorry ze nie w 1 poście ale na kom nie mogę edytować postów

**Comment by Aviannaqt** [comment]
Czyli działa dobrze tak?

**Comment by Jenovas** [comment]
Resi nie powinno redukować DMG ignite.
Ignite jest spellem zależnym od innego spella, czyli zadaje powiedzmy 50% DMG innego spella.
Jakby resi działało na ignite to mielibyśmy tzw double dipping, czyli nie dość że ingite jest mniejszy bo Fireball był mniejszy to jeszcze sam ignite znów by był pomniejszony.

Ignite powinien być redukowany przez spelle które obniżają DMG Taken. Jakby nie był to mielibyśmy sytuacje taką - Warrior dostaje ignite za 10k, odpala Shieldwalla który zmniejsza DMG a ignite dalej bije go za 10k.

Co do petów - robiłem testy, stojąc obok peta który mnie bił dodawałem sobie po 400 resi i z każdym wzrostem resi DMG peta z melee i z skilli spadał. Dla pewności sprawdziłem również kod i w kodzie jest sprawdzanie czy DMG jest od peta i czy właściciel peta jest graczem. Wszystko działa poprawnie.

**Comment by kadi2** [comment]
Na moja logike ignite, combustion powinno byc liczone z bazowego damage jego modyfikatorow (ignite - kazdy kryt) (combustion - ignite, pyroblast dot, living bomb) i dopiero pozniej modyfikowane przez wszystkie redukcje dynamicznie. Na tym filmiku znalazlem tylko dowod na ignite, nie mamy rowniez stu procentowej pewnosci co do combustion. Tak czy owak jest to temat na nowy bug report.

**Comment by BialyADI** [comment]
Wiem ze tak było, Resi redukowało Ignite.
Chyba że faktycznie potem to zmienili pod koniec Cata w jakimś patchu 4.3.x.

**Comment by Jenovas** [comment]
Nie. Jesteśmy na patchu 4.3.4 i pod niego są pisane wszystkie spelle. Nie będziemy przepisywać całej gry żeby 4.3.4 było patchem 4.2, bo nawet tooltipy spelli by się nie zgadzały.
