### ISSUE TITLE
[EN][PL][NPC] Deep Spider

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#5362]
**[EN]**
Deep Spider (Yellow Version): http://www.wowhead.com/npc=49815/deep-spider
Currently this NPC have 590k HP pool.
According to Wowhead it should be 7,096

----------------------------------------------
**[PL]**
Deep Spider (Wersja Żółta): http://www.wowhead.com/npc=49815/deep-spider
Aktualnie ten NPC ma 590k HP
Zgodnie z Wowhead powinno to być 7,096

**Comment by Bildo** [comment]
nie sugeruj sie wowheadem, od woda moby maja duzo nizsze hp

**Comment by Avalain** [comment]
@Bildo Dobrze, przestanę jeśli chodzi o HP, słuszna uwaga.

Pozostaje jednak problem, że te pająki (żółte) mają po 590k HP, podczas gdy podobne, fioletowe, w tej samej lokacji (Deepholm) posiadają około 7k HP.

Mały priorytet i serwer nie pęknie bez tej zmiany, jednak zawsze to małe odejście o oryginału.
