### ISSUE TITLE
[EN][Quest][Shadow Labyrinth]Trouble at Auchindoun(ID 29642)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5371]
NPC [Spymistress Mehlisah Highcrown](http://www.wowhead.com/npc=18893/spymistress-mehlisah-highcrown) is giving old quest [Trouble at Auchindoun(ID 10177)](http://www.wowhead.com/quest=10177/trouble-at-auchindoun) instead of [Trouble at Auchindoun(ID 29642)](http://www.wowhead.com/quest=29642/trouble-at-auchindoun). The quest [Trouble at Auchindoun(ID 10177)](http://www.wowhead.com/quest=10177/trouble-at-auchindoun) was replaced by [Trouble at Auchindoun(ID 29642)](http://www.wowhead.com/quest=29642/trouble-at-auchindoun) on 4.3 patch.

Wowhead Link: [Trouble at Auchindoun](http://www.wowhead.com/quest=29642/trouble-at-auchindoun)
Wowhead Link Obsolete one: [Trouble at Auchindoun(ID 10177)](http://www.wowhead.com/quest=10177/trouble-at-auchindoun)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7070-5371-quest-trouble-at-auchindoun-29642/
