### ISSUE TITLE
[PL][Item]Graccu's Mince Meat Fruitcake

### ISSUE THREAD

**Issue by probboy3** [Atlantiss/BugTracker#5374]
U świątecznych vendorów powinny znajdować się dwa placki, z jednym czyli:
 http://www.wowhead.com/item=17407/graccus-homemade-meat-pie  
jest wszystko ok, drugiego nie ma u żadnego z vendorów:
http://www.wowhead.com/item=21215/graccus-mince-meat-fruitcake

**Comment by Underliner** [comment]
I think you said that vendors are supposed to sell this cake but

"So this year, for all your joy and happiness,  Graccu's Mince Meat Fruitcake will be much easier to obtain. You can buy it from Kaymard Copperpinch or Macey Jinglepocket for 99 gold 99 copper"

This was added in 5.4.2.
