### ISSUE TITLE
[PL][Item]Stolen Present

### ISSUE THREAD

**Issue by probboy3** [Atlantiss/BugTracker#5375]
http://www.wowhead.com/item=116762/stolen-present#contains
Rzekoma stuprocentowa szansa na Graccu's Mince Meat Fruitcake (http://www.wowhead.com/item=21215/graccus-mince-meat-fruitcake) nie działa, tym samym przekreśla to możliwość otrzymania achievmentu za event świąteczny biorąc pod uwagę, że tego itemku nie ma u vendorów.

https://github.com/Atlantiss/BugTracker/issues/5374  (dotyczy braku itemów u vendorów)

**Comment by probboy3** [comment]
x

**Comment by Bildo** [comment]
it shouldn't drop rom Stolen Present

**Comment by probboy3** [comment]
so how the hell i can get it, when two years ago this achievment wasn't working and now it's not possible to get this item in any way?...
