### ISSUE TITLE
[PL][Warrior] Damage taken give no rage

### ISSUE THREAD

**Issue by Moks** [Atlantiss/BugTracker#5377]
Warrior powinien generować rage kiedy otrzymuje obrażenia. 

http://wow.gamepedia.com/Rage

Niestety jedyne strony jakie znalazłem, które posiadają wzmianek o generowaniu rage poprzez otrzymywane obrażenia na dodatku cataclysm to:

http://calltoarms.blog.com/2010/11/26/rage-normalization-what-it-is-and-what-it-isnt/
http://www.mmo-champion.com/threads/851623-Rage-Normalisation-Calculation

**Comment by BialyADI** [comment]
Tutaj jest ile powinien generować: http://calltoarms.blog.com/2010/11/26/rage-normalization-what-it-is-and-what-it-isnt/

Warrior generuje Rage gdy dostaje Dmg, ta wartość najwyżej na Atlantissie nie poprawna.

**Comment by Jenovas** [comment]
Działa poprawnie. Rage za DMG otrzymany jest poprostu bardzo mały. Za około 150k DMG otrymanego masz około 50 rage. Jest to poprawne.

**Comment by BialyADI** [comment]
na lvl 85 powinno to wyglądac mnie jwiecej tak :p:

    950 damage melee swings gave me 1 rage every time.
    3700 damage Howling Blast gave me 3 rage.
    4300 damage Chaos Bolt gave me 4 rage.
    5300 damage Soul Fire gave me 4 rage.
    9500 damage Chaos Bolt crit gave me 8 rage.
    12530 damage Soul Fire crit gave me 11 rage.
    1700 damage Immolate DoT gave me 1 rage

So the pattern is somewhat seeable. An awfully rounded rule of thumb could be 1 rage per 1000 damage, but as we can all see, it isn’t exactly true, but quite close.

lecz pewno ilość maksymalnego Hp tez ma znaczenie

**Comment by Jenovas** [comment]
Facet napisał że robił te testy majać 44k Max HP, więc pewnie jak masz tyle HP to tyle się dostaje, później to się skaluje że im więcej HP tym mniej rage się dostaje. Pokazywałem kiedyś filmiki bo był podobny temat i mamy w miarę poprawnie.
