### ISSUE TITLE
[EN][Quest] Cultivating an image

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#538]
In the quest **Cultivating an image** (http://www.wowhead.com/quest=12184), you can use a provided quest item, **Kilian's Camera** (http://www.wowhead.com/item=37045) repeatedly on one Iron dwarf corpse to get all the quest counts, but how it should work is that you should have to use it on 8 different iron dwarf corpses.

**Comment by Bildo** [comment]
fixed in rev 4245
