### ISSUE TITLE
[PL][Warrior][Druid?] Rage from taking Dmg.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5382]
Jak jest:
Redukując otrzymany Dmg(hit) redukujemy otrzymany Rage za ten Dmg.

Jak powinno być:
Redukując Dmg takim sposobami jak Resi/Armor/Umiejętność(np. Shield Wall)/Talenty nie powinno redukować się otrzymywanego Rage za ten Hit.
Którko mówiąc obliczanie otrzymanego Rage za Hit powinno się odbywać przed jakąkolwiek redukcją Dmg przez Armor, Resilience, Skille, Talenty, Block, Parry, Dodge, Absorb, Resist.

Dowody:
Bluepost: http://www.wowhead.com/news=151357.3/rage-normalization-in-cataclysm
"Rage from damage taken will no longer be based on a standard creature of the character’s level, but instead will based on the health of the warrior or druid. Again, there is a constant that is multiplied by the rage generated in order to allow for fine-tuning. This calculation ignores all damage reduction from armor, absorption, avoidance, block, or similar mechanics, so improving your gear will not reduce Rage gained."

http://calltoarms.blog.com/2010/11/26/rage-normalization-what-it-is-and-what-it-isnt/
"A dodge and parry might follow the same pattern, ~1 rage per 1000 damage dodged/parried. I’m not exactly sure if it scales up, cos Ceraius was such a whimp and wouldn’t hit hard enough to get reliable results easily. Could be easier in a bossfight where I get hit for a lot more, but that wasn’t an option at the time of writing. But you will at least get that 1 rage per dodge/parry. Would make sense for the rage amount scale with the hit, though, have to confirm that later."

Napisał że Parrując/Dodgujac atak, dostawał Rage tak jak by został trafiony i otrzymywał Dmg.
Swoją drogą ma to sens bo teraz zwiększając swoje statystyki defensywne(Parry Chance/Block/Armor/itd) drastycznie zmniejszamy generowany Rage z otrzymanego Dmg.

Grając na Cata prawdę mówiąc nie zwracałem na to uwagi ile generuje Rage z tego co mnie bija ;D.
Lecz sprawdziłem u nas jeszcze coś, jak zbiłem swojego warka z 100% do 0% to po Duelu zostawało mu 19 Rage mialem wtedy PvP set i Def stance.
Tutaj: http://calltoarms.blog.com/2010/11/26/rage-normalization-what-it-is-and-what-it-isnt/
ktoś testował jak wygląda generowanie Rage. Typek ma 44k HP i napisał że:
"4300 damage Chaos Bolt gave me 4 rage."
Wiec żeby go zbić z 100% do 0% 4300 * 10 = 43k => 4Rage * 10 = 40 tyle by miał Rage jak by go zbito z 100% do 0%.
To takie moje spostrzeżenie, w każdym bądź razie widać że redukując otrzymany Dmg redukujemy otrzymany Rage u nas.

No i tyle mam nadzieje że się przyda ^^.
Dość poważny bug dla tanków w PvE. Na na przykład jak taki Druid misio jak Dodguje atak Bossa to nie dostaje Rage a powinien dostać tak samo z Warkiem jak zablokuje atak czy Parry.  
Zakładając że sama formuła zdobywanego Rage z Dmg jest poprawna wystarczyło by obliczenia były robione przed redukcją otrzymanego Dmg.

Dodatkowo ss z testów:
![wowscrnshot_122415_013801](https://cloud.githubusercontent.com/assets/5780624/11987668/785d0682-a9e3-11e5-841a-42613395f1f7.jpg)
Tutaj dostałem hita jak widać i wygenerowało się 4 Rage.
![wowscrnshot_122415_013952](https://cloud.githubusercontent.com/assets/5780624/11987669/7ba887da-a9e3-11e5-8006-576c501c9fe9.jpg)
A tutaj mam jeszcze na sobie Shield Walla 40% redukcji i tyle samo Resi i wygenerowało 2.
Gdybym nie miał Resi ani Shield Wall prawdopodobnie wygenerował bym z 6 Rage i to by było coś bliskiego poprawnej wartości ;p.

**Comment by BialyADI** [comment]
Jeszcze w ten wigilijny poranek jedna rzecz mi się przypomniała.
Filmiki Swiftiego ^^! Gdze często testował Dmg innych klas jak go zbijają z 100% do 0%.

Przykład bo ma tych filmików wiele:
https://youtu.be/ThIYOrbzW2U?t=2m40s
Rogal po zbiciu go do 0 zostawia mu ok. 60% Rage czyli 60 Rage.
U nas taki sam test skończył by się tym ze Warek czy Druid Misiek miał by ok. 25 Rage.

Czemu tak jest ;D? 
Powiedzmy że jest sobie Warek który ma 100k HP i tyle Armoru by miał 50% redukcji, czyli taki Rogal musiał by zrobić 200k "czystego" Dmg żeby ubić takiego Warka.
U nas tylko te 100k równe HP Wraka jest przeliczane na Rage a powinno być 200k przed redukcją.
A do tego w trakcie walki może się trafić jakiś Parry czy Absorb i jeszcze Resi i inne redukcje i wychodzi na to że tak naprawdę tylko ułamek tego "czystego" Dmg sprzed redukcji Dmg jest obliczane na Rage. I dla tego może się wydawać że na Atlantissie nie dostaje się Rage za otrzymany Dmg
Jak tak pomysleć dość poważny Bug przynajmniej dla Tanków i w PvP.

Sry że aż tak łopatologicznie to wyjaśniłem wiem że nie było to konieczne ale lubię takie coś "rozkminiać".
Mam nadzieję że uda się to łatwo naprawić.

Wesołych Świąt ;).

**Comment by Jenovas** [comment]
Rage z DMG Taken działa poprawnie.
Właśnie sprawdziłem na warku który ma 0 resi i 200k HP, Warku który ma 4000 resi i 200k HP, Warku który ma 4000 resi i 100k HP, w każdym przypadku zbicie go od 100% do 0% dawało mu około 40-50 rage.
Żeby zobaczyć jak to działa proszę oglądnij sobie ten filmik - https://www.youtube.com/watch?v=vFVKI8F0gYk

W zależności od klasy czy klasa zadaje mały DMG a często czy duży DMG a rzadziej tak rośnie rage. Przykład z duelem z feral druidem dostał tylko 30 rage z DKsem dostał 60 rage.

Jedyny bug do naprawy to żeby po parry/block/dodge też dawało rage, ale to muszę doczytać.

**Comment by BialyADI** [comment]
https://github.com/Atlantiss/BugTracker/issues/5503
Teraz generowanie jest totalnie zrąbane juz nawet nie chodzi że mało generuje ale w ogole teraz nic ;x.

**Comment by Jenovas** [comment]
Wychodzi na to że spelle nie generują, bo robiłem testy z rogalem i rosło prawidłowo, nawet za dodge i parry rośnie rage.

**Comment by Jenovas** [comment]
Fixed in rev 4755

**Comment by BialyADI** [comment]
Jeśli tak to fanie oby było git ;D.
Jeszcze tylko ten nieszczęsny Field Dressing żeby zwiększał ten Heal poprawnie i będzie wszystko ok z Warkami.
Po testuje potem DK czy u nich wszystko jest ok.
