### ISSUE TITLE
[PL][World Event][Quest] You're a Mean One...

### ISSUE THREAD

**Issue by Deonorth** [Atlantiss/BugTracker#5385]
Mam odmienny problem z questem niż wszyscy. Mianowicie mam tą paczkę z ukradzionego skarbu, w okienku questa mi go zalicza ale nie mogę oddać questa ..

**Comment by Aviannaqt** [comment]
Dołączam do #5292

**Comment by Underliner** [comment]
Did you save Metzen?

**Comment by Bildo** [comment]
Clear cache
