### ISSUE TITLE
[EN][Spell][Zone]

### ISSUE THREAD

**Issue by jokehold** [Atlantiss/BugTracker#5386]
I have stumbled upon a bug.
Near Zul'Farrak's entrance, Deathwings spell "Molten Flame" kills you everytime!
Also he is not trying to dissapear.
Wowhead : http://www.wowhead.com/search?q=Zul%27Farrak
http://www.wowhead.com/spell=94644/molten-flame

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/5389
