### ISSUE TITLE
[EN][NPC][Tanaris] Duneclaw Broodling

### ISSUE THREAD

**Issue by jokehold** [Atlantiss/BugTracker#5387]
In Tanaris Duneclaw Broodling must have 166 Healthpoint but instead he has 2k+.

Wowhead: http://www.wowhead.com/npc=40666/duneclaw-broodling
    Zone: http://www.wowhead.com/zone=440/tanaris

**Comment by eryczek1615** [comment]
this is hp from Draenor or Legion. On the cataclysm he should  have 2k
