### ISSUE TITLE
Crash at quest "The Hungry Ettin"

### ISSUE THREAD

**Issue by kry631** [Atlantiss/BugTracker#5388]
First, when I bring every 5 horses Lorna dissappears:
![wowscrnshot_122415_111632](https://cloud.githubusercontent.com/assets/16166875/11993425/1fb8b4ce-aa31-11e5-870e-6650d210c2fe.jpg)
On second, when I go to her later, game crash with error 132

**Comment by Underliner** [comment]
You're a bit off with the format.
Read this: https://github.com/Atlantiss/BugTracker
