### ISSUE TITLE
[EN]Patrolling mobs stopped patrolling

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5389]
Since yesterday (I believe) dec 23, mobs all over the place that used to patrol have stopped patrolling. This isn't just limited to dungeons/raids but also through azeroth, outlands and northrend. 

#5386 is a related post. Because Deathwing doesn't fly around anymore, he messes up quite a big chunk of Tanaris as you can't get close to it or you die. 

This issue hasn't affected escort quests thankfully, but it's an issue that needs addressing

**Comment by Bildo** [comment]
I know where the problem is.

**Comment by Bildo** [comment]
Problem will disappear after restart/crash.

**Comment by Luna-maria** [comment]
cool, thanks :3
