### ISSUE TITLE
[PL][Npc]Tyrus Blackhorn

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5392]
Tych npc jest za duzo 
http://www.wowhead.com/npc=39933/tyrus-blackhorn
![wowscrnshot_122415_165523](https://cloud.githubusercontent.com/assets/16046575/11997267/afc6364a-aa77-11e5-8e89-c3bfb7645a2a.jpg)

**Comment by Aviannaqt** [comment]
#3927
