### ISSUE TITLE
[PL][Quest] Aessina's Miracle

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5393]
Zle pokazuje na mapie gdzie sie oddaje Q
http://www.wowhead.com/quest=25372/aessinas-miracle
![wowscrnshot_122415_194437](https://cloud.githubusercontent.com/assets/16046575/11997272/f7b6f49e-aa77-11e5-9674-e3edcc742be7.jpg)

**Comment by Wolffenstein** [comment]
Dobrze pokazuje, to npc stoi w złym miejscu.

**Comment by Lopfest** [comment]
I think there is just bad phasing. The NPC is ok.

**Comment by tomatosz** [comment]
This is blizzlike, you're supposed to hand it in at Shrine of Aessina (where the marker is), but it's also possible to do it at Sanctuary of Malorne.
