### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] Ogre Heaven

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5395]
This is the quest:http://www.wowhead.com/quest=11009/ogre-heaven
According to wowhead and wowiki (http://wowwiki.wikia.com/wiki/Quest:Ogre_Heaven) this quest should be available only after completing the quest "Into the soulgrinder" http://wowwiki.wikia.com/wiki/Quest:Into_the_Soulgrinder / http://www.wowhead.com/quest=11000/into-the-soulgrinder).
At the moment, the quest Ogre Heaven is available anyway.

**Comment by Bildo** [comment]
fixed
