### ISSUE TITLE
[EN][NPC][Tanaris] Deathwing stuck

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#5398]
In Tanaris, almost in front of Zul'Farrak entrance Deathwing got stuck. He's above the ground, but staying in one spot with looped animation when he breathes fire. It won't be big deal, if not fact that in pretty big range he insta-kills all nearby players, and when you ress in this range, you die again, so makes you almost unable to ress (somehow I managed, but I died on border of his killing range). 
http://i.imgur.com/JcDauHf.jpg 
http://i.imgur.com/uzh56bO.jpg he's probably somewhere close to this green circle. 
From what I heard, he's chilling there since yesterday.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/5389
