### ISSUE TITLE
[PL][Warrior] Mastery: Unshackled Fury don't work!

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5400]
Jak jest:
Masterka Fury Warka nie działa.

Zrobiłem szybki test po wbiciu 80 i nauczeniu się Masterki. Odpaliłem Enraged Regeneration i coś mi nie grało bo wyleczyło mnie za tyle samo jak bym nie miał Masterki, wiec zrobiłem test jeszcze raz, z i bez talentów na takim samym HP.

Screeny:
Bez talentów:
![wowscrnshot_122515_080918](https://cloud.githubusercontent.com/assets/5780624/12000892/e298709e-aade-11e5-803c-48f1efe94a2f.jpg)
ER leczył mnie po 651, łącznie 6510 czyli git bo mam 21,7k / 0,3 = 6510

Teraz z Masterką:
![wowscrnshot_122515_081246](https://cloud.githubusercontent.com/assets/5780624/12000924/506a15c8-aadf-11e5-9fe5-adc35c2cdc6f.jpg)
Tez zostałem wyleczony za łącznie 6510 a z Masterka powinno być o 2(tyle mam mastery) * 5,6% = 11,2% więcej, czyli 6510 * 1,112 = 7239 HP.
Nawet Tooltip pokazuje że powinienem być wyleczony za ~33% mojego HP.
Straszna lipa że takie coś się wkradło na Atlantissa, Bug bardzo poważny ;x.
No nic uciekam.

**Comment by Kejmil** [comment]
to teraz zrob respec w ta i w tamta, zauwaz ze juz dziala poprawnie i zamknij to zgloszenie :D

**Comment by kadi2** [comment]
Nie dziala to tutaj w ten sposob, ze musisz rozdac przynajmniej jeden talent zeby mastery zaczelo dzialac?

**Comment by Kejmil** [comment]
predzej bym obstawial ze cos jest nie tak z sama masterka fury warka
to normalne ze fury ma bazowe tylko 2 punkty mastery? obnizone mastery wzgledem innych klas ma na pewno frost mage ale tam masz za wybor specjalizacji wprost napisane ze "masterka obnizona, ale spoko frostbolt mocniej bije", tutaj nic takiego nie ma

**Comment by Jenovas** [comment]
Działa poprawnie. Naprawdopodobniej zbugowało Ci się mastery i GM musi Ci pomoc, albo zwykly relog / rebuild Ci naprawi mastery.

**Comment by Jenovas** [comment]
A co do 2 Mastery - patch 4.1 - Fury
Unshackled Fury now only grants 2 base points of mastery, down from 8.
