### ISSUE TITLE
[PL][Warrior][Talent] Field Dressing

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5401]
http://cata.openwow.com/spell=84580 <-- Field Dressing
http://cata.openwow.com/spell=55694 <-- ER

Jak jest:
Sprawdziłem ten talent na Enraged Regeneration i zwiększa lecznie ER tylko o "Increases all healing received by 6%".
Natomiast "and the effectiveness of your self-healing abilities by an additional 20%." jest całkowicie nie brane po uwage w końcu ER to nasz Self-heal.

Jak powinno być:
Heal z ER powinien być zwiększony o 1,06 * 1,2 = 1,272. Sam już nie wiem czego to wina czy Talentu czy skopane coś jest z Enraged Regeneration, może ER jest traktowany jak by ktoś go na nas rzucił?

**Comment by BialyADI** [comment]
Jenovas jeszcze jedno zobaczyłem talent Blood Craze(http://cata.openwow.com/spell=16489) ma natomiast na odwrót dostaje zwiększony Heal o 20% z Field Dressing ale nie dostaje 6% bonusu z Field Dressing.

Jak możesz przetestuj Masterke Fury Warka jeszcze raz, dostałem unbuff od GM i z masterka ciagle cos się wali albo za mało dostaje bonusu albo w ogóle.
Sprawdz tak postać na 80 lvl i 0 dodatkowego mastery tylko te standardowe 2 mastery czyli ~11% i wtedy mastery nie dzialana Enraged Regeneration przynajmniej.

**Comment by kadi2** [comment]
http://eu.battle.net/wow/en/forum/topic/3144505757#2

**Comment by BialyADI** [comment]
Hmm jeszcze ciekawe jak jest z Second Wind i Field Dressing.

**Comment by BialyADI** [comment]
Jeszcze coś sobie teraz sprawdziłem mianowicie bandaże, też powinny być zwiększane przez 6% i 20% a są teraz tylko przez 6%.

Dowód bo to może nie być oczywiste ;p.
http://us.battle.net/wow/en/forum/topic/1127129067
"It does affect bandages. Not sure on the enchants, but I would assume the Draenei self-heal and Undead cannibalize would also be affected, as well as potions. " 
Niewiem jak u ans jest z Potami ale to już mały pikuś.
Bardziej przydało by się by działało to też z Racialem Draneja, nie wiem jak teraz jest ale pewno nie działa a powinien.

http://www.wowhead.com/forums&topic=184187/field-dressing-what-it-affects-what-it-doesnt
"As i recall, yes it does affect bandages."

Reasumując:
Na pewno powinno być zwiększane przez 6% i 20%:
-Second Wind
-Victory Rush
-Blood Thirst
-Enraged Regeneration
-Bloodcraze
-Bandages

**Comment by Jenovas** [comment]
Czyli wychodzi na to że ten 20% w ogóle nie działa?

**Comment by BialyADI** [comment]
Ta można tak powiedzieć.
Te 20% aktualnie działa popranie tylko i wyłącznie na Victory Rush i BloodThirst i koniec ^^.

**Comment by BialyADI** [comment]
Jeszcze jedną rzecz sprawdziłem z Engineering mianowicie Spinal Healing Injector(http://cata.openwow.com/spell=82200, http://cata.openwow.com/spell=82184) też jest tylko większany o 6% a jako nasz Potion powinien być o 6% i 20%.

**Comment by BialyADI** [comment]
Bump! Jenovas plz fix it.
And Happy New Year ^^.

**Comment by BialyADI** [comment]
Plz, if that fix need time, only repair Enraged Regeneration it is so annoying that it Heal 20% less than it should ;<.

**Comment by Jenovas** [comment]
Dobra sprawdziłem.
O 20% powinien być zwiększany tylko Heal z spelli Warriora. Nie powinno wpływać na potiony, nie powinno wpływać na raciale etc.

Powinno wpływać na 100% na - 
23880 - Bloodthirst
29841 - Second Wind (Rank 1)
29842 - Second Wind (Rank 2)
34428 - Victory Rush
55694 - Enraged Regeneration

**Comment by BialyADI** [comment]
Talent Blood Craze - http://cata.openwow.com/spell=16492 tez dawałem na to dowody wyrzej
i bandaże.

ale i tak głównie sie tu rozchodzi o Enraged Regeneration bo te 20% jest spooro.

**Comment by BialyADI** [comment]
Jako dowód:
http://us.battle.net/wow/en/forum/topic/2369918917

"Actually you didn't even fix it properly. Percent bonuses rarely stack by straight addition. They stack by multiplication.

Blood Craze: 3% * 1.2 * 1.06 = 3.816%
Second Wind: 5% * 1.2 * 1.06 = 6.36%"

**Comment by Jenovas** [comment]
Fixed in rev 4812
Field Dressing will now increase the healing of Enraged Regeneration, Blood Craze and Second Wind

**Comment by BialyADI** [comment]
Yeah!
Good work men xD.
