### ISSUE TITLE
[EN][Blade's Edge Mountains][NPC][minor] Ogri'la Peacekeeper

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5402]
http://wowwiki.wikia.com/wiki/Ogri'la_Peacekeeper
http://www.wowhead.com/npc=23115/ogrila-peacekeeper#abilities

How it is bugged: On Atlantiss these guards have only 10 health points.

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7112-52275402-too-low-hp-for-several-npc/
