### ISSUE TITLE
[PL][Quest] The Atlar of Storms 

### ISSUE THREAD

**Issue by vrubik987** [Atlantiss/BugTracker#5407]
http://www.wowhead.com/quest=25688/the-altar-of-storms
Loramus pojawia się i tyle, czekałem 5 minut na jakiś cud, ale nic się nie stało. 
![wowscrnshot_122515_134302](https://cloud.githubusercontent.com/assets/16436600/12002942/6b2609ce-ab0e-11e5-9a44-345a27f76eea.jpg)

**Comment by Bildo** [comment]
przeczytaj zasady bt
