### ISSUE TITLE
[PL][NPC][Wintergrasp] Solid Ice

### ISSUE THREAD

**Issue by vrubik987** [Atlantiss/BugTracker#5408]
http://www.wowhead.com/npc=49233/solid-ice
Lód zadaje mi obrażenia jak widać na Combat Logu. 
![wowscrnshot_122415_204603](https://cloud.githubusercontent.com/assets/16436600/12002983/a9bcdef0-ab0f-11e5-94a1-fcef4dde282d.jpg)

**Comment by Aviannaqt** [comment]
#2926
