### ISSUE TITLE
[PL][Warrior] Enraged Regeneration

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5409]
Sry że tak na raty to piszę jakiś zmulony jestem po pasterce ale to rzeczy.
Nawiązując do tego zgłoszenia https://github.com/Atlantiss/BugTracker/issues/5400.

Wiem już co jest przyczyna tego, Masterka działa ok, przetestowałem Dmg i było ok(geniusz ;D).
Tu jest problem tylko i wyłącznie z ER!
Enraged Regeneration ani nie jest zwiększane przez Masterkę ani przez Talent Field Dressing.

Dowod(google pierwsze z góry):
http://us.battle.net/wow/en/forum/topic/2135903968
"For each point beyond 8, you get 5.6 additional %.
This total % increases the effect of your:
-Enraged Regeneration
-Raging Blow
-Death Wish
-Enrage Talent (though it cannot stack with Death Wish)"

http://eu.battle.net/wow/en/forum/topic/1622868988
"More damage from Raging Blow (requires enrage)
Bigger dmg boost from Death Wish (causes enrage)
More healing from Enraged Regeneration (requires enrage)"

"Enraged Regeneration (my Enraged Regeneration heals for >50% as fury when it heals 36% as Protection, lol)"

No i tyle Tooltip tez pokazuje że powinnien ER więcej leczyć w Fury o ilość Mastery, no i pamięć też mnie nie myli.

**Comment by Jenovas** [comment]
Masterka poprawnie wpływa na heal z Enraged Regeneration. Sprawdzałem to dziś kilkakrotnie. Jeżeli nie działa tzn że musisz poprosić GMa o .unaura all najlepiej i relog / retalent / zmiana speca.

Talent Field Dressing rzeczywiście nie wpływa na Enraged Regen.

**Comment by BialyADI** [comment]
O ja jebie czyli to było cały czas tylko u mnie(facepalm) no na to nie wpadłem, narazie niby działa ;D.

**Comment by Jenovas** [comment]
Ogólnie widzę że mamy problem z mastery, bo mamy coraz więcej zgłoszeń że mastery przestaje działać, ale jest to bug ogólny i niestety nie wiem po czym mastery przestaje działać i trzeba prosić GMa o pomoc albo samemu próbować odbugować. W wolnym czasie popatrzę na to. A Field Dressing postaram się niedługo poprawić.

**Comment by BialyADI** [comment]
Jenovas jeszcze jedno zobaczyłem talent Blood Craze(http://cata.openwow.com/spell=16489) ma natomiast na odwrót dostaje zwiększony Heal o 20% z Field Dressing ale nie dostaje 6% bonusu z Field Dressing.
