### ISSUE TITLE
[PL][Npc]Lurking Tempest

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5413]
Te npc sa zbugowane 
http://www.wowhead.com/npc=45704/lurking-tempest
![wowscrnshot_122515_024057](https://cloud.githubusercontent.com/assets/16046575/12003474/1eea04ee-ab21-11e5-8836-7cb7d019d2a2.jpg)

**Comment by Aviannaqt** [comment]
Jakies dowody? Jak powinny dzialac?

**Comment by eryczek1615** [comment]
Tak powinny działać.
