### ISSUE TITLE
[PL][Other]Mental Training: Speaking the Truth to Power

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5416]
Po wykonaniu tego Q gdy uzyje cat form psuje sie ui 
http://www.wowhead.com/quest=25299/mental-training-speaking-the-truth-to-power
![wowscrnshot_122515_160014](https://cloud.githubusercontent.com/assets/16046575/12003496/3e05c3d0-ab22-11e5-9896-6149b292f449.jpg)

**Comment by vrubik987** [comment]
To juz chyba wina addonów których uzywasz

**Comment by vragni** [comment]
Do Mam tylko Dbm , healboot , Error Filter , Minimap button frame , wiec do zmiany ui raczej nic nie mam

**Comment by Aviannaqt** [comment]
I pewnie wystarczy reload zeby wszystko sie naprawilo tak?

**Comment by vragni** [comment]
Tak
