### ISSUE TITLE
[EN][NPC]Grand Apothecary Putress

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5421]
http://www.wowhead.com/npc=31530/grand-apothecary-putress
I don't know if that's the right link but it's the only one I could find on wowhead

There is a lvl 1 friendly Grand Apothecary Putress next to the Aldor bank in Shattrath. Pretty darn sure he shouldn't be there :)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7799-5421-npcgrand-apothecary-putress/
