### ISSUE TITLE
[PL][NPC][hellfire peninsula] Blistering Oozeling

### ISSUE THREAD

**Issue by vrubik987** [Atlantiss/BugTracker#5423]
Te oozony mają złe hp, maja ~3900hp a powinni mieć 152hp
http://www.wowhead.com/npc=16903/blistering-oozeling
![wowscrnshot_122615_082226](https://cloud.githubusercontent.com/assets/16436600/12005527/403fff8e-abaa-11e5-84c0-dfd26745d317.jpg)

**Comment by aje** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7798-5423-npc-blistering-oozeling/
