### ISSUE TITLE
Shadowstep 

### ISSUE THREAD

**Issue by LaRussoo** [Atlantiss/BugTracker#5424]
When i use shadowstep on enemy near wall or little hill, i fal into textures and die. I must wait for release, because i cant use "release spirit button" or unstuck. It happened to me 4 times in last hour, its really annonying, fix this shit

**Comment by magromo** [comment]
Shadowstep is one of the most bugged skills, throws you to air, bottom of the ocean, under textures or simply nowhere

**Comment by Luna-maria** [comment]
1: post will be ignored if you don't follow the guidelines when it comes to the title
2: already reported and known issue (there's a search function, might want to use it before posting something)
