### ISSUE TITLE
[EN][PVP][Warlock][Pet][Succubus][Whiplash] Ability Broken

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#5425]
The the ability Whiplash http://www.wowhead.com/spell=6360/whiplash of the Warlock's pet Succubus is behaving randomly. Sometimes it doesn't knock back for no apparent reason. Also, whenever the target is in stun, roots, fear, frozen or otherwise, Whiplash doesn't work.

**Comment by kadi2** [comment]
It's supposed to not work in roots.

**Comment by Illusie** [comment]
Maybe it does not knockback duo texture? like you try to knockback someone who rooted or who cannot be knocked duo Walls / Tree / Obstacles

**Comment by kadi2** [comment]
It's common on the server that typhoon doesn't work in pvp.
