### ISSUE TITLE
[EN] [Class] [Paladin] [Movement Speed]

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#5427]
![wowscrnshot_122615_152514](https://cloud.githubusercontent.com/assets/16444508/12006588/18d21d2a-abe5-11e5-87bd-38f725af1dac.jpg)

I am not sure if it's me being retarded and missing something but i don't really see a reason having 152% movement speed without any buffs or being mounted. I do have the talent  [Pursuit of Justice] from retribution tree which increase movement speed by 15% making max movement speed 115% unmounted however sometimes i get 132% or in this case 152% (my boots enchant is 50 mastery meaning I don't have additional MS from enchants). Also this is not visual bug I'm actually running faster than other retribution paladins with  [Pursuit of Justice] talent.

**Comment by Aviannaqt** [comment]
mm.. try respec / talent reset
