### ISSUE TITLE
[EN][Metamorphis][Warlock] Metamorphis damage % increase is dynamic not static

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5431]
When you get a mastery increase in metamorphis it will increase your % damage buff, same if you lose the buff you it will decrease your % damage buff. 
http://www.wowhead.com/spell=103958/metamorphosis
It is supposed to be like this: When metamorphis is cast it will snapshot ur mastery value and increase the damage by a static amount during the full duration.
http://www.tauri-veins.tk/demonology-warlock-wow-pve-dps-rotation-cooldowns-abilities (go to 8.5.1)
Your Mastery (Master Demonologist) is recorded when you cast Metamorphosis, and it affects the damage you deal while you are in Metamorphosis. Further changes to your Mastery will not be taken into account while Metamorphosis is active. As such, if you have trinkets that increase your Mastery (most notably, Moonwell Chalice), you should have these active before you cast Metamorphosis.

This is basicly the same bug with doomguard that is supposed to snapshot your stats when cast and have static damage instead of dynamic. This is not that huge of a bug for demo in t11, but with firelands release and the molten front trinekts, aka moonwell chalice it is a huge dps loss if we cant benefit from using the trinket alongside metamorphis. Please fix this =))))

**Comment by anxanas** [comment]
Put high priority too =)))

**Comment by kadi2** [comment]
Did you test the real damage, or just a tooltip?

**Comment by anxanas** [comment]
I tested real damage, tooltip doesnt change

**Comment by Illusie** [comment]
Fix demo plz ! my spec for PvE ;d

**Comment by anxanas** [comment]
People will be able to get Moonwell chalice in 2-3 days, and i am just wondering if the meta bug will be fixed soon, if not it will greatly devalue the trinket that is supposed to be bis

**Comment by troublemakerr** [comment]
Bump

**Comment by Sepsis-Atlantiss** [comment]
bumpp

**Comment by Madwag** [comment]
Fix this please, my warlock will get trinket soon

**Comment by Necromnef** [comment]
Bump, i hope you will fix this and the doomguard soon.

**Comment by Kejmil** [comment]
doomguard will be fixed at the same time that ghoul in frost/blood Kappa

**Comment by anxanas** [comment]
Who cares about a ghoul in any other spec than unholy. Doomguard is such a vital part of dps in all warlock specs especially demo. This is not the bug being reported here though, the bug is metamorphis having dynamic damage increase while it should be static

**Comment by Wolffenstein** [comment]
Fixed in rev 4820.

**Comment by anxanas** [comment]
TYVM FOR FIX =))))))))))
