### ISSUE TITLE
[EN][Quest]Into The Black Tooth Hovel

### ISSUE THREAD

**Issue by CristiPV** [Atlantiss/BugTracker#5433]
The NPC that I am supposed to talk to, Quartermaster Kaoshin is hostile to me, and as soon as I approach him, he attacks.
So, after killing him, the quest's question mark on the minimap remains.

**Comment by TheCopacabanaMan** [comment]
Hey! Where is Quartermaster Kaoshin? Question mark is on Map & MiniMap, but Kaoshin not spawns
