### ISSUE TITLE
[PL][Npc]Living Blood

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5436]
Te Npc maja za duzy dps
http://www.wowhead.com/npc=43123/living-blood
![wowscrnshot_122615_140244](https://cloud.githubusercontent.com/assets/16046575/12007879/c7c8eff0-ac19-11e5-9d24-766544a4c10e.jpg)

**Comment by eryczek1615** [comment]
Już w Hyjal npc powinny bić  1-1.5k więc w Deepholm jest dobrze powinny bić 2k zaś w Uldum bug że biją za mało
