### ISSUE TITLE
[PL][Spell][Shaman] Flametongue Weapon

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5439]
https://github.com/Atlantiss/BugTracker/issues/4348 <-- Stare źle poprawione zgłoszenie.

Jak jest:
Bug z Flametongue Weapon nadal występuje.
Normalnie jak zaczniemy bić kukle jest ok ale jak użyjemy jakiegoś Skilla(StormStrike, Enleash Elements) to Flametongue Weapon zaczyna bić z Main-handa i Off-handa a powinien tylko z Off-handa no chyba że jest nałożony na obie bronie.

Czasem trzeba kilka razy walnąć z StormStrike, Enleash Elements jest to w jakimiś stopniu losowe ale w końcu zacznie Flametongue Weapon bić z obu broni mimo że jest tylko na Off-hendzie.

Dowód w postaci Screena:
![wowscrnshot_122715_080639](https://cloud.githubusercontent.com/assets/5780624/12009252/e5b0aac4-ac70-11e5-954c-c3f943b50e1c.jpg)

**Comment by lamaATS** [comment]
Fixed in rev. 5254

**Comment by BialyADI** [comment]
@lamaATS https://github.com/Atlantiss/BugTracker/issues/8575

**Comment by BialyADI** [comment]
Co od samego Flametongue Weapon też bije za wiele, powinien teoretycznie od 99 do 305 zależnie od szybkości broni i tak bił a teraz jest jakaś masakra ;D.
![wowscrnshot_111816_130134](https://cloud.githubusercontent.com/assets/5780624/20429474/2e8a4da2-ad8f-11e6-9e71-1f215178a9d6.jpg)

**Comment by lamaATS** [comment]
Tooltip tego spella jest kompletnie bezużyteczny niestety bo tam jest stała wartość bez jakichkolwiek bonusów.
