### ISSUE TITLE
Achievement: Explore Azuremyst Isle bug + EXP bug

### ISSUE THREAD

**Issue by Emielos** [Atlantiss/BugTracker#5444]
http://www.wowhead.com/achievement=860/explore-azuremyst-isle

Unable to complete, because Bristlelimb Village cannot be explored.
While questing here, there was a chain quest where you turn into a cat.
After arriving at Bristlelimb Village the monsters there gave way too much EXP (800-1000exp)
This is my first report so i hope i gave enough info on this bug.

**Comment by RandomPickNewb** [comment]
Read https://github.com/Atlantiss/BugTracker and change the tittle
