### ISSUE TITLE
[EN][Quest][Netherstorm] Summoner Kanthin's Prize

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5447]
http://www.wowhead.com/quest=10209/summoner-kanthins-prize

http://www.wowhead.com/item=28479 should have a 100% droprate according to comments, it doesn't right now

**Comment by Navedonar** [comment]
http://us.battle.net/wow/en/item/28479

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7442-5447quest-summoner-kanthins-prize/?p=27298
