### ISSUE TITLE
[EN] Honor Vendor selling the wrong dagger for spellcasters

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#5449]
http://imgur.com/sERufPV

I guess this dagger should be spell caster one, since there is no other dagger to be found there.

**Comment by RelmAtlantiss** [comment]
Confirmed, season 9 one-hand weapons are missing from the honor vendor.

NPC:
http://www.wowhead.com/npc=54659/blood-guard-zarshi

Missing items:
http://www.wowhead.com/item=61329/vicious-gladiators-spellblade
http://www.wowhead.com/item=61327/vicious-gladiators-shanker
http://www.wowhead.com/item=61338/vicious-gladiators-gavel
http://www.wowhead.com/item=61336/vicious-gladiators-bonecracker
http://www.wowhead.com/item=61335/vicious-gladiators-pummeler

**Comment by RelmAtlantiss** [comment]
fixed
https://github.com/Atlantiss/BugTracker/issues/5643

**Comment by Mos1ek** [comment]
not in alliance
