### ISSUE TITLE
[EN][NPC][Molten Front]Zen'Vorka

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5450]
Zenvorka's vendor items shouldn't become available until completing Through the Gates of Hell. 

http://www.wowhead.com/npc=52822/zenvorka
http://www.wowhead.com/quest=29201

**Comment by Thefakemccoy** [comment]
This npc also does not sell the alliance rep commendations
http://www.wowhead.com/item=70152/stormwind-writ-of-commendation
http://www.wowhead.com/item=70146/exodar-writ-of-commendation
http://www.wowhead.com/item=70148/ironforge-writ-of-commendation
http://www.wowhead.com/item=70145/darnassus-writ-of-commendation
http://www.wowhead.com/item=70147/gnomeregan-writ-of-commendation
http://www.wowhead.com/item=71087/gilneas-writ-of-commendation

**Comment by Bildo** [comment]
fixed
