### ISSUE TITLE
[EN] [Raid][Firelands]Scorpion packs

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5451]
The scorpion packs should be tied together and all pull if one is pulled.
http://www.wowhead.com/npc=53128/giant-fire-scorpion#comments
http://www.wowhead.com/npc=53127/fire-scorpion#comments

**Comment by melsage** [comment]
Whats more, debuff "Fiery Blood" which is given by little scorpions should be stackin on the players ( atm we get only one debuff http://www.wowhead.com/spell=99993/fiery-blood

**Comment by Thefakemccoy** [comment]
Also these are suppose to skinnable but are not a despawn to fast.
