### ISSUE TITLE
[EN][Quest][Cata][Stormwind]Your time has come 

### ISSUE THREAD

**Issue by Rageless** [Atlantiss/BugTracker#5454]
http://www.wowhead.com/quest=29453/your-time-has-come

Coridomi the NPC where u  have to turn it in has the  yellow questionmark above its head but when i click it  there are no options in the  window that pops up

**Comment by Aival94** [comment]
for me quest was completed on me which should not happen

**Comment by mesirka** [comment]
+

**Comment by Aival94** [comment]
I think problem is generally with npc and not with the quest itself as even if you have completed the quest [Your Time Has Come](http://www.wowhead.com/quest=29453/your-time-has-come) you cannot get quest [A Legendary Engagement](http://www.wowhead.com/quest=29132/a-legendary-engagement) from [Coridormi](http://www.wowhead.com/npc=52408/coridormi) which have the yellow ! mark upon her.

**Comment by Quban** [comment]
this was fixed if i remember, is this bug still in game?

**Comment by Aival94** [comment]
The only bug i see now is that upon [Coridormi](http://www.wowhead.com/npc=52408/coridormi) is spawned [Hallegosa](http://www.wowhead.com/npc=53466/hallegosa).

About quest [Your Time Has Come](http://www.wowhead.com/quest=29453/your-time-has-come) be able to complete it on yourself when should only complete it to NPC [Coridormi](http://www.wowhead.com/npc=52408/coridormi) i do not know if still happen as i completed this one.

**Comment by Deonorth** [comment]
i can't find npc.
