### ISSUE TITLE
[EN]T11 parts

### ISSUE THREAD

**Issue by probboy3** [Atlantiss/BugTracker#5456]
There's no npc that sells t11 parts. There are just old valor trinkets boots etc. No set parts.

**Comment by HUMBOL** [comment]
Confirm

**Comment by Therenir** [comment]
This is info from wowwiki
Slot	         Justice Points
Chest	2200
Hands	1650
Legs 	2200
Head	2200
Off-Hand	950
Necklace	1250
Shoulder	1650
Waist	1650

http://wowwiki.wikia.com/wiki/Justice_point

**Comment by Aviannaqt** [comment]
links

**Comment by Iskra12** [comment]
Slot Justice Points
 Chest 2200
 Hands 1650
 Legs 2200
 Head 2200
 Off-Hand 950
 Necklace 1250
 Shoulder 1650
 Waist 1650


This refers only to 346ilvl gear. 
You can only buy 3 pieces of Tier 11 using justice points: hands (1650jp), legs(2200jp), chest(2200jp), shoulders and head still needs token to purchase.

http://wow.gamepedia.com/Rugok
