### ISSUE TITLE
[EN] [Raid] [Firelands] Trash

### ISSUE THREAD

**Issue by troublemakerr** [Atlantiss/BugTracker#5457]
Mobs are not giving golds or anything else which they should drop, epics and patterns are dropping and it seems drop rate is fine. One mob (I dont know the name) keeps following you even when he dies (Hes untargetable) and hes doing damage to u. Scorpions can be pulled one by one which is wrong, they should all pull together when u pull one. People can't DE items from vendor. If you wipe on Ryolith, you will get that bar for his legs and its removable only if u wipe again.

**Comment by Thefakemccoy** [comment]
Items from vendor based off rep the epic ones any way should net be DE able

**Comment by Bildo** [comment]
Items should be disenchantable.

**Comment by Aival94** [comment]
These items can be Disenchanting and is a good way to decrease price of maelstorms to 200-300g each :).

Proof: [Disenchanting](http://www.wowhead.com/item=71229/flowing-flamewrath-cape#disenchanting)
[Second comment](http://www.wowhead.com/item=71229/flowing-flamewrath-cape#comments)

**Comment by Illusionist87** [comment]
There is 1 dead mob that can't be targeted, but he follows the raid and attacks.
That keeps entire raid in combat and does  lot of damage too. Don't know his name since I can't target him, but he is 1 of those "naga like" creatures, and is in the middle of 1 of the dog packs.

**Comment by anxanas** [comment]
Bump

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/6031
