### ISSUE TITLE
[EN] [Raid] [Baradin Hold] Occuthar

### ISSUE THREAD

**Issue by troublemakerr** [Atlantiss/BugTracker#5458]
Eyes are not doing damage at all when shooting you with that geen thing.

**Comment by Iskra12** [comment]
One more thing, for killing Occuthar we get 70vp according to patch notes shuld be like this:
-The number of Valor Points awarded for killing a boss in the Firelands is 120 in 10-player mode, and 140 in 25-player mode.
-The number of Valor Points awarded for killing Occu'thar in Baradin Hold is 120 in 10-player mode, and 140 in 25-player mode.
-The number of Valor Points awarded for killing a boss on Heroic difficulty in The Bastion of Twilight, Blackwing Descent, and Throne of the Four winds is 35 in 10-player mode, and 45 in 25-player mode.

http://us.battle.net/wow/en/blog/2993743/rage-of-the-firelands-patch-42-notes-%5Bupdated-628%5D-6-28-2011

**Comment by Thefakemccoy** [comment]
@Iskra12  I think Argaloth should give JP now instead of nothing. Same with all T11 normal raids.

**Comment by Quban** [comment]
valors fixed

**Comment by Iskra12** [comment]
Only info i can find right now about JP and VP
http://www.atlasmod.com/phpBB3/viewtopic.php?f=4&t=2036&p=13850&hilit=yeah&sid=3da61323e7f793a1dd94f0caaf20e211#p13850


"Yeah its probably the best way, just means the AL guys are gonna have to had a extra line to all the stuff that gives Justice/Valor points.
Below is a list of the TOTAL amount of Justice/Valor Points you can recieve from a Dungeon/Raid (NOT including the Random Bonus/Guild Reward), the WoTLK and BC Dungeons and Raids also give Justice Points but ONLY if your not over the level cap for that expansion (BC 60-70 WotLK 70-80) should we include them?

Justice Points
Blackrock Caverns Heroic
350 JP
Deadmines Heroic
420 JP
Grim Batol - Normal/Heroic
120/280 JP
Halls of Origination Normal/Heroic
210/490 JP
Lost City of Tol'vir Normal/Heroic
120/280 JP
Shadowfang Keep Heroic
350 JP
The Stonecore Heroic
280 JP
The Vortex Pinnacle Heroic
210 JP
Throne of the Tides Heroic
280 JP
Zul'Aman Heroic
420 JP
Zul'Gurub Heroic
420 JP
Valor Points
Baradin Hold 10/25M
Occu'thar
120/140VP
Argaloth
70JP

Blackwing Decent 10/25M
210/270VP

Firelands 10/25M
840/980VP

The Bastion of Twilight 10/25M
165/225 VP
Throne of the Four Winds 10/25M
70/90 VP"
