### ISSUE TITLE
[EN][Raid][Firelands]Shannox

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5459]
When Shannox is released from the gate keepers room. The dogs get stuck in the wall when he makes his turn just outside the room. 
http://www.wowhead.com/npc=53691/shannox

**Comment by Thefakemccoy** [comment]
Rageface and Riplimb still in staging area.
![wowscrnshot_122715_164434](https://cloud.githubusercontent.com/assets/12252441/12012756/915bf774-acd1-11e5-8e52-9723376625a8.jpg)

Shannox Patrolling
![wowscrnshot_122715_164437](https://cloud.githubusercontent.com/assets/12252441/12012758/9726a3d4-acd1-11e5-9983-ea6a3fe393d9.jpg)

**Comment by Aival94** [comment]
seems after a restart it start work correctly.

**Comment by Quban** [comment]
fixed
