### ISSUE TITLE
[EN][Vendor] Alliance honor quartermaster selling season 9 elite.

### ISSUE THREAD

**Issue by fizzle7** [Atlantiss/BugTracker#5460]
Alliance honor quartermaster is selling season 9 elite with a tooltip "Season 10" when it should be season 9 normal, not elite, with "Season 9" tooltip.
Proof:
1. http://us.battle.net/wow/en/forum/topic/4175420172
If that's not enough, search google, but it's pretty logical it shouldn't be available.

**Comment by Bildo** [comment]
https://cynwise.wordpress.com/2011/06/24/battleground-pvp-gear-in-cataclysm-patch-4-2-arena-season-10/
