### ISSUE TITLE
[EN][Quest][Eversong Woods][minor] The Fallen Courier

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5462]
http://www.wowhead.com/quest=9147/the-fallen-courier
According to wowhead and wowiki (http://wowwiki.wikia.com/wiki/Quest%3AThe_Fallen_Courier), this quest has a prerequisite , the quest http://wowwiki.wikia.com/wiki/Quest:Missing_in_the_Ghostlands.
How it is bugged: The quest is available without the prerequisite.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12507-5462questeversong-woodsminor-the-fallen-courier/
