### ISSUE TITLE
[EN][Raid][Firelands]Shannox

### ISSUE THREAD

**Issue by mesirka** [Atlantiss/BugTracker#5464]
Dear administration of the server Atlantiss, 
first of all I want to thank you for the work that you have done. It is a great pleasure for me to play on this server. As to online, content and work ability this server is the best I’ve ever seen. Believe me I have something to compare with. 
I, like many other players, was waiting for the promised updates and the introduction of the Firelands raid content. I wish I could enjoy digging through Firelands, my favourite raid, again. But I couldn’t.
Regretfully, I  have to inform you about a bug with the boss Shannox. 
Unfortunately, the boss is absolutely non-working. He almost does no damage, and stupidly stands still. Even his traps are triggered from time to time. And there was no Riplimb with Rageface, I liked them very much. And the saddest thing is that Shannox turned out to be a dummy with the loot. Would you kindly correct Fireland. 
Sincerely, one of the usual players.

**Comment by Sayris9876** [comment]
Confirming. Shannox is doing nothing only Crystal Prison Trap from time to time but that's about it. No Riplimb no Rageface. He was basicly target dummy with few traps thrown at us...

**Comment by Jenovas** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/5459. The dogs sometimes bug and stop walking and that's why "nothing works".
