### ISSUE TITLE
[EN][Raid][Firelands]][Alysrazor]

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#5466]
![wowscrnshot_122815_014806](https://cloud.githubusercontent.com/assets/16444508/12013714/3823485c-ad25-11e5-98ea-32e84e3aa936.jpg)

That happened after server restart while we were at Alysrazor. Majorodomo was gone and the feather that starts the encounter was missing too.

**Comment by metaldoctor** [comment]
Boss bugged if u in fight have disconect or server restart. After it u dont have feather to start event.

**Comment by Quban** [comment]
fixed in rev 4754
