### ISSUE TITLE
[PL][QUEST]Guardians of Hyjal: Call of the Ancients

### ISSUE THREAD

**Issue by baniasso** [Atlantiss/BugTracker#5467]
Problem polega na tym, że wykonane zostały przeze mnie wszystkie Q dostępne w Hyjal (dostałem achivement), a Lo'gosh assisted nie zostało zaliczone. Ba, sprawdziłem nawet, że faza z Lo'goshem nie nastąpiła. Q z nim związanego robiłem prawie rok temu.

**Comment by Wolffenstein** [comment]
Fixed in rev 4748.
