### ISSUE TITLE
[Item][Molten Front] Embergris

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5470]
http://www.wowhead.com/item=69722 do questa http://www.wowhead.com/quest=29255 dropią bez posiadania questa

**Comment by Aival94** [comment]
When you are in quest in tooltip it show 2 credit counters.

![wowscrnshot_011716_211124](https://cloud.githubusercontent.com/assets/10282971/12460996/4b3175e8-bfbf-11e5-8c32-c64bdb9edafe.jpg)

**Comment by Piklo** [comment]
posted fix on forum
http://community.atlantiss.eu/index.php?/topic/11078-npc-charred-soldier-charred-vanquisher/
