### ISSUE TITLE
[EN][Raid][Firelands] Valor Points.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#5473]
Hello.
We have wrong valor points in Fireland and in Baradin Hold when killing Occu'thar. We have 70 valor points per boss, but we must have 120 in 10man raids and 140 in 25 man raids.

 - The number of Valor Points awarded for killing a boss in the Firelands is 120 in 10-player mode, and 140 in 25-player mode.
 - The number of Valor Points awarded for killing Occu'thar in Baradin Hold is 120 in 10-player mode, and 140 in 25-player mode. 

I dont checking T11 content for Valor points and cant say how much we have now.
Full patch note is here http://wowwiki.wikia.com/wiki/Patch_4.2.0

**Comment by Bildo** [comment]
fixed

**Comment by Kejmil** [comment]
takie fixed ze na 25 nie ma lootu xD

**Comment by debtheone** [comment]
halo zrobcie reset id bo 1 w dupe

**Comment by Bildo** [comment]
czego nie ma?

**Comment by debtheone** [comment]
lootu

**Comment by Bildo** [comment]
niby z ktorego? zabilem shannoxa i leci loot

**Comment by Bildo** [comment]
niby z ktorego? zabilem shannoxa i leci loot

**Comment by Bildo** [comment]
Z pozostałych też leci.

**Comment by debtheone** [comment]
Occu'thar' 25

**Comment by Kejmil** [comment]
i 10 pewnie tez

**Comment by Bildo** [comment]
Nastpnym zrobcie nowy temat z informacjami abym nie musial od was wyciagac...

**Comment by debtheone** [comment]
jakiś reset id planujecie albo cos ?
