### ISSUE TITLE
[EN][Vendor] Alliance honor quartermaster selling season 9 gear.

### ISSUE THREAD

**Issue by fizzle7** [Atlantiss/BugTracker#5480]
So after the issue about selling season 9 "elite" gear as season 10 was resolved, now this comes up. Vendors are selling both season 9 normal and season 10 low-tier gear when they should only be selling season 10 low-tier vicious gear for honor points.

http://us.battle.net/wow/en/forum/topic/2743690992?page=3#57

**Comment by Aydien** [comment]
Also 1handed weapons of season 9 are missing.

**Comment by BialyADI** [comment]
And where is PvP Medalion !? ^^

**Comment by fizzle7** [comment]
Close this, works as intended, season 9 weapons and low tier season 10 gear, that's fine.
