### ISSUE TITLE
[EN][Quests][Mount Hyjal][Firelands Invasion]The Sanctuary of Malorne Dailies order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5486]
This happened the first day so it might be already fixed with some hotfixes but quests:
[Between the Trees](http://www.wowhead.com/quest=29125/between-the-trees)
[Call the Flock](http://www.wowhead.com/quest=29147/call-the-flock)
[Perfecting Your Howl](http://www.wowhead.com/quest=29164/perfecting-your-howl)
[Punting Season](http://www.wowhead.com/quest=29101/punting-season)
[Those Bears Up There](http://www.wowhead.com/quest=29161/those-bears-up-there)
Should be available(one of them) after complete quest [The Sanctuary Must Not Fall](http://www.wowhead.com/quest=29198/the-sanctuary-must-not-fall)

Wowhead Link: [Molten Front](http://www.wowhead.com/guide=58/a-guide-to-the-molten-front-and-respective-quests)

**Comment by Wolffenstein** [comment]
It's fixed already.
