### ISSUE TITLE
[En][Item]Mail Shoulders "Flickering Shoulders" from Bethilac dont have Random Enchant.

### ISSUE THREAD

**Issue by awakestar** [Atlantiss/BugTracker#5489]
When you loot the Shoulders from Beth they dont give Random Enchants.

**Comment by xolon** [comment]
neither do other items that should have random enchants like helmet from rhy

**Comment by Evelinrose** [comment]
I asume same goes for leathers shannox,wrist alysrazor and wrist from baleroc do have enchants but they are wrong.Like int/stam mastery hasted instead str/stam (mastery parry or dodge etc.)

**Comment by Frainzil** [comment]
http://www.wowhead.com/item=71011/flickering-cowl is the helmet. 
http://www.wowhead.com/item=70917/flickering-handguards is the bugged bracers (stamina socket bonus but stats were for healers (intellect)

**Comment by Aival94** [comment]
Can confirm about [Flickering Shoulders](http://www.wowhead.com/item=71030/flickering-shoulders) about not having random stats as it should.

![wowscrnshot_123015_030026](https://cloud.githubusercontent.com/assets/10282971/12050708/cb0411c8-af01-11e5-9571-ce1000493d2a.jpg)

**Comment by Newasenior** [comment]
got then too today and still they miss stats and enchantment :((

**Comment by Ranor** [comment]
Fixed in rev 4825
