### ISSUE TITLE
[EN][Item/Spell]Fandral's Flamescythe

### ISSUE THREAD

**Issue by Protanna** [Atlantiss/BugTracker#5490]
i recieved Fandral's Flamescythe from Majordomo and while you recieve the Druid of the Flames buff you do not recieve the visual effect it should grant which is the Fire Cat Form

http://www.wowhead.com/item=69897/fandrals-flamescythe
http://www.wowhead.com/spell=99244/druid-of-the-flames

**Comment by eryczek1615** [comment]
!

**Comment by eryczek1615** [comment]
Fix this,please! :D

**Comment by mitim1** [comment]
bump!

**Comment by Bastion** [comment]
feral hunter

**Comment by Jenovas** [comment]
Fixed in rev 4790.
