### ISSUE TITLE
[PL][ITEM] Token drop from Majordomo/Ragnaros

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#5494]
http://www.wowhead.com/npc=52571/majordomo-staghelm
http://www.wowhead.com/npc=52409/ragnaros

Ani Ragnaros ani Majordomo nie dropią tokenów t12.

**Comment by Bastion** [comment]
no troche lipa

**Comment by Frainzil** [comment]
Nor did it drop for us (25man mode).

**Comment by Quban** [comment]
fixed in rev. 4754
