### ISSUE TITLE
[EN] Majordomo Staghelm Trash (Firelands)

### ISSUE THREAD

**Issue by shandrios** [Atlantiss/BugTracker#5495]
The Druids of the Flame before Staghelm never stop casting Sunfire after they are pulled. This means the raid takes around 30k damage per second, which is almost impossible to heal. This means unless a GM kills the trash, Staghelm and Ragnaros are inaccessible.

**Comment by Frainzil** [comment]
It is killable. We were in 25m raid and we went 11 healers, MC'd the night elf mobs and killed 1 by one. Did cost us quiet some time to get it to work. Though indeed the trash is bugged as hell.

**Comment by Quban** [comment]
they are not spaming it now, pls test if its ok ;p

**Comment by anxanas** [comment]
Easily killable now
