### ISSUE TITLE
[EN][item][Loot][Firelands] Living Ember

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#5496]
the follow item: http://www.wowhead.com/item=69237/living-ember dropped once (2 of them) in our 25man raid, killing 6 bosses. Dragon annihilation also killed 6 bosses getting 3 living embers themself. Buggy dropchance?

**Comment by xolon** [comment]
#GimmeEmbers

**Comment by Bastion** [comment]
wtb 4 living ember

**Comment by Quban** [comment]
> Buggy dropchance?

nope
