### ISSUE TITLE
[PL][Achievement] Firelands

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#5497]
http://www.wowhead.com/achievement=5802/firelands
http://www.wowhead.com/achievement=5983/firelands-guild-run
nie zalicza lorda i ragnarosa
http://www.wowhead.com/npc=53772/lord-rhyolith
http://www.wowhead.com/achievement=5976/ragnaros-kills-firelands

**Comment by Elhalli** [comment]
Ragnarosa też nie zalicza

**Comment by Bastion** [comment]
ktoś coś?

**Comment by Bastion** [comment]
i jak tam Bildo, będzie na nowe id?

**Comment by eryczek1615** [comment]
bump

**Comment by Bastion** [comment]
firelandy 5/7 ( ͡° ͜ʖ ͡°)

**Comment by Aviannaqt** [comment]
Bo trudne te firelandy

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev4835

**Comment by Bastion** [comment]
gildyjny jeszcze :D

**Comment by Quban** [comment]
to juz inny bug
