### ISSUE TITLE
[EN][NPC][The Furnace/MotlenFront]Kirix

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5498]
Kirix does not patrol around the ledge instead he walks through the mountain and goes through the air.
http://www.wowhead.com/npc=54323/kirix

**Comment by eryczek1615** [comment]
http://i.imgur.com/wZ1HkG2.jpg

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/6750
https://github.com/Atlantiss/BugTracker/issues/5777
