### ISSUE TITLE
[PL][Raid][Firelands]][Alysrazor - dostep do lootu]

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#5499]
Boss padł kiedy był w powietrzu, i tam tez pozostał. Bez posiadania buffa do lotu ( ktory sie konczyl) nei bylo by mozliwosci zlootowania bossa [ eternal ember rowniez poszyly sie bujac bo osoba ktora zbeira nie miala mozliwosci podlecenia do bossa].

**Comment by Quban** [comment]
fixed in rev. 4754
