### ISSUE TITLE
[EN][NPC] PvP Medallion

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5501]
NPC:
![wowscrnshot_122915_081557](https://cloud.githubusercontent.com/assets/5780624/12030797/6c6319be-ae04-11e5-812a-8c5130d4b9fa.jpg)
Dont have:
http://cata.openwow.com/item=70606
http://cata.openwow.com/item=70604
http://cata.openwow.com/item=70603

And she shoud heave like in Ogrimmar :).

**Comment by phifedawg** [comment]
The same applies to the conquest vendor. There are no pvp medaillons from him either.

**Comment by Bildo** [comment]
Why it's so hard to make a good report.

**Comment by BialyADI** [comment]
What is wrong with that report, I do my best ;D,

**Comment by Bildo** [comment]
You forgot npc link

**Comment by phifedawg** [comment]
Let me get that for ya:

http://cata.openwow.com/npc=51256#sells

Here you go. The loot displayed is Bloodthirsty though.

**Comment by Bildo** [comment]
fixed

**Comment by phifedawg** [comment]
thanks :)
