### ISSUE TITLE
[EN][item][Loot][Firelands] Class tokens

### ISSUE THREAD

**Issue by lqlq32** [Atlantiss/BugTracker#5504]
Bosses don't drop tokens, while we were 25m raid.

How it should work:
On 10m you should have 2 items + 1 random token + chance for living ember + the item for the legendary quest + chance for shared boss loot.
On 25m you should have 4 items + 3 tokens + chance for living ember + the item for the legendary quest + chance for shared boss loot.
On heroic you have a chance for Crystallized Firestone too.

**Comment by Quban** [comment]
fixed in rev 4754 wait for compilation and restart
