### ISSUE TITLE
[PL][Item] Cena T11

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#5507]
Chest Tank - http://www.wowhead.com/item=60354
Chest Heal - http://www.wowhead.com/item=60360
Chest Dps - http://www.wowhead.com/item=60344
Legi Tank - http://www.wowhead.com/item=60357
Legi Heal - http://www.wowhead.com/item=60361
Legi Dps - http://www.wowhead.com/item=60347

Nie wiem jak inne klasy ale Paladyn ma do wyboru klate i legi w dwóch cenach: 1650JP oraz 2200JP. Ilość wymaganych punktów powinna zdaje się zostać taka sama(2200), jedynie ich rodzaj się zmienia.

Mogę podać linki do tych itemów jeśli chcecie.

Edit: Dodane linki.

**Comment by Bildo** [comment]
tak, chcemy

**Comment by Glare** [comment]
Linki dodane.
