### ISSUE TITLE
[EN][Quest][Mount Hyjal] Rage Against the Flames

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#5508]
The NPC [Charred Flamewaker](http://www.wowhead.com/npc=52791/charred-flamewaker) doesn't give credit for the quest [Rage Against the Flames](http://www.wowhead.com/quest=29163/rage-against-the-flames).

http://www.wowhead.com/npc=52791/charred-flamewaker#objective-of

**Comment by user1011** [comment]
Still presists.

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14362-npc-charred-flamewaker/
