### ISSUE TITLE
[EN][NPC][Vendor] PvP Trinket not sold, pretty major

### ISSUE THREAD

**Issue by MorbidMike** [Atlantiss/BugTracker#5510]
Knight-Lieutenant T'Maire Sydes is not selling the real PvP trinkets: Vicious Gladiator's Medallion of Tenacity/Cruelty/Meditation. They're the first items any PvP character should buy so it is very important that they are available.

**Comment by BialyADI** [comment]
https://github.com/Atlantiss/BugTracker/issues/5501
