### ISSUE TITLE
[EN][NPC][Molten Front] Lava Burster 

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5511]
not sure which id it is but

http://www.wowhead.com/npc=53090/lava-burster
http://www.wowhead.com/npc=52771/lava-burster
http://www.wowhead.com/npc=52633/lava-burster

their Lava showers are hella OP and near impossible to avoid (not saying it's actually impossible but jesus)
They will oneshot anyone nearby that isn't paying even a tiny bit of attention 

it also follows the players around and it should use it in a frontal arc
http://www.wowhead.com/spell=97549/lava-shower

edit, max range on the spell is also broken as some people report it being attacked over 40 yards away

please fix this asap

**Comment by BialyADI** [comment]
Ahh is ok look on Molten Front Video on YT.

**Comment by Luna-maria** [comment]
"Their Lava Shower is quite lethal, but pay attention and you can stay out of it easily. They spray it around themselves at a fixed distance (to strike whoever they're attacking) for 180 degrees. So in melee you can run behind them and escape it (they turn at about the rate it takes to run around them), and at range, you'll likely have to move a bit closer or further away to escape the shower.

Last edited by hymer on 2011/07/12 (Patch 4.2.0)"

It's not ok

180 degree cone us not following players 360 degrees around

**Comment by Thefakemccoy** [comment]
One thing I noticed with planting the seed. Every one that was up at one time for some reason when the vine grew out every lava burster that was there targeted that one vine and did a lava shower on it. Try avoiding like 10 lava showers coming from half way across that room.

This might have been just a issue i had i did not get any kind a proof.

**Comment by BialyADI** [comment]
Just don't make it too Easy, i want some challenge.

**Comment by Aival94** [comment]
If it is a bug is not about a challenge but about blizzlike rule.

**Comment by BialyADI** [comment]
But what is bugged?
That you cant dodge it?

**Comment by Thefakemccoy** [comment]
What is bugged is that he does a 360 with the ability and should only do a 180.

**Comment by Luna-maria** [comment]
Devs will know what to fix, lets not turn this into an endless discussion thread. It's bugged, and needs fixing

**Comment by Gozzreal** [comment]
ITs pretty bad, I got nuked by it when I was out of the way. I literally ran back up to furion and I still got rekked.

**Comment by vanael** [comment]
https://youtu.be/Vtp0elns6Ts

**Comment by Aival94** [comment]
Some lava bursters without a body/animation are spawned in wrong phase(when their quest is not available as daily)

![wowscrnshot_010816_155444](https://cloud.githubusercontent.com/assets/10282971/12225305/c3b84c8c-b810-11e5-9af0-a7438fff1cc9.jpg)

**Comment by TranceAccount** [comment]
They don't have loot, except 53090 with a q item.

**Comment by TranceAccount** [comment]
This should be fixed. Not completely blizzlike tho.
