### ISSUE TITLE
[EN][Raid] Firelands Respawns

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#5515]
In firelands everything resets after some time 5-6h, gates (gate infront or baleroc), events (bridge which requires all prev boss kills), trash. Nothing should reset inside the instance until server id restart

**Comment by Thefakemccoy** [comment]
If I remember correct Main room trash will respawn until shannox is dead. So if you go in there clear trash and not shannox all that trash will respawn over time.

Trash in front of Baleroc should only respawn if he is not killed with in so many hours. Once killed that trash in his room should never respawn.

Trash to Beth'tilac should only respawn if he is not killed with in so many hours. Once killed that trash up the walk way should never respawn.

Trash to Lord Rhyolith  should only respawn if he is not killed with in so many hours. Once killed trash will not respawn up the walk way.

**Comment by xolon** [comment]
we cleared 5/6 firelands yesterday and today everything reseted except bosses, Alysrazor event, Bridge, Flame wall infront of Baleroc. (Gm helped us tho)

**Comment by Quban** [comment]
its not perfect like retail but i think its ok for now :D
