### ISSUE TITLE
[EN][Loot][Ragnaros]

### ISSUE THREAD

**Issue by LaveGit** [Atlantiss/BugTracker#5516]
Ragnaros 25 man does not spawn chest with loot....

![skaermbillede 2015-12-29 kl 21 36 06](https://cloud.githubusercontent.com/assets/12621497/12041735/5f759fb8-ae74-11e5-86fe-3f4d0ad44009.png)

**Comment by TopKeK28** [comment]
bamp

**Comment by anxanas** [comment]
BUMP!! Stupid poles got their loot, we want loot too =)))

**Comment by egostar** [comment]
bump

**Comment by LaveGit** [comment]
And when we had GM to help us the loot was 10 man mode.

![skaermbillede 2015-12-29 kl 21 36 06](https://cloud.githubusercontent.com/assets/12621497/12041785/066e6c1e-ae75-11e5-8a83-742bcea90367.png)

**Comment by hakunatotama** [comment]
Quality server with quality GMs

**Comment by troublemakerr** [comment]
Bump

**Comment by anxanas** [comment]
We didnt even get achivement =((

**Comment by auviance** [comment]
https://www.youtube.com/watch?v=GcKFsW_TCfw&feature=youtu.be

**Comment by hakunatotama** [comment]
Instead of deleting my comment how about fix the goddamn loot for us quality gms?

**Comment by LaveGit** [comment]
No provoking, Hakuna :/

**Comment by anxanas** [comment]
Yes no reason to be a douchebag unless they are polish =))

**Comment by hakunatotama** [comment]
I'm not provoking, it's just to delete my comment a competent GM was found in less than 10seconds, to fix our loot a competent GM is yet to be found. Priorities of some people that are in charge of this server are off the roof.

**Comment by hakunatotama** [comment]
And yes, I am salty  about this. I do care about loot from raids, especially when I want our guild to be geared before HC. But yea, GMs gotta keep it atlantiss

**Comment by debtheone** [comment]
pve drama

**Comment by Jenovas** [comment]
Removed all comments that had nothing to do with the bug. 
Cheers.

**Comment by hakunatotama** [comment]
remove all the content that has nothing to do with scripted correctly
cheers

**Comment by Quban** [comment]
i fixed it already, we are having problems with changelog so you cant see that :D

**Comment by LaveGit** [comment]
Any idea when the fix will be applied, or what rev. the fix is in, so we can see it in-game? :)

**Comment by Quban** [comment]
> what rev. the fix is in

4757

**Comment by LaveGit** [comment]
Thanks

**Comment by anxanas** [comment]
Ty for fix
