### ISSUE TITLE
[EN][Quest][A Wrinkle in Time]

### ISSUE THREAD

**Issue by tohlakas** [Atlantiss/BugTracker#5517]
Okey it's very abusive. 

After seeing the cinematic I joined the BG went. what happened next i was invisible. I could kill allys, but they could not kill me. Also fellow horde players didnt see me. At 1st i found it bit odd that ally players were confused didnt target me etc. But then I jumped into group of them and nobody noticed me.

/// Test run 2. I just came into bad idea and went into Stormwind. No player or guard could attack or see me. meanwhile I was able to do whatever i wanted. Left soon after test.

**Comment by Thefakemccoy** [comment]
Relog should fix worked for me last night.

**Comment by tohlakas** [comment]
Yeah it did. I made this report just in case somebody else may abuse it in future + Since i went to BG and caused some confusion among allys to avoid ban.

**Comment by Quban** [comment]
fixed in rev 4757
