### ISSUE TITLE
[EN][Raid][Firelands]Ragnaros hitbox as hunter

### ISSUE THREAD

**Issue by lqlq32** [Atlantiss/BugTracker#5518]
Hunters cant attack the boss even if they aren't that close to the boss.
https://www.youtube.com/watch?v=EowPM2U7bB8
Here you can see the guy is attacking as hunter even from melee range.

**Comment by anxanas** [comment]
Hitbox is supposed to work like it works on ala'kir, also spells like felstorm immolation aura shadowflame, wild mushroom, doesnt hit rag especially for demo locks this is a huge problem,

**Comment by Jenovas** [comment]
Fixed in rev 4765
