### ISSUE TITLE
[EN][Raid][Firelands] Bethilac - Frenzy

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#5519]
<b>How it should work</b>
Bethilac should gain one stack of <a href='http://www.wowhead.com/spell=99497/frenzy#used-by-npc'>Frenzy</a> every 5 seconds
Proof 
retail logs <a href='http://www.worldoflogs.com/reports/rt-6i84oys40niuter6/xe/?s=5579&e=5997&x=spell%3D%22Frenzy%22'>Link</a>
<b>How it works now</b>
<a href='http://www.worldoflogs.com/reports/coz8yt5ebhgx7fg0/xe/?s=1634&e=2052&x=spell%3D%22Frenzy%22'>Link</a>

**Comment by anxanas** [comment]
4.3 nerfs to firelands?

**Comment by planche** [comment]
These logs are from 2011 patch 4.2 <a href='http://i.imgur.com/NygTxYO.jpg'>imgur</a>
<a href='http://wowwiki.wikia.com/wiki/Patches'>patches</a> It doesn't even matter to be honest. Every guide states that it should stack every 5 sec

**Comment by Quban** [comment]
fixed in rev. 4762
