### ISSUE TITLE
[PL] [items] t12 cant buy with tokens

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#5520]
Cześć t12 za tokeny nie mogę kupić u vendora. Sprawdzałem druida i tam bez problemu.
![wowscrnshot_122915_231402](https://cloud.githubusercontent.com/assets/8699987/12043108/d7af4ed6-ae81-11e5-8bb6-644f3b7b37a1.jpg)
http://www.wowhead.com/npc=46555/gunra

**Comment by Bastion** [comment]
nie kupisz

**Comment by lqlq32** [comment]
It isnt bugged for all classes, but it is for hunters.

**Comment by arekczup** [comment]
yes

**Comment by Aviannaqt** [comment]
fixed

**Comment by arekczup** [comment]
hero tokens może naprawicie...

**Comment by Bildo** [comment]
a masz hero dostepne?

**Comment by arekczup** [comment]
jeszcze nie

**Comment by arekczup** [comment]
jak włączyłem i paczałem to mi tylko wyświetliły za normale

**Comment by Bildo** [comment]
chodzi mi, ze hero firelandow nie jest dostepne jeszcze, jak wyjdzie heroic fl to beda dostepne tokeny

**Comment by arekczup** [comment]
wiem tylko kupno w wendorze
