### ISSUE TITLE
[PL][Spell][Warlock/Hunter] Avoidance

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#5521]
Wrath of Ragnaros(aoe dmg + knockback) - http://www.wowhead.com/spell=98263
Sulfuras Smash(miejsce uderzenia młotem) - http://www.wowhead.com/spell=98710
Lava Wave(ściany lawy wychodzące z powyższego spella) - http://www.wowhead.com/spell=98928
Magma Trap(sam dmg po detonacji) - http://www.wowhead.com/spell=98175
Molten Seed(dmg po wylądowaniu) - http://www.wowhead.com/spell=98495
Molten Inferno(dmg po przebudzeniu) - http://www.wowhead.com/spell=98518
Splitting Blow(dmg w miejscu wylądowaniu młota) - http://www.wowhead.com/spell=98951
Supernova(dmg jak Son of Flame dojdzie do Sulfurasa) - http://www.wowhead.com/spell=99112
Engulfing Flames(aoe dmg na platformie) - www.wowhead.com/spell=99171
Blazing Heat(dmg od ognistych kloców zostawianych na ziemi) - http://www.wowhead.com/spell=99145
Meteor Impact(wybuch meteorytu) - http://www.wowhead.com/spell=99287

Avoidance demonów ignoruje chyba wszystkie spelle Ragnarosa. Jeśli trzeba to dodam linki.

Na innych bossach nie zauważyłem tego problemu ale jeśli coś przeoczyłem to proszę dopisać.

Edit: Dodane linki.

**Comment by Jenovas** [comment]
Proszę napisać na jakie spelle nie działa a powinno.

**Comment by lqlq32** [comment]
I dont know polish but same thing is bugged for hunters too, they took too much dmg from aoe spells that kill them and for rest of the fight ur pet is gone.

**Comment by Glare** [comment]
Linki dodane.

**Comment by Jenovas** [comment]
Wrath of Ragnaros(aoe dmg + knockback) - http://www.wowhead.com/spell=98263
Sulfuras Smash(miejsce uderzenia młotem) - http://www.wowhead.com/spell=98710
Lava Wave(ściany lawy wychodzące z powyższego spella) - http://www.wowhead.com/spell=98928
Magma Trap(sam dmg po detonacji) - http://www.wowhead.com/spell=98175

Wszystkie te spelle działają poprawnie z avoidance, jedyny bug to aura po Lava Wave która potem zadaje 20k DMG co sekunde. Lava Wave poprawiony. Więcej spelli nie będę sprawdzał. Zamykam.
