### ISSUE TITLE
[Firelands]Ragnaros - pet damage taken and melee spell

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#5522]
Waves from Ragnaros SMash killing each time every pet and guardian.
Melee range spell like: Felstorm, Immolation Aura. Shadowflame itc doesnt work on Ragnaros, similar to Sinestra and Alakir...

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/594

**Comment by Jenovas** [comment]
Please create 1 issue for every bug. And the pets getting killed by everything issue alreadt exists.
Closing.
