### ISSUE TITLE
[EN][Achievement][Molten Front][Gang War]

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#5529]
On this achievement you need to have the quest  [The Protectors of Hyjal] and win a duel at Sethria's Roots. Both me and my friend had the quest we went to that location dueled each other but no achievement.

**Comment by LaveGit** [comment]
Confirmed.

**Comment by Aival94** [comment]
Just the link of the ach: [Gang War](http://www.wowhead.com/achievement=5864/gang-war)

**Comment by Samineh** [comment]
:+1:

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11166-achievement-gang-war/

**Comment by BAndysc** [comment]
[5142]
