### ISSUE TITLE
 [PL][Spell] Shaman Grounding not working on Freezing Trap

### ISSUE THREAD

**Issue by full789** [Atlantiss/BugTracker#5534]
Grounding Totem powinnien zjadać Freezing Trap'a.

http://www.wowhead.com/spell=8177/grounding-totem
http://wowwiki.wikia.com/wiki/Freezing_Trap

**Comment by arekczup** [comment]
tylko castowane zaklęcia ........  trap praktycznie nie jest castowanym  zaklęciem .....

**Comment by Jenovas** [comment]
Zmieniłem treść zgłoszenia.
full789 Nie obchodzą Nas Twoje poglądy, obchodzą Nas tylko i wyłącznie bugi.

**Comment by full789** [comment]
https://www.youtube.com/watch?v=9_FXRU6pfDA zasada dzialania groundinga na roznych spellach

**Comment by debtheone** [comment]
potwierdzam

**Comment by debtheone** [comment]
bump

**Comment by Jenovas** [comment]
Fixed in rev 4805
