### ISSUE TITLE
[PL][items] s10 spell power dagger

### ISSUE THREAD

**Issue by xD123xD123** [Atlantiss/BugTracker#5535]
Niema s10 daggera z spell powerem za honor dla magow w hordzie i ally

http://www.wowhead.com/item=67457/vicious-gladiators-spellblade
tu sa poprawne staty http://wow.gamepedia.com/Vicious_Gladiator's_Spellblade

**Comment by xmesaj2** [comment]
http://cata.openwow.com/npc=40607 Alliance vendor, no idea what's the horde vendor name

Some more missing items
http://cata.openwow.com/item=61342
http://cata.openwow.com/item=61351
http://cata.openwow.com/item=61338

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/5643
