### ISSUE TITLE
[PL][Quest][Mount Hyjal] Signed in Blood

### ISSUE THREAD

**Issue by arfik** [Atlantiss/BugTracker#554]
Jak dziala teraz: Na miejscu jest jeden NPC "Twilight Recruiter Maruk".
Jak powinno dzialac: Na miejscu wedlug filmiku z youtube, powinno byc jeszcze kilku NPCow "Twilight Recruit"
Co dokladnie nie dziala: W grze ktos mi napisal ze trzeba poczekac az sie pojawi NPC, czyli Recruit, albo czekac na crash serwera, w obu przypadkach jest zle bo, albo sie NPC nie spawni, a jesli sie spawni, to jest tylko jeden.

Linki:
wowhead: http://www.wowhead.com/quest=25274
youtube: https://www.youtube.com/watch?v=_2Kc-oLuRI8
Twilight Recruiter Maruk: http://www.wowhead.com/npc=39618
Twilight Recruit: http://www.wowhead.com/npc=39619

**Comment by armano2** [comment]
#608
