### ISSUE TITLE
[PL][Firelands] Ragnaros - Molten Elemental

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#5540]
Molten Elemental - http://www.wowhead.com/npc=53189

Elementale wykluwające się z Molten Seed idą po linii prostej do graczy, co za tym idzie przechodzą przez lawę omijając przy tym np. trapy huntera, zamiast zasuwać po platformie.

Reportuję jako boss/addy chociaż pewnie to wina map ;(

**Comment by Iskra12** [comment]
https://www.youtube.com/watch?v=Ez1pRo1sywY

Filmik co prawda z HC ale tutaj raczej zmian być nie powinno. Od 5.54 część elementali idzie przez lawę  a więc raczej blizzlike.
