### ISSUE TITLE
[EN][Raid][Firelands] Bethilac- Ember Flare

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#5545]
<b>How it should work</b>
Bethilac should cast <a href='http://www.wowhead.com/spell=99859/ember-flare#used-by-npc'>Ember Flare</a> every 5 seconds in phase 2
In addition you can see that damage shouldn't be resisted by fire resistance.(it is on Atlantiss)
Proof 
retail logs <a href='http://www.worldoflogs.com/reports/rt-6i84oys40niuter6/xe/?s=5579&e=5997&x=spell%3D%22Ember+Flare%22+and+type%3DTYPE_DAMAGE&page=2'>Link</a>
<b>How it works now</b>
<a href='http://www.worldoflogs.com/reports/coz8yt5ebhgx7fg0/xe/?s=1634&e=2052&x=spell%3D%22Ember+Flare%22+and+type%3DTYPE_DAMAGE&page=1'>Link</a>
It takes 10+ seconds to cast that spell.

Bug stated above and #5519 make soft enrage mechanics non existent.

**Comment by Quban** [comment]
fixed in rev. 4762
