### ISSUE TITLE
[PL][Death Knight][Pestilence]

### ISSUE THREAD

**Issue by Smiite** [Atlantiss/BugTracker#5551]
Talent Contagion sprawia że doty spreadowane za pomocą pestilence bija 100% (2rank)mocniej, jednak na atlantissie inaczej to się skaluje.
http://imgur.com/H4VYIYD nałożona dota ( z odpalonym trinem z str)
http://imgur.com/FQhYmZj zespreadowana dota z pestilence
http://wowwiki.wikia.com/wiki/Contagion
http://wowwiki.wikia.com/wiki/Pestilence

**Comment by Jenovas** [comment]
Działa poprawnie.
Sprawdzone teraz - Dotka na głównym celu zadaje 280 DMG, po użyciu Pestilience główny cel i cele obok otrzymują po 280 DMG. 

Odpalam Trinket - Dotka zadaje 330 DMG, po użyciu Pestilience jak trinket jest wciąż aktywny główny cel i cele obok otrzymują po 330 DMG. 

Odpalam Trinket - Dotka zadaje 330 DMG, po użyciu Pestilience jak trinket jest już nieaktywny główny cel dostaje wciąż za 330 DMG i cele obok otrzymują po 280 DMG. 

Zamykam.

**Comment by Smiite** [comment]
To jakim prawem dota zespreadowana pestilencem robi mniej niz normalna ?
