### ISSUE TITLE
[EN][Firelands][Item][Trinket] Variable Pulse Lightning Capacitor

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5552]
http://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor

After testing this trinket for a while on a target dummy I found following things;

1. Damage from trinket seems too low.

Test results from Atlantiss with the trinket:
1 stack = 2,6k dmg. No crit.
2 stacks = 3,9k dmg. No crit.
3 stacks = 6,6k dmg. No crit.
4 stacks = 6,9k dmg. No crit.
5 stacks = 7,2k dmg. No crit.

Compared to the results from a warlock from retail during patch 4.2.2:
http://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor#comments:id=1539109
4-stack crit: ~33k
2 stack crit: 16.3k
2 stack hit: 9k, 8.7k, 8.2k
1 stack crit: ~13.5k, 10.7k
1 stack hit: ~6.5k, 6.4k, 6k, 5.6k, 3.1k, 3k

The largest critical strike proc I got from this trinket on Atlantiss was 15,3k dmg (5 stacks proc, influenced by Elemental Mastery buff which buffs the Lightning Bolt dmg by 20%, and having Elemental Fury which should increase critical strike dmg on nature spells by 100%). That means that the critical strikes I should make would be higher than the warlock's procs from the post above, but insteead it's more than double as low with 1 stack more. This was the highest attack I did out of 73 procs on Target Dummy. Nowhere near the dmg from patch 4.2.2 retail.

Maybe the trinket doesn't have the buff it got during retail?
(http://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor#comments:id=1511324)
"This trinket got a stealth buff as of yesterday, or today. It now stacks to a max of 5 and does 300% increased tooltip damage. These are rough estimates, but it should be highly reconsidered as most classes BiS, pre-heroics now!"
This would make sense, since I saw a few times that the trinket stacked up to 6 charges here on Atlantiss.

(http://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor#comments:id=1348049:reply=263382)
"This trinket is buffed today. Quote from Blue post: The trinket Variable Pulse Lightning Capacitor is now pulsier, with more lightning!"

**Comment by Jenovas** [comment]
Fixed in rev 4764
