### ISSUE TITLE
[EN][Firelands][Item][Trinket] Apparatus of Khaz'goroth 

### ISSUE THREAD

**Issue by freddie12** [Atlantiss/BugTracker#5553]
Hello,
The problem with this trinket is that it does not proc from melee critical strikes, it procs only from critical auto-attacks. As a dual-wield frost dk, it is really awesome trinket since you can get 5 stacks easily with Killing Machine procs. However, as i reported above you can not get procs with strikes such as Obliterate,Frost Strike critical hits. I know other classes like Retribution Paladins can not get stacks with Crusader Strike and Templar's Verdict critical hits as well. 

wowhead link http://www.wowhead.com/item=68972/apparatus-of-khazgoroth#comments
Video: https://www.youtube.com/watch?v=G_YOYhnnHZY

As you can see in comments section and the video, it should proc from Frost Stirke and Obliterate crits. I know you have some other bugs to fix immediately and probably you are aware of the issue with this trinket but this bug just makes it crap. I hope you fix it as soon as possible. Keep up your awesome effort on the server and good luck. Happy new years.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/5493
