### ISSUE TITLE
[EN][NPC/Item] Main-hand S10 daggers not sold at Honor Quartermaster in SW

### ISSUE THREAD

**Issue by trvis** [Atlantiss/BugTracker#5555]
HI, just a quick post to let you guys know  that only off-hand daggers (the one on the left hand) are sold in Stormwind, there's no way to buy the one you equip on your right hand. I can't switch my old green dagger in order to realy start arenas, I hope this won't last too long

**Comment by Bildo** [comment]
link to those dagagers

**Comment by trvis** [comment]
Here it is, it's in french tho sorry for it, couldn't find the english version 

http://fr.wowhead.com/item=61328/coutelas-du-gladiateur-vicieux

It also concerns the non-left-handed weapons such as swords, maces...

**Comment by trvis** [comment]
Sorry for the slight delay, but here is the link to the dagger in question.

http://fr.wowhead.com/item=61328/coutelas-du-gladiateur-vicieux

It also concerns the non-left-handed weapons such as swords, maces...

2016-01-03 17:12 GMT+01:00 Bildo <notifications@github.com>:

**Comment by Bildo** [comment]
Yes, I know i jsut realised this topic is a duplicate.
