### ISSUE TITLE
[EN][Achievement][NPC-related][Mount Hyjal] The Fiery Lords of Sethria's Roost(ID 5861)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5557]
All of the mobs that required for the achievement are not spawned.This mobs are linked together and only one is spawned each time but when someone kill the spawned one the next one is spawned until all 4 are killed and the respawn time start count.Which one will start the chain of spawns is random.

Mobs for the achievement: 
[Searris <Lord of Embers>](http://www.wowhead.com/npc=53264/searris)
[Kelbnar <Lord of Ashes>](http://www.wowhead.com/npc=53265/kelbnar)
[Andrazor <Lord of Cinders>](http://www.wowhead.com/npc=53267/andrazor)
[Fah Jarakk <Lord of Smoke>](http://www.wowhead.com/npc=53271/fah-jarakk)

Wowheda Link: [The Fiery Lords of Sethria's Roost](http://www.wowhead.com/achievement=5861/the-fiery-lords-of-sethrias-roost)

Probably reason is this bug: https://github.com/Atlantiss/BugTracker/issues/5488

**Comment by Samineh** [comment]
:+1:

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11226-achievement-npc-the-fiery-lords-of-sethrias-roost/

**Comment by Malylolek** [comment]
Fixed in rev. [5151](http://atlantiss.eu/changelog#rev5151)
