### ISSUE TITLE
[EN][Item][Loot]Big-Mouth Clam

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5558]
http://www.wowhead.com/item=7973/big-mouth-clam#contains
I was farming these for a black pearl which thankfully I got lucky with and after about 20 kills I got what I wanted but what I noticed is that they are dropping the wrong clam meat. Wowhead says it should drop Zesty Clam Meat http://www.wowhead.com/item=7974 but most of the time I got Tangy Clam Meat and Giant Clam Meat

**Comment by Bildo** [comment]
fixed
