### ISSUE TITLE
[EN][Quest][Darkshore] The front line

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#5560]
In this quest you should report to Huntress Sandrya Moonfall, but she isn't where the map marks her position and not even in the entire area.

http://www.wowhead.com/quest=13590/the-front-line#screenshots

![wowscrnshot_010116_060250](https://cloud.githubusercontent.com/assets/11901135/12069797/5c66c72c-b04d-11e5-808d-ee5c41a097f9.jpg)

**Comment by Thefakemccoy** [comment]
I think it is because the shatterspear chamions kill her.

**Comment by Aival94** [comment]
Is reported here as well: https://github.com/Atlantiss/BugTracker/issues/3425
The problem is that it have some phases issues when someone else finish any of the quests there.
