### ISSUE TITLE
[PL][Achievement] Ludicrous Speed

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5563]
http://www.wowhead.com/achievement=5862/ludicrous-speed
"Zbieranie ptaszków" podczas questa Call of Flock : http://www.wowhead.com/quest=29147/call-the-flock nie nabija nam Soar

https://www.youtube.com/watch?v=W6JchPiN1gM Tutaj widac jak powinno działac.

**Comment by Aival94** [comment]
When you are on quest [Call the Flock](http://www.wowhead.com/quest=29147/call-the-flock) for each bird you should get specific speed using [Soar](http://www.wowhead.com/spell=99321/soar) and stack the buff [Soar](http://www.wowhead.com/spell=100957/soar) which maximun stacks you can get are 75 stacks.

Stacks per bird:
[Alpine Songbird](http://www.wowhead.com/npc=52595/alpine-songbird) give 1 stack per bird for 6 seconds
[Forest Owl](http://www.wowhead.com/npc=52596/forest-owl) give 5 stacks per bird for 8 seconds
[Goldwing Hawk](http://www.wowhead.com/npc=52594/goldwing-hawk) give 15 stacks per bird for 8 seconds.

**Comment by Wolffenstein** [comment]
![wowscrnshot_010116_171811](https://cloud.githubusercontent.com/assets/1576644/12071414/bafa7596-b0ab-11e5-912b-44a58bc5c3cb.jpg)

**Comment by Aival94** [comment]
I will check it again when i get quest as might be my visual bug but i did not receive buff or speed.

**Comment by Thefakemccoy** [comment]
Its not stacking for me.

**Comment by Bastion** [comment]
![image](https://cloud.githubusercontent.com/assets/1584564/12217566/c164d1ec-b704-11e5-8d45-49acea1e1110.png)

**Comment by Thefakemccoy** [comment]
It works for some has not for me.

**Comment by LaveniaGithub** [comment]
Achievement works for everyone, I couldn't see the stacks myself until I clicked on my own healthbar and saw it as buffs there.
![skaermbillede 2016-01-10 kl 01 13 57](https://cloud.githubusercontent.com/assets/12621497/12219198/dd509326-b738-11e5-8b7e-3ef072cc1826.png)

**Comment by Aival94** [comment]
The problem is you cannot see the stacks(the speed is shown normally.I think is a general problem about the form you take as you cannot see any buff you had before as well.So achievement can be done(speed and stacks are given) but you cannot see the stacks and the timer as you cannot see any buff at all.

**Comment by Bastion** [comment]
set ur character at focus

**Comment by Aival94** [comment]
This one is a temporary fix but still you should be able to see the stacks without setting your character to focus.
