### ISSUE TITLE
[EN][gameobject][Elwynn Forest] Wanted Poster not giving quest

### ISSUE THREAD

**Issue by tristanvm** [Atlantiss/BugTracker#5564]
Minor issue, the other poster does in fact give the quest but for some reason this poster just greets me.
Picture with proof that it should give the quest down below.
http://i.imgur.com/Xe3heFc.jpg

**Comment by ardo22** [comment]
Fix: http://community.atlantiss.eu/index.php?/topic/7501-5564gameobject-wanted-poster-not-giving-quest/
