### ISSUE TITLE
[PL][Quest]Gnomebliteration

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5565]
Po wziecu questa kula toczy sie w miejscu i nic dalej sie nie dzieje a powinienem nia sterowac , 
nie wiem czy ma to zwiazek z tym ze bylem w cat form 
http://www.wowhead.com/quest=27779/gnomebliteration

**Comment by Thefakemccoy** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/4754
