### ISSUE TITLE
[PL][Item] Vicious Gladiator's Insignia of Dominance s10

### ISSUE THREAD

**Issue by strzala** [Atlantiss/BugTracker#5567]
Wersja Trinka z Intem nie posiada Internal Cooldown, co znaczy ze buff się odświeża i trwa nieprzerwanie dopóki mamy combat i np. nałożoną jakąś dotę na target dając non-stop 1077 spell power.

http://www.wowhead.com/item=61045/vicious-gladiators-insignia-of-dominance#comments

Nie wiem jak maja się inne wersje z agi i str, oraz te Ruthless. Poprzednie, niższe wersje mialy ICD.

**Comment by Bildo** [comment]
fixed in rev 4766
