### ISSUE TITLE
[PL][Achievement] Infernal Ambassadors

### ISSUE THREAD

**Issue by Porobiony** [Atlantiss/BugTracker#5571]
http://www.wowhead.com/achievement=5869/infernal-ambassadors#comments Punkty z Lylagarem, Galengesem i Nemesis działają, natomiast część z Millagazorem nie zalicza mimo pozostawania w ruchu aby uniknąć obrażeń od Gout of Flame, ostatniej jeszcze nie sprawdziłem

**Comment by Wolffenstein** [comment]
Trzeba chociaż raz być jego targetem przy Gout of Flame, żeby zaliczyło.
