### ISSUE TITLE
[PL][WARLOCK][PET][FELGUARD][FIRELANDS] felstorm nie sięga bossa.

### ISSUE THREAD

**Issue by Assiria** [Atlantiss/BugTracker#5572]
Felstorm felguarda nie sięga bossa, stoi w połowie platformy i go bije, natomiast gdy odpale felstorma to pet nie zadaje dmgu, podobna akcja jest z DnD u dk które trzeba rzucać pod ragnarosa by go sięgał...

**Comment by Glare** [comment]
Podobnie jest z Sinestrą i Alakirem. Problem zdaję się leżeć w hitboxie a nie samych spellach. Jeżeli do tej pory tego nie naprawili to nie spodziewałbym się zmian w najbliższym czasie. Ze swojej strony proponuję zmianę speca na dowolny z 2 pozostałych bo Demo na tym encounterze jest naprawdę upośledzone.

**Comment by vanael** [comment]
Na samego Raganrosa shadowflame nie działa. Czy podejdę pod samego bossa czy jestem oddalony to spell i tak nie trafia go.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/594

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4867
