### ISSUE TITLE
[PL[Raid][Firelands][Debuff] Ragnaros - Blazing Heat

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#5573]
Blazing Heat (http://www.wowhead.com/spell=99128/blazing-heat) nie powinien zaznaczac targetow trzymajacych Addy/Bossa. U Nas potrafi zostac nalozony na tankow trzymajjacych i addy i bossa i odbiegajacy tank z addem powoduje ze ów add sie leczy.

[min.: http://www.icy-veins.com/wow/ragnaros-tank-strategy - punkt 5]

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev4767
