### ISSUE TITLE
[EN][EXPLORING][ZONE][ACHIEVEMENT] Azuremyst Isle, Bristlemaw Village

### ISSUE THREAD

**Issue by SurrealismAtlantiss** [Atlantiss/BugTracker#5576]
Bristlemaw Village cannot be discovered. Other peoples told me that this is working. It's not, i tried many times, in all places. Because of that, i cannot achieve World Explorer title.

[26.8, 65.9] - Coords.

**Comment by Thefakemccoy** [comment]
Can this title be corrected to Bristlelimb not Bristlemaw

**Comment by Aviannaqt** [comment]
rev. 4856
