### ISSUE TITLE
[EN][Quest][Arathi Highlands][minor] Triage (Horde)

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5577]
http://www.wowhead.com/quest=6622/triage
http://wowwiki.wikia.com/wiki/Quest:Triage_(Horde)
According to wowhead and wowwiki, as shown in the links above, the quest Triage (Horde) is part of a quest chain and should become available only after turning in the quest Horde Trauma (http://www.wowhead.com/quest=6623/horde-trauma).
How it is bugged: The quest Triage (Horde) is available without completing the prerequisite.

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7447-5577quest-triage/
