### ISSUE TITLE
Culling of Stratholme WotLK 

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#5581]
1. arthas near the end keep running into all the mobs on the way (where you make the zombie achievment) and literally kills himself, if you dont clear the way before him, and someone needs to stand near him so he doesnt dissapear
2. salramm the fleshcrafter, kills himself when you kill one of his ghouls that HE summons, leaving you with no loot from him and it would be like you didint even kill him
3. the chest at the end from Malganis CANT BE OPPEND , i was there afk waiting for  a GM to help, meanwhile the server crashed 2 times and after the second the chest was able to be opend

**Comment by Bildo** [comment]
read bt rules

**Comment by scidrov** [comment]
gues it wont be fixed then, thanks for nothing

**Comment by Bildo** [comment]
thanks to you
