### ISSUE TITLE
[EN][raid-cata][Firelands] Alysrazor

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#5582]
While raiding yesterday we noted few bugs; When a Voracious Hatchling is being dropped, upon breaking out of the egg, they 'cast' a spell called ''Imprinted'' on the nearest target, only attacking this player but giving them a damage buff (1000%). 

http://www.wowhead.com/spell=99389/imprinted

In our 25 man raid we noticed only 1 tank gets the buff, the other tank, tanking the 2nd hatchling does NOT get the buff. Which makes it insanely hard to kill them, and you will eventually have an insane amount of dmg in the 4th phase. 

Another bug we noticed about the Voracious Hatchling:
The spell Gushing Wound: http://www.wowhead.com/spell=99308/gushing-wound

This spell should get removed when someone drops below 50% hp, but it doesn't. It will stay on every person until the debuff runs off.

2nd phase: During this phase you need to avoid tornado's etc. Though if for example you are getting damage for some reason, and you use Divine Shield, Ice block or Cloak? You keep getting dmg and you will just die. So the spells in that phase keep doing damage even if you are supposed to be immune for any kind of damage.

Another bug occurs when you for example wipe on Day 1. The next day you re-enter the instance and you want to encounter Alysrazor. Both Majordomo as the feather (in the middle of the room) are up. Normally Majordomo should only appear the first time you try to encounter the boss, and should than disappear. Though when you re-enter the instance after for example 5 wipes, the day after, and you pull the boss with the feather, you activate the boss, pets will go attack the boss and pull the boss a 2nd time (even when the fight already started). Majordomo than roots everyone for 30seconds during the fight, hatchlings will spawn, initiates are already casting, and a wipe will happen 100%. Or you remove the feather, or make sure majordomo isn't there anymore. After wiping you will end up with an infinite combat bug which makes you unable to enter the instance.

**Comment by Thefakemccoy** [comment]
Boss not resetting after some wipes

**Comment by Thefakemccoy** [comment]
Not sure if this is a bug cant remember. But i dont think 1 tank should be able to tank both Voracious Hatchling. 1 tank can be imprinted by both.

**Comment by Quban** [comment]
imprinted is fixed

**Comment by Quban** [comment]
and i think boss should reset from now on, but im not sure ;d

**Comment by Frainzil** [comment]
1 tank is not able to kill 2 adds on 25man mode. We tried it, it's almost impossible :)

**Comment by Quban** [comment]
you dont know how to dps with tank xD

**Comment by Frainzil** [comment]
Shush! I blame bugs! :D

**Comment by Pacogt** [comment]
on Alysrazor is another bug with Brushfire casted by Blazing Talon Initiate those ballz deals no dmg

**Comment by Quban** [comment]
> on Alysrazor is another bug with Brushfire casted by Blazing Talon Initiate those ballz deals no dmg

fixed ill upload with more fixes :p
