### ISSUE TITLE
[EN][raid-cata][Firelands] Lord Rhyolith

### ISSUE THREAD

**Issue by Frainzil** [Atlantiss/BugTracker#5583]
1) DBM no longer works, When you start the encounter, 0 timers are given to you and this does not change throughout the fight.

2) When you wipe on this fight, you are unable to enter the instance. We waited for approximately 15 minutes but we kept getting the message ; You are unable to enter this zone ..... '' Meaning the encounter did not reset properly. (Similar to the Ascendant Council bug on heroic mode?)

**Comment by Exertt** [comment]
This bug seriously needs to be fixed ASAP. One wipe and your whole instance is done for until server crashes.

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/6031
