### ISSUE TITLE
[EN][Other][Durotar] Razor Hill Crash

### ISSUE THREAD

**Issue by Khangu** [Atlantiss/BugTracker#5584]
Game crashes after entering Razor Hill. Removing Catche, changing settings and installing new & clean client doesn't help at all.

As far as I know couple of other people have same problem.

Some coordinates where problem appears:
279.445,-4742.11,9.6458
308.835,-4727.31,9.84865
but this "crash zone" seems to cover whole center part of Razor Hill.

What is most important - everything was working fine all time till afternoon so something started crashing today.

**Comment by woodenengine** [comment]
I'm having the same problem; this is a huge issue for me because I took a flight path that goes over Razor Hill, and every time I fly over it, my client crashes and I am returned to the beginning of my flight path.

**Comment by Ado125** [comment]
Got same problem. I cant find any unstuck button on website so im pretty much blocked. I flew there by and im in the middle of razor hill. Client crashes just when i start game and im unable to make even one step so i cant get out at all... Any help please?

**Comment by Khangu** [comment]
Tried some things:
Unchecking "read only" in game folders properties do not help.
Changing classes, races etc does not help.
Instaling clean WoW copy on different PC with different Win and drivers also do not help at all.

And since this region was working alright all the time it has to be server not client issue.

**Comment by Lunni** [comment]
Same here. I took a flight from Sen'Jin Village to Razor Hill and it crashed right after landing. Using HS to Razor Hill on other character ended the same. Everything was OK yesterday and suddenly isn't any more. :/ I can't even log on character in RH because it's crashing over and over again.

**Comment by Bildo** [comment]
Should be fixed after crash/restart
