### ISSUE TITLE
[EN][Quest][Orgrimmar]Blown Away(ID 29401)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5585]
Quest should not only be available to horde players.Now is available to at least worgen race players as well.

![wowscrnshot_112315_234714](https://cloud.githubusercontent.com/assets/10282971/12074968/08e533cc-b179-11e5-855d-b20f948b63ba.jpg)

Wowhead Link: [Blown Away](http://www.wowhead.com/quest=29401/blown-away)

**Comment by Achiver** [comment]
It's available for all ally races here. You can't use the pet as an ally anyway

**Comment by Aival94** [comment]
/no
/pat
Yeah i remember you.Yeah in atlantiss is available to all races.I have not done it so i do not know about the pet but i posted the screenshot to show proof of the quest be available to alliance races right now which should not.
