### ISSUE TITLE
[PL] [ERROR]

### ISSUE THREAD

**Issue by Saliar** [Atlantiss/BugTracker#5589]
Podczas, grania w pewnych miejscach gre poprostu wywala, i wyskakuje error o następującej treści http://scr.hu/1kx9/45uqd.

**Comment by tristanvm** [comment]
This does not belong here but here's your solution. Change your Data folder, make sure read-only is unchecked.

**Comment by Saliar** [comment]
It, doesn't work. And data folder automatically change read-only checked.

**Comment by Krak123** [comment]
I have the same problem after logging in and loaded me immediately crashes

**Comment by Reversion** [comment]
Bug Tracker to nie miejsce do rozwiazywania problemow tego typu. Poszukajcie pomocy na forum
