### ISSUE TITLE
[PL] Mam problem z włączeniem gry.

### ISSUE THREAD

**Issue by Krak123** [Atlantiss/BugTracker#5594]
Wyskakuje mi error widoczny tutaj http://scr.hu/1x1o/830jw i nie wiem co z tym zrobić pobrałem przez torrenty

**Comment by Anhaeyn** [comment]
Znajdź w folderze gry plik .exe, usuń go, pobierz ze strony nowy plik (sam .exe) i wstaw do folderu - powinno pomóc. 
A jakby nie zadziałało, kiedyś mojej znajomej pomogło wyłączenie programu od torrentów ;)
