### ISSUE TITLE
[EN][Quest][Blackrock Depths]The Grim Guzzler

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#5601]
http://www.wowhead.com/quest=27589/the-grim-guzzler

"To spawn Hurley Blackbreath you must break all 3 kegs located within a small storage room inside the bar.

Hurley Blackbreath will spawn with 3 guards."

After you smash those 3 kegs he doesn't spawn so he cant be killed and thus far blocking the rest of the chain witch lead to http://www.wowhead.com/quest=27593/rebirth-of-the-k-e-f effectively removing all quests from the other part of the instance.

**Comment by Achiver** [comment]
In addition the 3 kegs are overlapping in one place

**Comment by aendry** [comment]
still

**Comment by Piklo** [comment]
#8999 reported with issue_template
