### ISSUE TITLE
Aeonaxx

### ISSUE THREAD

**Issue by dirtystoner** [Atlantiss/BugTracker#5604]
I spend more than20 hours w8ing and more than 4 hours trying to kill aeonax with my hunter ,after dieing because i couldnt atack nither adds nor aenoaxx i dismounted ( diengage before ground > feign death > .combatstate > mount up > dismount next to aenoaxx , do 3 dmging skill > rocket jump before ground > .combatstate and so on for 4 hours .... when aeonaxx was at 15 % hp it dissapeared , now tell me waht am i to do with all this time wasted ?

**Comment by Incia** [comment]
how to use BT https://github.com/Atlantiss/BugTracker

**Comment by dirtystoner** [comment]
This is  my personal problem , nothing like the others ... dont link me the bug tracker rules

**Comment by Anhaeyn** [comment]
Even if it's your personal problem, name it properly, because it's NEEDED. Even if you don't speak polish, everyone must name their issues properly and following the rules. Otherwise they'll close it without solving.
