### ISSUE TITLE
[EN][Quest/NPC] Griswold Hanniston

### ISSUE THREAD

**Issue by Khangu** [Atlantiss/BugTracker#5605]
Quest is bugged cause NPC doesn't attack after challenging him and remain friendly, thus he can't be defated in duel.

http://www.wowhead.com/quest=25258/griswold-hanniston

As far as I know quest was working fine few weeks ago.

**Comment by Khangu** [comment]
It seems NPC is acting correct first time (after restart or stmh).
I noticed that other gladiators from nearby quests turn friendly at the end of the fight to prevent killing them, and then switch back to neutral.
However Griswold reamains friendly and cannot be fought any more.

**Comment by xtul** [comment]
bump

**Comment by Dean1989** [comment]
still same problem

**Comment by Samineh** [comment]
Bump :) :+1:

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15298-9629958169265605-griswold-hanniston-smart_scripts/

**Comment by Jenovas** [comment]
Fix in 5537
