### ISSUE TITLE
[EN][NPC][Stromwind][T11 Paladin]Magatha Silverton

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5609]
The JP vendor is offering pally T11 gear multiple times one set is normal price then again at a cheaper price.
http://www.wowhead.com/npc=44246/magatha-silverton

![wowscrnshot_010216_234702](https://cloud.githubusercontent.com/assets/12252441/12077298/3d5757c0-b1ab-11e5-8f5c-93ff63390ff8.jpg)
![wowscrnshot_010216_234705](https://cloud.githubusercontent.com/assets/12252441/12077299/43b7e6d4-b1ab-11e5-9f15-cdb0c9f5743c.jpg)
![wowscrnshot_010216_234706](https://cloud.githubusercontent.com/assets/12252441/12077300/4acad882-b1ab-11e5-8b43-c4341a56c112.jpg)
![wowscrnshot_010216_234707](https://cloud.githubusercontent.com/assets/12252441/12077303/55994500-b1ab-11e5-9d4b-af8ff556359c.jpg)
![wowscrnshot_010216_234709](https://cloud.githubusercontent.com/assets/12252441/12077305/5f649990-b1ab-11e5-86e6-8c3f8cea6952.jpg)

**Comment by Aviannaqt** [comment]
duplicate

**Comment by Thefakemccoy** [comment]
No wonder i couldnt find it i have no clue what a cena is

**Comment by Aviannaqt** [comment]
#5507

**Comment by Thefakemccoy** [comment]
Ya but what is a cena?

**Comment by Bildo** [comment]
cena means price
