### ISSUE TITLE
[EN][Web] Armory doesn't show all new 4.2 items

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#5613]
![Screenshot](http://i.imgur.com/Yc5JJSB.png)
Items tooltips are not shown, model isn't generated and there are no icons.

**Comment by Khangu** [comment]
Additionaly armory shows question mark icon in ranged weapon slot instead of equipped weapon.

**Comment by xmesaj2** [comment]
Yes relic/thrown/libram slot shows question mark ![Armory unknown bonus](http://i.imgur.com/kGboeg1.png) Also some items seems to show Unknown Bonus /#number instead

**Comment by xmesaj2** [comment]
Fixed as of 02/07/2016
