### ISSUE TITLE
[PL][Spel][Warlock] Fel Armor

### ISSUE THREAD

**Issue by Wojteksc** [Atlantiss/BugTracker#562]
Po użyciu "Soulburn" http://cata.openwow.com/spell=74434 oraz "Drain Life" http://cata.openwow.com/spell=689 zostaje usunięty "Fel Armor" http://cata.openwow.com/spell=28176 z naszego przeciwnika warlocka. Dodatkowo efekt jest taki sam, jeśli użyjemy przed Drain Life "Demon Soul" http://cata.openwow.com/spell=77801. 

Dowód:
http://youtu.be/R48FfxHC9c4?list=PLvDxvkCgvtUYAUYIhVLlAEc2lNrC7IPKK

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
