### ISSUE TITLE
[EN][Quest][Northern Stranglethorn] Arena Grandmaster

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5620]
http://www.wowhead.com/quest=7838/arena-grandmaster
According to wowhead, this quest is repeatable.
How it is bugged: The quest Arena Grandmaster is not repeatable.

**Comment by cano112** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/7448-5349quest-an-oox-of-your-own/

**Comment by Aldurion** [comment]
That is related to the oox of your own quest.
