### ISSUE TITLE
[EN][NPC][Ghostlands] Farstrider Troll-Hunter

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5623]
http://www.wowhead.com/npc=53071/farstrider-troll-hunter#comments
How the npcs are bugged: They have only 10 healthpoints.
According to 4.3.4 wowhead comments, they should have 842,048 HP.

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11602-5623-npc-farstrider-troll-hunter/

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12503-5623npcghostlands-farstrider-troll-hunter/
