### ISSUE TITLE
[EN][Web] Vote System

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#5631]
Currently voting gives points even without actually voting, just clicking on vote button in vote panel gives them

All sites are affected with bugs, poinst should be granted after completing captcha and visiting server again from toplists as source:

openwow - gives no points even when completed captcha and visited server from toplist

gtop100, extremetop100 - get blocked by ad blockers, but still giving points, also no need to complete captchas and visit server from toplist

extremetop, top100arena, gowonda, topg, wowstatus, rpgparadize - gives points without completing captcha and visiting server page

**Comment by xmesaj2** [comment]
#4096

**Comment by xmesaj2** [comment]
top100arena, xtremetop100, gtop100 also don't have toplist thumbnails

**Comment by BialyADI** [comment]
openwow don't give vote point it broken.

**Comment by xmesaj2** [comment]
openwow voting now works, but still you can cheat the system by just visiting links and not voting
