### ISSUE TITLE
[PL][Npc]Nethergarde Defender

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5634]
Ci npc mimo ze sa na czerwono nie da sie ich atakowac 
http://www.wowhead.com/npc=51792/nethergarde-defender
![wowscrnshot_010216_010909](https://cloud.githubusercontent.com/assets/16046575/12082042/f7553c10-b28b-11e5-98c0-affe965a521f.jpg)

**Comment by Aviannaqt** [comment]
Nie jestem pewien czy powinno sie dac.

**Comment by Bildo** [comment]
Sa do questa potrzebne wiec sie powinno.
