### ISSUE TITLE
[PL][Npc]Neptool

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5635]
Ten Npc jest w niewlasciwym miejscu 
http://www.wowhead.com/npc=41354/neptool
![wowscrnshot_010216_012521](https://cloud.githubusercontent.com/assets/16046575/12082077/740a06dc-b28c-11e5-83ed-0e21104f6f84.jpg)

**Comment by aje** [comment]
just checked this morning and he was at the good position
