### ISSUE TITLE
[EN][Web] http://www.wowhead.com/item=68972/apparatus-of-khazgoroth

### ISSUE THREAD

**Issue by eshelyn** [Atlantiss/BugTracker#5640]
why closed my topic.. This trinket only procs with white damage Aka melle auto attack critical,, 
in retail this procs from every single spell melle swing critical too exmple Crusader strike, judgement,etc

**Comment by freddie12** [comment]
they know the issue but they choose to do nothing at all. that's why you report is deleted.

**Comment by Kejmil** [comment]
it's already reported, that is why they are closing next similiar issues...
https://github.com/Atlantiss/BugTracker/issues/5493
