### ISSUE TITLE
[EN][Battleground][PvP] Twin Peaks respawn

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#5642]
In Twin Peaks battleground players respawn as ghosts in the middle of their faction base when nearest graveyard is further than base instead being taken straight to the nearest graveyard. This also happens when you click button "teleport to graveyard", when graveyard is further than base, it teleports to base. You have to run towards graveyard and click button to teleport into it and get revived by spirit healer.

**Comment by Goraix** [comment]
bump zdarza sie to nagminnie czesto i przez to przegrywa sie bg

**Comment by karama300** [comment]
Very important to fix!

**Comment by Jenovas** [comment]
What is the bug? I didnt understand a thing.

**Comment by xmesaj2** [comment]
There is extra respawn in bases

If you are A and B is base and C is graveyard and you die like
B--A--------C you are placed as ghost in base
B--------A--C you are placed correctly in graveyard

**Comment by Jenovas** [comment]
"I'll start with Twin Peaks. there are two GYs: one at each base and one in the middle"

**Comment by xmesaj2** [comment]
Shouldn't they be on the rocks instead in the building? Spirit healers are on rocks.

**Comment by Jenovas** [comment]
So the placement of the graveyard is wrong?

**Comment by xmesaj2** [comment]
http://i.imgur.com/ulYSqQR.jpg

green are correct graveyards and with spirit healer

red are points in bases that you are teleported to as ghost if you die closer to them instead graveyard. also no spirit healer inside the buildings and these shouldn't be respawn locations. they should only be first/starting spawn locations (when you join battleground battle) but not act as graveyard when you died

**Comment by Jenovas** [comment]
Ok I get it now, there are additional graveyards in the flag room. Thx. 
I'll a look at it in a sec.

**Comment by Jenovas** [comment]
Fixed in rev 4894
