### ISSUE TITLE
[EN][NPC]Blood Guard Zar'shi-Knight-Lieutenant T'Maire Sydes missing pvp weapons

### ISSUE THREAD

**Issue by Evelinrose** [Atlantiss/BugTracker#5643]
Both alliance http://www.wowhead.com/npc=69974/knight-lieutenant-tmaire-sydes and horde http://www.wowhead.com/npc=52536/blood-guard-zarshi  npc's have following items missing.
http://www.wowhead.com/item=61327/vicious-gladiators-shanker
http://www.wowhead.com/item=61329/vicious-gladiators-spellblade
http://www.wowhead.com/item=61338/vicious-gladiators-gavel
http://www.wowhead.com/item=61324/vicious-gladiators-cleaver
http://www.wowhead.com/item=61325/vicious-gladiators-hacker
http://www.wowhead.com/item=61345/vicious-gladiators-quickblade
http://www.wowhead.com/item=61344/vicious-gladiators-slicer
http://www.wowhead.com/item=61336/vicious-gladiators-bonecracker
http://www.wowhead.com/item=61335/vicious-gladiators-pummeler
http://www.wowhead.com/item=61333/vicious-gladiators-right-render
http://www.wowhead.com/item=61331/vicious-gladiators-fleshslicer
http://www.wowhead.com/item=61330/vicious-gladiators-ripper
http://www.wowhead.com/item=61332/vicious-gladiators-slasher

**Comment by xmesaj2** [comment]
Captain Dirgehammer http://cata.openwow.com/npc=51254 (Conquest vendor) has them now instead honor vendor

**Comment by Bildo** [comment]
ups :D
