### ISSUE TITLE
[PL][Quest]The shadow Grave

### ISSUE THREAD

**Issue by wild1721** [Atlantiss/BugTracker#5644]
Nie działa pierwszy quest w Trisfal Glades. Quest powinien działać tak: https://www.youtube.com/watch?v=QEUW4JE6BlU
Nie można jednak wziąć itemu "Corpse Stitching Twine". Jest to pierwszy quest więc nie można rozpocząć gry Undeadem.
Link do questa: http://www.wowhead.com/quest=28608/the-shadow-grave

**Comment by Erthar** [comment]
W zasadzie to jest już drugi quest. Dziwi mnie, że kilka dni wcześniej działał ten q. Jest jakieś wyjaśnienie dlaczego nagle sie zbugował ?

**Comment by Thefakemccoy** [comment]
Can confirm the items are not contained in the 2 thing you have to click to loot.

**Comment by krecik88** [comment]
very weird because right now i've looted them

**Comment by Erthar** [comment]
same

**Comment by krecik88** [comment]
closing for now, please make another topic if bug appears again

**Comment by Wolffenstein** [comment]
Fixed in rev 4800.

**Comment by Samineh** [comment]
It is bugged again.
