### ISSUE TITLE
[EN][ACHIEVEMENT][EXPLORER] Azuremyst Isle - Bristlelimb Village

### ISSUE THREAD

**Issue by karka90** [Atlantiss/BugTracker#5647]
I have a problem. When I'm on the Azuremyst Isle I can't complete the Achievement because I cannot explore the Bristlelimb Village. When I'm in this area it shows that this location in unknown. Please do something about it.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5576

**Comment by Aviannaqt** [comment]
reported 1293812938129 time...

**Comment by Thefakemccoy** [comment]
I reason no one can find it if they search is it is not labeled as the right place.
