### ISSUE TITLE
[EN][PL][Quest][Elvynn Forest] - Fear no Evil

### ISSUE THREAD

**Issue by shaylopl** [Atlantiss/BugTracker#5650]
Witam. http://www.wowhead.com/quest=28812/fear-no-evil 
Quest działa - aczkolwiek akcje z itemem który należy użyć na danym ciele/NPC można powielać i nawet 4x naliczyć na raz na jednym ciele/NPC.

Hello. http://www.wowhead.com/quest=28812/fear-no-evil
Quest works - but actions with item quest which we have to use on body/NPC can multipling, so we can at least use 4x in a row on same NPC/body.

Sorry if my english is bad xd.

**Comment by Wolffenstein** [comment]
W jaki sposób? Jak klika się na npca to znika przecież możliwość kliknięcia na niego ponownie.

**Comment by shaylopl** [comment]
Normalnie, dziś (ok. 13godz jakoś) expiłem sobie humana paladyna i mogłem wyklikać jedną postać nawet 3 razy.
Zresztą zrobie go na nowo aby potwierdzić - bo akurat wtedy były lagi.

**Comment by Emielos** [comment]
This quest seems bugged, i don't get credit for healing the injured soldiers
