### ISSUE TITLE
[PL][Firelandy i dodatki]

### ISSUE THREAD

**Issue by Smiite** [Atlantiss/BugTracker#5653]
Firelandsy
-http://imgur.com/AJv3vsZ
Gigant powinien zrzucać pająki na dół.
-http://imgur.com/jEECs2O
Na Aatlantissie nie ma wogóle pajaka na fenixie, żeby dostać buffka trzeba zbić 2 pajaki po bokach dopiero wtedy spada pająk z feniks, który odlatując daje buffa graczom.
-http://imgur.com/Np3lkzb
Psy powinny atakować pajaki.
-http://imgur.com/ADc6Fos
Tarcza nie zasłania dużo miejsca + odpycha trochę do tyłu. Na atlantissie bańka odrazu odpycha do ściany i pokrywa prawie całe miejsce.

http://imgur.com/xPbM0o4  Animatory mają cały czas redukcje dmg po aktywowaniu eventu a na Atlantissie wrzucają sobie kiedy chcą.
http://imgur.com/nxG0wQ2  Na Atlantissie można odrazu go bić, powinno mu zejść debuff dopiero kiedy zabije się każdego animatora.

http://imgur.com/mE5ELbL
Kar'a nie można zranić dopóki nie wycofa się do tyłu i nie przybiegną 2 Pyrelordy, u nas można go zabić odrazu ponieważ nawet nie wycofuje się do tyłu

http://imgur.com/1Ai32Fi Brakuje parę kotków.

Bossy:
Shannox:
- ma szanse na zgubienie psa gdy okrąża firelandsy

-brakują 2 komunikatów przy zabijaniu stworów na firelandsach
dodatkowo
" Yes... I smell them too, Riplimb. Outsiders encroach on the Firelord's private grounds. Find their trail, find them for me, that I may dispense punishment!" powinien mówić kiedy wychodzi .

Rhyolith:
- Addy które przywołuje powinny po 2 sekundach dopiero się agrować na graczy, u nas rzucają się odrazu.

Beth'tilac
-Boss lubi schodzić na dół podczas pierwszej fazy ponieważ zmienia target na heali
-podnoszenie się na gore powinno trwać krócej.

Ragnaros:
-nie można na bossie użyć shadowflame, death and decay,immolation aura/ felguard felstorm
- podczas pierwszej przejściówki boss atakował z aa , nie zostawił plamy na ziemi gdzie stal młotek, więc nie wiadomo do którego miejsca idą addy.
- Each player targeted by a Living Meteor should move toward the rear of the platform, and then to the far corner, so that the meteor will be away from other players as much as possible. When the meteor corners a player, that player should use a direct ranged attack on it, which will cause the meteor to target someone else
U nas musi inna osoba zaatakować żeby meteor zmienił aggro.

BWD
-bossy lubią tracić aggro i switchują na healerów(meele ataki prawdopodobnie nie nabijają aggro.)
Vortex Pinnacle
-zgony bez uzasadanienia gdy leci się przez wirki na nastepną platformę z 2 na 3.
Pvp
-feary na arenie wrzucają w tekstury i następuje teleportowanie na środek areny np na dalaranie
-mag może zginąć podczas ice blocka (Kaldorn)
-gdy pet dostaje feara jest duża szansa że się zbuguje i nie bedzię się ruszał/ będzię latał podczas cc
-dr na rooty chyba nie działa ponieważ grając na 2 magów ciągle dostaje sie pełnego roota
-mmr liczone jest w dziwny sposób bo odejmuje za wina a za lose dodaje mmr.

Molten Front:
http://www.wowhead.com/npc=54323/kirix
Kirix latał gdzieś w powietrzu przy the furnance, Yggr zrespawnił go .

**Comment by Bildo** [comment]
więcej bugów w 1 zgłoszeniu nie mogłeś zgłosić? 1 bug 1 zgłoszenie

**Comment by Kejmil** [comment]
turncoaty tak maja :D
