### ISSUE TITLE
Global Cooldown Delay

### ISSUE THREAD

**Issue by dantethehunter** [Atlantiss/BugTracker#5654]
When you try to quick press buttons, theres almost always a delay that is really annoying. Your character tries to do the spell, then it stops, and when you press it again he finally does it. Thats a very serious bag thats effects not only pve experience but mainly pvp. As a healer i find that very frastruating and i guess all players do. I recenlty came back to Atlantiss and last time i played there isnt such a bug. Please guys fix it asap.

**Comment by dantethehunter** [comment]
To avoid misunderstandings,  this bug doesnt exists because of the general lag the server it has these days. This bug exists even if the server is lag free.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/1087

**Comment by Jenovas** [comment]
Please enter your client settings search for "Lag Tolerance" and set it to 0. Must of the bugs with Global Cooldown or a "smaller cooldown" happening after a cooldown are caused by this (the server doesnt support the Lag Tolerance setting and wont support it for now).

**Comment by dantethehunter** [comment]
That option kinda works. I guess its ok for now. Thanks a lot.
