### ISSUE TITLE
This quest is bugged? First Mate Moody.

### ISSUE THREAD

**Issue by xtremme** [Atlantiss/BugTracker#5656]
Dear Gm'm going through the following problem
I can not complete the quest (First Mate Moody) and thus follow in the wake of quest in trying to pick up the items (bottle wisk and the rope) Items not appear to be harvested am thankful since already and waiting for a solution.
Name of my character is Jhonsnow warrior Horde.
http://imgur.com/yjIrDuO
http://imgur.com/6PXFxtZ

**Comment by Luna-maria** [comment]
I suggest fixing the title to meet with the bugtracker requirements :) https://github.com/Atlantiss/BugTracker/blob/master/README.md

also try adding a wowhead/wowwiki/wowpedia/cata.openwow link of the quest. They might close this post without doing anything about it otherwise
