### ISSUE TITLE
[EN][PL][NPC][Elvynn Forest] - Bartlett (flight master of Goldshire)

### ISSUE THREAD

**Issue by shaylopl** [Atlantiss/BugTracker#5657]
Hi, there is some screens that NPC is on the roof in this village
Witam, poniżej załączam screeny pokazujące NPC na dachu budynku w wiosce.
![wowscrnshot_010516_001117](https://cloud.githubusercontent.com/assets/16543840/12103281/39e5864c-b341-11e5-9000-71930199e559.jpg)
![wowscrnshot_010516_001233](https://cloud.githubusercontent.com/assets/16543840/12103280/39e41992-b341-11e5-872e-61fa86459740.jpg)

**Comment by Aviannaqt** [comment]
Linki do npc poprosze

**Comment by shaylopl** [comment]
http://www.wowhead.com/npc=42983/bartlett-the-brave

**Comment by aje** [comment]
checked this morning and he was at the good position
