### ISSUE TITLE
[EN][Pets][Deathknight] Pet - Claw too Big Dmg.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5659]
Claw -> http://cata.openwow.com/spell=47468
Dark Transformation -> http://cata.openwow.com/spell=63560

Naw:
After Dark Transformation, Dmg form DK Pet spell(Claw) do almost 300% Dmg of normal melee attack.

Should be:
After Dark Transformation, Dmg form DK Pet spell(Claw) should do 150% Dmg of normal melee attack.

How it look on ss:
![wowscrnshot_010516_013620](https://cloud.githubusercontent.com/assets/5780624/12104762/ec77693a-b34e-11e5-8d8b-b192eb872b78.jpg)

![wowscrnshot_010516_013623](https://cloud.githubusercontent.com/assets/5780624/12104765/f08e48f4-b34e-11e5-96aa-0ab7c807b0e6.jpg)
Normal Pet Attack average 400 Dmg.
Claw average 962 Dmg. He should hit for 400*1,5=600 Dmg.

Pet Dmg in normal form is ok.
Mayby Dark Transformation Buff work on Claw too and that is The problem.

**Comment by blinkmaster** [comment]
Sweep claws have different formula than normal claw (higher %) and is increased by dt dmg buff. Also, when transformed claw dmg is considered shadow if i am not mistaken, thus penetrating armor and leading to higher overall dmg. I dont have exact numbers but im pretty sure its working fine :d and i am a mage saying this

**Comment by BialyADI** [comment]
No, you are wrong.

Buff already increase Pet Melee atack so claw should do 150% of it.

**Comment by blinkmaster** [comment]
hm ye it does indeed looks like that but dunno if this is correctly or not. maybe some1 will provide some info ^^

**Comment by BialyADI** [comment]
Double-dipping is never correct.

**Comment by Kejmil** [comment]
unless blizzlike :D

**Comment by metaldoctor** [comment]
I think its not bugged because if melee attack of pet deal 400, then 60% damage bonus in transformation and 150% of melee attack it will be 962 like at sceenshot. (400*1.6*1.5 = 962)

**Comment by meowmewo** [comment]
I cant believe you cant do the math....according to you, 400 + 150% is 600..my god.

**Comment by meowmewo** [comment]
Tested and did the math, Conclusion = false report.

**Comment by BialyADI** [comment]
Yes it was repaired 1 year ago. Facepalm ;D.
