### ISSUE TITLE
[EN][Item] Recipe: Captain Rumseys Lager

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#5660]
http://www.wowhead.com/item=34834/recipe-captain-rumseys-lager

I believe that this item has wrong drop chance, yes i know that is >0.9% but i've been doing cooking/fishing quests for whole year and still haven't seen it drop (i got 64 other duplicate recipes with 5 cake recipe drops which is also >0.9%, and a dozen of pets from Crocolisk quest bag) 
Recipe should drop from http://www.wowhead.com/item=67414/bag-of-shiny-things
http://www.wowhead.com/item=44113/small-spice-bag
http://www.wowhead.com/item=34863/bag-of-fishing-treasures
http://www.wowhead.com/item=35348/bag-of-fishing-treasures
http://www.wowhead.com/item=46007/bag-of-fishing-treasures
http://www.wowhead.com/item=33844/barrel-of-fish
http://www.wowhead.com/item=33857/crate-of-meat

**Comment by LaveniaGithub** [comment]
Maybe you're just unlucky?? (= 

Kidding aside, I had to farm this recipe for a damn long time as well, also getting multiple of the other recipes that should be just or almost as rare.
