### ISSUE TITLE
[EN][NPC]Flamewalkers

### ISSUE THREAD

**Issue by Docholiday-Atlantiss** [Atlantiss/BugTracker#5662]
The flame walkers in The Molten flow do not drop loot.
http://www.wowhead.com/npc=53085/flamewaker-sentinel
http://www.wowhead.com/npc=53093/flamewaker-shaman
http://www.wowhead.com/npc=53143/flamewaker-hunter

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11052-5662-loot-tables/
