### ISSUE TITLE
[EN][Spell][Class] Lava Lash

### ISSUE THREAD

**Issue by jendryk** [Atlantiss/BugTracker#5664]
When Lava Lash spreads Flame Shock thanks to Improved Lava Lash talent on nearby enemies, it triggers cooldown on Shock spells.
Lava Lash - http://cata.openwow.com/spell=60103
Shocks:
Flame Shock - http://cata.openwow.com/spell=8050
Earth Shock - http://cata.openwow.com/spell=8042
Frost Shock - http://cata.openwow.com/spell=8056
Improved Lava Lash : 
Rank 1 - http://cata.openwow.com/spell=77700
Rank 2 - http://cata.openwow.com/spell=77701

**Comment by anxanas** [comment]
I just tested it, it does trigger cd, this wasnt the case before

**Comment by jendryk** [comment]
Why is it did you close it?

**Comment by Bastion** [comment]
o co chodzi

**Comment by lamaATS** [comment]
Fixed in rev. 5206
