### ISSUE TITLE
[EN][Item] Demons Deck

### ISSUE THREAD

**Issue by pawazzz** [Atlantiss/BugTracker#5665]
After you make this deck by combining the 5 cards. (http://www.wowhead.com/item=44158/demons-deck)

It should give you a quest (http://www.wowhead.com/quest=13311/demons-deck)

The problem is , when i right-click the item to start the quest, it says " You don't meet the requirements for that quest".

Im level 85, the minimum level needed for the quest is 40.

**Comment by TranceAccount** [comment]
You need inscription in order to take this quest.

**Comment by wtRCH** [comment]
@pawazzz Tell me if you were testing it with inscription or not. I am closing it for now
