### ISSUE TITLE
[En][Warlock][Spell]Metamorphosis

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#5670]
Metamorphosis doesnt snapshot with Mastery.

How this affect our game us warlocks?
Mastery gear swithing doesnt work now (now w/e but later its important dps increase)
Also trinkets like Therarion Mirror can affect our Metamorphosis after we will use our Meta so its a dps increase fro some braindead warlocks cause increase uptime Metamorphosis.

http://www.wowhead.com/spell=103958/metamorphosis

ps. https://github.com/Atlantiss/BugTracker/issues/3389 ;c

**Comment by Bildo** [comment]
duplicate

**Comment by anxanas** [comment]
Is this bug hard to fix?
