### ISSUE TITLE
[PL][NPC][Quest line legendary weapon shadowmourne]

### ISSUE THREAD

**Issue by Noncontrol** [Atlantiss/BugTracker#5673]
Podczas wykonywania questa http://www.wowhead.com/quest=24749/unholy-infusion podczas zmiany w zombie i spozywania śluzu nie otrzymujemy stacków przez co nie możemy naładować broni a nastepnie wycastowac na sobie debuffa potrzebnego do zakonczenia questa

**Comment by Bildo** [comment]
fixed
