### ISSUE TITLE
[PL][Raid][Firelands] Lord Rhyolith 

### ISSUE THREAD

**Issue by Qwers** [Atlantiss/BugTracker#5675]
Jest to dość poważny bug, wpływający dość znacznie na mechanikę bossa, który zauważyłem oglądając filmik: https://www.youtube.com/watch?v=eYqLItSHXEM (kill DA). Sam nie testowałem, więc opieram się tylko o to, co widziałem na filmiku.

## Opis bugu:
Otóż bug polega na tym, że od samego początku encountera można targetować i BIĆ samego bossa. Na filmiku widać, że ludzie biją 3 targety (pomijam addy): 
1 target: Prawa noga bossa
2 target: Lewa noga bossa
3 target: Boss

## Jak powinno działać:
Przez pierwszą fazę "targetowalne" powinny być tylko nogi bossa. Sam boss na globie jest nietargetowalny. 

* Opis z Dungeon Journala:

"Stage One: Nuisances, Nuisances!

Lord Rhyolith ignores players while his armor is intact, but they can attack his feet to control his movement."

HP bossa zbija się poprzez bicie jego nóg (HP bossa jest sharowane z HP jego nóg). Po zbiciu "bossa" do 25% staje się on targetowalny i można go już normalnie bić.

* Opis z Dungeon Journala:

"Stage Two: Now you will BURN!

When Lord Rhyolith reaches 25% remaining health, his Obsidian armor shatters. He becomes attackable and no longer ignores players."

## Podsumowanie:

Boss aż do osiągnięcia 25% HP powinien być nietargetowalny. Targetować powinno być można tylko jego nogi (+ oczywiście addy). Boss powinien byc targetowalny dopiero w fazie drugiej (25% HP).

Mechanika tego bossa polega na właściwym sterowaniu bossem w fazie 1 poprzez zbijanie jednej lub drugiej nogi. Na Atlantissie można tą mechanikę praktycznie obejść, gdyż wystarczy bić samego bossa.

**Comment by Bastion** [comment]
już jest poprawiony
