### ISSUE TITLE
[EN][Warrior] Self Heal

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5677]
Talent Field Dressing: http://cata.openwow.com/spell=84580

Dont work on Warrior Self Heal like:
Enraged Regeneration: http://cata.openwow.com/spell=55694
Blood Craze: http://cata.openwow.com/spell=16492
Second Wind: http://cata.openwow.com/spell=29838

It should increase it by 6% like all Heals and by another 20% as Self Heal.
It is really major bug for Warriors in PvP.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/5401
