### ISSUE TITLE
[EN][Raid]Blackwing Descent-Magmaw

### ISSUE THREAD

**Issue by DontBeSadbro** [Atlantiss/BugTracker#5678]
After Mangle ends on the main tank, the tank is placed under him, into lava.

**Comment by Bastion** [comment]
-dkp & kick tank

**Comment by anxanas** [comment]
Thats cause you do not chain him?

**Comment by Thefakemccoy** [comment]
If he is not chained before mangle end he gets dropped in the lava.

**Comment by Aival94** [comment]
yeah but if boss not get killed after the tank fall it will fly to the room again.
