### ISSUE TITLE
[PL] [QUEST]The embalmer's revenge

### ISSUE THREAD

**Issue by krawath** [Atlantiss/BugTracker#5679]
Jak działa teraz - Gdy zabijemy moba Stitches, on odradza się zaraz po swojej śmierci.
Jak powinno działać - Po zabićiu Stitches, on się nie odradza i idziemy oddać misję.

https://www.youtube.com/watch?v=wOhQxbIAbDo

**Comment by Aviannaqt** [comment]
linki

**Comment by Kejmil** [comment]
tam jest oddzielna faza dla wszystkich graczy co maja tego questa a nie dla kazdego z osobna, wyobraz sobie co by bylo jakby ten mob mial normalny respawn i akurat bylby tlok w duskwood :D

**Comment by krawath** [comment]
wyobraz sobie co by bylo jakby ten mob mial normalny respawn i akurat bylby tlok w duskwood :dancer: 

Lol, a podobno atlantis jest serwerem blizzlike haha
