### ISSUE TITLE
[EN][Battleground][PvP] Portals can be cast in battlegrounds

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#5681]
http://wowwiki.wikia.com/wiki/Portal_(spell)?oldid=2627278
http://wowwiki.wikia.com/wiki/Portal_(spell)?oldid=2413844
Sources say:

_Portals cannot be cast in combat. In addition, portals cannot be cast inside PvP battlegrounds._

but on our server they can be cast while in battleground.
All people who click portal are teleported outside battleground and get deserter debuff

**Comment by Milton3450** [comment]
PLS FIX! Retarded mages are thinking this is funny and ppl click and get ported out of the BG.

**Comment by xmesaj2** [comment]
fixed 5378
