### ISSUE TITLE
[EN][Raid-Cata]Firelands -Shannox

### ISSUE THREAD

**Issue by fafal** [Atlantiss/BugTracker#5682]
Today on some pug i saw weird thing.
We killed dogs and we wipe it then we try it 2nd time shannox was without dogs. 
I talk with some random ppl and something like that wasnt something new.
Also without dogs shannox dont use any skill, only traps.

**Comment by Thefakemccoy** [comment]
Also i had a issue with riplimb running over the prison traps taking the spear back to shannox and not getting trapped. I had to move him to traps and tank him beside themthen move him over top of it  to get them to trigger on him half the time.

**Comment by Frainzil** [comment]
Sometimes the dog get immune for the traps for 20 seconds, though people don't pay attention to that (which is mostly caused by immolation traps). Though indeed there  sometimes is something wrong with hitboxes of the traps.

**Comment by Thefakemccoy** [comment]
I can tank him after he comes back from taking the spear just off from a trap and when he throws the spear i move him to the trap and still wont be trapped. And he does not run over a trap. Unless the traps are clipped in the ground and i can not see them.

**Comment by Aival94** [comment]
For us the dogs just came after some time.About how the traps are working i am not sure as i was not tanking the dog but our tank in the beginning had difficulties as well to trap it even when not go to any traps at all during the couldown of the Hurl Spear ability.

Give some links in case they want them:
[Shannox](http://www.wowhead.com/npc=53691/shannox)
[Riplimb](http://www.wowhead.com/npc=53694/riplimb)
[Rageface](http://www.wowhead.com/npc=53695/rageface)
[Crystal Prison Trap](http://www.wowhead.com/npc=53713/crystal-prison-trap)
[Immolation Trap](http://www.wowhead.com/spell=47784/immolation-trap)

**Comment by anxanas** [comment]
Time to abuse =))))

**Comment by Bildo** [comment]
Time to ban =))))

**Comment by metaldoctor** [comment]
Dogs are gone when you wiped at boss or evade he and dogs are in LoS of boss, Firelands have a lot of space with bugged textures. Dogs love going in textures in some places and stack in it.

**Comment by Quban** [comment]
> Dogs are gone when you wiped at boss or evade he and dogs are in LoS of boss, Firelands have a lot of space with bugged textures. Dogs love going in textures in some places and stack in it.

Ok im appling the fix now :dancer:

**Comment by metaldoctor** [comment]
Dear Quban we have chance for fix textures? Its biggest problem at for Shannox, because we killing he in room where Baleroc stay, but he love stack in one place. If u pulled he when he go close to gate his dogs running in textures (doesnt stack in it), but he stuck and dont come in room where whole raid stay. Its really hard to find place where he will dont stack in textures.

**Comment by Thefakemccoy** [comment]
Trap Issues

Riplimb should be able to get trapped while running the spear back to shannox.
Currently he does not.
On heroic he can not be trapped while running the spear back to shannox.

**Comment by Aldergar** [comment]
New bug that occurred yesterday: the flame vortex created by hurl spear and Magma Rupture were slighly inside the texture.

**Comment by Quban** [comment]
> New bug that occurred yesterday: the flame vortex created by hurl spear and Magma Rupture were slighly inside the texture.

which place it was on map?

**Comment by Aldergar** [comment]
It was on Alysrazor Arena

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/6031
