### ISSUE TITLE
[PL/EN][NPC]Nayura text bug

### ISSUE THREAD

**Issue by dudel02** [Atlantiss/BugTracker#5683]
![wowscrnshot_010616_011009](https://cloud.githubusercontent.com/assets/16526644/12132225/0a22087a-b41a-11e5-9c51-ac485c3ea5d7.jpg)

Na widocznym screenshocie widzimy, że Nayura mówi nam o tym, że statek kursuje między Stormwindem a Auberdine. Jest to oczywiscie nieprawda, gdyż Auberdine zostało zniszczone w Katakliźmie, a statek pływa od tamtego czasu do Teldrassilu.

On attached screenshot, we can see that Nayura tells us that ship sails between Stormwind and Auberdine. That's false of course, because Auberdine has been destroyed in Cataclysm, and the ship sails to Teldrassil since this time.

NPC: http://cata.openwow.com/npc=28650

**Comment by xmesaj2** [comment]
fix: http://community.atlantiss.eu/index.php?/topic/7558-5683-npcstormwind-nayura-text-bug/
