### ISSUE TITLE
[PL/EN][Object]Quest board in The Exodar

### ISSUE THREAD

**Issue by dudel02** [Atlantiss/BugTracker#5684]
Na załączonym screenshocie, zauważyć można, że stoją dwie tablice z questami, gdy wiemy że powinna stać ewidentnie jedna.

On attached screenshot, we can see that there are two boards, when there should be only one.
![wowscrnshot_010316_152905](https://cloud.githubusercontent.com/assets/16526644/12132301/f09bb0ee-b41a-11e5-930b-57bf27d3513a.jpg)

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/3705

BTW seems the extra one to be the one with the westfall quest(and other Eastern Kingdonm zone quests) and should be one of these:
[Hero's Call Board](http://www.wowhead.com/object=206111/heros-call-board)
[Hero's Call Board](http://www.wowhead.com/object=206294/heros-call-board)
