### ISSUE TITLE
[EN][NPC][Firelands Invasion]Dorda'en Nightweaver

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#5688]
This NPC is required for http://www.wowhead.com/achievement=5870/fireside-chat 
but he is missing. He should be avalible for players after completing
http://www.wowhead.com/quest=29201/through-the-gates-of-hell
which is the quest that leads you into Molten Front. He also gives 3 quests 1 random everyday which obviously are missing.

**Comment by Raknar** [comment]
Fixed. Will be spawned later evening
