### ISSUE TITLE
[EN][Quests][Dragonblight][Neltharion's Flame]

### ISSUE THREAD

**Issue by magromo** [Atlantiss/BugTracker#5689]
![wowscrnshot_010616_104424](https://cloud.githubusercontent.com/assets/13817775/12139721/8fff9906-b462-11e5-850b-3833bf4f8e82.jpg)
There should be enemy npc. 
https://www.youtube.com/watch?v=qHDb9-rx92o

**Comment by Aviannaqt** [comment]
read bt rules
