### ISSUE TITLE
[PL]Warrior 2p t12 dps bonus

### ISSUE THREAD

**Issue by Kepasax** [Atlantiss/BugTracker#5691]
Buff z bonusu za 2 czesci trwa 6sek a powinien 12. 
6 sek powinien trwac gry warrior ma rozdane 2 pkt w talent Booming voice i analogicznie 9 sek gdy ma rozdany 1 pkt i 12 gdy ma 0.

http://www.wowhead.com/spell=99234/item-warrior-t12-dps-2p-bonus#comments:id=1462021

**Comment by Kepasax** [comment]
Dzialalo poprawnie do dzis wieczorem. Po dc sie zepsulo.

**Comment by Nc94** [comment]
https://github.com/Atlantiss/BugTracker/issues/5981

**Comment by Bildo** [comment]
quban popsuł xd
