### ISSUE TITLE
[EN][Achievement]Exploring Bug - Northern Stranglethorn

### ISSUE THREAD

**Issue by ferstorm** [Atlantiss/BugTracker#5693]
I already explore all the map of Northern Stranglethorn but i havent got the archivement for it, please help me fixing this bug.

Character name: Kotto

Screenshots:
![archivement window](https://cloud.githubusercontent.com/assets/16574638/12140834/7de0c09c-b430-11e5-964c-556d62252023.png)
![map bug](https://cloud.githubusercontent.com/assets/16574638/12140833/7dd9904c-b430-11e5-8a48-78da7d686228.png)

**Comment by Aviannaqt** [comment]
rev. 4856
