### ISSUE TITLE
[EN][Raid][Ragnaros][Spell]Blazing heat following pet

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5695]
http://www.wowhead.com/spell=100460/blazing-heat
Blazing heat seems bugged for hunters, if a pet runs through a blazing heat spawned by someone(i think this is what happens) it will follow the pet attached to it like a magnet even through phase 3, its like the flame does /follow on the pet. This has happened twice both when i was on hunter and when i was on another class seeing this on another hunters pet. The fire does damage, no idea if it heals fire scions and elementals, i didnt want to test it in raid =))

**Comment by Frainzil** [comment]
I can comfirm this bug, the fire was acting like it was a mob following a pet arround the room.
