### ISSUE TITLE
[EN][Raid][Ragnaros][Spell] Damage from sulfuras smash

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5696]
http://www.wowhead.com/spell=98710/sulfuras-smash
When you stand infront of the place sulfuras smash hits, u take damage from an unknown source, the damage is insignificant(1 damage), but the damage is very rapid and it causes pushback. I was not able to track this damage on recount.

**Comment by Kejmil** [comment]
those are triggers using melee against you :P

**Comment by anxanas** [comment]
Triggers?
