### ISSUE TITLE
[EN][Quest] This can only mean one thing...

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#570]
In the quest **This can only mean one thing...** (http://www.wowhead.com/quest=28732), when you use **Finkle's Mole Machine** (http://www.wowhead.com/npc=49456) and arrive in front of **Blackrock Caverns** dungeon entrance, you don't get the count for the quest, so it can't be completed.

This quest leads to another quest inside the dungeon itself, so it's kinda important.

**Comment by Cassedy** [comment]
I can confirm this bug.

**Comment by Aurelia1993** [comment]
Still bugged from what I can tell.

**Comment by Articuno** [comment]
I confirm, still bugged.

**Comment by Aival94** [comment]
Quest is working just fine if you use the mole.Did it before some mins,

Proof: 
![wowscrnshot_113015_035243](https://cloud.githubusercontent.com/assets/10282971/11461983/eb43e50c-9715-11e5-8e74-d82e9422d0bf.jpg)
