### ISSUE TITLE
[EN][Quest][Molten Front] Dailies at Sethria's Roost

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5701]
Relieving the Pain http://www.wowhead.com/quest=29246/relieving-the-pain 
http://www.wowhead.com/item=69678 
various comments suggest that this should have a 100% droprate. Officially it should also drop it for ppl that weren't the first to tag the mob but idk if that's even possible to do on a private server. At the very least it'd be nice to see this drop 100% of the time

Treating the Wounds http://www.wowhead.com/quest=29247/treating-the-wounds#comments 
http://www.wowhead.com/item=69677/sulfur-laced-wrapping 
same issue as relieving the pain
The percentages mentioned on wowhead are lower because people kill these elites before getting these 2 quests and don't get the item while killing it then. 

The Protectors of Hyjal http://www.wowhead.com/quest=29128/the-protectors-of-hyjal
quest works fine but the respawn time on the giants and elementals should be faster, especially since everyone and their mother is camping them because the droprates aren't 100% right now
http://www.wowhead.com/npc=52289/fiery-behemoth
http://www.wowhead.com/npc=52300/seething-pyrelord

**Comment by phifedawg** [comment]
I don't see anywhere on the comments a suggestion of the droprate being 100%.. Could you quote something?

**Comment by Navedonar** [comment]
http://us.battle.net/wow/en/item/69678#tab=dropCreatures
http://us.battle.net/wow/en/item/69677#tab=dropCreatures

**Comment by Luna-maria** [comment]
what navedonar said and also comments saying that you only need to tag the mobs even if you're not doing 51% damage, you should get the item to drop. That suggest that no matter what you do, as long as you attack it once, you should get them to drop :) 

"By Aislinana (6,213 – 1·12·78) on 2011/07/02 (Patch 4.2.0)		
It should be noted that anyone who has contributed to the death of the Seething Pyrelord will have loot rights to the  Flame-Wreathed Heart. So if you are killing Pyrelords for the quest, make sure you snatch up your quest items or quest in a more isolated area of Sethria's Roost."

**Comment by Luna-maria** [comment]
:/ it's such an easy fix

DELETE FROM `creature_loot_template` WHERE (`entry`=52289);
INSERT INTO `creature_loot_template` VALUES 
(52289, 69677, -100, 1, 1, 1, 1);

DELETE FROM `creature_loot_template` WHERE (`entry`=52300);
INSERT INTO `creature_loot_template` VALUES 
(52300, 69678, -100, 1, 1, 1, 1);

I get that there's other loot set there now but I don't know what but... whatever other loot is already there, just copy paste this in there as well
pretty please? :)

**Comment by Navedonar** [comment]
http://community.atlantiss.eu/index.php?/topic/7785-relieving-the-paintreating-the-wounds/

**Comment by Luna-maria** [comment]
ah, that works too, sorry. I don't generally brows the forums
