### ISSUE TITLE
[EN][NPC][Molten Front]Commander Jarod Shadowsong(ID 52134)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5707]
NPC should be spawned in Molten Front after you have completed quest [Twilight Riot](http://www.wowhead.com/quest=25531/twilight-riot) and quest [Through the Gates of Hell](http://www.wowhead.com/quest=29201/through-the-gates-of-hell).
For me he was spawned after i completed quest [Druids of the Talon](http://www.wowhead.com/quest=29181/druids-of-the-talon)

Wowhead Link: [Commander Jarod Shadowsong](http://www.wowhead.com/npc=52134/commander-jarod-shadowsong)

**Comment by Raknar** [comment]
fixed
