### ISSUE TITLE
[EN] [Priest] - Shadowform Bug

### ISSUE THREAD

**Issue by annnnnnnn** [Atlantiss/BugTracker#5710]
https://www.youtube.com/watch?v=j5C4b4h13UE

I can't tell the exact reason why is this happening, but I guess spamming abilities too quick causes it; only relog helps

**Comment by anxanas** [comment]
This was supposed to be fixed in rev 4755

**Comment by RandomPickNewb** [comment]
Shadowform cooldown SHOULD no longer bug, as in it is supposed to bug a lot less often.The only way to avoid it is to never spam your Shadowform.
Also try this Jenova:"All players that have problems with some spell cooldowns bugging (example Shadowform, Tricks of the trade)! Please enter "interface/combat" and set Custom Lag Tolerance to 0! "
It will help a bit but not completely solve the problem
