### ISSUE TITLE
[En][Item]Cloth Head "Flickering Cowl" from Lord Rhyolith dont have Random Enchant.

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#5711]
When you loot Flickering Cowl http://www.wowhead.com/item=71011/flickering-cowl from   Lord Rhyolith http://www.wowhead.com/npc=52558/lord-rhyolith dont give Random Enchants.
![wowscrnshot_010616_202101](https://cloud.githubusercontent.com/assets/15231821/12150706/f1bca30e-b4b3-11e5-8360-179ea2858824.jpg)

**Comment by Bastion** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/1584564/12151995/41aaf3c2-b4b2-11e5-802e-44b3e6470029.png)

??

**Comment by Kejmil** [comment]
such strength, still not bis :<

**Comment by Bildo** [comment]
duplicate
