### ISSUE TITLE
[EN][ITEM] Alysra's Razor

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#5712]
Rogue was in the air and finished Alysrazor. Because of the DC I forgot to change loot so it stayed Group Loot and we had some troubles. I'll just post a screenshot, it speaks for itself.

![bug](https://cloud.githubusercontent.com/assets/13660744/12151828/54c71fcc-b4b1-11e5-8c9c-1c1be3a0985e.jpg)

**Comment by Aival94** [comment]
This should probably be closed as is not even a bug.
