### ISSUE TITLE
[PL] Warlock  movement PETS

### ISSUE THREAD

**Issue by krawath** [Atlantiss/BugTracker#5717]
Obecnie poruszanie się petów działa tragicznie. Chodzą pod teksturami, gubią się, przestają atakować lub nie mogą dobiec do celu na równej powieszchni. Oczy porostu bolo jak na to się patrzy. W najbliższym czasie nagram filmik jak to wygląda, niezła komedia poprostu.

**Comment by blinkmaster** [comment]
tak samo pety innych klas.

**Comment by Aviannaqt** [comment]
#5714
