### ISSUE TITLE
[EN][Spell][Shaman] Bugged Earthshield

### ISSUE THREAD

**Issue by Pacogt** [Atlantiss/BugTracker#5718]
Earth Shield is not stacking with Spell Power.
At this momment earth shield heals kind of 1985-2204 whenever you have spell power or not.
Earth shield should have 2142 (without talent nature blessing) and 2252 (with that talent) base heal
and should stack with spellpower in 0.1949 (Without talent) 0,2066 (with talent) per one spellpower point. 
So with about 7.5k spellpower is should tick for 3.7k.

**Comment by Jenovas** [comment]
Earth Shield Base Heal Should be - 1416
Atleast that is what the DBC says

**Comment by Jenovas** [comment]
Fixed in rev 4794
