### ISSUE TITLE
[PL][Talent][Deathknight] Mastery(Blood Shield) Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5719]
Masterka DK(Blood Shield): http://cata.openwow.com/spell=77535

Jak jest:
Mam np. mam 50% mastery, czyli lecząc się z Death Strike za 10k HP dostane 5k tarczy.
ale gdy mam redukcje heala 25% i uleczę sie za 7,5k to nadal dostane 5k tarczy.

Masterka DK Blood powinna leczyć dany procent od uleczonego HP z Death Strike.
Czyli w tym przypadku mając redukcje Heala i lecząc się z Death Strike za 7,5k powinienem dostać 7500*50%=3,75k tarczy.

**Comment by Kejmil** [comment]
tak jest blizzlike
ale mozesz poszukac dowodow ktore nie istnieja jak mi nie wierzysz :D

**Comment by aneq** [comment]
nie
absorb nie bierze pod uwage modyfikatorow healing done. niewazne czy dodatnich czy ujemnych
