### ISSUE TITLE
[EN][Core] Need before greed loot system

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#5721]
http://us.battle.net/wow/en/blog/2993743/rage-of-the-firelands-patch-42-notes-%5Bupdated-628%5D-6-28-2011

_If a player wins a Need roll under the Need Before Greed system on a Bind on Equip item, the item will become Soulbound to that player. The item will remain unbound if won via a Greed roll._

Need before greed is used by default in dungeon finder groups, people are rolling Need on items they can sell but don't really need except for sale without any consequences.

**Comment by Crusaderz** [comment]
https://github.com/Atlantiss/BugTracker/issues/4477
Duplicate
