### ISSUE TITLE
[EN][Quest][Daily][Molten Front] Into the Fire

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5722]
The daily quest version of the quest "Into the Fire" doesn't work. When you take the quest the event doesn't trigger.

**Comment by Glare** [comment]
Link quest: http://www.wowhead.com/quest=29206

It locks recently unlocked daily quests from Druids of the Talon preventing from futher expansion of Molten Front and slowing down the path of unlocking other factions.

I would call it a high prio because it hurts demo locks the most. /s

**Comment by LaveniaGithub** [comment]
Hmm, managed to do it just now. I think another guy triggered the event and I followed by.

**Comment by Luna-maria** [comment]
#5661
