### ISSUE TITLE
Shadow orbs proc

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#5726]
shadow priest has been my main for 3 years now and when i joined Atlantiss i noticed that there are certain periods where i have shadow word pain and use up to 3-5 mind flays to get only 1 orb, i think there might be a bug with the generation of the shadow orbs, it should be a 24% chance with the correct talents but they spawn so rarely

**Comment by anxanas** [comment]
Read BT rules https://github.com/Atlantiss/BugTracker/blob/master/README.md or your topic will be closed
