### ISSUE TITLE
[EN][Quest][Molten Front][Shadow Wardens]The Forlorn Spire

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5727]
This quest is still bugged, now the npcs that are there isnt even there, and the boss doesnt spawn,
The original topic was closed https://github.com/Atlantiss/BugTracker/issues/5694

**Comment by Sayris9876** [comment]
Confirmed... Yesterday morning when I opened the Wardens i was able to do this quest but today thats not the case.

**Comment by anxanas** [comment]
Seems like if you want to complete this quest again(as a daily) friendly npcs doesnt spawn and u cant do quest

**Comment by ponpontos** [comment]
This is pissing me off quite a bit, I planned on making money from selling the BS weapons as soon as I could buy them, did every single daily religiously and then this happens... huge setback.

**Comment by Raknar** [comment]
From build 4787 situation should be stable

**Comment by anxanas** [comment]
I heard from guildies that it works now, but respawn time is still way too long

**Comment by anxanas** [comment]
Bugged again today, seems like we are phased wrong when we take quest. A restart/crash might fix

**Comment by Aival94** [comment]
I did the quest for first time after completing the druid chain and i can see the npc but event is not starting.

**Comment by anxanas** [comment]
After crash it works again

**Comment by eryczek1615** [comment]
When i ended this quest[Deldren Ravenelm](http://www.wowhead.com/npc=52921)  dosen't appear.
And there should be a few [Hyjal Druid](http://www.wowhead.com/npc=52501) and [Anren Shadowseeker](http://www.wowhead.com/npc=52478) and [Tholo](http://www.wowhead.com/npc=52477) and [Shadow Warden](http://www.wowhead.com/npc=53449)

http://i.imgur.com/ecsT6Ts.jpg
http://i.imgur.com/GR8Gq76.jpg

**Comment by tnarf** [comment]
I think it can be becous one optimalization method.
If im not mistaken, server do nothing with NPC not seen by anyone.
So mayby after phase change no one see this NPCs and server cut their reset
Like after changing difficulty after wipe before boss respawn

[pl]
Jeżeli serwer nie przelicza nie widzianych przez graczy npców (a o ile się nie mylę tak jest)
to może przy zmianie fazy gracze przestają widzieć te npce, przez co serwer przestaje je przeliczać i blokuje reset
Tak jak przy zmianie trybu rajdu po wipie zanim reśnie się bos.

**Comment by ponpontos** [comment]
For the love of God and all that is Holy, if it wasn't for these stupid bugs I think I'd have the first vendor unlocked already.

There are close to 20 players waiting at Forlorn Spire for a respawn. 
![wowscrnshot_011416_162002](https://cloud.githubusercontent.com/assets/16211262/12330416/ebea9b00-badc-11e5-87da-1a5f155a8cb6.jpg)

**Comment by Dziara** [comment]
Bump!

**Comment by tomatosz** [comment]
Bump...

**Comment by Damfee** [comment]
Bump. As far as questing goes on this server, this should be number 1 priority, except for maybe Tipping the Balance in Uldum. Sadly, the thread is 9 months old :(

**Comment by karolnpc** [comment]
Bump

**Comment by Othentik** [comment]
Hi, still bugged

Thanks

**Comment by krecik88** [comment]
should be fixed in 5267
