### ISSUE TITLE
[EN][PL][Mechanic?][Instances mobs]

### ISSUE THREAD

**Issue by shaylopl** [Atlantiss/BugTracker#5730]
Hi, i wanna ask is that a bug ? I mean all mages/wizard (just mobs who castings spells only) dont follow the tank ? Why i asking that ? I think its a bug, because i playing on Sunwell much times, and on Blizzard servers and those mobs follow us when we go pull all of them and just hide behind the wall, after that action they will just go to us for easy stack them for AOE.
Sory for bad eng.

Witam, chciałbym zapytać czy to jest bug ? Mam tu na myśli że wszyscy magowie (mobki które po prostu rzucają zaklęcia cały czas) nie gonią za tankiem. Dlaczego o to właśnie pytam ? Ponieważ grałem dużo na Sunwellu i na serwerach Blizzarda i ci wszyscy magowie normalnie podążali za tankiem, a dokładniej mówiąc jak się np. pullneło jakąś grupę i się chciało wszystkich zebrać w kupę pod AOE to wystarczyło ukryć się za ścianą i z automatu wszyscy przybiegali do nas, na waszym serwerze magowie stoją w miejscach jak słupy soli.

Sorry if its not Mechanic problem (i dont know which define to report)
Przepraszam jeśli to nie problem "mechanik" (nie wiedziałem jak zdefiniować ten problem).

**Comment by Wolffenstein** [comment]
To nie bug w core, to kwestia indywidualna danego moba.
