### ISSUE TITLE
[en][druid] cancelform

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#5731]
currently /cancelform doesn't work if you're on global cooldown

it should work

**Comment by fizzle7** [comment]
Seriously, fix this shit. Don't just leave it for 2 years from now cause this is mandatory for druids. With this bug right now, basically druid is disabled from pvp.

**Comment by Kejmil** [comment]
yeah, that is why druid is in both r1 teams for now xD

**Comment by fizzle7** [comment]
Lol, being in r1 teams doesn't mean anything, there are too many variables to consider such as dodging, queuing times, teams played against, etc. Yes, disc/feral is really strong, but getting feared or hibernated because you were on gcd is absolutely game breaking.

**Comment by phifedawg** [comment]
i totally agree with fizzle7
