### ISSUE TITLE
[EN][Spell][Warlock]

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#5733]
Soul Harvest http://cata.openwow.com/spell=79268
Health funnel http://www.wowhead.com/spell=755/health-funnel

Cloak enchant, weapon enchant and all trinkets procc from channeling health funnel and soul harvest.
It's not supposed to do that.

Casting Shadow Ward cancels Metamorphosis form for some stupid reason. It's not supposed to do that either.

Also any spell i..e Frostbolt hits said warlock with Nether Ward up and it does more damage than the ward can actually absorb, it wont procc nether protection (destro talent, gamebreaking!!)

Moreover when a priest is casting mind control and your insta howl of terror, spell lock, fear, death coil or shadowfury (basically any spell that should interrupt the priest) the priest will evade the spell instead of getting interrupted. I think it has something to do with the fact that the casting warlock becomes friendly with the priest if cast at the end of mind control. But it's still really annoying to eat a full mind control & waste an important cooldown on that..

Also nether protection doesnt work with voidwalkers sacrifice or any other spells i.e. priest shield/engineering belt enchant

Apologizes in advance if I reported it wrong. I'll gladly change it <3

**Comment by anxanas** [comment]
"Cloak enchant, weapon enchant and all trinkets procc from channeling health funnel and soul harvest.
It's not supposed to do that." Its supposed to be like that you are healing with those spells so you proc them with certain trinket procs cloak enchant and weapon enchant

"Cloak enchant, weapon enchant and all trinkets procc from channeling health funnel and soul harvest.
It's not supposed to do that." already reported

**Comment by Fearyourself** [comment]
What about the rest that I reported?

**Comment by Jenovas** [comment]
1 issue = 1 bug

**Comment by kadi2** [comment]
Whenever you'll gonna correct your issue, you can add Helfire to the spell list that shouldn't proc enchants/trinkets

**Comment by Fearyourself** [comment]
You'll have to report it on a new thread since "1 issue = 1 bug" or whatever... Lol.
