### ISSUE TITLE
[EN][RO] Exploration bug Azuremyst Isle, please help!!!

### ISSUE THREAD

**Issue by hehepwnd39** [Atlantiss/BugTracker#5736]
Hey , my name is Derogg lv 15 Hunter Dranei , the Bristlelimb Village is still unexplored on my map and achievement list even though i walked in it many times.When i had the mission to save those 9 furbolgs it showed to me the new location but not on the map ...is like i never walked in it. Please help me!

http://i.imgur.com/mJgGXGG.jpg

**Comment by Luna-maria** [comment]
#5576

**Comment by hehepwnd39** [comment]
so what should i do?
