### ISSUE TITLE
[PL]Death Knight Scourge Strike critical chance

### ISSUE THREAD

**Issue by Kepasax** [Atlantiss/BugTracker#5739]
Jest problem z szansa na trafienie krytyczne Scourge Strike i prawdopodobnie takze Festering Strike, chodz w przypadku tego drugiego nie jestem pewny. Zamieszczam kilka screenow ze statystykami z 2 bossow i testu na kukle. Wartosci crita znajdujacego sie w panelu postaci a tego w recouncie nijak sie maja do siebie (o wiele za malo uderzen krytycznych, nawet uwzgledniajac -crit poprzez roznice lvli boss-gracz)

https://imgur.com/a/3tCy9

**Comment by Aviannaqt** [comment]
rng atlantiss

**Comment by Jenovas** [comment]
Recount wlicza shadow DMG z Scourge Strike jako zwykły Scourge Strike a ten z shadow DMG nigdy nie crita. Stąd takie wartości.

**Comment by Kepasax** [comment]
na kukle bilem bez diseasow = brak jakiegokolwiek shadow dmg(scourge strike bije shadow dmgem tylko jesli mam zaaplikowane doty), czysto fizyczne, poza tym na recouncie z bosa widac wyraznie ze oddziela shadow dmg od fizycznego

**Comment by Jenovas** [comment]
Wydawało mi się że wszystkie SSy są z bossów. Przepraszam.

**Comment by Roderic12** [comment]
Warto wrzucić logi z globala dla porównania http://www.worldoflogs.com/reports/eqal3tkanmy347k3/details/4/?s=2731&e=3075
Warto także przypomnieć , że content FL na globie to dla dk unholy mastery > crit :)

**Comment by Kepasax** [comment]
Dzis znow zrobilem 4 testy po okolo 150 scourge strike, moja szansa na cryta wynosila 10%. W 2 przypadkach scourge strike crytowal w okolo 15%, raz 9% raz 8%. Natomiast festering strike na 30 uderzen potrafil crytowac 5 razy, a czasami w ogole. Jest to dosyc dziwne bo im wieksza proba tym wynik powinien oscylowac w granicach posiadanych statystyk, a tym bardziej dziwne jezeli popadamy ze skrajnosci w skrajnosc i na bosie kukle(baleroc, doslowna kukła) ze wszystkimi aurami, odpalkami i buffami robie tyle samo dpsu co na kukle w Ebon Hold bez zadnych raidowych aur i odpalek (proby 5minutowe).

**Comment by Kejmil** [comment]
crit supression + atlantiss rng jak dla mnie
tak jak w simcrafcie cie ostrzegaja - minimum 1k symulacji zeby dps zmierzyc, minimum 10k zeby wagi statow w miare sie zgadzaly. Mniej symulacji i lucky/unlucky RNG bedzie wazniejsze

**Comment by Jenovas** [comment]
Zrobiłem dzisiaj test DKsem który ma 23% na crita. Na 1200 SS 21.5% z nich było critem.
Tak więc zamykam.
