### ISSUE TITLE
[EN][Quest][Legendary] On a wing and a prayer

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#5740]
upon accepting the quest, there should be an animation and a object (http://www.wowhead.com/object=208430/timeless-eye) should spawn with a quest item (http://www.wowhead.com/item=69238/timeless-eye#comments) lootable from it. Upon entering coldarra zone with this item a cut scene should play, and the player should be teleported to a npc (http://www.wowhead.com/npc=52835/tarecgosa)
It doesn't work and I assume further quests don't work as well

**Comment by LaveniaGithub** [comment]
So, high priority, but any news?

**Comment by Bastion** [comment]
no staff here

**Comment by adryjan** [comment]
''We couldn't give away the Firelands raid for everyday use without the legendary quest chain with a great reward, namely the Tarecgosa's Rest. Despite the fact that it'll take you a long time and effort to  attain this staff, we're sure that you'll have a lot of fun completing these quests.'' - News from website. 

Im quessing that ''Despite the fact that it'll take you a long time'' is more important than rest of this news.

Guys please it's freakin race for this staff. We dont want to waste ID's. 
We have lot of stuff to get from FL.

**Comment by LaveniaGithub** [comment]
Not much of a race it seems. 3rd guy from our guild from core runs is gathering his embers now, while the two first of us sits with 25 Both waiting for next gathering part

**Comment by fafal** [comment]
Lavenia +1

**Comment by Kejmil** [comment]
<b>"it'll take you a long time and effort to attain this staff"</b>
especially without sniffs ( ͡° ͜ʖ ͡°)

**Comment by aneq** [comment]
yep, If not for this bug, we would be halfway through stage2 already.

**Comment by LaveniaGithub** [comment]
Same (=, sad though

**Comment by adryjan** [comment]
bump bump bump

**Comment by LaveniaGithub** [comment]
4th guy from main group is now gathering embers. Still not possible to progress further :/

**Comment by linesar** [comment]
https://www.youtube.com/watch?v=eZmVxQkCNp4 might help some

**Comment by BAndysc** [comment]
Have anyone completed the chain on retail? Should player be teleported automatically to Coldarra or one has to go there on foot?

**Comment by LaveniaGithub** [comment]
You should fly there manually, but when entering Coldora a with the item a cutscene should appear

**Comment by LaveniaGithub** [comment]
https://youtu.be/eZmVxQkCNp4?t=6m36s

**Comment by Assiria** [comment]
Bump, bumpozord

**Comment by Illusionist87** [comment]
Any news about this?

**Comment by Walniety** [comment]
preety funny right now 3 ppl that i know have all embers :D and right now me 2 :D and this video that linesar send show whole chain quest how to do it -_- u culde at least let this be auto complete -_-

**Comment by BAndysc** [comment]
> -- u culde at least let this be auto complete --

It is against our rules. We are currently collecting items on retail, we cannot script the quest without it.

**Comment by ocbald** [comment]
Bump

**Comment by LaveniaGithub** [comment]
They know about it, no need for any more bumps.

**Comment by Illusionist87** [comment]
Four people in my guild are already  on this quest, and are stuck here.
Can we, at least, get an update on this?

**Comment by captjvmoore** [comment]
I think they label the high priority threads with another marker that rates the difficulty of completion and they start fixing stuff from the easiest to the hardest, in order to get more bugs fixed for the same time spent, at least that's how I do it at work. If that's true, don't expect a fix within the next week or two.

**Comment by LaveniaGithub** [comment]
Regardless of that I wouldn't expect a fix within multilple months. And it has been months already.

**Comment by BAndysc** [comment]
We are waiting for the special application "TrinityCore Packet Parser" to be updated

**Comment by LaveniaGithub** [comment]
Yea I know. That's why it will take extra time to gather the needed sniffs.

**Comment by captjvmoore** [comment]
Got bored, so :D
![image](https://cloud.githubusercontent.com/assets/9639063/13726488/c57894ae-e8d1-11e5-9e41-13fe66c6aff7.png)

**Comment by LaveniaGithub** [comment]
Any news? :s

**Comment by aneq** [comment]
doubtful

**Comment by linesar** [comment]
yeah, it would be cool with some news regarding this. But i dont think that we will see this working before FL heroic.

**Comment by Kaspi92** [comment]
Any news about this quest?
The following quests need alot of farming in FL, it would be nice to fix the questlin until 
[Time Grows Short](http://cata.openwow.com/quest=29270) atleast.

**Comment by BAndysc** [comment]
> Any news about this quest?
Yes, I am working on it.

**Comment by LaveniaGithub** [comment]
Out of curiosity: Have the sniffs also been collected for the later stages of the chain quest?

**Comment by Bildo** [comment]
Yes, we have sniffs for whole chain

**Comment by Kaspi92** [comment]
> Yes, I am working on it. (Fun fact: yesterday I have spent 7 hours in the evening to script 90 seconds of the quest in Nexus)

That sounds awesome, I can't wait for the progress and thanks alot for working on it, I know it takes alot of effort and time.

**Comment by Torquu** [comment]
Any news, any progress? last info was a month ago

**Comment by LaveniaGithub** [comment]
Close?
