### ISSUE TITLE
Field Repair Bot 74A recipe

### ISSUE THREAD

**Issue by chlebmati** [Atlantiss/BugTracker#5741]
hi, i've a big problem. i think that this recipe for Field Repair Bot 74A doesn't work. I was at the blackrock upper city dungeon, i found that recipe lying on the grount where it should be, but i wasn't able to pick it up. please help and fix it. thx a lot

**Comment by monibu** [comment]
You don't pick it up, you click it and when your engi skill is high enough you'll learn it.

Read BT rules - no links provided, so it'll be probably closed
(and when adding links, do it by editing original post, not by adding a comment)

**Comment by chlebmati** [comment]
hmm, ok, thank you for your help and sorry for my ignorance :P
