### ISSUE TITLE
[PL][Item set][Paladin]  t12 holy 2p bonus

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#5742]
Bonus za 2 części holy pala nie działa.
http://www.wowhead.com/spell=99067/item-paladin-t12-holy-2p-bonus
Żaden holy shock nie powodował proca (faktyczny heal i overheal).

**Comment by Reversion** [comment]
Użyj z 10 -20 shockow i wklej ss z widocznym combat logiem.

**Comment by Lenox07** [comment]
![wowscrnshot_010816_144111](https://cloud.githubusercontent.com/assets/9517740/12199120/108e8154-b616-11e5-8773-10c761971d94.jpg)

**Comment by Jenovas** [comment]
Fixed in rev 4792
