### ISSUE TITLE
[EN][Item] Matrix Restabilizer

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#5743]
I recently got the trinket, but it never procs, i tried it on a dummy for 8-10 min and in pvp w/o getting a single proc

http://www.wowhead.com/item=68994/matrix-restabilizer

**Comment by Bastion** [comment]
thx for report, i don't spend my gp for this :D

**Comment by Jenovas** [comment]
Fixed in rev 4789

**Comment by Kejmil** [comment]
faworyzacja agilitowcow :<

**Comment by LaveniaGithub** [comment]
You can now safely spend your GP for it, Bastion (=
