### ISSUE TITLE
[EN][Quest][Stormwind][Orgrimmar] The Call of the World-Shaman

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#5744]
This quest should be available to all 85s after 4.2 patch.
http://www.wowhead.com/quest=29439/the-call-of-the-world-shaman#comments

*Start of a quest chain added in 4.2 which eventually ends with Elemental Bonds: The Vow.*

*The quest chain rewards you with a choice of four cloaks:*
*Mantle of Doubt*
*Mantle of Desire*
*Mantle of Patience*
*Mantle of Fury*

**Comment by Luna-maria** [comment]
I remember gms/devs saying this questline wasn't finished yet so not available
