### ISSUE TITLE
[PL][Firelands][Ragnaros] Lava Bolt

### ISSUE THREAD

**Issue by Kepasax** [Atlantiss/BugTracker#5749]
Na fazie przejsciowej gdy Ragnaros bije Lava Boltami w 10 losowych graczy (25man) u nas wypuszcza 20 Lava Boltow za jednym razem (powinien tylko 10-po jednym na gracza) i wiekszosc Lava Boltow z tych 20 wypuszczonych trafia ten sam cel 2 razy. Jest to czesto bardzo trudne do odleczenia i jest to ewidentny bug. 

Dla porownania logi z globa: http://www.worldoflogs.com/reports/xd6wilq56ps2vxaq/log/?s=3991&e=4438

logi z naszej walki: http://www.worldoflogs.com/reports/uw85e4tmqu4j48w7/log/?s=6177&e=6852

(w oknie Query builder klikamy remove, pozniej Add Query-> w miejscu spell wpisujemy Lava Bolt-> Save -> Run)

Na naszych logach widac takze ze Lava Bolty trafiaja w pety i summony co tez nie powinno miec miejsca.

**Comment by Thefakemccoy** [comment]
Sulfuras smash is not really random it 99% time hits behind the tank.
http://www.wowhead.com/spell=98710/sulfuras-smash

The tip on wowhead versus the one in the journal are a little different.

Journal: Rag faces a location of a random players and prepares to smash sulfuras on the platform.

**Comment by Aival94** [comment]
The lava bolt seems to still continue hit twice the targets in all the raid versions sometimes(Both 10 and 25).
