### ISSUE TITLE
[EN][PvP][NPC] Blood Guard Zar'shi (Total honor gained issue)

### ISSUE THREAD

**Issue by Peepsqueak** [Atlantiss/BugTracker#5750]
Apparently we still have issue with total honor show even if we collected around 7.2k+ honor.:

![wowscrnshot_010816_144701](https://cloud.githubusercontent.com/assets/16557304/12198288/42277eea-b617-11e5-9a9d-512c000ea936.jpg)

Clearing cache, wtf, interface or relog wont help.

**Comment by Aviannaqt** [comment]
Yes, its visual bug connected with #5578
