### ISSUE TITLE
 [EN][Achievement]Explore Uldum 

### ISSUE THREAD

**Issue by c0rac0ideus** [Atlantiss/BugTracker#5752]
The Achievement Explore Uldum didn't work for me. I flew several times over the last region that was missing for the achievement, but it didn't seem to recognise the zone. I tried relogging, running instead of flying and flying across all that certain patch of the map.
![wowscrnshot_010816_141229](https://cloud.githubusercontent.com/assets/16610008/12198649/70159648-b612-11e5-9263-ca5baa4cc44b.jpeg)

**Comment by Aviannaqt** [comment]
Its global bug with explore.
