### ISSUE TITLE
[EN][Achievement][Molten Front] And the Meek Shall Inherit Kalimdor

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5753]
After completing the daily quest "Those Bears Up There", I wasn't given the credit of Hyjal Bear Cup in the achievement "And the Meek Shall Inherit Kalimdor. A guildie had the same problem as me, however though, someone else from my guild managed to get the achievement. So it isn't always giving credit for doing the quest.

**Comment by Wolffenstein** [comment]
It's not awarded for completing the quest...

**Comment by Bastion** [comment]
![image](https://cloud.githubusercontent.com/assets/1584564/12200538/ade10428-b61f-11e5-92ff-681c7067b886.png)

??
