### ISSUE TITLE
[PL][Achievement][Molten Front] And the Meek Shall Inherit Kalimdor

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5755]
http://www.wowhead.com/achievement=5868
Po ukończeniu q nie otrzymałem tego osiągnięcia

http://i.imgur.com/NA31p1I.jpg
Wykonałem http://www.wowhead.com/quest=29161 i  http://www.wowhead.com/quest=29162

**Comment by Wolffenstein** [comment]
Ten achievement nie polega na kończeniu questów tylko na wykonaniu pewnych akcji...
