### ISSUE TITLE
[PL][Molten Front] Graveyard

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#5756]
http://i.imgur.com/Ye03K5h.jpg?1

W miejscu na screenie nie ma ducha na cmentarzu a wskoczenie na wyspę po skałach jest w zasadzie niemożliwe przy gildyjnym przyspieszeniu z perka. W zasadzie to w duchu się nie da po tych skałach skakać ;d

Unstuck na stronie pomaga ale to chyba nie jest najlepsze rozwiązanie tego problemu.

Generalnie na wyspie jest graveyard ale niestety nie obejmuje on jej całej.

**Comment by Bildo** [comment]
fixed
