### ISSUE TITLE
[EN][BG&Arenas] Tol Barad Queue

### ISSUE THREAD

**Issue by chibiske** [Atlantiss/BugTracker#5758]
Me and few other people have recently ran into a weird and quite shitty bug.

Not matter how soon or how late I queue for TB battle, while my friend queues at 1 minute before the bg starts and gets in. This has been going on for like a week I haven't been able to do any tol barad battles. Before you say, it's rng , just no.

**Comment by Aviannaqt** [comment]
it was reported a long time ago

**Comment by chibiske** [comment]
then tell us the fucking fix
