### ISSUE TITLE
Tol Barad Queue Timer Off

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/BugTracker#5759]
I seem to be a few minutes behind the actual Tol Barad start timer, about 5 minutes to be exact. People start saying in /world to Queue for TB etc right as it says "Tol Barad will begin in 15 minutes" but my timer is always at 19-20 minutes (and i'm not able to queue until 15).
 
Same thing happens for when the match starts. It says "The Battle for Tol Barad has begun", but my timer is still counting down from 4-5 minutes (as if it still had not started).
 
I've only gotten in 1 single TB out of the maybe 15 or so I've queued for in the past few days because of this.
 
Proof: http://imgur.com/CcL6eJ9 & http://imgur.com/dqSfBIw
 
Timer is a bit off (was debating whether or not to make a post) but still, it shows on my screen the battle has not started yet, but for everyone else it has.

Deleted my Cache/WTF folders, did nothing.

Re-installed and used a fresh client, did nothing.

Must have something to do with my account.

**Comment by Aviannaqt** [comment]
read bt rules
