### ISSUE TITLE
[EN][Instance - TBC] The Black Morass / Opening of the Dark Portal

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#576]
Not a 4.3 change, but there is a significant problem with Infinite Dragonflight mob waves.

On our server, on every wave after killing Chrono Lord Deja, there is a significant delay between waves, that should be present only after killing a boss (i.e. before portals 7 and 13).

It works on portals 1-6 on our server, but portals 8-12 and 14-18 are affected by a significant delay. On retail it goes fast for portals 1-6, 8-12 and 14-18, with delays present after defeating a boss (i.e. before opening the portal 7, 13)

Chrono Lord Deja: http://www.wowhead.com/npc=17879 (although I think this has something to do with portal script, instead of him, still including his ID as an indicator).

**Comment by Rainofblood** [comment]
Bump
It takes like forever to finish this dungeon and most of the time you are waiting for salvation xD
