### ISSUE TITLE
[PL][Achievement][Utgarde Pinnacle] The Incredible Hulk

### ISSUE THREAD

**Issue by Vievior** [Atlantiss/BugTracker#5760]
Witam. Otóż po tym jak Svala zabija Scourge Hulka achievement nie jest zaliczony.

Link do achi http://www.wowhead.com/achievement=2043/the-incredible-hulk

**Comment by Aival94** [comment]
Reported or related: https://github.com/Atlantiss/BugTracker/issues/1865
