### ISSUE TITLE
[EN] [Battleground] Warsong Gulch Victory

### ISSUE THREAD

**Issue by Simgiov** [Atlantiss/BugTracker#5761]
In case of a draw after 27 minutes the horde won the BG. But the ally scored the first point (I did it personally). That's not what should happen.

**Comment by Wolffenstein** [comment]
Any proof? Because as far as I know, and from what I saw on Blizz forums, the team scoring last wins WSG in case of a draw.

**Comment by Simgiov** [comment]
Really? Then I'm a noob, sorry, nevermind ^^
