### ISSUE TITLE
[EN] [Spell] [Warrior] Farm in Arathi Basin

### ISSUE THREAD

**Issue by max10lock** [Atlantiss/BugTracker#5764]
In Arathi Basin many people are having trouble with their abilities, for me it was charge, which makes it impossible to actually compete with other players. It also happened around the blacksmith in arathi basin as well. Apparently it happened to some other classes as well. It also says, "No Path Availible" or "Too Far Away"

**Comment by max10lock** [comment]
Update: My friend told me to restart my client and I did and the problem has gone away

**Comment by Aviannaqt** [comment]
its global bug with move maps, reported some time ago
