### ISSUE TITLE
[EN][Warlock] Pet

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#5765]
Pet die randomly at Firelands,
Like The lava hit him -20k -20k everytime, and he is not in lava at all.

**Comment by anxanas** [comment]
So does doomguard and fiery imps.
And now that we have focus on warlocks i think these links are in order:
https://github.com/Atlantiss/BugTracker/issues/5431
https://github.com/Atlantiss/BugTracker/issues/5669
https://github.com/Atlantiss/BugTracker/issues/3389
https://github.com/Atlantiss/BugTracker/issues/5365
