### ISSUE TITLE
[EN][SHAMAN][MAGE]

### ISSUE THREAD

**Issue by morfeno** [Atlantiss/BugTracker#5766]
Hi! Today I wanted buy a pvp set for shamans on 60 lvl, but I can't find him and my friend (mage) can't find his set. So I relogin on my warlock and he have it. This npc name is: First Sergeant Hola'Mahi. Please, fix it :) Thank you a lot! :)
![wowscrnshot_010816_215022](https://cloud.githubusercontent.com/assets/16615856/12209233/f50194d0-b651-11e5-82c9-ea6357b9930e.jpg)

**Comment by metaldoctor** [comment]
I have some problem with set for hunter.

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
