### ISSUE TITLE
[EN][Quest][Eversong Wood] Solanian's belonging

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#5768]
In this quest you have to get three items, the scroll and the book are ok, but when you click on the orb, it's empty, no quest item.

http://www.wowhead.com/quest=8330/solanians-belongings

![wowscrnshot_010916_043026](https://cloud.githubusercontent.com/assets/11901135/12214167/20716216-b68a-11e5-8498-2cc38b08faf9.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4800.

**Comment by Griskhet** [comment]
The problem still persist.
