### ISSUE TITLE
[EN][RDF system for vanilla WoW dungeons] Sachel of Helpful Goods

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5769]
How it should work: The reward from the sachel should depend on the dungeon you complete, not your character's level. 
What is bugged: The reward from the sachel depends on your character's level.

Example for the 26-35 level range satchel from wowhead (dungeon level range, not character level range): http://www.wowhead.com/item=52000/satchel-of-helpful-goods#comments.
As you can see from the first comment on wowhead from this link,  "The level range is determined by the instance you run, not the level your character is. It includes Gnomeregan, Razorfen Kraul, all wings of Scarlet Monastry and the Wicked Grotto (purple) wing of Maraudon. The satchel for this level range contains either a Necklace or Gloves, all BoP randomly enchanted rare iLvl 35 items."

I noticed this bug when, after completing Shadowfang Keep at lv 19, I got a http://www.wowhead.com/item=51994/tumultuous-cloak ( correct loot for dungeons of level 15-25) and a priest that level to 26 in Shadowfang Keep got a http://www.wowhead.com/item=51996/tumultuous-necklace (this loot should belong to sachel from completing "Gnomeregan, Razorfen Kraul, all wings of Scarlet Monastry and the Wicked Grotto (purple) wing of Maraudon", as mentioned in the wowhead link above, regardless of your character's level).

**Comment by Wolffenstein** [comment]
You're wrong. You receive satchels based on the dungeon finder quest rewarded at the end of the dungeon, which depends on your character's level. The dungeon itself has no influence on the rewards, but it can belong to two different DF quest brackets, that's why the rewards will differ for some players.
