### ISSUE TITLE
[EN][Zangarmarsh] Unidentified plant parts

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#5771]
http://www.wowhead.com/item=24401/unidentified-plant-parts#comments
How this item is bugged: It  drops only if you are on the quest http://www.wowhead.com/quest=9802/plants-of-zangarmarsh .
How it should work: It should drop regardless if you are on the mentioned quest or not.

**Comment by NatsumeLily** [comment]
It does drop regardless...I've had them drop from herbs in Azeroth.

**Comment by Aldurion** [comment]
They didnt drop from mobs in Zangarmarsh unless I had the quest Unideintified Plant Parts in my quest log.

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11621-5771item-unidentified-plant-parts/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
