### ISSUE TITLE
[EN][Firelands] Lord Rhyolith.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#5772]
Hello.
Im checking tactic for this boss, and all of they said: Causing Rhyolith to step on Active Volcanoes removes 16 stacks of Obsidium Armor. It only takes 5 Volcanoes to drop him to 0 Armor (80 -> 64 -> 48 -> 32 -> 16 -> 0). But he lose only 10 stacks when step on active volcanoes. He must lose 10 stacks in Heroic vesrion only.
http://www.wowhead.com/npc=52558/lord-rhyolith#comments:id=1496615 comment at wowhead.
http://www.icy-veins.com/wow/lord-rhyolith-strategy-guide-normal-heroic example of tactic.

UPDATE:
I think you all know site mmo-champion. I find hotfixes for 4.2.0. Special for ppl who dont trust wowhead comment. It says:
Lord Rhyolith

    The explosion damage radius of each Magma Meteor just before Lord Rhyolith should now more closely match their spell effect visuals.
    Volcanoes should no longer emit plumes of smoke while they are dormant.
    Concussive Stomp should no longer knock nearby players back.
    Magma Flow lines are now 30 yards long, down from 40 yards, on normal difficulty.
    Rhyolith now activates volcanoes less often on normal difficulty.
    Stepping on an active volcano now removes 16 stacks of armor, up from 10, on normal difficulty.

Link: http://blue.mmo-champion.com/topic/183042-patch-42-hotfixes/

**Comment by Kaldros** [comment]
Read the comment u linked again. That is **post nerf**.
