### ISSUE TITLE
[EN][PL][Spell][Death Knight] Scourge Strike

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#5773]
**[EN]**
Scourge Strike: http://www.wowhead.com/spell=55090/scourge-strike

I notices huge damage difference in fight inside Vortex Pinnacle.
This is damage done on Assad: http://www.wowhead.com/npc=43875/asaad
![assad](https://cloud.githubusercontent.com/assets/7345784/12216574/b4e62f9c-b6e6-11e5-98e1-70ebd4a587df.jpg)

This is damage done on Altarius (2nd boss in Vortex Pinnacle):
![altarius](https://cloud.githubusercontent.com/assets/7345784/12216575/b8e79c2a-b6e6-11e5-9c43-3d8b9962ecd6.jpg)

On both fight I used self buffs.
I'm not sure if it's a bug in ability or boss itself (Assad).
I couldn't find any information on Assad reducing damage done by Scourge Strike.

---------------------
**[PL]**
Scourge Strike:   http://www.wowhead.com/spell=55090/scourge-strike

Zauważyłem dużą różnicę obrażeń w walce w Vortex Pinnacle.
To są obrażenia wykonane na Assad: http://www.wowhead.com/npc=43875/asaad
![assad](https://cloud.githubusercontent.com/assets/7345784/12216576/c29f3566-b6e6-11e5-8dc5-127e818b98e7.jpg)

To są obrażenia na Altariusie (drugi przeciwnik w Vortex Pinnacle):
![altarius](https://cloud.githubusercontent.com/assets/7345784/12216578/c735cde2-b6e6-11e5-987d-1085fb4f256d.jpg)

W obu walkach użyłem własnych buffków.
Nie jestem przekonany czy błąd istnieje w umiejętności czy w przeciwniku (Assad).
Nie mogłem naleźć informacji na temat Assada obniżającego obrażenia wykonane przez Scourge Strike.

**Comment by Jenovas** [comment]
Winny jest Asaad. Własnie sprawdziłem bossa i z przyczyn mi niewiadomych jego armor jest 100x większy od armora Altairusa.
Naprawione w revie 4801.
