### ISSUE TITLE
[EN][ÑPC][Molten Front] Kirix

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5777]
Kirix is flying in the air constantly.

http://www.wowhead.com/npc=54323/kirix

![kirix](https://cloud.githubusercontent.com/assets/12621497/12216870/ca9082ee-b6ef-11e5-93e8-b7d533e42bd9.png)

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/6750
https://github.com/Atlantiss/BugTracker/issues/5498
