### ISSUE TITLE
[EN][Quest][Molten Front] Into the Fire

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5781]
The Druids of the Talon quest "Into the Fire" is bugged now, and has been all day long.

The event doesn't start when you accept the quest, nothing happens. No Pyrolord to kill nor any NPC to walk up there with.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/5661#issuecomment-170256778
