### ISSUE TITLE
[PL][NPC][Kosmetyka][Firelands] Flamewaker Overseer

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#5783]
http://www.wowhead.com/npc=53185/flamewaker-overseer#screenshots

NPC Flamewaker Overseer nie posiada broni w swojej ręce.

**Comment by xmesaj2** [comment]
fix: http://community.atlantiss.eu/index.php?/topic/7560-5783npc-flamewaker-overseer-weapon-cosmetic/

**Comment by Navedonar** [comment]
fixed http://community.atlantiss.eu/index.php?/topic/7777-57835784flamewaker-taskmasterflamewaker-overseer/
