### ISSUE TITLE
[PL][NPC][Kosmetyka][Firelands] Flamewaker Taskmaster

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#5784]
http://www.wowhead.com/npc=53224/flamewaker-taskmaster

NPC posiada zły model broni.

**Comment by xmesaj2** [comment]
fix: http://community.atlantiss.eu/index.php?/topic/7561-5784npc-flamewaker-taskmaster-weapon-cosmetic/

**Comment by Assiria** [comment]
po co zglaszacie takie bzdury? bossy na fl uzywaja skilli jak chca kiedy chca sa pobugowane, bugi leza i kwicza, a tutaj sie naprawia model broni...

**Comment by InformatorPE** [comment]
@Assiria
bug jest bugiem, masz problem z bugami ktore leza to sam mozesz je naprawic i wrzucic do tematu **Post your fix** Najlepiej to narzekac i samemu nic nie robic
