### ISSUE TITLE
[EN][Achievement][Molten Front] King of the Spider-Hill

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5785]
http://www.wowhead.com/achievement=5872/king-of-the-spider-hill

I am aware that several people have gotten this achievement, but I cannot seem to get it. 

maybe it has something to do that I progressed into this questline http://www.wowhead.com/quest=29181/druids-of-the-talon ? 
Because a guildy of mine who hasn't done this, got the achievement a few minutes ago and says he's on the same spot where I am standing (we can't see eachother though cause phasing) 

whatever sparks the achievement (guessing some 'bunny/imp' npc focus thing... ) maybe it doesn't work in all phases?

_edit: http://imgur.com/B7xDt7J that's where I was
*_edit: i've been told that the achievement works for those who chose the warden quests, so it does seem to have something to do with phasing

**Comment by Bastion** [comment]
![wowscrnshot_122815_161106](https://cloud.githubusercontent.com/assets/1584564/12217311/ee62030c-b6fc-11e5-85e7-10961828c0a6.jpg)

**Comment by xolon** [comment]
I got it the first day of mf release

**Comment by Assiria** [comment]
works lol

**Comment by Luna-maria** [comment]
"I am aware that several people have gotten this achievement, but I cannot seem to get it."

**Comment by Sayris9876** [comment]
It doesnt have to do anything with wardens and u shouldnt climb up without being pulled u have to go from bottom to top only by getting pulled... I failed once or twice and got it eventually

**Comment by Luna-maria** [comment]
I checked how the achievement is supposed to be done on retail before posting. It's just not working for me

**Comment by vaseno1** [comment]
got it on the first day just SS my self up cuz im a bloody rogue :P

**Comment by lamaze** [comment]
i had the same problem and i solved it just relogging on the top of the hill
