### ISSUE TITLE
[EN][Item] Crossfaction Gold Mailing - Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5788]
Naw on our server you can send Gold with Heirloom to another character between faction.

Normaly you can't do it.
If our server is Blizzlike plz, make it Blizzlike.

Proof:
http://www.wowhead.com/forums&topic=146969/cross-faction-gold-gear-transfer

"the only way to transfer gold to diffrent faction is by using the neutral auction house in booty bay/ratchet. what i usually do say my orc wants to send my human 100g, ill take a worthless item with my human, and post said worthless item on the neutral AH for 100g then buy it with my orc.

just always make sure the item your posting is worth less than the gold your transfering so someone doesnt snatch it up.

forgot u cant buy ur own items, u can always get a friend to post the worthless item for you."

**Comment by Wolffenstein** [comment]
Fixed in rev 4802.

**Comment by Chulain** [comment]
one retard reports it, another retard bothers fixing it..

**Comment by BialyADI** [comment]
Now is much better and Blizzlike, cheers!
