### ISSUE TITLE
[EN][Firelands] Baleroc 25 Decimation Blade

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#5789]
Raid: Firelands 25man
NPC: Baleroc 
Link: http://www.wowhead.com/npc=53494
Spell: Decimation Blade
Link: http://www.wowhead.com/spell=99352

[EN]
Baleroc 25man dosn't use Decimation Blade.

Based on rumors and logs from one guild:
http://www.worldoflogs.com/reports/xxxohxb5h0i59syo/details/174/?s=5373&e=5664
http://www.worldoflogs.com/reports/l6xjoftlzuy7vetf/details/204/?s=6247&e=6514
(i dont do 25man myself)

10man works well.

**Comment by aneq** [comment]
confirmed it doesnt work, it used to work tho.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4862
