### ISSUE TITLE
[EN][Quest - TBC] Return to Andormu + The Black Morass

### ISSUE THREAD

**Issue by Velius94** [Atlantiss/BugTracker#579]
http://www.wowhead.com/quest=10285
http://wowpedia.org/Quest:Return_to_Andormu

This quest is no longer available as of 4.3

Its completion was required for the attunement for Black Morass, but it was marked as obsolete since the dungeon revamp for TBC and WotLK.

The attunement has to be removed, because in the PTR it is required to access the instance (even if the character has completed it before [most likely a different issue related to the PTR itself, since Main realm character can access it just fine], since my character had access to The Black Morass quest)

http://www.wowhead.com/quest=10296 - The Black Morass

This is the quest that should have been unlocked after completing Return to Andormu.
Because Return to Andormu has been removed in 4.3, The Black Morass quest should be unlocked by default (it's a breadcrumb quest, so the followup can be picked up without completing it).

**Comment by Tj20** [comment]
I encountered the same problem. Wowhead says

> In 4.2, its attunement process was removed and it no longer requires you to run a prior CoT instance.

Despite that, the Black Morass is still locked. Reason: "You have not completed the required quest."

![pic](http://i.imgur.com/JlQlV7F.jpg)

**Comment by Axahus** [comment]
http://www.wowhead.com/zone=2366/the-black-morass#comments
"You no longer need to attune for this instance as of 4.2"
Jakis czas temu (na 100% przed oficialnym 4.3.4) robiłem tę inste i mogłem normalnie wejść bez attu (sprawdzałem przed chwilą i nadal mogę), natomiast nowym altem nie mogę wejść, gdyż wyświetla się komunikt o wymaganym attu.
