### ISSUE TITLE
[EN][Core][GuildVault]Crash

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5790]
**Note there is already a error bug tracker open with just info about the crash here me and a guild member who had crash issues worked on it till it didnt crash on us anymore.**
Here is a list of the possible items that I have removed that has stopped the guild vault from crashing currently. There are all Cata greens that has random stats. Some stats items do not get the random stats as they should.
I did not link every single separate item the list would never end.

Highperch Items
http://www.wowhead.com/search?q=highperch#items
Mystral Items
http://www.wowhead.com/search?q=mystral#items
Ravencrest Items
http://www.wowhead.com/search?q=ravencrest
Mardenholde Weapons
http://www.wowhead.com/search?q=Mardenholde
Mereldar Items
http://www.wowhead.com/search?q=mereldar#items
Bladefist weapons
http://www.wowhead.com/search?q=bladefist
Talondeep Items
http://www.wowhead.com/search?q=talondeep
Stonewrought Items
http://www.wowhead.com/search?q=stonewrought
Crystalvein Items
http://www.wowhead.com/search?q=crystalvein
Haldarr items
http://www.wowhead.com/search?q=haldarr
Dandred items
http://www.wowhead.com/search?q=dandred

**Comment by Wolffenstein** [comment]
Need more data, it doesn't crash for me.

**Comment by Thefakemccoy** [comment]
Wolf I really dont know what other data I can give. It does not cause every one to crash. Some guild members it never effected.
