### ISSUE TITLE
[EN][ITEM][FIRELANDS]Matrix Restabilizer

### ISSUE THREAD

**Issue by Lamka** [Atlantiss/BugTracker#5792]
I tried 5 times and every time it boosts my haste but it should chose stat depending on my stats. I have 1300 hate and 1800 mastery at the moment and it still choses haste. I'm Feral Cat btw.

**Comment by freddie12** [comment]
I wanna add that we have same problem with Apparatus of Khaz'goroth as well. I tried it with a frost death knight.

**Comment by tnarf** [comment]
Effect of little test (crit << haste ; crit << mastery):
haste: 1326 (+10,35%) mastery: 1587 (+8,85) -> bost HASTE
haste: 1069 (+8,35%) mastery: 1501 (+8,37) -> bost MASTERY
...
haste +% > mastery +p -> bost HASTE
haste +% < mastery +p -> bost MASTERY

so trinket bost statistic witch biggest +value (bracket in statistic tooltip) not RATING (BUGGED)

**Comment by Jenovas** [comment]
tnarf - thx for the test I thought that might be the issue.
Fixed in rev 4808.
