### ISSUE TITLE
[EN][Firelands] Encounter is in progress bug

### ISSUE THREAD

**Issue by Exertt** [Atlantiss/BugTracker#5794]
After wiping at boss, there is a chance for the encounter to keep going even if everyone is dead and outside thus not letting us enter the instance. Happened to us with Lord Rhyolith and Beth'ilac.

Fortunately for Beth'ilac, everyone relogging helped, but Rhyolith kept our lockout bugged so we are not able to continue.

This is serious bug that needs to be fixed as fast as possible.

**Comment by ponpontos** [comment]
I agree.

**Comment by LaveniaGithub** [comment]
I've experienced this bug at both Lord Rhyolith and Alysrazor making it impossible to continue before a server crash or restart.

**Comment by metaldoctor** [comment]
At Alysrazor if u wiped best way to dont have this bug wait in corpse before she does full circle of phases and then reseted, it works for us.

**Comment by Exertt** [comment]
![ss 2016-01-10 at 09 46 55](https://cloud.githubusercontent.com/assets/16023330/12223898/cb24310c-b7e3-11e5-9d80-2bc0585fdc4c.jpg)

**Comment by gumby123** [comment]
This is pretty annoying atm tbh fam

**Comment by Kaldros** [comment]
This happened to my raid group as well - on Rhyolith and Alysrazor.

We believe the cause for this bug at **Rhyolith** were guild **banners** we placed close to the boss. We wiped 2 or 3 times while the banners were still there and we had to wait for 5-10 minutes before being able to enter - quite possibly until the banners despawned. However, after that we decided not to place any banners close to the boss and after we wiped, the boss reset immediately.

As for **Alysrazor**, you just need to wait until she goes through all four phases. That's when she resets and u can enter the raid normally.

**Comment by Exertt** [comment]
We also found out that once you wipe on Rhyolith and he fails to reset, you can just wait until lava damages his legs to 25% and takes him to 2nd phase, where he resets. 

Although sometimes he resets even in 1st phase.

**Comment by Aldergar** [comment]
#6031

**Comment by Atlntssplayer** [comment]
I can confirm that there is a high chance that guild banners have something to do with this bug.
Today Rhyolith bugged for us, he wouldn't reset after raid wipe, but as soon as the guild tabard disappeared, he reset and we could ress and enter the dungeon.
