### ISSUE TITLE
[EN][Raid][Firelands] Bethilac- Ember Flare

### ISSUE THREAD

**Issue by planche** [Atlantiss/BugTracker#5795]
<b>How it should work</b>
<a href='http://www.wowhead.com/spell=99859/ember-flare#used-by-npc'>Ember Flare</a 
shouldn't be resisted by fire resistance.
Proof
<a href='http://www.worldoflogs.com/reports/bxb06mx8duni19i3/xe/?s=1749&e=2174&x=spell%3D%22Ember+Flare%22+and+type%3DTYPE_DAMAGE&page=4'>Link</a>
<b>How it works now</b>
it is resisted. <a href='http://www.worldoflogs.com/reports/xxxohxb5h0i59syo/xe/?s=1628&e=2074&x=spell%3D%22Ember+Flare%22+and+type%3DTYPE_DAMAGE&page=3'>Link</a>

**Comment by Aldergar** [comment]
#6031
