### ISSUE TITLE
[EN][Molten Front] Reputation for quests.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#5799]
Hello.
Daily quest in molten fron give wrong reputation reward. For example Between the Trees give u 1rep only when it must give u 150, next one The Power of Malorne give u 2rep when it must give u 250.
Links for quests:
http://www.wowhead.com/quest=29125/between-the-trees
http://www.wowhead.com/quest=29126/the-power-of-malorne
http://www.wowhead.com/quest=29164/perfecting-your-howl (added new)
Proof link for screenshot with rep:
http://imgur.com/BhZdw7d
http://imgur.com/YL4HyOl (added new)

**Comment by metaldoctor** [comment]
Find 2more quests with bug reputation, both give 2rep for u:
http://www.wowhead.com/quest=29147/call-the-flock
http://www.wowhead.com/quest=29148/wings-aflame

**Comment by metaldoctor** [comment]
2 more bugged quests:
http://www.wowhead.com/quest=29101/punting-season
http://www.wowhead.com/quest=29122/echoes-of-nemesis
Proof:
http://imgur.com/a/d8k5X

**Comment by metaldoctor** [comment]
I think its 2 last bugged quest with rep in starts ones:
http://www.wowhead.com/quest=29161/those-bears-up-there
http://www.wowhead.com/quest=29162/natures-blessing
Proof of our low rep:
http://imgur.com/a/8jkSY

**Comment by user1011** [comment]
To which faction should they give reputation?

**Comment by TranceAccount** [comment]
Posted a fix on the forums.
