### ISSUE TITLE
[PL][NPC][Item]Honor weapons price

### ISSUE THREAD

**Issue by Kepasax** [Atlantiss/BugTracker#5800]
Co jest zle:
Bronie jednoreczne za honor kosztuja u nas 3400 honoru czyli tyle co 2h.

Powinny kosztowac 2450, analogicznie do ceny broni za conquesty.

https://cynwise.wordpress.com/2011/06/24/battleground-pvp-gear-in-cataclysm-patch-4-2-arena-season-10/

**Comment by Milton3450** [comment]
1h weaps cost too much (3400 honor) confirmed. Should cost 2450.

**Comment by theoar** [comment]
bump

**Comment by phifedawg** [comment]
bump 2.0

**Comment by Kuszki** [comment]
confirm

**Comment by Bildo** [comment]
Link those weapons

**Comment by Kuszki** [comment]
So, here u are.

|	Item						|	ID	|	 Price (actual)		|	Price (blizzlike)		|
|:-------------------------------------------|:-----------:|:-----------------------------:|:------------------------------:|
| [Vicious Gladiator's Right Ripper]	| 61330	| 950				| 2450				|
| [Vicious Gladiator's Right Render]	| 61333	| 3400				| 2450				|
| [Vicious Gladiator's Shanker]		| 61327	| 3400				| 2450				|
| [Vicious Gladiator's Hacker]		| 61325	| 3400				| 2450				|
| [Vicious Gladiator's Cleaver]		| 61324	| 3400				| 2450				|
| [Vicious Gladiator's Gavel]			| 61338	| 3400				| 2450				|
| [Vicious Gladiator's Bonecracker]	| 61336	| 3400				| 2450				|
| [Vicious Gladiator's Pummeler]		| 61335	| 3400				| 2450				|

[Vicious Gladiator's Right Ripper]: http://cata.openwow.com/item=61330
[Vicious Gladiator's Right Render]: http://cata.openwow.com/item=61333
[Vicious Gladiator's Shanker]: http://cata.openwow.com/item=61327
[Vicious Gladiator's Hacker]: http://cata.openwow.com/item=61325
[Vicious Gladiator's Cleaver]: http://cata.openwow.com/item=61324
[Vicious Gladiator's Gavel]: http://cata.openwow.com/item=61338
[Vicious Gladiator's Bonecracker]: http://cata.openwow.com/item=61336
[Vicious Gladiator's Pummeler]: http://cata.openwow.com/item=61335

**Comment by Bildo** [comment]
Fixed, will be on repo later.
