### ISSUE TITLE
[EN][Dungeon Finder] Valor points.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#5801]
Hello.
We always have reward 140 valor points, but it must be 150.
Wowwiki says:
Looking for Dungeon — 150 VP per run, with a cap of seven runs per week. All Cataclysm heroic dungeons introduced in 4.0, 4.1, and 4.3, will provide 150 Valor per run.
Link: http://wowwiki.wikia.com/wiki/Valor_point

**Comment by RandomPickNewb** [comment]
The 150 valor/dungeon was introduced in 4.3 we are on 4.2 content atm.

**Comment by Glare** [comment]
We should have 140 for Zandalari 5mans(ZA/ZG) and 70 for other heroics

**Comment by Aival94** [comment]
4.2 Patch changes:
The maximum number of Valor Points awarded for completing Rise of the Zandalari dungeons remains at 980.
The maximum number of Valor Points awarded for completing Heroic dungeons remains at 490.
The number of Valor Points awarded for killing a boss in the Firelands is 120 in 10-player mode, and 140 in 25-player mode.
The number of Valor Points awarded for killing Occu'thar in Baradin Hold is 120 in 10-player mode, and 140 in 25-player mode.
The number of Valor Points awarded for killing a boss on Heroic difficulty in The Bastion of Twilight, Blackwing Descent, and Throne of the Four winds is 35 in 10-player mode, and 45 in 25-player mode.
Link: [Patch 4.2](http://wowwiki.wikia.com/wiki/Patch_4.2)

I do not know if they are going to change it to 4.2 or just update it to 4.3 way of earning valor points but these were the changes they did on 4.2 about how to earn Valor points generally.

**Comment by Glare** [comment]
Too much work, low prio, they will change nothing.

**Comment by Kejmil** [comment]
from what i recall dev said that they can't change client to have separate queue for troll dungeons on our patch

**Comment by Aival94** [comment]
Yes.The separate troll dungeons category was only on 4.2 and if you want to change probably need to either change client to 4.2 or too much hard work from devs to implement their own ui system(or sth like this,i am not sure if the dungeon finder is a part of blizzard ui or not).
