### ISSUE TITLE
[PL][Item set][Paladin]  t12 holy 2p bonus (next try)

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#5803]
Teraz działa aż za dobrze bo ma szanse odpalić od każdego heala a powinnien tylko od holy shocka.
http://www.wowhead.com/spell=99067/item-paladin-t12-holy-2p-bonus
http://www.wowhead.com/spell=20473/holy-shock#modified-by
![wowscrnshot_011016_133541](https://cloud.githubusercontent.com/assets/9517740/12221547/5a220194-b79f-11e5-9895-ade75b621e30.jpg)

![wowscrnshot_011016_134216](https://cloud.githubusercontent.com/assets/9517740/12221566/fe94984a-b79f-11e5-8997-731ad5ea5dfc.jpg)

**Comment by Jenovas** [comment]
Fixed in rev 4811
