### ISSUE TITLE
[EN][NPC][Zangarmarsh]Mortog Steamhead(ID 23373)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5805]
NPC has the vendor button but when you interact with him he only show the greetings <Player> window.

![wowscrnshot_010516_203234](https://cloud.githubusercontent.com/assets/10282971/12221894/6aacff2c-b7b4-11e5-96f7-bf7b8b885de8.jpg)

Wowhead Link: [Mortog Steamhead](http://www.wowhead.com/npc=23373/mortog-steamhead)

**Comment by Wolffenstein** [comment]
Fixed in rev 4802.
