### ISSUE TITLE
[EN][Spell-Object][Portal][Twilight Highlands]Portal to Stormwind

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5807]
My portal to Stormwind stopped working after some updates.I have already done all the available quests in the zone and when i asked a gm told me to relog and clear cache.I tried but nothing.The name of my char is Worgdrud.I have not heard anyone else having the same problem but i just put it as report in bugtracker in case someone got it as well.

**Comment by Aival94** [comment]
/no
/pat
OK.Come on man.These are reports here.Please do not do it that :)

**Comment by Luna-maria** [comment]
portal isn't working for my toons either

**Comment by Illusionist87** [comment]
Portal is broken for my toons as well, and my friends also.

**Comment by Articuno** [comment]
Yup. Doesn't work.

**Comment by DuGalle** [comment]
Still not working i things its easy to fix this its not major but annoying as hell.

**Comment by karolnpc** [comment]
Bump

**Comment by Cellhawk** [comment]
Still not working.

**Comment by rdoherty0** [comment]
Still not working

**Comment by DuGalle** [comment]
after many months Still not working i made new char just now unlock the portal via quests and when you go true it nothing Bump

**Comment by Aival94** [comment]
Portal is working just fine now. You need to complete the quest [The Way is Open](http://www.wowhead.com/quest=27545/the-way-is-open).
I close this issue.
