### ISSUE TITLE
[PL]Power Word:Fortitude

### ISSUE THREAD

**Issue by Lugrossa** [Atlantiss/BugTracker#5809]
Jak w temacie , buff staminy od priesta na 80 dany  na twinka 19 lvl nalicza hp jak na 80 czyli twink mial prawie 6 k hp na tym poziomie
![wowscrnshot_011016_181157](https://cloud.githubusercontent.com/assets/16636271/12222854/d0da845a-b7c7-11e5-9308-cc20d1c6826c.jpg)

**Comment by BialyADI** [comment]
Mhm no ciekawe te pvp na low lvl ;D.

**Comment by Kejmil** [comment]
to chyba nie buff od priesta tylko scroll z insciption

**Comment by Aviannaqt** [comment]
chyba juz widzialem takie zgloszenie gdzies

**Comment by Kejmil** [comment]
bildo chyba kiedys to poprawial, widac cos zostalo pominiete

**Comment by Aviannaqt** [comment]
#3871
