### ISSUE TITLE
[EN] [bg&arenas] PvP armor 2 piece bonus stacking

### ISSUE THREAD

**Issue by Shisai** [Atlantiss/BugTracker#5810]
when a player uses 2 pieces of 2 pvp armor sets it's currently stacking the resilence bonus, for example; if a shaman wears 2 pieces of mail and 2 pieces of ringmail armor they recieve 800 resilence by getting the 400 resil bonus twice.
as of patch 4.2 they should only recieve the 400 resilience bonus once,

this applies to other classes with more than one type of pvp set too, such as druids, priests, shaman etc

http://us.battle.net/wow/en/blog/2993743/rage-of-the-firelands-patch-42-notes-%5Bupdated-628%5D-6-28-2011

"Set Bonuses

The 2-piece resilience bonus from Cataclysm PvP sets no longer stacks. If a player wears 2 pieces each from 2 different Cataclysm sets, the player will only receive the 400 resilience rating bonus once. This change does not apply to PvP sets from prior expansions."

**Comment by Illusie** [comment]
And it does stack atm?
Bootysweat told me it isn't (2/5 or 3/5)

**Comment by Lanrutcon** [comment]
It is stacking, at least for Priest.

**Comment by BialyADI** [comment]
Yeah it is, OP at the moment ;D.

**Comment by Shisai** [comment]
so many people are abusing this, makes healers pretty much immortal, kind of game breaking when it comes to pvp :/

**Comment by Aviannaqt** [comment]
#2270

**Comment by BialyADI** [comment]
bump.
