### ISSUE TITLE
[PL][Quest]The Art of Persuasion

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5812]
Nie dziala Qitem na npc ktorego trzeba torturowac a ponadto jak użyje itemka i bede chcial wylaczyc gre pojawia sie wow error 
http://www.wowhead.com/quest=11648/the-art-of-persuasion
![wowscrnshot_011016_224128](https://cloud.githubusercontent.com/assets/16046575/12224254/51a930bc-b7ec-11e5-8d03-fd55f0997b46.jpg)

**Comment by Avalain** [comment]
Powtórzenie błędu: #2281

Po restarcie serwera quest działa. Nie jest to idealnie, ale możliwy do ukończenia.

**Comment by Aviannaqt** [comment]
#2281 pamietam.. na kazdym privie tak działa/działało :D
