### ISSUE TITLE
[PL][Other]Utgarde Keep

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5813]
Nie ktore Moby w tej inscie maja zbugowane teksty jak rzucaja oszczepem 

![wowscrnshot_010816_004554](https://cloud.githubusercontent.com/assets/16046575/12224276/d8484f9a-b7ec-11e5-9412-b78da6ca6e82.jpg)

**Comment by Aviannaqt** [comment]
read bt rules
