### ISSUE TITLE
AV mountain  BUG

### ISSUE THREAD

**Issue by Drixa** [Atlantiss/BugTracker#5814]
![wowscrnshot_011016_165838](https://cloud.githubusercontent.com/assets/16639002/12224608/a2f544bc-b7fe-11e5-9a10-4485e233c869.jpg)
![wowscrnshot_011016_165842](https://cloud.githubusercontent.com/assets/16639002/12224609/a8269f8a-b7fe-11e5-9f9a-938feb7b6f8f.jpg)
![wowscrnshot_011016_165844](https://cloud.githubusercontent.com/assets/16639002/12224610/ab74cf4a-b7fe-11e5-98a5-4e32667edc98.jpg)
![wowscrnshot_011016_165849](https://cloud.githubusercontent.com/assets/16639002/12224611/adaec32e-b7fe-11e5-9b34-d4400c5adead.jpg)
![wowscrnshot_011016_165852](https://cloud.githubusercontent.com/assets/16639002/12224612/afdb9f50-b7fe-11e5-9d3e-03a19906a3ec.jpg)
![wowscrnshot_011016_165854](https://cloud.githubusercontent.com/assets/16639002/12224614/b256fa40-b7fe-11e5-8c46-9733e6258ff5.jpg)
![wowscrnshot_011016_165855](https://cloud.githubusercontent.com/assets/16639002/12224616/b68fe658-b7fe-11e5-98da-303f2fda8a48.jpg)
the mountain is bugd there is no LoS + most of the Horde players are abusing it like that mage

**Comment by Bastion** [comment]
BAN

**Comment by Kejmil** [comment]
ban all fire mages
and take ice lance away from frost!

**Comment by Aviannaqt** [comment]
read bt rules

xD
