### ISSUE TITLE
[PL][Warrior] Sweeping Strikes - "Crit" bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5821]
Sweeping Strikes(SS) -> http://cata.openwow.com/spell=12328

Jak jest:
Sweeping Strikes nie kopiuje Crita z głownego targetu.
Jeśli np. z Mortal Strikem walniemy za 10k Critem to skopiowany atak z SS tez powinien walnać Moba obok za 10k, u nas aktualnie walnie go za 5k jak by w ogole nie bylo Crita na głownym targecie.

Jak powinno być:
Sweeping Strikes sam w sobie nie może Critnąć lecz moze skopiować Crita i powinien to robić 1 do 1.
Czyli jak mamy Crita na głownym targecie SS powinien robić 2x Dmg jaki teraz robi.

Dowody:
http://wow.gamepedia.com/Sweeping_Strikes
"Sweeping Strikes cannot crit, but by dealing 50% of the original attack's damage, will deal double damage to the additional target when the original attack crits."

Czy WoltLK, czy Cata Speeping Strikes powinien bić za tyle co dostał główny target jeśli walneliśmy gówny target Critem to target obok powinien dostać taki sam skopiowany Dmg (nie Krytyczny) z SS, tak to też pamiętam grając na Cata.

**Comment by Nc94** [comment]
"Your melee attacks strike an additional nearby opponent for 50% damage." 
Z tooltipa SS czyli na polski każdy atak jest kopiowany ale bije o 50% mniej więc działa jak powinno

**Comment by BialyADI** [comment]
Gdyby działało to bym nie zgłaszał, If You Know What I Mean ^^.

**Comment by Nc94** [comment]
"Jeśli np. z Mortal Strikem walniemy za 10k Critem to skopiowany atak z SS tez powinien walnać Moba obok za 10k, u nas aktualnie walnie go za 5k jak by w ogole nie bylo Crita na głownym targecie."

Crit za 10k po skopiowaniu i zmniejszeniu o 50% powinien walnąć za 5k.... Więc to ty przeczytaj ze zrozumieniem co napisałeś i jeśli bug faktycznie istnieje to popraw, bo to co jest wyżej przez ciebie napisane pokazuje, że owego buga nie ma..

**Comment by Kejmil** [comment]
rekt

**Comment by blinkmaster** [comment]
Ss pewnie omija armor i resi, już widziałem taki bug na innym servie. Można też było go bugac mając macra na jednoczesny startattack na focus i target robiąc po 4 hity naraz .

**Comment by blinkmaster** [comment]
No i jak ktoś ma wara to niech jeszcze sprawdzi czy ss się nie odpala z bladestorma na 1 target bo to też bywa często zbudowane na privach

**Comment by Kejmil** [comment]
bladestorm+ss dziala dobrze, tak by przynajmniej wynikalo z mojego testu przed chwila

**Comment by BialyADI** [comment]
50% kopiuje na pandach, na Cata kopiuje wszystko 1 do 1 tylko nie Crity które tez powinny byc skopiowane 1 do 1 i tyle ta dam :p.

**Comment by Kepasax** [comment]
Powinien kopiowac 1:1 a takze brac pod uwage debuffy/buffy do dmg na targecie w ktory uderza. Dlatego w niektorych przypadkach sweeping strikes moze uderzac o wiele wiecej niz atak z ktorego zostal skopiowany.
http://www.wowhead.com/spell=12328/sweeping-strikes#comments:id=1286193

**Comment by mati865** [comment]
Jak już linkujesz wiki to linkuj chociaż z czasów Cata, http://wow.gamepedia.com/index.php?title=Sweeping_Strikes&oldid=2795578

Odnośnie 190% dmg na kukle, cytat z wowhead podanego komentarz wyżej:
"It is physical, but not mitigated by armour. The base damage is an exact copy of the damage done to the original victim regardless of anything which increased or decreased that original damage. The sweeping strikes damage however is also affected by damage and physical damage modifiers - even if the original mob had the same debuff. This means, if you hit one mob with a +100% damage taken debuff for 100k (normally 50k), and there is a mob standing next to him with the same debuff, he will be hit for 200k, quadruple the original damage. This is a neat trick for something like the adds on Maloriak during the green phase."

**Comment by blinkmaster** [comment]
a jakiez to debuffy mogla miec kukla, ze zrobil na niej ssem 2x wiekszy dmg?

**Comment by BialyADI** [comment]
Tu rozchodzi się o to że jak np. odpalamy Recklessness i Sweeping Strikes i bijemy po 50k z Crita nasz target to target obok tez powinien dostać za 50k a dostaje jak by nie było Crita i tu jest problemo.
Target obok powinien dostawać 2x aktualnego Dmg.

**Comment by Nc94** [comment]
Tak jak blinkmaster napisał jakie debuffy mogła mieć kukła stojąca obok, która nawet nie była w combat ze mną kiedy dostała z SS ;o I nie nie jest to wina jakichś tam debuffów po prostu SS bije za dużo kiedy jest kopiowany melee swing (w przypadku Mortal Strike jakoś jest kopiowany 1-1 http://i.imgur.com/EkP0byR.png ). Na pewno nie jest to też ten sam bug co z DRW od DK bo DRW to Guardian/Pet a one mają inną mechanike niż SS (correct me if im wrong).
I nie nie jest to drobny bug gdzie melee swing, który uderza zawsze za 190% dmg kiedy przy kochanym przez wszystkich RNG crit może wcale nie wejść.

P.S. "podwÓjnie"

**Comment by BialyADI** [comment]
Jasne że powinien kopiować Execute tu jest wszystko ok.
Cytat który dałeś jest z Vanilla WoW 1.11.0 wtedy to jeszcze inaczej działał SS miał Stacki ale nie o tym jest zgłoszonko.

Kurcze czytaj ze zroumieniem http://tf2.digitaljedi.com/midgetfaceslide.gif ;D.
Mortal Strike jak i inne ataki są dobrze kopiowane jeśli nie są Critami.
Natomiast przy krytycznym ataku SS kopiuje nasz atak jak by nie był Critem więc kopia jest 2x słabsza.

**Comment by Nc94** [comment]
..............

http://wow.gamepedia.com/index.php?title=Sweeping_Strikes&oldid=2795578

**Comment by BialyADI** [comment]
Bug jest Bugiem, ten jest na minus jak już sie licytujemy, w koncu nie kopiuje w ogóle Critów.
A korzystam z Googlowego translatorka jak muszę i nie narzekam ;D.
