### ISSUE TITLE
[PL][Warrior] Deep Wounds is no affected by damage modifiers.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5822]
Deep Wounds(DW) -> http://cata.openwow.com/spell=12868

Jak jest:
Deep Wounds nie jest zwiększne przez modyfikatory.

Normalnie po pojedyńczym Krytyku w kukle DW tickało po 350, i gdy odpaliłem Death Wish który zwiększa u mnie na Fury Warku Dmg o 34% i ponownym pojedyńczym Krycie nadal Dmg  z DW jest taki sam.
Podobnie jest z Enrage tez nie zwiększa Dmg z Deep Wounds.

Jak powinno być:
Dmg z Deep Wounds powinien być zwiększany przez efekty Enrage jak każdy inny Fizyczny Dmg.

Enrage -> http://cata.openwow.com/spell=13046
Death Wish -> http://cata.openwow.com/spell=12292
i Enrage z Wrecking Crew -> http://cata.openwow.com/spell=56611

**Comment by Jenovas** [comment]
Deep Wounds w DBC WoWa ma atrybut - SPELL_ATTR6_NO_DONE_PCT_DAMAGE_MODS
Tak więc wynika że nie powinno nic na niego wpływać tylko melee DMG który go włączył.
Jakby było tak jak mówisz to jakby boss powiedzmy miał aure że dostaje 1000% mocniej to nie dość że Twój melee uderzy za 100k to potem DW z niego biłby nie za 50% Twojego crita tylko 500%, a tak to raczej nie powinno działać. Zamykam.

**Comment by BialyADI** [comment]
No nic, poszukam dowodu bo z pamięci cięzko mi powiedzieć jak to dzialało.
Btw plz fix Self Heal Warka bo w PvP jest to spory bug z Field Derssing;x.

**Comment by BialyADI** [comment]
O kurde pozamiatane http://wowwiki.wikia.com/wiki/Deep_Wounds.
Nawet w patch notach jest że: 
"The damage done by this talent no longer receives modifications from effects that increase or decrease damage done by a percentage. The base weapon damage used in the calculation will still be modified by those effects."

Więc sry ciut za szybko to zgłosiłem ;p.

**Comment by kadi2** [comment]
Jedyna co moze udac ci sie znalezc to cos, co mialoby skalowac sie podobnie tak jak ignite, z modyfikatorami na targecie.
