### ISSUE TITLE
[PL][Druid][Spell][Ragnaros] Starfall, Wild Mushrooms

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#5824]
Starfall oraz Wild Mushrooms nie sięgają ragnarosa w żadnym przypadku

**Comment by fafal** [comment]
Wszystkie Melee Range Spelle nie sięgają Alakira, Sinestry oraz Ragnarosa ;)

**Comment by anxanas** [comment]
Dont forget shadowflame immolation aura(meta) immolation(infernal) felstorm =))

**Comment by Kejmil** [comment]
who cares about your sad aoe when ghoul is not working in blood/frost spec ( ͡° ͜ʖ ͡°)
WIP

**Comment by Aviannaqt** [comment]
co zrobisz nic nie zrobisz, mozesz czekac na fix xd
