### ISSUE TITLE
The Zapthrottle Mote Extractor! is this quest works ??

### ISSUE THREAD

**Issue by chlebmati** [Atlantiss/BugTracker#5825]
i don't see an exclamation above the "Mack Diver" in Zangarmarsh so i can't take the quest from him.

**Comment by Luna-maria** [comment]
update the title and add a wowhead/wowwiki/something link to the quest or it'll be closed

https://github.com/Atlantiss/BugTracker/blob/master/README.md instructions how to make posts so they won't get closed :)
