### ISSUE TITLE
[EN][Quest][Dragonblight] Planning for the Future

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#5828]
This quest has been reported bugged a total of 6 times. I'm posting it now again because it was reported in June and August of 2015 in English and Polish and both times issue has been closed with no fix. All that was done was reference both posts back and forth with no explanation or fix. This quest is a daily that's required for Kalu'ak reputation.

http://www.wowhead.com/quest=11960/planning-for-the-future

"Collect 12 Snowfall Glade Pups. Deliver them to Trapper Mau'i at Moa'ki Harbor."

When I click on the Pups I get no credit for picking them up. can not collect Pups.

**Comment by Anhaeyn** [comment]
This quest was working for some time. Recently it bugged again, and when I try to collect any, then this pup attacks me, instead of being gathered.

**Comment by Bmuzyn** [comment]
http://www.wowhead.com/item=35692/snowfall-glade-pup
when i click the pups they attack me instead of being looted

**Comment by Navedonar** [comment]
http://atlantiss.eu/changelog#rev4864
