### ISSUE TITLE
[EN] [SPELL] [SHAMAN] TREMOR TOTEM

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#5829]
http://cata.openwow.com/spell=8143    --> tt
http://cata.openwow.com/spell=605      --> mc
http://cata.openwow.com/spell=65543  --> fear
tremor makes u immune to fear and such effects even tho u destroyed it.
Ex.
1.priest mc'ed shaman
2.shaman used tremor
3.priest killed it 
4.priest feared jk immune
gamebreaking

**Comment by blinkmaster** [comment]
http://www.arenajunkies.com/topic/258037-tremor-totem-rework-idea/

its idea to rework tremor so it would grant immune - thus it didnt grant it before wod.

**Comment by Illusie** [comment]
@blinkmaster 
Yes but it should not grant immune after you destroyed it or it disappeared,
I found myself many times killing Tremor with Fel Flame, come Fear. and get "Immune" message.
And saying to myself "but I destroyed it!!!"

Can confirm.
Only work when someone destroying it, not working when it self-destroyed.

**Comment by blinkmaster** [comment]
of course, i posted this link to show how ridiculus it is on our server that it grants immune.

**Comment by Jenovas** [comment]
So what is the bug? Tremor Totem lasts for say 30 seconds and the shaman gains fear immune for 30 seconds even if Tremor got destroyed by a player?

**Comment by debtheone** [comment]
dunno how long the immune lasts will check later x]

**Comment by Jenovas** [comment]
I dont need to know for how long, I need to know when it happens.
Tremor expires everything works ok, Tremor gets destroyed by player Tremor still works. Yes?

**Comment by debtheone** [comment]
Tremor expires everything works ok ------->    dunno gonna test 
, Tremor gets destroyed by player Tremor still works. Yes? -------->  yes

**Comment by kadi2** [comment]
https://youtu.be/10eP2u8z9uk?t=1m52s

**Comment by Illusie** [comment]
@Jenovas yes like for 2-4 sec after destroyed by spell.
the immune should be removed immediatly when totem destroyed.
It still grant immune for like 2-4 sec after it destroyed.

I don't know how often and if it does it 100% of time, but I had few times.
AoE Fear > Tremor > destroying Tremor>Fear again, immune.

**Comment by kadi2** [comment]
Umm, shaman uses tremor at 1:55 and gets refeared 2 seconds later.

**Comment by Jenovas** [comment]
Tremor Totem in the DBC states that it gives the Shaman 6 seconds of immunity to fear, so this is probably the bug.

**Comment by kadi2** [comment]
So ya. That's correct, but the immunity should be removed when tremor totem gets destroyed/is canceled by the shaman.

**Comment by Jenovas** [comment]
Fixed in 4843
