### ISSUE TITLE
[PL][NPC][Vendor][Molten Front] Damek Bloombeard

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5833]
http://www.wowhead.com/npc=53214
nic nie sprzedaje. 
http://i.imgur.com/3LzXyqD.jpg

**Comment by Drutmaster** [comment]
Przeczytaj komentarze do tego vendora. Wątpię byś miał już odblokowane obie frakcje ORAZ następną opcję za 125 marków

**Comment by eryczek1615** [comment]
Znaczy ja myślałem ze po odblokowaniu obu frakcji powinien już sprzedawać. Przepraszam za niepotrzebne zgłoszenie
