### ISSUE TITLE
Throne of the Tides ENTRANCE - bug

### ISSUE THREAD

**Issue by marcinb12500** [Atlantiss/BugTracker#5836]
When you go down there and try to enter it manually, you will not get summoned to the throne of the tides entrance, instead you will just find the end of the vortex in vash, and I need this instance for my twink

I have SS 
https://gyazo.com/92421706659d9c799f9f7e60111a0cb2
https://gyazo.com/6cbadedb395ee14f9a358bb5ae8d95af
https://gyazo.com/473b6e3926a5ca4e440b5378f8e1a679

Fix this or give me some way to get there

I AM LVL 79

**Comment by Anhaeyn** [comment]
Aren't cata dungeons from 80 lvl?

**Comment by Thefakemccoy** [comment]
Cata dungeon have a level requirement of 80 so a 79 wont enter it. The vortex that takes you down is also no scripted since vashjir is not even open to quest.

**Comment by marcinb12500** [comment]
You have always been able to get in lvl 78, ALWAYS. lvl 80 is for Dungeon
que.. So I expect to get in somehow

**Comment by Thefakemccoy** [comment]
According to this 
http://wow.gamepedia.com/Cataclysm_instances_by_level
min lvl for TotT is 80 but 77 for BRC.

**Comment by Thefakemccoy** [comment]
So doing more research http://www.wowhead.com/guide=1750/dungeon-item-level-requirements#dungeons-cata-normal
                                                
1	Blackrock Caverns	        80-83	84-85	80-82	80	**77**	226	308	
2	Throne of the Tides	        80-83	84-85	80-82	80	**77**	226	308	
3	The Stonecore 	        81-85	N/A	        82-84	82	**80**	272	316	
4	The Vortex Pinnacle	81-85	N/A	        82-84	81	**80**	272	316	
5	Lost City of the Tol'vir	84-85	N/A	        84-85	83	**83**	272	333	
6	Halls of Origination	        84-85	N/A	        84-85	83	**83**	272	333	
7	Grim Batol	                84-85	N/A	        84-85	84	**83**	272	333

**Comment by marcinb12500** [comment]
Well I am a twink, so I have a high item  lvl due to  77-79 cata greens, I
can get into black rock cavern manually, but not throne since it's bugged,
I would like it fixed as I KNOW for FACT that I can get into it with my
gear and level.

I provided you proof of the bug, if you wish to have poof that you should
be able to get in at lvl 78 with the right gear, then I WILL give it to you.

**Comment by Aviannaqt** [comment]
read bt rules

**Comment by marcinb12500** [comment]
Bad excuse. Problem is a problem, fact is fact while it is valid and
perceived as such.. Personal flavor nor respect has nothing to do with
anything.. A doctor doesnt care if the patient laughs or yells, he still
has to mend him..

You should too
