### ISSUE TITLE
[EN][Quest][Elwynn Forest]Fear no Evil

### ISSUE THREAD

**Issue by AurorainR** [Atlantiss/BugTracker#5841]
Seems like this quest isn't able to be completed atm. http://www.wowhead.com/quest=28812/fear-no-evil

The soldiers that you revive don't contribute to the quest total. Now, this quest seems like it's slightly different for every class(the rewards change, but it's the same quest is what I mean), and I'm currently trying to finish it as a Hunter, so I'm not quite sure if it's only for Hunters.

**Comment by GreenParty** [comment]
Me too don't work :(

**Comment by Wolffenstein** [comment]
I broke it in the last update, sorry about that.

Fixed in rev 4806.
