### ISSUE TITLE
[EN][NPC][Vendor]Gunra

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#5842]
Gunra is missing item Cowl of Pleasant Gloom http://www.wowhead.com/item=58155 on content 4.2 for 2,2k JP. She should have it just like Mask of New Snow http://www.wowhead.com/item=58161.

**Comment by sohussain** [comment]
Can confirm this!

**Comment by user1011** [comment]
Perhaps a link to the NPC who sells them?

Thank you.

**Comment by stanq87** [comment]
http://wow.gamepedia.com/Cataclysm_Justice_Points_gear or use addon like atlasloot from 4.2 ? or inspect equip ? or even rawr has that data

**Comment by sohussain** [comment]
For Gunra: NPC ID is 46555 I suppose http://cata.openwow.com/npc=46555
For Magatha Silverton is 44246 http://cata.openwow.com/npc=44246
This is assuming the IDs on openwow are the IDs needed.

**Comment by user1011** [comment]
The IDs from WoWhead are needed, but the IDs from openwow should be the same as on WoWhead.

**Comment by user1011** [comment]
Posted a fix on the forums.
