### ISSUE TITLE
[EN][Item] - Gale of Shadows

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#5843]
Link - http://www.wowhead.com/item=56462/gale-of-shadows#comments

Drops from Erudax in Grim batol. The trinket is at its 4.0.6 state atm and has ICD of 2.5 seconds on the stacking buffs. It may take close to a minute to get all the stacks up. As of 4.2 (and we are at 4.2 atm) the trinket looses its ICD and stacks like the other trinkets with barely no ICD aka gets stack of every tick of Lifebloom for example or a dot.

**Comment by anxanas** [comment]
"Appears to have lost it's ICD in 4.2, 1 stack of the buff per 1 tick of Lifebloom at 0.83s per tick."
http://www.wowhead.com/item=56462/gale-of-shadows#comments

**Comment by Kejmil** [comment]
INSERT INTO spell_proc_event (entry, Cooldown) VALUES
(90986, 0) ON DUPLICATE KEY UPDATE Cooldown = 0;

**Comment by Jenovas** [comment]
Fixed in rev 4810
