### ISSUE TITLE
[EN][Spell]Spells disappearing from actionbar

### ISSUE THREAD

**Issue by kostas4949** [Atlantiss/BugTracker#5847]
After the latest fixes were applied the actionbar spells aren't saved after a relog for some people. I've lost 5 of my spells that after a relog disappear again. Changing position on any spell also resets after a relog.
This is happening so far to only 1 of my characters. A friend of mine has the same exact issue. It's not class specific since he is a warrior and my warrior alt doesn't have any such issues.

**Comment by Fapguy** [comment]
Yes, happens to me too, sucks having to pull out 8 different spells in each druid form. Really a pain in the a....

**Comment by kostas4949** [comment]
Got fixed after latest restart.Thanks
