### ISSUE TITLE
[EN][LOOT][Firelands] Items not having stats.

### ISSUE THREAD

**Issue by Maggun** [Atlantiss/BugTracker#5849]
Some items, like "Flickering Cowl" does not have stats. i suppose it's not just visual bug since those items don't give anything but armor even when worn.

**Comment by Kejmil** [comment]
all flickering XXX items from firelands have this problem
http://www.wowhead.com/items?filter=na=flickering;minrl=85;maxrl=85;cr=195;crs=1;crv=0;gb=1#head

**Comment by metaldoctor** [comment]
In 1st week we had nice tanking hands with stats for our tanks, but at other weeks we have bad luck, no stats or cloth head with agility only, for priest tank i think.
Agi cloth head proof:
http://imgur.com/mx2bH1d

**Comment by Bildo** [comment]
duplicate
