### ISSUE TITLE
[PL][NPC] Baradin Fox

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#5850]
http://cata.openwow.com/npc=47676
http://www.wowhead.com/npc=47676/baradin-fox
http://www.wowhead.com/item=64403/fox-kit

NPC Baradin Fox nie posiada w loocie Fox Kit.

**Comment by Wolffenstein** [comment]
(47676, 64403, 0.1, 1, 0, 1, 1);
