### ISSUE TITLE
[EN][NPC] Infernal - Acherus.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5854]
![wowscrnshot_011216_204027](https://cloud.githubusercontent.com/assets/5780624/12274835/083426ee-b96d-11e5-8de1-55cd28c0c416.jpg)
Small(Baby) Infernal is standing on teleport in Acherus something must be wrong.

**Comment by Kejmil** [comment]
it's teleport trigger

**Comment by BialyADI** [comment]
Yeah, but it shoud be invisible?
