### ISSUE TITLE
[PL][Spell][Mage][Warrior] Blink - Charge/Intercept Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5857]
False Alarm, sry ;(.

**Comment by blinkmaster** [comment]
Blink daje 1 sec immune na stun i jest to poprawne od czasów vanilli.
http://us.battle.net/wow/en/forum/topic/14926473324

**Comment by BialyADI** [comment]
Kurde myślałem że oszukujesz, ale z nickiem BlinkMaster nie mozesz kłamac na temat blinka ;D.

A tak serio poszukałem i kurde fakt:
http://eu.battle.net/wow/en/forum/topic/5116191886
"    Mages are immune to stuns for about 0,1-0,2 seconds after blinking.


Seems this really is the truth. This is ludicrous, why hasn't this sloppy blink mechanic been fixed ages ago? And the thing about hamstring not being applicable if certain other snares are present is mind-twitching, especially if you want to immobilize the target with improved hamstring... no wonder the warrior community seems so dissatisfied.

World #1 MMO... unbelievable."

Nie pamiętam żeby tak było ale jednak widać ze jest ;x.
Do zamknięcia.
