### ISSUE TITLE
[PL][Spell][Warrior] Charge - Arathi Basin BG.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5858]
Intercept -> http://cata.openwow.com/spell=20252
Charge -> http://cata.openwow.com/spell=100

Jak jest:
![wowscrnshot_011316_014928](https://cloud.githubusercontent.com/assets/5780624/12281725/d470eef6-b998-11e5-9f8e-ff72ea89f6fd.jpg)
![wowscrnshot_011316_014921](https://cloud.githubusercontent.com/assets/5780624/12281737/e62fe4e4-b998-11e5-8c2b-c7e457da1110.jpg)
![wowscrnshot_011316_014753](https://cloud.githubusercontent.com/assets/5780624/12281743/ea6795a2-b998-11e5-82f7-f02f91e116f4.jpg)
Na całym Arathi Basin nie można dać Charge/Intercept w przeciwnika.
Pamiętam że tak wcześniej nie było.
Znaczy zawsze były problemy z Charge całkowicie nie da sie nią "wjechać" pod górkę szarżą, ale tutaj jest prosty teren.

Próbowałem też skacząc nic nie pomagało ;<.
Pewno to samo ma Druid z swoim Charge.

**Comment by Aviannaqt** [comment]
global bug, kolejne zgloszenia nic nie dadza mozna jedynie czekac na fix
