### ISSUE TITLE
[PL][Quest] Desolation Hold Inspection

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#586]
Gdy rozmawiam z Warlordem Bloodhiltem w Vendetta Point ( http://www.wowhead.com/npc=37679 ) to nic prócz "Greetings <Name>" podczas interakcji się nie pokazuje.

Link: http://www.wowhead.com/quest=24577/desolation-hold-inspection

**Comment by armano2** [comment]
new issue: #4262

**Comment by vragni** [comment]
Dalej nie dziala
