### ISSUE TITLE
[EN][NCP][Vendor]Ayla Shadostorm

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#5860]
Ayla shadowstrom in Molten Front is unlocked once you turn in quest Filling the moon well.
She has all her items shes should sell except the Relics.
NPC
http://www.wowhead.com/npc=53881/ayla-shadowstorm
Missing Items
http://cata.openwow.com/item=70109
http://cata.openwow.com/item=70111
![wowscrnshot_011316_001225](https://cloud.githubusercontent.com/assets/12252441/12285670/7864bd1c-b98a-11e5-9b03-c340658cef26.jpg)

Valan Highbough will prob be missing his relics as well.

NPC
http://www.wowhead.com/npc=53882/varlan-highbough

Items
http://cata.openwow.com/item=70125
http://cata.openwow.com/item=70128

**Comment by Sayris9876** [comment]
I am really curious how you got enough marks to open the first vendor concidering im doing quests from the begining of MF and havent skipped a single day and yesterday i just opened my second faction...

**Comment by xolon** [comment]
Ye i want to know the same

**Comment by Thefakemccoy** [comment]
Do dailies.

**Comment by Sayris9876** [comment]
Something is fishy :} unless it is a screenshot from PBE realm its not possible to have enough marks for one of the end vendors yet

**Comment by Thefakemccoy** [comment]
What a PBE realm?

**Comment by LaveniaGithub** [comment]
At a point people could take a quest that shouldn't have been available. Some managed to take it in time. Quest gave 12 marks I heard.

**Comment by Thefakemccoy** [comment]
Fixed
