### ISSUE TITLE
[PL][Talent][Mage] Ignite Dmg Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5863]
Ignite -> http://cata.openwow.com/spell=12846

Jak jest:
Ignite Robi ponad 50% Dmg Crita od Fire Maga.

Jak powinno być:
"Your critical strikes from non-periodic Fire damage spells cause the target to burn for an additional 40% of your spell's damage over 4 sec."

SS:
Dostałem z Crita za 5947 a z Ignite za 3080 ponad 50% wartości Crita.
Na kukle podobnie.
![wowscrnshot_011316_112527](https://cloud.githubusercontent.com/assets/5780624/12291576/6b25fcd4-b9e8-11e5-8b8b-6e5082f9bcf2.jpg)
![wowscrnshot_011316_112534](https://cloud.githubusercontent.com/assets/5780624/12291581/70d7ef2a-b9e8-11e5-99c9-bc1bc2ac9992.jpg)

**Comment by Jenovas** [comment]
Proszę wpierw poczytać a potem robić zgłoszenia.
Zamykam.

**Comment by BialyADI** [comment]
Sry, pierdoła ze mnie zapomiałem o Mastery.
