### ISSUE TITLE
[PL][Quest][Halls of Origination] Map of the Architects

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5865]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Large Stone Obelisk" (http://www.wowhead.com/object=207410/large-stone-obelisk).

Link do zadania:
http://www.wowhead.com/quest=28802/map-of-the-architects

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
