### ISSUE TITLE
[PL][Quest][Grim Batol] Vengeance of the Wildhammer

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5866]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Dwarven Bone Pile" (http://www.wowhead.com/object=207411/dwarven-bone-pile).

Link do zadania:
http://www.wowhead.com/quest=28803/vengeance-of-the-wildhammer

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
