### ISSUE TITLE
[PL][Quest][Lost City of the Tol'vir] Tol'vir Hieroglyphics

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5867]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Tol'vir Grave" (http://www.wowhead.com/object=207409/tolvir-grave).

Link do zadania:
http://www.wowhead.com/quest=28801/tolvir-hieroglyphics

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
