### ISSUE TITLE
[PL][Quest][The Stonecore] Might of the Earthen

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5868]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Broken Pillar" (http://www.wowhead.com/object=207407/broken-pillar).

Link do zadania:
http://www.wowhead.com/quest=28799/might-of-the-earthen

**Comment by Achiver** [comment]
Z tego co wiem to akurat ten obiekt ten jest

**Comment by Vyrtuz** [comment]
Tak, jest- podobnie jak ten z Halls of Origination jednak nie ma zadania.

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
