### ISSUE TITLE
[PL][Quest][The Vortex Pinnacle] Whispers of the Djinn

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5869]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Magical Brazier" (http://www.wowhead.com/object=207408/magical-brazier).

Link do zadania:
http://www.wowhead.com/quest=28800/whispers-of-the-djinn

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
