### ISSUE TITLE
[PL][Quest][Throne of the Tides] Waters of Elune

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5870]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Strange Fountain" (http://www.wowhead.com/object=207406/strange-fountain).

Link do zadania:
http://www.wowhead.com/quest=28798/waters-of-elune

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
