### ISSUE TITLE
[PL][Quest][Zul'Aman] Zul'Aman Voodoo

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5871]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Voodoo Pile" (http://www.wowhead.com/object=208549/voodoo-pile).

Link do zadania:
http://www.wowhead.com/quest=29261/zulaman-voodoo

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
