### ISSUE TITLE
[PL][Quest][Zul'Gurub] Zul'Gurub Voodoo

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#5872]
Brak zadania. Daily quest powinien być dostępny z "obiektu" jakim jest "Voodoo Pile" (http://www.wowhead.com/object=208550/voodoo-pile).

Link do zadania:
http://www.wowhead.com/quest=29262/zulgurub-voodoo

**Comment by ardo22** [comment]
fix: http://community.atlantiss.eu/index.php?/topic/7694-5872quest-zulgurub-voodoo-pile/

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5107 fixed
