### ISSUE TITLE
[EN][Quest] Sealing the Way

### ISSUE THREAD

**Issue by jokehold** [Atlantiss/BugTracker#5877]
When using quest item on target and then pressing the ESC button,wow crashes
Quest: http://www.wowhead.com/quest=26501/sealing-the-way
Pic: ![bug](https://cloud.githubusercontent.com/assets/16424580/12302735/6be662de-ba2f-11e5-9e84-7f31574e881b.png)

**Comment by Aviannaqt** [comment]
#4135
