### ISSUE TITLE
[EN][Quest][tirisfal glades]A Daughter's Embrace

### ISSUE THREAD

**Issue by DanielMan191** [Atlantiss/BugTracker#5879]
the Quest work but dont sow good 
Quest:http://www.wowhead.com/quest=25046/a-daughters-embrace
1.the nps dont in the correct place 
![2015-12-21_00004](https://cloud.githubusercontent.com/assets/16239982/12303614/07403d64-ba34-11e5-8225-e9839168d36d.jpg)
the nps need to be here https://youtu.be/TwBFH6zHUak?t=1s
2.the nps need to following u not only whan u coma to there

**Comment by Aviannaqt** [comment]
duplicate

**Comment by DanielMan191** [comment]
from whar

**Comment by DanielMan191** [comment]
from whar
