### ISSUE TITLE
[EN][lost in the darkness][Silverpine Forest]

### ISSUE THREAD

**Issue by DanielMan191** [Atlantiss/BugTracker#5881]
in the quest lost in the darkness u cant Rescue all the Orc Sea Dogs only A few of them 
the quest http://www.wowhead.com/quest=27093/lost-in-the-darkness
![2015-12-24_00008](https://cloud.githubusercontent.com/assets/16239982/12304135/b40e8bfc-ba36-11e5-8d35-b62865ae04b5.jpg)

**Comment by Aviannaqt** [comment]
#3657

**Comment by ItsLozopess** [comment]
I would like to reopen this one. It has passed 2 years and the bug is still present.

**Comment by Piklo** [comment]
then open new report
