### ISSUE TITLE
[PL][QUEST] Ears of the Lich King

### ISSUE THREAD

**Issue by Therenir** [Atlantiss/BugTracker#5886]
Link : https://cata-twinhead.twinstar.cz/?quest=29803

Cześć, dziś będąc na Utgarde Keep swoim DK Worgen 68 lvl po  wykonaniu i oddaniu questów z owej instancji zauważyłem, że w/w quest dodaje mi repe do Horde Expedition zamiast do Alliance Vanguard
![wowscrnshot_011316_211326](https://cloud.githubusercontent.com/assets/15131744/12306785/e694f052-ba3b-11e5-9993-8cb391ebe036.jpg)

W prawym dolnym okienku widać, że dodało mi repy dla hordy

**Comment by Aviannaqt** [comment]
http://community.atlantiss.eu/index.php?/topic/7780-8556questears-of-the-lich-king/ fix
