### ISSUE TITLE
[EN][Raid][Firelands] Ragnaros encounter didnt end. 

### ISSUE THREAD

**Issue by lqlq32** [Atlantiss/BugTracker#5888]
We killed him tonight, boss went under lava, but the encounter didnt end, no chest with loot, he just keep casting hammers, meteors, but we cloudnt dps him anymore. he was under the lava or something like that. After we wiped - he respawned.

**Comment by LaveniaGithub** [comment]
![skaermbillede 2016-01-13 kl 23 04 39](https://cloud.githubusercontent.com/assets/12621497/12310331/1223d4ea-ba50-11e5-8f85-ab3b5c554e15.png)
![skaermbillede 2016-01-13 kl 23 03 35](https://cloud.githubusercontent.com/assets/12621497/12310340/1ab7438a-ba50-11e5-9cc6-7715a0937739.png)

**Comment by Bastion** [comment]
still no achiev :D

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev4832
