### ISSUE TITLE
[en][core] Pets

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#5889]
All classes controlable pets ( and some guardians like gargoyle for dk for sure ) are completly messed up right now. They stay in one place, does not attack at all ( /petattack nor aggresive nor assist ). 
only possible way to move them is via /petmoveto but this gives you only the possibility to move it, it does not follow its target.
Its seriously going worse with pets movement day after day.
plz fix :/

**Comment by Vegakyudan** [comment]
i'm pretty sure that gargoyle should fly above players, and move way faster then it is now. I'm gonna find some sources later.

**Comment by Larcan** [comment]
This bug is still here, problem is that this is happening only in some zones. Like for example Elwynn Forest just in front of Stormwind (Alliance Duel Area) also other zone is in Firelands in front of Baleroc and in molten front Malfurion's breach. Bug happens to be removed after a server restart or crash.

If anyone knows any other zones of this bug happening please list them here.

**Comment by Milton3450** [comment]
Confirmed!!! Very annoying and huge bug!

**Comment by Khangu** [comment]
Warlock's demons got the same problem. Additionally after summoning they often loose skillbar config restoring it to defuault.

**Comment by Larcan** [comment]
Update.
Looks like this bug works for Warriors, Feral druids as well they cannot use charge ability, when you try to use this ability it pops up a message No Path Found.

**Comment by Milton3450** [comment]
My pet doesn't even work now in BH 25 man!

**Comment by Milton3450** [comment]
lock pets seem to be working atm. This seems very random.

**Comment by Milton3450** [comment]
Pet stuck suddenly bugged again in Elwynn duelling area.

**Comment by Viggo93** [comment]
I just started playing on a new warlock and Im experiencing the same problem with the follow command for demon pets (Voidwalker and felguard) that they are not following or attacking even when I push the button (follow or attack) in the demon skillbar. The only demon that have worked so far is the imp. I have seen this problem in elwynn forest aswell as westfall.

secondly the skillbar for demons only first appeared when I hit level 10. Understandable that you get a passive skill giving control over demons but when you get a voidwalker in lvl 8, you cannot controll it at all.

**Comment by 1Andas** [comment]
The skillbar for demons is supposed to be learned on level 10, before that you're not supposed to have it in Cataclysm. It's same for hunters, they get theirs on level 10 as well in Cata.
