### ISSUE TITLE
[EN][Firelands] Ragnaros lava pool

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#5892]
Boss: Ragnaros
Link: http://www.wowhead.com/npc=52409/ragnaros

[EN]
Lava pool, in which he stand, Ragnaros doesn't make dmg,
This bug can be used durning combat especially by melee.

Proofs:
MMO chaimpions discusion about that SOMETIMES lava dosn't make dmg:
http://www.mmo-champion.com/threads/980577-Normal-ragnaros-lava-pool-no-longer-deals-damage?p=13283630&viewfull=1#post13283630

WorldOfLogs with dmg value (25k per second):
http://www.worldoflogs.com/reports/6tjintcbm7gmymaj/spell/97151/?s=9186&e=9894

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev4832
