### ISSUE TITLE
[EN][Quest][Molten Front] Living Obsidium Chip

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#5893]
I've found a problem, when doing http://www.wowhead.com/quest=29295/the-bigger-they-are
http://www.wowhead.com/npc=52107/obsidium-punisher - these ones are supposed to spawn loot boxes http://www.wowhead.com/object=208803/living-obsidium-chip when they are killed. Currently they don't do that, nor do they drop quest items in their loot list.

**Comment by Thefakemccoy** [comment]
How did you get this quest. I did not. And I have unlocked both sides plus a vendor.

**Comment by Raknar** [comment]
after dc they will drop

**Comment by Thefakemccoy** [comment]
Raknar will you add the relics to the vendors  :)

**Comment by tnarf** [comment]
As Raknar wrote that was.
But now (propably becous rev 4828) the don't spawn that "loot boxes" (quest not posilbe to complete).

Bug associated with:
https://github.com/Atlantiss/BugTracker/issues/5817

**Comment by Bildo** [comment]
fixed
