### ISSUE TITLE
[PL][Firelands][Ragnaros][Spell] - Sulfuras Smash

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#5895]
Na wczorajszym (tj. 13-01-2016) 10 os. rajdzie, Sulfuras Smash (http://www.wowhead.com/spell=98710/sulfuras-smash) uzywany przez Ragne, nie był graficznie ujawniany w ktorym miejscu uderzy, jedynie obracal sie w tę konkretna strone, uderzał młotkiem w jakies miejsce, i dopiero po 3/4 s. ( a nie instantowo) rozchodzily sie fale lawy.

Wiadomo jak to wyglada poprawnie, ale dla przypomnienia 5:20 https://www.youtube.com/watch?v=E2a0BnG_XhE

**Comment by aneq** [comment]
to wina diffu

**Comment by Quban** [comment]
fixed in rev. 4815
