### ISSUE TITLE
[EN][Quest][Molten Front]The Forlorn Spire/Into the fire

### ISSUE THREAD

**Issue by DontBeSadbro** [Atlantiss/BugTracker#5901]
They are bugged like they used to be when you completed one of the 150 mark quests, but now it happens on The Regrowth phase(when both 150 mark quests are completed). NPC doesnt spawn.

**Comment by Luna-maria** [comment]
#5661
#5727
#5694

**Comment by DontBeSadbro** [comment]
Yes, they all work now if you have 1 of 150 mark quests done, but they are bugged when you have both done.

**Comment by Luna-maria** [comment]
hmm, it bugged sometimes when I only had 1 questline opened as well (and I never take both quests at the same time cause phasing messes things up)
