### ISSUE TITLE
[EN][QUEST]The eye of All storms Bug

### ISSUE THREAD

**Issue by Devqv12** [Atlantiss/BugTracker#5903]
There is a really buged quest the dragons propobly should fly in the storm but they stay at ground and you can't kill them only 1 dragon is in the storm and you can kill him only with Thessera

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/2028
If you think you can give more info just make a comment after checking if it is already reported :).
