### ISSUE TITLE
[EN][Quest][Redridge Mountains] It's Never Over

### ISSUE THREAD

**Issue by gajeel1899** [Atlantiss/BugTracker#5905]
It doesn't work. The boat stops near it's destination. If i leave, the boat dissappears. Just bugged :(

**Comment by gajeel1899** [comment]
OKay, on next day worked. Maybe the admin fixed it after i told him

**Comment by Evelinrose** [comment]
Slight issue with this quest if it doesnt work simply relog and try it again.
