### ISSUE TITLE
[PL][NPC][Shadowfang Keep] Deathstalker Commander Belmont

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#5907]
Po zabiciu bossa NPC sobie staje i nie otwiera już drzwi do dalszej części dungeonu:

http://i.imgur.com/A79p3zx.jpg

**Comment by Aival94** [comment]
As far as i know fixed.

**Comment by xmesaj2** [comment]
closing since last comment says it's fixed
