### ISSUE TITLE
[EN][Item][Trinket] Moonwell Chalice

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5910]
http://www.wowhead.com/item=70142/moonwell-chalice

Trinket doesn't work. No buff is provided when used (should 1700 mastery rating for 20 seconds).

When you use the item the moonwell appears, but it doesn't link to you the way it should and it doesn't give you any buff.

![skaermbillede 2016-01-15 kl 11 10 14](https://cloud.githubusercontent.com/assets/12621497/12350697/f53e4bb0-bb78-11e5-8d69-187aef235e3f.png)

**Comment by Glare** [comment]
Damn.

**Comment by anxanas** [comment]
Bump

**Comment by fafal** [comment]
What ;o

**Comment by anxanas** [comment]
Important thing isnt fixing the animation, just the mastery gain =)))

**Comment by anxanas** [comment]
The moonwell is considered your guardian so the key to fixing it might have something to do with fixing a certain guardian bug? =))

**Comment by Jenovas** [comment]
Yes it is a guardian, but the bug is more about writing a proper script for the guardian. To find it's owner give the buff, cast the spell, despawn in the right time, remove the buff.

**Comment by Bildo** [comment]
should work :D
-- Moonwell SAI
SET @ENTRY := 53883;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,54,0,100,0,0,0,0,0,11,100612,0,0,0,0,0,23,0,0,0,0,0,0,0,"Moonwell - On Just Summoned - Cast '<Spell not found!>'");

**Comment by anxanas** [comment]
Lol this dev stuff looks hard =)) GJ if you get it to work.

**Comment by Bildo** [comment]
it actually took me 15 secs to make it :D

**Comment by anxanas** [comment]
You are a titan amongst mere men

**Comment by Malylolek** [comment]
Bildo lie !

**Comment by Bildo** [comment]
fixed, sorry @Jenovas

**Comment by carrine** [comment]
still nothing

**Comment by Bildo** [comment]
wait for update

**Comment by anxanas** [comment]
Noice ty for fix =)))

**Comment by anxanas** [comment]
Works perfectly, just like it did on retail cant be used with other trinkets/engineer buff and buff is removed when you go 30 yards away from it. =))) gj

**Comment by fafal** [comment]
Yeah it works, but if u fast enough u can take more than 1 buff from trinket
