### ISSUE TITLE
[EN][Firelands] Ragnaros' Abilities

### ISSUE THREAD

**Issue by shandrios** [Atlantiss/BugTracker#5911]
Since about a week, Ragnaros' abilties haven't worked as they are supposed to. His Sulfuras Smash has several delays, with both the Smash marker and the waves from the smash are delayed by 3-5 seconds. He also sometimes casts Sulfuron smash, and then immediatly afterwards casts Hand of Ragnaros. Because of the delay on the smash and the lava waves, this can result in melee's getting knocked back right into the smash, which most likely kills them outright unless they're a tank

He also should never cast his Engulfing Flames at the same time as he casts Molten seeds, but that has happened multiple times, which messes up the stacking for the seeds.
 
Lastly, it seems like his intermission phase has a slight bug, where it spawns too many elementals close to the hammer. For example, if he smashes his hammer at the far right, it sohuldn't be possible to spawn 4 elementals on the right side of it, but that seems to happen very often.

All in all, i hope these issues are fixed as fast as possible, becuase they make the fight a lot more frustrating.

**Comment by Malylolek** [comment]
You forgot about it 
[22:42:44.254] Ragnaros Lava Bolt Beatit 45333 (O: 0)
[22:42:44.254] Ragnaros Lava Bolt Beatit 44272 (O: 0)

 Lova bolt should target only 1 target in time

**Comment by Glare** [comment]
What about meteors exploding on totems and/or pets?

**Comment by Aldergar** [comment]
#6031
