### ISSUE TITLE
[EN][GameObject] Maplewood Treasure Chest

### ISSUE THREAD

**Issue by kitvoid** [Atlantiss/BugTracker#5912]
http://www.wowhead.com/object=207520/maplewood-treasure-chest

There is a chest spawning in Durotar, in a subzone near Sen'jin Village called Northwatch Foothold. It should contain items appropriate to the level of the zone (in this case levels 1-10) but it drops rare (blue) Northrend items (levels 70-80). I've looted the chest about 5-6 times to make sure it wasn't an isolated incident and I got about 5 high level items and only 1 low level item. Please let me know you acknowledged this information and I will delete the items as soon as you do.

There's also 5 other types of chests:
- Silverbound Treasure Chest
- Dark Iron Treasure Chest
- Silken Treasure Chest
- Sturdy Treasure Chest
- Runestone Treasure Chest

I don't know if any of these spawn in low level areas and drop high level items because I haven't found any yet but a quick check of the database should confirm this for you.

I've reported this to the GMs but I've been told to post it on the bugtracker instead. I didn't want to do this because it becomes public knowledge and more people are going to abuse it but that's what the GM told me so that's what I'm going to do.

I suggest removing these chests (they probably spawn in other low level locations too) until you can get around to fixing the issue. And these players who camp the chests should be at least temporarily banned, it's not fair to others who play hours and hours to get gold and items the old fashioned legit way.

Thank you.

(You can see the chest in the first picture, the items that drop in the second and then people camping the chest in the other screenshots.)

![1](https://cloud.githubusercontent.com/assets/16279909/12355469/93f28e98-bba5-11e5-8724-47ce06d2375c.jpg)
![2](https://cloud.githubusercontent.com/assets/16279909/12355472/93f6154a-bba5-11e5-850a-bf6026a781e6.jpg)
![3](https://cloud.githubusercontent.com/assets/16279909/12355470/93f2e078-bba5-11e5-98f2-c3e496d9b0d9.jpg)
![4](https://cloud.githubusercontent.com/assets/16279909/12355473/93f6ec2c-bba5-11e5-9aeb-036008e584af.jpg)
![5](https://cloud.githubusercontent.com/assets/16279909/12355474/93f85cce-bba5-11e5-9160-1d1cde5c3532.jpg)
![6](https://cloud.githubusercontent.com/assets/16279909/12355471/93f5ee94-bba5-11e5-9f30-fb28d035b51e.jpg)

**Comment by artamedan** [comment]
The problem is not the chest- it can contain high level items in low level zones, as it was done by Blizzard in 4.03. The bug consists of SPAWNING time- it should be random from 12 to 24 hours. And here we have a 3 minutes spawning time.
The chests also give exp in Cata so it is obvious that people camp and farm them not only for easy money. The same spawning bug is all over the Azeroth in low level zones, for ally too.

**Comment by kitvoid** [comment]
Sorry to say but you are completely wrong there, artamedan. It CANNOT contain high level items in low level areas. It's you who haven't read the information on wowhead. And I played on retail during Cataclysm so I KNOW for a FACT that this is how it should work.

**Comment by artamedan** [comment]
Please, post a Blizzard statement link about the chest scaling the drop to the zone level.
Anyway, you put unnecessary screenshots here and much bla, bla, bla.. but NOT the most important things about the bug, that I have written.

**Comment by kitvoid** [comment]
Stop being such a child. Are you one of the people I caught in the screenshots? I don't need a fucking Blizzard statement, do you even listen to what you're saying? I played on retail during Cataclysm and these chests dropped LEVEL APPROPRIATE LOOT. You don't have to believe me, ask other people who played retail and you will see I'm right. In the meantime, please stop spamming this topic with your stupidity. Thank you.

**Comment by artamedan** [comment]
Stupidity and spamming is what you are doing by writing garbage and not the important things about the bug.
