### ISSUE TITLE
[PL][Achievement] Firelands

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5913]
Do achievement'a [Firelands](http://www.wowhead.com/zone=5723) i [Firelnds Guild Run](http://www.wowhead.com/achievement=5983) nie zalicza [Lorda Rhyolitha](http://www.wowhead.com/npc=52558) oraz [Ragnarosa](http://www.wowhead.com/npc=52409).
![image](https://cloud.githubusercontent.com/assets/4455568/12358922/010cbd0a-bbb0-11e5-9963-a27ca28406bf.png)

**Comment by Aviannaqt** [comment]
duplicate
