### ISSUE TITLE
[EN][Warlock] - Demonology Bugreport.

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#5914]
Some bugs that Demo warlocks forgot to report.

1. Talent Decimation in Demonology tree reduces cast time of Soul Fire with 60%, not 40%. The tooltip shows its 40% but its actually 60%. The bug is that instead of reducing the cast time of Soulfire BY 40% , it reduces it TO 40%. Link to talent - http://cata-shoot.tauri.hu/?spell=63158

2. Felguard pet can use abilities while doing Felstorm aka it keeps doing Legion Strike etc. Link to Felstorm - http://cata-shoot.tauri.hu/?spell=89751

3. Felguard ability Legion Strike doesnt spread damage when it hits more than 1 target but rather hits all targets with the full amout of damage. Link to ability - http://cata-shoot.tauri.hu/?spell=30213

**Comment by anxanas** [comment]
Bump =)))))))
https://github.com/Atlantiss/BugTracker/issues/5910
https://github.com/Atlantiss/BugTracker/issues/5669
https://github.com/Atlantiss/BugTracker/issues/5431
https://github.com/Atlantiss/BugTracker/issues/5365
https://github.com/Atlantiss/BugTracker/issues/3389

**Comment by Wolffenstein** [comment]
1. It's working fine, check your calculations.
2. Fixed in rev 4820.
3. Fixed in rev 4820.

**Comment by kadi2** [comment]
Indeed it's reducing soul fire cast by 60%, the tooltip shows wrong value.

**Comment by meowmewo** [comment]
Its not working fine. Dont watch the tooltip. Watch the cast time.

**Comment by anxanas** [comment]
It doesnt work just check videos of demo locks on retail their cast time is 1,5-1,6 depending on haste, here its 1,2-1,3 depending on haste.
