### ISSUE TITLE
[EN][Warlock][Spell] Death's Embrace

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#5916]
Drain Life / Drain Soul don't recive bonus from Death's Embrace talent, when your target is below 25% HP. Reproduced on 84 level dummy, other skills (Shadow Bolt, UA, Corruption, Agony) worked fine with the talent.
http://cata.openwow.com/spell=47200 // Death's Embrace

**Comment by BialyADI** [comment]
I tested it on my Warlock.
And i think that with Drains is some thing wrong.
My Drain Life Dmg is much higher than DrDamage show, mayby Death's Embrace work already on Drain Life regardless of target HP.

**Comment by kadi2** [comment]
Drain Life seems recive bonus damage from Death's Embrace regladless added points in that talent and regladless HP of the target.

**Comment by meowmewo** [comment]
Confirmed. Drain Soul doesnt get bonus from Death's Embrace.

**Comment by anxanas** [comment]
Bump

**Comment by meowmewo** [comment]
To reproduce. Make 2 Affliction specs. One spec with Death's Embrace, one spec without
Results: 
1.On both specs i get the same amount of dmg over 25% with Drain Soul - Deaths Embrace is not always active over 25%. So we can rule that out. 
2. Under 25% Drain soul does same dmg for both spec. - Bug Confirmed - Drain Soul doesnt Benefit from the talent Deaths Embrace. I
3. Deaths Embrace works on dots properly

In conculusion - Deaths Embrace doesnt affect Drain soul under 25% of boss health. - Bugged.

**Comment by meowmewo** [comment]
I the hopes of seeing this Wolfenstein. The fix u did on Soul Siphon + Drain Soul isnt full. It works for 2 dots, not 3. Aka it reaches 12% not 18.

**Comment by Wolffenstein** [comment]
Description: While at or below $47198s3% health, your Drain Life heals an additional $s1% of your total health.

It doesn't say anything about Drain SOUL.

**Comment by meowmewo** [comment]
Um mate?

**Comment by meowmewo** [comment]
Increases the damage done by your Shadow Spells by 12% when your target is at or below 25% health.

**Comment by kadi2** [comment]
Ya, sorry i should've specified the bug report is about second line of the talent: "Increases the damage done by your Shadow Spells by 12% when your target is at or below 25% health."

**Comment by meowmewo** [comment]
I cry in my pillow a lot lately cuz of this :(

**Comment by meowmewo** [comment]
Crying in the rain

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.

**Comment by Fearyourself** [comment]
Soul Siphon doesn't increase the damage of drain soul/drain life either

**Comment by meowmewo** [comment]
False. Soul Siphon was fixed and its working properly.

**Comment by BialyADI** [comment]
Yeah very properly https://github.com/Atlantiss/BugTracker/issues/6458.

**Comment by meowmewo** [comment]
Soul Siphon is WORKING. Death;s Embrace recent "fix" is why Drain Soul atm is doing milions of damage.

**Comment by meowmewo** [comment]
Maybe instead of trying to be sarcasticly smart @BialyADI, u should learn the affliction talents first.

**Comment by BialyADI** [comment]
That talent increase Dmg Every Tick so it is buged.

**Comment by meowmewo** [comment]
@Fearyourself  was talking about Soul Siphon talent, not Death's Embrace.
