### ISSUE TITLE
[EN]Arena cap increase with rating doesn't work

### ISSUE THREAD

**Issue by Reportingstuff** [Atlantiss/BugTracker#5917]
Seems like arena rating/cap calculation doesn't work anymore.I can't find proper links for calculator for it,but this image is one I used for long time,and seems accurate for this patch.

http://imgur.com/a/q94uW

**Comment by Aviannaqt** [comment]
its blizzlike, fixed yesterday

**Comment by Reportingstuff** [comment]
Nop it's not fixed,you can check it yourself.Rating doesn't increase cap anymore,before you remove such important stuff please do your homework

**Comment by Aviannaqt** [comment]
#1152
Your Maximum Conquest Cap should be recalculated only once per week, not every relog like on main.
