### ISSUE TITLE
[EN][Warlock][Talent] - Decimation

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#5918]
Talent Decimation in Demonology tree reduces cast time of Soul Fire with 60%, not 40%. The tooltip shows its 40% but its actually 60%. 

THE BUG is that instead of reducing the cast time of Soulfire BY 40% , it reduces it TO 40%. Link to talent - http://cata-shoot.tauri.hu/?spell=63158

With me when Decimation is active the tooltip shows 1.51 cast time, but the actual cast time is 1.2 sec.

**Comment by anxanas** [comment]
Bump

**Comment by xolon** [comment]
Confirmed

**Comment by aneq** [comment]
supposedly fixed in rev 4882
@Aviannaqt do zamknięcia

**Comment by Bastek** [comment]
Fixed in rev. 4882
