### ISSUE TITLE
[PL][Spell][Warrior] Charge - WSG BG.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#5919]
Intercept -> http://cata.openwow.com/spell=20252
Charge -> http://cata.openwow.com/spell=100

Wiem że bug jest znany, ale jest w tym coś dziwnego w jednej lokacji mogę normalnie dać charge w innej nie a jeszcze w innej wpadam pod podłogę...

Tym razem na całym WSG nie można było dać charge.

SS:
![wowscrnshot_011616_115637](https://cloud.githubusercontent.com/assets/5780624/12372045/32fd7df6-bc49-11e5-8f9a-9eece44086f0.jpg)

![wowscrnshot_011616_115646](https://cloud.githubusercontent.com/assets/5780624/12372046/3668eb4c-bc49-11e5-8229-fac632d5c773.jpg)

**Comment by Aviannaqt** [comment]
hehe rekt xd

**Comment by BialyADI** [comment]
No siema :D. :+1:
