### ISSUE TITLE
Node issues at NR

### ISSUE THREAD

**Issue by sarar225** [Atlantiss/BugTracker#5921]
Hello,
I was trying lvlup my mining at NR where i came across some bugs regarding the mining nodes.
I will try to put the problems in simple ways.
1. There were Nodes underground, in other words i could see them in my mini map but couldn't see it in my screen and this problem happened all over NR. ( The amount of bugged Node's is approx 40-45% , Extra 5% give or take. ) and yes i have checked if there was any way to go underground just in case. 
2. There were less Nodes & I couldn't find titanium vin even after searching for 40+ min. Also the amount of nodes for saronite ore was about 40% including a 15+ re-spawning time. 

P.S. I have played on retail so I'm really confident about saying about the amount of nodes that can be found and the spawning time.

Leonaa.

Here are some Screenshot about the bugged Nodes.
![wowscrnshot_011616_182211](https://cloud.githubusercontent.com/assets/16732815/12372432/efb8b51e-bc80-11e5-941b-e3589515352d.jpg)
![wowscrnshot_011616_182239](https://cloud.githubusercontent.com/assets/16732815/12372431/efb85c90-bc80-11e5-8709-af87cae0ea92.jpg)
![wowscrnshot_011616_182453](https://cloud.githubusercontent.com/assets/16732815/12372430/efb6d4b0-bc80-11e5-9f08-d705ef49496f.jpg)

**Comment by Thefakemccoy** [comment]
Fix Title.
