### ISSUE TITLE
[EN][Warlock][Spell] Incinerate not benefiting for immolate

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5924]
I know this is a duplicate https://github.com/Atlantiss/BugTracker/issues/4814. But i feel like if i put this in the old thread it wont be seen. 
Incinerate doesnt benefit from immolate on target the damage doesnt change, also if you have the DR damage addon you will see that when you put immolate on the target the expected damage of incinerate is higher. But when you cast it the damage is the same as an incinerate without immolate on.
http://www.wowhead.com/spell=29722/incinerate
http://www.wowhead.com/spell=348/immolate
This bug greatly reduces destro damage(thats why noone plays destro) and also the damage of incinerate focused demo warlocks and to some degree shadow bolt focused demo warlocks. Another proof that it is bugged is that when boss is >25% and molten core procs its a dps loss to use incinerate instead of soul fire on this server eventhough it was a dps increase on retail.

PS tyvm for all the recent fixes =))))

**Comment by Wolffenstein** [comment]
Fixed in rev 4822.

**Comment by anxanas** [comment]
How do you fix things so quickly =))) tyvm

**Comment by meowmewo** [comment]
ty for the fixes.
