### ISSUE TITLE
[EN][Quests][Molten Front]Into the Fire(ID 29206) and The Forlorn Spire(ID 29205)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5926]
Quests right now can be both obtained and completed the same day each day but when you have in log or you have completed one of them each day the other one should not be available.

Proof: [Comments(The Forlorn Spire)](http://www.wowhead.com/quest=29205/the-forlorn-spire#comments:id=1883868) and [Comments(Into the Fire)](http://www.wowhead.com/quest=29206/into-the-fire#comments:id=1461218:reply=255117)

Wowhead Links: [The Forlorn Spire](http://www.wowhead.com/quest=29205/the-forlorn-spire) and [Into the Fire](http://www.wowhead.com/quest=29206/into-the-fire)

Note: If i find better proofs i will update it but now only wowhead comments and my addon are the proofs i have.

**Comment by Thefakemccoy** [comment]
http://www.wowhead.com/guide=58/a-guide-to-the-molten-front-and-respective-quests#molten-front-sections-additional-supplies

**Comment by Aival94** [comment]
Ty for the comment..have not checked this part of the guide to see if it say anything :)

**Comment by Piklo** [comment]
#5727

**Comment by Aival94** [comment]
I know this bug is related to #5727 but is not the same bug. This one is only minor bug about them being able to be done at the same day without any prerequisites quests.
