### ISSUE TITLE
[EN][Quest][Molten Front][Visual-Minor] Steal Magmolias(ID 29257)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5928]
Quest is working just fine but the [Lava Burster](http://www.wowhead.com/npc=53090/lava-burster) has 2 quest credits showing in their tooltips.

![wowscrnshot_011116_161521](https://cloud.githubusercontent.com/assets/10282971/12372935/d7f3fc28-bc70-11e5-9105-e0501431e096.jpg)

Wowhead Link: [Steal Magmolias](http://www.wowhead.com/quest=29257/steal-magmolias)

**Comment by TranceAccount** [comment]
Rev 5541.
