### ISSUE TITLE
[EN][NPC][Molten Front]Emberspit Scorpion(ID 53240)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5934]
NPC has a strange %d rage in its tooltip.

![wowscrnshot_011416_231217](https://cloud.githubusercontent.com/assets/10282971/12373016/c74f4e92-bc73-11e5-9ba4-17494a687aa0.jpg)

Furthermore it cannot be skinned.

Wowhead Link: [Emberspit Scorpion](http://www.wowhead.com/npc=53240/emberspit-scorpion)

**Comment by TranceAccount** [comment]
The creature is skinnable, only the %d rage problem still exists.

**Comment by Aival94** [comment]
I think someone fixed the skinning. Will check it and update the post.

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
