### ISSUE TITLE
[EN][NPC][ICC10HC/NORMAL] Deathbringer Saurfang

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#5935]
impossible to kill him and move on due to auto resetting
http://cata.openwow.com/npc=37813

**Comment by sunshitwowsucks** [comment]
confirmed

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
BUMP

**Comment by Darkrefugee** [comment]
Any dps done to him just resets him, no possible way to move on past him or kill him. Last tried on februari 28th, 2016

**Comment by debtheone** [comment]
bump

**Comment by avalancze23** [comment]
bump

**Comment by 1Andas** [comment]
Confirmed.

**Comment by raduriel** [comment]
Confirmed

**Comment by jissabraham** [comment]
plz fix like flame in Uldam

**Comment by pepe19** [comment]
pls repair that we wait four months :(

**Comment by Aequitass** [comment]
bump

**Comment by Kubelecer** [comment]
Apparently fixed http://atlantiss.eu/changelog#rev5051
