### ISSUE TITLE
[EN][Spell][Druid Flight Form] slow flight form deleted altogether? 

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#5937]
so, revision 4818 was supposed to remove slow flight form from druid's hotbars when they learn swift flight form (Once the Druid learns Swift Fly Form the normal Fly Form will no longer be visible in the stance bar)

instead, it seems all slow flight forms have been removed altogether. From players with, and without swift flight form

I don't really care about my slow flight form as I have the swift version and it's prettier, but this is a major issue for the people that haven't gotten swift flight yet, and now can't fly without having to buy a mount

**Comment by Thefakemccoy** [comment]
Most people I have heard from have swift flight form which means they learned that spell from the trainer and never learned past 150% flying


Which means it sees they have swift flight form learned there for removes flight form

**Comment by Thefakemccoy** [comment]
Flight form should be learned at lvl 60 and only be usable with 150% flight.
If the player learns the next flying skill which is 280% flight form should stay and still only scale to 150%
Allowing the druid to mount a normal flying mount to fly at 280%
Once the druid trains swift flight form from the class trainer it should over write flight form
**Here is the issue alot of people learned swift flight form prior to fix which should require the 280% flight riding before you can learn this spell.**

**Comment by anxanas** [comment]
They can begin using 1,5 secs to mount up like the rest of us, damn druids =))

**Comment by Thefakemccoy** [comment]
I have 310 flying so im ok

**Comment by DuGalle** [comment]
Still nothing i have a swift from witch i cant use coz my druid is poor and lack money for big flying and i dont have normal form soo basically i cant fly even with 15o fly and 150 more for fly license that sux :X

**Comment by Thefakemccoy** [comment]
Buy a gryphon

**Comment by Luna-maria** [comment]
-.- that is not a proper solution

**Comment by DuGalle** [comment]
To buy a mount when you are a druid is just wrong :X

**Comment by MelquiadesUBI** [comment]
well i bought a gryphone but the hole point of a druid is to be able change form quick and simple. Plz let someone fix this.

**Comment by DuGalle** [comment]
A major issue with no clear solution after all this time my fate in the team is growing weaker by the day ...
