### ISSUE TITLE
[EN][Item] Flintlocke's Woodchucker

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#5938]
This enchant should have 40 sec icd.
Right now, but I'm not 100% sure it doesn't have icd at all. ( i believe i saw a buff from proc re-apply iteself today )

http://www.wowhead.com/item=70139/flintlockes-woodchucker#comments:id=1473777

**Comment by anxanas** [comment]
Confirmed, it has no icd i had close to a 80% uptime, its basicly an almost static 300 agility increase, nerf hunters please =)))

**Comment by Bildo** [comment]
fixed
