### ISSUE TITLE
[EN][Spell][Mage] Cone of Cold targets behind you

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#594]
http://cata.openwow.com/spell=120

As we can see on this video: https://www.youtube.com/watch?v=N7JWFBNijDE (starts at 0:43) if you are standing a little in front of enemy you should be able Cone of Cold them.
Unfortunatelly you cannot do that on our server (on PTR), i tried in the same place in Stormwind but i didn't make it, i couldn't even attack target dummy like guy on above video.
This is my video, showing how it (doesn't) works on PTR: https://www.youtube.com/watch?v=lLUs9-K-wTM

I don't know what's the reason, radius of Cone of Cold? Or maybe it some mechanic which can't be transported on private server? Or maybe i'm doing it wrong?

**Comment by kadi2** [comment]
There are 2 options:
1.Cone of Cold was considering targets if it hitted somewhere in the hitbox, even if it didn't hit the center of the target.
2.There was an offset for Cone of Cold "the cone" radius so it was possible to hit targets behind the caster.

**Comment by blinkmaster** [comment]
working as intended, best checkd on targets with large hit box.
can be closed
@Aviannaqt
