### ISSUE TITLE
[EN] [Quest] [Secrets of the Tower] Quest wont work

### ISSUE THREAD

**Issue by Chasstastic** [Atlantiss/BugTracker#5943]
First of all.

Agent Kearnen isnt shooting the Mercs as she is meant to. This is one problem with the quest.
Secondly, more related to Westfall, there shouldnt be a Wind thing infront of the Tower.

Onto the quest again, the invisibilty potion doesnt work as it should. It's meant to automatically go onto you, it doesnt, only going onto you if you target yourself and not in combat.

Thirdly, when you go up to the top of the tower, the conversation that SHOULD take place....doesn't!

I find this irritating as before Sunwell was added, and other things. This quest worked fine for me.

How do I fix this?

Quest link: http://www.wowhead.com/quest=26290/secrets-of-the-tower

**Comment by Aival94** [comment]
Reported 1 thousand times.
Read comments for a solution: https://github.com/Atlantiss/BugTracker/issues/2338

**Comment by Chasstastic** [comment]
Aival94, none of those work. I've checked and tried each one. NOTHING. It's Just not working. The conversation doesnt happen

**Comment by Chasstastic** [comment]
Now there's mercenaries INSIDE the tower when the potion is active. WHY IS THIS SERVER TURNED SO BUGGY FFS

**Comment by Chasstastic** [comment]
Why close? THIS IS AN ISSUE THAT NEEDS TO BE RESOLVED FOR FUCKS SAKE
