### ISSUE TITLE
[PL] [Web] [Account] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null

### ISSUE THREAD

**Issue by kjmpp** [Atlantiss/BugTracker#5944]
Witam!

Kiedy loguję się na stronie Atlantiss, wita mnie napis tj. w tytule:
![atlantiss_login_error_small](https://cloud.githubusercontent.com/assets/16562793/12377812/94ffab46-bd2a-11e5-972e-47f54b7a4c31.png)

W Shop Panelu mogę jedynie kupić punkty, zagłosować i sprawdzić historię/itemy, ale poza tym nie widzę żadnych przedmiotów do kupienia oraz ilości jakichkolwiek punktów mimo, że mam kupionych parę punktów premium oraz kilka zdobytych za vote. Teraz ponadto mam problem również z transferami z sunwella, konto połączyłem, ale nic nie widzę gdy wchodzę w tę opcję.

Poniżej screen ze sklepu:
![atlantiss_no_items_2_small](https://cloud.githubusercontent.com/assets/16562793/12377821/aaa13dca-bd2a-11e5-9e75-fa2688585134.png)

Konto było zakładane wieki temu, może to przez to?
Do naprawy tego błędu będą pewnie potrzebne szczegółowe dane...

EDIT:
Zapomniałem dodać, że e-mail w informacji o koncie po zalogowaniu się na stronie widnieje normalnie. Poza tymi usterkami konto w samej grze oraz postacie działają prawidłowo.

**Comment by wolfager** [comment]
Mam to samo. Co zrobic? Da sie cokolwiek ??

**Comment by kjmpp** [comment]
Możemy jedynie czekać cierpliwie... a chętnie bym coś kupił w tym sklepiku, niestety nawet nie wiem co i za ile.

**Comment by kjmpp** [comment]
Działa jak trzeba. Skoro nie ma żadnych dalszych uwag to zamykam...
