### ISSUE TITLE
[PL][Vendor][Molten Front] Varlan Highbough

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5948]
http://www.wowhead.com/npc=53882
Nie sprzedaje
[Lancer's Greaves](http://www.wowhead.com/item=70123)
![image](https://cloud.githubusercontent.com/assets/4455568/12378277/31823c3c-bd39-11e5-9e7a-9b2601c2ef62.png)

[Relic of Torolla](http://www.wowhead.com/item=70128)
![image](https://cloud.githubusercontent.com/assets/4455568/12378279/3d7a9ac0-bd39-11e5-9556-18a970588786.png)

[Relic of Lo'Gosh](http://www.wowhead.com/item=70125)
![image](https://cloud.githubusercontent.com/assets/4455568/12378283/45c4c7fa-bd39-11e5-92f0-c292d955abbf.png)

![image](https://cloud.githubusercontent.com/assets/4455568/12378285/4bded3e2-bd39-11e5-8b42-35086b1978c5.png)

**Comment by Thefakemccoy** [comment]
this was fixed with https://github.com/Atlantiss/BugTracker/issues/5860
