### ISSUE TITLE
Three little pygmies BUG

### ISSUE THREAD

**Issue by Lukas727** [Atlantiss/BugTracker#5955]
During this mission I have to kill 3 different pygmies and killed the second and third, and first I did not notice so I went back to the place where he was first and I killed him but does not reckoned this to me to task on the map shows me that this is a different place than the reborn third I have killed again, third and second.I restarted the game and it did not work so I do not know what I can do, please some help.
Sorry for bad English
Server:Atlantiss
Nick Lukas727

**Comment by Bildo** [comment]
read bt rules
