### ISSUE TITLE
[EN][Hunter][Spell] Deterrence

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#5958]
Warrior charge\intercept stuns, heroic throw silence, hunter silencing shot and god knows what else still bypass deterrence while it should give complete immunity to _everything_.

**Comment by xolon** [comment]
Proof for charge/intercept https://youtu.be/36p24AUfkzw?t=44s
Gonna search for more soon, but yea loads of spells bypass deterrence here

**Comment by BialyADI** [comment]
DK if use Chain of Ice on you while Deterrence you will have Frost Fever and slow drom Child Binds ^^.

**Comment by Crusaderz** [comment]
Wind shear interrupts casts (like scare beast) during Deterrence. Isn't this great?

**Comment by lamaATS** [comment]
Fixed in rev. 5232
Warrior's **Charge** has been fixed.
Warrior's **Intercept** was working properly.
Warrior's **Heroic Throw** was working properly.
Interrupts: Patch 4.1 `All non-damaging interrupts off the global cooldown will now always hit the target`
