### ISSUE TITLE
[EN][NPC][Molten Front]Anren Shadowseeker

### ISSUE THREAD

**Issue by Fadogar** [Atlantiss/BugTracker#5960]
There appears to be a phasing issue involving this NPC affecting players that completed The Shadow Wardens faction quest before completing The Druid of the Talon faction quest.The issue causes Anren to appear near the entrance of the Molten Flow (a position he should only appear only after the completion of the quest [Need... Water... Badly...]) rather than his correct position near the end of the Molten Flow.This issue is also causing the quest [Need... Water... Badly...] to be completely unavaliable as a result.This is unfortunately robbing those who began with Shadow Wardens of an additional set of dailies and the Achievement [The Molten Front Offensive].

**Comment by Raknar** [comment]
That's not true, We know about Anren position at start, but still [Need... Water... Badly...] is avaliable to take and finish like 1553 people did. He stays in cave below Molten Front after you finish quest Into The Fire and Thisalee Crow dailies.
