### ISSUE TITLE
[EN][Hunter][Spell][Talent] Freezing trap and Lock and Load proc

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#5962]
Probably starting the day this issue is created, I began to notice that Freezing Trap now grants no Lock and Load proc, whether it is an enemy player on a bg, or a common mob somewhere out in the world.  The target just gets frozen and nothing else happens. Also, Ice Trap still procs LnL as it should do, but somehow lacks the sound effect of the proc.

**Comment by Wolffenstein** [comment]
Fixed in rev 4825.
