### ISSUE TITLE
lock and load

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#5963]

**Comment by Shanrolol** [comment]
Probably starting the day this issue is created, I began to notice that Freezing Trap now grants no Lock and Load proc, whether it is an enemy player on a bg, or a common mob somewhere out in the world. The target just gets frozen and nothing else happens. Also, Ice Trap still procs LnL as it should do, but somehow lacks the sound effect of the proc. 

A dude read it and gave a straight answer that this issue is fixed, but in fact it is not.
If it was once fixed, then its UP again!

**Comment by Wolffenstein** [comment]
It will be fixed in revision 4826, it's not live yet.

**Comment by Shanrolol** [comment]
Oh well, now I got u, thanks.
