### ISSUE TITLE
[PL][ITEM][Transfer] Reins of the Crimson Deathcharger

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#5965]
http://www.wowhead.com/item=52200/reins-of-the-crimson-deathcharger
Przetransferowane postacie z sunwella, które miały tego mounta na owym serwerze dostają go też na ATS (gdzie u nas nie da się go zdobyć) i to w postaci do użycia (można go wtedy komuś sprzedać).

**Comment by Beatit** [comment]
Roman [*]

**Comment by Lebiedz** [comment]
Ja nie widzę w tym problemu, gdyż crimson deathchargera POWINNO dać się zdobyć, gdyby ICC działało poprawnie. W związku z czym item istnieje na serwerze, a brak możliwości zdobycia tego itemu wynika z bugów, a nie z tego z planowanego działania.
Poza tym, brzmi to jak zazdrość? :)

**Comment by Nc94** [comment]
"Other achievements which are not available to achieve on our server have been deleted, we reserve the right for further cassation if we skipped through any other achievement by mistake."
http://atlantiss.eu/news/view/180

To samo tyczy się mountów i achievementów za Glory Icecrown Citadel 10/25

**Comment by Lebiedz** [comment]
Wydaje mi się, że po prostu inaczej rozumiemy przytoczony przez Ciebie zapis. Wg mnie oznacza to, że zostanie usunięte to co jest niedostępne do zdobycia w dodatku cata, bo zostało usunięte przez blizzard. Jeśli admini mieli na myśli rzeczy nieosiągalne wskutek nieprawidłowego działania odpowiednich questów i innego contentu, wtedy oczywiście masz rację.

**Comment by Nc94** [comment]
Kilkanaście razy było pisane (na forum/grze), że achi/mounty niedostępne na ats będą kasowane, a w przypadku gdyby coś zostało pominięte żeby to zgłosić.

**Comment by Lebiedz** [comment]
Tylko że nadal nie wspomniałeś jaka miała być przyczyna owej niedostępności - bugi czy usunięcie danych osiągnięć przez Blizzard w cata. Jest to pewna różnica, bo jeśli dany przedmiot i powiązany z nim achievement (np. Shadowmourne) jest chwilowo nieosiągalny (bo w przyszłości, miejmy nadzieję, zostanie to naprawione) to nie znaczy, że go nie ma w ogóle. Rozumiem usunięcie osiągnięć związanych z np. questami w eastern kingdoms i kalimdorze - w wotlk były one zebrane do kupy w achievach dotyczących danego kontynentu, a w cata zostały dodane achievy dla każdej lokacji z osoba zamiast poprzednich. Jednak usunięcie achievementów za Shadowmourne w momencie gdy jest on nieosiągalny wskutek bugów i niedopracowania contentu, nie wydaje mi się sprawiedliwe.

**Comment by Zhalox123** [comment]
Confirmed bought also cant mount up xD

**Comment by Nc94** [comment]
This topic isn't about not being able to mount on it but about that you shouldn't be able to receive it on ATS and that transfered characters from sunwell have them (when they shouldn't) and selling them to other players.
