### ISSUE TITLE
[EN][Instance]Shadowfang Keep

### ISSUE THREAD

**Issue by mzn928** [Atlantiss/BugTracker#5966]
So today i was doing rhc and i got sfk.all things worked ok and we killed the first boss
then after that we went upstairs to wait for the npc to open the door.but npc didnt appear
instead all the mobs in the yard got aggro on us somehow. as you can see in the picture below we killed mindless horror mobs. and no i didnt pull them with my pet.i think one of the recent updates caused this issue and i dont know if it happens all the time or it was just a one time thing.anyway i decided to report it here

![](https://i.imgur.com/gVbrfZL.jpg)

**Comment by Aviannaqt** [comment]
duplicate
