### ISSUE TITLE
[EN] [Dungeon] Magister's Terrace HC

### ISSUE THREAD

**Issue by Simgiov** [Atlantiss/BugTracker#5967]
Can't enter as a level 85 in the HC version. The normal works.
Screenshot (look at the chat message): http://i.imgur.com/Nndln2i.jpg

**Comment by Bastion** [comment]
go complete quest

**Comment by LaveniaGithub** [comment]
You need to complete prerequisite. It's working.

**Comment by Simgiov** [comment]
Then the chat message is wrong and needs a fix.

**Comment by Navedonar** [comment]
Patch 4.2.0 (2011-06-28): Completion of N [70D] Hard to Kill is no longer required for Heroic Mode.

**Comment by Aival94** [comment]
I believe this one has all the Magister's Terrace bugs including the wrong requirement.
https://github.com/Atlantiss/BugTracker/issues/572
