### ISSUE TITLE
[EN][Spell][Pet][Warlock] Shadow Bite

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#5968]
Hi i have noticed that shadow bite does somewhat lower damage than i have seen it do in videos, could just be me that is retarded =)))
http://cata.openwow.com/?spell=54049
According to Drdamage the damage should be higher, but i know that you dont take that or simcraft as proof, so i found this: "Bite the enemy, causing [M1+(1.228*(SP*0.5))] Shadow damage plus an additional 30% damage for each of your damage over time effects on the target." I wanted to calculate it but i am somewhat of a retard and i got no idea what M1 means, so i was wondering if anyone could test it for both affliction and demo, if not then please tell me what M1 means and ill give math a try. =))

My pets spell damage is 5885 and mastery is 39% if anyone wanna give it a try =))

**Comment by Lanrutcon** [comment]
After a few searches:
http://www.arenajunkies.com/topic/239504-demonic-breath-vs-mortal-coil-shadowfury/#entry3917590

Formula: *(142 + (1.228 * (SP * 0.5)))*

The post was created in MoP "season", still I think the formula is correct because in Patch 4.1:
*"Shadow Bite now scales from 61.4% of Spell power, up from 30.7%."*
http://eu.battle.net/wow/en/forum/topic/1776591660

Making the simple math: 61.4% = 1.228*0.5

**Comment by anxanas** [comment]
Tyvm ill do the math when i am less tired =))

**Comment by anxanas** [comment]
I am actually having some troubles calculating it since my pets SP value keeps changing once it was 18k+ now its 2k before that it was 8k, anyone else has this problem? It seems to only be a visual bug since the damage remains unchanged.

**Comment by anxanas** [comment]
I have been unable to calculate the damage my shadowbite should do cause of a very werid bug with pets visual spell damage changing, though i am sure that there is a bug, just looking at demo warlocks shadow bite from world of logs.
http://www.worldoflogs.com/reports/dhd07huwpmrkdqu2/details/87/?s=3434&e=3575 his average shadow bite crit was 65108.1, with a dps of 30k(Which is fairly normal on baleroc, so he we can assume he isnt overly geared or has some crazy rng)
My average shadow bite crit is around 40k and the highest i have ever achived is 73k at the start of the fight with potion procs and moonwell trinket.

Looking through other parses of world of logs from firelands will show that shadow bite did a lot more than on retail than it does here. I can try to calculate how much it should do by finding the felhunters base spelldamage and add it to how much benefit it should get from my SP but i have been unable to find the base spelldamage or the spell power gain from master to pet. If anyone is aware of this or know a website please inform me in this thread or /w me in game on fellord or wankypanky

**Comment by Illusie** [comment]
thank you both,
hope to see some Warlock fix in near future ;d

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
