### ISSUE TITLE
[EN][Spell][Priest] Penance

### ISSUE THREAD

**Issue by Kaldros** [Atlantiss/BugTracker#5970]
There is an issue with the third tick of Penance not landing.The bug is that the third tick of it just doesn't land sometimes. It's around once every 4 to 5 casts but considering that Penance is a very important healing spell for Discipline Priests, it is a rather big problem.

I hope you fix this promptly, since it is a serious issue affecting both PvP and PvE.

**Comment by anxanas** [comment]
https://github.com/Atlantiss/BugTracker/issues/4852
