### ISSUE TITLE
[EN][Quest][Moten Core]Attunement to the Core

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#5971]
http://www.wowhead.com/quest=7848/attunement-to-the-core

As soon as you get the quest it auto fail thus far you cant get the core fragment and have easy entrance to the core. Each time you retake the quest it auto fail

**Comment by Thefakemccoy** [comment]
I have not seen this npc in game. Howerver the window to the left facing that guy will take you to MC.

**Comment by DuGalle** [comment]
The NPC show to one of my Alts before i post this but after i have kiled ranga ranga once mby its related

**Comment by Bildo** [comment]
fixed
