### ISSUE TITLE
[EN][Rogue][Druid][Combo points] Combo points remain after arena or combat.

### ISSUE THREAD

**Issue by fizzle7** [Atlantiss/BugTracker#5973]
Combo points from rogue or druid remain on the last target you had them on after arena. Possibly after combat in bgs, but cannot confirm that as I haven't tested it. They do reset after duels though. Even if you go back into arena vs the same player, you still have them, which obviously is a HUGE imbalance and advantage. 

How it should work:
Points should reset to 0 after leaving arena on any player you had them before that.

Proof:
If you want to read this http://us.battle.net/wow/en/forum/topic/18706672633, be my guest, I'm tired of looking for proof for everything all day long cause I couldn't find anything except that, and the posters can't even agree on how it works, so yeah. But definitely they shouldn't stay in arenas.

**Comment by BialyADI** [comment]
So if you leave arena and enemy heave 5 Combo point you cant start on him for example with full Kidney Shot?
GG, and fix lags plz :<.

**Comment by fizzle7** [comment]
Just had this happen vs hunter/ret paladin where I still had 5 combo points on the ret paladin before even opening on him from stealth.

**Comment by fizzle7** [comment]
Yet another case vs a disc priest, I can start screenshotting and compressing the folder cause it would get pretty big.

**Comment by phifedawg** [comment]
This happens in general after an enemy dies with combo points remaining on him. It happens as well on world pvp, bgs etc..

**Comment by Pankaa** [comment]
bump.

Spoko boost dla klas grających z cp...

**Comment by Jenovas** [comment]
Fixed in rev 4965
