### ISSUE TITLE
[EN][ITEM][Vendor]Insignia of the Alliance

### ISSUE THREAD

**Issue by micha666** [Atlantiss/BugTracker#5974]
Insignia of the Alliance for mages should be obtainable from both npc's 
http://www.wowhead.com/npc=12805/officer-areyn
http://www.wowhead.com/npc=12785/sergeant-major-clate
I can't find officer areyn and i can't buy it from major Clate. 

My friend can buy warrior version.

Link to the item(This is the no lvl required version):
http://www.wowhead.com/item=18859/insignia-of-the-alliance

I also suggest checking it for other classes. Kind of disadvantage when playing PvP on lower levels.

**Comment by artamedan** [comment]
Who would WASTE TIME to play PvP on lower levels? Just level fast to 85 and START REAL PLAYING, baby.
There are many more important issues to bother developers with this stupid thing.

**Comment by micha666** [comment]
Your comment is not appropriate. It is the fact that this is a bug. It can be marked low priority. This is one of the great trinkets for twinks. If you have nothing to do but hating someone who tries to help server please don't write anything. You didn't helped at all with this useless post.(In truth that is one of the stupidest anwsers on bug taracker i have seen in my life).

**Comment by Birdseye123** [comment]
Fix Plz.








Screw off @artamedan

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
