### ISSUE TITLE
[EN][Rogue][Combat][Talent] Bandit's Guile Not Working at All

### ISSUE THREAD

**Issue by purabasura666** [Atlantiss/BugTracker#5975]
Rogue - Combat Spec - Talent - Bandit's Guile

The talent isn't working at all, at least at my level, 65. It does nothing. It shows no debuff on the target, under any circumstances. Not with 1/3, not with 3/3.

There is a related ticket, https://github.com/Atlantiss/BugTracker/issues/2147, which mentions that the talent doesn't work properly under some circumstances. What I am reporting there is that it never works.

This is a huge DPS loss, of up to 30%, for combat rogues.

Asked in world chat, a couple of rogues confirmed that it wasn't working for them, either, and that the combat spec is not suitable for endgame in its current state :(

**Comment by kadi2** [comment]
It's supposed to give butt to the rogue, not debuff to the enemy. Make sure you didn't misunderstood the spell mechanic.

**Comment by Jenovas** [comment]
The talent works properly. The rogue gets a buff that increases his DMG.

**Comment by purabasura666** [comment]
Ah, thanks so much for the clarifications, kadi2 and Jenovas. I'll check it out again next time I play my rogue.
