### ISSUE TITLE
[EN][Battlegrounds] Can not change Specializaton when the timer is ticking still!

### ISSUE THREAD

**Issue by PARANOiA32** [Atlantiss/BugTracker#5976]
It is annoying as hell! On blizzard servers, you can still change specs as much as you want to before the countdown goes to 0 and battle acutally starts, no matter the battleground! Fix please.
http://www.mmo-champion.com/threads/787793-Changing-specs-in-bg-s

**Comment by Ervzz** [comment]
Agreed. Super annoying when you wanna change to healer because there isn't any in the BG.

**Comment by Aviannaqt** [comment]
#1922
