### ISSUE TITLE
[EN][Profession][Engineering] Spinal Healing Injector

### ISSUE THREAD

**Issue by Larcan** [Atlantiss/BugTracker#5980]
Permanently attaches a specialized injector kit to your belt, allowing you to heal yourself for 62900 to 73100 every minute.  Shares a cooldown with potions.

Requires an Engineering skill of 450 or higher to operate.

So when you use it works fine and heals for 30k, but problem comes when you use it will get stuck (cooldown doesn't start) till you do relog.

![wowscrnshot_012016_152412](https://cloud.githubusercontent.com/assets/16437818/12451494/161fbfe8-bf8a-11e5-8df2-61588abcb02e.jpg) Before Spinal Healing Injector is used.

![wowscrnshot_012016_152421](https://cloud.githubusercontent.com/assets/16437818/12451513/309c585e-bf8a-11e5-9e25-1b0ae7c67f33.jpg) After Spinal Healing Injector is used.

**Comment by Fapguy** [comment]
pretty important....
makes engi kinda weak for some tanks

**Comment by muzak00** [comment]
First of all it's attached to your gloves. Second of all you should need a Mythical Healing Poiton to even use this tinker. If you have Mythical Healing Potions in your bags it works just fine.

**Comment by Fapguy** [comment]
First of all, whether it attaches to gloves or belt is irrelevant as the devs will just look at the tooltip, he made a typo, whatever.

Second of all, you don't need any potions for this to work.
Don't post bullshit.

**Comment by Wantuno** [comment]
This renders the tinker useless for tanks, basically you can only use it once per raid unless you relog after every use, just imagine a low geared tank relogging after every trash pull. Or even in pvp, after every fight you need to relog, making it only usable once per battleground. And as Fapguy said, you never needed to have potions in your bags, not even in retail.

**Comment by muzak00** [comment]
edit: checked again just to be sure, its bugged like hell you guys are right.

**Comment by xolon** [comment]
It bugs cd on every pot you have aswell

**Comment by Fapguy** [comment]
wow, really....

**Comment by ShockRW** [comment]
BUMP
