### ISSUE TITLE
[PL][Item] Warrior 2p t12 dps bonus

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#5981]
Jeśli rzuci się shouta tylko sobie buffek wchodzi normalnie na 12 sec (Booming Voice 0/2), lecz jeżeli mamy kogoś w pt / przyzwiemy peta (skarabeusze z archeo np) i jemu także rzucimy shouta to wtedy buffek wchodzi na 6 sec.

http://www.wowhead.com/spell=99234/item-warrior-t12-dps-2p-bonus

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
