### ISSUE TITLE
[PL][QUEST] Missing In Action - lokacja startowa gnomów

### ISSUE THREAD

**Issue by Therenir** [Atlantiss/BugTracker#5982]
http://www.wowhead.com/quest=26284/missing-in-action

Z wszystkich klatek respi się tylko jedna, co skutecznie blokuje startowy chain dla w/w rasy

edit. na chwilę obecną ostatnia klatka również przestała się respić co całkowicie blokuje ukończxenie lokacji startowej.

**Comment by apsiq** [comment]
Jak zrestartują serwer to klatki będą działały normalnie...tylko jacyś debile regularnie je bugują po przez otwieranie klatek gdy nie ma w nich gnomów do questa przez co gnom się respi w otwartej klatce i nie można go z niej uratować, dzisiaj po restarcie serwera wszystko było okey minęły bodajże 4 godziny i znowu wszystkie klatki zbugowane przez jakichś przygłupów. Jedyne co pozostaje to liczyć na  kolejny restart serwera a twórcy mogliby jakoś temu zapobiec nie wiem dodając do questa informacje o tym czy coś...

**Comment by Larousene** [comment]
Bump! Mam to samo w tej chwili - utknęłam w lokacji stratowej - wszystkie klatki otwarte, gnomy w środku i nic sie nie dzieje po kliknięciu

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4098
