### ISSUE TITLE
[PL][Item][Achievement] To the Looter Go the Spoils

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#5984]
http://www.wowhead.com/achievement=1166/to-the-looter-go-the-spoils
http://www.wowhead.com/item=18228/autographed-picture-of-foror-tigule

Item powinien leciec z ciał na Alterac Valley, jednak daje głowe, że nie dropi - z ciał lecą tylko silvery i krew, oprocz tego powinny leciec rowniez jakies inne copy w tym autograf.
(ps. tak podniosłem juz tysiące ciał)

**Comment by Beatit** [comment]
zgadza się nic nie dropi, questy na AV ogólnie nie działają :(

**Comment by Parwers** [comment]
też    lootowałem  ciała i nic nie było, co do questow  też nie działają.
Trzeba w końcu zrobić battlemastera :D

**Comment by Urwena** [comment]
Potwierdzam, sam próbowałem to robić i jak widać bez rezultatu :d

**Comment by Aviannaqt** [comment]
wtb fix 50k gold

**Comment by Bildo** [comment]
ok wyslij mi na maina :dancers:

**Comment by Aviannaqt** [comment]
:/

**Comment by Aviannaqt** [comment]
bump

**Comment by Aviannaqt** [comment]
Wnosze o usuniecie tego achieva osobom mających owy achiv z sunwella.

**Comment by Aviannaqt** [comment]
Fixed
