### ISSUE TITLE
[PL][Death Knight][Item Set] 4x t12

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#5985]
http://www.wowhead.com/spell=99000/flaming-torment#modified-by:0-1+17+2

Bonus fire dmg odpala sie tylko od physical dmg a powinnien też od częsci shadow.
http://www.worldoflogs.com/reports/eqal3tkanmy347k3/details/4/?s=4783&e=5055
logi z globa 99ss > 197 proców fire dmg.
http://www.worldoflogs.com/reports/uv4wulo0rgb9qqrb/details/75/?s=3800&e=4039
logi u nas 81ss > 81 proców

**Comment by tnarf** [comment]
accidentally deleted Lenox07's 3rd link:
http://www.worldoflogs.com/reports/iky33387u7fjz22c/details/75/?s=3800&e=4039

**Comment by Jenovas** [comment]
Fixed in rev 4844
