### ISSUE TITLE
[PL][Death Knight][Pet] Ghoul autoattack speed and energy regen 

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#5986]
Ghoul robi mniej autoattaków niż powinnien oraz regen energii jest mocno zaniżony.
http://www.worldoflogs.com/reports/eqal3tkanmy347k3/details/170/?s=4783&e=5055
249 ataki oraz 69 skilli na 268.8 sekund bicia
http://www.worldoflogs.com/reports/uv4wulo0rgb9qqrb/details/154/?s=3800&e=4039
153 ataki oraz 17 skilli na 237 sekund bicia
Taką liczbę ataków powinnien zrobić jakby nie miał buffów do haste (UF, totem, BL, trink)
237/1,48 = 160 ataków 
Oraz powinnien użyć 61 skilli.
![wowscrnshot_012016_215550](https://cloud.githubusercontent.com/assets/9517740/12462833/a6d484de-bfc0-11e5-9e6d-fc293c4edca2.jpg)

**Comment by Kejmil** [comment]
ze nie wspomne ze ghoul w blood/frost powinien byc kalka tego z unholy, poza brakiem stuna, faktem tego ze sie snapshotuje w momencie uzycia i ograniczonym czasem dzialania

**Comment by blinkmaster** [comment]
No, wiedziałem,  że coś jest nie tak bo mój pet nie solowal aren

**Comment by BialyADI** [comment]
Jeszcze Double-dipp'uje się jego Claw z bufami % do Dmg(https://github.com/Atlantiss/BugTracker/issues/5659).

**Comment by tnarf** [comment]
accidentally deleted Lenox07's 2nd link:
http://www.worldoflogs.com/reports/iky33387u7fjz22c/details/154/?s=3800&e=4039

**Comment by Jenovas** [comment]
Fixed in rev 4840

**Comment by Lenox07** [comment]
A autoataki też naprawione?
