### ISSUE TITLE
[PL][Firelands][Alysrazor][Faza] - Tornada

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#5987]
Faza z "Fiery Tornadoes" nie działa, wirki w ogóle sie nie poruszaja. Po pierwsze pojawiaja sie odrazu ( a powinny dopiero po chwili wyjsc ze srodka pola / rozejsc sie), i znacznie szybciej sie poruszac po terenie - patrz 3:14 - https://www.youtube.com/watch?v=LS2v0b_JlpQ

**Comment by Aldergar** [comment]
Confirmed.

**Comment by Aldergar** [comment]
#6031
