### ISSUE TITLE
[PL][Item][Mage] Set T12 Mage Problem

### ISSUE THREAD

**Issue by Walniety** [Atlantiss/BugTracker#5988]
Set T12 nie działa poprawnie . Z niewiadomych przyczyn po założeniu drugiej setówki z setu t12 dps spada z 20k do 10k co jest zbyt dziwne do tego spawn rate Mirror Image jest taki niski że przez trzy minuty bicia pojawiły się dwa klony , normalny spawn rate to 20% dodam że przez te trzy minuty biłem cały czas Firebalami to samo w każdym innym speku :D
http://www.wowhead.com/spell=99061/item-mage-t12-2p-bonus :D

**Comment by kadi2** [comment]
Co do drastycznego spadku DPS-u ja bym postawil na wymierajace pingwiny na antarktydzie oraz wypalanie lasow deszczowych. Ewentualnie powiekszanie sie dziury ozonowej moze zle wplywac na coeffy fireballi.

**Comment by Walniety** [comment]
oczywiście rotacje zachowywałem taką samą jak wcześniej więc :D problem nie jest po mojej stronie a zauważalna różnica jest tak czy siak + ten spadek jest tylko podczas zmienienia rękawiczek z t11 na t12 by uzyskać drugi set bonus(mam już jedną stówkę Chest) i tylko wtedy ;D więc tego to ja nie rozumiem :D

**Comment by Kejmil** [comment]
ale wiesz ze bonusy t11 sa tak mocne ze dopiero na t12 hc oplaca ci sie go wymienic jesli miales t11hc? Oraz ze mirrory maja bodajze 45sec icd na spawn, wiec nigdy nie bedziesz miec wiecej niz jeden?

**Comment by blinkmaster** [comment]
Ano t12 to szajs jakich mało. Pod fire nawet staty masz w nim tragiczne w wiekszosci

**Comment by Jenovas** [comment]
Sprawdziłem i żadnego drastycznego spadku z 20k do 10k nie ma.
Zamykam.
