### ISSUE TITLE
[EN][Druid][Balance T12 4p Bonus]

### ISSUE THREAD

**Issue by mrmcmahon** [Atlantiss/BugTracker#5989]
Hello there!
I got that issue with the Balance T12 4p Bonus, that if you are in a non-eclipse state where it generates more Lunar and Solar energy (according to which eclipse you are going) you are interrupted on every cast you do when your previous cast hits the target.
Means: You are at 0 energy and with Wrath you'll get to the Lunar eclipse, thus you aren't in an actual ecplise right now. And that's where the problem strikes. You'll get interrupted at every Wrath you are casting at the moment the other Wrath you shot is hitting the target.
I tested it with different ranges to the target, and as far as I've seen it has something to to with the range.

**Comment by Jenovas** [comment]
Fixed in rev 4840
