### ISSUE TITLE
[EN][Item][Loot][Firelands shared loot

### ISSUE THREAD

**Issue by Evelinrose** [Atlantiss/BugTracker#5991]
Following items either have extremely low drop chance or no drop chance at all.
http://www.wowhead.com/item=71779/avools-incendiary-shanker
http://www.wowhead.com/item=71787/entrail-disgorger
http://www.wowhead.com/item=71785/firethorn-mindslicer
http://www.wowhead.com/item=71780/zoids-firelit-greatsword
http://www.wowhead.com/item=71776/eye-of-purification
http://www.wowhead.com/item=71782/shatterskull-bonecrusher
http://www.wowhead.com/item=71775/smoldering-censer-of-purity
All these items have from around 1 to 2% drop chance so i know that someone might think it's just bad rng but it can't be.Between release of the firelands and up untill now we had close to 15 total kills of every boss in firelands yet not a single shared item droped,furthermore i have made inquiry from couple of other guilds which also confirmed that no shared loot droped from them either.

**Comment by Aldergar** [comment]
I can confirm,it's either bad luck or they are bugged.

**Comment by Sayris9876** [comment]
Confirming... never seen anyone with shared boss loot item at all so far

**Comment by Kejmil** [comment]
25man guilds saw some items from shared loot so bad luck i guess

**Comment by LaveniaGithub** [comment]
We've made 25 man raids every week since release, still haven't seen any.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4858
