### ISSUE TITLE
[PL/ENG][Priest]Reflective_shield_talent

### ISSUE THREAD

**Issue by MezVM** [Atlantiss/BugTracker#5993]
PL:      Obrażenia generowane przez tarcze nie powinny generowac aggro, w rzeczywistości jest jednak inaczej. Blad mozna powtorzyc zucajac czar na innego gracza ktory nie wykonuje akcji a jest atakowany przez potwory. Po otrzymaniu obrazen przezucaja sie one na priesta.

ENG:   Reflective shield should not generate any aggro, in reality after inflict reflected damage it does. When we cast it on attacked player, which makes no actions, mobs will change they target after damage receiving.

**Comment by Quban** [comment]
this spell cant generate any threat, mob changed target probably because target of power word shield didnt do anything and you are casting spell (sheld reflect dmg) so you did an action when your target didnt do anything

**Comment by Kejmil** [comment]
shoudn't reflect only work when cast on self?
"Causes $s1% of the damage <b>you</b> absorb with Power Word: Shield to reflect back at the attacker.  This damage causes no threat."
http://cata.openwow.com/spell=33201
http://cata.openwow.com/spell=33202

**Comment by Jenovas** [comment]
Reflective_shield works only on the priest that casted it
Closing
