### ISSUE TITLE
[PL][Item] Necromantic focus

### ISSUE THREAD

**Issue by astale** [Atlantiss/BugTracker#5996]
Link do itemu: http://www.wowhead.com/item=68982/necromantic-focus
Link do buffa: http://www.wowhead.com/spell=96963/necromantic-focus

Powinien odpalać się na dot'ach, natomiast odpala się również na hot'ach (np. riptide).

**Comment by Kejmil** [comment]
INSERT INTO spell_proc_event (`entry`, `procFlags`) VALUES
(96963, 0x00050000) ON DUPLICATE KEY UPDATE  procFlags = 0x00050000;

INSERT INTO spell_proc_event (`entry`, `procFlags`) VALUES
(97132, 0x00050000) ON DUPLICATE KEY UPDATE  procFlags = 0x00050000;

**Comment by Kejmil** [comment]
INSERT INTO spell_proc_event (entry, procEx) VALUES
(96963, 0x0080000) ON DUPLICATE KEY UPDATE procEx = 0x0080000;

INSERT INTO spell_proc_event (entry, procFlags) VALUES
(97132, 0x0080000) ON DUPLICATE KEY UPDATE procEx = 0x0080000;

will work after slamas will implement new procex flags

**Comment by Kejmil** [comment]
fixed in rev. 4868 xD
