### ISSUE TITLE
[PL][MOLTEN FRONT][NPC]Skarr

### ISSUE THREAD

**Issue by DonKefa** [Atlantiss/BugTracker#5997]
Pet którego można oswoić jest przyjazny, a powinien być nieprzyjazny. Można go oswoić wszystkimi specami, mimo wszystko zmiana specu nadal nie działała, bo pet jest zbugowany.

SCREENSHOT: http://i.imgur.com/LXtWbiU.jpg

WOWHEAD: http://www.wowhead.com/npc=50815/skarr

**Comment by Thefakemccoy** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/5702

**Comment by Bastion** [comment]
idź tam rare spidery oswajać lepiej :D

**Comment by Quban** [comment]
> Duplicate #5702
