### ISSUE TITLE
[PL/ENG][SPELL][PRIEST]dispel_magic

### ISSUE THREAD

**Issue by shockave** [Atlantiss/BugTracker#5998]
PL: zaklecie powinno dispelowac 2 "negatywne efekty" z przyjaznego celu, dispeluje natomiast 1

ENG: spell should dispel 2 armful effects from friendly target instead it only dispels 1

**Comment by blinkmaster** [comment]
to nie wotlk. sprawdz patch changes.

**Comment by debtheone** [comment]
tez to zauwazylem na rhc jutro obadam dokladnie jak to dziala raczej cos przy stackach sie psuje

**Comment by shockave** [comment]
stacki zdejmuje 2 owszem, ale jeśli są 2 "rożne" debuffy zdejmuje się tylko 1

**Comment by Aviannaqt** [comment]
Działa dobrze
