### ISSUE TITLE
[EN][Spell][Priest] Mind Control

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#6]
When you try to mc target during fear he can move on his own.
Same thing will happen during blind  scatter etc.
Same bug as on main
http://www.wowhead.com/spell=605

**Comment by debtheone** [comment]
BUMP

**Comment by debtheone** [comment]
bump fix please

**Comment by debtheone** [comment]
bump

**Comment by debtheone** [comment]
debtheone opened this Issue on 2 Nov 2014 :(:(

**Comment by debtheone** [comment]
debtheone opened this Issue on 2 Nov 2014 :(:(:(

**Comment by Wolffenstein** [comment]
Fixed in rev 4546.
