### ISSUE TITLE
Lightwell w Combacie

### ISSUE THREAD

**Issue by czajaj** [Atlantiss/BugTracker#6000]
Podczas trwania walki (status combat) Lightwell przestaje działać poprawnie. Po kliknięciu w studnie i zakończeniu trwania HoT'a gracz nie może użyć LW ponownie.Dodatkowo zanika ikona "trybu" kiedy się najeżdża na obiekt (też tylko w stanie combat) ale to kosmetyczna wada bo HoT jest normalnie przyznawany po kliknięciu.
Zauwazylem jeszcze ze gdy LW dostanie jakis dmg np z AoE to znow mozna kliknac ale znow tylko raz

**Comment by Aviannaqt** [comment]
duplicate
