### ISSUE TITLE
[PL][Firelands][Alysrazor][Faza 3 & 4] Hit box

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#6003]
Hit box bossa w fazie 3 i 4 jest ciut za mały, melee żeby było zdolne uderzyć Alysrazorke musi "wejsc" w bossa mnie wiecej do polowy zeby zaczac trafiac. Mozliwosc bicia feniksa powinna raczej byc ustawiona jak tu: od 5:20 https://www.youtube.com/watch?v=uB0La0v7x3o

**Comment by Aldergar** [comment]
#6031
