### ISSUE TITLE
[EN][Quest[Teldrassil] Teldrassil:The Burden of the Kaldorei

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6004]
http://www.wowhead.com/quest=7383/teldrassil-the-burden-of-the-kaldorei
How it should work: This quest should become available for all races of the alliance once you complete the prerequisites, http://www.wowhead.com/quest=918/timberling-seeds and http://www.wowhead.com/quest=919/timberling-sprouts.
What is bugged: The quest is not available for humans after completing the prerequisites. I have completed all quests in Teldrassil except the quest chain started by this quest (for non-nightelf characters).

**Comment by Sylvictus** [comment]
I just experienced this as well on my Draenei. No quest opens up once the seed quests are completed.

This quest http://www.wowhead.com/quest=929/teldrassil-the-refusal-of-the-aspects is Night Elf only and is correct. It comes from this NPC http://www.wowhead.com/npc=3515/corithras-moonrage and is a continuation of Night Elf only quests started in shadowglen.

However non night elf races should be able to pick up at the quest http://www.wowhead.com/quest=7383/teldrassil-the-burden-of-the-kaldorei once the prerequisites listed above in the OP's comment have been completed. The entire chain starting at burden if the kaldorei and further are alliance specific only, not night elf, like it is currently bugged in game;

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8053-6004questteldrassilthe-burden-of-the-kaldorei/?p=33565
