### ISSUE TITLE
[PL][Firelands][Beth'tilac] Venom Rain a schodzenie na dolną platformę

### ISSUE THREAD

**Issue by melsage** [Atlantiss/BugTracker#6005]
Zdaża się, szczegolnie przed jej pierwszym Smoldering Devastation, że jezeli target bossa spadnie z gornej sieci/"platformy" na ktorej znajduje sie z bossem, to Pajęczyca wariuje i schodzi na dół za swoim celem/tankiem, zamiast kontynuować używanie skilla Venom Rain (http://www.wowdb.com/spells/99333-venom-rain), do czasu aż jakikolwiek gracz wróci na górną platformę.

**Comment by Aldergar** [comment]
#6031
