### ISSUE TITLE
[PL][Achievement] Explore Arathi Highlands

### ISSUE THREAD

**Issue by TheNorberto** [Atlantiss/BugTracker#6006]
http://www.wowhead.com/achievement=761/explore-arathi-highlands
Nie zalicza niektórych lokacji
Dowód:
 http://i67.tinypic.com/2e4m9sh.jpg ( Mój achiv )
 http://i66.tinypic.com/23rn9yf.jpg (Odkryte Obszary )

**Comment by eryczek1615** [comment]
Ja żeby np odkryć zamek musiałem wlecieć do budynku. Tylko że to było dawno

**Comment by TheNorberto** [comment]
Dawniej dało się to zrobić teraz z tego co widzę nie tylko ja mam ten problem
