### ISSUE TITLE
[EN][Quest][Tanaris] The Black Morass

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6007]
http://www.wowhead.com/quest=10296/the-black-morass#comments
This quest should be available only after completing the prerequisite, http://www.wowhead.com/quest=29599/escape-from-durnholde.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8050-6007questtanaris-the-black-morass/
