### ISSUE TITLE
[EN][Item][Priest] 4p t12 holy/disco

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#6015]
i find it hilarious that it isn't reported yet, with all this minor bugs with sets labeled as high prio xD
http://www.wowhead.com/spell=99135
http://cata.openwow.com/spell=99135

it should heal </b>ONE</b> injured target in it's proximity, target in party (raid?)
not all of them, not even in party (raid?) ones, including triggers like it work now on ATS xD

**Comment by Aviannaqt** [comment]
podobno juz ta poprawka jest i oczekuje na wgranie, zobaczymy

**Comment by Aviannaqt** [comment]
fajnie sie av leczy :+1:

**Comment by Kejmil** [comment]
albo sinestre "dispeluje" ( ͡° ͜ʖ ͡°)

**Comment by Aviannaqt** [comment]
???

**Comment by Jenovas** [comment]
Fixed in rev 4840
