### ISSUE TITLE
[EN][Talent][Warrior] taste for blood

### ISSUE THREAD

**Issue by egostar** [Atlantiss/BugTracker#6017]
it does not activate buff "taste for blood" on every DoT-tick and talent does not increase critrate by 60%. it increas it TO 60%.
should increase by 60%
try it yourself on boss encounters. nobody want to believe me

**Comment by Kejmil** [comment]
http://cata.openwow.com/spell=56636 r1
http://cata.openwow.com/spell=56637 r2
http://cata.openwow.com/spell=56638 r3

"In addition, whenever your Rend ability causes damage, you have a 100% chance of allowing the use of Overpower for 9 sec. <b>This effect will not occur more than once every 5 sec</b>."

**Comment by anxanas** [comment]
How do you know that it increases it to 60% instead of increasing it by 60% have you tested it with enough overpowers to rule out rng. And the part with rend works perfectly, i and other warriors have never had the imaginary problem you seem to have

**Comment by Kejmil** [comment]
well, i wasn't able to score noncrit with recklessness up (120%+ crit chance on overpower), 100 samples, so i guess author of this issue is wrong

**Comment by egostar** [comment]
"And the part with rend works perfectly". it doesnt because u dont know how to play out taste for blood in the right way. sometimes rend-tick "skippes" a taste for blood proc so i get a proc after 9 seconds instead of 5 seconds

**Comment by Kejmil** [comment]
proofs, not words plz

**Comment by egostar** [comment]
can any of devs prove that their formular is like the origing? i dont think so.

**Comment by Jenovas** [comment]
We are not the ones that are supposed to prove anything. So we will not be proving anything.
