### ISSUE TITLE
[EN][spell][rogue] vanish

### ISSUE THREAD

**Issue by sapmvp** [Atlantiss/BugTracker#6018]
There is a little problem with Flame orb and Frostfire Orb because this spell can break vanish of rogue. You can see on this video https://youtu.be/kufsJysS8HE?t=1027  , rogue can vanish this spell, only the hunt's flare can spot rogue in vanish, because i'm immune at every damage when i vanish for 3sec

**Comment by blinkmaster** [comment]
http://us.battle.net/wow/en/forum/topic/2369745000#1
Working as intended.

**Comment by sapmvp** [comment]
This post was write at the 4 / 17 / 2011 , so this is the 4.1 and this video is in 4.3 (you can see his weapon)

**Comment by PARANOiA32** [comment]
Confirming that its not working as intended, i main a rogue here and did so on retail up untill end of mop.

**Comment by crosik** [comment]
its bugged, it shouldnt break vanish like this. BUMP
Skippy<<

**Comment by Malylolek** [comment]
This one look beeter #8109
