### ISSUE TITLE
[EN][Quests][Southern Barrens] Marley's Final Flight & Several More

### ISSUE THREAD

**Issue by ylluminate** [Atlantiss/BugTracker#6024]
When we click on Marley Twinbraid after completing prerequisite quests, he does not have the option to fly with him on his crashing last flight ([Wowhead](http://www.wowhead.com/quest=25120/marleys-final-flight) & [Video](https://www.youtube.com/watch?v=CbhkgRq1x2E)).  This also prevents players from obtaining the next and final important quests: 
* [Bael'dun Rescue](http://www.wowhead.com/quest=25153/baeldun-rescue),  
* [He Needs Ale!](http://www.wowhead.com/quest=25151/he-needs-ale), 
* [Who Did This?](http://www.wowhead.com/quest=25163/who-did-this), 
* [Twinbraid Needs to Know](http://www.wowhead.com/quest=25174/twinbraid-needs-to-know), & 
* [Kill 'em All!](http://www.wowhead.com/quest=25182/kill-em-all)

**Comment by lourrific** [comment]
May 23, 2016 and this quest is still bugged

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/1274
