### ISSUE TITLE
[EN][Quests][NPC][Twilight Highlands][Cementing Our Victory]

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#6025]
the q giver disapered during the time i was completing the Q , it looks like hess in a difrent faze or deep under the txttures

screen -http://i.imgur.com/3J9aNb2.jpg
video - https://www.youtube.com/watch?v=zUhtDq7XvAo
Cementing Our Victory - http://www.wowhead.com/quest=26788/cementing-our-victory
Ornak - http://www.wowhead.com/npc=44042/ornak

**Comment by Aviannaqt** [comment]
#5645
