### ISSUE TITLE
[En][rogue/druid][spell] stealth/vanish mechanics and spells in the air

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6028]
On our server using vanish, going in to stealth or pounce when spell is used against you make the spell efect and damage indeed vanish which is a bug.
How it should work : Sincerely cata vanish and stealth mechanics has been changed to alter 3 sec vanish rule. IT no longer made possible vanishing spells in mid air [well it did ofc > you would be in death coil efect in vanish ] 

http://eu.battle.net/wow/en/forum/topic/2393920117

**Comment by kadi2** [comment]
#263
