### ISSUE TITLE
[EN][spell][Priest] Mind control

### ISSUE THREAD

**Issue by Bustyplz** [Atlantiss/BugTracker#6029]
So, there is a little problem with the mind control because i can't dispell offensive the mind control 

you can see on this topic : http://us.battle.net/wow/en/forum/topic/2926964008

"It's a Friendly Magic Effect but it turns the target hostile, so it must be removed by an offensive dispel.

Dispel Magic - Priest
Purge - Shaman
Devour Magic - Felhunter (Warlock)
Tranq Shot - Hunter"

**Comment by Illusie** [comment]
hello!

**Comment by Fapguy** [comment]
yep.
MC is bugged, can confirm, very very very very annoying to use like it is now.

**Comment by Bustyplz** [comment]
Since January it doesn't fixe, so someone can check it please :) ? Cause it's very ennoying

**Comment by Illusie** [comment]
it must be fixed.
u can't put dots /  bleed on someone and MC him and he will keep take damage.
:/

**Comment by Jenovas** [comment]
The topic you linked does not exist. Also I found this.

85 Worgen Warlock
RKings
6080
I'm sorry to say that Mind Control doesn't break on damage from my numerous experiences with it. Maybe I'm just unlucky, but it's happened many times. T**he fact that it's not dispellable is what bothers me the most.** I don't see why that's allowed when all other caster CC is.

Please find proof and create a new report, or add the proof here.
Until proof is provided the report will be closed.

**Comment by Jenovas** [comment]
Just did some research. When a priest casts mind control both the priest and the target get a buff called mind control. Dispelling the target that is mind controlled does not break it, but dispelling mind control from the priest casting breaks it. My addons also show me the mind control on the priest as dispellable, but they do not show me that the mind control on the controlled target is dispellable.

I think this case is closed.

**Comment by Bustyplz** [comment]
We can offensive purge our teammate, cause if our teammate is Mind control he is considering like an "ennemy", so if I use an offensiv dispell like "Purge" (shaman spell) i can purge the mind control on my teammate, but it doesn't work on the priest ofc

http://eu.battle.net/wow/fr/forum/topic/2868801566

Sorry it's in french but i didn't find another topic in english cause the first is delete and i published this one in January, so if i translate it's just the same thing, i mean i can offensiv purge my teammate

**Comment by Jenovas** [comment]
As I stated above, you can purge the priest that is casting mind control and it will purge it breaking mindcontrol. I dont know which addon does this for me (maybe ElvUI), but I see the mindcontrol on my friend is as a gray icon on the priest it is as a normal dispellable icon. The post you showed does not prove anything, the purge can be casted on the priest to break mindcontrol.

**Comment by Bustyplz** [comment]
" the purge can be casted on the priest to break mindcontrol." 
**But it doesn't work** 

And as i remember, is when I purge my mate that break MC but maybe i'm wrong but in my precedent post i link you a tutorial for play Rsham at 4.3.4 and this guy confirm the fact, we can purge a MC.

But whatever if it's on the priest or my teammate, it doesn't work on Atlantiss

**Comment by Illusie** [comment]
More something I want ot add.
https://www.youtube.com/watch?v=cY4pgtfU4WM 12:34
Seems like the shaman is tremor the Mind Control.

I want to connect this to https://github.com/Atlantiss/BugTracker/issues/7813
Grounding & Tremor don't work as Intend.

**Comment by Illusie** [comment]
@Jenovas 
Hello jenovas.
Mind Control purgable gonna be happen soon?
