### ISSUE TITLE
[PL][Firelands][Ragnaros] Searing Totem [spell=3599]

### ISSUE THREAD

**Issue by Drazzer** [Atlantiss/BugTracker#6030]
Totem w czasie walki z Ragnarosem nie zdaje mu obrażeń z odległości większej niż promień zbiornika z lawą w którym się znajduje (1.) Żeby totem zaczął zadawać obrażenia trzeba stawiać go niemal w lawie (2.). Pomimo tego, że hit box bosa pokrywa całą platformę na której odbywa się walka. Jest to szczególnie problematyczne dla enh shamana, którego główny atak opiera się na bonusie z doty nakładanej przez ten totem.
1. ![wowscrnshot_011016_210518](https://cloud.githubusercontent.com/assets/8134884/12530609/39c0c2f6-c1e4-11e5-8093-fc3cf0bd0b55.jpg)
2. ![wowscrnshot_011016_210342](https://cloud.githubusercontent.com/assets/8134884/12530619/7f90824e-c1e4-11e5-9fdb-e6bcbf7f57e1.jpg)
Podobne zachowanie zauważono też w przypadku umiejętności paladyna: [Consecration](http://www.wowhead.com/spell=26573) i [Holy Wrath](http://www.wowhead.com/spell=119072)

**Comment by Aldergar** [comment]
#6031
