### ISSUE TITLE
[PL][PvE][Spell][Warlock][Firelands][Ragnaros][Immolation aura]

### ISSUE THREAD

**Issue by Assiria** [Atlantiss/BugTracker#6042]
Tak więc, na naszym serwerze na ragnarosie są pewnie bugi z zasięgiem, nie łapią go niektóre spelle, pety itd.
Nie ważne gdzie stoisz lockiem nie sięga go:
immolation aura= https://cata-twinhead.twinstar.cz/?spell=50589
felstorm felguarda= https://cata-twinhead.twinstar.cz/?spell=89751
shadowflame= https://cata-twinhead.twinstar.cz/?spell=47897
na wowheadzie nie moglem znalezc odpowiednich skilli z cata dlatego linkuje akurat te.
Dowód na działanie tych wszystkich skilli jest na wielu filmach z globala np:
https://www.youtube.com/watch?v=19XDuoxSW5c
https://www.youtube.com/watch?v=3SjTkIuyJ-c
ten film jest bardziej dokładny gdyż widać ikonki spelli po prawej stronie jakie zadają dmg, widać także ze na obydwu filmach boss dostaje zarówno debuffa od shadowflame breath i także dmg, widać jak pet używa felstorma i także boss otrzymuje dmg i to wszystko w połowie platformy.
Bugi z petami na ragnarosie widziałem ze już były zgłoszone ale nie akurat te spelle co opisałem.
Na wiekszości walk nie musze wcale używać life tapa, gdyż zwraca mi sie mana gdy mu pet critnie, natomiast na ragnarosie nie crituje prawie wcale i co chwile muszę life tapowac.

**Comment by Aldergar** [comment]
#6031
