### ISSUE TITLE
[PL][Item]Morningstar Shard - zbugowany?

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#6044]
http://wow.gamepedia.com/Morningstar_Shard 
Item ten kupiłam jakiś czas temu z vendora za 700vp. 
Wcześniej miałam Dragonwreck Throwing Axe http://wow.gamepedia.com/Dragonwreck_Throwing_Axe. 
Pomimo tego, że pierwszy item był znacznie lepszy od tego drugiego, to po tym upgrade, zadaję mniej obrażeń niż przedtem. Nie może to być moja wina - cały czas używam tej samej rotacji, no po prostu wszystko bez zmian, nie licząc lepszego itemu. Mając założony Dragonwreck Throwing Axe na luzie mogłam nabić 15k dpsu, a nawet i więcej. Z tym nowym itemem, jak dobiję 12k to jest dobrze. (często problem mam, by w ogóle przekroczyć 10k) Czasem udaje mi się jakiś sensowny dps nakręcić, ale to rzadko. 
Moje staty: http://imgur.com/a/UDhmw

**Comment by Haz3L** [comment]
Potwierdzam, z poprawną rotacją nie idzie nabić więcej niż 10k single target bo też próbowałem.

**Comment by Aviannaqt** [comment]
o.O

**Comment by tnarf** [comment]
kolejny...
Bądź tak miły i poza DPS przetocz inne cyferki (dla obu przypadków)
tzw:
ile poszczególnych ataków, jaki dmg (NIE DPS) one robiły itp itd..
Jak nie potrafisz tego zrobić albo nie potwierdzają twojej teorii to bądź tak miły i ZAMKNIJ ten temat

**Comment by Quban** [comment]
prawdopodobnie bug mastery, -> respec

**Comment by Jenovas** [comment]
Prosze o respec, sprawdzic czy mastery sie nie zbugowało.
Policzyć co i jak, dac jakies dowody.
Zamykam.

**Comment by Anhaeyn** [comment]
Robiłam respec parę razy, nie pomagało. Staty były w porządku.
