### ISSUE TITLE
[EN][Area][Object] Firelands Hatchery Portal

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#605]
After I've finished my quests in **Firelands Hatchery** (http://www.wowwiki.com/Firelands_Hatchery). I couldn't use the portal to get back out.

Some people in my guild said that it worked for them, but some also said that they had the same issue as me.

So I guess it gets bugged for some people, and not for others. Anyway, should be looked into.

**Comment by Thefakemccoy** [comment]
Broke as you can see im standing in it nothing happens.

![wowscrnshot_052515_060251](https://cloud.githubusercontent.com/assets/12252441/7795490/af926aa8-02a3-11e5-8cab-48be8b622e30.jpg)

**Comment by mikonek07** [comment]
Still bugged

**Comment by Hexenbane89** [comment]
Still bugged

**Comment by HUMBOL** [comment]
BUMP!
(http://imgur.com/9uKfbOk)

**Comment by Foggy0260** [comment]
Still bugged

**Comment by Rinniel** [comment]
Still bugged

**Comment by micha666** [comment]
Bump, still bugged.

**Comment by Charybdo** [comment]
Still Bugged :( . 
Błąd prawdopodobnie działa ze względu na te fazowanie, działa tylko w 1 gdy się tam pierwszy raz teleportujemy, po zrobienia questu z flagą już nie działa teleportyzer.
Możliwe jest też złe napisanie wiersza w skrypcie :(

**Comment by Silverdevilboy** [comment]
Still bugged.

**Comment by krecik88** [comment]
fixed

**Comment by krecik88** [comment]
fixed
