### ISSUE TITLE
[PL][Hunter][NPCs][core?] Stable masters doesn't work at all.

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#6053]
Opcje dialogowe do zmiany petów u stable masterów nie działają. Po ich wybraniu nic się nie dzieje.
Nie jest to błąd jednego NPC, tylko każdego możliwego stable mastera. (sprawdzane po stronie ally)

**Comment by Siudzin** [comment]
mam nadzieję,że ktoś sie tym zajmie... jak i również to,że pety pozostawione u stable mastera nie zostaną usunietę...

**Comment by krecik88** [comment]
zajme sie tym zaraz jak skoncze poprawki z innym branchem, prawdopoodbnie cos zostalo ominiete przy optymalizacji

**Comment by pawelli** [comment]
Też borykam się z tym bugiem. Problem nadal występuje. Byłem u kilku Stable Masterów lecz opcje dialogowe nadal nie działają. W miarę możliwości proszę o szybkie załatwienie sprawy albo chociaż informacje kiedy możemy spodziewać się poprawki. Pozdrawiam

**Comment by krecik88** [comment]
fixed in 4979
