### ISSUE TITLE
[EN][Quests][Twilight Highlands] Warm Welcome

### ISSUE THREAD

**Issue by Blackaddder** [Atlantiss/BugTracker#6054]
This quest should unlock after completing:
http://www.wowhead.com/achievement=5451/consumed-by-nightmare

This blocks the whole chain.

**Comment by Luna-maria** [comment]
that part of TH isn't scripted yet

**Comment by Blackaddder** [comment]
Oh, well. good to know. Thanks.Is there any source what is not available yet?
