### ISSUE TITLE
[EN][Talent][Arcane Potency]

### ISSUE THREAD

**Issue by dantethehunter** [Atlantiss/BugTracker#6055]
Arcane Mage's talent Arcane Potency doesnt work. Checked it many times. You can see in the picture, that even i got the buff, the critical strike rating remains the same. Please fix it, as it is very important talent for arcane mages for both pvp and pve. Thank you http://wow.gamepedia.com/Arcane_Potency
![untitled](https://cloud.githubusercontent.com/assets/16544783/12538156/10d0180e-c2db-11e5-85cb-80b36d72cbce.png)

**Comment by Jenovas** [comment]
The talent does not increase the crit chance in the player info, but it works properly. Just tested.
Closing.

**Comment by coba999** [comment]
I'm sorry, Jenovas , but your reply sounds like madness. This couldn't be a soltuion! How many more things can work but not be displayed? Or showed but does not work? Pls, fix it just like Blizzlike. 
Mage have skill Molten Sheild, and Crit. chance changes, when I use it. So, we can make the obvious conclusion, that Arcane Potency doesn't work!
![ojk3u_croper_ru](https://cloud.githubusercontent.com/assets/15231821/14012003/82370512-f1ab-11e5-8f20-8a9bb17f081f.jpeg)

**Comment by Jenovas** [comment]
Give me evidence that it should increase crit in the char info.
The obvious conclusion would be test it on a dummy and see that it works.

**Comment by coba999** [comment]
Because the only source where I can see my critical chance - it's char info.

**Comment by Jenovas** [comment]
That's not evidence. Show me that on retail it increased crit chance in char info.
Until we get such evidence it's eot for us. 
Cheers.

**Comment by coba999** [comment]
Game have only one place, where I can see your critical chance, and nothing more else, **and nothing more**. 
Arcane Potency must give 15% of critical chance, but it doesn't give any. I can see it in my char info, the only place, where i can find out my crit chance. **and nothing more else**. 
Arcane Potency doesn't work. **I have proof, in the form of screenshots**. Many players will be agreed with me.
Proof from your side of working skill =  **only words**. = nothing!
That's all. So fix it. Talent was working good earlier, like i told, but something was broked.

**Comment by Jenovas** [comment]
Talent works. Eot.
