### ISSUE TITLE
[PL][Spell][Warrior] Charge - Elven Forest

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6065]
Intercept -> http://cata.openwow.com/spell=20252
Charge -> http://cata.openwow.com/spell=100

"No path available" tym razem w Elven Forest, jest szansa by te "No path avaliable" zostało naprawione :x?
![wowscrnshot_012516_150132](https://cloud.githubusercontent.com/assets/5780624/12552899/a347b216-c374-11e5-8a2a-5531415ad2df.jpg)

**Comment by Aviannaqt** [comment]
soon

**Comment by BialyADI** [comment]
Soonwell.
