### ISSUE TITLE
[PL][Death Knight][Pet] Ghoul

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#6066]
Po fixie na regen ghul sie całkowicie zepsuł.
Weź cofnij to i zrób aby claw kosztowal 0 energii ale miał 4 sec cd.
![wowscrnshot_012516_153813](https://cloud.githubusercontent.com/assets/9517740/12553821/dc7df7ac-c379-11e5-91fc-67101ce5e1d3.jpg)

**Comment by Kejmil** [comment]
widze ghoul ma mane wiec to raczej nie przez fix Jenovy tylko optymalizacje petow

**Comment by Jenovas** [comment]
Nie jest to po mojej zmianie. Najpewniej ponowne wezwanie Ghoula to naprawi albo ostatnia zmiana w ktorej zostal przepisany caly pet system cos zbugowal.

**Comment by Lenox07** [comment]
Czyli to optymalizacja coś zrąbała bo po zalogowaniu ghul miał normalne staty.
Po zejściu z mounta ghoul sie nie pojawił a jak go przyzwałem rise dead to miał właśnie takie staty jak na screenie.

**Comment by krecik88** [comment]
working on it

**Comment by krecik88** [comment]
almost fixed

**Comment by krecik88** [comment]
fixed
