### ISSUE TITLE
[en][core] Pets

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6067]
after new revisions :  
/petmoveto cause pet to move at ultra high speed
/petfollow tends to bug out and pet stays in place
overall pet following/assising sucks.

after dismount pet vanishes entirely ( for mage this means i get 3 min cd and no ele )

miracles happens ;d

**Comment by blinkmaster** [comment]
ah and about dk pet in unholy : 34k hp 100 mana
before it was about 90k hp and ofc energy.

**Comment by krecik88** [comment]
working on it

**Comment by krecik88** [comment]
almost fixed

**Comment by krecik88** [comment]
fixed

**Comment by blinkmaster** [comment]
po fixie dismount powoduje, ze pet ma 0-1% hp.

**Comment by krecik88** [comment]
fixed

**Comment by blinkmaster** [comment]
resummon petow u locka powoduje wylaczenie autocastu ich umiejetnosci

**Comment by blinkmaster** [comment]
oprocz tego uzywanie abilities petow np na focus ( typu spell lock) kiedy pet bije nasz target powoduje jego switch targetu na focus, co nie powinno miec miejsca jezeli mamy peta na /passive i sami wskazujemy mu cele do bicia /petattack

**Comment by blinkmaster** [comment]
dismount powoduje znikanie petow locka
