### ISSUE TITLE
[EN][Talent][Druid]Tiger's Fury doesn't affect Ferocious Bite

### ISSUE THREAD

**Issue by Mordorianin** [Atlantiss/BugTracker#6068]
Like in the title. Tiger's Fury doesn't affect Ferocious Bite. Everything is getting stronger after we use our cooldown by 15% - mangle, shred, ravage, bleeds - but not Ferocious Bite. The damage is still the same with or without the buff.

http://wowwiki.wikia.com/wiki/Tiger%27s_Fury
http://wowwiki.wikia.com/wiki/Ferocious_Bite

**Comment by phifedawg** [comment]
I haven't noticed this on my druid so far. I will test and feedback asap whether this is correct or not.

**Comment by Jenovas** [comment]
Fixed
