### ISSUE TITLE
[PL][NPC]Shattrath

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#6069]
Aukcjonerzy w Shatt nie działają, brak możliwosci interakcji miedzy nami a NPC.
http://wowwiki.wikia.com/wiki/Auction_House

Horda:
http://www.wowhead.com/npc=50145/auctioneer-braku
http://www.wowhead.com/npc=50140/auctioneer-lyrsara

Ally (prawdopodobnie również nie działają):
http://www.wowhead.com/npc=50139/auctioneer-kalaren
http://www.wowhead.com/npc=50143/auctioneer-itoran

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/7978-60692811-auctioneers-shattrath-city/
