### ISSUE TITLE
[EN][Quest][Minor][Molten Front] Those Bears Up There

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6070]
http://www.wowhead.com/quest=29161/those-bears-up-there

quest works fine but there's a small error in the quest text

it says " Lil' b-b-b-baby bears! Save them, <name>!"  instead of the players name being there

**Comment by xmesaj2** [comment]
fix: http://community.atlantiss.eu/index.php?/topic/7980-6070questminormolten-front-those-bears-up-there/
