### ISSUE TITLE
[PL][Quest][Azshara] Azsharite Experiment Number Two

### ISSUE THREAD

**Issue by Syrnikus** [Atlantiss/BugTracker#6071]
Problem w tym ze nie zamieniamy sie w szczura i nei ma opcji interakcji w Gormungarze..

powinno działać tak jak na filmiku

https://www.youtube.com/watch?v=mXhK6dInwPk

**Comment by Khangu** [comment]
Quest działa mniej więcej dobrze (ma bugi ale da się go bez problemu ukończyć), trzeba po zmniejszeniu wsiąść na szczura i na nim podjechać do giganta, tak też mówi nam opis i tak jest na filmiku.

**Comment by Aviannaqt** [comment]
link do q
