### ISSUE TITLE
[PL][QUEST]Taragaman the Hungerer 

### ISSUE THREAD

**Issue by Therenir** [Atlantiss/BugTracker#6073]
http://wowwiki.wikia.com/wiki/Quest:Taragaman_the_Hungerer

Quest dostępny powinien być od lvlu 13, jednakże dziś na BG widziałem parę postaci 10lvl z chestem czy innymi itemami z owego questu co daje oczywistą przewagę.

Za przykład może posłużyć gracz "Coconutwater" 10 lvl druid z owym chestem

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8052-6073questtaragaman-the-hungerer/
