### ISSUE TITLE
[EN][Hunter][Pet][Spell] Call Pet

### ISSUE THREAD

**Issue by Blackaddder** [Atlantiss/BugTracker#6074]
My Wolf pet always spawns with 11,341/77,775 HP after calling him. Autocast settings don't save after dismissing. The problem is with every pet. Everythng worked fine till today. I've used BM spec before. Today changed to 2nd talent spec ( Survival). Maybe that's the cause. Still don't know how to fix that and if it's global problem or just me.

**Comment by krecik88** [comment]
will be working after next server restart
