### ISSUE TITLE
[EN][Spell][Hunter] Call Pet Bug

### ISSUE THREAD

**Issue by Aieerth** [Atlantiss/BugTracker#6075]
Soo when I try to call my new pets (I just tamed them) I summon pets I just stabled. As you can see in screen I don't have scorpion in my pet slots and I still summon him; though I called a sporebat. + I can't  call my fourth pet. After using call on him nothing happens.

http://imgur.com/mCR6PXk

+ after restart I can summon my fourth pet again!

**Comment by krecik88** [comment]
problem still exist or is ok everything?

**Comment by Aieerth** [comment]
I can't call any pet after taking him from stable farm now.

**Comment by krecik88** [comment]
fixed in 4979
