### ISSUE TITLE
[EN][Mage] T12 Set Bonus

### ISSUE THREAD

**Issue by Genoangel** [Atlantiss/BugTracker#6076]
Hello ,
I would like to report the bugs present in 2P bonus T12 and 4P for all specs.

2P Bonus : if the mirror image spawn it make you stop cast.

4P bonus : 
Arcane : The spell cost reduction (10%) doesn't apply on stacks of arcane blast.
Example : 
arcane blast cost initialy 871 Mana , with arcane power it will cost 783. wish is normal.
Arcane blast with 4 stacks cost 6097 mana. with 10% reduction of spell cost with arcane power , it's supposed to have 5488 mana. but it cost in reality 6009 mana. the mana reduction is 88 mana instead of 609 , like if the mage had only 1 stack.
You will find attached , the screens of arcane spec with the cost of spells in 4 stacks.
![with arcane power 4 stacks](https://cloud.githubusercontent.com/assets/16892058/12572406/dfdee77a-c3e3-11e5-8e62-269c7d1639a9.jpg)
![without arcane power 4 stacks](https://cloud.githubusercontent.com/assets/16892058/12572407/e032e654-c3e3-11e5-8e66-3e7c0bac66ad.jpg)

Fire : Hot streak doesn't proc from the set.
Frost : Finger of frost does proc , but i don't know if it's the talent or the set bonus.

Best Regards ,

**Comment by blinkmaster** [comment]
About posts of ppl saying t12 4p worked like here - it did at the beginning then it was stealthly hot fixed to reduce Total mana coś not only base. Also Plz make the mirrors start attacking :((

**Comment by Mordorianin** [comment]
T12 2P is also missing spells.

**Comment by BialyADI** [comment]
Where it say that it shoud reduce total mana cost, mage will have endless mana.

**Comment by Genoangel** [comment]
Hello , 
The bonus says that it reduces the cost of spells of 10% instead of increasing them by 10% when you are under effect of arcane power.
6097 * 10% = 609. 
6097 - 609 = 5488 
In my screen we see that it cost 6007 instead of 5488.
And i am not talking about arcane alone , Fire doesn't proc hotstreak at all from the set and frost also , but it's harder to provide proofs from screens.

Best regards ,

**Comment by ponpontos** [comment]
Confirming that t12 2p ALWAYS interrupts your casting.

Quite annoying.

**Comment by Genoangel** [comment]
Hello  , 
I have some new infos about the spec Frost & Fire : 
2-Piece Bonus: You have a chance to summon a Mirror Image to assist you in battle for 15 seconds when you cast Frostbolt, Fireball.

4-Piece Bonus: Your spells have an increased chance to trigger Brain Freeze, Hot Streak.

More details : 
The Mirror Image summoned by the mage set (2-piece bonus) does not cause him/her to drop threat. It summons a guardian who appears like the mage and casts Fireballs by his/her side.

Mage 4-piece bonus stats: +15% proc chance to Brain Freeze, +30% chance on single critical effect to Hot Streak.

Source : http://eu.battle.net/wow/fr/forum/topic/2057506151?page=3

**Comment by blinkmaster** [comment]
holy shit 30% increase? gonna reroll back fire if its gonna be repaird ;d

**Comment by Wuxia88** [comment]
Can't wait till it will be repaired. Fire spec gain no benefits from FL eq. 2p interrupting spells and 4p doesn't works at all, still 10% of pyroblast! for whole encounters (tested on 1k fb = ~100 pyro!; 100fb = ~8 pyro!).

**Comment by Jenovas** [comment]
The question is where did you get the number 30% from? I cant seem to find it anywhere. The spell effects on the 4P Bonus also show only -20 (which is the mana reduction) and +15 (which I would guess is for both the Frost and Fire Bonus).

**Comment by ponpontos** [comment]
I believe he was referring to this post: http://eu.battle.net/wow/fr/forum/topic/2057506151?page=3#57. 

I think the set bonuses were changed before actually being released in 4.2 though (the thread in question was posted 1 month before the patch release).

**Comment by Wuxia88** [comment]
Nah it should be +15% chance
http://www.wowdb.com/spells/99064-item-mage-t12-4p-bonus#related:affected-spells

According to my tests hot streak should looks like: ~10% now (imo it is too low but rng i know)
+ 15% 4p bonus

**Comment by Jenovas** [comment]
Fixed in rev 4860

**Comment by blinkmaster** [comment]
Will mirror images stopattack also work after thus?
