### ISSUE TITLE
[PL][ITEM]  [Potion of Treasure Finding]

### ISSUE THREAD

**Issue by Hexenbane89** [Atlantiss/BugTracker#6082]
Potion nie działa w żaden sposób - http://wowwiki.wikia.com/wiki/Potion_of_Treasure_Finding

Powinny dropić z mobków Tiny Treasure Chest - http://www.wowhead.com/item=67539/tiny-treasure-chest

A nie dropią.

**Comment by Aviannaqt** [comment]
#1644
