### ISSUE TITLE
[EN] [ZONE-Teldrassil] [EXPLORING] [ACHIEVEMENT] - Teldrassil, Starbreeze Village

### ISSUE THREAD

**Issue by Sylvictus** [Atlantiss/BugTracker#6083]
Currently the game is not registering that it has been discovered, at least not on the achievement side of it. The portion of the map does become unhidden as far as I can tell, but on the achievement it is listed as not being found, and therefore remains unable to be completed.

**Comment by Sylvictus** [comment]
Why has this been closed, the issue was not reported elsewhere and it is still outstanding.

**Comment by Aviannaqt** [comment]
gm said we don't need more reports about this
