### ISSUE TITLE
[PL][Spell][Mage][Mirror Image]

### ISSUE THREAD

**Issue by Pankaa** [Atlantiss/BugTracker#6091]
Witam, problem z zachowaniem vs spell castowany na nas z użyciem Mirror Image. 

jak dziala: przeciwnik na nas cos castuje=>przyzywamy klony=>gracz(przeciwnik) gubi nasz target ale jesli castowal spell to=>bez targetu/lub z klonem trafia w maga(tego prawdziwego)

jak byc powinno: przeciwnik na nas cos castuje=>przyzywamy klony=>gracz(przeciwnik) gubi nasz target ale jesli castowal spell to cast powinien byc przekazany na klony(cos jak grounding totem)

Co dokladnie jest zle: mimo zgubionego targetu/z klonem mozna swobodnie
dokonczyc cast na maga

Dowody
1.
(PvP)well if someone is casting something onto u and u pop clones. When they
complete their cast it will be directed to ur clone. Yeah, let someone else take
the damage!
http://www.wowhead.com/forums&topic=56067.3

2.
Originally Posted by Statix
So, when a caster mob is casting a spell on you, that spell might suddenly be
interrupted
If I recall correctly, their spell will continue casting - but be wasted on a
random Mirror Image. Never had the time to look that much into it, but I'll test
it when I get time.
http://www.mmo-champion.com/threads/625237-Seriously-disappionted-with-Mirror-Image/page3
3.
Newly cast spells will not be aimed at you if cast after the Mirror Images
appear.
http://forums.elitistjerks.com/topic/30366-wotlk-complete-mage-compendium-333-live/

Moje pierwsze zgloszenie tutaj xD  aha wiem że wpisy są jeszcze z wotlk^^(wtedy dodali klony i kazdy opisywal do czego sa zdolne a zgłoszenie było pierwotnie na sunie) ale zachowanie Mirror image vs spelle nie uległo zmianie brak takiego info: 
http://wowwiki.wikia.com/wiki/Mirror_Image 
http://www.wowhead.com/spell=55342/mirror-image

**Comment by Aviannaqt** [comment]
#5610 
#633
#2059
