### ISSUE TITLE
[EN][Druid][Item] T12 Set Bonus (4p - Resto)

### ISSUE THREAD

**Issue by Azkarus** [Atlantiss/BugTracker#6092]
Hello ,
I would like to report the following bug for the T12 Set (Resto Druid version)

How it should work:
4 pieces: Your Swiftmend also heals an injured target within 15 yards for the same amount.

How it works:
Swiftmend is not healing injured targets,apart from the main target of the spell itself,making the 4P bonus useless.

Tested it both in combat/out of combat and in party/raid

Edit:
Tested in a 10man raid. It does proc but not necessarily on injured targets. It seems to land on 100% hp targets quite often. Can anyone confirm this?

**Comment by adryjan** [comment]
Just find lock to party and some1 else, let him Life Tap and cast swiftmend on yourselv, observe and give us results.

**Comment by Jenovas** [comment]
Fixed in rev 4860
