### ISSUE TITLE
[PL][Achievement] The Explorer

### ISSUE THREAD

**Issue by Radeghost** [Atlantiss/BugTracker#6093]
Nie zalicza wielu obszarow danej mapy do achievementu, np w norther barrens jest to stagnant oasis.
Jezeli trzeba to moge zrobic calego explorera a potem wypisac wszystkie odkryte lokacje, ktorych nie zaliczylo do achievementa.

**Comment by Wolffenstein** [comment]
Nie ma potrzeby, wiemy o problemie oraz co go powoduje.
