### ISSUE TITLE
[en][rogue][spell] Killing Spree

### ISSUE THREAD

**Issue by mcfreddas** [Atlantiss/BugTracker#6097]
http://cata.openwow.com/spell=51690

hey i noticed that when i use killing spree i stay in the front of the mob instead of back.

**Comment by tnarf** [comment]
https://github.com/Atlantiss/BugTracker/issues/4306
i think something like "doubled" 
"i don't know why closed thread":
https://github.com/Atlantiss/BugTracker/issues/4164
