### ISSUE TITLE
[EN][Quest][Elwyn Forest] Cloth and Leather Armor

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6099]
http://www.wowhead.com/quest=59/cloth-and-leather-armor

How it should work: After completing http://www.wowhead.com/quest=71/report-to-thomas, the quest Cloth and Leather Armor should become available, given to you by Guard Thomas (http://www.wowhead.com/npc=261/guard-thomas).
How the quest is bugged: The quest is available without completing the prerequisite. Also, completing Cloth and Leather Armor before the prerequisite quest will bug the prerequisite quest ( http://www.wowhead.com/quest=71/report-to-thomas ) and you won't be able to take it  anymore.
Also, the quest Cloth and Leather is given to you by Marshal Dugan (http://www.wowhead.com/npc=240/marshal-dughan) while you should be able to take the quest only from Guard Thomas.

**Comment by Sylvictus** [comment]
I just experienced this bug. It kind of made me really mad to be honest that I couldn't finish the quest line after discover rolfe's fate. Highly annoying and unnecessary, please fix it asap. So much for "polishing" elwynn forrest.
