### ISSUE TITLE
[EN][NPC] Twilight Recruit

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#610]
Interacting with **Twilight Recruit** (http://www.wowhead.com/npc=39619) will make them follow you indefinitely. 

This shouldn't be the case.

They (or well, ONE of them) should follow you when you're on a quest **Signed In Blood** (http://www.wowhead.com/quest=25274), but here, you can interact with them regardless if you have the quest or not.

When you pick up the quest Signed in Blood (http://www.wowhead.com/quest=25274), several Twilight Recruits (http://www.wowhead.com/npc=39619) (They're the objective for the quest) spawn right at the quest giver, but that shouldn't happen.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/608
