### ISSUE TITLE
[EN][Quest][Elwyn Forest] Westbrook Garrison Needs Help!

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6101]
http://www.wowhead.com/quest=239/westbrook-garrison-needs-help

How it should work: The quest should become available only after completing the questline ending with
http://www.wowhead.com/quest=76/the-jasperlode-mine .
How it is bugged: The quest is available without completing the prerequisite.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8051-6101questelwyn-forest-westbrook-garrison-needs-help/
