### ISSUE TITLE
[EN] Chakra: Serenity and Renew refresh

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#6103]
The issue is with Glyph of Power Word: Shield. The glyph makes a heal equal to 20% of the absorbtion amount when you cast PW: Shield. The heal should refresh Renew when in Shakra: Serenity.

Chakra: Serenity: http://www.wowhead.com/spell=81208/chakra-serenity
Power Word: Shield: http://www.wowhead.com/item=42408/glyph-of-power-word-shield

Proof: http://us.battle.net/wow/en/forum/topic/4837134084
"Renew uptime is really good for Holy Priests and helps manage spread pressure quite well. Furthermore, since you'll be in Chakra: Serenity, direct healing spells refresh Renew, including the heal fromGlyph of Power Word: Shield."

**Comment by lamaATS** [comment]
Fixed in rev. 5224

**Comment by BialyADI** [comment]
@lamaATS Zbugowałeś Chakra: Serenity teraz Renew jest odświerzany tez przez AoE Heale i Taki prist moze mieć Renew na całym Rajdze odświerzjąc je Circle of Healing, Preyer of Healing i Prayer of Mending mimo że są to AoE Heale.

**Comment by BialyADI** [comment]
Teraz wystarczy jeden Prej by wyleczył cały rajd ;D.

**Comment by lamaATS** [comment]
Dzięki za report ale ogóle potrzebuje `whitelist` czyli to z czego powinno wchodzić czyli jak zrobie spelle:
```
Heal
Flash Heal
Greater Heal
Binding Heal
Prayer of Healing
Prayer of Mending
Glyph of Power Word: Shield
```
Będzie poprawnie?

**Comment by BialyADI** [comment]
Prayer of Healing
Prayer of Mending
są na 100% AoE Hilami i przed zmianą nie odnawiały Renew.

**Comment by BialyADI** [comment]
Aaa zapomniałem o Holy Word: Serenity.
reasumując Direct Heale:
Heal
Flash Heal
Greater Heal
Holy Word: Serenity
i Glyph of Power Word: Shield (to co dotyczyło zgłoszenie)

**Comment by kadi2** [comment]
>>Cataclysm Patch 4.0.6 (2011-02-08): Chakra states now last 1 minute, up from 30 seconds.
 [Binding Heal] and  [Holy Word: Serenity] now refresh the duration of  [Renew] on the target, in addition to the other direct heals.

**Comment by BialyADI** [comment]
http://wow.gamepedia.com/Chakra tu jest.
No i git czyli Binding Heal się wyjaśnił.

Reasumując Heale które powinny odnawiać Renew gdy ma się [Chakra: Serenity]:
Heal
Flash Heal
Greater Heal
Holy Word: Serenity
Binding Heal
i Glyph of Power Word: Shield (to co dotyczyło zgłoszenie)
I tyle teraz jest to nieźle przegięte.

**Comment by lamaATS** [comment]
Jeśli jesteście w stanie sprawdzić to na maine (tak nie jest wymagany restart do tej zmiany).

**Comment by BialyADI** [comment]
Teraz już poprawka działa?

**Comment by lamaATS** [comment]
Tak.

**Comment by BialyADI** [comment]
Jest okej Renew jest odświeżany tylko przez Direct Heale i Binding Heal na obu targetach,
zgodnie z tym tu http://wow.gamepedia.com/Chakra.
Więc jest wszystko ok, nieźle bez restartu ^^.

Jak będziesz miał jeszcze wenę zobacz co u napisałem na temat Charge/Intercepta/Intervene.
https://github.com/Atlantiss/BugTracker/issues/3499.

**Comment by BialyADI** [comment]
Bo zgłoszenie jest tylko na Charge ale to dotyczy też Intercepta i Intervene.

**Comment by lamaATS** [comment]
`Intercept stunuje przed dotarciem do target, Charge działa pięknie.`
Lokalnie poprawione ale jak coś nowe issue bo spamowanie na inne tematy nie pomaga na bt i tak naprawdę powinienem to usunać bo nie na temat.

**Comment by BialyADI** [comment]
No oki jak coś będę otwierał nowe zgłoszenia ;p.
