### ISSUE TITLE
[PL][Glyph] Glyph of Freezing Trap

### ISSUE THREAD

**Issue by Parwers** [Atlantiss/BugTracker#6105]
Witam 
♦ Glyph of Freezing Trap  powinien  spowalniać  70 %, a nie spowalnia w ogóle
http://www.wowhead.com/item=42905/glyph-of-freezing-trap
http://www.wowhead.com/spell=56845/glyph-of-freezing-trap

**Comment by Shanrolol** [comment]
True, this glyph's not working properly. When the trap is broken, there's no slow debuff.
