### ISSUE TITLE
[EN][Quest] Death to the broodmother

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#611]
Quest **Death to the Broodmother** (http://www.wowhead.com/quest=25553) auto-completes when you take it, so you can just turn it in right away. This shouldn't be the case.

How it should work is that you need to go to the designated place, and use **Young twilight drake skull** (http://www.wowhead.com/item=55173), this should lure **Desperiona** (http://www.wowhead.com/npc=40974), and killing her should complete the quest.

**Comment by ahtebe** [comment]
Desperiona is lured but as soon as the NPC enters combat it exits and "flees". While fleeing the NPC can't be attacked so it is not possible to kill it.
The quest is auto-completed anyway.

**Comment by biaicc98** [comment]
Still auto-complete.

**Comment by Aival94** [comment]
How it should work: [Death to the Broodmother](https://youtu.be/gU2TTusrdkE)

**Comment by LaveniaGithub** [comment]
A new report has been made with our new template: https://github.com/Atlantiss/BugTracker/issues/8528
