### ISSUE TITLE
[EN][Quest][Horde][Stonetalon Mountains]  We're Here To Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by Rockyboy97** [Atlantiss/BugTracker#6110]
This quest is located in Ashenvale at the Silverwind Refuge. The quest is given from Blood Guard Aldo Rockrain. The description says: "Takr the Krom' Gar Wagon to the old in Stonetalon Mountains." 

1st Bug: When you enter the Krom' Gar Wagon, two of them spawn and ride the route you're suppose to take. http://steamcommunity.com/sharedfiles/filedetails/?id=609428871

2nd Bug: While entering Talondeep Pass, a Sentinel Ambusher attack the wagon. Once he begins attacking the wagon you're on, the wagon freezes and you cannot leave it so you just end up dying. http://steamcommunity.com/sharedfiles/filedetails/?id=609428884

This has happened to another person that is in my guild and it's very frustrating that something like this hasn't been fixed yet.

**Comment by RandomPickNewb** [comment]
That quest has been bugged for quite some time so there might be another bug report.
Also read https://github.com/Atlantiss/BugTracker and change title.

**Comment by thissideup-atlantiss** [comment]
Quest is completable by starting from The Fold and running back to Silverwind Refuge (preferably on a mount) the same path the Wagon is taking. If you take out the two Sentinal Ambushers in the Crag (one right and one left of the road) and the two Ashenvale Assassins right outside the Skunkworks, the Wagon will ride right through to The Fold.

**Comment by Aival94** [comment]
The second bug is reported here as well: https://github.com/Atlantiss/BugTracker/issues/4972
