### ISSUE TITLE
[EN][Quest][Westfall] Shakedown at the Saldean's

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6113]
http://www.wowhead.com/quest=26236/shakedown-at-the-saldeans

How it should work: According to http://wowwiki.wikia.com/wiki/Quest%3AShakedown_at_the_Saldean's , this quest is part of a quest chain and should become available only after completing the prerequisite, http://wowwiki.wikia.com/wiki/Quest:Lou%27s_Parting_Thoughts .
How is the quest bugged: The quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10963-quest-a-strange-device-shakedown-at-the-saldeans/

**Comment by aje** [comment]
fixed in revision 5115
