### ISSUE TITLE
[EN][Quest][Westfall] Hope for the People

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6114]
http://wowwiki.wikia.com/wiki/Quest:Hope_for_the_People

How it should work: This quest should become available only after completing the prerequisite, http://wowwiki.wikia.com/wiki/Quest:You_Have_Our_Thanks .
How it is bugged: The quest is available after completing http://wowwiki.wikia.com/wiki/Quest:Shakedown_at_the_Saldean%27s

**Comment by user1011** [comment]
Confirmed. Bump.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10947-quest-hope-for-the-people/

**Comment by aje** [comment]
fixed in revision 5115
