### ISSUE TITLE
[PL][Core][Pet] Pet atack range(?)

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#6115]
Po ostatnich optymalizacjach petów zdarza się że nie biją albo robią strasznie mało ataków/skilli.
Zauważyłem to na BH na 2 bossie gdzie felguard nie zadał żadnego dmg felhunter użył 2 shadow bite i miał 0 ataków. U 2 locka felguard też nie zadał dmg a felhunter użył 3 shadow bite i zrobił 6 ataków, a także pet huntera nie zadał żadnego dmg.
![wowscrnshot_012716_150356](https://cloud.githubusercontent.com/assets/9517740/12615655/3f866a12-c507-11e5-8ead-b236943a560a.jpg)

Później poszedłem na 2 Bh aby sprawdzić czy to tylko jednorazowy przypadek ale było podobnie.
Tym razem Felunter u obu locków bił ale felguard nadal nie, na 4 hunterów żaden z petów nie bił,
a ghoul udk bił normalnie.
![wowscrnshot_012716_150352](https://cloud.githubusercontent.com/assets/9517740/12615662/4b3a4a54-c507-11e5-86fc-78b7f7c37ed3.jpg)

Możliwe że pety ustawiają sie za daleko od bossów co mają większy hitbox.

**Comment by Mordorianin** [comment]
Zobacz sobie gdzie stoi Twój pet na BH, a dopiero później pisz temat na bugtrackerze.
Pety ustawiają się na obrębie sali i stoją jak debile. Tylko komenda "move to" działa - i wtedy gdy pet jest w range'u bossa, możesz dać komendę "petattack".

**Comment by BialyADI** [comment]
Sam zasięg ataku peta jest ok, przynajmniej w pvp ;p.

**Comment by Bildo** [comment]
to wina zlych mmap problem wystepuje tylko na bh po crashu bedzie ok
