### ISSUE TITLE
[EN][Hunter] Tier 12 4set Bonus vs. Lock and Load

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#6119]
Explosive shots during lock and load should not consume 4set proc since those 2 shots are already free, gonna post proof soon.
http://www.wowhead.com/spell=99059
Edit: Currently only the first explosive shot in lnl consumes 4set proc, second shot works fine and it doesn't consume

**Comment by lqlq32** [comment]
+1, it should be consumed only from shots that req focus, prob its broken for free aimed shots on marksman too, dont have 4p to test it.

**Comment by anxanas** [comment]
It doesnt consume the set bonus with me when i use LnD with it up.

**Comment by anxanas** [comment]
It doesnt consume the set bonus if lock and load procs before the set bonus, only if it procs after =))

**Comment by lamaATS** [comment]
Fixed in rev. 5498
