### ISSUE TITLE
[EN][Talent][Warrior] Sudden death

### ISSUE THREAD

**Issue by petran123** [Atlantiss/BugTracker#6123]
Right now sudden death ignores the base 10 rage cost of the ability and doesn't refund it. But on retail, sudden death's execute part would keep the warrior at 10 rage even if the warrior only spent 10 rage for execute.

**Comment by Aviannaqt** [comment]
links

**Comment by petran123** [comment]
[Sudden death rank 1](http://cata.openwow.com/spell=29723)
[Sudden death rank 2](http://cata.openwow.com/spell=29725)
[Execute](http://cata.openwow.com/spell=5308)

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
