### ISSUE TITLE
[EN][Quest][Ahenvale][they took our gnomes]

### ISSUE THREAD

**Issue by macmas** [Atlantiss/BugTracker#6126]
this quest not working

**Comment by Aviannaqt** [comment]
read bt rules

**Comment by macmas** [comment]
![wowscrnshot_012816_190729](https://cloud.githubusercontent.com/assets/16924032/12654122/e8508a7e-c5f2-11e5-93e2-36fb20af363b.jpg)

**Comment by macmas** [comment]
![wowscrnshot_012816_191346](https://cloud.githubusercontent.com/assets/16924032/12654195/46a2dcb2-c5f3-11e5-97c6-ff66e887d8d0.jpg)
![wowscrnshot_012816_191332](https://cloud.githubusercontent.com/assets/16924032/12654215/52994556-c5f3-11e5-8384-91533ee4a446.jpg)

**Comment by macmas** [comment]
taueren stay in second caravan
