### ISSUE TITLE
[PL]Firelands hatchery [PORTAL]

### ISSUE THREAD

**Issue by Hexenbane89** [Atlantiss/BugTracker#6127]
Portal powrotny z Firelands hatchery nie działa, to już chyb 6 raz jak ktoś to zgłasza i nadal nikt tego nie naprawił. tak samo portal z Twilight Higlands też nie działa, jaja sobie robicie? niby cata a 50% zbugowane albo nie działa -.-

**Comment by Luna-maria** [comment]
#5397
#605
