### ISSUE TITLE
[EN][Achievement][Silithus] Explore Silithus

### ISSUE THREAD

**Issue by gurin** [Atlantiss/BugTracker#6128]
2nd try.

http://www.wowhead.com/achievement=856/explore-silithus

The Scarab Wall doesn't count.

http://i.imgur.com/KQ9SKDE.jpg

Aviannaqt stop closing issues without a reason.

**Comment by Aviannaqt** [comment]
#6093 ???

**Comment by gurin** [comment]
It's closed too. So search gives nothing. Peace ;)
