### ISSUE TITLE
[en][npc][vendor][item]justice points cloak/back cost

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#6129]
backs like http://www.wowhead.com/item=58194/heavenly-breeze should cost 1250 on content 4.2 not 1650 jp

**Comment by user1011** [comment]
Only heavenly breeze should be 1250 JP? What about the other items?

Perhaps a link to the NPC who sells them?

Thank you.

**Comment by stanq87** [comment]
http://wow.gamepedia.com/Cataclysm_Justice_Points_gear or use addon like atlasloot from 4.2 ?  or inspect equip ?  or even rawr has that data

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12979-6129-justice-poinst-cloak-cost/
