### ISSUE TITLE
[EN][Client] Random WoW-Errors after shutdown

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#6131]
After 29/01/2016 testing stopped,random wow-errors started popping up to me(and also many others).
It happend to me 2 times while questing in Molten Front and I had to use unstuck from website.

**Comment by Syroh94** [comment]
the same happend to me, I cant play, wherever i go there, critical bug and game client shutdown, im lvling in stranglethorn

**Comment by Scorpiuss** [comment]
The same happened to me , my nick ingame Scorpiuss , im lvling in Mount Hyjal

**Comment by krecik88** [comment]
shoudl be ok now
