### ISSUE TITLE
Errors after shutdown.

### ISSUE THREAD

**Issue by Retrolama** [Atlantiss/BugTracker#6132]
After the shutdowns today i start getting errors after i log in to game.
![bez nazvu](https://cloud.githubusercontent.com/assets/16955846/12674465/7af0dbd2-c683-11e5-997c-afb3ab199413.png)

**Comment by jurgen87** [comment]
Have the same problem but only one character.

**Comment by OnionTron88** [comment]
I have this problem

**Comment by Retrolama** [comment]
All my characters have this problem. ( have 2 characters)

**Comment by Retrolama** [comment]
New create char is ok.

**Comment by Retrolama** [comment]
I create new char then delete him and is ok now.

**Comment by krecik88** [comment]
shoudl be ok now
