### ISSUE TITLE
[EN][Item] Engineering, problem with formula of "Copper Tube" 

### ISSUE THREAD

**Issue by kolga1** [Atlantiss/BugTracker#6133]
The engineering trainer teaches the formula of "Copper Tube", but the item doesn't show in the profession list. Cleaning the cache file, forgetting the profession and restarting it doesn't resolve the problem, the formula is still considered as already learned.
http://www.wowhead.com/item=4361/bent-copper-tube#created-by-spell

**Comment by ponpontos** [comment]
That item was removed on 4.3 I believe, had the same problem. Just use something else to get these levels.
