### ISSUE TITLE
[PL] Error 132

### ISSUE THREAD

**Issue by Polownik** [Atlantiss/BugTracker#6135]
Po wczytaniu się lokacji od razu wyskoczył mi error 132.
Wcześniejszego dnia nie miałem żadnych podobnych problemów;
moja postać znajduje się w Stormwind, zaraz przy npc flight master.
**![error](https://cloud.githubusercontent.com/assets/16955750/12674419/25004564-c683-11e5-8141-0cbb8a672058.PNG)

**Comment by BAndysc** [comment]
Sprawdź proszę teraz czy możesz wejść na serwer

**Comment by krecik88** [comment]
shoudl be ok now
