### ISSUE TITLE
    problem z questem  "The Last of Her Kind"

### ISSUE THREAD

**Issue by faustion** [Atlantiss/BugTracker#6140]
Icemaw Matriarch jest nieobecna  w swojej lokacji czyli  the Hibernal Cavern.

**Comment by Thefakemccoy** [comment]
Duplicate https://github.com/Atlantiss/BugTracker/issues/4309

**Comment by faustion** [comment]
Thefakemccoy ty masz mistrzu coś z głową? jaki duplicate? zobacz   raz na daty   dwa na to że tamte  zostały pozamykane A PROBLEM DALEJ ISTNIEJE!!!!

**Comment by Navedonar** [comment]
po pierwsze zasady bt po drugie https://github.com/Atlantiss/BugTracker/issues/4309

**Comment by faustion** [comment]
ok   now  i hawe  question why! THIS PROBLEM  WAS CLOSED WHEN  IS  STIL IN THE WORK????

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/4309 jest otwarte nie ma potrzeby robienia 5 zgłoszeń do tego samego questa
