### ISSUE TITLE
[PL][QUEST][TBC][TELEPORT THIS!]

### ISSUE THREAD

**Issue by rafal363** [Atlantiss/BugTracker#6144]
Witam 
nie zalicza nam  zniszczenia zachodniego teleportu. przewaznie nie da sie da zaczarowac mobka aby nim zniszczyc teleport 
https://www.youtube.com/watch?v=OEH56UcYuDY

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/2858
