### ISSUE TITLE
[EN][Dungeon][Halls of Origination] Snakes are currently bugged.

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#6145]
The snakes in the first boss fight are bugged. The old snakes were bugged because they didn't come up but the current snakes are bugged also. They come up regardless if anyone goes down to levers, but they are suppose to aggro like normal mobs. 

Meaning you can run to stairs, hug the wall, pull the lever, and come back to boss with only maybe 1-2 snakes ( 3-4 snakes with a bad dps who didn't hug the wall).

It currently makes it impossible for a new heroic healer to heal this fight.

**Comment by Aviannaqt** [comment]
Its move map bug
