### ISSUE TITLE
[PL][ARENA]Nagrand Arena filary.

### ISSUE THREAD

**Issue by Caadu** [Atlantiss/BugTracker#6146]
Witam. Dziś po południu, grając areny udało mi się wychwycić, że Nagrand Arena jest mocno dziurawa. Pierwsza sprawa - szarżujący feral, który przy kolumnie bardzo często wpada pod tekstury. Jednakże nie to jest najbardziej irytujące. Spelle typu Dragon's Breath ( http://www.wowhead.com/spell=31661/dragons-breath ) czysto przechodzą przez kolumny i nie mówię tu o kantach kolumn tylko o całej ich grubości

**Comment by BialyADI** [comment]
To nie chodzi o Arene zwyczajnie, jest już zgłoszone że Dragon's Breath i Clone of Cold Maga napierdziela przez ściany ale nic z tym nie zrobili narazie ;x.
