### ISSUE TITLE
[PL] [Quest] DK quest bug (Brothers in death)

### ISSUE THREAD

**Issue by kaco120** [Atlantiss/BugTracker#6147]
Koltira deathweawer jest zespawnowany gdzieś w teksturach. nie ma go na miejscu,ale mozna go zaznaczyc komenda /target

**Comment by kaco120** [comment]
Zbindowałem klawisz do interacji z targetem. mając go zaznaczonego ,wchodzę w interakcję i wyskakuję napis,że powinienem podejść bliżej

**Comment by Thefakemccoy** [comment]
The respawn timer seems to be to long.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1932

**Comment by XrayAlert05** [comment]
quest dalej nie działa
