### ISSUE TITLE
[ENG][LOCATION]Obsidian Forest [Twilight Highlands]

### ISSUE THREAD

**Issue by Hexenbane89** [Atlantiss/BugTracker#6150]
Hi

Bug: There is no mobs here,not even one!
http://www.wowhead.com/npc=47797/obsidian-charscale
http://www.wowhead.com/npc=46141/obsidian-pyrewing
http://www.wowhead.com/npc=47796/obsidian-viletongue

People why? -.- Pls add this mobs, cant do any quest, cant skinning them. its not Cataclysm, its a Joke.

**Comment by RandomPickNewb** [comment]
There are no mobs there because TH isnt finished.There is also no quest that sends you to that area.
