### ISSUE TITLE
[EN][One With the Ground (Part 2 of 7)][Deepholm]

### ISSUE THREAD

**Issue by syndicate83** [Atlantiss/BugTracker#6152]
Completed this quest, however I can not click complete when where the "?" is.  I disabled addons but to no conclusion.  This quest is key important to finishing quests in Deepholm.   This is suppose to complete then a new quest pops out as Bring Down the Avalanche (Part 1).  I remember when I did this quest with my alts...there were 2 NPC Slate Quicksand giving different quests however now its just one there at coordinate 30.4 ,77.9

**Comment by Aival94** [comment]
Are you sure is the first time you did the quest as there is a bug about getting the quest again after completing the [Bring Down the Avalanche](http://www.wowhead.com/quest=27935/bring-down-the-avalanche).More info here: https://github.com/Atlantiss/BugTracker/issues/787
Other bugs about this quest: https://github.com/Atlantiss/BugTracker/issues/5876

**Comment by syndicate83** [comment]
You are correct, the original quest of One With the Ground did not update to complete but  Bring Down the Avalanche one did pop up.  Killed NPC with and got a complete for both.  Could not turn neither in, tried clear cached dropping and relogging.  Quest chain is now broken for toon.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/787
