### ISSUE TITLE
[EN][Without A Captain or Crew][Deepholm]

### ISSUE THREAD

**Issue by syndicate83** [Atlantiss/BugTracker#6153]
Quest is on board the alliance airship.  I didn't not pick up quest but it shows up as a Yellow Question Mark as in Completed quests.  When you interact with the NPC First Mate Moody, he requires Bottle of Whiskey and Spool of Rope.  They are both on board the airship, you can't loot the items, they disappear after looting and reappear as someone looted it.  Questlog also does not have the quest on toon.  Need this quest please.

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/3511
