### ISSUE TITLE
[EN][Talent][Mage] Early Frost

### ISSUE THREAD

**Issue by rabbiterino** [Atlantiss/BugTracker#6155]
This talent is meant to activate once you finish casting the spell that mages have, "Frostbolt". What it does, is reduce the cast time for frostbolt. This is done so that the first frostbolt sent is sent with faster cast time. But, when you cast and then move, without finishing the cast, (which is nominated as a fake cast), with uses for pvp, so that you get counterspelled accidentaly, and can counter the opponent for example, the talent function is already used, and you get the default frostbolt cast time.

**Comment by kadi2** [comment]
This is how it worked on retail. At the beginning of cata you were able to cast  speeded frostbolt twice and they hotfixed it. #8

**Comment by Jenovas** [comment]
Works as it should.

**Comment by Jenovas** [comment]
http://eu.battle.net/wow/en/forum/topic/1124803596
