### ISSUE TITLE
[EN][Spell][CC]

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6158]
So I looked into it and Crowd Control spells such as Hex, Polymorph, Freezing Trap etc. will not bring creatures into combat when cast. That was because they wanted to avoid creatures from being pulled if the CC lands before the actual pull.

Anyway here's the patch note and it doesn't say anything about it should happen to players aswell, which is why casting these spells should bring both the caster AND the player in combat.

Link to patch notes: http://eu.battle.net/wow/en/game/patch-notes/4-2-0

"Many crowd control abilities no longer cause creatures to attack players when they are cast. The creature will not attack the player when the crowd control wears off, and nearby creatures will not become hostile to the player either. However, if a visible player gets too close to the target creature, the creature will remember and attack the player when the crowd control effect wears off. The intent is to make it easier for dungeon groups to manage crowd control assignments and pulling packs of hostile NPCs. The abilities affected by this change are: Hibernate, Entangling Roots, Wyvern Sting (will still cause hostility when it begins to deal damage), Freezing Trap, Polymorph, Repentance, Shackle Undead, Blind, Hex, Bind Elemental, Banish, Seduction."

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/6139

**Comment by Fearyourself** [comment]
It was closed.

**Comment by kadi2** [comment]
You have to find video proof for that. Patch notes are not enough.

**Comment by Fearyourself** [comment]
Seriously? How am I supposed to find video proof of a mage polymorphing a player two times and drinks right after?

**Comment by Jenovas** [comment]
There are topics on blizzard forums where ppl say this happens in PvP.
Topic is getting closed. Do some research, find proof that it should give combat and create a topic.
Until you provide us with proof all topics like this will be closed. Cheers.

**Comment by Fearyourself** [comment]
I made a bugtracker a while back and when I gave you guys a link of people saying it wasn't supposed to be like that, you said it didn't matter about peoples opinions and that I would have to find patch notes. Here's patch notes for this issue and now you're not doing anything about it?
I'm confused... It clearly states this should only happen in pve, how can you even consider closing the thread? This is just weird man.

Thanks for replying so fast.

**Comment by Jenovas** [comment]
The patch notes do not state anything about PvP. They do not say that in PvP it will work like this, they do not state it wont. After reading other topics from blizzard forums and not only, players state that after this change in PvE it also changed for PvP. Also if you check bugtrackers of other servers you will find more stuff that prove that in PvP CC shouldnt give combat.

**Comment by Fearyourself** [comment]
Is it not simple? Before the patch update players and creatures would get in combat if CC used on them. Then there's an update and the patch says creatures won't come in combat with the caster. It doesn't get more simple than that... I'm not talking about other private servers, I just thought ya'all wanted blizzlike that's all.

One more question; If there's a bug on retail 4.3.4. patch, would you rather leave it like Blizzard did to be 100% blizzlike or would you fix it?

**Comment by kadi2** [comment]
https://youtu.be/sQj3_jnjCdg?t=1m22s Example with Rinf of Frost. Which still puts you in combat on atlantiss.

**Comment by Jenovas** [comment]
Fearyourself - yes it is simple. This is not a bug. CC should not give combat.
