### ISSUE TITLE
[EN][Spell][Death Knight]Army of the Dead(ID 42650)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6159]
Spell is working as it spawn the Ghouls but the Ghouls should be able to taunt everything near them except from the bosses when they first summoned but they do not.Furthermore the Ghouls stop attack after killing first mob they targeted and i believe their damage is too low as it does not have the proper stats upon the summoning.

Related to: https://github.com/Atlantiss/BugTracker/issues/3791
Wowhead Link: [Army of the Dead](http://www.wowhead.com/spell=42650/army-of-the-dead)

**Comment by Kejmil** [comment]
still no taunt, claw or proper stats from owner

**Comment by Jenovas** [comment]
Taunt, Claw, Leap added in rev 5080.
This report did not show any proof about how the Ghouls should scale with stats.
Closing report if you find proof about scaling please create a new report.
