### ISSUE TITLE
[EN][Spell][Druid] Eclipse - kolejny bug.

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#6161]
Grając dziś napotkałem kolejny bug dotyczący Eclipse. Gdy po zalogowaniu wbijemy Solar Eclipse, a następnie wyczarujemy jeden Starsurge, jeden Wrath oraz 9 Sunfire, które są pod wpływem Lunar Shower ustawimy pasek Eclipse na zero. W takiej sytuacji jeśli wyczarujemy znów Starsurge, to czar cofnie nas z powrotem w stronę Solar Eclipse, a powinien pchać nas w stronę Lunar Eclipse.

Jak odtworzyć bug ? Wejdź w Solar Eclipse, a następnie wyczaruj 1 Starsurge, 1 Wrath oraz 9 Sunfire pod wpływem Lunar Shower. Gdy Eclipse będzie na zero wyczaruj Starsurge. Voilà !

http://cata.openwow.com/spell=80745

**Comment by Astrobazooka** [comment]
Ps. Zacznijcie ogarniać Eclipse, ponieważ przez te wszystkie bugi spec jest praktycznie niegrywalny. Zaznaczam, że mówię o PvP. W PvE te bugi nie mają większego znaczenia.
https://github.com/Atlantiss/BugTracker/issues/4034
https://github.com/Atlantiss/BugTracker/issues/132
https://github.com/Atlantiss/BugTracker/issues/5296
https://github.com/Atlantiss/BugTracker/issues/5297

**Comment by PierwszyKrytykRP** [comment]
Na "ogarnianie Eclipse" się zbytnio nie nastawiaj. Wolff kiedyś powiedział (parafrazując), że eclipse jest rozjebane po wielu plikach i syf w związku z tym jest

**Comment by Astrobazooka** [comment]
Tragiczna sprawa w takim razie. Mogliby chociaż naprawić cztery części pvp, ponieważ przez ten bug Moonkin ma ogromne problemy z maną, a do tego dochodzi jeszcze żałosny Typhoon. Moonkin wymaga porządnego changelog'a i tyle.

**Comment by BialyADI** [comment]
Przy okazji 2 części setu PvP Balance i Resto stackują bonus do Resilience podobnie jest u Szamana i Preja.

**Comment by Jenovas** [comment]
Fixed in rev 4860
