### ISSUE TITLE
[en][mage][spell] Ice Barrier absorb

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6162]
according to http://www.wowhead.com/spell=11426/ice-barrier#comments
Ice Barrier has a sweet buff in 4.1.0. It's base absorb at 85 has gone up to 8069, from 3687. Also, the coefficient has gone up slightly, from 80.7% of spell power to 87% of spell power. This buff definitely makes this spell provide a real survivability barrier."

and the tooltip in wow which says exactly how much i should get (0.87x8700 + 8069 = 15638) my absorb in buff says it will absorb 15091 damage and it indeed absorb this. SO every ice barrier usage i am loosing more than 500absorb which is huge overall. My guess is it still have old coeff of 80,7% SP

**Comment by Wolffenstein** [comment]
Tooltip says 87%, but in the game files, Ice Barrier has SP Coeff 86.088%. I don't know whether Blizzard messed up the tooltip or the game files, I'm gonna assume it works fine and just the tooltip is wrong.

**Comment by Wolffenstein** [comment]
Fixed in rev 4852.
