### ISSUE TITLE
[PL][Quest][Firelands Invasion] The Forlorn Spire

### ISSUE THREAD

**Issue by hanibbal** [Atlantiss/BugTracker#6163]
Quest jest zbugowany, add **Forlorn Spire** którego trzeba zabić by zaliczyć questa nie respawnuje sie. Pojawia się tylko po DC servera i jak zostanie zabity juz sie nie respawnuje. Prz to nie można zaliczyć questa ani odblokować pozostałych daily by zdobyć **Mark of the World Tree**.

**Comment by Luna-maria** [comment]
#5926 #5727
