### ISSUE TITLE
[NPC][Elwynn Forest]Falkhaan Isenstrider

### ISSUE THREAD

**Issue by Navedonar** [Atlantiss/BugTracker#6164]
http://www.wowhead.com/npc=6774/falkhaan-isenstrider#comments
Stoi w nieprawidłowym miejscu dopiero w wod zmieniono jego pozycje.
Patch 6.0.2 (2014-10-14): Moved outside of the entrance to Northshire Valley, no longer standing in front of the fountain.

**Comment by Wolffenstein** [comment]
Fixed in rev 4855.
