### ISSUE TITLE
[EN][Quest][Loch Modan] In Defense of the King's Lands

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6165]
http://www.wowhead.com/quest=26146/in-defense-of-the-kings-lands
How it should work: This quest is part of a quest chain and should become available only after completing the quest http://www.wowhead.com/quest=13635/south-gate-status-report .
How it is bugged: The quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10948-questin-defense-of-the-kings-lands/

**Comment by aje** [comment]
fixed in revision 5115
