### ISSUE TITLE
[EN][Quest][Loch Modan] Out of Gnoll-where

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6166]
http://www.wowhead.com/quest=26842/out-of-gnoll-where
How it should work: This quest is part of a quest chain and should become available only after completing http://www.wowhead.com/quest=26176/onward-to-thelsamar .
How it is bugged: This quest is available without completing the prerequisite quest.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10949-quest-out-of-gnoll-where/

**Comment by aje** [comment]
fixed in revision 5115
