### ISSUE TITLE
[PL][Zone] Redukcja Heala/Absorbu - Tol Barad/Twin Peaks.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6168]
Na Tol Barad i Bg Twin Peaks nie działa 10% Redukcji Heala/Absorbu które powinno działać na wszystkich PvP zone/Arenach i Bg.
Testowałem to na DK i jego Death Strike i Rune Tap i bandażach.

Jeszcze jedna ciekawa rzecz na Wintergraps 10% redukcji Heala działa a na Tol Barad już nie.

**Comment by Wolffenstein** [comment]
Fixed in rev 4854.
