### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] The Warp Rifts

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#617]
# What is not working (Minor bug):

The current model of the warp rift is wrong.

---
# How should work:

Basically, it should have the same model on retail. Some sort of black magic ball...

---
# More info:

[Screenshot](http://i.imgur.com/beiJDTk.jpg)
[Video](https://www.youtube.com/watch?v=UQZ1qNSzPpg)
[The Warp Rifts - WoWHead](http://www.wowhead.com/quest=10278/the-warp-rifts)
[The Warp Rifts - WoWPedia](http://wow.gamepedia.com/Quest:The_Warp_Rifts)
[Void Spawner](http://www.wowhead.com/npc=20143)

**This was tested on 4.0.6a realm**

**Comment by Malylolek** [comment]
Quest item should spawn only 1 quest mob.
