### ISSUE TITLE
[PL][ARENA] Brak redukcji Absorbów.

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6170]
Redukcja Absorbów na arenach nie działa, 10% redukcji powinno obejmować nie tylko healing, również PWS, Ice Barrier, Mana Shield, Sacred Shield, Stoneclaw Totem Itp.

**Comment by BialyADI** [comment]
https://github.com/TrinityCore/TrinityCore/issues/4358

Tutaj podobny problem mieli.
Bardzo ważny problem.

**Comment by Wolffenstein** [comment]
Fixed in rev 4854.

**Comment by BialyADI** [comment]
Wow. Ekspresowo good work men :).

**Comment by BialyADI** [comment]
Jest jeszcze możliwość zaimplementować to do https://github.com/Atlantiss/BugTracker/issues/6168?
