### ISSUE TITLE
[PL][PASSIVE][DRUID]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6174]
Savage defence ma 100% szansy na odpalenie absorbu przy critach "non periodic dmg" a powinno mieć 50% (Testowane na każdym non preodic ataku druida). PLS FIX ASAP, mele klasy, których dmg opiera się głównie na Physical Dmgu nie są w stanie zabić druida w misiu, każdy crit misia powoduje 7-8k Physical absorbu.

**Comment by Wolffenstein** [comment]
Fixed in rev 4855.
