### ISSUE TITLE
[EN][Shadowmoon Valley] Crashes in Netherwing Ledge

### ISSUE THREAD

**Issue by RelmAtlantiss** [Atlantiss/BugTracker#6176]
Crashes often occur when I try to do A Slow Death quest (Netherwind rep grind). I read that adding `SET fixedfunction "1"` to Config.wtf can solve the problem - it lowers my FPS from 140 to 70 so I won't use it.

Logs:
http://pastebin.com/fdKqdgHB
http://pastebin.com/iV5QrzD7
http://pastebin.com/JCGWyzLW
http://pastebin.com/MUDyDY6t
http://pastebin.com/694SVhip

**Comment by Anhaeyn** [comment]
It was already reported. Fastest way to farm rep - collect eggs, screw this quest. If you'll farm it a lot, you can get exalted in 1 day.

**Comment by RelmAtlantiss** [comment]
It wasn't reported on BugTracker (I didn't find any reports).
You can do this quest while eggs are respawning for a little bit more rep :)

**Comment by Anhaeyn** [comment]
https://github.com/Atlantiss/BugTracker/issues/4290

**Comment by RelmAtlantiss** [comment]
Crashes aren't connected to A Slow Death quest though, because it keeps crashing even if you don't have the quest in quest log (I've checked). I thought it may have something to do with Dragonmaw Illusion buff - I've checked that on different character, still crashing. It has to be zone bug then.
