### ISSUE TITLE
[EN][achievement] achievement gone after faction change

### ISSUE THREAD

**Issue by Muhiqt** [Atlantiss/BugTracker#6177]
i have an issue with my main character after faction change , from alliance to horde and back to alliance , after the faction change i noticed certain achivements are gone , completely vanished and impossible to finish .

Like the loremaster of easter kingdoms
http://imgur.com/8EUXXIm (http://www.wowhead.com/achievement=1676/loremaster-of-eastern-kingdoms)

and the loremaster of kalimdor + achivement quest zone of silithus ( http://www.wowhead.com/achievement=1678/loremaster-of-kalimdor) (http://www.wowhead.com/achievement=4934/silithus-quests)
http://imgur.com/qyv0Cj8

and the accomplished angler
http://imgur.com/EWqoh3o (http://www.wowhead.com/achievement=1516/accomplished-angler)

as you can see in the screenshots , the achivements aren't there , as an achivement hunter....its a disaster for me , i really wish some help to restore the achviements , because i can't do them at all
as i said , the achievement are completely gone and impossible to do

**Comment by eryczek1615** [comment]
When you change faction (for example A -> H). You still have [Ambassador of the Alliance](http://www.wowhead.com/achievement=948), [Quests from Alliance zone](http://www.wowhead.com/achievement=4928) and [Drag a Maw](http://www.wowhead.com/achievement=5229) and ([Double Jeopardy](http://www.wowhead.com/achievement=5552)

**Comment by Muhiqt** [comment]
its more funny cuz my achievements aren't faction related , and as i said they are completely gone and impossible to do

**Comment by Aviannaqt** [comment]
@pelekon do zamkniecia
