### ISSUE TITLE
[EN][Quest][Westfall] A Vision of the Past

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6178]
This quest has been referenced and closed over 6 times and it is still broken. First reference was Jan 16, 2015 and it was marked High Priority. Since then all references have been closed. Over one year later and it is still broken. This quest is vital for Westfall progression. 

[PL][Quest][Westfall] A Vision of the Past #1622 
[EN][Quest][Westfall] A vision of the Past #2213
[EN][Quest][Westfall] A Vision of the Past #2444
[PL][Quest][Westfall] A Vision of the Past #2793
[EN][Quest][Script][Westfall] A Vision Of the Past #26320 #3538
[EN][QUEST][Westfall][A Vision of the Past] Quest id: 26320 #4553

**Comment by babbulu49** [comment]
doesnt even let me accept the quest, had to grind to 14 to even go to redridge mountains. Very inconvenient.

**Comment by Aival94** [comment]
The first one you posted(#1622) is open and that is probably the reason rest have been closed as there is already a report and you can make a comment there if you want to give some more info.

**Comment by lourrific** [comment]
#1622 was posted over a year ago. The quest is still broken so I made this new post.

**Comment by Aival94** [comment]
By making new post does not mean that will be taken in higher priority.All double posts of the same issue that devs know will be closed as already "Reported".
