### ISSUE TITLE
[EN][Quest]The shadow Grave - second quest from starting zone of undeads

### ISSUE THREAD

**Issue by ondrejkral** [Atlantiss/BugTracker#6186]
Bugged again, the second item ([Thick embalming fluid](http://www.wowhead.com/item=64582/thick-embalming-fluid)) cannot be looted from the table.

I think that functionality of quests in starting areas is representative for the server.

Edit: [http://www.wowhead.com/quest=28608](http://www.wowhead.com/quest=28608) (thx Samineh)

**Comment by Samineh** [comment]
:+1:

**Comment by xolon** [comment]
Wowhead links would always help

**Comment by Samineh** [comment]
http://www.wowhead.com/quest=28608

**Comment by Lanrutcon** [comment]
It's working fine: http://i.imgur.com/m38PsY1.jpg (a couple minutes ago) and https://www.youtube.com/watch?v=Qtuv0gdHo7k (~1week ago).

**Comment by ManiaqGH** [comment]
Still bugged as of today

**Comment by BAndysc** [comment]
Fixed in rev 5079
