### ISSUE TITLE
[EN][Wetlands] Quest] For Peat's Sake

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6187]
http://www.wowhead.com/quest=25939/for-peats-sake

How it should work: According to wowhead, this quest should become available after completing http://www.wowhead.com/quest=25926/mired-in-hatred .
How is the quest bugged: It is available regardless of completing that prerequisite or not.

**Comment by BehindTimesGame** [comment]
I am currently on this quest and there are no March Fire's being created. Therefore I am unable to complete the quest.

**Comment by Bildo** [comment]
fixed
