### ISSUE TITLE
[ENG][QUEST][HOWLING FJORD] The Slumbering King

### ISSUE THREAD

**Issue by rinovntr** [Atlantiss/BugTracker#6188]
NPC NECRO OVERLORD MEZHEN dont drop 'Mezhen Writing' that trigger 'The Slumbering King' quest.
i killed him 3 times but i cant loot him

**Comment by Aviannaqt** [comment]
read bt rules

**Comment by RangerTalion** [comment]
bump

**Comment by Piklo** [comment]
@RangerTalion open new issue

**Comment by Samineh** [comment]
#9200
