### ISSUE TITLE
[EN][Item][Trinket] Moonwell Chalice has too short range

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#6193]
The range of the link is way too low its 20 yards, here it how it should be.
https://www.youtube.com/watch?v=pALAqp9va4c (look at 2:45) Its 30-40 yards in that video

**Comment by RandomPickNewb** [comment]
According to wowhead comments it is indeed 30-40 yds (http://www.wowhead.com/item=70142/moonwell-chalice#comments) but the spell has 20 yds range (http://www.wowhead.com/spell=100403/blessing-of-the-moonwell).

**Comment by anxanas** [comment]
@RandomPickNewb please tell me how your comment told us anything i hadnt already written.

**Comment by RandomPickNewb** [comment]
I added more information to you report that was based on some visual cues.
Taken from the rules:Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com.

**Comment by Illusie** [comment]
Why you care about the range of Moonwell Chalice?
You this trinket  only for snapshotting.

#lowpriority ??

**Comment by anxanas** [comment]
You demon benefits from the mastery(you would know that if you had any idea about demo), and this trinket is used by other specs/classes than demo, like arcane mages who can hardly move if they pop this.

**Comment by blinkmaster** [comment]
@lamaATS plz halp ;<

**Comment by lamaATS** [comment]
DBC data:
```
SpellRange: (Id 3) "Twenty yards":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 20, MaxRangePositive = 20
```
The question is why in real this spell should have 30yd/40yd comments on wowhead are different.

**Comment by blinkmaster** [comment]
yes it should have 30 yds, here on ATS it seems 20 yd. Can be seen as minor bug but on some movable encounters it hurts ;)

**Comment by lamaATS** [comment]
Fixed on my test server.

**Comment by lamaATS** [comment]
Fixed in rev. 5218

**Comment by blinkmaster** [comment]
@lamaATS  love
