### ISSUE TITLE
[EN][Event] Lunar Festival

### ISSUE THREAD

**Issue by Invaerne** [Atlantiss/BugTracker#6194]
http://www.wowhead.com/event=327/lunar-festival
Festival should start today at 10 AM, but there's no event NPCs in Moonglade.

**Comment by NatsumeLily** [comment]
I don't know the dates for 4.3.4 but the events change every year. Look at the dates for our past event and compare them to Wowhead, they are different.

**Comment by Aldergar** [comment]
Also the in game events are manually started by a Game Master,so if you can't see the npcs,probably they haven't still activated it.

**Comment by Luna-maria** [comment]
http://wowwiki.wikia.com/wiki/Lunar_Festival

cataclysm was released in december 2010, so first lunar festival was in 2011
meaning it was supposed to start last week if we're going by original dates

**Comment by Aival94** [comment]
Lunar Festival is normally a moving event depend of year an is supposed to be at around the same days the Chinese New Year event which for 2016 is on February 8

Sources: "It appears that Blizzard moves the dates of this event to conform to the real-life Chinese Lunar New Year on which this festival is based." [Lunar Festival](http://wowwiki.wikia.com/wiki/Lunar_Festival)
[Chinese New Year](https://en.wikipedia.org/wiki/Chinese_New_Year#Dates_in_Chinese_Lunar_Calendar)
