### ISSUE TITLE
[EN][Spel][Plate Classes]Forceful Deflection(ID 49410)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6195]
After 4.2 [Forceful Deflection](http://www.wowhead.com/spell=49410/forceful-deflection) changed from 25% of Strength to 27%.Seems now is 25%(i believe is 25.1%-25.2%).

I have 370 parry on items and 2776 Strenght.

Normally i should have 370+(2776x27/100)= 370+749.52 =1119.52 but i have 1069(370+699=370+(2776x25.2/100))

Wowhead Link: [Forceful Deflection](http://www.wowhead.com/spell=49410/forceful-deflection)
Wowhead Link(Changelog): [Forceful Deflection(Changelog)](http://www.wowhead.com/spell=49410/forceful-deflection#changelog)

**Comment by metaldoctor** [comment]
This passive working only on strength from items. Then if you have 4697strength (i have this value in dps gear and tanking talents) you need recalcute strength from items, i have only 4500 (orc DK have 197 base str). 4500 * 0.27 = 1215 raiting. In Stats i have 1215 raiting.
http://imgur.com/or7QLZV,fMIJ89s

**Comment by Aival94** [comment]
The tooltip say of your Total Strenght so i think it was of your total Stenght and not only gear Stenght and i cannot find any proof about what you say.Furthermore did the calculations on my dk and still was not proper numbers.

**Comment by metaldoctor** [comment]
Death knights, paladins, and warriors now receive 27% of their Strength bonuses as parry rating, up from 25%. This conversion still only applies to Strength above and beyond their base Strength.
http://wowwiki.wikia.com/wiki/Patch_4.2.0

**Comment by Aival94** [comment]
Ok i close this issue as is not correct.Sorry for trouble.
