### ISSUE TITLE
[EN][Item]Sealed Crate

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6196]
http://www.wowhead.com/item=67597/sealed-crate

it doesn't always contain loot
it sometimes says 'that slot is empty' but doesn't give any errors or something and still doesn't drop anything sometimes either

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11915-6196-sealed-crate-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
