### ISSUE TITLE
[PL][RAID][MOLTEN CORE]

### ISSUE THREAD

**Issue by NikolasAntoni** [Atlantiss/BugTracker#6197]
Podczas solowania Molten Core doszedłem do miejsca gdzie powinien stać boss  Majordomus, lecz tam go nie było. Wszystkie wcześniejsze bossy zostały pokonane. Przez to nie mogę dokończyć raidu.

**Comment by Achiver** [comment]
Kiedy podczas robienia MC serwer dostanie dc (jeśli nie ubiłeś wszystkich bossów przed Majordomo) to boss się nie pojawia.
