### ISSUE TITLE
[ENG][QUEST][BOREAN TUNDRA] Abduction

### ISSUE THREAD

**Issue by rinovntr** [Atlantiss/BugTracker#6198]
All 'Beryl Sorcerer' have become 'captured Beryl Sorcerer' when i use 'arcane binder' on 'captured Beryl Sorcerer' the quest didnt complete.

**Comment by Matti297** [comment]
Now it's seems that they are normal but capture is unsukcesful every time i try to use item on them

**Comment by rinovntr** [comment]
ops its can captured Beryl Sorcerer just fine now. so i closing this
