### ISSUE TITLE
[EN][Druid] Base mana and spell cost.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6199]
Hello.
We have wrong value of base mana for druid. Its must be 18635 and we have 21751.
How i check it? - I have 2T12 resto and its regen 1% of base mana (only 186 mana, 186*100 ~ 18600). Wowhead sayed its correct value for regen. And wowwiki sayed too, 18635 must be.
http://www.wowhead.com/spell=99013/item-druid-t12-restoration-2p-bonus#comments:id=1410092 - wowhead comment.
http://wowwiki.wikia.com/wiki/Base_mana - table with base mana.
With this problem of base mana all spells cost more then must be.
For examples, all spess cost this value in game with out talents:
Lifebloom cost 7% of base mana. 21751 * 0.07 ~ 1523. It must be 18635 * 0.07 = 1304.45
Wild Growth cost 27% of base mana. 21751 * 0.27 ~ 5873. It must be 18635 * 0.27 = 5031.
Swiftness cost 10% of base mana. 21751 * 0.1 ~ 2175. It must be 18635 * 0.1 = 1863.5
I find some video guides from retail, at this guide you can see how much swiftness cost with full talents. Its 1695, at out server 2044.
Links:
http://www.youtube.com/watch?v=0isu7ev3BBw - video guide, at 11:47
http://imgur.com/a/0Vt8B - screen shot with mana with out gear and talents, and mana cost for swiftness in full restor build.
http://www.wowhead.com/spell=48438/wild-growth#changelog - WG change log, u can see how it cost in percent in 4.x.x
http://www.wowhead.com/spell=33763/lifebloom#changelog - same for LB.

**Comment by anxanas** [comment]
Base mana is the mana without any gear on or buffs, not the maximum mana.

**Comment by Jenovas** [comment]
Fixed in rev 4870
