### ISSUE TITLE
[EN][Other] Player health regeneration

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#6204]
http://bug.omfg.gg/issues/3680
"on Cataclysm, Health Regen was standarized to 1% HP regen out of combat.every 2 seconds"
http://wow.gamepedia.com/Health_regeneration
"Health Regeneration is increased by 33% while sitting."
http://wowwiki.wikia.com/wiki/Patch_4.0.1_%28undocumented_changes%29
"Outside of combat, all classes seem to regenerate 0.75% of their maximum health per second" (Emphasis on "seem")
Something is off with these values on atlantiss. While standing up I regenerated from 3200 to 5120 with one tick, which compared to my 128056 health is 1.49934%. However when I sat down my health went from 4131 to 7012, which is 2.24979% of my total health and 50.052% more than when I was standing up.
1.5% every 2 sec is such a high value that you hardly ever need to eat or bandage while out of combat unless you took serious damage.
Here is some evidence for 1% regeneration being correct value:
http://us.battle.net/wow/en/forum/topic/3182448914
The percentage regeneration is supposed to go down with level, so the fact that he had low level doesn't matter here. Also note that OP of that topic was a troll, so if value were to be 1.5% he would regenerate much more than ~1.1%.
https://www.youtube.com/watch?v=rVFbwC1ro_Y
0:53 (immediately after he won the duel) he regenerated from 56006 to 57205 health. This is 1199 regeneration tick and as you can clearly see he has 119k max health (probably close to 120k). Same scenario repeats in 2:39 (from 35894 to 37089).

**Comment by BialyADI** [comment]
http://wowwiki.wikia.com/wiki/Health_regeneration
This information is form 2.4.0 about regen while siting.

And this is from patch 4.0.1
"Health regeneration uses a new formula. Outside of combat, all classes seem to regenerate 0.75% of their maximum health per second before the effects of abilities."
So it will be 1,5% every 2 sec.
Mayby on our server problem is about rate of regeneration.
Regeneration should tick every 1sec or 2sec? And what tick rate is on Atlantiss?
And if we increase regeneration tick rate it will increase Lags ;D?

**Comment by Bjarzyna** [comment]
These are not official patch notes. There's no information about changes in regeneration in blizzard patch notes.
Tick rate seems fine. My character uses no talents or abilities that would increase health regeneration.

**Comment by Jenovas** [comment]
Fixed in rev 4859
