### ISSUE TITLE
[PL][RAID][Temple of Ahn'Qiraj]

### ISSUE THREAD

**Issue by NikolasAntoni** [Atlantiss/BugTracker#6205]
Podczas bicia pierwszego bossa czyli The Prophet Skeram po 10 sekundach boss zniknął. Po pewnym czasie (15 sekund) znów się pojawił. I tak non stop. Za każdym razem znika i się pojawia.

**Comment by Bastion** [comment]
ja bym to dał do archiwum x

**Comment by Achiver** [comment]
On po prostu używa mind control, a skoro oprócz ciebie nie ma nikogo innego to się resetuje, bo nie ma kogo atakować.
