### ISSUE TITLE
[EN] [Hunter] [Marksmanship] "Fire!" aimed shot proc overlap glitch

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#6206]
When casting Steady Shot, and once you get 5x "**Ready, Set, Aim...**" procs, if you are already casting **Aimed Shot** before the last Steady Shot hits for the 5th RSA buff, your non-instant Aimed Shot will make the the "**Fire!**" buff disappear, but the Aimed Shot will still cost **Focus**. 
Half of a MM hunters Aimed Shots are wasted because of this glitch.

How it should work:

Spam Steady Shot until you get 4x stacks, shoot 1 more steady shot and instantly cast Aimed Shot.
While casting, you get the "Fire!" buff, and your aimed shot cast will finish, using 50 focus, and afterwards you can instantly use Aimed Shot, because the "Fire!" buff should still be there.

**Comment by Fapguy** [comment]
https://vid.me/1JtB

A video to demonstrate if my explanation is horrible...

**Comment by lqlq32** [comment]
Nice catch, buff should be consumed on cast and it count it as cast because u fire it when it proc.

**Comment by Fapguy** [comment]
This hasn't been confirmed, labeled or even looked at yet? Do I need to bump it?

Just wondering, dunno!

**Comment by Wantuno** [comment]
I'd like this to be fixed too, such dps loss for this bug

**Comment by Fapguy** [comment]
I would like this to be pretty high priority, as you lose almost a whole minute of activity on long fights.

It's like any other class going afk for 30+ seconds.

**Comment by Fapguy** [comment]
10 days :e

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/825 15 months
https://github.com/Atlantiss/BugTracker/issues/3791 8 months
enjoy waiting :*

**Comment by Fapguy** [comment]
vamos

**Comment by Fapguy** [comment]
This seems to have been silently fixed... Am now able to cast Aimed Shot and spam the button to fire an extra aimed shot for free.
