### ISSUE TITLE
[EN][Spell][Druid]

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6209]
So I had this Bone shield buff on my druid the other day. I meant to report it back then but I've completely forgot everything about it. I don't remember how I got it, but if I recall correctly I think I was doing 2v2 or in a battleground.

I just thought I'd put it out there.. I remember there was a Death Knight involved and a wild guess would be that the DK would use dark simulacrum or whatever and I used one certain spell to copy some of his spells... I don't know.. Here you go.

Edit: Lol forgot the screenshot...
http://imgur.com/QqFTjpC

**Comment by Kejmil** [comment]
when blood dk use dancing rune weapon some of his spells are inproperly copied on target like that, you can also give your target horn of winter, or dmg them with rune tap (?!)

**Comment by Fearyourself** [comment]
Nice
