### ISSUE TITLE
[en][mage][talent] Shattered Barrier DR

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6210]
Hello, shattered barrier doesn't DR with improved cone of cold and it should.
this is actually a very HUGE bug for melee classes opponents becouse you can see more and more mages abusing this.
/dieforcancer

http://www.mmo-champion.com/threads/862509-Shattered-barrier-useless-talent-now
http://wow.gamepedia.com/Shattered_Barrier
Cataclysm Patch 4.1.0 (2011-04-26): The root effect from Shattered Barrier now shares diminishing returns with the root from  [Improved Cone of Cold].

**Comment by kadi2** [comment]
Wow. Nobody abused it for over 1 year.

**Comment by blinkmaster** [comment]
dunno i dint even know it was bugged ( coz its worthless talent ) but seeing more and more mages with it made me curious and here it is.

**Comment by Wolffenstein** [comment]
Fixed in rev 4863.

**Comment by BialyADI** [comment]
https://github.com/Atlantiss/BugTracker/issues/6286
Plz some one, it is more annoying than DC ;x.
