### ISSUE TITLE
[NPC]/[QUEST]Thoralius the Wise, A vision of the past

### ISSUE THREAD

**Issue by Grotharr** [Atlantiss/BugTracker#6212]
[EN]
This NPC ends quest http://www.wowhead.com/quest=26319/secrets-revealed.
Then he should give me next mission http://www.wowhead.com/quest=26320/a-vision-of-the-past.
Unfortunately he didn't gave me any mission, but he has BLUE question mark upon his head. When i click on him, dialogue window to complete quest open. When I click on "Complete Quest" nothing happens. Marshall Gryan Stoutmantle, who should end this quest has also, this time yellow, question mark upon head. When i talk to him he only says "Greetings ..."

[PL]
Ten NPC kończy questa http://www.wowhead.com/quest=26319/secrets-revealed.
Po nim daje nam kolejnego questa http://www.wowhead.com/quest=26320/a-vision-of-the-past.
Niestety, w moim przypadku, nie otrzymałem żadnej nowej misji od niego. Po zakończeniu questa ma on niebieski pytajnik nad głową. Gdy rozmawiam z nim pojawia się okno do zakończenia questa. Gdy klikam "Complete quest" nic się nie dzieje. Wiem że tego questa tak naprawdę kończy Gryan Stoutmantle w Sentinel Hill. Owszem, ma on żółty pytajnik nad głową, lecz to wszystko, gdy z nim rozmawiam mówi tylko "Greetings ...". Najwidoczniej gra traktuje mnie jakbym otrzymał questa, jednak nie mam go w quest logu i nie moge nic zrobić. Próbowałem reloga i nie pomógł

**Comment by madethatway** [comment]
It's now well over a month later and this quest is still bugged. As per the original ticket by Grotthar, the exact same thing happens with me. Can't hand it in, despite the blue question mark and can't obtain the next quest to report back to Sentinel Hill.

**Comment by Xenerus** [comment]
Bump. Problem still persists.

**Comment by Leg312** [comment]
Bump

**Comment by Leg312** [comment]
Bump

**Comment by user1011** [comment]
Bump.

**Comment by Valoiz** [comment]
Quest still bugged

**Comment by arndry** [comment]
I don't wanna open another issue post. when do the developers going to fix this bug? It looks like the bug have a long tail since 2014... we passed the middle of the going year. Can someone from the backoffice bring us some light?

**Comment by deathmace** [comment]
Fix this...

**Comment by Bildo** [comment]
you can take this quest but quest itself is not working
