### ISSUE TITLE
[EN][Char] Character model

### ISSUE THREAD

**Issue by Bartekhihi** [Atlantiss/BugTracker#6213]
![wowscrnshot_020216_202116](https://cloud.githubusercontent.com/assets/17032451/12761471/6de8e0d6-c9eb-11e5-94bc-598e81ca6d81.jpg)
I don't even know how to name this. How can I fix it? xD

**Comment by Bartekhihi** [comment]
I tried to restart game and computer also. I don't wanna to reinstall game :<

**Comment by Bildo** [comment]
write a ticket and ask for unaura
