### ISSUE TITLE
[EN][QUEST][BLASTED LANDS] The Altar of Storms

### ISSUE THREAD

**Issue by reapertg** [Atlantiss/BugTracker#6215]
When you use the altar, Lomasus' body does appear, but after that, nothing happens.
Quest is not completable.

http://www.wowhead.com/quest=26162/the-altar-of-storms

This has been reported a number of times but all those issues are closed, with this still being a problem i thought it best if i opened a new issue for it.

Thanks

**Comment by Thefakemccoy** [comment]
Still bugged nothing happens after clicking altar.

**Comment by artamedan** [comment]
You can get the Blasted Lands achievement without this quest. Many quests there are over the achievement limit. So no need to do this one.

**Comment by Thefakemccoy** [comment]
Yes it can be done but it still needed reported.

**Comment by Spatsa** [comment]
Same issue. I tried this quest and after clicking on the altar, Loramus' body appeared, standing inside of the altar, and nothing happened. None of the enemies that are supposed to appear to "stop the ritual" spawn, so nothing really happens.

**Comment by Hacker--x** [comment]
Still bugged. Same issue, cannot start ritual

**Comment by siwy92** [comment]
still not work

**Comment by karhima** [comment]
Quest still broken.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/409

**Comment by terranu1** [comment]
works now
