### ISSUE TITLE
[PL][ITEM] Blood of the mountain

### ISSUE THREAD

**Issue by kepucz** [Atlantiss/BugTracker#6217]
drop Blood of the Mountain z Dark Iron Deposit wynosi 100%, informacje z wowhead'a i openwow mówią że powinno być 0.5%-1% na drop tego itemu

dowód: http://imgur.com/CLhSHA4

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/8205-6217item-blood-of-the-mountain/
