### ISSUE TITLE
[EN][Quest][The Hinterlands] Quel'Danil Lodge

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6218]
http://www.wowhead.com/quest=27725/queldanil-lodge

How it should work: This quest should become available only after completing http://www.wowhead.com/quest=26526/hunt-the-keeper and all other quests given by http://www.wowhead.com/npc=43156/fraggar-thundermantle and http://www.wowhead.com/npc=43157/doran-steelwing#starts. (also see wowhead comments)
How it is bugged: The quest http://www.wowhead.com/quest=27725/queldanil-lodge is available without completing the prerequisites.

**Comment by TranceAccount** [comment]
Confirmed... Egh..

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:
https://community.atlantiss.eu/index.php?/topic/14736-quests-the-hinterlands/

[//]: # ([EN][Web] Armory doesnt work)

**Comment by Jenovas** [comment]
Fix in rev 5538
