### ISSUE TITLE
[EN][Warlock][Spell] Fel armor

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#6226]
Fel armor should not grant healing to the caster based on damage dealt by area of effect spell. Currently any form of spell damage causes it to heal the caster.

**Comment by anxanas** [comment]
No it doesnt, it does heal you from the damage from hellfire but only the damage you do to urself(Which is apparently counted as single target) all other aoe does not heal you.

**Comment by Bjarzyna** [comment]
http://imgur.com/JP2LhJ0
Yeah you're right, perfectly fine.

**Comment by anxanas** [comment]
Actually you are somewhat right, but it seems to only work with rain of fire, therefore the bug is probably not with fel armor, but with rain of fire counting as a single target spell(since neither hellfire immolation aura or seed of corruption heals you)

**Comment by Bjarzyna** [comment]
I can screenshot my spells all day, but the truth is I get healed from all of the following:
seed of corruption
rain of file
shadowflame
hellfire
I did not test shadowfury.

**Comment by anxanas** [comment]
Shadowflame is a cone flame not aoe you are supposed to be healed by that. You probably get healed by the single target corpenent of seed of corruption, hellfire heals you for the damage you do to urself(no idea if this is a bug or not). The bug is with rain of fire and probably hellfire self damage.

**Comment by Bjarzyna** [comment]
In fact:
Seed of corruption heal seem to come from tick damage not explosion damage.
Hellfire heals from self-damage.
Summon infernal initial damage does not heal at all.
However:
Rain of fire, shadowfury and shadowflame heals as if they were single-target. Also can you provide evidence for shadowflame (or cone spells in general) being considered single-target?

**Comment by anxanas** [comment]
Bjarzyna nice of you to repeat what i just said and add a little bit. Shadowflame anything with an aoe reduction and the damage wont be reduced(Rogue using feint or DBS adds)

**Comment by Bjarzyna** [comment]
All that does is proving shadowflame to be considered single target _by this server_. I requested retail evidence.

**Comment by anxanas** [comment]
You are the one who reported it prove that it shouldnt heal you through fel armor. Fel armor works perfectly, its the individual spells thats probably somehow listed as single target, even a retarded 5 year old can figure that out considered some aoe spells do heal and others dont.

**Comment by anxanas** [comment]
Just found a proof that hellfire is actually supposed to heal you through fel armor https://www.youtube.com/watch?v=ix3jErY9AoU (4:19) He is only using hellfire but he gets healed through his fel armor(look at left side milkscrollingtext and he has no dots on targets)

**Comment by Aviannaqt** [comment]
link

**Comment by Bjarzyna** [comment]
Fel armor: http://cata.openwow.com/spell=28176

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
