### ISSUE TITLE
[EN][Warlock][Spell] Demon soul

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#6227]
Using demon soul with voidwalker active causes threat generated by the caster's actions to be transfered to the demon permanently. Dismissing demon and mounting seem to fix this issue until demon soul is cast again.

**Comment by Aviannaqt** [comment]
link

**Comment by Bjarzyna** [comment]
Demon soul: http://cata.openwow.com/spell=77801

**Comment by Wolffenstein** [comment]
Fixed in rev 4901.
