### ISSUE TITLE
[EN][Spell][Paladin] Beacon of Light

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#6229]
The healing spells used on pets are not healing the Beacon of light target.

http://cata-shoot.tauri.hu/?spell=53563
Pets are part of the party so should be transferring the heals to Beacon. They are not.

**Comment by TheCatcherInTheRye** [comment]
Worked for me today with Felguard.

**Comment by Aviannaqt** [comment]
link

**Comment by calladin** [comment]
Up up up, beacon is not healing h paladin when he is casting it on himself

**Comment by lamaATS** [comment]
`beacon is not healing h paladin when he is casting it on himself` any proof?

**Comment by Piklo** [comment]
![beacon](https://cloud.githubusercontent.com/assets/16057987/20432683/9d59d2fa-ada0-11e6-932a-72b1c4ea6a4d.PNG)
:P

**Comment by lamaATS** [comment]
SS without explain is like nothing for me in this case. It's from ATS which say `is not healing on main server` or from Retail which say `is should be on self`.

**Comment by Piklo** [comment]
oh sorry, i forgot.
https://youtu.be/eFdem0pif7I?t=6m25s (i know weak quality, but enought to see scrolling combat texts)
in this video you can see this. pal casted beacon on himself and after healing arena partner he got heal from beacon

**Comment by lamaATS** [comment]
Fixed in rev. 5251 (in this revision applying buffs on Pet has been reworked)
