### ISSUE TITLE
[PL][Talent][Druid][Revitalize-Replenishment]

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#6230]
Replenishment z talentu http://cata.openwow.com/spell=48544 powinien dawać 1% max many casterowi oraz 10 osobom z rajdu. Jak widać na załączonym poniżej ss z combat logu daje  131 many przy 122k. Sam revitalize działa ok, moim zdaniem problem jest w częsci dotyczącej Replenishmenta. W combat logu widać mane otrzymaną z bonusu 2xT12 (heartfire). Ja się zapytuje jak to jest że z bonsu hearfire który działa poprawnie, oraz który bazuje na _PODSTAWOWEJ_ manie http://wowwiki.wikia.com/wiki/Base_mana dostaje prawidłowe 182 many (widać na ss), a z replenishmenta który opiera się na _MAKSYMALNEJ_ manie dostaje 131. 

http://jpghost.pl/mana_1454512997/

**Comment by Reversion** [comment]
Sprawdzałem to jeszcze z koleżka i wychodzi na to że rega 0.1% zamiast 1%, dawalo mu 118 many przy 118k mana. u mnie na ss pokazuje ze daje mi 131 many przy 122kmana prawdopodonie dlatego ze się odpalil jakis power torrent akurat jak robilem ss. Tak czy inaczej problem jest i to na spory minus. Czekam na opinie.

**Comment by Lenox07** [comment]
Masz napisane 1% na 10 sec czyli 0.1% co sekundę więc dobrze działa.

**Comment by Reversion** [comment]
;O Solved
