### ISSUE TITLE
[EN][Warlock][Spell] Fel armor with hellfire

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#6231]
Hellfire is supposed to heal you through fel armor for all the damage it does.
http://www.wowhead.com/spell=1949/hellfire
http://wowwiki.wikia.com/wiki/Fel_Armor
Proof:
https://www.youtube.com/watch?v=ix3jErY9AoU (4:19) He is only using hellfire but still getting lots of minor heals through fel armor(look at his milkscrollingtext).

**Comment by illidan810** [comment]
This quest doesn't work. Tried everything with the abomination but no effect.

**Comment by kadi2** [comment]
Currently fel armor is healing the warlock from all sources of damage instead just from physical.
