### ISSUE TITLE
[EN][Spell][DK]Pillar of Frost

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#6233]
Pillar of Frost is only being multiplied by the value of your item strength (flat str, enchants, gems, socket bonuses). 

It should calculate the total strength value instead, this is a big loss because it means it's not multiplying with the plate specialization + brittle bones strength increases. 

Proof: 
![wowscrnshot_020316_192514](https://cloud.githubusercontent.com/assets/16211262/12794348/80b43ca8-caac-11e5-8703-7ca3caa7183d.jpg)
![wowscrnshot_020316_192518](https://cloud.githubusercontent.com/assets/16211262/12794352/824582d4-caac-11e5-944b-3e482212bce4.jpg)

5509*1.2=~6611. Effectively losing 91 strength. The more strength bonuses are added the bigger is the loss (synapse springs, flask, pot, horn of winter, etc.).

**Comment by metaldoctor** [comment]
All classes have base str (depend of race). I think pilar of frost working like: (Total_str - base_str) * 1.2 + base_str. But im not sure how it must works.

**Comment by ponpontos** [comment]
My female night elf has 187 base strength, so that would mean (5509-187)*1.2+187, which would result in 6573, still not the value in the picture. Besides, I see no reason why it would work like that. 

I think the problem is related to the plate specialization bonus, because I tried respeccing without brittle bones and the numbers still didn't match, I'm just not sure about what is the exact problem with it though.

**Comment by ponpontos** [comment]
Actually, a lot of things don't seem to add up, if I have 187 base strength + 4868 from items that means  5055 total strength when I'm without a spec. So, with a plate dps specialization + brittle bones I should be getting 5055*1.04*1.05=5520.06 while I'm currently getting 5509. So what happened to the remaining 11 strength? Too big of a value to be a loss on roundings.

Either the values are bugged or strength multiplication doesn't work how I'm assuming it should.

**Comment by ponpontos** [comment]
Oh ok, I see how it goes now. Basically the bonus strength values you get from each bonus don't multiply with each other.

So my strength value is 5055+(5055*0.05)+(5055*0.04). And the total value I'm getting from Pillar of Frost is 5055+(5055*0.05)+(5055*0.04)+(5055*1.2). That does check up. 

Is this how stat multiplication stacking is supposed to behave though? I can't find anything on the subject, and it kinda sounds counterintuitive.

**Comment by metaldoctor** [comment]
Death knights, paladins, and warriors now receive 27% of their Strength bonuses as parry rating, up from 25%. This conversion still only applies to Strength above and beyond their base Strength.
http://wowwiki.wikia.com/wiki/Patch_4.2.0

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/4643

**Comment by ponpontos** [comment]
I don't really understand Polish so I have no idea of what's going on that report.

Is he basically saying that this is how strength multipliers are supposed to work? Because it seems really dumb.

**Comment by Jenovas** [comment]
On our server all stat bonuses are additive. If you have any proof that it shouldnt plz make a report with  the proof.

Closing.

**Comment by kadi2** [comment]
The amount of strengh you would get from passives would be hilarous. There's alot similar spells stacking like this.

**Comment by ponpontos** [comment]
I can't seem to find any info on the subject and there are no videos showing str value before and during pillar of frost, so yeah...

Also, it wouldn't exactly be "hilarious", as you can see it would increase my unbuffed strength by 9. It only makes a difference when you have a lot more strength.
