### ISSUE TITLE
[PL][SetSPELL][HolyPriest]Cauterizing Flame

### ISSUE THREAD

**Issue by Jeyei** [Atlantiss/BugTracker#6234]
Witam, jest problem z 4 setówką T12, a mianowicie nie działa jej pasywka czyli przyzwanie "Cauterizing Flame" który powinien uleczyć jedną osobę

**Comment by Aviannaqt** [comment]
Cauterizing Flame działa tak jak powinno, jedynym bugiem jest to, że owy heal nie zapisuje sie w logu jako twój heal. Tutaj działa to tak, że spell jest castowany przez osobnego "npc", który używa cauterizing flame jako swój heal.

http://worldoflogs.com/reports/rt-qf01j2abskalto00/sum/healingDone/?s=5857&e=6408 
Tutaj w logach cauter jest doliczany jako mój heal, jest również pokazany jako osobna creature (show creatures po prawej stronie)

**Comment by Aviannaqt** [comment]
bump

**Comment by Aviannaqt** [comment]
.

**Comment by Jenovas** [comment]
Duplicate
