### ISSUE TITLE
[En][Spell][Hunter] Flare

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#6235]
When you cast Flare you can't move out of line of sight from the flare until it lands. It only happens when you drop flare then LoS it before it lands.

http://cata.openwow.com/spell=1543/flare

It's known bug from retail in cata so I'm not sure it should be fixed, reporting though.

**Comment by Jenovas** [comment]
If this is how it worked on retail we will not change it.
Closing.
