### ISSUE TITLE
[EN][NPC][Ghostlands] Halduron Brightwing

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6236]
http://www.wowhead.com/npc=53068/halduron-brightwing

He should be friendly to Horde players and hostile to Allliance players.
How he is bugged: He is hostile to Horde players.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10957-npc-halduron-brightwing-vereesa-windrunner/

**Comment by aje** [comment]
fixed in revision 5115
