### ISSUE TITLE
[EN][NPC][Ghostlands] Vereesa Windrunner

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6238]
http://www.wowhead.com/npc=53067/vereesa-windrunner#sounds

This NPC should be friendly to Alliance players and hostile to Horde players.
How she is bugged: She is friendly to Horde players.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10957-npc-halduron-brightwing-vereesa-windrunner/

**Comment by aje** [comment]
fixed in revision 5115
