### ISSUE TITLE
[EN][NPC][Profession-Related][Darnassus]Rolf Karner(52640)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6240]
NPC has the blacksmith icon on him but he is not learning any blacksmithing at all.Only greet you.

![wowscrnshot_020416_173406](https://cloud.githubusercontent.com/assets/10282971/12820434/c458b4dc-cb67-11e5-8fd1-2ba8baab01fb.jpg)

Wowhead Link: [Rolf Karner](http://www.wowhead.com/npc=52640/rolf-karner)

**Comment by TranceAccount** [comment]
Please provide a WoWhead link to the NPC.

**Comment by Aival94** [comment]
Updated with link.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11603-6240npcdarnassusrolf-karner/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
