### ISSUE TITLE
[EN][Druid] Obsidian Arborweave Vestments 2p set bonus.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6241]
Hello.
Set bonus says:
2 pieces: Your periodic healing from Lifebloom has a 40% chance to restore 1% of your base mana each time it heals a target.
But its regen only 0.85%.
How calculate it?
1. Remove all items and reset talents.
2. Put mouse at your intelect in stats
3. Base mana = Mana - Mana from intellect. (23811 - 2060 = 21751).
4. Equip 2T12 and put lifebloom.
5. Wait for proc and see its restore 186 mana.
6. Calculate how much percantage is 186 of 21751. (186/21751 * 100% = 0.8551%)

![wowscrnshot_020416_205353](https://cloud.githubusercontent.com/assets/2743430/12824411/1dc6ccb0-cb82-11e5-8d96-6aff258b8df1.jpg)
![wowscrnshot_020416_205002](https://cloud.githubusercontent.com/assets/2743430/12824412/1dcf2ae0-cb82-11e5-873d-94e247130eee.jpg)

**Comment by anxanas** [comment]
https://github.com/Atlantiss/BugTracker/issues/6199
It seems to not be a problem with the set bonus, but druid base mana.

**Comment by Reversion** [comment]
no this bonus work propertly http://wowwiki.wikia.com/wiki/Base_mana
