### ISSUE TITLE
[EN][Event][Lunar Festival][NPC]Elder Windsong

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6242]
http://www.wowhead.com/npc=55224/elder-windsong#comments

supposed to be at the Sanctuary of Malorne, but I can't see her (I've done the whole Molten Front questchain, possibly a phasing issue?)

**Comment by Sayris9876** [comment]
I assume its phasing issue too shouldnt be hard to get fixed

**Comment by Sayris9876** [comment]
There was server restart and i just completed this one soo its all good now i guess
