### ISSUE TITLE
[EN][Event][Lunar Festival][Quest/NPC] Elune's Blessing / Omen summoning

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6243]
http://www.wowhead.com/quest=8868/elunes-blessing

can't complete this quest currently because it seems impossible to summon Omen. Shot of over 30 cluster rockets and nothing happened. Tried at both launchers, it didn't make any difference

**Comment by Sayris9876** [comment]
Tried with over 60 different firecrackers or w/e are they doesnt seem to work

**Comment by mean931** [comment]
same bug as the one from last year, the launchers are not working in moonglade

**Comment by HUMBOL** [comment]
Confirmed

**Comment by Luna-maria** [comment]
Ok so I saw a guildy getting the achievement earlier today (febr 5) and while flying to the place in moonglade I saw 2 dead bodies of Omen lying around 

it's been an hour since and it hasn't spawned again, and summoning it through using rockets, still, does not work 

sup?

**Comment by Aviannaqt** [comment]
fixed
