### ISSUE TITLE
PRIEST

### ISSUE THREAD

**Issue by malinakno** [Atlantiss/BugTracker#6245]
Witam czy jest cos wiadomo na temat niedziałającego 4 setu z Cleansing Flame na Priescie Holy ?? Dzisiejszego dnia nabylem 4 przedmiot do owego setu i nie zauważyłem by zadzialal prosil bym o przyjrzenie się temu. Dziekuje

**Comment by Bastion** [comment]
zgłoszenie zostało przyjęte do rozpatrzenia przez prokurature!
