### ISSUE TITLE
[PL][Raid - Blackwing Lair] Brood Affliction

### ISSUE THREAD

**Issue by kepucz** [Atlantiss/BugTracker#6246]
debuff nie dziala na gracza, z tego co zauwazylem to stunuje bossa
 Brood Affliction: Bronze: 4 second stun at random intervals for 10 minutes. Can only be removed with  Hourglass Sand.

**Comment by Achiver** [comment]
Przez ciebie nie będzie się dało go zsolować

**Comment by Aviannaqt** [comment]
linki
