### ISSUE TITLE
Molten Front PET BUGS

### ISSUE THREAD

**Issue by Swisher13** [Atlantiss/BugTracker#6249]
So first of all, Skarr is still bugged. When tamed he will go into your call pet option, but he cannot be summoned. Upon checking the stable master, he appears to be this. (Yes I have tamed Skarr 3 times in the last few days since the IMMUNE fix.)
![wowscrnshot_020516_023925](https://cloud.githubusercontent.com/assets/17079580/12840572/7e95aa7c-cbb2-11e5-88aa-0aa547558213.jpg)

Second of all Deth'tilac is bugged as well. Deth is confirmed to spawn. He is tameable and the encounter is as it should be. Once at 20% or below he is tameable. Once tamed though, cannot be called in. Upon checking the stable master, he is there as majestic as he should be; a fate unlike Skarr's.
![wowscrnshot_020516_023931](https://cloud.githubusercontent.com/assets/17079580/12840599/b9895ea8-cbb2-11e5-812d-28f2352656e3.jpg)

Thanks Devs for all your hard work. You're almost done wrapping this chapter up for all the hunters out there. Would like to see these fixed, hopefully I wont have to tame them again either ;)

**Comment by meowmewo** [comment]
Next time just relog after taming. :)

**Comment by krecik88** [comment]
i will get to fix pets once done with acutal testing branch.

please fix bug name according to bugtracker rules

**Comment by Aviannaqt** [comment]
change title

**Comment by krecik88** [comment]
fixed in 4979
