### ISSUE TITLE
[PL][Spell][Mage] Flame Orb

### ISSUE THREAD

**Issue by Shainear** [Atlantiss/BugTracker#625]
http://cata.openwow.com/spell=82731
http://cata.openwow.com/spell=83619
http://cata.openwow.com/spell=54734

Flame Orb z talentem Fire Power powinien wybuchać pod koniec swojego trwania, jednak wygląda na to, że żadnego wybuchu nie ma. Na 4.0.6 FO wybucha i jest to jedyny poprawny dmg tego spella, a w combat logu widnieje jako hit "Fire Power". Tymczasem na 4.3.4 nie ma żadnego wybuchu i spell po prostu znika gdy skończy tickować.

**Comment by Asavel** [comment]
Wyjmuje ze stealtha wybuchem,szukalem i nie bylo nic o tym zeby bil stealthow

**Comment by blinkmaster** [comment]
https://www.youtube.com/watch?v=cY4pgtfU4WM
5:26 clearly visible. and its not a glitch/bug, just a spell mechanic ;) in articles i provided above u can read about it. peace ;)

**Comment by Wolffenstein** [comment]
Fixed in 4242.
