### ISSUE TITLE
[EN][Event][Lunar Festival][Quest/NPC] Elders of Eastern Kingdoms - Rumblerock the Elder

### ISSUE THREAD

**Issue by Larousene** [Atlantiss/BugTracker#6250]
(http://www.wowhead.com/achievement=912/elders-of-eastern-kingdoms)
Can't complete this achievment. Rumblerock the Elder should be in Burning Steppes, at a top of Dreadmaul Rock, but he is not there and anywhere near.

**Comment by mean931** [comment]
Done it yesterday, he's at the top, near the little cave, on a ledge, don't know if today was bugged tho

**Comment by Larousene** [comment]
Today is no1 there :/

**Comment by Brotato** [comment]
I can't find him either. I researched a bit and it's because the wrong phasing in the zone. it happens if you did the quest chain in that zone. Please atlantiss fix it or at least give us auto complete.

**Comment by Bmuzyn** [comment]
please fix! I can't finish :( I did the questline there.

**Comment by Bildo** [comment]
fixed rev  4880
