### ISSUE TITLE
[EN][Quest][Borean Tundra] The Emissary

### ISSUE THREAD

**Issue by walker17x** [Atlantiss/BugTracker#6252]
The quest The Emissary in the borean tundra is bugged , it's impossible to complete it

The quest item "Trident of Naz'jan" should one shot the Leviroth but instead it just deals him big amount of damages and even after his death the quest doesn't complete.

thanks

**Comment by Lebiedz** [comment]
This issue was mentioned several times already - you should search for it before posting another one. There is a workaround to this bug - just fight the mob until his HP is enough to one shot him with quest item. The quest will complete then.

**Comment by walker17x** [comment]
i didn't get any result in google by searching "The Emissary Atlantiss Wow" this is why i posted this

and the private status addon didn't give any information to complete the quest , i think the addon database should be updated then.

thanks

**Comment by Lebiedz** [comment]
Maybe it should. And I suggest using bugtracker search engine instead of google :) Just type quest name in the search bar in "Issues" tab and look what comes out.

**Comment by Aviannaqt** [comment]
#3496
