### ISSUE TITLE
[EN] [npc] Sergeant Major Clate

### ISSUE THREAD

**Issue by Sinelis** [Atlantiss/BugTracker#6253]
This vendor should sell lvl 60+ pvp gear, but I can't see all items. The problem also occures with Lieutenant Jackspring. Some of my friends can see all gear, some can only see level 70+ one.

**Comment by Aviannaqt** [comment]
link

**Comment by Sinelis** [comment]
I am providing the screenshots of the vendor. As you can see he has only 5 pages of gear, while normally there are 10.
![wowscrnshot_021016_150154](https://cloud.githubusercontent.com/assets/17084945/12949325/72e8591e-d007-11e5-8154-fc6a7cfc1ff8.jpg)
![wowscrnshot_021016_150152](https://cloud.githubusercontent.com/assets/17084945/12949327/72e9cda8-d007-11e5-9f44-305882d74095.jpg)
![wowscrnshot_021016_150145](https://cloud.githubusercontent.com/assets/17084945/12949326/72e85536-d007-11e5-94ed-7953ef865c1c.jpg)
![wowscrnshot_021016_150131](https://cloud.githubusercontent.com/assets/17084945/12949328/72eaff70-d007-11e5-8892-7521cff5344a.jpg)

**Comment by TranceAccount** [comment]
Please provide a WoWhead link to the NPC, and try to be more specific with which items he doesn't sell.

**Comment by Sinelis** [comment]
I haven't played for a while on atlantiss, but he doesn't sell ANY items that are lvl 60+ PVP gear depending on class. Some ppl see some more items on certain classes.

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
