### ISSUE TITLE
[PL][NPC] PVP WARLORD SET ROGUE 60LVL

### ISSUE THREAD

**Issue by kurusek** [Atlantiss/BugTracker#6257]
WARLORD SET 60 LVL ROGUE MISSING.

Brakuje u vendora http://www.wowhead.com/npc=12795/first-sergeant-holamahi itemow PVP dla klasy rogue na 60 lvl

Dla warlocka sa, 10 stron itemów
![wowscrnshot_020516_190357](https://cloud.githubusercontent.com/assets/17088024/12855187/4365c004-cc3e-11e5-9ac0-6607e1068810.jpg)

A dla rogue nie ma, 5 stron itemów

![wowscrnshot_020516_190237](https://cloud.githubusercontent.com/assets/17088024/12855188/436825a6-cc3e-11e5-8e2c-5000a3937c79.jpg)

please add PVP WARLORD item SET for rogue 60 lvl

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-legacy-pvp-quartermasters/

**Comment by Jenovas** [comment]
Fix in rev 5541
