### ISSUE TITLE
[EN][Raid][Firelands] Alysrazor encounter

### ISSUE THREAD

**Issue by Various2** [Atlantiss/BugTracker#6259]
After server crashed (during the encounter), the boss disappeared and the feather did not spawn. The issue about it has been closed:
https://github.com/Atlantiss/BugTracker/issues/5506
However the problem hasn't been fixed yet, apparently, so I'm posting this bug.

EDIT: The whole event resetted after a couple of crashes a few hours later. (Majordomo waiting with his underlings at alysrazor's nest).

**Comment by Aldergar** [comment]
Confirmed,adding to the main thread
