### ISSUE TITLE
[EN][Character?]Zero Defence

### ISSUE THREAD

**Issue by Daggeran** [Atlantiss/BugTracker#6261]
I have been having trouble with my Paladin. My defence rating shows up as 0, even when I have the aura active. In fact it will show up as -243+*243, so as to show up as 0*.
When I unequip my armour and re-equip one by one, the armour rating will rise as normal, then randomly** it will turn back to 0 and I would have to unequip everything to try again.
From what I can see the 0 rating is accurate, I do in fact have no defence and therefore am useless as tank.

*In green
**From what I can determine, it doesn't happen on any particular item, number of armour, number of items or any other consistent cause.

**Comment by lqlq32** [comment]
WTH is defence rating, there isnt such think on this xpac.

**Comment by Daggeran** [comment]
Whatever, the damn number that tells you how much you have, your total.
It sayz fkn 0
