### ISSUE TITLE
[EN] [SKILL] [ENH SHAMAN] TREMOR AND WOLFS

### ISSUE THREAD

**Issue by masta055** [Atlantiss/BugTracker#6264]
Tremor totem doesn't properly work when shaman is charmed by Succubus. Except it, totem bugs itself when shaman gets the fear during the jump. Plus, it does not remove Priests' Mind Control. Warrior's fear effect from shout is deleted after few seconds, instead of instantly.

Spirit wolfs' skills can not be found in the Spell Book, what means shaman can't bind it on /cast macro. The only way is clicking on the pet action bar but it takes lot of time and interupts in the game focus

**Comment by BialyADI** [comment]
https://github.com/Atlantiss/BugTracker/issues/5350
Works as it should.

**Comment by Jenovas** [comment]
1 Report = 1 Bug 
Also these bugs have been reported already.
Closing
