### ISSUE TITLE
[EN][Spell]Forceful Deflection and Unholy Might

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6266]
Unholy Might - increasing you str by 25%, base str too. Then you will have more base str. For example you have 194(193 with some relogs) base str, then you spec for unholy and have 242 base str. Your parry chance must be 5.00% like base parry for dk. Forceful Deflection - not working for base str. #6195. But i checked my parry and its not 5%, its 5.07% (12 parry raiting).
Math: (242 - 194) * 0.27 = 12.96, round it down = 12. Then Forceful Deflection give you parry from base str.
![wowscrnshot_020616_124416](https://cloud.githubusercontent.com/assets/2743430/12866048/d2ab7992-ccd0-11e5-8dc5-b10cdad402c7.jpg)

**Problem is: core have some places with code where using magic numbers for calculate some things, when it must have non-magic numbers and take value from variable. It's like in my report #6241**

**Comment by BialyADI** [comment]
Warrior have The same problem.

**Comment by Jenovas** [comment]
Base STR is Base STR. If you get something that increases your STR by 25% you have BASE STR + 25% bonus STR. 

Find topics that state it should be like this.
Closing due to lack of any proof.
