### ISSUE TITLE
[PL][Spell][Paladin] Word of Glory

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#6273]
Mając 7401 spell powera Word of Glory powinno leczyć za ~13400 za 3 holy power według http://www.wowhead.com/spell=85673/word-of-glory#changelog , a w moim przypadku leczy za ~13500 za 3 holy power, i pytanie jest czy passywki które posiadam jako holy paladin działają http://cata.openwow.com/spell=85102 , http://cata.openwow.com/spell=54936 , http://cata.openwow.com/spell=63648 . Po doliczeniu tych passywek powinienem leczyć za ~20 300. Strata ~7k heala sprawia że w wielu sytuacjach lepiej użyć coś mocniejszego niż word of glory, i glyph http://cata.openwow.com/spell=93466 jest przez to kompletnie bezużyteczny.

**Comment by calladin** [comment]
Coeff z 4.2.0 na (4.3.4) nic sie nie zmieniło. ((1928+2148))+0,198*AP per charge of holy power.
Moje ap w Holy=577 unbuffed
((1928+2148))+0,198*577= 4076+114=4190        3x4190=12,570   do tego trzeba dodac +10% z glyphu na woga , 30% dodatkowo z pasywki w holy + 5% z glyphu Seal of Ins.  oraz  6% z divinity co razem daje12,570*1,51=18,980,7  ja leczę po 14,1k.   
Lecze za 14,1k
