### ISSUE TITLE
[PL][RAID][MOLTEN CORE]

### ISSUE THREAD

**Issue by masta055** [Atlantiss/BugTracker#6274]
Witam, przedostatni boss w Molten Core nie chce sie zespawnić. proszę coś z nim zroić lub chociaż oskryptować spawn Ragnarosa bez potrzeby zabicia wcześniejszych bossów.

**Comment by kepucz** [comment]
robilem na tym id molten core i wszystko dzialalo

**Comment by Syrnikus** [comment]
"oskryptować spawn Ragnarosa bez potrzeby zabicia wcześniejszych bossów."   nie blizzlike. Jak chcesz spawn przedostatniego bosa zabij wszystkie inne :) Dlatego nie mozesz tego zrobić. na dole idac do niego jest jeszcze jeden boss wiec dlatego nie pokazuje sie na gorze :)

**Comment by masta055** [comment]
![screen](https://cloud.githubusercontent.com/assets/17093367/12875164/62ef1036-cde4-11e5-992c-a101afe71848.jpg)

być może moja wina, rerobiony raid chociaż w takich przypadkach zwykle nie pozwala wejść pod powodem "fighting in progress" .
Ps syrnikus proszę o czytanie ze zrozumieniem chodzi o powszedniego bossa nie ragnarosa.

**Comment by eryczek1615** [comment]
Po dc Majordomo się już nie pojawi na tym id. Czasami po restarcie się pojawi albo po wyłączeniu serwera na jakiś czas.

**Comment by Bildo** [comment]
bt rules
