### ISSUE TITLE
[PL][NPC] Deth'tilac vs Tame Beast

### ISSUE THREAD

**Issue by Bulvers** [Atlantiss/BugTracker#6275]
Wyżej wymieniony pająk to rare spawn na molten froncie, powinien mieć na sobie buff Molten Will, który uniemożliwia hunterowi castowania na nim Tame Beast do momentu aż Deth'tilac będzie mieć mniej niż 20% hp a tego buffa niema.

**Comment by Aviannaqt** [comment]
linki
