### ISSUE TITLE
Shadow Priest ( Shadowy Apparitions )

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#6276]
The Shadowy Apparitions are not proccing my ability's like there suppose to be i have put a video link to show you in fack they dont really do anything but run to the mob and damage him sometimes they just stand there and do nothing

https://www.youtube.com/watch?v=uBUiPqJ3Dgs

**Comment by Jenovas** [comment]
But all that Shadowy Apparitions should do is run to the target and deal DMG and die.
What should they proc? What is bugged?

**Comment by Lanrutcon** [comment]
Nothing is bugged besides their HP (which is already reported). There is just a minor bug that Shadow Apparitions don't "explode" on contact when you are targeting a neutral mob (like a dummy). To "fix" this, you need to auto-attack (right-click on the unit) and the apparitions will explode.
This bug does not happen on "aggressive" npcs (red ones).


In that video, the shadow apparitions proc 3 shadow orbs (Shadow Priest mastery) whenever they reach the target. That's the 4p of T13 - http://cata.openwow.com/item=78703
