### ISSUE TITLE
[EN][Hunter] Auto attack while capturing bases

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#6277]
As a hunter sometimes while you're capturing bases/graveyards in combat on Alterac Valley, Arathi Basin, The Battle for Gilneas, (not sure about flag pickups in other battlegrounds) you are auto-shooting targetted enemy, clicking flag to begin capturing should stop any attacking.

**Comment by xolon** [comment]
can confirm this

**Comment by Bastek** [comment]
Fixed in rev. 4878
