### ISSUE TITLE
[en][mage][talent][core] Cauterize and resilence

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6283]
http://www.wowhead.com/spell=86949/cauterize

What's wrong:

Cauterize takes account of resilience, and it shouldn't be reduced by it.

proof:

http://us.battle.net/wow/en/forum/topic/2952805607

**Comment by BialyADI** [comment]
WoW, thats why Fire Mag live even without Ice Block it ;x.

**Comment by BialyADI** [comment]
I tested DK Unholy Frenzy and all was ok, not reduced by Resi.

**Comment by headachex** [comment]
I can confirm this issue.

**Comment by Illusie** [comment]
top priority. game breaking

**Comment by BialyADI** [comment]
No game breaking but PvP breaking ;p.

**Comment by BialyADI** [comment]
Bump ;<.

**Comment by headachex** [comment]
Yeap, this shouldnt be left forgotten. Its a top issue.

**Comment by Wolffenstein** [comment]
![resilience](https://cloud.githubusercontent.com/assets/1576644/12984130/af0b44fc-d0ec-11e5-817c-4f763e802ea6.jpg)

I guess 31000+ resilience and a check in Core blocking applying resilience to Cauterize is a valid enough proof.
