### ISSUE TITLE
[en][mage][spell/talent] Combustion additional tick on 40% haste

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6284]
Combustion gets additional tick on 40% haste when it should on 45%
5% - > 15% -> 25% -> 35% -> 45% ->(...)

http://www.wowhead.com/spell=11129/combustion

**Comment by ubangi** [comment]
It also does seemingly random amount of ticks with huge haste buffs (like sinestra and alysrazor) sometimes only 10 ticks with phase 3 sinestra buff.

**Comment by Caturix** [comment]
i can confirm that ticks sometimes bug out, with berserking,warp and 20% haste I get only 7-8 ticks sometimes o.O

**Comment by anxanas** [comment]
they will fix combustion when they fix doomguard and ghoul for blood and frost =)))

**Comment by lamaATS** [comment]
Fixed in rev. 5209
