### ISSUE TITLE
[en][mage][spell/talent] Improved Cone of Cold root DR

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6286]
Root effect from Cone of Cold doesn't DR with itself
it should DR with itself of course.
and other non controlled root ( like improved hamstring or paralisis from shadow priest if i am not mistaken)
http://wow.gamepedia.com/Improved_Cone_of_Cold

**Comment by headachex** [comment]
Confirming this aswell, this leads to non stop roots, especially vs 2 mages.

**Comment by BialyADI** [comment]
i was playing arena yesterday vs 2x mage was funy ;x.

**Comment by Illusie** [comment]
thank you.

**Comment by Kejmil** [comment]
@Aviannaqt fixed in rev 4889
