### ISSUE TITLE
[en][core][drop] PROBABLY smouldering essences drop chance

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6287]
Firstly i say probably due to fact chain is not working properly.
according to :4.2 hotfixes:
The number of Smouldering Essences that can be collected from a single boss in 25-person Firelands on Heroic difficulty has been reduced.
The number of Smouldering Essences that can be collected from a single boss in 10-person Firelands on normal mode has been increased.
The problem with the legendary-stuff is, that they tried to correct the "droprate" of the legendary the wrong way.

Stage 1 - Eternal Embers
Regarding to the google-spreadsheet, we get 0,8 Embers in 10m and 2 in 25m on average.
This sums up to 31 needed bosskills on 10m and 12 on 25m.

Stage 2 - Cinders
If we look again at the spreadsheet, we get 24,5 in 10m heroic and 60,5 in 25m heroic
leaving us with 41 bosskills in 10m and 17 in 25m.

Stage 3 - Essences
Previous to all the changes, we got ~8 in 10m heroic and ~18 in 25m heroic.
So 32 bosskills in 10m and 14 bosskills in 25m were needed.

As you can see, the bottleneck was stage 2, which took the most time in both raids.

Time needed for the first legendary:
10m: 104 bosskills
25m: 43 bosskills
-> 2,41:1

Time needed for all further legendarys:
10m: 41 bosskills
25m: 17 bosskills
-> 2,41:1

BUT NOW - with the change(!) - the number of essences for 25m heroic got nerfed to 9,5.
For the 250 essences you now need 27 bosskills and so the new bottleneck for 25m is stage 3 whith 27 bosskills.

Because of that, the time needed for a further legendary is now:
10m: 41 bosskills
25m: 27 bosskills
-> 1,52:1

I would not be surprised if 25m-Raids would now be "forced" to run 10m to optimize stage 3.
The only correct way to slow down the "droprate" of the legendary whould have been to reduce the droprate of the cinders to tighten the previous bottleneck.

http://www.mmo-champion.com/content/2440-September-9-Hotfixes?page=2

**Comment by aneq** [comment]
the comment is from the day before the hotfix (hotfix was deployed 9 september and the comment is dated as 8 sept.), meaning the numbers and nerf is purely a speculation

**Comment by adryjan** [comment]
Blink no sense in speculating, MoP will come faster to ATS than working chain.

**Comment by Aviannaqt** [comment]
:+1:
