### ISSUE TITLE
[en][druid][core] Bear form rage generation from damage taken.

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6288]
https://www.youtube.com/watch?v=_ZHTBXySmK8
3:41 -> 3:45 watch at 0.25 speed
http://www.wowhead.com/spell=22842/frenzied-regeneration#comments

Joejr82 on 2012/07/18 (Patch 4.3.4)
It's up to 60 rage, you can pop this with any mount of rage and get healed based on the amount of rage spent up to 60. **The only way to build rage now is to do damage**, kite the bear attack from range they wont have any rage to spend to heal.

https://www.youtube.com/watch?v=szdFET0uuEc
1.10 -> 1:30 watch at 0.25
on our server you get rage from taking damage.

**Comment by Jenovas** [comment]
on our server you get rage from taking damage. - because you should.
Closing.

**Comment by Kejmil** [comment]
they were discussing druid changes in MoP
