### ISSUE TITLE
[PL][Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by lelokrul** [Atlantiss/BugTracker#629]
Po zabraniu questa, nic nie można zrobić, nie ma odpowiedniej opcji w rozmowie.
Link do q:http://www.wowhead.com/quest=24553/the-purification-of-queldelar
Najprawdopodobniej quest nie działa również dla hordy.
Oraz quest można zabrać bez wykonania poprzednich questów z chaina.

**Comment by Hordraric** [comment]
due to sunwell being close in 4.3, this dungeon isnt doable. all previous quests work :)

**Comment by armano2** [comment]
new issue: #4216
