### ISSUE TITLE
[en][druid][spell/talent] Feral Charge Cat

### ISSUE THREAD

**Issue by Horpah** [Atlantiss/BugTracker#6290]
Feral Charge in Cat form should leap behind target. 

http://www.wowhead.com/spell=61132/feral-charge

In Atlantiss it works as bear charge or warrior charge - not leaping behind target.

**Comment by phifedawg** [comment]
#5277

**Comment by Jenovas** [comment]
As in the previous issue - this is a pathfinding bug and sometimes you jump in front sometimes in the back of the target.
Closing.
