### ISSUE TITLE
[EN][Calendar] World Events

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#6292]
Lunar Festival
Love is in the Air
Children's Week
Pilgrim's Bounty
Those four world events aren't displayed on calendar.
Its sort of a bug (since retail cata was from 2010-12) but it should be scripted here for this and years ahead

**Comment by Wolffenstein** [comment]
As far as I know these events weren't displayed in 4.3.4 client, since the server has no control over it.

**Comment by xolon** [comment]
I've seen on other cataclysm servers that its displayed, which means that they updated calendars.
And it like this, Cataclysm on retail was during 2010-2012 and then it was displayed, we have Cataclysm now, why shouldn't it be displayed now?

**Comment by xolon** [comment]
If you backtrack the calendar to 2010-2012 you can find those events

**Comment by xolon** [comment]
Forgot about Darkmoon, but i believe its used after the 4.3 patch for Darkmoon isle 
http://i.imgur.com/Ohj9vqY.jpg (you can see here, lunar and love is in the air)
