### ISSUE TITLE
[EN][Quest][Mount Hyjal] The Twilight Egg

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#6293]
It's impossible to complete this quest, because NPC - Aronus(40816) is missing. I enclose Youtube link that shows how should it work properly.

https://www.youtube.com/watch?v=RguhmS0Db0o

Link: http://www.wowhead.com/npc=40816/aronus

**Comment by Matti297** [comment]
this quest works i did it 4 days ago

**Comment by Assiria** [comment]
yeah if u do earlier q try to relog or leave this location for a while, he will appear

**Comment by Aival94** [comment]
Quest is working just fine.

Minor bug: Some mobs (one is [Twilight Subjugator](http://www.wowhead.com/npc=40463/twilight-subjugator) are showing that they can drop [Pure Twilight Egg](http://www.wowhead.com/item=55178/pure-twilight-egg) (they are not dropping it).

**Comment by vidplace7** [comment]
This bug is still, in fact, an issue. Aronus is NOT present at the defined location.
