### ISSUE TITLE
[EN][Quest][Deadwind Pass] Medivh's Journal

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6294]
http://www.wowhead.com/quest=9630/medivhs-journal#comments
How it should work: This quest should become available only after becoming honored with the Violet Eye faction (also see wowhead comments about this in the link above).
What is bugged: This quest is available regardless of reputation status with the Violet Eye.

**Comment by DuGalle** [comment]
Confirm. Tho the chain is bugged after few quests :(

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10937-quest-medivhs-journal/

**Comment by aje** [comment]
fixed in revision 5115
