### ISSUE TITLE
[EN][NPC]Roxi Ramrocket Bugged!

### ISSUE THREAD

**Issue by zainkiller4** [Atlantiss/BugTracker#6296]
Hey GM, 
So basically I want to make myself a Mekgineer's Chopper and I need to buy the mats but when I click on the NPC who sells them she doesn't not have the option to sell them and goes straight to the flying trainer tab. I'm not sure if its bugged or not. Please help thanks. NPC ID 31247

**Comment by monibu** [comment]
"I'm not sure if its bugged or not."
If you're not sure, search on web or ask in-game. BugTracker is for reporting bugs you're 100% sure of.

And the npc works just fine - that said she only sells those parts to engineers having the recipe.
