### ISSUE TITLE
[PL][SHAMAN][SPELL/TALENT] Elemental Fury

### ISSUE THREAD

**Issue by piernik666** [Atlantiss/BugTracker#6298]
Witam znalazłem buga na Elemental Shamanie, a mianowicie nie nalicza bonus crita ze spella Elemental Fury - spell ten powinien dawać bonus crit dmg 100%. Przeprowadziłem kilkanaście prób zarówno na Shamanie Ele jak i Magu arcane/fire aby się upewnić czy crit dmg wynosi x2 jak na wowheadzie. Przeprowadzone próby pokazały ze mamy przelicznik x2 w rozsądnej granicy błędu (najczęściej przelicza około x2.05). Niestety na shamie ele przelicznik jest identyczny a powinien wynosić x3 lub x4. Zależne to jest czy naliczamy 100% bonusu od dmg podstawowego czyli  (x*2 + x) = 3x dmg; czy 100% bonusu dolicza się do crita (x*2)*2= 4x, gdzie x to bazowe dmg spella (np. lava bursta). Do przeprowadzanych prób zdjąłem wszelkie odpałki zwiększające czasowo dmg ( triny jak volcano, staffa z power torrentem itd.), żeby dmg spellu w trakcie prób nie zmieniało wartości. 
Poniżej wrzucam screena z przeprowadzonych prób:
http://pl.tinypic.com/r/152ksg8/9

**Comment by BialyADI** [comment]
U mnie dział wszystko ok, pamiętaj że magczny Crit ma przelicznik 1,5x.

**Comment by piernik666** [comment]
na magu zarówno arcane jak i fire też uderza x2 więc nie wiem skąd masz przelicznik x1.5 (wg wowheada taki jest na wodzie dopiero)

**Comment by piernik666** [comment]
inaczej na wodzie zmniejszają na pvp crit dmg, więc dlaczego magowie też mają takie mocne crity ?

**Comment by piernik666** [comment]
Dobra patrząc na opis spella dochodzę do wniosku, że faktycznie dobrze działa bo zwiększa bonus do 100% a nie o 100%. Znalazłem też info ze magowie i warlocki mają bez talentów 200% ( nie wiem po co shamanowi dają skilla takiego, jak inni mają od razu). Temat zamknięty.

**Comment by Kejmil** [comment]
zeby resto nie robil depsu i dps enha byl zbalansowany :P
