### ISSUE TITLE
[EN][Event][Lunar Festival]+[Zone] Maraudon Entrance 

### ISSUE THREAD

**Issue by Larousene** [Atlantiss/BugTracker#6299]
Entrance to Maraudon is bugged. I've tried enter it(click it, pass through)  in 5-man party, normal mode and nothing happened.

**Comment by Luna-maria** [comment]
worked fine for me two days ago :o

**Comment by Larousene** [comment]
i've tried to enter it on my own (with 2 pals, not by dungeon finder or else) and we couldn't enter through the portal :/ We've tried it on Friday and today - still the same problem

**Comment by mean931** [comment]
I'm pretty sure u're doing something wrong there, I've done it multiple times, maybe u're just entering from a bugged entrance, try the others, maraudon's got like 3 entrances

**Comment by Larousene** [comment]
That portal (shown on youtube clip) is bugged: https://www.youtube.com/watch?v=Du657fzrgQ8

**Comment by NatsumeLily** [comment]
Go in through the entrance portal..It works fine...The shortcut portal might be bugged but you can still get in.

**Comment by x3m1** [comment]
Entrance to Maraudon is still bugged. I've tried to pass through and nothing happen.
