### ISSUE TITLE
[EN][Item] Matrix Restabilizer vs. Tranquilizing Shot

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#6302]
Matrix should only proc from harmful abilities.
Currently on ats, Tranquilizing Shot can trigger the proc.
http://www.wowhead.com/item=68994/matrix-restabilizer

**Comment by Kejmil** [comment]
"Your melee and ranged attacks have a chance to grant ..."
trans shot is using ranged table, so working as intended

hell, it was procing even from Sap on retail:
http://www.wowhead.com/item=68994/matrix-restabilizer#comments:id=1634296
