### ISSUE TITLE
[EN][Firelands] Baleroc.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6303]
Hello.
We did killed in Firelands 4 bosses (Beth, Shannox, Lord Rhyo and Baleroc) in 1st day, and then wanting continue in other. Today im checking our save for fun and Baleroc stay alive. My save said he is defeated.
![wowscrnshot_020816_194044](https://cloud.githubusercontent.com/assets/2743430/12892229/35ea921e-ce9c-11e5-8567-b1fd325706c6.jpg)

**Comment by LaveniaGithub** [comment]
Yesterday server was crashing a lot, maybe one of the crashes made a rollback to when the boss was alive?

**Comment by metaldoctor** [comment]
We killed boss at saturday when server dont have crashes.

**Comment by anxanas** [comment]
Praise the lord, more loot
