### ISSUE TITLE
[EN][Event][Lunar Festival][Item] Lunar Festival Fireworks Pack

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6305]
http://www.wowhead.com/item=21640/lunar-festival-fireworks-pack#contains

was empty

**Comment by artamedan** [comment]
Not relevant. Not important. Fireworks are so cheap that you should be ashamed to put this as an issue.

**Comment by Luna-maria** [comment]
pfff, bugs can be reported, I never said it was high priority or anything, now please bugger off and let the devs decide whether to close, fix or ignore this post tyvm

**Comment by coba999** [comment]
still empty

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/13006-6305-lunar-festival-fireworks-pack-loot-tables/
