### ISSUE TITLE
[EN][Spell][Shaman] Flametongue Totem

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#6307]
Hello.

http://cata.openwow.com/spell=8227
Flametongue Totem should increase the Spell Power by 6%.

But I think it bugged according to those screenshots I made:
Wondering if it visuality or actually bugged.

http://imgur.com/a/quKWR

**Comment by adryjan** [comment]
Listen to me bro step by step:
-Open character tab without totem
-Put totem
-Close character tab
-Open it again

Bam! ;]
