### ISSUE TITLE
[EN] [Quest] [Utgarde Keep]

### ISSUE THREAD

**Issue by linesar** [Atlantiss/BugTracker#6312]
The quest obtained from the npc in the beginning of Utgarde Keep in Northrend can be completed each time you enter the dungeon. With all the rewards and exp given every time.
http://www.wowhead.com/quest=29763/stealing-their-thunder
http://www.wowhead.com/quest=29803/ears-of-the-lich-king
http://www.wowhead.com/quest=29764/disarmament

**Comment by Aviannaqt** [comment]
link

**Comment by linesar** [comment]
what the quests names are?

**Comment by Lebiedz** [comment]
I can add also that as alliance player you can get all 3 quests, where [Ears of the Lich King] (http://www.wowhead.com/quest=29803/ears-of-the-lich-king) is horde quest and results in getting rep with the horde expedition. I don't know how does it look for horde players.

**Comment by Fapguy** [comment]
I kinda like this. This is one of those things that shouldn't be fixed even if it isn't blizzlike.

Makes Utgarde Keep more bearable for people leveling, since UK is what you get 80% of the time...

**Comment by Aldurion** [comment]
No, you get Nexus 80% of the time.

**Comment by sunshitwowsucks** [comment]
The easiest way to level, RIP xD
