### ISSUE TITLE
[en][mage][spell/talent] Water Elemental mana regeneration

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6313]
After few of the recent fixes ( approx 2-3 days of fixes) water elemental mana regen bugged. Its about 50 mp5 on 85 lvl. 
http://www.wowhead.com/spell=31687/summon-water-elemental

**Comment by ocbald** [comment]
Confirmed

**Comment by blinkmaster** [comment]
Show some love to blue bubbles :(

**Comment by Pankaa** [comment]
3-5min in fight and pets oom gg(no dmg/freez) -_-

pls fix

**Comment by Jenovas** [comment]
Fixed in rev 5076
