### ISSUE TITLE
Area 52 pvp old sets npc

### ISSUE THREAD

**Issue by scylus** [Atlantiss/BugTracker#6314]
w danej lokacji powinien stac npc ktory sprzedaje za jp itemy z 1 sezonu pvp. (tzn ich repliki do transmoga) niestety npc nie odpowiada. pozdrawiam

**Comment by BialyADI** [comment]
Może cie nie lubi mi odpowiada.

**Comment by scylus** [comment]
odpowiada ci npc z itemami z 1 sezonu?

**Comment by scylus** [comment]
dla jasnosci classic allianc mail and plate ?

**Comment by BialyADI** [comment]
Napisz poprawnie polsku to lub ewentualnie po angielsku, bo nic nie rozumiem.
Mi działa NPC.

**Comment by Lebiedz** [comment]
NPC działają, ale nie mają nic do sprzedania, choć powinni sprzedawać - jeden repliki setów pvp na 60 lvl, a drugi repliki broni do celów transmogowych. Co do autora tematu: przeczytaj zasady bugtrackera i popraw zgłoszenie.
