### ISSUE TITLE
[PL][Mage][Talent] Shattered Barrier DR/Improved Cone of Cold DR.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6315]
Bug z https://github.com/Atlantiss/BugTracker/issues/6286 nadal występuje.

Jak jest:
Nova po rozbiciu Ice Barrier nie ma DR z Improved Cone of Cold.

Jak powinno być:
http://www.mmo-champion.com/threads/862509-Shattered-barrier-useless-talent-now
http://wow.gamepedia.com/Shattered_Barrier
Cataclysm Patch 4.1.0 (2011-04-26): The root effect from Shattered Barrier now shares diminishing returns with the root from [Improved Cone of Cold].

Dodatkowo Improved Cone of Cold nie ma DR samo ze sobą.
http://cata.openwow.com/spell=83302 <- Improved Cone of Cold
http://cata.openwow.com/spell=83073 <- po rozwaleniu bariery root(Shattered Barrier)

**Comment by Kejmil** [comment]
@Aviannaqt fixed in rev 4889
