### ISSUE TITLE
[EN][Priest][Talent] Harnessed Shadows

### ISSUE THREAD

**Issue by pignon87** [Atlantiss/BugTracker#6319]
I was wondering why the shadow orbs were triggering so low on this server compared to retail.After few tests at dummyes i've found out this.

**What is wrong:**

http://wow.gamepedia.com/Harnessed_Shadows  
With 2/2 this Talent is not giving 100% chance to get a shadow orb when performing a critical strike with any spell.

**How should it be:**

2/2 Harnessed Shadows should give a 100% chance to get a shadow orb when a critical strike is performed with any spell.

EDIT: Didn't noticed that the bug was already reported https://github.com/Atlantiss/BugTracker/issues/1613

Anyway that report is in polish, it would be usefull to know what is discussed there..i see like a code or something,but a year has passed and bug still persists,so guess that's not a "fix" ,and i don't understand why that report is closed since the bug it's not fixed yet.

**Comment by BialyADI** [comment]
All works ok.
You gain Shadow Orb when some one Hit you by physical or spell attack.

http://wow.gamepedia.com/Harnessed_Shadows
"50/100% when hit critically by any physical or spell attack."

**Comment by Jenovas** [comment]
This gives you a Shadow Orb when YOU are critically hit by someone.
A warrior crits you for 20k you get a shadow orb.
