### ISSUE TITLE
[EN][Quest][Winterspring]'Borrowing' From the Winterfall

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6320]
http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall

No meat sacks are spawned on neither camps so if you are unlucky and get this daily multiple times you wont get mount for 20 days but for a lot more

**Comment by Larcan** [comment]
Still bugged

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1647
