### ISSUE TITLE
[EN][Dungeon-Cata][NPC][Spell] Zul'Aman - Nalorakk "charges" totems

### ISSUE THREAD

**Issue by gumby123** [Atlantiss/BugTracker#6322]
Boss Nalorakk http://cata.openwow.com/npc=23576 uses spell Surge http://cata.openwow.com/spell=42402 on shaman's **totems**. Pretty sure it should only work on alive & friendly **players**.

**Comment by Prodiege** [comment]
Still happening

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5107
