### ISSUE TITLE
[EN][Core][Class][Warrior] Charge

### ISSUE THREAD

**Issue by Radeghost** [Atlantiss/BugTracker#6328]
Charge does not work. No path available, almost everywhere. Auto-attack is bugged too, since Charge should toggle auto-attack, but it does not. 
Urgent issue.

**Comment by Radeghost** [comment]
Same goes for Heroic Leap.
Warrior is beyond broken now. No charge, no leap, 0 mobility

**Comment by BialyADI** [comment]
Same with off-hand in Dual Wield in Fury.
https://github.com/Atlantiss/BugTracker/issues/6300
But no one give a fuck.

**Comment by captjvmoore** [comment]
I confirm. As of right now, warrior class is completely useless because of this...

**Comment by headachex** [comment]
Its not "useless", you can add /startattack after /cast Charge and you have yourself a working macro. Its still an issue though.

**Comment by captjvmoore** [comment]
I am fully aware that Charge is not supposed to trigger auto-attacking. Aside from that, Charge failed to execute in BH10 last night. As usual, it notified via floating message that boss is imune to stun, but my character never actually moved from charging point to the designated target, in this case - the boss. Furthermore, I am still getting the "no path available" bug from time to time in random places, I can't remember where exactly. One thing I remember was that in Warsong Guilch, when attempting to charge at the elevation of the Spirit Healer(Horde side respawning point), I get this message, but when I do this in Tol Barad I can freely charge anyone that is respawning in their respective Spirit Healer sites and Reckstorm the fuck out of them all. I believe you're not supposed to be able to do that, not with warrior/feral druid at least.
