### ISSUE TITLE
[EN] [BG] [WSG] Falling through ground

### ISSUE THREAD

**Issue by Sinelis** [Atlantiss/BugTracker#6329]
I just got feared through the map in Warsong Gulch. When dead the flag gets automatically returned to their base I assume
![wowscrnshot_021016_145255](https://cloud.githubusercontent.com/assets/17084945/12949089/7bf02b28-d006-11e5-929a-7a3938f52f24.jpg)

**Comment by texa69** [comment]
That happens also when I use Shadowstep

**Comment by Aviannaqt** [comment]
its global maps bug.
