### ISSUE TITLE
[PL][Spell][Mage] Mirror Image

### ISSUE THREAD

**Issue by Asavel** [Atlantiss/BugTracker#633]
http://cata.openwow.com/spell=55342
Co działa:
1.Zmiana uzywanych spelli przez Glyph of mirror image ( http://cata.openwow.com/item=45739 )
2.Slow z Frostbolt'ów 
3.Stacki Arcane Blast skracają czas cast'u 20/40/60/80/100% same go sobie nabijaja a powinny pobierac je od nas
co nie działa:
1. Za maly dmg. 
2. <strike>Missuja nawet jesli posiadamy hit cap. <strike>
3. Nie crytuja
4. PoM nie daje pierwszego casta jako instant
5. Za duża ilość hp i many

Przy 7141SP mirrory bija po:
- Fire blast 490-510
- Frostbolt 800-821
- Fireball  99-114
- Arcane blast 1400-1560 jest prawdopodobnie poprawny jedynie złe działanie stacków obniża dmg 

Staty:
- 20% HP 
- 100% Many
- 33% Spell Power
- Frostbolt 30% Mirror Image Spell Power/10% Mage Spell Power
- Fireball ??% Prawdopodobnie tak samo jak Frostbolt
- Arcane Blast  ??% Prawdopodobnie tak samo jak Frostbolt
- Fire Blast 15% Mirror Spell Power/5% Mage Spell Power

link do przelicznika: http://www.wowwiki.com/Spell_power_coefficient

**Comment by Shainear** [comment]
Sprawdziłem jeszcze dla porządku dmg Mirrorów (bez glypha) z simcraftem i oto wyniki dla postaci z ok. 7850 SP. Jako że dmg reszty spelli się zgadza, to można myślę przyjąć, że simcraft nie myli się też co do Mirrorów. 
Atlantiss: Frost bolt ~ 860 
                Fire blast ~ 480 
Simcraft: Frost bolt - minimalny dmg 1610, średni 1719
                Fire blast - minimalny dmg 927, średni 992
http://oi59.tinypic.com/642r5y.jpg
http://oi58.tinypic.com/1492sfp.jpg
Jak to na Atlantissie wygląda każdy może sobie samemu sprawdzić. Mirrory bez glypha biją u nas niemal dwa razy za słabo, nigdy nie critują i missują mimo hit capa. Jeżeli ktoś będzie zainteresowany to sprawdzę jeszcze te wartości dla zglyphowanych wersji.
Jest to kolejny po zatrważająco działającym flame orbie skill maga z mocno ograniczoną użytecznością.

**Comment by Danelar** [comment]
O kurcze - nigdy na to nie zwracałem tak uwagi :O 
Faktycznie biją mi ognistymi czarami i rzadko forstboltem :| 
Do tego dochodzi jeszcze problem z transformacją - zamieniłem się na święta w Gnoma - to mi "zmutowało" BElfa z gnomem i koszmarne to było :< Gorzej jak zamieniło w kobietę... 

@Shainear " Kiepska próba trollingu" - może dlatego, że to nie był troll? Ja tak na serio.

**Comment by Asavel** [comment]
Bump!!!

**Comment by armano2** [comment]
simmilar: #2059

**Comment by pelekon** [comment]
Due to fact that this report is very old, I am closing it if sth is wrong with Mirror Image after rev 5840 make new report.
