### ISSUE TITLE
[EN][Mage] T12 Set Bonus

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#6330]
The 2P bonus is still interrupting spell cast upon mirror spawn as of rev 4886. 

Previous ticket was closed because the bug had supposedly been fixed #6076. Can't speak for 4P yet because unlucky with tokens.

**Comment by blinkmaster** [comment]
Can some1 check if 4p reduces Total or base mana of spells in arcane power?

**Comment by Kejmil** [comment]
@Aviannaqt fixed in rev. 4889

**Comment by kostas4949** [comment]
@blinkmaster Reduces by base mana. At 4 stack you have around -90 mana cost reduction :D

**Comment by Kejmil** [comment]
from simcraft:
" // Arcane Power only affects the initial base cost, it doesn't inflate the stack cost too"

**Comment by kostas4949** [comment]
From forums:
http://us.battle.net/wow/en/forum/topic/3082033369  post #4 and #5

Seems it used to be the way simcraft says in the start, then they changed it.

**Comment by Kejmil** [comment]
@kostas4949 make new issue about it then
