### ISSUE TITLE
[EN][Silithus][Quest][NPC] Commander Mar'alith

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#6331]
Commander Mar'alith in Silithus doesnt offer any quests after completing  "Vyral the Vile".
It should offer it after that.I am high lvl. I did the prequest from Ungoro. I did all quests i could in the area, and im Friendly with Cenarion Circle but after 10 quests i cant take any more quests in Silithus.

The first quest is http://www.wowhead.com/quest=8304/dearest-natalia
in the coments - "this quest requires you complete  Vyral the Vile before it's available."

I saw ppl with 19/19 Silithus quests. So this bug must be a new one.

**Comment by Bildo** [comment]
Vyral the Vile needs to be completed first
