### ISSUE TITLE
Haste not changing after spell buff

### ISSUE THREAD

**Issue by lamaze** [Atlantiss/BugTracker#6333]
![screenshot 2016-02-11 00 29 42](https://cloud.githubusercontent.com/assets/17169526/12965735/c3708086-d058-11e5-8f11-8e2b3e94f9c6.png)
As the image i attached shows, when i use all my cooldowns, trinkets, buffs, ecc... haste is not changing (the "white" note shows correct stat, but the "yellow" detail doesn't change so i benefit from my original haste without buff)... even if i got 39% haste with full buffs, when i cast some spell they are slow like if i don't have any buff on me. 
I have experienced this issue only on haste, i didn't checked if any other stat if affected too.

**Comment by anxanas** [comment]
It works perfectly for me, tested it on warlock, holy pala and balance druid. Maybe you should mouseover your abilities or try to cast something so we can see that you dont get haste increase, from what i am seeing now you are high and everything works like it should
