### ISSUE TITLE
[EN][Shaman][spell]Lava lash doing too much damage

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#6334]
http://cata.openwow.com/spell=60103
Lava lash seems to do too much damage, i tested this with 2 low lvl weapons and no gear on.

"You charge your off-hand weapon with lava, instantly dealing 260% of that weapon's damage to an enemy target. Damage is increased by 40% if your off-hand weapon is enchanted with Flametongue.
 I also use glyph of lava lash which increases the damage by 20% and i have the base mastery which is 20%. My OH damage is 50-60. 

So now lets calculate the lowest amount of lava lash damage i should do: 50 * 2.60 * 1.40 * 1.20 * 1.20=262,08
Now lets calculate the highest lava lash i should be able to do:
60 * 2,60 * 1,40 * 1,20 * 1,20=314,496
This gives us a damage range of 262,08-314,496
Now lets try attacking a dummy 10 times in game(crits will be taken out to make it easier)=
1: 294
2: 294
3: 323
4: 294
5:312
6:329
7:318
8: 291
9:318
10: critted so will be let out.

From this we have a damage range of 291-329 which is much higher than the calculated damage is. I have a theory that it is due to mastery douple dipping lava lash(like with many other abilities in the past), so let us try to add 20% to the calculated damage and see if it lines better up with the actual damage we got.
262,08 * 1,20= 314,496
314,496 * 1,20=377,3952
Which gives us a damage range of 314,496-377-3952, which is higher than the damage ingame

Conclusion: It seems to do more damage, but this small damage difference is probably not the reason for the huge lava lashes that is done.

If anyone didnt understand something just write it in the comment section and ill try to explain it to the best of my ability. 

Edited the thread since i found out that lava lash glyph increase it by 20% instead of 10%

**Comment by fizzle7** [comment]
I got crit for 36k as feral with 3.8k resilience while dealing 20k crit fb. Clearly server majorly shat itself somewhere.

**Comment by xolon** [comment]
I can confirm this, i just did some math with my shaman and the values are incorrect, damage has a big boost

**Comment by anxanas** [comment]
Please dont link your pvp experience with this ability it will only confuse more, cause of resilience+resist+damage reduction abilities+absorbs+the shaman lacking pve gear(aka high lvls of mastery)

**Comment by Evelinrose** [comment]
Here is just an example of how crazy this dmg can be,ss shows dmg on dummy with no buffs used other then ones shaman can provide naturally such as attack power and 550 agility(in raids it can crit 180k on bosses with no dmg inc on them)
http://imgur.com/4dmOSMp

**Comment by meowmewo** [comment]
Something does seem changed with lava lash. What was 50-60k crits before self buffed on dummies now is 70 up to 90k crits with the same gear.

**Comment by Kejmil** [comment]
t12 2p...
t12 4p propably working for all shamans

**Comment by anxanas** [comment]
I didnt use t12 to calculate my damage so i dont see your point, and just find me a source where someone in firelands nm gear does 180k lava lashes in raid with no damage increase and ill close this topic.

**Comment by Jenovas** [comment]
Please show us these 180k crits. And also give us the nick of your friend shaman.

**Comment by Bastion** [comment]
ja wczoraj w baleroca uderzyłem tyle ale to na wszystkich odpałkach siadło

**Comment by anxanas** [comment]
Jenovas ill SS it next wednesday(where ids reset), unless you want to reset his ID, and ill tell you his name after i ask him and he says ok.

**Comment by anxanas** [comment]
http://www.mmo-champion.com/threads/954034-Highest-Lava-Lash-Crit  
Take this into account with the picture evelinrose linked, where the shaman self buffed was able to crit 126k while people from retail(who were doing hc) could barely get it to 105k where they most likely had a lot of buffs from other classes,

**Comment by aneq** [comment]
@Jenovas lama has an idea that flat % increase masteries like enhancement shaman and survi hunter ones might be double dipping somewhere with spells like lava lash and cobra shot (he didnt confirm it yet tho, I think it's worth a shot)
This would explain the issue @anxanas  is having without t12 2p

**Comment by anxanas** [comment]
@Aneq no if you read the thread that you would see that it probably has nothing to do with this

**Comment by aneq** [comment]
Were there any updates since yesterday then? I didn't read those

**Comment by anxanas** [comment]
Yes i made some updates but i just read through it they were not applied, i assumed glyph of lava lash increased it by 10% its 20%, will update it again

**Comment by aneq** [comment]
Well your thread still says something about having too much damage from mastery.
In this case, shaman t12 2p issue is something completely different from the lava lash getting too much of an increase from mastery, correct?

**Comment by anxanas** [comment]
Aneq ye, i actually changed the thread around 2-3 am(when i found out my mistake), but i must have forgot to click update. There isnt a huge difference between the damage i calculated and the damage i did, so i cant really claim i found the bug, but something is clearly wrong with lava lash since people get so high lava lashes with it, i will keep the thread open since i am still 100% sure it is bugged, i just cant manage to find out how

**Comment by aneq** [comment]
If it's the 12 2p then it would actually make sense.
I did some simcraft tests in the past when people cried about enhancement and it was roughly in the same ballpark as it was on the server, so t12 2p makes sense

**Comment by anxanas** [comment]
It could also be the 4p bonus, it is hard to test when you dont have the gear and PTR no longer has easily obtainable gear.

**Comment by lqlq32** [comment]
Go in world of logs, check shamans that do 40-50k dps and see their crits on lavalash there isnt any with with more than 100k on baleroc.

**Comment by mitim1** [comment]
-.- Baleroc = 4.2 Atlanitss = 4.3.4

**Comment by fizzle7** [comment]
Oh no, PvP is very relevant since if it ignores resilience we're gonna have a major problem. Solve PvE but look into PvP as well. As I recall it wouldn't be the first time a shaman spell has ignored resil.

**Comment by Jenovas** [comment]
As I recall it wouldn't be the first time a shaman spell has ignored resil. - wat?

**Comment by Necromnef** [comment]
I can surely confirm that LL was doing 170/180k crits in Firelands at beleroc and Majordomo encounters ( because i was the one who did them xD), unfortunately i did not ss the the LL crits but it rly dose crit that much and now since i got even more gear on my shaman in the last raid i did on it, it can possibly go even higher with all procs up. And about the tier 12 2p being bugged i don't think that is the case, i did some testing earlier today ( unfortunately forgot to ss ll crits  as well) even by removing both 4 and 2p bonus of tier 12 i was still doing crits upto 100k witch shouldn't be happening.

**Comment by Kejmil** [comment]
double mastery for some players again?

**Comment by Wolffenstein** [comment]
Probably, since it doesn't matter how much time I spend calculating and modifying different things, I always get proper damage on my local server.

**Comment by Kejmil** [comment]
then it wouldn't be only enh problems, i heard also some strange things like full pvp mage pulling more dmg with ice lance than human mage with double trinkets, pve offparts, etc.
and some of this can go unnoticed even now, like survi hunter mastery (low percentages)

**Comment by lqlq32** [comment]
If mastery is 2x then all of their skills will do more dmg but their dmg seems ok to me, around 30k with bis.
[http://prikachi.com/images.php?images/716/8630716o.png](url)
[http://prikachi.com/images.php?images/715/8630715H.png](url)

**Comment by meowmewo** [comment]
... They arent saying the mastery is 2x, but Lava Lash double dipping from it.

**Comment by anxanas** [comment]
Lava lash doing 25% damage is non blizzlike at all, it usually did from 15%-20%, it is clearly bugged but like wolffenstein said, that the calculations of the abilitys damage fits very well with how much damage it does. But maybe it is double mastery for some players

**Comment by lqlq32** [comment]
There is a difference between 2x mastery and ability scaling with 2x mastery. In 1st case, all skills will benefit from it, in 2nd it will be only one. How i can understand what ppl mean under "double mastery", also yes i took a break between juny-november.

**Comment by fizzle7** [comment]
> As I recall it wouldn't be the first time a shaman spell has ignored resil. - wat?
As I recall there were enh spells ignoring resil before, but I'm not sure. What I mean is, there's no point in ignoring PvP since there could be bugs there as well.

**Comment by Necromnef** [comment]
As far as pve iv seen some absurd lava lashes on npc a lot, but as far as pvp what what iv seen ( tested ) lava lash dose not do any insanely high damage in pvp, at least on ppl who have minm of 3k resil, have not seen a higher crit then 25k ofc i was in full pvp gear and i try'd it on ppl with actual pvp gear as well as different armor types.

**Comment by Jenovas** [comment]
Should be better now. Please create a new report if the DMG is still to high.
