### ISSUE TITLE
[PL][Core] Burn Corpse

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6336]
rev. 4885 Author: Wolffenstein :: 2016-02-09 23:46
[Eastern Plaguelands]:
Removed possibility of applying Burn Corpse aura to players.

Nadal biegają gracze z Burn Corpse na sobie.

**Comment by Kejmil** [comment]
aura nie ma duration (chyba), wiec ci co ja mieli do czasu smierci albo unaury dalej beda z nia biegac

**Comment by anxanas** [comment]
They applied it before the fix.
Ich stosowania , a przed fix

**Comment by Aviannaqt** [comment]
to zamykac to czy nie?

**Comment by Wolffenstein** [comment]
Poproś GMa o usunięcie aury.
