### ISSUE TITLE
 [EN][Shaman][Item]T12 2p Enh increases lava lash by too much

### ISSUE THREAD

**Issue by anxanas** [Atlantiss/BugTracker#6337]
http://www.wowhead.com/spell=60103/lava-lash#comments
http://www.wowhead.com/spell=99209/item-shaman-t12-enhancement-2p-bonus
Shaman 2p seems to increase lava lash damage by way too much, here is how it should work: when you have a stacks of searing flame on the target you get 25% damage increase which makes 5 stacks 125% not. Proof; http://www.wowhead.com/spell=60103/lava-lash#comments the comment by Pope

 I did some testing with the 2p with no procable damage increasing items(only including normal attacks) I first tried it without having 5 stacks of searing, doing 10 lava lashes on the dummy, and got an average lava lash damage of  11647,3, that means that with a 5 stacks of searing flames lava lash should do on average 11647,3x2,25=26206,43. Then i did the same thing with 5 stacks of searing+ the 2p bonus. And got an average lava lash of 30581, which is clearly higher than it should be. My theory is that instead of multipling the damage with x2,25(Like it should), it first multiply the damage with x2 and then x1,25. Lets see if this is correct 11647,3x2x1,25=29118,25. This is a lot closer and might be the problem. 

You guys are more than welcome to guess how it is bugged.

**Comment by blinkmaster** [comment]
im kind of curious how many spell might be bugged right now.

**Comment by anxanas** [comment]
https://www.youtube.com/watch?v=KyqTd-cNYlY this shaman has the 2p too and doesnt seem to be doing OP lava lashes

**Comment by lamaATS** [comment]
Fixed in rev. 4898 (missing close)
