### ISSUE TITLE
[EN][Quest][Nagrand] HELP!

### ISSUE THREAD

**Issue by rinovntr** [Atlantiss/BugTracker#6338]
http://www.wowhead.com/quest=9923/help#screenshots
'Corki' is out of the cage already
and after u have the Key
u cant click the cage
so the quest stuck
please help

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6338

**Comment by Aequitass** [comment]
bump

**Comment by Bildo** [comment]
fixed
