### ISSUE TITLE
[PL][SPELL][EARTH SHIELD][SHAMAN]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6339]
Earth shield posiada zbyt krotki ICD miedzy zjadaniem stacku z uwalnianym healem a  obrywanym dmg, powinien miec 3,5 sec icd.

**Comment by Kejmil** [comment]
a dowody i linki zly pet bma zjadl

**Comment by calladin** [comment]
http://forum.warmane.com/showthread.php?200872-Shaman-Changes-from-4-0-6-to-4-3-4-%28enh-resto-and-ele%29
z 4.1 na 4.2
Water Shield has had its internal cooldown reduced to 3.5 seconds, **once again matching other shields.** The amount of mana restored when Water Shield procs has been reduced by 50%
Musze jeszcze dodatkowo sprawdzic zmiane z 4.0.6 na 4.1
Earth Shield healing done by Restoration shaman has been reduced by 20%.
4.0.6 na 4.0.1 (mozliwe ze u nas taka redukcja nie dziala, nie wiem, potzebny coeff :<)

**Comment by Kejmil** [comment]
wspaniale zrodlo, szkoda ze warmane nie jest oficjalnym serwerem blizzarda a autor tematu nie podal zrodel z ktorych te informacje wzial

**Comment by calladin** [comment]
Anyway, wszystko sie pokrywa z Twoim linkiem.

**Comment by BialyADI** [comment]
Pamiętam że na Sunwellu był podobny bug i ES miał 2,5s ICD.

Hmm bug poważny chyba że się gra z szmanem arenki ^^.

**Comment by BialyADI** [comment]
Jeszcze ciekawe jak jest z Lightning Shield tez powinien mieć 3,5s ICD, zresztą jak wszystkie ;D.

Daję jeszcze linki dla ułatwienia naprawy:
http://cata.openwow.com/spell=324 <- LS
http://cata.openwow.com/spell=52127 <- WS
http://cata.openwow.com/spell=974 <- ES

**Comment by Jenovas** [comment]
ES ma 3 sek cooldown ponieważ baza nie obsługuje liczb po przecinku.

**Comment by calladin** [comment]
Jezeli tak jest to najprawdopodobniej przez to, że baza nie obsluguje liczb po przecinku powstaje bug z "niewidzialnym gcd"

**Comment by Jenovas** [comment]
niewidzialnym gcd - to jest spowodowane przez "Lag Tolerance" po stronie klienta. Włącz i ustaw na 0, to powinno zmniejszyć częstotliwość występowania bugów z GCD.

**Comment by Jenovas** [comment]
Fixed in rev 4965
