### ISSUE TITLE
[EN][Hunter] Tier 12 4set Bonus vs. Aimed Shot

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#6341]
If you already started casting aimed shot and you get a 4set proc, when the cast finishes it won't consume the proc.
How it should work: even if you already started casting aimed shot and you get a proc, when the cast finishes it should consume the proc

**Comment by Kejmil** [comment]
http://www.wowhead.com/spell=99059/item-hunter-t12-4p-bonus
http://www.wowhead.com/spell=19434/aimed-shot

**Comment by Fapguy** [comment]
this will get fixed in 30 days or so, like all the other hunter stuff

**Comment by lqlq32** [comment]
I hope better than autoshot :D

**Comment by xolon** [comment]
This is working correctly now, i will close this.
