### ISSUE TITLE
No NPC's and no other players

### ISSUE THREAD

**Issue by jusdebaets** [Atlantiss/BugTracker#6342]
3 days ago I abandoned a quest, resulting in a bug which consists of me being al alone in the WOW-world. In other words, there are no NPC's and No other payers. I can still talk to guildmembers. And I can still see other mobs. I tried to relog etc but nothing seems to help.

**Comment by Luna-maria** [comment]
Try opening a ticket, your phase probably bugged out, gms can reset it :)
