### ISSUE TITLE
[EN][Quest][Uldamanl]The Platinum Discs

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6343]
http://www.wowhead.com/quest=2278/the-platinum-discs

Lore keeper not spawning quest cant be turn in and the next quest you auto receive even if you haven't finish the first quest

NPC: http://wowwiki.wikia.com/wiki/Lorekeeper_of_Norgannon

**Comment by Aviannaqt** [comment]
#1144
