### ISSUE TITLE
[PL][Item][Jaws Of Defeat]

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#6347]
http://cata.openwow.com/item=68926
Trinkiet nie działa prawidłowo.
U druida resto staki **_# nie wchodzą od instantów_** (reju/Lb/swift/Wild growth), załączają się TYLKO od spelli z cast time.
Dowód na to że powinny - http://www.wowhead.com/item=68926/jaws-of-defeat#comments
Z kolei u szamana staki wchodzą od tickow healing rain/riptide gdzie powinny tylko w momencie casta, tak jak jest opisane w tooltipie. "When CAST" spell nie" when HEAL"
Dodam że Wild Gworth powinien wbijać nam 5 ( z glyphem 6) staków ponieważ jest wrzucany (czyt. castrowany) jako hota na 5/6 osób. Inaczej niż w przypadku healing rain szamka gdzie jest castowany tylko raz- potem tickuje.
Nie wiem jak z innymi klasami bo nie mam jak sprawdzić jednak śmiem mniemać że tez nie jest tak jak powinno

**Comment by Kejmil** [comment]
zapomniales dodac ze trinket lubi nie zdjac buffa i ma sie pernamentnie zmniejszony koszt spelli

**Comment by Beatit** [comment]
+1 Kejmil
o dziwo tego nikt nie zgłasza :/

**Comment by Reversion** [comment]
Gdyby mi się to przytrafiło pewnie bym o tym wspomniał. W srodę go wydropiłem za wiele z nim nie porajdowałem z racji braku proca.

**Comment by Jenovas** [comment]
Fixed in rev 5075
