### ISSUE TITLE
New Warlock Imp Unresponsive

### ISSUE THREAD

**Issue by Paoni** [Atlantiss/BugTracker#6358]
Created a Worgen Warlock that is now at lvl 6. Imp became unresponsive at some point after character changed from human to Worgen.  The imp can be summoned, but does not follow my character. It does not attack...nothing.  It remains in the same spot, and if I get too far away from it, it disappears.  When I summon the imp again, it has a new name and does the same thing...nothing.  Please help.  :( I am unable to play my character like this.

**Comment by Glare** [comment]
Pre 10lvl Imp very often(always?) bugs out. Just reach lvl 10 and learn all new skills which include Demon Control or something like that.

**Comment by Aviannaqt** [comment]
read bt rules
