### ISSUE TITLE
[EN][Mage] Mirror Image from bonus T12 set interrupts spell casting

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#6361]
## What's wrong?
When T12 2/5 bonus set procs,if you're casting anything (Fireball,Arcane Blast,etc...),you will get interrupted (Link of the spell: http://cata-shoot.tauri.hu/?spell=99061 )

## How it should work?
When the Mirror Image is summoned, spell casting of any kind shouldn't be interrupted

**Comment by anxanas** [comment]
"Spawning Mirror Image should no longer interrupt cast" Supposed to be fixed in rev 4889

**Comment by Aldergar** [comment]
It isn't,still interrupting

**Comment by anxanas** [comment]
If it isnt still interrupting, close the topic

**Comment by Kejmil** [comment]
@Aviannaqt close this

**Comment by Aldergar** [comment]
It is interrupting still,don't close it rofl

**Comment by Aldergar** [comment]
Open again,it was a misunderstanding of my comment

**Comment by Kejmil** [comment]
i just tested it and images never interupted my casting

**Comment by Aldergar** [comment]
It does on my mage, It's a worgen.
