### ISSUE TITLE
[EN][Firelands] Flickering items have wrong stats.

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6364]
Hello.
Today we had drop from Alysrazor leather bracers with random stats. Stats are wrong.
They have wrong values of the stats. Wowhead comments says:
...of the Windstorm
+340 Stamina
+227 Agility
+151 Crit Rating
+151 Mastery Rating
http://www.wowhead.com/item=70735/flickering-wristbands#comments:id=1457890
We have **LESS** stats.
+340 Stamina
+211 Agility
+144 Crit
+144 Mastery
![wowscrnshot_021216_212115](https://cloud.githubusercontent.com/assets/2743430/13020022/0d915cf8-d1e4-11e5-981a-d1271738ce9b.jpg)

**Comment by Wolffenstein** [comment]
Enchantment data is taken directly from the client. If the stats don't match, it means that Blizzard must have changed them in between 4.2 and 4.3.4.

**Comment by tnarf** [comment]
Based on link1 we can suppose that on the CLIENT side is ONLY FORMULA for those stats.
In link 2 is formula for itemlinks (becous cataclysm we should delete 1 jewel position)

When on position suffixId we place correct suffixID (witch "-") we get link to item with +0 stats.
When in obtained link we chenge value on position uniqueId (next value) we get linkt to item with +X stats when X is bassed on this changed value.

So when we want obtain Flickering Wristbands of the Windflurry we must set:
suffixID: -135 (from link)
uniqueId: 432 (calculated based on wowhed stats)
And we get item witch stats like on wowhed.

But droped items have another stats.
If we check droped item link (forexample by script_1) we get another value on position suffixID (example -289 instead -135)

So in my opinion bug is on SERVER SIDE in place where item receives suffixID (random enchant id).
please:
change status to OPEN (wtihout any dev respound i open new thread in tuesdaym becous you can not read closed threads.

link1: http://wow.gamepedia.com/ItemRandomSuffix
link2: http://wowwiki.wikia.com/wiki/ItemString

script_1 (for item in 1st slot in bags):
/run link = GetContainerItemLink(0, 1);printable = gsub(link, "\124", "\124\124");ChatFrame1:AddMessage("Here's what it really looks like: \"" .. printable .. "\"");

link_without_stats: 
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:0:0:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");

link_with_0_stats:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:-135:0:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");

link_with_correct_stats: 
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:-135:432:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");

link_with_actual_stats: 
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:-289:432:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");
