### ISSUE TITLE
[EN][Mage] T12 Set Bonus

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#6368]
The 2P bonus is still interrupting spell cast upon mirror spawn as of rev 4889.

Would be nice if you stopped closing tickets and branding the issues as "solved" before they actually are #6330, #6076, #6361.

![wowscrnshot_021216_232401](https://cloud.githubusercontent.com/assets/16211262/13023377/3acc9d08-d1e0-11e5-8523-d01c6b66b642.jpg)

**Comment by Kejmil** [comment]
this screen proofs absolutely nothing you know? :D

**Comment by Kejmil** [comment]
on zori core with rev 4889 it works man ( ͡° ͜ʖ ͡°)

**Comment by ponpontos** [comment]
@Kejmil I have no fucking idea of what you're talking about, sever is currently in rev4889 and it's still interrupting cast every single time.

**Comment by Aldergar** [comment]
I have the same problem,but issues keeps getting closed for no reason.

**Comment by Kejmil** [comment]
reason was dev who was fixing this asked me to check this and i checked it... on his test server because i don't have this set on main (t11hc >>> t12norm), where for some reason with the same rev it was working while on ats is not
it is fixed there already, wait for rev including this

**Comment by ponpontos** [comment]
Why would you tell people that it is working if you haven't tested it in the actual server though?? Jesus Christ.

**Comment by Aldergar** [comment]
I quote ponpontos, it isn't working on the live server,so stop going around telling false claims.

**Comment by ponpontos** [comment]
Seems to be working properly finally, closing it now.
