### ISSUE TITLE
[EN][Spell][Mage] Mirror Image

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#6375]
didnt anyone notice that the clones from the spell mirror image are instantly distinguished from the mage, making the spell usless in pvp. some screens below:
[http://imgur.com/a/57vIH](http://imgur.com/a/57vIH)
the issue seems to be that the enemy player sees the clones as pets , ordinary pets not even as  mage class npc, just pets
[http://imgur.com/a/H1v5W](http://imgur.com/a/H1v5W)
here we can see that the clones spawned, where seen as pets/enemy npc and after the mage started casting they targeted me and my unit frames recognized them as mages but still they where *colored in a difrent color than the orginal mage

ps, if i reacall correctly clones should have the same buffs as the orginal mage when they spawn, all of them even from other classes

**Comment by kadi2** [comment]
You have to post some proof and proper links

**Comment by Jenovas** [comment]
https://www.youtube.com/watch?v=MBVndy3dSFo
Closing
