### ISSUE TITLE
[en][quest][southern barrens] Lifting the siege

### ISSUE THREAD

**Issue by Ambiorixa** [Atlantiss/BugTracker#6377]
http://www.wowhead.com/quest=24948/lifting-the-siege

It is not possible to throw a torch at a Rageroar blade thrower.
I have tryed every angle and distance.

**Comment by Arthurice47** [comment]
Bumped. I was literally standing underneath the place where the Torch lands, I throw the Torch, it lands in mid air, and nothing happens...

**Comment by Hallieth** [comment]
:(:( yep, not working

**Comment by Bildo** [comment]
fixed
