### ISSUE TITLE
[EN][Instance][Lunar Festival] Stratholme

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#6379]
It's impossible to go inside. A message apperars: "This instance is closed". It blocks the last Elder needed for the Lunar Festival title.

**Comment by Glare** [comment]
http://community.atlantiss.eu/index.php?/topic/8464-stratholme-closed/

**Comment by Articuno** [comment]
This explains a lot, I hope it will get fixed before the event ends.
