### ISSUE TITLE
[EN][PL][Quest][Azuremyst Isle] Totem of Vark

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#6383]
**[EN]**
Quest: http://www.wowhead.com/quest=9542/totem-of-vark

After completing quest: Totem of Yor (http://www.wowhead.com/quest=9541/totem-of-yor), I was unable to pick following quest. Exclamation mark wouldn't appear.
**For draenei this quest works as it should**. I tried to pick it up as night elf Death Knight.

![wowscrnshot_021316_134942](https://cloud.githubusercontent.com/assets/7345784/13027703/ddbf824a-d259-11e5-808f-0d1625c81ccf.jpg)

---

**[PL]**
Quest: http://www.wowhead.com/quest=9542/totem-of-vark

Po wykonaniu zadania: Totem of Yor  (http://www.wowhead.com/quest=9541/totem-of-yor), nie byłem w stanie wziąć następnego questu. Wykrzyknik nie pojawił się.
**Dla draenei quest działa prawidłowo**. Próbowałem wziąć zadanie jako nocny elf Death Knight.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12528-6383questazuremyst-isle-totem-of-vark/

**Comment by TheRealestMcCoy** [comment]
This quest still does not work.

**Comment by TheRealestMcCoy** [comment]
rev. 5295 Author: Bildo :: 2017-01-22 16:36

fixed Totem of Vark by Navedonar
