### ISSUE TITLE
[EN][NPC] Dungar Longdrink (stormwind fly master)

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#6384]
http://www.wowhead.com/npc=352/
He has too low health (96267) compared to other fly masters (~232k) and gryphons that he calls (http://www.wowhead.com/npc=9526) has incredibly low health (3hp at lvl 85)

**Comment by user1011** [comment]
Where did you find that he has too low health?

**Comment by user1011** [comment]
Dungar Longdrink's health isn't too low.

**Comment by user1011** [comment]
Fix posted on the forums.
