### ISSUE TITLE
[PL][Quest][Uldum] Gnomebliteration

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#6390]
http://www.wowhead.com/quest=27779
Nie można skakać kulką więc nie można się wydostać z tego statku

**Comment by Luna-maria** [comment]
took a few tries but I got over it not so long ago

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/4754

**Comment by DevilDesire7** [comment]
It's bugged again. The gnomes cannot be killed with the ball.
