### ISSUE TITLE
[EN][NPC Vendor] So many missing items

### ISSUE THREAD

**Issue by tosiaplpl** [Atlantiss/BugTracker#6393]
Hello
Why at Justice Quarermaster vendor's missing so many items for example Flamebinder Bracers ?
Is it bug or administration intentionally deleted items ?
With regards

**Comment by stanq87** [comment]
if these should be at that vendor with content 4,2  with prices from 4,3, and they are not there, it's a bug, but nobody seems to care to add an item or to to the npc or adjust the prices o be correct in some cases

**Comment by Luna-maria** [comment]
4.3 items aren't at the vendors yet because 4.3 content isn't available. 
We're basically using a 4.3.4 client, but on patch 4.2

**Comment by stanq87** [comment]
yes, but sill there are items miing and others have wrong prices

**Comment by Luna-maria** [comment]
well, I assume you're gonna have to say which is missing and which prices are wrong or they might close it

**Comment by stanq87** [comment]
[https://github.com/Atlantiss/BugTracker/issues/5842](https://github.com/Atlantiss/BugTracker/issues/5842)

[https://github.com/Atlantiss/BugTracker/issues/6129](https://github.com/Atlantiss/BugTracker/issues/6129)

**Comment by tosiaplpl** [comment]
For example i wanted to buy in Orgrimmar at Gunra Quartermaster: Flamebinder Bracers, Necklace of Smoke Signals, Dark Phoenix Tunic, Dark Phoenix Gloves, Dark Phoenix Legguards, Splintered Brimstone Seal, Morningstar Shard and there's any of it
Luna-maria u said u have these braicers, are u from SW ? How did u get that ?

**Comment by Anhaeyn** [comment]
I have Morningstar Shard, Necklace of Smoke Signals and Flamebinder Bracers. I bought them some time ago at Valorous Quartermaster, not Justice one.

**Comment by Luna-maria** [comment]
I'm Alliance yea

**Comment by tosiaplpl** [comment]
There's shoudn't be Morningstar Shard for 700JP, Necklace of Smoke Singals for 1250JP, Flamebinder Bracers for 1250JP ?
And for example Dark Phoenix Spaulders shoudn't be for Mantle of the Fiery Vanquisher at Justice Quartermaster and the heroic version of Dark Phoenix Spaulders at Valorous Quartermaster for Shoulders of the Fiery Vanquisher ?

**Comment by RandomPickNewb** [comment]
You do realise that you are talking about ilvl 378 items which at the time retail was on the 4.2 client were sold for valor points.We are using the 4.3 client BUT we are on 4.2 CONTENT so those 378 ilvl items are going to be sold for valor points.I really hope that you understand now..

**Comment by Anhaeyn** [comment]
^^ This ^^

**Comment by stanq87** [comment]
what about #5842 #6129

**Comment by Luna-maria** [comment]
those are still open so just wait I guess
