### ISSUE TITLE
[EN][Hunter][Pet][DR] Diminishing Returns 

### ISSUE THREAD

**Issue by Cholee** [Atlantiss/BugTracker#6396]
[Pin] (Pet)	 -Controlled Root
[Charge] (Pet) - None

these two ability do not have to share diminishing returns, but they do...
Crab is one of best PVP pet and with this bug it is "unplayble"  ATM..

**Comment by blinkmaster** [comment]
Proof

**Comment by Jenovas** [comment]
Please create a new issue with proof.
