### ISSUE TITLE
[EN][Reputation] Steamwheedle Cartel

### ISSUE THREAD

**Issue by xjf7** [Atlantiss/BugTracker#6399]
[Southsea Strongarms](http://www.wowhead.com/npc=40635/southsea-strongarm) and [Southsea Musketeers](http://www.wowhead.com/npc=40632/southsea-musketeer) are supposed to give 5 reputation with [Gadgetzan](http://www.wowhead.com/faction=369/gadgetzan) and 3 with other Goblin factions, but they don't. Besides, there are mobs in Tanaris which have a similar bug: [Wastewander Darkcasters](http://www.wowhead.com/npc=44613/wastewander-darkcaster) (supposed to give 5 rep with Gadgetzan (untill Honored), 2 with [Booty Bay](http://www.wowhead.com/faction=21/booty-bay) and 3 with [Ratcher](http://www.wowhead.com/faction=470/ratchet) and [Everlook](http://www.wowhead.com/faction=577/everlook) (untill Revered)) and [Wastewander Survivalists](http://www.wowhead.com/npc=44611/wastewander-survivalist) (same amount of rep, but it stops at Friendly).

**Comment by agardosh** [comment]
Bump, renders the 50 reputation achievement pretty much undoable, and the insane achievement undoable. Only mobs currently giving rep correctly for the Steamwheedle Cartel factions are the venture co mobs in Venture Bay, Grizzly Hills.
