### ISSUE TITLE
Super Sticky, quest in Un'Goro

### ISSUE THREAD

**Issue by adicolor** [Atlantiss/BugTracker#6402]
Hello! I must collect 8 super sticky tar, I killed more than 20 Tar Lords and it didn't drop even 1 quest item! The other thing is that usually when you enter the tar, it slows your speed by 50-60% I think, tried to search for the debuff's name but couldn't find it.

**Comment by Anhaeyn** [comment]
It's not item which drops.. Use quest item on corpse of tar lord.
