### ISSUE TITLE
[PL[TALENT][BLESSED LIFE][PURSUIT OF JUSTICE][PALLADIN]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6405]
Obydwa talenty powinnny miec wspolny icd 8sec, nie maja.

Pursuit of Justice now has an 8-second internal cooldown, shared with Blessed Life.

http://us.battle.net/wow/en/blog/1214741/patch-403a-the-shattering-of-azeroth-now-live-11-23-2010

**Comment by BialyADI** [comment]
http://cata.openwow.com/spell=26023
http://cata.openwow.com/spell=31829

**Comment by lamaATS** [comment]
Fixed in rev. 5208
