### ISSUE TITLE
[PL][Drop][Instance] Blackwing Lair

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#6406]
http://www.wowhead.com/zone=2677
Z bossów dropi od 1-6 itemów a zawsze powinno dropić
Z pierwszy 3 po 3 itemy
Z następnych 3 po 2
Z Chromagussa 4
Z Nefka 10-12(Zawsze head i sakiewka z gemami reszta to ity)

http://www.wowhead.com/npc=14401 zawsze powinien dropić http://www.wowhead.com/item=44956
"Krixix will only drop one book per kill."

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11893-6406-blackwing-lair-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
