### ISSUE TITLE
[PL][Quest]"Until Death Do Us Part"

### ISSUE THREAD

**Issue by Danelar** [Atlantiss/BugTracker#641]
Nie można użyć Clarice's Pendant ( http://www.wowhead.com/item=6145 )  na Yuriv's Tombstone                                   ( http://www.wowhead.com/quest=264#screenshots:id=17963 ) po interakcji pojawia się słynne "Greetings <name>";/ i nic 

Link: http://www.wowhead.com/quest=264/until-death-do-us-part

**Comment by Navedonar** [comment]
Poprawka czeka na wgranie

**Comment by Bildo** [comment]
rev. 4353 by Navedonar

**Comment by Danelar** [comment]
Super :>
