### ISSUE TITLE
[PL][Mage] Combustion - Tick/Resi Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6410]
Jak jest:
Dmg z Combustion nie jest redukowane w PvP przez Resi, też nie bierze pod uwagę zredukowanego przez Resi Dmg z pierwotnych Dot(Ignite, Living Bomb, Pyroblast Dot).
Ogólnie Dmg z Combustion zadaje aktualnie Dmg jak by target całkowicie nie miał Resi ani dla "zwykłych Dot"(Ignite, Living Bomb, Pyroblast Dot), ani dla samego Combustion.
Combustion też dziwnie Tiskuje przy jednej walce Mag dał mi Combustion które tickneło prawie 50 razy.
Prawdopodobnie związek z tym zgłoszeniem: https://github.com/Atlantiss/BugTracker/issues/6284.

Jak powinno być:
Combustion przynajmniej powinien brać pod uwagę zredukowane Dmg przez Resi z Dot z których powstaje(Ignite, Living Bomb, Pyroblast Dot).

Warto poczytać wszystko tu jest wyjaśnione jak BlizzLike to powinno działać:
http://blues.wowraider.net/blue/us2/2913052504/%5BBug%5D-Combustion-Hotfix-Repercussion?1312393473
http://blues.wowraider.net/blue/us2/2957535757/Combustion-Interacting-Improperly-W-Resil?1312414484

Dowód jak teraz u nas działa Combustion i 47 tickow z jednego Comb:
![wowscrnshot_021516_014323](https://cloud.githubusercontent.com/assets/5780624/13037983/7b6668fa-d38c-11e5-85c2-8fe7993ab681.jpg)

Jak to przetestować:
Dać jedna Dote na kogoś z Resi Np. Living Bomb i dać Combustion.
Potem dać to samo Living Bomb i Combustion na kogoś bez Resi i można zaobserwować ze Dmg z Combustion jest dokładnie taki sam, natomiast Dmg z Living Bomb oczywiście większy bo teraz nasz target nie ma Resi.
Co oznacza że w żaden sposób Dmg z Comb nie jest redukowane, czy to przez redukcje Living Bomb w tym przykładnie, czy to przez samą redukcje Combustion.

Co do Ticków nie wiem co trzeba odpalić by zrobić 50 ticków z Combustion, kilka razy już to widziałem na Arenie/Bg.

**Comment by kadi2** [comment]
Potwierdzam, na ta chwile przetestowane z living bombą. Damage combustion jest identyczny na targecie z resil/bez resil.

**Comment by calladin** [comment]
Combust najprawdopodobniej dziala poprawnie.
"No. It used to, but they changed it. It's the same idea of the old version of sweeping strikes, where it would double damage modifiers.** So only the dots that roll into combust are affected by resil**, it doesn't get doubly hit. "
http://us.battle.net/wow/en/forum/topic/388192475

**Comment by blinkmaster** [comment]
Ogólnie to combust nie powinien się double dipowac z resi ale z tego co rozumiem z tego reportu to niezależnie po ile bije sota która jest przez resi redukowana to combust i tak bije tyle samo co już jest bugiem

**Comment by calladin** [comment]
Czyli Combust bez wrzucanych dot powinien obejmowac redukcje z resila? A jak sa wrzucone doty (ktore juz maja redukcje z resi, a na ich dmgu opiera sie dmg combusta) combust powinien dodatkowo otrzymac redukcje?? To bedzie juz podowojnie naliczona redukcja, moze redukcja powinna np dzialac tylko na base dmg combusta? Dunno.

**Comment by blinkmaster** [comment]
A co do ilości tickow to no comment 😅 nawet nie wiem jak do tego dochodzi ale jak widać różne kwiatki są.

**Comment by calladin** [comment]
Wydaje mi sie, ze base dmg combusta nie obejmuje resi, moze w tym tkwi blad, ale nie jestem pewien an 100% w jaki sposob powinien dzialac combust:
A) Redukcja przez resila dmgu z dot skladajacych sie na Combu
B) Redukcja przez resila dmgu z dot skladajacych sie na Combu+ dodatkowa redukcja combu z resi (prawdopodobnie nie tak ma dzialac)
C) Redukcja przez resila dmgu z dot skladajacych sie na Combu + uwzglednienie resilence przy Base Dmgu combusta ( prawdopodobnie o to chodzi) QQ

**Comment by BialyADI** [comment]
Wyszystko jest opisane w linkach ktorych dalem jak powinno dzialac.
Teraz mag daje combustion i zabija na miejscu, major bug.

**Comment by calladin** [comment]
Combust przy nalozonych dotach(lb+ignity)nie powinien otrzymywac dodatkowej redukcji, bo jego dmg bierze sie juz ze zredukowanych cyferek.

**Comment by BialyADI** [comment]
Calladin gadasz głupoty, ale w jednym masz racje tak sa 2 Bugi.
Combustion Całkowicie omija Resi i źle się skaluje z Haste, bo mag na Time Warp i chuj wie czym jeszcze robi 50 Tickow Combustiona.

**Comment by calladin** [comment]
Pls, zapomniales wspomniec ze dota z combustion powinna robic duzo wiekszy dmg niz 1,8k, jezeli target ma na sobie 3 rozne doty?

**Comment by Jenovas** [comment]
Proszę aby osoby które NIE WIEDZĄ jak ma działać dany spell nie robiły bałaganu.
Tego zgłoszenia nie da się czytać. Mówicie o 10 rzeczach na raz, w jednym poście mówicie X, w drugim Y w trzecim Z i tak naprawdę nic już nie wiadomo. Jeżeli nie wiesz to nie pisz. Nie ma wydaje mi się, nie ma myślę. Doczytać, sprawdzić a potem pisać bo jest jeden wielki bałagan. 

PODSUMOWANIE BUGA:
Combustion omija w 100% resi. Cel z 0 resi i cel z 4000 resi dostaje taki sam DMG.
Zostanie dodane do Combustion to że powinien być redukowany przez resi.

**Comment by BialyADI** [comment]
Calladin wypisuje jakieś głupoty z znakiem i jeszcze się pyta czy dobrze pisze no Miszcz :D.

Jenovas przeczytaj te 2 linki co dałem w zgłoszeniu tam jest to ładnie opisane jak powinno być redukowane Combustion przez Resi.
Dodatkowo Comustion zle się jest skalowane z  Haste Mag moze zrobić tym horendalną ilośc Dmg bo pojedyńcze Combustion może ticnkać nawet 50 razy.
https://github.com/Atlantiss/BugTracker/issues/6284 tutaj jest to zgłoszone.

**Comment by calladin** [comment]
https://www.youtube.com/watch?v=8enjMXs88ww Zobaczcie jakie cyferki robi mage...

**Comment by BialyADI** [comment]
Głowa paratetu nie rozwalisz dlatego napisze tak:
Bardzo fajny filmik, serio lubię oglądać takie PvP kompilacje, ale lepsze są składanki samych aren :).

**Comment by kadi2** [comment]
@jenovas double-dipp ignite na combustion inc?

**Comment by Jenovas** [comment]
Tak kadi2

**Comment by Myrcool** [comment]
Oj @calladin nie ładnie mnie uwzględnić :-1: Testowaliśmy dzisiaj zarówno resilience jak i Combustion i wyniki były po prostu dziwne. Damage z Combustion przy 38% resilience był WIĘKSZY niż na targecie z 0 resilience - mimo, że w obu wypadkach odpalony był tylko living bomb przez tego samego maga w tym samym gearze i bez żadnych proców. Z drugiej strony nie jest tak, że Combustion powinno absolutnie ignorować resilience. Global miał swój bug, w którym combustion było dwa razy redukowane po użyciu. Nie zmienia to jednak faktu, że zarówno doty jak i sam dot z Combustion powinny być raz redukowane przez resilience.

Więcej na ten temat można poczytać tutaj. Wypowiedź R1 gracza w tamtym czasie. 

http://us.battle.net/wow/en/forum/topic/2957165884

Cytując:

> On the exact same player now wearing 4001 resilience - 39.84% damage reduction - my Combustion ticked for 2668.
> 
> With 39.84% damage reduction, a player would expect to take 100.00% - 39.84% = 61.16% damage from an ability.
> 
> Our expected damage on Combustion ticks would be 5973 * 0.6116 = ~3653 damage.
> 
> Our actual damage on Combustion ticks was 2668.

Bug polegał na tym, że combustion było nerfione raz a potem znowu drugi raz. Wciąż jednak autor tego postu zdaje sobie sprawę, że combustion powinno raz być redukowane przez resilience - tj. zadawać 3653 dmg w tym przypadku. Więc nie Calladin, Combustion nie powinno wchodzić z true damage.

**Comment by Zhalox123** [comment]
Combustion extra ticks should come from 5% 1st then each 10% after = New extra combustion tick.Compared the current state of combustion vs retail its still not close to its original by so doing slightly less dmg than it should normaly.But ye the combustion ticks should be checked and fixed but the current state of combustion still remains lowered on dmg.

**Comment by Zhalox123** [comment]
Also keep in mind in the conversation of your link Myrcool http://us.battle.net/wow/en/forum/topic/2957165884 u can see that he writed 
Combustion isn't taking resilience into account twice, it's only taking it into account once. The dots themselves are taking it into account the second time. The net effect is twice, but apparently only with Ignite. Careful that your complaining doesn't result it in it being factored into every other dot as well. Frankly I would have expected your test results to yield 2174 damage per tick combustion, but I fully agree with you that in principal Combustion itself should *ignore* resilience completely, as the dots it bases its damage on have already factored it in. Blizzard however said otherwise in one thread, while suggesting there was an issue with ignite that would be fixed in another. Mixed messages imo.

**Comment by Zhalox123** [comment]
Just found this note.
Combustion damage from Ignite is no longer penalized by Resilience more than once, nor can it gain double benefit from Flashburn (mastery).
THIS IS FROM 4.2 ORIGNAL WOW PATCHNOTES maybe this is the issue also about the combustion dmg but still dont know how its affecting so many ticks suddenly.
Link of patchnotes http://us.battle.net/wow/en/blog/3019413#blog

**Comment by Myrcool** [comment]
@Zhalox123 I already edited my post. Truth is we really can't go back in time and simply check it on retail. In current state combustion either ignores resilience all together or something is really off because it deals more damage to resilience geared players than it does to mobs/naked players. I will do serious testing of combustion and effects it has on different dots, separated and combined - same way I did with resilience. This whole thread is rushed and we can't really pinpoint the issue - clearly we don't want to make things worse. Would be nice if devs fixed resilience first because right now testing specific spells on pvp geared targets is pointless.

**Comment by BialyADI** [comment]
Ignite and Resi works as it should, ignite ignore Resi.

**Comment by blinkmaster** [comment]
http://us.battle.net/wow/en/forum/topic/3530366099
Ostatni komentarz.
Podsumowując - resi działac powinno na lb i pyro.
Nie powinno działać na ignite - bo spell z którego powstaje juz przelicza się z resi, było kiedyś zgłaszane. 
Oraz combust nie powinien być przez resi affectowany gdyż wszystkie dotychczasowe wchodzące w skład juz to robią i poprawił to sam blizz.
Co do reszty to widać ewidentnie gdzieś bug ale gdzie to nie wiem

**Comment by BialyADI** [comment]
Przecież jest mnóstwo tematów gdzie ludzie piszą że Combustion jest redukowane przez Resi i tak powinno być.

**Comment by Zhalox123** [comment]
I like the spell getting fixed I dont have any problem vs it but atlantiss rly needs to fix the ability correctly  every1 knows how retarded combustion was back in cataclysmic 4.3 season still hope to soon get it fixed.

**Comment by blinkmaster** [comment]
http://www.arenajunkies.com/topic/206995-combustion-double-dips-resilience/page__st__20
Jedne z ostatnich postów. 
Powoli zaczyna mnie męczyć ciągle wyszukiwanie tych samych dowodów do zgłoszeń nt tego, że combust ma się double dipowac z resi.

**Comment by ShockRW** [comment]
BUMP

**Comment by BialyADI** [comment]
Jest tu kto ^^?

**Comment by Jenovas** [comment]
Fixed in rev 4904
