### ISSUE TITLE
[EN][Quest] Get Kraken!

### ISSUE THREAD

**Issue by Snacky1** [Atlantiss/BugTracker#6411]
http://www.wowhead.com/quest=14108/get-kraken

You don't get credit for throwing the spears at the kraken. Every spear you throw you should get credit for.

**Comment by NatsumeLily** [comment]
#5864   #889
You can still complete it...When you throw 1 spear visually stop and reposition yourself. When you throw 2 visually, wait for the crazy flying one to hit and get credit. You can complete this in 30 seconds.

(Don't spam them)

**Comment by Oxyntes** [comment]
Two spears are thrown at the Kraken at the same time. As Lily said, you need to wait for the second spear (the one with the strange path) to hit Kraken and maybe a second or 2 after that for actually getting the credit for the hit, you must not throw the next spear at the Kraken.

However, you must not be to close to the Kraken or to far away as then the second spear is not thrown at the Kraken and, of course, you can not get the credit for hitting it. So, if only one spear is thrown at the Kraken, you are in the wrong position and need to move. 
Once you find the right position for throwing the spear, the quest is easily finished and takes a little time to complete.
