### ISSUE TITLE
[en] [ability] [rogue] Tricks of the Trade going on CD when it shouldn't 

### ISSUE THREAD

**Issue by RhythmOfficial** [Atlantiss/BugTracker#6414]
Tricks of the Trade is a ability with a 30 second cooldown it applies a buff on that person for 30 seconds and gives that person increased damage for 6 seconds and gives your threat to that player that gains ToTT.
The bug here is if the ToTT is not initiated that means if it hasn't gone off, no attacks were made there was no 6 second ToTT buff given to you and the player the cooldown of ToTT should reset!

It should only go on a 30 sec CD when its used not when u applied the buff and then you didn't enter combat and did not receive the buff this should reset and you should be able to cast another ToTT right away.
However if you right click on ur buff (you remove your buff) This should not happen it should only happen if there was no combat action.

**Comment by Jenovas** [comment]
Any proof? Please give us some videos / articles talking about this.

**Comment by RhythmOfficial** [comment]
@Jenovas 

The same effect applies to Soul Swap, if the buff falls off or you cancel aura it the ability should NOT go on cooldown.

http://www.arenajunkies.com/topic/169967-soul-swap-cancel-aura/

**Comment by tnarf** [comment]
maybe im blind but i don't see anything about rogue in this link

**Comment by Jenovas** [comment]
Rhythm show me proof for this spell not proof how soul swap works.

**Comment by RhythmOfficial** [comment]
IT IS THE EXACT SAME MECHANIC AS TOTT omg, do you even read what I am typing holy cow.

**Comment by Jenovas** [comment]
How do you know it's the same mechanic? Where does it say "TOTT WORKS LIKE SOUL SWAP".
Closing. Please make a proper report with links to the spell and links to proof your statement.
