### ISSUE TITLE
[PL][Core]Nieprawidłowe (?) przeliczniki z resilience.

### ISSUE THREAD

**Issue by Myrcool** [Atlantiss/BugTracker#6415]
Witam, dzisiaj przy okazji testowania Combustion zauważyłem dziwną anomalię w przeliczaniu resilience. Resilience redukuje damage nieproporcjonalnie do wyświetlanej w zakładce wartości. 

Przy 0% resilience i braku resistów wszystko działa jak należy, 5 ticków po 1301 damage dające łączną sumę 6505 dmg co mniej więcej zgadza się z tooltipem (6475 dmg w ciagu 13.01 sekundy). Ten sam damage aplikuje na mobach, które nie mają resil i resistów. 

http://i.imgur.com/6h0NH3M.jpg (Damage na moim paladynie przy 0% resil)

http://i.imgur.com/iSqEBsf.jpg (Ten sam damage w tym samym gearze na mobie bez resil i resistach)

http://i.imgur.com/LbppjDv.jpg (Tooltip living bomb pokazujący mniej więcej ten sam damage, przypuszczalnie zwiększony przez jakiś talent, który jest niepokazywany w tooltipie) 

Schody zaczynają się przy nałożeniu gearu z resilience:

http://i.imgur.com/AlNhq72.jpg (Dmg aplikowany przez tego samego maga w tym samym gearze przy 19.96% resilience)

19.96% resilience powinno redukować 259.6796 dmg z 1301 dmg bez resilience co daje przybliżony wynik 1040.  Otrzymuje natomiast 1013 dmg co daje zawyżoną 22.136817832436588 procentową redukcję damage. 

Potem jest już tylko coraz gorzej:

http://i.imgur.com/7zxmweE.jpg (Ten sam mag, ten sam gear, tym razem ja w gearze z 29.96% resilience)

29.96% resilience powinno redukować 389.7796 dmg z 1301 dmg bez resilience co daje przybliżony wynik 911. Otrzymuje natomiast 840 dmg co daje zawyżoną 35.43428132205995 procentową redukcję damage.

Im więcej resilience tym bardziej odchylony od prawidłowości wynik:

http://i.imgur.com/jrjaGo9.jpg (Ten sam mag, ten sam gear, tym razem już 38.15% resilience)

38.15% resilience powinno redukować 496.3315 dmg z 1301 dmg bez resilience co daje przybliżony wynik 805. Otrzymuje natomiast 680 dmg co daje zawyżoną 47.732513451191394 procentową redukcję damage.

Żeby upewnić się, że nie jest to wina samego maga poprosiłem Calladina aby przetestować resilience na moim judgemencie - który jak wiemy zadaje holy damage a ten nie jest redukowany przez armor.

http://i.imgur.com/PyqgtuT.jpg (Damage na Imperiusie bez żadnych proców itp w 0 resilience gearze. Dodaje przy okazji, że holy damage działa i ignoruje fizyczną redukcje z pancerza ponieważ wielokrotnie zadałem ten sam damage tj. 525 na critterach i mobach) 

http://i.imgur.com/fSUxt3G.jpg (Imperius w jego full pvp gearze dającym mu 39.86% redukcji)

http://i.imgur.com/boCVyAk.jpg (Imperius otrzymujący dmg z judgementa przy 39.86% redukcji - posiadam ten sam gear itp. brak proców) 

Jak widać w screenach powyżej 39.86% resilience powinno redukować 209.26500000000001 dmg z 525 dmg bez resilience co daje przybliżony wynik 316. Calladin otrzymuje natomiast 260 holy dmg co daje zawyżoną 50.476190476190474 procentową redukcję damage. 

Wniosek jest dość oczywisty: 

- Gracze w conquest gearze mogą otrzymywać nawet do 15% darmowej redukcji. 
- Niszczy to balans pvp sprawiając, że double dps teamy mają znacznie większy problem z zabiciem healerów.
- Cały model resilience jest do revampu 

Ode mnie tyle. Nie mam dokładnie pojęcia czemu tak się dzieje, ale jednak coś jest nie tak i należy to naprawić asap ponieważ w obecnym momencie pvp jest absolutnie złamane.

**Comment by xmesaj2** [comment]
może jest ta sama stara formuła co na armory widać
Resilience: 4061 (+51.32%)  - na armory
Resilience: 4061 (+40.30%)  - w grze

**Comment by Myrcool** [comment]
Cóż czytając post na http://www.skill-capped.com/forums/showthread.php?15459-Understanding-Resilience-Patch-4.3 idzie dość łatwo wywnioskować, że 100 resil to około 1% damage redukcji co by mniej więcej się pokrywało z tym co mamy teraz w grze (4k resil to około 40% dmg redukcji po czym następują dimishing returny). W takim razie formuła jest przestarzała i resil powinien dawać mniej redukcji.

**Comment by BialyADI** [comment]
Jeśli faktycznie jest Buged to może po naprawie w końcu arenki będą szybsze a nie po 30-40 min Dps/Heal vs Dps/Heal ehh.

**Comment by BialyADI** [comment]
s

**Comment by Jenovas** [comment]
Resi z tego co widzę działa jak z patcha 4.0.6.
W najbliższym czasie postaram się ogarnąć nowe przeliczniki które weszły w 4.3.4.

**Comment by BialyADI** [comment]
Plz dont forgot about Lock and Load https://github.com/Atlantiss/BugTracker/issues/6407 it is important too in PvP.
Thanks ^^.

**Comment by Myrcool** [comment]
@BialyADI Trinkety specjalnie ściągnąłem i mam na paladynie włączone wyświetlanie wrogich proców i buffów, których po prostu nie było. 

@Jenovas Dzięki za szybką odpowiedź, to dość ważny fix dla graczy pvp. 

Myślę, że spokojnie da się ogarnąć serwer tylko ludziom się nie chce testować.

**Comment by Jenovas** [comment]
Fixed in rev 4896

**Comment by blinkmaster** [comment]
Cool, make sure it will also affect pets and gurdians, cheers
