### ISSUE TITLE
Stormwind portals

### ISSUE THREAD

**Issue by iWubsy** [Atlantiss/BugTracker#6419]
So after finally finishing every single quest in Mount Hyjal, I went back to stormwind, only to realize I forgot to buy something from a merchant, I went over to the portals, and found it wasn't there. Everything in Hyjal is completed, and it's tedious, is there a fix for this?

**Comment by Myivo** [comment]
Complete quest chain with Alysra - http://www.wowhead.com/quest=25430/emerald-allies

**Comment by iWubsy** [comment]
I already have

**Comment by Bildo** [comment]
bt rules
