### ISSUE TITLE
[EN][Event][Love is in the Air] Love Rocket / Silver Shafted Arrow.

### ISSUE THREAD

**Issue by mean931** [Atlantiss/BugTracker#6420]
Players should be able to buy a stack of 5 love rockets or 5 shifted arrows in exchange for 5 love tokens, while right now a player can only buy 1 love rocket or shifted arrow per 5 tokens; 

http://www.wowhead.com/npc=37674/lovely-merchant
http://www.wowhead.com/item=34258/love-rocket#comments
http://www.wowhead.com/item=22200/silver-shafted-arrow

**Comment by Larousene** [comment]
Confirmed, spending 50 love tokens instead of 10, to grant an achievment, is too high price

**Comment by Luna-maria** [comment]
same goes for handful of petals, should cost 2 tokens to receive 5 petals
http://www.wowhead.com/item=22218/handful-of-rose-petals

**Comment by Samineh** [comment]
Still bugged :rabbit:
