### ISSUE TITLE
[en][daily quest][tbc][Bomb Them Again!][Wrangle Some Aether Rays!]

### ISSUE THREAD

**Issue by magion342** [Atlantiss/BugTracker#6427]
Hello
2 days there is impossible to perform daily tasks faction ogrill'a http://www.wowhead.com/quest=11066/wrangle-more-aether-rays with this task does not include us lapanych mobs , mobs much appears as caught. With this task www.wowhead.com/quest=11023/bomb-them-again not include us destroyed Fel Cannonball Stacks . After that did not work achievement Blade 's Edge Bomberman .

**Comment by HUMBOL** [comment]
did it yesterday, works fine.
