### ISSUE TITLE
[EN][Prof][Skinning] unable to skinn if there is drop

### ISSUE THREAD

**Issue by Artaxin** [Atlantiss/BugTracker#6428]
Hi Team

Since yesterday there is an issue with skinning prof. Mobs after beeing looted still has "loot icon" and it is not possible to skinn it. [ creature has to be looted first - occures ]

Please check as this has huge impact on game.
Thanks in advance!

**Comment by Corson** [comment]
I have the same problem since yesterday. I also cannot mine ores.

**Comment by Artaxin** [comment]
thanks, ill check that
