### ISSUE TITLE
[PL][Item] "Kupowanie" itemu za darmo i możliwość sprzedania go.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6430]
Tak jak widać na SS te spodnie z sklepu Gildyjnego można dostać za darmo i potem je sprzedac ale na szczęście tylko za 1Cupera.
![wowscrnshot_021616_165603](https://cloud.githubusercontent.com/assets/5780624/13081763/4fbc6f2c-d4ce-11e5-8316-1557a7a68eaa.jpg)

**Comment by Aviannaqt** [comment]
https://github.com/Atlantiss/BugTracker/issues/5114
