### ISSUE TITLE
[EN][Quest][Darnassus]Calm Before the Storm(ID 4510)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6434]
Quest has been removed on 4.0.6. [Comments](http://www.wowhead.com/quest=4510/calm-before-the-storm#comments:id=1350029)

Wowhead Link: [Calm Before the Storm](http://www.wowhead.com/quest=4510/calm-before-the-storm)

The horde one might still be in game but should be removed as well([Calm Before the Storm](http://www.wowhead.com/quest=4511/calm-before-the-storm)).

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11663-6434questdarnassuscalm-before-the-storm/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
