### ISSUE TITLE
[En][Warlock][Felhunter][Spell lock]

### ISSUE THREAD

**Issue by texa69** [Atlantiss/BugTracker#6435]
Fel hunter's pell lock sometime miss and does nothing at all ! 
It's always 30% miss 70% success. That's a big problem for warlocks in arenas !

**Comment by texa69** [comment]
Don't tell me that I'm not hit capped cuz I'm not that noob !

**Comment by blinkmaster** [comment]
I cant reproduce that.

**Comment by kadi2** [comment]
Its due to the serwer diff. But It always hits with interrupt instantly and then silences with delay.

**Comment by texa69** [comment]
Sometimes it doesn't interrupt at all !

**Comment by Jenovas** [comment]
Cant reproduce.
Please test it more and tell us next time how to reproduce this bug or even try creating a video if you have time.
Closing.
