### ISSUE TITLE
[EN] [Talent] Mage - Imroved cone of cold not working properly

### ISSUE THREAD

**Issue by flashxx** [Atlantiss/BugTracker#6436]
Hello,

Improved cone of cold is currently breaking from its own damage (i.e. damage done from CoC counts towards its root break threshold) which should not happen.

Proof:
1) http://imgur.com/iQgUug6
2) http://imgur.com/a63zeDy

On the first screenshot you can see the mob has around 600 HP and CoC freeze breaks instantly while on the second one it does not since the mob has twice as much HP.

By the way, on retail all forms of CC have a very small period (like 0.1 sec) of break immunity. For example you could cast polymorph and immediately after cast cone of cold, not breaking your polymorph while rooting and slowing the target. I am yet to see such mechanics working on a private server but maybe you could be the first one.

Thanks.

**Comment by RhythmOfficial** [comment]
You are reffering to the cc delay there was like a 0,25 sec delay or so b4 stuff was applied. (something in that direction not 100% sure) but that allowed cross cc etc aswell (blinding a deep freeze for example).
I am still leveling so haven't found that many bugs yet, will post the ones that I do find.

**Comment by flashxx** [comment]
Hi Rhythm, I think you are refering to another mechanic which was removed at the end of Wotlk if I am not mistaken. For example you could spam SW: Death while casting other spell, to break CC.

Anyway this issue is resolved as of last restart. Thanks a lot to the staff for the fast fix!

**Comment by kadi2** [comment]
Did you level up your character to 85? I don't think they did fix it, it could be just broken for lower rank spells like it used to be months ago.
