### ISSUE TITLE
[PL][Talent][Mage][Improved Cone of Cold]

### ISSUE THREAD

**Issue by rahliell** [Atlantiss/BugTracker#644]
Cone Of Cold z talentem Improved Cone of Cold, sam z siebie przerywa freeze.
Problem polega na tym, że kiedy DMG Cone of Cold przekroczy jakiś próg %hp to freeze zostanie przerwany. (Nie wiem dokładnie jaki, lecz dzieje się to notorycznie na patchu 4.0.6 aktualnie do poziomu 75. Testowane na PTR, rev. 4108, lvl 85, mob lvl 80-81, Cone przerywa sam siebie, kiedy spell zada wysoki critical dmg, np. kiedy zadany jest z użyciem trinketa)

Wniosek: Na wyższych poziomach efekt jest mitygowany przez różnice dmg/hp, przez co przerywanie jest żadsze, jednak nadal występuje

Jak być powinno: Improved Cone of Cold powinien zawsze, nie zależnie od dmg samego spella dawać targetowi freeze.

**Comment by Wolffenstein** [comment]
Fixed in rev 4235.
