### ISSUE TITLE
[EN][NPC?] Aeonaxx

### ISSUE THREAD

**Issue by Aieerth** [Atlantiss/BugTracker#6440]
Hello. I managed to get Aeonaxx today, but I lost him after server crashed second time... but I noticed few issues.

1. To get on him you need to dismount, that means if you don't click fast enough you'll fall to ground and lose hp or even die. I managed to get on him by first time, but it shouldn't work like that.
2. He flies around with his whelps alerady summoned. They should appear after you mount Aeonaxx. There was no statement that 'Kill Aeonaxx before his whelps overhelm you!'
3. I can't attack him as Hunter, beacuse I'm too close to him. It should be fixed, beacuse at this moment Hunters can't really kill him (he has ~770k hp) with meele weapon, especially when being Beast Master.

**Comment by xolon** [comment]
The first bug is overall, for everything u do you have to dismount manually first

**Comment by R0shy** [comment]
Yup same thing happen to me.

**Comment by Aieerth** [comment]
There's next thing: after killing Aeonaxx you should get parachute, not fall down to death. >: My friend killed Aeonaxx for me, and her Warrior couldn't attack him either, beacuse he was too far away. When she turned around, she noticed she can attack him on his wings. Weird thing.
