### ISSUE TITLE
[Q.Bug] [Z]The Writhing Haunt [Q]Combat training

### ISSUE THREAD

**Issue by lZzozZl** [Atlantiss/BugTracker#6443]
In The Writhing Haunt there is NPC Called Thurman Grant, he give you Q. called Combat Training (Part 6 of 6 ) for LvL: 37. The quest tell's you to go and talk with Gory and after that to challenge him. I found Gory but i cant speak with him :/
And btw if complete it, will give some good items :)

**Comment by Aldurion** [comment]
https://github.com/Atlantiss/BugTracker/issues/482

**Comment by Aviannaqt** [comment]
read bt rules
