### ISSUE TITLE
[pets][hunter][talent][DR] - diminishing returns BuG

### ISSUE THREAD

**Issue by Cholee** [Atlantiss/BugTracker#6444]
according to: http://wowwiki.wikia.com/wiki/Diminishing_returns
"Banish, Charge, Cyclone, Entrapment, and Mind Control are on diminishing returns with themselves."
"Controlled Root - Freeze (Water Elemental), Pin (Crab), Frost Nova, Entangling Roots, Earthgrab (Earth's Grasp), Frost Shock (Frozen Power)"

Problem is:
Pin and Charge shere same DR effect here but it shoud not. So if u charge and pin target pin will be only 2 sec root instead of 4 sec.

Proof:
http://postimg.org/image/72d6d235p/
http://s28.postimg.org/ka2rwmbal/image.jpg

I will post video if needed but u can see at picture 1 that Im going to use pin... CAnt make 2SS under  1 sec :P

Crab is best PVP pet and I think we need fast fix.
Also pet mechanism is wrong. When we click spell like pin(mele spell channeling) pet should go attack target and use spell, but we get the message that the pet is not in range. I fixed it by macro:

/petattack [@pettarget,noexists]target
/petattack [@mouseover,harm,nodead]
/petattack [mod:shift, @focus]
/cast [@mouseover, nodead, exists] [@focus, exists, mod:shift] [] Pin

**Comment by Jenovas** [comment]
http://us.battle.net/wow/en/forum/topic/10195910192?page=1#2
Closing.
