### ISSUE TITLE
[EN][Item] Gnomish Gravity Well

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#6448]
This item currently doesn't reset fall damage and you still take the full damage from a fall.

It should reset that damage and save you from fatal and any fall damage.

Proof - http://www.wowhead.com/item=40727/gnomish-gravity-well#comments

One of the comments from 4.3 is :
"Are you tired of dying a painful falling death because you used Rocket Jump at the wrong moment? Well, Gnomish engineers rejoice! You can save yourself from that "Oh $%^&!" Rocket Jump off the cliff with  Gnomish Gravity Well™. When your Cloak, Levitate, and Slow Fall are on cooldown, use  Gnomish Gravity Well™."

**Comment by ponpontos** [comment]
It's working for me.

**Comment by Wolffenstein** [comment]
It's working as intended.

**Comment by NatsumeLily** [comment]
No it's not ...It should RESET fall damage...It sorta does in multi uses

"After running a few tests, I've found out the following, and I'm sure most of this has been posted before:

- Does not work anywhere where flying is disabled.
- Stops all forward momentum when used.
- Can be used while in mid-air.
- **Resets falling speed, can be used to stop fall damage if used well.**
- Cannot be used in combat.
- Sometimes gives an Overheated debuff, a 15 second debuff disallowing the use of the Gravity Well for the duration."

The one 1 use was at 10yards above the ground...You don't take 60k damage from falling 10 yards off the ground, as this well should RESET falling speed and damage
![wowscrnshot_021716_140303](https://cloud.githubusercontent.com/assets/15247730/13125087/1a8b01ac-d581-11e5-89c1-0ef1435deb40.jpg)
