### ISSUE TITLE
[EN][Quests][Mount Hyjal] Mount Hyjal Quests order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6450]
Quest [Wings Over Mount Hyjal](http://www.wowhead.com/quest=25985/wings-over-mount-hyjal) should be available after you complete quest [Return to Nordrassil](http://www.wowhead.com/quest=25578/return-to-nordrassil). Should not be available when you have in log the quest [Aviana's Legacy](http://www.wowhead.com/quest=27874/avianas-legacy)(Seems blizzard allowed to do both quests if you complete one and take the other one after it).

Quest [The Flameseer's Staff](http://www.wowhead.com/quest=25472/the-flameseers-staff) should be available after completing quest [Protect the World Tree](http://www.wowhead.com/quest=25317/protect-the-world-tree)

Quest [An Offering for Aviana](http://www.wowhead.com/quest=25663/an-offering-for-aviana) should be available after completing quest [Return to Nordrassil](http://www.wowhead.com/quest=25578/return-to-nordrassil) and when complete or have in log the quests [Wings Over Mount Hyjal](http://www.wowhead.com/quest=25985/wings-over-mount-hyjal) and 
[Aviana's Legacy](http://www.wowhead.com/quest=27874/avianas-legacy) should not be available as are just breadcumbs.

Quest [Into the Maw!](http://www.wowhead.com/quest=25623/into-the-maw) is missing. More info here: https://github.com/Atlantiss/BugTracker/issues/2005 (Just let he prev report as has more info in comments)

Quest [Fighting Fire With ... Anything](http://www.wowhead.com/quest=25381/fighting-fire-with-anything) should be available after completing quest [The Fires of Mount Hyjal](http://www.wowhead.com/quest=25630/the-fires-of-mount-hyjal). Reported here:https://github.com/Atlantiss/BugTracker/issues/5332

[The Codex of Shadows](http://www.wowhead.com/quest=25763/the-codex-of-shadows) should be available after completing quest [Fact-Finding Mission](http://www.wowhead.com/quest=25740/fact-finding-mission).

[The Twilight Egg](http://www.wowhead.com/quest=25644/the-twilight-egg) should become available after you complete quest [Slash and Burn](http://www.wowhead.com/quest=25608/slash-and-burn).

[Flamebreaker](http://www.wowhead.com/quest=25323/flamebreaker) should be available after you complete quest [The Flameseer's Staff](http://www.wowhead.com/quest=25472/the-flameseers-staff). Other issues: https://github.com/Atlantiss/BugTracker/issues/3262

[The Voice of Goldrinn](http://www.wowhead.com/quest=25268/the-voice-of-goldrinn) should be available after you complete quest [End of the Supply Line](http://www.wowhead.com/quest=25233/end-of-the-supply-line)

[Good News... and Bad News](http://www.wowhead.com/quest=29066/good-news-and-bad-news) is missing(quest should be given automatically) and event does not start after completing quest [Black Heart of Flame](http://www.wowhead.com/quest=25428/black-heart-of-flame).Minor one: Quest do not have a completion mark on the map. Might be related to: https://github.com/Atlantiss/BugTracker/issues/3927

[Fresh Bait](http://www.wowhead.com/quest=25493/fresh-bait) should be available after completing quest [Smashing Through Ashes](http://www.wowhead.com/quest=25490/smashing-through-ashes). Might tried to be reported here with false/wrong info: https://github.com/Atlantiss/BugTracker/issues/2959

[An Ancient Awakens](http://www.wowhead.com/quest=25520/an-ancient-awakens) should be available after completing quest [Breaking the Bonds](http://www.wowhead.com/quest=25514/breaking-the-bonds)

[Sethria's Demise](http://www.wowhead.com/quest=25776/sethrias-demise) should be available after completing quest [Sethria's Brood](http://www.wowhead.com/quest=25746/sethrias-brood). Other bug: https://github.com/Atlantiss/BugTracker/issues/603

[Aviana's Legacy](http://www.wowhead.com/quest=27874/avianas-legacy) should be available after completing quest [Return from the Firelands](http://www.wowhead.com/quest=25611/return-from-the-firelands). Is related to: https://github.com/Atlantiss/BugTracker/issues/2026, https://github.com/Atlantiss/BugTracker/issues/5394, https://github.com/Atlantiss/BugTracker/issues/3939

[Twilight Training](http://www.wowhead.com/quest=25291/twilight-training) should be available after you complete [In Bloom](http://www.wowhead.com/quest=25224/in-bloom) and [Trial By Fire](http://www.wowhead.com/quest=25223/trial-by-fire) and [Waste of Flesh](http://www.wowhead.com/quest=25330/waste-of-flesh).

[Speech Writing for Dummies](http://www.wowhead.com/quest=25314/speech-writing-for-dummies) should be available after completing quests [The Greater of Two Evils](http://www.wowhead.com/quest=25310/the-greater-of-two-evils) and [Twilight Territory](http://www.wowhead.com/quest=25311/twilight-territory).

[The Greater of Two Evils](http://www.wowhead.com/quest=25310/the-greater-of-two-evils) should be available after completing quests [Spiritual Training: Mercy is for the Weak](http://www.wowhead.com/quest=25309/spiritual-training-mercy-is-for-the-weak) and [Grudge Match](http://www.wowhead.com/quest=25496/grudge-match).

[Twilight Territory](http://www.wowhead.com/quest=25311/twilight-territory) should be available after completing quests [Spiritual Training: Mercy is for the Weak](http://www.wowhead.com/quest=25309/spiritual-training-mercy-is-for-the-weak) and [Grudge Match](http://www.wowhead.com/quest=25496/grudge-match).

[Head of the Class](http://www.wowhead.com/quest=25601/head-of-the-class) should be available after you complete quest [Speech Writing for Dummies](http://www.wowhead.com/quest=25314/speech-writing-for-dummies).

[Secrets of the Flame](http://www.wowhead.com/quest=25554/secrets-of-the-flame) should be available after completing quest [Slash and Burn](http://www.wowhead.com/quest=25608/slash-and-burn).

Wowpedia Link: [Mount Hyjal quests](http://wow.gamepedia.com/Mount_Hyjal_quests)

**Comment by Damfee** [comment]
Because of the messed up order, if you do Slash and Burn, you are sent in a different phase.

Doing Slash and Burn makes it impossible to complete Twilight Territory and The Greater of Two Evils.

Make sure to do those 2 before Slash and Burn or you are fucked.

**Comment by jdcro** [comment]
[Fresh Bait](http://www.wowhead.com/quest=25493) not being offered so am currently stuck with no Mount Hyjal quests even after completing [Smashing Through Ashes](http://www.wowhead.com/quest=25490) prerequisite, as well as [Durable Seeds](http://www.wowhead.com/quest=25491) and [Prepping the Soil](http://www.wowhead.com/quest=25502)

**Comment by Aival94** [comment]
@jdcro try download Grail and wholly addons and see what quests you have available. Do not forget to take the hero's call quest as well as these sometimes are needed for the next quests. I have not seen any changes to this quest for some time so not sure why it bugged for you

**Comment by tomatosz** [comment]
Fixed in rev. 5759, thanks for the very clear list!

(Except Good News... and Bad News, can't figure that one out yet, but that one has a seperate bugtracker issue so I will close this one).
