### ISSUE TITLE
[EN][Item]Buccaneer's Vest

### ISSUE THREAD

**Issue by Gromblisk** [Atlantiss/BugTracker#6453]
Hello!

Buccaneer's Vest should have "Random enchantment" and one should be able to transmogrify cloth chest item to to this Vest. I tried to transmogrify it and i couldn't. It says "This appearance cannot be used". Please do anything you can to make it transmogrifiable again! 

![wowscrnshot_021716_131711](https://cloud.githubusercontent.com/assets/17275966/13125336/7b2a82aa-d5c5-11e5-87c5-76875e624d11.jpg)

link to wowhead http://www.wowhead.com/item=14175/buccaneers-vest

Kind regards,

Gromblisk

**Comment by Folkk** [comment]
Still bugged. All drops of this have no stats and we cant mog it because of that

**Comment by TranceAccount** [comment]
Should be fixed when you obtain this item again and does not fix already obtained items as of rev. 5860.
