### ISSUE TITLE
[EN][WARLOCK][SPELL][SOULBURN] Summoning demons via soulburn.

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#6455]
1. Summoning via soulburn (instant demon summ) should not casue the warlock demons to get "Summoning Disorientation" which is a 5sec stun.
2. Resummoning demons should make thier cds reseted.

Proof: https://youtu.be/PAM2YYf4Au0?t=16m35s
You can see that resummoned demon is free of Summoning Disorientation and also CD on Spell Lock is reseted !!
Soulburn: http://logon.warmane.com/spell=74434
Summoning Disorientation: http://cata.openwow.com/spell=32752

**Comment by kadi2** [comment]
"Pet cds got nerfed, when u dismiss your pet and resummon the last one your cds are still on cooldown. Also can confirm that fel dom got nerfed as well. holla "

4.3++ hotfix, shouldn't reset cooldowns.

**Comment by Kejmil** [comment]
SOULBURN SO IMPORTANT IT DESERVES LABEL
AND CAPSLOCK

**Comment by Fearyourself** [comment]
The part about summoning disorientation shouldn't apply when resummoning a pet. Also, if you have a pet at 50% hp and summon a new one without dismissing first, the new pet will spawn with 50% hp which it shouldn't.
