### ISSUE TITLE
[EN][Spell][Pet][Warlock] Shadow Bite Vol.2.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6457]
Shadow Bite bierze Spell Power właściciela a powinien brać SP Peta do przeliczeń Dmg.

Stąd teraz Shadow Bite bije czasem po blisko 200k.

Z tego zgłoszenia:https://github.com/Atlantiss/BugTracker/issues/5968

"After a few searches:
http://www.arenajunkies.com/topic/239504-demonic-breath-vs-mortal-coil-shadowfury/#entry3917590

Formula: (142 + (1.228 * (SP * 0.5)))"

Ok jeśli taka jest formuła to, Shadow bite powinien bić za:
Mój pet ma 1350 SP czyli powinien bić za (142 + (1.228 * (SP * 1350))) = 1800 a nie za 2900 biorąc SP z mojej postaci...
I każdy Pet nie ważne czy Locka czy Maga powinien brać swoje SP a nie właściciela do przeliczeń DMG, zresztą SP peta = 30% SP właściciela.
Test robiłem bez talentów.
No i tyle w tej chwili pet napierdziela horrendalne ilości Dmg bo bierze SP od właściciela, który jest sporo większy od SP Peta.
![wowscrnshot_021816_030153](https://cloud.githubusercontent.com/assets/5780624/13131485/10bd9e30-d5ec-11e5-9eaf-e7d2263cdc19.jpg)

**Comment by anxanas** [comment]
Bump, i was able to get a 213k crit obviously bugged

**Comment by meowmewo** [comment]
As Affliction i dont get more then 50k crits.

**Comment by anxanas** [comment]
Dont trust the SP value, its bugged and change each summon, therefore you wont be able to calculate the damage

**Comment by BialyADI** [comment]
Tym bardziej się wgryzam w te mechaniki na Cata tym bardziej widzę jak to wszystko jest po bugowane ;D.

**Comment by anxanas** [comment]
Server was rolled back i believe, and this is no longer a problem. You can close it

**Comment by Wolffenstein** [comment]
It was fixed.

**Comment by BialyADI** [comment]
It is possible to fix that Lock and Load proc on hunters and Combustion ignore Resi?
Any way good work.
