### ISSUE TITLE
[EN][Talent][Spell][Warlock] - Death's Embrace after fix.

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#6458]
Fix didnt work, what happens is that under 25% of target HP, when the talent starts kicking in, Drain Soul and Drain Life start doing more damage each tick up to MILLION per tick at the end of drainsoul cast and thausands of Drain life. Dots dont have that problem, they are working fine under 25%.

Link to old thread - https://github.com/Atlantiss/BugTracker/issues/5916

**Comment by BialyADI** [comment]
Bonus nalicza się co każdy tick i na koniec Drain Soula napierdala po kilka milionów hehe ( ͡° ͜ʖ ͡°).

**Comment by currygodny** [comment]
Kukła w Orgri, żadnych buffów
[http://oi66.tinypic.com/6jdgl2.jpg](url)

**Comment by meowmewo** [comment]
Are u guys even aware in wich report that is?

**Comment by anxanas** [comment]
Lets all reroll affliction =)))

**Comment by meowmewo** [comment]
Release Firelands HC FAST :D

**Comment by BialyADI** [comment]
It is no about only Aff, Demo Pets hit for 200k too xD.

**Comment by BialyADI** [comment]
To samo dotyczy Drain Life tez bije po kilka tys pod koniec casta.

**Comment by anxanas** [comment]
Server was rolled back i believe, and this is no longer a problem. You can close it

**Comment by Wolffenstein** [comment]
It was fixed.
