### ISSUE TITLE
[EN][Instance-Cata] Zul'Gurub, Bloodlord Mandokir

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#6459]
some things not right with this fight

 [Level Up] - this should go up max 8 times

 [Spirit's Vengeance] - this should be apllied when someone is resurected by  [Revive] from  [Chained Spirit]

 [Decapitate] this should be used  during whe whole euconter on a counter, even when the boss  gets  [Frenzy] and its his only special skill he uses it not suposeed to be cast  without a cd.

-----
all the buff from 3  rounds with him [http://i.imgur.com/nSTfNzH.jpg](http://i.imgur.com/nSTfNzH.jpg)
no  [Spirit's Vengeance]

https://www.youtube.com/watch?v=d9QpCZOJBJA
https://www.youtube.com/watch?v=grDua1bXSCE

**Comment by stanq87** [comment]
https://www.youtube.com/watch?v=4ijrJjlMRyM
https://www.youtube.com/watch?v=JmI4LwuTfiw
https://www.youtube.com/watch?v=vIKJupKHJ24

**Comment by RandomPickNewb** [comment]
[url=http://www.wowhead.com/spell=96493/spirits-vengeance]Spirit's Vengeance[/url] is working as intended(did blood lord today).Also recount/skada for buffs applied is not a reliable source.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5107 fixed
