### ISSUE TITLE
[EN][Event][Love is in the Air] Love Rocket / Silver Shafted Arrow

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#6461]
Players should be able to buy a stack of 5 love rockets or 5 shifted arrows in exchange for 5 love tokens, while right now a player can only buy 1 love rocket or shifted arrow per 5 tokens;

http://www.wowhead.com/npc=37674/lovely-merchant
http://www.wowhead.com/item=34258/love-rocket#comments x5 for 5 tokens,
http://www.wowhead.com/item=22200/silver-shafted-arrow x5 for 5 tokens
http://www.wowhead.com/item=22218/handful-of-rose-petals x5 for 2 tokens

other thread was closed, but it's not fixed yet. 
#6420

**Comment by Bildo** [comment]
oh sorry forgot 1 sql, fix on repo

**Comment by Samineh** [comment]
Thank you for the fix :heart:
