### ISSUE TITLE
[PL][Warlock][Talent] Shadow Embrace - Dmg increase Bug.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6462]
Talent: http://logon.warmane.com/spell=32392

Jak jest:
Zwiększa Dmg z Haunt i Shadow Bolt, mimo że nie są DoTy tylko Direct Dmg.

Jak powinno być:
"increasing all Shadow periodic damage dealt to the target by you by 5%. Stacks up to 3 times."
Shadow Embrace nie powinien zwiększać Dmg z Haunt i Shadow Bolt bo nie są to "periodic damage".

**Comment by meowmewo** [comment]
Duplicate
