### ISSUE TITLE
[EN][Hunter] Camouflage

### ISSUE THREAD

**Issue by 4free100** [Atlantiss/BugTracker#6466]
Rogues can sap hunter's in Camouflage on this server. Which is just hilarious.
I played on AT and other well scripted private servers so i know what i'm talking about. 
Also played from season 1 in TBC until Season 11 in Cata on retail.
Please fix this bug #Atlantiss team i trust in your abilities.:)

http://cata.openwow.com/spell=51753 = Camouflage
http://cata.openwow.com/spell=6770   = Sap

brgds 4free100

**Comment by GtGraphics6** [comment]
Can confirm of this, and yeah it shouldn't be possible

**Comment by calladin** [comment]
http://us.battle.net/wow/en/forum/topic/3082078295
Confirmed, so annoying bug PLS FIX ASAP /cheer

**Comment by Zhalox123** [comment]
Confirmed sap shouldnt be doable trough camouflage.

**Comment by Jenovas** [comment]
Fixed in rev 5276
