### ISSUE TITLE
[EN] [Quest] [Cata] Ignition

### ISSUE THREAD

**Issue by Sinelis** [Atlantiss/BugTracker#6467]
The event works almost fully, but if you choose to use the meteors like you should you can't loot the Titanic Guardian

![wowscrnshot_021816_172834](https://cloud.githubusercontent.com/assets/17084945/13150259/4fe107ea-d665-11e5-8b9e-c337f970420d.jpg)

**Comment by Aviannaqt** [comment]
read bt rules
