### ISSUE TITLE
[pl] [shaman] [spell] Lava lash

### ISSUE THREAD

**Issue by leyte** [Atlantiss/BugTracker#6473]
Lava lash nie aktywuje już efektu z unleash elements ktory powinien zwiekszyc o 30% dmg z Twojego next fire spell, no przeciez to tak powinno działać, że konsumuje go i zwiekszony jest dmg z lava lash.

**Comment by blinkmaster** [comment]
http://eu.battle.net/wow/en/forum/topic/12822302320
Nie.

**Comment by leyte** [comment]
Ten post z Globala jest z przełomu Mists of Pandaria i Warlord of Draenor więc... jak możesz opierać cataclysm na poscie z globala z końca 2014, nikt na globalu nie pisałby wówczas o CATACLYSM który skonczyl sie w 2012... znajdź post z cata i mi udowodnij, nie z początków WoD'a

**Comment by leyte** [comment]
W cata na globalu to normalnie działało, a jeżeli to blizzlike, to wszystko powinno być tak jak było na cata, nie zostało 'dopracowane/zmienione' w MoP/WoD

**Comment by blinkmaster** [comment]
http://eu.battle.net/wow/en/forum/topic/1503481711
Proszę bardzo

**Comment by Nc94** [comment]
To nigdy tak nie działało i nie powinno działać.

**Comment by blinkmaster** [comment]
No cóż jeżeli tak tu działało wcześniej to sporo wyjaśnia ten pop. Dmg

**Comment by leyte** [comment]
No dobra, to już lepszy argument.
