### ISSUE TITLE
[EN][Quest] Pilfering Perfume World Event Quest Please read!

### ISSUE THREAD

**Issue by R0shy** [Atlantiss/BugTracker#6475]
Hey GM,
Basically, once you transform into a Goblin package runner and run towards the Crown chemical Company's stock pile initially your suppose to talk to the Crown Supply sentry and he should give you a package which will then complete the quest. However this is not working and thus meaning a lot of players cant continue with the quest chain please fix it before the even ends. Thanks!

**Comment by Luna-maria** [comment]
#6418
