### ISSUE TITLE
[EN][Spell][Warlock] Soulburn

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6476]
Link to summon felhunter: http://cata.openwow.com/spell=691
Link to soulburn: http://cata.openwow.com/spell=74434

While having a minion out (i.e. felhunter) and you summon a new one using soulburn causes it to get stunned (summoning disorientation) which it shouldn't.

**Comment by Bjarzyna** [comment]
Also new felhunter is summoned with the same health, mana and debuffs as previous one

**Comment by Illusie** [comment]
ty

**Comment by Jenovas** [comment]
Fixed in rev 5035
