### ISSUE TITLE
[EN][Spell][Warlock] Minions

### ISSUE THREAD

**Issue by elasdmehico** [Atlantiss/BugTracker#6477]
When you have felhunter out at 50% health and summon a new one with or without soulburn, the next minion will have 50% health aswell. Health/mana should be at 100%.

Link to felhunter: http://cata.openwow.com/spell=691
Link to soulburn: http://cata.openwow.com/spell=74434

This is for all minions not just felhunter.

Edit: https://www.youtube.com/watch?v=PAM2YYf4Au0
Go to 0:39 and you see him summoning a new pet with full health

**Comment by Illusie** [comment]
ty
