### ISSUE TITLE
[EN][Spell][Warlock] Minions

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6478]
All warlock minions have way too low health compared to what they should have.

If you go to 0:34 you see the warlock having 139k hp and his pet at 102k hp.
https://www.youtube.com/watch?v=PAM2YYf4Au0

Screenshot of my health/pet health: http://i.imgur.com/IrnqIsv.jpg

When he gets healed by the shaman he gets more maximum health and his pet's health increases aswell.

**Comment by BialyADI** [comment]
What is Correct formula for all pets? And you have Wild on you.

**Comment by texa69** [comment]
THROW MOAR DOTS !

**Comment by Illusie** [comment]
ty

**Comment by Fearyourself** [comment]
It doesn't matter if I have wild on me. The health of pets is too low compared to what it should have. Pets should have x % health from the master and it doesn't work very much.
i.e. if I get mark or any other hp buff the hp of pets should increase aswell

**Comment by BialyADI** [comment]
It is not % Health, but % of your stamina.
It trayed find it but it is not easy ;x.

**Comment by Fearyourself** [comment]
I think it's health, because in the video I posted when the warlock gets healed by the shaman, his health increases for every heal and so does the felhunter's health.
