### ISSUE TITLE
[EN][Spell][Warlock] Minions cd reset

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6479]
When summoning a new minion the cooldowns of it's spells/abilities should be instantly reset.

Link to felhunter: http://cata.openwow.com/spell=691
Proof of cds getting reset: https://www.youtube.com/watch?v=PAM2YYf4Au0
Go to 0:39 you see spell lock is on cd, after 2-3 seconds he summons a new one and spell lock is instantly reset.

**Comment by RhythmOfficial** [comment]
This got hotfixed somewhere on patch 4.2.3 or something like that.
This bug is incorrect.

**Comment by Fearyourself** [comment]
No. When you dismiss your pet and summon a new one after that, then the cooldowns should be reset. That's what's happening in the video.

**Comment by RhythmOfficial** [comment]
Are you a pleb? can you even read what I just wrote IDGAF what is happenning in the video, that's an old video. 
This got hotfixed and doesn't work like what you're saying therefor it is incorrect.

**Comment by Jenovas** [comment]
This was hotfixed in patch 4.3.4 by blizzard.
Closing.
