### ISSUE TITLE
[EN][Quest][Darkshore] The Absent-Minded Prospector

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#648]
http://www.wowhead.com/quest=13911/the-absent-minded-prospector
the escort path work well but in the end the quest don't give the credit so you can't complete it

video if needed: https://www.youtube.com/watch?v=KF-_Pt9XlnY

**Comment by k-kang** [comment]
I'm also having this issue. The prospector will not move back to camp so the quest cannot be completed

**Comment by k-kang** [comment]
I've resolved this issue. When the prospector gets stuck on his path at the cliff, simply kite the Greymist Oracle mob immediately below him with a ranged attack and kill it. The NPC will then complete his path and finish the quest.

**Comment by Swepy** [comment]
yea what k-kang said worked for me, i just finished the quest by killing that mob, so its completable. thanks k-kang

**Comment by cuamanuel** [comment]
I've tried completing the quest objective multiple times but Jr. Archaeologist Ferd does not show a question mark sign to turn in the quest. Cannot proceed to next quest chain
![image](https://cloud.githubusercontent.com/assets/4362689/7562729/414ee502-f809-11e4-8500-db43e11f63bc.png)

**Comment by Aival94** [comment]
This happened because npc is in an other phase with the Aman projection.Probably phasing event not end when someone do it for some time(or till a restart/crash)

**Comment by rasengan111** [comment]
Not able to complete, the NPC completes it's patch after killing the murloc but, there is Aman spawned and Jr. Archaeologist Ferd wouldn't offer to turn in the quest.

**Comment by lourrific** [comment]
November 22, 2015 this quest is still bugged. I accept quest he asks me if I'm ready but he doesn't move or go anywhere. Can not complete quest. Next month in December this bug will have a birthday it will be one year old bug ....ffs smh.

**Comment by starsurge7** [comment]
It works, you just have to kill the murloc right beneath the cliff where prospector stops and then escort him to the camp. It might be difficult for warriors and rogues since the murloc can't be pulled and you should not jump down to kill him because you must be near the prospector in order for quest to be completed.

**Comment by Madenator** [comment]
Confirmed, you can complete the escorting tricky, but you cannot complete the quest.

**Comment by Snake90** [comment]
Still bugged ! The quest was completed but i can't return quest to the NPC and even after a crash/restart, the situation remains the same.

**Comment by karhima** [comment]
Still broken, escort can be done but the quest can't be turned in.

**Comment by Bildo** [comment]
Is this issue still exists?

**Comment by Aival94** [comment]
Yeah.Either NPC of event get aggro to the nearby murloc or after someone complete quest [The Titans' Terminal](http://www.wowhead.com/quest=13918/the-titans-terminal) event after the quest stuck without being completed and ended so npcs stay on "event" Phase.

**Comment by Khangu** [comment]
Confirmed. Killing the murlock allows to complete quest but it cannot be any longer turned in. "Jr. Archeologist Fred" doesn't have "question mark" and there is even no possibility to talk to him.

**Comment by Snake90** [comment]
Still bugged : the quest can be completed but no possibility to talk to the NPC because he's in a different phase :/

**Comment by coba999** [comment]
bugged! the quest can be completed but no possibility to talk to the NPC

**Comment by jackal86** [comment]
Bump. the quest can be completed, but can't be turned in to the right npc (no gold "?" on his head, no dialogue)

**Comment by Bildo** [comment]
tell me if its ok now

**Comment by jackal86** [comment]
Worked for me! thanks a lot for the hard work! yay!

**Comment by Bildo** [comment]
fix is not live yet :dagger:
