### ISSUE TITLE
[EN][Spell][Warlock] Minions resilience

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6480]
As of patch 3.3.0.: Pet Resilience: All player pets now get 100% of their master’s resilience.
I checked all patch notes up till 4.3.4. and none of them says anything about this being changed.

I don't even know how to test how bad it is, all I know is that it's broken.

**Comment by BialyADI** [comment]
No my warlock, pet have resi from me.

**Comment by Jenovas** [comment]
Pets do get resi from caster.
Closing. Please atleast do some tests te next time you report something.
