### ISSUE TITLE
[PL] [Raid] Firelands 10 - Splitting Blow

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#6481]
Po użyciu przez Ragnarosa umiejętności Splitting Blow podczas robienia go na 10 pojawia się 8 Sons of flame,czyli tyle, ile na 25. Na 10 powinny pojawiać się tylko 4 Sons of Flame.

links:

https://www.youtube.com/watch?time_continue=191&v=qYIGg9l7bLk
https://www.youtube.com/watch?v=2U35iEEHBlc

**Comment by Glare** [comment]
Na filmiku, który podałeś można zauważyć, że pojawia się ich 8.

**Comment by Respect69** [comment]
Do zamknięcia, źle spojrzałem.

**Comment by BialyADI** [comment]
Sam mozesz zmknąc swój ticket ;p
