### ISSUE TITLE
[EN] [Rogue] Tricks of the Trade sometimes unable to be used

### ISSUE THREAD

**Issue by RhythmOfficial** [Atlantiss/BugTracker#6482]
When I use tricks of the trade it sometimes grays out and I am unable to use it.
It just says : Ability is on not ready yet. when it clearly is it is just grayed out.
This is very annyoing in raids and arenas and would like to ask if you guys could fix this asap.

**Comment by blinkmaster** [comment]
In interface - combat - custom lag tolerance set it to 0 ms

**Comment by RhythmOfficial** [comment]
lol okay, never had this issue before on a server.

Weird fix aswell but I guess thats how this server rolls ......

**Comment by RhythmOfficial** [comment]
Just Litterally changed it and still the same problem, this is not fixed.
Please fix this bug its more important than you think.

**Comment by tnarf** [comment]
1. duplicated https://github.com/Atlantiss/BugTracker/issues/5299
2. this fixx only minimize chances for this bug

**Comment by RhythmOfficial** [comment]
how about trying to fix the bug ?
