### ISSUE TITLE
[EN][Quest][Dustwallow Marsh] Suspicious Hoofprints

### ISSUE THREAD

**Issue by therealmikz** [Atlantiss/BugTracker#6483]
Hoofprints don't give the quest.

**Comment by Aviannaqt** [comment]
read bt rules

**Comment by therealmikz** [comment]
You know, you could also point that I didn't post the link to the quest (if that's what you're refering to, you didn't mention - it's not a duplicate, quest clearly doesn't work, so I'm assuming that's on your mind) - I'd just post the link. Now I've got to pointlessly create another issue, but if you insist...
