### ISSUE TITLE
Westfall storyline

### ISSUE THREAD

**Issue by mandoge** [Atlantiss/BugTracker#6486]
So basically I was just questing in Westfall up until after the quest when you go to Moonbrook to observe the shadowy figure. That worked, but when I turned it in, no quest showed up. Gryan Stoutmantle has a question mark, but there is no quest. That wise Draenei guy also has a blue question mark, but the quest cannot be turned in. Now I'm stuck and can't progress any further into the storyline.

**Comment by Aviannaqt** [comment]
read bt rules
