### ISSUE TITLE
[pl][mage][spell] polymorph vs absorb damage

### ISSUE THREAD

**Issue by Pankaa** [Atlantiss/BugTracker#6488]
jak dziala: Absorbowany damage zrywa polymorph'a. Dla przykladu jesli priest ma banke(jakis absorb efekt np. pws) i da swd na poly ktore rzuca mu mag to poly zostaje zerwane
jak byc powinno: poly nie powinno byc zerwane jesli caly dmg jest absorbowany
Co dokladnie jest zle: Przestarzale dzialanie od cata bylo to zmienione.

Dowody
I've noticed, as I'm sure others have, that Shadow Word: Death won't break Polymorph if the damage is absorbed.
Furthermore, Hand of Sacrifice will not break Polymorph (as in the transferred damage will not break the Paladin out), but it will break other crowd controls.
http://us.battle.net/wow/en/forum/topic/1568011625

Keep in mind that if the recoil damage is absorbed, the sheep will not break
http://us.battle.net/wow/en/forum/topic/2416152829

Not sure if this is a bug or not but atm you cant death poly's while absorbing the incoming death damage.
http://us.battle.net/wow/en/forum/topic/969747226

ps. z racji tego bonusu z t12 można by poprawić zachowanie Mirror Image bo to kompletna porażka że taki uniwersalny spell obecnie działa tak że przyzywa 3 klony które STOJĄ i czekają aż przeciwnik je zatakuje(wcześniej nie robią nic).
Tu macie pełne zgłoszenie z dowodami i opisanymi wszystkimi bugami dotyczącymi MI u maga.
https://github.com/Atlantiss/BugTracker/issues/5610

**Comment by kadi2** [comment]
Przez chwile na cata faktycznie tak to dzialalo z poly, ale to jest raczej mechanika wotlkowa z tymi absorbami.

**Comment by debtheone** [comment]
nie trolluj gosciu

**Comment by Pankaa** [comment]
Sam jestes hotfixniety 

11/5/2010
http://us.battle.net/wow/en/forum/topic/969747226

10/30/2011
http://us.battle.net/wow/en/forum/topic/3424799418

**Comment by debtheone** [comment]
http://eu.battle.net/wow/en/forum/topic/3553610935

**Comment by tnarf** [comment]
hmmm
http://www.mmo-champion.com/threads/1000618-CC-s-now-count-on-damage-absob?p=13723005&viewfull=1#post13723005
Jeśli dobrze widzę to SW:D w magiczny sposób ominęło bańkę, zadało dmg i przerwało Poly

**Comment by debtheone** [comment]
no fixneli to gdzieś kolo 4.2 albo wyżej tego się miało na 4.0.6 cancelaure na da i pwsa
