### ISSUE TITLE
[EN][Talent][Priest]Vampiric Embrace

### ISSUE THREAD

**Issue by onqgore** [Atlantiss/BugTracker#6489]
http://cata.openwow.com/spell=15286
i dont resieve any heals from shadow spell dmg.Only 
http://cata.openwow.com/spell=2944
heal and work correctly.Whats wrong with it?

**Comment by RandomPickNewb** [comment]
It's working and worked fine for me.Are you sure you even casted it on yourself .. ?

**Comment by onqgore** [comment]
heh you are right it's not a passive....i'm so stupid xD
