### ISSUE TITLE
[EN] [Spell] [Warlock] Soulstone 

### ISSUE THREAD

**Issue by lameia** [Atlantiss/BugTracker#6490]
http://www.wowhead.com/spell=20707/soulstone
After using the Soulstone, player should be ressurected, but window with choice (Realase Spirit / Use Soulstone) is dissapearing. After disappear nothing happens and player have to exit the game

**Comment by vaseno1** [comment]
Depends if the Warlock dies before the player who has soulstone on him, ofc the soulstone will disapear if the warlock dies.

**Comment by lameia** [comment]
No, I mean before the warlock's death. I mean another player whos has a Soulstone. He/She cannot use that SS

**Comment by Fearyourself** [comment]
Back in the days soulstone was used to ress up the whole party in case of a wipe. That means even if the warlock dies the soulstone should still be useable. Warlocks can even soulstone themselves and ress up.

**Comment by anxanas** [comment]
if you have soulstone on you, and some idiot resses you, you lose both the soulstone and the ress too =)))

**Comment by lameia** [comment]
No.. The player which had soulstone cannot russurect by  this spell. After the choice 'use soulstone' window is disappearing and nothing happens

**Comment by reapertg** [comment]
So much misinformation on one report :'( Regardless of the living / death state of the casting warlock, whoever is soulstoned should be able to self rez upon death. The ability to use the soulstone to rez someone after their death was not added until much later. As for soulstone being used to rez whole party....what? this NEVER happened.

**Comment by pelekon** [comment]
As a warlock I have never had problem with ss, so I am closing this report as invalid.
