### ISSUE TITLE
[EN][Spell][Warlock] Nether Protection

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6491]
Nether ward: http://cata.openwow.com/spell=91711
Nether protection: http://cata.openwow.com/spell=30301
Voidwalker sacrifice spell: http://cata.openwow.com/spell=7812

Nether protection does only work when absorbing a spell damage using nether ward/shadow ward. It doesn't work with any other effects like priest shield, hpala mastery shield, voidwalker sacrifice etc.

**Comment by Zhalox123** [comment]
Confirmed working totaly different then in should

**Comment by Jenovas** [comment]
"Tested this yesterday with a guildmate, nether prot does not proc from PW:S, it only procs on Nether Ward, Shadow Ward and Sacrifice. "

**Comment by Fearyourself** [comment]
"When you absorb damage through Shadow Ward, Nether Ward or other effects, you gain Nether Protection, reducing all damage by that spell school by 15%/30% for 12 sec."

What I get out of this is that it should proc from other effects aswell. Meaning power word shield, right?

**Comment by Jenovas** [comment]
Fear no. It should only work from Nether Ward, Shadow Ward and Sacrifice.

**Comment by Fearyourself** [comment]
Oh okay

**Comment by Jenovas** [comment]
The tooltip is written in a way that would make you think all absorbs, but if you read about it, it turns out it works for only warlock absorbs.
