### ISSUE TITLE
[EN][Spell][Warlock] Nether Protection

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6492]
Warlock don't get nether protection if a spell is fully absorbed by the shield. i.e. having nether ward up say it absorbs 10k damage and you get hit by 12k spell, you wont get nether protection.

Link to nether ward: http://cata.openwow.com/spell=91711
Link to shadow ward: http://cata.openwow.com/spell=6229
Link to nether protection: http://cata.openwow.com/spell=30301

FYI this happens with shadow ward aswell. Nether protection is basically useless now with the low amount of absorb damage and the fact that spellcasters usually hit for more than the ~11k it absorbs.

**Comment by Zhalox123** [comment]
Confirmed

**Comment by Jenovas** [comment]
"Tested this yesterday with a guildmate, nether prot does not proc from PW:S, it only procs on Nether Ward, Shadow Ward and Sacrifice. "

**Comment by Fearyourself** [comment]
Can somebody take a look at this?

**Comment by Fearyourself** [comment]
@Jenovas
