### ISSUE TITLE
[PL] ToC / ToG

### ISSUE THREAD

**Issue by Grudol** [Atlantiss/BugTracker#6495]
Zbugowane move map bosowie spadaja pod tekstury.

**Comment by BialyADI** [comment]
ToC - http://wowwiki.wikia.com/wiki/Trial_of_the_Crusader
ToGC - http://wowwiki.wikia.com/wiki/Trial_of_the_Grand_Crusader

Tak daje linki by było wiadome o co chodzi :>.
