### ISSUE TITLE
[EN][Firelands] Alysrazor

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#6498]
After new updates, hatchlings aren't moving, images speak for themselves.

![wowscrnshot_022016_191314](https://cloud.githubusercontent.com/assets/13660744/13198328/3b844b84-d806-11e5-8029-b999d123f04c.jpg)
![wowscrnshot_022016_191310](https://cloud.githubusercontent.com/assets/13660744/13198329/3b9e78c4-d806-11e5-9f9b-b8f57113977c.jpg)

**Comment by currygodny** [comment]
#6497

**Comment by Aival94** [comment]
After they reversed the new Mmaps implementation they move.
