### ISSUE TITLE
learn to log please

### ISSUE THREAD

**Issue by Chulain** [Atlantiss/BugTracker#6503]
learn to log please

http://i.imgur.com/YYcMF7B.png

**Comment by Chulain** [comment]
ps i only duped a little over 1 million gold... i think?

**Comment by Kejmil** [comment]
gold wipe in 3... 2... 1...

**Comment by Kiperr** [comment]
http://imgur.com/YYcMF7B  Uploaded 11 months ago, sooo i gess it was fixed long time ago, bai.
