### ISSUE TITLE
[EN][Spell][Druid] Skull Bash while rooted

### ISSUE THREAD

**Issue by Astrobazooka** [Atlantiss/BugTracker#6504]
If you are within 13 yards with druid and he is affected by any root effect he can still use Skull Bash to interrupt you. Its pretty annoying and often abused.

OpenWoW link:
http://cata.openwow.com/spell=80964
http://cata.openwow.com/spell=80965

**Comment by blinkmaster** [comment]
Was repaired long time ago, maybe fix went down after new core changes etc

**Comment by Astrobazooka** [comment]
Maybe, but problem still persist !

**Comment by Jenovas** [comment]
No, while rooted Skull Bash doesnt work, only the interupt works and it works only if you are up to 7 yards away from the druid.

**Comment by blinkmaster** [comment]
@jenova
According to http://us.battle.net/wow/en/forum/topic/3392890444
This should be 5 yds not 7

**Comment by Astrobazooka** [comment]
Bump !
