### ISSUE TITLE
[PL][Spell][Warrior] Charge/Intercept/Intervene on new vmaps/mmaps.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6505]
Ogołnie Charge działa niezle, ani razu nie wpadłem pod mapę na BG póki co.

Lecz jest inny problem, nie można dać Charge na niektórych arenach i na małych schodkach.
Znalazłem wcześniejsze zgłoszenie na ten temat: https://github.com/Atlantiss/BugTracker/issues/2402.

Tak jak na Screenach, danie Charge kończy się doleceniem do miejsca "połączenia tekstur/schodka" lub zobaczeniu komunikatu "Patch no Available".
![6dd4e4ac-bd8d-11e4-8f72-ff87eedd8048](https://cloud.githubusercontent.com/assets/5780624/13200528/e10d6f72-d84c-11e5-8640-a540fad78a9e.jpg)
![d6de15be-bd8c-11e4-8648-0706afe8914f](https://cloud.githubusercontent.com/assets/5780624/13200529/e2a7a5be-d84c-11e5-8cd8-ec887a269b4d.jpg)

**Comment by Jenovas** [comment]
W drugim screenie chodzi ogólnie o charge do wody i z wody?

**Comment by BialyADI** [comment]
Raczej z wody do przeciwnika na "betonie" ponieważ pomiędzy jest stopień w góre, natomiast z "betonu do zielonej wody jest ok bo stopień będzie w dół wtedy nie ma problemu.

No i jest problem z takim czymś jak tu, o ile jest to możliwe do naprawy na Atlantissie:
Charge pod górę na resp przeciwnika na WG, na Atlantissie zobaczymy "No path available".
https://youtu.be/Qce6m6HstRA?t=3m50s <-- 3:50 min.

Intervene pod GÓRĘ, u nas niemożliwe:
https://youtu.be/scDrEXNSR-Y?t=21m49s <-- 21:49 min.

**Comment by BialyADI** [comment]
No i jest problem z takim czymś jak na filmiku, o ile jest to możliwe do naprawy na Atlantissie:
Charge pod górę na resp przeciwnika na WG, na Atlantissie zobaczymy "No path available".
https://youtu.be/Qce6m6HstRA?t=3m50s <-- 3:50 min.

Intervene pod GÓRĘ, u nas niemożliwe:
https://youtu.be/scDrEXNSR-Y?t=21m49s <-- 21:49 min.

**Comment by BialyADI** [comment]
Tez jest nadal czasem problem z "No path available" w miejscach których nie powinien być lecz nie są to miejsca szczególnie istotne.
![wowscrnshot_022316_154417](https://cloud.githubusercontent.com/assets/5780624/13255035/6ce1cafe-da44-11e5-8d50-02beb4661418.jpg)

**Comment by BialyADI** [comment]
Bug nadal występuje na Arenach w zgłoszeniu.
A co do samej Charge/Intercept/Inrervene na BG/Word PvP po zmianach jest niemal perfekcyjnie ^^.

**Comment by BialyADI** [comment]
Bump.

**Comment by lamaATS** [comment]
Jakiś czas temu były nowe vmapy oraz mmapy jak aktualnie wygląda sytuacja?
#3499

**Comment by BialyADI** [comment]
Jest całkiem dobrze, serio ;>.

**Comment by lamaATS** [comment]
Czyli mogę zamknąć na ten moment?

**Comment by lamaATS** [comment]
Jeśli będzie potrzeba będzie reopen w tym momencie zamykam.
