### ISSUE TITLE
[en][mage][spell] Slow pvp duration time

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6511]
Slow should have 8 sec duration time in pvp
http://wowwiki.wikia.com/wiki/Slow_(mage)
Patch 4.0.6 (8-Feb-2011): Slow now has a PvP duration of 8 seconds.

**Comment by BialyADI** [comment]
i have 15s like in PvE.

**Comment by BialyADI** [comment]
Bump
