### ISSUE TITLE
[EN][Spell][Hunter] Stable/Call Pet

### ISSUE THREAD

**Issue by jxk1000** [Atlantiss/BugTracker#6513]
The Pet Stable is bugged. I tried to take a new pet out of the stable to my pet bar, replacing an old one. The new pet "symbol" appears naturally on the bar, but when I click it, the old pet is summoned. For instance; let's say I stabled a Cat and replaced it with a Bear. The Bear symbol is there, but the pet summoned when i click the Bear button is the Cat, which should be stabled.
I'm not sure this has already been posted, if that's the case feel free to delete my post.

**Comment by jxk1000** [comment]
Edit: Also, the pet stabled, which in my example above should be the Cat, is not in the stable window shown as "stabled", it's tooltip (symbol) isn't there at all. Though, as already stated, it's summoned when I call the pet.

**Comment by krecik88** [comment]
fixed in 4979
