### ISSUE TITLE
[EN][Item][Reins of the Crimson Deathcharger]

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#6515]
I bought that mount few minutes ago i learned it and when i try to mount up on it i get the message  "The spell is not available to you"? I don't understand why i can't use it... I think it might have to do something with #5965 but i don't understand the language so I'm sorry if I'm repeating something.

http://www.wowhead.com/item=52200/reins-of-the-crimson-deathcharger  Link of the mount.

**Comment by Zhalox123** [comment]
Confirmed same problem

**Comment by Nc94** [comment]
This mount shouldn't be obtainable on ATS cuz Smourne chain doesn't work. Ppl from sunwell transfers received those mounts (cuz they had them on sunwell but they shouldn't) and now they're selling them knowing that this mount can't be used/will be deleted - administration turned them off right know like other mounts that shouldn't be transfered so it isn't a bug. You just wasted your money.

**Comment by Aviannaqt** [comment]
This mount is currently disabled so you can't ride it and it will be deleted within few next days. / Bastek

**Comment by Sayris9876** [comment]
Ok i saw that in the forums but i was told from GM ingame that the mount will remain disabled up untill the quest chain is fixed but it WONT be deleted? And if you guys deleting it why the hell did you allow people from sunwell to sell it at the first place? What about us the people that spend thousands of golds on this mount?
