### ISSUE TITLE
[PL][Druid][Talent] Master Shapeshifter

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#652]
http://cata.openwow.com/spell=48411

Nie daje nam dodatkowego physical dmg/crit change/spell damage jeśli shapeshiftujemy się z formy do formy.

Przykład:
Jesteśmy w cat forme, shapshiftujemy do bear form - brak % physical dmg
Podobnie na odwrót.

Jeśli z caster formy zmieniamy się w misia/kota/cokolwiek to bonus otrzymujemy

Występuje tez na main realm

**Comment by mitim1** [comment]
Bump!

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
