### ISSUE TITLE
[EN][Quest][Horde] Hillsbrad Foothills Quests

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#6522]
Those quests are bugged:

- [x] ~~[Matters of Loyalty (ID: 28600)](http://www.wowhead.com/quest=28600/matters-of-loyalty)
How the quest should work: https://www.youtube.com/watch?v=Wl8BnLXwNHI~~

This quest block:
- [x] ~~[March of The Stormpike (ID: 28506)](http://www.wowhead.com/quest=28506/march-of-the-stormpike)~~
- [x] ~~[Breaking The Hand (ID: 28556)](http://www.wowhead.com/quest=28556/breaking-the-hand)~~

When you have completed the Southpoint gate quests that introduce you to Orkus, you should be able to take those quests:
- [x] ~~[Cry of the Banshee (ID:28538)](http://www.wowhead.com/quest=28538/cry-of-the-banshee)~~
- [x] ~~[Decimation (ID:28566)](http://www.wowhead.com/quest=28566/decimation)~~
- [x] ~~[Infiltration (ID:28603)](http://www.wowhead.com/quest=28603/infiltration)~~
- [x] ~~[Deception and Trickery (ID:28604)](http://www.wowhead.com/quest=28604/deception-and-trickery)~~
- [x] ~~[Domination (ID:28605)](http://www.wowhead.com/quest=28605/domination)~~
- [x] ~~[Stormpike Apocalypse (ID: 28616)](http://www.wowhead.com/quest=28616/stormpike-apocalypse)~~

_____________________________

All the quests that are "Plants Vs Zombies" style are bugged:
1) [Basic Botany (ID: 28733)](http://www.wowhead.com/quest=28733/basic-botany)
2) [Flower Power (ID: 28617)](http://www.wowhead.com/quest=28617/flower-power)
3) [Ghouls Hate My Grains (ID: 28744)](http://www.wowhead.com/quest=28744/ghouls-hate-my-grains)
4) [Someone Setup The Pumpkin Bomb (ID: 28747)](http://www.wowhead.com/quest=28747/someone-setup-the-pumpkin-bomb)
5) [Lawn of The Dead (ID: 28748)](http://www.wowhead.com/quest=28748/lawn-of-the-dead)

**Comment by Angelo-DM-** [comment]
[March of The Stormpike (ID: 28506)](http://www.wowhead.com/quest=28506/march-of-the-stormpike) is bugged too...

How it should work: https://www.youtube.com/watch?v=S6jygcRUj3o

**Comment by BAndysc** [comment]
@Angelo-DM- 
I have used this issue as my notes to mark quests I have scripted already :D But of course I have waited to commit the fix until I finished all quests.
So with [rev 4913](http://atlantiss.eu/changelog#rev4913) it should work flawlessly now.

Now the only missing quests are Plants Vs Zombies which I am going to script as well

**Comment by Angelo-DM-** [comment]
:+1: ty @BAndysc! :smile:
i've writed that the quest was bugged becouse i've not noticed in the changelog that only "Master of Loyalty" was up as fix! my bad!
Thank you for your awesome work! :heart:

**Comment by BAndysc** [comment]
I will close the issue, because Plants vs Zombies have separate one

**Comment by joelpro2** [comment]
@BAndysc 
[Breaking The Hand (ID: 28556)](http://www.wowhead.com/quest=28556/breaking-the-hand)
this quest appears unchecked and its bugged. I can't place the bomb on any of the 4 fingers
