### ISSUE TITLE
[EN][Core]Unable to kick Bad Manner (aka Monkey Blind)

### ISSUE THREAD

**Issue by RhythmOfficial** [Atlantiss/BugTracker#6524]
You're unable to kick Bad Manner the spell cast fom a hunter's monkey pet that disorients you for 4 seconds.

You should be able to interupt this cast it is litterally impossible right now.

**Comment by kadi2** [comment]
Its supposed to be naturę school

**Comment by RhythmOfficial** [comment]
@kadi2

what do you even mean? it is nature school, what tf does that sentence mean rofl.

you should be able to kick this spell as it is a casted spell similair to Mass Dispell.
It was doable on retail, AT and many other private servers.

**Comment by kadi2** [comment]
Did you really Play the same game as we do?

**Comment by RhythmOfficial** [comment]
@kadi2 
No i wasn't stuck at the 1300 rating like you, because it seems like you know nothing about game mechanics.

**Comment by Zhalox123** [comment]
Confirmed Bad manner was always interruptable on cast.

**Comment by Crusaderz** [comment]
https://github.com/Atlantiss/BugTracker/issues/3187 duplicate
