### ISSUE TITLE
[EN][Achievement][Love is in the Air] The Rocket's Pink Glare

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#6526]
Shoot off 10 Love rockets in 20 seconds or Less

---------------------------------------------------------------------]

This is not obtainable on alliance side apparently I and others in my guild have tried this on separate occasions with a stopwatch.  However I have seen Horde players get the achievement in Dalaran.

**Comment by Sayris9876** [comment]
Horde here and i confirm for horde it works fine no issues with any of the event achievements

**Comment by Aldergar** [comment]
I completed it without any problems on Alliance side.

**Comment by Luna-maria** [comment]
I've gotten this achievement a couple of days ago on Alliance side with no issues as well

**Comment by morgs71** [comment]
I have done it multiple time as with others in guild anything special you did to get it to work ?

**Comment by morgs71** [comment]
Ok just tried again and it worked this time.  Thank you !
