### ISSUE TITLE
[PL][Core][Hunter][Rogue] Energy/Focus Regen - Haste Debuff.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6528]
Jak jest:
Debuff zmniejszające Haste(np. Thunder Clap), powinny zmniejszyć regenerację Focus/Energy.
Ciekawe jest to że jak coś Buffuje Haste(np. Bloodlust) to Regeneracja Focus/Energy jest zwiększona na na odwrót już nie.

Jak powinno być:
Głownie rozchodzi mi się tu o PvP gdzie jest to poważny bug.
Postać z Rage dostając Haste Debuff generuje mniej Rage bo wolniej atakuje i na odwrót jak dostnie Buff.
Postać z Energią powinna działać tak samo.

Dowody:
http://us.battle.net/wow/en/forum/topic/2416193981 (warto całość przeczytać co drugi Hunt o tym pisze)
"Slow doesnt affect a caster or healers resource. It does mine.
I have less focus to work with, and less ability to gain it.
My steady shot is normally 1.4 seconds to cast for 9 focus. With slow on me its a 2.3 second cast."

http://www.gamefaqs.com/boards/534914-world-of-warcraft/62837396
"Thunderclap slows passive energy regen, slow the cast of Steady Shot, white attack of warriors (therefore slows rage regen) and such. Demo shout does exactly what it says, so it's useful too."

https://github.com/Atlantiss/BugTracker/issues/2039 tutaj jeszcze użytkownik Tj20 dał dobry dowód wraz z filmik, widać ze działa to tez w PvE ale tak jak napisałem bardziej mi tu chodzi o Bug dotyczący PvP i Skill takich jak Thunder Clap, Infected Wounds itd.

https://github.com/Atlantiss/BugTracker/issues/3184
Tutaj poprzednie zgłoszenia które możliwe że to popsuły.

Jak coś to nie jest żaden visual, Feral z 0 energi do 100 musiał czekać 10 sec, i z Thunder Clapem to samo tez 10 sec.

Jak to wygląda u nas:
![wowscrnshot_022216_045451](https://cloud.githubusercontent.com/assets/5780624/13209634/99cc5df0-d926-11e5-98ce-43d021b6c5e8.jpg)
![wowscrnshot_022216_053748](https://cloud.githubusercontent.com/assets/5780624/13209633/9781f154-d926-11e5-9669-6a12f9393c46.jpg)

**Comment by BialyADI** [comment]
Some one is here ;x?

**Comment by Wolffenstein** [comment]
No dobra, ale 10 energii/sec to jest bazowy regen, gdzie dowód na to, że slowy czy cokolwiek innego powinno zmniejszać regen energii PONIŻEJ bazowego?

**Comment by BialyADI** [comment]
Chociżby tutaj https://github.com/Atlantiss/BugTracker/issues/2039 jeśli chodzi o Hunty.

**Comment by BialyADI** [comment]
asa

**Comment by BialyADI** [comment]
A na PvE się nie znam ale pewnie też bo jeśli daje jakiś Bos tak jak na filmiku z #2039 redukcję Haste to Dps inny postaci jak Warek(mniej generuje Rage bo mniej auto atakow) u Maga też bo wolniej castuje.
Natomiast postacie z Energią maja teraz w dupie Redukcje Haste bo dziala tylko na ich Auto attack a z skili naperdzela dalej.

**Comment by BialyADI** [comment]
Jeszcze jeden dowód znalazlem:
https://youtu.be/QiVOOV8R-kI?t=3m4s
Widać na początku że Hunter ma zwiększony Regen Focus od Buffa Altairusa.
Następnie w 3:09 dostał Debuff -75% Haste i widać ze Regeneracja Focusa praktycznie stanęła w miejscu mimo że filmik jest przyśpieszony.

**Comment by krojo** [comment]
Ten filmik który wrzuciłeś to dobrze pokazuje co robi HAST( zwiększa szybkość regania energy ) a nie  SLOW ATTACK SPEED , ziooom użyj mózgu.

**Comment by BialyADI** [comment]
No jasne że zwiększa a Debuff zmniejsza.

**Comment by krojo** [comment]
człowieku ty nie wiesz co mowisz , nie rozumiesz zasady

 Hast ( Attack Speed , Casting Speed , Energy Regen , Rune Regen )

Juz ci rozpisałem na co działa HAST a nie Attack Speed itp. Redukując Attack Speed Nie zmniejszysz Hast no bo jak?? powiedz mi. Daje Ci np Slow z Thunderclapa ( -20% Attack Speed ) <--- Gdzie tu pisze HAST???????

Az Szkoda tłumaczyć

**Comment by BialyADI** [comment]
To tobie trzeba tłumaczyć, nie wiem czy grałeś na Retailu ale tak to działało i pewno nadal działa tak jak opisałem to w Tickecie.
Zresztą potwierdzają to tematy na Blizzardowskich forach gidzie ludzie o tym piszą.

**Comment by krojo** [comment]
to idac takim tokiem rozumowania Mag dostanie Thunderclapa to zredukuje mu to i cast bo redukuje hast.

Znajdź Dowody to ktoś może ci uwierzy. Gadanie zwykłych plebów na forum blizza to żaden dowód.

**Comment by BialyADI** [comment]
Mylisz się a Bug jest poważny, kiedyś to działało na Atlantissie popranie jak wcześniej tu grałem w 2013/2014 tylko zostało to popsute przy okazji naprawy innych bugów z Energią.

**Comment by BialyADI** [comment]
hnj

**Comment by tnarf** [comment]
Tak jak pisze Krojo coś co zmienia ATACK SPEED nie powinno mieć żadnego wpływu na regen energii (np SnD rogala)
Ale problem polega na tym że Blizz sporo namieszał w niektórych tooltipach i tam gdzie powinien napisać "haste"/"melee haste"/"ranged haste"/"spell haste" (które zapisy jasno by mówiły o co biega) napisał "atack speed" lub "casting speed" (o ile się nie mylę ma to miejsce np w tooltipach BL'a,Hero,TW o których powszechnie wiadomo że zmieniają regen)

Co do Thunder Clapa i energii u rogala:
https://www.youtube.com/watch?v=XJ0LxoyinoM
wg daty jeszcze cata
(czas z przecinkiem brany z "Dane dla nerdów"; prędkość wygląda na rzeczywistą)
1:15 dostaje Thunder Clapa
1.czas -- energia
93,857 -- 7
99,778 -- 70
(pomiędzy nie używa skili; klika hemo ale wg debufow i energii się nie odpala)
1:45 wygrywa duel przez co schodzą debufy (TC zszedł ms przed końcem duelu)
2.czas -- energia
105,855 -- 35
112,54 -- 105
Czyli 1. pod wpływem TC a 2. bez wpływu
1. E/s: 10,64 = (70-7)/(99,778-93,857)
2. E/s: 10,47 = (105-35)/(112,54-105,855)
Różnica na poziomie 1,7% na korzyść sytuacji z TC zapewne wynikać z tego że:
TC NIE WPŁYWA na regen energii, na globie też jest diff i nagranie jak każde nagranie nie jest w 100% płynne (poza tym możliwe że nerdowski tooltip yt ma pewne błędy)

**Comment by Jenovas** [comment]
Z filmiku wyżej https://www.youtube.com/watch?v=XJ0LxoyinoM jasno wynika że thunder clap nie powinien zmniejszać regenu. Jeżeli jest jeszcze jakiś bug proszę zrobić osobne zgłoszenie od tego.
Zamykam.

**Comment by BialyADI** [comment]
Co prawda mniej mnie interesuje PvE ale co z Debuffa Altairusa -75% Haste?
Czemu on nie zmniejsza Regeneracji mimo że Buff zwiększa dział to tylko w jedna stronę.
