### ISSUE TITLE
[eng][transfer][account] Transfers of the Sunwell doesn't work correctly

### ISSUE THREAD

**Issue by themadman3** [Atlantiss/BugTracker#6532]
namely, when i'm creating new first level character, with the same rase and gender as it was on a sunwell, the transfer wizard does not see this character. It says "Currently you have no characters on our server which would conform any of characters mentioned above (remember that the characters on our server need to have level 1)". 
![transfers](https://cloud.githubusercontent.com/assets/17410469/13223489/b22b8444-d984-11e5-8c6a-50f6ae128dd7.jpg)

**Comment by artamedan** [comment]
Delete the char you created. Exit the game totally. Delete your Cache folder. Log in and create new level 1 char. Do it one by one, not all 5 possible at once.

**Comment by themadman3** [comment]
unfortunately doesn't work. I did it all earlier, and again step by step - I've deleted chars then logged out and deleted cache. After that i've created one new char, logged out then i logged in on sunwell transfers, and it's still the same.

**Comment by Bastek** [comment]
http://atlantiss.eu/account/sunwell

**Comment by themadman3** [comment]
I did all of that. It doesnt work. I've created a new first lvl char with the same race class and gender as it was on sunwell.

**Comment by Bastek** [comment]
Character's race at Atlantiss is different than on Sunwell.
