### ISSUE TITLE
[EN][Spell][Priest] Devouring Pleague (Very low dmg)

### ISSUE THREAD

**Issue by janchux** [Atlantiss/BugTracker#6538]
Problem with Devouring Plague. Too low damage.
I noticed these mystical "1" when I'm doing DPS I assumed they were caused by Shadowy apparitions but DP was the one to blame.

I did a test on a dummy:
8 million total damage
217 tick of Devouring Plague = 4387 total damage from dot.

![dp bug](https://cloud.githubusercontent.com/assets/17173602/13235034/779a6da0-d9c4-11e5-8687-170ad3c5470a.jpg)

**Comment by BialyADI** [comment]
DV doing normal Dmg, you was hiting dummy?

**Comment by RandomPickNewb** [comment]
You used devouring plague on the low hp dummy which will go down to 1 hp after some time.Devouring plague dmg cannot exceed the hp of a mod so you got that 1 dmg.Yeah yeah i know that you have the target on the heroic dummy but that is how devouring plague acts on the low hp dummy.
