### ISSUE TITLE
[EN][PTR][Battleground][PvP] Strand of the Ancients PTR

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#6539]
- Basically ship is bugged at start while it's still standing, unless you move you will drop in water, but when it started moving and you enter battleground while it's already on the move it's pretty fine, just probably you should be on the upper part of the ship instead inside it in lower. 
  If you disconnected at the time ship was already swimming you'll most likely respawn in water. - all of this works better but still needs some more testing
- Turrets can be cc'd by silence and ex. hunter freezing trap.
- Demolishers have no passenger seats
- One of the ships (dark model) stops with board higher than the pier

additional thanks to Bialy and Naguceł @ Discord for help finding these bugs

**Comment by BialyADI** [comment]
And Bombs you can plant them in the Gate so no one can defuse them.

**Comment by xmesaj2** [comment]
The Teleporters on defense should teleport players based on which line of gates have been destroyed, rather than directly behind that gate. For example, if a player clicks the Teleporter at the Blue gate when one of the beach gates has been destroyed, it will put the player behind the Red gate.

**Comment by Snacky1** [comment]
Also adding on to this, at the beginning of the game sometimes the horde sign pops up in the middle of the screen every 10 seconds or so, ex http://i.imgur.com/fZHKadK.jpg

I haven't done this bg on alliance so it may happen to alliance too.

**Comment by blinkmaster** [comment]
So basically it works like when it was disabled.

**Comment by Aldergar** [comment]
@Snacky1 happened also as ally
