### ISSUE TITLE
[EN][Spell][Druid] Ferocious Bite

### ISSUE THREAD

**Issue by Mordorianin** [Atlantiss/BugTracker#6540]
Ferocious Bite when berserk is active is consuming right energy (-50%) for the base cost, but is taking wrong energy to the additional dmg (+100% as it says in a talent description) without -50% - berserk is just dont affecting it. It means u can do 2 FBs and ur out of energy while berserked. Doing a burst with feral dudu without heroism in pve is just  impossible right now cause of that issue.

http://wow.gamepedia.com/Ferocious_Bite
http://wow.gamepedia.com/Berserk

**Comment by BialyADI** [comment]
It only decrease base Cost, like Warrior Deadly Calm.

**Comment by freddie12** [comment]
I agree on this. It's just impossible do a burst without heroism.

**Comment by Jenovas** [comment]
This is how it should work. Only the base cost is reduced by 50%.
Closing.
