### ISSUE TITLE
[EN][Item][Undercity Satchel]

### ISSUE THREAD

**Issue by CSLooney** [Atlantiss/BugTracker#6543]
http://www.wowhead.com/item=67529/undercity-satchel

After buying the Undercity I attempted to equip it, I received the message, "Unable to Equip this item". I double-checked to make sure I did not have this item on my character or in my bank but did not find another. I attempted clearing a back slot to attempt to equip it automatically, and tried dragging and dropping it to the bag spot I wished it to be in. Nothing worked. 

I attempted logging off, then back on, and discarding it, and buying a new one, neither of these worked.

**Comment by Anhaeyn** [comment]
"Requires Undercity - Revered" 
Are you revered with Undercity?
