### ISSUE TITLE
Problem with item stats

### ISSUE THREAD

**Issue by mikakusek135** [Atlantiss/BugTracker#6545]
I have a problem, when i click inspect on someone and i want to check the stats of item the window disapear after 0.1s

**Comment by stanq87** [comment]
tryout addon ratingbuster

**Comment by mikakusek135** [comment]
it's not working, window also disapear after 0.1s

**Comment by tnarf** [comment]
maybe delete cache or WTF (this one backup because addons settings etc)

**Comment by mikakusek135** [comment]
Ok, it works, thanks a lot :) subject closed

**Comment by mikakusek135** [comment]
worked but only ones, when i log out it hepened again

**Comment by Wolffenstein** [comment]
It's one of your addons, not a server issue.
