### ISSUE TITLE
[PL][Achievement] A Silver Confidant

### ISSUE THREAD

**Issue by jacula666** [Atlantiss/BugTracker#6546]
Achievement  [A Silver Confidant](http://www.wowhead.com/achievement=3676/a-silver-confidant) powinien odblokowywać dostęp do nowych daily q od następujących NPC:
**[Narasi Snowdawn](http://www.wowhead.com/npc=34880/narasi-snowdawn):**
[A Leg Up](http://www.wowhead.com/quest=14074/a-leg-up)
[Rescue at Sea](http://www.wowhead.com/quest=14152/rescue-at-sea)
[Stop The Agressors](http://www.wowhead.com/quest=14080/stop-the-aggressors)
[The Light's Mercy](http://www.wowhead.com/quest=14077/the-lights-mercy)
[You've Really Done It This Time, Kul](http://www.wowhead.com/quest=14096/youve-really-done-it-this-time-kul)

**[Savinia Loresong](http://www.wowhead.com/npc=34912/savinia-loresong):**
[Breakfast Of Champions](http://www.wowhead.com/quest=14076/breakfast-of-champions)
[Gormok Wants His Snobolds](http://www.wowhead.com/quest=14090/gormok-wants-his-snobolds)
[What Do You Feed a Yeti, Anyway?](http://www.wowhead.com/quest=14112/what-do-you-feed-a-yeti-anyway)

Dowód: Sam achievement [A Silver Confidant](http://www.wowhead.com/achievement=3676/a-silver-confidant): "_**Unlocks Silver Covenant dailies at the Argent Tournament**_.", a gdyby ktoś miał jeszcze jakieś wątpliwości, pierwszy komentarz pod nim http://www.wowhead.com/achievement=3676/a-silver-confidant#comments

Niestety na Atlantissie po wykonaniu tego Achivementu, nadal nie ma dostępu do ww. q. 

Pozdrawiam

**Comment by Aviannaqt** [comment]
#2239
