### ISSUE TITLE
[PL][Spell][Hunter] Silencing Shot (Travel Time)

### ISSUE THREAD

**Issue by jodvi** [Atlantiss/BugTracker#6547]
Silence powinien zadziałać natychmiastowo w momencie jego użycia. Bug polega na tym, że działa dopiero gdy strzała doleci do celu.
http://cata.openwow.com/spell=34490

Źródła:
https://github.com/trinitycore/trinitycore/issues/6550
http://us.battle.net/wow/en/forum/topic/18301005591

**Comment by Jenovas** [comment]
Fixed

**Comment by jodvi** [comment]
Silencing Shot nadal nie działa poprawnie. Teraz **przerywa** cast natychmiast po użyciu, natomiast sam **silence** jest nadal (niepoprawnie) nakładany dopiero gdy strzała doleci do celu. 

To bezsensu, **przerwanie** jest rezultatem działania **silenca**, a teraz mamy instantowy **interrupt**, a po dotarciu strzały do przeciwnika **silence**.

Powinny to działać tak: instantowy **silence** i tyle, ni mniej, ni więcej. Nie ma żadnego odrębnego **interrupta**.

**Comment by lamaATS** [comment]
Spell posiada właśnie dwa efekty **Interrupt** i **Silence** oraz **Silence Shot** jest jedynym (chyba) spellem na odległość który posiada efekt **Interrupt** oraz wizualnie się poruszą.
Tutaj https://youtu.be/UwL--2H13EM?t=538 można zauważyć że spell zostaje przerwany dużo wcześniej niż pojawia się efekt **Silence** prawdopodobnie blizz tego przypadku nie sprawdził dokładnie bo jest to ewenement i tyle.

Przepraszam że nie napisałem tego jak robiłem poprawkę żeby działało jak teraz działa.
