### ISSUE TITLE
[PL][quest]DEATH COMES FROM ON HIGH

### ISSUE THREAD

**Issue by Grawitacja** [Atlantiss/BugTracker#6551]
Po zaakceptowaniu questa http://www.wowhead.com/quest=12641/death-comes-from-on-high wyrzucilo mnie z servera. Po zalogowaniu odkryłem, że nie jestem orbem, którym być powinienem, a dodatkowo mam niezdejmowalnego buffa http://www.wowhead.com/quest=12636/the-eye-of-acherus
Mając tego buffa nie widzę żadnych npc, nie mogę przechodzić między piętrami, nie mogę się teleportować - ogólnie jestem zablokowany. 
Nie założę nowego z uwagi na to, że ten jest przetransferowany i akurat nim chciałem grać najwięcej. Napisałem ticketa w grze z prośbą o zabicie mnie(to powinno ściągnąć problematycznego buffa).

**Comment by Aviannaqt** [comment]
#877
