### ISSUE TITLE
[EN][Quest][Dragonblight]A Fall From Grace

### ISSUE THREAD

**Issue by kondor1992** [Atlantiss/BugTracker#6554]
Quest doesn't work. There is no dialogue option with Abbot.
Link: http://www.wowhead.com/quest=12274/a-fall-from-grace

**Comment by diurdor** [comment]
By killing his guards, there is a dialogue option with Abbot. He does however not teleport outside the abbey and hence the quest cannot be completed.

**Comment by stanq87** [comment]
after u kill the guards u can talk to the abbot and he does tp and  leadd u  where he should but after the quest objective is done u cant turn the quest in

**Comment by rwystop** [comment]
its not working like this.. you should use ring bell then guards should come up and abbey should be alone
