### ISSUE TITLE
[EN][NPC][Vortex Pinnacle] Young Storm Dragon doesn't want to move out

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker#6555]
The NPC Young Storm Dragon (http://www.wowhead.com/npc=45919/young-storm-dragon) only moves out of the healing well it casts (http://www.wowhead.com/spell=88201/healing-well), when the tank is very far away from the NPC.

How it should work: As the tank moves away from the NPC, it should follow the tank and get to melee range of the tank at all times, regardless of the distance between the NPC and the tank, like it happens normally on every other NPC.

Proof: https://youtu.be/oY9jDwxx2k4?t=3m27s (at 3m 27s) you see the NPC moving out of the healing well. The same happens at 4m 25s of the same video.

Edited as to confirm what Fapguy commented below.

**Comment by Fapguy** [comment]
The dragon DOES move, but you need to move very far.

This is a hitbox/pathing? issue

**Comment by ahtebe** [comment]
It should still try to get into melee range of the tank, no matter how far (or close) away it is pulled away from the healing well, and not just decide to come at an arbitrary distance.

**Comment by Fapguy** [comment]
No, I mean, the hitbox is massive.
You can stand very far away and still be able to hit it. The melee range is massive, so you have to almost go to the other end of the room.

**Comment by ahtebe** [comment]
Oh okay, I get it now.

**Comment by ahtebe** [comment]
You know, this bug still exists. When I get more evidence of it being an actual hitbox issue I'll open a new issue.

But regardless, the NPC still isn't behaving properly as it should.

**Comment by ahtebe** [comment]
Edited issue to confirm what Fapguy commented above.

**Comment by ahtebe** [comment]
Somehow, I am no longer having this issue. Tested on multiple occasions. I will close it.
