### ISSUE TITLE
[PL][NPC][Spell] Zanzili Fire

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#6558]
Umiejętność Zanzil'a na Zul'Gurub Zanzili Fire ma większy hitbox niż powinna mieć przez co uniknięcie jej jest o wiele trudniejsze niż powinno. http://www.wowhead.com/spell=96914/zanzili-fire

**Comment by Lebiedz** [comment]
Dodatkowo, nie da sie przewidzieć w która stronę Zanzil wypuści te płomienie. Obraca się w którąś stronę w trakcie castu, jednak płomienie idą w zupełnie dowolną, nawet za jego plecy.
