### ISSUE TITLE
low dps

### ISSUE THREAD

**Issue by groumulous** [Atlantiss/BugTracker#6562]
User: Groumulous
Mage: Elfin
Level 85 Mage has all but 2 epic items, full enchants, full glyphs, full gems, etc.  Dps exceptionallly low.  Other players say their addons report my dbs to be between 4k and 7k.  Unable to qualify for random raids even though gear is all maxed out.  Almost nothing else to upgrade.  Doing less damage than some level 83 characters in dungeons.

**Comment by stanq87** [comment]
sooooo what is your issue ? go cry on the forums, btw whats your ilvl ? fire arcane ?  caps ?  rotation  ? enchants ?  gems  ?

**Comment by ponpontos** [comment]
Stop playing arcane.
