### ISSUE TITLE
[EN]/[PL][Quest][Desolace] Gelkis Alliance

### ISSUE THREAD

**Issue by tomq523** [Atlantiss/BugTracker#6563]
I don't know what's happening.
What about that quest? I don't see Uthek the Wise. This is NPC which could start a new quest chain. 
Link for mission : http://www.wowhead.com/quest=1368/gelkis-alliance
Link for Uthek the Wise : http://www.wowhead.com/npc=5397/uthek-the-wise 
ScreenShot from my account : http://images78.fotosik.pl/362/156679a357dd60aa.jpg
What about that ?

**Comment by tomq523** [comment]
- [ ] 

- ``

**Comment by Aviannaqt** [comment]
That chain was deleted in cataclysm
