### ISSUE TITLE
[EN][Achievement][Firelands] Share the Pain

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#6564]
http://www.wowhead.com/achievement=5830/share-the-pain

Achievement is bugged.

We did it today, no one got the debuff more than 3 times (not even more than 2 times I think), but no achievement was granted.

**Comment by sohussain** [comment]
Not sure, my guild got this achievement last week.

**Comment by LaveniaGithub** [comment]
It was definitely bugged yesterday. I dont know if it only happens sometimes

**Comment by xolon** [comment]
Lave its just a bad luck ;))

**Comment by LaveniaGithub** [comment]
@xolon Yea right, kappa kappa (=

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4950
