### ISSUE TITLE
[PL][DK]Rime

### ISSUE THREAD

**Issue by Moks** [Atlantiss/BugTracker#6565]
Link do talentu dk frosta: 
http://cata.openwow.com/spell=49188
http://cata.openwow.com/spell=49188
http://cata.openwow.com/spell=49188 

Powyższy talent uruchamia aurę Freezing Fog: http://www.wowdb.com/spells/59052-freezing-fog ,która daje możliwość użycia umiejętności Icy Touch :http://cata.openwow.com/spell=45477 oraz Howling Blast: http://cata.openwow.com/spell=49184.
Opis aury Freezing Fog: 
Your next Icy Touch or Howling Blast will consume no runes and generate no Runic Power.
15 seconds remaining

Zarówno Icy Touch jak i  Howling Blast generują energie runowa podczas buffa z talentu Rime.

**Comment by BialyADI** [comment]
Generują tylko 10 z innego talentu.

**Comment by Kejmil** [comment]
^
do zamkniecia

**Comment by Jenovas** [comment]
Jest talent który powoduje że wyżej wymienione skille dają 10 runic powera więcej niż powinny.
Tak więc jak robisz zwykły cast dostajesz 20 zamiast 10, a jak robisz darmowy cast dostajesz 10 zamiast 0. Jest to poprawne działanie.

**Comment by Moks** [comment]
Właśnie popatrzałem i jest to mój błąd po prostu pamiętam, że ta umiejętność nie generowała mocy runicznej  na dodatku MOP a właśnie wtedy grałem ostatnio DK.
Widzę, że działanie jest inne właśnie przez ten talent Chill of the Grave, którego na Mop już nie ma.

 Moje nie dopatrzenie sorry ze zawracałem głowę.
