### ISSUE TITLE
[EN][PVP] Arena rating broken broken broken...

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#6566]
It's pretty self-explanatory:
![image](https://cloud.githubusercontent.com/assets/9639063/13305234/88122bd8-db62-11e5-9876-6bd9d3752ede.png)

Enemy team receives 96 rating upon win with 1600 MMR whereas we win 10 rating beating 2,3k MMRs on our other team that's barely 1,9k MMR. Bugged beyond words...

**Comment by BialyADI** [comment]
They have team with 1k rate probably or less.

**Comment by aneq** [comment]
The thing that is self-explainatory is your lack of knowledge of how arena and mmr system works.
If their team rating is lower than their matchmaking rating (MMR) and they win against a team that has higher MMR they get +96.

**Comment by captjvmoore** [comment]
@aneq This happens never :) I have made 2 new teams on my characters for a the last couple of weeks. Anything pass 1,4k is like 20 or less, never 96. Plus, I've seen Larcan's team (hunter/rogue), who are 2,3k+ kick our asses #noskill #carriedbyclass and still get 96+. Sadly I broke my keyboard raging and didn't manage to screenshot that.

**Comment by debtheone** [comment]
''Sadly I broke my keyboard raging and didn't manage to screenshot that". XDXP

**Comment by Aviannaqt** [comment]
+1 :D
