### ISSUE TITLE
[EN][Item]  Arcanum of the Earthen Ring

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#6568]
this item http://www.wowhead.com/item=62366/arcanum-of-the-earthen-ring#comments
when you buy it and sell to another char it still needs on the other char the reprutation requirement, and on wowhead it says it has been fixed and doesnt need it

**Comment by NatsumeLily** [comment]
All Cata faction enchants are like this.

**Comment by tkupcewicz** [comment]
> Patch 4.0.6 (8-Feb-2011): New Item Id for arcanums sold from Quartermaster. Now changed to not require reputation to apply as enchantment however still needed to purchase. Old items purchased with rep requirement will retain it.

ID of item sold by NPC has to be changed

**Comment by Piklo** [comment]
#682
