### ISSUE TITLE
[EN][Ingame Account]

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6569]
I can not log in on the server with the new account I created. I receive the error message " The information you have entered is not valid. Please check the spelling of the account name and password. If you need help in retrieving a lost or stolen password and account, see http://www.wow-europe/login.support for more information".
I made sure I log in with the correct account information.
Also, I made this account more than two weeks ago and I was able to log in on the website ever since. However I was not able to log in to play on the server.
Please make a new account and test if you get the same error.

**Comment by user1011** [comment]
Works fine for me.

**Comment by Aldurion** [comment]
I believe I have figured out what is the problem. I can't log in on the server if I have a password longer than 16 characters but I can log in on the website. You should implement some function to limit the characters put in the pasword or something similar or else people will make accounts for nothing.
