### ISSUE TITLE
[EN][Warrior][Fury]Mastery

### ISSUE THREAD

**Issue by Zengetsu88** [Atlantiss/BugTracker#6570]
mastery is not giving proper bonus for some skills 

![untitled](https://cloud.githubusercontent.com/assets/17097476/13320710/e185cdc6-dbf0-11e5-85b7-f37d462c9d0e.png)
![untitled1](https://cloud.githubusercontent.com/assets/17097476/13320711/e187056a-dbf0-11e5-964e-d844801190f4.png)

**Comment by Zengetsu88** [comment]
and i am sure its same with deathwish skill

**Comment by BialyADI** [comment]
It is only visual, just test The Dmg no Buff Tooltip ;x.

**Comment by Zengetsu88** [comment]
i did the calculations its not giving the 6%dmg

**Comment by BialyADI** [comment]
So do respec/relog Mastery Work normaly.

**Comment by Zengetsu88** [comment]
i did that but still i am not getting that 16% dmg i keep getting lower than that

**Comment by Zengetsu88** [comment]
this is with out death wish and with it check the dmg 
![untitled2](https://cloud.githubusercontent.com/assets/17097476/13321849/83ab2bc2-dbf7-11e5-9ab7-0a62a51e03af.png)
![untitled4](https://cloud.githubusercontent.com/assets/17097476/13321857/905a3ec6-dbf7-11e5-908b-38d887568e51.png)

deathwish should give me 32% dmg  increase but it doesnt same with enrage do let me know if i am wrong or not

**Comment by aneq** [comment]
do you count armor in your calculations?

**Comment by Zengetsu88** [comment]
shouldn't deathwish increase the dmg i already have witch is 5066-6055 x32%  and what does armor have anything to do with this ??  these skills don't increase atk power just dmg mult

**Comment by BialyADI** [comment]
Just test it on Bloodthirst all warks fine.

**Comment by Zengetsu88** [comment]
well did u even check the pics i posted u clearly can see that i am not getting 32% dmg on my auto atks

**Comment by BialyADI** [comment]
It is only Kurwa Character Info, check The Dmg :D.
What a moron.

**Comment by Zengetsu88** [comment]
kindly go fuck ur self ty

**Comment by BialyADI** [comment]
Ok xD.
