### ISSUE TITLE
Neutral Guards Bug

### ISSUE THREAD

**Issue by Valoiz** [Atlantiss/BugTracker#6573]
I Think Neutral Guards are Bug. For example the ones from the Argent Crusade, Guards of Hyjal, Goblins, etc Aren´t they supose to do something (agro) when someone engage pvp on their zones?

For example: Argent Sentry <The Argent Crusade>

http://www.wowhead.com/npc=16378/argent-sentry

The wowhead comments say stuff like: "These are the end-all of guards in the game. Nothing comes close to the sheer magnitude of defense at Light's Hope Chapel. Engaging in PvP here is suicide. You will be instantly stunned by 20 guards from 40 yards away. You will die. You cannot do anything, you cannot heal through them, you cannot run away, you cannot out range them."

But here ppl kill u over and over and they dont do anything.

Same for  Hyjal- Is a Farm fest due the NPCs doing nothing
Warden http://www.wowhead.com/npc=38915/hyjal-warden
http://www.wowhead.com/npc=43427/furious-hyjal-warden#abilities
http://www.wowhead.com/npc=53805/ystelle-oaksong#comments

Even Gadgetzan Bruiser and similars on many areas, in some camps they engage but do no significant dmg

http://www.wowhead.com/npc=9460/gadgetzan-bruiser#comments

http://www.wowhead.com/npc=48075/fuselight-bruiser#comments

**Comment by Bildo** [comment]
bt rules
