### ISSUE TITLE
Flying Obsidium deposit

### ISSUE THREAD

**Issue by ragabasz** [Atlantiss/BugTracker#6575]
Flying Obsidium deposit in Mount Hyjal
https://imgur.com/I0UwlmM

**Comment by stanq87** [comment]
u didnt seen noting yet, ive seen flying areology  nodes and fishchool's in mid air

**Comment by Kejmil** [comment]
gj, you didn't even added coords...

**Comment by Bildo** [comment]
bt rules

**Comment by stanq87** [comment]
one flying fish school is just above the lake in the start zone of MH, seen a couple more in TH,

**Comment by Bildo** [comment]
Who said about any proofs? You just didn't follow the bug tracker rules that's why it was closed.
