### ISSUE TITLE
[EN][QUEST][TBC][A Crystalforged Darkrune]

### ISSUE THREAD

**Issue by magion342** [Atlantiss/BugTracker#6576]
Hello
when they reach honored reputation with a faction Ogri'la get a backpack in the backpack should be the quest item " darkrune " but the backpack is empty . So we do not have to give up the task
link: http://www.wowhead.com/quest=11060/a-crystalforged-darkrune

**Comment by Aival94** [comment]
Quest seems to have been removed from game during 4.2 patch because it was bugged from the beginning of Cataclysm.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11659-6576questtbca-crystalforged-darkruneadd-loot-kronks-grab-bag/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
