### ISSUE TITLE
[PL] [BOSS] [Emperor Vek'nilash]

### ISSUE THREAD

**Issue by jasiek21** [Atlantiss/BugTracker#6578]
Witam,
Wyzej wymieniony boss z AQ powinien miec 100% szansy na drop quest itemu "Vek'nilash's Circlet" 

http://www.wowhead.com/item=20926/veknilashs-circlet

który jest potrzebny do questu "Conqueror's Crown"

http://www.wowhead.com/quest=8561/conquerors-crown

Owy quest posiadam, Bossa zabiłem kilka razy, jednak ani razu nie padł mi quest item potrzebny do zakonczenia questu.
Reszta quest itemów do reszty questow dropi bez problemu z pozostalych bossow. Jednak z tym jest problem. Co sprawia, ze obecnie mozemy zdobyc tylko 4/5 t2.5 na naszym serwerze.
Bardzo proszę o naprawe dropu, i z góry dziękuje.
Jesli dziala poprawnie to proszę chociaz o sprawdzenie drop rate'u.

**Comment by Aviannaqt** [comment]
#4531
