### ISSUE TITLE
[EN][Druid][Spell] Skull Bash

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#658]
http://cata.openwow.com/spell=80965
http://cata.openwow.com/spell=80964

both cat and bear form. I tested it only on mobs so i'm not sure if on players is the same, anyway when you use skull bash you can interrupt the spellcasting but the mob don't get the 4 sec lockout.

**Comment by rootowsky** [comment]
There is also important bug. You can skull bash your enemy from a distance while frozen (dont know about roots)

**Comment by knasen88** [comment]
http://gfycat.com/JaggedOrnateEarwig

you should change title to all interrupt based spells since this is a core issue. It doesn't lock out from schools

**Comment by Malylolek** [comment]
#7897  go ther couse now i dont know it bug or not.
