### ISSUE TITLE
[EN][Spell][Death Knight] Summon Gargoyle

### ISSUE THREAD

**Issue by freddie12** [Atlantiss/BugTracker#6581]
Hello, the spell "Summon Gargoyle" should take a snapshot of player's stats when the player summons a gargoyle. However, in Atlantiss, gargoyle's attacks weaken just after buffs fade away. 

Here are some links about the issue:
http://www.wowhead.com/spell=49206/summon-gargoyle
https://www.youtube.com/watch?v=u3mXQtOesMI

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/825
