### ISSUE TITLE
[en] [ability] [rogue] Tricks of the Trade sometimes unable to be used

### ISSUE THREAD

**Issue by RhythmOfficial** [Atlantiss/BugTracker#6586]
When I use tricks of the trade it sometimes grays out and I am unable to use it.
It just says : Ability is on not ready yet. when it clearly is it is just grayed out.
This is very annyoing in raids and arenas and would like to ask if you guys could fix this asap.

Also when you change the option in your interface to custom lag tolerance 0 ms, as your "FIX"  to this problem which doesn't do anything at all.
The bug still exists and changing your custom lag tolerance doesn't do anything, so please fix this bug it is annoying as hell.

**Comment by RhythmOfficial** [comment]
And you're closing it because it is fixed?
Because it is not...
So just reply with something saying like this has been reported and is being worked on to be fixed, don't just fucking close it and link me some polish post that i cant read at all.

And I thought this server would have helpfull devs....

@Jenovas

**Comment by Jenovas** [comment]
Please try searching before you create duplicates. https://github.com/Atlantiss/BugTracker/issues/5299
[EN]
Very often tott's cd doesn't disapear.
Probably becous Rev 4714

**Comment by RhythmOfficial** [comment]
Stop closing bugs saying that they are fixed when they are not, I played arround 15 arena matches 2 days ago, almost every arena match this bugged out.
so stop saying that it is fixed when it is not.

**Comment by RhythmOfficial** [comment]
> > Please try searching before you create duplicates. #5299
> [EN]
> Very often tott's cd doesn't disapear.
> Probably becous Rev 4714
> 
> PS - it's not Polish, just try searching, it's not that hard.

Hmmmm amazing search, now if you would actually have the brain capacity to understand english.
You would be able to understand what I was saying in my report, but since you don't let me put a couple of whitemarks and all caps in there so you can understand it ;).




GOING TO UR INTERFACE > COMBAT AND REDUCING THE SPELL LATENCY TO 0 DOESN'T WORK THE ISSUE STILL REMAINS THE SAME, THEREFORE THIS BUG "FIX" IS INCORRECT, AND STILL BUGGED NOT FIXED.


so now you can read it and not just mindlessly close it as fixed, then linking me some polish bug post claiming it's not polish when obviously it is. And actually fix the bug.
Thanks ;)

While you're at it, you might check my other bug reports that I did for this "amazing blizzlike"  server aswell, since that should help you get back to that r1 spot you guys always have been on!

**Comment by tnarf** [comment]
They do not close repaired but not repaired bugs threads (in those cases).
They close DUPLICATED bug threads becous they do not want to speak about the same in MULTIPLE threads.

FIRST TotT thread is STILL OPEN.
