### ISSUE TITLE
[PL][DUNGEON]Mal'Ganis

### ISSUE THREAD

**Issue by Venhis** [Atlantiss/BugTracker#6589]
Dungeon: Old Stratholme

Po pokonaniu Mal'Ganisa skrzynia z łupem jest niemożliwa do otworzenia. Dodam również, ze Arthas porusza się bardzo powoli niemalże jak żółw i jeżeli odejdziesz od niego za daleko to wpada w tekstury.
Dowód na bug skrzyni:
http://imgur.com/cznwPto

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/5052
