### ISSUE TITLE
[ENG][Quests] Lack of quests in the Bloodwatcher Post

### ISSUE THREAD

**Issue by Xavenirus** [Atlantiss/BugTracker#6595]
As well in the title, there is no quests in that place like e.g. 
http://www.wowhead.com/quest=27878/forcible-acquisition
(No pre-quest required)
In additional, Npcs like Ramah Goldenray doesn't provide their services (shops etc.) 
http://www.wowhead.com/npc=48122/ramah-goldenray

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6774
