### ISSUE TITLE
[EN][Quest-WotLK]Fresh Legs incompletable

### ISSUE THREAD

**Issue by Nuggfush** [Atlantiss/BugTracker#6596]
Quest http://www.wowhead.com/quest=11251/fresh-legs should be able to be turned into npc Defender Mordun http://www.wowhead.com/npc=24111/defender-mordun.

The quest is likely broken due to the fact that Mordun was once outside of Utgarde Keep (where the quest tracker says to go to turn-in). However, since quest npcs were placed inside their respective dungeons, the quest is unable to be turned in.

The quest is a breadcrumb and not terribly important, but is bugged nonetheless.

**Comment by artamedan** [comment]
Why do you think that it is not possible to turn in the quest if you have not even tried to enter the dungeon? YES, you can enter the dungeon without any problem and the NPC is just near the stairs. You don't need a group or DF queue to enter the dungeon, like all of normal difficulty dungeons.

**Comment by Nuggfush** [comment]
I'm not sure why you assume I haven't entered the dungeon. I have entered both normally, through the portal, and via RDF queue. In both cases, Mordun offers the quests that he is supposed to, but he will not let you turn in Fresh Legs. The quest is not completable.

**Comment by artamedan** [comment]
You wrote: "However, since quest npcs were placed inside their respective dungeons, the quest is unable to be turned in." It is not true - that is what I responded to you. 
Do you have any of 3 quests given by Mordun in your quest log? If so- you have to abandom them. 
Even if not- you abandon the quest from scout Valory, exit the game, delete your cache folder, log in and take the quest again. Complete it and try to turn it again.

**Comment by Nuggfush** [comment]
Deleted cache folder. Took quest again, was automatically given "quest completed" text above my head. Quest still can't be turned in.
https://i.imgur.com/Qsx7ZGM.jpg

**Comment by artamedan** [comment]
As I see, the NPC has no quests for you- no exclamation sign. So it is obvious that you did his dungeon quests before. If you complete his dungeon quests, you cannot  complete this quest as THIS QUEST is meant to be pre-requisite for the dungeon. It has to LEAD you to the NPC inside the dungeon.
You shouldn't have been given this quest but probably that is precisely the bug- you were given the quest even when you completed dungeon quests already.

**Comment by Nuggfush** [comment]
I posted this issue before completing any UK quests. The result was exactly the same - Mordun wouldn't let me turn the quest in.

**Comment by Bildo** [comment]
fixed
