### ISSUE TITLE
[pl] czas ressania / time ressurection

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#6597]
czas resania łączy sie z pvp jak i z normalnym upadkiem czy zabiciem przez moba, nie powinno tak byc , jesli ktos nas ubije to resamy sie powiedzmy te 2 min, a jesli spadniemy tez trzeba czekac 2 min, a powinno byc jakos 20-25 sekund

**Comment by Aviannaqt** [comment]
duplicate
