### ISSUE TITLE
[EN][Isle of Quel'Danas] Magister's Terrace

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#6598]
Changing the instance to heroic mode yealds the following error:

![image](https://cloud.githubusercontent.com/assets/9639063/13369892/48f52574-dd04-11e5-8d26-af0c513012a3.png)

"You must be level 65 to enter on Heroic Difficulty"

Also, the atonement quest http://www.wowhead.com/quest=11488/magisters-terrace#comments is missing from NPC Exarch Larethor http://www.wowhead.com/npc=24813/exarch-larethor

**Comment by sulosuse** [comment]
That is not a bug ... you have to run normal mode first

**Comment by Walniety** [comment]
better u need to complete quest that u get from shat :D

**Comment by captjvmoore** [comment]
I did. Seven times. We farmed for a one hand axe on normal. Then we decided to go heroic and this happens...

**Comment by Walniety** [comment]
i done that quest bcs i wanted sword and it took me one hour u cant do hero without this quest bcs this quest give you access to hero version of dung :D

**Comment by Glare** [comment]
To all you guys saying that you need quests or whatever:

> Since patch 4.2 the requirement to attain Heroic Countenance was lifted.

Besides, there is a whole issue about bugs with MT.
https://github.com/Atlantiss/BugTracker/issues/572

**Comment by Walniety** [comment]
i done it a lots of time and dont have any issues expect mmaps :D rest work fine for me

**Comment by Luna-maria** [comment]
yea well, the attunement was removed in 4.2, but not on the server. You gotta do the quests still if you want to do heroic mode until they fix it

**Comment by Aviannaqt** [comment]
connected #572
