### ISSUE TITLE
[EN][Quest][Ashenvale] The Last Stand

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#660]
http://www.wowhead.com/quest=13987/the-last-stand
when you take the quest nothing happens.

video: https://www.youtube.com/watch?v=i2nEV-almsc#t=264

**Comment by ammeba** [comment]
Still not working.

**Comment by Deonorth** [comment]
nadal nie działa

**Comment by potato9000** [comment]
Połowa 2015 i wciąż nie działa :P

**Comment by bemoi** [comment]
Yup, this quest is still not working

**Comment by Avalain** [comment]
Oooo... nope, still not working.

**Comment by lourrific** [comment]
November 21, 2015 this quest still does not work. In December (next month) it will be 1 full year this quest is broken.

**Comment by TaleOf4Gamers** [comment]
December 12th - Still not working!

**Comment by Madenator** [comment]
Still not working 13.1.2016

**Comment by Quban** [comment]
bump :D

**Comment by Illusionist87** [comment]
Not working

**Comment by Bildo** [comment]
fixed

**Comment by Snake90** [comment]
Still bugged

**Comment by TranceAccount** [comment]
Can you give a better description?

**Comment by Snake90** [comment]
Now, it's working :)
