### ISSUE TITLE
[PL][Quest]Cold Hearted

### ISSUE THREAD

**Issue by LOTHAR461989** [Atlantiss/BugTracker#6601]
http://www.wowhead.com/quest=12856/cold-hearted#videos:id=87275

Ten quest powinien wygladac tak jak na filmiku.

Kiedy wsiadam na smoka spadam z nim na ziemie ale to nie jest duzy problem, NPC które sa zamrozone i które trzeba ratować respia się bardzo długo i jest to respawn 1 albo 2 dziennie, a czasami w ogole ich nie ma, a jak już się zrespia to albo nie można ich podnieść skillem smoka "ice shatter" , albo trzeba klikac po kilka razy na jednego NPC. Kiedy już się wraca z NPC do bazy to smok zrzuca mnie w powietrzu i znika.

**Comment by Lachrim** [comment]
właśnie skończyłem robić tego quest, jest uciążliwie zbugowany jednak da się go zrobić
jak spadasz to dawaj od razu spacje, oberwiesz max 2 hity od giganta
żeby smok nie znikał musisz lecieć tuż przy ziemi i dolecieć do tego npc do dał CI questa wtedy zaliczy też smoka, przyglądaj sie uwaznie powietrzu bo kilka z nich będzie wracała skacząc w powietrzu i je możesz powtórnie odprowadzać, to uciążliwe ale da się zrobić

**Comment by LOTHAR461989** [comment]
Da się zrobić, mi również zalicza, jestem paladynem wiec banka w ruch, ale dla innych ludzi jest to pewnie o wiele bardziej uciążliwe, każdy chce zrobić questa w 15 minut.. a nie w 15 dni..

**Comment by artamedan** [comment]
Oczywiście, że da się zrobić. Poderwanie smoka do góry to żaden problem. Zamrożonych NPCów jest tyle ile trzeba- musiałes trafic na czas gdy ktoś robił wczesniej questa lub robił w tym samym czasie. Smok zabiera 3 NPCe tak jak powinien a skill do zabierania działa jak trzeba.
Po prostu nie myślisz gdy robisz questy, jak widać wszyscy go zrobili, a ty nie kombinujesz, tylko od razu robisz raban bez powodu.
Problem pojawia sie dopiero dalej w tym łańcuchu, przy zbugowanym quescie w jaskinii, bo nie ma niedźwiedzicy, którą trzeba uratować.

**Comment by LOTHAR461989** [comment]
Wyslalem ticketa.. Rozmawiałem z GMem i on tez stwierzdzil ze ten quest jest zbugowany.. Moby wcale sie nie respia tak jak trzeba.. Bylem w tym miejscu kilka razy i byl tylko raz 1 mob a na 2 dzien 2.. W tym czasie byl ktos inny i mial taki sam problem tez kilka razy byl i mobow nie bylo.. A w wiosce nikogo nie bylo .. Na northrendzie siedzi Malo osob bo w zasadzie po co tam siedziec.. Czas respienia tych mobow na globie to 30-60 minut dokladnie nie wiem a nie ze jest tak jak by tam mnóstwo osob robilo tego chaina i nigdy mobow nie ma..

**Comment by LOTHAR461989** [comment]
Jezeli

**Comment by LOTHAR461989** [comment]
Jezeli Quest by dzialal jak należy to nie kazano by mi zgłaszać tego na bugtrackera zreszta po dłuższej rozmowie i wyjadnianiu przypadku, wiec jezeli nie masz nic konkretnego do powiedzenia co by wnosilo cos do tematu to nie pisz.

**Comment by artamedan** [comment]
Ja zrobiłem tego questa BEZ PROBLEMU. Jeśli nie widzisz NPCów to znaczy, że masz jakiś inny quest wzięty, który cię wrzuca do innej fazy. Cały łańcuch na SonsOf Hodir to sa tzw. "phased quests".
Wyrzuć wszystkie questy wzięte w tym rejonie, wyjdź całkiem z gry, skasuj Cache, zaloguj.

**Comment by LOTHAR461989** [comment]
Nie mam zadnych questow w tamtym rejonie i wiem jak działa ten quest, robilem go kilka razy kilkoma postaciami.. w storm peaks mam tylko tego questa..

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/2471
