### ISSUE TITLE
[EN][NPC][Amani Dragonhawk] Supposed to be tameable.

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#6608]
I was glad, when Amani Dragonhawks in Zul-Aman got a new unique model, but in addition to that, they are supposed to be tameable. Currently they are not, please allow hunters to have such a beautiful pet

**Comment by Aviannaqt** [comment]
link

**Comment by Shanrolol** [comment]
http://www.wowhead.com/npc=23834/amani-dragonhawk
