### ISSUE TITLE
Deepholm quest chain

### ISSUE THREAD

**Issue by Dreab79** [Atlantiss/BugTracker#6609]
Char name: Variust
Area: Deepholm
Quest: The Twilight Overlook
Details:
After doing the quick completion of the chain before this, the quest did not allow me to progress the chain. I'm unsure if the quest was completed or if it was able to be accepted. So the quest chain is stuck at this point for me. I have checked with Stormcaller Mylra, and I have nothing to accept or do from her (the next part of the chain).

**Comment by Bildo** [comment]
bt rules
