### ISSUE TITLE
[en][mage]cauterize 100% ~ health

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#6611]
so the problem is next, sometimes when you damage a fire mage to the point cauterize procs, cauterize brings him to 70-100% health instead of 40%.

not sure how to reproduce it perfectly,from what I saw this problems occurs when the damage in between before cauterize and after is too high

like you are at 1k health left and you get a crit of 40k lets say, cauterize brings you to 70-100% health instead of 40%.

**Comment by fruvel** [comment]
maybe he use 1 tick evocation and healthstone ? can u try with mage duel, and see ?

**Comment by Zhalox123** [comment]
U can survive cauterize if u put mana shield and mage ward on yourself without block ofc, or just evocate drink a potion or healthstone.

**Comment by lamaATS** [comment]
Fixed in rev. 5205
