### ISSUE TITLE
Bugged achievement!

### ISSUE THREAD

**Issue by Zipper2013** [Atlantiss/BugTracker#6612]
Hello!
One of the achievements needed to "Glory of the Hero" is cerainly bugged. It is "The Incredible Hulk" achievement. Although the sword falls onto the mob, it does not inflict any damage, so we are unable to achieve the reward of "Red Proto-Drake"
Regards,
Zipper

**Comment by HUMBOL** [comment]
https://github.com/Atlantiss/BugTracker/issues/1865
