### ISSUE TITLE
[PL][Location][Maelstorm]

### ISSUE THREAD

**Issue by Pindzia** [Atlantiss/BugTracker#6613]
Wskoczyłem na tego mounta żeby wlecieć do Deepholmu ale missclicknąłem i zleciałem pod wir i mnie zabiło czy mogę się tam dostać jakkolwiek ponownie

**Comment by Anhaeyn** [comment]
Kup Potion of Deepholm z AH i się dostaniesz.

**Comment by artamedan** [comment]
Powinieneś mieć już odblokowany portal z Orgri skoro zrobiłes questa.

**Comment by Pindzia** [comment]
Solved by GM porada nie zeskakiwać z wywerny :)
