### ISSUE TITLE
[PL][Mage] Blink

### ISSUE THREAD

**Issue by Aborcjowany** [Atlantiss/BugTracker#6614]
Witam. Ostatnio znalazłem błąd związany z blinkiem u maga. Kiedy podleci się wysoko jakimś fly mountem a następnie podczas spadania użyje sie blinka to przeniesie nas o gigantyczną odległość.
Jak server będzie online to postaram się dodać screeny

**Comment by BialyADI** [comment]
Potwierdzam Wpizdu wysoko i dałem Blinka przenie tak daleko w przód że mi mapę musiało doczytać.

**Comment by Pankaa** [comment]
Apropo blinka to ja znalazłem inny smaczek w wodzie/pod obecnie kompletnie nie działa<=ak' blink w miejscu.(jedyna możliwość to nurkowanie do samego dna i taki sposób poruszania -_- )
