### ISSUE TITLE
[PL][Paladin][Spell][Hand of Freedom]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6619]
Istnieje możliwość rzucania Hand of Freedom na friendly targety podczas, gdy Palladyn jest uwięziony w Cyclone. Nie jestem pewien po której stronie leży problem HoF czy Cyclone.

**Comment by fruvel** [comment]
w cyklonie ;) bo palladyn jest w efekcie "stun"

**Comment by kadi2** [comment]
https://youtu.be/PdUUr605TSk?t=5m52s // blizzlike
