### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Arcane Legacy

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6620]
http://www.wowhead.com/quest=25766/arcane-legacy

This quest was refrenced here  [EN][Quest][Stonetalon Mountains] Arcane Legacy #4121 but apparently it has not been fixed. All it says is Quban closed this in 1f3f785 on Aug 6, 2015 and it has been 6 months and no fix yet.

This quest can not be completed because either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because these 2 quests are still broken.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
