### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Bombs Away: Mirkfallon Post!

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6625]
http://www.wowhead.com/quest=25768/bombs-away-mirkfallon-post

This quest was refrenced here [EN][Quests][Stonetalon Mountain] Quest Order #4458 but apparently it still remains broken. It was referenced in the wrong format along with other bugged quests on Sep 10, 2015 and it has been 4 months and no fix yet.

This quest can not be completed because either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because these 2 quests are still broken.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
