### ISSUE TITLE
[PL][Quests][Undercity]-Cooking and Fishing Dialy

### ISSUE THREAD

**Issue by SpiritHealerV** [Atlantiss/BugTracker#6627]
Eunice Burch i Armand Cromwell nie dają żadnych questów. Po rozmowie z GMem doszliśmy do wniosku że to bug. Wyżej wymienione NPC mimo iż można z nimi rozmawiać nie posiadają funkcji "Quest Givera" (nie świeci się niebieski wykrzyknik dialy questa).
Pozdrawiam
Spirithealer

**Comment by artamedan** [comment]
Potwierdzam. W UC ani cooking ani fishing dailies nie działają. Ponadto w TB brakuje też daily na fishing- NPC ma tylko opcję "train".
W Orgrimmar dailies na obydwie profesje działają dobrze.
Nie ma to nic wspólnego z tym, że w Cataclysm tylko jeden quest dziennie na cooking i fishing może być zrobiony- sprawdzone UC i TB pod tym kątem.

**Comment by Kiperr** [comment]
Undercity cooking&fishing quest will be fixed after rev 4915.
