### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Warn Master Thal'darah

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6631]
http://www.wowhead.com/quest=25880/warn-master-thaldarah

This quest was refrenced here  [EN][Quest][Stonetalon Mountains] Warn Master Thal'darah #4125 but apparently it has not been fixed. All it says is Quban closed this in 1f3f785 on Aug 6, 2015 and it has been 6 months and no fix yet.

This quest can not be completed because A prequisite quest needed is bugged or broken. It can be either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 because they are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because of this and other various bugged quests in the area.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
