### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Save the Children!

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6632]
http://www.wowhead.com/quest=25889/save-the-children

This quest was listed twice as bugged and never repaired:
here it was just closed with no explanation [EN][Quest][Stonetalon Mountains] Save the Children!(ID 25899) #1272 and here it was closed for being a duplicate post  [EN][Quest][Stonetalon Mountains] Save the Children! #1862 

This quest was first reported as bugged on on Jan 4, 2015 and it has been broken for over a year.

This quest can not be completed because A prequisite quest needed is bugged or broken. It can be either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 because they are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because of other various bugged quests in the area.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
