### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Last Ditch Effort

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6633]
http://www.wowhead.com/quest=25891/last-ditch-effort

This bugged quest was posted  or referenced in 3 different ocassions:

 [EN][Quest]Last Ditch Effort #4583 Wrong Format
 [EN][Quests][Stonetalon Mountain] Quest Order #4458 Wrong format not specific
 [Pl][Quest][Stonetalon Mountains] Last Ditch Effort #3166  In Polish

This quest was first reported on May 4, 2015 and it is still bugged 9 months later.

This quest can not be completed because the prequisite quest needed is bugged or broken. It can be either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 because they are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because of this and other various bugged quests in the area.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
