### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Brood of Seldarria

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6637]
http://www.wowhead.com/quest=25931/brood-of-seldarria

This quest can not be completed because the prequisite quest needed is bugged or broken. It can be either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 because they are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because of this and other various bugged quests in the area.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
