### ISSUE TITLE
[PL][NPC] Riha 

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#664]
Brak NPC 

http://www.wowhead.com/npc=52268

Dodatkowo jest ona z frakcji "The Sha'tar" i powinna oferować zniżki według reputacji tej frakcji, a nie reptuacji gildijnej

**Comment by Bildo** [comment]
rev. 4353 by Navedonar

**Comment by TranceAccount** [comment]
Riha is still missing.

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5827
