### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Shuttin Her Down

### ISSUE THREAD

**Issue by lourrific** [Atlantiss/BugTracker#6641]
http://www.wowhead.com/quest=25811/shuttin-her-down

This quest was referenced here [EN][Quests][Stonetalon Mountain] Quest Order #4458 but apparently it still remains broken. It was referenced along with other quests on Sep 10, 2015 and it has been 4 months and no fix yet. I'm not sure if that post was more of a quest guide or an actual list of bugged quests so I'm posting the bugged quests that I find in stonetalon mountains in the correct format.

This quest can not be completed because the prequisite quest needed is bugged or broken. It can be either [EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill(ID 25669) #1724 OR [EN][Quest][Stonetalon Mountains] Commandeer That Balloon!(ID 25652) #1257 because they are still bugged and have not been repaired thus ruining quest progression in Stonetalon Mountains. There are around 20 quests in Stonetalon Mountains that can not be completed because of this and other various bugged quests in the area.

**Comment by Bildo** [comment]
Make one report, dont spam bugtracker.
