### ISSUE TITLE
[EN][Quest][Westfall] Secrets of the Tower

### ISSUE THREAD

**Issue by Ntfk** [Atlantiss/BugTracker#6642]
http://www.wowhead.com/quest=26290/secrets-of-the-tower

This quest is not working
Tried every method I found still not working. Yes I saw #2338 fix, still not working.

**Comment by Aival94** [comment]
If you have seen a report open(https://github.com/Atlantiss/BugTracker/issues/2338) why make new report.Just comment under the old report.This one will probably be closed.
