### ISSUE TITLE
[EN][Quest][Storm peaksl]The Lonesome Watcher

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6644]
http://www.wowhead.com/quest=12877/the-lonesome-watcher

https://www.youtube.com/watch?v=QED8hmP51gU&feature=youtu.be

Creteus is spawned 2 times but not on proper place and does cant receive quest

**Comment by Kiperr** [comment]
https://scr.hu/1c8o/shhv1 from my local server.

**Comment by DuGalle** [comment]
So its Fixed now ?

**Comment by Kiperr** [comment]
On my local i dont see any problems with this npc, i only add waypoints for him.

**Comment by DuGalle** [comment]
Yey revision is not yet implemented right ?
