### ISSUE TITLE
[EN][Item] Jaws Of Defeat

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#6648]
Recently acquired this trinket on my restoration druid and seems that it isn't working as intended. After doing some research i found out that the Buff "Victory" you get from using the trinket is broken. Once you cast spells the buff should give also give the buff "Victorious" from All holy/nature spells not just casted ones. So for example it gives a stack for casting Regrowth But not for instant casts like rejuvenation, but it should give stacks and decreased mana costs for both casted AND instant spells like rejuvenation and renew. But is currently only giving for casted spells rendering it almost useless.

Wowhead link for item: http://us.battle.net/wow/en/forum/topic/3393369999
The comments section also provides some basic insight into how the trinket should work. Thank you.

@posted by 
Korrx opened this Issue on 8 Jan

**Comment by Kejmil** [comment]
moar duplicates!
https://github.com/Atlantiss/BugTracker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+jaws
