### ISSUE TITLE
[EN][PET][Hunter] - Hunter's  Pets  nameplate BUG

### ISSUE THREAD

**Issue by Cholee** [Atlantiss/BugTracker#6650]
http://postimg.org/image/frutp2j45/

As u can see at image, missing my pet NAMEPLATE, but I can see nameplates of others pets.

It is very difficult to track a pet during PVP without it. It is not addon problem.

**Comment by Jenovas** [comment]
Ctrl+v or some other shortcut should let you see friendly nameplates etc

**Comment by Cholee** [comment]
OMFG Jenovas

**Comment by Lanrutcon** [comment]
This is not a bug. If you want to check your pet's health, then check it's pet health bar.
Proof: http://eu.battle.net/wow/en/forum/topic/9751345541
