### ISSUE TITLE
[PL] Summon Garg.... 

### ISSUE THREAD

**Issue by VakuDark** [Atlantiss/BugTracker#6652]
Problem ze spellem u dk unh. Dk posiada umiejętność summon garg... ,ale i umiejętność unh freeze.
Umiejętność unh freeze zwiększa haste i ogólnie jest to mocna dopałka do dk unh. Ta zdolność powinna zwiększać szybkość kastowania pocisków przez przyzwanego gargulca. Szybkość z jaką gargulec kastuje zależy od ilości haste u dk w moim przypadku jest to 1,8 sekundy ,a po użyciu unholy freeze powinno być co najmniej 1,0 sekundy. Gargulec obecnie nie reaguje na unholy freeze i atakuje jak by tego nie było proszę o naprawę tego wrednego błędu. Wcześniej napisałem ticketa ale gm kazał mnie tutaj poinformować o tym błędzie. Dziękuję z góry za pomoc i czekam na naprawę błędu.

**Comment by kadi2** [comment]
http://www.coi.waw.pl/

**Comment by aneq** [comment]
gm cie powinien na chemioterapię skierować a nie na bugtacker
