### ISSUE TITLE
[PL][Hunter][StableMaster]

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#6653]
Doceniam naprawe stable masterów ale jak to bywa z skryptami cos naprawia cos popsuja  tak wiec wyglada to tak ze po kazdej zmianie peta u stable mastera trzeba zrobic reloga gdyż pety sie buguja nakładaja na siebie i przyzywa sie nie tego co sie chce, dziekuje za poswiecona uwage i czas na bład który znalazłem.

**Comment by Bildo** [comment]
Pojawilo sie to po updacie?

**Comment by avalancze23** [comment]
tak

**Comment by avalancze23** [comment]
zauwazyłem jeszcze ze po zakdorazowym złapaniu zwierzaczka trzeba robić reloga zeby mozna było  przyzwać peta który po złapaniu nie ma odrazu poziomu huntera

**Comment by krecik88** [comment]
fixed in 4979
