### ISSUE TITLE
[PL][Raid]Ragnaros loot

### ISSUE THREAD

**Issue by LOTHAR461989** [Atlantiss/BugTracker#6654]
http://imageshack.com/a/img924/926/tCtRis.jpg
http://imageshack.com/a/img923/2226/2ix05R.jpg
http://imageshack.com/a/img923/8372/yEiygJ.jpg
http://imageshack.com/a/img923/8495/B53QZd.jpg

Chciałbym zglosic brak lootu z Ragnarosa w Molten Core (Raid Vanilla/Classick).
Wczoraj postanowiłem zrobić xmog run do Molten Core, 2 razy zginalem od upadku walcząc z Ragnarosem kiedy wyrzuca w powietrze, a kiedy go już zabiłem.. Zonk.. Nie ma lootu.. Niestety jak zrobily się zdjęcia to nie widać kursora ale nie widać w ogole woreczka(brak interakcji z pokonanym bossem) . na 4 screenie widać ze boss się swieci i loot nie jest podniesiony, ponieważ nie da się go podnieść. Nie którzy uwazaja ze mieli loot solujac Ragnarosa, wiec wychodzi na to ze jest to rosyjska ruletka.

**Comment by calladin** [comment]
Na AQ po zabiciu 6 bossów tylko z jednego padł mi loot w dodatku 1 item. Wtf?

**Comment by Aviannaqt** [comment]
ogolnie caly loot z classic i tbc jest zwalony xd

**Comment by BialyADI** [comment]
Bardzo fajnie ;p.

**Comment by Kuszki** [comment]
Problem z MC musi być dość świeży - osobiście farmiłem tam kilka itemów i loot był OK. Miało to miejsce około 2 miesiące temu.

**Comment by LOTHAR461989** [comment]
Jestem Obecnie w Blackwing Lair i nie da się odpalić Valestrasz the Corrupt czyli 2go Bossa co przez mechanikę raidu unemozliwia pojscie do kolejnego Bossa. Gadam z nim po zabiciu dragonkinow stojących obok ale dalej się nic nie dzieje,tydzien temu było ok 1 boss w ogole nie ma lootu, tydzień temu również.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11848-6654-molten-core-boss-loot-tables/

**Comment by MichaelArchangelo** [comment]
Było już kilka zgłoszeń o innych bossach i jak dla mnie głupotą jest takie naprawianie po 1 raidzie/bossie, bo problem dotyczy wszystkich raidów classic i tbc. Liczba itemów w loocie jest losowa, czasem pada 0, czasem 8. Trzeba za jednym zamachem to fixnąć.

**Comment by Piklo** [comment]
@MichaelArchangelo "problem dotyczy wszystkich raidów classic i tbc" taki mam zamiar, ale potrzeba na to czasu, same bossy z vanilli dropią 1400 itemów? Jakby zrobienie tego to byłaby chwila, to już dawno temu by ktoś to zrobił :P 
Jak każdy developer i content fixer robię to w czasie wolnym, którego nie zawsze mam tyle żeby sobie usiąść na spokojnie i fixować loot.

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
