### ISSUE TITLE
[PL][Warlock][Spell] Healthstone

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#6656]
Po zrobieniu healthstona wchodze w combat, nie powinno tak byc bo to zwykly spell

**Comment by Glare** [comment]
Bug związany z demonami. Agressive/Defensive daje combat, natomiast Passive już nie. Combat dostajemy też za każdym razem, gdy ktoś weźmie Healthstone'a ze studni.

**Comment by Jenovas** [comment]
Fixed
