### ISSUE TITLE
[EN][NPC] Jearl Donald

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#6659]
This NPC stationed in Andorhal in Western Plaguelands (http://www.wowhead.com/npc=44462/jearl-donald#starts) gives the quest "Into the Woods" (http://www.wowhead.com/quest=27683/into-the-woods).

From my searching this seems to be incorrect as the only two NPC's that should give this quest are Argent Office Pureheart and Adrine Towhide.

**Comment by TranceAccount** [comment]
Confirmed on PTR.

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14617-npc-jearl-donald/
