### ISSUE TITLE
[PL][Quest][Howling fjord] It Goes to 11...

### ISSUE THREAD

**Issue by rruski91** [Atlantiss/BugTracker#6662]
Problem jest taki że po zniszczeniu obojętnie jakiego z budynków nie pojawiają się  Dragonflayer Defenders (http://www.wowhead.com/npc=24533/dragonflayer-defender), co u nie możliwia zaliczenie tego questa.
Link do questa: http://www.wowhead.com/quest=11421/it-goes-to-11#comments
Filmik na YT z przebiegiem tego questa: https://www.youtube.com/watch?v=NGwvNoZo5PU

**Comment by Aviannaqt** [comment]
#1667
