### ISSUE TITLE
[PL][Quest][Howling fjord] Lightning Infused Relics

### ISSUE THREAD

**Issue by rruski91** [Atlantiss/BugTracker#6663]
Problem polega na tym że "Work bench"(http://www.wowhead.com/object=186958/work-bench) nie pozwala na zmianę w golema po wybraniu opcji dialogowej (pomimo iż we wcześniejszch questach z tego chainu "Work bench" działał).
Link do questa: http://www.wowhead.com/quest=11494/lightning-infused-relics
Filmik z questem: https://www.youtube.com/watch?v=f0YdUnxwaJ8

Można pod ten problem podczepić również quest The Delicate Sound of Thunder (http://www.wowhead.com/quest=11495/the-delicate-sound-of-thunder) ponieważ on również wymaga działającego "Work Bench" do zmiany w golema.

**Comment by Aviannaqt** [comment]
#4335
