### ISSUE TITLE
[PL/EN][NPC] Gunra Justice Quartermaster

### ISSUE THREAD

**Issue by Woterek** [Atlantiss/BugTracker#6665]
The Justice Points Vendor in Orgrimmar is missing a few items. I didn't check them all but im sure about 1 of them.

Vendor Justice Points'ów w Orgrimmar nie pokazuje wszystkich itemów co powinien. Nie sprawdzałem wszystkich itemów ale jestem pewien co do 1 z nich.

Missing/brakuje
-Cowl of Pleasent Gloom

**Comment by Aviannaqt** [comment]
Atlas jest pod patch 4.3.4, wszystko dziala dobrze itemy te sa za Valory

**Comment by Woterek** [comment]
Nawet jeśli Wristy są za Valory to Head powinien być możliwy do kupienia, gadałem z jednym z devów i powiedział że przez buga Head za 2200 Justice Pointsów został przypadkiem usuniety i nie było to zamierzone.

**Comment by Aviannaqt** [comment]
Sorka, nie zauważyłem ze to o 346 heada chodzi

**Comment by TranceAccount** [comment]
#5842
