### ISSUE TITLE
[EN][PL][Item][Firelands] Flickering Wristbands

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#6668]
Item: Flickering Wristbands
Link: http://www.wowhead.com/item=70735/flickering-wristbands
(more links at bottom)

[EN]
Item uses WRONG random enchant (suffixID; 2xx in place 133,135,136,137).
Becous of that item have stats similiar to ilvl 372 not 378.

Profs:
Link_1 to wowhead comment with correct values.
Link_2 to random suffixID list.
When we check suffixID (for example by script_1 after puting intem in 1th bag's slot) for droped item we get UNLISTED value (for example -289).
Rest of Flickerig items (shoulders, handguards) uses unlisted suffixID too and have good stats,
BUT they have GEM SOCKET (wrist not).
Items from Throne of the Four Winds (TotFW) uses the same suffixes,
Items with socket and without from TotFW with the same suffixes use DIFFERENT suffixID (for example ring without gem slot from list, belt with gem unlisted).
Standard items (fixed stats) with socket have always (without gem) lower stats than items for the same slot and with the same ilvl.
So because hipotetical bigger stats from sockets, those items USE modified random enchant,
And because mistaken Wristbands have copied from Shoulders list of possible suffixID (or use the same).

For example script_2 is game link to Flickering Wristbands of the Windflurry wich CORRECT stats. and script_3 to WRONG stats.

[PL]
Flickering Wristbands używają błędnych random enchantów (suffixID; 2xx w miejsce 133,135,136,137) przez co mają zaniżone staty (ala 372 a nie 378ilvl)

Dowody:
Link_1 do komentarza na wowhedzie
Link_2 do listy sufixów
Wszystkie Flickering itki korzystają u nas z random enchantów z poza tej listy (możemy to sprawdzić za pomocą script_1 dla itka w 1. slocie bagów).
Naramy i rękawice w przeciwieństwie do writsów mają socketa.
Itki z TotFW korzystają z tych samych sufixów.
Itki z socketem i bez z TotFWa mające ten sam sufix mają inny suffixID (np ring bez socketa  z listy, pasek spoza)
Zwykłe itki z socketem mają zawsze niższe staty niż te na to samo miejsce z tym samym ilvl bez socketa.
Tak więc przez to że itki z socketami będą miały staty podwyższone gemem korzystają z nieco zmodyfikowanej formuły random encha aby to wyrównać.

Dla przykładu w script_2 i script_3 są WoWowe linki do Flickering Wristbands of the Windflurry kolejno z dobrymi i złymi statami.

Link_1:
http://www.wowhead.com/item=70735/flickering-wristbands#comments:id=1457890
Link_2:
http://wow.gamepedia.com/ItemRandomSuffix
Script_1:
/run link = GetContainerItemLink(0, 1);printable = gsub(link, "\124", "\124\124");ChatFrame1:AddMessage("Here's what it really looks like: \"" .. printable .. "\"");
Script_2:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:-135:432:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");
Script_3:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:70735:0:0:0:0:0:-289:432:85:0:0:0:0\124h[Flickering Wristbands]\124h\124r");

Tak wiem o innym wątku ale możliwe że dla tego że zamknięty nie było tam żadnego odzewu
https://github.com/Atlantiss/BugTracker/issues/6364

**Comment by Ranor** [comment]
fixed in rev 4914
