### ISSUE TITLE
[PL][Death Knight][Quest]Ebon Hold stuck

### ISSUE THREAD

**Issue by Pindzia** [Atlantiss/BugTracker#6670]
Cofneło mnie do Ebon Hold Skąd nie mogę się wydostać by dokończyć questa The Light of Dawn
i nie mam jak się wydostać ponieważ teleport nie działa

Ticket mam wystawiony 
Kilku innych Graczy też tam uwięziło

**Comment by Aviannaqt** [comment]
problem nadal wystepuje?

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.
