### ISSUE TITLE
[EN][NPC] Heroic Training Dummy (Not in place)

### ISSUE THREAD

**Issue by Vincentoxx** [Atlantiss/BugTracker#6673]
Heroic Training Dummy not in correct place.

![wowscrnshot_030216_135115](https://cloud.githubusercontent.com/assets/7830269/13459824/076048fe-e07f-11e5-9ec0-fa4e0520fff3.jpg)

**Comment by TranceAccount** [comment]
http://www.wowhead.com/npc=31146/raiders-training-dummy
-> Click on Stormwind City and see no Training Dummies spawned in the house (Command Center).

**Comment by TranceAccount** [comment]
https://community.atlantiss.eu/index.php?/topic/14394-npc-heroic-training-dummy/
