### ISSUE TITLE
[PL][Night Elf][Racial][Shadowmeld]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#6674]
Shadowmeld podobnie jak Mirrory maga powoduje utratę targetu z friendly Night Elfa. Tylko wrogowie powinni tracić target. Irytujący bug szczególnie w pvp, MELD INTERRUPTUJE HEALE.

**Comment by Fearyourself** [comment]
Agree with this. The other day I ns+HT myself instead of my partner :P

**Comment by aneq** [comment]
also shadowmeld causes you to leave combat during any encounters with npcs which should never happen,

**Comment by lamaATS** [comment]
Fixed in rev. 5486
