### ISSUE TITLE
[EN][Core] Skill casting

### ISSUE THREAD

**Issue by lqlq32** [Atlantiss/BugTracker#6678]
>  Implement Spell Queue (thx to Jenovas for base implementation)
> Correct restoring spell mods when spell cast failed

This is rly annoying  if i click 2nd cast while 1st cast isnt finished, i got 2nd cast too...  As hunter this mean u get focus cap rly offen, i am pretty sure it doesnt work like this on retail.

**Comment by Jenovas** [comment]
Well that is how it worked. Enter interface -> Combat -> Lag Tolerance and turn it off or set it to a smaller number.

**Comment by lqlq32** [comment]
My lag tolerance is at 0 ...

**Comment by Jenovas** [comment]
That means spellqueue happens only if you spam the button after GCD ended

**Comment by lqlq32** [comment]
Well i am on half of the cast and i still cast next skill when i click it.

**Comment by Jenovas** [comment]
Lag Tolerance doesnt work on spell cast, it works on GCD.
0 Lag tolerance means that spell queue will work only after GCD passes.
400 Lag tolerance means you can queue a spell 400ms before GCD ends.

**Comment by lqlq32** [comment]
Sorry but i am playing retail too and when i click skill during my cast, i dont cast it after this, i cast it after i click it after the cast + gcd is finished.

**Comment by Jenovas** [comment]
Sorry but i am playing retail too - please make a video. We had players that used to play retail testing this and they said that this is how they remember it working.

**Comment by lqlq32** [comment]
There isny any difference between 0 and 400ms.

**Comment by Jenovas** [comment]
There isnt any difference between 0 and 400ms. - I have been in-game testing this right now, there is a huge difference. I think you dont understand that spell queue effects GCD not spell cast.

**Comment by lqlq32** [comment]
http://prikachi.com/images/933/8667933U.png

**Comment by Jenovas** [comment]
lqlq32 - as I said it does not effect CAST TIME, it effects GLOBAL COOLDOWN an allows to queue a spell. You said you play on retail and this is not how it works, please make a video then.

**Comment by lqlq32** [comment]
My laptop cant handle fraps and wow for sure. 
It isnt about cast time.
Lets say i want to cast 2x cobra shots in a row. Clinking 1st and smash the button again to click the 2nd immediately but then i see a explosive shot and i want to cast if instead of 2nd cobra shot, after 1st cast is over, but i cant because 2nd click on cobra shot is in que and will be casted when my 1st cast is done, doesnt matter if i click explosive shot during the 1st cast or not.

**Comment by lqlq32** [comment]
OK there is 2 screens 1st one is from retail 2nd is from atlantiss . at the MIDDLE of each cast i will click instant cast. I hope its clear now.
![wowscrnshot_030316_000038](https://cloud.githubusercontent.com/assets/3619666/13477271/580f1050-e0d4-11e5-8940-64640e4779f9.jpg)


![wowscrnshot_030216_235919](https://cloud.githubusercontent.com/assets/3619666/13477286/6750bfa0-e0d4-11e5-8e81-e4cd33e9aeff.jpg)

**Comment by aneq** [comment]
okay naabseeker, is the spellqueue disabled on atlantiss or is it manually set to 0 ms?. Because if you uncheck the box it auto defaults to 400ms.

@jenovas 
"Lag Tolerance doesnt work on spell cast, it works on GCD.
0 Lag tolerance means that spell queue will work only after GCD passes.
400 Lag tolerance means you can queue a spell 400ms before GCD ends."
that might be a problem, when a spell has a cast time higher than a gcd. You queue your next spell before the gcd ends, so if you have a spell that has a 3 second cast time, with a 1.5 sec gcd, you can queue next spell in the middle of a cast, which is probably what Naabseeker is experiencing on atlantiss.

**Comment by lqlq32** [comment]
Dude just see how is it on retail, i did it with enabled, 0 ms on both servers. When u click a skill on retail during spell cast u get - Your Spell isnt rdy yet. But when u do it on atlantiss there isnt such thing spell is just delayed till the cast end, i dont know what is soooo hard to understand from screenshots above. It obv doesnt work correct.

**Comment by Aizenscar** [comment]
An example of the problem -
I am casting scorch (usually spam it when I am doing it) and I have a pyroblast proc up. So when the cast has .3 or so left I spam pyroblast but instead of my next cast being a pyroblast its a scorch.
Lag tolerance is set to 0 ms.

**Comment by aneq** [comment]
@lqlq32 Apparently there was an update in the morning, test it now

**Comment by lqlq32** [comment]
Now its better than yday. When i click a skill during cast it say - another action in progress instead of just que this skill and do it when. But still there is a small window (may be last 0.3s of the cast) and the end for que,
