### ISSUE TITLE
[EN][Quest][Ashenvale] They Took Our Gnomes

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#668]
http://www.wowhead.com/quest=13913/they-took-our-gnomes
the quest don't work, npcs are missing

video: https://www.youtube.com/watch?v=8a9H0rqUrgE#t=243

**Comment by Deonorth** [comment]
wóz jest troche dalej i nie da się go zaatakowac - quest dalej nie działa

**Comment by bemoi** [comment]
Still not working, you find the cart but its not moving and u cant attack it :(

**Comment by gurin** [comment]
This bug prevents progression into Stonetalon mountains because you never get the starter quests there, and also prevents completion of Ashenvale quests...so Loremaster is double-screwed over by this bug!

**Comment by lourrific** [comment]
November 21, 2015 and this quest is still bugged. Cart appears after following long trajectory but it's empty and there is nothing to kill. In December (next month) this quest will be 1 full year it has been broken.

**Comment by TaleOf4Gamers** [comment]
December 13th - Still bugged!

**Comment by gurin** [comment]
http://www.wowhead.com/npc=39096/painmaster-thundrak doesn't respawn. Still can't complete.
