### ISSUE TITLE
[EN][Pet Spell][Warlock] Spell Lock

### ISSUE THREAD

**Issue by emouse** [Atlantiss/BugTracker#6682]
**Problem:**
At the moment if you cast Spell Lock the pet will attack the target and only do the spell in meele range.
For 4.3.4 and 4.2.0 patches the range should be 30 yards and it could be cast without the pet attacking the target.

**Reproduce:**
Set pet to Passive -> move it away from target -> cast Spell Lock 

**How it should work:**
The pet should stay where it is if it's set to Passive, cast Spell Lock and not attack the target, also it should be 30 yardsn not meele range, it was never like that at any expansion.

**Wowhead link (and changelogs):**
http://www.wowhead.com/spell=67519/spell-lock#changelog

**Comment by Sayris9876** [comment]
I dont know what you were testing but i just got my lock to 82 and im using felhunter (affliction spec) and spell lock is 30 yards however yes it attacks the silenced target which i dont know if it should be that way or not but spell lock does have 30 yards

**Comment by Fearyourself** [comment]
If you place your felhunter somewhere and have it spell lock a target at 30 yrd range it will cast spell lock and not move. If it's on passive it attacks the target after you spell lock/devour magic. I don't know if it's supposed to attack after casting the said spell, but the range on spell lock is working as intended.

Moreover, if you don't want it to attack the target just place it somewhere with /petmoveto command and it wont move nor attack unless target is in range. Works good for me.

**Comment by emouse** [comment]
It does work sometime as intended for me as well, but a lot of the times it will go in meele and then do it. I will try and record what happens, but it's 100% not right that pet should attack the target after casting a spell.

**Comment by kadi2** [comment]
If you did put pet on defensive stance, after casting spell lock or Devour Magic. The pet becomes tauntable by normal taunt and stoneclaw totem unless you order petattack command again which shouldn't be the case. https://github.com/Atlantiss/BugTracker/issues/5177
