### ISSUE TITLE
Spell Queueing system

### ISSUE THREAD

**Issue by Jamishman** [Atlantiss/BugTracker#6683]
This new spell queue system is absolutely terrible. If you spam keys, like you're supposed to be able to do, it completely ruins your DPS. This is not Blizzlike at all, why would you introduce something that cannot be turned off? Lag tolerance does nothing, it still queues spells up, especially instant casts.

**Comment by Kozakko** [comment]
And again, another person who is to lazy to at least read changelog....

**Comment by aneq** [comment]
this is blizzlike, and its your fault for being a button masher, if you care to dig up blizzard forums you will see players whining about it.
I'm not saying that the spell queue is not bugged but the one thing you reported is not a bug
easy solution - stop spamming spells and think what you do. this will take a bit to get used to for some
