### ISSUE TITLE
[EN][Hunter][Spell] Feign Death

### ISSUE THREAD

**Issue by Larcan** [Atlantiss/BugTracker#6684]
Hello.

Feign Death spell at atlantiss is totaly bugged, only think that do is dropping your aggro down, how ever when you use Feign Death you need to exit out of combat, but here that is bugged.

How i should work
Using feign death exits the hunter from combat, allowing for such things as eating, mounting, or other activities not possible while in combat. This can also be helpful if needing to afk for a short duration, due to the fact that passing mobs will act as if the hunter is dead.

Source: http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by lqlq32** [comment]
It depend actually in raids FD is working good. On retail you cant leave combat during encounters because this will give u a huge dps boost.

**Comment by Aival94** [comment]
Related to: https://github.com/Atlantiss/BugTracker/issues/16

**Comment by aneq** [comment]
again, people using wowwiki as a valid source of information...
No, it shouldn't ever drop your combat in pve but it should make any mobs not recognize you as a valid target.
If you're alone this will lead to mobs resetting, but if you have a pet out you will still be in combat.

**Comment by fruvel** [comment]
Patch 2.3.0 (13-Nov-2007): Fixed a bug in which Hunters were able to disengage from combat using Feign Death during boss encounters.

http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by fruvel** [comment]
larcan read patch notes and when u see something works weird, try to report a bug. You don't read the patch notes. Next time read or find sth that proud the spell don't work correctly.... 

Sry for bad eng.

**Comment by Thefakemccoy** [comment]
Feign Death
PvE: If you are in party, raid, or have a pet out it will only drop your aggro. Unless you are the last one alive. (All party and raid members need to be dead along with your pet to drop the combat.)


Example you are in raid fighting a boss an the leader calls a wipe as a hunter if you can survive dismiss your pet(if still alive)  and be the last one alive then feign death only then can you drop combat.

**Comment by lqlq32** [comment]
@Thefakemccoy is correct this is only way where u drop combat and i am pretty sure it work here too, because i did it sometimes.
