### ISSUE TITLE
[EN][Mage][Spell] Water Elemental and melee attack

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#6685]
Water elementals, while they in melee range, hit their target with melee attacks between waterbolt casts (and keep doing it, even when they go OOM). 
They should be pure casters without melee attack: http://us.battle.net/wow/en/forum/topic/1670091290
This also applies to  warlock pet - imp.

**Comment by aneq** [comment]
this applies to nearly all warlock pets

**Comment by Kejmil** [comment]
imp, succubus and doomguard shoudn't be able to melee anything

**Comment by Fearyourself** [comment]
Succubus should.

**Comment by Kejmil** [comment]
nope, not on cata
