### ISSUE TITLE
[PL[Quest][blade edge mountains][banish the demonds]

### ISSUE THREAD

**Issue by magion342** [Atlantiss/BugTracker#6687]
nad głowa npc Kronk widnieje znak "!" ale npc nie ma nam do zaoferowania żadnego zadania
link : http://www.wowhead.com/quest=11026/banish-the-demons#comments

**Comment by MichaelArchangelo** [comment]
I also have this problem, although I do not even have a quest mark over the NPC, he just doesn't give it to me when he should.

Również mam ten problem, tylko że NPC nawet nie ma nad sobą wykrzyknika, po prostu nie daje mi questa, mimo że powinien.

**Comment by Aival94** [comment]
reported here: https://github.com/Atlantiss/BugTracker/issues/3180
