### ISSUE TITLE
[EN][Item] Oshu'gun Crystal Fragment

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6692]
http://www.wowhead.com/item=25416/oshugun-crystal-fragment#dropped-by
How it is bugged: This item doesn't drop unless you have the quest http://www.wowhead.com/quest=9882/stealing-from-thieves in your quest log.
How it should work: This is not a quest item, it should drop regardless if you have the quest or not.

**Comment by artamedan** [comment]
This is not true. Having a quest gives you possibility to gather item from the crystal formations. But the item drops also from mobs around the crystal formations. It drops also from other mobs around all Nagrand.

**Comment by Aldurion** [comment]
well, the item doesn't drop from mobs unless I have the quest in the quest log, that is why I made this bug report

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10946-item-oshugun-crystal-fragment/

**Comment by aje** [comment]
fixed in revision 5115
