### ISSUE TITLE
[EN][Other] Returning to corpse after server crash

### ISSUE THREAD

**Issue by Evelinrose** [Atlantiss/BugTracker#6699]
After server crash u you no longer able to enter a dungeon where your corpse is properly.You are a ghost inside dungeon? what the hell....and if you relog nothing happens u still can't click on 'ressurect now'  http://imgur.com/PelxsSJ
Only option left is to unstuck on website or ressurect at spirit healer and take sickness.

**Comment by Fapguy** [comment]
It happens often in Firelands, but you can jump into the abyss/world under textures, etc, and when you hear the "whoosh" or you have fallen for 10+ seconds, you can release spirit and suddenly you're alive.

**Comment by pelekon** [comment]
fixed in rev 5906
