### ISSUE TITLE
[PL][Molten Ftont] The Bigger They Are

### ISSUE THREAD

**Issue by Gogon95** [Atlantiss/BugTracker#6700]
W tym queście nie da się zebrać Living Obsidium Chip (10) które jest potrzebne do jego ukończenia. Owy quest blokuje dostęp do jednego z vendorów w Molten Front - Damek Bloombeard.

**Comment by Lebiedz** [comment]
Da się je zbierać, niestety jest to nieco zbugowane. Skałki są klikalne tylko przez ułamek sekundy tuż przed zniknięciem ciała mobka, w związku z czym ja robiłem ten quest poprzez ciągłe klikanie w skałkę po zabiciu mobka i w większości przypadków udawało mi się je zebrać.

Niemniej, na pewno nie jest to blizzlike'owe działanie tego questa (pomijając już zbugowanie samych mobków).

**Comment by Aviannaqt** [comment]
#6661
