### ISSUE TITLE
Hacker

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#6701]
(https://cloud.githubusercontent.com/assets/11332250/13535325/3e09e440-e242-11e5-8693-8f83153479d5.jpg)

https://cloud.githubusercontent.com/assets/11332250/13535362/6e57566e-e242-11e5-848f-70ec0c7a3424.jpg

his name Nearlyn flying hacker alliance lvl 79, lost bg with my God char twink against him ,  i hope punishment that u ban him on IP address.... thx

**Comment by BialyADI** [comment]
Why server dont have any "antycheat" :D?

**Comment by Hosampsich** [comment]
ewidentnie zgłoszony a 2h po fakcie na liście banów nic ;]

**Comment by scylus** [comment]
Fakt ;)

**Comment by avalancze23** [comment]
od kiedy na bug trackerze zgłasza sie hackerów? nie od tego to miejsce wiec nie zasmiecajcie bug trackera tym takie sprawy na forum mozecie dać

**Comment by phanttom** [comment]
so case closed , nothing happened , cheer fly hackers , gd to know that GG
