### ISSUE TITLE
[EN][NPC]Chef Audrey

### ISSUE THREAD

**Issue by kostas4949** [Atlantiss/BugTracker#6703]
Chef Audrey is not in the game(Undercity) like she is supposed to. This way you can't complete the cooking daily Roach Coach which has to be turned in to her.
http://www.wowhead.com/npc=53528/chef-audrey

**Comment by HUMBOL** [comment]
Confirmed

**Comment by Bastion** [comment]
halo

**Comment by Kiperr** [comment]
Fixed  in rev 4928.
