### ISSUE TITLE
The hunt for Sylvanas

### ISSUE THREAD

**Issue by Strypes** [Atlantiss/BugTracker#6706]
i managed to do the Take back Gilneas quest even though there were no mobs, and now i am stuck at this mission, is hould listen to an undead saying that Sylvanas is hiding in the cathedral, but because there are no mobs i`m not able to do that so i just skip to the next step, i go and hide int the water that is in the cathedral and nothing happens.

**Comment by Aviannaqt** [comment]
read bt rules
