### ISSUE TITLE
[EN][NPC] Razorgore the Untamed (loot)

### ISSUE THREAD

**Issue by Irisusan** [Atlantiss/BugTracker#6709]
No matter which way or how many times you kill it, Razorgore the Untamed from blackwing lair doesn't drop any loot. All classic bosses will always drop at least gold (even if not dropping any items), this one doesn't, and this proves the bug.

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/4521

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the NPC.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11893-6406-blackwing-lair-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.

**Comment by Diamyx** [comment]
Still doesn't drop anything
