### ISSUE TITLE
[EN][Quest][Ashenvale] Defend the Tree!

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#671]
http://www.wowhead.com/quest=13935/defend-the-tree
the quest don't work, when you take it nothing happen.

video: https://www.youtube.com/watch?v=Dh3g-DdA5vs#t=279

**Comment by Aival94** [comment]
When you take quest it should be an option on the NPC [Halannia](http://www.wowhead.com/npc=34377) and when choose it, it cast on the player the spell [Shade of Shadumbra](http://www.wowhead.com/spell=65396) and mount NPC [Shade of Shadumbra](http://www.wowhead.com/npc=3831) using spell [Defend the Tree!: Summon Shade of Shadumbra](http://www.wowhead.com/spell=61872).

When you mount/become the [Shade of Shadumbra](http://www.wowhead.com/npc=3831) the player has the controlled ablilities:
1. [Swipe](http://www.wowhead.com/spell=65402)
2. [Rake](http://www.wowhead.com/spell=65406)
3. [Pounce](http://www.wowhead.com/spell=65407)

And should be phased were [Warsong Invader](http://www.wowhead.com/npc=32856),[Warsong Trampler](http://www.wowhead.com/npc=34390] and [Warsong Demolisher](http://www.wowhead.com/npc=32850).

When on the pool it should be cast on the player the spell [Rune of Healing](http://www.wowhead.com/spell=73695).

More spells which you might need: [Shadumbra search](http://www.wowhead.com/search?q=shadumbra+#spells).

Openwow link: [Defend the Tree!](http://cata.openwow.com/quest=13935)
Gamepedia link: [Quest:Defend the Tree!](http://wow.gamepedia.com/Quest:Defend_the_Tree!)

Sorry for the big comment,Just try to help.

**Comment by Deadlyblonde** [comment]
Jest to jeden z dwóch questów, które nie działają a są potrzebne do zaliczenia http://www.wowhead.com/achievement=4925/ashenvale-quests

**Comment by Deadlyblonde** [comment]
Quest nadal nie działa...

**Comment by Deonorth** [comment]
nadal nie działa

**Comment by lcorr031** [comment]
It is 9/16/15 and this quest still does not work!

**Comment by lourrific** [comment]
It is November 21,2015 and this quest is still broken does not work. In December (next month) it will be 1 full year that nothing has been done to repair this quest.

**Comment by TaleOf4Gamers** [comment]
December 11th - Still broken.

**Comment by Madenator** [comment]
Still broken

**Comment by deplecak** [comment]
quest dont work

**Comment by BAndysc** [comment]
still broken ;(

**Comment by Aival94** [comment]
@BAndysc ask for scripts to fix it :)

**Comment by BAndysc** [comment]
Ough, I hate when scripting rather simple quest takes soo long. Fixed in #4973. Thanks @Aival94 for the info about healing pool, I didn't notice it while sniffing.
