### ISSUE TITLE
[EN] [Spell Queue] Moonkin form

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#6711]
When you cast Starfire and you are about to enter Solar Eclipse, if you attempt to cast Sunfire right after the Starfire cast, it will still be a Moonfire, resulting in DPS loss.

I think this might be the Spell Queue putting the normal Moonfire in the queue instead of Sunfire.

**Comment by kadi2** [comment]
It was bugged even harder on retail....

**Comment by Fapguy** [comment]
But it wasn't happening before the Spell Queue

**Comment by kadi2** [comment]
Indeed it shouldn't happen.

**Comment by Aviannaqt** [comment]
rev. 4919
