### ISSUE TITLE
[EN][Achievement] Cataclysm Raid Guild Achievements

### ISSUE THREAD

**Issue by Torquu** [Atlantiss/BugTracker#6712]
**Blackwing Descent Guild Run**:
Does not count Omnotron Defense System although it was repeatedly made

**Throne of the Four Winds Guild Run**
Does not count Conclave of Winds

**Bastion of Twilight Guild Run**
Does not count Cho'gall

**Firelands Guild Run**
Does not count Lord Rhyolith and Ragnaros

Of course all of this runs was made many times, in full guild team (10man)

**Comment by Aival94** [comment]
Have not done it for some time as we had achievement but for cho'gall it worked just fine before about a month.

**Comment by Anhaeyn** [comment]
I can confirm, that BWD and ToT4W achievments didnt worked, but BOT with my guild we did full last week and counted as achievment.

**Comment by HUMBOL** [comment]
Done ToT4W on Sunday. Did not work.

**Comment by Aival94** [comment]
BOT is working just fine as far as know.

**Comment by kaliak** [comment]
More can tell me what will be what may be happening?
I and my guild we are looking to end the conquest and see q has the guild already serves with him made it menbros mounted in their black fenix

**Comment by DuGalle** [comment]
Confirm about Tot4W and BWD respectivly Omnotron and Conclave

**Comment by Samineh** [comment]
Bump :+1:

**Comment by Pieczyyea** [comment]
After fix Tot4W, BoT and Firelands works, but still is not counting Omnotron Defense System on BWD to the achievement.

**Comment by Pieczyyea** [comment]
After rev 5717 it's possible to get Glory Achievement (finally)
