### ISSUE TITLE
[EN][Raid][Firelands] Eternal Embers Bosses.

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#6713]
Can't loot Eternal Ember[s] from bosses,
its Quest Item, As I know everyone should able to loot it from the bosses.

I need "fast" click on boss before someone else will pick it.
Also if Master Loot you can't pick it at all or something like that.

please fix.
ty.

**Comment by Thefakemccoy** [comment]
Embers can only be seen by players on the quest. The master looter has no control over them. First person who loots them on quest gets them its not looted by every one on quest.

**Comment by Illusie** [comment]
whatever,
so i need just click like crazy on boss before someone else get it. right?
is it how it suppost to be? or everyone with the quest can pick it just because it 'Quest Item'??

no logic. or try to make one. thank you.

**Comment by Thefakemccoy** [comment]
The boss only drops a certain amount depending on 10/25. It can not be looted by every one its a first loot situation. It is suppose to be like that.

**Comment by Fapguy** [comment]
If you are doing FL runs where there is no decency and everyone is a thief, maybe you should re-consider who you're grouping up with.

**Comment by Illusie** [comment]
@Fapguy we just /roll for it
but i thought it "quest item" so everyone can loot it.
wondering if it bugged or not.

gg.

**Comment by Thefakemccoy** [comment]
no every one wont get it even though it is a quest item it is not a normal quest item.

**Comment by kostas4949** [comment]
As stated already it's not bugged, only 1 person can get the eternal ember.
You could check wowhead and you'd have avoided creating this wrong report @Illusie
