### ISSUE TITLE
[EN][NPC][Deepholm] Therazane

### ISSUE THREAD

**Issue by Cafnaron** [Atlantiss/BugTracker#6715]
![wowscrnshot_030516_194509](https://cloud.githubusercontent.com/assets/17677546/13553247/e0d16da6-e382-11e5-888e-7b386b9f8460.jpg)
There's a problem with Therazane, which makes me unnable to interact with her. She isn't on her throne, but in central deepholm and I can't even click on her.

**Comment by Fapguy** [comment]
Yeah, report the people who are pulling her away.
