### ISSUE TITLE
[EN][Item] Empty Junkboxes

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#6717]
The junkboxes pickpocketed by a rogue are often empty when trying to open them. I have been farming http://www.wowhead.com/item=29569/strong-junkbox and I can say that it's really annoying to see 3 junkboxes show up as empty 3 times in a row when trying to open them.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12121-6717-strong-junkbox-loot-tables/
