### ISSUE TITLE
[EN][NPC] The Lone Hunter

### ISSUE THREAD

**Issue by Hez-Callan** [Atlantiss/BugTracker#6719]
The Lone Hunter is not tameable. Casting the 'Tame Beast' spell returns the 'Invalid Target' error.

It should be tameable since version 4.0.X: http://www.wowhead.com/npc=45450/the-lone-hunter
Model: Ghost Grey Wolf.

**Comment by meowmewo** [comment]
Someone is gonna try to bug the sword in his head :) :P :P :P :P :P

**Comment by Hez-Callan** [comment]
@meowmewo : 1) I don't think that it's possible in this game version.
2) There is no sword in its head (it's another bug), so it can be hard to bug a sword that doesn't exist.
3) Someone is trying to get a spectral pet collection and it seems that most of them are bugged:/
