### ISSUE TITLE
[Mage][Spell] Deep Freez

### ISSUE THREAD

**Issue by krojo** [Atlantiss/BugTracker#6721]
Deep Freez didnt do any dmg vs Immune Target. Tested on Dk

Prof
http://www.fotosik.pl/zdjecie/1f34e817b70e3097
http://www.fotosik.pl/zdjecie/081e9490fff18594

Spell --->  http://cata.openwow.com/?spell=44572

" Stuns the target for 5 sec. Only usable on Frozen targets. Deals [1.468*] to [1741*] damage to targets that are permanently immune to stuns. "

**Comment by meowmewo** [comment]
Deals [1.468] to [1741] damage to targets that are ----permanently---- immune to stuns. "

**Comment by aneq** [comment]
learn to read tooltips please
DK is not permamently immune to stuns, and judging how high deep freeze damage is, to even think that it should damage players is ridiculous

**Comment by krojo** [comment]
Learn Skill Dk pls 
 http://cata.openwow.com/spell=48792

" become immune to Stun effects and reduce all damage taken by 20% for 12 sec."

Immune is Immune. And is for 12 sec Permamently IMMUNE to STUN.

Why we have that stupid ppl idk

**Comment by BialyADI** [comment]
Krojo you are wrong ^^.

**Comment by krojo** [comment]
so give me Prof that i'm wrong.

**Comment by krojo** [comment]
ok found it self.
close
