### ISSUE TITLE
[EN][Quest][Azshara][Fade to Black]

### ISSUE THREAD

**Issue by geeorgee** [Atlantiss/BugTracker#6731]
Twilight Lord Katrana after slaying her, dragon grabbed me and nothing happend. Kalecgos didn´t come to save me and he is supposed to come and kill the Malicion. So i have to abandon the quest.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/3583
https://github.com/Atlantiss/BugTracker/issues/5249
