### ISSUE TITLE
[EN][Quest][Mount Hyal]black heart of flame

### ISSUE THREAD

**Issue by bziakot** [Atlantiss/BugTracker#6736]
I can't summon golem to kill him. Wherever I was stay and I used quest item I've got request "You are in wrong zone". I stay in good position. On yt film's can check where you need to stay to do this quest. 

http://images78.fotosik.pl/397/4f75b21ba054102a.jpg

https://www.youtube.com/watch?v=MDUrN_WfIsM

**Comment by Thefakemccoy** [comment]
The item to summon the guy does not work. However if you look you will find the guy already spawned in like a normal mob. If you do not see him wait for the respawn.

**Comment by Thefakemccoy** [comment]
Also https://github.com/Atlantiss/BugTracker/issues/577

**Comment by bziakot** [comment]
Thanks.

**Comment by XrayAlert05** [comment]
Can you guys fix this stupid quest? Want to get ring..
