### ISSUE TITLE
[PL] Magisters' Terrace Hero enter bug

### ISSUE THREAD

**Issue by hardrack** [Atlantiss/BugTracker#6738]
mam 83 lvl, chciałem zobaczyć jak trudne jest to hero by je solować po item do transmo, nie da sie wejść:
![wowscrnshot_030616_221526](https://cloud.githubusercontent.com/assets/17691695/13557129/c7c149d2-e3e9-11e5-99d5-83bd2c6b984d.jpg)

**Comment by Kiperr** [comment]
http://wowwiki.wikia.com/wiki/Magisters'_Terrace#Heroic mode

**Comment by hardrack** [comment]
hanks so much, sorry I didnt notice
