### ISSUE TITLE
[EN][Spell][Dk] Blood of the North

### ISSUE THREAD

**Issue by Snacky1** [Atlantiss/BugTracker#6739]
Sometimes when you die, death runes convert to blood runes and don't go back to death. To fix it you either have to relog or change specs. Can't do either if you're combat bugged in the middle of a dungeon, which is what usually happens to me.

**Comment by Kejmil** [comment]
https://github.com/Atlantiss/BugTracker/issues/3637
also you didn't even posted links, so here you have something to read:
https://github.com/Atlantiss/BugTracker
