### ISSUE TITLE
[EN] [Quest] Magister's Terrace

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#6740]
The atonement quest for Magister's Terrace hc http://www.wowhead.com/quest=11488/magisters-terrace is not obtainable from Exarch Larethor http://www.wowhead.com/npc=24813/exarch-larethor
![image](https://cloud.githubusercontent.com/assets/9639063/13558285/6b1fbaf4-e409-11e5-8b49-88bc76b3c792.png)
Trying to enter the heroic version of the dungeon yields the following message:
![image](https://cloud.githubusercontent.com/assets/9639063/13558297/a50c4868-e409-11e5-8c28-2f1445719a2c.png)

**Comment by jacula666** [comment]
To unlock hc version, You just need to complete chain started by aldors: http://www.wowhead.com/quest=11481/crisis-at-the-sunwell, or scryers: http://www.wowhead.com/quest=11482/duty-calls

**Comment by captjvmoore** [comment]
Thanks @jacula666 I will test it from A to Z tonight and post the results here. Keep this thread open until I do please.

**Comment by captjvmoore** [comment]
The chain works fine. Thanks again @jacula666 . You may close this thread now :)

**Comment by Aival94** [comment]
Furthermore is reported here with many other things: https://github.com/Atlantiss/BugTracker/issues/572
