### ISSUE TITLE
[PL] [General] [Core] duel

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#6741]
w duelu nie powinno dac sie zabic kogos, a jednak, trinkiety odpalaja sie w tym samym momencie, po zakonczeniu duelu powinno byc evade

**Comment by fruvel** [comment]
Templar Verdict http://www.wowhead.com/spell=85256/templars-verdict 
spell id 85256
w combat logu - 17k absorn 26k overkill critical i smierc a nie powinno tak byc ;) absorb 100%

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/6541
