### ISSUE TITLE
Glyph of Stormstrike tooltip

### ISSUE THREAD

**Issue by Nemanja99** [Atlantiss/BugTracker#6747]
So when you are using ,,Glyph of Stormstrike'' it should increase your crit chance effect by 10% = making it 35 %. If you move your cursor to the spell Stormstrike, it says it's 35 % crit chance bonus, but when you use it on the enemy, and move your cursor to it, it will say 25 %. So i'm not sure if it actually increases crit chance, or it's just display bug?

**Comment by Aviannaqt** [comment]
read bt rules

**Comment by Nemanja99** [comment]
Very helpfull answer :))) Why do i even post bugs that i find lol...
