### ISSUE TITLE
[EN][Raid][BWD][Maloriak]

### ISSUE THREAD

**Issue by EnPra** [Atlantiss/BugTracker#6748]
After casting arcane storm and release aberrations once, Maloriak tries to get in one of the phases by going to the cauldron, once there he just stands next to it and doesn't move until he drops to 20%.
At 20% all the aberrations that should've been released in red phase and killed in green almost instantly wipe the raid.

**Comment by Carpathea** [comment]
Heroic too

**Comment by Anhaeyn** [comment]
Can confirm this, we encountered that too.

**Comment by wcraycroft** [comment]
Video link of the bug: https://www.youtube.com/watch?v=ilBV4tFIJ4E

Happened on our first pull of the night. We were unable to soft reset the instance while he was in his bugged state.

**Comment by HUMBOL** [comment]
Can confirm

**Comment by arekczup** [comment]
rev 4927
    Repaired Maloriak

**Comment by Fapguy** [comment]
Just need to fix Nef now..

**Comment by Alagher** [comment]
Maloriak still bugged. i was abaut 10 hours ago and still the same
