### ISSUE TITLE
[Pl][NPC] Kirix

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#6750]
rzadka elita na molten front wychodzi poza swój teren poruszania pod tekstury co czyni go niemalże niemożliwego jak niemożliwego do złapania samemu.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/5777
https://github.com/Atlantiss/BugTracker/issues/5498

**Comment by avalancze23** [comment]
nie to nie jest ten bład o którym mówie
