### ISSUE TITLE
Nefarion Heroic PVE 

### ISSUE THREAD

**Issue by Carpathea** [Atlantiss/BugTracker#6753]
Onyxia's electrocute hits the whole raid in a 360 degree cone, its just about healable but messes up the whole fight because of the healers mana. It needs to be fixed for a kill

**Comment by blinkmaster** [comment]
Bitch Plz.

**Comment by Fapguy** [comment]
"blinkmaster"

What?

**Comment by blinkmaster** [comment]
Being drink ftw. But now when sober i can say that its killable with this bug

**Comment by Fapguy** [comment]
Who the fuck cares if it's killable?
It's still bugged.

**Comment by Carpathea** [comment]
That's not really the point, if a guild is trying to progress on it to enjoy the content, having to take enormous damage from a mechanic that you're supposed to avoid if tanked properly means the fight is not enjoyable. It's totally healable but i don't particularly care, it's not working properly

**Comment by xolon** [comment]
this bigger problem than adds on another side of the room ( ͡° ͜ʖ ͡°)

**Comment by Wantuno** [comment]
The amount of people missing the point is ridiculous. It's not about if it's killable or not, it's not about if its the biggest problem of the fight or not, this is a bug report, we reported a bug, and we hope it's fixed soon since it makes bwd not enjoyable. Maloriak is killable too when he bugs and does nothing until phase 2 where 15 adds that hit for 200k each suddendly spawn, but that doesn't make it a low priority fix.

**Comment by meowmewo** [comment]
What wonders me the most is whats up with 4.0.6 raids getting bugged again.

**Comment by xolon** [comment]
The amount of people that don't read bugtracker rules is ridiculous. It's not if its reported, it's not if there are no links, the biggest problem it is that it's not reported properly, and ofcourse people will mock till the grave.

**Comment by Wantuno** [comment]
Well they fucked up something in the last weeks, even normal dungeons, like bwc, the fire boss got 6 stacks per second last time i wetn there, wiping the group just by barely touching the fire for more than one tick.

**Comment by Carpathea** [comment]
I apologise for not reporting it properly i shall close this bug and when i have a proper report reopen it, i admit i rushed it last night just to get the info up.

**Comment by Fapguy** [comment]
It actually kinda seemed like the Discharge would hit anyone that _/was/_ in the cone for the attack, like, it remembered the positions, and it didn't matter if you turn it.

That or it just has a 20 degree space behind the boss where no one gets it. Not sure, didn't really have time to see
