### ISSUE TITLE
[ENG][Quests]howling mad

### ISSUE THREAD

**Issue by bziakot** [Atlantiss/BugTracker#6756]
Hello
I have problem with this quest. When i arrived to Takrik Ragehowl, he stay in village, not in cage. And when i started quest quest mobs don't appear. 
http://images76.fotosik.pl/398/660420291843e3ebgen.jpg
how it's schould woring
https://www.youtube.com/watch?v=cnlQfLcwFhw

if can't  fix it, can I have pass them to can make chain quest?

**Comment by artamedan** [comment]
I have done ALL the quest chain in Hyjal without any problem. It is not bugged so WHY do you post it in bug tracker? I have the achievement.
ALWAYS delete your cache folder before starting WoW! How many times it has to be told in-game and written here?

**Comment by Aviannaqt** [comment]
duplicate, write ticket or support@atlantiss.eu

**Comment by Lidless** [comment]
He posted it since it is bugged. Doesn't matter if you did it or not in the past.
Wowhead link: http://www.wowhead.com/quest=25270/howling-mad
Ragehowl is not in the cage, just standing on the hill and The Vandals are missing so the chain is broken.
