### ISSUE TITLE
[PL][Spell][Warlock] Silence from Unstable Affliction don't have DR.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#6757]
Link: http://logon.warmane.com/spell=31117

Silence z Unstable Affliction powinien podlegać pod Diminishing Returns z Silence effect w tym z samym sobą.
Aktualnie za każdym razem dostajemy całą długość Silence po dispellu Unstable Affliction i  Dmg, Silence powinien być DRowany.

Dowody:
http://wowwiki.wikia.com/wiki/Unstable_Affliction
http://wow.gamepedia.com/Diminishing_returns
http://wow.gamepedia.com/Unstable_Affliction
"The silence effect from this ability is subject to diminishing returns."
"Patch 2.3.0 (2007-11-13): The silence from this ability is now subject to diminishing returns."

**Comment by kadi2** [comment]
http://eu.battle.net/wow/en/forum/topic/1549667804

**Comment by BialyADI** [comment]
"I'm pretty sure it does have DR on it.. from experience."
Tam osoby do końca nie wiedza czy ma czy nie ma w ogóle ;x
Natomiast w Patch notach jest że powinien mieć. Bo teraz nie dość że mocno bije przy dispellu to jeszcze daje Silence i na dobra sprawę można  mieć tego silence 100% czasu.

**Comment by xolon** [comment]
"The silence from this ability is now subject to diminishing returns." this doesn't mean that it has dr now, it means that they considered putting it. Either find a patch note which says, "Unstable Afflicition now has <This/That> dr" or its not a bug

**Comment by Fearyourself** [comment]
Confirmed. It was never supposed to DR with itself and it never did in all of Cataclysm.

**Comment by Pankaa** [comment]
Patch 2.3.0 (13-Nov-2007): The silence from this ability is now subject to diminishing returns.
http://wowwiki.wikia.com/wiki/Unstable_Affliction

No need more.

**Comment by Kejmil** [comment]
http://gaming.stackexchange.com/questions/77299/in-pvp-how-does-unstable-affliction-affect-the-healers-strategically
no need more ( ͡° ͜ʖ ͡°)

**Comment by Pankaa** [comment]
Random post vs patch note

Unstable Affliction: The silence from this ability is now subject to diminishing returns.
http://us.battle.net/wow/en/game/patch-notes/2-3-0

The silence effect from this ability is subject to diminishing returns.
http://wow.gamepedia.com/Unstable_Affliction

**Comment by kadi2** [comment]
@Pankaa Raczej nic z tego nie ma wystarczajacej wartosci, aby podejmowac zmiane mechaniki spella. Podejrzewam, ze musialby to byc jakis filmik.

**Comment by Kejmil** [comment]
blizzard wiele rzeczy chcial a jeszcze wiecej hackfixowal

**Comment by Fearyourself** [comment]
UA silence is only supposed to dr with other silence effects, not with itself. It's working as intended.

**Comment by Zhalox123** [comment]
Srsly Kazzir stop reporting spells that work correctly you retarded idiot you barely know how to play a warrior and yet you post many spells on bugtracker that are working correctly already just to mess them up....UA when dispelled shouldnt have diminishing of itself  it should apply a silence  of 4 sec everytime its dispelled.READ HERE http://gaming.stackexchange.com/questions/77299/in-pvp-how-does-unstable-affliction-affect-the-healers-strategically    

No. A player who dispels Unstable Affliction will get silenced for four seconds, every time. Here          ( http://www.wowhead.com/forums&topic=190141/4-3-crowd-controls-dispels-pvp-de-buffs )you'll find a list of buffs, debuffs and their diminishing returns updated to 4.3. Notice that the silence debuff you get from Unstable Affliction is nowhere to be found.

**Comment by BialyADI** [comment]
You play Warlock?
I just want everything work perfect in this server.

**Comment by Illusie** [comment]
https://github.com/Atlantiss/BugTracker/issues/4267
i reported Unstable Affliction on August 16, 2015.

The spell act weird to me, when I checked via Recount the statistics and information about Dispelled, Penalty and other stuff.
