### ISSUE TITLE
[EN][Raid][NPC] Atramedes

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#6758]
Atramedes in BWD (I have only tested 10man and 10man heroic) On both difficulties he no longer properly applies sound to players. He will give you sound if you don't dodge waves, or if he uses a skill that gives sound. But it will instantly go away. You cannot stack sound, and it makes the fight a joke. 

http://www.wowhead.com/npc=41442/atramedes

The rest of the fight still works, Searing flame still wipes if not interrupted. Obnoxious fiend works properly though he also doesn't apply sound properly. Air phase works. Just the sound accumulation is bugged.

**Comment by Quban** [comment]
fixed
