### ISSUE TITLE
[EN][Transfer] LVL Bug

### ISSUE THREAD

**Issue by Machat2014** [Atlantiss/BugTracker#6761]
My char Exodya was lvl down to 80 after transfer from 85. Problem is i cant get exp to lvl her back to 85. I think she is flagged as max lvl.

**Comment by Lebiedz** [comment]
Try checking your max lvl setting in your account settings on atlantiss web page (you can set there your account lvl cap).

**Comment by Machat2014** [comment]
Error 504 :(

**Comment by Aviannaqt** [comment]
ticket or support@atlantiss.eu
