### ISSUE TITLE
[PL][Quests]Penetrating Their Defenses

### ISSUE THREAD

**Issue by Zakowpany** [Atlantiss/BugTracker#6765]
Witam:) Problem polega na tym, że wykonuję questa tj. m.in zabijam boss'a w Halls of Origination jednak ludek, u którego biorę, i później mam także oddać questa nie robi tego co powinien czyli nie idzie do komnaty przez co nie zalicza questa :-/ Jeszcze raz podam nazwę questa, jest on w Uldum, Penetrating Their Defenses

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/3432

**Comment by Lebiedz** [comment]
Podaj jeszcze link do tego questa z wowheada :)

**Comment by Zakowpany** [comment]
http://www.wowhead.com/quest=28746/penetrating-their-defenses

**Comment by Zakowpany** [comment]
Why?
 
W dniu 2016-03-10 16:35:49 użytkownik Aviannaqt <notifications@github.com> napisał:
Closed #6765.

**Comment by Aviannaqt** [comment]
#3432

**Comment by Zakowpany** [comment]
Szczerze, nie rozumiem :/ Temat z 2015 roku, ja go ponawiam w 2016 i zostaje on zamknięty mimo tego, iż nadal ten bug nie został naprawiony ;)?
 
W dniu 2016-03-11 11:10:59 użytkownik Aviannaqt <notifications@github.com> napisał:
#3432

**Comment by Aviannaqt** [comment]
tak

**Comment by Fuzzypunk** [comment]
nadal nie dziala!!
