### ISSUE TITLE
[EN] [Potion] sharing of cooldown

### ISSUE THREAD

**Issue by jissabraham** [Atlantiss/BugTracker#6769]
Invisibility Potion and  Mythical Healing Potion sharing cd in game it is suppose to have different shared cooldown as per wowhead.

Mythical Healing Potion sharing - http://www.wowhead.com/item=57191/mythical-healing-potion#shared-cooldown
Invisibility Potion sharing - http://www.wowhead.com/item=9172/invisibility-potion#shared-cooldown:150-2

**Comment by Kejmil** [comment]
healing potions not sharing cd with other ones (like invis or +stat potions) was implemented in wod due to absurd utility of warlock in mop

**Comment by jissabraham** [comment]
but cool down should be 2min not 10min for Invisibility Potion and 5min for Lesser Invisibility Potion
