### ISSUE TITLE
[EN][Transfer from sunwell] still 1[lvl] 

### ISSUE THREAD

**Issue by ffoxsunwell** [Atlantiss/BugTracker#6770]
Hello,

on my account i wanted to transfer my char from sunwell DB, i did everything like in description.

1. on Website i see that character is transferred
2. in game i see still character with lvl 1 which i created FOR transfer.

3. please solve this problem, ingame nick: Pikachuhd   

4. CLASS, RACE and MALE/FEMALE are correct ! :(

**Comment by Aviannaqt** [comment]
write ticket or support@atlantiss.eu
