### ISSUE TITLE
[PL][Talent][Shaman] Lava Surge

### ISSUE THREAD

**Issue by ashrasmun** [Atlantiss/BugTracker#6771]
Hej. Bug ten występuje w wielu miejscach (np. u huntera przy **_Misdirection_** i **_Trap Launcher_**), ale chciałbym go wyjaśnić na przykładzie talentu **_Lava Surge_**.

Jeżeli wycastuje manualnie **_Lava Burst_** i w przeciągu GCD, który jest wywołany z racji tego castu dostanę proc **_Lava Surge!_** to CD na **_Lava Burst_** nie zostanie zresetowany. 

Najłatwiej to zauważyć podczas zwykłego dpsowania na kukle z 4 częściami T12. 

Dodaje screen prezentujący jak to się objawia w samej grze. Łuki po bokach postaci sygnalizują wystąpienie buffu **_Volcano_** z P4T12, który jest bezpośrednio związany z procem **_Lava Surge!_**

http://i.imgur.com/gUwcvzh.jpg

**Comment by aneq** [comment]
sam mainuje ele i taka sytuacja jest bardzo denerwująca, ale niestety jest bugiem. To był po prostu kiepski design blizzarda
