### ISSUE TITLE
[EN][QUEST][GRIZZLY HILLS] The Darkness Beneath

### ISSUE THREAD

**Issue by holdias** [Atlantiss/BugTracker#6772]
This quest (http://www.wowhead.com/quest=12213/the-darkness-beneath) requires you to use Geomancer's Orb (http://www.wowhead.com/item=37173/geomancers-orb) beneath three locations, but when you do nothing happens. I tried using the orb at the three locations without any results.

**Comment by Kiperr** [comment]
Tested and works fine.
