### ISSUE TITLE
[PL][T12][WARLOCK]

### ISSUE THREAD

**Issue by Ukashi** [Atlantiss/BugTracker#6773]
witam

dziś po zakupie klaty z t12 dla locka zauwazyłem pewny bug, albowiem bonus t12 którym jest imp pojawia się nawet podczas posiadania jedynie jednej części setowej, będąc na kukle nie atakował lecz zauważyłem że w stosunku do mobów potrafi bić. Znajomy z gildii również był w pt i też go widział więc to nie visual. Załączam screeny.
![wowscrnshot_031016_000234](https://cloud.githubusercontent.com/assets/17753324/13653988/53c1fff4-e655-11e5-99d8-ce1d81ea4051.jpg)

**Comment by Kejmil** [comment]
przeczytaj opis spella "bane of doom"
mozesz juz zamknac to zgloszenie

**Comment by Reversion** [comment]
Ss z combat loga z widocznym info o tym jaki imp sie spawni rozwijał by wszelkie wątpliwości.

**Comment by Kejmil** [comment]
nie trzeba, on ma go na targecie, to ebon imp

**Comment by Mordorianin** [comment]
Po drugie imp z Bane of Doom pojawia się dokładnie na targecie, a ten z set bonusu na nas.
