### ISSUE TITLE
[En][Raid - Cata]Maloriak(BWD) still bugged

### ISSUE THREAD

**Issue by Alagher** [Atlantiss/BugTracker#6776]
I was about 12 hours ago on Maloriak and stil lthe same no using skill till 20% then relese all adds on second phase and wipe the raid.

**Comment by Vidyapoky** [comment]
He is working we just killed him normally

**Comment by Exertt** [comment]
He is working.

**Comment by Prodiege** [comment]
Is this fixed or not?

**Comment by Aival94** [comment]
I did it yesterday in Normal and it worked just fine.
