### ISSUE TITLE
[ENG][Skills] Feral Prowl Spell 

### ISSUE THREAD

**Issue by Coffly** [Atlantiss/BugTracker#6777]
After using prowl as feral once its not possible to use it anymore. So basically you just cant go stealth, which is by far one of the biggest class affecting bugs.

Please confirm if there were more People with that issue.

**Comment by Tomisko7** [comment]
Hi, i'm having the same issue too.
Kind regards.

**Comment by Crusaderz** [comment]
same for stealth. please fix asap.

**Comment by Kaldros** [comment]
I confirm. Prowl doesn't work after the first time. You can only activate it once.

**Comment by Aviannaqt** [comment]
rev. 4931
