### ISSUE TITLE
[EN][Skill][Mage] Presence of Mind

### ISSUE THREAD

**Issue by Netherstrider** [Atlantiss/BugTracker#6782]
Arcane Mage skill Presence of Mind also has the problem that several other skills encountered recently. It can be used only once after logging in. Any other time, you get a warning saying that 'Spell is not ready yet' and it can never be used again, unless you log out and log in again.

Unlearning the skill by changing spec doesn't help.

**Comment by Aviannaqt** [comment]
rev. 4931

**Comment by jasiudawid** [comment]
Arcane Mage I have a similar problem at Netherstrider just that I'm after using "blink". How  use blink during combat I can not use any spell, and displays the "Spell is not ready yet". This does not happen always but often. I have to log off again to reset bug.
