### ISSUE TITLE
[PL] [ stable pet] BM exotic pets and pets it get mixed

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#6787]
1.exotic pety mogą być przeniesione bez specu bm przenosząc normalnego peta na miejsce exotic peta 
2. jak jeden raz sie tak pomyli może zrobić sie bug że jak peta przeniesiemy na miejsce tego normalnego lub nadnim może nam sie zmieszać.
![wowscrnshot_031016_200322](https://cloud.githubusercontent.com/assets/8699987/13680954/2d986236-e6fb-11e5-9c34-695cbbcac101.jpg)
na tym zdjęciu przywołałem beetle a wyszkoczył mi monkey 
![wowscrnshot_031016_200507](https://cloud.githubusercontent.com/assets/8699987/13680988/598fb312-e6fb-11e5-8d2b-1fbae60aee8c.jpg)
przeniosłem tylko spedera na dół i zrobł sie wasp
![wowscrnshot_031016_200503](https://cloud.githubusercontent.com/assets/8699987/13681013/7120c9f8-e6fb-11e5-8afb-d5863e4d3b40.jpg)
jak to duplicat to usunąć

**Comment by Aieerth** [comment]
Przenosisz peta do Stable > Logout > Wchodzisz z powrotem. I tak za każdym razem gdy używasz Stable, to pomaga z duplikowaniem się petów. Jeżeli pety się nastackują na jednym slocie wsadzasz je po kolei do Stable i za każdym razem relogasz dopóki to się nie naprawi.

**Comment by arekczup** [comment]
czasami się nie da jak masz więcej petów od slotów

**Comment by arekczup** [comment]
zauważyłem że jak nawet chcę usunąć peta ze slotu to się nie da

**Comment by krecik88** [comment]
fixed in 4979
