### ISSUE TITLE
[EN][Proffession] Wispcloak recipe ( maybe more)

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#6788]
You should be able to learn this recipe from Charles Worth once you get the  (Northrend Dungeonmaster) achievement, but he doesn't offer it to you when you do get the achievement.

While I haven't tested it, if this recipe is bugged then the Deathchill cloak from the (Loremaster of Northrend) achievement might be too.

http://www.wowhead.com/npc=28699
http://www.wowhead.com/item=41609
http://www.wowhead.com/item=41610

Edit: Should be a gossip option when you talk to him.

**Comment by Aival94** [comment]
A better report with more info and links which was made by you: https://github.com/Atlantiss/BugTracker/issues/7635

Maybe you want to close this issue.

**Comment by MichaelArchangelo** [comment]
Bump 2 years later; both Deathchill and Wispcloak are still unavailable
