### ISSUE TITLE
[EN][Quest] A fitting weapon.

### ISSUE THREAD

**Issue by railsnk** [Atlantiss/BugTracker#6789]
Hi, there is no way to obtain this quest in warriors guild.
http://wow.gamepedia.com/Quest:A_Fitting_Weapon_(Alliance)
Both alliance and horde.

**Comment by Kiperr** [comment]
Did you go to Darnassus for pre quest?

> [23:30:01] Reputation with Stormwind increased by 10.
> [23:30:01] A Summons from Ander Germaine completed.
> [23:30:01] Experience gained: 160.
> [23:30:08] Quest accepted: A Fitting Weapon
