### ISSUE TITLE
[EN][Quest][Mount Hyjal] Scrambling for Eggs

### ISSUE THREAD

**Issue by Hez-Callan** [Atlantiss/BugTracker#6790]
http://www.wowhead.com/quest=25656/scrambling-for-eggs

Doing some other quests in MH results in phase issue with this quest that makes it unfinishable. I have no idea which quest is a case of this issue. I was doing [Guardians of Hyjal: Call of the Ancients](http://www.wowhead.com/quest=29390/guardians-of-hyjal-call-of-the-ancients). I've already finished  
Tortolla and Aessina parts.

I can see harpies from Shrine of Aviana, but as soon as I enter the zone with mobs, they dissaper and the whole area is empty.

The other quest in the same zone The Wormwing Problem has the same issue, but it can be finished with some help (another player in party can kill mobs).
The next quest - A Bird in Hand is going to have the same issue (I'm not able to see the item that should summon the npc for this quest).

**Comment by Foggy0260** [comment]
Happened to me too, i think it was after i completed "Aessina's Miracle"
http://www.wowhead.com/quest=25372/aessinas-miracle

**Comment by Shisai** [comment]
i'm currently having the same issue :/ kind of annoying

**Comment by MaggzWOT** [comment]
This Quest is still not working due to some phasing issue, I have found that if you are standing towards the Inn side of the quest area, and look at the harpies you can actually see an egg from a distance. However when you move towards it you are phased out of being able to see not only the harpies, but the eggs as well. making this quest un doable.

**Comment by rwystop** [comment]
yeah some chain quest is destroying that
 on my second char this is working for me on my main- not

**Comment by justmyluck** [comment]
I too have this phasing issue with the eggs; the phasing occurs when entering The Rim of the World and The Regrowth circled in WHITE but does not occur when entering/exiting The Scorched Plain circled in RED.  Would it be possible to add a few spawnable/clickable eggs to The Scorched Plain area where the phasing does not occur or affect this quest?  I think eggs are suppose to spawn there anyways.  Thanks.

![wow](https://cloud.githubusercontent.com/assets/22513570/18941381/88daf1ea-85c5-11e6-8e36-8372bed20bbb.jpg)

**Comment by Thorghar** [comment]
Eggs still does'nt exist...

**Comment by MaggzWOT** [comment]
The eggs do exist provided you do the quest prior to changing the phasing of the zone by doing the turtle quest line. I just did this line on my DK and if you do that section first you are then able to complete the quest line properly. However if you do not do it when you receive the quest, and get that turle line phasing complete, you can not do it at all after this.

**Comment by RastaTinu** [comment]
Still doesn't work

**Comment by Hernajs** [comment]
Still not working.

**Comment by xStiven** [comment]
Yep very annoying that such simple bug is still wan;t been fixed after all that time ;/

**Comment by MaggzWOT** [comment]
It is really just a phasing bug, After leveling a couple more characters, I have found that if you do the quests leading up to this as soon as you get them from the world tree in Hyjal. And then go to the roost and do them without doing the turtle section prior the phasing is fine, So in essense the quest isn't bugged, its just out of phase if you progress the other chain prior.

**Comment by Samineh** [comment]
Bump

**Comment by tomatosz** [comment]
Post an indirect fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15074-quest-the-last-living-lorekeeper-hyjal-phasing-issue/

**Comment by Buggingtrack** [comment]
An indirect fix would be @justmyluck 's suggestion, since there are no phasing problems in the Scorched Plain zone, might as well put some eggs there, and you are able to do the quest regardless of the phasing bugs in the zone you are supposed to get them...

**Comment by tomatosz** [comment]
In this case my fix indirectly causes the phasing issue to not happen anymore (or rather not until you've done the aviana quests). If you're already bugged you will need gm assistance

**Comment by Jenovas** [comment]
Fix in rev 5538
