### ISSUE TITLE
Stucked at Acherus, can't do anything.

### ISSUE THREAD

**Issue by n1mbler** [Atlantiss/BugTracker#6791]
Hello, I'm stuck at Acherus, starting location of DK's i can't do anything i can't see any npc's, i tried unstuck, friends tried to help me teleport to the graveyard doesn't work, and hearthstone is the thing what got me here. 
pls help me 
thank you
My acc name is : fenny
my character name is : Goodfellow

**Comment by Luna-maria** [comment]
probably best to make a ticket and mention which quest you're on, sounds like a phasing issue
