### ISSUE TITLE
[EN] [NPC] Burnished Legplates of Might

### ISSUE THREAD

**Issue by TonyHawkings** [Atlantiss/BugTracker#6793]
How it works- NPC named Shay Pressler is giving Burnished Legplates of Might for free without sell price.
How it should work- NPC named Shay Pressler should sell Burnished Legplates of Might for:

1500 gold at Neutral
1425 gold at Friendly
1350 gold at Honored
1275 gold at Revered
1200 gold at Exalted

with sell price 375 gold. Actually items at Neutral and Friendly level of reputation shouldn't be able to buy, but character which are in guild should be able to see it.

ID's:

Burnished Legplates of Might- 69888
Shay Pressler- 46602

**Comment by Aviannaqt** [comment]
duplicate
