### ISSUE TITLE
[EN][Raid][Firelands] Eternal Embers

### ISSUE THREAD

**Issue by zielonazabka** [Atlantiss/BugTracker#6797]
Hello , I wanted to report a bug , it's about the eternal ember (legendary quest) , this item should be able to distribute the master loot , now it may raise everyone who has a quest , the problem lies in the fact that this item is soulbound When will it raise

**Comment by Thefakemccoy** [comment]
The master looter has no control over embers. Only a player with the quest can see the embers. So if a warrior is the master looter he can not see the item so he can not hand them out.

**Comment by Aviannaqt** [comment]
#6713
