### ISSUE TITLE
[EN][Raid] Raid Lock Popup Showing When It Shouldn't 

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#6804]
1) Enter raid instance
2) Kill boss
3) Sit out for another player for next boss kill
4) Going back into raid for 3rd boss kill and enter raid instance
5) Raid lock popup shows up saying would you like to accept the raid ID with 2/## bosses killed

The raid lock popup shouldn't show up since you were already saved to the instance in the first place, your raid lock should be updated automatically when additional kills happen on the same lock

**Comment by Aival94** [comment]
During cataclysm the Flexible Boss-based Lockout System was introduced and till end of Cataclysm no change have been done. In this system is working with the pop up message and if you accept and you kill a boss you got saved for the prev bosses as well.It does not matter if you were there already for an other boss and you left and you returned. Only thing it matter is if you were there when they killed the boss.

Wowpedia Link: (Flexible Boss-based Lockout)[http://wow.gamepedia.com/Raid_lockout#Flexible_Boss-based_Lockout]
Wowwiki Link: (Patch 4.0.1)[http://wowwiki.wikia.com/wiki/Patch_4.0.1]
