### ISSUE TITLE
[EN][Spell] Distract

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#6808]
Distract doesn't stop mobs that are on a patrol path from moving for the duration of the distract

**Comment by Thefakemccoy** [comment]
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com

**Comment by Prodiege** [comment]
Was this fixed?

**Comment by Thefakemccoy** [comment]
Prob not but any open tracker that dont follow the tracker rules are subject to close.

**Comment by Thefakemccoy** [comment]
That's why i commented to add links to your report.
