### ISSUE TITLE
[EN][Dungeon-Cata] Zul'Aman - Pets Can Pull Halazzi Through His Door

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#6810]
Pets can run through the Halazzi door and pull the boss out of his room. Could just do a simple leash fix for this

**Comment by Thefakemccoy** [comment]
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com

**Comment by Prodiege** [comment]
Was this fixed?
