### ISSUE TITLE
[PL/ENG] QUEST BUG HOWLING MAD

### ISSUE THREAD

**Issue by Rasiden123** [Atlantiss/BugTracker#6818]
PL: Cześć! Quest howling mad nie działa, gdyż trakar powinien być w klatce, a jest w namiocie. I po wandalach również nie ma śladu.. Proszę o szybką interwencję gdyż to uniemożliwia dalszą grę.
Mój nick w grze: Sheeya Z góry dizęki.

Eng: Hi! Quest Howling Mad doesnt work. Trakar who must be in cage, be in tent.. And there are not wandals. I need this quest, to continue exp, so please for fast help.. My nickname ingame: Sheeya, and my login is Rasiden123. Thank  you.

**Comment by Kiperr** [comment]
Read how to report bug to bug tracer, then report it properly with wowhead links.

**Comment by Bastek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
