### ISSUE TITLE
[EN][Item] Reputation enchants

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#682]
Since patch 4.2 BoA enchantments don't require reputation to use them. You only need appropriate reputation to buy them 

http://www.wowhead.com/item=62366/arcanum-of-the-earthen-ring#comments

Second comment

http://www.wowhead.com/item=62366
http://www.wowhead.com/item=68765
http://www.wowhead.com/item=68766
http://www.wowhead.com/item=68763
http://www.wowhead.com/item=50368
http://www.wowhead.com/item=44139
http://www.wowhead.com/item=50367
http://www.wowhead.com/item=50370
http://www.wowhead.com/item=50373
http://www.wowhead.com/item=44133
http://www.wowhead.com/item=44135
http://www.wowhead.com/item=50337
http://www.wowhead.com/item=44134

**Comment by sabi102** [comment]
Wymienianie wszystkich itkow w sensie naprawienie tego? Oczywiscie jest to przydatne - teraz trzeba kazdym altem reputacje wbijac, zeby uzyc enchanta, kiedy powinno wystarczyc posiadanie reputacji na glownej postaci..

**Comment by PierwszyKrytykRP** [comment]
wymienianie w sensie wowhead link do kazdego z osobna

**Comment by Piklo** [comment]
posted fix on forum
http://community.atlantiss.eu/index.php?/topic/12515-682-wotlk-and-cata-boa-reputation-enchants/
