### ISSUE TITLE
[PL/ENG] Portal The Maelstrom

### ISSUE THREAD

**Issue by Tytan1996** [Atlantiss/BugTracker#6823]
PL: Byłem w lokacji The Maelstrom, był bug serwera i zginąłem, odrodziłem się w Stormwind. Teraz nie mam tego teleportu.

ENG: Byłem w lokacji The Maelstrom, był bug serwera i zginąłem, odrodziłem się w Stormwind. Teraz nie mam tego teleportu.

**Comment by Thefakemccoy** [comment]
Well the ENG was in polish so what i got from translate. You have to turn in the quest you get from thrall in the maelstrom to unlock the portal if you die dismount or join a queue before you land and turn in the quest the portal will not open.

**Comment by Aival94** [comment]
Related to: https://github.com/Atlantiss/BugTracker/issues/3104
