### ISSUE TITLE
[PL][Spell][Warrior] - Charge stun

### ISSUE THREAD

**Issue by battleleet2** [Atlantiss/BugTracker#6824]
Cześć!

W skrócie, warrior po wykonaniu chargy najpierw powinien dostać się do celu, w tym momencie zaaplikować stun z charge, na atlantiss jest odwrotnie, najpierw stun, potem charge, a w efekcie celu nie da się spowolnić, a często jest poza zasięgiem (odskok, mount etc)

https://www.youtube.com/watch?v=UWeB-regDi0

tak to mniej więcej wygląda u nas

![wowscrnshot_031216_205811](https://cloud.githubusercontent.com/assets/1586224/13725297/8d92f692-e895-11e5-91ce-07aabc9ad3ad.jpg)

**Comment by BialyADI** [comment]
Dodatkowo nadal nie da się użyć Charge w niektórych miejscach na Arenach tak jak w tym zgłoszeniu: https://github.com/Atlantiss/BugTracker/issues/6505.

**Comment by blinkmaster** [comment]
No właśnie po fixie na coś takiego by się zaczęły outjumpy charge jak na tbc i wotlk :) ja bym się cieszył,  że to tak działa tu

**Comment by battleleet2** [comment]
to działa jak na wotlk i bc... w tym właśnie problem, zobacz na screen, target ma stuna, zanim do niego dotarłem

**Comment by Kuszki** [comment]
Dodam, że podczas aktywnego [Deterrence](http://cata.openwow.com/spell=19263) stun z Charge jest aplikowany, mimo, że nie powinien.

**Comment by battleleet2** [comment]
bump? sens bumpować?

**Comment by Kochany** [comment]
@Kuszki Nie tylko stun z charge jest aplikowany, throwdown tez jakims cudem stunuje, ale nie dmguje w detera. Domyslam sie, ze podobnie jest z innymi tego typu rzeczami

**Comment by lamaATS** [comment]
Fixed in rev. 5232

**Comment by BialyADI** [comment]
Lama to nie tylko dotyczy Charge ale też Intercepta.

**Comment by lamaATS** [comment]
Tak wiem i będe to robić dziś zaś zgłoszenie było tylko o **Charge**.

**Comment by lamaATS** [comment]
Napiszę też to tutaj na globie przez ich błędnie opóźniane aplikowanie aur (nie zawsze) powstawało złudzenie że **Stun** jest aplikowany w momencie dotarcia do celu co jest błędne gdyż sam stun rozpoczyna już być castowany chwilę przed samą szarżą.
