### ISSUE TITLE
[EN][Hunter][Spell] Freezing Trap

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#6825]
Freezing trap should trap the nearest target to it.The problem atm is that you cant eat the trap to save your partner in arena it mostly always traps the 1 target it was near to it.Was literaly standing on the trap and it still trapped my partner that was 5 yards away from it..

**Comment by blinkmaster** [comment]
y but its pretty much impossible to find proof for that beside fact servers like AT had it working meh,

**Comment by Jenovas** [comment]
I can say that this report is true.
I watched many 3v3 Arena videos not long ago and I remember that every time a heal got scatter shotted he would yell for someone to run to him to eat the trap before it activates.
If I find the videos I watched I'll add them here or I'll just try to fix it since I know that it should work this way.

**Comment by kadi2** [comment]
I'd say it's working fine. It happened to me once or twice that i didn't menage to eat the trap, but most likely it always worked for me.

**Comment by jissabraham** [comment]
Pet companions are getting trapped sometime it shouldn't happen

**Comment by crosik** [comment]
"Pet companions are getting trapped sometime it shouldn't happen" - bullshit

**Comment by kadi2** [comment]
@crosik He meant non-combat pet compannions for sure.

**Comment by blinkmaster** [comment]
@lamaATS  can you take a look at this trap activation mechanics?

**Comment by lamaATS** [comment]
Problem is that currently server searching for any player in spell range (it's 10yd for **Freezing Trap** some addition is good) but problem is that this search ignore distance so any player in range is valid so bug may happen randomly.

**Comment by lamaATS** [comment]
I found this issue on TC report and I will port fix to this. (so BIG thanks to TC community)

**Comment by lamaATS** [comment]
Fixed in rev. 5239
