### ISSUE TITLE
[EN][Molten Front][Quest]The Forlorn Spire

### ISSUE THREAD

**Issue by sherrwood** [Atlantiss/BugTracker#6829]
I just unlocked the shadow wardens (get 150 marks) but now i cant make progress with this quest. I cant talk with anyone and elite on end dont spawn. I read other topics where this should works but i think its something wrong. Any ideas? I dont unlock yet a druid of the talons.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/5727
