### ISSUE TITLE
[EN][Racial][Night Elf] Shadowmeld

### ISSUE THREAD

**Issue by MorbidMike** [Atlantiss/BugTracker#6830]
You should be able to use abilities that require Stealth out of Shadowmeld (such as Ambush or Pounce). At the moment this is bugged and you can not use any ability that requires Stealth from Shadowmeld.

[Elitist Jerks Rogue guide](http://forums.elitistjerks.com/forums/topic/118015-cataclysm-subtlety-compendium/)

Night Elf

Previously one of the worst races for Sub, they are now very strong. With a slightly higher base agility, and the ability to Ambush out of Shadowmeld for added Find Weakness uptime, Night Elves 
are a very strong option when Shadowmeld can be reliably used.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/475
