### ISSUE TITLE
[EN][Warlock][Felhunter] Spell Lock delay

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#6832]
Warlock's Felhunter pet casts Spell Lock http://www.wowhead.com/spell=19647/spell-lock with close to a 1 sec delay. 1 sec in PvP is more than enough to fakecast and cheat.

I tested this with macros, I tested it with manual click on Spell Lock from pet's toolbar - the delay is the same. Interrupt abilities are supposed to be instant.

**Comment by kadi2** [comment]
interrut is always instant, but the silence effect is delayed with higher diff on the server.

**Comment by captjvmoore** [comment]
Sooo Affliction is broken too. OK, going back to Destro :)

**Comment by phifedawg** [comment]
should be fixed in revision 4938 afaik.. can someone close this?
