### ISSUE TITLE
[PL][Quest][Maelstrom][Deepholm, Realm of Earth]

### ISSUE THREAD

**Issue by anetka21pl** [Atlantiss/BugTracker#6835]
Rozpocząłem quest, wszystko przebiegało bez problemu do momentu DC. Po zalogowaniu spadłem z quest mounta ginąc w teksturach. Zrespiłem się w Westfall, wracam do Stormwind i już nie ma możliwości powrotu ani do Maelstrom ani Deepholm. Quest anulowałem z nadzieją, że portal pojawi się znów, ale niestety go nie ma. Jest to mój pierwszy ticket, więc proszę o wyrozumiałość. Nie wiem jakie są możliwości rozwiązania problemu - jeżeli da się 'cofnąć' jeden quest i exp za niego, abym mógł sprobować ponownie ze Stormwind to byłoby miło. Ewentualnie teleportowanie mnie do Maelstromu.

#3104

**Comment by Anhaeyn** [comment]
Ile razy było to zgłaszane i odpowiadano, by użyć potion of Deepholm...

**Comment by anetka21pl** [comment]
To niech ogarną serwer i zaczną dbać bo coś słabo im to idzie. Ludzie zgłaszają i są coś im winni, a nie użyj potiona... nawet na ah go nie ma. Zapewne mają możliwość cofnięcia questa. Fakt mam hearthston bo wyszłam z insty ale zależy mi na portalu i quescie,a nie na kupowaniu badziewnych potionów.

**Comment by anetka21pl** [comment]
dziekuje :)
