### ISSUE TITLE
(PL) enginering trinker problem

### ISSUE THREAD

**Issue by scylus** [Atlantiss/BugTracker#6838]
Mam nadzieje ze umieszczam post zgodnie z regulaminem . mianowicie trinker ktory nakladamy na peleryne z inzynieri tak zwany spadochron po uzyciu powinien automatycznie sie zdeaktywowac gdy gracz wejdzie w interakcje z ziemia . niestety tak nie jest . pozdrawiam

**Comment by fafal** [comment]
Nie umiesciles tego zgodnie z regulaminem, bo nawet go nie przeczytales.

**Comment by scylus** [comment]
No wiec zamknijcie i zignorujcie kolejny wpis. Skupcie sie na tym kto jak przedstawia problem a nie na tym jak problem rozwiazac. . temat do zamkncia. I oszczedzcie sobie komentarzy typu . nie wiesz jak korzystac nie korzystaj. Zegnam

**Comment by fafal** [comment]
Ostatni post przedstawiłem ci co jak i dlaczego.
Jeżeli nie potrafisz dostosować siędo najprostrzych zasad i pokazujesz tylko głupote i brak umiejetnosci czytania ze zrozumieniem to moze racja, lepiej nie korzystaj z BT.

**Comment by scylus** [comment]
Tak tak masz zapewne racje.
