### ISSUE TITLE
[PL][Priest][Absorption][Power word: shield & divine aegis] Za mało absorbu

### ISSUE THREAD

**Issue by Venomenalny** [Atlantiss/BugTracker#6839]
Witam, wszystko powinno być ładnie opisane w załącznikach, ale po krótce wytłumacze: 
Bańka ( obie bańki ) disco priesta absorbują za mało. Zauważyłem to z czasem, kiedy zreforgowałem się pod mastery, żeby zobaczyć czy warto. 
Jak się przekonacie - narazie nie warto ( mam nadzieje, że narazie ).

Obliczenia rozwieją wątpliwości. 

Jeżeli coś, źle pokombinowałem to upomnijcie mnie, ale nie wydaje mi się. 
![wowscrnshot_031416_141710](https://cloud.githubusercontent.com/assets/16546340/13745866/b18778f0-e9f0-11e5-88dc-b6f442311409.jpg)
![wowscrnshot_031416_141714](https://cloud.githubusercontent.com/assets/16546340/13745869/b44a7f88-e9f0-11e5-83cd-69156fec3027.jpg)
![wowscrnshot_031416_141736](https://cloud.githubusercontent.com/assets/16546340/13745874/b7ef2f12-e9f0-11e5-85b0-25e9a9ef725d.jpg)
![wowscrnshot_031416_141751](https://cloud.githubusercontent.com/assets/16546340/13745880/bb056180-e9f0-11e5-957d-faa7be5b888f.jpg)
[Mastery a bańka.txt](https://github.com/Atlantiss/BugTracker/files/172010/Mastery.a.banka.txt)

**Comment by Erthar** [comment]
Na końcu są te "kluczowe" obliczenia.

**Comment by blinkmaster** [comment]
no faktycznie. szkoda, ze robione na 0 spellpower. 
boze.

**Comment by Erthar** [comment]
To jest kwestia 400 absorbu bez mastery i około 1,2k +/- z potką, inner fire i buffem raidowym. 
Faktycznie, mogłem zrobić ze spellpowerem, żeby "było widać" ale to nie o taką różnicę chodzi.

**Comment by blinkmaster** [comment]
coef to 0.87 sp.
czyli okolo 8k absorbu brakuje ze spellpoweru.

**Comment by Venomenalny** [comment]
Bez buffów: 8793 > 26k absorbu
Z buffami >  9980 >  28k absorbu

9980 - 8793 = 1187 / 1187 x 0.8 ( bo jest podane od patchu 3.2.0 że jest to 0.8 COEF ) =
= 949 + 8136 ( power word shield upgrade ) = 9085
9085+28k = 37k 

Masz racje, ale teoretycznie, nie praktycznie.

**Comment by kadi2** [comment]
Bardzo proszę o zachowanie jakości tytułu oraz treści pierwszego posta do obowiązujących zasad BugTrackera!

**Comment by blinkmaster** [comment]
nadal nie rozumiesz.
pomoge.

bez buffow masz 8793 spell power.
liczymy coefem z 4.3.4 który wynosi 0.87
[8793 x 0.87] + 8136 = 7649,91 + 8136 = 15785,91
z buffami masz 9980 spell power
[9980 x 0.87] + 8136 = 8682,6 + 8136 =  16818,6

teraz lecimy z masterka ktora masz gdy jestes ubrany tj. 41% wiekszy absorb

bez buffow : 15785.91 x 1.41 = 22258, 1331
z buffami : 16818,6 x 1.41 = 23 714,226

taki powinienes miec absorb z samych itemow + masterka

domyslam sie, ze w gre wchodza jeszcze jakies talenty.
te talenty teraz mnoz i wyjdzie Ci.
nie ma tutaj buga.

**Comment by Jenovas** [comment]
Totalnie źle to liczysz. Wzór na PW:S to
Total shield=${((($SP*0.87)+$m1)*$<mastery>*$<spirit>*$<twin3>*$<ipws2>)}

Czyli w Twoim przypadku absorb powinien wynosić około 29k.
Nie ma buga, zamykam.
