### ISSUE TITLE
low level mining - copper not excessible

### ISSUE THREAD

**Issue by redneckdad** [Atlantiss/BugTracker#6840]
Has anyone had this problem, shows on map but when at location it is in a tree or under ground and can not get to it. I even took screen shots showing the ground sparkling but can not click on ore. Can this be fixed?

**Comment by Luna-maria** [comment]
there are a lot of issues with mining/herbing nodes, reported in several other cases. they said they'd ran some fixes a while back but I guess it's still a mess :/
