### ISSUE TITLE
[PL][Quest]Reputacja dla Holdir - Cold Hearted

### ISSUE THREAD

**Issue by ksantypa** [Atlantiss/BugTracker#6848]
http://www.wowhead.com/quest=12856/cold-hearted

Mobki które smoczysko ma zabrać są dla huntera widoczne przy użyciu Track Humanoids ale najprawdopodobnie siedzą w teksturze bo nie można ich zobaczyć w grze.

**Comment by Aviannaqt** [comment]
#6601
