### ISSUE TITLE
[EN][Talent][Hunter] Improved Steady Shot

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#685]
Spells like scatter shot, concusive shot and probably many more should reset Improved Steady Shot counter but they don't it. Works fine with basic damaging shots like Arcane shot or Aimed shot

"Sometimes you have to stop your second steadyshot to do something important like scatter/trap or Silencing Shot, however, it's not too difficult to get this buff applied in my opinion." // Quote from Skill Capped forum

http://youtu.be/3z_XozRwEGA?t=1m15s // Steady Shot -> Silencing Shot -> Steady Shot
http://youtu.be/3z_XozRwEGA?t=7m23s // Steady Shot -> Scatter Shot -> Freezing Trap -> Steady Shot

http://cata.openwow.com/spell=53220 // Improved Steady Shot

**Comment by Wolffenstein** [comment]
Fixed in rev 4223.
