### ISSUE TITLE
Terokkar Forest Skettis Skull Pile

### ISSUE THREAD

**Issue by quarin** [Atlantiss/BugTracker#6850]
I click at skull pile with 10 time-lost scrolls and it says "Greetings" instead of giving me choice to summon one of 4 minibosses. Becouse of that you can't grind fast Rep. Fix fast pls :)

**Comment by Dziara** [comment]
Have you completed quest chain which involves killing those minibosses?

**Comment by Aviannaqt** [comment]
its working

**Comment by coba999** [comment]
It doesn't working.
