### ISSUE TITLE
[EN][Class][Night Elf] Shadowmeld won't drops combat

### ISSUE THREAD

**Issue by hydewing** [Atlantiss/BugTracker#6852]
Shadowmeld doesn't drop combat when cast in PvP and PVE combat.

**Comment by aneq** [comment]
I'm pretty sure it does drop combat in pvp, and it's not supposed to drop combat in pve. The only situation in which it will drop pve combat is when the mob has nothing else in his threat list and it goes into evade mode.

**Comment by jissabraham** [comment]
how about feigndeath it should drop combat

**Comment by aneq** [comment]
same rules apply, during pve encounters you should never be able to drop combat

**Comment by Thefakemccoy** [comment]
Shadowmeld and Feign Death will only drop combat in PvE when you are the last player alive. The whole raid/party and pets must be dead or dismissed in order for the ability to drop combat. Other wise it is only a threat drop.

**Comment by hydewing** [comment]
That's why I can't not use any openers!!
According to elitistjerks, I should able to use Ambush (rouge) during the Shadowmeld stage.

http://forums.elitistjerks.com/forums/topic/118015-cataclysm-subtlety-compendium/

**Comment by Avalain** [comment]
I'm 100% sure it should drop you out of combat. 
I used it to reset Hagara the Stormbinder in Dragon Soul with full raid alive.
As a rogue I should be also able to move from shadowmeld to stealth.

Some conversation from MMO-Champ to back it up:
http://www.mmo-champion.com/threads/1318820-Night-Elves-Shadowmeld-and-it-s-uses-as-a-Rogue-(PvP)

**Comment by lamaATS** [comment]
Fixed in rev. 5486

**Comment by Zhalox123** [comment]
https://us.battle.net/forums/en/wow/topic/16528042667

Says here that it got bugged on 6.1 patch till then it removed combat in PVP so yeah in PVP it should remove but still clueless about PVE.

Shadowmeld's (Night Elf racial) functionality received a bug fix in Patch 6.1 to address a number of issues with the ability that wound up affecting its behavior in PvP combat. A hotfix is being worked on (it's not ready yet) that will restore Shadowmeld back to the way it worked (while keeping the bug fixes intact).
Posted by Blizzard GM
