### ISSUE TITLE
[PL][Quest][Thunder Bluff][Daily] Craving Crayfish

### ISSUE THREAD

**Issue by HUMBOL** [Atlantiss/BugTracker#6853]
Niedawno dodany daily quest z fishingu nie działa jak powinien. "Rybki", które należy zebrać z jeziora (http://www.wowhead.com/item=69977/stonebull-crayfish), są wrogie i można je tylko zabić, a powinno dać się je podnieść tak, jak w analogicznym quescie w Origrimarze (http://www.wowhead.com/quest=26226/crawfish-creole).

Quest: http://www.wowhead.com/quest=29349/craving-crayfish
Jak powinno działać: https://www.youtube.com/watch?v=kdr22Y0DnTk
Jak jest: http://screenshot.sh/n9CJ4ALwp8XA2

**Comment by Bastion** [comment]
@Kiperr
