### ISSUE TITLE
[EN][Quest][Zangarmash] As the Crow Flies

### ISSUE THREAD

**Issue by Driacom** [Atlantiss/BugTracker#6857]
http://www.wowhead.com/quest=9718/as-the-crow-flies

This item http://www.wowhead.com/item=25465/stormcrow-amulet doesn't tranform me into a crow.

Proof:
http://imgur.com/xX3AWj9
http://imgur.com/A8HlfDG

I'm on a invisible mount.

How should it work:
https://www.youtube.com/watch?v=uLwUXkGa2AE

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3236
