### ISSUE TITLE
[EN][Hunter]Camouflage

### ISSUE THREAD

**Issue by Damozaur** [Atlantiss/BugTracker#6858]
Rogues can sap hunter's in Camouflage on this server. Which is just hilarious.
also rogues can broke camouflage by distract 

http://cata.openwow.com/spell=1725 distract
http://cata.openwow.com/spell=51753 = Camouflage
http://cata.openwow.com/spell=6770 = Sap

**Comment by crosik** [comment]
http://us.battle.net/wow/en/forum/topic/19072467641

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6466
