### ISSUE TITLE
[PL][Searing Gorge] [Quest] Lunk`s Adventure: Redan`s Weakness

### ISSUE THREAD

**Issue by pistonkosiarz** [Atlantiss/BugTracker#6868]
Misja polega na pogadaniu z Guardami w wiosce (Iron Summit, przyblizone kordy: (40,0:70,0)) aby te dołąćzyły do szalonego tańca, jednak guardy nie wchodza w interakcję.

Według komentarzy na WoWheadzie;

> At least as of today, it's enough to simply just walk up to a guard and talk to them (e.g., rightclick and choose the "Want to join in?" Option). No need for a macro or any kind of /-emotes.
> 
> Apart of that: Awesome quest. Lunk for the win. =)

Dodaje również screen z miejscówki questa, nie mam jednak jak pokazać tego że nie wchodzą w interakcję.
![wowscrnshot_031616_154045](https://cloud.githubusercontent.com/assets/17881158/13816410/93431896-eb8e-11e5-8a5e-06eefc9507f6.jpg)

**Comment by Kiperr** [comment]
Should be fixed after rev 4937, some of guards propably doesnt despawn when other player complete quest.
