### ISSUE TITLE
[PL] [Badlands] [Quest] Lifting the Veil

### ISSUE THREAD

**Issue by pistonkosiarz** [Atlantiss/BugTracker#6869]
NPC jest zlokalizowany w Badlands (66.4 55.3). Po zaakceptowaniu misji w tle powinien pojawic się smok : 
Screenshot:
[http://wow.zamimg.com/uploads/screenshots/normal/254261-lifting-the-veil.jpg]
Film:
[https://youtu.be/Egz2AsdgOpo](url)

jednak po wcięciu questa nie dzieje się nic. Blokuje on ukończenie tej krainy i achievmenta: Badlands Quests.

**Comment by Kiperr** [comment]
Duplikat #1632
