### ISSUE TITLE
[EN][Char][My Char Farts]

### ISSUE THREAD

**Issue by sashatje** [Atlantiss/BugTracker#6872]
Soooo, this is a bit embarrassing.

Every 5 seconds my char emits green fumes that really make it look like she farts.

Take  a look: https://drive.google.com/file/d/0B7aGk8N8CdpGZW9qNDl1WENXR2c/view?usp=sharing

I tried re-logging, re-starting, /script RePopme() which did nothing.

I tried taking off all the gear (I thought maybe there was something weird about it, I mean, I'm wearing the Ring of the Quenched Inferno). Nothing helped.

Anyway, what I think happenned is I was questing and one of the quests supplied me with this unique, fragrant green aura. Which just didn't disappear afterwards.

Any help would be welcome! :)

**Comment by kadi2** [comment]
Did you try http://www.wowhead.com/item=44114/old-spices ?

**Comment by xolon** [comment]
this happens to my hunter and pet, like literary for 1 year almost

**Comment by phifedawg** [comment]
i've had this ranomdly occur to me but then again it randomly disappeared as well. I think it has something to do with rogue's poison animation staying after death.

**Comment by kadi2** [comment]
The animation is supposed to appear if you stand on some green ground i guess? Like in durotar you are supposed to make a dust.

**Comment by Kiperr** [comment]
Write a ticket in game to game master and he will remove that spell from you.
