### ISSUE TITLE
[EN] [Arena] Item that should not be usable

### ISSUE THREAD

**Issue by 1Andas** [Atlantiss/BugTracker#6877]
Night elf rogue with tauren visual, as seen in the picture provided.

![wowscrnshot_031716_150439](https://cloud.githubusercontent.com/assets/10603375/13849086/e36e139a-ec54-11e5-8c8f-319c5e9fd7a9.jpg)

The item used is http://www.wowhead.com/item=30544/ultrasafe-transporter-toshleys-station

I am pretty sure such items should not be usable in arena.

Cheers.

**Comment by Kiperr** [comment]
Item you link dont have any transformation effects.

**Comment by Fearyourself** [comment]
The item isn't useable in arenas, only outside of arenas and it was like this on retail. Please link proof

**Comment by 1Andas** [comment]
Link proof of what?

**Comment by Fearyourself** [comment]
Link proof of the item being used in arenas. I've got the item and I tried it myself. You can't use it inside arena, only outside of arena. What I'm saying is there's no difference if it's a tauren or a night elf you're fighting. The buffs never went away when entering arena on retail either

**Comment by 1Andas** [comment]
Well, why don't you link the proof from retail to confirm what you just said? Because we're not taking your word for it, you know.
