### ISSUE TITLE
[EN][Raid-WoTLK][Naxxramas]-Khel'thuzad

### ISSUE THREAD

**Issue by SpiritHealerV** [Atlantiss/BugTracker#6878]
Starting event works terribly. Belchers are falling under textures. But the worst thing is that after killing all mobs Khel'thuzad never disables the shield. The boss is just unbeatable.
Tip: Would be ok if Khel will engage after few minutes from start of the event. 

Cheers!

**Comment by Bildo** [comment]
duplicate
