### ISSUE TITLE
[PL][Spell][Shaman] Ancestral Resolve

### ISSUE THREAD

**Issue by Hextall** [Atlantiss/BugTracker#6880]
[Ancestral Resolve](http://cata.openwow.com/spell=77830) wydaje się że nie działa. Testowane przy pomocy [Death and Decay](http://cata.openwow.com/spell=43265) i [Blood Boil](http://cata.openwow.com/spell=48721), gdzie dmg jest stały. Dmg zadawany szamanowi w czasie castowania i niecastowania przez niego niczym się nie różni.

**Comment by calladin** [comment]
a sprawdziles, czy przypadkiem nie daje 10% redukcji cały czas?^^

**Comment by Hextall** [comment]
Sprawdzone. Nie ma żadnej różnicy. Wychodzi na to, że talent nie działa w ogóle.

**Comment by lamaATS** [comment]
Fixed in rev. 5229
