### ISSUE TITLE
[en][mage]Deep Freeze & rof should share DR

### ISSUE THREAD

**Issue by crosik** [Atlantiss/BugTracker#6882]
as stated in topic dr's should be shared.

[Ring of Frost]	drs with	Disorient + Deep Freeze
[Deep Freeze]	 drs with       Controlled Stun + Ring of Frost

http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by Reversion** [comment]
Cataclysm-Logo-Small Patch 4.2.0 (2011-06-28): Deep Freeze and Ring of Frost will cause diminishing returns on each other, in addition to the spells they normally share diminishing returns with.

http://wowwiki.wikia.com/wiki/Ring_of_Frost

**Comment by Aviannaqt** [comment]
#5396
