### ISSUE TITLE
[PL][BG] FLAGA NA INVISIBLE

### ISSUE THREAD

**Issue by Jallar89** [Atlantiss/BugTracker#6883]
Gracze przejmują flagi na bg nie wychodząc nawet z invisible'a. 
Po pierwsze invisibility potion nie powinien chyba działać na bg.

**Comment by fruvel** [comment]
powinien, ale uzycie invi umozliwia niesienie flagi

**Comment by Jallar89** [comment]
Oj źle się wyraziłem. Chodzi o flagi na bazach (AB,BoG). 
Czy kliknięcie, żeby przejmować bazę nie powinno kończyc invisible'a tak jak kończy chociażby stealtha ?

**Comment by Jenovas** [comment]
Should be fixed in rev 4980.
