### ISSUE TITLE
[EN][Quest][Lost Isles] Unable to level character until issue resolved (quest Rocket Boot Boost)

### ISSUE THREAD

**Issue by Paoni** [Atlantiss/BugTracker#6885]
I posted my bug here [https://github.com/Atlantiss/BugTracker/issues/3593](https://github.com/Atlantiss/BugTracker/issues/3593), because it is a quest issue for the zone (which the thread is concerning), but because it is an older thread and my issue has stalled my character from doing any further leveling, I'm creating this thread with the hope that someone will see this and address my issue a lot sooner, so I can continue playing my character.

**Comment by Paoni** [comment]
Quest still has a problem.  NPC's are out of place, but was able to find the location to activate the rocket boots for this quest and was able to level out of the zone.

**Comment by karhima** [comment]
You can use the boots at the location where the NPC is supposed to be at the Lost Peak (coords 51.8, 47) [http://wowwiki.wikia.com/wiki/Coach_Crosscheck](url)
