### ISSUE TITLE
[EN][Spell][Druid] Swift Flight Form

### ISSUE THREAD

**Issue by Foggy0260** [Atlantiss/BugTracker#6887]
If you go to a trainer and learn Swift Flight Form without having the Artisan riding skill, you will no longer be able to use Flight Form at all, since Swift Flight Form replaces your old Fligh Form.

**Comment by DuGalle** [comment]
Not working since god know when i abandon my druid coz of this bug to ride a mount as druis is just wrong

**Comment by Fapguy** [comment]
DuGalle, if you abandon a character just because of a small bug like this....
It was always possible to just go learn the artisan skill required.

**Comment by Luna-maria** [comment]
it's not a small bug -.- old flight form should not disappear from your spell book when you learn swift flight form. It should just be gone from the little action bar in your UI.

**Comment by Haz3L** [comment]
Fix it already goddammit! [High priority]

**Comment by Jenovas** [comment]
Should be fixed in rev 5012
All druids will have Swift Flight Form removed (please visit a trainer and buy it again)
To be able to buy Swift Flight Form from a trainer the Druid must have Artisan Riding
