### ISSUE TITLE
[PL][Quest][Mount Hyjal] A Ritual of Flame, quest zbugowany przez DC

### ISSUE THREAD

**Issue by Cargo2bull** [Atlantiss/BugTracker#6888]
Ukończyłem quest poprzedzający (Opening the Door). Zacząłem quest z tytułu posta, i nastąpiło DC. Po ponownym zalogowaniu się quest zniknął z questloga, nie mogę go wziąć ponownie, a Carbonite pokazuje, że ostatnim questem, jaki ukończyłem z tego cyklu, jest Opening the Door.

**Comment by Aviannaqt** [comment]
Napisz ticket
