### ISSUE TITLE
Bugged Mission

### ISSUE THREAD

**Issue by FinraX** [Atlantiss/BugTracker#6889]
Hi i wanna Play Goblin in Horde and i have a missions Necessary Roughness he is bugged i can't aim on steamwheedle shark...

**Comment by Luna-maria** [comment]
fix title to guideline standards or they'll close the thread
also have you tried killing it yourself without the item?

**Comment by Anhaeyn** [comment]
Kill these mobs without using quest item - it will work, and these mobs dont hit too hard, so it's not really a problem. Ofc, you should be able to use quest item and kill these mobs, but it's completable, like all other goblin quests.
