### ISSUE TITLE
[EN][NPC][Eastern Plaguelands] Beezil Linkspanner

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#6894]
Beezil Linkspanner is still not giving me the option or and text at all so he can join the caravan and award the achievement.  This was recently listed as working in the server revisions. Thank you !

**Comment by Thefakemccoy** [comment]
Changelog 4.3.4


rev. 4941 Author: Wolffenstein :: 2016-03-18 18:10 - **Waiting for update**
[Eastern Plaguelands]:

Added gossip text and option to Beezil Linkspanner. It will now be possible to obtain "Full Caravan" achievement.

**Comment by Thefakemccoy** [comment]
It is listed as waiting
