### ISSUE TITLE
Quest "Steady Handd"

### ISSUE THREAD

**Issue by Tytan1996** [Atlantiss/BugTracker#6895]
Ten quest zrobiłem, ale po kilku dniach, zobaczyłem ze w osiągnięciach i addone pokazuje ze nie mam jego zrobionego. Wróciłem to NPC, który ten quest daje, ale nie ma tam go :( . Ja mam 104/110 questów zrobionych w deepholm  i nie mogę dalej robić questów, po ich nie mam. Proszę o pomoc.

**Comment by Aviannaqt** [comment]
read bt rules
