### ISSUE TITLE
[EN][Quest][Dungeon][The Slave Pens]Lost in Action(ID 29563)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#6899]
Quest is now repeatable but should be one-time normal quest.

Wowhead Link: [Lost in Action](http://www.wowhead.com/quest=29563/lost-in-action)

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11003-questnpc-next-fixs/
