### ISSUE TITLE
[EN][Dungeon]Utgarde Pinnacele - Svala Sorrowgrave

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#6904]
http://www.wowhead.com/npc=26668/svala-sorrowgrave
http://www.wowhead.com/spell=48276/ritual-of-the-sword   // doesnt deal dmg to the player or the abomination for the http://www.wowhead.com/achievement=2043/the-incredible-hulk achievment , it deals damage to her and the 3 banshes she summons instead
http://www.wowhead.com/spell=48258/call-flames is non existand she casts it but nothing happens, it should shot flames from the braziers on the players and the Scourge Hulk also

**Comment by HUMBOL** [comment]
https://github.com/Atlantiss/BugTracker/issues/1865

**Comment by 1Andas** [comment]
Bug confirmed. Been there many times trying to get that achievement, couldn't get it.

**Comment by Prodiege** [comment]
Was this fixed? If not then it shouldn't be closed. It includes more than just the achievement
