### ISSUE TITLE
[EN] [Professions] Mining: TrueSilver has no mining nodes spawning

### ISSUE THREAD

**Issue by MaggzWOT** [Atlantiss/BugTracker#6906]
I have been mining in all known Zones according to WoWHead which should contain Truesilver nodes for the last 4-5 days now. I have mined 1300 Mithril ore, 850 Thorium ore, and 500 darkiron ore(not that it spawns from those nodes but just listing this as it shows I am in areas it should be happening) Anyhow, I have mined 0 Truesilver in al this time. I know there should be a limited chance that Truesilver spawns out of both Mithril and Thorium, however it should not be a Zero percent chance. This issue makes it especially difficult when leveling the 250 - 300 range of many professions. It is not impossible but extremely hard and exceedingly expensive having to buy transmuted Bars. The Zones I have been Mining in are:  Felwood, Searing Gorge, and Burning Steppes.

**Comment by Thefakemccoy** [comment]
I have leveled both BS and JC with out any issue. Just what you have to craft may take more of another material.

**Comment by MaggzWOT** [comment]
As I said it isn't impossible, but it certainly makes the path forward a bunch harder. As it limits the recipes you have that require no True Silver to larger mats farm recipes. However, Another side effect is that if you have an enchanter and do not have an alchemist you have to outsource for a transmute which shares a CD with a MUCH more valueable material, which for characters of this level range puts that object pretty hard to obtain. Try thinking of it in terms of having only one character where you would have to outsource, Either way, the fact still remains TrueSilver is not spawning as it should. Even if there is an alternative path to leveling things.

**Comment by Prodiege** [comment]
Might want to correct your title to the standards of the bug tracker

**Comment by MaggzWOT** [comment]
Changed Tags to what I am assuming to be appropriate from the list of tags.

**Comment by vidplace7** [comment]
I've spent hours looking in areas that should have truesilver, and have found none. Confirmed bugged.

**Comment by karhima** [comment]
I'll add my voice to this. The ridiculous prices for Truesilver on the AH are confirmation enough. Since chests aren't working either where I could loot the 1 Truesilver I need, I might as well give up on leveling enchanting.

**Comment by Matti297** [comment]
Truesilver spawns in one cave in Dustwallow Marsh

**Comment by MaggzWOT** [comment]
This bug was fixed recently, There was a patch notification on the website to corroborate. I am open to see this ticket closed now.
