### ISSUE TITLE
[PL][QUEST][WOLTK]Reforging the sword

### ISSUE THREAD

**Issue by Walniety** [Atlantiss/BugTracker#6909]
Nadal nie można wylootować tego Infused Saronite Bar -_-

**Comment by Verisspo** [comment]
Potwierdzam lecz byłem z ziomeczkiem, ktory mogl saronity podnosic wiec nie wiem o co chodzi.

**Comment by monibu** [comment]
When something that was fixed doesn't work always delete cache and try again

**Comment by Walniety** [comment]
Potwierdzam usunięcia Cache podziałało :D

**Comment by HUMBOL** [comment]
i tak nie zrobicie miecza, bo muszą otworzyć sunwell plateu
