### ISSUE TITLE
[EN][Quest][Secrets of the Tower]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#6911]
Good evening,

First, sorry for my bad english :) I hope you will understand anyway.

I have a problem with the quest [Secrets of the Tower] of Westfall : http://www.wowhead.com/quest=26290/secrets-of-the-tower

I'm taking the potion and go to the top of the tower but nothing happens. I gave up and taken the quest 17 times but nothing changes ... The NPC will not appear.

Thank you for your help :)
Good night.

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/2338
