### ISSUE TITLE
[EN][Profession][Mining] Titanium vein does not spawn in Northrend

### ISSUE THREAD

**Issue by KuperusBP** [Atlantiss/BugTracker#6916]
Hi,
I have been searching for Titanium veins to mine for several days now. But I cannot find any in Icecrown, Wintergrasp or Storm Peaks. Where can I find any titanium?

**Comment by Luna-maria** [comment]
hardly is any spawned, if at all. Best chance on getting titanium bars right now is to farm saronite like crazy and have an alchemist transmute it :/

**Comment by fruvel** [comment]
bugged, confirmed 3h farm 0 titanium

**Comment by dawnhunt** [comment]
I have actually seen numerous titanium nodes, namely in wintergrasp and scholozar basin. Anywhere saronite ore can be found you have a rare, keyword RARE, chance of spawning a titanium vein.

**Comment by Luna-maria** [comment]
it's been somewhat fixed since the time of posting :)
