### ISSUE TITLE
[EN][ITEM] [Lost items][Priest] Conquest Quartermaster and Glorious Conquest Quartermaster

### ISSUE THREAD

**Issue by jagii** [Atlantiss/BugTracker#6918]
With horde priest you can't see and can't buy: Ruthless Gladiator's Endgame, Ruthless Gladiator's Reprieve and Ruthless Gladiator's Reprieve.

![page1](https://cloud.githubusercontent.com/assets/17987602/13925433/91ac1c5a-ef88-11e5-9b79-351c8fe3276b.PNG)
![page2](https://cloud.githubusercontent.com/assets/17987602/13925437/992227a4-ef88-11e5-85b8-bf39a7103267.png)
![page3](https://cloud.githubusercontent.com/assets/17987602/13925441/9da0eff4-ef88-11e5-9540-6936bc169177.PNG)
![page4](https://cloud.githubusercontent.com/assets/17987602/13925447/a244998e-ef88-11e5-8e62-bc228140de1f.PNG)
![page5](https://cloud.githubusercontent.com/assets/17987602/13925448/a69ba770-ef88-11e5-88f1-83d6717de6c4.PNG)
![page6](https://cloud.githubusercontent.com/assets/17987602/13925457/aaf38680-ef88-11e5-9264-9aa2ea560833.PNG)

The same happens with Glorious Conquest Quartermaster and their respective items

**Comment by Fearyourself** [comment]
Page 2 top?

**Comment by Aival94** [comment]
Lol...2nd page on top as @Fearyourself  said :P

**Comment by Aviannaqt** [comment]
xD
