### ISSUE TITLE
[EN][Dungeon-Cata] Zul'Aman - Hex Lord Malacrass

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#6919]
Doesn't Aggro When His Adds Are CCed. All 3 mobs should be linked so that if one is pulled (or cced) the other two are pulled.

[Hex Lord Malacrass](http://www.wowhead.com/npc=24239/hex-lord-malacrass#encounter)

Possible Add 1: [Alyson Antille](http://www.wowhead.com/npc=24240/alyson-antille)
Possible Add 2: [Slither](http://www.wowhead.com/npc=24242/slither)
Possible Add 3: [Gazakroth](http://www.wowhead.com/npc=24244/gazakroth)
Possible Add 4: [Darkheart](http://www.wowhead.com/npc=24246/darkheart)

**Comment by Fapguy** [comment]
CC doesn't pull.
Never did.

**Comment by Prodiege** [comment]
[Video proof](https://www.youtube.com/watch?v=mw76ZzIqreo) of otherwise

**Comment by Prodiege** [comment]
[2nd video proof](https://youtu.be/lsb-Wza0coA?t=67) of otherwise

**Comment by Prodiege** [comment]
[3rd video proof](https://youtu.be/zhTJDbxsevE?t=23) of otherwise. Right when the shackles go off you see Hex Lord do his yell before any other spell is cast

**Comment by Fapguy** [comment]
I guess you are right, just doesn't make any sense.
CC never aggro'd anything before.. hmm.

**Comment by Prodiege** [comment]
CC always should aggro others around the target. There really hasn't ever been an exception

**Comment by Fapguy** [comment]
http://eu.battle.net/wow/en/forum/topic/2037775784
Sorry, I just remembered wrong.

It was in Cataclysm when CC was tweaked, no longer causing aggro.

In 4.1 when zandalari dungeons was released the "original" CC was still present.

But in 4.2 it was changed, so it shouldn't pull anymore.

**Comment by Prodiege** [comment]
Nice catch, that looks correct. I also found it here [http://wowwiki.wikia.com/wiki/Patch_4.2.0](http://wowwiki.wikia.com/wiki/Patch_4.2.0)

**Comment by Prodiege** [comment]
Nice catch, that looks correct. I also found it here [http://wowwiki.wikia.com/wiki/Patch_4.2.0](http://wowwiki.wikia.com/wiki/Patch_4.2.0)
