### ISSUE TITLE
[EN][Talent][Warlock] Soul Siphon doesn't work!

### ISSUE THREAD

**Issue by Jinkz** [Atlantiss/BugTracker#6924]
Soul Siphon Talent doesn't work: http://cata.openwow.com/spell=17805

Drains the self HP per tick without DOT's as with DOT's, but should drain 6% more per DOT, makes for me 18% [ 3 DOT's (i am level 47^^)] = 0,18 * 58 + 58 = 68 HP per tick, but still ticking with 58.

Checked it by many other Warlocks on the server, so it's confirmed.

**Comment by kadi2** [comment]
The talent is supposed to modify only dsmage. Not the healing.

**Comment by kadi2** [comment]
Invalid report.

**Comment by Jenovas** [comment]
"Soul Siphon does nothing to the health returned by siphon life anymore."
