### ISSUE TITLE
[EPL][Quest][Sholazar Basin] Just Following Orders

### ISSUE THREAD

**Issue by Hexenbane89** [Atlantiss/BugTracker#6925]
Dobry

Quest Just Following Orders (http://www.wowhead.com/quest=12540/just-following-orders)

Nie da się ukończyć ze względu na brak NPCa, tego stworka z frakcji Oracle, powinnien leżeć na ziemi przy rzece.

To tyle :)

**Comment by Aviannaqt** [comment]
#2050
