### ISSUE TITLE
[PL][QUEST/NPC] Griswold Hanniston

### ISSUE THREAD

**Issue by atryz** [Atlantiss/BugTracker#6926]
Dobry,
po opcji dialogowej ("I'm here to challange you in combat") NPC jest nadal friendly i nie da się go zaatakować, co uniemożliwia wykonanie questa.

**Comment by Samineh** [comment]
#5605

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15298-9629958169265605-griswold-hanniston-smart_scripts/

**Comment by Jenovas** [comment]
Fix in 5537
