### ISSUE TITLE
[EN][Spell]]Rogue]Shadowstep

### ISSUE THREAD

**Issue by Truskify** [Atlantiss/BugTracker#6929]
Hi,

Shadowstep still puts character into textures. It has no rule, just happens. Terrain doesn't matter. It is bugging on BG's, dungeons and regular lvling.

**Comment by Wolffenstein** [comment]
Changelog.

**Comment by Truskify** [comment]
It did not change it. still falling into textures. Maybe less often but always.

**Comment by Pvt-8Ball** [comment]
Check the server revision dude.
Apparently it's still on rev. 4942, and the fix is in rev. 4943.

**Comment by Truskify** [comment]
Ok so I assume revision is not complete and it will be fix. Is it good understanding? I thought rev in changelog are already done.

**Comment by Pvt-8Ball** [comment]
Well the server just needs restarting to apply the revision, so they'll wait so they don't disturb people too much.

**Comment by Truskify** [comment]
server had restart about an hour ago and it is still happening.

**Comment by Jenovas** [comment]
The update isnt on the server.
