### ISSUE TITLE
[PL][Spell][Shaman] Spirit Walk

### ISSUE THREAD

**Issue by krojo** [Atlantiss/BugTracker#6930]
Spirit Walk Powinien Uwalniac z wszelkich spowolniej i rotsów i dawac 60% speeda.

U nas Spell działa ( Za Dobrze ) Poniewaz daje jeszcze Immune na wszystkie slowy Rotsy a nie powinnien tego dawac

Spirit Walk ---- http://cata.openwow.com/spell=58875

" Removes all movement impairing effects and increases the movement speed of you and your Spirit Wolves by 60% for 15 sec. "
Jak widac pisze bardzo wyraznie " Removes all movement impairing effect " A nie ze Daje Immune na wszelkie slowy.
Taki Enh shaman przez 15 sec jest nie do zatrzymania bo zaden slow albo rots na niego nie dziala.

**Comment by Prodiege** [comment]
add [PL] to the title

**Comment by Kuszki** [comment]
Znalazłem takie coś:

> This now also triggers a four second movement impairing immunity. Aside from fixing the problem of Spirit Walk not properly removing movement impairing effects, this also makes it a viable counter to Frost Trap or Desecration.

[Źródło](http://www.wowhead.com/spell=58875/spirit-walk#comments:id=637150)

> I'm embarrassed to say I got killed by an Enhancement Shaman. What ability is that they have that makes them immune to snares? I think I've noticed that they're usually immune when their spirit wolves are out.

[Źródło](http://www.gamefaqs.com/boards/534914-world-of-warcraft/50154009)

> -Spirit Walk- Removes snares/roots and grants immunity to these effect, gives 60% movement speed.

[Źródło](http://www.arenajunkies.com/topic/217024-enhancement-pvp-guide/)

Powyższe linki powinny wystarczyć jako dowód, że spell ten powinien zapewnić niewrażliwość na efekty "snare". Pozostaje teraz rozstrzygnąć na jak długo. Komentarz Wowhead wspomina o 4 sekundach.

**Comment by lamaATS** [comment]
Jak wyżej na patchu 4.3.4 ten spell dawał dokładnie 4 sekundy immune i zostało to zmienione dopiero na MoPie.
