### ISSUE TITLE
[EN] [Raid] [BWD] - Nefarian HC - Bugs galore

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#6934]
Lightning Discharge is currently unavoidable except if you stand in FRONT of Onyxia.

Tail Swipe also hits everyone - even sometimes front of her.
Nefarian tail swipe is random aswell.

Hurl Bone is being cast on the tank when it shouldn't
(this is obvious because in NO GUIDE is it ever mentioned as something you should fear, it's not even on wowpedia as an ability because they couldn't make them use it: http://wow.gamepedia.com/Animated_Bone_Warrior)

**Comment by Fapguy** [comment]
Hope someone with the skills/access can quickly modify the 2 spells to be the way they should be.
I imagine it isn't a very hard fix for such a huge encounter!

The rest of the encounter seems pretty fine.

**Comment by Fapguy** [comment]
And now Feral Charge puts you under textures
Adds spawn under textures now also

**Comment by Fapguy** [comment]
People get mind controlled and go under textures


Boss is now undoable.. how is it possible you guys are breaking it even more every week?
I know FL is focus but, really... just dont touch old raids

**Comment by Wantuno** [comment]
This is literally undoable, dominion pulls you underground 70% of the time, even on first phase. We could overcome other bugs like 360º tail swipe one week, then adds hurling bones like crazy another, then nefarian spammin flames the next, but now with this, it just escapes our control, we can't adjust the tactics to not die.

**Comment by Fapguy** [comment]
#3978 - don't forget Hurl Bone is still bugged.

**Comment by Jenovas** [comment]
Fapguy really... just stop writing...
Every next post you write that isn't about a bug will get removed.
Cheers.

**Comment by Fapguy** [comment]
Hurl Bone is being cast on the tank when they shouldn't

**Comment by Wantuno** [comment]
How is this not about a bug?

**Comment by Bildo** [comment]
Nefarian should work as before after crash/restart

**Comment by Wantuno** [comment]
Hmm, what do you mean as before, as last week? At least that's and advance, last week dominion didnt pull you underground.

**Comment by Fapguy** [comment]
Nice Bildo!
Hope it works like last week at least :)

But many of the bugs still remain if that is the case, I will edit post to clarify.
