### ISSUE TITLE
[EN][Spell][Hunter] Feign Death

### ISSUE THREAD

**Issue by Madever** [Atlantiss/BugTracker#6935]
Every time, when Survival Hunter gain [Sniper Training] it disturb [Feign Death] ability- this make impossible to Survival Hunter [Feign Death] last longer then 5 second instead of 6 min.
http://wowwiki.wikia.com/wiki/Sniper_Training
http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by Prodiege** [comment]
Might want to add some links to the abilities/talents
