### ISSUE TITLE
[EN][Dungeon-Cata][Grim Batol] Battered Red Drake Incorrect Cooldown

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#6937]
[Battered Red Drakes](http://www.wowhead.com/npc=39294/battered-red-drake#abilities:mode=normal) used to fly and destroy NPCs during a "bombing run" currently don't have a cooldown on their ability, [Engulfing Flames](http://www.wowhead.com/npc=39294/battered-red-drake#abilities:mode=normal), and it can be spammed at will. 

There should be a 1 second GCD after each cast of Engulfing Flames

The upcoming video showing evidence is at 200% speed as mentioned [at the 0:20 second mark](https://youtu.be/37a2bWeVeB4?t=20), so you just need to set play speed to 0.5 to see GCD timer. [This video](https://youtu.be/37a2bWeVeB4?t=359) shows the cooldown timer sweeping and the player being able to click the spell roughly every 1 second

**Comment by xmesaj2** [comment]
rev. 5629 fixed
