### ISSUE TITLE
[PL][Quest]  It's Raid Night Every Night

### ISSUE THREAD

**Issue by Hosampsich** [Atlantiss/BugTracker#6940]
Zadania nie mogę wykonać od kilku dni, brakuje jakby części NPC'ów i interakcji od głównego NPC'a.
_Mam 3 krasnale na podobnym poziomie na żadnym ten quest nie działa._

Powinno wyglądać to tak:
https://www.youtube.com/watch?v=fDl9D6BLyck

**Comment by Aviannaqt** [comment]
#3134

**Comment by siwy92** [comment]
stil not work
