### ISSUE TITLE
[EN][Other]Hostile NPC aggro range issue

### ISSUE THREAD

**Issue by nok1z** [Atlantiss/BugTracker#6941]
Hey, been wondering around the world and noticed that hostile npcs have no aggro range i can stand right on top of a npc and it wont attack me. i am the same level as the npcs i am standing on top of.

**Comment by nok1z** [comment]
![screen shot 2016-03-23 at 14 19 01](https://cloud.githubusercontent.com/assets/9404347/13988105/67155f76-f102-11e5-94f9-974f309809d9.png)

![screen shot 2016-03-23 at 14 24 03](https://cloud.githubusercontent.com/assets/9404347/13988240/f38a034e-f102-11e5-933b-e3fa77e95376.png)


This has happened in every zone i have been in so far.

**Comment by Lebiedz** [comment]
It sometimes happens. Also, when you're in a dungeon group nobody can see you, but you can see everyone and play as you would do normally. Relog usually helps fixing that issue.
