### ISSUE TITLE
[EN][In Service of the Illidari][Shadowmoon Valley]

### ISSUE THREAD

**Issue by Jakovnator** [Atlantiss/BugTracker#6942]
This quest basicly is not bugged but since i didn't recieve the quest  i'm going to write it anyway.After saving the nether drakes in shadowmoon valley i should get the quest  In Service of the Illidari  and misteriously didn't get. Whats bugging me off mostly that my brother did get the quest and he and i are on a same stage of questing.I have writen the message to gm and still no response so i thought i'll get response faster if i wrote it here.

Cheers
Gugul

**Comment by Aviannaqt** [comment]
read bt rules
