### ISSUE TITLE
Problem with skills

### ISSUE THREAD

**Issue by mrmlfp** [Atlantiss/BugTracker#6943]
The problem is that I can't learn new skills or recipes from a trainer. I just can't see them at a trainer window, For example I will send two screenshots from my alt.
![wowscrnshot_032316_201816](https://cloud.githubusercontent.com/assets/18037547/13998002/042b3dd0-f135-11e5-832e-b6cf1460726a.jpg)
![wowscrnshot_032316_201758](https://cloud.githubusercontent.com/assets/18037547/13998018/11cf7f32-f135-11e5-9a0a-38c32791c7ea.jpg)

**Comment by phifedawg** [comment]
might be a display error. try a /reload or delete cache and restart the game

**Comment by mrmlfp** [comment]
Nothing, also I can say it lasts for about few hours, so I've reloged etc. a couple times since.

**Comment by mrmlfp** [comment]
I gave my guildie password to an account and he says she can't see the skills neither so I think the problem is my account.

**Comment by 1Andas** [comment]
It might be your addons, I don't know what you are using here, I don't recognize this UI.

**Comment by Fapguy** [comment]
It's ElvUI, and addons are not his problem.
