### ISSUE TITLE
[Pl][Raid][NPC] Majordomo

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#6945]
Przedostatni boss majordomo staghelm resetuje sie tzn znika i pojawia sie jak by był wipe po zmianie z kota w skorpiona kiedy powinny wejsc seedy

**Comment by Walniety** [comment]
tak jest jak głupio się rozbiegniecie :D

**Comment by Quban** [comment]
co znaczy 

> tak jest jak głupio się rozbiegniecie :D

**Comment by Walniety** [comment]
zbyt mocno się rozbiegali widocznie , boss się resetuje zauważyłem jak wejdzie się na schody za bossem podczas fazy jak trza się rozbiec to czasami się resetuje :D mieliśmy paru geniuszy co na komendę rozbiec się lecieli za daleko i resetowali bossa :D a po drugie quban pisałem już ci że adrenalina źle działa i druga faza kota jest nie potrzebna w ogóle bo nikt jej nie używa -_-
