### ISSUE TITLE
[PL] [ NPC ] what is that ?

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#6948]
![wowscrnshot_032416_090925](https://cloud.githubusercontent.com/assets/8699987/14011637/634a20b8-f1a0-11e5-8dfd-b8aee66df3e7.jpg)

**Comment by Lenox07** [comment]
fajne

**Comment by Bastion** [comment]
a potem czemu lagi

**Comment by mati865** [comment]
Zmartwię cię, to nie powoduje lagów serwera tylko powoduje spadki FPS u Ciebie.

**Comment by Luna-maria** [comment]
it's someone who thought it was funny to mount and dismount the traveler's tundra mammoth, which apparently leaves the npcs after you dismount

**Comment by Bastion** [comment]
ja bym banował
