### ISSUE TITLE
[EN][Addon] Quest Status

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6949]
The page to download DB for the addon is currently not working 

http://www.private-status.com/media/downloads/databases/39/database.lua

and if i may make a suggestion here i used to play on gaming Consortium server they god a addon for quest status check with voting capability inside the game true a special channel named quest status it will be more easy for ppl to vote in game and not to go to a site coz most ppl wont do it to go to a specific quest and find it then vote the GC addon was very good and easy to use.

**Comment by Piklo** [comment]
addon is not updated anymore
