### ISSUE TITLE
[EN][Core][Throne of the Four Windsl]Missing platforms

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6950]
Few minutes ago we try to do Tot4W normal when you jump from entrance platform to Rohans platform or from Anshal to Nezir you got stuck in the air going up and down like all the platforms are complete missing thus far making this raid unplayable. Resetting of instance, reloging and remaking of raid have no effect whatsoever

**Comment by 1Andas** [comment]
Bump.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5007 fixed
