### ISSUE TITLE
[EN] [item] Seafood Magnifique Feast

### ISSUE THREAD

**Issue by Stephenjawn33** [Atlantiss/BugTracker#6954]
Hello, the feast offers the buff "Well Fed" to players who eat from it for more than 10 seconds. As a protection warrior I get the wrong stats from the feast. Upon eating for more than 10 seconds I get Strength and Stamina, instead of Dodge and Stamina while I am in protection spec.

Proof:
![seafood](https://cloud.githubusercontent.com/assets/12234008/14026953/02ac43d6-f1fe-11e5-85e6-ccce94e3855a.png)

Proof on how it works on Blizzard:
http://www.wowhead.com/item=62290/seafood-magnifique-feast#comments

> By majgik (177 – 1) on 2011/03/13 (Patch 4.0.6)		
Prot wars get dodge, and fury wars get strength

Thank you for the read! ^^

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4945
