### ISSUE TITLE
[PL][Quest][Blades Edge Mountains] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by Xadroth** [Atlantiss/BugTracker#6956]
link: http://www.wowhead.com/quest=10565/the-stones-of-vekhnir
Po wykonaniu zadania nie wyskakuje komunikat "**_QUEST COMPLETE_**". 
Przy rozmowie z NPC opcja "_complete_" jest zablokowana pomimo tego, że quest item znajduje się w ekwipunku, co widać na załączonym screenie. 
![wowscrnshot_032416_195214](https://cloud.githubusercontent.com/assets/18057324/14028204/a5f78b8e-f1fb-11e5-87a6-0134b539dc05.jpg)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5224, https://github.com/Atlantiss/BugTracker/issues/4673
