### ISSUE TITLE
[EN/PL] [Mage] [Spell] Mage Arcane Blink and Arcane Power

### ISSUE THREAD

**Issue by jasiudawid** [Atlantiss/BugTracker#6959]
Arcane Mage I have a problem as I use Blink while active Arcane Power. How to use  Blink and is active Arcane Power is always later I can not use any spell, it displays "Spell is not ready yet." I have to log out and log in again. during bg few times so I have to do, you can not play. Please help

**Comment by jasiudawid** [comment]
Mage Arcane mam problem jak używam Blink. Jak go używam i jestem w combacie to czesto (nie zawsze) później nie moge użyć zadnego spella. Musze się wylogować i zalogować ponownie. Proszę o pomoc

**Comment by kadi2** [comment]
Would also check if the GCD reduction from the PVP Gloves isn't calculated server side aswell.

**Comment by jasiudawid** [comment]
How to check GCD Gloves? I have to change gloves on other enough by?Od: "Eyesclosed" &lt;notifications@github.com&gt;Do: "Atlantiss/BugTracker" &lt;BugTracker@noreply.github.com&gt;; Wysłane: 10:42 Piątek 2016-04-01Temat: Re: [Atlantiss/BugTracker] [EN/PL] [Mage] [Spell] Mage Arcane Blink and Arcane Power (#6959)Would also check if the GCD reduction from the PVP Gloves isn't calculated server side aswell.

**Comment by Malylolek** [comment]
#7440 close
