### ISSUE TITLE
[ PL i EN ] [Set bonus]Druid balance first bonus T12.

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#6964]
Pierwszy bonus z T12 przywołuje  " Burning Trent ". Wszystko jest okej z jego dmg ale hp raczej ma za niskie bo tylko 293 i ginie nie strzała od każdego uderzenia. Gdzie imp warlocka z bonus ma 146 k. Niestety nie znalazłem ile hp powinno to Burning Trent ale coś tu jest nie tak moim zdaniem. Screeny na dowód. 
http://prnt.sc/ajs039
http://prnt.sc/ajs0h5
First bonus T12 summoning a Burning Trent. Everything is fine with dmg but he have to low hp only 293 and die from everything. Where warlock imp from set bonus have 146k hp. Unfortunately i don't found information about how much hp Burning trent should have , but i think something wrong is witch his hp. Screenshoot for proof.
http://prnt.sc/ajs039
http://prnt.sc/ajs0h5

**Comment by Jenovas** [comment]
Fixed in rev 5035
