### ISSUE TITLE
[EN][Item] Sister Aquinne's Note

### ISSUE THREAD

**Issue by fapuspok** [Atlantiss/BugTracker#6966]
When you read Sister Aquinne's Note (http://www.wowhead.com/item=16263/sister-aquinnes-note) you get the wrong text, it's says:

"Nessa, It is good to hear from you. The collection of bones and scales you sent me was incredible. Never have I seen fish of that size off the mainland. The fishers of Rut'theran must pull in easily a ton of fish each day! I envy the size of their bounty, but I am a small bit troubled as well. Could our new world tree make the fish grow to such a size? If that is so what other effects might it have? Questions to ponder - Laird"

It should be: 
"Nyoma,
You can't imagine how surprised I was to receive the recipe book! Everything you included is just as I remember from home. I can't wait to try out the new recipes.
When you have some time, you should come visit me in Darnassus. I'll even cook for you!
Your friend,
Aquinne"

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12302-6966item-sister-aquinnes-note/
