### ISSUE TITLE
[EN][Quest][Druid of the Claw]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#6970]
Good afternoon,

I have a problem with the quest [Druid of the Claw] of Teldrassil : http://www.wowhead.com/quest=2561/druid-of-the-claw

The quest is completely bugged because the Barrow Den door, behind which hides Oben Rageclaw, remains sealed.

Thank you for your help :)
Good day.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/643
