### ISSUE TITLE
[PL][Quest][Outlands] [Hellfire Peninsula] A Spirit Guide

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#6972]
http://www.wowhead.com/quest=9410/a-spirit-guide
Quest kiedyś był wykonywalny, obecnie zbugowany całkowicie. Po Spacerku z wilkiem do NPC-ta http://www.wowhead.com/npc=16845/gorkan-bloodfist, okazuje się że reputacja z frakcją http://www.wowhead.com/faction=941/the-maghar jest na poziomie unfriendly, nie ma możliwości oddać questa pomimo że Gorkan ma pytajnik nad głową. Brakuje również wszystkich dialogów w momencie wejścia wilka do obozu.

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/7116

**Comment by Anhaeyn** [comment]
Still not working, please fix this.

**Comment by pistonkosiarz** [comment]
bump

**Comment by stanq87** [comment]
bump

**Comment by Bildo** [comment]
https://github.com/TrinityCore/TrinityCore/issues/4028

**Comment by Bildo** [comment]
fixed

**Comment by TranceAccount** [comment]
#8600

**Comment by AbigailKnox** [comment]
Teraz Gorkan nie ma już nawet pytajnika nad głową, a na mapie Hellfire Peninsula pytajnik zaznaczony jest w miejscu, w którym przywołuje się wilka. To bardzo ważny quest otwierający naprawdę dużą ich ilość u Mag'har. :(
