### ISSUE TITLE
[EN][Quest][Dalaran]Shipment: Shifting Sun Curio

### ISSUE THREAD

**Issue by KuperusBP** [Atlantiss/BugTracker#6973]
I tried to do this quest for Jewelcrafting, but none of the Scourge in Borean Tundra dropped the Scrouge Curio, required for this quest.
See http://www.wowhead.com/quest=12963/shipment-shifting-sun-curio
and http://www.wowhead.com/item=42108/scourge-curio

**Comment by Lertriency** [comment]
I can confirm, tried killing Scourge mobs in Icecrown and Storm Peaks with this quest today and not finding any Scourge Curio.

**Comment by Daetherion** [comment]
I could also confirm this. I've kill a bunch of Scourge mobs in Sholazar Basin and didn't get anything. Without this, one can't buy the WotLK recipes of Jewelcrafting, which is sad.

**Comment by KuperusBP** [comment]
Today, I was able to find a Scourge Curio - in Dragonblight - at Azjol Nerub... But struggled to find one in Borean Tundra again... So try Dragonblight

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14537-scourge-curio-drop/
