### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] Weaken the Ramparts

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#6977]
The following quest should no longer be available as of current patch http://www.wowhead.com/quest=9572/weaken-the-ramparts, however it is still there to be accepted by the NPC http://www.wowhead.com/npc=17493/stone-guard-stokton inside Thrallmar.

It has been replaced by http://www.wowhead.com/quest=29542/invading-the-citadel as the introductory quest to hellfire ramparts by which you talk to the quest giving NPC inside the actual instance http://www.wowhead.com/npc=54606/stone-guard-stokton.

That NPC gives the updated quest of Weaken the Ramparts equivalent for Cataclysm. http://www.wowhead.com/quest=29527/war-on-the-ramparts

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12521-6977questhellfire-peninsula-weaken-the-ramparts/
