### ISSUE TITLE
[EN][Item]Polymorph Rules and Regulations

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#6979]
The item (http://www.wowhead.com/object=192882/polymorphic-rules-regulations#comments) is 
missing its text when read. The correct text is available under the link.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12239-69806979itemcommonorcish-dictionary-polymorph-rules-and-regulations/
