### ISSUE TITLE
[EN][Item]Common/Orcish Dictionary

### ISSUE THREAD

**Issue by Jacobsjj2** [Atlantiss/BugTracker#6980]
The item (http://www.wowhead.com/object=192893/common-orcish-dictionary#same-model-as) is
missing its text. The correct text is available under the link.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12239-69806979itemcommonorcish-dictionary-polymorph-rules-and-regulations/
