### ISSUE TITLE
[EN][QUEST] Ticker Required

### ISSUE THREAD

**Issue by Pankonduktor** [Atlantiss/BugTracker#6983]
ID: 14485
The NPCs from quest item approach, tho pointing it on quest object doesn't do anything, while it should.
The NPCs summoned should also approach on the parchatues from the air, tho it's only for fun sake
http://www.wowhead.com/quest=14485/ticker-required

**Comment by SlendyMan0** [comment]
It is possible to complete this quest - after runestone that works for you respawns, approach it again to trigger its destruction second/third time.

**Comment by Khangu** [comment]
Quest bugged now other way. Using Gob Squad Flare (http://www.wowhead.com/item=49629/gob-squad-flare) should summon Ticker and other Gob Squad NPCs. But now item does nothing and quest is impossible to complete without Ticker.

**Comment by m3inbl0ck** [comment]
Quest works just fine now.
1. Summon the squad at runestone
2. Walk around it until one of the goblins says "Ticker, blow this thing."
3. 5 or 6 waves of Naga then need to be killed off
4. Runestone blows up and you're credited

**Comment by Khangu** [comment]
No it can't. Clicking item only spawns smoke flare - no sign of Gob Squad. However I noticed todady other Gob Squad wandering around possibly spawned by another player. I wonder if it's not the source of problem - only one squad can be deployed or worse it can be done once after res. Need more tests.

**Comment by m3inbl0ck** [comment]
Yes, it can because I completed it. I have no reason to lie. And I don't think I'm the only one. 
I was also able to summon the squad while members of the previous squad were walking around. Try abandoning and doing it again.

**Comment by Khangu** [comment]
I'm not saying you're lying I'm saying I can't complete it. In the past few days I tried about 5-6 times everytime canceling quest, deleting item, picking quest with new one and trying to summon the sqad in diferent parts of the ruins - always same effect -> smoke flare appears but without gob squad npcs.

**Comment by tourbizxqt** [comment]
can confirm this is still not working, tried it today, no goblin spawn when using the smoke signal, and i didn't saw any other player nearby

**Comment by Piklo** [comment]
#8687 reported with issue_template

**Comment by MercuricUma** [comment]
I just finished it. You have to click the rocket not next to the pillar you have to destroy but outside the temple where it is. Goblins will appear and once you get near the pillar tons of nagas will arrive from nowhere but with a goblin's army they won't even hurt you :) There should come 2 waves of nagas and after that you should get the credit for destroying the pillar. You'll know it's destroyed because it will disappear and you'll kind of blow
