### ISSUE TITLE
[EN][NPC][Shatrath Cityt]Lyrsara and Braku

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#6988]
http://www.wowhead.com/npc=50140/auctioneer-lyrsara
http://www.wowhead.com/npc=50145/auctioneer-braku

They should be connected to the Horde Auction House system not the Neutral(Goblin) like the robots in Dalaran they are working fine.

The reason those exist is removal of the portals in 4.0.3 same reason class trainers exist there as well my educated guess is allys counterpart are also connected to neutral not ally AH

**Comment by Kiperr** [comment]
Fixed in rev 4969.

**Comment by DuGalle** [comment]
Love ya :)
