### ISSUE TITLE
[EN][Quest]A Flawless Plan

### ISSUE THREAD

**Issue by CodeWiking** [Atlantiss/BugTracker#6990]
The target "altar" that the player is required to be near to use the explosive bundle given for the quest is not present, nor is the target NPC that needs to be killed in this Storm Peaks quest.

**Comment by CodeWiking** [comment]
This quest is required for a very long line of quests that end up unlocking more quest lines, dailies and an entire reputation faction. Please fix this soon!

**Comment by Aviannaqt** [comment]
read bt rules
