### ISSUE TITLE
[EN][Quest]Cold Hearted

### ISSUE THREAD

**Issue by CodeWiking** [Atlantiss/BugTracker#6991]
The prisoners a drake is supposed to be able to pick up spawn one at a time and at an unplayably reduced spawn rate. They can be picked up, but when flying back, the drake is supposed to assume automatic control of flight but doesn't. So whether prisoners have actually been collected or not, neither prisoners nor drakes can be handed in.

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/6601, https://github.com/Atlantiss/BugTracker/issues/2471
