### ISSUE TITLE
[EN][Quest][Darkshore][The Eye of All Storms]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#6994]
Hi :)

I have a problem with the quest [The Eye of All Storms] : http://www.wowhead.com/quest=13588/the-eye-of-all-storms

I read all issues about this quest but nothing works.

The quest can't be possible : impossible to kill the dragons as they are always out of reach and I don't see the portal no matter the distance at which I am from the ground. 

The dragons are all at ground and not in the vortex but even without the NPC, we can't attack them because they are also  out of reach.

And when the dragons are in the vortex, i can't kill them because they immediately recovered their points of life

Thanks for doing something about it.

**Comment by Aival94** [comment]
reported 1000 times with different posts: https://github.com/Atlantiss/BugTracker/issues/2028

**Comment by Snake90** [comment]
I know it but il still doesn't work

**Comment by 1Andas** [comment]
Yeah it's buggy, confirmed.
