### ISSUE TITLE
[PL][ITEM] Cofka itemów i lvlu.

### ISSUE THREAD

**Issue by adoziom33** [Atlantiss/BugTracker#6995]
Witam serdecznie podczas gry na serwerze nagle WoW się zaciął i wywaliło serwer, wbiłem ponownie i zauważyłem że nie mam swoich itemów, lvlu. Miałem 85 lvl i dużo itemów PvP z BG. Dostałem jedynie itemy te które dostaje się po zrobieniu transferu z Sunwella.

**Comment by Kozakko** [comment]
Na pewno nie zalogowałeś się na PTR ?

**Comment by adoziom33** [comment]
Było zmiana serwera, do zamnięcia.
