### ISSUE TITLE
[PL]Hunter Bug crit help!!!

### ISSUE THREAD

**Issue by underman65** [Atlantiss/BugTracker#6996]
Witam mam spory problem otóż mam huntera na 84 lvl i coś się popsuło mianowicie miałem jeszcze pare lvl temu szanse na ranget crit około 30% teraz mam zaledwie 18% przy lepszym sprzęcie. bez gearu mój Hunt ma 0.01% na 84 lvl wiec chyba coś jest nie tak i gra stała sie porostu irytujaca bo robie smieszny dps .GM powiedział że nie może nic zrobić i że trzeba to sprawdzić w bazie >Proszę o pomoc bo nie chce rezygnować z gry na waszym serwerze i liczę na jakąś pomoc 

pozdrawiam nick w grze Beleford

**Comment by lqlq32** [comment]
With google translate - you get less % crit when ur level grow up. Also hunter class start with negative crit chance. Nothing is wrong.

**Comment by kadi2** [comment]
Witam drogi sunwellowiczu! Wszystko jest w jak najlepszym porządku.

**Comment by underman65** [comment]
skoro tak to dzięki za info pozdrawiam
