### ISSUE TITLE
[EN][Class] frost mage diminishing retuns

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#6998]
the freezes from cone of cold, frost nova, frost nova talent when frost barrier gets destroyed, ring of frost, deep freeze
everything has its full duration on a player, dimisshnig return isint even present but it should
http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by blinkmaster** [comment]
cone of cold freeze dr with shattered barrier - works
freeze dr with frost nova - works
ring of frost dr with deep freeze - one time it works, second it does not. already reported.

**Comment by Jenovas** [comment]
...
