### ISSUE TITLE
[PL][Spell][Paladin] Guardian of Ancient Kings

### ISSUE THREAD

**Issue by Zlo-** [Atlantiss/BugTracker#700]
http://cata.openwow.com/spell=86150

Patch 4.1: The Retribution version of Guardian of Ancient Kings now benefits from the paladin's hit and expertise.

Obecnie Guardian nie dostaje hita ani expertise od paladyna:
http://i.imgur.com/onGfmuz.png

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
