### ISSUE TITLE
[EN][Quest][Moten Front]Into the Fire / The Forlorn Spire

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#7002]
They are broken Again for 1257946 time yesterday i did em and finally open few more daily's now broken again this molten front business is supposed to take max of 25 days i am already over 30 days as of now and i am not even half of it. 

Just set them to Auto-complete and be done with it PLS i cannot imagine how those things work when MF was first open and who is broking them

i am not even providing links coz this is prolly reported like 100 times already Thanks in Advance.

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/5661 and https://github.com/Atlantiss/BugTracker/issues/5727
