### ISSUE TITLE
[EN][Quest][Moten Front]Wings Aflame

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#7003]
When the flame bird fly away no small birds spawn to finish him off and if you have not enough dots on him he stays in air out of reach forever

not providing link coz its reported 100 times

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6327

**Comment by ko4o** [comment]
Bump, still doesn't work
