### ISSUE TITLE
Lunk's Adventures (Searing Gorge)

### ISSUE THREAD

**Issue by Heart1783** [Atlantiss/BugTracker#7004]
None of these quest's are currently working,and you need them to progress foward in the storyline in Searing Gorge. Please fix these when you can i realize this is a cataclysm private server but it would be nice if you could have all working quests.It is a big feat but with the help of your community i think you can do it. make this a bigger and better private server than any out there. You guys can do it i truley truley love your server. Most kind wishes!

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/3315 and https://github.com/Atlantiss/BugTracker/issues/559

**Comment by Heart1783** [comment]
what?

**Comment by Prodiege** [comment]
It has already been reported in those two postings.
