### ISSUE TITLE
[EN][Quest]Into the Wild Green Yonder

### ISSUE THREAD

**Issue by CodeWiking** [Atlantiss/BugTracker#7006]
The NPC pick-up ability the dragon the player is supposed to ride can use does not work, rendering this Icecrown quest and all the following ones broken.

**Comment by 1Andas** [comment]
It's completable.

**Comment by Luna-maria** [comment]
you can just go to the questender yourself

**Comment by heartlesshound** [comment]
Tirion no longer completes this quest on talking to him, neither can you pick up any of the captured crusaders with or without a dragon. Quest is bugged again :(

**Comment by Piklo** [comment]
@heartlesshound always you can make new post ;p 
https://github.com/Atlantiss/BugTracker/issues/new

**Comment by Danbar1976** [comment]
I tried today and I can't pick up a crusaders, so is still bugged

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/issues/new
