### ISSUE TITLE
[EN][MAGE][SPELL] DEEP FREEZE AND RING OF FROST DONT SHARE DR

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#7007]
The 2 spells should Dr with each other by the official patchnotes check on link under the mage lates fixes.
http://us.battle.net/wow/en/blog/2993743/rage-of-the-firelands-patch-42-notes-%5Bupdated-628%5D-6-28-2011
This bug is already long time on Bugtracker hope it gets fixed soon.

**Comment by Reversion** [comment]
https://github.com/Atlantiss/BugTracker/issues/6882
