### ISSUE TITLE
[EN]{Quest] Let's See What You've Got, Zanzil 

### ISSUE THREAD

**Issue by Kozakko** [Atlantiss/BugTracker#7009]
What is wrong?: During the quest you need to talk to Orgus but he is untalkable
How should it work? We should be able to talk with Orgus

LINKS:
http://www.wowhead.com/quest=26534/lets-see-what-youve-got-zanzil  -quest
http://www.wowhead.com/npc=43204/orgus   Orgus
https://www.youtube.com/watch?v=Ohjh9gPFJCw&feature=youtu.be -playthrough (WoD but i don't think that roleplays changed during the MoP/WoD)

**Comment by Kiperr** [comment]
Fixed in 4969.

**Comment by Reptoko** [comment]
It still doesnt work. Orgus is untalkable.
