### ISSUE TITLE
[PL] [NPC] [Guest line] Beat it Out of Them

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#7011]
![wowscrnshot_032716_162537](https://cloud.githubusercontent.com/assets/8699987/14065857/0aef81b4-f43a-11e5-8655-5717fc4668e4.jpg)
Brak karawany i jego właściciela
http://www.wowhead.com/quest=27522/beat-it-out-of-them

**Comment by Aviannaqt** [comment]
#5313
