### ISSUE TITLE
[EN][Event]Noble Gardener

### ISSUE THREAD

**Issue by jissabraham** [Atlantiss/BugTracker#7014]
The event Noble Gardener not started yet, suppose to start on 27th

**Comment by Larousene** [comment]
Confirmed, no eggs, no NPC's

**Comment by Thefakemccoy** [comment]
rev. 4949 Author: Bildo :: 2016-03-28 23:25 - Waiting for update
Noblegarden:

Enable Noblegarden (03/29 - 04/05)
