### ISSUE TITLE
[PL][Quest][When Science Attacks]

### ISSUE THREAD

**Issue by Beefe32** [Atlantiss/BugTracker#7016]
Witam, chciałbym zgłosić, że ww quest nie działa. Właściwie nie działa tylko połowa ponieważ o ile palące się gobliny można ugasić, to pożarów już nie. Czy można coś z tym zrobić?

**Comment by Aviannaqt** [comment]
link

**Comment by dinosaldo** [comment]
Dodaje link do questa . Tak jak kolega pisał gobliny idzie ugasić a pożarów nie 

http://www.wowhead.com/quest=14308/when-science-attacks
