### ISSUE TITLE
[En][Warlock][Pets] Follow ans resilience issues

### ISSUE THREAD

**Issue by texa69** [Atlantiss/BugTracker#7018]
When I joined the server I noticed that the warlock pets are kinda buggy and need to be fixed. Idk about other classes with pets. 
So first of all, the pets should be running with you (the warlock) not following him from behind, sometimes they stop following untill you command it to follow you and also pets should not disappear when using ground mounts, it makes you lose soul link and its really important in BGs. 
And the most important is the resilience, the pet does not benefit from the warlock's resilience in Pvp which makes it really easy to kill and thats so broken.

**Comment by 1Andas** [comment]
Pets/minions SHOULD disappear when you mount, that came with Cataclysm.
As for resilience, according to some sources that I found on the internet, pets should inherit 40% resilience rating from their master.

**Comment by Jenovas** [comment]
Can you atleast test before reporting a bug?
Warlock pet gets 100% of the owner's resi, tested it right now with EVERY DEMON and it works on all of them.
Closing the bug report.
