### ISSUE TITLE
[PL][Quest]The Spirits of Golakka Hot Springs

### ISSUE THREAD

**Issue by Jeesupin** [Atlantiss/BugTracker#7023]
Po wzięciu zadania Maximillian of Northshire nie podąża za nami, nawet sprowadzając Steam Furies koło niego nie dochodzi do żadnych reakcji.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6982, https://github.com/Atlantiss/BugTracker/issues/398
