### ISSUE TITLE
[EN][QUEST]Into the Fire (molten front)

### ISSUE THREAD

**Issue by Nabwek** [Atlantiss/BugTracker#7024]
Hello.
The quest "Into the Fire" is bugged again. The elite mob doesn't spawn and the druid isn't even here.
If I could propose - how about making it auto complete until the fix is found? It's just one quest and it would allow people to farm dailies without raging every day. 

It's well known issue on Atlantiss so I'll not post links or ss..

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7002 , https://github.com/Atlantiss/BugTracker/issues/5661

By reporting many new different posts about the same issue will probably not make the devs find a solution or fix it with a miracle.Make comment to the first post: https://github.com/Atlantiss/BugTracker/issues/5661
