### ISSUE TITLE
[EN] [Battleground] Tol Barad

### ISSUE THREAD

**Issue by headachex** [Atlantiss/BugTracker#7025]
The queue for Alliance players only (!) seems bugged. 

No one can get in to the TB battle, while the horde players are free to do so. 2nd time now it actually allowed us to get in to TB, but only after 10 minutes, which left us with 5 minutes total to capture 3 bases while being graveyard camped by the hordes that were already there.

![unbenannt2](https://cloud.githubusercontent.com/assets/2852477/14115372/fe7ad198-f5da-11e5-82f1-e3bfa6611f88.png)

This is how it looked 4 minutes after Tol Barad started (the one from 18:06).

**Comment by jissabraham** [comment]
Every time i queued it says battleground is full and you cant enter even through bridge

**Comment by 1Andas** [comment]
Confirmed.

**Comment by Jenovas** [comment]
It seems this bug isnt only for Ally - https://github.com/Atlantiss/BugTracker/issues/7030

**Comment by Aieerth** [comment]
If it's not for Ally only, why can Horde enter freely?

**Comment by headachex** [comment]
Same situation again. Tol barad started 5 minutes ago, yet only 2 people from the ally side are in...

**Comment by Aieerth** [comment]
Tol Barads are just waste of time right now. Thanks for fixing them.

**Comment by headachex** [comment]
Another thing to note: even if the ally side is allowed to join (usually after 6-9 mins after start) we are limited to 1 raid group (40 ppl) it seems that the horde arent though (they have >40 ppl).

**Comment by NatsumeLily** [comment]
Hey Alliance...This is how it was for Horde ...Let us have this for atleast a week, unlike the months and months you guys had with Hordes queue being bugged..

**Comment by headachex** [comment]
Except the horde queue was NEVER bugged, there were just less people that did PVP on the horde side. Also hordes used to win TB, only the last week or so it was pretty bad.

There is no questioning the fact that the queue system is seriously broken and only affects allies, which is even more infuriating.

**Comment by tantyk** [comment]
srsly up

**Comment by Kaspi92** [comment]
With the latest update the Tol Barad queue seems fixed. Both can join properly and there are similar numbers on horde and alliance players in TB.

**Comment by Wolffenstein** [comment]
Great :)
