### ISSUE TITLE
[EN][Rogue] Bandit's Guile off hand

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#7029]
Class: Rogue
Talent: Bandit's Guile
Link: http://cata.openwow.com/spell=84654

[EN]
Bandit's Guile doesn't increase DMG from OFF HAND auto attack.

Proof:
Only tooltip: "increasing damage to that target by up to 30%"
So we can understand that it increase ALL dmg (skills, mh auto attack, poisons are increased).

TEST:
Target: skull dummy
AP: 15011
Weapon speed: 2,6 (both)
MH weapon DPS: 47,9 (87-162)
OH weapon DPS: 551,8 (1004-1865)
Armor reduction: 0,6835 (based on dmg / tooltip  small amount of attacks)
Bandit's guile stacks: 3 (+30%)
DMG formula: ( dps + ap / 14) * speed * off-hand * armor * ambidexterity * bandit's_guile )

MH from tooltip: 2874-2950
OH from tooltip: 3318-4072

from formula:
MH dmg: 2587 (2554-2621)
OH dmg: 3282 (2948-3617)
aa avg: 2935

On ATS:
aa dmg - BG: 2238 (1969-2788)
aa dmg + BG: 2561 (2293-2785)
So only dmg from MH is increased, OH is still the same

**Comment by milzo** [comment]
It's known.

**Comment by tnarf** [comment]
I found only 6 BG threads all without mention about OH and 1 not related where is only mentioned (so probably it will be ignored)
if it is duplicated link previous
if not duplicated then it isn't known

**Comment by milzo** [comment]
You're right, it's not here on the bug tracker, but some devs are aware of this bug. That's the only bug that I could find for combat rogues which doesn't collide with KS and base values of the abilities (tho they are working fine according to formulaes I was using).

**Comment by Bjarzyna** [comment]
Can confirm it's working as intended on all 3 bandit's guile stages after the update
