### ISSUE TITLE
[En][Priest] Shadow orbs proc rate

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7032]
![wowscrnshot_033016_111003](https://cloud.githubusercontent.com/assets/16594771/14137408/fcc088e2-f667-11e5-9112-ade3ba8ddca8.jpg)
![wowscrnshot_033016_110947](https://cloud.githubusercontent.com/assets/16594771/14137409/fcd5192e-f667-11e5-9a10-e1d800ee8390.jpg)
i have mained shadow priests on alot of servers for years now, and i can clearly notice the proc rate of shadow orbs is significantly low on this server. its supposed to be 26% with the talent included, however i sometimes find myself using shadow word death and up to 5-6 mind flays just to proc 1 shadow orb. this is a big problem for shadow priests

**Comment by Jenovas** [comment]
No. The basic chance to proc Shadow Orbs is 10%, with the talent it's 18%.
Sometimes you need to use 5 MFs, sometimes one MF gets you 3 orbs.
RNG.
