### ISSUE TITLE
[EN] [Guild] - Guild Reputation lost when leaving guild - 10 day grace period doesn't exist

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#7033]
If you leave a guild you lose the guild rep permanently.
That is not supposed to happen unless you join another guild, or wait more than 10 days before rejoining the guild.

**Comment by Jenovas** [comment]
Create a new report with atleast one link stating that this "grace period" existed.
Closing.

**Comment by Fapguy** [comment]
Seriously?
This is common knowledge.

But sure here is the proof:
http://www.wowhead.com/faction=1168/guild

**"Guild reputation is lost if you:

    Go 30 days unguilded after guild removal.
    Transfer a character between accounts.

If you leave your guild and join another, you'll lose one rank of reputation. Meaning; if you are Exalted with your current guild and join another, you'll go back down to Revered."**

**Comment by Jenovas** [comment]
Thank you

**Comment by krecik88** [comment]
If you leave your guild and join another, you'll lose one rank of reputation. Meaning; if you are Exalted with your current guild and join another, you'll go back down to Revered."**

this is in mop, in cata you loose reputation when going to other guild

**Comment by krecik88** [comment]
Found problem with that, there is already fix on the repository but not yet on server, on rev higher than 4979 it should work fine
