### ISSUE TITLE
[EN] [Guild] - Guild Reputation lost when leaving guild

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#7035]
If you leave a guild you lose the guild rep permanently.
That is not supposed to happen unless you join another guild.

Cata patch proof http://us.battle.net/wow/en/blog/2113741#blog
(http://us.battle.net/wow/en/forum/topic/3424908904)

"It's important to note that if you leave your guild and join a new one your reputation with the previous guild is removed and your reputation with the new guild will be set to neutral. If you leave your guild and don't join a new one you have the ability to rejoin your previous guild and keep all of your previous reputation. Whether you rejoin or not you'll keep any rewards you purchased, but will of course lose the unlocked guild perks."

**Comment by Tigerief** [comment]
happened to me too.... all lost now cause was inactive

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/7033

**Comment by Fapguy** [comment]
krecik88 - don't close bug reports when you don't even bother to read it man, have some patience or at least let others do their job.

The date for that patch is 1/21/2011 - that's before Firelands!!!

**Comment by Fapguy** [comment]
"We plan to keep building on the guild features and advancement system and adding to it as times goes on. All you need to do is sound the recruiting call, gather your group, and set out to strengthen your guild. It's time for you and your guildmates to leave an even bigger footprint on the world of Azeroth!
 
* Available with patch 4.0.6"

And I quote. Really not hard to miss.

**Comment by ShadicSatan** [comment]
Yeah i remember that too.

**Comment by Wantuno** [comment]
One of the things i did the most in retail cata (to mock friends as officer) was to kick them and reinvite them (some inside game we had) and of course i had that done to me too... that was in cata, i fully remember my cata pvp gear and i remember retrieving my guild rep every time, or else we wouldnt have played that game.
