### ISSUE TITLE
[EN][Quest] Lost in the Floods

### ISSUE THREAD

**Issue by Khangu** [Atlantiss/BugTracker#7036]
http://www.wowhead.com/quest=25187/lost-in-the-floods

When we're using Spyglass we should see cinematic showing locations of four npcs. But now camera flies to npc location and stops (doesn't return to Thonk's tower where we use it) . We can only cancel cinematic mode using ESC and when we do it, our character appears at this location but quest objective remains uncompleted. When we return to Thonk's tower on foot and try to use spyglass again bug repeats making it impossible to complete.

Quest was working fine about 2-3 days ago so it's very fresh bug.

**Comment by glitterlance** [comment]
As of 28.04.16 it's still bugged.

**Comment by BAndysc** [comment]
Fixed in 4992
