### ISSUE TITLE
[EN][Talent][Hunter] Sniper Training interrupts Feign Death

### ISSUE THREAD

**Issue by covakz** [Atlantiss/BugTracker#7037]
So if you're a survival hunter and invest in [[Sniper Training]](http://wowwiki.wikia.com/wiki/Sniper_Training) talent you cannot use [[Feign Death]](http://wowwiki.wikia.com/wiki/Feign_Death) anymore, because when [[Sniper Training]](http://wowwiki.wikia.com/wiki/Sniper_Training) procs it is identified as an action(like moving or attacking) and it will interrupt the Feign Death effect. You can't just lay flat on the ground and chill anymore... you will get up after 4-5 seconds and die, eventually.

**Comment by szapol** [comment]
still bugged, very annoying

**Comment by mati865** [comment]
Not even confirmed status?

**Comment by xolon** [comment]
Merged with my newest report.
#9304
