### ISSUE TITLE
[EN][Raid] Eye of Eternity - Malygos

### ISSUE THREAD

**Issue by amyza1337** [Atlantiss/BugTracker#7041]
http://www.wowhead.com/zone=4500/the-eye-of-eternity
http://www.wowhead.com/npc=28859/malygos

## Phase 3: Don't work,drake spells are buggy can't use it and Malygos is in phase 3 sometimes invisible.

Other bugtracks 

https://github.com/Atlantiss/BugTracker/issues/2347
https://github.com/Atlantiss/BugTracker/issues/2533

**Comment by Aviannaqt** [comment]
#960
