### ISSUE TITLE
[PL] Warlock [PET] Whiplash

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#7044]
nie zawsze dziala, czasami kicknie czasami nie, nawet nie zada dmg

**Comment by pelekon** [comment]
Polecam się zapoznać z tą instrukcją https://github.com/Atlantiss/BugTracker  i poprawić zgłoszenie.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/6952
