### ISSUE TITLE
[EN][Hunter] Deterrence vs. Casted Spells (On Travel Spells)

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7045]
So if you used Deterrence while eg. warlock Death Coil is on its travel you don't deflect it, same with every already traveling spell.
How it should work: already traveling spells should be deflected when you use deterrence.
http://www.wowhead.com/spell=19263/deterrence

**Comment by kadi2** [comment]
Hey, you are wrong. You are not supposed to deflect for example a flying Death Coil from a warlock.
