### ISSUE TITLE
[EN][Core] Casted Spells (On Travel Spells) vs. End Of Immunity Effects

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7046]
If you cast some spell which has travel time while eg. paladin has bubble on, and bubble ends before that spell reaches him the spell will still be immuned, which shouldn't be the case.

**Comment by kadi2** [comment]
Can you post a proof? You actually might be wrong about it.

**Comment by krojo** [comment]
This would be work like Spell reflect 
If warrior use Spell reflect When Spell is going to hit him,  didnt hit target but reflect it. 
It's logic. 
How to Immune Spell if you didnt have bubble or anything else?

**Comment by krojo** [comment]
Found it in last min 
Someone Say that
 Spell reflect used when Spell travel to you,  didnt hit you but reflect to the Someone who cast it. 
Logic 
http://us.battle.net/wow/en/forum/topic/12674897730

**Comment by kadi2** [comment]
http://us.battle.net/wow/en/forum/topic/12674897730#3
"The first rule is that if when a spell is casted, if the target has said reflection/deflection activated, the spell will not hit, EVEN IF THE REFLECTION/DEFLECTION IS NO LONGER ACTIVE WHEN IT LANDS."

**Comment by krojo** [comment]
Then my mistake 
Didnt read all :)
