### ISSUE TITLE
[EN] [Guild] - Guild Reputation lost when leaving guild

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#7051]
If you leave a guild you lose the guild rep permanently.
That is not supposed to happen unless you join another guild.

Cata patch proof http://us.battle.net/wow/en/blog/2113741#blog
(http://us.battle.net/wow/en/forum/topic/3424908904)

"It's important to note that if you leave your guild and join a new one your reputation with the previous guild is removed and your reputation with the new guild will be set to neutral. If you leave your guild and don't join a new one you have the ability to rejoin your previous guild and keep all of your previous reputation. Whether you rejoin or not you'll keep any rewards you purchased, but will of course lose the unlocked guild perks."

"We plan to keep building on the guild features and advancement system and adding to it as times goes on. All you need to do is sound the recruiting call, gather your group, and set out to strengthen your guild. It's time for you and your guildmates to leave an even bigger footprint on the world of Azeroth!

    Available with patch 4.0.6"

**Comment by krecik88** [comment]
stop opening new issues, one is enough

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/7033

**Comment by Fapguy** [comment]
Krecik stop closing them then!

**Comment by Fapguy** [comment]
I didn't see the old one was reopened, sorry about that :)
