### ISSUE TITLE
[EN][Warlock] Jinx: Curse of Weakness 

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7052]
The energy cost increase doesn't work. Reproduced for 2/2 points into Jinx on feral and rogue. The effect has been changed since 4.0.6, but i am not sure if the old effect even presists.

http://cata.openwow.com/spell=85479 // Talent
http://cata.openwow.com/spell=702#see-also-ability // Spell

**Comment by kadi2** [comment]
https://youtu.be/PdUUr605TSk?t=17s // You can see it's applying the debuff which name, spell ID i couldn't find.

The curse debuff id prolly is 85539 and it's called "Jinx"

**Comment by Milton3450** [comment]
I can confirm this!

**Comment by rwystop** [comment]
yeah and it should working at all players within 40 yrds.. its working only on one

**Comment by lamaATS** [comment]
Fixed in rev. 5203
