### ISSUE TITLE
[EN] Gathering from landed flying mount

### ISSUE THREAD

**Issue by seastranger** [Atlantiss/BugTracker#7060]
When attempting to mine (or to gather herbs) from landed flying mount - u dismount, and do not start gathering - it is interrupted by the dismount action and you receive message cannot do that while moving. If the mount is landed the gathering action should happen despite the fact of dismount without the interrupt.

**Comment by ponpontos** [comment]
Ah yes, truly a shame, I feel awful for all the botters out there.

**Comment by zotmer** [comment]
Can confirm the stated bug and I can add that it isn´t only the problem of nodes but of everything that needs to be done while not moving. Very annoying bug because you have to click twice on everything you want to do.

**Comment by Wolffenstein** [comment]
Fixed in rev 5016.
