### ISSUE TITLE
[EN][CORE][BG] Battleground queue

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#7061]
I think the new system doesn't work quite well.

I was level 11 and when i joined to WSG queue i saw this:
![hordequeue](https://cloud.githubusercontent.com/assets/3641625/14225744/3a91b1b2-f8d6-11e5-8312-ec7201401e0c.PNG)

WSG in progress and 2 alliance in queue. It means right now, on that very bg, there is more alliance than horde players (should be atleast 7vs6), so system keep them in queue. But why didn't i get invite to that bg, if alliance have more players there? So i went to alliance:

![alliance queue](https://cloud.githubusercontent.com/assets/3641625/14225776/75b94d6c-f8d7-11e5-8419-3b7e641e9272.PNG)

As we can see, there is only 5 alliance players and for some reason, system keeps 2 alliance players in queue.

I requeued couple times, and "2 alliance in queue" was still there and /who shows same 5 alliance and 6 horde. 5 minutes later bg was over.

**Comment by Wolffenstein** [comment]
There were no changes to BattleGROUND queue. You confuse it with BattleFIELD queue.

**Comment by Crusaderz** [comment]
Sorry i don't get it. Is this behavior normal for queue system? When players sit in queue while there is ongoing BG with a spot for them?
