### ISSUE TITLE
[EN][Hunter] Enemy Hunter Ice Trap

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7064]
Currently on atlantiss Enemy Ice Trap doesn't flash red, so you can't know if its your trap or enemy hunter trap.
How it works: Enemy Ice trap should blink red, proof https://www.youtube.com/watch?v=7IhR3SCgOec
http://cata.openwow.com/spell=13809

**Comment by lamaATS** [comment]
Fixed in rev. 5232
