### ISSUE TITLE
[PL] Quest: How to Save a Life

### ISSUE THREAD

**Issue by kvokul** [Atlantiss/BugTracker#7067]
http://www.wowhead.com/quest=29649/how-to-save-a-life

Na oko nie można wziąc Fel Ember pomimo tego, że przedmiot questowy jest użyty koło brazierów.

**Comment by Kiperr** [comment]
Następnym razem opisuj to normalnie czyli: Nie da się użyć itemu koło brazierów na wersji hc.

**Comment by kvokul** [comment]
Starałem się opisać to obrazowo i wg wskazań, które znalazłem gdzieś na serwerze: link do questa, przedmiot z którym jest problem. Przedmiot na oko można "clicknąć" i ma opcję use, tylko, że nie wywołuje to efektu w queście.

Pozdrawiam
