### ISSUE TITLE
[EN][Rogue] Enemy Smoke Bomb

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7068]
Enemy Smoke Bomb should have red-crimson red effect, proof https://youtu.be/_Csv-0VZWDo?t=15m27s
On atlantiss both own and enemy smoke bombs are same.
http://cata.openwow.com/spell=76577

**Comment by Genomnomnomnom** [comment]
Also, if you place Smoke Bomb, and your enemy puts Smoke Bomb somewhere else, you can still perform actions from you Smoke Bomb which affect enemy Rogue. Every SB should create different LoS area, but it  seems Smoke Bombs are connected into one LoS.

**Comment by kadi2** [comment]
@Genomnomnomnom  It's not true 
http://www.skill-capped.com/watch/6587/neilyo-rogue-vs-rogue-guide/ // 21:20

**Comment by Genomnomnomnom** [comment]
@kadi2 Well I don't have account to watch this but if it's blizzlike it's good to know :)

**Comment by kadi2** [comment]
@Genomnomnomnom  it was free at that point when i posted it. Ya it's blizzlike.

**Comment by xolon** [comment]
Fixed in rev. 5232
