### ISSUE TITLE
[EN][Priest] Enemy Priest Power Ward: Barrier

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7070]
Enemy Priest Power Ward: Barrier should be red/crimson red, proof https://youtu.be/usQfBdPBkg4?t=1m12s
On atlantiss own and enemy Power Ward: Barrier are the same http://i.imgur.com/hVBFN08.jpg
http://cata.openwow.com/spell=62618

**Comment by lamaATS** [comment]
Fixed in rev. 5219
