### ISSUE TITLE
[PL][Spell] Feral charge

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#7072]
Po użyciu feral charga w cat formie powinniśmy doskakiwać za przeciwnika http://www.wowhead.com/spell=61132/feral-charge#changelog

**Comment by Jenovas** [comment]
Następnym razem proszę napisz chociaż co źle działa. 
Nie będziemy teraz wchodzić do gry, robić sobie druida i testować i szukać o co Ci chodzi.
