### ISSUE TITLE
[EN][Quest][The Lost Isles][Miner Troubles] Frightened miner script broken

### ISSUE THREAD

**Issue by muddykinz** [Atlantiss/BugTracker#708]
http://www.wowhead.com/quest=14021/miner-troubles

The miner is supposed to stop at each node and collect the ore, however, he just walks to the end and stands doing nothing.

(minor) he's also supposed to attack the monkeys as you walk with him, but this isn't necessary.

**Comment by Tj20** [comment]
I did the quest yesterday and the miner stopped at each node (didn't see if he was doing the "mining" animation, since I was doing the photo quest meanwhile).

It's true though that he doesn't help you fighting, he just continues walking down its path.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593
