### ISSUE TITLE
[PL][Quest]Lycanthoth the Corruptor

### ISSUE THREAD

**Issue by Maksi85** [Atlantiss/BugTracker#7081]
Jest to jeden z questów na Mount Hyjal. Polega on na przywołaniu oraz pokonaniu wrogo nastawionego ducha. Po jego pokonaniu powinien pojawić się przyjazna wersja wilczego ducha u którego można oddać i wziąć kolejnego questa. Problem w tym, że po pokonaniu wroga, nasz przyjaciel się nie pojawia. 

![wowscrnshot_040316_125019](https://cloud.githubusercontent.com/assets/11136167/14232058/67026708-f99b-11e5-8b48-5b99ec7585da.jpg)

PS. Sprawdzałem wiele razy, to nie jest wina peta.

**Comment by eryczek1615** [comment]
Ja też tak miałem i po wyjściu i wejściu do jaskini pojawił się
