### ISSUE TITLE
[Pl][raid][firelands]dziura w teksturach

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#7082]
na podescie gdzie rozgrywa sie walka z ragnarosem na skraju prawej strony podestu jest dziura w teksturach do której wpadaja scions of flame na trzeciej fazie i meteory nie wiem jak z lewa strona i czy jest wiecej takich dziur nie sprawdzałem wiem na pewno że z prawej strony na pewno takowa jest.

**Comment by krecik88** [comment]
po ostatnim udpate powinno juz byc dobrze
