### ISSUE TITLE
[PL] [RAID] ruins of ahn'quiraj - Classic raid

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#7083]
Zrobilem sobie ten klasyczny raid, ale itemy z bossow w ogole nie dropia, tj z lasta dropnal tylko item ktory zaczyna q i 0 itemow innych - epic 
hunter dropnal tylko niebieskie buty, brak jeszcze dodatkowo q itemow ktore daja repe po oddaniu do npc.
Reszta bossow dziala tylko drop ubogi
W dodatku nie ma kufrów ktore powinny byc http://www.wowhead.com/object=180691/scarab-coffer

http://www.wowhead.com/zone=3429/ruins-of-ahnqiraj - "Much like AQ40, tokens drop off bosses here. These provide class specific rewards: a ring at honored, a cloak at revered and a weapon at exalted. There is a set bonus for all thre"

Trashe nie dropia itemow:
http://www.wowhead.com/item=20873/alabaster-idol
http://www.wowhead.com/item=20866/azure-idol
http://www.wowhead.com/item=20868/lambent-idol
http://www.wowhead.com/item=20872/vermillion-idol
http://www.wowhead.com/item=20869/amber-idol
http://www.wowhead.com/item=20870/jasper-idol
http://www.wowhead.com/item=20871/obsidian-idol
http://www.wowhead.com/item=20867/onyx-idol

http://wowwiki.wikia.com/wiki/Ahn'Qiraj_scarabs
Linki osobno - 
http://wowwiki.wikia.com/wiki/Bone_Scarab
http://wowwiki.wikia.com/wiki/Bronze_Scarab
http://wowwiki.wikia.com/wiki/Clay_Scarab
http://wowwiki.wikia.com/wiki/Crystal_Scarab
http://wowwiki.wikia.com/wiki/Gold_Scarab
http://wowwiki.wikia.com/wiki/Ivory_Scarab
http://wowwiki.wikia.com/wiki/Silver_Scarab
http://wowwiki.wikia.com/wiki/Stone_Scarab

Re: Guild achievements for classic dungeons/r | 2010-09-14 03:46 | Mumper
AQ20 has been converted to a 10 player raid. 

Tak wiec loot caly mog sie wypierdziec przez ta zmiane ;)

**Comment by fruvel** [comment]
moderator change name on [PL][RAID][Classic] ruins of ahn'quiraj

**Comment by pistonkosiarz** [comment]
Z trashy itemy dropią, ale musisz mieć questy, co do itemów z bossów loot jest słaby, ale dropi. Po prostu musisz kilka ID wykorzystać, jednak jest jedna rzecz o której nie napisałeś, mianowicie po zabiciu pierwszego bossa (Kurinnaxxa) powinien przybiec NPC (Lieutant General Andorov), który powinien rozpocząć even i pomóc przy zabiciu drugiego bossa ( General Rajaxx). Po skończonej potyczce powinien stać się vendorem z 2 recepturami do Blacksmithingu.

**Comment by Piklo** [comment]
posted fix for boss loot at forum:
http://community.atlantiss.eu/index.php?/topic/11894-7083-ruins-of-ahnqiraj-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
