### ISSUE TITLE
[Pl][raid][firelands]Alysrazor

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#7086]
podczas encountera przy klinknieciu piórka rozpoczyna sie rozmowa zamiast otrzymanie stacka co całkowicie uniemożliwia latanie na pierwszej fazie .

**Comment by Quban** [comment]
wiem :D

**Comment by Bildo** [comment]
śmiechłem iksde

**Comment by EnPra** [comment]
Google translated the post and can confirm it. Alysrazor is broken right now. Feathers can't be picked up(tries to start a dialogue), and if you wipe you cannot start the boss with the feather in the middle. GM answered our ticket and tried to start it but failed.

**Comment by Bildo** [comment]
fixed, wait for an update
