### ISSUE TITLE
[EN] [Talent][Mage] Instant Pyroblast! crits don't count towards hot streak procs.

### ISSUE THREAD

**Issue by flashxx** [Atlantiss/BugTracker#7089]
Hello,
as the title says, instant pyroblasts don't count towards hot streak crit count. This is a significant dps loss for a fire mage.

On the screenshot you can see that after getting hot streak proc, I use direct spell + the instant pyroblast. Both of them critically hit, however new hot streak buff does not proc.
http://i.imgur.com/PhWDfPK.jpg

**Comment by anxanas** [comment]
It shouldn't count, only hardcasted pyroblasts can trigger hotstreak. It was the way you are saying it should be a few months ago, but it was fixed

**Comment by BialyADI** [comment]
works as indeed.

**Comment by kadi2** [comment]
Not a bug.
