### ISSUE TITLE
[EN][Dungeon] Firelands - Majordomo Staghelm

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#7091]
Currently you can't attack Majordomo's back and still stack for the flame scythe damage because his back range is wrong.

You should be able to attack his back right behide his pincer and still properly take the aoe damage. 

http://www.icy-veins.com/wow/majordomo-staghelm-dps-strategy

"Melee DPS classes suffer greatly if they are unable to attack mobs from behind, and Feral Druids and Rogues especially so. Fortunately, these classes can position themselves to the boss' sides, right behind either one of his pincers. This causes their attacks to be counted as being "from behind", while also causing them to properly soak Flame Scythe."

**Comment by Kaldros** [comment]
Bump because it's an important issue.

**Comment by Jenovas** [comment]
Should be fixed with rev . 5013
