### ISSUE TITLE
[EN][Quest][Cataclysm][Orgrimmar]Unfamiliar Waters

### ISSUE THREAD

**Issue by geeorgee** [Atlantiss/BugTracker#7092]
I cannot talk to the NPC, im clicking on him but there´s no option for talk or anything. Please fix it. You managed to fix entire zone one quest shouldn´t be problem.

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/5406

**Comment by Kiperr** [comment]
Duplicate #5406 .
