### ISSUE TITLE
[EN][Raid] Shannox Heroic 

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#7096]
While testing on the PTR,here is the bug we found on this fight:

1)Rageface isn't immune to CC,making the fight way more easier for the dps kiting him;

2) The boss + dogs + traps are doing WAY TOO LOW damage;

3) Rageface actually gets his Wary buff, but this doesn't keep him from getting trapped in a crystal. So the buff is there, but It doesn't work as intended.

4) Rageface used Face Rage on Shannox tank;

5)Engaging the boss gives you the HC achievement instantly.

6) Rageface increased critical strike chance to 100% doesn't work. We had out mage having normal hits while casting on rageface.

That's all we found for now,we tested Baleroc and it's in a really good state ,Gj developers :D

**Comment by Lonerin** [comment]
#3
Rageface actually gets his Wary buff, but this doesn't keep him from getting trapped in a crystal. So the buff is there, but It doesn't work as intended.
Alde wrote it wrong :D
6) Rageface increased critical strike chance to 100% doesn't work. We had out mage having normal hits while casting on rageface.

**Comment by Aival94** [comment]
I think all these bugs are fixed so probably better close it @TranceAccount
