### ISSUE TITLE
[EN][Warlock][Shaman][Pets] Tremor Totem doesn't affect Warlock's pets.

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7097]
For some reason tremor totem doesn't affect warlock's pets. It works fine with Spirit Wolfs. Didn't test other pets yet.

https://youtu.be/VtrEWrfDCJA?t=27s // Water Elemental and Fel Hunter
http://www.wowhead.com/spell=8143/tremor-totem

**Comment by kadi2** [comment]
It's possible it has something to do with Turn Evil ability, which as far as i know shouldn't be removed by Tremor Totem.

**Comment by Jenovas** [comment]
So what is the bug? That normal fears dont get removed from pets?

**Comment by kadi2** [comment]
@Jenovas Ya exactly.

**Comment by lamaATS** [comment]
Fixed in rev.  5251
