### ISSUE TITLE
Premium Points (Need Help)

### ISSUE THREAD

**Issue by Heart1783** [Atlantiss/BugTracker#7099]
Hello,So im using this debit card called (Greendot) so it's connected with my paypal the money is on the card , and connected to paypal so i go to the atlantiss webswite go to the premium points thing click on the 300 points go to the paypal options i enter my paypal account info...then it takes me to secure.przelewy24.pl and says 
:   
The transaction is expected to confirm have not yet received confirmation of payment from the bank. Confirmation should come in no more than 5 minutes. Be sure to wait for the outcome of the transaction. Remember number and password transactions for a possible complaint. Wait for confirmation ...

And i wait and wait and wait and wait...and then it usualy times out. I need help on this issue i am aware its not a bug (Or may be a website bug) i have no clue but i need help and this is the only place i knew to look so if a gm could help me or something 

(FYI)!! I AM IN THE USA NOT POLAND.

**Comment by Bastion** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Heart1783** [comment]
Bastion,couldent just leave a helpfull coment on how to fix this issue? duno how to or what? cause it seems like the atlantiss.eu website just doesnt want my money ...they need to make it more user friendly and accept all forms of cash income......would be worlds easier

**Comment by Heart1783** [comment]
scratch that ima jut buy something else thanks for wasteing my time!

**Comment by Bastion** [comment]
bugtracker is for game bugs
