### ISSUE TITLE
[EN][Raid] Majordomo Staghelm Heroic

### ISSUE THREAD

**Issue by milzo** [Atlantiss/BugTracker#7102]
1. Concentration bar is getting resetted after player receives a heal (can be overheal too), however self heal such as [Recuperate](http://www.wowhead.com/spell=73651/recuperate) isn't affecting that. 
2. [Burning Orbs](http://www.wowhead.com/spell=98584/burning-orb) despawns every time after half a second or so.
3. [Searing seeds](http://www.wowhead.com/spell=98620/searing-seed) explosion is not resetting Concentration bar, however that might not be a bug, not sure about this one.

Other than that boss is working fine, numbers are also correct from what we've seen.

**Comment by kadi2** [comment]
Did you test Warlock's Life Tap?

**Comment by milzo** [comment]
No to both questions as we didn't have those two classes, however this was just a "shortlist". Quban is aware of the bugs and what's causing them.

**Comment by freddie12** [comment]
Addition to this, Unholy Frenzy is resetting the Concentration. Only damages from abilities related with encounter should reset it. Self-hurt abilities shouldn't affect Concentration.

UH Frenzy: http://www.wowhead.com/spell=31626/unholy-frenzy

**Comment by linesar** [comment]
Shadow Word: Death from Priests also.

**Comment by tnarf** [comment]
10man
Spirit of the Flame (cats) have too big dmg from auto atack.
They do ~80k on Blood DK, when should ~30k (after nerf) or ~45k (pre nerf; big spread)


Links to WoL from 2012:
http://www.worldoflogs.com/reports/ccnd4so9mv5tdfmp/xe/?s=2447&e=2696&x=sourceName+%3D+%22Spirit+of+the+Flame%22%0D%0AAND+targetName+%3D+%22Rangoon%22
http://www.worldoflogs.com/reports/6iq5h8qekk1k1dw3/xe/?s=4130&e=4374&x=sourceName+%3D+%22Spirit+of+the+Flame%22%0D%0AAND+targetName+%3D+%22Feliandi%22

Link to WoL from 2011 before last nerf:
http://www.worldoflogs.com/reports/3bhvrovpyis241sz/xe/?s=7647&e=8199&x=sourceName+%3D+%22Esprit+de+la+flamme%22%0D%0AAND+targetName+%3D+%22Ysanne%22

**Comment by LaveniaGithub** [comment]
All issues have been fixed.
