### ISSUE TITLE
[PL][Raid] Ragnaros

### ISSUE THREAD

**Issue by DonKefa** [Atlantiss/BugTracker#7103]
No to sytuacja wygląda tak, że młotek się rusza, a nie stoi w miejscu co uniemożliwia nam zbicie addów wystarczająco szybko zanim dojdą.

https://www.youtube.com/watch?v=6V-XXJel4W4

**Comment by Quban** [comment]
Addy dalo sie zbic wystarczajaco szybko :D bo nie ida do mlotka tylko do triggera, ktory w tym momencie ma visuala i go widac :D Zmylilo was to ze mlotek wyladowal po lewej, powienien byc po prawej. Przyjgladne sie temu, tylko jakby dalo sie troche dluzszy fragment filmu tak z 15-20s wczesniej co sie dzialo bylbym wdzieczny ;)

**Comment by DonKefa** [comment]
Wcześniej nie miało to większego znaczenia, bo to był pierwszy trigger addów. Wcześniej to wskakiwałem w trapy i robiłem dps. Powtarzaliśmy to chyba z 5 razy i za każdym razem nas młotek mylił - w końcu odpuściliśmy sobie.

**Comment by eryczek1615** [comment]
Czasami jest tak że  podczas fazy przwjściowej gdy zginie target Ragnarosa to on obiera nowy i mlotek za nim się porusza.

**Comment by Quban** [comment]
> Czasami jest tak że podczas fazy przwjściowej gdy zginie target Ragnarosa to on obiera nowy i mlotek za nim się porusza.

faktycznie zginal wam tank

**Comment by eryczek1615** [comment]
tylko, że nam jak młotek padł na środek i zaczął się ruszać to addy i tak szły na środek

**Comment by DonKefa** [comment]
Rzeczywiście. Nie zauważyłem, że tank padł. Za pierwszym razem jak nagrywałem to młotek stał w miejscu (czyli tank żył), czyli można to uznać za Visual Bug - niestety mylący. Miło by było gdyby jednak została jakaś tam poprawka zaimplementowana. Myślę, że wszystko wyjaśnione.

**Comment by Quban** [comment]
postaram sie znalezc problem jak wpadne na jakis pomysl :dancer:

**Comment by Kozakko** [comment]
Jeżeli to może być pomocne to podobny bug pojawia się również podczas encounteru Valiony i Theraliona w Bastion of Twilgiht. Podczas fazy gdy Valiona jest na ziemi, castuje Devouirng Flames i jeśli podczas casta się ją tanuntnie to zaczynają się dziać cuda wianki z kierunkiem tego nieszczęsnego breatha. Smok się kręci zionąc przez co na serio ciężko określić pierwotny kierunek. (W requescie nastąpiła zmiana targetu podczas używania umiejętności przez Ragnarosa, a dokładniej rzecz biorąc śmierć tanka)

**Comment by Aival94** [comment]
I have encounter this bug when Ragnaros is about to use Sulfuras smash and we go to one intermissiong phase but it does not happen every time but only around 10% of the times sulfuras smash is being cast the same time as intermission phase.

During this time boss seems to not go to intermission phase and continue attack the tank(as it take Magma Blast if move away from the lava of Ragnaros) but adds are moving to the normal location of the hammer(the small infernal spell "bunny") and if they reach they explode normally.

If i see other situations where this bug occur will make a comment here i suppose.

**Comment by Respect69** [comment]
Coś się również zepsuło z timerami na Ragnarosie. Przykładowo jest taka sytuacja, że w tym samym momencie kiedy jest molten seed i trzeba się zbiegać, pod bossem pojawią się engulfing flame i to za każdym razem. Nie powinno tak być.

**Comment by Coolia** [comment]
Widzialem tego buga 2x w ciagu ostatnich dwoch dni i za kazdym razem wygladalo to tak:
- HP bossa jest blisko zmiany fazy
- Boss uzywa Sulfuras Smash
- Jeszcze zanim mlotek opadnie raid przebija hp Raga i zaczyna sie faza przejsciowa
- Po uderzeniu ze Smasha boss dalej stoi w lawie i bije tanka oraz mlotek sie porusza w inne miejsce niz spadla animacja
- Tankowie umieraja od Magma Blasta (bo odbiegli bic male addy albo lapac te duze) wiec boss zaczynacz krecic znnowu mlotkiem
- Wipe
Bardzo ciezko jest przezyc faze przejsciowa z bossem ktory juz wszedl w kolejna faze zamiast siedziec pod lawa. Dodatkowo visual bug mlotka myli graczy i nie wiedza oni gdzie faktycznie spada mlotek.

**Comment by Quban** [comment]
probably fixed http://atlantiss.eu/changelog#rev5025
