### ISSUE TITLE
Fishing skill up rates too high

### ISSUE THREAD

**Issue by Ehrel** [Atlantiss/BugTracker#7109]
Currently fishing skill up rates are so high it's a torture to get it to 525. According to some players advancing from 350 to 525 takes as much time as the whole 0 to 525 should take. Why not make this blizzlike? Or if it's bugged is there any way to fix it? Yeah I get that you can still make it to 525 and a lot of people did, but since you call this server blizzlike, it would be nice not to torture players with these extreeme rates just to get those heirloom legs from guild achievment.

**Comment by xolon** [comment]
they should be, on retail it took from 450-525 3 hours, and from 375-450 2,5 hours, 300-375 2hs
