### ISSUE TITLE
[EN][Quest][Deepholm] [Rocky Upheaval] 

### ISSUE THREAD

**Issue by wicu8** [Atlantiss/BugTracker#7110]
Speaking to Gorsik the Tumultuous is impossible.. As well as other quests when i can't speak with npc's.. like [Traitors Bait] ... 

http://www.wowhead.com/quest=26577/rocky-upheaval

**Comment by Luna-maria** [comment]
make sure you're not 'at war' with therazane?

**Comment by wicu8** [comment]
Ye, the problem was "At war" status with them. Thx. But Quest "Traitor's Bait" in ogrimmar is still bugged :/

**Comment by Luna-maria** [comment]
gotta make a separate post for that buddy :p
