### ISSUE TITLE
[pl][raid][ulduar] maszyny

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#7112]
maszyny nie pojawiaja sie po uruchomieniu eventu na poczatku tylko pod lewiatanem u demo nie traci pirytu za kazdy strzał a powinno tracic 10%  wad choppery maja zbieranie pirytu czego nie powinny posiadac u siege nie działa szarża wieze i beacony da sie zbić tylko przy udezeniach w portale zamiast w całe wieze to tyle co zauwazyłem narazie

**Comment by avalancze23** [comment]
dodatkowo zauwazyłem ze siege nie traca steam presshure po uzyciu umiejetnosci oraz trashe przed leviatanem pulluja sie tylko jak sie do nich blisko podejdzie a powinno dac je sie zbijac z daleka i niektóre moby nie otrzymuja dmg z niebieskich pocisków demo w samej walce z leviatanem boss targetuje maszyny które sa poza arena i boss sie resetuje

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.
