### ISSUE TITLE
Occu'thar loot bug

### ISSUE THREAD

**Issue by LOTHAR461989** [Atlantiss/BugTracker#7113]
Today i was at class run in Baradin Hold and Occu'thar drop only 1 item.. is it possible ? He drop only 1 item for warlock .. well, for me it's not a problem because i'm a warlock...but.. there was a palyers who rage and speculated i'm a ninja.. so.. here it goes..

http://imgur.com/a/WTep6

**Comment by Bildo** [comment]
bt rules
