### ISSUE TITLE
[EN][Quest]Thunderfury, Blessed Blade of the Windseeker - Unobtainable

### ISSUE THREAD

**Issue by wasatix** [Atlantiss/BugTracker#7119]
You can't turn in quest for this legendary blade named (quest) "Thunderaan the Windseeker". Npc named Highlord Dimitrian stays with silver question mark after you gather all quest items required for the completion of this quest.
So you get stuck in the chain AFTER spending all the time to gather materials - which is infuriating.

**Comment by Walniety** [comment]
Wtf why this dont work :( we need Thunderfury, Blessed Blade of the Windseeker bcs if there wont be Thunderfury, Blessed Blade of the Windseeker them we can't spam on chat Thunderfury, Blessed Blade of the Windseeker but we can spam Thunderfury, Blessed Blade of the Windseeker thanks to atlas loot who have Thunderfury, Blessed Blade of the Windseeker in libary but better repair quest for Thunderfury, Blessed Blade of the Windseeker  bcs its one of the best weapons in game :D

**Comment by Sainsyl** [comment]
Did you try abandoning it and retaking? When mats are included i noticed sometimes it bugs like this,but when i retake it it works fine. Alternatively,moving them in bank and back in your bags might work too.

**Comment by wasatix** [comment]
Nope, sadly that doesn't help.

**Comment by Krooks187** [comment]
Bruh, takes so damn long to gather everything needed, excited everytime a binding drops just to realise you can't have this iconic sword. Literally the only reason I came to play on this private server was to obtain these legendaries. Cmon devs help us out here please :(
