### ISSUE TITLE
[EN][Core] Guild reputation from bosses

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#712]
Bosses are not giving guild reputation

www.wowhead.com/faction=1168

Additional information
http://wow.gamepedia.com/Guild_group
http://wow.gamepedia.com/Guild_reputation
http://gaming.stackexchange.com/questions/15193/how-do-you-gain-guild-reputation

**Comment by krecik88** [comment]
Is the bug still ocurring? I think that in some rev we have added guild exp/rep to bosses.

**Comment by Varchord** [comment]
It's still not working

**Comment by krecik88** [comment]
But if i am correct, at the end of random dungeon exp/rep is added? And on BG also?

**Comment by Varchord** [comment]
BG and arena WINS should grant rep. Also honorable kills should grant reputation at 1 reputation per 20 honor rate.

Random dungeon completion gives rep because it's treated as quest. If someone wouldn't be level capped they would gain experience too.

The only thing that doesn't work right now is reputation from killing bosses and I think from honorable kills

**Comment by Varchord** [comment]
And that is putting pve players at disadvantage

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3779

**Comment by Varchord** [comment]
Bildo are you retarded? My issue which is 8 months old and has number 712 is DUPLICATE of an issue which is a 25 days old and has number 3779?

**Comment by Bildo** [comment]
so what, is that a difference ?

**Comment by Varchord** [comment]
You've confirmed my suspicions. You ARE retarded

**Comment by Bildo** [comment]
I'm just tired of you, one more word and u will say goodbye.

**Comment by Atraac** [comment]
Dortho jełopie, spojrzyj Ty czasem na daty.

**Comment by Varchord** [comment]
I know it can be hard. But you have to face the truth here
