### ISSUE TITLE
[EN][Professions][Tailoring]

### ISSUE THREAD

**Issue by ma95rius** [Atlantiss/BugTracker#7124]
I have a recipe for Vicious Embersilk Boots, but when I try to make them, I create Bloodthirsty Embersilk Boots. Same thing happens with other Vicious items (they turn to Bloodthirsty). Why does it happen? I saw similar problem with #3810 and #2414.

**Comment by ponpontos** [comment]
If actually had bothered reading the other reports, you'd see that it's because we're in patch 4.2 in terms of content and that is a 4.3 item.

**Comment by ma95rius** [comment]
thanks :) i'll be more observant next time..
