### ISSUE TITLE
[EN][Quest] Deepholm, Realm of Earth

### ISSUE THREAD

**Issue by Rismak** [Atlantiss/BugTracker#7125]
When you accept this quest and hop onto Aggra's Wyvern and you are flying and you disconnect or log off. When you log right back on you are kicked off the mount and killed, you respawn in Barrens. 

The problem is that there is no way to get back to where Thrall and Aggra are since the portal to them is not up nor is the portal directly to Deepholm.

**Comment by Luna-maria** [comment]
hmm need to open a ticket to fix it

**Comment by Aival94** [comment]
reported/related: https://github.com/Atlantiss/BugTracker/issues/645
