### ISSUE TITLE
[PL][Quest] Deepholm, Realm of Earth

### ISSUE THREAD

**Issue by Ordo1** [Atlantiss/BugTracker#7126]
W zasadzie to samo co w poście Rismaka, tylko tyczy się to strony alliance.
Jeśli podczas lotu na wyvernie straci się połączenie z internetem lub po prostu jeśli zeskoczy się z wyverny to postać ginie i odradza się w Westfall. Gdy wrócimy do Stormwind to portalu do Deepholm nie będzie. Nawet jeśli użyjemy mikstury do teleportacji nie da się wziąć chain questów w Deepholm.

**Comment by Aival94** [comment]
reported/related: https://github.com/Atlantiss/BugTracker/issues/645
