### ISSUE TITLE
[EN][Hunter] Cobra Strikes problem

### ISSUE THREAD

**Issue by Sakima92** [Atlantiss/BugTracker#7128]
Cobra Strikes talent procs but the pet doesn't critically hit like it should. Talent ID:53260

**Comment by user1011** [comment]
Wowhead link please

**Comment by Jenovas** [comment]
Works properly.
Basic attack doesnt mean melee attack.
Basic attack for pets is - Smack, Bite, Claw depending on pet

**Comment by Sakima92** [comment]
Ah, alright thank you, wish tooltip was a bit more clear about that. Silly Blizzard.
