### ISSUE TITLE
[En][Raid] Deathbringer Saurfang BUGGED

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7129]
![wowscrnshot_040816_175906](https://cloud.githubusercontent.com/assets/16594771/14389645/eaa2e1e8-fdb3-11e5-8348-155a850d51db.jpg)
![wowscrnshot_040816_175902](https://cloud.githubusercontent.com/assets/16594771/14389647/ead68df4-fdb3-11e5-9156-a84b0f0e3ae7.jpg)
this boss has been bugged for a long time now and it makes the entire raid undoable and needs to be fixed, when he is attacked by any form of damage or aggrod he calls out: BY THE MIGHT OF THE BITCH KING!!!!!!! and resets, he cant be killed this way making the whole raid undoable

**Comment by Aviannaqt** [comment]
duplicate

**Comment by Tigerief** [comment]
duplicate but still not fixed x_x
