### ISSUE TITLE
[EN][Quest][The Cap of Stranglethorn] Ol'Blasty

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7132]
Hi,

I have a problem with the quest [Ol'Blasty] in The Cap of Stranglethorn : http://www.wowhead.com/quest=26647/ol-blasty

1) The cannons are not on board, but in the water under the boat.
2) When I click on the cannons, I can not "climb above" and shot at Smilin' Timmy Sticks.

So the quest can't be completed. 

Thank you for your help :)
Good day.

**Comment by Dzdzia** [comment]
Hi
There's not blizzlike way to complete this quest.
You have to kill Smilin' Timmy Sticks as like normal mob and w8 for respawn to complete the quest. If you're low lvl ask someone with 85 to help you.

**Comment by Snake90** [comment]
Ok, I will try :)

**Comment by Snake90** [comment]
And ... it's work by killing Smilin' Timmy Sticks like normal mob.

**Comment by TranceAccount** [comment]
#5308
