### ISSUE TITLE
[EN][Spell][Mage] Dragons Breath, Cone of Cold

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#7135]
Ive noticed alot of times when you jump or move in a certain way that breath and cone of cold doesnt hit targets even if they are near and in front of you, same is happening with priest fear the yards of this abilitys are bugged somehow please try to fix this cos its annoying thx.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/594 Has been closed for some reason. cone spells are just a small part of this. The problem hits also single target spells that require facing.

**Comment by kadi2** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16885#issuecomment-204744091

**Comment by lamaATS** [comment]
Today I will try to port fix for this from TC.

**Comment by lamaATS** [comment]
Fixed in rev. 5228
