### ISSUE TITLE
[EN][NPC]Furious Hyjal Warden

### ISSUE THREAD

**Issue by Admarx** [Atlantiss/BugTracker#7136]
http://www.wowhead.com/npc=43427/furious-hyjal-warden

They should actually do some damage, it's getting pretty annoying when you can't even normally TP to Nordrassil because you get welcomed by "AFK" guards and lots of Horde/Alliance players greeting you.

**Comment by Aival94** [comment]
Normally those should hit extremely hard those that try to PVP near them but here nobody change that.

Some comments about situation it was in Cata: [Wowhead Comments](http://www.wowhead.com/npc=43427/furious-hyjal-warden#comments:id=1564355)
