### ISSUE TITLE
[DK] Glyph Of Resilent Grip

### ISSUE THREAD

**Issue by Unangwata** [Atlantiss/BugTracker#7138]
Fucking shit doesn't work on hunter morons deterrence, yeah give them more edge, no, fix that shit.

**Comment by mati865** [comment]
Maybe find some proofs?
Technically Deterrence DEFLECT spells.

**Comment by xolon** [comment]
"There's a lot of confusion over which spells are considered an immunity when using Glyph of Resilient Grip. Spells such as roots or a hunter's deterrence are not considered immunities. Spells that are considered immunities are:
● Divine Shield
● Ice Block
● Banish
● Cyclone
● Blessing of Protection
● Pillar of Frost "
http://us.battle.net/wow/en/forum/topic/2211722468
