### ISSUE TITLE
[PL][DK][Quest] The Light of Dawn

### ISSUE THREAD

**Issue by CirusSir** [Atlantiss/BugTracker#7139]
![wowscrnshot_041016_010647](https://cloud.githubusercontent.com/assets/18371861/14407061/d9818a0a-febb-11e5-9696-210734a72867.jpg)
![wowscrnshot_041016_010652](https://cloud.githubusercontent.com/assets/18371861/14407064/e0907766-febb-11e5-8270-56bc3e77ad49.jpg)
Po tym quescie powinno się dostać 3 talent pointy co widać na pierwszym zdjęciu. Jednak po wejściu w talenty tych 3 punktów brak (powinno być 28).

**Comment by Thorghar** [comment]
Ten sam problem i jak widać nie naprawiono...
Nie dostałem punktów umiejętności za zadanie więc BUGGED !!!
