### ISSUE TITLE
[EN][Quest][Western Plaguelands][Combat Training]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7142]
Hi,

Problem with the quest [Combat Training] in Western Plaguelands : http://www.wowhead.com/quest=27174/combat-training

The NPC doesn't give me some of his men and I can't attack Gory.

Thanks for your help.

**Comment by 1Andas** [comment]
Confirmed. Couldn't complete it recently as well. It used to work a long time ago though, because I did it on my main.

**Comment by coba999** [comment]
Confirmed.
