### ISSUE TITLE
[pl][raid][firelands] ragnaros

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#7143]
na ragnarosie wszystkie addy poza sons of flames spadaja pod tekstury to samo tyczy sie maga uzywajacego blinka itp

**Comment by Aival94** [comment]
When we did it yesterday around 23:50 server time it was working ok.

**Comment by BialyADI** [comment]
Yeah i kill Ragnaross thankt to that ^^.
I complete the game xD.

**Comment by Respect69** [comment]
Confirmed, we had the same problem today. Sometimes it happens to meteors too :/

**Comment by EnPra** [comment]
google translated from polish and can confirm. the floor texture is broken on rag. mages cannot blink, flame orb falls through sometimes, hunter pet falls down and the ragnaros adds cannot be targeted

**Comment by Atlntssplayer** [comment]
Also happened to the raid I was in today.
Mage went under the platform after blinking.
Warlock's pets couldn't attack, they were invisible (I guess they were under the texture too) to the raid.
In front of the stairs leading to RAG's platform, it seemed to work allright, but as soon as the warlock walked on to the platform, his pet became invisible.
It made the raid not being able to do the encounter.

**Comment by BialyADI** [comment]
lol naw Encounter is so easy i do it today with pug...

**Comment by eryczek1615** [comment]
Inny bug dotyczący Ragnarosa.
Jego spell [Burning Wound](http://www.wowhead.com/spell=99399)nie powinien schodzić z tanka.
Na przykład ja trzymam Ragnarosa całą 1 fazę i to samo z siebie schodzi a powinno zejść wtedy gdy tankowie się zamienią.
Jeśli się mylę to przepraszam.

**Comment by Quban** [comment]
> Jego spell Burning Woundnie powinien schodzić z tanka.

Ten spell ma inner cooldown, wchodzi co 2 hit i jezeli tank uniknie ataku to spell nie wejdzie. Fakt przez te 20s powinien wchodzic czesciej. Mozliwe ze absorby buguja tu coś.

**Comment by Quban** [comment]
issue no longer in game
