### ISSUE TITLE
[PL][SPELL/CORE][STEALTH/INVINCIBLE/BG]

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#7149]
Na bg można przejmować bazy ( ab/battle of Gilneas) nie wychodząc z niewidzialności. Stawiam ze to http://cata.openwow.com/item=3823#objective-of jednak nie jestem pewny w 100% ponieważ za każdym razem gdy byłem tego świadkiem osobą zajmująca bazę był rogal (typka i sekretarka- horda, warto by się ich zapytać może oni powiedzą coś więcej na temat tego buga.) Problem wystepuje od dawna i sprawia że pvp staje się cyrkiem.

**Comment by Jallar89** [comment]
Pisalem juz o tym dawno i nikt tego nie naprawil ? 
W ally widzialem jak robil to rogal, ale tez priest Raketee (notabene notoryczny bugger) wczoraj wszedl w hordziackim AH na tekstury i wraz ze swoja paczką zabijali bezbronnych hordziaków

Mam na to screeny ale maile do atlantissa nie dochodzą. wysyłalem na complaints@atlantiss.eu

**Comment by pelekon** [comment]
Jeśli nie dochodzą Ci jakieś maile na complaints@atlantiss.eu to możesz poprosić kogoś o wysłanie za Ciebie, ew wysyłać do kogoś z ekipy na forum(najlepiej do mnie, admini dostają tonę wiadomości codziennie, więc to raczej zaginie), a my to już przekażemy gdzie trzeba.

**Comment by Reversion** [comment]
NIe tyle chciałem zglosić nadużycia w postaci bugowania co fakt że da się to zrobić ( a w takim wypadku BT wydaje się najodpowiedniejszym miejscem).

**Comment by pelekon** [comment]
Akurat tamten komentarz kierowałem do @Jallar89 :p Zbadamy tą sprawę, ale nie ukrywam przydały by nam się dodatkowe informacje jak to dokładnie wygląda.

**Comment by Reversion** [comment]
Sprawa wygląda tak- stoję na wprost flagi, nikogo nie ma obok mnie w pewnym momecie gracz przeciwnej frakcji ją zajmuje nie pokazując się;P nie ma jak zrobic ssa bo nie ma co na nim pokazać. Jak dokladnie się to odbywa, co tzreba zrobic/wypic itp itd nalezało by się spytać osób które to robią. Imo problem rozwiązała by blokada potionow na niewidzialność na bg.

**Comment by Jallar89** [comment]
po prostu znajdzcie miejsce w kodzie odpowiedzialnym za uzywanie flagi na bg i na sztywno dodajcie kod "zdejmujacy" efekt invisibility, tak jak zdejmuje sie wszelki stealth. nawet jesli to nie invisibility potion to nie zaszkodzi sprobowac.
ew. przejrzyjcie wszelkei efekty/aury czy jak to sie tam nazywa w kodzie i w momencie interackj iz flaga zdejmujcie z gracza wszelkie "potencjalne" niewidzialnosci

to nie moze byc az tak trudne

**Comment by Jallar89** [comment]
https://github.com/JallarGames/uploaded/blob/master/nitrorunes.avi
https://github.com/JallarGames/uploaded/blob/master/whitex.avi

Przy okazji nagrania z tym zdarzeniem :) You welcome...

**Comment by Jenovas** [comment]
Should be fixed in rev 4980.

**Comment by jissabraham** [comment]
[Invisibility Potion] it can be used to get post in stealth not flags y its removed
