### ISSUE TITLE
[EN] [Raid] Trial of the crusader

### ISSUE THREAD

**Issue by Sainsyl** [Atlantiss/BugTracker#7150]
All bosses fall through the floor now. Pets can still attack them and sometimes they come near,so you can put dots on them,but it takes really long time.

<a href="http://tinypic.com?ref=wm13yr" target="_blank"><img src="http://i64.tinypic.com/wm13yr.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://tinypic.com?ref=wbrjvr" target="_blank"><img src="http://i68.tinypic.com/wbrjvr.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
and with blink i fell down as well

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/6495
Other bug: https://github.com/Atlantiss/BugTracker/issues/5959
