### ISSUE TITLE
[EN][Warrior] Deep Wounds ignoring resilience.

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7152]
Hey. I noticed Deep Wounds is totally ignoring resilience. Previous report https://github.com/Atlantiss/BugTracker/issues/5822
Not sure if it's a bug at all, but warriors do unexpected high ammmount of damage from Deep Wounds. Ofcourse i did some tests and it does ignore resilience, was thinking that's okhay since it's based on the hit you dealt, but it's calculated from from your actual weapon damage cause it should.

"From what i seen in some patch notes long ago, DW is no longer a subject of % damage talents. So no enrage or 2hander spec affects it."

"Bleeds surpass armor reduction (but are subject to reduction by resilience if you are pvping).
There are three types of average weapon damage. Normalised, normal and unmodified."

http://www.wowhead.com/forums&topic=144974/a-couple-questions-about-the-deep-wounds-mechanic
This is the only trustable comment i found about in the internet. Everyone later on are crying about Deep Wounds ignoring resilience in mop.

http://cata.openwow.com/spell=12868 // Deep Wounds

i found something like this: AttributesEx4 |= SPELL_ATTR_EX4_IGNORE_RESISTANCES
AttributesEx6: 0x00003204 (SPELL_ATTR6_IGNORE_CASTER_AURAS
Prolly SPELL_ATTR6_NO_DONE_PCT_DAMAGE_MODS contains those 2 attributes in TC and nothing else which would make sense for Ignite and Combustion issues.

**Comment by BialyADI** [comment]
Its work like Ignite.

**Comment by kadi2** [comment]
@BialyADI Thanks for the clarification.

**Comment by blinkmaster** [comment]
yeah mechanic is like ignite BUT:
if it does DW damage from damage reduced by resilence ( so for example 1k crit reduced to 600 ) then its ok.
If it does DW damage from 1k crit dmg then its bugged

**Comment by kadi2** [comment]
https://youtu.be/YlSRcWU0mcQ?t=2m47s // Random s11 movie with s11 gear....
344 Deep wounds tick, after getting one critical strike.
On Atlantiss in tests i was getting 522 damage from Deep Wounds.
It's pretty clear it was dealing less damage on retail in pvp and resilience is prolly the only issue.

**Comment by aneq** [comment]
No it doesn't work like ignite. Ignite is based damage of the spell that procs it. DW is based on weapon damage, Therefore it should be reduced by resi

**Comment by kadi2** [comment]
DW munching?

**Comment by kadi2** [comment]
![](http://i.imgur.com/Ii7fv4R.jpg)

**Comment by fluessig** [comment]
holy fuck i just tested this, deepwounds does ignore resil, thats the reason why warrios are twoshotting my rogue :(

**Comment by brokenshard** [comment]
nice joke about deep wounds toping dps i can see the clear photoshopping mechonichs its not even close to 5th top damaging spell

**Comment by Jenovas** [comment]
Fixed rev  5449
