### ISSUE TITLE
[EN][NPC] Scalding broodling

### ISSUE THREAD

**Issue by zotmer** [Atlantiss/BugTracker#7154]
Scalding broodling (http://wowwiki.wikia.com/wiki/Scalding_Broodling) has a pickaxe equipped. (I have no idea how did they get it.)
Screen: 
![scalding_broodling](https://cloud.githubusercontent.com/assets/18169265/14424203/16975b20-ffe0-11e5-9227-b5bb9ce9150f.png)

**Comment by Aival94** [comment]
Some mobs started to evolve and they started handling weapons.Be carefull of them as they might start taking weapons with enchants next time :P
