### ISSUE TITLE
[EN][QUEST][Icecrown] "Cannot Reproduce"

### ISSUE THREAD

**Issue by Sylvictus** [Atlantiss/BugTracker#7155]
This quest: http://www.wowhead.com/quest=13320/cannot-reproduce#comments

It involves using the item "http://www.wowhead.com/item=44251/partitioned-flask" next to three plague cauldrons to get a sample from each one. Currently using the item does nothing except cause your character to have an endless "working" animation loop, and you never get credit.

Interestingly enough, if you press the escape key at any point after you try to use the item, while your character is stuck in this looping animation, the client itself will crash completely.

**Comment by Lidless** [comment]
up

**Comment by Lidless** [comment]
still doesn't work

**Comment by Dranerys** [comment]
The quest []( http://www.wowhead.com/quest=13335/before-the-gate-of-horror) got broken again. Using the item on the reavers doesn't do anything.

**Comment by Lidless** [comment]
Dranerys: Try to retarget the appearing "soul" things above the corpses and use the q item on those, not on the corpses directly. As I can remember it was an issue for me as well.

**Comment by Dranerys** [comment]
Thank you Lidless, that indeed worked!
