### ISSUE TITLE
[PL][QUEST] Traitor's Bait (part 7 of 8)

### ISSUE THREAD

**Issue by Harakuru** [Atlantiss/BugTracker#7158]
nie dziala ten Q, nie można kliknąć w NPC żeby z nim porozmawiać i przejść dalej.
poniżej screen z sytuacji:
<img>http://imageshack.com/a/img924/3028/hZ2BhD.jpg</img>
i filmik z prawidłowego działania Q:
<video>https://www.youtube.com/watch?v=UmjeFx0ssto</video>

**Comment by wicu8** [comment]
Ten sam problem.. Nie da się przez ten błąd odblokować portalu do TH.. Pisałem o tym 10 dni temu i dalej zero odzewu ze strony osób zajmujących się bugami.. Może w końcu łaskawie się ktoś tym zainteresuje??

**Comment by Thefakemccoy** [comment]
rev. 4970 Author: Wolffenstein :: 2016-04-12 19:10 - Waiting for update
[Orgrimmar/Twilight Highlands]:

Fixed Traitor's Bait quest not resetting properly
Fixed Unfamiliar Waters quest not resetting properly

**Comment by Harakuru** [comment]
jeżeli to miało znaczyć że naprawili to nie wyszło bo problem nadal jest. Nie można porozmawiać z NPCem.

**Comment by Thefakemccoy** [comment]
2016-04-12 19:10 - Waiting for update

**Comment by wicu8** [comment]
W końcu dzisiaj udało się zrobić ten quest.. Chyba coś poprawili
