### ISSUE TITLE
[EN][Raid][BoT] Fury of Cho'gall

### ISSUE THREAD

**Issue by HCGWill** [Atlantiss/BugTracker#7160]
Fury of Cho'gall (as well as the Corrupted Adherent add) is currently being cast on a timer, 55 seconds into the fight, regardless of boss HP.

How it should work: Fury of Cho'gall should only be first cast once the boss reaches 85%, with the add spawning 5 seconds later. After that Fury should be recast every 45s with an add following each alternate cast.

Proof: https://www.youtube.com/watch?v=QjqyM8aefnk
This group goes ~1:20 into the fight before the boss casts Fury of Cho'gall, right after he reaches 85%.

**Comment by aneq** [comment]
all timers on cho gall are wrong. Mind control is as well
the fun thing is, fury timing is correct on heroic

**Comment by HCGWill** [comment]
If you're referring to the 85% trigger for Fury that's also bugged in heroic.

**Comment by aneq** [comment]
then every group I've been on cho gall heroic with has roughly the same dps or its a recent bug

**Comment by HCGWill** [comment]
https://www.twitch.tv/nitrous127/v/60264023?t=2m30s

This was tonight when we were testing stuff with one less dps. Boss pushes at 87%.

**Comment by Quban** [comment]
> If you're referring to the 85% trigger for Fury that's also bugged in heroic.

yes its 55s now on both difficulties

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4972
