### ISSUE TITLE
[PL][Quest][Orgrimmar] Unfamiliar waters

### ISSUE THREAD

**Issue by Xadroth** [Atlantiss/BugTracker#7166]
Quest który został ponoć naprawiony w ostatniej łatce nadal nie działa. Jest taki sam problem, mianowicie NPC nie ma opcji dialogowej.
Screen z informacją, że quest został naprawiony:
![11412199_894733870586464_5132317600817310662_n](https://cloud.githubusercontent.com/assets/18057324/14474524/d59c9706-00fd-11e6-9364-b0d9fddc2e32.jpg)
Screen z gry:
![wowscrnshot_041216_222544](https://cloud.githubusercontent.com/assets/18057324/14474532/de5fb5da-00fd-11e6-8e3f-333f887eea19.jpg)

**Comment by arekczup** [comment]
Waiting for update = czekaj na naprawę

**Comment by pelekon** [comment]
Dostarczyłeś ss z changeloga, z widocznym ,,Waiting for update",  tego zapewne nie zrozumiałeś, więc przetłumacze: Czeka na zaktualizowanie serwera. Następnym razem proszę o użycie google translate jeśli nie rozumiesz angielskiego(chociaż tego nawet angielskim nie można nazwać bo to poziom z jakiejś 2 klasy podstawówki). Report do zamknięcia.
