### ISSUE TITLE
[EN][Raid] Cho'gall - Corruption: Malformation

### ISSUE THREAD

**Issue by HCGWill** [Atlantiss/BugTracker#7167]
Corruption: Malfomation, the debuff you get at 75% corrupted blood, currently casts a volley of shadowbolts at the entire raid. Video shows our mage with full corruption hitting the entire group with AoE shadowbolts.
https://www.twitch.tv/nitrous127/v/60264023?t=4m39s

How it should work: The debuff should only cast 1 Shadow Bolt at a random friendly target every 2 seconds. Video shows a full corruption mage on the right side sending Shadow Bolts in 1 at a time. Note that he Ice Blocks the debuff off around 3:13 which is why he stops casting them for the rest of the fight.
https://youtu.be/u9i_lPg_tPg?t=2m35s

PoV video from at full corruption mage. He only casts 1 Shadow bolt before ice blocking the debuff, but it's not a volley (happens right at 3:01)
https://youtu.be/QjqyM8aefnk?t=2m55s

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4972
