### ISSUE TITLE
[EN][Talent] Last Word (Paladin)

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#7168]
it says that it has a increased critical strike chance when used on targets below 35% health by 30% 1/2 60 2/2 but the thing is that it crited for 70k (and not like a usual word of glory crit heal for 30k) on on me when i was below 35% hp
so i think the talent might be bugged and increases the HEAL by 30/60% when used on a target below 35% hp and not the critical chance of it

**Comment by headachex** [comment]
Confirm. Insta heals for 65k arent normal.

**Comment by aneq** [comment]
Are you by any chance from sunwell?

**Comment by 1Andas** [comment]
What aneq said. There's a talent in Retribution tree called Selfless Healer. Go look it up.

**Comment by Jenovas** [comment]
Did you even test this? Or did a paladin kill you and you're making up bugs?
Tested and everything works fine.
Closing.

**Comment by scidrov** [comment]
yeah gues that random 70k heal happend just because, nice server

**Comment by Jenovas** [comment]
no there is nothing random, retri paladins have a talent that increase healing done of WoG if used on self. Wog scales with AP, when low on HP you have an increased crit chance. When healing someone else you have a 50% increase in WoG heal. You can turn on wings that farther increase healing. You can use ancient guardian for even higher heal. Sacred Shield increasing healing again even more.

Search for videos on youtube. There are videos from arenas where paladins retri heal for more than 100k using WoG.
