### ISSUE TITLE
[EN][Zone][Drop] Loot tables Azshara incorrect (pre-cata levels)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#7170]
Along with a bunch of proper-leveled items, i have thus far had [Smooth Leather Helmet](http://www.wowhead.com/item=8753), [Warmonger's Greaves of Spirit](http://www.wowhead.com/item=9962) and [Overlord's Crown of the Whale](http://www.wowhead.com/item=10207) drop in Azshara. The last two dropped from [Varo'then's Ghost](http://www.wowhead.com/npc=6118), I'm not sure about the first one, may have been [Warlord Krellian](http://www.wowhead.com/npc=8408).

Update: also [Ivory Wand of Stamina](http://www.wowhead.com/item=15279/) from a mob called General Fangterror, which shouldn't even exist anymore as far as I know (not sure though).

**Comment by VioletFlare** [comment]
He should still exist, he just got moved do a different position.
www.wowhead.com/npc=6650/general-fangferror

**Comment by Piklo** [comment]
posted fix on forum
