### ISSUE TITLE
[PL] [Raid] Firelands 10 - Lord Sterowania Nogami

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7171]
Po przepisaniu systemu sterowania nogami kompletnie nie da się nimi sterować.. Sytuacja wygląda tak:
mimo bicia np. tylko i wyłącznie lewej nogi, pasek nie ładuje się do końca, cofa się bez powodu w kierunku drugiej nogi. Momentami pasek w ogóle się nie nabija, co skutkuje wizytą w lawie.

**Comment by Quban** [comment]
cofa sie bo powinien, a pewnie ciezko sie steruje bo malo macie dps, bo za duzy prog dmg ustawilem widocznie ;d

**Comment by Respect69** [comment]
Właśnie mamy bardzo duży dps, nogami kompletnie nie da się sterować.

**Comment by Hexenbane89** [comment]
Stacki również nie schodzą :)

**Comment by Respect69** [comment]
Stacki schodzą tylko od aktywnych wulkanów, ale problem w tym, że prawie niemożliwe jest go w nie wprowadzić, bo nie można kierować.

**Comment by Quban** [comment]
Nie wiem ja robilem dzis lorda i bardzo latwo sie sterowalo

**Comment by ppiotrrek1000** [comment]
My dziś go ubilismy, za 3 podejsciem poprostu trzeba melasami bic bossa a nie krecic dps na addach

**Comment by Hexenbane89** [comment]
Na Addach sie nie kreci dpsu bo padaja od aoe a dużego bierze tank na bok, chodzi o to że Lord sobie łazi jak chce, stacki nie schodzą i jeżeli raid robi po 20k dpsu każdy to to juz jest HC czy jeszcze norm że on nie skręca normalnie ?

**Comment by Quban** [comment]
> stacki nie schodzą

to akurat jest nieprawda

**Comment by Hexenbane89** [comment]
No to wytłumacz mi w jaki sposób tutaj na Atlantisie grupa która bije po 20k+ dpsu nie może zabić Lorda,gdzie na Globalu jak robiłem FL to grupa która robiła tak mniej więcej 15k zabijała go bez większego problemu ? coś nie działa z nim tak jak powinno :/

**Comment by Respect69** [comment]
Stacki schodzą tak, jak powinny, czyli tylko od aktywnych wulkanów. Ale z tym sterowaniem to serio jest coś popsute. Wczoraj go ubiliśmy za 4 podejściem, ale cały czas byliśmy na granicy wejścia do lawy, bo on ledwo skręca, a pasek ledwo co się nabija.

**Comment by Quban** [comment]
to serio macie cos nie tak z dps na nogach,

**Comment by Hexenbane89** [comment]
Ale jako można mieć nie tak z DPSem jak ludzie są ubrani już prawie pod FL HC :dancer:

**Comment by Articuno** [comment]
Jest jeszcze jeden problem - boss nie resetuje się poprawnie po wipe, szczególnie jeśli wipe jest spowodowany wejściem do lawy. Wczoraj musieliśmy czekać około 8 minut zanim mogliśmy wejść z powrotem do FL. Cztery razy wipnęliśmy i 4 razy był ten sam problem.

**Comment by Tomciu** [comment]
Coś nie tak na nogach...

**Comment by mati865** [comment]
Teraz podczas walki sa 3 targety: Right Leg, Lord Rhyolith, Left Leg. Maybe you focussed Lord instead of his leg?
We had no problems turning him into volcano.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4978

**Comment by Respect69** [comment]
Już da się go zabić, ale opornie te nogi skręcają. Po tupnięciu jest coś takiego, że mimo nabitego paska np. na prawo, skręca gwałtownie w lewo i dopiero później idzie we właściwym kierunku.

**Comment by Quban** [comment]
> skręca gwałtownie w lewo

odwraca sie w strone jakiegos gracza pewnie nie wiem wlasnie czemu :D ale kierunku nie zmienia ;p

**Comment by mati865** [comment]
To tylko visual bo shredy wtedy normalnie wchodzą.

**Comment by Respect69** [comment]
Niby visual, ale po normalnie zalicza lave po tym skręcie, więc jednak coś jest na rzeczy :D

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4982
