### ISSUE TITLE
[EN][ITEM] Crashin' Thrashin' Robot

### ISSUE THREAD

**Issue by nveri** [Atlantiss/BugTracker#7175]
http://www.wowhead.com/item=23767/crashin-thrashin-robot#comments

this item should last 3 min. can you please adjust ?

**Comment by 1Andas** [comment]
If you are annoyed by the sound they make when people put them in banks/AHs, you can use steam tonk to shoot them and destroy them. :P

**Comment by nveri** [comment]
i am not. i am annoyed by buggers.

**Comment by nveri** [comment]
bump kurwa mac. pizdy nadal buguja.

**Comment by krecik88** [comment]
fixed in 5266
