### ISSUE TITLE
[EN][Raid] No loot in FL trash

### ISSUE THREAD

**Issue by Zandark** [Atlantiss/BugTracker#7178]
Hi ! I've done 7 FL trash, 3 as Loot Master, and when i was in the party, no item were dropped.
I think it's a bit strange because a friend did a few without me and always found item dropped. Someone else told me it also happens to him.
Maybe it's only low drops rate, but if there's something to do, tell me. Thanks.

**Comment by Bildo** [comment]
It's just a low drop rate
