### ISSUE TITLE
[PL][Quest][Anvilmar the Hero]

### ISSUE THREAD

**Issue by qndziu** [Atlantiss/BugTracker#7182]
NPC Thargas Anvilmar nie przyjmuje questa. Widać na minimapie znak zapytania jednak kiedy chcę oddać quest nie można z nim wejść w żadną interakcję http://www.wowhead.com/quest=26327/anvilmar-the-hero

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3925
