### ISSUE TITLE
[EN] [LK Quest] Abduction

### ISSUE THREAD

**Issue by Rosexephon** [Atlantiss/BugTracker#7183]
This quest is still bugged, all the Beryl Soccer's have all been captured and do not despawn nor respawn, as they should.

**Comment by Aival94** [comment]
Bump.Quest is bugged as all [Beryl Sorcerer](http://www.wowhead.com/npc=25316/beryl-sorcerer) are [Captured Beryl Sorcerer](http://www.wowhead.com/npc=25474/captured-beryl-sorcerer) and they do not despawn so they will become again [Beryl Sorcerer](http://www.wowhead.com/npc=25316/beryl-sorcerer)

Wowhead Link: [Abduction](http://www.wowhead.com/quest=11590/abduction)
How it should work: [Abduction](https://www.youtube.com/watch?v=UMLZt759z3U)

**Comment by Cellhawk** [comment]
https://github.com/Atlantiss/BugTracker/issues/4651
