### ISSUE TITLE
[EN][Spell][PALADIN] REPENTANCE DOESNT BREAK ON OTHER CLASSES DOTS

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#7184]
REPENTANCE SHOULD ONLY NOT GET DISPELLED FROM PALADIN SEAL OF TRUTH DOT FROM ALL OTHER CLASSES IT SHOULD INSTANTLY GET REMOVED ON DMG TICK.

**Comment by mati865** [comment]
MOAR CAPS PLEASE

**Comment by Zhalox123** [comment]
Ye figured out after i ended writing hahah :D

**Comment by mati865** [comment]
Ok then maybe some proofs would be usefull?

> Puts the enemy target in a state of meditation, incapacitating them for up to 1 min. Any damage from sources other than Censure will awaken the target. Usable against Demons, Dragonkin, Giants, Humanoids and Undead.
http://cata.openwow.com/spell=20066


> Repentance is being buffed in 4.2 to a 30 yard range, however it still breaks on all damage except Censure.
http://www.wowhead.com/spell=20066/repentance#comments:id=1424141

**Comment by TranceAccount** [comment]
Could you remove the caps, and make a normal report? Thanks in advance.
