### ISSUE TITLE
Heroic:Nefarian

### ISSUE THREAD

**Issue by Snyffz** [Atlantiss/BugTracker#7185]
So as we killed Nefarian on heroic difficulty 8 out of 10 people did get kill credit, the ones that didn't get it were me and the add tank (we were all the way across the room dealing with adds) are there any chances that we could get the credit?Also nobody died during the encounter so the issue wasn't the release.
 Evidence: Here's the kill video.
                  If needed could even send an SS of it
                  10 people that were in raid

https://www.youtube.com/watch?v=_irq_OhWWiY&feature=youtu.be

Character name :Sniffië

**Comment by user1011** [comment]
https://github.com/Atlantiss/BugTracker 
I think this belongs in an in-game ticket.

**Comment by Snyffz** [comment]
I did that and they told me to post it on Bugtracker.

**Comment by xolon** [comment]
it doesn't have to do anything with nefarian its core problem, achievements/loot should be instance wide and on atlantiss they are not, i remb ats had an update with this but they reverted it cause of some server problems.

**Comment by Bildo** [comment]
bt rules
