### ISSUE TITLE
[PL][Spellbook] brak profesji i problem z tekstura

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#7188]
![wowscrnshot_041516_110854](https://cloud.githubusercontent.com/assets/18480484/14580638/39686ef8-03d4-11e6-9ad4-2c3498129321.jpg)
Witam, na postaci w zakładce "professions" nie widać mojego nauczonego gotowania, archeologii, łowiectwa oraz zielarstwa (które mam 525/525 - zbieram normalnie kwiatki). Skutkiem tego, jak widać na screenie, nie mogę sobie umiejętności przenieść na pasek, a co gorsza, skillowac pozostałych profesji. W dodatku z alchemii mam Transmute Master, nie Potion. Bardzo uciążliwy bug dla mnie. Proszę o naprawienie problemu. 
Pozdrawiam, Aujourdhui

**Comment by whiskass** [comment]
DOdam, że nie otrzymałam odpowiedzi na ticket, dlatego zdecydowałam się na bugtracker.

**Comment by Jenovas** [comment]
Proszę wyłączyć wszystkie addony i wyczyścić Cache, oraz zapisz sobie plik WTF a w plikach WoWa wyczyść.

**Comment by pepe19** [comment]
mi logout pomogl

**Comment by whiskass** [comment]
Nie pomogło, na pozostałych postaciach wszystko jest w porządku.

**Comment by whiskass** [comment]
Proszę o zainteresowanie się problemem, z którym borykam się od przeszło miesiąca, a 3-krotne podążenie za instrukcją Jenovas'a nie pomogło...

**Comment by Jenovas** [comment]
Proszę sprawdzić na innym komputerze jeżeli nic nie pomoże, proszę napisać ticket ingame że profesje Ci się zbugowały.
