### ISSUE TITLE
[EN][PL][Quest][The Blood Furnace] The Breaker

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#7190]
**[EN]**
Quest: http://wow.gamepedia.com/Quest:The_Breaker

Upon completing quest Alliance players receive reputation with Thrallmar.
They should receive 350 reputation for Honor Hold (before any bonuses).

---

**[PL]**
Quest: http://wow.gamepedia.com/Quest:The_Breaker

Po wykonaniu zadania, gracze Przymierza otrzymują reputację u Thrallmar.
Powinni otrzymywać 350 reputacji u Honor Hold (przed jakimikolwiek bonusami).

![clipboard01](https://cloud.githubusercontent.com/assets/7345784/14583142/0cf623c0-0419-11e6-873e-8dc26ae89c94.jpg)

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11476-questthe-blood-furnace-the-breaker/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
