### ISSUE TITLE
[PL][Raid] Majordomo

### ISSUE THREAD

**Issue by nouron93** [Atlantiss/BugTracker#7192]
Miała miejsce taka sytuacja:
https://www.youtube.com/watch?v=9VpcvNS-ooc&feature=youtu.be
Na poprzednim id tez byla taka sytuacja tylko ze na starcie walki zaraz po tym jak z czlowieka wszedl w forme kota

**Comment by Quban** [comment]
xD ok przyglądne się temu

**Comment by Quban** [comment]
ok poprawione :dancer:

**Comment by Respect69** [comment]
To przy okazji zerknij na lorda, bo stacki z tych wulkanów nabijają się graczom randomowo :D Nawet jak stoisz kilometr od niego xD

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4982
