### ISSUE TITLE
[Quest][TBC] Teron Gorefiend, I am... 

### ISSUE THREAD

**Issue by AteneNieOficer** [Atlantiss/BugTracker#7194]
Quest dont spawn mob.
Should work like this:https://www.youtube.com/watch?v=38rpK8O7xpY
Here is the wowhead: http://www.wowhead.com/quest=10639/teron-gorefiend-i-am

**Comment by krecik88** [comment]
please fix title accorind to BT rules

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/5376
