### ISSUE TITLE
[EN][NPC] Shadow revenant missing

### ISSUE THREAD

**Issue by Kikuv4e** [Atlantiss/BugTracker#7195]
Hello,

This npc http://www.wowhead.com/npc=30872/shadow-revenant is missing, if you could please add this npc at wintegrasp would be fine.

**Comment by RandomPickNewb** [comment]
Are you sure that your faction was controlling wintergrasp since they are only visible to the faction that controls wintergrasp ?

**Comment by Kikuv4e** [comment]
Oh shit, i am not sure about that, fuck. I am sorry

**Comment by TranceAccount** [comment]
Please confirm.
