### ISSUE TITLE
[EN][Item] Free Action Potion

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7196]
http://www.wowhead.com/item=5634/free-action-potion#comments

On every level above 77 this potion time should be reduced by 3 seconds.
78 - 27s uptime
79 - 24s uptime
80 - 21s uptime
81 - 18s uptime
82 - 15s uptime
83 - 12s uptime
84 - 9s uptime
85 - 6s uptime

Currently on every level mentioned above it has full 30 second duration, its kinda high prio since ppl abuse this in bgs and they will prolly abuse it in future rated bgs.

**Comment by phifedawg** [comment]
you can't use items as potions in rbgs afaik, but yeah this has high prio for normal bgs

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4984
