### ISSUE TITLE
[EN] Can´t finish the quests

### ISSUE THREAD

**Issue by UrWetDream** [Atlantiss/BugTracker#7199]
Hi. when i try to finish a quest (for example kill something), and i kill it... Its like i never kill it..
Someone help me?

**Comment by Luna-maria** [comment]
you're gonna have to be more specific on which quests it's about or they'll just close it. Generally though, have you tried relogging/retaking the quests?

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.
