### ISSUE TITLE
[EN][Raid][Firelands][NPC][Lord Rhyolith]

### ISSUE THREAD

**Issue by EnPra** [Atlantiss/BugTracker#7200]
After wiping on Rhyolith we cannot enter the instance again as it states that there is an encounter in progress. There seem to be a lot of other players not able to enter as well. Also Rhyolith's speed seems to vary with each try, and active volcanoes don't stay up as long as they should.
![buglantis r](https://cloud.githubusercontent.com/assets/17710214/14589614/8fa0b4b6-04e6-11e6-8e5f-6f3050ddf871.jpg)

**Comment by jissabraham** [comment]
may be some 1 used banner during fight. banner can bug dungeons u wont be able to enter until the banner is gone

**Comment by Illusie** [comment]
we wiped on Ryholith too.
He get "Superheated" on Normal.

And he bugs so much we cant drive him.
and many other issues with him.

should be fixed.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4982
