### ISSUE TITLE
[PL][RAID][Firelands] Rhyolith - wulkany

### ISSUE THREAD

**Issue by astale** [Atlantiss/BugTracker#7201]
Stacki od wulkanow nabijają się nieprawidłowo. Jedyne co udało mi się znaleźć z guideow/innych patchy:
http://www.wowdb.com/spells/98492-eruption
http://www.icy-veins.com/wow/lord-rhyolith-strategy-guide-normal-heroic
Może ktoś inyn jest lepszy w szukaniu tego wszystkiego i może lepiej opisac.

Dzisiaj nawet mialem przypadek gdzie na jednej osobie były 4 osobne stacki na laczna sume 31 stackow... Wg powyższego powinien być 1 stack na max 20, do tego tylko z aktywnych wulkanow na 3 osoby losowe na 10, 6 na 25. U nas chyba jest na wszystkich osobach w jakiejś odleglosci od wulkanow bo da się uciec...

Do tego po nadpnieciu crater jest targetowalny, ma 1 hp i można zbic żeby nie było magma flow.

**Comment by Hexenbane89** [comment]
Potwierdzam, Cratery mozna zbić mają 420 HP i Boss nakłada stacki na kogo mu się żywnie podoba, nie mówiąc o tym że sterowanie nogami to jakaś masakra.

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/6031
