### ISSUE TITLE
Moonstone Propaganda quest bugged

### ISSUE THREAD

**Issue by xalana** [Atlantiss/BugTracker#7206]
The informational panphlet is bugged and we can't get it

**Comment by krecik88** [comment]
Fix title, add wowhead links.

**Comment by Larousene** [comment]
Do You mean this quest: http://www.wowhead.com/quest=26295/propaganda?
All quest items are obtainable. Informational Pamphlet and Mysterious Propaganda are in first building on the left, Secret Journal is in first building on the right, upstairs.

**Comment by Bildo** [comment]
bt rules
