### ISSUE TITLE
[EN][Warlock] Soul Link - Hellfire, Crowd Control damage threshoot.

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7209]
1.Hellfire doesn't damage the pet through Soul Link, which was mostly used to break hunter's traps, Dragon's Breaths on warlock's pets in PvP scenario.
http://us.battle.net/wow/en/forum/topic/3123368452

2.Damage done to pet via Soul Link isn't considered in Crowd Control Damage threshold to break any type of CC. For example it was impossible to Dragon's Breath both pet and a warlock since the Soul Link would break Dragon's Breath from it's own damage.
http://us.battle.net/wow/en/forum/topic/3229385418
"Anyone else notice that Dragon's Breath will always, without fail, break on felhunters within the first half a second? No, it's not demonic empowerment. It occurs multiple times per minute."

3.Damage done by Soul Link should be done by a Warlock, currently it's done by our enemies that hit us. I have no idea if this currently has any impact on game mechanic, but this is probably linked with Hand of Sacrifice and latest fix to Rage generation and other procs on targets afffected by such spells. 
http://eu.battle.net/wow/en/forum/topic/1622898049
http://www.worldoflogs.com/reports/rt-dr9memg4t503t0nw/analyze/ff/source/

4.Damage done via Soul Link after fixing issue number 3 should Heal Warlock through Fel Armor 
http://us.battle.net/wow/en/forum/topic/3123368452

http://www.wowhead.com/spell=1949/hellfire
http://www.wowhead.com/spell=108415/soul-link
http://wowwiki.wikia.com/wiki/Fel_Synergy
http://www.wowhead.com/spell=44520/fel-armor
http://www.wowhead.com/spell=6940/blessing-of-sacrifice

**Comment by blinkmaster** [comment]
Damage from soul link was delayed on retail. So i guess it wont be fixed here

**Comment by kadi2** [comment]
@blinkmaster Probably it's going to break instantly when Damage threshoot to CC would be fixed.

**Comment by fruvel** [comment]
they never repair any warlock bug-- look at pets they are mostly bugged and usefull in game.... WAKE UP DEVS

**Comment by Fearyourself** [comment]
Considering the fact that warlocks are the least played class on all of world of warcraft (here on atlantiss too) I kinda get why warlocks have been given this little attention. That being said I fully understand that some mechanics can be more difficult than others, but I fail to see why you wouldn't care equally much for all the classes. I mean one of the reasons warlocks not being played by many players is the complexity of the class (correct me if I'm wrong) and the fact that it's a weak class and with all these minor things not working correctly just making them a fair deal weaker in comparison to other casters say mages/priests etc... I don't mean to complain, I love the stuff the developers do, but this is just unbelieveable

**Comment by Fearyourself** [comment]
No love.. @Jenovas

**Comment by Fearyourself** [comment]
@lamaATS <3 :(

**Comment by lamaATS** [comment]
Fixed in rev. 5254, only not working with Dragon's Breath
