### ISSUE TITLE
[EN] [Profession] No alchemy 80 stat bonus on flasks.

### ISSUE THREAD

**Issue by matus3** [Atlantiss/BugTracker#7211]
Alchemist that can create flask should recive bonus from Mixology (bonus time and stats) when he uses one. Now he only recives bonus one hour but still 300 agi/spirit/str instead of 380.

**Comment by kadi2** [comment]
"Alchemist that can create flask should recive bonus from Mixology (bonus time and stats)"
It's more like Alchemist should recive only the bonusses only when he knows the recipe for specific Flask, potion, elixir.

**Comment by matus3** [comment]
Oh come on... That is the same what i have just said. I am 525 alchemist and u think i have no recipes for flasks that are taught by alchemy trainer ? BTW it's not only me cause noone recives this bonus (talked to 3 guild members with full alchemy).

**Comment by xolon** [comment]
i don't have alchemy myself, but i have seen a lot of ppl with +80 stat buffs

**Comment by kadi2** [comment]
@matus3 Ya, but i just felt like it wouldn't be clear enough for a person that doesn't know about this mechanic :D

**Comment by matus3** [comment]
"i don't have alchemy myself, but i have seen a lot of ppl with +80 stat buffs"
80 stat buff is from flask of enhancment which is alchemist only flask and it works but alchemist should recive 380 stat instead of 300 from normal cata flask available for everyone(ofc if he can make it)

**Comment by Glare** [comment]
Have you actually checked stats. I doubt it was ever displayed on flask buff itself on Atlantiss. It might as well just be a visual bug.

**Comment by Kaldros** [comment]
I call bullshit on this one.

If you know the recipe and use the flask u will get ~80 more stats from the flask than what it says on the tooltip (e.g. 380 agility instead of 300). Just instead of looking at the tooltip, calculate the difference in the stat that the flask gives before and after drinking it.

Mixology works.

**Comment by Lanrutcon** [comment]
It's working: http://imgur.com/a/tYTxI
3537 - 3517 = 380 STR (= 300 Flask + 80 Bonus)

**Comment by matus3** [comment]
Ok fine i see now wrong calculations sorry
