### ISSUE TITLE
quests

### ISSUE THREAD

**Issue by ojtak** [Atlantiss/BugTracker#7212]
Witam,
Chciałem zgłosić problem z dwoma questami:
1. Into the fire   (http://www.wowhead.com/quest=29206/into-the-fire)
2. the forlorn spire (http://www.wowhead.com/quest=29205/the-forlorn-spire).
W obu przypadkach q jest dostępny tylko i wyłącznie po restarcie serwera (czyli można go zrobić raz na 1-2 dni).
Zwracam się z prośbą o naprawienie ww questów.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Hello!
i would like inform that i have problem with two quest:
1. Into the fire   (http://www.wowhead.com/quest=29206/into-the-fire)
2. the forlorn spire (http://www.wowhead.com/quest=29205/the-forlorn-spire).
First and second q are available only after restart server, it is very problematic :/

Please repair quests

**Comment by Quban** [comment]
Przecież jest napisane w changelogu że reset został poprawiony by wolf

**Comment by ojtak** [comment]
ok nie widziałem tego. dzięki za informacje

**Comment by ojtak** [comment]
Witam ponownie,
czy można wiedzieć co jaki czas da się zrobić ww questy?? Dziś czekałem od 9.30 do 12 aby zrobić the forlorn spire  i ani razu q nie zadziałał :/
