### ISSUE TITLE
[PL]Dodge i Parry

### ISSUE THREAD

**Issue by maserion** [Atlantiss/BugTracker#7214]
Wg wowwiki/wowpedii base chance na dodge i parry dla tanków wynosi 5%. Jak widać na naszym serwerze zgadza się to - http://i.imgur.com/8lgCnsl.png .
Po ubraniu itemów spotykamy następujący problem - http://i.imgur.com/JwvYeJz.png (parry) i http://i.imgur.com/LYGZ4qi.png (dodge). Po dodaniu dodge z parry ratingu 11,80% i 5% base powinniśmy otrzymać parry na poziomie 16,80% (przed DR) a nie 15,39%. Tak samo sprawa ma się z dodge - powinno być 5% (base) + 6,71% (dodge rating) = 11,71% (przed DR) a nie 11,34%.
http://wow.gamepedia.com/Parry 
http://wow.gamepedia.com/Dodge - Cataclysm Patch 4.2.0 (2011-06-28): Death Knights, Paladins, and Warriors no longer receive any bonus to their chance to dodge from Agility. Their base chance to dodge is now a fixed 5%.

**Comment by Jenovas** [comment]
Jak sam napisałeś PRZED DR, czyli potem wchodzi DR, obniża wartość w zależności od DR i pokazuje prawidłową wartość już po DR w karcie postaci.

**Comment by mati865** [comment]
@Jenovas ma rację. Ręcznie liczyłem i parry się zgadza.

**Comment by maserion** [comment]
niech pokazuje przed DR tak jak jest napisane w tooltipie

**Comment by mati865** [comment]
To byłoby bez sensu. Wszelkie addony/macra bazują na wartości po DR.
