### ISSUE TITLE
[EN][Quest/Npc][Shaddowmoon valley][Seek out Neltharaku]

### ISSUE THREAD

**Issue by basjes93** [Atlantiss/BugTracker#7215]
When you start he quest "Seek out Neltharaku" the NPC to complete the quest doenst appear. This makes it impossible the start the quest chain for the nether drake mounts.

http://wowwiki.wikia.com/wiki/Quest:Seek_Out_Neltharaku

Please repair this.

**Comment by Lidless** [comment]
I did it 3 weeks ago. Neltharaku is flying high above so you have to do some circles on the sky to find him. Ofc it may be bugged now.

**Comment by basjes93** [comment]
Thanks i didnt search far enough. Quest isnt bugged :)
