### ISSUE TITLE
[EN][Raid][Heroic Firelands]

### ISSUE THREAD

**Issue by jas0nkat** [Atlantiss/BugTracker#7219]
Baleroc:
-savage defense (druid mastery) is not increased by The Blaze of Glory
-countdown interrupts spellcasting

Majordomo Fandral Staghelm:
-adds on cat phase chose their targets immediately after spawning (no chance for tank to pick them up that quick, sometimes oneshotting melee players)
-burning orbs on second cat phase didn't spawn at all

Shannox (what we've experienced from our raid 2 weeks ago):
-Rageface can be kited all the time which makes this fight extremely trivial (not 100% sure, but i think it should not be possible to slow him that much.

Ragnaros:
-should not be accessible without defeating all of the previous bosses on heroic, now he is. (but for testing it's cool)
-i'll post more stuff from Rag after we'll make some more tries, just had enough time for 2 pulls, phase one looks fine (more feedback after next raid)

Special thanks to Quban for fixing our lockout :) 
Looking forward for more heroic testing :)

**Comment by Bildo** [comment]
While you're testing please take a look at hp.

**Comment by jas0nkat** [comment]
Baleroc, majordomo and rag were ok with their prenerf hp. Will check the rest next time.

**Comment by linesar** [comment]
Is ragnaros heroic even out on ptr?

**Comment by jas0nkat** [comment]
Yep, dunno how well scripted he is since we just got to the first transition but traps hit like a fucking truck and we got debuff from them, so yup, first phase is definetly heroic.
