### ISSUE TITLE
[PL] [Raid] [Firelands] - Ragnaros Meteor

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7220]
Meteory na Ragnarosie są kompletnie pobugowane. Po uderzeniu meteora powinien on zostać odrzucony, zatrzymać się na chwile w miejscu i obrać nowy target. U nas uderzony meteor od razu obiera nowy target i zaczyna toczyć się w przeciwnym do targetu kierunku, utrzymując ten tor ruchu przez jakieś 5 sekund i dopiero wtedy podąża za swoim targetem, co znacząco ogranicza możliwość sterowania meteorami. 

Tak to powinno działać: https://youtu.be/8tMRMG7KOTQ?t=8m51s

**Comment by Quban** [comment]
wynikalo to z uzycia zlej funkcji, zostalo poprawione w http://atlantiss.eu/changelog#rev4988

**Comment by Aival94** [comment]
Is not this one fixed?
We did not have any problems last time we did ragnaros.
