### ISSUE TITLE
[EN][SPELL][WARRIOR] Sunder Armor

### ISSUE THREAD

**Issue by mati865** [Atlantiss/BugTracker#7222]
Currently when one Warrior stack Sunder Armor (using Sunder Armor, Glyph of Colossus Smash, Glyph of Heroic Throw or Devastate) and another warrior use skill applying Sunder Armor stacks are reset. So when there are more than two Warriors in raid most of time there will be only one stack of SA because they will reset stacks applied by each other.
When second Warrior use SA stacks should be added instead of replacing.

For referecnce: this issue was fixed on Sunwell and should be fixed in SunwellCORE.

Providing Wiki links because wowhead pages were removed 
http://wow.gamepedia.com/Glyph_of_Colossus_Smash        id:63481
http://wow.gamepedia.com/Glyph_of_Heroic_Throw             id:43418
http://wow.gamepedia.com/Sunder_Armor                            id: 7386
http://www.wowhead.com/spell=20243/devastate                  id:20243

**Comment by gumby123** [comment]
Can confirm, very annoying in raid. When you have 2 warrior tanks in a raid, like on Magmaw, one warrior has to stop using his main ability - Devastate. This is a dps loss and very annoying.

**Comment by mati865** [comment]
Issue still persists.

**Comment by roesiran** [comment]
Can u fix this, warriors are unplayable.

**Comment by Piklo** [comment]
should be fixed in [rev5745](https://atlantiss.eu/changelog#rev5745)
