### ISSUE TITLE
[EN][Instance] HC COS

### ISSUE THREAD

**Issue by celtic660** [Atlantiss/BugTracker#7225]
It seems like the script of The culling of Stratholme (Heroic) stops midway after defeating Malganis. I double checked to confirm this and even contacted a GM through a ticket to which he said it was bugged. So basically due to the script stopping. I am unable to loot the chest for the rewards you earn after defeating Malganis. I really want that shield (Royal Crest of Lordaeron) for xmog xD. I hope this gets fixed soon. :)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5052
Related: https://github.com/Atlantiss/BugTracker/issues/2551
