### ISSUE TITLE
[EN][QUEST][Silvermoon City] - "Meet with Shadow-Walker Zuru"

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#7227]
This quest: http://www.wowhead.com/quest=28309/meet-with-shadow-walker-zuru
This NPC in Silvermoon gives it: http://www.wowhead.com/npc=16658/aldrae

Currently I can see this quest and choose to accept it on my warlock. It is a Troll Priest only breadcrumb quest.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11589-7227questsilvermoon-city-meet-with-shadow-walker-zuru/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
