### ISSUE TITLE
[EN][Quest][Free Our Sisters]

### ISSUE THREAD

**Issue by Larousene** [Atlantiss/BugTracker#7228]
Quest from Stonetalon Mountains: I've obtained keys to open the cages, but all cages are already open. I can't complete that and take another quests.

**Comment by 1Andas** [comment]
Confirmed. It's like this for a while now.
Also this has been reported already #2518 
It's advised to first search bugtracker before posting. :)

**Comment by Snake90** [comment]
Still bugged.

**Comment by Jevsevije** [comment]
Bugged!
