### ISSUE TITLE
[EN][Item] Synapse Springs

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7230]
Synapse Springs cant be use with pvp trinket Badge of Victory.
Normaly you should use enchant from gloves and Trinket in the same time.

**Comment by blinkmaster** [comment]
Invalid report. Using both synapses and on use trink was fixed by blizz around 4.1 or even earlier

**Comment by aneq** [comment]
this is correct behaviour, it shouldnt be used at the same time
