### ISSUE TITLE
[PL][Core] Raid Finder

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7231]
Nie działa u nas Raid Finder.
Ale jest rozwiązanie SunwellCore ^^, na Sunwellu to działało, można było zrobić rajd i był widoczny w wyszukiwarce rajdów można było tez zobaczyć kto jest już w nim i jego ilvl.
Wiem że nie jest to najistotniejsza rzecz ale zmniejszyło by to ilość spamu na Word/PL a skrypt może był by łatwy do zaimplementowania na Atlantisie z SunwellCora.

**Comment by Aival94** [comment]
Raid finder was introduced during 4.3 content so they will implement it when they release 4.3 content.

**Comment by aneq** [comment]
Ludzie z sunwella powinny być prewencyjnie zbanowani z bugtrackera. Jakbyś miał jakiekolwiek pojęcie czym jest raid finder i lfr to byś wiedział, że na 4.3 stary raidfinder został usunięty. Więc portowanie raid findera nie ma absolutnie żadnego sensu,
