### ISSUE TITLE
[PL][Core] Extend Raid Lock

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7232]
Nie działa u nas przedłużenie ID, a jest to dość przydatna opcja jak gildie chcą np. progresować tylko Ragnarosa i przedłużają ID gdzie mają ubite wszystkie Bossy bez Ragnarosa.
Podobnie jak z Raid Finderem jest to teź w SunwellCore o ile jest to łatwe do "wyciągnięcia" ;>.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4438
