### ISSUE TITLE
[EN][Quest][Unfamiliar Waters]

### ISSUE THREAD

**Issue by stef599** [Atlantiss/BugTracker#7233]
Quest from Orgrimmar from Warchief's Command Board is bugged, NPC [Herezgor Flametusk] dont give u item needed to complete it. This quest is part of Twilight Highlands q chain and u cant get there by portal bcs of this bug .

**Comment by Aival94** [comment]
reported:/related: https://github.com/Atlantiss/BugTracker/issues/5406
