### ISSUE TITLE
[PL][SPELL] Death Strike

### ISSUE THREAD

**Issue by TheDirtu** [Atlantiss/BugTracker#7239]
Witam! Zauwazylem ze Death Strike nie dziala prawidlowo poniewaz niezaleznie od ilosci otrzymanych obrazen zawsze leczy za minimlana wartosc HP tj.7% pociagajac za soba blood shielda (=za slaba banka).
Porosil bym aby administracja sie tym zajela.
Pozdrawiam!

**Comment by BialyADI** [comment]
A m isie wydaje ze cos jest nei tak z dmg Death strika, bo bije w po 100k czasem serio ;D.

**Comment by kadi2** [comment]
> Ludzie z sunwella powinni być prewencyjnie zbanowani z bugtrackera. Zaśmiecacie tylko bugtracker reportami które prawie nigdy nie są prawdziwe.

Aneq Max Kolonko mowi jak jest.

**Comment by TheDirtu** [comment]
syneczku jak narazie to Ty tu offtopujesz wiec czekam az sie wypowie jakis gm albo ktokolwiek kto ma cos sensownego do powiedzenia a nie jakisz plebejusz tWOJEGO pokroju
;)

**Comment by BialyADI** [comment]
No dobrze mu powiedziałeś Dirtu!

**Comment by TheDirtu** [comment]
Adi dmg jest wlasciwy poniewaz DS to 330% dmg broni do tego dolicz np.ok 30k AP ktore dostajesz z venege

**Comment by aneq** [comment]
A liczyłeś to chociaż? bo już było miliard takich zgłoszeń i zawsze się okazywało, że DS działa dobrze. Ściągnij sobie jakikolwiek blood shield tracker to zobaczysz kiedy leczy za więcej. Nie dałeś nawet żadnych dowodów., że działa źle.

**Comment by TheDirtu** [comment]
chlopie zobacz co ty piszesz nie gemuje sie w stame ale masterka nie ma  tutaj nic zwiazanego z leczniem :D wplywa tylko na blod shield (absorb) tu nie ma co liczyc jak leczy nons top za 7% liczyc to mozesz jaki masz absorb ale to juz dziala od mastery a tu dziala wlasciwie mastery chodzi  mi os am skil jako DS

**Comment by pelekon** [comment]
Co nie zmienia faktu, że nie dałeś na to żadnych dowodów w postaci ss-ów itp

**Comment by TheDirtu** [comment]
ciezko dac na to dowody bo dzieje sie to bardzo szybko wiec nie moge tego bezposrednio zarejestrowac a zaden blod shield tracker nie dziala mi na tym serwerze i sam nie wiem od czego to jest zalezne

**Comment by aneq** [comment]
DocsDebugRunes działa, polecam ten addon
poza tym wystarczy sprawdzić w recouncie ile wynosi największy healing z death strike, możesz to zrobić bardzo łatwo po walce

**Comment by TheDirtu** [comment]
sprawdzilem max heal z ds mam za 27k a max banke mam max za 20k wiec gdzie jest moje 140% mastery? i tak anwet gdybym to uduwodnil administracjia nie skrzywi palcem ;)

**Comment by Kiperr** [comment]
Ale nigdzie nie przedstawiłeś wiarygodnych dowodów na poparcie swojej tezy dlatego temat został zamknięty.

**Comment by aneq** [comment]
recount inaczej liczy absorby geniuszu, (absorb jest liczony gdy jest skonsumowany a nie gdy sie pojawia) czyli pewnie zszedł ci sam.  Poza tym ty zgłaszałeś heal z DSa a nie mastery. 
Ponawiam prośbę o zbanowanie sunwellowców z bugtrackera

**Comment by TheDirtu** [comment]
naprawde jestes smieszny chlopie nie jestem z sunwela a ty sie upierasz sunwel i sunwel o co ci chodzi przyczpiles sie jak mucha do gowna polecam jakas terapie na nerwice natrectw albo cokolwiek na uspokojenie moze zacznij od melisy

**Comment by Jenovas** [comment]
TheDirtu - Twoje posty nie na temat i posty atakujące administracje zostały usunięte, wpierw dowiedz się jak działają Twoje spelle, bo nawet podstaw nie znasz, a potem zgłaszaj bugi. I prosiłbym o powstrzymanie się przed dalszymi atakami w stronę innych graczy i administracji.
