### ISSUE TITLE
[PL][Warlock] Health Funnel leczy za LoSem.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7242]
Jak jest: Health Funnel można zacząć castować gdy nasz Pet jest za tekstura i go nie widzimy.

Jak powinno być: Nie powinno się dać zacząć leczyć Peta gdy jest za Losem. Podobny bug jak kiedyś z Hunterem i Master Callem.

**Comment by Fearyourself** [comment]
You have always been able to cast health funnel when your minion is in texture and it should heal too, but you can't cast health funnel while the minion is in line of sight.

Here you go reporting shit that works perfectly again

**Comment by BialyADI** [comment]
Dokładnie, u nasz minion jest line of sight, a my możemy zacząć go leczyć, jest lipa.

**Comment by Fearyourself** [comment]
I meant we can't cast health funnel when the minion is not in line of sight. That's why you macro health funnel to petfollow. Dude it's working correctly lol

**Comment by BialyADI** [comment]
Allmoust Correctly xD.

**Comment by BialyADI** [comment]
bump

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by BialyADI** [comment]
Jest już naprawione.
