### ISSUE TITLE
[PL][Mage] DR Deep Freeze z Ring of Frost.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7243]
Jak jest:
Nie działa DR DF z RoF, buguje się to gdy damy najpierw Deepa na przeciwnika a potem Ring of Frost, taką zależność zauważyłem i potem na danym przeciwniku ta DR'ka do końca Areny/Duela/BG jest popsuta.
Jeśli damy najpierw RoF a potem Deepa to jest wszystko ok Stun od Deepa ma 2,5s.

Jak powinno być: DR Deep Freeze z Ring of Frost powinien działać poprawnie nie zależnie od kolejności CC.

**Comment by BialyADI** [comment]
Ajj, przetestowałem to jeszcze raz na Magu kumpla dla pewności, i DR działa tylko RAZ i koniec.
Kolejność jednak nie ma znaczenia, po jednokrotnej DR'ce DF i RoF na przeciwniku DR'ka juz się nei powtórzy do końca Areny/Duela/BG lub wylogowania przeciwnika na którym DR'ka wystąpiła.

**Comment by BialyADI** [comment]
bump jest tu ktos ^^ ?

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by BialyADI** [comment]
Bump.

**Comment by BialyADI** [comment]
Bump. @lamaATS C++ Master look on this ;x.

**Comment by lamaATS** [comment]
Fixed in rev. 5252

**Comment by BialyADI** [comment]
@lamaATS 
Teraz DR, Ringu i Dragon Breath nie działa ;x.
Tutaj jest strona z DRkami: http://wowwiki.wikia.com/wiki/Diminishing_returns. 
[Ring of Frost] 	Yes 	8 	Yes 	8 	Disorient + Deep Freeze 
[Deep Freeze] 	Yes 	5 	Yes 	5 	Controlled Stun + Ring of Frost 
To jest ok teraz.

Ale Ring of Frost Podlega pod Disorient tak samo jak Dragon's Breath, Scatter Shot, Repentance, itd.
Teraz Mag Fire może zrobić kombo Ring/Breath i stoisz przez 8+5 sec podbonie jak to było z bugniętym Ring/DF
[Dragon's Breath] 	Yes 	5 	No 	5 	Disorient.

Reasumując Ring powinien mieć DR z Disorient Efektami jak miał + Deep Freez i tyle ^^.

**Comment by kadi2** [comment]
Dragon's Breath mial odzielny DR na cata i dzialal tak od poczatku serwera i tyle ^^.

**Comment by BialyADI** [comment]
No to źle, dla dowodu można znaleść to na jakimś filmiku.

**Comment by kadi2** [comment]
Pewnie, ze mozna ale komus sie nie chcialo.

**Comment by BialyADI** [comment]
Ja jestem pewien swego nie od wczoraj gram w tą przeklętą grę ;D, a tabelka jest z Cata.

**Comment by kadi2** [comment]
!(https://s12.postimg.org/3pginucbh/New_Bitmap_Image_3.jpg)

**Comment by BialyADI** [comment]
Nom zbyt długo ale nic lepszego nie ma ^^.
Czyli chcesz powiedzieć Scatter i Breath to jak by oddzielna kategoria Disorientów?
Coś nie chce mi się w to wierzyć ale sprawdzę to jeszcze i doczytam tylko jutro raczej bo ciut późno ^^.

**Comment by BialyADI** [comment]
Dobra poprzeglądałem parę filmików i masz racje Breath nie ma DR z Disorientami takimi jak np. Ring itd, wszystko jest ok.
Kurde byłem pewien ze tak nie jest, widać WoW nadal zaskakuje. Przynajmniej tematu nie trzeba ponownie zamykać ^^.

**Comment by lamaATS** [comment]
Ja jestem szczęsiliwy że bugi same się naprawiają 💃
