### ISSUE TITLE
[PL][Quest] Into the Fire

### ISSUE THREAD

**Issue by Elannsi** [Atlantiss/BugTracker#7244]
Albo Windcaller spawni się 5 godzin albo podobno spada gdzies pod tekstury. Questa moge zrobic tylko po DC servera. Jest to bardzo wazny quest, niepoprawne jego dzialanie uniemozliwa zdobycie 10 dodatkowych marek dziennie. Proszę aby został on niezwłocznie naprawiony.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5661
