### ISSUE TITLE
[EN][Quest][Darkshore][The Bear's Blessing]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7245]
Hi :)

Problem with the quest  [The Bear's Blessing] in Darkshore : http://www.wowhead.com/quest=13544/the-bears-blessing

The NPS is friendly so I can't attack him to got its tailfeathers which is necessary to complete the quest.

Thanks for your help.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/2515

Try to relog to see if help and maybe update with a comment which animal blessing you had as it might be related.

**Comment by Snake90** [comment]
I abandoned the quest and I went to the NPC but it's still friendly and I have to kill its to get the tailfeathers ... So he must be neutral.

I also tried to do the quest without tailfeathers but when I go to the ancient bear statue it says "you need tailfeathers" ...

So the quest can't be completed.

**Comment by jackal86** [comment]
Still bug, the mob is still green and can't be attacked, so the quest is still uncompletable.
I had the Stag blessing on.

**Comment by eline328** [comment]
Still bugged....when will this be fixed?
