### ISSUE TITLE
[PL][Quest][Badlands] Lifting the Veil 

### ISSUE THREAD

**Issue by Xendernik** [Atlantiss/BugTracker#7248]
Misja jest niesprawna, nic nie dzieje się po jej wzięciu.  Part 2 of 6
[http://www.wowhead.com/quest=27770/lifting-the-veil](url)

**Comment by Kiperr** [comment]
Proszę, wszystkich którzy zgłaszają bugi aby najpierw zapoznali się z zasadami zgłaszań a nie jechali na pałe i nawet nie sprawdzili czy nie istnieje już takie samo zgłoszenie.
Duplikat #1632
