### ISSUE TITLE
[EN][Hunter] Flare vs. LoS

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7249]
If you cast flare and go out of los from it, it won't work.http://www.wowhead.com/spell=1543/flare

**Comment by blinkmaster** [comment]
Flare also works through los for example on blades edge arena bridge, detecting not only people on bridge but beneath too. Also works the other way around.

**Comment by BialyADI** [comment]
Many skills on Antalntiss work no matter Los or noLos, like mage Dragon Breath, Cone of Cold or Boomkin Typhoon.

**Comment by lamaATS** [comment]
Fixed in rev. 5501
