### ISSUE TITLE
[EN][Warlock] Unstable Affliction

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7252]
1.Dispell from UA doesn't recive bonus from Shadow Mastery as intendend.
My UA Tick = 2507
My UA Dispel damage = 23391

UA Tick on the movie = 2513
UA Dispel damage on the movie = 29678
https://www.youtube.com/watch?v=i1-ZQ81oFsY

> Patch 4.1.0 (26-Apr-2011): Unstable Affliction damage done when it is dispelled has been doubled, but this damage can no longer be critical. Damage dealt by Unstable Affliction when it is dispelled now properly benefits from Shadow Mastery.

2.Unstable Affliction Ignores resilience and lacks double damage increase from previous patches.

> Patch 4.1.0 (2011-04-26): Damage done when it is dispelled has been doubled, but this damage can no longer be critical.

Some people say it was bugged with resilience only when you tried to dispell UA from others till the hotfix that ofcourse should apply to our server.

> It's bugged, I think when you dispel it off others it ignores resilience.

http://www.wowhead.com/spell=30108/unstable-affliction
Shadow Mastery == 87339

**Comment by Fearyourself** [comment]
@lamaATS help :(

**Comment by kadi2** [comment]
It doesn't seem like the double damage buff has been kept to the end of the expanstion. Gonna collect some 4.3.4 footages.
https://youtu.be/-1kAdsDifW4?t=5m36s

**Comment by blinkmaster** [comment]
bump ninja

**Comment by blinkmaster** [comment]
bump

**Comment by lamaATS** [comment]
Fixed in rev. 5491

**Comment by blinkmaster** [comment]
thank u! hope so its gonna work good :)
