### ISSUE TITLE
[PL] HP Gryphon Mastera w SW.

### ISSUE THREAD

**Issue by ysiu15** [Atlantiss/BugTracker#7254]
HP tego NPC jest znacząco obniżone w stosunku do jego Hordowego odpowiednika. Tutaj SS
![wowscrnshot_042416_115538](https://cloud.githubusercontent.com/assets/11962388/14766740/6928afb2-0a15-11e6-8b64-23b643e1172b.jpg)
![wowscrnshot_042416_120007](https://cloud.githubusercontent.com/assets/11962388/14766741/69297b22-0a15-11e6-891a-44a832bc77b4.jpg)

Pozdrowienia dla WS :)

**Comment by TranceAccount** [comment]
This issue has been fixed, but the reason why it wasn't closed it because your title was WRONG.
