### ISSUE TITLE
[PL][QUEST]  [A Present for Lila]

### ISSUE THREAD

**Issue by Hexenbane89** [Atlantiss/BugTracker#7255]
Quest http://www.wowhead.com/quest=25154/a-present-for-lila nie działa po zrobieniu 3 gemów nie zalicza pierwszej części questu. tak jak na screenie:

http://i.imgur.com/9tqF1ao.jpg

**Comment by Aival94** [comment]
Just giving the horde link as well as this one is tha alliance one: [A Present for Lila](http://www.wowhead.com/quest=25160/a-present-for-lila)

**Comment by Hexenbane89** [comment]
Dobra zaliczyło w końcu.

**Comment by Porobiony** [comment]
Może byłeś w raidzie podczas robienia ich
