### ISSUE TITLE
[PL][Achivment][Respect your Elders]

### ISSUE THREAD

**Issue by sebcioch** [Atlantiss/BugTracker#7257]
Nie mozna zrobic tego achivmentu ponieważ nawet po oddzieleniu bossa od guardianow boss dalej jest immune na dmg.

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by Aival94** [comment]
Achievement is working just fine. When you move guardian away it remove the shield. I think this one should be closed.
