### ISSUE TITLE
[EN][Quest][Ashenvale][The Last Stand]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7259]
Hi :)

Problem with the quest [The Last Stand] in Ashenvale : http://www.wowhead.com/quest=13987/the-last-stand.

When I take the quest, nothing happens whereas normally full of "Demonic Invader" are supposed to appear.

So the quest can't be completed :/

Thanks for help

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/660

**Comment by Snake90** [comment]
I don't understand why you have closed this issue because the quest still doesn't work ... nothing happens while I take the quest ...

**Comment by Quban** [comment]
> Reported: #660

thats why
