### ISSUE TITLE
[EN][Core] Raid Loot System

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7260]
So you have 2 (10 man) 4-5(25 man) loot slots and on atlantiss they together have a same chance\* to drop items, which means that you will never see 2 or even 3 of the same items droping from a boss kill.
How it should work: Every loot slot should have its own chance (spinning wheel) to choose between all items.
Example: First item - Chance of Item1 Item2 Item3 Item4 Item5
               Second item - Chance of Item1 Item2 Item3 Item4 Item5
               ...
So there should be a possibility for 5 same items to drop
On ats. if First item is Item1, 2nd and ... Item cannot be Item1 since it will be excluded from roll to drop.

Proof: https://youtu.be/hGeY1Hxv-u8?t=10m ( 2 of same item (types since its al'akir rng enchant))
https://youtu.be/5AjM0qGGYFY?t=10m30s (check chat 2 of the same cloth legs dropped)

**Comment by Jamishman** [comment]
Can we get an update on this? This issue is kind of a big deal for raiders

**Comment by xolon** [comment]
Better written in #8576
