### ISSUE TITLE
[EN][NPC][DALARAN] Ildine Sorrowspear

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#7261]
http://www.wowhead.com/npc=28714/ildine-sorrowspear 
This npc, according to wowhead, should sell Enchanting Vellum. http://www.wowhead.com/item=38682 
But she isn't selling this on ATS. http://imgur.com/a/w00K4

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/9898-7261npcdalaranildine-sorrowspear/
