### ISSUE TITLE
[EN][Class] shaman ghost form

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#7262]
i swear to god there is a bug or a glitch because i keep spaming chains of ice on a resto shaman on arena while his in ghost wolf form and he runs normally, i dont see any talent or anything that WOULD NOT make him immune to these slows
if theres some head admin here and this is indeed a bug , check the player Enhu out because it didint work on him

**Comment by aneq** [comment]
I have a counter-proposal. 
If there's some head admin here please perm ban people who are unable to read tooltips.
Thanks

**Comment by phifedawg** [comment]
Cataclysm-Logo-Small Patch 4.0.6 (8-Feb-2011): Player movement speed cannot be reduced below 100% while in Ghost Wolf if the player is or has been in an indoor environment.
