### ISSUE TITLE
[EN][NPC]Kael'thas Sunstrider (Tempest Keep) Loot

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7263]
http://www.wowhead.com/npc=19622

By Cesar2000 (663 – 2·4) on 2007/08/23 (Patch 2.1.3)  
If anyone wonders, Ashes of Al'ar does not take one of the regular loot slots when it drops (i.e. you will always get 2 tokens, 2 random epics, 2 vortices, and the sphere), so it is a complete bonus.

A guildy and I have been killing him for over 5 weeks now, and all  weeks, the only thing he dropped was the tokens (and sphere for the quest once till the quest was completed)

**Comment by Evelinrose** [comment]
Killed him 5 weeks? hue hue i killed him like 5 months at least never seen single one drop either just that unlucky or i dont know what.

**Comment by LaveniaGithub** [comment]
Killed him for like 1,5 years (= still nothing, so do not worry just yet.

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11982-7263-tempest-keep-boss-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
