### ISSUE TITLE
[EN][Raid][Firelands] Lord Rhyolith rev. 4989

### ISSUE THREAD

**Issue by Kaldros** [Atlantiss/BugTracker#7264]
After the latest revision to Lord Rhyolith there are several issues which I've noticed.
**First** of all, the "invisible" damage dealt to players that just randomly kills us without any trace in death logs (skada, recount, death note) - as you can see here:
![dnote1](https://cloud.githubusercontent.com/assets/15013668/14770353/1206f47c-0a70-11e6-8cad-bfd2c56d691d.png)
![dnote2](https://cloud.githubusercontent.com/assets/15013668/14770354/120b266e-0a70-11e6-8c97-b068539631b1.png)
(Red bar represents HP)
![wol1](https://cloud.githubusercontent.com/assets/15013668/14770548/a564c7cc-0a74-11e6-913d-ad86ed2fd9db.png)

As opposed to a normal death record:
![dnote3](https://cloud.githubusercontent.com/assets/15013668/14770478/d2dae40e-0a72-11e6-9947-3c4d86de5187.png)

**Second**: Craters and Magma Flow are a huge mess. Magma Flow should never come from more than one crater at a time. On Atlantiss, we had situations where Magma Flow would be coming from 5 craters at the same time. This is not Blizzlike. You can see on the two videos I linked below that even when there are 4-5 craters present at the same time, only ONE of them does Magma Flow.

https://www.youtube.com/watch?v=lmQz5o2UvwI

https://www.youtube.com/watch?v=gc05r7UTnDk

On Atlantiss, we currently have situations where magma is flowing from every single crater and that is just extremely hard to avoid and above all - **not blizzlike**. Magma Flow should be coming from only **one** crater at the same time, regardless of how many craters are present and regardless of the time when they were created. Meaning that even if two craters were created at the same time, you should still not have 2x Magma Flow at the same time.

Also, the "invisible" damage is extremely frustrating. I assume that it's some form of a bug, as all other boss abilities are clearly recorded in the logs.

**Comment by EnPra** [comment]
can confirm, we were unable to clear rhyolith today due to these bugs

**Comment by linesar** [comment]
The "invisible damage" you are mentioning here comes form the magmaw streams, the lines that spawns from the volcanoes. They still do damage even after the lava burst from them. The fight is really hard now since they deal damage untill the lines despawn, and later on in the fight you have so many lines so it is almost impossible to avoid them all (they can be jumped over i think), This is the damage that does not show on recount.
We had some problems y-day with this and afaik, this seem to be the reason.

**Comment by Aival94** [comment]
Steering was ok for us with 2 MDPS+1RDPS on the legs.

Furthermore i believe that Volcanoes spawn randomly sometimes when they should spawn 2-3 every time the boss use [Concussive Stomp](http://www.wowhead.com/spell=102306/concussive-stomp)

**Comment by Hextall** [comment]
http://i.imgur.com/xdpwKzi.jpg :)

**Comment by BiliBee** [comment]
Rev. 4991 waiting for update, multiple magma flows fix included.

**Comment by Respect69** [comment]
Uptade it finally -_-

**Comment by EnPra** [comment]
http://imgur.com/YKTRWPm 
Fixed? :D

**Comment by Kaldros** [comment]
Hahahah, wait what? How did u get rhyolith to baleroc's room?

**Comment by EnPra** [comment]
@Kaldros 
after the last update he just fixated on our pally and we were able to kite him around fl, he got reset after we reentered. Some guy on world chat said it happened to them a week ago. no big deal, happens rarely, but it was fun :D

**Comment by cybercaptain** [comment]
Its not invisible damage, The damage is from the fragments of rhyolith , If they are not killed in 30 seconds they do rest of their health as a damage to a random player.

**Comment by Kaldros** [comment]
No it isn't.

The damage I am talking about is the damage you get from the lines on the ground left after magma flow is done bursting. The lines remain even though they should disappear immediately after the burst and deal a ton of damage to anyone crossing over them.
This damage is not recorded properly by the logs and therefore I named it "invisible damage".

The damage you are talking about is called "Meltdown" and is properly recorded and shown by addon death logs and by combat logs.
