### ISSUE TITLE
Quest: Dask "The Flask" Gobfizzle

### ISSUE THREAD

**Issue by kevinmd88** [Atlantiss/BugTracker#7265]
Quest at Explorers' League Digsite. http://www.wowhead.com/quest=26825/dask-the-flask-gobfizzle

Upon accepting the quest, you receive the quest item, but you go over to NPC:Dask "The Flask" Gobfizzle and he presents no options to do anything... No speech bubble and no interaction, and the item itself does nothing.

Effectively no way to turn this quest in, which being one of the first ones in the entire Cape of Stranglethorn area/zone presents a big hurdle in working through the content.

Let me know if I can provide any further info.

**Comment by Bildo** [comment]
read bt rules
