### ISSUE TITLE
Hunter Bugs

### ISSUE THREAD

**Issue by Ryel-p** [Atlantiss/BugTracker#7266]
Hello,

I've recently started playing this server and straight away I can see that it has a number of issues (and isn't quite as advanced as it is marketed to be) but I've noticed that the community is filled, and with nice people too. 

Here are a list of bugs I have found so far.

Kill command seems to bug from time to time, reading something like " you used kill command" in the combat log but nothing actually happens. Luckily 50% of the time /reload ui seems to fix the issue, it might take a few attempts, but, it's not exactly a difficult (short term) fix

Another bug is the pet, it randomly disappears, and sometimes it doesn't actually attack while in combat, this requires dismissing and re-summoning your pet.

Lastly, tame beast appears to be bugged, upon use it aggros the targeted beast and the cast bar reduces in accordance to that of retail, but once complete you don't seem to tame the beast at all, and it continues to attack you.

Cheers,

Zyan

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Bildo** [comment]
read bt rules
