### ISSUE TITLE
[EN][Raid][Firelands] Lord Rhyolith crater mechanic

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#7268]
how it works: lord walks into a wolkano a crater is created and from it streams of lava come out after the "tube" emerges. so  if the boss steps into 6 volcanos u get 6 craters and up to 30 magma flows around them

how it should work : after  the volcano gets steped  the magma flows  begins to crip, but only one a a time, so the next one  wont start untilll the current one errupts

https://www.youtube.com/watch?v=kkFI0YJGr4Q

https://www.youtube.com/watch?v=kv1U2o77Uqk

https://www.youtube.com/watch?v=6fuO__bqTNE#t=93

http://www.wowhead.com/npc=52558/lord-rhyolith#encounter

**Comment by Aival94** [comment]
Reported here as well with some other bugs: https://github.com/Atlantiss/BugTracker/issues/7264

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4991
