### ISSUE TITLE
[EN][NPC]Cinderweb Creeper / Spinner

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7271]
http://www.wowhead.com/npc=52648/cinderweb-creeper
http://www.wowhead.com/npc=52981/cinderweb-spinner

they should be skinnable

edit, some of the spinners have a skinning icon when I hover my mouse over them but I don't get any loot

**Comment by Piklo** [comment]
posted fix at forum 
http://community.atlantiss.eu/index.php?/topic/11076-npccinderweb-creeper-spinner/
