### ISSUE TITLE
[PL][Raid][Firelands] Ryolith/Eruption stacking

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#7274]
http://wow.gamepedia.com/Lord_Rhyolith

Patch 4.2.0 (2011-06-28): Added.

Hotfix (2011-07-08): "
Multiple volcanoes casting Eruption will now create separate stacks. Crushing a volcano will cause its stacks of Eruption to fade shortly after.
Ranged pets can no longer damage Rhyolith’s legs without beginning the encounter."

Jak widać zmiana odnośnie osobnych stacków była wprowadzona po półtorej tygodnia po wprowadzeniu fl.
Hotfix (2011-09-20): "
Health and damage have been reduced by 15% on both normal and Heroic difficulty.
The health and damage of additional enemies in this encounter have been reduced by 15% on both normal and Heroic difficulty."

**Comment by Quban** [comment]
to dlaczego spamuja mi ludzie ze mialo sie stackowac w 1 stack xD ehhhh samemu musze wszystko sprawdzac

**Comment by Lenox07** [comment]
Pewnie dlatego że sie nie znają albo im sie wydaje że tak ma być.

Ogólnie też mam wrażenie że Ryolith coś przydużo spawnuje wulkanów jakby prawie zawsze spawnował po 3. Raz zdarzyło sie że mieliśmy 8 kraterów z których prawie jednocześnie wychodziła lawa. Może jak kratery będą się aktywować w jakiś odstępach to nie będzie z tym problemu.

**Comment by BiliBee** [comment]
W zasadzie nie wiem co jest nie tak i nie mam żadnej konstruktywnej sugestii, ale coś zdecydowanie jest nie tak. W piątek Lord był prawie idealny poza wulkanami które można było targetować i brakiem animacji do eruption. W niedziele był reset, hotfix czy cokolwiek innego i boss zrobił się nie do ubicia. Rzuć na to okiem jak będziecie robić 25 w czwartek, dzięki z góry

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev4991

**Comment by stanq87** [comment]
jesli chodzi o ilosc wulkanow to na kazdym stomp 2-3 powinny sie pojawiac,

**Comment by Quban** [comment]
i tak sie pojawia
