### ISSUE TITLE
[EN][Quest][Silithus] - "Thunderaan the Windseeker"

### ISSUE THREAD

**Issue by Krooks187** [Atlantiss/BugTracker#7276]
This quest is required to obtain the legendary vanilla sword Thunderfury, Blessed Blade of the Windseeker. However upon obtaining all the required items (which can take an extremely long time as they are rare drops and crafted items) you can't progress any further in the quest as the question mark above the npc is grey as is the complete button in the dialogue window. http://www.wowhead.com/quest=7786/thunderaan-the-windseeker

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/7119
