### ISSUE TITLE
[PL][Quest][Icecrown][Into the Wild Green Yonder]

### ISSUE THREAD

**Issue by rahliell** [Atlantiss/BugTracker#728]
Protodrake nie podnosi Captured Crusader.
Po użyciu skilla "Grab Captured Crusader" cooldown się włącza i nic się nie dzieje.

Edit.
Quest można zaliczyć, używając samego skilla "Drop off Captured Crusader" w odpowiednim miejscu.

**Comment by Lulz1** [comment]
Bump - quest teraz jest niewykonalny. Wskazanych npc nadal nie da się złapać, na dodatek skill nr. 2 smoka też nie daje q credit.
