### ISSUE TITLE
[QUEST] In The Face!

### ISSUE THREAD

**Issue by Tjasq** [Atlantiss/BugTracker#7281]
I picked up my SFG and used it on the enslaved son of arkkoroc as instructed to in the quest. It killed the npc but the quest didn't recognise that I had done it. I've tried everything, i killed it without the SFG and it didn't work. I went and tried to get another one but it still didn't work. Help plz.

**Comment by pelekon** [comment]
bt rules

**Comment by Tjasq** [comment]
What's Bt Rules? Sorry I don't know

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
