### ISSUE TITLE
Embersilk Tunic 

### ISSUE THREAD

**Issue by bsbae1** [Atlantiss/BugTracker#7282]
Both myself and GM Burgo attempted to transmog the Embersilk Tunic, but to no avail. We are met with the error (This Item's Appearance Cannot be used) And I certainly know it should be usable.

**Comment by Bildo** [comment]
read bt rules

**Comment by bsbae1** [comment]
So I report something, and instead of fixing it, and thanking me for taking the time out of my day to all attention to a bug in your game. You instead reply "Read bt rules". Jesus christ
