### ISSUE TITLE
Classic alliance weapons and armor vendors [area 52]

### ISSUE THREAD

**Issue by Ehrel** [Atlantiss/BugTracker#7283]
Just writing if u're not aware, but all vendors - except one, that should be selling classic armor and weapons for alliance in Area 52 - Netherstorm do not work (aren't scripted?). [Example](http://www.wowhead.com/npc=23396/krixel-pinchwhistle) of one that isn't working just so you know of which bunch of vendors I'm talkin 'bout. A real surprise to me, since they are merely just simple vendors, yet - don't have a script. Come on.

**Comment by Bildo** [comment]
read bt rules
