### ISSUE TITLE
[EN][Quest][Cape of Stranglethorn] Dask "The Flask" Gobfizzle

### ISSUE THREAD

**Issue by kevinmd88** [Atlantiss/BugTracker#7285]
Was told to "read the rules". Did so. Hopefully I've pleased you this time.

A quest in the Cape of Stranglethorn, entitled

Dask "The Flask" Gobfizzle

Is obtainable, but the NPC does not offer anything. He cannot be interacted with, there's no speech bubble on the cursor when selecting him, and the quest item that sits in your bags provides no way to turn it in to him.

http://www.wowhead.com/quest=26825/dask-the-flask-gobfizzle

Performed a search, nothing else returned for a search for "dask the flask" other than my first submission.

**Comment by TranceAccount** [comment]
It should work, because I've done it like 2-3 months ago.
