### ISSUE TITLE
[EN][Quest][Western Plaguelands] Combat Training

### ISSUE THREAD

**Issue by kevinmd88** [Atlantiss/BugTracker#7286]
http://www.wowhead.com/quest=27174/combat-training

Can't talk to Gory. He's a friendly (green) target, but has no speech bubble icon and does not respond to right-clicking him.

**Comment by Aival94** [comment]
reported as comment here: https://github.com/Atlantiss/BugTracker/issues/482
Other Bugs: https://github.com/Atlantiss/BugTracker/issues/6755, https://github.com/Atlantiss/BugTracker/issues/1517, https://github.com/Atlantiss/BugTracker/issues/1070
