### ISSUE TITLE
[EN][Quest][Southern Barrens] A Line in the Dirt

### ISSUE THREAD

**Issue by Sytirin** [Atlantiss/BugTracker#7287]
http://www.wowhead.com/quest=24546/a-line-in-the-dirt

Banner disapear when you click on him.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5017 , https://github.com/Atlantiss/BugTracker/issues/583

Try search for other flag as one is working and one is not for alliance at least.

**Comment by Sytirin** [comment]
I found at least 3, and each was broken.
