### ISSUE TITLE
[EN][Raid-Cataclysm][NPC] Magmaw

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#729]
http://www.wowhead.com/npc=41570
http://www.wowhead.com/spell=89773

UPDATE 02.05.2014 rev 4412
* Tank being in the mangle still takes damage from other sources like [Ignition](http://www.wowhead.com/spell=92134/ignition). He should be immune to all damage except mangle damage

* If you are in the mangle you should still be able to attack Magmaw. It doesn't work. You get "out of range" message, though aoe skills like blood boil, swipe, trash still damage the boss

Proof:
http://us.battle.net/wow/en/forum/topic/2712011414#2
Second question.

**Comment by Wojmistrz** [comment]
HIGH PRIORITY - when magmaw "eat" tank (uses Mangle) and ppls want to pin him down (2 chains at the same time is casted on spike) NOTHING is happening -.- it is irritating.... sometimes it works and sometimes not MOST TIMES not working, so @qubuslabadz please fix it to allways works :) and YES for second time i will writte that WE DID USE CHAINS IN THE SAME TIME ON SPIKE (there was no misses on spike with chains) and one time it works and 2nd time it's not working at all :( makes this boss to be impossible to beat. We tryed about 6 times to do this boss and allways wipe coz of it (on BWD 10HC i don't know how it works on normal).

**Comment by Wojmistrz** [comment]
dude if i say it was done propertly and nothing was happening then it WAS if u want u can ask my guild mates.

**Comment by Varchord** [comment]
I've done It yesterday on first try. No problems whatsoever. Heroic version

**Comment by Wojmistrz** [comment]
still LINE OF SIGHT is preventing helers from healing tank when he is in MANGLE.

**Comment by Varchord** [comment]
My healers had no problems whatsoever healing me and my co-tank yesterday

**Comment by Wojmistrz** [comment]
i don't care about UR raid how it goes coz i know how it was on my raid and i want this scripts to be checked again and to do something with this tank healing problem.

**Comment by Varchord** [comment]
More sample data can help devs find the problem or lack of thereof. 
Following your reasoning. Why would anyone care for your raid when theirs go smooth and without such problems?

**Comment by Varchord** [comment]
Killed him just now. No problem with healing or pinning him down

**Comment by Dziara** [comment]
"Why would anyone care for your raid when theirs go smooth and without such problems?" Because working boss isn't problem, but bug on boss is.
Our raid also encountered problem with LoS on tank in mangle. It only seems that it doesn't happen all the time (as Varchord said).

**Comment by Varchord** [comment]
I need screen/movie made by healers where I can clearly see that they don't stand out of LOS on their own (spike is creating los). Otherwise I won't add this to my issue, I've already trusted someone on their word and it turned out to be bullshit

**Comment by Jenovas** [comment]
1. You may not be able to pin him because someone shots NEXT to the pillar and not directly at it - that is your raid problem not a server problem.

2. Your healers probably are standing somewhere near the pillar or the pillar is between them and the tank - the pillars has VMAPS, so that ain't a server problem too (I heard once that the pillar shouldnt have VMAPS but didnt check into that)

**Comment by Varchord** [comment]
Fuck yeah! Cavalry!

**Comment by Varchord** [comment]
UPDATE 02.05.2014 rev 4412
* Tank being in the mangle still takes damage from other sources like [Ignition](http://www.wowhead.com/spell=92134/ignition). He should be immune to all damage except mangle damage

**Comment by Varchord** [comment]
Consolidated
https://github.com/Atlantiss/BugTracker/issues/3143
