### ISSUE TITLE
[PL][Hunter] Flare

### ISSUE THREAD

**Issue by kevery123** [Atlantiss/BugTracker#7290]
Flary range jest zbyt duży ponieważ np na duelu Roguem na Huntera powinna być możliwość użycia Sapa w stealthu na Huntera stojącego w samym środku Flary a tutaj nie ma możliwości ze Sapniemy w stealtha hunter stojącego w środku ponieważ Flara wcześniej nas wykryje.

**Comment by Jenovas** [comment]
Flara i Sap mają taki sam zasięg 10 yardów.
Naprawdę ciężko by było dać sapa.
Proszę o jakieś dowody na to co twierdzisz następnym razem.
Zamykam.

**Comment by jissabraham** [comment]
remove all from hunter and let every one kill
