### ISSUE TITLE
[PL][Warlock][Pet] Pet combat bug

### ISSUE THREAD

**Issue by kevery123** [Atlantiss/BugTracker#7293]
Pet Warlocka na tym serverze jest zbugowany ponieważ  Warlock po wysłaniu peta na kogoś odrazu dostaje combat. Nie musi nawet użyć spella Peta czy nawet Pet nie musi zaatakować wyznaczonego target aby przeciwnik dostał odrazu combat.

**Comment by lamaATS** [comment]
Fixed in rev. 5533
