### ISSUE TITLE
[EN][Raid][Firelands] - Ragnaros - Phase Two

### ISSUE THREAD

**Issue by MangeNerfedOwl** [Atlantiss/BugTracker#7294]
Yesterday during start Phase Two on Ragnaros (first hammer adds) Ragnaros instead of hiding in lava still stayed when usual what caused tanks got killed when tried to nuke adds because they were too far away from the boss. I happened once.

**Comment by Aival94** [comment]
Reported here as PL(i used google translator to understand what they were saying :P ): https://github.com/Atlantiss/BugTracker/issues/7103
