### ISSUE TITLE
[EN][Hunter][Pet] Beast master pets dmg overscaling or not scaling with resiliance.

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#7295]
The dmg of beast master hunter pets is overscaling on the server and by so doing too big dmg.The chances mostly are that the pet doesnt scale with resiliance same like with warlock imp and other classes with pets this should be put on top priority for fixing.

**Comment by Jenovas** [comment]
In the next issue please show some kind of proof.
Numbers, scaling, show that resilience doesnt work with the pet.
I'm not gonna do this myself only to find out everything seems fine.
