### ISSUE TITLE
[NPC][Children's Week] Ophan Matron Mercy

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#7301]
http://www.wowhead.com/npc=22819/orphan-matron-mercy

1. She doesn't give the "Children's Week" quest (ally: http://www.wowhead.com/quest=10943, horde: http://www.wowhead.com/quest=10942), probably because i did them 2-3 years ago. That's a bug, these quest should be available to complete every year
2. She doesn't have the gossip to get "Blood Elf Orphan Whistle" (http://www.wowhead.com/item=31880) or "Draenei Orphan Whistle" (http://www.wowhead.com/item=31881) if we don't have them.

These two bugs make the whole outland part of children's week quests unavailable and impossible to complete.

**Comment by 1Andas** [comment]
I'd also like to add that I never did her quest and she doesn't offer it at all.

**Comment by Mevar** [comment]
Hope u guys will fix this npc till the end of event. There is a only one way to day a rare achievement with 3 pets one by one every year. Please :)

**Comment by Bildo** [comment]
will be fixed by the end of this week just give me some time

**Comment by Bildo** [comment]
fixed

**Comment by monibu** [comment]
Shame we don't get to see her this year, since the update was made after the event ended
