### ISSUE TITLE
[EN][Quest][Darkshore] The eye of all storms

### ISSUE THREAD

**Issue by naakarg** [Atlantiss/BugTracker#7304]
Link to quest: http://www.wowhead.com/quest=13588/the-eye-of-all-storms
Quest: The eye of all storms, in this quest player is forced to jump on Thessera (dragon/vehicle), fly up in the air and kill 12 dragons.
Bug: Enemy targets supposed to be in the air, but instead of that are falling down to the ground at spawn making the quest almost impossible to complete. The dargon/vehicle itself can be sometimes uncontrollable, and even though if the player manages to reach the ground the game says that the enemy targets are out of range no matter how close they really are.
![Screenshot](http://i.imgur.com/5lAAEF0.png)
Thanks for your attention, please fix asap.
Good day to you

**Comment by Larousene** [comment]
That bug is already reported : https://github.com/Atlantiss/BugTracker/issues/2028

**Comment by naakarg** [comment]
Now I see that its been already reported lots of times and still bugged, are these reported quests actually getting fixed sometimes?
