### ISSUE TITLE
[EN][Quest][Darkshore] The Absent-Minded Prospector

### ISSUE THREAD

**Issue by naakarg** [Atlantiss/BugTracker#7305]
Link to quest: http://www.wowhead.com/quest=13911/the-absent-minded-prospector
Quest: In this quest the player is supposed to have a walk with a dwarf to help him find his journal.
Bug: When this "lovely journey" ends the quest tells the player to speak to the jr. archaeologist to finish the quest, well apparently as the screenshot below shows, there is no question mark or anything above the npc to click on.
(Btw the npc sometimes moves really sloppy and makes the player to bump into obstacles which makes the quest sometimes a real pain in the ***, but thats a minor thing that is possible to deal with.)
![Screenshot](http://i.imgur.com/XLJjagD.png)
Thanks for your attention
Good day to you

**Comment by Larousene** [comment]
That bug is also reported: https://github.com/Atlantiss/BugTracker/issues/648
