### ISSUE TITLE
[EN][Raid][Firelands]Rhyolith and Battle Standard of Coordination

### ISSUE THREAD

**Issue by Vidyapoky** [Atlantiss/BugTracker#7307]
![wowscrnshot_042916_001222](https://cloud.githubusercontent.com/assets/1499989/14903464/836d2ac6-0da1-11e6-8a41-ac9b01ea85bf.jpg)

As seen in screenshot, Rhyolith will be still in combat if a banner is dropped and will remain so until banner despawns. 

Furthermore the amount of volcanoes that spawn is overwhelming, with sometimes even 5 at one time, making fight really hard, if not almost impossible.

**Comment by stanq87** [comment]
the banner bugs  lord and the spider , somtemis the phenix
again: every stomp 2 or 3 volcanos should pop out and not despawn until u  step on one

**Comment by Aival94** [comment]
The banner should not be used and i remember some devs telling that this kind of bug abuse can be bannable so is your problem using a bug as in retail the banner could not be placed on FL generally.

**Comment by Taarg** [comment]
To many volcano's to many magma flow chaining.
