### ISSUE TITLE
[QUEST] Sigil of Strom

### ISSUE THREAD

**Issue by Astagos** [Atlantiss/BugTracker#7309]
The Sigil does not drop.

**Comment by Larousene** [comment]
Do u mean that q: http://www.wowhead.com/quest=639/sigil-of-strom?
According to wowhead quest item (http://www.wowhead.com/item=4440/sigil-of-strom) has 2% chance  to drop

**Comment by user1011** [comment]
@Astagos Please follow the _How to use?_: [https://github.com/Atlantiss/BugTracker](url)
