### ISSUE TITLE
[EN][NPC]Kael'Thas Sunstrider

### ISSUE THREAD

**Issue by boterhamburger** [Atlantiss/BugTracker#7310]
Hi, 

it seems that Kael'thas in Tempest Keep casts his Pyroblast through walls and obstacles. From what I know, he's not supposed to do that on the live servers.

Thank you for your help!
Boter

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.
