### ISSUE TITLE
[EN][Quest][Ashenvale] Return Fire

### ISSUE THREAD

**Issue by naakarg** [Atlantiss/BugTracker#7311]
[Link to Quest](http://www.wowhead.com/quest=13853/return-fire)
[Video to Quest](https://www.youtube.com/watch?v=xAglNhae8AY)
I've seen this quest has been reported once already, but it was poorly described without following these "posting rules" so I decided to re-issue it with the hope of catching your attention.

**EDIT:** I've decided to update this report as there is a new problem with the quest now.

**Quest:** Player must enter one of the [Astranaar Throwers](https://wow.gamepedia.com/Astranaar_Thrower) provided to shoot down 15 mobs in the air.
**Bug:** The mobs are fixed now and float in the air as expected, but the throwers can't be interacted with anymore and killing the mobs yourself won't give any credit.

![Screenshot](https://i.imgur.com/i9K0lji.jpg)
Thanks for your attention.

**Comment by locheiaagrotera** [comment]
I am having a different issue. I can't board the glaive throwers, and even when I manually kill riders, I don't get any credit towards shooting them down. Currently cannot be completed.

**Comment by Mickowhy** [comment]
I can't use the Astranaar Thrower too,

**Comment by DameronAlgalon** [comment]
I can confirm, the quest is currently bugged because you cannot enter the Astranaar Thrower.

**Comment by Damfee** [comment]
Still impossible to enter in the thrower. I think Malylolek fixed it but it is broken again.

**Comment by Malylolek** [comment]
Will look at this, sorry for problems.

**Comment by karhima** [comment]
The mobs are in the air now but as already reported the Astranaar Thrower cannot be used.

**Comment by Snake90** [comment]
Still bugged :/ The Astranaar Thrower can't be used even after a restart/ crash.

**Comment by 1Andas** [comment]
Confirmed. The vehicles can't be interacted with.

**Comment by UdfuzhnOlbrick** [comment]
Hmm. Unable board a thrower. Very uncommon bug while I was able to complete it months ago (middle of october/november, guess) before I decided on another class.

**Comment by Khangu** [comment]
There is possibility to kill mobs manually. If you hit them with any ranged attack, they will fly down and start fighting. However this doesn't help at all cause mobs killed that way doesn't count. Quest is still completely broken.

**Comment by Snake90** [comment]
Still bugged :/

**Comment by NMGAMING** [comment]
Still bugged, mobs are in the air but you cannot use Astranaar Thrower.

**Comment by Snake90** [comment]
Still bugged ! Somebody is really working on it or nobody has anything to do with it ...

**Comment by naakarg** [comment]
Don't think there is anyone who cares about it at this point, the answer will probably something like "it's not a priority quest, we have other stuff to fix..."

**Comment by TranceAccount** [comment]
## Posted a fix on the forum for the mounting part:

https://community.atlantiss.eu/index.php?/topic/18255-npc-astranaar-thrower-cecidit-parody/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
