### ISSUE TITLE
[EN][Quest][Ashenvale] The Last Stand

### ISSUE THREAD

**Issue by naakarg** [Atlantiss/BugTracker#7312]
I dont know if I shouldn't repost things here, tell me if so, but as some people said this quest has been bugged for a year now. (Prob there are more important things to fix, but you know hope dies last :D )
Link to Quest: http://www.wowhead.com/quest=13987/the-last-stand
Video: https://www.youtube.com/watch?v=_0vtoMF3bMU
Quest: As the video shows there must be enemies spawned after accepting the quest.
Bug: As the Image shows below nothing happens after accepting it.
![Screenshot](http://i.imgur.com/frpZPgy.png)
Thanks for your attention

**Comment by Aival94** [comment]
This bug is already reported.If you want to add sth make a comment to the first bug report which is open.

Reported: https://github.com/Atlantiss/BugTracker/issues/660

**Comment by naakarg** [comment]
Will do so next time
