### ISSUE TITLE
[EN][Firelands] Ragnaros Living Meteor

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#7314]
Raid: Firelands
Boss: Ragnaros
Creature: Living Meteor

Link1: http://www.wowhead.com/npc=52409/ragnaros#encounter
Link2: http://www.wowhead.com/npc=53501/living-meteor

1. Meteor sometimes sudenly stops moving
2. Meteor can target totems

**Comment by EnPra** [comment]
![ragnaros meteor](https://cloud.githubusercontent.com/assets/17710214/15230416/cbdb42bc-1895-11e6-8b39-6399ffd10c32.png)  meteors not moving is still a problem. also on wipe we got a meteor bugged in front of rag(it kept targeting us but rag wasnt pulled). it got fixed when we pulled rag and died.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5020
