### ISSUE TITLE
[PL][Raid][Firelands] Lord Rhyolith rev. 4991

### ISSUE THREAD

**Issue by LordKnightCecilo** [Atlantiss/BugTracker#7315]
Noticed a few bugs which are different from my time on retail. - http://www.wowhead.com/npc=52558/lord-rhyolith#encounter

The Eruption Debuff should only have one stack on a player, and all volcanos will simply add onto that stack. The way it currently works you could have two (or more) stacks of 10 stacks which each give you 100% increased fire damage, and it simply becomes too much.

Post 4.2.2, every time he steps on a volcano in Normal 10 or 25man he goes down by 16 Stacks of Obsidian Armor (Currently goes down by 10, not entirely sure what patch we are considered to be on)

I believe he is either creating to many volcanoes, or stomping too often. Only 2-3 should be spawned per stomp, and during my guild's attempt (Which we did kill after three hours, Fifteen wipes), we consistently saw 2-3 spawn on the first stomp, and then another 4-5 would pop up. 

It also feels like he is activating more than one volcano at a time, or again they are activating far too quickly, we had three active magma flows at a time, which could happen if you are actively avoiding sending him to volcanoes, but he would hit ones he just spawned and they would send lines.

Most raids I feel are not going to be able to do this, and considering my guild did the entirety of Firelands after this boss in one hour, while he took three, I think he has some serious issues.

https://www.youtube.com/watch?v=kkFI0YJGr4Q

25 Man Seems to be completely different to the 10man version, the 25man Tankspot video looked a lot more like the 10man version we were dealing with.

**Comment by Lenox07** [comment]
Eruption is working like it should.
http://wow.gamepedia.com/Lord_Rhyolith
http://us.battle.net/wow/en/blog/3019413
"July 8
Rhyolith
Multiple volcanoes casting Eruption will now create separate stacks. Crushing a volcano will cause its stacks of Eruption to fade shortly after."

If you think that he stomps too often check multiple vidz from retail and with timer specify stomp cooldown and then check with timer stopm cooldown on our server.

**Comment by Taarg** [comment]
It is not working fine, each crater erupts after its been trodden on causing a continuous chain event of magma flows and every crater created will erupt there is nothing "occasional" anymore about these magma flows constant warning now on my screen one after another...... "MAGMA FLOWS" , "MAGMA FLOWS". This boss is now the hardest boss in FL. We lasted longer on 25 man encounter with 10 men than on 10 man itself. I have watched some videos this does not look like retail, people in my guild say it is not like retail. This will end FL raids for many.

**Comment by Lenox07** [comment]
Eruption and magma flow are two difrent things XD
Eruption is debuff from ignited volcano and magma flow are those lines from craters.

**Comment by Aival94** [comment]
One more thing.There is a possibility for the boss to activate twice the same volcano if it stay active for too much time without being destroyed.

**Comment by milzo** [comment]
Whole Rhyolith is far from blizzlike :)

**Comment by Norbisio** [comment]
We just went to check if this is still an issue and it is! There isn't one set of stacks on this boss but there are many multiple stacks sometimes so it's impossible to heal 10 normal even with 3 heals dealing 20k heal per second each (yeah, we've tried that :P). This Eruption debuff isn't working as it should.

**Comment by coba999** [comment]
>there will be only one crater activated at a time (no more multiple lava flows)
**LIE!!!**

**Comment by Norbisio** [comment]
I believe it was fixed... There aren't multiple lava flows... There is one by one Lava Flow, not multiple Lava Flows at the same time... At least I haven't noticed that and I was trying to do this boss many times lately :) We stuck at him and cannot move on to Majordomo second week at the row :)

**Comment by Illusie** [comment]
https://github.com/Atlantiss/BugTracker/issues/7321
what i wrote there. ^
