### ISSUE TITLE
[PL][Raid][Firelands] Lord Rhyolith 

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#7321]
3 wipy 3x czekanie po 30 min az sie event odbuguje,  bez sztandarow i tego typu dodatkow

**Comment by Respect69** [comment]
Magma flowy wybuchają w większości nagle, a nie stopniowo, a kratery długo nie znikają po wybuchu.. to jest gorsze.

**Comment by stanq87** [comment]
tak, ale to da sie ogarnac a  zbugowany zapetlony event juz nie ogarniesz

**Comment by arekczup** [comment]
vulcano może sie zestakowac do 25 razy

**Comment by arekczup** [comment]
mamy bófa z hero molten armor http://www.wowhead.com/spell=98255/molten-armor#changelog

**Comment by Hexenbane89** [comment]
nadal lord zbugowany, powinny być wulkany tylko wtedy gdy tupnie nóżką :D a jest ich multum.

**Comment by Respect69** [comment]
Quban! Popraw tego lorda, bardzo Cię proszę :D

**Comment by Coolia** [comment]
To moze ja sie troche rozpisze...
Kierowanie bossem jest na Atlantissie calkowicie skopane. Na globie wystarczyla chwila aby skrecic bossem ale za to ciezko bylo dobic do maksymalnego skretu. Boss skrecal dokladnie tak jak skierowali go gracze. U nas wyglada to tak ze ciezko w ogole zaczac skrecac bossem, Zmiana kierunku przy calym przerzuconym raidzie na jedna noge zajmuje jakies 10sek. Dodatkowo boss mimo 'naladowanego skretu' czasami postanawia przejsc jeszcze sobie 10yd do przodu i dopiero wykrecic o 90stopni w jednym miejscu. Dodatkowo boss chodzi za szybko.
Magma Flowy u nas zadaja za duzo dmg. Stojac na drodze wybuchu otrzumuje sie 2-3uderzenia co zazwyczaj skutkuje smiercia. Koncowy wybuch po prostu zabija gracza i tyle sie naraidowal. na globie Flow podrzucal gracza RAZ zadajac mu 75k dmg i zostawial gracza w spokoju pozwalajac mu swobodnie odbiec z miejsca wybuchu. Koncowy wybuch zadawal ten sam dmg co wczesniejszy podrzut i wcale nie byl smiertelny.
Na globie wulkan razem ze sladem po Magma Flowie znikal dosownie sekunde po wybuchu i mozna bylo o nim zapomniec. U nas slad po wybuchu zostaje przez dobre 10sek o ile nie wiecej i do tego zadaje NIEWIDZIALNY dmg ktorego wcale nie powinien zadawac. Ten slad powinien byc tylko efektem wizualnym po wybuchu.
Tutaj prawde mowiac nie wiem co zglosic ale sam boss na 10tce robi 45-50k dpsu w raid. Na globie robil ok 26k dps w raid wiec mozna powiedziec ze mamy dwukrotne przebicie chociaz nie wiem w ktorym dokladnie miejscu.
Rozdeptane wulkany utrzymuja sie za dlugo co tez nie pomaga w walce (krater po wybuchu wraz ze sladem po Magma Flowie despawnuje sie chyba na tej samej zasadzie co inne wulkany czyli po jakims czasie)
Magma Flowy maja za duzy obszar dzialania. Czesto ludzie padaja tam gdzie mieli juz prawo czuc sie bezpiecznie.
Achiev za skrecanie tylko wprawo jest oczywiscie zbugowany i zalicza go po kazdym zabicu bossa.

Chyba wymienilem wszystko. Jesli potrzebujecie dowodow na potwierdzenie moich slow to niestety mam tylko filmiki znalezione na yt oraz stare logi z world of logs jednak zapewniam ze nie wyssalem sobie tego z palca. To jak dziala ten boss na Atlantissie mozecie sprawdzic w kazdej chwili wiec dowodow nie zbieralem.
Losowy filmik z yt - https://www.youtube.com/watch?v=-X45BEWpQ8k
World of Logs z zapisanymi Lordami (do wyboru do koloru. Sprawdzicie wszystko co chcecie) http://www.worldoflogs.com/zone/eu-us/firelands/lord-rhyolith/normal-10/kills/p15/

**Comment by arekczup** [comment]
lawa zadaje bosowi 1% damage jak wejdzie i tak do wejścia 2 fazy czasami krócej

**Comment by arekczup** [comment]
czasami ciongle aktywuje tylko 1 wulkan który został wcześniej aktywowany/././.

**Comment by Coolia** [comment]
Uzupelniajac moje poprzednie zgloszenie o niektrore dowody:
Wielokrotne uderzenie z Magma Flow (zapewniam ze bylby tez 3,4 oraz 5ty strzal z Flowa jesli tylko bym mial az tyle hp aby to wyzyc http://i.imgur.com/u97aMnb.jpg Magma Flow powinien uderzac tylko raz przy pojawianiu sie oraz ponownie tylko raz podczas wybuchu co mozna zobaczyc na zalaczonym wczesniej filmiki.
DPS zrobiony przez bossa http://i.imgur.com/VNCQWZZ.jpg Tak zeby nie bylo ze wzialem cyfry w poprzednim poscie z kosmosu
Niewidzialny dmg ktory zadaje slad po wybuchu Magma Flowa. Jak widac gracz oficjalnie nie otrzymal zadnego dmg ktory by go zabil a mimo wszystko cos go zabilo. http://i.imgur.com/OKOGhWD.jpg Tylko jeszcze powtorze ze ten dmg nie powinien w ogole istniec a slad po magma flowie znika zaraz po wybuchu co mozna ponownie zobaczyc na filmiku wklejonym wczesniej. 
Bez mozliwosci nagrania filmiku nie dostarcze dowodow na to jak wyglada u nas sterowanie bossem , na to ze boss chodzi ordobine za szybko oraz na to ze czasem mimo skretu postanawia isc prosto i dopiero pozniej zmienic kierunrunek o 90stopni.
Nie udalo mi sie zlapac na ssa sytuacji gdzie magma flow wysadzil w powietrze osobe ktora stala 3-4yd od flowa ale postaram sie to zrobic na nowym id. (Mozecie to tez sami sprawdzic ale komu by sie chcialo...) Zbyt dlugie utrzymywanie sie rozdeptanych wulkanow tez jest ciezkie do uchwycenia na ssie ale wystarczy ze wejdziecie postacia GMa i pullniecie bossa a sami zobaczycie jak to wyglada. Jak dlugo rozdeptane wulnany powinny byc widoczne doskonale widac na filmiku ktory wyslalem.

**Comment by Hexenbane89** [comment]
Dowodów na to że Boss jest źle oskryptowany jest wystarczająco, kiedyś działał w miarę normalnie a teraz co tydzień jest popsuty.

**Comment by Illusie** [comment]
Don't understand polish,
but we can't kill him this week. and we killing him everywhere for 3 months.
only last time we couldn't and now.

**Comment by EnPra** [comment]
after a wipe rhyolith stays bugged, 4th week in a row we have to wait for 30 min

**Comment by stanq87** [comment]
it seems  the event bugs when someone uses a survi skill like hunter or rogue, and when someone dies from lava

**Comment by Aival94** [comment]
I have done this encounter many times the past weeks and i have never encountered the eternal event bug. I believe this bug occur only when using the flag to get more rep which make the boss bugged.Next time better give ss with the boss getting bugged while no flag around or try to tell what else happened.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5028 still need to script banner
