### ISSUE TITLE
[EN][Quest] The Ring of Blood: The Final Challenge

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#7323]
Upon accepting this quest, Mogor walks into middle of nagrand arena and just stays there as a friendly target. Cannot be attacked and killed.

**Comment by Crusaderz** [comment]
It works now. I'm going to close this one.

**Comment by Noviush** [comment]
Mogor seems to be bugged again, after killing him quest isn't completed. Killed several times and no effect...

**Comment by RangerTalion** [comment]
bump

**Comment by Thunderlmao** [comment]
As of 05/05/2017 the quest doesn't work. The enemy will just stand there and be friendly.

**Comment by Piklo** [comment]
@Thunderlmao open new post instead of commenting the closed one

**Comment by stupididiotblizzard** [comment]
quest is still broken killed mogor 3 times now, he doesn't ressurect to kill him a second time to complete the quest.
