### ISSUE TITLE
[EN][Quest][Icecrown] Before the Gate of Horror

### ISSUE THREAD

**Issue by Dranerys** [Atlantiss/BugTracker#7325]
When doing the quest [Before the Gate of Horror](http://www.wowhead.com/quest=13329/before-the-gate-of-horror) using the [item](http://www.wowhead.com/item=44653/volatile-acid) doesn't seem to work. It's supposed to dissolve the remains of a Skeletal Reaver but when using it nothing happens.

**Comment by Dranerys** [comment]
Quest is completable by click on the tiny orange bolt near the Skeletal Reavers and using the item on that.

**Comment by TheCopacabanaMan** [comment]
There is no "tiny orange bolt" near the Skeletal Reavers. Me cannot complete quest
