### ISSUE TITLE
[EN][QUEST][GILNEAS] Save Krennan Aranas

### ISSUE THREAD

**Issue by DisposableDacian** [Atlantiss/BugTracker#7328]
In the Worgen starting zone there is a quest (Save Krennan Aranas) in which you mount a scripted horse, press a button once you get to an NPC (Krennan Aranas), and then ride off to save the NPC. For me, however, once I had saved him and I was automatically dismounted from my horse, it despawned, but I hadn't completed the "0/1 Save Krennan Aranas" requirement, and thus can't turn the quest in and progress in the game.

Link to quest: [http://www.wowhead.com/quest=14293/save-krennan-aranas](http://www.wowhead.com/quest=14293/save-krennan-aranas)
Link to NPC: [http://www.wowhead.com/npc=35753/krennan-aranas](http://www.wowhead.com/npc=35753/krennan-aranas)

I know of no way to restart the quest save to delete my character and begin anew. I was in a party at the time, and nobody else in my group had the same issue.

**Comment by naakarg** [comment]
cant u just abandon the quest in the quest log and go back to the quest giver?

**Comment by DisposableDacian** [comment]
I think as a result of the phasing (or whatever it is called that makes the world change as you quest) he disappeared for me. In the end I just deleted my character and started over cause that is the only way I could get the quest giver back.

Thanks very much for your help!
