### ISSUE TITLE
[EN][Spell][Mage] Pyromaniac

### ISSUE THREAD

**Issue by Niukka** [Atlantiss/BugTracker#7333]
> "Increases spell haste by 10% if 3 or more targets are taking Fire damage over time from your spells."

This talent can be bugged to grant 10% spell haste with only 1 Living Bomb active. Found the bug by accident and decided to try to reproduce it. Reproducable very easily by going into The Stockades, casting LB on 2 mobs and then exiting the instance before it ticks. When the bug is active, impact becomes bugged as well, not spreading Living Bomb onto targets near your fire blast target. On top of this, while the bug is active, Living Bomb can be put on as many targets as you want.

It resets when you log out.

![wowscrnshot_050216_120743](https://cloud.githubusercontent.com/assets/18738097/14951080/28c37b46-105f-11e6-8e6d-a34fc1b8f7a1.jpg)

**Comment by 1Andas** [comment]
Off topic, but I like your UI. Quite nicely arranged.

**Comment by Illusie** [comment]
still no fix.
gg for all the mages that have 10% free haste.

**Comment by Illusie** [comment]
@everyone
@lamaATS (sry for @ you ^^)
10% haste bug bonus for Fire Mages still exist.

Enter The Stockade > Pull 2 mobs near the exit/enterance > Living bomb them > leave dungeon before they tick > next living bomb on any mob will grant you 10% haste.

Normally mages have around 15% Haste with that bug > 25% haste

**Comment by lamaATS** [comment]
I understand but this talent required some specific mechanic and I want write it once so.  Currently I don't have idea how to write it properly. (This issue is on my TODO list since your last comment)

**Comment by lamaATS** [comment]
Fixed in rev. 5259
