### ISSUE TITLE
[EN][Quest][Northrend] Valkyrion Must Burn

### ISSUE THREAD

**Issue by Karathe** [Atlantiss/BugTracker#7334]
Quest is impossible to complete due to lack of Dry Haystack to be lit with Harpoon Launchers. Possibly they do not respawn after used by another player or they have very long respawn timer.

Even though PrivStat addon shows that quest is "blizzlike" I was unable to complete it since yesterday (01-05-2016).

Exact details of the quest can be found here: http://www.wowhead.com/quest=12953/valkyrion-must-burn

**Comment by stanq87** [comment]
still missing / bugged

**Comment by Navedonar** [comment]
.

**Comment by Ressin** [comment]
Just completed it, the Haystacks are respawning correctly.

**Comment by wtRCH** [comment]
I am closing it due to @Ressin comment.
