### ISSUE TITLE
[EN][Reputation][Dungeons]Cenarion Exedition on Underbog and Slave Pens

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7335]
The [Slave Pens](http://www.wowhead.com/zone=3717/the-slave-pens) bosses should give reputation to Cenarion Expedition in both Normal and Heroic mode until you reach 999/1000 to exalted.Now on normal bosses when you are honored give no rep(Trashes seems to be working correct).

The [The Underbog](http://www.wowhead.com/zone=3716/the-underbog) mobs and bosses should give reputation to Cenarion Expedition In normal and Heroic mode until you reach 999/1000 to exalted. Now on Normal nothing is giving rep at least when you are honored.

Wowhead Links: [Slave Pens Mobs](http://www.wowhead.com/zone=3717/the-slave-pens#npcs) and [The Underbog Mobs](http://www.wowhead.com/zone=3716/the-underbog#npcs)

Note: If there was any change in the reputation farming and make these dungeson farm spots after the cataclysm please make a comment with proof so i close this issue as for myself did not manage to find which patch the reputation farming changed.

**Comment by Navedonar** [comment]
http://www.wowhead.com/faction=942/cenarion-expedition#npcs
Honored to Revered
Once the player is Honored, running Slave Pens and the The Underbog (with the exception of Hungarfen and some giants), will no longer grant reputation.

**Comment by Aival94** [comment]
I searched a little more and found that only HC are giving reputation from these dungeons. This is the only thing i could find as proof: http://us.battle.net/forums/en/wow/topic/5149013746#post-5

If you know it changed during this time please close this post. For now will edit it and remove the Normal and keep the HC mode.
