### ISSUE TITLE
[EN][Quest][The Violet Hold]Containment(ID 29830)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7336]
Quest should be a one-time Dungeon quest but instead on server it is a repeatable one.

Wowhead Link: [Containment](http://www.wowhead.com/quest=29830/containment)

**Comment by 1Andas** [comment]
Confirmed.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12534-7336questthe-violet-holdcontainment/
