### ISSUE TITLE
[EN][Reputation][Dungeon]Sporegarr on Underbog

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7337]
The [The Underbog](http://www.wowhead.com/zone=3716/the-underbog) mobs in Normal should give reputation to Sporegarr until 999/1000 of Exalted but on Normal mode mobs do not give any reputation at all and in Heroic they give while in Heroic mode the reputation to Sporegarr have been removed during cata.

Wowhead Links: [The Underbog Mobs](http://www.wowhead.com/zone=3716/the-underbog#npcs)

**Comment by tomatosz** [comment]
It should actually only give Sporeggar rep on normal:

> By Amnestic (7,576 – 2·11·40) on 2011/12/20 (Patch 4.3.0)
I just went into Heroic Underbog and received NO reputation (at Revered) for any trash mob up to the first boss, who likewise gave NO Sporeggar rep. Rep gains therefore appear to be Normal Underbog only, though you can still get Sanguine Hibiscus from Heroic mode.
(http://www.wowhead.com/faction=970/sporeggar#comments)

**Comment by Aival94** [comment]
Updated it. Ty @tomatosz . To be honest only check wowhead mobs for the reputation and nothing else.

**Comment by tomatosz** [comment]
Attempted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14464-underbog-sporeggar-reputation/

**Comment by Jenovas** [comment]
Fix in 5539
