### ISSUE TITLE
[EN][Reputation][Dungeon]Honor Hold on Hellfire Ramparts and The Blood Furnace

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7338]
Both dungeons in normal mode mobs should give rep until honored and bosses until 999/1000 of exalted to Honor Hold. Now both dungeons mobs and bosses do not give any rep at all in Normal Mode.

Wowhead Link: [Hellfire Ramparts Mobs](http://www.wowhead.com/zone=3562/hellfire-ramparts#npcs) and [The Blood Furnace Mobs](http://www.wowhead.com/zone=3713/the-blood-furnace#npcs)

**Comment by user1011** [comment]
http://www.wowhead.com/npc=17455/bonechewer-beastmaster
Normal
- 5 reputation with Honor Hold (stops at Honored)
- 5 reputation with Thrallmar (stops at Honored)

**Comment by user1011** [comment]
Posted a fix on the forums for the Blood Furnace normal.
