### ISSUE TITLE
[EN][Quests][Mount Hyjal][Alliance][Minor]Completing Quest window does not disappear

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7341]
After pressing the "Complete Quest" button in these quests the window does not disappear or the next quest window does not appear.

[War on the Twilight's Hammer](http://www.wowhead.com/quest=25319/war-on-the-twilights-hammer)
[Flamebreaker](http://www.wowhead.com/quest=25323/flamebreaker)
[Emerald Allies](http://www.wowhead.com/quest=25430/emerald-allies)
[The Captured Scout](http://www.wowhead.com/quest=25320/the-captured-scout)
[Twilight Captivity](http://www.wowhead.com/quest=25321/twilight-captivity)
[A Prisoner of Interest](http://www.wowhead.com/quest=25324/a-prisoner-of-interest)
[Through the Dream](http://www.wowhead.com/quest=25325/through-the-dream)
[The Return of the Ancients](http://www.wowhead.com/quest=25584/the-return-of-the-ancients)
[The Voice of Goldrinn](http://www.wowhead.com/quest=25268/the-voice-of-goldrinn)
[Goldrinn's Ferocity](http://www.wowhead.com/quest=25271/goldrinns-ferocity)
[The Shrine Reclaimed](http://www.wowhead.com/quest=25280/the-shrine-reclaimed)
[Gar'gol's Gotta Go](http://www.wowhead.com/quest=25328/gargols-gotta-go)
[Lightning in a Bottle](http://www.wowhead.com/quest=25353/lightning-in-a-bottle)
[Cindermaul, the Portal Master](http://www.wowhead.com/quest=25599/cindermaul-the-portal-master)
[The Name Never Spoken](http://www.wowhead.com/quest=25412/the-name-never-spoken)
[Fact-Finding Mission](http://www.wowhead.com/quest=25740/fact-finding-mission)
[A Gap in Their Armor](http://www.wowhead.com/quest=25758/a-gap-in-their-armor)

**Comment by MichaelArchangelo** [comment]
That is the case in most of the quest chains, if not all.

**Comment by Luna-maria** [comment]
this started to happen when they 'fixed' the auto accept quests in the starting areas from being accepted straight when you completed the quest before it, without you even being able to read it without going to your questlog manually :/

**Comment by Aival94** [comment]
I am not sure when this happened but i think they said that this "bugged" quests should be reported one by one so i reported the Mount Hyjal ones for now.If it is a core problem they might find the issue by checking this quests i suppose and if they think this report is useless they can delete it.

**Comment by BAndysc** [comment]
Did it work in the past? If so when has it broken?

**Comment by Aival94** [comment]
As far as i remember in the past it worked much better but after an update these things started to happen. This bug is for a month and a half or more as far as i remember.

**Comment by Aival94** [comment]
Either @BAndysc or any other Dev can tell me if i should report per zones quests with same problem as minor issue or is just useless?

**Comment by BAndysc** [comment]
Fixed in 5097 :)
