### ISSUE TITLE
Battered Hilt quest

### ISSUE THREAD

**Issue by Dreadmaus** [Atlantiss/BugTracker#7344]
The quest has been bugged for sometime now according to some players. The quest chain stopped at the final chain which is "Return To Myralion Sunblaze" where the npc got stuck when blood queen appears. On top of that the quest item disappears from bag which pretty much means players have to farm the quest item again. I really do hope this bug gets fix and at least provide the quest item back so that I don't have to farm it again took me hours doing so.

**Comment by 1Andas** [comment]
This chain can't be finished at the moment. Sunwell is closed as a raid, so you can't enter the special quest phase required on the final quest to get the sword because the entrance is blocked.

**Comment by Dreadmaus** [comment]
thats sad i really want that transmog badly

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker

**Comment by Bildo** [comment]
bt rules
