### ISSUE TITLE
[EN][Quests][Stormwind City] Twilight Shores

### ISSUE THREAD

**Issue by yooppvladutz** [Atlantiss/BugTracker#7345]
I got the quest and the NPC where i need to go to finish the quest is not there to complete the quest and advance to Twilight Highlands.

**Comment by Jinkz** [comment]
Got the same problem here!

**Comment by AddictedKiD** [comment]
Same problem here..

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by Piklo** [comment]
should be fixed in rev. 5916
