### ISSUE TITLE
[EN][Priest][Hunter] Shadow Word: Death/Kill Shot Glyphs

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7347]
Shadow Word: Death and Kill Shot when glyphed is bugged in the way whenever you smash your keyboard to fire these abilities, you won't be able to fire the first queued spell.

www.wowhead.com/spell=32379/shadow-word-death
www.wowhead.com/spell=53351/kill-shot

**Comment by phifedawg** [comment]
I reccomend two separate tickets for this.. also, have you tried a /cast !kill shot [or !sw:d] macro? it allows you to spam abilities

**Comment by kadi2** [comment]
Haven't tried it yet, gonna check this out in meanwhile.

**Comment by TranceAccount** [comment]
Please confirm.

**Comment by kadi2** [comment]
Cannot reproduce this anymore.
