### ISSUE TITLE
[EN][NPC] Magnus Frostwake

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#7351]
As of cataclysm, [Magnus Frostwake](http://www.wowhead.com/npc=11278/) should be spawned in the blacksmith outside Scholomance, and visible without a trinket. Currently, he can't be seen (at least not without the trinket).

**Comment by DuGalle** [comment]
confirm

**Comment by Aival94** [comment]
Should be outside Scholomance and not Stratholme.

**Comment by tomatosz** [comment]
Oops my bad, edited the original post.

**Comment by Zodex110** [comment]
From the [Gamepedia](http://wow.gamepedia.com/Magnus_Frostwake).
Patch 4.2.0 (2011-06-28):  [Spectral Essence](http://www.wowhead.com/item=13544/spectral-essence) is no longer required to see and interact with [Magnus Frostwake](http://www.wowhead.com/npc=11278/magnus-frostwake).
Confirmed that it's not possibile to interact with the NPC at the moment in the server.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/11485-7351npc-magnus-frostwake/

**Comment by tomatosz** [comment]
As of [rev. 5211](http://atlantiss.eu/changelog#rev5211), where it says this NPC is added, it is not fixed. I can still not see him.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12280-7351npc-magnus-frostwake/
