### ISSUE TITLE
[EN][NPC] Scion of Al'Akir

### ISSUE THREAD

**Issue by karolnpc** [Atlantiss/BugTracker#7352]
Name plates do not appear on these guys. It appears this was fixed in patch 4.0.6 but in our server they still don't appear.

Link to npc - http://www.wowhead.com/npc=45755/scion-of-alakir

**Comment by xmesaj2** [comment]
http://community.atlantiss.eu/index.php?/topic/10780-7352npc-scion-of-alakir/ fix
