### ISSUE TITLE
the mana reg for helares bug not combat reg i'm talking about mana out of combat

### ISSUE THREAD

**Issue by killermommy** [Atlantiss/BugTracker#7353]
when priest use all he is mana reg CD hes mana reg in combat and out of combat be the same
like 4000 mana reg in combat
       4000 mana out of combat

**Comment by crosik** [comment]
what is this pirate language ?

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker
