### ISSUE TITLE
[PL][Quest][Eversong Wood] The Dwarven Spy

### ISSUE THREAD

**Issue by Kantazar** [Atlantiss/BugTracker#7354]
Witam.
Mam problem z tym questem, zostałem z ticketa odesłany na Bugtracker, mianowicie jeden z początkowych questów Blood Elfów jest zbugowany. Misja polega na tym, aby dojść do pewnej wieży i zabić krasnoluda, który tam jest, jednak nie można z nim porozmawiać i doprowadzić do walki. Blokuje to dalszy rozwój fabuły i jedyny sposób na expienie elfa w tym momencie to grind, który nie równa się z przyjemnością

**Comment by SlendyMan0** [comment]
Opis problemu troszkę słaby, więc dodam o co chodzi. Prospector Anvilward powinien znajdować się przed wejściem do wieży. Po rozmowie z nim, powinien wejść do środka i z moba przyjaznego zmienić wrogiego po wejściu na rampę. Parę dni temu (będzie z tydzień) quest jeszcze działał, aktualnie Prospector Anvilward stoi w miejscu w którym powinien się zmieć na agresywnego i nic nie robi.

**Comment by Ryan295** [comment]
I don't understand Polish, but I google translated what they said and it's true. Prospector Anvilward just stands up on top of the ramp and doesn't attack. He just stays green. So I can't finish the quest.

**Comment by martoak** [comment]
I can confirm this

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by Bildo** [comment]
can't reproduce
