### ISSUE TITLE
[EN][quest][Wetlands] The Battle of Thandol Span

### ISSUE THREAD

**Issue by karhima** [Atlantiss/BugTracker#7356]
Calamoth Ashbeard is supposed to spawn in the middle of the bridge, but he is nowhere to be found (I searched the area thoroughly). There's a video guide here: http://www.wowhead.com/quest=26128/the-battle-of-thandol-span

Sadly, without completing the quest, you're not sent to Arathi Highlands and it's blocking further progress there.

**Comment by 1Andas** [comment]
If it's bugged, you can take Hero's Board quest for Arathi from Stormwind or Ironforge for now.

**Comment by karhima** [comment]
The Hero's Board in Ironforge has no quest for Arathi and if you check my provided link to Wowhead you will see that it's a quest series - you need to finish Wetlands first to be sent to Stromgarde.

**Comment by Malylolek** [comment]
Still bug or no ?

**Comment by Navedonar** [comment]
quest works
