### ISSUE TITLE
[EN] [Quest] A Ritual of Flame bugg

### ISSUE THREAD

**Issue by awesometoschi** [Atlantiss/BugTracker#7357]
Hello there , i take A Ritual of Flame quest and it shows 100% ritual progress from the start tho i 

can't complite it , i tried killin tones of mobs , won't help , if i fly away and return it shows 0% ritual 

progress tho killin mobs won't help in this case as well . ingame nickname Bowt

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker
