### ISSUE TITLE
[EN][PRIEST][GOBLIN]  A Seer's Staff

### ISSUE THREAD

**Issue by ligersith** [Atlantiss/BugTracker#7358]
There are two quests by this name, one for Tauren (from Seer Liwatha) and the other for Goblins (Brother Silverhallow).

Currently Brother Silverhallow isn't offering it and so Goblins aren't able to do the quest. It's the same objectives as each of the other Priest class quests but each race can only complete the quest unique to themselves. It should be really easy to enable this one.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12536-7358priestgoblin-a-seers-staff/
