### ISSUE TITLE
[PL][Achievement] That's a lot of bait

### ISSUE THREAD

**Issue by mati865** [Atlantiss/BugTracker#7359]
Guild achievement: [That's a lot of bait](http://www.wowhead.com/achievement=5036/thats-a-lot-of-bait)

1 zlowiona ryba(niezaleznie od lvla, skillu fishingu, posiadanej reputacji w gildii) = 1 ryba do w/w osiagniecia

Jak to obecnie " dziala" ? = dobre pytanie, ryby sa naliczane randomowo, najczesciej nie nalicza tego w ogole a czasami zaliczy 1. Wiele osob wbija achi za 500 ryb(bedac w gildii od samego poczatku lowienia) - w gildii jest wylowione 60.
Jak powinno dzialac? - 1 zlowiona ryba = 1 zaliczana do guild achi

Odnosnie zaliczania innych przedmiotow z fishingu:
Komentarze z w/w linku(wowhead):

"By meene (1,061 – 3·14) on 2010/12/08 (Patch 4.0.3)        
> It says "catch fish" but it also counts Volatile Water fished from schools."

"Pseudo on 2010/12/27 (Patch 4.0.3)
> Confirmed, Volatile water counts towards the achieve (as "1 fish" even if its Water x2)"

**Comment by lameia** [comment]
Moim zdaniem, zalicza dopiero od cataclysmowych fishing pools (najprawdopodobniej ze szkółek)

**Comment by TrueSejten** [comment]
Zalicza tylko z pooli, sam mam zlowione 6k rybek i do gildi wpadlo moze z 500, bo malo z pooli lowilem

**Comment by Malylolek** [comment]
GG - Catch 10,000 fish from fishing pools. a nie z wody

**Comment by Kozakko** [comment]
Ok doszliśmy że powinno się łapać tylko z ławic a co z 2 częścią zgłoszenia?

**Comment by Malylolek** [comment]
Z samego zgłoszenia wynika że wszystko było testowane na openwater i czasami ktoś ze szkółki łowił. Zróbcie test złówcie 50 rzeczy ze szkółek i zobaczcie co zalicza a co nie dokładnie z nich.
