### ISSUE TITLE
[EN][PROFESSIONS][QUEST] Nibbler! No!

### ISSUE THREAD

**Issue by Norbisio** [Atlantiss/BugTracker#7360]
When the stones are being cut sometimes Solid Zephyrites Cut objective don't count, so the quest cannot be completed. When I trying to complete it I'm cutting stones and I have the stones that are useless to me, because I can't finish Cutting objective. I came across this bug twice recently.

**Comment by Aival94** [comment]
I did yesterday this quest in Alliance and did not have such a bug at all.I cut 3 and 3 credits where given to me.

**Comment by Norbisio** [comment]
Still doesn't work properly! I checked yesterday

**Comment by Aival94** [comment]
Did it on Alliance yesterday and was working correct.Which race you are.Horde or Alliance and maybe give your character name will help devs.

**Comment by Malylolek** [comment]
So work or no ?

**Comment by Aival94** [comment]
I have done this one many many times after this report get reported on my Alliance Draenei so i can tell for alliance is working just fine.

He might just was in raid during the quest so even if he cut the gems does not count at all but the gems credit that you have the gems is normally given.

**Comment by Malylolek** [comment]
Thanks for feedback. Close then.
