### ISSUE TITLE
[Dungeon] Shadowfang Keep

### ISSUE THREAD

**Issue by Astagos** [Atlantiss/BugTracker#7362]
The doors and gates of Shadowfang Keep dont open and dont allow the players to proceed to next phases.

**Comment by vesemir22** [comment]
Confirmed. Sfk is bugged. The doors are closed.

**Comment by Bildo** [comment]
fixed

**Comment by zexy024** [comment]
Is bugd again

**Comment by Wolffenstein** [comment]
Wait for rev 5005.
