### ISSUE TITLE
[EN][Achivement]Silithus quest

### ISSUE THREAD

**Issue by Gajulus** [Atlantiss/BugTracker#7365]
I came across a problem with getting this achivment - I can't find anymore quest in Silithus. I' stuck at 13/19. The problem is that I should be eligible for doing more quests according to both wowhead and the Loremaster Addon. 
Both sources show that I shoud be able to access at least 3 quests:
Dearest Natalia (http://www.wowhead.com/quest=8304/dearest-natalia)
The Twilight Mystery (http://www.wowhead.com/quest=8284/the-twilight-mystery)
Unraveling the Mystery (http://www.wowhead.com/quest=8314/unraveling-the-mystery)
and possibly even more.
I havent found on forum if anyone else had similar problem, also Private Status (http://www.private-status.com/39/atlantiss) shows that this achivement should be doable.

**Comment by Sayris9876** [comment]
Same here i did warsong command from orgrimar even took the quest from winterspring (still havent done un'goro to see if there is a chain or something) but for now i am at 13/19 aswell
