### ISSUE TITLE
[EN] [Quest] [Mount Hyjal]  A Ritual of Flame bugg

### ISSUE THREAD

**Issue by awesometoschi** [Atlantiss/BugTracker#7366]
http://www.wowhead.com/quest=29195/a-ritual-of-flame worked perfect for my first char on Atlantiss ,

tho i can't complite it with my alt since when i accpet it progression bar is at 100% and u can't complite 

today i say many people suffering from this bugg as well .

**Comment by Aival94** [comment]
It seems after a restart it get unbugged but this bug might occur again.

**Comment by krashan34** [comment]
Anyone have a fix for this?

**Comment by tomatosz** [comment]
bump

**Comment by thanhtotti** [comment]
bump!

**Comment by Prodiege** [comment]
This quest is broken again

https://github.com/Atlantiss/BugTracker/issues/7357

https://github.com/Atlantiss/BugTracker/issues/7536

**Comment by StarvingMonkeyy** [comment]
This quest has been bugged for at least a week, got 85 about a week ago and it just maxs out at 105/105, explotion happens (which is supposed to kill adds and finish quest) adds keep coming out and npc's stand there clueless. 6 Days behind my daily quests now because nobody wants to slove the problem

**Comment by Dracolucassos** [comment]
BUMP! for god sake

**Comment by fakirakos** [comment]
BUMP!! really needs a fix...completely blocks the molten front area for players

**Comment by BAndysc** [comment]
Should be fixed in rev 5098, let me know if it still bugs

**Comment by sunshitwowsucks** [comment]
still bugged 

edit: managed to do after retake??

**Comment by ko4o** [comment]
Bump, it's still bugged.

**Comment by fakirakos** [comment]
i actually found a way to do it....keep raising the bar to 100 and waiting a couple of minutes....if the event starts you are good....if not just fly away till the bar disappears then fly back and do it again...i got it on my 8th try but others got it anywhere from the 2nd to the 15th so its most likely the event trigger needs smth very specific to activate

**Comment by TheCroak** [comment]
I'm still trying to do the quest and I'm not able to complete it, therefore no Molten Front.
When will it get fixed?
