### ISSUE TITLE
[EN][Raid][FL][NPC][Lord Rhyolith]

### ISSUE THREAD

**Issue by EnPra** [Atlantiss/BugTracker#7368]
Does it feel kinda old to have Rhyolith on every page of bugtracker?
Guess not...
We wiped during testing the ''new rhylolith'' and now we cant enter for more than 15 minutes, no shaman totems, no banners or guild banks. This problem has been around for months, it also happened on beth'tilac with banner up. For the love of god just fix him already. Its already hard enough to keep ppl playing fl while waiting for fl hc.

**Comment by EnPra** [comment]
update: after waiting for 15 min we took resurrection sickness and reset the instance, still waiting.

**Comment by ponpontos** [comment]
As if T11 being absolutely fucked wasn't enough, now even which is supposedly the "focus" of the dev team FL is a mess as well.

Have fun raiding in this server.

**Comment by Wolffenstein** [comment]
We need more information, specifically about reproducing the bug.

**Comment by EnPra** [comment]
@Wolffenstein 
Sry but after 25 minutes of waiting the raid fell apart, cant provide any further information.
The bug is not unknown, saw it on atleast 2 other threads. Rhyolith has troubles reseting after a wipe

**Comment by Bildo** [comment]
If this issue is reported in 2 defferent threads then why making another one?

**Comment by EnPra** [comment]
@Bildo to bring it to devs attention so it gets resolved and also to see if other players faced the same problem. There were many rhyolith updates recently so im not sure if they know that the bug still persists. But sure, sweep it under the rug

**Comment by LaveniaGithub** [comment]
It is not about sweeping it under the rug or not, it is about not having a BugTracker that is filled with duplicates, which at some point will make it hard to keep organized.
