### ISSUE TITLE
[PL][Class][Paladin][Talent] Divine Purpose

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#737]
Link do talentu: http://cata.openwow.com/spell=86172
Link do buffa: http://cata.openwow.com/spell=90174
Link do Divine Storm: http://cata.openwow.com/spell=53385

Jak powinien działać: Następujące spelle mają szansę na to, aby zaaplikować nam buff, który sprawia, że następny Holy Power ability nie zużyje Holy Power oraz udeży/uleczy/buffnie z mocą odpowiadającą 3 stackom Holy Power.

Jak działa: W większości poprawnie, jednak buff, który ten talent nam daje jest konsumowany również przez Divine Storm, który nie jest Holy Power ability.

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
