### ISSUE TITLE
[PL][Raid][Firelands] Beth'tilac

### ISSUE THREAD

**Issue by Kozakko** [Atlantiss/BugTracker#7370]
Beth'tilac http://www.wowhead.com/npc=52498/bethtilac

1.Często po wipie Beth pojawia się trochę za nisko przez co wizualnie boss ryje głową w ziemi.
2. Meteor Burn (http://www.wowhead.com/spell=99076/meteor-burn). Spell sam w sobie działa dobrze ale jego efekt (rozerwanie sieci) jest wg mnie trochę za duży w stosunku do animacji ognia. Spaść można z większego range niż się powinno, niewiele ale jednak.
3.Cinderweb (Spinner http://www.wowhead.com/npc=53642/cinderweb-spinner) Bardzo często pojawiają się dokładnie w tym samym miejscu, niejednokrotnie spawniąc się 2x w tym samym miejscu jednocześnie co potrafi nieco uprzykrzyć encounter. Na poradniku tankspot (https://www.youtube.com/watch?v=hqYmX96ZxFU) widać między 1:48 a 1:55 że pinnery mogą się pojawić blisko siebie ale nigdy nie pojawiały się dokładnie w tym samym miejscu. 
4. Venom Rain (http://www.wowhead.com/spell=99333/venom-rain). tutaj jest tylko niesprawdzona do końca informacja. Da się znaleźć takie miejsce na ziemi stojąc na którym nie dostajemy w ogóle dmg od beth czyniąc ten encounter znacznie łatwiejszym,
5. Boss czasem korzysta ze zwykłego systemu aggro na początku encountera. Zdarza się że po wejściu na górę schodzi na dół by uderzyć jakiegoś castera który zadał mu spory dmg. Taktyczny taunt i wejście tanka na górę razem z beth często naprawia sprawę.
Edit. Ad 4. bug potwierdzony da się znaleźć takie miejsce.

**Comment by EnPra** [comment]
From what i understood from google translate i can confirm that Beth'tilac hangs a bit low with her head under the texture and also that sometimes she can stay bugged on top during phase 2 (sending the tank up and down fixes it though). Can also confirm that the range of holes in her nets got a lot bigger(not sure if intended or not). And if i understood the 3rd problem correctly, we also had issues where 2 spinners spawned on the exact same spot causing the healer to be unable to climb up until the second pack of spinners comes down.

**Comment by Kozakko** [comment]
Ad 2. https://www.youtube.com/watch?v=WeKSHgBIX54 między 0:15 a 0:25 widać ładnie jak tank po wybuchu meteoru podchodzi bardzo blisko pod jego krawędź.

**Comment by jissabraham** [comment]
plz dont try to fix it its working fine

**Comment by arekczup** [comment]
Cinderweb Spinners will spawn in random positions 
ostatnio to naprawili ale nie robiłęm jeszcze po tym updatu tego bosa

**Comment by Aival94** [comment]
are not these bugs fixed?

**Comment by Malylolek** [comment]
Many fix just test and make new issues if something still bug ther.
