### ISSUE TITLE
Problem with installation (Error 134)

### ISSUE THREAD

**Issue by Sylweq90** [Atlantiss/BugTracker#7371]
Hi guys. I'm loosing hope with that game to be honest. I've been trying since few days to install wow on my computer but every time something is wrong. I've downloaded game from atlantiss, exe file as well. Yesterday I tried to play and it was working. I've been playing for few hours. But today something was wrong. I deleted everything and downloaded WoW again from atlantiss.eu but all I see is this:
![wow error](https://cloud.githubusercontent.com/assets/19170412/15080420/e42d928c-13b5-11e6-96a3-0cd25da42d25.png)

Please help me. I really love this game and I missed it. I would like to play again but don't know how.

Regards,

Syl

EDIT:

I've been trying to use advices from youtube: https://www.youtube.com/watch?v=2Sb94BZtz3A
also advices from forum:
"In case you did not already do this, then try:
- Get this:
http://www.mediafire...4tngd77ocktend/
Extract it in WoW folder and overwrite "WoW.exe", "WoW.mfil" and "WoW.tfil".
- Thrn right click "Data" folder, choose Properties, and there, click box in front of "Read-only". When box is empty, click Ok and when promted, choose for all files, folders and subfolders. After that confirm again.
- Delete Cache folder in WoW folder, not in Data."

but unfortunately nothing is working...

I'm asking for help please!

**Comment by stanq87** [comment]
its all there, u point the game to download mfli file or mfil data from localhost, change that or download a full client by torrent

**Comment by pelekon** [comment]
Pro tip bt(Bug Tracker) is using to report bugs which occuring on server not to disscus about players problems with client.

**Comment by Sylweq90** [comment]
Pelekon I'm sorry I just didn't know when I can ask for that kind of help. 

stanq87 I've already tried that and it's still not working. Well, it's better because now I can see the page but still can't log in:
"The information you have entered is not valid"  - That's what I see now. And server name is "Atlantiss Main" (Yesterday when it was working serwer name was something like: dragonpath (not sure)

**Comment by JamesSinger94** [comment]
I fixed this issue by placing in the root of C:\ instead of C:\Program Files

Using Windows 10 Pro 64bit

**Comment by hudy1431** [comment]
Delete this 3 files from data named wow base something. Then uncheck only to read on wow folder,data folder and wow.exe . worked for me

**Comment by Bildo** [comment]
bugtracker its not a place for these things
