### ISSUE TITLE
MiniClient - UI - Setting/changing realm is not possible.

### ISSUE THREAD

**Issue by Gethath** [Atlantiss/BugTracker#7372]
After longer break i was not able to set the Dragonwrath realm, so i tried Public Test realm. It worked. However i am still not able to change it for Dragonbreath. 
It freezes for a second here:
![screen1](https://cloud.githubusercontent.com/assets/19231849/15087934/ffcd56fc-13ed-11e6-8ccf-776c99db2af6.jpg)

and then comes back here:
![screen2](https://cloud.githubusercontent.com/assets/19231849/15087943/0cfa5eec-13ee-11e6-96af-05359df1765b.jpg)

Any sollution for this issue?

Note:
These are log lines captured with few tries.

5/7 00:58:10.976  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
5/7 00:58:11.037  GRUNT: state: RESPONSE_CONNECTED result: LOGIN_OK 149.202.66.176:3724
5/7 00:58:11.078  GRUNT: state: LOGIN_STATE_AUTHENTICATING result: LOGIN_OK 
5/7 00:58:11.137  GRUNT: state: LOGIN_STATE_CHECKINGVERSIONS result: LOGIN_OK 
5/7 00:58:11.233  GRUNT: state: LOGIN_STATE_HANDSHAKING result: LOGIN_OK 
5/7 00:58:11.269  GRUNT: state: LOGIN_STATE_AUTHENTICATED result: LOGIN_OK 
5/7 00:58:11.269  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
5/7 00:58:12.458  ClientConnection Completed: COP_CONNECT code=RESPONSE_FAILED_TO_CONNECT result=FALSE
5/7 00:58:14.074  ClientConnection Completed: COP_CONNECT code=RESPONSE_CANCELLED result=FALSE
5/7 00:58:14.074  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
5/7 00:58:15.240  ClientConnection Completed: COP_CONNECT code=RESPONSE_FAILED_TO_CONNECT result=FALSE
5/7 00:58:16.225  GRUNT: state: LOGIN_STATE_DISCONNECTED result: LOGIN_OK

**Comment by pelekon** [comment]
Pro tip bt(Bug Tracker) is using to report bugs which occuring on server not to disscus about players problems with client.

**Comment by Gethath** [comment]
It is linked with server, sorry maybe description is missleading. Moveover even if it is client issue - this is Atlantiss's client, desined by them to connect to their realms so why not fix client issues here?

**Comment by Gethath** [comment]
I think it was some connection issue.. It's working good now anyway. I am closing.
