### ISSUE TITLE
[EN][NPC][Howling Fjord] Fjord Penguin

### ISSUE THREAD

**Issue by jissabraham** [Atlantiss/BugTracker#7373]
unable to find them anywhere 
www.wowhead.com/npc=28407/fjord-penguin

**Comment by Vidyapoky** [comment]
I found them perfectly fine standing on top of santa 23/72 cordinates in howling fjord

![wowscrnshot_051716_184521](https://cloud.githubusercontent.com/assets/1499989/15331033/a35ac092-1c5f-11e6-99ff-c19773274d90.jpg)
