### ISSUE TITLE
[EN][Mount] Swift Gryphon

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#7374]
Swift Gryphon running animation is slower than rare Gryphon running animation. While I was playing on another server, Swift Gryphon and rare Gryphon had the same animation speed. Someone needs to speed up the Swift Gryphon running animation. The same issue with Armored Snowy Gryphon.

**Comment by Jenovas** [comment]
Please Please create a report with a video atleast or something from our server + any kind of evidence (video on youtube or something).

If I wanted to fix this I need now I would need to go in game, I need to look at one mount, the second mount, find a video with one mount, second mount, try to compare them to eachother, compare to the videos and see if this bug really exists or not  -  after all this I can eventually try to fix it.

**Comment by cubson** [comment]
Watch this movie from 0:45
https://www.youtube.com/watch?v=fiLiJeCQsWg
