### ISSUE TITLE
[EN][Paladin][Spell] Holy radiance

### ISSUE THREAD

**Issue by bonibo** [Atlantiss/BugTracker#7376]
Greetings,
I believe holy radiance for holy paladins is not working as it should, numbers-wise.
I took all my gear off and slowly added it back piece by piece. 
The result was the same, regardless of intellect/spellpower: ~3.2k to ~3.8k direct heal and ALWAYS a 610 hot.  The only things that seemed to affect the hot were things like the conviction talent (that increases your output by a flat X%).
I believe holy radiance as it is does not account for intellect/spell power (buffing int/sp naked with flask/buffood had no effect either).

How to replicate: take a level 85 holy pala naked, use holy radiance. Then give him BiS gear (or any kind of int/sp gear really) and see the same numbers (especially obvious on the hot part).

wowhead link: http://www.wowhead.com/spell=82327/holy-radiance
opencata:. http://cata.openwow.com/spell=82327

P.S. i checked as much as i could for a similar report and i only found (https://github.com/Atlantiss/BugTracker/issues/3639) which handles a different matter entirely. this is my 1st report here, so i apologize if i fucked up.

**Comment by aneq** [comment]
radiance is also incorrectly transferred to beacon

**Comment by Andamarokk** [comment]
This is more of a question (cant find any evidence for/against it), but i think it shouldnt proc protector of the innocent for every target it hits?

**Comment by Piklo** [comment]
@lamaATS  , can you look on this bug?

**Comment by lamaATS** [comment]
Ofc I can but probably I need to ?buy? some more time I'm unable to fix everything in one day and I want to make some fixes to all classes (balance fixes).

**Comment by lamaATS** [comment]
I checked this now and I have to rework completely all spells that use **Holy Power** because I want write once and make all spells works in simply way.

**Comment by Psychobird7** [comment]
@lamaATS are you only reworking their mechanics or the scalings as well?

**Comment by lamaATS** [comment]
First I will rework all holy power because now each spell has own spell which consuming this power but I can be move to spell system and take all holy power and just save how many power has been consumed and this number can be used in spellscript to calculate proper damage/heal because this think can't be normalized for all spells.

**Comment by lamaATS** [comment]
**Holy Radiance** using 2 spells, first one is a initial healing and buff and the second one is a heal for each tick problem was that those spells didn't had any coeff (unknown reason) now I have it fixed (local server) and values are perfectly the same like in game tooltip.

**Comment by lamaATS** [comment]
Fixed in rev. 5236
