### ISSUE TITLE
[PL][Core] Auto attack / Attack table

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#7378]
wydaje sie gdzies  wkradl sie blad co do  decydowania kiedy atack jest  missem critem a normalem

cala teoria przyklady i dane sa pod  Auto attack, nie pod skile spele itd itp

Wzory i teoria:
http://wowwiki.wikia.com/wiki/Attack_table
http://wow.gamepedia.com/Attack_table
http://wowwiki.wikia.com/wiki/Critical_strike
http://wow.gamepedia.com/Combat_rating_system

Podstawa:
a) - tabela - kazdy atak na celu jest przeciagniety przez staty i lvl celu i atakujacego, w ponizszej kolejnosci
Miss --> Dodge --> Parry --> Glancing Blow --> Block --> Critical hit --> Crushing Blow --> Ordinary hit 
a2) jesli  cel i atakujacy sa  na tym samym lvl  i zakladajac ze atakujacy ma wszystkie ofensywne capy
Parry --> Block --> Critical hit -->Ordinary hit 
a3) zakladajac ze cel nie ma blocka - tarczy lub temu podobnego
Parry --> Critical hit -->Ordinary hit 
a4) zaklaajac ze  atakujacy zadaje obrazenia od plecow (nie dziala wtedy parry dodge block)
Critical hit -->Ordinary hit 

CZYLI
atakujac cel od plecow na tym samym lvl z capami ofensywnymi  nasz atak jest sprawdzany 
czy jest critem a jak nie to  zadane sa normalne ataki

ale wyjatkami sa:
Glancing blow 24% szansy  tylko na mobach wyzszych o nasz level lub bosach (dziala tylko na "biale obarazenia)
redukcja crita: o 1% za kazdy lvl moba nad nami

[http://i.imgur.com/nkrqH1j.jpg](http://i.imgur.com/nkrqH1j.jpg)
powinno byc 16,04 crit jest 14,7
[http://i.imgur.com/xkDTlS2.jpg](http://i.imgur.com/xkDTlS2.jpg)
powinno byc 39 jest 38
[http://i.imgur.com/ph4ooga.jpg](http://i.imgur.com/ph4ooga.jpg)
powinno byc 7,13 a jest 6,1
[http://i.imgur.com/IqJixYO.jpg](http://i.imgur.com/IqJixYO.jpg)
5,56 a  3
[http://i.imgur.com/8eRqfrz.jpg](http://i.imgur.com/8eRqfrz.jpg)
19,66 a 19,2

sprawdzane na feralu rogalu wariorze   na kukle  bossowej od tylu

**Comment by mati865** [comment]
Linki wstawia się tak: `[wyświetlony_tekst](link)`, teraz linki nie są klikalne.

Serwer prawdopodobnie generuje liczby pseudolosowe programowo. Co z natury nie da idealnej losowości.
Jedyny sposób by zniwelować wpływ niedoskonałości algorytmów to przeprowadzenie dużej liczby testów (10k melee dopiero daje jakiś wgląd) przez kilka dni.
Oczywiście można stosować tzw. Shuffle Bag i uzyskiwać wyniki zgodne z obliczeniami lecz wtedy wyniki będą mniej losowe co trochę nie pasuje do WoW'a który w każdym aspekcie zależy od RNG (no dobra od WotLK losowość dropienia quest itemów jest mocno ograniczona).

**Comment by stanq87** [comment]
tak i dlatego tez jak to sprawdzalem to pula testowa miala od 5 do 10m dmg,  dodam tez ze tego samego typu sprawdzanie na magu spriescie czy ele wykazalo 99,9% zgodnosc z tym co powinno byc

**Comment by Jenovas** [comment]
redukcja crita: o 1% za kazdy lvl moba nad nami
Crit supression wynosi 1.6% za każdy lvl.

Zamykam.
