### ISSUE TITLE
[EN][Quest][Northrend] That's What Friends Are For...

### ISSUE THREAD

**Issue by Karathe** [Atlantiss/BugTracker#7379]
Approaching quest NPCs does not change objectives status to "Complete". This bug makes completing that quest impossible.

For more data how this quest should work: http://www.wowhead.com/quest=12903/thats-what-friends-are-for

**Comment by Dranerys** [comment]
Confirmed. Also, by not being able to complete this quest a big part of other quests in Zul'drak become unobtainable.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3474
