### ISSUE TITLE
[EN][Quest][Dustwallow Marsh] Prisoners of the Grimtotem

### ISSUE THREAD

**Issue by Alinna99** [Atlantiss/BugTracker#7381]
Prisoners of the Grimtotem quest is bugged, all the cages are open so releasing the prisoners can't be completed. 

This is how it is supposed to go.

https://www.youtube.com/watch?v=JjMaUT6voSg

WowHead

http://www.wowhead.com/quest=27245/prisoners-of-the-grimtotems

Please fix this!

Thanks!

**Comment by TheCopacabanaMan** [comment]
Bump! +1

**Comment by aniviaegg** [comment]
May 7 issue open and September 21 and still bugged, sad ;-;

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
http://community.atlantiss.eu/index.php?/topic/13271-gameobject-blackhoof-cages/

**Comment by Thunderlmao** [comment]
As of 16/04/2017 this quest doesn't work. The cages are already open so you cannot free the NPCS. It's usually because another player has done the quest.

**Comment by Hernajs** [comment]
Bump. Still doesn't work.
