### ISSUE TITLE
[EN][Raid][Firelands] Lord Rhyolith rev. 5001

### ISSUE THREAD

**Issue by Kaldros** [Atlantiss/BugTracker#7382]
After the recent fixes, most of the stuff is working correctly, however, he is still bugged.

1. He doesn't lose stacks of Molten Armor on his body, only on his feet.
(http://www.wowhead.com/spell=98255/molten-armor)
In the first phase it works as intended, he gets them and lose them as he should but then he hits the second phase and it seems like he didn't lose any of the stacks.
For example at 26% he has 5-6 stacks on his feet, then he enters second phase and he has 20-25.
This is incredibly hard to survive because he does the stomp right away and deals around 80-90k damage per person, sometimes even more.

2. Too much damage from the stomps.
Sometimes he deals too much damage with a stomp. Usually close to the second phase. For example:
Note that the player has 3 stacks of Eruption and he gets hit for 125000 damage. He barely has around 120k max hp to start with.
![ryo1a](https://cloud.githubusercontent.com/assets/15013668/15094657/70ea20aa-14ab-11e6-8894-d74bd018734a.png)
And this was a tank, he had 9 stacks of Eruption.
![ryo2b](https://cloud.githubusercontent.com/assets/15013668/15094671/0815e2ac-14ac-11e6-8892-ed0798bf1a63.png)

**Comment by Kozakko** [comment]
Do you have world of logs? i don't know the addon that you use but if i get it right, on the first screen player have 3 different eruption debufs and i really dont know how many stacks of each one of them. The same situation with 2nd screen (2 sources)

Ps. Hint, If you have 5+ stacks of eruption debuf from one source you can always run away as far as you can from active volcano and reset them. Volcanos shots in the air 3 quite big magma balls and if you are far enough travel time > lenght of debuf on you.

**Comment by Kaldros** [comment]
Here is world of logs, I just uploaded it: http://www.worldoflogs.com/reports/2yl9fu2ge58khb3g/

**Comment by Kozakko** [comment]
Well here i think this is the source of that incredible damage http://www.worldoflogs.com/reports/2yl9fu2ge58khb3g/spell/101304/?s=9117&e=9698. In each one of your fights you spend more than 6 minutes of encounter. After 6th minute bos gain 1 stack of superheated debuff every 10 s.

**Comment by Kaldros** [comment]
That's definitely the issue then. That renders both of my reported bugs false.
I'll close this bug report as the problem was most like on our side. Thank you for pointing this out.
