### ISSUE TITLE
[EN][Quest][Northrend] It's All Fun and Games

### ISSUE THREAD

**Issue by Karathe** [Atlantiss/BugTracker#7386]
Quest target "The Ocular" deal to big damage (over 5000 per attack). On level 85 I was unable to kill it with quest item because I was getting killed by the target. In addition, sometimes when quest item is being used damage isn't dealt at all. I suggest reducing targets attack damage or increasing damage dealt by quest item.

For more data how quest should work: http://www.wowhead.com/quest=12892/its-all-fun-and-games

Video showing how quest works: https://www.youtube.com/watch?v=j-7v3yAF29k

**Comment by Luna-maria** [comment]
#1819
