### ISSUE TITLE
[EN / PL][Quest / NPC][Deepholm] Therazane's Mercy

### ISSUE THREAD

**Issue by kjmpp** [Atlantiss/BugTracker#7389]
[EN] For some time the High Priestess Lorthuna cannot be attacked. She has also gray name. U can see it on the picture. Server uptime is more than 2 days, maybe after restart it becomes normal...

[PL] Od jakiegoś czasu nie da się zaatakować mobka "High Priestess Lorthuna". Ciągle widnieje na szaro i nic na nią nie działa, a jeszcze bodajże tydzień temu wszystko było w porządku. Załączony obrazek. Serwer stoi już ponad 2 dni, być może po restarcie wszystko będzie działać jak należy...

![wowscrnshot_050916_141925](https://cloud.githubusercontent.com/assets/16562793/15113348/0432d21e-15f4-11e6-9c97-3aed1ed46547.jpg)

**Comment by Aival94** [comment]
Better make a comment here with the first report: https://github.com/Atlantiss/BugTracker/issues/2137

**Comment by kjmpp** [comment]
I've done this quest 5 time's on Atlantiss and always it worked perfectly, except this one little bug. After restart it works again! :). U can close this issue topic.
