### ISSUE TITLE
[PL][Class][Paladin][Talent] Grand Crusader

### ISSUE THREAD

**Issue by Glare** [Atlantiss/BugTracker#739]
Link do talentu: http://cata.openwow.com/spell=85043
Link do buffa: http://cata.openwow.com/spell=85416
Link do umiejętności(opis jest niewłaściwy ale innego nie znalazłem): http://cata.openwow.com/spell=31935

Jak powinien działać: Gdy Crusader Strike i Hammer of the Righteous zadają obrażenie głownemu targetowi mają szansę na zresetowanie CD umiejętności Avenger's Shield oraz powodują, że Avenger's Shield użyty w ciągu kolejnych 6 sekund zaaplikuje nam stack Holy Power.

Jak działa: W większości poprawnie, jednak 6 sekundowy buff, który otrzymujemy jest konsumowany właściwie przez wszystkie umiejetności, które zadają obrażenia. Trzeba też zaznaczyć, że wszystkie umiejętności które zużyją dany buff nabijają nam stack Holy Power.

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
