### ISSUE TITLE
[ENG][Quest][Feralas] General Shandris Feathermoon

### ISSUE THREAD

**Issue by karhima** [Atlantiss/BugTracker#7393]
Not able to complete since the NPC is missing. She should be here: http://www.wowhead.com/quest=26402/general-shandris-feathermoon (screenshot). In case she has been killed, I've been waiting, she hasn't respawned.

**Comment by Aival94** [comment]
I believe the npc has a huge respawn time which is the bug.

**Comment by Navedonar** [comment]
![wowscrnshot_092216_112753](https://cloud.githubusercontent.com/assets/1525533/18743212/41275bde-80b8-11e6-82f8-b9ebd0056888.jpg)

**Comment by Navedonar** [comment]
fix respawn time http://community.atlantiss.eu/index.php?/topic/11664-7393npcshandris-feathermoon/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
