### ISSUE TITLE
[EN][Quest][Ironforge]I Need to Cask a Favor

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#7396]
http://www.wowhead.com/quest=29356/i-need-to-cask-a-favor

Cask isnt even spawn

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7144

**Comment by ofelia59** [comment]
I have the same problem on 7.07.2016  [I Need to Cask a Favor] - no any cask to take
