### ISSUE TITLE
herb. Nodes missing

### ISSUE THREAD

**Issue by hudy1431** [Atlantiss/BugTracker#7397]
Hi. There is a lot of herb nodes missing. Stv and tanaris should have some but they are empty. I was camping stv sea for few hours and nothing. Could u please add them in the right places?

**Comment by cubson** [comment]
Title should look like this [EN][Object] Herb nodes

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker
