### ISSUE TITLE
[EN][Quest][Tanaris] On a Wing and a Prayer

### ISSUE THREAD

**Issue by Isdisbase** [Atlantiss/BugTracker#7399]
Basically the Quest Item is not spwning to loot.

After finishing the Quest http://wowwiki.wikia.com/wiki/Quest:All-Seeing_Eye Anachronos should start to create the Timeless Eye which you have to Loot at the following Quest http://wowwiki.wikia.com/wiki/Quest:On_a_Wing_and_a_Prayer.

WoWwiki Link StartQuest of Questline: http://wowwiki.wikia.com/wiki/Quest:A_Wrinkle_in_Time

Whole Questline in Retail Videos after collection the Questitems for Quest:All-Seeing Eye.

All important Sruff for the Questline is shown theire in good Quality.
Part1: https://www.youtube.com/watch?v=H2tukB6yp0M
Part2: https://www.youtube.com/watch?v=y8F1HTLz9yg
Part3: https://www.youtube.com/watch?v=mY2e7Bsdt38
Part4: https://www.youtube.com/watch?v=_Tli3qHsCDM

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/5740
