### ISSUE TITLE
[EN][Hunter][Spell] Deterrence

### ISSUE THREAD

**Issue by ShockRW** [Atlantiss/BugTracker#74]
1. Deterrence http://www.wowhead.com/spell=19263/deterrence Doesn't provide 30% damage reduction. 
   Patch 4.3.2 (31-Jan-2012): Deterrence now also reduces damage taken by 30% while active.
   Source: http://www.wowwiki.com/Deterrence
2. Warrior's Charge / Intercept stun bypasses Deterrence. Despite having active Deterrence I still get stuned by Warrior's Charge or Intercept etc.

**Comment by Kejmil** [comment]
deterrence still don't drop flag when used with it

**Comment by Jenovas** [comment]
deterrence still doesn't drop flag when used with it - should work for a while already

**Comment by lamaATS** [comment]
Fixed in rev. 5232
Warrior's **Charge** has been fixed.
Warrior's **Intercept** was working properly.
