### ISSUE TITLE
[PL][Quest][Deepholm] Take Him to the Earthcaller 

### ISSUE THREAD

**Issue by zgrabol** [Atlantiss/BugTracker#7400]
Take Him to the Earthcaller
wowhead:http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller
nie ma mozliwosciu ukonczenia questa. po dotarciu z npc do "konca trasy" nic sie nie dzieje

**Comment by Aival94** [comment]
When i did it(around a week ago) i just did it just fine.Was waiting for the event with the npcs speaking and i completed it just fine.

**Comment by stanq87** [comment]
yea it worked awhile ago, now its bugged,  u can stand there and wait till u die

**Comment by sigmundfreud2016** [comment]
https://www.youtube.com/watch?v=kmfbqxP9Mv8

**Comment by xmesaj2** [comment]
rev. 5417 fixed
