### ISSUE TITLE
[EN][item]cloak-of-coordination

### ISSUE THREAD

**Issue by jissabraham** [Atlantiss/BugTracker#7401]
The NPC shay pressler is suppose to sell  cloak-of-coordination to guild people who has [Master Crafter] ach but the npc currently dont sell it.
http://www.wowhead.com/item=65360/cloak-of-coordination

NPC which sells http://www.wowhead.com/item=65360/cloak-of-coordination

**Comment by Anhaeyn** [comment]
"This item can be purchased from a Guild Vendor upon earning the guild achievement  Master Crafter and reaching **Revered** reputation with your guild."

Are you revered with guild?

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4947
