### ISSUE TITLE
[EN][NPC][Icecrown Citadel] Deathbringer Saurfang

### ISSUE THREAD

**Issue by Digglewiggle** [Atlantiss/BugTracker#7402]
The 4th boss in Icecrown Citadel is quiet bugged. The event is working fine when it comes to attack the boss he's interacting with damage but instantly goes evade like there was a wipe.
http://www.wowhead.com/npc=37813/deathbringer-saurfang
It makes him impossible to kill.

**Comment by Porobiony** [comment]
https://github.com/Atlantiss/BugTracker/issues/5935
