### ISSUE TITLE
[ENG][The Maelstrom] I died in "the  Maelstrom" what i can do ? :( 

### ISSUE THREAD

**Issue by Ginomen** [Atlantiss/BugTracker#7403]
Dear GM,
i have a question :) 
Can you teleport me to the Maelstrom ? 
I fell down to the water and woke up at westfal. Now i dont ktow how to get there becous there is no portal in stormwind any more. 
i died in "The Maelstrom" at 3:00 pm ( in poland ), My name is Madderin, lvl 82 and login to the wow is Ginoman 
I hope you can help me :) 
your feithfully Rafal From Poland :) 

Sorry for my English :)

**Comment by stanq87** [comment]
write a ticket  in game and wait, up to 2 weeks  :D

**Comment by cubson** [comment]
Login to atlantiss.eu, go to Shop Panel>Account and characters and use unstuck.
