### ISSUE TITLE
[EN][NPC]Murloc Forager

### ISSUE THREAD

**Issue by user1011** [Atlantiss/BugTracker#7406]
**What is bugged:**
Murloc Foragers their health is too low at Stone Cairn Lake in Elwynn Forest.

**Comment:**
I'm not sure what their health is supposed to be, but it is at 73 at level 9 and 82 at level 10. 
They are way too easy to kill compared to the Murloc Lurkers, which have 176 health at level 9 and  198 health at level 10.
![image](https://cloud.githubusercontent.com/assets/13118481/15260760/ec86a268-1958-11e6-851b-fae984640fe6.png)

**Sources:**
http://www.wowhead.com/npc=46/murloc-forager
http://wowwiki.wikia.com/wiki/Murloc_Forager <- Quite unreliable because the health numbers aren't exact.

**Comment by xmesaj2** [comment]
Possible other values:
141 or 396 lvl10
120 or 352 lvl9
but it's data from WoD or MoP, because videos I watched are dated 2014+ and stats are different

Foragers on vids had the same health amount as Lurkers so it could just be the same on Cata that foragers need to be adjusted to same values as Lurkers have currently.

**Comment by user1011** [comment]
> Foragers on vids had the same health amount as Lurkers so it could just be the same on Cata that foragers need to be adjusted to same values as Lurkers have currently.

I believe all level 9 creatures, except non-rare or modified quest creatures, should have the same health points. A prowler in this area at level 9 has 176 health, and stated above 

> the Murloc Lurkers, which have 176 health at level 9

Your claim 

> Foragers on vids had the same health amount as Lurkers so it could just be the same on Cata that foragers need to be adjusted to same values as Lurkers have currently.

is correct from my part.

**Comment by user1011** [comment]
The Murloc Foragers have the same amount of health as the Murloc Lurkers on Trinity core. So the health of the Foragers at level 9 should be 176 and at level 10 it should be 198.
