### ISSUE TITLE
[EN][Quest] Anvilmar the Hero

### ISSUE THREAD

**Issue by kuba22277** [Atlantiss/BugTracker#7407]
http://www.wowhead.com/quest=26327/anvilmar-the-hero

NPC you're supposed to talk with is not interactive, and consequently breaks the quest chain for Dwarves.

**Comment by qndziu** [comment]
Had a same problem but in a moment the anvilmar appeared with question mark and i finished the quest and i proceeded the quest chain

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7182, https://github.com/Atlantiss/BugTracker/issues/3925
