### ISSUE TITLE
Unable to refund item

### ISSUE THREAD

**Issue by alucard994** [Atlantiss/BugTracker#7408]
Few days ago I bought gloves with valor points... As soon as I bought them I realized that I bought wrong ones... And when I wanted to refund them I was unable to... I didn't put any gem or enchant on them... Is there any way to get valor points back or get gloves I actually need (Obsidian Arborweave Handwraps) ?

Thank you in advance!
                                          Pawnerka

**Comment by xmesaj2** [comment]
Refund been working for me, it shows sell price in gold but when you right click item to sell it it will show refund window.

**Comment by alucard994** [comment]
Yeah I know... But when I tried to do it it said "Unable to refund item" ... And when I reloged I was only getting golds if I sell item... :S

**Comment by xmesaj2** [comment]
Maybe the time in which your refund was possible ended? BTW Look bugtracker rules and fix your report or it will be closed. Meanwhile contact support. It's not the place for dealing with players lost items but server bugs, yet the server rules say they are not returning lost goods.

**Comment by alucard994** [comment]
As I said in 1st post... As soon as I bought them I tried to refund them... And if being unable to refund items is not server bug then I don't know what is...

**Comment by xmesaj2** [comment]
It may be bug, but never heard of it before, maybe someone can confirm?


> Is there any way to get valor points back or get gloves I actually need (Obsidian Arborweave Handwraps) ?

I meant this should go to support, not to bug report.

**Comment by alucard994** [comment]
Well... The GM told me to report here so I don't know really...
