### ISSUE TITLE
[PL][Spell][Paladin] Seal of Insight

### ISSUE THREAD

**Issue by Brightflame** [Atlantiss/BugTracker#741]
http://cata.openwow.com/spell=20165

Jak działa: Działa jak na 4.0.6(tzn nadal jest zbugowany). Bijąc samymi melee atakami procuje raz/dwa razy na minutę.

Jak powinno działać: 

"The proc rate on the heal is 15ppm. This means that with a 2.6speed weapon it's heal proc is 65%, and with a 2.8 it procs 70% of the time. A 3.8second weapon will proc 95% of the time.

Haste and reckoning do not change the proc rate."
źródło: http://www.wowhead.com/spell=20165/seal-of-insight#comments

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.
