### ISSUE TITLE
[PL] ERROR #134

### ISSUE THREAD

**Issue by PRESTION** [Atlantiss/BugTracker#7412]
mam problem na helfire moja postać lata non stop od jednego punktu do drugiego podczas lotu dostaje bugsplata z errorerem 134 dodam ,ze nie moge nic zrobic z postacią bo caly czas lata
jakieś pomysły co z tym zrobić ?
![asdf](https://cloud.githubusercontent.com/assets/19373298/15274486/01767256-1ab3-11e6-8ebd-0aa8f9e44312.png)

**Comment by PRESTION** [comment]
![exde](https://cloud.githubusercontent.com/assets/19373298/15274505/cc6a4cbc-1ab3-11e6-9711-5d9ba5faa505.png)

**Comment by Kozakko** [comment]
Opcja unstuck? i od kiedy bt jest do takich zgłoszeń?

**Comment by PRESTION** [comment]
teraz nawet mi do gry nie chce poloczyc :)

**Comment by PRESTION** [comment]
w sensie widzisz drugiego screena przy ladowaniu do gry wyskakuje error :)

**Comment by Kozakko** [comment]
Zaraz i tak zamkną zgłoszenie bo ma się nijak do serwera. Masz jakiś problem z klientem wowa. Szukaj pomocy na forum gdzie opisano już xxxx takich przypadków.

**Comment by arekczup** [comment]
http://community.atlantiss.eu/index.php?/topic/3865-how-to-fix-error-132-and-error-134/
pisze jak naprawić.

**Comment by PRESTION** [comment]
Up
dziękuje narazie odinstalowalem wowa i pobieram go od nowa bo już troche godzin minelo a bylem bezradny unstuckowalem juz postac jak wyskoczy dalej blad to spróbuje coś zrobić , to jest dosyc dziwne jakies 40 sekund moglem znajdowac sie na hellfire i pozniej wyskakiwał błąd i tak za kazdym razem

**Comment by Tetriandoch** [comment]
Miałem podobny problem. Usuniecie folderu WTF pomogło

**Comment by stanq87** [comment]
z tego co tam pisze wynika ze albo pliki zostaly zle pobrane/zapisane lub gra nie ma dostepu do plikow zeby dograc brakujace dane,
