### ISSUE TITLE
[PL] [Quest] [Hellfire Peninsula] The Warp Rifts

### ISSUE THREAD

**Issue by Arko777** [Atlantiss/BugTracker#7414]
Sprawa dotyczy tego questu:
http://www.wowhead.com/quest=10278/the-warp-rifts

Jak działa obecnie:
Questowy item przyzywa rift, który przywołuje nieskończoną ilość questowych mobów w krótkich odstępach czasu. Można ten efekt odnawiać co 2 minuty i zapchać całą strefę tymi mobami, ponieważ rifty stworzone tym przedmiotem nie znikają. Nie powinno tak być.

Zdjęcie z dowodem:
http://postimg.org/image/kt00vqvu9/

Jak powinno być:
Questowy item powinien przyzywać jednego questowego moba tak jak jest to ukazane na filmiku poniżej.
https://www.youtube.com/watch?v=HvumZ3-H7ss

**Comment by Aival94** [comment]
Other bug: https://github.com/Atlantiss/BugTracker/issues/617

**Comment by Malylolek** [comment]
#617 DUPLICATE
