### ISSUE TITLE
Mage "That spell is not ready" bug + Scorch double GCD

### ISSUE THREAD

**Issue by alexilaiho1** [Atlantiss/BugTracker#7416]
Hi, today I encountered 2 new bugs on my mage. I'll start with the very critical one. Randomly in fights in BG, I'm suddenly unable to use any spell, no exceptions. It happens to me while in a fight, so I die, and after I ress back, I still can't cast anything, it keeps saying "that spell is not ready yet". The only thing that fixes it "temporarily" is a relog, which is a pain, in any situation.

2nd bug is on fire spec of the mage, it's pretty new and I only noticed it today, I get a second global cooldown on "Scorch" spell sometimes. So basically, usually when you cast any spell, you get the global cooldown, as soon as that spell starts casting (if it needs time to cast, or channeling), or is casted (if it's instant). Now what's new is when I cast scorch, I get the 1st GCD after releasing the button, and 2nd GCD after scorch ends casting, resulting in not being able to spam scorch like before. It doesn't happen 100%, but like every 3-5 casts, it happens at least once.

**Comment by Kozakko** [comment]
Do you use cancel spell queue macro ?

**Comment by kadi2** [comment]
Does the first bug occurs in arcane spec?

**Comment by alexilaiho1** [comment]
> Do you use cancel spell queue macro ?

No, I don't.

> Does the first bug occur in arcane spec only?

Yes, I forgot that was relevant, it started happening exactly when I specc'd Arcane!

**Comment by alexilaiho1** [comment]
Anything?

**Comment by kadi2** [comment]
This issue is going to be closed, since the bug about using blink during Arcane Power has been reported already and you did not follow the BT rules.

**Comment by alexilaiho1** [comment]
How about scorch double GCD issue?

**Comment by Bildo** [comment]
bt rules
