### ISSUE TITLE
Firelands bridge cutscene after Baleroc

### ISSUE THREAD

**Issue by BoulderGiant** [Atlantiss/BugTracker#7417]
I think there is a little problem with the Firelands bridge cutscene after Baleroc boss.
When I clicked on the orb to make the bridge appear, I assisted the cutscene... but the cutscene started with the bridge already constructed. The scene should start with the bridge formed as molten lava, and gradually win the final form of the bridge that players will use to cross.
I know it isn´t very important, but its something that will make the raid a lot better.

I hope when Firelands Heroic mode release, the Normal mode is fully operacional. And, too, the Heroic Mode, when Dargon Soul normal release.

**Comment by lamaze** [comment]
no one cares about a cinematic that everyone skip everytime :D

**Comment by Kaldros** [comment]
The cinematic is not even interesting. It's literally just a bridge forming in a totally non-spectacular way. There are other things to fix in Firelands, a lot more useful and important than a bridge forming cut scene.

**Comment by Bildo** [comment]
bt rules
