### ISSUE TITLE
[EN][Quest][Northrend] It's All Fun and Games

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#7419]
quest  not doable on 78 lvl dk

Quest mob should have 55,340  hp   -[link]( http://www.wowhead.com/npc=29747/the-ocula)
q item should do  12.6K dmg per shot -[link]( http://www.wowhead.com/quest=12892/its-all-fun-and-games#comments)

**Comment by Luna-maria** [comment]
#1819 #7386
