### ISSUE TITLE
Combat training (quest)

### ISSUE THREAD

**Issue by mohammadpm** [Atlantiss/BugTracker#7425]
Western plagueland It is in this quest. This is the Quest for Horde. In this quest after killing a abomination should be killed forsaken trooper and they are not after this quest is broken
Please fix it

This is quest: https://www.google.com/url?sa=t&source=web&rct=j&url=http://m.youtube.com/watch%3Fv%3DyrmBJVWX6PE&ved=0ahUKEwiPpdLLs-PMAhWE1xQKHWJxB2UQtwIIKDAC&usg=AFQjCNHPusskYPQ7m6O8n8ktJ885ppGUIA

**Comment by naakarg** [comment]
Mate follow the BT rules use Tags and stuff.

**Comment by naakarg** [comment]
BTW it´s been reported many times already [#7142](https://github.com/Atlantiss/BugTracker/issues/7142), [#482](https://github.com/Atlantiss/BugTracker/issues/482), [#6755](https://github.com/Atlantiss/BugTracker/issues/6755)
