### ISSUE TITLE
[EN][Item/NPC] Cowl of Pleasant Gloom missing from Justice Vendor

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#7427]
The item http://cata.openwow.com/item=58155 Cowl of Pleasant Gloom is missing from the NPC http://cata.openwow.com/npc=44246 Magatha Silverton in Stormwind. 
This is a fairly important item while gearing up in pve since its the only other place besides dungeons where you can get a pve dps headpiece.

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/5842

**Comment by user1011** [comment]
Posted a fix on the forums.
