### ISSUE TITLE
[EN][NPC/Auction][Shattrath City] Kalaren

### ISSUE THREAD

**Issue by Jelkor** [Atlantiss/BugTracker#7428]
Does not open the auction when clicked on npc: "Kalaren"

http://www.wowhead.com/npc=50139/auctioneer-kalaren
Location: {57.6, 62.6} at the shattrath city bank.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11596-7428npcauctionshattrath-city-kalaren/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
