### ISSUE TITLE
[EN][Spell][Warrior] Colossus Smash

### ISSUE THREAD

**Issue by PVPViddys** [Atlantiss/BugTracker#7431]
http://www.wowhead.com/spell=108126/colossus-smash
http://cata.openwow.com/spell=108126
http://wow.gamepedia.com/Colossus_Smash

Colossus smash is not bypassing correct armor %.

In PvP, should be 50% instead of 100%. Currently only reducing armor by 10%.

**Comment by tnarf** [comment]
Test (arms in battle stance vs frost dk, frost presence, 0buffs etc)
weapon: dagger 7,2dps; 1,4speed
ap: 7217
dk armor: 21477 (45,17%)

armor reduction formula: reduction = armor / (armor + 26070,0445) [coeficiant calculated based on tooltip; match with others armor values]
expected dk armor with CS: 10738,5 (~29,17%)

avg AutoAttack dmg 
without CS: 421
with CS: 543

avg AutoAttack dmg / (1- armor reduction)
without CS: 767
with CS: 766

So where is this bug?

**Comment by Quban** [comment]
> In PvP, should be 50% instead of 100%

it is 50%, 50% armor less dosnt mean 50% more dmg, tnarf has proven that
