### ISSUE TITLE
[EN][Item] The Favor of Zangus

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7432]
http://www.wowhead.com/item=36958/the-favor-of-zangus#dropped-by

wowhead says it has a 7% dropchance but I don't believe this to be true. On battlenet, the item is said to have a high droprate http://us.battle.net/wow/en/item/36958#tab=dropCreatures

knowing blizz logic (most of the time) and their questlines, for the previous quest you had to gather 5 cultists suits, and the droprate for that was near 100% for me. A followup quest starting from an item you get from killing those specific mobs should at least have a 20% (1 in 5) chance to drop since you need to kill at least 5 of them to complete the previous quest. 

It'd be nice if the droprate was raised at least a little

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12117-7432-the-favor-of-zangus-drop-chance/
