### ISSUE TITLE
[EN][QUEST][DARKSHORE][THE DARKSCALE WARLORD]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7433]
Hi

Problem with the quest [THE DARKSCALE WARLORD] :
http://www.wowhead.com/quest=13899/the-darkscale-warlord

The NPC isn't here so the quest can't be completed.

Thanks for your help :)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1099
