### ISSUE TITLE
Quest The Seer's Relic

### ISSUE THREAD

**Issue by Volkarjan** [Atlantiss/BugTracker#7435]
In Aliance quest The Seer's Relic NPC Mag'har Escort don't disappear and they stack 
(https://cloud.githubusercontent.com/assets/19469550/15391896/23159d6a-1dc4-11e6-9c1e-d20946bac360.jpg)

**Comment by naakarg** [comment]
U have to know, if u will not follow the BT rules, ur reports probably will be ignored
For rules click [here](https://github.com/Atlantiss/BugTracker)
U r welcome
