### ISSUE TITLE
[PL][Guild][Achievement] Problem

### ISSUE THREAD

**Issue by lameia** [Atlantiss/BugTracker#7438]
Ahoj!
Mamy problem w gildii (Veritas Aequitas) z guild achievementami tak jak na screenshotach. Nie zaliczyło nam ubicia bossów na Tot4W, Firelands oraz BWD. Zgłaszamy to ze względu na mounta oraz kolejnego achiva :)

Tutaj są SS 
http://imgur.com/a/yCjQG

**Comment by Anhaeyn** [comment]
Te achievmenty są zbugowane od roku już chyba.

**Comment by lameia** [comment]
Wiem, ale otrzymałem wiadomość od GM żeby zgłosić to na BT

**Comment by Aival94** [comment]
Reported here: https://github.com/Atlantiss/BugTracker/issues/6712

**Comment by lameia** [comment]
Any help from GM ?
