### ISSUE TITLE
[EN][Raid-Cataclysm][NPC] Atramedes

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#744]
http://www.wowhead.com/npc=41442

He is rotating extremaly slow during [Sonic Breath](http://www.wowhead.com/spell=78075)
Being chased by it i was able to go around,  get behind him and shred for a while :P

In addition this little cut scene featuring young Atramedes, Nefarian and Maloriak should trigger after killing the trash and it should disappear when someone summons boss

And it should be placed a little farther
Like this http://scr.hu/28uv/gyt5e

**Comment by mitim1** [comment]
!bump

**Comment by Varchord** [comment]
This is bump worthy issue to you? ^^

**Comment by arekczup** [comment]
when me gulid click gongs  no fight atramendes no wipe all team cant click gongs restart all time inst and cant click.

**Comment by Varchord** [comment]
Um. What?

**Comment by Varchord** [comment]
Consolidated
https://github.com/Atlantiss/BugTracker/issues/3143
