### ISSUE TITLE
[EN][Glyph][Mage] Glyph of Arcane Power

### ISSUE THREAD

**Issue by Netherstrider** [Atlantiss/BugTracker#7440]
This is a refference to jasiudawid's post [1] which was clearly not resolved so far.

The bug is this - when a mage has Glyph of Arcane Power [2] and the spell Arcane Power active, casting Blink while or after casting another spell will permanently make the mage unable to cast anything. Other two spells included in the glyph, Mirror Image and Mana Shield, don't seem to cause this failure.
This bug appeared when changes were made regarding the spell queue a while ago. It was fixed for some time, but it's there again. It also might have something to do with wearing PvP gloves [3], which reduce the global cooldown of Blink by 0.5 sec

This is resolved by re-logging, but clearly that is not a solution.  Saying "stop playing arcane mage" is also not a solution.

Thank you for the great work, I hope you get to this problem soon because not being able to cast spells means that an entire class is unplayable.
...
[1] jasiudawid's post: https://github.com/Atlantiss/BugTracker/issues/6959
[2] Glyph of Arcane Power: http://cata.openwow.com/item=42736
[3] PvP gloves: http://cata.openwow.com/item=60463

**Comment by l337g0g0** [comment]
Yep this one really screws you over in a BG, you can't re log to fix it... :(

**Comment by swerc** [comment]
Can we bump this to get if fixed sometime soon??

**Comment by lamaATS** [comment]
I found the problem and I see it was my fault (sorry) problem is underflow in one variable I have it already fixed problem exists only when You have PvP `Blink` reduction and `Arcane Power` because `1500ms + 500ms = 2000ms` which is bigger number then default GCD (1500ms) and in result give -500ms cooldown but cooldown never can be below 0 and that's the problem.

**Comment by l337g0g0** [comment]
Thank you so much, going to test it...

**Comment by lamaATS** [comment]
Fix only exists on my server follow this issue or changelog.

**Comment by l337g0g0** [comment]
KK, ty for getting the fix.
I guess we wait for patch right?

**Comment by lamaATS** [comment]
Yes, You will see in info here when it will be closed (it will be today when I will commit my changes).

**Comment by l337g0g0** [comment]
Thank you so much, that blink resting the GCD is soooo important in PVP.
It is the whole Arcane spec ability to escape people. you don't have that your useless.
you just walk around with slow debuffs and get slaughtered...

Great work, thank you again... :D

**Comment by lamaATS** [comment]
Fix tested and works properly.

**Comment by lamaATS** [comment]
Fixed in rev. 5228
