### ISSUE TITLE
[EN][Rated Battleground] MMR/rating not working correctly

### ISSUE THREAD

**Issue by crosik** [Atlantiss/BugTracker#7441]
So rating should work like lets say team mmr is 1500
so every game gives you +192 until you reach team mmr

How it works atm (since we cant see team mmr idk if its working correctly but it should start from 1500)
so we won 4 games
first gave us +192 = correct
2nd gave us +191 
3rd gave us +189 
and 4th barely +80 

Boosting to 2.2k while mmr was 2.4k was about 14 games, 
Jenova halp :dancer: 

edit:
mod here explains how system changed beetwen 4.0.6 n later seasons ( before it was all bout personal mmr and now its all about average mmr of team )
http://eu.battle.net/wow/en/forum/topic/2504843213

**Comment by Jenovas** [comment]
So rating should grow faster?

**Comment by crosik** [comment]
yup it should go like personal rating to team rating 
so +192 till u reach average team mmr

**Comment by Jenovas** [comment]
It shouldnt work like that, on retail when your personal / team rate start getting closer to your MMR the numbers fall down, it works the same way here. When close to you MMR you still gain bonuses to eventually get Team/Personal to be equal to MMR, but the closer you are the smaller the bonus and thats how it should work.
