### ISSUE TITLE
[EN][Quest][Desolace] Rider on the Storm

### ISSUE THREAD

**Issue by everblack** [Atlantiss/BugTracker#7442]
Seems like only 3 out of 15 (or how many are there) Merchants at Nijel's Point are counted as quest  progress upon death, forcing the player to clear the village and return to Furien's Post 5 times.

Update: Sitting and watching the Storm roam the village until the Merchants spawn again is also viable option of getting the next two or three kills

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/2693

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/2693
