### ISSUE TITLE
[PL][Quest] HELP! Corki Freed.

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#7444]
http://www.wowhead.com/quest=9923/help
Witam, Corki widnieje poza klatką i nie da się go uwolnić w żaden sposób po wydropieniu klucza. Po zagadaniu jedynie pozdrawia:). Usuwanie zadania i tym podobne nie pomogły. 
Pozdrawiam.
![wowscrnshot_052016_135952](https://cloud.githubusercontent.com/assets/18480484/15427197/b09f1be6-1e93-11e6-8877-961141f65592.jpg)

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/6338
