### ISSUE TITLE
http://www.wowhead.com/quest=27718/warchiefs-command-vashjir----->http://www.wowhead.com/quest=25924/call-of-duty

### ISSUE THREAD

**Issue by lxfactor** [Atlantiss/BugTracker#7447]
The NPC , Commander Thorak , doesn't give  the quest . Please check

**Comment by Piklo** [comment]
Vashj'ir is closed

**Comment by Kaldros** [comment]
Also, read this before posting bug reports https://github.com/Atlantiss/BugTracker/blob/master/README.md
