### ISSUE TITLE
[PL] [NPC]NIE WIDZĘ NPCÓW 

### ISSUE THREAD

**Issue by zofia665** [Atlantiss/BugTracker#7449]
Hejka
Wczoraj wzięłam questa przy wejściu do Hillsbrad Foothills 'Welcome to the Machine' i się coś zbugowało - nad moją postacią był ten znak zapytania żółty od oddawania questa. Relogowalam kilka razy i zniknął. Wróciłam do ogri i nie widzę npców, skrzynek na listy, innych graczy itp.
Próbowałam relogować, reinstallować - nic nie pomogło. 
Na innych postaciach na tym samym koncie wszystko działa.
Proszę o pomoc!

**Comment by Bildo** [comment]
napisz ticketa i popros gma o unaure
