### ISSUE TITLE
[PL][Apprentice Riding][Night Elf]Oracle Hachling

### ISSUE THREAD

**Issue by Invaerne** [Atlantiss/BugTracker#7450]
Miałam pewien problem z tytułem, bo bug jest dosyć dziwny. Otóż od wprowadzenia poprawek do eventu Children's Week Night Elfy, które wbiły 20 lvl, dostają na maila peta z tegoż eventu, wraz z mailem od trenera ridingu. Trochę to niesprawiedliwe, zważywszy na to, że poprawki do eventu nie zostały wprowadzone na czas i nie dało się tego peta zdobyć normalnie.
Edit: Teraz zobaczyłam, że Humany też go dostają. Nie wiem jak z innymi klasami, ale Draeneie chyba nie.

**Comment by TranceAccount** [comment]
rev 5085
