### ISSUE TITLE
[EN] [RAID] [Looting]

### ISSUE THREAD

**Issue by freddie12** [Atlantiss/BugTracker#7456]
Hello, I've just witnessed a serious glitch shortly after my raid group and i killed Ragnaros, in Firelands. While in the looting process, the raid leader invited 2 of guys' alts which were not in the group at that very moment we killed the boss. Then, he set the loot as free roll and one of them took the item. Honestly, i am not 100% sure it's a bug but i just wanted to inform you just in case.

**Comment by Andamarokk** [comment]
I think you could always take loot out of !CHESTS! not a Boss if you put on FFA, even if that person wasnt present on the kill.

**Comment by TranceAccount** [comment]
Please make another issue when you find out that it shouldn't happen.
