### ISSUE TITLE
(Ita)Quest Ashenvale Got Wood?

### ISSUE THREAD

**Issue by Crazyalex91** [Atlantiss/BugTracker#7459]
Hi i take the quest then i think is not fixed because i can mount the mount who the npc give it to me...could you please fixed or look that thanks you.

**Comment by Angelo-DM-** [comment]
for me the quest work 100% blizzlike. u need to click on brutusk in order to mount up. and you need to stay near brutusk...

**Comment by Crazyalex91** [comment]
Oh yess it is true i don't see it :D thanks you

**Comment by Angelo-DM-** [comment]
No problem!

This issue can be closed.

**Comment by ElvisPruna** [comment]
The quest works if you kill all the elves in and around the post.
