### ISSUE TITLE
Wintergrasp- Vehicle Workshop NPCs do not spawn.

### ISSUE THREAD

**Issue by trashdog** [Atlantiss/BugTracker#7460]
The NPCs that are supposed to spawn at the workshop do not spawn. All workshops were horde controlled for entire Wintergrasp match but no NPCs would spawn and no vehicles could be created. Wintergrasp is Alliance controlled and I've been trying to access the Wintergrasp vendor but its impossible to win the match if vehicles can't be spawned.

**Comment by Prodiege** [comment]
The npcs are there but they are under the ground. Did this get fixed? Is that why it was closed? It is really hard to tell if it was fixed or not especially if nothing was said here or in the changelog

**Comment by Oxyntes** [comment]
The NPC's still do not spawn for horde.
