### ISSUE TITLE
Im dead and stucked

### ISSUE THREAD

**Issue by neyttiri** [Atlantiss/BugTracker#7461]
I was in ZA dungeon after i got disconnected because of problems with my connection. After i came back i was kicked from group and death. So now there is no spirit where i can ressurect and when i enter dungeon i canot revive also. So basically im stucked. What should i do? 

My character's name is Djilee (gnome warlock)

**Comment by Angelo-DM-** [comment]
An easy way: http://atlantiss.eu/shop/details/163
