### ISSUE TITLE
[EN][Raid][Firelands] Lord Rhyolith

### ISSUE THREAD

**Issue by Bud1980** [Atlantiss/BugTracker#7463]
After wiping on Lord Rhyolith he did not reset we waited 25 mins and still didnt reset please look into this

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7321

**Comment by Quban** [comment]
probably fixed http://atlantiss.eu/changelog#rev5028 say if its not

**Comment by HCGWill** [comment]
Not fixed as of 7/17
