### ISSUE TITLE
[EN][Hunter] Feign Death

### ISSUE THREAD

**Issue by kevery123** [Atlantiss/BugTracker#7470]
I noticed two bugs in Hunter's spell called Feign Death. Firsly Feign Death spell should let us lose combat after using it, we can see it how it should work in 0:48 https://www.youtube.com/watch?v=S5BBIPiMsqE. Secondly Feign Death spell should also let us get rid off enemy pets which are attacking you, becuase they should lose target when they are attackin us and stop attacking us we can see how it should work properly in 1:28 https://www.youtube.com/watch?v=S5BBIPiMsqE  .
In atlantiss after using this spell we don't lose combat and pets are still attacking us.

**Comment by jissabraham** [comment]
its long known bug

**Comment by user1011** [comment]
Duplicate #16.

**Comment by kevery123** [comment]
Why it's closed if it was reported and still bug occur.  Just fix these bugs instead of closing topic because the have been already reported.

**Comment by Jenovas** [comment]
Duplicate = issue will be closed

**Comment by kevery123** [comment]
So what give reporting bugged spell on bugtracker if  they won't be fixed . I reported like 10 bugged spells and they are still open and nothing happening to them

**Comment by Jenovas** [comment]
Bad luck. The bugtracker has more than just your reports.
