### ISSUE TITLE
[EN][Quest][Blood Elf Starting Area] Evisceration

### ISSUE THREAD

**Issue by nitrorunes** [Atlantiss/BugTracker#7472]
Hello. I thought I'd make a rogue alt so created a new belfy and started questing. But actually the quest 'evisceration' (which Rogue Trainer gives btw) is bugged. You can take it to your questbook, even complete this but there is no option to turn that in because simply the NPC that gives it has no question mark above his head and if you click on him there is no option to click to turn it in. IIRC it was working some months ago.

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker

Links to wowhead and such please.

**Comment by xmesaj2** [comment]
http://community.atlantiss.eu/index.php?/topic/10233-enquestsunstrider-isle-evisceration/ fix

**Comment by TranceAccount** [comment]
rev 5029
