### ISSUE TITLE
Truesilver

### ISSUE THREAD

**Issue by Palwind** [Atlantiss/BugTracker#7473]
pls fix truesiler spawning i farmed everything but cant find it so i have to find alchemy and let them make but they prefer to make trugold so im with nothing :(( and 1 more pls if someone knows other way of getting them tell me

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker

**Comment by Luna-maria** [comment]
also reported already, and probably fixed on next update (here's hoping)
