### ISSUE TITLE
[EN][Quest][Mount Hyjal] Forged of Shadow and Flame [81]

### ISSUE THREAD

**Issue by Tinta89** [Atlantiss/BugTracker#7474]
Hello.
I noticed that, if you click fast you can get quest credit for 2-3 crates on one crate. This happens on other quests that have this kind of credit as well.
In my defense I use a Aula "Killing the soul" mouse with a double click button, and I use it mostly instead of the regular left click, because its a bit broken and looses contact.

**Comment by Aival94** [comment]
reported:https://github.com/Atlantiss/BugTracker/issues/1489
