### ISSUE TITLE
[EN][Quest][Redridge Mountains] Saving Foreman Oslow [14]

### ISSUE THREAD

**Issue by Tinta89** [Atlantiss/BugTracker#7475]
Used the orb, nothing happens. The ettin follows me around and does nothing.

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker

Add links to WoWhead and such.

Thank you.

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/2589
