### ISSUE TITLE
[EN][SPELL][Druid] Swift Flight Form

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#7478]
Druids shouldn't be able to learn Swift Flight Form from trainers **before** they learn artisan riding. I learned swift flight form without learning artisan riding and my normal flight form is gone. My new swift flight form is not usable and i have no money for riding skill.
Please make it blizzlike: http://us.battle.net/wow/en/forum/topic/1305770707

**Comment by Jenovas** [comment]
Already fixed in rev http://atlantiss.eu/changelog#rev5012 
Please wait for update.

**Comment by DuGalle** [comment]
http://atlantiss.eu/changelog#rev5012 is implemented and yet swift fly form isnt removed

**Comment by Jenovas** [comment]
Yes, I know about that, we will remove swift fly form shortly.
