### ISSUE TITLE
[Variable Pulse Lightning Capacitor]

### ISSUE THREAD

**Issue by linesar** [Atlantiss/BugTracker#7479]
http://www.wowhead.com/item=69110/variable-pulse-lightning-capacitor#comments

According to comments here, it should scale with Elemental Fury (Passive ability gained from picking Elemental) which increases all crit damage with nature spells by 100%. Afaik, I compared its damage with my Priest and Shaman, and it is roughly the same.
It is also unknown atm, if it scales with "Concussion", it is a talent in elemental talent tree which increases Lightning Bolts damage by 6%. Atm on the server, it does not scale with it, but it kinda feels like it should. I haven't found any statement for it yet.

It is very hard to track its damage as Elemental Shaman, but you can just test it by using Lava Burst and Flame Shock on the target, for 100% crit chance. Then all Lightning Bolts procing will be from the trinket.

**Comment by LaveniaGithub** [comment]
A hint for testing as Elemental Shaman; use Chain Lightning as filler instead of Lightning Bolt. That was what I did while testing this trinket at Firelands release.

**Comment by linesar** [comment]
Or you can do that, yeah. but I tested it on a dummy and compared it between my S-Priest and E-Shaman and they had roughly the same crit damage.

**Comment by Respect69** [comment]
Well, if this trinket really stacks with skills of particular classes its damage should be also increased by Druid's Eclipse.

**Comment by LaveniaGithub** [comment]
Well, the thing is that it doesn't scale with all skills, but just some. It's hard to find a lot of information about this trinket, so I do not know if it scales or doesn't scale with Eclipse.
For instance, it scales with Elemental Fury, Elemental Precision and Elemental Mastery for Elemental shamans.

Elemental Fury should increase the critical hit of the trinket proc by 100% instead of 50%.
Elemental Precision should increase the trinket proc's damage by 3%
And Elemental Mastery (the spell) should increase the trinket's damage by 20% when the buff is active.

(Source: http://www.wowhead.com/item=69110/variable-pulse-lightning-capacitor#comments:id=1523587)

**Comment by linesar** [comment]
It does already scale with dtuid solar eclipse on the server.
And about the Elemental Fury, since it is a 100% increase from nature damage crits. It should count as 2 crits upon eachother. I easily have 25k crits with my S-Priest, so a 25k crit would lead it to crit 50k from Elemental Shamans.

**Comment by linesar** [comment]
I believe that it might scale when the tolltip says "increased spell damage" (increased nature damage) or if the boss has a debuff which increases spell damage taken.

**Comment by LaveniaGithub** [comment]
If you crit 25k on your Shadow Priest it shouldn't be a 50k crit on your Elemental Shaman. It is only the bonus damage (the difference between the non-crit spell and the crit spell) that is 100% increased, not your whole damage from that spell.

**Comment by linesar** [comment]
Ahh, so a 25k crit would lead to 37.5k then. If the normal base hit is 12.5k.

**Comment by linesar** [comment]
"The damage of the Lightning Bolt is affected by debuffs (e.g. Stormstrike, Misery) and talents (e.g. Arcane Instability, Molten Fury) which improve all, or at least nature spells. However, talents which specifically mention their affected spells do not improve it. Furthermore, even the Shaman's talents which improve Lightning Bolt do not affect it"

**Comment by linesar** [comment]
I am on my phone so it is rather hard to copy stuff from other tabs.

Anyway the link here http://wowwiki.wikia.com/wiki/The_Lightning_Capacitor is a guide for how the trinket from Karazhan works and it is probably the same. The statement above is from this guide. It also says that everything that increases spell damage taken and increases spell damage (nature damage) buffs the trinket.

**Comment by linesar** [comment]
I have done some more testing. My highest crit with my Shaman was 33k, while my biggest crit with Priest was 25k. I don't know if what happened the other day, but I could not get it to crit higher than 27k with the Shaman.

33k still feels a bit weak for Elemental Shamans, since my highest non-crit was 17k, crit on that is 34k and then if we add Elemental Fury, it should end up with 51k.

**Comment by kadi2** [comment]
People would write alot if it would be that overpowered on elemental shamans. I guess it's just supposed to scale with Elemental Mastery and Elemental Precision.

Elemental Fury was made just to reduce healer's damage. since healers can crit just for 150% of normal damage. All the dps specializations have similar passives or built in 200% critical damage.

**Comment by linesar** [comment]
Moonkins already crit 50k+ with it, since it scales with their mastery.

**Comment by linesar** [comment]
And in 4.3 every spell is a 200%, even for healers if I am not mistaken.

**Comment by kadi2** [comment]
@linesar VPLC scales with overall damage increase, like Tricks of the trade, Spell Damage and Nature damage increases. So for moonkins it's Solar Eclipse, Moonfury, Master Shapeshifter, Balance of Power, Moonkin Form and Owlkin Frenzy. I don't wanna go that deep in CoE and other similar buffs and debuffs.

**Comment by kadi2** [comment]
Molten  Fury is supposed to increase crit damage from 150% to 200%for dps specs only like Moonfury, Shadow Power.

**Comment by linesar** [comment]
http://www.wowhead.com/item=69110/variable-pulse-lightning-capacitor#comments:id=1523587
Ok got the normal version of this on my elemental shaman yesterday, and it seams awesome, prolly mostly couse we elementals really love ekstra lightningbolts. 

after some testing here is a list of disclaimers and claimers: 

Claimers: 

Procs of dots such as fire shock. 
As the lava burst is a crit you are sure to get alot of procs of this specielly with the tier 12 four-set 
Elemental fury increse the crit damage by 100% 
Elemental precision increse the bolts with 3 % 
Elemental Mastery increse the bolts with 20% 

Disclaimers: 

The lightningbolts from the trinket are not affected by shaman mastery so no double bolts from trinket atlest. 

Yet unknown: 
if the proc is affected with Shamanism 
if the proc scales with Concussion 6% damege on lightning bolt
If the proc gives Clearcasting (10% damege) when crit 
if the proc scales of Clearcasting (10%damage) 
if the proc consumes Clearcasting (10%damege) 
if the proc gives Rolling thunder 
if the proc affekts feed back

Elemental Fury:
"Increases the critical strike damage bonus of your Searing and Magmaw totems and your Fire, Frost and Nature spells by 100%....." it clearly says that it increases your bonus to Nature criticals by 100% here

**Comment by Jenovas** [comment]
So some sources claim it should, some that it shouldnt. Tried to find a video where it would be visible but could not. I checked Rawr (sadly didnt show infoabout the trinket DMG) and Simcraft and Simcraft claims that it does not crit for 200% while in Elemental.

Issue closed. If you find any proof thatit should crit for 200% please create an new issue.
