### ISSUE TITLE
[EN][Quest][The Hinterlands] Find OOX-09/HL!

### ISSUE THREAD

**Issue by Nightend1** [Atlantiss/BugTracker#7480]
The robot chicken is not on the rock and the quest completes itself.
http://www.wowhead.com/quest=485/find-oox-09-hl

**Comment by Nightend1** [comment]
Nevermind fount it in the forest.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/320
