### ISSUE TITLE
[EN][NPC][Jewelcrafting][Stormwind City][Minor]Terrance Denman(ID 44583)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7482]
The NPC [Terrance Denman](http://www.wowhead.com/npc=44583/terrance-denman) should sell every Cataclysm Jewelcrafting Recipe but on server he does not.

Wowhead Link:  [Terrance Denman](http://www.wowhead.com/npc=44583/terrance-denman)

Note: In case someone want to check if rest of Vendors are selling these recipes you can find the vendors in every recipe link like this one: [Sold By](http://www.wowhead.com/item=52426/design-piercing-dream-emerald#sold-by)

**Comment by Luna-maria** [comment]
I believe they're not all added yet because dragon soul isn't open, and some of the pvp craftable items are too high in ilvl for our current available content

**Comment by Aival94** [comment]
No..they should sell i mean all cata and those that are not 4.3.

**Comment by user1011** [comment]
Which recipes are missing..?

**Comment by Aival94** [comment]
Seems it fixed.Cannot find the rev but still npc has the recipes now so i close this issue.
