### ISSUE TITLE
[EN][Druid][Spell] Feral Charge (Cat Form) is breaking Prowl

### ISSUE THREAD

**Issue by Odblanovac** [Atlantiss/BugTracker#7488]
After server shutdown on May 26th (cca at 19:30) Feral Charge started to break Prowl after use. To be more specific, Prowl is canceled immediately after use of Feral Charge, not after reaching the target (and dazing it).

PS: I also tried creating macro which included /stopattack command, but it didn't help.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5023
