### ISSUE TITLE
[EN][Quest][Durotar][Darkspear Hold] Sen'jin Village

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#7489]
Quest: [Sen'jin Village (ID: 25073)](http://www.wowhead.com/quest=25073/senjin-village)

This quest should be availlable to Taurens, Blood Elfs and Trolls, instead is availlable only to Trolls.

**Comment by user1011** [comment]
Are you sure it not supposed to be available for the whole factions?

**Comment by user1011** [comment]
Please confirm...

**Comment by Angelo-DM-** [comment]
Yes. as blood elf i can't take it. As troll i was able to get this quest.

**Comment by user1011** [comment]
On retail?

**Comment by Angelo-DM-** [comment]
WOWHEAD:
Level: 5
Requires level 1
Loremaster: Yes
Side: Horde
Races: Tauren, Troll, Blood Elf
Start: Vol'jin
End: Master Gadrin

On comments i read:
"Since there are no Paladin or Death Knight versions of the quest chain that begins with The Rise of the Darkspear, none of the Echo Isles quests unlock for these two classes."

Maybe a BE non paladin, non dk, could tell us.

**Comment by user1011** [comment]
So what should it be now?...

**Comment by Angelo-DM-** [comment]
As my first post say:
"This quest should be availlable to Taurens, Blood Elfs and Trolls, instead is availlable only to Trolls."
I've tried with my Blood Elf paladin and with my Tauren warrior... and i can't take this quest.

**Comment by TranceAccount** [comment]
You should know that wowhead supports the latest retail build, and I think that this quest is supposed to be available to all races.

**Comment by Angelo-DM-** [comment]
Oh, ok. In each case, there is a problem about this quest, that is availlable only to trolls.
If @TranceAccount have right, the quest should be availlable to whole horde races (and not factions), instead is availlable only to trolls.

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12532-7489questdurotardarkspear-hold-senjin-village/
