### ISSUE TITLE
[EN[Core]Currency

### ISSUE THREAD

**Issue by nerv234** [Atlantiss/BugTracker#749]
1: Dungeon finder shows player gets 140 vp instead of 150(didn't tested yet if it gives vp).

2: Valor points for raid boses, tested on 10man version u get 70vp for bos, u should get 115 for 10man and 135 for 25man, cap is ok.

3: Tol Barad Commendation(TBC): after completing daily quest(every daily in both TB and TB Peninsula) you get 2 TBC instead of one(one and after it one another, after sth. about 50ms).

4: After getting any currency there isn't notification in chat window even if such option is checked.

Source of numbers: http://www.wowwiki.com/Valor_point
http://www.wowhead.com/currency=391/tol-barad-commendation
http://www.wowhead.com/item=62898/tol-barad-commendation

**Comment by Chulain** [comment]
something wrong with honor gains from TB?
http://i.imgur.com/VeQY2xt.png

I was already had 250 honor +-

"You receive currency: honor x1266." on my chat
But I only got like +550 honor

I was in the second raid of TB, the first one was full, maybe something to do with that?

**Comment by kadi2** [comment]
3: Tol Barad Commendation(TBC): after completing daily quest(every daily in both TB and TB Peninsula) you get 2 TBC instead of one(one and after it one another, after sth. about 50ms).

This point probably includes all the tokens in the game.
