### ISSUE TITLE
[EN][Quest][Northern Barrens][Ratchet] Root Sample

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#7490]
Quest: [Root Sample (ID: 866)](http://www.wowhead.com/quest=866/root-samples)

Need to have herbalism to get this quest: Root Sample should be found in any herb patch with 100% drop while you are doing this quest, instead i've gathered something like 300 herbs, and i've found only 1 root sample!!!!
So, the problem is: really low drop rate!

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1952
