### ISSUE TITLE
[PL][NPC][Shadowfang Keep] Baron Ashbury

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#7491]
na dzien dzisiejszy 1 boss w sfk jest nie do ubicia przez 95% populacji serwera
jest to spowodowane tym ze boss po uzyciu  [Asphyxiate] czyli po sprowadzeniu graczy do 1hp zamiast castowac  [Stay of Execution] czyli leczenie wszystkiego dookola o 5-10% uzywa  [Wracking Pain] zadajac gracza z 1hp po 10k (plus debuf) .  2 razy widzialem jak po sprowadzeniu  wszystkich do  1hp przechodzil w 2 faze i uzywal  [Calamity]

Baron Ashbury
http://www.wowhead.com/npc=46962/baron-ashbury

http://www.wowhead.com/spell=93581/pain-and-suffering
channeling zadajazy 1,5k dmg co 0,5 sec przez 8 sek
Cooldown	8 seconds  <- od przerwania lub zakonczenia

http://www.wowhead.com/spell=93720/wracking-pain
instant zadanie 10k dmg i nalozenie debufa stakujacego sie do maks 4 zwiekszajacego dmg o 20%  cd 6 sec
Cooldown	6 seconds

http://www.wowhead.com/spell=93423/asphyxiate
chaneling przez 6 sec sprowadza wszystkich do 1 hp
Cooldown	12 seconds 
Cast time	Channeled <nieprzerywalne

http://www.wowhead.com/spell=93468/stay-of-execution
chaneling leczy siebie o 5% graczy o 10 co sekunde przez 8sec
Cooldown	n/a
Cast time	8 seconds  <przerywalne

http://www.wowhead.com/spell=93757/dark-archangel-form
shadow forma po osiagnieciu 25% hp bossa, 
Cast time	3 seconds <nieprzerywalne

http://www.wowhead.com/spell=93812/calamity
zadaje 5k dmg  i naklada debufa zwiekszajacego dmg o 1% co sec, 
Cast time	Channeled <nieprzerywalne trwa do konca walki ( wipe lub zabicie bossa)

https://www.youtube.com/watch?v=3XAFhyz-MSo
tu jest wszystko wytlumaczone

https://www.youtube.com/watch?v=s8Hv1sNmC6M
tu jest film z normalnej walki

**Comment by stanq87** [comment]
po dzisiejszym podejciu:
cd asphyxiate wydaje sie miec jakies 6-8 s nie 12, 2x patrzylem na te cd spelu bossa na dbm i rzucil zanim skonczylo sie cd

raz jeszcze po zejsciu ponizej 25% postanowil jeszcze raz dac asphyxiate i zaraz po tym  wracking-pain  

na dzien dzisiejszy  zamiast wyscigu   dps heala i umiejetnosci przerywania, jedynym sposobem  na zabicie go jest pozwolic mu sie wyszalec  , tz zatrzymac dps na 30-40% hp  
 dac mu wycastowac  drugiego asphyxiate i dopiero zjechac ponizej 25%

**Comment by mati865** [comment]
Albo zbić zanim wycastuje 2 Asphyxiate.

**Comment by karolnpc** [comment]
Potwierdzam zaraz po drugim Asphyxiate castuje od razu Wrecking Pain zamiast Stay of Execution co momentalnie zabija większość osób.

**Comment by Quban** [comment]
fixed in rev. 5070

**Comment by Raikurs** [comment]
This is not fixed. When ashbury lands players from grip they get fall damage and die. Happened 4 times today and then we gave up and quit instance.

**Comment by Quban** [comment]
Its fixed
