### ISSUE TITLE
My corpse is not exist

### ISSUE THREAD

**Issue by unholie** [Atlantiss/BugTracker#7492]
My character name Kajanawesome, and im bugged dead, my corpse not exist,and gy. Can someone fix this?

**Comment by user1011** [comment]
Please follow the _How to use?_: https://github.com/Atlantiss/BugTracker

- Wrong title.

Go to http://atlantiss.eu/shop/3 and buy an unstuck for your character. If you don't have any vote points go to http://atlantiss.eu/shop/vote and vote 5 times.
You could also write a ticket in game and ask a GM to fix it for you, but the shop panel works faster.
