### ISSUE TITLE
[ENG][Spell]Starfall

### ISSUE THREAD

**Issue by Grizoor** [Atlantiss/BugTracker#7498]
Hey Guys,

i think Starfall is bugged.
[http://cata.openwow.com/spell=50288](url)

It should hit all enemies in a range of 40 yrds, but when i use Starfall it hits only 2 mobs per hit.

**Comment by Kiperr** [comment]
Starfall is hitting only mobs that you are in combat and you are in LOS with them.

**Comment by Aival94** [comment]
I believe he meant that Starfall should hit all mobs that are on aggro with you and in your los simultaneously while in Atlantiss hit maximun 2 mobs simultaneously. I am not sure if is a bug or not as i do not remember how was working on cata.

**Comment by Jenovas** [comment]
Starfall should hit only two enemies, It was changed in WoD.
Warlords-Logo-Small Patch 6.0.2 (14-October-2014): Starfall no longer cancels when mounting. However, it can no longer hit stealthed or invisible targets.; Starfall now shares charges with Starsurge, and has no cooldown of its own. **It also now hits all nearby enemies (up from 2 nearby enemies).**
