### ISSUE TITLE
[EN][Spell][Mage] Elemental of Water in PVE and T12 tier bonus for Frost and Arcane

### ISSUE THREAD

**Issue by Genoangel** [Atlantiss/BugTracker#7500]
Hello , 
I report an issue I am having with my pet in PVE comparing to all other classes with pet.
The mage's pet in frost spec , the elemental of water ,  take exactly the same damage as any member of the raid (he takes aoe , traps of Shannox and every possible source of damage that can oneshot him) while all other pets of other classes are only sensitive to direct damage spells , to sum up he is counted like a member of a raid instead of being counted like a pet like for every other class.
I can't unfortunately provide screens since it's hard to track why the pet die in recount. but he take exactly the same damage as me or more and keep dying while other pet stay alive in all boss/trashes encounters except if they are hit by direct damage.
Also , since the T12 bonus was bugged before for Fire and fixed I would like to ask you if it's possible to verify if the bonus T12 provide appropriate % increase of the procs of finger of frost.
For arcane it's definitely bugged , the bonus is supposed to provide 10% less cost on arcane blast. it reduce the cost of mana by 10% in the effect of arcane but only for the first stack of Arcane blast (wish means instead of saving 600 mana when you are in 4 stacks , he make you save 10 mana , like you were in 1 stack in Arcane blast).
I hope you will take a look in these issues for mage since it provide a real weakness for the two other specs of mage in PVE.

Best Regards ,

**Comment by Jenovas** [comment]
One issue = one report.
Closing.
