### ISSUE TITLE
Quest 

### ISSUE THREAD

**Issue by Spuner1993** [Atlantiss/BugTracker#7501]
does not work , please repair mission  [Stones of Binding] , greet the player atlantiss wow

**Comment by Aival94** [comment]
First of all follow the rules of how to report an issue: https://github.com/Atlantiss/BugTracker/blob/master/README.md

Second quest is reported here and if there are more bugs just make a comment on the already exist report: https://github.com/Atlantiss/BugTracker/issues/2201

**Comment by Spuner1993** [comment]
Then I'm sorry for my excuse I will say that for the first time here I indicate with mistake
