### ISSUE TITLE
[EN][Quest][Molten Front] Through the Gates of Hell

### ISSUE THREAD

**Issue by Inglorionus** [Atlantiss/BugTracker#7502]
After killing enemy I wanted to talk to Malfurion, but he disappeared. He is nowhere. It shows screen.

http://s2.ifotos.pl/img/WoWScrnSh_sasensw.jpg

[SOLVED]

**Comment by Aival94** [comment]
Probably you did not follow him and he disappeared like many npcs disappear after you lost los from them. Try to redo quest

**Comment by Inglorionus** [comment]
It helped, thanks :) :+1:

**Comment by Aival94** [comment]
I believe is better to close this report as is a general bug and not a quest bug.
