### ISSUE TITLE
[EN][NPC][Drops]Rare Elites(world bosses)

### ISSUE THREAD

**Issue by shaunb19** [Atlantiss/BugTracker#7504]
Myself and 2 friends killed Akma'hut earlier today and only received a Jewelcrafting recipe.
if you read through the wowhead comments for patch 4.1 and later you see that he has 1 guaranteed epic item http://www.wowhead.com/item=69877/belt-of-a-thousand-gaping-mouths along side 1 other random world drop 359 epic item. this worked the previous time one of the group members killed it as we received the belt and a random world drop epic. however now it appears to not work as you can see in this image http://imgur.com/r5JaTvb.

**Comment by Aival94** [comment]
First of all change title as it should be following the rules: https://github.com/Atlantiss/BugTracker/blob/master/README.md

Second yes this is a bug for some time with all world bosses. Sometimes they do not even drop gear or recipe but only gold.

Related: https://github.com/Atlantiss/BugTracker/issues/4004, https://github.com/Atlantiss/BugTracker/issues/1092
