### ISSUE TITLE
[PL][Quest][Deepholm] Violent Gale

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7505]
W tym queście musimy znaleźć Felsen the Enduring, aczkolwiek nie ma go w miejscu, gdzie powinien stać, zamiast niego stoi tam Felsen the Enduring Speak Credit.

Screen:http://i67.tinypic.com/5eakhz.jpg

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7207
Other bugs: https://github.com/Atlantiss/BugTracker/issues/5441, https://github.com/Atlantiss/BugTracker/issues/2962
