### ISSUE TITLE
[EN][Death Knight][Spell] Pillar of Frost gives new immunity

### ISSUE THREAD

**Issue by MangeNerfedOwl** [Atlantiss/BugTracker#7508]
How it works: Pillar of Frost grants for the Frost DK immunity for silences effects.

How it should work: Pillar of Frost should give immunity only for knockback effects such like typhoon, whiplash or thunderstorm. Should not give immunity for silence.

Tested on Silence (Shadow Priest) and Strangualate.
Bug like that can be really gamebreaking because silence turns off most of DKs abilities, including melee interrupt.
Back in the days there was a smiliar bug that caused Pillar of Frost grants immunity to fear effects.

**Comment by Jenovas** [comment]
Fixed in rev 5035
