### ISSUE TITLE
Bugged gate Shadowfang Keep

### ISSUE THREAD

**Issue by Zipper2013** [Atlantiss/BugTracker#7509]
After Lord Walden's defeat the gate leading to the rest of the dung and last boss doesn't open even tho that worgen npc is there

**Comment by Aival94** [comment]
If someone interracted with NPC while event to open the door was going on there is a possibity it get bugged. I remember this bug happened to me once and after that nobody ever interract with npc while this event so not sure if fixed or just all know of this bug and be carefull

Furthermore read the rules of how to make a report on bugtracker: https://github.com/Atlantiss/BugTracker/blob/master/README.md
