### ISSUE TITLE
[EN][Spell][Hunter] Steady Shot --- May 29th, 2016

### ISSUE THREAD

**Issue by Kaiurem** [Atlantiss/BugTracker#7511]
[**_Steady Shot_**](http://cata.openwow.com/spell=56641) does not generate focus properly. Currently it is generating focus once the shot lands rather than once the cast is finished. This is annoying and puts hunter's at a disadvantage in both PvP and PvE.

**Comment by Thefakemccoy** [comment]
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com

**Comment by Kaiurem** [comment]
Added link.
