### ISSUE TITLE
[EN][Spell][Hunter] Steady Shot

### ISSUE THREAD

**Issue by Quickscoped** [Atlantiss/BugTracker#7517]
[**_Steady Shot_**](http://cata.openwow.com/spell=56641) does not generate focus properly. Currently it is generating focus once the shot lands rather than once the cast is finished. This is annoying and puts hunter's at a disadvantage in both PvP and PvE.

**Comment by Quickscoped** [comment]
Additional info. In this video you can see from around 8:45-9:00 his casts and focus generation at tje end of each cast. This is on retail in patch 4.2. https://youtu.be/OYJRyU-a1T0

**Comment by xolon** [comment]
Steady shot gives focus when cast is finished. You can close this issue.
Sigh this bug with Cobra still exist tho
