### ISSUE TITLE
[EN][Spell][Hunter] Cobra Shot

### ISSUE THREAD

**Issue by Quickscoped** [Atlantiss/BugTracker#7518]
[**_Cobra Shot_**](http://cata.openwow.com/spell=77767) does not generate focus properly. Currently it is generating focus once the shot lands rather than once the cast is finished. This is annoying and puts hunter's at a disadvantage in both PvP and PvE.

**Comment by Quickscoped** [comment]
Additional info. In this video you can see from around 8:45-9:00 his casts and focus generation at tje end of each cast. This is on retail in patch 4.2. https://youtu.be/OYJRyU-a1T0

**Comment by xolon** [comment]
PLEASE

**Comment by lamaATS** [comment]
Fixed in rev. 5229
