### ISSUE TITLE
[EN][Raid-Cataclysm][NPC] Maloriak

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#752]
After killing Maloriak in hc mode raid should get 30 minutes debuff [Master Adventurer Award](http://www.wowhead.com/spell=89798#comments) which grants the title [Slayer of Stupid, Incompetent and Disappointing Minions](http://www.wowhead.com/title=188). Not Working :<

And it would be nice if You investigated this knock back he does when changing to green phase. Last night only our Maloriak tank have got knocked back. Idk which ability causes it, so no wowhead link :<

**Comment by qubuslabadz** [comment]
"And it would be nice if You investigated this knock back he does when changing to green phase. Last night only our Maloriak tank have got knocked back. Idk which ability causes it, so no wowhead link :<"

http://www.wowhead.com/spell=77948

Jak widziać spell ma 30 jardów zasięgu od środka kotła, bo to kocioł wybucha. Jeśli to bug proszę o konkrety dowód.

**Comment by Varchord** [comment]
No ja właśnie nie wiedziłame z jakiego spella ten knockback się bierze. Pamiętałem tylko, że na 4.0.6 wszystkich odrzucało.

Tytuł napraw. toż to high priority a nie low XD

**Comment by qubuslabadz** [comment]
Fixed in rev 4203

**Comment by Varchord** [comment]
Fuck yea
