### ISSUE TITLE
[EN][NPC] Thorim

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7522]
NPC Thorim in Storm Peaks (id 29445) uses wrong model (old one). It was changed way back in patch 3.1. He should have the same as in Ulduar now. It's probable that there's the same case with other Thorim npcs in Storm Peaks during quests, not sure.

**Comment by Bildo** [comment]
wowhead links

**Comment by MichaelArchangelo** [comment]
http://www.wowhead.com/npc=29445
I've checked and the rest of Thorims seem to use the right model.

**Comment by xmesaj2** [comment]
http://community.atlantiss.eu/index.php?/topic/10777-7522npc-thorim/ fix
