### ISSUE TITLE
[EN][Quest][Darkshore][The eye of All Storms]

### ISSUE THREAD

**Issue by DanyelSnow** [Atlantiss/BugTracker#7523]
I have reported about this quest once , i do it again fix it please! 
http://www.wowhead.com/quest=13588/the-eye-of-all-storms 
There is no portal in the storm and all dragons stay down 
![wowscrnshot_053016_164402](https://cloud.githubusercontent.com/assets/19279671/15651157/77e7ddc4-2686-11e6-80f6-3a6299890752.jpg)

**Comment by Bildo** [comment]
duplicate

**Comment by DanyelSnow** [comment]
Thanks for fixing , you are so kind :)
