### ISSUE TITLE
[PL] [Quest] Missing in action

### ISSUE THREAD

**Issue by Smyk65** [Atlantiss/BugTracker#7524]
Klatki z gnomami pozostają otwarte od kilku godzin. Respi tam wszystko oprócz nich. Obiekt questa siedzi w środku ale klatki otwarte.
Nie można pobrać nast. z łańcuszka.

<a href="http://www.fotosik.pl/zdjecie/c594f4525e5126eb" target="_blank"><img src="http://images75.fotosik.pl/638/c594f4525e5126ebmed.jpg" border="0" alt="" /></a>

Edit: 31.05/16:34 Sytuacja bez zmian.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/5982
