### ISSUE TITLE
[EN][Spell][Priest] Shadow word: Death

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#7529]
SW:D does not break gouge with pw:s up or/and divine aegis. It should break it like it does with any other stuff like scatter blind etc etc.

SW:D --> http://cata.openwow.com/spell=32379
Gouge --> http://cata.openwow.com/spell=36862
PW:S --> http://cata.openwow.com/spell=68032
DA --> http://cata.openwow.com/spell=47515
HC --> http://cata.openwow.com/spell=49203
# UPDATE

It should not break dragon breath however as Sand3r wrote it should break Hungering Cold

**Comment by blinkmaster** [comment]
Actually i also think swd doesnt brake dragons breath, not sure if this is intended tho cóż swd can be Type of dot damage thus not destroys mg it with backlash damage

**Comment by Sand3r-** [comment]
It also doesn't break the Hungering Cold

(it should : http://www.skill-capped.com/forums/showthread.php?15800-Stuff-we-can-shadow-word-Death&p=103112 )

**Comment by Aival94** [comment]
Other bug: https://github.com/Atlantiss/BugTracker/issues/7347

**Comment by TranceAccount** [comment]
Please confirm.

**Comment by blinkmaster** [comment]
Still bugged

**Comment by tito38** [comment]
Played arena and the SWD cant remove Dragon's Breath.
Still bugged. Confirm.

**Comment by debtheone** [comment]
Bug still exists.

**Comment by debtheone** [comment]
bump?

**Comment by Purpleness** [comment]
bump, still doesn't break dragon's breath

**Comment by debtheone** [comment]
swd aint supposed to break db :^)

**Comment by lamaATS** [comment]
SW:D does NOT break Dragon's Breath and it shouldn't because DoTs are not breaking Dragon's Breath.
It's blizzlike mechanic.

**Comment by lamaATS** [comment]
Fixed in rev. 5510
