### ISSUE TITLE
[En][Quest]A Ritual of Flame [Molten Front]

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7536]
Apon taking the quest, you get 105/105 ritual progress, therefore nothing you do can progress the quest, preventing you completely of progressing the quest chain.
![wowscrnshot_060116_063729](https://cloud.githubusercontent.com/assets/16594771/15698288/571abdf8-27c3-11e6-853f-ed1481886160.jpg)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7366
