### ISSUE TITLE
[EN][NPC] vaelastrasz the corrupt

### ISSUE THREAD

**Issue by phantomgodx** [Atlantiss/BugTracker#7538]
vaelastrasz the corrupt is bugged,after you talk to him he should turn hostile but he doesnt,it worked perfectly fine a day ago,now it doesnt and i dont know why.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6550

**Comment by phantomgodx** [comment]
Note: It worked yesterday on my twink,I don't know what the problem is honestly. Without this boss I can't go to other bosses and get my transmog , so please fix this soon as possible,thanks.
