### ISSUE TITLE
[EN][RAID][Blackwing Lair] Vaelastrasz the Corrupt

### ISSUE THREAD

**Issue by Drackous** [Atlantiss/BugTracker#7539]
The 2nd Boss (The Sleeping drake) can't be started. After you talk to him. he stays there doing nothing.

**Comment by Prodiege** [comment]
It can, the leader of the group needs to start it; otherwise this bug occurs. Still a bug, everyone should be able to start it

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/6550

**Comment by krelein** [comment]
This boss is bugged out again ;/. Now even leader can't activate the boss.
