### ISSUE TITLE
[EN][Quest][Deepholm] Testing the Trap

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#7540]
In the quest [Testing the Trap](http://www.wowhead.com/quest=26771/), you don't get credit if the [Stonescale Matriarch](http://www.wowhead.com/npc=44148) dies due to the damage from the trap. You only get credit when you do most of the damage yourself.

**Comment by Aival94** [comment]
I did it before some days and got credit normally.If you let mob die from the traps you probably do not take credit but if you normal dps it you get and i believe this was blizzlike.

**Comment by lameia** [comment]
Works normally. Have done few days ago.

**Comment by tomatosz** [comment]
In that case I have misunderstood what it should be like as blizzlike, thought you should get credit without doing damage/doing little damage.
