### ISSUE TITLE
[EN] [Quest] [BloodElf] [SilverPine Forest] On her majesty's secret service

### ISSUE THREAD

**Issue by EyalAndOmer** [Atlantiss/BugTracker#7542]
The Quest Starter NPC Lord Godfey : http://www.wowhead.com/npc=45878/lord-godfrey
isn't opening the quest (i have done all the others in this region)

**Comment by Bildo** [comment]
duplicate

**Comment by RastaTinu** [comment]
Quest still doesn't work
