### ISSUE TITLE
[EN][Object-Questgiver][Southern Barrens] Roadway Plans

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#7544]
**Problem:** The item [Roadway Plans (ID: 49776)](http://www.wowhead.com/item=49776/roadway-plans) is missing from the loot of the NPC [Honor's Stand Officer (ID: 37216)](http://www.wowhead.com/npc=37216/honors-stand-officer) that it should have 72% of chance to loot. I've killed something like 20 times him, but no1 of them drop the item.

The quest that the item unlock is: [The low road (ID: 24518)](http://www.wowhead.com/quest=24518/the-low-road)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/4938

**Comment by Angelo-DM-** [comment]
#4938 is closed, but the item still not availlable from the NPC.
