### ISSUE TITLE
[EN][Spell][Class][Minor]Pick Lock(ID 1804)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7551]
Seems that some(if not all) rogue trainers are outdated and still learn [Pick Lock](http://www.wowhead.com/spell=1804/pick-lock) at level 16 instead of 20( Cataclysm Patch 4.0.1 (2010-10-12): Pick Lock now skills up as you level, you no longer need to practice. Hovering over your Pick Lock icon will show the current level of box you can open. Now learned at level 20 (was 16).)

Wowpedia Link: [Pick Lock](http://wow.gamepedia.com/Pick_Lock)
[Rogue Trainers](http://wow.gamepedia.com/Rogue_trainers)

**Comment by user1011** [comment]
Fix posted on the forums.
