### ISSUE TITLE
[EN] [Raid] Rhyolith HC

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#7553]
We have tested Rhyolith in 10hc mode,and we encountered the following bugs:

- no liquid obsidian spawns when Rhyolith steps on an active volcano;
- there are too many active volcanoes and healing isn't sustainable(should be only 1 active volcano at a time);

**Comment by Quban** [comment]
because there is a lot older rev on ptr than on main ;p this is fixed
