### ISSUE TITLE
[EN][Raid][Firelands] Majordomo Staghelm HC

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#7554]
We tested Majordomo 10 HC and we found the following bugs:

- burning orbs disappear immediatly;
- concentration isn't resetted when taking damage from the seeds;

**Comment by Quban** [comment]
> burning orbs disappear immediatly;

this is coz ptr havent been updated yet, 

> concentration isn't resetted when taking damage from the seeds;

i ll look into it

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the Spells and NPC.
