### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] Stasis Chambers of Bash'ir

### ISSUE THREAD

**Issue by Rinniel** [Atlantiss/BugTracker#7556]
http://www.wowhead.com/quest=10974/stasis-chambers-of-bashir

Problem 1: The boss appears after opening the Stasis Chamber but it only respawns after a server restart or server crash.

Problem 2: Even if you manage to get the [Evidence from Alpha](http://www.wowhead.com/item=32061), the [Image of Commander Ameer](http://www.wowhead.com/npc=22919/image-of-commander-ameer) is not spawned so there is no way of finishing this quest.

**Comment by Bildo** [comment]
fixed
