### ISSUE TITLE
[EN][NPC]Twilight Highlands]Gronk Hamcheeks

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#7557]
http://www.wowhead.com/npc=57262/gronk-hamcheeks#comments

He is supposed to be right next to the quest giver for the crucible of carnage since patch 4.3.0 he seels stuff for 2 achievements since the other 2 vendors become phased once you finish of Hyjal quests

**Comment by Thefakemccoy** [comment]
Duplicate 
https://github.com/Atlantiss/BugTracker/issues/6059
