### ISSUE TITLE
[EN][Item]Apparatus Of Khaz'Goroth

### ISSUE THREAD

**Issue by Kiferr** [Atlantiss/BugTracker#7558]
It should give highest of Haste/Mastery/CritChance but It Always gives me (Retribution Paladin) Crit chance (with 8Haste, 11CritChance, 15Mastery)

**Comment by Jenovas** [comment]
Please tell me what stats you have both % values and rating values.
For example:
I have 32% crit  - which is 3100 crit rating
I have 15% haste - which is 1500 haste rating
I have 22 mastery - which is 2900 mastery rating

**Comment by Kiferr** [comment]
K Nvm Thank u ^^
