### ISSUE TITLE
spell reflection hammer of wrath

### ISSUE THREAD

**Issue by Bhaals** [Atlantiss/BugTracker#7559]
i remember this being spell reflected

**Comment by mati865** [comment]
> i remember this being spell reflected

Is it all you have to say? No proofs?

**Comment by Vyrtuz** [comment]
I found some info on forums:
"The Hammer of Wrath is a ability with melee hit cap, deals magical holy damage which there is no resistance to in game AND is considered a physical attack."
(http://eu.battle.net/wow/en/forum/topic/975219082)
&
"Hammer of Wrath is considered melee attack doing holy damage just like Judgement. Both of them were never able to be reflected. Exorcism and Hammer of Justice were always considered spells. So they can and always could be reflected"
(http://eu.battle.net/wow/en/forum/topic/975219082?page=2)
&
"Hammer of wrath is considered a 20-yard melee attack"
(http://www.wowhead.com/forums&topic=106044/list-of-spells-that-can-be-reflected)
