### ISSUE TITLE
[EN][CORE]You have entered too many instances recently

### ISSUE THREAD

**Issue by KubKub5** [Atlantiss/BugTracker#7563]
I entered Magisters' Terrace with my main character (killed first boss, exited and reset) for five times.

After the fifth it said (as it should): You have entered too many instances recently.

After i log in with my alt character; however, and tried to enter Naxxramas as well as Firelands, i couldn't enter. Yet again it said: You have entered too many instances.

Note: My alt has not been saved in any normal, heroic or raid and i was in a raid group when i tried to enter Naxx and FL.

Problem: My main is locked in all instances for an hour ( as he should), but my alt is locked as well.

**Comment by HCGWill** [comment]
Instance lockouts are account wide. 

http://wowwiki.wikia.com/wiki/Instance_limitations?oldid=2476638
"Note: The number of instances you can enter is linked to your other characters on the same account as well. This means that if you have reached the entering limit on character A, character B will not be able to enter any instance."
