### ISSUE TITLE
[EN][Quest][Twilight Highlands] Small Comforts

### ISSUE THREAD

**Issue by abanator** [Atlantiss/BugTracker#7566]
I was doing the quest called **Small Comforts** for like 15 minutes. After that I watched a video and looked  where the **quest items** are. I went to the exact positions where he was on the video and **they weren't there**. On the video the village was on fire, but in my game it's not. I can't continue my quests in Twilight Highlands because of this quest.

**Comment by Thefakemccoy** [comment]
So here is the issue with small comforts. If the buildings are no longer on fire that means you have phased the area. Making that quest incomplete able. This was a big issue Blizz had on retail during cata. It was eventually fixed at some point.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/7157

**Comment by ofelia59** [comment]
I have the same i cannot complete this
