### ISSUE TITLE
[EN][Quest][Classic][Blasted Lands] You Are Rakh'likh, Demon

### ISSUE THREAD

**Issue by Karathe** [Atlantiss/BugTracker#7567]
Quest works fine however the area in which encounter occurs doesn't seem to reset if player gets killed during fight. Due to that if one dies, lather there are too many enemies which leads to being contantly overwhelmed.

I suggest adding some mechanism to reset that particular area in case of death.

**Comment by Bildo** [comment]
npc reset takes 3 minutes
