### ISSUE TITLE
[EN][Quest]Darkshore]The Eye of All Storms

### ISSUE THREAD

**Issue by DanyelSnow** [Atlantiss/BugTracker#7568]
Thessera stuck in the vortex , doesn't want to land , besides that the portal is missing which doesn't allow me to complete the quest , please fix it , add the portal , thanks :)

**Comment by Bildo** [comment]
duplicate

**Comment by DanyelSnow** [comment]
Thansk for fixing , works perfectly , that's the third time when i am talking about this issue
