### ISSUE TITLE
(Ita)Quest Tanaris Rocket rescue

### ISSUE THREAD

**Issue by Crazyalex91** [Atlantiss/BugTracker#7569]
Hi i think the quest is not already good fix because,when i m jump in the balloon rescue i haven't any attack or supplies for rescue the goblin or slain the pirates...i don't know why...could you please have a look thanks you!

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/384 duplicate

**Comment by Crazyalex91** [comment]
so what i have to do to complete the quest? :D

**Comment by Bildo** [comment]
If it's not working then you simply can't complete :P
