### ISSUE TITLE
[EN/PL][Quest][Twilight Hihglands] Twilight Shores

### ISSUE THREAD

**Issue by Wasod** [Atlantiss/BugTracker#7570]
http://www.wowhead.com/quest=28238/twilight-shores
There is no Fargo Flintlocke at Stormwind Harbor therefore u can't progress the TH questline at all, it's weird because I know this quest worked a while ago...

Nie ma Fargo Flintlocke w Stormwind Harbor przez co nie można kontynuować questów TH, dziwne, bo wiem, że jeszcze jakiś czas temu działał dobrze...

**Comment by Thefakemccoy** [comment]
Open a ticket ingame and a gm can fix this for you.

**Comment by Wasod** [comment]
Suddenly it worked, so nvm.
