### ISSUE TITLE
[EN][Raid][Karazhan] Malchezaar

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#7571]
Okay so the last two times I did Malchezaar in Karazhan the drops were really weird:
-The first time there was no T4 headpiece token.
-The second time there was no loot at all. 
Unfortunately I didn't make any screenshots at the time since this isn't a major issue. Still, I would greatly appreciate if someone could look into it whenever he gets the chance.

Cheers

**Comment by mean931** [comment]
Can confirm this, I will try taking some screenshots myself next time I've got the occasion, the loot for malchezaar it's not balanced atm

**Comment by MichaelArchangelo** [comment]
It's not the case with just Malchezaar, it's the case with every vanilla and tbc raid. I've seen 4 bosses in a row drop 1 to 0 items. Sometimes they drop none, sometimes they drop 6-8. The loot tables are crazy.

**Comment by BilboBagosz** [comment]
In last wednesday i killed him and nothing dropped from him. Two weeks ago dropped only bow. Someone could look on loot tables :)

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the NPC.

**Comment by MichaelArchangelo** [comment]
There's no point in giving a link to a single NPC, when the entire loot tables of vanilla and tbc bosses are screwed up. An issue should be opened describing the bigger problem.

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11636-7571-malchezaar-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
