### ISSUE TITLE
[EN] [Quest] In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by Cardonix** [Atlantiss/BugTracker#7572]
The machineguns and flying NPC's don't appear(probably phasing isn't scripted) - ruins all Krom'gar's chain

**Comment by Bildo** [comment]
duplicate

**Comment by Cardonix** [comment]
Still doesn't work, nothing is happening, maybe you've meant i should provide more information?

**Comment by Bildo** [comment]
This quest is already reported, we dont neeed second
