### ISSUE TITLE
[EN][Firelands][NPC][Ragnaros][Loot table]

### ISSUE THREAD

**Issue by EnPra** [Atlantiss/BugTracker#7576]
http://www.wowhead.com/npc=52409/ragnaros
Not 100% sure but i think ragnaros loot table might be a bit off.
For example i've never seen http://www.wowhead.com/item=68995/vessel-of-acceleration drop from ragnaros. I've thought it might have been a string of bad luck at first but now after 5 months of raiding firelands 2-3 times a week i still havent seen it drop. 18% chance that it drops vs 5% for sulfuras, and i've seen sulfuras drop atleast 10 times(also seen 2x Smoldering Egg of Millagazor @1.5%). Is it bad luck, or there are some other raiders that can confirm this(assuming you have been doing fl for a longer period)?

**Comment by Trunta** [comment]
Can confirm this

**Comment by Wasod** [comment]
I saw the vessel dropped 2 days ago on my FL, so I guess bad luck, not sure about the correct % drop rate though...

**Comment by EnPra** [comment]
@Wasod  yeah it definately drops, ive seen ppl with it, but not too many... and im not exaggerating, its been almost 5 months of killing ragnaros 1-3x a week. everyone who wanted matrix or capacitator got it on multiple alts

**Comment by Kozakko** [comment]
that is just bad luck, on our fl raids vessel dropped 2 times in a row.

**Comment by arekczup** [comment]
Vessel of Acceleration drop many times on my raid . Arathar, the Eye of Flame drop 1 time and have 15% to drop  . sulfuras drop 4 times ......

**Comment by EnPra** [comment]
@arekczup yeah, sulfuras seems to be very common despite the supposed 5% drop chance

**Comment by LaveniaGithub** [comment]
Well, I myself have seen Vessel drop a bunch of times. Have never seen Smoldering Egg of Millagazor, so it might just be bad luck, idk.

**Comment by Illusie** [comment]
Lolz i'm doing FL since it released. Lets say 5 months? Still haven't Capacitor.
I saw it only one lost the roll. feeling unlucky.

besides saw all the other stuff drop many times. except Crown of Flames & Roaring Flames.
far 5 items from BiS. while in my mind i know people BiS in less than two months.
