### ISSUE TITLE
Westfall/Moonbrook

### ISSUE THREAD

**Issue by TheTrashmaster** [Atlantiss/BugTracker#7577]
I'm not very familiar with bugs, but I do know that this is something quite gamebreaking.
As a person who likes to do quest, I'd like to get that House of Wrynn gear you get from completing Westfall's questline. But at the mission "A Vision Of The Past" I got stuck. When completing the quest before, it must've auto completed this one, 'cause I couldn't accept it, and just gives me the text: "Complete Quest", and when I click it, it does nothing. Also it can be noted that the questionmarker over the questgiver, who is "Thoralius The Wise", is blue, as if it was a Daily Quest.
So. Since I don't know much about the problem, my submission ends here.
I hope that it can be fixed, as that I really enjoy playing on this server
Thank you
TheTrashmaster

**Comment by Xenerus** [comment]
https://github.com/Atlantiss/BugTracker/issues/6212
