### ISSUE TITLE
[rogue] [guest] rocket rescue 

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#7578]
balon posiada moje skile przesto nie moge zrobić questa
![wowscrnshot_060616_155637](https://cloud.githubusercontent.com/assets/8699987/15824398/4a2a01ea-2bff-11e6-8093-adf6f301b14e.jpg)

**Comment by Kozakko** [comment]
Autor jest zbyt leniwy aby poszukać pozdrawiam https://github.com/Atlantiss/BugTracker/issues/384

**Comment by arekczup** [comment]
pokazałeś tylko stare zgłoszenie w którym  był auto ukończenie
