### ISSUE TITLE
[PL][Quest][The Cape of Stranglethorn] Drive-By Piracy

### ISSUE THREAD

**Issue by Mihu44** [Atlantiss/BugTracker#7579]
Quest http://www.wowhead.com/quest=26649/drive-by-piracy 

Po pogadaniu z NPC stojącego obok łódki postać jest teleportowana na nią, lecz łódka ta nie odpływa. Po zejściu z niej można znów z tym NPC pogadać przez co czynność ta znów zostaje wykonana i tak można na okrągło, co skutkuje tym, że quest nie może zostać wykonany (na załączonym obrazku widoczne są łódki stworzone w ten sposób)

![wowscrnshot_060616_225613](https://cloud.githubusercontent.com/assets/19785736/15837629/5a962640-2c3a-11e6-9eb9-b5f44e44aadd.jpg)

**Comment by Bildo** [comment]
duplicate
