### ISSUE TITLE
[EN][Web] Shop History typo

### ISSUE THREAD

**Issue by Cellhawk** [Atlantiss/BugTracker#7581]
I think the title is well explained in the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/8853211/15919380/16a6134a-2e11-11e6-9dd0-908680111cb6.png)

**Comment by VioletFlare** [comment]
You could at least say where's the typo. 
It's "expirence" in the reward column, i guess.

**Comment by Cellhawk** [comment]
Ah sorry. Changed the screenshot and forgot to specify the typo. Yes, you're right, it's the "expirence" one.
