### ISSUE TITLE
[EN][Dungeon/Quest] Stasis Chambers of the Mana-Tombs

### ISSUE THREAD

**Issue by Rinniel** [Atlantiss/BugTracker#7583]
http://www.wowhead.com/quest=10977/stasis-chambers-of-the-mana-tombs

Problem: There is no Stasis Chamber inside [Mana-Tombs](http://www.wowhead.com/zone=3792/mana-tombs) heroic.

**Comment by TranceAccount** [comment]
#7584

**Comment by Bildo** [comment]
actually its not related :D

**Comment by TranceAccount** [comment]
Lol okay
