### ISSUE TITLE
[EN][Dungeon/NPC] Yor in Mana-Tombs Heroic

### ISSUE THREAD

**Issue by Rinniel** [Atlantiss/BugTracker#7584]
http://www.wowhead.com/npc=22930/yor

Problem: The Stasis Chamber to summon [Yor <Void Hound of Shaffar](http://www.wowhead.com/npc=22930/yor)> is not there in [Mana-Tombs](http://www.wowhead.com/zone=3792/mana-tombs) heroic.

How it should work: There should be a Stasis Chamber in the same room with Nexus-Prince Shaffar to summon Yor, as shown on [this video](https://youtu.be/ztFkxu772is?t=3m57s).

**Comment by Bildo** [comment]
fixed
