### ISSUE TITLE
Quest Bugged" Druid of The Claw

### ISSUE THREAD

**Issue by adorcik** [Atlantiss/BugTracker#7586]
the spirit of Oben Rageclaw is giving you that quest  and u need to find body of rageclaw which is  behind the Barrows doors  unfortunately even when u obtained the quest the doors are still locked so u cant reach the rageclaw soulless body and u cant kill it to cleanse it 
http://www.wowhead.com/quest=2561/druid-of-the-claw

**Comment by Bildo** [comment]
read bt rules
