### ISSUE TITLE
[EN][quest][Druid of the Claw]

### ISSUE THREAD

**Issue by adorcik** [Atlantiss/BugTracker#7587]
quest - http://www.wowhead.com/quest=2561/druid-of-the-claw
the NPC http://www.wowhead.com/npc=7317  is giving you that quest and u need to find his body which is behind the Barrows doors-http://www.wowhead.com/quest=2561/druid-of-the-claw#videos:id=80237 unfortunately even when u obtained the quest the doors are still locked so u cant reach the rageclaw body

**Comment by Aival94** [comment]
reported: https://github.com/Atlantiss/BugTracker/issues/643
