### ISSUE TITLE
[EN][Quest][Teldrassil] The Relics of Wakening

### ISSUE THREAD

**Issue by adorcik** [Atlantiss/BugTracker#7588]
Quest - http://www.wowhead.com/quest=483/the-relics-of-wakening
In This quest the object http://www.wowhead.com/object=2742/chest-of-nesting its empty 
and it suppose to contain http://www.wowhead.com/item=3408/rune-of-nesting

**Comment by Aival94** [comment]
Have done it before a week and i worked just fine.Are you sure you have not looted the item before or your bags are full?

**Comment by adorcik** [comment]
yes im sure of that i was waiting there yesterday 2 hrs with ticket opened 23 free bag space standing in one place and opening that box anyone who passed me was asking is it bugged? - so i gues no one could loot it

**Comment by adorcik** [comment]
well i log in today and still no loot the loot box doseant even shows if its important tho u just open it and nothing is happening

**Comment by adorcik** [comment]
i'm so dissapointed i know that 2 quest doesnt shows the server but im new player and these are q in starting location  well.. in my opinion this quests should be shining above others cause when new player comes and see this he trhink wtf im done with this server 2 quest in one place bugged

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/11983-7588-chest-of-nesting-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
