### ISSUE TITLE
[EN][quest][The Shimmering Frond]

### ISSUE THREAD

**Issue by adorcik** [Atlantiss/BugTracker#7590]
http://www.wowhead.com/quest=931/the-shimmering-frond
as you can see at the description of quest the NPC - http://www.wowhead.com/npc=2080/denalan
"can usually be found at Lake Al'Ameth, but sometimes travels to Wellspring Hovel"
after receiving the quest i linked above he didn't start to travel from lake to wellspring but system just made a copy of the NPC, and this copy is standing just right  beside the original NPC. He is not traveling just standing there and u can turn in quest at both of them - i suggest or just delete the script that make the copy cause traveling doesn't work so why we need 2x Denelan in one place.

**Comment by TranceAccount** [comment]
#5536
