### ISSUE TITLE
[Server bug] Mirror image

### ISSUE THREAD

**Issue by Bhaals** [Atlantiss/BugTracker#7594]
SO yesterday in arena a mage used mirror image before i charged so i would lose my target, so i quickly tabbed and targeted him again, but then i lost my target and it targeted the mirror image again.. this is impossible due to the fct that i have tab set to enemy players only  , i suspect the spell que

**Comment by Piklo** [comment]
Kinda bad title, next time read it https://github.com/Atlantiss/BugTracker

**Comment by TranceAccount** [comment]
If the enemy spawns his Mirror Image, his mirror images will be enemies towards you too, so if you press tab to target another enemy it will select one of the 4 current enemies.
If you don't agree with this, make a new report and follow the _How to use_: https://github.com/Atlantiss/BugTracker#atlantiss-core-4
