### ISSUE TITLE
[En][Quest]Compendium of the Fallen Scarlet Monestary quest

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7595]
![wowscrnshot_060816_212008](https://cloud.githubusercontent.com/assets/16594771/15907901/58e8211e-2dbf-11e6-8e72-0214b4c4c331.jpg)
after getting the quest, the book cant be clicked as you can see, making the quest undoable.

**Comment by Cellhawk** [comment]
https://github.com/Atlantiss/BugTracker/issues/1559
