### ISSUE TITLE
[PL][Warlock][Spell] Summon Doomguard

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#76]
http://www.wowhead.com/spell=18540/summon-doomguard

Po przywołaniu Doomguard nie aggruje się na kukłach, które bijemy. Nawet gdy przywołamy go przed wejściem w CB. Doomguard nie castuje spelli, ani nie autoattackuje. 
Nie wiem jak to wygląda na mobach  ani w pvp, na kukłach nic nie robi.

**Comment by fafal** [comment]
Obecnie doomguard nadal jest marny. ba bije nawet mocniej w destro niz w demo co jest niedorzeczne bo w demo widocznie mocniejszy jest poprzed scallowanie z mastery. Porownujac dla demo poprzez simcrafta / filmiki z yt i comment z EJ powinien być dmg być ponad 2x większy gdzie hity na raidach spokojnie powinny przekraczać 18-22k. Obecnie ten dmg jest marny ;s
Dodatkowo potrafi bić z melee na melee range co nie powinno mieć miejsca.

**Comment by fafal** [comment]
Jako że był update do dooma to:
1. Pet nie skaluje się z Mastery w Demo
2. Petowi zdarzało się missnać doombolta co przy hit capie właściciela nie powinno mieć miejsca
3. Dosyć regularnie ma problemy z aggrowaniem się z automatu w target, cześto jak podejdzie do targetu to zadaje 1 do max 2 ataków melee

**Comment by Bildo** [comment]
meele to wina zlego sa, poprawie to niedlugo

**Comment by Jenovas** [comment]
Bildo zrób SAI żeby chain castował + wyłącz melee, skalowanie z mastery etc. ja postaram się dorobić.

**Comment by Varchord** [comment]
O a ja miałem nowy issue robić. Ten Doomguard to missuje  na potęge :P

**Comment by fafal** [comment]
Po ostatniej poprawce:
-Melee ataków już nie było (conajmniej na paru próbach nie zauważyłem)
Nadal źle z:
-Missuje mimo hit capa właściciela (ostatnio na missie miałem ok 25-30%)
-Brak scalowanie z mastery w demo

**Comment by fafal** [comment]
Jeszcze pare drobnostek :P 
Will automatically attack the target currently afflicted by your  [Bane of Doom] or  [Bane of Agony] (or Bane of Havoc). http://wow.gamepedia.com/Doomguard_(warlock_minion)
Gdy jest jeden cel to jeszcze ok, ale przy dwóch to at random sb wybiera target chyba, nie mam pojecią, na pewno nie kieruje się bane.

Nadal potrafi używać melee ataków, wydaje mi się że może być to dlatego kiedy jego poprzedni cel zginął ale nie mam pojęcia.

**Comment by kadi2** [comment]
Doomguard chyba ma tutaj piorytet melee ponad doombolty, jezeli jest w melee range.

**Comment by fafal** [comment]
Wydaje mi się że raczej nie, wiele razy go summałem na melee range i nie było tego problemu. To raczej chodzi o coś innego ale nie jestem w stanie sprecyzować.

**Comment by Jenovas** [comment]
A jak tam missy, crit i skalowanie z mastery?

**Comment by fafal** [comment]
Missów nie ma, conajmniej nie zauważyłem na żadnym pecie locka ani guardianie. Skalowanie się - tyle widać że w demo wyraźnie już lepiej bije więc wygląda jakby działało. Crit u petów działa, nie spr co do guardianów, w najbliższym czasie zobacze.

**Comment by Varchord** [comment]
Doomguard nie zaczyna atakować jak jest się daleko od targetu :<

**Comment by kadi2** [comment]
@Varchord zaczyna atakowac pierwszy target z ktorym wejdzie w combat i prawdopodobnie nie zmienia targetu dopoki nie umrze pierwotny cel. Niektore Hostile NPC maja to do siebie, ze stojac z nimi w melee range nabijaja combat wszystkiemu dookola combat. Jak stoisz zbyt daleko od bossa, twoj pet nie dostaje zadnego dmg podczas encountera ktory mialby spowodowac wejscie w combat twojego peta to twoj pet nie zacznie atakowac.

PS: Czy ktos sprawdzal DMG samego Doombolta?

**Comment by adryjan** [comment]
Ciężko bo nie mogłem go zmusić do bicia dummy.

**Comment by fafal** [comment]
http://zapodaj.net/e42b6657563a1.jpg.html
przy ponad 2k mastery w demo i odpałkach wyciąga prawie pół miliona, hity obok na dole, i mniej wiecej u mnie takie wyniki osiąga, 
http://zapodaj.net/c378a148ec18e.jpg.html
Crit jest na poziomie zwykle 25-28% na około 10 próbach.
Jak łatwo zauważyć u mnie średnio osiąga 19 dooboltów, wg choćby SC powinno być to 22 (nawet matematyka wskazuje na 21-22) szukając zaginionych doomboltów można zauważyć:
http://zapodaj.net/bffa8959a618a.jpg.html
2 melee swingi, pet był odpalony na melee zasięgu (BH), mniej więcej ost na chogallu było to samo, także były 2 melee ataki na single target.
Co do dmg jak pamięta to dla destro/afk bez itemów i telanetów było to 6k od bolta, z ponad 10, dla demo oczywiscie odpowiednio wiecej. Ustawiajac w SC odp rzeczy i profile, z/bez pierdól dmg był zbliżony generalnie +-500, już nie posiadam logów, niestety skasowałem ;/ 
Generalnie przeszukałem też kawał internetu i youtube w poszukiwaniu jakiś formól ale do guardianó locka nie potrafie ich znaleść niestety. Ale jestem prawie na 90% pewien że jeśli dmg coś odbiega to jest już mała różnica i w każdym bądz razie ten guardian coś już bije.

Wiadomo że jak jest za duży range to nie bije, mozę właśnie atakowanie targetu z Bane of Doom/Agony tak jak powinno być zresztą co udowodniłem pare postów wcześniej załątwiło by sprawe? No i niestety nie mam pojęcia o co chodzi z tymi melee swingami.

**Comment by fafal** [comment]
Bump!
Nadal źle się aggruje, użyty gdy w pobliżu jest więcej targetów potrafi odwalać maniane i atakować zły target albo bić melee ;c nie mówiąc że trzeba być blisko targetu bo nic nie robi! ;c
Po dłuższym sprawdzaniu - on crituje zwykle dosyć nędznie więc prosiłbym o sprawdzenie tego czy wszystko jest ok ;c
Nadal bije melee czasami ;c

**Comment by Wulgarny** [comment]
Bump! 
Warlocki nadal czekają :c

**Comment by Varchord** [comment]
#NobodyCaresAboutWarlocks
#EclipseStillBugged
Taki hip i modny jestem, że hasztaga używam ^^

**Comment by Wolffenstein** [comment]
#NobodyCaresAboutWarlocks - taaa

Fixed in rev 4441. Jakby cos jeszcze bylo z tym nie tak to proszę o nowe zgłoszenie.
