### ISSUE TITLE
[EN][Gameobject][Ironforge] Hall of Explorers

### ISSUE THREAD

**Issue by Cellhawk** [Atlantiss/BugTracker#7600]
Multiple signs in Ironforge Hall of Explorers seems to be misplaced.
Location is roughly here:
![image](https://cloud.githubusercontent.com/assets/8853211/15919533/a4c0ca5c-2e12-11e6-9285-9066c00c11ff.png)

**[Horde Catapult](http://www.wowhead.com/object=175688/horde-catapult)**
Issue looks like this:
![image](https://cloud.githubusercontent.com/assets/8853211/15919473/fad900fe-2e11-11e6-96fd-a0f6430d817b.png)

It should look like this:
![image](https://cloud.githubusercontent.com/assets/8853211/15919567/ddb010b6-2e12-11e6-904c-bb01c64bf051.png)

**[Toothgnasher's Skeleton](http://www.wowhead.com/object=175683/toothgnashers-skeleton)**
Issue:
![image](https://cloud.githubusercontent.com/assets/8853211/15919650/8707179a-2e13-11e6-9cf4-59878c5114d0.png)

Should look like:
![image](https://cloud.githubusercontent.com/assets/8853211/15919660/9c6f35fe-2e13-11e6-95ed-aead162383ae.png)

...and many more, you just take a look around the Hall of Explorers.

Edit: Signs can be hovered over, with tooltip showing the name of the object. The objects can be found in "Database > Objects > Books" section of Wowhead

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the misplaced Gameobjects.

**Comment by Cellhawk** [comment]
Updated.

**Comment by wtRCH** [comment]
fix pending.
