### ISSUE TITLE
[EN][Achievement] Icecrown: The final goal

### ISSUE THREAD

**Issue by Gajulus** [Atlantiss/BugTracker#7601]
Its part of the loremaster achievement and as far as I know it cannot be completed due to 3 bugged quests (maybe there are more, I only found these three):
New recruit  http://www.wowhead.com/quest=13143/new-recruit  - you can sudue the lithie stalker but it does not go to the questgiver 
That's Abominable!  http://www.wowhead.com/quest=13289/thats-abominable  - you can crate your own abomination but it dies after being hit just once by any mob, also the 'explode skill' doesn't work
Battle at Valhalas: Fallen Heroes  http://www.wowhead.com/quest=13214/battle-at-valhalas-fallen-heroes  - the mobs appear after the quest is started but killing them des not trigger the objective so u cannot finish it

That's all of them - I guess after fixing theese ones the achievement should be doable.

**Comment by LaveniaGithub** [comment]
I completed the achievement about two weeks ago.

I did both That's Abominable! and New Recruit, so they're completable, but could use some fixing to make it more blizzlike.

Try to aggro the mobs yourself before summoning your Abomination, makes the quest easier to complete since they won't attack your Abomination if you've attacked them first.

**Comment by Tigerief** [comment]
if you do the legendary blade quest chain from the battle hilt item you can finish the zone ALOT easier :)

**Comment by Gajulus** [comment]
@LaveniaGithub Thank's for advice  - it worked and I menaged to finish That's Abominable and the following ones after it. But I still cant do New Recruit and I stopped at 135 (I also did the legendary sword chain to the moment till the quests count for loremaster). Can you maybe tell me how you menaged to do New Recruit?

**Comment by Tigerief** [comment]
i remember i reached a point where the zones chains from the ship just were bugged and uncompletable and that the 1 was completable but WAAAAAAAAAAAAAY to hard and would take to long, thats abominable is buggy and hard but i did manage to do it after a struggle i cant :l but as i said, the legendary chain is best way to do it. i never did new recruit :D cause i didnt need to

**Comment by Bildo** [comment]
1 quest 1 ticket
