### ISSUE TITLE
[EN][Deepholm][Quests][Minor]Quests Order

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7605]
Quest [That's No Pyramid!(A)](http://www.wowhead.com/quest=28292/thats-no-pyramid) should be available after completing quest [The Wrong Sequence(A)](http://www.wowhead.com/quest=27058/the-wrong-sequence)

Quest [The Explorers](http://www.wowhead.com/quest=27952/the-explorers) should become available after reaching 83 level but on server seems to have a prerequisite.

[Don't. Stop. Moving.](http://www.wowhead.com/quest=26656/dont-stop-moving) should be available after completing quest [Steady Hand](http://www.wowhead.com/quest=26576/steady-hand)

[Loose Stones](http://www.wowhead.com/quest=26375/loose-stones) should be available after completing quest [Rocky Relations](http://www.wowhead.com/quest=26328/rocky-relations)

[Unsolid Ground](http://www.wowhead.com/quest=26377/unsolid-ground) should be available after completing quest [Rocky Relations](http://www.wowhead.com/quest=26328/rocky-relations)

 [Hatred Runs Deep](http://www.wowhead.com/quest=26376/hatred-runs-deep) should be available after completing quest [Rocky Relations](http://www.wowhead.com/quest=26328/rocky-relations)

**Comment by Vidyapoky** [comment]
Plus can confirm I didnt get the quest The Wrong Sequence on death knight but I had the quest That's No Pyramid!
Decryption made easy was completed with auto complete, so it is possible that it is buggy, but questgiver did not give quest either. [http://www.wowhead.com/npc=44799/explorer-mowi](url)

**Comment by Aival94** [comment]
@Vidyapoky Try to remove quest [The Wrong Sequence](http://www.wowhead.com/quest=27058/the-wrong-sequence) from the quest log as many times these kind of chains get bugged if you have or complete the next in order quest.

**Comment by Vidyapoky** [comment]
@Aival94 I didn't even get the quest, thats the point, I'm sitting on 109 quest in deepholm because of this on my alt. I completed the whole deepholm on main and I've only seen deepholm get buggier.

**Comment by Aival94** [comment]
Sorry meant the Tha's no Pyramid. I updated it :P

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11003-questnpc-next-fixs/
