### ISSUE TITLE
[EN][Quest][Ashenvale]Sentinel Basic Care Package(ID 7863) and Sentinel Advanced Care Package(ID 7865)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7606]
Quests should be available after reaching Friendly with [Silverwing Sentinels](http://www.wowhead.com/faction=890/silverwing-sentinels)

Wowhead Links: [Sentinel Basic Care Package](http://www.wowhead.com/quest=7863/sentinel-basic-care-package) and [Sentinel Advanced Care Package](http://www.wowhead.com/quest=7865/sentinel-advanced-care-package)

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11003-questnpc-next-fixs/
