### ISSUE TITLE
[EN][NPC] Xariona

### ISSUE THREAD

**Issue by Vidyapoky** [Atlantiss/BugTracker#7611]
![screenshot_37](https://cloud.githubusercontent.com/assets/1499989/15979932/81033a4a-2f67-11e6-8fd5-d1e9283b93cb.png)
World boss in deepholm doesnt drop right loot, instead drops low jc recipe.

http://www.wowhead.com/npc=50061/xariona#drops

**Comment by Vidyapoky** [comment]
> HP lowered to 12,883,800 in Patch 4.1. Drops the named epic loot and one of the boe world epics with ilvl 359. Seems to be a 100% drop chance for a second boe epic since Mobus and Xariona did drop a second boe epic today.

The second item was  Dizze's Whirling Robe.

According to my experience with the cataclysm world bosses and other posts on wowhead, the loot table seems to always contain the following:

    The epic item (359 ilvl) named after the boss.
    A random boe epic item off of the known world drop loot table (359 ilvl).
    A green jewel-crafting recipe.

Edit: Changed hp value to the actual value and added information about loot.

From comment on wowhead, the worldboss currently has 30M hp, and drops only the gem recipe

**Comment by TranceAccount** [comment]
Are you working on this @Vidyapoky ?

**Comment by Vidyapoky** [comment]
I was on holidays. I'm going to look into it now

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
