### ISSUE TITLE
[EN][Npc][Drop] Azshara Naga Drops

### ISSUE THREAD

**Issue by VioletFlare** [Atlantiss/BugTracker#7615]
The Nagas in Azshara drop high level items, [I got some high level (~40 lvl) items](http://i.imgur.com/NxV6lSl.jpg) near Forlon Ridge (26.8, 52.7), but I guess it applies to any naga found in Azshara.

[I'm quite sure these nagas are using the pre-cataclysm drop tables.](http://db.vanillagaming.org/?npc=6195#drop:100-13+1)

Nagas inspected:
- [Spitelash Screamer](http://www.wowhead.com/npc=6193/spitelash-screamer)
- [Warlord Krellian](http://www.wowhead.com/npc=8408/warlord-krellian)
- [Spitelash Myrmidon](http://www.wowhead.com/npc=6196/spitelash-myrmidon)

**Edit:**
Looks like the nagas aren't the only affected. I noticed the following mobs also drop high level items:
- [Makrinni Razorclaw](http://www.wowhead.com/npc=6350/makrinni-razorclaw)
- [Makrinni Scrabbler](http://www.wowhead.com/npc=6370/makrinni-scrabbler)
- [The Evalcharr](http://www.wowhead.com/npc=8660/the-evalcharr)

Found them at Bay of Storms (69.8, 77.3).

I think all of the old mobs who were downscaled might drop high level items.

**Edit 2:**
#7170

**Comment by Piklo** [comment]
posted fix on forum
