### ISSUE TITLE
[EN][Item] Black Diamond Ring

### ISSUE THREAD

**Issue by Velerios** [Atlantiss/BugTracker#7616]
Vendor [Haris Pilton](http://www.wowhead.com/npc=18756/haris-pilton) in Shattrath City does not offer the [Black Diamond Ring](http://www.wowhead.com/item=71037/black-diamond-ring#sold-by) to sell, which according to WoWHead was added in patch 4.2.0, and should be available in unlimited quantity for 3500 gold each.

**Comment by TranceAccount** [comment]
Posted a fix on the forums.
