### ISSUE TITLE
[NPC][QUEST] A vision of past 

### ISSUE THREAD

**Issue by Leg312** [Atlantiss/BugTracker#7617]
Thoralius the Wise should give quest "a vision of past" , he doesn't give it and if you click on him it says "complete quest" but clicking that doesn't make anything happen stoping whole questline.

**Comment by Cellhawk** [comment]
https://github.com/Atlantiss/BugTracker/issues/6212

**Comment by Leg312** [comment]
Ye I just wanted it to put it on 1st page again, maybe it was forgoten? idk just started to play so not sure how all of this works.
