### ISSUE TITLE
[En][Quest]Banish Some demons Ogri'la rep farm

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7619]
This quest is supposed to be available from honored. But i have been honored for a week now and its still not available. Even the quest that comes with the reward item from this quest is already available so it is supposed to be available.
![wowscrnshot_061216_085041](https://cloud.githubusercontent.com/assets/16594771/15989671/9f6af362-307d-11e6-91c5-719843981771.jpg)

Here is the proof that it should be available:   http://wowwiki.wikia.com/wiki/Ogri'la

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3180

BTW the quest [A Crystalforged Darkrune](http://www.wowhead.com/quest=11060/a-crystalforged-darkrune) has been removed on cata so do not even count it(Reported here as a comment: https://github.com/Atlantiss/BugTracker/issues/6576)
