### ISSUE TITLE
[PL][Quest]Soothing the elements 

### ISSUE THREAD

**Issue by doktorekg** [Atlantiss/BugTracker#762]
Zadania nie można wykonać. Stojąc w odpowiednim miejscu (klif przy czerwonym ołtarzu - The blazing strand) i stawiając totem, pojawia się tylko jeden lub dwa elementale. Zmiana miejsca nic nie daje. Próbowałem przez dwie godziny w każdym miejscu na klifie. 
http://www.wowhead.com/quest=13580/soothing-the-elements

**Comment by Hordraric** [comment]
i believe this is the last quest required to get the darkshore quests completed. i am 86/90 and according to addons seems its the only chain quest missing.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1521
