### ISSUE TITLE
The memory could not be "written"

### ISSUE THREAD

**Issue by Algosus** [Atlantiss/BugTracker#7621]
https://imagizer.imageshack.us/v2/782x412q90/924/hywoUY.png i have this issue

**Comment by VioletFlare** [comment]
If it happens after you close the game you can ignore it.

**Comment by Algosus** [comment]
it hapepent when i enter my password and press enter

**Comment by user1011** [comment]
http://community.atlantiss.eu/index.php?/topic/3865-how-to-fix-error-132-and-error-134/
