### ISSUE TITLE
My character is bugged

### ISSUE THREAD

**Issue by Funkeymytolo** [Atlantiss/BugTracker#7624]
Me and my friend were doing The Cruicble of Carnage, and the second character you had to fight did the thing where he picked you up, then smashed you into the rocks. However, once my friend deathgripped him as he was about to smash me into the rocks and now my character is stuck holding her staff and her head leaning to one side
![sdasdasdasdasds](https://cloud.githubusercontent.com/assets/19894335/15993594/318d4e76-30eb-11e6-8051-fe7c31c06a01.PNG)

**Comment by Luna-maria** [comment]
if it hasn't been fixed yet, you probably need to open a ticket ingame and wait for a gm to fix it for you :)

**Comment by Funkeymytolo** [comment]
*stares blankly into the abyss* but how

**Comment by Luna-maria** [comment]
click that red ? on your actionbar next to your bags > I want to talk to a gm/open a ticket (or something like that) and explain your issue there :)

**Comment by Funkeymytolo** [comment]
Thanks brah

**Comment by user1011** [comment]
Sometimes a suicide fixes visual problems.
