### ISSUE TITLE
[EN][QUEST]Twillight Highlands: Small Comforts

### ISSUE THREAD

**Issue by Vidyapoky** [Atlantiss/BugTracker#7627]
If you complete all quests while village is on fire except for this one, this quest will become uncompletable because you are phased.

Things should be in burning buildings, but since you completed all quests except this one, you are in different phase and can not complete this quest. Did this on DK with no problems because I completed it along with other quests such as dousing the fire and killing elementals. Yet I cannot do it on my hunter since I already did all these quests. 

Retaking does not work.

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/7157

**Comment by rdoherty0** [comment]
Still bugged
