### ISSUE TITLE
[EN][Quest][Death knight] Quest Brothers in Death (ID=12725)

### ISSUE THREAD

**Issue by thanhtotti** [Atlantiss/BugTracker#7630]
Link http://cata.openwow.com/quest=12725
koltira deathweaver can be targeted by /target but can't be seen
Please hot fix it ! Many DK are stucking here.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6147, https://github.com/Atlantiss/BugTracker/issues/1932
