### ISSUE TITLE
[EN][Raid] Heroic Cho'gall Conversion and Order Timers

### ISSUE THREAD

**Issue by HCGWill** [Atlantiss/BugTracker#7631]
There are 2 incorrect timers on this fight's heroic mode making it notably harder than it should be. Both the Conversion timer and the Flame/Shadow's Order timer should change when you enter Phase 2 (85%).

Retail Videos: 
1) https://www.youtube.com/watch?v=QjqyM8aefnk
2) https://www.youtube.com/watch?v=TOshtMTM2jA
3) https://www.youtube.com/watch?v=569IMakTY6k

**Flame/Shadow's Orders:**

Ability Timing on retail:

Phase 1:
- First Flame cast 5 seconds after pull
- First Shadow cast 20 seconds after pull
- Both are recast every ~37 seconds until boss hits 85%
- This means there is a 15s delay between Flames->Shadow, and a 22s delay between Shadow->Flames

Phase 2 (85%):
- All timers reset, first add is always Flame even if P1 ends with a Flame's Order (see video 3)
- First Flame cast 15 seconds after Fury of Cho'gall cast
- First Shadow cast 40 seconds after Fury
- Both are recast every ~47 seconds now.
- The delay is now 25s between Flames->Shadow and 22s between Shadow->Flames

Atlantiss video (6/14/16): https://www.youtube.com/watch?v=tKFagKn4DTM
This is a clip from our last raid, he's well into P2 but his Shadow/Flame's Orders are still being cast with P1 timers (35s cooldown, 13s delay between Flame->Shadow, 22s between Shadow->Flame). They should be on 45s cooldown, the extra 10 seconds makes Cho'gall damage throughput much higher than it should be in that phase.

**Conversion:**

Similar case here. In Phase 1, Conversion should have a 20 second CD. When you hit 85%, the Conversion timers is **not** reset, but Conversion will now have a 35 second CD after its next cast (see video 3). On Atlantiss, Conversion keeps its 20 second CD in Phase 2.

**Comment by HCGWill** [comment]
Quban pls <3

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5100
