### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Buried Blades

### ISSUE THREAD

**Issue by VioletFlare** [Atlantiss/BugTracker#7632]
In this quest, we need to use [Light-Touched Blades](http://www.wowhead.com/item=61302/light-touched-blades#provided-for) on [Slain Scourge Trooper](http://www.wowhead.com/npc=45695/slain-scourge-trooper).
The quest is completable, but we are allowed to use it multiple times on a single Slain Scourge Trooper.

Wowhead: http://www.wowhead.com/quest=27467/buried-blades

**Comment by BAndysc** [comment]
Fixed
