### ISSUE TITLE
[EN][NPC] Chef Audrey

### ISSUE THREAD

**Issue by VioletFlare** [Atlantiss/BugTracker#7633]
[Chef Audrey](http://www.wowhead.com/npc=53528/chef-audrey) is an NPC in Undercity who sells food. It is impossible to trade with her.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11598-7633npc-chef-audrey/

**Comment by Navedonar** [comment]
fixed

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
