### ISSUE TITLE
[EN][Dungeon][Raid]Trials of Champion/Crusader, not enterable when dead

### ISSUE THREAD

**Issue by Vidyapoky** [Atlantiss/BugTracker#7634]
As in title, you cannot enter these instances when you die, as you are too big to enter through gates along with your gryphon, only nelves with wisp form are sure to enter for now.

**Comment by ShadicSatan** [comment]
There's a workaround for this, Customer Support > Character Stuck > Teleport to graveyard. This will dismount you from the gryphon when you're dead.

**Comment by xolon** [comment]
Relog, and you can enter.

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/5959, https://github.com/Atlantiss/BugTracker/issues/6495
