### ISSUE TITLE
[PL][Quest][Darkshore] The Offering to Azshara

### ISSUE THREAD

**Issue by BiliBee** [Atlantiss/BugTracker#7636]
Po zabiciu 4 kaplanek pojawia sie Queen Azshara po czym natychmiast umiera i nie pojawia się Malfurion u którego oddaje się questa. Pomijam już brak całej scenki bo to detal, bądź co bądź quest niemożliwy do ukończenia przez co nie można kontynuować chainu w Darkshore.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7398
