### ISSUE TITLE
[EN][NPC] Trigore The Lasher

### ISSUE THREAD

**Issue by VioletFlare** [Atlantiss/BugTracker#7638]
This rare has a neutral standing towards the player, while it should be aggressive.
~~Also, it is impossible to tame it.~~
Wowhead: http://www.wowhead.com/npc=3652/trigore-the-lasher

**Comment by smmuntz** [comment]
Trigore the Lasher is a Hydra, Hydras were not tameable until Warlords of Draenor. So while wowhead says it should be tameable, and it is correct in current retail WoW, this is not correct for the server being a cata server.

**Comment by TranceAccount** [comment]
> By Bluewildfire (2,167 – 6·48) on 2014/07/17 (Patch 5.4.8)		
This guy is amazingly beautiful. I would love to tame him come WoD when Hydras will (at long last) be tameable but it is going to take a LOT of good luck for any hunter wishing to tame him. His spawn time has never been determined and he is rarely seen

**Comment by VioletFlare** [comment]
While I believe xShojirox is right (I never played on retail), I don't think this thread should have been closed for this reason. **The main problem with this mob was it's standing**.
Here's a peek at the cata database:
http://cata.openwow.com/npc=3652
It should have an agressive standing towards horde and alliance.
I don't know if the issue has been already fixed though, nobody wrote anything.
