### ISSUE TITLE
[EN][Spell][Paladin] Word of Glory

### ISSUE THREAD

**Issue by nikolaylen** [Atlantiss/BugTracker#7639]
Word of Glory as a 85 Holy Paladin says I should heal for around 4,5k per charge of Holy Power. Though I heal around 3k which is too low. In addition when I change to strength items (still holy paladin) I heal for 3,6k heal... Obviously scaling with spell power/intelect as a holy paladin doesn't work with this spell only. 

P.S. My Light of Dawn heals the same amount (even a little more) per charge than Word of Glory...

**Comment by Jenovas** [comment]
No calculations, no proof, no stats, no screenshots, no links, no nothing.
Closing.

**Comment by nikolaylen** [comment]
![screen shot 2016-06-16 at 0 07 34](https://cloud.githubusercontent.com/assets/19942267/16097686/c62c3b50-3357-11e6-8e0d-c1736e57e742.png)
![screen shot 2016-06-16 at 0 07 54](https://cloud.githubusercontent.com/assets/19942267/16097687/c62c6ee0-3357-11e6-9b93-c6ca7a377065.png)
![screen shot 2016-06-16 at 0 08 37](https://cloud.githubusercontent.com/assets/19942267/16097688/c63013ec-3357-11e6-9657-60dce68d9cd8.png)
