### ISSUE TITLE
bugged character

### ISSUE THREAD

**Issue by ketub** [Atlantiss/BugTracker#7640]
i cant login to my wow account , probably its couse bugged flying on gryphon. my account name :  ketub
fix it pls and thanks

**Comment by Speedydwarf** [comment]
The same has happened 2 my rogue, but i can enter all my other chars

**Comment by Luna-maria** [comment]
probably fastest way to get it fixed is to log another toon and make a ticket, since it's an issue that gms can probably fix without needing the help of a dev
if you can't log the account at all, just make a second one, make a ticket and mention the toon that's bugged, should do the trick :)

**Comment by Speedydwarf** [comment]
I've already made a ticket, but noone seems to care about it.


2016-06-15 19:48 GMT+02:00 Luna-maria <notifications@github.com>:

**Comment by Aival94** [comment]
@ketub @Speedydwarf fastest way is to go on shop and use the unstuck options(cost only 5 Vote points and every day you can get 10)
