### ISSUE TITLE
[EN] [Ghostlands] The Twin Ziggurats

### ISSUE THREAD

**Issue by Smiley13** [Atlantiss/BugTracker#7642]
To achieve this quest, you're supposed to find two stones (The stone of flame and the stone of light) but when you open the chest in the Ziggurat, there is nothing inside..

**Comment by Angelo-DM-** [comment]
This quest was 100% blizzlike. Are you sure that is bugged? Are you downloading the game while you play? Try to clear your cache too.
I've done this quest few times with different characters, and never had problem with that.

**Comment by Kozakko** [comment]
This is not quest bug. This is core issue. Sometime when you are doing quest some of the quest object are empty, Only way to complete that kind of quest is to w8 for server crash. After restart everything will be alright.

**Comment by Smiley13** [comment]
@Angelo-DM- Should I remove all the files from the cache?

**Comment by Aival94** [comment]
Wowhead Link: [The Twin Ziggurats](http://www.wowhead.com/quest=9176/the-twin-ziggurats)

If it can only be done after a restart of server you cannot do anything else except waiting for a server restart/crash or the bug to get fixed.

About the caches of wow folder you can delete it all without causing any problem as it will be recreated while you play(be carefull, the one in Wow folder and not in Data Folder of Wow)
