### ISSUE TITLE
[En][Login] Login issue

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7643]
i sometimes find and now completely am unable to login, it would say: login server down but i know very well that isnt the case. What can i do to resolve this? i tried to delete my WTF folder but it didnt do anything, in the past this issue was caused by deleting the folder

**Comment by Aival94** [comment]
It might be server side bug as sometimes it might happen when they update it.

Furthermore try to traceroute when this happens as it might be a problem of the connection you have with the server.

Try to clear cache as well.
