### ISSUE TITLE
Broken Earthen Figurine / Other figurines - Bugged drop rate?

### ISSUE THREAD

**Issue by lightstylez** [Atlantiss/BugTracker#7646]
Getting the blue figurines shouldn't take very long, in fact I got most of them shortly after hitting 85 in retail. In the WoWhead comments ppl are saying they got all 4 figurines farming mobs for 25 mins or that they got their first figurine after 5 mins. Not one comment says anything about it taking long and ppl do love to mention if something takes long to get on WoWhead, so.

I've been farming different suggested mobs from the WoWhead comments and after 2-3 hours I've not seen a single JC figurine drop. I have JC and it is over 500, either the drop rate isn't correct or it doesn't drop at all from certain mobs that should. The tank trinket is a really good one and necessary for me. I don't wanna farm HC's for 20 hours, there really aren't many good blue tank trinkets and their drop rate is below 20% for any of them.

It's possible that I had the unluckiest streak ever but it seems unlikely. Still I want to confirm either way. I don't wanna spend more hrs farming if it can't even drop.

The mobs I farmed most are Baradin Crocolisk's in TB and Jaspertip Swarmers in Deepholm.

**Comment by DuGalle** [comment]
i also lack any luck with those need my daemon panther
 check the loot tables mby thank you :)
