### ISSUE TITLE
[EN] [Achievement] Higher Learning

### ISSUE THREAD

**Issue by Kubelecer** [Atlantiss/BugTracker#7648]
In dalaran, some of these books won't spawn because the books currently in place will never despawn. Easy test is to read a book, stay afk for about 5 minutes and the reading window will disappear indicating that the book has despawned. There are 3 spots that I found bugged, however I got lucky and on 1 spot the achi book spawned before the never respawning one.

Bugged spot nr:1

http://i.imgur.com/LCBbYgu.jpg

Kirin Tor Monthly (March Issue) will never despawn once spawned.

Spot nr: 2

http://i.imgur.com/ClsCwC0.jpg

I am not sure if this book (Portals are NOT garbage bins!) despawns, but after standing for 10 minutes and nothing, I assume this book is bugged too. Remedial Magic 101: Tips from the Pros which spawns in this spot never despawns aswell.

Spot nr: 3
http://i.imgur.com/Tqsi3Ql.jpg

Don't remember the book that doesn't despawn, but after waiting 10 min this one(The Fate of Apprientice Argoly) doesn't despawn either.

Currently still trying to get Conjuration and Enchantment from spots nr 1 and nr 2

Quite possible some other books are bugged aswell.

**Comment by jissabraham** [comment]
i got ach, all books spawns

**Comment by LaveniaGithub** [comment]
Server crashes or restarts can help you ;)

**Comment by Thefakemccoy** [comment]
I got them all on my main have the pet to go with it. Its just a mater of the spawn order.
