### ISSUE TITLE
Dungeon Loot bug

### ISSUE THREAD

**Issue by Hercraft** [Atlantiss/BugTracker#7649]
Upon winning an item in a dungeon via group loot, if I, the winner, has no inventory space, the item then becomes free for anyone to loot since I didn't recieve it. Usually I can be quick enough to rectify the error and loot it myself, but more times than not someone will pick it up and suddenly become unable to understand English and won't trade it over, despite explaining the situation.

**Comment by NatsumeLily** [comment]
Not a bug..95% sure is was like this on retail.

**Comment by Cellhawk** [comment]
Not really, as far as I know, if the "owner" has full bags, item stays in corpse until owner is able to pick it up. Hell, it even gets sent to the owner via email if he doesn't.
Although, I'm not sure what content it is like this since.
