### ISSUE TITLE
[PL][NPC] 40578 - Farden Talonshrike (kilka kopii tego npc) oraz pobliskich jednostek

### ISSUE THREAD

**Issue by Mithras2801** [Atlantiss/BugTracker#7652]
**Jak dziala teraz:** NPC ten jest powielony

**Jak powinno byc:** Powinien byc jeden npc w danym miejscu

**Co dokladnie jest zle:** NPC jest kilka razy w tym samym miejscu

PS: tak samo jest w przypadku pobliskich jednostek, sa powielone.

Linki:
http://www.wowhead.com/npc=40578/farden-talonshrike
http://www.wowhead.com/npc=40719/avianas-guardian
http://www.wowhead.com/npc=39710/avianas-guardian
http://www.wowhead.com/npc=40720/avianas-guardian
http://www.wowhead.com/npc=40723/avianas-guardian

Warunek wejscia na tego mounta
http://www.wowhead.com/npc=40723/avianas-guardian#comments:id=1666216
oraz ubrana lanca.

Filmik jak powinno wygladac tam (poczatek filmiku)

**Comment by Aival94** [comment]
Reported as comment: https://github.com/Atlantiss/BugTracker/issues/7652
