### ISSUE TITLE
[PL][Quest][Mount Hyjal] Vigilance on Wings (ID = 29177) 

### ISSUE THREAD

**Issue by Mithras2801** [Atlantiss/BugTracker#7654]
**Jak dziala teraz:** Wchodzimy na mounta i zbijamy unoszace ptaki.

**Jak powinno byc:** Kiedy wezmiemy Q powinna wyskakiwac inforamcja nam na srodku ekranu o wzieciu lancy itp. Czynnosci ktore mamy wykonywac. Ptaki, ktore mamy stracac powinny latac, a zostawac trafione kiedy najedziemy lanca na nie, a nie kiedy uniesiemy sie w momencie bycia przy nich.

**Co dokladnie jest zle:** Zeby trafic lanca trzeba sie uniesc w momenciu zblizenia z tym npc, brak informacji na srodku ekranu. Ptaki tam latajace w sumie unosza sie. Brakuje im umiejetnosci przemiesczania sie lub waypointow ruchu. Praktycznie stoja w miejscu, a nie powinny.

**Linki:**
http://www.wowhead.com/quest=29177/vigilance-on-wings#videos
stracamy ich: http://www.wowhead.com/npc=40660/twilight-lancer

**Filmik:**
https://www.youtube.com/watch?v=XkfyQnrBda0

**!! UWAGA !!**

Quest ten powinien byc widoczny dopiero po zrobieniu Q Wave One
http://www.wowhead.com/quest=25525/wave-one

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/1313
