### ISSUE TITLE
[PL][QUEST] 25544 - Wave Two (part 4 of 6) (braki)

### ISSUE THREAD

**Issue by Mithras2801** [Atlantiss/BugTracker#7656]
**Jak dziala teraz:** Bierzemy questa i robimy, zabijamy npc, nie spadaja z "sufitu" ogniste kamienie, brak mozliwosci wziecia lancy ze stoiska za NPC od questa.

**Jak powinno byc:** Bierzemy questa, wiadome informacje na srodku ekranu, ale do tego questa dochodza spadajace ogniste kule z "sufitu". Warunek wejscia na mounta to lanca, mozna schodzic i wchodzic ponownie na mounta. NPC zbijamy po zblizeniu sie do nich (nasza postac robi to automatycznie).

**Co dokladnie jest zle:** Brak informacji na srodku ekranu, brak wymagania lanca, brak mozliwosci ponownego wejscia bez odrzucenia q na mounta, brak stoiska z lanca, nie ma spadajacych kamieni z "sufitu"

**Linki:**
http://www.wowhead.com/quest=25544/wave-two
http://www.wowhead.com/npc=40660/twilight-lancer

**Filmik:**
https://www.youtube.com/watch?v=KRY6xPXm-2E

**Comment by Aival94** [comment]
Reported as Comment: https://github.com/Atlantiss/BugTracker/issues/4292
