### ISSUE TITLE
[PL][QUEST] 25832 - Return to Aviana (part 6 of 6) (uszkodzony teleporter)

### ISSUE THREAD

**Issue by Mithras2801** [Atlantiss/BugTracker#7658]
**Jak dziala teraz:** Teleporter nie dziala, brak informacji o broni, brak broni za npc od Q.

**Jak powinno byc:** Teleporter powinien przeniesc nas na powierzchnie. Informacja po wzieciu q na srodku ekranu mowi o zmianie broni.

**Co dokladnie jest zle:** Teleporter nie dziala. brak stoiska z bronia, brak napisu na srodku ekranu.

**Linki:** 
http://www.wowhead.com/quest=25832/return-to-aviana

**Filmik:** (teleporter - 0:15 s)
https://www.youtube.com/watch?v=Yd45t1LEt9g

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/4185
