### ISSUE TITLE
[EN/PL][Firelands] Alyslazora - stacks

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7659]
Po ostatnim uptade nie można nabijać stacków na Alys, zamiast otrzymywania kolejnych stacków, odświerzany jest tylko buff do latania, a ma się ciągle tylko 1 stack, przez co bossa bije się baardzo długo.

After last uptade it's impossible to get stacks from circles during Alyslazor's encounter, instead of receiving next stacks, there is only one stack all the time and flying buff is refreshed only.

**Comment by LaveniaGithub** [comment]
http://atlantiss.eu/changelog#rev5054
