### ISSUE TITLE
[EN][Quest][Borean Tundra] Escape from the Winterfin Caverns

### ISSUE THREAD

**Issue by xiz1337** [Atlantiss/BugTracker#766]
The quest works fine, until you come to the point where the murloc you escort (Lurgglbr) swims back to saftey, you escorte him to the shore but than he just stands there.

![wowscrnshot_121914_103415](https://cloud.githubusercontent.com/assets/10241870/5502493/2f09ae36-876b-11e4-8eb3-d9094c7797f4.jpg)

**Comment by bgb** [comment]
Just did it. You have to come closer to him. Then You will get quest credit and he will dissapear.
