### ISSUE TITLE
[PL][Quest][Deepholm] The Stone Throne

### ISSUE THREAD

**Issue by Matti297** [Atlantiss/BugTracker#7660]
Nie jest możliwe porozmawianie i oddanie questa u Therazane w Therazane's Throne. NPC w ogóle się nie pojawia

**Comment by Aival94** [comment]
Related/Reported: https://github.com/Atlantiss/BugTracker/issues/5906, https://github.com/Atlantiss/BugTracker/issues/3902, https://github.com/Atlantiss/BugTracker/issues/3726
