### ISSUE TITLE
[EN/PL][Firelands] - Podwójny Ragnaros/Double Ragnaros

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7662]
Po ostatnim uptade Ragnaros pojawia się i walczy podwójnie, co uniemożliwia zabicie tego bossa.

After last uptade Ragnaros appears and fights doubly, what makes the killing of this boss impossible. 

Wywalcie tą ostatnią poprawkę, bo rozwaliła pól Firelandów kosztem głupiego DB.

**Comment by ppiotrrek1000** [comment]
Ubijalny Mordor mówi ze whirlwind opłaca się już na dwóch targetach i walka trwa 4 min dłużej. Więc blizzlike 2x. Pozdrawiam.

**Comment by arekczup** [comment]
Jeśli rev5056 działa to możecie już zamknąć temat
