### ISSUE TITLE
[EN] [Icecrown Citadel] [NPC] Volatile Ooze

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7663]
Volatile Ooze (http://www.wowhead.com/npc=37697) on Professor Putricide encounter in Icecrown Citadel has an incorrect amount of health points, about 4 million on 25 normal difficulty, making it much harder to kill than it should be. Correct amounts are:

10	  -    395,290
10H	  -    451,760
25	  -    1,581,160
25H	  -    1,976,450

source: http://wow.gamepedia.com/Volatile_Ooze

**Comment by xmesaj2** [comment]
http://community.atlantiss.eu/index.php?/topic/10756-7663npc-volatile-ooze/ fix
