### ISSUE TITLE
Inscription disappeared

### ISSUE THREAD

**Issue by HardKillah** [Atlantiss/BugTracker#7666]
I was skilling my inscription when server crashed, when I logged back in my inscription icon disappeared from my spellbook and from UI. It says that my inscription skill is 0/0 but b4 the crash it was 460. I've tried deleting cache and reloading UI but noting helped. I even deleted the game client and downloaded a new one. That did not help either. I also can't unlearn the skill. Can some one help me out?

**Comment by TranceAccount** [comment]
This isn't a forum.
