### ISSUE TITLE
[EN][Set][Pvp] Bonus 2/5, 3/5.

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#7668]
Hi.
The bonus gear 2/5 & 3/5 (400 resilience x2)
It should work or should not?

I'm asking because in in the past two days. I saw few players running this gear setup.
When I'm asked them: "why you do that, it should not stack".
They answered me: "But it work!"

I don't know if it really work. I did not checked this myself. But you should.

**Comment by BialyADI** [comment]
It is buged and some times work. you need relog.

**Comment by Illusie** [comment]
@BialyADI I am not talking about myself because I'm not using this kind of gear setup.
Talking in general from past two days seen several players that actually use it.

so I am reporting here.

**Comment by Jenovas** [comment]
Fixed in rev 5058
