### ISSUE TITLE
Quest The Eye of All Storms in Darkshore is bugging please help?

### ISSUE THREAD

**Issue by Slenderman64** [Atlantiss/BugTracker#7669]
I can't find the twilight portal and the dragon is stuck i can't go down please help?

**Comment by MentisMortem** [comment]
Yeah, i just tried this quest and everything works okay except that when attack the portal, it immediately regens to 100% hp.

**Comment by MentisMortem** [comment]
Nevermind, i relogged and it worked perfectly :)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/2028

**Comment by TheCopacabanaMan** [comment]
Up! There is no twilight portal
