### ISSUE TITLE
[EN][Item] Jaws Of Defeat

### ISSUE THREAD

**Issue by Reversion** [Atlantiss/BugTracker#7674]
It is already more than half a year, c mon guyz.

https://github.com/Atlantiss/BugTracker/issues/5745

**Comment by xolon** [comment]
intentional double is something worst you can do

**Comment by Kaldros** [comment]
And completely ignoring important issues for extended periods of time is not much better either.

It has been more than five full months since the issue was first reported and not even a single reply by someone in charge... That's really shameful.
