### ISSUE TITLE
Quest: "A curse we cannot lift" - Quest ID: 26720 - Duskwood 

### ISSUE THREAD

**Issue by Nightshade070** [Atlantiss/BugTracker#7677]
When i get inside the house, the worgen that is on the cupboard jump down to me and thats okay but the real problem is when i try to inject him that item the quest giver gave me nothing happens. I can kill him (done it accidentally 2-3 times) but i must caputure him with that inject thing. I hope you can get it fixed. Thanks in forward !!

**Comment by Quban** [comment]
duplicate
