### ISSUE TITLE
[EN][Quest][Searing Gorge]Lunk's Adventure: Rendan's Weakness

### ISSUE THREAD

**Issue by BiliBee** [Atlantiss/BugTracker#7679]
How it should work: https://www.youtube.com/watch?v=-GSyy5YwuOk
On atlantiss there are missing Iron Summit Guards so they cant join to dance and chain can't be continued.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3315
