### ISSUE TITLE
[EN][Event][Item][Juggling Torch] 

### ISSUE THREAD

**Issue by Velerios** [Atlantiss/BugTracker#7684]
The tooltip for [Juggling Torches](http://www.wowhead.com/item=34599/juggling-torch) says they should be unique (40), yet as of right now they seem to be unique (4), making the achievement associated with juggling 40 of them in 15 seconds impossible to complete.

**Comment by Kubelecer** [comment]
I have completed the quest very recently, and I managed to buy 35 torches to get me to 40, and then complete the achievement

**Comment by Velerios** [comment]
That's weird, I sent some torches to another character and he can have them in his equipment without problems; maybe it's a character or death knight issue then- I can't even complete the quest "Torch Catching" which is supposed to give 5 of these as I get the error: "I can't carry anymore of those"/

**Comment by Velerios** [comment]
Well the issue resolved itself, it seems it might've been associated with phasing from some quests that I abandoned.
