### ISSUE TITLE
[EN][Raid] Atramedes Sonic Breath

### ISSUE THREAD

**Issue by HCGWill** [Atlantiss/BugTracker#7688]
As of 6/20, when Atramedes uses Sonic Breath, he no longer applies the Tracking debuff (http://www.wowhead.com/spell=78092/tracking#used-by-npc) on the player the breath is focused on as he should.

Our kill last week (6/14): www.twitch.tv/nitrous127/v/72299443?t=0h41m35s
Breath targets are getting the Tracking debuff correctly.
Our kill this week (6/20): https://secure.twitch.tv/kimano117/v/73594005?t=1h08m40s
No breath targets are getting the debuff, no way to tell who has it.

**Comment by Quban** [comment]
fixed in rev 5059
