### ISSUE TITLE
[EN][Raid] Raid lockouts resetting

### ISSUE THREAD

**Issue by HCGWill** [Atlantiss/BugTracker#7690]
There's been several instances now of our weekly raid ID somehow getting reset during the week for both BWD and BoT.

BWD reset tonight sometime during our clear. This was around 3am server time on Tuesday (6/21). When we tried swapping a new player into the group after Atramedes, it kept putting them in an empty instance with all bosses alive. We zoned out and reset the instance, when we zoned back in the entire instance was reset, and our raid ID was gone (the lockout still shows up on our calendar, but I doubt that's of importance). We also realized then, that our BoT instance ID had reset as well, but our TotFW was still there.

As a side note, it only reset the ID of the players who were in the raid at that time. We switched one of our players out after the second boss, and they still have a BWD ID with first 2 bosses dead.

**Comment by EnPra** [comment]
did firelands alt run on wenesday and my raid lock for fl got reset somewhere around friday i think

**Comment by Aival94** [comment]
Probably this week there were some problems with ids because of some major bugs and changes to FL and to the Core.

**Comment by sunshitwowsucks** [comment]
the crash reset it

**Comment by TranceAccount** [comment]
Does this problem still exist?

**Comment by Aival94** [comment]
When there are crashes some ids reset(usually you need to online with the char with the id for it to reset).

Some other times instead of the id to reset some bosses reset(mostly seen in fl by having alysrazor or moajordomo reset)
