### ISSUE TITLE
[EN] [NPC] Magnus Frostwake

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7692]
NPC Magnus Frostwake (http://www.wowhead.com/npc=11278) is missing from Scholomance's exterior in Western Plaguelands. Pre-cata, he could be seen using an item from Scholo's quest chain, but seeing as the NPCs giving quests are missing too, it's impossible to get that item. Not sure if he's invisible or just missing, he's not there.

**Comment by Aival94** [comment]
Reported with wrong location mentioned: https://github.com/Atlantiss/BugTracker/issues/7351
