### ISSUE TITLE
[EN][Midsummerl][Item] Juggling Torch

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7695]
http://www.wowhead.com/item=34599/juggling-torch#sold-by

currently you can get 1 torch by paying 5 burning blossoms, you should get 5 torches

**Comment by DuGalle** [comment]
true

**Comment by Rinniel** [comment]
Confirmed. This should get fixed before the event ends, there's a related achievement for them

**Comment by Navedonar** [comment]
fix https://github.com/Atlantiss/BugTracker/issues/7695

**Comment by Navedonar** [comment]
fixed

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
