### ISSUE TITLE
Quest: In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by iirpdg** [Atlantiss/BugTracker#7698]
The machineguns and flying NPC's don't appear

**Comment by krecik88** [comment]
Please follow the How to use?: https://github.com/Atlantiss/BugTracker or issue will be closed

**Comment by Bildo** [comment]
duplicate

**Comment by GamerSlew** [comment]
Link:  http://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress

Video: https://www.youtube.com/watch?v=sKM2TP3Hveg

Quest doesn't work.
