### ISSUE TITLE
[EN][RAID][TBC] Reliquary of the Lost

### ISSUE THREAD

**Issue by vidoceq** [Atlantiss/BugTracker#7699]
It just doesn't spawn when we get there. Nothing is happening, it should be releasing itself from the chains as soon as someone enters the chamber, but atm our movement doesn't trigger it. We've tried to do The Black Temple 3 times already, and it didn't spawn.

**Comment by Aival94** [comment]
Reported as comment: https://github.com/Atlantiss/BugTracker/issues/2829
Reported: https://github.com/Atlantiss/BugTracker/issues/2700
