### ISSUE TITLE
[PL]{QUEST][The Bigger They Are]

### ISSUE THREAD

**Issue by ardanien** [Atlantiss/BugTracker#7700]
Nie działa poprawnie. Pomijając że z [Obsidium Punisher]

http://www.wowhead.com/npc=52107/obsidium-punisher

nie ma żadnego dropu, to quest

http://www.wowhead.com/quest=29295/the-bigger-they-are#comments

jest nie wykonalny.
1. wypadające z [Obsidium Punisher] [Living Obsidium Chip]

 http://www.wowhead.com/item=69860/living-obsidium-chip

nie da się zebrać mimo że na ziemi go widać

2. według wowhead z [Obsidium Punisher] winien być drop 0,05% tym czasem nawet nie ma żadnego dropu

3. respawn [Obsidium Punisher] jest tak szybki że nawet nie da się uciec w bezpieczne miejsce

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6661
The so fast respawn time is blizzlike.
