### ISSUE TITLE
[PL][Dungeon] Helfire Ramparts

### ISSUE THREAD

**Issue by Matti297** [Atlantiss/BugTracker#7702]
W heroic Helfire Ramparts po pokonaniu Vazruden the Herald zamiast aktywować się walka z jego smokiem Nazan'em on pojawia się na smoku i nie można skończyć instancji i uzyskać achiva

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the NPCs.

**Comment by Matti297** [comment]
[http://www.wowhead.com/npc=17307/vazruden-the-herald](url)
[http://www.wowhead.com/npc=17536/nazan](url)

**Comment by Matti297** [comment]
it work's now
