### ISSUE TITLE
[PL][Warrior][Druid] Rage and Dots, Channeling Spells.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7703]
Doty nie generują Rage gdy biją Warka/Druta i podobnie jest z Channeling Spells jak: Mind Flay, Drain Life, Drain Soul itd.

Zgłoszenie powiązane z tym zgłoszeniem: https://github.com/Atlantiss/BugTracker/issues/5382.

Wcześniej po naprawie Rage był problem że Dmg z Spelli nie generowały Rage(ostatni post Jenovasa ;p).
Teraz po Duelu z Lockiem/Sprejem po zbiciu mnie z 100% do 0% Dotami ma się ciągle 0 Rage, wiec zostało jeszcze to :(.

Dowód:
Biłem cały czas jedna Dotą i Channeling Spellem.
![wowscrnshot_062316_025430](https://cloud.githubusercontent.com/assets/5780624/16288627/19fee2f0-38ee-11e6-9148-da687274e47d.jpg)

**Comment by Izanamix** [comment]
I confirm that, just see my screenshot. You can see a feral who take me 13k critics on a dot. It's impossible to do that at the s10 season. 
![feral dots](https://cloud.githubusercontent.com/assets/20111736/16308471/58dd08e0-3965-11e6-84f1-e6a5a43eb07b.jpg)

Look this video of a multi glad feral at officiel. He did 10k dots maximum **at the s11 season.** 

Check yourself 

https://www.youtube.com/watch?v=xTx36ffwy1U

**Comment by BialyADI** [comment]
It is not about Dot Dmg, But about that Dots Dmg don't generate Rage on Warrior/Druid!
Izanamix create another ticket if Feral Dot Dmg is Buged.

**Comment by Izanamix** [comment]
Okay I will do that

**Comment by Jenovas** [comment]
Fixed in rev 5063

**Comment by Vyrtuz** [comment]
Testowano bleedy na druidzie. Nie generują rage. Poszedłem nawet o krok dalej żeby upewnić się czy DoTy w ogóle powinny generować rage... I znalazłem takie coś:
(http://wow.allakhazam.com/forum.html?forum=243&mid=111645474659488320)
Nijaki "Kalinwulf" wspomina, że obrażenia w czasie nie generują zasobów rage.
WoWWiki nic nie wspomina:
(http://wowwiki.wikia.com/wiki/Rage)
WoW gamepedia no cóż..:
(http://wow.gamepedia.com/Rage)

**Comment by BialyADI** [comment]
To co dałeś jest z TBC ;x. Na jakimiś filmiku trzeba to zaobserwować ale ogólnie otrzymywany Dmg powinien generować Rage, chodź i tka jest tego niewiele.

**Comment by BialyADI** [comment]
Swifty Duels! Można na filmiku spokojnie wyłapać że Doty i Drain Life w tym przypadku Generuje Swiftemu Rage.
https://www.youtube.com/watch?v=ZBVvUuV7v1I

**Comment by Vyrtuz** [comment]
Haha.. Faktycznie zwracam honor i najmocniej przepraszam :D

**Comment by BialyADI** [comment]
Jenovas, spelle chanellujące tez będą generowały Rage czy na razie Doty?

**Comment by Jenovas** [comment]
Tak channele tez powinny. Prosze sprawdzic czy ilosc generowanego rage jest poprawna.

**Comment by BialyADI** [comment]
https://github.com/Atlantiss/BugTracker/issues/7794
Jenovas plz od stycznia ^^.

**Comment by Kejmil** [comment]
learn to wait
https://github.com/Atlantiss/BugTracker/issues/825
