### ISSUE TITLE
 [EN][Event][Midsummer Festival]Uldum & Twilight Bonfires

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#7704]
Hello I have tried multiple times to complete the "Extinguishing the Cataclysm" achievement today, but I am unable to click on the Uldum and Twilight highlands bonfires to receive credit.

**Comment by Luna-maria** [comment]
eeh, worked fine for me 2 days ago. Might be worth mentioning if you're horde or alliance? and if you're sure you're at the right ones?

**Comment by Aequitass** [comment]
It worked for me yesterday :S

**Comment by Bildo** [comment]
works
