### ISSUE TITLE
[EN][QUEST][Escape Velocity bug.]

### ISSUE THREAD

**Issue by poldons** [Atlantiss/BugTracker#7705]
Well there is something wrong with this quest for sure. Plus Candy Cane is not where she is supposed to be.
![wowscrnshot_062316_120831](https://cloud.githubusercontent.com/assets/20107990/16299732/167b2da2-393c-11e6-96f7-687e0241b989.jpg)

**Comment by user1011** [comment]
Why don't you tell us what IS wrong?
