### ISSUE TITLE
[PL][NPC] [Quest]Therazane 

### ISSUE THREAD

**Issue by arekczup** [Atlantiss/BugTracker#7706]
![wowscrnshot_062316_122715](https://cloud.githubusercontent.com/assets/8699987/16300033/ee3cde38-393d-11e6-8982-822594f8ba53.jpg)
teleportowała się magicznie z tronu do świątyni ziemi gdzie wziąłem  od niej questa world in stone 
i stała się nie zdatna do targetowania. quest nie do ukończenia....

**Comment by Aival94** [comment]
Related/Reported: https://github.com/Atlantiss/BugTracker/issues/5906, https://github.com/Atlantiss/BugTracker/issues/3902, https://github.com/Atlantiss/BugTracker/issues/3726
