### ISSUE TITLE
[EN][NPC] Razorgore the Untamed

### ISSUE THREAD

**Issue by Velerios** [Atlantiss/BugTracker#7707]
First boss of Blackwing Lair instance, [Razorgore the Untamed](http://www.wowhead.com/npc=12435/razorgore-the-untamed#drops) does not drop any loot, (making it impossible to complete the Tier 2 sets) not even the gold- his corpse is uninteractable after his death. Additionally, he only has 135 HP instead of the supposed  449685 HP.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6709
Related: https://github.com/Atlantiss/BugTracker/issues/4521
