### ISSUE TITLE
how often repair the bugs?

### ISSUE THREAD

**Issue by iirpdg** [Atlantiss/BugTracker#7708]

**Comment by Piklo** [comment]
if you have any questions please use the forum, bugtracker is for the bugs

**Comment by Aival94** [comment]
Sorry for giving useless comments but what is this about?

**Comment by user1011** [comment]
Engrish please.

**Comment by Aldergar** [comment]
How often study inglish?

**Comment by Anhaeyn** [comment]
Bugtracker isn't place for such questions.
