### ISSUE TITLE
[EN][Kill Command][Hunter] Hunt BM damages

### ISSUE THREAD

**Issue by Izanamix** [Atlantiss/BugTracker#7709]
Hello,

There is a problem concerning these damages of BM Hunters. 

Can you check this please ? 

![hunt dmg bug](https://cloud.githubusercontent.com/assets/20111736/16307438/8b5b6496-3961-11e6-8c88-68af3f4829e5.jpg)

**Comment by ohbytheway** [comment]
Go and make some bg's, or something, instead killing fly master and low lvls that are waiting for him to spawn in Orgrimmar. Pro player, really :P. True ally. Grats.

**Comment by roudiou** [comment]
What a constructive awnser. Maybe you should stop talking for nothing ;)
70k kill command is just insane and need to be script.

**Comment by Izanamix** [comment]
Why crying ? Why are you useless ? 

You are right, I will continue to kill this fly master when I'll pass to orgri, stupid boy

**Comment by ohbytheway** [comment]
...and like usual, you will always get your ass rekt, baguette

**Comment by Izanamix** [comment]
So funny you are. We 5v2 so easily that you are obliged to come with 10 guys. No matter what, if you come as an equal number, it's you who will see your ass rekted, chausette

**Comment by ohbytheway** [comment]
I wish, i could understand, what are you writing about.

**Comment by roudiou** [comment]
just stop talking about other thinks which are not about the game. we just don't care about all your life.If youhave nothing more intresting than " ..and like usual, you will always get your ass rekt, baguette " then go away to spam on an other topic. Thx

**Comment by ohbytheway** [comment]
oh, I'm so sorry. Please don't do this:  ''We 5v2 so easily that you are obliged to come with 10 guys. No matter what, if you come as an equal number, it's you who will see your ass rekted''  - whatever it is :P

btw. it was you, started to discuss with me, scroll up

**Comment by roudiou** [comment]
first comment of the topic: "Go and make some bg's, or something, instead killing fly master and low lvls that are waiting for him to spawn in Orgrimmar. Pro player, really :P. True ally. Grats." .

No one exept you began to talkabout other thinks. Sincerly,

**Comment by ohbytheway** [comment]
Don't be rude, shitty scum-rogue-bag.
I was kind, but i will answer now, like you do.

**Comment by Aldergar** [comment]
He is using a bug on the pet,a gm should ban this guy.

**Comment by Jenovas** [comment]
No proof. You didnt calculate the DMG. You did not do any tests. You didnt show the pet if it had some weird buff from an instance. Nothing.
Closing.
