### ISSUE TITLE
[EN][QUEST][NPC] Nowhere to run

### ISSUE THREAD

**Issue by jurkobohun** [Atlantiss/BugTracker#7710]
Unfortunately this quest doesn't work. Not only for me but also for other players. When you accept it Master Forteski should run into the mine but nothing happens. He says nothing and stands still. Turning off addons, reloging, abandoning quest doesn't work either.

**Comment by henrythenth** [comment]
I can attest to this. Tried all methods mentioned above but to no avail.

**Comment by fakan** [comment]
same for me , this is frustrating

**Comment by pbednarek91** [comment]
Same problem there, can You tell us when this one will be solved?

**Comment by KikoDominion** [comment]
Same here, i should write a new report? or we should wait? i got my character stuck cause i dont have more quests, atleast history quests, i could go to other city etc but i wanted follow the main quests.

**Comment by pbednarek91** [comment]
Devs please spend some time to fix this issue, i cant end this quest with my GF

**Comment by fakan** [comment]
you have to quest somewhere else or do dungeons till level 19 and then move into the next zone to the right , there will be quests 19+.. doesn't seem like they are going to fix it any time soon.

**Comment by Quban** [comment]
fixed in rev http://atlantiss.eu/changelog#rev5086

**Comment by fakan** [comment]
16 days , nice tempo
