### ISSUE TITLE
[EN][Liberation Day][Gilneas] Ball of Chains not attached to Enslaved Gilneans don't count as 'freeing'

### ISSUE THREAD

**Issue by Paraselenean** [Atlantiss/BugTracker#7711]
[EN][Quest][Zone] Liberation Day [Gilneas]
[EN][NPC] Lorna Crowley
[EN][Npc][Drop] Slavery Key
What's bugged: You get the Slavery Keys from killing the mobs but freeing the 'Enslaved Gilneans' only counts if their 'Ball and Chain' is next to the 'Enslaved Gilnean' itself which isn't the case for ALL the NPCs except for like 3, which makes this a very tedious quest - especially for groups as freeing one Gilnean only counts for the person who used the Slavery Key on the Ball and Chain.
[EN][Web] http://cata.openwow.com/quest=24575

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3558 which direct you to first report: https://github.com/Atlantiss/BugTracker/issues/3459 as a dev asked to be.
