### ISSUE TITLE
[EN] Bandit's Guile and Redirect

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#7712]
Redirect is not transfering Bandit's Guile to new target. The cycle begins again which is a bug. 

"Switching to a new target resets your cycle of Bandit's Guile Icon Bandit's Guile. Using Redirect Icon Redirect on a new target will transfer your current Bandit's Guile buff to the new target."
http://www.tauri-veins.tk/combat-rogue-wow-pve-dps-rotation-cooldowns-abilities

**Comment by tnarf** [comment]
duplicate:
https://github.com/Atlantiss/BugTracker/issues/2147
