### ISSUE TITLE
[EN] [QUEST] [Distillambre Farm] The Night, All Trolls Are Greys

### ISSUE THREAD

**Issue by CptWaso** [Atlantiss/BugTracker#7713]
I took the quest but nothing happened . No troll's attacks. nothing i've got screenshot.
![wowscrnshot_062416_014906](https://cloud.githubusercontent.com/assets/20118468/16323962/879e6fda-39af-11e6-81d8-678a27ebf415.jpg)

**Comment by Aival94** [comment]
I am not sure but i believe this quest is called It's Raid Night Every Night and is already reported here: https://github.com/Atlantiss/BugTracker/issues/3134

**Comment by Lebiedz** [comment]
It is one another quest completable only after server crash or restart. So you will have to wait for a fix or for a restart :)
