### ISSUE TITLE
[EN][NPC] Calia Hastings

### ISSUE THREAD

**Issue by Starkad1** [Atlantiss/BugTracker#7714]
The rogue trainer in Theramore isle Is bugged Displays only greetings /playername/
![untitled](https://cloud.githubusercontent.com/assets/20122142/16329133/5fc29544-39d8-11e6-8c32-a9fc41a202b1.png)

**Comment by lierox90** [comment]
She is not a class trainer.
`http://www.wowhead.com/npc=23566/calia-hastings`
