### ISSUE TITLE
EN][Spell][Class] all mage one for instance

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#7715]
So i played bg today and 3 times it happend that i got silenced by a rogue or feral and now tried to cast within a smoke cloud from the rogue and all my spells glitched. Cant cast a single one of them unless i relog or alt f4

**Comment by xmesaj2** [comment]
More information? Which spells, battleground? Smoke bomb cast by enemy or ally? Be more precise and tell more details. It's good practice to add spell IDs etc (and linking them to cata.openwow.com for example)
