### ISSUE TITLE
[EN][Tear][Druid] Feral Dots

### ISSUE THREAD

**Issue by Izanamix** [Atlantiss/BugTracker#7716]
Hello,

On my screenshot, you can see a feral who did me 13k critics on a dot. It's impossible to do that at the s10 season. 
![feral dots](https://cloud.githubusercontent.com/assets/20111736/16308471/58dd08e0-3965-11e6-84f1-e6a5a43eb07b.jpg)

Look this video of a multi glad feral at officiel. He did 10k dots maximum **at the s11 season.** 

Check yourself 

https://www.youtube.com/watch?v=xTx36ffwy1U 

For exemple, to 1:04

**Comment by mati865** [comment]
It depends on many aspects. He was doing 10.6k dot crits without BoM, also resilience is important factor. Finally feral who did 13k crit on could stack mastery as crazy.

**Comment by Jenovas** [comment]
No proof.
Closing.
