### ISSUE TITLE
[EN][other]Stuck as bones

### ISSUE THREAD

**Issue by centurijon** [Atlantiss/BugTracker#7717]
Running through Scholomance and something turned me into a pile of meat.
Since then when I go into instances I am a pile of meat. When I am out in the world I am a pile of bones.

Nothing seems to make this effect go away. Being polymorphed, dieing, relogging, etc. Even my ghost is bones. Oddly, my corpse while I am a ghost is accurate. Other players can see it so it's not just a local view thing.

My actual abilities are unaffected.

It's been 2 days and, while it's a little funny, I'd like to be able to see my arms and legs again.

![wowscrnshot_062416_214022](https://cloud.githubusercontent.com/assets/5652223/16354033/8e551216-3a54-11e6-8af2-48137a5d4b9d.jpg)
![wowscrnshot_062416_214507](https://cloud.githubusercontent.com/assets/5652223/16354048/019ce690-3a55-11e6-924b-59e2111a6caa.jpg)

**Comment by Aival94** [comment]
make a ticket in-game and wait for a gm to help you(you need to be online on the character so they can help you)

Reported: https://github.com/Atlantiss/BugTracker/issues/1661

**Comment by VioletFlare** [comment]
You might try deleting your Cache folder, it is in your wow folder.

**Comment by centurijon** [comment]
That's great. I actually opened a ticket before submitting this bug.
Just got a GM email today "Ticket response requires being online". Well while this ticket has been open I leveled from 45 - 50. That's HOURS of being online, then the ticket is closed while I happen to be off.
