### ISSUE TITLE
[EN][Guild Achievement] That's A Lot of Bait

### ISSUE THREAD

**Issue by Wowpappa** [Atlantiss/BugTracker#7718]
[http://www.wowhead.com/achievement=5036/thats-a-lot-of-bait](url)
- How it "works" here? - it counts only fish from schools
- How it should work? - ( [http://wowwiki.wikia.com/wiki/That's_A_Lot_of_Bait](url)) 

> "That's A Lot of Bait is a guild achievement which requires guild members to collectively catch 10,000 fish from fishing pools. Once a guild has earned this achievement, members can purchase **[Recipe: Seafood Magnifique Feast]** for 150Gold from the guild vendor."

 - WoWWiki

Some comments from Wowhead:

1) "That's A Lot of Bait" - Ironically you don't need any Bait and have a 100% success chance at fishing from pools even with a skill of 001."
2) "It says "catch fish" but it also counts **Volatile Water** fished from schools"
3) "Confirmed, Volatile water counts towards the achieve (as "1 fish" even if its Water x2)"

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/7359
