### ISSUE TITLE
[EN] [Midsummerfestival] Char won't stop spinning!

### ISSUE THREAD

**Issue by ShogunSho** [Atlantiss/BugTracker#7720]
So i tried out that pole at a Midsummerfestivals place, and of course i started spinning ang gaining the buff- so far no problem. But then, while spinning i teleported back to Orgrimmar usig my Hearthstone and now i wont stop spinning. I tried walking through portals, using the Zeppelin, mounting and other stuff. But it just wont stop. Maybe its because the buff is still ongoing but i dont know... Relogging and Reloading dont work either. Please save my Rogue!!!! (Shogonin)

**Comment by user1011** [comment]
Have you tried killing character? It sometimes resets stuff.

**Comment by ShogunSho** [comment]
Worked, thanks!!!
Am 25.06.2016 11:25 vorm. schrieb "Somebody" <notifications@github.com>:
