### ISSUE TITLE
[EN][World Event][Quest] More Torch Catching

### ISSUE THREAD

**Issue by user1011** [Atlantiss/BugTracker#7721]
**What is bugged:**
When you do this quest and catch like 5 torches in a row and then fail, these catches will count for the next row of catching you start. This makes the quest very easy to complete since you don't have to catch 10 torches in a row, but can fail as many times as you like and catch 10 in total in the end.

**How it should be:**
You should complete this quest by catching 10 torches in a row, and if you fail you must start all over again.
According to the youtube video there should also be an area of effect when the torch lands on the ground.

**Additional information:**
http://www.wowhead.com/quest=11924/more-torch-catching
https://youtu.be/qmqneMVQsio?t=2m58s

I'm not sure if there are shadows on the ground in game though, because I might have turned that off. The torches are predictable too: first go forward, then the rest only backwards..

**Comment by Luna-maria** [comment]
'this makes the quest very easy to complete'

what? This quest is 10 times more difficult than on retail because the shadow on the ground isn't showing properly

**Comment by user1011** [comment]
> what? This quest is 10 times more difficult than on retail because the shadow on the ground isn't showing properly

Last line of the report:
> The torches are predictable too: first go forward, then the rest only backwards..

**Comment by Luna-maria** [comment]
shadows still don't show so half of the time it's still pure luck.

**Comment by visi212** [comment]
It's easy bro just throw it forward, then move forward and when you catch torch first time move back all time just with S key.

**Comment by Rinniel** [comment]
That doesn't happen every time though. Sometimes you fail and it will remove the stacks. And like @Luna-maria said, the shadows don't show so the quest is **not** "very easy to complete"

**Comment by user1011** [comment]
> I don't know why you cry there are more important buged things. This quest works that's why i think there is no problem. ~ @visi212 

A bug is a bug, and it has to be reported.
I have noticed that it now works, so I'm closing it since it isn't official.
