### ISSUE TITLE
[En][Dungeon][Boss Bug]Shadow fang keep

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7726]
The last few days i noticed the first boss is EXTREMELY harder to down. for some reason i see there is a bug that he does aoe damage immediately after he casts apphixiate wiping the whole group. Im pretty sure it shouldnt be like this. please look into this :L

**Comment by mati865** [comment]
In polish https://github.com/Atlantiss/BugTracker/issues/7491

**Comment by Quban** [comment]
fixed in rev 5070
