### ISSUE TITLE
[PL][Talent][Death Knight] Imporved Frost Presence

### ISSUE THREAD

**Issue by jakubo98** [Atlantiss/BugTracker#7728]
Testowane na Howling Blast
NoPres 8035
Blood 8242
Unholy 8035
Frost 9241
Przyrost obrażeń w Blood pres, pochodzi od zwiększenia armora, Poniżej album ze screenami obrażeń  broni dla każdej wersji. http://imgur.com/a/eBK39

**Comment by mati865** [comment]
https://github.com/Atlantiss/BugTracker/issues/7685

**Comment by mati865** [comment]
https://github.com/Atlantiss/BugTracker/issues/7685,
widać bardziej to zbugowane niż się wydawało

**Comment by jakubo98** [comment]
Właśnie jak zobaczyłem to w changelogu pokusiło mnie na sprawdzanie statów. Jeszcze za PTR cały Frost pres nie działał

**Comment by Jenovas** [comment]
Ale co jest zbugowane? Imprv Frost Presence nie powinien zwiększać DMG w innych presence.
Zamykam zgłoszenie. Następnym razem jak tworzysz zgłoszenie to proszę napisz o jakiego buga Ci chodzi, bo nie będziemy się domyślać.
