### ISSUE TITLE
[EN][Spell][Warlock] Create Healthstone

### ISSUE THREAD

**Issue by pahanzt** [Atlantiss/BugTracker#773]
1. http://cata.openwow.com/spell=34130
2. While you have one of warlock's demons summoned (except Succubus): Imp (http://cata.openwow.com/spell=688), Voidwalker (http://cata.openwow.com/spell=697), Felhunter (http://cata.openwow.com/spell=691) and Felguard (http://cata.openwow.com/spell=30146) creating healthstone makes you entering battle for a few seconds. 
3. Bug was noticed 19.12.2014
4. Value: 3/10.

**Comment by kadi2** [comment]
http://cata.openwow.com/spell=5697 // Causes combat to pet whenever casted only on yourself
