### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] Atonement

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7730]
http://www.wowhead.com/quest=9543/atonement

How it should work: This quest should become available only after completing the prerequisite quest chain ending with http://www.wowhead.com/quest=9424/makurus-vengeance.
What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10934-quest-atonement/

**Comment by aje** [comment]
fixed in revision 5115
