### ISSUE TITLE
[EN][NPC] Derak Nightfall doesnt sell

### ISSUE THREAD

**Issue by gally9** [Atlantiss/BugTracker#7733]
This NPC **Derak Nightfall** is not able to sell or buy any items because the window does not open when clicking on sentence "I wish to buy from you, Derak"

Its annoying because he sells an important cook recipe for leveling.

http://www.wowhead.com/npc=2397/derak-nightfall#sells
![bugwow](https://cloud.githubusercontent.com/assets/20181972/16407667/2d2d4f62-3d15-11e6-9db7-0dede930fa39.png)

**Comment by user1011** [comment]
Thanks for reporting this issue.

The cooking recipes he sells are sold by other vendors too:
http://www.wowhead.com/item=21219/recipe-sagefish-delight#sold-by
http://www.wowhead.com/item=6330/recipe-bristle-whisker-catfish#sold-by
http://www.wowhead.com/item=21099/recipe-smoked-sagefish#sold-by
