### ISSUE TITLE
[EN][NPC] Agent Kearnen

### ISSUE THREAD

**Issue by Khangu** [Atlantiss/BugTracker#7736]
http://www.wowhead.com/quest=26289/find-agent-kearnen

NPC is missing.

(she's not where she supposed to be and nobody knows where she is)

**Comment by ecloix** [comment]
Me neither, I was not able to take quest the pnj was absent

**Comment by user1011** [comment]
She has respawned. Probably got killed by a horde.

**Comment by Khangu** [comment]
Actually before writing this thread I was trying to catch her for 2 days, about 2-4 times each day... So horde hates her so much? I don't think so. Anyway she's there now.

**Comment by user1011** [comment]
The quest Jango Spothide puts you into another phase.
I am currently having this issue.

**Comment by arndry** [comment]
I was about to submit the issue but waiting a moment she appears in the place where she's supposed to be. I accept the secret tower quest. let's see if she turns invisible again or nah
