### ISSUE TITLE
Dungeon problem.. 

### ISSUE THREAD

**Issue by ijsadjisdaiojsdai** [Atlantiss/BugTracker#7737]
So i was playing in the maraudon dungeon and once we finished it i got killed by some mobs ( i play as a  shaman ) and it took my back to the graveyard in the dungeon so i decided to leave the party and respawn myself as soon as i find my corpse . But once i left the party and went to my body i was unable to respawn . It says "resurrect now " and when i click on " accept " , absolutely nothing happens ... I am not sure what i am supposed to do ,since i am new to this game and so i am asking for your advice !

**Comment by user1011** [comment]
Try relogging?

**Comment by Aival94** [comment]
Normally when you enter a dungeon you will get resurrected immediately. If this does not work either relog or use /script RepopMe()
