### ISSUE TITLE
[PL][Quest][Ashenvale] Hot Lava

### ISSUE THREAD

**Issue by garlyn** [Atlantiss/BugTracker#7738]
Co jest zbugowane: Nie można wziąć questa od NPC - Core. Pojawia się jedynie okno z pozdrowieniami.

Zdjęcie sytuacji: 
![wowscrnshot_062916_125233](https://cloud.githubusercontent.com/assets/16537604/16449545/6157428c-3df8-11e6-89ff-bbd18173788f.jpg)

**Comment by Aival94** [comment]
Is Visual bug.
Complete first [Go With The Flow(Alliance)](http://www.wowhead.com/quest=13877/go-with-the-flow)
