### ISSUE TITLE
[PL][Quest][Ashenvale] Put out the fire

### ISSUE THREAD

**Issue by garlyn** [Atlantiss/BugTracker#7739]
Co jest zbugowane: Nie można wziąć questa od NPC - Arctanus. Pojawia się jedynie okno z pozdrowieniami.

Zdjęcie sytuacji: 
![wowscrnshot_062916_124515](https://cloud.githubusercontent.com/assets/16537604/16449598/b6bb6e06-3df8-11e6-9826-006c2fe240b5.jpg)

**Comment by Aival94** [comment]
Is Visual bug.
Complete first [Go With The Flow(Alliance)](http://www.wowhead.com/quest=13877/go-with-the-flow)
