### ISSUE TITLE
[PL][Report Gracz Wyzwanie]

### ISSUE THREAD

**Issue by czeru** [Atlantiss/BugTracker#7741]
Oto jak pewien miły paladyn o Niku ( Welos ) postanowił wrazić swoje mniemanie na czacie , gdyby to miało jedno razowe miejsce to bym to zlekceważył ale to nie pierwszy raz.

![wowscrnshot_062916_145224](https://cloud.githubusercontent.com/assets/3833749/16453475/3f698742-3e0d-11e6-949f-ea17cb76bf02.jpg)
![wowscrnshot_062916_145256](https://cloud.githubusercontent.com/assets/3833749/16453476/3fc2d7c0-3e0d-11e6-984b-92d37113a3f9.jpg)

**Comment by BAndysc** [comment]
To jest bugtracker
