### ISSUE TITLE
[EN][Quest][Ashenvale] The Last Stand

### ISSUE THREAD

**Issue by immersedone** [Atlantiss/BugTracker#7742]
Quest is bugged, won't spawn the "Demonic Invaders" that are required to finish the quest.

A link for the quest as on WOW Head and Youtube are below:

http://www.wowhead.com/quest=13987/the-last-stand

http://youtu.be/yMsbu2-mUI4

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/660
