### ISSUE TITLE
[EN][Shaman][Spell] Earth Shield

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#7743]
Pretty self-explanatory. Upon casting Earth Shield on the caster, I get a message "Spell not ready yet" and I die very fast because of it. Sometimes this lasts for 5 sec sometimes for over a minute. Never in the history of Shaman play has ES ever ever had an internal cd.

**Comment by BialyADI** [comment]
It have 3,5s.

**Comment by captjvmoore** [comment]
@BialyADI you missunderstand. Nothing besides silence and cc that causes to lose control over your character can forbid you from spaming ES as much as you like. However, when I try to cast and re-cast, I get this message "Spell not ready yet" and ES does not cast. Sometimes this lasts for 5 sec, sometimes for up to a minute.

**Comment by Illusie** [comment]
I have same issue, and my friend has same problem.
when he get auto-attack he can't "spam" the earth-shield.
he click it but the spell is not cast itself. like stucked or something like that.

its damn mandatory and top periority to fix. for PvP I can say I lost few arenas because of it :/

**Comment by Bustyplz** [comment]
ye it's 100% bugued, i have this bug too and i cant spam my earth shield, when someone hit me with physical damage (like auto attack) i cant use my earth shield during 5sec (sometime it's more, like 20sec)

**Comment by TranceAccount** [comment]
Please provide a WoWhead link to the Spell.

**Comment by blinkmaster** [comment]
Bump

**Comment by Aival94** [comment]
Since wowhead have a new updated Earth shield which is from honor i will give openwow and wowpedia link:
Wowpedia Link: [Earth Shield](http://wow.gamepedia.com/index.php?title=Earth_Shield&oldid=2801937)
Openwow Link: [Earth Shield](http://cata.openwow.com/spell=974)

**Comment by Malylolek** [comment]
From #8111 


earth shields healing should happen after the damage was taken which triggered it, not before

http://cata.openwow.com/spell=974 earth shield

proof:
https://www.youtube.com/watch?v=_CStLA51Q7U (3:32)

prayer of mending and living seed might have the same problem
http://cata.openwow.com/spell=33076 prayer
http://cata.openwow.com/spell=48496 seed rank1
http://cata.openwow.com/spell=48499 seed rank2
http://cata.openwow.com/spell=48500 seed rank3

**Comment by zorix** [comment]
Fixed in rev. 5206

**Comment by lamaATS** [comment]
Fixed in rev.  5206
