### ISSUE TITLE
[EN][Quest] Violet Eye Ring Quests

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7749]
http://www.wowhead.com/quest=10729/path-of-the-violet-mage
http://www.wowhead.com/quest=10730/path-of-the-violet-restorer
http://www.wowhead.com/quest=10731/path-of-the-violet-assassin
http://www.wowhead.com/quest=10732/path-of-the-violet-protector

these quests and all that follow it as you gain more reputation, should only be one chain per person. You chose which one you want and then you continue with that particular questline. Currently, you can get all 4, and get all 4 upgrades at the same time. This shouldn't be possible

Also, as you get higher rep, the previous ring should be taken from your character and a better version given as a reward.  Currently you get to keep all versions. (I know they're unique-equipped so you can't wear 2 at the same time but it clutters up your inventory a lot and they don't sell for anything so meh) 

Additional issue that might exist because you can get all of the rings already but these quests are missing from the npc that gives out the rings:
http://www.wowhead.com/quest=11031/archmage-no-more
http://www.wowhead.com/quest=11033/assassin-no-more
http://www.wowhead.com/quest=11032/protector-no-more
http://www.wowhead.com/quest=11034/restorer-no-more
Those should open up after receiving the exalted version of whichever ring you chose, so you can, if you wish, pick another one. 

ps. Before anyone attacks me on the post saying I can just delete the rings and shouldn't bother posting mundane stuff like this. Bugs are bugs, and even if they're not important they should be reported. It's up to the devs to fix it or ignore it.

**Comment by tomatosz** [comment]
Posted fix for the first part on the forum:

https://community.atlantiss.eu/index.php?/topic/14715-7749-path-of-the-violet-quests/

**Comment by tomatosz** [comment]
Posted another partial fix:

https://community.atlantiss.eu/index.php?/topic/14747-quests-violet-rings-exchange-and-duplicate-rings-fix/

Only non-fixed part now (which is not mentioned in the original post) is that you can't get deleted rings back from the questgiver. I will make a new issue for that.
