### ISSUE TITLE
[EN][Spell][Warlock] Healthstone

### ISSUE THREAD

**Issue by pahanzt** [Atlantiss/BugTracker#775]
1. http://cata.openwow.com/spell=6262
2. I'm not 100% sure but It wont heal you when you have full health.
3. Bug was noticed 19.12.2014
4. Value: 1/10.

P.S. As I noticed, every in-game item which can heal actually heals you whenever you are at full health or not.

**Comment by kadi2** [comment]
Did it crit for anyone on the server or i was so unlucky with it?

**Comment by Wolffenstein** [comment]
Fixed in rev 4441.
