### ISSUE TITLE
[EN][Quest][Tirisfal Glades, Deathknell] Recruitment

### ISSUE THREAD

**Issue by Garrota** [Atlantiss/BugTracker#7752]
The quest "Recruitment", one of the first Undead race quests, is not working. Quest NPC Darnell dont do what he suppose to do - grab corpses of the alliance NPC dead warriors. Thats why I cant move on with undead race quests, cause I have to finish this one first, but it is impossible. This makes playing undead race not possible too, there were 3 players just like me that stuck with similar problem.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3460

**Comment by wtRCH** [comment]
Working. Not all corpses are able to pick up, more of them are bugged and unable to.
