### ISSUE TITLE
[EN][Quest][Silverpine Forest,Deep Elem Mine]  Nowhere to Run

### ISSUE THREAD

**Issue by alex007me** [Atlantiss/BugTracker#7753]
![d5a7ea487d57bae5cec0107357840c74](https://cloud.githubusercontent.com/assets/20255098/16539978/aa4a8d8a-405c-11e6-8517-78b04a92015c.jpg)

**Comment by Kiperr** [comment]
Befoure you apply a bug report, please read the rules.
