### ISSUE TITLE
[EN] Can't log in after connecting account with other by RaF system

### ISSUE THREAD

**Issue by Garrota** [Atlantiss/BugTracker#7754]
Hello, need a help! Can't login after using RaF. I have send my link to my friend, he registered an account, but since then nor me, neither my friend cant connect account. The game shows error: "The information you have entered is not valid", tho both password and login are correct, because I can enter profile of my account on the website.

**Comment by user1011** [comment]
If the password is longer than a certain amount of characters you can't login in the game. I belief it was >16.

**Comment by Garrota** [comment]
Thank you for your answer, user1011, i was mistaken, I really forgot my account password and now since i get my password back I can log into my account in the game. But the problem with my friend's account still happening. I mean, if in my case it was really about wrong password, but in this case its some kind of issue I dont understand. 
The account of my friend is new, never ben logged from it into the game, but still the game telling us that "The information you have entered is not valid", tho it is really valid, i checked it like 10 times. Password is smaller than 16 symbols, so yeah, dont know what to do.
Btw, in my profile on atlantiss website I can see that i got accounts registered with my link: 1
