### ISSUE TITLE
[EN][Armory][Website] Armory

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#7756]
Hey hello,
Wondering if Armory will get fix.

I am talking about Character review.
When I am entering to review Someone -X- page I can't see anything about him.

Screenshot:
http://oi68.tinypic.com/jafn28.jpg
Tried via Chrome, Firefox, Aion

Also I think the Armory can be more improved in many things.

**Comment by user1011** [comment]
He might have full firelands gear.
Try this: http://community.atlantiss.eu/index.php?/topic/10071-website-armory-openwow-tooltip/

**Comment by Illusie** [comment]
@user1011 cool thanks, :)
that thing still not showing Gems, But still cool. better than nothing.

**Comment by xmesaj2** [comment]
#5613

**Comment by xmesaj2** [comment]
Fixed as of 02/07/2016
