### ISSUE TITLE
[EN][Quest][Wetlands] Anvilmar the Hero

### ISSUE THREAD

**Issue by BehindTimesGame** [Atlantiss/BugTracker#7757]
Unable to complete the quest because Thargas Anvilmar does not have a Quest marker and you can not interact with him.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7407, https://github.com/Atlantiss/BugTracker/issues/7182, https://github.com/Atlantiss/BugTracker/issues/3925
