### ISSUE TITLE
[PL][Quest][Westfall] Secrets of the Tower

### ISSUE THREAD

**Issue by Ahanai** [Atlantiss/BugTracker#7761]
Quest "Secrets of the Tower" w Westfall jest zbugowany i nie da się go zrobić. Po użyciu mikstury dalsza część questa w ogóle się nie odpala
http://www.wowhead.com/quest=26290/secrets-of-the-tower

**Comment by Thefakemccoy** [comment]
https://github.com/Atlantiss/BugTracker/issues/2338
