### ISSUE TITLE
[EN][Quest][Zone] Pilgrim's Bounty Elwynn Forest

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7762]
[EN][Quest][Zone] Pilgrim's Bounty Elwynn Forest = http://www.wowhead.com/quest=14022/pilgrims-bounty

this quest can't be finished because of the ending NPC how give the reward for the quest is missing

[EN][NPC] Gregory Tabor = http://www.wowhead.com/npc=34675/gregory-tabor

now.... watching the internet I saw that that mission is available only the last week of nobember, so... why this mission is available out of that range of time if nobody can be able to finish it due to the missing NPC? fix this please

**Comment by Luna-maria** [comment]
the commoners have several seasonal quests that show up whenever they spawn, happens nearly every seasonal event :) just ignore the quests that aren't related to midsummer at the moment ^^

**Comment by arndry** [comment]
thanks for reply (y)
