### ISSUE TITLE
[EN][Quest][Tirisfal Glades] The Shadow Grave 

### ISSUE THREAD

**Issue by smrda** [Atlantiss/BugTracker#7763]
This quest was supposedly fixed but it's been bugged again for 2 days that I have known.
There is no loot window when you try to loot the items, so you can't take them. 
This is preventing all players from starting new undead characters...

http://www.wowhead.com/quest=28608/the-shadow-grave

**Comment by Brego55** [comment]
No it's not, you can skip this quest buy killing few mobs and start with quests right after starting zone at lvl 5, with pumpkins or whatever it is there. Or even go to The Brill, I had the same problem too. Anyway it will be fixed soon, rev. 5079 by Bandysc "Quest 'The Shadow Grave' will no longer bug when player doesn't loot objects"
