### ISSUE TITLE
[EN][Quest][Nagrand] Not on my watch 

### ISSUE THREAD

**Issue by Vellorie** [Atlantiss/BugTracker#7764]
Lump appear for one or two seconds and after that disappear. I can not catch him for quest.

**Comment by Kleanex** [comment]
http://www.wowhead.com/quest=9918/not-on-my-watch

http://www.wowhead.com/quest=9918/not-on-my-watch#videos

**Comment by Vellorie** [comment]
Yes, the quest is still infeasible, because Lump disappear. This quest is really important for people who want make reputation in Kurenai's

**Comment by Bildo** [comment]
duplicate

**Comment by Vellorie** [comment]
Well u don't solve the problem :(
