### ISSUE TITLE
[EN][Quest][Western Plaguelands] Combat Training 

### ISSUE THREAD

**Issue by skalante2569** [Atlantiss/BugTracker#7765]
I CAN'T TALK WITH GORY FOR DEFEAT HIM AND DO THE QUEST.
[gory defeated]
http://www.wowhead.com/quest=27174/combat-training

**Comment by arndry** [comment]
same here

**Comment by Noviush** [comment]
Still not working

**Comment by RastaTinu** [comment]
Quest still doesn't work

**Comment by baks93** [comment]
further inaction/ dalej niedziała :(

**Comment by alexasylum** [comment]
Quest STILL NOT WORKING!!! Cannot speak with Gory to challenge to combat.

**Comment by xmesaj2** [comment]
fixed in rev. 5389
