### ISSUE TITLE
[EN][Quest][Eastern Kingdoms][Badlands][Alliance] Lifting the Veil

### ISSUE THREAD

**Issue by Kleanex** [Atlantiss/BugTracker#7766]
http://www.wowhead.com/quest=27770/lifting-the-veil

Hello, the alliance quest does not, the bug was repaired side horde #6774, would it possible to adapt the script for the other side?
Thank you

**Comment by Bildo** [comment]
it wasnt repaired

**Comment by Kleanex** [comment]
Hello,
I reiterate my request, can you adapt hordeux script to the package alliance or put the search in the car validation in order to continue the adventure please, thank you

**Comment by Bildo** [comment]
Horde version is not scripted either.

**Comment by Kleanex** [comment]
@Bildo 
Do you have write on the ticket #6774 that the search was valid, out the screen mentions a Goblin as player, I deduce from it that script is ok for the horde, can you please modify it for alliance?
  

https://github.com/Atlantiss/BugTracker/issues/6774
Bildo  commented on Jun 7 • edited Bildo edited this comment about 1 month ago 

Work in progress
wowscrnshot_060716_002750
  
:heart: 1 Angelo-DM- reacted with heart emoji
