### ISSUE TITLE
[EN][Quest][Azuremyst Isle] Hunter Training

### ISSUE THREAD

**Issue by Kalua96** [Atlantiss/BugTracker#7768]
It's just a minor one, but once you reach level 3, you just immediately get the quest "Hunter Training" (Though I don't know whether that's actually blizzlike); you can finish it normally, but there's no text at all from Keilnei, the trainer. Just the quest title and then the "Complete Quest" and "Cancel" buttons.

**Comment by Aival94** [comment]
Next time better give link of quest and if possible a video of how it should be.

Wowhead Link: [Hunter Training(Horde)](http://www.wowhead.com/quest=9393/hunter-training) and [Hunter Training(Alliance)](http://www.wowhead.com/quest=9288/hunter-training)

Completion text should be([Wowhead Proof](http://www.wowhead.com/quest=9288/hunter-training#comments:id=47620)):
"I'm glad that you have come to me. For quite some time now I have been responsible for the training of our young hunters, a responsibility that I intend to continue on this new world. I've had my eye upon you for a while now and it would be my honor to help train you in the ways of the hunter.

"Shall we begin?"

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12264-7768azuremyst-isle-hunter-training/
