### ISSUE TITLE
[EN][Core][DB]INT(10) UNSIGNED Means in-game mail will fail in approx. 90 years 

### ISSUE THREAD

**Issue by sunshitwowsucks** [Atlantiss/BugTracker#7772]
Description:

INT(10) UNSIGNED is not big enough to handle UNIX timestamps into infinity

Current behaviour:

mail.expire_time and mail.deliver_time will overflow at: 2106-02-07 at 06h 28m 16s (24h time) which is approx. 90 years from the time of this post.

Expected behaviour:

The database should be robust enough to allow continued operation

Steps to reproduce the problem:

Max value of an INT(10) UNSIGNED is 4294967295 which is 2106-02-07 at 06h 28m 15s (24h time)

Attempt to insert 4294967296 into mail.expire_time and mail.deliver_time
You will get an error: WARNING CODE: 1264, Out of range value
NOTE: 4294967296 is 2106-02-07 at 06h 28m 16s (24h time)

TDB version: TDB_full_world_335.61_2016_04_11.sql

Operating system: N/A

NOTE: UNIX timestamps calculated using

http://www.csgnetwork.com/time2unixdscalc.html
http://www.csgnetwork.com/unixds2timecalc.html

**Comment by Wolffenstein** [comment]
Fixed in rev 5084.

**Comment by sunshitwowsucks** [comment]
broken again
