### ISSUE TITLE
QUEST CATA A Vision of the Past 

### ISSUE THREAD

**Issue by Valoiz** [Atlantiss/BugTracker#7773]
This NPC ends quest http://www.wowhead.com/quest=26319/secrets-revealed.
Then he should give me next mission http://www.wowhead.com/quest=26320/a-vision-of-the-past.
Unfortunately he didn't gave me any mission, but he has BLUE question mark upon his head. When i click on him, dialogue window to complete quest open. When I click on "Complete Quest" nothing happens. At lest let us complete the quest and move on ....

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6212, https://github.com/Atlantiss/BugTracker/issues/1622
