### ISSUE TITLE
[EN][Quest][Silverpine Forest] Nowhere to run

### ISSUE THREAD

**Issue by Kalua96** [Atlantiss/BugTracker#7775]
In the quest, you're supposed to escort Master Forteski through the mine, but he doesn't go into it, and talking to him only makes him say "Greetings [Name]".
How it should be: 
ttp://www.wowhead.com/quest=27195/nowhere-to-run
https://www.youtube.com/watch?v=3a--gbWzQpY&feature=youtu.be

In the game, it looks like the screenshot provided here: #7753 (It's closed, but only with an answer saying to look into the rules, and I can't find any mention of the quest in the changelog)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/7710
