### ISSUE TITLE
Bugged DK in started place- Unop

### ISSUE THREAD

**Issue by Zieluu** [Atlantiss/BugTracker#7776]
Hello ! 
My DK is bugged. When I do quest THE LIGHT OF DAWN I thought that it's bugged and i delete it. After that I used Hearthstone and moved me to started place. Furthermore there are no NPCs and teleport doesn't work too. I am bloced and can't do anything. All NPCs and quest to continue game is on down but I can't to get there. If you cant summon me down I would be very happy.

Unop

**Comment by Bildo** [comment]
read bt rules
