### ISSUE TITLE
[EN][Quest][Deepholm] Elemental Energy

### ISSUE THREAD

**Issue by deckerdew** [Atlantiss/BugTracker#7778]
Hello Atlantiss support, one of the starting quests in Deepholm: Elemental Energy seems to be bugged now.

I finished it with all my toons before, and now with my new character when I'm trying to do this quest is not working: When you place the totem even if you are, even if you are not attacking the mob (Energized Geode and/or Lodestone Elementals) (and also killing it) it's not being counted, so it's also impossible to follow the Therazane quest chain.

**Comment by deckerdew** [comment]
http://www.wowhead.com/item=60835/depleted-totem

**Comment by deckerdew** [comment]
Check full bugtracker. This issue is happening only now, before it was working.

**Comment by xmesaj2** [comment]
After server uptime is long some things might start bugging out, I remember this quest working correctly, but need to verify after next server restart if it is just temporary problem

**Comment by deckerdew** [comment]
Yeah, it has to be temporary, as I sais before I already did this quest before with pala/DK.
