### ISSUE TITLE
[EN][Spell][Death Knight] Dark Simulacrum

### ISSUE THREAD

**Issue by Kubelecer** [Atlantiss/BugTracker#7779]
I have recently seen my Dark Simulacrum do nothing on a mage, expiring without copying a thing while he was casting, and today I tested it and managed to see that this spell will not copy ring of frost, which it should. I am sure that there are other spells that won't work, but with the 1 min cd it's very tiresome to check everything.

Using this list 
http://www.arenajunkies.com/topic/177503-the-dark-simulacrum-list/
and 
http://us.battle.net/wow/en/forum/topic/2838574174
I managed to test all mage spells in a duel, with the exception of the useless category ones, and out of all the useful spell, only ring of frost wasn't working. I also just saw a frost mage doing frost nova with my debuff and then frostfire orb, but instead of copying nova i got the orb, which was pretty weird considering  I was getting it earlier, which makes me thing that the mage shields could be the reason this spell fails to steal sometimes.

 I'd say this is a pretty big deal considering how powerful that spell is. There were also some PvE  encounters with spells that I supposedly could copy based on comments, like Bloodletting from Mandokir in Zul'Gurub but was unsuccesful, http://www.wowhead.com/npc=52151/bloodlord-mandokir#comments:id=1407922 , _might be outdated as it's reffering it in 4.2_, so this bug might be more widespread.

**Comment by Kubelecer** [comment]
I also just realized this has already been posted, but I couldn't find it because of a typo

**Comment by Aival94** [comment]
Related: https://github.com/Atlantiss/BugTracker/issues/3476, https://github.com/Atlantiss/BugTracker/issues/362

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/362
