### ISSUE TITLE
[EN][Achievement][Duskwood] Explore Duskwood

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7780]
I completed the requirements to get the achievement but no luck. It is bugged or just happened to me?

Do I need to put a wowhead link to this?

here's the screenshot, check the chat window and the place where I'm

![wowscrnshot_070816_014726](https://cloud.githubusercontent.com/assets/20273373/16678532/fe52ba06-44ad-11e6-90e4-4dd8b4ef7c5f.jpg)

**Comment by Bildo** [comment]
You didnt complete requirements for this achievemtn, 1 spot is missing

**Comment by arndry** [comment]
DUDE! read the chat box. ""Has descubierto Arboleda del crepusculo"" the missing requirement that you alegate is the one that I just discovered.....

translation "" You have discovered twilight grove""... Did you see that portal in front of me? is the portal located in twilight grove! and twilight grove is the missing requirement?

**Comment by Pombywa** [comment]
Also experienced this bug. Hope to see it resolved.

**Comment by Nergleth** [comment]
I had a problem with Twilight Grove too, but a minute ago i got the achievement. Below i've attached screen with a place where i was standing 

![wowscrnshot_090516_232719](https://cloud.githubusercontent.com/assets/11330667/18257212/779b468a-73c0-11e6-892a-d2592eb8b191.jpg)

**Comment by MercuricUma** [comment]
![wowscrnshot_011518_233831](https://user-images.githubusercontent.com/35276089/34964336-74f9f088-fa4d-11e7-987f-4fbea405f903.jpg)
 Same thing here. Just discovered the last spot I needed but it didn't give me the achievement

**Comment by MercuricUma** [comment]
Got the achievement few minutes later when dungeon opened but apart from a tower place (that wasn't on the achievement list) I didn't discover anything o.o
