### ISSUE TITLE
[EN][Spell][Warlock] Shadowburn

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7785]
Shadowburn= http://www.wowhead.com/spell=17877/shadowburn
does not work properly on murlock in Wetlands.
does not work properly on gnomes in The Dagger Hills Instance Westfall

Edit: does not work on any mob in Wetlands

**Comment by Jenovas** [comment]
Just did tests. Everything seems fine.
Closing.

**Comment by arndry** [comment]
I will update with a video soon

**Comment by arndry** [comment]
I hope this video can show you what I'm talking about [https://youtu.be/jQLh1DianXo](url)

**Comment by Jenovas** [comment]
If the target dies and yields experience or honor, one Soul Shard is energized.
Please read the spell...
you are 11 levels above the NPC, the NPC name is gray that means it gives no exp that means you wont get soul shards.

**Comment by arndry** [comment]
uhm I did not know that game mechanics. thanks for answering
