### ISSUE TITLE
[EN][Spell][Warlock] Drain Soul

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7786]
Drain Soul = http://www.wowhead.com/spell=103103/drain-soul

does not work on murlocks in Wetlands
does not work on gnomes in The Dagger Hills Instance Westfall

Edit: does not work on any mob in Wetlands

**Comment by Jenovas** [comment]
Just did tests. Everything seems fine.
Closing.

**Comment by arndry** [comment]
I will update with a video soon

**Comment by arndry** [comment]
I hope this video can show you what I'm talking about [https://youtu.be/jQLh1DianXo](url)

**Comment by arndry** [comment]
if you're still skeptical after seeing the video and want me to do another one with the missed mobs  Let me know. But those spells as you can see are broken! at least for all of this area Mobs.

**Comment by Jenovas** [comment]
If the target dies and yields experience or honor, one Soul Shard is energized.
Please read the spell...
you are 11 levels above the NPC, the NPC name is gray that means it gives no exp that means you wont get soul shards.
