### ISSUE TITLE
[EN][NPC] Quartermaster Enuril

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7787]
Quartermaster Enuril of the Scryers (http://www.wowhead.com/npc=19331) sells 2 recipes that belong to his Aldor counterpart:
http://www.wowhead.com/item=24295
http://www.wowhead.com/item=24293

It should be Endarin (http://www.wowhead.com/npc=19321) who sells them.

**Comment by user1011** [comment]
Can you make a screenshot of it? I don't have access to the Scryer's quartermaster, because I chose the Aldor.

**Comment by MichaelArchangelo** [comment]
http://imgur.com/a/m7km3

**Comment by user1011** [comment]
Thank you. I'll look into it.

**Comment by user1011** [comment]
Posted a fix on the forums.
