### ISSUE TITLE
Invalid Target

### ISSUE THREAD

**Issue by Hanauske** [Atlantiss/BugTracker#7790]
When i want tame beast it say "invalid target" i dont know why. I thought is that was untameable pets but i tried it on normal tameable pet and it was "invalid target" again. I dont know what can I do in this situation. :( Please help me. :/ 
Troll, Hunter lvl 58 
Pets (invalid target):
Grubthor 
King Mosh
Young Diemetradon 
Tyrant Devilsaur
All pets have smaller level than me.
Btw, sorry for my Gramatic English >.<

**Comment by Bildo** [comment]
read bt rules
