### ISSUE TITLE
[EN] Quest [SilverPine Forest] Nowhere to run.

### ISSUE THREAD

**Issue by Casually1987** [Atlantiss/BugTracker#7792]
This quest is broken. the npc Master Forteski does not move when you accept the quest. You can spea k to him but there is no option to allow him to move.
the quest should look like this. https://www.youtube.com/watch?v=WMNwGtR9ajg

this is the wowhead link. http://www.wowhead.com/quest=27195/nowhere-to-run

**Comment by krecik88** [comment]
tested it just before, working

**Comment by Casually1987** [comment]
ya for some reason the quest now works. very odd i tried restarting it like 10x yesterday but perhaps the maintenence or something fixed it. thanks.

**Comment by Bildo** [comment]
Well next time see changelog.
