### ISSUE TITLE
[PL][Warrior][Druid] Rage and Dots, Channeling Spells

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7794]
Poprzedni ticket: https://github.com/Atlantiss/BugTracker/issues/7703.

Tak jak Jenovas napisał sprawdziłem generowaną ilość Rage przed otrzymane Dmg od DoT i Channeling Spells, i niby jest generowane nawet Dotki od DK generują ale jest tego strasznie mało.

Zrobiłem proste porównanie z filmikiem Swiftego:
https://youtu.be/aDT28yQfHMY?t=1m22s <- tutaj widać jak Warlock Affi zbija Swiftiego z 100% do 0%(Doty, Darin Life, i Direct Dmg jeden Haunt). Po zbiciu Swifti miał ok 50 Rage 

Powtórzyłem to kilkukrotnie i Rage po zbiciu z 100% do 0 mojego warka osiągał max 20 Rage(używałem też Hounta, ogólnie zwykła rotacja Locka).
Jeden z testów:
![wowscrnshot_071116_003952](https://cloud.githubusercontent.com/assets/5780624/16716631/4b91b2f8-4702-11e6-9cca-486902e2297a.jpg)

Generowany Rage z otrzymywanego Dmg z DoT, ogólnie z Magii jest dość mocno zaniżony, po testuje potem tez inne magiczne klasy do których mam dostęp.

**Comment by BialyADI** [comment]
![wowscrnshot_071116_010734](https://cloud.githubusercontent.com/assets/5780624/16716677/f736e82a-4703-11e6-8b94-3c6159ec5afe.jpg)
Inny przykład po Duelu z Lockiem Affi dużo lepiej ubranego niż mój, ten był full Ruthless.
Po zbiciu mnie z 100% od 0, 21 Rage :(.
Powinno być coś w granicach 40-50, gdy by ten Dmg był Fizyczny tyle by Rage wygenerował, pamiętam wcześniej otrzymywany fizyczny Dmg mało co generował Rage Warkom/Drutom ale jest ok zgadza się na oko z filmikami, szkoda ze ciężko znaleść w necie dokładną formułę.

**Comment by Piklo** [comment]
Na filmiku wyraźnie widać że pet warlocka też bije warriora, na pewno sprawdzaliście to z petami? Nie jestem pewien ale pet chyba bije trochę obrażeń fizycznych, a to może generować więcej rage'a

**Comment by BialyADI** [comment]
Lock na Duelu bił też petem i udało mu się wygenerować mi 21 Rage zamiast 20 co mi się udawało bez peta. Zresztą każdy sam może sam się przekonać że generowany Rage z Magii jest jakiś lipny w stosunku do tego co widać na filmikach ;x.

**Comment by sunshitwowsucks** [comment]
warr fury rage so broken

**Comment by BialyADI** [comment]
Yeah its hard to get Rage with fury and that miss witch AA dont Help too.

**Comment by sunshitwowsucks** [comment]
sucks fury warrior is really fun and its annoying to have to use berserker rage or battle shout everytime

**Comment by BialyADI** [comment]
Crit dont geave you 2x Rage on Cata, but miss should but no one belive my proofs and close my ticket about that ;x.

**Comment by sunshitwowsucks** [comment]
you have any info that misses give rage?

**Comment by BialyADI** [comment]
There is ticket about that witch video, its nvm naw i hope that Jenovas will repair that Rage form Magic Dmg.

**Comment by BialyADI** [comment]
Bump

**Comment by BialyADI** [comment]
Bump.

**Comment by Jenovas** [comment]
Fixed rev 5231
