### ISSUE TITLE
Missing mining nodes

### ISSUE THREAD

**Issue by selmira** [Atlantiss/BugTracker#7795]
Mining nodes are really rare for some reason, and there is nothing more annoying when you finally find one and it is missing. My mining is at 180 at the moment and I've already found around 15-20 missing nodes. I've accidentally found one underground when blinking, some might be in the air. No clue.
Here is a picture: http://imgur.com/NmxDEcb
My minimap is fully zoomed in for this picture to show that the mineral should be right in front of me or under me. It is gone.
As i said, this is not the first time it happened to me. It's really disappointing since the minerals are so rare.

Thank you for your time

**Comment by Aival94** [comment]
Use the Bugtracker rules to make a report: [Bugtracker Rules](https://github.com/Atlantiss/BugTracker/blob/master/README.md)

Furthermore for this bug to be fixed might need every node with this bug to be reported with coordinates.
