### ISSUE TITLE
[PL][QUEST][WESTFALL][A Vision of the Past]

### ISSUE THREAD

**Issue by Sibool** [Atlantiss/BugTracker#7796]
Po dotarciu duchem do celu wszyscy stoją w miejscu dłuższy czas i znikają totalnie nic się nie dzieje sprawdzałem parę razy dla pewności ale nie działa. Proszę o naprawienie.
https://www.youtube.com/watch?v=ZFZBM42jdmY Tak to powinno wyglądać.

**Comment by Bildo** [comment]
duplicate
