### ISSUE TITLE
[PL][Quest]  The yorgen worgen

### ISSUE THREAD

**Issue by wisnia098** [Atlantiss/BugTracker#7799]
Zgłaszam ,że wymieniony niżej quest jest zbugowany
[PL] po wzięciu questa jest on wykonany natychmiastowo ,lecz nie można go oddać ..

[EN][Quest][Zone] the yorgen worgen
[EN][NPC] Apptenlce Fess

**Comment by wisnia098** [comment]
![wowscrnshot_0](https://cloud.githubusercontent.com/assets/20402858/16737598/6a8a78bc-4792-11e6-87bb-9777ca3458b7.jpg)
![wowscrnshot_071116_180458](https://cloud.githubusercontent.com/assets/20402858/16737611/758d49ba-4792-11e6-9592-d6dd6ba16a20.jpg)

**Comment by wisnia098** [comment]
osobiście problem rozwiązałem "zamykam "

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/7426
