### ISSUE TITLE
[EN][Trainer][Professions][Jewelcrafting]Design missing: Punisher's Band

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7800]
http://www.wowhead.com/item=69853/design-punishers-band#sold-by

this design is missing from vendors in stormwind. According to wowhead it should be sold by Terrance http://www.wowhead.com/npc=44583 
My Ackis recipe list addon says it should also be sold by Isabel Jones http://www.wowhead.com/npc=50480 . This seems more logical to me because she also sells all the other recipes 

note, ironforge vendor does sell it http://www.wowhead.com/npc=52584/laida-gembold but that doesn't change the fact it should be available in stormwind as well
I can't even talk to http://www.wowhead.com/npc=52644/tarien-silverdew who should also vendor it (no chat or something opens when clicking him) 
The Exodar vendor http://www.wowhead.com/npc=17512/arred also doesn't vendor it, but should according to wowhead

**Comment by Bildo** [comment]
fixed
