### ISSUE TITLE
[EN][Professions] WotLK Jewelcrafting Designs Boss Drops

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7802]
Design: Deadly Monarch Topaz - Keristraza 26723 , The Nexus (Heroic only) http://www.wowhead.com/?item=41794
Design: Deft Monarch Topaz - Sjonnir the Ironshaper 27978 , Halls of Stone (Heroic only) http://www.wowhead.com/?item=41792
Design: Fierce Monarch Topaz - Ingvar the Plunderer 23954 , Utgarde Keep (Heroic only) http://www.wowhead.com/?item=41793
Design: Infused Twilight Opal - Anub'arak 29120 , Azjol-Nerub (Heroic only) http://www.wowhead.com/?item=41796
Design: Precise Scarlet Ruby - Herald Volazj 29311 , Ahn'kahet: The Old Kingdom (Heroic only) http://www.wowhead.com/?item=41790 
Design: Thick Autumn's Glow - Cyanigosa 31134 , The Violet Hold (Heroic only) http://www.wowhead.com/?item=41791
Design: Timeless Forest Emerald - The Propeht Tharon'ja 26632 , The Drak'Tharon Keep (Heroic only) http://www.wowhead.com/?item=41795

Design: Austere Earthsiege Diamond http://www.wowhead.com/item=41797 - King Ymiron 26861 , Utgarde Pinnacle (Normal and Heroic)
Design: Bracing Earthsiege Diamond http://www.wowhead.com/item=41798- Cache of Eregos http://www.wowhead.com/object=191349/cache-of-eregos http://www.wowhead.com/object=193603/cache-of-eregos, The Oculus (Normal and Heroic)
Design: Eternal Earthsiege Diamond http://www.wowhead.com/item=41799/design-eternal-earthsiege-diamond - Loken http://www.wowhead.com/npc=28923/loken , Halls of Lightning (Normal and Heroic)

these should all have a 100% droprate
proof: 
http://us.battle.net/wow/en/item/41799
http://us.battle.net/wow/en/item/41793
http://us.battle.net/wow/en/item/41790
http://us.battle.net/wow/en/item/41797
http://us.battle.net/wow/en/item/41798
http://us.battle.net/wow/en/item/41799

yes, I realize not all of them have the 'garantueed' post but it shows a meta design and 2 other uncommon drops. Experience on retail is that they only show when you're a Jewelcrafter, and because of this, the droprate on wowhead is a bit off because there's plenty of groups running the dungeons when they don't have someone with jewelcrafting with them

(also probably don't have to say it but the npc ids I added are normal mode only, since I don't know the ids for heroic mode without being able to see it in the db :P)

**Comment by sunshitwowsucks** [comment]
On wowhead "Its entirely possible, therefore, for the real drop rate on this item to be much higher than wowhead shows. Its like certain quest items with a functional 100% drop rate showing up as a 10% or lower drop in wowhead- because the quest items only drop when you're on the quest, but people farm the mobs anyway.

Thus, if there's no JC in the party, this item could drop and nobody would know- and thus it wouldn't be registered by wowhead."

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5094
