### ISSUE TITLE
[EN][Quest][Westfall] Secrets of the Tower

### ISSUE THREAD

**Issue by nathielka** [Atlantiss/BugTracker#7803]
http://www.wowhead.com/quest=26290/secrets-of-the-tower
doesn't work at all. 
you have to engage elities in front of the tower and quest giver to one shots them. which is not happening. next, you have to enter the tower, climb up the stairs and use potion, which makes you invisible, so conversation event could happen. potion is useable, however, nothing happens after it.

it's the key quest in chain to Deadmines in Westfall and without completing it, it's impossible to complete 35 quests in zone -> no achiev.

**Comment by Bildo** [comment]
duplicate
