### ISSUE TITLE
[EN][Item][Trinket] Ricket's Magnetic Fireball

### ISSUE THREAD

**Issue by Rozpacz** [Atlantiss/BugTracker#7806]
The passive abillity of this trinket 

http://www.wowhead.com/item=70144/rickets-magnetic-fireball&spec=263

should be 20% chance on every hit.

http://www.wowhead.com/spell=95871/meteor-magnet#used-by-item

![wowscrnshot_071216_135221](https://cloud.githubusercontent.com/assets/20418964/16766105/4a022f3a-4838-11e6-9977-e22a517e2d74.jpg)

Recount while using this trinket shows only 2 activated hits in 130 hits. 
The active chance is too low

**Comment by user1011** [comment]
Change title.
https://github.com/Atlantiss/BugTracker

**Comment by Quban** [comment]
> should be 20% chance on every hit.

yes, you are right, it hase 20% Chance, but it also has 120s internal cooldown so, from what ive read on wowhead it works like intended
