### ISSUE TITLE
[PL][Spell][Paladin] Holy Radiance

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#7810]
lol

**Comment by Jenovas** [comment]
Jak to sprawdziłeś?

**Comment by Piklo** [comment]
Na poniższym zdjęciu jestem delikatnie bliżej niż 10 yardów i mój target nie otrzymuje shielda z mastery holy paladin, choć jest w odpowiedniej odległości od źródła heala w tym przypadku ode mnie
![wowscrnshot_071216_233422](https://cloud.githubusercontent.com/assets/16057987/16784689/3c792664-488a-11e6-9e8e-05bec6535652.jpg)
Na drugim zdjęciu jestem delikatnie dalej niż 8 yardów i mój target dalej nie otrzymuje shielda z mastery
![wowscrnshot_071216_233714](https://cloud.githubusercontent.com/assets/16057987/16784725/60cd2c90-488a-11e6-8da1-414c41d72a7c.jpg)
Na trzecim zdjęciu jestem delikatnie bliżej niż 8 yardów i mój target zaczął otrzymywać shielda, czyli healing over time z holy radiance ma 8 yardów zasięgu. Addon pokazuje dobrze range. Testowane na http://cata.openwow.com/spell=87172 delikatnie powyżej 15 yardów zwiększenie prędkości zostawało aktywowane, delikatnie poniżej 15 yardów już nie zostawało aktywowane

**Comment by Aival94** [comment]
Reported/related: https://github.com/Atlantiss/BugTracker/issues/7376

**Comment by TranceAccount** [comment]
Nice
