### ISSUE TITLE
[EN][Priest] Mind Control

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#7811]
Hey hello!
another Pvp breaker arrived on Atlantiss server.

When someone use a dots on you (dots / bleeds etc) and you get MC
you still take damage through MC

**Comment by Jenovas** [comment]
http://www.mmo-champion.com/threads/642446-Dots-up-and-Mind-Control
Here players claim that it's normal.

Closing. Find proof before creating a new report.

**Comment by Illusie** [comment]
@Jenovas  hey jenovas, can you keep this open?
I don't think you should take dots / bleeds damage when you're Mind Controlled because when you MC someone it consider you as "ally".

Also the healer can't target/heal the one who MC'd.

Its game-breaker duo the fact that someone can fully dot / bleed you out, then you get MC and not able to get heals.

**Comment by Jenovas** [comment]
I'll be checking this topic tomorrow, if I see proof I will unblock it.
Every topic I read seems to say that DoTs still hit, there was even a bug on retail where DoTs hit during mind control as if the player had 0 resilience, so if reports like this exist I think mind control doesnt do anything to DoTs. 

"Its game-breaker duo the fact that someone can fully dot / bleed you out, then you get MC and not able to get heals." you can interrupt mind control and the player casting it can't do any other action, so no this is not gamebreaking in any way.

**Comment by Illusie** [comment]
Yes but interrupting MC
make Priest free cast Mana Burn.

You can't interrupt MC everytime a Priest cast it. MC should be interrupted only on crucial time.

that why we (I & other players) believe MC is being bugged & abused on Atlantiss.

btw,
Tomorrow I'll probably will log to another Cataclysm servers. to check it out myself.

@Jenovas

**Comment by Bustyplz** [comment]
You can interrupt mind control if your teammate is not control by other cc like cyclone or whatever, it can be a game-breaker so that make no sense to said "you can interrupt mind control", but the real point is 

"I don't think you should take dots / bleeds damage when you're Mind Controlled because when you MC someone it consider you as "ally".

And the referenced it another great thing to debug, cause if nobody can dispell the MC so there is only one way to interrupt a MC

**Comment by Illusie** [comment]
Hey hello, Im still digging out every website on Internet that give information about Mind Control.
found this http://us.battle.net/wow/en/forum/topic/2059296210 from 2011.
Read Braxy's message. (Page 1), Otterlover's message (page 2),

We shall not relay on "players claims..." and find a proper source.
but this worth a look.

@Jenovas

**Comment by Jenovas** [comment]
Please search on youtube - mind control wow - you can find many mind control videos, in some of them you can see that players that had DoTs up still take DMG from the DoTs.

**Comment by Illusie** [comment]
@Jenovas did few searches, you should take damage when you MC'd. this post is irrelevant.
yet https://github.com/Atlantiss/BugTracker/issues/6029#issuecomment-232688272
this post is very relevant. as I know you can't purge MC from the target who got the MC.

I think it should be...

@Wolffenstein 
@Aviannaqt
