### ISSUE TITLE
[PL][Quest][Deepholm] Deepholm, Realm of Earth

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#7812]
http://www.wowhead.com/quest=27123/deepholm-realm-of-earth
Jak powinno być: Po zabandonujemy tego questa, portal do Maelstrom powinien być dalej dostępny i możliwy do użycia
Jak jest u nas: Jeżeli zabandonujemy tego questa, nie ma portalu do Maeltromu i żeby mieć ponownie tego questa musimy poprosić GM'a o questa lub inną osobę z tym questem żeby go nam zsharowała i użyć potki która nas teleportuje do deepholm
Problem: Nikt "normalny" raczej nie będzie abandonować tego questa i nie będzie wychodzić z Maelstromu, ale mi się tak zdarzyło, a że nie mogłem wrócić do Maelstromu nie mogłem ponownie wziąć tego questa i musiałem szukać osoby która miała akurat tego questa i chciała mi go zsharować

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5094
