### ISSUE TITLE
[EN][Shaman] Grounding Totem, Tremor Totem

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#7813]
Well, my friend said there some bugs with Grounding totem.
He tried on Arena to ground few things. and they are not grounded at all.
Yet when he tested on 1v1 those things been grounded.

Hunter Freeze Trap.

http://cata.openwow.com/spell=8177

*couldn't find a absorb list of Grounding 4.3.4 :/

About Tremor totem,
http://cata.openwow.com/spell=8143

As I know you should able to tremor Succubus seduction,
and Wyrnn shot from hunter.

*couldn't find a tremored list 4.3.4 :/

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/5350

**Comment by Malylolek** [comment]
Duplicate ~thanks Kadi
