### ISSUE TITLE
[EN][Spell][Shaman] Earth Shield

### ISSUE THREAD

**Issue by ktperyfcker** [Atlantiss/BugTracker#7814]
Earth shield has an infinite internal cooldown for as long as you are still taking damage with an active Earth Shield. Normally, you should be able to cast earth shield on any target and/or yourself as soon as the Shaman's global cooldown is ready. 

On Atlantiss, Earth Shield cannot be reapplied while already active, with any number of charges remaining. The only work arounds that I know of are to remain out of combat for a minimum of 6 seconds, to a maximum waiting period of forever. I have often had to even relog in order to be able to reapply an Earth Shield upon expiration. 

This is a devastating bug for the Resto spec, as you cannot refresh Earth Shield before anticipating damage that will be sustained longer than your current amount of stacks may last. I am begging the developers of Atlantiss to please repair Earth Shield to the state that it was in during Cataclysm live, from patch 4.0.1, all the way through 5.0 when MOP talents arrived.

It should behave in a manner that allows the buff to be constantly refreshed.

**Comment by Illusie** [comment]
https://github.com/Atlantiss/BugTracker/issues/7743#issuecomment-232199077

@Jenovas
