### ISSUE TITLE
[EN][Quest][Outland] Not On My Watch!

### ISSUE THREAD

**Issue by bugman543** [Atlantiss/BugTracker#7815]
http://www.wowhead.com/quest=9918/not-on-my-watch

What happens is Lump, the NPC required to get down to low health, spawn he immediately disappears. There is a ~1 second window in which he is vulnerable to attack before 'de-spawning'. He fades out like a enemy rogue does when he escapes combat, and simple to not have a hit box anymore. An AoE attack does not hit anything. Makes the quest incomplete-able. 

Bugged for a level 66 Female Draenei Death Knight

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/3674 dup, should be fixed soon :)

**Comment by BAndysc** [comment]
Fixed in rev 5093
