### ISSUE TITLE
[EN]Quest [Zen'kiki and the cultists] [Western plaguelands]

### ISSUE THREAD

**Issue by Casually1987** [Atlantiss/BugTracker#7817]
this quest is bugged. the plague bears arent in their cages so they cannot be rescued and healed by zenkiki. the bears are just standing around outside. there is no way to heal them either..

quest should look like 
http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

https://www.youtube.com/watch?v=FnZ9ceCvLsA

**Comment by Luna-maria** [comment]
#3954 #2763 #3269
