### ISSUE TITLE
[EN]Quest [combat training]horde side [Western plaguelands]

### ISSUE THREAD

**Issue by Casually1987** [Atlantiss/BugTracker#7818]
the valk doesnt come and there is no pet bar.
there are no forsaken either.
typing /call to arms doesnt work either.
the boss works fine but u cant complete the rest of the quest.
http://www.wowhead.com/quest=26938/combat-training#comments

it should look like https://www.youtube.com/watch?v=yrmBJVWX6PE

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/482
