### ISSUE TITLE
[EN][Quest][All]

### ISSUE THREAD

**Issue by valtteriha** [Atlantiss/BugTracker#7819]
I noticed that every time i complete a quest, the quest reward windows stays open and wont close. i tried without any addon's and i don't know how to fix this

**Comment by sunshitwowsucks** [comment]
skyfire EMU problem

**Comment by Aival94** [comment]
Is a general issue. Devs have not fixed it yet.I had made mount hyjal report for all the quests that has this bug but not sure if can help them.

**Comment by sunshitwowsucks** [comment]
https://github.com/sunshitwowsucks/AtlantissCore

somewhere in there, but i can not find questhandler.cpp...

https://github.com/sunshitwowsucks/AtlantissCore/blob/master/src/server/game/Entities/Player/Player.cpp

probably just add somewhere on quest completing method to close the menu

**Comment by BAndysc** [comment]
Fixed in 5097 :)
