### ISSUE TITLE
[EN][Quest][Borean Tundra] Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by BAndysc** [Atlantiss/BugTracker#782]
Quest item [D.E.H.T.A. Trap Smasher](http://www.wowhead.com/item=35228) can be spammed 8 times on single npc [Trapped Mammoth Calf](http://www.wowhead.com/npc=25850). Of course player should be able to use item only once on single npc.

Quest: [Help Those That Cannot Help Themselves](http://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves)

**Comment by Bildo** [comment]
Item has 15 sec cd for me so how can u spam it ?
