### ISSUE TITLE
[EN]Portal to Hijal doesn't open.

### ISSUE THREAD

**Issue by sashatje** [Atlantiss/BugTracker#7821]
Hi,

I've been doing a chain of quests to open the Hijal portal from Horde. 

The dragon in Moonglade wouldn't fly. I tried finishing it by getting to Hijal on my own, but the next NPC in the chain wouldn't have quests for me of course.

Any help would be appreciated.

**Comment by Piklo** [comment]
you have to do http://www.wowhead.com/quest=25578/return-to-nordrassil

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3646, https://github.com/Atlantiss/BugTracker/issues/963

**Comment by BAndysc** [comment]
Since rev 5099 portal to Hyjal will appear once you finishe quest As Hyjal Burns
