### ISSUE TITLE
Fire At Will, drastically bugged! [EN] or [PL]

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#7824]
http://cata.openwow.com/quest=10911
the quest Fire At Will is drastically bugged, when i'm ussing the naturalized ammunition at Fel cannon-
it becomes my minion- but, i can't even fire a shoot- if im attacking other mob, the cannon is attacking with me, i cant enter to the cannon... the quests is impossible to do. btw if i use naturalized ammunition at fel cannon, i'll get a combat bug -,-
Quest fire at Will jest totalnie zbugowany, jak uzywam znaturalizowana amunicje na fel cannon, zamienia sie w mojego miniona ale nie moge nic z niej wystrzelic, jak atakuje inne moby, to ona atakuje razem ze mna, nie moge do niej wejsc, quest jest niemozliwy do zrobienia... swoja droga jak uzyje natualized ammunition na fel cannon, dostaje combat bug -,-
https://cloud.githubusercontent.com/assets/20461805/16846878/78d7db72-49ee-11e6-96db-473a28babf30.jpg <--- screenshoot

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/2507
