### ISSUE TITLE
[EN][NPC] Tylos Dawnrunner

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7826]
NPC Tylos Dawnrunner (http://www.wowhead.com/npc=34914) is attackable and killable by Alliance players, which should not be the case for any of the NPCs in Sunreaver Pavillon.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11003-questnpc-next-fixs/
