### ISSUE TITLE
[EN][Gameobject] Discarded Soul Crystal

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#7836]
Objects called Discarded Soul Crystal (http://www.wowhead.com/object=195344) should be scattered around The Valley of Fallen Heroes, placed in circles of dark blue light, as seen on the wowhead screenshot or video provided below.
Currently the number and location of the crystals themselves is quite correct, but the blue light circles are in much different places and there's far fewer of them, like this:
http://i.imgur.com/zipUiWG.jpg

Video: https://www.youtube.com/watch?v=a9NMWtdHPxk

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12508-45787836questicecrown-the-fate-of-the-fallen/
