### ISSUE TITLE
[EN][Spell] Well Fed

### ISSUE THREAD

**Issue by Rhyvos** [Atlantiss/BugTracker#7841]
Low level characters can eat [Seafood Magnifique Feast](http://www.wowhead.com/item=62290/seafood-magnifique-feast) to get full buff coefficient from that food. Maybe it works with other "group foods".

Proof:
![nowy obraz mapy bitowej 2](https://cloud.githubusercontent.com/assets/9784730/16890015/204615ca-4aeb-11e6-8854-d27d76306c86.jpg)

**Comment by shaunb19** [comment]
worked this way on retail aswell. low level twinks getting a friend to put down a fish feast or some other group food to gain huge advantage in low level BGs
