### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] [Argent Call: The Trial of the Crypt

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7842]
[Argent Call: The Trial of the Crypt](https://www.youtube.com/watch?v=9eF5oGCVfx4)

the quest works but is not blizzlike

Here is a video of the retail
[https://www.youtube.com/watch?v=9eF5oGCVfx4](url)

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/499

**Comment by arndry** [comment]
thanks. it's weird cuz i look for the issue before posting but there it is :)

**Comment by Quban** [comment]
duplicate
