### ISSUE TITLE
[PL][Glyph][Paladin] Glyph of the Long Word

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#7843]
http://cata.openwow.com/spell=93466
Jak powinno to działać: Przypuśćmy że nasze word of glory bez tego glypha leczy za 30k. Z tym glyphem powinno leczyć połowę czyli w tym przypadku 15k instant, i drugie 15k w ciągu 6 sekund w 3 tickach (suma 3 ticków powinna wynosić w tym przypadku 15k). Jeżeli nasze word of glory będzie mieć crita przypuśćmy 60k, z tym glyphem powinniśmy otrzymać instant heala za 30k (czyli połowę) i powinniśmy zostać wyleczeni za drugie 30k w ciągu 6 sekund w 3 tickach (suma 3 ticków powinna wynosić 30k). Każdy tick ma również swoją szansę na crita czyli suma tych 3 ticków może być większa niż instant heal z word of glory. Mastery http://cata.openwow.com/spell=86273 powinno zostać nałożone tylko przez instant heala (czyli ticki nie nakładają shielda z mastery)

Jak działa to u nas: Healing z word of glory rzeczywiście zostaje zmniejszony o połowe, ale healing over time z glypha nie działa już dobrze, przypuśćmy że mamy word of glory za 15k (już zmniejszone oczywiście), suma healingu over time wynosi około 2-3k jest to zdecydowanie za mało bo powinno wynosić co najmniej 15k + szansa na crita na każdym ticku. Mastery działa dobrze, ticki nie nakładają shielda.

![wowscrnshot_071616_144350](https://cloud.githubusercontent.com/assets/16057987/16894865/d4a4594a-4b64-11e6-9429-a53aa32b5a82.jpg)

**Comment by Piklo** [comment]
Zapomniałem dopisać, każdy tick też powinien też triggerować healing na beacon of light http://cata.openwow.com/spell=53563 tak jak normalne word of glory to robi (nie over time)

**Comment by rwystop** [comment]
jakbys napisal po angielsku dostalbys odpowiedz szybciej, niestety polscy GM sie opierdalaja :)

**Comment by pelekon** [comment]
@rwystop Po pierwsze, GMi nie zajmują się bugami, od tego jesteśmy my devi. Po drugie język w jakim jest napisane zgłoszenie nie ma znaczenia bo wszyscy developerzy są polakami. Po trzecie class spellami zajmuje się u nas Jenova, więc naprawi to kiedy sprawdzi zgłoszenie i uzna, że przyszła na nie kolej(są rzeczy które mają większy priorytet do naprawy)

**Comment by Jenovas** [comment]
@rwystop - niestety nie wiesz o czym gadasz i Twój komentarz został usunięty.

Mam ważniejsze sprawy na głowie niż Glyph który nie działa poprawnie.
Czekać.

**Comment by lamaATS** [comment]
Fixed in rev. 5246
