### ISSUE TITLE
[PL][Quest][Dragonblight] Fresh Remounts

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#7844]
http://www.wowhead.com/quest=12214/fresh-remounts
Quest jest zbugowany, oczywiscie wszystko dziala poprawnie- mozesz zabic npc, ktory ma item quest, ale jesli kontrolujesz konia, on ma speed jakies 1%- wolniej niz zwykle chodzenie, i jesli ktos cie zaatakuje, po przejsciu paru yrd, kon sie teleportuje do atackera...
BARDZO DENERWUJĄCE!

**Comment by Piklo** [comment]
#9002 reported in english with issue_template
