### ISSUE TITLE
[EN][NPC] Frostmaul Giant/Preserver

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7848]
http://www.wowhead.com/npc=7428/frostmaul-giant#mining
http://www.wowhead.com/npc=7429/frostmaul-preserver#mining

low priority but both should be mine-able after death

**Comment by user1011** [comment]
What about this mob, can you mine him? http://www.wowhead.com/npc=50258/frostmaul-tumbler

**Comment by Luna-maria** [comment]
eh, I"ll go check. Didn't have to kill them for a quest, will get back to it in a few

**Comment by Luna-maria** [comment]
nope, can't mine them either

**Comment by user1011** [comment]
Posted a fix on the forums.
