### ISSUE TITLE
[EN][NPC][Borean Tundra] Leryssa

### ISSUE THREAD

**Issue by bugman543** [Atlantiss/BugTracker#7850]
Her text is 'Need TXT YTDB'

![wowscrnshot_071716_110400](https://cloud.githubusercontent.com/assets/20433395/16898693/82a358c6-4c0e-11e6-8262-2e96b380d6ca.jpg)

**Comment by user1011** [comment]
Missing: Link to the npc on WoWhead, and what the text should be.

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12248-7850npcborean-tundra-leryssa/
