### ISSUE TITLE
[EN][Quest][Icecrown] The Halls Of Refrection

### ISSUE THREAD

**Issue by maximancini** [Atlantiss/BugTracker#7856]
Quel'Delar doesn't have a body model, after defeating the sword you cant pick "subdued quel'dalar' item from the corpse normally, i found a workaround using the target command (/target Quel'Dalar) a then loot the corpse using a previously bonded interact key
wowhead link: http://www.wowhead.com/quest=24561/the-halls-of-reflection

**Comment by jissabraham** [comment]
its reported somewhere down the line link quest, even if u loot him u cant enter sunwell, anyone with engineering prof can loot him

**Comment by Kubelecer** [comment]
Also: with a DK you can pull the sword just as it dies to make sure it doesn't fall into the textures.

**Comment by reyuk** [comment]
not able to loot the sword..

**Comment by LaveniaGithub** [comment]
https://github.com/Atlantiss/BugTracker/issues/5418
