### ISSUE TITLE
[en][Shadowfang Keep][5n][NPC] Baron Ashbury

### ISSUE THREAD

**Issue by Birdseye123** [Atlantiss/BugTracker#7857]
When Baron Ashbury reaches roughly 20% health, around 2400 health, he casts http://www.wowhead.com/spell=93757 (Dark Archangel Form), and begins casting http://www.wowhead.com/spell=93812 (Calamity).
This is supposed to happen in heroic difficulty against this boss, instead of normal.

According to wowhead, the only three spells he should cast are the following:
- http://www.wowhead.com/spell=93423 (Asphyxiate)
- http://www.wowhead.com/spell=93423 (Pain and Suffering)
- http://www.wowhead.com/spell=93468 (Stay of Execution)

I've confirmed that this is a constant bug, because I've ran the dungeon several times, and failed almost every time on this first boss.

**Comment by Quban** [comment]
k ill fix it soon

**Comment by Aival94** [comment]
@Quban  is it possible to check [Lord Godfrey](http://www.wowhead.com/npc=46964/lord-godfrey) being pulled by pets when you enter the dungeon by using the teleportation of rdf or need to make second bugtracker report(is recent issue).

**Comment by Quban** [comment]
> @Quban  is it possible to check Lord Godfrey being pulled by pets when you enter the dungeon by using the teleportation of rdf or need to make second bugtracker report(is recent issue).

can you make another issue with description whats exactly wrong with Godfrey or pets?

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5105
