### ISSUE TITLE
[EN][Priest] Echo of Light 

### ISSUE THREAD

**Issue by LucaPr** [Atlantiss/BugTracker#7859]
Priest mastery (Echo of light) is not triggered by Divine Hymn and Guardian Spirit (the heal that it gives when you reach 0 hp), it's correctly triggered by all the other spells, such as:

Flash Heal
Heal
Greater Heal
Binding Heal
Circle of Healing
Prayer of Healing
HW: Serenity
HW: Sanctuary
Holy Nova
Renew

Personally tested.

source: http://wow.gamepedia.com/Mastery:_Echo_of_Light

**Comment by lamaATS** [comment]
Fixed in rev. 5205
