### ISSUE TITLE
[EN[Combat Talent][Rogue]Bandit´s Guide

### ISSUE THREAD

**Issue by hunzisak** [Atlantiss/BugTracker#7862]
Bandits Guide http://cata.openwow.com/spell=84654
 
Your Sinister Strike and Revealing Strike abilities have a 100% chance to grant you an evolving insight into an opponent's defenses, increasing damage to that target by up to 30%. Opponents can adapt over time, negating this benefit, and Striking a different opponent will begin the cycle anew.

issues on server: its 1% maybe here+spell stack on me nop on monster

**Comment by Jenovas** [comment]
It stacks on you maybe because it should???
https://www.youtube.com/watch?v=OBtyMlJNe8k

Closing issue.

**Comment by hunzisak** [comment]
and about chance will be repair or ?

**Comment by Jenovas** [comment]
First find out how the spell should work.
