### ISSUE TITLE
[EN][NPC] Evonice sootsmoker

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7863]
this NPC is not in the server. www.wowhead.com/npc=14628/

**Comment by Quban** [comment]
i ve checked and she is in 2 places same as on wowhead

**Comment by arndry** [comment]
can you give me the coords? need to check out

**Comment by Quban** [comment]
k my bad, she has invi quest aura, but only the one underground should have this aura so its a bug, ill fix it soon, easy fix ;)

**Comment by Quban** [comment]
fixed http://atlantiss.eu/changelog#rev5114

**Comment by arndry** [comment]
> fixed http://atlantiss.eu/changelog#rev5114

Thank u m8! 
I was out for a few days so thanks for reply and fixing too
