### ISSUE TITLE
[en][Npc][Vendor][Orgrimmar][First Sergeant Hola'Mahi]

### ISSUE THREAD

**Issue by Birdseye123** [Atlantiss/BugTracker#7864]
# This npc doesn't sell the following items:
http://www.wowhead.com/item=18849 Insignia of the Horde(Rogue)
http://www.wowhead.com/item=18853 Insignia of the Horde(Druid)
http://www.wowhead.com/item=18852 Insignia of the Horde(Warlock)
http://www.wowhead.com/item=18851 Insignia of the Horde(Priest)
http://www.wowhead.com/item=18850 Insignia of the Horde(Mage)
http://www.wowhead.com/item=29592 Insignia of the Horde(Paladin)
http://www.wowhead.com/item=18846 Insignia of the Horde(Hunter)
http://www.wowhead.com/item=18845 Insignia of the Horde(Shaman)
http://www.wowhead.com/item=18834 Insignia of the Horde(Warrior)

[**In order to prove this is a blizzlike fix, here's a link to the wowhead page cached from August 18, 2012.**                                                Wayback Machine Internet Archive]       (https://web.archive.org/web/20120818163734/http://www.wowhead.com/npc=12795/first-sergeant-holamahi#sells:400-2)

[This is what she currently sells on Atlantiss](http://imgur.com/a/KfeGr)

**Comment by TranceAccount** [comment]
You've already reported this before #4238
