### ISSUE TITLE
[EN][Item] Cub's First Toy

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#7866]
~~**What is bugged:** The item [Cub's First Toy](http://www.wowhead.com/item=69986/cubs-first-toy) (ID = 69986) shows "0" in the tooltip.~~

![image](https://cloud.githubusercontent.com/assets/13118481/16964678/012b2e4a-4dfd-11e6-8241-f24e6de056e8.png)

[Actual screenshot](http://imgur.com/a/1LgXI)

Update: It is also missing it's text when read.

[Screenshot](http://imgur.com/0SfWYxn)

 **How it should be:**
- [x] The item shouldn't show "0" in the tooltip.
- [x] It is also missing it's text when read.

**Comment by user1011** [comment]
Posted a fix on the forums.

**Comment by user1011** [comment]
Update: It is also missing it's text when read.

[Screenshot](http://imgur.com/0SfWYxn)

**Comment by TranceAccount** [comment]
Posted a fix on the forums for the missing page_text.

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
