### ISSUE TITLE
[ENG] [Quest/NPC] [Silverpine Forest] Cornered and Crushed

### ISSUE THREAD

**Issue by Enddi** [Atlantiss/BugTracker#7869]
This Quest is bugged http://www.wowhead.com/quest=27194/cornered-and-crushed . 
I can't talk with Master Forteski. He is not on Quaestion mark on map but he is in mine. Next to him stay 8 or 10 the same NPC. This quest block story line so i can't leave this location with out ending it.
This is video how this quest sholud work: https://www.youtube.com/watch?v=lkKAM-egxTg

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5106 fixed
