### ISSUE TITLE
[EN][Quest][Deepholm] One with the ground

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#787]
http://www.wowhead.com/quest=27934
Found an issue with this quest, after you take the quest from the NPC, and talk with it to start, you travel automatically underground to a cave, next to a mob called Avalanchion. Once you arrive there, the quest should say objective complete, get you out of the ground and the NPC should spawn (or a popup should come up) to give a new quest to kill the before mentioned mob. 
The bug I've encountered is that once you arrive at the cave, the objective doesn't update as complete and no follow up quest pop up to kill the mob, thus breaking the whole chain from there on.

**Comment by Aival94** [comment]
I did it yesterday and all was working fine about completion and give of new quest but i found an other issue related to this quest.After completing quest [Bring Down the Avalanche](http://www.wowhead.com/quest=27935/bring-down-the-avalanche) if you speak again with NPC [Slate Quicksand <Arch Geomancer>](http://www.wowhead.com/npc=47195/slate-quicksand) it give you quest automatically(accepted automatically) again(but atleast you cannot do it as it stop on a blank "continue" window after traveling again and try to complete it).

**Comment by PVPViddys** [comment]
Ran into this problem today, this breaks a very long quest chain and now I'm stuck grinding.

**Comment by Thefakemccoy** [comment]
So doing this today it looks like it is missing some data. This is a picture of how you should turn it in but all the info is missing.
![wowscrnshot_102815_005027](https://cloud.githubusercontent.com/assets/12252441/10779945/0aa26bb6-7d0e-11e5-80f6-8805636569df.jpg)

Here is the video 
https://www.youtube.com/watch?v=-NssM_4_3Qo

**Comment by Zeracri** [comment]
Hey, I had the same problem like guy above me. Talked to GM he said that quest is working properly but if you completed it already and forgot about it, NPC is bugged for some reason and allows you to retake quest but not complete it again for obvious reasons. 

Get Addon called "Quest Completist" it takes quest cache from server and  shows you what quests you have finished. If it's your first time doing the quest and you're getting same bug I'm sorry not sure what to do, contact gm or something. Hope this helps someone, peace. :)

**Comment by Bildo** [comment]
fixed
