### ISSUE TITLE
[EN][Spell][Rogue] Poisons

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#7870]
rogues poisons should have a chance to hit the enemy when the rogue casts certain abilities that deal no damage but debuff the enemy, this doesnt work on atlantiss. basically anything that swings at your enemy should have a chance of proccing the poisons from your mainhand (very important only your mainhand poisons can proc)

rupture http://cata.openwow.com/spell=14903
garrote http://cata.openwow.com/spell=703
expose armor http://cata.openwow.com/spell=8647
kidney shot http://cata.openwow.com/spell=408
cheap shot http://cata.openwow.com/spell=1833
kick http://cata.openwow.com/spell=1766 (kick works on atlantiss)

excluded from this rule are gouge and sap they never apply poisons

poisons:
wound http://cata.openwow.com/item=10918
mind-numbing http://cata.openwow.com/item=5237
crippling http://cata.openwow.com/item=3775
deadly http://cata.openwow.com/item=2892
instant http://cata.openwow.com/item=6947

proof:
https://www.youtube.com/watch?v=u03Brc1C564 (0:43 white swings are immuned by iceblock, kidney hits -> mind numbing is intantly also on the mage // 2:35 kidney shot hits mage, mind numbing double procs as u can see on his debuff frame, which means kidney as well as a white swing applied mind numbing)

http://www.warcraftmovies.com/movieview.php?id=160679 (3:25 this is an old lvl 80 movie but thats how it works to this day on retail, it was never changed)

http://www.warcraftmovies.com/movieview.php?id=207657 (4:02 focus kicks the priest, applies wound poison without even hitting him with anything else)

**Comment by lamaATS** [comment]
Fixed in rev. 5210
