### ISSUE TITLE
[PL] Warlock pets

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/BugTracker#7871]
Kiedy naprawicie kombat oraz punkty zycia po resummonie peta oraz jego komendy
1 bug - kombat pet laczy kombat z jego wlascicielem a nie powinien
2 po resummonie pet ma dalej 10k hp lub umiera z dotami
3 po uzyciu invi na komendzie stania w miejscu pet podchodzi do wlasciciela, przeciez ma stac w miejscu
4 na bg jesli pet jest agrssive, a ktos nas ubije, to po ressnieciu pet leci za ta postacia ktora bil
5 gdy wchodzimy na bg a przyzwiemy sobie impa(przed wejsciem na bg mielismy felhuntera), to po starcie bg mount/dismount znowy wychodzi felhunter, przeciez przyzwalismy impa....
6 czasami pet nie reaguje na zadne komendy, stoi w miejscu, nie podchodzi do targetu, nie daje seduction, chodzi o suke ale tez i o inne pety, typu spell lock u felhuntera itd
7 imiona petow powinny byc stale, dla kazdego locka powinno byc zajete imie peta, a teraz summujemy to kazdy pet ma inne imie, moze przez to sa te bugi z resummonami itd
8 whiplash u suki nie dziala na bance palladyna a powinien oraz nie dziala na targety w fear. Powinien dzialac na wszystkie targety, po za magiem w ib....

**Comment by damian475** [comment]
Powiem ze trzeba się temu przyjrzeć dokładnie bo tak jak kolega opisuje jest to baaardzo uciążliwe!

**Comment by m1athew** [comment]
Kolejny bug jeżeli chodzi o pety, to jeżeli pet zabije moba/npc bez twojej pomocy (jeżeli nie zadasz żadnych obrażeń) to nie możesz podnieść lootu. jest to bardzo uciążliwe podczas farmienia jakichś reagentów, clothów albo greenów z mobow na cata, ogolnie na low levelach jeszcze bardziej wkurza bo mój felguard wpada robi lolstroma i nic nie moge podnieść...

**Comment by Jenovas** [comment]
1 zgloszenie = 1 bug. Niektóre zgłoszone bugi zostały naprawione.
Zamykam.
