### ISSUE TITLE
[EN][Quest][Swamp of Sorrow] Maliciously Delicious

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7872]
[Maliciously Delicious](http://www.wowhead.com/quest=27587/maliciously-delicious) is missing. this has to be the first mission in this zone but it's not. this mission is given by [Trade Baron Silversnap](http://www.wowhead.com/npc=45786/trade-baron-silversnap)

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5118
