### ISSUE TITLE
[PL][Racial][Talent] Field Dressing a Gift of the Naaru.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7873]
Talent Field Dressing(http://wowwiki.wikia.com/wiki/Field_Dressing) nie zwiększa leczenia z Gift of the Naaru(http://wowwiki.wikia.com/wiki/Gift_of_the_Naaru) o 20% jako nasz Self Heal.

**Comment by mati865** [comment]
Powinno zwiększać o 6% jako że to jest heal a nie self-heal
http://www.wowhead.com/forums&topic=184187/field-dressing-what-it-affects-what-it-doesnt#p2561589

**Comment by Jenovas** [comment]
Proszę sprawdzić zgłoszenia zanim je zgłaszacie...
Wszystkie zgłoszenia bez dowodów będą zamykane nawet jeżeli macie racje.
