### ISSUE TITLE
[EN][QUEST][IceTombs] Entombed in Ice

### ISSUE THREAD

**Issue by XavoMS** [Atlantiss/BugTracker#7874]
Is not a new issue i am bringing today sense i already saw posts like this, but i think is a bug that comes and goes because a few weeks ago i did it with no problem. This quest cannot be done because the drawf are already free, Same thing happen with one of the started quest of the gnomes where the gnomes to be free have their cages already open. Side note: This quest is important to continue to the next ones and to the next area :)

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/7300, https://github.com/Atlantiss/BugTracker/issues/4841
