### ISSUE TITLE
[EN][NPC][Blackrock Caverns] Rom'ogg Bonecrusher (ID = 39665)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7878]
Boss got bugged again and the ability [Chains of Woe](http://www.wowhead.com/spell=75441/chains-of-woe) is not working.
He normally cast the ability and he teleport the players but the chain do not "root" the players till they kill the chain.
Furthermore the chains has not model right now for some reason(you can see the health and dps the chain but there is no model).

Wowhead Link: [Rom'ogg Bonecrusher](http://www.wowhead.com/npc=39665/romogg-bonecrusher)

**Comment by zano354** [comment]
Bump

**Comment by sunshitwowsucks** [comment]
yeah easy to do now

**Comment by Kenosz** [comment]
bump

**Comment by user1011** [comment]
Confirmed.

**Comment by xmesaj2** [comment]
rev. 5629 fixed
