### ISSUE TITLE
[PL][Quest][Searing Gorge] Operation: Stir the Cauldron

### ISSUE THREAD

**Issue by TheManGGo** [Atlantiss/BugTracker#7883]
## http://www.wowhead.com/quest=28052/operation-stir-the-cauldron
Problem polega na tym, że jak docieram na miejsce latającą maszyną to po kilku sekundach spadam z maszyny. Próbowałem kilka razy, lecz za każdym razem z takim samym skutkiem.

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5118
