### ISSUE TITLE
[EN][QUEST][Uldum] under the choking sands

### ISSUE THREAD

**Issue by kattming77** [Atlantiss/BugTracker#7884]
currently with the quest it says to just click the targets, nothing happens when i attempt to do that action.the targets do nothing

**Comment by user1011** [comment]
Missing: WoWhead link to the NPC and the quest.

**Comment by BAndysc** [comment]
Fixed in rev 5117

**Comment by ko4o** [comment]
Still doesn't work, they don't give credit.

**Comment by BAndysc** [comment]
Because rev 5117 is not yet live on the server
