### ISSUE TITLE
[EN][Quest][Deepholm] Reactivate the Construct

### ISSUE THREAD

**Issue by zano354** [Atlantiss/BugTracker#7885]
The NPC that should been the target click to as the main objective of the quest, can't be clicked.
Instead they are fighting the mobs near it, even though the mobs are dead, they still cant be clicked.

Name of the npc: Deactivated War Construct

**Comment by zano354** [comment]
The NPC that should been the target click to as the main objective of the quest, can't be clicked.
Instead they are fighting the mobs near it, even though the mobs are dead, they still cant be clicked.

Name of the npc: Deactivated War Construct

**Comment by user1011** [comment]
Missing: WoWhead links to the NPC and the quest.

**Comment by Supremacja** [comment]
[http://www.wowhead.com/quest=26762/reactivate-the-constructs](url) Quest link
[http://www.wowhead.com/npc=43984/deactivated-war-construct](url) Bugged NPC
It was working about week ago, now player is unable to make any actions with NPC.

I can add that from what i know this quest is needed to proceed to therazane chain.

**Comment by Ardenus** [comment]
Yes, quest sill not working.

**Comment by BAndysc** [comment]
Fixed in rev 5117

**Comment by Ardenus** [comment]
Test it, and still not working as it should

**Comment by BAndysc** [comment]
@Ardenus, I write revision number it is fixed in so that you can check current revision with command `.server info` or on the website http://atlantiss.eu/changelog whether the revision is live on the server.

And 5117 is not yet.
