### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Rumble in the Lumber... Mill

### ISSUE THREAD

**Issue by Alinna99** [Atlantiss/BugTracker#7889]
The cage for Huntress Illiona is wide open and cannot be unlocked, thus the quest is cannot be completed.

This is how it supposed to work: https://www.youtube.com/watch?v=YmPSpNlFYvY

http://www.wowhead.com/quest=25669/rumble-in-the-lumber-mill

Please fix this!
Thanks!

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1724
