### ISSUE TITLE
[EN][Item] Chromatic Sword

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#7890]
This sword is the rarest sword in the game, so much that people were sending tickets to GM to see if it was still in-game. [Chromatic Sword](http://www.wowhead.com/item=1604)

But I've seen 12 in the last couple days. This sword is suppose to be a below 0.5% drop from a rare [Scale Belly](http://www.wowhead.com/npc=1552) with a respawn timer of 3-8 hours. I've also killed him twice with both kills dropping the sword. That is statistically speaking incredibility rare.

From wowhead comments patch 4.2.2

> "Im suprised no one has posted this but:
> 
> Scale Belly is the only mob in the game that drops the "Chromatic Sword" a level 40 UNIQUE sword that is referred to as the "Rainbow Sword" because of its unique Enchant to have the colors of the rainbow. Bear in mind it has a 1.1% Drop Rate so you maybe out there a few tries in order to get one to drop despite it is completely useless but with the 4.3 Transmorgifyer you will be able to wield the "Rainbow Sword" once more. GL and happy hunting :)"

Reply to that is:

> As more kills have come in, drop rate has gone farther down, its currently at 0.6% drop rate. 

And the drop chance was not increased in 4.3.4. There were only 6 worldwide on the AH during retail cata 4.3.4.

**Comment by NatsumeLily** [comment]
Killed him again as of today..Sword dropped again.

Yea...This isn't a 0.5% drop chance...

**Comment by Piklo** [comment]
posted fix on forum
