### ISSUE TITLE
[EN][Quest][Blasted Lands] Curtail the Darktail

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7891]
http://www.wowhead.com/quest=25709/curtail-the-darktail

the target [mob ](http://www.wowhead.com/npc=42235/darktail-bonepicker)it's still placed too far away and they are very dispersed around the area.

the mobs need to be 30 yards away from the ground to be able to  attack them

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4415
