### ISSUE TITLE
[PL][Warrior] Absorb - Enrage nie ma szansy na proca na Absorbie z Auto Attaków.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7893]
Enrage Talent: http://cata.openwow.com/spell=13046

Jak jest: Enrage nie ma szansy na proca z Auto Attacku gdy bijemy w kogoś kto ma Absorb na sobie.
Jak powinno być: Absorb nie powinien wpływać na Proc Enrage.

Dowodem może być to że na Retailu Absorb nie ma wpływu na Proc Enrage i na Cata też nie miał.
Aktualnie w PvP jest to dość uciążliwe, wcześniej to działało i Enrage normalnie procował na Absorbie z Auto Attacku, przynajmniej teraz to zobaczyłem i przetestowałem bijąc Disco Prista.

**Comment by TranceAccount** [comment]
Your title is wrong.
> On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player.

**Comment by BialyADI** [comment]
Bump

**Comment by kadi2** [comment]
On ratail you had many spells and talents that didn't proc on absorbs. Your proof is pointless.

**Comment by BialyADI** [comment]
Właśnie nie ;p.
Bug jest ten sam co u Enha był że AA na Absorbie nie nabijały Malestormu a tu nie daje Enrage u Warka, a powinien dawać tak jak jest to na Retailu.

**Comment by lamaATS** [comment]
Fixed in rev. 5208
