### ISSUE TITLE
[EN][Quest][Dalaran] Friends in Dalaran 

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7894]
http://www.wowhead.com/quest=29609/friends-in-dalaran
What is bugged: This quest is missing from the starting NPC, http://www.wowhead.com/npc=25288/turida-coldwind.

Note: This quest was added in patch 4.3.0

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5118
