### ISSUE TITLE
[EN][Quest][Borean Tundra] Cleaning Up the Pools

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7895]
http://www.wowhead.com/quest=11906/cleaning-up-the-pools
How it should work: This quest should become available after completing the prerequisite, http://www.wowhead.com/quest=11895/master-the-storm ( read the wowhead comments for http://www.wowhead.com/quest=11895/master-the-storm).
What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10931-quest-cleaning-up-the-pools/

**Comment by aje** [comment]
fixed in revision 5115
