### ISSUE TITLE
[EN][Quest][Borean Tundra] Souls of the Decursed

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7896]
http://www.wowhead.com/quest=11899/souls-of-the-decursed

How it should work: This quest should become available after completing the prerequisite, http://www.wowhead.com/quest=11895/master-the-storm ( read the wowhead comments for http://www.wowhead.com/quest=11895/master-the-storm).

What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10930-quest-souls-of-the-decursed/

**Comment by aje** [comment]
fixed in revision 5115
