### ISSUE TITLE
[EN][Spell][Druid] Skull Bash

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#7897]
skull bash kicking in roots bugs again

druid should not be able to kick the full 13 yard range in root, they can only kick in melee range when rooted

http://cata.openwow.com/spell=80965 skull bash catform
http://cata.openwow.com/spell=80964 skull bash bearform

proof:
http://us.battle.net/wow/en/forum/topic/3392890444
"you used to not be able to (wouldn't even be able to use ability - you'd get "cannot do that while now" error text), but they fixed that. melee range is 5yrds, from the center of the kitty model. you should be able to skull bash to that distance while rooted."

**Comment by TranceAccount** [comment]
Please provide a WoWhead link to the spell.

**Comment by fluessig** [comment]
openwow link works too right?

**Comment by Malylolek** [comment]
Sure Sure

**Comment by lamaATS** [comment]
Fixed in rev. 5245
