### ISSUE TITLE
[EN][Talent][Mage] Pyromaniac

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#7898]
Hey what's up.
Pyromaniac proc on one target. // bugged again ;'(

http://cata.openwow.com/spell=83582
https://github.com/Atlantiss/BugTracker/issues/3151

**Comment by Malylolek** [comment]
#7333

**Comment by Illusie** [comment]
Hello
the pyromaniac buff via Stormwind Dungeon still exist.
It's really unfair that Mages abuse this bug and get 10% haste bonus at single-target. 

Mages with 15% haste have now 25% haste.
unfair.

https://github.com/Atlantiss/BugTracker/issues/7333
