### ISSUE TITLE
[EN][Quest][Deepholm] Without a captain or crew

### ISSUE THREAD

**Issue by Aruzam** [Atlantiss/BugTracker#790]
http://www.wowhead.com/quest=26427/without-a-captain-or-crew
As the quest suggest you're supposed to grab a spool of rope and a bottle of whiskey, problem is they're missing completely from the ship. I know where they are supposed to be since I did this quest before on several toons while server was 4.0.6. and it worked fine. Now they are missing completely and quest can't be completed.

**Comment by Satyr87** [comment]
also that ship sometimes teleports you 1km above the roof of deepholm

**Comment by Duros** [comment]
Can this get a auto complete like the other quests on the gunship as temporary fix?

**Comment by Aruzam** [comment]
It's not really an important quest, it doesn't have any follow up. It's still possible to get the achievement in Deepholm doing quests without it no problem. It also doesn't break any chain quest-line. Just skip it for now ^^

**Comment by Exorcista** [comment]
Sadly @Aruzam it seems that in the server it is blocking the following quest: http://www.wowhead.com/quest=26250/on-second-thought-take-one-prisoner, leading to unlock a long chain seen in this wowhead comment http://www.wowhead.com/quest=26861/block-the-gates#comments:id=1627868, leading in the end to unlock: http://www.wowhead.com/quest=26326/the-very-earth-beneath-our-feet, the important quest needed to Therazane chain to start.

**Comment by Maczuga** [comment]
Bump

**Comment by Tj20** [comment]
[Rev. 4458](http://atlantiss.eu/changelog#rev4458) says: 
> Fixed SMSG_UPDATE_OBJECT packet structure for gameobjects on transports, they will now be visible (this fixes quest Without a Captain or Crew in Deepholm)

so this issue may have been fixed? (but see also Thefakemccoy's new bug report about this quest with different issues)
