### ISSUE TITLE
[EN][Quest][Dragonblight] To Dragon's fall

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7903]
http://www.wowhead.com/quest=12095/to-dragons-fall

How it should work: This quest should become available only after completing the prerequisite quests, http://www.wowhead.com/quest=12091/wanted-dreadtalon, http://www.wowhead.com/quest=12090/wanted-gigantaur and http://www.wowhead.com/quest=12089/wanted-magister-keldonus

What is bugged: This quest is available without completing the prerequisites.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10935-quest-to-dragons-fall/

**Comment by aje** [comment]
fixed in revision 5115
