### ISSUE TITLE
[EN][Quest][Western Plagueland] Combat Training

### ISSUE THREAD

**Issue by Herodill** [Atlantiss/BugTracker#7905]
I can't challenge him to combat. The group of settlers they do not appear there.

http://www.wowhead.com/npc=45212/gory#objective-of

http://www.wowhead.com/quest=27174/combat-training

**Comment by TheCopacabanaMan** [comment]
+1 bump. But there were already some other issues open with the same title. 
Just do a simple search.
There was no need to open another.

**Comment by TranceAccount** [comment]
#7765

**Comment by xmesaj2** [comment]
fixed in rev. 5389
