### ISSUE TITLE
[EN][Quest][Dragonblight] Imbeciles Abound

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7907]
http://www.wowhead.com/quest=12189/imbeciles-abound

How it should work: This quest and http://www.wowhead.com/quest=12182/to-venomspite should be mutually exclusive (also see the commments for http://www.wowhead.com/quest=12182/to-venomspite abou being mutually exclusive with http://www.wowhead.com/quest=12189/imbeciles-abound). If you take one of them,the other should not be available to be taken.

What is bugged: Both quests are available at the same time.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
