### ISSUE TITLE
[EN][Quest][Howling Fjord] To Venomspite!

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7908]
http://www.wowhead.com/quest=12182/to-venomspite

How it should work: This quest should be mutually exclusive with http://www.wowhead.com/quest=12189/imbeciles-abound.

What is bugged: The two quests are available to be taken at the same time.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
