### ISSUE TITLE
[EN][Quest][Dragonblight] Containing the rot

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7909]
http://www.wowhead.com/quest=12100/containing-the-rot

How it should work: This quest should become available only after completing http://www.wowhead.com/quest=12034/victory-nears.

What is bugged: The quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
