### ISSUE TITLE
[EN][Quest][Dragonblight] Strenghthen the Ancients

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7910]
http://www.wowhead.com/quest=12096/strengthen-the-ancients#comments

How it should work: This quest should become available once you pick up http://www.wowhead.com/quest=12084/atop-the-woodlands.

What is bugged: The quest is available regardless of prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
