### ISSUE TITLE
[EN][Quest][Dragonblight] The Flesh-Bound Tome

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7911]
http://www.wowhead.com/quest=12057/the-flesh-bound-tome

What is bugged: The quest item starting this quest, http://www.wowhead.com/item=36744/flesh-bound-tome should not drop unless you have completed http://www.wowhead.com/quest=12056/marked-for-death-high-cultist-zangus. 

What is bugged: The quest item drops without having completed the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10954-quest-the-flesh-bound-tome/

**Comment by aje** [comment]
fixed in revision 5115
