### ISSUE TITLE
[EN][Quest][Dragonblight] Message from the West

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7912]
http://www.wowhead.com/quest=12033/message-from-the-west

How it should work:This quest should become available only after turning in the quest http://www.wowhead.com/quest=11916/hellscreams-champion.

What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
