### ISSUE TITLE
[EN][Quest][Dragonblight] Strength of Icemist

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7913]
http://www.wowhead.com/quest=12063/strength-of-icemist

How it should work: It should become available after completing http://www.wowhead.com/quest=12036/from-the-depths-of-azjol-nerub.

What is bugged: It is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
