### ISSUE TITLE
[EN][Quest][Dragonblight] Black Blood of Yogg-Saron

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7914]
http://www.wowhead.com/quest=12039/black-blood-of-yogg-saron

How it should work: This quest should become available after completing the prerequisite, http://www.wowhead.com/quest=12034/victory-nears.

What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10952-quest-continued/

**Comment by aje** [comment]
fixed in revision 5115
