### ISSUE TITLE
[EN][Quest][Dragonblight] A strange device (quest ID 12059, horde version)

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7917]
http://www.wowhead.com/quest=12059/a-strange-device#comments

How it should work:The quest item starting this quest (http://www.wowhead.com/item=36746/goramoshs-strange-device) should drop only after completing the prerequiste, http://www.wowhead.com/quest=11999/rifle-the-bodies.

What is bugged: The starting quest item drops without completing the prerequisite.

Note: This is the horde version of the quest, most probably the Alliance version (http://www.wowhead.com/quest=12055/a-strange-device) is bugged as well.

**Comment by Malylolek** [comment]
I cant find prove of it, if you can paste it here.

**Comment by Aldurion** [comment]
I believe the comments from here should be enough:
http://www.wowhead.com/quest=12059/a-strange-device#comments

**Comment by Malylolek** [comment]
Blind me xD, ok will put fix in near future.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10963-quest-a-strange-device-shakedown-at-the-saldeans/

**Comment by aje** [comment]
fixed in revision 5115
