### ISSUE TITLE
[EN][Quest][Dragonblight] Defiling the Defilers

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7921]
http://www.wowhead.com/quest=12265/defiling-the-defilers

How it should work: This quest is part of a quest chain and should be available after completing http://www.wowhead.com/quest=12263/the-best-of-intentions.

What is bugged: It is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10959-quest-defiling-the-defilers-culling-the-damned-no-one-to-save-you/

**Comment by aje** [comment]
fixed in revision 5115
