### ISSUE TITLE
[EN][Quest][Dragonblight] Culling the Damned

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7922]
http://www.wowhead.com/quest=12264/culling-the-damned

How it should work: This quest should become available after completing http://www.wowhead.com/quest=12263/the-best-of-intentions.

What is bugged: This quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10959-quest-defiling-the-defilers-culling-the-damned-no-one-to-save-you/

**Comment by aje** [comment]
fixed in revision 5115
