### ISSUE TITLE
[EN][Quest][Dragonblight] No One to Save You

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#7923]
http://www.wowhead.com/quest=12262/no-one-to-save-you

How it should work: This quest is part of a quest chain and should be available after completing http://www.wowhead.com/quest=12447/the-obsidian-dragonshrine.

What is bugged: The quest is available without completing the prerequisite.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10959-quest-defiling-the-defilers-culling-the-damned-no-one-to-save-you/

**Comment by aje** [comment]
fixed in revision 5115
