### ISSUE TITLE
[EN][QUEST][Stonetalon Mountains] In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by MementoHymen** [Atlantiss/BugTracker#7924]
Destroy 15 Gnomish Flying Machines or Bombers and 25 Gnome Wing Commanders.

"There's no time left. Here they come! Take control of a heavy gun and shoot the gnomes out of the sky! If that bomb takes too many hits it will blow, taking us all with it!

Defend the base, <name>! You're our only hope!

If we somehow make it out of this in one piece, report to Overlord Krom'gar."

REWARD: 
	Krom'gar Legionnaire, which allows for really good early game gear including early helms and pauldrons.

ISSUE: The implied "heavy gun" doesn't seem to appear aswell as the flying machines.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/4869 multithread for stonetalon is here also you didnt post wowhead links

**Comment by groumulous** [comment]
Still not working. Guns and targets do not exist.
