### ISSUE TITLE
[EN][NPC][RAID] Beth'Tilac

### ISSUE THREAD

**Issue by sunshitwowsucks** [Atlantiss/BugTracker#7925]
Beth will continue spilling out fire and you can't taunt the beth, which causes a wipe

and this will also cause an enounter is in progress issue

update:

testing beth out seems that if you change difficulty to 25 man and back to 10 man Beth disappears forever?

**Comment by Quban** [comment]
> if you change difficulty to 25 man and back to 10 man Beth disappears forever?

its known bug, its not boss bug, its for all maps, if you change difficulty if boss havent respawn yet than it will not respawn

**Comment by sunshitwowsucks** [comment]
the changelog does not list that fix

**Comment by Quban** [comment]
hmm, can you tell me if it was on 10 man or 25 man? maybe there is bug

**Comment by sunshitwowsucks** [comment]
i tested 10 man with my bdk then went on 25 man to test it again but beth disappered and i checked 10 man beth still gone, and i went on this mroning and beth is there again in same raid group

**Comment by Quban** [comment]
k i think i ve found this bug, let me know after next server update if it disappeared

**Comment by sunshitwowsucks** [comment]
beth came back after like 1 hr again xD

**Comment by sunshitwowsucks** [comment]
but server didnt restart yet

**Comment by Aival94** [comment]
Beth still do not move when someone have the most aggron on her(just face this one) so phase one she use her aoe all the time.

Drone now hit only the target in front of them as far as i saw.

Done on rev. 5123

Btw quban are these fixed already(do not understand polish): https://github.com/Atlantiss/BugTracker/issues/7370

**Comment by sunshitwowsucks** [comment]
beth cant be taunt still up ^ was in his raid and confirm

**Comment by Quban** [comment]
fixed in http://atlantiss.eu/changelog#rev5128
