### ISSUE TITLE
[EN][Quest][Searing Gorge] Operation: Stir the Cauldron

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7926]
when you reach the spot via helicopter. the vehicle eject you on free fall. you can shot before falling but despite doing the process three times and clearing the entrance of the cauldron, the mission is not completed

**Comment by Sayris9876** [comment]
Confirm. Tried it few times yesterday and today and cant make it work at all
Link of the quest: http://www.wowhead.com/quest=28052/operation-stir-the-cauldron

**Comment by Aival94** [comment]
Reported/Related here: https://github.com/Atlantiss/BugTracker/issues/7883

**Comment by Quban** [comment]
> Reported/Related here: #7883

thx

**Comment by Quban** [comment]
http://atlantiss.eu/changelog#rev5118
