### ISSUE TITLE
[EN] [LOOT] [INSTANCE]

### ISSUE THREAD

**Issue by FirenExee** [Atlantiss/BugTracker#7927]
Bug in old stratholme. When Malganis (last boss) die arthas should give a loot in chest but chest didnt work. Pls it is small bug but from this boss players can take awesome items for transmogs.

**Comment by user1011** [comment]
Please learn your small bugs. :P

**Comment by Quban** [comment]
https://github.com/Atlantiss/BugTracker/issues/5052
