### ISSUE TITLE
[EN][Quests][Storm Peaks]The Warm-Up

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7931]
http://www.wowhead.com/quest=12996/the-warm-up

I realize there's been posts about this before but they've all been closed and I"ve run into an issue.
The Yeti, http://www.wowhead.com/npc=29352/kirgaraak won't respawn. I assume he will once the server restarts/crashes but he should respawn much faster than that :p (like 10 minutes according to wowhead comments)

**Comment by Aequitass** [comment]
I had one of the ppl from Staff come and spawn it for me. I didn't ask or anything, he just came. I was previously spamming on global if it works. Making a ticket might help you out.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/10992-quest-the-warm-up/
