### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] The Dark Missive

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7938]
[this quest](http://www.wowhead.com/quest=10395/the-dark-missive) can't be started. the item [Burning Legion Missive](http://www.wowhead.com/item=29589/burning-legion-missive) Is missing...
Is a looted item from [Warbringer Arix'Amal](http://www.wowhead.com/npc=19298/warbringer-arixamal)

EDIT: after 7kills the item drops. close this

**Comment by Luna-maria** [comment]
no, dont' close, should be a 100% droprate

**Comment by Malylolek** [comment]
Next time, if you add wowhead links. Be sure items is correct, item what drop to take this quest is http://www.wowhead.com/item=29588/burning-legion-missive and drop rate should be around 42% and it was actual like at ATS.

**Comment by Luna-maria** [comment]
Eeh I'vw never not gotten it to drop the first time on retail. Maybe i was just super lucky then. Seems wrong though for a quest starter which  is part of a chain to not be 100%

**Comment by Luna-maria** [comment]
http://us.battle.net/wow/en/item/29590 it's actually a garantueed drop

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12118-7938-the-dark-missive-drop-chance/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
