### ISSUE TITLE
[PL][Death Knight] Frost Strike nie może być Blokowany przez tarcze.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#7940]
Jak jest:
Frost Strike nie da się zablokować(Block) tarczą.
Można go tylko Sparować lub uniknąć.

Jak powinno być:
http://wow.gamepedia.com/Frost_Strike
"This ability can now be dodged, parried, or blocked."

**Comment by TranceAccount** [comment]
Your title is wrong.
> On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player.

**Comment by BialyADI** [comment]
Bump.

**Comment by TranceAccount** [comment]
Fix your title.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14090-7940-frost-strike/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
