### ISSUE TITLE
[EN][Quest][Howling Fjord] Burn Skorn, Burn!

### ISSUE THREAD

**Issue by poilmok** [Atlantiss/BugTracker#7941]
Hello,

I can't finish my quest because I lost my NPC "Winterhoof Brave" and the other NPC (Chieftain Ashtotem) doesn't want to give me Winterhoof Emblem in order to call Winterhoof Brave.

Thank you for your help

**Comment by Aldurion** [comment]
Have you tried to abbandon and retake the quest?

**Comment by poilmok** [comment]
I can't retake the quest because the NPC appears that when he is called by "Winterhoof Emblem". He is not on the map !

**Comment by Aival94** [comment]
Other bug: https://github.com/Atlantiss/BugTracker/issues/2186

And next time give quest link(wowhead or openwow)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/6311
