### ISSUE TITLE
[EN][Raid Boss][Naxxramas] Kel Thuzad not attackable

### ISSUE THREAD

**Issue by lamaze** [Atlantiss/BugTracker#7943]
As the title of the thread suggest, Kel Thuzad it's not attackable and many achievement related to him aren't obtainable. This should be a quick fix, so pls repair it :)

**Comment by Sayris9876** [comment]
Its been like this forever I managed to do it once on 25man but thats it never got it to work on 10man

**Comment by Tigerief** [comment]
save him :(
Kel'Thuzad's Gold Coin
Item Level 1
Binds when picked up
Use: Throw this coin back into the Dalaran fountain.
"Sometimes... I wish someone would come along and just give me a big, long hug."

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/2450

They have scripted the boss onced but the script caused lags and dcs on the server so now is unscripted. Be patient and wait for a dev to find time and fix it(they focus mostly on cata)

**Comment by mastercho** [comment]
It's end of year almost and still no fix for it!

**Comment by Shaie454** [comment]
Still does not work :/ It's blocking Champion of the Frozen Wastes achievement and some pretty interesting transmog options. It would be nice if u can't fix him to blizzlike state, remove his tactics and just allow us to kill him.
