### ISSUE TITLE
[EN][Quest][Deepholm] Reactivate the Constructs

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#7946]
http://www.wowhead.com/quest=26762/reactivate-the-constructs
The NPC that should been the target click to as the main objective of the quest, can't be clicked.
Instead they are fighting the mobs near it, even though the mobs are dead, they still cant be clicked.

Name of the npc: Deactivated War Construct

![wowscrnshot_072916_122358](https://cloud.githubusercontent.com/assets/20461805/17245924/2ded0fb4-5589-11e6-8475-0d7b088e4686.jpg)

**Comment by rwystop** [comment]
and dont try to tell that is fixed because i was plying on global and i know how that should be working...
Its bugged as fuck !!!

**Comment by Piklo** [comment]
http://atlantiss.eu/changelog#rev5117 "waiting for update" so probably with next server restart it should work

**Comment by rwystop** [comment]
thank you
