### ISSUE TITLE
[EN][Achivement] [Ready for Raiding]

### ISSUE THREAD

**Issue by jokerking963** [Atlantiss/BugTracker#7955]
I cant get the achivement everyone in party got it except me 
And I am sure i didnt get hit 
it did it 3 times and didnt get hit 
and the achive:
http://www.wowhead.com/achievement=5366/ready-for-raiding

**Comment by Sayris9876** [comment]
Im sure its one time thing since everytime i go there with alt i get it and next time link the achievement because there is another one with the same name so people wont get confused!
http://www.wowhead.com/achievement=5366/ready-for-raiding
