### ISSUE TITLE
[EN[QUEST][Darkshore]The Eye of All Storms

### ISSUE THREAD

**Issue by chamhuj** [Atlantiss/BugTracker#7956]
hi everyone i have a problem with quest  THE EYE OF ALL STORMS , twilight portal i not anywhere, i waiting 30 minutes but is still not anywhere

**Comment by sunshitwowsucks** [comment]
change the title to

[EN[QUEST][Darkshore] The Eye of All Storms

**Comment by Bildo** [comment]
duplicate
