### ISSUE TITLE
[PL] [INSTANCE] THE AUCHINDOUN-AUCHENAI CRYPTS-POSSIBLY BUGGED,OR EVEN DAMAGED

### ISSUE THREAD

**Issue by Klick17** [Atlantiss/BugTracker#7959]
On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].

Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.
Make sure, that what you report is actually a bug.
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Write your tickets according to the format:
[EN][Quest][Zone] A Vision of the Past
[EN][NPC] Thoralius the Wise
[EN][Spell][Class] Frostfire Bolt
[PL][Talent][Class] Brain Freeze
[EN][Glyph][Class] Glyph of Frostfire Bolt
[EN][Npc][Drop] Thoralius the Wise
[EN][Web] Armory doesnt work
List of currently supported tags /wiki/List-of-supported-tags-in-issue

**Comment by Klick17** [comment]
May you Staff members of this server go have a serious look inside Auchenai Crypts please? i tried going in there alot of time, but all i got was as stupid crash report and game closed on it own after that.

**Comment by Aival94** [comment]
First try to make a proper bug report. Do not copy and paste everything. Just give correct title and links from Wowhead or Openwow. 

I tried enter with my main and no crash. Can you give some more info when the crash is happening or what addons are you using?

If you want try redownload the mini client just once to see if client problem.

**Comment by TranceAccount** [comment]
Please follow the _How to use_ when reporting bugs: https://github.com/Atlantiss/BugTracker#atlantiss-core-4
