### ISSUE TITLE
[PL][Quest][Westfall]A Vision of the Past

### ISSUE THREAD

**Issue by BoudikaPL** [Atlantiss/BugTracker#7961]
[PL] Quest nigdy nie działał poprawnie, co było już nieraz sygnalizowane. Jednak przynajmniej do stycznia tego roku dało się go oddać. Obecnie po jego wzięciu nad NPC Marshal Gryan Stoutmantle jest szary znak zapytania, a na minimapie widzę żółty. Czy dałoby się przywrócić stan sprzed pół roku lub jakakolwiek inna forma auto zaliczenia tego Questu?

**Comment by Bildo** [comment]
duplikat
