### ISSUE TITLE
[EN][NPC] Spitelash Warrior

### ISSUE THREAD

**Issue by Luchass** [Atlantiss/BugTracker#7963]
1. http://www.wowhead.com/npc=6190/spitelash-warrior ;
   http://www.wowhead.com/spell=51901/dream-lash or http://www.wowhead.com/spell=78921/dream-lash
2. This NPC uses Dream Lash that kills me and some another NPCs instantly
3. This NPC shouldn't have this ability
   http://www.wowhead.com/npc=6190/spitelash-warrior#abilities

YouTube: https://youtu.be/VIEd-sTlsQg

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14043-7963-spitelash-warrior/

**Comment by Jenovas** [comment]
Fix in rev 5541
