### ISSUE TITLE
[EN][Quest][Ashenvale] We're Here to Do One Thing, Maybe Two... (chain)

### ISSUE THREAD

**Issue by Luchass** [Atlantiss/BugTracker#7967]
1. http://www.wowhead.com/quest=28532/warchiefs-command-stonetalon-mountains
   http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two
2. These quests can be available together.
3. "We're Here to Do One Thing, Maybe Two..." should be after "Warchief's Command: Stonetalon Mountains!"

**Comment by Aival94** [comment]
Quest [Warchief's Command: Stonetalon Mountains!](http://www.wowhead.com/quest=28532/warchiefs-command-stonetalon-mountains) is breadcumb to quest [We're Here to Do One Thing, Maybe Two...](http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two) which means that if you have [Warchief's Command: Stonetalon Mountains!](http://www.wowhead.com/quest=28532/warchiefs-command-stonetalon-mountains) you need to complete it for the [We're Here to Do One Thing, Maybe Two...](http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two) to become available but if you do not have in your quest log the quest [Warchief's Command: Stonetalon Mountains!](http://www.wowhead.com/quest=28532/warchiefs-command-stonetalon-mountains) the [We're Here to Do One Thing, Maybe Two...](http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two) is available and if you have it in your quest log or complete it the quest [Warchief's Command: Stonetalon Mountains!](http://www.wowhead.com/quest=28532/warchiefs-command-stonetalon-mountains) become unavailable.

**Comment by arathop** [comment]
Did you manage to the "We're Here to Do One Thing, Maybe Two..." quest? Everytime I jum into the caravan I can´t move and after a while I die. The quest remains uncompleted, and hence I can´t continue. A bit annoying.

**Comment by Lidless** [comment]
thissideup-atlantiss commented on Jan 31 2016 "
Quest is completable by starting from The Fold and running back to Silverwind Refuge (preferably on a mount) the same path the Wagon is taking. If you take out the two Sentinal Ambushers in the Crag (one right and one left of the road) and the two Ashenvale Assassins right outside the Skunkworks, the Wagon will ride right through to The Fold.
"
This one is a good solution, so follow it! You have to kill that 2 Sentinal Ambushers and they will not attack you on the way. If you are too slow and the Ambushers are up again then I suggest you to set your HS to Silverwind refuge so you can jump back in no time after clearing the way.

**Comment by MercuricUma** [comment]
just done the quest. the orcs were talking about taking some meat, rdf popped out so it made me down the caravan but i cannot deliver the quest
