### ISSUE TITLE
[EN][NPC] Ya'mon 

### ISSUE THREAD

**Issue by Luchass** [Atlantiss/BugTracker#7969]
1. http://www.wowhead.com/npc=41676/yamon
2. He doesn't trade and repair
3. He should trade and repair. 
Unfortunately, I found what he should trade in cata only on wowroad 
http://cata.wowroad.info/?npc=41676

Evidence of repair - http://wow.gamepedia.com/index.php?title=Ya%27mon&oldid=2806594
"This vendor offers a repair service."

**Comment by Luchass** [comment]
![wowscrnshot_080116_125346](https://cloud.githubusercontent.com/assets/20752862/17291268/91a3fe3c-57eb-11e6-802e-c0d46de89e0c.jpg)

**Comment by user1011** [comment]
http://www.wowhead.com/npc=41676/yamon#sells

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11106-npc-yamon/
