### ISSUE TITLE
[EN][Quest][Uldum] Battlezone

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#7970]
http://www.wowhead.com/quest=27990/battlezone
u can't ride the machine, u need to kill these mobs by yourself ( they are elite with 170k hp) 
characters like rogue will have problem with this...
![wowscrnshot_080116_150915](https://cloud.githubusercontent.com/assets/20461805/17295017/6d53a67c-57fa-11e6-8775-e8e2cb23c829.jpg)

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/2626

You can make a comment on previous reported post.

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/2626
