### ISSUE TITLE
[EN][Quest] Stealing Their Thunder

### ISSUE THREAD

**Issue by Luna-maria** [Atlantiss/BugTracker#7972]
http://www.wowhead.com/quest=29763/stealing-their-thunder

http://us.battle.net/wow/en/item/33330

ingvar's head should have a 100% droprate (both on normal and heroic), it doesn't seem to be like that right now

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11072-npc-ingvar-the-plunderer/
