### ISSUE TITLE
[EN][Quest][Zangarmarsh] Balance must be preserved

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7974]
[Balance must be preserved](http://www.wowhead.com/quest=9720/balance-must-be-preserved)

the controls to turn off the machines can't be manipulated

EDIT: you have to use a [provided Item](http://www.wowhead.com/item=24355/ironvine-seeds) near the controls to destroy them. Can close this

**Comment by user1011** [comment]
You should be able to close your own issues.
