### ISSUE TITLE
[EN][Quest][Ashenvale] Respect for the Fallen

### ISSUE THREAD

**Issue by Jevsevije** [Atlantiss/BugTracker#7976]
In Maesta's Post I need to retrieve Feero's Holy Hammer and The Purifier's Prayer Book. Can't pick them up.

**Comment by user1011** [comment]
Missing: WoWhead links.

**Comment by Aival94** [comment]
Have you tried using the item [Cloak of Cenarius](http://www.wowhead.com/item=45044/cloak-of-cenarius) which is given to you?(you need to activate it after equip it)

**Comment by Luna-maria** [comment]
what aival94 said, quest worked fine when I did it :)

**Comment by Jevsevije** [comment]
I did use Cloak of Cenarius! Done this quest million times. But, I did manage take The Purifier's Prayer Book, not Feero's Holy Hammer. So...

**Comment by Aequitass** [comment]
I have done this quest a few days ago, I couldn't pick the 2 items too while the invisibility was active, when i cancelled it, i was able to pick them up.

**Comment by Jevsevije** [comment]
Will try that. Thanks!

**Comment by TranceAccount** [comment]
Any news @Jevsevije ?

**Comment by Jevsevije** [comment]
Works without invisibility! Don't need to use Cloak of Cenarius.

**Comment by wtRCH** [comment]
Clossing, hope it works
