### ISSUE TITLE
[EN][Quest][Ashenvale] Defend the Tree!

### ISSUE THREAD

**Issue by Jevsevije** [Atlantiss/BugTracker#7981]
http://www.wowhead.com/quest=13935/defend-the-tree
Speak with Halannia to summon the Shade of Shadumbra and use its power to destroy any 50 Warsong enemies at Raynewood Retreat. Quest not working. Can't summon the Shade of Shadumbra!

video: https://www.youtube.com/watch?v=Dh3g-DdA5vs#t=279

**Comment by Jevsevije** [comment]
Now the quest is working with no problem! :-)

**Comment by Aival94** [comment]
Close this issue.
