### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Pickup (ID = 13949)

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#7982]
**Quest link:** [Crossroads Caravan Pickup](http://www.wowhead.com/quest=13949/crossroads-caravan-pickup) (ID = 13949)

**What is bugged:** When you try to mount the [Lead Caravan Kodo](http://www.wowhead.com/npc=34430/lead-caravan-kodo) (ID = 34430) you get stuck in the spot where you mounted the Kodo and thereby you can't do the shooting part to defend the Caravan. This makes you fail the quest, and doesn't allow you to progress further into the Northern Barrens. The [Far Watch Caravan Kodo](http://www.wowhead.com/npc=34432/far-watch-caravan-kodo) (ID = 34432) doesn't disappear as reported in #4442.

**NOTE:** It is the sixth quest you get in the Northern Barrens. You can complete the quest by first leaving the mount and then running after it using instant spells on the Quillboars.

[Screenshots with comments](http://imgur.com/a/FJrqK)

**How it should be:** The player should be able to mount the Lead Caravan Kodo and ride with him, shooting the attacking Quillboars, and reach the Grol'dom Farm. After reaching the Grol'dom farm the Caravan should disappear.

**Comment by user1011** [comment]
This kinda happened in [Tailgunner!](http://www.wowhead.com/quest=27905/tailgunner) too. Here you have to mount a plane, and I got stuck in the spot where you get mounted on the gun. It is completable but it didn't feel good.

If I find another quest that has a mount bug I'll change this title.

**Comment by TranceAccount** [comment]
Works again.
