### ISSUE TITLE
[EN][Achievement] Warsong Gulch Perfection

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#7984]
**Achievement link:** [Warsong Gulch Perfection](http://www.wowhead.com/achievement=168/warsong-gulch-perfection) (ID = 186)

**What is bugged:** You can get this achievement by just winning a Warsong Gulch. Might be because the other team didn't have any captured flags, and the battleground ended early.

**How it should be:** Your team must win with a score of 3 captured flags, and the opposite team should have 0 flags captured.

**Comment by BAndysc** [comment]
Fixed in rev 5144
