### ISSUE TITLE
[EN][Quest][Elwynn Forest]The Fargodeep Mine

### ISSUE THREAD

**Issue by blafaq** [Atlantiss/BugTracker#7985]
Quest can not be completed : http://www.wowhead.com/quest=62/the-fargodeep-mine

**Comment by user1011** [comment]
Any information? Where did you stand? Did you go inside the mine?

**Comment by blafaq** [comment]
Sorry, I explained it wrong.. It's completed in quest log but the NPC don't want to accept it.

**Comment by user1011** [comment]
Try retaking the quest.

**Comment by blafaq** [comment]
It works, thanks !
