### ISSUE TITLE
[EN][Item] Disgusting Jar

### ISSUE THREAD

**Issue by TheCroak** [Atlantiss/BugTracker#7986]
The item shows 3 days left when you buy it, but when you relog or close the game it bugs. After that it will show "Duration: 0 sec". So there's no way to wait for the 3 days and open it to get your reward. Tried re buying and nothing happens. Also, if you move the item to another slot in your backpack it will reset to 3 days again.

http://www.wowhead.com/item=44717/disgusting-jar
http://www.wowhead.com/item=44718/ripe-disgusting-jar
http://www.wowhead.com/npc=31911/tanak

Thank.

**Comment by Sainsyl** [comment]
It's a known bug i think,keep it in your main bag and it will work (you might have to buy it again though)

**Comment by TheCroak** [comment]
I already kept for 4 days and nothing happened, so I sold that one and bought a new one... any other tip to make it work?

**Comment by rwystop** [comment]
MOST OF ITEMS WITH DURATION 0 DONT WANT TO fade

**Comment by Docholiday-Atlantiss** [comment]
I can confirm the jar does bug. I have held one for 3 days now and am unable to open it.

The jar after 1 days showed a duration of 0 days. To test the issue I did not move it as some have stated it will reset the counter. As that I can confirm as it may be a visual moving the jar to another bag slot does show the counter at 3 days again.

**Comment by Samineh** [comment]
Bump :+1:

**Comment by pelekon** [comment]
fixed in rev 5901
