### ISSUE TITLE
[EN][NPC][Darkshore] Jr. Archaeologist Ferd

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#7987]
Hi :)

Problem with this quests : 
-- http://www.wowhead.com/quest=13911/the-absent-minded-prospector
-- http://www.wowhead.com/quest=13912/swamped-secrets
-- http://www.wowhead.com/quest=13918/the-titans-terminal

The problem comes from the NPC Jr. Archaeologist Ferd  (http://www.wowhead.com/npc=34342/jr-archaeologist-ferd) who is in a different phase ... 

So if a player ends the quest [The Titans' Terminal], the NPC enters in a different phase and all the others players can't talk to him to end [Swamped Secrets]+[The Absent-Minded Prospector] and they can't have the quest [The Titans' Terminal]. 

Thanks for your help.

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/648
