### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by Idiosynkrasis** [Atlantiss/BugTracker#7993]
In this quest, the NPC asks us to speak to a Warden of the Sunwell to grant us passage to the Sunwell Plateau raid. Unfortunately, when we speak to the wardens in question, a message appears in chat and says that the raid is closed, meaning that it's not open at all to players.

This problem makes the quest impossible to complete. 

Also, the quest giver appears to give two version of the quest, each asking to immerse a different version of Quel'Delar in the quest text, but give the same item (Tainted Quel'Delar).

Another problem is that a friend of mine also reached the same point, but the NPC didn't give the quest - he didn't have any available quests, i.e., no exclamation marks.

http://www.wowhead.com/quest=24553/the-purification-of-queldelar
http://www.wowhead.com/quest=24595/the-purification-of-queldelar

**Comment by Bildo** [comment]
duplicate
