### ISSUE TITLE
[EN][Quest][Mount Hyjal] A Ritual of Flame

### ISSUE THREAD

**Issue by TheCroak** [Atlantiss/BugTracker#7995]
I actually searched for this quest and found it, but they said it was fixed already. But still bugged. I cannot complete it and have been trying for days. When I was leveling and now. This make players unable to go to Molten Front and its limiting content for some people with the same issue.
The bar is already full when you get the quest and you can never open the portal, nothing happens and you cannot complete the quest.

http://www.wowhead.com/quest=29195/a-ritual-of-flame

**Comment by box7or** [comment]
This is important, tried to do it today with my friend to get to the Molten Front and we were pissed when we found out it doesn't work. Please fix

**Comment by Thefakemccoy** [comment]
The quest is not properly resetting as it should. Leyara is freezing up and not continuing the RP she should.

**Comment by maslak** [comment]
bump

**Comment by Aurainbows** [comment]
Still bugged. Charred Invaders continue to come out of the portal and all NPCs appear to be working, however the timer is 105/105 and fully lit, and the NPC Leyara does not come out of the portal, thus the quest cannot be finished. I've heard that it can only be done after a server reset or crash.

**Comment by worloq** [comment]
still doesnt work

**Comment by rasmodeus** [comment]
I have the same problem, the timer starts at 105/105, and I was there for quite some time killing the mobs without quest success.

**Comment by karolnpc** [comment]
bump

**Comment by wojtekwax** [comment]
bump, 3 char stuck on that q

**Comment by tomatosz** [comment]
Seems to be fixed, can anyone else confirm?

**Comment by Parmon** [comment]
yup works now

**Comment by Aival94** [comment]
As far as i know now is working so should be closed(only bug about quest and spell is reported here: https://github.com/Atlantiss/BugTracker/issues/9118).
