### ISSUE TITLE
[EN][Raid][Firelands] Lord Ryolith Not Resetting Properly

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#7998]
**What is happening:** Lord Ryolith isn't resetting properly after the group wipes. Sometimes the group is locked out of the instance with "unable to zone in while encounter is in progress" for up to 30 minutes. If you do not release you can see the boss still walking around and hitting volcanoes until he transitions into phase 2; once he gets to phase 2 he resets.

**How to replicate and observe:** Wipe to Lord Ryolith and do not release, watch him run bounce off lava until he hits enough volcanoes to get into phase 2

**How it should be:** Lord Ryolith should reset immediately after everyone in the group dies

**Comment by sunshitwowsucks** [comment]
he also does to much dmg of active volcanos

**Comment by Prodiege** [comment]
Not relevant at all, please remove

**Comment by Quban** [comment]
From what i ve seen, lord is not resetting when someone released and got ressurected by trying to enter FL, than somehow boss keeps aggro on that player and dont want to reset :(

**Comment by Prodiege** [comment]
My whole raid has been a ghost (not resurrected) and stuck outside the instance while he is still not resetting. No one released before the full wipe occurred.

I will test it with you to show you exactly how if you want to meet me on the PTR
