### ISSUE TITLE
[EN][Quest][Sholazar Basin] Just Following Orders

### ISSUE THREAD

**Issue by BadTudor** [Atlantiss/BugTracker#8004]
In the quest http://www.wowhead.com/quest=12540/just-following-orders, the NPC Injured Rainspeaker Oracle doesn't exist. The Crocodilisk doesnt exist also.

**Comment by Aequitass** [comment]
Did u check the Oracle camp? He was located there when I did the quest.

**Comment by Bildo** [comment]
duplicate
