### ISSUE TITLE
[EN][Calendar] World Events

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8006]
Lunar Festival
Love is in the Air
Children's Week
Pilgrim's Bounty
Those four world events aren't displayed on calendar.
Its sort of a bug (since retail cata was from 2010-12) but it should be scripted here for this and years ahead.

> As far as I know these events weren't displayed in 4.3.4 client, since the server has no control over it.

"Forgot about Darkmoon, but i believe its used after the 4.3 patch for Darkmoon isle
http://i.imgur.com/Ohj9vqY.jpg (you can see here, lunar and love is in the air) "
#6292

**Comment by rwystop** [comment]
They will never repair this anyway :) *Kisses

**Comment by Samineh** [comment]
Bump :+1:

**Comment by pelekon** [comment]
Hardcoded clientside.
