### ISSUE TITLE
Leatherworking 

### ISSUE THREAD

**Issue by anolie** [Atlantiss/BugTracker#8008]
There is a bug/mistake in lw recipe. When u craft it is said u  would get Vicious Leather Gloves (http://oi67.tinypic.com/2up7ngk.jpg)

but after crafting u get another item instead of it. Gloves with other name and stats - Bloodthirsty Leather Gloves (https://s10.postimg.org/823fr7zsp/Wo_WScrn_Shot_080816_151750.jpg)

**Comment by Aival94** [comment]
This is not a bug but sth devs did as on 4.2 content there were no Vicious Craftable gear and instead they were the Bloodthirsty one.

Every time we go to next tier(both PVE and PVP change together) they update the recipes to next patch which mean Vicious gear will be when we have next tier.

**Comment by Malylolek** [comment]
Like Aival said its not bug 

Close
