### ISSUE TITLE
[EN][Quest][Cape of Stranglethorn] Drive-By Piracy

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#8009]
**Quest link:** [Drive-By Piracy](http://www.wowhead.com/quest=26649/drive-by-piracy) (ID = 26649)
**Prerequisite:** [Ol' Blasty](http://www.wowhead.com/quest=26647/ol-blasty) (ID = 26647) #5308

**What is bugged:** When you ask [Bloodsail Oarsman](http://www.wowhead.com/npc=43605/bloodsail-oarsman) (ID = 43605) to ride the boat, you get mounted onto the cannon on the boat, but when the NPC starts rowing the boat goes away, and you are stuck on the cannon in the same spot. Since you are stuck in the same spot you can't shoot down the [Venture Co. Oil Workers](http://www.wowhead.com/npc=43596/venture-co-oil-worker) (ID = 43596) and thereby **you can't complete the quest.**

[Screenshots](http://imgur.com/a/E6OTZ)

**How it should be:** The cannon should be stuck on the boat, and move with the boat when the Bloodsail Oarsman starts rowing. After the Bloodsail Oarsman stops rowing, you should aim on the Oil Towers with your cannon and kill the Venture Co. Oil Workers (75 of them).

Similar kind of mount bugs: #7982 and #842.

**Comment by BAndysc** [comment]
Probably fixed after next update (with rev 5131), let me know if the rev is on the main server and bug persists.
