### ISSUE TITLE
[EN][NPC] Essence of Suffering

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#8012]
http://www.wowhead.com/npc=23418/essence-of-suffering
i killed all the bosses before him and he is still unattackable
![wowscrnshot_080816_191333](https://cloud.githubusercontent.com/assets/20461805/17495153/2d600272-5db8-11e6-91b8-32ff8be98760.jpg)

**Comment by pelekon** [comment]
duplicate #1881
