### ISSUE TITLE
[EN][NPC] Essence of Suffering

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#8013]
http://www.wowhead.com/npc=23418/essence-of-suffering
this boss is still unattackable, even if i killed all bosses before him...
![wowscrnshot_080816_191333](https://cloud.githubusercontent.com/assets/20461805/17498027/086112e2-5dc5-11e6-8eae-02534a2b601b.jpg)

**Comment by pelekon** [comment]
As I wrote duplicate #1881 so don't open new reports...

**Comment by rwystop** [comment]
sorry i didn't see i thought i started the ticket but i dont publicated

**Comment by rwystop** [comment]
WTF it isnt repaired since 29 Jan 2015

**Comment by pelekon** [comment]
old content raids have lower prio than everything else. We'll script BT on Netherwing, so it will be fixed.
