### ISSUE TITLE
[EN][Instance-TBC] -  Magisters' Terrace

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#8014]
sometimes ( 40% of dungeon run)
even if you kill Priestess Delrissa you can't loot her and the door to fiinal boss Kael'thas Sunstrider aren't oppened...
sometimes its working sometimes its not... and if you logout you will be dead and teleported somewhere, then u need to speak with graveyard...
F!@%#^ ANNOYING
![wowscrnshot_080916_003912](https://cloud.githubusercontent.com/assets/20461805/17499057/5011c374-5dcb-11e6-8730-55adaa44ce83.jpg)

**Comment by rwystop** [comment]
THAT WAS EVEN WORKING WITH HEROIC ON WARMANE

**Comment by pelekon** [comment]
Duplicate #6907 start using search option...

**Comment by rwystop** [comment]
SOO REPAIR IT YOU FUCKTARDS !!!!!!!!!!!!!!!!!!!!!1

**Comment by Noviush** [comment]
Yes, it is duplicated, but pelekon in he's (her's) wisdom could understood yhat not all Atlantiss players spek polish :P
