### ISSUE TITLE
[PL][Raid][Firelands HC]

### ISSUE THREAD

**Issue by Kozakko** [Atlantiss/BugTracker#8015]
Beth'tilac
Engorged Broodling (http://www.wowhead.com/npc=53745/engorged-broodling) Zdarza się że za swój target wybierają osoby które aktualnie wchodzą na sieć przy pomocy linek po spinnerach, przez co faktycznie kończą swój bój na górze co nie powinno mieć miejsca.
Cinderweb Spinner (http://www.wowhead.com/npc=53642/cinderweb-spinner) Po ich zabiciu pozostaje po nich ich sieć, ta niestety ma swój termin ważności co kończy się problemem z wejściem na górę po Smoldering Devastation. (Linki zaczynają znikać kiedy ktoś już na niej jest) Sugerowanie rozwiazanie to stworzenie warunku który uniemożliwiał by despawn podczas użycia.
Cinderweb Drone (http://www.wowhead.com/npc=53635/cinderweb-drone) Ich umiejętność Fixate (http://www.wowhead.com/spell=125390/fixate) Po prostu nie działa, mimo otrzymanie bufka drone po prostu nie ignoruje innych celów.

Lordy Rhyolith
Liquid Obsidian (http://www.wowhead.com/npc=52619/liquid-obsidian) Tutaj jest coś nie tak albo z ich ilością albo z nabijaniem przez nich stackow armora, Wg tooltipa w journalu powinno ich wychodzić 5 co daje max 5 odzyskanych stackow armora. Kilkakrotnie na dzisiejszym raidzie zdarzyło się nam napotkać sytuacje w której po wdepnięciu w jeden aktywny wulkan boss ostatecznie uzyskał 76 stacków co jest raczej matematycznie niemożliwe.

PS. W jaki sposób skontaktować się Bastkiem w celu updatowania postaci na PTR?

Edit, Shannox
Achievment za zabicie bosa dostaliśmy sekude po pullu.

**Comment by Malylolek** [comment]
Baza postaci na PTR jest aktualizowana co kila tygodni. Musisz zaczekać na kolejny update.

**Comment by Malylolek** [comment]
A i fajnie by było jakbyś przerobił na angielski bo inne gildie też testują a Jenovie robić spam na mailu i kolejne wpisy na bt też nie wypada.

**Comment by Respect69** [comment]
Engorged Broodlingi w dodatku nie zostawiają po sobie chmurki, a powinny.

**Comment by Malylolek** [comment]
Merge to #8036
