### ISSUE TITLE
[EN][NPC] Anub'shiah (ID = 9031)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#8020]
NPC is Neutral for some reason while should be Hostile.

Wowhead Link: [Anub'shiah](http://www.wowhead.com/npc=9031/anubshiah)

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11597-8020npc-anubshiah/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
