### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Delivery 

### ISSUE THREAD

**Issue by yooper2211** [Atlantiss/BugTracker#8024]
Cant talk to the NPC to progress quest, i also read a lot of older posts about this quest, is it possible to at least we have auto complete for this quest "?

**Comment by pelekon** [comment]
Don't use BT as place to ask questions.

**Comment by yooper2211** [comment]
dude this is not a question, how to complete this quest ?

**Comment by pelekon** [comment]
,,is it possible to at least we have auto complete for this quest "?" this is question...
