### ISSUE TITLE
[EN][CORE][Achievement][Reward] Glory of the Cataclysm Raider

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#8027]
Upon completing the the meta achievement "Glory of the Cataclysm Raider", you should get a mail from Thrall which contains the reward from this meta-achievement, Reins of the Drake of the East Wind.

The reward does not work on Atlantiss, you do not get any mail from Thrall.

Link to mail and what it should contain: http://www.wowhead.com/achievement=4853/glory-of-the-cataclysm-raider#comments:id=1557852

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11139-achievementreward-glory-of-the-cataclysm-raider/

**Comment by Aival94** [comment]
As far as i know the achievement [Double Dragon](http://www.wowhead.com/achievement=4852/double-dragon) do not work on atlantiss because the adds do not spawn in the realm.
How you even tested it to know that you do not get the mail?

**Comment by Malylolek** [comment]
@Aival94 http://atlantiss.eu/armory/character/280918/achievements/168#view-page

**Comment by Bildo** [comment]
Yea can you tell us how did you manage to get it?

**Comment by Sayris9876** [comment]
So what you talking? Double Dragon working now?

**Comment by Malylolek** [comment]
Fixed in rev. [5137](http://atlantiss.eu/changelog#rev5137).
