### ISSUE TITLE
 [EN][Talent][Warrior] Enrage with the mastery on fury doesn't scale damage.

### ISSUE THREAD

**Issue by wills18** [Atlantiss/BugTracker#8029]
The mastery of the war fury doesn't work because the talent enrage don´t scale physical attacks and spell.
![bug 1](https://cloud.githubusercontent.com/assets/20975023/17598822/e64f410c-5fc1-11e6-8e42-ec9c493c3dc9.jpg)
![lel](https://cloud.githubusercontent.com/assets/20975023/17598930/6c1e9526-5fc2-11e6-963d-2f5e2251d6ee.jpg)

**Comment by Giovanni2293** [comment]
i got this problem too. please take a look here. that is a huge decrease damage.

**Comment by BialyADI** [comment]
Its visual bug.

**Comment by mati865** [comment]
Have you tested if it does increase dmg by 10%?

**Comment by wills18** [comment]
Yup adam i tested visual bug thx anyways.
