### ISSUE TITLE
[EN][Quest][Object][Blackrock Spire] Drakkistah's Brand

### ISSUE THREAD

**Issue by Articuno** [Atlantiss/BugTracker#8033]
http://www.wowhead.com/object=179880/

The brand is missing. It makes the quest Blackhand's Command (http://www.wowhead.com/quest=7761) uncompletable which in turn blocks the usage of the Orb of Command to enter Blackwing Lair. There was another issue with the quest (failed on pickup), that got resolved recently, but it is still broken.

**Comment by rwystop** [comment]
@Articuno why are u even reporting that? they will never repair this anyway :D ?

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11646-8033objectblackrock-spire-drakkistahs-brand/

**Comment by Damfee** [comment]
I was happy to see the fix implemented last update, so I went to do the quest.

The orb is here, but clicking on it only prompts a box that says ''Greetings (name)'' . Still cannot finish the quest.

**Comment by Bildo** [comment]
Well it was just adding the object not the script to it :P

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12060-8033objectblackrock-spire-drakkistahs-brand/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.

**Comment by Articuno** [comment]
Well, for me it's still "Greetings, <player>" and nothing else. No change.

**Comment by Navedonar** [comment]
The fix hasn't got accepted yet.

**Comment by TranceAccount** [comment]
The latest fix hasn't got accepted yet xD
