### ISSUE TITLE
Warlock Enslave Demon Spell

### ISSUE THREAD

**Issue by GeneticDepravation** [Atlantiss/BugTracker#8034]
Seems like this spell works only half correctly. After using it on a demon, it gets enslaved but if you use that demon to kill anything, after it completely gets out of combat/aggro it automatically and by itself dismisses and you cannot use enslave demon on it again, on the same demon I mean. EVER. So it is buggy. You should really look into it.

Thank you for your consideration.

Cheers.

**Comment by pelekon** [comment]
Read https://github.com/Atlantiss/BugTracker/blob/master/README.md and edit your report.

**Comment by rwystop** [comment]
@GeneticDepravation why are u even reporting that? they will never repair this anyway :D ?
