### ISSUE TITLE
Mind Control Priest Spell

### ISSUE THREAD

**Issue by GeneticDepravation** [Atlantiss/BugTracker#8035]
This spell also works half right. You mind control a humanoid, you can move it around, use it to attack, although sometimes it attacks by itself and moves by itself against your control. But after a few solid 20-30 seconds maximum( even though the spell lasts longer) it gets out of your control and bugs. plus keeps moving by itself most of the times. And of course, I'm not trying to be Captain Butthurt, but there are no abilities at some humanoids, most of them actually. So it works like 35-40% this spell. And it's a pretty damn spell and lots of fun

Thank you for your consideration.

Cheers.

**Comment by pelekon** [comment]
Read https://github.com/Atlantiss/BugTracker/blob/master/README.md and edit your report.

**Comment by rwystop** [comment]
@GeneticDepravation why are u even reporting that? they will never repair this anyway :D ?
