### ISSUE TITLE
[EN][Raid][Heroic Firelands]

### ISSUE THREAD

**Issue by dzejsonator** [Atlantiss/BugTracker#8036]
Beth'tilac:
- Drone's fixate doesn't work at all

Ryolith:
- Meltdown doesn't work (fragments)
- Move mechanic

**Comment by xolon** [comment]
Almost all the bugs above are already reported.
-Obsidian blobs sometimes spawn in 2s so it might seem that 1 gives double stack if you don't use nameplates. We've killed him 2 times already and haven't noticed "real" double stack.
Thnx for the other 2 rhyo reports, haven't really thought to test those!

About Baleroc idk what do you mean by undertuned, people have 379 ilvl here instead on like retail pre nerf version where people had 368-370 (even with 379 ilvl our bdk tank dropped to 10-20% few times) Health is pre-nerf.

**Comment by Malylolek** [comment]
Merge from #8015 : 

Beth'tilac
Engorged Broodling (http://www.wowhead.com/npc=53745/engorged-broodling) Zdarza się że za swój target wybierają osoby które aktualnie wchodzą na sieć przy pomocy linek po spinnerach, przez co faktycznie kończą swój bój na górze co nie powinno mieć miejsca.
Cinderweb Spinner (http://www.wowhead.com/npc=53642/cinderweb-spinner) Po ich zabiciu pozostaje po nich ich sieć, ta niestety ma swój termin ważności co kończy się problemem z wejściem na górę po Smoldering Devastation. (Linki zaczynają znikać kiedy ktoś już na niej jest) Sugerowanie rozwiazanie to stworzenie warunku który uniemożliwiał by despawn podczas użycia.
Cinderweb Drone (http://www.wowhead.com/npc=53635/cinderweb-drone) Ich umiejętność Fixate (http://www.wowhead.com/spell=125390/fixate) Po prostu nie działa, mimo otrzymanie bufka drone po prostu nie ignoruje innych celów.

Engorged Broodlingi w dodatku nie zostawiają po sobie chmurki, a powinny.

Lordy Rhyolith
Liquid Obsidian (http://www.wowhead.com/npc=52619/liquid-obsidian) Tutaj jest coś nie tak albo z ich ilością albo z nabijaniem przez nich stackow armora, Wg tooltipa w journalu powinno ich wychodzić 5 co daje max 5 odzyskanych stackow armora. Kilkakrotnie na dzisiejszym raidzie zdarzyło się nam napotkać sytuacje w której po wdepnięciu w jeden aktywny wulkan boss ostatecznie uzyskał 76 stacków co jest raczej matematycznie niemożliwe.

PS. W jaki sposób skontaktować się Bastkiem w celu updatowania postaci na PTR?

Edit, Shannox
Achievment za zabicie bosa dostaliśmy sekude po pullu.

**Comment by Kozakko** [comment]
Dodatkowo 
Lord Rhyolith Filmik ilustrujący działanie bosa z 07.07.2011
https://www.youtube.com/watch?v=mzSvmlvcS7w
Spark of Rhyolith http://www.wowhead.com/npc=53211/spark-of-rhyolith
Tutaj zauważyłem mały bug aczkolwiek w wersji hc może okazać się dość uciążliwy. Sprki u nas od razu zaczynają bić aoe i agrują się na najblizszego gracza. Na filmiku instruktażowym widać doskonale spawn sparka między 2.05 a 2.15. 2.07-Sprark się pojawia 2.10-Spark zaczyna bić aoe i leći na osobę która jest 1 w threacie. Przkopiowałem to z mojego poprzedniego zgłoszenia, Delay z mele atakami został naprawiony przez @Wolffenstein lecz niestety nie ma go co do startu casta aoe dmg

**Comment by Kozakko** [comment]
UPDATE.

Liquid Obsidian nabijają już po 1 stacku. 
Spark of Rhyolith. Fajnie zrobiony delay z immolation aurą lecz ten delay powinien utrzymywać się w kwestii poruszania, Spark po spawnie powinien siedzieć tak jakby w stunie i po jakimś czasie powinien z niego wyjść i atakować. Gracze powinni od niego odbiec a nie tank wyprowadzić go z raidu. Jeśli ktoś kiedys bił LK to mechanika powinna być podobna do Raging Spiritów. Spawn->x sekundowy stun ( z możliwością normalnego wbijania aggro)-> normalne poruszanie się atakowanie.
Superheated (http://www.wowhead.com/spell=101304/superheated#used-by-npc) Nie

**Comment by Jenovas** [comment]
I removed all comments and updated the first the report. 
Sorry for removing all the comments, but it's easier for me to keep the first post updated than read all the comments.

Please write comments normally, I will be removing them and updating the main post with everything you report.

Thx for your help. Cheers.

**Comment by Malylolek** [comment]
From up : 

What's not working: Rhyolith movement is a bit buggy just like it was before the movement fix from Quban,it shouldn't be moving buggy like it is now(example,even if bar is full on the right side,the boss keeps going forward,and then moves right after a stomp).
