### ISSUE TITLE
[EN][Atlantiss][General] i think these all issues are bugged for Admins , because they will never repair this anyway

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#8042]
This server is idiotic

**Comment by rwystop** [comment]
REALLY AT LEAST ON WARMANE CLASS WERE FULLY SCRIPTED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rwystop** [comment]
MAYBE BETTER REALLY ABANDON THE fuCKING CATA PROJECT AND DO AT LEAST FUCKING TBC
WITH WORK LIKE THAT THIS SERVER WILL GET NOTHING

**Comment by rwystop** [comment]
FUCKING BUGLANTISS WITH DRASITCALLY BUGS, THIS SERVER IS UNPLAYABLE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

**Comment by karhima** [comment]
Wow, ragekid much? Please close the door behind you when you're leaving.

**Comment by rwystop** [comment]
RAGEKID ?!! IM JUst FUCKING BORED OF THIS SERVER, ITS WORST SERVER I EVER SEEN, EVEN MAJOR SPELLS ARE BUGGED !!

**Comment by rwystop** [comment]
WHAT ARE THEY DOING FOR THIS SERVER ?!?!?!?!!? OPENNED ISUES SINCE 2014 AND STILL NOT REPAIRED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THIS FUCKING SERVER HAS NO FUTURE

**Comment by rwystop** [comment]
LEAVE THIS SERVER IS THE bEST thiNG THAt U CAN DO

**Comment by TranceAccount** [comment]
Go back to warmane if it is better there.

**Comment by TranceAccount** [comment]
Attack power =/= Damage

**Comment by wojen616** [comment]
well, i guess he will be forced to go back to warmane xd

**Comment by rwystop** [comment]
ofc im going back to warmane
as i said- AT LEAST THEY HAVE WORKING SPELLS TALENTS AND GLYPHS
YOU HAVENT WORKING (EVEN) MAJOR SPELLS !!!
