### ISSUE TITLE
[EN][Huge Atlantiss Problem]- PPL dont know that u will never repair bugs

### ISSUE THREAD

**Issue by rwystop** [Atlantiss/BugTracker#8047]
sad but true
![image](https://cloud.githubusercontent.com/assets/20461805/17649524/bdccbe62-6237-11e6-9c72-9f4fd108230f.png)
since year and still dont repaired :camel:

**Comment by Aldergar** [comment]
[EN][Player-rwystop] Retard

**Comment by rwystop** [comment]
@aldergar because of true ?
im just openning your eyes
