### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Zander1994** [Atlantiss/BugTracker#8051]
The Exorcism of Colonel Jules

This quest http://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules has recently bugged.
I am supposed to talk to Anchorite Barada http://www.wowhead.com/npc=22431/anchorite-barada to start the exorcism but there is no option to talk to him.
The problem with this is that it starts a 3 quest chain and is in the way of getting the To Hellfire and back Achievement in with the player need to complete 76 quests in Hellfire Peninsula, without this quest I am stuck at 74/76!

Thank you for your time!

**Comment by Lebiedz** [comment]
If you want your issue to be reviewed, fix the title according to rules: https://github.com/Atlantiss/BugTracker

**Comment by Aival94** [comment]
I can confirm that the quest is no longer working(used to work just fine).

How it should work: [The Exorcism of Colonel Jules](http://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules#videos:id=53347)

**Comment by Griskhet** [comment]
Still bugged

**Comment by ponkytok** [comment]
bump
still bugged
please fix this

**Comment by rasmodeus** [comment]
Still not working. Anchorite Barada has no dialogue option to start the event.

**Comment by Danbar1976** [comment]
ye, still bugged
 please fix this

**Comment by rdoherty0** [comment]
Bump 10/29/2016

**Comment by Noviush** [comment]
Still bugged :(

**Comment by reapertg** [comment]
Bump 01/12/16 - still no dialogue option with Anchorite Barada to start the exorcism.

**Comment by reapertg** [comment]
However, it is still possible to get the questing achievement. The only chains i can think of that you may have missed start at the crashed zeppelin & at the cave just NW of Thrallmar

**Comment by baks93** [comment]
Still bugged

**Comment by Avalain** [comment]
I waited for server restart and hoped everything will work fine. I even killed those Quest NPC's with my Horde toon to make sure they will respawn.

There is no dialogue , event doesn't start.

**Comment by Alinna99** [comment]
This is still bugged, please fix it! Thanks!

**Comment by DuGalle** [comment]
Still bugged 3 quest chain blocked

**Comment by sigmundfreud2016** [comment]
Still bugged after today's restart.

**Comment by jissabraham** [comment]
still bugged

**Comment by Hernajs** [comment]
Bump. Still bugged.

**Comment by Snake90** [comment]
Still bugged : impossibl to talk the NPC to begin the exorcism.

**Comment by naakarg** [comment]
Still doesn't work, issue is the same as stated above.

**Comment by MercuricUma** [comment]
Still bugged : /

**Comment by tomatosz** [comment]
Oops, forgot to close this, this has been fixed as of rev. 5660.
