### ISSUE TITLE
[EN][NPC] Muradin Bronzebeard

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#8052]
Muradin Bronzebeard in Icecrown Citadel, the one that triggers Deathbringer Saurfang encounter (I believe it's this one: http://www.wowhead.com/npc=37200) uses wrong model. He looks like High Overlord Saurfang (http://www.wowhead.com/npc=36939) instead of his dwarven model.

**Comment by TranceAccount** [comment]
Duplicate... #5193
