### ISSUE TITLE
[EN][Item][Fishing] Crates and Bags

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Atlantiss/BugTracker#8056]
Currently some bags or crates from fishing dailies and or just caught fishing may be empty. 

Current crates opened to be empty:
http://www.wowhead.com/item=21228/mithril-bound-trunk
http://www.wowhead.com/item=27481/heavy-supply-crate
http://www.wowhead.com/item=27513/curious-crate
 http://www.wowhead.com/item=21150/iron-bound-trunk
http://www.wowhead.com/item=34863/bag-of-fishing-treasures (@Sunshineinabox)
http://www.wowhead.com/item=46007/bag-of-fishing-treasures (@Sunshineinabox)
http://www.wowhead.com/item=67414/bag-of-shiny-things (@Sunshineinabox)
http://www.wowhead.com/item=35348/bag-of-fishing-treasures (@Luna-maria)
http://www.wowhead.com/item=34863/bag-of-fishing-treasures (@Luna-maria)

**Any crates or bags not listed please leave a comment and will add.**

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11607-80564791-crates-and-bags/

**Comment by xolon** [comment]
Some are still empty

**Comment by Luna-maria** [comment]
that the fix is on the forums doesn't mean it's on the server yet :( they still have to run the fix

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.

**Comment by roesiran** [comment]
My past 10 Bags of Shiny Things were empty from daily in Stormwind, so it still persists, and sometimes bags from Dalaran quest and Shattrath is sometimes empty, but bag from Stormwind is always empty. Please fix it because it blocks Cooking Achievements, cuz i can't drop last Recipe.

**Comment by TheRealestMcCoy** [comment]
the fix would have worked but for some reason the loot mode was left to 0 should be 1.
LootMode
A special parameter used for separating conditional loot, such as Hard Mode loot. A lootmode of 0 will effectively disable a loot entry (its roll will always fail). This column is a bitmask, so you shouldn't duplicate loot across lootmodes. The active lootmode(s) can be changed at any time by the core. This column should only be used if required, in most cases it should be left as 1. Valid lootmodes include: 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 16384, 32768.

**Comment by TheRealestMcCoy** [comment]
Here is a fix i tested 10 bags with most i got 9/10 bags containing items on average so it may depend on your luck from RNG. 

`DELETE FROM item_loot_template WHERE entry IN (21228, 27481, 27513, 21150, 34863, 46007, 67414, 35348);
INSERT INTO item_loot_template (entry, item, ChanceOrQuestChance, lootmode, groupid, MinCountOrRef, maxcount) VALUES
(21228, 4339, 42, 1, 0, 1, 3),
(21228, 4304, 41, 1, 0, 2, 4),
(21228, 14048, 31, 1, 0, 1, 2),
(21228, 8170, 30, 1, 0, 1, 2),
(21228, 6149, 21, 1, 0, 1, 2),
(21228, 3928, 21, 1, 0, 1, 2),
(21228, 34109, 4, 1, 0, 1, 1),
(21228, 3914, 0.9, 1, 0, 1, 1),
(21228, 7909, 0.5, 1, 0, 1, 1),
(21228, 10071, 0.3, 1, 0, 1, 1),
(21228, 7910, 0.3, 1, 0, 1, 1),
(21228, 6411, 0.19, 1, 0, 1, 1),
(21228, 8129, 0.18, 1, 0, 1, 1),
(27481, 23424, 30, 1, 0, 1, 3),
(27481, 23783, 30, 1, 0, 1, 3),
(27481, 23781, 26, 1, 0, 1, 2),
(27481, 23768, 15, 1, 0, 1, 4),
(27481, 34109, 3, 1, 0, 1, 1),
(27513, 23424, 34, 1, 0, 2, 5),
(27513, 21877, 34, 1, 0, 4, 6),
(27513, 34109, 2, 1, 0, 1, 1),
(21150, 4234, 47, 1, 0, 2, 4),
(21150, 4305, 46, 1, 0, 1, 3),
(21150, 4339, 35, 1, 0, 1, 2),
(21150, 4304, 34, 1, 0, 1, 2),
(21150, 1710, 24, 1, 0, 1, 2),
(21150, 3827, 23, 1, 0, 1, 2),
(21150, 34109, 5, 1, 0, 1, 1),
(21150, 1725, 1, 1, 0, 1, 1),
(21150, 10288, 0.5, 1, 0, 1, 1),
(21150, 3864, 0.4, 1, 0, 1, 1),
(21150, 1529, 0.3, 1, 0, 1, 1),
(34863, 34861, 76, 1, 0, 4, 6),
(34863, 8827, 25, 1, 0, 2, 3),
(34863, 24478, 11, 1, 0, 2, 3),
(34863, 22578, 11, 1, 0, 2, 4),
(34863, 34859, 11, 1, 0, 1, 1),
(34863, 34840, 11, 1, 0, 1, 1),
(34863, 34843, 11, 1, 0, 1, 1),
(34863, 34839, 11, 1, 0, 1, 1),
(34863, 34860, 11, 1, 0, 1, 1),
(34863, 34841, 11, 1, 0, 2, 4),
(34863, 24479, 3, 1, 0, 1, 1),
(34863, 34836, 2, 1, 0, 1, 1),
(34863, 34828, 1.4, 1, 0, 1, 1),
(34863, 34829, 1.4, 1, 0, 1, 1),
(34863, 34824, 1.4, 1, 0, 1, 1),
(34863, 34826, 1.3, 1, 0, 1, 1),
(34863, 34827, 1.3, 1, 0, 1, 1),
(34863, 34823, 1.3, 1, 0, 1, 1),
(34863, 34825, 1.3, 1, 0, 1, 1),
(34863, 34822, 1.2, 1, 0, 1, 1),
(34863, 34831, 1, 1, 0, 1, 1),
(34863, 34838, 1, 1, 0, 1, 1),
(34863, 33820, 0.9, 1, 0, 1, 1),
(34863, 34109, 0.7, 1, 0, 1, 1),
(34863, 34834, 0.6, 1, 0, 1, 1),
(46007, 6522, 50, 1, 0, 2, 4),
(46007, 40195, 46, 1, 0, 3, 5),
(46007, 8827, 23, 1, 0, 2, 3),
(46007, 46006, 23, 1, 0, 1, 1),
(46007, 45978, 16, 1, 0, 2, 5),
(46007, 33448, 10, 1, 0, 1, 2),
(46007, 49667, 9, 1, 0, 1, 1),
(46007, 36783, 6, 1, 0, 1, 3),
(46007, 46361, 6, 1, 0, 2, 2),
(46007, 46359, 6, 1, 0, 1, 1),
(46007, 45980, 6, 1, 0, 1, 1),
(46007, 46001, 6, 1, 0, 1, 3),
(46007, 46003, 6, 1, 0, 1, 3),
(46007, 46000, 6, 1, 0, 1, 3),
(46007, 46002, 6, 1, 0, 1, 3),
(46007, 45999, 6, 1, 0, 1, 3),
(46007, 45984, 5, 1, 0, 1, 1),
(46007, 46004, 5, 1, 0, 1, 1),
(46007, 54469, 5, 1, 0, 1, 1),
(46007, 54470, 5, 1, 0, 1, 1),
(46007, 45981, 5, 1, 0, 1, 1),
(46007, 45979, 5, 1, 0, 1, 1),
(46007, 45977, 2, 1, 0, 1, 1),
(46007, 36784, 1.1, 1, 0, 1, 1),
(46007, 33820, 0.9, 1, 0, 1, 1),
(46007, 45883, 0.8, 1, 0, 1, 1),
(46007, 44983, 0.6, 1, 0, 1, 1),
(46007, 46023, 0.6, 1, 0, 1, 1),
(46007, 46360, 0.6, 1, 0, 1, 1),
(46007, 45879, 0.5, 1, 0, 1, 1),
(46007, 45880, 0.5, 1, 0, 1, 1),
(46007, 19971, 0.5, 1, 0, 1, 1),
(46007, 34834, 0.5, 1, 0, 1, 1),
(46007, 45862, 0.4, 1, 0, 1, 1),
(46007, 45987, 0.4, 1, 0, 1, 1),
(46007, 45991, 0.3, 1, 0, 1, 1),
(46007, 45992, 0.3, 1, 0, 1, 1),
(46007, 45998, 0.3, 1, 0, 1, 1),
(46007, 45861, 0.3, 1, 0, 1, 1),
(67414, 6532, 41, 1, 0, 1, 1),
(67414, 8827, 14, 1, 0, 1, 1),
(67414, 3820, 14, 1, 0, 2, 3),
(67414, 2459, 14, 1, 0, 1, 1),
(67414, 6372, 14, 1, 0, 1, 1),
(67414, 67404, 5, 1, 0, 1, 1),
(67414, 67406, 5, 1, 0, 1, 1),
(67414, 67397, 5, 1, 0, 1, 1),
(67414, 67398, 5, 1, 0, 1, 1),
(67414, 67405, 5, 1, 0, 1, 1),
(67414, 67411, 5, 1, 0, 1, 1),
(67414, 67409, 5, 1, 0, 1, 1),
(67414, 67402, 5, 1, 0, 1, 1),
(67414, 67412, 5, 1, 0, 1, 1),
(67414, 67403, 5, 1, 0, 1, 1),
(67414, 67400, 5, 1, 0, 1, 1),
(67414, 67391, 5, 1, 0, 1, 1),
(67414, 67385, 5, 1, 0, 1, 1),
(67414, 67388, 5, 1, 0, 1, 1),
(67414, 67399, 5, 1, 0, 1, 1),
(67414, 67401, 5, 1, 0, 1, 1),
(67414, 67407, 5, 1, 0, 1, 1),
(67414, 67386, 5, 1, 0, 1, 1),
(67414, 67410, 5, 1, 0, 1, 1),
(67414, 67408, 5, 1, 0, 1, 1),
(67414, 929, 2, 1, 0, 1, 1),
(67414, 44983, 1.1, 1, 0, 1, 1),
(67414, 33820, 1.1, 1, 0, 1, 1),
(67414, 34834, 1.1, 1, 0, 1, 1),
(67414, 34109, 1.1, 1, 0, 1, 1),
(67414, 45991, 0.5, 1, 0, 1, 1),
(67414, 45992, 0.5, 1, 0, 1, 1),
(35348, 34861, 75, 1, 0, 4, 6),
(35348, 8827, 24, 1, 0, 2, 3),
(35348, 34859, 12, 1, 0, 1, 1),
(35348, 35350, 11, 1, 0, 1, 1),
(35348, 33818, 11, 1, 0, 1, 1),
(35348, 35349, 11, 1, 0, 1, 1),
(35348, 33816, 11, 1, 0, 1, 1),
(35348, 24478, 11, 1, 0, 2, 3),
(35348, 34843, 11, 1, 0, 1, 1),
(35348, 34860, 11, 1, 0, 1, 1),
(35348, 22578, 10, 1, 0, 2, 4),
(35348, 34840, 10, 1, 0, 1, 1),
(35348, 34839, 10, 1, 0, 1, 1),
(35348, 34841, 10, 1, 0, 2, 4),
(35348, 24479, 3, 1, 0, 1, 1),
(35348, 34836, 2, 1, 0, 1, 1),
(35348, 34823, 1.4, 1, 0, 1, 1),
(35348, 34825, 1.4, 1, 0, 1, 1),
(35348, 34827, 1.3, 1, 0, 1, 1),
(35348, 34824, 1.3, 1, 0, 1, 1),
(35348, 34826, 1.2, 1, 0, 1, 1),
(35348, 34822, 1.2, 1, 0, 1, 1),
(35348, 33820, 1.1, 1, 0, 1, 1),
(35348, 34828, 1.1, 1, 0, 1, 1),
(35348, 34829, 1.1, 1, 0, 1, 1),
(35348, 34838, 1, 1, 0, 1, 1),
(35348, 34109, 0.8, 1, 0, 1, 1),
(35348, 34831, 0.7, 1, 0, 1, 1),
(35348, 34834, 0.4, 1, 0, 1, 1);`

**Comment by Piklo** [comment]
if you want to change only loot mode
UPDATE item_loot_template SET lootmode = 1 WHERE entry IN (your entries);
would be better, also please post your fix on forum not here

**Comment by TranceAccount** [comment]
I appreciate what you posted tho.

**Comment by TranceAccount** [comment]
The lootmode has been updated from 0 to 1 for the entries 21228, 27481, 27513, 21150, 34863, 46007, 67414, 35348 in rev. 5710.
Thanks TheRealestMcCoy and Piklo.
