### ISSUE TITLE
[EN][Quest][Uldum] Neferset Prison

### ISSUE THREAD

**Issue by zemljazrak** [Atlantiss/BugTracker#8060]
http://www.wowhead.com/quest=27707/neferset-prison
https://www.youtube.com/watch?v=vsfn2pSUEdo

I included a youtube video to show you that nothing happens when you talk with the npc.
Some people said that the quest works, but somebody killed the mobs before so you just have to wait till they spawn, but that's not the case here, i've been flying around and camping/afking around that place for serveral hours now and nothing happens, no mobs spawn, the npc does nothing. This quest is important for the Ramkahen quest line, so it would be nice if it gets fixed.
This may be a duplicate, but other posts are marked as the quest works, but the quest does not work for me.
Thanks

**Comment by TranceAccount** [comment]
Have you tried relogging? It sometimes fixes phasing.

**Comment by zemljazrak** [comment]
I did and I also tried deleting cache folder, but none worked. I've seen other people trying to do the quest   and just end up leaving. Idk anymore

**Comment by Aival94** [comment]
go near the npc and speak with him.After some time the event should start..have done it before around 3 days and was just fine.

**Comment by TranceAccount** [comment]
@Aival94 It looks like he did that on the youtube video he added.

**Comment by Aival94** [comment]
Ok sorry. 

Thought it was a general youtube video of quest from blizzard,

I know it sound stupid but have you tried retake quest and speak with npc while not in any druid form(might be a bug not activated when you are in mount in any transformation)

**Comment by zemljazrak** [comment]
@Aival94  Was the quest on auto accept ? I cant really remember but i think it was, so i'm kinda scared if i abandon it will i be able to take it again. Or was it from a quest giver ?

**Comment by BAndysc** [comment]
@zemljazrak All auto accept quests can also be taken from the quest giver ;)

**Comment by zemljazrak** [comment]
Well i tried talking to the npc without shapeshift, and waiting there for 10-15 minutes, retaking the quest, relogging.. so either im retarded or the quest does not work on me for some reason, i'll try to do it again maybe tomorrow or some time. Either way, thank you guys for being helpful and friendly :D

**Comment by zemljazrak** [comment]
I finally managed to do it ! http://imgur.com/a/5nFSn
The npc responded to me after i talked to him, and the event started like it should.
I did do it early in the morning, maybe you can complete that once a day or something, idk, doesn't matter anymore, im closing this post. Thank you guys again for helping, cya ingame! :D
