### ISSUE TITLE
[EN][Quest][Deepholm]The World Pillar Fragment

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Atlantiss/BugTracker#8063]
The quest [The World Pillar Fragment](http://www.wowhead.com/quest=26876/the-world-pillar-fragment) is bugged. The fragment does not drop now. 

[Fragment](http://www.wowhead.com/item=60574/the-upper-world-pillar-fragment)

**Comment by TranceAccount** [comment]
> is not bugged

**Comment by Docholiday-Atlantiss** [comment]
I killed the dragon 3 times and the pillar fragment did not drop. I was not the only one having this issue as I saw others in world asking about the quest as well so it is worth checking in on it.

**Comment by Avengenaera** [comment]
It is bugged. It's doable, but bugged. I had to summon and kill Abyssion over ten times to get the necessary quest item. Not sure if it's an abysmal drop rate or something else.

**Comment by Docholiday-Atlantiss** [comment]
It may just be a issue of the item respawn timer on the boss kill not sure.

**Comment by Zodex110** [comment]
There is something seriously wrong with this quest, I've killed him 10+ times and haven't completed it. But my friend comes in, kills the dragon and gets the loot on the first try. We're both playing paladins on the horde side, he's tauren and I'm belf.

**Comment by Silverdevilboy** [comment]
I got the item as loot after about two dozen kills, seems like it has been added as loot rather than spawning, and the droprate is super low.

**Comment by rajer93** [comment]
I had the same problem as players above. What i did was to create a party group with a player and set the loot to free for all. After succesfuly slained dragon the mob has a drop; pick it up and objective will complete. 
Note: you must do it a one slain each for a each player (the wanted player must be the party leader; leave and recreate a party.)
 My personal experience. Hope it helps!

**Comment by Silverdevilboy** [comment]
I was indeed in a party when I got the drop, however we didn't remake the party and it dropped again for the other person 5-10 kills later. Might be party-only though.

**Comment by kjmpp** [comment]
I can also say, that we can attack this mob with melee skills from a distance... maybe he is bigger than his model? Nevermind, killed 10+ times and nothing.

**Comment by szapol** [comment]
dropped for me the second time i killed him. there's also something wrong with his hitbox, as a hunter i had to run to the very east end of the lair to get within the shot distance, pet runs away to attack him as well.

**Comment by erendkny** [comment]
You should kill him before throwing shadow nova and then it will drop the quest item.

**Comment by buglantiss** [comment]
Hello,

tried with party FFA <- no loot
killed before he casted shadow nova <- no loot
tried like 30 times <- no loot

Quest is bugged.

Orc, Warrior, Horde, LvL84

**Comment by karhima** [comment]
Quest is bugged, the fragment does not drop.

With Vashj'ir not working and Hyjal completed, that leaves me at 81% of lvl 83 with no more quests to do before Uldum.

**Comment by Silverdevilboy** [comment]
Quest is not blizzlike, but is not bugged. The fragment drops as loot, though it is rare. Have completed quest 3 times in the past two months, took an average of 15 kills to get it.

**Comment by mastercho** [comment]
i just try like 5 times but no drop, please fix it

**Comment by TranceAccount** [comment]
The fragment should drop from a gameobject that spawns after the dead of Abyssion.
https://www.youtube.com/watch?v=ZbMO77fNyjc

**Comment by mastercho** [comment]
Its droped for me after 10th try, seems have low drop rate.

**Comment by Thorghar** [comment]
It's BUGGED !!! Sometimes  Ultraxion hit me, sometimes i can destroy his powerfull nova, and sometimes everythind without a drop is ok. That shitty thing NEVER drop's for me. I've killed him multiple times and nothing. REPAIr THAT FUCKING QUEST, this server it's not so young for those mistakes...

**Comment by Reno323** [comment]
Prabobly on ats u need to do at least 50% dmg to Abyssion to get loot.

**Comment by Silverdevilboy** [comment]
Solo kills do not drop it after several tries. It's just a super low drop rate.

**Comment by Thorghar** [comment]
The droprate need to be 100% like Blizz says http://www.wowhead.com/npc=44289/abyssion#drops
![wowscrnshot_110416_092437](https://cloud.githubusercontent.com/assets/22906825/19999208/43dd2c70-a271-11e6-8171-5f09e02f2cc7.jpg) and when i got those text after killing Ultraxion nothing happens...

**Comment by Reno323** [comment]
@up If Abyssion had 536,148 Health (wowpedia) u dont did 50% of dmg at this mob so u cant get loot from this mob. Helpers should be 'in your party' but here they not. Try to do some good dps and then check loot :)

**Comment by Silverdevilboy** [comment]
Again, solo kills dont drop the loot.

**Comment by bug1912** [comment]
Completed the quest, it's very buggy, but doable. As a hunter I had to find a spot where i was in range to use my range weapon.

**Comment by krecik88** [comment]
fixed in 5266

**Comment by Slotease** [comment]
Horde Troll Hunter 83. It's bugged for me. I have killed him a few times and no drop. Only way i can target him as hunter using ranged is to get very far away where the pet is. This is very far outside of the circle where the dragons are roaming. If i get in close i can only use melee. Also my hunter does this weird Warrior shout thing that they do as a buff when i attack. For me this is bugged. Funny how some classes are bugged. I have done this on ally as druid, mage, hunter paladin, rogue with no problems. On horde side only my hunter is bugged. Shame cos now i can go any further in deepholm.
