### ISSUE TITLE
[EN][Quest][Uldum] Hacking the Wibson

### ISSUE THREAD

**Issue by Avengenaera** [Atlantiss/BugTracker#8065]
After looting the Maintenance Axe from the toolbox next to the mainframe, according to the sources mentioned below, you should be able to hack at it with the axe, however you can't interact with it at all and thus cannot obtain the necessary quest credit. 

For reference: 
http://www.wowhead.com/quest=27778/hacking-the-wibson
https://www.youtube.com/watch?v=Rk7F1w_kZzo

**Comment by Malylolek** [comment]
Merged from : #6391
Brak animacji uderzania toporkiem o maszynę. ~~~~ no animation

**Comment by Charybdo** [comment]
2 hours ago i couldn't even pick up this axe from box.

**Comment by Nergleth** [comment]
Quest can be completable. Animation doesn't work.
