### ISSUE TITLE
[EN][Dungeon][NPC] Trial of the Champion

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#8066]
http://www.wowhead.com/npc=36557/argent-warhorse 
Argent Warhorse cannot be mounted anymore. Worked yesterday. 
I tried reset instance, relog, change dungeon type to heroic, equip [Argent Lance]. Nothing.
Since player can start dungeon event only on a horse, whole instance is broken now.

**Comment by Crusaderz** [comment]
Other players confirm bug. Seems like update with trial of champion achievement fix did something wrong.
I'm alliance btw, if it matters.

**Comment by LaveniaGithub** [comment]
Confirmed. Not sure that the achievement fix caused the problem though.

**Comment by Crusaderz** [comment]
> UNIT_NPC_FLAG_SPELLCLICK will not be added to vehicle when there is empty seat AND npc does not have flag in database
Then this might be the reason. Anyway, many people farm this instance for transmorg gear so it is important.

**Comment by Bildo** [comment]
fixed
