### ISSUE TITLE
[EN][GLYPH][MAGE] Glyph Arcane power

### ISSUE THREAD

**Issue by l337g0g0** [Atlantiss/BugTracker#8067]
So I always had this problem when randomly all my abilities would be on CD.
I had to re log to fix it.
I was just in a BG from not playing for months cause of this, it happened again and I asked again people if they experience it.
Someone in there knew my problem and how to deal with it.
If your an Arcane mage and you have the Glyph of Arcane power and you use Blink while Arcane power is active it glitches and all your abilities to go on CD forever.

I hope you guys can look into this as there might be lots of arcane mages that are terrible frustrated as I have been.
It stopped me from playing on this server cause it happened for months and I could never figure out why this kept happening to me and i was in BG's and you can't re log in there of you wasted all the time trying to earn honor points. :(

But it's all fixed I unequipped Arcane power glyph, but hope you guys can fix it permanently.

Thank you all...

**Comment by Malylolek** [comment]
Already exist #7440
