### ISSUE TITLE
[EN][Quest][Temple of Ahn'Qiraj] Striker's Hauberk

### ISSUE THREAD

**Issue by therealpadthai** [Atlantiss/BugTracker#8070]
I have recently finished AQ40 and killed C'Thun. I have the quest in my questlog, Striker's Hauberk (http://www.wowhead.com/quest=8656/strikers-hauberk), and was expecting to find the quest item in C'Thun's loot table, given that it has a 100% drop chance per WoW databases. 

As per the screenshots provided, no such luck. It did not drop. 

http://imgur.com/a/F1MVY

Item that should have dropped: http://www.wowhead.com/item=20929/carapace-of-the-old-god

Thank you and have a nice evening!

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11634-826581918070-cthun-loot-tables/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
