### ISSUE TITLE
[EN][Dungeon][NPC] Blackrock caverns: Rom'ogg Bonecrusher

### ISSUE THREAD

**Issue by RageWolf** [Atlantiss/BugTracker#8072]
Today while i was doing some rdf (not heroic), I entered blackrock caverns, and while we were fighting the first boss (Rom'ogg Bonecrusher) Whenever he started casting his [Chains of Woe] ability, the group got teleported   underground. We tried the fight three times always with the same result, i was able to record one try, I hope it helps.
https://www.youtube.com/watch?v=zx-D-J6o2pE

**Comment by Aival94** [comment]
Link not working.

**Comment by RageWolf** [comment]
Link should work now

**Comment by Aival94** [comment]
It seems sth else happened as you got teleported before boss use any ability at all. Not sure to be honest but i saw that he started casting chains after you teleported.

**Comment by mzn928** [comment]
it also happens on heroic difficulty. we got teleported some where else with no terrain but the adds where still coming

**Comment by Aival94** [comment]
The bug happen in both Normal and Heroic Difficulty.

It happen just before the boss [Rom'ogg Bonecrusher](http://www.wowhead.com/npc=39665/romogg-bonecrusher) start casting [Chains of Woe](http://www.wowhead.com/spell=75441/chains-of-woe) and the encounter continue.

It seems that the bug happen after rev. 5148 or 5149 but not sure.

If you open your map to see where you are the map is empty and say is a custom room/location.

Wowhead Links:
Location: [Blackrock Caverns](http://www.wowhead.com/zone=4926/blackrock-caverns)
Bugged Boss: [Rom'ogg Bonecrusher](http://www.wowhead.com/npc=39665/romogg-bonecrusher)
Possible bug(Teleport just before the spell start casted): [Chains of Woe](http://www.wowhead.com/spell=75441/chains-of-woe

**Comment by TranceAccount** [comment]
Rev. 5152
