### ISSUE TITLE
[EN][Fishing][Hyjal] Pool of Fire in a place where you cannot get it

### ISSUE THREAD

**Issue by stefan99j** [Atlantiss/BugTracker#8075]
Outside of the Firelands portal, there are fishing nodes called ''Pool of Fire'' when you fish in them you get Volatile Fire, which is working fine. But the bug is that there is one node, which absolutely can't be reached, i've tried to place myself everywhere around it, but it says that i can't fish there, like 2 meters away from it you can fish but in the node you can't. This is a minor bug but it's annoying.

**Comment by pelekon** [comment]
Read BT rules.

**Comment by pelekon** [comment]
oh duplicate  #1111
