### ISSUE TITLE
[PL][Talent][Priest] Shadowy Apparition

### ISSUE THREAD

**Issue by Charybdo** [Atlantiss/BugTracker#8077]
**Jak działa**
Kopia która się pojawia wybiera losowy target do którego zmierza.

**Jak powinno działać**
Kopia powinna wybierać aktualny target wybrany przez nas jeśli ma nałożony czar "Shadow Word: Pain"
Jeśli nasz target nie ma nałożonego "Shadow Word: Pain", nasz guardian powinien wybrać target z którego tick "paina" go przywołał.

**Comment by Malylolek** [comment]
#4770
