### ISSUE TITLE
[PL][Spell][Priest] Shadowfiend

### ISSUE THREAD

**Issue by Charybdo** [Atlantiss/BugTracker#8078]
**Jak działa**
Gdy przyzwiemy Shadowfienda, wybiera on losowy target nawet nie zaagrowany przez nikogo.

**Jak powinno działać**
Shadowfiend powinien atakować target na który go przyzwaliśmy, w momencie gdy ten target zginie , nie zaatakuje ponownie chyba że ktoś nas atakuje lub my kogoś atakujemy.

Dodam że shadowfienda nie można przyzwać nie mając aktualnego wrogiego targetu.

**Comment by Malylolek** [comment]
#1004
