### ISSUE TITLE
[ENG] Potion of Illusion

### ISSUE THREAD

**Issue by Haggar123** [Atlantiss/BugTracker#8080]
I've noticed an issue regarding Potion of Illusion 
[http://www.wowhead.com/item=58489/potion-of-illusion#comments](url)
After i use this it says ''This Spell is not avaiable to you''
Would be very nice if you could fix it because its a very fun item.

**Comment by pelekon** [comment]
Duplicate #1234

**Comment by Haggar123** [comment]
Was almost 2years ago, still nothing about this so why to delete the issue.

**Comment by Bildo** [comment]
Because its still duplicate

**Comment by Haggar123** [comment]
but whats the point of this? if there are more complains about a bug it just means that more people want it to be fixed. But its not my thing. Bye

**Comment by Zumigon** [comment]
No matter if it is duplicate or not, it is still not fixed.
