### ISSUE TITLE
[EN][Quest][Mulgore] Attack on Camp Narache

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8082]
Blizzard disabled this quest since are became unreachable by low level players after the shattering
http://www.wowhead.com/quest=781/attack-on-camp-narache
You can still find it on Atlantiss
http://imgur.com/a/T6Jl5

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12222-8082questmulgore-attack-on-camp-narache/
