### ISSUE TITLE
[PL][Quest][Ashenvale] Return Fire

### ISSUE THREAD

**Issue by Mesanub** [Atlantiss/BugTracker#8084]
Nie można "dosiąść" Astranaar Thrower, żadna nie reaguje na kliknięcia. Relog nie pomaga, ponowne zabranie questa również. 
http://www.wowhead.com/quest=13853/return-fire#comments

**Comment by Malylolek** [comment]
Im not sure about entry of this thrower. 

Update creature_template SET npcflag=npcflag|16777216 WHERE entry = 34492;

**Comment by Mesanub** [comment]
See the video:
http://www.wowhead.com/quest=13853/return-fire#videos:id=47721

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11290-questnpc-next-vehicles/

**Comment by Malylolek** [comment]
Should work after rev. [5164](http://atlantiss.eu/changelog#rev5164)

**Comment by Damfee** [comment]
Not fixed. Impossible to enter in the thrower still.

**Comment by jakubu** [comment]
I tried to complete this quest today, but I too can't get into Astranaar Thrower.
I'm Human Priest.

**Comment by coba999** [comment]
bugged. can't get into Astranaar Thrower.

**Comment by nemmip** [comment]
Not fixed :/

**Comment by RatPete** [comment]
Still not fixed

**Comment by TranceAccount** [comment]
Ceci updated the wrong creature entry.

**Comment by TranceAccount** [comment]
## Posted a fix on the forum for the mounting part:

https://community.atlantiss.eu/index.php?/topic/18255-npc-astranaar-thrower-cecidit-parody/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
