### ISSUE TITLE
[EN][Elemental Shaman][Dragonwrath Tarecgosa's Rest] Proc rate

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#8085]
The proc rate of the Legendary staff is not correct for Elemental Shamans. The proc rate should not be the same for every class. For classes which do all their damage through their spells, the proc rate should be around 10-12%, but for classes which get damage not only from their spells, the proc rate should be higher to make the dmg gained from the staff more equal, i.e. Warlocks and Shamans.

"Test 1:
Casts = 1000 Lightning Bolts
Procs = 172
Proc Rate = 17.2%
1000 Lightning Bolts - Parse #1

Test 2:
Casts = 1000 Lightning Bolts
Procs = 155
Proc Rate = 15.5%
1000 Lightning Bolts - Parse #2

Test 3:
Casts = 5000 Lightning Bolts
Procs = 821
Proc Rate = 16.42%
5000 Lightning Bolts - Parse #3" (http://www.mmo-champion.com/threads/1002334-Dragonwrath-proc-WoL-parses-included?p=13756944&viewfull=1#post13756944)

As seen above, proc rate for Elemental Shaman should be somewhere around 15-17%, but atm it is around 10%.

Own results:
![skaermbillede 2016-08-24 kl 10 38 26](https://cloud.githubusercontent.com/assets/12621497/17926842/3417088a-69f3-11e6-85e2-3be81e5752bd.png)

I tested it with 2037 Flame shock DOT ticks, and I got 236 Wrath of Tarecgosa procs. However, I should've gotten somewhere around 346 ticks of the staff proc instead.

2037 / 100 \* 17 = 346,29.

**Comment by blinkmaster** [comment]
Wasnt dtw nerfed in 4.3 to 8 or 7%?

**Comment by LaveniaGithub** [comment]
Maybe for some classes, but not for Elemental Shamans. 

"Flame Shock:
I received 4622 dot ticks, got 765 Wrath of Tarecgosa which is a 16.5% proc chance.
http://www.worldoflogs.com/reports/i...ick/details/2/" (after the nerf).

**Comment by Aival94** [comment]
The nerf make the proc from 15% to 9% but either way recount does not count all the procs as it should but only from dots which elemental shamans have only one dot(flame shock).
There are many posts in blizzard about this problem as on recount only way to see procs were from the dots

Furthermore to the link you posted one said that by testing them he saw that the proc from casting spells was reduced to 10-11% but on dots remain the same 16-17%

**Comment by LaveniaGithub** [comment]
Dude, I know how to track it... Which is why I only counted my Flame Shock DOT ticks, so yes it does show all procs.

And yea, haven't tested Lightning Bolts or anything else since mastery makes it a pain to track

**Comment by anxanas** [comment]
Changed to around 10% for pet classes in 4.3.4. http://eu.battle.net/forums/en/wow/topic/3061866525
Looks like your numbers are fine lavenia, though i am not sure if elemental shamans are considered pet classes and should have 10% proc chance.

**Comment by xolon** [comment]
ur just unlucky.

**Comment by LaveniaGithub** [comment]
Bumping since I got the staff on main realm (it's not a distant future bug)

Also, currently staff is untouched and gives 10% to all classes and specs. So it is not balanced at all.

**Comment by lamaATS** [comment]
Fixed in rev. 5269
