### ISSUE TITLE
[EN] Foothill Stalker

### ISSUE THREAD

**Issue by presstmoded** [Atlantiss/BugTracker#8086]
These cats hit for about 4 times as much, as they did on retail (the dmg and health should be similar to Hill Stag, so they get to low health at around the same time), for a fresh character (lvl 24 arms war) with 908hp, 784armor unbuffed, few hits taken from these beasts mean certain death. Their attack speed is around 1sec too, no idea if it's correct or not.

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
