### ISSUE TITLE
[EN][Spell][Shaman] Tremor Totem

### ISSUE THREAD

**Issue by Cavyx** [Atlantiss/BugTracker#8090]
Shamans cant use Tremor Totem while warriors fear them. They can use it only when warrios/preists use fear on shamans' team mates. Please fix it because it is impossible to play with warriors as shamans.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/5350

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md 

+ duplicate
