### ISSUE TITLE
[EN][Quest][Molten Front] The Bigger They Are

### ISSUE THREAD

**Issue by BoulderGiant** [Atlantiss/BugTracker#8092]
The mobs are very difficult to kill because of a buff they get when they take some damage (I dont know if THIS is blizzlike or not) but, if for some reason, I can kill one, something appears on the ground. I think its the quest item, but I can´t interact with it. Besides, the respawn time is too short, they re-appear too fast after I kill one.

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
