### ISSUE TITLE
[EN][Quest][Uldum] Tipping the Balance

### ISSUE THREAD

**Issue by MnmZilla** [Atlantiss/BugTracker#8094]
I never get into the cinematic in this quest, and then if I try talking to the Harrison Jones NPC he just spawns another copy of himself which jumps on top of the statue which then disappears. If I try to talk to him again he just repeats the same thing, I have tried doing /reload then abandoning the quest and retaking the quest but no luck. I cannot go further in the Uldum quest chain if I do not complete this quest, pls halp.

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
