### ISSUE TITLE
[EN][Quest][Ashenvale] Don't Forget the Horde (Minor)

### ISSUE THREAD

**Issue by Avengenaera** [Atlantiss/BugTracker#8098]
The quest requires you to kill 10 Horde NPCs at Bathran's Haunt. There are 2 types of such NPCs - Orc Overseers and Forsaken Herbalists. The issue is that the quest only credits you for the kills of the Orcs, even though the Forsaken Herbalists should also be counting towards the quest. While the issue is easily dealt with, it seems rather easy to fix even if minor.

Wowhead quest link: http://www.wowhead.com/quest=13594/dont-forget-the-horde
Forsaken Herbalist that isn't giving credit towards the quest: http://www.wowhead.com/npc=3733/forsaken-herbalist
Video for how the quest should be working: https://www.youtube.com/watch?v=dmJSh3xOgHw&feature=youtu.be

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12292-8098questashenvale-dont-forget-the-horde/
