### ISSUE TITLE
[EN][NPC][Ashenvale] Orc Overseer

### ISSUE THREAD

**Issue by Avengenaera** [Atlantiss/BugTracker#8099]
Incorrectly labeled as a Forsaken Thug.

http://www.wowhead.com/npc=3734/orc-overseer

Images of how the NPC looks on the server:

![wowscrnshot_082616_125202](https://cloud.githubusercontent.com/assets/21101937/18001548/23125a22-6b8c-11e6-89bf-7cf11ee6df7a.jpg)
![wowscrnshot_082616_125443](https://cloud.githubusercontent.com/assets/21101937/18001600/52b3565a-6b8c-11e6-8be4-b033759cb7e6.jpg)

**Comment by Avengenaera** [comment]
Image of how the NPC looks on the server:

![wowscrnshot_082616_125202](https://cloud.githubusercontent.com/assets/21101937/18001548/23125a22-6b8c-11e6-89bf-7cf11ee6df7a.jpg)

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12291-8099npcashenvale-orc-overseer/
