### ISSUE TITLE
[EN][RAID][BWD][Achvievement Guild Boss Omnotron Defense System bug achviement

### ISSUE THREAD

**Issue by kaliak** [Atlantiss/BugTracker#8101]
hello me and my guild are trying to end the achv BWD , the Omnotron Defense System head not is telling the achv we are on our making 8 menbros Guild and 2 random all the leaders have done so and tell the achv so the defense boss system that no, pliz help me on what might be going on

**Comment by pelekon** [comment]
Duplicate #6712
