### ISSUE TITLE
[EN][Object] Table in Kharanos

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#8102]
These scrolls (see the schreenshot) should lay on a table. Table is missing.

Atlantiss screenshot: http://s2.ifotos.pl/img/1png_ahrpxxe.png

http://wow.mmorpg-life.com/quest_images/25724/CaptainTharran_1_WoWScrnShot_113010_024622.jpg

The table should be placed next to Captain Tharran.

http://www.wowhead.com/npc=40950/captain-tharran

**Comment by Malylolek** [comment]
Put wowhead link couse find this place can be very annoying.

**Comment by wtRCH** [comment]
fix pending
