### ISSUE TITLE
[EN][NPC][Icecrown Citadel] Muradin Bronzebeard

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#8105]
NPC Muradin Bronzebeard in Icecrown Citadel (http://www.wowhead.com/npc=37200 I think that's the right id) doesn't have the talk option to trigger the start of Deathbringer Saurfang (http://www.wowhead.com/npc=37813) encounter (dunno about the horde counterpart).

Bildo fix pls

**Comment by Bildo** [comment]
fixed

**Comment by MichaelArchangelo** [comment]
Still bugged. Now he has a talk option, but it's like this:
Me: "I'm ready"
Muradin: "U sure?"
Me: "Yeah"
And when I click the second option nothing happens.

**Comment by krecik88** [comment]
fixed 5281
