### ISSUE TITLE
[EN][Spell][Rogue][Warrior] Throw

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8106]
rogues thrown weapon cast is too long, it should be only 0.5 seconds or lower (depending on haste)
but right now on atlantiss its closer to 1-1,5 seconds which is incredibly frustrating if u want to slow someone with ur thrownweapon poison

warriors thrown is the exact same

http://cata.openwow.com/spell=2764

**Comment by lamaATS** [comment]
Fixed in rev. 5205
