### ISSUE TITLE
[EN][Spell][Mage] Spellsteal

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8107]
if u spellsteal a buff u already have its duration will always be reduced to 2 min or less on atlantiss,
thats wrong

http://wowwiki.wikia.com/wiki/Spellsteal
Patch 2.4.0 (25-Mar-2008): Blink, Slow, and Spellsteal have all had their mana cost reduced, and Spellsteal will no longer overwrite a longer duration buff.

http://cata.openwow.com/spell=30449

**Comment by Malylolek** [comment]
Merge to #7238
