### ISSUE TITLE
[EN][Spell][Mage] Flame Orb vs cloak/block/vanish

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8109]
orb "locks onto" a cloaked rogue when it should fly right through him
ice blocked mages are ignored properly (here u can see what i mean by flying right through)
flame orb doesnt dissapear once it has reached its maximum distance and didnt find anything to lock onto
flame orb breaks vanish when it should not
flame orb should only break regular stealth (which works on atlantiss)

http://cata.openwow.com/spell=82731 flame orb
http://cata.openwow.com/spell=95969 frostfire orb rank1
http://cata.openwow.com/spell=84721 frostfire orb rank2
http://cata.openwow.com/spell=1856 vanish
http://cata.openwow.com/spell=31224 cloak of shadows
http://cata.openwow.com/spell=45438 ice block

proof:
https://www.youtube.com/watch?v=W53drBt6B3E (0:18) orb ignores cloaked rogue
https://www.youtube.com/watch?v=djtKYp5NFKY (9:19) orb ignores blocked mage and disappears once its max range is reached
https://www.youtube.com/watch?v=WLGMp0KMfSo (2:19) rogues vanish isnt broken by orb (also looks like he is not getting slowed by orb?)
https://www.youtube.com/watch?v=kufsJysS8HE&feature=youtu.be&t=1027 
(15:04) rogue vanishes orb hits rogue but vanish doesnt break (this time hes getting the slow debuff so i guess u can get slowed in vanish by orb just not have your vanish broken by it)
(10:11, earlier in same video) frostfire orb disappears after not locking onto anything

**Comment by fluessig** [comment]
not sure if deterrence and ams are supposedto work just like cloak and block

**Comment by Genomnomnomnom** [comment]
bump

**Comment by Genomnomnomnom** [comment]
BUMP

**Comment by Soulywood** [comment]
You can't imagine how frustrating that is when you loose an arena just because the mage got one of your vanish thanks to this bug. Please fix it it's been years now

**Comment by lamaATS** [comment]
Fixed in rev. 5498
