### ISSUE TITLE
[EN][Talent][Mage] Impact spread Ignite

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8110]
if u spread your ignite dot on atlantiss with impact the ignite that was spread shows up on the other mobs as a debuff but doesnt tick for any damage

http://cata.openwow.com/spell=12357 impact
http://cata.openwow.com/spell=12846 ignite
http://cata.openwow.com/spell=2136 fire blast

**Comment by blinkmaster** [comment]
Ìts due to bugged pyromaniac talent which gives pretty much Passive haste whole fight

**Comment by Malylolek** [comment]
Added to #8005
