### ISSUE TITLE
[EN][Spell][Shaman] Earth Shield

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8111]
earth shields healing should happen after the damage was taken which triggered it, not before 

http://cata.openwow.com/spell=974 earth shield

proof:
https://www.youtube.com/watch?v=_CStLA51Q7U (3:32)

prayer of mending and living seed might have the same problem
http://cata.openwow.com/spell=33076 prayer
http://cata.openwow.com/spell=48496 seed rank1
http://cata.openwow.com/spell=48499 seed rank2
http://cata.openwow.com/spell=48500 seed rank3

**Comment by fluessig** [comment]
prayer of mending and living seed might have the same problem

http://cata.openwow.com/spell=33076 prayer
http://cata.openwow.com/spell=48496 seed rank1
http://cata.openwow.com/spell=48499 seed rank2
http://cata.openwow.com/spell=48500 seed rank3

**Comment by Aival94** [comment]
Other bug: https://github.com/Atlantiss/BugTracker/issues/7743

**Comment by Malylolek** [comment]
Added to #7743
