### ISSUE TITLE
[EN][Spell][Rogue] Sapping vanish

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8113]
vanish does not drop combat in pvp right now which makes sapping a vanish impossible,
also dropping combat should occur a little bit before vanishing, thus enabling sapping vanish
its a very small window to be able to sap a vanish
sap completely breaks vanish and stealth (no sitting in stealth ccd)
this ticket is all about pvp, in pve vanishing does not drop combat if someone in the raid is still in combat

http://cata.openwow.com/spell=1856 vanish
http://cata.openwow.com/spell=1784 stealth
http://cata.openwow.com/spell=6770 sap
http://cata.openwow.com/spell=5215 prowl

proof:
https://www.youtube.com/watch?v=GuY7v6ZeDNo (0:07) sap vanish
https://www.youtube.com/watch?v=rOxZmQdfbKw (1:37) vanish drops combat for rogue
https://www.youtube.com/watch?v=Zj3wStRBZZs (0:38) vanish drops combat for rogue
https://www.youtube.com/watch?v=xMhQNzZBeI4 (2:35) vanish drops combat for rogue
(1:10+1:16 samevid) rogue saps vanish

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/228

**Comment by Malylolek** [comment]
Look up :package:
