### ISSUE TITLE
[EN][Battleground][Mage]

### ISSUE THREAD

**Issue by swerc** [Atlantiss/BugTracker#8114]
Nearly every battleground I join after a few minutes I get the problem where I can cast anything. I'll be in the middle of a fight then all I get is "spell not ready yet". I can still mount but every other ability just says "Spell not ready". Including all instant cast abilities. Doesn't matter if i'm in combat or not. As a mage this makes me completely useless. The only way I've found to fix it is to re-log. This only happens during battleground and no one else seems to have had this happen to them. I'm using the Mods Reforgenator, X-Perl, Bartender, and recount.

**Comment by Sayris9876** [comment]
#7440   Stopid arcane mages :D

**Comment by Aival94** [comment]
test if the problem is the same and then either close it or update it better how to reproduce it.

**Comment by swerc** [comment]
Ah, I see. Thanks for providing that Link. I wasn't sure what caused it. Thank you! Hopefully this will actually get fixed soon then.
