### ISSUE TITLE
[PL][Quest][Silverpine Forest] Belmont's Report

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8115]
Quest: http://www.wowhead.com/quest=27056/belmonts-report
NPC: http://www.wowhead.com/npc=44789/deathstalker-commander-belmont

Problem jest taki, że nie idzie oddać questa Lady Sylvanas

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/7608
