### ISSUE TITLE
[EN][NPC]Flying Trainer

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#8118]
I went to the flying trainer to learn the expertise riding skill. After purchasing, i gained the achievement but the expertise riding skill wasn't in my spellbook. I checked again in the trainer skill list but it said " already known ".
Here some screenshots:

![wowscrnshot_082816_215951](https://cloud.githubusercontent.com/assets/11901135/18036480/c293cc62-6d6b-11e6-972e-40851e794589.jpg)
![wowscrnshot_082816_220003](https://cloud.githubusercontent.com/assets/11901135/18036481/c293e7ec-6d6b-11e6-8425-ce0cf9c52f19.jpg)
![wowscrnshot_082816_220009](https://cloud.githubusercontent.com/assets/11901135/18036483/c29b57ca-6d6b-11e6-8384-a00d96e15d54.jpg)
![wowscrnshot_082816_220020](https://cloud.githubusercontent.com/assets/11901135/18036482/c29ad5fc-6d6b-11e6-9667-ae03dced7b3b.jpg)

**Comment by Docholiday-Atlantiss** [comment]
Relog.
