### ISSUE TITLE
[PL][Item][Warlock] Vengeful Gladiator's Dreadweave Hood

### ISSUE THREAD

**Issue by MasterK15** [Atlantiss/BugTracker#812]
Vendor  http://www.wowhead.com/npc=54650 (Kezzik the Striker) Sprzedaje ten item za 1k honoru, lecz item na model http://www.wowhead.com/item=31051 (powinien być granatowy a jest czerwony/// Model heada t6 zamiast t3 pvp) Możliwe że inne heady u tego wendora tez mają zły model.

**Comment by mrkariox** [comment]
Istnieje chociaż cień szansy na poprawienie tego? Napaliłem się na transmog z uzyciem tego heada ;/

**Comment by Kubelecer** [comment]
As of today this bug is still present and kind of annoying

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12987-812-vengeful-gladiators-dreadweave-hood-felweave-cowl-displayid/

**Comment by TranceAccount** [comment]
Fix got accepted.

**Comment by TranceAccount** [comment]
@Piklo Any news?

**Comment by TranceAccount** [comment]
Fix should be live.
