### ISSUE TITLE
[EN][Quest][Firelands] Time Grows Short

### ISSUE THREAD

**Issue by Haddis991** [Atlantiss/BugTracker#8120]
You can not see Kalecgos to complete the quest after you accept, therefore probably making it impossible to complete.

Take Quest then your back in level 70 zone and no more Kalecgos, so this will cause problems when people try to finish quest, therefore making it incomplete-able.

http://cata.openwow.com/quest=29270

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Haddis991** [comment]
updated the quest link

**Comment by Haddis991** [comment]
i rewrote the issue to make it more clear

**Comment by Malylolek** [comment]
@Haddis991 Its propably Bandy not script quest after cinders, first person who can complete this quest will be at next Wednesday 7.09 [25 man 3 weeks ] so he have time and propably doing it now.
