### ISSUE TITLE
[ENG] Steamvault and Underbog Heroic Boss drops bug

### ISSUE THREAD

**Issue by TojataBM** [Atlantiss/BugTracker#8121]
[EN][Quest][Zone] The Steamvault heroic and normal / Underbog Heroic
[EN][NPC]  **Steamvault**: _Mekgineer Steamrigger_ http://www.wowhead.com/npc=17796/mekgineer-steamrigger
**Underbog:** _Hungarfen_ http://www.wowhead.com/npc=17770/hungarfen
[EN][Npc][Drop] **The steamvault** : _Mask of penance_ http://www.wowhead.com/item=27790/mask-of-penance
**The Underbog** : http://www.wowhead.com/item=27748/cassock-of-the-loyal

I think the loot is bugged for those 2 items. Drop rate for them is 14 and 19% . Also Mask of penance drops on normal and heroic dungeon so i repeat this 2 times daily. 
I did tis for over 2 weeks - no drop , still droping same items for these bosses.
I'm not sure if this is bug or im just that unlucky but it's really strange with this high drop rate that is not dropped yet. I' am also having problem with wrist "Virtue Bearers Vambraces http://www.wowhead.com/item=27489/virtue-bearers-vambraces . Could you check if drop rate for those are ok ?

**Comment by Piklo** [comment]
posted fixes at forum:
http://community.atlantiss.eu/index.php?/topic/12047-8121-the-steamvault-boss-loot-tables/
http://community.atlantiss.eu/index.php?/topic/12048-8121-the-underbog-boss-loot-tables/
