### ISSUE TITLE
[EN][Quest][Winterspring] A Cub's Cravings

### ISSUE THREAD

**Issue by mastercho** [Atlantiss/BugTracker#8122]
Shardtooth Meat item is not drop from bears in in north Winterspirng. I spend 2 days farming but no luck on drop. http://www.wowhead.com/quest=29035/a-cubs-cravings#comments

**Comment by Piklo** [comment]
posted fix at forum
http://community.atlantiss.eu/index.php?/topic/11337-item-shardtooth-meat-drop-chance/
