### ISSUE TITLE
[Raid - TBC][NPC] Black Temple - Illidan Stormrage

### ISSUE THREAD

**Issue by mastercho** [Atlantiss/BugTracker#8123]
If we die on Phrase 2 in Illidan Akarama is not back and its stays at back, should be Debugged so if we die at Illidian , we can continue after ress

**Comment by Bildo** [comment]
bt rules

**Comment by mastercho** [comment]
http://wowwiki.wikia.com/wiki/Illidan_Stormrage_(tactics)

here is not mention Akarama get back and never come again for other phrases, also i have played BT since BC so i know what must happen , its not anything to do with BT rules... You must debugged asap

**Comment by Malylolek** [comment]
Bildo Mean bug tracker rules :
https://github.com/Atlantiss/BugTracker/blob/master/README.md
