### ISSUE TITLE
[Not Working]Mounts in Wintergrasp & Argent Tournament

### ISSUE THREAD

**Issue by AmbroBlizzard** [Atlantiss/BugTracker#8124]
I've noticed an ugly bug in Wintergrasp the siege engines can't be mounted. So the horde can't win the battle. Also the mounts from Argent Tournament don't work too....they have the same problem as siege engines from Wintergrasp...they can't be mounted, that way it's impossible to complete the quests from the Argent Tournament to earn the achievements.

**Comment by Bildo** [comment]
read bt rules
