### ISSUE TITLE
[PL][Boss] 3rd boss on Magister's Terrace bugged

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#8129]
Dzień dobry. 
Drzwi do Kaela za trzecim bossem nie otwierają się po ubiciu Priestless. Oczywiście, wedle wskazówki jednego z GMów, biję najpierw mini bossy, a na końcu głównego demona. Mimo to, kiedy boss nie daje dropu, drzwi za nim nie otwierają się. 
Tak się dzieje w większości przypadków, i zaznaczam, że w wersji heroic - na normal nie wiem, czy taki problem występuje (może miałam szczęście).
Bardzo proszę o rozpatrzenie problemu, ponieważ z szatką z kaela można bardzo fajny xmog sobie ułożyć, zależy mi na nim. :) 
Pozdrawiam, Borowka.

**Comment by maslak** [comment]
Dzisiaj tam byłem nie było żadnych problemów. Raczej coś u ciebie.

**Comment by whiskass** [comment]
A mnie za to udało się zrobić jakieś 3 razy na 10,  jedną jak i drugą postacią. Więc nie wiem, co jest nie tak.  :/

**Comment by Malylolek** [comment]
Sprecyzuj bardziej bo nawet nie wiem jak z reprodukować, próbowałem dziś i było ok.

**Comment by whiskass** [comment]
Tak jak w opisie, dochodzę do 3 bossa. Biję najpierw mini-bossy, addy, czy jakkolwiek chcemy to nazwać - te, które stoją obok bosa. Na samym końcu zabijam właściwego bossa. w 80-90% przypadków brama za bossem, do kaela, mi się nie otwiera i dodatkowo wtedy 3 boss nie daje dropu (co akurat nie jest dla mnie istotne). 
Co robię nie tak? Pull? Pullałam zarówno wszystkich na raz jak i po prostu "pojedynczo" i nie było różnicy.
