### ISSUE TITLE
[PL][Azshara][QUEST] Ticker Required

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8131]
NPC: http://www.wowhead.com/npc=36895/sergeant-zelks
Quest: http://www.wowhead.com/quest=14485/ticker-required

Po użyciu flary na runestone'ach nic się nie dzieje, gobliny nie lądują na spadochronach i nie niszczą obiektu tak jak powinno to działać. Z góry uprzedzam, że czytałem komentarz do podobnego ticketa, a także komentarze ze strony private-status.com. Pomimo zastosowania się do porad w nich zawartych nie udało mi się ukończyć tego questa.

Edit: Po restarcie servera także nie działa.

**Comment by Malylolek** [comment]
#6983
