### ISSUE TITLE
[EN][Quest][Achievement] The Purification of Qual'Delar

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#8134]
Quest: http://www.wowhead.com/quest=24596/the-purification-of-queldelar

What doesn't work?
The event doesn't begin when you use the quest item the required place.

Event that should begin: https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by LaveniaGithub** [comment]
Love you, Bildo (=

**Comment by ounagi21** [comment]
Any updates on this issue? Just a few more steps to complete the quest chain =/

**Comment by Bildo** [comment]
I dont have time right now so you wont a see fix in a time (at least not from me)

**Comment by ounagi21** [comment]
Is this ever gonna get fixed? Any progress? Any other assignee? Any information so I know if I should just stop giving a shit and stop waiting?
