### ISSUE TITLE
[PL][Farewell, Minnow][Azshara][Item] Faded Wizard Hat

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8135]
Quest: http://www.wowhead.com/quest=14392/farewell-minnow
Item: http://www.wowhead.com/item=53057/faded-wizard-hat

Item który dostajemy z questa nie działa tak jak powinien, tzn. nie zmienia losowo wyglądu naszego bohatera. Po jego użyciu nic się nie dzieje.

Pozdrawiam
Tinu

**Comment by Malylolek** [comment]
#3844
