### ISSUE TITLE
[EN][Raid] boss spell dmg and hp

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8138]
bosses on  FL normal have hp values from hc, same goes from abilitie timings and dmg are from hc not normal

**Comment by Jenovas** [comment]
Closing report. I will not be checking every boss now and every spell.
Please create a report where you list out everything that is wrong.
Cheers.

**Comment by stanq87** [comment]
====================
Beth'tilac  
in 10-man normal difficulty: 17.8M;
in 10-man heroic difficulty: 27.9M
-------------------
skada shows 27.74 +/-
====================
Alysrazor
in 10-man normal difficulty: 38.6M;
in 10-man heroic difficulty: 65M;
------------------------
skada shows 68.72
====================
Baleroc 
in 10-man normal difficulty: 31.5M;
in 10-man heroic difficulty: 52.5M;
---------------
skada shows 56,1
====================
Lord Rhyolith
in 10-man normal difficulty: 12.7M;
in 10-man heroic difficulty: 19.5M;
----------------------------
shada shows Rfoot 9,8  Lfoot 5,46 and lord 5,32
====================
Shannox
in 10-man normal difficulty: 20.4M health;
in 10-man heroic difficulty: 28.6M health;
On normal mode, Rageface and Riplimb have 8.2M health each in
On heroic mode, Riplimb has 4.1M health , while Rageface has 36.4M
-----------------------------------------
shannox 32,03       rageface 14,12      13,74
====================

**Comment by stanq87** [comment]
spells where off, and boss skill dmg where to big but its hared to show from shada, and i didnt record the raid

**Comment by stanq87** [comment]
i didnt paste here hp from majrodomo , because we had a wipe and the raid ended but we did 53M dmg on him and he had alot more hp 
in 10-man normal difficulty: 38.2M;
in 10-man heroic difficulty: 105M;

**Comment by stanq87** [comment]
ps we know that spells timers where off because our dbm   where usless on  bosses
