### ISSUE TITLE
[PL][Quest]A Vision of the Past Quest 

### ISSUE THREAD

**Issue by Berlin1993** [Atlantiss/BugTracker#8140]
Podczas użycia Q iteamu przy wejściu w instancji nasza postać "wędruje" na miejsce eventu jednak ten się w ogóle nie rozpoczyna oraz dodatkowo nasza postać zostaje zablokowana i nic nie możemy zrobić nawet po wyłączeniu i włączeniu gry gdy wyjdziemy z insty dostajemy DC . A po zalogowaniu dalej nie widzimy nic i nie możemy nic zrobić . Jest to ostatni quest do zrobienia loremastera w Westfall. Bardzo proszę o naprawę.
Pozdrawiam serdecznie :)

Poniżej prawidłowe działanie Questa
----> https://www.youtube.com/watch?v=SaKEUK4Nuoo

Link do Questa
---->http://www.wowhead.com/quest=26320/a-vision-of-the-past

**Comment by pelekon** [comment]
Duplicate #1622
