### ISSUE TITLE
[EN][Quest][Silverpine Forest]On Her Majesty's Secret Service

### ISSUE THREAD

**Issue by Niriam** [Atlantiss/BugTracker#8141]
You actually can't even start that quest and continue the questchain. Also, the trio of Forsaken keeps following you and you can't do anything about it. I think it's quite important and should be fixed (these are last not-working quests in Silverpine Forest).

http://www.wowhead.com/quest=27594/on-her-majestys-secret-service

**Comment by Niriam** [comment]
Important fact also connected to the trio of Forsaken - you can't drop Partially Digested Head (http://www.wowhead.com/item=61505/partially-digested-head) if you already finished other quests from Lord Godfrey which heads to unability of completing this quest: http://www.wowhead.com/quest=27574/i-never-forget-a-face

**Comment by pelekon** [comment]
Duplicate #391

**Comment by Fuzzypunk** [comment]
Quest: "On Her Majesty's Secret Service" still doesn't work 

Lord Godfrey doesn't give this quest ;(

**Comment by worloq** [comment]
On Her Majesty's Secret Service-- still Lord Godfrey doesn't give this quest
