### ISSUE TITLE
[EN][NPC] Haggard War Veteran

### ISSUE THREAD

**Issue by ounagi21** [Atlantiss/BugTracker#8142]
http://www.wowhead.com/npc=19684/haggard-war-veteran

This NPC is missing from the location as stated in WoWHead. He is required to start the quest [A'dal].
http://www.wowhead.com/quest=10210/adal

**Comment by Malylolek** [comment]
It should exist

**Comment by vanter1282** [comment]
Found the NPC patrolling on the north entrance bridge to Shattrath city coords 61,11. And gives the Quest 10210 A'dal
