### ISSUE TITLE
[EN][Spell][Rogue] Combat Readiness

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8143]
combat readiness should cancel after 10 seconds of no incoming melee swings
this works right now but what doesnt work is if u use combat readiness and never got hit it lasts the full 20 seconds which is wrong

http://cata.openwow.com/spell=74001

**Comment by kadi2** [comment]
It's supposed to work this way. You may not undestand anything from this report but there is a video including that situation. https://github.com/Atlantiss/BugTracker/issues/1389

**Comment by fluessig** [comment]
im a rogue main and even i find this stupid, but okay
found better proof btw
https://www.youtube.com/watch?v=Gf8iY-mVNCk (3:29)
