### ISSUE TITLE
[EN][Talent][Druid] Infected Wounds

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8144]
infected wounds lasts too long in pvp (12 seconds on atlantiss)
it should only last for 8 seconds in pvp

http://cata.openwow.com/spell=48483 rank1
http://cata.openwow.com/spell=48484 rank2

proof:
https://www.youtube.com/watch?v=fL6pzResomQ (8:55) the mage is affected by infected wounds and they only last for 8 seconds total

**Comment by kadi2** [comment]
@fluessig Most of the slows should have shorter duration in PvP, you can include Crippling Poison to this report aswell.

**Comment by lamaATS** [comment]
Fixed in rev. 5205
