### ISSUE TITLE
[EN][Spell][Warlock] Curse of Tongues

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8145]
curse of tongues should only last 10 seconds in pvp
on atlantiss it lasts 12 seconds

http://cata.openwow.com/spell=1714

proof:
https://www.youtube.com/watch?v=fL6pzResomQ (1:06) curse of tongues is applied 1:11 the curse is half way done

**Comment by lamaATS** [comment]
Fixed in rev. 5205

**Comment by kadi2** [comment]
not sure if it's correct, just found this https://youtu.be/wyubPXb_af4?t=2m26s . Check the dates.
