### ISSUE TITLE
[EN][Talent][Warlock] Curse of Exhaustion

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8146]
curse of exhaustion should only last 10 seconds in pvp
on atlantiss it lasts 30 seconds

http://cata.openwow.com/spell=18223

proof:
https://www.youtube.com/watch?v=PAM2YYf4Au0 (3:02) curse of exh lasts until 3:12 on rogue

**Comment by lamaATS** [comment]
Fixed in rev. 5205

**Comment by kadi2** [comment]
https://youtu.be/OleQNQcIf8M?t=11m19s some better looking clip

**Comment by lamaATS** [comment]
Corrected in rev. 5206
