### ISSUE TITLE
[EN][Spell][Mage] Scorch

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8147]
u cannot shatter combo with scorch on atlantiss (shatter combo describes two spells benefitting from the increased crit rate on a frozen target, when cast at the same time)
u can test this by nova'ing a lvl 60 testdummy and casting scorch + icelance (icelances dmg is more if it benefitted from the root)
there should be a slight delay on scorch hitting the target so another instant cast spell can benefit from the nova

http://cata.openwow.com/spell=2948

proof:
https://www.youtube.com/watch?v=dNQBbrdDkWM (19:56)

**Comment by blinkmaster** [comment]
Same goes with frost nova sheep for example. I wish luck, id love to have it working like on retail but we already tried reporting this with Kadi2 and the answer was they wont introduce that here

**Comment by Jenovas** [comment]
We will not be introducing the 500ms Blizzard lag.
