### ISSUE TITLE
[EN][Spell][Rogue] Stealth

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8148]
if u enter stealth on atlantiss u disjoint projectiles that were flying at u (means that they do nothing to u when they hit u)
stealth and shadowmeld (nightelf racial) are actually working exactly opposite of how they should
smeld should disjoint
stealth/prowl should not

shadowmeld works as vanish immune worked in wotlk
u can even shadowmeld immune instant aoe cc like priest fear or any spell rly for that matter because u are immune for a short period when first entering shadowmeld
disjointing spells works even if ur shadowmeld ends up breaking before the spell reaches u as long as u melded once it was flying at you

http://cata.openwow.com/spell=1784 stealth
http://cata.openwow.com/spell=5215 prowl
http://cata.openwow.com/spell=58984 shadowmeld

proof:
https://www.youtube.com/watch?v=IVwC63sxIpw#t=1.97902 (1:50) boomkin disjoints chaosbolt
https://www.youtube.com/watch?v=C2kMEZhTjpk (1:20) warrior shadowmeld immunes throwdown
https://www.youtube.com/watch?v=6U4zveFkK7A (6:03) hunter shadowmeld immunes cheapshot (weirdly find weakness still applies)

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/263
