### ISSUE TITLE
[EN][Talent][Mage] Hot Streak

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8150]
hot streak proc is not lost if u miss with the pyroblast (for example if u cast pyro into a cloak of shadows of a rogue)
this is incorrect, u always lose hot streak once the pyro leaves ur hands wether or not the pyro misses or does no damage

http://cata.openwow.com/spell=11366 pyroblast (this link is weird cus pyro cast time is 3.5 and not 5)
http://cata.openwow.com/spell=92315 pyroblast! (this is the pyro u shoot when HS is up)
http://cata.openwow.com/spell=44445 hot streak
http://cata.openwow.com/spell=44446 imp hs rank1
http://cata.openwow.com/spell=44448 imp hs rank2

**Comment by lamaATS** [comment]
No it shouldn't because you got already benefit (spell was without cast time) and as You said Cloak of Shadows can be used when Pyroblast was already lunched so You would chance to cast two Pyroblasts on one buff.
If I'm wrong give any proof.

**Comment by lamaATS** [comment]
Sorry for my miss misunderstood because I skip first `not`.
I have fix for it already. (You can test it on PTR)

**Comment by lamaATS** [comment]
Fixed in rev. 5207
