### ISSUE TITLE
[EN][Spell][Druid] Tranquility

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8151]
tranquility should heal the most injured (lowest health %) nearby party/raid members but it just heals random targets who can even be at full health -.-

Divine hymn of priests should also heal the most injured targets
and chainheal of shaman is also a so called smart-heal prioritizing low health % targets
im guessing these dont work as well but i only tested tranqu

http://cata.openwow.com/spell=740 tranquility
http://cata.openwow.com/spell=64843 divine hymn
http://cata.openwow.com/spell=1064 chain heal

proof:
http://wowwiki.wikia.com/wiki/Chain_Heal
"Chain Heal is a 'smart' heal and always jumps to the eligible target with the largest health deficit in range."

**Comment by Jenovas** [comment]
Fixed rev 5231
