### ISSUE TITLE
[EN][NPC][Undercity] Neller Fayne

### ISSUE THREAD

**Issue by Grumpyelf** [Atlantiss/BugTracker#8152]
Jewelcrafting trainer in the Undercity is not spawned.
I have checked this a couple of times, including after server resets, he's just not there.

http://www.wowhead.com/npc=52587/neller-fayne

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11601-8152npcundercity-neller-fayne/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
