### ISSUE TITLE
[EN][Talent][Mage] Ignite munching

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8162]
u cannot implement ignite munching based on assumptions as to how it works.
theres examples of it not happening on retail, so u have to find out how often it happened on retail which i guess u dont have any data of (if u do have data id like to see it).
if u dont have reliable data of how often ignite munching occured, u do not implement it.
right now on atlantiss if 2 crits happen at once, one of the ignites is always 100% munched -.-

example1:
http://us.battle.net/forums/en/wow/topic/3341769380
"16312(scorch crit)+ 14411(fireblast crit ) = 30723 (total damage)
30723 x 0.4 (40%) = 12289 x 1.26 (mastery 26%) =
15484 (predicted ignite)
5161 (predicted ignite dot .. 15484/3)

I get 5166 per ignite dot, 3 times (5166x3 = 12552)
but that was correct just 3 times... then all others try i get a 25-33% damage loss (munching)"
_______________________________________________________________________________________________________

example2:
https://www.youtube.com/watch?v=u7W75EXoev4 (12:18)
pyro and fireball crits happening at the same time creating a 6 second ignite
22645 fireball + 26749 pyro=7191 ignite
even with only base mastery, ignite should have ticked for more dmg
49394*0.488 = 24104.272/3 = 8034.7573 ignite ticks

if we assume that one crit is entirely munched, we get
7191* 3 =21573 ignite
21573/26749=0.806497 ignite factor
0.8065/0.4=201.625   
this means u need 101.625% mastery
we take off 22%baseline mastery
so for this to be only one crit he would have needed at least 79.625% mastery 
79.625%mastery/2.8=28.4375 extra mastery pts
28.4375pts*179.4258=5102.422 mastery rating
i think its safe to assume he couldnt have had this much mastery, especially because in the video he has darkmoon card volcano as one of his trinkets and u do not see a mastery proc trinket proc
_______________________________________________________________________________________________________

example3:
https://www.youtube.com/watch?v=3cLSildAono
(0:13) 2 crits at once -> 6 sec ignite
(0:36) 2 crits at once -> 6 sec ignite
_______________________________________________________________________________________________________

example4:
https://www.youtube.com/watch?v=OQkaysuV9WM
(8:40) fireball and pyro crit thrown out at about the same exact time (if u did that on atlantiss u would only get a 4 second ignite) ->6 sec ignite
fireball crit for 60300 
combustionhelperaddon shows ignite for 34634
ignite factor: 34634 / 60300 = 0.574362
when pyro crits for 75969 ignite is recalculated in combhelper to 73188
taking the previous ignite off that is:  38554 ignite just from the 2nd crit
pyrocrit 75969 * ignite factor 0.574362 = 43633 expected ignite
this shows that ignite munching does exist and eats a bit of dmg but not even nearly as much as u pretend on atlantiss right now by eating the entire 2nd ignite
ignite in the video 24396dps
on atlantiss dps of same ignite would be only 21816dps
(this is only considering ignite for combustion as dps, the dps loss of the 2nd ignite not applying at all is insane)

**Comment by blinkmaster** [comment]
I agree. I pointed out several times in previous ignite munching reports that it wasnt 100%. Well it went in anyway

**Comment by lamaATS** [comment]
Fixed in rev. 5205
