### ISSUE TITLE
[EN][Achievement] Straw That Broke the Camel's back

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#8163]
We are not able to enter a camel before Earthrager Path in Halls of Origination ... We tried all way like clearing every trash, checked if camels are usable during the boss fight, teleported out-in cuz of combat bug but still cant enter. Many other players complaining about its bug at the world
Achievement link: http://www.wowhead.com/achievement=5294/straw-that-broke-the-camels-back#comments
I couldnt find the link to the camels
Its also an achievement of Glory of the Cataclysm Hero and many people only missing this one achiev!

**Comment by Luna-maria** [comment]
I got this achievement a few weeks ago, it works but is a bit tricky to complete as the camels tend to die pretty quick

**Comment by Malylolek** [comment]
Just you can't enter camel right ? Or i misunderstand you ?

**Comment by Luna-maria** [comment]
I could and so could the rest of my group. But something might have changed since then idk

**Comment by trolloh** [comment]
We cant even enter the camel. We tried every way is possible.. like get the camel to lowhealth, still couldnt enter.

**Comment by Malylolek** [comment]
This what i need to know :P will fix it soon.

**Comment by Malylolek** [comment]
Fixed in rev. [5182](http://atlantiss.eu/changelog#rev5182)
