### ISSUE TITLE
[EN] [QUEST] [Returne Fire] [Cataclysm]

### ISSUE THREAD

**Issue by cavalzeratu** [Atlantiss/BugTracker#8165]
Quest Returne Fire, its not possible to enter the Astranaar Thrower to shot the Watch Wing Riders
Location: Astranaar

**Comment by Aival94** [comment]
Give links for the quest

**Comment by Malylolek** [comment]
1. readme before just post something 
2. i fix it here rev. [5164](http://atlantiss.eu/changelog#rev5164)
