### ISSUE TITLE
[PL][The Hinterlands][NPC] Eliza Darkgrin

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8166]
NPC: http://www.wowhead.com/npc=42622/eliza-darkgrin#starts
Quest: http://www.wowhead.com/quest=26368/venomous-secrets

NPC nie daje nam questa Venomous Secrets po zrobieniu poprzednich questów, przez co nie da się go ukończyć.

**Comment by Piklo** [comment]
still bugged?

**Comment by Piklo** [comment]
https://community.atlantiss.eu/index.php?/topic/14824-questshorde-hinterlands/ fix by tomatosz

**Comment by Jenovas** [comment]
Fix in rev 5538
