### ISSUE TITLE
[EN][GAME MECHANICS] "Chance on hit" weapons.

### ISSUE THREAD

**Issue by Chromiell** [Atlantiss/BugTracker#8171]
Hey guys,
i just want to report a bug that affects (from what i know) every weapon with a chance on hit effect. Basically the issue is that the chance on hit effect can never proc, regardless of the number of times you hit a target, it will NEVER proc once.
I've tested this effect with a bunch of Vanilla weapons that happen to have a chance on hit effect and the result was always the same, the effect never goes off.
In the screenshot below i hit the target dummy for 100 times with my Sulfuras, Hand of Ragnaros, this weapon has a chance to shoot a fireball at the enemy and the proc should happen quite frequently, needless to say it didn't proc once.

http://imgur.com/a/gu4vs

Just to be more sure i even brought it to some Battlegrounds, i played like 4 different bgs and it haven't procced a single time, hence my conclusion that the chance on hit is bugged (i also did more tests with)  Poison-Tipped Bone Spear which also happens to have a chance on hit effect as well as with Vanilla versiona of the weapon called Shadowstrike/Thunderstrike (which is supposed to have a lifeleech chance on hit).

Now i know that this is not a high priority bug, but since i (and i think many other players) invested a ton of time farming mats for old school legendaries i would at least see these weapons fully working (I'm referring to Sulfuras, Thunderfury, Warglaives of Azzinoth etc.).

**Comment by TranceAccount** [comment]
I am currently also testing this, and I can quite sure say too that it is bugged. Probably because the Spellppmrate is missing in the item_template.

**Comment by henkka90** [comment]
Follow the template given or close this report 

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by TranceAccount** [comment]
This report describes that the bug is occuring for all chance on hit items, and will therefore remain opened.

**Comment by TranceAccount** [comment]
Fixed in rev. 5855.
