### ISSUE TITLE
[PL][Firelands][Alysrazor] Brak trashu

### ISSUE THREAD

**Issue by PervertsHentai** [Atlantiss/BugTracker#8173]
Witam przed bossem Alysrazor brakuje do niej najbardziej upierdliwego trashu Tj. Powinny stać Harbringer of Flame które trzymają do czasu zaatakowania ich Blazing Monstrosity. Blazing Monstrosity powinny ciągle pluć "kulami ognia" które zadają obrażenia także mobą i dzięki nim można by zbijać Egg Pile oraz trash. Po stronach powinny stać Egg Pile z których powinny wychodzić małe moby (niestety nazwy już nie pamiętam)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/6031
