### ISSUE TITLE
[EN][Raid][Firelands]

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#8177]
There was an uptade that increased HP and Dmg of bosses on FL HC, that's cool, but unfortunately HP and DMG of FL norm bosses was improved too, what is absolutely pointless and unblizzlike. It was probably done by mistake, so please fix it as fast as possible.

**Comment by Aival94** [comment]
Is already known by the devs so no point reporting it. The buff is 20% and is a custom buff from the devs,
