### ISSUE TITLE
[PL] [Achievements] Changing achievements after refraction.

### ISSUE THREAD

**Issue by maslak** [Atlantiss/BugTracker#8178]
Ally->Horda, w drugą stronę za pewne jest podobnie.
Po zmianie frakcji brakuję lub w dalszym ciągu jest wiele takich, których nie powinno być bo są przynależne tylko do jednej frakcji jak np achiev za gotowanie, łowienie itp. Brakuje również wielu achiev za pvp takich jak Master Of ...[dany bg][nie ma ich w zakładkach odpowiednich bg]. Brakuje Hail to the Chef  oraz Accomplished Angler[nie ma ich w zakładce cooking i fishing].  To te widoczne na pierwszy rzut oka.
Jednym słowem achievementy po zmianie frakcji są totalnie popsute. Pisałem ticketa, miałem pisać tu.

**Comment by Malylolek** [comment]
Napisz ID acivmentów po stronie Hordy i jaki powinnien być zamienik po stronie Ally, wtedy ktoś to szybko poprawi.

**Comment by maslak** [comment]
Pozostały po stronie hordy ,zaliczone podczas grania postaci w ally
**Achiev za gotowanie**
Let's Do Lunch: Stormwind - http://www.wowhead.com/achievement=5474/lets-do-lunch-stormwind - 5474
Let's Do Lunch: Ironforge - http://www.wowhead.com/achievement=5841/lets-do-lunch-ironforge - 5841
Let's Do Lunch: Darnassus - http://www.wowhead.com/achievement=5842/lets-do-lunch-darnassus - 5842
Wszystkie 3 A Bunch of Lunch - http://www.wowhead.com/achievement=5845/a-bunch-of-lunch - 5845
**Po stronie hordy trzeba wszystko od nowa wbijać:**
Let's Do Lunch: Orgrimmar - http://www.wowhead.com/achievement=5475/lets-do-lunch-orgrimmar - 5475
Let's Do Lunch: Undercity - http://www.wowhead.com/achievement=5844/lets-do-lunch-undercity - 5844
Let's Do Lunch: Thunder Bluff - http://www.wowhead.com/achievement=5843/lets-do-lunch-thunder-bluff - 5843



**Achiev za łowienie rybek**
Fish or Cut Bait: Stormwind - http://www.wowhead.com/achievement=5476/fish-or-cut-bait-stormwind - 5476
Fish or Cut Bait: Darnassus - http://www.wowhead.com/achievement=5848/fish-or-cut-bait-darnassus - 5848
Fish or Cut Bait: Ironforge - http://www.wowhead.com/achievement=5847/fish-or-cut-bait-ironforge - 5847
Wszystkie 3 Gone Fishin' -  http://www.wowhead.com/achievement=5851/gone-fishin - 5851
**Po stronie hordy trzeba wszystko od nowa wbijać:**
Fish or Cut Bait: Orgrimmar - http://www.wowhead.com/achievement=5477/fish-or-cut-bait-orgrimmar - 5477
Fish or Cut Bait: Undercity - http://www.wowhead.com/achievement=5850/fish-or-cut-bait-undercity - 5850
Fish or Cut Bait: Thunder Bluff - http://www.wowhead.com/achievement=5849/fish-or-cut-bait-thunder-bluff - 5849


**Nie ma następujących achiev po stronie hordy[brak ich w ogóle] Nie zostały zaliczone postacią w frakcji ally:**
Accomplished Angler - http://www.wowhead.com/achievement=1516/accomplished-angler - 1516
Hail to the Chef - http://www.wowhead.com/achievement=1563/hail-to-the-chef - 1563
Master of Alterac Valley - http://www.wowhead.com/achievement=1167/master-of-alterac-valley - 1167
Master of Twin Peaks - http://www.wowhead.com/achievement=5223/master-of-twin-peaks - 5223

**Comment by maslak** [comment]
bump

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/8534
