### ISSUE TITLE
[EN][Raid][Firelands] Majordomo Staghelm HC - Concentration

### ISSUE THREAD

**Issue by lamaze** [Atlantiss/BugTracker#8179]
Tonight I have been trying Majordomo on PTR with my guild, and as demonology warlock I've noticed that my pets are not affected by dmg increase from Concentration buff (they are not taking any damage). I don't know how it should work, so i'm asking if this is normal or it's a bug. Thanks for answers :)

**Comment by Aival94** [comment]
The controllable pets should get the buff but the not controllable should not but if you swap pet while you have the 100% buff your new pet will not receive this buff(i mean that the pets that are during the time of the 100% will receive it and not all your pets all the time as far as you have the buff).

http://www.mmo-champion.com/threads/968672-Majordomo-10HC-Damage-buff

**Comment by lamaze** [comment]
My felhunter and felguard were doing normal dmg (they didnt get buffed) , doomguard and fiery imp as well... i think that even if i swap pet during encounter / or summon non controllable pets like doomguard they should start gathering buff from the moment i've summoned them... am i right?

**Comment by Aival94** [comment]
As i said for your Controllable only pets to get the buff they need to be spawned before your reach 100% buff. Rest do not receive the buff and rest of the situations as well.

So if you spawn a controllable pet when you have 90% it will get the 100% when you get it. They get only the the x% buff from you when it become active as far as i understand and what i find in the link i gave.

"Example:
You are at 90% concentration, and felguard is out.
Pop all CDs, including DS:FG, and petswap felhunter before you reach 100% concentration.
Felhunter will receive legendary concentration buff when you reach 100% concentration.

Example 2:
You are at 100% concentration, and felhunter is out, and MWC just went off CD.
You hardcast a felguard out, pursuit+felstorm, and pop your CDs. After which you do a soulburn petswap and get your felhunter out.
Note: All the while, you are at 100% concentration while performing the above.
This way, your felhunter will NOT get any legendary concentration buff until your concentration bar resets."

**Comment by Malylolek** [comment]
Can you post SIMPLE how should work and how it work here #8036 I will bless :)

**Comment by Amerigowarlock** [comment]
Bump ! Pets do not benefit at all from Concentration buff. They should benefit from it regardless of any other factor.

**Comment by Aival94** [comment]
The none Guardian pets should get the Concetration buff when you get it, not all of them.

And they should be summoned before you get the Concetration buff(Every 25%) to get it. If for example you summon your controllable pet after you get 50% it will get the 75% buff when you get it and not the 50% while you have it and if you summon it after you get 100% it will not receive any buff till you lose your buff(concetration) and retake it again.

**Comment by Amerigowarlock** [comment]
I'm not quite sure what you mean. Are you saying this is how it should behave, or how it behaves right now ? Because all i've seen so far is no buffs at all on pets

**Comment by Aival94** [comment]
I just said that not all pets should get it and then told how it should work.

Here nor the pets that should get neither the one that should not get it at all so is still a bug.

**Comment by Amerigowarlock** [comment]
https://www.youtube.com/watch?v=l-owGgl-jcc

Here's a video of the fight from demolock pov. 
You can see the pets buffs above the player's unit frame.

As you can see, the concentration buff is applied to the pet everytime the player gets it, may it be 25, 50, 75 or 100 concentration buff. It also fades from the pet as soon as the player loses it.

Guardian pets such as Doomguards do not get the buff however.

**Comment by Amerigowarlock** [comment]
How is this not confirmed yet ? high priority anyone ?

**Comment by lamaze** [comment]
Did majo every week since FL HC was released, my pet is still not getting any buff, and as demonology warlock its a pain.

**Comment by Amerigowarlock** [comment]
4 months, still no fixed.
What's going on ?
