### ISSUE TITLE
[EN][NPC][Dustwallow Marsh] Raedra Windhammer

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/BugTracker#8181]
Raedra Windhammer, shaman trainer is missing.
Added in patch 4.2, should be inside inn .
http://www.wowhead.com/npc=53405/raedra-windhammer#comments

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11622-8181npcdustwallow-marsh-raedra-windhammer/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
