### ISSUE TITLE
[EN][Raid][Firelands] Alysrazor HC

### ISSUE THREAD

**Issue by Dolmio1** [Atlantiss/BugTracker#8187]
Hatchlings cast a spell called "Gushing Wound" which doesn't get removed when target falls below 50% like it's supposed to.

http://www.wowhead.com/spell=100024/gushing-wound

**Comment by anxanas** [comment]
Read changelog rev. 5174 http://atlantiss.eu/changelog

**Comment by Dolmio1** [comment]
It's still broken. They released the raid without deploying the listed fixes. Gushing wound is broken at current moment.

**Comment by Psychobird7** [comment]
Can confirm. Gushing wound lasted the full minute duration on both tanks and requires absurd amounts of healing to keep up with or even survive.

**Comment by LaveniaGithub** [comment]
Confirmed.
