### ISSUE TITLE
[EN][NPC] Valor Vendors (A/H)

### ISSUE THREAD

**Issue by sunshitwowsucks** [Atlantiss/BugTracker#8188]
they do not have heroic gear in them, for set pieces, for helm, shoulders, chest, gloves, legs.

you should be able to redeem your tier piece with a heroic token, dropped from FL to get a heroic tier piece.

**Comment by Piklo** [comment]
wowhead links to valor vendors?

**Comment by sunshitwowsucks** [comment]
http://www.wowhead.com/npc=44245/faldren-tillsdale
http://www.wowhead.com/npc=46556/jamusvaz
