### ISSUE TITLE
[EN][Quest][Dragonblight] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by karhima** [Atlantiss/BugTracker#8190]
As mentionend here [EN][Quest][Dragonblight] Flight of the Wintergarde Defender #2437 in the last comment after the issue had been closed, the gryphon cannot be mounted and so the quest cannot be completed.

Link to quest again: http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender

**Comment by Malylolek** [comment]
Gimmie ID of this gryphon pls so will fix it soon.

**Comment by karhima** [comment]
Sorry, how do I see it's ID?

**Comment by Malylolek** [comment]
If you dont know, its okey. I will find it at night. Dont bother yourself

**Comment by karhima** [comment]
http://www.wowhead.com/npc=27258/wintergarde-gryphon#summoned-by
ID = 27258

**Comment by Malylolek** [comment]
Fixed in rev. [5182](http://atlantiss.eu/changelog#rev5182)
