### ISSUE TITLE
[EN][Item] Heroic Apparatus of Khaz'goroth

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8192]
Heroic Apparatus of Khaz'goroth currently does not grant Blessing of the Shaper upon activation.
When AoK gets activated, it goes on cooldown but doesn't grant a stat buff and does not consume Titanic Power stacks.

**Comment by sunshitwowsucks** [comment]
http://www.wowhead.com/spell=96934/blessing-of-khazgoroth#comments works (used on norm)

http://www.wowhead.com/spell=97127/blessing-of-khazgoroth#changelog does not work (hc trink)

plz fix

**Comment by Madwag** [comment]
Bump
