### ISSUE TITLE
[EN][NPC] Pogeyan, Tsul'Kalu

### ISSUE THREAD

**Issue by cubson** [Atlantiss/BugTracker#8194]
Pogeyan is a cat NPC. But if you tame Pogeyan, he acts as a wolf.
Same thing with Tsul'Kalu. Tsul'Kalu is a gorilla, but acts as a wolf after taming.

http://s2.ifotos.pl/img/Clipboard_aherphr.jpg

http://www.wowhead.com/npc=51663/pogeyan
http://www.wowhead.com/npc=51661/tsulkalu

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/11471-8194npc-pogeyan-tsulkalu/

**Comment by Navedonar** [comment]
fixed

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists.
