### ISSUE TITLE
[EN][NPC][Darkshore] Corrupted Blackwood

### ISSUE THREAD

**Issue by Drainerzz** [Atlantiss/BugTracker#8195]
While doing quest Cleansing the Afflicted (http://www.wowhead.com/quest=13545/cleansing-the-afflicted) I noticed that Corrupted Blackwood tend to not loose aggro and follow you forever. I'm providing a picture of one already after cleansing. This one after cleansing should disappear while he started to follow me and attack and I couldn't attack him back. Others (pre cleanse) also follow you forever but those are killable. Some screenshots: 
![screenshot from 2016-09-08 09 31 15](https://cloud.githubusercontent.com/assets/22038684/18340901/cea1e158-75a7-11e6-970d-daf2f5ae06fb.png)
![screenshot from 2016-09-08 09 31 20](https://cloud.githubusercontent.com/assets/22038684/18340900/cea1199e-75a7-11e6-892e-0f866c5ab6aa.png)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3935
