### ISSUE TITLE
[EN][Raid][Firelands] Ragnaros HC

### ISSUE THREAD

**Issue by Dolmio1** [Atlantiss/BugTracker#8197]
Hello, listing multiple bugs here...
we're the guild "dock me a recharge mate"

Main core bug: server crash issues.
how to reproduce: sometimes when you wipe and have adds/meteors up, they will stay alive until you pull the next time. dont think the small adds crash the server but its a bug anyways and they shouldnt stay there, what crashes the server is pulling the boss with meteor up, meteor takes a target and server instantly crashes.

Other bugs:
-there is one scenario in phase transition that hammer lands on an add and it results in an instant wipe. (not blizzlike positions on adds or hammer not sure which)
-add positions are not very blizzlike either
-sulfuron smash and lava waves have a weird delay (minor bug)
-adds stay alive after wiping

another non related bug to ragnaros, after a server crash when you login before the leader you get ported to your HS location.

**Comment by Psychobird7** [comment]
"Other bugs: [...]"          

Can confirm all of those.   
Video links available if you need them.              

To add on this, we've had an instance of the hammer coming down on the platform without ANY Sons spawning. (resulted in a wipe through Supernova after the 45s T2 timer was over)

**Comment by Jenovas** [comment]
> To add on this, we've had an instance of the hammer coming down on the platform without ANY Sons spawning. (resulted in a wipe through Supernova after the 45s T2 timer was over)

> -adds stay alive after wiping

Should be fixed after next update. So the crash with meteors should also disappear.
