### ISSUE TITLE
Warrior Double Jump

### ISSUE THREAD

**Issue by Beodun** [Atlantiss/BugTracker#8198]
Class related bug : Warrior
Spec : Arms

There is a bug on the Arms warrior where if you use Mortal Strike and jump you can perform a double jump.

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by sunshitwowsucks** [comment]
when atlantiss updated to legion, double jumps were added and buggy as fk :(

**Comment by TranceAccount** [comment]
Wtf?
