### ISSUE TITLE
[EN][NPC] Booty Bay Bruiser

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#8199]
Booty Bay bruiser in STV (http://www.wowhead.com/npc=4624) should continue to give Bloodsail Buccaneers reputation when killed after you reach Revered status, currently it stops after Honored.

**Comment by TranceAccount** [comment]
#4130

**Comment by TranceAccount** [comment]
Fixed in rev. 5849.
