### ISSUE TITLE
[EN][Items] FL Heroic trinkets

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8201]
Hi! This is to followup on the heroic Apparatus ticket that was incomplete. (that I closed because it is now irrelevant)            

This is going to cover the item IDs and spell IDs for every heroic FL trinket, in no particular order, as I assume most of them are not fully functional.              

Spidersilk Spindle (itemID 69138) uses Loom of Fate (spellID 97129). Absorb value is 19283, and uses the same mechanic as the normal Spindle.
Item: http://www.wowhead.com/item=69138
Loom of Fate: http://www.wowhead.com/spell=97129

Eye of Blazing Power (itemID 69149) uses Blaze of Life (spellID 97136). 
Item: http://www.wowhead.com/item=69149
Blaze of Life: http://www.wowhead.com/spell=97136

Necromantic Focus (itemID 69139) provides Soul Fragment (spellID 97131), which stacks 5 times.
Item: http://www.wowhead.com/item=69139
Soul Fragment: http://www.wowhead.com/spell=97131

The Hungerer (itemID 97126) uses Devour (spellID 97125).
Item: http://www.wowhead.com/item=69112
Devour: http://www.wowhead.com/spell=97125

Jaws of Defeat (itemID 69111) uses Victory (spellID 97121) which grants the buff Victorious (spellID 97120), stacking up to 10 times. (same mechanic as the normal one)
Item: http://www.wowhead.com/item=69111
Victory: http://www.wowhead.com/spell=97121 
Victorious: http://www.wowhead.com/spell=97120

Vessel of Acceleration (itemID 69167) grants Accelerated (spellID 97142) which stacks up to 5 times.
Item: http://www.wowhead.com/item=69167
Accelerated: http://www.wowhead.com/spell=97142

Matrix Restabilizer (itemID 69150) uses Matrix Restabilizer (spellID 97138) and grants the buff Matrix Restabilized, in three different versions (spellIDs  97139 for Haste; 97140 for Crit; 97141 for Mastery).
Item: http://www.wowhead.com/item=69150
Spell: http://www.wowhead.com/spell=97138
Buffs: http://www.wowhead.com/spell=97139 ; http://www.wowhead.com/spell=97140 ; http://www.wowhead.com/spell=97141

Variable Pulse Lightning Capacitor (itemID 69110) uses Variable Pulse Lightning Capacitor (spellID 97119), following the same mechanic as its normal counterpart. 
Item: http://www.wowhead.com/item=69110
Spell: http://www.wowhead.com/spell=97119

Apparatus of Khaz'goroth (itemID 69113) uses Titanic Power (spellID 96923), and Blessing of Khaz'goroth (spellID 97127) consumes stacks to grant Blessing of the Shaper, of which there are three different versions (spellID 96927 for Haste; 96928 for Crit; 96927 for Mastery).
Item: http://www.wowhead.com/item=69113
Spell: http://www.wowhead.com/spell=96924 
Titanic Power: http://www.wowhead.com/spell=96923
Blessing of Khaz: http://www.wowhead.com/spell=97127
Blessing(s) of the Shaper: http://www.wowhead.com/spell=96927 ; http://www.wowhead.com/spell=96928 ; http://www.wowhead.com/spell=96929

Scales of Life (itemID 69109) triggers Weight of a Feather (spellID 97117) and consumes the stacks to heal the user via Tipping of the Scales (spellID 96880).
Item: http://www.wowhead.com/item=69109
Weight of a Feather: http://www.wowhead.com/spell=97117
Tipping the Scales: http://www.wowhead.com/spell=96880

Hope this helps, if anything is missing please let me know and I'll do my best to add it.

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/6974 report related to VPLC

**Comment by LaveniaGithub** [comment]
Fixed, no?
http://atlantiss.eu/changelog#rev5187
http://atlantiss.eu/changelog#rev5185

**Comment by pelekon** [comment]
Fixed.
