### ISSUE TITLE
[EN][Professions][Blacksmithing] Can't learn to blacksmithing

### ISSUE THREAD

**Issue by septerrahun** [Atlantiss/BugTracker#8204]
Hi!

I've got one serious problem with the blacksmithing, and one minor issue with all other professions.

Playing as horde here in the first time, i decided to play as Blood elf paladin. Professions would be simple Mining and blacksmithing.

I wasn't about to report the minor one, but since the video, i report too. Every time i visit a trainer that his/her profession i not know, "Think" i have way to high point on the certain profession. Of course soon as i learn, the number will become to one, as it need to be. So i will not be able to craft literaly anything at level one 5 :)

But the other, it must be! I'm in silvermoon city. next to the trainer, and not want to train me anything, start with the first tier of the blacksmithing. I can see what could i learn, but not going to teach me, Before someone would ask/say....  

Yes, i have all the copper to learn it the first tier of the blacksmithing. 
Her level is 12.
Yes, i tried to log out log in! Also tried the exit the game, and log again
No, i have not use any addon
Yes. It's only happen with the blacksmithing (in my case) I even learned the engeenering just for the video and then unlearn. and the blacksmith still give me hard time

I'll link the video, prehaps somene can help me in this case
http://www.mediafire.com/download/phyzy1t7iez3k1i/IssueWithBS.mp4
Sorry for the quality, sadly if i would made it "nice" then the whole video were looked like 7 picure or so

**Comment by Anhaeyn** [comment]
Well, I think this npc is bugged. Had the same buggy look of this window, but I learned BS probably from this npc http://www.wowhead.com/npc=47421/saren and I could normally learn new stuff from BS trainer in Silvermoon tho.

**Comment by septerrahun** [comment]
Hi Anhaeyn!

Wow, i didn't expected to be answered for like a day, by the way, i checked out that npc, she gladly teached me the blacksmithing! Millions of thanks to you! :)
