### ISSUE TITLE
[PL][Raid][Firelands] Lord Rhyolith 10HC

### ISSUE THREAD

**Issue by Reno323** [Atlantiss/BugTracker#8207]
Boss posiada kilka bledow ktore sprawiaja ze walka z nim wymaga tyle samo umiejetnosci co i szczescia.
1. Boss powinien priorytetowo podpalac wulkany przed soba. Aktualnie boss podpala losowy wulkan ktory czesto znajduje sie po drugiej stronie platformy.
2. Podpalone wulkany zbyt czesto (lub na zbyt wiele osob na raz) uderzaja z Eruption. Jesli podpalony zostanei wulkan znajdujacy sie gdzies daleko za bossem to w 20sek ktore zajmnie dojscie do niego caly raid ma juz ok 10 stackow debuffa zamiast ok 4.
Oba te bledy oraz buff bossow na hc sprawiaja ze bez szczescia nie da sie zrobic tego bossa.
3. Magma Flow z wulkanu uderza kilka razy podrzuconego gracza zamiast tylko raz. Identyczny blad byl kiedys w wersji normal wiec prawdopodobnie macie gotowego fixa ;p
4. Boss niestety nadal chodzi jak kaleka i ciezko sie nim kieruje. Porownujac filmiki z globa do tego co mamy u nas to sa to dwa rozne bossy ale juz stracilem nadzieje na naprawienie tego...

Losowy filmik na ktorym widac podpalanie wulkanow przed bossem, szybkosc narzucania debuffa z Eruption, pojedyncze otrzymywanie dmg z Flowa oraz sposob w jaki boss powinien sie poruszac. https://www.youtube.com/watch?v=bWtgD-Aylk4

**Comment by Reno323** [comment]
Boss chodzi za wolno albo Liquidy chodza za szybko (raczej to pierwsze). U nas boss chodzi wolniej od Liqudow co znaczaco przysciesza regeneracje armora. Filmik z poprzedniego posta ladnie pokazuje jak liquidy gonia bossa i doganiaja go tylko na zakretach.

**Comment by blinkmaster** [comment]
Bump

**Comment by Candisek** [comment]
Bump

**Comment by Jenovas** [comment]
Bumpowanie raczej nic nie da, jestem na wakacjach a to ja byłem/jestem odpowiedzialny za FLa.
