### ISSUE TITLE
[EN][Raid][Firelands][Heroic] Alysrazor hc additional Firestorm

### ISSUE THREAD

**Issue by tnarf** [Atlantiss/BugTracker#8208]
Raid: Firelands 10 hc (propably 25 hc too)
Boss: Alysrazor 10 hc (propably 25 hc too)
SpellName: Firestorm
SpellID: 100744 (cast) ; 101665 (dmg 40k) ; 101662 (dmg 9k)

How should be:
At the end of Phase 4 Alysrazor should cast Full Power and return to Phase 1 (fly etc)

Bugged:
On ATS after Full Power Alysrazor cast "metor's" Firestorm (unavoidable 50k/s per capita).

It isn't a return to the beginning of the fight, because at the beggining of the fight he use "start" Firestorm (unavoidable 9k/s per capita)

Links with proofs how should be:
Wowhead: http://www.wowhead.com/npc=52530/alysrazor#encounter
YouTube (FatBoss guide): https://www.youtube.com/watch?v=fJY9Qg-7Uu4
YouTube (long fight): https://www.youtube.com/watch?v=1TVmrn_5Xyo
WoL (all Alysrazor hits/spells page with end of phase4): http://worldoflogs.com/reports/rt-m2atin0cn4ez0a98/xe/?x=sourceName+%3D+%22Alysrazor%22&page=2

**Comment by LaveniaGithub** [comment]
Check changelog...
