### ISSUE TITLE
[PL][Achievement] Have... Have We Met?

### ISSUE THREAD

**Issue by QuHard** [Atlantiss/BugTracker#8210]
Witam,
Zgłaszam niedziałający achievement "Have... Have We Met?" w Mount Hyjal. Achievement z tego co wyczytałem na wowhead polega na pojawianiu się npcy podczas walki z elitami na Sethria's Roost podczas questu dialy "The Protectors of Hyjal".

**Comment by Malylolek** [comment]
#5735 duplicate
