### ISSUE TITLE
[EN][Spell][Shaman] Fire Elemental Totem

### ISSUE THREAD

**Issue by Angierr** [Atlantiss/BugTracker#8213]
It's been "fixed" in the previous revs, but the problem still persists, which is Shaman's Fire Elemental not having his Avoidance working, becoming literally useless in encounters that include AoE damage, such as Ragnaros, because the Elemental dies within couple of seconds. 

Example of spell that shouldn't be killing the Elemental (or rather Elementals, because Earth Elementals are dealing with the same issue):
http://www.wowhead.com/spell=98263/wrath-of-ragnaros

And I'm pretty sure more than this one AoE skills work on Elementals and kill them. I think it's a major problem, since it's a major boost for both Elemental and Enhancement Shamans, and it makes them basically useless and not worth wasting the CD on.

Cheers

**Comment by fluessig** [comment]
fire elemental and earth elemental dont seem to have avoidance on atlantiss
i did blackrock caverns hc the other day where first boss does this 250k aoe whirlwind
and both elementals insta died from 70k+ hp
so either avoidance doesnt work, or the boss abilities arent flagged as aoe dmg

**Comment by LaveniaGithub** [comment]
Bump, very very very annoying in phase 3 Ragnaros Heroic :))

**Comment by KhrystalGH** [comment]
Bump, still bugged.

**Comment by pelekon** [comment]
fixed in rev 5731
