### ISSUE TITLE
[EN][NPC][Shadowfang Keep][Heroic] Lord Godfrey - Cursed Bullets

### ISSUE THREAD

**Issue by Fabiana-B** [Atlantiss/BugTracker#8218]
Hi!

The last boss in [Shadowfang Keep Heroic,](http://cata.openwow.com/npc=35553) Lord Godfrey is a little bugged. 

The spell ["Cursed Bullets"](http://cata.openwow.com/spell=93761) will be interruptible.

I tried doing Paladin's [Rebuke](http://cata.openwow.com/spell=96231) and [Avenger's Shield](http://cata.openwow.com/spell=31935). Tried too with Mage's [Counterspell](http://cata.openwow.com/spell=2139), and the Blood Elf racial: [Arcane Torrent](http://cata.openwow.com/spell=28730). But nope, I can't interrupt the ability.

![godfrey1](https://cloud.githubusercontent.com/assets/22076895/18415614/8639d7d8-77c6-11e6-9301-2940af81974a.png)

I do not tried this on the normal version.

**Comment by xmesaj2** [comment]
fixed in rev 5631
