### ISSUE TITLE
[PL] Achievements

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#822]
1.http://www.wowhead.com/achievement=5752/justly-rewarded - nalicza od 0 pomimo wykonanej poprzedniej czesci
2.http://www.wowhead.com/achievement=5751/2500-daily-quests-complete -  nalicza od 0 pomimo wykonanej poprzedniej czesci
![image](https://cloud.githubusercontent.com/assets/1584564/5525298/2847c940-89e4-11e4-8ad0-b4fa591bbc38.png)
![image](https://cloud.githubusercontent.com/assets/1584564/5525303/2e143b10-89e4-11e4-89f2-cfd90a9f2f72.png)

**Comment by armano2** [comment]
#2999

**Comment by armano2** [comment]
All bugs with this type are merged into one issue: #4451
