### ISSUE TITLE
[EN][Item][Shaman] Leggings of the Fiery Protector

### ISSUE THREAD

**Issue by Durst-atlantiss** [Atlantiss/BugTracker#8220]
A small issue - there are no http://cata.openwow.com/item=71555 (Elemental), instead of that aditional http://cata.openwow.com/item=71550 were added, so there are two enhancement legs now.

**Comment by Malylolek** [comment]
http://community.atlantiss.eu/index.php?/topic/11464-npc-valor-vendors-ah-heroic-items/?p=54577

fixed in xxx

**Comment by sunshitwowsucks** [comment]
Bump
