### ISSUE TITLE
[EN][Quest][Dragonblight] Lumber Hack

### ISSUE THREAD

**Issue by LogicError0** [Atlantiss/BugTracker#8222]
http://www.wowhead.com/quest=12050/lumber-hack

The shredder can't be entered.  For what it's worth, I'm starting to suspect a recent update broke a bunch of vehicles.

**Comment by xmesaj2** [comment]
fix http://community.atlantiss.eu/index.php?/topic/11606-npc-quest-vehicle-fixes/

**Comment by TranceAccount** [comment]
Fix got accepted
