### ISSUE TITLE
Equipment Menager bugged.

### ISSUE THREAD

**Issue by AllBlackz** [Atlantiss/BugTracker#8223]
Hi, my name is Manonu in WoW. And i can't seem to delete any previous made Equipment Menager sets. Please can you just delete them or whatever. Please just if u can delete all previous made sets. Thank you in advance.

**Comment by anxanas** [comment]
I have the same problem, and i cant even create new equipment sets.

**Comment by Malylolek** [comment]
Make ticket in-game.
