### ISSUE TITLE
[EN][NPC][Firelands][Heroic] Blazing Talon Initiate

### ISSUE THREAD

**Issue by sanhechuan** [Atlantiss/BugTracker#8226]
In the heroic fight on this server, when Alysrazor uses Firestorm, the ads are supposed to stop casting and cast their shield that shields away damage from Alysrazor. The issue here though, is that on the server, the ads do not cast that ability at all, and continuously cast bushfire+feiroblast, which does a lot of damage in heroic, making the fight quite more difficult than it really is supposed to be.

**Comment by Haddis991** [comment]
yeaap this is bugged, when i try to make pugged runs in world i cant do any othre boss than shannox hc, fix this shit you lazy shit admins :P

**Comment by anxanas** [comment]
@Haddis991 gg, ofc they will fix it when you insult them =)

**Comment by mzn928** [comment]
bump.
with the dmg and hp custom buff on bosses this bug makes it really hard for less casual guilds to progress firelands hc. please fix. thanks

**Comment by whatisthisthing** [comment]
Adding spell ID and information for clarification: http://www.wowhead.com/spell=101484/blazing-shield

**Comment by Prodiege** [comment]
In addition to no longer casting, all existing brushfires should despawn

** Proof **:

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Alysrazor

        On Heroic difficulty, Brushfires will despawn once Firestorm is cast, and since the Initiates shield themselves during Firestorm, none are cast again until it ends.
