### ISSUE TITLE
[PL][Southern Barrens][QUEST] Changing of the Gar'dul 

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8228]
Quest: http://www.wowhead.com/quest=24591/changing-of-the-gardul

Po wejściu na tower nie rozgrywa się scenka i nie zalicza questa tak jak powinno to wyglądać.

**Comment by Dranerys** [comment]
When getting atop the tower it doesn't update the "Go to the Top of Tower" part of the quest thus the event doesn't start. Not even standing in the precise spot people on WoWhead mentioned updates this.

**Comment by Bildo** [comment]
fixed
