### ISSUE TITLE
[PL][GAME MECHANICS] Party bugi po kickaniu z instancji

### ISSUE THREAD

**Issue by turboszczur** [Atlantiss/BugTracker#8233]
Przy kickaniu ze zbugowanych instancji(np deadmines, culling of stratholme etc) albo normalnych, wyrzucona osoba dalej jest w zbugowanym party. Czasem wyskakuja komunikaty o zapisaniu albo znalezieniu grupy, jak się zaprosi kogoś i zapisze na kolejnego rdf albo rhc to ta osoba czasem zostaje zostawiona poza grupa, generalnie party buguje sie jak jasna cholera dla osoby kickanej i nawet relog nie pomaga, jedyne rozwiazanie to zaproszenie od kogos innego do grupy.

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
