### ISSUE TITLE
[PL][DUNGEON-CATA] Vortex Pinnacle bugs

### ISSUE THREAD

**Issue by turboszczur** [Atlantiss/BugTracker#8235]
Skyfall star zaatakowalo nas z odleglosci okolo 100 yardow zanim wogole je zauwazylismy i atakowaly wciaz po przekroczeniu ponad 100 yardow poprzez tekstury itp.

Asaad gdy rzuca "unstable grounding effect" pod siebie to sie buguje i zabija wszystkich niewazne gdzie stoja.

**Comment by Malylolek** [comment]
Duplicate.
