### ISSUE TITLE
[EN][Talent][Shaman] Lava Surge

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8236]
when lava surge procs (resetting of lavaburst) there should be a visual in your standard blizzard UI noting that it procced
the visual looks almost like the hotstreak proc from firemages just a bit more lava-y
the visual should not disappear until u press your lavaburst keybind

http://cata.openwow.com/spell=77755 lava surge rank1
http://cata.openwow.com/spell=77756 lava surge rank2
http://cata.openwow.com/spell=51505 lava burst

proof:
https://www.youtube.com/watch?v=OQkaysuV9WM (1:55)
https://www.youtube.com/watch?v=ZsBOYNwPZP4#t=0.203666 (0:25)

**Comment by LaveniaGithub** [comment]
Ehm, no?

That is from an Addon, and not from the Standard Blizzard UI.

The addon is called TotemTimers, and it gives you the option to get that visual (can also be made in Power Auras).

**Comment by anxanas** [comment]
#Laveniaisasmartass

**Comment by fluessig** [comment]
i guess u can close this ticket then
my memory must be playing tricks on me
i leveled a goblin shaman on retail in cata and couldve sworn i had a visual for lava surge procs (and no i didnt have an addon for it)
*shrug* gonna use addon then

**Comment by Kejmil** [comment]
t12 bonus was baked into ele spec in mop
