### ISSUE TITLE
[EN][Spell][Shaman] Windfury Weapon

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8237]
https://github.com/Atlantiss/BugTracker/issues/4895
https://github.com/Atlantiss/BugTracker/issues/5531

on atlantiss windfury does not have the 3 second ICD it should have.
i cannot post video proof of it but i get back to back windfury procs on my resto shaman with a 2.3 base swingtime healmace (with my gear my swingtime is 2.03 even)
just test it yourself, doesnt take that long to get back to back procs

**Comment by anxanas** [comment]
This shit has been tested so many times, and in all the tests it had a 3 sec icd, why do you guys keep bringing it up. Jenova even tested it with GM melee attack speed increase.

**Comment by fluessig** [comment]
https://www.youtube.com/watch?v=L7lMpiOvxbc
1 minute of testing, your ignorance is pissing me off

**Comment by anxanas** [comment]
What is the point of that video? It just shows that you are wrong and i am right.

**Comment by Jenovas** [comment]
I already did tests.

> Windfury cooldown work properly. On your SS the time could have been 2.8 sec not 2 sec.
> Just did tests with a Shaman with 200% haste giving both my main-hand and off-hand a speed of 0.4.
> Windfury procs around every 3sec.
> 
> I also did ten 1 minute tests with 200% haste + normal rotation to see how many times I can get Windfury to proc. The max amount of procs that can happen in 1 minute is 20. My max amount of procs was 18.
> 
> Closing.

**Comment by fluessig** [comment]
are u serious 
my video shows i got back to back windfury procs on a 2.08 swing timer
which means the 3 sec or 2.8 sec ICD or w/e is not met
