### ISSUE TITLE
[EN]Pet system

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#824]
Since cataclysm, pets shouldn't be able to get buffs (or more likely, that buffs don't actually work on them but the visual of some buffs stays on). There are few exceptions to this rule of course, such as haste and %increase damage buffs. This was introduced because since cataclysm pets get 100% of their stats from their owner, thus if pets are getting stats from their owners who already have buffs on them, things go little out of hand
Currently pets are able to be buffed (and this bug was present on the 4.0.6 realm as well)
Why is this important? It's pretty simple. Let's see Unholy DK's and their ghouls. A ghoul gets his master's strenght which was already increased by MotW/Kings and Horn of winter. Again, a ghoul is buffed with mark of the wild and horn of winter increasing his strength even further. While this wasn't that noticable on the 4.0.6 patch, on 4.3 unholy DK's passive strength gain was buffed from 5% to 25% and on higher gear levels this will be a more serious problem. This also applies to BM hunters and demo locks. On the 4.0.6 realm this bug was about a 2-3k dps increase in endgame gear for unholy DK's. Now I imagine it will be much more serious, mainly due to the unholy might buff (5% -> 25%)

**Comment by Milton3450** [comment]
My pet gets stuck some places. I have to go back to him and he will follow again. Is this bug also a part of the pet system?
