### ISSUE TITLE
[EN][Quest][Sholazar Basin] Still At It

### ISSUE THREAD

**Issue by rustndust** [Atlantiss/BugTracker#8240]
I cannot complete this quest. http://www.wowhead.com/quest=12644
The quest NPC ("Tipsy" McManus, not the quest giver) gives commands what to do in order to get the quest item. Theoretically simple. But after 10 commands he shuts down. :P Nothing happens, no quest item, no new commands, no sign of completing the quest, Tried several times. Not only to talk to him and start the booze making process again but to abandon and re-take the quest as well.

**Comment by sulosuse** [comment]
Tested today, still not working.

**Comment by RastaTinu** [comment]
Still doesn't work

**Comment by Danbar1976** [comment]
confirmed still not working

**Comment by Othentik** [comment]
Hi, 

Still not

Ciao

**Comment by Samineh** [comment]
#3413

**Comment by Piklo** [comment]
duplicate
