### ISSUE TITLE
[EN][Quest][Vashj'ir]Elemental Bonds: Desire

### ISSUE THREAD

**Issue by krauza666** [Atlantiss/BugTracker#8241]
GM from ticket send me to BT so here i am. We get buff like this: http://wow.gamepedia.com/Sea_Legs, but it doesn't work, so everyone dies. Repop send my ghost to Westfall and now i don't know how to return to this quest.

**Comment by Anhaeyn** [comment]
Vashj'ir isn't scripted yet.

**Comment by krauza666** [comment]
But Elemental Bonds questline is scripted...

**Comment by jissabraham** [comment]
ya u have to use underwater potions or u die and your body will be in westfall

**Comment by jakubo98** [comment]
Vash doesn't need to be scripted. Buff is supposed to give waterbreathing. If it's given by quest is says something like "at least for time saving Thrall of the vortex"

**Comment by LaveniaGithub** [comment]
In the meantime: Kalu'ak Fishing Pole (=

**Comment by krauza666** [comment]
@Wolffenstein Thanks for fix

**Comment by Malylolek** [comment]
rev. [5197](http://atlantiss.eu/changelog#rev5197)

**Comment by Noviush** [comment]
But the question was how to return to this quest, got the same situation and have no idea howto get back there...
