### ISSUE TITLE
[PL][NPC] Mor'norokk the Hateful

### ISSUE THREAD

**Issue by turboszczur** [Atlantiss/BugTracker#8245]
W/w NPC pojawił się podczas robienia questow dla Diamant the Patient w Deepholm (chain therazane). Laził za mną całą mapę nie chciał się odwalić, a zabicie go low lvlowym tankiem gdy on ma pól miliona hp graniczy z cudem.

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
