### ISSUE TITLE
[PL][Quest][Kezan] Do it Yourself

### ISSUE THREAD

**Issue by vouchero** [Atlantiss/BugTracker#8246]
Mam problem z jednym z questow startowych goblinów "Do it Yourself". Mam zabić 3 moby: 
Bruno Flameretardant
 Frankie Gearslipper 
 Jack the Hammerb
 Sudsy Magee beaten 
Niestety kiedy podchodzę do tych mobów ich nazwa jest niebieska i nie mogę ich zaatakować bez tego questa nie odblokuja mi się kolejne a chciałbym grać goblinem

**Comment by Malylolek** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
