### ISSUE TITLE
[PL][Quest][The Lost Isles]precious Cargo

### ISSUE THREAD

**Issue by vouchero** [Atlantiss/BugTracker#8250]
http://www.wowhead.com/quest=14242/precious-cargo
Po wzięciu questa helikopter zaczyna wariować i nie leci do statków przez co nie da się go skończyć

**Comment by aniviaegg** [comment]
well, i`m stuck here in this quest as well, the chopper will just randomly fly and wont go to the ship, and as this is a main quest to proceed, should be fixed asap or no goblins will get ouf of the island ;-;

**Comment by maronics** [comment]
Same. Fix please. :(

**Comment by Maskedrapeman** [comment]
I'm stuck there for 1 week now, can you plz fix this ASAP?

**Comment by sulx95** [comment]
I completed this quest but now I´m with a bug, I´m in a tornado, please don´t be hard, my english is not good

**Comment by lamaATS** [comment]
Fixed in rev. 5241
