### ISSUE TITLE
[PL][Web] linkowanie na shoutboxie

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#8251]
Kiedy edytujemy shout'a który ma w sobie link, link zmienia się z:
"https://github.com/Atlantiss/BugTracker/issues"
na
"[url="https://github.com/Atlantiss/BugTracker/issues"]https://github.com/Atlantiss/BugTracker/issues[/url]"

**Comment by Malylolek** [comment]
To chyba problem IP.Board'a : ( nie wiem czy da się z tym coś zrobić
