### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by LemonPotatoes** [Atlantiss/BugTracker#8255]
Sunwell Plateau has recently opened, and I finnaly got a chance to try to complete the questline but the quest : http://www.wowhead.com/quest=24553/the-purification-of-queldelar doesn't work, you use the item and then nothing happens. 
It should give you http://www.wowhead.com/item=49871/restored-queldelar  once you use the item but nothing happens, Hope it gets fixed soon.

**Comment by LaveniaGithub** [comment]
Reported already...
https://github.com/Atlantiss/BugTracker/issues/8134
