### ISSUE TITLE
[EN][Quest][Terokkar forest] Ezekiel

### ISSUE THREAD

**Issue by gally9** [Atlantiss/BugTracker#8259]
Quest : "Ezekiel"

The NPC Ezekiel is walking around in Shattrath City as below :
http://www.wowhead.com/npc=19715/ezekiel

But this NPC is impossible to find. so we are unable to do this chain quest, it is bloking for following quests 
http://www.wowhead.com/quest=10228/ezekiel

**Comment by Damfee** [comment]
I have done this chain quest on 2 different chars in the last week. Ezekiel is there.

**Comment by gally9** [comment]
I checked, yes he is there, I close the issue. Maybe a reboot fixed it.
