### ISSUE TITLE
[PL] [Guild]Guild Runs TBC

### ISSUE THREAD

**Issue by Althin** [Atlantiss/BugTracker#826]
Nie działają Achi za robienie TBC Heroiców. Party 4/5 osób.

**Comment by Althin** [comment]
Prosze o otworzenie tego tematu spowrotem, gdyż guild runy z tbc nadal nie są zaliczane.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1716 nie ma takiej potrzeby
