### ISSUE TITLE
[PL][Raid][Firelands] Ragnaros 10 N - Meteory

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#8260]
Po ostatnim uptade na Ragnarosie pojawił się bug dotyczący pojawiania się Living Meteorów na Ragnarosie. Powinny spadać na mapę po jednym, a u nas wygląda to tak: w momencie, kiedy mamy już jeden meteor - spada jeden, kiedy mamy już dwa, to spadają dodatkowe dwa, gdy mamy 3 - spadają 3 i tak dalej. Powinny pojawiać się po 1 niezależnie od ilości obecnych.

Tak powinno to działać: https://youtu.be/UEWheSvOKPk?t=8m45s

W ten sposób bossa ledwo idzie zrobić z bisowymi dpsami, więc proszę o zerknięcie okiem na tego buga.

**Comment by pelekon** [comment]
Zgłoszenie nieprawdziwe.
