### ISSUE TITLE
[PL]Wintergrasp nie działające maszyny.

### ISSUE THREAD

**Issue by MrAdrian976** [Atlantiss/BugTracker#8261]
Na wg nie działa żadna maszyna.

**Comment by monibu** [comment]
Tzn. nie da się wsiąść do nich. Sprawdzałem Demolishera http://www.wowhead.com/npc=28094 i Siege Engine http://www.wowhead.com/npc=32627.

Przez to horda nie może wygrać żadnej bitwy i dostać się do swoich vendorów.

**Comment by pelekon** [comment]
Będzie naprawione + zgłoszenie napisane niewłaściwie.
