### ISSUE TITLE
[EN] [NPC] Aessa Silverdew <Jewlcrafting Trainer>

### ISSUE THREAD

**Issue by Evoes** [Atlantiss/BugTracker#8262]
The Jewlcrafting Trainer in Darnassus City is bugged where when you talk to her she only says "I can instruct you in jewlcrafting. Interested?" She has no options to click, therefore unable to teach Jewlcrafting. I have relogged and walked out of range to reset her and even waited a day to see if it was just a small temp bug with how she loaded. She is still bugged. please fix :) thanks for all the hard work!

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
