### ISSUE TITLE
[EN][Quest][Westfall] CLUCK!

### ISSUE THREAD

**Issue by Bikinitrusa** [Atlantiss/BugTracker#8263]
There aren't any chickens at Saldean's Farm for us to turn in the quest "[CLUCK!](http://www.wowhead.com/quest=3861/cluck)".
There is however, a yellow question mark on both the map and minimap (after i bought the special chicken feed), but no chicken npc I can deliver my quest to. Actually there aren't any chickens at all at Saldean's Farm...
Please fix this, i kinda want a chicken pet, i like chickens, chickens are cool.

**Comment by Lebiedz** [comment]
You can do this with any random chicken in the world. You just need to have the special feed.

**Comment by coba999** [comment]
1. Buy food
2. Abandon chiken quest
3. Find 2 or more chickens
4. Use /chicken macro on both, untill 2 quest (!)  signs will appear at one time
5. Pick quest from first chicken and devilver food to second

Egg will be on the ground after quest complete. Good luck!

**Comment by TranceAccount** [comment]
It is repeatable for ever.
