### ISSUE TITLE
[EN][Dungeon][Coren Direbrew] Coren Direbrew Not Dropping Correct iLevel Gear

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8264]
1) Coren Direbrew is not the correct level. He is currently an 81 elite

2) Coren Direbrew is dropping WoTLK ilevel gear, instead of 365 ilevel gear

**Comment by Hextall** [comment]
Cataclysm Patch 4.2.0 (2011-06-28): Updated to level 85. 
[http://wow.gamepedia.com/Coren_Direbrew](url)

**Comment by Kikuv4e** [comment]
What patch are we now? Aren't we 4.2.0?

**Comment by Anhaeyn** [comment]
We are patch 4.3 but content  we have from 4.2

**Comment by Kikuv4e** [comment]
Either way, the trinkets should be updated, and coren should be updated.

**Comment by Prodiege** [comment]
This has not been resolved. Coren is still level 81 and doesn't hit hard at all.

Also, the two weapons that have a chance to come out of the Keg are still ilevel 200 instead of 365
