### ISSUE TITLE
[PL][Raid][Ulduar]

### ISSUE THREAD

**Issue by Digglewiggle** [Atlantiss/BugTracker#8266]
**Jak jest**: Macki Yogg-Saron'a po złapaniu kogoś http://www.wowhead.com/npc=33983/constrictor-tentacle są friendly dla graczy przez co utrudnia to znacznie encounter.
**Jak powinno być**: Macki Yogg-Saron'a powinny być możliwe do zaatakowania przez graczy.

**Comment by Malylolek** [comment]
#1756
