### ISSUE TITLE
[EN] Pathing

### ISSUE THREAD

**Issue by dewittejager** [Atlantiss/BugTracker#8267]
the problem is the overal pathing mobs go trough walls over fences traight up mountains etc this should be fixxed asap this makes the server stand out from the rest of the wow servers out there this bug is everywhere like litterly everywhere.

**Comment by Jenovas** [comment]
Saying - pathing is broken wont help anyone. There is no magic line of code "PATHING START WORKING". Please create a new report and add screenshots/videos of the bugged NPCs, bugged places etc.
Closing.
