### ISSUE TITLE
[EN][PL]CAN'T LOG IN, banned?

### ISSUE THREAD

**Issue by zofia665** [Atlantiss/BugTracker#8268]
I got this message. Am I banned?
![14383530_1188848874507039_1165646755_n](https://cloud.githubusercontent.com/assets/19503719/18630709/ea059732-7e76-11e6-8212-76df29b64ea6.jpg)

**Comment by Piklo** [comment]
http://atlantiss.eu/bans

**Comment by zofia665** [comment]
Well I'm not on the list

**Comment by Malylolek** [comment]
Bugtracker is not place for resolve this type of problem write mail at complaints@atlantiss.eu or support@atlantiss.eu with ask about information what happend with your account.
