### ISSUE TITLE
[EN][Event][Item] Coren's Chilled Chromium Coaster

### ISSUE THREAD

**Issue by freddie12** [Atlantiss/BugTracker#8277]
Hello, Coren's Chilled Chromium Coaster should have an icd for 45 seconds yet it seems that it doesn't have icd on our server and it has almost 100% uptimes when equipped on a sub. rogue or a feral druid. And yeah it's much more powerful then it should actually be. 

Link: http://www.wowhead.com/item=71335/corens-chilled-chromium-coaster
Note: You can check the comments for more information.

**Comment by LaveniaGithub** [comment]
All Coren Direbrew trinkets are bugged and have no ICD.

**Comment by sunshitwowsucks** [comment]
plz don't fix rip dps

**Comment by AtlantissBlood** [comment]
http://cata.openwow.com/spell=101288
http://www.wowhead.com/item=62362/signet-of-the-elder-council
RiP Where did you see that internal cooldown(ICD) ?

**Comment by freddie12** [comment]
"Based on ForteXorcist. The Proc is called //www.wowhead.com/spell=101287.

It has an ICD of 45 seconds. 
Based on the Trinket math its 4000AP * 10 / 45 = 888.8 AP

This trinket procs almost immediately after the ICD is up on my enhancement shaman. It should for all melee and ranged classes that have a decent crit%.

Doesn't seem to proc as much on my Retribution Pally. Although Crit is their 2nd best stat and some can be reforged to mastery. 

And someone said it wasn't good for rogues. It is not good for Assassination Rogues since they don't stat for crit rating. Crit is weakest stat for Combat as well. It will benefit Subtlety the most.

It should benefit Hunters since crit is their best secondary stat and it can be reforged into hit or haste based on their needs.

Crit is weakest stat for Frost and Unholy DKs. There are probably better blue trinkets like the //www.wowhead.com/item=56393.

This is also a decent trink for Fury and Arms warriors. Crit is their strongest secondary stat and takes 2000 Strength to get 4000AP. This trinket for a warrior is like having a static 444 STR."
This is the 3rd comment on wowhead link of the trinket.
