### ISSUE TITLE
[EN][Talent][Hunter] 4p T12 and LnL

### ISSUE THREAD

**Issue by szapol** [Atlantiss/BugTracker#8278]
so i'm acting like the previous topic submitted half a year ago didn't exist cause it was written crappy, had 2 comments and no admin attention whatsoever.

[Lock n Load](http://www.wowhead.com/spell=194595/lock-and-load)
[Hunter T12 4p bonus](http://www.wowhead.com/spell=99059/item-hunter-t12-4p-bonus)
[Burning Adrenaline (buff u gain)](http://www.wowhead.com/spell=99060/burning-adrenaline)
[ES](http://www.wowhead.com/spell=145661/explosive-shot)

How it works now:

situation 1: 4p procs => LnL procs => hunter casts ES => 4p bonus gets consumed by the free ES
situation 2: LnL procs => 4p procs => hunter casts ES => 4p bonus doesn't get consumed by ES

How it should work:

in any case 4p bonus should only consume abilities that cost focus, not during LnL

How to reproduce:

keep shooting and using ice trap to proc lnl at will

**Comment by arekczup** [comment]
https://github.com/Atlantiss/BugTracker/issues/6119
