### ISSUE TITLE
[EN][Event][Item] Coren Direbrew DF reward

### ISSUE THREAD

**Issue by Valtras** [Atlantiss/BugTracker#8280]
Hello,

it's good to see, you've fixed Coren Direbrew's loot, but there's still a bug in a form of outdated content of Keg-Shaped Treasure Chest (daily reward from dungeon finder). It's a pitty, because we, enha shamans, are still missing our [Tremendous Tankard O' Terror](http://cata.openwow.com/item=71332) as event days are passing by.
Current content is probably according to [http://cata.openwow.com/item=54535#contains](http://cata.openwow.com/item=54535#contains), but it should be more like [http://cata-shoot.tauri.hu/?item=54535](http://cata-shoot.tauri.hu/?item=54535) or [https://cata-twinhead.twinstar.cz/?item=54535](https://cata-twinhead.twinstar.cz/?item=54535).

Thank you

**Comment by LaveniaGithub** [comment]
Fixed
