### ISSUE TITLE
[EN][Spell][Paladin] Hand of Light

### ISSUE THREAD

**Issue by MatthewFT** [Atlantiss/BugTracker#8283]
[EN] Hello, my dear friends. I've found a bug about Paladins with Retribution specialization. The damage of this spell http://cata.openwow.com/spell=96172 should be invisible, but on Atlantiss you can see the numbers. These numbers overshadow the damage from Templar's Verdict, Crusader strike and Divine Storm. As a Damager I think that this bug is VERY annoying because you want to see the BIG numbers on screen but not these small ones from your mastery! 

From all Ret Pallys.

**Comment by Psychobird7** [comment]
This bug has nothing to do with HoL itself, rather with your combat text settings or add-on. 
My combat text displays both the CS/DS/TV hit and the HoL damage as a separate instance of damage right next to it.

I just checked an old screenshot from retail and you can also clearly see the HoL damage on the combat text.
