### ISSUE TITLE
[EN][Item] Coren's Chilled Chromium Coaster

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#8285]
first if you leave the party after defeating coren direbrew http://www.wowhead.com/npc=23872/coren-direbrew you get 30min dungeon deseter sometimes
and http://www.wowhead.com/item=71335/corens-chilled-chromium-coaster is bugged it has no cooldown, it keeps on procing and refreshing itself (all the time durning dpsing you got 4k more attack power)

**Comment by LaveniaGithub** [comment]
Trinkets fixed.
Haven't experienced deserter from this event dungeon myself.

**Comment by AtlantissBlood** [comment]
http://www.wowhead.com/spell=101288/reflection-of-torment 
make sure you check this item have CooldDown N/A GCD: 0 in retail too

**Comment by LaveniaGithub** [comment]
Trinket has been fixed.

Already another post about the deserter bug: https://github.com/Atlantiss/BugTracker/issues/8279
