### ISSUE TITLE
[EN][Spell][rejuvenation][RESTO DUDU]

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#8286]
On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].

Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.
Make sure, that what you report is actually a bug.
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Write your tickets according to the format:
[EN][Quest][Zone] A Vision of the Past
[EN][NPC] Thoralius the Wise
[EN][Spell][Class] Frostfire Bolt
[PL][Talent][Class] Brain Freeze
[EN][Glyph][Class] Glyph of Frostfire Bolt
[EN][Npc][Drop] Thoralius the Wise
[EN][Web] Armory doesnt work
List of currently supported tags /wiki/List-of-supported-tags-in-issue

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by phanttom** [comment]
12.50% haste + nature grace = only one tick wild growth extra . NO 6th trick rejv that it should
even with haste 2032 + nature grace= no 6th tick rejvenation
even i reached 4111( 32.10%)haste and rejuvenation 6th tick didnt happen
even 2005 haste should make 9 ticks of wild growth and efflorecence but it doesnt here!
Here with 4111 haste only 9 tick wild growth which it should be 2005 haste to make 9 ticks

6th tick now on atlantis above 58.52% haste thats around 6000 haste
note higher ticks works fine for wild growth example 58.52% haste gives 13 sticks wild growth which is correct
plz fix druid, without these is useless .was working fine previous . thx u




 Previous it was working . plz fix it. regards from top druids resto on server

**Comment by phanttom** [comment]
also try use rejuvenation twice in a row on urself, u get one number lower than 30% of talent. what i mean that number very low u never see than low tick in druid healing. example first tick rejuvenation from talent gives on me 3200. if i cast it again fast on me while other rejuvenation on me il get number below 3200 :(

**Comment by phanttom** [comment]
i tested unreachable numbers with haste , seems 7 th tick and 8th tick and 9ths ticks of rejuvenation working fine with wild growth. Seems only 6th tick of rejuvenation deleted or need to be fixed

**Comment by phanttom** [comment]
If u have coren egg trinket pops 24/7 on u or nature's grace 24/7 on u or BL 24/7 on u,means now that as if u don't have them.
In other words : the 6th tick for rejuvenation(  gift of earth mother is a talent u wont count it as a tick which is counted number zero in tick)
Lets just say ur number zero tick is 3222 hp without buffs when u cast it on yourself. 12.50% haste cap + nature's grace should push u to 6th tick rejuvenation. means ur initial tick zero will increase from 3222 hp to 3867 hp. 3867-3222= 645 hp more.
Remark: each 300 intellect will increase the zero tick of rejuvenation by 58 hp. So 645 hp rejuvenation increase is = around 3300 intellect and little more.
Remark: im focusing on zero tick rejuvenation , i dont want to enter with details of effect of crit and other spells that will take me 10 hours work to explain it, like when u reach 55% haste and above what will happen.
Since 6th tick rejuvenation deleted lately in server. 12.50% haste + nature's grace or 12.50% haste + egg coren trinket or 12.50% haste + BL = same result 3222 zero tick rejuvenation not 3867
therefore u lost 3300 intellect.

FIX druid Resto :Z:Z:Z

**Comment by Piklo** [comment]
"FIX druid Resto :Z:Z:Z" not only resto druid is bugged, but no one crying :P
Soon™

**Comment by phanttom** [comment]
lets make loss 3300 intellect to all casters and miss call me if no one cries

**Comment by Fearyourself** [comment]
Even though his English is broken af he's got a pretty valid point imo

**Comment by Illusie** [comment]
I miss understood what he said,
but how that come that no moderator labeled this issue in any periority?

@Jenovas 
@Wolffenstein 
@pelekon 
@Quban 
@lamaATS

**Comment by Kiperr** [comment]
https://docs.google.com/spreadsheets/d/1WLOZ1YevGPw_WZs0JhGzVVy906W5y0i9UqHa3ejyBkE/edit#gid=25

**Comment by lamaATS** [comment]
Please write a new issue according the rules.
