### ISSUE TITLE
Bug in auction house

### ISSUE THREAD

**Issue by kiraka123** [Atlantiss/BugTracker#8288]
As i was browsing the auction house it suddenly sent me a trade with  potion of illusion in it.
![wowscrnshot_092116_181731](https://cloud.githubusercontent.com/assets/22349636/18717620/2a7ce172-8029-11e6-8361-d12b6d3e2c6c.jpg)

[EN][NPC] Auctioneer Drezmit

**Comment by arekczup** [comment]
https://github.com/Atlantiss/BugTracker
