### ISSUE TITLE
[EN][NPC][Firelands][Heroic] Cinderweb Drone

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#8290]
When drone is fixated on any player all damage he deals should be reduced by 75%, but on our server only physical damage of drone is mitigated when he's fixating. Boiling Splatter hits for full amount of damage during fixate what causes ocassional one shots of players who get fixated.

**Comment by Psychobird7** [comment]
This happened to us yesterday, half the raid got oneshot by Splatter+Emberflare.          

Fixate should also not be breakable by taunts or Deathgrips.

**Comment by Jenovas** [comment]
Fixate's description is that it only reduces Physical DMG Done.
