### ISSUE TITLE
[EN][Talent][Mage] Cauterize

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8292]
when u cauterize from 100% hp or anything above 40% for that matter, u just burn from your current health for cauterize dmg

it should work differently. cauterize always brings u to 40% of hp when u absorb an attack that would otherwise kill you, doest matter what hp u were at when u absorbed for cauterize

http://cata.openwow.com/spell=86948 cauterize rank1
http://cata.openwow.com/spell=86949 cauterize rank2

proof:
https://www.youtube.com/watch?v=FWogJDWXj6s (0:54)

**Comment by lamaATS** [comment]
Fixed in rev. 5205

**Comment by sunshitwowsucks** [comment]
cauterize only works sometiems now too.

**Comment by lamaATS** [comment]
What means `sometimes`?

**Comment by sunshitwowsucks** [comment]
for example if you get meleed by lets say Majordomo Staghelm and your at full hp as mage and he hits you for like 150k, the talent doesn't even go off and you just die

**Comment by milzo** [comment]
Cauterize absorb only up to 200% of player's max HP.

**Comment by sunshitwowsucks** [comment]
so if i ahve 123k hp and i get hit 150k hp i die that isnt 200%
