### ISSUE TITLE
[EN] warrior and druid rage on miss

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8294]
warriors and bears again do not generate any rage if their auto attack misses
this was in changelog before but i tested it on both classes right now, doesnt work

rev. 5004 Author: Jenova :: 2016-05-10 10:52

Warrior:

    misses should generate rage

please dont forget about bears btw :(

**Comment by Jenovas** [comment]
Warriors and Druids should not generate rage on miss. The fix was reverted because we found proof that misses dont generate rage.
Closing.
