### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] Return to Obadei

### ISSUE THREAD

**Issue by ponkytok** [Atlantiss/BugTracker#8295]
The NPC that is sedai's corpse [http://www.wowhead.com/npc=16852/sedais-corpse] which should give the quest doesnt give it (no exclamation mark sign at all)
He should give this quest http://www.wowhead.com/quest=9423

**Comment by monibu** [comment]
Have you finished "In Search of Sedai" (http://www.wowhead.com/quest=9390) first?
I've leveled 6 chars to 85 and never had a problem with this chain.

**Comment by ponkytok** [comment]
Yes I had, that's why I'm quite perplexed when the quest chain is broken
Thanks for response

**Comment by krauza666** [comment]
Confirmed bug.

**Comment by Damfee** [comment]
The recent break of this quest chain, coupled with #8051 who has been broken for a while makes the questing achievement for Hellfire Peninsula sadly unoptainable for Alliance.

**Comment by reapertg** [comment]
The quest is still broken but even with this one and #8051 bugged, it is still possible to get the questing achievement. The only chains i can think of that you may have missed start at the crashed zeppelin & at the cave just NW of Thrallmar

**Comment by DuGalle** [comment]
Confirm bugged and this is part of 3 - 4 chain quests

**Comment by Avalain** [comment]
Strangely I done this quest before, I couldn't pick quest from NPC's corpse. Killing boars around it didn't help. Neither did server restart.
Problem still exists.

**Comment by Lluksonak** [comment]
Gonna bump this, still bugged on rev. 5612

**Comment by tomatosz** [comment]
Fixed in rev. 5645
