### ISSUE TITLE
Rezz sickness

### ISSUE THREAD

**Issue by immakoo** [Atlantiss/BugTracker#8299]
every time i die then get kicked or leave a dungeon before rezzing i will be put in dalaran or stormwind dead and have to take rez sickness tjhis is a major inonvenience and i expect this to be fixed alon with everything else with this server cause this is just rediculoous where is all the money from the vote shop going????

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
