### ISSUE TITLE
[PL][NPC] Hudson Banes

### ISSUE THREAD

**Issue by Imacc10** [Atlantiss/BugTracker#83]
http://www.wowhead.com/npc=54021, brak

P.S. przyda się pomoc kogoś z lepszą pamięcią, a mianowicie chodzi o to czy jak nie ma eventu to NPC na pewno jest

**Comment by TranceAccount** [comment]
This can be closed. Because Hallow's End is from the 18th of October until the 1st of November and this bug was reported on the 3rd of November.
