### ISSUE TITLE
A Revenant's Vengeance quest

### ISSUE THREAD

**Issue by Elkas** [Atlantiss/BugTracker#8300]
The quest work but the control ability when you mount Lord Hydrolis is bug, at first his ability work fine, but after few use he become bugged in his casting stance, he doesn't do anything if you order/click his ability. The boss mob is level is ?? so all my normal spell or attack misses her, making this quest impossible to complete.

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
