### ISSUE TITLE
[EN][Quest][Molten Front] The Forlorn Spire

### ISSUE THREAD

**Issue by vinklas** [Atlantiss/BugTracker#8301]
At the moment, the quest can't be completed because the druid never appears even when you stand at the beginning of the path where these druid must supposed to be and start the event, nothing happens

this is a major bug because of this quest, no one can complete the other quests 

http://www.wowhead.com/quest=29205/the-forlorn-spire

**Comment by Piklo** [comment]
#5926

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/5727

**Comment by Digglewiggle** [comment]
bump
