### ISSUE TITLE
[EN][Raid-Cata][Firelands]Avengers of Hyjal - Heroic Raid Mode reputation

### ISSUE THREAD

**Issue by Trollpowah** [Atlantiss/BugTracker#8303]
Reputation gain from heroic bosses on Firelands haven't been increased, proof from Heroic Shannox (You can see that some players got achievements):

http://prntscr.com/clle4j

What the reputation gains should be like: 

"The first four bosses (Shannox, Lord Rhyolith, Beth'tilac, Alysrazor) give 250 base reputation on Normal Mode and 500 base reputation on Heroic Mode.
The other bosses (Baleroc, Majordomo Staghelm, Ragnaros) grant 400 base reputation on Normal Mode and 800 reputation on Heroic Mode."

Proof: http://www.wowhead.com/faction=1204/avengers-of-hyjal

**Comment by sunshitwowsucks** [comment]
Bump

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12046-8303-firelands-boss-reputation/

**Comment by Evelinrose** [comment]
This is pretty huge thing.will see what can be done about it if your fix is fine :)

**Comment by Piklo** [comment]
posted fix at forum again, sorry, now should work:
http://community.atlantiss.eu/index.php?/topic/12495-8303-firelands-boss-reputation/
