### ISSUE TITLE
[EN][Quest][Zone] precious cargo quest cannot be completed.

### ISSUE THREAD

**Issue by rulzux** [Atlantiss/BugTracker#8305]
The gyrochoppa goes back and forth and never reaches the ship. i have abandoned and taken the quest atleast 20 times, relogged manytimes, deleted some cache files and nothing works. I even tried to get summoned to orgrimmar but it proved unsuccessful
heres couple of pictures:
http://puu.sh/rlHCJ/2587460ae6.jpg
http://puu.sh/rlHEq/e7558fb3e0.jpg
http://puu.sh/rlHFO/9b32bf5ea6.jpg
It twitches between those spots and after a while it drops me to the same spot where i was before i started flying.  
It has never dropped me to water.
pls help

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/8250

**Comment by swiftdeath** [comment]
Stand on the right tip of the anchor on the left side (back to front) on the ship. Face a little inwards ( to the ship ). Jump and use your rocket boots. It made me land right on the deck.. 2 min work
