### ISSUE TITLE
[EN][Raid][NPC][C'thun]Temple of Ahn'Quiraj Boss loot table

### ISSUE THREAD

**Issue by Dr4kth4rr** [Atlantiss/BugTracker#8311]
C'thun drops same items every time (Vanquished Tentacle of C'thun and Eyestalk Waist Cord). I have been farming this boss for 2 months and same items drops every week. Please fix the loot :)

Thanks in advance, best Regards!

**Comment by Piklo** [comment]
i made fix but you have to wait 
http://community.atlantiss.eu/index.php?/topic/11634-826581918070-cthun-loot-tables/

**Comment by Piklo** [comment]
#8191
