### ISSUE TITLE
[EN][Quest][Zone] precious cargo quest cannot be completed. #8305

### ISSUE THREAD

**Issue by XavierMarcano** [Atlantiss/BugTracker#8313]
I try to quit the quest and take it back like 7 times, reload, swin to the place and nothing it cannot be complete.  i hope you fix this quest fast so i can play. Its my first time playing in cataclysm and i want to try this new class for me and fully play the zone . thanks.

Here are some images of me and others trying to make the quest:
http://prntscr.com/cmoeez
http://prntscr.com/cmof8v
http://prntscr.com/cmofxy
http://prntscr.com/cmohjx

The gyrochoppa just goes back and for but never really flies.

**Comment by Aival94** [comment]
Reported: #8250

**Comment by swiftdeath** [comment]
Stand on the right tip of the anchor on the left side (back to front) on the ship. Face a little inwards ( to the ship ). Jump and use your rocket boots. It made me land right on the deck.. 2 min work
