### ISSUE TITLE
Lord Rhyolith Not Resetting Properly (Less Frequent Now)

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8315]
Same issue reported, and closed, here [https://github.com/Atlantiss/BugTracker/issues/7998]

The reported issue is still happening, just less frequently now

This is really annoying when trying to progress and the raid literally has to sit outside doing nothing for 1 hour of raid time

**Comment by NatsumeLily** [comment]
1 hour?..Why 1 hour? Instances reset after 30mins.

**Comment by Prodiege** [comment]
Does it really matter? This shouldn't be happening

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
