### ISSUE TITLE
[EN][Raid][Firelands] Lord Rhyolith Not Resetting Properly

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8316]
Same issue reported, and closed, here [https://github.com/Atlantiss/BugTracker/issues/7998]

The reported issue is still happening, just less frequently now

This is really annoying when trying to progress and the raid literally has to sit outside doing nothing waiting for Rhyolith to reset

**Comment by Sayris9876** [comment]
Confirm... Happened to us 2 days ago we had to wait only 10 min tho

**Comment by Prodiege** [comment]
The time you have to wait is dependent on his hp when you wipe

**Comment by Aldergar** [comment]
Added to the complete report #6031

**Comment by sunshitwowsucks** [comment]
fix: do not wipe

**Comment by Jenovas** [comment]
Does this still happen?

**Comment by Aldergar** [comment]
It seems the only boss that fails to reset(sometimes) at the moment is Bethilac,the others seems to work fine.

**Comment by Prodiege** [comment]
This needs a bigger sample size of players saying this isn't still happening in order to close this topic. I know our guild will be attempting heroic Rhyolith all day this upcoming Tuesday
