### ISSUE TITLE
[EN][Spell][Death Knight] Death Pact

### ISSUE THREAD

**Issue by Sblarck** [Atlantiss/BugTracker#8317]
Death Pact is not consuming my Gargoyle.
The spell description says: "Sacrifices an undead minion, healing the Death Knight for 25% of its maximum health. This heal cannot be a critical".

It clearly states an UNDEAD minion so I should be able to consume my Gargoyle, Ghoul (Raise Dead), or 1 of ghoul of (Army of the Dead) but it's not working. I target my Gargoyle or even try to consume with a macro but it will ALWAYS consume my main ghoul (as an unholy DK at least). Please fix this as it is a major bug when it comes to PvP, thank you.

**Comment by Fearyourself** [comment]
Yeah I noticed it's impossible to sacrifice the gargoyle for some reason... Pretty annoying imo

**Comment by MangeNerfedOwl** [comment]
It actually is possible to sacrifice Gargoyle - when you have no ghoul up. And yeah its so damn annoying bug that you can't choose sac target by macro.

**Comment by lamaATS** [comment]
Fixed in rev. 5205
