### ISSUE TITLE
[EN][Spell][Death Knight] Death Grip

### ISSUE THREAD

**Issue by Sblarck** [Atlantiss/BugTracker#8318]
Arena wise, Death Grip seems to bug out when you try to pull someone who is in a superior platform. Let me explain with some examples. 

-Dalaran Arena: If you are the DK and you try to pull someone who is ON the platform when you're down, Death Grip wont work.

-Blade's Edge Arena: If you are the DK and you are under the bridge, if you try to pull someone who actually is ON the bridge, Death Grip won't work.

**Comment by kadi2** [comment]
https://youtu.be/-wD1_82byGM?t=3m22s

**Comment by pelekon** [comment]
fixed in rev. 5545( forgot to close)
