### ISSUE TITLE
[EN][Quest] Thalorien Dawnseeker

### ISSUE THREAD

**Issue by rares310** [Atlantiss/BugTracker#8319]
http://www.wowhead.com/quest=24535/thalorien-dawnseeker

When you arrive at the destination pointed out by the map, you notice that there is no body on the ground. Targeting Thalorien Dawnseeker won't work either. 
Please fix as this is a big important quest chain for a nice weapon.

Thank you.
This is my first bug report so I apologise if I have missed something or made some mistakes.

[EDIT] I have noticed that when you are close to the dead scar on the bottom of the map of Isle of Quel'danas you can see mobs and hear thalorien and a dk called coldgrip. But at the exact moment you enter the deadscar all of the mobs including thalorien dissapear.

**Comment by ounagi21** [comment]
Same issue here. It would seem to be a phasing problem. The quest npc and mobs disappear when I have the quest. They appear the moment I abandon the quest. It should work the other way around. Please fix this soon.

**Comment by pampidoo** [comment]
I can see grave and mobs around while iam not in The Dead Scar zone but as soon as i enter it everything dissapered.

**Comment by DuGalle** [comment]
confirmed still broken reverse phasing pls

**Comment by ounagi21** [comment]
bump

**Comment by ounagi21** [comment]
Looking at the amount of fixes and updates during this period of time. Can this quest receive some love from the developers too?

**Comment by wowcircle** [comment]
i see you've just scripted 'The Purification of Quel'Delar' but not this quest yet. Plz fix this asap

**Comment by Bildo** [comment]
fixed

**Comment by wowcircle** [comment]
it still bugged. Please take a look i cant complete it

**Comment by Piklo** [comment]
http://atlantiss.eu/changelog#rev5315
"Waiting for update"

**Comment by wowcircle** [comment]
aw man. tks anyway

**Comment by DuGalle** [comment]
calm down soon we shall claim our legendary dragon blades :)

**Comment by jissabraham** [comment]
now it teleport u as of rev. 5314, but once inside the event is not starting and the sward is not been able to be restored. so quest is still undoable

**Comment by secu312** [comment]
yea,  The Purification of Quel'Delar is still bugged
