### ISSUE TITLE
[EN][Quest][Howling Fjord] I´ve got a flying machine

### ISSUE THREAD

**Issue by sulosuse** [Atlantiss/BugTracker#8320]
You can hop on the flying machine, pick up the bag but it should automaticly fall down on the platform. It does not and quest is not completable.

http://www.wowhead.com/quest=11390/ive-got-a-flying-machine

**Comment by RelmAtlantiss** [comment]
I've completed the quest. You need to fly around the platform to find a one spot that works. Also make sure to be dismounted before taking this quest, otherwise you can't get on a flying machine.
