### ISSUE TITLE
[EN][Quest][Icecrown] The Sum Is Greater Than The Parts

### ISSUE THREAD

**Issue by hawcik** [Atlantiss/BugTracker#8329]
In the quest you can't mount a Nergeld.

**Comment by TranceAccount** [comment]
Please follow our _How to use?_: https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.

**Comment by RelmAtlantiss** [comment]
Confirmed, the quest can't be completed. Blocks 6 quests from a chain.

http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts
http://www.wowhead.com/npc=30403/nergeld

**Comment by RastaTinu** [comment]
Quest still doesn't work
