### ISSUE TITLE
[EN][DUNGEON][Westfall]DEADMINES

### ISSUE THREAD

**Issue by seanwow1337** [Atlantiss/BugTracker#8331]
Helix Gearbreaker this boss is bugged. only 1st boss work

**Comment by RastaTinu** [comment]
#8116

**Comment by Vincentoxx** [comment]
I think second doors wont work normaly and plus if you kill boss second you got no loot. And i think you need have bombs to blow up doors. I never did deadmines normaly but youtube can provide alot help.

**Comment by sunshitwowsucks** [comment]
Helix isn't on the vehicle (Olaf) at all, he is completely missing.

**Comment by pelekon** [comment]
Duplicate.
