### ISSUE TITLE
[EN][deadmines][dungeon-cata] dead mines door

### ISSUE THREAD

**Issue by cristianmars** [Atlantiss/BugTracker#8338]
hello so in the dungeon after you kill the lumbering oaf boss (http://www.wowhead.com/npc=47297/lumbering-oaf ) the door its suposed to open by itself but dont , so you cant continue the dungeon . i would like to point that when you kill the boss his name is still red so maybe has something to do with the dungeon no registering the dead of the boss

**Comment by cristianmars** [comment]
hello so in the dungeon after you kill the lumbering oaf boss (http://www.wowhead.com/npc=47297/lumbering-oaf ) the door its suposed to open by itself but dont , so you cant continue the dungeon . i would like to point that when you kill the boss his name is still red so maybe has something to do with the dungeon no registering the dead of the boss

**Comment by pelekon** [comment]
Duplicate.
