### ISSUE TITLE
[EN][Npc][Drop] Alysrazor HC dropping [Vrykul Female Mask]

### ISSUE THREAD

**Issue by Stephenjawn33** [Atlantiss/BugTracker#8340]
Hello a few days ago we killed Alysrazor HC and on the loot table there was two [Vrykul Female Mask] and a chest token. It was on Sunday the 25th I think, when there were a few crashes.

http://imgur.com/QcJROwe - You can see how right after the Alys HC achievement the player got http://www.wowhead.com/achievement=979/the-mask-task achievement when obtaining one of the Vrykul Female Masks. It could not have been staged since we're not even durring Hallow's End event.

**Comment by Aldergar** [comment]
I can confirm there is something wrong with Alysrazor HC drop, we keep getting the LEGS token instead of the CHEST token every week.

**Comment by Illusie** [comment]
Happen to Kunoichi's group (Collateral group) too
but I dont think GM respond to him.

**Comment by therealpadthai** [comment]
Confirmed, We continue to get leg tokens

**Comment by demaciaprotector37** [comment]
http://community.atlantiss.eu/index.php?/topic/11912-alysrazor-hc-chest-token-vanquisher-fix/

**Comment by sunshitwowsucks** [comment]
This has been fixed in Rev. 5230
