### ISSUE TITLE
[EN][Spell][Class][Hunter] Serpent sting

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#8349]
There's a problem on Atlantiss with the hunter's ability Serpent sting, It's that if it happens to pass through any kind of obstacle after its already shot out (during its fly-time), it wont apply itself to the target, as if missing. The issue is especially apparent in PvP, where ppl run around pillars all the time, pls fix it.  Spell ID [1978].

**Comment by lamaATS** [comment]
Fixed in rev. 5203
