### ISSUE TITLE
[EN][Spell][Class][Hunter] Deterrence

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#8350]
On Atlantiss, a hunter in deterrence is still affected by all of the effects of targeted charges and leaps - warrior and pet charges, skullbashes and feral leap. Those should miss according to spells tooltip. Spell ID [19263]. Maybe it has smth to do with the survival hunter talent called "Mirrored Blades", like, those gapclosers count as spells, that cant be reflected back.

**Comment by xolon** [comment]
#7629 #5958 #6892

**Comment by pelekon** [comment]
Duplicate.
