### ISSUE TITLE
[EN][Quest][Terokkar forest]The soul cannon of Reth'herdon

### ISSUE THREAD

**Issue by Zumigon** [Atlantiss/BugTracker#8353]
Can't talk to NPC Sar'this, which spawns (somehow) NPC Flawless arcane elemental (http://www.wowhead.com/npc=23100/flawless-arcane-elemental#drops)
which drops flawless arcane essence (http://www.wowhead.com/item=32822/flawless-arcane-essence#dropped-by) needed for quest.

**Comment by Aival94** [comment]
Reported in Polish: https://github.com/Atlantiss/BugTracker/issues/2426
