### ISSUE TITLE
[EN][NPC] King Crawler in Feralas, The Steam Pools, missing

### ISSUE THREAD

**Issue by Atlntssplayer** [Atlantiss/BugTracker#8355]
Same issue already reported about 1 YEAR AGO here: https://github.com/Atlantiss/BugTracker/issues/5117 but it seems it is still unsolved so I'm going to report it again.

In Feralas region, at the lakes called The Steam Pools, there should be a lot of King Crawler NPCs, especially in the smaller lakes, on the upper part.
I went there recently and there were zero of these NPCs. I waited a good amount of time and nothing spawned.
In-game coordinates for the place within Feralas: 72,72.

Here, in the comment section you can find lots of info about what are these, what they drop etc.:
http://www.wowhead.com/npc=51714/king-crawler

There is also some info in the comments here:
http://www.wowhead.com/item=52982/deepsea-scale#comments

Please check it out, thank you!

**Comment by xolon** [comment]
Understand this, bumping, duplicating will just make it worse and postpone the fix. If you wish to submit a bug report that's already reported consider in if its still open or closed. If its open there is no need to make duplicate. If its closed but bug still exist you should re-open it.
Cheers.

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/5117
