### ISSUE TITLE
[EN][Glyph][Rogue] Glyph of Kick, not working

### ISSUE THREAD

**Issue by Atlntssplayer** [Atlantiss/BugTracker#8357]
Hello

Glyph of Kick for rogues is not working correctly.

This is how it should work correctly:
Without the Glyph of Kick, the Kick ability of a rogue has 10 second cooldown.
With the Glyph the cooldown should be 14 sec but after interrupting a cast with Kick the cooldown should decrease by 6 seconds.

This is how it is on Atlantiss now:
With the Glyph of Kick, the Kick ability has 14 second cooldown, but after interrupting a cast this cooldown remains at 14 seconds, it doesn't shorten by 6 seconds.

Links:
http://wowwiki.wikia.com/wiki/Glyph_of_Kick - Glyph of Kick on Wowwiki
On wowhead this item doesn't exist anymore, probably because it was changed in later expansions.

Please look into this matter as this Glyph could be useful in PVE, in raids, on some bosses.
Ty

**Comment by lamaATS** [comment]
Duplicate #7759
