### ISSUE TITLE
[PL][Spell][Rogue] Killing Spree

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8358]
Link: http://cata.openwow.com/spell=51690
Glyph: http://cata.openwow.com/item=45762

Jestem całkowicie świadomy tego, że temat był już poruszany, lecz od daty zgłoszenia to jest 20 sierpnia 2015 nic nie zostało z tym zrobione (https://github.com/Atlantiss/BugTracker/issues/4306), a problem dalej jest i to niemały. Pozwolę sobie jeszcze raz wyjaśnić: po użyciu umiejętności Killing Spree nasza postać pojawia się przed targetem i jest zwrócona do niego plecami przez co podczas trwania KS (przez 2.5 sec) nasza postać nie auto atakuję targetu co uniemożliwia wrzucanie poisonów, podwójnych hitów z naszego off handa itd. Dodatkowo bonus z KS (+20% dmg) traci na znaczeniu, więc używanie Glyph of Killing Spree nie ma najmniejszego sensu (miałem zamiar wykorzystać go w PVP). Po zakończeniu umiejętności dalej jesteśmy zwróceni plecami do targetu, także aby kontynuować zadawanie obrażeń musimy się odwrócić co zajmuję dodatkowy czas. Podsumowując uważam, że aktualnie nie bardzo opłaca się się używać tej umiejętności, ponieważ więcej na niej tracimy niż zyskujemy, przez to że nie działa prawidłowo. Mam nadzieję, że pozytywnie rozpatrzycie moje zgłoszenie, a przynajmniej zakwalifikujecie problem do "High Priority".

Pozdrawiam

**Comment by Jenovas** [comment]
Jak będziemy mieli czasu to naprawimy.
Duplikat - Zamykam.
