### ISSUE TITLE
[EN][Spell] Fear | Gamebreaking

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8361]
After the latest update [Fear](http://www.wowhead.com/spell=5782/fear) in [PvP lasts 20 seconds](http://i.imgur.com/ttwTf18.jpg), and doesn't have DR.

**Comment by blinkmaster** [comment]
Give warlock some pvp love

**Comment by Zhalox123** [comment]
I just dont know what does fear have to do with the last changelog gg Atlantiss xD hahah 💃

**Comment by xolon** [comment]
> I just dont know what does fear have to do with the last changelog gg Atlantiss xD hahah 💃

It got broken after.

**Comment by Zhalox123** [comment]
Ye but it got changed by someone becouse it was working normaly before :P

**Comment by lamaATS** [comment]
Fixed in rev. 5206 (sorry for that mistake)
