### ISSUE TITLE
[EN][Mage] T12 Bonus set Arcane

### ISSUE THREAD

**Issue by Genoangel** [Atlantiss/BugTracker#8362]
Hello , 

I would like to report the bug regarding the spell reduction of the T12 bonus.

The T12 bonus is supposed to reduce the mana cost of all your spells by 10% instead of making it increase by 10%.

The T12 bonus actually reduce only the cost of the first Arcane blast wish make it useless.

please find attached 3 screens : 1 with Arcane power without T12 , another without arcane power (to see the normal cost) , and one with arcane power with T12.

Arcane blast without arcane power cost 6097 so with 10% reduction it should cost 6097*90/100 = 5487 mana , it actually cost 6009.

Arcane power without T12 : http://imgur.com/a/4ND3u
Arcane Blast *4 without arcane power : http://imgur.com/a/HtlO9
Arcane blast *4 with arcane power with T12 : http://imgur.com/a/6rcdV

Best Regards ,

**Comment by lamaATS** [comment]
Duplicate #6371
