### ISSUE TITLE
[EN][Glyph][Hunter] Glyph of Dazzled Prey

### ISSUE THREAD

**Issue by Cholee** [Atlantiss/BugTracker#8363]
http://cata.openwow.com/spell=56856
Just not working...
conected with:
Concussive Barrage Talent
Concussive Shot Ability

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use

**Comment by lamaATS** [comment]
Fixed in rev. 5229 (missing close)
Commit message:
`Glyph of Dazzled Prey has been reimplemented`
