### ISSUE TITLE
[PL][Warden][Stuck]

### ISSUE THREAD

**Issue by Silverowsky** [Atlantiss/BugTracker#8364]
Witam.

Dziś rozpocząłem przygodę na serwerze. Lecz moja postać utknęła.

Opis sytuacji:
Przeniosło mnie po tym jak nie udało się odeprzeć ataku. NPC podszedł do mnie. Coś zaczął gadać, następnie pojawił się Q do odebrania u niego(Aktywny znak zapytania). Byłem "zdybowany" z innym graczem. Klikłem aby odebrać zadanie od NPC. Nastąpiło wtedy rozłączenie od serwera "DC".  Po ponownym połączeniu nie było nikogo. Jedynie szczur biegający po obszarze. Nie mogę wykonać jakiej kolwiek czynności. ![wowscrnshot_100616_203011](https://cloud.githubusercontent.com/assets/22666635/19165898/e0764db4-8c05-11e6-943f-ffae20b2faf2.jpg)

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
