### ISSUE TITLE
[EN][Quest][Molten Front] The Forlorn Spire

### ISSUE THREAD

**Issue by Kervian** [Atlantiss/BugTracker#8367]
The druid you have to escort does not, ever return to place from which you are supposed to escort him.
Which blocks you from doing couple of dailies from Shadow Wardens in MF

He's just standing next to spire as it was already destroyed that day by another player.

http://www.wowhead.com/quest=29205/the-forlorn-spire

**Comment by Piklo** [comment]
#5926
#5727
#8301
