### ISSUE TITLE
[EN][Spell][Warlock] Corruption haste is not calculated properly

### ISSUE THREAD

**Issue by jo11190** [Atlantiss/BugTracker#8369]
Hello,

Haste is not correctly affecting Corruption as it's not giving a 2nd extra tick (making it 8) before 1996 haste instead of the normal 1993 (raidbuffed) as seen in EJ's original 4.3 thread : https://web.archive.org/web/20120102031610/http://elitistjerks.com/f80/t112939-affliction_cataclysm_4_3_release/

This might be a server-wide problem with how haste is handled server side at all, but as of now I only did tests with Corruption.

Please refer to the screenshots below. Apologies for the poor quality (and fucked up action bars), as this was taken in 800x600 quality while I was multiboxing on my shaman to get the 5% haste buff.

![wowscrnshot_100916_005020](https://cloud.githubusercontent.com/assets/22721822/19218189/82e49800-8dc1-11e6-8189-dc5ea45eb59b.jpg)

![wowscrnshot_100916_004712](https://cloud.githubusercontent.com/assets/22721822/19218191/87b2ec60-8dc1-11e6-984a-afc19bfaec35.jpg)

**Comment by lamaATS** [comment]
Fixed in rev. 5209
