### ISSUE TITLE
[PL][Warlock][Ritual of Summoning]

### ISSUE THREAD

**Issue by jakubo98** [Atlantiss/BugTracker#837]
Szafa nie działa poprawnie:
Bez względu na cel przywołany zostaje gracz, który kliknął na portal, żeby dokończyć summ.
EDIT: http://www.wowhead.com/spell=698
ten powinien starczyć

**Comment by Varchord** [comment]
BUMP

**Comment by nevcio** [comment]
bump

**Comment by mitim1** [comment]
Po ostatnim revie (rev. 4400) który miał naprawić działanie meeting stone oraz Ritual of Summoning nie działa już żaden sposób sumania ludzi włącznie z Have grupe will travel -.-.

**Comment by mitim1** [comment]
bump! Po ostatnim revie z Guidami znów działa jak wyżej.

**Comment by Atraac** [comment]
Bump

**Comment by mitim1** [comment]
Mass summ znów popsuty rev. 4427

**Comment by sunshineinabox** [comment]
I'm not sure if this belongs here, but before I make a new topic I thought I would try asking if its related, but when you use summoning stone the summon does not work unless the person is on the same continent as you. I'm sorry if this has been pointed out above, but none of this is in english so I couldn't tell. Just wanted to point out that it does work when you are summoning on the same continent. (EK to EK, Kalimdore to Kalimdore, Outlands to Outlands)

**Comment by Jenovas** [comment]
Fixed in rev 4488

**Comment by Varchord** [comment]
Zaufałem Ci Jenova
