### ISSUE TITLE
[EN] [NPC] Ragnaros last boss in firelands normal. 10 man

### ISSUE THREAD

**Issue by blazin995** [Atlantiss/BugTracker#8371]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Phase 3,meteors arent working as they should,they spawn 1,2,then 4 and so on,it shouldn't be like that.

**Current behaviour**: What happens
One week he is working normaly and the other week he isnt.He used to spawn meteors 1-2-2-1 and so on but now he is spawning 4 meteors at once.
**Expected behaviour**: What should happen instead
i think he should be spawning 1 meteor then 2 then 2 again then 1 something like 1-2-2-1
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by bonibo** [comment]
I'm pretty sure it's normal. The meteors should spawn on the order 1 1 2 2 4 4 8 etc. At least that's what icyveins says http://www.icy-veins.com/wow/ragnaros-strategy-guide-normal-heroic

**Comment by pelekon** [comment]
Meteors work well.
