### ISSUE TITLE
[EN][RAID][NPC] alysrazor hc meteors

### ISSUE THREAD

**Issue by bonibo** [Atlantiss/BugTracker#8372]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
During the alysrazor HC encounter (we only tried 10m, not sure about 25), meteors should spawn that players need to kill in order to avoid the firestorm.
**Current behaviour**: Meteors are invisible AFTER they are killed. They are still there as objects. You cannot run through them, you can still use them to lineofsight the firestorm, but you just can't see them.

**Expected behaviour**: What should happen instead
Meteors should be visible after they are killed.
**Steps to reproduce the problem**:

1. Pull alysrazor HC.
2. Kill the meteors.
3. Panic?

**Revision**: Current server version. We encountered the bug on October 9th 2016

**Comment by bonibo** [comment]
It seems the bug had already been reported on January. https://github.com/Atlantiss/BugTracker/issues/6031

For a while it worked correctly though. I'm not sure if this amid a duplicate or not

**Comment by pelekon** [comment]
Duplicate.
