### ISSUE TITLE
[PL] [Talent] [Mage] Incanter's Absorption

### ISSUE THREAD

**Issue by Binchal** [Atlantiss/BugTracker#8373]
Witam 
  Zgłaszam problem z  [Incanter's Absorption] Talentem w drzewku Arcane. W skrócie bug polega na tym co się dzieje kiedy działanie 10 sek kończy się zamiast od SP odejmować wartość którą dodał ten talent wywala około 20% SP w kosmos. Przykładem może być sytuacja z której bez swoich własnych buffów mam SP 8865 z MA i AB mam SP 9396 zaczyna działać  [Incanter's Absorption] po absorbach z MS i MA wartość skacze w górę. Następnie po 10 sek spada do 8819 czyli mniej niż mam z itemów i buffów klasowych...
Tutaj przykładowy filmik
https://www.youtube.com/watch?v=KQd0g74ke5s

**Comment by Jenovas** [comment]
Prosze sprawdzic czy jest to tylko visual bug czy rzeczywiscie masz mniej SP.
Moze byc tak ze tylko graficznie cos sie psuje w karcie postaci a nadal zadajesz DMG jakbys mial 9400 SP.

**Comment by Binchal** [comment]
bug zauważyłem na raidzie jak dmg poleciał w dół :(

**Comment by kadi2** [comment]
Might be related to https://github.com/Atlantiss/BugTracker/issues/1320

**Comment by BialyADI** [comment]
Po testowałem to na moim Magu i jest u mnie ok SP po zniknięciu Buffa Incanter's Absorption wraca to poprzedniej wartości przed zabsorbowaniem Dmg.

**Comment by lamaATS** [comment]
Talent nie działa poprawnie sprawdzałem u siebie i jest już poprawiony.

p.s. @Binchal proszę pisać zgłoszenie zgodnie z przykładem.

**Comment by BialyADI** [comment]
Teraz już jest poprawione na serwie?

testowałem to 1 min temu.

**Comment by lamaATS** [comment]
Nie, u mnie lokalnie jest poprawione.

**Comment by BialyADI** [comment]
Ale teraz tez działa poprawnie.
Mam na magu 920 SP
Mana Shield daje 1764 absorbu czyli 20% z tego to 352 SP.
Czyli po dodaniu 920 +352 = 1272.
I po zniknięciu buffa jest normalnie 920.
Wiec co było po psute? Żeby nie wyszło z tego coś gorszego i Mag Arcane będze 1 szotował w PvP co zresztą robi.
![wowscrnshot_101016_210516](https://cloud.githubusercontent.com/assets/5780624/19248004/dbf8584c-8f2d-11e6-8670-07432e6d980b.jpg)
![wowscrnshot_101016_210528](https://cloud.githubusercontent.com/assets/5780624/19248006/dd0b3506-8f2d-11e6-8ef8-c54199e15b73.jpg)
![wowscrnshot_101016_210534](https://cloud.githubusercontent.com/assets/5780624/19248007/de0330bc-8f2d-11e6-9bdd-09499a4f9ca0.jpg)

**Comment by lamaATS** [comment]
Problem pojawia się gdy Incanter's Absorption zostanie odświeżony najlepiej użyć na siebie obu absorbów a następnie bić aż nie zejdą i zobaczyć na efekt.
Bug można zauważyć po tym że Spell Damage i Spell Healing zostają rozdzielone na stałe ponieważ mają różne wartości.

**Comment by BialyADI** [comment]
Przetestowałem tez połączenie Mana Shielda i Mage Warda i w statystykach obniża SP ale jest to tylko Visual Bug Dmg na przeciwniku na Duelu jest taki sam przed i po Incanter's Absorption.

**Comment by BialyADI** [comment]
No tak w Bala to przetestowałem na moim magu ale bug jest tylko visulny odejmuje w statystykach SP ale wszystkie czary biją tyle ile powinny Absorby tez są takie same mimo ze w tool tipie co innego jest napisane ;D.
Niby mam 93 SP Mana Shield w Tooltipie bedze niby absorbowała 1096 ale absorbuje normalnie 1800.
Dmg tez jest normalny.
![wowscrnshot_101016_212426](https://cloud.githubusercontent.com/assets/5780624/19248407/24edfdfc-8f30-11e6-873e-d38edae8a2e8.jpg)
![Uploading WoWScrnShot_101016_212431.jpg…]()

**Comment by lamaATS** [comment]
Pod tym względem tego nie sprawdzałem lecz błąd został już i tak poprawiony. (Na razie u mnie lokalnie)

**Comment by BialyADI** [comment]
No ok git byle by po fixie nie było tak że dodaje SP na stałe co każdy Mana Shield/Mage Ward ale mam nadzieje ze będzie ok.

**Comment by Binchal** [comment]
Czyli zostanie poprawiony po najbliższym Fixie?

**Comment by lamaATS** [comment]
Tak

**Comment by lamaATS** [comment]
@Binchal `To mój pierwszy raz kiedy zgłaszam buga więc do końca nie ograniam jak to się robi. W każdym razie coś jeszcze znalazłem i też to zgłoszę.`

Polecam opcje Preview aby zobaczyć bo będzie przed wysłaniem lub ew. zawsze jest opcja edit.

**Comment by lamaATS** [comment]
Fixed in rev. 5210
