### ISSUE TITLE
[PL][Mage] Arcane Mage Slow duration is again more than 8 sec in PvP.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8374]
Jak jest: Slow Arcane Maga trwa dłużej niż 8 sec w PvP.

Jak powinno być: Slow Arcane Maga powinien trwać od nałożenia maksymalnie 8 sec w PvP

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by lamaATS** [comment]
Błąd już u mnie lokalnie poprawiony dziękuje za report i proszę następnym razem wypełniać zgodnie z przyjętą formą.

p.s. problem wystąpił dlatego że ten Slow posiada redukcję cast timu oraz redukcje movementu (jest to jedyny taki) co w efekcie dało że pierw zostało sprawdzone dla drugiej redukcji (błędna kolejność)
