### ISSUE TITLE
[PL][Mage] Arcane Mage Slow duration is again more than 8 sec in PvP.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8375]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Zła długość Slow'a Arcane Maga w PvP.
**Current behaviour**: What happens
Teraz Slow w PvP trwa 12 sec.
**Expected behaviour**: What should happen instead
Slow Maga Arcane powinien trwać 8 sec jak każdy inny snare.
**Steps to reproduce the problem**:

1. Dać Slow komuś na Duelu.

**Revision**: Current server version
5208

**Comment by lamaATS** [comment]
Błąd już u mnie lokalnie poprawiony.
Problem wystąpił dlatego że ten Slow posiada redukcję cast time-u oraz redukcje movement-u (jest to jedyny taki spell) co w efekcie dało że po pierwsze sprawdzono czy posiada redukcje cast time-u (błędna kolejność).

**Comment by lamaATS** [comment]
Fixed in rev. 5210
