### ISSUE TITLE
[EN][NPC] Sunblade Dragonhawk

### ISSUE THREAD

**Issue by xShojirox** [Atlantiss/BugTracker#8376]
**Description**: Currently Sunblade Dragonhawks are supposed to be tamable but they are not.
http://www.wowhead.com/npc=25867/sunblade-dragonhawk#comments

**Current behaviour**: Sunblade Dragonhawks cannot be tamed.

**Expected behaviour**: Sunblade Dragonhawks can be tamed.

**Steps to reproduce the problem**:
1. Go to Sunwell Plateau as a 70+ Hunter
2. Attempt to tame a Sunblade Dragonhawk

**Revision**: 5208

There are a few different reasons why it could be not tamable, one would be that the family flag isn't set properly, the other would be that the type_flags is an even number when it should be odd. The fixes for those are below:

```
UPDATE creature_template SET family = 30 WHERE entry = 25867;

UPDATE creature_template SET type_flags = type_flags + 1 WHERE entry = 25867  AND type_flags % 2 = 0;
```

The type_flags I am updating by adding 1 to it so that the other flags are not being changed, but this should only be done if it is an even number already.

**Comment by TranceAccount** [comment]
You can post fixes on the forums:
http://community.atlantiss.eu/index.php?/forum/90-post-your-fix/

**Comment by smmuntz** [comment]
I did post it on the forums if you notice, currently the top 4 posts (aside from the pinned post) are all mine posted from months ago.

The type_flags is supposed to be in binary, but doing a + seemed to work when I tested it on my own system.

**Comment by xmesaj2** [comment]
The correct way to add flag is to do
`UPDATE creature_template SET type_flags = type_flags|1 WHERE entry = 25867;`
for example if npc has flag 1 using |1 won't change it, but using +1 will change flag to 2 thus messing up existing flag

**Comment by TranceAccount** [comment]
@xmesaj2 This can be closed because his fix got accepted:
https://community.atlantiss.eu/index.php?/topic/11870-npc-sunblade-dragonhawk/

**Comment by xmesaj2** [comment]
thanks for info
