### ISSUE TITLE
Rocky upheaval

### ISSUE THREAD

**Issue by kiradeathh** [Atlantiss/BugTracker#8377]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
not to deliver the mission
![wowscrnshot_101016_193858](https://cloud.githubusercontent.com/assets/22756798/19253618/be162242-8f22-11e6-9af9-6be4097b1b34.jpg)

2. 
not to deliver the mission
3. mission is in Deepholm -Therazane

**Revision**: Current server version

**Comment by kiradeathh** [comment]
http://pt.wowhead.com/quest=26577/rocha-dura-de-roer

**Comment by pelekon** [comment]
Fix title.

**Comment by NatsumeLily** [comment]
This tells us absolutely nothing...Please fix your post. 

How is it bugged?

**Comment by Aldergar** [comment]
...what?

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19397861/f1d9c49c-9249-11e6-9316-7c09b03b23c6.PNG)
