### ISSUE TITLE
[EN][Quest][Mount Hyjal]Druids of Talon

### ISSUE THREAD

**Issue by iOSBlack** [Atlantiss/BugTracker#8381]
**Description**: When delivering the mission of the Druids of the Talon (http://www.wowhead.com/quest=29181/druids-of-the-talon), and I went to give it to Molten front, I had nothing. It is as if he had entered the stage but could not deliver or see Skylord Omnuron. After a while trying to make divorce her and wanted to go to take it up to Shrine of Aviana, but the NPC Skylord Omnuron, was gone.

**Current behaviour**: After giving Druids of the Talon 150 [Mark of the World Tree], the event start and can not deliver in Molten Front or resume the mission.

**Expected behaviour**: I guess I should enter another phase of Molten Front

**Steps to reproduce the problem**:
1. Deliver the mission "Druids of the Talon"
2. Try to deliver (NPC did not appear none)
3. Quit and try to resume (Skylord Omnuron no longer to resume the quest)

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19397851/e4d1838e-9249-11e6-8548-b2167c287d90.PNG)
