### ISSUE TITLE
[EN][Dungeon-Cata] Zul'Gurub-Jin'do the Godbreaker

### ISSUE THREAD

**Issue by Atlntssplayer** [Atlantiss/BugTracker#8382]
**Description**: In Zul'Gurub 5-man heroic dungeon the last boss, Jin'do the Godbreaker is seriously bugged and can't be killed.

**Current behaviour**: Phase 1 of the fight seems normal, but when phase 2 is about to start the encounter stops and after a few seconds resets. The boss is placed at it's starter position with max HP and can be pulled again.
I saw this bug happen in 2 different parties, on 2 different days.

**Expected behaviour**:  Instead resetting the encounter should continue with phase 2 normally.
**Steps to reproduce the problem**:
1.  Get into a party for ZG.
2.  Clear all bosses, go to Jin'do the Godbreaker.
3.  Start the fight, reach the point where phase 2 should happen.

**Revision**: rev. 5211

**Comment by Damfee** [comment]
Tried Zul'Gurub twice, and this happened both times. Pretty crushing, as this happens at the very end of the dungeon, and you have to accept that it's not completable.

**Comment by Baggedmilk** [comment]
Bump.

**Comment by Baggedmilk** [comment]
Bump.

**Comment by Baggedmilk** [comment]
Bump.

**Comment by Baggedmilk** [comment]
Bumpyyyyyyy

**Comment by Othentik** [comment]
Hi, still bugged

cheers

**Comment by xmesaj2** [comment]
rev. 5629 fixed
