### ISSUE TITLE
[EN][Quest][Temple of Ahn'Qiraj] Imperial Qiraji Armaments

### ISSUE THREAD

**Issue by BigBadVoodo** [Atlantiss/BugTracker#8383]
[http://www.wowhead.com/quest=8789/imperial-qiraji-armaments](url)
[http://www.wowhead.com/quest=8790/imperial-qiraji-regalia](url)
 Auto fail on accept

**Comment by xmesaj2** [comment]
Use https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
