### ISSUE TITLE
[EN][Spell] Mining

### ISSUE THREAD

**Issue by Lumnos** [Atlantiss/BugTracker#8384]
**Description**: Pyrite in Minable before 525

**Current behaviour**: You have successfull mining attempts of Pyrite before the skill reaches 525.

**Expected behaviour**: You should get a message saying your skill is not high enough until 525

**Steps to reproduce the problem**:
1.  Raise mining limit of Pyrite Veins to 525

**Revision**: rev. 5211

**Comment by TranceAccount** [comment]
## Posted a fix on the forums.
