### ISSUE TITLE
[EN][Quest][Achievement] The Purification of Qual'Delar

### ISSUE THREAD

**Issue by ounagi21** [Atlantiss/BugTracker#8386]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Quest: http://www.wowhead.com/quest=24596/the-purification-of-queldelar

What doesn't work?
The event doesn't begin when you use the quest item the required place.

Event that should begin: https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by ounagi21** [comment]
I know, I know, this is a duplicate. Just trying to get some insight as to the progress of fixing this issue. Thanks

**Comment by Bildo** [comment]
if you are trying to get an update just bump existing one no need to create a new
