### ISSUE TITLE
[PL][Warlock][Skill] Health Funnel can Heal when Pet is no in LOS.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8387]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
WarLock może leczyć Health Funnel przez ściany.
Przykład bug na arenie:
![wowscrnshot_101216_233029](https://cloud.githubusercontent.com/assets/5780624/19329503/7ab63e48-90d9-11e6-9db7-19c0103379b8.jpg)
**Current behaviour**: What happens
Lock moze użyć Health Funnel nawet gdy jego Pet jest za tekstura co tworzy pewien dysbalans w PvP.
**Expected behaviour**: What should happen instead
Lock musi widzieć Peta by zacząć castować Health Funnel.
**Steps to reproduce the problem**:
1. Zagraj Arenke na Locka.
2. Idź za teksturę i gdy Lock puści na ciebie Peta zacznij go bić.
3. I obserwuj jak Lock leczy Pety za ściany.

**Revision**: Current server version
5211

**Comment by BialyADI** [comment]
http://wotlk.openwow.com/spell=47856 Link do skilla z Cata database.

**Comment by lamaATS** [comment]
Fixed in rev. 5214 (You can still cast spell but no healing received and no damaged taken)
