### ISSUE TITLE
[EN] Zul Gurub Jin'zoh not entering second phase

### ISSUE THREAD

**Issue by Psyduckxoxo** [Atlantiss/BugTracker#8389]
**Description**: Today our 5 group tried multiple times to kill Jin'doh in Zul Gurub. When he reached 50% health he ran to a spot and despawns without entering phase 2. Then Jin'doh respawned at his starting location acting like the boss fight never happened.
**Current behaviour**: Jin'doh despawns at 50% health and ends the fight prematurely

**Expected behaviour**: Jin'doh should enter phase 2 instead
**Steps to reproduce the problem**:
1.  Start Jin'doh bossfight
2. beat him to 50%health
3. see that he despawns

**Revision**: 5213

**Comment by LaveniaGithub** [comment]
https://github.com/Atlantiss/BugTracker/issues/8382

Duplicate. Already reported.

**Comment by Baggedmilk** [comment]
Bump.
