### ISSUE TITLE
[EN][Spell][druid] Ferocious Bite

### ISSUE THREAD

**Issue by SlapZech** [Atlantiss/BugTracker#8391]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

http://cata.openwow.com/spell=22568

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Ferocious Bite damage is utterly bugged and renders the skill practically useless. 
Level 42 feral druid in full heirlooms deals about 60 dmg per melee swing, 130 per rake tick and 240 per mangle. Ferocious Bite deals 26 ( yes, TWENTY SIX ) damage on 5 combo points. This renders the combo point system of druid non-existent untill 54 lvl, on which the class gets it's SECOND finisher.
Spell occasionally does it's supposed damage, but it happens 10% of time the spell is used.

**Current behaviour**: Ferocious Bite damage calculation is wrong, the damage is absurdly low in most cases of the skill usage. Spell deals less damage then melee swings.

**Expected behaviour**: Ferocious Bite should deal stable damage depending on combo points, which should be also increased by attack power and deal additional damage by using up to 35 more energy for up to 100% more damage.

**Steps to reproduce the problem**: 

1. Attack any target as feral druid
2. Reach 1-5 combo points on said target
3. Use Ferocious Bite

**Revision**:  5214

**Comment by lamaATS** [comment]
Fixed in rev. 5212
