### ISSUE TITLE
[PL][Quest][Sunwell Pateau]The Purification of Quel'Delar

### ISSUE THREAD

**Issue by Amarilla88** [Atlantiss/BugTracker#8392]
http://www.wowhead.com/quest=24564/the-purification-of-queldelar

2 problemy. 
- Po pierwsze po wzięciu q i rozmowie z npc obok, nie przenosi nas do raidu (przenosi nas dopiero, kiedy jesteśmy z kimś w grupie raidowej, ale tak to nie powinno działać.
- Po użyciu q itemu nic się nie dzieje, nie odpala się event - a powinno być https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by LaveniaGithub** [comment]
Duplicate. Please use search option before creating a new report.

**Comment by xmesaj2** [comment]
And use issue template
