### ISSUE TITLE
[EN][Spell][Warrior] Stance

### ISSUE THREAD

**Issue by Othentik** [Atlantiss/BugTracker#8393]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: issue with selection of warrior stance.

**Current behaviour**: Stance doesn't change on click or keybind since update server 14/10/16 12pm

**Expected behaviour**: Stance should switch on click or KB

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 
![wowscrnshot_101416_135418](https://cloud.githubusercontent.com/assets/22837119/19386697/f82ba790-9215-11e6-80a5-60369d46862f.jpg)

**Thank you in advance for your work !!!**

**Comment by sunshitwowsucks** [comment]
so that's why i couldnt get aggro in dungs

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19397833/d1a91416-9249-11e6-9313-bd9614760f59.PNG)

**Comment by lamaATS** [comment]
Fixed in rev. 5216
