### ISSUE TITLE
[EN][NPC][Firelands] Molten Meteor / Alysrazor

### ISSUE THREAD

**Issue by Digglewiggle** [Atlantiss/BugTracker#8394]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Alysrazor on HC is pretty bugged because of Meteors which dont show any visible texture to hide from Firestorm ability.

**Current behaviour**: When player kills Molten Meteor it doesnt leave any visible Boulder that could protect raid from taking damage from Firestorm
**Expected behaviour**: When player kills [Molten Meteor](http://www.wowhead.com/npc=54563/molten-meteor) it should have left a VISIBLE texture of a boulder that protect raid from taking damage if u stay in Alysrazor's line of sight.

**Steps to reproduce the problem**:

1.  
2. 
3. 

**Revision**: 5214

**Comment by Jenovas** [comment]
Fixed
