### ISSUE TITLE
[PL][Spell][Rogue] Stealth

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#8395]
**Description**: Po użyciu/wyjściu ze stealth'a pojawia się komunikat: "You are in the wrong zone."

Link: http://cata.openwow.com/spell=1784

**Current behaviour**: Pojawia się opisany powyżej komunikat.

**Expected behaviour**: Nie powinien pojawiać się komunikat.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5214

![wowscrnshot_101416_170124](https://cloud.githubusercontent.com/assets/21290619/19393440/09e5ddb0-9235-11e6-91d1-792156b5b1bb.jpg)
![wowscrnshot_101416_170131](https://cloud.githubusercontent.com/assets/21290619/19393453/0f744bf4-9235-11e6-9abb-6a655fa10c58.jpg)

Edit: Problem pojawił się po ostatnim update'cie.

**Comment by lamaATS** [comment]
Fixed in rev. 5216

**Comment by RastaTinu** [comment]
Problem nie zniknął :/

**Comment by lamaATS** [comment]
Sprawdzałem to chwilę temu u siebie lokalnie oraz na main serwerze i problem nie występuje, prawdopodobnie jest to problem z postacią lub lokalizacją.

**Comment by Piklo** [comment]
@RastaTinu relog / respec / umrzyj (in game oczywiście :D ). u mnie działa dobrze

**Comment by RastaTinu** [comment]
Okej do zamknięcia, problem leżał w tym itemie: http://www.wowhead.com/item=31109/stealthers-helmet-of-second-sight :D

**Comment by Piklo** [comment]
ale to już jest zamknięte :D

**Comment by RastaTinu** [comment]
Dobra dobra, tak mi się napisało :D
