### ISSUE TITLE
[EN][QUEST][Howling Fjord] Of Keys and Cages

### ISSUE THREAD

**Issue by needybastard** [Atlantiss/BugTracker#8398]
This NPC http://www.wowhead.com/npc=24135/greatmother-ankha currently does not give out the quest Of Keys and Cages (Horde) http://www.wowhead.com/quest=11265/of-keys-and-cages

This is a different issue than the Of Keys and Cages that is already on this bugtracker, as that is talking about a quirk with the alliance version, which is available.

The horde quest simply isn't available to pick up from the NPC at all, and therefore neither is it's follow ups. Makes completing I've Toured The Fjord achievement nearly impossible for horde side.

Rev. 5214

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by needybastard** [comment]
Why has this issue been closed when it is still valid and not a duplicate?
