### ISSUE TITLE
[EN][NPC][DROP] Necro Overlord Mezhen

### ISSUE THREAD

**Issue by needybastard** [Atlantiss/BugTracker#8399]
This NPC http://www.wowhead.com/npc=24018/necro-overlord-mezhen

Currently he does not drop "Mezhen's Writings" http://www.wowhead.com/item=34091/mezhens-writings

This is horde version. I am unaware if alliance somehow works. This item is needed to begin the quest http://www.wowhead.com/quest=11453/the-slumbering-king which is once again, horde version.

Rev. 5214

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19402784/64599a9c-9263-11e6-924f-56ca2ad453b3.PNG)

**Comment by xmesaj2** [comment]
Again, use https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by Piklo** [comment]
posted fix at forum:
http://community.atlantiss.eu/index.php?/topic/12045-8399-necro-overlord-mezhen-loot-tables/

**Comment by needybastard** [comment]
Why has this issue been closed when it has not been resolved?

**Comment by 2jasemx** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by RangerTalion** [comment]
bump

**Comment by Piklo** [comment]
@RangerTalion open new issue

**Comment by Samineh** [comment]
#9200
