### ISSUE TITLE
[EN][Spells][Core] Block "one school" spell, blocks "both school" spell

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#84]
Patch 4.2:
"When interrupted while casting a single-school spell such as Mind Flay or Frostbolt, players will now be able to cast dual-school spells such as Mind Spike (Frost and Shadow schools) or Frostfire Bolt (Frost and Fire schools). However, being interrupted while casting a dual-school spell will still interrupt all respective schools as intended."
(http://us.battle.net/wow/en/game/patch-notes/4-2-0#mages)

Unfortunatelly on PTR counterspell on Frostbolt (frost school) or Fireball (fire school) blocks Frostfire Bolt (which shouldn't). But counterspelling Frostfire bolt (fire and frost school) blocks frost and fire spells as intended (this part works).

- Frostbolt (frost) or Fireball (fire) -> Frostfire Bolt (frost/fire) - confirmed
- Mind Flay (shadow) -> Mind Spike (frost/shadow) - confirmed
- Wrath (nature) or Starfire (arcane) -> Starsurge (nature/arcane) - ???
- Immolate (fire) or Shadow bolt (shadow) - Hand of Gul'dan (shadow/fire) - ???

**Comment by Wolffenstein** [comment]
Fixed in rev 4355.
