### ISSUE TITLE
[EN][Guild Achievement][Guild Run to the Throne of the Tides (heroic)]

### ISSUE THREAD

**Issue by bananzis** [Atlantiss/BugTracker#8400]
achievement - http://ru.wowhead.com/achievement=5135

as part of the guild 5 persons, kill the last boss Ozumata guild achievement does not count         http://ru.wowhead.com/npc=106293/ozumat

Our guild is the need to achieve to pass http://ru.wowhead.com/achievement=5143

Tried again and again, nothing came of it, and I boldly announce that this achievement is not working, and it spoils the gaming processes

**Comment by Piklo** [comment]
#7809

**Comment by sunshitwowsucks** [comment]
dupe

**Comment by bananzis** [comment]
I have seen 15% of the players is to achieve ....... OMG

**Comment by pelekon** [comment]
Duplicate.

**Comment by Samineh** [comment]
Bump :+1:
