### ISSUE TITLE
Mustard Dogs!+

### ISSUE THREAD

**Issue by Hardwolfz** [Atlantiss/BugTracker#8402]
**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:
1.  Quest [Mustard dogs!] does not work.
2. Wild mustards doesnt spawn at all
3. Wild mustards should spawn at grassy areas of dalaran

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19409096/4e95dea4-92cd-11e6-90fd-c0186b6c0014.PNG)
