### ISSUE TITLE
Aution House Sales

### ISSUE THREAD

**Issue by Trissme** [Atlantiss/BugTracker#8403]
**Description**: Describe the problem
I wonder if it is normal that some emails from the auction house, which contain gold sales of objects (gems specifically), I do not get paid, even after waiting several hours does not get paid and what is worse, they are automatically deleted  from my mailbox without me having that gold.
**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19410203/1d958156-92e6-11e6-8525-72fc0d8f5c7a.PNG)

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
https://github.com/Atlantiss/BugTracker/blob/master/README.md
