### ISSUE TITLE
[EN][Achievement] Higher Learning

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8404]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/achievement=1956/higher-learning

**Current behaviour**: The achievement is not working. Books are not counted, when you read them

**Expected behaviour**: All the books in the achievement should appear as read after reading them

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: ACore rev. 5217 hash. 1841564f20ef 2016-10-15 00:16:52 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
![revision](https://cloud.githubusercontent.com/assets/16057987/19411040/0404a1fe-92fa-11e6-9c5d-ce1c369d6eef.PNG)

**Comment by coba999** [comment]
works fine, it's random books spawn
