### ISSUE TITLE
[EN][Spell][Rogue][Death Knight] Cloak of Shadows + Frost fever

### ISSUE THREAD

**Issue by arifashaari** [Atlantiss/BugTracker#8406]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: A rogue with cloak of shadows on can still get afflicted by the death knight's frost fever (from casting Chains of Ice)

**Current behaviour**: Not immune to frost fever

**Expected behaviour**: Frost fever should miss and should not be applied

**Steps to reproduce the problem**:

1. Rogue casts Cloak of Shadows
2. Death Knight casts Chains of Ice. 
3. Repeat until frost fever is applied DURING Cloak of Shadows

Photo below 

![image](https://cloud.githubusercontent.com/assets/21334240/19418332/5c73e174-93f4-11e6-914e-16794dc2cb4f.png)

**Revision**: Current server version: rev. 5217

**Comment by strzala** [comment]
http://us.battle.net/forums/en/wow/topic/9753835397
http://us.battle.net/forums/en/wow/topic/9422973273
"This isn't a bug, that's just the way it is."

**Comment by Kejmil** [comment]
chain of ice is physical debuff iirc so it works as intended
same with plague strike+blood plague

**Comment by BialyADI** [comment]
Yeah that was on Retail too, sad but true.
