### ISSUE TITLE
([PL][Zone][Quest]) Problem with Quest on Deepholme

### ISSUE THREAD

**Issue by Dorael22** [Atlantiss/BugTracker#8407]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:([PL][Zone][Quest]) Quest na Deepholm  

**Current behaviour**: Podczas wykonywania misji serwer został wyłączony a po powrocie do gry postać zaczęła spadać no i sie zabiła, po tym odrodziło mnie w The Barrens i nie mam możliwość przejścia misji

**Expected behaviour**:  -

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 4.3.4

**Comment by pelekon** [comment]
In game ticket.

**Comment by XrayAlert05** [comment]
http://community.atlantiss.eu/index.php?/topic/12367-deepholm-portal-bug/
