### ISSUE TITLE
[EN][NPC] Ragnaros HC not resetting properly after wiping on phase 4

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#8408]
**Description**: Ragnaros HC is not resetting properly after wiping in P4

**Current behaviour**: When you wipe in P4,the boss will reset in his current position

**Expected behaviour**: He should ALWAYS reset in his original position(the pool of lava)

**Steps to reproduce the problem**:

1.  Pull Ragnaros HC
2.  Reach Phase 4 of the encounter
3.  Wipe

**Revision**: 5217

**Comment by lamaATS** [comment]
Fixed in rev. 5223
