### ISSUE TITLE
[EN][Hallow's End] Loot not updated for patch 4.2

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#8409]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Wrong loot for Headless Horseman and Loot-Filled Pumpkin (loot not updated for patch 4.2 content)

**Current behaviour**: Headless Horseman drops lvl 80 and lvl 70 rings. Also sometimes he drops 2 rings, he probably should always drop just 1.
http://www.wowhead.com/item=49121/ring-of-ghoulish-glee
http://www.wowhead.com/item=49123/the-horsemans-seal
http://www.wowhead.com/item=49124/wicked-witchs-band
http://www.wowhead.com/item=34073/the-horsemans-signet-ring
http://www.wowhead.com/item=34074/witches-band
http://www.wowhead.com/item=34075/ring-of-ghoulish-delight

Loot-Filled Pumpkin contains lvl 80 helm and sword:
http://www.wowhead.com/item=49126/the-horsemans-horrific-helm
http://www.wowhead.com/item=49128/the-horsemans-baleful-blade
(not sure if it doesn't also contain lvl 70 goods, write a comment if you see one)

**Expected behaviour**: Horseman should drop ilvl 365 rings: 
http://www.wowhead.com/item=71327/band-of-ghoulish-glee
http://www.wowhead.com/item=71328/the-horsemans-signet
http://www.wowhead.com/item=71329/wicked-witchs-ring
http://www.wowhead.com/item=71330/seal-of-the-petrified-pumpkin

Loot-Filled Pumpkin should contain ilvl 365 items:
http://www.wowhead.com/item=71326/the-horsemans-horrific-helmet (5% chance)
http://www.wowhead.com/item=71325/the-horsemans-sinister-saber (5% chance)

**Steps to reproduce the problem**:

1. Join Headless Horseman as tank, dps or heal
2. Kill the Headless Horseman
3. Loot the Horseman
4. Open Loot-Filled Pumpkin. If it's not your first Headless Horseman kill, you won't get the pumpkin. Relog to another character or wait for tomorrow and complete it again.

**Revision**: 5217

**Comment by ounagi21** [comment]
Additional information to support his claims and could be helpful to developers:
http://www.wowhead.com/news=196439/hallows-end-guide-oct-18th-31st

**Comment by pelekon** [comment]
Fixed by Bildo in rev 5220.
