### ISSUE TITLE
[EN][World-Object] Pillar

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8410]
**Description**: [Pillar in-front of Undercity is missing.](http://imgur.com/a/yAxYQ)

**Current behaviour**: Pillar is not there.

**Expected behaviour**: [Pillar should be there.](https://youtu.be/0nYBQBZSGjw?t=1m1s)

**Steps to reproduce the problem**:
1. Take a trip to Undercity.
2. Park your mount in-front of Undercity.
3. Watch the magical sign float in mid air.

**Revision**: rev. 5217

**Comment by wtRCH** [comment]
fix pending.
