### ISSUE TITLE
[EN][Hallow's End] Stink Bombs Away! - alliance

### ISSUE THREAD

**Issue by Dufemi** [Atlantiss/BugTracker#8411]
**Description**: cannot take broom to bomb Undercity

**Current behaviour**: You cannot use dialog option from Gertrude Fenlow to fly to Undercity

**Expected behaviour**: You should be able to ride to undercity and bomb it
 ( http://www.wowhead.com/quest=29054/stink-bombs-away )

**Steps to reproduce the problem**: 
1. take quest
2. try to take a ride from Gertrude Fenlow
3. that`s it

**Revision**: 5217
 hope it is written in correct form and if not I apologize :)

**Comment by snoopyrock85-85** [comment]
horde version doesn't work too.

**Comment by jissabraham** [comment]
plz fix it and update before the event finishes

**Comment by BAndysc** [comment]
Fixed in the last update.
