### ISSUE TITLE
[PL][Hallow's End]  A season for celebration

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8412]
http://www.wowhead.com/quest=29400/a-season-for-celebration
Quest powinien być dostępny na tym patchu a nie jest.

**Comment by xmesaj2** [comment]
Alii: Ironforge
Horda: Orgrimmar

Quest jest dostępny

![wowscrnshot_102016_104809](https://cloud.githubusercontent.com/assets/550384/19553066/ea02cfe4-96b2-11e6-83c9-48f164d39aae.jpg)

**Comment by snoopyrock85-85** [comment]
:D Podziękowania dla Bildo.
