### ISSUE TITLE
[PL][Hallow's End] [NPC] Spoops

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8413]
http://www.wowhead.com/npc=15309/spoops
Nie ma tego npc w undercity, ani w  the ruins of lordaeron. Dodam że jest to questgiver który daje questa http://www.wowhead.com/quest=8312/hallows-end-treats-for-spoops. Z tego wynika, że robienie questów u innkeeperów na treat'y bez tej postaci jest bez sensu, zalegają one potem w bagach.

**Comment by xmesaj2** [comment]
NPC jest. Po wejściu do ruin główną bramą z Tirisfal jest po lewej stronie zaraz przy ścianie.

**Comment by snoopyrock85-85** [comment]
W momencie wstawiania nie był. Podziękowania dla Bildo za szybką naprawę.

**Comment by Myivo** [comment]
Na przyszłość, zgłoszenia prosimy wysyłać zgodnie z szablonem.

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
