### ISSUE TITLE
[PL][Hallow's End] [Quest] Call the headless Horseman

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8414]
http://www.wowhead.com/quest=11405/call-the-headless-horseman
Nie da się oddać pomimo znaku zapytania.

**Comment by Myivo** [comment]
Zgłoszenia prosimy wysyłać zgodnie z szablonem

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
