### ISSUE TITLE
recruit a friend does not work for me

### ISSUE THREAD

**Issue by swepticle** [Atlantiss/BugTracker#8415]
Dear Atlantiss i recruited a friend some days ago and when we started doing quests together we didn't get our triple experience and summon friend did not work. we were in a party and also within 100 yards of each other what am I doing wrong? also when we take the quests it says we got for instance 1500 experience but when we turn them in we only get 500.

**Comment by pelekon** [comment]
Bt is not proper place to ask about game, just make ticket.
