### ISSUE TITLE
[EN][Quest][Zone]The Eye of Whatever DARKSHORE QUEST

### ISSUE THREAD

**Issue by IMPRESSIONER** [Atlantiss/BugTracker#8416]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

put simple twister quest in darkshore is still bugged after at least a year after first being found problematic - what is one supposed to do?skip the quest that leads to the next zone?

**Comment by TranceAccount** [comment]
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use
Thanks in advance.
