### ISSUE TITLE
[PL][Hallow's End] [Object] [Achievement] [Stonetalon Mountains] Candy Bucket

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8417]
http://www.wowhead.com/achievement=965/tricks-and-treats-of-kalimdor nie można zrobić tego pumpkina ze stonetalon mountains, a dokładnie z Krom'gar Fortress. http://www.wowhead.com/quest=29009/candy-bucket. Jest widoczny znak zapytania, ale po kliknięciu go pokazuje you are too far away, pomimo że stoi się obok niego.

**Comment by Dranerys** [comment]
Confirmed

**Comment by Myivo** [comment]
Zgłoszenia prosimy wysyłać zgodnie z szablonem.

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
