### ISSUE TITLE
[PL][Hallow's End] [Quest] Chicken Clucking for a Mint

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8418]
http://www.wowhead.com/quest=8354/chicken-clucking-for-a-mint
Rzecz przedstawia się następująco. Po wykonaniu emotki na http://www.wowhead.com/npc=6741/innkeeper-norman aktualizuje zadanie w questlogu, ale nie można go oddać. Relogi i inne cuda na kiju nie naprawiają sprawy.

**Comment by xmesaj2** [comment]
ten sam problem w alli http://www.wowhead.com/quest=8353/chicken-clucking-for-a-mint

**Comment by Myivo** [comment]
Proszę o dostosowanie się do regulaminu bugtrackera.

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
