### ISSUE TITLE
Seething Pyrelord

### ISSUE THREAD

**Issue by blackswordguy** [Atlantiss/BugTracker#8420]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Seething Pyrelords can't be interrupted by "Mind Freeze" from Death Knights.

**Current behaviour**: Seething Pyrelords don't show reaction about the mind freeze from Death Knights.
**Expected behaviour**: The Seething Pyrelords should be interrupted plus don't cast the "Reflective Shield" anymore, once that in Retail they need to be interrupted just once.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
