### ISSUE TITLE
([EN][Quest][Dragonblight] A Fall from Grace)

### ISSUE THREAD

**Issue by TheSteventh** [Atlantiss/BugTracker#8425]
**Description**: Describe the problem
Cant turn in quest.Retaking quest or relog and reload doesn't work,.
**Current behaviour**: What happens
You follow the steps and when you  go to turn in you simply cant.
**Expected behaviour**: What should happen instead
All is marked as complete and should be able to turn in.
**Steps to reproduce the problem**:
1.Go ring the bells a few times so both body guards go up to the bell and disappear.
2.You talk to High Abbot and he tells you to go to the entrence.
3.At the entrence the event starts and you follow him to a cliff nearby where he jumps.
4.When all is complete you go to turn in but you cant.
**Revision**: Current server version

**Comment by RastaTinu** [comment]
https://github.com/Atlantiss/BugTracker/issues/7845
