### ISSUE TITLE
[PL][Event][Professions][Fishing] Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8426]
http://www.wowhead.com/event=301/301
Jest to bug pozwalający na natychmiastowe wygranie turnieju, oraz zdobycie tytułu http://www.wowhead.com/achievement=306/master-angler-of-azeroth. Z tego co rozumiem zbugowany jest item http://www.wowhead.com/item=19807/speckled-tastyfish oraz npc-et http://www.wowhead.com/npc=15077/riggle-bassbait. NPC-etowi da się oddać questa nawet wtedy kiedy jest już dawno po turnieju, chyba w każdy dzień tygodnia (wymaga to sprawdzenia), a dodatkowo ryby wyłowione się nie resetują.

**Comment by Anhaeyn** [comment]
To akurat niekoniecznie jest wina tego konkretnie itemu. Ogólnie w grze itemy, które mają jakiś tam "termin ważności" jak rybki z tego eventu + jajko z oracles są lekko pobugowane. Działają tylko jeśli je trzymasz w pierwszej torbie, bo jak trzymasz w każdej innej to ten termin ważności nie działa jak należy. Rybki nawet jak czas spadnie do 0, to nie znikną, a jajko po 3 dniach nadal się nie wykluje i będzie miało czas 3 dni do wyklucia. I ten bug właśnie jest wykorzystywany do wygrywania eventu z fishingu.

**Comment by Myivo** [comment]
Zgłoszenia proszę wysyłać zgodnie z szablonem.

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
