### ISSUE TITLE
[PL][Quest][Hallows's End]Stop the Fires

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#8427]
Przez przypadek kliknęłam dodanie problemu, dlatego umieszczam opis w komentarzu.
W Goldshire nie ma w ogóle NPC, który powinien dawać to zadanie. W innych wioskach nie ma ognia, co skutkuje tym, że nie można ukończyć zadania.
Proszę o rozwiązanie problemu, na pewno nie tylko ja chcę mieć tytuł z achivementu. :)
Pozdrawiam.

**Comment by jissabraham** [comment]
just show the fire, npc is there in 3 cities

**Comment by xmesaj2** [comment]
Zgłoszenia wysyłaj zgodnie z szablonem https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
