### ISSUE TITLE
[EN][Item] Sylvanas' Music Box

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#8428]
You can summon the two banshees but they just sit there and nothing happens. They should rise up a little in the air and sing a specific song.

Link of the item: http://www.wowhead.com/item=52253/sylvanas-music-box#reward-from-q
Youtube link from what suppose to happen: https://www.youtube.com/watch?v=FbrLxr7Y4vI
(Before someone ask... No you dont need to be next to Sylvanas in order for the banshees to sing)

P.S. Other items from sealed chest work properly this is the only one with an issue.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19606332/caad45ce-97c1-11e6-98e8-036b31773dbb.PNG)

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
