### ISSUE TITLE
[EN][NPC] Shade of the horseman

### ISSUE THREAD

**Issue by alexsanderr5205** [Atlantiss/BugTracker#8429]
Shade of the horseman bugged. He stay/fly at one place and do nothing.
http://www.wowhead.com/npc=23543/shade-of-the-horseman

**Comment by tomatosz** [comment]
After the fires event, the shade comes down as he should. When people don't kill him then, he floats back to his spawn point and stays there, bugging the event. 
Solution: make him despawn after a set time.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19606313/b3f239ca-97c1-11e6-86b7-bcb607e2117b.PNG)
