### ISSUE TITLE
[EN][Spell]Magic Broom

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8433]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://cata.openwow.com/item=37011
"Summons and dismisses a rideable magical broom! This mount changes depending on your Riding skill and location."

**Current behaviour**: It's useable in arena.

**Expected behaviour**: "You can't use that here"

**Steps to reproduce the problem**:

1. Queue arena
2. Enter battle
3. Use the item

**Revision**: 5222

Updated revision thanks TranceAccount.

**Comment by TranceAccount** [comment]
> Revision: ?
1. Go to http://atlantiss.eu/changelog
2. Look for the latest active revision. (Not the one with "Waiting for update")
3. Substitute ? with the number of that revision.

**Comment by blinkmaster** [comment]
This is not a bug.

**Comment by Fearyourself** [comment]
Yes it is a bug. You're not supposed to be able to use that in arena, or atleast it should have a cast time when in arena. There's nothing on blizzard forums about anybody abusing it like here on Atlantiss. Thanks.

**Comment by blinkmaster** [comment]
http://us.battle.net/forums/en/wow/topic/7005431277 blizzlike, cya
