### ISSUE TITLE
[EN][NPC] Ban'thalos 

### ISSUE THREAD

**Issue by thessera** [Atlantiss/BugTracker#8434]
**Description**: 

NPC ID: 54320
Classification: Rare
Tameable (Spirit Beast)
Added in patch 4.2.0
Link: http://www.wowhead.com/npc=54320/banthalos

**Current behaviour**: 
The NPC does NOT spawn.

**Expected behaviour**: 
Should spawn after the player has complited the "The Sanctuary Must Not Fall" Quest in Hyjal
Link:http://www.wowhead.com/quest=29198/the-sanctuary-must-not-fall

**Revision**: 4.3.4

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19606263/6f36599c-97c1-11e6-9f64-e08651ac4188.PNG)

**Comment by NatsumeLily** [comment]
Just to correct this report for any developers..
That quest DOES NOT make him spawn. It puts you in the phase where you can see if he spawned or not. He follows the same spawn rules as any other rare in the world.

**Comment by ShockRW** [comment]
bump

**Comment by Piklo** [comment]
#8983 reported with issue_template
