### ISSUE TITLE
[EN][NPC] Ghostcrawler

### ISSUE THREAD

**Issue by thessera** [Atlantiss/BugTracker#8437]
**Description**: 
NPC ID: 50051
Classification: Rare
Tameable (Spirit Beast)
Added in patch 4.0.3
Link: http://www.wowhead.com/npc=50051/ghostcrawler

**Current behaviour**: 
Does NOT Spawn

**Revision**:  4.3.4

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19606256/67a92bbe-97c1-11e6-81ba-7f49e867607d.PNG)

**Comment by Piklo** [comment]
#8983 reported with issue_template
