### ISSUE TITLE
[PL][High Priority][Raid-Cata] Nefarian

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#844]
http://www.wowhead.com/zone=5094

* Po wskrzeszeniu kogoś w okolicach platformy Nefariana osoba wskrzeszona spada pod tesktury

* [Shadowflame Barrage](http://cata.openwow.com/spell=78621) Według Dungeon Journal powinien bić 36k(bez resistów). Aktualnie jest 40-45k(z resistami)

# UBER PRIORITY

* LAWY NIE WIDAC I SIĘ PŁYWAĆ NIE DA! XD [link do lawy] Damage zadaje 

UPDATE 29.12.2014 rev 4176

* Na HC lawy nie widziałem, na normie już tak. Niktórzy widzieli z opóźnieniem dosyć długim

**Comment by fafal** [comment]
Wtorek na 1 próbie lava się podniosła po 10s, na każdej kolejnej próbie już nie)zrobiliśmy ok 6 podejśc).
Na jednej próbie Oxycia po chwili staneła w miejscu i nie chciała się ruszyć, Nefarian tak samo.
Czwartek, lava na początku encounteru opadła do poziomu głowy Onyxii także nie dało się przeżyć zaczynając walke :(((

**Comment by adryjan** [comment]
Wczoraj niektórzy u nas na normalu nie widzieli lawy, podniosła się po opóźnieniu, u niektórych w ogóle nawet jak się podniosła nie zadawała dmg. Natomiast 2 osoby które miały opóźnioną lawe po zeskoczeniu z filarów umarli od dmg który lawa zadaje, jednak według nich żadnej lawy już nie było ;p

**Comment by Varchord** [comment]
Platforma nie działa. Nie ma sensu narazie o tym pisac

**Comment by Malylolek** [comment]
Teraz coś Wolf robił z transportami na osi Z (no chyba że źle cl zrozumiałem) więc po upie może coś zacząć działać

**Comment by Varchord** [comment]
Oś Z nie musi być koniecznie wertykalna. Może się ona odnosić do "głębi"
Nie wiem jak to jest w tym core ale trzymym kciuki ^^

**Comment by wojen616** [comment]
Notka: Jeśli ten fix z pozycją na osi z jest już wgrany, to 11.01.2015 o 17 dalej lawa jest zbugowana. :(

**Comment by Malylolek** [comment]
Tak bo fix ma/miał [ strona nie działa i nie wiem co jest no bardziej odpowiednie ;d ] rev.4225 a obecnie na Atlantissie jest rev.4240

My może jeszcze dziś sprawdzimy jak na hc to wygląda jeśli coś to się napisze.

**Comment by Varchord** [comment]
Jak na norm nie dziła to na hc tez nie

**Comment by Malylolek** [comment]
Spite, ale nam na normalnie działało wtedy kiedy nie powinno wiec wiesz może a nóż zadziała :D

**Comment by Pazurek** [comment]
Za pierwszym razem działalo normalnie, lawe wszyscy widzieli itp ale po wipie sie zbugowało jak napisal Wojen. Lawy nie widać albo tylko kilka osób na raid ją widzi przez co nie da się zrobić tego bossa.

**Comment by wojen616** [comment]
Nie do końca, mi lawa przy pierwszej próbie "pojawiła się" jak już część siedziała na słupkach. Za to widziałem jak Humbol wskakuje sobie po niewidzialnej, strasznie deprymujące :D

@Malylolek No właśnie nie wiedziałem jaki jest obecnie rev, bo jestem za głupi, żeby znaleźć info na ten temat gdy wszystko ma status "oczekuje" ;)

**Comment by Malylolek** [comment]
Life hack dla nerdow (.s in)

**Comment by wojen616** [comment]
Dzięki śliczne :)

**Comment by HUMBOL** [comment]
Ktoś się tym zajmuje? Bo fajnie byłoby jednak kiedyś to gónwo zabić.

**Comment by Varchord** [comment]
Nie. Wszyscy czekaja aż ty to naprawisz

**Comment by KrolServera** [comment]
Wiadomo kiedy naprawią ?

**Comment by Qwers** [comment]
Platforma dalej sie buguje. Aktualnie boss nie do ubicia.

**Comment by fafal** [comment]
TRudno, jak nie było fixa żeby działało...

**Comment by melsage** [comment]
siemka, pytanie natury informacyjnej, sa moze jakeis postepy w sprawie fixa nefka ? dzieki za odp jakby co

**Comment by mitim1** [comment]
!bump

**Comment by KrolServera** [comment]
Żałosne, żeby nadal nie zostało naprawione.

**Comment by Varchord** [comment]
Zgadzam sie. Żałosne, ze jeszcze dupska nie ruszyłeś i nie naprawiłeś tego tylko narzekasz. No kurwa ale chyba musisz miec jakiś ważny powód? Pewnie nad stabilnością serwera pracowałeś, nie? To może przygotowywałeś go do przeniesienia na nowa maszynę? Tez nie? 
No to może chociaż progresowałeś cały content heroic łącznie z sinestra. Pewno cholera tez nie

**Comment by Kejmil** [comment]
ja tylko kolorowalem zgloszenia na bt, tak jak w przedszkolu uczyli
to z pewnoscia przeze mnie, zle kolorki dawalem :<

**Comment by Varchord** [comment]
Ja też chce kolorować!  Nie fair :<

**Comment by Varchord** [comment]
Consolidated
https://github.com/Atlantiss/BugTracker/issues/3143
