### ISSUE TITLE
[EN][Quest] To the Digsite

### ISSUE THREAD

**Issue by karhima** [Atlantiss/BugTracker#8440]
You are being followed by Bwemba, the flying troll spirit, from the Rebel Camp to the Digsite. When you arrive there you can turn in the quest to her: http://www.wowhead.com/quest=29133/to-the-digsite

The quest doesn't update for me, I have abandoned and relogged twice. Bwemba is there with me, I'm at the right spot, but I cannot turn it in. I also tried leaving the zone on foot, so Bwemba can follow me easily, then return, but it doesn't register. I'd really like to finish this chain.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19622355/53dcbdb6-98a8-11e6-8fee-f7d7cc2e935f.PNG)

**Comment by karhima** [comment]
rev. 5222

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
