### ISSUE TITLE
([PL][Zone] The Nexus)

### ISSUE THREAD

**Issue by Halficzek** [Atlantiss/BugTracker#8444]
**Description**: Problem z Nexusem podczas zapisu przez rdf

**Current behaviour**: 
1. Po rozpoczęciu dungeona całe party pojawia się w miejscu gdzie nic nie ma. Wszyscy spadają aż w końcu giną. Nie da się w żaden sposób normalnie zrespić. Jedynym sposobem jest wyjście z gry za pomocą alt+f4. Po ponownym zalogowaniu postać pojawia się na cmentarzu niedaleko wejścia do insty, ale już nie jest w grupie z ludźmi z rdf'a. Jedyna próba na ukończenie Nexusa to zrobienie grupy i wejście do instancji przez jej portal ( sposób nie daje bonusu za ukończenie insty ).
1. Drugim problemem jest to, że jeżeli robimy inste w wyżej wymieniony sposób i ktoś zginie, a nie ma nikogo kto mógłby go ożywić, kiedy pojawimy się na cmentarzu nieopodal wejścia do instancji i po przejściu przez portal do niej nadal jesteśmy duchami. Podejście do ciała wewnątrz insty również nie przynosi skutków gdyż po kliknięciu " Accept " gdy ukazuje się komunikat " Ressurect now? " nic się nie dzieje. W tym momencie jedynym sposobem na ożywienie postaci jest powrót na cmentarz i ożywienie u ducha ( Resurrection Sickness ).

**Expected behaviour**: 
1.Po wczytaniu instacji The Nexus grupa powinna znaleźć się przy wejściu wewnątrz niej. 
2. Jeżeli ktokolwiek zginie wewnątrz The Nexus, po pojawieniu się na cmentarzu i przejściu przez portal powinien od razu ożyć.

**Steps to reproduce the problem**:
1. Zapisujemy sie na inste The Nexus za pomocą RDF'a.
2. Po znalezieniu grupy występuje pierwszy z wyżej wymienionych problemów.
3. Po zginięciu wewnątrz The Nexus występuje drugi z wyżej wymienionych problemów.

**Revision**: rev. 5222

**Comment by RastaTinu** [comment]
https://github.com/Atlantiss/BugTracker/issues/8211
