### ISSUE TITLE
Quest "Secrets of the Tower"

### ISSUE THREAD

**Issue by Harlson** [Atlantiss/BugTracker#8445]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Westfall    Quest: "The secrets of the Tower"
**Current behaviour**: Quest nie działa prawidłowo. Postacie w wieży się pojawiają ale później nic się nie dzieje. 

**Expected behaviour**: Po wypiciu eliksiru niewidzialności postać nadal jest widzialna mimo iż pojawia się zmiana statusu na niewidzialny. Postacie w szczycie wieży się pokazują ale później nic się nie dzieje.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19626047/85ea89de-9928-11e6-8ff4-528b5093ce2c.PNG)

**Comment by pelekon** [comment]
Duplicate #2338

**Comment by Harlson** [comment]
I regret that this quest is still not working. We're located in the tower and lime
