### ISSUE TITLE
Instancja "Dedmines"

### ISSUE THREAD

**Issue by Harlson** [Atlantiss/BugTracker#8446]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: "Deadmines"

**Current behaviour**: Instancja nie do ukończenia

**Expected behaviour**: Po zabiciu wszystkich mobów w tartaku powinny się otworzyć drzwi aby umożliwić kontynuację co się nie dzieje. 

**Steps to reproduce the problem**:

1. Wejście na instancje "Dedmines"
2. Zabicie wszystkich mobów przed drzwiami w tartaku
3. Nic się nie dzieje. Drzwi są nadal zamknięte, brak możliwości kontynuowania instancji.

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19626071/1b32eed2-9929-11e6-8c7d-695ec50e6ca8.PNG)

**Comment by pelekon** [comment]
Duplicate #8116
