### ISSUE TITLE
[PL][Trinket] Scales of Life Heroic

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#8447]
Podczas overheal'a powinien pojawic sie buff pokazujacy ile HP zostalo zmagazynowane do max 19283.
W tej chwili item daje tylko sama stamine, przy uzyciu wbija CD ale brak efektu. W załacznikach screen z combat logiem.
![wowscrnshot_102316_174436](https://cloud.githubusercontent.com/assets/10501084/19627544/74fc96c8-9949-11e6-9129-c195e5301dbc.jpg)
![wowscrnshot_102316_174055](https://cloud.githubusercontent.com/assets/10501084/19627548/88acc706-9949-11e6-81ba-544232e06172.jpg)

Item: http://www.wowhead.com/item=69109/scales-of-life
Buff: http://www.wowhead.com/spell=97117/weight-of-a-feather

Obecny rev. 5222

**Comment by Jenovas** [comment]
Fixed rev 5231
