### ISSUE TITLE
[EN] [Paladin] Mana Regeneration too high

### ISSUE THREAD

**Issue by Energumeno1** [Atlantiss/BugTracker#8448]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
I have been on the server for some time playing with different classes and most of them seem to be working fine, but I found a problem with the paladin and the mana regen.
**Current behaviour**: What happens
When casting spells that consume mana with ret paladin it seems like spent mana regenerates incredibly quickly making it very op. I have only tested this in PvE dungeons, still not in PvP, but it may also happen against other players. Most of the times mana is full because as soon as you cast a spell it refills as if you weren't in combat.
**Expected behaviour**: What should happen instead
Mana not regenerating almost every second and having to carry multiple potions in order to refill it, which isn't neccesary at all in the current state.
**Steps to reproduce the problem**:

1. Engage combat with any mob
2. Cast any spell that consumes mana while in combat
3. Wait for it to refill
 

**Revision**: Current server version
4.3.4

**Comment by Piklo** [comment]
maybe http://cata.openwow.com/spell=89901 ?

**Comment by Energumeno1** [comment]
For now it is happening only in dungeons but probably not judgement for the bold as it doesn't regenerate periodically, it is pretty much instant.

**Comment by bonibo** [comment]
I don't know if it is indeed bugged or not, but most certainly the Expected behavior is not 'having to carry multiple pots to refill it' as ret. Ret paladins use strength potions (golemblood), only holy paladins use mana pots (at high gear levels even holy paladins sometimes use int potions -volcanic). I'm only talking about PVE, no idea about PVP

**Comment by Energumeno1** [comment]
Thank you for your responses and education, trying the Dead Mines, mana working just fine, maybe it was because of a single dungeon.
