### ISSUE TITLE
[EN] [Professions] [Plump Dig Rat]

### ISSUE THREAD

**Issue by megas4o** [Atlantiss/BugTracker#8449]
Description: The Item "plump dig rat" is supposed to teach the recipe "dig rat stew" when used at a cooking fire
http://www.wowhead.com/item=78342/plump-dig-rat
Current behavior: You use the item, it cooks the recipe but it doesn't teach it to the profession

Expected behavior: You use the item,cooks the recipe and it's added to the profession

Steps to reproduce the problem:
1. Obtain the item from the mob "dig rat" from southern barrens
2. Use it properly

Revision: 5222

**Comment by krecik88** [comment]
fixed in 5244
