### ISSUE TITLE
[PL][Spell][Druid] Rebirth

### ISSUE THREAD

**Issue by Wyrafinowane** [Atlantiss/BugTracker#845]
Umarłem i kliknąłem release spirit. Druid rzucił na mnie combat ressa (Rebirth) a gdy akceptowałem to wskrzesiło mnie i wyskoczył mi alert o tym że nie mogę wejść do instancji która jest w trakcie progressu.

**Comment by Slotease** [comment]
I have the glyph but people are being spawned with %40 or so and its causing wipes

**Comment by Malylolek** [comment]
Its not possible we use cb ress with glyphs every raid and allways target have 100% hp it mb your friend get hit after resurect ?

**Comment by Slotease** [comment]
It was others who told me that they were spawning with less than %100. So i watched it a few times and it was happening. After they spawned with less than %100 i deleted glyphs and reinstalled them. Maybe that has something to do with it being bugged. This does not happen all the time. I promise you there were not getting hit so it i possible.

**Comment by Aival94** [comment]
I use as well the glyph and they spawn with 100% of life.Are you sure you have the right one activated as there 2 glyphs which change things at rebirth.

**Comment by Slotease** [comment]
I still have two druids, one on horde and one on ally that are not ressing with full health. They are not getting hit after they res. I have casted this after boss fight where there are NO MOBS around and they still comeback %25. I have tried re-applying glyph but that did not help. I cant raid unless this is fixed.

**Comment by Slotease** [comment]
Furthermore there is only one that affects rebirth when ressing. The other one mentioned above is to stop reagents from being used when you cast rebirth so you do not have to carry them anymore. There is only one glyph of rebirth.
