### ISSUE TITLE
[EN][Vendor-Tron 1000]

### ISSUE THREAD

**Issue by megas4o** [Atlantiss/BugTracker#8450]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: The NPC "Vendor tron 1000" is supposed to spawn when the gizelton caravan reaches it's northern destination, but since the caravan isn't scripted and doesn't exist, the npc isn't there
http://www.wowhead.com/npc=12245/vendor-tron-1000

Current behaviour: No caravan,no Npc.

Expected behaviour: Since the npc that is supposed to spawn when the caravan reaches its southern destination is spawned permanently http://www.wowhead.com/npc=12246/super-seller-680 ,the other can be as well

Revision: 5222

**Comment by wienio** [comment]
That's right, but NPC stays all the time beetwen Cenarion Wildlands and Thunder Axe Fortress, near the main road here. I mean Vendor-tron-1000 ofc.

Super-seller-680 stays near crossroads, west from Mannoroc Coven.
Caravan doesn't work but NPCs are still here ;)
