### ISSUE TITLE
Sha'tari skyguard exalted =/= mounts and pets

### ISSUE THREAD

**Issue by Hardwolfz** [Atlantiss/BugTracker#8451]
**Description**: I've hit Exlated with Sha'tari skyguard and i cant purchase anything from npc, the npc doesnt even exist tho.

**Current behaviour**: theres no npc

**Expected behaviour**: Npc with mounts and pets for thos, who're exalted with sha'tari
**Steps to reproduce the problem**:
1. Give npc to sha'tari skyguard
2. make him want trade with exalted guys

**Revision**: 5222

**Comment by Aldergar** [comment]
I had no problem buying mounts,are you sure you checked the right place?

**Comment by arifashaari** [comment]
@Hardwolfz do you even understand what does it mean by "steps to reproduce the problem" xD

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
