### ISSUE TITLE
location range of stone towers, Krom'gar fortress bugged

### ISSUE THREAD

**Issue by kiradeathh** [Atlantiss/BugTracker#8452]
![wowscrnshot_102416_000658](https://cloud.githubusercontent.com/assets/22756798/19633809/cef111d0-998b-11e6-8212-5f44d53b1465.jpg)
![wowscrnshot_102416_000658](https://cloud.githubusercontent.com/assets/22756798/19633830/062c522c-998c-11e6-8615-7b0c07c704d3.jpg)
![wowscrnshot_102416_000658](https://cloud.githubusercontent.com/assets/22756798/19633938/dc7a7c32-998c-11e6-8a8d-24f2c09ae33c.jpg)
![wowscrnshot_102416_000658](https://cloud.githubusercontent.com/assets/22756798/19633949/f6412cf6-998c-11e6-933e-4eb8553552e8.jpg)

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by kiradeathh** [comment]
![wowscrnshot_102416_000658](https://cloud.githubusercontent.com/assets/22756798/19633959/15749d1a-998d-11e6-928c-8ca884c2d692.jpg)

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
