### ISSUE TITLE
[EN][Spell][Priest] Holy Word: Serenity

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#8455]
**Description**: Holy Word: Serenity 25% increased crit buff doesn't affect Renew.

**Current behaviour**: Tested 32 times Renew tick of which 6 were crits. = 18.75% crit chance. My priest's crit chance ~13% crit from intellect and crit rating. If the Serenity buff were functioning, I would have 38% crit with the buff and should gain ~12 crits.

**Expected behaviour**: Renew should gain the 25% crit buff and crit a lot more often.

**Steps to reproduce the problem**:

1. Gain Chakra: Serenity. Use renew on self.
2. Cast Holy Word: Serenity 
3. Measure how many crits out of total ticks.

**Revision** 5224

**Comment by BialyADI** [comment]
It shouldn't work on HoTs. It give you buff for 6s and it will give you 25% Crit for Renew for full Renew duration 12s?

**Comment by Milton3450** [comment]
My mistake then. Closing.
