### ISSUE TITLE
[EN][Quest] [Northern Barrens] [Miner's Fortune]

### ISSUE THREAD

**Issue by karhima** [Atlantiss/BugTracker#8457]
You should turn in the Cats Eye Emerald to Brak Blusterpipe but he doesn't have a dialogue option. I tried to relog but to no avail.

Here's how it should work: http://www.wowhead.com/quest=29015/miners-fortune

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19657954/5eac4f34-9a26-11e6-8dd3-92bc7180fba5.PNG)
