### ISSUE TITLE
[EN][NPC][Throne of the Tides ]Neptulon

### ISSUE THREAD

**Issue by darkmanu** [Atlantiss/BugTracker#8461]
**Description**: Wipe on ozumat, instance gets bugged

**Current behaviour**: If you wipe, you cant do the boss becouse neptulon get bugged

**Expected behaviour**: 

**Steps to reproduce the problem**:
1. Go to ozumat, talk to neptulon and wipe
2.  go again to neptulon talk to him and you will get the buff that should be given to you just at the end of the event
3.  see how neptulone gets bugged

**Revision**: 5224

pd: sory for my bad english

**Comment by xolon** [comment]
Please provide us with more information about the problem an expected behaviour.
Also include wowhead.com or cata.openwow.com links.
