### ISSUE TITLE
Arena 2s

### ISSUE THREAD

**Issue by Schizopathic** [Atlantiss/BugTracker#8462]
**Description**: The Conquest Points still bugged ?

**Current behaviour**: Because i haz 2106 personal raithing and i get 2172 conquest point.

**Expected behaviour**: Ill try to calculate that raithing on arena calculator ... there is 2541 conquest points

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Revision**: 5227

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19764035/42789152-9c41-11e6-8242-b3cf9c074f54.PNG)

**Comment by Schizopathic** [comment]
Revision: 5227

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
