### ISSUE TITLE
[EN][Item] Coren's Chilled Chromium Coaster

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8463]
**Description**: Trinket [Coren's Chilled Chromium Coaster](http://www.wowhead.com/item=71335/corens-chilled-chromium-coaster) has really low proc rate.

**Current behaviour**: Trinket has really low proc rate. Yesterday on Baleroc HC fight which lasted about 5:15 give or take, it procced only 2 times and trinket only has 45 second icd.

**Expected behaviour**: Trinket should have high proc rate. ["This trinket procs almost immediately after the ICD is up on my enhancement shaman. It should for all melee and ranged classes that have a decent crit%."](http://www.wowhead.com/item=71335/corens-chilled-chromium-coaster#comments)

**Steps to reproduce the problem**:

1. Equip the trinket.
2. Stay on dummy for 10-20 min.
3. Count how many times it procs during those 10-20 min.

**Revision**: 5227

**Comment by lamaATS** [comment]
Fixed in rev.  5232
