### ISSUE TITLE
[PL][Quest][Shadowmoon Valley] Dragonmaw Race: The Ballad of Oldie McOld

### ISSUE THREAD

**Issue by snoopyrock85-85** [Atlantiss/BugTracker#8465]
http://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold
Po zaakceptowaniu questa nic się nie dzieje, Oldie http://www.wowhead.com/npc=23340/murg-oldie-muckjaw nie wsiada na mounta i nie zaczyna wyścigu. Przepada nam przez to całkiem znaczna ilość punktów reputacji ( bo wyścigów jest kilka), nie mówiąc o achievemencie http://www.wowhead.com/achievement=1638/skyshattered. W reputacji z frakcją Netherwing (dodatkowa informacja więc daruję sobie linki) lwią część reputacji wbijanej stanowią właśnie te questy chain'owe, co skutkuje tym, że dłużej wbija się ją od honored do revered.
Tutaj wideo do tego q:
https://www.youtube.com/watch?v=pqT9ulCIHr8
Apropos, widziałem już tuziny pytań apropo tego questa na kanałach world i pl - czy działa? (Sam nie zgłosiłem bo musiałem sprawdzić czy istotnie?) Panowie i panie gracze, mam tutaj mały apel : jeżeli widzicie że dany quest, czy jakakolwiek inna rzecz nie działa, bądź nie działa jak należy, zgłaszajcie to na bugtrack'erze. Nie wymaga to tytanicznego wysiłku, wystarczy się stosować do zasad i zgłoszenie zostanie przyjęte.

**Comment by xolon** [comment]
Please use the new template while reporting bugs:
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
