### ISSUE TITLE
Drakes in Grim Batol bugged

### ISSUE THREAD

**Issue by Zipper2013** [Atlantiss/BugTracker#8468]
After feeing them from the nets we are unable to mount them, there only appears a message saying "You are in the wrong zone"

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:

**Comment by lamaATS** [comment]
Fixed (undocumented in changelog)
