### ISSUE TITLE
[EN][NPC][Ratchet] Innkeeper Wiley

### ISSUE THREAD

**Issue by JohannDoe** [Atlantiss/BugTracker#8469]
**Description**: At innkeeper Wiley in Ratchet it's not possible to make the inn one's home. 

**Current behaviour**: After the dialogue, nothing happens.

**Expected behaviour**: Ratchet should be made the new home.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
wowhead link

you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/20059116/cfc58d10-a4f4-11e6-9240-c42f8582ba52.PNG)

**Comment by TranceAccount** [comment]
Confirmed. Yet there is nothing wrong with the npcflag. Maybe you need to be friendly with a faction if you want to set your home there?

**Comment by tomatosz** [comment]
Tried at exalted, and it works fine.

**Comment by TranceAccount** [comment]
It doesn't show the visual setting, but it did silently 🗡
