### ISSUE TITLE
[EN][Quest][Firelands] The Heart and Souls of Flame (Alysrazor Heroic)

### ISSUE THREAD

**Issue by Aizenscar** [Atlantiss/BugTracker#8472]
**Description**: You cannot siphon essences from Alysrazor on heroic on 10 or 25. It doesn't matter if you kill her in the sky, while she is on the ground or as she is gaining her energy.

**Current behaviour**: It is impossible to siphon essences from Alysrazor on heroic.

**Expected behaviour**: Once you kill Alysrazor you should be able to siphon the essences from her corpse.

**Steps to reproduce the problem**:
1. Kill Alysrazor on heroic on 10 or 25.
2. Try to siphon essences.
3. Bitch and whine as you spiral into crippling depression and question every decision you ever made in life.

**Revision**: 5230

**Comment by Aival94** [comment]
Before a week in Normal 10 man you could do it just fine.

**Comment by Aizenscar** [comment]
We have never been able to siphon essences from Alysrazor in 10 or 25 man on normal or heroic.

**Comment by Aival94** [comment]
Will check it today and give screenshot i suppose.

**Comment by Aival94** [comment]
On 10 man Normal you can siphon just fine as you can see here(sorry.Press escaped by accident so you could not see the siphon):
![wowscrnshot_102916_230106](https://cloud.githubusercontent.com/assets/10282971/19833197/1397b4b4-9e42-11e6-9b77-cab254d4e06e.jpg)

but just sometimes does not show the animation.

**Comment by Aizenscar** [comment]
This may be a recent fix as none of the other casters in my guild have been able to loot essences from alysrazor on normal before and we haven't done her on normal for 3 weeks now. However it is still impossible to siphon essences from her in heroic. Thanks for your input, I'll update the report.

**Comment by sunshitwowsucks** [comment]
Siph does not work on alys for hc

**Comment by LaveniaGithub** [comment]
It seems to only be bugged on heroic indeed.

**Comment by KhrystalGH** [comment]
Still bugged.

**Comment by paladincnn** [comment]
Still bugged. Please fix.

**Comment by pwnrip** [comment]
Still bugged please fix this

**Comment by soulthedusha** [comment]
Still bugged. Please fix.

**Comment by paladincnn** [comment]
Still bugged. Now I need to call for a GM for help every week we killed Alysrazor. And it looks like GMs are not always available. Even one of them are online, not all of them have the commands to fix this problem in game. So please fix this!

**Comment by meowmewo** [comment]
Not just for heroic, 3 weeks in a row now i cant Siphon out of 25 normal alyslazor.

**Comment by lamaATS** [comment]
Fixed in rev. 5505
P.S. It was bugged on all difficulties except 10N.
