### ISSUE TITLE
[EN][Paladin] Templar's verdict, Seals of Command, Seal of Truth and Normalized/Unnormalized weapon damage

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8473]
Hi! 

[Abbreviations for clarity; TV: Templar's verdict; SoT: Seal of truth; SoC: Seals of command (talent)] 

A while ago (about 6 months), I noticed some of my numbers being lower than they should be. I've explored several theories and this is the most likely. Math below.

Going through old logs I found an issue with TV and SoC. 
TV, the SoT on-hit and SoC, unlike most abilities/talents that deal damage based on weapon damage, are meant to deal unnormalized weapon damage, as opposed to normalized weapon damage. 
Important: "normalized" weapon damage means the ability's AP scaling is calculated as if the weapon had a speed of 3.3 as opposed to its actual speed; "unnormalized" weapon damage means the ability damage is calculated for the actual weapon speed. Which means unnormalized abilities will deal MUCH higher damage with a slower weapon.  

The two logs I'll be using for sample are a log of our latest Baleroc 10H kill, this thursday  (oct 27th) and an older log from retail of a Baleroc 10H kill on farm (april 7th, 2012).
Averages for the relevant abilities: 
        Atlantiss       Retail
CS:     15030.8         17939.2
TV:     30950.2         43460.1
Melee:  9312.5          10790.8
SoT:    2352.7          3570.3
SoC:    981.9           1548.1  

The big thing to notice here is the percentage difference between Atlantiss and Retail, specifically the difference between the CS delta and the TV/SoT/SoC deltas.     

Retail CS is 19.3% higher and Retail Melee is 16% higher. Which is pretty normal considering the gear and weapon difference (397 Sulfuras on Atlantiss, 416 Gurthalak on Retail). 

TV however, 40.5% higher on retail. Which is too large of a difference to be chalked up to RNG or 4T13. And should be much smaller because Sulfuras' speed is 3.8 whereas Gurthalak is 3.6, meaning TV's unnormalized weapon damage scaling should make it deal proportionally more damage on the Atlantiss logs.  
If my theory regarding TV is correct, Atlantiss TV damage would go from 30950 to 35639, and the Retail average would only be 21.9% higher than Atlantiss which is much more in line with the other ability deltas. 
The same goes for SoC and SoT, although the delta is higher than 20% after recalculating them to unnormalized weapon damage which is due to their double scaling (both AP and SP, and since Ret paladins get SP from AP it kind of double dips, yielding higher scalings); SoC delta remains 37% and SoT delta 31.8%. 

Why do I think this is an important thing to fix? 
As you can see from my short calculations above, TV dealing normalized weapon damage means AP only gets a 3.3 scaling factor, as opposed to 3.6 or in the case of this Tier's best weapon, 3.8. Which for about 20k AP under raid buffs, is very very big. 
Example with 397 Sulfuras for a flat 20k AP, not accounting for any other raid buffs, on average: 
TV calculated with normalized weapondamage:     (((20000/14)*3.3)+3375)*3.4075 =27564.2
TV calculated for unnormalized weapondamage:    (((20000/14)*3.8)+3375)*3.4075 =29998.2
(20000 AP, 3.3 (normalized) and 3.8 weaponspeed (unnormalized), 3375 is the average baseWeapondamage for 397 Sulfuras, and 3.4075 is TV's weapondamage ratio with Crusade and TV glyph.)

I chose to use Baleroc logs for my demonstration and while you could argue the sample size is small I feel like the differences are way too large to be caused by purely sample size or RNG, and Ragnaros and Shannox logs showed similar although slightly smaller anomalies on the numbers. 

Screenshots of both Baleroc logs: 
Atlantiss:  http://i.imgur.com/9fhAT2x.png
Retail:     http://i.imgur.com/YKa6uFf.png

Sources on Normalized/Unnormalized weapon damages, CS, TV and SoT/SoC scalings:
- Normalization: http://wowwiki.wikia.com/wiki/Normalization

"The normalized weapon damage for instant attacks is:
    normalized_damage = base_weapon_damage + (X \* Attack Power / 3.5)
    where X is: 3.3 for two-handed weapons"
- Ability/talent scalings: https://web.archive.org/web/20120218223915/http://elitistjerks.com/f76/t110342-retribution_concordance_4_3_voice_dps

"Attacks: Base damage and Coefficients at L85 

Crusader Strike
(((AP/14) \* 3.3 ) + Weapon damage) \* 135%                       // Notice the "*3.3" indicative of Normalized weapon damage (Crusade increases this ratio to 175.5%)

Templar's Verdict
(((AP/14) \* Weaponspeed) + Weapon damage) \* 235%                // Notice the "*Weaponspeed" indicative of Unnormalized weapon damage (Crusade+Glyph increase this ratio to 340.75%)

Seal of Truth
Seal: (((AP/14) \* Weaponspeed) + Weapon damage) \* 15%"          // This is the "once stacked, deal 15% weapon damage" part of SoT; notice "*Weaponspeed", again

---

**Current behaviour**: What happens
TV, SoC and SoT seem to scale off normalized weapon damage, thus dealing much lower damage than they should. 

**Expected behaviour**: What should happen instead
TV, SoC and SoT should scale off unnormalized weapon damage, therefore scaling with weapon speed and dealing much higher damage with slow weapons.

**Steps to reproduce the problem**:
Hard to "reproduce" per se, since the scalings are incorrect on the server.

**Revision**: 5230 at posting time.

Thank you for reading.

**Comment by BialyADI** [comment]
I think naw is no Weaponspeed normalized and is scale hard naw witch Weaponspeed.
Look on those two SS:
First witch low ilvl hamer and 2.6 Speed:
![wowscrnshot_110316_020115](https://cloud.githubusercontent.com/assets/5780624/19953034/215b6b60-a16a-11e6-8b41-15ef496d0d43.jpg)
And scond witch 3.8 weapon Speed:
![wowscrnshot_110316_020236](https://cloud.githubusercontent.com/assets/5780624/19953035/23f98b72-a16a-11e6-9ecd-ac7f36a9a4d9.jpg)
As you see if you have weapon slower than 3.3 Dmg is lower than it should.
But if you have Weapon faster than 3.3 The Dmg on Templar Verdict is Much Higher than it should like on SS witch 3.8 Weapon.
I just want show haw Dmg change naw when you use weapon witch (low ilvl/Dps) and only Speed of weapon is difference between them.

**Comment by Psychobird7** [comment]
Your difference comes from the pure level difference of the weapons.        

Your testing doesn't show anything...

**Comment by lamaATS** [comment]
Try to test TV when rev. 5238 will be on main I found only one fail in core for 3HP was 225% weapon damage instead of 235% and damage for this spell is not normalized.

**Comment by lamaATS** [comment]
Fixed in rev. 5239
Everything should work properly.

For any new problems/bug please open new issue.
