### ISSUE TITLE
[EN][Quest][Plaguelands: Scarlet Enclave] More Skulls For Brew

### ISSUE THREAD

**Issue by exal99** [Atlantiss/BugTracker#8474]
**Description**: You cannot complete the quest even if you got sufficient crusader skulls.

**Current behaviour**: Nothing happens when you press "continue" on the quest dialog.

**Expected behaviour**: The quest should be turned in

**Steps to reproduce the problem**:
1. Collect 20 or more crusader skulls
2. Try to turn in the quest
3. Watch as nothing happens

**Revision**: 5233

**Comment by Aldurion** [comment]
https://github.com/Atlantiss/BugTracker/issues/3781
