### ISSUE TITLE
[PL][NPC]Trapper Tikaani

### ISSUE THREAD

**Issue by Cranker91** [Atlantiss/BugTracker#8476]
npc nie ma w swojej ofercie sprzedaży http://www.wowhead.com/item=46545/curious-oracle-hatchling a wedlug wowhead'a powinien miec http://www.wowhead.com/npc=27183/trapper-tikaani
![awfwaf](https://cloud.githubusercontent.com/assets/23165876/19850373/7fdc6ad6-9f58-11e6-9d68-15409fff828f.jpg)

**Comment by Piklo** [comment]
w cata możesz dostać go tylko z eventu
https://web.archive.org/web/20120705215430/http://www.wowhead.com/item=46545/curious-oracle-hatchling

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

Następnym razem proszę o dostosowanie się do wzoru.
