### ISSUE TITLE
[EN][Spell][Secondary Skill] Expert Riding

### ISSUE THREAD

**Issue by exal99** [Atlantiss/BugTracker#8477]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I have not trained Expert Riding, yet my trainer don't allow me to train it because in the trainer it's says that I've all ready trained that ability, but in my skillbook it says "See your trainer". I also got two copies of Journeyman Riding in my skillbook.

**Current behaviour**: When I go to the trainer he don't have the ability to train Expert Riding.

**Expected behaviour**: I should be able to train Expert Riding.

**Steps to reproduce the problem**:
I don't know if it is reporducable but I can describe what I did.

1. I trained Journeyman Riding.
2. I trained Flight Master's License
3. Expert Riding dissipated from the trainer

**Revision**: 5233

**Comment by Piklo** [comment]
make relog

**Comment by exal99** [comment]
Thanks it worked!
