### ISSUE TITLE
[EN]{Quest] Let's See What You've Got, Zanzil

### ISSUE THREAD

**Issue by ounagi21** [Atlantiss/BugTracker#8478]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

What is wrong?: During the quest you need to talk to Orgus but he is untalkable
How should it work? We should be able to talk with Orgus

LINKS:
http://www.wowhead.com/quest=26534/lets-see-what-youve-got-zanzil -quest
http://www.wowhead.com/npc=43204/orgus Orgus
https://www.youtube.com/watch?v=Ohjh9gPFJCw&feature=youtu.be -playthrough (WoD but i don't think that roleplays changed during the MoP/WoD)

**Comment by ounagi21** [comment]
This is a copy from another closed issue. Supposedly fixed but still not working.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19856118/6ad60348-9f78-11e6-962e-21c72be8372b.PNG)

**Comment by ounagi21** [comment]
Sorry how does the current server revision relate to this issue?

**Comment by Piklo** [comment]
"DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED"
