### ISSUE TITLE
[EN][Missin in action][Nevershow]

### ISSUE THREAD

**Issue by Ozzaq** [Atlantiss/BugTracker#8480]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version
Hello
Problem with above quest, after taken the quest from NPC, all cages are open and I can't do nothing.
This kind of issue efficently block me to continue game.

Please provide all of player some solving the problem,

Thanky you,

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19866332/12153f30-9fa0-11e6-908b-3c549fbebc2e.PNG)

**Comment by Ozzaq** [comment]
OK sorry for wrong using the BugTracker, but i don't understand your sugestion.
I checked the revision of server and, how this can  solve the problem ?
Sorry for stupid question but i'm new player.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
Description: - you have to describe the problem
Current behaviour: - what is bugged
Expected behaviour: - how it should work
Steps to reproduce the problem: - what dev should do, to reproduce the problem
Revision: - you have to give current server revision

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4098
