### ISSUE TITLE
[EN][Quest][Westfall] Secrets of the Tower )

### ISSUE THREAD

**Issue by BlueHorizon1993** [Atlantiss/BugTracker#8482]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
They dont tell me the secret
**Current behaviour**: What happens
Nothing they stay around and do nothing.
**Expected behaviour**: What should happen instead
They should talk about the plan and tell me the secrets while im unvisible
**Steps to reproduce the problem**:

1. Fix that talk about them
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19884520/619a3888-a01a-11e6-9556-1fc195e130e4.PNG)
