### ISSUE TITLE
[EN][Raid]Lord Rhyolith Normal/Heroic - Volcano Eruption Count Incorrect

### ISSUE THREAD

**Issue by Maxvla** [Atlantiss/BugTracker#8483]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Lord Rhyolith's Volcano Eruption Count Incorrect

**Current behaviour**: What happens
When Lord Rhyolith ignites a volcano, it erupts 5 times, dealing damage and applying 1 stack of increased damage taken.

Atlantiss video:
See 2:36-2:38 - 3 land, then 2 more land further back https://www.youtube.com/watch?v=JGOlRJYf0Sk

Also - https://gyazo.com/1ccb9852dae56548b3cb64d921170a0e
See 4:47 

Two images from our raid video - 
https://gyazo.com/e5a0a4037be7fdf1333b1fdaabc97e63
https://gyazo.com/beae8d55d32d7cc0c9e8859002362bc2

**Expected behaviour**: What should happen instead
See Dungeon Journal - Volcano! (ignore damage figure) 
http://www.wowhead.com/npc=52558/lord-rhyolith#encounter

Active volcanoes should erupt 3 times on 10 man, not 5. Active volcanoes should erupt 6 times on 25 man, you may want to check the behavior on this server. I have no experience with 25 man here.

From Fatboss Heroic 10 Guide - 
https://gyazo.com/e04b3f2d56c844feca118f1c1daaa257
See 2:09 https://www.youtube.com/watch?v=ejAKEb_NSRQ

On a Jesse Cox guide, listen to the voiceover instructions at 1:10-1:24.
https://www.youtube.com/watch?v=mzSvmlvcS7w

**Steps to reproduce the problem**:

Engage Rhyolith and count the eruptions from an active volcano. It should be 3 on 10 man, 6 on 25 man.

**Revision**: ACore Rev 5232

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19888161/2f8a6030-a02d-11e6-8a1d-f986565219d3.PNG)

**Comment by Maxvla** [comment]
Updated. Apologies, first post here.

**Comment by Piklo** [comment]
Rev 5253 O.o?

**Comment by Maxvla** [comment]
Updated again. Sorry, about 6 hours past my bed time.

**Comment by Wolffenstein** [comment]
Should be fixed in rev 5243 (can't test it alone).

**Comment by Jamishman** [comment]
Needs to be reopened
