### ISSUE TITLE
([EN][Quest][ Redridge] To win a war, You Gotta become war)

### ISSUE THREAD

**Issue by BlueHorizon1993** [Atlantiss/BugTracker#8485]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
I dont have the bomb in my tool bar.
**Current behaviour**: What happens
I need to walk back to the men who gives me the quest, normaly you become it automaticly in that orc area, so i activate my quest item "Bravo company field kit" and there is no Bomb
**Expected behaviour**: What should happen instead
Normaly i have the bomb so i can "Seaforium planted at Munitions Hut and Seaforium planted at Blackrock tower
**Steps to reproduce the problem**:

1. Add the Bomb.
2. 
3. 

**Revision**: Current server version Acore rev.5232
http://www.wowhead.com/quest=26651/to-win-a-war-you-gotta-become-war

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/307
