### ISSUE TITLE
[Quest Bug]A Slow Death (Daily) Netherwing Daily in Shadowmoon Valley

### ISSUE THREAD

**Issue by cobruhh** [Atlantiss/BugTracker#8486]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem Once you start Poisoning the Peons after you have collected the glands, Your wow and/or Computer crash. Happened to my wife on several occasions and couldnt figure out what was causing it until i narrowed it down to that one specific quest

**Current behaviour**: What happens Your WoW and/or Computer crashes

**Expected behaviour**: What should happen instead The Game and/or Computer should NOT crash

**Steps to reproduce the problem**:

1.  Fix the Daily
2. Test it
3. Conclude it has been fixed?

**Revision**: Current server version

**Comment by Piklo** [comment]
steps to reproduce the problems
not 
steps to fix the problem
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19933268/163909ce-a113-11e6-909a-65e452af2909.PNG)

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/4290

**Comment by LaveniaGithub** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/4290
