### ISSUE TITLE
[EN][Quest][Deepholm] Forgemaster's Log

### ISSUE THREAD

**Issue by Maskedrapeman** [Atlantiss/BugTracker#8487]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

The quest box that is supposed to show at the end of the quest doesn't appear.
Because of that, I can't access the next quest and since this is a chain of quests, There is no way to complete it and get the fragment.

**Steps to reproduce the problem**:

1. Accept the quest "forgemaster's log"
2. Complete it

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:

**Comment by Aival94** [comment]
First of all. You have wrong title as you speak about different quest that the one you have on title. The quest you report as bugged(and it is) is [Silvermarsh Rendezvous](http://www.wowhead.com/quest=27007/silvermarsh-rendezvous) and this one is reported here as the hall chain quest problem: https://github.com/Atlantiss/BugTracker/issues/3325 and here as a quest alone: https://github.com/Atlantiss/BugTracker/issues/2960.

When you find a bug first search bugtracker and then report it if there is no report yet or make a comment or bump it on the old report to add sth or just make it more active.

Furthermore please try to follow the rules that Atlantiss bugtracker has as Piklo said.
