### ISSUE TITLE
[PL][Warrior][Skill] Charge/Intercept/Intervene i szybko poruszające się Targety.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8490]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Gdy ktoś szybko się porusza np. na Wierzchowcu/Nitro Buty to po daniu na niego Charge/Intercept/Intervene Możemy nie być w Mele Range z nim. 

**Current behaviour**: What happens
Teraz po użyciu Charge/Intercept/Intervene dolatujemy do celu tam gdzie target był podczas naciśnięcia Skilla.

**Expected behaviour**: What should happen instead
Po Charge/Intercept/Intervene powinniśmy być w Mele Range z naszym targetem, nie ważne jak szybko się poruszał podczas Charge/Intercept/Intervene.
Podczas Charge/Intercept/Intervene pozycja Celu powinna być jakoś aktualizowana by do niego dotrzeć.

**Steps to reproduce the problem**:
1. Odpalić np. Nitro Buty i biec.
2. Dać Charge/Intercept/Intervene na dany target z odpalonymi Nitro Butami.

**Revision**: Current server version
5235

**Comment by blinkmaster** [comment]
Mówiłem,  że lepiej dla Was ze działal tak jak działał. To niee, forsujecie bugi które bugami nie są i się z nich nie wycofujecie. to zgłoszenie powinno się nazywać charge jumping mechanic i co więcej,  jest blizzlike.

**Comment by BialyADI** [comment]
Pewno czasem oglądasz filmiki PvP, pooglądaj Warkowe Charge/Intercept powinien Stunować po dotarciu do celu.
Jest lepiej niż było, tylko teraz jak ktoś porusza się szybciej niż zwykłe bieganie to Charge się kończy w miejscu gdzie target był gdy my wciskaliśmy Skilla ^^.

**Comment by lamaATS** [comment]
@blinkmaster mogę prosić o wozwinięcie tego `forsujecie bugi które bugami nie są` ?

**Comment by blinkmaster** [comment]
Postaram się być na ts wieczorem to Cię złapie i powiem ocb

**Comment by BialyADI** [comment]
Sam już nie wiem czy jest lepiej, niby jest lepiej bo Stunuje po dotarciu do celu i ma się czas by dać chociaż Hamstringa, a niby gorzej bo po Charge czasem target jest dalej niż był przed xD.

Kolega na Mouncie i Charge:
![wowscrnshot_110216_212358](https://cloud.githubusercontent.com/assets/5780624/19945994/d0a83972-a142-11e6-9e08-3d5d0e580ac2.jpg)
Gdy przeciwnik stoi w miejscu jest perfekt ale jak biega no to lipka ;x.

**Comment by kadi2** [comment]
Moja teoria
1.Charge powinien stunowac przy Charge cast (pamietajmy, ze na retailu wystepowal delay tak wiec stunowal mniejwiecej w polowie przebutej drogi))
2.Aplikacja Charge stuna powinna wywolywac efekt opadania w pion jezeli nasza postac skakala w jakims kierunku. Podobny efekt wystepuje przy uzyciu Ice Block.

Wedlug BialegoAdiego punkt do ktorego ma szarzowac wojownik powinien byc aktualizowany. Wedlug mnie ten punkt powinien byc ustalany podczas castu inaczej wygladalyby takie zjawiska jak Shadowstep Charge uzyte w tym samym czasie.

@lamaATS <3

**Comment by BialyADI** [comment]
2.Aplikacja Charge stuna powinna wywolywac efekt opadania w pion jezeli nasza postac skakala w jakims kierunku. Podobny efekt wystepuje przy uzyciu Ice Block.

To co napisałeś to fakt, od 4.2 każde CC Stun, Root, itd... po dostaniu go spadasz prosto w dół jeśli byłeś w powietrzu np. wyskoczyłeś czy jak hunter odskoczyłeś Disengage.

**Comment by kadi2** [comment]
@BialyADI  niestety nie kazde CC tak dzialalo. Nie znajdziesz tego efektu przy cheap shocie.

**Comment by BialyADI** [comment]
Jestem jak Max Kolanko nic nie wymyślam, mowie jak jest ;D.
CC które nas unieruchamia czyli Stuny, Rooty powinno powodować że spadamy prosto w dół a czy to dodano w 4.2 czy 4.3 to bez znaczenia w sumie mamy 4.3.4.
To że nie działa to na Cheap Shocie Rogala no cóż różnie to bywa na Atlantissie, nie testowałem tego nie mam Rogalka, a na Warku ciężko to ocenić teraz ;x.

**Comment by blinkmaster** [comment]
charge jump byl naprawiony wlasnie dlatego, ze jak sie dalo rownoczesnie z charge jumpa to sie dostawalo stuna i spadalo na glebe. teraz mamy tak, ze stun i spadanie owszem wystepuje ale dopiero w momencie kiedy ten stun zostanie zaaplikowany. tym samym jest to nie blizzlike i w sumie w niektorych przypadkach na plus dla warriora ale 9/10 myslacych ludzi da szybki odskok od czarge i drugi przed dostaniem stuna i sie ma z 5 -7 yd przewagi :)

**Comment by blinkmaster** [comment]
i druga sprawa - stun z charge na globie podlegal tak jak wspomnial @kadi2 latency delayowi.
dlatego stun sie dostawalo pod koniec biegu ( a raczej w polowie - ale zalezalo to od servera etc ).

**Comment by lamaATS** [comment]
Wszystkie triggerowane spelle przez **Charge Effect** będą castowane w momencie wycastiwanie spella bazowego gdyż w danych z retaila (w końcu je znalazłem) widac że sam **Stun** dla **Charge** jest jakby castowane wcześniej niż sama szarża tyle w temacie co do innych bugów proszę otwierać nowe issue.

**Comment by BialyADI** [comment]
Hmm tak jeszcze myślę że sporo zależy od szybkości Charge Jakiś czas temu (jak jeszcze był Sunwell ;D) czytałem że szybkość Charge to 450% normalnej szybkość, jak to u nas wygląda?
Bo target który szarżujemy przesuwa się w trakcie gdy my dolatujemy do niego.

**Comment by lamaATS** [comment]
Prędkość charge jest 42 zaś bieg gracza jest równy 7 a chód 2.5 żadna z tych liczb nie będzie zmieniona na podstawie danych z internetu bo gdzieś ktoś tak napisał. Jedynie jeśli z danych które mam wykonam obliczenia i wyjdzie inna wartość wtedy dopiero będę się zastanawiać dla mnie aktualnie (visualnie) jest effect bardzo dobry.

**Comment by BialyADI** [comment]
Lamia czyli nie jako będzie tak jak było przedtem?

**Comment by lamaATS** [comment]
Co znaczy tak jak przedtem? Stun będzie w momencie rozpoczęcia szarży i tak było na Retailu (a przynajmniej powinno bo mają ten delay).

**Comment by BialyADI** [comment]
No ok oby było git zobaczmy, tylko Lama pamiętaj o obydwóch nie tylko Charge ale i Intercept ^^.

**Comment by lamaATS** [comment]
Fixed in rev. 5236

**Comment by kadi2** [comment]
@BialyADI Przegladalem sobie jakies filmiki pvp po 4.3. Tak naprawde nie moge znalezc juz zadnego cc ktore byloby odskakiwane w ten sposob.
