### ISSUE TITLE
[PL][Warrior][Talent][Skill] Intervene nie wyciąga z Rootów/Snear gdy ma się talent Warbringer.

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8491]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Intervene powinien wyciągać Warka z Root, Snear effect gdy używa Intervene na kimś z grupy, ważny talent dla Prota PvP który nie działa jak powinien.
Talent: http://cata.openwow.com/spell=57499.
Intervene: http://cata.openwow.com/spell=3411.

**Current behaviour**: What happens
Nie działa. Intervene nie wyciąga z Rootów gdy mamy Talent Warbringer

**Expected behaviour**: What should happen instead
Intervene powinien wyciągać z Rootów gdy mamy Talent Warbringer 

**Steps to reproduce the problem**:

1. Dać Rooty na Wara Prota z Talentem Warbringer.
2. War powinien móc dać Intervene na kimś z Party/Rajdu i powinno go to wyciągnąć z Rootów które ma.

**Revision**: Current server version
5235

**Comment by BialyADI** [comment]
To chyba już ostatni problem jaki znam który dotyczy movementu Warka(Charge/Intercept/Intervene) ;D.

**Comment by BialyADI** [comment]
Aaa jeszcze dla sprecyzowania to chodzi o "movement impairing effects" czyli Rooty i Slowy, to samo co Dispersion u Shadow Preja wycziaga z Rootsów i Snerów.
http://cata.openwow.com/spell=47585
http://cata.openwow.com/spell=57499

**Comment by lamaATS** [comment]
Fixed in rev. 5238
