### ISSUE TITLE
[PL][Raid][Firelands] Alysrazor HC

### ISSUE THREAD

**Issue by CoCConati** [Atlantiss/BugTracker#8492]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Prawdopodobnie błąd z addem Blazing Talon Initiate

**Current behaviour**: Podczas, gdy Alysrazor castuje Firestorm, Blazing Talon Initiate nie castuje Blazing Shield, co więcej nie przestaje castować Fieroblast'ów i Brushfire'ów co dość znacząco utrudnia walkę.

**Expected behaviour**: Blazing Talon Initiate powinien castować Blazing Shield, w momencie gdy Alysrazor castuje Firestorm 
SS z opisem umięjetności: http://www.wowhead.com/spell=101484/blazing-shield

**Revision**: 5235

**Comment by LaveniaGithub** [comment]
Already reported: https://github.com/Atlantiss/BugTracker/issues/8226

**Comment by Mordorianin** [comment]
Potwierdzam
