### ISSUE TITLE
[Quest Bug] The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by cobruhh** [Atlantiss/BugTracker#8493]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Bug: The 'Flawless Arcane Essence' item is obtained from an NPC in terrokar, however when you talk to the NPC he doesnt reply, and he doesnt summon elementals for you to kill and loot the quest item.

**Current behaviour**: Nothing, He is green and you can not talk to him

**Expected behaviour**: You should be able to talk to him. he walks around, summons some trash until he spawns 4 elementals after another, until he summons last Elemental who has Flawless Arcane Essense

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com link
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/8353, https://github.com/Atlantiss/BugTracker/issues/2426
