### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Muvotuc** [Atlantiss/BugTracker#8495]
![wowscrnshot_110216_150122](https://cloud.githubusercontent.com/assets/23215831/19931813/2c02d776-a10e-11e6-93a5-8289b9e5c093.jpg)

**Comment by BialyADI** [comment]
What is the problem ?

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/19933041/6e1b0166-a112-11e6-9b4f-ec5cd3fe2ec2.PNG)

**Comment by Piklo** [comment]
@Muvotuc btw try put it in "backpack"

**Comment by TranceAccount** [comment]
You also require the other 'tokens' in order to complete it.
