### ISSUE TITLE
[EN][Raid] Firelands; Crystallized Firestone droprates.

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8497]
**Description**: Crystallized Firestones have been dropping way too rarely in the past few weeks. 

**Current behaviour**: My guild hasn't seen a single Firestone drop in over 4 weeks, while running 4-5 runs every week, that clear 7/7 or 6/7 heroics consistently. 
The drop percentage seems too low. 

**Expected behaviour**: According to Wowhead data, the droprates should be around 10-17%, with Shannox being slightly lower and Baleroc/Domo being a bit on the higher end. 
http://www.wowhead.com/npc=52498/bethtilac#drops:mode=h10
http://www.wowhead.com/npc=52498/bethtilac#drops:mode=h25
http://www.wowhead.com/npc=52558/lord-rhyolith#drops:mode=h10
http://www.wowhead.com/npc=52558/lord-rhyolith#drops:mode=h25
http://www.wowhead.com/npc=52530/alysrazor#drops:mode=h10
http://www.wowhead.com/npc=52530/alysrazor#drops:mode=h25
http://www.wowhead.com/npc=53691/shannox#drops:mode=h10
http://www.wowhead.com/npc=53691/shannox#drops:mode=h25
http://www.wowhead.com/npc=53494/baleroc#drops:mode=h10
http://www.wowhead.com/npc=53494/baleroc#drops:mode=h25
http://www.wowhead.com/npc=52571/majordomo-staghelm#drops:mode=h10
http://www.wowhead.com/npc=52571/majordomo-staghelm#drops:mode=h25
There's no reliable data on Ragnaros but it's to be assumed that he does also drop Firestones.

**Steps to reproduce the problem**:

1. Go into Firelands, kill 6/7 or 7/7 heroic. 
2. Expect to get 1 Firestone per run on average. 
3. Get no Firestones and cry your eyes out. 

**Revision**: 5235

**Comment by Aldergar** [comment]
Wowhead data isn't correct,the droprate is correct as it is now.

**Comment by Psychobird7** [comment]
Uhm yeah, please bring some proof before pulling things out of your arse.

**Comment by Piklo** [comment]
http://us.battle.net/wow/en/item/71617#dropCreatures
Low - 25%,
Very Low - 7.5%

**Comment by Illusie** [comment]
4th firelands heroic to 6/7 bosses, 0 firestone dropped.
approximately bosses done on heroic last week - 20:0 firestone dropped.

fix please?

**Comment by Psychobird7** [comment]
Bump.

**Comment by Psychobird7** [comment]
Bump!
