### ISSUE TITLE
[EN][NPC] Dragonkins missing in Twilight Highlands

### ISSUE THREAD

**Issue by PGhostek** [Atlantiss/BugTracker#8498]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Hi,

there are lot's of dragonkin NPCs missing in the Twilight Highlands specifically in the Obsidian Forest.

List of missing NPCs:
http://www.wowhead.com/npc=46141/obsidian-pyrewing
http://www.wowhead.com/npc=47372/gloomwing
http://www.wowhead.com/npc=47796/obsidian-viletongue
http://www.wowhead.com/npc=47797/obsidian-charscale
http://www.wowhead.com/npc=47835/scarderis

Revision: Current server version 5235

Thanks!

**Comment by TheRealMcCoy-Atlantiss** [comment]
Any npcs not related to quest available was removed till the rest of the zone can be scripted.

**Comment by PGhostek** [comment]
Great thanks a lot for feedback. Is there anything blocking the scripting of the zone?

**Comment by LaveniaGithub** [comment]
@PGhostek Time :/

**Comment by LaveniaGithub** [comment]
Closing report. When rest of the zone will be scripted, these NPCs will be added as well.
