### ISSUE TITLE
[EN][RAID][CLASS][TALENT][MAGE] Majordomo Staghelm concentration and ignite

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8499]
http://www.wowhead.com/spell=98245/legendary-concentration
http://www.wowhead.com/spell=12654/ignite

**Description**: 
Majordomo Staghelm legendary buff works wierdly with mage ignite talent.
When on 100% concentration, critting for ( example ) 80k should put 32k ignite on the target ( assuming 0 mastery etc). 
Currently it tends to bug out ( not always but often ) and ignite you get is not from 80k crit but from 40k crit ( like ignite not reading you were under conc buff and had done increased damage ).

this also leads me to question if ignite applied is not bugged in such way that direct damage increase buffs / debuffs doesnt increase ignite damage and ignite is always ( often?) from the "original" unmodified spell crit. Hopefully @lamaATS you can take a look at this in the database 

**Current behaviour**: 
Ignite tend to not recognize correctly buffed crit damage from spells thus applying lower damage

**Expected behaviour**: 
ignite should be placed in numbers taken from crit buffed by concentration

**Steps to reproduce the problem**:

1.  engage majordomo
2. get 100% concentration buff
3. spam fireballs / pyroblasts etc to get ignite and see low ignite numbers

**Revision**: 5235

**Comment by kadi2** [comment]
Anyone have WoL from Majordomo's fight?

**Comment by blinkmaster** [comment]
double dipping this custom buff to bosses might indeed be the case, can't check this on this raiding week but gonna check on next

**Comment by Kozakko** [comment]
at least try to fix ignite spreading due to impact talent :P this will be big inprove

**Comment by lamaATS** [comment]
I tested it on my server and I have **Fireball** which deals 100k dmg per crit (100% chance) and **Ignite** tick is 20k when I applied on my self **Legendary Concentration** 100% bonus damage from Majordomo my **Fireballs** started hitting for 200k and each **Ignite** tick was 40k so Ignite works correctly problem is a boss (maybe this damage reduction).

**Comment by Illusie** [comment]
I don't had any problems with it, normally my Ignite at this fight stand at 60-70k at the "pick" which is more or less 35k like, if I had 0% concentration buff.

**Comment by blinkmaster** [comment]
guess i am retarded ;s
