### ISSUE TITLE
[EN][Spell][Mage] Cone of cold doesn't proc Brain Freeze

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#85]
Spell Cone of Cold (http://cata.openwow.com/spell=120) should have 10% to proc Brain Freeze effect (http://cata.openwow.com/spell=44548) but it doesn't. Actually CoC procs Finger of Frost effect which is good - just missing Brain Freeze.

**Comment by blinkmaster** [comment]
bump. major bug for procc management

**Comment by blinkmaster** [comment]
.

**Comment by blinkmaster** [comment]
plz fix this :((

**Comment by blinkmaster** [comment]
it also cant proc mutilple FoF when used against multiple targets, thus its massive proc lose.. bump..

**Comment by kadi2** [comment]
@Aviannaqt 
Fixed in rev.: https://atlantiss.eu/changelog#rev4889
