### ISSUE TITLE
[EN][Talent][Paladin] Inquiry of Faith, Divine Purpose

### ISSUE THREAD

**Issue by Windwalk** [Atlantiss/BugTracker#8501]
Hello,

Please fix those two talents:
1. Inquiry of Faith, after spent 2 or 3 holy power Inquisition last for 12sec, should be 24 after 2 holy powers and 36sec after 3 holy powers.
2. Divine Purpose, when it's active, Zealotry can't be used, why???

**Comment by lamaATS** [comment]
One issue one report.
