### ISSUE TITLE
[EN][Paladin] Holy Power and Inquisition

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8504]
**Description**: Inquisition's duration is always calculated as if cast with 1 Holy power.

**Current behaviour**: Inquisition's duration is always calculated as if cast with 1 Holy power.

**Expected behaviour**: Inquisition should be 4s PER Holy power (12s for Ret)

**Steps to reproduce the problem**:

1. Go hit a dummy
2. Get 2 or 3 Holy power
3. Cast Inquisition
4. RIP

**Revision**: 5236 
I'm assuming this has to do with the Holy Power ability rework.

**Comment by lamaATS** [comment]
I tested it with in all cases of Holy Power and Set Bonus and was working correctly. Sorry about that I will look at this again.

**Comment by Psychobird7** [comment]
It's not a set bonus, it's Inquisition itself that seems to calculate its duration as if cast with 1HP regardless of how much HP you have. hope this helps

**Comment by lamaATS** [comment]
http://cata.openwow.com/spell=90299
This Set Bonus increase duration of **Inquisition**

**Comment by Psychobird7** [comment]
I don't have a Ret 4T11, so my testing was without it (I have 4T12 equipped)

**Comment by lamaATS** [comment]
Fixed in rev. 5237
