### ISSUE TITLE
[EN][Paladin][Talent] Divine Purpose

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8505]
**Description**: Divine Purpose doesn't allow Zealotry to be cast

**Current behaviour**: Unable to cast Zealotry during Divine Purpose

**Expected behaviour**: Zealotry should be usable during Divine Purpose, and should not consume the Divine Purpose buff

**Steps to reproduce the problem**:

1. Spam any abilities that can proc DivinePurpose
2. Get a proc, try to cast Zeal
3. Zealotry doesn't cast

**Revision**: 5236

**Comment by lamaATS** [comment]
Fixed in rev. 5237
