### ISSUE TITLE
([EN][NPC] Aldraan)

### ISSUE THREAD

**Issue by Muvotuc** [Atlantiss/BugTracker#8511]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I have enough tokens to buy the mount but it said i cant buy it.

**Current behaviour**: When i try to buy the mount, it simply said that i dont have enough tokens (but i have)

**Expected behaviour**: It should take my tokens and give me the mount

**Steps to reproduce the problem**:

1. Try to buy the mount
2. Its said you cant
3. And then you fell stupid for farming that long for a mount you can get.

**Revision**: 5237
![wowscrnshot_110516_162023](https://cloud.githubusercontent.com/assets/23215831/20031205/08fca3de-a374-11e6-88ef-5acd4849baec.jpg)

**Comment by Aival94** [comment]
I believe you misunderstood. In order to buy these mounts need both the 100[Halaa Battle Token](http://www.wowhead.com/item=26045/halaa-battle-token) AND 20[Halaa Research Token](http://www.wowhead.com/item=26044/halaa-research-token) and as far as i see in the Screenshot you only have the 20[Halaa Research Token](http://www.wowhead.com/item=26044/halaa-research-token)

**Comment by TranceAccount** [comment]
What @Aival94 said.
