### ISSUE TITLE
[EN][Quest][Deepholm] Take Him to the Earthcaller

### ISSUE THREAD

**Issue by harmyv** [Atlantiss/BugTracker#8512]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)

**Description**: You are supposed to take the guy  to  Earthcaller Yevaa
**Current behaviour**: He goes with you but when you arrive to her nothing happens

**Expected behaviour**: When you arrive there is supposed to be a dialog and the quest should complete

**Revision**: rev. 5237

**Comment by Piklo** [comment]
#7400

**Comment by harmyv** [comment]
Sorry but it is posted there from May and it is still not working and it is needed to be able to do Therazane fraction rep, so i brought it again just to be sure.

**Comment by harmyv** [comment]
Sorry but it is posted there from May and it is still not working and it is needed to be able to do Therazane fraction rep, so i brought it up again just to be sure.

**Comment by pelekon** [comment]
Duplicate.
