### ISSUE TITLE
[EN][Firelands][NPC][Loot Table] Shannox (Flickering Shoulderpads)

### ISSUE THREAD

**Issue by sunshitwowsucks** [Atlantiss/BugTracker#8515]
http://www.wowhead.com/npc=53691/shannox

**Description**: He does not drop shoulders : http://www.wowhead.com/item=71025
Wowhead link from 2011: https://web.archive.org/web/20110711141327/http://www.wowhead.com/item=71025/flickering-shoulderpads

**Current behaviour**: After many kills I have never seen these BOE shoulders drop or on AH, so he doesn't drop them 

**Expected behaviour**: He should drop these shoulders with random enchants:

...of the Feverflare (24.5% chance)
+453 Stamina, +281 Intellect, +192 Haste Rating, +192 Mastery Rating
...of the Fireflash (30.1% chance)
+453 Stamina, +281 Intellect, +192 Critical Strike Rating, +192 Haste Rating
...of the Undertow (18.9% chance)
+453 Stamina, +281 Intellect, +192 Haste Rating, +192 Spirit
...of the Wavecrest (26.5% chance)
+453 Stamina, +281 Intellect, +192 Mastery Rating, +192 Spirit

**Steps to reproduce the problem**:

1. Kill Shannox repeat every week
2. Loot him 
3. No shoulders drop for 3000 times

**Revision**: ACore rev. 5237

**Comment by TranceAccount** [comment]
@Evelinrose you have access to the database? 🐙

**Comment by Sayris9876** [comment]
@TranceAccount No we dont but my guild (same as few others) doing FL since release date and personally I am doing multiple times per week sometimes on alts and all that. Still havent seen it drop or someone wearing those shoulders. I know i might be wrong since i dont main druid but also cant recall seeing this.

**Comment by CatchmeATS** [comment]
^Did not see them since FL release.

**Comment by Evelinrose** [comment]
@TranceAccount Yes i do.

**Comment by sunshitwowsucks** [comment]
rev. 5264 fix by Bildo

**Comment by Fabiana-B** [comment]
Finnaly I got that item on Heroic: https://cdn.discordapp.com/attachments/210533070384660482/255692181216559104/WoWScrnShot_120516_231747.jpg
