### ISSUE TITLE
[EN][Shaman][Elemental] Lava Burst

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8516]
When you cast Lava Burst
And Lava Surge proc (With 4P bonus gear) while you are while casting / loading the spell.

the CD of Lava Burst remain 7 second.
You still have the Proc in your buffs, but you can't use the Instant lava burst.
Yo must wait till a new Lava Surge proc (CD refresh when Surge procing) or till the 7 second CD run out.

Causing a HUGE dps loss to every Elemental Shaman.

I don't know if its problem with the expansion Cataclysm.
I could not find a video of Elemental shaman 4.2 from Retail.

I know on MoP when you cast Lava Burst and while casting it you get Proc
You can shot them both.

How it should work? (According to MoP / Can be "backported" to Cata because its same mechanism.)

You normal cast lava burst
while casting you get lava surge

Normal casted lava burst > executed.
Lava Surge > executed > CD start now.

So Infact as long you have the Lava Surge in your buffs.
you should not get the CD.

*video is from 5.4.8 MoP retail.
https://www.youtube.com/watch?v=PNw5xIRwwyo - 0:58-0:59 (x0.5 to watch carefully)
Lava burst is manual casted. when the spell is still loading/on cast, Lava Surge proc.
CD does not start till the Lava Surge is been used.

*Same issue can also happen with Balance druid Starsurge, need someone with that class to check.

**Comment by LaveniaGithub** [comment]
This is blizzlike in cataclysm, it was changed in mop.

**Comment by LaveniaGithub** [comment]
Proof: https://youtu.be/yI7uCwubink?t=1m31s

**Comment by lamaATS** [comment]
When writing issue please follow template.

**Comment by Illusie** [comment]
@LaveniaGithub gotta, so that how it suppost to be on Cataclysm :'[
@lamaATS what was wrong with the template?

**Comment by lamaATS** [comment]
When you creating new issue you have template pattern with what you should write in the issue (https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md) but I see you removed everything and just you wrote what you wanted if you didn't had any text when creating issue tell as about that because maybe it's some kind of bug. (example what you should see when creating a issue http://imgur.com/a/SoJtB)
