### ISSUE TITLE
[EN][Instance - TBC] Heroic mode for Magisters' Terrace 

### ISSUE THREAD

**Issue by mastercho** [Atlantiss/BugTracker#8517]
I want to report that i can't enter in Magisters' Terrace HC even i complete quest chain from http://wowwiki.wikia.com/wiki/Aldor
 
I Do following quest chain from Aldor:
http://wowwiki.wikia.com/wiki/Quest:Crisis_at_the_Sunwell
http://wowwiki.wikia.com/wiki/Quest:Magisters'_Terrace
http://wowwiki.wikia.com/wiki/Quest:The_Scryer%27s_Scryer
http://wowwiki.wikia.com/wiki/Quest:Hard_to_Kill

But still telling me "Have to be 65lvl..." i do also couple normal runs to see if this fixed, but nothing happens.

What i think possible for this issue is http://wowwiki.wikia.com/wiki/Kalec to be bugged and don't count http://wowwiki.wikia.com/wiki/Quest:Hard_to_Kill like completed.

**Comment by TranceAccount** [comment]
And what level are you?

**Comment by mastercho** [comment]
im 85lvl with 365ilvl if this does matter.

**Comment by TranceAccount** [comment]
Well, I wouldn't know what's wrong then. I did it like 5 months ago. Could be bugged.

**Comment by Navedonar** [comment]
Patch 4.2.0 (2011-06-28): Completion of N [70D] Hard to Kill is no longer required for Heroic Mode.

**Comment by mastercho** [comment]
That was not implemented into Atlantiss core if you check other reports for instance

**Comment by Navedonar** [comment]
http://community.atlantiss.eu/index.php?/topic/12155-8517instance-tbc-heroic-mode-for-magisters-terrace/

**Comment by mastercho** [comment]
Looks like nobody run the query still, cause problem still exist!

**Comment by TranceAccount** [comment]
The fix hasn't got accepted yet.
