### ISSUE TITLE
[Achievment] Intense Cold

### ISSUE THREAD

**Issue by mastercho** [Atlantiss/BugTracker#8518]
I do this run 25 times , everyday in 1 month to gain http://www.wowhead.com/achievement=2036/intense-cold. 

I manage to kill http://www.wowhead.com/npc=26723/keristrasza without stacks , with 1 stack or 2 stacks. Its not giving the achievement. 
Peoples from guild also try it and same for them.

**Comment by Damfee** [comment]
I got it like 4 days ago, just made sure to never go to 3 stacks and it worked. Took me a few tries because I kept getting to 3 stacks, but eventually got it!

**Comment by mastercho** [comment]
`What you do when he stuns you? Cause dispell items is not working``

**Comment by Damfee** [comment]
Trinket first one, then fortitude dk spell 2nd, and third one anti-magic shell at 2 stacks and praying to kill her before it fades off.

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
