### ISSUE TITLE
[EN][Quest][Icecrown] Battle Before The Citadel

### ISSUE THREAD

**Issue by exal99** [Atlantiss/BugTracker#8520]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest http://www.wowhead.com/quest=13864/battle-before-the-citadel is bugged. The quest it self is probably completable, but in order to do in you need to slay a bunch of level 80 elites, which is very hard when you are around that level. The problem is that the quest mounts, located at [[48, 71]][1], that you are supposed to mount in order to slay them doesn't work. When I hover over them the "mount cursor" doesn't appear at all.

**Current behaviour**: The mounts at he forward base camp cannot be mounted therefore making the quest nearly impossible for some.

**Expected behaviour**: You should be able to mount the horses and then kill the commanders

**Steps to reproduce the problem**:

1. Pick up the quest Battle Before The Citadel from Crok Scouergebane. You need to be a death knight in order to get it.
2. Get to the forward base-camp ([[48, 71]][1]) and try to mount a horse with the lance equipped
3. Nothing happens!

**Revision**: 5238

[1]: http://www.wowhead.com/maps?data=210:489710

**Comment by xmesaj2** [comment]
rev. 5403 fixed
