### ISSUE TITLE
[PL][Spell][Paladin] Beacon of Light

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#8521]
**Description**: Beacon of Light transferuje healing z spelli z których nie powinien transferować.
https://web.archive.org/web/20120506202719/http://www.wowhead.com/spell=53563
https://web.archive.org/web/20120506202719/http://www.wowhead.com/spell=53563#comments:id=1587583 - komentarz potwierdzający że beacon nie powinien transferować healingu z holy radiance 

**Current behaviour**: Beacon of Light transferuje healing z holy radiance, seal of insight + z reszty spelli z których powinien.

**Expected behaviour**: Beacon of Light powinien transferować healing tylko z Holy Light za 100%, a z Word of Glory + hota z word of glory jeżeli używamy glyph of the long word (który jest zbugowany), Holy Shock, Flash of Light, Divine Light i Light of Dawn za 50%

**Steps to reproduce the problem**:

1. Użyć Beacon of Light na kimś (może być potrzebne też użycie beacon'a na sobie bo wydaję się że wtedy trochę inaczej u nas działa)
2. Użyć holy radiance na grupie npc (lub graczy, na npc inaczej działać)
3. Widzimy że beacon transferuje z holy radiance healing

**Revision**: 5238

Edit: Może być potrzebne sprawdzenie healing reduce efektów w połączeniu z beaconem. Z tego co pamiętam można było leczyć tanka z 100% healing reduce na Beth'tilacu.

**Comment by lamaATS** [comment]
Fixed in rev. 5245
