### ISSUE TITLE
Flying Bug when Entering on flying mount into a structure/building

### ISSUE THREAD

**Issue by Rakrakk** [Atlantiss/BugTracker#8522]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
"How did I find it? Doing pvp on SW I enter and structure mounted and it did happen, didnt notice I was flying until I leaved it bcoz I was getting rekt and pressed space to jump and I start flying lmao, re-logged in the air and it did go away, turns out mounting again and relogging removes the bug
**Description**: Describe the problem
It's a flying bug, that's all, not suposse to happen ofc
**Current behaviour**: What happens
You start flying without a mount
**Expected behaviour**: What should happen instead
Just get dismounted without being able to fly without a mount and that'is it
**Steps to reproduce the problem**:

1. Get on your flying mount
2. Enter an structure quick after before mounting spell finish casting
3.You will be flying without mount

**Revision**: Current server version
https://www.youtube.com/watch?v=xCnITbI-vzE&feature=youtu.be video showing it
![image](https://cloud.githubusercontent.com/assets/23297095/20040899/d7e67236-a43e-11e6-8837-1e88e6e4338b.png)

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/20040199/56d01408-a453-11e6-86e4-fddcedcf7e74.PNG)

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Rakrakk** [comment]
take it or leave it lmao
