### ISSUE TITLE
[EN][Raid]Ragnaros HC Magma Trap debuff

### ISSUE THREAD

**Issue by muzak00** [Atlantiss/BugTracker#8524]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Magma trap debuff in the Ragnaros HC encounter wroks incorrectly.

**Current behaviour**: On our server whole raid gets the increased magma trap damage debuff (lol).

**Expected behaviour**: Read from the raid journal: The Magma Trap causes the _**TRIGGERING**_ player to take 50% more damage from other Magma Traps. This effect lasts for 45sec and stacks.

**Steps to reproduce the problem**:

1. Get at least 2 people in raid and wobble to rag hc.
2. Trigger Magma Trap by stepping into it with one dude.
3. Only the dude stepping into the trap should get the debuff.

**Revision**: 5238

**Comment by LaveniaGithub** [comment]
Incorrect. 

"Each time a Magma Trap is detonated, the entire raid is debuffed with Magma Trap Vulnerability. This debuff lasts 45 seconds and it increases the damage taken from Magma Trap Eruption by 50%." (source: http://www.icy-veins.com/wow/ragnaros-strategy-guide-normal-heroic)

It is supposed to work like this, a debuff for all of the raid.
