### ISSUE TITLE
[EN][Spell][Hunter]Kill Shot

### ISSUE THREAD

**Issue by Jamishman** [Atlantiss/BugTracker#8525]
Atlantiss Kill Shot

http://puu.sh/s93T9/2d683a9d0b.png
http://puu.sh/s93Vn/33e0276f1d.png

Retail Kill Shot

http://puu.sh/s93XX/aabd687801.png
http://puu.sh/s93ZB/41cc5b6787.png

Kill Shot Formula at Cataclysm release: You attempt to finish the wounded target off, firing a long range attack dealing 150% weapon damage plus [ 30% of RAP + 362 ]. Kill Shot can only be used on enemies that have 20% or less health.

Buff to Kill Shot in retail: Patch 4.0.6 (8-Feb-2011): Kill Shot’s attack power scaling has been increased by 50%.

Current Kill Shot formula should be 150% weapon damage(normalized) + [45% of RAP + 543]

**Description**: The hunter spell Kill Shot hits for significantly less damage on Atlantiss than on retail

**Current behaviour**: Kill Shot damage, especially crit damage, is extremely low

**Expected behaviour**: Kill Shot should deal damage closer to its expected values

**Steps to reproduce the problem**:

1. Be a big dick hunter on Baleroc
2. Press all your buttons until <20%
3. Fire off a Kill Shot
4. Cry when you see the retail logs of other hunters

**Revision**: rev. 5238

**Comment by Psychobird7** [comment]
Math was done, and after some testing there's definitely something wrong with KS.         

Scaling or a multiplier that isn't being applied correctly.

**Comment by xolon** [comment]
I've done Calculations alongside Lama and Dr. Damage addon on training dummy, nothing seemed wrong, including damage reduction from armor. Maybe kill shot is double dipping from FL buff?

**Comment by Jamishman** [comment]
If you just take a look there's no possible way its not fucked up, its doing no damage compared to retail, over 10k on a crit can't be related to RNG.

**Comment by xolon** [comment]
Maybe something changed from patch 4.2 till 4.3.4
Try looking at for an example late DS logs. See of you can find anything

**Comment by Jamishman** [comment]
Ultraxion on retail

http://puu.sh/s9jkJ/74d8fe4df2.png
http://puu.sh/s9jCK/eaa7b5a6bb.png

Its pretty clear that Kill Shot is garbage on Atlantiss

**Comment by xolon** [comment]
Here i can see that average crit is bigger on Baleroc than Ultraxion?

**Comment by Aizenscar** [comment]
The logs on Baleroc are from 4.3.4 with hunters having DS HC gear(same for ultraxion hunters).

**Comment by Jamishman** [comment]
You can see that relative to Autoshot damage, Kill Shot does 0 fucking damage on Atlantiss, I don't know how more clearly to show that to you lol...

**Comment by lamaATS** [comment]
`Current Kill Shot formula should be 150% weapon damage(normalized) + [45% of RAP + 543]`
Probably it's a bug in Client and that's why we have problem on server. 45% of RAP is not multiplied by 150% so anyone of you that have hunter please take your RAP then divide it by 2 and damage will be increase by this number will be good?

Example:
RAP: 10000
bonus: 10000/2 = 5000 (it's the same like take 50%)
current damage from KS = 20000
damage after change = 20000 + 5000 = 25000
25k will be new damage if I will apply this multiplier for RAP (I found this info in simcraft)

**Comment by Jamishman** [comment]
I'm not really sure what you're asking... The correct formula is ((150% weapon damage + (45% of RAP + 543))

Full unbuffed my RAP is 14316, so half of it would be 7158, but that's not really what is needed in the formula. 

6442 would be .45% of RAP adding 543 would make it 6985, but that doesn't account for any buffs at all, so I'm not really sure what you're asking me to calculate.

**Comment by lamaATS** [comment]
I made a big mistake.
Here is corrected what I wanted.

Example:
RAP: 10000
bonus: (10000*0.45)/2 = 4500/2 = 2250 (it's the same like take 50%)
current damage from KS = 20000
damage after change = 20000 + 2250= 22250
22250 will be new damage if I will apply this multiplier for RAP (I found this info in simcraft)

**Comment by Jamishman** [comment]
I'm so confused as to what you're trying to accomplish with that information, are you saying that the current formula is 100% weapon damage + (45%rap + 543)?

**Comment by Jamishman** [comment]
((((14316/14)2.8)+2664.5)1.5)+(0.45*14316)+543 = 15276.75

That is the full formula for 2.8 speed normalization, with Heroic Arathar, completely unbuffed RAP from my hunter.

**Comment by lamaATS** [comment]
543 should be multiplied by 1.5

**Comment by Jamishman** [comment]
((((14316/14)2.8)+2664.5)1.5)+(0.45*14316)+814.5 = 15548.25

**Comment by Jamishman** [comment]
Also there's no talent or glyph that increases Kill Shot damage, for Survival hunters

**Comment by lamaATS** [comment]
Your current damage (without reduction):
`((((14316 / 14) * 2.8) + 2664.5 + 543) * 1.5) + (0.45 * 14316) = 15548.25`
Damage after change will be:
`((((14316 / 14) * 2.8) + 2664.5 + 543 + (0.45 * 14316)) * 1.5) = 18769.35`

**Comment by Jamishman** [comment]
SeemsGood

**Comment by lamaATS** [comment]
For me no other bugs exists (currently not sure if this is a bug but I found it in simcraft)

**Comment by blinkmaster** [comment]
theres always possibility of double dipping of this fireland custom buff on bosses btw @Jamishman

**Comment by Aizenscar** [comment]
Our actual damage done is unaffected by the firelands custom buff, it auto updates via Boss HP I believe. Recount/Logs/Skada shows the actual damage you do without accounting for damage reduction.

**Comment by Psychobird7** [comment]
Aizenscar would be correct there. The FL buff does not affect actual damage numbers or Recount in *any* way.

**Comment by Jamishman** [comment]
Any reason this isn't confirmed?

**Comment by LaveniaGithub** [comment]
Because only a few people have access to core and can check if the current formula is correct or not.

**Comment by lamaATS** [comment]
Fixed in rev. 5245
