### ISSUE TITLE
[EN] Goblins The Lost Isles tornado bug

### ISSUE THREAD

**Issue by zdzicho12** [Atlantiss/BugTracker#8526]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: we just wanted to fly on the ships by helicopter, but it was also bugged it just keep going back to it location, so we decided to swim to the location of ships, we couldnt jump in so we used rocket jump to get inside middle alliance ship, we free'd Thrall from cage he turned us into tornados and we are stuck with it, all the npc's we looking for is not there. we are also way ahead
![wowscrnshot_110716_133105](https://cloud.githubusercontent.com/assets/23312594/20057931/8c99bf1c-a4ee-11e6-89de-ead1247352e2.jpg)
![wowscrnshot_110716_133121](https://cloud.githubusercontent.com/assets/23312594/20057933/8ce630ae-a4ee-11e6-8dc0-220880ac00ab.jpg)
![wowscrnshot_110716_133135](https://cloud.githubusercontent.com/assets/23312594/20057932/8c9a838e-a4ee-11e6-93c1-c5f50ff9105b.jpg)

 the level of the island, is there any way of just teleporting us into orgrimmar or something? it took us rlly long time to walk around island it was really annoying

**Current behaviour**: we cant find quests to conquer the island and go on with storyline

**Expected behaviour**: we should finish quests and leave this doomed island ;-; is there any way to teleport us into orgrimmar skipping the quests? Our nicknames is:
Dadamu (me) and Mamuro (my brother)

**Steps to reproduce the problem**:

1. Talking to thrall on alliance ship, so he can make us tornado and killing alliance marines
2. after killing 50 of them we try to leave tornado(vehicle)
3. we couldnt leave it, we couldnt move so we left the game and when we back, and everytime we relog we have tornado on us and there is no specific Npc for quest continuation

**Revision**: 
![fdsfsfs](https://cloud.githubusercontent.com/assets/23312594/20060651/6e0b2ea6-a4fc-11e6-8fcd-2c17d1db3e69.png)

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/20058917/e407dd42-a4f3-11e6-97df-79ac54f39176.PNG)

**Comment by lamaATS** [comment]
Fixed in rev. 5241
