### ISSUE TITLE
[EN][Spell][Priest] Events for chain channeling Mind flay  are not blizzlike from Atlantiss

### ISSUE THREAD

**Issue by paladincnn** [Atlantiss/BugTracker#8529]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Events sent from atlantiss server while player clipping a mind flay (http://cata.openwow.com/spell=15407) with another  mind flay are wrong. 

**Current behaviour**: What happens
Players will not lose the last tick if you clip a mind flay with another mind flay before the last tick. The last tick will be added to the next cast, the extend mind flay. It was fixed in rev. http://atlantiss.eu/changelog#rev4923. However, the castbar addon Gnosis can not show 4 ticks of the extend mind flay on atlantiss, but it should be able to as shown in the vidoes https://www.youtube.com/watch?v=XUG_g_uftFU and https://www.youtube.com/watch?v=HFKy9RUJ2gA. 

I have been digging codes of Gnosis and doing lots of tests on Atlantiss. And I think I have figured out what happens on this server. While you clipping a mind flay with another mind flay, the server sends a UNIT_SPELLCAST_CHANNEL_STOP event and then a UNIT_SPELLCAST_CHANNEL_START event to the client. But it should send a UNIT_SPELLCAST_CHANNEL_UPDATE event instead of UNIT_SPELLCAST_CHANNEL_STOP according to the event handlers of Gnosis.  After I move the stuffs in 
Gnosis' UNIT_SPELLCAST_CHANNEL_UPDATE handler to UNIT_SPELLCAST_CHANNEL_START handler and make some other changes, Gnosis is able to show 4 ticks of the extend mind flay.  (Shown in the uploaded images)
![gnosis 4 ticks mind flay](https://cloud.githubusercontent.com/assets/3739367/20100297/d38bfff2-a5f7-11e6-9e35-c0176310be0c.png)
![gnosis clip mind flay message](https://cloud.githubusercontent.com/assets/3739367/20100296/d38bb8e4-a5f7-11e6-8a2f-68b951433a72.png)

I am asking the developers for a favor if you could fix this issue so that Gnosis can show ticks correctly without any modification. It would be greatly appreciated.  :)

**Expected behaviour**: What should happen instead
Gnosis should show 4 ticks while you chain channeling mind flay.
**Steps to reproduce the problem**:

1.  Load Gnosis
2.  Chain channeling mind flay
3.  Gnosis always shows 3 ticks.

**Revision**: Current server version
ACore rev. 5239 hash. 6143f49891d3 2016-11-07 18:39:24 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)
Online players: 1003 (max: 1006)
Active connections: 1042 (max: 1046) Queued connections: 0 (max: 0)
Server uptime: 5 Hour(s) 24 Minute(s) 3 Second(s).

**Comment by LaveniaGithub** [comment]
Add revision please. To see revision, type ".s in" in-game.

**Comment by lamaATS** [comment]
Fixed in rev. 5242
