### ISSUE TITLE
[PL][Quest] The Ring of Blood: The Final Challenge

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#853]
http://www.wowhead.com/quest=9977
http://www.wowhead.com/npc=18069

Powinien się wskrzesić po pierwszej śmerci. Pokonanie go po raz drugi dopiero zalicza questa.
Aktualnie umiera, quest zaliczony i na tym koniec

**Comment by starmil1** [comment]
Zabiłem go trzy raz i ani razu nie zaliczyło mi questa

**Comment by Noviush** [comment]
Ciągle nie zalicza zabicia Mogora...

**Comment by Beatlejuicey** [comment]
Tried this quest last night and I'm still having the same problem, can not complete the quest chain.
