### ISSUE TITLE
[EN] All raid bosses(?)

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8530]
**Description**: "Wolffenstein commented on Apr 2, 2015
Dummies and bosses have 13083 armor."

**Current behaviour**: Raid bosses' (and probably all bosses') armour values are too high, so they get 33% damage reduction.

**Expected behaviour**: source: Rawr/Simcraft.
Raid bosses (88) should have 11977 armour, giving them 31.52% damage reduction.
87 mobs should have 11682 armour.
86 mobs should have 11441 armour.
85 mobs should have 11161 armour. 

**Steps to reproduce the problem**:

0. Wolfenstein's comment is old so it might be outdated.
1. Check Cata core? I'm not sure how to prove this.
2. Confirm/fix the boss armour values.
3. Make melees happy.

**Revision**: 5239

**Comment by Psychobird7** [comment]
New issue is up, with proof. #8619

**Comment by xolon** [comment]
Explained better in #8619

**Comment by Piklo** [comment]
@Psychobird7 next time edit your post instead doing another :P
