### ISSUE TITLE
[EN][Raid][Firelands] Majordomo Resetting to 50% Energy After Every Scorpion Cleave

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8531]
Majordomo is resetting to 50% energy every time he casts his cleave, instead of 0%

_This is a known mechanic if he only hits 4 or less people with cleave_

**However**, he is currently doing this while he is hitting the whole raid with cleave (more than 4 people)

Just experienced this November 8th at 3:30AM Server Time

**Comment by stanq87** [comment]
bump, same thing

**Comment by Evelinrose** [comment]
Can confirm this most likely something to do with recent update.

**Comment by LaveniaGithub** [comment]
Please use following template when making bug reports:

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by lamaATS** [comment]
Fixed in rev. 5242
