### ISSUE TITLE
[PL][Mage][Skill] Blink, Glyph dla Blinka

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8533]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Glyph dla Blinka powinien dawać magowi dodatkowe 5y na Blinku nie więcej.
I Blink nie powinien pozwalać na teleport na Budynki czy Góry lub na takie odległości że pokazuje się pasek wczytywania terenu, jak przy komędzie /reload ;D.

**Current behaviour**: What happens
Glyph na Blinka powinien dawać dodatkowo 5y do zasięgu teleportu.

**Expected behaviour**: What should happen instead
Blink nie powinien pozwalać wspinać się na budynki np. na Arathi Basin czy Góry.
Dodatkowo gdy latasz gdzieś wysoko na Wierzchowcu nie powinien cie teleportować na GIGANTYCZNE odległości jeśli użyjesz Blinka w locie czy zeskoku z wysokości ^^.

**Steps to reproduce the problem**:
1. Stań Magiem w teksturach Warka, Warek może być nawet trochę przed Magiem.
2. Daj Blinka, War mimo że był przed Magiem nie może dać Charge, ponieważ Blink Maga z Glyph na owego Blinka pozwala mu teleportować się dalej niż 20y+5y. Blink z Glyphem teleportuje na około 30y a powinien na 25y a zwykły na 20y i tyle.

**Revision**: Current server version
5241

Żeby pokazać jak potrafi teleportować taki Blink, wystarczą 2 ss xD:
Przed Blinkiem:
![wowscrnshot_111016_031521](https://cloud.githubusercontent.com/assets/5780624/20162273/1f203b5c-a6f4-11e6-8fb3-f990c2c2b689.jpg)

I po Blinku i tu jeszcze nie miałem zbugowanego Gliphu.
Przeteleportowało mnie pod Góre i gdzieś Wpizdu z 300y:
![wowscrnshot_111016_031544](https://cloud.githubusercontent.com/assets/5780624/20162294/52040012-a6f4-11e6-8186-faacf4a12898.jpg)
W PvP wykorzystują to gracze, głownie na BG takim jak Arathi Basin i World PvP.

**Comment by mati865** [comment]
Na AV wykorzystują bug z blinkiem żeby dostać się na dachy budynków i bić z AoE ludzi pod nimi.

**Comment by Myivo** [comment]
Co do tytułu zgłoszenia to wystarczy tylko {PL][Mage][Skill] Blink, reszta nie jest potrzebna ; )

**Comment by mati865** [comment]
@Myivo It's a [feature](https://en.wikipedia.org/wiki/Self-documenting_code)

**Comment by BialyADI** [comment]
@lamaATS Lama zobacz to swoim profesjonalnym okiem, niesamowicie wkurwiający bug w PvP(nie dla Maga ^^)

**Comment by TranceAccount** [comment]
Your title is wrong.

> On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player.

**Comment by BialyADI** [comment]
Bump, that Blink is so broken ;D.
i dont know how to title it in english thats why i did it in polish.

**Comment by lamaATS** [comment]
@BialyADI Tytuł nie ma mówić wszystkiego tylko czego dotyczny takie jest jego zadanie i potem jest zawartość aby ładnie to rozpisać na konkretne elementy.

**Comment by BialyADI** [comment]
Tytuł, tytułem ale mógłby ktoś spróbować to naprawić bo magowie to nadmiernie wykorzystują ;x.

**Comment by BialyADI** [comment]
I jak tu się dostać do zasrańca a ten w ciebie bije xD.
![wowscrnshot_113016_193653](https://cloud.githubusercontent.com/assets/5780624/20765935/af20b2f4-b734-11e6-9795-56b69f253629.jpg)

**Comment by fluessig** [comment]
since i cant speak polish i dont know
does this report include that glyph of blink increases blink range even if u then replace the glyph with another one :x

**Comment by mati865** [comment]
@fluessig no, it says that glyph of blink increases range too much.

**Comment by BialyADI** [comment]
Jest w ogóle szansa by ten Glyph i Blinka naprawić?

**Comment by Jenovas** [comment]
rev. 5274 Author: Jenova :: 2016-12-29 17:43 - Waiting for update
Mage:

Reduced the range of Blink should be closer to 20 yards
Reduced the range of Blink with Glyph of Blink should be closer to 25 yards
Blink will no longer teleport players a huge distance when used at a high altitude
