### ISSUE TITLE
[EN] Achievements after faction change

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#8534]
Description: After performing faction change from the Alliance the following achievements have not been changed to their Horde counterparts:

Ghosts in the Dark (http://www.wowhead.com/achievement=5453)
Stormpike Perfection (http://www.wowhead.com/achievement=220)
Drag a Maw (http://www.wowhead.com/achievement=5229)
I'm in the White Lodge (http://www.wowhead.com/achievement=5219)
Double Jeopardy (http://www.wowhead.com/achievement=5231)
Just Another Day in Tol Barad (http://www.wowhead.com/achievement=5718)
Tol Barad Veteran (http://www.wowhead.com/achievement=5417)
Loremaster of Eastern Kingdoms
Loremaster of Kalimdor (not sure about the links for those two, because wowhead shows only one, while there should be separate achievements for both sides as I don't have mine anymore after faction change)
Let's Do Lunch: Darnassus (http://www.wowhead.com/achievement=5842)
Let's Do Lunch: Stormwind (http://www.wowhead.com/achievement=5474)
Let's Do Lunch: Ironforge (http://www.wowhead.com/achievement=5841, most likely, didn't have that one, would make sense though if the other two are screwed)
Fish or Cut Bait: Darnassus (http://www.wowhead.com/achievement=5848)
Fish or Cut Bait: Stormwind (http://www.wowhead.com/achievement=5476)
Fish or Cut Bait: Ironforge (http://www.wowhead.com/achievement=5847, most likely, didn't have that one, would make sense though if the other two are screwed)
Flirt With Disaster (http://www.wowhead.com/achievement=1279)
Flame Warden of Northrend (http://www.wowhead.com/achievement=6008)
Flame Warden of Cataclysm (http://www.wowhead.com/achievement=6011)
Extinguishing Northrend (http://www.wowhead.com/achievement=6007)
Extinguishing Cataclysm (http://www.wowhead.com/achievement=6013)

Current behaviour: The achievements are not properly converted after faction change

Expected behaviour: The achievements should be converted to their horde counterparts

Revision: 5241

Btw. would be nice if you could send a GM to clean up my achievement mess ;_;

**Comment by LaveniaGithub** [comment]
For more achievements affected: https://github.com/Atlantiss/BugTracker/issues/8178

**Comment by tomatosz** [comment]
Can anyone confirm that the the pvp-achievements and fishing/cooking achievements should indeed be converted? The sources I have found so far are these two (both latest version of the page before MoP):
https://wow.gamepedia.com/index.php?title=Faction_Change_service&oldid=2794844#Achievements
http://wowwiki.wikia.com/wiki/Faction_Change_service?oldid=2556920
they both only mention a few pvp-achievements and none of the fishing/cooking ones. 

It does say that 

> Faction-specific achievements include several in the Player-vs-Player category (such as those to defeat the racial leaders and enemy players in their capital cities), and are included in certain world events like Midsummer Fire Festival and Hallow's End. The majority of these achievements follow a 1-to-1 conversion to an opposite-faction equivalent.

however this may only be about the achievements listed, which are mostly the pvp-title achievements.

**Comment by MichaelArchangelo** [comment]
I think it's kinda obvious that Blizzard wouldn't let players keep another faction's achievements after conversion

**Comment by tomatosz** [comment]
Yeha of course, but I meant which achievements you 'keep' the opposite version off. Like if you have earned  the achievement [For the Alliance!](http://www.wowhead.com/achievement=614/for-the-alliance) as Alliance (obviously), then after faction change you will already have [For the Horde](http://www.wowhead.com/achievement=619/for-the-horde) complete without having to defeat the alliance leaders.
And I'm wondering for how many achievements that holds up.

**Comment by pelekon** [comment]
fixed in rev 5561
