### ISSUE TITLE
[EN]Mounts after faction change

### ISSUE THREAD

**Issue by MichaelArchangelo** [Atlantiss/BugTracker#8535]
Description: After performing faction change from the Alliance the following mounts have not been changed to their Horde counterparts:

Armored Brown Bear (http://www.wowhead.com/item=44225)
Black War Bear (http://www.wowhead.com/item=44223)
Black War Mammoth (http://www.wowhead.com/item=43956)
Grand Ice Mammoth (http://www.wowhead.com/item=43961)
Ice Mammoth (http://www.wowhead.com/item=43958)
Mountain Horse (http://www.wowhead.com/item=73838)
Swift Mountain Horse (http://www.wowhead.com/item=73839)
Wooly Mammoth (http://www.wowhead.com/item=44230)

Seeing the mammoth trope, Grand Black War Mammoth (http://www.wowhead.com/item=43959) is probably not converted either, though I'm not sure because I don't have it.

Current behaviour: The mounts are not properly converted after faction change

Expected behaviour: The mounts should be converted to their horde counterparts

Revision: 5241

Btw. would be nice if you could send a GM to convert my mounts after fix

**Comment by tomatosz** [comment]
Does anyone have proof that these mounts should convert? I can't find any, only from the [comments on wowhead](http://www.wowhead.com/item=44230/reins-of-the-wooly-mammoth#comments) it seems that the Wooly Mammoth does since cata:

> By Cambra (3,801 – 9·47) on 2010/07/13 (Patch 3.3.5) 
This mammoth does not get converted when changing factions, I have both ( Blue and red) as an undead. Both counted towards 100 mounts.
edit: It does now .... stupid 4.01 patch. wasted 200 badges

**Comment by MichaelArchangelo** [comment]
Screenshot from mmochampion:
[http://i.imgur.com/dIjfqul.png](url)
Mounts and reps should get converted after faction change. It was changed a bit in MoP when account-wide mounts and other stuff got introduced.

**Comment by tomatosz** [comment]
hm... well, fix on forums:

https://community.atlantiss.eu/index.php?/topic/14672-mounts-faction-change/

**Comment by MichaelArchangelo** [comment]
Thanks! Now if you could fix achievements too I'd love you :D

**Comment by tomatosz** [comment]
you have too much faith in me :P
