### ISSUE TITLE
[EN][Twillight Highlands][Quest] Devourted

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8536]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Quest "Devourted"
http://www.wowhead.com/quest=27377/devoured
https://www.youtube.com/watch?v=NeySF8trsII

**Description**: Oozes keep spawning. there no end for the quest. killed them for 10min.
Impossible to completed.

**Current behaviour**: 

Oozes spawn and spawn.
the NPC cast the spell all the time.
And You don't recieve the quest completed.

**Expected behaviour**: After a few Oozes you kill, the NPC should cast the spell.
You should recieve auto-quest completed and move to the other quest in the line.

**Steps to reproduce the problem**:

No clue?

**Revision**: Current server version

No idea.

**Comment by Anhaeyn** [comment]
Quest is working flawlessy. You have to die to complete this quest.

**Comment by Noviush** [comment]
Well, i died several times and nothing happend...
