### ISSUE TITLE
[EN] Goblins The Lost Isles tornado bug

### ISSUE THREAD

**Issue by zdzicho12** [Atlantiss/BugTracker#8537]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: We just wanted to fly on the ships by helicopter, but it was also bugged it just keep going back to it location, so we decided to swim to the location of ships, we couldnt jump in so we used rocket jump to get inside middle alliance ship, we free'd Thrall from cage he turned us into tornados and we are stuck with it, all the npc's we looking for is not there. we are also way ahead the level of the island.

I'm creating new article because someone closed my old one and i didnt got Any help,
I'm not very skilled and dont have much experience with World of Warcraft and **it's my second time making a request like this so dont close my thread Instantly**

**Current behaviour**: I still cannot see any NPC, and i still have Tornado on my character, my brother also.

**Expected behaviour**: Any contact In Game or anyway of help LIVE

**Steps to reproduce the problem**:

1. ?
2. ?
3. ?

**Revision**: 5242
![wowscrnshot_111016_201813](https://cloud.githubusercontent.com/assets/23312594/20191246/f9247990-a784-11e6-9a05-d5e2d8f72fb7.jpg)

**Comment by zdzicho12** [comment]
#8526

**Comment by LaveniaGithub** [comment]
Zori fixed the problem from what I can see at last report. Maybe you are still bugged because you did it before that update. Please make a ticket in-game so that a GM can help you out.

**Comment by lamaATS** [comment]
Quest working on Dragonwrath realm but You took quest before it has been fixed so You need gm help or just take quest again if possible.
