### ISSUE TITLE
[EN][Raid][Firelands] Majordomo Adds Activating Too Soon

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8538]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Once Majordomo Staghelm leaps in cat form, the [Spirit of the Flame](http://www.wowdb.com/npcs/52593-spirit-of-the-flame) he spawns is activated immediatly

**Current behaviour**: Majordomo leaps, add spawns, add instantly attacks/aggroes player, player dies from 1 shot

**Expected behaviour**: Majordomo leaps, add spawns, add sits still for 1 or 1.5 seconds (from watching the videos looks like could be 1.5), add activates and starts attacking. 

[This video ](https://youtu.be/muuty0AJsec?t=178) shows the correct behavior. You can see it most clearly at 3:04. You can also see it at 4:07, 4:20

**Steps to reproduce the problem**:

1. Pull majordomo
2. Have at least 4 people more than 10 yards away to enable cat form
3. Have 1 tank and 1 melee dps
4. Eventually melee dps will be instant gibbed

**Revision**: 5242

**Comment by Aizenscar** [comment]
Confirmed, please fix. Insanely annoying when progressing 25 HC.

**Comment by lamaATS** [comment]
Yes that's true and I found that [Spell](http://www.wowhead.com/spell=101224/stun-hate) should be cast on spawn.

**Comment by Prodiege** [comment]
Sweet. That looks like the correct duration. I was watching the video at .25 speed to count the time between the add spawning and it activating and seemed to be 1.5 seconds

**Comment by lamaATS** [comment]
Fixed in rev. 5246
