### ISSUE TITLE
[EN][Raid] Majordomo's hitbox is too small

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8540]
**Description**: Majordomo's hitbox, both in scorpion and in cat form, is too small.

**Current behaviour**: Domo's hitbox is so small that you have to almost stand inside of his model and risk getting hit by Flamescythes, and makes keeping up a good DPS uptime as a melee hard during cat form.

**Expected behaviour**: On any retail video you can see his hitbox is much larger than it is on atlantiss right now.
Example here; https://www.youtube.com/watch?v=Eh8rZZm_-ng 

**Steps to reproduce the problem**:

1. Be a melee dps 
2. Try to dps Domo at any point in time, notice you have to stand extremely close
3. Lose DPS.

**Revision**: 5242

**Comment by lamaATS** [comment]
Fixed in rev. 5245
