### ISSUE TITLE
 I am in the lava and I can not escape from it

### ISSUE THREAD

**Issue by JDzejcob** [Atlantiss/BugTracker#8541]
(https://cloud.githubusercontent.com/assets/23396619/20208026/83d0437e-a7eb-11e6-8151-136795afa8a7.PNG)
Can u help me ?

**Comment by Piklo** [comment]
login [here](http://atlantiss.eu/) > if you dont have vote points, vote [here](http://atlantiss.eu/shop/vote) > buy unstuck [here](http://atlantiss.eu/shop/3)

**Comment by LaveniaGithub** [comment]
Use either unstuck from Vote Shop or create a ticket in-game.
