### ISSUE TITLE
[EN][Spell][Mage] Blink

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8542]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://cata.openwow.com/spell=65793
I'm not sure if this is the correct link since there's 100 versions of the Blink spell.

**Current behaviour**: You can blink up a hill or mountain.

**Expected behaviour**: You should be teleported to the foot of the mountain or hill, not upwards or on top of it.

**Steps to reproduce the problem**:

1. There's a hill in the middle of all 3 bases in battle for gilneas battleground
2. Go to the hill where you would normally not be able to walk up (at the cliffs or whatever)
3. Use blink and voila you're standing on top of it.

**Revision**: 5242

**Comment by BialyADI** [comment]
i wrote it in polish https://github.com/Atlantiss/BugTracker/issues/8533.
