### ISSUE TITLE
[EN}Quest[BoreanTundra]Hellscream's Vigill

### ISSUE THREAD

**Issue by Terrar2** [Atlantiss/BugTracker#8543]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Garrosh doesn't appear 
**Current behaviour**:Garrosh doesn't appear 
**Expected behaviour**: Garrosh should appear near Magistrix Kaelana
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Core 5242

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/20213177/888db074-a807-11e6-8c17-bada975b3fc5.PNG)

**Comment by LaveniaGithub** [comment]
As Piklo said, please provide wowhead links to quest, npcs, etc.

I do not remember this quest, but I suppose steps to reproduce this bug is to just take the quest and see? or?

**Comment by Samineh** [comment]
#8696
