### ISSUE TITLE
[EN][Paladin] Beacon of light

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#8546]
**Description**: Took a look at changelog. Beacon of light is now bugged. Other then the spell not transferring heals on pets in the party to the beacon target, the spell worked correctly.

**Current behaviour**: Beacon of light only transfers the heals listed in the tool tip. 

**Expected behaviour**: Beacon of light should transfer the healing spells in the tool tip plus:  Enlightened Judgement talent and Protector of the Innocent talent.

**Steps to reproduce the problem**:

1. ...
2. ...
3. ...

**Revision**: 5245

**Comment by Prodiege** [comment]
That fix hasn't been applied to the server yet. Might want to rephrase this report under the assumption of the current revision (5242). Also, is this about Beacon not activating from healing pets? Or is it about beacon not working from some spells?

**Comment by NatsumeLily** [comment]
It's about the a new revision coming that's incorrectly "fixing" the spell. And I said other then it not transferring heals on pets to beacon targets, the spell worked correctly before this change.

**Comment by NatsumeLily** [comment]
I was incorrect...But I love how my issue #6229 is dusty from being posted 8~ months ago but this was fixed in 1 week which is bullshit.

**Comment by Kejmil** [comment]
welcome to the club, gargoyle is waiting 2 years for correcting his crit dmg :D
