### ISSUE TITLE
[EN][NPC] Mragesh

### ISSUE THREAD

**Issue by Daknyas** [Atlantiss/BugTracker#8549]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: just a minor bug. This npc has a wrong (old) model. You can see its current model here:
http://www.wowhead.com/npc=18286/mragesh

**Current behaviour**: this npc still uses its old model.

**Expected behaviour**:  its model should be updated.

**Steps to reproduce the problem**: 
1. locate this npc;
2. ... notice it's using a wrong model.

**Revision**: 5246

**Comment by Navedonar** [comment]
fix http://community.atlantiss.eu/index.php?/topic/12233-8549npc-mragesh/
