### ISSUE TITLE
[EN][Quest][LAST DITCH EFFORT][Stonetalon Mountains]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#8550]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Problem with the quest [LAST DITCH EFFORT] : http://www.wowhead.com/quest=25891/last-ditch-effort
Not work even after a restart/crash. 

Description : The quest can't be completed because the event is bugged :/ And it is impossible to speak to the NPC to start the event or anything else. 

Current behaviour : Nothing happens, that's the problem. 

Expected behaviour : The NPC who gives the quest turns into a hyppogriff and takes us to Thal'darah Grove to see a bomb explode (like in this video : https://www.youtube.com/watch?v=NQwLKD7EBq0&feature=youtu.be)

Steps to reproduce the problem:

1. This is a quest chain so you have to complete a lot of quests before this one : [Free Our Sisters] +[Rumble in the Lumber... Mill] + [Arcane Legacy] + [Fallowmere Beckons] + [Bombs Away: Mirkfallon Post!] + [Gnome on the Inside] + [It's Up There!] + [No Time for Goodbyes!] + [Warn Master Thal'darah] + [Save the Children!] 

2. Take the quest [Last Ditch Effort] from Master Thal'darah in Thal'Darah Overlook in Stonetalon Mountains. 

3. Nothing happens. The event doesn't begin, the NPC doesn't turns into a hyppogriff. 

Revision: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat

**Comment by Snake90** [comment]
Still bugged.

**Comment by Piklo** [comment]
still no [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by Snake90** [comment]
Still bugged

**Comment by Snake90** [comment]
still bugged

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/3166
