### ISSUE TITLE
[EN][Core] Disappearing mailed items.

### ISSUE THREAD

**Issue by muzak00** [Atlantiss/BugTracker#8551]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: After some latest patch items sometimes disappear after sending them via mail. I lost 3 Cauldrons of Battle, 40 Prismatic Elixirs and 10 Elixirs of the Master that way today. I was using same account for transfering the items.

**Current behaviour**: Arriving mail is empty/missing sent items.

**Expected behaviour**: Arriving mail contains all sent items.

**Steps to reproduce the problem**:

1. Create two characters.
2. Acquire some non-soulboud items.
3. Spam some items from one character to another.
4. Check the lost item ratio.

**Revision**: 5246

**Comment by Theodas** [comment]
I too have had this issue.

**Comment by lamaATS** [comment]
I has been fixed last night.
