### ISSUE TITLE
[EN][GUILD][ACHIVEMENT]

### ISSUE THREAD

**Issue by Bloodwraith** [Atlantiss/BugTracker#8553]
Completing heroic version of "Throne of the Tides" while in guild group does not giving a guild achievement (http://www.wowhead.com/achievement=5135/heroic-throne-of-the-tides-guild-run), which guild need for (http://www.wowhead.com/achievement=5143/guild-cataclysm-dungeon-hero). This is not a first guild with this issue.
Guild name: The Old Camp
Screen: http://oi63.tinypic.com/33avvqd.jpg   ( 4/5 from guild, but still no achievement after all)

**Comment by sunshitwowsucks** [comment]
god damn do people even use search function?

#7809

you are also not following new format for creating an issue

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
