### ISSUE TITLE
[EN][Quest][Stonetalon Mountains.] Free Our Sisters

### ISSUE THREAD

**Issue by KushFace** [Atlantiss/BugTracker#8554]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The opened cages doesnt close itself. So if all cages were opened people cant do this quest until Server Restart, http://www.wowhead.com/quest=25662/free-our-sisters

**Current behaviour**: Cages doesnt close itself.

**Expected behaviour**: Cages close itself after a minute.

**Steps to reproduce the problem**:

1. I
2. Dont
3. Know

**Revision**: ACore rev. 5246

**Comment by Daknyas** [comment]
Reported 4 times.
https://github.com/Atlantiss/BugTracker/issues/2518

**Comment by LaveniaGithub** [comment]
https://github.com/Atlantiss/BugTracker/issues/2518
