### ISSUE TITLE
[EN] [RAID] [FIRELANDS] Ragnaros 25 HC bugs with hammer / pet

### ISSUE THREAD

**Issue by Amerigowarlock** [Atlantiss/BugTracker#8556]
Ragnaros 25 HC man bugs with the hammer dropping inside the lava pool. Pets also go into lava to melee the boss.
I suspect something with Ragnaros' center of gravity or hitbox idk (though melee hit him just fine from where they are supposed to be, and aoe do too)

https://www.youtube.com/watch?v=EPDjC1d0b50

Current behaviour : Pets go into lava to hit the boss. Hammer drops too close to the boss, into lavapool.

Expected behaviour : Pets should melee the boss when in the usual melee range (see 10m or normal mode). Hammer should drop in usual range from the boss (ie on the platform)

Steps to reproduce : 

1 - Put in 25m HC (I can only guess)
2 - Pull the boss
3 - Enjoy

rev. 5246

**Comment by sunshitwowsucks** [comment]
sometimes this bug happens even on 10 man but a wipe usually fixes.

**Comment by Aizenscar** [comment]
Wiping didn't end up fixing it for us.
