### ISSUE TITLE
[EN][Item][The Oracles] Mysterious Egg

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#8558]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
http://www.wowhead.com/item=39878/mysterious-egg
http://www.wowhead.com/item=39878/mysterious-egg#comments
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The item is supposed to "hatch" in 3 days real time and then turn into the clickable Hatched egg to be opened and give a reward.
**Current behaviour**: What happens
However i have had it in my bag for almost a month now and what happens is after the 3rd day it says this: duration 0 sec and it cant be clicked to open.
**Expected behaviour**: What should happen instead
After 3 days it should be clickable and give one of the rewards:
The  Mysterious Egg turns into  Cracked Egg which has the following drop rates according to WoWhead:

 Aged Yolk: 30%
 Cobra Hatchling: 20%
 White Tickbird Hatchling: 19%
 Tickbird Hatchling: 18%
 Proto-Drake Whelp: 8%
 Reins of the Green Proto-Drake: 5%
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Othentik** [comment]
Hi, 

you have to keep it in your main (first) bag, doesn't work if not.

Bye

**Comment by pelekon** [comment]
Read BT rules.
