### ISSUE TITLE
[EN][Spell][Warlock] Soulburn

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8560]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://cata.openwow.com/spell=74434
"Consumes a Soul Shard, allowing you to use the secondary effects on some of your spells.

Drain Life
Summon Imp, Voidwalker, Succubus, Felhunter, Felguard
Demonic Circle: Teleport
Soul Fire
Healthstone
Searing Pain"

**Current behaviour**: Spends a soul shard

**Expected behaviour**: Shouldn't spend a soul shard when getting ready in arena/battlegrounds

**Steps to reproduce the problem**:

1. Queue arena
2. Get Preparation buff
3. Use Soulburn

**Revision**: 5252

It worked until a few days ago.. I don't know if it's on purpose or not, but having to use soul harvest inside arena after summoning a pet before the gates opens is just annoying... ~P.S. Fix soul link and ua LOL~

**Comment by lamaATS** [comment]
Fixed in rev. 5261
