### ISSUE TITLE
[EN][Quest][Healing of Wounding]

### ISSUE THREAD

**Issue by SmaTTeRR** [Atlantiss/BugTracker#8562]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When you pick up the quest in human area as a priest "Healing of Wounded", the human quest where you heal the "Training Dummys" 5 times for your trainer. When you attempt to heal the dummy with flash heal it just heals you instead.
**Current behaviour**: Flash heal won't heal the dummy when targeted it just heals you even though you have the dummy targeted

**Expected behaviour**: You should be able to heal the dummy so you can complete the quest

**Steps to reproduce the problem**:

1.  Start Priest
2.  Finish quest up to Healing of Wounded(level 3)
3.  Attempt to heal "Training Dummy" with flash heal and it heals yourself instead of dummy.

**Revision**: 5214

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
example:
![revision](https://cloud.githubusercontent.com/assets/16057987/20321606/56b9b954-ab76-11e6-91e3-232a6da37b8f.PNG)

**Comment by SmaTTeRR** [comment]
So should I change Revision to rev. 5214?

**Comment by SmaTTeRR** [comment]
Be nice if they would look at the bugs cause I can't even progress my character cause it's in starting area

**Comment by TranceAccount** [comment]
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use

- You forgot a wowhead link to the quest.
- You should do ".s in" in game, and not just copy it from Piklo.

**Comment by Navedonar** [comment]
work
![wowscrnshot_111616_145450](https://cloud.githubusercontent.com/assets/1525533/20349932/e66264b6-ac0c-11e6-9f0f-224ca3f39a53.jpg)
