### ISSUE TITLE
Lord Rhyolith Volcano Eruptions on 10 man

### ISSUE THREAD

**Issue by Jamishman** [Atlantiss/BugTracker#8563]
Description: Describe the problem
Lord Rhyolith's Volcano Eruption Count Incorrect

Current behaviour: What happens
When Lord Rhyolith ignites a volcano, it erupts 5 times, dealing damage and applying 1 stack of increased damage taken.

Atlantiss video:
See 2:36-2:38 - 3 land, then 2 more land further back https://www.youtube.com/watch?v=JGOlRJYf0Sk

Also - https://gyazo.com/1ccb9852dae56548b3cb64d921170a0e
See 4:47

Two images from our raid video -
https://gyazo.com/e5a0a4037be7fdf1333b1fdaabc97e63
https://gyazo.com/beae8d55d32d7cc0c9e8859002362bc2

Expected behaviour: What should happen instead
See Dungeon Journal - Volcano! (ignore damage figure)
http://www.wowhead.com/npc=52558/lord-rhyolith#encounter

Active volcanoes should erupt 3 times on 10 man, not 5. Active volcanoes should erupt 6 times on 25 man, you may want to check the behavior on this server. I have no experience with 25 man here.

From Fatboss Heroic 10 Guide -
https://gyazo.com/e04b3f2d56c844feca118f1c1daaa257
See 2:09 https://www.youtube.com/watch?v=ejAKEb_NSRQ

On a Jesse Cox guide, listen to the voiceover instructions at 1:10-1:24.
https://www.youtube.com/watch?v=mzSvmlvcS7w

Steps to reproduce the problem:

Engage Rhyolith and count the eruptions from an active volcano. It should be 3 on 10 man, 6 on 25 man.

Revision: ACore Rev 5252

**Comment by Maxvla** [comment]
Confirmed still 5 eruptions as of Nov 13 raid.

Image from last night's raid: 

https://gyazo.com/327fff1747b7255801e8217e356f95d5

**Comment by Jenovas** [comment]
Fixed in rev 5253
