### ISSUE TITLE
[EN][Server] Raid reset time

### ISSUE THREAD

**Issue by unkelrara** [Atlantiss/BugTracker#8564]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Before daylight savings time raids would reset at 6 AM, but now they reset at 5 AM.

**Current behaviour**: Raids reset at 5 AM server time.

**Expected behaviour**: Raids should reset at 6 AM server time.

**Steps to reproduce the problem**:

1. Get saved to a raid.
2. Subtract the remaining time on your raid save from the time until 6 AM server Wednesday morning.
3. See that there is a 1 hour discrepancy.

**Revision**: 5252

**Comment by Fabiana-B** [comment]
It happens for me on last night, we tried to kill Majordomo at 4:58 (thinking on the reset at 6AM) and nope, at 5AM the raid was closing :/

**Comment by krecik88** [comment]
config changed
