### ISSUE TITLE
Quest Delegation bugged

### ISSUE THREAD

**Issue by Fearlina** [Atlantiss/BugTracker#8565]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest Delegation not working properly 

**Current behaviour**: Quest Delegation for legendary staff doesent work. I use the item at the perfect time on the perfect spot and my item just dies and i cant loot it. For example Beth'tilac uses smoldering devastation and my items dies and i cant loot it. Happens for 4 weeks in a row and i tried for all 4 bosses combined more then 10 times and always the different fragments die.

**Expected behaviour**: The item should become obtainable and lootable

**Comment by Fabiana-B** [comment]
Confirmed for me, 2 weeks ago, but I do not tried it on last week, so I do not reported it as a bug.

Lemme try this week.

**Comment by Fearlina** [comment]
So annoying all of my guildies have the staff except me and im sure im doing it right because i have done it in retail

**Comment by 2jasemx** [comment]
@BAndysc

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links

**Comment by stanq87** [comment]
u use it to late, u neet to put the gem beforethe spell that suposed to charge get started, so on bethilac u neeet to put it up there before the bosss cats deastation, not during

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
https://github.com/Atlantiss/BugTracker/blob/master/README.md
