### ISSUE TITLE
Samophlange and A burning threat

### ISSUE THREAD

**Issue by facecommer** [Atlantiss/BugTracker#8566]
Most of samophlange quests are not displayed on the map
http://www.wowhead.com/quest=901/samophlange
Also this quest has same issue
http://www.wowhead.com/quest=29090/a-burning-threat

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
