### ISSUE TITLE
[EN][NPC][DROP] Necro Overlord Mezhen

### ISSUE THREAD

**Issue by needybastard** [Atlantiss/BugTracker#8569]
**Description**: http://www.wowhead.com/npc=24018/necro-overlord-mezhen is supposed to drop http://www.wowhead.com/item=34091/mezhens-writings . (This is the horde version of the writings. I can assume that the alliance version also does not drop.)

**Current behaviour**: The overlord does not drop http://www.wowhead.com/item=34091/mezhens-writings

**Expected behaviour**: The overlord should drop http://www.wowhead.com/item=34091/mezhens-writings

**Steps to reproduce the problem**:

1. Kill http://www.wowhead.com/npc=24018/necro-overlord-mezhen
2. Notice he does not drop http://www.wowhead.com/item=34091/mezhens-writings

**Revision**: 5252

**Comment by Piklo** [comment]
I posted fix but it isn't accepted yet
#8399

**Comment by RangerTalion** [comment]
bump

**Comment by Samineh** [comment]
#9200
