### ISSUE TITLE
[PL][Shaman][Skill] Windfury Proc Bije o wiele za wiele, po ostatnim fixie!

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8575]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Windfury Proc bije o wile za wiele.
Hit on Windfury powinien bić za Dmg równa normalnemu ataku + 4430 A. Power i tak 3x.

**Expected behaviour**: What should happen instead
Bije na oko o 10x za mocno, tak jak by do Auto Attaku było dodane wiele więcej niż te 4430 A. power albo jest jakiś dziwny mnożnik.

**Revision**: Current server version
5254
@lamaATS po ostatnim fixie coś się popsuło ;x.
Zobaczyłem to jak jakiś szaman z 2h i WF zapił mnie Procem na BG ;D. 

SS z Dmg na Kukl: Jak wygląda zwykły AA z gówniana bronią i odpowiednio Proc WF:
![wowscrnshot_111816_125457](https://cloud.githubusercontent.com/assets/5780624/20429508/6d79e824-ad8f-11e6-83d1-36d98047ee84.jpg)
![wowscrnshot_111816_125517](https://cloud.githubusercontent.com/assets/5780624/20429510/6fd51792-ad8f-11e6-8209-956ec48e051d.jpg)

**Comment by lamaATS** [comment]
Możesz podać swoje statystki z zakładki Character:
Damange: min-max (nie broni) oraz multiplier (po najechaniu na damage)
Weapon Speed (z opisu broni bez haste)
Attack powera: ze statystyk

**Comment by BialyADI** [comment]
ok juz wysyłam

**Comment by BialyADI** [comment]
![wowscrnshot_111816_130954](https://cloud.githubusercontent.com/assets/5780624/20429656/50194a58-ad90-11e6-8f7b-a1f6e5c9ac3b.jpg)

**Comment by lamaATS** [comment]
Dobra chyba juz wiem ze zepsułęm dosłownie literówka (chyba)
.

**Comment by zorix** [comment]
Poprawka wgrana wymagany restart i kompilacja (nie widać w changelogu).

**Comment by lamaATS** [comment]
Poprawka wgrana wymagany restart i kompilacja (nie widać w changelogu).

**Comment by BialyADI** [comment]
Gitarka, lepiej to zrobić zanim wieczorem Ragnarosry ludzie będą bić, bo Rag dostanie oneszota xD.

**Comment by lamaATS** [comment]
Aż tak źle nie będzie widać to na tej postaci tak mocno ponieważ ma mało AP a tylko ten bonusowy AP jest źle skalowany i dlatego tak mocno bije.

**Comment by BialyADI** [comment]
WF nadal ma 3s icd?

**Comment by lamaATS** [comment]
Tak

**Comment by BialyADI** [comment]
@lamaATS Jeszcze Flametounge bije więcej niż Auto Attack...

**Comment by lamaATS** [comment]
```
Imbue the Shaman's weapon with fire, increasing magical damage done by 5%. Each hit causes x to X additional Fire damage, based on the speed of the weapon. Slower weapons cause more fire damage per swing. Lasts 30 minutes.
```
Gdzie tu jest coś że powinno tylko z spelli/skilli?

**Comment by BialyADI** [comment]
Procuje ok z tego co powinien tylko po ostatnim Fixie, Dmg jest sporo większy niż był przed Fixem.

**Comment by BialyADI** [comment]
Jak teraz jest:
![wowscrnshot_111816_142812](https://cloud.githubusercontent.com/assets/5780624/20431615/433d5eb8-ad9b-11e6-8efe-7686004d3f42.jpg)\

A bił po:
SS z mojego starego ticketu o Flametounge, ta sama postać nic nie zmieniane od dawna nie gram nią, https://github.com/Atlantiss/BugTracker/issues/5439.
![](https://cloud.githubusercontent.com/assets/5780624/12009252/e5b0aac4-ac70-11e5-954c-c3f943b50e1c.jpg)

**Comment by lamaATS** [comment]
Aktualni jest wersja taka że podstawowy damage razy weapon speed co jest raczej zawsze stosowane do spelli który bazują na broni poprzednio był dodatkowy dzielnik nie bliżej nieznanych mi źródeł. Poszukam jeszcze formułę na to ale chyba nigdzie nie znajdę poprawnej (ps. to chyba nawet niema się nawet skalować z SP czy AP)

**Comment by lamaATS** [comment]
Zamknięte bo FT to nie WF

**Comment by BialyADI** [comment]
Jeśli jakoś da radę wyciagnąć formuęł z Addonu DRDamage.

**Comment by BialyADI** [comment]
http://wowwiki.wikia.com/wiki/Flametongue_Weapon
Cataclysm-Logo-Small Patch 4.0.6 (8-Feb-2011): Flametongue Weapon procs now deal roughly 20% less damage.; Flametongue Weapon damage now scales from attack power instead of spell power (for Enhancement shaman only).

Jeśli się aktualnie Skaluje z SP to nie powinien.
