### ISSUE TITLE
[PL][Hunter][Skill] Hunter - Intimidation

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8577]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Intimidation nie ma DR z Control Stunami jak HoJ, Deep Freez. itd.

**Current behaviour**: What happens
Dostajemy całego Stuna(Intimidation) po innym Control Stunie.

**Expected behaviour**: What should happen instead
Intimidation powinien podlegać pod DR.

**Steps to reproduce the problem**:
1. Dać Np. HoJ na target a potem Intimidation.

**Revision**: Current server version
5256

**Comment by TranceAccount** [comment]
Your title is wrong.

> On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player.

**Comment by Fearyourself** [comment]
What is he saying about the DR anyway?

**Comment by lamaATS** [comment]
**Intimidation** doesn't have DR with other controlled stuns like **Deep Freeze** or **Hammer of Justice**

**Comment by BialyADI** [comment]
https://www.warmane.com/changelog?expansion=3&id=49 podobnego Buga mieli na tym serwie którego nazwy nie napisze ;D.
Czasem warto poprzegladać inne changelogi by wiedzieć co u nas może być zle.

**Comment by BialyADI** [comment]
Bump.

**Comment by lamaATS** [comment]
Fixed in rev. 5261
