### ISSUE TITLE
[EN][Talent][Warrior] Bladestorm and disarm

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8578]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: warriors bladestorm does not stop when disarmed but it should

**Current behaviour**: bladestorm does not stop when disarmed, keeps spinning for dmg and it appears as if the warrior is still cc immune (at least i can still see the bladestorm buff on warrior)

**Expected behaviour**: warrior loses bladestorm buff and doesnt spin anymore in addition to the other effects of disarm (in case of priest disarm: warrior immunes the horror effect but is disarmed if u psychic horror bladestorm)

**Steps to reproduce the problem**:

1. pick up bladestorm talent
2. use bladestorm
3. disarm warrior in bladestorm

**Revision**: 5256

it used to work in the past, not sure why its not possible now
i tested only priest and rogue disarm, because i didnt have access to two warriors nor a hunter

http://cata.openwow.com/spell=51722 dismantle (rogue disarm)
http://cata.openwow.com/spell=676 disarm (warrior disarm)
http://cata.openwow.com/spell=64044 psychic horror (priest disarm)
http://cata.openwow.com/spell=50541 clench (hunter pets disarm)
http://cata.openwow.com/spell=91644 snatch (other hunter pets disarm)
http://cata.openwow.com/spell=46924 bladestorm

proof:
https://www.youtube.com/watch?v=8FF3wCLE-Go (2:11)

**Comment by BialyADI** [comment]
Potwierdzam War po Disarmie bije z plaskacza wszystkich do okoła ;D.

Błąd prawdopodobnie powstał po naprawie rev. 5245 "When the target will be disarmed all the buffs that are requiring weapons or shield will remain on the target"

Blade strom jest wyjątkiem od tej reguły jest to nawet zaznaczone w opisie Skilla.
"While under the effects of Bladestorm, you do not feel pity or remorse or fear and you cannot be stopped unless killed or disarmed"

**Comment by lamaATS** [comment]
Fixed in rev. 5257
