### ISSUE TITLE
[EN][Talent][Rogue] Shadowsteps positioning

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8579]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: shadowstep does not always position the rogue correctly

**Current behaviour**: if u shadowstep to someone who stands with his back to an edge u might fall down when u should step inside his character, also u cannot shadowstep to flying targets on atlantiss u will just port to the ground below them

**Expected behaviour**: shadowstep ports you to the player even in air and if theres an edge behind the character (ie u will fall down from using shadowstep) u stand as close to the edge without falling down as u can (if the enemy stands right on the edge u will literally be inside the enemy)

**Steps to reproduce the problem**:

1. spec subtlety and get shadowstep talent
2. mount up an enemy and fly into the air
3. put an enemy close to an edge he could fall off and turn his back to the edge
4. use shadowstep on both enemies

**Revision**: 5256

http://cata.openwow.com/spell=36554 shadowstep
http://cata.openwow.com/spell=49377 feral charge

feral charge cat should also work like shadowstep (the part of not falling down an edge just because an enemy positioned his back to it)
(feral charge cat into the air works) cut this ive mistaken feralcharge with skullbash :l

proof:
https://www.youtube.com/watch?v=CFxUvpQk1ws (0:27)
https://www.youtube.com/watch?time_continue=76&v=K1J3UEHEivM (1:12)

now i know theres a polish ticket about shadowstep open but i have no clue what they are talking about thats why i opened this, if u could merge the polish one into this (in case they are about the same) i would appreciate it a lot :)

**Comment by arifashaari** [comment]
shadowstepping on swimming enemies will also position the rogue on the ground at the bottom

**Comment by fluessig** [comment]
feral charge also doesnt work correctly underwater, skullbash under water only works if youre not in the same horizontal as ur target

warrior  charge in water also doesnt work, it always says no path available
https://www.youtube.com/watch?v=Z0HX-cS1_5E (1:16+1:31)
charge intercept and intervene i guess

**Comment by Genomnomnomnom** [comment]
The edge part is the most frustrating since I'm used to fully working Shadowstep and I make mistakes everytime someone covers his back.

**Comment by Zhalox123** [comment]
I think when a target has its back turned against the wall the rouge shouldnt be able to step on the target also I readed on wowhead about it and it says there
--if target is against a wall it'll put you in front of them, not sure if this is universal but it happens some times.

http://www.wowhead.com/spell=36554/shadowstep#comments   

In comments you can find about it.Even a guy told that he got stepped somewhere else becouse a mage was holding his back on the wall on the start of the comments.

**Comment by Jenovas** [comment]
Fixed in rev 5273
