### ISSUE TITLE
[EN][Spell][Hunter]Traps

### ISSUE THREAD

**Issue by Dranerys** [Atlantiss/BugTracker#8582]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When placing any trap the trap disappears when a mob is touching it and doesn't do anything. You don't see snakes and patches of ice appearing, the trap just disappears. This is the case for ice, freezing, snake and immolation traps. Explosive trap works fine. It also doesn't matter if you're using trap launcher or are manually placing the traps. 

**Current behaviour**: When placing a trap the trap disappears and doesn't do anything.

**Expected behaviour**: When placing a trap the trap should do something. 
Snake trap: Snakes will appear and will attack the mob that stood on the trap.
Ice trap: When triggered a patch of ice will appear and slow the mobs standing on the patch. 
Freezing trap: When triggered the mob is caught in an iceblock. 
Immolation trap: When triggered the trap does fire damage over time.

**Steps to reproduce the problem**:

1. Place a trap near a mob, or use trap launcher to place a trap on a mob.
2. Wait till the mob is on the trap,
3. See that nothing is happening.

**Revision**: 5256

**Comment by lamaATS** [comment]
Fixed in rev. 5257

**Comment by Fabiana-B** [comment]
Aw, nerf hunters

**Comment by lamaATS** [comment]
Report bugs and I will try to fix it.
