### ISSUE TITLE
[EN][Quest][Twilight Highlands] Parting Packages

### ISSUE THREAD

**Issue by hardrack** [Atlantiss/BugTracker#8584]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Impossible to plant bombs in needed locations - q is not woarking

**Current behaviour**: Nothing

**Expected behaviour**: Bomb should be planted

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by RastaTinu** [comment]
But it work good :D

**Comment by hardrack** [comment]
Yesterday it didnty woark, today its ok
