### ISSUE TITLE
[EN][NPC]Nazan and Vazruden in Hellfire Ramparts Dont work.

### ISSUE THREAD

**Issue by bane5** [Atlantiss/BugTracker#8587]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
After doing Hellfire Ramparts for few days, i realised that last 2 days boss didn't drop the chest.
First i couldn't take him down , but then i managed to find spot where i can use my Death Grip on.
After i took him down, he dropped only money and no chest appeared.

**Current behaviour**: What happens
He just flies in the sky in 1 spot, not even moving. And after he dies he doesn't drop chest for loot.

**Expected behaviour**: What should happen instead
He should be flying in the sky, and he should be dropping the chest after he is killed.

**Steps to reproduce the problem**:

1. Fix it
2. Fix it
3. Fix it 🍡 

**Revision**: Current server version

Pictures:    http://imgur.com/a/PeD2E

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links

you can see current server revision by typing ".s in" in chat

**Comment by 2jasemx** [comment]
> Steps to reproduce the problem:
> 
> Fix it
> Fix it
> Fix it 🍡

 Are you serious?
