### ISSUE TITLE
[EN][Spell][Class] Soul Link

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8588]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

- [ ] 1.Hellfire doesn't damage the pet through Soul Link, which was mostly used to break hunter's traps, Dragon's Breaths on warlock's pets in PvP scenario.
http://us.battle.net/wow/en/forum/topic/3123368452

- [ ] 2.Damage done to pet via Soul Link isn't considered in Crowd Control Damage threshold to break any type of CC. For example it was impossible to Dragon's Breath both pet and a warlock since the Soul Link would break Dragon's Breath from it's own damage.
http://us.battle.net/wow/en/forum/topic/3229385418
"Anyone else notice that Dragon's Breath will always, without fail, break on felhunters within the first half a second? No, it's not demonic empowerment. It occurs multiple times per minute."

- [ ] 3. Damage done to a warlock with soul link should heal the warlock through fel armor. If you have a mage using frostbolt on a warlock with soul link on, 20% of the damage should be split with the demon. If Fel armor is active aswell, the warlock should be healed for 3% of the 20% damage split with the demon since the warlock is doing that damage to the demon, not the mage.
http://us.battle.net/wow/en/forum/topic/3123368452

This is not to be mistaken with fel synergy. Fel synergy seems to work like it should.

http://www.wowhead.com/spell=1949/hellfire
http://www.wowhead.com/spell=108415/soul-link
http://wowwiki.wikia.com/wiki/Fel_Synergy
http://www.wowhead.com/spell=44520/fel-armor
http://cata.openwow.com/spell=31661

Metzo told me to repost this with the remaining bugs. Updated it aswell.

**Revision**: 5256

**Comment by Piklo** [comment]
you can see **current** server revision by typing ".s in" in chat

**Comment by kadi2** [comment]
http://www.worldoflogs.com/reports/xd6wilq56ps2vxaq/xe/?x=spell+%3D+%22Fel+Armor%22%0D%0Aor+spell+%3D+%22Soul+Link%22

>>[18:40:43.743] Zorfip takes **10533** damage from Huhuran's Soul Link
[18:40:43.758] Huhuran Fel Armor Huhuran +247 (O: 0)
[18:40:44.182] Huhuran Fel Armor Huhuran +**316** (O: 0)

https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=10533*0.03
10533*0.03=315.99

**Comment by kadi2** [comment]
<<2.Damage done to pet via Soul Link isn't considered in Crowd Control Damage threshold to break any type of CC. For example it was impossible to Dragon's Breath both pet and a warlock since the Soul Link would break Dragon's Breath from it's own damage.
http://us.battle.net/wow/en/forum/topic/3229385418
"Anyone else notice that Dragon's Breath will always, without fail, break on felhunters within the first half a second? No, it's not demonic empowerment. It occurs multiple times per minute."

It just doesn't work with Dragon's Breath

**Comment by Fearyourself** [comment]
It plays a big role in pvp wether it works with Dragon's Breath or not. More than you know.

Also the warlock doesn't get healed by the damage it does through soul link. I had a balance druid moonfire me once with soul link active. The damage were split, but I wasn't being healed for the damage I did to my minion... I'm going to test it again later tonight just for the heck of it.

**Comment by kadi2** [comment]
@Fearyourself My point was that you should report just remaining bugs, not those that doesn't exist anymore.

**Comment by lamaATS** [comment]
`Metzo told me to repost this with the remaining bugs. Updated it aswell.`
Repost mean something has been reported already so where is the reference? (probably this #7209 )

Next You removed major part of template and reported 3 different bugs (yes everything is related to **Soul Link**) in one issue.

Last thing about what You said about last issue that has been closed without fixing all things (check again who closed it)

**Comment by Fearyourself** [comment]
Thanks for being so kind guys. I'll edit it when I get home tonight.

**Comment by Fearyourself** [comment]
I've made two new issues with the remaining bugs: #8593 & #8594

**Comment by Piklo** [comment]
@Fearyourself  it's your post so you can close it :P 
![awsfdgh](https://cloud.githubusercontent.com/assets/16057987/20500491/dd9a6518-b035-11e6-8d62-5cbe9fb382df.PNG)

**Comment by lamaATS** [comment]
@Piklo Thanks!

**Comment by Fearyourself** [comment]
Thanks :P
