### ISSUE TITLE
bugged veins on loch modan

### ISSUE THREAD

**Issue by brawlekk** [Atlantiss/BugTracker#8590]
the server was doing something weird like freezing the game client yesterday but now i can pick low level veins on loch modan with my dwarf miner and it have more than 55 points on mining which is ridiculous since all veins are there but they seem to be broken for me. are there any command lines that can be wrote to solve this problem? or do i need to wait?

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
