### ISSUE TITLE
[EN][World Event][Achievement] [Pilgrim's Paunch]

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#8592]
**Description**: Achievement Pilgrim's Paunch (Horde version) doesnt work... Link: http://www.wowhead.com/achievement=3557/pilgrims-paunch

**Current behaviour**: The achievement requires to get "Spirit of Sharing" buff by eating all different types of food in front of each city. When you get the buff you dont get credit for the achievement for the specific city.

**Expected behaviour**: As soon as you get the "Spirit of Sharing" buff in front of the specific city you should get credit for it.

**Steps to reproduce the problem**:

1. Go in front of any Horde town.
2. Get "Spirit of Sharing" buff by eating 5 different types of food from the tables.
3. Check the achievement status.

**Revision**: Current server revision: 5258

P.S I've heard alliance version works but I cannot confirm it by myself.

**Comment by Piklo** [comment]
#4956

**Comment by Sayris9876** [comment]
Ok sorry about that i searched for it but didnt get any results -_-.......

**Comment by Stephenjawn33** [comment]
Yep, I searched it and it showed the one from last year, IN SPITE all of that I'd still make the report and almost was going to (so thank youu! ^^). It's the last one remaining and that Turkey pet would really help with getting the 150 pets achiev! ^^

**Comment by DuGalle** [comment]
confirmed broken

**Comment by maslak** [comment]
bump

**Comment by Stephenjawn33** [comment]
The Alliance version also does not work, by the way. ^^

**Comment by Sayris9876** [comment]
@Stephenjawn33 Thanks for pointing it out.

**Comment by Dranerys** [comment]
Only achievement not working to do the Pilgrim achievement and get the title and the companion. Would be great if it would work before the event ends :3.

**Comment by Llagas** [comment]
Please fix this before the event end, i've been waiting a year for this.

**Comment by Bildo** [comment]
If im not gonna fix this in time event will be extended

**Comment by Pphhaaaddd** [comment]
Good to know that the time of the event will be extended for this :)

**Comment by Bildo** [comment]
Ok event extended for 3 days, if you want to achieve in Undercity please use chairs in this 'weird' place :P
