### ISSUE TITLE
[EN][Warlock][Spell] Soul Link

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8593]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Damage done to minions via soul link doesn't break Dragon's Breath on the minion. It should be impossible to Dragon's Breath both pet and a warlock since the dragon's breath would break through soul link from it's own damage.

**Current behaviour**: It doesn't break Dragon's Breath from minion

**Expected behaviour**: It should break Dragon's Breath from minion if warlock and minion gets breathed at once.

**Steps to reproduce the problem**:

1. Have a Mage use Dragon's Breath on a warlock and the minion with soul link active
2. 
3. 

Proof: https://youtu.be/p667ZATEkPY?t=9m43s
http://us.battle.net/wow/en/forum/topic/3229385418
"Anyone else notice that Dragon's Breath will always, without fail, break on felhunters within the first half a second? No, it's not demonic empowerment. It occurs multiple times per minute."

Link to Soul Link: http://cata.openwow.com/spell=79957
Link to Dragon's Breath: http://cata.openwow.com/spell=31661

**Revision**: 5258

Thanks Kadi2 for helping out.

**Comment by BialyADI** [comment]
They repair Soul Link But Pets have all time much more HP than Master, come on https://github.com/Atlantiss/BugTracker/issues/7933...

**Comment by lamaATS** [comment]
I was testing it on my local server and I know why it's not working.
Problem is **Dragon's Breath** is always first applied on player and then on pet so it looks like this:
1. Apply **Dragon's Breath** on player
2. **Dragon's Breath** deals damage to player
3. **Soul Link** is triggered
4. **Soul Link** deals damage to pet
5. Apply **Dragon's Breath** on pet
6. **Dragon's Breath** deals damage to pet
....

As you can see Pet doesn't have **Dragon's Breath** when **Soul Link** deals damage.

**Comment by Fearyourself** [comment]
Thanks a lot for taking your time.

It sounds like a great way to solve the problem. But will this fix increase the damage or healing done to the minion or the warlock? If so, I'm guessing it's very low numbers? Do you follow?

**Comment by Fearyourself** [comment]
Wait never mind. Numbers will stay the same. Just a little confusing when thinking about it :-)

**Comment by lamaATS** [comment]
Nothing will chance except **Dragon's Breath** applying order because of current mechanics player is always first one. (It will be applied to all cone effects and in 99.9% spells nothing will be changed)

**Comment by Fearyourself** [comment]
Thanks alot IamaATS <3

**Comment by lamaATS** [comment]
Fixed in rev. 5261

**Comment by Fearyourself** [comment]
@lamaATS do you think it's possible to make it work exactly like on retail? So it wouldn't matter about the distance with the pet?

**Comment by lamaATS** [comment]
Problem is that on retail a lot of things have different delay and what I always say: `everything is possible but need time` so If you think it's still bugged reopen issue.
