### ISSUE TITLE
[EN][Warlock][Spell] Fel Armor

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8594]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  Damage done to a Warlock with Soul Link should heal the warlock through Fel Armor. If you have a Mage using Frostbolt on a Warlock with Soul Link active, 20% of the damage should be split with the demon. If Fel Armor is active aswell, the Warlock should be healed for 3% of the 20% damage split with the demon since the Warlock is doing that damage to the demon, not the Mage.

**Current behaviour**: I'm not getting heals from the damage I do through Soul Link with Fel Armor active.

**Expected behaviour**: I should get healed when damaging my minion through Soul Link with Fel Armor active.

**Steps to reproduce the problem**:

1. Summon pet, have Soul Link and Fel Armor active.
2. Have anyone damage you, say Frostbolt from a Mage.
3. See how you aren't getting heals by the damage you do to the minion.

**Revision**: 5258

I reported this as a bug with Fel Armor since I'm not sure wether it's Soul Link or Fel Armor being bugged. Also it's easier to tell the difference between this and the other Soul Link bug if I named it Fel Armor. Thanks for being so kind.

Proof:

http://us.battle.net/wow/en/forum/topic/3123368452

http://www.worldoflogs.com/reports/xd6wilq56ps2vxaq/xe/?x=spell+%3D+%22Fel+Armor%22%0D%0Aor+spell+%3D+%22Soul+Link%22

[18:40:43.743] Zorfip takes 10533 damage from Huhuran's Soul Link
[18:40:43.758] Huhuran Fel Armor Huhuran +247 (O: 0)
[18:40:44.182] Huhuran Fel Armor Huhuran +316 (O: 0)
10533*0.03=315.99 https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=10533*0.03
Those logs are from firelands patch tho.

http://www.worldoflogs.com/reports/xd6wilq56ps2vxaq/xe/?x=spell+%3D+%22Fel+Armor%22%0D%0Aor+spell+%3D+%22Soul+Link%22

[18:40:51.093] Zorfip takes 12029 damage from Huhuran's Soul Link
[18:40:51.093] Huhuran Fel Armor Huhuran +42 (O: 0)
[18:40:51.468] Huhuran Fel Armor Huhuran +361 (O: 0)
12029*0.03=360.87 https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=12029*0.03%3D
The latest log from Dragon Soul done by Paragon

**Comment by lamaATS** [comment]
Fixed in rev. 5259
