### ISSUE TITLE
[EN][Raids][Firelands-HC] Alysrazor Heroic Meteors

### ISSUE THREAD

**Issue by whatisthisthing** [Atlantiss/BugTracker#8595]
**Description**: Describe the problem
Alysrazor Meteors on Heroic should be slow-able by abilities that are direct (caused to the enemy) and indirect (caused by ground effects).

**Current behaviour**: What happens
In it's current state, the meteors are not affected by slows, both direct and indirect.

**Expected behaviour**: What should happen instead
The meteors should be slow-able.

**Steps to reproduce the problem**:

1.  Form raid group and set to heroic.
2.  Pull Alysrazor and wait for meteor
3.  Try to slow it and watch it continue on it's merry way towards a wall.

**Revision**: Current server version
5258

Video showing meteor slow at multiple points (both direct and indirect)
https://www.youtube.com/watch?v=oA9aq59uvho

Date of the kill: July 22, 2011 - http://www.wowprogress.com/guild/eu/twisting-nether/Quantum/rating.tier12

**Comment by Illusie** [comment]
Can confirm even if already confirmed.
in like month ago we used Arcane mage and one time we used Frost mage, and the Meteor slowed.
now you can't slow it.

Plus, Fieroblast + Brushfire still cast when you behind the meteor.

**Comment by whatisthisthing** [comment]
Yes, that is a separate issue that was confirmed recently. Did not want this bug report to repeat something that's already been reported.
