### ISSUE TITLE
[EN][Talent][Rogue] Honor among thieves 3/3

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8596]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: HaT has longer ICD than 2 seconds

**Current behaviour**: HaT can only proc every 4-5 seconds

**Expected behaviour**: HaT should proc every 2 seconds

**Steps to reproduce the problem**:

1. spec into the talent HaT
2. get 2 crits 2 seconds apart
3. observe how u get no bonus combo pt

**Revision**: 5258

i tested this very thoroughly, it does not have 2 seconds icd

http://cata.openwow.com/spell=51701

**Comment by Genomnomnomnom** [comment]
Bump. Also it seems HaT 1/3 doesn't work at all.

**Comment by Genomnomnomnom** [comment]
Fix it :< Sub does 0 dps now

**Comment by lamaATS** [comment]
Fixed in rev. 5259
