### ISSUE TITLE
[EN][Secrets of the Tower][Westfall] - Secrets of the Tower

### ISSUE THREAD

**Issue by Aftermathzz** [Atlantiss/BugTracker#8597]
**Description**: While taking the quest Secrets of the Tower ( http://www.wowhead.com/quest=26290 ) there is a issue that stops you from completing the quest 

**Current behaviour**: As you enter the tower and you use the provided Potion of Shrouding ( http://www.wowhead.com/item=58112 )  you will see the npc's but they do not start the relevant dialogue in order to complete the quest as one of them is missing -> Helix Gearbreaker ( http://www.wowhead.com/npc=42655 )

**Expected behaviour**: As you use the Potion of Shrouding ( http://www.wowhead.com/item=58112 ) , you should see the 2 ( 3 ) npcs   shrouded figure , the ogre and Helix Gearbreaker ( http://www.wowhead.com/npc=42655 ) climbed on the sholder of the ogre . While shrouded you could assist at their discussion and once they finish your quest will be completed .
At the moment the relevant discussion is missing obviously
"Helix Gearbreaker says: The gnolls have failed, mistress.
Shadowy Figure says: They provided the distraction I required. We continue as planned.
Helix Gearbreaker says: But mistress, the admiral is sti...
Shadowy Figure says: We will free the admiral during the dawning.
Helix Gearbreaker says: Yes, mistress.
Shadowy Figure says: Judgment day is soon upon us, Helix.
Shadowy Figure says: Call for the people. I wish to speak to them one last time before the dawning.
Helix Gearbreaker says: Moonbrook, mistress?
Shadowy Figure says: Aye. Tonight."
Also for  a pertinent idea how is working we can look at this video : ( https://www.youtube.com/watch?v=kso9k8tiWdQ&feature=youtu.be )

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/issues/2338
