### ISSUE TITLE
[EN][World Event][Achievement] [Pilgrim's Peril]

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8599]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: On Alliance side achievment [Pilgrim's Peril](http://www.wowhead.com/achievement=3580/pilgrims-peril) don't work.

**Current behaviour**: The "Undercity" part of acheivment **can not** be obtained. Another 3 parts of achiev  is fine.

**Expected behaviour**: All four parts of achiev can be obtained.

**Steps to reproduce the problem**:

1. Wear either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table
2. Do it in Undercity
3. See that Undercity part of achiev can not be obtain.

**Revision**: ACore rev. 5258 hash. 6d643e991ab5 2016-11-21 00:59:39 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)
![2016-11-22_203557](https://cloud.githubusercontent.com/assets/15231821/20536768/0e846242-b0f3-11e6-8cad-268c47c3f8e6.jpg)

**Comment by Piklo** [comment]
#4957
