### ISSUE TITLE
[EN] [Talent] [Druid] [Minor] Primal Fury

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/BugTracker#860]
Talent works always like on 1/2 talent points even if we have 2/2.

Marked as minor cause respec makes the problem solved.

Links:
- http://wotlk.openwow.com/spell=37117 (talent 2/2 - 1/2 in "see also")
- http://wotlk.openwow.com/spell=16954 (effect 2/2 - same as above)
- http://wotlk.openwow.com/spell=16953 (talent effect - probably this is bugged)

**Comment by Wolffenstein** [comment]
Fixed in rev 4230. You need to respec to fix that.

**Comment by Varchord** [comment]
Finally. All praise lord wolffenstein

**Comment by Kuszki** [comment]
Still bugged (rev. 4280)
