### ISSUE TITLE
[PL][Raids][Firelands-HC]Majordomo

### ISSUE THREAD

**Issue by radarowy** [Atlantiss/BugTracker#8601]
Removed by Jenova

**Comment by BialyADI** [comment]
Is it work with another 10% Dmg debuffs like Demoralizing Shout ;D?

**Comment by radarowy** [comment]
dont know cause i dont have warrior to check it :(

W dniu śr., 23.11.2016 o 14:09 Adam <notifications@github.com> napisał(a):

**Comment by BialyADI** [comment]
I will test it.
But on Boss any Debuffs should work, but no on atlantiss xD.

**Comment by radarowy** [comment]
sadly, now people may bugg this boss today as i wrote a ticket on
bugtracker. I dont think today devs fix this critical bug :p

W dniu śr., 23.11.2016 o 14:35 Adam <notifications@github.com> napisał(a):

**Comment by BialyADI** [comment]
Jenovas?

**Comment by Kejmil** [comment]
no ciekawe czy do wieczora bedzie sfixowane czy nie ( ͡° ͜ʖ ͡°)
