### ISSUE TITLE
[PL][Firelands] Alysrazor - Brak Dmg na Start(nie trzeba sie stackować).

### ISSUE THREAD

**Issue by BialyADI** [Atlantiss/BugTracker#8602]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Alysrazor nie robi Dmg na start po wzniesieniu się w powietrze.

**Current behaviour**: What happens
Alysrazor nie robi Dmg na start po wzniesieniu się w powietrze.

**Expected behaviour**: What should happen instead
Powinna robić Dmg na cały Rajd gdy się wznosi.

**Steps to reproduce the problem**:

1. Iść na Alysrazor.

**Revision**: Current server version

**Comment by Kejmil** [comment]
fix your title

**Comment by Fabiana-B** [comment]
Title would be written on English, instead if it's PL or EN

**Comment by lamaATS** [comment]
Wrong title
