### ISSUE TITLE
mana reganaration become bug

### ISSUE THREAD

**Issue by killermommy** [Atlantiss/BugTracker#8603]
judgements of the pure give holy paladin 30% spirit

it should give paladin mana regen at combat and mana regen out of combat but it's not work at mana out of combat so plz fix this

becouse when i use mana reg CD it become bug and not give me the correct mana

if you need more information w me name (henata)

**Comment by BialyADI** [comment]
xD

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by killermommy** [comment]
so my ticket is?

**Comment by lamaATS** [comment]
From tooltip `your mana regeneration from Spirit while in combat by`.
You can see here **while in combat** so working properly.

Issue template has been completely removed so issue is invalid.
