### ISSUE TITLE
[EN][QUEST][BITTER REACHES] Fade to Black

### ISSUE THREAD

**Issue by Electro1293** [Atlantiss/BugTracker#8605]
I didn't see this quest about problems, so I do not know if was bugged.

**Description:** Can't kill a dragon

**Current behaviour**: The quest cannot be complete because you can't kill the dragon's quest.

**Expected behaviour:** I must kill Katrana then  Malicion comes and catches my character, then Azuregos comes to kill him and the quest will be complete

**Steps to reproduce the problem:**

1. Just go to Bitter Reaches to Kalec
2. Pick up the quest " Fade to Black"
3. Go to kill a orc called "Katrana", the dragon called "Malicion" will attack you and when you kill orc Malicion catches you then Azuregos comes and kill him. 

**Revision:** 5258

How should the quest works: https://www.youtube.com/watch?v=38NkHijK0Kk

Here there is lots information how to make it: http://www.wowhead.com/quest=24467/fade-to-black

Hope you guys can help me :D

**Comment by Khangu** [comment]
It worked for me actually few days ago. Black dragon catched my char and few moments aflater blue one killed it completing quest. Possibly it's another Q that works only once after res.

**Comment by Bildo** [comment]
fixed
