### ISSUE TITLE
[EN][Achievement] Dinner Impossible

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8608]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Dinner Impossible](http://www.wowhead.com/achievement=1785/dinner-impossible) Present a Great Feast in each of the battlegrounds:
- Alterac Valley
- Warsong Gulch
- Eye of the Storm
- Arathi Basin
- Strand of the Ancients

**Current behaviour**: Can not put Great Feast on Strand of the Ancients field, because this battleground  not working. And without this achievment, i can't get this achiev [Hail to the Chef](http://www.wowhead.com/achievement=1563/hail-to-the-chef). With another battlegrounds in achiev [Dinner Impossible](http://www.wowhead.com/achievement=1785/dinner-impossible) all fine.

**Expected behaviour**: putting Great Feast on battleground field, that will count to achiev.

**Steps to reproduce the problem**:

1. Try to get to Strand of the Ancients
2. See, that battleground is disable and i cant do achiev.

**Revision**: ACore rev. 5259 hash. e97a77544a59 2016-11-25 01:07:12 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

![2016-11-25_170258](https://cloud.githubusercontent.com/assets/15231821/20628812/e34dfe72-b330-11e6-9109-0c1ecd9eba06.jpg)

**Comment by pelekon** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by coba999** [comment]
And why this issue was closed?

**Comment by pelekon** [comment]
Due to bad title, after fixin it just open it again

**Comment by Luna-maria** [comment]
I was told to 'wait for the bg to get fixed'  before I could attempt the achievement like a year ago. So far nothing happened :/

**Comment by Sayris9876** [comment]
Battleground not being opened doesnt mean achievement doesnt work... Its kinda useless report sorry. Yes you cannot get it but you also cannot report the achieve for being bugged. Achieve works and I am sure they know that SoTA is closed so no really reason to post anything like that. At least i dont see a reason...

**Comment by Bildo** [comment]
exactly, achievement itself works
