### ISSUE TITLE
[PL][Talent][Druid] Nature's Bounty

### ISSUE THREAD

**Issue by Lamka** [Atlantiss/BugTracker#8612]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Talent nie działa tak jak powinien.

**Current behaviour**: Zamiast skracania czasu rzucania Nourshia o 30 % talent wydłuża go o 30%.

**Expected behaviour**: Talent powinien skórcać czas rzucania zaklęcia o 30%.

**Steps to reproduce the problem**: 

1. Wybrać talent
2. Użyc na 3 postaciach reujventaion
3. Rzucać Nourish

**Revision**: 5259

**Comment by lamaATS** [comment]
Ups. Sorry for that mistake. (it was reworked with Pyromanic because using same logic)

**Comment by lamaATS** [comment]
Fixed on my local server.

**Comment by lamaATS** [comment]
Fixed in rev. 5261
