### ISSUE TITLE
[PL][Talent][Paladin] Protector of the Innocent

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#8613]
**Description**: Protector of the Innocent nie crituje i triggeruje się wtedy kiedy nie powinien.

**Current behaviour**: [Protector of the Innocent](http://cata.openwow.com/spell=20138) ([rank 2](http://cata.openwow.com/spell=20139), [rank 3)](http://cata.openwow.com/spell=20140) nie crituje i triggeruje się z spelli z których nie powinien się triggerować na przykład [holy radiance](http://cata.openwow.com/spell=82327) (albo [ten](http://cata.openwow.com/spell=86452))

**Expected behaviour**: Protector of the Innocent powinien móc critować, a triggerować się tylko z [Holy Light](http://cata.openwow.com/spell=635), [Divine Light](http://cata.openwow.com/spell=82326), [Flash of Light](http://cata.openwow.com/spell=19750), [Holy Shock](http://cata.openwow.com/spell=25914), [Word of Glory](http://cata.openwow.com/spell=85673), [Lay on Hands](http://cata.openwow.com/spell=633) i [Light of Dawn](http://cata.openwow.com/spell=85222) (ale tylko raz, nie ważne ile osób wyleczy zawsze tylko raz triggeruje)

**Steps to reproduce the problem**:

1. wycastuj holy radiance w grupę przyjaznych npc / graczy
2. Protector of the Innocent się triggeruje choć nie powinien
3. wycastuj Light of Dawn w grupę przyjaznych npc / graczy
4. Protector of the Innocent nie triggeruje się w ogóle, choć powinien się ztriggerować raz
5. widzimy że Protector of the Innocent ani razu nie miał crit'a

**Revision**: 5259

**Comment by lamaATS** [comment]
Fixed in rev. 5261
