### ISSUE TITLE
[EN][Spell][Mage] Living Bomb

### ISSUE THREAD

**Issue by unkelrara** [Atlantiss/BugTracker#8614]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When using Fire Blast to spread Living Bomb it removes the Living Bomb from your target. 

**Current behaviour**: Living Bomb is removed when using Fire Blast to spread your dots.

**Expected behaviour**: Living Bomb should remain on your target when using Fire Blast.
Example https://www.youtube.com/watch?v=wGEJBoj9bF8

**Steps to reproduce the problem**:

1. Cast Living Bomb on something. 
2. Use Fire Blast when you have an Impact proc.
3. See that Living Bomb is removed from your target when Fire Blast is used.

**Revision**:  5261

**Comment by BialyADI** [comment]
It is removed when you spread on more than 3 targets.

**Comment by unkelrara** [comment]
3 or more.

**Comment by lamaATS** [comment]
Fixed in rev. 5262
