### ISSUE TITLE
[EN][Quest] Solanian's Belongings

### ISSUE THREAD

**Issue by Knox69** [Atlantiss/BugTracker#8615]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In that quest, the item Scroll of Scourge Magic dont appear before i open it.

**Current behaviour**: Don't give the item

**Expected behaviour**: Normaly it should give the item.

**Steps to reproduce the problem**:

http://www.wowhead.com/quest=8330/solanians-belongings

**Revision**: 5261

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links

you can see current server revision by typing ".s in" in chat

**Comment by xmesaj2** [comment]
![image](https://cloud.githubusercontent.com/assets/550384/26077359/0f5c3076-39bc-11e7-8572-5001e6334617.png)
