### ISSUE TITLE
[EN][Sap][Rouge] sapped mobs can still go into combat

### ISSUE THREAD

**Issue by Avalan666** [Atlantiss/BugTracker#8618]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Mobs that were sapped can still go into combat if you attack anything near them

**Current behaviour**:  See above

**Expected behaviour**:  Mobs should be sapped, ergo unable to go into combat?

**Steps to reproduce the problem**:

1.  Sap a mob
2.  Attack another mob close to it
3.  See how you cant restealth since you are in combat with sapped mob

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links
you can see current server revision by typing ".s in" in chat

**Comment by MichaelArchangelo** [comment]
They even go into combat when you walk near them. Sap is pretty useless in pve right now.

**Comment by Kejmil** [comment]
just to clarify, if you pull something which is "linked" to sapped mob, it will still get combat with you, you can't skip 1 mob every pack in dungeon by using sap
