### ISSUE TITLE
[EN][Raids] Boss armour

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8619]
**Description**: Raid boss armour values are too high

**Current behaviour**: According to Wolfenstein, bosses have 13083 armour on Atlantiss
"Wolffenstein commented on Apr 2, 2015
Dummies and bosses have 13083 armor."

**Expected behaviour**: Boss-level (88) mobs should have 11977 armour.
https://web.archive.org/web/20120207222124/http://elitistjerks.com/f78/t105429-cataclysm_mechanics_testing/
"Confirmed results
1. Boss armor is 11977"

**Steps to reproduce the problem**:

1. Go into a raid
2. Hit a boss
3. Do less physical damage than you should

**Revision**: 5262

**Comment by Piklo** [comment]
#8530

**Comment by lamaATS** [comment]
Fixed in rev. 4400 by @Jenovas (checked current state on server and is correct).
Rev. 4400: `2015-04-14`
`reducing all level 88 bosses armor to 11977`
