### ISSUE TITLE
Totemic Wrath

### ISSUE THREAD

**Issue by kilomud** [Atlantiss/BugTracker#8622]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. Totemic Wrath(Elemental Shaman) does not increase spell power by 10%. 
2. Instead of provides only 200 spell power flat,doesnt matter how much spell power do you have.
3. It should increase spell power based on your current spell power.

**Revision**: Current server version

**Comment by Vayns** [comment]
Tested this myself just now and my spellpowerp went from 9408 to 10348, thus giving 10% spellpower.  Have you tried respeccing?

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links, title

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
you can see current server revision by typing ".s in" in chat

**Comment by Jenovas** [comment]
Did tests and seems to work fine. It might be only a visual bug and entering / exiting char tab might fix it or its only a bug for you, please try respecing if that doesnt help write a ticket for a GM to .unaura all you and relog.
