### ISSUE TITLE
[EN][Talent][Warrior] Blitz

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#8624]
**Description**: http://cata.openwow.com/spell=80977 warrior talent doesn't work properly

**Current behaviour**: Stun works properly,but doesn't give any rage

**Expected behaviour**: Rage should be generated properly

**Steps to reproduce the problem**:

1. Put at least 1 talent on Blitz;
2. Use charge on a target;
3. You will gain rage only from charge

**Revision**: 5263

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links

**Comment by Jenovas** [comment]
Fixed in rev 5273
