### ISSUE TITLE
[PL][Talent][Paladin] Conviction

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#8626]
**Description**:  [Conviction](http://cata.openwow.com/spell=20049) ([rank 2](http://cata.openwow.com/spell=20056), [rank 3](http://cata.openwow.com/spell=20057)) triggeruje się wtedy kiedy nie powinno

**Current behaviour**:  Conviction triggeruję się prawdopodobnie ze wszystkich critów (w tym na 100% z [hoty z holy radiance](http://cata.openwow.com/spell=86452), nie jestem pewny czy hota z world of glory z glyphem też triggeruje ten talent)

**Expected behaviour**:  Conviction powinno triggerować się z wszystkich critów poza critami z healing over time (hota z holy radiance i hota z world of glory z glyphem, w przypadku obu tych spelli tylko początkowy heal powinien móc triggerować talent)

**Steps to reproduce the problem**:

1. Wycastuj Holy radiance w grupę graczy / przyjaznych npc
2. Widzimy że hota triggeruje talent choć nie powinna

**Revision**: rev. 5263

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14067-8626-conviction/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
