### ISSUE TITLE
[EN][NPC] Zorus the Judicator

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8628]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  [Zorus the Judicator](http://www.wowhead.com/npc=21774/zorus-the-judicator) does not give an item.

**Current behaviour**: You cannot re-obtain item [Spectrecles](http://www.wowhead.com/item=30719), after you complete [Harbingers of Shadowmoon](http://www.wowhead.com/quest=10643/harbingers-of-shadowmoon) quest.

**Expected behaviour**: When handling to Zorus, you should see a line to re-obtain item [Spectrecles](http://www.wowhead.com/item=30719).

**Steps to reproduce the problem**:

1. Complete the quest [Harbingers of Shadowmoon](http://www.wowhead.com/quest=10643/harbingers-of-shadowmoon)
2. Delete from inventory [Spectrecles](http://www.wowhead.com/item=30719)
3. Try to re-obtain [Spectrecles](http://www.wowhead.com/item=30719), by speaking with [Zorus the Judicator](http://www.wowhead.com/npc=21774/zorus-the-judicator) and you will see that it is impossible. And you need it to do next quests, whithout them it stuck.

**Revision**: ACore rev. 5263 hash. cccc6270bf54 2016-11-28 12:03:48 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)
![2016-11-30_130312](https://cloud.githubusercontent.com/assets/15231821/20749933/15ecd4a0-b6fd-11e6-9df6-9bcbfe2534e0.jpg)

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12538-8628npc-zorus-the-judicator/#entry59969
