### ISSUE TITLE
[EN][Paladin][Holy] Judgement

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8629]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

http://cata.openwow.com/spell=53657
Judgement / Judgements of the Pure

**Description**: When you Judgement target it should grant you Judgement of the Pure.
Mana regeneration increased by additonal 30% & 9% haste.

**Current behaviour**: When Judgement Parry you don't get the buff.

**Expected behaviour**: **I am not *sure*** but I think when the judgement parried you still need to get the buff.

**Steps to reproduce the problem**:

1. Judgement on some boss/target that can parry. (I did on Majordomo)
2. get Parried on Judgement
3.  See what happen

**Revision**: Current server version

*I think I had same problem with Crusader Strike when parried did not recieved Holy Power.
same here I don't know Paladin mechanic and if you should get Holy Power when parried/dodge.
And I'm not sure if you need get Judgements of the pure if parried to.
I just know I didn't got the buff on Majordomo cause attack been parried.
If it should work like that. then close this issue.

** Editing:
Jugement of the Pure buff did not refreshed when Judgement miss too.

**Comment by Piklo** [comment]
change title to
[PL][Talent][Paladin] Judgements of the Pure


you can see current server revision by typing ".s in" in chat

**Comment by Illusie** [comment]
its not PL its EN.
and i dont know to use ".s" commands.

**Comment by Piklo** [comment]
so change to [EN] omg -_-

**Comment by Jenovas** [comment]
http://www.mmo-champion.com/threads/1039762-Judgements-of-the-Pure
from this topic players claim that the Judgement must deal DMG, if the creature is immune, if there is a miss or even if the judgement is the killing blow players often see that the buff doesnt refresh / doesnt get applied.

Please find proof that it should react the way you claim. Till the I am closing this issue.

**Comment by Illusie** [comment]
@Piklo it has [EN] open your eyes.
@Jenovas I don't know how the mechanic should work that why I opened the issue.
I know that on previous times I missed or dodged the Judgement it still refreshed.

It would be nice if you will keep it open on the BugTracker list (not the #Closed list)
so might someone that know will see it and answer us.

**Comment by Piklo** [comment]
@Illusie read slowly my last 2 messages
"change title to
[PL][Talent][Paladin] Judgements of the Pure"
ok my bad, i wrote [PL], so you should change title to
"**[EN]**[Talent][Paladin] Judgements of the Pure" because there is problem with talent "Judgements of the Pure" not with judgement -_-
