### ISSUE TITLE
[PL][Npc] Beauty

### ISSUE THREAD

**Issue by Piklo** [Atlantiss/BugTracker#8631]
**Description**: [Beauty](http://www.wowhead.com/npc=39700/beauty) ma za mały hitbox

**Current behaviour**: Żeby móc używać melee skilli trzeba stać w bossie

**Expected behaviour**: Boss powinien mieć większy hitbox

**Steps to reproduce the problem**:

1. Spróbuj użyć skilla który wymaga melee range na bossie
2. Widzimy że żeby go użyć trzeba stać w bossie

**Revision**: rev. 5263

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/13378-8631-8834-beauty-and-ozruk-hitbox/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
