### ISSUE TITLE
Heroic Apparatus

### ISSUE THREAD

**Issue by icetax** [Atlantiss/BugTracker#8632]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
I just got Heroic Apparatus on my paladin and i tried it out on dummies. I use both the Vessel and Apparatus as my trinkets which both gets stacks when your melee hit crits, but for some reason my vessel gets more stacks than the apparatus.

**Steps to reproduce the problem**:
1. Equip both Vessel and Apparatus
2. DPS and wait for criticals
3. Check both Vessel and Apparatus stacks

![wowscrnshot_113016_223937](https://cloud.githubusercontent.com/assets/24257691/20771835/ca82cb80-b753-11e6-9fff-6d7051d40199.jpg)

As u can see from the picture, my Vessel has 5 stacks while Apparatus has 4.

**Comment by ysiu15** [comment]
BC Vessel stack from all Crits . Aparatus only from mele crit.

**Comment by Aldergar** [comment]
#7719 duplicate

**Comment by Psychobird7** [comment]
To clarify, VoA is NOT supposed to proc from all crits. And neither is AoK. 

AoK and VoA are both meant to proc from melee crits. Which for paladins means: CS, DS, TV, J, HoW, AA. 
And **maybe** Seals, though I don't have a source on that at hand. Pretty sure it shouldn't proc from Seals. 

Right now, VoA procs too often and AoK seems to proc too little.

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
https://github.com/Atlantiss/BugTracker
