### ISSUE TITLE
[EN] [RAID] [FL] Majordomo concentration & pets

### ISSUE THREAD

**Issue by Amerigowarlock** [Atlantiss/BugTracker#8635]
I am reposting this because even though the last topic about this is 3 months old, the issue has yet to be confirmed by the staff, regardless of the amount of evidence we gave. Hoping this has not been forgotten.

Current behavior : Concentration buffs do not apply to both players & pets.

Expected behavior : it should.

https://www.youtube.com/watch?v=l-owGgl-jcc

Here's a video of the fight from demolock pov.
You can see the pets buffs above the player's unit frame.

As you can see, the concentration buff is applied to the pet everytime the player gets it, may it be 25, 50, 75 or 100 concentration buff. It also fades from the pet as soon as the player loses it.

Guardian pets such as Doomguards do not get the buff however.

**Comment by Piklo** [comment]
#8179
