### ISSUE TITLE
[EN][Item] Variable Pulse Lightning Capacitor

### ISSUE THREAD

**Issue by therealpadthai** [Atlantiss/BugTracker#8636]
**Description**:

This report has been created because of discussion regarding #8623.

The normal version of VPLC is buffed incorrectly with a 300% value as per (http://atlantiss.eu/changelog/25#rev4764), but it should in fact be buffed by a _260%_ value, as per the OFFICIAL blizzard patch notes (https://worldofwarcraft.com/en-us/news/3019413). You can find the line in September 9th under the subheading, Items: "The Variable Pulse Lightning Capacitor now does an average of 2.6x more damage than before, but is less likely to reach a large stack of charges." Also, under wowhead. Disregard the 300% comment, as that was refuted and proven to be false by the comment below (http://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor#comments:id=1511324:reply=263159).

**Current behaviour**: The lightning bolt of normal version of VPLC is buffed incorrectly by _300%_.

**Expected behaviour**: The lightning bolt of normal version of VPLC should be buffed by _260%_.

**Steps to reproduce the problem**:

1. Equip normal VPLC.
2. Fire at training dummy.
3. Watch the trinket damage do 3300, when it should be doing approximately 2860.

**Revision**: 5263

**Comment by BialyADI** [comment]
It proc on No Crit Dmg too. It should from only Crit Direct Dmg or DoT.

**Comment by Jenovas** [comment]
Should be fixed in rev 5270
