### ISSUE TITLE
[EN][Spell][Rogue] Wound Poison

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8637]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: wound poison lasts too long in pvp

**Current behaviour**: wound poison lasts 15 seconds in pvp

**Expected behaviour**: wound poison should only last 10 seconds in pvp

**Steps to reproduce the problem**:

1. apply wound poison
2. attack a player in pvp
3. 

**Revision**: 5263

http://cata.openwow.com/item=10918
http://cata.openwow.com/spell=13219

proof:
https://www.youtube.com/watch?v=LlivtllvLb0 (0:02)

**Comment by kadi2** [comment]
Didn't test hunter's Widow Wenom, but it's supposed to be 10 seconds aswell.
https://youtu.be/3z_XozRwEGA?t=1m26s
Spell ID: 82654

**Comment by fluessig** [comment]
no hunter venom seems to be the correct 10 seconds in pvp

**Comment by lamaATS** [comment]
Fixed in rev. 5269
