### ISSUE TITLE
Items having wrong color

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8640]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

when i first encountered this problem i believed that this issue existed on retail until the beginning of mop and thus wouldnt be fixable
example:
season3 warlock head is red instead of the correct blue-ish version
but recently i found this
https://www.youtube.com/watch?v=p667ZATEkPY (7:36)
its a female human warlock with a blue season3 head
hansol says he recorded all his footage in January

http://www.wowhead.com/item=33683/vengeful-gladiators-felweave-cowl#comments
"I just bought this last night on my warlock. I'm wondering why the helm has the same color as theHood of the Malefic, when in this SS, and every other SS I've seen, it's the blue version."
this comment is from 6th December

on atlantiss female humans have a red season 3 head

is there any way to fix this?

**Comment by Fearyourself** [comment]
I think I recall reporting this a year and a half ago or something like that. It's not supposed to have the orange wings/helm design, but it does on most private servers...

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
