### ISSUE TITLE
[EN][Alchemy] Recipe: Greater Nature Protection Potion

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#8643]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The recipe for [Greater Nature Protection Potion](http://www.wowhead.com/item=13496/) is currently not sold by [Calandrath](http://www.wowhead.com/npc=15174).

**Current behaviour**: Calandrath never sells the recipe for Greater Nature Protection Potion.

**Expected behaviour**: Calandrath should sell the recipe on limited supply, but with a short respawn timer. (Less then 5min according to one [comment](http://www.wowhead.com/item=13496/recipe-greater-nature-protection-potion#comments:id=1592756:reply=505918) on wowhead).

**Steps to reproduce the problem**:

1. Go to Calandrath in Silithus.
2. Look in her inventory.
3. Note that the recipe is not there and does not appear after any given time either.

**Revision**: 5265

**Comment by Navedonar** [comment]
Fix http://community.atlantiss.eu/index.php?/topic/12502-8643alchemy-recipe-greater-nature-protection-potion/
