### ISSUE TITLE
[EN][Quest] 'Borrowing' From the Winterfall

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8646]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: quest ['Borrowing' From the Winterfall](http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall) doesn't working.

**Current behaviour**: Using the [Smoked Meat](http://www.wowhead.com/item=68645) does not count quest progress.

**Expected behaviour**: Using the [Smoked Meat](http://www.wowhead.com/item=68645) shall count at  quest progress.

**Steps to reproduce the problem**:

1. Take quest ['Borrowing' From the Winterfall](http://www.wowhead.com/quest=29037/borrowing-from-the-winterfall)
2. Loot [Smoked Meat](http://www.wowhead.com/item=68645)
3. Use it.

**Revision**: ACore rev. 5265 hash. 9f4981c23a47 2016-11-28 21:11:06 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Alinna99** [comment]
Please fix this!
