### ISSUE TITLE
[EN][Profession][Engineering] Spinal Healing Injector

### ISSUE THREAD

**Issue by ntrns** [Atlantiss/BugTracker#8647]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
Wowhead link.
http://www.wowhead.com/spell=82200/spinal-healing-injector

This engineering tinker should inject a Mythical Healing Potion with a better result healing up to 30k HP. It doesn't require a potion in your inventory or elsewhere.

It doesn't work as intented. You can use it once and then you have to relog in order to use it again. The message below the potion or the gloves you've tinkered says "Cooldown Starts Upon Leaving Combat" and no matter if you enter and leave combat multiple times the cooldown won't start and u've to relog.

http://imgur.com/UdyrV6T - screenshot of the message it leaves on the gloves and any potion sharing gcd with Mythical Healing Potion taken on Atlantiss.

**Comment by ShockRW** [comment]
BUMP

**Comment by Piklo** [comment]
#1352  #5980
