### ISSUE TITLE
I can't buy conquest weapons after the 7800 season restriction

### ISSUE THREAD

**Issue by l337g0g0** [Atlantiss/BugTracker#8648]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

I don't know how to do this, but i made a video of it for you.
I can't buy my conquest weapon after reaching 7800 conquest points for the season.
I recorded it for you...

(EDIT): I re logged and restarted the game.

https://www.youtube.com/watch?v=Ug2kRl1FDBE

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by TranceAccount** [comment]
I believe there was a workaround for this:
1. You buy another item which you can afford from the CP vendor.
2. You sell this item back and get your CP back.
3. Buy the weapon.

**Comment by l337g0g0** [comment]
I played a few BG's and got some more Conquest points and then was able to buy it.

It's fixed for me but i guess i need to leave this hear so they can fix it.

Thank you for your tip...
