### ISSUE TITLE
[EN][NPC][Deepholm] Therazane fraction

### ISSUE THREAD

**Issue by Vonzu** [Atlantiss/BugTracker#8649]
**Description**: I attacked by mistake Berracite in Deepholm (the little earth elemental near Kor the Immovable) and now i can't take quests from Kor and i can attack all fraction members of Therazane. In rep tab i have "friendly" but on red background

**Current behaviour**: I can attack all members of Therazane fraction and i can't take quests from them.

**Expected behaviour**: Kor should give me quests. I have quest mark on his head but i can only attack him.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
reputation tab > therazane > uncheck "at war"

**Comment by Vonzu** [comment]
Thank you very much 👍
