### ISSUE TITLE
[PL][Quest]Mr. P's Wild Ride

### ISSUE THREAD

**Issue by Suda1221** [Atlantiss/BugTracker#8651]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Machina nie działa (Mr. P)

**Current behaviour**: Po odebraniu questa powinniśmy od razu automatycznie wejść do maszyny (Mr. P) i nią sterować. Następnie powinniśmy zniszczyć wrogie jednostki, niestety nic się nie dzieje. Robot bojowy którego naprawiliśmy w poprzednim queście nie działa w ciągu dalszym i nie można do niego wejść. Quest w Stonetalon Mountains

**Expected behaviour**:  Po rozpoczęciu questa powinniśmy od razu móc sterować robotem bojowym

**Steps to reproduce the problem**:

1.  Rozpoczęcie questa
2.  Brak jakichkolwiek reakcji, robot leży na ziemi i nie można do niego wejść
3. 

**Revision**: 05-12-2016

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

you can see current server revision by typing ".s in" in chat

**Comment by Myivo** [comment]
Proszę o ponownie napisanie zgłoszenia zgodnie z regulaminem bugtrackera czyli: link do wowheada + revision servera.
