### ISSUE TITLE
(Burn in Effigy)

### ISSUE THREAD

**Issue by Belvaac** [Atlantiss/BugTracker#8652]
When I want to use the torch colmillarr does not leave me I get that I have to be near a ship and being close to one does not let me still use it 
The mission is called Burn in Effigy

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links
title

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
you can see current server revision by typing ".s in" in chat

**Comment by Fabiana-B** [comment]
Change title!
