### ISSUE TITLE
[EN][Raid][Chest Loot] Shadowfrost Shards / Fragment of Val'Anyr

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#8653]
**Description**: I completed Shadowmourne quest chain a while ago and currently I am working on Val'anyr fragments collecting and I've noticed that doesn't matter how many times you kill the bosses shard or fragment never drops from chest loot. That really slows things down especially in Ulduar considering most drops are from chests not boss corpses.

**Current behaviour**: Shadowfrost Shards and Fragments of Val'Anyr never drop from bosses that the loot is located in chests. (Example: Deathrbinger Saurfang, Valithria Dreamwalker from ICC, Freya, Hodir from Ulduar and so on.)

**Expected behaviour**: Shards and Fragments should drop from boss corpses and boss chests.
http://www.wowhead.com/item=50274/shadowfrost-shard#dropped-by
http://www.wowhead.com/item=45038/fragment-of-valanyr
"Dropped by" section shows bosses that you can loot corpses; "Contained in" shows the chests for bosses that you can take loot only from chests not from corpses.
**Steps to reproduce the problem**:

1. Go to any boss in Ulduar / ICC where the loot is from chest
2. Kill it repeatedly on 25man mode
3. See the lack of shards / fragments.

**Revision**: 5265

P.S. I didnt include that some chests are bugged and they dont give loot at all but that is there too (Thorim for example). Also if the title is not correct let me know to what should I change it. I might be wrong about the whole report but I am 100% sure that I never saw a shard or a fragment from chest and considering I already have Shadwomourne and I am 3 or 4 weeks into farming fragments to never see a shard or fragment from chest I have to be super unlucky.

**Comment by Fabiana-B** [comment]
Valithria have a chest? She never dropped it before :/

**Comment by Sayris9876** [comment]
Chest from dreamer spawns behind the right door. You need someone to stay there before the encounter ends because the doors as you know get closed. Anyway thats not even the point of the report...

**Comment by Fabiana-B** [comment]
@Sayris9876 but thanks for the info :3

**Comment by Sayris9876** [comment]
@Fabiana-B You are welcome...Go get them dreamer items!

**Comment by xmesaj2** [comment]
Fix in rev 5541
