### ISSUE TITLE
[EN][NPC] Lieutenant Tristia Elite Set Warrior Class

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#8656]
http://www.wowhead.com/npc=54660/lieutenant-tristia
https://i.imgsafe.org/8956c8417f.jpg
**Description**: Describe the problem
The Npc is bugged elite gear for warrior atm isnt buyable the main set pieces.

**Current behaviour**: What happens
When you get 2200 raiting in 3s or 5s or rated bg and you want to change your set from normal into elite you cant becouse it says requires mail shaman items instead of warrior ones.This bug occurs when trying to buy the gear as warrior class.
**Expected behaviour**: What should happen instead
When you reach the raiting required for elite you should be able to change the set from normal to elite for warrior with 0 cost (ONLY SET AND BOOTS).

**Steps to reproduce the problem**:

1. Make a Warrior put 2200 raiting personal and team in 3v3 5v5 or rated bg and have full set ruthless
2. Go to the seller npc Lieutenant Tristia try to change your current ruthless set from normal to elite
3. You will notice that it says you need to have shaman set in order to buy the elite.

**Revision**: Current server version
5265

**Comment by Piklo** [comment]
@Zhalox123 Could you give links to items?

**Comment by Piklo** [comment]
i think its not a problem anymore, because with 4.3 we had to add new items
