### ISSUE TITLE
[EN][Quest][Ruins Of Guilneas]The F.C.D.

### ISSUE THREAD

**Issue by ixvenomxi** [Atlantiss/BugTracker#8661]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
the quest cant be complete because The forsaken comunication device dont give the item for the quest.

**Current behaviour**: What happens
Forsaken Comunication Device cast but dont give the item.

**Expected behaviour**: What should happen instead
Forsaken Comunication Device will cast and give me the item that have the same name Fosaken Comunication Device

**Steps to reproduce the problem**:

1. Going to the item
2. Click in the item for getting the item quest
3. getting the quest item

**Revision**: Current server version

**Comment by pelekon** [comment]
It is working, I did it a few days ago

**Comment by DarkestDuck** [comment]
It does not work
