### ISSUE TITLE
/]: # ([EN][Web] pvp doesnt work)

### ISSUE THREAD

**Issue by moeh2415312** [Atlantiss/BugTracker#8662]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: when i try to do enter pvp battlegrounds it waits a long time, it works for other people but i had to wait 3 hours and nothing happens

**Current behaviour**: pressing the battlegrounds won't let me enter it i pressed arathi basins and it waits for ever

**Expected behaviour**: When i queue for battlegrounds  i should enter 4-5 min, the queue is somehow stuck

**Comment by Jenovas** [comment]
So this is an ingame problem?
You try to join BG but it never invites you?

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by moeh2415312** [comment]
yes this is a ingame problem and it has  been ocurring over a year now and when i try to join random bg iit never invites me
