### ISSUE TITLE
[EN][Warlock] Doomguard

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8663]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: My doomguard died on Ragnaros somehow
http://imgur.com/a/XsqoX

http://cata.openwow.com/spell=18540

**Current behaviour**: Summoned Doomguard and he died.
Isn't doomguard is like every pet on pve. and he have avoidance do damage.
I don't think my doomguard got hitted by Meteor or Wave (Isn't meteor & wave should just bypass through him like they do on Felhunter/Felguard? He should not take any damage at all right?)

**Expected behaviour**:  Doomguard will stay alive like every pet?

**Steps to reproduce the problem**:

1.  fight rag 
2. summon doomguard at Phase3 (Meteors)
3.  see what happen

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

you can see current server revision by typing ".s in" in chat

**Comment by Illusie** [comment]
@Piklo oh yeah forgot cata.open link.
don't know to use revision commands.

**Comment by TranceAccount** [comment]
> Revision: ?
1. Go to http://atlantiss.eu/changelog
2. Look for the latest active revision. (Not the one with "Waiting for update")
3. Substitute ? with the number of that revision.

**Comment by Mordorianin** [comment]
Illusie Doomguards, same as Elementals on our server are just diyng from the flames on Rag norm/hc. Just tell ur healer to keep him alive.

**Comment by Illusie** [comment]
Hey Mordor.
I don't think they capable to heal my pets when the fight is too intense ;P
I assume that Doomguard and Elemental suppost to get Avoidance buff. That that my report is for ;)

**Comment by Jenovas** [comment]
Closing issue. All pets have avoidance. Some single spells are bugs. Please create a new issue specifying what spell / spells are bugged on Ragnaros. From this issue all I know is your pet died, dont know why, dont know to what, dont know if Ragnaros attacked him, got hit by meteor, I dont know anything.

**Comment by Illusie** [comment]
@Jenovas died again, I think it the Engulfing Flame, I can't really watch what the cause of it.
But actually its not a Meteor, the Meteor just went through the Doomguard.
Also I don't think he got waved.

So I would say Engulfing Flame.
