### ISSUE TITLE
[EN][Battle of mount Hyjal] cant recover corpse inside

### ISSUE THREAD

**Issue by kartonick** [Atlantiss/BugTracker#8667]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
while soloing mount hyjal as a DK upon entering raid instance after death im still present as ghost. 

**Current behaviour**: What happens
entering mount hyjal as ghost doesnt rrecover characters body. Also there is no spirit healer outside the instance (graveyard at 61.1 , 57,9 Kalimdor)

**Expected behaviour**: What should happen instead
chracter should be revived upon entering raid instance. spirit healer should be present at any graveyard.
**Steps to reproduce the problem**:

1. create a dk capable of entering battle of mount hyjal
2. die inside the raid
3. release spirit and try to recover corpse from instance.

**Revision**: 5267

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by pelekon** [comment]
fixed in rev 5906
