### ISSUE TITLE
[en][item][spell][mage] Dragonwrath legendary staff and frostfirebolt

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8669]
https://us.battle.net/forums/en/wow/topic/2973251647
http://www.wowhead.com/spell=69984/frostfire-bolt
http://www.wowhead.com/spell=101085/wrath-of-tarecgosa
http://www.wowhead.com/spell=101056/wrath-of-tarecgosa

**Description**:  frostfirebolt is considered dot by staff and procs wrath of terecgosa when it should be considered a normal direct damage spell thus should procing spell duplication. Due to this frostfire bolt dtr procs don't trigger additional fingers of frost etc but also – doesn't consume brain freeze etc

**Current behaviour**: frostfirebolt spell is not copied, the damage is as wrath of terecgosa, its pinned to wrong spell id (  101085 ) should be pinned to ( 101056 )

**Expected behaviour**:  frostfirebolt should be capable of being doubled, with animation of second frostfirebolt 

**Steps to reproduce the problem**:

1. equip legendary staff
2. cast frostfire bolt
3. observe recount and screen

**Revision**: 5267

**Comment by lamaATS** [comment]
Fixed in rev. 5269
