### ISSUE TITLE
[en][item][spell][mage] Dragonwrath legendary staff and pyroblast

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8670]
https://us.battle.net/forums/en/wow/topic/2973251647
http://www.wowhead.com/spell=11366/pyroblast
http://www.wowhead.com/spell=101085/wrath-of-tarecgosa
http://www.wowhead.com/spell=101056/wrath-of-tarecgosa

**Description**:  pyroblast and pyroblast! is considered dot by staff and procs wrath of terecgosa when it should be considered a normal direct damage spell thus should procing spell duplication. Due to this pyroblasts dtr procs don't trigger additional effects ( critical mass / ignite )etc but also – doesn't consume pyroblast! Procs when you got one when pyro was already in air etc

**Current behaviour**: pyroblast spell is not copied, the damage is as wrath of terecgosa, its pinned to wrong spell id (  101085 ) should be pinned to ( 101056 )

**Expected behaviour**:  pyroblast should be capable of being doubled, with animation of second pyroblast, also capable of critting ( hitting ) independend of main spell from which it proc'd

**Steps to reproduce the problem**:

1. equip legendary staff
2. cast pyroblast ( pyroblast!)
3. observe recount and screen

**Revision**: 5267

**Comment by lamaATS** [comment]
Fixed in rev. 5269
