### ISSUE TITLE
[en][item][spell][mage] Dragonwrath legendary staff and flamestrike

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8671]
https://us.battle.net/forums/en/wow/topic/2973251647
http://www.wowhead.com/spell=2120/flamestrike
http://www.wowhead.com/spell=101085/wrath-of-tarecgosa
http://www.wowhead.com/spell=101056/wrath-of-tarecgosa

**Description**:  flamestrike dot procs new flamestrikes when it should proc flamestrike dot damage on targets.  Due to this the more targets are in range you can pretty much outaoe everything ( should duplicate dot damage on tick not whole spell )

**Current behaviour**: flamestrike dot is pinned to wrong spell id (101056 ), should be pinned to (  101085 ) 

http://imgur.com/a/7n28E

**Expected behaviour**:  flamestrike can only get duplicated on initial spell hit not every dot tick, flame strike dot can be duplicated on every tick

**Steps to reproduce the problem**:

1. equip legendary staff
2. gather few targets
3. cast flamestrike, wait for dot damage to proc new direct damage flamestrikes

**Revision**: 5267

**Comment by Illusie** [comment]
Nice reports Blink.
I think Tarecgosa is most broken with Shadow Priest or maybe Shadow Priest with Tarecgosa just sucks don't know ^^..

Btw what is that addon you have near your chat?

**Comment by blinkmaster** [comment]
its called CUBAN, mod made to track DTR procs

**Comment by sunshitwowsucks** [comment]
also suck on sham xd

**Comment by lamaATS** [comment]
Fixed in rev. 5269
