### ISSUE TITLE
[en][item][spell][mage] Dragonwrath legendary staff and frostbolt

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8672]
https://us.battle.net/forums/en/wow/topic/2973251647
http://www.wowhead.com/spell=116/frostbolt
http://www.wowhead.com/spell=101085/wrath-of-tarecgosa
http://www.wowhead.com/spell=101056/wrath-of-tarecgosa

**Description**:  frostbolt procs wrath of terecgosa (arcane damage) ( 101085 ) when it should be proccing (101056)

**Current behaviour**: frostbolt is pinned to wrong spell id (101085 ), should be pinned to (  101056 ) 

**Expected behaviour**:  frostbolt legendary staff duplication should be additional frostbolt, not wrath of terecgosa arcane damage

**Steps to reproduce the problem**:

1. equip legendary staff
2. cast frostbolts on target
3. observe recount and screen

**Revision**: 5267

**Comment by lamaATS** [comment]
Fixed in rev. 5269
