### ISSUE TITLE
[PL][Gameobject][Cata - Raid] Ragnaros Meteors HC

### ISSUE THREAD

**Issue by SupaMasta** [Atlantiss/BugTracker#8674]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Meteory które pojawiają się na fazie 3 można Fearować i dawać Blinda. 

**Current behaviour**: Castujac feara lub blinda unieruchamiamy meteora na czas trwania tego CC. 

**Expected behaviour**: Meteor powinien być immune na wszystkie spelle typu stun i CC.

**Steps to reproduce the problem**:

1. Przeżyj do 3 fazy na Ragnarosie HC. 
2. Po pojawieniu się meteora rzuć na niego blind lub fear.
3. Meteor stoi i nic nie robi.

**Revision**: 5267

**Comment by SupaMasta** [comment]
Nikt się nie wypowiedział czyli to nie bug. Mam nadzieje ze banow za to nie ma :)

**Comment by Piklo** [comment]
to że nikt się nie wypowiedział nie znaczy od razu że to nie jest bug. Jenova który głównie zajmował się Firelandsami teraz pracuje nad nie działającymi BG, więc może teraz nie mieć czasu. 

Skoro napisałeś posta w którym mówisz że da się fearować itd. a nie powinno się móc dać (przynajmniej według tego co mówisz), znaczy to że to jest bug. 

Co do banów, jeżeli dobrze rozumiem [rules](http://atlantiss.eu/pages/3) które u nas panują, to chyba można za to dostać bana.
