### ISSUE TITLE
[EN][Item][Druid] Dragonwrath, Tarecgosa's Rest and Moonfire/Sunfire

### ISSUE THREAD

**Issue by therealpadthai** [Atlantiss/BugTracker#8679]
**Description**: Moonfire/Sunfre has a direct damage portion when you cast it and then it leaves a dot on the target. If I remember correctly, the direct damage portion of the Moonfire/Sunfire spell should be duplicated just like a wrath/starfire is. It should not show up as "Wrath of Tarecgosa hits ...", as only DOTs should show up duplicated as that.

As you can see in the screenshot posted below, the staff is duplicating the direct damage portion of Moonfire/Sunfire as a DOT duplication. Why does this matter if everything seems fine damage wise?

If the direct damage portion of Moonfire/Sunfire is duplicated as a "Wrath of Tarecgosa" DOT duplication, then the Moonfire DOT is not refreshed as seen in: https://eu.battle.net/forums/en/wow/topic/2504844873#post-1.

Now, I tested this with Lunar Shower talented as well. _Lunar Shower increases the direct damage done by Moonfire by 45% and reduces the mana cost by 30%. This effect stacks up to 3 times and last 3 sec. While under the effect of Lunar Shower, Moonfire generates 8 Solar Energy and Sunfire generates 8 Lunar Energy._

I was under the mistaken impression that given this talent, the duplication of the direct damage of Moonfire/Sunfire should ALSO be giving a duplicate 8 energy and another stack of Lunar Shower. However, as proven in this post (https://eu.battle.net/forums/en/wow/topic/2504844873#post-1), I am wrong. I'm not even sure why it doesn't give a duplicate 8 energy but if it doesn't work on Blizz realms, I doubt it should here. I am pointing this out just to make sure that while fixing the direct damage duplication of Moonfire/Sunfire, this also doesn't bug out.

That being said, the direct damage portion is definitely not being copied as a direct damage spell but as a DOT spell and thus is bugged in that way.

The DOT damage is clearly identifiable as the lower value in the screenshot whereas the initial damage portion is the higher damage value and also the phrasing of both reflects the same in the combat log.

http://i.imgur.com/hpYQG7V.jpg

**Current behaviour**: The direct damage portion of Moonfire/Sunfire is not being copied as a direct damage spell but as a DOT spell.

**Expected behaviour**: The direct damage portion of Moonfire/Sunfire should be copied as a direct damage spell and not as a DOT spell, thus refreshing any current Moonfire/Sunfire dot already on the target.

**Steps to reproduce the problem**:

1. Get Lunar Shower spec.
2. Spam Moonfire until it gives you a higher value than the dot to differentiate duplications.
3. Watch your combat log for the DOT duplication to occur on a direct damage hit of Moonfire/Sunfire. 

**Revision**: 5267

**Comment by lamaATS** [comment]
Can you check this now on main realm? (today was update rev. 5269).

**Comment by therealpadthai** [comment]
I will, just away from computer, will do it in a couple hours.

**Comment by therealpadthai** [comment]
@lamaATS I can confirm that this was fixed with update rev. 5269. Thank you for the fix :)

**Comment by lamaATS** [comment]
😸
