### ISSUE TITLE
[EN][Raid][Loot] Conclave of Wind

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#8680]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Boss body despawn less then a minute after the kill before any loot was distributed on 25 man**: Describe the problem

**Kill conclave of wind and body's disappear less then min after**: What happens

**Boss body should stay on the ground before all loot if removed from it**: What should happen instead

**Steps to reproduce the problem**:

1. Go to Tot4W
2. Kill Conclave of wind
3. Wait some seconds 

**rev. 5269**: Current server version

**Comment by Reno323** [comment]
I was on that raid. Body of the boss (with loot) despawn after 3-5min.

**Comment by Piklo** [comment]
should be fixed in [rev. 5613](https://atlantiss.eu/changelog#rev5613)
