### ISSUE TITLE
[EN][Quest][Silverpine Forest] On Her Majesty's Secret Service

### ISSUE THREAD

**Issue by xStiven** [Atlantiss/BugTracker#8681]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: NPC Lord Godfrey isn't giving "On Her Majesty's Secret Service" quests. 

**Current behaviour**: After "7th Legion Battle Plans" and "Sowing Discord" is done, NPC Lord Godfrey which running together with PC and two other npc, isn't giving next quests in chain "On Her Majesty's Secret Service"

**Expected behaviour**: The npc should give the quest immediately after "7th Legion Battle Plans" and "Sowing Discord" is finished.

**Steps to reproduce the problem**:

1. Do the chain until last 2 quests.
2. ???
3. No profit, no next quests.

**Revision**: ACore rev. 5269 hash. e09b68089d49 2016-12-14 23:02:45 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

http://cata.openwow.com/quest=27594   the quests.
http://wow.gamepedia.com/Quest:The_Warchief's_Fleet    Whole chain.

Reposting since this bug is persist from 2014 up to this day. Old topic probably has been burried under tons of others and dev don't see it.

**Comment by Piklo** [comment]
#391

you can see current server revision by typing ".s in" in chat

**Comment by lomitoh** [comment]
The mission still does not appear

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14388-3918681-on-her-majestys-secret-service/
