### ISSUE TITLE
shop level reduction bugged

### ISSUE THREAD

**Issue by swepticle** [Atlantiss/BugTracker#8682]
hello

I'm currently shop level 3 but i don't recieve the 10% reduction like it's supposed to be 
for instance the swift razzashi raptors base price is 550 vote points if you're shop level 3 it's supposed to be 495 vote points but it is not.

what should I do?

regards, a good friend

**Comment by Piklo** [comment]
http://community.atlantiss.eu/index.php?/topic/11920-atlantiss-qa/?p=59574
"**Q: I would like to know what about "5th level shop's features". I guess that I'm not the only one who reached 5th lvl in the shop and would be great to get some additional features from this**
**A:** It’ll be introduced together with the new website."
