### ISSUE TITLE
[Event][Winter Veil] Bros, Before Ho's Ho's Ho's

### ISSUE THREAD

**Issue by Damfee** [Atlantiss/BugTracker#8686]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: For this achievement, you go around looking for Brothers, and use the Mistletoe on them. http://www.wowhead.com/achievement=1686/bros-before-ho-ho-hos

**Current behaviour**: Everything works fine, except for Brother Wilhelm (Goldshire). You cannot use the mistletoe on him.

**Expected behaviour**: Your mistletoe should be applied to him, giving you credit for the achievement.

**Steps to reproduce the problem**:

1. Get Mistletoe 
2. Use on Brother Wilhelm
3. Fail

**Revision**: Current server version

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by Shaie454** [comment]
Yes i can confirm it does not work.

**Comment by coba999** [comment]
Again, the problem with the Alliance! The Horde has all right. Coincidence? I don't think so! The developers sabotage the Alliance!

**Comment by coba999** [comment]
@Piklo **Revision:** ACore rev. 5269 hash. e09b68089d49 2016-12-14 23:02:45 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Bildo** [comment]
What information do you get when trying to cast mistletoe on him?

**Comment by Delirath** [comment]
Brother Wilhelm can't receive the object "Mistletoe" and thus can't do achievement.

**Comment by coba999** [comment]
@Piklo can't cast Mistletoe on him.

**Comment by krecik88** [comment]
fixed
