### ISSUE TITLE
[PL][Raid-Cata] Throne of the Four Winds, Conclave of Wind, Rohash

### ISSUE THREAD

**Issue by InformatorPE** [Atlantiss/BugTracker#869]
http://www.wowhead.com/zone=5638
http://www.wowhead.com/npc=45872
http://www.wowhead.com/spell=86193

Wind Blast na Rohashu na Throne of the Four Winds nie odrzuca graczy.

**Comment by mrkariox** [comment]
Kiedy Al'akir (http://www.wowhead.com/npc=46753/alakir) uzyje **Wind Burst** (http://www.wowhead.com/spell=87770/wind-burst) w momencie gdy **gracz znajduje sie poza platforma** (wyskoczy z niej) to **crashuje klient wowa**, gdyz serwer nie wie gdzie takiego gracza odrzucic.

Sprawdzane w wersji **HC** bossa, w wersji **NORMAL** bug chyba nie wystepuje, ale nie jestem pewien.

**I zeby nie bylo dalszych nieporozumien, wnosze o zmiane nazwy tematu na temat ogolny o Throne of the four winds, a nie totfw-conclave**

**Comment by arekczup** [comment]
mnie jak odrzuci i trawie na wir to mam i tak crash bo nie wie gdzie odrzucić :P
