### ISSUE TITLE
 [EN][QUEST][Fade to Black]

### ISSUE THREAD

**Issue by xStiven** [Atlantiss/BugTracker#8690]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Buged quest, one of two NPC which need to kill in quests, is un-attackable, 

**Current behaviour**: Twilight Lord Katrana - is can be killed, but Malicion - dragon, just hovering above on one spot and can't be killed or attacked. He is in range of attacks but just can't be attacked.

**Expected behaviour**: At very least  Malicion should be killable. There is video https://www.youtube.com/watch?v=38NkHijK0Kk

**Steps to reproduce the problem**:

1. none. 

**Revision**: ACore rev. 5269 hash. e09b68089d49 2016-12-14 23:02:45 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

http://www.wowhead.com/quest=24467/fade-to-black

**Comment by Fabiana-B** [comment]
#8605

**Comment by silberberg44** [comment]
'fraid this issue still stands. Killing Twilight Lord Katrana doesn't trigger Malicion - he just stands in one place and rotates only at Lord Katrana's side, does literally nothing besides that.

**Comment by Batranelu** [comment]
The quest still doesn't work , killing twilight lord Katrana doesn't trigger Malicion!

**Comment by Bildo** [comment]
fixed
