### ISSUE TITLE
[EN][Warlock][Spell] Summon Felhunter

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8691]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  Summons a Felhunter under the command of the Warlock.

Link to felhunter: http://cata.openwow.com/spell=691
Link to soulburn: http://cata.openwow.com/spell=74434

This is for all minions not just felhunter.

Proof: https://www.youtube.com/watch?v=PAM2YYf4Au0
Go to 0:39 and you see him summoning a new pet with full health

**Current behaviour**: If your pet has 50% hp and you summon a new one using soulburn -> summon felhunter it spawns with same amount of health as when it dissapeared.

**Expected behaviour**: Should have full hp/mana

**Steps to reproduce the problem**:

1. Have someone damage your felhunter to 50%
2. Soulburn + summon felhunter
3. Watch how felhunter has same amount of health

**Revision**: 5269

**Comment by Jenovas** [comment]
Rev 5272 - Resummoning a pet will reset its CDs and set HP / Mana to full
