### ISSUE TITLE
[EN][Quest][Borean Tundra] Emergency Protocol: Section 8.2, Paragraph D

### ISSUE THREAD

**Issue by Delirath** [Atlantiss/BugTracker#8693]
![wowscrnshot_121916_100524](https://cloud.githubusercontent.com/assets/24631226/21307138/8064be02-c5d4-11e6-97db-02e77b8cb205.jpg)
Quest item only works on one machine. Using on the Southern and Northwestern doesn't work 
after many tries. I tried to use the item in many places around the machines but doesn't work in any of them.

**Comment by coba999** [comment]
There is another plane. Search it.

**Comment by Delirath** [comment]
Read- "Using on the Southern and Northwestern doesn't work
after many tries".

**Comment by aendry** [comment]
still broken

**Comment by Piklo** [comment]
#2452
