### ISSUE TITLE
[EN][Quest][Northrend - Borean Tundra] [Hellscream's Vigil]

### ISSUE THREAD

**Issue by ixvenomxi** [Atlantiss/BugTracker#8696]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Garrosh Hellscream isnt in the hall to continue with the mision 

http://www.wowhead.com/quest=11586/hellscreams-vigil
https://www.youtube.com/watch?v=E7VL443vgyY

**Current behaviour**: Garrosh Hellscream isnt in the hall, so i cant finish the mision.

**Expected behaviour**: The vidio shows that Garrosh must be in the hall up the map on the floor.

**Steps to reproduce the problem**:

1. Take the mision for northrend
2. In Northrend take the mision Hellscream's Vigil
3. Garrosh Hellscream isn´t in the hall to completed

**Revision**: Quest ID: 11585

**Comment by Sayris9876** [comment]
Most recent alt I leveled was few days ago and I started with Borean Tundra... Everything went well and he was there and every quest was working properly.

**Comment by Samineh** [comment]
Got the same bug today. Rev: 5319

**Comment by Samineh** [comment]
Link for garrosh: http://www.wowhead.com/npc=25237

**Comment by xmesaj2** [comment]
Are you sure Alliance haven't killed him? It's boss type so has probably about 10h respawn timer

**Comment by Samineh** [comment]
Any reference for 10 hours respawn?
