### ISSUE TITLE
[EN][Warlock][Talent][Spell] Affliction Eradication talent/spell/buff

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8700]
**Description**:
the buff Eradication seems to have a  internal cd, what it should not have
http://cata.openwow.com/spell=64371
http://us.battle.net/wow/en/game/patch-notes/3-1-0
http://wowwiki.wikia.com/wiki/Eradication

**Current behaviour**: 
Eradication procs once everry 45-60 sec

https://www.youtube.com/watch?v=ixEUg6cIolY
desc: u can see that:
Eradication proced 8 times,
Power Torrent proced 7 times
Shadow Trance proced 31 times

Shadow Trance has a 8% proc chance, no ICD
Eradication   has a 6% proc chance, no ICD
Power Torrent has a 45sec ICD

**Expected behaviour**: 
every tic of corruption on every  target with it has a ( and in theory u can have up to 17-18  targets with it on) 6% chance of giving a 20% buff for 10 sec

**Steps to reproduce the problem**:

1. be a warlock
2. go spread corr
3.  watch how often the talent/spell procs

**Revision**: 5269

**Comment by Zhalox123** [comment]
Confirmed on my alt lock.

**Comment by Jenovas** [comment]
Fixed in rev 5272
