### ISSUE TITLE
[EN][Warrior][Spell][Shattering Throw]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#8701]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: It doesn't remove Ice block. Probably doesn't remove anything at all, must test it on other immunities as well.

**Current behaviour**:
![wowscrnshot_122116_203539](https://cloud.githubusercontent.com/assets/12395407/21404295/cda1a976-c7c0-11e6-862a-fb280f6318bf.jpg)

**Expected behaviour**: It should remove ALL invulnerabilities (at least on players), including bubble and ice block.
**Steps to reproduce the problem**:

1. Find a mage
2. Force him to use IB
3. Try to dispel it with ST
4. FAIL

**Revision**: 5269

**Comment by sigmundfreud2016** [comment]
![wowscrnshot_122216_163106](https://cloud.githubusercontent.com/assets/12395407/21432420/c9305c10-c86b-11e6-9c8e-cc9c009f7a5a.jpg)
another prove, made just today

**Comment by sigmundfreud2016** [comment]
bump, it's VERY important! 5 min CD ability is currently completely useless.

**Comment by Jenovas** [comment]
Works properly. The log shows "The user was immune" to the DMG part and after that the immunity (Ice Block, Divine Shield) gets removed. Closing issue.
