### ISSUE TITLE
[EN][Quest][Blackrock Depths][Warlock] Stones of Binding

### ISSUE THREAD

**Issue by fox82es** [Atlantiss/BugTracker#8702]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
When you go to the dungeon zones marked in the quest, there aren't any [stone](http://www.wowhead.com/object=207145/elemental-binding-stone) to get the items needed to finish the quest: "[Elemental Binding Stone](http://www.wowhead.com/item=64308/elemental-binding-stone)"

**Current behaviour**: What happens
As there aren't such objects the quest cannot be finished

**Expected behaviour**: What should happen instead
One should find the stones and get the items to finish the quest

**Steps to reproduce the problem**:

1. Take the level 50 warlock quest ["Stones of Binding"](http://www.wowhead.com/quest=28399/stones-of-binding)
2. Go to Blackrock Depths dungeon
3. Go to marked locations and the stones aren't there.

**Revision**: Current server version

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/2201
