### ISSUE TITLE
[EN][Mage][Spell][Arcane missiles] Number of missiles fired by Arcane missiles variers

### ISSUE THREAD

**Issue by Featurer** [Atlantiss/BugTracker#8704]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Mage] Arcane missiles
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
http://www.wowhead.com/spell=5143/arcane-missiles#modified-by

**Description**: Number of missiles fired by Arcane missiles variers. Spell id: "ID 5143"

**Current behaviour**: When a player cast Arcane missiles it firing varied, between 4 and 5 missiles.

**Expected behaviour**: When a player cast arcane missiles it should always be firing 5 missiles, when a mage have specced "improved Arcane Missiles", if not it should fire 3 missiles. 

**Steps to reproduce the problem**:

1. Cast arcane blast til Arcane missiles procs
2. Cast Arcane missiles and let it FINISH
3. Look at recount, it will tell how many counts there is by arcane missiles.

**Revision**: Current server version
5269

**Comment by pelekon** [comment]
title

**Comment by pelekon** [comment]
and links

**Comment by Featurer** [comment]
Noidea, how I do that, first time in here :)

**Comment by Featurer** [comment]
Changelog from 4.3.0, Build 14849 it says: Launches five, four, three waves of arcane missiles at the enemy over 2 sec. Looks like there is nothing wrong then?

**Comment by rasmodeus** [comment]
Three is the default number of missiles fired before talents.  2/2 Improved Arcane Missiles gives the 5 missiles.  If there is a fluctuation in the number of missiles fired, then that particular talent (and indeed the spec as Arcane Missiles is a good chunk of dps) has issues.

**Comment by Featurer** [comment]
I remember from retail when I was playing Arcane mage in this expenasion, Arcane Missiles with 2/2 Improved Arcane Missiles always fired five missiles.

**Comment by sigmundfreud2016** [comment]
I think it could be merged with penance-thread https://github.com/Atlantiss/BugTracker/issues/8708

**Comment by Featurer** [comment]
Could someone look up this please? Thanks :)

**Comment by Featurer** [comment]
Have anyone taken a look at this ?

**Comment by Piklo** [comment]
fixed in [rev5472](https://atlantiss.eu/changelog#rev5472)
