### ISSUE TITLE
[EN][Item] Ribboned Wrapping Paper

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8706]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Ribboned Wrapping Paper doesn't working

**Current behaviour**: [Red Ribboned Wrapping Paper](http://www.wowhead.com/item=5042/red-ribboned-wrapping-paper) and [Green Ribboned Wrapping Paper](http://www.wowhead.com/item=17304/green-ribboned-wrapping-paper) doesn't working. Impossible to wrap an object in festive paper.
**Expected behaviour**: Wrap an object in festive paper.

**Steps to reproduce the problem**:

1. Buy [Red Ribboned Wrapping Paper](http://www.wowhead.com/item=5042/red-ribboned-wrapping-paper) and [Green Ribboned Wrapping Paper](http://www.wowhead.com/item=17304/green-ribboned-wrapping-paper);
2. Try to use it on any item and nothing happening;

**Revision**: 5269

**Comment by Piklo** [comment]
#5420 #4843
