### ISSUE TITLE
[EN][Firelands][Baleroc] Shard of Torment twice ticking

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8707]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Shard of Torment

**Current behaviour**: When someone take Shard of Torment it tick twice(double) damage instant.
Plus, the maximum stacks is not 24x. we had 26x and 28x.

**Expected behaviour**: Shard of Torment should every X second deal Y amount of damage plus apply debuff which increase the damage taken.
Maximum shard ticks - 24x.

**Steps to reproduce the problem**: 

1. Go Baleroc Fight him.
2.  stand  near Shard of Torment and take damage & heals
3. watch sometimes you get double ticks.

**Revision**: rev. 5269

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by Illusie** [comment]
fixed.
someone can watch it and fix baleroc shard? it bug again, thank you.

**Comment by Aival94** [comment]
As far as i know this has been fixed.
