### ISSUE TITLE
[EN][RAID][BWD][Magmaw] Lava Parasites dont spawn at all

### ISSUE THREAD

**Issue by CatchmeATS** [Atlantiss/BugTracker#8710]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: On normal difficulty. Lava parasites dont spawn. Dont know about HC.

**Current behaviour**: Pillar of flame appears on time but it doesnt spawn any lava parasites and thus makes this fight plain tank and spank.

**Expected behaviour**: Pillar of flame should spawn several lava parasites.

**Steps to reproduce the problem**:

1. Engage Magmaw N
2. Wait for Pillar of flame.
3. Watch the nothingness.

**Revision**: 5269

**Comment by therealpadthai** [comment]
Same on HC.

**Comment by coba999** [comment]
can anyone tell, how this bug could even happen?

**Comment by sunshitwowsucks** [comment]
confirmed did it with guild on weds, and fight was dumbshit easy

**Comment by Fabiana-B** [comment]
Confirmed.
