### ISSUE TITLE
[EN][Professions][Inscription] Unable to Craft Swords Deck

### ISSUE THREAD

**Issue by RobHibicus** [Atlantiss/BugTracker#8711]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: It's impossible to craft [[Swords Deck]](http://www.wowhead.com/item=37164/swords-deck). [[Four of Swords]](http://www.wowhead.com/item=37160/four-of-swords) doesn't drop from a [[Strange Tarot]](http://www.wowhead.com/item=44142/strange-tarot). [[Five of Swords]](http://www.wowhead.com/item=37161/five-of-swords#comments) drops instead which never happened on retail.

**Current behaviour**: You open a Strange Tarot and receive either Ace of Swords, Two of Swords, Three of Swords, or _Five_ of Swords.

**Expected behaviour**: You open a Strange Tarot and receive either Ace of Swords, Two of Swords, Three of Swords, or _Four_ of Swords.

**Steps to reproduce the problem**:

1. Open Strange Tarot
2. Don't receive Four of Swords

**Revision**: 5269

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12612-8711-strange-tarot-loot-tables/

**Comment by Piklo** [comment]
#7042
