### ISSUE TITLE
[EN][Quest][Borean Tundra] Abduction

### ISSUE THREAD

**Issue by ixvenomxi** [Atlantiss/BugTracker#8715]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: i cant attack the mob that i have to capture, and the item for capture him dont work

**Current behaviour**: the mob it shows me as friend, so i cant attack him, and the item for capture the mob dont work.

https://postimg.org/image/86gq9klyb/

**Expected behaviour**: it should let me atack that mob for capture him, and the item for that must work it.

http://www.wowhead.com/quest=11590/abduction
https://www.youtube.com/watch?v=UMLZt759z3U

**Steps to reproduce the problem**:

1. Take the mision
2. Going to the zone and attack de mob and let him in 30% life
3. use the item for capture the mob
4. get back to the place where it take de mision
5. finish the mision

**Revision**: 5269

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat
#7183 #4651
