### ISSUE TITLE
[EN][QUEST][SILVERPINE FOREST] Belmont's Report

### ISSUE THREAD

**Issue by Penfoer** [Atlantiss/BugTracker#8717]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Question mark doesn't show above Sylvanas 

**Current behaviour**: After i got Belmont's Report, i can't deliver it to Sylvanas because i can't interract with her.

**Expected behaviour**: I should delliver quest item [Belmont's Report] to Sylvanas, talk to her and end the quest.

http://www.wowhead.com/quest=27056/belmonts-report

**Steps to reproduce the problem**:

1. Take the mission from Belmont
2. Go deliver Belmont's Report to Sylvanas
3. Can't talk to her (no question mark)

**Revision**: 5269

**Comment by Khangu** [comment]
Two things more...
First - wowhead indicates that she can be found at Sepulcher. True but not at this point of chain. Sylvanas standing at Forsaken High Command is the correct one.
Second - this little bug locks entire Silverpine chain almost at begining thus making questing there impossible.

**Comment by krecik88** [comment]
working as it should, you need to give the quest to the first sylvanas, not the one mentioned on wowhead.
Check this video:
https://www.youtube.com/watch?v=VSqCsNcZTUU

**Comment by Khangu** [comment]
Eeem isn't it what I said? Check once more please.
The first = Sylvanas standing at Forsaken High Command (shown in the movie) -> she's the correct one and she's the bugged one.
The second at sepulcher (wowhead location) sits in another phase and is inaccessible anyway at this point of quest chain.

**Comment by krecik88** [comment]
"she's the correct one and she's the bugged one."
show me some screenshot with that she's bugged, because i created new char yesterday and did this quest properly.

**Comment by Khangu** [comment]
Sorry I wasn't able to check it earlier. But at this moment quest is working fine again.
