### ISSUE TITLE
[PL][EVENT][WINTER HAT}

### ISSUE THREAD

**Issue by rafal363** [Atlantiss/BugTracker#8718]
witam  z bossta http://www.wowhead.com/npc=26731/grand-magus-telestra#drops:mode=heroic,  o ile dobrze pamietam powinna leciec "red winter hat" 100 % dropu na hc  , przy dodatku cata

**Comment by ysiu15** [comment]
Idz na norma . 30 % ze padnie. ja tak farmilem.
