### ISSUE TITLE
[EN][NPC][Vashj'ir][Quartermaster] Provisioner Arok

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#8719]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/npc=50324/provisioner-arok is missing

**Current behaviour**: 
![wowscrnshot_122416_145924](https://cloud.githubusercontent.com/assets/12395407/21467332/e3d013c4-c9e9-11e6-981d-ef4ac9bba3f5.jpg)

**Expected behaviour**: He should be in the cave. I know that Vashj'ir is not scripted etc, BUT since Earthen Ring reputation can be obtained via quests in Deepholm & Twilight Highlands, it is possible to get friendly with them, buy the tabard from this guy, get more rep and obtain all his items. It shouldn't be so hard to place him there, just him, nothing else.

**Steps to reproduce the problem**:

1. Travel Vashj'ir
2. Use any water breathing
3. Swim to the cave (entrance near second "o" in the word "hollOw")

**Revision**: 5269

**Comment by Piklo** [comment]
Vashj'ir is not scripted yet

**Comment by sunshitwowsucks** [comment]
i think he is where therazane is.

**Comment by sigmundfreud2016** [comment]
@Piklo have you read my post?
@sunshitwowsucks doubt it, there is no reason for it http://wowwiki.wikia.com/wiki/Therazane%27s_Throne
Check it anyway if you can, if he is really there, it's a bug as well.

**Comment by sunshitwowsucks** [comment]
he was added there because vashjr isnt scripted next to therazane quartermaster, im pretty sure.. atelast

**Comment by sigmundfreud2016** [comment]
@sunshitwowsucks 
I am not so far with Deepholm quests yet, can't enter the Throne.

**Comment by Piklo** [comment]
@sigmundfreud2016 my bad, didnt read everything. Like @sunshitwowsucks said, he is near therazane quartermaster
![wowscrnshot_122416_174801](https://cloud.githubusercontent.com/assets/16057987/21468011/279ff01c-ca01-11e6-8f54-c72e3e15d229.jpg)

**Comment by sigmundfreud2016** [comment]
Thanks, I think I 'll close it then.

**Comment by sigmundfreud2016** [comment]
@Piklo Reopening since I can't find anyway to get that far in the quest chain. I did all the quest I could find except https://github.com/Atlantiss/BugTracker/issues/7400 and I still have 0 Therazane rep, can't do their quests and ofc can't get to the Throne. How did you manage to do it?

**Comment by Piklo** [comment]
"except Take Him to the Earthcaller" this one quest is required in this chain :D
http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller#comments:id=1627881

**Comment by sigmundfreud2016** [comment]
@Piklo So, this guy is indeed unaccessible by now. At least for those who didn't this quest before, when it worked.

**Comment by Piklo** [comment]
@sigmundfreud2016 you can't fly to him without doing quests?

**Comment by sigmundfreud2016** [comment]
@Piklo No, there is no way to get to the Throne without quest chain, except **MAYBE** a warlock.

**Comment by Piklo** [comment]
@sigmundfreud2016 im hated with therazane but i flew here without problems.
![wowscrnshot_122516_142313](https://cloud.githubusercontent.com/assets/16057987/21471305/e3ac463c-caad-11e6-8759-a76535840ffc.jpg)

**Comment by sigmundfreud2016** [comment]
where is it then?

**Comment by Piklo** [comment]
near [D'lom the Collector](http://www.wowhead.com/npc=45408/dlom-the-collector) :P

**Comment by sigmundfreud2016** [comment]
@Piklo just got there, thanks & closing.
