### ISSUE TITLE
[EN][world?] battlegrounds, graveyards and respawn

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#8720]
if i take a base on arathi basin and some horde is respawning there in the meantime it doesnt even matter if i take the base horde will respawn. horde finishes to respawn on a conquested base instead of geting teleported somewhere else
steps to reproduce? go in arathi basin see for yourself

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
