### ISSUE TITLE
[EN][Quest][Uldum]"Gnomebliteration"

### ISSUE THREAD

**Issue by DevilDesire7** [Atlantiss/BugTracker#8721]
When you take the ball and go through the gnomes they don't die as they are supposed to. You still push them around but they are alive and unharmed.

**Expected behaviour**: The gnomes should die...

**Steps to reproduce the problem**:

1. Take the quest
2. Take the ball
3. Try to kill the gnomes with it.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
you can see current server revision by typing ".s in" in chat

**Comment by krecik88** [comment]
I've just tested it on server and on local, everything is working fine. 
Please provide more info screenshot or movie.
