### ISSUE TITLE
[EN][Quest][Uldum] "Therazane's Mercy"

### ISSUE THREAD

**Issue by DevilDesire7** [Atlantiss/BugTracker#8722]
**Description**: One of the quest mobs to kill, "High Priestess Lorthuna", cannot be targeted and therefore killed.

**Expected behaviour**: The mob should be targetable and killable.

**Steps to reproduce the problem**:

1. Go to the specified spot where the mob is.
2. Target it.
3. Try to attack it.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
you can see current server revision by typing ".s in" in chat
