### ISSUE TITLE
[EN][Quest][Firelands] Alysrazor Siphon, Heart of Flame

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8723]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: You cant siphon Alysrazor, not me and not another dude who has the quest.
http://i.imgur.com/G5fOVLq.jpg

**Current behaviour**: Can't siphon Alysrazor

**Expected behaviour**: You should able to siphon Alysrazor

**Steps to reproduce the problem**:

1. kill alysrazor heroic
2. try to siphon
3. see what happen

**Revision**: 5269

**Comment by blinkmaster** [comment]
There is a workaround for that i think (noticed last week) 
Cloud for siphoning is hovering in the air maybe if ur fast enough a sec after kill u might be able to siphoning it, worth testing

**Comment by sunshitwowsucks** [comment]
#8472

**Comment by Illusie** [comment]
still not working / fixed.

**Comment by Illusie** [comment]
Still not working.
Canont siphoning Alysrazor and I lost like 40 points during this month cause of Alysrazor bugged.
please notice it.

@Jenovas

**Comment by Piklo** [comment]
#8472 duplicate
