### ISSUE TITLE
[EN][Talent ][MAGE][Ignite] Ignite duration and damage.

### ISSUE THREAD

**Issue by PolpoVolante** [Atlantiss/BugTracker#8725]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When Ignite is refreshed the duration should be 6 seconds and do 3 ticks of equal damage
http://cata.openwow.com/spell=12846#see-also-ability

"Following this new system, ignite's behavior is as follows: 
- Ignite's initial application will be 4s in duration: 2 ticks, one at 2s, one at 0s. Ignite's total damage pool is divided between these two ticks.
- Any refreshes at any time will refresh ignite to 6s in (max) duration (current duration is ignite's current duration mod 2 plus 4s): 3 ticks, one at 4s, one at 2s, one at 0s. Ignite's damage pool is divided evenly between these three ticks.
- Ignite must be below 4s in current duration to accept any new refresh events."
From:
https://web.archive.org/web/20120126062032/http://elitistjerks.com/f75/t110326-cataclysm_fire_mage_compendium 

Video from retail: https://www.youtube.com/watch?v=4AQypHQOtY0 at around 1:40 look at ignite on the left 

**Current behaviour**: Ignite when refreshed is still 4 seconds and does equal damage .
After more testing I found out that ignite increases duration to 6 seconds if you crit before the first tick (from 4 to 2 secs remaining on ignite), and after that it will only get refreshed to 6 seconds again if you crit from 4 to 6 seconds.

**Expected behaviour**: Ignite when refreshed should add 4 seconds to the remaining dot (max 6 seconds) and add an additional tick.

**Steps to reproduce the problem**: 
1.  go to a dummy 
2.  cast scorch 
3.  observe ignite ticks from crits in a row

**Revision**: 5269

**Comment by PolpoVolante** [comment]
surprised this wasnt reported yet.

**Comment by Illusie** [comment]
I think they re-worked Ignite when I reported on 300k max ignite LamaATS said something about re-work the Ignite.

**Comment by PolpoVolante** [comment]
No it is bugged since ever i tought thie was reported so i didnt do anything but today i noticed and reporter it. 
Im Pretty sure is bugged By atleast March that i got my mage.

**Comment by CatchmeATS** [comment]
I dont even remember the last time I saw 6s ignite renew. You might be onto something.
Something might be wrong with ignite in general, if you stand too close to some target, sometimes you can have large periods of time with 0 or very very low ignite.

**Comment by Zhalox123** [comment]
Ignite and Combustion is overall rly fucked up on Atlantiss its nothing compared to Retail or even AT but its still decently manageble hope they check it out better.

**Comment by PolpoVolante** [comment]
@catchme that is because munching nothing they can really do to fix it if not making it less of a pain.
If they fix this One bug the mage Will be less rng because now if you dont crit 6 times in a row you wont get a decent ignite and Aldo imo the rng in Atlantiss is bugged aswell but have no proof.

**Comment by Fearyourself** [comment]
Rng on 'lantiss is fine. Frostfire orb grants FoF on each attack and we're getting ruins/dalaran arenas all day <3

**Comment by PolpoVolante** [comment]
I'll post my findings in crit chance in the forums since is more appropriate for now lets talk about ignite pls.

**Comment by Fabiana-B** [comment]
I'm the only one thinking, I have some ignite procs with low duration... 

I don't know how to confirm this, lemme hit a dummy :p

**Comment by PolpoVolante** [comment]
bumperino?

**Comment by Piklo** [comment]
@PolpoVolante you can close your own post ;p
![awsfdgh](https://cloud.githubusercontent.com/assets/16057987/22617990/f409873a-ead1-11e6-9b0c-b56852a37206.PNG)
