### ISSUE TITLE
[PL][QUEST][HELLFIRE PENINSULA] The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by donsledz** [Atlantiss/BugTracker#8727]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Wymagany NPC nie posiada opcji dialogowej potrzebnej do rozpoczęcia questa
**Current behaviour**: What happens
Nic się nie dzieje. Nie można wybrać opcji dialogowej w rozmowie z NPC

**Expected behaviour**: What should happen instead
Powinno się pogadać z Anholite Barrada i rozpocząć w ten sposób egzorcyzm.
Tak to powinno wyglądać : https://www.youtube.com/watch?v=zHjh0i5vXRQ
**Steps to reproduce the problem**:

1. Rozpocząć questa u Assistant Klatu w karczmie w Honor Hold
2. Udać się do Anholite Barrada i porozmawiać z nim
**Revision**: Current server version

**Comment by Piklo** [comment]
możesz zobaczyć aktualny server revision wpisując ".s in" w czacie w grze

**Comment by DuGalle** [comment]
confirm broken it locks down 3 more quests from chain

**Comment by donsledz** [comment]
Fortunately, we can earn loremaster without it :)
