### ISSUE TITLE
([PL][Quest][Silverpine Forest] Belmont's Report ) 

### ISSUE THREAD

**Issue by Dorael22** [Atlantiss/BugTracker#8728]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Nie mogę porozmawiać z Lady Sylvanas i to uniemożliwia mi dalszą rozgrywkę.

**Current behaviour**: Nie można wykonać żadnej interakcji z NPC.

**Expected behaviour**: Możliwość porozmawiania z NPC i oddaniem quest itemu.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) albo [cata.openwow.com](http://cata.openwow.com/) linki
możesz zobaczyć aktualny server revision wpisując ".s in" w czacie w grze

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/8717
