### ISSUE TITLE
[EN][Quest][Westfall] Westfall Stew

### ISSUE THREAD

**Issue by VioletFlare** [Atlantiss/BugTracker#8730]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
[Wowhead: Westfall Stew](http://www.wowhead.com/quest=26241/westfall-stew)
While collecting [Okra](http://www.wowhead.com/item=57911/okra) i noticed some bushes didn't despawn after being foraged. Their content didn't respawn either, they stayed empty for the whole time. 
**Current behaviour**:
Bushes do not disappear.
**Expected behaviour**:
Bushes should disappear.
**Steps to reproduce the problem**:

1. get [Wowhead: Westfall Stew](http://www.wowhead.com/quest=26241/westfall-stew) quest
2. forage the bush
3. if it didn't disappear it means that it might be one of the buggy ones

**Revision**: 5269

**Comment by krecik88** [comment]
fixed
