### ISSUE TITLE
[PL][Item][NPC][Priest] Cauterizing Flame

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#8732]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Cauterizing Flame (guardian) (http://www.wowhead.com/spell=99136/cauterizing-flame#comments) generuje "aggro" (nie mylić z "threat")

**Current behaviour**:  W momencie aktywacji bonusu 4p u priesta (holy/discipline) pojawia się niewidzialny "guardian/pet" znany jako "Cauterizing Flame". Wygląda na to, że guardian jest dostrzegany tylko przez NPC i generuje aggro. W efekcie całego procesu moby są nawet w stanie zabić "guardiana" tym samym negując efekt uzdrowienia.

**Expected behaviour**: Proc "Cauterizing Flame" przywołuje "Cauterizing Flame" (guardiana), który nie generuje aggra, nie może być namierzony przez NPC i nie może zostać zabity (również przez efekty AoE).

**Steps to reproduce the problem**:

1. Udaj się do miejsca jako priest gdzie stacjonują liczne grupki "mobów" (Firelands, Chamber of fanatics w Stonecore)
2. Ustaw się na pozycji w której żaden "mob" nie aggruje się na gracza
3. Rozpocznij intensywny healing w siebie lub innego gracza do czasu aż nie procnie bonus z czterech partów "Cauterizing Flame" (ja testowałem za pomocą "Prayer of Healing")
4. Nagle "całe" otoczenie zostaje pullnięte

Garść ciekawostek które pozwolą zrozumieć działanie:
**Cauterizing Flame** jest często zbijany w tym procesie. Przypuszczam, że aggro bierze się z tytułu "małego lv" guardiana. Potwory na małych poziomach również ochoczo się rzucają na Cauterizing Flame, przykład:
(http://imgur.com/a/LhmuL)
**Cauterizing Flame** otrzymuje efekty od aur jednak nie zbadałem czy przekłada się to na heal guardiana.

**Revision**: 5269 hash. e09b68089d49 2016-12-14 23:02:45 +0100

Pozdrawiam.

**Comment by Piklo** [comment]
#7385

**Comment by Vyrtuz** [comment]
Fakt, nie zwróciłem uwagi na rozwinięcie tematu. Przepraszam za kłopot.

**Comment by Jenovas** [comment]
Should be fixed in rev 5272
