### ISSUE TITLE
Is this some kind of bug?

### ISSUE THREAD

**Issue by Spoown** [Atlantiss/BugTracker#8734]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. After dungeon Scholomance my character turned in some kind of meat as shown on screen shot.
![wowscrnshot_122816_192002](https://cloud.githubusercontent.com/assets/24814479/21528638/4050d6cc-cd34-11e6-8e11-77eb6b440d31.jpg)

2. Is this some bug or i need to do something. Any advice is appreciated.
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1661

Make a ticket in-game and stay on the same Character so a GM will help you.
