### ISSUE TITLE
[EN][RAID][Firelands][Ragnaros] Molten Elementals Don't Follow Always Focus Their Player

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8736]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When Molten Elementals spawn from their Molten Seeds they don't always focus and attack the player the seed dropped on

**Current behaviour**: Sometimes you will have 2 or more elementals on one person and no elementals on other people

**Expected behaviour**: Each player should have a Molten Elemental link to them and run at/attack ONLY that player unless that player dies.

**Steps to reproduce the problem**:

1. Fight Ragnaros with multiple players
2. Get to phase 2
3. Watch as eventually there won't be a Molten Elemental on you

**Revision**: 5269

**Comment by Jenovas** [comment]
Not true, watching Paragon you can easily see a hunter have 2 elementals on him.
Also quote from guides "Molten Elemental /// The Molten Elemental is spawned from a Molten Inferno. It will attack and fixate on a random player."
Closing.

**Comment by Prodiege** [comment]
Uhh. I am saying they should fixate on their players. I am also saying THAT DOESNT CURRENTLY HAPPEN. Please reread the bug report
