### ISSUE TITLE
[EN][RAID][Firelands][Ragnaros Heroic] Molten Elementals Can Be Knocked Back

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8737]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Molten Elementals Can Be Knocked Back - Heroic ONLY

**Current behaviour**: You can knock back Molten Elementals  - Heroic ONLY

**Expected behaviour**: You shouldn't be able to knock back Molten Elementals  - Heroic ONLY

**Steps to reproduce the problem**:

1. Fight Ragnaros ON HEROIC
2. Get to phase 2
3. Use a knockback on Molten Elementals

**Revision**: 5269

**Comment by Jenovas** [comment]
Proof?

**Comment by Prodiege** [comment]
https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

-Firelands

    -Ragnaros
        Molten Elementals can no longer be knocked back while having the Molten Power buff. Molten Elemental move speed has also been decreased by 15% on Heroic difficulty. These adjustments will require a realm restart to take effect.

**Comment by Piklo** [comment]
if i remember well, we have pre-nerfed firelands

**Comment by Prodiege** [comment]
This is questionable if it is a nerf or not
