### ISSUE TITLE
[EN][RAID][Firelands][Shannox] Attacks on Rageface

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8739]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Attacks on Rageface while he is channeling the ability called "Face Rage" should be critical strikes 100%, but are not currently

**Current behaviour**: Attacks on Rageface while he is channeling "Face Rage" are not always critical strikes

**Expected behaviour**: Attacks on Rageface while he is channeling "Face Rage" should always be critical strikes

**Steps to reproduce the problem**:

1. Engage Shannox
2. Wait until Rage Face jumps someone and starts channeling Face Rage
3. Attack him with any ability multiple times and witness not 100% crit chance

**Proof**: 

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Shannox

    Successful attacks on Rageface will now always be critical strikes while he is channeling Face Rage.

**Revision**: 5269

**Comment by Aival94** [comment]
Is this one still bugged?(never had any problem to do crit as any class on rageface when use Face Rage ability)

**Comment by TranceAccount** [comment]
If anyone can reproduce this bug, please comment and I will reopen it in due time.
