### ISSUE TITLE
 [EN][RAID][Firelands][Lord Rhyolith] Eruption Debuff feat. Phase 2

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8740]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Eruption Debuff is persisting into Phase 2

**Current behaviour**: Eruption Debuff is persisting into Phase 2

**Expected behaviour**: Eruption Debuff should be cleared when Phase 2 is activated

**Steps to reproduce the problem**:

1. Fight Rhyolith
2. Make sure you get some Eruption debuff from the volcanoes
3. Transition Rhyolith into phase 2 with Eruption debuffs still on you

**Proof**:

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Rhyolith

    The Eruption debuff is now cleared when transitioning into phase 2 of the fight.

**Revision**: 5269

**Comment by Jenovas** [comment]
This is a pre nerf mechanic. All bosses on FL HC are prenerf. Closing.
