### ISSUE TITLE
[EN][RAID][Firelands][Lord Rhyolith] Concussive Stomp Knockback

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8741]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Concussive stomp is knocking nearby players back

**Current behaviour**: When players are in close melee range to Lord Rhyolith, and he casts Concussive Stomp, they will get knocked back 

**Expected behaviour**: Players shouldn't get knocked back from Concussive Stomp at all

**Steps to reproduce the problem**:

1. Fight Lord Rhyolith
2. Stand underneath him 
3. Wait until he casts Concussive Stomp

**Proof**: 

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Lord Rhyolith
    Concussive Stomp should no longer knock nearby players back.

**Revision**: 5269

**Comment by Jenovas** [comment]
Players shouldget knocked back. This is a pre nerf mechanic. Closing.
