### ISSUE TITLE
[EN][RAID][Firelands][Majordomo Staghelm] Flame Scythe Bonus Energy

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8742]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Majordomo is not gaining additional energy when he hits 6 targets with Flame Scythe. He is gaining energy when he hits 5 or less targets.

**Current behaviour**: If majordomo hits 6 targets with his Flame Scythe he doesn't gain bonus energy

**Expected behaviour**: He should gain bonus energy when hitting 6 or less targets with Flame Scythe

**Steps to reproduce the problem**:

1. Engage Majordomo
2. Have 6 players in front of Majordomo
3. Get hit by Flame Scythe

**Proof**:

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Majordomo Fandral Staghelm

    Fandral now gains energy when his Flame Scythe hits fewer than 7 targets. The amount gained increases as fewer targets are hit.

**Revision**: 5269

**Comment by Prodiege** [comment]
It was never fixed correctly

**Comment by Aival94** [comment]
This one is fixed as far as i know. Please someone confirm.

**Comment by Prodiege** [comment]
No. The fix a while back was to try and make it this way. Please pay close attention to my wording. He should gain bonus energy when he hits fewer than 7 with flame scythe. Right now that only occurs when he hits fewer than 6 with flame scythe. So you can have 4 people. behind majordomo instead of only 3 right now

**Comment by Prodiege** [comment]
Why was this closed?

**Comment by Aival94** [comment]
Jenova said: 70 - 10 * players_hit.
So with 6 players the boss should be gaining 10 energy.
On this post https://github.com/Atlantiss/BugTracker/issues/8930 where i have tried to implement all known bugs including this one.
