### ISSUE TITLE
[EN][Item] Cauldron of Battle and Big Cauldron of Battle 

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#8744]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Cauldron of Battle and Big Cauldron of Battle disappearing too soon

**Current behaviour**: If someone has a Flask of Battle already in their inventory and they click on a cauldron then the cauldron will disappear regardless of how many flasks are left in it

**Expected behaviour**: Cauldron shouldn't disappear until all flasks have been taken from it. Cauldrons shouldn't give the player any more flasks until they use the one in their inventory.

**Steps to reproduce the problem**:

1. Drop a Cauldron
2. Take 1 flask and keep it in inventory
3. Take 2nd flask

**Extra Info**:

https://worldofwarcraft.com/en-us/news/3019413/patch-4-2-hotfixes

- Items

Cauldron of Battle and Big Cauldron of Battle no longer lose flask charges from repeated clicks when players already have one in their inventory.

**Revision**: 5269

**Comment by Aival94** [comment]
Because we use Cauldron every time if someone double click the cauldron will count it as a second flask being taken(even if the member has the one flask already in his/her inventory.

So it does not just disappear but instead it just count all the Clicks(even if no flasks is being given for some reason)

**Comment by pelekon** [comment]
fixed in rev 5903
