### ISSUE TITLE
[EN][Spell][Shaman][Enhancement] Flametongue weapon

### ISSUE THREAD

**Issue by bonfax4** [Atlantiss/BugTracker#8745]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Flametongue weapon on hit is doing way less damage than expected  and few other issues.

- Damage with my gear is being simmed around 2.6k - 4.7k nonccrit / 4.1 - 7.3k crit damage  self buffed . Currently doing @ 0.4k-2.1k dmg ( 2.1k being the max crit ).

- Clearly something wrong with the scaling.( "Patch 4.0.6 (8-Feb-2011): Flametongue Weapon procs now deal roughly 20% less damage.; Flametongue Weapon damage now scales from attack power instead of spell power (for Enhancement shaman only" http://wowwiki.wikia.com/wiki/Flametongue_Weapon).

- AP procs ( Landslide ) not making any change on the dmg output. Also, flametongue seems to be doing random amounts of dmg regardless of if you have any  mastery proc or crits. The dmg should be for the most part static unless you get procs/crits. The only stats affecting the dmg should be mastery / ap (agi) / sp / spell dmg taken debuff / t12 4pc / talents.

- This video can be used as reference ( https://www.youtube.com/watch?v=sD9anO-GViY @ 1:50 ). You can see flametongue damage being way higher.

- Discussion about formulas on this page [here](https://cata-twinhead.twinstar.cz/?issue=6366)

**Current behaviour**: Flametongue doing less damage than what it's supposed to do

**Expected behaviour**: Should be doing more damage

**Steps to reproduce the problem**:

1. Training dummy
2. enchant off hand flametongue
3. autoatack and tickle the dummy

**Revision**: 5269

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by bonfax4** [comment]
Self buffed formula :  
( **damageFTBase** + (**damageFTCoef** * **attackPower** )) * ( **UnhastedOHSpeed** / 4.0 ) * **otherPersonalModifiers**

damageFTBase = 306
damageFTCoef = 0.1253

**otherPersonalModifiers :** Mastery ,  Elemental Precision talent  , FT dmg multiplier * Elemental Weapons talent , t12 4pc .

**Sources :** [here](https://rawr.svn.codeplex.com/svn/Rawr-4.3/Rawr.Enhance/CalculationsEnhance.cs) and [here](https://cata-twinhead.twinstar.cz/?issue=6366)

**Comment by Jamishman** [comment]
bump

**Comment by bonfax4** [comment]
BUMP! Enhancements have the worst gear scalings already on this release already and this just makes it worse..

**Comment by sebastian-luczak** [comment]
Enh Shammys are now broken beyond point, they're rarely seen on raids. Most of enh already respecced to ele 'cause of this bug. I can confirm this bug, my enh shammy suffered -3k DPS lost overall on raids.

**Comment by Jaffar1989** [comment]
Bump

**Comment by gogenks** [comment]
bump

**Comment by Tetuz** [comment]
Bump, just tested it a bit and confronted with simcraft simulation (just the flat damage part, couldn't see if it was changed by ap/mastery procs). Anyway can confirm what op's saying, my damage (386 ilvl) is between 0,4k and 2,2k (on 331 hits) while simmed one is between 3,3k and 6,6k. 
Sorry about huge pics, don't know how to resize them, they show simcraft results and stats, with in-game tests and current stats.
![cattura3](https://user-images.githubusercontent.com/26360436/27985421-0d6f5320-63eb-11e7-83c1-90815a318790.PNG)
![cattura4](https://user-images.githubusercontent.com/26360436/27985423-0ec566a6-63eb-11e7-8f81-37ea2818ab6c.PNG)
![wowscrnshot_070817_141726](https://user-images.githubusercontent.com/26360436/27985427-1c632898-63eb-11e7-8fc7-22536952da22.jpg)
![wowscrnshot_070817_141732](https://user-images.githubusercontent.com/26360436/27985428-1db773c0-63eb-11e7-9f35-a6211fdc6c9f.jpg)

**Comment by Jaffar1989** [comment]
Jeśli juz zamknełes dubla   Piklo ([Shaman] [Spell] Flametongue weapon damage #9390 ), to moze dało by rade chciaz oznaczyc ten bug jako  klasowy shamanaa ? wisi to jzu od grudnia 2016 , nikt z ekipy atlantissa nie raczył sie tym zajac, a shamanow ench na serwerze przez to jest na lekarstwo, mainy graczy  zmieniły talenty na resto badz ele , a alta w enhu nie spotkasz :P prosty powod robi za mały dmg i na razie wyglada na to ze macie to gdzies głeboko ..... , bo nikt sie na ten temat nie wypowiada z ekipy atlantissa :P

**Comment by Piklo** [comment]
samo danie labeli nie sprawi, że nagle się ktoś tym zainteresuje + aktualnie są inne priorytety. wczoraj dałem labele dla 150 postów i po prostu do tego nie doszedłem, wszystko w swoim czasie

**Comment by Jaffar1989** [comment]
Wiem ze głównym celem devow jest oskryptowanie DS, ale tez nie wolno zapominać o graczach którzy teraz graja bo morze wyjść na to ze nie będzie komu progresować tego DS. Poł roku czekać na label  buga to za 2 lata będziemy mieli naprawiony, ale przynajmniej coś się ruszyło w tej materii :P

**Comment by Piklo** [comment]
Sorry for random polish talks

> Pół roku czekać na label buga

To czy post ma label czy nie, nie ma kompletnie znaczenia, labele są tylko do łatwiejszego szukania. 
Cele celami, ale nie każdy dev ma lata doświadczenia w cpp i naprawi Ci każdy bug. Każdy robi co może i tyle ile może, albo tyle na ile ma ochotę.

Jak dalej masz ochotę się wymieniać argumentami jak powinno coś wyglądać to zapraszam na pw, albo do sekcji sugestie na forum jak wstanie, bo póki co robimy tu nie potrzebny spam.

**Comment by Tetuz** [comment]
I found some other formulas for flametongue damage and it should be for 4.3.4 http://forum.warmane.com/showthread.php?t=228239 hope the link isn't a problem. Anyway i did some try at rag hc today, and assuming a damage like the ones from world of logs (took one recount from patch 4.2 at rag 10hc and one from patch 4.3 at morchok 10n where damage from spells were like mine) and by doing some math on last try's recount i calculated a total damage lost of around 800k on the whole fight. From logs i took an average ft damage of 3,5k for normal hits and 5,5k for crits, then used something like (number_of_hits*(3,5k-avg_dmg_noncrit)+number_of_crits*(5,5k-avg_dmg_crit)), resulting in (231*(3500-998)+55*(5500-1508))= 799832. Numbers shown in screen below.
![wowscrnshot_080717_003210](https://user-images.githubusercontent.com/26360436/29007673-9655170e-7b08-11e7-88f1-b12bdec98171.jpg)
Maybe this isn't the only bug that affects enhancement, but it will surely help to give them less embarassing performances. Btw, there's something that we need to provide to confirm this bug?

**Comment by lamaATS** [comment]
Fixed in rev. 5477
