### ISSUE TITLE
[EN][Spell][Hunter] [Rapid Fire]

### ISSUE THREAD

**Issue by MangeNerfedOwl** [Atlantiss/BugTracker#8746]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: While poping any dps cooldown in game like recklessness, wings, ivy veins, vendetta, deadly calm, arcane power etc. you don't get global cooldown, but when you pop Rapid Fire on hunter then you do get gCD.

**Current behaviour**: Rapid Fire causes global cooldown.

**Expected behaviour**: Rapid Fire should not cause global cooldown.

**Steps to reproduce the problem**:

1. Log on hunter
2. Cast Rapid Fire
3. Look on your skills or try to use them straight away.

**Revision**: 5269

**Comment by Jenovas** [comment]
Proof that it should cause GCD?

**Comment by MangeNerfedOwl** [comment]
Well i thought it's obvious while it's the only burst cd with gCD but ok here you have a video https://www.youtube.com/watch?v=nGiivnU5Ghc (i chose MM spec guide because we can see using Rapid Fire twice due to Readiness)
First RF - 1:57 - As you can see hunter in video pops RF at the beggining and there's no any gCD on other skills
Second RF after Readiness - 2:12 - Here hunter resets his RF, uses that again and there was not any delay between using RF and casting next Aimed shot, he could use it straight away.

**Comment by Jamishman** [comment]
Unless something was just broken, RF does not have a GCD. You need to be out of a GCD to use it, but it does not cause one. You can use any ability right after you use it.

**Comment by Jenovas** [comment]
Just checked. Rapid Fire does not cause GCD.
Closing.
