### ISSUE TITLE
[EN][NPC] last chest in culling of stratholme doesnt open after defeating mal'ganis

### ISSUE THREAD

**Issue by scidrov** [Atlantiss/BugTracker#8748]
Description**: Describe the problem
after defeating mal'ganis in culling of stratholme the chest cant be opnd
Current behaviour**: What happens
chest cant be opnd
Expected behaviour**: What should happen instead
the chest should be able to be open after mal'ganis finishing his dialogue and dissapearing
Steps to reproduce the problem**:

1. go culling of stratholme
2. complete the dungeon
3. last chest cant be opened

Revision**: Current server version
rev. 5275

here is proof http://imgur.com/a/zVovB

**Comment by Piklo** [comment]
#5052

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14181-9067-8748-5052-malganis-loot-tables/
