### ISSUE TITLE
[EN][Item] Darkmoon Card: Tsunami

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#8752]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: This trinket procs on every time any spell heals any target.

**Current behaviour**: It gives a stack of Giant Wave (the spirit buff from trinket) every time a healing spell heals any target.

**Expected behaviour**: It shouldn't have a 100% chance to grant a stack of Giant Wave every time it heals a target.

**Steps to reproduce the problem**:

1. Equip Tsunami trinket
2. Cast any healing spell
3. Watch it proc from any healing spell

Link to trinket:
http://cata.openwow.com/item=62050

**Revision**: 5275

**Comment by Jenovas** [comment]
I did some research (reading both wowhead and mmo champions) and players claim that it has a 100% chance to proc. For example priests claim that casting one coh/poh gives you instant 5 stacks.
Closing.

**Comment by Fearyourself** [comment]
Hmm. It seems like there's some kind of internal cooldown on this trinket, but I can't find anything of how long it should be. IF the procc chance is 100% which I highly doubt, then there's no doubt an ICD on the trinket.

Also, when people say "100% uptime", it means that it's easily held at 5 stacks when raiding, not that it proccs on every spell. I'll do some more research because I do remember that it wouldn't go to 5 stacks on 5 secs of lifebloom.

**Comment by Jenovas** [comment]
Fearyourself - on the begining of Cata the trinket didnt proc from HoTs and had a 10sec ICD. After I think 4.0.3 the ICD got removed and HoTs started stacking the trinket. You can find many comments on mmo and wowhead that after the buff priests need 1 CoH/PoH cast, Druids need 1 Wild Growth to have the trinket stack in 1-2 secs

"Also, when people say "100% uptime", it means that it's easily held at 5 stacks when raiding," - no they dont mean that, they added logs showing that they had a 98% Uptime of the 5 stack buff. So lets say a battle lasts around 6mins, that is 360secs so it took them 7secs to stack the trinket to 5 stacks, so probably the first AoE cast they did into the battle.

Also some proof from retail servers
[19:33:39.640] Persephøne gains Giant Wave from Persephøne
[19:33:40.859] Persephøne gains Giant Wave (2) from Persephøne
[19:33:42.859] Persephøne gains Giant Wave (3) from Persephøne 
[19:33:42.875] Persephøne gains Giant Wave (4) from Persephøne
[19:33:44.062] Persephøne gains Giant Wave (5) from Persephøne
[19:33:46.078] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:47.265] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:48.859] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:48.875] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:48.875] Persephøne's Giant Wave is refreshed by Persephøne (Beacon)
[19:33:49.265] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:49.671] Persephøne's Giant Wave is refreshed by Persephøne
[19:33:49.671] Persephøne's Giant Wave is refreshed by Persephøne (Beacon)
The Log show a proc every 1, 2, 3 secs (probably cast / HoT ticks).

Another post:
Disc Priest Perspective:
Prayer of Healing: 5 stacks
Binding Heal: 2 stacks

Getting more than 1 stack per cast would probably be proof that the spell doesnt have a cooldown and has a 100% proc rate.
