### ISSUE TITLE
[EN][Spell][Shaman] Grounding Totem Glyphed

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#8753]
**Description**: Describe the problem
Grounding totem with reflect glyph is bugged
Travel time spells dont consume the totem gets reflected but stays still up.
Non travel spells like living bomb poly dont reflect but consumes it.

**Current behaviour**: What happens
When you cast any traveling dmging spell Like pyroblast it reflects pyro but the totem doesnt get consumed by it.Also when u cast non traveling spells like polymorph it consumes it but doesnt reflect poly.

**Expected behaviour**: What should happen instead
The grounding with glyph to reflect should reflect a dmg incoming traveling spell and get consumed,also for polymorph should reflect poly and get consumed.
**Steps to reproduce the problem**:

1. Drop grounding with glyph to reflect
2. Cast any traveling spell ull notice that it reflects it but doesnt get consumed
3. Cast polymorph consumes it but doesnt reflect back the poly effect.

**Revision**: Current server version
5275

**Comment by Jenovas** [comment]
Is this a new bug that showed up after my latest update to Grounding Totem? Or was it like this before?

**Comment by Zhalox123** [comment]
Ye its after the fixes I think didnt rly try the grounding reflect after the fix but probably is.

**Comment by Zhalox123** [comment]
Jenova also spell reflection of warrior http://www.wowhead.com/spell=23920/spell-reflection
Same problem if you cast spells that travel on it he can reflect as many times as he wants until shield reflect is up but for instant spell non traveling gets instant removed.

**Comment by Jenovas** [comment]
fixed in rev 5278
