### ISSUE TITLE
Frost elemental not attacking when set on assist.

### ISSUE THREAD

**Issue by Aezerk** [Atlantiss/BugTracker#8754]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Whenever my frost mage attacks anything the frost elemental won't attack it will just run to a random spot and stay there unless i order it to attack a target. The frost element is set to follow me and assist and should be attacking whatever i attack. 
**Current behaviour**: What happens
Once i attack a target frost elemental runs to a random location. 
**Expected behaviour**: What should happen instead
Should start casting its frostbolt on the target i am currently attacking.
**Steps to reproduce the problem**:

1. Summon water elemental
2. Attack a mob. 
3. Watch the water elemental run to a random location.

**Revision**: Current server version
Cataclysm patch 4.3.4

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links
