### ISSUE TITLE
The character is stunned

### ISSUE THREAD

**Issue by sines051** [Atlantiss/BugTracker#8755]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The initial chain of quests the Worgen after I had to bite,I reviewed the video and nothing happened,I remained in the same place which took this quest,then I ran to the place where they should be chained to pesona,I ran I turned into a Worgen and the past is allegedly in fetters,cannot digitise,and to pass the quest you need to be in chains,and the character is 2 meters away from the NPC
**Current behaviour**: What happens

**Expected behaviour**: The character is stunned and cannot move and perform any actions

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links
