### ISSUE TITLE
[EN][Talent ][MAGE] Arcane Concentration / Clearcasting

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8762]
**Description**: 
Clearcasting from Arcane Concentration seems to have a 15 sec icd before u can get another Clearcasting

**Current behaviour**:
after u gain Clearcasting u wont get another until  15 sec pass, (which is the duration of the cleacrast buff u get)

**Expected behaviour**:
with 3 talent points in Arcane Concentration u should have a 10% chance to get a clearcast every time a spell does damage , that counts: direct dmg, dot dmg, and chanaled spell tics dmg,

http://wowwiki.wikia.com/wiki/Arcane_Concentration
Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards 

https://www.engadget.com/2010/11/20/arcane-brilliance-arcane-mage-cataclysm-talent-analysis/
This is and always has been a core part of the base arcane build. With mana management being so completely integral to arcane mage DPS, any talent that helps conserve mana becomes that much more valuable. The 10% proc rate on this talent gives you a free spellcast with surprising frequency, and the longer your mana pool can stay right of center, the better your DPS will be. This is no longer a mana talent, it's a straight-up DPS talent.

**Steps to reproduce the problem**:

https://www.youtube.com/watch?v=CJrn5LIOi2A

1. do dmg
2. watch for clearcast
3. count sec betwen procs
4. enrage

**Revision**: 5277

**Comment by blinkmaster** [comment]
https://us.battle.net/forums/en/wow/topic/1922568849

"it is 40% chance on 15 seconds internal cooldown, which is supposedly averaging to 10%, this is the same for all specs. it was changed so you would have CC procs on a more even basis rather than back to back. this also links up with LB up time, so with a bit of luck you can have some nice free LB casts."

**Comment by stanq87** [comment]
dude , show me that 15 seconds internal cooldown in change log

**Comment by Jenovas** [comment]
From the blizzard DBC Files for patch 4.3.4 (the files that can be found in every client).

ID - 12575 Arcane Concentration (Rank 3)
Description: Gives you a $s1% chance of entering a Clearcasting state after any damage spell hits a target.  The Clearcasting state reduces the mana cost of your next damage spell by $/10;12536s1%.
Proc flag 0x00015550, **chance = 40**, charges - 0
Trigger spell (12536) Clearcasting. **Chance = 40**

**Comment by stanq87** [comment]
the only  mention in the change log about clearcasting on mage is about a nerf with arcane miisles, and Jenovas, a see a 40 cahnce but wheere di u see anything about a 15sec icd ?

**Comment by stanq87** [comment]
http://cata-shoot.tauri.hu/?spell=12536
http://cata-shoot.tauri.hu/?spell=12575

**Comment by Jenovas** [comment]
Stanq87 I dont care what the changelog says. Blizzard tooltips never were accurate. Hundreds of spells work differently than what the tooltip says. Blizzard tends to keep it clear - in the tooltip we show 10% chance, but for real its a 40% chance with an ICD that makes it look like 10%, this makes sure the user doesnt get 10 procs one after another and makes sure that almost every 15 secs there is a proc where with RNG you could go a full minute without a proc with a base 10% chance. This is how Blizzard did it and EoT. Both retail players and various websites talk about this and the DBC files prove this.

**Comment by stanq87** [comment]
Jenovas, i dont care that u dont care what the changelog says, DBC files prove the 40% chance not  theICD durration or its existance, and as far as official sources go the only mechanics in clear casting are those fro arcane mages with their arcane missles procs, that not every missle from  arcane missles gets a proc chance, so

**Comment by Jenovas** [comment]
I found 3 different topics on retail forums speaking about 15s. thats enough for me. As I said EoT. Wont be coming back to this topic.

**Comment by fluessig** [comment]
http://wow.gamepedia.com/Arcane_Concentration
Cataclysm Patch 4.0.3a (2010-11-23): Now has a much higher chance (13/27/40%) of entering a Clearcasting state. This effect cannot occur more than once every 15 seconds. The tooltip still states that there is a 3/6/10% chance, as it averages out to approximately the same chance with the internal cooldown applied.
