### ISSUE TITLE
Crossroads Caravan Escorted

### ISSUE THREAD

**Issue by madzkull** [Atlantiss/BugTracker#8763]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
you cannot talk to Rocco Whipshank
**Current behaviour**: What happens
when you select him he doesn't pop up his dialogue 
**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use

**Comment by TranceAccount** [comment]
#3718

**Comment by graham79** [comment]
The problem with this quest still remains, quest npc does not have working gossip. So after accepting the quest there is no way to trigger the script. (if such a script exists).
method of fix, select * from gossip_menu_option where menu_id=10528;  and check entry has correct values in option_id and npc_option_npcflags fields. If npc has gossip_menu_id then gossip will show on clicking him.
