### ISSUE TITLE
[EN][Firelands] Ragnaros ciritcal hits

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8766]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Fatality: Name> 71.4k Melee (Critical) [Ragnaros]

**Description**: Ragnaros hit critical

**Current behaviour**: Ragnaros Hit Critical

**Expected behaviour**: To be honest, I don't know, but since when Bosses hit critical?
And if Bosses / Ragnaros specially suppost to hit Critical,
The question i must ask is.. -> What the critical chance that bosses / Ragnaros have?

**Steps to reproduce the problem**:

1. fight rag
2. 
3. 

**Revision**: 5281

**Comment by sunshitwowsucks** [comment]
fucking noob just stack more mastery

**Comment by Fabiana-B** [comment]
This is a question or an issue(?)

**Comment by Aldergar** [comment]
Well if you don't have the talent that reduces the crit chance from bosses,then ofc you get critted.

**Comment by Illusie** [comment]
@sunshitwowsucks our tank tried something new vs Rag hc to increase dps.
@Aldergar The talent give 6% crit reduction (if im right) look the questions I been asked over the Issue.
@Fabiana-B actually it both. question and issue.
the first was - if bosses suppost to crit? (if no - than it should get fix.)
the second was - if yes, what their(bosses) crit chance?

I tried to search in google for "wow bosses crit chance / ragnaros melee crit chance".
found nothing.

so look at that as an issue and also as an question.
Thank you.

**Comment by sunshitwowsucks** [comment]
bosses can not crit with abilities but they can with melee

**Comment by Aldergar** [comment]
The talent prevents bosses to crit the tank,if you don't put the talent,then the boss will rape your tank.

**Comment by Illusie** [comment]
@sunshitwowsucks 
@Aldergar 

Ok? so bosses are able to crit on melee attacks...that weird to me.
I know normal mobs can crit. But bosses able to crit too? lol...
(I Did some research and found nothing about bosses critical hits)

By the way, you both completely ignored the 2nd question.
The question was: What the crit chance bosses have? 5%? 6%? 50%? 20%? 15%? what the crit chance?

(Again, I did  researchs and found nothing about Bosses critical chance)

As I said before, we know the Talent, we are not stupid. The talent give 6% crit reduction.
You missunderstand totaly why I'm even opened that issue ;d

**Comment by Aldergar** [comment]
http://www.wowhead.com/forums&topic=17116/do-npcs-crit

**Comment by Aldergar** [comment]
https://us.battle.net/forums/en/wow/topic/10490929355

**Comment by Aldergar** [comment]
You can see that boss crit chance is probably around 5/6%,and without talent, you get critted

**Comment by Illusie** [comment]
@Aldergar Well, yeah nevermind >.<' as I said earlier we tried something new on Ragnaros hc. and we got crit on Tank it was like "lol", than the tank had to switchback his talents xD...

Yes the NPCs / Bosses crit chance is probably 6% after reading all Tanks abilities
all provide 6% crit reduction, so probably 5-6% is the crit chance, and the talents completly cancel the crit to appear ^^..

http://cata.openwow.com/spell=29594
http://cata.openwow.com/spell=50371
http://cata.openwow.com/spell=84629
http://cata.openwow.com/spell=16931

issue can be locked.
