### ISSUE TITLE
[en][item][spell][mage] Dragonwrath, Tarecgosa's Rest bugs Hot Streak

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8769]
**Description**: proc from staf consumes  instat hot steak proc, 

**Current behaviour**: it consumes the proc from hot steak

**Expected behaviour**:  the pyro from the staf (that is already a instatn extra  pyro) should not use the  hotsteak buff from talent

**Steps to reproduce the problem**:

1.  spam pyroblast, or fireball pyro combos or what ever
2.  look for proc from hotsteak that disapears before u pres the pyro button but theres is stil a pyro flying without u presing the pyro button

http://cata-shoot.tauri.hu/?spell=48108
http://cata-shoot.tauri.hu/?item=71086

**Revision**: 5281

**Comment by blinkmaster** [comment]
Its not a bug. Do some research next time.
