### ISSUE TITLE
NPCs/Banks/etc nothing visible

### ISSUE THREAD

**Issue by Saintcronus** [Atlantiss/BugTracker#8771]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Can not view any NPC/or interactive items with one of my characters

**Current behaviour**: What happens
Only affects one of my characters (Coolidge) on the Dragonwrath realm. I was playing last night, and my game seem to freeze. So I restarted. When I joined the game the quest NPC was not there. I then went to the nearby town and no npcs were there. I teleported to a capital city and not a single npc was viewable and the guild banks were gone. I signed in with another character and could view everything as normal.

**Expected behaviour**: What should happen instead
I should be able to see NPCs with my character, Coolidge (level 78 mage)

**Steps to reproduce the problem**:

1. Log in with Coolidge
2. Look for NPCs
3. 

**Revision**: Current server version
WoW: Cataclysm, Atlantiss server Dragonwrath

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

in game ticket or abandon your quests, maybe quest changed your phase

**Comment by Saintcronus** [comment]
I was on a "mounted quest" (King's revenge or something like that in Zul'Drak when my game crashed yesterday). 

I typed in ".s in" and I see the following:
"ACore rev. 5821 hash 63734dfacee1 2017-01-06 17:06:31 +0100 (anticheat branch) (Unix, RelWithDebInfo) Online players: 1522 (max: 1898) Active Connections: 1582 (max: 1946) Queued connections: 0 (max: 0) Server uptime: 22 hour(s) 6 Minute(s) 49 Second(s). Update time diff: 51. Average time diff: 51.

**Comment by Piklo** [comment]
"**rev. 5821**"

**Comment by Saintcronus** [comment]
OK, 

Ive dropped what I would have assumed would have been the trouble quests, still not clearing anything. Thoughts?

Thanks for the quick responses by the way!

**Comment by Piklo** [comment]
You tried to die? sometimes helps

**Comment by Saintcronus** [comment]
That worked!!!

Thank you!
