### ISSUE TITLE
[EN][Pet-bug][Frostmage] Pet doesn't scale with resi and other issues

### ISSUE THREAD

**Issue by Martibis** [Atlantiss/BugTracker#8772]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Frostmage pet doesn't scale with resilience and doesn't attack when target is LoS (and more). These are huge issues in PvP.

**Current behaviour**: What happens

**Expected behaviour**: Pet should scale with resilence, should look for target if LoS

**Steps to reproduce the problem**:

1. Let pet scale with resilence and let pet look for target if the target is LoS

**Revision**: Current server version

**Comment by Jenovas** [comment]
Pets scale properly with Resilience. Please atleast do tests before reporting.
Closing.
