### ISSUE TITLE
[EN][Spell][Priest][Mind Control]

### ISSUE THREAD

**Issue by Soulywood** [Atlantiss/BugTracker#8774]
Mind control keep you in combat even after 8 seconds. It should put players out of combat after 5.5 seconds. 

Important bug for rogues/ferals because they can't restealth after getting mind controlled.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
you can see current server revision by typing ".s in" in chat

**Comment by TranceAccount** [comment]
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use

- Create a new issue following the issue template.

Thanks in advance.
