### ISSUE TITLE
[PL][Quest][Northrend][Lupus Pupus]

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#8775]
Gdy podchodzę do wilka od razu znika i nie da sie wykonac Questa 
tak powinien wyglądać Quest
https://www.youtube.com/watch?v=BBt5omqHwgY

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) albo [cata.openwow.com](http://cata.openwow.com/) linki

użyj [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
możesz zobaczyć aktualny server revision wpisując ".s in" w czacie w grze

**Comment by krecik88** [comment]
fixed in 5289
