### ISSUE TITLE
[EN][Quest][Azshara] Easy is Boring

### ISSUE THREAD

**Issue by Yoghurt4C** [Atlantiss/BugTracker#8778]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest doesn't count as ready to turn in when it has to

**Link**: http://www.wowhead.com/quest=14390/easy-is-boring

**Current behaviour**: Nothing happens after the last dialogue option is picked when talking to Azuregos (in video format: https://my.mixtape.moe/xnnfdv.webm )

**Expected behaviour**: Quest should be marked for turn-in after the last dialogue option is picked

**Steps to reproduce the problem**:

1. Accept "Easy is Boring"
2. Go through the dialogue with Azuregos

**Revision**: 5281

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by BAndysc** [comment]
Will be fixed in the next revision. Thanks for reporting
