### ISSUE TITLE
[EN] [Quest] [Hillsbrad Foothills]

### ISSUE THREAD

**Issue by androohdooh** [Atlantiss/BugTracker#8779]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: NPC Kingslayer Orkus missing.

**Current behaviour**: Quest leads to find Kingslayer Orkus (http://www.wowhead.com/npc=47443/kingslayer-orkus) however NPC is not present.

**Expected behaviour**: NPC should be present in water next to pier at Ruins of Southshore.

**Steps to reproduce the problem**:

1. Start quest 'Can you smell what the lok' tar is cooking' (http://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking).

Noted that issue was deemed fixed twice previously and temporary NPC was made on pier. However currently NPC can not be located.

**Revision**: 4.3.4. rev. 5281

**Comment by BAndysc** [comment]
He is present, have you finished quest http://www.wowhead.com/quest=28096/welcome-to-the-machine?

**Comment by androohdooh** [comment]
Yes,
Currently at his apparent position. Have attempted to reset quest twice. Still not present.
Quest marker in water, but no NPC in or next to pier.

**Comment by BAndysc** [comment]
Strange, I do not know who has deleted his from database. Will be fixed in the next rev
