### ISSUE TITLE
[EN]You do not mee the requiments

### ISSUE THREAD

**Issue by indu575** [Atlantiss/BugTracker#8780]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Whenever i try to que in DF for rhc with 356 itemlvl im getting the issue.
**Current behaviour**: What happens
Can´t que for rhc
**Expected behaviour**: What should happen instead
Working que
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version
4.3.4

**Comment by coba999** [comment]
Screenshot of RCH queue window

**Comment by indu575** [comment]
![wowscrnshot_011217_003751](https://cloud.githubusercontent.com/assets/23377422/21870957/766e9c90-d85f-11e6-9647-eb25a3328096.jpg)

**Comment by Fabiana-B** [comment]
Do you check if you're locked in all heroic dungeons?

**Comment by Batranelu** [comment]
He's definitely locked in all heroic dungeons..

**Comment by indu575** [comment]
This might be the problem. I was locked on all hc yesterday. If you are locked in every single dungeon, you can do shit?

**Comment by rschinkoeth** [comment]
actually this is NOT expected behaviour. on live servers if you were locked to all instances you couldnt queue specific anymore, but RANDOM heroic ignored instance locks.
