### ISSUE TITLE
[EN][SPELL][PROFESSION]Coarse Grinding Stone

### ISSUE THREAD

**Issue by gejewski** [Atlantiss/BugTracker#8781]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens
Making Coarse Grinding Stone does not level up your profession/
**Expected behaviour**: What should happen instead
Making
![wowscrnshot_011117_222001](https://cloud.githubusercontent.com/assets/25066293/21867410/57801a72-d84e-11e6-965f-cec3a6f0e024.jpg)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by coba999** [comment]
Go to Mining Trainer.

**Comment by gejewski** [comment]
Oh my god i feel so stupid I completely forgot about that.
