### ISSUE TITLE
[EN] [Quest] [Shadowmoon Valley] Neltharaku's tale 

### ISSUE THREAD

**Issue by Sharpxz** [Atlantiss/BugTracker#8782]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Reading Neltharaku's tale does not complete the quest.

**Current behaviour**: After reading tale, Neltharaku turns away, "?"mark remains silver-colored.

**Expected behaviour**: After taking quest and reading Neltharaku's tale you should be able to complete quest.

**Steps to reproduce the problem**:

1. Take quest
2. Read the tale
3. Try to complete quest after reading.

**Revision**: 5281

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

you can see current server revision by typing ".s in" in chat

**Comment by Sharpxz** [comment]
@Piklo ty for commment (first time using this to report an error)

**Comment by Sharpxz** [comment]
Works as intended after server restart.
