### ISSUE TITLE
[EN][Quest][Bloodmyst Isle] What We Don't Know...

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8783]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: the quest [What We Don't Know...](http://www.wowhead.com/quest=9756/what-we-dont-know) is not working.

**Current behaviour**: it is impossible to interract with [Captured Sunhawk Agent](http://www.wowhead.com/npc=17824/captured-sunhawk-agent). Dialog window is empty.

**Expected behaviour**: interraction  with [Captured Sunhawk Agent](http://www.wowhead.com/npc=17824/captured-sunhawk-agent) must provide dialog window with option to continue the quest.

**Steps to reproduce the problem**:

1. Take the quest [What We Don't Know...](http://www.wowhead.com/quest=9756/what-we-dont-know).
2. Talk to [Captured Sunhawk Agent](http://www.wowhead.com/npc=17824/captured-sunhawk-agent)
3. You see empty dialog window.

**Revision**: 5281

![wowscrnshot_011217_193510](https://cloud.githubusercontent.com/assets/15231821/21900822/edc9255a-d8fd-11e6-855e-116b99c056fc.jpg)

**Comment by krecik88** [comment]
Working as should, on quest accept you receive aura, which transform you into blood elf, then you go to the npc and talk to him, if you go to far away to another area, aura is canceled, you need to retake the quest.
