### ISSUE TITLE
[EN][NPC][(Big Zokk Torquewrench) I think he's Glitched HELP :)

### ISSUE THREAD

**Issue by Tombuscus** [Atlantiss/BugTracker#8784]
So! I wanted to do some Transmog on my Swords so I searched up some good Alliance Transmog Gear and then it took me too Big Zokk Torquewrench in Area 52. So I clicked on him but nothing happened? I tried everything I could to get access to the Goblin but sadly it didn't open :( Please Fix this

**Comment by Piklo** [comment]
#8254

**Comment by krecik88** [comment]
duplicate
