### ISSUE TITLE
[en][QUEST]Through a Glass, Darkly

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8785]
**Description**: cant enter instance

**Current behaviour**: when u try to enter instance u get teleported somewhere else

**Expected behaviour**: u should be afle to enter instance and meet the npc and follow her around killing ads and a boss at the end

**Steps to reproduce the problem**:

1.  go get the quest  Through a Glass, Darkly  http://cata-shoot.tauri.hu/?quest=29194
2. try enter the instance 
3. se what happens

3 other ppl seme to have the same issue

**Revision**: 5281

**Comment by BAndysc** [comment]
Fixed now
