### ISSUE TITLE
[EN][QUEST][Sholazar Basin] Rejek: First Blood

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8786]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: the quest [Rejek: First Blood](http://www.wowhead.com/quest=12734/rejek-first-blood) doesn't working.

**Current behaviour**: Using of [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade#comments) doesn't count quest progress.

**Expected behaviour**: Using of [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade#comments) should count quest progress.

**Steps to reproduce the problem**:

1. Take quest [Rejek: First Blood](http://www.wowhead.com/quest=12734/rejek-first-blood)
2. Use [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade#comments)
3. Quest progress doesn't count.

**Revision**: 5281

![wowscrnshot_011317_102158](https://cloud.githubusercontent.com/assets/15231821/21922933/f1ad77bc-d979-11e6-8e2d-32aa5d819aa4.jpg)

**Comment by Fabiana-B** [comment]
Kill another Sapphire, or check if u was in a raid group.

Last day I got that quest was... 3 days ago(?), and for me works perfectly.

**Comment by Fabiana-B** [comment]
Ok, editing... today, doing the quest, sword doesn't work on the creatures.

bump.

**Comment by BAndysc** [comment]
rev 5286

**Comment by jissabraham** [comment]
still dont work

**Comment by Lebiedz** [comment]
I've tried to do this quest today and couldn't get any credit either on apes or wasps. Haven't tried oracles after these two.

**Comment by jissabraham** [comment]
I did the quest today, the bug here is you have to be in male rang during u kill it like on top of it and use the sword not on range kill.

**Comment by sfgjhurtyu** [comment]
Today I tried to this quest and none of the three required target validate the quest.
I'm not in raid group. Abandon and re-take the quest also doesn't make it work.

Any update ?

**Comment by jissabraham** [comment]
kiss it and kill it ul be able to do it
