### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] What Illidan Wants, Illidan Gets... 

### ISSUE THREAD

**Issue by Moonsie** [Atlantiss/BugTracker#8788]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When i talk to the NPCRuusk while wearing the provided item http://www.wowhead.com/item=30639/blood-elf-disguise i should get credit when im finished with the dialogue options it provides, instead i get no credit and cant turn in the quest no matter how many times i try it.

**Current behaviour**: Nothing i get no quest credit at all.

**Expected behaviour**: When i finish the dialogue options i should get the credit for the quest and be able to turn it back in to  http://www.wowhead.com/npc=21293/borak-son-of-oronok from who i got the quest.

**Steps to reproduce the problem**:

1. Take http://www.wowhead.com/quest=10577/what-illidan-wants-illidan-gets from http://www.wowhead.com/npc=21293/borak-son-of-oronok
2. Use http://www.wowhead.com/item=30639/blood-elf-disguise  upon entering the required zone
3.  Talk to the NPC Ruusk

**Revision**: Current server version

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by krecik88** [comment]
Working as intended, there was small update after your issue. Try now
