### ISSUE TITLE
[EN][Quest][Eastern Plaguelands]Beat it Out of Them

### ISSUE THREAD

**Issue by Yoghurt4C** [Atlantiss/BugTracker#8790]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
**Link**: http://www.wowhead.com/quest=27522/beat-it-out-of-them

**Description**: 2 out of the 3 objectives aren't being marked as completed

**Current behaviour**: "Discover" objectives aren't getting completed when the quest mobs die. After 2 hours of grinding the necessary quest mobs, both of the objectives are 0/1. On retail the mobs have one-liners that sometimes trigger upon being attacked/provoked - this isn't crucial, but it's also not present.

**Expected behaviour**: When a mob reaches low hp/dies, both of the objectives should be marked as completed one after another?

**Steps to reproduce the problem**:

1. Accept quest, go to the quest area
2. Grind skeletons

**Revision**: 5281

**Comment by BAndysc** [comment]
Fixed in 5285
