### ISSUE TITLE
[EN][Quest][Southern Barrens] Desolation Hold Inspection

### ISSUE THREAD

**Issue by szentigrad3** [Atlantiss/BugTracker#8793]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Can't Complete Quest

**Current behaviour**: Take ride no completion

**Expected behaviour**: Once arrived at Desolation Hold Quest should complete and dismount

**Steps to reproduce the problem**:

1. Talked to npc 
2.  Ride the wolf to Desolation Hold
3. The Quest did not complete and the wolf just sat there, had to relog

**Revision**: 5281

http://www.wowhead.com/quest=24577/desolation-hold-inspection

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

you can see current server revision by typing ".s in" in chat

**Comment by szentigrad3** [comment]
updated

**Comment by BAndysc** [comment]
The wolf doesn't disappear, but it can be completed. It shouldn't be automatically completed, you have to talk to the npc.
