### ISSUE TITLE
[EN][Quest][Hyjal] Those bears up there

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#8796]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Quest link: http://cata.openwow.com/quest=29161

**Description**: When you're in the top of the tree you can't climb down unless you use ALT+F4.

**Current behaviour**: You remain stuck on the top of the tree.

**Expected behaviour**: You should be able to climb down.

**Steps to reproduce the problem**:

1. Take a bear
2. Go on top of the tree
3. Try to climb down

**Revision**: 5287

Edit: this doesn't bug on all trees , only some of them.

**Comment by krecik88** [comment]
fixed
