### ISSUE TITLE
Righteous-Sermon Quest on Wintergarde Keep

### ISSUE THREAD

**Issue by Megalodonti** [Atlantiss/BugTracker#8799]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Hello there. I would like to report a problem i have while being on this quest  [A Righteous Sermon].
**Current behaviour**: when i accept the above quest the npc vanishes in the wall. The name of my Hero is Megalodonti alliance druid 73 level!

**Expected behaviour**: the npc named inquisitor Hallard, should start the spell of exorcism on the Goul 
**Steps to reproduce the problem**:

1. http://www.wowhead.com/quest=12321/a-righteous-sermon
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by krecik88** [comment]
add wowhead links, fix title, you've got perfect template how to do it while creating new issue

**Comment by Aldergar** [comment]
Still not the correct title and wrong format
