### ISSUE TITLE
 Death Knight Black front fortress out not to go

### ISSUE THREAD

**Issue by hefengzhuan** [Atlantiss/BugTracker#8801]
![qq 20170116181638](https://cloud.githubusercontent.com/assets/25157739/21996099/83e715c2-dc20-11e6-9ac7-db100acb1366.png)
![qq 20170116181819](https://cloud.githubusercontent.com/assets/25157739/21996108/882801aa-dc20-11e6-8a3e-882883a4a688.png)

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Death Knight Black front fortress out not to go

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. Death Knight Black front fortress out not to go
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links, title, revision

**Comment by xmesaj2** [comment]
You're better of sending a ticket instead bugtracker report.
[How to submit a ticket](http://atlantiss.eu/pages/14)

**Comment by lazyracer** [comment]
It looks like not fully downloaded client. 
Sometimes when you change client language(and from screenshot it is seen so) - it starts to download **everything** from zero, even textures and models. 

However i can be mistaken.

**Comment by Batranelu** [comment]
This is were you should of been , I've done the quest myself 2-3 days ago with my DK so it works. You shouldn't of been up there in the first place, you probably thinked that you must go UP to Highlord Darion but you should of stayed down and start the war with him to Light of Dawn.
Here's a guide for your quest : https://www.youtube.com/watch?v=8ekrr2JZfZM
