### ISSUE TITLE
[EN][PL][Item] Variable Pulse Lightning Capacitor icd

### ISSUE THREAD

**Issue by bijtankga** [Atlantiss/BugTracker#8802]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

[EN]
**Description**: Variable Pulse Ligtning Capacitor descritpion tell that each crit spell dmg give us 1 stack of Electrical Charge with chance for consume this stacks for Lightning Bolt (dmg depends on ammount of stacks). But this effect cannot occure more than 1 time per 2,5s.

**Current behaviour**: We can get stack of Electrical Charge more often than 2,5s.
For example on firelands shaman ele earned 600+ stacks but 120 with lower interval than 2,5s 

**Expected behaviour**: This trinket should have 2,5s cd

**Steps to reproduce the problem**:
1. Equip this trink
2. Attack something using spell with cast lower than 2,5s (faster is better)
3. Check interval between spells

[PL]
**Description**: Z opisu trinketu Variable Pulse Lightning Capacitor wynika ze z "kazdym" krytycznym magicznym atakiem stackuje buffa (Electrical Charge) i ma szanse na zuzycie zebranych stackow na Lightning Bolt (dmg zalezny od ilosci stackow). Gdzie ilsoc stackow nei moze przekroczyc 10 i nie mozna ich dostac czesciej niż 2,5s.

Link norm: http://cata.openwow.com/item=68925
Link heroic: http://cata.openwow.com/item=69110

**Current behaviour**: Zdarza się że trinket uruchamia się częściej niż 2,5s (przykladowo u shamana na firelandach na ponad 600 prockow 120 z hakiem bylo ponizej 2,5s)

**Expected behaviour**: Efekt trinku powinien mieć wewnetrzny cd wynoszący 2,5s
Nie znalazłem danych... forumowych ale takze nie znalazlem zadnych logow z globa (przejrzalem kilkunastu uzytykownikow tego trinka na firelandach) ktore by zawierala proca ponizej 2,5s

**Steps to reproduce the problem**:

1. Zalozyc tego trinka
2. Zaczac cos atakowac czarami o cascie ponizej 2,5s (im szybsze tym lepsze)
3. Obserwowac czas miedzy procami

**Revision**: 5292

**Comment by BialyADI** [comment]
Nadal bugnięte?

**Comment by blinkmaster** [comment]
its fixed, can be closed
@wtRCH
