### ISSUE TITLE
[EN][Quest][Darkshore] Consumed

### ISSUE THREAD

**Issue by tfmertz** [Atlantiss/BugTracker#8805]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Investigate water hole isn't completing when finding the Devouring Artifact

**Current behaviour**: Player can swim all around pond with Devouring Artifact without quest completion.

**Expected behaviour**: Player should complete the "Watering Hole Investigated" portion of the quest when entering the pond with the Devouring Artifact

**Steps to reproduce the problem**:

1. Be alliance character
2. Go to Kathrena Winterwisp in Darkshore
3. Accept Consumed
4. Walk to water hole (45.1, 79.2 according to wowhead)

**Revision**: ACore rev. 5288

**Comment by krecik88** [comment]
ive just tested quest, you can finish it by just killing bears

**Comment by Khangu** [comment]
"Watering Hole Investigated" portion can be completed only after bears are killed. Sometimes it even auto-complete after bears without entering the pond at all. Something is bugged there but quest still can be done.

**Comment by Traxis** [comment]
I can't complete it even after killing the bears :/

**Comment by BAndysc** [comment]
Fixed in 5299 (bears have to be killed first)
