### ISSUE TITLE
[EN][NPC] Ichoron

### ISSUE THREAD

**Issue by heartlesshound** [Atlantiss/BugTracker#8806]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Here is a link to Ichoron - http://www.wowhead.com/npc=29313/ichoron
He's unkillable!

**Current behaviour**: What happens
His phase begin to work, he comes up the water pool, starts attacking, disappears and spawns a load of mini water elementals. This is what should happen (I think). After the third or fourth time of him spawning his mini water elementals he come's back but in his dead form with only one hp and is unattackable, not even with non targeted aoe's. He does however continue to attack. If everyone ports out and back in again via the DF, once back in the room he is back to his normal place (post spawn but pre attack) with full HP but completely unattackable.

**Expected behaviour**: What should happen instead
I suspect he should be killable.

**Steps to reproduce the problem**:
Go there and try and kill him I guess ...
1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Aldergar** [comment]
It's because you deal too much damage to him,try to not hit him at all while he is up.
