### ISSUE TITLE
[PL][Quest] The Zandalari Menace

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#881]
http://www.wowhead.com/quest=29157
Brak tego q . Został on dodany w patchu 4.1 i po ukończeniu chaina otrzymujemy  http://www.wowhead.com/item=68833

A także brak npc w tym chainie m.in http://www.wowhead.com/npc=53081 http://www.wowhead.com/npc=52374

Jak powinno wyglądać https://www.youtube.com/watch?v=6iPX2NCZd9c

**Comment by Misiac** [comment]
Zul'Gurub zostało wprowadzone wiec przydałby się i chain :P
