### ISSUE TITLE
[PL][Quest][Thousand Needles] Get Zherin!

### ISSUE THREAD

**Issue by secu312** [Atlantiss/BugTracker#8810]
**Description**:  W queście należy udać sie do moba Trackmaster Zherin, pobić go i zabrać przedmiot. Niestety nic się nie dzieje podczas walki z nim i mob umiera.

**Current behaviour**: Podczas walki mob umiera

**Expected behaviour**: Mob w pewnym momencie walki powinien dostac stuna i powinien wyświetlic sie napis "Trackmaster Zherin is stunned. Steal the Horde's Proposal now"

**Steps to reproduce the problem**:

1.  Dojść do moba
2.  Walczyc z nim 

**Revision**: 5292

http://www.wowhead.com/quest=25756/get-zherin
https://www.youtube.com/watch?v=jn10QVBHoOQ
https://www.youtube.com/watch?v=g4Au1oXZasw
http://wow.gamepedia.com/Quest:Get_Zherin!

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) albo [cata.openwow.com](http://cata.openwow.com/) linki

**Comment by secu312** [comment]
Dodam, że gdyby nie ten quest to Loremaster Kalimdoru byłby wykonalny po stronie Alliance, bo reszta krain działa, a wątpie, żeby po tym było więcej niedziałających w Thousand Needles

**Comment by virushm** [comment]
quest not work

**Comment by BAndysc** [comment]
Fixed in 5299
