### ISSUE TITLE
[PL][Quest][Dustwallow Marsh] The Deserters

### ISSUE THREAD

**Issue by karolnpc** [Atlantiss/BugTracker#8811]
Description: Należy udać się do wrogiego npc Balos Jacken, zbić go do około 20 % po czym npc powinien stać się przyjazny. Następnie powinniśmy oddać mu quest. 

Current behaviour: Npc Balos Jacken cały czas jest nam wrogi nie ważne ile hp aktualnie posiada.

Expected behaviour: Npc Balos Jacken powinien stać się przyjazny po zbiciu mu hp do ok 20 %. 

Steps to reproduce the problem:
1.Wziąć quest The deserters
2.Zawalczyć z npc Balos Jacken i zbić mu hp do ok 20 %
3.Oddać quest npc Balos Jacken

Revision: 5292

Linki: 
Quest - http://cata.openwow.com/quest=27287
Npc Balos Jacken - http://www.wowhead.com/npc=5089/balos-jacken
Film: https://www.youtube.com/watch?v=8Z00VtyVq54

**Comment by karolnpc** [comment]
Bump

**Comment by BAndysc** [comment]
Fixed in 5299
