### ISSUE TITLE
[EN][Quest][Eastern Plaguelands]Beat it Out of Them

### ISSUE THREAD

**Issue by duzda** [Atlantiss/BugTracker#8812]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Link**: http://www.wowhead.com/quest=27522/beat-it-out-of-them

**Description**: Can't attack "Scourge Siege Engineer"

**Current behaviour**: I can't attack "Scourge Siege Engineer", which is necessary to complete the quest. Whenever i try to attact it, it says: "Invalid target".

**Expected behaviour**: I should be able to kill the mobs.

**Steps to reproduce the problem**:

1. Go to quest area
2. Try to attack "Scourge Siege Engineer"

**Revision**: 5292

**Comment by BAndysc** [comment]
Fixed in 5299
