### ISSUE TITLE
[EN][Spell][Class] Focus Fire

### ISSUE THREAD

**Issue by arigox** [Atlantiss/BugTracker#8813]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Focus Fire does not show it's visual on the screen (three yellow arrows from both sides in the center of the screen) when it reaches five stacks

**Current behaviour**: When the ability reaches five stacks, the icon on the action bar light up, but the visual that appears in the center of your screen does not show

**Expected behaviour**: After five stacks, the icon should light up (already working) and the visual indicator should show (not working)

**Steps to reproduce the problem**:

1. Doing DPS untill you reach five stacks

**Revision**:  5292

**Comment by Batranelu** [comment]
Works for me http://imgur.com/a/Gj2N5

**Comment by arigox** [comment]
That's crazy! I guess I'll hit up some GMs to see what's up with my character. Thank you for letting me know. I'll close the issue.
