### ISSUE TITLE
[EN][Npc] NPCs bugged in Area52 in Netherstorm (Outland)

### ISSUE THREAD

**Issue by Tombuscus** [Atlantiss/BugTracker#8815]
Hello I would like to Request if its possible to Please fix the Vendors which sell some good Replica Items in Area52 in Netherstorm (Outland) because they sadly DO NOT WORK!
They can not be open! So that way, characters that use those kind of gear can not have the epics for level 60 (and also the vanilla WoW replicas which would make Characters look good for Transmog) 

This is the Vendor = http://www.wowhead.com/npc=23396/krixel-pinchwhistle
Please Fix this if Possible and Thank you for taking the time to read this
:)

**Comment by Bildo** [comment]
duplicate
