### ISSUE TITLE
[EN][NPC][Shadowfang Keep] Stone Sleeper

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8816]
http://wow.gamepedia.com/Stone_Sleeper
http://www.wowhead.com/npc=3870/stone-sleeper
http://www.wowhead.com/shadowfang-keep
http://wow.gamepedia.com/Shadowfang_Keep

**Description**: of 8 mobs 3 dont dont leave their stone form but the still walk after u fear u and malle dmg u

**Current behaviour**:  above
**Expected behaviour**: the should leave they  stone form and be killable liek the rest
**Steps to reproduce the problem**: go there and  pull them

**Revision**: 5292

**Comment by Prodiege** [comment]
To explain some more. There are 2 packs with 4 stone sleepers each. When activated, 2 stone sleepers in each pack are not attackable, but attack you.

Everything was working correctly a couple of revisions ago, but now it does not.

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links

**Comment by stanq87** [comment]
Myivo u have 2 wowhea link right there  did y even read anything ?

**Comment by stanq87** [comment]
https://github.com/Atlantiss/BugTracker/issues/8847
