### ISSUE TITLE
[EN][Crafting] Vicious Pyrium Boots

### ISSUE THREAD

**Issue by rdoherty0** [Atlantiss/BugTracker#8818]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
When crafting Vicious Pyrium Boots, I instead receive Bloodthirsty Pyrium Boots.

**Current behaviour**: What happens
Craft Vicious Pyrium Boots using Blackmithing 515, materials Elementium Bar x 12, Volatile Fire x 10.  I receive Bloodthirsty Pyrium Boots instead, which are measurably worse (50 strength less).

http://www.wowhead.com/item=75120/vicious-pyrium-boots
http://www.wowhead.com/item=70005/bloodthirsty-pyrium-boots

**Expected behaviour**: What should happen instead
I should receive the Vicious Pyrium Boots I crafted.

**Steps to reproduce the problem**:

1. Have Blacksmithing 515 and mats
2. Craft Vicious Pyrium Boots
3. Receive the wrong item, Bloodthirsty Pyrium Boots

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
rev 5292

**Comment by therealpadthai** [comment]
Vicious blue crafted gear are not available until dragon soul is released

**Comment by rdoherty0** [comment]
I purchased the recepie for the Vicious Boots from the Vendor in Twilight Highlands and learned it just fine.  It lists as craftable in the profressions maneu, and crafting uses up all the mats, it just produces the wrong gear.  If it's not supposed to be available, it shouldn't be available from the vendor.  If I'm not supposed to be able to craft it, it should not use up the (hard to farm) mats.

**Comment by whatisthisthing** [comment]
This is the current behavior of all crafted PvP items. I believe the only exception is jewelry (ring/neck). I also believe this is intended for the state of the server.

**Comment by Piklo** [comment]
you won't be able to craft 377 ilvl pvp items before dragon soul, the recipe is fine, post can be closed

**Comment by rdoherty0** [comment]
This is confusing, there is definitely a bug here.  See screen shots: #1 and #2 are what the Blacksmithing shows will be crafted, #3 is what results from the crafting - an item of lesser quality.  Perhaps the crafting recipe is wrong, or is available in error from the vendor.  There was no PvP involved, only a straight vendor purchase.

![vicious1](https://cloud.githubusercontent.com/assets/20824803/22158817/fb3dad64-def2-11e6-9302-3d5d0738c2ab.JPG)
![vicious2](https://cloud.githubusercontent.com/assets/20824803/22158818/fb3f3044-def2-11e6-92b0-213ebf1b8907.JPG)
![vicious3](https://cloud.githubusercontent.com/assets/20824803/22158819/fb3f4caa-def2-11e6-8b3f-3ba45f915b4f.JPG)

**Comment by TranceAccount** [comment]
It will be fixed when 4.3 hits.
