### ISSUE TITLE
[PL][Instance-Cata] Zul'Aman

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#882]
# Trash
* [Amani'shi Flame Caster](http://www.wowhead.com/npc=23596#abilities): [Conflagration](http://www.wowhead.com/spell=42220http://www.wowhead.com/spell=4222) mob castuje to nawet jeśli jest w cc lub nie jest w combacie z targetem. W dodatku ten debuff pokazuje się jako buff 

# [Jan'alai](http://www.wowhead.com/npc=23578#abilities)

* [Flame Breath](http://www.wowhead.com/spell=97497) dostajemy debuff nawet jeśli staliśmy za bossem podczas castowania [Flame Breath](http://www.wowhead.com/spell=43140). Za duży zasięg?
* [Amani Dragonhawk Hatchling ](http://www.wowhead.com/npc=23598) - [Flame Buffet](http://www.wowhead.com/spell=16168) Każdy debuff pokazuje się osobno zamiast się stackować

# [Hex Lord Malacrass](http://www.wowhead.com/npc=24239/hex-lord-malacrass)
UPDATE 28.12.2014 rev 4170
* https://github.com/Atlantiss/BugTracker/issues/362
* [Wind Shear](http://www.wowhead.com/spell=57994/wind-shear) podobno nie przerywa mu castów

**Comment by NONLIFE** [comment]
Zandalari Juggernaut przed bossem Jan'alai buguje sie na petach i dalej bije jak jest martwy

**Comment by qubuslabadz** [comment]
"Wind Shear podobno nie przerywa mu castów"

Działa.

"Zandalari Juggernaut przed bossem Jan'alai buguje sie na petach i dalej bije jak jest martwy"

Globalny bug, zgłosić najlepiej "npc zwiększający sobie HP w chwili śmierci buguje się"

Reszta fixed in rev. 4297.
