### ISSUE TITLE
[EN][QUEST][Stonetalon Mountain]To be Horde...

### ISSUE THREAD

**Issue by holdias** [Atlantiss/BugTracker#8820]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest To be Horde... in Stonetalon Mountain (http://www.wowhead.com/quest=26115/to-be-horde) doesn't work.

**Current behaviour**: After you take the quest nothing happens.

**Expected behaviour**: Inmediatly after accepting the quest a scene should be triggered where Overlord Krom'gar is punished by Garrosh.

**Steps to reproduce the problem**:

1. Take the quest from the npc.
2. Wait for something to happen.
3. Keep waiting 'til the end of times for something to happen.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/8231
