### ISSUE TITLE
[en][Quest][Winterspring]'Borrowing' from the Winterfall

### ISSUE THREAD

**Issue by Niaseer** [Atlantiss/BugTracker#8825]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The meat from the smoker stacks are counting towards the quest A Cub's Cravings instead of the intended quest 'Borrowing' From the Winterfall.

**Current behaviour**: What happens
When you use the smoked meat that you obtain from the smoker stacks the smoked meat counts as Shardtooth Meat (for the daily quest A Cub's Cravings) instead of Smoked Meat as such you can't complete the quest

**Expected behaviour**: What should happen instead
When you use the Smoked Meat it should counts towards the quest 'Borrowing' From the Winterfall 

**Steps to reproduce the problem**:

1. Get the daily quest 'Borrowing' From the Winterfall from the Winterspring cub
2. Get the daily quest A Cub's Cravings
3. Obtain some smoked meat form the smoker stacks in the winterfall camp
4. Use the Smoked Meat (right click it)

**Revision**: ACore rev. 5292 hash. 09643da2048c

**Comment by Piklo** [comment]
#8646
