### ISSUE TITLE
[EN][Npc][Quest Giving] 

### ISSUE THREAD

**Issue by nathielka** [Atlantiss/BugTracker#8826]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
NPC Sedai's Corpse in Hellfire Peninsula should give you quest Return to Obadei (http://www.wowhead.com/quest=9423/return-to-obadei), after you complete the previous one, In Search of Sedai (http://www.wowhead.com/quest=9390/in-search-of-sedai).
**Current behaviour**: What happens
After you turn in the quest, nothing happens.
**Expected behaviour**: What should happen instead
The Sedai's Corpse NPC should give you the next quest in chain.
**Steps to reproduce the problem**:

1. complete the 1st quest
2. get another one
3. profit (get the Loremaster)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links
