### ISSUE TITLE
[EN][Quest][Cape of Stranglethorn] Let's See What You've Got, Zanzil

### ISSUE THREAD

**Issue by DarkestDuck** [Atlantiss/BugTracker#8827]
**Description**: During the quest you need to talk to Orgus but he is untalkable.
[http://www.wowhead.com/quest=26534/lets-see-what-youve-got-zanzil](http://www.wowhead.com/quest=26534/lets-see-what-youve-got-zanzil)
[http://www.wowhead.com/npc=43204/orgus](http://www.wowhead.com/npc=43204/orgus)

**Current behaviour**: Quest could not been finished because you can not fulfill its objective - talk with Orgus.

**Expected behaviour**: Orgus should have option to talk "Want to try some of Jasper's Jungle Cooler?" like Gmurgl and Captain Bartholomew Softbeard have.

**Steps to reproduce the problem**:

1. Take quest.
2. Go to the tower where prisoners are kept.
3. Try to talk to Orgus.

**Revision**: 5294

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by DarkestDuck** [comment]
Links added

**Comment by BAndysc** [comment]
Works in 5304
