### ISSUE TITLE
[EN][NPC] Skarr

### ISSUE THREAD

**Issue by pwnrip** [Atlantiss/BugTracker#8829]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Does Skarr spawn at al? if yes in what phase and where exactly?

At the moment I am in the beginning phase of questing in Molten Front and looking for Skarr 3 times a day (I know where he spawned on retail, so I am not looking at the wrong spot, also reference wowhead.com for this). Sadly enough, Skarr has never been found by me. A friend of mine said that he saw him spawn once. However, when he logged on his hunter to tame him, he couldn't find him, because his hunter was in a different (questing) phase in Molten Front. 

Currently, I can not find any info on Skarr and therefore I am not questing further in Molten Front, because maybe Skarr is spawning in the first phase and if I do quest further I can f up my chance to get him.

**Current behaviour**: Skarr spawns only in 1 phase (?)

**Expected behaviour**: Skarr spawns in every phase 

**Steps to reproduce the problem**:

1. ?
2. ?
3. ?

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

ACore rev. 5294 hash. d5103a9496b2 2017-01-20 21:03:36 +0100 (4.3.4 branch) (Unix RelWithDebInfo)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by Sayris9876** [comment]
I saw it today after completing http://www.wowhead.com/quest=29206/into-the-fire 
Saw it behind the cliff from where you kill the pyrelord and drop down into the molten flow he was walking around that part. So not sure if phasing should have anything to do with it but it does spawn at least in that phase.

**Comment by pwnrip** [comment]
Found and tamed him in that part!
After doing that quest you get 2 additional quests in the volcano (http://www.wowhead.com/npc=52444/thisalee-crow#starts) and after completing Fire FLower you have to deliver to Choluna (http://www.wowhead.com/npc=52492/choluna#ends). At this point I spotted skarr on one of the floating platforms (he sometimes falls through it). 

Tip for taming: Have max range and know after which fireball he is going to cast "Fierocast Barrage". Go MM and Silencing Shot that fireball and tame him. (the silence fierocast barrage and detterence+tame doesnt work somehow)
