### ISSUE TITLE
[EN][Quest][Tol Barad] Magnets, How do they Work?

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#8832]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest worked before but bugged after a few restarts.

**Current behaviour**: Magnets no longer respawn (ever) when using quest item.

**Expected behaviour**: Magnets should appear for you to loot them.

**Steps to reproduce the problem**:

1.  Take quest
2. Go to area on map
3.  Use quest item

**Revision**: 5295

Quest link: http://www.wowhead.com/quest=28692/magnets-how-do-they-work

**Comment by BAndysc** [comment]
Fixed in 5316
