### ISSUE TITLE
[EN][NPC][Stonecore] Ozruk

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#8834]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: His hitbox is very small , I have to stack with him to actually hit it.

**Current behaviour**:  Hitbox very small

**Expected behaviour**: Hitbox should be bigger

**Steps to reproduce the problem**:

1.  Start the fight
2.  Try to hit him (meele dps )
3.  

**Revision**: 5294
Boss : http://www.wowhead.com/npc=42188/ozruk

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/13378-8631-8834-beauty-and-ozruk-hitbox/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
