### ISSUE TITLE
[EN][QUEST][THEMAELSTROM] Deepholm, Realm of Earth

### ISSUE THREAD

**Issue by Satanisagoddess** [Atlantiss/BugTracker#8835]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
While I was on the mount for this quest a Random Dungeon que popped. I clicked join not knowing that once I finished the dungeon I'd come back out off the mount and at the bottom of Maelstrom. So I hearthed out thinking I could just try again which was not the case. Thus also causing an issue with my quest tracker.

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead
I get to Deepholm and do starter quests.

**Steps to reproduce the problem**:

1. Start quest, jump on mount
2. Join random dungeon que in flight
3. End up at the bottom of Maelstrom

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
#5446 #3104 #645
