### ISSUE TITLE
[EN][Quest][Deepholm] Therazane's Throne Daily Quests

### ISSUE THREAD

**Issue by mohaghegh1** [Atlantiss/BugTracker#8836]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Therazane's Throne Daily Quests

**Current behaviour**: They Are Not Friendly NPC And I Cant Complete My Daily Quests

**Expected behaviour**: They Should Be A Friendly NPC To Take Quests . 

**Steps to reproduce the problem**:

1. Take Quest.
2. Complete Quest .
3. NPC's At Therazane Area Should Get Quests . Like Every Normal Quests .

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by Batranelu** [comment]
You have selected At War with them , press U, go to Therazane and uncheck "At War"
