### ISSUE TITLE
[EN][Glyph][warlock] Glyph of shadowflame

### ISSUE THREAD

**Issue by chazz100** [Atlantiss/BugTracker#8840]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
What steps will reproduce the problem?
Get a warlock.
Learn Shadowflame ability. (http://cata.openwow.com/spell=47897 )
Get a Glyph of Shadowflame and learn it. ( http://cata.openwow.com/spell=63310)
Get a  class who can dispel/remove Magic debuff.
Warlock cast Shadowflame for the other character.
Dispell it 
What is the expected output?
When the Shadowflame dot dispelled, should also disappear the slowing effect.
What do you see instead?
The slowing effect stays on the caracter, because is not a Magic debuff and not linked to the dot.
"is not dispellable itself and lasts as long as Shadowflame BUT it will go away if the Shadowflame DoT is dispelled (tested, confirmed).
Thus, it neither adds more dispel protection nor is it unremovable."
Proof:https://www.youtube.com/watch?v=KVWz-poEoHk&t=419s (min6:50)

**Comment by brokenshard** [comment]
+1

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
