### ISSUE TITLE
[EN][QUEST][Dragonblight][Steamtank Surprise]

### ISSUE THREAD

**Issue by nathielka** [Atlantiss/BugTracker#8843]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
steamtank vehicles cannot be used/mouted, thus cannot be completed Veteran of the Wrathgate achievment.
http://www.wowhead.com/quest=12326/steamtank-surprise
**Current behaviour**: What happens
nothing happens.
**Expected behaviour**: What should happen instead
steamtanks should be useable and ou can do the quest.
**Steps to reproduce the problem**:

1. steamtanks cannot be used
2. quest cannot be completed
3. achievment cannot be achieved

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links
