### ISSUE TITLE
[EN][QUEST][Zul'Drak] Foundation for Revenge

### ISSUE THREAD

**Issue by Nozmolar** [Atlantiss/BugTracker#8845]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Unable to complete quest. Thus, unable to play through Zul'drak's major quest line. 
**Current behaviour**: What happens
Killing Quetz'lun Worshippers or Serpent-Touched Berserkers near the soul fonts does not award quest credit at all.
**Expected behaviour**: What should happen instead
Killing Quetz'lun Worshippers or Serpent-Touched Berserkers near the soul fonts should award quest credit ("Trolls killed near a Soul Font..."
**Steps to reproduce the problem**:
1. Start the chain questline by looting "Strange Mojo" quest item dropped from trolls at "Altar of Sseratus", and accept the quest.
2. Following the quest line, you will eventually accept "Foundation for Revenge" quest from "Quetz'lun's Spirit" at the Altar of Quetz'lun while having "Ghostly" buff (...soul-self is in the deathly underworld of Quetz'lun.).
3. Try killing Quetz'lun Worshippers or Serpent-Touched Berserkers near the soul fonts.
4. Cry.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5294 hash. d5103a9496b2 2017-01-20 21:03:36 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**References:**
A) wowhead link: http://www.wowhead.com/quest=12668/foundation-for-revenge
B) Quest Chain according to wowhead comments:
          1. Strange Mojo
          2. Precious Elemental Fluids
          3. Mushroom Mixer
          4. Too Much of a Good Thing
          5. To the Witch Doctor
          6. Breaking Through Jin'Alai
          7. To Speak With Har'koa
          8. But First My Offspring
          9. Spirit of Rhunok 
          10. My Prophet, My Enemy 
          11. An End to the Suffering 
          12. Back to Har'koa 
          13. I Sense a Disturbance 
          14. Preparations for the Underworld 
          15. Seek the Wind Serpent Goddess 
          16. Setting the Stage 
          **17. Foundation for Revenge**
          18. Hell Hath a Fury 
          19. One Last Thing 
          20. Blood of a Dead God 
          21. You Reap What You Sow
          22. The Key of Warlord Zol'Maz
          23. Rampage
          24. The Gods Have Spoken
          25. Convocation at Zol'Heb
          26. Unfinished Business
          27. Gal'darah Must Pay

**Comment by xmesaj2** [comment]
rev. 5403 fixed
