### ISSUE TITLE
[EN][NPC][Deadmines] Oaf Lackey

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#8846]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The NPC ability ( Axe to the Head ) is doing 25k / tick , and there are 2 mobs at entrance, both of them will put that ability on you and you take 50k / tick. 

**Current behaviour**: The damage is huge.

**Expected behaviour**: Less damage since there are so many ticks and ability can stack.

**Steps to reproduce the problem**:

1.  Go to Deadmines at second boss
2.  Aggro the mobs at the entrance or the one in the room.
3. 

**Revision**: 5294
NPC: http://www.wowhead.com/npc=48445/oaf-lackey
Ability: http://www.wowhead.com/spell=90098/axe-to-the-head

**Comment by Prodiege** [comment]
I don't see any proof. These always hit hard on retail. You usually had to CC the 2nd one. Please provide evidence

**Comment by whatisthisthing** [comment]
Just a read through the wow-head comment section:

(Patch 4.0.3)		
These guys throw axes that do a ton of damage while hitting tanks really hard.

(Patch 4.0.3)		
Their bleed ability called Axe to the Head deals A LOT of damage. Do your healer a favor and try to mitigate as much damage as possible by using defensive cooldowns or remove the bleed with Stoneform, Divine Shield, Ice Block, etc.



It looks like it was nerfed in MoP though

(Patch 5.1.0)		
You'd think... really, truly... that this would inflict much more damage than it actually does.

**Comment by Prodiege** [comment]
Here is some actual proof: https://m.youtube.com/watch?v=8eWPQgz432w

Start at 8:00

He explains how they hit like trucks and then explains how he got ticked for 25k by the bleed. You can even see it in his scrolling combat text. 

Myivo I am disappointed in you. Saying this is confirmed when OP gave no proof and you yourself obviously didnt do any research. Shame
