### ISSUE TITLE
[EN][NPC][Shadowfang Keep] Gargoyles

### ISSUE THREAD

**Issue by Batranelu** [Atlantiss/BugTracker#8847]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Half of the gargoyles can't be attacked, aggroed, CC'ed and sometimes will follow and kill you even after you released.

**Current behaviour**: Bugged

**Expected behaviour**: All of them should be able to die

**Steps to reproduce the problem**:

1. Go to dungeon
2. Aggro them
3. 

**Revision**: 5294
Dungeon : http://www.wowhead.com/shadowfang-keep

**Comment by sebastian-luczak** [comment]
Can confirm this bug, Gargoyle is untargetable/unkillable, can't be hit with any of AoE spells, follows you till the moment you die, leading to wipe.

**Comment by stanq87** [comment]
https://github.com/Atlantiss/BugTracker/issues/8816

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14063-8847-shadowfang-keep-gargoyles/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved

**Comment by Dranerys** [comment]
Still bugged

**Comment by TranceAccount** [comment]
http://www.wowhead.com/npc=3870/stone-sleeper

**Comment by TranceAccount** [comment]
Doesn't work Piklo since our AI sets it to not_selectable.

**Comment by Piklo** [comment]
i know

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14764-88479326-shadowfang-keep-gargoyles/

**Comment by Jenovas** [comment]
Fix in rev 5539
