### ISSUE TITLE
[EN][Talent ][MAGE][Ignite] Ignite damage.

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8849]
**Description**:
a debuf applied by a crit, it makes 40% dmg of that crit in 2 tics

**Current behaviour**:
data after 10m spam:
++++++++++++++++++++
pyroblast:

avg crit amount after 10m spam	44744
avg ignite	13318

avg ignite tick should be 8948,8
47% difrence beetween theory and actual, minus 32% from mastery makes a 15% difrence

++++++++++++++++++++
fireball:

avg crit	35724
avg ignite	11177

avg ignite tick should be 7144,8
56% difrence beetween theory and actual, minus 32% from mastery makes a 24% difrence

**Expected behaviour**:
ignite tic  = (crit dmg x 0.4) : 2

Talent
http://cata-shoot.tauri.hu/?spell=12846
http://cata.openwow.com/spell=12846
http://www.wowhead.com/spell=12846

debuff:
http://cata-shoot.tauri.hu/?spell=12654
http://cata.openwow.com/spell=12654
http://www.wowhead.com/spell=12654

http://wow.gamepedia.com/Patch_4.0.1_(class_changes)
http://wow.gamepedia.com/Mastery:_Ignite

**Steps to reproduce the problem**:

1. spam fireall or pyro
2. check ignites dmg 

**Revision**: 5294

**Comment by sigmundfreud2016** [comment]
It's actually harder than it seems:
http://www.wowhead.com/spell=12846/mastery-ignite#comments:id=1657349
> guatafu on 2012/07/31 (Patch 4.3.4)
No, and it's difficult to explain, lets say your current ignite is ticking for 1k, it has 1 tick remaining and you crit again, the new ignite is ticking for 1k as well; since you still had 1 tick remaining, your next ignite tick will be the sum of both, thus ticking for 2k, but the remaining ticks will be for the last spell only, thus ticking for 1k.

If you want to test it properly, avoid casting second spell before previous ignite expires.

**Comment by Jenovas** [comment]
Ignite is a more complicated mechanic than you think its not a basic 40% of all crits.
Closing.

**Comment by stanq87** [comment]
this is not about the ignite refreshing before 1 or 2 tic, its only about the values that are preatty straight foward,  the strange thing is that when i took this numbers into combustion calculation ive got what the theory  expected

**Comment by Jenovas** [comment]
"its only about the values that are preatty straight foward" - no its not. When you get two fast crits in a row you have something called ignite munching making the ignite value lower than it should be, when you hit a crit exactly at the moment of a tick you get ignite stacking / rolling which makes ignite stack higher than it should be. When you refresh ignite it changes into a 6sec DoT with 3 ticks.

**Comment by blinkmaster** [comment]
Not exactly. Ignite munching = 2 crits same time (pretty much) ignite occurs only from 1 crit, 2nd is consumed.
Ignite Rolling - 2 cRits happen pretty much exact time, ignite happens from both.
Ignite refresh to 6 sec only if 1st ignite duration is rolled after the tick. Stacking crits under 2 sec interval (ignite ticks) causes ignite Rolling with 4 sec duration and 2 ticks empowered with additional ignite stacked in it. 
This is how it should be. On our server munching can occur in 0-0.5 interval

**Comment by stanq87** [comment]
well , after i read what @sigmundfreud2016  wrote,  i cheked the ignites outside rotation, and there the difrences  between theory ant practice seem to be around  xx dmg per ignite tick, which is so small i wont bitch about that, but its there if u care to check :
a  mage with 29% mastery bonus to dots makes a 25608 crit that gives me  a 6634 tic of ignite, when it should give me 6607

and its not stackin its roling, staking was back when u could make ignite go to infinitive numbers: 

about staking: 
Your fireball hits the boss and applies a dot for 6 seconds.
Two seconds later, your second fireball hits the boss and applies a dot for 6 seconds.

For two seconds Ignite does damage equal to x% of one fireball. (After the first cast)
For four seconds Ignite does damage equal to x% of two fireballs. (After the second cast)
For two seconds Ignite does damage equal to x% of one fireball. (Six seconds after the first cast)

and ofcourse

When you score a critical strike when Ignite is up, it gets refreshed with a 6 seconds and a value per tick that should correspond to 40% of the damage of the critical strike you just scored plus whatever remained of the 40% of the damage of the spell that had caused Ignite in the first place. In that case, there is another game engine issue. When Ignite is up with 6 to 4 seconds remaining (which can only happen after Ignite was refreshed), any occurring critical strike will not further refresh Ignite and the 40% additional damage will not be dealt.
