### ISSUE TITLE
[EN][Quest][Dalaran] Waterlogged Recipe

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8852]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: quest [Waterlogged Recipe](http://www.wowhead.com/quest=14203/waterlogged-recipe) cannot be completed.

**Current behaviour**: End NPC [Christi Stockton](http://www.wowhead.com/npc=32337)  haven't quest dialog window to complete it.

**Expected behaviour**: you can talk with NPC about quest and get reward.

**Steps to reproduce the problem**:

1. Take the quest from item [Waterlogged Recipe](http://www.wowhead.com/quest=14203/waterlogged-recipe)
2. Try to complete it.

**Revision**: 5294

**Comment by Malanie** [comment]
still not working as of rev. 5340
http://www.wowhead.com/quest=14203/waterlogged-recipe

**Comment by Dranerys** [comment]
Bump

**Comment by podatekvat** [comment]
rev. 5418 and still isn't scripted.

**Comment by KieraHorde** [comment]
Hi guys. Any changes you're working on? I've stocked already three quest items...

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14533-waterlogged-recipe-quest-ender/
