### ISSUE TITLE
[EN][Talent][Warlock] Eradication + UA and Corruption

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#8855]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Link of the talent (rank 3) - http://cata.openwow.com/spell=47197
 The Warlock talent Eradication in Affliction tree affects dots, as if they scale with it as haste, but its not % haste, It is % casting speed = affects only casting of shadow bolt, UA and channeling spells such us drain soul and drain life.

**Current behaviour**: Currently the talent works as if its 20% haste, not 20% casting speed, wich leads to DOT spells Corruption and Unstable Affliction scaling with it.

**Expected behaviour**: Should work as a 20% casting speed increase = should affect casting speed + channeling spells only.

**Steps to reproduce the problem**:
0. For a easy result, get 2700-2800 unbuffed haste.
1. Cast Corruption or UA on Dummy , wait for all ticks to get off and count them.
2.  Proc Eradication 3/3
3.  Repeat (In my case i get 1 extra tick at the end due to faster ticking and reaching a new haste breakpoint of the dot)

**Revision**: 5294

PS. 1: In order to see the extra tick, you have to have a certain amout of haste prior, so together with the 20% added by the bug, the DOT can reach a haste breakpoint and get an extra tick. But thats not a must to confirm a bug, rather you can just notice that the ticks are ticking faster even without having high enough haste for extra tick to get added.

PS. 2: ! I want to stress again that this is a bug affecting Corruption + Unstable Affliction DOT spells ONLY. Drain Soul and Drain Life are DOT spells but they are channelled and they MUST be affected by Eradication. (Please dont mess up drain soul QQ)

**Comment by Jenovas** [comment]
Eradication should effect DoTs. Closing
https://cynwise.wordpress.com/2011/11/18/how-warlock-dots-work-in-cataclysm-part-ii-dot-refreshing-proc-stacking-and-getting-your-warlock-black-belt/

http://www.wowhead.com/forums&topic=166963&p=2265769

http://www.mmo-champion.com/threads/925434-Does-Eradication-talent-speed-up-Corruption-ticks
