### ISSUE TITLE
[EN][Quest][Northern Barrens] To the Mor'shan Rampart

### ISSUE THREAD

**Issue by tedkx** [Atlantiss/BugTracker#8856]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The objective of the quest [To the Mor'shan Rampart](http://www.wowhead.com/quest=28876/to-the-morshan-rampart) is to talk to to the NPC [Kadrak](http://www.wowhead.com/npc=8582/kadrak) at the northern part of the Norther Barrens. However the NPC is nowhere to be found.

**Current behaviour**: The quest ender [Kadrak](http://www.wowhead.com/npc=8582/kadrak) cannot be found. Kadrak is also the objective of [The Warchief's Command: Ashenvale](http://www.wowhead.com/quest=28493/warchiefs-command-ashenvale) which can neither be completed.

**Expected behaviour**: The [wowhead page](http://www.wowhead.com/npc=8582/kadrak) shows where Kadrak should be.

**Steps to reproduce the problem**:

1.  Pick up the quest [To the Mor'shan Rampart](http://www.wowhead.com/quest=28876/to-the-morshan-rampart). This is the second quest in a chain. Alternatively you can pick up [The Warchief's Command: Ashenvale](http://www.wowhead.com/quest=28493/warchiefs-command-ashenvale) from Orgrimmar.
2. Go to the Mor'shan Rampart on the northern part of Norther Barrens
3. Kadrak is nowhere to be found

**Revision**: 5294

**Comment by Batranelu** [comment]
From wowhead info should be 6 Kadrak in Northern Barrens and 39 in Ashenvale here u have the coordonates
http://www.wowhead.com/npc=34006/kadrak

**Comment by tedkx** [comment]
There is a Kadrak stationed in Splintertree Post in Ashenvale. He does not move and never reaches Mor'shan Ramparts. More importantly, there is no question mark above his head to turn in quests.

**Comment by BAndysc** [comment]
Cannot reproduce - there is Kadrak in Mor'shan Rampart

**Comment by tedkx** [comment]
A screenshot would help. A note about where you found him. Up on the tower? Down on the ground?. A server time maybe? Did you find him just after a server restart?
Because I've visited the place many times, including today, and I assure you, I shit you not: there is no Kadrak that I can see or target or complete quests at, neither in the Mor'shan Rampart nor on the road going to Splitertree Post.

We get it: it's a private server. There are lots of bugs. There are even more phasing issues that exist even in retail (and I think this issue is one of them). My understanding is that devs fix things on their free time and the only motivation is donations. We are grateful for your contributions. None of the issues I have submitted have been fixed. But I absolutely get it.

But when you finally make the time to investigate an issue that is documented in a comprehensive way with your predefined format, then I guess we deserve a little more than "Cannot reproduce - Checked off my list". You need more information? A screenshot? Anything extra, please tell so. But if you "cannot reproduce" then it's your problem and the ticket should not be closed.

**Comment by BAndysc** [comment]
I get your sarcasm. And devs do not get donations, money goes to maintain server and advertisement (possibly with the donations the motivation could be higher).

Screenshot one: http://imgur.com/a/H9X4U
Map: http://imgur.com/a/r3eid
Link to wowhead: http://www.wowhead.com/npc=8582/kadrak

Uptime: 8h, revision 5304. Anything else?

**Comment by tedkx** [comment]
It was no sarcasm. Apologies if my phrasing hinted that it was. I am sincerely grateful for the ability to play for free in a server with this high level of stability maintainer by people that have not obligation to do it whatsoever.

I still don't see him though. Probably a phasing issue. Anyway...

**Comment by BAndysc** [comment]
What is your ingame nick?

**Comment by tedkx** [comment]
Panoukla
