### ISSUE TITLE
[EN][NPC] Karkin

### ISSUE THREAD

**Issue by Miko1742** [Atlantiss/BugTracker#8857]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Karkin (rare hunter crab tame) appears to be untameable by hunters (he's green/friendly).
Magma Springs

I found out that Karkin appears to be untameable by hunters (he's green/friendly).
I tried to re-log, made sure that I have enough slots for tame, using /cast Tame Beast macro but nothing seems to work. In the other hand Skarr is working properly and they spawn in the same zone. 

![wth](https://cloud.githubusercontent.com/assets/25408299/22399958/e1450e7c-e5a8-11e6-8a93-dd9b639c2a21.jpg)

**Current behaviour**: He acts like friendly NPC, you cannot aggro him nor tame.
**Expected behaviour**: He should appear as unfriendly NPC (red) and hunters should be allowed to tame.

**Steps to reproduce the problem**:

1. ?
2. ?
3. ?

**Revision**: ACore rev. 5294 hash. d5103a9496b2 2017-01-20 21:03:36 +0100 (4.3.4 branch) (Unix RelWithDebInfo)

**Comment by Batranelu** [comment]
From wowhead information should be 4 Karkin in Molten Front so try to search for another here you have the link i found try to go to those coordonates.
http://www.wowhead.com/npc=50959/karkin

**Comment by Miko1742** [comment]
These three spawn places you're talking about are either Skarr or Karkin spawn places (they do share the same spot usually) and it's nowhere a solution to my problem. I don't quite get what do you mean by saying "should be 4 Karkin", are you trying to imply there are FOUR spots where this rare beast spawns? Or FOUR Karkin beasts wandering around? Well then, LOL.

**Comment by TranceAccount** [comment]
So the problem is that he isn't attackable?

**Comment by Miko1742** [comment]
@TranceAccount 
Yes, he is untargetable/appears friendly to my hunter. Other Molten Front rare (Skarr) is tameable w/o any problems, Karkin seems to be bugged.

**Comment by Miko1742** [comment]
# update
I've asked another hunter to come join me @ the molten front just to see if it's a bug or not. He wasn't phased yet in the molten front (like I am with daily quests, I'm just before Druids of the Talon chain, when you need to collect another 150 Marks of the World tree) so I assume it's a visual bug that happens when you finish the first chain quest. 
![karkin bug update](https://cloud.githubusercontent.com/assets/25408299/22624417/fdd6e258-eb7b-11e6-8081-768b8223e290.png)

Here's the general question - does he even spawn? ... I searched thru atlantiss's board but couldn't find a word about this rare crab. Still, Skarr spawns as usual.

**Comment by TranceAccount** [comment]
## Posted a fix on the forums.

**Comment by Miko1742** [comment]
@TranceAccount 
Can you post link to a thread where's a solution? I'd really appreciate this. Thanks.

**Comment by TranceAccount** [comment]
http://community.atlantiss.eu/index.php?/topic/13117-npc-karkin/

**Comment by Miko1742** [comment]
Awesome. Hope to see a live fix soon. Thank you.

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
