### ISSUE TITLE
[EN][Talent][Warrior][Deep Wounds]

### ISSUE THREAD

**Issue by brokenshard** [Atlantiss/BugTracker#8858]
Description: Deep Wounds damage is very low comapred to retail and other servers

Current Behaviour: Deep Wounds does 48% of the weapon's average damage http://imgur.com/a/AMUQV

Expected Behaviour: Deep Wounds is supposed to be doing 48% of the melee attack damage for example if my mortal strike hits for 40k it will do do around 19k over 6secs damage as this video shows https://www.youtube.com/watch?v=T0iEzpWLgOE deep wounds was doing 9k+ dmg where on atlantiss it does 3/4k max

Steps to reproduce the problem:
1. Take the deep wounds talent in the Arms spec
2.Go to any training dummy
3. Try to get as much crits as possible
4. Check Deep wounds damage from recount

Revision: 5294

**Comment by Batranelu** [comment]
48% * 40000 = 19200 , over 6 seconds that means 3200 / tick (second).

**Comment by brokenshard** [comment]
no i tried it i did a mortal strike crit for 26k deeps wounds did around 700 damage per tick in total 4182
http://imgur.com/a/vabh2

**Comment by bijtankga** [comment]
You wrote "Deep Wounds does 48% of the weapon's average damage"
WEAPON'S AVERAGE DAMAGE
not skill damage
propably stacking like rogue t12p2

little test
arms, str/ap ench/trinks
ap: 10667
weapon: 2,6s 1004-1865
damege in char info: 3283-4231
avg: 3757
avg on dummy: 2571 (115 hits)
deep wound ticks on dummy: 369

3757 * 0,48 ~ 1803
1803 / 6 ~ 300
300 * 1,3 = 390 (trauma)
revers
369 / 1,3 ~ 283
283 * 6 = 1698
1698 / 0,48 ~ 3537

369 / 1,3 ~ 283
283 * 6 ~ 1698
1698 / 3757 ~ 0,45

so there can be error in value 45% instead 48% or something 

about movie:
1:59 deep wounds icon pop up with strange dmg value (5646)
2:02 on start deep wounds on debuffs list
2:03 deep wound icon pop up with EXPECTED value (933)
so more than one skill have this icon on his ui / warrior

**Comment by Batranelu** [comment]
48% * 26000 = 12480 , over 6 second that means 2080 / tick so here you're right.

**Comment by sigmundfreud2016** [comment]
@brokenshard 
@Batranelu 
1) 48% of your **melee weapon's average damage**
it doesn't matter, which ability crits and how strong it was
2) It has similar mechanic as ignite, i.e. you get second crit before first DW expires => it stacks/rolls with previous one. You must wait 6 seconds after each crit to test it properly.

**Comment by Batranelu** [comment]
My bad ;D i didn't read it all, @bijtankga is right , but there was no rend applied so 30% bleed damage isn't applied also.

**Comment by bijtankga** [comment]
for my trauma apply with deep wounds

**Comment by brokenshard** [comment]
no the actualy tick is doing 29k dmg it just doesnt stack here on atlantiss or it doesnt stack properly

**Comment by brokenshard** [comment]
u can see on the far right side its only periodic dmg its started from 900 into 2400 into 16k cuz he kept on critting and it resetted it and once u crit deep wounds start ticking after 1sec or a bit less after the crit but he just went ham with reck and kept on stacking it its clearly bugged, i do a lot more dmg on other servers as arms warrior

**Comment by Jenovas** [comment]
No deep wounds isnt seriously bugged. It works almost as intended and the DMG is almost perfect.
We have logs from both our server Baleroc HC 25 and a warrior from Method doing Baleroc 25HC on retail and the average Deep Wounds tick is alsmot the same. There will be soon a small fix to deep wounds that will increase it's DMG by around 10-15% but that's it, Deep Wounds works as intended.

**Comment by Jenovas** [comment]
Fixed rev  5449
