### ISSUE TITLE
[EN][Kalecgos] Legendary staff chain

### ISSUE THREAD

**Issue by MarcoZornetta** [Atlantiss/BugTracker#8860]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
I'm on quest TIME GROWS SHORTLY, I collected all 1000 Seething Cinders but now, in Coldarra, I have no npc to talk.
**Current behaviour**: What happens
No NPC in Coldarra
**Expected behaviour**: What should happen instead
Kalecgos spawns near Nexus
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by stanq87** [comment]
abbandon q, cinders should not disapear ,  make ss before u do that, just in case , soo abbandon quest and look for this guy in this location http://cata-shoot.tauri.hu/?npc=53210 , and retake it,  sometimes watching the full cutscene helps, good luck

**Comment by TranceAccount** [comment]
Comment if still presists after doing what @stanq87 said.
