### ISSUE TITLE
[EN] I have problem which seams to be bugg in Death Knight's place

### ISSUE THREAD

**Issue by Rengky** [Atlantiss/BugTracker#8861]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise
![wowscrnshot_013017_165649](https://cloud.githubusercontent.com/assets/25434907/22427950/d14fdf86-e70d-11e6-84c1-7828040f445a.jpg)
![wowscrnshot_013017_165644](https://cloud.githubusercontent.com/assets/25434907/22427952/d153e8ba-e70d-11e6-804c-fc35e622a9e1.jpg)
![wowscrnshot_013017_165639](https://cloud.githubusercontent.com/assets/25434907/22427951/d1532d12-e70d-11e6-8e45-8dc46e26cac5.jpg)
![wowscrnshot_013017_165629](https://cloud.githubusercontent.com/assets/25434907/22427953/d1543fe0-e70d-11e6-8291-bc077f102aa3.jpg)

**Description**:  I get the last quest " The Light of Dawn " , i abanddoned it by mistake and i cannot take it back ( and it is a quest that has to be done one way or another ). I used hs to go back on Ebon Hold to search if i have to do something more to take it back, but when I got up there is nothing and noone on the Archerus except one friend of mine who did the same mistake with hearthstone and no way out.
Need your help please !!!!

**Current behaviour**: Im trapped in isolation.... 

**Expected behaviour**: There should be a way out go to back and take the quest again.

**Revision**: Current server version, is 4.3.4

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links, title, revision, ticket in game

**Comment by Batranelu** [comment]
Go down and search for Mograine maybe you can take the quest again from him.

**Comment by TranceAccount** [comment]
Make a ticket
