### ISSUE TITLE
[EN][Quest][Draenei] Learning the Word

### ISSUE THREAD

**Issue by AnimaFox** [Atlantiss/BugTracker#8862]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I'm having a trouble with the quest Learning the Word for Draenei Priest. I have to cast 5 times the Shadow Word: Pain in the Training Dummy, but the game doesn't register the hits. There are 3 dummies outside of Crash Site, they are out of the blue zone (Quest zone) and I don't know if it means something, but I can't do any progress with my Draenei priest. I've already search in the BugTracker and I've found nothing usefull.

**Current behaviour**: Doesn't register the hits in the dummy.

**Expected behaviour**: No hit will be registered.

**Steps to reproduce the problem**:

1. Create a Priest Draenei.
2. Reach level 4 to train and buy the Skill: Shadow Word: Pain
3. Use it in the training dummy. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Edit:**
The Draenei one has been reported in this topic:
http://www.wowhead.com/quest=26970/learning-the-word -- Draenei race.

The Night Elf one has been reported by a comment in this topic:
http://www.wowhead.com/quest=26949/learning-the-word -- Night Elf race.

These need to be confirmed:
http://www.wowhead.com/quest=26919/learning-the-word -- Human race.
I don't think the Worgen one matters, because it doesn't need dummies in order to get credit.

_Edited by: @TranceAccount_

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by davidtheking341** [comment]
Quest: Learning the Word, Landing Ship Startzone Draenei
NPC:   Zalduun<Priest Trainer>
Spell: Shadow Word: Pain (Priest)
The Quest states that you have to be level 3 to learn the new spell for the quest, but you actually need to be Level 4 to get that Spell. After you are Level 4 and learn the required spell, it's not possible to attack the training dummy to successfully end the quest. 

http://www.wowhead.com/quest=26949/learning-the-word

**Comment by AnimaFox** [comment]
I'll give up. So many things to do just to resolve a glitch or something. I just needed a answer, a solution. Leaving WoW.

**Comment by TranceAccount** [comment]
This probably happens because the dummies remain in combat.

**Comment by Avalain** [comment]
Problem is that you should HEAL wounded by using Flash Heal five times.
I couldn't find wounded draenei.

I was searching for dummy that wasn't in combat and had more than 1 HP to put 5 Shadow Word: Pain on them. Strangely it didn't work on full HP dummy I found in Night Elf starting zone, I found Wounded Sentinel and cast Flash Heal on her. it started counting as I did Shadow Word: Pain.

Conclusion: Quest description is misleading. You need to find Wounded NPC (Wounded Sentinel for example), and use Flash Healing five times.

**Comment by Bildo** [comment]
fixed
