### ISSUE TITLE
The quest Missing in Action in the Gnome starting zone is bugged. You can't rescue the NPC's because all of the cages are already opened, so you can't click them. First time trying this server and 5 minutes in, I'm already finding bugged quests. Not a good sign.

### ISSUE THREAD

**Issue by FistofKhonshu** [Atlantiss/BugTracker#8864]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by whatisthisthing** [comment]
This isn't a place to write reviews about a server, you're best bet for that is reddit or youtube. This is a site to post bugs, how to duplicate them, and how they should be remedied. The fact that you didn't even fill out any of the fields related to the report shows you have no intention of notifying a developer for help and are just here for attention.

**Comment by sigmundfreud2016** [comment]
Good that you bothered to register and report it. Most people forget about this quest in few minutes, that's why it remains bugged. I suggest you to level to 85 and try BG, arena, cata heroics and raids before judging. You 'll not be disappointed, believe me.
Edit your message and title according to the rules, i.e.
title: [EN][Quest][Dun Morogh] Missing in Action
message:
Description: You can't rescue the NPC's: all of the cages are already open and non-interractable.
Expected: https://www.youtube.com/watch?v=QvHuiyVuFDo
Revision: 5294

**Comment by karolnpc** [comment]
Every quest with cages to open are bugged.

**Comment by sigmundfreud2016** [comment]
@karolnpc list "every quest with cages to open"

**Comment by Bildo** [comment]
read bt rules
