### ISSUE TITLE
Arcatraz Dungeon

### ISSUE THREAD

**Issue by Zorbak95** [Atlantiss/BugTracker#8865]
Arcatraz Dungeon has two important bugs:
(The bugs i'm reporting can be found in normal and heroic mode)
The door after the second boss remain closed, no way to pass it.
The final boss event's prisons dont work, only the first one works  then the event will stop.

**Comment by Aldergar** [comment]
Follow the format or the report will be closed

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by Bildo** [comment]
read bt rules
