### ISSUE TITLE
[EN][Quest][Item][NPC]There's Something About the Squire 

### ISSUE THREAD

**Issue by lutherr** [Atlantiss/BugTracker#8866]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  Prompt to loot Maloric doesn't appear after incapacitating him with with large femur

**Current behaviour**: Maloric is stunned, but it is only possible to attack him rather than loot

**Expected behaviour**: He should become lootable and drop murderer's toolkit item

**Steps to reproduce the problem**:

1.  Kill skeletal worker
2.  Incapacitate Maloric
3.  Right click 

**Revision**: 5298

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by BAndysc** [comment]
Fixed in rev 5300
