### ISSUE TITLE
[EN][Quest][Darkshore] Consumed)

### ISSUE THREAD

**Issue by DanielJ79** [Atlantiss/BugTracker#8867]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest ,,Consumed,, can't be completed

**Current behaviour**: When i got into the lake to investigate it , it doesn't show me that i have investigated the whole of the lake , i stay near that artifact that poisons the water ,swim near that artifact so much time and nothing appears to be completed

**Expected behaviour**: http://www.wowhead.com/quest=13881/consumed

**Steps to reproduce the problem**:

1. Take the quest from Kathrena Winterwisp
2. Dive in the lake to locate the devouring artifact
3. Water investigation complete

**Revision**:5298

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/8805

**Comment by DanielJ79** [comment]
![za](https://cloud.githubusercontent.com/assets/25421527/22546062/0bd1649e-e944-11e6-98e0-3c30225d9bd4.PNG)
stop putting that link with how-to-use and resolve this , the smart one

**Comment by BAndysc** [comment]
Fixed in 5299 (bears have to be killed first)
