### ISSUE TITLE
[EN][Quest][Bloodmyst Isle]The Kessel Run

### ISSUE THREAD

**Issue by davidtheking341** [Atlantiss/BugTracker#8868]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: If I start the quest, I can use the Elekk mount, but I can't end the quest because you can't speak with the 3 persons you have to speak with. And I even can't log out because I'm on the Elekk so I had to restart WoW via Task Manager

http://www.wowhead.com/quest=9663/the-kessel-run

**Current behaviour**: Can't speak with the 3 persons you have to speak with

**Expected behaviour**: You should be able to speak to all 3 persons.
**Steps to reproduce the problem**:

1. Accept quest
2. Right click the Elekk
3. You can't complete the quest

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Aival94** [comment]
Have a lot of time to do it bu it used to work just fine. Try to right click the NPCs even if it does not show the correct icon(might be visual bug only).

Other bug: https://github.com/Atlantiss/BugTracker/issues/5639

**Comment by BAndysc** [comment]
Fixed in 5302
