### ISSUE TITLE
Jademir Lake - Bugged archeology site

### ISSUE THREAD

**Issue by Dirtrap** [Atlantiss/BugTracker#8870]
Description: Just finded out that archeology site at Jademir lake in Feralas is bugged below are the pictures that proves it

Current behaviour: Draenei archeology fragments on Night Elven ruins+ fragments inside the texture (mountain) and pointer pointing outside the archeology zone 

![draenei on night elfen ruins](https://cloud.githubusercontent.com/assets/25485181/22513959/1bbb3bb0-e89e-11e6-9d41-68fdb73f911b.png)
![relic insade](https://cloud.githubusercontent.com/assets/25485181/22513978/27e862aa-e89e-11e6-84e3-2019b9cff2ae.png)
![bug](https://cloud.githubusercontent.com/assets/25485181/22514169/ba1f4404-e89e-11e6-8475-786eb2b461d8.png)

Expected behaviour: Pointer should point where the fragments are, the fragment should not be in textures and fragment are ment to be the ones based on race ruins

**Comment by TranceAccount** [comment]
Title.
