### ISSUE TITLE
[EN][RAID]{Firelands} Ragnaros Heroic timers in p2

### ISSUE THREAD

**Issue by Kozakko** [Atlantiss/BugTracker#8872]
**Description**: During fight with Ragnaros few timers are wrong in p2
**Current behaviour**: Wrong timers of World in Flames (http://www.wowhead.com/spell=100171/world-in-flames) and Molten Seed (http://www.wowhead.com/spell=98495/molten-seed) In addition due to bugged World in flames timers we have a situation where sulfuras smah i casted sec before World in flames 
**Expected behaviour**: Timers should look like 
0-emerge of ragnaros
0 m 15 s 1st molten seeds spawn
0 m 25 s 1st molten seeds explosion
0 m 37-38 s world in flames
1 m 15 s 2nd molten seeds spawn
1 m 25 s 2nd molten seeds explosion
1 m 37-38 s world in flames
and we have a 1 min cycle
**Steps to reproduce the problem**:

1. Engage Ragnaros fight
2. Survive till 2nd phase
3. Watch wrong timers
 Some proofs https://www.youtube.com/watch?v=bFmfroDZqc4&t
https://www.youtube.com/watch?v=HEfzHGwCSQk&t
https://www.youtube.com/watch?v=Ez1pRo1sywY
**Revision**: 5298

**Comment by whatisthisthing** [comment]
Thank you for posting this. I was going to post a report tonight after I get footage of the current behavior. I will likely contribute to this post or write a separate one later tonight

**Comment by Aival94** [comment]
Is not this one fixed yet?
