### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Ever So Lonely

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#8874]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest: [Ever So Lonely](http://www.wowhead.com/quest=24974/ever-so-lonely). After the restart the murlocs won't be affected by the leash. 

**Current behaviour**: When you cast [Murloc Leash](http://www.wowhead.com/item=52059/murloc-leash) on http://www.wowhead.com/npc=1544/vile-fin-minor-oracle or http://www.wowhead.com/npc=1543/vile-fin-puddlejumper it won't do anything regardless of their HP.
**Expected behaviour**: First you need to damage the murlocs and after that the leash should make the murloc friendly and give you a buff for 10 min so that you can turn in the murloc.

**Steps to reproduce the problem**:

1. Take quest.
2. Damage the murlocs.
3. Use the leash.

**Revision**: 5302

**Comment by BAndysc** [comment]
Will be fixed in the next update.
