### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Planting the Seed of Fear

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#8875]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest : [Planting the Seed of Fear](http://www.wowhead.com/quest=24999/planting-the-seed-of-fear). If you stand near the little friendly murlocs they get feared but the quest won't count the progress.

**Current behaviour**: When you stand near [Vile Fin Tadpol](http://www.wowhead.com/npc=38937/vile-fin-tadpole) They will get feared but it won't give you credits.

**Expected behaviour**:  You should get credits for fearing the little murlocs.

**Steps to reproduce the problem**:

1. Take quest.
2. Stand near the little friendly murlocs.
3. No credits will be given to you.

**Revision**: 5302

**Comment by BAndysc** [comment]
Will be fixed in the next update

**Comment by mitherio** [comment]
it happens to me that the Vile Fin Tadpol are not scared

**Comment by joelpro2** [comment]
still bugged

**Comment by PlainDoll** [comment]
Still not working. Theyre not getting scared
