### ISSUE TITLE
[EN][Quest][Tirisfal Glades] A Scarlet Letter

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#8876]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest: [A Scarlet Letter](http://www.wowhead.com/quest=24979). Lilian can't be rescued, cause the script seems broken.

**Current behaviour**: When you click on [Lilian](http://www.wowhead.com/npc=38999) you only have one option and if you click that the script goes till the part when she says :  Yes, my... wait, be quiet! I hear the lieutenant approaching. But after that [Scarlet Lieutenant Gabler](http://www.wowhead.com/npc=39002/scarlet-lieutenant-gebler) won't appear and that's the end of the script.
**Expected behaviour**: Scarlet Lieutenant Gabler should appear and the script has to move on till the part the quest will be completed.

**Steps to reproduce the problem**:

1. Loot [A Scarlet Letter](http://www.wowhead.com/item=52079) from http://www.wowhead.com/npc=1535/scarlet-warrior and take the quest.
2. Go to the top of the tower and talk with Lilian.
3. Watch the script.

**Revision**:  5302

**Comment by BAndysc** [comment]
Will be fixed in the next update.
