### ISSUE TITLE
[EN][Quest][Gilneas][Two By Sea]

### ISSUE THREAD

**Issue by rdoherty0** [Atlantiss/BugTracker#8877]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Quest Two By Sea http://www.wowhead.com/quest=14382/two-by-sea

You cannot board the catapults, and therefore cannot complete the quest.

Worse, this means **Worgen are completely broken**, as you are phased on this island and cannot leave until the quest chain is done, and therefore cannot play the character anywhere else or ever progress.

**Current behaviour**: What happens
Catapults are present, Forsaken Machinists are manning them.  You can kill the machinists, but cannot board the catapults and cannot lunch yourself where you need to go to finish quest.

**Expected behaviour**: What should happen instead
You board the catapult, aim it, and launch yourself to the ships where you can kill the required bad guys.

**Steps to reproduce the problem**:

1. Go to the Catapults.
2. Kill The Machinists
3. See that you cannot mount or use the catapults.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
rev 5302

**Comment by diablo0097** [comment]
Confirm, nobody can use this catapults and do this quest. Please repair this.

**Comment by Andgrand** [comment]
It should be fixed immediately. Without completing this quests none new worgens can leave starting area.

**Comment by TranceAccount** [comment]
http://www.wowhead.com/npc=36283/forsaken-catapult

**Comment by Bildo** [comment]
quest works now
