### ISSUE TITLE
[EN][Quest][Wetlands][The Battle Of Thandol Span]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#8878]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hi 

Problem with the quest [The Battle Of Thandol Span] in Wetlands
http://www.wowhead.com/quest=26128/the-battle-of-thandol-span

The NPC can't be killed so the quest can't be completed ... and normally Thargas Anvilmar is suppoded to speak with Calamoth Ashbeard before we can attack him but nothing happens :/

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
