### ISSUE TITLE
[EN][Quest][Darkshore][The Darkscale warlock]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#8879]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hi

Problem with the quest [The Darkscale warlock] in Darkshore : 
http://www.wowhead.com/quest=13899/the-darkscale-warlord

The NPC can be "killed" so it's impossible to talk to him to end the quest ... normally after a fight against him, he becomes "friendly" and wa can talk to him but impossible to reach the end of his life bar.

**Comment by Astear** [comment]
Hi. I can confirm this, even got the pictures too. But Snake, little typo correction it's warlord not warlock. 
Yes you can attack him but you can not kill him as his HP reach 1 hp and that's it.
This was working before I did this quest about one-two weeks ago with another char and it was working.

![wowscrnshot_020317_222801](https://cloud.githubusercontent.com/assets/14007359/22609990/a45f409e-ea63-11e6-8fc5-2347c4e5cad0.jpg)

**Comment by Piklo** [comment]
use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
