### ISSUE TITLE
[EN][Quest][Darkshore][Writings Of The Void]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#8880]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hi

Problem with the quest [Writings Of The Void] in Darkshore :  
http://www.wowhead.com/quest=28529/writings-of-the-void

The problem is really simple ... we just can't go to the location of the NPC who gives the quest ... normally after a little swam wa fall in the cave but there I swim endlessly.

**Comment by Piklo** [comment]
use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by TranceAccount** [comment]
Go to the middle of the lake. Still not blizzlike, but I got into a cave.
