### ISSUE TITLE
Archaeology bugged

### ISSUE THREAD

**Issue by CataCartelmofo** [Atlantiss/BugTracker#8881]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # http://www.wowhead.com/guide=1189/archaeology-1-600-leveling-and-collecting-strategies#power-leveling-375-450

[//]: # ([EN][Archaeology][Proffesion] 
[//]: # ([EN][Archaeology][Drop] Northrend digsites)

**Description**: Unable to proceed with Archaeology beyond lvl 431

**Current behaviour**: No new digsites will appear my map is empty only 1 but that is bugged

**Expected behaviour**: new digsites should pop up so i can continue to lvl the proffesion in Northrend 

![wowscrnshot_020417_122927](https://cloud.githubusercontent.com/assets/25547627/22618173/40e925e8-ead6-11e6-8408-c37f63ab4f06.jpg)

**Steps to reproduce the problem**:

1. Lvl @ toon to [85]
2. Lvl Archaeology
3. Get stuck With Archaeology in northrend

**Revision**: Acore Rev 5304

**Comment by TranceAccount** [comment]
You have a digsite in the Howling Fjord.

**Comment by CataCartelmofo** [comment]
rly dude you gonna do this one as invaled read the post first before you making retard comments on it.

I said i got one but its bugged so that means the one you said is bugged as in not working go troll someone else post

**Comment by TranceAccount** [comment]
Not all digsites you have are supposed to show up in Northrend at 431 archaeology, so this picture doesn't show all places where you could have a digsite.

**Comment by CataCartelmofo** [comment]
thats the only digsite that i got all other continents are empty why should i lie about that

**Comment by CataCartelmofo** [comment]
and even tho i got one digsite there should be more then 1 in northrend yesi played retail and done all this shit already so i know how this should work

**Comment by CataCartelmofo** [comment]
nice and now you don't respond anymore rly pro man

**Comment by TranceAccount** [comment]
What do you want me to say? That you must change the title of your report?

**Comment by CataCartelmofo** [comment]
to what ?
 like instead of being all judge mental you can help people aswell because do you rly think i took all this time to make a post just to troll.....

**Comment by TranceAccount** [comment]
> to what ?

Write your tickets according to the format:
* [EN][Quest][Zone] A Vision of the Past
* [EN][NPC] Thoralius the Wise

> like instead of being all judge mental you can help people aswell because do you rly think i took all this time to make a post just to troll.....

Of course I don't think you took all this time to make a post to just troll, but I do not know how to fix your problem at this moment. 
Just to be sure: Have you also looked at the Outlands for possible digsites?
