### ISSUE TITLE
[EN][Quest][Northern Barrens] Hunting the Huntress

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8882]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest doesn't display that http://www.wowhead.com/npc=3415/savannah-huntress drops http://www.wowhead.com/item=5096/huntress-claws when you hover the mouse over the Savannah Huntress.

**Current behaviour**: It doesn't display that the Savannah Huntress drops the quest item Huntress Claws

**Expected behaviour**: It should display that the Savannah Huntress drops the quest item Huntress Claws

**Steps to reproduce the problem**:

1. Take the quest ''Hunting the Huntress'
2. Hover over a Savannah Huntress
3. You cant see if the Savannah Huntress drops Huntress claw

**Revision**: ACore rev. 5304 hash 5740299ea5a7 2017-02-04 00:51:26 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15070-quest-hunting-the-huntress/

**Comment by Jenovas** [comment]
Fix in rev 5538
