### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8883]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Talk to Rocco Whipshank at Grol'dom Farm and escort his caravan all the way to the Crossroads.

**Current behaviour**: Rocco Whipshank becomes non-interactive when you accept the quest from him, making it impossible to continue the quest.

**Expected behaviour**: You should be able to interact with Rocco Whipshank and escort the Caravan to The Crossroads.

**Steps to reproduce the problem**:

1. Accept the Quest from Rocco Whipshank
2. ???
3. He's non-interactive. 

**Revision**:  ACore rev. 5304 hash 5740299ea5a7 2017-02-04 00:51:26 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
#3718
