### ISSUE TITLE
[EN][Quest][Northern Barrens] Raging River Ride

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8888]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/npc=44057/riverboat boards land when you arrive at your destination, and makes you fall through the land

**Current behaviour**: The ride is perfect, until you arrive at your destination

**Expected behaviour**: http://www.wowhead.com/npc=44057/riverboat stops at the mini docks and drops you off on the mini docks.

**Steps to reproduce the problem**:

1. Accept ''Raging River Ride'' 
2. Board the http://www.wowhead.com/npc=44057/riverboat and ride the river to your destination
3. When you arrive, you fall through the map.

**Revision**: ACore rev. 5304 hash 5740299ea5a7 2017-02-04 00:51:26 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
#5097
#4181
