### ISSUE TITLE
[PL][QUEST] Get Kraken

### ISSUE THREAD

**Issue by wojen616** [Atlantiss/BugTracker#889]
http://www.wowhead.com/quest=14108/get-kraken

Nie zalicza rzutów włócznią (http://www.wowhead.com/item=46954) w North Sea Kraken.

**Comment by Exorcista** [comment]
issue still persist

**Comment by Krasska** [comment]
Nadal nie zalicza. Weszło mi tylko 1/6 za pierwszym razem, już na wszystkie sposoby próbowałam i nic dalej się nie dzieje. Czasem nawet nie da się ich zaggrować.

**Comment by schwim0341** [comment]
If the PL version of this report is that you get no credit for hurling spears, the issue persists and the quest is unable to be completed.

**Comment by Bildo** [comment]
fixed
