### ISSUE TITLE
[EN][Quest][Northern Barrens] Miner's Fortune

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8890]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Retrieve the Cats Eye Emerald from one of the Venture Co. Overseers or Enforcers.

**Current behaviour**: http://www.wowhead.com/npc=34674/brak-blusterpipe Doesn't let you turn in the quest

**Expected behaviour**: http://www.wowhead.com/npc=34674/brak-blusterpipe Should let you turn in the quest

**Steps to reproduce the problem**:

1. Accept the quest http://www.wowhead.com/quest=29015/miners-fortune
2. Retrieve the http://www.wowhead.com/item=5097/cats-eye-emerald
3. Return to http://www.wowhead.com/npc=34674/brak-blusterpipe

**Revision**: ACore rev. 5304 hash 5740299ea5a7 2017-02-04 00:51:26 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by aholler2** [comment]
You can turn this into Wharfmaster Dizzywig in Ratchet.
