### ISSUE TITLE
[EN][Quest][Gilneas]Two by Sea 

### ISSUE THREAD

**Issue by DanielJ79** [Atlantiss/BugTracker#8895]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After killing 8 footsoldiers i have to kill catapult machinists to launch myself aboard the forsaken warships , when i want to get on the catapult it doesn't happen and what really interesting i don;t know what the fuck happens on this realm beaceause yesterday this quest worked perfectly
**Expected behaviour**: What should happen instead
5 months ago the gilneas zone,darkshore worked perfectly i don;t know what happend to you guys , fix the catapults as we can continue our levelling in gilneas
http://www.wowhead.com/quest=14382/two-by-sea
**Steps to reproduce the problem**:

1. Take the quest from Lord Godfrey
2. Kill severel footsoldiers 
3. Kill machinists and launch yourslef aboard the ships ,kill several sailors and those 2 captains Anson and Morris

**Revision**: 5304

**Comment by Andgrand** [comment]
There is already one ticked opened for it. https://github.com/Atlantiss/BugTracker/issues/8877
