### ISSUE TITLE
[PL][QUEST][Fellwood]A destiny of flame and sorrow

### ISSUE THREAD

**Issue by Matti297** [Atlantiss/BugTracker#8904]
**Description**: 
Po rozpoczęciu questa walka pomiędzy Arthasem a Illidanem trwa do śmierci Arthasta.

**Current behaviour**: Arthas waczy do momentu aż zgine

**Expected behaviour**: W pewnym momencie powinni przestać walczyc i powinnien być dialog

**Steps to reproduce the problem**:

1. Weź quest
2. Pomóż illidanowi w walce z Arthasem
3. 

Revision: ACore rev.5304 hash. 5740299ea5a7 (4.3.4 branch) (Unix,RelwithDebInfo)

**Comment by TranceAccount** [comment]
Wowhead link to the quest please?

**Comment by karolnpc** [comment]
http://www.wowhead.com/quest=28218/a-destiny-of-flame-and-sorrow

**Comment by BAndysc** [comment]
Quest rescripted in 5310

**Comment by TranceAccount** [comment]
So I managed to fix #8924 on PTR realm and took this quest, but the event is not really working.
Arthas doesn't spawn, and there are 2 Illidan Stormrage spawned.
![wowscrnshot_070417_215230](https://user-images.githubusercontent.com/13118481/27841603-2efd01da-6103-11e7-97f8-1ae766928422.jpg)
