### ISSUE TITLE
[EN][Quest][Ashenvale] Freedom to Ruul

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8905]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Escort [Ruul Snowhoof](http://www.wowhead.com/npc=12818/ruul-snowhoof)

**Current behaviour**: [Ruul Snowhoof](http://www.wowhead.com/npc=12818/ruul-snowhoof) goes through the ground before vanishing.

**Expected behaviour**: You're supposed to escort him away from the Thistlefurs.

**Steps to reproduce the problem**:

1. Go to Thistlefur Hold (Cave Entrence)
2. Accept [Freedom to Ruul](http://www.wowhead.com/quest=6482/freedom-to-ruul)
3. Attempt to escort him, but fail horribly.

**Revision**: ACore rev. 5305 hash. 4db80dd65b44 2017-02-07 10:14:01 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Cerms** [comment]
UPDATE

Found him in the cave too, and not just outside the cave.
DELETE PLEASE.

**Comment by Piklo** [comment]
@Cerms you can close it yourself
![you can close it yourself](https://cloud.githubusercontent.com/assets/16057987/22712648/e0a8f8ea-ed85-11e6-8371-df086799f538.PNG)
