### ISSUE TITLE
[EN][Item] Troll Charm

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#8906]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
![wowscrnshot_020717_221808](https://cloud.githubusercontent.com/assets/17596151/22712016/9648a216-ed83-11e6-8099-82828f625036.jpg)

**Current behaviour**: You are able to loot [Troll Charm](http://www.wowhead.com/item=46128/troll-charm) as a horde.

**Expected behaviour**: This is an Alliance Quest that you can pick up from the Thistlefur mobs (example [Thistlefur Avenger](http://www.wowhead.com/npc=3925/thistlefur-avenger) ), Horde players should not be able to loot this.

**Steps to reproduce the problem**:

1. Go to Thistlefur Hold
2. Kill Thistlefur Mobs
3. Loot the quest item and try to take the quest.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14180-8906-troll-charm/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
