### ISSUE TITLE
[EN][Raid] Baleroc: Inferno Blade.

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#8914]
**Description**: Baleroc's Inferno Blade currently isn't blockable on Atlantiss.

**Current behaviour**: Baleroc's Inferno Blade isn't blockable. 

**Expected behaviour**: Inferno Blade should be blockable by shield users. 
 
http://www.wowhead.com/npc=53494/baleroc#comments:id=1471272 
"Inferno Blade can be dodged, parried and blocked."   

Video from retail: https://www.youtube.com/watch?v=Pll_qZ_gwQw 
Check the scrolling combat text on the left side of the screen.   

Logs from retail: http://worldoflogs.com/reports/p6uh36yxpv1xxncu/details/3/?s=4018&e=4198 ; http://worldoflogs.com/reports/rt-l04vxtsq8xyxmr3x/details/9/?s=5046&e=5214 
Go into "Damage by Spell" --> Taken --> Inferno Strike. "blocked". 

**Steps to reproduce the problem**:

1. Have a prot paladin/warrior as your main tank
2. Pull Baleroc
3. Enjoy the lack of blocks

**Revision**: 5311

**Comment by Piklo** [comment]
#8894

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14089-8914-inferno-blade-strike/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved

**Comment by stanq87** [comment]
#9912
