### ISSUE TITLE
[EN][Quest][Dragonblight] Steamtank Surprise

### ISSUE THREAD

**Issue by Adamclisi** [Atlantiss/BugTracker#8915]
Description: Use an Alliance Steam Tank to destroy 6 Plague Wagons and deliver the 7th Legion Elites to Wintergarde Mausoleum. Speak with Ambo Cash inside the Wintergarde Mausoleum in Dragonblight should you succeed.

Current behaviour: Steam tanks aren't usable. They can't be boarded, as it's required for quest completion.
![wowscrnshot_021117_145207](https://cloud.githubusercontent.com/assets/25705215/22853944/3fb815ae-f06b-11e6-9eef-3085eca09479.jpg)

Expected behaviour: Steam tanks should be able to be used, so the required Plague vehicles can be destroyed, and the Legion soldiers can be dropped off.

**Steps to reproduce the problem**:

1. Go to [Duke August Foehammer](http://www.wowhead.com/npc=27157/duke-august-foehammer) and take the quest [Steamtank Surprise](http://www.wowhead.com/quest=12326/steamtank-surprise)
2. Go south-east from the Wintergarde Keep, to the Carrion fields, to board the tanks.
3. Tanks aren't working

Revision: ACore rev. 5311 hash. 60f0bbaa11f4 2017-02-08 22:03:25 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
#8850 #8217
