### ISSUE TITLE
[EN][Quest][Achievement] The Purification of Qual'Delar (Blood Elves)

### ISSUE THREAD

**Issue by ounagi21** [Atlantiss/BugTracker#8917]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Description: The cut scene does not work for Blood Elves. A different set of dialogue is suppose to take place for blood elves compared to all other races. 

Current Behavior: No cut scene happens for Blood Elves. Apparently, the cut scene works for every other races as of current revision. I believe this is due to the fact that Blood Elves are suppose to be shown different dialogues/cut scenes.

Expected Behavior: Cut scene should play out and we should be able to grab the quest item.

Here is the link of the quest for Blood Elves only : 
http://www.wowhead.com/quest=24594/the-purification-of-queldelar

Here is the video of the quest for Blood Elves only:
https://www.youtube.com/watch?v=FILdWp5AaaQ

Steps to reproduce the problem:

1. Be a blood elf =.=
2. Take the quest.
3. Join a raid group and teleport into the sunwell using the NPC
4. No cut scene

P.S: I am making a new issue because everything else has been closed. Please do not refer me back to an old issue because this is technically an entirely different issue.

Revision: 5318

**Comment by coba999** [comment]
This quest still bugged for me. Same situation as before.

**Comment by Bildo** [comment]
well shit happens :D sorry i will fix this asap

**Comment by secu312** [comment]
bugged for Night Elves too :D probably for all races

**Comment by ounagi21** [comment]
@Bildo Thanks!

**Comment by Sainsyl** [comment]
Not a blood elf, some sort of cut scene happens for me - weapon appears and when i loot it - it's empty.

**Comment by ounagi21** [comment]
I believe you need to get out of raid party before you loot the weapon if you are able to get the cut scene to appear.

**Comment by coba999** [comment]
@ounagi21  work your advice

**Comment by Sainsyl** [comment]
Oh, i figured it's a raid quest since it requires raid group to tp in and all that. Thanks, that worked:)

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev5319
