### ISSUE TITLE
[PL][Quest][Achievement] A Victory For The Sunreavers

### ISSUE THREAD

**Issue by QuHard** [Atlantiss/BugTracker#8918]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Witam serdecznie,

**Description**: Describe the problem
Po zakończeniu questa "The Purification of Qual'Delar" npc [Myralion Sunblaze](http://www.wowhead.com/npc=36642/myralion-sunblaze) powinien dać finalnego questa o nazwie ["A Victory For The Sunreavers"](http://www.wowhead.com/quest=24800/a-victory-for-the-sunreavers)

**Current behaviour**: What happens
Myralion Sunblaze nie chce dać questa.

**Expected behaviour**: What should happen instead
Myralion Sunblaze powinien dać finalnego questa, który należy oddać u [Archmage Aethas Sunreaver](http://www.wowhead.com/npc=30116/archmage-aethas-sunreaver) w Dalaranie

**Steps to reproduce the problem**:

1. Zakończ questa "The Purification of Qual'Delar"
2. Leć oddać questa "The Purification of Qual'Delar" do npca Myralion Sunblaze w Icecrown
3. Spróbuj wziąć finalnego questa o nazwie "A Victory For The Sunreavers".

**Revision**: 5318.

**Comment by Dranerys** [comment]
Confirmed. After doing all the quests, Myralion doesn't give the final quest.

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev5319
