### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by wowcircle** [Atlantiss/BugTracker#8920]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/quest=24596/the-purification-of-queldelar

**Current behaviour**: The quest doenst pop up in Halduron Brightwing after i finished "Thalorien Dawnseeker"

**Expected behaviour**: Halduron Brightwing should give me quest "The Purification of Quel'Delar" after "Thalorien Dawnseeker

**Steps to reproduce the problem**: dont know

**Comment by Bildo** [comment]
http://atlantiss.eu/changelog#rev5319

**Comment by Aldergar** [comment]
Still bugged on my paladin. I use the quest item near the sunwell but nothing happens

**Comment by secu312** [comment]
same problem as Aldergar

**Comment by Aldergar** [comment]
Now the event starts,but the loot doesn't appear or it's empty

**Comment by Bildo** [comment]
1. Abandon quest
2. clear cache
3. leave raid group before looting sword

**Comment by Lebiedz** [comment]
@Bildo, I've done the steps you wrote above: abandoned the quest, cleared cache - both in root game folder and in /Data folder - and tried two ways: being in the raid group while using the quest item as well as using it after leaving the raid group. Unfortunately, there is still nothing. No event, no sword sticking out from the Sunwell and no progress in the quest.

**Comment by Aldergar** [comment]
@Lebiedz I used the item to the side where Lor'themar is,try it

**Comment by Lebiedz** [comment]
@Aldergar Which faction are you from? Horde or Alliance?
