### ISSUE TITLE
[en][spell][talent] Summon Water Elemental statistics and scaling

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8921]
http://www.wowhead.com/spell=31687/summon-water-elemental

**Description**: statistics scaling and base stats are wrong

**Current behaviour**: it sucks / its too high.

**Expected behaviour**: should be different.

**Steps to reproduce the problem**:

1. summon water elemental
2. see it yourself.

**Revision**: 5318

virtual water elemental base stats taken from simc 4.3
no data about base armor.

void init_base() { pet_t::init_base(); // Stolen from Priest's Shadowfiend attribute_base[ ATTR_STRENGTH ] = 145; attribute_base[ ATTR_AGILITY ] = 38; attribute_base[ ATTR_STAMINA ] = 190; attribute_base[ ATTR_INTELLECT ] = 133; health_per_stamina = 7.5; mana_per_intellect = 5; }

Scaling data from elitist jerk 4.3 thread 

One of the big changes in Cata is that pet scaling is suppose to be fixed, meaning that pets scale as equally as possible with buffs and don’t double dip. For the most part this is implemented. Current scaling on the water elemental in the beta has been reported as follows.
•	Health and Mana: 50%
•	Armor: 0%
•	Spell Power: 40% but this may be academic. Waterbolt may get 1/3 of the mage’s spell power and the spell power of the elemental itself is ignored.
•	Hit, Crit, Haste: 100%
•	Mastery: 0% but Ghostcrawler is indicated that mastery will “scale” as pure damage for trees where sharing the actual mastery would be complicated / illogical.
•	Cit damage: 200%.

Some info about water bolt:
http://catabt.frostmourne.eu/issues/2637
Pet Waterbolt Formula: [195-249 base dmg + (petSP * 0,833)] * 1,25 (frost spec) PetSP= MageSP * 0,4

I tried to look for info about armor contribution from later patches than cata beta:
By bobanddave (+2380) on 17.05.2015 (Content 4.0.6)
Base mana je čistě mana získaná ze základního intellectu. Water summoned elemental má mít a third of its master's spell power, 30% of its master's Stamina and Intellect, and 35% of its master's Armor.. To jsou base staty braný od mage bez equipu viz. 

"Base Mana is the amount of mana you'd have if you were at 0 intellect. Not +0 intellect from gear, but really 0 total intellect in your character screen"
http://forums.elitistjerks.com/topic/105070-cataclysm-mage-resources/page-4#entry1773226

Sadly this topicis unavaible to find on elitist jerk archive yet i think armor scaling here is valid.

Additionaly:
Got movie where warrior in 4.2  attacks water ele -> https://www.youtube.com/watch?v=FOV9cSaRSXI&feature=youtu.be&t=113
Melee damage taken by pet is lower than on mage -> on atlantiss its reversed.
Mage in video due to full ruthless has exact armor as me, due to this fact water elemental armor must be higher than 9k (thats my armor).
Considering research i did on other private servers (tauri when it was still 4.3, warmane, twinstar) -> mage elemental has 9,8k armor without scaling with mage armor.

Actual health on retail compared to atlantiss:
https://youtu.be/Wmzlh6ZIg4M?t=15m37s
mage in video health : 147 000
mage mana in video:  126 000
elemental health in video: 82 377
elemental mana in video:  69 424

http://imgur.com/a/Jqc8j
my health : 145 000
my mana: 125 700
my elemental health: 66 900
my elemental mana: 117 400

harcore math:
water ele health

147 000 – 82 377
145 000 – x

X= 81 256 – this is what my water ele health on atlantiss should be.

Health loss:

81 256 – 100%
66 900 – x

X = 82, 33 %

Mage elemental on atlantiss lose 17, 77 % health

Water ele mana:

126 000 – 69 424
125 700 – x

X = 69 258 – this is what my water mana on atlantiss should be.

69 258 – 100%
117 400 – x

X = 169,51% 

Mage elemental on atlantiss get additional 69,51% mana which it shouldnt have (the ele).

Additionally:

Water elemental doesn’t scale dynamically with buffs.
This means that when i get intellect procs its waterbolt damage is not increased
His health doesnt increase dynamically and mana.
Same goes with haste
It can be also abused (specially with haste) – you cast time warp, summon water ele and its gonna be permament +30% haste untill u mount up/die

**Comment by blinkmaster** [comment]
bumppppppp

**Comment by wtRCH** [comment]
Bump

**Comment by Jenovas** [comment]
Fixed
