### ISSUE TITLE
[PL][Achievement][Firelands] Only the Penitent...

### ISSUE THREAD

**Issue by Reno323** [Atlantiss/BugTracker#8926]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

**Description**: Achiev ktory mozna zdobyc na trashach przed bossem Majordomo.

**Current behaviour**: Achieva nie da sie wykonac poniewaz w grze brakuje dwoch obiektow o nazwie "Fandral's Flames".
http://www.wowhead.com/achievement=5799/only-the-penitent

**Expected behaviour**: Po obu stronach trashy przej Majordomo pownny znajdowac sie obiekty Fandral's Flames ktore po rownoczesnym uzyciu (bez otrzymania obrazen od 'Kneel to the Flame') przyznaja achieva wszystkim uzywajacym. Oto filmik: https://www.youtube.com/watch?v=ORXDvoemm6I
Dodam jeszcze ze ten achiev blokuje mozliwosc wykonania Glory of the Firelands Raider i tym samym zdobycia mounta.

**Steps to reproduce the problem**:

1. Pokonac wszystkie bossy przed Majordomo.
2.  Podejsc do trashu i zobaczyc ze brakuje obiektow Fandral's Flame.

**Revision**: 5319

**Comment by Anhaeyn** [comment]
Jesteś pewien, że podczas wchodzenia na platformę Majordomo, **na pewno nikt** nie otrzymał obrażeń od Kneel to the Flame? Z tego co kojarzę, te obiekty znikają jeśli ktokolwiek otrzyma obrażenia od tej umiejętności.

**Comment by Reno323** [comment]
Tak jestem pewien ze obiekty wcale sie nie pojawiaja. Poza tym nikt na serwerze jeszcze nie lata na mouncie za ta glorke a to o czyms swiadczy.

**Comment by pelekon** [comment]
Zgadza się ten achiev nie działa, ale to już jest zgłoszone tutaj #6031 tak więc zamykam jako duplikat.
