### ISSUE TITLE
Some bugs concerning pets and unholy DK ghouls.

### ISSUE THREAD

**Issue by sp00per** [Atlantiss/BugTracker#8927]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

- When you mount up your pet disappears. Pets should only disappear when you are on a flying mount and take off, start flying, in the air.

- When you dismount and your ghoul shows up, he is with 0 energy.

- If you try to use Gnaw, while your ghoul does not have enough energy, due to the dismounting bug mentioned above, Gnaw buggs out and can't be used until the player leaves combat.

**Comment by Jenovas** [comment]
Please read our guide how to report bugs.
Closing

**Comment by sp00per** [comment]
picky cunt

**Comment by sp00per** [comment]
ye lets not fix these bugs because they weren't reported just as we want them

**Comment by Jenovas** [comment]
Rules are Rules.
EOT.
