### ISSUE TITLE
[EN][Spell][NPC][Death Knight] Summon Gargoyle

### ISSUE THREAD

**Issue by sp00per** [Atlantiss/BugTracker#8928]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The Ebon Gargoyle can be feared by normal fears such as a warlock's fear. It should only be fearable with a paladin's Turn Evil

**Current behaviour**: Ebon Gargoyle can get feared.

**Expected behaviour**: As an undead, it should only be fearable by Turn Evil

**Steps to reproduce the problem**:  

1. Get a DK to summon a gargoyle.
2. Get any class with a fear spell to fear it.
3. Cry as your gargoyle gets shut down.

**Revision**: ACore rev. 5319

**Comment by kabashx** [comment]
It can be feared by warriors fear as well

**Comment by sp00per** [comment]
and another bug is that it does not inherit spell penetration

**Comment by sp00per** [comment]
fix this shit

**Comment by Piklo** [comment]
#9111
