### ISSUE TITLE
You can't drain the essences from HC Alysrazor for last legendary quest.

### ISSUE THREAD

**Issue by kabashx** [Atlantiss/BugTracker#8929]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Well the title says it all. You can't drain the essence from HC Alysrazor for last legendary quest.

**Current behaviour**: You can't.

**Expected behaviour**: You should.

**Steps to reproduce the problem**:

1. Go FL hc
2. Kill boss
3. Drain essence

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by therealpadthai** [comment]
#8472
