### ISSUE TITLE
The last line of defense quest, Argent Vanguard

### ISSUE THREAD

**Issue by kniploks** [Atlantiss/BugTracker#8931]
Quest is not working, when u take quest, all cannons dissapear andu cant kill mobs required.

**Comment by kniploks** [comment]
and just now most of NPC's are dissapeared

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by coba999** [comment]
do quest by yourself
