### ISSUE TITLE
[EN][Core] Auctioneers in Stormwind

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#8932]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Auctioneers Chilton and Jaxon in Trade District are serving some parallel auction. Judging by deposit fees (300% instead of 60%) a cross-faction one. Can't check it because I don't have any horde chars. Auctioneer Fitch is normal. It's a huge trap for someone not paying attention to the fees.

**Expected behaviour**: All auctioneers in SW should serve the same auction.

**Revision**: 5319

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
https://github.com/Atlantiss/BugTracker/blob/master/README.md
