### ISSUE TITLE
[EN] [NPC] [Pet] Warp Stalker

### ISSUE THREAD

**Issue by Kalua96** [Atlantiss/BugTracker#8934]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

I tamed a green warp stalker (http://www.wow-petopia.com/look.php?id=warpstalkerskingreen) in Winterspring. When I summoned him, however, he changed his color to black/purple (http://www.wow-petopia.com/look.php?id=warpstalkerskinblack).
In the stable master's window, however, the color is correct.
![wowscrnshot_021617_182839](https://cloud.githubusercontent.com/assets/20307658/23032739/c552a9f0-f475-11e6-91fd-78a89579006e.jpg)

**Comment by TranceAccount** [comment]
# Please follow our _Issue_template_: 
Thanks in advance.
