### ISSUE TITLE
Pet Hydra

### ISSUE THREAD

**Issue by fostaa** [Atlantiss/BugTracker#8936]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  I had a hydra pet for a long time but now I can't summon it neither tame it again (although it says it's tamable!)

**Current behaviour**: I click on summon the hydra but nothing happens (my character just whistles). I also can't tame it when I try - it says invalid target even that my Beast Lore says "Tamable".

**Expected behaviour**: To be able to have pet Hydra? We are playing Cataclysm so that should be possible. Further more - can't understand why I had it but now I don't. (I also noticed that ONLY ONE hydra in the whole game can be tamed which is also false!).

**Steps to reproduce the problem**:

1. Make hydras tamable again.
2. Fix my own.
3. Explain why hydras should not be pets anymore since everything was ok with them?

**Revision**: ACore rev. 5319 hash. 7bb9aac9d916, 13.02.2017 (4.3.4)

**Comment by Shisai** [comment]
not a bug
http://wow.gamepedia.com/Hydra
"WoD Patch 6.0.2 (2014-10-14): Hydras are now tamable as hunter pets."
