### ISSUE TITLE
[EN][Spell][Death Knight] Death Pact

### ISSUE THREAD

**Issue by sp00per** [Atlantiss/BugTracker#8938]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Using Death Pact to sacrifice a non-pet minion counts as dealing a killing blow to a target that grants experience or honor and therefore resets the cooldown on Death Grip with the Unholy Command talent and procs the Glyph of Dark Succor

**Current behaviour**: If you sacrifice an Ebon Gargoyle, Army of The Dead Ghoul or a non-unholy Ghoul, the cooldown of Death Grip is reset if you have the Unholy Command talent and if you have the Glyph of Dark Succor you get the Dark Succor buff. 

**Expected behaviour**: Non-pet minions of the Death Knight should not count as targets that grant experience or honor, when they are killed with Death Pact.

**Steps to reproduce the problem**:

1. Get a DK with Unholy Command talent and Glyph of Dark Succor.
2. Summon a non-pet minion (anything but an unholy DK ghoul)
3. Use Death Grip before using Death Pact.
4. Use Death pact u cunt

**Revision**: 5319

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

**Comment by sp00per** [comment]
man shut yo gay ass up

**Comment by Bildo** [comment]
LOL
