### ISSUE TITLE
[EN][Night Elf][Racial][Shadowmeld] Substantial Rogue Shadowmeld bug

### ISSUE THREAD

**Issue by sadroguesadface** [Atlantiss/BugTracker#8939]
[//]: # http://cata.openwow.com/spell=58984
[//]: # ([EN][Spell][Night Elf][Racial] Shadowmeld)
[//]: # ([EN][Spell][Class] Ambush)

**Description**: Stealth-only abilities not being able to be used in Shadowmeld.

**Current behaviour**: Currently it only works for feral druid. You cannot use rogue stealth-abilities in Shadowmeld.

**Expected behaviour**: Ambush, Garrote, Cheap Shot and other stealth-only abilites should be able to be used, even in PvE during Shadowmeld.

**Steps to reproduce**:
1. Use Shadowmeld
2. Look at your Ambush
3. See that it doesn't light up.

**Revision**: ACore rev. 5319

**Comment by TranceAccount** [comment]
# Please follow our _Issue_template_

**Comment by Piklo** [comment]
@TranceAccount you forgot about link :D 
[Issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by lamaATS** [comment]
Fixed in rev. 5486
