### ISSUE TITLE
[EN][Stormwind][NPC] Inspector Snip Snagglebolt

### ISSUE THREAD

**Issue by razalghul22** [Atlantiss/BugTracker#8948]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The NPC is missing. He is needed to end a quest.

**Current behaviour**: He is missing.

**Expected behaviour**: He should appear.

**Steps to reproduce the problem**:

1.  Go there. Have a look. Maybe he is out for coffee, but havent seen him in days.

http://www.wowhead.com/npc=38066/inspector-snip-snagglebolt

**Revision**:  5319

**Comment by coba999** [comment]
Added in patch 5.2.0.16577
So it's reason.

**Comment by TranceAccount** [comment]
Watch the comments: 3.3.2 & 4.0.3

**Comment by coba999** [comment]
@TranceAccount sure, i see it's event NPC, and event has gone already.

**Comment by Anhaeyn** [comment]
Thats Love Is In The Air event NPC, event is gone, so npc is gone too.

**Comment by razalghul22** [comment]
Thank you. Didn't see, that he is only there for the event. So I close this.
