### ISSUE TITLE
[PL]Bug z wygrywaniem Battleground'ów

### ISSUE THREAD

**Issue by michux412** [Atlantiss/BugTracker#8950]
**Description**: Kiedy wygrałem dzisiaj BG na Warsong Gluch (horda) mieliśmy 3 flagi a Alliance 0, powinniśmy wygrać ale Tabla pokazała "Alliance wins" i dostałem honor jak za przegraną

**Current behaviour**: Po zrestartowaniu gry, zacząłem nowe BG i powinniśmy przegrać a na tabeli Horde wins ale teraz wogóle honoru nie dostałem

**Expected behaviour**: Powinno być wiadomo jak

**Steps to reproduce the problem**:

1. start BG
2. wygrać lub przegrać
3. efekt jest taki sam (kiedy wygrywasz to przegrywasz a kiedy przegrywasz to wygrywasz bez nagordy)

**Revision**: 5319

**Comment by Jenovas** [comment]
Tylko bug wizualny. Nagrody są rozdawane poprawnie. Własnie sprawdziłem żeby mieć pewność.
