### ISSUE TITLE
Missing pets

### ISSUE THREAD

**Issue by fostaa** [Atlantiss/BugTracker#8955]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Ghostcrawler missing

**Current behaviour**: No NPC Ghostcrawler inhabits Abyssal Depths.

**Expected behaviour**: There should be It.

**Steps to reproduce the problem**:

1. Spawn a Ghostcrawler.
2. Make it tameable.
3. Do the same with Ban'thalos in Hyjal.
4. Apologize for da delay.

**Revision**: Spawn those missing pets already.

**Comment by TranceAccount** [comment]
Fix your title.

**Comment by fostaa** [comment]
Dude, what's wrong wit ma'h title? I dont think there is any misunderstanding written and whoever reads this should know what I am talkin' about. Please.

**Comment by fostaa** [comment]
Now be a good boy. I will post it again. Dont close any topics without discussion/permission of the OP.
