### ISSUE TITLE
[EN][Raid][Firelands] Majordomo Staghelm HC - Searing Seeds don't reset Concentration

### ISSUE THREAD

**Issue by Celiez** [Atlantiss/BugTracker#8956]
http://cata.openwow.com/spell=98450

## _**Current behaviour**:_
Taking damage from Searing Seeds doesn't reset Concentration on Atlantiss.
You can completely ignore this mechanic. You don't need to move out with the Seed at all. You can let your raid take all the damage from Seeds and still maintain everyone's Concentration at 100% for the whole fight.

## _**Expected behaviour**:_
When **anyone** takes damage from Searing Seeds it should break **their** Concentration.

## _**Revision**:_  
5319
Personally observed in 10-man heroic - date 26.02.2017

**Comment by Psychobird7** [comment]
This is correct.      

Can be seen in this video: https://www.youtube.com/watch?v=Eh8rZZm_-ng 
Go to ~1'45, see Seeds getting applied and watch the countdown. Keep watching the SP's Concentration gauge (the blue bar saying "100% - 100%" just above his HP bar.  
You'll see it reset to 0 when Seeds explode.          

**However**. If you become immune to the damage, Concentration will not reset.      
As seen here: https://www.youtube.com/watch?v=ZF-9Ajs8TBc 
Go to ~4'00 and watch the buff bars at the top right. Seeds are about to explode, mage pops IB and keeps Concentration.

**Comment by Kimano** [comment]
What Celiez is referring to is that the damage from your own seed exploding on this server does not reset your concentration even if you take the damage. If you hit anyone else with it, it will correctly reset their concentration, but yours won't affect your concentration.

**Comment by Celiez** [comment]
@Kimano 

> If you hit anyone else with it, it will correctly reset their concentration, but yours won't affect your concentration.

No, Kimano, right now on Atlantiss it doesn't reset **anyone's** Concentration - neither the person who got Seeded, nor the people who were hit by someone else's Seed. It's doesn't work AT ALL.

**Comment by Jenovas** [comment]
Fixed in rev 5343
