### ISSUE TITLE
Need to fix Death knight Tele-Pad's

### ISSUE THREAD

**Issue by Heart1783** [Atlantiss/BugTracker#8958]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

In the Dk starting area the tele pad's are working as intended but they have an infernal on them can ya either remove it or move it out of the player's vision. tyvm (Fyi i dont search for bug's i just report them) so yeah...do with that as ya will.

**Comment by Heart1783** [comment]
i cannot be bothered searching this site for bug's that already exsist so if this issue has been reported, well it just got reported again. ty

**Comment by TranceAccount** [comment]
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use

Thanks in advance.
