### ISSUE TITLE
[EN] [Achievement] 25 Fish

### ISSUE THREAD

**Issue by xALSQ** [Atlantiss/BugTracker#896]
Fishing up items doesn't count towards the achievement. I suppose the later achievements such as 50 Fish and 100 Fish don't work either.

http://www.wowhead.com/achievement=1556 (can't find the OpenWoW link)

**Comment by Angelo-DM-** [comment]
I confirm this bug! The problem is that the fishes are not counted...
openwow 25 fish achievement: http://cata.openwow.com/achievement=1556.

**Comment by qubuslabadz** [comment]
Fixed in rev. 4266
