### ISSUE TITLE
[EN][Bloodlust][Shaman] Bloodlust does not stack with 5% haste buff.

### ISSUE THREAD

**Issue by unkelrara** [Atlantiss/BugTracker#8961]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The 5% haste raid buff does not stack with the 30% haste cd.

**Current behaviour**: The two buffs do not stack.

**Expected behaviour**: The buffs should stack.

**Steps to reproduce the problem**:

1. Drop wrath of air totem.
2. Use bloodlust.
3. Remove wrath of air totem.
4. See that your haste is unchanged.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5319

Edit: Adding a link to an old ej thread talking about haste breakpoints for combustion, including separate breakpoints for Netherwind Pressence, NP+Raid (5% haste), NP+raid+lust.
https://web.archive.org/web/20111025082046/http://elitistjerks.com/f75/t110326-cataclysm_fire_mage_compendium

**Comment by Vayns** [comment]
Can confirm as ele shaman. Just to add it does work for melee haste.

**Comment by KhrystalGH** [comment]
Can confirm as an elemental shaman. It does work with melee haste totem, I'm unsure how it interacts with the other 5% haste buffs.

**Comment by meowmewo** [comment]
Bumperino.

**Comment by Vayns** [comment]
another bumperino with additional info;

Tried this with other classes and had the same problem. Doesn't matter if its bloodlust or timewarp, spellhaste from moonkin, spriest or ele. The spellhaste gets overwritten by BL like its the same buff.

**Comment by Psychobird7** [comment]
Can also confirm this as ret.         
CS with JotP, WoA/BA/MQ and 733haste is at its correct 3.719s CD.    
CS with JotP, WoA, BL and 733haste should be on a 2.861s CD, but instead goes down to 3.003s as if WoA wasn't being applied. (my testing showed WoA to drop altogether while BL was active)      

Would be nice to see this and PI fixed.

**Comment by meowmewo** [comment]
Just tested all possible combinations as well. Confirmed 5% gets overwriten by heroism. Cmon guys, this leads to a lot of lost haste during bloodlust.

**Comment by meowmewo** [comment]
This is a very serious bug. It leads to close to 10% if not more, of lost haste speed during bloodlust/heroism/timewarp. Please.

**Comment by meowmewo** [comment]
Crymucherino.

**Comment by Trollpowah** [comment]
https://youtu.be/k7ToVHYtUWE

As you can see on linked video, despite using Heroism, and removing/reapplying totem, haste values are unchanged.

**Comment by meowmewo** [comment]
You hear that? Thats the sound of destro warlocks crying cuz they cant reach their last Conflagrate cap cuz of this bug.

**Comment by Jenovas** [comment]
Fixed in rev 5431
