### ISSUE TITLE
[EN][Warlock] Hellfire with Tarecgosa staff.

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8963]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: http://cata.openwow.com/spell=1949
Hellfire

**Current behaviour**: Hellfire does not proc from Tarecgosa staff.

**Expected behaviour**: Hellfire will proc out of Tarecgosa staff?

**Steps to reproduce the problem**:

1. https://www.youtube.com/watch?v=UJa-TZ94MnM
2. hellfire dummies / some aoe mobs
3. watch if it does.

**Revision**: ACore rev. 5319 hash. 7bb9aac9d916 2017-02-13 13:53:18 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by blazin995** [comment]
Please fixerino.

**Comment by Illusie** [comment]
@Jenovas hi jenova,
Atleast here I hope I don't need to proof that hellfire work with Tarecgosa xD.

Have nice day man, keep doing great job to ATS and to Players experience.

**Comment by meowmewo** [comment]
Helloooooo :(

**Comment by meowmewo** [comment]
Locks need love too QQ

**Comment by meowmewo** [comment]
This has been working for a while btw.
