### ISSUE TITLE
Chat window not working on one of the characters

### ISSUE THREAD

**Issue by Mallinoss** [Atlantiss/BugTracker#8966]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: On one of the Characters (Wargen - Druid) the general chat window is not working as it should. 

**Current behaviour**: The chat window will show me all the status updates, however, will not show global chat, guild chat, general chat or whispers - The issue occurs only on one character (Eldeara). All the other characters are fine - I gave already removed the Cache folder which did not help.

**Expected behaviour**: I should be able to see when I send a whisper out or when I send a message to my guild. I should also see local defense updates as well as any guild chat/replies I receive. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: I am unable to provide server version as when I type the ".server info" command in the game chat, I can not see the reply, info or my message at all. The game chat remains blank.

**Comment by TranceAccount** [comment]
I don't think this is a bug.
I think you can fix this by right clicking on the General tab > Settings > Toggle stuff

**Comment by Mallinoss** [comment]
Oh Damn!

Fixed :)
Cheers a bunch :)
You're a hero!
