### ISSUE TITLE
[PL][Talent][Druid] Nature's Bounty

### ISSUE THREAD

**Issue by Moks** [Atlantiss/BugTracker#8969]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Talent nie działa poprawnie.

**Current behaviour**: Zamiast skracać czas rzucania Nourshia o 30 % talent zwiększa healing czaru Nourish o 30%.  
Wystarczy rzucić czar Rejuvenation na 1 osobe aby uzyskać zwiększenie healingu Nourshia o 30%.  

**Expected behaviour**: Talent powinien skracać czas rzucania czaru Nourish o 30%  kiedy czar Rejuvenation znajduje się na 3 osobach.
 
Opis talentu: http://wow.gamepedia.com/Nature%27s_Bounty_(druid_talent)

**Steps to reproduce the problem**:

1. Wybrać talent.
2. Użyć czaru Rejuvenation na postaci
3. Użyć czaru Nourish

**Revision**: 5319

**Comment by Jenovas** [comment]
Działa poprawnie. Zamykam.
