### ISSUE TITLE
([EN][Spell][Mage] Fire Orb/Frost Orb )

### ISSUE THREAD

**Issue by niconiconikkinen** [Atlantiss/BugTracker#8971]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Frostfire/Fire Orb takes a rogue out of vanish while vanish buff is active, it also detects rogues and druids in stealth too far away. Same goes for Shadowmeld also

**Current behaviour**: What happens
Shouldn't take rogues out instantly after they use vanish nor should it take rogues or druids in stealth out of such a long range. ( For the first 3 sec after vanishing, damage and harmful effects received will not break stealth.)  http://www.wowhead.com/spell=1856/vanish. Same goes for Shadowmeld also
**Expected behaviour**: What should happen instead
Rogue should be able to vanish and be safe for 3seconds from the Frost/Fire Orb without it getting the rogue out of stealth. Frostfire/Fire Orb also shouldn't take rogues or druids out of stealth at the range it now does.
**Steps to reproduce the problem**:

1. Fix the radius of Frostfire/Fire effecting to people in stealth.
2. Fix Vanish buff so Frostfire/Fire orb doesen't take you out of stealth for 3 seconds after vanishing.
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) Cataclysm 4.3.4

**Comment by blinkmaster** [comment]
@Jenovas 
plz iv got no more strength to reply to such topics :d can u reply to this bugreport?^^
