### ISSUE TITLE
[EN][Spell][Death Knight] Silencing Shot can be applied through Anti-Magic Shell

### ISSUE THREAD

**Issue by sp00per** [Atlantiss/BugTracker#8975]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hunters can apply the Silencing Shot silence, which is a magic effect, while a DK has AMS on, which should be preventing the application of harmful magic effects.

**Current behaviour**: A hunter can silence a DK, while he has Anti-Magic Shell on.

**Expected behaviour**: The silence from Silencing Shot should not be applied, because it's a magic effect and AMS is supposed to prevent the application of harmful magic effects.

**Steps to reproduce the problem**:

1. DK uses Anti-Magic Shell
2. Marksmanship hunter uses Silencing shot on DK, during AMS
3. devs fix this bug

**Revision**: 5319
http://cata.openwow.com/spell=31662
http://cata.openwow.com/spell=34490

**Comment by Anixxia** [comment]
You linked wrong Anti-Magic Shell

**Comment by Jenovas** [comment]
Anti-Magic Shell (AMS) only affects magic abilities. While Silencing Shot leaves behind a magic-type debuff, the skill itself is physical and - as such - is completely unaffected by AMS.
