### ISSUE TITLE
[PL][QUEST][Teldrassil] Resident Danger

### ISSUE THREAD

**Issue by devnull96** [Atlantiss/BugTracker#8976]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
http://www.wowhead.com/quest=13945/resident-danger
**Description**:  Nie zalicza do postępów w quescie zabicia Gnarpline Shaman, Warrior

**Current behaviour**: Zalicza tylko Gnarpline Defender

**Expected behaviour**: Zaliczanie Gnarpline Shaman, Warrior i Defender

**Steps to reproduce the problem**:

1. Wzięcie questa od Sentinel Kyra Starsong
2. Zabicie Gnarpline Warrior/Shaman
3.  - 

**Revision**: 5319

**Comment by Piklo** [comment]
#9274 reported in english with issue_template
