### ISSUE TITLE
[EN][Spell][NPC][Death Knight] Ebon Gargoyle does not inherit the player's spell penetration

### ISSUE THREAD

**Issue by sp00per** [Atlantiss/BugTracker#8977]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Ebon Gargoyle does not inherit the player's spell penetration.

http://cata.openwow.com/spell=49206
**Current behaviour**: It just doesn't get your spell penetration and its attacks get resisted.

**Expected behaviour**: Ebon Gargoyle should be benefiting from the death knight's spell penetration.

**Steps to reproduce the problem**:

1. Get a DK, who has spell penetration (at least 195).
2. Get a class/race with nature resistance racial or spell(tauren, night elves, hunters, shamans)
3. Use Summon Gargoyle on the target with resistance.
4. fix this shit 

**Revision**: 5319

**Comment by Aival94** [comment]
Other bugs: https://github.com/Atlantiss/BugTracker/issues/8928

**Comment by pelekon** [comment]
fixed in rev 5715
