### ISSUE TITLE
[EN][Spell][Shaman] Grounding Totem

### ISSUE THREAD

**Issue by KhrystalGH** [Atlantiss/BugTracker#8978]
**Description**: Grounding not being consumed after like 3 spells reflected.
**Current behaviour**: I ice lanced multiple different shamans for like 6 times in a row, it reflected all of them instead of consuming grounding

**Expected behaviour**: After first spell reflected grounding is consumed and would no longer reflect spells.

**Steps to reproduce the problem**:

1.  Shaman puts grounding.
2.  Use any reflectable spell
3.  ???? 6 reflects?

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)  5319

**Comment by kabashx** [comment]
i saw that as well yesterday in BG. 1 totem reflected 4+ spells

**Comment by Zhalox123** [comment]
Confirmed this was fixed but got bugged again

**Comment by joker1292** [comment]
Confirmed  yestarday 4 ice lance 1 deep freaze pls fix

**Comment by xmesaj2** [comment]
was fixed in rev. 5379
