### ISSUE TITLE
([EN][Quest][Azshara] Ticker Required

### ISSUE THREAD

**Issue by ElliothDracke** [Atlantiss/BugTracker#8979]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

http://www.wowhead.com/quest=14485/ticker-required

**Description**: There are 3 runestones that need to be destroyed with the help of a small squad of goblin which are summoned by using the object " Gob squad flare gun " but when I try to use the gun nothing happens, the gob squad doesn't appear so the quest can't be completed. 

**Current behaviour**: When using the Gob squad flare gun nothing happens.

**Expected behaviour**: A small squad of goblins should appear to help destroy the Spitelash Runestones.

**Steps to reproduce the problem**:

1. Accept the quest
2. Use the gob squad flare gun
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 5319

**Comment by Aival94** [comment]
reported/related: https://github.com/Atlantiss/BugTracker/issues/8687, https://github.com/Atlantiss/BugTracker/issues/6983

**Comment by Piklo** [comment]
#8687
