### ISSUE TITLE
[PvP][Class][Spell][Mage] - Flame Orb/Frost Fire Orb Spell Bug

### ISSUE THREAD

**Issue by PvPbugreporter** [Atlantiss/BugTracker#8981]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
There is a bug I am having when I fight mages as my rogue that is kind of game breaking when fighting mages. Most people do not even realize it is a bug but it is not like this in retail.
**Current behaviour**: What happens
When I vanish as rogue I get a buff called "Improved Stealth". As long as I have this buff the one thing in the game that should unstealth me is the hunter's flair. The bug is that upon vanishing the mage's flame orb or frostfire orb will bring me out when it does damage.
**Expected behaviour**: What should happen instead
   The mage's orb should not bring me out of stealth in any manner as long as I have my improved stealth buff from vanish on, which lasts 3 seconds (5 with the glyph).
**Steps to reproduce the problem**:

1. Find the code for both the flame orb/frostfire orb and for vanish and improves stealth.
2. Identify where the code is missing. This could be with the flame orb, vanish, or improved stealth.
3. Rather than correcting the code, just add a while or if condition to the flame orb that goes something like, " While target enemy player  has buff improved stealth cast (the name of the spell or condition that hits the player) = false

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
#8971 #8109
