### ISSUE TITLE
[en] Crit supression on 3+ level higher mobs/bosses

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#8982]
**Description**: after testing done on dummy and raid bosses you can see crit suppresion for spells is more than 2.1%
Im also unsure about crit suppresion for melee which should be 4.8%

**Current behaviour**: Crit suppresion is too high on spells, greatly reducing dps of many classes.
**Expected behaviour**: spell crit suppresion should be 2.1%
**Steps to reproduce the problem**:

1. go dummy
2. crit dummy with recount for 1000000times
3. see results

**Revision**: 5319
https://web.archive.org/web/20120207223821/http://elitistjerks.com/f78/t111329-combat_guide_cata_12_01_2011_a/
"        Partial resists no longer occur against bosses.
        Glancing blows happen when white attacking equal or higher level NPCs and deal 25% reduced damage. For bosses this has a 24% chance to happen for all of your white attacks.
        When attacking a NPC target from behind you cannot be parried but can still be dodged.
        All melee classes suffer a 4.8% crit suppression vs bosses when using melee attacks.
        All spell attacks have a 2.1% crit suppression vs bosses."

also frost mage pve threads from elitist jerks, according to which you should get shatter crit cap at about 34% crit chance.

**Comment by Psychobird7** [comment]
Melee crit suppression is working properly, from what I can tell.

**Comment by Kozakko** [comment]
AFAIK Crit supression is working like this https://us.battle.net/forums/en/wow/topic/1756045376. But this is only source that i can find where it is written that crit suppresion is beeing increased during the content progression. All of the dps guides says that mele crit suppresion is 4.8 % (1,6 per lvl) and spell crit suppresion is 2.1 (0,7 per lvl) or 3 % (1 per lvl but IMO 1 % was set during warlords, wow wikia article gves value of 1 % but it was updated to WoD)

**Comment by Kozakko** [comment]
> There's no proof of that ever being implemented. Every EJ thread updated to 4.3 that mentions crit suppression states 4.8%/~2.1%.

That's the point I remember Jenova have written somewhere that crit suppresion is set as 1.6 % per lvl and +2 due to firelands but idk if this really should work like this. This topic that i linked is the only one that claims it. And as you said every dps guide claims that suppresion is set on accurat value of 4.8 and 2.1 %. I hope that #Jenova will post somethng here

**Comment by Jenovas** [comment]
Crit Supression is set to:
1. 1.6% per level difference for melee attacks (4.8% vs Bosses)
2. 0.6% per level difference for magic attacks (1.8% vs Bosses)

**Comment by Jenovas** [comment]
Did a test:
Mage - Hit Chance 18.36% (no misses), Crit Chance 10,76%

3240 casts of Fireball
2946 Normal Hits            90.9%
294   Crits                        9.1%

10.76% - 1.8% = 8.97%
Crit Supression seems to be working fine.

**Comment by blinkmaster** [comment]
Oh well atlantiss rng.
Then crit red for spells should be further reduced from 1.8 tp 2.1

**Comment by Jenovas** [comment]
Crit supression will be increased to 2.1% with next update
