### ISSUE TITLE
[EN][NPC][Twilight Portal]

### ISSUE THREAD

**Issue by DanielJ79** [Atlantiss/BugTracker#8984]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I have to kill 12 twilight riders and twilight portal that are stopped by malfurion in the darkshore.
**Current behaviour**: The Twilight Portal respawns so long and more than that it is placed wrong.
![wowscrnshot_030517_125628](https://cloud.githubusercontent.com/assets/25421527/23586927/1ab2282c-01a9-11e7-9b4d-28671a8b579d.jpg)

**Expected behaviour**: The portal's correct place and short respawn time.

**Steps to reproduce the problem**:

1. Kill the twilight riders 
2. See the portal in the middle of the vortex 
3. Destroy the portal , quest completed

**Revision**: 5319

**Comment by Aival94** [comment]
close this one please. You have done a better report.
