### ISSUE TITLE
[EN] [Event] Fishing Contest in Stranglethorn

### ISSUE THREAD

**Issue by sfgjhurtyu** [Atlantiss/BugTracker#8985]
Description: PNJ already say that there's a winner at 14pm

Current behaviour: Not able to complete the contest / No regional annoncement / already a winner before the start of the contest.

Expected behaviour: at 14pm server hour, it should have a regional annoncement saying that the contest is starting. When a player finish the contest, a regional annoncement should also say that there's already a winner. Same for 2nd and 3rd place. Requested fish shouldn't be fishable before the start of the contest.

Steps to reproduce the problem: go in Stranglethorn on sunday at 14pm (as stated in the calendar). Check that the PNJ is already saying that there's a winner (even if the contest shouldn't be started yet). 

Revision: Current server version : 5319

**Comment by sfgjhurtyu** [comment]
At 15pm (server time), the PNJ yelled that we can't finish the contest now. It should yell this at 16pm.
Maybe the contest is starting at 13pm instead of 14pm as stated in the calendar ?

If so, can you please correct the hour of the start of the contest OR correct the time in calendar ?

**Comment by Anhaeyn** [comment]
Yeah, contest starts at 1pm (13), not 2pm (14)
