### ISSUE TITLE
[EN][Quest][Darkshore][The Eye Of All Storms]

### ISSUE THREAD

**Issue by DanielJ79** [Atlantiss/BugTracker#8986]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I have to ride the green dragon thessera and to slay 12 twilight riders and twilight portal.
http://www.wowhead.com/quest=13588/the-eye-of-all-storms

**Current behaviour**: After killing 12 twilight riders , thssera is stuck in the vortex more than that the portal is missing that doesn't allow me to complete the quest , i had been waiting for 3 hours for portal to respawn but nothing happened.

**Expected behaviour**: Put the portal in the vortex , make it respawn faster after that fix the dragon to not be stuck in the vortex because it allows me to land and to complete the quest , but at the current situation the only way to get down is to jump from the dragon and to die.
https://www.youtube.com/watch?v=guQs8Rdl40I

**Steps to reproduce the problem**:

1. Put the portal in the vortex
2. Fix the Thessera Dragon
3. Complete the quest

**Revision**: 5319

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/8675, https://github.com/Atlantiss/BugTracker/issues/8442, https://github.com/Atlantiss/BugTracker/issues/8984
