### ISSUE TITLE
[EN][Raid][Firelands][Majordomo] Movement bug

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#8987]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: While in cat form, Majordomo just stuck in place after 3rd or 4th jump. He only moved on jumps and after switch to scorpion, he stopped moving at all. He was dummy for the rest of the fight.

**Current behaviour**: ^up

**Expected behaviour**: Majordomo should always follow first target on his aggro list.

**Steps to reproduce the problem**:

Not really sure what caused that :(

**Revision**: Current server version: 5333

**Comment by Sainsyl** [comment]
Also when we stacked and got scorpion form, he wasn't hitting us with flames. I think he was hitting those behind,but not in front of him.

**Comment by BAndysc** [comment]
Movement after jumping fixed in 5337
