### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by sfgjhurtyu** [Atlantiss/BugTracker#9000]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quel'Delar is not lootable after purification and event

**Current behaviour**: The event starts (had to finish the sunwell raid before being able to start it). Now the NPCs are talking but there's no loot when clicking on the weapon. I got an Error message in my chat box (see screenshot). 
![quel delar 1](https://cloud.githubusercontent.com/assets/26201332/23750330/ad9efe3c-04cc-11e7-83f7-b82fac221d54.jpg)

I've seen many issues regarding this quest in the bugtracker but can't find a relevant solution and all issues are now closed.

**Expected behaviour**: Repaired Quel'Delar should be lootable

**Steps to reproduce the problem**:

1. Finish Sunwell Raid (without taking the quest)
2. Move out Sunwell and take quest.
3. TP using the guard (as stated in quest)
4. Use the Item in the sunwell and wait to see that the weapon is not lootable.

**Revision**: Current server version : 5340

**Comment by sfgjhurtyu** [comment]
I also tried when disabling all my addons : same issue.

**Comment by Bildo** [comment]
you cant be in raid group

**Comment by sfgjhurtyu** [comment]
Humm ok :)
Thanks for your quick reply.

I just retested it and it worked... I've joined a raid in order to enter the Sunwell Raid using TP with guard, and then go back in group mode. Then I've done the purification, waited for the event to end and was able to loot the item !
I had done this test before creating this issue, that's strange but it worked now.

Thanks for your help anyway !
