### ISSUE TITLE
[PL][NPC] Brann Bronzebeard 

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#9006]
NPC: http://www.wowhead.com/npc=28070/brann-bronzebeard

**Description**: Nie ma opcji rozmowy z NPC przez co instancja nie jest możliwa do ukończenia (problem dotyczy wyłącznie wersji Heroic)

**Current behaviour**: Nie ma opcji rozmowy z NPC

**Expected behaviour**: Powinna pojawić się chmurka umożliwiająca rozpoczęcie eventu

**Steps to reproduce the problem**:

1. Rozmowa z NPC
2. Początek eventu
3. Ukończenie instancji

**Revision**: 5340

**Comment by Aival94** [comment]
Related and other bugs: https://github.com/Atlantiss/BugTracker/issues/2517, https://github.com/Atlantiss/BugTracker/issues/2882, https://github.com/Atlantiss/BugTracker/issues/5839, https://github.com/Atlantiss/BugTracker/issues/5909

**Comment by RastaTinu** [comment]
pls fix it

**Comment by Piklo** [comment]
#9014 reported in english
