### ISSUE TITLE
[EN][Spell][Deathknight] Death Strike / [EN][Talent][Deathknight] Improved Death Strike

### ISSUE THREAD

**Issue by Essigboon** [Atlantiss/BugTracker#9009]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: First Problem:
The spell Death Strike heals 7% of max life, but it should heal up to 20% if you get dmg taken. 
Even if you get dmg it heals only the 7% of life as before. 

Second Problem:
The talent Improved Death Strike, should improved the heal of Death strike be 45%, but it does not.
I tryed it with the talent and without, the amount of heal was both times exact the same.

**Current behaviour**: The heal is always the same.

**Expected behaviour**: Death strike should heal more if you take dmg and the talent should improve the amount of heall too.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links
"**heals you for 20% of the damage you have sustained during the preceding 5 sec** (minimum of at least 7% of your maximum health)". so it shouldn't heal you for 20% of your hp when you take dmg

**Comment by Jenovas** [comment]
It does not effect the minimum 7%. 
This talent only effects the "20%" of DMG part (so basically you heal for 30% of DMG Taken but a minimum o 7%).
