### ISSUE TITLE
[ES][Profesion][Mineria] 

### ISSUE THREAD

**Issue by VicoMaster** [Atlantiss/BugTracker#9011]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Los depositos de mineria de rasganorte tienen muchos problemas en las zonas con relieve, quedan debajo del suelo.

**Current behaviour**: En la mayoria de los terrenos de rasganorte, en particular en Corona de Hielo, el 50% de los depositos de mineria salen bajo tierra, ya sea por un simple relieve o por una piedra quedan debajo de estas imposibilitando que sea recogido el material. Tambien pasa mucho en Zuldrak

**Expected behaviour**: Que salgan encima del terreno, ya sea una piedra, una montaña o en un simple relieve, siempre deben quedar encima.

**Steps to reproduce the problem**:

1. Ir a cualquier lugar donde existan muchos relieves o paisaje montañoso
2. Si marca un nodo el minimapa ir a ese lugar
3. Si no esta el deposito es porque esta debajo de la tierra.

**Revision**: 5340

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
When describing the problem **you can use English as well as Polish and in nearest future - others**.

**Comment by Piklo** [comment]
#9012 reported in english
