### ISSUE TITLE
[EN][Profession][Minning] 

### ISSUE THREAD

**Issue by VicoMaster** [Atlantiss/BugTracker#9012]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The deposits of mining of rasganorte have many problems in the zones with relief, they are under the floor.

**Current behaviour**: In most of the lands to Northrend, in particular in the Ice Crown, 50% of the mining deposits are underground, either by simple relief or by a stone they remain under these making it impossible to collect the material. There is also a lot happening in Zuldrak

**Expected behaviour**: Whether they come out on the ground, whether it be a stone, a mountain or simply relief, must always remain on top.

**Steps to reproduce the problem**:

1. Go to any place where there are many reliefs or mountainous landscape
2. If a node marks the minimap go to that place
3. If it is not  here, Is why because it is under the earth.

**Revision**: 5340

**Comment by xmesaj2** [comment]
Could you mark locations on map where the bugged veins are?

**Comment by VicoMaster** [comment]
Sure!, There are several who are under the earth...In this link are all the photos with the coordinates:
http://imgur.com/a/Vljpx

**Comment by tomatosz** [comment]
Fixed in rev. 5723
