### ISSUE TITLE
[EN][Quest][The Storm Peaks] Battling the elements

### ISSUE THREAD

**Issue by LeoTheCleaner** [Atlantiss/BugTracker#9019]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
http://www.wowhead.com/quest=12967/battling-the-elements#screenshots

For this Quest you have to mount a giant named Snorri and pick up some snow so you can throw it to the Seething Revenants and kill 10 of them, the problem is that there ain't any snow to pick up.
This quest is obligatory in order to complete the quest Forging an Alliance.

**Comment by Piklo** [comment]
use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by Noviush** [comment]
Kill elements by yourself, it will give you a credit for this quest. But only those near anvil, the others doesn't works.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/568

**Comment by artamedan** [comment]
As of 31 march 2017 the "snowdrifts" are still missing. You have to kill the Revenants by yourself to complete the quest. Easy for some classes, not so for other when levelling.
