### ISSUE TITLE
[PL][Quest][Horde][Ashenvale] Tell No One!

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#902]
Brak NPC Durak
http://www.wowhead.com/quest=13751 quest "Tell No One!" ( polowa chaina )

**Comment by Bildo** [comment]
4250 fixed

**Comment by HUMBOL** [comment]
Skoro ten to i ten: https://github.com/Atlantiss/BugTracker/issues/903

**Comment by Bildo** [comment]
nie to sa 2 inne moby

**Comment by HUMBOL** [comment]
Oh, w takim razie sorry za błąd.
