### ISSUE TITLE
[EN][Object][Drop] Frozen Herb

### ISSUE THREAD

**Issue by paulcosma97** [Atlantiss/BugTracker#9021]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Frozen Herbs can't be looted.

**Current behaviour**: See description

**Expected behaviour**: Should drop some herbs.
**Steps to reproduce the problem**:

1. Go to Hillsbrad Foothills
2. Find Frozen Herb
3. Try to loot

**Wowhead Link**: http://www.wowhead.com/object=206085/frozen-herb

**Revision**: 5347

**Comment by Aival94** [comment]
Also Reported: https://github.com/Atlantiss/BugTracker/issues/2197, https://github.com/Atlantiss/BugTracker/issues/3118
Other Related: https://github.com/Atlantiss/BugTracker/issues/3656

Change your title as is not a specific zone bug but instead a profession and object bug.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14310-219731189021-frozen-herb/

**Comment by pelekon** [comment]
Fixed
