### ISSUE TITLE
[PL] [item][Sinestra] tabela lootu

### ISSUE THREAD

**Issue by Binchal** [Atlantiss/BugTracker#9023]
Description:
Błędna tabela dropu na sinestrze przy okazji nie pasuje ona nawet założeniem że wszystkie itemy mają taki sam drop.

Expected behaviour: 
Itemy powinny dropić inaczej niż obecnie to robią.

Steps to reproduce the problem:
http://www.wowhead.com/object=208044/cache-of-the-broodmother#contains:mode=h10

1. Po prostu zabić sinestre więcej niż 10+ 
2. Porównać loot z tym co podaje wowhead.

**Comment by orionTHC** [comment]
Its something wrong with drop calculator, I killed it many times and i never saw drop with highest drop rate, check this out guys

**Comment by Aival94** [comment]
Other bugs: https://github.com/Atlantiss/BugTracker/issues/5107, https://github.com/Atlantiss/BugTracker/issues/5231, https://github.com/Atlantiss/BugTracker/issues/4937, https://github.com/Atlantiss/BugTracker/issues/2278, https://github.com/Atlantiss/BugTracker/issues/1282

**Comment by Bildo** [comment]
everything is working as it should

**Comment by Binchal** [comment]
jak działa to jakim cudem na 12 killów trinket nie dropi ani razu a head lub plaszcz po 7 razy?? To chyba jakiś żart....

**Comment by Piklo** [comment]
@Binchal **teraz** patrzę na ten loot i wszystko wygląda ok. masz pecha, w końcu dropnie

**Comment by Binchal** [comment]
jka wygląda tabela lootu? Możesz podać?

**Comment by Binchal** [comment]
To  mounty z 1 % droopu tak naprawdę mają u was 1/przez liczbę itemów z  bossa?

**Comment by Binchal** [comment]
O.K Ten item mi na 22 itemy nigdy nie poleciał i tyle Pozdrawiam i dzięki że odpisałeś

**Comment by Aviannaqt** [comment]
@pelekon close
