### ISSUE TITLE
[EN][Paladin] Hand of Light (passive)

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9024]
**Description**: Hand of Light (HoL; Retribution paladin's mastery) does not benefit from +8% magic damage taken debuffs (i.e. Curse of Elements). 
http://cata.openwow.com/spell=76672 -- this is the Mastery passive. 
http://cata.openwow.com/spell=96172 -- this is the triggered damage. 

**Current behaviour**: HoL's damage does not benefit from +8% magic debuffs on targets. 

**Expected behaviour**: HoL's damage should benefit from +8% magic debuffs on targets, and should stack multiplicatively with Inquisition. 

- Exemplar has stated on EJ that HoL should not double dip off buffs/debuffs, which it would not if it was increased by the magic debuff, since CS/DS/TV do not benefit from it at all.  
- Exemplar's guide on EJ states the following:  
"Mastery Damage: The original attack is calculated, modified by de/buffs and armour. Mastery then takes the appropriate % of this damage and applies that as a flat value. The Mastery cannot Crit - if the base attack Crit then you are taking 16+% of the Crit, so the increase is already factored. 
**The only de/buffs which impact Mastery are Inquisition and CoE.**" 
- Simcraft shows HoL to benefit from 8% magic debuffs, both the code and simulation results. So does Rawr. 
- See combat log info proving this interaction in my comment below. 

**Steps to reproduce the problem**: 

1. Note your mastery, and go to a dummy. 
2. Do two test runs, one with CoE/EPB/MP/E&M, one without. Do not use Inq. 
3. There will be no difference in HoL damage. (but there **should** be)

**Revision**: 5609

**Comment by 1Andas** [comment]
Interesting report. Looking forward to see how this all turns out.

**Comment by Psychobird7** [comment]
Bump!

**Comment by Psychobird7** [comment]
Bump! edited things.

**Comment by Psychobird7** [comment]
Side note on the EJ guide. 
The bolded line only appears in the MoP guide, however there were no functional changes to Ret mastery from 4.1 to 5.4, so the part stating it should benefit from Magic debuffs should still be accurate, and is backed by theorycrafting tools.

**Comment by Psychobird7** [comment]
Bump. Found direct proof from retail logs.      
Source log: http://www.worldoflogs.com/reports/yagp5xsqd7czj52q/details/50/ 
You can see from the upload date that this is a 4.3.4 log. 

- http://www.worldoflogs.com/reports/yagp5xsqd7czj52q/log/ 
- [{"spellNames": ["Crusader Strike"], "eventTypes": [1]}, {"spellNames": ["Hand of Light"], "eventTypes": [1]}, {"spellNames": ["Templar's Verdict"], "eventTypes": [1]}, {"spellNames": ["Divine Storm"], "eventTypes": [1]}, {"spellNames": ["Curse of the Elements"], "eventTypes": [4]}, {"spellNames": ["Lightning Breath"]}] 

[16:29:40.880] Carlmarx-Shadowmoon Crusader Strike Twilight Assaulter 9754
[16:29:41.621] Carlmarx-Shadowmoon Hand of Light Twilight Assaulter 3237
[16:29:43.229] Leventhorpe casts Lightning Breath on Twilight Assaulter
[16:29:43.634] Twilight Assaulter afflicted by Lightning Breath from Leventhorpe
[16:29:44.866] Carlmarx-Shadowmoon Crusader Strike Twilight Assaulter 9920
[16:29:45.630] Carlmarx-Shadowmoon Hand of Light Twilight Assaulter 3557
3237 / 9754 = 0.331864  -- this is the paladin's mastery multiplier, determined from a mob unaffected by CoE, and the paladin without Inquisition; it will be used in the following 
9920 * 0.331864 * 1.08 = 3557   

------------ 

[16:33:26.512] Carlmarx-Shadowmoon Crusader Strike Ultraxion 23998
[16:33:27.319] Carlmarx-Shadowmoon Hand of Light Ultraxion 7966
[16:33:29.244] Ultraxion afflicted by Curse of the Elements from Kaelthuzzad-Twisting Nether
[16:33:29.647] Carlmarx-Shadowmoon Crusader Strike Ultraxion 28205
[16:33:30.318] Carlmarx-Shadowmoon Hand of Light Ultraxion 10111

[16:33:22.424] Carlmarx-Shadowmoon Crusader Strike Ultraxion 9975
[16:33:23.144] Carlmarx-Shadowmoon Hand of Light Ultraxion 3311
^ This is without CoE and inquisition 
= 0.3319298246
 
[16:33:29.647] Carlmarx-Shadowmoon Crusader Strike Ultraxion 28205
16:33:30.318] Carlmarx-Shadowmoon Hand of Light Ultraxion 10111 
This is without inquisition and with CoE up
28205 * that long number * 1.08 = 10111

[16:33:32.455] Carlmarx-Shadowmoon Crusader Strike Ultraxion 12455
[16:33:33.238] Carlmarx-Shadowmoon Hand of Light Ultraxion 5805
This is Inquisition and CoE 
12455 * that long number * 1.3 * 1.08 = 5804

**Comment by Piklo** [comment]
should be fixed in [rev5782](https://atlantiss.eu/changelog#rev5782)
