### ISSUE TITLE
[EN][Spell][Shaman] Flame shock

### ISSUE THREAD

**Issue by pwnrip** [Atlantiss/BugTracker#9026]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The haste breakpoints for flame shock are 5% (+1 tick), 15% (+2 ticks), 25% (+3 ticks), 35% (+4 ticks) etc. 

I tested this with no gear and "wrath of air totem" which gives 5% haste and no extra tick is given. However, if you go over the 5% you will get an extra tick, same counts for 15% you need to have atleast 16% haste in order to get an additional tick. 
For 25% same problem, currently (fully geared) I have 26.57 % haste and am not getting that extra tick.

**Current behaviour**: What happens
Extra ticks aint happening according to haste breakpoints

**Expected behaviour**: What should happen instead
It should happen according to haste breakpoints

**Steps to reproduce the problem**:

1. Flame shock on dummy with no gear, with and without wrath of air totem for the 5% 
2. Put some additional gear on for the 15%, 25% etc...
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5347 hash. f24189504087

**Comment by Psychobird7** [comment]
"Revision" only needed to be 5347, fyi.        

As for the WoA bug, this could be similar to what's happening to BL+WoA.

**Comment by Vayns** [comment]
Seems to me you got the haste breakpoints from MoP. From what I've tested just now the breakpoints seem to work for the most part. Here's what I found;

no haste and no buffs gave me 9 ticks = correct
710* haste gave me 10 ticks = correct
Wrath + 1423* haste gave me 11 ticks = correct
Wrath + Emastery + 183* haste gave me 12 ticks = correct
BL + Wrath + 228* haste gave me 12 ticks = not correct and should be 13
BL+Wrath+Emastery + 1526* haste gave me 16 ticks = not correct either and should be 17

_*for the haste i just unequipped items to get as close as possible to the cap, so my actual stats with the tests is ~10 to 40 haste higher._

So even though the report isn't correct my tests do prove once again that BL + Wrath isn't stacking as reported in #8961

**Comment by pwnrip** [comment]
OK my bad, thanks for clarification
