### ISSUE TITLE
[PL][Quest][Horde][Ashenvale] Dread Head Redemption

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#903]
Brak NPC Durak 
http://www.wowhead.com/quest=13842 quest "Dread Head Redemption" ( last q z chaina )

**Comment by Danelar** [comment]
W którym revie to naprawicie?

**Comment by Danelar** [comment]
Brak możliwości rozmowy z Durakiem :|

**Comment by Bildo** [comment]
fixed ?
