### ISSUE TITLE
[EN][Spell][Shaman] Grounding Totem Glyphed

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#9035]
Description: Describe the problem
Grounding totem with reflect glyph is bugged
The totem doesnt get consumed by using spell on enemy 

Current behaviour: What happens
When you cast spells the totem doesnt get consumed by it.It also reflects more than once and doesnt get consumed for most 3-4 spells casted.

Expected behaviour: What should happen instead
The grounding with glyph to reflect should reflect a spell then get removed.
Steps to reproduce the problem:

Drop grounding with glyph to reflect
Cast grounding glyphed 
Cast spell on enemy
Totem doesnt get removed 
Revision: Current server version
5347

**Comment by Piklo** [comment]
#8978
