### ISSUE TITLE
[EN][Spell][mage] Dragonwrath staff procs consume hot streak buff.

### ISSUE THREAD

**Issue by PolpoVolante** [Atlantiss/BugTracker#9039]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
When Dragonwrath legendary staff procs off of an instant pyroblast (pyroblast!) if there is another hot streak procced the said hot streak will be consumed.

**Current behaviour**: 
Dragonwrath consumes a new hot streak if an old instant pyro got the proc.

**Expected behaviour**: 
When it procs off of a pyroblast! it should just launch another pyroblast! regardless if there is an hot streak proc or not on the caster.

**Steps to reproduce the problem**:

1. cast fireball till you have hot streak + another fireball crit
2.  cast fireball and pyroblast! after 0.2 
3.  if fireball crits it procs hot streak
4. if pyroblast! gets a proc of dragonwrath it cancels hot streak.

**Revision**: 5347 but its been atleast  a week before i understood how it worked.

Also found this link that's pretty much the same: https://us.battle.net/forums/en/wow/topic/3789699952

![wowscrnshot_031517_110058](https://cloud.githubusercontent.com/assets/24251572/24142534/25da2a58-0e27-11e7-9b4e-ce60fc9f00e4.jpg)

**Comment by stanq87** [comment]
we know, https://github.com/Atlantiss/BugTracker/issues/8769 + wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest

**Comment by CatchmeATS** [comment]
Its not a bug.

**Comment by PolpoVolante** [comment]
It looks like a bug if you consider the fact that it can proc off instant pyroblasts and in those cases it doesnt waste anything.

Seems like common sense to me.
Make it always  consume hot streak or never.
