### ISSUE TITLE
[PL][Quest][Horde][Ashenvale] Blastranaar!

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#904]
Brak możliwości wziecia mounta u Thraka który bedzie lecial nad wioska Alliantów żeby móc ją zbombardować
http://www.wowhead.com/quest=13947 quest "Blastranaar!" ( last q z chaina )

**Comment by anijatsu** [comment]
+1

**Comment by Wolffenstein** [comment]
Fixed in rev 4489.
