### ISSUE TITLE
[EN][QUEST][Sholazar Basin] Rejek: First Blood

### ISSUE THREAD

**Issue by sfgjhurtyu** [Atlantiss/BugTracker#9042]
Description: the quest [Rejek: First Blood](http://www.wowhead.com/quest=12734/rejek-first-blood) isn't working.  (exactly the same issue as #8786 )

Current behaviour: Using of [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade) doesn't count quest progress.

Expected behaviour: Using of [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade) on one of the three target should validate the count progress.

Steps to reproduce the problem:

Take quest [Rejek: First Blood](http://www.wowhead.com/quest=12734/rejek-first-blood)
Use [Rejek's Blade](http://www.wowhead.com/item=39577/rejeks-blade) on one of the three target (it doesn't work for any of these three targets)
Quest progress doesn't count.
Revision: 5347

Unfortunately, revision 5286 doesn't solve the issue.

**Comment by xmesaj2** [comment]
fixed in rev. 5404
