### ISSUE TITLE
Water Elemental Melee attack bug..

### ISSUE THREAD

**Issue by Gianniskalikakis** [Atlantiss/BugTracker#9044]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Water Elemental Melee attack...

**Current behaviour**: I just spawned a water elemental pet.. and the only thing it does is waterbolt it should melee too but it doesn't.. even if the target is in the melee range... how can I set it to automelee

**Expected behaviour**: The Water elemental should auto melee when it was in the melee range

**Steps to reproduce the problem**:

1. Spawn Water elemental 
2. Pressing Ctrl-1 to attack 
3. Fires only waterbolt..(that i set it on autocast) 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Jenovas** [comment]
Water Elemental chouldnt be able to melee attack. Closing.
