### ISSUE TITLE
[EN][NPC] Darkslayer Mordenthal

### ISSUE THREAD

**Issue by Rolvalkz** [Atlantiss/BugTracker#9046]
[//]: http://www.wowhead.com/npc=3736/darkslayer-mordenthal

**Description**: Not a rare mob as shown on wow head

**Current behaviour**: Normal Mob Normal XP for kill

**Expected behaviour**: Should be Rare Mob with Rare XP bonus for kill

**Steps to reproduce the problem**:

1. kill it
2. see it
3. be disappointed by it

**Comment by Rolvalkz** [comment]
![wowscrnshot_032417_014611](https://cloud.githubusercontent.com/assets/26643369/24282075/b42c46fc-1033-11e7-89aa-a03f5c9179ba.jpg)

**Comment by TranceAccount** [comment]
Wowhead link.

**Comment by Rolvalkz** [comment]
http://www.wowhead.com/npc=3736/darkslayer-mordenthal

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/13850-npc-darkslayer-mordenthal/

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
