### ISSUE TITLE
[en][item][spell][mage][talent][Dragon's Breath] Dragonwrath legendary staff and

### ISSUE THREAD

**Issue by kabashx** [Atlantiss/BugTracker#9047]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When staff procs on Dragon's Breath, u get deminishing returns on the stun.

**Current behaviour**: When you use Dragon's Breath and staff procs, it doesnt duplicate only the dmg, it duplicates the stun itself, so instead of 5s stun u get only 2.5s stun. And yes, I dont use glyph of Dragons Breath.

**Expected behaviour**: The staff should replicate the dmg only without stuning the target again and by doing that halfing the stun on the target.

**Steps to reproduce the problem**:

1. Get Dragonwrath legendary staff
2. Use Dragon's breath till the staff procs
3. See 2.5s stun 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by BialyADI** [comment]
Proof?

**Comment by Jenovas** [comment]
No proof provided. Closing.
