### ISSUE TITLE
[EN][Spell][Warlock] Seduction

### ISSUE THREAD

**Issue by moonsado** [Atlantiss/BugTracker#9048]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description:  Succubus cant cast Seduction on an already controlled target (polymorphe, blind, hammer of judgment etc). 

Current behaviour: Succubus won't either cast or even start casting her seduction ability as long as there is another form of crowd control.

Expected behaviour: Seduction should be able to chain crowd control with polymorphe. For example if a mage casts polymorphe on a rogue and there is 2 seconds left a warlock should be able to precast seduction to land on its target as the polymorphe fades.

Steps to reproduce the problem: Ask a friend to crowd control a target try to use seduction on it it wont start casting unless it isnt crowd controlled anymore.

http://cata.openwow.com/spell=6358

**Comment by joker1292** [comment]
it is true, this is a serious bug I hope we can solve it as soon as

**Comment by dxxa** [comment]
Yeah i know it,this a serius bug for cc

**Comment by moonsado** [comment]
Notice me please q_q...

**Comment by liran11** [comment]
https://github.com/Atlantiss/BugTracker/issues/9048
