### ISSUE TITLE
[PL][Quest][Horde][Ashenvale] To the Rescue!

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#905]
Nie można porozmawiać z Kadrak at Mor'shan Ramparts aby udać sie do obozu w Splintertree Post
http://www.wowhead.com/quest=13712 quest "To the Rescue!" ( polowa chaina )

**Comment by Adramen** [comment]
I tried doing this quest today and was unable to get further than accepting the quest. After talking to Kadrak to begin the quest there was no Kodo spawned to ride/follow to Splintertree Post. I tried just taking the flight path to  to town see if the quest would complete that way, no luck. There is a Kadrak spawned in Splintertree.

**Comment by anijatsu** [comment]
+1

**Comment by BAndysc** [comment]
Fixed in rev. 4464
