### ISSUE TITLE
[EN] [Class - Druid] Wisp Spirit

### ISSUE THREAD

**Issue by Slotease** [Atlantiss/BugTracker#9052]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
When a nightelf dies they get the faster wisp spirit form. See here: http://wow.gamepedia.com/Wisp_Spirit

**Current behaviour**: What happens
When i die i get the wisp spirit visual but not the altered faster travel mode and am the slowest out of all that wipe. 

**Expected behaviour**: What should happen instead

While other races run at normal movement speed as ghosts, this racial trait causes dead night elves to turn into wisps that move 75% faster.

**Steps to reproduce the problem**:

1. Die
2. Arrive at the spirit healer and then attempt to run back to corpse.
3. 

Feel free to log my character in and die. You will see how slow it is. It is walking speed rather than the boosted %75 speed it should be. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by kabashx** [comment]
maybe u are the slowest of all people who wiped couse they were in a 25lvl guild, and one of the perks of a 25 lvl guild is faster spirits when u die...

**Comment by Khangu** [comment]
Wisp spirit stacks with guild ghost speed boost, making nelfs ultra fast wisps.

**Comment by TranceAccount** [comment]
> Feel free to log my character in and die. You will see how slow it is. It is walking speed rather than the boosted %75 speed it should be.

You think they do that?

**Comment by Piklo** [comment]
![image](https://user-images.githubusercontent.com/16057987/29086582-67cfb4cc-7c73-11e7-9c0c-1b85515a5d27.png)
wisp boost works fine for me
