### ISSUE TITLE
[EN][RAID][Firelands] Majordomo Executus is not resetting after a wipe

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#9058]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Majordomo Executus doesn't reset, preventing the raid from zoning into the raid again

**Current behaviour**: Majordomo Executus doesn't reset, preventing the raid from zoning into the raid again

**Expected behaviour**: Majordomo Executus should reset

**Steps to reproduce the problem**:

1. Fight Majordomo
2. Wipe
3. Try to zone in

**Revision**: 5356

**Comment by Aival94** [comment]
This one is fixed already.

Furthermore Majordomo Executus is on Molten Core while the one in Firelands is called Majordomo Staghelm.
