### ISSUE TITLE
[PL][NPC][Stormwind][Transmutation]

### ISSUE THREAD

**Issue by Samel12** [Atlantiss/BugTracker#9059]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Gdy wchodzę do pomieszczenia, w której można dokonać transformacji to wszystkie postacie dookoła znikają (NPC/inni gracze) i tak samo ja dla nich staję się niewidzialny. To samo się dzieje przy moście, który jest idealnie na przeciwko w stormwind.

**Current behaviour**: Znikam wszystkim graczom i nie jestem w stanie robić transformacji wyglądu ekwipunku.

**Expected behaviour**: Wszystko powinno zostać a nie znikać. Nie mam możliwości korzystania z tego miejsca.

**Steps to reproduce the problem**: nie wiem o co cho

1. 
2. 
3. 

**Revision**: http://imgur.com/a/ZHzVB

**Comment by Samel12** [comment]
Mój nick na tej postaci to Samalejkaa

**Comment by pelekon** [comment]
Bugtracker nie służy do rozwiązywania pojedynczych bugów psotaci, od tego są tickety.

**Comment by Piklo** [comment]
ticket in game
