### ISSUE TITLE
[PL][Quest][Horde][Stonetalon Mountains] We're Here to Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#906]
Nie można wskoczyc na wagon
http://www.wowhead.com/quest=25945 quest "We're Here to Do One Thing, Maybe Two..." (poczatek q w Stonetalon Mountains)

**Comment by Danelar** [comment]
W którym revie to naprawicie? bo wciąż nie można przeprowadzić wagonu :|
