### ISSUE TITLE
[EN][SPELL][SHAMAN] Grounding totem being removed by Chimera shot.

### ISSUE THREAD

**Issue by champk1** [Atlantiss/BugTracker#9060]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Marksman hunter's Chimera shot removes shamans grounding totem.

**Current behaviour**: Chimera shot removes grounding totem. This should not happen. 10/10 bug.
Got a quick vid of it done in wargame. https://vid.me/dsvX

**Expected behaviour**:  Hunter should be able to remove grounding only via Growl(pet taunt), or just by killing the totem. 

**Steps to reproduce the problem**:

1.  Go into wargame or just arena with a Shaman(was resto) and a MM hunter.
2. Simply use grounding totem and let hunter use Chimera shot
3. Grounding totem is removed. Rip. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) - 5356

**Comment by champk1** [comment]
Bump

**Comment by lamaATS** [comment]
Problem is not **Chimera Shot** but **Concussive Barrage** proc.
I found info about it [here](http://www.arenajunkies.com/topic/208397-new-hunter-bug/?p=3429056)
> 2. Grounding Totem takes Concussive Barrage from Chimera Shot, but it does not seem to destroy it. You just see 'Immune' pop up on the Grounding.

So it was kind of bug on Retail too.

**Comment by lamaATS** [comment]
Fixed in rev. 5510
