### ISSUE TITLE
[EN][GLYPH][SHAMAN] Glyph of grounding totem.

### ISSUE THREAD

**Issue by champk1** [Atlantiss/BugTracker#9061]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Shamans Glyph of grounding totem reflecting up to 3 abilities, instead of just 1.

**Current behaviour**: Glyph of grounding totem can be abused hard in arenas/bgs. Instead of absorbing a spell, the glyph reflects the spell, but it should reflect only 1, instead if reflects up to 3 different abilities now. Can be abused hard on reflecting full shatters/on locks dark soul etc.

**Expected behaviour**: The glyph should reflect only one ability, instead of over 3.

**Steps to reproduce the problem**:

1.  Play shaman and use grounding totem glyph
2. Duel/play in bgs/arenas against a caster and use grounding.
3. Let them use their rotation on you and see for yourself.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) - 5356

**Comment by moonsado** [comment]
Confirmed, I tried to fear someone it reflected onto me then I tried again it reflected again and then i used fel flame and it reflected one more time...............

**Comment by xmesaj2** [comment]
fixed in rev. 5379
