### ISSUE TITLE
[Quest][Deepholm] Violent Gale

### ISSUE THREAD

**Issue by ming21266** [Atlantiss/BugTracker#9062]
I wanted to do that quest but there's no trigger after finding the cave. [//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Use the template when reporting, otherwise report will be marked invalid and closed, if it's too hard then I made this simple generator https://xmesaj2.github.io/SimpleBT/

It found also it was reported before:
#7207 [EN][Quest][Violent Gale]
#5441 [PL][Quest][Deepholm] Violent Gale

so probably this report will be closed anyway

**Comment by ming21266** [comment]
Sorry for mistakes. It was my first report. Thanks for information.

2017-03-29 23:49 GMT+02:00 Mesaj <notifications@github.com>:
