### ISSUE TITLE
EN][ACHIEVMENT]Classy Dwarves

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#9068]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: A member of my guild dwarf warlock get honored rep last night relog and yet the warlock criteria of dwarf 85 dint triggered. The dwars was a faction change but on all wowhead comments they say that's not a problem as long as its 85 and have honored at least.

**Current behaviour**: Warlock get honored Rep with guild and didn't treigger in the meta achi.

**Expected behaviour**: When 1 class-race specific combo reach both things necessary: 85 + honored guild shold get credit.

**Steps to reproduce the problem**:

1. Be in guild wich a class-race combo they dont have
2. reach lvl 85 and honored rep with guild
3. check the meta guild achievment

**Revision**: rev. 5357)

**Comment by TranceAccount** [comment]
Can any other guild confirm that the warlock criteria in [Classy Dwarves] didn't proc?

**Comment by DuGalle** [comment]
If its some help warlock was goblin before faction change and he was 85 when hit Honored with our guild

**Comment by TranceAccount** [comment]
Okay the achievement should work normal, but something went wrong with your guild's achievement.

**Comment by DuGalle** [comment]
A way i thin to make this work coz it seems only our guild ach dont proc and since this is the last thing before our Tab 8 of the Vault, i have a suggestion if some gm is kind enough to lower the lock by 1 lvl then return to 85 and i think it will proc for our Guild. :)

**Comment by TranceAccount** [comment]
They won't do that

**Comment by DuGalle** [comment]
ok then only lower him by one lvl he will get to 85 on himself

**Comment by TranceAccount** [comment]
They won't do that either.

**Comment by DuGalle** [comment]
then what he wasted 44k gold on faction change for nothing ...

**Comment by TranceAccount** [comment]
You bought a faction change for this? Lol.
You could try a ticket, and I'm not sure whether this is a bug or not, because I don't how the achievement should work.

**Comment by DuGalle** [comment]
http://www.wowhead.com/achievement=5152/stay-classy#comments

By Kyraylia (150 – 10) on 2012/10/13 (Patch 5.0.5)		
Question for you all

To get the acheivements:?

Do the people need to actually reach the level 85 or 90 while in your guild?
Like If someone is invited to your guild that is higher than the needed level then later gets honored with the guild will you get the acheive?

Do they actually need to reach the level while honored - ?

Thanks

2

	

FurySpec on 2013/01/18 (Patch 5.1.0)
You'll get credit for each class/race combo as soon as you have somebody of that class & race in your guild who is at least level 85 (90 for Pandaren) and Honored with the guild. It doesn't matter what order they meet the criteria, and you can recruit a new 90 to your guild and get credit as soon as he/she is Honored. You can also do a race change, for example if you've already done Gnome Mage and want to easily get credit for Dwarf Mage.

**Comment by DuGalle** [comment]
Close the report the achievement just procked wile doing a regular quest with give 6 rep with guild i guess server restart fixed it :) We are now proud Owners of Tab 8
