### ISSUE TITLE
[PL][Quest][Horde][Stonetalon Mountains] In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#907]
Brak dział
http://www.wowhead.com/quest=26058 quest "In Defense of Krom'gar Fortress"

**Comment by Danelar** [comment]
Brak Mobów do ubicia :|

**Comment by NONLIFE** [comment]
Najpierw trzeba mieć z czego strzelać do tych mobów.

**Comment by Danelar** [comment]
a gdzie to jest?

**Comment by NONLIFE** [comment]
Obok npc od ktorego bierzesz q masz platforme tzn po lewej stronie i tam powinny byc dziala

**Comment by Danelar** [comment]
No widzę, że są te platformy na działa :/

**Comment by Angelo-DM-** [comment]
The quest can't be done.
The GOBLIN HEAVY GUNS http://www.wowhead.com/npc=41895 are missing.

How it should work: https://www.youtube.com/watch?v=sKM2TP3Hveg
