### ISSUE TITLE
[EN][Spell][Paladin][Rebuke]

### ISSUE THREAD

**Issue by Beatlejuicey** [Atlantiss/BugTracker#9073]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

Rebuke interrupts but does not silence the target from casting spells from the same school for 4 seconds as it should do. http://www.wowhead.com/spell=96231/rebuke

**Current behaviour**: What happens

Rebuke only interrupts spell casting.

**Expected behaviour**: What should happen instead

Interrupts spellcasting and prevents any spell in that school from being cast for 4 sec.

**Steps to reproduce the problem**:

1. 
 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

Revision 5357

**Comment by meowmewo** [comment]
Just to move away one small detail. Are u taking in consideration that in order for the 4 sec prevent to happen, a spell has to be interupted.

**Comment by Beatlejuicey** [comment]
Yes of course

**Comment by Holycowitstaurenpaladin** [comment]
this is true. I also have paladin its just interrupt spellcasting without blocking magic school for 4 sec

**Comment by 1Andas** [comment]
I noticed that when used on mobs school most of the time does not get locked, on players I am not sure.

**Comment by Beatlejuicey** [comment]
I have not tested it on players, only NPCs

**Comment by Jenovas** [comment]
This does not work on NPCs, is already reported. Closing.
