### ISSUE TITLE
Dalaran quest "Waterlogged recipe"

### ISSUE THREAD

**Issue by Holycowitstaurenpaladin** [Atlantiss/BugTracker#9074]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
1.Quest <Waterlogged recipe> Zone - Dalaran.
2.NPC Christi Stockton <Wine vendor>
3.I have finished fishing quest and recieve waterlogged recipe which i should bring to npc who is called Christi Stockton wine wendor. All quest helpers lead to this npc. When im reading quest its also leading to this npc. But i cant finish this quest because there is no options to complete it. No yellow question mark above this npc.Fix this quest please if you can do it.I dont know how to add screenshots here сorrectly because its my first message.
![wowscrnshot_040117_102121](https://cloud.githubusercontent.com/assets/26832621/24576515/c92ab208-16c5-11e7-8586-3a8bbce6c725.jpg)
![wowscrnshot_040117_102143](https://cloud.githubusercontent.com/assets/26832621/24576516/d2fa4906-16c5-11e7-88dd-ebd35de452b5.jpg)
Acore rev.5357 hash.f895f588dcc8 2017-03-29 00:17:01 +02:00 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by TranceAccount** [comment]
Uhmm first of all, you should have stated the zone, language and quest in the title as follows: 
[EN][Quest][Dalaran] Waterlogged Recipe
Second: Missing a wowhead link to the quest / npc.
Third: You should've followed the issue_template that is automatically generated by the issue_template.md.

Not saying this to demotivate you, but it are the bugtracker rules.

**Comment by TranceAccount** [comment]
http://www.wowhead.com/quest=14203/waterlogged-recipe states that the quest is for alliance only for some reason... 
Can I ask you how you got the item?

**Comment by Holycowitstaurenpaladin** [comment]
Sure its fishing daily

**Comment by Holycowitstaurenpaladin** [comment]
in dalaran quest mob Marcia Chase gives 5 daily quests after completing you recieve bag with some things deviate fish and something like that. I recieved this item from that bag

**Comment by IamtheLexx** [comment]
I play ally and it doesn't work either on our side, you can't complete the quest.

**Comment by Holycowitstaurenpaladin** [comment]
Thanks for help everyone anyway.Im closing this topic

**Comment by TranceAccount** [comment]
Why do you close it if it doesn't work?

**Comment by Holycowitstaurenpaladin** [comment]
Its alliance quest.Im horde player its gives me nothing.All i have to do abandon it and thats all.

**Comment by Holycowitstaurenpaladin** [comment]
If its good for server im can reopen my ticket

**Comment by TranceAccount** [comment]
@IamtheLexx said that he couldn't hand in the quest either, so I think you can reopen this thread.

**Comment by Holycowitstaurenpaladin** [comment]
no problem.Reopening...
