### ISSUE TITLE
[EN] [QUEST] Combat Training (ALLIANCE)

### ISSUE THREAD

**Issue by JustAnotherDisgrace** [Atlantiss/BugTracker#9077]
Unable to speak with Gory.

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
[wowhead](http://www.wowhead.com/) or [cata.openwow.com](http://cata.openwow.com/) links

use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
