### ISSUE TITLE
[EN][Spell] Bloodlust doesn't stack and overrides other 5% haste buffs from auras.

### ISSUE THREAD

**Issue by PolpoVolante** [Atlantiss/BugTracker#9078]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Bloodlust doesn't stack with other 5% haste buffs (wrath of air, moonkin aura, shadow aura)

**Current behaviour**: 
If I have any of the 5% buffs above and I use bloodlust those buffs will be dispelled even for example moonkin aura or spriest aura on the druid/priest.

**Expected behaviour**: 
5% haste buff and bloodlust should stack together.

**Steps to reproduce the problem**:

1.  get 5% haste buff
2.  use bloodlust
3.  see buffs

**Revision**: 5357

**Comment by PolpoVolante** [comment]
Can get screenshots if needed but honestly there is no need.

**Comment by Piklo** [comment]
#8961

**Comment by Trollpowah** [comment]
https://youtu.be/k7ToVHYtUWE

Pay attention to haste values after Heroism. Wrath of Air totem isn't even on the buffs bar, neither doesn't give proper ammount of haste.

**Comment by Prodiege** [comment]
Already reported

**Comment by Jenovas** [comment]
Fixed in rev 5431
