### ISSUE TITLE
[EN][Web] Quartermaster's Satchels

### ISSUE THREAD

**Issue by Sepherzuck** [Atlantiss/BugTracker#9079]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: You don't need to be 'Revered' with the faction to use the satchels provide by the quartiermasters.

**Current behaviour**: I bought the Undercity satchel without being revered and I could use it. I did the same with Silvermoon, Orgrimmar and Darkspear trolls ones.

**Expected behaviour**: Not be able to use them.

**Steps to reproduce the problem**:

1. I bought one without being 'Revered'
2. I tried to use it
3. It was possible.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
#4358

**Comment by TranceAccount** [comment]
How is this related to [Web]?

**Comment by Piklo** [comment]
duplicate #4358
