### ISSUE TITLE
[EN][Spell][Warlock] Backlash

### ISSUE THREAD

**Issue by moonsado** [Atlantiss/BugTracker#9081]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: 
http://cata.openwow.com/spell=47258           backdraft
http://cata.openwow.com/spell=34939           backlash

When you use instant shadow bolt or incinerate via backlash while having backdraft active - it consumes 1 stack of backdraft even though it's not supposed to. 

here's source: http://wowwiki.wikia.com/wiki/Backlash 
Quote: "Patch 3.2.2 (2009-09-22): When using Shadowbolt or Incinerate while having Backlash and Backdraft active, only Backlash will now be properly consumed."

**Current behaviour**: 
Using shadow bolt or incinerate via backlash consumes 1 stack of backdraft.

**Expected behaviour**: 
You should be able to use shadow bolt or incinerate via backlash consuming 0 stacks of backdraft.

**Steps to reproduce the problem**:

1. Get hit by melee.
2. Get backlash proc and use shadow bolt or incinerate.
3. Consume a backdraft proc.

rev. 5357

**Comment by moonsado** [comment]
Notice me pls q_q..

**Comment by lamaATS** [comment]
Fixed in rev. 5498
