### ISSUE TITLE
[EN] [quest]Dalaran Infused Mushroom Meatloaf  Daily cooking quests(horde).Working or not?

### ISSUE THREAD

**Issue by Holycowitstaurenpaladin** [Atlantiss/BugTracker#9082]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
[//]: # ([EN][Quest][Zone]Dalaran Infused Mushroom Meatloaf;Sewer Stew;Mustard Dogs!;Convention at the Legerdemain;Convention at the Legerdemain;Сheese for glowergold.
[//]: # ([EN][NPC] Awilo Lon'gomba <cooking trainer>
wowhead link: http://www.wowhead.com/achievement=1783/our-daily-bread
I have visiting few times this npc and still no daily cooking quests.Im still cant understand quests dont working or i have some problems with my character.Forums,information says: to complete daily dalaran cooking quests you needed to be: 77 lvl (some sites says 75 or 76) and have cooking skill 350. I have 83 lvl character and cooking skill 391 and still no daily quests from trollboy Awilo.There is no blue 
Exclamation point above quest mob.Dear GM!If you will have time check please this 5 quests for cooking in dalaran.I want to see my cow in chef's hat.Thank you.May be i forget to add something but i dont remember.And its hard for me because my english knowlege is far from ideal.
![wowscrnshot_040417_103433](https://cloud.githubusercontent.com/assets/26832621/24646765/b097c796-1925-11e7-928f-6a2e9f43e50e.jpg)
ACore rev.5357 hash f895f588dcc8 2017-03-29 00:17:01 +0200 (4.3.4 branch) (Unix,RelwithDebInfo)

**Comment by Sayris9876** [comment]
The only reason not to get those quests is either you completed the fishing daily from Dalaran or you have a fishing daily quest in your quest log. From the quests I see on the screenshot you dont have any of those so did you complete fishing daily before making the screenshot? Also Waterlogged Recipe quest is alliance quest 1st you dont need it and cant complete it 2nd that might be the reason for you not getting cooking daily. Try to abandon it and see if anything changes.

**Comment by Holycowitstaurenpaladin** [comment]
thanks i will try

**Comment by Holycowitstaurenpaladin** [comment]
Yes i have completed daily fishing quest.I dont know why completing fishing quest is abandon my daily cooking quest

**Comment by Sayris9876** [comment]
For some reason you cannot do fishing and cooking from dalaran together. You have to pick which one you wanna do for the day

**Comment by Holycowitstaurenpaladin** [comment]
thats sad man

**Comment by Holycowitstaurenpaladin** [comment]
Yes i this quest finally appears today! But cooking for fishing.That just sad.In original wow the same situation?

**Comment by Anhaeyn** [comment]
Nope, it's just bugged here on ATS.

**Comment by Holycowitstaurenpaladin** [comment]
then i will keep this problem,dont want to close my ticket.May be it will be fixed someday

**Comment by Holycowitstaurenpaladin** [comment]
Now its working well i few times wisit dalaran and now you can do fishing and cooking the same time.Closing
