### ISSUE TITLE
[EN][Quest] Rite of vision

### ISSUE THREAD

**Issue by witijer** [Atlantiss/BugTracker#9083]
**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

//: # ([EN][Quest][Zone] Rite of vision, bloodhoof village in mulgore
//: # ([EN][NPC] Zarlman two-moons
wowhead link :http://www.wowhead.com/quest=20441/rite-of-vision

It's my first time doing a report if I did wrong, I apologize.
According to the addon they have in the page private status says that this mission is blizzlike but when you use the item you get the spirit wolf starts to attack the moobs around and sometimes crosses the floor even the wolf died and died in the void The mission if complete but not blizzlike if they could fix it please
![wowscrnshot_040517_232216](https://cloud.githubusercontent.com/assets/18519575/24736587/d1f920ec-1a56-11e7-9cba-857227c6e2f5.jpg)

**Comment by Piklo** [comment]
read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use) and follow our [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
