### ISSUE TITLE
[EN][RAID][FIRELANDS] Baeleroc - Shards of Torment Double Ticking

### ISSUE THREAD

**Issue by Prodiege** [Atlantiss/BugTracker#9085]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Sometimes [Shards of Torment](http://www.wowhead.com/spell=99259/shards-of-torment) apply the [Torment](http://www.wowhead.com/spell=142983/torment) debuff twice in the normal duration of one application

**Current behaviour**: Quite often the total number of [Torment](http://www.wowhead.com/spell=142983/torment) debuff stacks from a [Shard of Torment](http://www.wowhead.com/spell=99259/shards-of-torment) will be higher than 24, anywhere from 25 to 30 seen after one run

**Expected behaviour**: [Shards of Torment](http://www.wowhead.com/spell=99259/shards-of-torment) should apply the [Torment](http://www.wowhead.com/spell=142983/torment) debuff at a constant rate and end up outputting a total of 24 [Torment](http://www.wowhead.com/spell=142983/torment) debuffs through it's duration

**Steps to reproduce the problem**:

1. Fight Baeleroc
2. Have someone take [Torment](http://www.wowhead.com/spell=142983/torment) debuffs
3. Watch the stacks apply multiple times in the time one would normally apply

**Revision**: 5357

**Comment by Psychobird7** [comment]
We've had this happen tonight. Seems to be a fairly new bug, as I can't recall it happening in the past few weeks.          

Our Shadow priest was soloing a shard and ended up taking 29 applications instead of the expected 24, and died. Difficulty was 10H. 
Log here: http://www.worldoflogs.com/reports/el07l3gpshy2lor5/details/6/?s=81&e=277 
Go to "Buffs gained", search for "Torment", you'll see 29 applications. Click the # to the right of it, you'll notice they were all applied in one go.

**Comment by Aival94** [comment]
From what i saw the stacks on crystal can be between 24-30 stacks. I know we used to be on 24 fixated stacks but now either by accident or a fix we did not see now is working more randomly as was during retail.

I checked fatboss guide which had 27 stacks and the world first which had 28 stacks once.

**Comment by Aival94** [comment]
Is this one continue?

**Comment by stanq87** [comment]
#9912
