### ISSUE TITLE
[QUEST/NPC][EN] Cornered and Crushed! 

### ISSUE THREAD

**Issue by fujisaplan** [Atlantiss/BugTracker#9089]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I just took the quest cornered and crushed but when I go to master forteski at deep elem mine but I cant talk to him even though I need to talk to him for me to complete the quest and also progress the story of my undead rogue. The story of the forsaken cannot proceed without the completion of this quest meaning that a newly created forsaken would not even be playable to level 20+ unless the quest would be fixed.

**Current behaviour**: There is no quest marker above his head and i still cant talk to him

**Expected behaviour**: I should be able to talk to him and finish the quest

Links to the quest and npc: http://www.wowhead.com/npc=45228/master-forteski
                                            http://www.wowhead.com/quest=27194/cornered-and-crushed

**Comment by fujisaplan** [comment]
![d21](https://cloud.githubusercontent.com/assets/27050454/24826783/5cbd3b80-1c70-11e7-9906-a08ee06c1e4d.png)

**Comment by nekilik** [comment]
Confirmed, the NPC cannot be talked to.

**Comment by TranceAccount** [comment]
# Please follow our [_How to use?_](https://github.com/Atlantiss/BugTracker#how-to-use)
- Wowhead link to the quest and npc.
- Add [EN] at the start of your title.

Thanks in advance.

**Comment by Piklo** [comment]
#9087

**Comment by fujisaplan** [comment]
#9087 is different from this thread

**Comment by fujisaplan** [comment]
@TranceAccount sorry this is my first post here.

**Comment by fujisaplan** [comment]
fixed
