### ISSUE TITLE
[PL][Quest][Horde][Stonetalon Mountains] To Be Horde...

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#909]
Nie można porozmawiać z High Chieftain Cliffwalker w Cliffwalker Post
http://www.wowhead.com/quest=26115/to-be-horde quest "To Be Horde..."

**Comment by Angelo-DM-** [comment]
Comfirm! [Hoverlord Krom'gar](http://www.wowhead.com/npc=42106/overlord-kromgar) not move, not do anything.

How it shold work: [Video](https://www.youtube.com/watch?v=HdN5qSRguc0)
