### ISSUE TITLE
[EN][Quest] Hearts-is-hearts

### ISSUE THREAD

**Issue by witijer** [Atlantiss/BugTracker#9093]
**Description**: The kodo does not appear anywhere http://www.wowhead.com/quest=24620/hearts-is-hearts

**Current behaviour**: not appear

**Expected behaviour**: That should appear and that of the heart

**Steps to reproduce the problem**:

1. The kodo does not appear
2. not appear
3. That should appear and that of the heart

**Comment by Piklo** [comment]
change title, add revision

**Comment by Piklo** [comment]
duplicate #2902
