### ISSUE TITLE
[EN][Quest] Those Bears Up There

### ISSUE THREAD

**Issue by xmesaj2** [Atlantiss/BugTracker#9095]
**Description:**

Quest http://www.wowhead.com/quest=29161/those-bears-up-there is now currently completed upon taking without doing objectives.

Issue #7997 is not related and invalid

**Current behaviour:**

Quest is completed as soon as you taken it.

**Expected behaviour:**

You should climb the trees to grab bears http://www.wowhead.com/npc=40240/hyjal-bear-cub and throw them on trampoline to finish the quest objective.

**Steps to reproduce the problem:**

1. Take quest 
2. Do nothing 
3. Quest completed 

**Revision:** 5364

**Comment by Aival94** [comment]
I think you are kind of a little wrong. The quest you gave is the daily quest from Molten Front(last time i did it had the bug with the target try to reset itself) and is a 85 level quest [Thoose Bears Up There](http://www.wowhead.com/quest=29161/those-bears-up-there), while they one that is auto-completing is [The Bears Up There](http://www.wowhead.com/quest=25462/the-bears-up-there) which is a one-time quest which can be done when you are 80+ level and is reported on https://github.com/Atlantiss/BugTracker/issues/578.

If i am wrong sorry but have some time to do the daily molten front quest.

**Comment by xmesaj2** [comment]
Right. Different name and haven't found another report.
