### ISSUE TITLE
Character stack. It says "Cant do that while stunned". 

### ISSUE THREAD

**Issue by majuelite** [Atlantiss/BugTracker#9098]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:Character stack. It says "Cant do that while stunned". Nothing work - Repop, summons, bubles, hs, relogs etc. Character name is Defiblirator stacked in storm peaks.

**Current behaviour**: Cant do that while stunned

**Expected behaviour**: It should work normaly
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 4.3.4

**Comment by Piklo** [comment]
Ticket in game
