### ISSUE TITLE
[EN][Talent][Druid] Master Shapeshifter (buff missing)

### ISSUE THREAD

**Issue by Khangu** [Atlantiss/BugTracker#9100]
**Description**: Restoration Talent "Master Shapeshifter" has following description:

_Grants an effect which lasts while the Druid is within the respective shapeshift form._
_- Bear Form - Increases physical damage by 4%._
_- Cat Form - Increases critical strike chance by 4%_
_- Moonkin Form - Increases spell damage by 4%._
_- Tree of Life/**Caster Form** - Increases healing by 4%._

As we see it clearly states that 4% healing bonus buff should be applied when we are in Tree of Life OR Caster Form (default druid form). Description from WoW Wiki confirms it: _" increasing healing done in your **original Caster**/Tree of Life Form"_. But 4% healing buff appears only when shapeshifted into Tree of Life form.

WoW Wiki link: http://wowwiki.wikia.com/wiki/Master_Shapeshifter

**Current behaviour**: Talent "Master Shapeshifter" give 4% healing bonus buff ONLY when druid is shapeshifted into Tree of Life form.

**Expected behaviour**: *Talent "Master Shapeshifter" should give 4% healing bonus buff when druid is shapeshifted into Tree of Life form AND when druid has no form = original caster form.

**Steps to reproduce the problem**:

1. Pick "Master Shapeshifter" talent from Restoration talents.
2. Switch all of yours possible shapeshift forms.
3. See as you get Master Shapeshifter 4% bonus on Moonkin, Bear, Cat, Tree of Life but NOT on Caster form.

**Revision**: 5364

**Comment by TranceAccount** [comment]
Can you confirm this with healing proofs?
I believe it is normal that it doesn't show in human form.

https://web-beta.archive.org/web/20110903023803/http://www.wowhead.com:80/spell=48411
> By steelpony (5·16) on 2010/12/05 (Patch 4.0.3)
Buff shows up while shifted, but there's nothing there when in "caster" form so if there's a 4% buff I can't see it or tell a difference when healing...

**Comment by Khangu** [comment]
I can't se possibility to check it manually by simple spamming heals, since every form other than Tree automatically switches to Caster when trying cast heal and Tree itself heals stronger even without this buff. My report was based on missing buff icon and same values in healing spells tooltips after switching to other form (logically they should be lowered by this 4% in cat form for example).

**Comment by Jenovas** [comment]
There should not be a icon, the healing increase is a passive / invisible buff. Checked it many times in the past and it always worked. Closing topic.
