### ISSUE TITLE
[EN][Rumble in the Lumber... Mill][Stonetalon Mountains]

### ISSUE THREAD

**Issue by Thunderlmao** [Atlantiss/BugTracker#9101]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: You must find the key for Huntress Illiona's cage then free her. 

**Current behaviour**: The cage for Huntress Illiona is already open, so you can't free her and she is just standing in the cage. It happens when other players have already done the quest, usually a restart is the only way to fix it sadly, which shouldn't be the case.

**Expected behaviour**: This guide shows clearly what should happen: https://www.youtube.com/watch?v=YmPSpNlFYvY

**Steps to reproduce the problem**:

1. Start the quest from her,
2. Kill the NPC for the key,
3. Use the key on her cage, which doesn't work.

**Revision**: Current server version: http://i.imgur.com/lgP5uPB.png

**Comment by Kiperr** [comment]
Fixed in rev 05389.
