### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Teron Gorefiend, I am... - there is no reward for complete

### ISSUE THREAD

**Issue by pariskaravidas** [Atlantiss/BugTracker#9102]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The quest: www.wowhead.com/quest=10639/teron-gorefiend-i-am
is suppose to give one of the following rewards and its not:
http://www.wowhead.com/item=31104/evokers-helmet-of-second-sight
http://www.wowhead.com/item=31109/stealthers-helmet-of-second-sight
http://www.wowhead.com/item=31106/stalkers-helmet-of-second-sight
http://www.wowhead.com/item=31110/druidic-helmet-of-second-sight
http://www.wowhead.com/item=31107/shamanistic-helmet-of-second-sight
http://www.wowhead.com/item=31105/overlords-helmet-of-second-sight
**Current behaviour**: What happens
You coplete the quest and there is no reward.
**Expected behaviour**: What should happen instead
When you speak to the npc in the respected faction hold he should rewards one of these items.
**Steps to reproduce the problem**:

1. Complete the chain quest.
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
Posted fix on forum:

https://community.atlantiss.eu/index.php?/topic/14532-teron-gorefiend-i-am-rewards/
