### ISSUE TITLE
[//]: # ([EN][Quest][Zone] Seek Nelthraku)

### ISSUE THREAD

**Issue by moeh2415312** [Atlantiss/BugTracker#9103]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] Seek Nelthraku)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Speak with Nelthraku

**Current behaviour**:When im doing the quest where you have to ''seek'' Nelthraku i cannot find the big ass dragon the question mark symbols is there but the Npc is missing

**Expected behaviour**: Npc Nelthraku should appear

**Comment by MichaelArchangelo** [comment]
He's there, just not exactly where the map suggests he is. Btw. add wowhead links on your issues.
