### ISSUE TITLE
[EN][Quest][Stonetalon Mountains] Reinforcements...)

### ISSUE THREAD

**Issue by Cerms** [Atlantiss/BugTracker#9104]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Subdue 6 kobolds, by whiping them.

**Current behaviour**: The kobolds cannot be subdued, even after many, many lashes.

**Expected behaviour**: The kobolds should be able to be subdued after 1-3 lashes.

**Steps to reproduce the problem**:

1. Accept the quest [Reinforcements...](http://www.wowhead.com/quest=26066/reinforcements) from [Subjugator Devo](http://www.wowhead.com/npc=42023/subjugator-devo) located at Malaka'jin, south east of Stonetalon mountains
2. Travel to Boulderslide Ravine
3. Attempt to subdue a [kobold](http://www.wowhead.com/npc=11915/boulderslide-rock-keeper), by using [Subjugator Devo's Whip](subjugator-devos-whip) on them.

**Revision**: ACore rev. 5465 hash. b808be466b67 2017-04-12 00:53:03 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Kiperr** [comment]
Fixed in rev 05389.
