### ISSUE TITLE
[([EN][Quest][Dire Maul] Pusillin The Thief

### ISSUE THREAD

**Issue by alukkard** [Atlantiss/BugTracker#9105]
**Description**: Convince Pusillin to give up the Book of Incantations.

**Current behaviour**: the [imp](http://www.wowhead.com/npc=14354/pusillin#comments) doesn't speak with the player. 

**Expected behaviour**: After speak with the [imp,](http://www.wowhead.com/npc=14354/pusillin#comments) he follows the player and attacks in a specific point to drop [Book of Incantations.](http://www.wowhead.com/item=18261/book-of-incantations) 

**Revision**: ACore rev. 5365 hash. b808be466b67 2017-04-12 00:53:03 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by 1Andas** [comment]
Confirmed bug. 

Side note, he also drops a cooking recipe some collectors might be interested in that counts towards achievement of Iron Chef (Although it's still possible to do it without Pusillin's recipe).

**Comment by liran11** [comment]
https://github.com/Atlantiss/BugTracker/issues/8193
