### ISSUE TITLE
Fizz Lighter in the starter area is bugged

### ISSUE THREAD

**Issue by Hr46ph** [Atlantiss/BugTracker#9106]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Fizz Lighter, the Mage Trainer in the Goblin starter area is bugged. When I interact with him, I can start a convo about some arcane thing, but I can't train anything. Clicking the info for arcanery doesn't do anything.

**Current behaviour**: What happens
Interacting with Fizz Lighter opens a dialog with a link for arcane info, but it doesn't work so I am never able to train in the starter area.

**Expected behaviour**: What should happen instead
Be able to interact, get the info for arcane he offers, and be able to train.

**Steps to reproduce the problem**:

1.  Level a mage
2.  be sent to the trainer
3.  interact with fizz lighter and observe the above problem

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Hr46ph** [comment]
If you explain why it is invalid I might be able to provide a better bug report.

**Comment by Piklo** [comment]
i think wowhead links

**Comment by Hr46ph** [comment]
Wut?

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
"Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com"
