### ISSUE TITLE
[EN][Spell][Deathknight] Death Grip

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9107]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Death Grip is not working sometimes, standing near LoS

**Current behaviour**: Enemy is getting a Debuff from Death Grip but not getting moved to the right point (=my position)

**Expected behaviour**: Getting moved to my position

**Steps to reproduce the problem**:

1. Run towards an enemy player while he is standing near a LoS position
2. use Death grip while he is near LoS or running around it.
3. Cry while you see him not getting gripped

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
wowhead links, add revision

**Comment by lamaATS** [comment]
@Heroclassx Can you provide video and/or place where this bug exist. It will allows me to validate bug and check fix when will be created.

**Comment by Heroclassx** [comment]
Sure, streamed some 3v3 yesterday and it didnt work from time to time, gonna try to find the parts later. Ty for your effort!

**Comment by Heroclassx** [comment]
Sorry took me a while, didnt wanna rewatch 4 hours of footage to find the spot.

Just played some 2s games, this happend in the second game.

https://www.twitch.tv/videos/176893722

**Comment by liran11** [comment]
https://github.com/Atlantiss/BugTracker/issues/8318
