### ISSUE TITLE
[EN] [Spell] [Deathknight] Anti-Magic shell

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9109]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: AMS generates Runic power while beeing attacked with spells when AMS is active.

**Current behaviour**: It does generate runic power but to less.

**Expected behaviour**: Should be generating about 2-3 times the amount it is currently.

**Steps to reproduce the problem**:

1. Find any Caster (mage, warlock, et cetera)
2. Let him cast non physical spells on you
3. use AMS before the spells hit you and watch your runic power bar

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Jenovas** [comment]
Please show some proof. Some calculations.

**Comment by Aival94** [comment]
sorry if understood wrong but Runic Power should only be generated by the use/depletion of runes with Offensive spells. AMS is not either an offensive spell or an ability which use runes. Other than that as far as you are not in combat runic power should slowly be depleted.

Proof: "Only by spending some of these runes (each of which regenerates after a short time) on battle spells may the death knight thereby acquire and incrementally build up for a short time runic power, which in turn he or she may draw on for other spells." - Source: [Runic Power](http://wow.gamepedia.com/index.php?title=Rune_system&oldid=2987235)

**Comment by Heroclassx** [comment]
I think you missunderstood me, might be because of my bad explanation, sorry:

AMS absorbs the magic damage you gain and converts it into runic power.

This is working atm but as far as I know it does far to less.

I dont know how i should proof it, i looked for 2 Hours for a calculation for the runic power generation via AMS but didnt found one. I can only upload a video from other private servers where it does work and gives a correct amount of runic power, but i dont know if that counts as proof

**Comment by codernk** [comment]
1) We should get back ~20% of the absorbed damage as runic power.  (int32 bp = absorbAmount * 2 / 10;)
2) I think it's Magic Suppression talent bugged. Second part: Increases the spell damage absorption of your Anti-Magic Shell by an additional 25%, **and increases the Runic Power generated when damage is absorbed by Anti-Magic Shell**.

https://web.archive.org/web/20120604001742/http://www.wowhead.com:80/spell=49611#comments

**Comment by Heroclassx** [comment]
That could be the problem because blood and Frost runic power regeneration is fine, it is just Unholy which is to low. 

I think you are right, thank you for that :) I hope you guys fix that soon.

**Comment by Jenovas** [comment]
20% of DMG taken? So taking 500 DMG should give you 100 Runic Power? Are you sure? Didn't you mean 2%?

**Comment by codernk** [comment]
Sounds weird. After patch 6.0.2 talent was nerfed to:
AMS generates 2 Runic Power for every percent of maximum health absorbed.
Actually it was nerfed twice till 6.0.2 
http://www.arenajunkies.com/topic/250107-anti-magic-shell-rp-soaking-rip/

**Comment by codernk** [comment]
Look at 2:38 https://www.youtube.com/watch?v=zNQiw69IveY
Arcane blast refunds 54 Runic Power.  Arcane Barrage 40 RP.
Not even close to atlantiss.

**Comment by lamaATS** [comment]
Currently each rank has same formula for Runic Power generation but it will be changed. After 3 hours of calculation I found formula which is in 99% cases correct and it's based on rank and DK's level (level is required because on each player has different amount of health).

**Comment by lamaATS** [comment]
According to @codernk video damage for each Runic Power Generation was:
* `Arcane Blast` for 20655 damage and generated 54 RP
* `Arcane Barrage` for 15300 damage and generated 40 RP
* `Arcane Blast` for 363375 damage (probably crit) and generated 54 RP

This shows how new formula will work.

**Comment by lamaATS** [comment]
Fixed in rev. 5510
