### ISSUE TITLE
[PL][Quest][Horde][Northern Barrens] Investigate the Wreckage

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#911]
Brak dalszej czesci chaina po sprawdzeniu co sie stało z karawana.
http://www.wowhead.com/quest=14066 quest "Investigate the Wreckage"

**Comment by Haffyd** [comment]
Sprawdzałem Twoj sposób latania nad ale nic nie zalicza.

**Comment by Bildo** [comment]
quest dziala
