### ISSUE TITLE
[EN] [Spell] [Deathknight] Dark Simulacrum

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9110]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Dark Simulacrum should copy any spell that costs mana. 

**Current behaviour**: It does copy most spells but not every

**Expected behaviour**: Copy the spells it should (for example Ring of Frost, it is just an example there are other spells too, like Power word: barrier)

**Steps to reproduce the problem**:

1. Find a Mage
2. Use Dark Simulacrum on Mage
3. Let mage use Ring of Frost while Dark Simulacrum is up

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by codernk** [comment]
Cast Dark Simulacrum on pally. Cast Bone Shield. Pally copied **your** bone shield. Happened to my holy paladin in BG several times.

**Comment by Heroclassx** [comment]
http://www.arenajunkies.com/topic/177503-the-dark-simulacrum-list/

There is a list with all spells which should be possible in Cata.

**Comment by lamaATS** [comment]
Fixed in rev. 5510
