### ISSUE TITLE
[EN] [Talent] [Deathknight] Summon Gargoyle

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9111]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Gargoyle is an undead Minion and should be immune to Priest psychic scream and warriors intimidating shout. (btw ghul is immune to that spells, dont know why gargoyle isnt) 

**Current behaviour**: Gets feared by psychic scream and intimidating shout

**Expected behaviour**: not getting feared by these spells

**Steps to reproduce the problem**:

1. Find Priest / Warrior
2. Summon Gargoyle
3. let them use psychic scream / intimidating shout

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14116-9111-summon-gargoyle/

**Comment by Heroclassx** [comment]
Thank you :)
