### ISSUE TITLE
[EN] [Spell] [Deathknight] Dark Simulacrum + AMS

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9112]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Imagine you are fighting a Druid, he is trying to use cyclone at you. You want to copy it but not getting hit by it. You will use Dark Simulacrum to copy that spell and also will use AMS to not getting hit by it.

**Current behaviour**: If spell is immuned by AMS you wont copy that spell, game thinks he didnt cast that spell

**Expected behaviour**: You should be able to copy that spell even though you immuned that spell with AMS, not sure if the same problem occours when using a spell against an ice block or divine protection

**Steps to reproduce the problem**:

1. let a Druid cyclone / Mage sheep / warlock fear et cetera
2. put Dark Simulacrum on the enemy before he finish the cast 
3. also use AMS before the cast is finished

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by lamaATS** [comment]
Fixed in rev. 5510
