### ISSUE TITLE
[EN] [Item] Book "Portals are NOT garbage Bins!" doesnt have text.

### ISSUE THREAD

**Issue by CatchmeATS** [Atlantiss/BugTracker#9113]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Missing text of a book called: Portals are NOT garbage Bins!

**Current behaviour**: Missing text of a book called: Portals are NOT garbage Bins!

**Expected behaviour**: Book should have a text to read. http://www.wowhead.com/object=192884/portals-are-not-garbage-bins

**Steps to reproduce the problem**:

1. Go to Dalaran.
2. Find the book.
3. Read it.

**Revision**: 5371

**Comment by Kiperr** [comment]
Fixed in rev 05389.
