### ISSUE TITLE
Impossible to get Stranglekelp

### ISSUE THREAD

**Issue by kalashnikov96** [Atlantiss/BugTracker#9114]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. I'm an alchemist and I need the plant Impossible to get Stranglekelp
2. I have searched them in the cities that according to wowhead are and do not appear
3. I hope they solve it :D

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by SwimzwithSharkz** [comment]
They are where they are supposed to be, along coastlines.
I am gathering them now on the West Coast of Wetlands.
( I came here to be certain my Memory was correct. )

**Comment by Khangu** [comment]
Straglekelp can be found only near water and more often underwater.
