### ISSUE TITLE
[EN][Raid][Firelands] Ragnaros 4th phase Deluge

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#9115]
**Description**: Deluge has a delay of 0.5 up to 1 second on clearing dreadflames.

**Current behaviour**: Deluge has a delay of 0.5 up to 1 second on clearing dreadflames upon stepping on it, and causes you to wait inside every individual patch of dreadflames.

**Expected behaviour**: [Upon stepping onto dreadflame deluge should clear it with no delay.
](https://youtu.be/AuqIcepONvQ?t=8m56s)
**Steps to reproduce the problem**:

1.  Start Ragnaros Heroic Encounter
2.  Get to phase 4 and grab the cloudburst
3.  Try to clear some dreadflames

http://www.wowhead.com/spell=100757/deluge
http://www.wowhead.com/spell=100713/deluge

**Revision**: 5371

Note: How TF is this not reported.

**Comment by Smiite** [comment]
HEEEEEELLLLLLLLLLLOOOOOOOOOOOOOOOOO STILL WAITING,RAG 25HC TOO EASY WITH THIS DELAY

**Comment by xolon** [comment]
Apparently fixed with rev. 5450
Please someone report how it's working & I'll close the issue. Thanks Pelekon!

**Comment by xolon** [comment]
I can confirm that deluge works properly. Thanks again Pelekon!
