### ISSUE TITLE
[EN][Raid][Firelands] Ragnaros 4th phase Cloudburst

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#9116]
**Description**: Cloudburst is scripted totally wrong, you should be able to click on it to get deluge and not just enter it or be close to it.

**Current behaviour**: Instead of being able to click the Cloudburst you have to go inside of it to get deluge.

**Expected behaviour**: [Cloudburst should be clickable
](https://youtu.be/AuqIcepONvQ?t=8m47s)
**Steps to reproduce the problem**:

1. Start Ragnaros heroic encounter
2. Reach phase 4
3. Try to click on the cloudburst

http://www.wowhead.com/spell=100714/cloudburst

**Revision**: 5371

**Comment by pelekon** [comment]
Posted fix on forum: https://community.atlantiss.eu/index.php?/topic/14076-9116-ragnaros-hc-cloudburstdeluge/#comment-66387

**Comment by xolon** [comment]
Fixed, thanks Pelekon.
