### ISSUE TITLE
[PL][QUEST][Mount Hyjal] The Last Living Lorekeeper

### ISSUE THREAD

**Issue by hirumka** [Atlantiss/BugTracker#912]
http://www.wowhead.com/quest=25830/the-last-living-lorekeeper - Brak możliwości oddania q gdyż npc znika podczas zbliżenia do niego.

**Comment by mitim1** [comment]
Bump!

**Comment by Murmaider** [comment]
bump, nadal to samo

**Comment by iprotocol** [comment]
still in effect. prevents any further leveling in zone

**Comment by Tj20** [comment]
Regarding this issue, I've read in the [forum](http://atlantiss.eu/community/viewtopic.php?f=22&t=425&p=1996&hilit=lorekeeper#p1996):

> At some point everyone in Hyjal gets stuck on the quest chain by some phasing bug. In order to fix it, you need to open a ticket and wait for a GM to fix it for you. After that you should have enough working quests to even be able to get the Hyjal Quests achievement.
