### ISSUE TITLE
[PL][Quest][Stranglethorn Vale] An Unusual Patron

### ISSUE THREAD

**Issue by Akio501** [Atlantiss/BugTracker#9120]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Używając quest itema jesteśmy w stanie przywoływać bez końca bossa. Odpalając multiboxa na 3 kontach, crash servera to kwestia paru minut.

**Current behaviour**: Quest działa poprawnie.

**Expected behaviour**: -

**Steps to reproduce the problem**:

1. Wprowadzić cd na quest itema, lub żeby boss znikał po minucie

**Revision**: 5371

**Comment by Kiperr** [comment]
Fixed in rev 05389.
