### ISSUE TITLE
[EN][Raid] Ragnaros: Breadth of Frost

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9122]
**Description**: Breadth of Frost currently does not have its intended effects on Living Meteors. 
http://www.wowdb.com/spells/100567-breadth-of-frost

**Current behaviour**: Breadth of Frost should increase the Living Meteors' damage taken by 50%.

**Expected behaviour**: Breadth of Frost does not increase the Living Meteors' damage taken, making them impossible to kill on 25H. 
edit: Effect is apparently also missing on 10H, though far less critical. 

**Steps to reproduce the problem**:

1. Go into FL. Engage Ragnaros 10H/25H
2. Freeze a meteor
3. Check its damage taken. 

**Revision**: 5371

**Comment by Malylolek** [comment]
Also missing at 10 man.

**Comment by Piklo** [comment]
still bugged after [rev5445](https://atlantiss.eu/changelog/2#rev5445)?
