### ISSUE TITLE
[EN][Rogue][Spells] Kidney Shot

### ISSUE THREAD

**Issue by Govanceros** [Atlantiss/BugTracker#9124]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Kidney shot sometimes doesn't last corresponding to the amount of combo points consumed
**Current behaviour**: What happens
When Kidney Shot is used with lets say 3 combo points, instead of lasting 4 seconds, it lasts 1 second
**Expected behaviour**: What should happen instead
The enemy should be stunned for a period of time corresponding to the amount of combo points consumed
**Steps to reproduce the problem**:

1. Fill combo points
2. Cast "Kidney Shot"
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Isn't it just because of http://wow.gamepedia.com/Diminishing_returns ?

**Comment by WarriorBugFinder** [comment]
Yes thats diminishing returns.
