### ISSUE TITLE
[EN][Deepholm, Realm of Earth][Deepholm]

### ISSUE THREAD

**Issue by Forrestwl-l** [Atlantiss/BugTracker#9128]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: While flying down into the Maelstrom I accidentally kicked myself off the mount, fell through the world, and died.  I instantly respawned in Org and found that the portal was no longer there, and I couldn't get it back.

**Current behaviour**: Nothing

**Expected behaviour**: Farseer Krogar will open another portal for me.

**Steps to reproduce the problem**:

1. Go to Deepholm
2.  Take the quest from Thrall
3. Get yourself kicked off the mount while flying into the Maelstrom

**Revision**: 5371

**Comment by Piklo** [comment]
If you want faster help, open a ticket on game

**Comment by Aival94** [comment]
reported/related: https://github.com/Atlantiss/BugTracker/issues/5446, https://github.com/Atlantiss/BugTracker/issues/3104, https://github.com/Atlantiss/BugTracker/issues/645

**Comment by Forrestwl-l** [comment]
I did that as well and it's been resolved, just thought I'd report it here
too, thanks.

**Comment by AngryEndUser** [comment]
Happened to me as well, what I did was I bought a [Potion of Deepholm](http://www.wowhead.com/item=58487/potion-of-deepholm) of the auction house and used it to get there.
