### ISSUE TITLE
[PL][NPC] KTC Train-a-Tron Deluxe <Professions Trainer & Vendor>

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#913]
Zgodnie z nawą prócz nauczania powinien też sprzedawać Przedmioty do Profesji, ale on tylko uczy tych profesji ;/

Link: http://www.wowhead.com/npc=45286/ktc-train-a-tron-deluxe

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/15537-npc-ktc-train-a-tron-deluxe/

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
