### ISSUE TITLE
Windshear quest "Commandeer That Baloon!"

### ISSUE THREAD

**Issue by Szwajcarek** [Atlantiss/BugTracker#9131]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
Here is a link for the quest from wowhead: http://www.wowhead.com/quest=25652/commandeer-that-balloon

**Description**:
Well it is quest in the Windshear and i cant do it because of glitch
**Current behaviour**: 
The baloon doest appear and you cant do the main quest
**Expected behaviour**: 
The baloon should appear and we should do this quest
**Steps to reproduce the problem**:

1. Just go near to the windshear mines and take quest from a guy named "Boog the "gear whisperer""
2. He gives you quest and its showed on map where you should go
3. You go there and there is no baloon

**Revision**: 
ACore rev 5377, hash 82ed4a08bc04

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1257
