### ISSUE TITLE
[EN] [Quest] [Northern Barrens] Raging River Ride

### ISSUE THREAD

**Issue by Xiondar** [Atlantiss/BugTracker#9134]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In the quest "Raging River Ride", after the boat gets to it's destination and you are ejected from it, you end up falling through the world and dying.

**Current behaviour**: You fall through the world after exiting the boat.

**Expected behaviour**: After exiting the boat, you can then walk and complete the quest.

**Steps to reproduce the problem**:

1. Accept the quest from Ratchet
2. Take the boat for the quest
3. Ride the boat to its destination

**Revision**: 5393
![capture](https://cloud.githubusercontent.com/assets/28207325/25714210/40bf9d06-30c5-11e7-9489-e010d89a774e.PNG)

http://www.wowhead.com/quest=26769/raging-river-ride

**Comment by GrumpFirefly** [comment]
link added

**Comment by xmesaj2** [comment]
#4181
