### ISSUE TITLE
[EN] [Quest] [Northern Barrens] Miner's Fortune

### ISSUE THREAD

**Issue by Xiondar** [Atlantiss/BugTracker#9135]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After looting the "Cats Eye Emerald" quest item, you are supposed to turn in the quest. But the quest giver doesn't have the quest listed for turn in.

**Current behaviour**: Cant turn in quest after looting quest item.

**Expected behaviour**: You should be able to turn  in the quest to "Brak Blusterpipe".

**Steps to reproduce the problem**:

1. Accept "Miner's Fortune"
2. Loot the emerald
3. Try and turn in the quest

**Revision**: 5393
![catseye](https://cloud.githubusercontent.com/assets/28207325/25717487/9b9e7aa2-30d0-11e7-90fd-e539f74b24c9.png)

http://www.wowhead.com/quest=29015/miners-fortune

**Comment by TranceAccount** [comment]
Could you add wowhead links to your reports?
Thanks in advance.

**Comment by GrumpFirefly** [comment]
@TranceAccount Hopefully thats what you meant. :)

**Comment by TranceAccount** [comment]
Yeah, thank you. Could you also add the quest link to #9134?

**Comment by Khangu** [comment]
It seems there was some problem in quest conversion to cata. Pre-cata this quest was accepted and turned in Ratchet, near ship sailing to BB. Some time ago I picket it and turned to 2 different NPC's.

**Comment by TranceAccount** [comment]
@Khangu do you remember those NPCs their names?

**Comment by xmesaj2** [comment]
Cannot reproduce, the NPC shows question mark to hand in quest normally

**Comment by aholler2** [comment]
You can turn this into Wharfmaster Dizzywig in Ratchet.
