### ISSUE TITLE
[EN][Npc][Drop] Leotheras the Blind (Updated 5/10/2017)

### ISSUE THREAD

**Issue by Guntrix** [Atlantiss/BugTracker#9138]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: This particular boss is suppose to drop hand tokens for Tier 5 sets and other loot drops. Prior to this week's drop loot, it did not drop anything other than gold. If this is a bug, please someone look into this since I already have reported this as a ticket but I would like for it to be permanently fixed.

**Current behavior**: Does not drop hand tokens and or other loot in some cases, or in this case, nothing at all.

**Expected behavior**: A fixed loot table.
4/26/2017

![wowscrnshot_042617_013214](https://cloud.githubusercontent.com/assets/28435100/25740744/c78f4bc0-3155-11e7-8d00-aa69dab2cd4c.jpg)

5/3/2017

![wowscrnshot_050317_114850](https://cloud.githubusercontent.com/assets/28435100/25740750/ce4e021c-3155-11e7-83df-f0b048bfe32e.jpg)

5/3/2017 - Same day but with a different character.

![wowscrnshot_050317_120109](https://cloud.githubusercontent.com/assets/28435100/25740757/d3480e0c-3155-11e7-83c1-1af3778d3dd1.jpg)

PS. Here's an update, again the same issue, no hand tokens dropped. 5/10/2017

![wowscrnshot_051017_165033](https://cloud.githubusercontent.com/assets/28435100/25920888/5e64fcc6-35a1-11e7-97b8-c4e930ce3cbc.jpg)

5/10/2017 - Again, same day, different character, and again, no tokens.

![wowscrnshot_051017_180643](https://cloud.githubusercontent.com/assets/28435100/25923520/e58f3144-35ab-11e7-9030-a1096406b835.jpg)

**Comment by MellenIO** [comment]
The hand tokens drop at around 75% rarity (ie not all the time). It's possible that you just got extremely unlucky.

**Comment by Piklo** [comment]
i posted fix some time ago but we have to wait until bildo will accept it
https://community.atlantiss.eu/index.php?/topic/13677-ahnqiraj-temple-ruins-of-ahnqiraj-karazhan-serpentshrine-cavern-tempest-keep-the-battle-for-mount-hyjal-boss-loot-tables/

**Comment by fluessig** [comment]
wtf was this then?

http://atlantiss.eu/changelog/9
Serpentshrine Cavern boss loot tables

did u just forget some bosses or what?
i remember going into SSC after those were up
and looting ONLY gold from leotheras
no hate btw just curious what went wrong

**Comment by Prodiege** [comment]
He posted original fixes but there were some overlooked errors and his most recent fix hopefully fixes his mistakes

**Comment by Guntrix** [comment]
I just seriously want to get my hand token and this has been going on for about three weeks prior before I posted this. I didn't record data for the attempts I have done, but you can clearly see there are not any tokens whatsoever. They should at least drop one from the boss instead of not dropping it at all, and only a 66% change to drop accordingly to what the difficulty is. So I have it set up for 25 man, meaning it will drop more items, but in my case, only gold I have received.

It's fine anyways. I was told by the GM that the next restart will have the boss's loot table fixed, and hopefully I will get something.

**Comment by Piklo** [comment]
who said that? @Guntrix

**Comment by Guntrix** [comment]
@Piklo Narilrave.

Here's his response from yesterday.

5/5/2017

![wowscrnshot_050517_064702](https://cloud.githubusercontent.com/assets/28435100/25776174/84a7c46e-3285-11e7-8cbf-ea7e3c8b2832.jpg)

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
