### ISSUE TITLE
[EN][NPC] Father Lazarus drops Cataclysm items?

### ISSUE THREAD

**Issue by MellenIO** [Atlantiss/BugTracker#9139]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When a member of the alliance kills [Father Lazarus](http://www.wowhead.com/npc=4608/father-lazarus) (one of the Priest Trainers in Undercity), he drops cataclysm items, including the BOP [Steelbender's Masterpiece](http://www.wowhead.com/item=56302/steelbenders-masterpiece)

Screenshots of his drops (tried it 3 times to make sure it wasn't just a one time glitch): http://imgur.com/a/lwyrs

**Current behaviour**: The trainer drops random Cataclysm items, including grey trash items and BOP blue items.

**Expected behaviour**: The trainer should not drop anything.

**Steps to reproduce the problem**:

1. Be alliance
2. Go to Undercity
3. Kill Father Lazarus
4. Loot him

**Revision**: ACore rev. 5397, hash 1b31284c6c58

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14120-npc-father-lazarus/

**Comment by Artamedes** [comment]
@TranceAccount lootid could be wrong too, better set to 0

**Comment by TranceAccount** [comment]
Lootid is okay, Bildo checked it for me.
Thanks for noting that tho. :)

**Comment by Artamedes** [comment]
It will make a DB error in console, but it probably wont matter

**Comment by xmesaj2** [comment]
rev. 5427 fix approved
