### ISSUE TITLE
[EN][Quest][Sholazar Basin] Rejek: First Blood

### ISSUE THREAD

**Issue by Pocketerino** [Atlantiss/BugTracker#9140]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In the quest http://www.wowhead.com/quest=12734/rejek-first-blood after throwing the quest item (Rejek's Blade) at one of the mobs youre supposed to throw it at after you kill them nothing happens and you dont get credit, the sword can be seen in the corpse of the mob tho. This makes http://www.wowhead.com/achievement=961/honorary-frenzyheart undoable.

**Current behaviour**: You dont get credit after using the quest item.

**Expected behaviour**: After killing a mob and throwing the quest item you should get credit towards completing the quest.

**Steps to reproduce the problem**:

1. Take the "Rejek: First Blood"quest.
2. Kill one of the mobs youre assigned to kill.
3. Use the quest item on its corpse.

**Revision**: 5397

Sorry for making a double didnt realize.

**Comment by Piklo** [comment]
#9042

**Comment by xmesaj2** [comment]
closing as duplicate
