### ISSUE TITLE
quest  [Angered Spirits] bug

### ISSUE THREAD

**Issue by killermommy** [Atlantiss/BugTracker#9142]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem  

 quest  [Angered Spirits] not working

**Current behaviour**: What happens

quest give me gun i should use it to the mob name Furios specter when he have 50% hp or less to be completed

**Expected behaviour**: What should happen instead

when i use the quest item to 5 mobs  Furios specter have 50% hp or less it should be complete

**Steps to reproduce the problem**:

1. take the quest
2. use quest item to Furios specter when he have 50% hp or less
3. try to complete it

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Correct the title and add links to wowhead.com related to quest and NPCs involved
https://github.com/Atlantiss/BugTracker#how-to-use
