### ISSUE TITLE
[ENG] [DK] [Glyph] Glyph of Death's Embrace

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9143]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: "Your Deathcoil refunds 20 Runic Power when used to heal an allied Minion."

**Current behaviour**: If Death Coil is used on my pet i will get the Runic power refunded. If used on myself (via Lichborne) it should also generate that amount of Runic power.

**Expected behaviour**: It should generate Runic Power if used on myself via Lichborne

**Steps to reproduce the problem**:

1. Generate 34 Runic Power
2. Use Lichborne
3. Use Deathcoil @ player

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
"Your Deathcoil refunds 20 Runic Power when used to heal an allied **Minion**."
I think you are not minion :P

**Comment by Heroclassx** [comment]
That is just a error in the description, it is working is used on other DK's which have Lichborne active.

+ It was working on retail and warmane, et cetera. Also posted on arenajunkies and skill-capped to be working like that as intended

**Comment by kadi2** [comment]
Just put a little bit effort in this bug report and post a videoproof

**Comment by Piklo** [comment]
If it was working on retail give proofs

**Comment by Jenovas** [comment]
You can find many notes on Blizzard forums / MMO / Wowhead and other sources that claim that somewhere at the start of Cata (4.0.3 - 4.0.6) the Glyph stopped rewarding RP when healing yourself.

If you find any proof that they turned it back on please create a new issue and add all the data there.
Cheers.

Closing issue.
