### ISSUE TITLE
[EN] [quest] [Zone] [Zul'Drak] Parachutes for the argent crusade [76 lvl]

### ISSUE THREAD

**Issue by Holycowitstaurenpaladin** [Atlantiss/BugTracker#9145]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:
http://www.wowhead.com/quest=12740/parachutes-for-the-argent-crusade

1. You starting your quest from En[npc] Commander Falstaav.He wants you to equip every argent crusader with a parachute.To complete quest you need to find friendly npc argent crusader.Click on your quest item crusader parachute and every time you doing this there is no progress at all.No count to completing quest.You can all day long choose npc,click on parachute. But quest is still 0/10.Im adding one more screenshot with server version because type all this letters so undertaking.
![wowscrnshot_050917_121945](https://cloud.githubusercontent.com/assets/26832621/25844004/d4535ad6-34b1-11e7-8487-7c5940d51b84.jpg)

![wowscrnshot_050917_121528](https://cloud.githubusercontent.com/assets/26832621/25843937/a14f6d8c-34b1-11e7-89e9-d8d7dff34af3.jpg)
![wowscrnshot_050917_121530](https://cloud.githubusercontent.com/assets/26832621/25843942/a5431e52-34b1-11e7-8d1c-d29d0424477d.jpg)

2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
should work after rev. 5403
