### ISSUE TITLE
[Western Plaguelands] Combat Training

### ISSUE THREAD

**Issue by Vyrus21** [Atlantiss/BugTracker#9149]
**Description**: I try to talk with "Gory" but nothing happened, it suppost to talk challenge him to combat.

**Current behaviour**: Not working.

**Steps to reproduce the problem**:

1. Put "Gory" able to talk to challenge him to combat.

https://www.youtube.com/watch?v=rLVmmJYrobQ

http://www.wowhead.com/quest=27174/combat-training

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Revision?

**Comment by Vyrus21** [comment]
No my friend dont work, the "Gory" if you try to talk to him, you dont have that option only click on him, nothing else.

**Comment by xmesaj2** [comment]
Ok I identified the problem, will add the fix with next update

**Comment by xmesaj2** [comment]
rev. 5413 - when it goes live it should be able to talk with him
