### ISSUE TITLE
[Western Plaguelands] Zen'Kiki and the Cultists

### ISSUE THREAD

**Issue by Vyrus21** [Atlantiss/BugTracker#9150]
**Description**: You open the cage, and its no bear inside like suppost to be, they are outside and "Zen'Kiki" can't heal them like suppost to do.

**Current behaviour**: Bugged

**Steps to reproduce the problem**:

1. Put the bears inside of the cages. 
2. http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists
3. https://www.youtube.com/watch?v=jNZoVs6SX5c

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
bump (rev. 5418)

**Comment by lomitoh** [comment]
When will this quest be fixed?

**Comment by kayze2012** [comment]
Confirmed bugged. Bears are now spawned, however, they're outside of the cages. He does not heal them even after you open the gates. 20180117 1415 MST

**Comment by Snake90** [comment]
The quest is still bugged.

2 problems :

1) When someone makes the quest after a restart / crash, the bears stay outside the cages as they should return for the next player.

2) Even if we do the quest after a restart / crash, it doesn't work : the cage opens, the bear comes out, Zen'Kiki is there but nothing happens, it doesn't cont for the quest.

**Comment by Snake90** [comment]
Still bugged
