### ISSUE TITLE
[EN][quest][Zone][Deepholm] Violent gale

### ISSUE THREAD

**Issue by Holycowitstaurenpaladin** [Atlantiss/BugTracker#9151]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
http://www.wowhead.com/quest=26426/violent-gale
I got some problems with that quest.Its quest for reputation with Therazane faction which makes this quest important.You starting this quest from [EN]NPC Diamant the patient.You take this quest and you need to do two steps.First find [EN]NPC Felsen the Enduring (this part of quest works like a clock)but second part buggy.You need to find your entrance to Crumbling depths.When you finding it quest marked as complete.You can see it on screenshot. But real problem is there is no npc who takes your quest back.I also watched this quest on youtube.https://www.youtube.com/watch?v=yrHsePGv9h0
I think this will be helpful.There is no npc for completing this quest.All you have to do just click on question mark right side of your screen and then quest will be completed.But no such question mark in this quest on Atlantiss.That makes the task impossible.Abandon and taking
![wowscrnshot_051117_091714](https://cloud.githubusercontent.com/assets/26832621/25935710/09f5992a-362d-11e7-8c40-8a8d7d4ae7a7.jpg)
![wowscrnshot_051117_092455](https://cloud.githubusercontent.com/assets/26832621/25935714/0fc7b252-362d-11e7-996b-d28c9159e464.jpg)
![wowscrnshot_051117_092909](https://cloud.githubusercontent.com/assets/26832621/25935716/157e3252-362d-11e7-8812-2cd34dbc836c.jpg)
 this quest again dosent helps.
Adding screenshot with server info.Thanks once again.
![wowscrnshot_051117_093543](https://cloud.githubusercontent.com/assets/26832621/25935756/45c6e8aa-362d-11e7-8dc2-1c87c2696489.jpg)

**Comment by meowmewo** [comment]
Before they close this report.  2 things.
1. Learn to make proper reports.
2. Go to the NPC location from the start of the chain, where there are 2 npcs, this guy, and one small one, not the place where you see on map.

**Comment by Fabiana-B** [comment]
Diamant is the one who complete your quest. (Yes, the questgiver).
He supposed to teleport to Crumbling Depths entrance, but not, he's stay on the same place you accepted the quest.
Come back to Diamant.

PD: Make a ticket and make sure the quest is bugged, before making a post here on the Bugtracker :p

**Comment by Holycowitstaurenpaladin** [comment]
ok i will try

**Comment by Holycowitstaurenpaladin** [comment]
Thanks its really works but on the youtube quest was done in different way.Closing.
