### ISSUE TITLE
[Eastern Plaguelands] Fiona's Caravan

### ISSUE THREAD

**Issue by Vyrus21** [Atlantiss/BugTracker#9152]
**Description**: Remove all Fiona's Caravan its to much caravans there is very confused.

**Steps to reproduce the problem**:

1. Remove Caravans
2. Leave 1 for the Quest

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
there are different caravans for different state of zone quests completed, it's normal
