### ISSUE TITLE
[EN] [Quest] [Silverpine Forest] Lordaeron

### ISSUE THREAD

**Issue by meatofit** [Atlantiss/BugTracker#9155]
Description: In the quest Lordaeron [http://www.wowhead.com/quest=27098/lordaeron] , the player is suppose to accompany Sylvanas Windrunner to the Sepulcher.

Current behaviour: The player mounts his horse at the beginning of the cinematic as Sylvanas starts talking but does not move onto the road in order to get to the Sepulcher. This causes the quest to be incomplete.

Expected behaviour: Sylvanus is suppose to ride with the player and dialogue starts about current times in Azeroth for the Forsaken until the player and Sylvanas reach the Sepulcher.

Steps to reproduce the problem:

1. Go up to Sylvanas Windrunner and accept the Lordaeron quest in Silverpine Forest
2. The cinematic will start playing
3. Nothing will happen from there

Revision: 5411

**Comment by BAndysc** [comment]
Fixed in rev 5414

**Comment by meatofit** [comment]
The current revision is 5412, so i'll patiently wait. Thank you very much and I love the Server =)
