### ISSUE TITLE
[EN][NPC][Stormwind] Rebecca Laughlin <Tabard Designer>

### ISSUE THREAD

**Issue by DuGalle** [Atlantiss/BugTracker#9161]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Tabard vendors are supposed to be able to restore missing tabards with a text dialogue option. Our dont have this option.

**Current behaviour**: When you talk to her only 2 things I want to browse and I want to create.

**Expected behaviour**: She should have options like : Restore Purple Tabard of the Ilidary

**Steps to reproduce the problem**:

1. Get some fancy tabard like Ilidary one from quest.
2. Remove it from your possessions 
3. talk to her to restore it for ya.

**Revision**: 5412

16

	
By AlexL1118 (7,577 – 1·12·47) on 2012/10/30 (Patch 5.0.5)		
Would be nice to see the full list of tabards that she can or can't restore after their deleting, such as:

Can restore (checked all of them myself):
- Arathor Battle Tabard
- Green Trophy Tabard of the Illidari
- Purple Trophy Tabard of the Illidari
- Tabard of the Achiever
- Loremaster's Colors
- Tabard of the Explorer
- Tabard of Brute Force
etc.

Can NOT restore:
- Scryers Tabard
- Tabard of the Argent Dawn (according to Salyna)
- Theramore Tabard (according to skyline33)
- Tabard of Conquest (according to adogsfanclub)
etc.

http://www.wowhead.com/npc=5193/rebecca-laughlin#comments

**Comment by 1Andas** [comment]
Theramore Tabard should not even be available for us here on Cata, should it? That's MoP content.

**Comment by wtRCH** [comment]
Theramore Tabard cannot be restored because It was added to the game in the next expansion - Mists of Pandaria.

**Comment by TranceAccount** [comment]
wowhead link

**Comment by TranceAccount** [comment]
Btw it is only this npc? wtf

**Comment by TranceAccount** [comment]
Should be fixed in rev 5843
