### ISSUE TITLE
[EN][Quest][Deepholm] Take Him to the Earthcaller

### ISSUE THREAD

**Issue by AngryEndUser** [Atlantiss/BugTracker#9162]
**Description**: In the quest [Take Him to the Earthcaller](http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller), you are supposed to take [Flint Oremantle](http://www.wowhead.com/npc=43036/flint-oremantle) (NPC) to [Earthcaller Yevaa](http://www.wowhead.com/npc=42573/earthcaller-yevaa) (another NPC) in the Temple of Earth in Deepholme.

**Current behaviour**: When you reach the Earthcaller, Flint Oremantle doesn't recognize her, keeps following you and the quest remains uncompleted. I've tried to fly, run and walk around her and near the entrance, relogging and reentering Deepholm. No matter what I do, I can't finish the quest. Other players are also stuck in this quest. I normally wouldn't bother about it too much but not doing this quest prevents me from doing the entirety of the remaining quests and dailies in Deepholm, including the Therezane faction.

**Expected behaviour**:  Flit Oremantle should enter dialogue with Earthcaller Yevaa and the quest should be completed.

Steps to reproduce the problem:

1. Take the quest.
2. Go to Temple of Earth.
3. Try to complete it.

**Revision**: 5412

**Comment by AngryEndUser** [comment]
Wait, I think a gm just fixed it lol.

**Comment by Piklo** [comment]
#7400

gm != dev
