### ISSUE TITLE
EN][Quest][Nagrand] Vision of the Dead

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9168]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: this quest is missing

**Current behaviour**: the NPC does not give the quest

**Expected behaviour**: What should happen instead is to resieve the quest

**Steps to reproduce the problem**:

1. locate the NPC
2. enjoy

**Revision**: Rev.5412

**Comment by xmesaj2** [comment]
links... http://www.wowhead.com/quest=10252
should be available after completing
http://www.wowhead.com/quest=10251/the-masters-grand-design

**Comment by xmesaj2** [comment]
![image](https://cloud.githubusercontent.com/assets/550384/26162041/e7c9b75c-3b25-11e7-9208-876dd4d3dfa7.png)

**Comment by aendry** [comment]
Oh :O thank you so much!

**Comment by aendry** [comment]
hey I'm doing this chain again and I notice that the quest [What Book? I Don't See Any Book.](http://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book) Is bugged and I can't do [the master's grand design](http://www.wowhead.com/quest=10251/the-masters-grand-design) also leads to even can't iniciate the Vision of the Dead quest...... so, you gonna autocompleat that quest for me? I don't know how you get there if that quest is bugged

**Comment by aendry** [comment]
re-open

**Comment by xmesaj2** [comment]
please make a separate issue for different quests and relate by a hashtag and issue number
