### ISSUE TITLE
[EN] [PVP] [Battleground&Arenas] [Quest] Alterac Valley - Coltdooth supplies

### ISSUE THREAD

**Issue by henkka90** [Atlantiss/BugTracker#9169]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: There are no coldtooth supplies found in coldtooth mine at Alterac Valley battleground for the quest for Coldtooth Supplies.

**Current behaviour**: Can't complete the Coldtooth Supplies quest, because there are no Coldtooth supply items

**Expected behaviour**: There should be boxes  that  you can loot, coldtooth supplies that you need to collect for the quest of Coldtooth Supplies
http://www.wowhead.com/quest=5893/coldtooth-supplies#comments
http://www.wowhead.com/item=17542/coldtooth-supplies#comments

**Steps to reproduce the problem**:

1. Enter alterac valley battleground
2. Accept the quest of Coldtooth supplies
3. Enter the Coldtooth mine and look for boxes

**Revision**: 5412

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14305-91699174-coltdooth-supplies-irondeep-supplies/

**Comment by Jenovas** [comment]
Fix in rev 5541
