### ISSUE TITLE
Hunter's Mark

### ISSUE THREAD

**Issue by onqgore** [Atlantiss/BugTracker#9177]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hunters mark spell (spell ID:1130) does appear to affect only the person who casted it on the boss.
**Current behaviour**: We have tested that in real raid environment and it seems only the hunter who casted it benefits from it, while all other hunters do not receive dmg bonus even though there is a mark on the target unless they cast it on the boss, but that apparently removes the first mark since only 1 mark can be active per target.
**Expected behaviour**:Hunters mark as well as all other similar effects should affect all players from the same class who benefit from that spell. We have tested that only for hunters mark, there might be other spells with similar effect which do not work properly. Maybe devastate/ sunder armor. We are still testing to prove that.

**Steps to reproduce the problem**:

1. For example with 3 hunters on one target.
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
maybe in your ui you see only debuffs casted by you?

**Comment by Psychobird7** [comment]
Server revision at the time of posting is 5417. 
Disregarding the incomplete report... 

Our hunters tested this in game 10min ago and were not able to reproduce the bug.     

/close, please.
