### ISSUE TITLE
[PL][Talent][Warlock] Demonic Rebirth

### ISSUE THREAD

**Issue by Wojteksc** [Atlantiss/BugTracker#918]
Jeśli mamy talent Demonic Rebirth (http://www.wowhead.com/spell=88448) i nasz demon zostanie zabity , następuje wtedy przerwanie castingu czaru u warlocka.

Dowód:
http://youtu.be/kAMOUHtjfic?list=PLvDxvkCgvtUYAUYIhVLlAEc2lNrC7IPKK

**Comment by Wolffenstein** [comment]
Fixed in rev 4320.
