### ISSUE TITLE
[EN][QUEST][Icecrown] The Admiral Revealed

### ISSUE THREAD

**Issue by podatekvat** [Atlantiss/BugTracker#9187]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: This is the ending quest in a long chain quest for Ebonblade Knights in Icecrown
http://www.wowhead.com/quest=12852/the-admiral-revealed

**Current behaviour**: NPC can be killed but quest doesn't recognize it so it can not be complited. Also he doesn't transform into Mal'ganis and he doesn't have a Protection Sphere on him in any time of the encounter.

**Expected behaviour**: Grand Admiral Westwind suppose to get a Protection Sphere buff at 50% hp. Then we suppose to use a quest item - "Lord-Commander's Nullifier" to dispell it from him so we can do damage on him again. At 45% he transforms into Mal'ganis. At 0,5% the battle ends and he escapes thru demon portal.

**Steps to reproduce the problem**:

1. Give this NPC a Protection Sphere at 50% which makes him immune to damage etc
2. After we use quest item on him the sphere disappears so we can damage him again
3. At 45% he changes into Mal'ganis 
4. We attack him untill he ends combat and escapes thru portal at 0,5% hp (or we kill him) which makes the quest completed

**Comment by TranceAccount** [comment]
# Please follow our [_How to use?_](https://github.com/Atlantiss/BugTracker#how-to-use)
- Wrong title.
- No wowhead link to the quest.

Thanks in advance.

**Comment by xmesaj2** [comment]
rev. 5425 fixed
