### ISSUE TITLE
[PL][Quest][Horde][Northern Barrens] Crossroads Caravan Delivery 

### ISSUE THREAD

**Issue by NONLIFE** [Atlantiss/BugTracker#919]
NIe akceptuje oddania q u Thork-a w The Crossroads 
http://www.wowhead.com/quest=13975  quest "Crossroads Caravan Delivery"

filmik: https://www.youtube.com/watch?v=JbO27vyMTmE

**Comment by siwy92** [comment]
nadal nie dziala .

**Comment by NONLIFE** [comment]
Jak bedzie dzialalo to bedziesz mial napisane a problem bedzie zamkniety

**Comment by Angelo-DM-** [comment]
Confirmed Bug! The quest http://www.wowhead.com/quest=13975 is bugged.
After you get the quest, you should talk with Rocco (the same NPC that gives you this quest) and as the precedent quest (much similar) http://www.wowhead.com/quest=13949, you should mount a kodo and escort it, but this time you need to reach Crossroads...

**Comment by Oxyntes** [comment]
yes, I have the same problem, I acquire the quest, but I can't talk to Rocco afterwards to get the Kodo to mount.

**Comment by xALSQ** [comment]
confirmed to not work, no dialog option available with Rocco to start the caravan

**Comment by Jokoga** [comment]
not working, the dialog option dont appear

**Comment by Dean1989** [comment]
the dialogue option to start the quest is still missing

**Comment by armano2** [comment]
duplicate: #3718
