### ISSUE TITLE
[EN][Quests][Burning Steppes] 

### ISSUE THREAD

**Issue by Braunschweider** [Atlantiss/BugTracker#9190]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Loot unavailable for quest "Scrapped Golems" http://www.wowhead.com/quest=28226/scrapped-golems

**Current behaviour**: You don't get quest loot

**Expected behaviour**: Get quest loot

**Steps to reproduce the problem**:

1. Go to mob
2. Kill mob
3. Not get loot

**Revision**: 5417 hash (4.3.4)

**Comment by TranceAccount** [comment]
Cannot reproduce on PTR.
@Braunschweider you know that the items you need to loot lie around on the ground and not in the corpse of the War Reaver?

**Comment by kayze2012** [comment]
This quest is working on main server. This quest needs to be closed. Golem will drop item on the ground, says it in the quest as well. Killed about 15 of them to get the final Stone Power Core.
