### ISSUE TITLE
delete my dk char

### ISSUE THREAD

**Issue by SirReza2** [Atlantiss/BugTracker#9196]
hello attlantis i maded an dk char and after first quest in start point i deleted my weapon and also sent him some money with mail by another my char now i want delete my dk char cuz i cant do anything without weapon and game do not let me to delete my char cuz i have an mail on it and there is no mail box in start point of dk plz delete my dk char plz 

atlantiss plz delete my dk char his name is Colazex plz delete it i can't delete it cuz he have an email but you can plz do it plz

**Comment by Sayris9876** [comment]
Everything you wrote is not for bugtracker. Either way there is one mailbox infront of a house where the horses are. Good luck
