### ISSUE TITLE
[EN][Spell][Aura][Aura Stacking] Flametongue totem buff (6% spell power) stacking with Demonic Pact (10% spell power)

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#9197]
**Description**: Currently the 6% spellpower buff given by a non elemental shaman via Flametongue totem (elem shamans give 10%), stacks with 10% spell power buff given by demonology warlocks (10% spellpower) and 10% spell power buff given by elemental shamans via the talent Totemic Wrath. Elemetal shaman (who has Totem Wrath) flametongue totem gives 6% + 10% spellpower AT THE SAME TIME.

**Current behaviour**: The buffs stack and give total of 16% spellpower increase.

**Expected behaviour**: The stronger buff aka  10% SP should overwrite the 6%. In the end you must only have 1 spell power buff and this should be the 10%, not both.

It seems that its a bug with Flametongue totem aura only, cuz the mage 6% SP buff gets overwritten properly. But for some reason, the flametongue 6% spell power buff just doesnt get overwritten and it stays aways up. This is NOT a visual bug. It really ends up being 16%.

**Steps to reproduce the problem**:

1. Make a demo warlock, summon pet to have 10% spell power buff (via talent Demonic Pact)
2. Group with shaman, put flametongue totem wich gives 6% spell power = you see how they stack.
3. Group with mage this time, buff intellect (also gives 6% spell power) = demonic pact overwrites it properly.
4. Also you can just make an elemental shaman, put a point in Totemic Wrath and put down Flametongue totem. The result is 2 buffs given by the totem, 10% and 6%, instead of only 10%. And both are active.

**Revision**: 5418

Ps. Would also just like to remind you, that the heroism aura STILL does not stack with 5% haste buff aura, and they should. Overall aura stacking really needs some work.

**Comment by Prodiege** [comment]
Does this also work if you are buffed with the 6% spellpower given by Arcane Brilliance from a Mage?

**Comment by ashrasmun** [comment]
bump

**Comment by pelekon** [comment]
fixed by lama
