### ISSUE TITLE
[EN][Spell][Item] Teracgosa's legendary staff + Seed of Corruption

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#9199]
**Description**: The staff doesnt proc of any damage, the initial nor the one after the explosion of the seed. And it should. Seed of corruption is the main source of AOE damage for affliction warlocks.

**Current behaviour**: Tyragosa's staff doesnt proc on seed of corruption damage.

**Expected behaviour**: It should proc.

**Steps to reproduce the problem**:

1. Make a warlock
2. Get legendary staff
3. Spam seed of corruption (affliction spell book) on as many targets as u want 24/7. You wont see a single copy.

**Revision**: 5418

PS. Its pretty much like the bug for demonology warlocks where Teracgosa doesnt copy Hellfire as well, wich is still bugged btw. Overall this leads to the staff not giving almost any benefits to warlocks in AOE heavy fights.

**Comment by ashrasmun** [comment]
This is not true and never was...

Proof from main (rev. 5434) on 3 targets:
Multiple staff procs on direct Seed of Corruption damage: http://i.imgur.com/Brb0ass.jpg
Multiple staff procs on Corruption damage from SoC: http://i.imgur.com/j1MNHRm.jpg

**Comment by meowmewo** [comment]
Where is the staff proc on the first pic?
