### ISSUE TITLE
[EN][Item][Howling Fjord]Mezhen's Writings

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9200]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Necro Overlord Mezhen](http://www.wowhead.com/npc=24018/necro-overlord-mezhen) should drop [Mezhen's Writings](http://www.wowhead.com/item=34091/mezhens-writings) after you kill him but he doesn't drop anything.

**Current behaviour**: After killing [Necro Overlord Mezhen](http://www.wowhead.com/npc=24018/necro-overlord-mezhen) nothing will drop.
**Expected behaviour**: If you have done the quest [Necro Overlord Mezhen](http://www.wowhead.com/quest=11264) or you are on the quest,  [Necro Overlord Mezhen](http://www.wowhead.com/npc=24018/necro-overlord-mezhen) should drop [Mezhen's Writings](http://www.wowhead.com/item=34091/mezhens-writings).

**Steps to reproduce the problem**:

1. Complete Howling Fjord quests up to [Necro Overlord Mezhen](http://www.wowhead.com/quest=11264).
2. Kill [Necro Overlord Mezhen](http://www.wowhead.com/npc=24018/necro-overlord-mezhen).
3. There will be no loot :).

**Revision**: 5418

**Comment by TranceAccount** [comment]
Cannot reproduce on PTR as an Alliance.

**Comment by Samineh** [comment]
Fixed in rev. 5427 by @Piklo. Closing this. Thank you <3 .
