### ISSUE TITLE
[EN][Quest][Grizzly Hills] Quest Line

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9202]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The main quest line in Grizzly Hills is buggy somehow. If you don't do every quest chain in it's right order you will end up ignoring some quests and after you take the [pit quest](http://www.wowhead.com/quest=12427/the-conquest-pit-bear-wrestling) before doing all the previous chains you are going to bug them (you won't be able to take them anymore).

**Current behaviour**: Explained in the Description.

**Expected behaviour**: Some quests shouldn't be available unless you do the prerequisite ones before them don't know exactly the blizzlike version of the chains but after reading the comments in wowhead I can tell even in retail there were some problems about the quest chains there.

**Steps to reproduce the problem**:

1. Start doing the quests in grizzly hills from the "Conquest Hold"
2. Take the [pit quest chain](http://www.wowhead.com/quest=12427/the-conquest-pit-bear-wrestling) as soon as it will be available to you.
3. You will end up bugging the previous quest chains. (you can't take them anymore)

**Revision**: 5418

**Comment by tomatosz** [comment]
I'm gonna see whether I can make an overview of how the quests are supposed to be

**Comment by tomatosz** [comment]
Well the quest chains in conquest hold are not correct, but the prereqs for the conquest pit quests are fine. Do you remember which quests were blocked for you?

**Comment by Samineh** [comment]
I tried recalling as much as I could I will post the quests that I am not sure if I may be able to get or not: 
1) http://www.wowhead.com/quest=12422/tactical-clemency
2) http://www.wowhead.com/quest=12178/delivery-to-krenna
3) http://www.wowhead.com/quest=12413/attack-on-silverbrook

**Comment by tomatosz** [comment]
Thanks, posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15252-quests-grizzly-hills/

**Comment by Jenovas** [comment]
Fix in 5537
