### ISSUE TITLE
[EN][QUEST][Storm Peaks] The Lonesome Watcher

### ISSUE THREAD

**Issue by podatekvat** [Atlantiss/BugTracker#9204]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/quest=12877/the-lonesome-watcher This quest works like it should till the end when u suppose to give quest item to NPC Creteus which is where he suppose to be but he is always dead and there is another Creteus next to the dead one but there is no interaction with him. Also, important to mention, current phase where NPC is, contains Stormforged Warmongers and Iron Behemoths (dwarves) and it suppose to be the phase with Ice Steppe Rhinos and such. Anyway it cannot be completed becouse of the missing correct NPC.

rev. 5418

**Comment by xmesaj2** [comment]
template
