### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] Crisis At The Sunwell

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9207]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: the NPC that recieves the quest is not recieving the quest.

**Current behaviour**: [What happens](http://i64.tinypic.com/zkhovk.jpg)

**Expected behaviour**: [What should happen instead](https://www.youtube.com/watch?v=GDc9PH3BVys)

**Steps to reproduce the problem**:

1. watch the video
2. 
3. 

**Revision**: 5418

**Comment by xmesaj2** [comment]
attach picture to the report instead linking to tinypic, describe all steps
