### ISSUE TITLE
[EN][Achievement][Eye of the Storm]Take a Chill Pill

### ISSUE THREAD

**Issue by Aviannaqt** [Atlantiss/BugTracker#9209]
Link: http://www.wowhead.com/achievement=1258/take-a-chill-pill

Description: Killing a person who has berserking buff doesn't give you achievement credit.

Current behaviour: After kill player who is under the berserking buff you'll not get an achievement.

Expected behaviour: You should get it.

Steps to reproduce the problem:

1. Enter the Eye of the Storm bg
2. Kill a player who is under the berserking effect.
3. No achi.

Revision: 5418

**Comment by xmesaj2** [comment]
fix rev. 5432
