### ISSUE TITLE
[EN] [Hunter] [Mechanic] Trap range indicator

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9213]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In PvP if the hunter scatters someone and then throws a trap you can walk into the trap to get it instead of the one who got scattered.

**Current behaviour**: Sometimes the Indicator for the visual display is bugged and if you are standing directly in the trap you wont get it. (actually that happens quite often) 

**Expected behaviour**: the one standing in the trap should get the trap not a random person around the trap.

**Steps to reproduce the problem**:

1. Scatter Person A
2. Throw a frost Trap
3. let Person B walk directly into the trap
4. sometimes (not always but most of t he time) person A will get the trap.

since I got told i should put some effort into my reports here are some videos of 2 hours Arena played, if you need more videos i can post some more, happend a lot today:

1. https://www.twitch.tv/videos/148066376
2. https://www.twitch.tv/videos/148067891
3. https://www.twitch.tv/videos/148071994

Would be awesome if you could fix that problem, lost us some games and it is really frustrating.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Heroclassx** [comment]
please ignore random german talk :D

**Comment by lamaATS** [comment]
Fixed in rev. 5498
