### ISSUE TITLE
[EN][QUEST][Howling Fjord] The Delicate Sound of Thunder

### ISSUE THREAD

**Issue by podatekvat** [Atlantiss/BugTracker#9214]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/quest=11495/the-delicate-sound-of-thunder Quest cannot be completed. It's very important couse it blocks main chain quest progression for ally in Howling Fjord, thus making loremaster achievement impossible to get.

**Current behaviour**: We can use Iron Rune Construct to get inside the cave but it doesn't complete the quest.

**Expected behaviour**: When entering the cave there suppose to be an army of dark iron dwarves. After passing by this army of Dark Iron Dwarves an image of Loken appears talking to the crowd. After listening to the conversation, which can be found in wowhead link in the comments section you get the quest completed.

**Steps to reproduce the problem**:

1. Take the quest
2. Use nearest table to get into Iron Rune Construct
3. Go to the quest location which is the thundering cave
4. Enter it and nothing happens thus quest cannot be completed
**Revision**: 5418

**Comment by xmesaj2** [comment]
#9032
