### ISSUE TITLE
[EN][Spell][Death Knight] Summon Gargoyle: Critical hit damage modifier 

### ISSUE THREAD

**Issue by zekk3n** [Atlantiss/BugTracker#9215]
Crit modifier is currently 150% when it should be 200%. I have no idea why this happens seeing as it never worked that way from what I remember. Tried searching patch notes and such and never found anything referring to it.

If you want proof this video was posted in a previously closed ticket: https://www.youtube.com/watch?v=y0tfUCk7FbI&feature=youtu.be&t=121

As you can see in the video, gargoyle normal attacks are doing around 9k damage while crits (they pop up in the middle of the screen) do 18k. For clarity, the gargoyle attacks have a (Pet) prefix and the shadow bolt icon. 

I can provide more videos AND simcraft 4.3.4 results as proof if necessary.

**Comment by TranceAccount** [comment]
# Please follow our _[Issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)_.
Thanks in advance.

**Comment by zekk3n** [comment]
I'm sorry but I'm not one to care about bureaucracies in a private server bugtracker lol. 

The issue template is unnecessarily complicated, this ticket was written in what I believe to be a concise and practical fashion.

**Comment by Aival94** [comment]
and the report can and might be closed because you do not follow the rules to write a bug report.

**Comment by zekk3n** [comment]
Closing a completely valid report over such reason would be nonsensical. I trust whoever is in charge of this bugtracker to have a better judgement.

**Comment by Heroclassx** [comment]
welcome to atlantiss, where no one cares about class bugs because dragon soul heroics are more important

**Comment by Aival94** [comment]
As far as i know everything is important but the bug reports should be reported correct and now the way you want them. Rules are rules and should be followed. If not followed anyone can just close your valid report because of not following the rules. Whatever. If they close it you know what is the reason for that :)

**Comment by Heroclassx** [comment]
For now we are planning to work only with 4.3 Content.

All 4.2 bugs that still exist need to wait, the same goes for class spells.

Every now and then there will be probably some fixes to spells / classes, but they aren't our priority currently.

**Comment by Jenovas** [comment]
Fixed in 5430.
