### ISSUE TITLE
[//]: # ([EN][NPC]Caladis brigtspear )missing npcs in frozen halls

### ISSUE THREAD

**Issue by moeh2415312** [Atlantiss/BugTracker#9218]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: several npcs are missing in the frozen halls
please add those npcs especially Caladis brightspear 

Caladis Brightspear:http://pt.wowhead.com/npc=36624/caladis-setalume

**Comment by TranceAccount** [comment]
Where are the Frozen halls?

**Comment by MichaelArchangelo** [comment]
I think it's the side chamber of Icecrown Citadel where the portals to FoS, PoS and HoR are

**Comment by moeh2415312** [comment]
its the place where the heroic 5 man dungeons are for icc
