### ISSUE TITLE
[EN][NPC][Reputation] Twilight Geolord Cenarion Circle rep

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9220]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Killing [Twilight Geolord](http://www.wowhead.com/npc=11881/twilight-geolord) does not give the appropriate amount of [Cenarion Circle](http://www.wowhead.com/faction=609) reputation.

**Current behaviour**: Killing the geolords gives 2 reputation (with guild perk), all other twilight mobs are fine.

**Expected behaviour**: The geolords should give 10 base reputation (so 11 with guild perk), like the other twilight mobs.

**Steps to reproduce the problem**:

1. Kill Twilight mobs in Silithus.
2. Notice that the Geolords give less rep than the others.
3. 

**Revision**: rev. 5418

**Comment by TranceAccount** [comment]
https://community.atlantiss.eu/index.php?/topic/14384-npc-twilight-geolord/

**Comment by Jenovas** [comment]
Fix in rev 5541
