### ISSUE TITLE
[EN][NPC][Reputation] Hellfire Imp Thrallmar reputation

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9221]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Hellfire imps](http://www.wowhead.com/npc=17477/hellfire-imp) in the Bloodfurnace give too much [Thrallmar](http://www.wowhead.com/faction=947/thrallmar) (and [Honor Hold](http://www.wowhead.com/faction=946/honor-hold)?) reputation.

**Current behaviour**: On heroic (dunno about normal) the imps give 16 reputation with guild perks.

**Expected behaviour**: They should give 3 reputation on heroic without perks, and 1 on normal.

**Steps to reproduce the problem**:

1. Kill hellfire imps in Bloodfurnace hc.
2. Check the rep increase.
3. 

**Revision**: rev. 5418

**Comment by TranceAccount** [comment]
#7338 similar issue for normal

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14380-npc-hellfire-imp-hc/
