### ISSUE TITLE
[EN][NPC][Reputation] Blood Guard Porung Thrallmar reputation

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9222]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Blood Guard Porung](http://www.wowhead.com/npc=20923/blood-guard-porung) in the Shattered Halls doesn't give [Thrallmar](http://www.wowhead.com/faction=947/thrallmar) (and [Honor Hold](http://www.wowhead.com/faction=946/honor-hold)?) reputation.

**Current behaviour**: This heroic only boss doesn't give any reputation.

**Expected behaviour**: He should give 250 reputation before perks.

**Steps to reproduce the problem**:

1. Kill Blood Guard Porung in Shattered Halls hc.
2. Check the lack of rep increase.
3. 

**Revision**: rev. 5418

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14382-npc-blood-guard-porung/
