### ISSUE TITLE
[EN][Spell][Shaman] T12 2p resto shaman mana gain not working properly

### ISSUE THREAD

**Issue by Throrn** [Atlantiss/BugTracker#9224]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The mana gain of the resto shaman T12 2p bonus is not working properly. It says it restores 1% of the base mana, but it's not even close to 1%. As of my character, I have 99140 base mana, but the T12 2p bonus restores only 234 mana when it procs. 1% of my base mana would be 991 mana, which is a huge difference.

**Current behaviour**: The T12 2p bonus for resto shamans restores 0.24% of the base mana instead of 1%.

**Expected behaviour**: The T12 2p bonus for resto shamans should restore 1% of the base mana when it procs.

**Steps to reproduce the problem**:

1. Log on a resto shaman with 2 pieces of T12
2. Heal with riptide
3. Check the combat log and see how much mana is gained from Flametide

**Revision**: 5418
![wowscrnshot_060417_114611](https://cloud.githubusercontent.com/assets/29173643/26760312/97ef1046-491d-11e7-913d-a6ba4f700b26.jpg)

**Comment by Piklo** [comment]
Base mana = mana without any items and buffs, 99140 is your maximum mana not base

**Comment by Throrn** [comment]
Thank you, I thought base mana = mana without any buffs or periodic int gains.
