### ISSUE TITLE
Hellfire Citadel Boss - Vazruden the Herald - Not Working Properly

### ISSUE THREAD

**Issue by cobruhh** [Atlantiss/BugTracker#9225]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem   In Hellfire Citadel, Vazruden The Herald is not working, When you kill him, he just respawns on his Mount when you kill him, and thhe drake fight encounter doesnt start, he just dies, no loot drop

**Current behaviour**: What happens   He just respawns on his mount. And when you do kill him, the drake fight encounter doesnt activate, and no loot drops

**Expected behaviour**: What should happen instead  When you Kill Vazruden, the Drake he flies on comes down to fight, and then you kill him, and then a loot chest drops

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
Try waiting for the dragon to come down before killing Vazruden?

**Comment by cobruhh** [comment]
The Dragon Doesn't come down until after he dies

**Comment by Piklo** [comment]
#2407
