### ISSUE TITLE
[EN][Spell][Shaman] Fulmination not being copied properly by Dragonwrath, Tarecgosa's Rest

### ISSUE THREAD

**Issue by ashrasmun** [Atlantiss/BugTracker#9227]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Copied Fulmination (http://wow.gamepedia.com/Fulmination) deals very low damage. By very low I mean below 10 points of damage.

**Current behaviour**: Damage done is too low.

**Expected behaviour**: Damage should be copied.

**Steps to reproduce the problem**:

1. Hit a target dummy with Earth Shock to trigger Fulmination (only 9 stack Fulminations were used during my tests)
2. Repeat the first step until you see Earth Shock triggering Fulmination that is copied.

Proof: http://i.imgur.com/WMryFLZ.jpg, http://i.imgur.com/lLk6jtn.jpg

**Revision**: 5434

**Comment by blinkmaster** [comment]
Same bug as with vlpc trinket

**Comment by ashrasmun** [comment]
bump

**Comment by Olrios** [comment]
1 year anniversary incomming

**Comment by pelekon** [comment]
fixed in rev 5891
