### ISSUE TITLE
[EN] [NPC] [Eversong Woods] Lanthan Perilon (minor)

### ISSUE THREAD

**Issue by Aldurion** [Atlantiss/BugTracker#923]
http://www.wowhead.com/npc=15281#starts
Currently he says " NEED TXT YTDB" . I have not found any gossip text associated especially with this NPC. I just wanted to mention this gossip error.

**Comment by Navedonar** [comment]
fixed soon

**Comment by Bildo** [comment]
rev. 4353 by Navedonar
