### ISSUE TITLE
[EN][Spell][Warlock] Drain Soul ticks do not proc Warlock T12 4-set.

### ISSUE THREAD

**Issue by frosttbitten** [Atlantiss/BugTracker#9236]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Drain Soul ticks do not proc Apocalypse (T12 warlock 4-set bonus), only the initial cast does which is huge for Affliction and it hinders the spec alot.

**Current behaviour**: It doesn't proc Apocalypse.

**Expected behaviour**: It should proc Apocalypse.

**Steps to reproduce the problem**:

1. Fix Drain Soul to proc 4-set from ticks instead of casts 
2. Affliction becomes viable
3. Profit 

**Revision**: 5434

**Comment by ashrasmun** [comment]
Fill the revision field please...

**Comment by Psychobird7** [comment]
Sources?

**Comment by frosttbitten** [comment]
@Psychobird7 What sources, it literally has Drain Soul listed as one of the spells that proc it on the item itself and it doesn't do that right now.

**Comment by wrisa** [comment]
Psychobird7 Are you a moron or are you just pretending. Instead of acting smart go read what the fuck 4 set t12 for warlock does.

**Comment by ashrasmun** [comment]
https://community.atlantiss.eu/index.php?/topic/14433-9236-drain-soul-does-not-proc-warlock-t12-4-set/

**Comment by frosttbitten** [comment]
Okay, just tested it, it's properly working now.

**Comment by Prodiege** [comment]
@frosttbitten you still haven't given any proof. By the phrasing of the set bonus it seems like it would only be on initial cast anyways due to the phrase "Casting your" instead of a phrase like "Your spellnamehere..."

You need to provide more proof that it is on every tick. Find affliction warlock POV videos for a warlock casting Drain Soul and the buff either applying on a tick other than the first, or the buff refreshing from a tick that isn't the first

**Comment by frosttbitten** [comment]
@Prodiege I apologize, finally managed to find proof of it and it looks like Blizzard just wanted to kill Affliction in this patch, it is working properly indeed, this thread can be closed.

**Comment by ashrasmun** [comment]
Thanks for wasting my time then... Next time you post something on the BugTracker - TEST / CONFIRM IT.
