### ISSUE TITLE
[EN][Quest][Gilneas] Gasping for Breath

### ISSUE THREAD

**Issue by Ntsee** [Atlantiss/BugTracker#9237]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The server crashes when getting a specific Drowning Watchman.

**Current behaviour**: What happens
Attempting to pick up the Drowning Watchman that is near the scarecrow, Silverleaf herb, and wooden stand crashes the server. Other watchmen work fine, just this specific one crashes the server.

**Expected behaviour**: What should happen instead
The Drowning Watchman should be picked up without crashing the server.

**Steps to reproduce the problem**:

1.  Find the Drowning Watchmen near the scarecrow, Silverleaf herb, and wooden stand.
2. Click on the Drowning Watchmen.
3.  Crash

**Revision**: 5434

**Comment by TranceAccount** [comment]
Your game crashes or the server completely crashes?

**Comment by Ntsee** [comment]
The server crashes. Its not only me. I wasnt sure at first so I tried again. The server goes offline for a couple minutes and came back up.

**Comment by krecik88** [comment]
Can u describe more (or post screenshot) which npc causes crash? because i've tested it and couldnt reproduce the problem.
