### ISSUE TITLE
[PL][Achievement - You'll Feel Right as Rain]

### ISSUE THREAD

**Issue by Misiac** [Atlantiss/BugTracker#924]
Po zjedzenie 91x Chocolate Cookie - http://www.wowhead.com/item=62680
i zdobyciu 91 stackow buffa http://www.wowhead.com/spell=87649
Nie zalicza achievu http://www.wowhead.com/achievement=5779

**Comment by Lauthai** [comment]
Potwierdzam, po zdobyciu 91 achievement nie jest zaliczany

**Comment by qubuslabadz** [comment]
Fix in rev. 4228.
