### ISSUE TITLE
[EN][NPC][Reputation] Ethereal Beacon and Ethereal Apprentice hc Consortium

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9240]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In Mana Tombs hc, the [Ethereal Beacon](http://www.wowhead.com/npc=18431/ethereal-beacon) and [Ethereal Apprentice](http://www.wowhead.com/npc=18430/ethereal-apprentice) don't give the proper amount of [Consortium](http://www.wowhead.com/faction=933) reputation.

**Current behaviour**: The Ethereal Beacon gives 16 Consortium reputation and the Ethereal Apprentice gives none (regardless of current reputation).

**Expected behaviour**: The Ethereal Beacon should give 8 reputation and the Ethereal Apprentice should give 21 reputation, regardless of current reputation.

> By spike3607 (5,991 – 3·16·40) on 2009/05/15 (Patch 3.1.1) 
These mobs are worth 21 consortium rep surprising. They are only worth 8 if you kill them in beacon form. 
(http://www.wowhead.com/npc=18430/ethereal-apprentice#comments)

>By Ely16 (1,891 – 5) on 2012/05/09 (Patch 4.3.4)		
Step 3. Clear up to Nexus-Prince-Shaffar
Step 4. Engage him but do not damage or kill him.
Step 5. Wait until his ethereal assistants spawn (out of spark form) and kill them. 
Result: 23rep/15seconds=5520rep/hour=6.52hours from neutral to exalted.
(http://www.wowhead.com/faction=933/the-consortium#comments)

^available till exalted

**Steps to reproduce the problem**:

1. Run Mana Tombs hc till Nexus-Prince Shaffar
2. Don't kill him, let the beacons turn into assistants
3. Kill assistants and beacons and note the (lack of) rep increase.

**Revision**: rev. 5434

**Comment by tomatosz** [comment]
Attempted a fix on forums:
https://community.atlantiss.eu/index.php?/topic/14427-npc-ethereal-beacon-and-ethereal-apprentice/

**Comment by Jenovas** [comment]
Fix in rev 5541
