### ISSUE TITLE
Duplicate NPC's

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9241]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem: [EN][NPC] Denalan

**Current behaviour**: What happens: There are two Denalan at Lake Al'ameth

**Expected behaviour**: What should happen instead: There should only be one.
![unknown](https://user-images.githubusercontent.com/11807325/26928084-f10c20da-4c54-11e7-8bf1-5fa46ef5c988.png)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 4.3.4

**Comment by deadspear** [comment]
I do believe one of them is suppose to be at Wellspring Hovel. In the quest journal it says he wander from there to the Wellspring Hovel. So he can be found at both locations.

**Comment by TranceAccount** [comment]
1 of them spawns when you complete the quest Denalan's Earth, and doesn't despawn.

**Comment by TranceAccount** [comment]
#5536
