### ISSUE TITLE
NPC: Agal

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9242]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem: Missing Rare status

**Current behaviour**: What happens: Agal spawns without the rare status hes suppose to have.

**Expected behaviour**: What should happen instead: Agal should be a rare spawn: http://www.wowhead.com/npc=2162/agal (Classification: Rare)
![unknown](https://user-images.githubusercontent.com/11807325/26936435-00067a76-4c6f-11e7-83fa-8fa8e41c5f2b.png)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 4.3.4

**Comment by tomatosz** [comment]
Fix posted on forums (I hope) 
https://community.atlantiss.eu/index.php?/topic/14429-npc-agal/

**Comment by Jenovas** [comment]
Fix in 5541
