### ISSUE TITLE
[QUEST] [Stranglethorn Vale] See Raptor

### ISSUE THREAD

**Issue by eric-starr** [Atlantiss/BugTracker#9244]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Accept quest, talk to Priestess Hu'rala and she doesn't offer to start the mind vision.
**Current behaviour**: What happens

**Expected behaviour**: What should happen instead
Accept quest, click on Priestess Hu'rala and she offers to start mind vision.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Sayris9876** [comment]
Even tho the report is horrible written I can confirm. But i think there is already a report for that quest?

**Comment by ashrasmun** [comment]
From what I understand, after ending third quest in Priestess Hu'rala's chain, one should be able to get Mind Control quest (http://www.wowhead.com/quest=26360) as a next step.

**Comment by tomatosz** [comment]
#500
