### ISSUE TITLE
Riding Trainer Quest

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9248]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The Item that starts the quest isn't mail to the character upon reaching level 20.

**Current behaviour**: What happens is that it only mails you the letter, not the item itself.

**Expected behaviour**: What should happen instead is that the item should be mailed along with the letter.
http://wowwiki.wikia.com/wiki/Riding_Training_Pamphlet (Mine is a Night Elf so http://www.wowhead.com/item=46876/riding-training-pamphlet)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
Posted fix on forums:
https://community.atlantiss.eu/index.php?/topic/14499-riding-trainer-pamphlet-lvl20/
