### ISSUE TITLE
[EN] Died in maelstorm 

### ISSUE THREAD

**Issue by Mixcoatls** [Atlantiss/BugTracker#9249]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I felt in maelstorm and died, and can't get back there to complete the quest and open the portal to Deepholm.

**Current behaviour**: When I was riding the wind rider from the quest, after 2 minutes of flying i felt from it and died.

**Expected behaviour**: Shouldn't fall, but keep riding to complete the quest and go to Deepholm.

**Steps to reproduce the problem**:

1. Talked to NPC and teleported to maestorm
2. Took the quest and ride the wind rider
3. Felt from the sky while flying during the quest.
4. Died, released tmy spirit
5. Get teleporte to the barrens.
6. Tried to get back to complete the quest and get to Deepholm, but the portal isn't up and NPC can't teleport me back to maenstorm.

**Revision**: Current server version 4.3.4

**Comment by Piklo** [comment]
ticket in game

**Comment by Mixcoatls** [comment]
GM fixed it.
