### ISSUE TITLE
The NPC Gorsik in Deepholme is bugged.

### ISSUE THREAD

**Issue by Ryggbiff** [Atlantiss/BugTracker#9250]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The NPC in Deepholme Gorsik The Tumultuous is not clickable.
**Current behaviour**: What happens
 As above he is not clickable, can't interact with him. Therefore you can't handle in or take new quests.
**Expected behaviour**: What should happen instead
He is expected to be a normal NPC.
**Steps to reproduce the problem**:

1. Get to Deepholme
2. Try to Talk to Gorsik
3. Get mad AF

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
Revision 5434

**Comment by xmesaj2** [comment]
Did you turn off "At War" with Therazane in your reputation tab?

**Comment by TranceAccount** [comment]
No wowhead link + wrong title.
