### ISSUE TITLE
NPC Thurman Grant

### ISSUE THREAD

**Issue by Wegaxs** [Atlantiss/BugTracker#9254]
The NPC is on top of the House.
![thurman grant](https://user-images.githubusercontent.com/29362063/27015881-82844550-4eef-11e7-9813-639e4308d70c.jpg)

**Comment by ashrasmun** [comment]
https://community.atlantiss.eu/index.php?/topic/14472-9254-thurman-grant/

**Comment by roirraWedorehT** [comment]
Still have the issue 2/4/2018.
