### ISSUE TITLE
All mobs despawn when entering area "Rim of the World" @ Mount Hyjal

### ISSUE THREAD

**Issue by SoulanubisOG** [Atlantiss/BugTracker#9255]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
No mobs are at the "Rim of the World" when I am there

**Current behaviour**: What happens
When at Shrine of Aviana, heading west to do "A bird in Hand" into the "Rim of the World", all mobs despawn, when i head back to the shrine, all the mobs re-spawn.  All other sub-zones appear to have mobs, but I can't complete A bird in the hand without it.

**Expected behaviour**: What should happen instead
Should be mobs...

**Steps to reproduce the problem**:

1. Enter "Rim of the World"
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5434 hash 5367c2a19cfe

**Comment by Piklo** [comment]
Your phase seems to be bugged. Abandon your quests, die or ticket In game

**Comment by SoulanubisOG** [comment]
Abandoned all quests, flew into the Rim, jumped off my mount, died, same thing.  no mobs. I'll open an ingame.

**Comment by SoulanubisOG** [comment]
Fixed by ingame ticket
