### ISSUE TITLE
[EN][Quest][Scholazar Basin] A Hero's Burden - switch faction

### ISSUE THREAD

**Issue by bambucza** [Atlantiss/BugTracker#9256]
I would like to report the quest named: [A Hero's Burden](http://www.wowhead.com/quest=12581/a-heros-burden).
I want to switch faction from Frenzyheart or Oracles, but NPC [Artruis the Heartless](http://www.wowhead.com/npc=28659/artruis-the-heartless) is bugged. I can't kill and choose one's of faction represant (Zepik the Gorloc Hunter or Jaloot) because they are in ice tomb.  
I will be very grateful if you fix this bug.

**Comment by TranceAccount** [comment]
# Please follow our _[Issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)_.
Thanks in advance.
