### ISSUE TITLE
[EN][Guild][Calendar] Guild events

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9262]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Guild events can't be deleted after they are made.

**Current behaviour**: Explained in the Description.

**Expected behaviour**: Ranks that have the permission to create the guild event should have the ability to delete them also.

**Steps to reproduce the problem**:

1. Be in a guild.
2. Have the permission to create guild events. Create one.
3. You can't delete the event you just created.

**Revision**: 5434

**Comment by TranceAccount** [comment]
Proof? 🗡

**Comment by Samineh** [comment]
wowwiki.wikia.com/wiki/Calendar
@ the notes section there are proofs that the guild events could be deleted also if you search the google you will see some discussions about it.

**Comment by TranceAccount** [comment]
I'm too lazy to use google. I don't understand google.

**Comment by Samineh** [comment]
Well I've searched and it seems the differences between a normal event and guild event are: If you create a guild event all the members of your guild can see the event and sign up for it, you can only invite players from out of the guild. If you delete the guild event every player who signed will get a notification by in game mail. On the other hand if you create a normal event you can invite players from inside and outside the guild and only they can see the event. You can delete the event and there won't be a notification if you do so.

**Comment by tomatosz** [comment]
^I can confirm that the notifications do work, even after the event xD (got some lovely spam when people left the guild, apparently the only way of deleting guild events =D)
