### ISSUE TITLE
[PL][spell][priest] Dispel Magic

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#9264]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Zacytuję z gry: "Dispels magic on the target, removing 2 harmful spells from a friend or 1 beneficial spell from an enemy".

**Description**: Describe the problem
Kiedy priest zrobiony jest w talentach w shadow, nie może używać na nikim (czy to w raidzie, na BG, czy poza party) dispel magic oprócz na sobie. Pokazuje "invalid target". 
Sprawdzałam talenty discipline, działa bez problemu na osobie w grupie/raidzie, poza nimi, na sobie oraz na wrogim przeciwniku. Używam niezbyt wygodnej i mano-żernej umiejętności "mass dispel". 

**Current behaviour**: What happens
Używam "dispel magic", pokazuje na czerwono "invalid target", mogę użyć czaru wyłącznie na sobie, na innych już nie. 

**Expected behaviour**: What should happen instead
Po użyciu dispel magic na osobach w grupie, w raidzie, poza nią oraz na wrogim targecie powinien czar zadziałać bez względu czy jest co zdjąć z osoby lub nie. Powinna zostać zużyta mana.

**Steps to reproduce the problem**:
1. Klikam Dispel Magic na nieważne jakim targecie, gdy aktywne są talenty shadow
2. Nie tracę many i nie mogę użyć czaru na nikim oprócz siebie 
3. Pokazuje "invalid target".

Pozdrawiam, Borowka.

**Comment by Piklo** [comment]
Zacytuję z gry: "Dispels magic on the target, removing 2 harmful spells from a friend or 1 beneficial spell **from an enemy**".
"from an enemy"

**Comment by whiskass** [comment]
@Piklo nie o to do końca mi chodziło akurat.
Temat do zamknięcia, zacytowałam opis Dispel Magic z discipline, a w shadow formie zmienia się na Dispels magic on the target, removing 2 harmful spells from YOURSELF or 1 beneficial spell from an enemy".
Najwyraźniej potrzebowałam zaśmiecić bugtracker, aby zauważyć tę malutką zmianę w opisie, a tyle zastanawiałam się, o co chodzi. :)

**Comment by ashrasmun** [comment]
@whiskass to jest tak zwana metoda na gumową kaczuszkę ;)
