### ISSUE TITLE
[PL][NPC][Drop] Attumen the Huntsman

### ISSUE THREAD

**Issue by whiskass** [Atlantiss/BugTracker#9265]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

http://wowwiki.wikia.com/wiki/Attumen_the_Huntsman
screen-shot: https://zapodaj.net/ee31d83cb2e32.jpg.html
**Description**: Describe the problem
1wszy boss w Karazahn, Attumen the Huntsman już od kilku ID dropi wyłącznie golda, nie ma z niego żadnych itemów. Ten boss jest o tyle istotny, że dropi cieszącego oko mounta Fiery Warhorse:). 
 
**Current behaviour**: What happens
Po zabiciu bossa i podniesieniu lootu widnieje wyłącznie gold, nie ma żadnych itemów.

**Expected behaviour**: What should happen instead
Po ubiciu bossa powinny wydropić gold, itemy oraz przy dużym szczęściu mount. 

**Steps to reproduce the problem**:
1. Pull oraz bicie konia;
2. przejście do fazy 2, kiedy jeździec wchodzi na konia;
3. ubicie bossa i podniesienie lootu: golda, itemów oraz przy małej szansie mounta.

Pozdrawiam, Borowka.

**Comment by Piklo** [comment]
mount aktualnie dropi, reszta itemów powinna lecieć po nowym revie
http://atlantiss.eu/changelog#rev5440
