### ISSUE TITLE
druid damage absorb bug

### ISSUE THREAD

**Issue by killermommy** [Atlantiss/BugTracker#9266]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
druid damage absorb bug
**Current behaviour**: What happens
damage absorb don't work for rdf and raids with magic damage spells
**Expected behaviour**: What should happen instead
damage absorb should work for every think hit a damage
**Steps to reproduce the problem**:

1. make a druid tank
2. try to join rdf like  [Grand Vizier Ertan] first boss at vortex
3. atk the boss as a bear (watch your damage absorb and you well see that you take magic damage from boss)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
Dk and bear shield absorbs only physical damage
