### ISSUE TITLE
[EN][NPC][Drop] Greengill Slave

### ISSUE THREAD

**Issue by Smiite** [Atlantiss/BugTracker#9269]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)
http://www.wowhead.com/npc=25084/greengill-slave#pickpocketing
**Description**: Describe the problem
You should be able to pickpocket Heavy Junkbox from Greengill Slave
**Current behaviour**: What happens
After 100 attempts i had 0 of them.
**Expected behaviour**: What should happen instead
You should get some Heavy Junkboxes
**Steps to reproduce the problem**:

1. Go to Isle of Quel'Danas 
2. Pickpocket some murlocks

**Revision**: 5434

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14520-9269-greengill-slave-pickpocket-loot-tables/
