### ISSUE TITLE
[EN][NPC] Shadowclaw model bug

### ISSUE THREAD

**Issue by Eldrasil** [Atlantiss/BugTracker#9270]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Tamed model different from the actual model of the beast in question

**Current behaviour**: Black striped saber cat (Shadowclaw - Darkshore) changes to a regular black striped cat after being tamed

**Expected behaviour**: The model should stay the same 

**Steps to reproduce the problem*
**:

1. Find the cat
2. Tame the cat
3. See it change

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
Wowhead link to the pet.
+ Title should've stated the pet 📦

**Comment by Eldrasil** [comment]
The name is in the "Current Behaviour" but w/e, I can change the title, no prob.

**Comment by Eldrasil** [comment]
Here http://www.wowhead.com/npc=2175/shadowclaw

**Comment by TranceAccount** [comment]
Thanks

**Comment by TranceAccount** [comment]
The difference between these models is so small ._.

**Comment by TranceAccount** [comment]
![afbeelding](https://user-images.githubusercontent.com/13118481/27327053-95ede6e0-55ad-11e7-9fd7-6f51aa4f04e6.png)

**Comment by TranceAccount** [comment]
## Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14549-npc-shadowclaw/
