### ISSUE TITLE
[PL][Item] Moonwel Chalice

### ISSUE THREAD

**Issue by Trollpowah** [Atlantiss/BugTracker#9272]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Przedmiot [Moonwell Chalice](http://www.wowhead.com/item=70142/moonwell-chalice) nie daje buffa do Mastery w combacie.
**Current behaviour**: Przedmiot niezależnie od momentu użycia (przed walką jak i podczas walki) nie daje buffa kiedy posiadamy combat. 

Dowód 1: https://youtu.be/f425mPawgcw

Widzimy jak około 2 sekundy dostaję buffa z trinketu, a po użyciu Hand of Gul'Dan na kukle i wejściu w combat, tracę połączenie z kielichem i buffa do mastery.

Dowód 2: https://youtu.be/g_AWzyumADE

Nasz obiekt testowy, Mag Arcane wchodzi w combat z kukłą, po czym używa trinketu. Jak widać, nie zostaje on połączony z kielichem i nie dostaje buffa do mastery.

**Expected behaviour**: Przedmiot powinien zdejmować buffa do mastery, tylko jeżeli go zdejmiemy. Jeżeli jest założony, podczas walki powinien nam dawać 1700 Mastery Ratingu.
**Steps to reproduce the problem**:

WERSJA 1
1. Użyj Moonwell Chalice
2. Wejdź w Combat
3. Sprawdź czy buff dalej jest

WERSJA 2
1.Wejdź w Combat
2.Użyj Moonwell Chalice
3.Buff do Mastery nawet się nie pojawia

**Revision**:  5434

**Comment by Frostbreaker** [comment]
#potwierdzoneinfo

**Comment by ashrasmun** [comment]
Tymczasem wystarczy używać Moonwella po 1 spellu / po wejściu w combat i problem jest rozwiązany.

**Comment by Frostbreaker** [comment]
Niestety jak widać na załączonych filmach ten "trick" nie działa na magu. Zostało tam użyte Arcane Barrage oraz Fire Blast a Chalice nadal nie zadziałał. Testowałem także z innymi kombinacjami Arcane Blast x3 etc. żadna z nich nie zadziałała. Poza tym Moonwell Chalice nie działa tak jak powinien i należy go naprawić.

**Comment by ashrasmun** [comment]
https://www.youtube.com/watch?v=0wQ0CABU1_4 5:25 - jednak to prawda. Moonwell działa jak chce i kompletnie losowo się odpala. Dla przykładu, na moim locku (czerwony znacznik) został odpalony Moonwell, który na początku był nieaktywny, a potem aktywował się na sekundę, tylko po to, żeby znowu się wyłączyć :(
