### ISSUE TITLE
[EN][NPC] Mangy Nightsaber (ID = 2032)

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#9279]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: www.wowhead.com/npc=2032/mangy-nightsaber
http://www.wowhead.com/quest=28713/the-balance-of-nature
Tested on PTR.

**Current behaviour**: [Mangy Nightsaber (ID = 2032)](www.wowhead.com/npc=2032/mangy-nightsaber) doesn't count for the quest [The Balance of Nature (ID = 28713)](http://www.wowhead.com/quest=28713/the-balance-of-nature).

**Expected behaviour**: [Mangy Nightsaber (ID = 2032)](www.wowhead.com/npc=2032/mangy-nightsaber) should count as a [Young Nightsaber (ID = 2031)](http://www.wowhead.com/npc=2031/young-nightsaber) kill.

**Proof:** http://web.archive.org/web/20110829145328/www.wowhead.com/npc=2032/mangy-nightsaber#objective-of

**Steps to reproduce the problem**:

1. Create a Night Elf. (Non-dk)
2. Accept the first quest in Shadowglen [The Balance of Nature (ID = 28713)](http://www.wowhead.com/quest=28713/the-balance-of-nature).
3. Head towards the Shadowthread cave and kill some [Mangy Nightsaber (ID = 2032)](www.wowhead.com/npc=2032/mangy-nightsaber).

**Revision**: 5434

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14711-9279-mangy-nightsaber-quest-the-balance-of-nature/
