### ISSUE TITLE
[EN][Spell][Druid] Rebirth

### ISSUE THREAD

**Issue by Slotease** [Atlantiss/BugTracker#9287]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Previous thread closed even though it is not fixed for my Horde druid. Trust me. This is a bug for me. I have ressed people totally out of combat with nothing around and they still come back with only %40. Its fine closing tickets if the issues are resolved but it isnt for me so i cant even raid cos of this.

**Current behaviour**: Upon spell cast target comes back to life with %40 health. No, they are not getting hit after spawning.

**Expected behaviour**: Per http://www.wowhead.com/spell=224112/rebirth you are supposed to come back to life with %100 health.

**Steps to reproduce the problem**:

1. Have somebody die. In or out of combat does not matter as they still only come back to life with %40 health.
2. Use the rebirth spell
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Slotease** [comment]
Log in my character and test yourselves if you think i am BS'ing.

**Comment by Piklo** [comment]
maybe you should use glyph for rebirth? 
![image](https://user-images.githubusercontent.com/16057987/27373966-709ccaa6-566a-11e7-9d54-a425986cd1cf.png)

**Comment by TranceAccount** [comment]
> Log in my character and test yourselves if you think i am BS'ing.

GMs/Admins/Developers don't do that.

**Comment by MangeNerfedOwl** [comment]
Have you tried to relearn the glyph?
