### ISSUE TITLE
[EN][NPC] Corrupted Tide Crawler (ID = 32935)

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#9288]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/npc=32935/corrupted-tide-crawler

**Current behaviour**: [Corrupted Tide Crawler (ID = 32935)](http://www.wowhead.com/npc=32935/corrupted-tide-crawler) can't be tamed.

**Expected behaviour**: [Corrupted Tide Crawler (ID = 32935)](http://www.wowhead.com/npc=32935/corrupted-tide-crawler) should be tamable.

**Proof:** https://web.archive.org/web/20120729032102/http://www.wowhead.com/npc=32935/corrupted-tide-crawler Quick Facts:
"Tameable (Crab)"

**Steps to reproduce the problem**:

1. Go to the beach next to Lor'danel in Darkshore as a hunter.
2. /cast Beast Lore on [Corrupted Tide Crawler (ID = 32935)](http://www.wowhead.com/npc=32935/corrupted-tide-crawler).
3. Dismiss your current pet.
4. /cast Tame Beast on [Corrupted Tide Crawler (ID = 32935)](http://www.wowhead.com/npc=32935/corrupted-tide-crawler).

**Revision**: 5444

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14710-9288-corrupted-tide-crawler-family/
