### ISSUE TITLE
[EN][NPC] Shimmershell Snail (ID = 48182)

### ISSUE THREAD

**Issue by TranceAccount** [Atlantiss/BugTracker#9291]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/npc=48182/shimmershell-snail

**Current behaviour**: [Shimmershell Snail (ID = 48182)](http://www.wowhead.com/npc=48182/shimmershell-snail) drops [Tightly Sealed Trunk (ID = 20708)](http://www.wowhead.com/item=20708/tightly-sealed-trunk).

**Expected behaviour**: [Shimmershell Snail (ID = 48182)](http://www.wowhead.com/npc=48182/shimmershell-snail) should not drop anything.

**Steps to reproduce the problem**:

1. Go to Darkshore around Lor'danel.
2. Kill some [Shimmershell Snail (ID = 48182)](http://www.wowhead.com/npc=48182/shimmershell-snail).
3. Loot them.

**Revision**: 5444

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14709-9291-shimmershell-snail-loot_template/
