### ISSUE TITLE
[EN][Quest][Desolace] Firestarter 

### ISSUE THREAD

**Issue by Miel44** [Atlantiss/BugTracker#9293]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I should summon Wispy Vortex, and defeat 7 Disciples of Elune in its presence. 

**Current behaviour**: After killing Disciples nothing happens, Vortex doesn't react in any way. 

**Expected behaviour**: Vortex should ignite itself, and grow bigger with each slain Disciple. After 7 kills quest should be completed. 

**Steps to reproduce the problem**:

1. Summon Wispy Vortex
2. Kill some Disciples 
3. Nothing happens

**Revision**: 4.3.4

**Comment by Myivo** [comment]
wowhead link?

**Comment by AbigailKnox** [comment]
http://www.wowhead.com/quest=14196/firestarter

Quest doesn't work - vortex still doesn't react after killing Disciples.
