### ISSUE TITLE
[EN][Racial][Shadowmeld] Meld not working as intendet?

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9300]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Yesterday i played some Arena 2v2 and i noticed that meld is not working as it should be, if you use Shadowmeld, your enemies should lose their target (if they are targeting you) and it should apply the old Vanish mechanic aka beeing able to meld spells / not receiving them.

**Current behaviour**: Its weird, it works (sometimes), I had an Arena game where I got counterspelled by a mage in a frostnova he started to shatter me (frostbolt + ice lance /w fof or nova) so I used shadowmeld after he finished the cast to negate the damage, but i received the damage. If i had Shadoewmelded while he was casting it should cancel the cast for him but that is also not working.

I was lucky to catch it on stream: https://www.twitch.tv/videos/154540173 please watch at about 13 sec i pressed shadowmeld after he finished the cast but received the full damage.

**Expected behaviour**: @ description

**Steps to reproduce the problem**:

1. Find any class (mage and boomkin are the easiest I think)
2. Let them Cast Frostbold / Wrath at you
3. Shadowmeld after cast finished /cry 
_______________________________________-

1. Find any caster that casts CC (clone, polymorph, et cetera)
2. Shadowmeld while they are casting that spell
3. sometimes they lose their target but most of the time you will receive it while in shadowmeld
(if needed i also have a twitch video of this somewhere in my stream)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Heroclassx** [comment]
my bad, had Faerie fire in that clip, but the problem still exists sometimes its not working and i have no idea why

**Comment by Heroclassx** [comment]
Okay since first clip was with faerie fire i looked out for another one.

Its the second problem I discribed. also no Faerie fire up! :D

https://www.twitch.tv/videos/154539596 ~16 sec. I deathed first sheep, so death was on cooldown, pillar to far away to los decided to meld to cancel cast waiting till death is back up. Sadly didnt cancel the cast of him.

**Comment by xolon** [comment]
> https://www.twitch.tv/videos/154539596 ~16 sec. I deathed first sheep, so death was on cooldown, pillar to far away to los decided to meld to cancel cast waiting till death is back up. Sadly didnt cancel the cast of him.

If player is close to you, and you meld that player will only lose but not sight of you. So the cast won't break. 
![wowscrnshot_062817_183857](https://user-images.githubusercontent.com/10000334/27650429-3e96ef2a-5c35-11e7-99fb-72a4b621f017.jpg)
![wowscrnshot_062817_183848](https://user-images.githubusercontent.com/10000334/27650431-3e99c3a8-5c35-11e7-9eba-ff553da8192a.jpg)
![wowscrnshot_062817_183853](https://user-images.githubusercontent.com/10000334/27650430-3e987fb6-5c35-11e7-80e1-485c0188595f.jpg)

**Comment by xolon** [comment]
https://www.youtube.com/watch?v=o-JWVYX7vFQ

**Comment by xolon** [comment]
However if you meant to Evade the poly, you melded to early on your vid. You have to meld at the almost exact same time the cast finishes. Will upload other videos when I come home. Cheers

**Comment by Heroclassx** [comment]
Thank you for your effort, I know how the meld mechanic works.

I made the decision to not try to meld the poly in the exact same time as he finished because the chance on a cast with no traveling time is to low. Spells with traveling time are no problem but without is kinda hard.

BUT Meld has an improved stealth mechanic and should even prevent from beeing seen even if i am near the target, since my shadowword death was on cooldown and pillar to los not close enough i tried to meld. It SHOULD HAVE canceled the cast of his Polymorph but he could finish it since he had still vision on me.

**Comment by Uradopted** [comment]
Shadowmeld does indeed work that way, but for only certain instances. For example, when a balance druid casts Treants and shadowmelds, anyone targeting the druid will now have their targets be the treants. Shadowmeld does not work like Mirror Images.

**Comment by lamaATS** [comment]
Fixed in rev. 5486
