### ISSUE TITLE
[EN][NPC] The Razza

### ISSUE THREAD

**Issue by Aieerth** [Atlantiss/BugTracker#9301]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The Razza isn't spawning. Game Master answered me in game and they couldn't summon it either, so it looks like that mob was removed from the database or simply never was in it. 

**Expected behaviour**: He should spawn and be tameable for hunters. It's the only mob with this look, so it's valuable for hunters who want rare pets.

**Revision**: 5447?

**Comment by TranceAccount** [comment]
What about a wowhead link?
