### ISSUE TITLE
[EN][NPC] Anren Shadowseeker

### ISSUE THREAD

**Issue by Terrar2** [Atlantiss/BugTracker#9305]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: NPC doesn't show up where he should,so i can;t accept Quest Need...Water...Badly
**Current behaviour**: Can't complete Molten Front Offensive achivment
**Expected behaviour**: Quest should be acceptable 

**Steps to reproduce the problem**:

1. Fix NPC
![wowscrnshot_062917_102501](https://user-images.githubusercontent.com/7278448/27678697-67b64122-5cb6-11e7-8ba0-4b1b9eee367f.jpg)

**Revision**:

**Comment by tomatosz** [comment]
He's in the cave that you enter after Into the Fire, it looks like you're outside (but I may be mistaken)

**Comment by Terrar2** [comment]
He is in the cave but i can't take quest from him or even talk with him.

**Comment by Sayris9876** [comment]
Yes indeed he is suppose to be in the cave but I dont think its spawning at all. Year ago when I was doing MF for acheves i wrote ticket and GM spawned it for me. So I guess you could try with ticket but the fact is that this NPC doesnt spawn at all (maybe after restart or crash cant confirm)

**Comment by Terrar2** [comment]
Ok thank you guys ;)

**Comment by tomatosz** [comment]
Hm, I finished it (less than a year ago) without any issues, could be after a restart though, dunno.
