### ISSUE TITLE
[EN][NPC] West Plains Drifter

### ISSUE THREAD

**Issue by TweSlages** [Atlantiss/BugTracker#9308]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] West Plains Drifter)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: They should be Pushing the carts 
**Current Behavior**: http://imgur.com/a/ooBPp
https://hydra-media.cursecdn.com/wow.gamepedia.com/thumb/e/ed/West_Plains_Drifter.jpg/200px-West_Plains_Drifter.jpg?version=673b4bf35018b10b759b97a49c40247d

**Comment by TranceAccount** [comment]
Duplicate?
