### ISSUE TITLE
[EN][Quest][Felwood] Do The Imp-Possible

### ISSUE THREAD

**Issue by Draycos99** [Atlantiss/BugTracker#9309]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
NPC 'Impsy' cannot be captured as per quest requirements, as seen in previously closed bug (#2282),
This prevents further quests from becoming available.
http://www.wowhead.com/quest=28000/do-the-imp-possible

**Current behaviour**:
On first attempt, Impsy took enough damage to enter waiting-for-capture state, but activating the the Enchanted Imp Sack had no effect with "You cannot do that yet" error.
The quest was abandoned and reattempted, but this time Impsy was an "invalid target" and could not be damaged.
Note that the previously closed bug (#2282) appeared to be temporarily resolved by a server restart, but the issue persists.

**Expected behaviour**:
Once sufficiently damaged, Impsy enters a waiting-for-capture state. The player can then use the Enchanted Imp Sack to captue Impsy and return him to the quest vendor for completion.

**Steps to reproduce the problem**:
1.  Complete pre-requisit quests in Felwood (The Corruption of Jadefire, Culling the Corrupted, An Arcane Ally)
2.  Accept the quest Do the Imp-Possible from NPC Arcanist Delaris (Felwood 42,72)
3.  Locate Impsy (Felwood 48,73) and fight him
4.  If Impsy enters waiting-to-capture state, use the quest item Enchanted Imp Sack

**Revision**:
5447 hash. 4d5f532b3d43 2017-06-26

**Comment by Snake90** [comment]
Still bugged :/ It's imp-possible to attack him.

**Comment by BAndysc** [comment]
Fixed in 5635
