### ISSUE TITLE
[EN][Quest][Nagrand] The Ring of Blood : The Final Challenge

### ISSUE THREAD

**Issue by Dhalpha** [Atlantiss/BugTracker#9310]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The last part of the quest cannont be finished.

**Current behaviour**: When you kill Mogor, Hero of the Warmaul, the quest seems to be unfinished, like you never killed him.

**Expected behaviour**: When Mogor dies, the quest ends, then you can return your quest.

**Steps to reproduce the problem**:

1. Get the quest from Gurgthock, Nagrand ( the previous parts must be finished in order to get the last quest )
2. Mogor runs into the arena, he should be killed.
3. Return the quest to Wodin the Troll Servant and get your rewards

**Revision**: 5447 hash, 4d5f532b3d43 2017-06-26

**Comment by henkka90** [comment]
There should be a script involving Mogor, Hero of the Warmaul ressurecting himself when he dies, so the quest credit count only on the 2nd kill, add the ressurection script and it should work.

**Comment by VgqGHTNm** [comment]
> add the ressurection script and it should work.

That assumes that the other variable in the equation (credit on the 2nd kill) actually is implemented. Which we don't know for certain. Do we?

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15153-9310-the-ring-of-blood/

**Comment by TheCopacabanaMan** [comment]
Piklo, thanxie for posting the SQL fix, but problem still persists....

**Comment by Piklo** [comment]
problem still persists because fix is not accepted yet

**Comment by Jenovas** [comment]
Fix in 5537
