### ISSUE TITLE
[EN][Item] Aboriginal Vest Transmog

### ISSUE THREAD

**Issue by Acis-Atlantiss** [Atlantiss/BugTracker#9316]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
It is impossible to transmogrify an uncommon item Aboriginal Vest [http://www.wowhead.com/item=14121](url). It is a part of Aboriginal Regalia, which is an unofficial transmog set. [http://www.wowhead.com/transmog-set=11/aboriginal-regalia](url)
**Current behaviour**: 
As stated above, the transmogrifier vendor gives an error "This item's appearance cannot be used."
**Expected behaviour**: What should happen instead
It should be possible to transmogrify Aboriginal Vest as any other uncommon item. 
**Steps to reproduce the problem**:

1. Perhaps it's due to a bug not giving the item any enchantment? According to [http://www.wowhead.com/item=14121/aboriginal-vest](url) Aboriginal Vest should have a random enchantment.
2. Allow this item to be transmogrified.

**Revision**: 
ACore rev. 5451

**Comment by TranceAccount** [comment]
Should be fixed when you obtain this item again and does not fix already obtained items as of rev. 5860.
