### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Enraged Spirits of Water

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9320]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:

There is no way to even do this quest.

**Current behaviour**:

Any attempt to place the totem ( http://www.wowhead.com/item=30094/totem-of-spirits ) will result in "You are in the wrong zone."

**Expected behaviour**:

See the spawn location of the target mob:

http://www.wowhead.com/npc=21059/enraged-water-spirit

In the spawn locations for that mob, you are supposed to place down the earlier mentioned totem, to then kill the mobs. The totem will then collect the souls of those watery spirits.

See this screenshot for the area of the map that the totem is supposed to be placed in:

![wowscrnshot_070617_203619](https://user-images.githubusercontent.com/29864511/27927072-da649c9e-628a-11e7-935e-4a121767298a.jpg)

Further evidence:

![wowscrnshot_070617_203037](https://user-images.githubusercontent.com/29864511/27927217-57ebf3a6-628b-11e7-9723-89222223c830.jpg)

I am clearly in the correct location (see minimap), and the mob is the one we're supposed to kill. But, as seen in the screenshot, placing the totem is not allowed.

**Steps to reproduce the problem**:

1. Acquire the quest Enraged Spirits of Water
2. Move to the location as indicated by my 2nd screenshot.
3. Try and place totem.

**Revision**: 5451

Additional information:

* The preceding quest ( http://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth ) actually works perfectly fine. Although not entirely as intended, since the totem does follow you (which a totem should not be able to do) but it is completable.
* I tried all possible spawn locations in Shadowmoon Valley for that particular mob (Enraged Water Spirit) and none of them will accept the totem. None.
* It is important to note that this issue is a blocker for the remainder of an extremely long and rewarding quest chain. Also see the top comment here: http://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth

**Comment by tomatosz** [comment]
Please check whether a bug is posted before adding a new one: #1295
