### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9322]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:

An NPC is missing.

**Current behaviour**:

The NPC (Ancient Shadowmoon Spirit) is completely absent.

**Expected behaviour**:

While wearing the item provided by the quest giver (which **does** happen correctly), an NPC should be visible on the altar at the Altar of Shadows.

**Steps to reproduce the problem**:

1. Start the quest Teron Gorefiend - Lore and Legend
2. Wear the item provided by the quest giver ( http://www.wowhead.com/item=30721/spectrecles )
3. Travel to the Altar of Shadows.

**Revision**: 5451

Screenshots:

Location on map:
![wowscrnshot_070617_230158](https://user-images.githubusercontent.com/29864511/27932738-29069e38-629f-11e7-9065-e20da3533968.jpg)

Altar the NPC should be standing on:
![wowscrnshot_070617_230208](https://user-images.githubusercontent.com/29864511/27932757-34f2c73a-629f-11e7-99db-8165abe50799.jpg)

Interesting detail, Terron Gorefiend on his horse, behind the altar (which should not be there):
![wowscrnshot_070617_230317](https://user-images.githubusercontent.com/29864511/27932787-4f5af7b4-629f-11e7-9a25-be12a83b2b92.jpg)

Further reference:
http://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend

**Comment by tomatosz** [comment]
Please check whether a bug is posted before adding a new one: #8770 and #9148

**Comment by aendry** [comment]
this post is much more explanatory than the other one... you should close the other one and let this open. just saying
