### ISSUE TITLE
[EN][Quest][Shadowmoon Valley] Thwart the Dark Conclave

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9323]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:

Quest cannot be completed.

**Current behaviour**:

Using the quest item provided by the quest giver does nothing at the specified location. Just states that it requires "Unguarded Summoning Site". Even after ensuring all the cultists (who are not at the locations they're supposed to be at either) are dead.

**Expected behaviour**:

After killing the cultists, you are supposed to use the quest item provided by the quest giver to end a summoning process.

**Steps to reproduce the problem**:

1. Start the quest Thwart the Dark Conclave
2. Go to the specified location and kill the cultists.
3. Use the staff provided by the quest giver.

**Revision**: 5451

Screenshots:

Location on map:
![wowscrnshot_070617_232401](https://user-images.githubusercontent.com/29864511/27933550-3a8fdcd4-62a2-11e7-9495-39d150fc3a28.jpg)

Cultist (there should be 4 to kill):
![wowscrnshot_070617_232233](https://user-images.githubusercontent.com/29864511/27933566-46efdbd2-62a2-11e7-8125-0308c0e471cf.jpg)

Further reference:
http://www.wowhead.com/quest=10808/thwart-the-dark-conclave

**Comment by Sayris9876** [comment]
Oke all of the quests you linked ( #9320  #9321 #9322 ) I did them multiple times so either they got bugged recently (like in the past week or two) or they are just completable once per restart / crash.

**Comment by VgqGHTNm** [comment]
> or they are just completable once per restart / crash
This would not surprise me at all. I've experienced so many things by now that are only completable once per restart.

**Comment by tomatosz** [comment]
Please check whether a bug is posted before adding a new one: #2302 and #8768
