### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9327]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:

The quest cannot be handed in.

**Current behaviour**:

The turn-in NPC does not accept the completed quest.

**Expected behaviour**:

Obviously the quest should be completable.

**Steps to reproduce the problem**:

1. Start the quest The Stones of Vekh'nir
2. Perform the steps required for the quest. It will complete in your log.
3. Return to the quest giver (who also is the turn-in NPC). Minimap will show the NPC up as a yellow question mark, so, turn-in-able but the NPC does not accept it.

**Revision**: 5451

Screenshots:

Exact location on map:

![wowscrnshot_070717_171212](https://user-images.githubusercontent.com/29864511/27964227-d8b88a42-6337-11e7-86c3-9d3f63fb4085.jpg)

Me, holding the item the NPC should accept (see right-hand side, tooltip), talking to the NPC in question and the Continue button greyed out:

![wowscrnshot_070717_171156](https://user-images.githubusercontent.com/29864511/27964272-f73be4be-6337-11e7-986d-3d1942079bef.jpg)

**Comment by tomatosz** [comment]
Please check whether a bug is posted before adding a new one: #5224 and #4673
