### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] Showdown

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9328]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:

Quest ( http://www.wowhead.com/quest=10742/showdown ) cannot be completed because credit is not awarded.

**Current behaviour**:

After killing the quest's target ( http://www.wowhead.com/npc=20555/goc ) the quest status is not updated to reflect this.

**Expected behaviour**:

Upon killing Groc, credit for the kill should be awarded. As it is the sole requirement for the quest.

**Steps to reproduce the problem**:

1. Start the quest Showdown.
2. Go to Groc's altar and summon Rexxar with the Horn provided by him.
3. Kill Groc.

**Revision**: 5451

Screenshots:

Exact location on map:

![wowscrnshot_070717_191713](https://user-images.githubusercontent.com/29864511/27969056-b2a817d4-6349-11e7-9a63-7e43c158c4f7.jpg)

Dead Groc (and tooltip hover over quest item, see right-hand side):

![wowscrnshot_070717_191700](https://user-images.githubusercontent.com/29864511/27969075-d08fa262-6349-11e7-8db2-d3682b39236a.jpg)

Further evidence of the correct location:

![wowscrnshot_070717_191707](https://user-images.githubusercontent.com/29864511/27969094-dea348fe-6349-11e7-8774-2f620d68faa2.jpg)

**Comment by tomatosz** [comment]
Please check whether a bug is posted before adding a new one: #9178
