### ISSUE TITLE
Register Captcha is not working. [EN]

### ISSUE THREAD

**Issue by mdl7x7** [Atlantiss/BugTracker#9329]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When i type all my info when i register it tells me that captcha is invalid, but it doesn't show it to me in the first place.

**Current behaviour**:Same
**Expected behaviour**: It should show me a captcha code to type but it isn't.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
![image](https://user-images.githubusercontent.com/29986760/27972376-73a17442-6356-11e7-8375-171b76558398.png)

**Comment by TranceAccount** [comment]
What brower are you using?

**Comment by mdl7x7** [comment]
Im using google chrome.

07.07.2017. 20.56, "Somebody" <notifications@github.com> је написао/ла:

**Comment by TranceAccount** [comment]
Tried reloading?

**Comment by mdl7x7** [comment]
Yeah loads of times, still same. If u want we can go on skype and talk in detail.

**Comment by xmesaj2** [comment]
are you using adblock or other extensions?

**Comment by mdl7x7** [comment]
No, none at all.

**Comment by mdl7x7** [comment]
I've seen with other people, they get that captcha thing but its non-existent in my case i don' know why.

**Comment by Bastek** [comment]
Firefox 54.0.1
![kapcza](https://user-images.githubusercontent.com/537738/27973013-a7a7e012-6358-11e7-86da-c8a0240b9825.png)

**Comment by TranceAccount** [comment]
Tried updating Chrome to the latest patch?

**Comment by mdl7x7** [comment]
Uhmm i thought it's auto update thingy or something like that, although i feel dumb now but, can u tell me where can i update it? xd

**Comment by TranceAccount** [comment]
https://www.youtube.com/watch?v=RyI7RyEEPxM

**Comment by mdl7x7** [comment]
Oh it seems my browser is up to date.

**Comment by mdl7x7** [comment]
No need for update. What could be the problem then...

**Comment by TranceAccount** [comment]
Egh this is hard, we can't reproduce it.
Maybe restart brower or restart pc?

**Comment by mdl7x7** [comment]
ill try to restart pc brb.

**Comment by mdl7x7** [comment]
Ugh it's still the same..

**Comment by TranceAccount** [comment]
Try another browser :s

**Comment by mdl7x7** [comment]
I tried it 10 mins ago and still the same.

**Comment by mdl7x7** [comment]
![image](https://user-images.githubusercontent.com/29986760/27973767-81668644-635b-11e7-9f4d-970652971d5b.png)

**Comment by mdl7x7** [comment]
but when i type it here it says that my email does not exist logically, but idk...

**Comment by mdl7x7** [comment]
Yes i know :D 
![image](https://user-images.githubusercontent.com/29986760/27973987-4d857fe6-635c-11e7-8b03-9e5fabc28435.png)

**Comment by Bastek** [comment]
Can you do that via mobile phone?

**Comment by mdl7x7** [comment]
OMG YES! THANKS GUYS <3 It works on phone!! :D

**Comment by mdl7x7** [comment]
Sorry for being a trouble..

**Comment by Bastek** [comment]
For the record: it is user-side issue

**Comment by mdl7x7** [comment]
Sorry if i did something wrong its my first time doing this forum thing, thanks again :)
