### ISSUE TITLE
Eastern Plaguelands 

### ISSUE THREAD

**Issue by Nahoris** [Atlantiss/BugTracker#9332]
![image](https://user-images.githubusercontent.com/24939088/27995135-76c0854a-64c9-11e7-883e-fea9c5a1b2f6.png)

Fix it pls

**Comment by TranceAccount** [comment]
# Please follow our _[Issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)_.
Thanks in advance.
# Please follow our [_How to use?_](https://github.com/Atlantiss/BugTracker#how-to-use)
Thanks in advance.

**Comment by tomatosz** [comment]
Also, it has been reported, twice: #9153 #1035
