### ISSUE TITLE
[EN][NPC][Molten Front] Cinderweb Spinner

### ISSUE THREAD

**Issue by Purpleness** [Atlantiss/BugTracker#9333]
**Description:** Cinderweb Spinners in Molten Front has the incorrect amount of HP. 

**Current behaviour:** 

They have 232k HP. 

**Expected behaviour:** 

They should have 58,118 HP. 
See: 
http://cata-shoot.tauri.hu/?npc=52981
https://www.youtube.com/watch?v=flQY2CvxAXc (or any other King of the Spider-Hill achievement video)

**Steps to reproduce the problem:**

1. Go to Molten Front and look for yourself. 

**Revision**: 5451

**Comment by zekk3n** [comment]
They probably used same ID from Beth encounter spinners. 

Made that daily a major pain in the ass.

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14708-9333-cinderweb-spinner-health_mod-molten-front/
