### ISSUE TITLE
([EN][Quest][Plaguewoods] Morbent's Bane 

### ISSUE THREAD

**Issue by Anexio** [Atlantiss/BugTracker#9335]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
This quest doesn't work because the boss you have to kill can't be targetted.
**Current behaviour**: 
When you try to hit Morbent with a spell or a simple attack, it doesn't work because he's not at the right place.
**Expected behaviour**: 
Morbant should be place at the right spot so players can attack him and start the fight.
**Steps to reproduce the problem**:

1. Get into Morbant's room
2. Get in front of him
3. Try to attack him.

**Revision**: Current server version

**Comment by Anexio** [comment]
WoW Head link : http://www.wowhead.com/quest=26754/morbents-bane
Video link : https://www.youtube.com/watch?v=9uJg4ZszZLM

**Comment by Myivo** [comment]
Revision?
