### ISSUE TITLE
[EN][Spell][Hunter] Trap arming time

### ISSUE THREAD

**Issue by Purpleness** [Atlantiss/BugTracker#9339]
**Description**: 

Trap arming time should be 1 second and not 2 seconds.

**Current behaviour**: 

Current trap arming time is 2 seconds.

**Expected behaviour**: 
Correct trap arming time is 1 second.

See: http://wowwiki.wikia.com/wiki/Trap and https://youtu.be/qOyKu0iG63c?t=6m15s (look at shaman in focus at 6:20) 

**Steps to reproduce the problem**:

1. Scatter an enemy.
2. Cast any trap with 1 second remaining on scatter shot.
3. Scatter shot will break before the trap is triggered. 

**Revision**: 5451

**Comment by Uradopted** [comment]
Hello @Purpleness The links you provided were for later expansions, as of cataclysm, the trap arming time is two seconds, see here https://eu.battle.net/forums/en/wow/topic/2226274340 as for the video you posted, it was actually over 1 second watching in slow motion, with the timer of Scatter as an aid, when the shaman was trapped. Therefore, the timer of trap arming is correct on the server.

**Comment by Uradopted** [comment]
Hello @Purpleness I am sorry to inform you that you are mistaken, as seen in the video you posted in a different topic, you can clearly see that even in retail, this is a spell that requires travel time, every miss-able spell will have a travel time. https://www.youtube.com/watch?v=qOyKu0iG63c&feature=youtu.be&t=6m15s
