### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] Apothecary Zelana

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9345]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Deliver Bonechewer Blood Samples to [Apothecary Zelana](http://www.wowhead.com/npc=21257/apothecary-zelana) at Reaver's Fall in Hellfire Peninsula.

**Current behaviour**: You turn in Bonechewer Blood Samples to [Apothecary Zelana](http://www.wowhead.com/npc=21257/apothecary-zelana), and nothing happens after that.

**Expected behaviour**: There is supposed to be an RP Event when you turn in the quest.
This is the RP Event:
When giving her the  [Bonechewer Blood Samples]
    Apothecary Zelana says: Thank you, <name>. Now, to perform the test...
    Apothecary Zelana says: Ah, I see...
    Apothecary Zelana says: Yes, this is unfortunate.
    Apothecary Zelana says: <name>, I have confirmed that this blood is from the Bonechewer clan of orcs, tainted with demonic power. I'm afraid, however, that my current equipment can delve no deeper into this mystery... 

**Steps to reproduce the problem**:

1.  Accept the quest [Apothecary Zelana](http://www.wowhead.com/quest=10449/apothecary-zelana) from Vurtok Axebreaker (Should do [Bonechewer Blood](http://www.wowhead.com/quest=10450/bonechewer-blood) first to get it.
2. Travel to Apothecary Zelana at Reaver's Fall in Hellfire Peninsula.
3. Turn in the quest to Apothecary Zelana

**Revision**: 5458

Useful links= http://www.wowhead.com/quest=10449/apothecary-zelana
https://www.youtube.com/watch?v=GqhY6Kc0xX0
http://www.wowhead.com/npc=21257/apothecary-zelana
http://wow.gamepedia.com/Apothecary_Zelana

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14769-9345-apothecary-zelana-smart_scripts/
