### ISSUE TITLE
[EN][Spell][Hunter] Silencing Shot & Scatter Shot

### ISSUE THREAD

**Issue by Purpleness** [Atlantiss/BugTracker#9347]
**Description**: Silencing Shot and Scattering Shot should be instant and not have a travel time. 

**Current behaviour**: The target is affected by the silence/scatter when the 'arrow' hits the target (it has travel time)

**Expected behaviour**: The target should instantly be silenced/scattered when the hunter casts his Silencing/Scatter Shot (it doesn't have travel time). 

**Steps to reproduce the problem**:

1.  Cast Silencing Shot/Scatter Shot
2. Watch travel time
3. Profit

Useful links: 
https://github.com/Atlantiss/BugTracker/issues/6547
https://github.com/trinitycore/trinitycore/issues/6550

**Revision**: 5458

**Comment by xolon** [comment]
Confirmed

**Comment by Uradopted** [comment]
Hello @Purpleness I am sorry to inform you that you are mistaken, as seen in the video you posted in a different topic, you can clearly see that even in retail, this is a spell that requires travel time, every miss-able spell will have a travel time. https://www.youtube.com/watch?v=qOyKu0iG63c&feature=youtu.be&t=6m15s

**Comment by Uradopted** [comment]
The further away from the target you are, the longer it will take to silence the target. This is demonstrated in the video I used as reference in my previous comment. Watching it in slow motion will allow you to see the travel time even from little as 10yrds away from your target.

**Comment by Jenovas** [comment]
Closing
