### ISSUE TITLE
[EN][Npc][Drop] Razorsaw

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9348]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Razorsaw](http://www.wowhead.com/npc=20798/razorsaw) has a wrong drop rate for [Burning Legion Missive](http://www.wowhead.com/item=29590/burning-legion-missive) , took me 4 kills before I got it. Should be 100% if you didn't do the quest [Vile Plans](http://www.wowhead.com/quest=10393/vile-plans) yet.

**Revision**: 5458

http://www.wowhead.com/npc=20798/razorsaw
http://www.wowhead.com/item=29590/burning-legion-missive
http://www.wowhead.com/quest=10393/vile-plans
https://www.youtube.com/watch?v=t2Zl5OihbW0&feature=youtu.be

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14766-9348-burning-legion-missive-drop-chance/

**Comment by TranceAccount** [comment]
http://eu.battle.net/wow/en/item/29590
