### ISSUE TITLE
[EN][Quest][Sholazar Basin] Still At It

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9349]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The entire event seems to be bugged.

**Current behaviour**: Your suppose to talk to the brew master "Tipsy" McManus (http://www.wowhead.com/npc=28566/tipsy-mcmanus) and start the event, after that he calls out what to throw into the machine. He does that part, however he never confirms that you threw something in, so he just keeps on listing things. After he does everything the keg of the brew is suppose to be spawned. Currently a Keg is already spawned however you can't interact with it/If you somehow manage to open it, its empty.

**Expected behaviour**: https://www.youtube.com/watch?v=T7_Epv3iB8g Your suppose to talk to him then he'll list out the instructions and confirm them. Then the keg should spawn.

**Steps to reproduce the problem**:

1. Simply talk to Tipsy
2. 
3. 

**Revision**: 5458 (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
Please check if it's already posted before adding an issue yourself: #3413, #8240

**Comment by Piklo** [comment]
duplicate
