### ISSUE TITLE
[EN][Profession] Swordguard Embroidery 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9351]
**Description**: Swordguard Embroidery's Internal Cooldown is incorrect. 

**Current behaviour**: Swordguard's ICD is 64s. 

**Expected behaviour**: Swordguard's ICD should be 55s. 
https://web.archive.org/web/20121002035547/http://www.wowhead.com/spell=75178#comments 
https://web.archive.org/web/20120704234204/http://elitistjerks.com/f76/t110342-retribution_concordance_4_3_voice_dps/ 
More since someone asked. 
http://worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/details/13/?s=5141&e=5343 --> Buffs gained. 
http://worldoflogs.com/reports/rt-h0o5yew8kk0p1yd9/details/23/?s=4158&e=4397 --> Buffs gained. 

**Steps to reproduce the problem**:

1. Have a character with Swordguard
2. DPS and wait for a proc
3. Keep going, and wait for the second proc. Notice the delay will be too long. 

**Revision**: 5458

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14770-9351-swordguard-embroidery/

**Comment by Psychobird7** [comment]
TY! :)
