### ISSUE TITLE
[EN][Quest][Icecrown] Need More Info (ID = 13345)

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9353]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The amount of NPC's spawned in the room is too small compared to how many are there are suppose to be spawned.

**Current behaviour**:  In game there are about 5-6 NPC's in the left side of the room, while the right is completely vacant. 

**Expected behaviour**:  Its suppose to be filled with researchers: https://www.youtube.com/watch?v=q9Qc4uRT2Sk

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
Wowhead link to the missing npcs and quest?

**Comment by TranceAccount** [comment]
Might be a phasing issue

**Comment by deadspear** [comment]
http://www.wowhead.com/quest=13345/need-more-info
http://www.wowhead.com/npc=32297/cult-researcher
As you can see on the wowhead map theres dots on both sides of the room.
