### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] The Earthbinder

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9354]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After turning in [the quest](http://www.wowhead.com/quest=10349/the-earthbinder) Earthbinder Galandria Nightbreeze should do something.

**Current behaviour**: Nothing happens after finishing [the quest](http://www.wowhead.com/quest=10349/the-earthbinder).

**Expected behaviour**: There should be a small event.

[Earthbinder Galandria Nightbreeze](http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze) says: I have an idea. Let's plant this shard in the ground and see what happens. 

*[Galandria](http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze) walks down from the small hill she is standing on, and plants the crystal. A level 62 [Lured Colossus](http://www.wowhead.com/npc=20599/lured-colossus) suddenly appears.*

[Earthbinder Galandria Nightbreeze](http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze) says: The evil emanating from the crystal shard has lured one of the colossi. Put it down quick! 

*After the player defeats the colossi, the quest [Natural Remedies](http://www.wowhead.com/quest=10351/natural-remedies) becomes available from [Galandria](http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze).*

**Steps to reproduce the problem**:

1. Get a Crimson Crystal Shard from a Raging Colossus and start the quest Crimson Crystal Clue
2. Turn in the quest Crimson Crystal Clue at Tola'thion
3. Get the quest The Earthbinder and turn it in at Earthbinder Galandria Nightbreeze

**Revision**: 5458

http://www.wowhead.com/npc=20599/lured-colossus
https://www.youtube.com/watch?v=lXGhCpnxieY
http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze
http://www.wowhead.com/quest=10349/the-earthbinder

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14799-9354-earthbinder-galandria-nightbreeze-smart_scripts/

**Comment by Jenovas** [comment]
Fix in rev 5539
