### ISSUE TITLE
[EN][QUEST][Shattrath City] Fel Armaments

### ISSUE THREAD

**Issue by brabusek** [Atlantiss/BugTracker#9357]
**Description**: Quest thasnt work. 

**Current behaviour**: Ishanah should give quest to colect Fel Armaments. But She doesnt. 

**Expected behaviour**: She should give quest "Fel Armaments" after done "A Cleansing Light"

**Steps to reproduce the problem**:

1. Get into Aldor Tarace.
2. Do "A Cleansing Light" quest. 
3. See nothing.

**Revision**: 
http://www.wowhead.com/quest=10421/fel-armaments

**Comment by tomatosz** [comment]
Did you do the quest chain to actually choose a faction? That could be prerequisite. I had no issues handing in Fel Armaments

**Comment by brabusek** [comment]
holy crap u were right. No one could help me on forum ond in game either.. thanks much for help
