### ISSUE TITLE
[EN][Item] Demonfork

### ISSUE THREAD

**Issue by phixor** [Atlantiss/BugTracker#9358]
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
**Description**: http://www.wowhead.com/item=12621/demonfork HP transfer doesn't work. After 15 mins of white hitting target dummy, my Recount addon haven't recorded any healing done (and as over 264 hits were made during this time, I'm pretty sure that it should proc at last once).

**Current behaviour**: Item's chance on hit never procs.

**Expected behaviour**: It should grant buff that would transfer HP from affected enemy target.

**Steps to reproduce the problem**:

1. Get demonfork.
2. Leave your character hitting target dummy with this weapon for any amount of time.
3. Figure out that it's chance on hit effect never procs.

**Revision**: 5461
**Edit**
here is SS with melee hits dealt, as u can see there were 679 white hits + several additional (due to trink proc) + 1 bloodthirst to measure any self healing
http://imageshack.com/a/img922/6508/HZl9t8.jpg
here is SS with all the healing done during my test
http://imageshack.com/a/img924/3900/JAC8n7.jpg
and heres record of normal healing done, just in case if somebody has any doubts (as i had full hp, all the healing done has been acknowledged as overhealing)
http://imageshack.com/a/img922/6745/1jgjLx.jpg

**Comment by Myivo** [comment]
please ss or some other proof.

**Comment by TranceAccount** [comment]
#8171
