### ISSUE TITLE
[EN][Quest][Blade's Edge Mountains] Baron Sablemane's Poison

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9359]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Wrong [quest](http://www.wowhead.com/quest=10749/baron-sablemanes-poison) text. 

**Current behaviour**:  Last line is wrong, "Now, do be a good little oy : girl, and run this up to Rexxar.

**Expected behaviour**: Should be either boy or girl. "Now, do be a good little <boy/girl> and run this up to Rexxar."

**Steps to reproduce the problem**:

1. Read the quest.

**Revision**: 5461

http://www.wowhead.com/quest=10749/baron-sablemanes-poison

**Comment by TranceAccount** [comment]
Fix by lastguardd:
https://community.atlantiss.eu/index.php?/topic/18482-questblades-edge-mountains-baron-sablemanes-poison/

**Comment by TranceAccount** [comment]
Should be fixed when rev. 5825 goes live. Credits to lastguardd.
