### ISSUE TITLE
[EN] [Dk] [Unholy] Summon Gargoyle:

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9362]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: https://community.atlantiss.eu/index.php?/topic/14116-9111-summon-gargoyle/
https://github.com/Atlantiss/BugTracker/issues/9111

**Current behaviour**: 

**Expected behaviour**: 

**Steps to reproduce the problem**:

1. Still not working, please fix :)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
please read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use) and [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by Heroclassx** [comment]
Just posted #9111 because i already wrote it as you wanted it to be. You posted a fix and closed the topic even tho it is still not working so I thought i might open up a new one, but cba writing everything I already did so just posted the topic since it contains every valid information.

Thank you :)

**Comment by Psychobird7** [comment]
Ctrl+C.      
Ctrl+V.

**Comment by Heroclassx** [comment]
Thank you for sharing your secret tricks with me, whise man.
