### ISSUE TITLE
[EN][Quest][Darkshore] The Bear's Blessing

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#9363]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hi,

Problem with the quest The Bear's Blessing in Darkshore : 
http://www.wowhead.com/quest=13544/the-bears-blessing
https://www.youtube.com/watch?v=u9ravQhUO0k

1. To complete the quest and receive the bear spirit's blessing, we need Bear's Paw Bundle + Fleetfoot's Tailfeathers. The Tailfeathers is obtained by killing the Fleetfoot.

2. The Fleetfoot is friendly so it can't be attacked and killed. 

3. The Fleetfoot should be neutral. 

Thanks for fixing it.

**Comment by Piklo** [comment]
add revision

**Comment by Piklo** [comment]
#2515 duplicate
