### ISSUE TITLE
[EN][Quest][Ashenvale] Return Fire

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#9364]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hi,

Problem with the quest [Return Fire] in Ashenvale : 
http://www.wowhead.com/quest=13853/return-fire

1. To complete the quest, we need to kill 15 Wind Riders but we can't attack these mobs without using the Glaive Throwers but the Glaive Throwers are bugged, we can't get into it.

2. The Glaive Throwers can't be used so the Wind Riders can't be killed and the quest can't be completed. 

3. The Glaive Throwers launch rockets which kill the riders in full flight.

Thanks for fixing it.

**Comment by tomatosz** [comment]
1. Please use the template.
2. Please check whether it has been posted already: #8084 #7311
