### ISSUE TITLE
[EN][NPC][Quest][Icecrown] Koltira Deathweaver

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9369]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The [Koltira Deathweaver](http://www.wowhead.com/npc=29795) quest chain is not as it should be.

**Current behaviour**:  [Koltira Deathweaver](http://www.wowhead.com/npc=29795) (the quest giver) has amany quests available from the start which will ruin the chain and make it confusing if you don't know the quests order.

**Expected behaviour**:  Koltira Deathweaver should give you the chain quests one by one.

**Steps to reproduce the problem**:

1. Do the quests in Icecrown till [No Rest For The Wicked](http://www.wowhead.com/quest=13367).
2. Turn in the quest and check the chain quest order.
3. See that you are missing [The Ironwall Rampart](http://www.wowhead.com/quest=13312) & [No Rest For The Wicked (daily version)](http://www.wowhead.com/quest=13368) and the quest giver is giving you all the chain quest also so you should know that you need [Raise the Barricades](http://www.wowhead.com/quest=13306) also.

**Revision**: 5464.

**Comment by tomatosz** [comment]
You have done [Raise the Barricades](http://www.wowhead.com/quest=13306/raise-the-barricades)? Seems to also be a prereq for The Ironwall Rampart according to the fancy scheme someone posted on wowhead.

**Comment by tomatosz** [comment]
I'll use [this comment](http://www.wowhead.com/quest=13312/the-ironwall-rampart#comments:id=662366) to fix Koltira

**Comment by Samineh** [comment]
Yeah both quests will be available after doing [Raise the Barricades](http://www.wowhead.com/quest=13306) ;). Thank you.

**Comment by tomatosz** [comment]
Posted fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14908-quests-koltira-deathweaver-icecrown/

**Comment by Jenovas** [comment]
Fix in 5538
