### ISSUE TITLE
[EN][Quest][NPC][Gillneas City]: By the skin of his teeth; Worgen Runt

### ISSUE THREAD

**Issue by deadmage** [Atlantiss/BugTracker#9370]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The Worgen Runts spawned after starting the "By the skin of his teeth" quest in the Gillneas City produce error messages when going into frenzy - in the chat window.

**Current behaviour**: Error messages are shown after the Worgen Runts go into frenzy.

**Expected behaviour**: After the Worgen Runts go into frenzy, there should be a clear message saying what happened exactly - Worgen Runt goes into frenzy - for example.

**Steps to reproduce the problem**:

1. Start the By the skin of his teeth quest in the Gillneas City.
2. Wait for the Worgen Runts to spawn and attack you.
3. Observe the chat window when the Worgen Runts go into frenzy.
4. Notice that error messages are shown after the Worgen Runts go into frenzy.

**Revision**: 5464
![unknown](https://user-images.githubusercontent.com/12057043/28497140-6250f152-6f88-11e7-8148-a9d47c5390d8.jpg)

**Comment by TranceAccount** [comment]
Duplicate

**Comment by deadmage** [comment]
Yeah, actually this thing happens on every worgen i've encoutered so far.
