### ISSUE TITLE
[EN][NPC][Quest][Easter Plaguelands] Fiona's Caravan

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9373]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Theres more then 50 spawned caravans.

**Current behaviour**: For some reason Fiona's Caravan is spawned more then 50 time. http://imgur.com/a/LUhVy http://www.wowhead.com/npc=45400/fionas-caravan

**Expected behaviour**: There should be only one.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5464 (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
already reported: #9153
