### ISSUE TITLE
[EN][Quest] Learn to Ride in ...

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9376]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest [Learn to Ride in the Eversong Woods](http://www.wowhead.com/quest=14081/learn-to-ride-in-the-eversong-woods) (and probably the other races too) can't be handed in. (*sigh* you fix one thing, and another bug pops up, I'll probably post a fix once the forums are back, decided to post the bug in the meantime).

**Current behaviour**: You get the [Riding Training Pamphlet](http://www.wowhead.com/item=46882/riding-training-pamphlet) from the mail (yay), can start the quest but can't hand it in.

**Expected behaviour**: You should be able to hand it in to [Perascamin](http://www.wowhead.com/npc=16280/perascamin).

**Steps to reproduce the problem**:

1. Level a blood elf to lvl 20.
2. Check your mail and get the quest item.
3. Walk to Perascamin and note the lack of option to hand the quest in

**Revision**: 5464

**Comment by Piklo** [comment]
"These Learning to Ride quests have been removed prior patches they no longer exist this has even been confirmed from a GM it was something new they wanted to try to get people excited about getting there mounts. It was just temporary"

http://www.wowhead.com/quest=14081/learn-to-ride-in-the-eversong-woods#comments:id=1655631

**Comment by tomatosz** [comment]
Oops, in that case my previous fix (adding the quest item to the mail at lvl 20) also has to be undone.

**Comment by Samineh** [comment]
It is not undone xD u still get the quest items :3.

**Comment by tomatosz** [comment]
@Samineh poke the devs to implement CF fixes :P cause the fix is on the forums: https://community.atlantiss.eu/index.php?/topic/14858-undoing-riding-trainer-pamphlet-lvl20-fix/
