### ISSUE TITLE
Prayer of Mending

### ISSUE THREAD

**Issue by Chiasm** [Atlantiss/BugTracker#9377]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Prayer of Mending critical heal doesn't activate Inspiration (10% reduced physical damage taken).

**Current behaviour**: No Inspiration icon.

**Expected behaviour**: Inspiration icon.

**Steps to reproduce the problem**: 

1. Use only Prayer of Mending on a target.
2. Oh it didn't crit? It's okay if you're level 70 like I am, use it like 30 times because of low crit chance and wait until it crits.
3. See all the Inspiration not going on on the target.

**Revision**: 4.3.4

**Comment by Piklo** [comment]
change title, add proper revision
https://github.com/Atlantiss/BugTracker#how-to-use
https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
