### ISSUE TITLE
[PL][Spell][Mage] Clearcasting

### ISSUE THREAD

**Issue by Binchal** [Atlantiss/BugTracker#9378]
Description: Clearcasting ma za małą szansę na proca

Current behaviour: na 40 castów AB były 3 proce

Expected behaviour: na 10% powinno być więcej proców

Steps to reproduce the problem: 1. castuj arcane blast do czasu az procnie clearcasting

Revision: 5464

**Comment by Psychobird7** [comment]
3 procs over 40 casts is hardly below average. You could easily just have been a little "unlucky".   

If you're going to report a proc rate bug, you should have a statistically significant sample size.

**Comment by Jenovas** [comment]
Closing / Zamykam.
