### ISSUE TITLE
Escape from Silverbrook in Grizzly Hills Buged

### ISSUE THREAD

**Issue by lotus233** [Atlantiss/BugTracker#9381]
Quest works untill NPC jumps on the horse and tells us to jump too which isn't working. It suppose to be working like for example sidecar of Mekgineer's Chopper, we mount up and NPC drives us both to the quest destination. This quest is a part of the main GH chain quest and while bugged it blocks many more quests after, thus unabling us to get Fo' Grizzle My Shizzle achievement 
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED**)

**Comment by tomatosz** [comment]
...
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED**)

You may want to use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md), and add current revision and wowhead links.

**Comment by Bugaevan** [comment]
The problem still exists to this day.

**Comment by Piklo** [comment]
Report was closed because of missing template not fix
