### ISSUE TITLE
[EN] [web] [4.3.4]  login and forum errors

### ISSUE THREAD

**Issue by Judjmentnaut** [Atlantiss/BugTracker#9384]
**Description**: logging in the game results in error message (you have been disconnected from the server)

**Current behaviour**: i played WOW 4.3.4 Cata yesterday, i restarted my pc today and tried to log in using my correct e-mail and password, but when i try to connect a error pops up saying: you have been disconnected from the server. i tried restarting, clearing the WTF folder, still no fix. When i went looking on the forum for fixes the page was down. 
update: when i enter the correct infos (mail and pass) the buttons around the login area fade (like if logged in) for half a second before showing the message and reappear again

**Expected behaviour**: Like yesterday, the game should work just fine

**Comment by Piklo** [comment]
use account name to log in not email

**Comment by Judjmentnaut** [comment]
uh. i feel such an idiot. strange thou, yesterday i was sure to have used my email to log in, it was even saved on the "remember my info" ceckbox. thanks for helping out a poor idiot like myself
