### ISSUE TITLE
[EN][PRIEST SPEEL BUG][MINDCONTROLE]

### ISSUE THREAD

**Issue by nerzoole** [Atlantiss/BugTracker#9385]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: mindcontrole bug

**Current behaviour**: free dps

**Expected behaviour**: free loot

**Steps to reproduce the problem**:you go in bot whit priest use mindcontrol now you can dps the mobs and i can't attack you it is free dps and money and loot 

1. bug speel
2. free dps
3. free loot
https://www.youtube.com/watch?v=HlaMONHWtJs&feature=youtu.be
**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Sayris9876** [comment]
This is so cringy. And about the bug you didnt make a proper post. Even the video is a bit confusing if people dont know what exactly you talking about. Try to fix the post and explain the bug.

**Comment by Piklo** [comment]
please edit your post, add revision and wowhead links
