### ISSUE TITLE
[EN][Spell][Warrior]Charge and Ragnaros

### ISSUE THREAD

**Issue by kabashx** [Atlantiss/BugTracker#9387]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When u reach phase 4 on Ragnaros hc and u wipe. From that moment on you can't charge the boss at all during whole next fights. And that's a huge dps loss.

**Current behaviour**: Warriors cant charge Rag

**Expected behaviour**: Warriors should be able to charge Rag.

**Steps to reproduce the problem**:

1. Enter FL, and bring Rag to phase 4
2. Wipe
3. Fell the pain of not charging

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Elannreportujerzeczy** [comment]
yes, it hurts so much :c

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by kabashx** [comment]
?

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
bump, i cri ewritiem

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by karolnpc** [comment]
bump

**Comment by Smiite** [comment]
HELLO DARKNESS MY OLD FRIEND

**Comment by HUBERTmiszcz** [comment]
bumb iks de

**Comment by HUBERTmiszcz** [comment]
Druid chage(bear form) doesn't work too. 
feels bad

**Comment by kabashx** [comment]
well it doesnt work couse Rag is''bouncing'' after 4p wipe. So its like he is beyond the ground :S

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
daily bump x]

**Comment by Elannreportujerzeczy** [comment]
@zorix jak juz fixujesz spelle to bump x]

**Comment by HUBERTmiszcz** [comment]
bump

**Comment by Elannreportujerzeczy** [comment]
If you can't charge you lose free energy, you lose 25% increased critical strike from Mortal Strike and Slam (Juggernaut talent), less Mortal Strike crit -> less enrage from Wrecking Crew talent (10% increased damage). It's very serious bug, fix it fast
Bump

**Comment by kabashx** [comment]
Elan, how long were u frustrating before i submited this bug? :D

**Comment by lamaATS** [comment]
Because of so many useless `bump`s on my own list this issue has very very low priority.

**Comment by Elannreportujerzeczy** [comment]
@lamaATS now high prio :3

**Comment by lamaATS** [comment]
Much better but still too much.

**Comment by lamaATS** [comment]
When rev 5479 will be on main please check this bug once again. I was unable to reproduce bug but I made one change which can affect this. (Info in change log is not related to this issue)

**Comment by Elannsi** [comment]
@lamaATS Did 25HC yesterday and it works fine. Thank you :>

**Comment by lamaATS** [comment]
@Elannsi Thanks for information.
