### ISSUE TITLE
[PL][Quest][Borean Tundra] Across Transborea

### ISSUE THREAD

**Issue by hexerion** [Atlantiss/BugTracker#939]
Rev: 4162
Dotyczy: www.wowhead.com/quest=11930/across-transborea
NPC Taunka'le Evacuee (http://www.wowhead.com/npc=26159/taunkale-evacuee) przed samym NPC Wartook Iceborn (http://www.wowhead.com/npc=26156/wartook-iceborn) na klifie zapada się w tekstury. Starałem się manewrować postacią, by npc tak dobiegł, by zaliczyło quest, nic to. 

Materiały z yt: https://www.youtube.com/watch?v=kHjjYmlkIoQ  /  https://www.youtube.com/watch?v=tlWRcGcf0fU

**Comment by Satyr87** [comment]
przez ten szajs nie mozna zrobic tych koncowych questow z wrathgate w dragonblight
gdyz:
jest taki potrzebny quest http://www.wowhead.com/quest=11978/into-the-fold i 2 za nim w lancuchu ale jest on odblokowany przez http://www.wowhead.com/quest=11977/a-tauren-among-taunka (do ktorego prowadzi across transborea) LUB http://www.wowhead.com/quest=11979/the-taunka-and-the-tauren ktory sie robi bez komplikacji , problem w tym ze tu warunkiem do podniesienia "into the fold" jest zrobienie obu tych questow zamiast tego albo tego

**Comment by Satyr87** [comment]
moze po prostu ustawcie to tak ze warunkiem spelniajacym questa jest zblizenie sie taunka'le evacuee do wartooka na 50 metrow , bo teraz jest pewnie jakies 5-10 i zwyczajnie dojsc nie moze , spada kawalek przed nim

**Comment by nerv234** [comment]
Warunkiem jest scenka przed ostatnim mostem, quest działa jak powinien.
Postaraj się obejrzeć linki z yt które wstawiasz, zgłoszenie do zamknięcia.

**Comment by Frixus** [comment]
As of right now this quest is not completable.  The npc just falls through the rock before you can get close enough to register the escort as complete.  I have tried many different ways to get the npc close enough to wartook but no matter what it just keeps falling through all the way to the water.

**Comment by hexerion** [comment]
Scenka przed ostatnim mostem, której nie ma :D

**Comment by Satyr87** [comment]
mi sie udalo po 20 probie , tam przed tym mostem trzeba posterczec jak kolek jakis czas az tauren wrzasnie "stop!" i zacznie dramatyzowac , lepiej sie wcale nie ruszac i zaczekac az skonczy i szybko frunac do wartooka jak wyskoczy objective complete , co ciekawe po quescie ten npc nadal lata za toba i jak zdechnie to quest wraca do loga jako failed

**Comment by stanq87** [comment]
aktualnie  quest zbugowany
npc pojawia sie jako nasz pet, martwy, zwloki biegaja za nami i tylko uzywaja emota /cry,   po dojsciu do  znacznika nie zalicza q i nie zazcyna sie 2 faza w ktorej on powinien nas prowadzic do wioski

[https://www.youtube.com/watch?v=_I22EuPmjSU](https://www.youtube.com/watch?v=_I22EuPmjSU)

**Comment by Bildo** [comment]
fixed
