### ISSUE TITLE
[Shaman] [Spell] Flametongue weapon damage

### ISSUE THREAD

**Issue by Tetuz** [Atlantiss/BugTracker#9390]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Flametongue weapon damage is doing way less damage than it should, with my gear it does a third of simmed damage., it seems unaffected by mastery and just a little from attack power.

**Current behaviour**:  Flametongue does ridicolously low damage
just tested it a bit and confronted with simcraft simulation (just the flat damage part, couldn't see if it was changed by ap/mastery procs). My damage (386 ilvl) is between 0,4k and 2,2k (on 331 hits) while simmed one is between 3,3k and 6,6k.
Sorry about huge pics, don't know how to resize them, they show simcraft results and stats, with in-game tests and current stats.
![cattura3](https://user-images.githubusercontent.com/26360436/28747390-d65334a6-749d-11e7-928c-d914745befd7.PNG)
![cattura4](https://user-images.githubusercontent.com/26360436/28747391-d790b816-749d-11e7-8018-01984ddc2831.PNG)
![wowscrnshot_070817_141732](https://user-images.githubusercontent.com/26360436/28747395-e996ba1a-749d-11e7-9dca-4ce6eeaac085.jpg)
![wowscrnshot_070817_141726](https://user-images.githubusercontent.com/26360436/28747396-ea93651c-749d-11e7-8ec1-13ffba8a5666.jpg)
EDIT: did some more tests, removed every proc chance and tested base damage, then equipped mastery trinket and tested again, then removed mastery trinket and used agility totem and +80 agi flask and tested, then tested only with weapon (and relic, forgot to take it off). Results (everytime more than 200 hits)

    1. 13,6k ap, 20.57 mastery, 7% spell crit: 275 hit (94,2% hit and 5.8% crit) avg hit 893, avg crit 1369
    2. 13,6k ap, 22.70 mastery, 7% spell crit: 237 hit (96,2% hit , 3,8% crit) avg hit 922, avg crit 1413
    3. 15,8k ap, 20,57 mastery, 7% spell crit: 267 hit (97% hit, 3% crit) avg hit 880, avg crit 1469
    4. 1,9k ap, 8.88 mastery, 5,38% spell crit: 232 hit (84,5 hit, 13,8% miss, 1,7% crit) avg hit 701, avg crit 1246
    
It seems spell doesn't stack correctly with almost nothing, if someone more expert can make sense of any of this please tell me, got screens if needed.

EDIT 2: done some try on rag hc tonight, so full buffed, flask, food and still flametongue damage is lower than the simmed one with just self buffs. On 222 hit it went from a minimum of 500 to a max of 1905 (avg1049), and on 50 crits min was 785 and max was 3068 (avg 1724). This is a HUGE dps loss, this spec is almost unplayable if you don't want to be just a dead weight to raid, there's almost no enha in fl hc alliance side, most shamans just reroll elemental. Hope it will get fixed.

**Expected behaviour**: Should do way more damage, just look at simmed damage on Simcraft

**Steps to reproduce the problem**:

1. Use flametongue weapon
2. Hit something
3. Look at damage

**Revision**: 5464

**Comment by Prodiege** [comment]
Enhancement definitely does way less dps than it should, this could be part of the problem. Simcraft isn't that great of proof. What I would try to do is find 4.3.4 logs of enhance shamans, or even 4.2 logs of enhance shamans. You can compare the hit/crit damage of the flametongue. En example is: https://github.com/Atlantiss/BugTracker/issues/9382

**Comment by Tetuz** [comment]
Thanks for the reply, i searched on world of logs, don't know how to see which patch was it and what ilvl this shamans got at the moment, but looking at lava lash damage I think it's fl hc gear, like mine (or a bit better). Anyway you can see damage being higher looking at the first enhancement dps on bale hc doing 51k dps (like 18k better than my best dps on same boss) and even if looking at a shaman doing a dps just like mine (around 32k), respectively:
http://www.worldoflogs.com/reports/a4xo91mglw1y9xef/details/7/?s=1057&e=1219 (51k dps, avg 4,5k avg crit 6,9k)
http://www.worldoflogs.com/reports/rt-mtk3uw840xek1cvu/details/1/?s=3897&e=4189 (32k dps, avg 4,3 avg crit 6,6k)
While i'm doing max 2,4k crit on bale hc, raid buffed.
https://www.youtube.com/watch?v=sD9anO-GViY in this video we can see damage being higher ( he probably got better gear, but the difference is to much)
https://cata-twinhead.twinstar.cz/?issue=6366 here i think there are some formulas, but unfortunately i can't understand the language.

**Comment by Prodiege** [comment]
Look at the rest of the abilities and see if they match up in the averages, then you can kind of assume they are in about the same gear. You tell the patch by the upload date

**Comment by Piklo** [comment]
probably spell power / attack power coeff is wrong.

**Comment by Tetuz** [comment]
I'll try to pug a rag hc, already got 6/7 id and don't have recount for baleroc, i'll let you know as soon as i get some data. Did some more testing with simcraft and every spell does almost the same avg damage, there are differences of like 200 +/-, except for flametongue of course.
Flametongue should stack only with attack power for enhas (http://wowwiki.wikia.com/wiki/Flametongue_Weapon) but it seems even mastery coeff could be a bit off.

**Comment by Tetuz** [comment]
Did some try on rag hc and compared damage with other on WoL. Most of them hit less with lava lash but more with every other spell like stormstrike and lightning bolt, maybe it's because being patch 4.2 they were using spell power main hand weapon. Anyway i'm pretty sure they're using firelands gear.
Comparing Flametongue damage with a shaman who did my same dps on last try it's obvious that here it's bugged, my average on 199 hits was 1092 for normal hit and 1772 for crit, while here (http://www.worldoflogs.com/reports/rt-dpdvnpiirgaxfg4f/details/10/?s=5469&e=5774)  you can see hits more than 3 times bigger.

**Comment by Piklo** [comment]
duplicate #8745
