### ISSUE TITLE
[EN][NPC] Randomly being one-shot by various mobs at low level.

### ISSUE THREAD

**Issue by Niarik** [Atlantiss/BugTracker#9391]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Various mobs have now one-shot me for varying amounts. The latest stated the hit was 29 (113 Overkill), which is impossible. Every time this happens, I'm at about half health, been in combat for a few seconds and then just abruptly am dead.

**Current behaviour**: As described above, being overkilled via small hits. I have one screenshot of this in Hillsbrad Foothills versus a Foothill Stalker.

**Expected behaviour**: We exchange hits and I don't have my health zero'd by a low level mob!

**Steps to reproduce the problem**:

1. I'm not sure, it seems random. It's happened to me three times since yesterday, I haven't noticed a pattern and it's not any one specific mob. Attacking the same mob again usually results in normal success. It doesn't appear to be a mob inside the floor that I simply can't see, either. Even approaching the same mob in the same way doesn't reproduce the issue.

**Revision**: 5464

**Comment by TranceAccount** [comment]
Uhmm checked your combat log?

**Comment by Niarik** [comment]
Yeah, every time it showed I'd taken a random hit of 250-odd damage with significant overkill from a mob that normally does hits of somewhere between 20 and 50.

**Comment by Piklo** [comment]
Create a new post, give links to wowhead, npc names etc. Just follow our [how to use](https://github.com/Atlantiss/BugTracker#how-to-use)
