### ISSUE TITLE
[EN][NPC] Kor The Immovable/Berracite

### ISSUE THREAD

**Issue by Draycos99** [Atlantiss/BugTracker#9393]
**Description**: Kor The Immovable and Berracite are not interactable since taking the quests Intervention, Making Things Clear, and Putting The Pieces Together

http://www.wowhead.com/npc=42469/kor-the-immovable
http://www.wowhead.com/npc=43344/berracite

**Current behaviour**: When trying to hand in completed quests (Intervention, Making Things Clear, and Putting The Pieces Together), the NPCs are shown with the quest marker as normal, but they behave as non-hostile mobs (yellow, hostile when attacked). This prevents the quests (and Deepholme quest chain) from being completed.
Abandoning the quests changes the quest marker to available, but the NPCs are still not interactable.

**Expected behaviour**: Kor and Berracite should allow quests to be handed in.

**Steps to reproduce the problem**:
1. Accept the quests Intervention, Making Things Clear, and Putting The Pieces Together from Kor and Berracite.
2. Complete the quests and attempt to hand them in to Kor and Berracite.

**Revision**: ACore rev. 5464

**Comment by tomatosz** [comment]
Turn off 'at war' with Therazane.

**Comment by Piklo** [comment]
as tomatosz said, turn off "at war" with Therazane
