### ISSUE TITLE
[PL][Storm Peaks][bugged phase]

### ISSUE THREAD

**Issue by magion342** [Atlantiss/BugTracker#9396]
Witam mam problem zwiazany  z okolica Engine of the makers a mianowicie nie mam tam zadnych mobkow do zabiacia tylko jakies iron behemoty mi chodza/czlonkowie pt znikaja z mapy i itp 
![bugtracker2](https://user-images.githubusercontent.com/16358596/28767031-78c53ff6-75d2-11e7-8220-948192ef36a5.png)
![bugtracker 4](https://user-images.githubusercontent.com/16358596/28767085-a39e60ae-75d2-11e7-8739-24a91993e1f0.png)

![bug tracker 3](https://user-images.githubusercontent.com/16358596/28766965-36a4d5f0-75d2-11e7-8f22-e5b382b735eb.png)

**Comment by tomatosz** [comment]
Please use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md) and add the subject of the issue to your title (in english), not just the tags.

**Comment by Piklo** [comment]
ticket in game
