### ISSUE TITLE
[EN][Warlock][Spell] Doomguard

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#9401]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Using Doomguard on Phase3 (Aka Nuke phase3) // After Scions.
https://github.com/Atlantiss/BugTracker/issues/8940 - reported aswell here.

**Current behaviour**: Doomguard die from Engulfing, Hammer damage, Hammer Wave, Hammer ground damage thingy, Blazing Heat.

**Expected behaviour**: Be immortal D:

**Steps to reproduce the problem**:

1.  summon doomguard in the most crucial part of Ragnaros.
2.  Die within 10> sec. damage lose, maybe he will cast 1 Shadow bolt, cry.
3. Make doomguard Immortal!

**Revision**:
[23:45:33] ACore rev. 5464 hash. bfa7df19d759 2017-07-20 17:28:09 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by pelekon** [comment]
Personaly I don't know how you manage to allow your doomguard die in less than 10 sec, most of my doomguards on P3 survive whole timer

**Comment by Illusie** [comment]
Does it matter how I manage to 'allow' my doomguard die.
It's not like I want it to die.. It's die because no ignorance // whatever.

I tried summon it few times in different positions (Left // Mid \\ Right) Doesn't matter where he is he dying. And It's pretty annoying.

So here is the Issue I opened in BugTracker. And I hope it will get fixed. Because I'm losing around 800-1m damage done in crucial phase that effect how P4 will look like.

**Comment by Prodiege** [comment]
"Scions die from Engulfing, Hammer damage, Hammer Wave, Hammer ground damage thingy, Blazing Heat."

Replace Scions with Doomguard

**Comment by Psychobird7** [comment]
What he means is, Doomguard and a few other similar guardians are missing their avoidance mechanic, which makes them take reduced AoE damage.      
They should NOT be immortal.

**Comment by zekk3n** [comment]
Guardians, akin to other pets, should have the avoidance buff that reduces damage taken by NPC AoE spells by 90%.

**Comment by Pocketerino** [comment]
boom

**Comment by Piklo** [comment]
#9627 new report for other guardians and with wowhead links
