### ISSUE TITLE
[EN][Quest] [On a Wing and a Prayer]

### ISSUE THREAD

**Issue by asimu26** [Atlantiss/BugTracker#9403]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hello!
My problem is on the quest  [On a Wing and a Prayer]
Quest for the collection of the legendary staff

1. I arrive in the zone of action and after I die constantly
2. Tarecgosa flies in the top and does not come down
3. I can not pass the quest

Sorry screen can not be created for some reason
My nickname in the game Asimu

**Comment by Piklo** [comment]
http://atlantiss.eu/changelog#rev5466
Check quest, when new rev will be on the server. If quest still will be bugged please open new post
