### ISSUE TITLE
[EN][Quest][Legendary] On a wing and a prayer 

### ISSUE THREAD

**Issue by asimu26** [Atlantiss/BugTracker#9405]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hello!
My problem is on the quest [On a Wing and a Prayer]

DID NOT HELP NEW REV
Everything remains as before

Sorry screen can not be created for some reason
My nickname in the game Asimu

When flying over the island of Coldarra, instead of seeing the cinematic the screen goes dark with a warning of "Out of Range". Then the character fall to the ground and dies. The quest objective results unfulfilled.

1.The Northrend instance loading screen briefly appears on screen
2.The screen goes dark and an "Out of range" warning flashes for a second
3.The charachter falls to the ground dying while Tarecgosa remains several yarde above the corpse

**Comment by asimu26** [comment]
When flying over the island of Coldarra, instead of seeing the cinematic the screen goes dark with a warning of "Out of Range". Then the character fall to the ground and dies. The quest objective results unfulfilled.

**Comment by xmesaj2** [comment]
rev. 5466 Author: Bandysc :: 2017-07-25 21:49 - Waiting for update

resubmit the report using correct template when this revision goes live
you can check current revision by typing ".s in" in chat
