### ISSUE TITLE
[EN] Nagrand Arena + Wanted: Zorbo the Advisor do not work.

### ISSUE THREAD

**Issue by Zipper2013** [Atlantiss/BugTracker#9406]
In the Nagrand Arena quest chain the last boss doesn't work, you can kill him, but the quest does not complete.
Wanted: Zorbo the Advisor doesn't work either. Zorbo doesn't even spawn.

**Comment by Piklo** [comment]
please read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use) and follow our [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
