### ISSUE TITLE
[EN][Quest][Icecrown] Mind Tricks

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9411]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The [quest](http://www.wowhead.com/quest=13308) can't be taken.

**Current behaviour**: [Darkspeaker R'khem](http://www.wowhead.com/npc=31892) (the quest giver) won't give you the quest.

**Expected behaviour**: Darkspeaker R'khem has to be chained. He has to give out the quest Mind Tricks and you should be able to free him.

**Steps to reproduce the problem**:

1. Do the Icecrown quests untill you reach [Slaves to Saronite](http://www.wowhead.com/quest=13302).
2. Enter the cave to do the above quest.
3. You will find Darkspeaker R'khem there without any quests.

**Revision**: 5470

**Comment by tomatosz** [comment]
Posted fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14905-quest-mind-tricks/

**Comment by Jenovas** [comment]
Fix in 5538
