### ISSUE TITLE
[EN][Spell][Hunter] Auto Attack

### ISSUE THREAD

**Issue by Lamesshka** [Atlantiss/BugTracker#9417]
**Description**: I've been playing with many other hunters. I can surely say i played with all races that have hunter class available it all looks normal, but recently while playing i've encountered a weird animation bug in which night elf female hangs her head low. Walking towards the target while attacking them with any ranged weapon triggers it.

**Current behaviour**: She hangs her head low while aiming. It looks hilarious 
![obraz](https://user-images.githubusercontent.com/30748312/29081680-770f0c0e-7c63-11e7-8188-e00691149c00.png)

**Expected behaviour**: She should look at her enemies while aiming not under her feet!

**Steps to reproduce the problem**:

1. Wear any ranged weapon (bow, gun, crossbow)
2. Attack something.
3. Walk towards it while attacking.

**Revision**: 5470

**Comment by Piklo** [comment]
ticket in game

**Comment by TranceAccount** [comment]
It is kinda true what he says
