### ISSUE TITLE
[EN] [MAGE] [TALENT] Blazing Speed

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9418]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Gives you a 10% chance when hit by a melee or ranged attack to increase your movement speed by 50% and dispel all effects that prevent movement. This effect lasts 8sec.

**Current behaviour**: It procs from everything, even dots, it is only supposed to proc from melee hits and ranged attacks. But it has a chance on every dmg impact, so versus classes which rely on dots a mage has Blazing speed 24/7

**Expected behaviour**: see current behaviour

**Steps to reproduce the problem**:

1. Use Dots on a Mage with Blazing speed talent
2. dont do any melee und range hits
3. see it proc

**Revision**: ACore rev. 5470

**Comment by kabashx** [comment]
The talent Molten Shields. Maybe thats the reason...

**Comment by Heroclassx** [comment]
fuck you Kabash

**Comment by Heroclassx** [comment]
yeah sadly he is right, my bad guys.

http://wowwiki.wikia.com/wiki/Molten_Shields

**Comment by Heroclassx** [comment]
still not sure about that 10% proc chance, it feels like its up 24/7, cant prove tho.

**Comment by kabashx** [comment]
haha, pleb, learn to read :P

**Comment by Elannreportujerzeczy** [comment]
https://youtu.be/ufJsONfRnMI?t=98
hmm, is it 10% or 90%?

**Comment by Jenovas** [comment]
If a mage is vs a Feral + Rogue it's only normal that Blazing Speed will be up 24/7. Both of  you have like 50% of crit, you melee attack every 1 sec + you use skills that also crit and also can trigger Blazing Speed.

**Comment by xolon** [comment]
https://youtu.be/bK8Qw4ZXFJA?t=3m10s
Further proof that Blazing Speed procs often (Look at the buffs and you can see him reproccing Blazing Speed 4-5 times withing few seconds)

**Comment by xolon** [comment]
Here cause I can't use shoutbox @Heroclassx
