### ISSUE TITLE
[**SQL FIX QUERY**] [EN] [Hunter] Judgement goes through Camouflage

### ISSUE THREAD

**Issue by RealSctr** [Atlantiss/BugTracker#9419]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Judgement goes through Camouflage

**Current behaviour**: Certain spells will go through camo
https://youtu.be/izscOPvhoxM
**Expected behaviour**: Camouflage should ignore any ranged attack. 

**Steps to reproduce the problem**:
1. open HeidiSQL ( or w/e u guys use )
2.  go to query , load this. 
3. INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceEntry`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `NegativeCondition`, `ScriptName`, `Comment`) VALUES 
('17', '20271', '1', '1', '51755', '1', '0', 'Made by Sctr_camo_judgement');

Proof of it working 100%
https://youtu.be/xbqCeKzSF4c
**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
proofs?

**Comment by RealSctr** [comment]
any dev that has database acces has enough proof by that vid

**Comment by Piklo** [comment]
I meant the proof that this is a bug

**Comment by Sayris9876** [comment]
Judgement is considered as mele attack so it works fine its not a bug
