### ISSUE TITLE
Fiona's Caravan

### ISSUE THREAD

**Issue by shaadow82** [Atlantiss/BugTracker#9420]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Upon accepting the quest "Onward, to Light's Hope Chapel" you need to board Fiona's Caravan in Eastern Plaguelands. There are lots of caravans by Fiona. 
**Quest**: http://www.wowhead.com/quest=27373/onward-to-lights-hope-chapel

**Current behaviour**: When you board Fiona's Caravan it doesn't travel to the destination you need to go for the quest. It just sits there and does nothing. 

**Expected behaviour**: It should take you to Crown Guard Tower but nothing happens, and there should only be one caravan. When I'm stuck, I just log out and log back in and fall through the world and die.
 **Screenshot**: 
![bug](https://user-images.githubusercontent.com/29046604/29175153-4459bdfa-7db6-11e7-8575-b489d6b94b3b.png)
![bug1](https://user-images.githubusercontent.com/29046604/29175251-895a0e64-7db6-11e7-8da8-f850571e9f29.png)

**Steps to reproduce the problem**:

1. Go up to Fiona's Caravan
2. Click it
3.  

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
Duplicate

**Comment by Piklo** [comment]
#9153
