### ISSUE TITLE
[EN][Quest][Twilight Highlands] Warm Welcome

### ISSUE THREAD

**Issue by hezuite1112** [Atlantiss/BugTracker#9421]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After end of quest Nightmare (The Maw of Madness chain) in Twilight Highlands, does not appear new quest form Gullock Rockfist named Warm Welcome.

**Current behaviour**: Does not appear ! Over the NPC and you can,t interact with it.

**Expected behaviour**: NPC Should start quest chain Warm Welcome.

**Steps to reproduce the problem**:

1. End quest Nightmare in Twilight Highlands

**Revision**: ACore rev. 5470 hash. a61a7c1953d4 2017-07-30 11:05:36 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)
Online players: 587 (max: 590)
Active connections: 608 (max: 610) Queued connections: 0 (max: 0)
Server uptime: 10 Hour(s) 23 Minute(s) 27 Second(s)
Update time diff: 50. Average time diff: 50.

**Comment by Piklo** [comment]
that part of TH isn't scripted yet
