### ISSUE TITLE
[EN][Quest][Mount Hyjal] Punting Season

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9423]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Description text is wrong. 

**Current behaviour**: In the quest text it says  < name>! instead of your characters name.

**Expected behaviour**: Should say your characters name.

**Steps to reproduce the problem**:

1. Talk to the npc and read the quest.

**Revision**: 5470

http://www.wowhead.com/quest=29101/punting-season

**Comment by TranceAccount** [comment]
Probably someone just copied the text from wowhead and forgot to edit the <name> to $N.

**Comment by Piklo** [comment]
🤦‍♂️  :D

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:
https://community.atlantiss.eu/index.php?/topic/14848-quest-punting-season/
[//]: # ([EN][Web] Armory doesnt work)

**Comment by Jenovas** [comment]
Fix in rev 5538
