### ISSUE TITLE
[EN] [ACHIEVEMENT] HYJAL SUMMIT

### ISSUE THREAD

**Issue by Fireus14** [Atlantiss/BugTracker#9424]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When you finish doing all the Hyjal Summit, after defeating Archimonde, not everyone on the party gets de achievement of this raid.

**Current behaviour**: one guy, after looting Archimonde gets the achievement and everyone who looted him, the ones who don't (or can't because there's nothing more to loot), don't get the achievement.

**Expected behaviour**: Everyone, after defeating archimonde, should get the achievement.

**Steps to reproduce the problem**:

1. Go through all Hyjal summit (the 2 waves per área) and then fight Archimonde
2.  When he's down to 15% of his life, everyone gets killed by him and the NPC's start fighting him.
3.  After one member release spirit and revive the team, not everyone go loot Archimonde, and the one's who did get's the achievement. (The person who release spirit did this while archimonde was fighting with the NPC's, he got the achievement)

**Revision**: Acore rev. 5470

**Comment by Piklo** [comment]
duplicate #8431
