### ISSUE TITLE
[EN][Talent][Paladin] Again Conviction lel

### ISSUE THREAD

**Issue by Drokal** [Atlantiss/BugTracker#9425]
Links: http://wowwiki.wikia.com/wiki/Conviction
          http://wowwiki.wikia.com/wiki/Light_of_Dawn
Other conviction problems: https://github.com/Atlantiss/BugTracker/issues/9318

**Description**: Sick situation, you can stack conviction on other holy paladin with conviction.

**Current behaviour**: Your Light of Dawn critical heals on other paladin are stacking conviction on him.

**Expected behaviour**: Your Light of Dawn critical heals on other paladin should not stack conviction on him.

**Steps to reproduce the problem**:

1. Have two holy paladin with conviction picked in talent tree (IMPORTANT: BOTH OF US HAVE PROBLEM DESCRIBED IN https://github.com/Atlantiss/BugTracker/issues/9318)
2. Use Light of Dawn till you crit on second paladin
3. See the conviction proc on second paladin

**Revision**: 5470

**Comment by Piklo** [comment]
fix is not accepted yet :P
