### ISSUE TITLE
[EN][Quest][Sholazar Basin] The Ape Hunter's Slave 

### ISSUE THREAD

**Issue by Xarit** [Atlantiss/BugTracker#9426]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Describe the problem
I kill the mobs needed for the quest 8/8 and 6/6 but it still says 0/8 0/6

**Current behaviour**: What happens
I kill the mobs needed for the quest 8/8 but it still says 0/8 same with the 0/6
http://www.wowhead.com/npc=28096/hardknuckle-charger
http://www.wowhead.com/npc=28098/hardknuckle-forager

**Expected behaviour**: What should happen instead
It should be 1/8 or 1/6 if i kill a mob (depending on the monkey i kill ofc) if i kill one more it should be 2/8 or 2/6 ect if i kill the other kind.

**Steps to reproduce the problem**:

1. Make the hardnuckle monkeys more alive they just stand in one spot.
2. Make the quest completeable by being able to slain these mobs and make the quest continue.
3. Thats it.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
4.3.4

**Comment by tomatosz** [comment]
Are you sure you weren't raid group? pretty sure I did this quest semi-recently. 
Also, revision would be 5474, not 4.3.4

**Comment by CrypticWizard** [comment]
Further note -- Atlantiss suffers greatly from quests not updating their completion, visually anyhow. Even countless quests that in spite of actually having met completion not reflecting this in the quest log but still eligible for hand-in.

So, it's purely cosmetic in this case.
