### ISSUE TITLE
[EN][NPC][Blasted Lands] Bloodmage Drazial and Bloodmage Lynnore

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9427]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Bloodmage Drazial](http://www.wowhead.com/npc=7505/bloodmage-drazial) and [Bloodmage Lynnore](http://www.wowhead.com/npc=7506/bloodmage-lynnore) have a duplicate spawn.

**Current behaviour**: They are not only spawned in the cave where they should be, but also around 47.5, 12.5.

**Expected behaviour**: They shouldn't be at 47.5,12.5 since Cataclysm.

**Steps to reproduce the problem**:

1. Fly to 47.5,12.5 in Blasted Lands.
2. 
3. 

**Revision**: 5474

**Comment by Piklo** [comment]
https://community.atlantiss.eu/index.php?/topic/14899-npc-bloodmage-lynnore-and-bloodmage-drazial/ fix by tomatosz
