### ISSUE TITLE
[EN][Quest][Blasted Lands] Loramus Thalipedes Awaits

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9431]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest [Loramus Thalipedes Awaits](http://www.wowhead.com/quest=25700/loramus-thalipedes-awaits) is auto-complete.

**Current behaviour**: see description.

**Expected behaviour**: You should click [Bloodmage Lynnore](http://www.wowhead.com/npc=7506/bloodmage-lynnore) and select the gossip option that's available for this quest (I would like to start the Amulet Ritual, Lynnore.) after which she goes through a small script, talking and casting a spell on you. This completes the quest. 
Video: https://www.youtube.com/watch?v=z2pPp-HMOIM .

**Steps to reproduce the problem**:

1. Do the quest chain starting with [Futile Pride](http://www.wowhead.com/quest=25674/futile-pride) (currently Loramus Thalipedes Awaits is available immediately).
2. Get this quest and note that it completes instantly.
3. 

**Revision**: 5474

**Comment by tomatosz** [comment]
Gonna attempt a fix, prolly gonna fail tho =D

**Comment by tomatosz** [comment]
Wut, I actually got it to work on my local server =D

Fix on the forums:
https://community.atlantiss.eu/index.php?/topic/14892-quest-loramus-thalipedes-awaits/

**Comment by Jenovas** [comment]
Fix in 5538
