### ISSUE TITLE
Missing Nyxondra

### ISSUE THREAD

**Issue by shaadow82** [Atlantiss/BugTracker#9433]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: For the quest "Third Sample: Implanted Eggs" Nyxondra will be beside Rhea where you can collect the eggs.

**Current behaviour**: Nyxondra isn't anywhere in sight. She's missing. You can't complete the quest.

**Expected behaviour**: She should be lying down asleep next to Rhea guarding her eggs.

**Steps to reproduce the problem**:

1. Accept the quest "Third Sample: Implanted Eggs"
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by axorian0** [comment]
Agree, i just check it, it is not working

**Comment by Piklo** [comment]
badlands are not scripted yet
