### ISSUE TITLE
[EN][Warlock][Affliction] Corruption and Unstable Affliction lose Snapshot Buff after Haunt and Fel Flame

### ISSUE THREAD

**Issue by Uradopted** [Atlantiss/BugTracker#9435]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
   After using Volcanic Potion, Lifeblood (rank 8), Demon Soul, Rune of Zeth (Firelands Rep Trinket), Power Torrent proc, Apocalypse (T12 4 set), Mithril Stopwatch proc, and Shadow and Flame, Applying buffed Dots (Corruption and Unstable Affliction) will do massive dmg, and should stay that way. However, after all procs wear off, and Corruption is extended by Haunt and Fel Flame extends Unstable affliction, the DoT ticks will decrease to the unbuffed amount. A massive dps loss making Affliction nonviable in raid environments. 
**Links:** 
(https://cynwise.wordpress.com/2011/11/18/how-warlock-dots-work-in-cataclysm-part-ii-dot-refreshing-proc-stacking-and-getting-your-warlock-black-belt/)
(http://forum.warmane.com/showthread.php?t=316459)
(http://www.wowhead.com/forums&topic=164443/clipping-dots-as-affliction)

**Current behaviour**: 
The DoT Tick amounts will change from buffed amounts, to unbuffed amounts. 
**Expected behaviour**: 
The DoTs should remain buffed until the dot completely falls off or is overwritten by a new DoT.

**Steps to reproduce the problem**:
1. Use a macro to use all potions and trinkets when you have optimal procs as stated in Description.
2. Cast Corruption and Unstable Affliction.
3. Check dot amounts.
4. Cast Haunt.
5. Cast Fel Flame.
6. Check new dot amounts.
7. Cry to your massive dps loss. :'(

   Another way to see that your dots are doing enough damage is to look at your recount at the end of the fight. You see that shadow bolt actually does more damage than your dots... Corruption and Unstable Affliction should be doing A LOT more than shadow bolt if working as intended.

**Revision**: 5474

**Comment by kadi2** [comment]
https://cynwise.wordpress.com/2011/11/18/how-warlock-dots-work-in-cataclysm-part-ii-dot-refreshing-proc-stacking-and-getting-your-warlock-black-belt/)

> The only time a DoT updates for buffs on the Warlock is when it’s refreshed, either through a hard cast or a refreshing ability (i.e. Everlasting Affliction, Pandemic, or Fel Flame). This is a change from how things worked in Wrath, which contributes to the confusion.

Are you for real?

**Comment by Uradopted** [comment]
First off, fel flame does not "refresh" but increases the duration by six seconds. And furthermore, if you casted unstable affliction with only rune of zeth proc, the tick amount changes after wear off and without casting fel flame. Also, do you notice that haunt isnt included in that list? Im surprised about how much you know about wow mechanics.

**Comment by kadi2** [comment]
@Uradopted Did you realize that you didn't post any proof for your bullshits? I know you want this broken and bugged mechanic that still exists on lolten to be imported in here. Similar machanic you present us existed only in WOTLK with corruption and for few patches in MOP. This mechanic never had a place during Cataclysm.

**Comment by Piklo** [comment]
https://us.battle.net/forums/en/wow/topic/3729953542#post-16
