### ISSUE TITLE
[EN][Quest][Searing Gorge] Lunk's Adventure : Rendan's Weakness #28034

### ISSUE THREAD

**Issue by Diieuu** [Atlantiss/BugTracker#9438]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: This quest is not working as intended

**Current behaviour**: The Iron Summit Guards are not anymore spawned in the Iron Summit but at the middle of The Cauldron so we can't valid the quest

**Expected behaviour**: There are supposed to be 3 Iron Summit Guards in the Iron Summit camp in Searing Gorge that we can talk with and incite them to dance and valid the quest.

**Steps to reproduce the problem**:

1. Make the Iron Summit Guards spawn at their right place (http://www.wowhead.com/npc=47434/iron-summit-guard)
2. Make possible to talk to them to make them dance
3. Valid the quest objective

**Revision**: 5474

**Comment by tomatosz** [comment]
Duplicate: #3315

**Comment by Piklo** [comment]
@tomatosz same quest, other bug

**Comment by tomatosz** [comment]
@Piklo I thought bugs relating to the same quest were gathered in the same issue, my bad.

**Comment by Ressin** [comment]
It is possible to talk to them and to complete the quest. If you have a problem with it try retaking the quest/wait for server restart or simply relog, in my case one of these helped and when I took quest for the third time I was able to talk to the dwarves.

**Comment by xmesaj2** [comment]
after rev. 5514 guards should respawn properly
