### ISSUE TITLE
Twilight Highlands intro event glitched the whole world

### ISSUE THREAD

**Issue by DaMouse7** [Atlantiss/BugTracker#9439]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Was doing the intro to twilight highlands, now every mob and npc in the world on every continent is not there.
**Current behaviour**: What happens
I cant do anything anymore besides queue for dungeons
**Expected behaviour**: What should happen instead
I should be able to continue the quest chain
**Steps to reproduce the problem**:
There are none this section is pointless for my issue
1. Tried abandoning new quests entitled "Cementing Our Victory" and "Muddied Waters"
2. Again, no change.
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev 5474 hash. 66c24f358e10 2017-08-16 00:31:31 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by CrypticWizard** [comment]
I had a similar issue on an 85 Shaman a while back. I started the Wildhammer wedding even while in Ghost Wolf form and that somehow caused the entire gameworld to become empty.

Or, rather, what actually happened for both you and me -- an instance was created for whatever event we were engaged in and a bug of some sort failed to populate that instance.

The only fix I could find was to force myself out of that instanced gameworld, by dying. Dying has the secondary effect of flushing your character's state. So, if you're still stuck -- die and walk back to your corpse, it should reset your character to the proper state and with it, the normal gameworld should become available to you again.

**Comment by TranceAccount** [comment]
You could also create a ticket if what CrypticWizard says doesn't work.

**Comment by Piklo** [comment]
open a ticket in game
