### ISSUE TITLE
[EN][Lost City of the Tol'vir][NPC]  Blaze of the Heavens

### ISSUE THREAD

**Issue by Raamzey** [Atlantiss/BugTracker#944]
NPC http://cata.openwow.com/npc=48906
NPC Spell http://cata.openwow.com/spell=91185

After a wipe Blaze of the Heavens (Npc) didn't despawn. Instead it remained alive with a dot that damaged it, but it was regenerating fast to 100% hp.
Later there were two Blazes when we encountered the boss again.

Screenshots:
http://postimg.org/image/bsqukobsn/
http://postimg.org/image/9csipkier/

**Comment by qubuslabadz** [comment]
Fixed in rev. 4300.
