### ISSUE TITLE
[EN][NPC] Venomhide Hatchling

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9442]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Your [Venomhide Hatchling](http://www.wowhead.com/item=46362/venomhide-hatchling) gives you dailies for the quest [They Grow Up So Fast](http://www.wowhead.com/quest=13906/they-grow-up-so-fast).

**Current behaviour**: He gives all dailies.

**Expected behaviour**: He should only give 1 daily a day.

**Steps to reproduce the problem**:

1.  Do quests to get Venomhide Hatchling
2.  See that he gives you all the dailies
3. 

**Revision**: 5474

http://www.wowhead.com/item=46362/venomhide-hatchling
http://www.wowhead.com/quest=13906/they-grow-up-so-fast
http://www.wowhead.com/item=47196/venomhide-baby-tooth

The quests he gives: 
http://www.wowhead.com/quest=13903/gorishi-grub
http://www.wowhead.com/quest=13889/hungry-hungry-hatchling
http://www.wowhead.com/quest=13904/poached-scrambled-or-raw
http://www.wowhead.com/quest=13905/searing-roc-feathers

**Comment by tomatosz** [comment]
More specifically, you can get anywhere from 1 to 5 dailies on one day (a quest can duplicate).

**Comment by TranceAccount** [comment]
Are you sure these are the correct quest ids?

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18260-npc-venomhide-hatchling/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
