### ISSUE TITLE
[EN][Item] Highland Pomegranate

### ISSUE THREAD

**Issue by AngryEndUser** [Atlantiss/BugTracker#9445]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The food [Highland Pomegranate](http://www.wowhead.com/item=58265/highland-pomegranate) is currently sold for 2g each. The correct value is indeed 2g, but [it should be 2g per stack of 5](http://i.imgur.com/Yml7X9Z.png).

**Current behaviour**: http://i.imgur.com/egH9B6q.png (1g 62s because of honored 10% faction discount + Bartering Guild guild perk 10% discount = 0.9 * 0.9 * 2 = 1.62)

**Expected behaviour**: 2g per stack of 5.

**Steps to reproduce the problem**:

1.  Go to any innkeeper in any major city (except Undercity and Exodar), or Umi in Uldum, or some innkeepers in Twilight Highlands.
2. Check the price of Highland Pomegranates.

**Revision**: 5474

**Comment by TranceAccount** [comment]
This is pretty much the case for most vendors with mana drinks.

**Comment by Navedonar** [comment]
Fix https://community.atlantiss.eu/index.php?/topic/18265-item-highland-pomegranate/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)

**Comment by TranceAccount** [comment]
Did it even change any rows? Because I think it was already like this

**Comment by TranceAccount** [comment]
Fix did not work.

**Comment by TranceAccount** [comment]
www.wowhead.com/item=8529/noggenfogger-elixir
Should also be sold in stacks of 5

**Comment by TranceAccount** [comment]
Fixed in rev. 5855.
