### ISSUE TITLE
[PL][RAID][FIERLANDS] Ragnaros

### ISSUE THREAD

**Issue by MrBiggi** [Atlantiss/BugTracker#9447]
**Description**: Molten Elemental bijo silno

**Current behaviour**: Molten Elemenatl robią sie na norme ragnarosie w hc mobki

**Expected behaviour**: bijo silno

**Steps to reproduce the problem**: naprafcie 

1. Molten Elemental bijo mocno
2. wajpy i wgl bijo
3. fix it. 
Elo

**Comment by Piklo** [comment]
duplicate #9432
