### ISSUE TITLE
[EN][NPC] Adana Thunderhorn

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9448]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Adana Thunderhorn](http://www.wowhead.com/npc=36694/adana-thunderhorn) gives quests in wrong order.

**Current behaviour**: You can get [Rite of Courage](http://www.wowhead.com/quest=14456/rite-of-courage), [Stop the Thorncallers](http://www.wowhead.com/quest=14455/stop-the-thorncallers), [The Battleboars](http://www.wowhead.com/quest=14459/the-battleboars) and [Feed of Evil](http://www.wowhead.com/quest=14461/feed-of-evil) all at once.

**Expected behaviour**:  You should do [Rite of Courage](http://www.wowhead.com/quest=14456/rite-of-courage) and [Stop the Thorncallers](http://www.wowhead.com/quest=14455/stop-the-thorncallers) first before you can do [The Battleboars](http://www.wowhead.com/quest=14459/the-battleboars) and [Feed of Evil](http://www.wowhead.com/quest=14461/feed-of-evil). 

**Steps to reproduce the problem**:

1. Finish your quests all up to Go to Adana
2. Talk to her

**Revision**: 5474

https://wow.gamepedia.com/Quest:Go_to_Adana
http://www.wowhead.com/quest=14456/rite-of-courage
http://www.wowhead.com/quest=14455/stop-the-thorncallers
http://www.wowhead.com/quest=14461/feed-of-evil
http://www.wowhead.com/quest=14459/the-battleboars

**Comment by arvit** [comment]
1.H [1] The First Step
    2.H [2] Rite of Strength
    3.H [2] Our Tribe, Imprisoned
    4.H [2] Go to Adana
    5.H [3] Rite of Courage / H [3] Stop the Thorncallers
    6.H [4] The Battleboars / H [4] Feed of Evil
    7.H [5] Rite of Honor
    8.H [5] Last Rites, First Rites
    9.H [5] Rites of the Earthmother
  10.H [5] Rite of the Winds (to Bloodhoof Village)

**Comment by tomatosz** [comment]
Posted a fix on the forums (i think...) 

https://community.atlantiss.eu/index.php?/topic/14983-quests-mulgore-quest-order/

**Comment by Jenovas** [comment]
Fix in rev 5538
