### ISSUE TITLE
[EN][NPC] Mull Thunderhorn

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9452]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [Mull Thunderhorn](http://www.wowhead.com/npc=2948/mull-thunderhorn) gives quests in wrong order.

**Current behaviour**: You can get [Poison Water](http://www.wowhead.com/quest=20440/poison-water) and [Winterhoof Cleansing](http://www.wowhead.com/quest=24440/winterhoof-cleansing) at the same time.

**Expected behaviour**: You should do [Poison Water](http://www.wowhead.com/quest=20440/poison-water) first before you can do [Winterhoof Cleansing
](http://www.wowhead.com/quest=24440/winterhoof-cleansing)
**Steps to reproduce the problem**:

1.  Talk to [Mull Thunderhorn](http://www.wowhead.com/npc=2948/mull-thunderhorn) as a Tauren (Tauren only quest)

**Revision**: 5480

http://www.wowhead.com/npc=2948/mull-thunderhorn
http://www.wowhead.com/quest=20440/poison-water
http://www.wowhead.com/quest=24440/winterhoof-cleansing

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14983-quests-mulgore-quest-order/

**Comment by Jenovas** [comment]
Fix in rev 5538
