### ISSUE TITLE
[EN][Quest][Zone] Make Haste to Stormwind

### ISSUE THREAD

**Issue by deadspear** [Atlantiss/BugTracker#9455]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest cannot be taken or completed.

**Current behaviour**: The quest cannot be taken or completed only a blue question mark is above the notice board in Dalaran.

**Expected behaviour**: http://www.wowhead.com/quest=29071/make-haste-to-stormwind Complete the quest and receive a heart stone to Stormwind.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5480 Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
You can only complete it once, yet it is still a bug that the board has the blue question mark.

**Comment by deadspear** [comment]
I never completed it.

**Comment by wtRCH** [comment]
fix pending
