### ISSUE TITLE
[PL][Quest][Zone] Unexpected Results (quest=8488)

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/BugTracker#9462]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  After picking up a quest from NPC, monster should start to not only appear but start to attack player too. After abandoning quest mobs don't despawn.

**Current behaviour**: As stated above

**Expected behaviour**: After taking a quest mobs should spawn and immidiately aggro on player. If a group of players do this quest (in a party) only one copy of each should appear. After abandoning the quest mobs should despawn.
**Steps to reproduce the problem**:

1. Video: https://www.youtube.com/watch?v=2AEHXqSM-R8
2. Proof, that nothing has changed: http://wowwiki.wikia.com/wiki/Quest:Unexpected_Results

**Revision**: 5482 (you can see current server revision by typing ".server info" command in the game chat)

**Comment by CrypticWizard** [comment]
Duplicate: https://github.com/Atlantiss/BugTracker/issues/1813
Workaround: Before taking the quest, kill off all the mobs in front of her. Then, take the quest and kill the named mob ( Gharsul the Remorseless ). It should complete.

**Comment by wtRCH** [comment]
I know, done it but it's still a bug and not working as Blizzlike

**Comment by Piklo** [comment]
wowhead links

**Comment by CrypticWizard** [comment]
Quest:

http://www.wowhead.com/quest=8488/unexpected-results

Quest giver:

http://www.wowhead.com/npc=15402/apprentice-mirveda

**Comment by Piklo** [comment]
posted fix on forum
https://community.atlantiss.eu/index.php?/topic/15444-9462-apprentice-mirveda-sai/

**Comment by TranceAccount** [comment]
@Piklo Any news?

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still persists.
