### ISSUE TITLE
[EN][Spell][Hunter]Fire!

### ISSUE THREAD

**Issue by Sayris9876** [Atlantiss/BugTracker#9465]
**Description**: MM Hunter talent "Master marksman" allows you to stack a buff called "Ready, Set, Aim...". On 5 stacks of this buff the hunter gets that "Fire!" buff which allows him to use "Aimed shot" as instant cast and free of focus. I assume the "Fire!" buff is the issue?

You can see the 3 step process talent/buffs here: http://wowwiki.wikia.com/wiki/Master_Marksman

**Current behaviour**: When you get the "Fire!" proc you fire off the instant Aimed shot but the buff stays until the arrow hits the target leading to potential 2 up to 3 (on Ragnaros) instant Aimed shots.

**Expected behaviour**: The "Fire!" buff should disappear as soon as the Aimed shot is used. As of now the buff disappears when the first Aimed shot interacts with the target.

**Steps to reproduce the problem**:

1. Go to dummy at max range or Ragnaros (where the interact range is longer)
2. Stack up "Ready. Set. Aim..." to 5 stacks
3. Start spamming Aimed shots and check how many you can fire off until first Aimed interacts with boss.

World second kill of Rag as proof. Check between 4:20 and 4:30 the hunter spamming Steady shots and as soon as he uses "Fire!" buff (the instant aimed shot) he can no longer use it:
https://youtu.be/0YG2KKvLcLc?t=259

Here I made small video from our server. I know its bad quality but you still can see the 2x Aimed shots from the Scrolling Combat text (and recount).
https://www.youtube.com/watch?v=EHUdyAm4ylU

Edit: Forgot to add that in situations where "Fire!" proc happens while you already have hard casted Aimed shot flying towards the boss when that Aimed shot hits the boss "Fire!" gets consumed. This one I am not sure if it suppose to be like that or not but just adding it for more info.
**Revision**: 5482

**Comment by CrypticWizard** [comment]
Regarding your original bug report:

If that truly is what happens then that is definitely not Blizzlike.

Regarding your edit:

That is definitely not Blizzlike either.

It does indeed sound like Aimed Shot hitting something is the key trigger to consume the proc. Which does in fact explain both points. This obviously is not Blizzlike-behaviour. The cast of the ability should be the moment of proc-consumption. As was always the intended design for this particular proc. As it stands now, getting a proc is an immense burst of DPS. Get a proc while having low latency and high FPS and you're going to be able to spam who knows how many Aimed Shots. I could definitely see 4 being possible. Far more than was ever the goal -- Just the one.

**Comment by lamaATS** [comment]
Fixed in rev. 5491
