### ISSUE TITLE
[EN][Quest][Dalaran] Waterlogged Recipe

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9466]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  The quest doesn't give any Dalaran cooking rewards, while it should give 5 of them.

**Steps to reproduce the problem**:

1.  Do fishing daily in Dalaran.
2.  Get Bag of Fishing Treasures
3.  Be lucky that it drops Waterlogged Recipe

**Revision**: 5482
Not sure which version this patch is using so I linked a bunch.

http://www.wowhead.com/search?q=Waterlogged+Recipe
http://www.wowhead.com/quest=24431/waterlogged-recipe
http://www.wowhead.com/quest=14203/waterlogged-recipe
http://www.wowhead.com/item=43016/dalaran-cooking-award
http://www.wowhead.com/item=49667/waterlogged-recipe

**Comment by tomatosz** [comment]
Fix is already on the forums, just have to wait for it to be implemented

**Comment by tomatosz** [comment]
https://community.atlantiss.eu/index.php?/topic/14745-waterlogged-recipe-reward/

**Comment by Jenovas** [comment]
Fix in 5539
