### ISSUE TITLE
[EN][Npc][Drop] Darnassian Scout

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9473]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Problem with [Incriminating Documents](http://www.wowhead.com/item=20765/incriminating-documents)

**Current behaviour**: [Darnassian Scout](http://www.wowhead.com/npc=15968/darnassian-scout) doesn't always drop [Incriminating Documents](http://www.wowhead.com/item=20765/incriminating-documents)

**Expected behaviour**: If you haven't done the quest [Incriminating Documents](http://www.wowhead.com/quest=8482/incriminating-documents) or have the item already then it should drop 100%

**Steps to reproduce the problem**:

1.  Kill [Darnassian Scout](http://www.wowhead.com/npc=15968/darnassian-scout)
2.  See that it doesn't always drop Incriminating Documents (still high % chance that it does)  

**Revision**: 5482

http://us.battle.net/wow/en/item/20765
http://www.wowhead.com/npc=15968/darnassian-scout
http://www.wowhead.com/item=20765/incriminating-documents
http://www.wowhead.com/quest=8482/incriminating-documents

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15288-9473-darnassian-scout-creature_loot_template/

**Comment by Jenovas** [comment]
Fix in 5537
