### ISSUE TITLE
[PL][Zone][Darkshore - Tower of Althalaxx]

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/BugTracker#9479]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: NPC in purple cloths (https://i.gyazo.com/f3ac4781d25b4c4977a2ec984d3f2c71.png)

**Current behaviour**: NPC are standing instead of lying dead

**Expected behaviour**: Every NPC looking like that (https://i.gyazo.com/f3ac4781d25b4c4977a2ec984d3f2c71.png) in this zone should be lying dead instead of standing

**Steps to reproduce the problem**:

1. Make them lying dead
2. Proof, watch video: https://www.youtube.com/watch?v=zNadfO3rJCM

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/15553-npc-dark-strand-victim/

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
