### ISSUE TITLE
[EN][Item] Seal of the Seven Signs

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9487]
**Description**: DS trinket

**Current behaviour**: Nothing yet

**Expected behaviour**: Seal of the Seven Signs, all versions:
- LFR: http://www.wowhead.com/item=77969 ; uses http://www.wowhead.com/spell=109803 and grants http://www.wowhead.com/spell=109802 
- Normal: http://www.wowhead.com/item=77204 ; uses http://www.wowhead.com/spell=107984 and grants http://www.wowhead.com/spell=107982 
- Heroic: http://www.wowhead.com/item=77989 ; uses http://www.wowhead.com/spell=109805 and grants http://www.wowhead.com/spell=109804 

All of these are shown to be a 15% proc chance on active heal, and a 115s ICD. 

Other sources: 
http://www.wowhead.com/spell=107982/velocity#comments:id=1595095 
http://www.wowhead.com/item=77204/seal-of-the-seven-signs#comments:id=1585624 
http://www.wowhead.com/item=77969/seal-of-the-seven-signs#comments:id=1595875 
ICD modelled to be 115s by Rawr. 

**Steps to reproduce the problem**:

1. Cat. 

**Revision**: 5482

**Comment by pelekon** [comment]
Fixed in rev 5568
