### ISSUE TITLE
[EN][Item] Soulshifter Vortex

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9488]
**Description**: DS trinket 

**Current behaviour**: Nothing yet 

**Expected behaviour**: Soulshifter Vortex, all versions: 
- LFR: http://www.wowhead.com/item=77970 ; uses http://www.wowhead.com/spell=109775 and grants http://www.wowhead.com/spell=109774 
- Normal: http://www.wowhead.com/item=77206 ; uses http://www.wowhead.com/spell=107987 and grants http://www.wowhead.com/spell=107986 
- Heroic: http://www.wowhead.com/item=77990 ; uses http://www.wowhead.com/spell=109777 and grants http://www.wowhead.com/spell=109776 

All versions of this trinket are a 15% proc chance, on a 115s ICD. 
Simcraft models it to proc off *any* damage dealt, while Rawr shows it to be limited to Melee attacks. 

Other sources: 
- Simcraft: trinket2=soulshifter_vortex,heroic=1,ilevel=410,quality=epic,stats=775sta,equip=ondamage_3278mastery_15%_20dur_115cd,suffix=0 
- Could not confirm whether it should proc off melees only, or all forms of damage. Warlocks will suggest all forms of damage, theorycrafting tools differ. 
- A retail video shows it triggering from a Frost mage's spells, This suggests it does trigger off *any* damage dealt by the player. https://youtu.be/y7tIIzF6o8k?t=160 ; watch the top right corner for the icon resembling Arcane Tactics's. **The ICD mentioned in this video is incorrect. The correct ICD is 115s, as listed higher up in this report.** 

**Steps to reproduce the problem**:

1. Beep 

**Revision**: 5482

**Comment by blinkmaster** [comment]
All types of damage (See cartoonz Best mage trinket suggest on 4.3 - even tho hes wrong xd)

**Comment by pelekon** [comment]
Fixed in rev 5568
