### ISSUE TITLE
[EN][Item] Bone-Link Fetish 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9490]
**Description**: DS trinket 

**Current behaviour**: Nothing yet 

**Expected behaviour**: Bone-Link Fetish, all versions: 
- LFR: http://www.wowhead.com/item=77982 ; uses http://www.wowhead.com/spell=109753 and triggers http://www.wowhead.com/spell=109752 [Value: 8029 to 12044 (AP mod: 1.196)] 
- Normal: http://www.wowhead.com/item=77210 ; uses http://www.wowhead.com/spell=107998 and triggers http://www.wowhead.com/spell=107997 [Value: 9063 to 13594 (AP mod: 1.35)] 
- Heroic:  http://www.wowhead.com/item=78002 ; uses http://www.wowhead.com/spell=109755 and triggers http://www.wowhead.com/spell=109754 [Value: 10230 to 15345 (AP mod: 1.524)] 

All versions of this trinket are a 15% proc chance, and a 25s ICD. 
Rawr models it to only proc off melee attacks. 

Damage: 
- The spell used by this trinket, called Whirling Maw, casts a whirlwind dealing physical damage to *all* enemies within 10 yards of the bearer. 
- LFR: ~~8029 to 12044 (AP mod: 1.196) (wowhead)~~ // 8029 to 12044 (AP mod: 0.598) (Simcraft) 
- Normal: ~~9063 to 13594 (AP mod: 1.35) (wowhead)~~ // 9063 to 13594 (AP mod: 0.675) (Simcraft) 
- Heroic: ~~10230 to 15345 (AP mod: 1.524) (wowhead)~~ // 10230 to 15345 (AP mod: 0.762) (Simcraft) 
- Damage values vary depending on source. Considering armour reduction, and damage reported or observed in raids, math suggests Simcraft's values, as listed above, are closer to correct. -- SpellWorks seems to confirm Simcraft's values are correct. 
- This is affected by **all** physical damage modifiers, including passives, as well as temporary buffs and debuffs. 
- Whirling Maw can crit, using physical crit chance, and benefit from meta gems, but cannot miss. 

Other sources: 
- http://www.wowhead.com/item=78002/bone-link-fetish#comments:id=1668874 
- Damage was double-checked against T12 and T13 BiS geared Ret paladin and Arms warrior AP values, and aligns with previous findings. 
- http://worldoflogs.com/reports/rt-z4ulpkw9q4v549o3/details/14/?s=881&e=1237 (see Damage by Spell) 
- http://worldoflogs.com/reports/rt-z4ulpkw9q4v549o3/details/3/?s=881&e=1237 (see Damage by Spell) 
- http://worldoflogs.com/reports/1316s7owmwfqv1ov/details/22/?s=68&e=365 (see Damage by spell) 

**Steps to reproduce the problem**:

1. LUL 

**Revision**: 5482

**Comment by pelekon** [comment]
Fixed in rev 5568
