### ISSUE TITLE
[EN][Item] Vial of Shadows 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9493]
**Description**: DS Trinket

**Current behaviour**: Nothing yet 

**Expected behaviour**: Vial of Shadows, all versions 
- LFR: http://www.wowhead.com/item=77979 ; uses http://www.wowhead.com/spell=109722 and triggers http://www.wowhead.com/spell=109721 
- Normal: http://www.wowhead.com/item=77207 ; uses http://www.wowhead.com/spell=107995 and triggers http://www.wowhead.com/spell=107994 
- Heroic: http://www.wowhead.com/item=77999 ; uses http://www.wowhead.com/spell=109725 and triggers http://www.wowhead.com/spell=109724 

All of these have a 45% proc chance (15% in 4.3, tripled to 45% in 4.3.2) on melee or ranged physical attacks, and a 9s ICD. 

**There is no hard data on this trinket's exact damage range or scaling, so the above are determined based on web-archived wowhead stats, wowhead comments, Simcraft, and post-4.3.2 logs. 
These numbers do however all line up with data from logs and several theorycrafting tools, and I can say with a high degree of confidence that they are close to, if not, correct.** 

Damage: 
- The spell called Lightning Strike grants an on-hit that deals physical damage to a single target. 
- LFR: 3568 to 5353 (confirmed) (AP mod: 0.266) 
- Normal: 4028 to 6042 (confirmed) (AP mod: 0.3) 
- Heroic: 4546 to 6819 (confirmed) (AP mod: 0.339) 
- These are affected by **all** physical damage modifiers, including passives, as well as temporary buffs and debuffs. 
- They can crit, using physical crit chance, and benefit from meta gems, but cannot miss. 

Other sources: 
-- Base damage: 
- SpellWorks 4.3.4 ; 
- https://web.archive.org/web/20120620142331/http://www.wowhead.com/item=77979 
- https://web.archive.org/web/20120505111713/http://www.wowhead.com/item=77207 
- https://web.archive.org/web/20120505111059/http://www.wowhead.com/item=77999 
- Rawr contains the pre-nerf, average base damages for Normal (15105) and Heroic (17050) Vial, which align with the post-nerf damage ranges I was able to find in Simcraft and on Wowhead. 

-- AP Scaling: 
- https://web.archive.org/web/20120505111713/http://www.wowhead.com/item=77207#comments:id=1574792:reply=283301 
- The above is a comment from 4.3.0 (pre-nerf) and states: "The AP scaling coefficients are 0.797 for 384 version, 0.9 for 397 version and 1.016 for 410 version (data mined from game files)." 
- Divide these by 3 to obtain the modifiers listed under "Damage". 
- Damage was double-checked against T13 BiS geared survival Hunters and Rogues, and matches previous findings. The following are short fights, and feature high uptime Agility buffs, so the averages are higher than they usually would be, but are well within determined ranges. 
- http://worldoflogs.com/reports/2asn130hb94jiwn6/details/5/?s=3527&e=3695 (see Damage by spell) 
- http://worldoflogs.com/reports/h0ldviygss1280su/details/23/?s=2630&e=2827 (see Damage by spell: Blitzeinschlag) 

**Steps to reproduce the problem**:

1. :cry: :gun: 

**Revision**: 5482

**Comment by pelekon** [comment]
Fixed in rev 5568

**Comment by ZappBrannigan93** [comment]
I confirm the behaviour for the hunter and the fact that this was fixed on retail. 
Is it going to be fixed here as well? 
Thanks.
