### ISSUE TITLE
[EN][Item] Windward Heart 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9494]
**Description**: DS Trinket 

**Current behaviour**: Nothing 

**Expected behaviour**: Windward Heart, all versions: 
- LFR: http://www.wowhead.com/item=77981 ; uses http://www.wowhead.com/spell=109823 and triggers http://www.wowhead.com/spell=109822 
- Normal: http://www.wowhead.com/item=77209 ; uses http://www.wowhead.com/spell=108002 and triggers http://www.wowhead.com/spell=108000 
- Heroic: http://www.wowhead.com/item=78001 ; uses http://www.wowhead.com/spell=109826 and triggers http://www.wowhead.com/spell=109825 

This trinket's effect procs off any critical healing, including HoT ticks, and benefits from Resto shaman's mastery, as well as other multipliers. 
It will target a low Health party/raid member, similar to Atonement's mechanic. 
Range seems to be 40 yards, although this is not confirmed. 
ICD has been reported to be 20s to 25s, with 20s being the more likely option as the tester reporting 25s was a Holy Paladin. 

Healing: 
- LFR: 9203 to 10696 (SP mod: 1.107) 
- Normal: 10388 to 12073 (SP mod: 1.25) 
- Heroic: 11726 to 13627 (SP mod: 1.411) 
- Healing numbers and SP coeffs confirmed by Wowhead and SpellWorks. 

Additional sources: 
- http://www.wowhead.com/item=77209/windward-heart#comments:id=1584021 
- http://www.wowhead.com/item=77209/windward-heart#comments:id=1571958 

**Steps to reproduce the problem**:

1. B

**Revision**: 5482

**Comment by pelekon** [comment]
Fixed in rev 5568
