### ISSUE TITLE
[EN][spell][Hunter] Freezing trap possession prioritize is currently not working

### ISSUE THREAD

**Issue by RealSctr** [Atlantiss/BugTracker#9500]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hunter's Trap hitbox beeing to big and not working correclty. 

**Current behaviour**: Currently the traps work in a way I can best describe with a small video I made
https://youtu.be/8vyw69OEkrI 

**Expected behaviour**:  Place a frost trap that freezes the first enemy that approaches, preventing all action for up to 1 min.  Any damage caused will break the ice.  Trap will exist for 1 min.
*WHEN 2 or MORE players are on the trap location* : The trap should  prioritize the player / npc most CENTRAL to the trap radius. 

Example: https://youtu.be/4msAkuQcbJI

**Steps to reproduce the problem**:

1. Decrease Trap hitbox(radius) to the correct visual icon(with trap launcher on)
2. Change freezing trap prioritize to closest invoker. 

**Revision**: ACore rev. 5482

**Comment by lamaATS** [comment]
Fixed in rev. 5498
