### ISSUE TITLE
tame beast not working 

### ISSUE THREAD

**Issue by zuukotv** [Atlantiss/BugTracker#9502]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
tame beast not working correctly currently not taming beast pets please fix
**Current behaviour**: What happens
it casts tame beast like normal but does not tame the beast it self please fix it so you can tame beasts...
**Expected behaviour**: What should happen instead
when tame beast reaches its full cast it should tame the beast that it is currently taming 
**Steps to reproduce the problem**:

1. fix tame beast
2. fix it
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by CrypticWizard** [comment]
Even though this was closed and is actually fairly rude as well, I'll offer an explanation on what might have been happening:

Tame Beast will only work if you have an available Call Pet slot. So, visit a stable master to make sure of that.
