### ISSUE TITLE
[EN][spell][Hunter] Hunter's mark breaks Camouflage 

### ISSUE THREAD

**Issue by RealSctr** [Atlantiss/BugTracker#9505]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
Hunters mark is currently breaking camo, when you shoudln't be able to use it
**Current behaviour**:
It breaks camo and hunters are abusing it vs each ohter. meaning camo becomes useless VS an other hunter
**Expected behaviour**:
It should say"can't be used right now
**Steps to reproduce the problem**:

1. Make it where it can't be used on a hunter that has camo active. aka condition. 
2.  https://community.atlantiss.eu/index.php?/topic/14994-spellhunter-hunters-mark-removes-camouflage/
3. 

**Revision**:  ACore rev. 5482

**Comment by Psychobird7** [comment]
None of your your links shows any evidence of the ability's proper behaviour...    
NotLikeThis

**Comment by RealSctr** [comment]
how it works on atlantiss:
https://clips.twitch.tv/GeniusDreamyRadicchioDancingBanana 
And this is how it used to work on Arena Tournament 4.3.4 (AFTER PTR meaning no bugs) 
https://youtu.be/udgzKK5KcUs

PS: i've done my research, for the time beeing i used to be a Beta Tester / CO dev on remedy. i'm pritty confident this is how it should be since I've asked people who played retail themself.

**Comment by CrypticWizard** [comment]
> None of your your links shows any evidence of the ability's proper behaviour...

As per the ability's own description:

"causing you and your pet to be untargetable by ranged attacks"

Hunter's Mark is a ranged "attack". True enough, it does no damage but it is targeted, it is a hostile action and it is ranged.

**Comment by RealSctr** [comment]
@CrypticWizard Thank you

**Comment by kadi2** [comment]
I would rather expect red text about "Your vision of the target is obscured" in this case.

**Comment by Jenovas** [comment]
Fix in rev 5538
