### ISSUE TITLE
[EN][SITE] Forum and Google Chrome

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#9507]
There are issues with forum performance whenever you use Google Chrome and full version of the forum. The mini version works perfectly fine on the browser. Tested IE and it worked fine for both.

how to reproduce:
1.Use Google Chrome and do something like this:
![new bitmap image 7](https://user-images.githubusercontent.com/6608500/30080179-f42dcc0e-9282-11e7-9d04-6782dfa647c7.jpg)
2. Try scrolling up and down both versions.
3. Compare it to the normal version and you'll see the diffrence.

**Comment by CrypticWizard** [comment]
> do something like this

Like what? Opening Developer Tools? And what is that supposed to demonstrate. Anyhow, on a mostly shoddy PC ( A6-3650 APU // 4 Gb of memory // no GPU ) the forum actually behaves about as well as I'd expect it to in Google Chrome.

In fact, personally I can't say I've noticed Atlantiss' forum being harsh on Chrome. You should try Twitch. Anyhow, even if there is an issue with the Atlantiss forum in Google Chrome I would suggest you file a bug report with the Chromium project and not with Atlantiss. Atlantiss' forum is quite generic ( https://invisioncommunity.com/ ) and if it behaves poorly in Chrome, quite a few other sites would as well. Hinting at a possible issue in Chrome.

**Comment by kadi2** [comment]
@CrypticWizard Opening developer's tools is just easy way to decrease the width of the site to convert it into mini version. So you can actually compare mini and normal version site performance.

**Comment by CrypticWizard** [comment]
Still leaves the point that if you have issues with the forum while using Google Chrome it's either a problem with Google Chrome itself or with Invision. Neither of which can be resolved by the Atlantiss crew. So, the bug report is most likely Invalid.

Can I ask what OS you're using? It could simply be hardware acceleration is completely disabled in your Google Chrome configuration. Particularly if you're on Linux like I am.

**Comment by kadi2** [comment]
@CrypticWizard I asked few people about the problem and all of them had the same issue with site's performance. The only diffrence i know was that i am using win7 and they are using win10.

**Comment by wtRCH** [comment]
Working fine for me - Windows 10

**Comment by Piklo** [comment]
if the problem persists please create a new report
