### ISSUE TITLE
[EN][Quest][The Shattered Halls] Fel Ember

### ISSUE THREAD

**Issue by arvit** [Atlantiss/BugTracker#9511]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest [Fel Ember](http://www.wowhead.com/quest=29650/fel-ember) gives honor hold reputation ( for some reason wowhead says you should get it from this quest) while you obviously should get Thrallmar reputation.

**Steps to reproduce the problem**:

1. Get the quest
2. Finish the quest
3. Turn it in

**Revision**: 5499
http://www.wowhead.com/quest=29650/fel-ember

**Comment by tomatosz** [comment]
Fix was already on the forums, we just have to wait for it to be implemented:

https://community.atlantiss.eu/index.php?/topic/14430-quest-fel-ember/
