### ISSUE TITLE
All mobs despawn when entering area Rim of the World at Mount Hyjal

### ISSUE THREAD

**Issue by Mystikmohawk** [Atlantiss/BugTracker#9512]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
When i enter rim of the world all mobs disappear.

**Current behaviour**: What happens
when at Shrine of Aviana, heading to do a bird in hand into the Rim of the World  all mobs despawn, when i head back to the shrine, all the mobs re-spawn. also when i try to kill harpys on the ground if i head to west they all despawn and i go back into the rim of the world. i am completely stuck and can not finish quests. 

**Expected behaviour**: What should happen instead
umm..mobs should be there.

**Steps to reproduce the problem**:

1. re entering rim of the world, 
2.  
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
5488 hash. 2eae659befc

**Comment by tomatosz** [comment]
#5530 Phasing issue

**Comment by Aressius** [comment]
To reproduce this issue (on alliance side):
- Start doing questline in Mount Hyjal until you hit a branch: you are given a quest called Aviana's Legacy by Ysera.
- Then simply ignore it and keep doing "main" questline until you hit phase-changing quests for Archdruid Hamuul Runetotem and Tortolla (located south-west from Shrine of Aviana)... At that point, even if you decide to do Aviana's quest chain (which, by the way, you should be able to), you will hit many phasing bugs.
Not 100% certain if these bugs are present before Archdruid Hamuul Runetotem and Tortolla's quests, though, so can't say if they are the cause.

**Comment by tomatosz** [comment]
To be more specific on the reproducing:

- Ignore the [Aviana's Legacy](http://www.wowhead.com/quest=27874/) chain until you get the quest [Aessina's Miracle](http://www.wowhead.com/quest=25372/).
- Go to the Rim of the World to see that it still looks as intended.
- Hand in the quest Aessina's Miracle.
- Fly back to Rim of the World to see that it is now phased and empty.

**Comment by tomatosz** [comment]
Post an indirect fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15074-quest-the-last-living-lorekeeper-hyjal-phasing-issue/

**Comment by Jenovas** [comment]
Fix in rev 5538
