### ISSUE TITLE
[EN][NPC] Warcaller Gorlach

### ISSUE THREAD

**Issue by leinadd** [Atlantiss/BugTracker#9513]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Warcaller Gorlach have a bugged animation.

**Current behaviour**: Instead of walking, Warcaller Gorlach have a falling animation.

**Expected behaviour**: Warcaller Gorlach should walk.

**Steps to reproduce the problem**:

1. This bug happens always, so go find Warcaller Gorlach.
![wowscrnshot_090617_103254](https://user-images.githubusercontent.com/31683485/30199597-0fe3b76a-947c-11e7-9424-58f283cb165b.jpg)

2. 
3. 

**Revision**: 5488

**Comment by tomatosz** [comment]
Blizzlike bug =D https://www.youtube.com/watch?v=miFnb_-hoEY
