### ISSUE TITLE
[EN][Raid][Firelands] Shannox (HC) Spear + Ragnaros Hammer + Engulfing Flames (HC)

### ISSUE THREAD

**Issue by Schneevogel** [Atlantiss/BugTracker#9514]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Current behaviour**: The fire from the spear of Shannox is a bit bugged. The indicators don´t match with the hitbox of this spell. So it can happen, that this spell oneshot you, even you´re not rly standing in it.
And the Ragnaros hammer is invisible during the transition phases, so you only see a fire circle at the hammers´ position.
The Engulfing flames in the hc-mode are also a bit bugged. I don´t know how, but it was able to hit you even if you weren´t at the position to get a hit.

**Expected behaviour**: The fire from the Shannox spear shouldn´t oneshot somebody if he´s not standing in it. And the hammer should be visible ofc. Engulfing Flames should only hit, if you stand in it and not out.

**Steps to reproduce the problem**:

1. Do a Firelands Raid
2. Pull those bosses
3. Enjoy the bugs: Shannox will throw the spear after a few seconds. If you´re not standing exactly between 2 fire rings, you could die. For Ragnaros you have to hit the intermition phase to see the hammer bug. For the Engulfing Flames you have to hit at least Phase 2. It is a bit random, so sometimes it works properly and sometimes not.

**Revision**: 5488

**Comment by Aival94** [comment]
All the abilities with Lines(Magma flow from Rhyolith and hurling spear from Shannox) have increased range from latest updates. 
For the hammer it was before these updates but not sure if the hammer got increased "hitbox" as well.

**Comment by lamaATS** [comment]
Please check once again on main server, should be fixed now.

**Comment by Aival94** [comment]
except ragnaros visual on intermission phases rest seems to be fixed.

**Comment by lamaATS** [comment]
Do you mean visual has too big range? If yes try to test it today (at 8 am was a update).

**Comment by Aival94** [comment]
No. Is not easy to understand but seems every big box ability got fixed. The only visual is the one with the hammer not appearing on intermission phases(only some fires appear on the the spot of the hammer).

Yesterday when i did most bosses for me seems that all the big boxes got fixed.

**Comment by lamaATS** [comment]
So this issue can be closed? Sorry for me too many bugs in a one issue. Hitboxes and invisible spells are a different kind of bug.

**Comment by Aival94** [comment]
I think you can close it as the hitboxes are fixed.

**Comment by Schneevogel** [comment]
Aye, can be closed. Hitboxes are fine right now. I´ll do another thread for the visuals in Firelands (after a raid).
