### ISSUE TITLE
[EN][Ragnaros][Drop] Variable Pulse Lightning Capacitor Heroic

### ISSUE THREAD

**Issue by sayonarawr** [Atlantiss/BugTracker#9517]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: it doesnt fuckign drop on 10 man heroic. ive seen the alys mount drop more than the trinket

**Current behaviour**: it doesnt ever drop

**Expected behaviour**: drop at least more than once in 40 kills

**Steps to reproduce the problem**:

1. kill rag 50 times on 10 man hc
2. kill alys 50 times on 10 man hc
3. see mount drop x5 and capacitor x1

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
5496

**Comment by sayonarawr** [comment]
alys mount winner

**Comment by Psychobird7** [comment]
Impressive.  
/vote for close
