### ISSUE TITLE
[en][spell][rogue] vanish

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9518]
**Description**: Using vanish when offensive spell is  mid air makes you immune/evade to them, when they should hit you in the vanish and take full effect (damage and anything that comes with spell)

**Current behaviour**: spells mid air can be vanished into complete immune (wotlk vanish mechanic)

**Expected behaviour**: rogue should take full damage and spell effects (cataclysm mechanic)

**Steps to reproduce the problem**:

1. cast spell like for example frostbolt at rogue
2. rogue cast vanish when spell is mid air
3. rogue doesnt get damage nor frostbolt slow effect

**Revision**: 5497

http://www.wowhead.com/spell=1856/vanish
https://eu.battle.net/forums/en/wow/topic/2793222809

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/263

**Comment by lamaATS** [comment]
Fixed in rev. 5498
