### ISSUE TITLE
[en][spell][rogue] stealth

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9519]
**Description**: Using stealth when offensive spell is  mid air makes you immune to them, when they should hit you in the stealth and take full effect (damage and anything that comes with spell) and also get you out of stealth

**Current behaviour**: spells mid air can be stealthed into complete immune/evade

**Expected behaviour**: rogue should take full damage and spell effects

**Steps to reproduce the problem**:

1. cast spell like for example frostbolt at rogue
2. rogue cast stealth when spell is mid air
3. rogue doesnt get damage nor frostbolt slow effect

**Revision**: 5497

http://www.wowhead.com/spell=1784/stealth
https://www.youtube.com/watch?v=9Kxig2jp8FE 1:19 (its subterfuge but mechanic is the same beside breaking stealth effect)

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/263

**Comment by fluessig** [comment]
im sure kadi is right it has to do with losing vision of the target, theres a trick with mind vision of priest where u can put it on a rogue and u will see him even if he stealths
if he now comes close to u u can put SWD or DP on him to dmg him and get him out of stealth but on atlantiss the spell just fizzles
all combatlog says i casted the spell but it never landed

**Comment by lamaATS** [comment]
Fixed in rev. 5498
