### ISSUE TITLE
[EN][Quest][Isle of Quel'Danas] Crisis At The Sunwell

### ISSUE THREAD

**Issue by Sainsyl** [Atlantiss/BugTracker#9520]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest should be turned in to Exarch Larethor, but he is missing (he is not in the instance either)

**Current behaviour**: Exarch Larethor missing, can't turn in quest.

**Expected behaviour**: Exarch Larethor should be there, so you can turn in the quest,take the next one.

**Steps to reproduce the problem**:

1. Take the quest from Adyen the Lightwarden
2. Go to Isle of Quel"Danas
3. Look for Exarch Larethor who is nowhere to be seen

**Revision**: 5497

<a href="http://tinypic.com?ref=jhda87" target="_blank"><img src="http://i64.tinypic.com/jhda87.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
http://www.wowhead.com/quest=11481/crisis-at-the-sunwell
http://www.wowhead.com/npc=24813/exarch-larethor

**Comment by tomatosz** [comment]
As of 4.2 these quests are no longer required for Magister's Terrace hc, so it is accessible.
The quests should still be there though.

**Comment by Sainsyl** [comment]
tomatosz, I don't know how I missed/didn't notice since I've probably done it without the quest :D anyway, edited.

**Comment by TranceAccount** [comment]
He should not be in this house anymore, but only in the dungeon. #572
