### ISSUE TITLE
Alysrazor HC siphoning

### ISSUE THREAD

**Issue by narilrave** [Atlantiss/BugTracker#9523]
**Description:**

29308 - [Heart of Flame](http://www.wowhead.com/quest=29308/heart-of-flame) (Horde). 
29307 - [Heart of Flame](http://www.wowhead.com/quest=29307/heart-of-flame) (Alliance). 
Part 1 - Smouldering essences Collected x 250. 
Upon boss death corpse gets the aura 101093 - [Smouldering](http://www.wowhead.com/spell=101093/smouldering). 
Use the item 71085 - [Runestaff of Nordrassil](https://www.wowhead.com/item=71085) to cast the spell 101140 - [Siphon Essence](https://www.wowhead.com/spell=101140) in order to siphon the essence from a corpse of a firelands boss with the aura 101093 - [Smouldering](https://www.wowhead.com/spell=101093) . 

Works on all bosses but not Alysrazor in heroic mode (it does work in normal).

**Current behaviour:**

Currently using the 71085 - [Runestaff of Nordrassil](https://www.wowhead.com/item=71085) to cast the spell 101140 - [Siphon Essence](https://www.wowhead.com/spell=101140) in order to siphon the essence wont work and the following message in red will appear in the middle of the screen "You can't do that yet" http://prntscr.com/glax4z.

**Expected behaviour:**

After using [Runestaff of Nordrassil](https://www.wowhead.com/item=71085) to cast the spell 101140 [Siphon Essence](https://www.wowhead.com/spell=101140) the aura 101093- [Smouldering](https://www.wowhead.com/spell=101093) will be removed from the corpse and a few essences should collected and a short animation .

**Steps to reproduce the problem:**

1. Enter FireLands 10HC or 25HC (NOT NORMAL). 
2. Kill Alysrazor . 
3. Target Alysrazor corpse and attempt to use 71085 - [Runestaff of Nordrassil](https://www.wowhead.com/item=71085) to cast the spell 101140 - [Siphon Essence](https://www.wowhead.com/spell=101140). 

**Revision:** ACore rev. 5498 hash. 4f7281da05c9 2017-09-12 02:00:42 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
#8472 duplicate
