### ISSUE TITLE
[EN][Quest][Mount Hyjal] The Last Living Lorekeeper (25830) (related to phasing issue)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9524]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The quest [The Last Living Lorekeeper (25830)](http://www.wowhead.com/quest=25830/the-last-living-lorekeeper) is available without doing all prerequisites. This makes it possible to get phasing issues later on (after [Aessina's Miracle](http://www.wowhead.com/quest=25372/aessinas-miracle)).

**Current behaviour**: You can do The Last Living Lorekeeper without having finished [An Ancient Reborn (25807)](http://www.wowhead.com/quest=25807/an-ancient-reborn). I don't know whether the other prerequisites work properly here.

**Expected behaviour**: You should only be able to do this quest after finishing An Ancient Reborn and [An Ancient Awakens (25520)](http://www.wowhead.com/quest=25520/an-ancient-awakens). Some [comments](http://www.wowhead.com/quest=25830/the-last-living-lorekeeper#comments:id=1241656) on wowhead also mention [Return From the Firelands (25611)](http://www.wowhead.com/quest=25611/return-from-the-firelands)([Horde (25612)](http://www.wowhead.com/quest=25612/return-from-the-firelands)), [Durable Seeds (25491)](http://www.wowhead.com/quest=25491/durable-seeds) and [Prepping the Soil (25502)](http://www.wowhead.com/quest=25502/prepping-the-soil) as a prerequisite but I haven't been able to confirm that.

**Steps to reproduce the problem**:

1. Start questing in Mount Hyjal
2. When you get the quest [Aviana's Legacy (27874)](http://www.wowhead.com/quest=27874/avianas-legacy), ignore it and follow the other quest chain.
3. Complete the chain until An Ancient Awakens.
4. A Vision of Ysera will appear that offers The Last Living Lorekeeper.

**Revision**: rev. 5498

**Comment by tomatosz** [comment]
Post a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15074-quest-the-last-living-lorekeeper-hyjal-phasing-issue/

**Comment by Jenovas** [comment]
Fix in rev 5538
