### ISSUE TITLE
[EN][Achievement][Northrend] Northrend Explorer

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9532]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: this achievement give you a [tabard](http://www.wowhead.com/item=43348/tabard-of-the-explorer#reward-from-a) as reward.

**Current behaviour**: I did [the achievement](http://www.wowhead.com/achievement=45/northrend-explorer#guides) and the tabard was not given

**Expected behaviour**: after completing the achievement this tabard have to be sended to you in a mail

**Steps to reproduce the problem**: 
explore all the zones listed [here](http://www.wowhead.com/achievement=45/northrend-explorer#guides).

**Revision**: Current server version 5508

**Comment by aendry** [comment]
It looks like the email was missed because of a roll back or something like that. where can I put a ticket to get the item?

**Comment by Thunderlmao** [comment]
:(

**Comment by wtRCH** [comment]
@aendry do you still miss the tabard? Please contact any GM via ticket ingame.
