### ISSUE TITLE
[EN][Quest][Howling Fjord] Stop the Ascension!

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9534]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: this quest is given by a [dropable item](http://www.wowhead.com/item=33339/vrykul-scroll-of-ascension) that you obtain kiiling [this mobs](http://www.wowhead.com/item=33345/vrykul-scroll-of-ascension#dropped-by)

**Current behaviour**: the item never drops

**Expected behaviour**: item to be droped

**Steps to reproduce the problem**:

1. go to Howling Fjord
2. kill like 1000 mobs or so and when you borred create a ticket xD 

**Revision**: Current server version 5508

**Comment by tomatosz** [comment]
Have you completed Skorn Must Fall! (horde) or Operation: Skornful Wrath (alliance)?

**Comment by tomatosz** [comment]
Posted a fix on the forums:
https://community.atlantiss.eu/index.php?/topic/15118-quest-stop-the-ascension/

**Comment by aendry** [comment]
I'll check tomorrow

**Comment by aendry** [comment]
@tomatosz nope. it looks like didn't .... let me travel there to see if that quest is available or no.

**Comment by aendry** [comment]
didn't see your edit lol

**Comment by Jenovas** [comment]
Fix in 5537
