### ISSUE TITLE
(EN)(Achievement)(Drunken Stepor)

### ISSUE THREAD

**Issue by poleloa** [Atlantiss/BugTracker#9549]
That achievement does not work i tried yesterday 10 times .Two from ten time i was dying.
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED)
please help i'm new on bugtracker in game i'm as farana 

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: . It's bugg.

**Current behaviour**: I tried it 10 times ,unfortuneably 2 time from ten i died.

**Expected behaviour**: I should fell from 65 yards ,saved 20% of my health(26012 from 130063)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Sayris9876** [comment]
Achievement works fine you just dont know how high is 65 yards. 2 years ago i did it myself last year i did it for friend yesterday a friend did it infront of me.

**Comment by xolon** [comment]
Just go to random orgrimmar, wait till it's at the bottom and jump, you'll get the achi

**Comment by poleloa** [comment]
elevator? can u link map with that please?

**Comment by xolon** [comment]
http://media-azeroth.cursecdn.com/attachments/44/153/635150484134078943.png
