### ISSUE TITLE
[EN][Quest][Azuremyst Isle]A Hearty Thanks!(ID 9612)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#955]
Quest should only be available for Draenei characters. Now it is also available for other Alliance races like Worgen.

Wowhead link: http://www.wowhead.com/quest=9612
Gamepidia link: http://wow.gamepedia.com/Quest:A_Hearty_Thanks!
Openwow link: http://cata.openwow.com/quest=9612

![wowscrnshot_122414_004008](https://cloud.githubusercontent.com/assets/10282971/5548845/69bf991a-8b84-11e4-95e8-e75638c0f942.jpg)

**Comment by Bildo** [comment]
rev. 4353 by Quban
