### ISSUE TITLE
 [Learn to Ride in Elwynn Forest]

### ISSUE THREAD

**Issue by Uilesbr** [Atlantiss/BugTracker#9551]
[Learn to Ride in Elwynn Forest]   não e possivel entregar essa quest arrumen por favor, nos aqui do brasil vamos ajudar voces com doaçoes. para manter o servidor

**Comment by tomatosz** [comment]
Please post in English or Polish and use the template.

Also, fix is on the forums, this quest shouldnt exist anymore in 4.3.
