### ISSUE TITLE
[EN][NPC][Missing] Exarch Larethor

### ISSUE THREAD

**Issue by Thunderlmao** [Atlantiss/BugTracker#9552]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # http://www.wowhead.com/npc=24813/exarch-larethor#comments

[//]: # ([EN][NPC] [Missing] Exarch Larethor)

**Description**: There are two quests that require you to speak to Exarch Larethor, which are either 'Crisis at the Sunwell' or 'Duty Calls'. Exarch Larethor is meant to be  located in the Isle of Quel'Danas at 47.4, 30,7 (next to the quartermaster).

**Current behaviour**: He is not at the location he should be at.

**Expected behaviour**: He should be at the location in order for players to turn in their quests.

**Steps to reproduce the problem**:

1. Go to the Isle of Quel'Danas at 47.4, 30,7 (next to the quartermaster).
2. Look for Exarch Larethor, or type /tar Exarch Larethor.
3. Realise he is missing.

**Revision**: Current server version: 4.3.4

**Comment by Thunderlmao** [comment]
Edit: Submitted an ticket in game  and the GM Myivvo spawned the NPC in the appropriate location for me.

**Comment by TranceAccount** [comment]
He has been moved inside the instance. #572
