### ISSUE TITLE
[EN][Npc][Item] All Vendors Selling Incorrect stacks of Water

### ISSUE THREAD

**Issue by Taiguh** [Atlantiss/BugTracker#9560]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
ALL Innkeepers and Barkeeps that sell Water/Drinks are selling all types that are level 65 and under for single stacks instead of the normal(blizzlike) 5 stacks
**Current behaviour**: What happens
Go to a drink vendor and they will sell you water/drink in single stacks and happens for all water/drinks at level 65 and under
**Expected behaviour**: What should happen instead
Vendors should sell the water/drinks 65 and under at 5 stacks instead of the servers 1 stack
**Steps to reproduce the problem**:

1. went to Menethil Harbor which sold water in singles
2. went to Dalaran which sold water in singles
3. went to Stormwind Dwarven side, and confirmed its only low level water(65 and under) selling for singles, cata items are normal
4. cleared cache to confirm its server side

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
4.3.4 hash 5510

**Image**
![bugtracker item stacks](https://user-images.githubusercontent.com/32307883/30875065-d642e27a-a2b7-11e7-9112-ca2d0753c868.png)

**Comment by Piklo** [comment]
wowhead links
https://github.com/Atlantiss/BugTracker#how-to-use

**Comment by Taiguh** [comment]
there is no reason for wowhead links as every single expac since vanilla has had vendors selling water at 5 stacks.

**Comment by tomatosz** [comment]
he doesn't mean wowhead links to the bug, but to things relevant to the bug/fix, in this case the items that are sold in the wrong stacks (e.g. [Melon Juice](http://www.wowhead.com/item=1205/melon-juice) )

This makes it easier to confirm that it's a bug, as well as give data that is needed to fix the bug.

**Comment by Taiguh** [comment]
ah ok i see, my apologies my first time reporting any kind of bugs, thanks for the tips

**Comment by tomatosz** [comment]
no problem, and thanks for posting it, too many people don't bother.

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15155-sold-stacks-of-mana-drinks/

**Comment by Jenovas** [comment]
Fix in 5537
