### ISSUE TITLE
Icecrown Citadel 10HC @PP

### ISSUE THREAD

**Issue by Sherbeti** [Atlantiss/BugTracker#9561]
Recently went into icc10hc with my friends till pp everything was works fine but at pp i noticed some problems that needs to be fixed.

1.Abomination when u drink at the table after some seconds u become abomination then u gain 3 abilities .
A.1st ability its a spell that if u click that on a green puddle gain some energy which u need this for later on . B.2nd its a Spell that causes Green Oze/Orange Oze to be slowed for quite amount of time but this spell requires 45energy which on my attempt i wasnt gaining any energy by drinking puddles cause that only resource of gaining energy . C.3rd its a Swipe which ur Abomanation deal moderate dmg that doesnt require energy.
Also forgot to mention when pulled the boss after getting on abom and trying to go to puddle and drink Abomination disappared and i have to drink again then after that abomination stood alive but energy system didnt worked at all .

**Comment by Piklo** [comment]
follow our [issue_template ](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md) and read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use)
