### ISSUE TITLE
[EN][Valiant's Charge][Icecrown]

### ISSUE THREAD

**Issue by Pipish** [Atlantiss/BugTracker#9565]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After becoming a champion for a race in argent tournament cant take valiant charge quest for other races

**Current behaviour**: Quest givers doesn't have the quest 

**Expected behaviour**: After completing The Valiant's Charge and turning in A Champion Rises i should be able to get The Valiant's Charge from another race's quest giver. (For example after completing The Valiant's Charge for orcs i should be able to get the Tauren one)

**Steps to reproduce the problem**:

1. Turn in the The Valiant's Charge
2. Take and turn in A Champion Rises
3. Return to quest giver (Mokra the Skullcrusher/Zul'tore/Runok Wildmane/Deathstalker Visceri/Eressea Dawnsinger)
**Revision**: 5510

**Comment by Piklo** [comment]
should be fixed in [rev5794](https://atlantiss.eu/changelog#rev5794)
