### ISSUE TITLE
Quest stuck. unable to proceed.

### ISSUE THREAD

**Issue by niktr** [Atlantiss/BugTracker#9571]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
http://www.wowhead.com/quest=26077 Final Delivery
**Current behaviour**: What happens
objective: use the blimp.
The blimp is in the lake. Not on top of it, not on the platform where it's supposed to be. it's inside the lake. Im unable to proceed with this questline.
**Expected behaviour**: What should happen instead
Blimp spawns on platform. I click the blimp. Blimp takes me places.
**Steps to reproduce the problem**:

1. Start the quest Final Delivery in Stonetalon Mountains
2. Proceed to the objective

**Revision**: 5510 hash. a75aa2ec9bf2

**Comment by tomatosz** [comment]
Change the title according to template, so it's clear what it's about

**Comment by Piklo** [comment]
please change title or your post will be closed :)
https://github.com/Atlantiss/BugTracker#how-to-use

**Comment by Sayris9876** [comment]
Relog. When you do that the "blimp" as you call it have falling animation from platform and you can click on it if you are fast enough
