### ISSUE TITLE
[ENG][Guild] Guild Charter doesn't open

### ISSUE THREAD

**Issue by NixShraik** [Atlantiss/BugTracker#9574]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Guild Charter doesn't open, when right clicked.

**Current behaviour**: I have tried login in and out, destroying the old one and buying a new one and such, but nothing happens.

**Expected behaviour**: Guild Charter should open.

**Steps to reproduce the problem**:

1. Right-click on the Guild Charter
2. Nothing happens

**Revision**: 4.3.4 branch

**Comment by Piklo** [comment]
https://us.battle.net/forums/en/wow/topic/8197591486#post-5
