### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by Uilesbr** [Atlantiss/BugTracker#9578]
it is not possible to deliver this quest  [Zen'Kiki and the Cultists]

**Comment by tomatosz** [comment]
Please use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md).

**Comment by Piklo** [comment]
read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use) and use our [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
