### ISSUE TITLE
[EN][Quest:25258][Durotar]Griswold Hanniston

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/BugTracker#9581]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: You can't duel Griswold Hanniston

**Current behaviour**: When you talk to Griswold to start the fight, he refuses to duel - https://youtu.be/-XSyjYGKoIc

**Expected behaviour**: After short talk with Griswold he should start the encounter.

**Steps to reproduce the problem**: 

1. Pick up quest from Spiketooth
2. Talk to Griswold Hanniston
3. Request him to duel with you

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15298-9629958169265605-griswold-hanniston-smart_scripts/

**Comment by Jenovas** [comment]
Fix in 5537
