### ISSUE TITLE
[PL][Item]Demonfang Ritual Helm

### ISSUE THREAD

**Issue by wojen616** [Atlantiss/BugTracker#9582]
W loot table hc The Black Stalker (http://www.wowhead.com/npc=17882/the-black-stalker) brakuje Demonfang Ritual Helm (http://www.wowhead.com/item=27781/demonfang-ritual-helm)

**Revision**: 5510

**Comment by wojen616** [comment]
@Piklo

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15231-9582-the-black-stalker-loot_template/

**Comment by Jenovas** [comment]
Fix in 5537
