### ISSUE TITLE
[EN] [DK] [PET] Gnaw

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9583]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Gnaw (without dark Transformation) should be a 3 second stun
https://imgur.com/4xUqoQ9

**Current behaviour**: Played some arean yday and it was only a 1 second stun in most of the games, also have the recordings if needed. (was against rogue (rogue dosent have any stun reduction talents, nor is he orc or has the mate gem to reduce stun duration)

**Expected behaviour**: should be a 3 second stun.

**Steps to reproduce the problem**:

1. Use gnaw
2.  Look at duration of gnaw

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by blinkmaster** [comment]
This happens with Deep freeze Too. No idea what makes it happen tho

**Comment by lamaATS** [comment]
Fixed in rev. 5536
I know that changes may looks like it's not related but trust me it is.
