### ISSUE TITLE
[EN][Talent][DK] Missing talent points (5).

### ISSUE THREAD

**Issue by Kaiyuni** [Atlantiss/BugTracker#9584]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I'm missing 5 of my talent points from the DK starting zone despite having done all the quests.

**Current behaviour**: I don't have the last 5 talent points you're supposed to receive.

**Expected behaviour**: I should have all my talent points.

**Steps to reproduce the problem**:

1. Do the DK starting zone.
2. Get to the last batch of quests (Lich King frostwyrm, etc.)
3. Don't get talent points for those quests.

**Revision**: 5510 hash

**Comment by Buggingtrack** [comment]
DKs like other classes have the right amount of talent points at the **same levels** that any other character earns while leveling.
The quests are probably still designed as WotLK where there used to be alot more talent points in total, so it's just a visual bug. In cataclysm when you leave the starting zones you will have the same talents points as other classes of your same level.
