### ISSUE TITLE
[EN][Quest] Cultivating an Image

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9586]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The [item (37125)](http://www.wowhead.com/item=37125/rokars-camera) for this [quest (12202)](http://www.wowhead.com/quest=12202/cultivating-an-image) should work on all iron dwarves in the area.

**Current behaviour**: The item only works on [Iron Rune-Smith](http://www.wowhead.com/npc=26408/iron-rune-smith). Using it on another dwarf gives the message "Invalid target".

**Expected behaviour**: It should also work on [Runic Lightning Gunner (26414)](http://www.wowhead.com/npc=26414/runic-lightning-gunner), [Iron Rune Overseer (27177)](http://www.wowhead.com/npc=27177/iron-rune-overseer), [Rune-Smith Kathorn (26410)](http://www.wowhead.com/npc=26410/rune-smith-kathorn) and [Rune-Smith Durar (26409)](http://www.wowhead.com/npc=26409/rune-smith-durar).

**Steps to reproduce the problem**:

1. Get the quest Cultivating an Image
2. Kill a Runic Lightning Gunner, Iron Rune Overseer, or one of the named Rune-Smiths.
3. Try to use the item on the dead dwarf

**Revision**: rev. 5530

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15538-quest-cultivating-an-image/

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
