### ISSUE TITLE
[EN][Paladin] Retribution: Guardian of Ancient Kings/Ancient Power

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9587]
**Description**: Ancient Power (AP) stacks get cancelled when recasting Guardian of Ancient Kings (GAK) 
Ret GAK spell ID: 86150 
Ancient Power spell ID: 86700 

**Current behaviour**: See description. 

**Expected behaviour**: Recasting GAK should not cancel AP stacks, it should merely extend their duration, allowing you to keep them until GAK completely expires. 

**Steps to reproduce the problem**:

1. Go into End Time and engage Murozond (only boss that currently allows this scenario to happen
2. cast GAK, stack it up 
3. Hit the Hourglass
4. See your AP stacks drop 

**Revision**: 5530

**Comment by Piklo** [comment]
proofs

**Comment by Psychobird7** [comment]
Coming up, don't worry.

**Comment by Psychobird7** [comment]
Unable to find a video showing being done. 
Closing report.
