### ISSUE TITLE
[EN][NPC] Alizabal

### ISSUE THREAD

**Issue by Aydien** [Atlantiss/BugTracker#9591]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Players are able to CC boss.

**Current behaviour**: Boss can be stunned, feared, etc.

**Expected behaviour**: Immune

**Steps to reproduce the problem**:

1.  Target boss
2. Cast Cyclone or any other crowd controll spell
3. See boss flying in cyclone

**Revision**: 5531

**Comment by Piklo** [comment]
already sent fix to pelekon

**Comment by pelekon** [comment]
fixed in rev 5561
