### ISSUE TITLE
[EN][Quest] In Unending Numbers not obtainable

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#9592]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: I have checked you guys have been fixing the chain quests for the newly opened hour of twilight dungeons, just saw you added ["The Hour of Twilight"](http://www.wowhead.com/quest=30102/the-hour-of-twilight) that was missing; it is still missing though the last quest for the 2nd dungeon of the three [Well of Eternity](http://www.wowhead.com/well-of-eternity), and would love to have this last quest added for the particular rewards, so i will just be reporting this if you aren't yet aware of this last missing thing

**Current behaviour**: After turning in ["The Well of Eternity"](http://www.wowhead.com/quest=30098/the-well-of-eternity) you dont get from [this Nozdormu](http://www.wowhead.com/npc=55624/nozdormu) the next quest for the chain to obtain one of the four epic 378 items in its rewards ["In Unending Numbers"](http://www.wowhead.com/quest=30099/in-unending-numbers) till reaching ["The Path to the Dragon Soul"](http://www.wowhead.com/quest=30101/the-path-to-the-dragon-soul)

**Expected behaviour**: You should be able to get ["In Unending Numbers"](http://www.wowhead.com/quest=30099/in-unending-numbers) and all the relative quests to complete the last chain you are missing in your newly opened hour of twilight dungeons

**Steps to reproduce the problem**:

1. Obtain ["The Well of Eternity"](http://www.wowhead.com/quest=30098/the-well-of-eternity) from the quest chain in the previous dungeon End Time
2. Turn this quest to the related NPC
3. See how the same NPC whom you turned in the quest doesn't give the next one 

**Revision**: 5531

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15229-quests-in-well-of-eternity/

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5854.
