### ISSUE TITLE
Cross faction heriloom not allowed

### ISSUE THREAD

**Issue by bbiagio** [Atlantiss/BugTracker#9595]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

When you try to send heirloom items via mailbox to your opposite faction characters, it says "unfriendly target" and the process stops.

**Comment by Sayris9876** [comment]
You sure you sent only and only looms? If you put anything else in the mail (mats/any kind of other items/gold etc) you cannot send the looms since only and only looms are allowed to be sent between factions via mail. Also fix your report you didnt follow the template.

**Comment by Aydien** [comment]
Xfactionnlooms sending works flawless, tested yesterday

**Comment by tomatosz** [comment]
If the solution from Sayris9876 doesn't work, could you specify which heirloom caused the issue? Maybe it's a problem with a specific one, not all heirlooms.
