### ISSUE TITLE
[PL][PALADIN][HAND OF FREEDOM]

### ISSUE THREAD

**Issue by calladin** [Atlantiss/BugTracker#9597]
Jak działa obecnie: Nie można użyć freedom'a na target, który znajduje się pod wpływem efektu typu "silence"
Jak powinno działać: Oczywiście freedom'a powinno się dać użyć na target, który znajduje się pod wpływem efektu "silence".

Rev. 5531

**Comment by Aydien** [comment]
kieyś już chyba bylo zgłaszane ale zniknęło to samo sie tyczy Hand of Protection

**Comment by Aydien** [comment]
https://github.com/Atlantiss/BugTracker/issues/3313

**Comment by pelekon** [comment]
fixed
