### ISSUE TITLE
[PL][Raid] Eye of Eternity

### ISSUE THREAD

**Issue by Bastion** [Atlantiss/BugTracker#960]
http://www.wowhead.com/zone=4500/the-eye-of-eternity
key bag usunięty a nadal trzeba mieć klucz żeby odpalić orba
http://www.wowhead.com/object=193958/the-focusing-iris
http://www.wowhead.com/object=193960/the-focusing-iris
http://www.wowwiki.com/Focusing_Iris

faza na smokach kompletnie nie działa, nabija id po zabiciu sciona w 2 fazie, po wipe nie ma bossa

Patch 4.2.0 (28-Jun-2011): No longer requires Key to the Focusing Iris (reward) or Heroic Key to the Focusing Iris (reward) to activate.

**Comment by Bastion** [comment]
fix pls (:

**Comment by eryczek1615** [comment]
bump

**Comment by Bastion** [comment]
asdf

**Comment by phantomgodx** [comment]
Hey 1 question,does it always disappear or only sometimes? :)

**Comment by Malylolek** [comment]
#8000 - beeter topic
