### ISSUE TITLE
[EN] [Death knight] rune regeneration speed

### ISSUE THREAD

**Issue by Sathus** [Atlantiss/BugTracker#9600]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:  Rune speed is not affected by anything, making rune regeneration extemely slow.

**Current behaviour**: Rune speed is stuck at a very slow rate, and is not affected by haste.

**Expected behaviour**:  Rune speed should vary depending on your haste rating.

**Steps to reproduce the problem**:

1. Log your Death knight, check rune speed.
2. Swap between tank gear and dps gear, notice rune regen does not change.
3. Cry.

**Revision**:5533

**Comment by Katonetwo** [comment]
note that it is currently stuck at 13.30s, which is lower than base (10s)
![wowscrnshot_101417_133737](https://user-images.githubusercontent.com/32794643/31575589-acb8366c-b0ea-11e7-86a9-e18ea0bf99ad.jpg)

**Comment by c0ldw1nter** [comment]
same, stuck at 12.18 seconds. presence makes no difference as well

**Comment by Katonetwo** [comment]
UPDATE: rune speed appears to scale the wrong way with haste
example: energy regen is 10/s base
if you get 10% haste, it makes it be 11/s instead

now rune speed is being treated the same way, except it does not update
so base rune speed is 10s
*1.2 from improved blood presence ( + 20% rune regeneration, example)
and another factor based on haste, *1.1087 in this case
giving us 10*1.2*1.1087=13.30, our exact rune speed
![wowscrnshot_101417_182044](https://user-images.githubusercontent.com/32794643/31577360-2f060816-b10d-11e7-9fae-8566f07463cd.jpg)

OR
*1.1860 in this case
giving us 10*1.2*1.1860=14.23, rune speed again
![wowscrnshot_101417_182050](https://user-images.githubusercontent.com/32794643/31577372-6184a07c-b10d-11e7-835e-dbd86cf1ce18.jpg)

**Comment by kircaaaaa** [comment]
Can confirm

**Comment by TranceAccount** [comment]
Check changelog

**Comment by lamaATS** [comment]
Fixed in rev. 5534 (you can test it already on PTR)

**Comment by kircaaaaa** [comment]
Wait so when is the fix going live ?
