### ISSUE TITLE
[EN] Fury warrior raging blow

### ISSUE THREAD

**Issue by brokenshard** [Atlantiss/BugTracker#9601]
Description: Raging blow should do more damage

Current behaviour: Raging blow does only 100% of the weapon's damage (not counting fury mastery or other talents that increases its damage)

Expected behaviour: It should do 120% of the weapon's damage according to 4.0.6 patch notes
http://eu.battle.net/wow/en/game/patch-notes/4-0-6

Steps to reproduce the problem:

1. Unlearn your talents
3. Mouseover on raginblow 
3. You'll see that it says it does 100% of the weapon's damage

http://eu.battle.net/wow/en/game/patch-notes/4-0-6

Revision: 5534

**Comment by Psychobird7** [comment]
4.0.6 is hardly relevant anymore, it has been nerfed since. 

Simcraft, Spellworks and Rawr all model RB dealing 100% weapon damage.    

http://www.wowhead.com/spell=85288/raging-blow#changelog 
Hover over any of the 4.1 and 4.2 versions to see the tooltips.

**Comment by Psychobird7** [comment]
And here are the relevant patch notes. 
https://worldofwarcraft.com/en-us/news/2259389     
Ctrl+F "Raging". 
"Warriors
Raging Blow has been reduced from 120% to 100% weapon damage at max level. More information can be found here." 
"here": https://us.battle.net/forums/en/wow/topic/2065568025?page=1#0
