### ISSUE TITLE
[En][wow_434.exe][Critical Error]

### ISSUE THREAD

**Issue by CrazyRampage** [Atlantiss/BugTracker#9604]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Extracted the mini game client, critical error occurs
**Current behaviour**: What happens
Game does not launch there is an error 
**Expected behaviour**: What should happen instead
Game should launch
**Steps to reproduce the problem**:

1. No idea. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
[2017-10-15 20.54.44 Error.txt](https://github.com/Atlantiss/BugTracker/files/1385962/2017-10-15.20.54.44.Error.txt)

**Comment by tomatosz** [comment]
Make a post on the forums so people can help you out there:
https://community.atlantiss.eu/index.php?/forum/9-support-amp-qa/

This is not an actual bug in the game so it does not belong on the bugtracker.

**Comment by xmesaj2** [comment]
https://community.atlantiss.eu/index.php?/topic/3984-problems-with-launching-your-wow-solutions-to-wow-errors-132-134-disconnecting/&do=findComment&comment=82242
