### ISSUE TITLE
Shadowfury can't stun the target

### ISSUE THREAD

**Issue by kabashx** [Atlantiss/BugTracker#9607]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
If u duel the same person several times, the guy u were dueling can bug out and can't be stun by warlocks  [Shadowfury]
**Current behaviour**: What happens
Char u are dueling wont get stuned by  [Shadowfury]
**Expected behaviour**: What should happen instead
He should be stuned
**Steps to reproduce the problem**:

1. Duel the same person several times
2. It can bug out
3.  [Shadowfury] wont stun him

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Isn't it just https://wow.gamepedia.com/Diminishing_returns ?

**Comment by Psychobird7** [comment]
It seems unlikely that DR would persist throughout several duels.

**Comment by kabashx** [comment]
@xmesaj2 mate, i didnt duel him 1 sec after duel ended. it was like 1-2min later, so its not DR :)
When the mate whom I dueled loged out, and I did that as well the problem was solved. But it happend as well when I fought as warr vs Onlycarrots, after few duels lock cound't stun me with Shadowfury. This happen on ally side and my lock is on horde so its a general bug.

**Comment by kabashx** [comment]
it happens in arena as well. after 3-4 arenas the holy pala become imune to stun. Like first Shadowfury didnt hit, so its definitely not DR

**Comment by kabashx** [comment]
hello??

**Comment by calladin** [comment]
Are you 100% sure that he didn't pre used some alchemy potions? (for example free action potion) http://www.wowhead.com/item=5634/free-action-potion

**Comment by fluessig** [comment]
yeah he used pots in arena
i do this all the time

**Comment by kabashx** [comment]
No Calladin, i dont use pots at all, not even duel, Im not Quodan ffs :)

**Comment by fluessig** [comment]
he meant the enemy drinking pots

**Comment by kabashx** [comment]
hello?

**Comment by kabashx** [comment]
hello?

**Comment by kabashx** [comment]
here is the proof, Kaspi and I made a vid
https://www.youtube.com/watch?v=sNPZoN-STq0&feature=youtu.be

**Comment by lamaATS** [comment]
Fixed in rev. 5536
Thanks for video it was really helpful.
