### ISSUE TITLE
[EN][Item][Companion] Creepy Crate

### ISSUE THREAD

**Issue by Samineh** [Atlantiss/BugTracker#9612]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [It](http://www.wowhead.com/item=71076) does not eat critters >.>.

**Current behaviour**: Creepy crate should eat critters when he is summoned according to [wowhead](http://www.wowhead.com/item=71076/creepy-crate#comments).

**Expected behaviour**: it does not do anything :(.

**Steps to reproduce the problem**:

1. Get Creepy Crate.
2. Summon it and go near critters.
3. Cry.

**Revision**: 5534

**Comment by 1Andas** [comment]
Bump.

**Comment by wtRCH** [comment]
Now eat critters but won't play emote after eating them.
