### ISSUE TITLE
[EN][Npc][Item] Recipe: Highland Spirits

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9616]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [The item](http://www.wowhead.com/item=65415/recipe-highland-spirits#teaches-recipe) is necessary to complete the achievement Drown Your Sorrows. It is meant to be sold by [Fyldan ](http://www.wowhead.com/npc=4223/fyldan), [Emrul Riknussun](http://www.wowhead.com/npc=5160/emrul-riknussun) and [Bario Matalli](http://www.wowhead.com/npc=49701/bario-matalli).

**Current behaviour**: any of this NPCs sells the Item in question.

**Expected behaviour**: that the 3 NPCs have the item for sale

**Revision**: Current server version 5534

NOTE: same happens with [this one](http://www.wowhead.com/item=65433/recipe-south-island-iced-tea)

**Comment by Navedonar** [comment]
Fix https://community.atlantiss.eu/index.php?/topic/18263-ennpcitem-recipe-highland-spirits/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)
