### ISSUE TITLE
[EN][Npc][Item] South Island Iced Tea

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9617]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [this NPC](http://www.wowhead.com/npc=2832/nixxrax-fillamug) is the only one in the game that can sells you [the item](http://www.wowhead.com/item=62672/south-island-iced-tea#sold-by) but he  doesn't have it

**Current behaviour**: the Item is not on sale

**Expected behaviour**: the Item needs to be on sale for this NPC

**Revision**: Current server version 5534

**Comment by Navedonar** [comment]
Fix https://community.atlantiss.eu/index.php?/topic/18264-npcitem-south-island-iced-tea/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)
