### ISSUE TITLE
[EN][Glyph][Death Knight] Pillar of Frost glyph not working as intended

### ISSUE THREAD

**Issue by Chiasm** [Atlantiss/BugTracker#9622]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Glyph of Pillar of Frost does not work as intended

**Current behaviour**: Casting Glyphed Pillar of Frost does freeze you into place, but it does not make you immune to any kind of crowd control, especially "all" as stated

**Expected behaviour**: Glyphed Pillar of Frost should grant immunity to any kind of incoming CC, polymorph, blind, disarm, stun, fear, silence, slow, etc.

**Steps to reproduce the problem**: 

1. Glyph Pillar of Frost on a Death Knight
2. Have someone CC you in a duel after PoF has been cast
3. Get CCd anyway

**Revision**: 5534

**Comment by Katonetwo** [comment]
unfortunate

**Comment by Dethawk** [comment]
https://github.com/Atlantiss/BugTracker/issues/10002 they rly dont care
