### ISSUE TITLE
[EN][Spell][Warlock][Shaman][Death Knight] Guardians dying in Ragnaros p3.

### ISSUE THREAD

**Issue by Pocketerino** [Atlantiss/BugTracker#9627]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When the classes listed in the name use their Guardians(Doomguard/Infernal, Elementals, Gargoyle) in the Ragnaros NM/HC encounter,the summoned guardians have a high chance of dying, especially in p3 where they're usually used for the extra DPS push.

**Current behaviour**: Its happening because they have no Avoidance to the following NPC AoE abilities

http://www.wowhead.com/spell=99171
http://www.wowhead.com/spell=100171
http://www.wowhead.com/spell=100460
http://www.wowhead.com/spell=98710, also to the Flame Patch it leaves behind, couldn't find a link to that, sorry fams.
http://www.wowhead.com/spell=98928

**Expected behaviour**: The guardians should have 90% damage reduction to all of those spells.

**Steps to reproduce the problem**:

1. Start the Ragnaros NM/HC encounter.
2. Summon any of the guardians I named in any phase, ideally p3.
3. Watch them die to EF, WiF, SS, LW or BH.

**Revision**: 5535

**Comment by Pocketerino** [comment]
Heres a fine example of a good ol' bumperoo.

**Comment by pelekon** [comment]
fixed in rev 5731
