### ISSUE TITLE
Griswold Hanniston bugged

### ISSUE THREAD

**Issue by finalhonor** [Atlantiss/BugTracker#9629]
as stated Griswold Hanniston in Durrotar is bugged. Cant attack him for quest

http://www.wowhead.com/quest=25258/griswold-hanniston

**Comment by tomatosz** [comment]
Known issue: #9581 #6926 #5605 

Also, next time you report a bug, please use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md).

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15298-9629958169265605-griswold-hanniston-smart_scripts/

**Comment by Jenovas** [comment]
Fix in 5537
