### ISSUE TITLE
[EN][Quest] Mount Hyjai Portal doesnt appear.

### ISSUE THREAD

**Issue by int24rain** [Atlantiss/BugTracker#963]
Hello there.I did the quest chain to Mount Hyjai and after 20 quests I decided to go back in SW to buy smth and when I came back there wasnt any portal to Hyjai..

**Comment by Aival94** [comment]
Reported here as well and i gave the specific quest which should unlock normally the portals as some proofs: https://github.com/Atlantiss/BugTracker/issues/3646

**Comment by BAndysc** [comment]
Since rev 5099 portal to Hyjal will appear once you finishe quest As Hyjal Burns
