### ISSUE TITLE
[EN/PL][Glyph][Shaman] Glyph of Shocking doesn't works

### ISSUE THREAD

**Issue by Olrios** [Atlantiss/BugTracker#9631]
**Description**:
[en] Glyph of Shocking doesn't works at all.
[pl] Glyph of Shocking w ogóle nie działa.

**Current behaviour**:
[en] Even with that glyph equipped global cooldown shared between Shaman's Shock spells is still 5 seconds. If you use any shock spell at this moment all shocks spells are going to 5 second cooldown.
[pl] Nawet z założonym glypem globalne CD dzielone pomiędzy Shockami Shama jest nadal równy 5 sekund. Jeśli uzyjesz jakiegokolwiek shocka to wszystkie shocki dostają 5 sekund cd.

**Expected behaviour**:
[en] When you equip that glyph your shared cd between shock spells should be equal to 1 second.
[pl] Z założonym glyphem dzielone cd pomiędzy shockami powinno być równe 1 sekundę.

**Steps to reproduce the problem**:

1. use any shaman shock, check cds on all shocks
2. equip glyph of shocking
3. repeat step 1.

**Revision**: 5535 date 20-10-2017

**Comment by Katonetwo** [comment]
it says global cooldown, not cooldown
if it was just the cd that would reduce it to 0 with the talent

**Comment by Qrowrequiem** [comment]
The gcd disappears, this glyph doesnt delete cd from your shocks.

**Comment by Olrios** [comment]
You are all wrong.
The glyph says exactly "to 1 second".
And it reduces cooldown from 5 second to 1. This is how it always worked in all versions of wow. The glyph and how you understanding it is wrong.

This is how it must work:
Expected behaviour:
[en] When you equip that glyph your shared cd between shock spells should be equal to 1 second.
[pl] Z założonym glyphem dzielone cd pomiędzy shockami powinno być równe 1 sekundę.
