### ISSUE TITLE
{EN}I have not quests In Unending Numbers ,The Vainglorious, The Path of Dragon Soul, Documenting the Timeways.  

### ISSUE THREAD

**Issue by poleloa** [Atlantiss/BugTracker#9636]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Hello gm's and other players you know i'm as Farana in game, but on my death knight i have not this quests,why? I did End Time,Murozond,The Well of Eternity,Hour of Twilight q speak with npc. Help please.
Thanks in top Poleloa(in game Farana,Avenger of Hyjal,85 Death Knight Human,Female,370+ilvl)

**Description**: in my profile haven't that quests. I do not know why.

**Current behaviour**: After did earlier quests i clicked on npc and no next quests.

**Expected behaviour**: Quests which i said npc should give.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by poleloa** [comment]
please help i didn't get any comment
I did Well of Eternity,but haven't that quests ,which i told earlier.
Please

**Comment by poleloa** [comment]
i waited too much time for help. But i did not get answer,so i must close issue,sorry.

**Comment by Piklo** [comment]
lol

**Comment by poleloa** [comment]
sorry but i'm not patience player 
I told on the issue haven't that quest
