### ISSUE TITLE
[EN][Quest][Northern Barrens] Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by Valdanif** [Atlantiss/BugTracker#9638]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem You cannot get into the caravan, quest giver Rocco Whipshank does not give you the option.

**Current behaviour**: What happens Quest giver Rocco does not allow you to get into the caravan

**Expected behaviour**: What should happen Quest Giver Rocco should allow you to get into the caravan when you talk with him.

**Steps to reproduce the problem**:

1. Caravan is not working
2. Quest giver doesn't get you into the caravan
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
Please check whether a bug is already posted before posting it yourself: #3718

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18125-quest-crossroads-caravan-delivery/

**Comment by TranceAccount** [comment]
Did you fix this @Bildo ?

**Comment by Bildo** [comment]
nah, just closed duplicate
