### ISSUE TITLE
[EN][NPC][Well of Eternity] Mannoroth

### ISSUE THREAD

**Issue by trolloh** [Atlantiss/BugTracker#9654]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Mannoroth in Well of Eternity is bugged after stunning him

**Current behaviour**: At the third phase when Captain died, if you stun Mannoroth his script doesnt work anymore, and he cant be killed, he has 1/82994K HP

**Expected behaviour**: You shouldnt be able to stun him

**Steps to reproduce the problem**:

1. Get to Mannoroth
2. Kill Captain Varo'then
3. Stun Mannoroth

**Revision**:  5535
P.S: Im not sure how it should go, never killed him in retail but I finally want to report him because nobody did it yet

**Comment by mabz1** [comment]
U can also stun captain varo'then which im sure shouldnt be the case

**Comment by karolnpc** [comment]
Bump come on how can you leave it like this

**Comment by xmesaj2** [comment]
rev 5632 fixed
