### ISSUE TITLE
 [Zen'Kiki and the Cultists] Quest

### ISSUE THREAD

**Issue by Veryalive** [Atlantiss/BugTracker#9655]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Bears are already out of the cage and im not able to complete the quest since the Troll is not with me to heal the Bears after releasing them from the cages.

**Current behaviour**: Nothing, Bears stand outside of the cages and the troll that should be with me from the quest aint there.
**Expected behaviour**: Bears should be inside the cages so that after i click to release them come out and then the troll Npc called "Zen'Kiki" should heal the bears.
![wowscrnshot_110317_073522](https://user-images.githubusercontent.com/33342529/32364005-41dd9460-c06a-11e7-925f-8932f3d9807b.jpg)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by tomatosz** [comment]
Duplicate: #9150 #4513 #3954

Also, please use the proper tags in the title (as explained in the template)

**Comment by Snake90** [comment]
Still bugged.
Now even the bears are in the cages and the cages are closed, the quest can't be completed.

**Comment by rnel76** [comment]
As of this posting, the bears are out of their cages, and non interactable

**Comment by Snake90** [comment]
Still bugged. The bears are in the cages but Zen'Kiki doesn't heal them. The quest can't be completed.
