### ISSUE TITLE
[PL][Achievement]Warglaives of Azzinoth and Warglaives of Azzinoth - Guild Edition

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#9660]
Link1: http://www.wowhead.com/achievement=426/warglaives-of-azzinoth
Link2: http://www.wowhead.com/achievement=5185/warglaives-of-azzinoth-guild-edition

**Description**: Dzisiejszego dnia poleciała mi druga część Warglaive of Azzinoth, po założeniu obu broni nie otrzymałem żadnego achiva zarówno ja, jak i gildia.

**Current behaviour**: Brak achievementu

**Expected behaviour**: Po założeniu obu części powinienem dostać achievement jak i gildia

**Steps to reproduce the problem**:

1. Załóż dwie części Warglaive of Azzinoth
2. Nic się nie dzieje

**Revision**: 5535
![wowscrnshot_110717_162723](https://user-images.githubusercontent.com/21290619/32502863-246900ca-c3dc-11e7-866c-e21b4d05cfcd.jpg)
![wowscrnshot_110717_162738](https://user-images.githubusercontent.com/21290619/32502880-2ba536ba-c3dc-11e7-8b87-eccf64a9dc17.jpg)

**Comment by Piklo** [comment]
duplicate #6708
