### ISSUE TITLE
Recipe: Mightfish Steak

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#9663]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [This recipe](http://www.wowhead.com/item=13948/) is sold by 3 NPCs [Sheendra Tallgrass](http://www.wowhead.com/npc=8145), [Vivianna](http://www.wowhead.com/npc=7947) and [Kelsey Yance](http://www.wowhead.com/npc=2664/) the last one doesn't have it.

**Revision**: Current server version 5535

**Comment by Piklo** [comment]
read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use)
