### ISSUE TITLE
'"Documenting the Timeways" missing quest on End of Time

### ISSUE THREAD

**Issue by Azotox** [Atlantiss/BugTracker#9664]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

In the inside the instance End of Time Npc named alurmi should have 2 quests :
Archival Purposes 
Documenting the Timeways this quest is missing an should bring as new items

**Comment by Piklo** [comment]
read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use) and use our [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)
