### ISSUE TITLE
[EN][NPC] Nefarian

### ISSUE THREAD

**Issue by Othentik** [Atlantiss/BugTracker#9665]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Nefarian only drop Chest T2

**Current behaviour**: Last boss of Black Wing Lair (Vanilla) should gives 1x Helm + 1x Chest and actually gives chest only.

**Expected behaviour**: Drop 1x helm and 1x chest

**Steps to reproduce the problem**:

1. Kill Nefarian
2. Loot
3. 

**Revision**: Rev 5535

Thanks in advance :)

**Comment by MichaelArchangelo** [comment]
He drops helmets too, it's just random if he does or doesn't. Many classic/tbc boss loot tables are all over the place.

**Comment by Othentik** [comment]
https://wow.gamepedia.com/Blackwing_Lair_loot#Boss_loot

"The bosses of Blackwing Lair all drop two Tier 2 set pieces except for Firemaw, Ebonroc and Flamegor"

**Comment by Psychobird7** [comment]
Yes, Nefarian definitely drops both heads and chests. The drop rates are rather sketchy, but they do drop.
