### ISSUE TITLE
[EN][Dungeon] Well of Eternity - Mannoroth Boss Fight

### ISSUE THREAD

**Issue by Zerotech80** [Atlantiss/BugTracker#9666]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The boss battle script sometimes breaks, the adds/mobs that you supposed to encounter before Mannoroth sometimes they don't appear or are broken. Therefore you cannot complete the boss fight.

**Current behaviour**: What happens
Somtimes You are unable to engage the Infernal but skips instead to the bats therefore Mannoroth has a huge defensive buff that can only be broken by defeating the mobs and the mini boss.

When a wipe occurs, the next time you encounter the boss again, the group of bats don't shop up, therefore you are unable to encounter the boss fight.

**Expected behaviour**: What should happen instead
After you defeat the Infernal, you should engage with a group of bats then a mini boss and then fight Mannoroth

**Steps to reproduce the problem**:

1. When you don't fight the Infernal, but instead skip to fight the Group of bats 
2. Without killing the infernal first Mannoroth has a huge defensive buff that takes minimal damage from all players

**Revision**: ACore Rev 5535

**Comment by stanq87** [comment]
the boss fight breaks alot,  not only when u wipe, or stun bos o that captain guy, but even when u take on of those too far from their orgina position,   everything respawns, including ilidian, but the event dosent go by script  and resets over and over, a  non blizlike solution would be a dialogue option a the begining to restart all to start point ( it needs to check for boss kill on id, so noone starts buging that)

**Comment by xmesaj2** [comment]
rev. 5629 fixed, bats shouldn't be attackable until infernal dies
