### ISSUE TITLE
[EN][ITEM] Sulfuras, Hand of Ragnaros

### ISSUE THREAD

**Issue by phixor** [Atlantiss/BugTracker#9667]
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)

**Description**: http://www.wowhead.com/item=17182/sulfuras-hand-of-ragnaros passive of this item does not work. It's silly as it's legendary item and I'm guessing nobody had opportunity to use that weapon for other reasons than cause of its representative value. It never hurls fireballs (however it's 5dmg to attacker on hit works).

**Current behaviour**: https://image.ibb.co/jcCRfw/Wo_WScrn_Shot_111317_180350.jpg
here is ss from test that I've done. I had that fire blasting trink equipped to show that my recount is capable of measuring dmg done from such side sources (in the picture it's flame lash). As you can see 92 melee hits were dealt (I think that it's enough to provoke at last 1 fireball proc), but there was no single fireball proc.

**Expected behaviour**: Sulfuras's proc chance should be around 6.19% (according to my personal experience from Nostarlius private realm, that used to be faithful copy of retail vanilla).

I know that fixing such things got no priority over working on cata content but as it's legendary weapon I'm looking forward for seeing it hurlin balls and wreckin it's targets.

**Revision**: 5535

**Comment by MichaelArchangelo** [comment]
There's already a mass application [here](https://github.com/Atlantiss/BugTracker/issues/8171), cause there are quite a few weapons with no working proc.
