### ISSUE TITLE
Blocker when u playing playthrough as Worgen

### ISSUE THREAD

**Issue by Anttiax** [Atlantiss/BugTracker#9668]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Get stucked when playing plathrouh as Worgen and use HearthStone

**Current behaviour**: Player cannot continue in playthrough

**Expected behaviour**: Player should be continue in playthrough

**Steps to reproduce the problem**:

1. Create Worgen Character
2. to accomplish the task where you throw poles to worgens
3. Use Hearth Stone

**Revision**:  4.3.4 15595 x86

**Comment by Piklo** [comment]
read [how to use](https://github.com/Atlantiss/BugTracker#how-to-use)

**Comment by duzda** [comment]
Nevermind, solved by using [Have Group, Will Travel] spell, took a moment to figure out, but leveling up another worgen and in same phase of chain, we were able to teleport the bugged one,
