### ISSUE TITLE
[EN][NPC][Item] Level 60 PvP sets

### ISSUE THREAD

**Issue by Dethawk** [Atlantiss/BugTracker#9669]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:  Before writing anything, I would like to note that it is stated as "fixed"(https://community.atlantiss.eu/index.php?/topic/12978-6257-6253-5766-4238-5974-4291-legacy-pvp-quartermasters/), but it still doesn't work, so please don't mark this as duplicate. This NPC (http://www.wowhead.com/npc=12785/sergeant-major-clate) is supposed to sell the level 60 pvp set for every class, however it is only available for warriors, not for other classes. As a growing 60 twink community, the sets would be very useful for everybody. Here's a screenshot about the vendor list from a hunter: http://tinypic.com/r/1zyy6gw/9

**Current behaviour**: The set is only available for warriors.

**Expected behaviour**: Each class set should be available for their respective classes.

**Revision**: 5535

**Comment by Drokal** [comment]
Set is available for warriors and warlocks.
Oh my god xD I love these sets so much!

**Comment by Dethawk** [comment]
It's not available for warlocks what are you talking about?

**Comment by tomatosz** [comment]
The fix you linked is still in the folder 'Post your fix', not in 'Accepted', and the related bugtracker posts are not closed. That means that the fix is not (yet) implemented. I don't know why it isn't implemented, but at least one thing I could think of is that, with that fix, everyone can see the gear for all classes, from lvl 60, 70 and 80 sets.

**Comment by wtRCH** [comment]
????? FIX PENDING for 1 year

**Comment by Piklo** [comment]
works fine
