### ISSUE TITLE
[EN][QUEST][DUN MOROGH] It's Raid Night Every Night

### ISSUE THREAD

**Issue by Gaewix** [Atlantiss/BugTracker#9673]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After taking quest nothing happens

**Current behaviour**: Frostmane Raiders doesn't appears

**Expected behaviour**: After taking the quest there should appear Frostmane Raiders. They are suppose to stole Ram in the ranch and we are suppose to defend the Amberstill Ranch.

**Steps to reproduce the problem**:

1.  Take the quest, nothing happens
2.  abandon quest
3.  Take the quest again and, again, nothing happens

**Revision**: Current server 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
#3134 
Duplicate
