### ISSUE TITLE
[EN][Recipe (Leatherworking)] Drakehide Leg Reinforcements

### ISSUE THREAD

**Issue by cyberknight1993** [Atlantiss/BugTracker#9677]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Recipe is missing from Leatherworking trainers which should be learned normally like its twin recipes Dragonscale Leg Reinforcements for example.

It is changed in latest patches on Wowhead so I will link you different source I could find: https://wow.gamepedia.com/Drakehide_Leg_Reinforcements
**Current behaviour**: What happens
It is not in trainers list.
**Expected behaviour**: What should happen instead
It should be in trainers list.
**Steps to reproduce the problem**:

1. Visit Leatherworking trainer.
2. See the mentioned recipe not available.
3. /cry

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5535 hash. 145845f01b17 (date) +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15405-recipe-drakehide-leg-reinforcements/

**Comment by poleloa** [comment]
Uhh it is not a little trouble . 
I minded about blacksmithing choice: weaponsmith or armorsmith.
But that server has not it. I should write it to forum?

**Comment by tomatosz** [comment]
First of all, this is not related to the issue, next time make a new issue for this sort of thing.
In this case, the feature has been removed in Cataclysm so it is correct that it’s not there.

**Comment by Jenovas** [comment]
Fix in rev 5541
