### ISSUE TITLE
[EN][Quest][Ashenvale] Got Wood?

### ISSUE THREAD

**Issue by Satyr87** [Atlantiss/BugTracker#968]
http://www.wowhead.com/quest=13628
when you try to ride on brutusk he walks 2 meters and disappears
quest objective is not completed
quest cant be completed
(what they wrote in wowhead comments doesnt fix it here but thats a different bug anyway)

**Comment by Adramen** [comment]
Quest was working as intended when I did it on May 17, 2015

**Comment by awike** [comment]
This is still bugged as of June 21st 2015

**Comment by JurajNyiri** [comment]
This quest is still bugged. I can't get on Brutusk because i don't have Reins from Kadrak.
