### ISSUE TITLE
[EN][PET][CLASS] Mage Pet

### ISSUE THREAD

**Issue by Dimitrijed93** [Atlantiss/BugTracker#9697]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Description: Water Elemental Petbar is missing and the pet cant be dismissed.

Current behaviour: There is no water elemental petbar and he cant be controlled at all.

Expected behaviour: it should be able to control ones pet and to dismiss him.

Steps to reproduce the problem: 

1. 
2. 
3. 

Revision: ACore rev. 5536 hash. 808aad465152 2017-10-30 17:50:29 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by xmesaj2** [comment]
closing as it's related to #9696
