### ISSUE TITLE
[EN][Quest][Temple of Ahn'Qiraj] Mortal Champions(ID 8579)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#9700]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest is repeatable, not prerequisite and missing progress text.

**Current behaviour**: On the server quest is repeatale, not prerequisite for the reapatable version and is missing progress text.

**Expected behaviour**: The quest [Mortal Champions(ID 8579)](http://www.wowhead.com/quest=8579/mortal-champions) should not be repeatable but one time quest. Furthermore should be prerequisite quest for the Repeatable version [Mortal Champions(ID 8595)](http://www.wowhead.com/quest=8595/mortal-champions) and should have the progress text which is shown on the wowhead link.

**Steps to reproduce the problem**:

1. Speak with NPC [Kandrostrasz <Brood of Alexstrasza>](http://www.wowhead.com/npc=15503/kandrostrasz) for first time and see have both quest available.
2. Click the first quest and see its progress missing.
3. After you complete the one time quest speak with npc to see that is again available.

**Revision**: 5536

**Comment by TranceAccount** [comment]
Confirmed.

**Comment by TranceAccount** [comment]
Fixed in rev. 5657.
