### ISSUE TITLE
[EN][Quest][Temple of Ahn'Qiraj]Imperial Qiraji Regalia(ID 8790) and Imperial Qiraji Armaments(ID 8789)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#9701]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quests are failing automatically when you take them and quest items do not drop from bosses.

**Current behaviour**: Quests [Imperial Qiraji Regalia](http://www.wowhead.com/quest=8790/imperial-qiraji-regalia) and [Imperial Qiraji Armaments](http://www.wowhead.com/quest=8789/imperial-qiraji-armaments) are failing automatically when you take them and quest items [Imperial Qiraji Regalia](http://www.wowhead.com/item=21237/imperial-qiraji-regalia) and [Imperial Qiraji Armaments](http://www.wowhead.com/item=21232/imperial-qiraji-armaments) do not drop from bosses(Have not tested [Elementium Ingot](http://www.wowhead.com/item=18562/elementium-ingot).

**Expected behaviour**: Quests should not fail and quest items should drop from bosses.

**Steps to reproduce the problem**:

1. Kill bosses and never see quest items.
2. Take the Quests
3. See the quests failing instantly.

**Revision**: 5536

Related/Reported here but missing the quest items issue: https://github.com/Atlantiss/BugTracker/issues/9307, https://github.com/Atlantiss/BugTracker/issues/9306

**Comment by Aival94** [comment]
Related/Reported here but missing the quest items issue: https://github.com/Atlantiss/BugTracker/issues/9307, https://github.com/Atlantiss/BugTracker/issues/9306

**Comment by henkka90** [comment]
The Imperial Qiraji Regalia and Armaments both have low drop chance, it's something like 8%. So it's not always a guaranteed drop from bosses. The drop rate did seem fine to me when i was killing the AQ40 bosses.

**Comment by Aival94** [comment]
I killed all bosses and not even one dropped and last time that i killed them again before 1 month same happened. So i think they are not dropping(Note: Quest items should drop without the need to have the failed quest on log)

**Comment by tomatosz** [comment]
@Aival94 The items do drop, and you don't need the quest to make them drop.

**Comment by Aival94** [comment]
Ok then. Closing the issue as the correct one is reported by henkka90
