### ISSUE TITLE
[EN][Npc][Transmog] Warpweaver Hashom <Transmogrifier>[Bugged]

### ISSUE THREAD

**Issue by infamous99** [Atlantiss/BugTracker#9707]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
![wowscrnshot_121017_103814](https://user-images.githubusercontent.com/34410422/33802240-9d6c6496-dd98-11e7-9aca-beb66e1c23bf.jpg)

[//]: # ([EN][Web] Armory doesnt work)

**Description**: I am Unable to Transmog any of my items
**Current behaviour**: All items are grey @ transmogifier

**Expected behaviour**: We should be able to Transmog easily

**Steps to reproduce the problem**:

1. I have no idea
2. IDK
3. Not a Clue

My items for Transmog are in BAG and still all are grey.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
iirc if your items are grey it means they are not transmogrified already, just try

**Comment by infamous99** [comment]
iirc? There is no option for transmogify , even though I bring my mouse or click.... nothing works

**Comment by Qrowrequiem** [comment]
All items are and will be grey in tmog npc as long as you wont tmog them. Tired right clicking on item in your bag you want to tmog?

**Comment by infamous99** [comment]
Yes I did

**Comment by infamous99** [comment]
But nothing works...

**Comment by infamous99** [comment]
OK Dragging the item to the piece fixes the problem for me...

**Comment by Piklo** [comment]
https://www.google.pl/amp/s/www.urbandictionary.com/define.php%3fterm=iirc&amp=true
