### ISSUE TITLE
Problem with aliance qvests in Badlands 44-47 

### ISSUE THREAD

**Issue by cmoudo33** [Atlantiss/BugTracker#9708]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Problem with qvests in Badlands 44-47 

**Current behaviour**: not working and missiong qvests

**Expected behaviour**: working qvests

**Steps to reproduce the problem**:

1. qvest {45} The Warden's Pawn 
- the qvestion mark not exsist, nothing happend
http://www.wowhead.com/quest=27796/the-wardens-pawn

2. qvest {45} Lifting the Veil 
- is missing from the game
http://www.wowhead.com/quest=27770/lifting-the-veil
3. 

**Revision**: 4.3.0 (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
#6774 badlands is not scripted

**Comment by cmoudo33** [comment]
What do you mean whith not scripted?

**Comment by Piklo** [comment]
quests are not working
