### ISSUE TITLE
[EN][Npc][Drop] Murozond- arrow of time

### ISSUE THREAD

**Issue by Ishgar** [Atlantiss/BugTracker#9710]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description:**  Arrow of Time got about 16% Chance to drop, yet didn't dropped on my shaman a single time. 

**Current Behavior:** Trinket even with low drop rate, never drops, they were players who farmed it for 3 months with no effects.

**Expected Behavior:** Literally endless grind should be stopped and bugged drop rate fixed.
                                                       
**Steps to reproduce the problem:**
                                                        
All in "Expected Behavior"

**Comment by Buggingtrack** [comment]
It's called RNG, not a bug, you should blame it for the endless grind

**Comment by tomatosz** [comment]
The Arrow of Time is in the loot tables correctly, so you just had bad luck and this issue can be closed. Also, next time please provide a link to wowhead or a similar website.
