### ISSUE TITLE
[EN][Quest][Winterspring] 'Borrowing' From the Winterfall

### ISSUE THREAD

**Issue by brolio** [Atlantiss/BugTracker#9714]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The looted meat doesn't count towards the quest completion

**Current behaviour**: The meat racks are spawned, and lootable correctly, but when the meat is used it doesn't progress the quest 

**Expected behaviour**: Using the meat should allow to complete the quest

**Steps to reproduce the problem**:

1. Fly to furbolg camp
2. Loot smoked meat from the racks
3. Spawn the cub
4. Use the meat

**Revision**: ACore rev. 5546 hash. f82d8fdadc95 2017-12-09 15:36:55 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by TranceAccount** [comment]
I have a fix for the quest reward.
