### ISSUE TITLE
[EN][Item] Quivers dont get displayed

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/BugTracker#9717]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Quivers equipped as bags dont display on character's back.
**Current behaviour**: What happens
There are few EX-ammo bags, quivers more specificly, now turned common bags, left in game in cataclysm. You can equip them just as you do your normal bags, but sadly they dont display behind your back.
**Expected behaviour**: What should happen instead
These should display on anyones back when they equip it in their bag slots. It would be such a cool feature for players, hunters mostly, and it is blizzlike - here's a screenshot of a cata shadowpriest with a quiver equipped - http://www.wowhead.com/item=34105/quiver-of-a-thousand-feathers#screenshots:id=211723
**Steps to reproduce the problem**:
1. Fly to Hillsbrad and buy a quiver of your factions respective Alterac Valley representative (Stormpike guard for the alliance, Frostwolf clan for the horde) for 50 honor.
2. Equip it, and see for yourself that it does not display behind your back.
3. 

**Revision**: 5549

**Comment by TranceAccount** [comment]
It was blizzlike in TBC

**Comment by Shanrolol** [comment]
Wowhead screenshot with a priest from cata, using it as a regular bag and still getting it displayed makes it clear, that its blizzlike in cata too.

**Comment by Sainsyl** [comment]
Comment of another quiver  - "As of 4.1 quivers will no longer show on characters."
http://www.wowhead.com/item=18714/ancient-sinew-wrapped-lamina

**Comment by Shanrolol** [comment]
A pity, ok then.
