### ISSUE TITLE
[PL][Item] Potion of Illusion

### ISSUE THREAD

**Issue by Taaak** [Atlantiss/BugTracker#972]
Po uzyciu(http://www.wowhead.com/item=58489) pojawia sie komunikat"The spell is not available to you" i nic sie nie dzieje.

**Comment by Bildo** [comment]
duplicate https://github.com/Atlantiss/BugTracker/issues/1234

**Comment by micha666** [comment]
Dalej nie działa. "This spell is not availble to you"
