### ISSUE TITLE
[EN][SPELL][MAGE] Mirror image

### ISSUE THREAD

**Issue by Dimitrijed93** [Atlantiss/BugTracker#9722]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Description: The summoned mirror images are supposed to aid me in battle and attack my target. Instead, they are most of the time staying passive.

Current behaviour: The summoned mirror images are not attacking my target.

Expected behaviour: They are supposed to cast arcane blasts (due to my glyph) on my target.

Steps to reproduce the problem:

1. Use mirror image while attacking someone.
2. Watch their behaviour.
3. 

Revision: 5549

**Comment by Olrios** [comment]
This bug refers to all pets, shaman's elementals have the same behavior. All are bugged.

**Comment by pelekon** [comment]
Fixed in rev 5840
