### ISSUE TITLE
[EN][Quest][Achievements][Character] Faction Change Went Wrong / Disappeared Not Completed Loremaster Achievements

### ISSUE THREAD

**Issue by KieraHorde** [Atlantiss/BugTracker#9727]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After changing faction to Horde, I've discovered that certain achievements (Loremaster of Eastern Kingdoms and Loremaster of Kalimdor, as well as some achievements for Horde-Only leveling zones did not appear in my list. I have changed faction back to Alliance, and still have missing Loremaster of Kalimdor, as well as lost track of quests for Stonetalon Mountains Quests achievement.
![wowscrnshot_122617_195257](https://user-images.githubusercontent.com/13039049/34367079-5338243a-eaa6-11e7-8ab6-f8a41c74883c.jpg)
![wowscrnshot_122617_195303](https://user-images.githubusercontent.com/13039049/34367087-6915c6a4-eaa6-11e7-8028-f2af51598a19.jpg)

**Current behaviour**: Achievement "Loremaster of Kalimdor" (http://www.wowhead.com/achievement=1678/loremaster-of-kalimdor) doesn't appear in the list at all.

**Expected behaviour**: It should be there.

**Steps to reproduce the problem**:

1. Log in to my character?
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by MichaelArchangelo** [comment]
#8534
