### ISSUE TITLE
[EN] Stuck in Deepholm

### ISSUE THREAD

**Issue by Nahoris** [Atlantiss/BugTracker#9729]
Hi. I've done 51 quests in DH and there is no more. I was using questcompletist and questhubber. I was where the tags were and there were no tasks. Could you help me?

**Comment by Piklo** [comment]
check wowhead or downlaod any quest helper addon

**Comment by Nahoris** [comment]
As i said i was using 2 quest helper addons without effect

**Comment by pelekon** [comment]
Pro it, its bug tracker, its place to report bugs and it isnt bug, in case of any problems in game you should contact our support via in game ticket system.
