### ISSUE TITLE
[EN][Quest][Ashenvale] Return Fire

### ISSUE THREAD

**Issue by josue1795** [Atlantiss/BugTracker#9731]
http://www.wowhead.com/quest=13853/return-fire#comments
**Description:**
Right clicking on the Astraanar throwers don't work.
Completing this quest removes the fires and Horde attackers.

**Comment by tomatosz** [comment]
Duplicate of #8084 and #7311

Also please use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md).

**Comment by TranceAccount** [comment]
## Posted a fix on the forum for the mounting part:

https://community.atlantiss.eu/index.php?/topic/18255-npc-astranaar-thrower-cecidit-parody/

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653.
