### ISSUE TITLE
[EN][Dungeon] Random Dungeon Finder Level Requirements Incorrect

### ISSUE THREAD

**Issue by icee5** [Atlantiss/BugTracker#9737]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
At level 83 my character CANNOT specific queue or join: Halls of Origination, Grim Batol, Lost City of the Tol'Vir. However I am allowed to enter the dungeons manually through a portal which means random dungeon finder locks people out of entering these dungeons for no reason. 

**Current behaviour**: What happens
RDF does not display the dungeons listed above when your character is level 83. This should not be the case. 

**Expected behaviour**: What should happen instead
You're able to enter the dungeons yourself so it should allow you to queue for them at 83 through the RDF interface as well.

**Steps to reproduce the problem**:
1.  Open RDF interface as level 83
2.  Halls of Origination, Grim Batol, Lost City of the Tol'Vir dungeons aren't available for queue
3.  

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
5554

**Comment by Piklo** [comment]
Maybe your ilvl is too low?

**Comment by tomatosz** [comment]
You can always walk i to dungeons at a lower level than the required level to rdf queue. 
Check requirements:
http://www.wowhead.com/halls-of-origination
http://www.wowhead.com/grim-batol
http://www.wowhead.com/lost-city-of-the-tolvir
