### ISSUE TITLE
[en][NPC][Echo of Bairne]

### ISSUE THREAD

**Issue by sstndr** [Atlantiss/BugTracker#9738]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)[

**Description**: Describe the problem
Echo of Baine in End Time instance applies his debuff as removeable buffs
**Current behaviour**: What happens
Whenever Echo of Baine gets dragged in the lava, Molten Axe dot "Molten Blast" gets applied as a buff to his current target, allowing players to right-click it.

**Expected behaviour**: What should happen instead
Molten blast should be a debuff.

**Steps to reproduce the problem**:

1. Enter the instance and reach the Eco of Baine
2. Drag the cow in the lava.
3. Notice how the dot gets applied as a buff, and how it can be removed with /cancelaura

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
5554

**Comment by TranceAccount** [comment]
Fixed in rev. 5849.
