### ISSUE TITLE
[EN][Quest][Zone] Documenting the Timeways

### ISSUE THREAD

**Issue by Ishgar** [Atlantiss/BugTracker#9742]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: In cata after quest "Archival Purposes", was another one "Documenting the Timeways" possible to start from Alurmi in End Time or Well of Eternity.

http://www.wowhead.com/quest=30097/archival-purposes
http://www.wowhead.com/quest=30104/documenting-the-timeways

**Current behaviour**: There is only first quest of those two.

**Expected behaviour**: Quest should be able to get from Alurmi after completing "Archival Purposes"

**Revision**: ACore rev. 5554 hash. ed65e1f912d5 2017-12-27 12:45:07 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by RangerTalion** [comment]
There are more quests missing from Well of Eternity

http://www.wowhead.com/quest=30099/in-unending-numbers
http://www.wowhead.com/quest=30100/the-vainglorious
http://www.wowhead.com/quest=30101/the-path-to-the-dragon-souls

The last one awards the BiS Belt for Shamans for 4.2 patch and it really bugs me that I can't get it

**Comment by Laskko** [comment]
Is there any information on these quests?
Especially this one: http://www.wowhead.com/quest=30104/documenting-the-timeways

**Comment by TranceAccount** [comment]
@Laskko with information you mean if it got fixed or if this report is still relevant?

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5854.
