### ISSUE TITLE
[EN][Spell][Mage] Ignite

### ISSUE THREAD

**Issue by firemagegodx** [Atlantiss/BugTracker#9743]
Description: Whenever you crit with a Fire spell, a DoT is applied to the boss, doing 20% of the impact damage twice over 4 seconds. (once and 2, and once at 0 seconds remaining.)

Describe the problem: Ignite can get stacked for way higher than intended. 

Current behaviour: At the moment, Ignite gets higher whenever you crit above 2 seconds remaining on the DoT. This is always the case. On the other hand if you crit below 2 seconds remaining, the Ignite gets roughly cut in half.

Expected behaviour: Ignite should do damage in a more logical manner. 
10k crit applied, 2k damage twice.
Another 10k crit applied, now it will tick for 4k every 2 seconds, aka twice.
If you then crit 4 seconds after the first initial 10k, it will still be 4k per tick, because the original Ignite has run out at this point

Example from retail: https://www.youtube.com/watch?v=1tX64eLakrs&t=240s
This video shows quite clearly how his Ignites rarely get higher, despite chaining them. This is because they hit for roughly the same, so the Ignite can't get any higher than what he has, because he's not magically casting faster or doing more damage to avoid the 4s damage time.

Example from Atlantiss: https://www.youtube.com/watch?v=hf64WWGB8Kk&t=153s
Here you can see how consecutive crits are building an Ignite far beyond what should be capable.

I simply used Alysrazor as a way to prove this, since you have 100% crit chance.

Revision: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Frostbreaker** [comment]
Rewrite whole ignite script aka noone has idea how it should properly work even blizzard xD

**Comment by pelekon** [comment]
Not bugged
