### ISSUE TITLE
[EN][spell][mage] Mage t13 

### ISSUE THREAD

**Issue by PolpoVolante** [Atlantiss/BugTracker#9746]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ( [EN])
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
Mage tier13 2p and 4p not working properly.

**Current behaviour**: 
1 - 2P procs off any damage for all spec. 
2 - 4p Does not consume stacks of stolen time and does not reduce the cooldown of the cds.

**Expected behaviour**: 
The stolen time buff gets procced from fireball/pyro/frostbolt with a 50% chance and from arcane blast with a proc chance of 100% for a max of 10 stacks (500 haste).
When combustion/icy veins/arcane power is expired all the stacks should get removed.

4p For every stack of stolen time that was removed from using combustion/icy veins/arcane power their respective cooldown should be reduced by 5sec/15sec/7sec per stack consumed.

**Steps to reproduce the problem**:

1.  get t13 
2. dummy 
3.  cast any spell

**Revision**: 5570

**Comment by PolpoVolante** [comment]
After the fix there is still something to change:

1 Fireball/pyroblast/frostbolt have 100% chance to proc  stolen time should be 30%

2 Pyroblast! from hot streak proc does not give a stack.

**Comment by Frostbreaker** [comment]
Aactually chance to proc stolen time should be 50%, according to http://www.wowhead.com/spell=105788/item-mage-t13-2p-bonus-haste

**Comment by PolpoVolante** [comment]
My bad I wrote comment in a hurry.

**Comment by PolpoVolante** [comment]
2p - Resets cooldown of combustion even without 4p and if combustion is spread it resets the cooldown entirely.

**Comment by PolpoVolante** [comment]
as of 5599 

2p - Resets cooldown of combustion even without 4p and if combustion is spread it resets the cooldown entirely.

2p - Stolen time is not procced from pyroblasts that come from hot streak
