### ISSUE TITLE
[EN][spell][hunter] Hunter t13

### ISSUE THREAD

**Issue by ZappBrannigan93** [Atlantiss/BugTracker#9747]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
hunters' 2p t13 not working as expected

**Expected behaviour**: What should happen instead
2p t13 for hunter should make cobra shot generate 18 focus instead of 9 
**Current behaviour**: What happens
 I feel no difference in focus gained through cobra shot wrt the t12 set, while t13 4p seems to work perfectly fine. So it still generates 9 focus.

This is the list of gear to remove from Pranab in PTR:
77029
77030
77031
77032
77215
**Steps to reproduce the problem**:
1. Get t13
2. dummy
3. cast cobra shot and verify the focus gained

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by pelekon** [comment]
should be fixed in rev 5577
