### ISSUE TITLE
[EN][Spell][Paladin] Paladin T13

### ISSUE THREAD

**Issue by Giovanni2293** [Atlantiss/BugTracker#9748]
**Description**: 
Paladin Retribution T13 set doesn't work properly.

**Current behaviour**: 
1- 2p  bonus doens't work properly because any direct skill like (Exorcism, Divine storm, Holy wrath, Hammer of wrath adds holy power), meaning crusader strike adds 2 holy power (1 from skill and 1 from set) and templar veredict also adding one holy power(spending it and then adding one). The only skill working properly with this 2p set is Judgement, it adds 1 holy power.
2- 4p bonus set Doesn't work properly because any Skill adds the effect from 4p bonus, meaning on 4 set bonus being active forever.

**Expected behaviour**: 
1- 2p bonus adds 1 holy power only from using Judgement not any direct skill.
2- 4p Set bonus should be only active when using Zealotry.

**Steps to reproduce the problem**:

1. Gear up Tier 13 Retribution Paladin.
2. Dummy
3. Cast any spell.

**Revision**: 5570

**Comment by Psychobird7** [comment]
https://github.com/Atlantiss/BugTracker/issues/9538
