### ISSUE TITLE
[EN][Rogue] T13 item sets

### ISSUE THREAD

**Issue by firemagegodx** [Atlantiss/BugTracker#9749]
Description: 2-set: Gives you 20% less energy cost on your abilities when using Tricks of the Trade.
4-set: Gives 2 seconds extra on Shadow Dance, 3 seconds extra on Adrenaline Rush and 9 seconds extra on Vendetta.

Current behaviour: 2-set does not give 20% reduced energy cost.
4-set works very well atm.

Expected behaviour: Tricks of the Trade should give 20% energy cost reduction for 6s when used.

Steps to reproduce the problem: 

1. Equip 2-set
2. Press Tricks
3. Enjoy the sight of nothingness

Revision: 5570, type ".s info" ingame to see the current revision.

**Comment by pelekon** [comment]
fixed in 5578 unfortunately It doesnt appear in changelog
