### ISSUE TITLE
[EN][Quest][Hellfire Peninsula] The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Myunri** [Atlantiss/BugTracker#9750]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
You should speak to Anchorite Barada in the room where Colonel Jules is to start the exorcism but he doesn't have a talk option. 
(http://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules)

**Current behaviour**: 
Anchorite Barada doesn't have a talk option to start the exorcism.

**Expected behaviour**: 
You should be able select an talk option with Anchorite Barada to start the ritual. It should say "I am ready, Anchorite. Let us begin the exorcism."

**Steps to reproduce the problem**:

1. Accept the quest with Assistant Klatu in Honor Hold inn, second floor
2. Go to room where Colonel Jules is 
3. Speak with Anchorite Barada to find no option to start the ritual

**Revision**: 5554

**Comment by Lluksonak** [comment]
Still bugged as of rev. 5612

**Comment by tomatosz** [comment]
Fixed in rev. 5660
