### ISSUE TITLE
[EN] [ACCOUNT] I didn't receive the confirmation email.

### ISSUE THREAD

**Issue by Lucasjapagamer** [Atlantiss/BugTracker#9757]
**Description**: Describe the problem
   My friend is creating an account and does not receive a confirmation email. He tried with other data and it did not work.
**Current behaviour**: What happens
   He can't created account
**Expected behaviour**: What should happen instead
   After a moment you receive a confirmation email
**Steps to reproduce the problem**:

1. ...
2. ...
3. ..

**Revision**: 4.3.4

**Comment by PlainDoll** [comment]
I can confirm this, as I've waited for whole day for this confirmation to come, tried resending multiple times aswell. Fix this, please.

**Comment by Lucasjapagamer** [comment]
In account creation has option have If You didn't receive activation link please use this form that worked again. Who was bugged but also came back

**Comment by xmesaj2** [comment]
http://atlantiss.eu/reactive

**Comment by MercuricUma** [comment]
Done it twice but didn't receive anything. : /
