### ISSUE TITLE
[Mage] [Talent] [Blazing speed & impact] procrate

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9760]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Blazing speed and impact proc rate is way too high. 

**Current behaviour**: Blazing speed and impact proc rate is way too high. 

**Expected behaviour**: Blazing speed and impact proc rate is way too high. 

**Steps to reproduce the problem**:

1. Blazing speed and impact proc rate is way too high. 
2. Blazing speed and impact proc rate is way too high. 
3. Blazing speed and impact proc rate is way too high. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
> Expected behaviour: Blazing speed and impact proc rate is way too high.

please make proper post

**Comment by Psychobird7** [comment]
2/10. Not enough effort to disguise the obvious trolling.
