### ISSUE TITLE
[EN][Spell][Priest] Divine Hymn

### ISSUE THREAD

**Issue by Bislibur** [Atlantiss/BugTracker#9764]
**Description**: 
Divine Hymn at 0 haste should have and does have a cap of 20 heals as shown in the tooltip. 
However, at the haste breakpoints that grant an additional tick (12.5%, 37.5%, 62.5%,... haste) the cap should be increased by 5 each time automatically. 
There is a variety of video material and logs from retail servers supporting this claim.

Example video (1:07:40-1:07:55):
https://youtu.be/xK5fEC52IME?t=1h7m40s
You can see the Diviny Hymn ticks on the scrolling combat text, there are clearly more than 20.

Example logs (randomly chosen from World of Logs ranking lists):
http://www.worldoflogs.com/reports/rt-n5dk453v40b4maw5/details/4/?s=5730&e=5991
See "Healing by spell", 58 heals from divine hymn, check "buffs cast" to see it actually is only one spellcast.

http://www.worldoflogs.com/reports/rt-03w55tl45jbt6jvw/details/7/?s=948&e=1105
Same here, this time it's a disc priest and its 35 heals from 1 divine hymn.

**Current behaviour**: 
Divine Hymn automatically cancels after 20 heals, even if there are more potential ticks to come.

**Expected behaviour**: 
Divine Hymn should keep channeling beyond 20 heals if the above mentioned haste thresholds are met.

**Steps to reproduce the problem**:

1. Get in a group of 5 or more people, let them stack on you.
2. Get a lot of haste, at least over 12.5%.
3. Cast Divine Hymn.

**Revision**: 
rev. 5595

**Comment by Psychobird7** [comment]
The following EJ thread confirms this. 
https://web.archive.org/web/20120126054209/http://elitistjerks.com:80/f77/t127522-4_3_discipline_priest_compendium       
"Divine Hymn
Changed in 4.3 to heal the 5 lowest health raid or party members (up from 3). Always use hymns 
when buffed with Borrowed Time, a haste trinket or bloodlust (or both). **Tick gains and haste calculations 
are made at the start of the channel**, so beginning the cast with only a second or two left on bloodlust 
is enough to get the benefit for the entire channel. 
see also Haste and Channeled Spells" 
See the bolded part.  

Someone on wowhead also seems to have noticed it happening. 
http://www.wowhead.com/spell=64843/divine-hymn#comments:id=1627744

**Comment by Bislibur** [comment]
Following the links you posted brought me to the following site:
https://web.archive.org/web/20111230054236/http://www.wowpedia.org:80/Divine_Hymn#Known_bugs

_However as of Patch 4.2.2, Divine Hymn responds normally to haste, with sufficient amounts granting extra ticks and so an increased total amount of healing. By using haste-granting trinkets, racials and spells (such as [Power Infusion]) before casting Divine Hymn, the priest can dramatically increase the number of ticks [...]_

This suggests that divine hymn getting extra ticks was actually a bug.
However the fact that Blizz never fixed the bug and even removed the caps in an MoP-pre-patch
leaves the Atlantiss devs to decide if they want divine hymn to work _as intended_ OR **blizzlike**.

**Comment by Psychobird7** [comment]
It must have been intended then, clearly. 
Blizzard have removed/broken everything they did not agree with in the game, be it add-ons, set bonuses (including pre-pulls obviously, see mage T10), you name it.

**Comment by Jenovas** [comment]
[5829] Priest:
- Divine Hymn will now scale with haste. There is no longer a limit to the amount of times it can heal.
