### ISSUE TITLE
[EN][Trinket][PVP vendors]No medallion trinkets at the PVP vendors

### ISSUE THREAD

**Issue by Simmenthal** [Atlantiss/BugTracker#9766]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description:**
Since the DS was released all PVP vendors of alliance faction are not selling medallions trinkets anymore.
such as http://www.wowhead.com/item=72414/ruthless-gladiators-medallion-of-meditation and all the others. 
Same problem for season 10 and 11 vendors.
I already checked horde faction and they are OK there.

**Comment by Piklo** [comment]
should be fixed in [rev. 5596](https://atlantiss.eu/changelog#rev5596)
