### ISSUE TITLE
[EN][Quest][Sholazal Basin] Still on it

### ISSUE THREAD

**Issue by cmoudo33** [Atlantiss/BugTracker#9768]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

sorry, name of qvest is **Still at it**
**Description**: I can't complete this qvest 76 Still at it
http://www.wowhead.com/quest=12644/still-at-it

**Current behaviour**: There is too many empty kegs, so I can't find qvest item

**Expected behaviour**: None empty kegs before complete this qvest

**Steps to reproduce the problem**:

1. Keg is still next to "Tipsy"
2. when you grab qvest Still on it → you can open the keg, but he is empty
3. when you do all "Tipsy" commands the keg is still empty

**Revision**: 4.3.4

**Comment by Volcanicus** [comment]
I can confirm this is still happening. Perhaps make the keg spawn into the bag at the end of the DDR minigame?

**Comment by TranceAccount** [comment]
Confirmed. Fix soon.

**Comment by TranceAccount** [comment]
Fixed in rev. 5659.
