### ISSUE TITLE
[en][NPC]Corla, herald of Twilight

### ISSUE THREAD

**Issue by sstndr** [Atlantiss/BugTracker#9769]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The boss can be dragged far, far away from the adds, trivializing the encounter.

**Current behaviour**: Currently you can (and most groups do) grab the boss and drag her on the structure in the far side of the room, completely ignoring the ad mechanic: even if they get transformed they won't aggro the group nor react in any way, making it a tank and spank encounter

**Expected behaviour**: Nice question. I have no clue if on retail the adds should try to murder you no matter where you are (which sounds the most obvious explanation), or if the boss should either leash or enrage if too far from her platform, 

**Steps to reproduce the problem**:

1. Get to blackrock cavern
2. Take the boss for a stroll on the structure - or sufficently far away from her adds
3. Wait for them evolve and chit-chat while their boss is getting murdered.

**Revision**: 5597

**Comment by xmesaj2** [comment]
rev. 5629 fixed
