### ISSUE TITLE
[EN][Dungeon][Well of Eternity] Dungeon completion broken

### ISSUE THREAD

**Issue by martijnhaah** [Atlantiss/BugTracker#9772]
**Description**: Describe the problem
After completing the Well of Eternity (http://www.wowhead.com/well-of-eternity) by beating Mannoroth and Varo'then (http://www.wowhead.com/npc=54969/mannoroth) (http://www.wowhead.com/npc=55419/captain-varothen), the dungeon does not get completed.

For example, valor points are not rewarded. Other issues may be present aswell (not sure, but I believe it will give you dungeon deserter aswell when you leave).

**Expected behaviour**: What should happen instead
When you "kill" mannoroth, points should be rewarded. The dungeon should be "completed".

**Steps to reproduce the problem**:

1. Kill all the bosses
2. Let the scripts complete their dialogue
3. Valor points not rewarded

Revision: 5597

**Comment by stanq87** [comment]
well the end of the dungeon is after ilidian ends his speech not after bos dies, or loot chest spans / gets open, try that and come back. btw if u leave party before ilidian  ends his event u will get a deserter debuff

**Comment by martijnhaah** [comment]
I did stay the whole event after the dungeon (just because I like the whole roleplay event thingy). It did not give me deserter, but it did not give me the valor points either.

**Comment by martijnhaah** [comment]
Re-tested today. Dungeon will award achievement etc. But no valor points, tanksatchel or anything else than loot.
Waited the whole event + 5 more minutes.

**Comment by xmesaj2** [comment]
rev. 5629 fixed
