### ISSUE TITLE
Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by Xaltorez** [Atlantiss/BugTracker#9773]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] [Crossroads Caravan Delivery][Northern Barrens]
[//]: # ([EN][NPC] [Rocco Whipshank]

**Description**: Talk to Rocco Whipshank at Grol'dom farm and escort his caravan all the way to Crossroads" There is no such option to move on with the caravan while talking to Rocco at Grol'dom farm

**Current behaviour**: There's no start button whilst talking to Rocco

**Expected behaviour**: Click button and start.
**Steps to reproduce the problem**:

1. Start the quest.
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Blackaddder** [comment]
Already reported and open: #3718

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18125-quest-crossroads-caravan-delivery/
