### ISSUE TITLE
[EN][Quest][Blasted Lands]Blood Ritual

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#9774]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Blood Ritual : http://www.wowhead.com/quest=26160/blood-ritual

**Description**:  The quest can't be completed because the NPC doesn't start the ritual.

**Current behaviour**: The NPC have to start the ritual after we talk to him but he doesn't. 

**Expected behaviour**: When we talk to him, we can normally choose " I would like to start the Blood Ritual, Kasim. " but now we can't. 

**Steps to reproduce the problem**:

1. Take the quest [The First Step] from Kasim Sharim in Blasted Lands and do it. So now you can take the quest [Blood Ritual] from the same NPC.
2. Try to talk to the NPC.
3. You can't.

**Comment by tomatosz** [comment]
There is a fix on the forums, just have to wait till it’s implemented :)

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
