### ISSUE TITLE
[ENG][Achievement][Higher Learning] The Schools of Arcane Magic - Illusion

### ISSUE THREAD

**Issue by RastaTinu** [Atlantiss/BugTracker#9775]
Link1: http://www.wowhead.com/achievement=1956/higher-learning
Link2: http://www.wowhead.com/object=192865/the-schools-of-arcane-magic-illusion

**Description**: The book does not appear in the place where it should, I checked it for over a month every day, also after dc

**Current behaviour**: There is no book

**Expected behaviour**: Among the random books appearing in this place should also appear "The Schools of Arcane Magic - Illusion" book

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5604

**Comment by tomatosz** [comment]
The book does appear. But some other book in the same place can get bugged and not respawn, and then it’s stuck till the next server restart.

**Comment by Piklo** [comment]
fix by tomatosz https://community.atlantiss.eu/index.php?/topic/15615-gameobject-books-for-higher-learning-despawn/

**Comment by TranceAccount** [comment]
@Piklo Any news?
