### ISSUE TITLE
[EN][Zone]Grim Batol skip

### ISSUE THREAD

**Issue by sstndr** [Atlantiss/BugTracker#9776]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: It is possible to skip the whole dungeon with a clever reconnection on the drakes.

**Current behaviour**: If you logout and login during the drake fly-by in grim-batol you get reconnected on the ground, allowing you to completely skip the instance if done properly.
![wowscrnshot_011418_213157](https://user-images.githubusercontent.com/1354707/35003236-7802861a-faec-11e7-801a-a8ced0585664.jpg)

**Expected behaviour**: Nice question. A wild guess is that the dragon you're riding doesn't disappear, and you get reconnected where the dragon is.

**Steps to reproduce the problem**:

1. Join Grim Batol (either df or just walk in)
2. Free the drakes and fly over the place, until you get to an interesting place to dismount
3. Logout and log-in to get dropped where you want.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
5604

**Comment by xmesaj2** [comment]
rev. 5629 fixed
