### ISSUE TITLE
[EN][Quest][Tirisfal Glades] Speak with Sevren

### ISSUE THREAD

**Issue by Chaos-Kayze** [Atlantiss/BugTracker#9778]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem: Original quest giver does not give you the remains.

**Current behaviour**: What happens: When you gather the remains for the first quest you should get them from the current quest giver. However, he does not give you the remains.

**Expected behaviour**: What should happen instead: Quest giver gives you the remains to take back to the next NPC.

**Steps to reproduce the problem**:

1. After turning in both; Deaths in the Family and The Haunted Mills you should get the next quest: Speak with Sevren
2. Initial quest giver does not give you the remains.
3. Quest ID 24989

**Revision**: Current server version (Rev. 5604)

**Comment by tomatosz** [comment]
There seems to be an issue with quest order. You can already get Speak with Sevren while you have Deaths in the Family. If you then hand in the latter, you lose the item, but it is provided if you use the correct order.
Closing this issue.
