### ISSUE TITLE
[EN][Quest][Darkshore][The Bear's Blessing]

### ISSUE THREAD

**Issue by eline328** [Atlantiss/BugTracker#9783]
Hi!

There is a problem with the quest [The Bear's Blessing] in Darkshore : http://www.wowhead.com/quest=13544/the-bears-blessing

The NPS is friendly so I can't attack him to got its tailfeathers which is necessary to complete the quest.

Other issues regarding this have been closed..but not been fixed

Please help!

Thanks!

**Comment by TranceAccount** [comment]
Have you tried to remove a buff?

**Comment by eline328** [comment]
How?

**Comment by eline328** [comment]
![image](https://user-images.githubusercontent.com/35601874/35164663-95c4ecae-fd4b-11e7-96eb-4845f2891c9b.png)

**Comment by TranceAccount** [comment]
Top left corner on that bear mark and right click it? Or make a ticket for unaura

**Comment by eline328** [comment]
Didnt work :/ but thanks! I will make a ticket
