### ISSUE TITLE
[EN] [Spell] [Death Knight] Rune Strike

### ISSUE THREAD

**Issue by Katonetwo** [Atlantiss/BugTracker#9789]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Rune Strike is currently missing its base damage, and only doing 180% weapon damage regardless of attack power.
![rs](https://user-images.githubusercontent.com/32794643/35188697-d492c646-fe3a-11e7-86ab-d3f1128f8e98.jpg)
![rs2](https://user-images.githubusercontent.com/32794643/35188744-f5851ede-fe3b-11e7-8b14-e63f5cb91a8d.jpg)

**Current behaviour**: Rune Strike does a solid 20% less than it should

**Expected behaviour**: Rune Strike should scale with attack power as well as weapon damage

**Steps to reproduce the problem**:

1. Locate a training dummy while in Blood spec (or Blood Presence, or both)
2. Use Rune Strike on it, and melee it
3. Compare the damage numbers on Rune Strike to your melee autoattacks, notice that Rune Strike does pretty much exactly 180% of your autoattack damage, even though it should do more

**Revision**: 5604

**Comment by Psychobird7** [comment]
Did you take armour reduction and weapon damage ranges into account?

**Comment by Katonetwo** [comment]
this test was done with a skullstealer greataxe hc, so 3.60 speed
(no fallen crusader rune ofc)

armor reduction on rune strike and melees is the same, since they are both physical and neither ignore armor

as for damage ranges, 113 rune strikes and 218 melees should be good enough to get a decent average at the very least, and the average, minimum, and maximum all have basically the same factor, 180%

**Comment by Psychobird7** [comment]
Rune strike is normalised, so in order to get accurate results, you should run this test with a 3.3 speed weapon.

**Comment by Axelitoo** [comment]
Did calculations for myself.
[((((ap/14)×3.3)×1.8)+ap×0.18)] = 6531 + 2863 = 9 399
9 399 / 1.46 to account for armor = 6 437.
Sorta confirmed by simcraft, it claimed the expected damage to be roughly 6 500.

**Comment by Piklo** [comment]
should be fixed in [rev5837](https://atlantiss.eu/changelog#rev5837)
