### ISSUE TITLE
[EN][Spell][Warrior] T13 2p set bonus

### ISSUE THREAD

**Issue by Alexski123** [Atlantiss/BugTracker#9794]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
T13 2 set bonus is not working properly

**Current behaviour**: What happens
Whenever I use Inner Rage the buff that's supposed to reduce your Heroic Strike by 10 rage does not apply, as seen in the picture below
![wowscrnshot_012218_191200](https://user-images.githubusercontent.com/35699901/35235005-9389004e-ffab-11e7-9e08-2d9355ee4112.jpg)
But when I'm getting healed the buff applies, and it reapplies with every single heal I get.
![wowscrnshot_012218_192611](https://user-images.githubusercontent.com/35699901/35235053-b810601a-ffab-11e7-818a-a8bbc53320bd.jpg)

**Expected behaviour**: What should happen instead
Everytime I use Inner Rage and only during its duration i should receive a buff that reduces the rage cost of Heroic Strike to 20.

**Steps to reproduce the problem**:

1. Equip 2 pieces of the Warrior Tier 13 set
2. Use Inner Rage
3. 

**Revision**: 5609

**Comment by LemonPotatoes** [comment]
I confirm this issue, Heroic Strike does not cost 20 rage as it should when Inner Rage is active
