### ISSUE TITLE
[en][spell][item] Drain Life and legendary staff

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9796]
**Description**: Drain life interaction with legendary staff is currently bugged. All channeled spells should be duplicated by additional tick of channeling spell. On ats you get additional damage as terecgosa wrath.

**Current behaviour**: drain life replicated ticks are considered as arcane damage.

**Expected behaviour**: All channeled spells interaction with legendary staff is additional "wave" of channeled spell (like additional arcane missle)

"Channeled spells like  [Arcane Missiles] will gain an additional tick when a duplication is triggered."

https://wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest
http://wowwiki.wikia.com/wiki/Drain_Life

**Steps to reproduce the problem**:

1. equip staff
2. go dummy
3. cast drain life

**Revision**: 5609

**Comment by blinkmaster** [comment]
bump

**Comment by pelekon** [comment]
fixed in rev 5891
