### ISSUE TITLE
[en][spell][item] Unstable affliction dispel damage and legendary staff

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9798]
**Description**: Legendary proc duplicates from unstable affliction dispel damage do 1 dmg.  They should duplicate the dispel dmg

**Current behaviour**: It duplicates 1 dmg.

**Expected behaviour**: should duplicate full damage.

https://wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest
Duplicated spells behave as if you did cast them. They are subject to the same talents, buffs, debuffs and other conditions. They can also trigger other procs except the spell duplication from the staff itself.

**Steps to reproduce the problem**:

1. equip staff, go duel healer
2. dot healer with ua tell him to dispel it
3.  watch 1 dmg from legendary procs on ua dispel.

**Revision**: 5609

**Comment by blinkmaster** [comment]
bump

**Comment by pelekon** [comment]
fixed in rev 5891
