### ISSUE TITLE
[EN][Spell][Druid] Druid t13 4p set bonus

### ISSUE THREAD

**Issue by AudacityTheCat** [Atlantiss/BugTracker#9801]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The t13 4p set bonus is not working correctly

**Current behaviour**: After using Frenzied Regeneration, your party members still get the buff called Mass Regeneration but it does not affect even the max hp nor the hp regeneration of those. If using the Frenzied Regeneration glyph, the 30% healing increase is working

**Expected behaviour**: The Party members should have their max hp increased by 15% of the druid hp and also regenerate hp while not using the glyph

**Steps to reproduce the problem**:

1. Invite someone to your party
2. Use Frenzied Regeneration (must be at least 15 second in bear form prior to that)
3. Now you can see the Mass Regeneration effect not working properly

**Revision**: 5604

**Comment by Vayns** [comment]
Confirming the report. Just adding that https://github.com/Atlantiss/BugTracker/issues/8159 is related; making the 4set slightly better than it currently can be.
