### ISSUE TITLE
[EN][Spell][Death Knight][Warrior][Mechanic] Death Grip - Spell Reflection doesn't Reflect it.

### ISSUE THREAD

**Issue by Aridam** [Atlantiss/BugTracker#9802]
**Description**: Death Grip cannot be Reflected by Spell Reflection.

**Current behaviour**: If a Warrior uses Spell Reflection, Death Grip doesn't do what it's supposed to do under such circumstances, which is to work-backwards and pull the DK to the Warrior instead.

**Expected behaviour**: Using Death Grip on Spell Reflection is supposed to bring the DK to the Warrior.

**Steps to reproduce the problem**:

1. Use Spell Reflection;
2. Get Death Gripped;
3. SR doesn't Reflect DG and drag the DK to you instead -- you still get DG-ed to the DK.

**Revision**: 5609

Proof of this mechanic: https://us.battle.net/forums/en/wow/topic/2353275510?page=1
https://www.youtube.com/watch?v=kHoJYHUY02Q

**Comment by Katonetwo** [comment]
i am around 95% sure this is false
![wowscrnshot_012518_130356](https://user-images.githubusercontent.com/32794643/35387542-80ecda6a-01d0-11e8-8098-79e8b4db5b73.jpg)
![wowscrnshot_012518_130529](https://user-images.githubusercontent.com/32794643/35387543-8109bc0c-01d0-11e8-995d-456a3cfc6206.jpg)

**Comment by Aridam** [comment]
Did Arenas and in both Matches I did Spell Reflection and DG didn't get Reflected while the Buff stayed up, so not sure what that's all about.

**Comment by Aridam** [comment]
Coming back here to update on things: It seems the bugreport is invalid as DG is indeed affected by Spell Reflection -- seems it was just finicky due to lag/Spell Queue system.

**Comment by Varnae** [comment]
This problem has been solved already.
