### ISSUE TITLE
[EN][Profession][Herb] Northern Stranglethorn - Undermap Nodes

### ISSUE THREAD

**Issue by Synathy** [Atlantiss/BugTracker#9803]
ACore rev. 5609
Some herb nodes are being undermap in Northern Stranglethorn.
46.8/54.2 - Bruiseweed : https://i.imgur.com/V4L0wtx.jpg
46.0/35.5 - Wild Steelbloom : https://i.imgur.com/qtQDN3h.jpg

WoWHead links
http://www.wowhead.com/object=1622/bruiseweed
http://www.wowhead.com/object=1623/wild-steelbloom

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18147-gameobject-miscellaneous-objects/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)
