### ISSUE TITLE
[EN][Spell][Mage] Blink

### ISSUE THREAD

**Issue by Elannreportujerzeczy** [Atlantiss/BugTracker#9805]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: after blink, mage is immune for stuns for a while
http://wowwiki.wikia.com/wiki/Blink

**Current behaviour**: Mage is immune for stuns after he blinks for short while.
video: https://youtu.be/WfwMyJ6YT8I

**Expected behaviour**: This effect shouldn't occur
https://www.youtube.com/watch?v=Ba6Ty72eSH8
3:51 ; 5:34 ; 5:54 ; 7:17

**Steps to reproduce the problem**:

1. Best use warrior to reproduce the problem
2. Be prepared for mage's blink
3. Charge instantly after he blinks or be in place where he's going to blink and use throwdown instantly after the blink.
**Revision**: 
rev:5609

**Comment by blinkmaster** [comment]
https://us.battle.net/forums/en/wow/topic/1660219995

not a bug. 

bug is tho, that using blink gives hidden buff "blink" with 0 sec duration. It should be visible to everybody. thus you will see when you can use stuns/roots.

**Comment by Elannreportujerzeczy** [comment]
doesnt it last too long then?

**Comment by blinkmaster** [comment]
i don't think so. it lasts less than 1 sec for sure :) need some tests to do but i cba

**Comment by Jenovas** [comment]
This is probably a bug caused by latency + aura update delay that retail servers had.
Bladestorm should have the same bug that allows to use Bladestorm up to 0.5sec after receiving a CC and Bladestorm should break the CC. We didn't add the Bladestorm bug and we won't be adding this one.
