### ISSUE TITLE
[EN][Spell][Death Knight] T13 2p set bonus 

### ISSUE THREAD

**Issue by Vaelinnn** [Atlantiss/BugTracker#9809]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: With T13 2 piece bonus , rime or sudden doom has a chance to proc x2 charges 

**Current behaviour**: x2 charges are used up with a single howling blast

**Expected behaviour**: It should be 1 charge=1howling blast

**Steps to reproduce the problem**:

1. Equip 2 piece of t13 dk gear
2. cast oblitirate on dummy to proc x2 rime
3. cast howling blast

**Revision**: 4.3.4

**Comment by freddie12** [comment]
here is the link for "Expected Behaviour" : http://www.wowhead.com/spell=105609/item-death-knight-t13-dps-2p-bonus
