### ISSUE TITLE
[EN][Profession][Fishing] Deepsea sagefish school - no loot

### ISSUE THREAD

**Issue by zinikh** [Atlantiss/BugTracker#9810]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: no loot for fishing in a Deepsea sagefish school in Twilight highlands 

**Current behaviour**: sometimes we get fishing levels and after few attempts the school disappears confirming the attempts are successful but no loot is awarded.

**Expected behaviour**: loot window should open showing the fish caught or error message displayed telling the player that "your fish got away! / no fish are hooked."

**Steps to reproduce the problem**:

1.  Head to twilight highlands
2.  Search for schools of deepsea sagefish on the southern side of the map
3.  attempt fishing.

**Revision**: ACore rev. 5609 (4.3.4 branch)

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/18143-gameobject-deepsea-sagefish-school-loot/

**Comment by zinikh** [comment]
hi, does this mean the fix has been applied in the game ? or i need to apply it somewhere on my gamefiles ?
PS: tried today and still no loot from "deepsea sagefish schools"

**Comment by tomatosz** [comment]
It was posted on the forums, after that a dev still has to implement it and then the server has to be restarted for it to be effective. 
The server has been restarted just now, so the pools should now work.

**Comment by zinikh** [comment]
thumb's up. confirming the fix. tested and was able to fix in several schools in twilight highlands.
thanx
