### ISSUE TITLE
[EN][Quest][Dragonblight] The Chain Gun And You

### ISSUE THREAD

**Issue by Lluksonak** [Atlantiss/BugTracker#9813]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The 7th Legion chain guns cannot be mounted

**Current behaviour**: Right-clicking does nothing - it only targets them like any other mob.

**Expected behaviour**: The player mounts a chain gun to mow down the ghouls while the stranded soldiers make an attempt to escape http://www.wowhead.com/quest=12457/the-chain-gun-and-you

**Steps to reproduce the problem**:

1. Accept the quest
2. Right click the 7th Legion Chain Gun
3. That's about it...

**Revision**: 5609

**Comment by TranceAccount** [comment]
Can't reproduce on PTR

**Comment by TranceAccount** [comment]
Adding npc_spellclick to the chain gun makes them phase out.

**Comment by TranceAccount** [comment]
## Posted a fix on the forum:

https://community.atlantiss.eu/index.php?/topic/18183-npc-7th-legion-chain-gun/

**Comment by MercuricUma** [comment]
I didn't quite get what to do to make the quest completable. I mean about your fix. :S.

**Comment by TranceAccount** [comment]
The fix I posted on the forum should make the chain gun mountable after a developer applies it to the main realm.

**Comment by MercuricUma** [comment]
oh can't wait that quest to be fixed. Need 2 more quests for the achievement. thanks for your reply. I thought there was a macro or something else to do

**Comment by TranceAccount** [comment]
Fix got accepted. Comment if still presists. Rev 5653. Just wait for the server to update.
