### ISSUE TITLE
[EN][Spell][Mage] Mage t13 2p set bonus

### ISSUE THREAD

**Issue by Frostbreaker** [Atlantiss/BugTracker#9817]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Stolen Time from mage's t13 2p set bonus http://www.wowhead.com/spell=105788/item-mage-t13-2p-bonus-haste does not proc from fire spec talent Hot Streak.

**Current behaviour**: Stolen Time does not proc from instant pyroblast, fire talent Hot Streak.

**Expected behaviour**: Stolen Time SHOULD proc from pyroblast whether it is casted or instant, fire talent Hot Streak, and as in description should have 50% to appear.

**Steps to reproduce the problem**:

1. Proc Hot Streak by using fireball, frostfire bolt, scorch or fire blast;
2. Cast instant pyroblast;
3. Track no Stolen Time proc;

**Revision**: rev.5612

**Comment by firemagegodx** [comment]
On the topic of Stolen Time, what is the proc chance of this? I had it dropped 3 times on Baleroc, and only reached 10 stacks during Time Warp, when it after dropped.

**Comment by pelekon** [comment]
@firemagegodx 100% on Arcane Blast and 50% on rest of spells which can proc it.
