### ISSUE TITLE
[EN][Quest] Battle For The Scarlet Monastery : Killing Commander Mograine 

### ISSUE THREAD

**Issue by juantequila** [Atlantiss/BugTracker#9818]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The quest requires High Inquisitor Whitemane and Commander Mograine to be slain. 
When High Inquisitor Whitemane is killed it counts towards the quest. However when Commander Mograine is slain it does not count.
**Current behaviour**: What happens
When Commander Mograine is killed, the quest does not register him being slain.

**Expected behaviour**: What should happen instead
When Commander Mograine is killed, the quest detects him being slained.

**Steps to reproduce the problem**:

1. Go to instance
2. Kill Commander Mograine
3. Kill doesn´t count

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 5612

**Comment by TranceAccount** [comment]
Wowhead link :s

**Comment by TranceAccount** [comment]
I don't see anything wrong with it.
You know how this quest works right? 
First you "kill" him and then you start attacking Whitemane. At 50% hp of Whitemane, you get stunned and she resurrects Mograine. After that you get credit for both kills if you kill them.

**Comment by juantequila** [comment]
Sorry, we tried it until she resurrected Mograine. Works fine
