### ISSUE TITLE
[PL][WEB] Armory

### ISSUE THREAD

**Issue by mitim1** [Atlantiss/BugTracker#982]
Jeśli ubijemy jakiegoś bossa w wersji hc na armorach pokazuje ze ubiliśmy go w wersji 25 norm. 

Dodatkowo jeśli ubijemy ods hc na armorach pokazuje nam się : 
Kill boss Omnotron (25 normal) 
Kill boss Arcanotron (25 normal)
Kill boss Toxitron (25 normal) 
Kill boss Electron (25 normal) 
Kill boss Magmatron (25 normal)

**Comment by armano2** [comment]
nie
