### ISSUE TITLE
[EN][Items] Proc Trinkets and equip Cooldowns

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9822]
**Description**: There are major issues with proc trinkets 

**Current behaviour**: 
- It is currently possible to proc a trinket, then unequip it, and keep its proc. 
- Proc trinkets do not go on a 30s cooldown when equipped. 

**Expected behaviour**: 
- Every trinket buff should be lost the moment it is unequipped 
- All on-use trinkets and all proc trinkets should go on a 30s CD when equipped. **For on-use trinkets, this works. For proc trinkets, it does not.** 

https://wow.gamepedia.com/Trinket
"After equipping a trinket, there is a 30-second delay before it can be used and any passive effect will start after the hidden internal cooldown, if any."
It is unclear whether this should affect the trinket's base stats and/or any stacking mechanics like License to Slay. 

https://www.mmo-champion.com/threads/877367-Shared-Cooldown
See the 4th post
 "Once you remove a trinket any buffs you get from it are removed. So activating and removing the trinket in stealth wouldn't work.
Try it" 

6th post
"Don't forget that equipping a trinket puts it on a 30-second cooldown as well. If you get out of combat and swap trinkets immediately, you still can't use the new ones until that cooldown ends too."

https://www.mmo-champion.com/threads/1120365-Warlock-Tips-and-Tricks-and-Specific-Encounter-Guides-4-3 
Read the section on "Gear swap" for more detail. It describes the gear/trinket swapping and the trinkets' behaviour, and confirms the information found on the wiki article, as well as the other MMOC thread. 

**Steps to reproduce the problems**:
1. Equip any proc trinket (my testing was done with Heart of Rage) 
2. Proc it 
3. Unequip said trinket, you will keep the buff 

-------- 
1. Equip any proc trinket 
2. Attempt to proc it immediately 
3. Notice the 30s CD on equip is not present 

**Revision**: 5612

**Comment by Psychobird7** [comment]
**Reliable** evidence welcome if you can find any.

**Comment by firemagegodx** [comment]
May also add on this topic, that some trinkets such as Matrix Restabilizer procs from anything. Fan of Knives, you name it.

**Comment by Psychobird7** [comment]
I'm fairly sure that issue with normal Matrix was fixed a while ago, because I haven't seen it proc from swiping the air in cat form lately.

**Comment by kadi2** [comment]
There was an issue with a Matrix proc, but in the end, someone found out that it could proc on retail from Sap too.

**Comment by meowmewo** [comment]
Bump. Too many demo warlocks started abusing this thing...!

**Comment by meowmewo** [comment]
Bump.

**Comment by RangerTalion** [comment]
I'll drop in and leave my two cents on this.
Steps to reproduce:
1. Pick an Elemental Shaman and make an Item Set with your raiding gear
2. Equip Ruthless (390) + Cataclysmic (403) Gladiator's Insignia of Dominance
3. Use Healing Rain on your raid / party members

4. Now you can either equip your Item Set or swap and proc even more trinkets, for example Foul Gift of the Demon Lord / Seal of the Seven Signs
5. Notice how you keep previous trinket procs even though they're unequipped
6. Proceed with your ridiculous burst and shapshotting of totems (Elemental Shaman) / doomguard (Demo Warlocks) etc etc

Warlocks are also able to pull this off with other trinkets that only proc from harmful spells and dealing damage, such as Theralion's Mirror / Soulshifter Vortex, by damaging themselves!

**Comment by pelekon** [comment]
fixed in rev 5788
