### ISSUE TITLE
[EN][Achievment] Alliance Slayer

### ISSUE THREAD

**Issue by maddy169** [Atlantiss/BugTracker#9828]
Description: Unobtainable achievments.

Current behaviour: The guild pvp achievments Slayers are simple, kill certain combinations of Alliance player (race-class), but even after killing any 85lv Alliance player, they never count, so the achievments are unobtainable, including Alliance Slayer wich unlocks the Guild Page. We have tried with guild members who are honorable, revered and exalted.

Expected behaviour: Honorable kills on 85lv Alliance players should count for the achievments (Human Slayer, Gnome Slayer, Draenei Slayer, Worgen Slayer, Dwarf Slayer and Night Elf Slayer).

Alliance Slayer Achievment: http://www.wowhead.com/achievement=5179/alliance-slayer
Guild Page: http://www.wowhead.com/item=65362/guild-page

Steps to reproduce the problem:

1. Kill any Alliance 85lv player.
2. Doesn't count for the achievments.

NOTE: I don't know if there is the same trouble for the Horde Slayer achievment.

Revision: 5623

**Comment by Aridam** [comment]
Confirmed and it's the same for the Horde Slayer overall and subsequentially for the prerequisites of it.
