### ISSUE TITLE
[EN][RAID][Firelands][Ragnaros] Incorrect 2nd intermission yell message

### ISSUE THREAD

**Issue by mati865** [Atlantiss/BugTracker#9830]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
When 2nd intermission starts wrong yell message is displayed causing some addons to loose their timers.

**Current behaviour**: What happens
Ragnaros yells: `Sulfuras will be your end` when he smashes with Sulfuras on start of 2nd intermission (1st intermission is OK).

**Expected behaviour**: What should happen instead
Ragnaros should yell: `Your judgement has come!` instead like on [this](https://youtu.be/zs0unBNQi_o?t=4m22s) video.

**Steps to reproduce the problem**:

1. Bring Ragnaros down to 40% hp.
2. See chat.

**Revision**: 5624

I can upload video from Atlantiss show this bug if necessary.

**Comment by Fortesqueg** [comment]
also Ragnaros didnt have many yell message like: Pathetic! Die insect! when he killed player, and some quotes wrong

**Comment by Fortesqueg** [comment]
Mortal Insects! You dare tresspass into MY domain? Your arrogance will be purged in living flame.
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_AGGRO.ogg')
Not ... No! That should be my finest hour! (?)
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_DEATH_HEROIC.ogg')
Too soon! ... You have come too soon...
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_DEATH_NORMAL.ogg')
You will be destroyed! (?)
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_DROP_01.ogg')
Die!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_DROP_02.ogg')
Your judgement has come!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_DROP_03.ogg')
Enough! I will finish this.
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_PICKUP_01.ogg')
Fall to your knees, mortals! This ends now.
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_PICKUP_02.ogg')
Sulfuras will be your end.
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HAMMER_PICKUP_03.ogg')
The realm of fire will consume you!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_PURGE_01.ogg')
Die, insect!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_KILL_01.ogg')
Pathetic.
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_KILL_02.ogg')
This is MY realm!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_KILL_03.ogg')
All ... EVERYTHING! (?)
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HEROIC_FIGHT_01.ogg')
Ah, intruder! This realm is not yours! (?)
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HEROIC_FIGHT_02.ogg')
When I finish this, my revenge will burn your wretched world, mortals! (?)
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_HEROIC_FIGHT_03.ogg')
Come forth, my servants! Defend your master!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_ADDS_01.ogg')
Minions of fire! Purge the outsiders!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_ADDS_02.ogg')
Denizens of flame, come to me!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_ADDS_03.ogg')
Arise, servants of fire, consume their flesh!
/script PlaySoundFile('sound/CREATURE/RAGNAROS/VO_FL_RAGNAROS_ADDS_04.ogg')

There is right quotes. http://ru.wowhead.com/npc=52409#english-comments

**Comment by Piklo** [comment]
should be fixed in [rev5753](https://atlantiss.eu/changelog#rev5753)
