### ISSUE TITLE
[EN][Death Knight] Death Knight T13 2p

### ISSUE THREAD

**Issue by dkt132setbonus** [Atlantiss/BugTracker#9832]
Description: T13 death knight dps 2 pieces set bonus is not working properly, bugged.

Current behaviour: Currently t13 2 pieces unholy death knight dps set bonus does only proc 1 sudden doom death coil charge and other one disappears.

Expected behaviour: Sudden doom has a 30% chance to grant 2 charges when triggered instead of 1 and both can be used separately.

Steps to reproduce the problem: Equip 2 pieces of t13 dps set as unholy death knight with sudden doom talent learned, auto attack the dummy until u get 2 procs of sudden doom, try to use both death coil charges.

**Comment by Maneto25** [comment]
any news on this? just got 2 set today and tested,still aint working

**Comment by poleloa** [comment]
Did u wear these items 397 or 410 ilvl ? 
How it should work? http://www.wowhead.com/item-set=1057/necrotic-boneplate-battlegear
or set for blood dk ?greetings

**Comment by dkt132setbonus** [comment]
hi poleloa, 

only available ilvl of the set is 397 at the moment ( couse hc mode of dragon soul is work in progress and raid finder is not planned to be implemented) , currently 2 set pieces for unholy shows that u get 2 charges of death coil couse of http://www.wowhead.com/spell=49530/sudden-doom#changelog talent and set bonus http://www.wowhead.com/spell=105609/item-death-knight-t13-dps-2p-bonus but its registered as a regural sudden doom proc and u get only 1 usable death coil. 

I can't provide any info on blood set bonus http://www.wowhead.com/spell=105552/item-death-knight-t13-blood-2p-bonus but my assumption its working fine since there are no reports of possible bugs on the bugtracker.

**Comment by freddie12** [comment]
will anyone take care of this?

**Comment by Maneto25** [comment]
cmon atlantiss its been 2 weeks when the post was made......

**Comment by Smiite** [comment]
As always fuck dk's :) ty for nice gameplay

**Comment by freddie12** [comment]
should we abandon hope on this or will we get any update/fix?

**Comment by c0ldw1nter** [comment]
Just tested this, and you do indeed get 2 stacks of Sudden Doom occasionally, however casting Death Coil consumes both of them instantly. Hoping for someone relevant to notice this post already

**Comment by freddie12** [comment]
it's been 3 weeks since this report was made. -.-

**Comment by freddie12** [comment]
bump -.-

**Comment by xmesaj2** [comment]
fixed in rev. 5655
