### ISSUE TITLE
[EN][Quest][Darkshore] Cleansing the Afflicted

### ISSUE THREAD

**Issue by VarWoW** [Atlantiss/BugTracker#9837]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: NPCs not becoming friendly and stopping their attack.

**Current behaviour**: After you cleanse a Corrupted Furbolg using the Blessed Herb Bundle, the NPC keeps attacking as a "Green" NPC, meaning you cant attack it even after the blob is dead.
**Expected behaviour**: The NPC is supposed to become friendly and stop their attack after killing the blob.

Video of the quest on retail: https://www.youtube.com/watch?v=xbCmP8M-N4M

**Steps to reproduce the problem**:

1.  Get [quest ](http://www.wowhead.com/quest=13545/cleansing-the-afflicted)
2. Use quest item, kill blob
3. NPC still attacks

**Revision**: 5630

**Comment by Bildo** [comment]
fixed
