### ISSUE TITLE
[PL][Class][Warrior] Shield Block and avoidance cap

### ISSUE THREAD

**Issue by Lenox07** [Atlantiss/BugTracker#984]
http://cata.openwow.com/spell=2565
Jeżeli używając shield blocka przekroczymy avo cap to nadwyżka blocku nie jest zamieniana na critical block.
http://imgur.com/TXvXeJv
http://imgur.com/RzRhzQA

**Comment by gumby123** [comment]
This bug makes protection warriors unplayable. It's almost 1 year and it's still not fixed.

**Comment by Jenovas** [comment]
Fixes
