### ISSUE TITLE
[EN][Spell][Gnome] Shortable Specialization

### ISSUE THREAD

**Issue by Dziaduszek** [Atlantiss/BugTracker#9841]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: http://www.wowhead.com/spell=92680/nimble-fingers#changelog

**Current behaviour**: Gnome's racial "Shortable Specialization" does not increase Spell Hit for casters while wearing daggers or swords. 
**Expected behaviour**: It should increase Spell Hit for casters by 1%.

**Steps to reproduce the problem**:

1. Be a Gnome Mage/Warlock.
2. Wear Dagger or One-handed Sword.
3. Check your Spell Hit.

**Revision**: 5631

**Comment by Frostbreaker** [comment]
Expertise is NOT hit, especially not spell hit. Delete this shit.

**Comment by Katonetwo** [comment]
that's  MoP thing

this is cata
