### ISSUE TITLE
[EN][Quest][Silithus] Signet of the Unseen Path

### ISSUE THREAD

**Issue by Pugzy** [Atlantiss/BugTracker#9842]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Quest can not be completed, end point isn't at the correct NPC/location. 
Not sure if this applies to all quests from Windcaller Yessendra or just this one (Hunter).

**Current behaviour**: 
The quest NPC Windcaller Yessendra starts the quest outside AQ40 but the completion point for this quest with Windcaller Yessendra is placed on the map in Cenarion Hold for some reason.

**Expected behaviour**: 
Quest should start and end at Windcaller Yessendra outside AQ40.
http://www.wowhead.com/quest=8704/signet-of-the-unseen-path

**Steps to reproduce the problem**:

1. Pick up quest from Windcaller Yessendra.
2. Have required items and rep.
3. View next stage of quest.

**Revision**: 5632

**Comment by tomatosz** [comment]
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/18190-quests-aq10-rings-and-weapons/

**Comment by tomatosz** [comment]
Fix in rev. 5645
