### ISSUE TITLE
[EN][Item] Cunning of the Cruel - proc rate

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9844]
**Description: 
the script seems to have an artificial cap on proc amount, 

**Current behaviour: 
it procs once from one target and olny on 23 of 24 targets ( it also should dmg the main target or the mob that it proced from), so in a raid seting of the time ppl where geting  about 9% of overal on sigle target boss and to 30% with alot off ads, we get 4% on aoe multi mob figts 3% on sigle target

https://www.youtube.com/watch?v=W4YqCbM42gY

**Expected behaviour: 
every 9 sec it should have  a 45% chance of procing from an atack (direct and dot) so if proced from a single aoe atack on 24 targets   best case scenerio  it should give ass 24 procs so 576 bolts . and all that is without  a legendary staff ( with the staff in theory it should have a chance to even double the number, dont even ask if your a ele shamn with hes mastery  o.O )

"On last week's logs, Heroic Cunning did 9.2% of my damage on H-Morchok and 8% on H-Ultraxion- on Yor'sahj it's been as high as 25% with numerous Yellow/Black/Red phases and a little luck. With the high spellpower scaling, this trinket continues to be the most OP piece of gear in this tier."

item
http://www.wowhead.com/item=77208
http://cata-shoot.tauri.hu/?item=77208

proc
http://www.wowhead.com/spell=108006/shadowbolt-volley
http://cata-shoot.tauri.hu/?spell=108006

proced spell
http://www.wowhead.com/spell=108005/shadowbolt-volley
http://cata-shoot.tauri.hu/?spell=108005

PS

"Cunning of the Cruel will now trigger its Shadowbolt Volley approximately three times as often, but will deal approximately one third as much damage. This results in the tooltip for the item being incorrect, but should moderate its burst damage in PvP."

here http://www.wowhead.com/spell=108006/shadowbolt-volley#changelog we se that after 4.3.3 the dmg was nerfed to (2820-4230)

https://us.battle.net/forums/en/wow/topic/3764968153

https://www.mmo-champion.com/threads/1075730-Cunning-of-the-Cruel-NERFED

PS2

best  forum comment (of the time)  i've seen that says alot of this trinkets power , "damn your legendary i got Cunning of the Cruel"

**Steps to reproduce the problem:

1.  go somewhere with alot od mobs
2.  atack with an aoe spell
3.  se how many bolts where spawned

**Revision**: rev. 5632

**Comment by Psychobird7** [comment]
Interesting report.    

"it also should dmg the main target or the mob that it proced from"     
Yes it should. Every target within 10 yards of the triggering spell's target (not the player's current target), including that target.   
If it doesn't, that is a legitimate bug.  

"every 9 sec it should have a 45% chance of procing"     
Which it does, as of 4.3.2. As a reminder, we are playing on 4.3.4, so we are getting the "post-nerf" version of the trinket.      

"if proced from a single aoe atack on 24 targets best case scenerio it should give ass 24 procs so 576 bolts"   
There is no evidence to suggest such behaviour.   

"with the staff in theory it should have a chance to even double the number"     
No. See the following.  
https://www.mmo-champion.com/threads/1074500-Dragonwrath-Cunning-of-the-Cruel  
-- "so it will proc a lone SB from the volley but not a copy of the volley" 

"On last week's logs, Heroic Cunning [...]"    
This entire quote is taken completely out of context, and you did not link to a source.  
Now the wowhead comment you took it from... the user's previous comment states the following: 
"On DS raid bosses, I'm averaging about 35k DPS as a Demo Lock and this trinket consistently accounts for about 8% of my total damage. Get it. Love it." 
35k DPS, as a Demo lock, having farmed DS long enough to have H Cunning, seems... *rather low.*  
The poster is also a warlock, a class that gets shadow damage multipliers. 
Either way that quote is not worth much without logs to support it.

**Comment by stanq87** [comment]
As an affliction warlock the proc alone was doing 6-12% of my overall damage on the last 3 bosses of Dragon Soul. The shadowbolts crit for up to 70k with my gear (Doomoracle@Cho'Gall).
I have some testing to do, but this trinket seems ABSURDLY good.
By Falcrist (437 –  3·8)  on 2011/12/14 (Patch 4.3.0) 

<Update> On last week's logs, Heroic Cunning did 9.2% of my damage on H-Morchok and 8% on H-Ultraxion- on Yor'sahj it's been as high as 25% with numerous Yellow/Black/Red phases and a little luck. With the high spellpower scaling, this trinket continues to be the most OP piece of gear in this tier.
hilltopperpete on 2012/05/02 (Patch 4.3.4)

**Comment by Pocketerino** [comment]
Howtobugreport101

**Comment by pelekon** [comment]
I am closing it, report is not valid and way of how its written is poor, hard to read etc + there is no problem with proc of trinket.
