### ISSUE TITLE
[PL] [Achievement] [Guild] The Bastion of Twilight Guild Run

### ISSUE THREAD

**Issue by Pazurek** [Atlantiss/BugTracker#985]
Po zabiciu Czogalla nie zaliczyło gildyjnego achievmenta. Screeny jako dowód:

http://zapodaj.net/9f33ee11bfb07.jpg.html

http://zapodaj.net/27cd4a103efa8.jpg.html

**Comment by Althin** [comment]
Prosze o odnowienie tego tematu. Gildia Wintervale w Sobote 14 Marca 2015 ubila Cho'gall'a na 10man Norm 10/10 ludzie z gildii. Achivmentu nie zaliczylo dla Gildii. Prosze o szybkie naprawienie. Pozdrawiam Althin :)

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/issues/1716
