### ISSUE TITLE
[EN][Quest][Badlands][Third Sample: Implanted Eggs]

### ISSUE THREAD

**Issue by Snake90** [Atlantiss/BugTracker#9851]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

Link : http://www.wowhead.com/quest=27771/third-sample-implanted-eggs

**Description**: It's impossible to take the Nyxondra's eggs. 

**Current behaviour**: Normally, Nyxondra is supposed to be right behind the NPC,  we have to attack it, and ,when it loses enough life, we can take the eggs.

**Expected behaviour**: The dragon isn't there or any of its eggs.

**Steps to reproduce the problem**:

1.  Take the quests [First Sample: Wild Eggs] then [Second Sample: Whelps] from Rhea in Badlands : http://www.wowhead.com/npc=46654/rhea. 
2. Then take the quest [Third Sample: Implanted Eggs] from the same NPC.
3. The quest can't be completed because there is no eggs. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by roirraWedorehT** [comment]
+1

**Comment by Dunno666** [comment]
+1

**Comment by rnel76** [comment]
as of 05/24/2018...still bugged :(

**Comment by deymian4** [comment]
Up.

**Comment by Snake90** [comment]
Why have you close it ? The quest is still bugged.
New bug by the way : the NPC can't give the quest now :/

**Comment by Bildo** [comment]
it is not a bug, this is intended. you cannot take a quest because third sample required quest lifting the veil to be completed which is disabled until all badlands are finished
