### ISSUE TITLE
DTR proc rate

### ISSUE THREAD

**Issue by madsaloise** [Atlantiss/BugTracker#9853]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Dragonwrath Tarecgosa's rest is currently proccing too often for all (relevant) classes. It was nerfed in patch 4.3 as seen here: http://us.battle.net/wow/en/game/patch-notes/4-3-0 
From http://wowwiki.wikia.com/wiki/Patch_5.0.1 we see that there was no changes in existing items from 4.3.4 to 5.0.1(MoP Beta), so no changes to DTR were made. 
Therefore it makes sense to use the 5.0.1 SimulationCraft's proc rates.

**Current behaviour**: The proc rate of DTR is too high. 
The current values we have are (from Jenova, taken from the core):
Mage - 12.5%
Priest - 13.6%
Warlock - 17%
Druid - 11%
Shaman - 17%

**Expected behaviour**: What should happen instead

DTR should proc less with SimulationCraft as the source for the proc rate
From sc_unique_gear in their MoP client:
case DRUID:   chance = 0.08; break;
  case MAGE:    chance = 0.08375; break;
  case PRIEST:  chance = 0.09112; break;
  case SHAMAN:  chance = 0.1139; break;
  case WARLOCK: chance = 0.1139; break;
  default: break;
Further proof/sources to state that these values are approximately the value of retail 4.3:
Mage (8.348%, 10k sample) 
http://web.archive.org/web/20130512024335/http://elitistjerks.com/f75/t110187-cataclysm_mage_simulators_formulators/p27/
Druid (8%) 
https://web.archive.org/web/20120208051315/http://elitistjerks.com/f73/t114017-balance_wrathcalcs/p14/
Warlock (Last 3 pages. Mixed results, 11% being mentioned) http://web.archive.org/web/20120809045323/http://elitistjerks.com/f80/t125554-dragonwrath_tarecgosas_rest_warlock_specific_analysis/p6/
Priest (7-9%, small sample) 
https://www.mmo-champion.com/threads/1028122-Dragonwrath-Tarecgosa-s-Rest-How-bad-is-the-nerf-for-us

**Steps to reproduce the problem**:

1. Check proc rates in core 
2. Realise that they are too high

**Revision**: rev. 5632

**Comment by Psychobird7** [comment]
Thank you for making this.  
Hope the changes happen in the near future.

**Comment by xmesaj2** [comment]
rev 5641
