### ISSUE TITLE
[EN][Warrior] T12 Protection 2-set does double damage

### ISSUE THREAD

**Issue by Katonetwo** [Atlantiss/BugTracker#9866]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The T12 Protection Warrior 2-set bonus, which attaches a DoT to your Shield Slam ability, is doing twice as much damage as it should do.

**Current behaviour**: Shield Slam puts a 4 second long DoT on the target, which ticks twice, each tick doing 20% of the initial Shield Slam's damage - so a total of 40%, rather than the 20% it's supposed to be.
![ss1](https://user-images.githubusercontent.com/32794643/36491068-24a5d0c6-172a-11e8-9ed6-117cb75b775f.jpg)
![ss2](https://user-images.githubusercontent.com/32794643/36491075-282bc9ee-172a-11e8-8786-3302feaee1b5.jpg)
![ss3](https://user-images.githubusercontent.com/32794643/36491082-2bb4219c-172a-11e8-9ec3-76e2fd61cf9f.jpg)

**Expected behaviour**: The ticks should in total do 20% of the initial Shield Slam's damage, 10% each.

**Steps to reproduce the problem**:

1. Equip Protection Warrior T12 2-set
2. Locate hittable object
3. Use Shield Slam on said object
4. Notice how Combust does twice as much as it should

**Revision**: 5637

**Comment by stanq87** [comment]
the way it works now is lice a copy/paste from the mages ignite, and yes, it seems to do to much dmg unless im missing something

**Comment by Piklo** [comment]
should be fixed in [rev5831](https://atlantiss.eu/changelog#rev5831)
