### ISSUE TITLE
[PL] Balans Postaci!

### ISSUE THREAD

**Issue by Swinuub** [Atlantiss/BugTracker#9868]
Description: warlock,mag,hunter,feral,rogue

Steps to reproduce the problem: 
1. warlock ( talent Destruction ) Jego pet za mocno bije 
2. Rogue podczas PVP mocno się leczy ( za dużo ) 
3. Feral mastery ( bleedy ) róznica pomiędzy że ktoś ma o wiele więcej mastery a o wiele mniej prawie nie ma żadnej róznicy za słabe bleedy ma Feral ( Teraz ) 
4x. Hunter podczas pvp jak się wyjdzie z jego pułapki ( lodu ) z Aimeda potrafi śćiągnąć życie z Krytykiem nawet 50-70K
5. Mag Tak samo jest dość silny 
    
Proszę o przetestowanie tego wszytkiego co napisałem,  wszystko testowałem

**Comment by Piklo** [comment]
Dowody, logi, coeffy, testy, cokolwiek? Samo napisanie że "coś jest źle" nikomu nic nie mówi
