### ISSUE TITLE
[EN][NPC][Missing] Rockchewer Whelk

### ISSUE THREAD

**Issue by OvanSan** [Atlantiss/BugTracker#9870]
**Description**: The critt Rockchewer Whelk is missing for achievment
http://www.wowhead.com/npc=48848/rockchewer-whelk#screenshots

**Revision**:  5637

**Comment by tomatosz** [comment]
I can't be sure whether they are exactly at the blizzlike spots, but I can definitely confirm that the Rockchewer Whelk is spawned in multiple places.
