### ISSUE TITLE
[en][Warrior][Talent] Field Dressing

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9871]
**Description**: Field Dressing - Increases all healing received by 6%, and the effectiveness of your self-healing abilities by an additional 20%.

Field Dressing http://cata-shoot.tauri.hu/?spell=84580
Victory Rush http://cata-shoot.tauri.hu/?spell=34428
Enraged Regeneration http://cata-shoot.tauri.hu/?spell=55694
Blood Craze http://cata-shoot.tauri.hu/?spell=16492
Second Wind http://cata-shoot.tauri.hu/?spell=29842

**Current behaviour**: increases all healing on warrior by 6%

**Expected behaviour**: it should increase allhealing by 6% but self healing  by 26%

**Steps to reproduce the problem**:  

be awarrior  
get rage 
use any self healing skill like : victory rush , enrgaged regeneration, Blood Craze or Second Wind
calculate 

**Revision**:  5644

**Comment by Piklo** [comment]
duplicate #9695
