### ISSUE TITLE
[EN][Spell][Warrior] T13 2p set bonus

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9872]
**Description**: no absorbs of any kind after revenge when t13 2p equiped

**Current behaviour**: nothing happens

**Expected behaviour**: after u hit with revenge, 20% of the dmg should be aplied as a shield

set http://cata-shoot.tauri.hu/?itemset=1074
spel http://cata-shoot.tauri.hu/?spell=105908
buff http://cata-shoot.tauri.hu/?spell=105909

set http://www.wowhead.com/item-set=1074/colossal-dragonplate-armor
spel http://www.wowhead.com/spell=105908/item-warrior-t13-protection-2p-bonus-revenge
buff http://www.wowhead.com/spell=105909/shield-of-fury

**Steps to reproduce the problem**: 

1.be warrior 
2. get hit until u can use revenge
3. use revenge
4.se revenge dgm done
5. look for absorbs, or a buff or aura or anything in combatlog

**Revision**:  rev. 5637

**Comment by xmesaj2** [comment]
fixed in rev. 5655

**Comment by stanq87** [comment]
ok now its bugged so that  not only revenge gives the shield, it also works for shieldslam and devastate and some others

**Comment by Vayns** [comment]
Can confirm, any damaging ability is proccing the 2set now.
