### ISSUE TITLE
Cinematic after defeat The Lich King doesn't exist on server

### ISSUE THREAD

**Issue by poleloa** [Atlantiss/BugTracker#9874]
Hello people. From 29.01.2017,those day was sunday in afternoon(6 Pm) I got tittle "The Kingslayer"
but :
After 6 months, I wanted to watch on the fountain, unfortuneably,it's still the same like :That cinematic is not available.
What should I do? Greetings.

**Description**:That cinematic does not work,I do not know why.

**Current behaviour**:When Arthas is dying on Icc ,then communicate says: Cinematic is not available.

**Expected behaviour**: After defeat the Lich King,on fountain click :See fall of Lich King and watch.

https://www.youtube.com/watch?v=qAIrj_Vqdfc 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Frostbreaker** [comment]
Fake news I get it everytime after killing boss. Probably it's problem on your side. Check your WoW files.
