### ISSUE TITLE
[EN][item] armor

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9877]
**Description**: some itmes with zero armor give armor

Guardspike Choker - http://cata-shoot.tauri.hu/?item=77092
Mandible of Beth'tilac - http://cata-shoot.tauri.hu/?item=71406

**Current behaviour**: we get armor

**Expected behaviour**: no armor on item no armor on player

**Steps to reproduce the problem**:

**Revision**: rev. 5637

**Comment by Psychobird7** [comment]
This does not seem to be limited to warriors.   

I was able to reproduce this on a prot paladin by equipping/unequipping Mandible.

**Comment by stanq87** [comment]
yes, but the same choker on dk dosent give armor but it does on warrior, dont know about druids, dont care about paladins

**Comment by mati865** [comment]
I have 0 armor on warrior with only those 2 items equpped on my warrior.
Are you sure about it?

**Comment by stanq87** [comment]
i guess something changed , now i also have 0,  closing
