### ISSUE TITLE
[EN][spell][Warrior] Prot Warrior T13 4p set bonus

### ISSUE THREAD

**Issue by Vayns** [Atlantiss/BugTracker#9900]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The prot warr t13 4set isn't doing anything.

**Current behaviour**: Shield Wall should become a raidwide buff but right now it's not even giving raid members the aura.

**Expected behaviour**: "Your Shield Wall ability now grants 50% of its effect to all party and raid members."

**Steps to reproduce the problem**:

1. Equip the prot warrior 4p while in a group/raid
2. Use Shield Wall 
3. See that nothing is happening

**Revision**: 5667

**Comment by Psychobird7** [comment]
http://www.wowhead.com/spell=105911/item-warrior-t13-protection-4p-bonus-shield-wall#comments:id=1600111
