### ISSUE TITLE
[EN][spell][Death Knight] T13 4p set bonus

### ISSUE THREAD

**Issue by Vayns** [Atlantiss/BugTracker#9901]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: T13 4p isn't doing anything.

**Current behaviour**: Nothing.

**Expected behaviour**: "Your Vampiric Blood ability also affects all party and raid members for 50% of the effect is has on you."

**Steps to reproduce the problem**:

1.  Equip the Blood DK 4 set while in a group / raid.
2.  Use Vampiric Blood.
3.  See nothing happening.

**Revision**: 5667

**Comment by Psychobird7** [comment]
http://www.wowhead.com/spell=105911/item-warrior-t13-protection-4p-bonus-shield-wall#comments:id=1600111

**Comment by Vayns** [comment]
1 minor bug remains after the last fix. The extra hp for the raid / group gets applied except its literally 7 hp instead of 7%.
