### ISSUE TITLE
[EN][Paladin] Retribution 4T13 (Zeal of the Crusader) 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9902]
**Description**: Zeal of the Crusader (ZotC), Retribution's 4T13 currently does not work correctly. 
***ZotC should act as an 18% increase to all damage dealt, in the same way Avenging Wrath does.***

**Current behaviour**: ZotC does not grant the proper 18% increase to abilities.  

**Expected behaviour**: ***ZotC should act as an 18% increase to all damage dealt, in the same way Avenging Wrath does.*** 
~~**To clarify, it is possible that other abilities are also not getting the full bonus. Exorcism and Hammer of Wrath are almost impossible to test in these conditions.** 
This should include the following abilities: Crusader Strike, Divine Storm, Templar's Verdict, Judgements, Exorcism, Hammer of Wrath, Holy Wrath, Consecration, Ancient Fury, as well as all Seals.
It does not include Hand of Light, Melee swings, Censure and Seals of Command. 
It seems to affect Holy Wrath and Judgement correctly.  
Templar's Verdict (and others) however, is not getting the proper damage increase, and neither are Crusader Strike and others. The following testing will use TV numbers.~~

~~**TV expected w 4T13**: Hits: 27244 // Crits: 56123, **Atlantiss**: Hits: 25945 // Crits: 53446 
**TV expected w/o 4T13**: Hits: 22986 // Crits: 47351, **Atlantiss**: Hits: 22983 // Crits: 47344~~ 

~~How to calculate the expected damage. -- for crits, multiply the total by 2.06. 
With 4T13 (12587 AP): ((((12587/14)\*3.3)+3308)\*1.02\*1.03\*1.25\*3.4075\*1.2\*1.18\*0.685205)=27244.35 
Without 4T13 (12469 AP): ((((12469/14)\*3.3)+3308)\*1.02\*1.03\*1.25\*3.4075\*1.2\*0.685205)=22986.09 
Numbers are confirmed by Simcraft and Rawr.~~ 

~~As you can see from these results, without 4T13 equipped, the damage is exactly as expected (3-7 damage difference, which is down to rounding). 
With 4T13 equipped however, TV does not deal its intended/expected damage, in fact it is off by quite a massive amount.~~ 

- See the following:
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/sum/damageDone/?s=5141&e=5343#Dns
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/details/13/?s=5141&e=5343
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=spellID%3D105819+OR+spellID%3D85256+OR+spellID%3D86700+OR+spellID%3D75176

Take the highest TV seen in the log, 124258.

Now for the sake of comparison, I will run a 500k iteration simulation of a BiS ret paladin.
We know exactly how Simcraft models ZotC, and therefore know exactly how it calculates TV's damage, which will be useful in determining the correct calculation method based on this log.
"if ( p -> set_bonus.tier13_4pc_melee() && p -> buffs_zealotry -> check() )
{player_multiplier *= 1.18;}"
The maximum TV damage as calculated by Simcraft (same gear, same procs, same everything) is 126728.

If we were to fully recalculate TV's damage to see the maximum possible damage with ZotC being additive, the result would be 120728. This is much lower than the number seen on the log.

---> ***Zeal of the Crusader had to have been multiplicative on retail***.

- http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=sourceName%3D%22Dns%22

[20:39:26.699] Dns crits Ultraxion 32483

This auto-attack proves that ZotC had to have been coded as an AW-like damage increase.

If ZotC did not increase melee swing damage, the highest possible melee swing on a full Heroic Dragon Soul BiS ret paladin would be 29994.1, using the same buffs as the Paladin on the aforementioned log had.
The paladin on the log crits for 32483.

- The same thing happens with Censure ticks.
[20:39:24.000] Dns Censure Ultraxion 9859
This tick occured just before the Paladin activated AW+Zeal.

[20:39:26.042] Dns Censure Ultraxion 15938
This tick occured right after. The difference between those two ticks (keep in mind, he has the same buffs for both) is far too high to be caused by RNG.

**Steps to reproduce the problem**:

1. Go on PTR (not necessary, but helpful), add the item with ID 57692. 
2. Make two sets of gear, one with 4T13 equipped, one without, and note your AP in both setups. 
3. Do a test run for each set of gear, and note the damage of your abilities. See it will not match the expected values listed under Expected Behaviour. 

**Revision**: 5678 on live (5680 on PTR?)

**Comment by 1Andas** [comment]
Bump.

**Comment by Psychobird7** [comment]
Bump. This issue still exists.

**Comment by Psychobird7** [comment]
Bump. Found direct evidence.     

Zeal of the Crusader is meant to act *exactly* like Avenging Wrath, except it should not affect Censure and melee swings. 

See the following: 
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/sum/damageDone/?s=5141&e=5343#Dns 
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/details/13/?s=5141&e=5343 
http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=spellID%3D105819+OR+spellID%3D85256+OR+spellID%3D86700+OR+spellID%3D75176  

Take the highest TV seen in the log, at 124258. 

Now for the sake of comparison, I will run a 500k iteration simulation of a BiS ret paladin. 
We know exactly how Simcraft models ZotC, and therefore know exactly how it calculates TV's damage, which will be useful in determining the correct calculation method based on this log. 
"if ( p -> set_bonus.tier13_4pc_melee() && p -> buffs_zealotry -> check() )
    {player_multiplier *= 1.18;}" 
The maximum TV damage as calculated by Simcraft (same gear, same procs, same *everything*) is 126728. 

If we were to fully recalculate TV's damage to see the maximum possible damage with ZotC being *additive*, the result would be 120728. This is much lower than the number seen on the log. 

---> ***Zeal of the Crusader had to have been multiplicative on retail.***

**Comment by Psychobird7** [comment]
Bump. 

Zeal of the Crusader was coded as an 18% damage increase on retail, the same way Avenging Wrath was a 20% damage increase. 

http://www.worldoflogs.com/reports/rt-xf8jxdn7bd03w38d/xe/?s=5141&e=5343&x=sourceName%3D%22Dns%22 

[20:39:26.699] Dns crits Ultraxion 32483 

This auto-attack *proves* that ZotC **had** to have been coded as an AW-like damage increase. 

If ZotC did not increase melee swing damage, the highest possible melee swing on a full Heroic Dragon Soul BiS ret paladin would be 29994.1, using the same buffs as the Paladin on the aforementioned log had. 
The paladin on the log crits for 32483.
