### ISSUE TITLE
[EN][Dragon Soul][Ultraxion] 10man aspect buff spawn timers

### ISSUE THREAD

**Issue by Bislibur** [Atlantiss/BugTracker#9903]
**Description**: 

These buffs don't spawn at the correct times:

http://www.wowhead.com/spell=105900/essence-of-dreams
http://www.wowhead.com/spell=105896/gift-of-life
http://www.wowhead.com/spell=105903/source-of-magic

I will try to provide more accurate information, read 6.2. for a rough estimate:

https://www.icy-veins.com/wow/ultraxion-strategy-guide-normal-heroic

**Current behaviour**: 

The first buff spawns way into the fight.

**Expected behaviour**: 

Red buff should spawn around 1:30 into the fight,
green buff should spawn around 2:30 into the fight,
blue buff should spawn around 3:30 into the fight.

**Steps to reproduce the problem**:

1. Fight Ultraxion on 10man difficulty.
2. ???
3. Profit.

**Revision**: 5678

**Comment by Psychobird7** [comment]
This issue also exists for 25N.

**Comment by Bislibur** [comment]
This issue has been resolved in 10man so I will close this ticket for now.
