### ISSUE TITLE
[EN][Hagara the Stormbinder][Dragon Soul] Hagara the Stormbinder timers 

### ISSUE THREAD

**Issue by PolpoVolante** [Atlantiss/BugTracker#9907]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: 
Hagara's normal phases last 15 seconds less than they should be doing.

**Current behaviour**: 
At the moment from a lightning storm phase end to the next frozen tempest cast (finished cast)
Roughly 50 seconds pass.

The same thing happens from frozen tempest phase end to the next water shield cast (finished cast)

Tested in both 10 men and 25 men normal mode.

https://imgur.com/a/SXyIZ 

Here you can see screnshots from my recording of this week this was 25 men.
You can also see that on the first screenshot dbm has a timer of 1.01 for the next lightning storm.
In the second screenshot lightning phase starts at 14.2 seconds before the timer ends.
If needed for clarity i can send other screenshots from 10 men aswell.

**Expected behaviour**: 
Each phase should last roughly 65 seconds

https://youtu.be/hFoHMBoWGkA -  This is one of the videos I checked the timers for.
0.46 into the video the boss finishes the cast of water shield and is immune to damage.
1.23 the lightning phase ends and water shield dissipates thus starting the "damage phase"
2.30 boss finishes to cast frozen tempest and becomes immune to damage.

You can also see that the phase starts when the dbm count reaches 0 also with dbm voice countdown.

https://youtu.be/YeFkfT0zT_k - Another video example this time 10 men.
3.40 frozen tempest ends and you can dps the boss
at 4.44 water shield is up and boss becomes immune.

You can also see his timers.

**Steps to reproduce the problem**:

1.  
2. 
3. 

**Revision**: 5683 but before aswell.

**Comment by PolpoVolante** [comment]
Other examples.
https://youtu.be/_WSE0g876xw     1.26 frost phase ends / 2.30 water shield up.

https://youtu.be/7PmInv7vN4I       1.00 lightning phase ends / 2.07 forzen tempest up


Please send legit reasoning and not "i read on this site it does x".

**Comment by Aival94** [comment]
Please next time do a more proper testing and explain the reason of the bug. 

The bug is that the timer start when you go out of Ice or Lighting phase while the Normal Phase is supposed to start after the boss lose [Feedback](http://www.wowhead.com/spell=108934/feedback)(during feedback is not supposed to be normal phase but burst phase for the group as boss do nothing)

The guide is properly telling what is supposed to happen on encounter and the encounter timers have not being updated but only damage of spells. I gave the link as proof of what you said as well.

Next time try to not be aggresive against someone else comment.

**Comment by PolpoVolante** [comment]
Sorry I have misunderstood the comment and even then I shouldn't have answered like this.

On that you are probably right about the timer that starts after feedback.

Thanks for the feedback.

**Comment by pelekon** [comment]
fixed in rev 5862
