### ISSUE TITLE
[EN][Spell][Priest] Shadow T13 2p 

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#9909]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Bonus from 2 parts of T13 does not provide damage reduction from our own SW:D 

**Current behaviour**: Bonus from 2 parts of T13 does not provide damage reduction from our own SW:D 

**Expected behaviour**: Bonus from 2 parts of T13 should provide 95% damage reduction from our own SW:D

**Steps to reproduce the problem**:

1. Cast SW:D on dummy with following effect: 4998 damage on target - 4248 damage transferred back
2. Equip T13 2p
3. Cast SW:D on dummy with following effect: 8233 damage on target - 6998 damage transferred back

In both cases it is only reduced by 15% (Shadowform bonus)

**Revision**: 5683

**Comment by lostmyusername** [comment]
just went to a dummy: sw:d hit around 34k, 7.1k dmg transferred back. sth seems to be off there. dont have the time for proper testing but it seems, that if you use that sw:d BEFORE the 25%-phase, the 2pt13 doesnt work at all, as you described it, but in that 25%-phase there definitly IS a dmg-reduction (also experienced that in raid on encounters like zonozz or hagara), eventho this reduction might not be 95% as the setbonus should be.

**Comment by Dziara** [comment]
Below 25% you suffered damage equals to SW:D damage above 25% (without 3x multiplier bonus). It was probably resisted and mitigated by shadowform too. But anyway your comment has nothing to do with T13 bonus

**Comment by xmesaj2** [comment]
fix in r5748

**Comment by Dziara** [comment]
Still not working :( Just tested on dummy

**Comment by xmesaj2** [comment]
rev. 5751 corrected my fail
