### ISSUE TITLE
[EN][Dungeon][NPC] Auchenai Crypts skeletons

### ISSUE THREAD

**Issue by demon034** [Atlantiss/BugTracker#9915]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Reanimated Bones, near the end boss, are the same level on normal and heroic

**Current behaviour**: Their level is too high, they are around 71-72

**Expected behaviour**: They should be around level 63 on normal

http://www.wowhead.com/npc=18700/reanimated-bones#abilities:mode=normal
Since blizzes revamp of old content, I can't show the TBC max lvl of the mob, but it should start at 63

**Steps to reproduce the problem**:

1. Finger in bum
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Navedonar** [comment]
They should be 66-67 lvl on normal
Fix https://community.atlantiss.eu/index.php?/topic/18363-dungeonnpc-auchenai-crypts-skeletons/

**Comment by Piklo** [comment]
should be fixed in [rev. 5730](https://atlantiss.eu/changelog#rev5730)
