### ISSUE TITLE
[PL][Rated Battleground][PvP][High priority] Que bug

### ISSUE THREAD

**Issue by Arcadia713** [Atlantiss/BugTracker#992]
Zebraliśmy Raid 15 osób w celu zapisania się na Rated BG - niestety po kliknięciu w przycisk "Join battle" nic się nie dzieje, nie ma komunikatu o zapisaniu się, nie ma ikony BG koło mapy - po prostu nie reaguje. 
Upewniliśmy się, że nikt w raidzie nie jest zapisany na RHC, BG, Arenę (każdy robił relog) więc to wykluczamy.
Zmiana raidu 10/25 też nie pomaga.

**Comment by HaydenGT** [comment]
dalej ne funguje

**Comment by deadlycalm** [comment]
bump
