### ISSUE TITLE
[EN][spell][Death Knight] T13 4p set bonus

### ISSUE THREAD

**Issue by H4bits** [Atlantiss/BugTracker#9922]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When using [Vampiric Blood](https://web.archive.org/web/20120702201820/http://www.wowhead.com:80/spell=55233) together with [4p T13](http://www.wowhead.com/spell=105587/item-death-knight-t13-blood-4p-bonus) and [Glyph of Vampiric Blood](https://web.archive.org/web/20120622045643/http://www.wowhead.com/item=43554#created-by-spell) the raid gets increased healing taken  _and_ increased health. 

**Current behaviour**: When used with Glyph of Vampiric Blood the raid / party members get 20% increased healing taken _and_ 12% increased health (the DK doesn't get extra health)

**Expected behaviour**: When used with Glyph of Vampiric Blood the raid / party members get 20% increased healing taken (and no extra health, just like the DK)

_How it should work_
**What it does for the DK**
Unglyphed: Increase health with 15% and healing taken with 25%
Glyphed: Increase healing taken with 40%
**What it does for the raid**
Unglyphed: Increase health with 7% and healing taken with 12%
Glyphed: Increase healing taken with 20%

The percent by which the glyph should increase the healing taken is correct. (tested on ptr)
Glyphed: 40% for the DK and 20% for the party / raid.

So everything works now except that the raid gets increased health when using the Glyph.
Without using the Glyph there are no problems at all.

**Steps to reproduce the problem**:

1. Equip 4p of the T13 Death Knight tank set.
2. Use Vampiric Blood with Glyph of Vampiric Blood while in a raid / party.
3. See how the raid members get both increased healing taken _and_ increased health.

**Revision**: 5700

**Comment by pelekon** [comment]
fixed in rev 5701
