### ISSUE TITLE
[EN][Talent][Spell][Mage] Ignite

### ISSUE THREAD

**Issue by Pocketerino** [Atlantiss/BugTracker#9925]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hello boys and goofs, if you try to spread your ignite to other targets it won't do any daMage. monkaS i know.

**Current behaviour**: If you try to spread your Ignite with Impact then the Ignite that was spread shows up as a debuff on the target that it was spread onto but it doesnt actually do any daMage.

Here's a video, https://www.youtube.com/watch?v=P8AUaJfgqIs , French 101 from what i hear.

**Expected behaviour**: If you try to spread your Ignite with Impact then the Ignite that was spread shows up as a debuff on the target that it was spread onto and it does that sweet daMage.

**Steps to reproduce the problem**:

1. Have Impact up. And have some targets within 12 yards of your current target,
2. Do a crit on your current target.
3. Use impact to spread your Ignite,
4. Realize that the Ignite you spread did no daMage.
5. It's mandatory that you cry after.

**Revision**: 5700.

**Comment by stanq87** [comment]
![bez tytulu](https://user-images.githubusercontent.com/16665131/37559881-fa555f50-2a2d-11e8-9f49-55d6505b2a72.jpg)
A- ignite spread with fireblast + spell aura apllied
B- mising dmg from ignite , dmg only on orginal target

**Comment by firemagegodx** [comment]
Wonder who that mage is!?! Looks like a rogue main to me /shrug
In all seriousness, even if you spread a 40k Ignite and crit >2s remaining, not even the damage is applied, instead it just ticks for whatever damage the 2nd application did. Here's an example:
1. Ignite spread, 40k
2. Spell X hit all of them, should increase ignite of them since it crit on >2s remaining on the DoT, ATS™
3. Expected damage is 40k+Y
4. Actual damage done is only Y

**Comment by Pocketerino** [comment]
@firemagegodx So, that comment is so poorly worded its actually sad, I believe you're talking about the issue where if you crit with under 2 secs left on your ignite your ignite semi-dies, if that's the case, then to correct your nr. 4 - Actual damage isn't "Y" _(btw, when you decide to refer to something with Y, X, Z, R, them, whatever the shit letter or word, make sure you note what the hell does it mean or at least make sure its extremely obvious)_ It's a random low value whose origin I haven't made the effort to discover yet, its not a new crit on the targets ignite value. I don't see how having multiple targets changes anything here, yet you mention "them" (whatever "them" means). FYI, >2 means higher than two, <2 means lower than two. If my assumption is wrong then please reword your comment, actually, no matter if I'm right or wrong reword it so it's understandable, if you can't be arsed to do that please delete it because in this form it doesn't add anything to the report.

**Comment by Fearyourself** [comment]
Why is this marked with high priority?

**Comment by Pocketerino** [comment]
Bumperino.

**Comment by stanq87** [comment]
bump

**Comment by Jenovas** [comment]
Fixed
