### ISSUE TITLE
[EN][Raid][Dragon Soul][Warmaster Blackhorn]

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9926]
**Description**:
u can put debufs on goriona ( the big drake) before the combat starts, saw a mage do this and his  living bomb made blackhorne start using his skills in the 1phase  kiling the raid, it buggged the instance bloking us from entering ( encounter in progress)

**Current behaviour**: 

```
3/17 18:23:32.438  SPELL_CAST_SUCCESS,0xF150DDCD0000174F,"Goriona",0xa48,0x0,0xF130DF66000016A6,"Engine Stalker",0xa18,0x0,107583,"Twilight Blast",0x1
3/17 18:23:33.221  SPELL_CAST_SUCCESS,0x000000000016F1A9,"Schröder",0x512,0x0,0xF150DDCD0000174F,"Goriona",0xa48,0x0,44457,"Living Bomb",0x4
```

**Expected behaviour**: 
who knows just postion so u know why sometimes the raid locks up  , maybe do somthing it wont

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by meowmewo** [comment]
Are you saying you shouldnt be able to damage her until she comes close to the ship on the next phase? Cuz you should...

**Comment by stanq87** [comment]
but when u do it how the mage did it blackhorne start using his shout in p1, and u get " euconter in progress" if u wipe
