### ISSUE TITLE
[PL][Cataclysm][Quest][Uldum] Smoke in their Eyes

### ISSUE THREAD

**Issue by bioly1928** [Atlantiss/BugTracker#9929]
Description: http://www.wowhead.com/quest=27923/smoke-in-their-eyes

https://www.youtube.com/watch?v=dS-AVKxNllQ

Quest polegający na podpaleniu 5 bali ze słomą przy pomocy pochodni, po użyciu pochodni nic się nie dzieje i nie zalicza podpalonych bali, przez co quest staje się niewykonalny. 

Current behaviour: Po podpaleniu balu nic się nie dzieje, nie zalicza progresu questa.

Expected behaviour: Po podpaleniu balu powinno naliczac spalone bale

Steps to reproduce the problem:
1. Pobranie questa od NPC
2. Wyruszenie w poszukiwaniu bali do podpalenia, reszta wyjasniona powyzej

Revision: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Piklo** [comment]
dodaj [issue_template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by bijtankga** [comment]
jesli chodzi o scislosc to uzycie pochodni cos robi: PODPALA PODLOGE
siano po wypaleniu sie ognia (ciezko stwierdzic czy siano sie pali czy tylko ziemia) nie znika
i nie zalicza spalenia

**Comment by pelekon** [comment]
fixed in rev 5705
