### ISSUE TITLE
[EN] [Spell] [Priest] Empowered Shadow

### ISSUE THREAD

**Issue by Dziara** [Atlantiss/BugTracker#993]
Empowered Shadow http://cata.openwow.com/spell=95799
Mind Blast http://cata.openwow.com/spell=8092
Mind Spike http://cata.openwow.com/spell=73510
Shadow Orb http://cata.openwow.com/spell=77487

When we miss with Mind Blast or Mind Spike while we have at least 1 Shadow Orb, Orbs don't get consumed and we don't get ES buff. It shouldn't work like that. Orbs get consumed and we get ES buff when we CAST MB/MS not when we HIT with that spells

http://howtopriest.com/viewtopic.php?f=50&t=408
"Even if you miss on MB you still get the ES buff.

One thing people say as a reason to not go under hit cap is that ES might fall off. This is simply not true since you get the ES buff from casting MB not from MB doing damage."

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.

**Comment by armano2** [comment]
##4061
