### ISSUE TITLE
[EN][STATISTICS][MAGE]

### ISSUE THREAD

**Issue by pytek12125** [Atlantiss/BugTracker#9930]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Zauważyłem kilka interesujących zmian w magu. Po pierwsze uważam, że przed osłabieniem legendarnego staffa mój mag zadawał większe obrażenia  z zaklęcia. Moje statystyki nie zmieniły się znacząco, ale to wygląda tak jakby Mastery nie działało za dobrze i kilku magów również potwiedziło podobny problem. Podobnie jest z ignite ale ten problem już został zgłoszony, więc nie będę o nim pisał.  Kolejnym problemem jest Haste i odczuwam tu nieznacznie wolniejsze casty niż wcześniej (ta sama wartość haste daje mi wolniejszy cast niż wczśniej), co oczywiście wydaje się śmieszne i niepoważne, jednak jako wieloletni gracz takie małe różnice są dla mnie widoczne. Być może rzeczy, o których pisze działają prawidłowo i są to tylko moje prywatne urojenia, ale moją prośbą jest sprawdzenie, czy faktycznie to wszystko działa poprawnie. 

Current behaviour: Mniejsze obrażenia/prawdopodobnie bonusy do dmg źle naliczone z mastery oraz możliwie wolniejsze casty u maga arcane.

Expected behaviour: Sprawdzenie jedynie czy statystyki naliczane są poprawnie.

Steps to reproduce the problem:

               1. Sprawdzić czy statystyki Mastery i Haste są naliczane prawidłowo.
 
Z góry dziękuję za odpowiedź.

**Comment by stanq87** [comment]
zapomniales dodac ze przez tydzien mag napierdalal critami jak glupi i bez problemu mozna bylo miec 150k ignite,  co do haste to latwo to sprawdzic

**Comment by Piklo** [comment]
z tego reporta nic nie wynika, cos jest "zbugowane", ale w sumie nie wiesz co i czy na pewno jest

**Comment by pytek12125** [comment]
Nie wiem czy u Was była podobna zmiana, ale u mnie z fazy burst gdzie robiłem ok. 70-90 a nawet czasami 100k i 40k+ dps na koniec walki do poziomiu jakiś 50-60k w burst i ok 35k na koniec walki. A nic nie zmieniałem jeśli chodzi o itemy. Szukam tylko przyczyny, bo nie wierze, że to obniżony delikatnie % na staffie mógłby to spowodować.

**Comment by pelekon** [comment]
Zamykam, ten report nic nie wnosi, jeśli będziesz mieć konkretne dowody, poparte wyliczeniami, ss-ami itd to wtedy otwórz kolejny. A jak czegoś nie jesteś pewien to masz wachlarz doświadczonych graczy jak Pocketmage z WSI, Polpoz z Madness, Frostbreaker z Immortal Legion, oni zapewne z chęcią odpowiedzą na pytania odnoście maga, a jednocześnie żaden z nich nic mi nie pisał jakby występował bug o którym piszesz.
