### ISSUE TITLE
[en][item][spell][mechanic] Legendary staff and drain soul

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9934]
Description: Drain soul interaction with legendary staff is currently bugged. All channeled spells should be duplicated by additional tick of channeling spell. On ats you get additional damage as terecgosa wrath.

Current behaviour: drain soul replicated ticks are considered as arcane damage.

Expected behaviour: All channeled spells interaction with legendary staff is additional "wave" of channeled spell (like additional arcane missle)

"Channeled spells like [Arcane Missiles] will gain an additional tick when a duplication is triggered."

https://wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest
http://www.wowhead.com/spell=198590/drain-soul

Steps to reproduce the problem:

equip staff
go dummy
cast drain soul
Revision: 5700

**Comment by pelekon** [comment]
fixed in rev 5891
