### ISSUE TITLE
[en][talent][warlock] soul siphon and drain life heal

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#9936]
http://www.wowhead.com/spell=234153/drain-life

**Description**: soul siphon talent should increase damage of drain life and drain soul on targets with affliction warlock effects. It should also increase healing done by drain life by same ammount.

**Current behaviour**: Drain life healing is not increased by soul siphon talent
**Expected behaviour**: health drain should be increased by up to 18%

https://www.mmo-champion.com/threads/766897-Why-healing-will-be-OK-for-affliction-85
https://eu.battle.net/forums/en/wow/topic/1820952486

"Percent[%] based Heals - With no ARP, high armor, base Soul Link, Demon Armor, and huge health pools % based heals actually become very powerful. At lvl 80 PTR damage is out of control but that is subject for balancing. With hp at the level of 85k + and pvp dps being at around 5-7k level % based heals even if its just 2% from drain life become powerful tool and other classes need to make sure to silence/schoollock us to win. 2% of 85,000 is 1700 heal. Drain Life has 3 ticks, With haste we can have it around 2,5 sec level thus we reach 2040 HPS level. With Eradication up and soulburn effect we can reach under 1 seconds casts giving us quick health and incredible damage. With Death's Embrace when we get low we heal 5% instead of 2% meaning that 1700 hp per tick becomes 4250 hp per ticks and with 2,5 sec channel time we reach 5100 HPS.Now tell me this is low? You still think so ? Ok, throw in Demon armor or Improved Demon Armor increasing our heals by 20/30%. In 30% scenario our 1700 becomes 2210 per tick and 4250 becomes 5525 heal. Couple that with Soul Siphon and Haunt heal and potential Healthstoneand you have one fking touh warlock to take out. Just so you know, 5525 ticks with 2,5 channel are 6630 HPS "

"Soul Burn: Healthstone gives you that extra health that will give healers a bit extra time, and it also buffs the amount of health gained from % based healing like Drain Life and Soul Siphon, so if u got your dots up, available healthstone, and in a position to use Drain Life, SB:HS can cut it, althought 8 sec feels quite short."

**Steps to reproduce the problem**:

1. talent into soul siphon
2. cast dots on target
3. check drain life heal ammount
4. let dots fade
5. cast drain life and check heal ammount - its the same.

**Revision**: 5700

**Comment by kadi2** [comment]
https://github.com/Atlantiss/BugTracker/issues/6924

If you check any clip, you will see that it shouldn't increase heals at all. You don't have to do any calculations, just see that Soul Siphon and Siphon Life always heals for 2% of your maximum health pool.
