### ISSUE TITLE
[EN][Raid][Dragon Soul][Ultraxion][Rogue][Killing Spree]

### ISSUE THREAD

**Issue by mcfreddas** [Atlantiss/BugTracker#9937]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Rouge talent http://www.wowhead.com/spell=51690/killing-spree is making you leave the platform and get stuck in unknown area. Also http://www.wowhead.com/spell=109075/fading-light seems to only come in 5 sec verison and in live i pretty sure it was a 5-10 second interval for the debuff. (might have missed that is dose work as it did)

**Current behaviour**: You get teleported away from the fight unable to continue

**Expected behaviour**: Stay infront of the boss able to use the spell as normal

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5701

**Comment by Arakis14** [comment]
Also using KS on Warmaster can be lethal. Forgot to make a screenshot but I ended up on one of the cannons half way down the ship :)

**Comment by mati865** [comment]
Kitty charge also drops you down.

**Comment by pelekon** [comment]
fixed in rev 5712

**Comment by wtRCH** [comment]
@Arakis14 @mati865 Your reports (more comments) don't get fixed in the rev. 5712. Please make saparate Issue (with good explaination), so we can fix it as soon as possible.

**Comment by mcfreddas** [comment]
Also you get turned away from the boss so your ¨normal¨ attacks dosen't hit the boss while you use Killing Spree. This would be a real shame in fights like spine when u have a small window of dps on key tendon.

**Comment by Piklo** [comment]
Open new posts
