### ISSUE TITLE
[EN][Spell][Mage] Mage t13 2p set bonus without 4p

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9938]
**Description**:
stacks of stolen time get consumed after combustion even if u only have 2set pieces . the 4p mechanic should work only if u have 4pieces 

**Current behaviour**:
after using combustion u loose all stacks of stolen time even when  u have 2 pieces

**Expected behaviour**:
the mages t13 4p should be active when a mage has 4pieces  of t13 not less,

http://www.wowhead.com/item-set=1062/time-lords-regalia#comments
http://cata-shoot.tauri.hu/?itemset=1062
https://www.youtube.com/watch?v=i8Aa24EyGYY

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Revision**: Current server version

**Comment by Pocketerino** [comment]
What are you even talking about, have you even read the 2p text?
