### ISSUE TITLE
[EN][Talent][Spell][Mage] impact + living bomb ticks

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9940]
**Description**:
copied living bomb's ticks are out of sync with the orginal living tics because of that the copied

PS. the same happnes to the dot portion of pyroblast

**Current behaviour**:
the remaning time on the living bomb is copied on  the spred ones but the tics are like on a dres living bomb rather like on the original

![bez tytulu](https://user-images.githubusercontent.com/16665131/37655176-d8d3d3ac-2c44-11e8-9c04-8ab4ec198e0e.jpg)

red- orginal lb aplied
green - spread point
dark blue - tics of original lb
pink - spread lb apllied
light blue - copied lb tics
greay - where the tics of the copied lb should happen  

**Expected behaviour**:
spread/copied living bombs should  be exact copies of the  orginal one including tics 

https://wow.gamepedia.com/Living_Bomb
http://wowwiki.wikia.com/wiki/Living_Bomb
http://cata-shoot.tauri.hu/?spell=44461
http://www.wowhead.com/spell=44457/living-bomb

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version

**Comment by Jenovas** [comment]
Fixed
