### ISSUE TITLE
[EN][Talent][Warrior]Improved Hamstring now broken, applyed with hamstring

### ISSUE THREAD

**Issue by ngtmp** [Atlantiss/BugTracker#9943]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: The talent "improved hamstring" was supposed to immobilize the target after reapplying skill "hamstring" on that target. However, after the last hotfix the skill "hamstring" immobilizes the target after the first apply.

**Expected behaviour**: After reapplying Hamstring it should immobilize target (http://wowwiki.wikia.com/wiki/Improved_Hamstring)

**Steps to reproduce the problem**:

1. Use Hamstring on the target
2. Reapply Hamstring on the same target

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by wtRCH** [comment]
@ngtmp Please describe a problem a bit more

**Comment by wtRCH** [comment]
http://wowwiki.wikia.com/wiki/Improved_Hamstring

**Comment by ngtmp** [comment]
The talent "improved hamstring" was supposed to immobilize the target after reapplying skill "hamstring" on that target. However, after the last hotfix the skill "hamstring" immobilizes the target after the first apply.

**Comment by wtRCH** [comment]
Fixed in rev. 5716
