### ISSUE TITLE
[EN][Talent][Warrior] Taste for Blood doesn't work properly

### ISSUE THREAD

**Issue by Smokens** [Atlantiss/BugTracker#9950]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The talent is supposed to refresh after 5 seconds (6 seconds if it's single target because rend only ticks once every 3 seconds so that means its should refresh when there are 3 seconds left on the buff)

**Current behaviour**: It doesn't, it refreshes after 9 seconds or when you reapply it with mortal strike/reapply it manually after 5 seconds, so it only refreshes if the taste for blood buff runs out or when you reapply rend 

**Expected behaviour**: It should refresh after 5 seconds or 6 if it's single target (when there are 3 seconds left on the buff) 
proof: https://www.youtube.com/watch?v=wRiE5GsHG8g at 4:37 he actually uses an execute but the taste for blood buff refreshes itself anyway at 3 seconds left, and again at 4:50 while he was bladestorming

**Steps to reproduce the problem**:

1. Apply rend on the target
2. Wait for it to refresh
3. Refreshes after 9 seconds

**Revision**: 5707

**Comment by Psychobird7** [comment]
Sources, proof of behaviour, anything?

**Comment by Smokens** [comment]
didn't find any wowhead links sadly since the talent doesn't exist anymore/was reworked

**Comment by Smokens** [comment]
Added a video proof of expected behaviour

**Comment by stanq87** [comment]
http://cata-shoot.tauri.hu/?spell=56636
https://wow.gamepedia.com/Taste_for_Blood
http://www.wowhead.com/spell=69634/taste-of-blood

**Comment by LemonPotatoes** [comment]
any progress on this ?

**Comment by Elannreportujerzeczy** [comment]
bump

**Comment by firemagegodx** [comment]
Well speaking logically, since it ticks every 3s and Taste for Blood procs at the pull, it should proc at 6s again, since 0-3-6. It can't proc at 3s because of the 5s ICD of the talent, so it should proc at 6s, one second after the ICD is off.

https://www.youtube.com/watch?v=yDwhUQwt5u0&feature=youtu.be

Here is a video showing how it's proccing on ATS
Notice how it's taking it a lot longer to proc it than intended.

**Comment by stanq87** [comment]
oww but we know that, but it does that only when there are several rends on multiple targets, however on 1 target it does that 4 sec AFTEr cd look that well crafted idiot proof image i uploaded

**Comment by LemonPotatoes** [comment]
This truly is annoying... Clicking the OP button but it never comes... feelsbadman

**Comment by ragehoof72343** [comment]
Any progress :")

**Comment by bucranio** [comment]
https://www.youtube.com/watch?v=efpknOVIxVc&feature=youtu.be u can see here what is he talking about

**Comment by Piklo** [comment]
should be fixed in [rev5813](https://atlantiss.eu/changelog#rev5813)
