### ISSUE TITLE
[EN][Item]Cobalt Shoulders

### ISSUE THREAD

**Issue by suthorian** [Atlantiss/BugTracker#9973]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The item http://www.wowhead.com/item=39083/cobalt-shoulders has the wrong display value it currently looks like http://www.wowhead.com/item=40950/spiked-cobalt-shoulders

**Current behaviour**: wrong Display ID 49675 (current)

**Expected behaviour**: collor pallet should be Blue instead of Brown display ID should be: 48513

**Steps to reproduce the problem**: craft a http://www.wowhead.com/spell=52572/cobalt-shoulders

**Revision**: Acore Rev. 5718

**Comment by wtRCH** [comment]
This is correct, this item was yellow due to some bug on cata back then and fixed later back to blue in MoP.
