### ISSUE TITLE
[EN][Talent][Warrior] - Juggernaut

### ISSUE THREAD

**Issue by henkka90** [Atlantiss/BugTracker#9978]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description** Juggernaut talent reduces the cooldown of your charge by 2 seconds and charge and intercept abilitys share a cooldown, however charge and intercept doesn't share the same cooldown.

**Current behaviour**: When you use charge, while you've got the Juggernaut talent, you can also use intercept ability on a seperate cooldown.

**Expected behaviour**: Intercept's cooldown should adjust to the charge's cooldown. Right now, intercept share cooldown of 15 seconds, instead of the 13 seconds, which was reduced by 2 seconds off the 15 seconds cooldown with the Juggernaut talent, also the glyph which reduces the cooldown of charge( Rapid Charge) makes this issue even more an issue.

Addional Information.

http://wowwiki.wikia.com/wiki/Juggernaut_(warrior_talent)

**Steps to reproduce the problem**:

1. Use charge on the target
2. wait 13 seconds and use charge again.
3. now you can use intercept after the last charge, and you can repeat the proccess.

**Revision**: 5722

**Comment by Piklo** [comment]
charge talent / glyph cd reduction shouldn't affect intercept
https://youtu.be/T0iEzpWLgOE?t=1m56s
however bug should be fixed in [rev5815](https://atlantiss.eu/changelog#rev5815)
