### ISSUE TITLE
[EN][Companion Pet][Achievement][Guild] Guild Page (Horde)

### ISSUE THREAD

**Issue by Pieczyyea** [Atlantiss/BugTracker#9979]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: My guild got [Alliance Slayer] (http://www.wowhead.com/achievement=5179/alliance-slayer). This guild achievement allows you to buy [Guild Page] (http://www.wowhead.com/item=65362/guild-page) pet from guild vendor, if you have at least Honored reputation. Sadly, vendor is not offering this pet.
Screenshots:
Achievement: http://s1304.photobucket.com/user/dementor_111/media/WoWScrnShot_040418_124654_zps92osjux7.jpg.html
Guild Vendor:
http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_040318_222055_zps3txexky6.jpg
http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_040318_222056_zpsjviha6xr.jpg
http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_040318_222057_zpsrbihxufi.jpg
http://i1304.photobucket.com/albums/s530/dementor_111/WoWScrnShot_040318_222058_zpsi4rfnjcy.jpg
**Current behaviour**: You can't buy Guild Page pet from Guild Vendor, no matter, what level of reputation with guild you have.

**Expected behaviour**: You should be able to buy Guild Page from Guild Vendor after unlocking guild achievement and reaching at least Honored reputation.

**Steps to reproduce the problem**:

1. Unlock [Alliance Slayer] achievement in your Horde Guild.
2. Reach Honored reputation with Guild.
3. Try to buy a pet from Guild Vendor.

**Revision**: 5722

**Comment by Navedonar** [comment]
.

**Comment by TranceAccount** [comment]
Should be fixed in rev. 5827

**Comment by Pieczyyea** [comment]
No, still not possible to buy

**Comment by TranceAccount** [comment]
Then how can there be a more recent report that states that you can summon him: #10141
Which vendor are you at?

**Comment by Pieczyyea** [comment]
I'm using Orgrimmar vendor

**Comment by TranceAccount** [comment]
I see an error in my commit now. I forgot to add the items to Goram.

**Comment by TranceAccount** [comment]
It should be fixed on next server update.
