### ISSUE TITLE
[EN][Item][Drop]Design: Rhinestone Sunglasses

### ISSUE THREAD

**Issue by Flinvoltx** [Atlantiss/BugTracker#9981]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Never seen this on a server, i guess the drop is missing.

**Current behaviour**: Never seen this on a server, i guess the drop is missing.

**Expected behaviour**: This pattern is a worlddrop and can drop from every mob in Cata

http://www.wowhead.com/item=71965/design-rhinestone-sunglasses#comments

"I spoke with a GM a few minutes ago and he told me this:
- This pattern is a worlddrop and can drop from every mob in Cata and MoP.
- The Chance in Cata is a bit higher than in MOP, maybe because it was implemented in Patch 4.3.
- The Chance is aprox. 0,01% and can only drop for Jewelcrafters.
- It can drop realy from every monster."

"Can confirm that the pattern is ingame (patch 4.3.3)
A fellow guildy showed/linked it to me, he told me it dropped from Xariona in Deepholm."

**Steps to reproduce the problem**:

1. Check the server data

**Revision**: 5722

**Comment by wtRCH** [comment]
This pattern should drop only from World Bosses such as: Garr, Mobius, Akma'hat, Xariona, Poseidus and Julak-Doom
