### ISSUE TITLE
[EN][Quest][Stormwind] Twilight Shores

### ISSUE THREAD

**Issue by kingochan** [Atlantiss/BugTracker#9983]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
After completing the previous quests, the NPC Fargo Flintlocker doesn't show up in Stormwind. The affected character's name is "Elizebath".

**Current behaviour**: What happens
No actions required or can be made. The exp bar disappeared. No way to get leveled up in game. Now my character stays at lvl 84.

**Expected behaviour**: What should happen instead
The NPC should be at the harbor so I can continue with the quest series.

**Steps to reproduce the problem**:

1. Complete the quest Hero's Call: Twilight Highlands!
2. Take the quest Twilight Shores.
3. No NPC shows up. (Not all players have this issue)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5722

**Comment by Piklo** [comment]
should be fixed in rev. 5916
