### ISSUE TITLE
[EN] [PVP] [System] Conquest point calculation.

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9988]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: You're not receiving enough Conquest points (=CP) equal to your raiting, 

**Current behaviour**: The formular seems to be off, It stops at some points [around 2,2k] and starts too low.

**Expected behaviour**: AJ still has the 4.3.4 CP-Calculator since the side wasnt updated since Cata.
http://www.arenajunkies.com/tools/conquest-points-calculator/ 

**Steps to reproduce the problem**:

1. Play some arena and reach a raiting of 2,6k
2. Wait till wednesday 
3. You'll see, that you will get the same cap as a player on 2,2k Raiting

Why is that important to fix: It kinda stops the motivation of players. Right now there is no reason to play higher than 2,2k since there wont be any benefits. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
Smaller brackets yield lower maximum cap. If you compare calculator results, it's also not a big change between, said 2600 and 2900 and while on smaller bracket, it will be even smaller difference in result.

Rating | CAP
-- | --
2200 | 2668
2300 | 2772
2400 | 2848
2500 | 2901
2600 | 2937
2700 | 2963
2800 | 2982
2900 | 2995
