### ISSUE TITLE
[EN][NPC][Borean Tundra] Blending In

### ISSUE THREAD

**Issue by BAndysc** [Atlantiss/BugTracker#999]
After completing one goal (out of three), required aura (from this [spell](http://www.wowhead.com/spell=45614)) disappears making the quest impossible to complete. [Item](http://www.wowhead.com/item=34782), which gives aura, disappears after first use. 

Quest: [Blending In](http://www.wowhead.com/quest=11633/blending-in)

**Comment by aje** [comment]
the quest works.

when the spell disappears, just put off and on the item and the aura is back
