### ISSUE TITLE
[EN][Raid][NPC] Al'ar

### ISSUE THREAD

**Issue by demon034** [Atlantiss/BugTracker#9991]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: So basically if you get to p2 and you wipe, you can't target him

**Current behaviour**: Can't target him

**Expected behaviour**: Should be able to target him

**Steps to reproduce the problem**:

1. Finger up bum
2.  Go to TK
3.  Pull Al'ar and wipe in p2

**Revision**: 5722

**Comment by Piklo** [comment]
should be fixed in [rev5753](https://atlantiss.eu/changelog#rev5753)
