### ISSUE TITLE
Loot From Murozond EoT

### ISSUE THREAD

**Issue by Vilfernan2** [Atlantiss/BugTracker#9992]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Once you use the time clock for the first time you are able to loot the chest without killing the boss (Murozond).

**Current behaviour**: What happens
If you click the chest after the first use of the time clock you get the loot and can leave the instance without killing Murozond

**Expected behaviour**: What should happen instead
The loot should be available after killing Murozond
**Steps to reproduce the problem**:

1. Start the fight
2. Use time clock to reset 
3. Click the chest and it'll give you the loot.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by stanq87** [comment]
try looting the chest after each use of clock, that would be an epic bug

**Comment by poleloa** [comment]
Last time i heard many times about "murozond is bugg" Loot items is not polite.
Same when I was fighting versus him. 
I have defeated murozond but haven't seen loot. The most interesting fact is-When do developers fix it?
Greetings

**Comment by Piklo** [comment]
should be fixed in [rev5826](https://atlantiss.eu/changelog#rev5826)
