### ISSUE TITLE
[EN][Spell][Priest] T13 Shadow 4-set Mastery interaction (or lack thereof)

### ISSUE THREAD

**Issue by Katonetwo** [Atlantiss/BugTracker#9994]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The T13 Shadow 4-set is, in its current state, barely a dps increase (if an increase at all) due to Shadow Orbs generated by it not gaining all the benefits of your Mastery, Shadow Orb Power.

**Current behaviour**: Orbs that were generated by the 4-set give a 20%-ish damage increase to Mind Spike or Mind Blast per Orb, regardless of your mastery rating.  This a bit less than the bonus you would get at base mastery (8) - and naturally, a lot less than at the actual mastery value you have.

The amount of Mastery used in these tests:
![mastery](https://user-images.githubusercontent.com/32794643/38646689-3c6cceae-3de9-11e8-8414-ffbb022b2e0f.jpg)
..which grants us 38% increased damage per Shadow Orb.
![orbdesc](https://user-images.githubusercontent.com/32794643/38646822-d4c3b4f6-3de9-11e8-8e64-65beb9c593b0.jpg)

Base Mind Spike and Mind Blast damage (0 Shadow Orbs):
![basespikes](https://user-images.githubusercontent.com/32794643/38646614-f8bcb1ce-3de8-11e8-8115-cc81be61a027.jpg)![baseblasts](https://user-images.githubusercontent.com/32794643/38646621-fc913a0e-3de8-11e8-96e5-e2550b8fd3ac.jpg)

Mind Spike and Mind Blast damage with 3 Shadow Orbs generated through use of Mind Flay:
![3orbspikes](https://user-images.githubusercontent.com/32794643/38646642-10a1269e-3de9-11e8-902d-271ca1a7b8ae.jpg)![3orbblasts](https://user-images.githubusercontent.com/32794643/38646643-12770178-3de9-11e8-9e9a-67726ee6f0c4.jpg)

Mind Spike and Mind Blast damage with 3 Shadow Orbs generated by Shadowfiend attacks:
![sfiendspikes](https://user-images.githubusercontent.com/32794643/38646670-2b4cfd24-3de9-11e8-92b2-a4d7a2b3760b.jpg)![sfiendblasts](https://user-images.githubusercontent.com/32794643/38646669-29407344-3de9-11e8-9cea-66f3c3ab9468.jpg)

**Expected behaviour**: Shadow Orbs generated by the 4-set should behave like regular Shadow Orbs and increase Mind Spike and Mind Blast damage according to your mastery.

**Steps to reproduce the problem**:

1. Be Shadow Priest
2. Equip T13 Shadow 4-set
3. Locate a dummy, try to burst with your 4-set
4. Notice how you do a grand total of 20k DPS with all your cooldowns at once.

**Revision**: 5722

**Comment by Malylolek** [comment]
Could you test it after 

rev. 5780 Author: Pelekon :: 2018-05-16 14:01
Priest:

Orbs from T13 4p should properly scale with mastery

**Comment by Katonetwo** [comment]
they still behave the same way after rev 5780

**Comment by Bislibur** [comment]
Testing done on rev. 5792.
Unequipped all proc gear. 
Running 18.61 mastery (1902 rating), increasing Mind Spike damage by 37% per Shadow Orb (111% with 3 Orbs).

Mind Spike with no Orbs_ around 8.8k 
Mind Spike with 3 Orbs from Shadowfiend: around 14.1k
Mind Spike with 3 Orbs from Mind Flay: around 18.3k

( 14.1k / 8.8k ) - 1 = ~ 60%
( 18.3k / 8.8k ) -1 = ~ 108%

Thanks for your attention.

**Comment by Jenovas** [comment]
Rev 5801 - Fixed

**Comment by firemagegodx** [comment]
Open, shit still doesn't work.

**Comment by Katonetwo** [comment]
UPDATE: Orbs gained from Shadowy Apparitions work like a charm in rev. 5808, but the ones gained from Shadowfiend attacks still do not scale with Mastery.

**Comment by pelekon** [comment]
fixed
