### ISSUE TITLE
[EN][Quest][Icecrown] The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by suthorian** [Atlantiss/BugTracker#9996]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: you cannot mount Nergeld wich makes the quest broken since the mobs required do not spawn

**Current behaviour**: Nergeld just walks around a littlebit

**Expected behaviour**: What should happen instead : he should stand at the end of the hallway waiting on you to be mounted so he can kill some Vargul with your assistance

**Steps to reproduce the problem**: follow the quest chain all the way to part 10:
1A http://www.wowhead.com/quest=12887/its-all-fun-and-games
1H http://www.wowhead.com/quest=12892/its-all-fun-and-games
2 http://www.wowhead.com/quest=12891/i-have-an-idea-but-first
3 http://www.wowhead.com/quest=12893/free-your-mind
4A http://www.wowhead.com/quest=12896/if-he-cannot-be-turned
4H http://www.wowhead.com/quest=12897/if-he-cannot-be-turned
5A http://www.wowhead.com/quest=12898/the-shadow-vault
5H http://www.wowhead.com/quest=12899/the-shadow-vault
6 http://www.wowhead.com/quest=12938/the-duke
7 http://www.wowhead.com/quest=12955/eliminate-the-competition
8 http://www.wowhead.com/quest=12999/the-bone-witch
9 http://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls
NOTE: You do not need to complete step 9, but you must be on the quest in order to loot http://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant , which starts step 10.
10 http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts

this quest chain continues up to 22 quests total but i cannot test the others currently

here is a video on how the quest should go: https://www.youtube.com/watch?v=PKr2j4T38xI

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) ACore rev. 5734

**Comment by TranceAccount** [comment]
He is missing his npc_spellclick_spell flag in creature_template.
He should only be mountable if you have the quest right?

**Comment by suthorian** [comment]
yes he only with the quest you should be able to ride on his back as doing so would trigger the mobs attacking you

**Comment by TranceAccount** [comment]
Got a fix ready, just needs a little more testing and minor edits in the already available script.

**Comment by TranceAccount** [comment]
The quest should be doable in rev. 5738. Might not be completely blizzlike tho, since one of Nergeld's spell doesn't work.
