### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Ilya1x** [Atlantiss/BugTracker#9999]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

Can't log in.

It says "You have been disconnected from the server" no matter what I type for passward.
It happened after I mistakenly typed wrong code for 2 Factor Authentication.
**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by firemagegodx** [comment]
1. Probably not a bug.
2. Contact a GM at support@atlantiss.eu.
3. If you ever find a proper bug ingame, follow the template provided when you create the topic.
